### ISSUE TITLE
Edit as YAML, and reading from a file by selecting a large file may cause the page to jam

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#100]
**Steps to replicate:**
1. On VM/Image list page, choose one of the items, proceed `Edit as YAML`
2. Click `read from file` and choose a large file
3. After the file is uploaded, click the `show diff` button to compare

**Result:**
After clicking the `show diff` button, the page stuck for a long time
![image](https://user-images.githubusercontent.com/57614736/91825616-14a36900-ec6f-11ea-93e7-fb3f40851109.png)

**Comment by guangbochen** [comment]
let's add restriction to only allows `.yaml` file uploading.

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/93408532-65e66600-f8c7-11ea-80b8-9eef53364507.png)
