### ISSUE TITLE
[BUG] No filtering on Projects/Namespaces page

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1001]
**Describe the bug**
In `Projects/Namespaces` tab, when I try to filter by selecting `All Namespaces`, `Only System Namespaces` or something else I still have the same results. It seems that the filtering is not working at all.

**To Reproduce**
1. Go to `Projects/Namespaces`
2. Select another filter than the default one: list is still the same.

**Expected behavior**
Filter should work.

**Support bundle**
[harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T10-12-41Z.zip](https://github.com/harvester/harvester/files/6763444/harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T10-12-41Z.zip)

**Environment:**
 - Harvester ISO version: master-88f1d22c-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9

**Additional context**
None.

**Comment by WuJun2016** [comment]
@gitlawr    We should add annotation to the namespace to filter the harvester-system namespace

**Comment by guangbochen** [comment]
as per https://github.com/rancher/rancher/issues/34911 discussion, we will follow the following conditions to filtering those system-related namespaces from the UI:
- We maintain a setting SystemNamespaces that has the default system namespaces
- namespaces added dynamically for the fleet for example and they are added to the system project and carry an annotation "management.cattle.io/system-namespace": "true"

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. 

- Showing available namespaces
![image](https://user-images.githubusercontent.com/83787952/135151481-0618d937-14ca-4a2d-b000-a86a3fed5204.png)
- List of VMs in namespaces
![image](https://user-images.githubusercontent.com/83787952/135151595-95f98a14-6e77-45dd-967b-bb42ba9aa498.png)
