### ISSUE TITLE
[BUG] Created namespace appears as User but created project appears as System

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1002]
**Describe the bug**
A new created namespace appears as User namespace, but a new created project appears as a System namespace : is it expected?

**To Reproduce**
1. Create a new namespace in `Projects/Namespaces` as well as a new project
2. Create an image for each new created project/namespace
3. Check with the filter: you can see that the image for the namespace appears as a User namespace where the image for the project appears as a System namespace

**Expected behavior**
Both should appear as a User namespace.

**Support bundle**
[harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T15-24-05Z.zip](https://github.com/harvester/harvester/files/6765210/harvester-supportbundle_e707144b-450c-4130-b3a9-3255c3159c1d_2021-07-05T15-24-05Z.zip)

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9

**Additional context**
None.

**Comment by WuJun2016** [comment]
- In singleVirtualCluster, we don't have the filtering categories of user namespace and system namespace and project namespace.
 single cluster: 
![image](https://user-images.githubusercontent.com/24985926/135403375-70f509e1-ee23-4a41-9edd-7896953c38b6.png)

- In multiVirtualCluster, we have only project namespace as a category.
multi cluster:
![image](https://user-images.githubusercontent.com/24985926/135403316-be0f240d-4622-4fa9-adfb-48d027c8f104.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1002#issuecomment-930887401
