### ISSUE TITLE
[BUG] Cannot choose either volume or vlans not in default namespace

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1003]
**Describe the bug**

**To Reproduce**
1. I created `Volume` and `Vlan` that both are not in `default` namespace.
![volume-list.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/9dd324bf-2f3a-4e45-a352-58a3b9b11e6b)
![network-list.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/43dfb8b8-df12-4528-b21d-4896aa25cc9c)
2. The options only display volumes/vlans in `default` namespace when creating VMs.
![choose-volume.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/6fab6e9c-59a6-4755-a6a4-c52f9dc9bd64)
![choose-network.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/61babd40-2edb-41ca-8694-3770d043c56a)

**Expected behavior**
1. Can choose `Volumes` that are not in `default` namespace.
2. Can choose `Vlans` that are not in `default` namespace.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by ldevulder** [comment]
I tested on version `master-7b0da5d1-head`:
- I created a local namespace called `ldevulder-ns`
- I was able to add a vlan on that created NS, as well as a volume and a Cloud Config template
- I also added an OS image in that NS
- And I was able to create a VM with the WebUI on the same NS and all resources created in `ldevulder-ns` were available
- I also tried to create a VM in the `default` NS with the resources created in `ldevulder-ns`, but in that case I had issue with the vlan: I will open a new bug for this.

So, I wasn't able to reproduce the original issue, seems to be fixed. Could be closed.
