### ISSUE TITLE
[BUG] Harvester API doc not viewable as it expends

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1005]
**Describe the bug**
Harvester API doc is seem to get cutoff and become un-viewable as we drill down the model descriptions.

**To Reproduce**
1. Go to https://docs.harvesterhci.io/v0.3-dev/reference/api/
2. Select 'POST /apis​/kubevirt.io​/v1​/namespaces​/{namespace:[a-z0-9][a-z0-9\-]*}​/virtualmachines'
3. Select 'model' and start drilling down. i.e. click on 'spec*' and you'll notice that the right side of the field descriptions are only partially viewable and the rest got cutoff.  In some cases, the description is not visible at all. I've tried both Firefox and Chrome and got the same result.

**Expected behavior**
All the fields along with their respective descriptions should be viewable and the layoff should be intuitive.

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: v0.3-dev
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): N/A

**Additional context**
![harvester_api_doc_problem](https://user-images.githubusercontent.com/1808417/124686470-0f630c00-de88-11eb-8d79-12dca7f17d3b.png)

**Comment by guangbochen** [comment]
fixed via https://docs.harvesterhci.io/v0.3/reference/api/
![image](https://user-images.githubusercontent.com/4569037/137253456-2b24fcac-5bc9-4f9c-b64c-e1bbd349a3c2.png)
