### ISSUE TITLE
[BUG] 3rd Virtual Machine always Starting, not Running

### ISSUE THREAD

**Issue by insbire** [harvester/harvester#1007]
**Describe the bug**

**To Reproduce**
1. Creat 2 VMs used https://github.com/rancher/k3os/releases/download/v0.20.7-k3s1r0/k3os-amd64.iso, worked fine.
2. From the 3. VM always starting, not running.

**Expected behavior**

**Support bundle**

[harvester-supportbundle_e622d515-edce-4b59-b5c0-c86d3ee2bdcf_2021-07-07T06-49-02Z.zip](https://github.com/harvester/harvester/files/6774996/harvester-supportbundle_e622d515-edce-4b59-b5c0-c86d3ee2bdcf_2021-07-07T06-49-02Z.zip)

**Environment:**
 - Harvester ISO version: Harvester 0.2.0
 - Underlying Infrastructure : Dell PowerEdge R630 E26S001

**Additional context**
<img width="633" alt="2021-07-07-145100" src="https://user-images.githubusercontent.com/86938244/124714026-d7b19e00-df33-11eb-9984-6cd50b2fd2be.png">

**Comment by gitlawr** [comment]
There's no sufficient storage.
Disk size of the single node: 19506000Ki ≈ 20Gi

logs in longhorn manager pod:
```
2021-07-07T06:49:03.375074779Z time="2021-07-07T06:49:03Z" level=error msg="There's no available disk for replica pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4-r-37137fe0, size 10737418240"
2021-07-07T06:49:03.375131306Z time="2021-07-07T06:49:03Z" level=error msg="unable to schedule replica" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=harvester0.2 owner=harvester0.2 replica=pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4-r-37137fe0 shareEndpoint= shareState= state=detached volume=pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4
```

Do you install Harvester on R630 bare metal server or a small VM on top of it?

**Comment by gitlawr** [comment]
We need to improve VM status or messages when disk space is insufficient so that users can easily know the cause.

**Comment by insbire** [comment]
> There's no sufficient storage.
> Disk size of the single node: 19506000Ki ≈ 20Gi
> 
> logs in longhorn manager pod:
> 
> ```
> 2021-07-07T06:49:03.375074779Z time="2021-07-07T06:49:03Z" level=error msg="There's no available disk for replica pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4-r-37137fe0, size 10737418240"
> 2021-07-07T06:49:03.375131306Z time="2021-07-07T06:49:03Z" level=error msg="unable to schedule replica" accessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=harvester0.2 owner=harvester0.2 replica=pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4-r-37137fe0 shareEndpoint= shareState= state=detached volume=pvc-c0ed938c-73b1-4e80-8b19-b6952c116da4
> ```
> 
> Do you install Harvester on R630 bare metal server or a small VM on top of it?

I installed Harvester on bare metal server.
Based on your infos, tried as following:
1. Create 2 VM. on Harvester
<img width="564" alt="01 vm" src="https://user-images.githubusercontent.com/86938244/125020473-7c0a2080-e0ab-11eb-850e-655a214cebb7.png">

2. k3os1 with 10GB storage, running
<img width="560" alt="02 k3os1 volumes" src="https://user-images.githubusercontent.com/86938244/125020484-81676b00-e0ab-11eb-9a5d-e959547c57cb.png">

3. k3os2 with 20GB storage, only starting
<img width="555" alt="03 k3os2 volumes" src="https://user-images.githubusercontent.com/86938244/125020516-9217e100-e0ab-11eb-9ffa-38b505e9b73a.png">
<img width="565" alt="04 k3os2 event" src="https://user-images.githubusercontent.com/86938244/125020526-95ab6800-e0ab-11eb-82e4-9c0b54285f4a.png">
Same issue like before, FailedAttachVolume and FailedMount

[harvester-supportbundle_70c5297d-b371-4178-b58e-7f164d159ec4_2021-07-09T03-49-55Z.zip](https://github.com/harvester/harvester/files/6788595/harvester-supportbundle_70c5297d-b371-4178-b58e-7f164d159ec4_2021-07-09T03-49-55Z.zip)

**Comment by gitlawr** [comment]
Can you check why your node has this limited disk size?

**Comment by insbire** [comment]
> Can you check why your node has this limited disk size?

R U sure it's because of disk size? Just tried 4 VMs with Storage 10G, 20G, 40G and 100G. Nothing changed.
<img width="566" alt="vms" src="https://user-images.githubusercontent.com/86938244/125024807-14a49e80-e0b4-11eb-991f-eaceee0bec32.png">
<img width="561" alt="volumes all" src="https://user-images.githubusercontent.com/86938244/125024819-18382580-e0b4-11eb-9d6d-5a7bfaa43c39.png">



`
<html>
<body>


FailedMount | Pod virt-launcher-k3os2-j588cUnable to attach or mount volumes: unmounted volumes=[cdrom-disk rootdisk], unattached volumes=[ephemeral-disks container-disks hotplug-disks libvirt-runtime sockets cdrom-disk rootdisk]: timed out waiting for the condition
-- | --



</body>
</html>`

I tried to create VM using Ubuntu before, same issue as well. Can U be more specific, which **condition** the system need, any docs about it?

**Comment by gitlawr** [comment]
I meant the disk of the node(host), not VMs. Can you `ssh rancher@<server-ip>` with the admin password you set on installation and run `sudo df -h` there

**Comment by gitlawr** [comment]
I think the cause is that you installed Harvester via BIOS but the disk size is larger than the MBR limit(2TB). (If that's the case)Can you reinstall using UEFI?

**Comment by insbire** [comment]
> I meant the disk of the node(host), not VMs. Can you `ssh rancher@<server-ip>` with the admin password you set on installation and run `sudo df -h` there
<img width="960" alt="屏幕截图 2021-07-09 144727" src="https://user-images.githubusercontent.com/86938244/125036629-cac4b400-e0c5-11eb-8468-eddee9640dab.png">
<img width="960" alt="屏幕截图 2021-07-09 144944" src="https://user-images.githubusercontent.com/86938244/125036649-d021fe80-e0c5-11eb-9c38-82f80b68401d.png">
<img width="960" alt="屏幕截图 2021-07-09 145123" src="https://user-images.githubusercontent.com/86938244/125036663-d3b58580-e0c5-11eb-8d8b-c99dcaafc6d3.png">
<img width="960" alt="屏幕截图 2021-07-09 145444" src="https://user-images.githubusercontent.com/86938244/125036682-d912d000-e0c5-11eb-9a79-2fa9e3767f11.png">

**Comment by insbire** [comment]
> I think the cause is that you installed Harvester via BIOS but the disk size is larger than the MBR limit(2TB). (If that's the case)Can you reinstall using UEFI?

Reinstalled. The BIOS of DELL R630 support UEFI.
![微信图片_20210709161152](https://user-images.githubusercontent.com/86938244/125047416-8808d900-e0d1-11eb-8dde-2fbf8a0201e4.jpg)
And the disk sda 2.2T was already recognized by Harvester.
![微信图片_20210709161203](https://user-images.githubusercontent.com/86938244/125047440-92c36e00-e0d1-11eb-9d36-258ae6588bf6.jpg)

After installation why the storage has only 18.6G？
<img width="565" alt="Hosts" src="https://user-images.githubusercontent.com/86938244/125050321-74ab3d00-e0d4-11eb-9218-6db79833a0f9.png">

**Comment by gitlawr** [comment]
Can you try to provide a remote harvester config like the following during the installation?
https://gist.githubusercontent.com/gitlawr/12d50e8e2833e1952f7bbecb8743b163/raw/f4ce2cd08555a03aec311b030c2690d2c5c96151/force-efi.yaml

By default It creates EFI partitions if `/sys/firmware/efi` is detected. I'm not sure why it misses in this case.

For reference: https://docs.harvesterhci.io/v0.2/install/harvester-configuration/

**Comment by insbire** [comment]
> Can you try to provide a remote harvester config like the following during the installation?
> https://gist.githubusercontent.com/gitlawr/12d50e8e2833e1952f7bbecb8743b163/raw/f4ce2cd08555a03aec311b030c2690d2c5c96151/force-efi.yaml
> 
> By default It creates EFI partitions if `/sys/firmware/efi` is detected. I'm not sure why it misses in this case.
> 
> For reference: https://docs.harvesterhci.io/v0.2/install/harvester-configuration/

I reinstalled Harvester again, did same configuration. It seems normal this time. Confused
<img width="619" alt="Hosts 07-10" src="https://user-images.githubusercontent.com/86938244/125159238-cae9b000-e1a8-11eb-9012-485e8c3e833f.png">
[df -h 2021-7-10.txt](https://github.com/harvester/harvester/files/6795017/df.-h.2021-7-10.txt)

**Comment by guangbochen** [comment]
close due to inactivity and it was resolved per the last comment.
