### ISSUE TITLE
[BUG] Image object does not expose storage class

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1008]
**Describe the bug**
PVC storageClassName is required when creating a VM, and it must match the image's storage class. However, the image
object currently does not expose the storage class (i.e. backingImageStorageClass) after the image is imported.

**To Reproduce**
1. from UI, create an image with an valid image URL
2. after the image is successfully imported, view the image object from 'View in API'

**Expected behavior**
'backingImageStorageClass' field should be visible in the image object.

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): N/A

**Additional context**

**Comment by yasker** [comment]
I am not sure how the storage class name was decided currently when creating the disks based on the image, but we should write it as metadata information in the image status, so other callers can use it as well.

**Comment by ldevulder** [comment]
I checked on the previous master version and the field was not here, as expected. I then tested with the latest master version (`master-84781dcb-head`) and I now see the `storageClassName` field in `View in API` mode:
```
"status": {
  "appliedUrl": "https://download.opensuse.org/distribution/leap/15.3/appliances/openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2",
  "conditions": [
    {
      "error": false,
      "lastUpdateTime": "2021-07-08T09:45:51Z",
      "status": "True",
      "transitioning": false,
      "type": "Initialized"
    }
  ],
  "size": 227497472,
  "storageClassName": "longhorn-image-2g9wz"
}
```

So all looks good.
