### ISSUE TITLE
[BUG] Harvester install crashes when assigning Static IP to join existing cluster.

### ISSUE THREAD

**Issue by nittanygeek** [harvester/harvester#1013]
**Describe the bug**
When trying to join an existing cluster and setting a static IP for the node, the installer will crash.

**To Reproduce**
1. Select 'Join existing Harvester cluster' from the installer
2. Select 'Static' for the network
3. When you type in the static IP address and press Enter, the installer crashes.

**Expected behavior**
I expected that the node would statically set the IP address and continue instead of crashing the installer.

**Support bundle**
NA

**Environment:**
 - Harvester ISO version: 0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  UniFi Application Server (UAS-XG)

**Additional context**
NA

**Comment by guangbochen** [comment]
looks like a similar issue of https://github.com/harvester/harvester/issues/698, caused by small screen resolution

**Comment by nittanygeek** [comment]
> looks like a similar issue of #698, caused by small screen resolution

I think this is precisely the issue.  It drops to the command line.  I found that typing ```exit``` will get me back to the installer, but it then starts over.

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/2937
