### ISSUE TITLE
[FEATURE] Bump longhorn to v1.1.2

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1016]
**Describe the solution you'd like**
Bump longhorn to v1.1.2 so that we can verify the current latest longhorn is fully compatible with the Harvester. 

**Additional context**
related issue https://github.com/harvester/harvester/issues/849

**Comment by guangbochen** [comment]
**Test plan:**
1. verify all the pods in the `longhorn-system` are healthy.
2. verify uploading VM images is working as expected.
3. verify creating VMs using the longhorn storage driver is working as expected.
4. consider verifying other additional VM features that are related to the LH storage driver(better to have those testings covered in the e2e test so we can use the testing framework to help verify those testing cases after the LH dependency bump cc @guangyee  ).

**Comment by noahgildersleeve** [comment]
Tested in `master-6ae8d8ee-head`

- Image creation and backing images
- Backup/restore with NFS
- Basic VM creation tests
- Volume tests
