### ISSUE TITLE
[FEATURE] Harvester CCM & Guest CSI Automatic Integration with RKE2 Provisoner

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1019]
**Is your feature request related to a problem? Please describe.**
Both Harvester CCM & Guest CSI driver should install and configure by default when the user spins up a k8s cluster with the Harvester RKE2 node driver.

dependes on https://github.com/rancher/rancher/issues/33611

**Describe the solution you'd like**
- [x] RKE2 Chart integration
    - [x] Add Harvester CCM chart @yaocw2020 
    - [x] Add Guest CSI driver chart @gitlawr 
 - [x] RKE2 integration @gitlawr 
    - Add Harvester as a `cloud-provider` to the RKE2 [kontainer driver metadata](https://github.com/rancher/kontainer-driver-metadata/blob/78a6b22a0d4bc52fef5d57b707e92c619efe94c3/channels-rke2.yaml#L84) and update the RKE2 [dockerfile integration](https://github.com/rancher/rke2/pull/924/files)
 - [x] Harvester API @yaocw2020 
    - Support generating `kubeconfig` file for the guest k8s cluster based on cluster name and VM namespace
- [x] UI integration: @n313893254 
    - set the default cloud provider to the `harvester`
    - call the imported cluster API to get the generated `kubeconfig` file and set it to the `cloud_provider_config`

Notes: For the external harvester cluster, the user has to copy & paste the `kubeconfig` file manually to the `Cloud Provider Config` in order to use the CCM and guest CSI features.

**Additional context**
https://github.com/harvester/cloud-provider-harvester

**Comment by yaocw2020** [comment]
dependency: https://github.com/harvester/harvester/pull/1061

**Comment by yasker** [comment]
Imported Harvester v0.3.0 cluster with RKE2 built-in cloud provider support has been validated in https://github.com/rancher/dashboard/issues/4208. Guest CSI driver will be validated in https://github.com/harvester/harvester/issues/580 . Close the issue as done.
