### ISSUE TITLE
Names on the delete popup are linked to API UI

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#102]
**Steps to replicate:**
1. On VM/Image/SHH Keys/Template/Volume page, select one or some of the items
2. Proceed a delete action and a delete popup will open, click the name on the popup

**Result:**
The name on popup links to API UI
![image](https://user-images.githubusercontent.com/57614736/91834942-4d493f80-ec7b-11ea-86c4-7fe055e8270e.png)
![image](https://user-images.githubusercontent.com/57614736/91834990-5d611f00-ec7b-11ea-8acd-7e3777e12571.png)

**Comment by DaiYuzeng** [comment]
It's expected to link to API UI, the API page will be opened on new page.

**Comment by guangbochen** [comment]
this is still not working when under the proxy mode.

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/86
