### ISSUE TITLE
[BUG]View Link in the host API not working

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1021]
**Describe the bug**
The view link in the links field fails to return the particular host information

**To Reproduce**
1. Use the view link as specified in links view field of a specific host when 'View In API'
2. The host info is not displayed and it errors out with 'not authorized'

**Expected behavior**
The host info should be displayed for the host in view link

**Support bundle**

**Environment:**
 - Harvester iso version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): IPXE vagrant environment

**Additional context**

**Comment by DaiYuzeng** [comment]
The Host API page seems like be ok on harvester/dashboard.

**Comment by noahgildersleeve** [comment]
Tested in master-3edc82a7-head. Fixed.
