### ISSUE TITLE
[BUG] Handler disconnected of harvester multi-cluster api

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1024]
**Describe the bug**
When visiting the downstream Harvester API via API aggregation from the rancher server, it will return the `handler disconnected` error with the `harvester` prefix API.

**To Reproduce**
1. create a single rancher server
2. importing the harvester cluster to the rancher server
3. visiting the imported harvester API via https://rancher-server-url/k8s/clusters/$cluster-id/v1/harvesterhci.io.virtualmachineimages, it will return `Handler disconnected` error
4. all `/v1/harvester*` related API will return the above error as it was caused by an incorrect router handler.

**Expected behavior**
should be able to visit the harvester API correctly of the downstream cluster.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
![image](https://user-images.githubusercontent.com/4569037/125900453-dca3c5fd-342a-4c46-8d62-739c908cd702.png)
![image](https://user-images.githubusercontent.com/4569037/125900484-a9c158f1-e616-44d8-9922-6dc39cf9d60d.png)

**Comment by gitlawr** [comment]
Workaround: 
```
kubectl edit apiservices.management harvester
```
then change the paths to
```
spec:
  pathPrefixes:
  - /v1/harvester/
  paths:
  - /v1/harvester
```

**Comment by guangbochen** [comment]
**To Test**
- create a single rancher server
- importing the harvester cluster to the rancher server
- visiting the imported harvester API via https://rancher-server-url/k8s/clusters/$cluster-id/v1/harvesterhci.io.virtualmachineimages, it should serve all the `harvester` prefix APIs correctly.

**Comment by ldevulder** [comment]
I used Harvester version `master-bc40fc79-head` and Rancher version `master-861fb92`, I imported the Harvester cluster (with some OS images on it) and I was able to see the Harvester APIs correctly with no error:
![issue#1024-validated](https://user-images.githubusercontent.com/25102165/126764807-b2ed2f38-b414-48ca-86b7-f36068b3dda4.png)

Issue can be closed.
