### ISSUE TITLE
[BUG] When you delete a host and there's less than three hosts the VMs are lost

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1026]
**Describe the bug**

If you delete a host with VMs on it and there's less than three in the cluster it will fail to migrate them to a new host
**To Reproduce**
1. Create a cluster
**Expected behavior**

You should either be prompted to move the VMs, or the migration should complete.
**Support bundle**

[harvester-supportbundle_0b1adc6b-9518-4cb6-8044-4353071f75d7_2021-07-16T21-20-36Z.zip](https://github.com/harvester/harvester/files/6833434/harvester-supportbundle_0b1adc6b-9518-4cb6-8044-4353071f75d7_2021-07-16T21-20-36Z.zip)

**Environment:**
 - Harvester ISO version: master-6ae8d8ee-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with DL160

**Additional context**
![Greenshot 2021-07-16 14 19 53](https://user-images.githubusercontent.com/83787952/126009766-a147ac18-0805-4fa0-96e4-c1be6de3a106.png)
![Greenshot 2021-07-16 14 20 12](https://user-images.githubusercontent.com/83787952/126009767-615d9ea3-1e3c-4316-8fb9-5ec1691d2fe9.png)

**Comment by gitlawr** [comment]
Verified in master-9f917060-head

1. Created 3 node cluster.
2. Create a VM which is scheduled to node-2
3. Delete node-2

Result:
The VM is recreated and running on another node after a period of time
