### ISSUE TITLE
[FEATURE] restore supports restoring to the specified namespace

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1027]
**Is your feature request related to a problem? Please describe.**

Currently, restore only supports restoring to the namespace of the VM that created the backup. It is better to support restoring to any namespace that the user is able to use.
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### Test Plan

**Case 1: Restore VM in another namespace.**
* Create a VM `vm` in namespace `default`.
* Create a file `~/test.txt` with content `test`.
* Create a VMBackup `default-vm-backup` for it.
* Create a new namepsace `new-ns`.
* Create a VMRestore `restore-default-vm-backup-to-new-ns` in `new-ns` namespace based on the VMBackup `default-vm-backup` to create a new VM.
![Screen Shot 2022-02-17 at 5 38 31 PM](https://user-images.githubusercontent.com/4927361/154448078-ac006e07-85c9-4233-a85d-11b1f002b052.png)
* A new VM in `new-ns` namespace should be created. It should have the file `~/test.txt` with content `test`.

**Case 2: Restore VM in the original namespace.**
* Create a VM `vm` in namespace `default`.
* Create a file `~/test.txt` with content `test`.
* Create a VMBackup `default-vm-backup` for it.
* Create a VMRestore `restore-default-vm-backup-to-default-ns` in `default` namespace based on the VMBackup `default-vm-backup` to create a new VM.
* A new VM in `default` namespace should be created. It should have the file `~/test.txt` with content `test`.

**Case 3: Restore to existing VM.**
* Create a VM `vm` in namespace `default`.
* Create a file `~/test.txt` with content `test`.
* Create a VMBackup `default-vm-backup` for it.
* Update the file `~/test.txt` with content `new-test`.
* Create a VMRestore `restore-default-vm-backup` in `default` namespace based on the VMBackup `default-vm-backup` to replace original VM.
* The original VM in `default` namespace should be replaced. It should have the file `~/test.txt` with content `test`.

**Comment by guangbochen** [comment]
currently, this is not supported with restoring the PVC from different namespaced volume snapshot, https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#persistentvolumeclaimspec-v1-core

**Comment by FrankYang0529** [comment]
Currently, we can only restore a PVC from a VolumeSnapshot in the same namespace and [transferring VolumeSnapshot feature](https://github.com/kubernetes/enhancements/pull/2849) is still WIP. So we may need a complicated way to fulfill this feature like the following:

* Create another VolumeSnapshot and VolumeSnapshotContent in another namespace via Backup ([ref](https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-snapshot-support/restore-a-backup-via-csi/#restore-a-backup-that-has-no-associated-volumesnapshot)).
* The `deletionPolicy` of VolumeSnapshotContent must be `Retain` to prevent Backup from being removed when users delete VolumeSnapshot.
* Create PVC in another namespace via the new VolumeSnapshot.
* Create VM in another namespace.

**Comment by FrankYang0529** [comment]
We need to let users choose which namespace to restore a new VM.
![Screen Shot 2022-02-15 at 10 49 27 AM](https://user-images.githubusercontent.com/4927361/153983764-16b71697-2f6f-4e79-98f1-24d1a85d040e.png)

**Comment by WuJun2016** [comment]
Hi,  @FrankYang0529   the frontend pr has been merged, can you help test the feature? If it's ok, please help move it to ready-to-testing， thanks.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-bfd6a8a9-head` (02/21). Close this issue.

### Result 
Pass all three test scenarios 
- [x] Case 1: Restore VM in another namespace.
- [x] Case 2: Restore VM in the original namespace.
- [x] Case 3: Restore to existing VM.


####  Case 1: Restore VM in another namespace. 
Can restore VM to different namespace `new-ns` correctly, have the file ~/test.txt with content `test`.

  ![image](https://user-images.githubusercontent.com/29251855/155276142-659bf33b-dc80-4a7c-9eee-41cbf8b9f856.png)
  
  ![image](https://user-images.githubusercontent.com/29251855/155277190-985c5040-1a96-4b52-98a1-5ed97b4410d8.png)

#### Case 2: Restore VM in the original namespace.
Can restore VM to different namespace `new-ns` correctly, have the file ~/test.txt with content `test`.

  ![image](https://user-images.githubusercontent.com/29251855/155279058-8f5f64b7-f399-4f33-86f8-3bc784c1e4f2.png)
  
  ![image](https://user-images.githubusercontent.com/29251855/155278933-fa159fb7-2683-450c-a8bb-c6be26fd68d9.png)

#### Case 3: Restore to existing VM.
Can restore to original VM on the default namespace and restore the status of vm

  ![image](https://user-images.githubusercontent.com/29251855/155280046-1fe8157d-0151-491a-b7f7-094de735e216.png)
  
  ![image](https://user-images.githubusercontent.com/29251855/155280232-ef4807a9-c5e1-4d6b-b726-ed1a8b21e630.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-bfd6a8a9-head (02/21)

### Verify Steps

1. Create a VM `vm` in namespace `default`.
2. Create a file ~/test.txt with content test.
3. Create a VMBackup `default-vm-backup` for it.
4. Create a new namepsace `new-ns`.
5. Create a VMRestore `restore-default-vm-backup-to-new-ns` in `new-ns` namespace based on the `VMBackup default-vm-backup` to create a new VM.
6. Create a VMBackup `default-vm-backup` for it.
7. Create a VMRestore `restore-default-vm-backup-to-default-ns` in default namespace based on the `VMBackup default-vm-backup` to create a new VM.
8. Update the file ~/test.txt in the original `vm` with content new-test.
9. Create a VMRestore `restore-default-vm-backup` in `default` namespace based on the VMBackup default-vm-backup to `replace` original VM.
