### ISSUE TITLE
[FEATURE] Kubevirt GPU/vGPU Configuration

### ISSUE THREAD

**Issue by kralicky** [harvester/harvester#1029]
Kubevirt has support for provisioning GPUs and other host devices according to the [docs](https://kubevirt.io/user-guide/virtual_machines/host-devices/)

There is also an [existing Nvidia plugin](https://github.com/NVIDIA/kubevirt-gpu-device-plugin) which will discover GPUs and vGPUs on nodes so they can be added to VMs.

It would be great if the Harvester UI could display available GPUs and add the necessary configuration into VirtualMachineInstances.

I've done some experimenting with assigning GPUs to Harvester-provisioned VMs which I documented in this [gist](https://gist.github.com/kralicky/0f9994526eac7ddc1808bcbfea6a8444)

Edit: Include GPU support for VMs and K8s workloads.

**Comment by rebeccazzzz** [comment]
Added a line to the description above: “Include GPU support for VMs and K8s workloads.”

**Comment by ProjectInitiative** [comment]
Adding "hookscripts" that allow a script to run during different phases of the VM lifecycle would be beneficial when dealing with binding, unbinding and cleaning up the VFIO-PCI drivers.

**Comment by WuJun2016** [comment]
Hi,  @tlehman  should this function include UI related changes?  If so, please help to add `require/ui` label.  thanks

**Comment by tlehman** [comment]
The version of this feature we are targeting for release 1.1.0 will be based on #992 and use PCI Passthrough. The driver for your specific GPU will need to be installed in a VM, but the VM will have direct access to the underlying PCI device by using PCI passthrough.

**Comment by tlehman** [comment]
Closing this issue as a duplicate of #992

**Comment by tlehman** [comment]
The vGPU work is being tracked in #2764
