### ISSUE TITLE
[Enhancement] Better instance config descriptions of Harvester RKE1 & RKE2 node driver

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#1030]
**Describe the bug**
When I was testing the new harvester node driver with rancher 2.6 in this [issue](https://github.com/harvester/harvester/issues/861), the process failed when the rancher server tried to ssh into the Harvester VM and then, it was running in a loop:

![rke111](https://user-images.githubusercontent.com/6025636/126337442-32d00202-0b26-4c70-bba6-d803ca7520c7.png)

![rke111112](https://user-images.githubusercontent.com/6025636/126337467-e74355e5-3b69-42f5-b97f-911bc3c09dc6.png)

![rke11113](https://user-images.githubusercontent.com/6025636/126337497-429d6c64-889e-4d91-a808-581d626f1336.png)

The ping worked from the harvester VM to the rancher server.

**To Reproduce**

- launch a new rancher server using the `master-head` image https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher
- importing the downstream Harvester cluster(use master-head ISO) to the rancher server through the rancher dashboard UI
    - Click`Import Existing` and choose Generic
    - fill in an arbitrary cluster name and click Create
    - wait a few seconds(and refresh the page), you will see a Registration tab on the cluster detail page
    - copy the registration command(The second curl --insecure ...|kubectl apply, basically it is for deploying the agent to the downstream harvester cluster), run it against the harvester cluster
    - wait a few seconds and the harvester cluster should be imported and managed by the external Rancher.
- Go to the global settings via the hamburger menu and replace the rancher `ui-index` and `ui-dashboard-index` respectively (Note: this is not required for the official Rancher 2.6 release, currently the dashboard UI PR is not merged yet)
    - ui-index: https://rancher-harvester.s3.ap-southeast-1.amazonaws.com/harvester-node-driver/latest2/index.html
    - ui-dashboard-index:  https://rancher-harvester.s3.ap-southeast-1.amazonaws.com/harvester-node-driver/harvester-node-driver/index.html
 - verify the user is able to spin up the guest k8s cluster with Harvester node driver with RKE1.
    - select create `Harvester cluster` and add a cloud credential by choosing one of the imported Harvester clusters.
![image](https://user-images.githubusercontent.com/4569037/125890367-914a97ac-9bd7-4545-a67e-1b1a1ec5807c.png)
    - config the VM instance options(only cloud image is supported, and VLAN network is required), u specify the k8s config or you can add more node-pools if needed.
 ![image](https://user-images.githubusercontent.com/4569037/125901317-56a64316-8d67-47de-a23d-cf9016e4dd71.png)
    - Click create to spin up the guest k8s cluster and check the status.

**Expected behavior**
The cluster should be ready.

**Support bundle**
[harvester-supportbundle_54a7b4d6-cc17-44c6-9fb4-c7d5f2ed53bd_2021-07-20T14-04-22Z.zip](https://github.com/harvester/harvester/files/6849037/harvester-supportbundle_54a7b4d6-cc17-44c6-9fb4-c7d5f2ed53bd_2021-07-20T14-04-22Z.zip)

**Rancher server's log**
[rancher_rke1_harvester.log](https://github.com/harvester/harvester/files/6849043/rancher_rke1_harvester.log)

**Environment:**
 - Harvester ISO version: master-bc40fc79-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 5 nodes cluster DL360G9

**Additional context**

**Comment by juadk** [comment]
Ok it looks better now, my mistake was with the ssh user field in the node template.
![image](https://user-images.githubusercontent.com/6025636/126472555-0a5299b8-5af5-41bd-98a8-f3e7b0d5b99f.png)
First, I though it was the ssh key created in Harvester as we are using images, network from Harvester.
It works with the ubuntu ssh user.
Maybe a better description is needed there, WDYT?

**Comment by guangbochen** [comment]
That sounds like a reasonable request, @WuJun2016 can we please add the description of both the RKE1 & RKE2 instance config options.

**Comment by n313893254** [comment]
- [x] RKE2
- [x] RKE1

**RKE2 Verify steps**
- Install the latest Rancher
- Import a Harvester cluster
- Go to cluster management and create an RKE2 cluster by Harvester node driver.
- Create a harvester cloud credential
- Check the machine config description (placeholder and tooltip)

**RKE1 Verify steps**
- Install the latest Rancher
- Import a Harvester cluster
- Go to cluster management -> RKE1 Configuration -> Node Templates
- Click the "Add Template" button
- Select Harvester driver and check the "Instance Options"

**Additional Context**
[RKE2 Machine Config]
![image](https://user-images.githubusercontent.com/18737885/141447407-64b23198-119b-4461-beb8-eea0cc91552e.png)

[RKE1 Machine Config]
![image](https://user-images.githubusercontent.com/18737885/141685602-022a5c4c-615d-46c2-b755-548de2d76318.png)

**Comment by TachunLin** [comment]
Verified **fixed** on master-f5bde7fa-head with Rancher v2.6-head. Close this issue.

### Result
A hover tips notification of `SSH user to login with the selected OS image` on

1. Create RKE1 cluster template page
![image](https://user-images.githubusercontent.com/29251855/143222572-716f632f-9f8d-4b31-850d-2cc25cfc65da.png)
2. Create RKE cluster page 
![image](https://user-images.githubusercontent.com/29251855/143222311-84a48ef4-a8a7-44fd-bd3c-ed9cb9d89be8.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-f5bde7fa-head
* Rancher version: v2.6-head 


### Verify Steps

1. Docker install rancher v2.6-head
2. Imported harvester on rancher virtualization management
3. Enable harvester node driver
4. Create harvester cloud credential 
5. Create harvester RKE1 cluster template
6. Create harvester RKE2 cluster
