### ISSUE TITLE
[BUG] RKE2 cluster in pending state with harvester node driver

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#1031]
**Describe the bug**
When I was testing the new harvester node driver with rancher 2.6 in this [issue](https://github.com/harvester/harvester/issues/861), the process failed when the rancher server tried to deploy a RKE2 cluster on top of Harvester.

![image](https://user-images.githubusercontent.com/6025636/126325404-110152b9-1610-4943-abd6-19e63a602344.png)
2 nodes keep pending on "Waiting on probes: calico"

However, all looks good from the cluster (named rke2) view:
![image](https://user-images.githubusercontent.com/6025636/126349851-0050f349-4143-4842-b616-f7092f816506.png)

![rke2-3](https://user-images.githubusercontent.com/6025636/126328339-56a4a4b5-252c-4a80-ada9-b8fc249c5b87.png)

I opened a kubectl shell and looked at the pods status, all looks good too:
```
> kubectl get pods -A
NAMESPACE             NAME                                                              READY   STATUS      RESTARTS   AGE
calico-system         calico-kube-controllers-5f8b57fc77-742vd                          1/1     Running     0          82m
calico-system         calico-node-2hkq6                                                 1/1     Running     0          82m
calico-system         calico-node-l7bwz                                                 1/1     Running     0          78m
calico-system         calico-node-v25gw                                                 1/1     Running     0          76m
calico-system         calico-typha-66b479cdf8-b57mj                                     1/1     Running     0          82m
calico-system         calico-typha-66b479cdf8-nt9xd                                     1/1     Running     1          76m
calico-system         calico-typha-66b479cdf8-xdnkj                                     1/1     Running     1          78m
cattle-fleet-system   fleet-agent-84ccfd47b-6mjn5                                       1/1     Running     0          79m
cattle-system         apply-system-agent-upgrader-on-rke2-pool1-gw6nk-with-3b7f-l5wzm   1/1     Running     0          76m
cattle-system         apply-system-agent-upgrader-on-rke2-pool1-nkjbq-with-3b7f-hg2q8   1/1     Running     0          78m
cattle-system         apply-system-agent-upgrader-on-rke2-pool1-qmtm2-with-3b7f-nrb8b   1/1     Running     0          78m
cattle-system         cattle-cluster-agent-55bbb75957-c92cz                             1/1     Running     0          77m
cattle-system         dashboard-shell-zz8sz                                             2/2     Running     0          48s
cattle-system         system-upgrade-controller-8bbcd68fb-24w2l                         1/1     Running     0          79m
kube-system           etcd-rke2-pool1-gw6nk                                             1/1     Running     0          76m
kube-system           etcd-rke2-pool1-nkjbq                                             1/1     Running     0          77m
kube-system           etcd-rke2-pool1-qmtm2                                             1/1     Running     0          84m
kube-system           helm-install-rke2-calico-crd-fvpw5                                0/1     Completed   0          84m
kube-system           helm-install-rke2-calico-kbf7h                                    0/1     Completed   1          84m
kube-system           helm-install-rke2-coredns-jlcp9                                   0/1     Completed   0          84m
kube-system           helm-install-rke2-ingress-nginx-z5mn8                             0/1     Completed   0          84m
kube-system           helm-install-rke2-kube-proxy-vzcvs                                0/1     Completed   0          84m
kube-system           helm-install-rke2-metrics-server-q9l46                            0/1     Completed   0          84m
kube-system           kube-apiserver-rke2-pool1-gw6nk                                   1/1     Running     0          76m
kube-system           kube-apiserver-rke2-pool1-nkjbq                                   1/1     Running     0          76m
kube-system           kube-apiserver-rke2-pool1-qmtm2                                   1/1     Running     0          84m
kube-system           kube-controller-manager-rke2-pool1-gw6nk                          1/1     Running     0          76m
kube-system           kube-controller-manager-rke2-pool1-nkjbq                          1/1     Running     0          77m
kube-system           kube-controller-manager-rke2-pool1-qmtm2                          1/1     Running     0          84m
kube-system           kube-proxy-r27b6                                                  1/1     Running     0          78m
kube-system           kube-proxy-tx5fd                                                  1/1     Running     0          76m
kube-system           kube-proxy-vxqff                                                  1/1     Running     0          83m
kube-system           kube-scheduler-rke2-pool1-gw6nk                                   1/1     Running     0          76m
kube-system           kube-scheduler-rke2-pool1-nkjbq                                   1/1     Running     0          77m
kube-system           kube-scheduler-rke2-pool1-qmtm2                                   1/1     Running     0          84m
kube-system           rke2-coredns-rke2-coredns-65d668ddf9-g89rh                        1/1     Running     0          83m
kube-system           rke2-ingress-nginx-controller-8gwkl                               1/1     Running     0          80m
kube-system           rke2-ingress-nginx-controller-pxhqz                               1/1     Running     0          76m
kube-system           rke2-ingress-nginx-controller-vfq6s                               1/1     Running     0          75m
kube-system           rke2-metrics-server-6647ffc866-89wx4                              1/1     Running     0          81m
tigera-operator       tigera-operator-db8446457-btmqs                                   1/1     Running     0          83m
```

**To Reproduce**
- launch a new rancher server using the `master-head` image https://rancher.com/docs/rancher/v2.x/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher
- importing the downstream Harvester cluster(use master-head ISO) to the rancher server through the rancher dashboard UI
    - Click`Import Existing` and choose Generic
    - fill in an arbitrary cluster name and click Create
    - wait a few seconds(and refresh the page), you will see a Registration tab on the cluster detail page
    - copy the registration command(The second curl --insecure ...|kubectl apply, basically it is for deploying the agent to the downstream harvester cluster), run it against the harvester cluster
    - wait a few seconds and the harvester cluster should be imported and managed by the external Rancher.
- Go to the global settings via the hamburger menu and replace the rancher `ui-index` and `ui-dashboard-index` respectively (Note: this is not required for the official Rancher 2.6 release, currently the dashboard UI PR is not merged yet)
    - ui-index: https://rancher-harvester.s3.ap-southeast-1.amazonaws.com/harvester-node-driver/latest2/index.html
    - ui-dashboard-index:  https://rancher-harvester.s3.ap-southeast-1.amazonaws.com/harvester-node-driver/harvester-node-driver/index.html
 - verify the user is able to spin up the guest k8s cluster with Harvester node driver with RKE2.
    - select create `Harvester cluster` and add a cloud credential by choosing one of the imported Harvester clusters.
![image](https://user-images.githubusercontent.com/4569037/125890367-914a97ac-9bd7-4545-a67e-1b1a1ec5807c.png)
    - config the VM instance options(only cloud image is supported, and VLAN network is required), u specify the k8s config or you can add more node-pools if needed.
 ![image](https://user-images.githubusercontent.com/4569037/125901317-56a64316-8d67-47de-a23d-cf9016e4dd71.png)
    - Click create to spin up the guest k8s cluster and check the status, it should stay in the provisioning state.

**Expected behavior**
The cluster should be ready as well as all the nodes.

**Support bundle**
[harvester-supportbundle_54a7b4d6-cc17-44c6-9fb4-c7d5f2ed53bd_2021-07-20T12-25-55Z.zip](https://github.com/harvester/harvester/files/6848363/harvester-supportbundle_54a7b4d6-cc17-44c6-9fb4-c7d5f2ed53bd_2021-07-20T12-25-55Z.zip)

**Environment:**
- Harvester ISO version: master-bc40fc79-head
- Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 5 nodes cluster DL360G9

**Additional context**

**Comment by juadk** [comment]
Today, I've tried to reproduce the issue to give more logs but this time, all worked as expected.
The 3 nodes RKE2 cluster is up and running as well as all the pods.
![image](https://user-images.githubusercontent.com/6025636/126485389-841e9de7-62e9-413f-981c-0d48fe412956.png)

**Comment by guangbochen** [comment]
RKE2 is not marked as GA yet and that's part of the Rancher dependency, let's investigate if this can be stably reproduced, otherwise feel free to close it (let's get more env to test this to see if we can reproduce it).

**Comment by juadk** [comment]
I did a second try and everything worked well again.
