### ISSUE TITLE
[BUG] integration test failure at "verify host maintenance mode" step

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1034]
**Describe the bug**
The integration test might fail at the following test:
```
------------------------------
verify host APIs operate via steve API
  verify host maintenance mode
  /go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:42
STEP: enable maintenance mode of the host
STEP: then the node is unschedulable and maintain-status is set
STEP: disable maintenance mode of the host

• Failure [0.040 seconds]
verify host APIs
/go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:18
  operate via steve API
  /go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:20
    verify host maintenance mode [It]
    /go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:42

    failed to post disableMaintenanceMode action, response with 500, Operation cannot be fulfilled on nodes "harvester-control-plane": the object has been modified; please apply your changes to the latest version and try again

    /go/src/github.com/harvester/harvester/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:463

    Full Stack Trace
    github.com/harvester/harvester/tests/integration/api_test.glob..func1.1.3()
        /go/src/github.com/harvester/harvester/tests/integration/api/host_apis_test.go:64 +0x4d4
    github.com/harvester/harvester/tests/integration/api_test.TestAPI(0xc00148a600)
        /go/src/github.com/harvester/harvester/tests/integration/api/suite_test.go:53 +0xee
    testing.tRunner(0xc00148a600, 0x345f160)
        /usr/local/go/src/testing/testing.go:1193 +0xef
    created by testing.(*T).Run
        /usr/local/go/src/testing/testing.go:1238 +0x2b3
------------------------------
```

**To Reproduce**
1. This sometimes happens during the CI tests. Some failed tests:
https://drone-pr.rancher.io/harvester/harvester/1021/1/2
https://drone-pr.rancher.io/harvester/harvester/1039/1/2

**Expected behavior**
The test should pass.

**Comment by w13915984028** [comment]
**Action sequence:**
Tester:
helper.PostAction(nodeObjectAPI, "enableMaintenanceMode")
helper.GetObject(nodeObjectAPI, &retNode)
helper.PostAction(nodeObjectAPI, "disableMaintenanceMode")

Http action:
 h.nodeCache.Get(name)
 toUpdate := node.DeepCopy()
   Prepare data
  h.nodeClient.Update(node)

**Occasional failure:**
`failed to post disableMaintenanceMode action, response with 500, Operation cannot be fulfilled on nodes "harvester-control-plane": the object has been modified; please apply your changes to the latest version and try again`


**Analysis:**
When try “`disableMaintenanceMode`”, the “`toUpdate`” is taken from “`nodeCache.Get(name)`”, when finally `nodeClient.Update(node)`, the “`toUpdate`” has been changed by others (not always), thus the API Server complains `“the object has been modified; please apply your changes to the latest version and try again”`

**To Do:**
Check conflict error, when it happens, get node again via nodeClient, then try updating again.


@guangbochen @bk201 : please also take a look, thanks.

**Comment by guangbochen** [comment]
close in favor of the harvester CI as we didn't encounter a similar issue nowadays.
