### ISSUE TITLE
[BUG] Wrong storage class configured when creating a volume with the Harvester terraform provider

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#1041]
**Describe the bug**
This issue was spotted during the validation of https://github.com/harvester/harvester/issues/634

When I try to create a volume from an image with the Harvester terraform provider, the volume stays in NotReady status forever.
I've tried to debug it a little bit and looks like the storage class is wrong, the terraform provider adds the namespace in the storage class name:

```
hpd8s12 [~]$ kubectl get pvc
NAME                      STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                AGE
ubuntu20-dev-image-disk   Pending                                                                        longhorn-default-ubuntu20   11m
ubuntu20-dev-mount-disk   Bound     pvc-83933329-93e2-4876-955f-9bb0b16287f7   10Gi       RWX            longhorn                    11m
```

```
hpd8s12 [~]$ kubectl get sc
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn (default)   driver.longhorn.io   Delete          Immediate           true                   84m
longhorn-k3os        driver.longhorn.io   Delete          Immediate           true                   12m
longhorn-ubuntu20    driver.longhorn.io   Delete          Immediate           true                   12m
```

From my knowledge, the storage class is not a resource where you can use namespace:
```
kubectl api-resources --namespaced=false --sort-by=name | grep storageclasses
NAME                              SHORTNAMES   APIVERSION                             NAMESPACED   KIND
storageclasses                    sc           storage.k8s.io/v1                      false        StorageClass
```
I'm totally beginner with GO langage but the issue can comes from [here](https://github.com/harvester/terraform-provider-harvester/blob/master/internal/provider/volume/resource_volume_constructor.go#L78-L79)

In my case, I tried to create a new storage class named `longhorn-default-ubuntu 20` and this time, the PVC got the Bound status.

**To Reproduce**
1. Follow the step to configure the harvester terraform provider [here](https://github.com/harvester/harvester/issues/634#issuecomment-884778622)
2. Follow the step to create the images by executing the [image example](https://github.com/harvester/terraform-provider-harvester/blob/master/examples/resources/harvester_image/resource.tf)
3. Create the volumes with the [volume example](https://github.com/harvester/terraform-provider-harvester/blob/master/examples/resources/harvester_volume/resource.tf)
4. The volume `ubuntu20-dev-image-disk` will stay in the NotReady status forever.

**Expected behavior**
The volume should be ready using a correct storage class name.

**Support bundle**
[harvester-supportbundle_58a64e6c-b087-49b5-89d2-6b3196a32355_2021-07-26T13-43-41Z.zip](https://github.com/harvester/harvester/files/6878824/harvester-supportbundle_58a64e6c-b087-49b5-89d2-6b3196a32355_2021-07-26T13-43-41Z.zip)

**Environment:**
 - Harvester ISO version: master-2f810069-head + terraform-provider-harvester v.0.1.0 + Terraform v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 5 nodes cluster DL360 G9

**Additional context**

**Comment by futuretea** [comment]
## To test
Use the recreated release v0.1.0: https://github.com/harvester/terraform-provider-harvester/releases/download/v0.1.0/terraform-provider-harvester-amd64.tar.gz

**Comment by futuretea** [comment]
After reinstall, run `rm .terraform.lock.hcl` before `terraform init`

**Comment by juadk** [comment]
Tested successfully with the last master branch of harvester (master-2f810069-head
) and last release of the terraform provider.
```
hpd12s17 [~]$ kubectl get pvc
NAME                      STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
ubuntu20-dev-image-disk   Bound    pvc-fb85d146-1241-479e-b040-377af43ff234   10Gi       RWX            longhorn-ubuntu20   11m
ubuntu20-dev-mount-disk   Bound    pvc-9b05b07e-f101-4c1f-89ee-7de24e8e3ade   10Gi       RWX            longhorn            11m
```
```
hpd12s17 [~]$ kubectl get sc
NAME                 PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn (default)   driver.longhorn.io   Delete          Immediate           true                   3h48m
longhorn-k3os        driver.longhorn.io   Delete          Immediate           true                   13m
longhorn-ubuntu20    driver.longhorn.io   Delete          Immediate           true                   13m
```
![Screenshot from 2021-07-28 15-45-04](https://user-images.githubusercontent.com/6025636/127333022-f37df2b0-2759-4429-aa58-6b38993098ee.png)
