### ISSUE TITLE
[BUG]Latest Master ISO no longer prompt for password reset on first login

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1043]
**Describe the bug**
Using the latest harvester iso https://releases.rancher.com/harvester/master/harvester-amd64.iso , the harvester UI no longer prompts for password reset on first login. Using username admin and password admin enables you to login.

**To Reproduce**
1. Bring up harvester using latest ISO https://releases.rancher.com/harvester/master/harvester-amd64.iso
2. Try to login to harvester UI

**Expected behavior**
The first login should ask for password reset

**Support bundle**

**Environment:**
 - Harvester ISO version: https://releases.rancher.com/harvester/master/harvester-amd64.iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):ipxe vagrant env

**Additional context**

**Comment by gitlawr** [comment]
After we disable MCM in the embedded rancher, the API `/v3/settings/first-login` now returns 404. We need to call `/v1/management.cattle.io.setting/first-login` instead to check whether it's the first time login.

**Comment by ldevulder** [comment]
I saw that we are not able to change the password of the default `admin` user, as well as not able to create a new user with this `admin` account: is it a side effect of this issue or a new one? If it's a new one I will create a new issue for it, I just want to be sure ;-)

**Comment by guangbochen** [comment]
this is by design in 0.3, we will not promote mult-user management in the single Harvester cluster view, multi-tenant, auth providers, and RBAC will only be supported in the multi-cluster view for now.

**Comment by yasker** [comment]
@chajain Can you help to check if the password reset prompt works in the master?

**Comment by chajain** [comment]
Verfied, Looks good now.
