### ISSUE TITLE
[BUG] Unable to restore backup if the vm is not in default namespace

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1047]
**Describe the bug**

Unable to restore backup if the vm is not in default namespace

**To Reproduce**
1. create a vm in harvester-public namespace
2. take backup
3. use the backup to restore new vm

**Expected behavior**

restore success

**Support bundle**

[harvester-supportbundle_d92ae942-0a8d-4a24-ae0d-67ca3ef638f1_2021-07-28T10-11-48Z.zip](https://github.com/harvester/harvester/files/6892188/harvester-supportbundle_d92ae942-0a8d-4a24-ae0d-67ca3ef638f1_2021-07-28T10-11-48Z.zip)

**Environment:**
 - Harvester ISO version: master-0728.iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

```bash
❯ kubectl get vm -A
NAMESPACE          NAME   AGE   VOLUME
harvester-public   test   35m

❯ kubectl get virtualmachinebackup -A
NAMESPACE          NAME          SOURCE_KIND      SOURCE_NAME   READY_TO_USE   AGE    ERROR
harvester-public   test-backup   VirtualMachine   test          true           5m9s

❯ kubectl get virtualmachinerestores.harvesterhci.io -A
NAMESPACE   NAME                        TARGET_KIND      TARGET_NAME   COMPLETE   AGE     ERROR
default     restore-test-backup-4lw5x   VirtualMachine   test-new      false      4m37s

❯ kubectl -n default describe virtualmachinerestores.harvesterhci.io restore-test-backup-4lw5x
Name:         restore-test-backup-4lw5x
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  harvesterhci.io/v1beta1
Kind:         VirtualMachineRestore
Metadata:
  Creation Timestamp:  2021-07-28T10:00:01Z
  Generate Name:       restore-test-backup-
  Generation:          2
  Managed Fields:
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName:
      f:spec:
        .:
        f:newVM:
        f:target:
          .:
          f:apiGroup:
          f:kind:
          f:name:
        f:virtualMachineBackupName:
      f:status:
        .:
        f:complete:
        f:conditions:
    Manager:         harvester
    Operation:       Update
    Time:            2021-07-28T10:00:01Z
  Resource Version:  24954
  UID:               414aed49-9665-4c10-b98e-430d022cf13c
Spec:
  New VM:  true
  Target:
    API Group:                  kubevirt.io
    Kind:                       VirtualMachine
    Name:                       test-new
  Virtual Machine Backup Name:  test-backup
Status:
  Complete:  false
  Conditions:
    Last Transition Time:  2021-07-28T10:00:01Z
    Message:               failed to find vm backup resource test-backup
    Status:                False
    Type:                  Ready
Events:                    <none>
```

**Comment by ldevulder** [comment]
I tried on version `master-3edc82a7-head`:
- I was able to create, backup and restore a VM on `default` namespace
- I created and successfully backed-up a VM on `harvester-public` namespace
- I tried to restore the VM as a new one on `harvester-public`, the restoration was on the correct namespace this time:
```
hpd12s11 [~]$ kubectl get virtualmachinerestores.harvesterhci.io -A
NAMESPACE          NAME                                   TARGET_KIND      TARGET_NAME         COMPLETE   AGE     ERROR
default            restore-default-vm-01-backup-r67tn     VirtualMachine   default-new-vm-01   true       3h15m   
harvester-public   restore-public-vm-02-backup-01-xqk8d   VirtualMachine   public-new-vm-02    true       2m45s
```
But I had this error message on the webui:
![restore-vm-screen01](https://user-images.githubusercontent.com/25102165/130246700-870179a1-eba5-4e82-b55f-ede935b00e0d.png)
- And after this, each time I tried to restore a VM I had this error:

![restore-vm-screen02](https://user-images.githubusercontent.com/25102165/130247302-474f1674-5e3e-4658-ba57-213068207fe1.png)
- And also on the previously working `default` namespace:

![restore-vm-screen03](https://user-images.githubusercontent.com/25102165/130248055-6391b48d-ec74-4b70-a3a4-1e8e74787c8d.png)

Did I do something wrong? Unfortunately I can't provide a support-bundle, as this feature is broken for now.

**Comment by WuJun2016** [comment]
In the v0.2.0 version, we only support restoring to the default namespace, and now we support restoring to the namespace when the vm was backed up.

Note: Due to the limitation of k8s, we do not support restoring to a different namspace

**Comment by guangbochen** [comment]
restore VM to different namespace will be tracked on the https://github.com/harvester/harvester/issues/1027, for this issue please help to verify restore/replace VM with the same backup namespace should works.

**Comment by ldevulder** [comment]
@guangbochen maybe my explanation wasn't good, but I tried to restore a VM on the same namespace has it was before, here in namespace `harvester-public`. This lead to the issue I described.

**Comment by noahgildersleeve** [comment]
Tested on VM in user namespace in master-f38adc70-head

1. Created file and md5 checksum
2. Made backup
3. Overwrote first file, created new checksum
4. Created new file and md5checksum
5. Created backup
6. Restored to first backup
7. Checked file and md5 checksum
