### ISSUE TITLE
[FEATURE] support bonded network of the Harvester

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1048]
**Is your feature request related to a problem? Please describe.**
Currently, users still need to ssh to the node and create the bond network manually before they can assign it to the VLAN network, also during the ISO installation they can't create a bonded network even if they have multiple NICs.

**Describe the solution you'd like**
- allow users to create a bonded network through the Harvester UI
- allow users to create a bonded network during the ISO instllation

**Describe alternatives you've considered**

**Additional context**
https://github.com/harvester/network-controller-harvester/pull/34

**Comment by janeczku** [comment]
Interface bond configuration is typically something that needs to be done during initial setup as it depends on specific configuration of physical server (cabling) and switch ports.

The primary requirement therefore is to:
- allow users to create a bonded network during the ISO/PXE installation

The ability to manage bonds post-install in the UI would be a secondary requirement.

**Comment by yasker** [comment]
We don't have an environment to validate the bonded nic in our lab currently.

@janeczku Can you help to verify the bonded network works for you?

**Comment by alexdepalex** [comment]
@yasker Can confirm bonding works. We do miss some specific configuration options which are addresses in https://github.com/harvester/harvester/issues/1324

**Comment by yasker** [comment]
Thanks @alexdepalex . I will close this one as validated and track the options enhancement using #1324 .
