### ISSUE TITLE
[Question] how to properly load balance?

### ISSUE THREAD

**Issue by vobo70** [harvester/harvester#1049]
Hello,
I try to test harvester hci as 3 (or 6) node cluster and had one question? How to set up cluster to do a proper HA? Means when I pull out power plug of any node (including master) all VMs will seamless move to another host.
And how many hosts I need to do a proper HA?
(home use only 2 VMs)
Regards
Maciek

**Comment by gitlawr** [comment]
It needs three nodes to form a HA cluster.
The VM failover is a known issue that needs to be addressed: https://github.com/harvester/harvester/issues/913

**Comment by vobo70** [comment]
Seems I asked wrong question. When I have three nodes: node1, node2, node3 IPs xxx.xxx.xxx.11-13, and node1 is master cluster is available on IP .11
When I shut down that node the cluster is not available. How to do that the cluster will be always available on IP .11 or another IP not within cluster let's say .10?
Should I use external LB?
If yes how to configure it?
(draft will be enough)

**Comment by vobo70** [comment]
@gitlawr
Do you know the answer for my last questions?

**Comment by guangbochen** [comment]
If u have >= 3 nodes, the harvester will auto-promote the first 3 nodes as the management node to form a HA cluster, which means u can have one node down tolerance. For the existing 0.2 release, u will need an external LB e.g like the Nginx server to proxy all 3 management node IPs, and in the 0.3 release we are working on the built-in LB feature https://github.com/harvester/harvester/issues/632
