### ISSUE TITLE
Templates page issues

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#105]
- [x] 1. Create a template, users are able to create a new  template by just filling up the template name - Validated
![image](https://user-images.githubusercontent.com/57614736/91842632-fb0e1b80-ec86-11ea-89b8-b83436e0d642.png)

- [x] 2. On the template detail page, template name does not wrap around to fit the screen if its text is too long - Validated
- [x] 3. On the template detail page, seems there is no description displayed on the page? - Validated
- [ ] 4. On the template detail page, is not necessary to have the version dropdown selectable
- [ ] 5. On the template detail page, is not necessary to have the ellipsis button available
![image](https://user-images.githubusercontent.com/57614736/91842903-6ce66500-ec87-11ea-9f94-d0df36477c26.png)

- [ ] 6. On the template detail page, is not necessary to have the checkbox available - No checkbox anymore
![image](https://user-images.githubusercontent.com/57614736/91843642-ad92ae00-ec88-11ea-9e6c-b38fa6cb95c4.png)

- [x] 7. Sort by the state could cause the page to jam - Validated
![image](https://user-images.githubusercontent.com/57614736/91844154-85577f00-ec89-11ea-886b-8a4f6384d567.png)

**Comment by WuJun2016** [comment]
case 4、 case 5 are normal

**Comment by DoNotSayYes** [comment]
Validated
