### ISSUE TITLE
[BUG] You can edit server version in advanced settings

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1050]
**Describe the bug**

You can edit the server version to any arbitrary string
**To Reproduce**
1. Go to advanced in the sidebar
2. Go to settings
3. Edit server-version
4. change it to another string
5. Save
6. Refresh the page
**Expected behavior**

You should not be able to edit the server version
**Support bundle**

[harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-28T19-47-36Z.zip](https://github.com/harvester/harvester/files/6896073/harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-28T19-47-36Z.zip)

**Environment:**
 - Harvester ISO version: master-bc40fc79-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with DL160

**Additional context**
![Greenshot 2021-07-28 12 47 01](https://user-images.githubusercontent.com/83787952/127386654-3870a5ec-d889-4fe7-9cc3-018df0142d0b.png)
![Greenshot 2021-07-28 12 47 12](https://user-images.githubusercontent.com/83787952/127386657-5f634d44-f496-4630-871d-151efc968fd5.png)
![Greenshot 2021-07-28 12 47 22](https://user-images.githubusercontent.com/83787952/127386658-a62d2550-9172-48c9-a76e-c73f2e064881.png)

**Comment by ldevulder** [comment]
I tested on version `master-7b0da5d1-head` and I cannot edit the `server-version` field anymore.

Issue fixed and tested, can be closed.
