### ISSUE TITLE
[Task] Test Air gap with Rancher integration

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1052]
We need to test the air gap support with Rancher integration, make sure not only Harvester works fine in the air gap environment by itself, but the user can also start a Rancher in the air gap environment and complete all the necessary tasks.

**Comment by guangbochen** [comment]
Known issues related to the air-gap env support: cc @noahgildersleeve 
- [x] https://github.com/harvester/harvester/issues/1218
- [x] https://github.com/harvester/harvester/issues/1247
- [x] https://github.com/harvester/harvester/issues/1012

**Comment by guangbochen** [comment]
All known issues are resolved in the `v1.0.0-rc1` release, please help to move on with more air-gap env testings, thanks.

**Comment by TachunLin** [comment]
According to task, we propose to begin the test coverage with the following scenarios

#### Environment Test Scenarios: 

- [x] 1. Rancher and harvester are both under air gap environment within same subnet

- [x] 2. Rancher is under air gap environment while harvester have internet connection, they are located in same subnet

#### Validate point

- Can import harvester from Rancher correctly 
- Can access downstream harvester cluster from Rancher dashboard 
- Can provision at least one node RKE1 cluster to harvester correctly with running status
- Can explore provisioned RKE1 cluster nodes 
- RKE1 cluster VM created running correctly on harvester node
- Can provision at least one node RKE2 cluster to harvester correctly with running status
- Can explore provisioned RKE2 cluster nodes 
- RKE2 cluster VM created running correctly on harvester node

**Comment by TachunLin** [comment]
### Test Scenario 2: PASS
`Rancher is under air gap environment while harvester have internet connection, they are located in same subnet`

#### Test environment
* Rancher: v2.6-head (04520-c0)
* Harvester: master-5d6f3db0-head


- [x] Can import downstream harvester from rancher

- [x] Can access downstream harvester cluster from Rancher dashboard 

- [x] Can provision at least one node RKE1 cluster to harvester correctly with running status

- [x] Can explore provisioned RKE1 cluster nodes

- [x] RKE1 cluster VM created running correctly on harvester node

- [x] Can provision at least one node RKE2 cluster to harvester correctly with running status

- [x] Can explore provisioned RKE2 cluster nodes

- [x] RKE2 cluster VM created running correctly on harvester node

---
* Can import downstream harvester from rancher
  ![image](https://user-images.githubusercontent.com/29251855/145968774-562ba210-5539-47b0-996e-bcb91e118d83.png)

* Can access downstream harvester cluster from Rancher dashboard 
  ![image](https://user-images.githubusercontent.com/29251855/145969769-a1a67d61-aac7-4bd0-9da7-aefdf67294ba.png)

* Can provision at least one node RKE1 cluster to harvester correctly with running status
  ![image](https://user-images.githubusercontent.com/29251855/145972829-d2940e1a-3efa-40d6-8304-03a3f95e9bb9.png)

*  Can explore provisioned RKE1 cluster nodes
  ![image](https://user-images.githubusercontent.com/29251855/145972913-1ec03b6e-1d2b-45d4-b232-6fd8793ff1c2.png)

* RKE1 cluster VM created running correctly on harvester node
  ![image](https://user-images.githubusercontent.com/29251855/145973083-cae2bf75-e412-4ba9-a789-83575f56661d.png)

* Can provision at least one node RKE2 cluster to harvester correctly with running status
  ![image](https://user-images.githubusercontent.com/29251855/145964093-31dbb135-7995-47bc-9baa-d8eeb2b13608.png)

* Can explore provisioned RKE2 cluster nodes
  ![image](https://user-images.githubusercontent.com/29251855/145969139-190fff02-29b3-465b-b8b8-2584d1d8ebc8.png)

* RKE2 cluster VM created running correctly on harvester node
  ![image](https://user-images.githubusercontent.com/29251855/145969381-b2d8f567-2ca3-42a1-ad11-0a68235c4ee6.png)

**Comment by TachunLin** [comment]
### Test Scenario 1: Ongoing
`Rancher and harvester are both under air gap environment within same subnet`

#### Test environment
* Rancher: v2.6-head (77392a6)
* Harvester: master-5d6f3db0-head


- [x] Can import downstream harvester from rancher

- [x] Can access downstream harvester cluster from Rancher dashboard

- [ ] `Failed` to provision RKE2 cluster on harvester with `failed calling webhook`

![image](https://user-images.githubusercontent.com/29251855/146041509-685c27da-ebdc-41d1-8997-ccd3ae0fe0ad.png)

**Comment by guangbochen** [comment]
@TachunLin can u please check the pod status via ssh login to the RKE2 node on the Harvester side, just want to double-check if that is caused by missing some RKE2 air-gap images, thanks.

**Comment by TachunLin** [comment]
@guangbochen, once clicking create button on rancher dashboard, it was hanging for seconds then directly pop out above error message of `Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io"`
Since the RKE2 node vm not yet be created on harvester side, it's not available to check the pod status inside the rke2 node. 

I checked the docker logs on rancher side it has some syncing issue, I think can check the http proxy setting on rancher side to investigate the connectivity to internet through proxy.

**Comment by TachunLin** [comment]
@guangbochen, according to @gitlawr instruction, currently I can `successfully provision` **RKE2 cluster** on both harvester and rancher in air gap environment as **Test scenario 1**

- [x] Can import downstream harvester from rancher

- [x] Can access downstream harvester cluster from Rancher dashboard

- [x] Can provision RKE2 cluster on harvester

![image](https://user-images.githubusercontent.com/29251855/146718123-05ed06e8-3d39-4f82-8ed5-6d8449d403e2.png)

To solve this error we need to fulfill the following criteria 

1. Rancher docker run command requires http proxy arguments 
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 \
-e HTTP_PROXY="http://192.168.0.254:3128" \
-e HTTPS_PROXY="http://192.168.0.254:3128" \
-e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.0.0/16,.svc,.cluster.local,example.com" \
--privileged rancher/rancher:v2.6.3-rc6
```

2. Set the following in Advanced - user data in the create RKE2 cluster page 
```
#cloud-config
apt:
  http_proxy: http://192.168.0.254:3128
  https_proxy: http://192.168.0.254:3128
```
![image](https://user-images.githubusercontent.com/29251855/146680197-d78ef411-7ef8-42ce-b2b8-0036c7dc85c9.png)

3.  In Cluster Configuration - Agent Environment Vars, add the following
```
HTTP_PROXY: http://192.168.0.254:3128
HTTPS_PROXY: http://192.168.0.254:3128
NO_PROXY: localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local
```

![image](https://user-images.githubusercontent.com/29251855/146680338-922b0c6c-ebac-49c7-b4d5-dc68c534689b.png)

**Comment by guangbochen** [comment]
@gitlawr @TachunLin can we please help to document this with an `air-gap` support page on http://127.0.0.1:8000/rancher/rancher-integration/#air-gap-support, thanks

**Comment by TachunLin** [comment]
### Test Scenario 1: PASS
`Rancher and harvester are both under air gap environment within same subnet`

#### Test environment
* Rancher: v2.6.3-rc6
* Harvester: v.1.0.0-rc2


- [x] Can import downstream harvester from rancher

- [x] Can access downstream harvester cluster from Rancher dashboard 

- [x] Can provision at least one node RKE1 cluster to harvester correctly with running status

- [x] Can explore provisioned RKE1 cluster nodes

- [x] RKE1 cluster VM created running correctly on harvester node

- [x] Can provision at least one node RKE2 cluster to harvester correctly with running status

- [x] Can explore provisioned RKE2 cluster nodes

- [x] RKE2 cluster VM created running correctly on harvester node

**Comment by TachunLin** [comment]
### Steps to provision RKE1 cluster in both air gap environment 
1. Clone ipxe example 
2. Enable `offline` feature in settings.yaml
3. Use vagrant pxe example to build an one node harvester
4. Prepare a ubuntu VM and config virtual network `harvester` provided by pxe example 
5. Run docker command to create rancher with http proxy arguments 
```
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 \
-e HTTP_PROXY="http://192.168.0.254:3128" \
-e HTTPS_PROXY="http://192.168.0.254:3128" \
-e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.0.0/16,.svc,.cluster.local,example.com" \
--privileged rancher/rancher:v2.6.3-rc6
```
6.  Import harvester to rancher dashboard 
7. Create cloud credential in rancher
8. Enable virtual network in harvester with `harvester-mgmt` 
9. Create the virtual network vlan1 with id 1 
10. Create RKE1 template
11. Input the following content in user data 
```
#cloud-config
apt:
  http_proxy: http://192.168.0.254:3128
  https_proxy: http://192.168.0.254:3128
write_files:
- path: /etc/environment
  content: |
    HTTP_PROXY="http://192.168.0.254:3128"
    HTTPS_PROXY="http://192.168.0.254:3128"
  append: true
```
![image](https://user-images.githubusercontent.com/29251855/146871485-082f6f12-2c24-4f9b-bdda-3e92ec07e952.png)

12. Expand Engine Options, add the following engine environment 
```
HTTP_PROXY: http://192.168.0.254:3128
HTTPS_PROXY: http://192.168.0.254:3128
NO_PROXY: localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local
```
![image](https://user-images.githubusercontent.com/29251855/146890084-7ac0ea03-e29a-4d06-90b8-03cfe4b99c62.png)

13. Create a RKE1 cluster 
14. Select harvester as cloud provider 

---

### Steps to provision RKE2 cluster in both air gap environment 
1. Follow the same step 1 ~ 9 as RKE1 scenario
2. Create a RKE2 cluster page
3. Add the following content in User data under `Advanced` 
```
#cloud-config
apt:
  http_proxy: http://192.168.0.254:3128
  https_proxy: http://192.168.0.254:3128
```
![image](https://user-images.githubusercontent.com/29251855/146890876-69793b3b-5165-475b-8fa5-a461966cf00e.png)

4. Open `Agent Environment Vars` 
5. Add the following variable and value pair 
```
HTTP_PROXY: http://192.168.0.254:3128
HTTPS_PROXY: http://192.168.0.254:3128
NO_PROXY: localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,.svc,.cluster.local

```
![image](https://user-images.githubusercontent.com/29251855/146891167-5d4fa0d2-014a-4380-b779-c76f1e5d2bc7.png)
6. Click the create button
