### ISSUE TITLE
[BUG]  Error while trying to destroy all created resources with TF provider

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1054]
**Describe the bug**
I successfully created vlan/image/vm on a Harvester cluster with `terraform-provider-harvester` but I ran into an issue when I tried to delete the whole resources at the same time:
```
$terraform destroy -auto-approve
harvester_ssh_key.ldevulder-key: Destroying... [id=default/ldevulder-key]
harvester_clusternetwork.vlan: Destroying... [id=harvester-system/vlan]
harvester_image.sles-jeos-15-sp3: Destroying... [id=default/sles-jeos-15-sp3]
harvester_network.vlan1: Destroying... [id=default/vlan1]
harvester_virtualmachine.leap-vm-test01: Destroying... [id=default/leap-vm-test01]
harvester_volume.leap-15-3-data-disk: Destroying... [id=default/leap-15-3-data-disk]
harvester_image.leap-jeos-15-3: Destroying... [id=default/leap-jeos-15-3]
harvester_network.vlan: Destroying... [id=default/vlan802]
harvester_image.sles-jeos-15-sp3: Destruction complete after 1s
harvester_image.leap-jeos-15-3: Destruction complete after 1s
harvester_ssh_key.ldevulder-key: Destruction complete after 1s
harvester_clusternetwork.vlan: Destruction complete after 1s
harvester_network.vlan1: Destruction complete after 1s
harvester_virtualmachine.leap-vm-test01: Destruction complete after 1s

Error: admission webhook "validator.harvesterhci.io" denied the request: can not delete the volume leap-15-3-data-disk which is currently attached to VMs: default/leap-vm-test01



Error: admission webhook "validator.harvesterhci.io" denied the request: network vlan802 is still used by vm(s): leap-vm-test01
```

I checked on the WebUI and I seen that the VM was in `Terminating` state. After the VM disappears I was able to successfully re-run the destroy command to complete:
```
$ terraform destroy -auto-approve
harvester_network.vlan: Destroying... [id=default/vlan802]
harvester_volume.leap-15-3-data-disk: Destroying... [id=default/leap-15-3-data-disk]
harvester_network.vlan: Destruction complete after 0s
harvester_volume.leap-15-3-data-disk: Destruction complete after 0s

Destroy complete! Resources: 2 destroyed.
```

**To Reproduce**
1. Install latest Harvester and `terraform-provider-harvester`
2. Use the provided TF files to create the resources (init, plan, apply)
3. Check that the resources are up and running on the Harvester cluster
4. Destroy the resources with TF (destroy)
5. You should see the issue!

**Expected behavior**
We should be able to destroy all resources at the same time, like on AWS or GCP.

**Support bundle**
[harvester-supportbundle_846e8e03-8e4f-49f8-8c0b-e254330c8818_2021-07-29T09-50-51Z.zip](https://github.com/harvester/harvester/files/6899602/harvester-supportbundle_846e8e03-8e4f-49f8-8c0b-e254330c8818_2021-07-29T09-50-51Z.zip)

**Environment:**
 - Harvester ISO version: `master-44558714-head`
 - terraform-provider-harvester version: `0.1.0`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9

**Additional context**
Find the attached TAR file that contains the needed TF files to be able to reproduce the issue: [tf-files.tar.gz](https://github.com/harvester/harvester/files/6899580/tf-files.tar.gz)

**Comment by futuretea** [comment]
Thanks, I will update docs and examples to add `depends_on` to vm examples:
more info:
https://learn.hashicorp.com/tutorials/terraform/dependencies

**Comment by ldevulder** [comment]
@futuretea thanks, I tested by adding this in my `vm.tf` file and it works:
```
depends_on = [harvester_image.leap-jeos-15-3, harvester_volume.leap-15-3-data-disk, harvester_network.vlan802]
```

Is there a way to have this done in the implicit way, like in AWS? Could be easier. Otherwise for sure adding this in the docs will be helpful ;-)

**Comment by futuretea** [comment]
@ldevulder  have updated the examples and docs.

**Comment by ldevulder** [comment]
Doc is OK now, issue can be closed. Thx!
