### ISSUE TITLE
[Question] Where can I get the sha to check the ISO

### ISSUE THREAD

**Issue by gtvmsilva** [harvester/harvester#1056]
I've downloaded https://releases.rancher.com/harvester/v0.2.0/harvester-amd64.iso and want to CHECKSUM but I can't find it anywhere in the docs.  Please advise

**Comment by yasker** [comment]
I don't think we have provided it right now. But yes, we should provide the checksums for the image to ensure integrity.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1211 as it will be addressed in that issue.
