### ISSUE TITLE
[BUG] When you click download yaml on hosts page it logs you out

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1057]
**Describe the bug**

When you click download yaml on hosts page it logs you out
**To Reproduce**
1. Navigate to hosts page
2. click triple dot to the right of a host
3. click download yaml
**Expected behavior**

Either the download should complete, or you shouldn't see th eoption
**Support bundle**

[harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-29T22-57-45Z.zip](https://github.com/harvester/harvester/files/6904047/harvester-supportbundle_0278c74f-2ced-4d9a-ae93-7776ce875960_2021-07-29T22-57-45Z.zip)

**Environment:**
 - Harvester ISO version: master-bc40fc79-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal with DL160

**Additional context**

**Comment by WuJun2016** [comment]
Fixed after integration with rancher.

**Comment by ldevulder** [comment]
Tested with latest `master-head` version: I followed the test steps and I was able to download the yaml file. I did this on a 5 nodes cluster and tested the download on all the nodes successfully).

Issue can be closed.
