### ISSUE TITLE
Remove CDI and use PVC APIs for volumes

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1058]
We don't have a dependency on CDI after we import images with the backing image feature.
We can remove CDI and replace the volume APIs with PVCs. It helps to:
1. simplify the stack and reduce support efforts
2. Reduce ISO image size
3. Get rid of the dependency for [volume expansion](https://github.com/harvester/harvester/issues/879) support

**Comment by gitlawr** [comment]
For testing:
1. Verify the CDI component is removed. The following commands should output nothing:
```
kubectl get po -n harvester-system|grep cdi
kubectl get crd|grep cdi
```
2. Verify functionalities around volumes work as before, including:
- Volumes
- VMs
- VM templates
- VM backup and restore

**Comment by noahgildersleeve** [comment]
Will test after next ISO build.

**Comment by yasker** [comment]
It's a refactoring work. Close as done. Feel free to file new issues if observed.
