### ISSUE TITLE
[Enhancement] SSH connectivity via the public IP fails when VM has both mgmt network and public network

### ISSUE THREAD

**Issue by mbelur** [harvester/harvester#1059]
**Describe the bug**
SSH connectivity via the public IP fails when VM has both mgmt network and public network

In our baremetal environment, we have the following setup for the harvester cluster baremetal nodes:
eth0: native vlan - general/management
eth1: tagged vlan - For VMs

When I bring up a VM with only the public vlan network, the SSH connectivity via the public IP works fine.

However, when I bring up the VM with both the default management network (masquerade) and the public network (e2e tests have this scenario), trying to SSH via the public IP does not work.
[6569b57c818d453c9d4f99c7cbb3061c.txt](https://github.com/harvester/harvester/files/6909426/6569b57c818d453c9d4f99c7cbb3061c.txt)

**To Reproduce**
1. Enable vlan in the Settings page specifying the Default Physical NIC (in my case, its eth1)
2. Create a network in the default Namespace providing the name and Vlan ID with L2VlanNetwork type
3. Create a Virtual Machine and in the Networks section, in addition to the 
default managementNetwork, add the network created in step 2.

(Attached is a 6569b57c818d453c9d4f99c7cbb3061c.yaml file for the VM created in my environment )
	

**Expected behavior**
SSH connectivity via the public IP should still work.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HP DL360G9

**Comment by mbelur** [comment]
Support bundle attached
[harvester-supportbundle_0c731a58-5930-4b40-9d5e-5a1aad54842d_2021-07-30T18-32-28Z.zip](https://github.com/harvester/harvester/files/6909440/harvester-supportbundle_0c731a58-5930-4b40-9d5e-5a1aad54842d_2021-07-30T18-32-28Z.zip)

**Comment by noahgildersleeve** [comment]
I tested this also in another environment. It still happened. When you create two networks on different VLANS the first one will work. So 
- if you setup the management network as the first one it will work and the second external one won't route
- If you setup the external VLAN as the first one then it will route. 

It's worth noting that if you setup the external VLAN as the second network you still have internet connectivity. It can pull a DHCP lease, and resolve DNS, but you can't ping it, or SSH into it. This was the network config I used for testing.
```
#cloud-config
version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: dhcp
  - type: physical
    name: eth1
    subnets:
      - type: dhcp
```

**Comment by yaocw2020** [comment]
> harvester-supportbundle_0c731a58-5930-4b40-9d5e-5a1aad54842d_2021-07-30T18-32-28Z.zip

Could you please show me the route in the VM?

**Comment by yaocw2020** [comment]
I set up an ubuntu VM with the management network and VLAN network NICs. It works.
```
➜  ~ ping 172.16.0.65
PING 172.16.0.65 (172.16.0.65): 56 data bytes
64 bytes from 172.16.0.65: icmp_seq=0 ttl=64 time=12.094 ms
64 bytes from 172.16.0.65: icmp_seq=1 ttl=64 time=8.609 ms
64 bytes from 172.16.0.65: icmp_seq=2 ttl=64 time=8.501 ms
^C
--- 172.16.0.65 ping statistics ---
3 packets transmitted, 3 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 8.501/9.735/12.094/1.669 ms
```

```
root@two-nic:/home/ubuntu# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel state UP group default qlen 1000
    link/ether 52:54:00:4e:3c:2f brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 brd 10.0.2.255 scope global dynamic enp1s0
       valid_lft 86311703sec preferred_lft 86311703sec
    inet6 fe80::5054:ff:fe4e:3c2f/64 scope link
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0a:bc:5a:56:67:d7 brd ff:ff:ff:ff:ff:ff
    inet 172.16.0.65/16 brd 172.16.255.255 scope global enp2s0
       valid_lft forever preferred_lft forever
    inet6 fd31:f874:bf29:0:8bc:5aff:fe56:67d7/64 scope global dynamic mngtmpaddr
       valid_lft forever preferred_lft forever
    inet6 fe80::8bc:5aff:fe56:67d7/64 scope link
       valid_lft forever preferred_lft forever
root@two-nic:/home/ubuntu# ip r
default via 172.16.0.1 dev enp2s0
default via 10.0.2.1 dev enp1s0 proto dhcp src 10.0.2.2 metric 100
10.0.2.0/24 dev enp1s0 proto kernel scope link src 10.0.2.2
10.0.2.1 dev enp1s0 proto dhcp scope link src 10.0.2.2 metric 100
172.16.0.0/16 dev enp2s0 proto kernel scope link src 172.16.0.65
```
I guess the problem is related to the default routes. @mbelur @noahgildersleeve

**Comment by mbelur** [comment]
![Uploading publicvlan.png…]()
![Uploading bothmgmt_publicvlan.png…]()

**Comment by guangyee** [comment]
@yaocw2020 in our case, the VM got the IP from DHCP. That's not the problem. The problem is pinging it. In other words, the IP is inaccessible outside of the VM.

**Comment by mbelur** [comment]
I tried to attach some screenshots earlier but looks like it did not go through:

for successful case:
ubuntu@meeraonlypublic:~$ ip r
default via 10.84.103.254 dev enp1s0 proto dhcp src 10.84.103.24 metric 100 
10.84.103.0/24 dev enp1s0 proto kernel scope link src 10.84.103.24 
10.84.103.254 dev enp1s0 proto dhcp scope link src 10.84.103.24 metric 100 


for unsuccessful case: (with opensuse)
meeraboth:~ # ip r
default via 10.0.2.1 dev eth0 proto dhcp 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2 
10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29 

I restarted this virtual instance this morning. After restart, now it shows correctly:

meeraboth:~ # ip r
default via 10.84.103.254 dev eth1 proto dhcp 
10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2 
10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29

**Comment by yaocw2020** [comment]
> I tried to attach some screenshots earlier but looks like it did not go through:
> 
> for successful case:
> ubuntu@meeraonlypublic:~$ ip r
> default via 10.84.103.254 dev enp1s0 proto dhcp src 10.84.103.24 metric 100
> 10.84.103.0/24 dev enp1s0 proto kernel scope link src 10.84.103.24
> 10.84.103.254 dev enp1s0 proto dhcp scope link src 10.84.103.24 metric 100
> 
> for unsuccessful case: (with opensuse)
> meeraboth:~ # ip r
> default via 10.0.2.1 dev eth0 proto dhcp
> 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2
> 10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29
> 
> I restarted this virtual instance this morning. After restart, now it shows correctly:
> 
> meeraboth:~ # ip r
> default via 10.84.103.254 dev eth1 proto dhcp
> 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2
> 10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29

In the successful case, the default route is through the NIC within the VLAN network, while in the unsuccessful case, it's through the NIC within the management NIC. That's clear. Moreover, the choice of the default route NIC depends on how the os manages the network.

**Comment by yaocw2020** [comment]
> @yaocw2020 in our case, the VM got the IP from DHCP. That's not the problem. The problem is pinging it. In other words, the IP is inaccessible outside of the VM.

Please confirm whether the machine you use to ping the VM is in the VLAN network. Or you can set up another VM with the NIC in the VLAN network to ping the previous one.

**Comment by guangyee** [comment]
> > @yaocw2020 in our case, the VM got the IP from DHCP. That's not the problem. The problem is pinging it. In other words, the IP is inaccessible outside of the VM.
> 
> Please confirm whether the machine you use to ping the VM is in the VLAN network. Or you can set up another VM with the NIC in the VLAN network to ping the previous one.

I was trying to ping the VM from within the Harvester node where the VM is running.

**Comment by guangyee** [comment]
> > I tried to attach some screenshots earlier but looks like it did not go through:
> > for successful case:
> > ubuntu@meeraonlypublic:~$ ip r
> > default via 10.84.103.254 dev enp1s0 proto dhcp src 10.84.103.24 metric 100
> > 10.84.103.0/24 dev enp1s0 proto kernel scope link src 10.84.103.24
> > 10.84.103.254 dev enp1s0 proto dhcp scope link src 10.84.103.24 metric 100
> > for unsuccessful case: (with opensuse)
> > meeraboth:~ # ip r
> > default via 10.0.2.1 dev eth0 proto dhcp
> > 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2
> > 10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29
> > I restarted this virtual instance this morning. After restart, now it shows correctly:
> > meeraboth:~ # ip r
> > default via 10.84.103.254 dev eth1 proto dhcp
> > 10.0.2.0/24 dev eth0 proto kernel scope link src 10.0.2.2
> > 10.84.103.0/24 dev eth1 proto kernel scope link src 10.84.103.29
> 
> In the successful case, the default route is through the NIC within the VLAN network, while in the unsuccessful case, it's through the NIC within the management NIC. That's clear. Moreover, the choice of the default route NIC depends on how the os manages the network.

Does this mean we will need to explicitly/manually setup a route for the VLAN from within the Harvester node? If so, is that a reasonable expectation for the customers?

**Comment by noahgildersleeve** [comment]
I'm not sure if the node would be able to ping the VM. However anything on that VLAN should be able to. We aren't really handling routing. It'll be whatever the switch has setup. However there's no guarantee that the connectivity that the node has will route to the VLAN.

**Comment by guangyee** [comment]
> I'm not sure if the node would be able to ping the VM. However anything on that VLAN should be able to. We aren't really handling routing. It'll be whatever the switch has setup. However there's no guarantee that the connectivity that the node has will route to the VLAN.

Yes, you're right. I was expecting Harvester to offer a mechanism to create the route for troubleshooting purposes. I guess that may not be a production requirement.

However, the VM is not pingable from the node where we run the tests. The route exist on that node though.

`10.84.103.0/24 dev eth1.1238 proto kernel scope link src 10.84.103.1`

**Comment by inmanturbo** [comment]
@yaocw2020 this is not just a matter of being able to ping.

I can confirm that if the vm will only have one active network at a time. If a vlan is up, the management network will be down. If the management network is up (on the VM) the vm will be unreachable on the vlan.

In short it is not possible to multi-home the VM, and straddle both an internal and external network, as it were.

Tested v0.02 in a cirros vm on a Dell Poweredge R440 with Ethernet Converged Network Adapter X540-T2:
<table>
<tr ng-repeat-end="" ng-if="config.showRowOnExpand&amp;&amp;config.expandable&amp;&amp;row.expanded" class="advancedrow ng-scope">
                        <td></td>
                        
                        <td colspan="1">
                            <idrac-advanced-table privileges="privileges" config="config.advancedDataConfig" data="row" response="row.advancedDataArray" template-url="config.advancedDataTemplate" on-button-action="onAdvancedRowAction(map,row)" class="ng-isolate-scope"><div ng-include="templateUrl" class="ng-scope"><div class="advancedDataDiv ng-scope">
	<div class="container-fluid">
        <div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="BusNumber" class="ng-scope">BusNumber</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="101">101</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="DataBusWidth" class="ng-scope">DataBusWidth</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="8x or x8">8x or x8</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="Description" class="ng-scope">Description</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="Ethernet Converged Network Adapter X540-T2">Ethernet Converged Network Adapter X540-T2</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="DeviceDescription" class="ng-scope">DeviceDescription</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="NIC in Slot 2 Port 1">NIC in Slot 2 Port 1</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="DeviceNumber" class="ng-scope">DeviceNumber</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="0">0</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="DeviceType" class="ng-scope">DeviceType</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="PCIDevice">PCIDevice</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="FQDD" class="ng-scope">FQDD</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="NIC.Slot.2-1">NIC.Slot.2-1</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="FunctionNumber" class="ng-scope">FunctionNumber</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="0">0</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="InstanceID" class="ng-scope">InstanceID</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="NIC.Slot.2-1">NIC.Slot.2-1</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="LastSystemInventoryTime" class="ng-scope">LastSystemInventoryTime</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="2021-08-23T02:41:46">2021-08-23T02:41:46</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="LastUpdateTime" class="ng-scope">LastUpdateTime</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="2021-01-17T05:26:20">2021-01-17T05:26:20</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="Manufacturer" class="ng-scope">Manufacturer</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="Intel Corporation">Intel Corporation</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="PCIDeviceID" class="ng-scope">PCIDeviceID</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="1528">1528</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="PCISubDeviceID" class="ng-scope">PCISubDeviceID</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="0001">0001</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="PCISubVendorID" class="ng-scope">PCISubVendorID</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="8086">8086</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="PCIVendorID" class="ng-scope">PCIVendorID</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="8086">8086</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="SlotLength" class="ng-scope">SlotLength</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="Short Length">Short Length</div>
        </div><div class="row ng-scope" ng-repeat="property in data.PROPERTY">
            <div class="col-sm-2" style="padding: 0px;"><strong style="float: right;"><span translate="SlotType" class="ng-scope">SlotType</span>:</strong></div>
            <div class="col-sm-10 ng-scope" translate="PCI Express Gen 3 x16">PCI Express Gen 3 x16</div>
        </div>
    </div>
</div></div></idrac-advanced-table>
                        </td>
                    </tr>
</table>

**Comment by yaocw2020** [comment]
Workaround: Add a router by cloud-init manually. 
e.g. The network of hosts in my environment is 172.16.0.0/16, and the gateway for the VLAN 178 is 172.16.178.1, and the NIC in the VM is eth1, so I can add the routing rule in the cloud config user data as below.
```
#cloud-config
bootcmd:
  - ip route add 172.16.0.0/16 via 172.16.178.1 dev eth1
```
@guangyee @mbelur @noahgildersleeve

**Comment by yaocw2020** [comment]
We will add an enhancement to add the routing rule automatically.
Related issue: https://github.com/harvester/harvester/issues/1476

**Comment by guangyee** [comment]
Adding bootcmd to cloud-config does not appear to work. Running `ip r` still showing the old routes.

**Comment by guangyee** [comment]
I still don't understand why adding the route via cloud-config is a viable workaround. In our case, the route works *after rebooting the VM*. The routes inside the VM remained the same. This is still a mystery.

**Comment by yaocw2020** [comment]
> I still don't understand why adding the route via cloud-config is a viable workaround. In our case, the route works _after rebooting the VM_. The routes inside the VM remained the same. This is still a mystery.

We should execute the command `sudo cloud-init clean` in the VM before modifying the cloud-init config, otherwise the new cloud-init config won't take effect.

**Comment by szthanatos** [comment]
Same problem.
When I create a VM with 2 network like this:
![image](https://user-images.githubusercontent.com/3314301/147728950-33d7f8ce-59d0-4cef-babf-8c43b3036c3a.png)

```yaml
# Network Data:
version: 1
config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: dhcp
```

I can't access to the VM with ssh.

`route -n` show:

```bash
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.1        0.0.0.0         UG    100    0        0 enp2s0
0.0.0.0         172.16.70.254   0.0.0.0         UG    100    0        0 enp1s0
10.0.2.0        0.0.0.0         255.255.255.0   U     0      0        0 enp2s0
10.0.2.1        0.0.0.0         255.255.255.255 UH    100    0        0 enp2s0
172.16.70.0     0.0.0.0         255.255.255.0   U     0      0        0 enp1s0
172.16.70.254   0.0.0.0         255.255.255.255 UH    100    0        0 enp1s0
```

So even I set VLAN as my first network, the default route still target to the management network.

I solve the problem with:

```bash
route add -net 0.0.0.0/0 enp1s0
route add -net 0.0.0.0/0 gw 172.16.70.254
```

😞

**Comment by w13915984028** [comment]
> I still don't understand why adding the route via cloud-config is a viable workaround. In our case, the route works _after rebooting the VM_. The routes inside the VM remained the same. This is still a mystery.

---
From analysis, the working or not, depends on the default route in the guest OS side, it is affected by the DHCP processing of both ports, the latter one will set the default route finally.


suppose your ping/ssh starts from the mgmt network, no VLAN, it will first send ARP broadcast,

when guest OS sets default route with mgmt NIC, ping/ssh will work, ARP will be solved first,

when guest OS sets default route with VLAN NIC, ping/ssh will not work, the ARP broadcast will not be flooded into this VLAN/not be answered.

Could you confirm again, the working/not-working VM, has same "routes" ?

---
Another reference:

![image](https://user-images.githubusercontent.com/31133476/148404744-d21ac12b-8bd3-4e38-a0a4-bafea42dedb8.png)

**Comment by yasker** [comment]
Based on the above explanation, it's not a feature or bug. We need to create a knowledge base article for this.

**Comment by tjjh89017** [comment]
related KB PR: https://github.com/harvester/harvesterhci.io/pull/26

**Comment by rebeccazzzz** [comment]
KB article was published: https://harvesterhci.io/kb/multiple-nics-vm-connectivity
