### ISSUE TITLE
harvester crd shortname missing plurals

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#106]
**Description:**
currently, harvester CRD short-name is missing plurals, for example, the user should be able to get virtualmachinetemplates by typing either `vmtemplates` or `vmtemplate`, however `vmtemplates` short-name is not added for now.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/114

**Comment by gitlawr** [comment]
validated
