### ISSUE TITLE
[BUG] `make build-iso` failed with error on master branch

### ISSUE THREAD

**Issue by yeahdongcn** [harvester/harvester#1060]
**Describe the bug**

`make build-iso` failed with the following error.
Once I updated `HARVESTER_INSTALLER_VERSION=v0.1.3` to `HARVESTER_INSTALLER_VERSION=master`, the error is gone.

Question: What is the preferred way to build the whole project?

```
Start building ISO
Successfully packaged chart and saved it to: k3os/images/70-iso/charts/harvester-0.0.0-dev.tgz
Error: unknown command "read" for "yq"
Run 'yq --help' for usage.
FATA[0066] exit status 1                                
make: *** [build-iso] Error 1
```

**To Reproduce**
1. `make build-iso`

**Expected behavior**

`make build-iso` with no error

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/blob/master/scripts/build-iso#L10
