### ISSUE TITLE
[BUG] RBAC menu and Advanced menu did not expand

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1063]
**Describe the bug**

RBAC menu and Advanced menu did not expand

**To Reproduce**
1. Go to Virtualization Management
2. Click a harvester cluster
3. Go to the harvester and click the RBAC menu
4. click add and add a cluster member
5. After saving success, the page will be a cluster member list, but the RBAC menu did not expand.
6. Click the Advanced menu
7. Page goto template menu, but Advanced menu did not expand.

**Expected behavior**

RBAC and Advanced menu will expand as "explore" do.

**Comment by ldevulder** [comment]
I tried to test on version `master-3edc82a7-head`, but I don't have a `RBAC` menu:
![harvester-missing-rbac-menu](https://user-images.githubusercontent.com/25102165/130463190-2d3f681b-daeb-428e-95a5-a5ed69cf6882.png)

So how can I test this? Of course I've enabled the developer options but no change...

**Comment by WuJun2016** [comment]
@ldevulder   Sorry, this needs to be tested in multiple clusters, you need to import the harvester cluster into the rancher cluster。

Currently there is no way to test, you need to wait for this pr  https://github.com/rancher/dashboard/pull/3726 to be merged into rancher, plan to release with rancher 2.6.2

**Comment by ldevulder** [comment]
@WuJun2016 thx for the info.

@DaiYuzeng So maybe better to move back this issue to `Review`?

**Comment by yasker** [comment]
~~@slickwarren can you help to verify this one?~~

Need to reassign due to Caleb is out.

**Comment by gitlawr** [comment]
Verified in Rancher v2.6.1-rc13 with Harvester master-0136b815-head imported

![image](https://user-images.githubusercontent.com/5697937/136646378-6d6c04c6-03fa-400b-9bce-dd3e4bb6e246.png)
