### ISSUE TITLE
[BUG] Host and project/namespace menus are dismissed after add a cluster member

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1064]
**Describe the bug**

Host and project/namespace menus are dismissed after add a cluster member.

Before:
![image](https://user-images.githubusercontent.com/18737885/127844998-3a1b8390-61da-49a9-be36-4107bafbfcab.png)

After:
![image](https://user-images.githubusercontent.com/18737885/127845080-5505159b-ddb6-400f-baf6-e5bb1454a580.png)

**To Reproduce**
1. Go to Visualization management and click a cluster.
2. Go to RBAC and add a cluster member.

**Expected behavior**

Host and project/namespace menus should display in the left menu.

**Additional context**
It also can produce by click cancel on Add cluster member menu

**Comment by ldevulder** [comment]
I tried to test on version `master-3edc82a7-head`, but I don't have a `RBAC` menu:
![harvester-missing-rbac-menu](https://user-images.githubusercontent.com/25102165/130463190-2d3f681b-daeb-428e-95a5-a5ed69cf6882.png)

So how can I test this? Of course I've enabled the developer options but no change...

**Note:** I made the same comment in issue #1063

**Comment by yasker** [comment]
~~@slickwarren can you help to verify this one?~~

Need to reassign due to Caleb is out.

**Comment by yasker** [comment]
This issue seems have been fixed when fixing https://github.com/rancher/dashboard/issues/4299.

**Comment by gitlawr** [comment]
Verified in Rancher v2.6.1-rc13 with Harvester master-0136b815-head imported.
Adding a cluster member does not affect the menus.
![image](https://user-images.githubusercontent.com/5697937/136646560-18821e75-4b9e-4189-bf6b-0e5bc8d3d540.png)
