### ISSUE TITLE
[BUG] Eject CDROM did not work on VM detail page

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1067]
**Describe the bug**

![image](https://user-images.githubusercontent.com/18737885/127982445-8ec0464d-b7c0-462d-be89-d03e5ffa1bf9.png)

**To Reproduce**
1. Go to VM detail page
2. Click the action menu, and then click Eject CDROM
3. Modal does not display on the page

**Expected behavior**

Eject CDROM modal display on the VM detail page.

**Additional context**
Back to VM list the modal display on the list page.

![image](https://user-images.githubusercontent.com/18737885/127982949-d8db0c22-3aef-41e9-931f-0300c4eb80a5.png)

**Comment by noahgildersleeve** [comment]
Tested in master-3edc82a7-head. Fixed.
