### ISSUE TITLE
[Question] Node deletion behavior

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#1069]
Hello, I deleted one node of my 3 nodes cluster and I was surprised that it was came back inside the cluster after simply rebooting it.
From my point of view, I think it's dangerous and a customer may be surprised too. 
My expectation was to completely reinstall the node to add it back to the cluster.
Perhaps we can imagine two kinds of deletions that the user can choose from.

**Comment by yasker** [comment]
I also don't expect the node to rejoin the cluster if the admin decided to delete it. Though I am not sure how we can prevent the node from rejoin use the same token.

**Comment by guangbochen** [comment]
refer to https://docs.rke2.io/install/linux_uninstall/

**Comment by FrankYang0529** [comment]
I can't reproduce the bug in harvester-v0.3.0-rc1. My steps are:

1. Use https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester to create a cluster (3 nodes).
2. Delete harvester-node-2 in Hosts page.
3. Reboot harvester-node-2.
4. Wait for harvester-node-2 reboot done. Check Hosts page or run `kubectl get nodes`. harvester-node-2 is not in the list.

**Comment by yasker** [comment]
Move to v1.0.0 due to cannot reproduce.

**Comment by yasker** [comment]
I also cannot reproduce this issue. The deleted node will stay in `NotReady` state and won't show up in the Harvester UI. RKE2 server is down due it seems lost the IP of the remote node. Close as cannot reproduce.
