### ISSUE TITLE
[FEATURE] Kubeconfig download button

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1072]
**Is your feature request related to a problem? Please describe.**

We need a button in Harvester for downloading the cluster kubeconfig
**Describe the solution you'd like**

There should be a button that downloads the kubeconfig for the kubernetes cluster. **Describe alternatives you've considered**

Currently there is no way other than going into embedded rancher, or SSH into the node. We could also do it via an API call, but if that is the case there should still be a UI option.
**Additional context**

The kubeconfig download button is also currently not working in embedded rancher.  We also should probably restrict this to admins in the user roles.

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Fixed.

**Comment by noahgildersleeve** [comment]
Re-opening. Misunderstood implementation.

**Comment by guangbochen** [comment]
![image](https://user-images.githubusercontent.com/4569037/133730725-1508301e-1989-40b0-95f0-8f6d77c26d76.png)
u should be able to download it from the top navbar and use kubectl to access this cluster e.g `KUBECONFIG=./cluster.yaml kubectl get node`

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head with the steps outlined above.

1. Create a harvester setup with master
2. download kubeconfig from topbar
3. Use kubeconfig to access cluster with yaml with `kubectl get node`

I got an error with the certificate data. Unable to connect to the server: x509: certificate is valid for x.x.x.x, x.x.x.y, x.x.y.y, not y.y.y.y. I took a look and the kubeconfig was different from what was on the node at `/etc/var/rancher/rke2/rke2.yaml`. In the downloaded cubeconfig there isn't anything about `certificate-authority-data`, or `client-certificate-data`

**Comment by gitlawr** [comment]
@noahgildersleeve kubeconfig from the UI is generated per user, so it's different from the one on the node.

In master-1a041d23-head,
- When I access Harvester with https://VIP and download the kubeconfig, it works.
- When I access Harvester with https://node-ip:30443 and download the kubeconfig, it shows the x509 error. The kubeconfig uses the node-ip as ther cluster server endpoint but the IP is not added to certificate SANs.

@WuJun2016 We need to bring back the server-url setting on the first login. The generated kubeconfig will use the consistent server-url once it's set.

**Comment by WuJun2016** [comment]
server-url is set through the backend

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. Kubeconfig download button now includes cert information. Tested with
1. Used `KUBECONFIG` to connect via kubectl with `kubectl get node`
2. Verified that IP was correct with VIP address
3. Downloaded `KUBECONFIG` from VIP address via https and no port
