### ISSUE TITLE
[BUG] Can't create new user in harvester UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1075]
**Describe the bug**[harvester-supportbundle_df06ab7c-75ee-47da-a5e5-bd58ef901fd5_2021-08-04T20-20-41Z.zip](https://github.com/harvester/harvester/files/6934202/harvester-supportbundle_df06ab7c-75ee-47da-a5e5-bd58ef901fd5_2021-08-04T20-20-41Z.zip)
You can't click create after filling in the new user form
**To Reproduce**
1. Log in as admin to harvester
2. Go to users  and authentication then users
3. Add new user
4. Try to hit save
**Expected behavior**

You should be able to create new user
**Support bundle**

[harvester-supportbundle_df06ab7c-75ee-47da-a5e5-bd58ef901fd5_2021-08-04T20-20-41Z.zip](https://github.com/harvester/harvester/files/6934202/harvester-supportbundle_df06ab7c-75ee-47da-a5e5-bd58ef901fd5_2021-08-04T20-20-41Z.zip)**Environment:**
 - Harvester ISO version: master-44558714-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160 Baremetal

**Additional context**
The button is greyed out. This might be as simple as the form not being updated when you confirm the password.
![Greenshot 2021-08-04 13 16 59](https://user-images.githubusercontent.com/83787952/128250148-ecdcb3a2-de60-44c7-8d68-f79287242618.png)

**Comment by lucidd** [comment]
So what i found out so far is that the create button stays disabled because of roles not being set. The roles seem to be handled by the GlobalRoleBindings component which is empty in the ui because it tries to get data for `management.cattle.io.globalrole` but fails when it does not find the schema for it. I don't see any of the requests for schema data containing it either so i guess something is wrong there.

**Comment by guangbochen** [comment]
since we are removing the Harvester user and migrating to the Rancher user mechanism, so creating a user from a single Harvester cluster is no longer supported in the current stage, instead, the user can using the central Rancher to benefits from multi-cluster and central RBAC management.

**Comment by lucidd** [comment]
Ok does it even make sense then to keep this page at all especially once harvester ui is merged with the rancher ui i guess the rancher ui will cover the user management or am i missing something?

**Comment by guangbochen** [comment]
the user page will be removed eventually, we are merging the Harvester UI with the dashboard UI https://github.com/harvester/harvester/issues/923 and the new UI will be updated in the coming days.

**Comment by lucidd** [comment]
i guess in that case we can save the time on this and wait till https://github.com/harvester/harvester/issues/923 is done.

**Comment by noahgildersleeve** [comment]
I'll check it when I'm testing the new user permissions stuff after the merge of #923 .

**Comment by lucidd** [comment]
i just installed master-94bf1714-head and it seems the Users/Authentication menu is already gone there.

**Comment by guangbochen** [comment]
currently, only one admin user will be allowed on the single Harvester cluster, please refer to the [multi-tenant](https://github.com/harvester/harvester/issues/582) feature that will be supported by Rancher v2.6.1+.
