### ISSUE TITLE
[BUG] VMs created in a namespace with quotas cannot run

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1082]
**Describe the bug**

**To Reproduce**
1. Use the `qcow2` image to create a VM in a namespace with quotas
2. The VM cannot run

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
We need to add the `guest` params when creating VMs, `guest` should be always less than `limits`.

    spec:
      domain:
        memory:
          guest: "4G"
        resources:
          limits:
            memory: 4Gi
          requests:
            memory: 4Gi

**Comment by guangbochen** [comment]
close in favor https://github.com/harvester/harvester/issues/1082#issuecomment-896445833
