### ISSUE TITLE
[Question] Hardware assisted virtualization

### ISSUE THREAD

**Issue by vobo70** [harvester/harvester#1083]
Hello,
I have some used laptops (Dell E5540) and I would like to try harvester on them,
so my question is:
does the Intel® Core™ i5-4210U Processor
[https://ark.intel.com/content/www/pl/pl/ark/products/81016/intel-core-i5-4210u-processor-3m-cache-up-to-2-70-ghz.html](url)
supports Hardware assisted virtualization?
intel ARK states:
Intel® Virtualization Technology (VT-x) - Yes
Intel® Virtualization Technology for Directed I/O (VT-d) - No
Intel® VT-x with Extended Page Tables (EPT) - Yes
regards,
Maciek

**Comment by gitlawr** [comment]
VT-x is Intel hardware virtualization. According to the documentation, the answer is yes. You can also check the CPU flags in `/proc/cpuinfo` or run `virt-host-validate` command to check.

**Comment by vobo70** [comment]
Thanks for answer.
