### ISSUE TITLE
[BUG]  Unable to migrate `restore-new` vm twice

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1086]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/129302446-14de9284-2a0b-4aa8-9a5d-4bfb31b7cf7d.png)
![image](https://user-images.githubusercontent.com/15064560/129302457-0c801ec8-3a60-4741-a77d-f8795ef44be2.png)

**To Reproduce**
1. create vm `a`
2. backup vm `a` to `a-bak`
3. restore new `a-bak` to `a-new`
4. migrate `a-new` to othoer node
5. migrate `a-new` to othoer node again

a-new will keep migrating

**Expected behavior**

after migrate twice, `a-new` will become running

**Support bundle**

[harvester-supportbundle_3852db2a-eeea-48fe-8f3b-91898d44e0c2_2021-08-13T03-46-02Z.zip](https://github.com/harvester/harvester/files/6979747/harvester-supportbundle_3852db2a-eeea-48fe-8f3b-91898d44e0c2_2021-08-13T03-46-02Z.zip)

**Environment:**
 - Harvester ISO version:  ISO, server version: master-44558714-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
V0.3.0 version has the same problem

**Comment by guangbochen** [comment]
The LH volumes will reset to `Restore` status to true after the first-time migration, and this will make the volume unmountable on the second time migration.
```
Events:
  Type     Reason                        Age                From                     Message
  ----     ------                        ----               ----                     -------
  Normal   Scheduled                     25s                default-scheduler        Successfully assigned default/virt-launcher-new-vs9wp to bm-se1
  Warning  MultiplePodDisruptionBudgets  24s (x3 over 25s)  controllermanager        Pod "default"/"virt-launcher-new-vs9wp" matches multiple PodDisruptionBudgets.  Chose "kubevirt-disruption-budget-l5sd5" arbitrarily.
  Warning  FailedAttachVolume            23s (x2 over 24s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to attach volume pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514 to bm-se1: volume pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514 is restoring data] from [http://longhorn-backend:9500/v1/volumes/pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514?action=attach]
  Warning  FailedAttachVolume            5s (x4 over 21s)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514 to bm-se1: volume pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514 is restoring data, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-3511b274-fe9c-41fc-9a6c-dae9b5a2c514?action=attach]
```
related to https://github.com/longhorn/longhorn/issues/3210

**Comment by guangbochen** [comment]
should be addressed via https://github.com/longhorn/longhorn/issues/3210 with LH bump to `v1.2.3-rc1`, can we please help to validate it, thanks:

**To Test:**
- create a VM `A`.
- create a VM backup of it.
- restore a new VM of the created backup.
- migrate the VM to another node twice, originally the second one will be failed due to https://github.com/harvester/harvester/issues/1086#issuecomment-957287790

**Comment by lanfon72** [comment]
verified this issue has been fixed.

Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-1e042e04-head**
* **ui-source** Option: **Auto**
* VM ISO: **opensuse-leap-15.3.x86_64-nocloud.qcow2**
* backup-target: **NFS on pxe_server**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. setup backup-target with NFS
3. Create image for VM creation
3. Create VM **a**
4. Add file with some data in VM **a**
5. Backup VM **a** as **a-bak**
6. Restore backup **a-bak** into VM **b**
7. Start VM **b** then check added file should exist with same content
8. Migrate VM **b** to another node, then check added file should exist with same content
9. Migrate VM **b** again, then check added file should exist with same content
