### ISSUE TITLE
[FEATURE] List all available NIC on vlan setting page

### ISSUE THREAD

**Issue by Tu-114-s-undercarriage** [harvester/harvester#1089]
Detect all phycial NIC on each node (maybe can use command `ip` by ansible?), then list these NIC to maybe a combobox. Then administrator could select the NIC by click mouse instead of typing NIC name manully.
Please take this into consideration.

**Comment by guangbochen** [comment]
duplicate and will be track on https://github.com/harvester/harvester/issues/1273
