### ISSUE TITLE
Unable to access dashboard of imported Harvester cluster

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1091]
**To Reproduce**
1. Deploy rancher v2.6.0-rc3 using docker run
2. Deploy Harvester using master iso image
3. import Harvester cluster to the rancher

**Result**
Cluster explorer for the Harvester cluster is not available

**Expected behavior**
Be able to access Harvester dashboard in rancher multi-cluster management.

**Other infos**
It can be resolved by updating the embedded rancher to v2.6.0-rc3.
Ideally, we would expect embedded & central rancher versions to be decoupled

Related Issue:
https://github.com/rancher/rancher/issues/34357

**Comment by noahgildersleeve** [comment]
Harvester version: master-ada6b573-head
Rancher version: deployed from rancher/rancher:latest ver: `0784199`
I installed external rancher on separate VM.

Link is greyed out.
![Greenshot 2021-08-16 09 21 05](https://user-images.githubusercontent.com/83787952/129596951-907de892-dd7d-4c46-9be9-0f8b950f706c.png)

Support Bundle:
[harvester-supportbundle_fe3b515b-4849-4874-b60c-031a8cf37682_2021-08-16T16-21-35Z.zip](https://github.com/harvester/harvester/files/6993892/harvester-supportbundle_fe3b515b-4849-4874-b60c-031a8cf37682_2021-08-16T16-21-35Z.zip)

**Comment by gitlawr** [comment]
We've bumped the embedded rancher in the latest image.
1. With upstream rancher(v2.6.0-rc3) and embedded rancher(v2.6.0-rc3), downstream cluster explorer is available.
2. After updating the rancher image to `master-861fb9208fd59c7f0c5266f087ccf050c1577ead-head` in the same setup, downstream cluster explorer is not available.

Root cause:
When the cluster is imported, cluster-agent will create an aggregation secret.
The embedded rancher uses it to establish the connection to the upstream.
The secret naming is changed between these two versions in https://github.com/rancher/rancher/pull/33830. If we change the secret name in the above case 2, it will work again.

So technically the connection to the downstream cluster depends on both embedded rancher and central rancher versions atm.

**Comment by guangbochen** [comment]
@ibuildthecloud do u think if we can make an improvement of this by decoupling the upstream and embedded rancher dependency version. Ideally, the aggregation secret should only be initiated and managed by the `cluster-agent` of upstream rancher, the embedded Rancher should have no induction of it.

**Comment by guangbochen** [comment]
close as it is confirmed from the Rancher team that we will just keep the secret name to remain unchanged.
