### ISSUE TITLE
[BUG] Cannot create VM in default namespace with a vlan created in another namespace

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1092]
**Describe the bug**
When I was testing the fix for issue #1003, I tried to create a VM with an OS image and a VLAN declared in `ldevulder-ns` namespace instead of the default one. The `disk-0` image was successfully created but not the network:
![vm-creation-issue](https://user-images.githubusercontent.com/25102165/129572466-755e5ea6-2d61-45fc-8232-75640b14f8d1.png)

**To Reproduce**
1. Create a new namespace, for example `test-ns`
2. Create a vlan in `test-ns` namespace
3. Create an OS image in `test-ns` namespace
4. Try to create a VM with these defined resources **BUT** in `default` namespace

**Expected behavior**
The VM should be created and running.

**Support bundle**
[harvester-supportbundle_6a9fc02d-4a8d-4c86-9db1-a45a0dd5070e_2021-08-16T13-43-08Z.zip](https://github.com/harvester/harvester/files/6992798/harvester-supportbundle_6a9fc02d-4a8d-4c86-9db1-a45a0dd5070e_2021-08-16T13-43-08Z.zip)

**Environment:**
 - Harvester ISO version: `master-7b0da5d1-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL160 Gen9

**Additional context**
Found while testing fix for issue #1003.

**Comment by yaocw2020** [comment]
These resources should not be used across namespaces.

**Comment by ldevulder** [comment]
@yaocw2020 ok, so in that case it could be a good idea to show only the resources created in the selected namespace when creating a VM, as it's not possible to know easily on which NS the resource has been created (when creating a VM). And with the fix added for #1003 it's even more complicated ;-)

**Comment by futuretea** [comment]
![image](https://user-images.githubusercontent.com/15064560/129695534-6c17541f-ab59-40a1-b290-56ef3abc937f.png)
http://kubevirt.io/api-reference/v0.40.0/definitions.html#_v1_multusnetwork

**Comment by WuJun2016** [comment]
@ldevulder   VLAN across namespaces will be supported in v0.3.0

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head. Validated as fixed.
