### ISSUE TITLE
[BUG]  When there is only one node in the cluster, there should be no "enablemaintancemode" action

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1093]
**Describe the bug**

When there is only one node in the cluster, there should be no "enablemaintancemode" action

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
Adding a proper validation message is sufficient enough.

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/1093
