### ISSUE TITLE
[BUG] Incorrect Harvester version

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1094]
**Describe the bug**
UI shows incorrect version in the bottom-left corner

**To Reproduce**
1. Deploy Harvester using the latest ISO(master-94bf1714-head)
2. Check the UI

![image](https://user-images.githubusercontent.com/5697937/129696508-4059ae50-e4b3-46bc-b111-b7dc7a5a2ace.png)

**Comment by ldevulder** [comment]
Tested with latest build, the correct version is back:
![fix-issue-1094](https://user-images.githubusercontent.com/25102165/130103839-b75a8367-c2a2-42a1-b8fd-95a785c12329.png)

Issue can be closed.
