### ISSUE TITLE
[BUG] Failed to create VM from a built-in VM template

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1095]
**To Reproduce**
1. Create a VM image.
2. Create a VM, fill in the name, select `Use VM Template`, choose `harvester-public/raw-image-base-template`, select an image.
3. Click `Create`

**Result**
UI stucks in creating
error in the console:
![image](https://user-images.githubusercontent.com/5697937/129697460-afa48c99-cf70-4663-b814-5f5aa6d383c8.png)

**Expected behavior**
Creation succeeds

**Environment:**
 - Harvester ISO version: master-94bf1714-head

**Comment by lucidd** [comment]
i just installed the latest iso master-94bf1714-head and can not reproduce this error. VM gets created and starts as expected using the raw-image-base-template.

**Comment by WuJun2016** [comment]
@lucidd  It has been fixed as the current UI is using a remote `master-head` version.

**Comment by noahgildersleeve** [comment]
Tested in master-3edc82a7-head with raw image and ISO image.
