### ISSUE TITLE
[BUG] create rke1 cluster failed because of node driver get ipv6 ip

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1097]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/129707255-5010d0b1-d9c0-451e-83dd-60473ee240f3.png)

**To Reproduce**
1. install the harvester using the master-head.iso created on 08-17
1. create rke1 cluster by node driver

**Expected behavior**

create rke1 cluster sucessful

**Support bundle**

**Environment:**
 - Harvester ISO version:  master-head ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
verified with Rancher `v2.6.1-harvester2` and Harvester `master-9f917060-head` - `passed`
- spin up a new RKE k8s cluster with the Harvester node driver
- the RKE cluster is up and running successfully and only the IPV4 address is used by the cluster
![image](https://user-images.githubusercontent.com/4569037/136686616-c10298a5-44cd-4130-a09f-bab735988fe6.png)
![image](https://user-images.githubusercontent.com/4569037/136686621-4bfb2d95-fd2f-4875-87ca-fa97eeb3117e.png)
