### ISSUE TITLE
add rancher vm ui

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#11]
add rancher VM UI with the following scope
- [x] add image management page that allows user to view, upload and edit OS images
- [x] add ssh-key management page that allows user to view, create and edit ssh keys
- [x] add VM listing/view detail page
- [x] add a creating page of VM
- [x] add PV/PVC management page
- [x] add VM template page
- [x] add Graphical Console (VNC)

**Comment by jkim711** [comment]
My company would be interested in the feature as well. 
Can  you share us some updates on these types of development?

**Comment by yasker** [comment]
@jkim711 We're still in the very early stage of Harvester (the new name and new architecture) development. The target is deploying VMs with Kubernetes and allow interaction between the VMs and PODs. We will have more details when we're ready to announce the product.

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui as the above pages are all added for now.
