### ISSUE TITLE
[BUG] There's no support bundle link in footer

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1101]
**Describe the bug**

There's no link to create support bundle in the footer
**To Reproduce**
1. Login to harvester 
2. Check footer
**Expected behavior**

There should be a link to create support bundle
**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
This might have just moved with the UI refactor

**Comment by guangbochen** [comment]
![image](https://user-images.githubusercontent.com/4569037/131871347-ea4af451-12c5-47d0-8061-4b7d72f74a48.png)
![image](https://user-images.githubusercontent.com/4569037/131871440-3b2b7ea0-df5a-4e2e-8758-891a6535c3ed.png)

**Comment by noahgildersleeve** [comment]
Tested in `master-c4584348-head`. Verified that link is in new place in support.
