### ISSUE TITLE
[BUG] Settings link in networks doesn't work

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1102]
**Describe the bug**

If you don't have a VLAN added to the harvester cluste you get a link when going to the networks page. The link is broken
**To Reproduce**
1. Navigate to networks in settings
2. Click the settings link
**Expected behavior**

It should take you to the advanced settings vlan section of settings
**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
It looks like the relative URL isn't correct. 
![Greenshot 2021-08-17 15 03 07](https://user-images.githubusercontent.com/83787952/129806874-1bcf14de-68f9-4a81-9460-2dfe4f425331.png)
![Greenshot_2021-08-17_15_03_21](https://user-images.githubusercontent.com/83787952/129806879-5e8e6727-5228-4edd-bdc9-ad4946e0a258.jpg)

**Comment by guangbochen** [comment]
caused by https://github.com/harvester/harvester/issues/1096

**Comment by guangbochen** [comment]
should be addressed via https://github.com/harvester/harvester/pull/1098, and the network CRD is updated to the non-namespaced scope via https://github.com/harvester/network-controller-harvester/commit/c68dcf51f5fd09625640a4c219aff6a1869941d5

**Comment by ldevulder** [comment]
Tested with latest `master-head` build: the link (https://<harvester-master>:30443/dashboard/c/local/virtual/network.harvesterhci.io.clusternetwork/vlan?mode=edit) is working again.

This issue can be closed.
