### ISSUE TITLE
[BUG] No VLAN settings for setting the vlan interface

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1103]
**Describe the bug**

There's no option to define the VLAN interface in advanced settings
**To Reproduce**
1. Navigate to advanced settings
2. 
**Expected behavior**

There should be an option to set the default interface for VLAN in settings.
**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
There was an option before the UI merge

**Comment by guangyee** [comment]
Also, we are seeing e2e test failures in networking area due to  `/apis/network.harvesterhci.io/v1beta1/namespaces/harvester-system/clusternetworks/vlan` returning HTTP 404.

**Comment by guangbochen** [comment]
related to https://github.com/harvester/harvester/issues/1096

**Comment by guangbochen** [comment]
should be addressed via https://github.com/harvester/harvester/pull/1098, and the network CRD is updated to the non-namespaced scope via https://github.com/harvester/network-controller-harvester/commit/c68dcf51f5fd09625640a4c219aff6a1869941d5

**Comment by ldevulder** [comment]
I had to add a VLAN interface to validate #1096 and #807: no issue on that screen, issue can be closed.
