### ISSUE TITLE
[BUG] Use a cloud credential created form rke1 ui to create a rke2 cluster, unable to select namespace, image and network

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1105]
**Describe the bug**

**To Reproduce**
1. create a cloud credential created form rke1 node template ui

![image](https://user-images.githubusercontent.com/15064560/129847410-0821a87f-d739-4d13-9c02-8d8b79db4f08.png)
![image](https://user-images.githubusercontent.com/15064560/129847479-e60fa11e-66be-40a0-bed4-2d8dd4ce0452.png)
![image](https://user-images.githubusercontent.com/15064560/129847371-2e341e05-77e9-4ee8-bd69-810f22add888.png)

2. use the created cloud credential to create rke2 cluster by harvester node driver
![image](https://user-images.githubusercontent.com/15064560/129847518-11ace960-85e3-4ffe-81b2-30111deb647e.png)
![image](https://user-images.githubusercontent.com/15064560/129832702-31231531-8ce6-4c79-a2ca-2166cb3a52b4.png)

**Expected behavior**

Users are able to select namespace, image and network during create rke2 cluster by harvester node driver

**Support bundle**

**Environment:**
 - Harvester ISO version:   rancher 2.6.0-rc3 + harvester master-head iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
fix it by change ui-dashboard-index to https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/cloud/index.html

**Comment by noahgildersleeve** [comment]
Tested with master-f38adc70-head and Rancher v2.6.0-head.
- Created cloud credentials via UI with RKE1 cluster
- Selected cloud credentials from RKE2 cluster c
![Greenshot_2021-09-28_12_54_25](https://user-images.githubusercontent.com/83787952/135156762-a8961952-a79f-40d8-aff4-3ba2522e9422.jpg)
reation
