### ISSUE TITLE
[BUG] Setting password on install loops

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1110]
**Describe the bug**

When you are doing your initial setup you get prompted to use the bootstrap password and set your password. Then it goes to inputting your password. This loops. You can get out of it by manually changing the URL
**To Reproduce**
1. Deploy a new harvester cluster
2. Navigate to the dashboard
3. Set password
4. Login
**Expected behavior**

After setting password you should either be logged in, or directed to login page where you can log in
**Support bundle**

Support bundle is currently missing do to other bug

**Environment:**
 - Harvester ISO version: master-3edc82a7-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): PowerEdge DL160
**Additional context**
![bootstrap password error](https://user-images.githubusercontent.com/83787952/130121323-49feb595-1530-405c-96fd-ecdd1d61e5ec.gif)

**Comment by lucidd** [comment]
i was just trying to reproduce this but on a fresh install master-72b5a35f-head. After the initial screen to put in the passwords it goes directly to the dashboard for me. Could it be already fixed?

**Comment by noahgildersleeve** [comment]
I'll retest with the new version.

**Comment by noahgildersleeve** [comment]
I tested with master-72b5a35f-head. It also seems resolved to me. I think we can close this.
