### ISSUE TITLE
[Question] is PCIE passthrough supported? Or will it be?

### ISSUE THREAD

**Issue by JonasKaber** [harvester/harvester#1112]
Is there a possibility with Harvester to assign a graphics card to a VM using PCIE passthrough? To enable application scenarios like cloud gaming.

**Comment by gitlawr** [comment]
It is tracked in https://github.com/harvester/harvester/issues/1029

**Comment by tlehman** [comment]
It has been supported since release 1.1.0, here are the docs: https://docs.harvesterhci.io/v1.1/advanced/pcidevices
