### ISSUE TITLE
Task: Switch support bundle to use the new `support-bundle-kit`

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1114]
https://github.com/rancher/support-bundle-kit

**Comment by guangbochen** [comment]
related to the newOS change https://github.com/harvester/harvester-installer/pull/93, will need to make sure the new support bundle kit works with RKE2 using journals, additionally would prefer to make the supported k8s provider configurable e.g like `k8s-provider: rke2/k3s/etc.`

**Comment by guangbochen** [comment]
close in favor of `master-48c97ea7-head`, the support-bundle was updated to `rancher/support-bundle-kit:v0.0.3`
```
ks get settings support-bundle-image -oyaml
apiVersion: harvesterhci.io/v1beta1
default: rancher/support-bundle-kit:v0.0.3
kind: Setting
metadata:
  creationTimestamp: "2021-09-26T04:30:37Z"
  generation: 1
  name: support-bundle-image
  resourceVersion: "5354"
  uid: ce67f380-e2f8-4015-b169-9f8c2ee7646f
status: {}
```
