### ISSUE TITLE
[BUG] Installer shows rancher dashboard not Harvester Dashboard

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1121]
**Describe the bug**

When you run an install with the new master ISO it takes you to the rancher dashboard after install not the harvester dashboard
**To Reproduce**
1. Run the installer
2. Navigate to the management URL
**Expected behavior**

1. It should take you to the harvester dashboard
**Support bundle**

**Environment:**
 - Harvester ISO version: master 8-25-21
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
This might be related to the OS changes that were recently merged in. I'm pretty sure this was working yesterday with the master build. You can't seem to access the harvester dashboard anywhere. Also the looping installer password issue is back with this.
![Greenshot 2021-08-25 11 18 11](https://user-images.githubusercontent.com/83787952/130844417-accb44e8-6f85-4ffb-8636-f767e840dee1.png)

**Comment by ldevulder** [comment]
This seems to be fixed in version `master-eea67886-head`.

**Comment by noahgildersleeve** [comment]
I also verified in `master-d25964a2-head`. Issue seems resolved.

**Comment by guangbochen** [comment]
close in favor of above verification
