### ISSUE TITLE
[BUG] Harvester doesn't install on build from August 26 2021

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1124]
**Describe the bug**
Harvester installer stuck on this screen during installation:
![harvester_cos_version_installation_fails](https://user-images.githubusercontent.com/25102165/130942270-7a853695-4fc8-4754-85fc-bb6d311e4a6f.png)

**To Reproduce**
1. Start the Installer, answer the first questions and wait for the issue

**Expected behavior**
Harvester installed.

**Support bundle**
Cannot be generated.

**Environment:**
 - Harvester ISO version: ISO build from August 26 2021 (I don't know the exact version, maybe the one generated from commit eea67886?)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): tested on HP ProLient DL160 Gen9 and Qemu VM

**Additional context**
Related to the recent OS changes? I saw that the OS image is now generated with cOS.

**Comment by bk201** [comment]
Could you provide the output of `lsblk`? Thanks!

**Comment by ldevulder** [comment]
> Could you provide the output of `lsblk`? Thanks!

Of course:
```
ancher:~ # lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0 461.5M  1 loop /run/rootfsbase
sda      8:0    0    20G  0 disk 
├─sda1   8:1    0    47M  0 part 
└─sda2   8:2    0    14G  0 part 
sr0     11:0    1     3G  0 rom  /run/initramfs/live
```

**Comment by bk201** [comment]
The new OS disk has the following partition layout (non-EFI system):

| Partition ID |      Label     |          Size          |
|:------------:|:--------------:|:----------------------:|
|       0      | COS_OEM        |                    50M |
|       1      | COS_STATE      |                    15G |
|       2      | COS_RECOVERY   |                     8G |
|       3      | COS_PERSISTENT | all remaining capacity |

The first 3 partitions are in fixed sizes.
The last one is for persistent data. In my new installed system, the used space is 17G.
I'll recommend at least allocate 50G for the install disk (for testing purposes).

**Comment by ldevulder** [comment]
@bk201 thx, it's better with an install disk of 60GB. I will do some tests to find the minimal size needed, could be useful to document this.

**Comment by ldevulder** [comment]
@bk201 I've did more tests and I'm able to install the latest build on a 35GB disk, and the status is `Ready`.

**Comment by bk201** [comment]
Thanks for the testing. We have a [recommended](https://docs.harvesterhci.io/v0.2/#hardware-requirements) value in the doc. It would also be nice we can add some checks in the installer if the node doesn't meet the recommended spec. I created an issue to track this: https://github.com/harvester/harvester/issues/1154

**Comment by guangbochen** [comment]
close as this issue is resolved by using the correct disk size, an enhancement from the installer will be tracked on https://github.com/harvester/harvester/issues/1154.
