### ISSUE TITLE
[BUG] Fail to start Harvester cluster if the entered token is in number

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1125]
**Describe the bug**
By specifying a token in number (e.g. `12345`) in the installer, the cluster state stays at `"Setting up harvester"` after reboot.

**To Reproduce**
1. Install harvester with token `12345`.

**Expected behavior**
The cluster should start.

**Support bundle**

**Environment:**
 - Harvester ISO version: master ISO. 2021 Aug. 27.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VM

**Additional context**
Rancherd log:

```
loading config from /etc/rancher/rancherd/config.yaml: json: cannot unmarshal number into Go struct field Config.token of type string
```

**Comment by noahgildersleeve** [comment]
tested in master-8afedf0a-head. Fixed.
