### ISSUE TITLE
[BUG] kubectl cann't load the right kubeconfig

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1126]
**Describe the bug**

```
bm-harv4:~ # kubectl get ndoes
W0827 06:48:41.636258   14451 loader.go:221] Config not found: /etc/rancher/k3s/k3s.yaml
The connection to the server localhost:8080 was refused - did you specify the right host or port?
```
**To Reproduce**
1. Connect the host with ssh.
2. Execute `kubectl get nodes`

**Expected behavior**

kubectl can be used normally.

**Support bundle**

**Environment:**
 - Harvester ISO version: master ISO. 2021 Aug. 25.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ISO

**Additional context**

**Comment by bk201** [comment]
This is supposed to be fixed in https://github.com/harvester/os2/pull/6
Could you check if it's resolved in the latest master ISO? Thanks!

**Comment by yaocw2020** [comment]
It's resolved in the 08-27 master-head ISO.
```
~# kubectl get nodes
NAME   STATUS   ROLES                       AGE    VERSION
wj     Ready    control-plane,etcd,master   115m   v1.21.3+rke2r2
```
