### ISSUE TITLE
[BUG] Use the downloaded kubeconfig to connect to the cluster, display the certificate error

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1131]
**Describe the bug**

Use the downloaded kubeconfig to connect to the cluster, display the certificate error

**To Reproduce**
1. Download the kubeconfig file through the header menu
2. Use this configuration to connect to the cluster

![image](https://user-images.githubusercontent.com/24985926/131312315-5f2f4775-1bff-4907-b09e-bb0d17a118f2.png)

**Expected behavior**

Can connect to the cluster normally

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. fixed.
