### ISSUE TITLE
[BUG] The text UI sometimes has systemd messages

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1132]
**Describe the bug**
After the cluster is provisioned, sometimes the text UI is flooded with systemd messages.

![Screen Shot 2021-08-31 at 12 22 25 AM](https://user-images.githubusercontent.com/1691518/131371948-dadd31e9-c7f5-47c5-81ec-f1ec37f173c1.png)

**To Reproduce**
1. Do a multi-node installation.
2. Check node consoles, sometimes the console has systemd messages.

**Expected behavior**
The console should display the text UI correctly.

**Support bundle**

**Environment:**
 - Harvester ISO version: master ISO Aug. 30.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-82c4225b-head. Close this issue.

### Result 
Verified under the following scenarios, no systemd message display on console UI. 

1. Fresh install 4 nodes harvester (3 management, 1 join)
2. Reboot node 3 and node 4 harvester
3. Reboot all harvester nodes at once
4. Shutdown all harvester nodes, wait 10 minutes and power on all nodes

![image](https://user-images.githubusercontent.com/29251855/148738199-63c6e3cc-1685-4004-b892-2ceb65231cbc.png)

![image](https://user-images.githubusercontent.com/29251855/148741187-0b38935f-602b-42c4-abe5-ec87ff5c7607.png)

### Test Information
* Test Environment: 4 nodes harvester cluster on local kvm machines
* Harvester version: master-82c4225b-head (22/01/10)

### Verify Steps
1. ISO install 4 nodes harvester
2. Check the console UI output during the installation
3. Reboot node 3 and node 4 
4. Check the console UI output 
5. Reboot all harvester nodes at once
6. Check the console UI output
7. Shutdown all harvester nodes, wait 10 minutes and power on all nodes
8. Check the console UI output
