### ISSUE TITLE
[BUG] Rancher enabled settings does not enable the Rancher button in the header

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1133]
**Describe the bug**

When you enable rancher in the advanced settings the UI element doesn't show
**To Reproduce**
1. Navigate to advanced settings
2. Set rancher-enabled to `true`
3. Check header

**Expected behavior**

Either we need to fix the UI issue, or we need to remove the setting in advanced settings.
**Support bundle**

**Environment:**
 - Harvester ISO version: master-d25964a2-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized Harvester in hyper-v

**Additional context**
![Greenshot 2021-08-30 11 13 24](https://user-images.githubusercontent.com/83787952/131385386-73d12f0b-9843-465d-b6f6-17543aa0faab.png)

**Comment by yasker** [comment]
Embedded Rancher will be for debugging purposes, at least we need to change the wording of the setting, or remove it but make it accessible through another way (e.g. hidden URL).

**Comment by guangbochen** [comment]
this setting will be removed eventually.

**Comment by guangbochen** [comment]
close as the rancher setting has been removed. verified in the `master-48c97ea7-head`
