### ISSUE TITLE
[BUG] Embedded Rancher doesn't work

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1134]
**Describe the bug**

When you try to navigate to the embedded Rancher for any reason it doesn't seem to go anywhere
**To Reproduce**
1. Navigate to `https://<rharvesterIp>:30444`
**Expected behavior**

You should be able to get to the embedded rancher
**Support bundle**

**Environment:**
 - Harvester ISO version: master-d25964a2-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized harvester node on hyper-v

**Additional context**
I took a look at the pods that were running on the node. It looks like harvester is being exposed on port `8443`, and rancher-expose is on `30443` not `30444.` I'm not sure what changed with the rancher API changes, but it doesn't look like rancher is being exposed on port `30444` anymore Since the harvester dashboard is being shown on both `30443` and `8443`

**Comment by bk201** [comment]
We now expose Rancher via NodePort `30443` only.
Rancher's `ui-dashboard-index` setting is configured with a default value `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`, thus when users connect to rancher, it fetches the UI assets from that URL and send them back to users.

HostPort `8443` is special and Rancher is also exposed on that port for rancherd bootstrap purposes.

**Comment by noahgildersleeve** [comment]
You can access the old rancher UI at `https://<harvesterIp>:30443/dashboard/c/local/explorer`

**Comment by guangbochen** [comment]
@noahgildersleeve please help to confirm it is ok to close this issue, thanks

**Comment by noahgildersleeve** [comment]
@guangbochen As long as everyone is OK with the URL being hidden and there being no link then we can close it.

**Comment by yasker** [comment]
Is there a way to access the Rancher UI for the downstream Harvester from the upstream Rancher?

**Comment by guangbochen** [comment]
Yes, just through the explorer dashboard.
![image](https://user-images.githubusercontent.com/4569037/132613939-e5186329-d6ba-40ff-a7ef-464591710dd9.png)

**Comment by guangbochen** [comment]
@yasker do u think we should add visiting embed Rancher on the support page? 
![image](https://user-images.githubusercontent.com/4569037/138263056-71ce710e-4940-4de3-af83-c035cad6d0e8.png)

**Comment by yasker** [comment]
No. Let's just document the URLs used for accessing the embedded Rancher and Longhorn in the Debug section of the documentation.

**Comment by Remigius2011** [comment]
it even looks like it's possible to add new users via this URL: https://&lt;harvesterIp&gt;:30443/dashboard/c/local/auth/management.cattle.io.user
subsequently, a new ClusterRole must be added for the user using "Create from YAML" - at first sight it seems to work. However, a small piece of UI to manage members of the Harvester Cluster would definitely add to the UX.

**Comment by guangbochen** [comment]
> it even looks like it's possible to add new users via this URL: https://<harvesterIp>:30443/dashboard/c/local/auth/management.cattle.io.user subsequently, a new ClusterRole must be added for the user using "Create from YAML" - at first sight it seems to work. However, a small piece of UI to manage members of the Harvester Cluster would definitely add to the UX.

Yes but it is not recommended in the current stage, we would prefer users to leverage an external Rancher to manage its downstream Harvester clusters, https://docs.harvesterhci.io/v0.3/rancher/virtualization-management/, with that u will get full support of multi-tenant, auth providers and so on from the Rancher server.

**Comment by guangbochen** [comment]
close in favor of https://docs.harvesterhci.io/v0.3/troubleshooting/harvester/#access-embedded-rancher

**Comment by Remigius2011** [comment]
For both embedded Rancher and embedded Longhorn it says: "We only support to use the Rancher dashboard for debugging purpose." - If you close this in favor of accessing the embedded Rancher, one might expect that this is not only for debugging purpose, but to avoid having to import the Harvester to a Rancher instance, e.g. just to add more users - which is imo not a debugging task. Also, access to the embedded Longhorn might be something that is useful beyond debugging.

**Comment by guangbochen** [comment]
Sorry for the ambiguity, as we should highlight the `embedded rancher` instead, managing Harvester through an external Rancher is definitely not a debugging tool but a multi-cluster and multi-tenant feature support as per https://docs.harvesterhci.io/v0.3/rancher/rancher-integration/.

I Will update the notes, thanks.

**Comment by thooooooomas** [comment]
> it even looks like it's possible to add new users via this URL: https://<harvesterIp>:30443/dashboard/c/local/auth/management.cattle.io.user subsequently, a new ClusterRole must be added for the user using "Create from YAML" - at first sight it seems to work. However, a small piece of UI to manage members of the Harvester Cluster would definitely add to the UX.

I'm interested in doing this as well in the embedded Rancher as well as configuring ADFS as an auth provider is this possible? I do not wish to have an external Rancher just to config ADFS and have some users
