### ISSUE TITLE
[FEATURE]Is there a way to build harvester as a platform or service, other than an OS?

### ISSUE THREAD

**Issue by hxjr** [harvester/harvester#1136]
I want to build and install harvester on some other OS, like centos or debian.
Is it possible? any guide?

**Comment by wonleing** [comment]
Any method to deploy harvester on another OS?

**Comment by guangbochen** [comment]
In v0.3 we have replaced the k3os with the newOS which uses the sle15:15.3 as base kernel, u may want to take a look when it is out(ETA 09/30).

Additionally, u can refer to the doc https://docs.harvesterhci.io/v0.2/dev/dev-mode/#requirements here and install the Harvester via helm chart (both k8s cluster and some requisites with pre-setup are required), **please be aware that Helm mode installation is just for development purposes, it is not officially supported.**

**Comment by wonleing** [comment]
We managed to deploy harvester0.2.0 with helm chart on our existing kubevirt env.(avoid kubevirt and cdi over installation)
So this issue could be closed now

**Comment by rebeccazzzz** [comment]
Closing this issue based on the comment from @wonleing.
