### ISSUE TITLE
[BUG] DNS servers seem to be hardcoded in /etc/resolv.conf

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#1137]
**Describe the bug**
I tried to automatically install latest Harvester build using PXE boot (so I used `ip=dhcp` option) but I had this error during the installation:
![harvester_dns_issue](https://user-images.githubusercontent.com/25102165/131519832-ed31bfd6-a012-4686-8303-59b8e2cf8a6b.png)

I checked and here what I have in the `/etc/resolv.conf` file:
```
rancher@rancher:~> cat /etc/resolv.conf
nameserver 8.8.8.8
nameserver 1.1.1.1
```

Clearly, the DNS servers sent by the DHCP server are not used.

**To Reproduce**
1. Install from PXE or ISO with `ip=dhcp`
2. Use a YAML template for the installation, hosted on a non-public repo
3. Installation should fail like the screenshot

**Expected behavior**
DNS servers provided by the DHCP should be used, and the automatic installation should be accomplished.

**Support bundle**
Can't be generated at this stage.

**Environment:**
 - Harvester ISO version: latest master build (I don't have the exact version at this stage)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HP ProLiant DL360 Gen9 and on a VM

**Additional context**
N/A

**Comment by guangbochen** [comment]
address via https://github.com/harvester/harvester-installer/pull/109, can u please help to validate it using latest ISO, thanks

**Comment by ldevulder** [comment]
I tested on version `master-c8041619-head` and the issue is fixed:
```
rancher@harvester-k9ldm:~> cat /etc/resolv.conf 
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
search prairie.suse.net
nameserver 10.84.43.11
nameserver 10.84.43.12
nameserver 10.84.2.21
```

Can be closed.
