### ISSUE TITLE
[BUG]Rancher UI on first screen when Installing Harvester using IPXE Boot

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1139]
**Describe the bug**
When trying to install Harvester using ipxe Boot, the first screen which pops up on first login is Rancher UI

**To Reproduce**
1. Install Harvester using instructions on https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester

**Expected behavior**
Harvester Ui Login page should appear

**Support bundle**

**Environment:**
 - Harvester ISO version: Master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): IPXE Harvester Boot

**Additional context**

**Comment by lucidd** [comment]
Not sure if what i'm seeing is different from this bug but i wanted to put it here just in case. I'm not using IPXE but after the first login i get to `/dashboard/home` which shows the "welcome to rancher" dashboard. After some more time (~5 minutes for me) on the same url after refreshing the message changes to "welcome to harvester" and navigating to / opens the harvester ui. I also noticed that on the terminal the harvester-installer shows `Ready` while its still serving the rancher ui.

**Comment by yasker** [comment]
We shouldn't show the Rancher UI at all from Harvester.

**Comment by noahgildersleeve** [comment]
I tested this and the rancher login prompt happens while harvester is still doing the post install setting up step. Once it goes to ready it will show the harvester prompt. I imagine that when run locally with less resources the step takes longer so it is easier to hit that fail condition. We should probably just disable the web UI while it's not ready. That would probably resolve the issue.

**Comment by guangbochen** [comment]
that's exactly the reason why some rancher elements are showing on the single Harvester dashboard. On the console, we should already display the server as `NotReady` when the Harvester server is not running, but as long as the Rancher server is ready and users are visiting with the correct URL we can't disable the web UI.

And the server only needs to config it once at the initial stage.

**Comment by yasker** [comment]
@guangbochen can we find a way to disable Rancher server UI temporarily until the Harvester setup is done? We might need to reach out to the Rancher team to see if there is a way.

**Comment by guangbochen** [comment]
closed in favor of `master-48c97ea7-head`, currently only the Harvester UI and name was pop up.
