### ISSUE TITLE
[FEATURE] Node scheduling enhancement

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1140]
Can we replace the Input Component with the Select Component to make it easier to match?

![截屏2021-09-01 上午9.47.05.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/ce8b750d-3aeb-4ee5-bf3a-97f396063767)

#817

**Comment by guangbochen** [comment]
this is not required for now but can we allow users to add additional node labels on the host page.

**Comment by guangbochen** [comment]
close in favor of `v0.3.0`, customized labels are supported.
![image](https://user-images.githubusercontent.com/4569037/137253953-01f6187e-0a26-4030-b35a-f5b866dc310b.png)
