### ISSUE TITLE
[BUG] VM console fails with websocket errors

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1144]
**Describe the bug**

When you try to open a console on a VM it just has a blank window
**To Reproduce**
1. Create a new VM from image
2. Boot the VM
3. Navigate to the virtual machine list
3. Try to open a web console from harvester UI
4. Either Serial or Web VNC

**Expected behavior**

The console should output
**Support bundle**

**Environment:**
 - Harvester ISO version: master-4583f10e-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
This happens with both serial console and web VNC. I attached screenshots of the web console.
![Greenshot_2021-09-01_11_37_30](https://user-images.githubusercontent.com/83787952/131726568-d98a0311-769c-414b-aa2c-072cbb10c8d3.jpg)
![Greenshot_2021-09-01_11_39_25](https://user-images.githubusercontent.com/83787952/131726572-513f2e9a-0ff3-4984-a964-efc44bac2f36.jpg)
![Greenshot_2021-09-01_11_39_52](https://user-images.githubusercontent.com/83787952/131726574-d0392226-d649-42bc-8387-3b1c14224a5c.jpg)

**Comment by guangbochen** [comment]
@noahgildersleeve can u please help to re-validate if this is still an issue, thanks?

**Comment by noahgildersleeve** [comment]
Tested in `master-c4584348-head`. Verified as fixed.
