### ISSUE TITLE
[BUG] On airgapped server you get rancher dashboard after install

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1150]
**Describe the bug**

When you install on an airgapped server you get the rancher dashboard
**To Reproduce**
1. Install on an airgapped server
2. Log into the web UI
**Expected behavior**

You should get the harvester dashboard
**Support bundle**

This support bundle is after I opened up the connectivity and it resolved the issue.
[harvester-supportbundle_1e964292-2861-46ca-93c2-dfd89f0f9db0_2021-09-02T23-14-37Z.zip](https://github.com/harvester/harvester/files/7102274/harvester-supportbundle_1e964292-2861-46ca-93c2-dfd89f0f9db0_2021-09-02T23-14-37Z.zip)

**Environment:**
 - Harvester ISO version: master-14ef2406-head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized environment on Hyper-V 8 cores 16GB RAM

**Additional context**
You can set this up with internal networking on a hypervisor. I rebooted the server after adding internet connectivity and it recovered and gave me the harvester dashboard.
![2021-09-02 16_08_47-Rancher — Mozilla Firefox](https://user-images.githubusercontent.com/83787952/131927754-d4f4b8d5-ccf9-4a47-895e-70e5c3ac23bb.jpg)
![2021-09-02 16_14_09-](https://user-images.githubusercontent.com/83787952/131927755-6a98e6e9-0160-4960-b655-4132a4313e9d.jpg)

**Comment by guangbochen** [comment]
should be addressed via https://github.com/harvester/harvester/pull/1152, can u please re-validate it, thanks.

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head. Fixed.
