### ISSUE TITLE
[FEATURE] Hardware Spec preflight checking in the installer

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1154]
**Is your feature request related to a problem? Please describe.**

We have hardware requirements and recommended values in the [doc](https://docs.harvesterhci.io/v1.3/install/requirements/). We can check if the system meets all needs before performing the installation.

**Describe the solution you'd like**
The installer can check the hardware and warn the user if the hardware doesn't meet the recommended spec.

**Describe alternatives you've considered**

Read the doc.

**Additional context**

**Comment by w13915984028** [comment]
With the wide deployment of Harvester, this enhancement looks to be important.

**Comment by schmitch** [comment]
however it should be possible to discard the warning by inputing something like: `I KNOW WHAT I'M DOING AND I WILL PASS!` 

because the requirements are not needed for testing.

**Comment by w13915984028** [comment]
> however it should be possible to discard the warning by inputing something like: `I KNOW WHAT I'M DOING AND I WILL PASS!`
> 
> `because the requirements are not needed for testing`.

Even for testing, it is not easy to estimate the exact lower hardware requirements, especially for memory, lower memory may cause OOM, that then leads to things like: VIP is not reachable, system stuck in setting or others, it takes time to do trouble shooting.

Another example is:
https://github.com/harvester/harvester/issues/1904

**Comment by schmitch** [comment]
well the thing is, 32gb is a ton of memory. not even vsphere has that amount. esxi only needs 8gig while vcenter needs 10g.

if harvester runs a pod that needs multiple of gig of memory because of an iso upload I would consider that an bug anyway. (never a good idea to cache more than a handful of megabytes in memory for file uploads). i.e. the same bug can be reproduced even if I gave a node 10000gig of memory.

the correct way of doing that is by using a epheremal mount for a disk based cache for the harvester pod and if that is full uploads should be suspended, if longhorn can't keep up the network speed.

**Comment by w13915984028** [comment]
> well the thing is, 32gb is a ton of memory. not even vsphere has that amount. esxi only needs 8gig while vcenter needs 10g.
> 
> if harvester runs a pod that needs multiple of gig of memory because of an iso upload I would consider that an bug anyway. (never a good idea to cache more than a handful of megabytes in memory for file uploads). i.e. the same bug can be reproduced even if I gave a node 10000gig of memory.
> 
> the correct way of doing that is by using a epheremal mount for a disk based cache for the harvester pod and if that is full uploads should be suspended, if longhorn can't keep up the network speed.

no worry, when it's bug, we solve the bug, for #1904, a couple of enhancement/digging is ongoing. 

my comment, is for your point ` because the requirements are not needed for testing `

**Comment by schmitch** [comment]
well most of the time the requirements aren't needed for testing, memory is a thing that happens because of a bigger environment/whatever. but I'm pretty sure that 32gb is not needed for harvester per node and that is why I do not think that having a preflight check is a good idea. disk performance is probably way more important cause of etcd (well I even ran that on a raid 10 with 10krpm disks already)

so there are people like me who run harvester in a smaller environment and can live with the accidental breakage that we have because we use way less memory/cpu/disk than really necessary.

(P.S.: I'm also not the biggest fan of longhorn and I probably would prefer it, if it was optional and can be substituted by a nas/san)

**Comment by ne0YT** [comment]
How can I install Harvester from the .ISO on a host which only has 57GB of Storage? (Th e Installer says it's only possible with 60GB+)
I have a small edge-project where I would love to try this on hardware which I already own.

**Comment by w13915984028** [comment]
@ne0YT guess you are mentioning Harvester v0.3.

In v1.0.0, https://docs.harvesterhci.io/v1.0/install/requirements, it requires `140 GB minimum for testing, 500 GB or above preferred for production` .

**Comment by ne0YT** [comment]
@w13915984028 
The 140GB isn't enforced, only the 60GB is on setup.
But I have 57.6GB.. and I really would like to run it there..

**Comment by w13915984028** [comment]
@ne0YT 

A workaround is to build Harvester ISO from scratch, and change a few places to let it decrease the resource requirements.

Suppose you have an Linux distro, `git clone https://github.com/harvester/harvester-installer.git` or download the source code, then `make`, to get the ISO. After that, I will let you know how to change the related resource requirements.

Meanwhile, please double check if your edge device has X86 CPU and supports virtualization for creating VM.

**Comment by ne0YT** [comment]
@w13915984028 
hey there
The emails from github went into my spam..
I just built the .ISO successfully, can you tell me where to change what to make an installation possible with 57GB of Storage?

**Comment by w13915984028** [comment]
@ne0YT Please try:

https://github.com/harvester/harvester-installer/blob/master/pkg/config/config.go#L34

	SoftMinDiskSizeGiB   = 140
	HardMinDiskSizeGiB   = 60
	MinCosPartSizeGiB    = 25
	NormalCosPartSizeGiB = 50

->

	SoftMinDiskSizeGiB   = 140
	HardMinDiskSizeGiB   = 50
	MinCosPartSizeGiB    = 20
	NormalCosPartSizeGiB = 45



https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L52
storage: 5Gi -> 1Gi


https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L63
size: 2Gi -> 1Gi


https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L88
retentionSize: 50GiB -> 2GiB

https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L97
storage: 50Gi -> 2Gi

**Comment by ne0YT** [comment]
> @ne0YT Please try:
> 
> https://github.com/harvester/harvester-installer/blob/master/pkg/config/config.go#L34
> 
> ```
> SoftMinDiskSizeGiB   = 140
> HardMinDiskSizeGiB   = 60
> MinCosPartSizeGiB    = 25
> NormalCosPartSizeGiB = 50
> ```
> 
> ->
> 
> ```
> SoftMinDiskSizeGiB   = 140
> HardMinDiskSizeGiB   = 50
> MinCosPartSizeGiB    = 20
> NormalCosPartSizeGiB = 45
> ```
> 
> https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L52 storage: 5Gi -> 1Gi
> 
> https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L63 size: 2Gi -> 1Gi
> 
> https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L88 retentionSize: 50GiB -> 2GiB
> 
> https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L97 storage: 50Gi -> 2Gi

I get some errors after adjusting these values:
```
                Test:           TestCalcCosPersistentPartSize/500GiB
    --- FAIL: TestCalcCosPersistentPartSize/600GiB (0.00s)
        cos_test.go:101: 
                Error Trace:    cos_test.go:101
                Error:          Not equal: 
                                expected: 0x5f
                                actual  : 0x64
                Test:           TestCalcCosPersistentPartSize/600GiB
time="2022-11-24T14:19:25Z" level=info msg="Adding default NIC bonding options for \"mgmt-bo\""
FAIL
coverage: 58.1% of statements
FAIL    github.com/harvester/harvester-installer/pkg/config     0.014s
ok      github.com/harvester/harvester-installer/pkg/console    0.037s  coverage: 7.0% of statements
ok      github.com/harvester/harvester-installer/pkg/util       0.010s  coverage: 53.5% of statements
?       github.com/harvester/harvester-installer/pkg/version    [no test files]
?       github.com/harvester/harvester-installer/pkg/widgets    [no test files]
FAIL
FATA[0021] exit status 1                                
make: *** [Makefile:11: default] Error 1
```

**Comment by ne0YT** [comment]
```
--- FAIL: TestCalcCosPersistentPartSize (0.00s)
    --- FAIL: TestCalcCosPersistentPartSize/Disk_too_small (0.00s)
        cos_test.go:96: 
                Error Trace:    cos_test.go:96
                Error:          Expected value not to be nil.
                Test:           TestCalcCosPersistentPartSize/Disk_too_small
    --- FAIL: TestCalcCosPersistentPartSize/Disk_meet_hard_requirement (0.00s)
        cos_test.go:101: 
                Error Trace:    cos_test.go:101
                Error:          Not equal: 
                                expected: 0x16
                                actual  : 0x19
                Test:           TestCalcCosPersistentPartSize/Disk_meet_hard_requirement
    --- FAIL: TestCalcCosPersistentPartSize/Disk_a_bit_larger_than_hard_requirement:_80G (0.00s)

```

**Comment by w13915984028** [comment]
edit scripts/default
comment ./test as #./test, or delete this line

**Comment by ne0YT** [comment]
> edit scripts/default comment ./test as #./test, or delete this line

hey there
the installation works, but somehow I directly land on the rancher dashboard instead of the harvester dashboard.

**Comment by tserong** [comment]
JFTR, latest hardware requirements are listed in https://docs.harvesterhci.io/v1.3/install/requirements (the original post refers to v0.2 docs).

**Comment by tserong** [comment]
The hardware spec preflight check obviously needs to happen when you're running the interactive installer after booting the ISO.

Do PXE-booted systems (`harvester.install.automatic=true`) also need the pre-flight check (which I guess would just fail the install somehow)?  Or are we expecting anyone who's gone to the trouble of setting up PXE boot to have also read the documentation and confirmed that their systems meet the minimum hardware specs?

@bk201

**Comment by bk201** [comment]
For the PXE path, how about just letting the installer fail with a reason but allowing the use of a flag to bypass the check?
For the interactive path, I'd suggest the user be able to ignore the warning and continue (use at your own risk way).

**Comment by bk201** [comment]
Add `require/release-note` label. We need to mention this might stop automatic installation in some low-spec hardware and the user needs to specify the `harvester.install.skipchecks=true` parameter.

**Comment by bk201** [comment]
@tserong we also ~~need a section in https://docs.harvesterhci.io/v1.3/install/harvester-configuration to explain the new field~~ and update the examples in https://docs.harvesterhci.io/v1.3/install/pxe-boot-install

**update** section in the document is not needed since it's only take effect from kernel parameter.

**Comment by irishgordo** [comment]
This looks great on v1.3.0-rc2 :smile: :+1:  with the CPU / Mem Preflights
![Screenshot from 2024-02-14 15-22-16](https://github.com/harvester/harvester-installer/assets/5370752/96f61952-11e0-4349-8e3b-19d076e51f59)
![Screenshot from 2024-02-14 15-20-34](https://github.com/harvester/harvester-installer/assets/5370752/d1ee4fcf-b333-4b07-b1ea-706622db7df9)
![Screenshot from 2024-02-14 15-19-32](https://github.com/harvester/harvester-installer/assets/5370752/e522435c-c05d-45b2-b4c4-83db712480b3)

@tserong 
Should I go ahead and leave this open as the network preflight check isn't merged in & tested yet?

**Comment by tserong** [comment]
@irishgordo yeah let's get the network check in before calling this done - I promise not to write any more checks in the meantime ;-)

**Comment by tserong** [comment]
@irishgordo the NIC speed check is in RC3. It appears down the bottom of the screen after you select the network interface(s) to use:

![nic-speed-test-rc3](https://github.com/harvester/harvester/assets/754700/68767087-5a6e-4bc6-9fb8-5bf1972597a0)

If you manage to configure a system with less than a 1Gbps NIC, you'll see something like:

`Link speed of eth0 is only 100Mpbs. Harvester requires at least 1Gbps for testing and 10Gbps for production use.`

For >= 1Gbps but < 10Gbps, you'll see something like:

`Link speed of eth0 is 1Gbps. Harvester requires at least 10Gbps for production use.`

For >= 10Gbps, there'll be no warning message.

If PXE booting, the check will be applied as with the other pre-flight checks, and will abort the install if you don't have 10Gbps, unless `harvester.install.skipchecks=true` is set, in which case it'll just log warnings to `/var/log/console.log`

**Comment by irishgordo** [comment]
@tserong  this looks good with v1.3.0-rc3 :smile: :+1: 
I'll go ahead and close this out

![Screenshot from 2024-02-21 12-53-38](https://github.com/harvester/harvester/assets/5370752/b6171c9e-08ab-4f0d-8088-d64b7f25e117)
![Screenshot from 2024-02-21 12-53-02](https://github.com/harvester/harvester/assets/5370752/44dc34aa-8297-474c-9d51-a60635a716f0)


@tserong  - but I did notice a low-severity issue if there is a large amount of NIC ports the user/org/etc. were to use for the management bond:
https://github.com/harvester/harvester/issues/5189
Though I do not think most users/orgs/etc would tend to use "a lot" of NIC ports for the mgmt bond, maybe most ~4 ports being used?  I'm not really sure on the stats, it's just a gut feeling that the likelyhood most users would encounter 5189 would be low.
( cc: @bk201 ^)
