### ISSUE TITLE
[BUG] Follow wiki to setup development environment failed

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1161]
**Describe the bug**

I tried to follow the wiki [Setting Up Harvester Development Environment](https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment) to set up my development environment, but harvester keeps showing errors:
```
ERRO[1916] Failed to dial steve aggregation server: dial tcp 10.53.11.235:443: i/o timeout
```
![image](https://user-images.githubusercontent.com/5047724/132194423-1eab7898-2e25-4e0a-9497-44e553c14f18.png)

I checked `kubectl` output and found out that IP is a ClusterIP in namespace `cattle-system`:
```
$ kubectl get svc -n cattle-system
NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
rancher           ClusterIP   10.53.11.235   <none>        80/TCP,443/TCP   3d8h
rancher-expose    NodePort    10.53.49.235   <none>        443:30443/TCP    3d8h
rancher-webhook   ClusterIP   10.53.78.29    <none>        443/TCP          3d8h
webhook-service   ClusterIP   10.53.33.58    <none>        443/TCP          3d8h
```
Seems like it tries to connect to ClusterIP service...? but that shouldn't be connectable from outside of the cluster.

**To Reproduce**

1. Follow wiki [Setting Up Harvester Development Environment](https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment) to set everything up.
2. Run harvester executable.

**Expected behavior**

Running harvester executable should be fine outside of the cluster.

**Support bundle**

**Environment:**

 - Harvester ISO version: `master` download on 2021-09-02
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Deploy in HCI Mode in KVM

**Additional context**

**Comment by guangbochen** [comment]
this only happens when u run local harvester development and the wiki doc has not been updated to reflect the 0.3 architectural design changes:
- for now, the easiest way to connect the Harvester cluster with your local dev environment is through the https://telepresence.io/
- we have introduced the aggregated api-server for the multi-cluster management purpose with rancher 2.6 integration https://github.com/harvester/harvester/pull/998
- with https://github.com/harvester/harvester/pull/1152 u can now add `--add-local-ui=true` to run the local UI directly for development testing, the `Failed to dial steve aggregation server` error can be ignored if u are not testing the Rancher API integration.

**Comment by wangpan-hqu** [comment]
> this only happens when u run local harvester development and the wiki doc has not been updated to reflect the 0.3 architectural design changes:
> 
> * for now, the easiest way to connect the Harvester cluster with your local dev environment is through the https://telepresence.io/
> * we have introduced the aggregated api-server for the multi-cluster management purpose with rancher 2.6 integration [Serve Harvester APIs as Rancher aggregation APIs #998](https://github.com/harvester/harvester/pull/998)
> * with [Add local-ui-dev mode and fix rancher ui expose registry #1152](https://github.com/harvester/harvester/pull/1152) u can now add `--add-local-ui=true` to run the local UI directly for development testing, the `Failed to dial steve aggregation server` error can be ignored if u are not testing the Rancher API integration.

I am following wiki to setup development environment，there are many problems as follows：
1.In go environment, do GoLand and harvester need to be on the same host? If not, how can they be connected
2. What kind of effect can you see when setting up the development environment
3. Can you give a detailed document

**Comment by wangpan-hqu** [comment]
> **Describe the bug**
> 
> I tried to follow the wiki [Setting Up Harvester Development Environment](https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment) to set up my development environment, but harvester keeps showing errors:
> 
> ```
> ERRO[1916] Failed to dial steve aggregation server: dial tcp 10.53.11.235:443: i/o timeout
> ```
> 
> ![image](https://user-images.githubusercontent.com/5047724/132194423-1eab7898-2e25-4e0a-9497-44e553c14f18.png)
> 
> I checked `kubectl` output and found out that IP is a ClusterIP in namespace `cattle-system`:
> 
> ```
> $ kubectl get svc -n cattle-system
> NAME              TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)          AGE
> rancher           ClusterIP   10.53.11.235   <none>        80/TCP,443/TCP   3d8h
> rancher-expose    NodePort    10.53.49.235   <none>        443:30443/TCP    3d8h
> rancher-webhook   ClusterIP   10.53.78.29    <none>        443/TCP          3d8h
> webhook-service   ClusterIP   10.53.33.58    <none>        443/TCP          3d8h
> ```
> 
> Seems like it tries to connect to ClusterIP service...? but that shouldn't be connectable from outside of the cluster.
> 
> **To Reproduce**
> 
> Steps to reproduce the behavior:
> 
> 1. Follow wiki [Setting Up Harvester Development Environment](https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment) to set everything up.
> 2. Run harvester executable.
> 
> **Expected behavior**
> 
> Running harvester executable should be fine outside of the cluster.
> 
> **Support bundle**
> 
> **Environment:**
> 
> * Harvester ISO version: `master` download on 2021-09-02
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Deploy in HCI Mode in KVM
> 
> **Additional context**

I have the same problem，how did you finally solve it

**Comment by futuretea** [comment]
@johnliu55tw @wangpan-hqu we can try to follow the latest wiki [Setting-Up-Harvester-Development-Environment](
https://github.com/harvester/harvester/wiki/Setting-Up-Harvester-Development-Environment) with the latest master code to setting up dev env, and see if we have any questions.

**Comment by rebeccazzzz** [comment]
Please refer to this document https://docs.harvesterhci.io/v1.0/dev/dev-mode/ and feel free to ask again if you still have any issues.
