### ISSUE TITLE
[FEATURE] Metallb support

### ISSUE THREAD

**Issue by inmanturbo** [harvester/harvester#1165]
It would be nice to have support within the ui for metalLb and be able to use that to assign floating ips to VM's.

**Comment by davidspek** [comment]
I believe the kube-vip implementation should be able to take care of that already.

**Comment by yasker** [comment]
Duplicate of #1676

**Comment by inmanturbo** [comment]
This predates #1676 by over 500 tickets. I would have thought it would have been be the duplicate!

**Comment by yasker** [comment]
LOL. The reason I marked this as duplicate is because the other item has been worked on and scheduled. 

Either way the feature is coming!
