### ISSUE TITLE
[BUG] disk `auto_delete` doesn't work in terraform-provider-harvester v0.2.0

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1168]
**Describe the bug**

**To Reproduce**
1. create vm by terraform-provider-harvester. like https://github.com/harvester/terraform-provider-harvester/blob/master/docs/resources/virtualmachine.md
2. terraform destory
3. use `kubectl get pvc` to check volume list

**Expected behavior**

if set disk field auto_delete  to true, volume will be auto deleted.

**Environment:**
 - terraform-provider-harvester:  v0.2.0
 - Harvester ISO version:  master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by yasker** [comment]
~~@slickwarren can you help to validate this?~~

Need to reassign due to Caleb is on other tasks

**Comment by chajain** [comment]
Created a VM using terraform and the resource has a root disk which uses auto_delete = true.
disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image        = "{{ image_name }}"
    auto_delete  = true 
  }

The VM is created successfully and the root disk is deleted automatically when VM is destroyed using terraform.
