### ISSUE TITLE
[BUG] A long downtime after disabling the VLAN network.

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1171]
**Describe the bug**

It takes more than one minute to recover the network connectivity after disabling the VLAN network.

**To Reproduce**
1. Go to "Advance/Settings/vlan"
2. Disable the VLAN network

**Expected behavior**

The downtime is less than 2 seconds.

**Support bundle**

**Environment:**
 - Harvester ISO version: 2021-0903-master-head ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  VirtualBox

**Additional context**

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/1464
