### ISSUE TITLE
Hide support bundle link if users have no permission for it

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1177]
**To Reproduce**
1. Log in as a project member
2. Click the support link and click `generate support bundle`

**Result**
![image](https://user-images.githubusercontent.com/5697937/132509291-745b188c-1d20-497d-a6f1-a40bf71cccf4.png)

**Expected behavior**
Hide the link when users have no permissions

**Environment:**
 - Harvester ISO version: master-5fc1858a-head

**Comment by FrankYang0529** [comment]
## Test info

* Verified Harvester version: v0.3.0-rc1
* Verified Rancher version: v2.6.1-rc5

## Test cases

* A a user as member and click support link.
  * [x] Generate Support Bundle is not on the page.
![Screenshot from 2021-10-05 18-58-25](https://user-images.githubusercontent.com/4927361/136010882-9a5d0f70-fd20-454d-a28c-f119e3a1e80a.png)
