### ISSUE TITLE
[FEATURE] Backup page enhancement

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1178]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/18737885/132512371-031aed9e-ba03-43d4-b2f5-32e3474b2aff.png)
- It seems "Ready To Use" will be better
- How about "true/false" replace with an icon or "yes/no"

![image](https://user-images.githubusercontent.com/18737885/132515605-0ec44f81-6157-4b6b-93d8-c2dad00455b2.png)
- Backup detail did not expand the side menu after page refresh

![image](https://user-images.githubusercontent.com/18737885/132516578-e6753ae3-a8e2-45a7-8d90-697b1518b549.png)
- We should hide this link because the volume does not exist.

**Comment by n313893254** [comment]
> Backup detail did not expand the side menu after page refresh

The issue is a common issue.

**Comment by johnliu55tw** [comment]
Tested and verified on 0.3.0-rc1. Everything works as expected except
> Backup detail did not expand the side menu after page refresh

However @n313893254 did [mention](https://github.com/harvester/harvester/issues/1178#issuecomment-928701787) this is a common issue so I suppose we're not changing anything right now. @noahgildersleeve Do you think we could close this issue?

**Comment by yasker** [comment]
@johnliu55tw Feel free to close the issue. The expansion issue is a minor issue. We can file another issue to track it to see what we can do for v1.0.0 release.
