### ISSUE TITLE
[FEATURE] backup-target should display error message

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1179]
**Is your feature request related to a problem? Please describe.**
![image](https://user-images.githubusercontent.com/18737885/132518520-f28308ab-4fd8-4606-9fa7-3133b1ab88e3.png)

- Configure S3 correctly
- Select Virtual Hosted-styled to false

There is no error message shows on the backup list page or backup-target setting page.

**Comment by n313893254** [comment]
Seems the issue has been fixed.

- Setting page
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/01913c2c-11d3-4585-ab7a-17992736d100)

- Backup list
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/ad479e85-6669-41da-827e-6fc0ee430a4f)

**Comment by lanfon72** [comment]
Can not reproduce the origin one, error message always displayed.

Harvester version: **master-d05a6cc7-head**
ui-resource option: **Bundled**

#### Additional Context
- Tested on last week's iso and this week's iso. (dashboard's version not changed)
- S3's environment using opnebare's demo account.
