### ISSUE TITLE
[BUG] Support VIP on Equinix Metal

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1181]
**Describe the bug**
The VIP feature is in, we need to figure out how to use that in Equinix Metal platform.
Also, the ipxe-examples should be updated.

**Comment by FrankYang0529** [comment]
Following Equinix documents, I can create an Elastic IP and use it between multiple servers through BGP.

* [Configuring Local BGP](https://metal.equinix.com/developers/docs/bgp/local-bgp/)
* [Route BGP with BIRD](https://metal.equinix.com/developers/docs/bgp/route-bgp-with-bird/)
* https://github.com/packethost/network-helpers/blob/master/routers/bird/README.md

Steps:

1. Request an elastic IP address.
2. Create a server with Ubuntu 20.10 and enable Local BGP for it.
3. Run commands
```
# configure elastic IP on lo:0
> cat >>/etc/network/interfaces <<EOF
auto lo:0
iface lo:0 inet static
  address <Elastic-IP>
  netmask 255.255.255.255
EOF
> ifup lo\:0
# install packages
> apt -y update && apt -y install python3-pip git bird
> cd /opt
> git clone https://github.com/packethost/network-helpers.git
> cd network-helpers
> pip3 install jmespath
> pip3 install -e .
# generate bird.conf
> ./configure.py -r bird | tee /etc/bird/bird.conf
> systemctl restart bird
> birdc
bird> show protocols all neighbor_v4_1
# after few seconds, we can see BGP state is Established
```
4. Run steps 2 and 3 for another server.
5. We can ssh to these two servers by `ssh root@<elastic-ip>`.


I will try to establish this process on Harvester ISO and if it works, I will try to make the process automatically.

**Comment by FrankYang0529** [comment]
I tried to follow [kube-vip](https://kube-vip.chipzoller.dev/docs/usage/equinix/#using-annotations) document to deploy [Equinix CCM](https://github.com/equinix/cloud-provider-equinix-metal#deploy-project-and-api). Equinix CCM pod keeps showing:
```
cloud-provider-equinix-metal-5d969d9768-8r64x E0117 09:19:07.236351       1 cloud.go:316] failed to update and sync services: elastic ip tag is empty. Nothing to do
cloud-provider-equinix-metal-5d969d9768-8r64x E0117 09:19:07.236404       1 cloud.go:325] failed to update and sync nodes: no provider ID given for node hk-c3-small-x86-01
```
I tried to set `METAL_EIP_TAG` as Elastic IP, but it doesn't work.

Also, kube-vip pod keeps showing:
```
kube-vip-ds-9928p time="2022-01-17T09:18:33Z" level=error msg="node-asn value missing or empty"
```

**Comment by guangbochen** [comment]
Noted some known limitations https://github.com/harvester/harvester/issues/2360 that we may need to document on both the [harvester/ipxe-examples](https://github.com/harvester/ipxe-examples/) and the doc website, thanks.
