### ISSUE TITLE
[BUG] Set the initial password for the first login, but did not jump to the dashboard page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1182]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/5c51e02c-8779-45c1-99dc-35e420fb264c)

**To Reproduce**
1. Install a new cluster
2. set password

**Expected behavior**

Jump to the dashboard page

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
didn't encounter this issue anymore, please feel free to reopen it if u can reproduce it, thanks
