### ISSUE TITLE
[BUG] VIP display doesn't have port on node

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1186]
**Describe the bug**

When you look at the IP in the console on your node it doesn't show the port. If you go to that IP it will give you a 404
**To Reproduce**
1. Create a new Harvester cluster
2. Set the VIP as something routable
3. Finish install and reboot
4. Navigate to the address shown in the console
**Expected behavior**

Either the URL should work, or we should add the port 30443 to the output
**Support bundle**

**Environment:**
 - Harvester ISO version: master-9a316b50-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Virtualized on Hyper-V

**Additional context**
It's showing `https://<harvesterIp>` instead of `https://<harvesterIp>:30443`

**Comment by guangbochen** [comment]
nodePort is not required for the VIP, but it will support both 443 and 30443, the console should default to show VIP without port if the VIP is configured.

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Fixed.
