### ISSUE TITLE
[FEATURE] Support case-insensitive value for network modes in Harvester configuration

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1187]
**Is your feature request related to a problem? Please describe.**

Currently, valid values of `Install.VipMode` and `Install.Network.Method` fields are:
- `DHCP`
- `static`

The validator reports error if the mode is set to `dhcp` or `Static`. 

**Describe the solution you'd like**

We can relax the check by making the value case-insensitive.

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
@yaocw2020 uppercase `DHCP` will be failed with https://github.com/harvester/ipxe-examples/pull/13/files#diff-314da8b4affed3b1dcec6680be5bdb6d8454107a6593d2c62fe94489b738e4c0R16

**Comment by lanfon72** [comment]
Tested uppercase `DHCP` works with https://github.com/harvester/ipxe-examples/commit/7b9cebdcaa7231a3d16120b5ba12a1305e191eda and [v0.3.0-preview1](https://github.com/harvester/harvester/releases/tag/v0.3.0-preview1) combination on my laptop.

I will test other cases like `dHcP`, `StaTIC`..etc.

**Comment by lanfon72** [comment]
Close this issue as I verified those cases work normally:

```
VIP mode string -- result
-----
STATIC  -- pass
DhCp    -- pass
sTaTic  -- pass
DHCP    -- pass
```

Test Information
----
* Environment: Laptop, Vagrant, iPXE install
* Harvester Version: [v0.3.0-preview1](https://github.com/harvester/harvester/releases/tag/v0.3.0-preview1)
Verify Steps:
  - Clone https://github.com/harvester/ipxe-examples/commit/5e99d35b399e148caadef63c2ee93a49c01dda1f and modify settings.yml for 2 nodes
    (We just need to make sure that **VIP**'s config section could be used and install main node successfully.)
  - After Installed, browse `https://<VIP_Address>/`  
    _To notice: there don't required port on the URL, the site should be the same as `https://<VIP_Adress>:30443/`_

  _Additional Verify:_
  - With *DHCP mode*, login to main node and run `ip addr | grep vip` to check there have the interface named `vip-...`
  - With _STATIC mode_, no interface named `vip-...`, but u can still access VIP address.
  - With _**Both** mode_, check with `kubectl get configmap -n harvester-system vip`, will show the health status.
