### ISSUE TITLE
[BUG] Cannot access Web VNC Console from individual VM page: t.name is null

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1190]
**Describe the bug**
When I tried to access the Web VNC Console from the individual VM page (Not from the list of VMs), the GUI reports Error: t.name is null. It works when I access the Web VNC from the list of VMs.

![image](https://user-images.githubusercontent.com/5047724/132656978-79ddd168-df03-421e-8256-1716dffa7a9c.png)

**To Reproduce**
1. Create a Virtual Machine and wait for it to start.
2. Click the VM to go to the VM page
3. Click "Console" -> Open in Web VNC
4. New window opened and an error is shown

**Expected behavior**
Opening Web VNC Console should work.

**Support bundle**

**Environment:**
 - Harvester ISO version: master - 2021-09-08
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by yasker** [comment]
I believe this has been fixed as a part of UI integration. @johnliu55tw please verify. Thanks.

**Comment by johnliu55tw** [comment]
Verified on 0.3.0-rc1. Web VNC opened without any issue.
