### ISSUE TITLE
[BUG] UI websocket disconnect error

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1193]
**Describe the bug**

When visiting the Harvester UI via the VIP, at times the WebSocket will be disconnected.

**Expected behavior**
Websocket should not be disconnected regularly.

as a temporary workaround is to click re-enable the cert 
![WechatIMG18](https://user-images.githubusercontent.com/4569037/132688488-f77457f2-8f93-4c6a-b6c6-4e48306234d1.png)

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. During testing I haven't seen any websocket disconnected errors. I will keep an eye out as testing proceeds and will re-open issue if it comes up. Closing as fixed.
