### ISSUE TITLE
[BUG] " not a valid IP address" Baremetal with multiple NICs. VIP issue

### ISSUE THREAD

**Issue by voima-eetu** [harvester/harvester#1194]
**Describe the bug**

iPXE Harvester install on baremetal node with multiple nics will fail without configuring VIP.

**To Reproduce**
1. iPXE install harvester on baremetal with multiple nics.
2. No VIP configuration on config-create.yaml
3. eth0 trunk with no dhcp or IP address and eth1 connected to management vlan with dhcp. <- I guess this doesn't matter
4. Latest master install fails with " is not a valid IP address" 

**Expected behavior**

Install is successful

**Support bundle**

**Environment:**
 - Harvester ISO version: **v0.2.0 / master**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

My guess of the issue:
Issue is that even though VIP is not configured, validator.go "checks" vip. https://github.com/harvester/harvester-installer/blob/master/pkg/console/validator.go#L204
This check will run checkIP against empty IP address and will fail. https://github.com/harvester/harvester-installer/blob/master/pkg/console/validator.go#L166

**Comment by bk201** [comment]
The VIP was introduced in the master branch yesterday.
We didn't update the document yet, but the `vip` field will become mandatory in create mode.
Please check the example: https://github.com/harvester/ipxe-examples/blob/53d09a684762932b5f892b2919f69fd0cc5bddb1/general/config-create.yaml#L14-L16

**Comment by bk201** [comment]
Close the issue because VIP is mandatory.
