### ISSUE TITLE
[FEATURE] node-disk-manager: using a strong hash algorithm to generate disk name

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1195]
**Is your feature request related to a problem? Please describe.**
We can choose a better hash algorithm for disk names.
Currently, md5 is used.
https://github.com/harvester/node-disk-manager/blob/db32a015ba90635525262485ef8f320d32bb922d/pkg/block/block_device.go#L554-L558

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

It's not backward compatible if the algorithm is changed. We need to make this move before formal release.

**Comment by weihanglo** [comment]
Sounds reasonable. But what do yo mean by "strong & better hash"? There are plenty of properties in hash algorithms. IMO the most notable would be "cryptographic or not". A cryptographic hash algorithm can produce deterministic hash value and resist to collusion to some extent. MD5 was in that category but it has been proved as [cryptographically broken](https://en.wikipedia.org/wiki/MD5#Security). If we want to to choose a better cryptographic hash algorithm, I'll recommend [BLAKE3](https://github.com/BLAKE3-team/BLAKE3) but if [lack of official support from Golang](https://github.com/golang/go/issues/36632) is a concern, we can choose BLAKE2b instead.

![image](https://user-images.githubusercontent.com/14314532/132775433-b72f0a73-bfc1-4b45-b2fa-df124b148a34.png)

If we are comfort about non-crypto hash, there are lots of choices out there, but there are trade-offs. Be aware of non-determinism and high collision rate. For example, [aHash is really performant](https://github.com/tkaitchuck/aHash/blob/master/compare/readme.md#Quality) by leveraging hardware AES instructions. However, this results in non-deterministic hash value across different machine, so the hash value cannot sent over network. The others also have different concerns. 

I'll recommend sticking with cryptographic hash if performance is not a big concern.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/node-disk-manager/pull/10, and not required for QA validation as this is just a backend enhancement.
