### ISSUE TITLE
[BUG] node-disk-manager: pod crashes on duplicated disk names

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1196]
**Describe the bug**

If two nodes have disks that are hashed to the same ID, one of the node-disk-manager pod will exit with panic.

**To Reproduce**
The easiest way to reproduce is to attach the same CDROM to multiple machines.
Suppose we have node1 and node2 in Harvester cluster:
1. Attach Harvester ISO to node1 and node2.
2. If NDM pod on node1 starts earlier, NDM pod on node2 will be in `CrashLoopBackOff` status.

**Expected behavior**

NDM pods on all nodes should start and work.

**Additional context**

*node1 NDM pod log*
```
time="2021-09-09T14:25:42Z" level=info msg="Starting node disk manager controller"
time="2021-09-09T14:25:42Z" level=info msg="register ndm filters"
time="2021-09-09T14:25:42Z" level=info msg="Scan block devices of node: aa"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device 02783de21ce74204ceabec116bbffa89 with device: /dev/sr0"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device 131dd8835417a0ce3df58c34dfe15f88 with device: /dev/vda"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device 5ba98ddbb824b309118e5ce013a17046 with device: /dev/vda1"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device 10bac0dd54ff8f1d2b783822699e6406 with device: /dev/vda2"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device fe524d2219f40da469db2d491a7c6d24 with device: /dev/vda3"
time="2021-09-09T14:25:42Z" level=info msg="Add new block device d6abf549fc26dfd7c3bd5f8bb45e3965 with device: /dev/vda4"
time="2021-09-09T14:25:43Z" level=info msg="Start monitoring udev processed events"
time="2021-09-09T14:25:43Z" level=info msg="Starting harvesterhci.io/v1beta1, Kind=BlockDevice controller"
I0909 14:25:44.625254       1 request.go:668] Waited for 1.002427799s due to client-side throttling, not priority and fairness, request: PUT:https://10.53.0.1:443/apis/harvesterhci.io/v1beta1/namespaces/longhorn-system/blockdevices/d6abf549fc26dfd7c3bd5f8bb45e3965
time="2021-09-09T14:26:42Z" level=info msg="Scan block devices of node: aa"
time="2021-09-09T14:26:43Z" level=info msg="Update existing block device status 02783de21ce74204ceabec116bbffa89 with devPath: /dev/sr0"
I0909 14:27:01.922591       1 request.go:668] Waited for 1.195865612s due to client-side throttling, not priority and fairness, request: PUT:https://10.53.0.1:443/apis/harvesterhci.io/v1beta1/namespaces/longhorn-system/blockdevices/131dd8835417a0ce3df58c34dfe15f88
time="2021-09-09T14:27:42Z" level=info msg="Scan block devices of node: aa"
time="2021-09-09T14:27:42Z" level=info msg="Update existing block device status 02783de21ce74204ceabec116bbffa89 with devPath: /dev/sr0"
time="2021-09-09T14:28:42Z" level=info msg="Scan block devices of node: aa"
time="2021-09-09T14:28:42Z" level=info msg="Update existing block device status 02783de21ce74204ceabec116bbffa89 with devPath: /dev/sr0"
```
*node2 NDM pod log*
```
time="2021-09-09T15:04:09Z" level=info msg="Starting node disk manager controller"
time="2021-09-09T15:04:09Z" level=info msg="register ndm filters"
time="2021-09-09T15:04:09Z" level=info msg="Scan block devices of node: bb"
time="2021-09-09T15:04:09Z" level=info msg="Add new block device 02783de21ce74204ceabec116bbffa89 with device: /dev/sr0"
time="2021-09-09T15:04:09Z" level=fatal msg="failed to register block device controller, blockdevices.harvesterhci.io \"02783de21ce74204ceabec116bbffa89\" already exists"
```

*The CDROM infomation*
```
bb:~ # blkid /dev/sr0
/dev/sr0: BLOCK_SIZE="2048" UUID="2021-09-09-10-08-04-00" LABEL="COS_LIVE" TYPE="iso9660" PTUUID="4bd81584" PTTYPE="dos"
bb:~ # echo -n 2021-09-09-10-08-04-00 | md5sum
02783de21ce74204ceabec116bbffa89  -
```

We can filter out CDROM to avoid this problem. But there might still be other situations that can cause this problem, e.g.,
- A iSCSI disk is shared between multiple nodes. (in Harvester, we already filter out longhorn targets)
- Multiple nodes are connected to a single JBOD and zoning is not on.
- USB disks...

**Comment by weihanglo** [comment]
How about prepending `nodeName` on the blockdevice name? It makes sense that blockdevice is a node-scoped resources. 

But if `auto-gpt-generate` is enabled, a weird scenario may happens that two NDMs on different nodes are trying to make GPT partition against the same non-identifiable device at the same moment. Is that a concern from NDM's side?

**Comment by guangbochen** [comment]
The `nodeName` looks good to me, in regards to the auto-gpt creation, I think we should handle the concurrency issue properly, probably mark a label or something similar to make sure it is locked by one of the node only.

**Comment by weihanglo** [comment]
I create a new issue https://github.com/harvester/harvester/issues/1213 for race condition of auto GPT generating. Supposed it is not urgent since the scenario is a niche, but still valuable to record it.

**Comment by guangbochen** [comment]
fixed via https://github.com/harvester/node-disk-manager/pull/10, the NDM pod is up and running properly with the same disk names but on the different nodes, since this is just a backend fix so close it for now.
