### ISSUE TITLE
[BUG] The network interface name is unpredictable in the new OS

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1197]
**Describe the bug**
In a multiple-NICs environment, the order of interface name (`eth0`, `eth1`) is not guaranteed in each boot.
This can cause RKE2 to fail to run or some other problems.

We can use a predictable naming scheme.

**To Reproduce**
1. Install the new OS on a system with multiple-nics.

**Expected behavior**

The interface scheme needs to be predictable.

**Environment:**
 - Harvester ISO version: master ISO Sep 9th.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Physical machines with 4 interfaces.

**Additional context**

**Comment by guangbochen** [comment]
Should be addressed via https://github.com/harvester/harvester-installer/pull/118

**To Test:**
- make sure the NIC name is persisted after reboot (better to validate using multiple NICs)
- will need to set `net.ifnames=1` using USB installation https://github.com/harvester/harvester/issues/1200

**Comment by lanfon72** [comment]
ref to #1267

**Comment by lanfon72** [comment]
close this issue as it can't be reproduced either in Provo's bare metal or QEMU[BIOS mode] environment.
(All of those environment shows renamed NIC prefix as `ens` and the order always kept the same after 3+ times rebooted)

tested Harvester Version: [master-1a041d23-head](https://github.com/harvester/harvester/commit/1a041d2371c5e70419bbe2a6997e8756054ab58c)
