### ISSUE TITLE
[BUG] Unable to migrate a VM from one node to another

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1198]
**Describe the bug**
On a three-node cluster, I am unable to migrate a VM from one node to another. The `Create` button is remained grayed out even after I select a qualified node to migrate to.

**To Reproduce**
1. On a three node cluster, create a small VM (1 CPU, 1 Gb RAM, and 10 Gb disk).
2. After the VM had successfully started and in `running` state, select `migrate` from the drop-down menu.
3. Select a node to migrate to and notice that the `Create` button remained grayed-out.

**Expected behavior**
We should be able to click on the `Create` button and the VM is successfully migrated to the desired node.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-965a9c96-head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Vagrant virtual environment.

**Additional context**
![Harvester-3-Node-Cluster](https://user-images.githubusercontent.com/1808417/132807629-0a46435a-321c-49a6-8e7a-cc863f2c61cb.png)
![Harvester-VM-Running-On-Node-1](https://user-images.githubusercontent.com/1808417/132807644-da40002f-6ec2-45d9-bd0c-fe94ad9d9260.png)
![Harvester-Unable-Migrate-VM-To-Node-2](https://user-images.githubusercontent.com/1808417/132807668-64b839cc-1918-494c-ad4e-b89e4de75599.png)

**Comment by alexdepalex** [comment]
Same here. And create sounds a bit odd for initiating the migration.

**Comment by DaiYuzeng** [comment]
@alexdepalex Thanks for your advice! `Create` would be renamed to `Apply`.

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head on 3 node cluster. Closing as fixed.
