### ISSUE TITLE
[FEATURE] Doc: Install OS from a USB disk

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1200]
**Is your feature request related to a problem? Please describe.**

Using a USB stick to install an OS is quite common. We can have a guide for that.

**Describe the solution you'd like**
- A tested guide that shows how to create an installable USB stick.

**Describe alternatives you've considered**

An image that can be directly dd to a USB stick.

**Additional context**

**Comment by yasker** [comment]
For preview1, if you're installing via USB instead of ISO, you need to edit the kernel parameter at boot time when booting up the USB installer to add `net.ifnames=1` parameter.

**Comment by davidspek** [comment]
Just in case anybody else runs into this, when starting the installer ISO, press `Esc`, then `e` to edit the kernel parameters and add `net.ifnames=1` to the end of the line. Then press `enter` to continue the boot process. Given that `net.ifnames=1` is enabled after the installation, the installer should probably also have this kernel parameter set.

**Comment by bk201** [comment]
The `net.ifnames=1` parameter is mandatory in the new OS (a Leap 15.3 derivative).
it's disabled by default in the [udev](https://github.com/openSUSE/systemd/commit/74b2d3b88ab2dc2c710840c2564d00a51da40add).

**Comment by yasker** [comment]
@bk201 is it something we can improve at the OS level? It's probably unreasonable to ask many users to modify their boot cmdline.

**Comment by bk201** [comment]
> @bk201 is it something we can improve at the OS level? It's probably unreasonable to ask many users to modify their boot cmdline.

Looks like the only way is to build and ship our own systemd, it's the default value in the code:
https://github.com/openSUSE/systemd/blob/611376f8306c8c73789d3dc743c4c8ff1a930f7a/src/udev/net/link-config.c#L206-L210

It's weird the image writer doesn't include this parameter but includes others (like `root=live:CDLABEL=COS_LIVE rd.live.dir=/`). I'll check the image writer.

**Comment by yasker** [comment]
@bk201 Thanks for the update. Weird, since it's `default` instead of `hardcoded` value, that means there must be a way to change it?

**Comment by bk201** [comment]
> @bk201 Thanks for the update. Weird, since it's `default` instead of `hardcoded` value, that means there must be a way to change it?

Yes, the way is just to include `net.ifnames=1` in boot parameters.

**Comment by guangbochen** [comment]
should be addressed via https://github.com/harvester/harvester/issues/1267 using Grub2 and no additional config is required.

**Comment by lanfon72** [comment]
It seems this issue was target to update documents for _ISO installation with USB_, as we changed to use **Grub2**, @bk201 does it means that we can use any methods to make bootable USB from ISO? (and it should work correctly?)

**Comment by bk201** [comment]
So far I have seen these ways to create installation USB:
- `dd` the ISO to the USB
- Use balenaEtcher

There are also some caveats using a USB stick, I'll create a section in the doc.

**Comment by TachunLin** [comment]
I also tried using **rufus** 3.15 to create USB installation stick works on local bare machine. (with bios storage set to UEFI only)
By setting partition theme to "GPT" and Target system to "UEFI" 

![image](https://user-images.githubusercontent.com/29251855/139616002-ee610915-0e83-41f2-9aea-7251dda241d7.png)

**Comment by lanfon72** [comment]
Verified it is support **UEFI-only**, USB disk generated from _balenaEtcher_, _Imagewriter_, `dd` (*nix only) and Rufus (windows only) have the same behavior to install Harvester.

Also tested on qemu/KVM's USB simulation, all of UEFI OVMF binaries are unable to boot and install normally.


Test Information
----
* Environment: **Bare metals** Desktop BIOS only, Dell 5560 laptop
* Harvester Version: **master-d05a6cc7-head**
