### ISSUE TITLE
[BUG] Baremetal cluster VIP cannot be used to join the cluster for other nodes

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1201]
**Describe the bug**
Baremetal cluster VIP cannot be used to join the cluster for other nodes. The mgmt IP of the node has to be used instead.

**To Reproduce**
Try to use `mgmt address` shown on the first node to join the cluster from other nodes.

**Expected behavior**
The user should either be able to join the cluster using the VIP or be shown the IP that can be used for joining the cluster.

**Support bundle**
NA

**Environment:**
 - Harvester ISO version: v0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal.

**Additional context**
No.

**Comment by davidspek** [comment]
During the installation using the ISO from a USB I tested this and filled in the VIP from the first node, and the new node was able to join it successfully. After having joined the new node does show the Harvester management URL to be the management address and not the VIP though.

**Comment by yaocw2020** [comment]
> During the installation using the ISO from a USB I tested this and filled in the VIP from the first node, and the new node was able to join it successfully. After having joined the new node does show the Harvester management URL to be the management address and not the VIP though.

It should be VIP.
![image](https://user-images.githubusercontent.com/7421463/133015217-82eadf4c-48e1-4a90-877e-e8382e554e43.png)

**Comment by yasker** [comment]
Able to join using VIP with the latest image. Close the issue.
