### ISSUE TITLE
[BUG] Network configuration on the node doesn't show all the nics

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1202]
**Describe the bug**
I have a cluster of three nodes. Two of them have identical setup, another one has a different NIC name due to a different model. The host->network configuration doesn't allow me to choose the nic that's available. There is no nic in the list.

**To Reproduce**
1. Install a three-node cluster in the environment
2. Set default network interface to e.g. ` enp129s0`
3. Observe **one node reports network setup failure.**
4. Edit the node config to try to correct it. Cannot find any nics in the dropdown.
<img width="1646" alt="Screen Shot 2021-09-10 at 12 18 19 PM" src="https://user-images.githubusercontent.com/3344618/132906312-7666dc69-a3a5-411b-b60f-6446476d72fc.png">

**Expected behavior**
The user should be able to configure each node's nic.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal

**Additional context**
I suspect the information wasn't passed to the backend due to the initial network configuration failure.

**Comment by guangbochen** [comment]
close in favor of `master-48c97ea7-head`, currently, all NICs are viewable on the `Hosts -> Netowk` tab after added the bond NIC support. https://github.com/harvester/harvester/issues/1207
![image](https://user-images.githubusercontent.com/4569037/134941226-04f0511c-fa42-4dcd-846a-8c228bcfcaac.png)
