### ISSUE TITLE
[BUG] Editing `backup-target` results in `{"data":"Handler disconnected\n"}`

### ISSUE THREAD

**Issue by bgulla** [harvester/harvester#1203]
**Describe the bug**

I put in a bad value for the backup target (prepended the endpoint with s3://, which we should check for and strip or yell at user before save). When I went back to the UI to modify it, it is unable to complete and errors out with `{"data":"Handler disconnected\n"}`

**To Reproduce**
1. Create a backup target with a bad url scheme (include s3://)
2. After saving, you realize that `unsupported protocol scheme "s3"`
3. Edit the backup target, it will be unable to save due to: `{"data":"Handler disconnected\n"}`

**Environment:**
 - Harvester ISO version: 0.3-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Nuc9i9qnx bare-metal

**Comment by bgulla** [comment]
Update: after trying to use the harvester UI after I made the 'bad' urlscheme edit in the `backup-target`, it would seem that my harvester UI is now displaying fail-whale on every page with `{"data":"Handler disconnected\n"}`

restarting the node/cluster results in only the fail-whale screen

edit: upon further investigation, it seems that the `harvester` deployment in `harvester-system`is CrashLoopBackOff-ing. 
it seems that calico is unable to setup the network (cannot find /var/lib/calico/nodename). I doubt the backup target would bork calico, so I may be bumping into other issues.

**Comment by gitlawr** [comment]
From my testing editing the setting does not break the setup. Probably related to known networking issues https://github.com/harvester/harvester/issues/1207#issuecomment-917790342

Can you check logs of CNI pods in the kube-system namespace?

**Comment by guangbochen** [comment]
most likely it is related to the network error fixed via https://github.com/harvester/harvester/issues/1259

**Comment by guangbochen** [comment]
validated by input a bad backup-target config, e.g start with `s3://` it shows the error message correctly and no `{"data":"Handler disconnected\n"}` has occurred, this should be fixed via a network issue with #1259 and please feel free to reopen this if u have encountered it again.
![image](https://user-images.githubusercontent.com/4569037/134801968-86787cf6-503a-4930-8056-b9c02ebb78a7.png)
