### ISSUE TITLE
[BUG] `backup-target` button `Use Default Value` is always disabled

### ISSUE THREAD

**Issue by bgulla** [harvester/harvester#1204]
**Describe the bug**

I would like to revert to the default value as indicated by the `backup-target` button but it is disabled

**To Reproduce**
1. Add a backup target (mine was bad)
2. Try to click the `use default value` button to revert to a good configuration
3. it's disabled

**Environment:**
 - Harvester ISO version: 0.3-preview1

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/1051
