### ISSUE TITLE
[BUG] NICs not named correctly and status shows that they are down, though they are connected

### ISSUE THREAD

**Issue by axsms** [harvester/harvester#1205]
**Describe the bug**
In the GUI, at _Configure Network Connection_, the name and status of NICs is incorrect. There are two 10Gbps NICs that are connected and should be named ens3f0 and ens3f1. The remaining two NICs are 1Gbps and are not in use. 

Currently, what is shown is eth0, eth1, eth2, and eth3. And all say...
NIC <name> is down
Network cable isn't plugged in

Due to the inability to move forward, the install cannot be completed.

**To Reproduce**
1. Begin a normal install and attempt to select the appropriate NIC

**Expected behavior**
After selecting a connected NIC, the GUI should allow IPv4 Method to be selected and the install to continue. 

**Support bundle**
Unavailable

**Environment:**
 - Harvester ISO version: Master ISO 0.2.x (09/11/2021)
 - Underlying Infrastructure: Baremetal with Quanta QuantaGrid D51B-1U

**Additional context**
10G NICS are fiber, systems are remotely accessed via KVM, and managed with "remote hands".

**Comment by yasker** [comment]
@axsgitty are you use USB to install? Might be #1200

**Comment by axsms** [comment]
Yes. I'll follow the guidance there and let you know.

**Comment by axsms** [comment]
This was not resolved by implementing net.ifnames=1 as described in #1200

**Comment by yasker** [comment]
If you add `net.ifnames=1` and it took effect correctly, you shouldn't see `ethx` at all during the installation process.

**Comment by axsms** [comment]
Unfortunately, I am either doing something wrong or it's not sticking. I attempted to add `net.ifnames=1` to the end of the `e` list as noted in #1200, which I just attempted again. I also tried it from cmd line using `GRUB_CMDLINE_LINUX_DEFAULT="net.ifnames=1"`, which also failed...that was a shot in the dark.

**Comment by guangbochen** [comment]
this is only supported with either the [`master-head`](https://releases.rancher.com/harvester/master/harvester-amd64.iso) image or v0.3.0-preview image only, it is not supported with v0.2 version which I I think u are currently using?

**Comment by axsms** [comment]
That's correct. I'll have my remote folks try the [`master-head`](https://releases.rancher.com/harvester/master/harvester-amd64.iso) image.

**Comment by axsms** [comment]
Due to the remote hands situation, this is exponentially more difficult than doing this locally. With the [`master-head`](https://releases.rancher.com/harvester/master/harvester-amd64.iso) image, I do not see/get the option to edit parameters. Is this removed or happening too fast in that image? There is a very quick flash of less than a second from initial scroll of activity before the GUI is shown.
