### ISSUE TITLE
[BUG] No disk shows up when plugging a new disk to add to host

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#1208]
**Describe the bug**

After plugging a new disk to a host machine, the "Add Disk" action in `"Host" page > "Disks" panel` always shows "Sorry, no matching options.", but actually there are valid blockdevice CRs.

**To Reproduce**
1. Install v0.3.0-preview1 harvester
2. Plug a disk onto the host device
3. Head to the dashboard "Hosts" > "Disks". Then press "Add Disk" button

**Expected behavior**

- The extra disks shows up in dropdown and can be added and provisioned to the host machine.

**Environment:**
 - Harvester ISO version: v0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): kvm

![disk](https://user-images.githubusercontent.com/14314532/133016635-61d1457c-3aa2-43c8-a95c-9faf8d4ec730.png)

**Comment by weihanglo** [comment]
I've found the auto-created blockedevices for the plugged-in disk seems correct on my testing cluster.

I guess it may result from [filtering in only provisioned disks](https://github.com/harvester/dashboard/blob/master/edit/host/index.vue#L63-L69),  but I am not familiar with Vue. It should display non-provisioned disks as well.

<details>
<summary>valid extra blockdevice yaml</summary>

```yaml
apiVersion: harvesterhci.io/v1beta1
kind: BlockDevice
metadata:
  creationTimestamp: "2021-09-13T02:34:31Z"
  finalizers:
  - wrangler.cattle.io/harvester-block-device-handler
  generation: 3
  labels:
    kubernetes.io/hostname: h0
    ndm.harvesterhci.io/device-type: disk
  name: 251bebef4976180ab119911c667fdc64
  namespace: longhorn-system
  resourceVersion: "137236"
  uid: 73ea1051-f7ac-4c7c-8961-d15b5ecde52a
spec:
  devPath: /dev/vda
  fileSystem:
    mountPoint: ""
  nodeName: h0
status:
  conditions:
  - lastUpdateTime: "2021-09-13T02:34:32Z"
    status: "False"
    type: Mounted
  deviceStatus:
    capacity:
      physicalBlockSizeBytes: 512
      sizeBytes: 1048969216
    details:
      busPath: pci-0000:00:05.0
      deviceType: disk
      driveType: HDD
      model: unknown
      ptUUID: 8a44073a-f4df-41ee-b3b2-c8284eac4911
      serialNumber: unknown
      storageController: virtio
      vendor: "0x1af4"
      wwn: unknown
    fileSystem:
      isReadOnly: true
      mountPoint: ""
      type: ""
    partitioned: true
  state: Active
---
apiVersion: harvesterhci.io/v1beta1
kind: BlockDevice
metadata:
  creationTimestamp: "2021-09-13T02:34:32Z"
  finalizers:
  - wrangler.cattle.io/harvester-block-device-handler
  generation: 2
  labels:
    kubernetes.io/hostname: h0
    ndm.harvesterhci.io/device-type: part
    ndm.harvesterhci.io/parent-device: 251bebef4976180ab119911c667fdc64
  name: 679e7f6d014b683d889a9c1e9ec80948
  namespace: longhorn-system
  resourceVersion: "137240"
  uid: 4caf9028-9f04-48c9-88b0-21f792c0b3d8
spec:
  devPath: /dev/vda1
  fileSystem:
    mountPoint: ""
  nodeName: h0
status:
  conditions:
  - lastUpdateTime: "2021-09-13T02:34:32Z"
    status: "False"
    type: Mounted
  deviceStatus:
    capacity:
      physicalBlockSizeBytes: 512
      sizeBytes: 1047527424
    details:
      deviceType: part
      driveType: HDD
      partUUID: 2d522ea2-407b-4aaa-bbdd-9e852bf03ddd
      storageController: virtio
    fileSystem:
      isReadOnly: true
      mountPoint: ""
      type: ""
    parentDevice: /dev/vda
    partitioned: false
  state: Active
```

</details>

**Comment by guangbochen** [comment]
Verified using the `master-48c97ea7-head` version - pass
1. All disks and partitions are displayed correct on the Hosts => Edit Config => Disks tab
![image](https://user-images.githubusercontent.com/4569037/134848781-e266bba3-4e3c-4b8d-bca3-ab04998fe451.png)

1. Validate available disks on the node are matched with the UI (should exclude the loop and longhorn generated block devices)
![image](https://user-images.githubusercontent.com/4569037/134848858-9324e45f-2bb0-4aa2-82a8-abadf70f7183.png)

**Comment by lanfon72** [comment]
@weihanglo we don't provide partitioning function and didn't allowed user to format raw disk as #1285 and #1240 's result,
I think it is acceptable that new disk should not appeared in the UI until it has been partitioned.
(Raw disk is not allowed to be mounted in Linux, you need create at least one partition for it, so I think it should be the same for longhorn)

**Comment by weihanglo** [comment]
> (Raw disk is not allowed to be mounted in Linux, you need create at least one partition for it, so I think it should be the same for longhorn)

That's correct. However, Harvester provides users to create a single partition and format raw disk simultaneously in one-click. I think showing raw disk is required for this feature.

BTW, this issue should be fine and probably fixed.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1208#issuecomment-927540240

**Comment by janeczku** [comment]
It seems that the [expected behavior](https://github.com/harvester/harvester/issues/1208#issue-994388641) is not working yet (correctly) so this ticket should be reopened.

> Expected behavior
> The extra disks shows up in dropdown and can be added and provisioned to the host machine.

**Actual (0.3.0):**

Raw disk devices are displayed in the UI but **can not be selected and added** (disabled)
<img width="684" alt="Screenshot 2021-10-11 at 13 56 29" src="https://user-images.githubusercontent.com/3813921/136786565-6737d6ef-2512-4fbe-a085-e16ddc2855a9.png">

It is also unclear what steps are involved in order to add a raw (=unpartitioned) disk to Harvester via the UI. Managing both physical devices and partitions under the same `blockDevice` resource seem to add to the confusion.

**Comment by janeczku** [comment]
The above behavior is a bug. Tracking here: #1414
