### ISSUE TITLE
vm template status is not updated correctly when adding a new template version

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#121]
**Description:**
the vm template status of `latestVersion` is not updated correctly after adding a new template version, it should set the `latestVersion` to the version id of the newest template version.

**Comment by aiwantaozi** [comment]
step:
create a template version and check the set as default
check the template page, the default version number is correct, but the latest version isn't updated to the lastest one

reason:
in norman, UI can't update the object's status, even UI send status in the request body to the backend, the backend will use current status in etcd to replace it. But in steve, UI can update status. UI update the status to the old one.

**Comment by gitlawr** [comment]
@aiwantaozi In what cases the UI will update a vmtemplate with a stale version?

**Comment by aiwantaozi** [comment]
When UI set the default version may also send status with stale version, and on the template controller we don't recalculate the latestVersion before, so the latest version doesn't update.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/124

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/124
