### ISSUE TITLE
[BUG] Wrong management URL for the agent node.

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1210]
**Describe the bug**

For the agent node, the management URL is the IP of the master node plus port 30443, which should be the VIP.

![image](https://user-images.githubusercontent.com/7421463/133023476-bb879b4a-fbc8-4640-8e64-c7555775878e.png)

**To Reproduce**
1. Join a node into Harvester.
2. The dashboard panel will display the wrong management URL after installation.

**Expected behavior**

The dashboard panel display the management URL as the VIP.

**Support bundle**

**Environment:**
 - Harvester ISO version:  ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualbox

**Additional context**

**Comment by yaocw2020** [comment]
For the agent node, we use the kubeconfig of kubelet to access the apiserver. However, the kubeconfig of kubelet has no right to get configmaps, thus we fail to get the VIP from configmap vip.

**Comment by yaocw2020** [comment]
To test:
- Add an agent node to an existing Harvester cluster
- To check the dashboard panel, it will show the management URL as the VIP.

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head with two nodes. Fixed.
