### ISSUE TITLE
[FEATURE] Harvester ISO name and checksum enhancement

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1211]
**Is your feature request related to a problem? Please describe.**
We are currently pulling the release artifacts in Jenkins using the following URLs, prefer to make the ISO release name more consistent across master-head and tagged versions, so we don't have to special-case the code. 
e.g the master-head image will be called `harvester-master-amd64.sio` with `harvester-$tag-$arch.iso` parttern.

```
 - "https://releases.rancher.com/harvester/{{ harvester_release }}/harvester-initrd-amd64"
 - "https://releases.rancher.com/harvester/{{ harvester_release }}/harvester-vmlinuz-amd64"
 - "https://releases.rancher.com/harvester/{{ harvester_release }}/harvester-amd64.iso"
```

Additionally, we should add all file's checksum to the `harvester-$version-$arch.sha256` file of each tagged release.

**Describe the solution you'd like**
- align the master-head ISO release name with the tagged one
- add all file's checksum to the sha256 file.

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Feature verified pass on master-c4a76706-head and later
The daily build artifacts file name have renamed to the following (add master-head tag):

- https://releases.rancher.com/harvester/master/harvester-master-amd64.iso 
- https://releases.rancher.com/harvester/master/harvester-master-initrd-amd64
- https://releases.rancher.com/harvester/master/harvester-master-rootfs-amd64.squashfs
- https://releases.rancher.com/harvester/master/harvester-master-vmlinuz-amd64
- https://releases.rancher.com/harvester/master/harvester-master-amd64.sha256

Checked alll file's checksum have already added to the harvester-$version-$arch.sha256 file
 `sha256sum -c harvester-master-amd64.sha256`
 
![sha256_check](https://user-images.githubusercontent.com/29251855/136491453-288f70bd-bf58-464d-bb88-889853cd3f15.png)
