### ISSUE TITLE
[FEATURE] Installer: enhance UX in network configuration panel

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1212]
**Is your feature request related to a problem? Please describe.**
It takes time to configure an interface (especially in DHCP mode), the text-UI freezes after selecting an interface mode.
![Screen Shot 2021-09-13 at 3 12 15 PM](https://user-images.githubusercontent.com/1691518/133039812-27d59563-1801-428b-b3e6-1035c73a952d.png)

**Describe the solution you'd like**
We can:
- Add a spinner to let the user know the configuration is in process.
- Preview the offered IP in DHCP mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by FrankYang0529** [comment]
## Test info

Verified version: master-e617c6ae-head

## Test cases

* Run installer on KVM with DHCP server
  * [x] Show applying message for DHCP mode
![Screenshot from 2021-10-04 14-30-38](https://user-images.githubusercontent.com/4927361/135807193-1ef0a4a1-b498-4eb9-933a-856eeb94ff29.png)
  * [x] Show applying message for Static mode
![Screenshot from 2021-10-04 14-51-04](https://user-images.githubusercontent.com/4927361/135807267-e81c46ca-8951-42a6-98d8-0396b85e7059.png)

* Run installer on KVM without DHCP server
  * [x] Show error message
![Screenshot from 2021-10-04 14-58-51](https://user-images.githubusercontent.com/4927361/135807369-31cd270b-3946-44b0-a928-b0dc3987ae5f.png)
