### ISSUE TITLE
[BUG] DNS servers offered by DHCP server are not set in PXE boot installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1214]
**Describe the bug**
The DNS servers offered by the DHCP server are not configured in the PXE boot installation time.
If the Harvester configuration file is served from a server that needs name resolution, the installation will fail.

**To Reproduce**
1. Create a DHCP server to offer IPs and DNS servers for PXE boot installation.
2. Perform PXE boot installation. The DNS servers are not configured correctly:
```
rancher:~ # cat /etc/resolv.conf
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
```

**Expected behavior**
The DNS servers provided by the DHCP server should be configured in the `/etc/resolv.conf` file.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VM, Equnix.

**Additional context**

- The name servers are set correctly during the initramfs stage, but not configured correctly in the real root.
- This is an issue caused by the [predictable interface name change](https://github.com/harvester/harvester-installer/pull/118/files#diff-da6d6162c492135baaa5d8aad8873ec00226c59cd63c8edbdbd8b44b13a37639R9-R10).
Previously, we have a configuration file `/etc/sysconfig/network/ifcfg-eth0` to make interface `eth0` default to DHCP mode and wicked brings up `eth0` in a later stage. The DNS serves will be re-configured at that time. The file is removed in the PR.
- We also need to consider booting from another interface.
- This only affects PXE boot installation. The DNS servers are set correctly if user boots from ISO.

**Comment by guangbochen** [comment]
@guangyee can u guys please help to verify if this is fixed in the master-head.iso, thanks

**Comment by juadk** [comment]
I was impacted by this issue and now it's ok with the last master-head.iso.
`/etc/resolt.conf `is filled with the good DNS information and I'm able to download the harvester ISO and the config file using the DNS name of my webserver.
