### ISSUE TITLE
[BUG] Failed to PXE boot the latest master ISO in vagrant environment

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1220]
**Describe the bug**
Latest master ISO failed to install in Vagrant PXE environment (https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester)

https://releases.rancher.com/harvester/master/harvester-amd64.iso
https://releases.rancher.com/harvester/master/harvester-vmlinuz-amd64
https://releases.rancher.com/harvester/master/harvester-initrd-amd64

RKE2 server failed to properly install because it was trying to download images from docker.io. The ISO is supposed to contain all the images required by RKE2.

**To Reproduce**
1. Clone https://github.com/harvester/ipxe-examples.git
2. cd vagrant-pxe-harvester
3. ./setup_harvester.sh
4. Notice that the first node `harvester-node-0` failed to install.

**Expected behavior**
Harverster node successfully install.

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant pxe

**Additional context**

**Comment by guangyee** [comment]
This problem doesn't seem consistently reproducible. So far, the installation went through successfully on the second and third try.

**Comment by guangbochen** [comment]
@guangyee  could this be related to the https://github.com/harvester/harvester/issues/1243, or can u verify with the `master-head` image to check whether this issue has been addressed or not, thanks.

**Comment by guangyee** [comment]
Problem was due to an extra (disabled) NIC in the Vagrant environment. Because we are using `ip=dhcp` in the PXE parameter, the disabled NIC can be selected by the installed as NIC naming/ordering is rather unpredictable. The issue was effectively fixed by specifying the precise NIC to use for installation. https://github.com/harvester/ipxe-examples/pull/20 fixed the problem.

**Comment by guangyee** [comment]
Fixed by https://github.com/harvester/ipxe-examples/pull/20
