### ISSUE TITLE
[BUG] If you enable a VLAN NIC after install dashboard stops loading

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1222]
**Describe the bug**

If you specify a NIC for the VLAN after install the dashboard stops loading
**To Reproduce**
1. Install harvester
2. Go to advanced settings
3. Edit config for VLAN
4. Enable then specify second NIC name in interface
5. Save
6. Refresh page

**Expected behavior**

The NIC should save and the dashboard should load
**Support bundle**

**Environment:**
 - Harvester ISO version: master from yesterday
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized environment

**Additional context**
I got the NIC name from `ip link` in the console/SSH. This was in a KVM virtualized environment using 2 virtIO NICs.

**Comment by WuJun2016** [comment]
@noahgildersleeve 
Didn't understand what problem was encountered. Does it mean that you cannot access the UI after configuring the NIC?
You can add a screenshot to tell me what problem you encountered。

**Comment by andrehofman** [comment]
I have the same problem. it got back online after a manual restart of all network-related pods.

**Comment by noahgildersleeve** [comment]
Here's the support bundle
[bundle.zip](https://github.com/harvester/harvester/files/7171927/bundle.zip)

**Comment by guangyee** [comment]
I can also reproduce this issue on my 3-node vagrant environment.

**Comment by guangyee** [comment]
Right now it appears enabling network on management NIC renders the entire cluster non-functional.

**Comment by yasker** [comment]
Same here as Guang mentioned with the latest master image.

**Comment by guangbochen** [comment]
The root cause is because the first management NIC name is set as the default canal iface, it will make the cluster network dysfunctional if the other node has a different management NIC name, a temporary solution is to set the `flannel.iface` config to empty and use the default route config.
```
kubectl edit helmchartconfigs.helm.cattle.io rke2-canal -n kube-system 
# set spec.valuesContent.flannel.iface to "" and restart the canal pods
```

A proper fix will be addressed via https://github.com/harvester/harvester/issues/1207 with using the `bond` NIC.

**Comment by guangbochen** [comment]
and multi NICs case is fixed via https://github.com/harvester/harvester/issues/1259

**Comment by noahgildersleeve** [comment]
Tested in master-1a041d23-head with 2 NICs on 2 node cluster. Fixed.
