### ISSUE TITLE
[BUG] USB Boot hangs indefinitely at `fb0: switching to amdgpudrmfb from EFI VGA`

### ISSUE THREAD

**Issue by jesseagonzalez** [harvester/harvester#1225]
**Describe the bug**

Tried to boot Harvester v0.3.0 preview image via USB and screen hangs at `fb0: switching to amdgpudrmfb from EFI VGA`. Screenshot below.

As interim solution, I supplied the `nomodeset` option after kernel parameter by hitting `e` on bootup during the initial install of harvester, and subsequently after the initial startup.

It's worth noting that I have 3 nodes with identical specs, and each exhibited the same behavior.

**To Reproduce**

1. Boot to USB
2. Select `cOS Live` option
3. Within 12-16 seconds, boot sequence will hang indefinitely with error above.

**Expected behavior**

I have deployed previous version of harvester and this was not an issue on boot, so expectation would be similar behavior.

**Environment:**

 - Harvester ISO version:  v0.3.0 preview
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 
   - Baremetal with Intel NUC 8i7HVK (Hades Canyon), 32 GB of RAM, Radeon RX Vega M GH graphics GPU

**Additional context**

![BootError](https://user-images.githubusercontent.com/8986826/133408007-04c6a3ca-2745-4763-b52b-3171a7218111.jpg)

**Comment by krumware** [comment]
This is also experienced by some machines as a blank screen, both during installation and runtime.
`nomodeset` also works as a temporary workaround in those cases.

**Comment by bk201** [comment]
Could be we didn't ship the `kernel-firmware-amdgpu` package in the OS.

**Comment by himslm01** [comment]
Same issue with the released version of v0.3.0.

I understand how to add `nomodeset` when installing from the ISO, and how to add `nomodeset` when booting into Harvester. But how do I add `nomodeset` as a permanent option so I don't have to type it when I'm booting?

Googling suggests I need to edit `/etc/default/grub` then run `grub2-mkconfig -o /boot/grub2/grub.cfg` but that fails with `/usr/sbin/grub-probe: error: failed to get canonical path of 'overlay'`.
 
Of cause, `/` is ro and `/boot` is overlay. How can I fudge my way around this problem.

Also mentioned in https://rancher-users.slack.com/archives/C01GKHKAG0K/p1634146413358500 and https://rancher-users.slack.com/archives/C01GKHKAG0K/p1634152907360200

**Comment by JimWilson** [comment]
Piling on.

Hang on boot at: fb0: switching to amdgpudrmfb from EFI VGA

harvester-v0.3.0-amd64.iso

CPU: AMD FX8350
GPU: AMD RX570
BIOS: UEFI: IOMMU enabled
RAM: 32G

boot log fragment

16.098676] [drm] amdgpu kernel modesetting enabled.
16.099716] CRAT table not found
16.101756] Virtual CRAT table created for CPU
16.103834] amdgpu: Topology: Add CPU node
16.106014[ fb0: switching to amdgpudrmfb from EFI VGA


Boot succeeded on:

CPU: AMD 5700G
GPU: AMD 5700G
BIOS: UEFI: IOMMU enabled
RAM: 32G

**Comment by bk201** [comment]
@himslm01 Please check https://docs.harvesterhci.io/v0.3/troubleshooting/os/#how-to-permanently-edit-kernel-parameters for how to set the kernel parameters permanently in 0.3.0.

**Comment by u2m4c6** [comment]
> Could be we didn't ship the `kernel-firmware-amdgpu` package in the OS.

If that is the case, I strongly recommend including that with the OS. AMD GPU's and APU's are very common these days, especially as AMD CPU's dominate at pretty much every level. Even though Harvester is primarily targeted at server hardware (I think), adoption will be greatly helped if we can plug and play Harvester at home or on a spare rig at work.

**Comment by bk201** [comment]
@u2m4c6 We'll include VGA firmwares. I can confirm including the firmware fix the problem on my local PC (a discrete AMD VGA card)

**Comment by krumware** [comment]
Thanks y'all! I'll also retry this on some older hardware once another release is available

**Comment by simonflood** [comment]
Is it possible to get a new build of Harvester 0.3.0 with the missing firmware included? I've tried installing it on some older VGA-only servers and seeing (or not!) the blank screen. Adding nomodeset gets me to the install but after typing in a hostname and pressing Enter (whether creating a new cluster or joining an existing one) it takes me back to the Installation Mode screen. This is happening on two different makes/models of servers and I've also tried two different USB keyboards.

**Comment by guangbochen** [comment]
> Is it possible to get a new build of Harvester 0.3.0 with the missing firmware included? I've tried installing it on some older VGA-only servers and seeing (or not!) the blank screen. Adding nomodeset gets me to the install but after typing in a hostname and pressing Enter (whether creating a new cluster or joining an existing one) it takes me back to the Installation Mode screen. This is happening on two different makes/models of servers and I've also tried two different USB keyboards.

You can download and test the latest ISO build from the https://releases.rancher.com/harvester/master/harvester-master-amd64.iso, but please keep in mind this is master-head version and just use it for validation purpose, thanks

**Comment by simonflood** [comment]
> You can download and test the latest ISO build from the https://releases.rancher.com/harvester/master/harvester-master-amd64.iso, but please keep in mind this is master-head version and just use it for validation purpose, thanks

Thanks, the latest ISO build (af921bf) worked a treat on an older VGA-only server. No need to use nomodeset plus the keyboard worked fine too and I was able to progress through installer menus.

**Comment by guangbochen** [comment]
The VGA firmware support is added in the [v1.0.0-rc1 release](https://github.com/harvester/harvester/releases/tag/v1.0.0-rc1), feel free to reopen it if u encounter this error again, thanks.
