### ISSUE TITLE
[BUG]Timing Issues while destroying the resources created by Terraform

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1227]
**Describe the bug**
I am creating a VM using the terraform (https://github.com/harvester/terraform-provider-harvester/blob/master/examples/resources/harvester_virtualmachine/resource.tf). All the resources are created successfully and VM is is running state. During the terraform destroy, the first time the VM is deleted but not the attached volumes as it attempts to delete Volume before the VM is deleted
harvester_ssh_key.t-7a727cc9010b418786cb819a06c76629: Destroying... [id=default/t-7a727cc9010b418786cb819a06c76629]
harvester_virtualmachine.t-4b8ab968b3ce431c9e26d09ee75c0fad: Destroying... [id=default/t-4b8ab968b3ce431c9e26d09ee75c0fad]
harvester_ssh_key.t-7a727cc9010b418786cb819a06c76629: Destruction complete after 0s
harvester_virtualmachine.t-4b8ab968b3ce431c9e26d09ee75c0fad: Destruction complete after 0s
harvester_volume.t-a0e16bd1d40d4a238f5682b75b1c373e: Destroying... [id=default/t-a0e16bd1d40d4a238f5682b75b1c373e]
harvester_network.t-16aa98e6c84a424a9442fba25445a73e: Destroying... [id=harvester-public/t-16aa98e6c84a424a9442fba25445a73e]
harvester_volume.t-d28fd26f4a594b87aa2ec1159cfae254: Destroying... [id=default/t-d28fd26f4a594b87aa2ec1159cfae254]
harvester_network.t-16aa98e6c84a424a9442fba25445a73e: Destruction complete after 0s
╷
│ Error: admission webhook "validator.harvesterhci.io" denied the request: can not delete the volume t-d28fd26f4a594b87aa2ec1159cfae254 which is currently attached to VMs: default/t-4b8ab968b3ce431c9e26d09ee75c0fad
│ 
│ 
╵
╷
│ Error: admission webhook "validator.harvesterhci.io" denied the request: can not delete the volume t-a0e16bd1d40d4a238f5682b75b1c373e which is currently attached to VMs: default/t-4b8ab968b3ce431c9e26d09ee75c0fad
After running terraform destroy again, the volumes are deleted
harvester_volume.t-d28fd26f4a594b87aa2ec1159cfae254: Destroying... [id=default/t-d28fd26f4a594b87aa2ec1159cfae254]
harvester_volume.t-a0e16bd1d40d4a238f5682b75b1c373e: Destroying... [id=default/t-a0e16bd1d40d4a238f5682b75b1c373e]
harvester_volume.t-a0e16bd1d40d4a238f5682b75b1c373e: Destruction complete after 0s
harvester_volume.t-d28fd26f4a594b87aa2ec1159cfae254: Destruction complete after 0s
harvester_image.t-b932ad526ec745eeae6da97df56b902d: Destroying... [id=harvester-public/t-b932ad526ec745eeae6da97df56b902d]
╷
│ Error: admission webhook "validator.harvesterhci.io" denied the request: Cannot delete image harvester-public/t-b932ad526ec745eeae6da97df56b902d: being used by volume default/t-d28fd26f4a594b87aa2ec1159cfae254
Third time when I run terraform destroy, the image is deleted
harvester_image.t-b932ad526ec745eeae6da97df56b902d: Destroying... [id=harvester-public/t-b932ad526ec745eeae6da97df56b902d]
harvester_image.t-b932ad526ec745eeae6da97df56b902d: Destruction complete after 0s

Destroy complete! Resources: 1 destroyed.

**To Reproduce**
1. Create resources which depends on other resources using terraform

**Expected behavior**
During terraform destroy the resources should be destroyed in the order

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):Ipxe Vagrant env

**Additional context**

**Comment by futuretea** [comment]
@chajain can u provide your tf files and terraform-provider-harvester version?

**Comment by chajain** [comment]
@futuretea Following are the tf files I used

provider.tf
terraform {
  required_version = ">= 0.13"
  required_providers {
    harvester = {
      source  = "registry.terraform.io/harvester/harvester"
      version = "~> 0.2.2"
    }
  }
}

provider "harvester" {
  kubeconfig = "/root/harv-ter/tests/terraform_test_artifacts/.kube/config"
}

resource_image.tf
resource "harvester_image" "t-6b3c4b2c245f41d889c64c2b41be692d" {
  name         = "t-6b3c4b2c245f41d889c64c2b41be692d"
  namespace    = "harvester-public"
  display_name = "t-6b3c4b2c245f41d889c64c2b41be692d"
  url          = "http://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.2/images/openSUSE-Leap-15.2.x86_64-NoCloud.qcow2"
  source_type  = "download"

  lifecycle {
    ignore_changes = all
  }
}

resource_keypair.tf
resource "harvester_ssh_key" "t-9972659c85444aa3810e48a3baae30f6" {
  name        = "t-9972659c85444aa3810e48a3baae30f6"
  public_key  = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDE8iu9Z6JlCjKyIgTHhm/A4fLcczIENVd7F0ZgeHZUJyB4Pf/VHZUzIlbbnxM53QaAnUEd6uRn5GTYJ5yeZhqP7JuatROuFmAySSkMCyk/SF6hzPKf8VnzlKc0FKh5wA976KBDZmXtJuLajwZgZVJn2XxnE+OT8bQjn6QYP9OcNQ=="

  lifecycle {
    ignore_changes = all
  }
}

resource_network.tf
resource "harvester_network" "t-ad8be02015c14921ae69dd1635b1f536" {
  name      = "t-ad8be02015c14921ae69dd1635b1f536"
  namespace = "harvester-public"

  vlan_id = 10

  lifecycle {
    ignore_changes = all
  }
}

resource_vm.tf
resource "harvester_virtualmachine" "t-416fbb6a8f004d4ebdc54e1a7cb70773" {
  depends_on = [harvester_volume.t-2898d6227a0a495d801c470264fa7afa, harvester_volume.t-97d05a5245f3445b9445a1772d7df844, harvester_network.t-ad8be02015c14921ae69dd1635b1f536]

  name        = "t-416fbb6a8f004d4ebdc54e1a7cb70773"
  description = "test raw image"

  tags = {
    ssh-user = "root"
  }

  cpu    = 1
  memory = "2Gi"

  start        = true
  hostname     = "t-416fbb6a8f004d4ebdc54e1a7cb70773"
  machine_type = "q35"

  ssh_keys = [
    "t-9972659c85444aa3810e48a3baae30f6"
  ]

  network_interface {
    name         = "default"
    model        = "virtio"
    type         = "masquerade"
  }

  network_interface {
    name         = "nic-1"
    model        = "virtio"
    type         = "bridge"
    network_name = "harvester-public/t-ad8be02015c14921ae69dd1635b1f536"
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    existing_volume_name = "t-97d05a5245f3445b9445a1772d7df844"
    auto_delete          = false
  }

  disk {
    name = "mount-disk"
    type = "disk"
    bus  = "virtio"

    existing_volume_name = "t-2898d6227a0a495d801c470264fa7afa"
    auto_delete          = false
}

  cloudinit {
    user_data    = "#cloud-config\nchpasswd:\n  list: |\n    root:linux\n  expire: false\nssh_pwauth: true\nusers:\n  - name: root\n    ssh_authorized_keys:\n      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAAAgQDE8iu9Z6JlCjKyIgTHhm/A4fLcczIENVd7F0ZgeHZUJyB4Pf/VHZUzIlbbnxM53QaAnUEd6uRn5GTYJ5yeZhqP7JuatROuFmAySSkMCyk/SF6hzPKf8VnzlKc0FKh5wA976KBDZmXtJuLajwZgZVJn2XxnE+OT8bQjn6QYP9OcNQ==\npackage_update: true\npackages:\n  - qemu-guest-agent\nruncmd:\n  - - systemctl\n    - enable\n    - '--now'\n    - qemu-ga\n"
    network_data = "#cloud-config\nversion: 1\nconfig:\n  - type: physical\n    name: eth0\n    subnets:\n      - type: dhcp\n  - type: physical\n    name: eth1\n    subnets:\n      - type: dhcp\n"
  }
}

resource_volume_image.tf
resource "harvester_volume" "t-97d05a5245f3445b9445a1772d7df844" {
  depends_on = [harvester_image.t-6b3c4b2c245f41d889c64c2b41be692d]
  name  = "t-97d05a5245f3445b9445a1772d7df844"
  size  = "10Gi"
  image = "harvester-public/t-6b3c4b2c245f41d889c64c2b41be692d"

  lifecycle {
    ignore_changes = all
  }
}

resource_volume.tf
resource "harvester_volume" "t-2898d6227a0a495d801c470264fa7afa" {
  name  = "t-2898d6227a0a495d801c470264fa7afa"
  size  = "10Gi"

  lifecycle {
    ignore_changes = all
  }
}

**Comment by chajain** [comment]
@futuretea @guangbochen Can you Please cut a new release of terraform-harvester-provider.

**Comment by chajain** [comment]
@futuretea @guangbochen I installed version 0.2.3 and still see the issues during destroy of virtual machine. It fails with error
harvester_ssh_key.t-d966367d61c04d1eb40978ea6dd0c1f3: Destroying... [id=default/t-d966367d61c04d1eb40978ea6dd0c1f3]
harvester_virtualmachine.t-e6555978e29d48e5b61ce29ae902b132: Destroying... [id=default/t-e6555978e29d48e5b61ce29ae902b132]
harvester_ssh_key.t-d966367d61c04d1eb40978ea6dd0c1f3: Destruction complete after 0s
harvester_virtualmachine.t-e6555978e29d48e5b61ce29ae902b132: Still destroying... [id=default/t-e6555978e29d48e5b61ce29ae902b132, 10s elapsed]
╷
│ Error: timeout waiting for virtualmachine default/t-e6555978e29d48e5b61ce29ae902b132 to be deleted

The destroy of all resources is successful after the second attempt
harvester_network.t-02442f242afd4c43b6f04457f5f746e9: Destroying... [id=harvester-public/t-02442f242afd4c43b6f04457f5f746e9]
harvester_volume.t-788583493c724e568c88c3737190d3d2: Destroying... [id=default/t-788583493c724e568c88c3737190d3d2]
harvester_image.t-6e456125d6c046d6a360f2cc77528217: Destroying... [id=harvester-public/t-6e456125d6c046d6a360f2cc77528217]
harvester_image.t-6e456125d6c046d6a360f2cc77528217: Destruction complete after 0s
harvester_volume.t-788583493c724e568c88c3737190d3d2: Destruction complete after 0s
harvester_network.t-02442f242afd4c43b6f04457f5f746e9: Destruction complete after 0s

Destroy complete! Resources: 3 destroyed.

**Comment by futuretea** [comment]
@chajain  This error occurs because the VM has not been deleted successfully after 15s. Could you please help confirm how long it will take for the VM to be deleted in your environment?

**Comment by chajain** [comment]
@futuretea On my env it took atleast 20-25 secs to terminate the VM

**Comment by futuretea** [comment]
@chajain Increase timeout to 300s and fix cloud-init bug in release [v0.2.5](https://github.com/harvester/terraform-provider-harvester/releases/tag/v0.2.5)

**Comment by chajain** [comment]
@futuretea On a 3 node harvester setup we are also encountering the i/o timeout sometimes during creation of a resource or destroy of the resource for images, volumes, keypairs  and networks also.
AssertionError: Failed to run terraform : rc: 1, stdout: bError:Post "https://192.168.0.30:30443/apis/k8s.cni.cncf.io/v1/namespaces/harvester-public/network-attachment-definitions": dial tcp 192.168.0.30:30443: i/o timeout with harvester_network.t-1de8f15a940b44cb85aaa7007f4eea43 on resource_network.tf line 1, in resource "harvester_network" "t-1de8f15a940b44cb85aaa7007f4eea43":\n\x1b[31m\xe2\x94\x82\x1b[0m \x1b[0m   1: resource "harvester_network" "t-1de8f15a940b44cb85aaa7007f4eea43"

AssertionError: Failed to run terraform : rc: 1, stdout: b'Error:Post "https://192.168.0.30:30443/api/v1/namespaces/default/persistentvolumeclaims": dial tcp 192.168.0.30:30443: i/o timeout\   with harvester_volume.t-25fc9103bf37446199205322469e1fc0,\ on resource_volume.tf line 1, in resource "harvester_volume" "t-25fc9103bf37446199205322469e1fc0":\n   1: resource "harvester_volume" "t-25fc9103bf37446199205322469e1fc0" 

Can you please increase the timeouts for creation and destroy of volumes, images, keypair and network resources also?

**Comment by futuretea** [comment]
@chajain 

> Can you please increase the timeouts for creation and destroy of volumes, images, keypair and network resources also?

There is no any timeout code for these resources.

> dial tcp 192.168.0.30:30443: i/o timeout 

This should be a network timeout

**Comment by chajain** [comment]
@futuretea I  see these error messages while creating resources 
cjain-leap:~/harv-ter/tests/terraform_test_artifacts/terraformharvester # TF_CLI_CONFIG_FILE=../dev.tfrc terraform apply -input=false tfplan
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - harvester/harvester in /root/harv-ter/tests/terraform_test_artifacts/.terraform.d/plugins/registry.terraform.io/harvester/harvester/0.2.3/linux_amd64
│ 
│ The behavior may therefore not match any released version of the provider and applying
│ changes may cause the state to become incompatible with published releases.
╵
harvester_ssh_key.t-21e4455e6cba4e0798d099009def7096: Creating...
harvester_ssh_key.t-21e4455e6cba4e0798d099009def7096: Still creating... [10s elapsed]
harvester_ssh_key.t-21e4455e6cba4e0798d099009def7096: Still creating... [20s elapsed]
harvester_ssh_key.t-21e4455e6cba4e0798d099009def7096: Still creating... [30s elapsed]
╷
│ Error: Post "https://192.168.0.30:30443/apis/harvesterhci.io/v1beta1/namespaces/default/keypairs": dial tcp 192.168.0.30:30443: i/o timeout
│ 
│   with harvester_ssh_key.t-21e4455e6cba4e0798d099009def7096,
│   on resource_keypair.tf line 1, in resource "harvester_ssh_key" "t-21e4455e6cba4e0798d099009def7096":
│    1: resource "harvester_ssh_key" "t-21e4455e6cba4e0798d099009def7096" {

**Comment by futuretea** [comment]
@chajain  The k8s apiserver port should be 6443, not 30443, can you check the kubeconfig is correct?

**Comment by chajain** [comment]
Tested using the latest terraform-harvester-provider 0.2.5. The VM is created and destroyed successfully using terraform. Used the same resource as mentioned earlier in the Bug.
