### ISSUE TITLE
[BUG] tty console shows dev version

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1231]
**To Reproduce**
1. Install v0.3.0-preview1
2. Check the console
![image](https://user-images.githubusercontent.com/5697937/133575866-22382742-09d2-4e99-af2a-5b36c5f30612.png)

**Environment:**
 - Harvester ISO version: v0.3.0-preview1

**Comment by johnliu55tw** [comment]
I think we should show both harvester version and harvester-installer version, something like this (I removed the _version_ from the title for simplicity): 
![image](https://user-images.githubusercontent.com/5047724/134483299-14d2cd2d-924f-4b18-9744-8626bb66fc07.png)

Now I'm thinking how can I get the version of harvester while building harvester-installer? **harvester-installer** is built at `build` stage,  prior to the `build-bundle` stage which `git clone` the **harvester** source. In this case, we can't determine the version of harvester while building **harvester-installer**.

Few options I could think of:
1. `git clone harvester` at the `build` stage to determine the version of harvester, then reuse this cloned source at `build-bundle` stage.
2. Store the harvester version as an environment variable, and harvester-installer fetches the version from this environment variable at run-time. In other words, harvester version would not be compiled into the executable

I would probably try the first option. @bk201 @gitlawr feel free to give any thoughts, thanks!

**Comment by gitlawr** [comment]
The screenshot is the console post-installation, I doubt if we want to show the installer version there. I would suggest we show that in the installation procedure if it matters.

Please note that the tagged ISO is built in [harvester CI](https://github.com/harvester/harvester/blob/1a041d2371c5e70419bbe2a6997e8756054ab58c/.drone.yml#L218).  Harvester version should be available from the git tag

**Comment by lanfon72** [comment]
Verified the `version` following ISO version, snapshots as below:
![image](https://user-images.githubusercontent.com/5169694/135420735-81fe7ca0-97fb-4999-b178-960000a2c092.png)
(for the `v0.3.0-rc1`)
![image](https://user-images.githubusercontent.com/5169694/135420762-e24e99db-693b-4962-a9e6-c2ae1a221928.png)
(for the `master-head`)
