### ISSUE TITLE
[BUG] The VM details page displays an incorrect image name

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1232]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/8905ed51-f65e-4619-b135-3a817a6ff2ee)

**Expected behavior**

The displayName of the image should be displayed

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
verified with the `master-48c97ea7-head`, the image name is showing correctly.
![image](https://user-images.githubusercontent.com/4569037/135096614-c0bcf4ab-2dc4-47f0-befe-25e2c7be07ad.png)
