### ISSUE TITLE
[Question]how to ssh to guest OS?

### ISSUE THREAD

**Issue by wonleing** [harvester/harvester#1233]
Here's current situation:
hostos:  10.10.54.x
harvester pod: 10.52.0.x
guestos: 10.0.2.x

I want to ssh from network of hostos to guestos.
On original kubevirt, pod IP equeals to guestos IP, so I can make it by exposing pod port 22  to hostos port 3xxxx. But how can I expose guestos port 22 to hostos port on harvester?

**Comment by guangbochen** [comment]
- for the pod IP u can only access it on the Harvester nodes(or u can export the kubeconfig file(/etc/rancher/k3s or rke2(`if using v0.3.x or the master-head version`)) and expose it using https://kubevirt.io/user-guide/virtual_machines/service_objects/#expose-virtualmachineinstance-as-a-nodeport-service or https://kubevirt.io/user-guide/virtual_machines/accessing_virtual_machines/) (Note: the pod IP is ephemeral)
- u can enable the VLAN network and access it with the VLAN network IP, this IP will be persisted and is retrieved either from a DHCP server or statically. https://docs.harvesterhci.io/v0.2/harvester-network/

**Comment by wonleing** [comment]
Thank you. I enabled the VLAN network, then guestos IP equals to pod IP. And use `kubectl label pod virt-launcher-xxxxxxx app=vm;kubectl create service nodeport vm --tcp=22` to expose nodeport service

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1233#issuecomment-922246696
