### ISSUE TITLE
[BUG] VMs are crashing when writing bulk data to additional volumes

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1234]
**Describe the bug**

Running `dd` to write data to an additional volume causes the VM to crash.

**To Reproduce**
1. Create a VM with an additional volume attached. Configure VM Memory limit to 10GB.
2. Run`dd if=/dev/zero of=/dev/sda bs=1M conv=sync` on the volume and wait for 10-20 seconds
3. The VM crashes and is automatically restarted

**Expected behavior**

A VM should not crash when writing data to a secondary disc.

**Environment:**
 - Harvester ISO version: 0.3.0-preview

**Additional context**

It appears the qemu pod is OOM killed because it exceeds the memory limit of 10GB that Harvester has configured.

```
Sep 16 08:38:09 lpedge01003 kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=06ea4e4c81e3b77d6c6d4d150016783adb9476391a3d713e4ccf0180889a4557,mems_allowed=0-1,oom_memcg=/kubepods/pod4f6371a7-c7ea-416a-837a-a4692d874756,task_memcg=/kubepods/pod4f6371a7-c7ea-416a-837a-a4692d874756/06ea4e4c81e3b77d6c6d4d150016783adb9476391a3d713e4ccf0180889a4557,task=qemu-system-x86,pid=1526,uid=107
Sep 16 08:38:09 lpedge01003 kernel: Memory cgroup out of memory: Killed process 1526 (qemu-system-x86) total-vm:11226804kB, anon-rss:10439204kB, file-rss:24704kB, shmem-rss:4kB
Sep 16 08:38:09 lpedge01003 kernel: oom_reaper: reaped process 1526 (qemu-system-x86), now anon-rss:0kB, file-rss:12kB, shmem-rss:4kB
```

**Comment by janeczku** [comment]
https://github.com/kubevirt/kubevirt/issues/4560

**Comment by FrankYang0529** [comment]
I can reproduce the bug on harvester v0.3.0-preview1, but not on v0.2.0. After checking resources yaml, I find that v0.3.0-preview1 has `limits` for memory, but v0.2.0 doesn't. However, even if I add `limits` on the `VirtualMachine` resource and restart the VM, v0.2.0 still works fine.

I will try to create VM on KubeVirt directly with other storage provider and check whether it's upstream issue.

**Comment by alexdepalex** [comment]
For me it seems like the memory limit applies to the entire pod. So that includes the qemu process plus the additional supporting processes (`virt-lancher`, `virtlogd`, `libvirtd`). When the vm allocates all available memory, the total consumed memory exceeds the set limit, and the qemu process is killed off.

When setting `spec.domain.memory.guest` to the vm memory size, and setting the memory limit for to pod to a higher value, the issue doesn't occur anymore.

**Comment by FrankYang0529** [comment]
> For me it seems like the memory limit applies to the entire pod. So that includes the qemu process plus the additional supporting processes (`virt-lancher`, `virtlogd`, `libvirtd`). When the vm allocates all available memory, the total consumed memory exceeds the set limit, and the qemu process is killed off.
> 
> When setting `spec.domain.memory.guest` to the vm memory size, and setting the memory limit for to pod to a higher value, the issue doesn't occur anymore.

Yes, I try to modify yaml as following and it works.

```
spec:
  template:
    spec:
      domain:
        memory:
          guest: 9Gi
        ...
        resources:
          limits:
            cpu: "1"
            memory: 10Gi
          requests:
            cpu: "1"
            memory: 10Gi
```

**Comment by guangbochen** [comment]
This can be addressed from the UI side by not setting the `spec.domain.memory.guest` to the full-size of the memory limits, set it with a proper percentage discount e.g 95%. cc @WuJun2016

**Comment by FrankYang0529** [comment]
From https://github.com/kubevirt/kubevirt/issues/5958#issuecomment-872642909, KubeVirt already add extra memory for Pods, but it's probably not enough in our case.

In harvester-v0.3.0-preview1, I set `spec.domain.memory.guest` as `9.9Gi` and it still can work.

**Comment by guangbochen** [comment]
@WuJun2016 can we use `Gi` unit conversion instead?
![image](https://user-images.githubusercontent.com/4569037/135097783-63ee4730-107a-4d32-80fa-9f9b61430ab9.png)

**Comment by WuJun2016** [comment]
@guangbochen  I am using Gi units, the backend will convert Gi to m units.

**Comment by yasker** [comment]
@FrankYang0529 Can you help to verify the fix?

**Comment by FrankYang0529** [comment]
## Test info

* Verified version: master-e617c6ae-head
* Environment: 1 KVM (8 cores, 20G RAM)

## Test cases

* Create a VM with 2 disks and run `dd if=/dev/zero of=/dev/vdb bs=1M conv=sync`
  * [x] VM doesn't crash
  * [x] VM shows no space message
![Screenshot from 2021-10-04 15-06-14](https://user-images.githubusercontent.com/4927361/135808188-0a6f7bd2-39ce-478e-af0f-df83c92b093d.png)
