### ISSUE TITLE
[ENHANCEMENT] QEMU agent is not installed by default when creating VMs

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1235]
**Is your feature request related to a problem? Please describe.**

It seems that having the QEMU agent installed in the VM is critical for full functionality. For example, without it, the IP address of the VM is missing from the UI. However when provisioning VMs via the Harvester UI, QEMU agent install flag default to `disabled`.

This also constitutes an inconsistency with regards to provisioning VMs via the Rancher integration where the agent is in fact `enabled` by default.

If there is a reason for not installing it by default, then there should be a last a notice displayed on the VM overview or detail page that the guest tool is missing. Otherwise a user might interpret the missing IP address information as a failed VM provisioning.

**Comment by yasker** [comment]
@guangbochen We can toggle the default value of the checkbox of the guest agent.

**Comment by guangyee** [comment]
Package name and server name for QEMU guest agent maybe different from OS to OS. In openSUSE, for example, the package name is `qemu-guest-agent` and the service name is `qemu-ga.service`. We may need to maintain a config map for all the supported OS images.

**Comment by noahgildersleeve** [comment]
Tested in master-d05a6cc7-head on ubuntu focal and openSUSE 15.3. 

- qemu-ga is installed and running on openSUSE
- there does not seem to be a guest agent installed on ubuntu. I checked the repos and the oldest version of ubuntu that seems to have a guest agent in the repos seems to be 21.10. So it seems probably out of scope.

@guangbochen should I close this as fixed?

**Comment by guangbochen** [comment]
@noahgildersleeve I found the latest version of Ubuntu is 21.1.0, and what do u mean by the `oldest version of ubuntu`? also, all ubuntu releases from `18.x` to `21.x` should support the `quemu-guest-agent` config.

@WuJun2016 per offline discussion the following changes are required:
- update `openSuse -> openSUSE`
- move OS Type to the `Advanced` tab，and hide hostname with the `show more` option.
- auto-update the OS type if the root disk image is changed and can be used for os type judgment.

**Comment by noahgildersleeve** [comment]
@guangbochen Sorry about the confusion. I meant that the minimum required version to see qemu guest agent in the ubuntu repos is 21.10. However that launched this month and is not the current LTS version. You can still install `qemu-guest-agent` but I don't think you can just use `apt`.

**Comment by noahgildersleeve** [comment]
Tested in master-9cde746b-head on ubuntu focal. Fixed.
1. Created Focal VM
2. Started VM
3. checked for `qemu-ga` package
