### ISSUE TITLE
[BUG] Opening VNC console fails with error

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1236]
**Describe the bug**

Opening a VNC console for a VM that has already an active VNC console connection results in an error page with the following message:

> Cannot read property startsWith of null

**Environment:**
 - Harvester ISO version: 0.3-preview

**Comment by guangbochen** [comment]
@janeczku can u provide the guest OS image info and the VM YAML config for a proper debugging, thanks

**Comment by yasker** [comment]
We need to handle VNC errors more gracefully. We don't need to allow multiple people to use the VNC console at the same.

**Comment by alexdepalex** [comment]
In general, the Web VNC client works very flacky when using the vip. This might probably be fixed if we're able to add a custom certificate on the vip.

**Comment by yasker** [comment]
@alexdepalex did you mean you need to reauthorize/disable warnings due to SSL from time to time? If so yes that's will be addressed via #761

**Comment by alexdepalex** [comment]
Exactly this, so we'll wait for that.

**Comment by lanfon72** [comment]
Verified this VNC Error message has been changed as expected.

![image](https://user-images.githubusercontent.com/5169694/150088012-ad6770b1-cff7-41d2-b176-428f006033fb.png)

Test Information
----
* Environment: **Bare metal DL360 3 nodes**
* Harvester Version: **v1.0.0-rc2**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with any Nodes (node required 2 ports)
2. Create Image for VM Creation
3. Create and start VM
4. Connect to VM via  `Console` -> `Open in Web VNC`
5. Connection should establish successfully.
6. Start another **VNC Console** again
7. Connection should establish successfully.
8. **First** VNC console should be disconnected with error message
