### ISSUE TITLE
[BUG] Clone VM doesn't input any data in the form

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1238]
**Describe the bug**

When you clone a VM that was created from a template it doesn't include any data from the form
**To Reproduce**
1. Create a new VM from template with image
2. Start VM
3. Click three dots next to VM in VM list
4. Click clone
**Expected behavior**

1. Form data should be pre-populated
**Support bundle**

[supportbundle_d3bbb44a-07f9-44ce-9d87-d31e6ef4ace6_2021-09-16T17-22-10Z.zip](https://github.com/harvester/harvester/files/7179834/supportbundle_d3bbb44a-07f9-44ce-9d87-d31e6ef4ace6_2021-09-16T17-22-10Z.zip)

**Environment:**
 - Harvester ISO version: master-8afedf0a-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized libvirt/kvm setup

**Additional context**
This was working recently
![Screenshot from 2021-09-16 10-20-47](https://user-images.githubusercontent.com/83787952/133657491-2b8e4117-3e75-46d4-aaca-1c13c0bc479f.png)
.

**Comment by wonleing** [comment]
Maybe the whole "clone" feature is still under developing?

**Comment by WuJun2016** [comment]
addressed via https://github.com/harvester/dashboard/commit/7e90e8a48918c48cd0df9cd104af0da20c1f81c9, and should be ready for testing.

**Comment by guangbochen** [comment]
@WuJun2016 except the `Node Scheduling` everything else is copied successfully, also I think we should call it `Clone Template` instead of the `Clone`, as the real VM clone will be addressed via https://github.com/harvester/harvester/issues/569

**Comment by guangbochen** [comment]
verified on the `master-48c97ea7-head` version, clone the template has successfully cloned all VM configurations, the VM clone will be tracked on https://github.com/harvester/harvester/issues/571.
![image](https://user-images.githubusercontent.com/4569037/135033503-efd70121-fa5a-44b5-b4ff-d30be86babef.png)
