### ISSUE TITLE
[BUG] Harvester API VIP address is configured on the harvester0 bridge

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1239]
**Describe the bug**
When configuring separate physical interfaces for the management network and the VLAN network respectively, then the VIP IP address for Harvester API/UI is still configured on the harvester-0 bridge interface.

**Expected behavior**

The Harvester management VIP should only be configured on the physical interface configured as management NIC.

**Environment:**
 - Harvester ISO version: 0.3-preview
 - 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by yasker** [comment]
@janeczku I am not sure it's a bug since once the bridge was created, the original nic won't have an IP anyway IIUC.

The VIP will be on the same NIC or bridge as the mgmt network.

**Comment by yaocw2020** [comment]
The rule of how Harvester selects which network interface for the VIP is as following.
The VIP is configured on the management NIC at default. After users enable the VLAN network, if the management NIC in any one of the nodes is used by the VLAN network, the VIP will be configured on the harvester bridge. Once users disable the VLAN network, if the VIP is still on the harvester bridge, it will be configured back to the management NIC.

**Comment by yaocw2020** [comment]
We ignore one case that if users change the VLAN NIC to make the management NIC is not used by the VLAN network on every node.

**Comment by janeczku** [comment]
> After users enable the VLAN network, if the management NIC in any one of the nodes is used by the VLAN network, the VIP will be configured on the harvester bridge. 

That seems wrong. The VIP should never be configured anywhere but on the management interface. Why does it move to the bridge interface in the first place?

**Comment by guangbochen** [comment]
This is only required when users use the same management NIC for the VLAN network since it is a bridge VLAN setup. 
If users use a separate NIC for the VLAN, then the VIP will always sit on the management NIC by default.

**Comment by yaocw2020** [comment]
> > After users enable the VLAN network, if the management NIC in any one of the nodes is used by the VLAN network, the VIP will be configured on the harvester bridge.
> 
> That seems wrong. The VIP should never be configured anywhere but on the management interface. Why does it move to the bridge interface in the first place?

The VIP on the management interface attached to the harvester bridge is unable to be reached.

**Comment by yasker** [comment]
@janeczku Let me know if you still think this is an issue. In conclusion, the VIP is only configured either on the mgmt network (when it's not double purposed for VLAN nic), or the bridge that contains the previous mgmt NIC with the mgmt network IP (when it's double purposed for VLAN nic).

**Comment by janeczku** [comment]
We will add more information once we are able to reproduce

**Comment by guangbochen** [comment]
@janeczku can u please help to check if this is still an issue of the v0.3.0, thanks.

**Comment by tjjh89017** [comment]
This issue will be solved once harvester bump the version of `kube-vip` and `network-controller-harvester` 
In further version of harvester, it will not detect and set `vip_interface` for `kube-vip`, kube-vip will detect it directly.

checked with @yaocw2020 

https://github.com/kube-vip/kube-vip/pull/339
https://github.com/harvester/network-controller-harvester/commit/7a7f054a4840e0ce328231a88292281beac10fe6

**Comment by lanfon72** [comment]
@tjjh89017 do we need test this? if so, can you provide test plan?

**Comment by tjjh89017** [comment]
manual test plan
1. Setup Node VLAN network interface to harvester-mgmt
2. check the harvester-br0 has VIP, don't care about harvester-mgmt
3. modify Node VLAN network interface to another interface.
4. check the harvester-mgmt has VIP, check harvester-br0 will not have VIP.

step 4 is most important to test

Thanks a lot

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/156516561-49d8a953-8b3f-4e98-8e25-d71c0ac08ee5.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-9ecb4f9d-head**
* **ui-source** Option: **Auto**

### Verify Steps:
based on https://github.com/harvester/harvester/issues/1239#issuecomment-1056684361
