### ISSUE TITLE
[BUG] Additional disk is not visible unless manually formatted

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1240]
**Describe the bug**

When trying to add additional physical disks to Harvester the disk does not appear in the UI unless it has been manually formatted by the user.

Expectation:
Harvester should allow the user to add raw disk devices that have not previously been partitioned/formatted.

Harvester 0.3-preview

**Comment by yasker** [comment]
Also, it seems the user needs to manually specify the mounting location on the node. That shouldn't be necessary.

**Comment by weihanglo** [comment]
> Also, it seems the user needs to manually specify the mounting location on the node. That shouldn't be necessary.

I guess this part can be addressed from UI part, right? We just need to decide a conventional mount point for additional disks in Harvester, e.g. `/var/lib/harvester/extra-disks/<some-id>`.

@janeczku, could you provide blockdevice CR yaml as well as the disk info. It would be very helpful for us. Thanks!

**Comment by alexdepalex** [comment]
@weihanglo Additional info is here https://github.com/harvester/harvester/issues/1237#issuecomment-921629903

**Comment by yasker** [comment]
@weihanglo Is it possible to leave the handling to the backend as well? Like we can set `format` for the disks.

Also, those disks will need to be automatically remounted again after the system restarted. Make sure that part is covered as well.

**Comment by weihanglo** [comment]
Hi, @yasker. If you are referring to specifying mount point, I guess yes. We can handle it from the backend if needed.

**Comment by alexdepalex** [comment]
From an operational perspective, can we in some way make sure that the mount point contains a description, or name, of the underlying block device?

**Comment by weihanglo** [comment]
> From an operational perspective, can we in some way make sure that the mount point contains a description, or name, of the underlying block device?

Hi @alexdepalex. Technically it's possible, but I am not sure what info users need to retrieve from mount point and how can we make it better. Could you elaborate more about the scenario and use case? If the blockdevice custom resource has an optional field to store user's description, would that helps?

**Comment by alexdepalex** [comment]
If during an installation disks are automatically configured, then from a user perspective it would be good if you could see the relation between the longhorn mount point and the actual device on the underlying operating system.

**Comment by lanfon72** [comment]
> Harvester should allow the user to add raw disk devices that have not previously been partitioned/formatted

Verified additional disk which partitioned could be added and auto formatted.
You can't use UI to do partition on the additional raw disk for now, I think it better to be tracked in another issue. 

> Also, it seems the user needs to manually specify the mounting location on the node. That shouldn't be necessary.

Verified UI provided a randomly named folder and the default mounting location `/var/lib/harvester/extra-disks`

> Also, those disks will need to be automatically remounted again after the system restarted. Make sure that part is covered as well.

Verified new disks will be remounted automatically after reboot.

![image](https://user-images.githubusercontent.com/5169694/135450254-66e9d870-b80e-4d7a-bb28-4d31877a389f.png)


Test Information
----
* Environment: **Laptop qemu/KVM** single node
* Harvester Version: **v0.3.0-rc1**
### Verify Steps:
1. create VM with 2 disks
2. Install Harverster
3. login to console, use `fdisk` to create partition on 2nd disk
4. open dashboard, navigate to host's disk section and check new partitions could be detected and added.
5. check *longhorn-disk.cfg* exists in the mounted path.
6. reboot and check remount automatically
    - open dashboard, navigate to host's disk and check new added disks still showing here
    - login to console, check *longhorn-disk.cfg* exists in the mounted path of new added disks
