### ISSUE TITLE
[BUG] Volumes are not cleaned up when VM provisioning fails

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1246]
**Describe the bug**
When creating a RKE2 cluster with Harvester driver and for some reason (e.g. an invalid config) the VM provisioning fails (and is then automatically retried by the provisioner all over again) there will be eventually hundreds of volumes on Harvester occupying all storage space.

Volumes should be cleaned up if a VM was not successfully provisioned.

**Comment by guangbochen** [comment]
seems to be a known issue fixed by node driver `v0.3.1` at the https://github.com/rancher/rancher/pull/34765, can u possibly check what is the node driver version have been used?

**Comment by alexdepalex** [comment]
We're using node driver `v0.3.0`. An unexpected side effect of this is that it exhausted storage on the integrated longhorn and prevented new pvc's to fail. And this doesn't result in an error because of this issue: https://github.com/harvester/harvester/issues/1242

**Comment by futuretea** [comment]
@guangbochen  @alexdepalex
v0.3.0 no pvc clean up logic.
v0.3.1 fix pvc clean up but still has some timing issue, harvester/docker-machine-driver-harvester#26 will fix it.
need v0.3.2

**Comment by alexdepalex** [comment]
I don't know if it's deliberate, but when deleting the volumes in Harvester, they're still lingering in Longhorn. It also still shows that the pv's are attached, but that bogus, since they weren't attached in Harvester and the vm's were already removed hours ago.
![Annotation 2021-09-17 162759](https://user-images.githubusercontent.com/713019/133799919-41798b02-b5d3-4097-aa53-e7234b2595d9.png)

**Comment by guangbochen** [comment]
> since they weren't attached in Harvester and the vm's were already removed hours ago.

it should get deleted, can u please help upload a support bundle file so that we can dig into the error logs properly, thanks

**Comment by alexdepalex** [comment]
Gathering logs doesn't work. It's stuk at 0%. I'll give it some time.

**Comment by futuretea** [comment]
@alexdepalex v0.3.2  released
URL: https://releases.rancher.com/harvester-node-driver/v0.3.2/docker-machine-driver-harvester-amd64.tar.gz
Checksum: f113d826b8bee79abf60f1026b4076befdf735c6675889240c75da6b30f09971

**Comment by guangbochen** [comment]
Verified using the Rancher v2.6-head and Harvester node driver with `v0.3.2`, @noahgildersleeve can u please confirm to close, thanks:
1. spin up a guest k8s cluster with a total of 3 nodes using the RKE2 node driver (e.g 1 control plane + 2worker)
2. check the VM and volumes that exist on the Harvester cluster
![image](https://user-images.githubusercontent.com/4569037/134794766-89c0d92b-447d-4713-bc46-370216ccff40.png)
3. delete 2 worker nodes and make sure the volumes are gone
![image](https://user-images.githubusercontent.com/4569037/134794814-429c9119-aa92-4ed0-adb0-1037690d89bc.png)
![image](https://user-images.githubusercontent.com/4569037/134794823-60f82642-f09a-4bba-a4ac-5cac57120089.png)

**Comment by yasker** [comment]
close as verified per https://github.com/harvester/harvester/issues/1246#issuecomment-927234690 .
