### ISSUE TITLE
[BUG] Update NTP server to use OpenSUSE one

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1248]
We need to update the default NTP server to a SUSE NTP server.

**Comment by alexdepalex** [comment]
@yasker When specifying NTP servers in the config-create, these are concatenated to the default NTP servers. In this case, we have the ubuntu NTP server first, followed by our internal NTP servers.

**Comment by bk201** [comment]
> @yasker When specifying NTP servers in the config-create, these are concatenated to the default NTP servers. In this case, we have the ubuntu NTP server first, followed by our internal NTP servers.

@alexdepalex  Do you use the installer to install and also provide a `config-create` file in the "Optional: remote harvester config"? If that's the case, the NTP servers in the config file will be merged with the one input in the "Optional: Configure NTP servers".

You can delete the content of the text field in the "Optional: Configure NTP servers" page to only use those NTP servers in the remote config.

**Comment by alexdepalex** [comment]
We just use the pxe boot method and provide a `config-create` file. No manual configuration through the installer ui is done.

**Comment by yasker** [comment]
@FrankYang0529 Due to some reason, `0.suse.pool.ntp.org` always fails on me in the installer when checked for the first time, and always passed on the second time.
<img width="762" alt="Screen Shot 2021-09-23 at 9 32 42 AM" src="https://user-images.githubusercontent.com/3344618/134547556-a723b8db-e0cc-4f0b-b5c2-f529d81e64cb.png">


After installation, it seems the NTP server has been configured correctly though.


<img width="620" alt="Screen Shot 2021-09-23 at 9 35 47 AM" src="https://user-images.githubusercontent.com/3344618/134547994-c19982b8-246c-4fc0-9943-4dafc43d6d37.png">

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Due to some reason, `0.suse.pool.ntp.org` always fails on me in the installer when checked for the first time, and always passed on the second time.
> <img alt="Screen Shot 2021-09-23 at 9 32 42 AM" width="762" src="https://user-images.githubusercontent.com/3344618/134547556-a723b8db-e0cc-4f0b-b5c2-f529d81e64cb.png">
> 
> After installation, it seems the NTP server has been configured correctly though.
> 
> <img alt="Screen Shot 2021-09-23 at 9 35 47 AM" width="620" src="https://user-images.githubusercontent.com/3344618/134547994-c19982b8-246c-4fc0-9943-4dafc43d6d37.png">

@yasker , do you use air-gapped environment? We only validate whether NTP servers can be connected and serve NTP requests.

**Comment by FrankYang0529** [comment]
@yasker , we show validation error message now. Could you please try again and screenshot error message? Thank you.

**Comment by guangbochen** [comment]
![image](https://user-images.githubusercontent.com/4569037/134793038-d6d6b97c-3cd5-43e0-9ffd-0ba49e5d760e.png)

**Comment by FrankYang0529** [comment]
@guangbochen , I think i/o timeout is dependent on different connection quality. How about prolonging timeout deadline to 10 seconds and retrying at most 3 times for timeout error?

**Comment by yasker** [comment]
@FrankYang0529 It looks like something else. At this phase, we've checked the connectivity to the first node server already. Also, it always failed on the first time and succeed on the second time, and for each node. It doesnt make sense. 

I can reproduce it on my baremetal environment. @guangbochen how did you reproduce it?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 It looks like something else. At this phase, we've checked the connectivity to the first node server already. 

@yasker , may you try this [repo](https://github.com/vladimirvivien/go-ntp-client)? This repo uses 15 seconds as timeout deadline, but we only use 5 seconds. @guangbochen has tried it and got results as following:

```
➜  go-ntp-client git:(master) go run time.go -e 0.suse.pool.ntp.org:123
2021/09/27 10:13:20 failed to read server response: read udp 10.7.0.2:60629->139.199.215.251:123: i/o timeout
exit status 1
➜  go-ntp-client git:(master) go run time.go -e pool.ntp.org:123
2021-09-27 10:13:22.832826074 +0800 CST
➜  go-ntp-client git:(master) go run time.go -e 0.suse.pool.ntp.org:123
2021-09-27 10:13:32.188261819 +0800 CS
```

> Also, it always failed on the first time and succeed on the second time, and for each node. It doesnt make sense.

For this behavior, it's from discussion here https://github.com/harvester/harvester-installer/pull/119#issuecomment-918916649.

**Comment by yasker** [comment]
Verified NTP part no longer error out during installation.

Though it's obvious now the NTP server check part took less than 5 seconds this time in either of my three nodes. Don't really understand why it works now. Maybe `0.suse.pool.ntp.org` has some issues last time. 

Close this as verified for now. Feel free to reopen if it happens again.
