### ISSUE TITLE
[BUG] Harvester v0.3.0-preview1 - RKE2 engine failed to start

### ISSUE THREAD

**Issue by vobo70** [harvester/harvester#1251]
**Describe the bug**

fresh install v0.3.0-preview1 - after restart nothing happends for 30 minutes - logon to console - reboot and after restart get error rke2-server failed to start

**To Reproduce**
fresh install v0.3.0-preview1
restart
error rke2-service failed to start

**Expected behavior**

get ready to connect panel as in 0.2

**Support bundle**

irvesterl:/ S systenctl states rke2-server
rke2-server .service - Rancher Rnbemetes Engine uZ (server)
Loaded: loaded (/usr/local/lib/systend/systen/rke2-server.service; enabled; vendor preset: disabled)
Active: activating (auto-restart) (Result: exit-code) since Sun 2621-69-19 69:36:18 UTC; Is ago
Docs: https://githnb.con/rancher/rke21readne
Process: 4518 ExecStartPre=/bin/sh -xc ! /usr/bln/systenctl is-enabled —quiet nn-cloud-setup.service (code=exlted. status=6/SUCCESS)
Process: 4529 ExecStartPre=/sbin/nodprdbe brjnetfllter (code^exited. status=0/SUCCESS)
Process: 4536 ExecStartPre=/sbin/nodprobe overlay (code=exited. status=6/SUCCESS)
Process: 4531 ExecStart=/usr/local/bin/rke2 server (code=exited> status=l/FAILURE)
Process: 4541 ExecStopPost^/bin/sh -c systend-cgls /systen.slice/rke2-server.service I grep -Eo '(6-9)+ (containerd Ikebe let)' I auk '(print I snege -r kill (cedcTxited, status=6/SUCCESS)
Main P1D: 4531 (code=exited« status=l/FAILURE)
(may contain errors, becouse it was OCR from screen photo)

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
v0.3.0-preview1
dell optiplex 7020, i5, 16GB RAM, 1,5TB HDD

**Additional context**

**Comment by vobo70** [comment]
no one have same problem?
I will wait for next release then.

**Comment by yasker** [comment]
@vobo70   We had a few known issues for preview1. We will have rc1 soon which should be much more stable. Feel free to give it try soon.
