### ISSUE TITLE
[Question] how do I modify the grub parameters on install?

### ISSUE THREAD

**Issue by hornet83** [harvester/harvester#1252]
Hi, I want to add the net.ifnames=1 as my interface naming is different to the ethx. I read to hit esc + e (as you would to modify kernel parameters) during the ISO boot.. the ESC doesnt do anything and I'm getting to the "Create Harvester Cluster" and after that there doesnt seem to be a way to modify the grub parameters anymore.

Thanks

**Comment by hornet83** [comment]
nevermind I got it.. only have about half a sec to push ESC after selecting the USB device for booting - I was simply to slow ;)

**Comment by guangbochen** [comment]
thanks for the confirmation and it also has the doc available at https://docs.harvesterhci.io/v0.3/troubleshooting/os/.
