### ISSUE TITLE
[BUG] Network interface not detected in ISO installer

### ISSUE THREAD

**Issue by bashofmann** [harvester/harvester#1254]
**Describe the bug**
In a test installation, it is not possible to select a network interface in the ISO installer. The error message "NIC not found" is shown. A SLES installation on the same hardware detects the network interface correctly.

**To Reproduce**
* Install harvester with the ISO installer
* Create a new cluster
* Try to select a network interface

**Expected behavior**
you can select the network interface in the installer

**Environment:**
 - Harvester ISO version: 0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal with synergy 4820c network adapter

**Comment by bk201** [comment]
The `qede` module is presented, but `kernel-firmware-qlogic` package is missing.

![capture](https://user-images.githubusercontent.com/1691518/134318617-e322d1c6-7d2b-4ee0-88dc-feefa0cbdc60.png)

**Comment by noahgildersleeve** [comment]
Tested in master-d05a6cc7-head. Verified that both interfaces showed up during ISO install on virtualized environment and deploy was successful to bare metal environment with three node DL160 environment.
