### ISSUE TITLE
[BUG] NTP selection is before proxy selection in installer

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1257]
**Describe the bug**

The NTP server selection is before the proxy selection. This causes the NTP server selection to fail if you need to select a proxy.
**To Reproduce**
1. Run the installer on a harvester node behind a proxy and without external connectivity
2. Try to select an NTP server
**Expected behavior**

The proxy should be before the NTP server selection
**Support bundle**

**Environment:**
 - Harvester ISO version: master 9-21-21
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM/QEMU virtualized

**Additional context**
I'm not positive that the NTP traffic is going to pass through the web proxy, but if it is then we need to change the order.

**Comment by bk201** [comment]
We use [systemd-timesyncd](https://www.freedesktop.org/software/systemd/man/systemd-timesyncd.service.html) for time synchronization and it implements SNTP (Simple Network Time Protocol).
I don't think UDP traffic is transferred through the HTTP proxy. @FrankYang0529 Could you verify this? Thanks!

And the `systemd-timesyncd` service is actually only run after rebooting, we should enhance this too.

**Comment by FrankYang0529** [comment]
`timesyncd` uses `SOCK_DGRAM` as socket type which is UDP socket, so httpproxy can't support it.

ref: https://github.com/systemd/systemd/blob/main/src/timesync/timesyncd-manager.c#L823

**Comment by noahgildersleeve** [comment]
Moving to ready for testing due to no code change needed.

**Comment by noahgildersleeve** [comment]
Closing since it's working as designed.
