### ISSUE TITLE
[FEATURE] Configuring additional trusted CA certificates

### ISSUE THREAD

**Issue by bashofmann** [harvester/harvester#1260]
**Is your feature request related to a problem? Please describe.**
It should be possible to configure additional trusted CA certificates for all components that communicate outside of the cluster. In Harvester this affects for example image downloads which could be hosted by web servers that are secured with TLS certificates from a corporate CA or where a proxy or firewall intercepts TLS.

**Describe the solution you'd like**
Similarly to Rancher (https://rancher.com/docs/rancher/v2.6/en/installation/install-rancher-on-k8s/chart-options/#additional-trusted-cas) it should be possible to configure additional trusted CAs. Either with a config/helm chart option during installation, or as a global setting.
These certificates should be picked up by all components that are communicating with the outside, probably also the integrated rancher and longhorn (external backups).

**Comment by yasker** [comment]
Ref #761

**Comment by yasker** [comment]
From #761 , we can also consider automatically generate SSL certificates using e.g. Let's Encrypt.

**Comment by alexdepalex** [comment]
@janeczku

**Comment by gitlawr** [comment]
To test:
1. set up a self-signed HTTP server to serve virtual machine images.
2. set up a self-signed s3 server(e.g., https://longhorn.io/docs/1.2.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore)
3. Configure additional trusted CA certificates in Harvester settings
4. Verify image download/VM backup works using those servers.

**Comment by lanfon72** [comment]
### Verify items
- [x] image download with self-signed additional-ca (IP-based)
- [x] VM backup with self-signed additional-ca (IP-based)
    - [x] ~~blocked by #1562~~
- [ ] ~~image download with self-signed additional-ca (domain-based)~~  won't test due to it actually same as IP-based
- [ ] ~~VM backup with self-signed additional-ca (domain-based)~~  won't test due to it actually same as IP-based


Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-f5bde7fa-head**
* **ui-source** Option: **Auto**

### Verify Steps:
**Image Download**
1. Install Harvester with ipxe-example which includes https://github.com/harvester/ipxe-examples/pull/36
2. Upload any valid iso to **pxe-server**'s `/var/www/`
3. Use Browser to access `https://<pxe-server-ip>/<iso-file>` should be valid
4. Add self-signed cert to Harvester
    - Navigate to Harvester _Advanced Settings_, edit _additional-ca_
    - cert content can be retrieved in pxe-server `/etc/ssl/certs/nginx-selfsigned.crt`
5. Create Image with the same URL `https://<pxe-server-ip>/<iso-file>`
6. Image should be downloaded

**VM backup**
1. Install Harvester with ipxe-example
2. setup **Minio** in pxe-server
  - follow [instruction](https://docs.min.io/docs/minio-quickstart-guide.html) to download binary and start the service
  - login to UI console then add region and create bucket
  - follow [instruction](https://docs.min.io/docs/how-to-secure-access-to-minio-server-with-tls.html#using-open-ssl) to generate self-signed cert with IP SANs
  - restart service with self-signed cert
3. Add self-signed cert to Harvester
4. Add local **Minio** info as S3 into **backup-target**
5. Backup-Target Should not pop up any Error Message
6. Create Image for VM creation
7. Create VM with any resource
8. Perform VM backup
9. VM's data Should be backup into **Minio**'s folder

**Comment by lanfon72** [comment]
@gitlawr, @WuJun2016 this issue will put back to implement in the following reason:
- backup-target unable to use self-signed cert in the following error
![image](https://user-images.githubusercontent.com/5169694/143611796-898e29fd-c9e7-4daa-8ebf-98871fed1adc.png)

The added CA
![image](https://user-images.githubusercontent.com/5169694/143612169-6e922149-a221-40fe-8f65-463a57929451.png)


I tested with Minio's Python API as following
```bash
(.env) lanfon@lanfonsuse:~/dev_src> ls
boshiamy-ibus-1-8-x  del_key    fluxgui        ipxe.efi       minio.crt  tests    wtf
daily.md             e2e-tests  harvester_iso  ipxe-examples  note.md    WebDemo
(.env) lanfon@lanfonsuse:~/dev_src> cat minio.crt 
-----BEGIN CERTIFICATE-----
MIIDejCCAmKgAwIBAgIUBouG0xzv14eva5XSZInkoVp12OswDQYJKoZIhvcNAQEL
BQAwZDELMAkGA1UEBhMCVVMxCzAJBgNVBAgMAlZBMRIwEAYDVQQHDAlTb21ld2hl
cmUxDjAMBgNVBAoMBU15T3JnMQ0wCwYDVQQLDARNeU9VMRUwEwYDVQQDDAxNeVNl
cnZlck5hbWUwHhcNMjExMTI2MTUzMDUzWhcNMjMxMTI2MTUzMDUzWjBkMQswCQYD
VQQGEwJVUzELMAkGA1UECAwCVkExEjAQBgNVBAcMCVNvbWV3aGVyZTEOMAwGA1UE
CgwFTXlPcmcxDTALBgNVBAsMBE15T1UxFTATBgNVBAMMDE15U2VydmVyTmFtZTCC
ASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAL5c6b3b2TmTow71LAUKRuSs
PhMq30PcDYQUwirbgGGzJA5h682y9DHbtesNfNzqPBVc4BO/8nPthY5Sb4YPI4It
t5mWozRdFExHAGYO1Ja4Dj1QqWNTn33LqEGd/xoTI53jPFxJsUUbb+a5bKAyRd4y
Qmsi6ydTaKlDVsG3UI0XUreCrBUEZ34PFkO9eLc1+mTdVscmPlkwIFI2r2ACLHiz
gaHDIJmD283H0wE9adhZWOyI4y5FXfVjUR1H5VqEMqA0VYJYkCH3g1rrWi79aEZX
3y7HuHFd28kdCZ872clLmPOa4hwuEnOS/Bp46PniP5snqoUcfyj42XfIDXTVRKEC
AwEAAaMkMCIwIAYDVR0RBBkwF4cEwKoA/ocEwKh5t4IJbG9jYWxob3N0MA0GCSqG
SIb3DQEBCwUAA4IBAQBCpdkrQNdu8jncPjlYt9ywledNitL7lWL2umSQL+N+JArn
sh2cQLTWhVCPbIu4s1yd0uoR+kNju3mJ5gbdCwhEy+uKovpjWJG318gSEgxZZUsu
wDdksc+Drw500lndaboVGI5xXYXivajuo4JPBY48T0Y0rx7fqocAnWdOEYluSzzn
ggxJg5/kssPOgnAJIcdgRzWD10/wiZwc8sp5cP/Cs2XKmUE3brfk+zXsvNJt1pgB
bIVOu/A6XPCEqEyWPsK3cuoPhE0LbmCFqSBdap+Zi03fhfaoPDKtdS1fBcEJePRc
5yQkpz3OmjRIZJ78/yqSmR1ymw8DW6NVrzjhag5e
-----END CERTIFICATE-----
(.env) lanfon@lanfonsuse:~/dev_src> python
Python 3.9.9 (main, Nov 17 2021, 09:50:59) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ['SSL_CERT_FILE'] = './minio.crt'
>>> from minio import Minio
>>> cli = Minio('192.170.0.254:9000', 'admin', 'password')
>>> cli.list_buckets()
[Bucket('local-test')]
>>> 
```

**Comment by lanfon72** [comment]
@gitlawr function broken on non-SSL/SSL endpoint
![image](https://user-images.githubusercontent.com/5169694/144181945-f518c283-9b52-45fc-bb1f-117fa994f810.png)


![image](https://user-images.githubusercontent.com/5169694/144182673-1326c599-9f01-4ad4-89b9-0336793e6ea0.png)
request payload (formatted)
```json
{
    "id": "backup-target",
    "type": "harvesterhci.io.setting",
    "links":
    {
        "remove": "https://192.170.0.131/v1/harvester/harvesterhci.io.settings/backup-target",
        "self": "https://192.170.0.131/v1/harvester/harvesterhci.io.settings/backup-target",
        "update": "https://192.170.0.131/v1/harvester/harvesterhci.io.settings/backup-target",
        "view": "https://192.170.0.131/apis/harvesterhci.io/v1beta1/settings/backup-target"
    },
    "apiVersion": "harvesterhci.io/v1beta1",
    "default": "{\"type\":\"\",\"endpoint\":\"\",\"accessKeyId\":\"\",\"secretAccessKey\":\"\",\"bucketName\":\"\",\"bucketRegion\":\"\",\"cert\":\"\",\"virtualHostedStyle\":false}",
    "kind": "Setting",
    "metadata":
    {
        "creationTimestamp": "2021-12-01T05:55:05Z",
        "fields":
        [
            "backup-target",
            null
        ],
        "generation": 1,
        "managedFields":
        [
            {
                "apiVersion": "harvesterhci.io/v1beta1",
                "fieldsType": "FieldsV1",
                "fieldsV1":
                {
                    "f:default":
                    {},
                    "f:status":
                    {}
                },
                "manager": "harvester",
                "operation": "Update",
                "time": "2021-12-01T05:55:05Z"
            }
        ],
        "name": "backup-target",
        "relationships": null,
        "resourceVersion": "5693",
        "state":
        {
            "error": false,
            "message": "Resource is current",
            "name": "active",
            "transitioning": false
        },
        "uid": "51d062ad-638d-4bb8-b2bc-f8a193ab240c"
    },
    "status":
    {},
    "value": "{\"type\":\"s3\",\"endpoint\":\"http://192.170.0.254:9000/\",\"accessKeyId\":\"admin\",\"secretAccessKey\":\"password\",\"bucketName\":\"local-test\",\"bucketRegion\":\"local-vm\",\"cert\":\"\",\"virtualHostedStyle\":false}"
}
```

Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-1e042e04-head**
* **ui-source** Option: **Auto**

**Comment by gitlawr** [comment]
@lanfon72 Can you provide support bundle or logs from harvester-webhook pods

**Comment by lanfon72** [comment]
uploaded: [supportbundle_c2e87632-8554-4d16-8193-6ed15f5a8ac8_2021-12-01T06-31-37Z.zip](https://github.com/harvester/harvester/files/7631392/supportbundle_c2e87632-8554-4d16-8193-6ed15f5a8ac8_2021-12-01T06-31-37Z.zip)

**Comment by w13915984028** [comment]
I also encountered this issue yesterday, backup target with the minio local server was not working, web-hook said `unexpected end of JSON input`, and was wondering there were problems with my ENV setting.

**Comment by lanfon72** [comment]
Verified it works as expected.
- [x] VM backup with self-signed additional-ca (IP-based)

![image](https://user-images.githubusercontent.com/5169694/144639987-972300eb-1562-4c52-ba98-006cede37293.png)


Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **v1.0.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
described in https://github.com/harvester/harvester/issues/1260#issuecomment-975444914
