### ISSUE TITLE
[FEATURE] Ability to define storage disk devices as global option

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1262]
In order to make use of additional disk devices for VM storage currently, one has to add them manually disk by disk and node by node via the Harvester UI. This is not practical for large scale rollouts.

**Proposal:**

We need a global option that allows the user to specify the disk devices that should be added to the LH storage pool during initial cluster installation or while adding nodes to a cluster.

This option should be both supported in the  `create-config` and `join-config` (the latter overriding the value specified in the former).
The option could either be a list of device paths (e.g. `/dev/nvme0n1,/dev/nvme0n2`) or a regex matcher.
When this option is specified by the user, the OS disk device configured in the `install.device` option is no longer added to the LH storage unless it's specifically included via the new option.

The ability to exclude the OS disk from LH storage would better support cases where there is a small disk used for the OS and a hard isolation of IO between Harvester system components and VM workloads is desired.

**Comment by yasker** [comment]
@janeczku You had another issue https://github.com/harvester/harvester/issues/1241 ? Are those the same?

**Comment by janeczku** [comment]
Closing duplicate of https://github.com/harvester/harvester/issues/1241
