### ISSUE TITLE
[BUG] Image import from file fails occasionally on large files

### ISSUE THREAD

**Issue by 2stacks** [harvester/harvester#1265]
**Describe the bug**
Image import from file fails occasionally with an error similar to
![image](https://user-images.githubusercontent.com/15258140/134558633-f9386691-c6ed-4caf-a060-21c41776b180.png)

**To Reproduce**
1. Go to **Images**, click **Create**, select type **File**, select the filename of the image to import.

**Expected behavior**
Image imports successfully.

**Support bundle**
[harvester-support-bundle.zip](https://github.com/harvester/harvester/files/7219880/harvester-support-bundle.zip)

**Environment:**
 - Harvester ISO version: `v0.3.0-preview1`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `Baremetal Dell PowerEdge R610 w/ 1TB PCIE NVMe storage`

**Additional context**
Image source is on an NFS mount connected to the client initiating the upload.  All systems are connected to the same switch using 1Gbps connections.

**Comment by w13915984028** [comment]
This issue was solved in https://github.com/harvester/harvester/issues/1904, close.
