### ISSUE TITLE
[BUG] Cann't switch from shell to console by F12.

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1268]
**Describe the bug**

According to the hint, we can use F12 to switch between the Harvester console and shell. However, it only works when switching from console to shell but is ineffective in the case of switching from shell to console. 

**To Reproduce**
1. Press F12 from console to shell.
2. Press F12 again but it failed to switch to console.

**Expected behavior**

We can use F12 to switch from shell to console.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head 0924
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtual environment.

**Additional context**

**Comment by yasker** [comment]
I am not sure if we have to add F12. You can always use `Ctrl-D` to exit from the terminal, like any other Linux-based system.

**Comment by guangbochen** [comment]
Verified works with `Ctrl-D` in v0.3.0.
