### ISSUE TITLE
[BUG] Cursor jumps to the end while editing image name

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1269]
**Describe the bug**
While editing the **name** of an image, the cursor jumps to the end of the string when I tried to prepend something to the name.

**To Reproduce**
1. Go to "Images" page
2. Click "Create"
3. Enter some string, like `awesome-image`
4. Try to change the name to `my-awesome-image` so I move the cursor to the beginning of the string
5. Type `m`, the name becomes `mawesome-string`, **and the cursor jumps to the end of the string.**
6. Happens as long as the cursor is not at the end of the string.

**Expected behavior**
Cursor shouldn't jump around while I'm typing.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-466a24f6-head 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by n313893254** [comment]
Verify steps:
- Install the latest Harvester
- Create an image from "Images"
- Check the image name input(with the namespace select)

**Comment by lanfon72** [comment]
Verified that Input box of Image Name works normally.


Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-04c5f438-head**
* **ui-source** Option: **External**
### Verify Steps:
1. Install Harvester with any Nodes
2. Setup password and login
3. Navigate to _**Images**_ and Click _Create_
4. Input any **Valid** URL like `https://127.0.0.1/this_is_valid_file_format.raw`
5. Insert any characters in any position of the _**Name**_ Input box
6. Make sure new character should be added following previous one.  (cursor should not change)
7. Click Any position in the String of the Input box
8. Click `backspace` Key, make sure 1 character removed in the left, and cursor following.
9. Click `delete` Key, make sure 1 character removed in the right, and cursor staying.
