### ISSUE TITLE
[BUG] Image name with leading and trailing spaces should be trimmed

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1270]
**Describe the bug**
I am able to create images that look like they have identical names by **adding leading and trailing spaces.**
![image](https://user-images.githubusercontent.com/5047724/134641260-622cb1d3-8931-418d-a6d5-317518723a75.png)

Names with leading/trailing spaces should either be trimmed before they are created, or considered invalid.

**To Reproduce**
1. Go to "Images" page
2. Create an image with name `test` and any valid URL.
3. Create another image with name `test` **but with a trailing space** and any valid URL. The image is created without any issue.
4. Create another image with name `test` **but with a leading space** and any valid URL. The image is created without any issue.
5. On the images list, the three images all show name `test`.

**Expected behavior**
There shouldn't be images that look like they have identical names.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-466a24f6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. Got error on trying to create the same named image with trailing and leading spaces.
![image](https://user-images.githubusercontent.com/83787952/135157052-a4ef35e9-61af-4bc4-8090-19b2cb1c7a37.png)
