### ISSUE TITLE
[BUG] Shut down a node with maintenance mode should show red label

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1272]
**Describe the bug**
Maintenance mode label doesn't change from yellow to red when a node has been shut down.
![Screenshot from 2021-09-24 16-56-04](https://user-images.githubusercontent.com/4927361/134647555-d8a77116-880b-45f8-a3bb-fbfc1f89a436.png)

**To Reproduce**
1. Put a node in maintenance mode.
2. When a node shows Maintenance mode, then turn off the node.

**Expected behavior**
The node should be updated from yellow maintenance mode to red.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-466a24f6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by TachunLin** [comment]
Verified **failed** on master-b5dadc82-head. Move issue to review stage.

### Result
Node keeps in yellow maintenance mode when node has been turned off

![image](https://user-images.githubusercontent.com/29251855/139856722-e5e7dc8e-da64-4a6f-a4e5-308a4300bbfb.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm
* Harvester version: master-b5dadc82-head

### Verify Steps

1. Open host page
2. Set a node to maintenance mode
3. Turn off host vm of the node
4. Check node status
 
### Additional Context
![image](https://user-images.githubusercontent.com/29251855/139859173-24004a98-df23-458b-8ce2-25eb4f271b16.png)

**Comment by n313893254** [comment]
```
v1/nodes/qy
{
"error": true,
"lastHeartbeatTime": "2021-11-16T09:27:39Z",
"lastTransitionTime": "2021-11-16T09:29:16Z",
"lastUpdateTime": "2021-11-16T09:29:16Z",
"message": "Kubelet stopped posting node status.",
"reason": "NodeStatusUnknown",
"status": "Unknown",
"transitioning": false,
"type": "Ready"
}

=====
v1/harvester/nodes/qy
{
"error": false,
"lastHeartbeatTime": "2021-11-16T09:27:39Z",
"lastTransitionTime": "2021-11-16T09:29:16Z",
"lastUpdateTime": "2021-11-16T09:29:16Z",
"message": "Kubelet stopped posting node status.",
"reason": "NodeStatusUnknown",
"status": "Unknown",
"transitioning": false,
"type": "Ready"
}
],
```

`v1/harvester/nodes/qy` return error should be false

**Comment by noahgildersleeve** [comment]
Tested in master-5d6f3db0-head. Verified as fixed
## Test Steps
1. Put on host on 4 node setup into maintenance mode
2. Shutdown node via SSH with `shutdown now`
3. Verified that maintenance mode label turned red
![image](https://user-images.githubusercontent.com/83787952/145727543-ccf984f6-7afe-4b46-994c-1a9a92080129.png)
4. Turned server back on and verified that maintenance mode label went back to yellow
![image](https://user-images.githubusercontent.com/83787952/145727763-8b0ac31f-70ff-476e-8046-bf0a49bba821.png)
