### ISSUE TITLE
[FEATURE] Show common network interface when selecting network interface for the VLAN network

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1273]
**Is your feature request related to a problem? Please describe.**
- We should filter out the slave of the bond device since they can be used by the VLAN network
- While enabling the VLAN network, It would be convenient for users to know what are the common network inerfaces available across those Harvester nodes. [UI]
   - To add a dropbox and show all the common NICs across the Harvester nodes

**Describe the solution you'd like**

- Filter out the slave of the bond device
- To add a dropbox and show the common NICs available on the Harvester nodes

**Comment by yaocw2020** [comment]
UI changes
 - Host network edit page UI requirements
   - display the type of the network interfaces as the form `name(type, status)`
   - filtering the network interfaces with masterIndex and not used by VLAN network
 - Setting VLAN edit page UI requirements
   - add the dropbox to display the common network interfaces in all nodes
 
 @guangbochen @gitlawr @WuJun2016

**Comment by guangyee** [comment]
Currently when enabling vlan, if the wrong default physical NIC name is entered (i.e. the enslaved interface instead of the bonded interface), VLAN will stayed non-functional, even if user corrected it later, till the cluster is re-installed. A dropdown menu to prevent these kind of user mistakes would greatly improve usability.

**Comment by yasker** [comment]
@yaocw2020 We won't be able to make any UI changes now due to Rancher UI merge window has closed. We can continue to enhance the backend part. Please create another issue for the UI enhancement and use this ticket to track the backend enhancement. Thanks.

**Comment by yaocw2020** [comment]
The backend part is better not be merged  if the UI can not been changed in this version because we modify some items of the CRD. Otherwise, the UI about the networking will be not work.

**Comment by yasker** [comment]
In fact for this one we should be able to do the UI change since user will likely use the standalone UI to configure the network.

**Comment by yasker** [comment]
> The backend part is better not be merged if the UI can not been changed in this version because we modify some items of the CRD. Otherwise, the UI about the networking will be not work.

Though, we need to maintain the compatibility between the multi-user UI and standalone UI. This makes the change sounds risky if user is going to configure additional vlans in the multi-user UI.

**Comment by WuJun2016** [comment]
https://github.com/harvester/dashboard/commit/3155a482d39a749dd491d71af55a1b9c3ae2ef99

**Comment by guangbochen** [comment]
verified using the master-head ISO - `passed`
1. on the `VLAN` setting configuration page, we were able to view common NICs across all nodes e.g the `harvester-mgmt`
![image](https://user-images.githubusercontent.com/4569037/136648547-834262c5-aff2-492d-a861-c3d4ee0d38af.png)
2. on each host edit page, only showing the available NICs without the master config.
![image](https://user-images.githubusercontent.com/4569037/136648565-fd4ad54c-5c46-4867-97bc-8e404f542f8d.png)
```
** Notes: the UI enhancement is only supported in the single cluster UI due to Rancher/Harvester UI release constraints.
2: eno49: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master harvester-mgmt state UP group default qlen 1000
    link/ether 8c:dc:d4:b5:cb:c4 brd ff:ff:ff:ff:ff:ff
    altname enp4s0f0
3: eno50: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 8c:dc:d4:b5:cb:c5 brd ff:ff:ff:ff:ff:ff
    altname enp4s0f1
    inet6 fe80::8edc:d4ff:feb5:cbc5/64 scope link
       valid_lft forever preferred_lft forever
4: harvester-mgmt: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master harvester-br0 state UP group default qlen 1000
    link/ether 8c:dc:d4:b5:cb:c4 brd ff:ff:ff:ff:ff:ff
    inet 10.84.102.5/24 brd 10.84.102.255 scope global harvester-mgmt
       valid_lft forever preferred_lft forever
    inet6 fe80::8edc:d4ff:feb5:cbc4/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by yasker** [comment]
For UI discrepancy between single and multitenant UI, we need a release note.

**Comment by yaocw2020** [comment]
Reopen to add the enhancement below.

- [x] Filter the NICs which is a slave of one interface in the backend controller.

**Comment by yasker** [comment]
Is it possible to make this feature optional? E.g. can you still type the box even if it's not a common name shared across the node? I have one node has different nic name compare to others, so wondering if I can put the most common NIC in the setting then just update that one node later.

**Comment by yaocw2020** [comment]
> Is it possible to make this feature optional? E.g. can you still type the box even if it's not a common name shared across the node? I have one node has different nic name compare to others, so wondering if I can put the most common NIC in the setting then just update that one node later.

We can optimize the way to show the NIC. A preliminary idea is to show all NICs and the percentages appearing in all nodes.

**Comment by WuJun2016** [comment]
![image](https://user-images.githubusercontent.com/24985926/139777741-9c0e8c36-f53e-4bc6-932c-4e0f2c792fca.png)
![image](https://user-images.githubusercontent.com/24985926/139777757-1828b729-5449-43d1-b37a-ea083456b4a0.png)

**Comment by guangbochen** [comment]
@WuJun2016 how come the `harvester-mgmt` is 50% since it will be created by default of all nodes?

**Comment by WuJun2016** [comment]
@guangbochen  Did you test it on a 4.3 environment? The 4.3 environment is deployed with Lawance's image, so the harvester-mgmt may have problems （The harvester-mgmt on some nodes has been filtered）. I talked about this with @yaocw2020

**Comment by noahgildersleeve** [comment]
Tested in master-d21b9161-head. Fixed.
1. Setup 3 node cluster
2. checked available NICs in Vlan settings
3. All showed as 100% for all nodes
4. Checked with bonded and non-bonded NICs
