### ISSUE TITLE
[BUG] Create images failed at the beginning but finished eventually

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1274]
**Describe the bug**
Create an image shows as "failed" at the beginning:
![image](https://user-images.githubusercontent.com/5047724/134655487-b8901090-fa00-4aa0-9578-495f60fa59ae.png)

But after a while it started to download and eventually succeeded:
![image](https://user-images.githubusercontent.com/5047724/134655678-e858921a-64fc-4059-a5ea-0a2a20cbeaf3.png)

**To Reproduce**
1. Create a Harvester server node
2. Create an image. It succeeded without any issues
3. Add two additional Harvester nodes to join the cluster and wait for it to show on "Hosts" page
4. Create an image, **with a different image URL**
5. The UI shows image creation failed, but recovered after a while and eventually finished the creation

**Expected behavior**
The image shouldn't be in "Failed" state at the beginning

**Support bundle**
[supportbundle_564f0af7-b964-4eb8-9f2b-374b95a26667_2021-09-24T10-10-13Z.zip](https://github.com/harvester/harvester/files/7224867/supportbundle_564f0af7-b964-4eb8-9f2b-374b95a26667_2021-09-24T10-10-13Z.zip)

**Environment:**
 - Harvester ISO version: master-466a24f6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
- This issue occurred only after I added two additional Harvester nodes. When there's only one server node, the image is created without any warning.

- After the image eventually got created and became active,  use the same URL to create another image **would not create any error**.

- Longhorn UI shows this error:
![image](https://user-images.githubusercontent.com/5047724/134655537-fd851607-9bf8-4bd0-b8dd-a353e6fb8a2d.png)

**Comment by guangbochen** [comment]
@shuo-wu is this something that we can improve from the backing image-side?

**Comment by lanfon72** [comment]
not reproduced in regression testing.

**Comment by guangbochen** [comment]
Close as can't reproduce it now; feel free to reopen it if u encounter this again.
