### ISSUE TITLE
[Question]Issue with harvester installer

### ISSUE THREAD

**Issue by sakisx** [harvester/harvester#1276]
Hi, i'am trying to install harevster 0.2.0 on ProLiant XL170r Gen9, but after confirm of installation i have an issue. At the moment i cannot find any solution about that, any advise about ? Everything on server is up to date. Also there is internet connection on that. Of course i try to install v0.3.0-preview1, v0.2.0-rc5 with the same results. Also i try to install harvester on other servers DL170e G6, DL165 G7 with the same issue. Should i check something spesific for example on BIOS? I try to boot harvester with two ways, with media/cd through iLO and with USB stick, and also in dd with rufus.

![Image of issue](https://i.ibb.co/yRZszS9/issue-1.jpg)

**Comment by guangbochen** [comment]
can u please try the https://github.com/harvester/harvester/releases/tag/v0.3.0, thanks
