### ISSUE TITLE
[BUG] No validation of proper hostname format

### ISSUE THREAD

**Issue by gustafj** [harvester/harvester#1277]
**Describe the bug**
When entering a non-conformant `hostname` during installation the system never enters a `Running` state, its stuck at `NotReady`.
`systemctl is-system-running` is `starting` and the queued jobs is stuck at `rancherd`.
`systemctl status rancherd` gives an error printout about the hostname.

**To Reproduce**
Use a non-conformant hostname during install, e.g. `Harvester`

**Expected behavior**
"Error invalid hostname" or similar (e.g. the error output that `rancherd` prints).

It would also be nice if the queued jobs that are not yet completed are listed below the `Status:` line in the console.

**Support bundle**
_Not needed_

**Environment:**
 - Harvester ISO version: 0.3.0-preview1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by FrankYang0529** [comment]
I can reproduce this issue and get error message as following:

```
> journalctl -u rancherd.service
# ...
Sep 27 02:47:27 Harvester rancherd[1821]: time="2021-09-27T02:47:27Z" level=info msg="[stderr]: The Node \"Harvester\" is invalid: metadata.name: Invalid value: \"Harvester\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. Fixed.
![Screenshot from 2021-09-28 12-30-24](https://user-images.githubusercontent.com/83787952/135153418-6a92f923-1993-40ea-b029-f67dc928875a.png)
.
