### ISSUE TITLE
Update support links

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1278]
The support links are referring to the Rancher docs/issues, etc. Change to Harvester links.

**To Reproduce**
1. Click `Support` in the bottom-left corner.
2. Check the links in `Community Support`

**Environment:**
 - Harvester ISO version: master-48c97ea7-head

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/1300, close as that one is more detailed.
