### ISSUE TITLE
[BUG] Missing delete/download yaml buttons in volumes page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1279]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5697937/134795157-f76723d1-c6e6-4a2b-8f58-56809f0bb812.png)

**Environment:**
 - Harvester ISO version: master-48c97ea7-head

**Comment by lanfon72** [comment]
verified download/delete buttons appeared and work normally.

![image](https://user-images.githubusercontent.com/5169694/134932090-e4d298f6-5d8d-401a-b903-5a6ec6033c56.png)
![image](https://user-images.githubusercontent.com/5169694/134929479-73664e59-a325-46bc-a470-ce4a5745a504.png)

Test Information
----
* Environment: bare metal DL360 in Provo
* Harvester Version: master-c6474a74-head
Verify Steps:
  - visit dashboard and navigate to **Volumes**
  - click `...` button or select volume(s)
  - verify **download** and **delete** should shown as expected
  - click **download** to verify there have `.yaml` file downloaded
  - click **delete** to verify there should have prompt for confirmation, and the volume should be remove after confirmed.
