### ISSUE TITLE
[FEATURE] Identify if the NIC is either up or down during ISO installation

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1280]
**Is your feature request related to a problem? Please describe.**
Be able to identify whether the NIC is either up or down during the ISO installation 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/4569037/134795189-0a3afb79-f860-47fe-b9fb-f225fe4d89b2.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by weihanglo** [comment]
FWIW, we identify NIC states [right after confirming the interfaces selection](https://github.com/harvester/harvester-installer/blob/9362db78f85e292f84e848950bd1d83df2f801ef/pkg/console/install_panels.go#L760-L780). Does this enhancement aim to check NIC states at each selection of a single NIC?

**Comment by guangbochen** [comment]
Yep, I got 4 ports of my bare-metal server and only 2 have the cable plugged in, therefore it is hard for me to identify which 2 are enabled from the console during the ISO installation, it would be helpful if we can view it directly when selecting the NICs.

**Comment by gitlawr** [comment]
Verified in https://github.com/harvester/harvester/issues/1328#issuecomment-939245735
