### ISSUE TITLE
[Bug] Exclude OS root disk and partitions from the NDM manager

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1282]
**Is your feature request related to a problem? Please describe.**
The UI should prohibit admin users to either add or force-format the root disk or system partitions from the UI, the NDM manager should identify and exclude the root disk and its system partitions

![image](https://user-images.githubusercontent.com/4569037/134796099-20ac5b73-8ce9-411c-8f55-8c994534d502.png)

**Describe the solution you'd like**
1. using the device label i.e `COS_*` to filter out Harvester OS's root disk and system partitions

```
sudo blkid /dev/sda*
/dev/sda: PTUUID="b79a5360-30af-4fec-afbb-2cd4d2f9bbb6" PTTYPE="gpt"
/dev/sda1: LABEL_FATBOOT="COS_GRUB" LABEL="COS_GRUB" UUID="8C4B-9D2F" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="primary" PARTUUID="6c601349-8337-4cb1-83fc-1f634f675051"
/dev/sda2: LABEL="COS_OEM" UUID="b7ab0874-b444-4164-a9b2-ff4fc192fb4b" BLOCK_SIZE="1024" TYPE="ext4" PARTLABEL="primary" PARTUUID="2b195f7e-8fef-48f6-9916-3b2d6107710c"
/dev/sda3: LABEL="COS_STATE" UUID="c5358b27-b20f-46c0-a821-14e31d12162d" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="fd533d79-6a3a-4065-b2a1-62240fc6f97c"
/dev/sda4: LABEL="COS_RECOVERY" UUID="b504f1ff-9727-4bad-bf4c-007c863ba5f5" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="53f09933-1bc0-40bc-b02e-ea820e2dd9cd"
/dev/sda5: LABEL="COS_PERSISTENT" UUID="dd157207-6b96-43c6-834c-9d6a621e5cb8" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="881d56a1-d4f3-42d1-9817-67f527cc0e92"
```

**Comment by alexdepalex** [comment]
The image below shows multiple nvme drives, which are already partitioned. The partition itself is already added to the disk configuration, so shouldn't those drives be filtered out as well? Not filtering it out just creates noise.

![image](https://user-images.githubusercontent.com/713019/135345395-dbcc83d9-a772-4c31-b127-c3e1843b8de5.png)

**Comment by weihanglo** [comment]
Great advice!

@guangbochen. Given an already provisioned device, I guess we can hide all parent devices of it. Is it possible to address from the UI side?

Also, in regard to filtering out the root disk (`/dev/sda` from above picture), it does not contain any filesystem `LABEL` nor any provisioned partitions, and it also lack disk vendor or mount point. As a result we cannot filter it out by the current filter logic. Do we have any possible idea to deal with this situation?

**Comment by guangbochen** [comment]
Yes, it makes sense to hide/disable add the parent device when its partition is already provisioned cc @n313893254, additionally, can we sort those devices in a proper tree structure e.g like the output of `lsblk`
```
sda       8:0    0  1.6T  0 disk
├─sda1    8:1    0   47M  0 part
├─sda2    8:2    0   47M  0 part /oem
├─sda3    8:3    0   14G  0 part /run/initramfs/cos-state
├─sda4    8:4    0  7.5G  0 part
└─sda5    8:5    0  1.6T  0 part /usr/local
sdb       8:16   0   40G  0 disk
├─sdb1    8:17   0  2.1G  0 part
├─sdb14   8:30   0    4M  0 part
└─sdb15   8:31   0  106M  0 part
``` 

In regards to root disk filtering, I believe those labels are customizable in cOS via https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/stages/, @bk201 do u think it would be better if we label those system disks and partitions with a customized label e.g `HARVESTER_COS_*` cuz the default label will also be used by the other OS build with the cOS tools.

**Comment by bk201** [comment]
@guangbochen Yeah, this will need support from https://github.com/rancher-sandbox/cOS-toolkit/issues/160

**Comment by weihanglo** [comment]
> do u think it would be better if we label those system disks and partitions with a customized label e.g `HARVESTER_COS_*` cuz the default label will also be used by the other OS build with the cOS tools. 

No. I am afraid that we cannot apply ext filesystem `LABEL` on the disk since it's not a formatted partition.


```console
node1:/ # blkid /dev/sdb*
/dev/sdb: PTUUID="636361ad" PTTYPE="dos"
/dev/sdb1: LABEL="COS_OEM" UUID="64e7b722-c5e2-4441-8820-48a9a635d92a" BLOCK_SIZE="1024" TYPE="ext4" PARTUUID="636361ad-01"
/dev/sdb2: LABEL="COS_STATE" UUID="5395f7bf-e2b4-4f26-b06f-03c6a9eb7224" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="636361ad-02"
/dev/sdb3: LABEL="COS_RECOVERY" UUID="7979cfe3-19b3-4972-86ff-f0b7f0143f53" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="636361ad-03"
/dev/sdb4: LABEL="COS_PERSISTENT" UUID="53dc44ad-dd12-4bc8-a65a-4279ac4d693c" BLOCK_SIZE="4096" TYPE="ext4" PARTUUID="636361ad-04"
node1:/ # e2label /dev/sdb COS_DISK
e2label: Bad magic number in super-block while trying to open /dev/sdb
Found a dos partition table in /dev/sdb

node1:/ # blkid /dev/sda*
/dev/sda: PTUUID="dd042c8d-b897-4f2c-a106-6644e7cbd2ac" PTTYPE="gpt"
/dev/sda1: UUID="35a423b0-94aa-4880-b950-518cccc35565" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="5af16e6c-bbdd-44c4-a06c-80994815b4be"
node1:/ # e2label /dev/sda
e2label: Bad magic number in super-block while trying to open /dev/sda
Found a gpt partition table in /dev/sda
node1:/ #
```

**Comment by yasker** [comment]
@weihanglo Is there a UI change related to this? If so, we might have to punt it to v1.0.0 since Rancher UI's merge window has closed.

**Comment by weihanglo** [comment]
I don't think so. For this issue we filter disk only on the backend logic.

**Comment by guangbochen** [comment]
Verified with the `master-9f917060-head` version - `passed`
- system root disk is not shown as an additional volume option
![image](https://user-images.githubusercontent.com/4569037/136678693-2f183375-e8d9-4ddf-9976-c6499c4aad98.png)
-  root disk volumes are filter out if its partitions contain the filter label, i.e `COS_*`
```
harvester-bcmxw:/home/rancher # blkid
/dev/sda1: LABEL_FATBOOT="COS_GRUB" LABEL="COS_GRUB" UUID="7E18-E307" BLOCK_SIZE="512" TYPE="vfat" PARTLABEL="primary" PARTUUID="9e577ded-1070-4685-8064-d4682f3bc7ec"
/dev/sda2: LABEL="COS_OEM" UUID="30ead577-ea78-40ef-b409-5cc7cd0822b2" BLOCK_SIZE="1024" TYPE="ext4" PARTLABEL="primary" PARTUUID="b4f738fd-ba4b-4cd9-97da-c76b21d0a8f6"
/dev/sda3: LABEL="COS_STATE" UUID="33ff11a6-add5-462e-8918-898d7129312d" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="9659c01d-ccf8-4798-908d-124f2a078b96"
/dev/sda4: LABEL="COS_RECOVERY" UUID="4ccbca48-7162-4a97-bfee-90cbc933e6da" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="7d534afc-d0b5-44bc-9a56-1fc4b73a9713"
/dev/sda5: LABEL="COS_PERSISTENT" UUID="ecf0987a-0e93-45b8-9f67-7d3667cb6995" BLOCK_SIZE="4096" TYPE="ext4" PARTLABEL="primary" PARTUUID="b0e6bf8f-b294-423f-825f-c1c74f12e1ea"
/dev/loop0: LABEL="COS_ACTIVE" UUID="45d58a61-39d5-4e57-b4dd-598cb7cad0a8" BLOCK_SIZE="4096" TYPE="ext2"
```

**Comment by alexdepalex** [comment]
It still shows any attached cdrom drives, also in the UI. Should we open a new ticket? Or can this one be reopened?


```
node1:~ # kubectl get blockdevices.harvesterhci.io -A -o wide|grep node1
longhorn-system   12df0e8f129b4bac41cb464be4f18c61   disk   /dev/nvme2n1                                                                       node1   Active   7h7m
longhorn-system   7a5a7e5945582182f5c850bb4f9c67b2   disk   /dev/sr0                                                                           node1   Active   4h28m
longhorn-system   7f95ff328dda0610d5386f0e9b33447b   disk   /dev/nvme4n1                                                                       node1   Active   7h7m
longhorn-system   8b964ba6f099f9c37ad67f7e0dcfbc88   disk   /dev/nvme0n1                                                                       node1   Active   7h7m
longhorn-system   9a2271cb4fe2209b47d01bc330294418   disk   /dev/nvme1n1                                                                       node1   Active   7h7m
longhorn-system   c0e69dd92a250119fc1acf9ee386587f   disk   /dev/nvme3n1                                                                       node1   Active   7h7m
longhorn-system   c3c3365dfe86e88b61d0fa0a6bb275fa   disk   /dev/nvme5n
```

**Comment by guangbochen** [comment]
> 

I think u have raised it in https://github.com/harvester/harvester/issues/1623#issuecomment-985108607, let's just track it over there, thanks.
