### ISSUE TITLE
[BUG] Fix required fields on VM creation page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1283]
**Describe the bug**
1. Both image and size are required for an image volume
![image](https://user-images.githubusercontent.com/5697937/134796480-47e2312b-8f5f-4360-9a8a-1da87a677150.png)
2. Hostname is not required
![image](https://user-images.githubusercontent.com/5697937/134796495-a4544680-b409-4285-81ad-027da3f7960e.png)
3. Also, update the input labels:
Host Name => Hostname
MachineType => Machine Type

**Version**
master-48c97ea7-head

**Comment by johnliu55tw** [comment]
## Test info
- Verified Harvester version: v0.3.0-rc1

## Test cases
- Create VM with required Volume fields not filling in **should result in errors**
  - [x] Volumes -> Image
  - [x] Volumes -> Size
- Add another volume while creating VM, with required fields not filling in **should result in errors**
  - [x] Add another Volume with "Size" empty
- Create VM with optional fields not filling in should be OK
  - [x] Advanced Options -> Hostname

## Comments
I do notice a weird behavior: After the error message of "Size is required" appeared, the value I entered in "Size" field would disappear after I clicked somewhere else:
![Peek 2021-10-01 17-12](https://user-images.githubusercontent.com/5047724/135595980-16cdd757-8a4f-4808-a48f-ad8d218cdcd4.gif)

**Comment by yasker** [comment]
Move back to Implement due to a bug. cc @WuJun2016

**Comment by yasker** [comment]
Move to v1.0.0 due to Rancher UI merge window has closed.

**Comment by noahgildersleeve** [comment]
Tested in master-d05a6cc7-head. Verified as fixed.
1. Tried to create without image name and size
2. Tried to create without size
3. Had to enter both before creation was successful
4. Hostname wasn't required
