### ISSUE TITLE
[BUG] A force-formatted disk was not added as an additional data volume

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1285]
**Describe the bug**
A force-formatted disk was not added as an additional data volume successfully.
![image](https://user-images.githubusercontent.com/4569037/134797055-a3d52745-c64d-4139-bd8a-f5621f74aa13.png)

**To Reproduce**
1. Select an additional disk that already has a partition and filesystem type
2. Set the `force-formatted` to true
3. click save and check the node disks again
4. no additional disk was added to the LH side

Issue:
We should provisioning the single root partition after force-format instead of the original block device.
e.g that should be `/dev/sdb1` instead of the `/dev/sdb`
![image](https://user-images.githubusercontent.com/4569037/134797509-3394edf3-538c-4f74-88df-3023e5f97913.png)

**Expected behavior**
The force-formatted disk should be added as an additional data disk.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by lanfon72** [comment]
> Expected behavior
The force-formatted disk should be added as an additional data disk.

The _Expected behavior_ been verified in #1240 , for raw disk without partition, it is not allowed to be added as a additional disk.
![image](https://user-images.githubusercontent.com/5169694/135549243-6a0e1660-e2ea-45bb-b051-e3e33f09d07e.png)


Test Information
----
* Environment: **Laptop qemu/KVM** single node
* Harvester Version: **v0.3.0-rc1**
### Verify Steps:
1. create VM with 2 disks
2. Install Harverster
3. login to console, use `lsblk` to check 2nd disk don't have any partition
4. open dashboard, navigate to host's disk section, check raw disk such like `/dev/sdb` is not allowed to be added
5. login to console, use `fdisk` to create a partition on 2nd disk
6. open dashboard, navigate to host's disk section, check raw disk such like `/dev/sdb` is still not allowed to be added

**Comment by lanfon72** [comment]
The UI and error message still enhance-able, I would check related issues and open one if needed.
