### ISSUE TITLE
[BUG] Prometheus rules are not deployed because the CRD is not installed

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1289]
**Describe the bug**
There is a possibility that the kubevirt Prometheus rules are not deployed because the CRD is not installed

**To Reproduce**
1. install the master-head image of the `v0.3.0` version e.g `master-48c97ea7-head`
2. check the Harvester cluster is up and running
3. check the monitoring of service monitor and Prometheus rules, at times the Prometheus rules or service monitor is not created of the kubevirt-operator

**Expected behavior**
both kubevirt's service monitor and Prometheus rules should be created, and this is because the race-condition of the `virt-operator` and Prometheus-CRD chart, as there is a possibility that the `monitoring-crd` chart is not installed before the `virt-operator` is running.

**Workaround**
delete the virt-operator pod in the `harvester-system` namespace and it will be created successfully

**Environment:**
 - Harvester ISO version:  `master-48c97ea7-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by weihanglo** [comment]
Upstream issue: https://github.com/kubevirt/kubevirt/issues/6551
This might be a feasible solution (and maybe the best at this time).

**Comment by alexdepalex** [comment]
@guangbochen We experience the same on all our v1.0.1 clusters, which means no VM metrics.

**Comment by guangbochen** [comment]
As a temp workaround, you can trigger the Prometheus rules redeployment by restarting the kubevirt operator pod:
```
$ kubectl get pod | grep virt-operator | awk '{print $1}' | xargs kubectl delete po
```

**Comment by belgaied2** [comment]
Do we have news on this? This is pending since mid-April. Though it might be acceptable to use the workaround once per Harvester cluster, the issue itself is definitely problematic.

**Comment by guangbochen** [comment]
This is an upstream bug related to the https://github.com/kubevirt/kubevirt/issues/6551, also the issue only occurs when there is a race condition during the cluster-init bootstrap, not every installation or cluster will encounter this problem, but we will see if we can make some contribution to the upstream kubevirt, thanks for bearing with us.

**Comment by w13915984028** [comment]
The `kube-operator` saves  `service monitor enable` and `promethues enable` into local flag when it starts up by checking if related CRDs are in ApiServer. And later only use local saved flag.  Hence, both of those two have no chance to be enabled later. Current workaround is to delete the POD via kubctl, then the replaced new POD will have related local flag enabled.

I will add it to harvester doc troubleshooting
https://docs.harvesterhci.io/v1.0/troubleshooting/monitoring/

And look for a patch to upstream kubevirt.

```
kubevirt/kubevirt/pkg/virt-operator/application.go

serviceMonitorEnabled, err := util.IsServiceMonitorEnabled(app.clientSet)
prometheusRuleEnabled, err := util.IsPrometheusRuleEnabled(app.clientSet)
```

**Comment by w13915984028** [comment]
Another possibility, let's check if it can be patched in the Harvester `cluster-init bootstrap` before `kube-operator` has a fix.

**Comment by w13915984028** [comment]
> $ kubectl get pod | grep virt-operator | awk '{print $1}' | xargs kubectl delete po

Update the workaround: the namespace is needed.

check the virt-operator pod
 ```
 $ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl get pods -n harvester-system
 
 NAME                             READY   STATUS    RESTARTS   AGE
virt-operator-78b84587c9-zw2cd   1/1     Running   0          4m51s
 ```
 
 delete the virt-operator pod
 ```
 $ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl delete pod -n harvester-system
 ```
 
 verify the newly replaced virt-operator pod log to confirm `prometheusrule is defined`
 ```
 $ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl logs -n harvester-system | grep "prometheusrule is defined"
 
{"component":"virt-operator","level":"info","msg":"prometheusrule is defined","pos":"application.go:262","timestamp":"2022-07-12T15:58:40.080472Z"}
 ```

**Comment by guangbochen** [comment]
The best way to address this issue would require an upstream fix of https://github.com/kubevirt/kubevirt/issues/6551 and PR https://github.com/kubevirt/kubevirt/pull/9646, postpone to the future milestone and please refer to the [above workaround solution](https://github.com/harvester/harvester/issues/1289#issuecomment-1102347781) if u have encountered this issue, thanks.

**Comment by LucasSaintarbor** [comment]
@guangbochen Would a KB article referencing this workaround (https://github.com/harvester/harvester/issues/1289#issuecomment-1102347781) work best? Or do you want this workaround included under **Troubleshooting > Monitoring**?

**Comment by guangbochen** [comment]
@LucasSaintarbor adding a doc to the `Troubleshooting > Monitoring` should be good enough, btw since the upstream PR https://github.com/kubevirt/kubevirt/pull/8914 is merged, so we will backport the fix to the Harvester v1.2.0 release, thanks.

**Comment by chrisho** [comment]
This is on the v1.2.0 test plan:
1. Check the Harvester cluster is up and running
1. Enable rancher-monitoring on the add-on page
1. Check if the monitoring service monitor and Prometheus rules have been created.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2-a5e74302-head**
* **ui-source** Option: **Auto**


### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, navigate to _Advanced/Addons_
3. Enable `rancher-monitoring`
4. Login to console, execute `kubectl get pods -A | grep monitor`, all pods should be updated to **Running** excepts `helm-install-rancher-monitoring`
5. In dashboard page _Advanced/Addons_, state of `rancher-monitoring` should be updated to **DeploySuccessful**
6. Access Prometheus dashboard in _Prometheus tab_ of `rancher-monitoring`
7. Status of Runtime & Build Information should have _Start time_ and _Configuration reload: Successful_
8. Access Grafana dashboard in _Grafana tab_ of `rancher-monitoring`
9. Monitoring data should displayed accordingly
