### ISSUE TITLE
[FEATURE] Support running Harvester on VM

### ISSUE THREAD

**Issue by olljanat** [harvester/harvester#1290]
Now when Harvester is based on RKE2 it is actually easiest way to create RKE2 clusters. That why it would be very useful to have support to run Harvester also on VMs which would allow configurations like:
* Master nodes on VMs + workers on bare metal
* Shared HCI platform on bare metal and separate dev and production application RKE2 clusters on VMs (Harvester in Harvester)

Afaiu only requirement for Harvester to support VM mode is that it should detect nodes which which have virtualization support, label them and use `nodeSelector` on kubevirt and kubevirt-operator charts.

**Comment by abonillabeeche** [comment]
Can you please clarify this use case? I don't see how it makes a lot of sense.

**Comment by olljanat** [comment]
Currently outside of Harvester anyone who want to run RKE2 + Longhorn must first create VM with some of these OS versions https://docs.rke2.io/install/requirements/#linux , then install RKE2 and then Longhorn which takes a lot of more time than just installing Harvester and mean that after that user also need to care about maintaining those.

Of course if Rancher/Suse will release another similar OS than k3OS is but with RKE2 then it does the trick but IMO that does not make any sense as Harvester can very easily support those use cases too by just disabling components which are not needed on VMs.

Also if I can choose between supporting one or two OS for our users I would prefer to go with just one and use my effort to make that as good as possible.

**Comment by olljanat** [comment]
#1294 should do the trick that any Harvester node(s) which are running on VM will be labeled with `kubevirt.io/schedulable=false` so even hybrid VM + bare metal mixed clusters should works correctly as `virt-operator` will schedule VMs only to nodes which can run them.

**Comment by gitlawr** [comment]
Kubevirt deploys device plugins to detect virtualization support on nodes. Eash VM pod has the resource request for the kvm device. It ensures that VMs are scheduled to nodes with kvm available. Is that not working for you?
```
      requests:
        devices.kubevirt.io/kvm: "1"
```

Running Harvester on VMs works for me, can you describe the problems you've encountered?

**Comment by olljanat** [comment]
The most critical thing would be to get answer to question that: Is this something which will be officially supported? I mean for real production workloads and running non-VM pods?

Having OS like k3OS where need for maintenance is minimized makes a lot of sense but https://github.com/harvester/harvester/issues/581#issue-840585458 very clearly says that it have no been officially supported by Rancher / Suse and we need something which is. And IMO Harvester is already much better than k3OS because it comes with Longhorn, Fleet, Rancher, etc bundled to it.

From technical point of view only issue I can see is that nodes without virtualization support are labeled with `kubevirt.io/schedulable=true` which at least looks very confusing for anyone who is looking for those.

**Comment by abonillabeeche** [comment]
@olljanat Harvester is a virtualization platform. At the moment, it doesn't need separate masters or cp nodes that need to be running outside of the workload nodes. Harvester facilitates the creation of virtual machines on a container platform (as the implementation infrastructure) - It is meant to be running on bare-metal.

**Comment by olljanat** [comment]
@abonillabeeche but what is/will be the officially supported way to run RKE2 with minimum maintenance work (like k3OS) then? Will there be one more OS?

#372 is related as my use case of course need support to run non-VM pods on Harvester too.

**Comment by olljanat** [comment]
May I ask the mastermind @ibuildthecloud to share his vision about where this k3OS/RKE2/Harvester/etc should/will go from non-VM pods point of view? (Someone may need ping him on Rancher/Suse as I guess that he will not get notification from this).

I see that Harvester takes automation to totally new level compared to k3OS as it also automates Fleet, kube-vip, Prometheus, etc... installation, configuration and upgrades and it is very sad if nothing similar will be available for non-VM pod use cases.

**Comment by olljanat** [comment]
> @abonillabeeche but what is/will be the officially supported way to run RKE2 with minimum maintenance work (like k3OS) then? Will there be one more OS?

Looks that we got answer to that question on https://rancher.github.io/os2/ so closing this one.
