### ISSUE TITLE
Task: Public available test plan

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1291]
We should make all of our automation and manual test plan available at https://github.com/harvester/tests , so adding the test plan can be a part of the requirement for closing the issue.

Ref:
https://github.com/longhorn/longhorn-tests
https://longhorn.github.io/longhorn-tests/manual/
https://longhorn.github.io/longhorn-tests/integration/
https://github.com/longhorn/longhorn/issues/2460#issuecomment-919132422

**Comment by noahgildersleeve** [comment]
The tests are available at https://github.com/harvester/tests in the docs folder and the tests are also available and being published on CI at https://harvesterhci.io/tests/ .
