### ISSUE TITLE
[BUG] Unnecessary DNSNameservers in networks configurations

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1296]
**Describe the bug**
We already have an `os.dns_nameservers` [field](https://github.com/harvester/harvester-installer/blob/212059f8bc7561477e258bb3554ed7ba008f3a36/pkg/config/config.go#L101) to specify static DNS nameservers, it doesn't make sense to have [per-network DNS servers.](https://github.com/harvester/harvester-installer/blob/212059f8bc7561477e258bb3554ed7ba008f3a36/pkg/config/config.go#L38)

We also need to update the doc.

**Additional context**
per-network DNS servers are used in [connman services](https://manpages.debian.org/testing/connman/connman-service.config.5.en.html). Connman is the network manager of k3os.

**Comment by johnliu55tw** [comment]
## Test info
Verified version: master-c4a76706-head

## Verify DNS settings
- Check `/etc/resolv.conf`

## Test cases and Results
- DHCP Network
  - [x] Leave DNS setting empty, then the system should use DNS provided by DHCP - PASS
  - [x] Enter one DNS IP, then the system should use it - PASS
    - `1.1.1.1`
  - [x] Enter multiple DNS IPs, then the system should use them all in the given order - PASS
    - `1.1.1.1,8.8.8.8,8.8.4.4`
- Static Network
  - [x] Leave DNS setting empty, then the system should **not** have any DNS settings - PASS
  - [x] Enter one DNS IP, then the system should use it - PASS
    - `1.1.1.1`
  - [x] Enter multiple DNS IPs, then the system should use them all
    - `1.1.1.1,8.8.8.8,8.8.4.4`
- Negative Test Cases
  - [x] Prevent users from proceeding with installation if DNS addresses are invalid - PASS

## Comments
- For Static Network, empty DNS would cause any further steps (NTP, Import SSH Key, ...) that require domain name resolving to fail. IMO that does remind users to set up DNS correctly.
- For DHCP Network, if I entered one DNS, there will be two DNS `nameserver` rows in `/etc/resolv.conf`. The other is provided by the DHCP server.
  ![image](https://user-images.githubusercontent.com/5047724/136321917-068c3065-7163-46e8-b4a2-21bf13355758.png)
