### ISSUE TITLE
[BUG] Don't support the disk more than 4294967295 section

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1299]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7421463/135037454-29896a82-07aa-4a91-af0f-19a831b32e56.png)
Install failed with a 9.5T nvme disk

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: harvester0.3 pre1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  Baremetal

**Additional context**

May need to switch to GTP partitions.

**Comment by bk201** [comment]
@yaocw2020  Is this tested on legacy BIOS or UEFI mode? For large disks, we might want to use UEFI mode (or turn on the `COS_INSTALL_FORCE_EFI` flag) because the installer [defaults to msdos partition in legacy mode](https://github.com/rancher-sandbox/cOS-toolkit/blob/0b3d79b22e5b09644fa91bf2253a5bf3252a5eec/packages/installer/installer.sh#L297-L309).

**Comment by yaocw2020** [comment]
> @yaocw2020 Is this tested on legacy BIOS or UEFI mode? For large disks, we might want to use UEFI mode (or turn on the `COS_INSTALL_FORCE_EFI` flag) because the installer [defaults to msdos partition in legacy mode](https://github.com/rancher-sandbox/cOS-toolkit/blob/0b3d79b22e5b09644fa91bf2253a5bf3252a5eec/packages/installer/installer.sh#L297-L309).

I don't know. It's the problem from a community user.

**Comment by gitlawr** [comment]
Most likely happens on BIOS. With the 2^32*512 bytes = 2TB disk size limit of MBR

**Comment by johnliu55tw** [comment]
Tested on a VM with UEFI firmware (`ovmf-x86_64-code.bin`), the partition table automatically becomes GPT.

**Comment by tscswcn** [comment]
changed to Unified Extensible Firmware Interface (UEFI)，still have issue. 
it is me who raise this issue. 
![harvester_uefi_issue1](https://user-images.githubusercontent.com/16184308/135377635-d8b646c7-929a-4386-b80c-09e7930badd8.JPG)

**Comment by guangbochen** [comment]
@tscswcn what is your Harvester ISO image version, can u try the v0.3.0-rc1 if u are not using this one, thanks?

**Comment by bk201** [comment]
@tscswcn The error message is different from what's in the issue description. line 103 is:
`parted -s ${DEVICE} mklabel ${PARTTABLE}`, looks like the disk can't be written. Dumping your `dmesg` output might help.

**Comment by tscswcn** [comment]
> @tscswcn what is your Harvester ISO image version, can u try the v0.3.0-rc1 if u are not using this one, thanks?

harvester 0.3- prew

**Comment by tscswcn** [comment]
> @tscswcn The error message is different from what's in the issue description. line 103 is: `parted -s ${DEVICE} mklabel ${PARTTABLE}`, looks like the disk can't be written. Dumping your `dmesg` output might help.

how to do this for just install?

**Comment by johnliu55tw** [comment]
@tscswcn you can switch to another virtual terminal by `Ctrl + Alt + F2` and log in with `rancher/rancher` to execute some commands during installation.

**Comment by rknightion** [comment]
I'm on v0.3.0-rc1 and running into this, but my server has no UEFI support (this is with a 2.2TB disk
<img width="779" alt="Screenshot 2021-10-01 at 17 23 13" src="https://user-images.githubusercontent.com/12484127/135654878-d10ffce8-29e0-439e-9a30-9d33c4aa17f6.png">
)
Most other operating systems I install seem to partition the disks as GPT by default. Is there a way to achieve this via some kind of preseed/config file or manual partitioning?

**Comment by yasker** [comment]
We need to fix this in v0.3.0. It's common for users to have a hard drive bigger than 2T (which around 4294967295 * 512).

**Comment by johnliu55tw** [comment]
We could force using GPT partition scheme on legacy BIOS system, as GRUB supports this. I've submitted a PR for cOS-tookit for this usage: https://github.com/rancher-sandbox/cOS-toolkit/pull/759

**Comment by futuretea** [comment]
validated 3T+BIOS  on harvester/harvester-installer@da460c7
![dfd5155448f1af1bf0ba9b72840bea5](https://user-images.githubusercontent.com/15064560/136653772-b23b9a08-ccf4-4ea2-8f83-9c0312cf2fee.png)
![9e375d277f1b6657175a7a33148e578](https://user-images.githubusercontent.com/15064560/136653779-3b665752-a77d-4dc0-96d6-9fd355b86a2a.png)
