### ISSUE TITLE
[BUG] Delete cluster throw an error

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1301]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/88e9b1ad-73d2-43ec-a5d4-80cb0081c18f)

**To Reproduce**
The issue is random reproduction, reproduce on delete cluster.

**Comment by guangbochen** [comment]
the `harvesterhci.io.management.cluster` CRD does not exist, can u check why the UI uses this type.

**Comment by n313893254** [comment]
`harvesterhci.io.management.cluster` is a spoofedType defined by UI, use for custom data model and route.

**Comment by gitlawr** [comment]
This is consistently reproducible for me. Steps:
1. Set up Rancher v2.6-head(v2.6-06e19b04ce49a4a8f2895769cfa892b8ad14575c-head)
2. Import a Harvester v0.3.0-preview1
3. Delete the harvester cluster from virtualization management

**Comment by n313893254** [comment]
I found the reproduce steps:

1. Go to "virtualization management"
2. Import a cluster named "test"
3. Click another harvester cluster, and then go to the harvester dashboard.
4. Go to "virtualization management" throw the side menu.
5. Delete the "test" cluster.

**Comment by shangma** [comment]
### Test Info

- Verified info:
    - Harvester: v0.3.0-rc1
    - Rancher: v2.6.1-rc10
- Environment: rancher in a vm, harvester inside another, and both are running in KVM


### Test case

1. start rancher in a vm, start harvester in another
2. import harvester into rancher from "Virtualization Management"
3. once the imported one is active, delete it
4. the imported harvester cluster is **successfully** removed from rancher
