### ISSUE TITLE
[BUG] Unable to generate support bundle

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1302]
### Describe the bug
generate support bundle failed but no error message displayed.
(please check log file in additional context)

### To Reproduce
1. navigate to `support`
2. click `Generate Support Bundle` and perform

### Expected behavior
1. process number should increasing  (or maybe move console's log up here?)
2. when generate failed,there should display error message

## Environment:
 - Harvester ISO version: **master-c6474a74-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
UI test case No.3
- [browser_console.log](https://github.com/harvester/harvester/files/7241920/browser_console.log)
- snapshot
![image](https://user-images.githubusercontent.com/5169694/135041368-3660eabc-ff4a-468d-8501-c4e8cb163a3f.png)

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. Created new support bundl
[supportbundle_5e8c08b6-5b6d-46c1-9ebc-612e9547f365_2021-09-29T01-26-44Z.zip](https://github.com/harvester/harvester/files/7248961/supportbundle_5e8c08b6-5b6d-46c1-9ebc-612e9547f365_2021-09-29T01-26-44Z.zip)
e
