### ISSUE TITLE
[BUG] Lack Edit as YAML button for resource creation

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1304]
### Describe the bug
Some resources lack the button of `Edit as YAML` to create.
All of those listed in **Expected behavior**.

### To Reproduce
1. navigate to the topic listed in **Expected behavior**
2. Click `Create` button
    (in the right up, It seems some confusing when you click it and u still need click another _Create_ button, maybe we can renaming to `NEW` would be more suitable?)
3. `Edit as YAML` button should appeared aside `Create` Button

### Expected behavior
- [x] Virtual Machines
  - [x] Basic
  - [x] Volumes
  - [x] Networks
  - [x] Node Scheduling
  - [x] Advanced Options
- [x] Volumes
- [x] Images
  - [x] Basics
  - [x] Labels
- [x] Namespaces

** Advanced Option **
- ~~Templates~~  * will not allowed to edit as YAM[^1]
- ~~Backups (button shows `Restore Backup` in there)~~ * will not allowed to edit as YAM[^1]
- [x] Networks
- [x] SSH Keys
- [x] Cloud Config Templates

## Environment:
 - Harvester ISO version: **master-c6474a74-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
UI test case NO.5

[^1]: https://github.com/harvester/harvester/issues/1304#issuecomment-968281936

**Comment by WuJun2016** [comment]
Restoring a backup is not suitable for normal Edit as YAML,   
Creating a Template requires two api calls, so Edit as YAML is not supported either

**Comment by lanfon72** [comment]
@WuJun2016 this issue will put back to _**implement**_ as there have several functions not work correctly.


Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: **master-45e25939-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Click **Create**
2. fill in required data
3. Click **Edit as YAML**
4. Click **Create**

### Verified not work correctly listed below:
- Virtual Machine: Create Failed[^1]
    1. attributes not propagate to YAML in spec.domain: `memory`, `devices.bootOrder`, `machine.type`, `resources.limits`, `hostname`, `volumes`, `cloudInitNoCloud`
- Volumes: Create success, but pending in `NotReady` state
    1. Volume created from YAML, no `volumeName` assigned (same behavior in source New/VM Image)
- Images: Create failed
    1. label will not be added (both Form and YAML)
    2. url and name assign
    3. Create button will show `Error` but no error message displayed, switch back to Form view, create successfully.
- Networks: Create failed, `Vlan ID` is not assign in YAML.
- Cloud Config Templates: Create succeed, but won't appear in page.


[^1]:
![image](https://user-images.githubusercontent.com/5169694/142390906-8bb28097-185f-4d49-be2f-e7cc2c002df6.png)

**Comment by lanfon72** [comment]
Verified those functions work correctly.

Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-7a54d362-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Click **Create**
2. fill in required data
3. Click **Edit as YAML**
4. Click **Create**

### Verification
- [x] Virtual Machine: Create Failed
    1. attributes not propagate to YAML in spec.domain: `memory`, `devices.bootOrder`, `machine.type`, `resources.limits`, `hostname`, `volumes`, `cloudInitNoCloud`
- [x] Volumes: Create success, but pending in `NotReady` state
    1. Volume created from YAML, no `volumeName` assigned (same behavior in source New/VM Image)
- [x] Images: Create failed
    1. [x] label will not be added (both Form and YAML)
    2. [x] url and name assign
    3. [x] Create button will show `Error` but no error message displayed, switch back to Form view, create successfully.
- [x] Networks: Create failed, `Vlan ID` is not assign in YAML.
- [x] Cloud Config Templates: Create succeed, but won't appear in page.

**Comment by lanfon72** [comment]
@guangbochen Create Image via **Upload File** not work with **Edit as YAML**, should we add some error message to block user when creating, or just leave it work?
Currently, create image from YAML will failed after 1 min and error messages shows as:
![image](https://user-images.githubusercontent.com/5169694/143831705-d61db6a9-7ae5-4f39-9521-1a9d4d94e79e.png)

cc @WuJun2016

**Comment by gitlawr** [comment]
Leave it as it is. 
it needs the following 2 APIs to do that: 1. create an image. 2. call the upload action
It timeouts out after 60 seconds if no upload action is invoked.
We cannot call actions via editing resource yaml so I would say it's by design.

**Comment by WuJun2016** [comment]
I don't think uploading a file to create an image should support Edit as Yaml.

**Comment by WuJun2016** [comment]
The front-end should hide Edit as Yaml when the user chooses to upload a file.   @lanfon72

**Comment by lanfon72** [comment]
> I don't think uploading a file to create an image should support Edit as Yaml.
> The front-end should hide Edit as Yaml when the user chooses to upload a file. @lanfon72

yeah, I don't think File API could be called outside DOM....
I'm thinking that should we hide the button or block creating when user input `sourceType: upload` ...

**Comment by lanfon72** [comment]
verified the button `Edit as YAML` will not appear when creating Images from File.

Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-7a54d362-head**
* **ui-source** Option: **Auto**
