### ISSUE TITLE
[BUG] VM Backup can only be restored once

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1309]
**Describe the bug**
A VM backup can only be restored once using "Restore New", then both "Restore New" and "Replace Existing" no longer work. However, a browser refresh would make them work again.

**To Reproduce**

1. Create a VM `ubuntu1`
2. Create a backup `ubuntu1-file1`, go to _Backups_ page and wait for it to be Ready
3. Click "Restore New" to create a new VM named `ubuntu1-file1-restored` with the backup
4. Wait for the new VM `ubuntu1-file1-restored` to finish restoring
5. Go to _Backups_ page
6. Now click "Replace Existing" using the same backup `ubuntu1-file1` with default options
8. Automatically jump back to _Virtual Machines_ page, but **nothing happened**
9. From now on, **both "Replace Existing" and "Restore New" would have no effects**. It jumps back to the Virtual Machines page after I clicked Create but nothing happened.
10. **Refresh the browser, then "Restore New" works again**

**Expected behavior**
I should be able to restore the backup multiple times without browser refreshing.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-466a24f6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
After several additional tests, "Restore Virtual Machine" page started to show some weird error messages:
![image](https://user-images.githubusercontent.com/5047724/135063570-9027ba5b-2776-4308-b0ad-3c17b734c86b.png)

**Comment by lanfon72** [comment]
Verified we can restore backup any number of times now.

![image](https://user-images.githubusercontent.com/5169694/136019224-3e28ac30-990a-4a6a-916a-ab7dfd032177.png)

Test Information
----
* Environment: **Bare mental DL360** 3 nodes
* Harvester Version: **master-82506f55-head**
### Verify Steps:
 ** Follow the Reproduce steps above**
