### ISSUE TITLE
ui settings page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#131]
1. move the setting page to the harvester UI(i.e. similar to the namespace page).
2. change the user logo to avatar style(please refer to the rancher UI).
3. update setting's drop style and make it consistent with the current UI design.
![image](https://user-images.githubusercontent.com/4569037/92871160-34891880-f437-11ea-8836-60223bdf42eb.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/82
