### ISSUE TITLE
[BUG] Deleting a cluster in rancher dashboard doesn't fully remove it

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1311]
**Describe the bug**

When you delete an RKE1/RKE2 cluster from rancher dashboard for Harvester it will remove the nodes from Harvester, but the last node doesn't appear to be removed on the rancher side. It just says that it's still waiting to be removed. On the Harvester side it is removed though.
**To Reproduce**
1. Create 3 node RKE2 cluster on Harvester through node driver with Rancher
2. Wait fo the nodes to create, but not fully provision
3. Delete the cluster
4. Wait for them to be removed from Harvester
5. Check Rancher cluster management

**Expected behavior**

They should be fully removed from both Rancher and Harvester
**Support bundle**

**Environment:**
 - Harvester ISO version: master-b7b757e9-head
 - Rancher version: v2.6-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
Add any other contex
![Greenshot 2021-09-28 07 33 59](https://user-images.githubusercontent.com/83787952/135108378-4de7c776-2294-41fe-9f42-de3613cec030.png)
t about the problem here.
It says that it's waiting for the last node to delete, but since it's already removed from Harvester it doesn't seem to finish. I wonder if it's not catching the d
![Greenshot 2021-09-28 07 32 15](https://user-images.githubusercontent.com/83787952/135108328-2c103348-a6da-4053-ad96-e434b1b101ac.png)
elete, or if it's not properly listing the RKE1/RKE2 nodes

**Comment by guangbochen** [comment]
The guest k8s cluster is not removed successfully because the management cluster CR is blocked by the `cluster-agent-controller-cleanup` finalizer. After deleting the finalizer manually the cluster will be clean up successfully.
![image](https://user-images.githubusercontent.com/4569037/137457152-eccc1205-7422-4b03-80c5-6ae61ead1387.png)

Will need to check the finalizer issue on the Rancher side.

**Comment by guangbochen** [comment]
Probably this is also fixed in Rancher v2.6.2, can we please help to re-validate it, thanks.

**Comment by FrankYang0529** [comment]
I can't reproduce this on Harvester master-119c2c48-head with Rancher v2.6.2.

## Harvester setup steps

* Create a 3-node cluster.
* Change Rancher version to v2.6.2
```
# ssh to one of Harvester nodes.
> sudo -i

# Extract the rancher install image.
> mkdir mkdir -p /usr/local/harvester-upgrade/rancher
> sudo wharfie --images-dir /var/lib/rancher/agent/images/ rancher/system-agent-installer-rancher:v2.6.2 /usr/local/harvester-upgrade/rancher

# Export helm chart values.
> sudo -i /usr/local/harvester-upgrade/rancher/helm get values rancher -n cattle-system -o yaml > /usr/local/harvester-upgrade/rancher/values.yaml

# Edit `rancherImageTag` to `v2.6.2`.
> vim /usr/local/harvester-upgrade/rancher/values.yaml

# Apply the helm chart
> sudo -i /usr/local/harvester-upgrade/rancher/helm upgrade rancher /usr/local/harvester-upgrade/rancher/*.tgz --namespace cattle-system -f /usr/local/harvester-upgrade/rancher/values.yaml

# Wait until rancher version changes.
> sudo -i kubectl get settings.management.cattle.io server-version -w

NAME             VALUE
server-version   v2.6.1-harvester2
server-version   v2.6.2
```

* Import Harvester cluster to Rancher v2.6.2.
* Enable Harvester Node driver.
* Setup Images, SSH Keys and, VLAN Networks.

## Test cases

Create 3 node RKE2 cluster on Harvester through node driver with Rancher.

✅  **Delete RKE2 cluster before VMs are created.**
✅  **Delete RKE2 cluster before VMs are in Running state.**
✅  **Delete RKE2 cluster if there is a node provisioning failed**
✅  **Delete RKE2 cluster if one node is provisioning successfully, but the other 2 nodes aren't.**

**Comment by TachunLin** [comment]
Verified on master-a4ed2af5-head with rancher 2.6.2 
**Did not encounter** the cluster or vm not fully removed result. Suggest we can close this issue if no additional concern. 

### Result

Verify under the following 3 different scenario, all of them can remove rke2 cluster from rancher and corresponding vm node in harvester 

1. Rancher: 2 node in provisioning, 1 node with failed (Harvester: 2 vm running, 1 vm running w/o ip) 
![image](https://user-images.githubusercontent.com/29251855/142020896-31a79dfd-2792-4589-8f7d-2c0b0d0ed7e3.png)
![image](https://user-images.githubusercontent.com/29251855/142020979-b586fd91-7b7a-4402-8b68-0a7c40ae1c1c.png)
2. Rancher: 3 node in provisioning (Harvester: 3 vm fully running with ip)
![image](https://user-images.githubusercontent.com/29251855/142021944-d7bd38a2-9703-4a88-8997-6741d79eee64.png)
![image](https://user-images.githubusercontent.com/29251855/142021906-4c1f7281-2a26-46b6-86a1-2027135f3692.png)
3. Rancher: 1 node in provisioning (Harvester: 1 vm is creating) 
![image](https://user-images.githubusercontent.com/29251855/142022593-047f49cb-c0f3-472d-9188-2adc5c7d5ab9.png)
![image](https://user-images.githubusercontent.com/29251855/142022675-0c28940c-05dc-4a09-a614-ad0df47f88fd.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine (RackD8 ClusterA)
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. Create nodes harvester
2. Prepare rancher 2.6.2 and import harvester
3. Create 3 nodes RKE2 cluster on Harvester through node driver with Rancher
4. Each node provide (8 core cpu and 16G memory)
5. According to above scenario to remove rke2 cluster while in provisioning state
6. Check rke2 cluster can be removed in rancher
7. Check rke virtual machine can be in harvester

### Additional Context
Some edge scenario like power off machine or network disconnected may need to monitor the remove behavior
