### ISSUE TITLE
[BUG] When VM is off it shows VMI status

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1313]
**Describe the bug**

When a VM is off it shows a status `VMI does not exist`.
**To Reproduce**
1. Create a VM
2. Turn it on
3. Turn it off
4. Check status
**Expected behavior**

It should not have a status since the off status is already shown to the left. 
**Support bundle**

[supportbundle_5e8c08b6-5b6d-46c1-9ebc-612e9547f365_2021-09-28T20-15-16Z.zip](https://github.com/harvester/harvester/files/7247025/supportbundle_5e8c08b6-5b6d-46c1-9ebc-612e9547f365_2021-09-28T20-15-16Z.zip)

**Environment:**
 - Harvester ISO version: master-f38adc70-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
![Greenshot 2021-09-28 13 02 34](https://user-images.githubusercontent.com/83787952/135159267-a9e10b39-ec36-4326-b6b7-a204fb2f3969.png)

**Comment by guangbochen** [comment]
@WuJun2016 when the VM is off, don't need to show any particular VM/VMI/pod related messages

**Comment by gitlawr** [comment]
Verified in master-8542e305-head
No VMI status is shown when the VM is off.
![image](https://user-images.githubusercontent.com/5697937/136645523-72c58602-c1a2-4284-aa7a-5b524e38cc29.png)
