### ISSUE TITLE
[BUG] Server temporarily lost connection after enabled VLAN

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1314]
**Describe the bug**
Server temporarily lost connection after enabled VLAN

**To Reproduce**
1. Install on nodes
2. Use the same nic as the mgmt network to enable VLAN networking
    * notice the nics on the third node has different name compare to the other two 
3. Access the UI after a couple of seconds.
4. Trying import an image from internet.

**Expected behavior**
There shouldn't be service interruption.

**Support bundle**
[supportbundle_25cb5754-a449-4518-a982-dfe27ac62d1f_2021-09-28T20-29-12Z.zip](https://github.com/harvester/harvester/files/7247082/supportbundle_25cb5754-a449-4518-a982-dfe27ac62d1f_2021-09-28T20-29-12Z.zip)

**Environment:**
 - Harvester ISO version: Harvester master 09/28/2021
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R630

**Additional context**

**Comment by yasker** [comment]
Hmm, it might due to the promotion though.

**Comment by guangbochen** [comment]
We should use the `harvester-mgmt` bond instead of the NIC name as it has already set its master to the bond NIC, as an enhancement this will be addressed via #1273.
