### ISSUE TITLE
[FEATURE] Fully support configuration of bond options

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1324]
As an admin user i want to be able to fully configure the typical Linux bond interface options, such that i can optimize performance and stability of Harvester networking.

But currently the only configurable option is the bonding policy (ie. `mode`):

```
      bond_options:
        mode: balance-rr
```

The available Linux bonding interface options are documented here: https://www.kernel.org/doc/Documentation/networking/bonding.txt

**Proposal**

Change the type of `bond_options` field to a list, allowing the user to pass arbitrary `option-name=option-value` pairs to specify any bond option. E.g:

```
      bond_options:
        - mode=balance-rr
        - fail_over_mac=1
        - resend_igmp=100
```

Alternatively, `bond_options` struct should be extended to support setting at least the following options in addition to `mode`:

```
- lacp_rate
- updelay
- miimon
- xmit_hash_policy
```

**Comment by yasker** [comment]
Make sure we will correct the typo as stated in https://github.com/harvester/harvester/issues/1323

**Comment by johnliu55tw** [comment]
Maybe we should use a map instead of a list here?
```
      bond_options:
        mode: balance-rr
        fail_over_mac: 1
        resend_igmp: 100
```

**Comment by guangbochen** [comment]
Yep, it should be a map instead of a list.

**Comment by yasker** [comment]
@janeczku Can you help to verify the fix?

**Comment by futuretea** [comment]
validated on v0.3.0-rc2
