### ISSUE TITLE
[BUG] Error when re-adding imported harvester cluster to Rancher

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1326]
**Describe the bug**

When you re-add harvester to rancher virtualization after removing it you get an error provisioning RKE2 cluster
**To Reproduce**
1. Import Harvester via virtualization management
2. Check that dropdowns populate when starting to provision RKE2 cluster
3. Delete Harvester cluster from virtualization management
4. Import Harvester cluster again
5. Try to provision RKE2 cluster
**Expected behavior**

You should get the dropdowns again and you shouldn't get an error
**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0-rc1
 - Rancher version: 2.6.1-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant

**Additional context**
I attached screenshots and the console error you get on the web page.
![Screenshot from 2021-09-29 11-02-41](https://user-images.githubusercontent.com/83787952/135324871-4d8b7e1a-0a70-4a80-ad13-3ba8f73e1afa.png)
![Screenshot from 2021-09-29 11-02-55](https://user-images.githubusercontent.com/83787952/135324872-fffa543b-6474-4a44-a26a-dbbcfc62fd7c.png)
![Screenshot from 2021-09-29 11-03-07](https://user-images.githubusercontent.com/83787952/135324873-b342e641-4eba-47ae-88e7-fce11baae35c.png)
![Screenshot from 2021-09-29 11-04-03](https://user-images.githubusercontent.com/83787952/135324877-591c7a63-f9b1-43e6-9d3e-b7482fb965c7.png)
![Screenshot from 2021-09-29 11-04-15](https://user-images.githubusercontent.com/83787952/135324879-be3de2de-ab62-431f-859e-eb6bdd133ed6.png)
![Screenshot from 2021-09-29 11-04-24](https://user-images.githubusercontent.com/83787952/135324880-1d0168c4-554a-484c-9e80-3eb609063bc2.png)

**Comment by yasker** [comment]
@noahgildersleeve are you using the cloud credential from the previous cluster? the cluster name will change.

**Comment by noahgildersleeve** [comment]
I don't think so, but I'll check.

**Comment by shangma** [comment]
@noahgildersleeve  I can reproduce this issue easily 
![image](https://user-images.githubusercontent.com/2396545/136289868-744e67b3-4ea5-42dd-880c-b835b7983902.png)

but this doesn't feels like a bug and the way to solve it is always to create a new cloud credential when we try to create a new cluster, see the image below. 
![image](https://user-images.githubusercontent.com/2396545/136289381-30f61963-d046-4ca5-b67e-f772865a37f4.png)

From the configuration of a given credential you can see that it is tied to a specific cluster, see the image below:
![image](https://user-images.githubusercontent.com/2396545/136289579-2c9f2dd8-0747-4d12-8598-9965733a39f1.png)

So if we try to create a new cluster with an existing cloud credential and the old cluster created with this old credential has been deleted, this error will appear. Maybe we should also remove a credential when we are deleting the cluster. @yasker

**Comment by yasker** [comment]
@shangma This behavior is expected. Feel free to close the issue.

**Comment by shangma** [comment]
Sure @yasker
