### ISSUE TITLE
[FEATURE] Clarify in the installer that bonded nic is not required

### ISSUE THREAD

**Issue by modzilla99** [harvester/harvester#1327]
Hey there,

I'd like to try harvester in a VM with nesting first, but am unable to due to the fact that I am not able to select a networking mode without any kind of bond. Or can linux bridges handle that as well as I don't really want to get into ovs just to try it out.
Thanks!

**Comment by yasker** [comment]
@modzilla99 you don't need to have a pair of nics to create mgmt interface. just choose your single nic and the default bonded mechanism is fine.

**Comment by yasker** [comment]
We need to highlight in the installer that we don't require a bonded nic for the network installation.

**Comment by modzilla99** [comment]
Sorry, was a little busy the last days. Yes as you said, it totally works that way!

Issue could be closed! :)

**Comment by yasker** [comment]
@modzilla99 nice to hear that! we'd like to keep the issue open to track the fix for the prompt message, to avoid confusion like yours in the future.

**Comment by guangbochen** [comment]
close in favor of the master-head ISO build, a proper message is displayed of bond NIC is not necessarily required.
![image](https://user-images.githubusercontent.com/4569037/136648259-830d9bfa-8dad-466d-bb0d-a0b73a0199dd.png)
