### ISSUE TITLE
[FEATURE] Shell access on ISO image

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1329]
**Is your feature request related to a problem? Please describe.**

Sometimes you might need to debug stuff around the installation, like checking network interfaces, hard drives etc.
Therefore it would be good if a login to the shell was provided

**Describe the solution you'd like**

Simplest solution would be that a logged in shell is ready at tty2 or so,
Another solution would be to print the login details in the MOTD
Another solution would be like the installed harvester says, "press F12 for ..."

**Describe alternatives you've considered**

**Additional context**

**Comment by yasker** [comment]
The username/password for the iso is `rancher/rancher`.

**Comment by guangbochen** [comment]
close in favor of https://docs.harvesterhci.io/v0.3/troubleshooting/installation/#installation
