### ISSUE TITLE
[FEATURE] Enhance the import experience to Rancher

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1330]
Currently user need to log into a Harvester physical node to run `kubectl` to import the Harvester cluster to a Rancher cluster.

We should allow that in the UI. Also, we need to enforce that one Harvester cluster can only be managed by one Rancher.

**Comment by jnfinitym** [comment]
I also noticed the binding script in Rancher 2.6.1 seems to look for k3s.yaml instead of rke2.yaml which is created in the installation of Harvester 0.3; copying `/etc/rancher/rke2/rke2.yaml` to `/etc/rancher/k3s/k3s.yaml` allowed me to add default as admin-role and subsequently join the Rancher. Should I file this in a dedicated issue or is this just part of this one?

**Comment by yasker** [comment]
@jnfinitym can you elaborate? Which binding script you're talking about? Might be another issue.

**Comment by jnfinitym** [comment]
I will file a seperate issue then, so I have mroe space to describe it - I am not home right now, so I will try it this weekend, so I can add the exact error messages I got and what exactly I did to get around them; I am specifically talking about importing Harvester to a Rancher instance, but it looks to be easily resolvable, but I am thinking it may actually be a Rancher Problem and not a Harvester Problem… My workaround was on the Harvester side though

**Comment by jnfinitym** [comment]
Weird, today I installed Harvester again from the same USB Stick and used the same version of Rancher deployed in the same way (in a VM on docker) and didn’t get the same issue!? - can’t reproduce it anymore, so I guess it was just a fluke.

**Comment by guangbochen** [comment]
Refer from https://github.com/harvester/harvester/issues/1437

**Expected:**

that explain how to import a Harvester cluster. E.g. the specific steps to be able to run the "kubectl" command in harvester.

**Actual:**

user is shown generic instructions to run the command on "an existing Kubernetes cluster running a supported Kubernetes version"


<img width="841" alt="Screenshot 2021-10-15 at 12 56 32" src="https://user-images.githubusercontent.com/3813921/137477163-0ef47d87-7965-4c3b-9dd6-9b2624231345.png">

**Comment by gitlawr** [comment]
Proposal for the import UX:
1. In Rancher UI, we show the instructions for importing Harvester using Harvester UI.
![image](https://user-images.githubusercontent.com/5697937/139803392-03c644a2-ffb9-4d29-88a4-6bc2abddcb07.png)

2. In Harvester settings, add a `cluster-registration-url` settings. Users import the Harvester cluster by clicking the `Import to Rancher` button and inputing the registration URL.
![image](https://user-images.githubusercontent.com/5697937/139802433-c667ced7-f66d-473a-aa2f-956fc4c2307e.png)

3. Under the hood, Harvester settings controller applies the manifests for the import.

**Comment by guangbochen** [comment]
LGTM

**Comment by guangbochen** [comment]
**To Test:** (and please sync to close https://github.com/rancher/dashboard/issues/4531 if passes)
1. Spin up the Rancher v2.6.3-rc1 and In Rancher UI, we show the instructions for importing Harvester using Harvester UI.
![image](https://user-images.githubusercontent.com/5697937/139803392-03c644a2-ffb9-4d29-88a4-6bc2abddcb07.png)

2. In Harvester settings, add a `cluster-registration-url` settings. Users import the Harvester cluster by clicking the `Import to Rancher` button and inputing the registration URL.
![image](https://user-images.githubusercontent.com/5697937/139802433-c667ced7-f66d-473a-aa2f-956fc4c2307e.png)

3. Under the hood, the Harvester settings controller applies the manifests for the import and the cluster will be visible in the Rancher UI.

please also close the issue of https://github.com/rancher/dashboard/issues/4531 if the validation passes, thanks.

**Comment by TachunLin** [comment]
@gitlawr , @n313893254 
Verified **not fixed** on master-81141c98-head with latest rancher `v2.6-head`. Move it to implement pipeline. 
Please check whether the feature and UI have merged to the latest master release. 

On Rancher v2.6-head, we can see the instructions for importing Harvester under registration tab 
![image](https://user-images.githubusercontent.com/29251855/142975079-33aa0e90-1936-4341-b567-b048c5a42deb.png)

While we can't find the `cluster-registration-url ` configuration in harvester settings page
![image](https://user-images.githubusercontent.com/29251855/142975242-5eea8afe-c606-4921-bb9e-d6544bb795fd.png)

**Comment by n313893254** [comment]
@TachunLin  My bad. As the PR is merged by rancher/dashboard, we should validate `cluster-registration-url ` after  harvester/dashboard rebase rancher/dashboard.

**Comment by WuJun2016** [comment]
rebase, Done.

**Comment by TachunLin** [comment]
Verified **fixed** on master-b7e562d3-head with Rancher v2.6.3-rc1 .Close this issue.

### Result
User can input registration url from rancher into harvester settings then import harvester in rancher dashboard

![image](https://user-images.githubusercontent.com/29251855/143016335-e042b5a6-747f-4273-99d1-ef7893d3d70a.png)

![image](https://user-images.githubusercontent.com/29251855/143016378-6cb739ac-37fb-44c3-855b-65b0042cc8cf.png)


### Test Information
* Test Environment: 1 nodes harvester on local kvm/qemu
* Harvester version: master-b7e562d3-head
* Rancher version: v2.6.3-rc1

### Environment Preparation
1. Install harvester v2.6.3-rc1 in docker command
2. Update the ui-dashboard-index and ui-offline-preferred in rancher global settings



### Verify Steps

1. Environment preparation as above steps
2. Access virtualization management page in rancher
3. Press ctrl+R to reload page
4. Import existing harvester
5. Copy the registration url 
![image](https://user-images.githubusercontent.com/29251855/143016093-e849e5f0-c6b5-4950-9d83-7b7fd1a95e3d.png)
6. Access harvester dashboard settings
7. Edit the `cluster-registration-url`
![image](https://user-images.githubusercontent.com/29251855/143016190-f6843398-bbb9-497e-80f7-68be88daf81e.png)
8. Paste the registration url and save
![image](https://user-images.githubusercontent.com/29251855/143016248-1593af54-ba8b-4bcd-bed2-efad20b1a057.png)

![image](https://user-images.githubusercontent.com/29251855/143016335-e042b5a6-747f-4273-99d1-ef7893d3d70a.png)

9. Back to rancher dashboard and wait for import process
![image](https://user-images.githubusercontent.com/29251855/143016378-6cb739ac-37fb-44c3-855b-65b0042cc8cf.png)

10. Access harvester from rancher virtualization management page
