### ISSUE TITLE
[BUG] Volumes fail with Scheduling Failure after evicting disc on multi-disc node

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1334]
Harvester v0.3.0-rc1

**To Reproduce**

1. Create 3-node Harvester cluster
2. Launch a few VMs
3. Add one or more additional discs to at least one of the nodes and ensure the disk is schedulable
4. On  a multi-disc node, disable scheduling for the initial/system disk and set `Eviction Requested` to `TRUE`

**Expected behaviour**

Replicas are moved from the evicted disc to another schedulable disc on the same node

**Actual behaviour**

All volumes enter failure state "Scheduling Failure" indefinitely.

The issue is only resolved after either adding a 4th node to Harvester cluster or disabling `Eviction Requested`.

**Additional Information**

This seems to be related to the hard anti-affinity scheduling (enabled by default). The algorithm probably needs to be updated to allow the moving of replicas between discs on the same node (which doesn't violate anti-affinity).

**Comment by weihanglo** [comment]
Hi, there are a few similar feature requests in Longhorn: longhorn/longhorn#3076, longhorn/longhorn#1400.

There is also a [temporary hack](https://github.com/longhorn/longhorn/issues/1400#issuecomment-633723863) to manually schedule those volumes (though the steps need an update with new `Replica eviction` feature).

Seems that the feature is arranged in Longhorn v1.3.0 milestone, we might not able to make it in Harvester v0.3.0 release. 😞

**Comment by weihanglo** [comment]
The logic of adding/removing disk from Longhorn is naive that doesn't take already scheduled volumes into account. Would need a way to avoid this risk. There is one solution currently in my mind:

1. Re-implement a part of disk eviction check logic of Longhorn in Harvester's node disk manager. Mainly make the disk unscheduleable and eviction-requested then wait all volumes on the disk being evicted. After that, the disk on Harvester is safe to remove.
2.  `blockdevice.status.state` would have new states to handle disk evictions, such like `Provisioned` and `Evicting`.
2. Dashboard UI also needs updates to reflect these changes.

**Comment by yasker** [comment]
We need to move this issue to v1.0.0 due to It's caused by a Longhorn hard anti-affinity limitation. Longhorn will fix it in the v1.2.2, which will align with Harvester v1.0.0 release.

**Comment by weihanglo** [comment]
For my perspective, longhorn/longhorn#3076 is more relevant to this issue as its more general. That is, when a user evicts a disk, they does not need to know where the volume would be scheduled.

**Comment by guangbochen** [comment]
should be addressed via https://github.com/longhorn/longhorn/issues/3257 with LH bump to `v1.2.3-rc1`, can we please help to revalidate it, thanks.

**Comment by weihanglo** [comment]
Confirmed that in Harvester, we can reschedule volumes between disk on the same node. The VM is still running after the volume reschedule.

![image](https://user-images.githubusercontent.com/14314532/144022011-95b619b5-9aa5-470f-9c82-af25e2a674e4.png)

Though, I won't see this issue resolved. Tell user to access Longhorn dashboard is not friendly. At this moment, the disk removal on Harvester dashboard is really naive, it removes the disk from node directly without taking reschedule into account. We should implement similar user flow in node-disk-mananger to wait the reschedule finished.

**Comment by weihanglo** [comment]
To enhance the UX of disk removal and prevent accidental data loss, I propose adding new status `status.provisionPhase` on blockdevice CRD.

The new status indicates the provision phase of the device with a Longhorn node. It's an enum type with three variants:

- `Provisioned`: device is provisioned onto a Longhorn node as a disk. Longhorn replicas should be safe to schedule on it.
- `Unprovisioning`: the related disk of the device is under eviction from a Longhorn node. Once all replicas get evicted, he related disk would be removed from the node.
- `Available`: The device is healthy and can be provision as a disk to the longhorn node.

The flow is simple:

1. User provisions a device onto a node by specifying `blockdevice.spec.fileSystem.provisioned = true`
2. The disk is added to Longhorn node. `blockdevice.status.provisionPhase` becomes `provisioned`. Replicas can be schedules on it.
3. User unprovisions the device/disk from the node by specifying `blockdevice.spec.fileSystem.provisioned = false`
4. NDM detects that a device/disk need to unprovision. To prevent data loss, NDM sets `evictionRequested = true` and `allowScheduling = false` on the relevant disk on the longhorn node for rescheduling replicas to other disks. Meanwhile, the `blockdevice.status.provisionPhase` becomes `Unprovisioning`.
5. Once `scheduledReplica` of the disk is empty, NDM then safely removes the disk from the longhorn node. `blockdevice.status.provisionPhase` is then back to `available`.

Any thought?

cc @guangbochen @bk201

**Comment by guangbochen** [comment]
sounds good to me, loop @gitlawr

**Comment by weihanglo** [comment]
### Test scenario:

1. Create a 3-node cluster.
2. Attach extra disks on a node in page **Hosts** > **Disks** > **Edit Config**
3. Create some VMs on that node (Use **Node Scheduling** to specify node)
4. Make sure some volumes are schedules onto the node. You can check it in page **Hosts** > **Disks**
5. Remove some of the extra disks. In the meanwhile, your VMs should continue working.
6. `kubectl -n longhorn-system get lhn` and check if the extra disks on the longhorn node are completely removed by the field `spec.disks.<your-disk-guid>`. (Note that this part will eventually be displayed in Harvester Dashboard. Just jot it down here and wait for UI getting this)

**Comment by guangbochen** [comment]
@weihanglo seems we need a chart bump since the CRD manifest is changed

**Comment by noahgildersleeve** [comment]
Tested in master-5e8d9764-head.
## Test Steps
1. Created 3 node Harvester setup with ipxe example in KVM/libvirt
2. Added formatted disk to node0 VM
3. Created three VMs on node0
4. Created large files on three VMs to see where they were located with `dd if=/dev/urandom of=file1.txt count=5192 bs=1M`
5. Checked Longhorn to be sure that some VMs were on new disk
6. Deleted disk from Harvester
7. Checked Longhorn to be sure that disk was marked for eviction
8. Verified that VMs were still available while evicting replicas by running commands from serial console/SSH
9. Verified that disk was removed from Longhorn and VMS were still up.
