### ISSUE TITLE
[FEATURE] Support collection of crash dumps

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1335]
To facilitate troubleshooting crashing of nodes during operation there should be a Harvester configuration option to collect crash dumps. This could include enabling `kdump` service on the OS level as well as writing process level dumps (e.g. Go panics) in a common location.

**Comment by janeczku** [comment]
Maybe also log panics occurring in critical Harvester components to `/dev/kmsg`

**Comment by janeczku** [comment]
It should also be possible to setup kernel with access to a serial port to facilitate debugging (`console=ttyS0`)

**Comment by janeczku** [comment]
https://www.suse.com/support/kb/doc/?id=000016171

**Comment by guangbochen** [comment]
Verified using the `master-9f917060-head` version - `passed`
![image](https://user-images.githubusercontent.com/4569037/136684887-3e14d060-b4d7-4169-a409-f17622f4c0dd.png)
- [x] There is a new debug boot grub option
- [x] Normal boot
  - [x] No `crashkernel` parameter
  - [x] kdump.service is disabled
  - [x] Triggered a crash then it rebooted in 10 seconds without any dump in `/var/crash`
- [x] Debug boot
  - [x] Got `crashkernel` parameter
  - [x] kdump.service is active
  - [x] Triggered a crash then the dump can be seen in `/var/crash`
