### ISSUE TITLE
[BUG] Cannot restore VM after changing the Backup Target

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1338]
**Describe the bug**
Restoring from backup results in error after changing the Backup Target.

**To Reproduce**
1. Set up a backup target to S3 bucket `bucket1`
2. Create a VM, then create a backup of it
3. Verify the backup is ready
4. Change the backup target to another S3 bucket: `bucket2`
5. Verify the backup still exists
6. "Restore New" from the backup
7. The new VM stuck at "Scheduling" status with error: 
    ```
    0/3 nodes are available: 3 pod has unbound immediate PersistentVolumeClaims.
    ```

**Expected behavior**
I think there are several viable behaviors:
1. Backup/Restore should work just fine after changing the Backup Target.
2. Prohibit users from changing the Backup Target if they already created several backups. 
3. Warn users that all the backups would be removed if they changed the Backup Target, and we removed all the backups.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
- **Error:**
![image](https://user-images.githubusercontent.com/5047724/135433258-57bea57d-c665-4857-8016-dd22c2913b3d.png)

- Everything went back to normal after I switched back to the original Backup Target (`bucket1`).

**Comment by yasker** [comment]
Change the backup target should refresh all the backups (not deleting from the backup target). Since the backup doesn't exist in the new backup target, we definitely shouldn't show them.

**Comment by FrankYang0529** [comment]
I have checked that longhorn delete all backups when we change the backup target, so we should also delete VM backup too when the backup target changed.

**Comment by yasker** [comment]
@FrankYang0529 Can you confirm Longhorn only deletes the Backup CR object, not the real backup in the backup target?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Can you confirm Longhorn only deletes the Backup CR object, not the real backup in the backup target?

Yes, Longhorn only deletes Backup CR objects. I still can see backups in my S3 bucket.

**Comment by guangbochen** [comment]
One thing I have concerned about here is whether we should remove all the existing VMbackup CRs automatically when the user modified the backup target, I prefer to leave it for the users to manage those VM backups for the following reasons:
- users may change the backup target back and forth for validation or testing purposes
- we can disable users from using those VM backups if the current backup target is not equal to the stored backup target(e.g via webhook validation)

**Comment by guangbochen** [comment]
verified using the master-head version - `passed`
1. config the backup target with the NFS server
2. create a backup of the VM 
3. update the backup target to the S3 server e.g [minio](https://longhorn.io/docs/1.1.2/snapshots-and-backups/backup-and-restore/set-backup-target/)
![image](https://user-images.githubusercontent.com/4569037/136646048-fbf5582d-bef0-451e-9b89-837ede4b7b3f.png)
4. either restore a new VM or replacing the existing VM with the last backup, and a proper validation message is shown.
![image](https://user-images.githubusercontent.com/4569037/136646038-09ff7eb8-fad2-4b53-9347-16935b05bde5.png)
5. config the backup target to the previous config and both restore new VM or replace existing works.
