### ISSUE TITLE
[BUG] Backup-target failing for the harvester-ci-testing bucket

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1339]
**Describe the bug**
The backup-target in settings is failing when trying to use the aws account credentials provided for harvester-ci-testing bucket. It fails with error
backup-target Modified
Custom back target to store VM backups.
{
  "type": "s3",
  "endpoint": "",
  "accessKeyId": "",
  "secretAccessKey": "",
  "bucketName": "harvester-ci-testing",
  "bucketRegion": "us-east-2",
  "cert": "",
  "virtualHostedStyle": false
}
operation error S3: ListBuckets, https response error StatusCode: 403, RequestID: E0NEZH6VAXNEEWCT, HostID: lePh+/9xeaHXfS6WLYF6JHqfmk1NXfdd3BJDLZXLSBBxgqkkraaaYMOBwQF3SVXc7INtUJLY2BybQzLIj8bl+g==, api error AccessDenied: Access Denied

I performed the following steps on Longhorn UI and backup/restore seems to work there fine.

- Created aws-secret on harvester-node-0 using kubectl command

- Did settings on longhorn UI
      Backup Target - s3://harvester-ci-testing@us-east-2/
      Backup Target Credential Secret- aws-secret

- Created a backup and restored and it is successful

**To Reproduce**
Try to modify the backup-target in settings with aws credentials of harvester-ci-testing bucket. 

**Expected behavior**
backup-target should be created without any errors

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe vagrant harvester setup

**Additional context**

**Comment by yasker** [comment]
It seems Harvester is performing a connection check that requires additional permission for S3 than necessary.

**Comment by w13915984028** [comment]
The code 
` validateS3BackupTarget ` in `backupTaget.go`
tries to verify if the bucket is existing,
as per S3 API, HeadObject (longhorn uses) or HeadBucket is the proper API to use, it is high efficiency, and will not cause potential "AccessDenied",  harvester uses ListBucket.

HeadObject is a general API to check if a single object exists.
----
AWS has 3 APIs related here:
```
// * If you have the
// s3:ListBucket permission on the bucket, Amazon S3 returns an HTTP status code
// 404 ("no such key") error.
//
// * If you don’t have the s3:ListBucket permission,
// Amazon S3 returns an HTTP status code 403 ("access denied") error.

The HEAD action retrieves metadata from an object without returning the object itself. This action is useful if you're only interested in an object's metadata. To use HEAD, you must have READ access to the object.

A HEAD request has the same options as a GET action on an object. The response is identical to the GET response except that there is no response body. Because of this, if the HEAD request generates an error, it returns a generic 404 Not Found or 403 Forbidden code. It is not possible to retrieve the exact exception beyond these error codes.
func (c *Client) HeadObject(ctx context.Context, params *HeadObjectInput, optFns ...func(*Options)) (*HeadObjectOutput, error) 


Returns a list of all buckets owned by the authenticated sender of the request.
func (c *Client) ListBuckets(ctx context.Context, params *ListBucketsInput, optFns ...func(*Options)) (*ListBucketsOutput, error) 


// This action is useful to determine if a bucket exists and you have permission to
// access it. The action returns a 200 OK if the bucket exists and you have
// permission to access it. If the bucket does not exist or you do not have
// permission to access it, the HEAD request returns a generic 404 Not Found or 403
func (c *Client) HeadBucket(ctx context.Context, params *HeadBucketInput, optFns ...func(*Options)) (*HeadBucketOutput, error) {



Harvester usage:
pkg/controller/master/backup/backupTaget.go:293:        output, err := client.ListBuckets(h.ctx, &s3.ListBucketsInput{})


Longhorn usage:
vendor/github.com/longhorn/backupstore/s3/s3_service.go:102:func (s *Service) HeadObject(key string) (*s3.HeadObjectOutput, error) {
vendor/github.com/longhorn/backupstore/s3/s3_service.go:108:    params := &s3.HeadObjectInput{
vendor/github.com/longhorn/backupstore/s3/s3_service.go:112:    resp, err := svc.HeadObject(params)
vendor/github.com/longhorn/backupstore/s3/s3.go:150:    head, err := s.service.HeadObject(path)
vendor/github.com/longhorn/backupstore/s3/s3.go:159:    head, err := s.service.HeadObject(path)

```

Harvester current code:
```
func (h *TargetHandler) validateS3BackupTarget(target *settings.BackupTarget) error {
  ...
        // create a s3 service client
        client := s3.NewFromConfig(cfg)
        output, err := client.ListBuckets(h.ctx, &s3.ListBucketsInput{})
..
        for _, b := range output.Buckets {
                if *b.Name == target.BucketName {
                        return nil
                }
        }
..
}
```

**Comment by w13915984028** [comment]
test with minio, it said: failed to load custom CA bundle PEM file.   which step is missing ?

https://longhorn.io/docs/1.1.2/snapshots-and-backups/backup-and-restore/set-backup-target/


![image](https://user-images.githubusercontent.com/31133476/141338510-eeac7c3e-4305-4a6d-b00e-0210799013ba.png)

**Comment by gitlawr** [comment]
@w13915984028 The `cert` doesn't look like a PEM certificate file starting with `-----BEGIN CERTIFICATE-----`. Is it base64 encrypted?

**Comment by w13915984028** [comment]
With the used s3 harvester-ci-testing credentials, backup target setting is successful in my local harvester.

**Comment by w13915984028** [comment]
reproduced now

the "endpoint" field should be empty, then, the same error occurs:
-----

`operation error S3: ListBuckets, https response error StatusCode: 403`, RequestID: MBWD5GVK5MS2NMY0, HostID: o7HZ6AXjotKv01pher5AByzwpwcpJP3Rpz8R46JQF56KR+WKoPrseJrYS5OykGSMETuqCXTBDiw=, api error AccessDenied: Access Denied

**Comment by guangbochen** [comment]
should be resolved in the latest `v1.0.0-rc1` release of supporting both s3 and s3 compatible servers like MiniO.

**Comment by w13915984028** [comment]
After merge of #1447, both s3 and minio are working correctly. 

#1447 refactor the validation of backup target, it is forwarded and delegated to longhorn and returns unified error message.

**Comment by lanfon72** [comment]
Verified it works as #1547 described.
As the Minio is compatible with AWS S3, it's testd on MInio environment rather than S3.


Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **v1.0.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Setup Minio
    a. then follow the [instruction](https://objectivefs.com/howto/how-to-restrict-s3-bucket-policy-to-only-one-aws-s3-bucket) to create a `single-bucket-user`.
    b. Create specific bucket for the user
    c. Create other buckets
5. setup `backup-target` with the **single-bucket-user** permission
    a. When assign the dedicated bucket (for the user), connection should success.
    b. When assign other buckets, connection should failed with **AccessDenied** error message

**Comment by yasker** [comment]
nvm, as long as the Minio permission setup can reproduce the original issue, we should be fine here.
