### ISSUE TITLE
[FEATURE] ucode-intel/amd missing

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1341]
**Is your feature request related to a problem? Please describe.**

The package ucode-intel/amd is missing, this might be good to include for mitigations for spectre and other bugs

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
The ucodes should be included in the latest master ISO.

Archwiki provides ways to verify if microcodes are applied.
https://wiki.archlinux.org/title/microcode#Verifying_that_microcode_got_updated_on_boot

**Comment by Jellyfrog** [comment]
This has been resolved
