### ISSUE TITLE
[FEATURE] Improve Harvester kernel debug-ability.

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1343]
- [x] In case we have any kernel-related issues, a serial port output is a must for debugging.
- [x] Other best practices the kernel team suggested, e.g. including kdump by default (if there is no performance penalty)

**Comment by yasker** [comment]
Some debug methods we can put in our documents. https://github.com/rancher-sandbox/cOS-toolkit/issues/751#issuecomment-934112598

**Comment by bk201** [comment]
Crash dump feature is tracked in https://github.com/harvester/harvester/issues/1335

**Comment by bk201** [comment]
@yasker I'm not sure if we should hard-code a tty console parameter (e.g., `console=ttyS0`) because:
- Users' machine might have a different usable serial port, e.g., ttyS1 or ttyUSB0
- The buadrate of a serial console needs to be identical both on server and serial port client.

Currently, the user needs to edit the grub menu and append the console=ttyS0 parameter to output kernel message to a serial console.

**Comment by yasker** [comment]
@bk201 Your concern is valid. My concern is user shouldn't have to specify it every time when troubleshooting. And they might have something connected to the serial port for the entire lifecycle of the server.

There are two things we need to address here:
1. How to allow users to configure the serial port output permentately in the kernel cmd line? Can we do that via the installer?
2. How to allow users to configure the serial port only for a time being? I guess [RW partition](https://rancher-sandbox.github.io/cos-toolkit-docs/docs/reference/troubleshooting/#kernel-parameters) should help.

**Comment by janeczku** [comment]
It would be good to have an installation option where user can specify the serial console device name.

**Comment by alexdepalex** [comment]
There should be an option where enabling the serial console or the crash kernel is made persistent across reboots. Currently, the latter can only be enabled by selecting the "debug" boot option in grub while booting. This doesn't scale and with systems that have multiples of 100GB of memory, losing 250MB of memory to the crash kernel is peanuts.

**Comment by bk201** [comment]
> There should be an option where enabling the serial console or the crash kernel is made persistent across reboots. Currently, the latter can only be enabled by selecting the "debug" boot option in grub while booting. This doesn't scale and with systems that have multiples of 100GB of memory, losing 250MB of memory to the crash kernel is peanuts.

A temporary workaround to set second entry persistently across reboots: https://docs.harvesterhci.io/v0.3/troubleshooting/os/#how-to-change-the-default-grub-boot-menu-entry

**Comment by guangbochen** [comment]
close in favor of https://docs.harvesterhci.io/v0.3/troubleshooting/os/#how-to-debug-a-system-crash-or-hang
