### ISSUE TITLE
[BUG] VM(CentOS 8) with "Install guest agent" enabled cannot show correct information from the guest agent

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1344]
**Describe the bug**
GUI shows "Guest agent required" for both _Operating System_ and _Kernel Release_ fields, even with "Install guest agent" selected while creating the VM. 
![image](https://user-images.githubusercontent.com/5047724/135799807-c8ba85f7-0ddd-44b4-a5dd-986b0eadc929.png)
![image](https://user-images.githubusercontent.com/5047724/135799834-73ee635f-10ac-4436-bd0d-3570df97e40d.png)

**Occasionally they appeared just fine, with both fields show the correct information:**
![image](https://user-images.githubusercontent.com/5047724/135801203-a19e0116-9c97-4b31-bd77-4b09182fb38d.png)

**To Reproduce**
1. Create an image with URL https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2
2. Create a VM using the image with "Install guest agent" selected ("Advanced Options")
3. Check the VM detail and see both _Operating System_ and _Kernel Release_ show "Guest agent required"

**Expected behavior**
Both fields should show the correct information.

**Support bundle**

**Environment:**
 - Harvester ISO version: 0.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
If "Install guest agent" is **not** selected, those two fields always show the correct information because the image has a guest agent pre-installed. Its release is different from the VM with "Install guest agent" selected:
  ```
  $ yum info installed qemu-guest-agent | grep Release
  ```
- With "Install guest agent": `48.module_el8.4.0+885+5e18b468.3`
- Pre-installed: `48.module_el8.4.0+783+f8734d30`

**Comment by futuretea** [comment]
@guangbochen  maybe we need to do a enhancement for image:  add metadata to image.
for example , user add a metadata "contain qemu-guest-agent" to image, if use this image to create virtual machines , ui will not select the `install qemu guest agent` by default.

other possible metadata:
1. os
2. required disk size

**Comment by futuretea** [comment]
This issue seems to have been solved in favor of https://github.com/harvester/harvester/issues/1553#issuecomment-1048491145

![image](https://user-images.githubusercontent.com/15064560/156324111-0f61573a-4efc-44a9-969e-779cb75caa22.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/156724543-820a86c8-e289-4962-bcbd-60f84a79c839.png)
![image](https://user-images.githubusercontent.com/5169694/156724562-b080f6af-b91e-4601-86ed-0835d4d25b2b.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.0 master-dba85940-head**
* **ui-source** Option: **Auto**

### Verify Steps:
Same as **Steps to reproduce** in https://github.com/harvester/harvester/issues/1344#issue-1014773209
