### ISSUE TITLE
[BUG] NTP connection check unreailable 

### ISSUE THREAD

**Issue by Jellyfrog** [harvester/harvester#1345]
**Describe the bug**

Something is wrong with the NTP connection check, sometimes it works, sometimes it doesn't, and it seems to be rather 50/50
However it does work when trying from the tty:

![Screenshot from 2021-10-04 10-36-49](https://user-images.githubusercontent.com/759887/135819932-7bf7614b-358e-476d-bab6-1205af559dd6.png)

![Screenshot from 2021-10-04 10-37-46](https://user-images.githubusercontent.com/759887/135819946-d52c9a79-e0ee-4d79-9ff2-6b05904d56e2.png)

**To Reproduce**
1. Try install harvester via ISO

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: Nightly from 2021-10-04
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Virtual

**Additional context**

**Comment by bgulla** [comment]
+1 reproduced

**Comment by FrankYang0529** [comment]
Hi @Jellyfrog, for [NTP validation](https://github.com/harvester/harvester-installer/blob/bce2a81adaf7a34e644cd46f902d31e0a349575c/pkg/console/util.go#L108-L115), we send a simple NTP request to check whether servers can work, so it depends on network quality.

@yasker, do you think we need to add a retry mechanism for NTP validation? We already [prolong the timeout](https://github.com/harvester/harvester-installer/commit/68c789d393ca09cbbd8c051de55a3be84a2018fd#diff-7585f2fd8ff9666817a029d282094ddc9ae07863f3af56712c47bda13d3b39b9) for it. I tried to add a retry mechanism, but @guangbochen thinks it may take long time on the NTP page.

**Comment by yasker** [comment]
Can we include multiple NTP servers by default? Will the system automatically check the next one if the first one doesn't work?

Also I suspect there is a race condition regarding the network configuration behind the scene. For fixing that we need to reproduce the issue first in the lab.

**Comment by FrankYang0529** [comment]
Yeah, we can give multiple NTP servers. Even if we don't give any NTP server, we still have default `FallbackNTPServers` in the system.
![Screenshot from 2021-10-05 22-32-58](https://user-images.githubusercontent.com/4927361/136044356-8b5c0a20-befc-4605-86af-b2e71d8dfc9a.png)

**Comment by yasker** [comment]
The fallback mechanism looks good at the moment. We probably don't have time to find the root cause in a couple of days before the code freeze. Move to v1.0.0.

**Comment by janeczku** [comment]
Still an issue on 0.3.0 even with the default `0.suse.pool.ntp.org`. 

The error occurs only on the first attempt. When going back to the previous installation step using ESC key and then saving the NTP configuration again then it succeeds. So it's likely a race condition with the network initialization.
<img width="353" alt="Screenshot 2021-10-12 at 16 59 24" src="https://user-images.githubusercontent.com/3813921/136982433-eef1fa57-acc6-4861-8d3d-fd569c6e0072.png">

**Comment by FrankYang0529** [comment]
NTP connection issue also happened in another golang NTP client https://github.com/beevik/ntp/issues/35. I will take advice from https://github.com/beevik/ntp/issues/35#issuecomment-751244523 to check all IP address which DNS server returns if there is an i/o timeout for the first probe. This way was also implemented in the [NTP project](https://github.com/ntp-project/ntp/blob/master-no-authorname/ntpdate/ntpdate.c#L1396) which was written in C.

I will also check users' input every time when users go back to the NTP setting page.

**Comment by TachunLin** [comment]
@FrankYang0529 
Verified fixed on master-d05a6cc7-head, close this issue. 

### Result
After many times and different condition trial, 
Using valid ntp server, there is no "failed to reach to NTP server" message happens

- [ O ] Use default ntp server 0.suse.pool.ntp.org 
         more than 20 times, through back and force to each end. 
         **Even encounter network latency, it will retry several times until it works**

- [ O ] Using local valid ntp server many times. 

- [ O ] Use invalid ntp server url , it will prompt connection error message 

- [ O ] Use empty ntp server url, it will proceed to the next setup steps

- [ O ] Launch ISO installer many times to try the ntp server detection 


### Test Information
* Test Environment: Local qemu kvm machines with one node
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. Launch harvester ISO installation process 
2. Proceed to input ntp server url step

**Comment by Jellyfrog** [comment]
@TachunLin 
This still fails when the server got a ipv4 and ipv6 answer.

```
$ host ntp.se
ntp.se has address 194.58.200.20
ntp.se has IPv6 address 2a01:3f7::1
```

![image](https://user-images.githubusercontent.com/759887/140947482-8b6431e6-e1fe-4c04-aefa-11ee34960874.png)

**Comment by FrankYang0529** [comment]
> @TachunLin This still fails when the server got a ipv4 and ipv6 answer.
> 
> ```
> $ host ntp.se
> ntp.se has address 194.58.200.20
> ntp.se has IPv6 address 2a01:3f7::1
> ```
> 
> ![image](https://user-images.githubusercontent.com/759887/140947482-8b6431e6-e1fe-4c04-aefa-11ee34960874.png)

Hi @Jellyfrog, thanks for the comment. We use [UDP for NTP validation](https://github.com/harvester/harvester-installer/blob/52c560d85c1b2d0a499c640695e5153ba5486c38/pkg/console/util.go#L116). Since UDP is not reliable, we update the mechanism from validating one IP address to [validating each IP address](https://github.com/harvester/harvester-installer/blob/52c560d85c1b2d0a499c640695e5153ba5486c38/pkg/console/util.go#L101) in domain lookup. `ntp.se` can only get 2 IP addresses, so validation may fail sometimes. We haven't added retry mechanism. For validation again, you can try to press Enter to the next page and press Esc to NTP setting page.

Even if validation is failed, we still write the input to `/etc/systemd/timesyncd.conf` after installation is finished. Also, even if the input is a wrong NTP domain, we still have the default `FallbackNTPServers` list in the system.

![image](https://user-images.githubusercontent.com/4927361/136044356-8b5c0a20-befc-4605-86af-b2e71d8dfc9a.png)

**Comment by Jellyfrog** [comment]
Hi, thanks for a quick and verbose answer.
This is not however what's wrong, its trying to validate the ipv6 address tho ive only setup a ipv4.
So it wouldn't matter how many times it would retry
