### ISSUE TITLE
[FEATURE] Move `download kubeconfig` icon

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1349]
`Download Kubeconfig` shouldn't be so obvious in the UI, since we don't encourage users to use the Harvester cluster as a normal Kubernetes cluster.

The only use case for kubeconfig is for debugging or importing as an external cluster to Rancher. The P1 use case with Rancher is via imported Harvester cluster, not via an external Harvester cluster via kubeconfig. So we shouldn't highlight the download kubeconfig function.

We should move the icon to somewhere else.

**Comment by lanfon72** [comment]
Close this as I verified `download KubeConfig` has been moved to **Support** page:
[New section for download kubeconfig]
![image](https://user-images.githubusercontent.com/5169694/137908874-cacfc38a-0642-4594-b3e5-4b6c82253aa5.png)
[removed from general views]
![image](https://user-images.githubusercontent.com/5169694/137908761-14895773-67c9-4346-b5fb-959e7a6ea9af.png)

Test Information
----
* Environment: **Bare mental DL360** 3 nodes
* Harvester Version: **master-ebfbf44a-head**
### Verify Steps:
- navigate to every pages to make sure *download kubeconfig* icon will not appear in header section
- navigate to *support* page to check **Download KubeConfig** is work normally

**Comment by lanfon72** [comment]
As the new UI not bundled into **master-ebfbf44a-head** yet, I will update the correct version with bundled one.
(this means, if you set the **ui-source**(from Advanced -> Settings) to `Bundled`, you can still see the KubeConfig Icon in header section)

**Comment by lanfon72** [comment]
verified **master-d05a6cc7-head** with `ui-source=Bundled`
