### ISSUE TITLE
[BUG] Nodes in maintenance mode are listed in Node Scheduling selection

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1350]
**Describe the bug**
When trying to create a VM in a specific node, nodes in maintenance mode are listed in the selection.

![maintenance mode](https://user-images.githubusercontent.com/4927361/135798107-47acda47-4f14-4ad1-b606-005bf14eb79d.png)

**To Reproduce**
1. Create a cluster (2 nodes).
2. Go to the Host page and enable maintenance mode for 1 node.
3. Go to the VM page, create a VM, and choose maintenance mode node in Node Scheduling.

**Expected behavior**
Nodes in maintenance mode should not be listed in Node Scheduling selection.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
https://github.com/harvester/harvester/issues/817

**Comment by guangbochen** [comment]
additionally, we should display the customized node name when it is specified on the host page.

**Comment by WuJun2016** [comment]
duplication: 
this issue:  https://github.com/harvester/harvester/issues/1014
display the customizd node name:   https://github.com/harvester/harvester/issues/1434

**Comment by WuJun2016** [comment]
closed

**Comment by lanfon72** [comment]
verified that Nodes will not appear in the list of scheduling VM on specific Node when they entered of `maintenance mode`. 


Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-04c5f438-head**
* **ui-source** Option: **External**
### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Login and Navigate to _Virtual Machines_
3. Create VM and Select `Run VM on specific node(s)...`
4. All _**Active**_ nodes should in the list
5. Navigate to _Host_ and pick node(s) to **Enable Maintenance Mode**
6. Make sure Node(s) state changed into _**Maintenance Mode**_
7. Repeat step 2 and 3
8. Picked Node(s) should not in the list
9. Revert picked Node(s) to back to state of _**Active**_
10. Repeat step 2 to 4
