### ISSUE TITLE
[BUG] advanced options `auth-max-ttl-minutes` not exists

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1352]
### Describe the bug
_Advanced_ test cases No.3 and No.4 require to test `auth-max-ttl-minutes`.

### To Reproduce
1. Log in as admin
2. Navigate to advanced settings
3. configure option `auth-token-max-ttl-minutes` not exists

### Expected behavior
Either able to configure `auth-max-ttl-minutes` or remove test cases

## Environment:
 - Harvester ISO version: **master-82506f55-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

**Comment by yasker** [comment]
Option removed. Need to update the test case.

**Comment by lanfon72** [comment]
close this as test cases has been updated.
