### ISSUE TITLE
[Question] How to set https proxy? 

### ISSUE THREAD

**Issue by yshashix** [harvester/harvester#1354]
While installting , i only get place to set HTTP proxy but not https proxy. Is it same place ?
I installed release 0.2.

**Comment by guangbochen** [comment]
This is currently not supported, will be tracked on https://github.com/harvester/harvester/issues/1218 with v1.0.0.

**Comment by yshashix** [comment]
When is a tentative plan for v1.0.0?

**Comment by guangbochen** [comment]
https://github.com/harvester/harvester/milestone/9 with  `Due by December 16, 2021`

**Comment by yshashix** [comment]
I still don't see the section to add https proxy while installing on v1.0 , I still see section to add http_proxy only.
Any idea how to add https proxy?

**Comment by guangbochen** [comment]
IIRC u should be able to configure both the http_proxy and https_proxy via the `settings -> http_proxy` setting.
https://docs.harvesterhci.io/v1.0/settings/settings/#http-proxy

![image](https://user-images.githubusercontent.com/4569037/152740609-f2cf1750-5b94-4656-9ebe-673f8f38934e.png)
