### ISSUE TITLE
[FEATURE] We should not expose 'prevent_destroy' attribute in Terraform 'harvester_clusternetworks' resource

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1355]
**Is your feature request related to a problem? Please describe.**
If the `prevent_destroy` attribute is set to `false`, executing `terraform destroy` will delete the special `vlan` resource, which causes the VIP to become non-functional. Furthermore, the networking config is no longer available in the UI. We should not expose the `prevent_destroy` option to prevent user from shooting-themselves-in-the-foot.

**Describe the solution you'd like**
Make the `vlan` resource immutable to deletion, or at least make it insanely hard to delete as deleting it could damage the entire cluster.

**Describe alternatives you've considered**
Put a big red warning in the documentation indication the consequences of deleting the special `vlan` resource.

**Additional context**
Use the following terraform script to reproduce the problem:
```
resource "harvester_clusternetwork" "vlan" {
  lifecycle {
    prevent_destroy = false
  }
  name                 = "vlan"
  enable               = true
  default_physical_nic = "harvester-mgmt"
}

```

**Comment by yasker** [comment]
@futuretea what's the use case for `prevent_destory=false` scenario?

**Comment by guangyee** [comment]
Looks like `prevent_destroy` is part of TF lifecycle management. https://www.terraform.io/docs/language/meta-arguments/lifecycle.html
However, we still need to find a way to guard against accidental deletion of the `vlan` resource as deleting it will have adverse impact on the cluster.

**Comment by futuretea** [comment]
@guangyee release v0.2.6. If users try to destory clusternetwork, will see "clusternetwork should not be destroyed, to avoid this error and continue with the plan, either move clusternetwork to another module or reduce the scope of the plan using the -target flag"

**Comment by guangyee** [comment]
Verified. I do see the proper warning message when attempting to destroy the vlan.
