### ISSUE TITLE
[BUG] Crash dump not written when kernel panic occurs

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1357]
1. Using 0.3.0-rc1-hotfix1
2. Trigger a kernel crash:
```
echo c >/proc/sysrq-trigger
```

Expect:
Crash dump is written to /var/crash

Actual:
Crash dump is not written, system just hangs

Note:
The server in this case has 768GB memory. Harvester seems to use a hardcoded `crashkernel=219M,high crashkernel=72M,low` which is not sufficient to perform crash dump on a system with that amount of RAM.

We probably need to make `crashkernel`  size user configurable such that it can be adapted to the physical system.

**Comment by yasker** [comment]
I doubt we need to dump the whole memory. Most of that is not the kernel.

**Comment by bk201** [comment]
The reserved memory values are calculated in the installation time based on the formula [here](https://doc.opensuse.org/documentation/leap/tuning/html/book-tuning/cha-tuning-kexec.html#sec-tuning-kexec-crashkernel).

Please help to collect
- `blkid`
- `journalctl -u kdump`
- The crash kernel booting log:
  - Attach any virtual terminal to the serial port of the server.
  - When booting, press `e` on the Grub menu and append `console=ttyS0,115200n8.` (depends on the server serial port and buadrate)    
    ![Screen Shot 2021-10-06 at 11 35 24 AM](https://user-images.githubusercontent.com/1691518/136137899-6e97225b-a971-42ae-916b-c7548f2f693c.png)
  - Boot the system, kernel message should be available on serial port.
  - Trigger a crash. The booting kernel message should be on the serial port.
- Is the machine NUMA enabled? ` dmesg | grep -i numa`

**Comment by alexdepalex** [comment]
I retested this on freshly installed nodes with `0.3.0-rc1-hotfix1` and now it seems to work. Not sure what's different from the different deployment. Issue can be closed.

**Comment by yasker** [comment]
I will move this to the next milestone and keep it in the icebox. If the issue arises again in the next couple of weeks we can revisit.

**Comment by noahgildersleeve** [comment]
I tested this in master-d05a6cc7-head. It didn't seem to work. I tested on a node with 12 logical cores and 64gb of RAM in a 4 node setup (DL160). 
1. trigger kernel panic as `root` with `echo c >/proc/sysrq-trigger`
2. Wait for reboot
3. Check logs with `journalctl -u kdump` and `ls /var/crash`
Let me know if you want this to be tested in some other way.

**Comment by janeczku** [comment]
@noahgildersleeve 

I believe the crash kernel is currently only activated if the system is booted via the "debug" boot menu entry. Could you clarify whether you did boot from that?

**Comment by noahgildersleeve** [comment]
Ah. I did not. I'll test it with that option and I'll update the test steps to include it.

**Comment by noahgildersleeve** [comment]
Tested in master-d05a6cc7-head.
1. Created new single node cluster with 16GB RAM
2. Booted into debug mode from GRUB entry
3. Created several VMs
4. triggered kernel panic with `echo c >/proc/sysrq-trigger`
5. Waited for reboot
6. Verified that dump was saved in `/var/crash`
