### ISSUE TITLE
[BUG] "Add disk" drop down resets back to first item

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1358]
**Describe the bug**
When hovering over a disk from the `Add disk` drop-down menu, the selection will jump back to the first item after a certain time period.

**To Reproduce**
- Select `Edit Config` from a node's context menu
- Select `Disks`
- At the bottom of the screen click on the `Add Disk` drop-down menu
- Hover over a disk that is not the first on the list
- Wait
- Selection will jump back to the first item

**Expected behavior**
Keep the selection on the hovered item.

**Environment:**
 - Harvester ISO version:  0.3.0-rc1-hotfix1

**Comment by TachunLin** [comment]
@n313893254 
Verified fixed on master-d05a6cc7-head, close this issue. 

### Result

When mouse hovering on add disk drop-down menu, the selection will not jump back to the first item after a certain time period.

![image](https://user-images.githubusercontent.com/29251855/138722149-20c04442-3d1b-4dee-be6b-048bbc35cfb3.png)


### Test Information
* Test Environment: Local qemu kvm machines with 3 nodes
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. Prepare a host machine with 3 nvme disks to add
2. Select Edit Config from a node's context menu
3. Select Disks
4. Click add Disk drop-down menu
5. Hover over a disk at the middle item of the available disk list 
6. Wait 10 min
7. Check the mouse hover location
