### ISSUE TITLE
[BUG] VM's function won't work when host is down

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1360]
### Describe the bug
This issue contain several cases but point to the same thing.
When VMs running on a certain Node1, and Node1 had connection issues, those functions for VM still available, you can click them but nothing happened even no error messages.

** This is discovered when testing Negative test cases(4, 5, 14, 15) of *Backup and Restore*.

### To Reproduce
1. Install harvester with 3+ nodes
2. Create VMs on specific Node (for example, Node1)
3. reboot Node1, then Node1's state changed to `In Progress`
4. all VMs be hosted on Node1 still shows Running/Stopping/processing(backup)...etc

### Expected behavior
Update Node's state to `unavailable` or other state instead of `In Progress` when cluster can't receive its status. (This should be configure-able in Settings)
When entering the state, VMs function should be frozen too.

## Environment:
 - Harvester ISO version: **master-82506f55-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
[host's state]
![image](https://user-images.githubusercontent.com/5169694/136208805-3e6c0fc6-e64e-4302-91ee-c22e69d322ca.png)

[VM's status]
![image](https://user-images.githubusercontent.com/5169694/136208896-5e11e160-4be8-4f6e-9ad3-55b3160ae530.png)

[backup's status]
![image](https://user-images.githubusercontent.com/5169694/136209074-c1ca80df-cc78-41d4-8d62-fd958e73f87c.png)

**Comment by lanfon72** [comment]
There also have some cascading issues as #1361's situation. (And we don't have any test cases for them yet)
so I will verify this when it is fixed and ready for testing. :wink:

**Comment by yasker** [comment]
Since the UI code is frozen already, we need to release note this for v0.3.0 then punt it to v1.0.0.

**Comment by lanfon72** [comment]
Ref exists issues: #982, #983 
All VM's negative test cases(1,2,3,4,5,7,8) is blocked due to this.

**Comment by WuJun2016** [comment]
track issue:   https://github.com/harvester/harvester/issues/982

**Comment by lanfon72** [comment]
@FrankYang0529, @WuJun2016, I will put this back to _review pipeline_ due to VM can't bring back after host is back.

- After host is back, VM will change to **Starting** state, but always hit _**FailedAttachVolume**_, and keep retrying.
![image](https://user-images.githubusercontent.com/5169694/141092998-3194275a-9819-40db-9860-fe5d95eaeff2.png)

- And If we bring down the host again, VM's state will not be changed. (still in the retrying loop, and state shows _Starting_)

**Comment by FrankYang0529** [comment]
@lanfon72 I try to reproduce the bug on Harvester master-119c2c48-head. VM can get back when a node is back. I have tried many times. May you try again? If you still get the error, may you provide support bundle? Thank you.

**Comment by lanfon72** [comment]
@FrankYang0529 I can reproduce this case on the test environment described below, but after refresh (with `ctrl+r`) page, VM bring back and operate normally.  Also tested on Provo's Baremetal, the behavior works as expected without refresh page.

In short, I think the different behaviors between KVM and baremetal is not related to this bug, so I will close this issue.


Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-119c2c48-head**
* **ui-source** Option: **Auto**
* [supportbundle_040c0aa6-88c5-4dad-be31-e590c690c36d_2021-11-16T13-06-33Z.zip](https://github.com/harvester/harvester/files/7546490/supportbundle_040c0aa6-88c5-4dad-be31-e590c690c36d_2021-11-16T13-06-33Z.zip)

**Comment by guangbochen** [comment]
reopen due to `vm-force-deletion-policy` is not configurable via the UI settings.

**Comment by WuJun2016** [comment]
The latest UI has added "VM force deletion policy" setting. You can take the latest UI to test whether the function is available.   @FrankYang0529  @lanfon72

**Comment by lanfon72** [comment]
@WuJun2016, @guangbochen I think the force deletion policy is not working.

The settings
![image](https://user-images.githubusercontent.com/5169694/144194608-758bfb20-cef9-4bae-aabe-6b93efcbacae.png)
Hosts
![image](https://user-images.githubusercontent.com/5169694/144194662-ae8df7a1-588a-498a-8cf9-5d923eb39441.png)
VMs
![image](https://user-images.githubusercontent.com/5169694/144194703-c5f36152-c007-4e04-9366-3acce4f35dd9.png)
VM which is pending on terminating
![image](https://user-images.githubusercontent.com/5169694/144194502-0562cde1-ceeb-4de8-8ff3-8cc1e371e61a.png)
VM which is pending on stopping
![image](https://user-images.githubusercontent.com/5169694/144194529-c8502add-b202-4001-9f2b-44c100f0141f.png)


Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-1e042e04-head**
* **ui-source** Option: **Auto**
*  [supportbundle_c2e87632-8554-4d16-8193-6ed15f5a8ac8_2021-12-01T08-05-45Z.zip](https://github.com/harvester/harvester/files/7631953/supportbundle_c2e87632-8554-4d16-8193-6ed15f5a8ac8_2021-12-01T08-05-45Z.zip)

**Comment by lanfon72** [comment]
Verified the _vm-force-deletion-policy_ works as expected.

Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-3b5fe2e0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Create Image for VM creation
3. Create 2 VMs on Node A
4. Disable _vm-force-deletion-policy_ in Advanced Settings
5. shut down Node A
6. Delete and stop each VM on Node A
7. `TaintManagerEvicition` should be appeared in VM's Events after the set time of _vm-force-deletion-policy_ has elapsed, and VMs should not be deleted
8. Enable _vm-force-deletion-policy_ in Advanced Settings
9. VMs should be deleted/stopped after the policy enabled
10. Change _Period_ of _vm-force-deletion-policy_ to `180`
11. power on Node A
11. repeat step 3 to 6
12. VMs should be deleted/stopped after the set time of _vm-force-deletion-policy_ has elapsed
