### ISSUE TITLE
[BUG] Node duplicate display when it back online

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1361]
### Describe the bug
Previous status of certain Node still shown when it back online.

### To Reproduce
1. install Harvester with 3+ nodes
2. reboot specific Node (for example, Node1)
3. Wait until its state changed to `In Progress`, then boot back to OS
4. the Node back online, but old one still here.

### Expected behavior
Old state column should be eliminated.

## Environment:
 - Harvester ISO version: **master-82506f55-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
[on joining]
![image](https://user-images.githubusercontent.com/5169694/136215481-ea2612f3-832e-4a09-84e9-c3b3fcee4e87.png)

[after joined]
![image](https://user-images.githubusercontent.com/5169694/136215557-8be87b16-195c-4ec3-9d3e-a0bc72aa49eb.png)

**Comment by lanfon72** [comment]
There have a bit different that:
origin one was named by custom Name, hostname was not configured in configure file. (and get the random name as `harvester-rb6l4`)

hostname changed to `hpd8s11` after reboot.

[origin one]
![image](https://user-images.githubusercontent.com/5169694/136217424-e26969ea-82ca-4e1c-8885-46fb68c28056.png)

[the newer]
![image](https://user-images.githubusercontent.com/5169694/136218024-69f6039b-b3b5-46cf-ab31-5929df8dd126.png)

**Comment by lanfon72** [comment]
There also have some duplicated host options could be selected in several functions, they should be in the same root cause, so I would tend to verify this when it is ready to testing. (so that I don't need to open other issues... :wink:)

**Comment by yasker** [comment]
Need to release note this for v0.3.0.

**Comment by weihanglo** [comment]
Cannot reproduce on KVM for 3 node clusters. @lanfon72 if you haven't stepped into this issue, feel free to close it. Thanks.

**Comment by lanfon72** [comment]
Close as I didn't hit this bug recent two weeks.
