### ISSUE TITLE
[FEATURE] login page of bootstrap password

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1362]
### Describe the bug
There have two different pages to setup password, it's confusing.

### To Reproduce
1. install Harvester
2. navigate to `https://<VIP>/` - the general form
   (and it actually redirect us to `/dashboard/auth/setup`)
3. navigate to `https://<VIP>/dashboard/auth/login` - this form requires user to do some docker/k8s commands

### Expected behavior
Although we already redirect user to general form, but after setup password, we use 2nd's route path `/dashboard/auth/login` to show login page.
I think it would be nice that we change to use the same route path for setup password and login.

## Environment:
 - Harvester ISO version: **master-a4528869-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360** single node

### Additional context

[general form]
![image](https://user-images.githubusercontent.com/5169694/136250775-f6d3cc9b-cefb-4b34-b947-4644280039ad.png)

[command form]
![image](https://user-images.githubusercontent.com/5169694/136250728-05f0ad1a-56f0-4d7b-95a8-d2eabf2e3b80.png)

**Comment by yasker** [comment]
Need @guangbochen to confirm if this is expected behavior. But good finding on the difference between the login pages @lanfon72 !

**Comment by lanfon72** [comment]
Alejandro asked in slack:
> I am confused by the Dashboard setup on rc1 - after setting up my admin password, it’s asking for a bootstrap password. Is it talking about the Harvester cluster secret? Why does it want me running a docker command to find a password?

I report this as a reference.

**Comment by WuJun2016** [comment]
Is the ui version v0.3.0?    I can't reproduce it at the moment, it may be an occasional problem.

**Comment by lanfon72** [comment]
reproduced on the version **master-a4528869-head** was released between _v0.3.0-rc1_ and _v0.3.0-rc2_.

I saw UI had many changes on v0.3.0, will try to reproduce this issue on it.

**Comment by lanfon72** [comment]
reproduced on the version **v0.3.0**
The route path `https://<VIP>/dashboard/auth/login` still shows:
![image](https://user-images.githubusercontent.com/5169694/137089886-8119ff57-c6cd-40bd-ac8f-475b751ef40e.png)

It's corner case that users usually will not reach here unless they bookmark the login URL.

**Comment by WuJun2016** [comment]
@lanfon72   The first login will automatically jump to `dashboard/auth/setup`. But at this time, you did not set a password, but entered the url to jump to` /dashboard/auth/login` ?

**Comment by lanfon72** [comment]
@WuJun2016 yes, some scenario like that.
this should be low priority, normally users won't reach this area unless.... :wink:

**Comment by WuJun2016** [comment]
Not all users need to reset their passwords, and we don't know if we need to reset the initialized password before logging in.  So when the user enters the url to `auth/login`, we should not force the user to go to the `setup/auth` page to set the password.

**Comment by lanfon72** [comment]
As the concern, lets change the topic to enhance instead.

**Comment by yasker** [comment]
Close as stale. Feel free to reopen if needed.
