### ISSUE TITLE
[FEATURE] Support diskless nodes with external storage

### ISSUE THREAD

**Issue by olljanat** [harvester/harvester#1365]
Split from https://github.com/harvester/harvester/issues/1199#issuecomment-936835564

**Is your feature request related to a problem? Please describe.**
I can see that documentation already describe how to boot Harvester installer from PXE but it still assumes that installation would be done to local disk.

**Describe the solution you'd like**
It should be possible load even rootfs from iSCSI https://github.com/dracutdevs/dracut/blob/c868feb1b1c118781050ecdff3c14a1a8f008c92/man/dracut.cmdline.7.asc#iscsi or from NFS https://github.com/dracutdevs/dracut/blob/c868feb1b1c118781050ecdff3c14a1a8f008c92/man/dracut.cmdline.7.asc#nfs which would works even on fully diskless nodes.

I have big set of diskless servers which have been running VMware earlier with external storage and it would be very interesting to use those for piloting Harvester if that will be supported.

**Comment by vanakema** [comment]
Just putting my desire for this too in writing. 

sidenote: The Rancher team seems to not be that into diskless nodes. K3OS doesn't support it either via PXE boot

**Comment by kajla** [comment]
Dear @vanakema ,

It's okey, but what happens when the system is installed on a small SD card, and other bigger, faster data disk(s) is attached from SCSI?
We have got some blade servers, which contain a small (32/64 GB) SD card for OS, and lot of TB disk from SCSI.
Is it possible to install Harvester?

Thank you in advance for your answer.

**Comment by olljanat** [comment]
> sidenote: The Rancher team seems to not be that into diskless nodes. K3OS doesn't support it either via PXE boot

@vanakema Note that Harvester is not based on K3OS anymore #581 so it's limitations does not matter here.

> It's okey, but what happens when the system is installed on a small SD card, and other bigger, faster data disk(s) is attached from SCSI? We have got some blade servers, which contain a small (32/64 GB) SD card for OS, and lot of TB disk from SCSI. Is it possible to install Harvester?

@kajla that sounds like use case which #1199 is about.

**Comment by vanakema** [comment]
> > sidenote: The Rancher team seems to not be that into diskless nodes. K3OS doesn't support it either via PXE boot
> 
> 
> 
> @vanakema Note that Harvester is not based on K3OS anymore #581 so it's limitations does not matter here.
> 
> 
> 
> > It's okey, but what happens when the system is installed on a small SD card, and other bigger, faster data disk(s) is attached from SCSI? We have got some blade servers, which contain a small (32/64 GB) SD card for OS, and lot of TB disk from SCSI. Is it possible to install Harvester?
> 
> 
> 
> @kajla that sounds like use case which #1199 is about.
> 
> 
> 
> 

Yea I was just mentioning it as a reference to the Rancher team's general sentiment on full diskless live boot via PXE (vs PXE install which they do support for both K3OS and Harvester)

**Comment by Sporesirius** [comment]
+1 for this

**Comment by deke997** [comment]
+1

**Comment by bk201** [comment]
@jeff-radick-suse wrote a document on how to install Harvester on a diskless server: https://harvesterhci.io/kb/install_iscsi_firmware_install_boot

However, we should improve the installer to avoid the manual workarounds:
- https://harvesterhci.io/kb/install_iscsi_firmware_install_boot#4-on-first-boot-edit-kernel-boot-parameters-in-the-grub-kernel-command-line
- https://harvesterhci.io/kb/install_iscsi_firmware_install_boot#5-permanently-edit-the-grub-configuration-file

**Comment by innobead** [comment]
Let's track https://github.com/harvester/harvester/issues/5150 instead.
