### ISSUE TITLE
Adjust the API ID format

### ISSUE THREAD

**Issue by thxCode** [harvester/harvester#137]
According to https://github.com/rancher/harvester/pull/112#discussion_r486176045, we should adjust the format of the API ID from `{namespace}:{name}` (norman style) to `{namespace}/{name}` or compatible:
https://github.com/rancher/harvester/blob/6a0eb2ffc5af2df5f39a38772d28e82346f95447/pkg/ref/api_id.go#L8-L15

**Comment by guangbochen** [comment]
I think the `ns:name` format is also used in other places like VM image annotation, we should make this consistent across the project, @gitlawr can u please help to confirm, thanks.

**Comment by thxCode** [comment]
I think a breaking change is better than a compatible enhancement if possible.

**Comment by gitlawr** [comment]
Yes we need to coordinate with UI for the change

**Comment by gitlawr** [comment]
After backend is ready, UI should update the processing for the following fields accordingly
```
VMTemplateVersion.spec.templateId
VMTemplateVersion.spec.keyPairIds
VMTemplate.status.defaultVersion
DataVolumes' "harvester.cattle.io/imageId" annotation.
```

**Comment by aiwantaozi** [comment]
@WuJun2016

**Comment by DaiYuzeng** [comment]
@gitlawr hi, i think we should not update the field ```VMTemplate.status.defaultVersion``` ,  but ``` VMTemplate.spec.defaultVersionId ```.

![image](https://user-images.githubusercontent.com/15041915/93285924-93b8a580-f808-11ea-8e2f-4b5b52ba9b5a.png)

**Comment by gitlawr** [comment]
@DaiYuzeng Good catch, also check if there's any place I am missing

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/93, https://github.com/rancher/harvester-ui/pull/90, https://github.com/rancher/harvester/pull/141.
