### ISSUE TITLE
[BUG] VM's volume be purged and can't be edited

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1372]
### Describe the bug
An VM is created from existing volume, start and running, but unable to restart, and Volumes' configuration tab shows that value of attached volume is empty and unable to edit.

** VM's test case No.16

### To Reproduce
1. install Harvester
2. create a VM and boot to OS
3. delete the VM but keep disk volume
4. create another VM using former volume
5. start the VM, then edit the configuration
6. the value of attached volume shows no value and unable to edit

### Expected behavior
The value of VM's volume should not be no value and unable to edit in any case.

## Environment:
 - Harvester ISO version: **master-a4528869-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360** 3nodes

### Additional context
[running with empty value's volume]
![image](https://user-images.githubusercontent.com/5169694/136422061-7cc39e04-f66c-4ab4-bb62-b8063a4c1495.png)

[Volumes page shows it's attached]
![image](https://user-images.githubusercontent.com/5169694/136422210-06f8df90-0c28-41aa-a9b7-a4c794948450.png)

The VM's yaml:
[k3ospc.yaml.txt](https://github.com/harvester/harvester/files/7305289/k3ospc.yaml.txt) 
(renamed to `.txt` to upload here)

**Comment by lanfon72** [comment]
forgot to snapshot the Volume tab when VM is off...
but even if it become `off` state, we still unable to edit it.

**Comment by guangbochen** [comment]
verified using the `master-8542e305-head` version - `passed`
1. create a new VM from an existing root disk volume
2. after the VM is up and running, click edit config and check the volumes tab 
3. the existing volume is showing correctly and modify the config e.g CPU, memory and add an additional disk
![image](https://user-images.githubusercontent.com/4569037/136646539-b28c6dd9-2aef-4be9-a0c7-086e25f8dfef.png)
4. click save and the VM is able to be up and running successfully. 
![image](https://user-images.githubusercontent.com/4569037/136646597-4287f0db-a8ca-4ad6-8585-c7a1021142c7.png)
