### ISSUE TITLE
[BUG] RKE2 / Harvester: Nodes stuck in provisioning when master nodes lack worker role

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1373]
Rancher version: v2.6.1-rc5
Harvester version: v0.3.0-rc1

See here for details: https://github.com/rancher/rancher/issues/35065

Related issue: https://github.com/rancher/rancher/issues/34992

**Comment by yasker** [comment]
We need to investigate to see if there is an easy to solve this. Otherwise, we need to push it out of v0.3.0.

**Comment by futuretea** [comment]
If  set cluster-provider to None, the cluster will be ready. @guangbochen
If set cluster-provider to harvester, `kubectl get po -A` show as below:
![image](https://user-images.githubusercontent.com/15064560/136529122-aac9d654-10e3-4ba6-a016-0391c8ea7de5.png)

**Comment by guangbochen** [comment]
so most likely it is because the Harvester CCM pods are not up and running as expected, therefore it leads the cluster to a forever provisioning status, @yaocw2020  can u PTAL of this, thanks.

**Comment by abonillabeeche** [comment]
Did anyone figure this out? I'm wondering why we provision the worker nodes before the masters as well...

**Comment by yaocw2020** [comment]
> Did anyone figure this out? I'm wondering why we provision the worker nodes before the masters as well...

The pr is merged. It's ready for testing. It's a bug about the harvester cloud provider. Users can not deploy any workload before the cloud provider is ready. We should add the tolerations to allow the harvester cloud provider to be deployed in the master node.

**Comment by yaocw2020** [comment]
For testing
Due to we have not cut a new rke2 release, please use the rke2 master version to verify this issue.

**Comment by noahgildersleeve** [comment]
How would you do that? I didn't see an option in the node driver.

**Comment by yaocw2020** [comment]
> How would you do that? I didn't see an option in the node driver.

What about suspending this case and waiting for the RKE2 to cut a new release? That will be easier and spend less time.

**Comment by noahgildersleeve** [comment]
Sounds good to me. How do you feel about it @guangbochen. Also how will I know if there's a new RKE2 release?

**Comment by guangbochen** [comment]
Yep, just doing the validation after the RKE2 new release is out, u should be able to track it on the https://github.com/rancher/kontainer-driver-metadata/blob/dev-v2.6/channels-rke2.yaml (needed for Rancher's) and https://github.com/rancher/rke2/releases

**Comment by yasker** [comment]
Verified via https://github.com/rancher/rancher/issues/35065#issuecomment-995109182
