### ISSUE TITLE
[Enhancement]Namespaces present in the harvester cluster eg: rancher-server and harvester-public are not present in any of the Rancher projects like System,Default project

### ISSUE THREAD

**Issue by anupama2501** [harvester/harvester#1378]
**Is your feature request related to a problem? Please describe.**
We have some namespaces in the Harvester Cluster like rancher-server and harvester-public which are not present in any of the Rancher provided projects eg: System, Default
Virtualization management --> Harvester cluster --> Projects/namespaces

**Describe the solution you'd like**
The namespaces can be moved to rancher provided projects as applicable and can be referred via Projects accordingly from the namespace picker for a better hierarchy.

**Additional context**
In rancher server the upstream and downstream clusters, we have namespaces separated by projects for a better hierachy of the workloads .

**Comment by bk201** [comment]
Please check https://github.com/rancher/dashboard/issues/4348#issuecomment-955911204
