### ISSUE TITLE
[BUG] deleted clusters still visible under rancher

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1379]
**Describe the bug**
I can see (2) as the cluster count in Rancher, but I only have "local" - also when creating Cloud Credentials, I can see a list of previously deleted clusters

**To Reproduce**
Add more than one Harvester Cluster, then delete it. Go to Cloud Credentials, it's still listed there.

**Expected behavior**
Clusters should be deleted from Rancher when deleted from Virtualization Management

**Support bundle**
rancher 2.6.1-rc11
Harvester ISO version: master-c4a76706-head 

**Environment:**
 - Harvester ISO version: master-c4a76706-head 
 - Underlying Infrastructure: Dell PowerEdge r620

**Additional context**
Add any other context about the problem here
<img width="1239" alt="Screen Shot 2021-10-07 at 7 12 56 PM" src="https://user-images.githubusercontent.com/5146963/136474619-5819088e-e6ae-4a06-8312-6d438ee6f61d.png">
.
<img width="1475" alt="Screen Shot 2021-10-07 at 7 13 13 PM" src="https://user-images.githubusercontent.com/5146963/136474635-93252fd9-3f59-4d6d-b0fc-fe6d6a6ccd44.png">
.
<img width="1035" alt="Screen Shot 2021-10-07 at 7 13 34 PM" src="https://user-images.githubusercontent.com/5146963/136474644-3f7db0bb-51d7-4888-b9a8-495e9cb87803.png">

**Comment by abonillabeeche** [comment]
I think this might be a residue of
https://github.com/rancher/rancher/issues/35018
maybe duplicate of
https://github.com/harvester/harvester/issues/1311

**Comment by guangbochen** [comment]
this is identical to https://github.com/harvester/harvester/issues/1311, close as it has already been verified on the other issue, feel free to re-open it if u encounter a different issue, thanks.
