### ISSUE TITLE
[BUG] Add Image upload notification message

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1380]
It seems I cannot get image upload to work with the latest master
<img width="453" alt="Screen Shot 2021-10-07 at 4 30 24 PM" src="https://user-images.githubusercontent.com/3344618/136475837-1b196dd2-5e8d-4c02-aa7d-d5ef6ed3f2f8.png">

**Comment by yasker** [comment]
The second try works for me. It seems due to I've refreshed the page during the upload for the first time, since I didn't see any warning against it.

**Comment by guangbochen** [comment]
Should notify user do not to refresh the page while uploading the file locally.

**Comment by simonflood** [comment]
I'm seeing this with Harvester 0.3.0 when trying to upload ~250MB qcow2 files, either from a local directory on my laptop or a remote directory mounted via CIFS. I am NOT refreshing the Images page during upload.

**Comment by simonflood** [comment]
I should note that the file size is not picked up on the Images page.

I am able to Create an image if I set up a local HTTP server using Python in the source directory and use the appropriate URL for the same files (http://<localipaddress>:8000/filename) - the file upload is almost instant with file size picked up.

**Comment by noahgildersleeve** [comment]
I can repro this error, but it seems to be happening on dmg files. It's possible to upload them, are we supporting using that in the virtual drive? I'm not sure what kind of an OS level filetype list we're enforcing. 
I tested this with `master-d05a6cc7-head` and the google chrome dmg.
![image](https://user-images.githubusercontent.com/83787952/139736433-a60e3856-d335-4b2f-8b07-8935ba179c85.png)

**Comment by n313893254** [comment]
We support .iso, .img, .qcow2 and .raw file types, the .dmg is the same as .img on the chrome browser view. All the images require the size should be a multiple of 512 bytes since Longhorn uses directIO by default.

How about adding an error notification on UI after the upload fail?

**Comment by guangbochen** [comment]
Yep, adding a failed error message is helpful as the current `Failed to wait for xx` message is meaningless.

**Comment by WolframRavenwolf** [comment]
I could reproduce this issue with the latest k3os-amd64.iso (v0.20.11-k3s2r1, 514 MB) and a remastered version of that. Tried it in Firefox and Chrome, didn't refresh the page, got the error message "Failed to wait for processing start in 60 seconds" every time.

**Comment by TachunLin** [comment]
Update my test status on version master-d21b9161-head for reference.

Senario1: Upload `k3os-amd64.iso` from file, disable network during upload process:
- Show `context canceled` 
![image](https://user-images.githubusercontent.com/29251855/140720320-9818778e-e250-4e6f-b405-8f3394b27a2d.png)

Senario2: Upload centos 8 qcow2 from URL under poor or limited network environment, cause timeout
Show `Failed to finish file.... processing context cancel`
![image](https://user-images.githubusercontent.com/29251855/140723327-95d922e8-4d27-4b17-bd2e-d1bca73f8bf3.png)

Senario3: Upload chrome dmg file from URL till the end
Show `Failed to calculate checksum...`
![image](https://user-images.githubusercontent.com/29251855/140723230-44b347cc-0a72-4a21-a618-353891ca4af1.png)

**Comment by TachunLin** [comment]
Verified **not fixed** on master-119c2c48-head. Move issue to review pipeline stage.
Suggest can provide more clear information for what cause the error 

### Result
Upload file type .qcow2 (253MB) and googlechrome.dmg from file still show error message
`Failed to wait process start in 60 seconds`
![image](https://user-images.githubusercontent.com/29251855/141098180-c0b587f0-0f9b-4c82-84f2-2af88fe65c45.png)

- [ X ] googlechrome.dmg (106.6MB) 
- [ O ] k3os-amd64.iso (539.4MB)
- [ O ] focal-server-cloudimg-amd64.img (567.7MB)
- [ O ] CentOS-8-GenericCloud-8.4.2105-20210603.0.x86_64.qcow2 (1.2G)
- [ X ] CentOS-7-x86_64-GenericCloud-1602.qcow2 (253.2MB, rename from xx.qcow2.xy)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-119c2c48-head

### Environment Preparation


### Verify Steps

1. Download different type of installation image file
2. Create image
3. Upload image from file

### Additional Context
None

**Comment by n313893254** [comment]
@TachunLin, I can not reproduce the issue with master-119c2c48-head, Could you give me more information to reproduce the issue? 

https://user-images.githubusercontent.com/18737885/141735082-1bd20ef4-e7fd-489a-8a72-7e253ce9d9cf.mp4

**Comment by TachunLin** [comment]
@n313893254 
I have verified again on provo bare machine with master-119c2c48-head. 
Please use this dmg file [googlechrome.dmg](https://mysuse-my.sharepoint.com/:u:/r/personal/david_lin_suse_com/Documents/Harvester/test_data/googlechrome.dmg?csf=1&web=1&e=3rsiHB) can always reproduce the error upload scenario. 

I reproduce this issue on provo bare machine today, in the beginning it will show up with 
`Failed to wait for processing start in 60 seconds` 
When I relogin and access harvester and open developer tool to refresh page
The error upload message shows our expected error message in `Upload failed the uploaded file size ...` 
Maybe it's related to webook operation 

Below is the demo gif video for reference:

![1380_3](https://user-images.githubusercontent.com/29251855/141772548-b81dd87e-e905-4b0c-9e00-ee1b31cffdbd.gif)

**Comment by gitlawr** [comment]
@TachunLin From the recording, the upload resulted in an expected error message. Are you able to reproduce the timeout error now?

**Comment by TachunLin** [comment]
@gitlawr 

Verified on the latest master-45e25939-head version with brand new installation without any page refresh action. 
Upload .img and .qcow2 with unsupported file size multiplies, did not show the `Failed to wait for processing start in 60 minutes` message

![image](https://user-images.githubusercontent.com/29251855/142422288-7ca932d0-59a7-429b-bff3-7d8e5b23015a.png)

### Test Information
Test Environment: 3 nodes harvester on provo bare machine
Harvester version: master-45e25939-head

**Comment by guangbochen** [comment]
> @gitlawr
> 
> Verified on the latest master-45e25939-head version with brand new installation without any page refresh action. Upload .img and .qcow2 with unsupported file size multiplies, did not show the `Failed to wait for processing start in 60 minutes` message
> 
> ![image](https://user-images.githubusercontent.com/29251855/142422288-7ca932d0-59a7-429b-bff3-7d8e5b23015a.png)
> 
> ### Test Information
> Test Environment: 3 nodes harvester on provo bare machine Harvester version: master-45e25939-head

@TachunLin the screenshot states it is a file byte size issue from longhorn, I think this is the correct message we are expecting for?

**Comment by TachunLin** [comment]
> We support .iso, .img, .qcow2 and .raw file types, the .dmg is the same as .img on the chrome browser view. All the images require the size should be a multiple of 512 bytes since Longhorn uses directIO by default.
> 
> How about adding an error notification on UI after the upload fail?

@guangbochen 
I think from user's perspective, if they encounter this message they can't just take a look and quickly understand what's going on or what to do next.

@n313893254, @gitlawr 
If this case did coming from the limitation of unsupported format or file size not fit size of multiple of 512 bytes in longhorn. 
Can we enhance the error message with clear notification to user and provide some suggestion to give them some suggestions?

**Comment by n313893254** [comment]
How about adding a size validation for image upload from the UI side?

**Comment by gitlawr** [comment]
It tells that the provided image is invalid. I think a size validation won't help. The dmg file is not supported. qcow2 image should be supported, how did you get the test qcow2 file? @TachunLin

**Comment by TachunLin** [comment]
Hi @gitlawr 
The qcow2 file downloaded from the CentOS image site url (253MB)
https://cloud.centos.org/altarch/7/images/CentOS-7-x86_64-GenericCloud-1602.qcow2.xz

Then rename and remove the .xz file extension to make it .qcow2 

The test chrome dmg file, it's directly downloaded from Google official site, I save a copy to  [googlechrome.dmg](https://mysuse-my.sharepoint.com/:u:/g/personal/david_lin_suse_com/EZAMUL8znq1FstRMyD13HS8BQ4TVL5xvfZBgXJU-OBc_4Q?e=uOJKF8)

**Comment by gitlawr** [comment]
Compressed files are not supported. For this case, users should provide a supported image file.

**Comment by TachunLin** [comment]
For the compressed file we need to have a clear message to notify user it's not a supported file format. 

Regarding to the error message response from longhorn, after discussed with longhorn team member 
`.dmg` file also not supported on longhorn UI and response with the same error message 
![image](https://user-images.githubusercontent.com/29251855/142888231-4771f306-9fae-4dd8-a3de-42dfa0131343.png)


I have filed an issue suggestion in [longhorn/longhorn/#3294](https://github.com/longhorn/longhorn/issues/3294) for tracking.

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. I tried to upload opensuse qcow2 image, and it gave a 413 error in the console and then gave an error after a 60 sec timeout. image used was http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img
[supportbundle_9a2fd2e9-f01f-46d9-92aa-6d89e75fd98d_2021-12-07T21-07-06Z.zip](https://github.com/harvester/harvester/files/7671585/supportbundle_9a2fd2e9-f01f-46d9-92aa-6d89e75fd98d_2021-12-07T21-07-06Z.zip)
![Greenshot 2021-12-07 13 06 31](https://user-images.githubusercontent.com/83787952/145106496-da2a7730-065d-494a-aba5-7ba77937770d.png)
![Greenshot_2021-12-07_13_05_47](https://user-images.githubusercontent.com/83787952/145106500-3dab27fd-d3f8-4e62-8484-f5000cdb941a.jpg)

**Comment by guangbochen** [comment]
observe the [413 error](https://github.com/kubernetes/ingress-nginx/issues/4825) recently due to the ingress changes and should be resolved by adding the following config to disable the size check.
```
kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-configuration
  namespace: ingress-nginx
  labels:
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
data:
    proxy-body-size: 10m # set size to 0 to disable the check.
```

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Still getting 413 error on upload.
![Screenshot from 2021-12-12 15-53-36](https://user-images.githubusercontent.com/83787952/145734769-2efe3688-821c-4c7c-aafe-bf4987a93130.png)
![Screenshot from 2021-12-12 15-52-56](https://user-images.githubusercontent.com/83787952/145734770-86279b1d-827b-4468-b202-386416273bdf.png)

**Comment by gitlawr** [comment]
@noahgildersleeve 655c251a is a commit from 6 days ago, can you try with the latest image?

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head with http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img
## Test Steps
1. upload image
2. wait for image to be ready
3. Create VM with image
4. Run VM health Checks.
Verified as fixed.
