### ISSUE TITLE
[BUG] Move DNS page before Configure Management Address page

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1381]
**Describe the bug**
Since users can input a domain name as a management address, we need to configure DNS first.

![Image from iOS](https://user-images.githubusercontent.com/4927361/136481395-92873046-069c-4c0b-90e7-586a0c0204b9.jpg)

**To Reproduce**
1. Set up the first Harvester node with a domain name.
2. Set up the second node and join the first node by the domain name.

**Expected behavior**
A node can join a cluster by the domain name.

**Support bundle**

**Environment:**
 - Harvester ISO version: master-c4a7670-master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by guangbochen** [comment]
close in favor of the master-head ISO build, the user was able to config the DNS server before specifies the management node.
![image](https://user-images.githubusercontent.com/4569037/136648143-44866c28-768a-44a0-9136-98463a52a6a2.png)
