### ISSUE TITLE
[BUG] Change namespace of existing VM by using terraform provider will cause "Virt-launcher pod has not yet been scheduled" 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1384]
### Describe the bug 
Change the namespace value of virtual machine terraform resource file (.tf) 
Then use Terraform provider to apply to Harvester. 
The virtual machine is keep running with message 
`Virt-launcher pod has not yet been scheduled` 
<br>

![change-vm-namespace_terraformer.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/ac2e35a2-6512-40e9-89e0-51e0fb812364)

### Prerequisite

- Install Terraform and Terraform Provider of Harvester 
   https://confluence.suse.com/display/HARV/17.+Terraform+provider 
- Install Terraformer 
https://confluence.suse.com/display/HARV/18.+Terraformer+Harvester 
- Export existing Harvester kubeconfig file (from Dashboard or API) and save as /.kube/config 

### To Reproduce

1.  Unzip file `provider_resouce_tf.zip` 
2.  Add your kubeconfig file path in provider.tf file 
![provider_kubeconfig.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/9826b987-eece-4474-ac47-f43d787f1044)
3. Run `terraform init` -> `terraform plan` -> `terraform apply`
4. Wait for all resource created on Harvester 
5. Run `terraformer import harvester -r virtualmachine`
6. Replace the provider to registry.terraform.io/harvester/harvester
7. Open virtualmachine.tf under ../generated/harvester/virtualmachine
8. Change the namespace value in virtualmachine.tf 
9. Run `terraform init` -> `terraform plan` -> `terraform apply` 
10. Open Harvester virtual machine page to check VM status

### Expected Behavior 
Virtual machine status should be running without showing message:  
`Virt-launcher pod has not yet been scheduled"`

### Environment 
- Harvester ISO version: master-82506f55-head
- Test Environment: qemu/KVM 1 nodes 
---
### Additional Information
Harvester provider provider and resource file for creating virtual machine 
[provider_resouce_tf.zip](https://github.com/harvester/harvester/files/7309189/provider_resouce_tf.zip)

I have tried reboot Virtual machine and Host KVM, But nothing changed. FYI

**Comment by futuretea** [comment]
@TachunLin 

This error occurs because the existing volume cannot be found in the new namespace after you modify the namespace of the VM.

Existing volume and vm must belong to the same namespace. If you modify the namespace of the VM, you should also modify the namespace of the existing volume used by the VM.

This problem does not occur if your VM does not use existing Volume.

Another important point to note is that after modifying a namespace, the old resources will be replaced by a new one. If you modify an existing volume namespace, the existing data will be lost.

**Comment by TachunLin** [comment]
I see, I also notice if I changed the namespace value of VM then run `terraform plan` 
1 resource added and 1 deleted.  

Update the relating test case 6 in 
https://confluence.suse.com/display/HARV/18.+Terraformer+Harvester

**Comment by guangbochen** [comment]
@TachunLin can u please help to verify and close it if it has passed, thanks.

**Comment by TachunLin** [comment]
Close this issue since according to @futuretea comment: 
Existing volume and vm must belong to the same namespace. 
Change namespace of VM should not consider to be a regular operation for VM.
