### ISSUE TITLE
[BUG] VM always in starting state when 3 VMs is running

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1387]
### Describe the bug
When starting 4th VM or more, they always looping on starting state.
those VMs use the same img/iso file, so it's not image issue.

### To Reproduce
1. Install Harvester
2. start 3 VMs and make sure they are running
3. start 4th VM, it looks like take a long starting time but actually fail to start and keep trying to restart.

### Expected behavior
VM should start and become running successfully.

## Environment:
 - Harvester ISO version: **master-a4528869-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
[VM's state]
![image](https://user-images.githubusercontent.com/5169694/136532517-5c4c86e0-3932-41b9-931d-c0f675b77386.png)

[4th VM's Event]
![image](https://user-images.githubusercontent.com/5169694/136532396-844d40dc-6c26-416c-bd47-cd6f1e91dd10.png)

**Comment by lanfon72** [comment]
I will generate and upload support bundle few hours later, to make sure there have enough log to debug.

**Comment by weihanglo** [comment]
Haven't dig into the support bundle. Just a random ask: Do we have sufficient storage or memory to allocate 4th VM in that machine?

**Comment by lanfon72** [comment]
I think no, nodes are bare material which have large amount of CPUs/Mems, for storage... although storage only 250Gb but I didn't allocate any volumes >10Gb.

In this case, if I turn off any running VM, 4th VM will start successfully later.

**Comment by guangbochen** [comment]
this seems to be a bug related to the batch VM creation, I will need to refresh to page to get the correct VM status, @WuJun2016 can u guys PTAL, thanks

**Comment by lanfon72** [comment]
Upload the support bundle:
[supportbundle_f266b1fc-034c-471d-8705-133d66a985ba_2021-10-08T16-35-27Z.zip](https://github.com/harvester/harvester/files/7312954/supportbundle_f266b1fc-034c-471d-8705-133d66a985ba_2021-10-08T16-35-27Z.zip)

**Comment by lanfon72** [comment]
tested on **v0.3.0**, I can start more than 3 VMs, but new VM still had chance stuck into the loop `Create -> Volume attach failed -> Delete -> Pending -> Create`.

**Comment by lanfon72** [comment]
successfully create VMs over than six, and still able to start new VM successfully.

Harvester version: **master-ebfbf44a-head**
dashboard option: **Auto**

**Comment by WuJun2016** [comment]
> I think no, nodes are bare material which have large amount of CPUs/Mems, for storage... although storage only 250Gb but I didn't allocate any volumes >10Gb.
> 
> In this case, if I turn off any running VM, 4th VM will start successfully later.

I have not reproduced the problem, and based on this description I think it is caused by a lack of resources.    @lanfon72

**Comment by WuJun2016** [comment]
The calculation of remaining resources in the host is incorrect, we will fix it in this issue （https://github.com/harvester/harvester/issues/1376 ）

**Comment by lanfon72** [comment]
> > I think no, nodes are bare material which have large amount of CPUs/Mems, for storage... although storage only 250Gb but I didn't allocate any volumes >10Gb.
> > In this case, if I turn off any running VM, 4th VM will start successfully later.
> 
> I have not reproduced the problem, and based on this description I think it is caused by a lack of resources. @lanfon72

yeah I thought the issue is caused by longhorn... I will close this issue if can't reproduce it in this week.

**Comment by noahgildersleeve** [comment]
I tested in master-a412145f-head. Fixed.
1. Created 5 VMs with opensuse raw image template
2. Started all VMs
3. Verified all Vms showed as ready
4. Spot checked VM with VM health checks
