### ISSUE TITLE
[BUG] rd.cos.debugrw does not persist changes to /boot

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1388]
**Describe the bug**
1. Install Harvester 0.3.0-rc1-hotfix1
2. Reboot machine with kernel parameter `rd.cos.debugrw` to [make root fs read/write](https://rancher-sandbox.github.io/cos-toolkit-docs/docs/customizing/runtime_persistent_changes/#transient-changes)
3. Make changes to `/boot` e.g. by installing a kernel RPM

**Expected Result**
Changes to `/boot` are persisted

**Actual Result**
Changes to `/boot` are lost after reboot

Note:

This was working with 0.3.0-rc1 but broke in hotfix1 possibly as a result of making kdump work.

**Comment by yasker** [comment]
We need to make sure in the debug mode, users can upgrade kernel packages for testing purposes.

**Comment by bk201** [comment]
Before https://github.com/harvester/os2/pull/18 is in, there is a workaround. Please see https://docs.harvesterhci.io/v0.3/troubleshooting/os/#how-can-i-install-packages-why-are-some-paths-read-only

**Comment by bk201** [comment]
The master ISO should contain the fix to make `/boot` writable in `debugrw` mode now.
Description of https://github.com/harvester/os2/pull/18 contains test plans.

**Comment by TachunLin** [comment]
Verified fixed on master-d05a6cc7-head. Close this issue. 

### Result
Now we can make `/boot` writable in `debugrw` mode
![image](https://user-images.githubusercontent.com/29251855/138877307-ce8e6aff-f36b-470f-a445-3693c783ea5c.png)

### Test Information
* Test Environment: Local qemu kvm machines with 1 nodes
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. ISO install harvester 
2. Reboot harvester machine
3. Follow the guide to enable [rw ](https://docs.harvesterhci.io/v0.3/troubleshooting/os/#how-can-i-install-packages-why-are-some-paths-read-only)mode. Skip the /oem/91_hack.yaml workaround.
4. Run `mount | grep overlay` there should be no overlaid directories.
5. Write a file in /boot folder

### Additional Context 
![image](https://user-images.githubusercontent.com/29251855/138878141-1b5359b7-be16-453a-9cbe-0cc74fc19c41.png)
