### ISSUE TITLE
[BUG] unable to remove Machine from scaled cluster

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1389]
**Describe the bug**
After creating an rke2 cluster from Rancher 2.6.1-rc11 using the Harvester node driver, I clicked the + to add a 4th node to the cluster. It failed to deploy, so I tried deleting it from the cluster. It won't delete. I tried removing the cluster entirely but the Machine in question is stuck in deleting, yet it was deleted from the provider (harvester)

**To Reproduce**
Deploy rke2 cluster on Harvester using Rancher
click + to add another node within the cluster in cluster manager
Wait for the node addition to fail
Try deleting the node from the cluster or Machine or the entire cluster

**Expected behavior**
a clean node deletiong

**Environment:**
 - Harvester ISO version: post rc1 master-c4a76706-head
 - Underlying Infrastructure: Dell R620

**Additional context**
Error in the UI for reference - looks like the same from it failing to deploy
<img width="1411" alt="Screen Shot 2021-10-08 at 9 06 02 AM" src="https://user-images.githubusercontent.com/5146963/136562999-3bf2e03e-5505-4c1d-a869-b1876df9cf4a.png">

**Comment by guangbochen** [comment]
It may get blocked by the CR finalizers, u may select to edit as YAML and remove those finalizers accordingly to force delete it, or u may try `kubectl delete $CR --force --grace-period=0`

**Comment by FrankYang0529** [comment]
I tried to reproduce the bug, but I can't initialize RKE2 in harvester. I got error like the following.

![Screen Shot 2021-10-25 at 8 54 53 PM](https://user-images.githubusercontent.com/4927361/138698942-889d626f-dd28-4fce-b6af-46e3373ab914.png)

When I tried to debug in the VM, I got error message. `[ 6651.811118] cloud-init[1382]: [ERROR]  Error while connecting to Rancher to verify CA necessity. Sleeping for 5 seconds and trying again.`

I will survey how [cluster-api](https://cluster-api.sigs.k8s.io/introduction.html) and [docker-machine-driver-harvester](https://github.com/harvester/docker-machine-driver-harvester) work.

**Comment by guangbochen** [comment]
@futuretea can u please help to take a quick look and give some advice to @FrankYang0529 if possible, thanks.

**Comment by FrankYang0529** [comment]
I can reproduce this issue. When I provision a 4th node failed and try to delete it, VM in Harvester has been deleted, but the node status doesn't change.
![Screen Shot 2021-11-08 at 9 45 03 AM](https://user-images.githubusercontent.com/4927361/140671811-e95e51ca-f372-41ff-9456-879a08061483.png)
![Screen Shot 2021-11-08 at 9 44 53 AM](https://user-images.githubusercontent.com/4927361/140671851-c4908446-ab28-4a71-82ea-a48317f26d0e.png)

**Comment by guangbochen** [comment]
**To Test** (and should close https://github.com/rancher/rancher/issues/35398 if passes)
- Create a 3-node RKE2 cluster on Harvester through node driver with Rancher v2.6.3-rc1
- Wait for the nodes to create.
- Since the resource is not enough, a node can't be scheduled successfully. Wait for the provisioning failed.
- Delete the provisioning failed node.
- Machine CR should be removed successfully if the cluster is deleted.

**Comment by FrankYang0529** [comment]
> **To Test** (and should close [rancher/rancher#35398](https://github.com/rancher/rancher/issues/35398) if passes)
> 
> * Create a 3-node RKE2 cluster on Harvester through node driver with Rancher v2.6.3-rc1
> * Wait for the nodes to create.
> * Since the resource is not enough, a node can't be scheduled successfully. Wait for the provisioning failed.
> * Delete the provisioning failed node.
> * Machine CR should be removed successfully.

Following the above steps, I still can't delete `Machine` CR.

* If trying to remove provisioning failed nodes, `HarvesterMachine`, `Job`, and `VirtualMachine` are removed, but they will be created again after a while. Also, `Machine` CR will be back to provisioning state again.
* If trying to remove the whole cluster, all nodes including the provisioning failed node can be deleted.
* If trying to add annotation `provisioning.cattle.io/force-machine-remove: "true"` to `HarvesterMachine` and deleting the failed node, the result is the same as the first case. `HarvesterMachine`, `Job`, and `VirtualMachine` are removed, but they will be created again after a while. Also, `Machine` CR will be back to provisioning state again.

**Comment by FrankYang0529** [comment]
After discussing with @guangbochen, we think the behavior is expected. `MachineDeployment` CR is like a `Deployment` CR for `Machine`. When we fail to provision a node and delete it, `MachineDeployment` will do its best effort to make sure the count of running `Machine` is equal to `MachineDeployment.spec.replica`. So we can see `HarvesterMachine` will be created again.

* If we want to totally remove `Machine` CR, we need to modify `count` in `Cluster`. After modifying `count` in `Cluster`, provisioning failed `Machine` will be removed.
* If harvester doesn't have enough resources for `Machine` CR and we remove something to make sure it has enough resources, `Machine` CR can be back to running state.
