### ISSUE TITLE
task: trigger the ISO build with the new Harvester commit

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1395]
Currently, the ISO only builds on either `harvester/harvester-installer` change or the nightly build. It should be triggered (and gated in the future) the `harvester/harvester` build as well. Otherwise, we will get the latest ISO with an older version of Harvester.

REF: https://github.com/harvester/harvester/issues/1351#issuecomment-939056608

**Comment by w13915984028** [comment]
Target:
  When new commit is merged into master, the harvester ISO needs to be built and put into release.

Solution:
  In drone CI, add triggers on "push" event, so as to build and upload ISO.
 
In local test environment, the "Merge pull request" triggers build-iso, in last step, it upload the iso, please skip the error, as there is no related google_auth_key. 
 
![image](https://user-images.githubusercontent.com/31133476/140044635-26bdcd51-3ba1-40f9-b5fd-05cee30feba7.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/pull/1506
ISO build of the Harvester repo is available via https://drone-publish.rancher.io/harvester/harvester/430/3/3

**Comment by gitlawr** [comment]
One of the two builds failed: https://drone-publish.rancher.io/harvester/harvester/429/3/2
The reason is unclear. Let's keep an eye on it.
