### ISSUE TITLE
Ejecting non-existed CD-ROM causes VMI creating

### ISSUE THREAD

**Issue by thxCode** [harvester/harvester#140]
**Problem:**
According to the current `ejectCdRom` implement,

https://github.com/rancher/harvester/blob/788d1a08a9e349d1d57238b73a8d7e687624ebee/pkg/api/vm/handler.go#L104-L114

if we pass a non-existed CD-ROM name to VM `ejectCdRom` action, it will delete the existing VMI. The template resource(VM) has not changed, so the generated resource(VMI) should not be recreated.

**Solution:**

We can enhance the `ejectCdRomFromVM` to validate the non-existed CD-ROM name.

**Comment by gitlawr** [comment]
Validated that ejecting a non-existing cdrom does not trigger VMI recreation
