### ISSUE TITLE
[BUG] Read-only user was able to manage API actions

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1406]
**Describe the bug**
Read-only user was able to manage API actions, e.g stop/restart/start VMs

**To Reproduce**
1. import the downstream Harvester to the Rancher
2. create a `read-only` user and assign it to the `default` project
3. login as the `read-only` user and found the user was able to use the API actions.

![image](https://user-images.githubusercontent.com/4569037/136691117-deb308c7-b05f-4cd7-ad36-e520d306d0d7.png)

**Expected behavior**
- Read-only users should not be able to manage resources through the API actions.

**Environment:**
 - Harvester ISO version: v0.3.0-master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare-metal

**Additional context**

**Comment by gitlawr** [comment]
With the fix, there's one thing that needs to be checked on the UI side @WuJun2016 :

For a read-only user, actions are not available in volume APIs, but UI still shows the export action. A js error will pop up if the action is performed.
![image](https://user-images.githubusercontent.com/5697937/137092210-86d77a51-2817-4a9d-bd78-91134ff29260.png)

![image](https://user-images.githubusercontent.com/5697937/137091860-7fc997f2-0e2a-4a97-87aa-f5029691f09a.png)

**Comment by TachunLin** [comment]
@guangbochen, @WuJun2016 Verified on master-ebfbf44a-head. 
Read-only user can't manage API actions now but still remain some settings in volume and images page

### Result

After checking, Read-only user can't do API management actions on VM, Image and Volume.
While for volume and images , there's still UI settings remains like **"export to image"** in Volume and **"create virtual machine"** in images. But read-user can't actually do these actions. 

Personal suggestion is we can verify it again after all relating read-only user UI settings have hided. 
Thus move it to review pipeline.  

Display export to image to read-only user
![image](https://user-images.githubusercontent.com/29251855/138629271-3be58a86-ec4f-46ba-9ca1-9840c0403566.png)

Display create virtual machine to read-only user
![image](https://user-images.githubusercontent.com/29251855/138629687-ebec6cbf-399a-4c07-894c-97c13216a72a.png)


### Test Information
* Test Environment: Provo bare machines 3 nodes (hpd8s7, hpd8s8, hpd8s9 in RackD8)
* Harvester version: master-ebfbf44a-head

### Verify Steps
Follow the [v0.3.0 document ](https://docs.harvesterhci.io/v0.3/rancher/virtualization-management/) to install Rancher 2.6.1 and import existing Harvester  

1. Create project-readonly user in Rancher
2. Open Harvester in Rancher 
3. Access to default project in Projects/Namespaces 
4. Assign project-readonly user with read-only permission
5. Logout admin and login with read-only user
6. Open Virtual machine page, check setting menu of any vm
7. Open Images page, check setting menu of any images
8. Open Volumes page, check setting menu of any volumes

### Additional Context 

Read only user API action and UI settings screenshot

Virtual machine with no API management and UI settings
![image](https://user-images.githubusercontent.com/29251855/138629554-0d8c032b-a7fe-4031-9f7b-d6c7a5baad2e.png)

Edit volume UI settings
![image](https://user-images.githubusercontent.com/29251855/138629271-3be58a86-ec4f-46ba-9ca1-9840c0403566.png)

Ready-only user run export to image
![image](https://user-images.githubusercontent.com/29251855/138629381-59d73b8d-a594-4082-8c31-63e651168744.png)

Edit images UI settings
![image](https://user-images.githubusercontent.com/29251855/138629687-ebec6cbf-399a-4c07-894c-97c13216a72a.png)

Read-only user try to create virtual machine 
![image](https://user-images.githubusercontent.com/29251855/138629990-b99abdca-1f20-4624-9e3d-7ee47ec8fdfd.png)

**Comment by guangbochen** [comment]
@WuJun2016 seems like `For a read-only user, actions are not available in volume APIs, but UI still shows the export action. A js error will pop up if the action is performed.` is still exists, we should fix it properly. 

Additionally, @TachunLin I think we can close this issue once the above bug is fixed, and feel free to file a new issue if any similar bugs occur, thanks.

**Comment by TachunLin** [comment]
Close this issue since currently read-only user are not able to manage API actions in vm, images and volumes.
The remaining UI settings will raise a new issue to tracking accordingly.
