### ISSUE TITLE
[BUG] There's no way to change user password in single cluster UI

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1409]
**Describe the bug**
I don't find a UI page for updating the password of the admin user

**Environment:**
 - Harvester ISO version: v0.3.0-rc2

**Comment by gitlawr** [comment]
Workaround:
Go to the API-UI view via <SERVER_URL>/v3/users, and click `changepassword` action button.

**Comment by WuJun2016** [comment]
In a single cluster, the id cannot be obtained in the v3/principal interface. 

- data returned from single clusters
![image](https://user-images.githubusercontent.com/24985926/136878384-64752f79-7611-4bd0-8c7d-a000a7909abb.png)


- data returned from multiple clusters
![image](https://user-images.githubusercontent.com/24985926/136878736-cea9447c-1c1a-4c92-8f23-2adb44fcdb7b.png)

I think they should return the same data format。   @gitlawr

**Comment by guangbochen** [comment]
@WuJun2016 the API part should be resolved with the `master-head` version, can u PTAL and fix it on the UI part, thanks.
![image](https://user-images.githubusercontent.com/4569037/145368499-6f4bd8d2-c87a-4155-a112-13ade54f9ec5.png)

**Comment by noahgildersleeve** [comment]
Tested with master-655c251a-head. This does change the password, however you get an error on submitting the API request. Is that acceptable @guangbochen @yasker ?
![2021-12-09_10-13](https://user-images.githubusercontent.com/83787952/145452586-a063c640-04b5-418d-89b2-28675fa635c0.png)

**Comment by yasker** [comment]
@guangbochen what's the expected behavior here? Do we have UI or are we asking users to use API to change the password?

**Comment by WuJun2016** [comment]
test step:
![image](https://user-images.githubusercontent.com/24985926/145500766-ba080b59-3f36-4e4d-97fc-d78e27f0ab7d.png)
![image](https://user-images.githubusercontent.com/24985926/145500791-fe12f16c-9dc2-40cc-927e-99a70d337287.png)


@yasker   @noahgildersleeve

**Comment by noahgildersleeve** [comment]
The button is there, but when you submit the request you get a parsing error.

> Tested with master-655c251a-head. This does change the password, however you get an error on submitting the API request. Is that acceptable @guangbochen @yasker ? ![2021-12-09_10-13](https://user-images.githubusercontent.com/83787952/145452586-a063c640-04b5-418d-89b2-28675fa635c0.png)

**Comment by gitlawr** [comment]
@noahgildersleeve You don't need to go to the API-UI. It's a workaround before the fix.

To verify,
1. In Harvester UI, click the top-right avatar.
2. Select Account & API Keys.
3. Click the `Change password` button

**Comment by noahgildersleeve** [comment]
Tested in master-5d6f3db0-head. 
## Test Steps
1. Logged in with user
2. Changed password
3. Logged out
4. Logged back in with new password
5. Verified old password didn't work
