### ISSUE TITLE
[FEATURE] Support getting VIP automatically during PXE boot installation

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1410]
**Is your feature request related to a problem? Please describe.**

By version 0.3, it's required for users to provide the VIP and VIP hardware address manually in DHCP mode with PXE boot installation.

**Describe the solution you'd like**
Request the VIP during PXE Boot installation as what is done during ISO installation.

**Describe alternatives you've considered**

During ISO installation, we create the macvlan interface based on harvester-mgmt, which may not be created during PEX boot  installation.

**Additional context**

**Comment by FrankYang0529** [comment]
### Test Case

* Comment `vip` and `vip_hw_addr` in `ipxe-examples/vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2`
* Start vagrant-pxe-harvester
* Run `kubectl get cm -n harvester-system vip`
  * Check whether we can get `ip` and `hwAddress` in it
* Run `ip a show harvester-mgmt`
  * Check whether there is two IP in it and one is vip.

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head with vagrant ipxe-examples config. Tested with included test case


> ### Test Case
> * Comment `vip` and `vip_hw_addr` in `ipxe-examples/vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2`
> * Start vagrant-pxe-harvester
> * Run `kubectl get cm -n harvester-system vip`
>   
>   * Check whether we can get `ip` and `hwAddress` in it
> * Run `ip a show harvester-mgmt`
>   
>   * Check whether there is two IP in it and one is vip.
