### ISSUE TITLE
[BUG] Harvester not operational when DNS nameserver is not configured

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1412]
Installation method: PXE
Harvester 0.3.0

When installing Harvester with static network configuration and without specifying `os.dns_nameservers` in the `create-config` file the installation will proceed without errors but the cluster will never be fully functional. The Harvester UI will never work and additional servers fail to join the cluster.

This is difficult to troubleshoot because there is no indication to the user that the missing dns nameserver configuration causes many installation steps to fail.

> For Static Network, empty DNS would cause any further steps (NTP, Import SSH Key, ...) that require domain name resolving to fail.
See https://github.com/harvester/harvester/issues/1296#issuecomment-937394860

**Expectation:**
Installation should not proceed and error is  thrown if a configuration parameter that is critical for installation is missing.

**Comment by lanfon72** [comment]
Hi @janeczku, would you please provide the YAML file so that I can reproduce and narrow down the bug?

**Comment by noahgildersleeve** [comment]
Tested in master-177ab565-head.
### Verification Steps
1. Start new install
2. Setup static IP
3. Try to continue with no DNS server defined
### Expected Results
1. You should get an error that you must have a DNS server with static IP
![Screenshot from 2022-01-10 14-17-20](https://user-images.githubusercontent.com/83787952/148850221-d6a36d8c-c20b-44d5-8d21-270f96ee0058.png)
