### ISSUE TITLE
[BUG] Adding unpartitioned NVMe disks fails

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1414]
0.3.0

1. Create 3-node Harvester cluster with each node having multiple unpartitioned physical disks (NVMe)
2. Add first physical disk via Harvester ui -> Host -> Disks by selecting the physical device path, `/dev/nmve0n1`

**Expected result:**

Disk is partitioned, formatted and mounted successfully.

**Actual result:**

Block Device resource is constantly reconciled with errors.

Duplicate `blockDevice` resources of type `partition` are created.

```
lpedge01001:~ # kubectl get blockdevices.harvesterhci.io -A|grep 01004|grep 0n1
longhorn-system   1f986f71f84dded0a163dd7872ccee78   part   /dev/nvme0n1p1                                                                     lpedge01004   Active   3s
longhorn-system   2a69f39b69da2752373e6470680579d7   part   /dev/nvme0n1p1                                                                     lpedge01004   Active   33s
longhorn-system   719ce4fa2b2f67e538acb16fd9292e91   disk   /dev/nvme0n1                                                                       lpedge01004   Active   53m
```

Many errors are constantly logged in node-disk-manager.
Information for invalid disk names is looked up (`/dev/nvme0n11` is not a valid device or partition name!).

```
time="2021-10-11T13:30:53Z" level=info msg="debug: parent path nvme0n1"
time="2021-10-11T13:30:56Z" level=warning msg="failed to read disk uuid of /dev/nvme0n11 : exit status 2\n"
time="2021-10-11T13:30:56Z" level=warning msg="failed to get filesystem label for device /dev/nvme0n11, exit status 32"
```
[Untitled.txt](https://github.com/harvester/harvester/files/7322854/Untitled.txt)

**Comment by janeczku** [comment]
Root Cause:

Node disk manager constructs the partition name by simply appending the number "1" to the device path. This does not work for NVMe disks, as the partition number is separated from the device name by using a `p`: `/dev/nvme0n1p1` instead of `/dev/nvme0n11`.

https://github.com/harvester/node-disk-manager/blob/28f9c80cc31dda50efcf16500458f38e51f480ad/pkg/controller/blockdevice/controller.go#L222

**Comment by janeczku** [comment]
PR ready for review https://github.com/harvester/node-disk-manager/pull/16

**Comment by TachunLin** [comment]
@guangbochen, @janeczku 
This issue verified **not fixed** on master-d05a6cc7-head. Move this issue to review pipeline stage. 

### Result
Unpartitioned NVMe disks can be detected and partitioned. 
But failed to add and mount NVMe disks in host page. 
![image](https://user-images.githubusercontent.com/29251855/138704497-2bce24c3-3fd4-4115-83d0-d84c502ac286.png)


### Test Information
* Test Environment: Local qemu kvm machines with 3 nodes
* Harvester version: master-d05a6cc7-head

### Verify Steps

1. Use "qemu-img create -f qcow2" command to create three disk image locally
2. Shutdown target node VM machine
3. Edit qemu/kvm VM XML settings by either way:
    * Directly edit VM xml content in virt manager page
    * User virsh > edit domain id 
4. Add `<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>` to the first line
5. Add the following line to before the end of <domain> quote   
    
![image](https://user-images.githubusercontent.com/29251855/138705593-9934b091-1fbd-4a63-8b27-22f805ea35e1.png)

6. Start VM node 
6. Open Host page and edit the host config 
7. Click Disk -> Add disk to select available nvme disks


### Additional Context

Add three nvme disks in host page
![image](https://user-images.githubusercontent.com/29251855/138702675-0dc65034-ddb3-4d43-97c5-68b45d999e14.png)

Disk can be detected and full formatted
![image](https://user-images.githubusercontent.com/29251855/138702859-3ff8f22d-6b30-48cb-8e6e-3be2735c9486.png)

But fail to add disk
`Operation cannot be fulfilled on blockdevices.harvesterhci.io "ce524f41b75b3f89271bc6e95a82fe4a": the object has been modified; please apply your changes to the latest version and try again`

![image](https://user-images.githubusercontent.com/29251855/138703369-e0f1023b-3ba9-439b-8eec-99ab54bd4b2e.png)

**Comment by guangbochen** [comment]
@TachunLin this is a known common issue of the Rancher dashboard + k8s API, the error message states that the object is modified after we click the `Edit` host button and the UI won't reload the YAML content directly, and by clicking save we are sending the old version of the object so the k8s API rejects it, users can only resolve it by refresh the page or go back and click edit again.

**Comment by TachunLin** [comment]
Verified **fixed** on master-45e25939-head. Close this issue.

### Result
Unpartitioned NVMe disks can be detected, partitioned and mounted to harvester node. 
With `schedulable` and `running status`

![image](https://user-images.githubusercontent.com/29251855/142553133-1e67d4b0-1203-482f-be76-afa0e4a0066c.png)


### Test Information
* Test Environment: 3 nodes harvester on local kvm/qemu machines
* Harvester version: master-45e25939-head


### Verify Steps

1. Use `qemu-img create -f qcow2` command to create three disk image locally
2. Shutdown target node VM machine
3. Directly edit VM xml content in virt manager page
4. Add <domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'> to the first line
5. Add the following line before the end of <domain> quote
```
<qemu:commandline>
    <qemu:arg value="-drive"/>
    <qemu:arg value="file=/home/davidtclin/Documents/Software/qemu_kvm/node_3/nvme301.img,if=none,id=D22"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="nvme,drive=D22,serial=1234"/>
    <qemu:arg value="-drive"/>
    <qemu:arg value="file=/home/davidtclin/Documents/Software/qemu_kvm/node_3/nvme302.img,if=none,id=D23"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="nvme,drive=D23,serial=1235"/>
    <qemu:arg value="-drive"/>
    <qemu:arg value="file=/home/davidtclin/Documents/Software/qemu_kvm/node_3/nvme303.img,if=none,id=D24"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="nvme,drive=D24,serial=1236"/>
  </qemu:commandline>
```
6.  Start VM node
7.  Open Host page and edit the host config
8.  Click Disk -> Add disk to select available nvme disks
9.  Check disk can be mounted with `schedulable` and `running status` in edit node disk page

**Comment by Palando** [comment]
As a workaround you can create a partition manually and add it in the UI:

1. Login via ssh with user rancher
2. 'sudo gdisk /dev/sdX' and create partition
3. 'sudo mkfs.ext4 /dev/sdX1'
4. Add partition in UI

**Comment by TachunLin** [comment]
@Palando,  
Really appreciated for your suggestion, 
I tried your workaround it would be faster to add the sdX type disk on Harvester UI dashboard.
