### ISSUE TITLE
[BUG] unable to upload image by file

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1415]
**Describe the bug**

Trying to upload an image by File fails with Failed to wait for processing start in 60 seconds

https://user-images.githubusercontent.com/5146963/136810025-6a389a7d-cc9d-415a-b9cc-5a759bc02fbb.mp4

```
actions.js:23 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'includes')
    at actions.js:23
    at d (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.O.forEach.t.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at asyncToGenerator.js:21
    at y.request (actions.js:19)

```
**To Reproduce**
Try uploading an image by file (this was working and a few days later stopped working)

**Expected behavior**
Image Uploads
**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure: Dell R620

**Comment by abonillabeeche** [comment]
support bundle
https://drive.google.com/open?id=1-6H1z7YCViRMRM8GkfmSaokDslkY9gD9&authuser=alejandro.bonilla%40gmail.com&usp=drive_fs

**Comment by gitlawr** [comment]
Harvester version of the setup: master-c4a76706-head

**Comment by gitlawr** [comment]
Reproducible in v0.3.0.
It fails in single-cluster view, works in multi-cluster view.

**Comment by yarunachalam** [comment]
I also see the same issue upload image in multi-cluster view. @gitlawr - Does it work for you in multi-cluster view. @g
	
Failed
	testfile 	
0%
	- 	22 mins 	
	Failed to wait for processing start in 60 seconds

**Comment by lanfon72** [comment]
Tested on bare metal 3nodes that successful uploaded with 5.36G/5.43G .

Harvester version: **master-ebfbf44a-head**
dashboard option: **Auto**

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1415#issuecomment-948200449 and should be resolved in the next release.

For the current v0.3.0 version, u can either using multi-cluster UI or replace the single cluster UI settings with the following config(but this is just for validation purposes as the master-head UI is keep updating and may break from time to time.)
![image](https://user-images.githubusercontent.com/4569037/138667109-a53e2f07-681d-43dd-b1ac-c02a4a118675.png)
