### ISSUE TITLE
[FEATURE] Support management of node labels  for advanced scheduling of VMs

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1416]
In order to make use of [advanced scheduling features](https://kubevirt.io/2020/Advanced-scheduling-with-affinity-rules.html) for VM workloads, such as `nodeSelector` and `affinity` rules we need to be able to configure and manage the labels assigned to Harvester hosts.

Examples for the information we can encode with labels:

`topology.kubernetes.io/zone`: `Rack-A-11`
`node.kubernetes.io/instance-type`: `GPU`

**Describe the solution you'd like**
1. Host labels can be assigned during installation via `config-create` / `config-join` YAML.
2. Host labels can be managed post installation via the Harvester UI.
3. Host label information can be accessed in Rancher Virtualization Management UI.

**Comment by guangbochen** [comment]
Host labels are already configurable on the Harvester UI, @bk201 can u please help to check if we can add labels with the Harvester configure file.
![image](https://user-images.githubusercontent.com/4569037/138072013-50a31646-743d-4f93-8a3b-156153359a0c.png)

**Comment by bk201** [comment]
> Host labels are already configurable on the Harvester UI, @bk201 can u please help to check if we can add labels with the Harvester configure file. ![image](https://user-images.githubusercontent.com/4569037/138072013-50a31646-743d-4f93-8a3b-156153359a0c.png)

The `labels` and `taints` fields are removed when designing the Harvester configuration because I didn't see the need, do we want to add those fields back?
A workaround is to use `os.write_files` to create RKE2 configuration files.

**Comment by guangbochen** [comment]
Yep, I think allowing users to configure directly with Harvester config file is what is expected here.

**Comment by johnliu55tw** [comment]
Thought about using [rke2-90-harvester-agent.yaml and ](https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rke2-90-harvester-agent.yaml) and [rke2-90-harvester-server.yaml](https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rke2-90-harvester-server.yaml), but modifications to labels added this way did not survive a reboot. RKE2 uses configs in these files as CLI args so labels are reverted whenever system rebooted. [REF](https://docs.rke2.io/install/install_options/install_options/#configuration-file)

**Comment by bk201** [comment]
> but modifications to labels added this way did not survive a reboot.

@johnliu55tw  Could you verify if this is true? `/etc/rancher` is persistent so it should survive. Thanks.

**Comment by johnliu55tw** [comment]
@bk201 By modification I meant modifying the label from GUI. After a reboot, the label got reverted to its default value (specified in the config file).

**Comment by johnliu55tw** [comment]
Testing out whether the labels added by [rancherd-config.yaml](https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-config.yaml) would only be applied **once**, when a node is creating/joining a cluster:
- For the `cluster-init` (creating cluster) role Node, the labels will be applied, and changes made from GUI **would persist** after node reboot. :+1: 
- For the `agent` (joining cluster) role Node, the labels will be applied, but changes made from GUI **would not be persisted** after node reboot. The value would change back to the value set by the config file.

**Comment by johnliu55tw** [comment]
Asking Rancherd people: https://github.com/rancher/rancherd/issues/16

**Comment by johnliu55tw** [comment]
Seems like Rancherd adds a config file to `/etc/rancher/rke2/config.yaml.d/` that causes RKE2 to overwrite the label's value whenever the agent Node rebooted:
```
# cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml
{
  "node-label": [
    "harvesterhci.io/managed=true",
    "rancherd-label=installer-provided", # The label added by Installer
    "rke.cattle.io/machine=f7e54ccb-6b90-4127-9a4f-b8f85d404a9b"
  ],
  "server": "https://192.168.122.242:9345",
  "token": "harvester"
}
```

To prohibit the overwriting behavior, I'm thinking using `/oem/99_custom.yaml` to **clear `node-label` config if the Node has been bootstrapped**. We could tell whether it's bootstrapped by seeing if file `/var/lib/rancher/rancherd/bootstrapped` exists:
```yaml
# /oem/99_custom.yaml
stages:
  fs: # Need to be in "fs" stage to read the bootstrapped file
  - if: '[ -f /var/lib/rancher/rancherd/bootstrapped ]'
    files:
    - path: /etc/rancher/rke2/config.yaml.d/99-remove-predefined-node-label.yaml
      permissions: 384
      owner: 0
      group: 0
      content: 'node-label: []'
```

Because it's the last config file being processed (`99-...`), the final value of `node-label` after merging all the config files would be an empty array, thus not overwriting any Node labels.

I've tested this out and it seems to work. @bk201 what do you think?

**Comment by bk201** [comment]
Another option is using a systemd drop-in to add an `ExecStartPre=` option to rke2-server/agent services.
In this case, the node-label reset doesn't need to wait for a reboot.

**Comment by johnliu55tw** [comment]
Right, besides reboot, restarting RKE2 service would also reload the configs.

**Comment by johnliu55tw** [comment]
For anyone testing this feature, please check https://github.com/harvester/harvester-installer/pull/167.

**Comment by lanfon72** [comment]
### Verification
- [x] Host labels can be assigned during installation via config-create / config-join YAML.
- [x] Host labels can be managed post installation via the Harvester UI.
- [x] Host label information can be accessed in Rancher Virtualization Management UI.


Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: **master-b7e562d3-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6-4375161a2780765f0fd58af2936876a3e0254741-head**

### Verify Steps:
1. Install Harvester with config file with additional labels
2. Navigate to Host details then navigate to Labels in Config
3. Check additional labels should be displayed [1]
4. Use **edit config** to modify labels
5. Reboot the Node and wait until its state become active
6. Navigate to Host details then Navigate to Labels in Config
7. Check modified labels should be displayed [2]
8. Install Rancher with any nodes
9. Navigate to _Virtualization Management_ and import former created Harvester
10. Wait Until state become **Active**
11. Click _Name_ field to visit dashboard
12. repeat step 2-7, and both compare from Harvester's dashboard (accessing via Harvester's VIP)
