### ISSUE TITLE
[FEATURE] Support topology aware scheduling of guest cluster workloads

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1418]
**Describe the solution you'd like**
We would like to be able to configure advanced scheduling of pods in guest clusters, based on the topology and physical architecture of the Harvester cluster.

This would allow - among others - to make use of:

- [Automatic spreading of pods across failure domains by the Kubernetes scheduler](https://kubernetes.io/docs/reference/labels-annotations-taints/#topologykubernetesiozone).
- Scheduling of pods to specific physical nodes based on labels

**Implementation Details**

The Harvester CPI controller will propagate the topology encoded in the Harvester cluster node labels to the guest cluster nodes:

At a minimum the following node labels would be propagated:

Harvester node -> Guest cluster node

- `topology.kubernetes.io/zone` -> `topology.kubernetes.io/zone `
- `topology.kubernetes.io/region` -> `topology.kubernetes.io/region`

Related issues:
https://github.com/harvester/harvester/issues/2317
https://github.com/harvester/harvester/issues/2316

**Comment by janeczku** [comment]
Related: https://github.com/harvester/harvester/issues/1416

**Comment by alexdepalex** [comment]
This sounds like a great feature for v1.0.3 :)

**Comment by janeczku** [comment]
PR https://github.com/harvester/cloud-provider-harvester/pull/20

**Comment by chrisho** [comment]
@WuJun2016 The host management page needs open `topology.kubernetes.io/zone` and `topology.kubernetes.io/region` , thx.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-08af3d7c-head` (07/06) with cloud provider v0.1.4. Close this issue.

### Result
The topology encoded in the Harvester cluster node labels
![image](https://user-images.githubusercontent.com/29251855/177771658-1e3a8336-61c7-459d-9d4f-19e626ce9f23.png)

Can be correctly propagated to the additional node of the RKE2 guest cluster
![image](https://user-images.githubusercontent.com/29251855/177757013-d04214d3-3f70-4331-b4ab-663e19e2a816.png)

![image](https://user-images.githubusercontent.com/29251855/177757261-da51ac4e-806b-48a0-ac32-f2b4c10d3e0b.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-08af3d7c-head
* Rancher version: v2.6.5
* Kubernetes version: v1.23.7
* Cloud provider version: rancher/harvester-cloud-provider:v0.1.4

### Environment Preparation
1. Prepare Harvester cluster 
2. Create Rancher 
3. Import Harvester from Rancher

### Verify Steps
1. Environment preparation as above steps
2. Access Harvester node config page 
3. Add the following node labels with values
 - topology.kubernetes.io/zone
 - topology.kubernetes.io/region
4. Provision an RKE2 cluster 
5. Wait for the provisioning complete
6. Access RKE2 guest cluster 
7. Open Workload deployments
8. Edit the yaml of cloud provider 
![image](https://user-images.githubusercontent.com/29251855/177773323-2152dd4e-9b8e-431a-ab5b-a72f1bc94f6a.png)
9. Replace the image version to `rancher/harvester-cloud-provider:v0.1.4`
![image](https://user-images.githubusercontent.com/29251855/177774896-4c2cef6c-148b-4366-a822-c859416b3f34.png)
10. Delete the original v0.1.13 cloud provider deployment to let the latest one can be created correctly
11. Access the RKE2 cluster in Cluster Management page 
12. Click + to add another node 
![image](https://user-images.githubusercontent.com/29251855/177774100-63c1a229-19d4-45f7-bd4e-8d2453c9149f.png) 
13. Access the RKE2 cluster node page
![image](https://user-images.githubusercontent.com/29251855/177774234-ed001086-75a2-46e7-9638-0771cc790fad.png)
14. Wait until the second node created
![image](https://user-images.githubusercontent.com/29251855/177774368-0c8b6ac1-15f0-4a64-8945-85551dc85e4f.png)
15. Edit yaml of the second node 
16. Check the harvester node label have propagated  to the guest cluster node 
![image](https://user-images.githubusercontent.com/29251855/177774559-8f278b2d-fff0-48ec-a62f-ceb3a9da8cc3.png)
