### ISSUE TITLE
[Question] Change network settings after install?

### ISSUE THREAD

**Issue by seanb4t** [harvester/harvester#1419]
For instance, I set up secondary bond interfaces incorrectly, can this be changed after install? Or do I need to do a full reinstall again?

**Comment by alexdepalex** [comment]
You can change it manually for testing, or alter the configuration YAML files in `/oem` to make it persistent.

**Comment by seanb4t** [comment]
I found the testing bit, wasn't familiar with the distro , but some grepping around found the /etc/sysconfig/network entries
