### ISSUE TITLE
[BUG] ui is not automatically refreshed.

### ISSUE THREAD

**Issue by shangma** [harvester/harvester#1420]
**Describe the bug**
UI is not auto refreshed after user's action, say, creating an image or creating an vm in v0.3.0.

**Expected behavior**
UI is automatically refreshed after user's action, say, creating an image or creating an vm.

**Environment:**
 - Harvester ISO version: v0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): qemu/kvm

**Comment by guangbochen** [comment]
most likely this should be an issue related to the WebSocket connection, u can resolve it by either refresh the page or re-enable the cert.
![image](https://user-images.githubusercontent.com/4569037/137248830-9052327c-c482-4c0f-9aac-10a2652b3ee1.png)

**Comment by WuJun2016** [comment]
Close,  Feel free to open it if you have any questions.
