### ISSUE TITLE
How is Harvester 0.3.0  deployed by HELM? Urgent urgent[Question]

### ISSUE THREAD

**Issue by hellocloudnative** [harvester/harvester#1421]
How is Harvester 0.3.0  deployed by HELM? Urgent urgent

**Comment by guangbochen** [comment]
Helm deployment currently is not officially supported as various OS and k8s distro will encounter different issues that will need to be addressed case by case, also the purpose of the Harvester is to leverage the befits of k8s but without introducing the complexity and knowledge of the k8s themselves to the normal users.

For testing and evaluation purposes u can try out the https://github.com/harvester/harvester/tree/master/deploy/charts/harvester and please note the Rancher is also required to be installed in the `cattle-system` namespace for the Harvester.

Refer:
https://github.com/harvester/harvester-installer/blob/master/manifests/harvester.yaml

**Comment by hellocloudnative** [comment]
Not Found
Type: harvesterhci.io.management.cluster

**Comment by hellocloudnative** [comment]
Rancher 2.6.2, which I deployed at the K3s helm, started up completely fine, but when I added harvester clusters, the UI displayed:

Not Found
Type: harvesterhci.io.management.cluster

@guangbochen

**Comment by hellocloudnative** [comment]
#1542

**Comment by hellocloudnative** [comment]
@guangbochen  I use https://github.com/harvester/harvester-installer/blob/master/manifests/harvester.yaml deployment harvester 3.0, The rancher 2.6.2. Harvester successfully added Rancher, but my screen still shows this:
![image](https://user-images.githubusercontent.com/32674956/141934256-0b0f688c-d69e-4765-a234-1b44d393583c.png)
![image](https://user-images.githubusercontent.com/32674956/141934291-97a3ee86-f084-4f0d-becb-14e647b554d0.png)

**Comment by guangbochen** [comment]
The manifest is correct and u may need to check the Harvester or Rancher API server logs to identify the issue properly, Harvester API is exposed through the Rancher server by leveraging its aggregated API feature and therefore u will be able to access the Harvester UI properly.  You would be expecting to see the apisevice CR resources as below if it was setup properly:
```
$ kubectl get apiservices.management.cattle.io harvester -oyaml
apiVersion: management.cattle.io/v3
kind: APIService
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/3yQwU6EMBCG32XO7JZFFrI8hPHgzXiYtr9QA5R0Zolmw7ubcjCrJh7b+fJ//8yNJih7VqbuRjzPUVlDnCU/o32HU4EeU4hHx6ojjiGa4KmjgdMKUaQDL0GQ1uBAW0EuYU94DhNEeVqom6/jWNDIFuO/uQPLQB1V1rqmaqq29Rd/qtpzDb40vuayqbkpH+qyhD23bbbNPOG+TP6TBS5rFtbhKeEtfECoeyGznsw3aKgg41kGGzl5Q6/Fzv8F80TgEvTxl+vAfZ/Q79vSPSQLu5+kfIpi2ssp6zVfYdu+AgAA///MSg2gfAEAAA
    objectset.rio.cattle.io/id: harvester-apiservice
  creationTimestamp: "2021-11-08T03:44:47Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: 2bbc626277d9d12754ea96d4a064a603400eb577
  name: harvester
  resourceVersion: "2572"
  uid: ea1961db-0272-4c4d-8f94-b6e226221a25
spec:
  pathPrefixes:
  - /v1/harvester/
  - /dashboard/
  paths:
  - /v1/harvester
  secretName: harvester-aggregation
  secretNamespace: harvester-system
status:
  serviceAccountName: harvester-api-service
  serviceAccountNamespace: cattle-system
```

You can refer to the https://github.com/harvester/harvester/pull/998 for more details if u are interested, currently `Helm` mode is not officially supported because it requires more developing and debugging skills so I would encourage us to use the ISO build if u can, thanks.

**Comment by hellocloudnative** [comment]
@guangbochen  Thank you very much, I would like to further debug and would like to help the community support helm way.

**Comment by hellocloudnative** [comment]
Harvester services in my Harvester cluster:

```
time="2021-11-16T08:19:13Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.23, not 10.43.219.189"
```
@guangbochen

**Comment by hellocloudnative** [comment]
![image](https://user-images.githubusercontent.com/32674956/141947901-3cd29bb2-1397-44a9-9a0f-22dbfe7d25f8.png)
There is another problem. I need to deploy rancher in a Harvester cluster. So far I have only created the cattle-system namespace in a Harvester cluster

**Comment by hellocloudnative** [comment]
![image](https://user-images.githubusercontent.com/32674956/141957288-cd6bd20a-a913-4754-8134-819b8c194c6e.png)
The Harvester API is accessible, but why isn't the UI displayed? @guangbochen

**Comment by hellocloudnative** [comment]
I seem to have found the problem. Providers recognize harvester clusters only when they are harvesters  
@guangbochen
