### ISSUE TITLE
[Question] What does ">-" mean in User Data?

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1427]
In relation to #1426 , what does it mean when a seemingly valid runcmd line within the User Data section is changed to include a new line before it with just ">-" (without quotes)?

As the previously referenced bug might suggest I've been playing with User Data, in particular runcmd to automate the setup of a VM. Whilst a couple of simple commands have worked, a longer string (also including colons which I've read are problematic) has ended up being split into three lines with the first line being the ">-" characters.

Which library is the UI currently using? I'm hoping that if I can find out why the ">-" characters are being introduced that will reveal the solution (and/or perhaps I'll need to log another bug).

Thanks.

Harvester 0.3.0

**Comment by lanfon72** [comment]
`>` is Block Style Indicator and `-` is Block Chomping Indicator, you can test them in [here](https://yaml-multiline.info/)

**Comment by simonflood** [comment]
Thanks, so something in Harvester, or more likely the library it's using, is splitting up my long command into two lines which then includes these indicators. Will do some more testing.

**Comment by simonflood** [comment]
It seems that lines with total length (i.e. including any preceding spaces and/or hyphens) are incorrectly split every 80 characters. This is most notable if using a Base64 encoded string as content within write_files section. Will now log a bug.

**Comment by simonflood** [comment]
In repeating tests when writing up a bug things now seem to be working as expected, in particular my long runcmd is now working (with the the long command being split onto two lines with an additional ">-" line preceding). Harvester is still the same with the only thing changed is I restarted my NUC. I'll cancel the bug report and keep an eye on things.
