### ISSUE TITLE
[BUG] Should not be possible to add parent device of existing partition as disk

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1430]
Harvester 0.3.0

1. Setup a Harvester host with an additional disk that has GPT partition table and a single ext-4 partition
2. Navigate to Hosts and select Host -> Edit Config -> Disks
3. Click Add Disk
4. Select the disk device path of the additional disk, e.g. `/dev/sda` instead of `/dev/sda1`
5. Click Save

<img width="1489" alt="Screenshot 2021-10-14 at 18 34 23" src="https://user-images.githubusercontent.com/3813921/137360750-64f63409-e952-4094-8151-7ef0a631f702.png">

Expected:
User should not be allowed to add the parent disk device when there are existing partitions

Actual:
User is allowed to add the disk and save changes.

When navigating to Host -> Status -> Disks the following error is permanetly displayed:

> cannot mount parent device with partitions

<img width="1653" alt="Screenshot 2021-10-14 at 18 43 36" src="https://user-images.githubusercontent.com/3813921/137360845-449a690e-5073-454b-af94-132fd5901e25.png">

**Comment by alexdepalex** [comment]
@janeczku I observe different behavior on 2 systems. The first one has existing partitions that were created manually and where the partition label is `Linux filesystem`. On this configuration, both the partition and the parent device are selectable.

On the second system, the partitions were probably previously created by NDM, and there the partition label is set to `primary`. In this case, only the partition was selectable from the drop-down menu.

**Comment by weihanglo** [comment]
It might be a case that a user plugs a partitioned disk but wants to format it all without accessing the terminal console. If that is confusing, disabling or hiding all partitioned disks might be a solution.
cc @guangbochen WDYT?

**Comment by janeczku** [comment]
> It might be a case that a user plugs a partitioned disk but wants to format it all without accessing the terminal console.

It's a valid use case, but then we have to ensure that user-specifies "force format" to prevent running into the error situation above.

**Comment by janeczku** [comment]
Whats the reason we are exposing partitions to the user in the first place? Is there a use case of using multiple partitions on the same disk? 
I think we should hide partition management and only let use select physical disc. that will also prevent all the UX confusion that stems from treating partitions and physical disks like they were the same thing.

**Comment by guangbochen** [comment]
as per offline discussion, It is recommended to only support adding the entire disks from the UI to avoid ambiguity, for users who want to manipulate the partition disks they do it manually via the API-UI. cc @n313893254 @weihanglo

**Comment by belgaied2** [comment]
Was a choice made here ? Is there going to be a fix ?

**Comment by guangbochen** [comment]
@belgaied2 we will support to add raw block device directly after PR https://github.com/harvester/node-disk-manager/pull/26.

**Comment by WuJun2016** [comment]
According to the discussion, fixing in https://github.com/harvester/harvester/issues/1839.    cc @weihanglo

**Comment by guangbochen** [comment]
@janeczku @belgaied2 from the UI, we consider supporting provisioning raw block devices directly as extra disks; partition devices can only be added via the API or using the kubectl. If that's reasonable we may close this issue in favor of duplicate with https://github.com/harvester/harvester/issues/1839, thanks.

**Comment by WuJun2016** [comment]
Close the issue, because https://github.com/harvester/harvester/issues/1839 has already closed
