### ISSUE TITLE
[BUG] Harvester v0.3.0 unable to get local issuer certificate with https squashfs url

### ISSUE THREAD

**Issue by antonym** [harvester/harvester#1431]
**Describe the bug**
When iPXE booting, harvester root:live= entry fails to retrieve squashfs if URL is set to https. If switched to http, it can retrieve the file normally.

**To Reproduce**

Use root=live:https://releases.rancher.com/harvester/v0.3.0/harvester-v0.3.0-rootfs-amd64.squashfs as the source.

![Screen Shot 2021-10-14 at 11 58 55 AM](https://user-images.githubusercontent.com/245007/137364419-0d9f52da-bd82-4e55-ab11-c2faf815d344.png)

If root=live:http://releases.rancher.com/harvester/v0.3.0/harvester-v0.3.0-rootfs-amd64.squashfs is used instead, it boots up properly.

**Expected behavior**
Should be able to retrieve the squashfs over HTTPS

**Environment:**
 - Harvester ISO version: v0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Proxmox loading netboot.xyz menu, booted through that

**Additional context**

**Comment by bk201** [comment]
@antonym Could you try adding `rd.noverifyssl ` to the boot parameters? like
https://github.com/harvester/ipxe-examples/blob/b97d6fb3e3689cad10c075ba81852ebe8ab8af27/general/ipxe-create#L3
We missed it in our document.
The initrd doesn't contains SSL CA certs.

**Comment by lanfon72** [comment]
verified it works on PXE server with self-signed SSL certificate (IP-based).


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: N/A
* **ui-source** Option: not applicable
