### ISSUE TITLE
[feature] allow users to create cloud-config template on the VM creating page

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1433]
**Is your feature request related to a problem? Please describe.**
Allow the user to create cloud-config templates directly on the VM creating page and auto-select the last added one. 

**Describe the solution you'd like**
![image](https://user-images.githubusercontent.com/4569037/137444405-c198a162-31a5-438e-aac6-4af94018a7aa.png)

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-d05a6cc7-head. Close this issue.

### Result
User now can create user and network data template when create virtual machine
Created cloud-init template can be saved and auto selected to the latest one

![image](https://user-images.githubusercontent.com/29251855/139009117-9c191986-2253-4bff-b73f-962eabe2b2d9.png)

![image](https://user-images.githubusercontent.com/29251855/139008946-97f0d528-c5b9-4add-82d9-4105bd51f0c5.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-d05a6cc7-head

### Verify Steps
1. Create a new virtual machine
2. Click advanced options
3. Drop down user data template -> create new
4. Drop down network data template -> create new

**Comment by lanfon72** [comment]
@TachunLin the new option won't appeared on **master-d05a6c77** with `ui-source` option is **Bundled**.
Please aware this when verifying UI related changes.
