### ISSUE TITLE
[BUG] the node name is not showing customized one

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1434]
**Describe the bug**

**To Reproduce**
1. Go to the `Host` page and add a customized node name
![image](https://user-images.githubusercontent.com/4569037/137444776-ac0d60ab-504b-4721-8b5f-59713bff7b64.png)
2. Go to the VM page and add a new VM
3. Click the `Node Scheduling` tab and select assign the VM to a specific node, but the node name is still showing the original one instead of the customized node name. 
![image](https://user-images.githubusercontent.com/4569037/137444705-342aa947-3c46-4fc9-9639-44ed9d910a9f.png)

**Expected behavior**
The node name on the `Node Scheduling` page should be using the customized node name.

**Comment by TachunLin** [comment]
Verified **fixed** on master-d05a6cc7-head. Close this issue.

### Result
The customized node name can sync up the latest name in the node list of `Node Scheduling` tab when create virtual machine

![image](https://user-images.githubusercontent.com/29251855/139005275-feeab879-2160-4943-890f-aa818d7ff479.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-d05a6cc7-head

### Verify Steps
1. Add customized name for each each node
2. Create a new virtual machine
3. Open Node scheduling
4. Select Run vm on specific node
 
### Additional context
Customized node name in host page
![image](https://user-images.githubusercontent.com/29251855/139005469-f86c72df-1892-4ca9-9a24-9d97058e2c7e.png)
