### ISSUE TITLE
[FEATURE] better loadblancer config of Harvester cloud provider

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1435]
**Is your feature request related to a problem? Please describe.**
1. Create a guest k8s cluster via the Harvester node driver e.g rke2 with the Harvester cloud provider enabled.
2. Wait for the cluster to be ready and create a new service with the type of `loadbBalancer`.
3. Currently, users have to use annotations to config those cloud provider configs, we should add a better UX integration of it on the Rancher dashboard.

https://docs.harvesterhci.io/v0.3/rancher/cloud-provider/#load-balancer-request-parameters

<img width="1789" alt="lb-svc" src="https://user-images.githubusercontent.com/4569037/137464552-13d4ae38-4293-4774-8f85-d35949ddc555.png">

**Comment by n313893254** [comment]
Verify steps:
- Install rancher 2.6.1 by docker
- Go to global settings and replace ui-dashboard-index to https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
- Import harvester to rancher virtualization management
- Create a harvester cluster by harvester driver 
- Access the new harvester cluster from rancher cluster management
- Create a load balancer from service discovery -> services
- Check the "Add-on Config" tabs

Notes:
- The cluster created by the harvester driver and k8s version >= v1.21.4+rke2r4 shows the config.
- I changed the version check function which is used on create cluster page, we should test it both.

Additional context:
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/6147d0b2-4106-4f1b-a331-a4d337c1002a)

**Comment by TachunLin** [comment]
@n313893254 
Verified **Not fixed** on master-d21b9161-head with rancher 2.6.1
No `Add-on Config` display after replacing  ui-dashboard-index
Move this issue to review stage.

### Result
Create load balance page have no` Add-on Config` tab
![image](https://user-images.githubusercontent.com/29251855/140541604-f4c4f429-4e1e-4910-a974-519ce2f50072.png)

Version change in create cluster page have changed to `v1.21.6+rke2r1`
![image](https://user-images.githubusercontent.com/29251855/140541952-8e7b5cd1-7c8c-4622-a1b0-74ca81a813ac.png)


### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-d21b9161-head

### Verify Steps

1. Install rancher 2.6.1 by docker
2. Replace `ui-dashboard-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
![image](https://user-images.githubusercontent.com/29251855/140537130-c5dc23c7-cc1e-4711-823d-e240a96f2f75.png)

3. Import harvester to rancher virtualization management
4. Create a harvester cluster by harvester driver
5. Access the new harvester cluster from rancher cluster management
6. Create a load balancer from service discovery -> services
7. Check the "Add-on Config" tabs

**Comment by n313893254** [comment]
Sorry, ui-offline-preferred needs to change to Remote. Otherwise, Rancher still use local UI instead of the UI you are configuring in the remote.

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/de55b6eb-48b2-4fb3-a16e-be195dd0bdf7)

**Comment by TachunLin** [comment]
@n313893254, 
Verified `Not fixed` on master-d21b9161-head with rancher 2.6.2, Move it to review pipeline

After replacing `ui-dashboard-index `and set  `ui-offline-preferred` to `Remote`
![image](https://user-images.githubusercontent.com/29251855/140778188-616ac3d8-c374-42de-82b4-d8bf8c571ce3.png)

There is still no `Add-on Config` tabs found in Create LoadBalancer page
![image](https://user-images.githubusercontent.com/29251855/140778131-ed67a4eb-6914-4702-8c86-0116e6e64f5a.png)

Can you check or give a screenshot to specify the location in case of I miss anything. Thanks

**Comment by n313893254** [comment]
I can see the add-on config by following my verify steps, here is the screenshot with the location:

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/919a878f-2d12-4063-84e3-e4a213a539bb)

Maybe the UI still use the local UI file, can you check the console -> network to make sure the UI file has been requested from remote address? If you have any questions, please let me know. Thanks

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/3a34c6f9-1e2d-4c45-bfcd-c543a008205c)

**Comment by TachunLin** [comment]
@n313893254 ,
After replacing ui-dashboard-index and set ui-offline-preferred to Remote
There is no `add-on config` tab display on create load balance page

Open console-> network, I get a hint to press `ctrl+R` to reload page. 
By doing this step, the `add-on config` show up.   
![image](https://user-images.githubusercontent.com/29251855/141243397-af5f6bb1-851c-4c7b-bec5-bf49218614e2.png)

May I know is it a must have step from future issue verification or just only for this issue.

**Comment by TachunLin** [comment]
Verified **fixed** on master-119c2c48-head. Close this issue.

### Result
User can configure `port`, `IPAM` and `health check` related setting on `Add-on Config` page
![image](https://user-images.githubusercontent.com/29251855/141245366-799057f1-2aa7-4d7a-90d2-5e11541ddbc3.png)


### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-119c2c48-head

### Verify Steps
1. Install rancher 2.6.1 by docker
2. Replace `ui-dashboard-index` 
3. Change ui-offline-preferred to `Remote`
3. Import harvester to rancher virtualization management
4. Create a harvester cluster by harvester driver
5. Access the new harvester cluster from rancher cluster management
6. Create a load balancer from service discovery -> services
7. Re login rancher
8. Open create load-balance page
9. Click ctrl+R to refresh page
10. Check the "Add-on Config" tabs

### Additional Context
None

**Comment by n313893254** [comment]
> May I know is it a must have step from future issue verification or just only for this issue.

I think after replacing the ui-index, UI should refresh the page so that make sure the UI is what you want. How about enhancing this UX?
