### ISSUE TITLE
[FEATURE]  Allowing users to download backing images

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1436]
**Is your feature request related to a problem? Please describe.**
Allowing users to download the backing images from UI, so that those images can be shared accordingly.

Depends on: https://github.com/longhorn/longhorn/issues/3155

**Comment by shuo-wu** [comment]
The corresponding Longhorn backend API is `/v1/backingimages/{name}/download`

And the Longhorn UI PR is: https://github.com/longhorn/longhorn-ui/pull/519 (This PR also includes one upload-API-related modification, which fits the recent backing image refactoring)

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/189675005-a7509189-f0c3-42e4-b5a4-d8c1bc1f6341.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-a579442f-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create a Image `img1`
3. Click the details of `img1`, **Download** Button should be available
4. Click **Download** button, `img1` should able to be downloaded and downloaded successfully.
