### ISSUE TITLE
[BUG] Confusing instructions for importing Harvester into Rancher

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1437]
**Describe the bug**
Rancher 2.6.1

When importing a Harvester cluster into Rancher, the user is shown instructions:

**Expected:**

that explain how to import a Harvester cluster. E.g. the specific steps to be able to run the "kubectl" command in harvester.

**Actual:**

user is shown generic instructions to run the command on "an existing Kubernetes cluster running a supported Kubernetes version"

<img width="841" alt="Screenshot 2021-10-15 at 12 56 32" src="https://user-images.githubusercontent.com/3813921/137477163-0ef47d87-7965-4c3b-9dd6-9b2624231345.png">

**Comment by guangbochen** [comment]
identical to https://github.com/harvester/harvester/issues/1330
