### ISSUE TITLE
[BUG] Incorrect storage capacity information displayed on Host

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1438]
**Describe the bug**
Rancher 2.6.1 / Harvester 0.3.0

Have a node with multiple disks configured for LH storage.

**Expected:**
Information about storage capacity accounts for all disks.

**Actual:**

Information about storage capacity accounts only the storage of the default disk (/var/lib/longhorn/).

<img width="1430" alt="Screenshot 2021-10-15 at 13 09 01" src="https://user-images.githubusercontent.com/3813921/137478551-d1bf786a-bd50-4b75-9f69-d2397e6b161d.png">

<img width="1439" alt="Screenshot 2021-10-15 at 13 08 53" src="https://user-images.githubusercontent.com/3813921/137478570-e3f0c111-f018-441b-95da-c5fb46510402.png">

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/1253
