### ISSUE TITLE
[SECURITY] Harvester cloud provider credentials should not be stored as plain text

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1440]
Rancher 2.6.1
Harvester 0.3.0

When provisioning RKE2 clusters on Harvester the Kubeconfig for the Cloud Provider is currently stored inline, in the plain text field `cloud-provider-config` within the `cluster` object.

**Security implications**

- A user that has no access to Harvester but has permisisons to provision clusters on Harvester via Rancher, may intercept the Kubeconfig and thus gain direct access to Harvester API.
- An admin who wants to make use of RKE2 cluster templates  for Harvester would have to store the plain text Kubeconfig credential in the source code repository.

<img width="1634" alt="Screenshot 2021-10-15 at 16 27 47" src="https://user-images.githubusercontent.com/3813921/137513268-c5e9acc1-a615-4d7e-9afd-a10d6b618224.png">

**Expected Behavior**

Kubeconfig should not be handled in the UI and thus be exposed to User. Kubeconfig should also not be stored inline in a field of the Harvester `Cluster` resource (`provisioning.cattle.io/v1`) to allow secure usage of RKE2 cluster templates.

Instead, the Kubeconfig should be generated and injected on the server-side upon cluster creation request using the provided cloud credential.

** Additional Context **
https://github.com/rancher/rancher/issues/33611#issuecomment-901714497

**Comment by yasker** [comment]
@guangbochen We need to recheck to understand the implication and the way we can address it.
