### ISSUE TITLE
[FEATURE] Support setting hostname via DHCPv4 client

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1444]
**Is your feature request related to a problem? Please describe.**

Currently (0.3.0), the hostname is set by users manually or generated automatically in PXE boot installation if it's not provided.
Users might want to control nodes' hostname via DHCP server. We can provide an option to enable this hehavior.

**Describe the solution you'd like**

- Harvester configuration: add an option in networks to enable this feature:
  - Turn on `DHCLIENT_SET_HOSTNAME` flag to support this. See `/etc/sysconfig/network/dhcp`.
- Installer: add a check box to enable this behavior.

**Describe alternatives you've considered**

**Additional context**

A workaround is to use `os.write_files` to manually create a ``/etc/sysconfig/network/dhcp` file.

**Comment by Jellyfrog** [comment]
According to; https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#oshostname
this should already work (but it doesn't)

**Comment by yasker** [comment]
@bk201 does this work already?

**Comment by bk201** [comment]
> @bk201 does this work already?

No, `DHCLIENT_SET_HOSTNAME` is disabled by default in OpenSUSE. I'd suggest we add a configuration field in [network configuration](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#installnetworks) to turn this feature on specified networks.
The [document](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#oshostname) @Jellyfrog mentioned is a legacy from k3os, I will create a PR to remove that statement first.

**Comment by bk201** [comment]
@tjjh89017 Any concern if we enable this feature? Thanks.

**Comment by tjjh89017** [comment]
> @tjjh89017 Any concern if we enable this feature? Thanks.

It will rely on users' correct configuration of DHCP server.
if users have a correct DHCP server, there is not a problem for this feature.

**Comment by bk201** [comment]
We can have a configuration field to enable this feature. (disabled by default)

**Comment by tserong** [comment]
Summarising current work on this feature:

My initial implementation (https://github.com/harvester/harvester-installer/pull/717) added an option to the installer to enable `DHCLIENT_SET_HOSTNAME` as described above. When that option is enabled, if the DHCP server specifies a hostname, the system will use that when it boots up, and if the DHCP server doesn't specify a hostname, it'll fall back to using the manually set hostname. This works just fine, provided the DHCP server always exists, and always returns the same hostname.

@ibrokethecloud pointed out that we really don't want Harvester system hostnames to change after installation, which could happen if the DHCP server is later reconfigured, or breaks, or starts handing out different hostnames for whatever reason, and suggested taking the DHCP-supplied hostname (if set) _only_ during installation, and using that as the default for the hostname setting. This still allows the DHCP server to supply a hostname, but once only, when the system is first installed, which means the hostname is never going to accidentally change later. The end result of that discussion is the implementation in https://github.com/harvester/harvester-installer/pull/726. FTR, I prefer this version.

**Comment by irishgordo** [comment]
@tserong thanks for this feature :smile: :+1:  - this all looks good - I'll go ahead and close this out :smile: 

### Environment
* Harvester
  * Version: Harvester-v1.4-20240923 /  Version: v1.4-97e60e1-head 
  * Profile: QEMU/KVM
  * ui-source: Auto


### Verification
### 1 Node Cluster
1. :green_circle: iPXE/PXE Based Boot With Hostname Left Out Of Config Comes From DHCP Server Side
   
   <details>
   <summary> <i>Given</i> <code>os.hostname</code> is not present in the <code>config-create.yaml</code>
   </summary>
         <ul>
          <li>it should be pulling from DHCP as a first try place</li>
          </ul>
   </details>

   <details>
   <summary> <i>When</i> <code>dhcp.conf</code> gets modified to set the hostname
   </summary>
         <ul><li><code>option host-name "our-custom-host-name";</code> is included</li></ul>
   </details>

   <details>
   <summary> <i>Then</i> we observe that the `hostname` is set correctly both in UI & on node </summary>
   
   ![image](https://github.com/user-attachments/assets/fb62a29f-3f48-4507-974d-89ed8b7a3539)
   
   ![image](https://github.com/user-attachments/assets/38ffd7f3-2e76-4efa-8219-ac210e867153)
   
   </details>
1. :green_circle: iPXE/PXE Based Boot With Hostname In Config Works
   
   <details>
   <summary> <i>Given</i> <code>os.hostname</code> is present in the <code>config-create.yaml</code>
   </summary>
         <ul>
          <li>it should be using os.hostname once the node is up</li>
          <li><code>
              Warning: Permanently added '192.168.0.30' (ED25519) to the list of known hosts.
              (rancher@192.168.0.30) Password: 
              rancher@harvester-node-0:> cat /etc/host
              cat: /etc/host: No such file or directory
              rancher@harvester-node-0:> cat /etc/host
              host.conf    hostname     hosts        hosts.allow  hosts.deny   hosts.equiv  hosts.lpd    
              rancher@harvester-node-0:> cat /etc/hostname 
              harvester-node-0
              rancher@harvester-node-0:> exit
              logout
              Connection to 192.168.0.30 closed.
          </code></li>
          </ul>
   </details>
1. :green_circle: when installing interactive if dhcp.conf supplies hostname panel will pick it up
   
   <details>
   <summary> 
      <i>Given</i> dhcp.conf is supplying the hostname and install is interactive
   </summary>

    https://github.com/user-attachments/assets/9ec42dcd-0247-4da0-837a-a901ed6d7f50
   </details>
   


4. :green_circle: when interactive installing if hostname isn't going to be propegated from any dhcp.conf/dnsmasq/etc. , default panel should be empty to start for hostname
   
   <details>
   <summary> 
      When no hostname is provide upstream, panel interactively should be by default blank
   </summary>
   
   ![Screenshot from 2024-09-27 15-09-27](https://github.com/user-attachments/assets/5b90b308-b7d3-4e3e-9af2-4ad90c91e4bd)
          
    ![Screenshot from 2024-09-27 15-08-42](https://github.com/user-attachments/assets/9b9f6601-5912-4178-968b-ca2d5d9fdacd)
   </details>
