### ISSUE TITLE
Waiting for ValidatingWebhookConfiguration harvester-validator...

### ISSUE THREAD

**Issue by BugMosquito** [harvester/harvester#1448]
what's the meaning of this info?

**Comment by aland-zhang** [comment]
There may be a problem with the code and it is not possible to automatically generate a ValidatingWebhookConfiguration named Harvester validator and a MutatingWebhookConfiguration named Harvester mutator.

**Comment by ScionOfDesign** [comment]
Is there any workaround to this issue?
I'm trying to run Harvester as a Helm Chart on my Kubernetes cluster. Everything seems to start up fine, but the harvester node seems to get stuck on `level=info msg="Waiting for ValidatingWebhookConfiguration harvester-validator..."` before eventually restarting.
This is with `v1.1.1`.

It seems that for me the harvester-webhook reports `reflector.go:324] github.com/rancher/lasso/pkg/cache/cache.go:145: failed to list *v3.ManagedChart: the server could not find the requested resource (get managedcharts.meta.k8s.io`

**Comment by w13915984028** [comment]
As explained in https://github.com/harvester/harvester/issues/3777#issuecomment-1511019570, Harvester no longer supports `dev` mode, installed as a helm chart in original k8s cluster.
