### ISSUE TITLE
[BUG] Incorrect naming of project resource configuration

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1449]
Harvester 0.3.0
Rancher 2.6.1

Navigate to Virtualization Management, select Harvester cluster, navigate to Projects/Namespaces. 
Click on Create Project

Expected:
1. Can configure default resource limits for Virtual Machines
2. Can configure resource quota for resources relevant to VM management

Actual:

1.  Can configure "Container Default Resource Limit"
2. Can configure resource quota for resources not relevant for VM management, e.g. pods.

<img width="1448" alt="Screenshot 2021-10-18 at 14 46 48" src="https://user-images.githubusercontent.com/3813921/137733642-d51804a0-07a6-4f52-b41f-023225f2bde4.png">

<img width="1684" alt="Screenshot 2021-10-19 at 14 47 33" src="https://user-images.githubusercontent.com/3813921/137912572-039404fe-a701-428b-95cb-66b2c9c421b1.png">

**Comment by TachunLin** [comment]
Verified **Not fixed** on master-b5dadc82-head. Move this issue to review stage.

### Result
Still display `Container Default Resource Limit` in create project
![image](https://user-images.githubusercontent.com/29251855/140242678-93f6e309-db1f-496d-b180-617cf3febb1c.png)

Can still configure resource quota for resources not relevant for VM management (pods, replication controllers)
![image](https://user-images.githubusercontent.com/29251855/140242267-ac70c5d2-dc6a-4557-ad52-f6df3906ffb2.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-b5dadc82-head

### Verify Steps

1. Install rancher 2.6.1 by docker  
2. Import harvester to rancher virtualization management
3. Access harvester from rancher virtualization management
4. Create a project in Projects/Namespaces
5. Check the field

**Comment by n313893254** [comment]
My bad.  Because Dashboard does not merge the change.  The change needs to replace `ui-dashboard-index` to validate.

Verify Steps :
- Install rancher 2.6.1 by docker
- Go to global settings and replace `ui-dashboard-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
- Import harvester to rancher virtualization management
- Access harvester from rancher virtualization management
- Create a project in Projects/Namespaces
- Check the field

**Comment by TachunLin** [comment]
@n313893254 
Verified **Not fixed** on master-d21b9161-head with rancher 2.6.1
UI display remains unchanged after replacing `ui-dashboard-index` in rancher settings
Move this issue to review stage.

### Result
Create project shows `Container Default Resource Limit` 
![image](https://user-images.githubusercontent.com/29251855/140535585-224e363b-a418-4f57-8574-b702ef3099b1.png)

Resource quota page have `pods` and `replication controllers`
![image](https://user-images.githubusercontent.com/29251855/140535770-a52baf10-8a7d-444a-96a6-1345b604550a.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-d21b9161-head

### Verify Steps

1. Install rancher 2.6.1 by docker
2. Replace `ui-dashboard-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
![image](https://user-images.githubusercontent.com/29251855/140537130-c5dc23c7-cc1e-4711-823d-e240a96f2f75.png)

3. Import harvester to rancher virtualization management
4. Access harvester from rancher virtualization management
5. Create a project in Projects/Namespaces
6. Check the field 

### Additional Context
It seems can't access https://releases.rancher.com/harvester-ui/dashboard/latest/index.html 

![image](https://user-images.githubusercontent.com/29251855/140537319-b3977856-edec-41cd-af0f-af4d09e6a4ce.png)

**Comment by n313893254** [comment]
Sorry, `ui-offline-preferred` needs to change to `Remote`. Otherwise, Rancher still use local UI instead of the UI you are configuring in the remote.

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/8bf1e4bd-0d75-430e-9ea7-16a7a076eb55)

**Comment by TachunLin** [comment]
Verified **fixed** on master-d21b9161-head with rancher 2.6.2, Close this issue.

### Result
In create project page now change tab to `VM Default Resource Limit` 
![image](https://user-images.githubusercontent.com/29251855/140687954-2b7dd1a7-919e-4980-a69d-57d180cd3b1e.png)

In resource quota page now only contains `CPU limit`, `Memory Limit`, `CPU Reservation` and `Memory Reservation`
![image](https://user-images.githubusercontent.com/29251855/140688068-ce31071a-08a8-4e16-9e29-c1ab9b4c36d7.png)

![image](https://user-images.githubusercontent.com/29251855/140688190-45ef099b-13e8-4097-bfc3-2d7cd2ed15f7.png)


### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: master-d21b9161-head
* Rancher version: 2.6.2
* ui-dashboard-index: `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
* ui-offline-preferred: `Remote`

### Verify Steps

1. Install rancher 2.6.1 by docker
2. Replace `ui-dashboard-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
![image](https://user-images.githubusercontent.com/29251855/140537130-c5dc23c7-cc1e-4711-823d-e240a96f2f75.png)
3. Change ui-offline-preferred
4. Re login rancher again
5. Import harvester to rancher virtualization management
6. Access harvester from rancher virtualization management
7. Create a project in Projects/Namespaces
8. Check the field 

### Additional Context
None

**Comment by TachunLin** [comment]
@n313893254, may I know whether I need to change `ui-dashboard-index` and `ui-offline-preferred` for the upcoming rancher UI issues? Thank you.

**Comment by n313893254** [comment]
Sure
