### ISSUE TITLE
[BUG] Resource quota management not completely implemented in UI

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1450]
https://github.com/rancher/dashboard/issues/4412

**Comment by janeczku** [comment]
This issue must be addresses in both UI views:

- RKE2 Cluster Explorer
- Harvester Virtualization Management

**Comment by n313893254** [comment]
Verified **not fixed** on v2.6.3-rc1.

**Verify Steps**

1. Go to an Explore Cluster from the left-side menu
2. Go to Project/Namespaces page
3. Create a project with the following resource quota assigned:
```
CPU limit: 2000 (Namespace default: 1200)
CPU reservation: 1000 (Namespace default: 600)
```
4. Configure container default resource limit of:
```
CPU reservation/limit 100/200
Memory reservation/limit 64MB/128MB
```
5. Create two namespaces in the project
6. Create a workload in each namespace

** Result**
![image](https://user-images.githubusercontent.com/18737885/142826104-e920155f-0960-4ffd-bc7c-322c1a49e39f.png)

**Comment by n313893254** [comment]
Verify on the latest dashboard UI.
- [Fixed] RKE2 Cluster Explorer
- [Not Fixed] Harvester Virtualization Management
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/e50c6783-b3ae-493c-8d39-6908244a2ff1)

And I found the progress bar of namespace detail page makes me confused. Compared with Rancher management UI (ember UI), seems that should be an issue?

[Namespace detail page]
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/40dacbec-cedd-4f8e-8206-89590a933a90)

[Rancher management UI]
![image](https://user-images.githubusercontent.com/18737885/144015675-47e880e3-46c2-437e-850d-83b1ae63cd88.png)

**Comment by n313893254** [comment]
**Test Plan**
- Check the Resource Quota of the project create/edit/detail page.
- Check the workload deploy successfully

TBH, I am not sure what the Resource Quota of the namespace detail page is expected. That makes me confused, I think the progress bar should display more useful information for users.

**Comment by lanfon72** [comment]
As I tested, **Resource quota** for Namespaces is not work as expected.
Please check those verify steps after step 6.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-655c251a-head**
* **ui-source** Option: **Auto**
* Rancher Version: **master-e4db3ee-head** (v2.6-head tagged)
* Rancher cluster type: Docker

### Verify Steps:
1. Install Harvester with any nodes
2. Install Rancher
3. Login to Rancher, import Harvester from _Virtualization Management_
4. Access Harvester dashboard via _Virtualization Management_
5. Navigate to _Project/Namespaces_, Create Project `A` with Resource quotas
6. Create Namespace `N1` based on Project `A`
7. The Default value of Resource Quotas should be the same as **Namespace Default Limit** assigned in Project `A`
8. Modifying **resource limit** should work correctly (when increasing/decreasing, the value should increased/decreased)
9. After `N1` Created, Click **Edit Config** on `N1`
10. **resource limit** should be the same as we assigned
11. Increase/decrease **resource limit** then Save
12. Click **Edit Config** on `N1`, **resource limit** should be the same as we assigned
13. Click **Edit Config** on `N1`, then increase **resource limit** exceeds Project `A`'s Limit
14. Click **Save** Button, error message should shown.
15. Click **Edit Config** on `N1`, then change the **Project** to `Default`
16. The Namespace `N1` should be moved to Project `Default`

**Comment by n313893254** [comment]
The same failed with the upstream repo, we will wait for the upstream repo to fix it.

https://github.com/rancher/dashboard/issues/4412#issuecomment-986487125

**Comment by n313893254** [comment]
Verify on the latest dashboard UI. Change pipeline to ready for testing.

**Verify Steps**
- Change CPU Limit from 800 to 200
- Change CPU Reservation from 400 to 64

**Result**
- ✅   RKE2 Cluster Explorer
- ✅   Harvester Virtualization Management

**Addictional Context**

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/0e251d1f-420c-44ce-9eb6-c75f36a814db)

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/bd62648d-0b60-4937-bc08-a9e96bbd51ec)

**Comment by lanfon72** [comment]
Verified following test cases (based on https://github.com/harvester/harvester/issues/1450#issuecomment-988970732):
- [ ] 6., 7. The Default value of Resource Quotas should be the same as **Namespace Default Limit** assigned in Project `A`
- [ ] 8. Modifying **resource limit** should work correctly (when increasing/decreasing, the value should increased/decreased)
- [x] 11., 12. **resource limit** should be the same as we assigned
- [x] 13., 14. exceeded **resource limit** will be fall back to the maximum
- [x] 15., 16. namespace moving between projects works correctly

For unchecked test cases, please check the video in **Additional Content**.

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-3d096946-head**
* **ui-source** Option: **Auto**
* Rancher Version: **master-6de683b-head** (v2.6-head tagged)
* Rancher cluster type: Docker


### Additional Content
https://user-images.githubusercontent.com/5169694/146171402-aa4a0cdb-4e9f-4bf4-a74d-eb39363fd254.mp4

**Comment by n313893254** [comment]
Confirmed fixed by upstream repo. Change to the pipeline to ready for testing.

**Comment by lanfon72** [comment]
Verified following test cases (based on https://github.com/harvester/harvester/issues/1450#issuecomment-988970732):
- [x] 6., 7. The Default value of Resource Quotas should be the same as **Namespace Default Limit** assigned in Project `A`
- [x] 8. Modifying **resource limit** should work correctly (when increasing/decreasing, the value should increased/decreased)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-3d096946-head**
* **ui-source** Option: **Auto**
* Rancher Version: **master-39cecf0-head** (v2.6-head tagged)
* Rancher cluster type: Docker
