### ISSUE TITLE
[BUG] The config will keep changing,  so the frontend will keep refreshing the list

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1453]
**Describe the bug**

The config will keep changing

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/ee771543-a001-469f-944d-ddba4f5aba48)

**To Reproduce**
1. Listening to config resources

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
The changes of these configmaps are expected. They are updated by controllers for leader selection. Given that they are not items on the list, we need to avoid refreshing the list on the UI side.

**Comment by WuJun2016** [comment]
test step:
- go to the vm creation page
- click advanced options tab
- Select the userData or networkData template and observe if the mouse moves abnormally in the drop-down list

**Comment by lanfon72** [comment]
verified drop-down list work normally in VM's advanced options.

Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-04c5f438-head**
* **ui-source** Option: **External**
### Verify Steps:
- follow the [comment](https://github.com/harvester/harvester/issues/1453#issuecomment-958611266) above
