### ISSUE TITLE
[BUG] Incorrect memory unit conversion in namespace resource quota

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1454]
https://github.com/rancher/dashboard/issues/4417

**Comment by TachunLin** [comment]
Verified **fixed** on rancher `v2.6.3-rc2` and harvester `master-47ea94ee-head`. Close this issue.

### Result
Based on configured project resource limit and namespace default limit, 
The memory limit of 256 Megabytes and memory reservation of 128 Megabytes can be configured and applied correctly.

![image](https://user-images.githubusercontent.com/29251855/143846876-41021ccf-86a3-40b5-81ca-101800444bee.png)

![image](https://user-images.githubusercontent.com/29251855/143847197-d340a01d-5c4f-4d15-a7c9-2b470a9f72ff.png)

![image](https://user-images.githubusercontent.com/29251855/143846795-915a4445-2e0d-4349-a8c4-100fbaf13efb.png)

And can create deployment with resource limit correctly. 
![image](https://user-images.githubusercontent.com/29251855/143847999-8223c260-68eb-4dd6-b8ab-97237392dc93.png)

![image](https://user-images.githubusercontent.com/29251855/143848330-9754035b-686f-4d30-b94e-c4d3d255f8de.png)

![image](https://user-images.githubusercontent.com/29251855/143848699-cd1ef60a-5ca2-497e-abcf-77eb914bf850.png)

### Test Information
* Test Environment:  3 nodes harvester on local kvm machines
* Harvester version: master-47ea94ee-head
* Rancher version: `v2.6.3-rc2`

### Verify Steps

1. Access Rancher dashboard
2. Open Cluster management -> Explore the active cluster
3. Create a new project `test-1454-proj` in Projects/Namespaces
4. Set resource quota for the project 
  * Memory Limit:
    - Project Limit: 512
    - Namespace default limit: 256
  * Memory Reservation:
    - Project Limit: 256
    - Namespace default limit: 128
5. Click create namespace `test-1454-ns` under project `test-1454-proj`
6. Click `Kubectl Shell` and run the following command
  * kubectl get ns
  * kubectl get quota -n test-1454-ns
7.  Check the output 
8. Click `Workload` -> `Deployments` -> `Create`
9. Given the `Name`, `Namespace` and `Container image`
![image](https://user-images.githubusercontent.com/29251855/143847775-eb84fa49-54d5-4001-a210-cbd8ed1235d1.png)
10. Click Create


### Additional Context

#### The harvester cluster in Virtualization Management also passed the test scenario (except the deployment)
 
![image](https://user-images.githubusercontent.com/29251855/143840915-28e965d4-5aff-4ace-85c6-9d3e1a766843.png)

![image](https://user-images.githubusercontent.com/29251855/143841660-9521a184-07df-4910-a6a6-bffc6225c81e.png)

![image](https://user-images.githubusercontent.com/29251855/143845098-0b2dbd80-26a3-451a-8d54-04aae51254d7.png)
