### ISSUE TITLE
[FEATURE] Supprt Network IP Pools config on the Harvester UI

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1458]
**Is your feature request related to a problem? Please describe.**
Before Harvester v1.2.0, users has to have to config the VIP CIDR pools manually using the `kubectl` command, we should add support to allow config on the dashboard.
```
apiVersion: v1
kind: ConfigMap
name: kubevip
namespace: kube-system
data:
  cidr-default: 192.168.0.200/29
  cidr-development: 192.168.0.210/29
  cidr-finance: 192.168.0.220/29
  cidr-testing: 192.168.0.230/29
```

https://docs.harvesterhci.io/v0.3/rancher/cloud-provider/#ipam
https://github.com/kube-vip/kube-vip-cloud-provider#global-and-namespace-pools

**Proposed Solution:**
- In Harvester v1.2.0, we have added a custom cloud provider of VIP, and users will be able to manage IP pools via `Networks -> IP Pools`, and it should allow users to:
  - config IP range via CIDR or range
  - config IP pools selector by VM network, namespace names
     -  multi-cluster UI will support additional selectors with project and guest cluster name

Note: for the design proposal please refer to https://github.com/harvester/harvester/blob/master/enhancements/20220214-harvester-cloud-provider-enhancement.md

**Comment by janeczku** [comment]
The current implementation of Harvester's built-in load balancer feature requires editing a ConfigMap for setup and comes with a few other important limitations, including:

- Lacks **support for central management of VIP pools** via Rancher or Harvester API/UI
- Lacks **support for managing VIPs in different VLANs** (ConfigMap is not VLAN aware)
- Lacks **support for assigning multiple /32 VIP addresses per tenant**
- Lacks support for allocation of VIPs to specific downstream clusters
- **Traffic for different VIPs is not load balanced across multiple Harvester nodes**, creating a bandwidth bottleneck and SoP.

Expected State:

We need a more flexible and operatable VIP implementation with first class integration in Rancher and Harvester UI **that addresses the above limitations**.

The VIP Pool custom resource managed by user must have following attributes:

- mapped to a specific VLAN
- mapped to a specific Harvester tenant project/namespace

Multiple VIP pools may exist for same pair of VLAN and tenants. 

When provisioning a Harvester guest cluster in Rancher then a VIP is automatically assigned from a pool matching both the Harvester namespace *and* the VLAN network configured in the cluster options.

**Comment by janeczku** [comment]
@guangbochen ^ for discussion

**Comment by guangbochen** [comment]
- Lacks support for managing VIPs in different VLANs (ConfigMap is not VLAN aware) (need deal with cases like one namespace have multiple VLAN network configs)
- Traffic for different VIPs is not load balanced across multiple Harvester nodes, creating a bandwidth bottleneck and SoP. (ARP mode is more prefered)

**Comment by janeczku** [comment]
Regarding first point from [@guangbochen ](https://github.com/harvester/harvester/issues/1458#issuecomment-984485093)

If one namespace creates guest clusters using different VLANs then we need to make sure that the VIPs are assigned from the CIDR that matches the guest cluster VLAN.

**Comment by n313893254** [comment]
@yaocw2020  Can the issue be moved to ready for testing?

**Comment by yaocw2020** [comment]
We provide IPPool CRD to allow users configure their own IP pool. Get more details from https://github.com/harvester/harvester/blob/cc849f78afb0d676a5485ddac7d1ee687a7e4505/enhancements/20220214-harvester-cloud-provider-enhancement.md.

**Comment by TachunLin** [comment]
## Test Plan 

- New Features in Network > IP Pools

More test plans are under description 

#### IP Pool Basic

- [x] Create 
- [x] Delete
- [x] Edit config
- [x]  `(fixed)` Edit YAML
  - **Failed** When we edit as Yaml without changes and directly save, pool will become `Not ready`
- [x] Download YAML
- [x] Clone

#### IP Pool Range
User need to create a load balancer with `Pool` type to interact with IP Pool feature

- [x] CIDR: with Subnet value 
- [x] CIDR: without subnet value
   - Prompt `"Subnet" is required` 
- [x] CIDR: with and without Gateway value
- [x] Range: with Subnet value 
- [x] Range: with Subnet value and Start IP only 
- [x] Range: with Subnet value and End IP only 
- [x] Range: with Subnet value and both Start / End IP
- [x] Range: with and withoug Gateway value

- [x] Overlap (conflict) check for multiple Range
    - Prompt `could not create IP pool pool-conflict because there are overlaps between range`
    - [x]   - New Subnet <-> Existing start and end range 
       
    - [x]   - New Subnet <-> New Subnet 
                
    - [x]   - New Subnet <-> Existing Subnet 

- [x] `(fixed)` Available ip number on IP Pools page
   - **Failed**: When we set IP pool CIDR to 192.168.101.9/32, the available IP display 3 
- [x] allocated IP list in yaml 
- [x] Gateway value should be skipped in available number 
- [x] Gateway without value should set default value `1`
- [x] Multiple Ranges: IP allocation should follow the sequence
- [x] Multiple Ranges: IP allocation will skip to next if no available in current 
- [x]  `(fixed)`  Historical allocation: arrange the same IP to the backend server which have historical record before 
   - **Failed**: When we set load balancer to use the same IP pool on the same VM workdload, it did not get the previous recorded IP address

- [x] Out of Range 
   - [x] New CIDR <-> start and end range 
      - could not update IP pool pool-mgmt-conflict because range start IP 192.168.102.1 is out of subnet

#### Negative and Edge Testing

- [x] When Load balancer can't find available IP address in the given IP Pool

    - The load balancer would display `Not ready` state
    ![image](https://github.com/harvester/harvester/assets/29251855/c02c99fa-d686-4ff6-9446-cd1eb77bef68)
 
- [x] Negative value on CIDR and Range (e.g -1, 258 etc...) 

- [x] `(fixed)` Range of IP: Edge value of IP address 192.168.130.0 , 192.168.130.255  
   - **Failed**: We can still set these network and broadcast IP address on gateway

#### IP Pool Selector
Note: 
Network and Guest Kubernetes Cluster options aim for multiple cluster usage 

- [x] Apply All namespace scope to Pool IPAM load balancer
- [x] Display existing vlan network list 
- [x] `(fixed)` Display guest kubernetes cluster provisioned from external Rancher 
   - **Failed**: After import Harvester from external Rancher instance, we can't find available `guest kubernetes cluster` in IP Pool page
- [x] Priority rules check
    - [x] Migrate (clone) IP pool with different priority
    - [x] `(fixed)` Priority can't be 0 or the same value with any existing pool
       - **Failed** We can set priority to `0` and save it. But actually it saved with empty value
    - [x] Larger value have higher priority 
    - [x] Higher priority will be consider first among the Pool lists


## Dependency and Blocker

### Required feature (dependency)
* Project options: 
#3984 

###  Multi cluster guest cluster (Blocker)
* Failed to provision RKE2 cluster on MCM: 
#3973

**Comment by TachunLin** [comment]
## Issues found and enhancement list 

1. **[BUG]** When we edit config of the existing IP pool, click `Edit as Yaml`, don't change anything then save directly. The state of IP pool become `Not Read` 

    ![image](https://github.com/harvester/harvester/assets/29251855/805be2d2-549e-44c9-a076-1d916460ad6a)

2. **[BUG]** [Reproduce steps unknown] When you delete a load balancer without removing VM first, it will keep in `Removing` state

    And after that we can't create new load-balacner, it always keep in `Not Ready` state
    
    ![image](https://github.com/harvester/harvester/assets/29251855/373f7e08-01fe-458f-a553-5a8400a1e2e0)

    Check the logs of load-balancer pod `kubectl logs harvester-load-balancer-65c4f66b66-w7dqq -n harvester-system -f`
    We found it looping at get service failure
    ```
    time="2023-05-30T07:48:38Z" level=warning msg="get service default/lb2 failed, error: services \"lb2\" not found, continue..."
    time="2023-05-30T07:48:38Z" level=warning msg="get service default/lb3 failed, error: services \"lb3\" not found, continue..."
    time="2023-05-30T07:48:39Z" level=warning msg="get service default/lb2 failed, error: services \"lb2\" not found, continue..."
    time="2023-05-30T07:48:39Z" level=warning msg="get service default/lb3 failed, error: services \"lb3\" not found, continue..."
    time="2023-05-30T07:48:40Z" level=warning msg="get service default/lb2 failed, error: services \"lb2\" not found, continue..."
    ```
    Also we can't find the corresponding load balancer service in Harvester explorer dashboard
    

3. **[BUG]** When we set IP pool CIDR to `192.168.101.9/32`, the available IP display `3`, which should be `1` in concept. 
  ![image](https://github.com/harvester/harvester/assets/29251855/cdd23b15-9032-4ea5-aa81-5f001af9b0c5)

4. **[BUG]** [Reproduce steps unknown] When we set CIDR subnet check `10.84.99.9/24`, and do some operation, it would possible cause the available IP list set to **-3**

5. **[BUG]** When we assign the same load balancer to the same VMs workload again after deletion,  the load balancer did not allocate the previous recorded (historical) IP address to the same VM workload

  ![image](https://github.com/harvester/harvester/assets/29251855/8ca25cb2-7843-4cfe-a7c3-1d053c772bfa)
 
6. **[BUG]** We can set network and broadcast IP address on the:
  - Start and End IP: 192.168.130.0 - 192.168.130.255
  - Gateway: 192.168.130.255
  ![image](https://github.com/harvester/harvester/assets/29251855/f4380aac-1421-4c3e-ac0f-3aaa17a643e8)

7. **[BUG]** We can set priority to `0` and save it. But actually it saved with empty value 
8. **[BUG]** When we set `Higher` priority, it still can't  ignore the overlapped Range with existing Pool 
    ( For Range to Range priority case)
  ![image](https://github.com/harvester/harvester/assets/29251855/170b4cb0-0b85-4728-a602-306cdab6452d)
  
9. **[BUG]** After import Harvester from external Rancher instance, we can't find available `guest kubernetes cluster` in IP Pool page
  ![image](https://github.com/harvester/harvester/assets/29251855/8b0bb7be-7991-42e1-9139-be6fd0077bd5)
  ![image](https://github.com/harvester/harvester/assets/29251855/af9a8067-1920-4630-bf29-58e9972a2203)

**Comment by TachunLin** [comment]
Move to implement for checking the found issue of rc1 test result

**Comment by irishgordo** [comment]
**validation question**

@n313893254 @yaocw2020 would we want to change the IP Pool: Create vue's Selector -> Network to read:
`VM Network`

Would that make more sense to the user in the UI?
As it's tied to a VM Network.
```
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: IPPool
metadata:
  name: vlan-awareness-pool
spec:
  selector:
    network: default/vlan1
```

![Screenshot from 2023-06-26 11-43-40](https://github.com/harvester/harvester/assets/5370752/9f044a2d-901e-43c5-88c7-1afd16261ef4)

Maybe just update the Tab component:
https://github.com/harvester/dashboard/blob/f0588a55030e80e3a07eee9e207080ff18ceb6dd/pkg/harvester/detail/loadbalancer.harvesterhci.io.ippool.vue#L77-L81

To maybe something like:
```vue
    <Tab
      name="vm network"
      label-key="harvester.ipPool.network.label"
      :weight="99"
    >
```

Just curious :smile: - don't know if we'd want to implement that UI change or not.

I know in the Virtual Machine: Create page, we don't explicitly say "VM Network" from:
![Screenshot from 2023-06-26 11-54-38](https://github.com/harvester/harvester/assets/5370752/f44c2483-6d5e-4fc6-ac1b-f85a1fdf1bab)

Since it's a VM and there is Networks -> VM Networks present in the menu, guessing the user would make that link more easily.
Whereas, with IP Pools, it may not be obvious immediately that it's tied to VM Networks?

**Comment by irishgordo** [comment]
**Validation Issue:**
Discovered https://github.com/harvester/harvester/issues/4135 - when attempting to implement a Health Check with a Load Balancer creation

**Comment by n313893254** [comment]
Good question, I have changed the "Network" to "VM network".

**Comment by TachunLin** [comment]
Verified **failed** on `v1.2-f4968e49-head` (06/30). Move the issue to implement stage.

### Test Result
* When we edit existing IP pool -> edit yaml -> do nothing and click `Save` 
* The load balancer state will become `Not ready` 
* Check the yaml content found no `status` content been recorded into it. 

https://github.com/harvester/harvester/assets/29251855/2c391671-edfa-45da-b7f8-d717889b5fe4

Further check when an IP pool status is `Not ready` and we create a load balancer and assign that IP pool. 
The available IPs will become `-1` 

![image](https://github.com/harvester/harvester/assets/29251855/32802649-17de-4392-8608-8a96ce9718c4)


### Test Information
* Test Environment: Single node Harvester on local kvm machine
* Harvester version: `v1.2-f4968e49-head` (06/30)

**Comment by TachunLin** [comment]
### Regression test on v1.2-4d7b1196-head (07/05)

1. - [x] **Fixed** [BUG] When we edit config of the existing IP pool, click `Edit as Yaml`, don't change anything then save directly. The state of IP pool become `Not Read` 

    ![image](https://github.com/harvester/harvester/assets/29251855/805be2d2-549e-44c9-a076-1d916460ad6a)

2. - [x] **Fixed** [BUG] [Reproduce steps unknown] When you delete a load balancer without removing VM first, it will keep in `Removing` state

   
3. - [x] **Fixed** [BUG]  When we set IP pool CIDR to `192.168.101.9/32`, the available IP display `3`, which should be `1` in concept. 
  ![image](https://github.com/harvester/harvester/assets/29251855/cff59a2b-ec40-4cc9-8972-f5cd9d1e36aa)

4. - [x] [BUG]  [Reproduce steps unknown] When we set CIDR subnet check `10.84.99.9/24`, and do some operation, it would possible cause the available IP list set to **-3**

      - This could happen only when the IP pool in not ready and we try to assign it to a load balancer. After the yaml issue fixed, we should seldom hit this issue.

5. - [x] **Fixed** [BUG] When we assign the same load balancer to the same VMs workload again after deletion,  the load balancer did not allocate the previous recorded (historical) IP address to the same VM workload

     - When we delete and recreate the same name load balancer, IP pool will assign the same VIP to it.
     
    ![image](https://github.com/harvester/harvester/assets/29251855/0f07aa96-ec1a-44a9-af69-17ca1c42d279)

 
6. - [ ] **Not fixed** [BUG] We can set network and broadcast IP address on the:
      - Start and End IP: 192.168.130.0 - 192.168.130.255
      - Gateway: 192.168.130.255

    ![image](https://github.com/harvester/harvester/assets/29251855/b0e672f6-bf80-4a3b-a20e-3ac0c778de25)


7.  - [x] **Fixed** [BUG] We can set priority to `0` and save it. But actually it saved with empty value 
  ![image](https://github.com/harvester/harvester/assets/29251855/673b1fe9-1ea5-470a-9495-39592219b99e)

8. - [x] **Fixed** [BUG] After import Harvester from external Rancher instance, we can't find available `guest kubernetes cluster` in IP Pool page
     - This already fixed in https://github.com/harvester/harvester/issues/1762#issuecomment-1611073439

9. The Selector `Network` changed to `VM Network`
  ![image](https://github.com/harvester/harvester/assets/29251855/7e532e67-3376-4c50-87f3-503a690538a1)

**Comment by TachunLin** [comment]
The **priority** attribute in IP pool indicate when multiple IP pool are matched, it will select IP pool with higher priority

* Verified the priority setting of load balancer selector can work correctly on **single** cluster environment 
![image](https://github.com/harvester/harvester/assets/29251855/66fa903b-e0d6-4c92-aca2-02bc9eecdfb2)

* Verified the priority setting of load balancer selector can work correctly on **multiple** cluster environment 
![image](https://github.com/harvester/harvester/assets/29251855/b05782d1-1853-4361-9c53-a68dd7cfee07)

**Comment by TachunLin** [comment]
Verified **failed** on `v1.2-4d7b1196-head` (07/05). Move the issue to implement 

We passed most of the regression issue, just a remaining issue not yet fixed:
-  We can still set network and broadcast IP address on the
     - Start and End IP: 192.168.130.0 - 192.168.130.255
      - Gateway: 192.168.130.255

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2.0-rc3` for the remaining IP range issue. Close this issue. 

### Result
Now we can't set Gateway, Start IP and End IP with 192.168.130.0 and 192.168.130.255. 
Each of them would be blocked with message to indicate it's network and broadcast IP address

  ![image](https://github.com/harvester/harvester/assets/29251855/885ce382-bacc-498f-9747-053902806f27)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/7f218c33-b4be-4b58-a45f-12219dea5800)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/9e8262ab-1b4b-4405-abc0-67b542156524)

And we also verified **fixed** all test scenarios in:
https://github.com/harvester/harvester/issues/1458#issuecomment-1562525762

With result 
https://github.com/harvester/harvester/issues/1458#issuecomment-1621470440
https://github.com/harvester/harvester/issues/1458#issuecomment-1623393562


### Test Information
* Test Environment: 4 nodes Harvester on bare machine and single cluster on local kvm
* Harvester version: v1.2.0-rc3

### Verify Steps
https://github.com/harvester/harvester/issues/1458#issuecomment-1562525762

**Comment by LucasSaintarbor** [comment]
Hi @yaocw2020 @n313893254 @TachunLin, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [ ] New documentation/KB
- [ ] Updated documentation/KB
- [ ] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!

**Comment by yaocw2020** [comment]
> Hi @yaocw2020 @n313893254 @TachunLin, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following?
> 
> * [x]  New documentation/KB
> * [x]  Updated documentation/KB
> * [ ]  Release note
> * [ ]  None of the above
> 
> If it does, may you please open a PR or share details on what needs to be created or updated? Thanks!

Document update PR: https://github.com/harvester/docs/pull/323

Do we require a release note for this enhancement? @guangbochen

**Comment by guangbochen** [comment]
> Do we require a release note for this enhancement? @guangbochen

The doc and GH issue look sufficient to me, but the original issue was a bit outdated; I will update it to reflect the current design and feature change; thanks.
