### ISSUE TITLE
[BUG][UI] F keys and Alt-F keys in web VNC interface

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#1461]
As mentioned in https://github.com/harvester/harvester/issues/401 :: when viewing a VM's UI using the web VNC viewer in the Harvester UI from a web browser on a Linux GUi desktop, it is impossible to send some F keys and all Alt-F keys to any VM via the web VNC interface.

https://github.com/harvester/harvester/issues/401 was closed after some Windows desktop specific key strokes were implemented, but that left Linux desktop users still unable to send many key strokes to a VM via the web VNC interface.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-949bbb0c-head` (06/25). Close this issue.

### Result
Verified the soft shortcut keys can display and work correctly on Linux OS VM (Ubuntu desktop 20.04)
![image](https://user-images.githubusercontent.com/29251855/177092853-0a9d570e-39b1-4127-ac22-2b9508d5b4f6.png)

Checked the following short cut can work as expected
* CTRL + ALT + DELETE: Logout system
* Soft Reboot
* Print screen
* F12: Developer mode
* F11: Full screen
* F10: Open menu
* ALT + F1: zoom in windo
* ALT + F2: Run command
* ALT + F4: Close window
* ALT + F8: Drag and drop
* Ctrl + N: New window
* Ctrl + N: New tab
* Ctrl + W: Close tab


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-949bbb0c-head
* os image: ubuntu-20.04.4-desktop-amd64.iso

### Verify Steps
1. Create a new VM with Ubuntu desktop 20.04 
2. Prepare two volume
3. Complete the installation process
4. Open a web browser on Ubuntu desktop
5. Check the shortcut keys combination
