### ISSUE TITLE
[BUG] Fail to use `/dev/by-id/xxx` link as the install disk in PXE boot installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1462]
**Describe the bug**

**To Reproduce**
1. Do a PXE boot installation and specify the symbolic link to a disk (e.g., `/dev/disk/by-id/wwn-0x5000c50015ea819b`) in the `install.device` field.
2. The installation fails even `/dev/disk/by-id/wwn-0x5000c50015ea819b` exists on the host.
 
![Screen Shot 2021-10-21 at 3 48 36 PM](https://user-images.githubusercontent.com/1691518/138234404-928343fe-7cbb-41d1-b4af-7a54c500a03c.png)

**Expected behavior**

The installation should succeed. Using links to disks is a reliable way to choose a disk.

**Support bundle**

**Environment:**
 - Harvester ISO version: `0.3.0`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
We only compare the field with `lslbk` output (which contains `/dev/sda`...)
https://github.com/harvester/harvester-installer/blob/3d823e58afd0e18fecaaec68c53bc1b597831174/pkg/console/validator.go#L69-L83

**Comment by bk201** [comment]
The doc can also suggest users use the persistent link names too.

**Comment by lanfon72** [comment]
verified we can use _**symbolic**_ to point the disk, like `/dev/disk/by-path/xxx`.
