### ISSUE TITLE
[FEATURE]  toggle harvester node driver with the harvester global flag

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1465]
link to https://github.com/rancher/rancher/issues/34886

We should add the Harvester node driver as a built-in type and also support downloading the Harvester node driver within the air-gap env.

**Comment by guangbochen** [comment]
Can we help to validate this issue on https://github.com/rancher/rancher/issues/34886 thanks? and both can be closed after passing the validation.

To Test:
- If the feature flag was turned on, we enable the Harvester node driver automatically (if it's not enabled and default to enabled).
- If the feature flag was turned off, nothing will change to the Harvester node driver.
- Enable/disable the Harvester node driver will not affect the state of the feature flag.

**Comment by TachunLin** [comment]
Verified **fixed** on `Rancher v2.6.3-rc1` with builtin node driver
Pass the following test scenario. Close this issue and [rancher/rancher#34886](https://github.com/rancher/rancher/issues/34886) accordingly.

Test in Rancher v2.6.3-rc1 under airgapped environment

- [x] Harvester feature flag will be enabled by default and turned on harvester node driver accordingly

- [x] If the feature flag was turned off, nothing will change to the Harvester node driver.

- [x] Enable/disable the Harvester node driver will not affect the state of the feature flag.

- [x] If the feature flag was turned on, we enable the Harvester node driver automatically 


### Result

1. Harvester feature flag are turned on by default
![image](https://user-images.githubusercontent.com/29251855/142818784-21d084eb-ed8e-4f7c-93a7-e224119c0190.png)

1. The node driver also enabled automatically
![image](https://user-images.githubusercontent.com/29251855/142818649-8bb1c585-f9dd-47fd-a8a2-80558f59fafd.png)

2. Deactivate the  feature flag, 
![image](https://user-images.githubusercontent.com/29251855/142819289-6e06b72f-6631-44f1-83e1-77947dc4ba6d.png)

2. Harvester node driver will not be affected
![image](https://user-images.githubusercontent.com/29251855/142819219-0f3a4eaf-f837-49cf-bdc7-347ff38c7a88.png)

3. Deactivate harvester node driver
![image](https://user-images.githubusercontent.com/29251855/142819526-321e2ead-474c-403a-88e6-14445f316c6c.png)

3. Harvester feature flag did not being affected
![image](https://user-images.githubusercontent.com/29251855/142819705-347aab30-cd92-4b45-935f-a3f0dcd17342.png)

3. Activate harvester node driver 
3. Harvester feature flag did not being affected
![image](https://user-images.githubusercontent.com/29251855/142821763-4860a371-0a89-4476-8f56-45ffbfb842fe.png)

4. Both harvester feature flag and node driver are deactivated, Activate feature flag will also bring up harvester node driver
![image](https://user-images.githubusercontent.com/29251855/142819920-3b29e61a-7543-44e0-830c-4c450a1b30fa.png)

### Test Information
* Rancher version: v2.6.3-rc1

### Environment Preparation
* Prepare an airgapped ubuntu vm
* Install rancher 2.6.3-rc1 

### Verify Steps

1. Environment preparation as above steps
2. Open global setting -> feature flag in rancher
3. Check harvester feature flag 
4. Open cluster management -> Driver page
5. Check harvester node driver
6. Deactivate harvester feature flag
7. Activate harvester feature flag
8. Deactivate harvester node driver
9. Activate harvester node driver 
10. Deactivate both harvester flag and node driver
11. Activate harvester feature flag
