### ISSUE TITLE
[FEATURE] HA cluster plan if Master nodes get down.

### ISSUE THREAD

**Issue by yshashix** [harvester/harvester#1466]
I tested v0.3 but when the master node goes down, I am unable to access the cluster and VM went down I guess. Is there any plan to make an HA cluster for harvester?

**Comment by guangbochen** [comment]
When u have total nodes with >= 3 it will promote the other two nodes to be the management node and therefore u will get a HA cluster automatically, the node fault toleration is 1 out of those 3 management nodes.

All other nodes joined later will only become a compute node and have no effect on the cluster's HA.
