### ISSUE TITLE
[Question] Flat network type support

### ISSUE THREAD

**Issue by yshashix** [harvester/harvester#1467]
Is there plan to support flat network type as well? 
Many test cluster not have access to switch with VLAN configuration. This will ease testing rancher integration with harvester as harvester currently need VLAN to be successfully integrated to Rancherv2.6

**Comment by simonflood** [comment]
You don't need a switch with VLANs to test Harvester+Rancher. If you enable VLAN support within Harvester and add a custom network using VLAN ID 1 you're effectively setting up a bridge to your flat network. Any VMs attached to your custom network will then appear on and be accessible from your flat network.

**Comment by yshashix** [comment]
@simonflood Thanks for a tweak to use VLAN ID 1 but still my VMs created from a rancher for rke2 on harvester are not able to get IPs.
I tried to set VLAN from Advance->settings->vlan in harvester dashboard VLAN "Default physical NIC name of the VLAN network.", I don't get the option of selecting physical NIC other than harvester-mgmt whereas I have selected NICs for VLAN in each host and created a network in Advance tab with VLAN id 1.

**Comment by WolframRavenwolf** [comment]
@yshashix I encountered that problem as well and the solution posted by @simonflood works for me:

1. Advanced > Settings: vlan Enabled, Default Physical NIC: harvester-mgmt
2. Advanced > Networks > Create: L2VlanNetwork, Vlan ID: 1
3. Add this network to VM, Type: bridge

This works (got an IP address by DHCP on my main network and was able to SSH into the VM from my workstation), but it's far from intuitive. What I expected to work out of the box was keeping the existing management network (default) and switch from masquerade to bridge type, but the setting reverted all the time by itself (which looks like a bug, so I'll open an issue for that).

**Comment by yshashix** [comment]
@StefanDanielSchwarz 
Yes, @simonflood  solution worked for me as well but I had to wait 5-10 min around to get IP in the VMs

**Comment by verejoel** [comment]
If DHCP is not available is there a way to assign a static IP in the flat network to the VMs?

**Comment by simonflood** [comment]
Yes you can use the Network Data config to set static IP - there's a working example in https://community.suse.com/posts/how-to-manage-harvester-030-with-rancher-261-running-in-a-vm-within-harvester which I posted on the SUSE Community site.

**Comment by yshashix** [comment]
Thanks @simonflood

**Comment by bk201** [comment]
We supported untagged traffic for VMs in v1.1.0, please check https://docs.harvesterhci.io/v1.1/networking/harvester-network#untagged-network. Feel free to create an issue if it doesn't work, thanks!
