### ISSUE TITLE
[FEATURE] Support HostPath Storageclass / local Storage

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1469]
**Is your feature request related to a problem? Please describe.**
Certain virtual machines are not worth protecting or may require close to bare-metal storage performance. 

**Describe the solution you'd like**
Supporting a hostPath to place the VMs on a separate disk/path would allow this.
Allow Live Migration of the VM, even if the migration takes longer with minimal ping/connectivity loss.

**Comment by yasker** [comment]
Having another storage class is against the general design of Harvester. The VM with local path has to be treated separately and cannot be migrated, snapshotted, backed up etc. 

If no replication is needed, Longhorn with a single replica might be the way to do it instead.
