### ISSUE TITLE
Unable to create image if the URL begins or ends with spaces

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#147]
**Steps to replicate:**
1. On the image create page, type in some spaces at the beginning or in the end of the URL
2. Fill in other required fields and click the create button

**Result:**
Failed to create an image, along with error messages
![image](https://user-images.githubusercontent.com/57614736/93497150-afc06200-f942-11ea-959b-47b04efb7031.png)

**Comment by guangbochen** [comment]
will add string trim on both backend and the UI, thanks

**Comment by DaiYuzeng** [comment]
This issue has been fixed at https://github.com/rancher/harvester-ui/commit/21aa2c2ef1a5b89577f4a264de618d0117b8379f

**Comment by DoNotSayYes** [comment]
Validated.
