### ISSUE TITLE
[BUG] current images error out

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1472]
**Describe the bug**
My images were working perfectly fine, suddenly two of them show this error

<img width="1543" alt="editedscreenie" src="https://user-images.githubusercontent.com/5146963/138335429-d21fe950-e95e-44fc-8aa6-7c7dff00bf8f.png">

**To Reproduce**
Don't know.

**Expected behavior**
Already imported images shouldn't fail or get re-downloaded.

**Support bundle**
https://drive.google.com/file/d/1-PnyIeYrBYVK8UTHZuZ95uWvUuFEcPwV/view?usp=sharing

**Environment:**
 - Harvester ISO version: 0.3
 - Underlying Infrastructure : R620

**Comment by shuo-wu** [comment]
The root cause is this issue: https://github.com/longhorn/longhorn/issues/3061

**Comment by guangbochen** [comment]
should be addressed via bump LH to `v1.2.3-rc1`, and please help to validate according to https://github.com/longhorn/longhorn/issues/3061#issue-1005273858.

**Comment by noahgildersleeve** [comment]
Version of Longhorn was bumped and issue has not been seen again during testing run. 
## Test Steps
1. Created new volume from backing image
2. modified backing image with `echo test > backing`
3. made image same size with `truncate -s 543M backing`. 
4. Deleted backing image service pod from embedded rancher
5. Verified that image rebuilt properly.
![Greenshot 2021-12-16 19 59 22](https://user-images.githubusercontent.com/83787952/146487053-47bd2c0b-c825-48b3-8e91-3a47414c7642.png)
![Greenshot 2021-12-16 20 00 16](https://user-images.githubusercontent.com/83787952/146487054-abe0a68a-ae6e-4f6d-8bc5-dda85ca74a77.png)

Closing ticket as fixed.
