### ISSUE TITLE
[Feature][Bug] Add a route to prove RKE1/RKE2 in VLAN network can access the VIP

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1474]
**Describe the bug**

The reachability of the network among the external rancher, Harvester VIP and the rke2 cluster nodes is a necessary condition for the rke1 or rke2 cluster created by the Harvester node provider in the VLAN networks. 

The users should guarantee network reachability between the external rancher and the rke cluster nodes, the external rancher and the Harvester VIP. However, we should ensure the VIP is reachable by adding a route in the host root network(e.g.  `172.16.178.0/24 via 172.16.0.1 dev harvester-mgmt`, 172.16.178.0/24 is in VLAN network 178)

**To Reproduce**
1. Create a VLAN network with VLAN id except 1
2. Import the Harvester cluster into Rancher
3. Create a rke2 cluster with the Harvester node provider in the VLAN network

**Expected behavior**

Under the premise the users guarantee network reachability between the external rancher and the rke cluster nodes, the rke1/rke2 created by the Harvester node provider should work if the gateway of the NIC can reach the VLAN network.

**Support bundle**

**Environment:**
 - Harvester ISO version:  0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by gitlawr** [comment]
Check if Harvester cloud provider can connect host k8s via rancher proxy instead of using the VIP

**Comment by yaocw2020** [comment]
> Check if Harvester cloud provider can connect host k8s via rancher proxy instead of using the VIP

We could not generate the kubeconfig for the specified serviceaccout using the rancher API `v3/clusters/clusterid?action=generateKubeconfig`.

**Comment by yaocw2020** [comment]
We could close this issue now because it's the same as https://github.com/harvester/harvester/issues/1476
