### ISSUE TITLE
[FEATURE] Add network reachability detection from host for the VLAN network

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1476]
**Is your feature request related to a problem? Please describe.**

- Add the route from the host to the VLAN network automatically
- Provide network reachability detection for the VLAN network.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yaocw2020** [comment]
Dependency: https://github.com/harvester/harvester/issues/1474

**Comment by yaocw2020** [comment]
UI requirement:
- Add the label `network.harvesterhci.io/vlan-id` for the VLAN network.
- Provide the UI for users to select the mode of how to get the layer 3 network information.
   - if manual mode is selected, provide the text box for users to configure the CIDR and gateway. 
   
@WuJun2016

**Comment by yaocw2020** [comment]
For testing:
- Enable VLAN network.
- Create a VLAN network getting route by `auto` mode or `manual` mode.
- Create a VM with only one network NIC in the VLAN network.
- Ping the VM from the host. It should be connectable.

**Comment by yaocw2020** [comment]
There is something wrong with `auto` mode. 
Dependency issue:  https://github.com/harvester/harvester/issues/1611

**Comment by guangbochen** [comment]
> There is something wrong with `auto` mode. Dependency issue: #1611

u may help to bump the chart so they can be verified with the `master-head` ISO

**Comment by noahgildersleeve** [comment]
Tested in master-140adb56-head. When adding route manually it still shows as unknown. That is the same route that is being set as DHCP. It shows as active via DHCP. The VM is routing to the internet though.
![Greenshot 2021-12-06 16 15 32](https://user-images.githubusercontent.com/83787952/144942988-9a9d8286-b97d-4e0f-a88e-437c27491c01.png)
[supportbundle_57ddef0a-5e9c-4a55-9f91-96f8494dab45_2021-12-07T00-17-02Z.zip](https://github.com/harvester/harvester/files/7664364/supportbundle_57ddef0a-5e9c-4a55-9f91-96f8494dab45_2021-12-07T00-17-02Z.zip)

**Comment by noahgildersleeve** [comment]
After talking with @TachunLin the status updated over time. He said that it takes about 15 minutes. This probably shouldn't take this long, and it shows as unknown while waiting to update.

**Comment by yaocw2020** [comment]
> After talking with @TachunLin the status updated over time. He said that it takes about 15 minutes. This probably shouldn't take this long, and it shows as unknown while waiting to update.

The harvester network controller will ping the gateway every 15 minutes. I will add the function to initialize the route connectivity by pinging the gateway once the network is created.

**Comment by yaocw2020** [comment]
> > After talking with @TachunLin the status updated over time. He said that it takes about 15 minutes. This probably shouldn't take this long, and it shows as unknown while waiting to update.
> 
> The harvester network controller will ping the gateway every 15 minutes. I will add the function to initialize the route connectivity by pinging the gateway once the network is created.

@TachunLin @noahgildersleeve I have optimized the display of the route connectivity. The UI will show the route connectivity in one minute once you create the VLAN network.

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head. This was in a virtual environment/network. network updated in a timely manner. Quicker for valid networks than invalid networks.
## Test Steps
1. Setup network that is routed properly with valid VLAN (available)
2. Setup network that is routed improperly with valid VLAN (not available)
![Screenshot from 2021-12-15 13-46-15](https://user-images.githubusercontent.com/83787952/146270095-6689e0b3-d3ac-47ff-9df4-7c7c5ea68605.png)
