### ISSUE TITLE
[BUG] intimidating error message when missing mandatory field

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#1477]
**Describe the bug**
When creating a new VM, if leave memory field blank, it'll throw an error with complex regular expressions.

**To Reproduce**
1. Head to "Virtual Machines" page. Fill out all mandatory field but leave memory blank.
2. Click "Create"
3. See that error

**Expected behavior**
Maybe Web UI should check the value not empty such like other fields do.

**Environment:**
 - Harvester ISO version: master-d05a6cc7-head
 - Underlying Infrastructure: openSUSE Tumbleweed with KVM

**Additional context**

<img src="https://user-images.githubusercontent.com/14314532/138429203-23ecfafa-42ce-47be-adf7-d29728aa3eac.png" width="450px">

**Comment by TachunLin** [comment]
Verified **fixed** on master-b5dadc82-head. Close this issue.

### Result
Leave empty memory field empty when create virtual machine will show "Memory is required" error message

![image](https://user-images.githubusercontent.com/29251855/140006054-92b12a07-af8b-4087-9fc8-4cf76c6500ea.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine (RackD8 ClusterA)
* Harvester version: master-b5dadc82-head

### Verify Steps

1. Create some image and volume
2. Create virtual machine
3. Fill out all mandatory field but leave memory blank.
4. Click create
