### ISSUE TITLE
[BUG] Required to input bootstrap password with setup new password

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1479]
### Describe the bug
Input box `Bootstrap Password` shown and required input password to set up new password.
![image](https://user-images.githubusercontent.com/5169694/138676750-a7bf91b2-5079-49ff-9b4b-77fc2ed6c2cf.png)

### To Reproduce
1. Install fresh Harvester
2. Navigate to `https://<vip>/`, will be redirect to `https://<vip>/dashboard/auth/setup`
3. use `ctrl+R` to refresh page, Input box `Bootstrap Password` shown
4. unable to set up new password when the Input box is appeared.

** The Input box will disappear when visiting the page via url redirect. (which means user can navigate to `https://<vip>/` to fix this as a workaround)

### Expected behavior
Bootstrap Password should comes with an hint as snapshots in #1362 .
Or the behavior should be consistent whatever how many refresh pages hits.

## Environment:
 - Harvester ISO version: **master-d05a6cc7-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

**Comment by lomas969** [comment]
The token is "admin"
I got it logging into the node with ssh and running:
kubectl get secret -n cattle-system bootstrap-secret -o jsonpath="{.data.bootstrapPassword}" | base64 --decode

**Comment by WuJun2016** [comment]
close, if there issue can reproduction, please feel free to open.
