### ISSUE TITLE
Unknown state shows at the beginning of creating an image, and error messages do not show until refreshing the page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#148]
**Steps to reproduce:**
1. Create an image with an invalid URL or something
2. Check on the image list

**Results:**
- [x] 1. Unknown state shows at the beginning of creating an image
![image](https://user-images.githubusercontent.com/57614736/93497873-90760480-f943-11ea-969d-c7c9eba50261.png)

- [x] 2. Error messages do not show until refreshing the page
![image](https://user-images.githubusercontent.com/57614736/93497933-ae436980-f943-11ea-922b-93d288dc36a1.png)

- [x] 3. The process bar could disappear if users select the failed items
![image](https://user-images.githubusercontent.com/57614736/93498136-f06cab00-f943-11ea-93af-1464c67b1ae8.png)

**Comment by DoNotSayYes** [comment]
Case 1 and case 2 still can be encountered, could you help look into it? @DaiYuzeng

**Comment by DaiYuzeng** [comment]
@DoNotSayYes  Case 1, the display of unknown status is reasonable

**Comment by gitlawr** [comment]
Validated
