### ISSUE TITLE
[BUG] The VM  Pods trun to terminating state after switch  device reboot

### ISSUE THREAD

**Issue by 290760647** [harvester/harvester#1488]
**Describe the bug**
The VM  Pods turn to terminating state after switch  device reboot

**To Reproduce**
1. turn off the switch device and turn on
2. The VM pods turn to terminating state and can't recover after 20 min

![image](https://user-images.githubusercontent.com/42170674/139170291-47d8447d-4d11-48ce-80cd-50e26b690b16.png)
![image](https://user-images.githubusercontent.com/42170674/139170360-bbf29d92-83fe-4704-9a06-fd6cc02c7f7c.png)

**Comment by 290760647** [comment]
[supportbundle_3af972b7-db54-4c16-895a-95ccf6c66d17_2021-10-28T04-47-35Z.zip](https://github.com/harvester/harvester/files/7431176/supportbundle_3af972b7-db54-4c16-895a-95ccf6c66d17_2021-10-28T04-47-35Z.zip)
supportbundle file.

**Comment by 290760647** [comment]
In Harvester Cluster we use kubectl command delete VM pod ，The VM will restart and state turn to running
kubectl delete pod_name --force

**Comment by guangbochen** [comment]
related to https://github.com/harvester/harvester/issues/982

**Comment by w13915984028** [comment]
Closed, as #982 have been solved and verified.
