### ISSUE TITLE
Three node RKE2 Cluster on SLES fails on startup 

### ISSUE THREAD

**Issue by wjimenez5271** [harvester/harvester#1494]
**Describe the bug**
When launching a three node RKE2 cluster from Rancher onto Harvester, only two out of the three nodes will successfully join the cluster. 

**To Reproduce**
1. Using Rancher 2.6.1 and Harvester 0.3.0, go to Rancher and provision an RKE2 cluster on Harvester. 
2. Use the JeOS `SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2` image
3. Add user data to install needed packages:
```
#cloud-config
runcmd:
- zypper ar -cfG 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/oss/' tuna-oss
- zypper ar -cfG 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/non-oss/' tuna-non-oss
- zypper ref
- zypper -n in glibc-2.34-2.1.x86_64 glibc-locale-base-2.34-2.1.x86_64 filesystem-84.87-3.1.x86_64 apparmor-parser
```
4. one out of three nodes will fail to boot

**Expected behavior**
All three nodes should boot 

**Environment:**
 - Harvester ISO version: v0.3.0
 - SLES version: SLES15-SP3-JeOS.x86_64-15.3

**Additional context**

**Comment by wjimenez5271** [comment]
Rancher engineering suggests that this is fixed by: https://github.com/rancher/rancher/pull/35054

**Comment by guangbochen** [comment]
**To Test:**
- Provisioning the RKE2 cluster on Harvester with Rancher `v2.6.3-rc1`.
- Use the JeOS `SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2` image
- Add user data to install needed packages:
```
#cloud-config
runcmd:
- zypper ar -cfG 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/oss/' tuna-oss
- zypper ar -cfG 'https://mirrors.tuna.tsinghua.edu.cn/opensuse/tumbleweed/repo/non-oss/' tuna-non-oss
- zypper ref
- zypper -n in glibc-2.34-2.1.x86_64 glibc-locale-base-2.34-2.1.x86_64 filesystem-84.87-3.1.x86_64 apparmor-parser
```
- all nodes and the cluster should be up and running successfully.

**Comment by FrankYang0529** [comment]
RKE2 cluster can be created with Rancher `v2.6.3-rc1` and JeOS `SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2`.

![Screen Shot 2021-11-22 at 4 26 44 PM](https://user-images.githubusercontent.com/4927361/142828161-83030c44-97b4-433b-bf87-64e47059d1d1.png)
![Screen Shot 2021-11-22 at 4 29 37 PM](https://user-images.githubusercontent.com/4927361/142828190-b505b77d-2501-449b-968c-ca4191e1fdd3.png)
