### ISSUE TITLE
[BUG] Backup-target show old error message when connecting to new target

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1499]
### Describe the bug
when set up backup-target with a invalid server, error message popped; then trying another invalid server, the error message still shows old one.

### To Reproduce
1. install Harvester with any nodes
2. navigate to *Advanced* -> *Settings*
3. edit _**backup-target**_ and input an invalid NFS like `nfs://127.0.0.1/invalid/endpoint`
4. wait until the error message shown
5. edit _**backup-target**_ and input another invalid NFS like `nfs://localhost/invalid/endpoint`

### Expected behavior
Error message should show the latest one.

## Environment:
 - Harvester ISO version: **master-d05a6cc7-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**
 - `ui-source` Option: Bundled

### Additional context
[similar case]
![image](https://user-images.githubusercontent.com/5169694/139617852-264050a8-d93b-4ad9-955b-f9c73277c8bf.png)

**Comment by lanfon72** [comment]
Root cause of this bug is, backup-target still in connecting state (as #1498 described), and the *old* error message box didn't set to invisible.

**Comment by lanfon72** [comment]
moved from #1498, also close #1498
### The problem
when we establish connection to the backup-target, in some case, connection spend a long waiting for server response, and the UI didn't show any message to display current state is succeed or connecting.

### The solution
Add an *Info* message box to display current state.

### The Alternatives
An loading icon for alternative.

### Additional Context
This case can be reproduced when you connect to an **NFS** Type, and connect to an server not provide NFS service, such like `localhost`.

**Comment by lanfon72** [comment]
ref to #1051

**Comment by WuJun2016** [comment]
hi，@lanfon72   now save the configuration backend will check, there is no way to configure the invalid backup-target,    I think this issue has been fixed.    Can you help verify it

**Comment by lanfon72** [comment]
close this issue as it is fixed following #1051 , and unable reproduce the original case.
