### ISSUE TITLE
duplate display name of the os image

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#15]
**Issue:**
currently, the display name is auto-generated by its URL name and we don't validate whether its name is duplicated or not, the backend should add validation to this.

**Solution:**
The backed API should validate the display name and auto-increment the display name by 1. e.g `os-aaacc` to `os-aaacc1`

**Comment by gitlawr** [comment]
I think we shouldn't implicitly change the name, just pop the validation and let users do the decision.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/28

**Comment by guangbochen** [comment]
close in favor of #28
