### ISSUE TITLE
An error message shows if the URL is blank or begins/ends with spaces

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#150]
**Steps to reproduce:**
Fill in a valid URL and then remove it

**OR**

Add spaces at the beginning or at the end of the URL

**Result:**
In the above three cases, it's not necessary to display an error message
![image](https://user-images.githubusercontent.com/57614736/93500222-9caf9100-f946-11ea-99df-a3bdefae7c13.png)

**Comment by WuJun2016** [comment]
Fill in a valid URL and then remove it.  (In this case, I think the error message should be displayed)。 @guangbochen @DoNotSayYes

**Comment by DoNotSayYes** [comment]
> Fill in a valid URL and then remove it. (In this case, I think the error message should be displayed)。 @guangbochen @DoNotSayYes

`Fill in a valid URL and then remove it.` just like users are not typing in anything at all, what is the necessity of showing this error message? @WuJun2016 

And another case is if users type in the URL letter by letter, the error message will show all the time until users finish completing the whole URL. Could we just do the validation just before submitting the request?

**Comment by DaiYuzeng** [comment]
@DoNotSayYes 
After clicking the create/edit button, an error message will be displayed , but it will not be hidden until the next click.
Does it make sense?

**Comment by DoNotSayYes** [comment]
Validated
