### ISSUE TITLE
[BUG] Multiple instance creation VMs do not match the set number

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#1504]
**Describe the bug**
**VMs** are created by means of **multiple instances**, the actual number of VMs created does not correspond to the number configured, **only one** VM is created

**To Reproduce**
1. Create a VM using multiple instances and set count to 10
2. After the creation, go back to the VM list and check the currently added VMs
3. Only one VM is created

**Expected behavior**

There should be 10 VMs created
**Support bundle**

**Environment:**
 - Harvester ISO version: master-9cde746b-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
I think that this is related to https://github.com/harvester/harvester/issues/1512

**Comment by TachunLin** [comment]
Verified **fixed** on master-d21b9161-head , Close this issue.

### Result
Now create VM using 10 multiple instances can actually create 10 VMs accordingly
![image](https://user-images.githubusercontent.com/29251855/140714245-e86832b1-e9d3-4fe3-93bc-2de692d02416.png)

All VMs can starting and get ip address. 

### Test Information
* Test Environment: 3 nodes harvester on provo bare machines
* Harvester version: master-d21b9161-head


### Verify Steps

1. Create VM by using multiple instances option and set count to 10
2. Return to Virtual Machine page, wait for all VM created
3. Check VMs status

### Additional Context
![image](https://user-images.githubusercontent.com/29251855/140713878-18cd3cc2-6e20-4eef-a660-a69431af5b99.png)
