### ISSUE TITLE
[BUG]  Refreshing the page causes the vm migration status to disappear

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1516]
**Describe the bug**

refreshing the page causes the vm migration status to disappear

**To Reproduce**
1.  create a vm
2.  migrate this vm
3.  This vm status shows migration
4.  Refresh the page, the status of the migrated vm is shown as running

**Expected behavior**

If the migration has not been completed, the status should be displayed as migration

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-d21b9161-head. Close this issue.

### Result
Refresh virtual machine page when vm is migrating, the vm migration will always keep in `migrating` status
![image](https://user-images.githubusercontent.com/29251855/140866721-b245994f-aec2-4806-ae9a-7ef148e3d933.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine (RackD8 Cluster A) 
* Harvester version: master-d21b9161-head

### Verify Steps

1. Create a virtual machine
2. Migrate the virtual machine
3. Refresh page several times while virtual machine status show `migrating`

### Additional Context
None
