### ISSUE TITLE
[BUG] Network type "bridge" reverting to default "masquerade" on management network

### ISSUE THREAD

**Issue by WolframRavenwolf** [harvester/harvester#1517]
**Describe the bug**
VM's management network type always resets to default "masquerade" when I change it to "bridge". There's no error message and it looks like the change is applied, but upon reopening the config page, it's back on "masquerade". Doesn't matter if the VM is newly created, stopped or running - always the same, wrong behavior.

**To Reproduce**
1. Create a new VM - I used the VM template "harvester-public/iso-image-base-template" and the latest k3os-amd64.iso image. All settings default except for network type "bridge".
2. Once the VM has been created, check network type - it's back to "masquerade"!
3. Try to get it to "bridge" - no matter if the VM is running or stopped, it always reverts.

**Expected behavior**
When "bridge" is selected, it should remain selected and be applied. And using default settings with my main network, I'd expect the VM to be bridged to my LAN network and accessible from the outside.

**Support bundle**
[supportbundle_43cce680-695a-4e67-8622-766b7dee6f2f_2021-11-05T15-29-17Z.zip](https://github.com/harvester/harvester/files/7487158/supportbundle_43cce680-695a-4e67-8622-766b7dee6f2f_2021-11-05T15-29-17Z.zip)

**Environment:**
 - Harvester ISO version: v0.3.0
 - Underlying Infrastructure: Baremetal with Dell Optiplex 3060/7040/7050

**Additional context**
Related to https://github.com/harvester/harvester/issues/1467 - getting a working bridge to your main network should be easy since that's probably the simplest and most common use case.

**Comment by rrajendran17** [comment]
@WolframRavenwolf I tried this on v1.3.1 harvester version and vm image using https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img and I do not see any issue.
The network type stays in "bridge" for the management network.

Can you check if still see the issue in latest and if yes can you provide more details about what type of image you used to create the vm ?

**Comment by WolframRavenwolf** [comment]
Years have passed since I reported this bug, and the software has likely evolved to the point where the issue is no longer relevant. As for me, I no longer work in this field and therefore cannot verify or provide additional information. From my perspective, you are welcome to close the ticket.
