### ISSUE TITLE
[BUG] Unable to create RKE1 cluster in rancher by node driver, shows "waiting for ssh to be available"

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1519]
**Describe the bug**

Can't create harvester RKE1 cluster in rancher by using harvester node driver. 
Keep in provisioning state with wait for ssh available 
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/a2843e7d-68be-40c8-be0c-630bea5a5695)

Erroe message: 
`Error creating machine: Error detecting OS: Too many retries waiting for SSH to be available. `

![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/1771711c-e858-48e0-a597-6c606b4f835e)

**To Reproduce** 
1. Create 3 nodes harvester cluster
2. Enable network, set harvester-mgmt as NIC 
3. Create vlan1 with id 1
4. Create ssh key by using `~/.ssh/id_rsa.pub`
5. Docker install rancher 2.6.2
6. Import harvester cluster in rancher virtual management page
7. Enable harvester node driver in cluster -> drivers page
8. Create harvester cloud credential in rancher 
Follow document steps 
https://docs.harvesterhci.io/v0.3/rancher/rke1-cluster/ 
9. Create a RKE1 harvester cluster, add template
10. Provide required value in field (ssh user: `ubuntu`)
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/d0ae1323-b07c-46b3-b118-0a7e0fd193f8)
11.  Provide cluster name and name prefix 
12. Check etcd and control panel
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/aba980d4-636c-41e6-a6f2-d3b62b4d1dd3)

13. Click create button

**Expected behavior**

Should create RKE1 harvester cluster in rancher dashboard correctly

**Support bundle**

[supportbundle_5ecc499f-1933-4642-82c0-206575951304_2021-11-07T16-53-23Z.zip](https://github.com/harvester/harvester/files/7492719/supportbundle_5ecc499f-1933-4642-82c0-206575951304_2021-11-07T16-53-23Z.zip)

**Environment:**
 - Harvester ISO version: master-d21b9161-head
 - Rancher version: 2.6.2 and 2.6.1 (with v1.21.6-rancher1-1) 
 - image: focal-server-cloudimg-amd64.img
 - Underlying Infrastructure: 3 nodes harvester on local kvm machines
                                             

**Additional context**
Can create virtual machine correctly on harvester cluster with IP assigned in vlan1
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/f7836481-edbd-4e57-baef-e585b7dff2d3)

**Comment by guangbochen** [comment]
This seems like a rancher-related bug, @TachunLin can u please try if the Rancher v2.6.2 will encounter the same issue, thanks?

**Comment by TachunLin** [comment]
@guangbochen , Sorry I did not provide full information since yesterday I have both tested 2.6.1 and 2.6.2 on my local kvm environment. Today I test this issue again using rancher 2.6.2 on provo bare machine, but still failed. 

Let me update the environment information in issue description

**Comment by TachunLin** [comment]
After several trials and consult team members, now I can provision RKE1 cluster in rancher 2.6.2. 
To make it work, I found some clues   

1. Harvester node need to be installed within the same subnet with rancher 
2. Install one node harvester instead of 3 nodes
3. Allocate enough cpu and memory to harvester node (e.g cpu: 10 core, memory: 32GB)

![image](https://user-images.githubusercontent.com/29251855/142244096-f284206d-2027-481b-a1b4-fae743450789.png)

This issue is not relating to ssh user since the ssh key is generated by node driver during provisioning. 

Thus when we encounter provisioning fail, we may start troubleshooting in

1. Network connectivity between harvester and rancher
2. Allocate enough resource to harvester node

**Comment by guangbochen** [comment]
@TachunLin why only use one node harvester, users should be able to add as many nodes as they want of the Harvester cluster and spin up guest k8s clusters on it when it has enough resources.
Additionally, feel free to close if u found this is not a bug, thanks.

**Comment by TachunLin** [comment]
Verified **fixed** on master-d577bb6c-head with rancher v2.6.3-rc1 (node driver v.0.3.4). 
Close this issue.

Confirmed can provision 3 nodes RKE1 cluster on harvester under the following circumstance:

1. Harvester node need to be installed within the same subnet with rancher
2. Allocate enough cpu and memory to harvester node 

![image](https://user-images.githubusercontent.com/29251855/142876571-2d26ba6f-a81a-4c0e-8f4e-3f386adf16f1.png)

![image](https://user-images.githubusercontent.com/29251855/142876618-c9a6ba35-4830-4fe0-8a4f-2f7b5a856f70.png)

![image](https://user-images.githubusercontent.com/29251855/142877029-b854d044-c1e1-4ce4-878e-36a1fa15ccf9.png)

**Comment by twoody2007** [comment]
I am currently experiencing this issue with the host on the same subnet as the nodes, using the same VM image as well. I am using the same versions as TachunLin

Perhaps there Is there some other required harvester configuration that isn't documented yet?
