### ISSUE TITLE
[BUG] incorrect title and favicon

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1520]
### Describe the bug
Dashboard shows incorrect title and favicon when access with login-ed session.
![image](https://user-images.githubusercontent.com/5169694/140692811-614270a8-688a-4773-a56f-5e8507a12278.png)

### To Reproduce
1. Install Harvester And setup default password
2. Login to the dashboard, and it displays correct one.  (_Harvester_ and green favicon)
3. Open another tab, access to `https://<vip>/`, will be redirect to dashboard page
4. Then the title displays _**Rancher**_ and blue favicon (rancher's icon)

### Expected behavior
Step 2. and 4. visiting same URL, it should have the same behavior.

## Environment:
 - Harvester ISO version: **master-d21b9161-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**
 - _ui-source_ Option: **External**  (select _Bundled_ hit the issue too)

**Comment by noahgildersleeve** [comment]
Tested in master-119c2c48-head. Verified as fixed. Tested in 
1. main page
2. settings
3. support
