### ISSUE TITLE
[BUG] Agent node becomes NotReady when one of the controller node fails

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1521]
**Describe the bug**

The HA doesn't seem to work well. When a controller node fails, agent nodes might fail too.
VMs on the agent nodes might become Terminating.

**To Reproduce**
**NOTE** this doesn't always repro.

1. Create a 4-node cluster.
2. 3 nodes will become controller nodes.
```
# kubectl get nodes
kubectl get nodes -o wide
NAME    STATUS   ROLES                       AGE     VERSION          INTERNAL-IP   EXTERNAL-IP   OS-IMAGE               KERNEL-VERSION         CONTAINER-RUNTIME
node1   Ready    control-plane,etcd,master   7d11h   v1.21.5+rke2r1   10.10.0.11    <none>         v20211007 (04ec006)   5.3.18-59.24-default   containerd://1.4.9-k3s1
node2   Ready    <none>                      7d11h   v1.21.5+rke2r1   10.10.0.12    <none>         v20211007 (04ec006)   5.3.18-59.24-default   containerd://1.4.9-k3s1
node3   Ready    control-plane,etcd,master   7d11h   v1.21.5+rke2r1   10.10.0.13    <none>         v20211007 (04ec006)   5.3.18-59.24-default   containerd://1.4.9-k3s1
node4   Ready    control-plane,etcd,master   7d11h   v1.21.5+rke2r1   10.10.0.14    <none>         v20211007 (04ec006)   5.3.18-59.24-default   containerd://1.4.9-k3s1
```
3. Log in to the agent node, check `/var/lib/rancher/rke2/agent/etc/rke2-agent-load-balancer.json`
```
# on node2
# cat /var/lib/rancher/rke2/agent/etc/rke2-agent-load-balancer.json
{
  "ServerURL": "https://10.10.0.13:9345",
  "ServerAddresses": [
    "10.10.0.11:9345",
    "10.10.0.13:9345",
    "10.10.0.14:9345"
  ],
  "Listener": null
}
```
4. Stop or shut down the controller node whose IP address is `10.10.0.13`.
5. After the controller becomes `NotReady`, the agent node becomes `NotReady` too.
```
kubectl get nodes
NAME    STATUS     ROLES                       AGE     VERSION
node1   Ready      control-plane,etcd,master   7d11h   v1.21.5+rke2r1
node2   NotReady   <none>                      7d11h   v1.21.5+rke2r1
node3   NotReady   control-plane,etcd,master   7d11h   v1.21.5+rke2r1
node4   Ready      control-plane,etcd,master   7d11h   v1.21.5+rke2r1
```
**Expected behavior**

The agent node should continue working if one controller node fails.

**Support bundle**

**Environment:**
 - Harvester ISO version: 0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

- rke2-agent logs on node2: [rke2-agent.log](https://github.com/harvester/harvester/files/7497917/rke2-agent.log)
- https://docs.rke2.io/install/ha/#1-configure-the-fixed-registration-address

**Comment by bk201** [comment]
It somehow might be related to the boot order of machines (in my case they are VMs).
If I start all my 4 VMs at the same time, this is easy to reproduce.
But if I start controller nodes first and wait for all controller ready, then starting the agent node laster, the agent node doesn't go into NotReady if one controller node fails.

**Comment by gitlawr** [comment]
See the cause in https://github.com/rancher/rke2/issues/2101. If we change the server address in `/var/lib/rancher/rke2/agent/kubelet.kubeconfig` to loopback address the node can recover.
 I open the ticket for discussion but I'm not sure if it's an upstream bug though. As rke2 docs suggest to use a fixed url for HA setup, I think this can be resolved when we use the vip as the server_url for joining nodes.
@bk201 Can you verify if that's the case?

**Comment by bk201** [comment]
@gitlawr I'm using the VIP in rancherd config to join a node, but the VIP is not used when rancher deploys RKE2.
Need to figure out a way how to do that.
```
node3:~ # cat /etc/rancher/rancherd/config.yaml
server: https://10.10.0.100:8443     <--- VIP
role: agent
token: 'aa bb cc'
kubernetesVersion: v1.21.5+rke2r1
labels:
 - harvesterhci.io/managed=true
 
 node3:~ # cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml
{
  "node-label": [
    "harvesterhci.io/managed=true",
    "rke.cattle.io/machine=3be7358b-af61-4d0d-85dd-43e2ba01c8a8"
  ],
  "server": "https://10.10.0.14:9345",     <--- one of the server node IP
  "token": "aa bb cc"
}
```

I manually edit `server` in ` /etc/rancher/rke2/config.yaml.d/50-rancher.yaml` to the VIP and confirm the agent will use local LB after servers are up:

```
node3:~ # cat /var/lib/rancher/rke2/agent/kubelet.kubeconfig | grep server
    server: https://127.0.0.1:6443
    certificate-authority: /var/lib/rancher/rke2/agent/server-ca.crt
```

These are spotted in the agent's log and killing a server node **won't** make the agent node become NotReady.
```
Nov 11 14:25:05 node3 rke2[1954]: time="2021-11-11T14:25:05Z" level=info msg="Updating load balancer server addresses -> [10.10.0.12:6443 10.10.0.14:6443 10.10.0.11:6443 10.10.0.100:6443]"
Nov 11 14:25:05 node3 rke2[1954]: time="2021-11-11T14:25:05Z" level=info msg="Updating load balancer server addresses -> [10.10.0.14:9345 10.10.0.11:9345 10.10.0.12:9345 10.10.0.100:9345]"
```

**Comment by bk201** [comment]
@gitlawr We can work around this by overriding the server URL on agent nodes:
```
# cat /etc/rancher/rke2/config.yaml.d/91-harvester-vip.yaml
server: https://10.10.0.100:9345
```

In my tests when VIP is ready, the agent can get the correct server list and will use the local LB endpoint.

**Comment by bk201** [comment]
For testing plan, please see the description of https://github.com/harvester/harvester-installer/pull/171

**Comment by lanfon72** [comment]
Verified the bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 4 nodes**
* Harvester Version: **master-655c251a-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with 4 nodes which joining node MUST join by VIP (point `server-url` to use VIP)
2. Make sure all nodes are ready
    a. Login to dashboard, check host **state** become `Active`
    b. SSH to the 1st node, run command `kubectl get node` to check all **STATUS** should be `Ready`
3. SSH to agent nodes which **ROLES** IS `<none>` in **Step 2b**'s output
   - [x] Output should contains VIP in the server URL, by run command `cat /etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml`
   - [x] Output should contain the line `server: https://127.0.0.1:6443`, by run command `cat /var/lib/rancher/rke2/agent/kubelet.kubeconfig`
   - [x] Output should contain the line `server: https://127.0.0.1:6443`, by run command `cat /var/lib/rancher/rke2/agent/kubeproxy.kubeconfig`
4. SSH to server nodes which **ROLES** contains `control-plane` in **Step 2b**'s output
    - [x] Check file should not exist in the path `/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml`
5. Shut down a server node, check following things
    - [x] Host **State** should not be `Active` in dashboard
    - [x] Node **STATUS** should be `NotReady` in the command output of  `kubectl get node`
    - [x] **STATUS** of agent nodes should be `Ready` in the command output of  `kubectl get node`
6. Power on the server node, wait until it back to cluster
7. repeat **Step 5-6** for other server nodes
