### ISSUE TITLE
[BUG] NIC are going down randomly or after a reboot, no error in kernel or logs... 

### ISSUE THREAD

**Issue by marcuspocus1** [harvester/harvester#1523]
**Describe the bug**
After a reboot or a certain period of time ( 48h + ), some NIC are going down / no-carrier... 
no error on kernel, no error on switches: they are flagged as No Carrier...

**To Reproduce**
bind 2 NIC together ( 25Gb NIC, 802.3ad or balance-tlb )
start some VM, let them runs for 48h +...

**Expected behavior**
NIC should stay up all the time !!

**Support bundle**
[supportbundle_b89bc142-c79a-4c6c-95a6-27838d57853b_2021-11-08T20-42-58Z.zip](https://github.com/harvester/harvester/files/7500316/supportbundle_b89bc142-c79a-4c6c-95a6-27838d57853b_2021-11-08T20-42-58Z.zip)
![Screen Shot 2021-11-08 at 4 02 28 PM](https://user-images.githubusercontent.com/79535752/140823949-85b57794-672e-4d4f-8427-9ab9cae1ea28.png)
![Screen Shot 2021-11-08 at 4 04 22 PM](https://user-images.githubusercontent.com/79535752/140823953-f1c3feb5-d6ef-4a50-9d28-f0e606e8cc1c.png)

**Environment:**
Version: v0.3.0-rc2-hotfix1b. 
HW: Dell Poweredge R740xd

**Additional context**
A way to fix the problem: 
log in via iDRAC, force the interface to go down, bring it back... fixed ! 
ip link set ens7f0np0 down
ip link set ens7f0np0 up
-≥ back online !

**Comment by tjjh89017** [comment]
Hi @marcuspocus1 
We didn't find out any error in the kernel log.
Could you help us to collect more logs after the link went down?
You can use iDRAC to bring it back and create support bundle again.
and if possible, using scp to copy whole folder `/var/log` to us.
Make sure we have 48+ hours logs for it, or the issue occurs.

And could you also provide SFP28 transceiver model and switch model?
It's better to get transicever detail info via `sudo ethool -m <interface name>`

thanks a lot

**Comment by tjjh89017** [comment]
@marcuspocus1 if update firmware will not help, please re-open this issue
thanks a lot
