### ISSUE TITLE
[BUG] Failed to enable vlan cluster network after disable and enable again, display "Network Error"

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1529]
**Describe the bug**

When user enable cluster network to `harvester-mgmt` then disable and try to enable it again. 
Not it can't be enabled and finally show error message "Network Error"

![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/9f2ccd31-60c8-4288-9d67-92b750767cab)

**To Reproduce**
1. Open settings and config vlan network
2. Enable network and set default `harvester-mgmt`
3. Disable network
4. Enable network again 

**Expected behavior**

User can disable and enable network with any choice provided in the list 

**Support bundle**

Unable to create bundle since network error
![image](https://user-images.githubusercontent.com/29251855/140946647-f60f4abf-b704-40cd-8560-588f67ac62a0.png)

**Environment:**
 - Harvester ISO version: master-d21b9161-head
 - Underlying Infrastructure: 1 harvester node on local kvm machine 

**Additional context**
In the begging, save button will keep saving for a long time then finally show "Network error"
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/95abcce6-619f-4e3c-89cd-bd16aa256702)

Actually the vlan setting keeps in disable 
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/e54041ee-03c1-4699-9449-963389cb5498)

**Comment by yaocw2020** [comment]
Due to the downtime after disabling the VLAN network.

**Comment by yaocw2020** [comment]
Probable the same reason with https://github.com/harvester/harvester/issues/1464

**Comment by TachunLin** [comment]
Verified **fixed** master-f6bc010b-head (11/30). Close this issue.

### Result
User can disable and enable network with default `harvester-mgmt`. 
Harvester dashboard and network work as expected

### Test Information
* Test Environment: 3 nodes harvester on local kvm machines
* Harvester version: master-f6bc010b-head

### Verify Steps
1. Open settings and config vlan network
2. Enable network and set default harvester-mgmt
3. Disable network
4. Enable network again
5. Check Host, Network and harvester dashboard
6. Repeat above steps several times
