### ISSUE TITLE
Typos

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#153]
- [x] 1. On the delete prompt box, attempting is missing a t. (also remove the virtual machine just call it image)
![image](https://user-images.githubusercontent.com/57614736/93562420-98bc5700-f9b8-11ea-8d39-7bf801a8944e.png)

- [x] 2. For the name length restriction case, it's better to say: 
`Name cannot be longer than 63 characters -> "Name" cannot be more than 63 characters.`
![image](https://user-images.githubusercontent.com/57614736/93562694-2009ca80-f9b9-11ea-84dc-142f18d6c783.png)

- [x] 3. Required fields not completed! In this case, it's better to say: Required fields are not completed! Or anything else can make it better
![image](https://user-images.githubusercontent.com/57614736/93580121-f0b38780-f9d1-11ea-86cb-186fc3d8c113.png)

**Comment by gitlawr** [comment]
Validated
