### ISSUE TITLE
[BUG]  The resources of the system namespace should not be displayed

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1533]
**Describe the bug**

![image](https://user-images.githubusercontent.com/24985926/141079713-7fa98175-b9ff-40b6-81de-d2254c685ff6.png)

**To Reproduce**
1. Go to volume page
2. resources belonging to the cattle-monitoring-system namespace exist

**Expected behavior**

The volume in cattle-monitoring-system should not be displayed

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-119c2c48-head. Close this issue.

### Result
Now there is no cattle-monitoring-system volume show up on the volumes page 
![image](https://user-images.githubusercontent.com/29251855/141135474-be8348c9-4f10-457b-8330-c370805d6938.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-119c2c48-head

### Verify Steps

1. Create several volumes or keep empty
2. Open Volumes page 

### Additional Context
None
