### ISSUE TITLE
[BUG] VM memory display in long bytes value instead GB on virtual machine page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1534]
**Describe the bug**

Create VM with 4GB memory, but it displays memory value `2863311530` on the virtual machine page

![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/c08db590-d337-40c5-bdca-10cac804ff74)

**To Reproduce**
1. Create an virtual machine
2. Give 4GB memory 
3. Provide required information and create vm 
4. Check the memory value on virtual machine page 

**Expected behavior**

Should display virtual machine value in GB unit 

**Support bundle**

**Environment:**
 - Harvester ISO version: master-119c2c48-head
 - Underlying Infrastructure: 3 nodes harvester on provo bare machines (RackD8 ClusterA) 

**Additional context**
Memroy unit on VM creation page 
![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/ff18decc-bbe5-4fdc-85d9-ca39f18609f8)

**Comment by WuJun2016** [comment]
@TachunLin  I set up 4GB of memory without reproducing this issue, the long unit should be returned by the backend, I don't know under what circumstances the backend will convert the unit 。  cc @guangbochen

**Comment by TachunLin** [comment]
@WuJun2016 
This issue can be reproduced with master-119c2c48-head on both my local laptop and 
provo bare machines (RackD8, ClusterA) 
Today I tested again on my local kvm, it still happen here.
![image](https://user-images.githubusercontent.com/29251855/141231209-b245a4b1-e23a-47db-bc55-9cc496230cc6.png)

I just create images, setup network, add ssh keys then create a virtual machine. 
Then the VM record shows long bit value.

**Comment by lanfon72** [comment]
this should be caused by #1429

**Comment by weihanglo** [comment]
Note that the value is the exact bytes after memory overcommit calculation. If we want to truncate that value in the backend we'll also affect the actual memory requested.

**Comment by WuJun2016** [comment]
@TachunLin  What is the value of overcommit-config in your environment?  It seems that the default overcommit-config value does not have a unit problem, I need to reproduce it to convert to the correct unit。

**Comment by TachunLin** [comment]
@WuJun2016 
The overcommit-config value keeps in default without changing it. This issue can be reproduce by using the master-119c2c48-head version with out extra configuration. 
![image](https://user-images.githubusercontent.com/29251855/141997194-e05de866-3aa0-4dc1-9471-5095e5bfc7b1.png)

**Comment by wangpan-hqu** [comment]
> @WuJun2016 The overcommit-config value keeps in default without changing it. This issue can be reproduce by using the master-119c2c48-head version with out extra configuration. ![image](https://user-images.githubusercontent.com/29251855/141997194-e05de866-3aa0-4dc1-9471-5095e5bfc7b1.png)

In my  harvester UI setting, there is not overcommit-config, why ? (harvester 0.3)

**Comment by guangbochen** [comment]
> In my harvester UI setting, there is not overcommit-config, why ? (harvester 0.3)

this is a new feature that will be supported via v1.0.0, thanks.

**Comment by wangpan-hqu** [comment]
> > In my harvester UI setting, there is not overcommit-config, why ? (harvester 0.3)
> 
> this is a new feature that will be supported via v1.0.0, thanks.

how to get the lastest version？The latest version is only 0.3  in the github, can you give me a link，thanks

**Comment by WuJun2016** [comment]
> > > In my harvester UI setting, there is not overcommit-config, why ? (harvester 0.3)
> > 
> > 
> > this is a new feature that will be supported via v1.0.0, thanks.
> 
> how to get the lastest version？The latest version is only 0.3 in the github, can you give me a link，thanks



https://github.com/harvester/harvester-installer/wiki/Development-ISO-Build

**Comment by TachunLin** [comment]
Verified **fixed** on master-45e25939-head.Close this issue.

### Result
Now VM created in different amount of memory can reflect correct format to actually reflect the input value in creation. 
![image](https://user-images.githubusercontent.com/29251855/142519970-f9603e69-8f23-4010-9bbe-b4235e0fb44c.png)

![image](https://user-images.githubusercontent.com/29251855/142520528-181921a5-e1b5-477c-8d1f-d95fe8836001.png)


### Test Information
* Test Environment: 3 nodes harvester on provo bare machines
* Harvester version: master-45e25939-head

### Verify Steps

1. Create an virtual machine
2. Give different amount of memory
3. Provide required information and create vm
4. Check the memory value on virtual machine page
