### ISSUE TITLE
[FEATURE] NTP daemon in host OS

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1535]
**Is your feature request related to a problem? Please describe.**

We don't currently have an NTP daemon running in the host OS. This is causing issues with timestamps not matching up in areas like backups and snapshots.
**Describe the solution you'd like**

An NTP daemon that has the server populated by the NTP server selected in the installer.
**Describe alternatives you've considered**

**Additional context**

There is already an option in the installer for this, but it seems that it's not running after install, so it's just a single update. This is going to cause very large issues in a clustered environment and seems to be causing odd issues with Longhorn right now.

**Comment by bk201** [comment]
We use timesync feature of systemd if NTP servers are configured.
Run `systemctl status systemd-timesyncd.service` to check if it's alive.

**Comment by Jellyfrog** [comment]
Works for me.
```
# timedatectl timesync-status
       Server: 194.58.200.20 (ntp.se)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
         Leap: normal
      Version: 4
      Stratum: 1
    Reference: PPS
    Precision: 1us (-25)
Root distance: 30us (max: 5s)
       Offset: +85us
        Delay: 1.301ms
       Jitter: 127us
 Packet count: 53
    Frequency: +42.371ppm
```

**Comment by FrankYang0529** [comment]
@noahgildersleeve, could you please try again to set up the latest vagrant-ipx-harvester environment? I think we should get `timesync` if we set `ntp_servers` in harvester configuration. Thank you.

https://docs.harvesterhci.io/v0.3/install/harvester-configuration/

**Comment by noahgildersleeve** [comment]
Tested in master-119c2c48-head on 4 node setup that has been up for over 24 hours. All four nodes are within a few seconds. All nodes are showing NTP active via `sudo timedatectl status`. Mark as ready for testing and I will close the ticket.

**Comment by noahgildersleeve** [comment]
Tested in master-119c2c48-head on 4 node setup that has been up for over 24 hours. All four nodes are within a few seconds. All nodes are showing NTP active via `sudo timedatectl status`.
