### ISSUE TITLE
[BUG] Memory is being saved as the wrong amount in VMs

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1537]
**Describe the bug**

When you save a VM with a raw image template the amount of memory is showing as incorrect in the config
**To Reproduce**
1. Create a VM with a raw image template
2. Leave defaults as they are (1vcpu, 2gi memory)
3. Save VM
4. Check list for memory in VM
5. Open VM and check amount of memory
**Expected behavior**

The amount of memory should be what is set on creation
**Support bundle**

[supportbundle_59f99d92-cd77-47ab-96c9-27d2042ac7c4_2021-11-11T18-20-25Z.zip](https://github.com/harvester/harvester/files/7522529/supportbundle_59f99d92-cd77-47ab-96c9-27d2042ac7c4_2021-11-11T18-20-25Z.zip)

**Environment:**
 - Harvester ISO version: master-119c2c48-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**
This seems to be a regression and if you try to just open and save the config again after creating it then you get an error that says that it isn't a valid amount. It's showing as 1.33gi memory. The YAML is showing a few different amounts of memory. If you edit the VM after creation and set it to 2gi memory it shows up properly after saving. I'm attaching screenshots.
![Greenshot 2021-11-11 10 20 29](https://user-images.githubusercontent.com/83787952/141350496-dece6437-683d-4686-bd77-4e797498fa72.png)
![Greenshot 2021-11-11 10 26 35](https://user-images.githubusercontent.com/83787952/141350497-df07ba9b-cdee-486e-a6c9-dbddebcc927a.png)
![Greenshot 2021-11-11 10 30 29](https://user-images.githubusercontent.com/83787952/141350501-4b3d6b3f-9f9c-4e17-a148-08ca3d10bc74.png)
![Greenshot 2021-11-11 10 32 08](https://user-images.githubusercontent.com/83787952/141350651-2b8e98ea-1176-4b08-98df-43fe816786a2.png)

**Comment by guangbochen** [comment]
Memory is calculated in bytes but I think to be more user friendly can we calculate it in `Mi`, cc @weihanglo

**Comment by weihanglo** [comment]
> Memory is calculated in bytes but I think to be more user friendly can we calculate it in `Mi`, cc @weihanglo

AFAIK `resources` for memory only accept integer and there will be a precision loss if we truncating memory like that. Though it is technically achievable.

**Comment by noahgildersleeve** [comment]
This is a new issue that came up with the nightly build yesterday. @yasker  said that he thought it might be related to the changes with overprovisioning. https://github.com/harvester/harvester/pull/1492

**Comment by weihanglo** [comment]
The templates has been updated. This is ready for testing @noahgildersleeve. Thanks!

**Comment by lanfon72** [comment]
Verified this has been fixed following #1429

Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: ** master-45e25939-head**
* **ui-source** Option: **External**
* **overcommit-config** Setting:
```py
{
  "cpu": 1600,
  "memory": 150,
  "storage": 200
}
```

### Verify Steps:
1. Install harvester with any nodes
2. Create Image for VM creation
3. Create VM with 1vCPU and 2Gi memory
4. list view will display the VM with `1 CPU, 2Gi Memory`
5. Open Web VNC and login to shell
6. `lscpu` should display **CPU(s): 1**
7. `lsmem` should display **Total online memory: 2G**
