### ISSUE TITLE
Create a ssh key, and reading from a file by selecting a large file may cause the page to jam 

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#154]
**Steps to reproduce:**
1. On the ssh key create page
2. Click `Read From File`button and upload a large file. (Tested by uploading a dmg file)

**Result:**
By uploading a large file could cause the page to jam

**Suggestion:**
Add some restrictions, like only allow users to upload txt, yaml and yml this kinds of files

**Comment by guangbochen** [comment]
this is a public key so using `.pub` file extension check would make sense.

**Comment by DoNotSayYes** [comment]
Now all kinds of files are still able to be uploaded, reading from a file by selecting a large file could cause the page to jam. @DaiYuzeng

**Comment by DaiYuzeng** [comment]
We lost a few commits at the first merge for upstream, probably this fix was one of them  :-|

**Comment by DoNotSayYes** [comment]
Validated
