### ISSUE TITLE
Create an ssh key by filling nothing, an inappropriate error message shows

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#155]
**Steps to reproduce:**
1. On the SSH key create page
2. Not filling anything on the page then click the create button

**Result:**
An error message shows and says: Name cannnot longer than 63 characters. Actually nothing is populated
![image](https://user-images.githubusercontent.com/57614736/93564854-fc488380-f9bc-11ea-895a-52e490512f35.png)

**Comment by guangbochen** [comment]
addressed in https://github.com/rancher/harvester-ui/pull/99

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/94363609-ed1cb080-00f5-11eb-9f3b-768f589974b4.png)
