### ISSUE TITLE
[BUG] The password field in the Harvester continue login screen does not offer show/hide toggle

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#1550]
**Describe the bug**
The password field in the Harvester continue login screen does not offer show/hide toggle. This is a shortcoming for UX as user may
not always know what's been entered from the keyboard (i.e. forgot cap lock is accidentally on).

**To Reproduce**
1. Go to https://<VIP> to login again after initial setup is completed.

**Expected behavior**
There should be a show/hide toggle for the password field on continue login.

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): any

**Additional context**
![Harvester_login_again](https://user-images.githubusercontent.com/1808417/142084529-fd2aca43-796c-48fc-8e0f-4f10c2299306.png)

**Comment by lanfon72** [comment]
Verified _password field_ able to toggle to display password as plain text.
![image](https://user-images.githubusercontent.com/5169694/142395914-673c5953-01c3-4400-9cc2-235f507b0200.png)



Test Information
----
* Environment: **Bare metal DL360** 3 nodes
* Harvester Version: **master-45e25939-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. install harvester with any nodes
2. setup password
3. logout then login again
