### ISSUE TITLE
[BUG] Harvester populates VMs IP 6 minutes after deployment

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1553]
**Describe the bug**
Harvester only provides the VMs IP 6 minutes after deployment. Waiting for the IP (I think) slows down Rancher deployed cluster provisioning and the overall CPI.

<img width="1230" alt="Screen Shot 2021-11-17 at 8 47 25 AM" src="https://user-images.githubusercontent.com/5146963/142213060-3524c033-3d05-461f-9bd2-7019ad5c5c33.png">

<img width="1226" alt="Screen Shot 2021-11-17 at 8 48 14 AM" src="https://user-images.githubusercontent.com/5146963/142213078-a2c22127-9b62-49ca-a88b-0790a3b42ef2.png">

**To Reproduce**
Deploy a VM, look at the IP Address section and it will populate short of the 6 minutes age of the VM.

**Expected behavior**
The IP should be available as the VM becomes available and the qemu agent reports it (or however we acquire it the IP).

**Environment:**
 - Harvester ISO version: 0.3
 - Underlying Infrastructure: PowerEdge R620

**Comment by futuretea** [comment]
@abonillabeeche If the VLAN network is used, the IP address is displayed only after qemu-guest-agent is started.
The time an IP address displays depends on several factors:
1. Scheduling time (show state Starting in UI)
2. Start time (show state Running in UI, show system starting log in console)
3. qemu-guest-agent initialization time(show state Running in UI, show cloud-init log in console)

Can you help to test how long each stage takes:
1. state Starting
2. state Running but no IP is displayed
3. state Running  and IP is displayed

In my v1.0.0 environment, a vm created by "ubuntu-20.04-minimal-cloudimg-amd64.img
", ip will display after 2.3 minutes
![98802ba66b306bcb04b5836f71a61dc](https://user-images.githubusercontent.com/15064560/148860759-a9d49515-4483-4b3c-b3be-590d03193e41.png)

**Comment by abonillabeeche** [comment]
It takes
41 seconds to change to Running
1.2 min to allow ssh via the console
immediately has an IP and the qemu agent is running
```
Welcome to SUSE Linux Enterprise Server 15 SP3  (x86_64) - Kernel 5.3.18-59.37-default (ttyS0).

eth0: 10.0.0.201 2601:347:4200:7c30:3dae:4325:1c99:b87


ip-test login: abonilla
Password: 
No mail.
abonilla@ip-test:~> uptime
 14:26:12  up   0:00,  1 user,  load average: 0.73, 0.18, 0.06
abonilla@ip-test:~> systemctl | grep qemu
  qemu-ga@virtio\x2dports-org.qemu.guest_agent.0.service                                   loaded active running   QEMU Guest Agent                                                               
  system-qemu\x2dga.slice                                                                  loaded active active    Slice /system/qemu-ga
```

6 minutes to report an IP in the UI.
It did report an IPv6 IP for 3 seconds right when the state changed to Running but that quickly never comes up again.

**Comment by futuretea** [comment]
https://github.com/kubevirt/kubevirt/blob/28c8c9b529334c0d6a415289e263648bb670f03e/cmd/virt-launcher/virt-launcher.go#L355 The reason should be the `qemu-agent-sys-interval` , It default to 120s. Need a little more time to do a test.

**Comment by futuretea** [comment]
After changing this configuration `qemu-agent-sys-interval`, it still takes 6 minutes

**Comment by janeczku** [comment]
Observation: When migrating the VM right after the boot, the IP address is populated immediately.

**Comment by abonillabeeche** [comment]
To be clear - this issue is visible in RHEL/CentOS/Rocky and SLES - just not visible in Ubuntu.

**Comment by futuretea** [comment]
This issue is visible in a image which has qemu-guest-agent pre-installed.

After guest-agent connected and VM get IP,  the VM IP will be reported if we update the  vmi resource.

**Solution**
I'm going to add some logics to the vmi controller like this:
```go
func (h *VMNetworkController) SyncGuestStatus(id string, vmi *kv1.VirtualMachineInstance) (*kv1.VirtualMachineInstance, error) {
	if id == "" || vmi == nil || vmi.DeletionTimestamp != nil {
		return vmi, nil
	}

	logrus.Debugf("sync guest status of the vm: %s\n", vmi.Name)
	toUpdate := vmi.DeepCopy()
	if toUpdate.Annotations == nil {
		toUpdate.Annotations = make(map[string]string)
	}
	toUpdate.Annotations[util.AnnotationTimestamp] = time.Now().Format(time.RFC3339)
	if _, err := h.vmiClient.Update(toUpdate); err != nil {
		return nil, err
	}

	h.vmiController.EnqueueAfter(vmi.Namespace, vmi.Name, 1*time.Minute)

	return vmi, nil
}
```

**Comment by vasiliy-ul** [comment]
Hey, I think a similar issue was observed in KubeVirt not so long ago. In short: there was a delay of several minutes before the VMI status was updated with the IP address from the guest agent. Though it was happening only in the test with multiple NICs:

https://github.com/kubevirt/kubevirt/pull/6997#issuecomment-1019546079

The fixes are already merged upstream and should be included in KubeVirt v0.50.0: https://github.com/kubevirt/kubevirt/pull/7131 and https://github.com/kubevirt/kubevirt/pull/7135 .

It would make sense to test with 'clean' KubeVirt images (0.49.0) and then with the fix applied (just to ensure this is the same issue). The 0.49.0 images are already availalbe and I can also backport the fixes. Though will probably need some help with testing that scenario.

**Comment by vasiliy-ul** [comment]
I prepared the images with backported fixes. Could someone with proper environment check if they solve the issue?
- The 'clean' KubeVirt images (**without** the fixes) are available at `registry.suse.com/suse/sles/15.3/virt-*` with the tag `0.49.0-150300.8.10.1`.
- The 'fixed' images (**with** the backported patches) can be pulled form `registry.suse.com/harvester-beta/virt-*` using the tag `0.49.0-1`.

**Comment by futuretea** [comment]
> I prepared the images with backported fixes. Could someone with proper environment check if they solve the issue?
> 
> * The 'clean' KubeVirt images (**without** the fixes) are available at `registry.suse.com/suse/sles/15.3/virt-*` with the tag `0.49.0-150300.8.10.1`.
> * The 'fixed' images (**with** the backported patches) can be pulled form `registry.suse.com/harvester-beta/virt-*` using the tag `0.49.0-1`.

Thanks a lot.
I have tested quay.io/kubevirt/virt-* with the tag `v0.50.0` which solve this issue (populate VMs IP < 2 minutes)
I'm going to test  the `registry.suse.com/harvester-beta/virt-*` using the tag `0.49.0-1`.

**Comment by futuretea** [comment]
@vasiliy-ul @guangbochen I have tested `registry.suse.com/harvester-beta/virt-*` with the tag `0.49.0-1` which solve this issue (populate VMs IP < 2 minutes)

**Comment by guangbochen** [comment]
Thanks and I will bump the image version on the related PR https://github.com/harvester/harvester/pull/1939 later for the verification, thanks.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-9ecb4f9d-head`. Verified as fixed.
## Verification Steps
1. Create new SLES VM from [image](https://transfer.susedemo.com/share/kiwi/SLES15SP3_20220215_v7.qcow2) with external VLAN
2. Wait for VM to get IP
3. Check amount of time passed
![Screenshot from 2022-03-02 12-54-35](https://user-images.githubusercontent.com/83787952/156448247-3da7baac-e35e-4244-b5b7-885427e2ea91.png)
![Screenshot from 2022-03-02 12-54-16](https://user-images.githubusercontent.com/83787952/156448249-32985f87-7ea1-4943-9da6-d9d4c2ccf55a.png)
