### ISSUE TITLE
[BUG] Grub Menu displays **cOS** instead of Harvester

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1559]
### Describe the bug
Grub Menu displays **cOS**, it was displayed **Harvester xxxxx**
![image](https://user-images.githubusercontent.com/5169694/142373513-d217ea82-d6f6-41b6-9e73-28566fbe42f6.png)

### To Reproduce
1. install Harvester and monitoring

### Expected behavior
It should displays the format like **Harvester <version>**

**Comment by bk201** [comment]
This will be addressed in https://github.com/harvester/harvester-installer/pull/160 too.

**Comment by lanfon72** [comment]
Verified it has been fixed.
![image](https://user-images.githubusercontent.com/5169694/143169254-cde7f933-52ad-4938-ab24-0d593b58a89a.png)


Test Information
----
* Environment: **qemu/KVM** single node
* Installer Version: **cdb4841**

### Verify Steps:
1. install harvetster
2. reboot to check grub menu
