### ISSUE TITLE
[BUG]Inconsistency in API HeadBucket between S3 and Minio

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#1562]
**Describe the bug**

After the fix of #1339 , it works with S3, but minio replacement breaks.

**To Reproduce**
1. Edit backup target to "S3", with a minio installed in cluster or independently, edit config like 
{
  "type": "s3",
  "endpoint": "http://192.168.3.31:9000",
  "accessKeyId": "",
  "secretAccessKey": "",
  "bucketName": "backupbucket",
  "bucketRegion": "us-east-1",
  "cert": "",
  "virtualHostedStyle": true
}

it will report error:
operation error S3: HeadBucket, exceeded maximum number of attempts, 3, https response error StatusCode: 0, RequestID: , HostID: , request send failed, Head "http://backupbucket.192.168.3.31:9000/": dial tcp: lookup backupbucket.192.168.3.31 on 10.53.0.10:53: no such host      

**Expected behavior**

The minio replacement of S3 should still work.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
Baremetal Server, single node harvester, master-head ISO

**Additional context**

related issues:
#1051
#1339

**Comment by w13915984028** [comment]
A quick analysis, 

When "HeadBucket" is called and the "Endpoint" is not NULL, AWS sdk will try to build an URI,  here it becomes "http://backupbucket.192.168.3.31:9000/":

But the DNS does not know it. It causes the error.

Before commit of #1339, the "ListBuckets" API is called, it does not care about bucket name,  the credential is used to get all buckets. the URL is not changed.

S3 endpoint is in different format comparing with minio, need to consider how to identify them.

The worst solution is to try "HeadBucket" first, then "ListBucket", if both fail, then report fail.

**Comment by w13915984028** [comment]
Planed solution is:

check the endpoint, if it is not empty and not contains "amazonaws.com", assume it is NONE s3, then call ListBuckets, 
in other cases, call HeadBucket

It is verified locally.

```
awss3EndpointKeyword = "amazonaws.com"
       if target.Endpoint != "" && !strings.Contains(target.Endpoint, awss3EndpointKeyword) {
              // s3 replacement, like minio
               output, err := client.ListBuckets(h.ctx, &s3.ListBucketsInput{})
               if err != nil {
                       return err
           } else {
             // aws s3
              headBucketInput := s3.HeadBucketInput{
                      Bucket: &target.BucketName,
              }
       ....
```

**Comment by w13915984028** [comment]
s3 url format (endpoint):
https://docs.aws.amazon.com/AmazonS3/latest/userguide/VirtualHosting.html
https://stackoverflow.com/questions/47755043/what-is-difference-between-aws-s3-virtual-hosted-style-url-v-s-path-style-url

```
In a virtual-hosted–style:
  http://bucket.s3.amazonaws.com
  http://bucket.s3-aws-region.amazonaws.com.


In a path-style URL : 
  http://s3.amazonaws.com/bucket
  http://s3-aws-region.amazonaws.com/bucket
```

for minio (s3 replacement): the endpoint is required, like
```
  https://minio-service.default:9000
  http://127.0.0.1:9000
```

**Comment by w13915984028** [comment]
Local test: set the backup target as s3, or s3 replacement minio.

Please notice: when error, the return messages have difference between them.

```
                                           s3                             minio
valid input                                 OK                            OK
none existing  bucket                  NotFound                       bucket ´name´ does not exist
credential error                 api error Forbidden: Forbidden       api error InvalidAccessKeyId: The Access Key Id you provided does not exist in our records
```

**Comment by w13915984028** [comment]
The new update below, makes s3 and minio both works. There issue here is gone.

https://github.com/harvester/harvester/pull/1447

**Comment by andyrue** [comment]
I seem to be experiencing this exact thing when trying to configure Logging to use minio as a target. `rancher-logging-root-fluentd-0` is crashing because 

```
error="#<Seahorse::Client::NetworkingError: Failed to open TCP connection to harvester-logs.10.111.104.14:9000 (getaddrinfo: Name does not resolve)>"
```
`harvester-logs.10.111.104.14:9000` is not the correct url.
I have endpoint set to `http://10.111.104.14:9000/` and bucket set to `harvester-logs`. What is the solution for this?

I'm running Harvester 1.2.0

**Comment by xind** [comment]
set `UsePathStyle` to true
