### ISSUE TITLE
[BUG] VM's Edit YAML function work incorrectly

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1564]
### Describe the bug
VM will broke when user do `Edit YAML` inside `Edit Config`, as the attached screen record shown, **Edit YAML** loads different content in **Edit Config** view.

### To Reproduce
1. Install harvester with any nodes
2. Create image for VM creation
3. Create VM with any resource
4. click _Edit YAML_ in list view, edit `spec.

## Environment:
 - Harvester ISO version: ** **
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3nodes**

### Additional context
https://user-images.githubusercontent.com/5169694/142601804-9c899416-c73a-4a23-9164-c62127d17f03.mp4

**Comment by WuJun2016** [comment]
https://172.16.4.9/v1/schemas/kubevirt.io.v1.virtualmachine.spec.template.spec.domain.resources

![image](https://user-images.githubusercontent.com/24985926/143205115-703abf05-2a4d-4bcc-bf76-d153ff00ef61.png)

The type value here should not be "map[]", you should be able to get the correct format of this property by clicking on the type

**Comment by weihanglo** [comment]
Haven't found why the code is generated differently. The two of the code snippets look almost identical. Only for `io.k8s.api.core.v1.ResourceRequirements` it got `map[string]` type for fields `limits` and `requests`.

- https://your-harvester-ip/v1/schemas/io.k8s.api.core.v1.ResourceRequirements
- https://your-harvester-ip/v1/schemas/kubevirt.io.v1.virtualmachine.spec.template.spec.domain.resources

![image](https://user-images.githubusercontent.com/14314532/162912198-1be6c192-5f40-4f4b-86c4-eea0882c2dd5.png)

https://github.com/harvester/harvester/blob/c5bfa702c4868124b5cc8645f46ab31940bdfe62/vendor/k8s.io/api/core/v1/types.go#L2181-L2193

https://github.com/harvester/harvester/blob/c5bfa702c4868124b5cc8645f46ab31940bdfe62/vendor/kubevirt.io/api/core/v1/schema.go#L270-L283

**Comment by weihanglo** [comment]
I've tested it several times. None of cases below can reproduce the original issue:

- Edit spec via the path "Edit Config > Edit as YAML"
- Edit spec via the path "Edit YAML"

The time this issue reported was pre1.0 era (perhaps v0.3), and lots of upstream dependencies has been upgraded since then, so I guess the issue was accidentally fixed.


BTW, the type mismatch issue which @WuJun2016 mentioned  is still there, but it doesn't cause editing corruption.

**Comment by lanfon72** [comment]
Closed as the bug can not be reproduced in `v1.0.1`.
Also tested on `v1.0.0`, `v0.3.0`(lacking **Edit YAML** button inside **Edit Config**)
