### ISSUE TITLE
[BUG] virtualization management page crash

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1571]
**Describe the bug**

In a multi-cluster environment：

- Click on the virtualization management menu.

- The page reports an error

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/1a46a3fb-b51c-4ced-b970-5b7541dca486)

**To Reproduce**

**Expected behavior**

Show harvester clusters that have been imported

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-47ea94ee-head` with rancher `v2.6.3-rc2`. Close this issue.

### Result
Click `Virtualization Management` page in the beginning or after harvester imported can't show any page error 

![image](https://user-images.githubusercontent.com/29251855/143833328-8e9e3009-22b2-4fed-a6e3-6116ca748a7b.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machines
* Harvester version: master-47ea94ee-head
* Rancher version: v2.6.3-rc2

### Verify Steps
1. Login harvester dashboard
2. Open Virtualization page
3. Import existing harvester
4. Navigate to other page 
5. Access Virtualization page
