### ISSUE TITLE
[BUG] Multi-cluster projectNamespace details page error

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1574]
**Describe the bug**

1. Page Crash
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/99928fef-8a36-4475-89c5-304d9dec96ed)

2.  Empty project without namespace shows error

https://user-images.githubusercontent.com/24985926/142840075-7a5a4a3d-038a-40c0-99b5-40903bbc39cc.mov

**To Reproduce**

- Case 1:  
  - Multi-cluster environments
  - click projects/Namespaces menu
  - Click on any namespace to go to the details page （Page Crash）

- Case 2:
  - Multi-cluster environments
  - click projects/Namespaces menu
  - Create a new project
  - The project created before should be displayed in the list.   （Expected behavior）

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-47ea94ee-head` with rancher `v2.6.3-rc2`. Close this issue.

### Result
1. Access harvester from rancher virtualization management page
   Click any namespace in the Projects/Namespace can display details correctly with no page error

Default namespace
![image](https://user-images.githubusercontent.com/29251855/143835124-6f81b902-e0b1-4cbd-8e1f-e818ee033fdb.png)

Customized namespace
![image](https://user-images.githubusercontent.com/29251855/143835686-ac125432-568b-426b-8612-c861585eaab2.png)


![image](https://user-images.githubusercontent.com/29251855/143835629-b4913167-b447-4a20-af4a-8ac5452eee62.png)

2. Newly created namespace will display under project list 
![image](https://user-images.githubusercontent.com/29251855/143833328-8e9e3009-22b2-4fed-a6e3-6116ca748a7b.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machines
* Harvester version: master-47ea94ee-head
* Rancher version: v2.6.3-rc2

### Verify Steps
1. Import harvester from rancher dashboard
2. Access harvester from virtualization management page
3. Create several new projects
4. Create several new namespaces under each new projects
5. Access all default and self created namespace
6. Check can display namespace details 
7. Check all new namespaces can display correctly under each projects
