### ISSUE TITLE
[FEATURE] Option to disable load balancer feature in cloud provider

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1577]
**Use case:** 

We want to use a custom load balancer integration and need to prevent the harvester cloud provider to take ownership of service type load balancer resources (we still want to use use harvester storage class).

**Expected Behaviour:**

There is  a parameter to disable the load balancer feature of the harvester cloud provider during cluster provisioning

**Comment by yasker** [comment]
@janeczku We need some discussion around this:
1. Can you share more details regarding the custom load balancer implementation? And is it general enough to contribute to the upstream Harvester?
2. What's the problem with the existing load balancer mechanism?

**Comment by yasker** [comment]
Set milestone to v1.1.0 to start the discussion.

**Comment by yasker** [comment]
Talked with @janeczku on this.

@guangbochen @yaocw2020 Is it possible for us to add this disable option to Harvester v1.0? Not sure how much effort it will take.

**Comment by guangbochen** [comment]
You should already be able to do so via config the cloud provider option to `None`.
![image](https://user-images.githubusercontent.com/4569037/142971322-f34a9c6d-095e-4dcc-9981-103bee4453ff.png)

**Comment by guangbochen** [comment]
@janeczku can u please confirm this issue is fine to be resolved, thanks.
- users can disable the Harvester cloud provider via setting the option to `None`
- users can install the `Guest-CSI` driver by adding the harvester chart repo https://github.com/harvester/charts and installing the CSI driver chart manually.

**Comment by noahgildersleeve** [comment]
Tested in master-655c215a-head. You can't change the cloud provider in the RKE2 node driver page to `None`. 
![node-driver-rke2-cloud-driver](https://user-images.githubusercontent.com/83787952/145735758-e8eb9eca-fb3c-462c-8069-cafbd8538a64.gif)

**Comment by noahgildersleeve** [comment]
Tested in  master-5e8d9764-head.
1. Provisioned RKE2 1.21.7 with no cloud provider on 4 node Harvester setup. Finished provisioning and showed management console.
![image](https://user-images.githubusercontent.com/83787952/146481881-3a48ff52-cfe8-469c-a2fa-b68737077773.png)

**Comment by oivindoh** [comment]
> I can't speak for @janeczku, but for us the use case for another load balancer integration (metallb) in guest clusters is getting client IP propagated to services in the guest cluster, which does not seem to be possible with the current kube-vip based implementation.

**Comment by TrooperT** [comment]
While I will only speak for myself and my use cases which are similar in nature to @oivindoh 's use case e.g. 

- RKE2 Cluster created via rancher 
- Harvester Node Driver
- Harvester Cloud Provider
- Load Balancer Services via MetalLB in the guest cluster 
- MetalLB providing ExternalIPs from pre-allocated subnets announced toward the Nodes' Default Gateway via BGP for reachability

I have not found any manner of doing this via the Graphical UI, I have found that post-Cluster creation if the **Deployment** created by the Helm Chart "harvester-cloud-provider" is modified with an extra arg "--controllers=cloud-node,cloud-node-lifecycle,route" that it will have the effect of disabling  the CCM from attempting to allocate LBs from the host Harvester cluster.
Found via help documentation for harvester-cloud-provider:
```
--controllers strings                                                                                                                                                                 
               A list of controllers to enable. '*' enables all on-by-default controllers, 'foo' enables the controller named 'foo', '-foo' disables the controller named 'foo'.
               All controllers: cloud-node, cloud-node-lifecycle, route, service
               Disabled-by-default controllers:  (default [*])
```
I've not examined whether this would be scriptable via an additional manifest, I'm sure it is, just haven't had the time.

Hope this helps someone

**Comment by brotherdust** [comment]
@TrooperT it helped me! Thanks much!

**Comment by brotherdust** [comment]
> @janeczku can u please confirm this issue is fine to be resolved, thanks.
> 
> * users can disable the Harvester cloud provider via setting the option to `None`
> * users can install the `Guest-CSI` driver by adding the harvester chart repo https://github.com/harvester/charts and installing the CSI driver chart manually.

Sorry for commenting on a closed issue, but I need some clarification, please! =) There doesn't seem to be a documented method for the manual installation. Specifically, does one need to generate a cloudConfig and place it in a directory somewhere on a Harvester node? If so, how does one generate cloudConfig and where must it be placed?
Thanks in advance!

**Comment by ryzenpay** [comment]
the flag overwrite has stopped working in newest version 0.2.5 with error in the lines of:
"controllers cloud-node,cloud-node-lifecycle,route dont exist"
