### ISSUE TITLE
[ENHANCEMENT] api formatter shoud return panic message on error exceptions

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#158]
refer to: https://github.com/gorilla/handlers/blob/master/recovery.go

**Comment by yasker** [comment]
@guangbochen Is this issue still valid?

**Comment by guangbochen** [comment]
Yep, but this is a nice-to-have enhancement related to the steve framework; currently, our API server didn't contain any error exceptions, but if any panic occurs it will still fail silently.

**Comment by irishgordo** [comment]
@tserong thanks for this enhancement :smile: :+1:  - this all looks good - I'll go ahead and close this out :smile: 

### Environment
* Harvester
  * Version: Harvester-v1.4-20240923 /  Version: v1.4-97e60e1-head 
  * Profile: QEMU/KVM
  * ui-source: Auto


### Verification
### 1 Node Cluster
1. :green_circle: API Formatter Doesn't Fail Silently & Returns Info + Non-existent Routes Act Appropriately 
   
   <details>
   <summary> <i>Given</i> 500 Raises on $harvester_vip/v1/harvester/dont-panic & Non-Existent Route Returns 404
   </summary>

    ![Screenshot from 2024-09-30 16-07-49](https://github.com/user-attachments/assets/ea4c155f-255b-4332-83a2-205968f96f46)
    ![Screenshot from 2024-09-30 16-06-32](https://github.com/user-attachments/assets/ffc03cd7-3ba7-47d2-9564-5b3d8bd73e7f)


     </details>
