### ISSUE TITLE
[FEATURE] Load balancer service improvements

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1580]
-WIP-

Load balancer service for guest clusters should be improved to meet the following requirements:

1) All VIPs created for downstream clusters should not be attached to a single common Harvester node.
Instead, Individual VIPs should be able to attach to any available Harvester node in order to increase resiliency and not have the network resources of a single Harvester node become a bottleneck for the overall ingress traffic of all guest clusters. 
   Note: Layer-2 mode is acceptable but not all Layer-2 VIPs should be attached to the same Harvester node as it is currently the case.

2) Admin must be able to assign multiple VIP addresses (/32 CIDR) per Harvester tenant (= namespace). Currently, only a single CIDR range can be configured per Harvester namespace (limitation of kube-vip configmap)

**Comment by yaocw2020** [comment]
The kube-vip supports BGP mode but we have not brought it into the Harvester.

**Comment by janeczku** [comment]
Layer-2 mode is acceptable as long as not all Layer-2 VIPs are configured on a single Harvester node. @yaocw2020

**Comment by belgaied2** [comment]
Though this is necessarily highest priority, I would expect this to be problematic in bigger deployments where many Load Balancer services are created in downstream clusters deployed on Harvester.

**Comment by n313893254** [comment]
@yaocw2020 Can the issue be moved to ready for testing?

**Comment by yaocw2020** [comment]
@janeczku About the failover mechanism, we integrate the kube-vip with Harvester cloud provider in Harvester 1.2.0.  Exactly, it means every guest cluster with Harvester cloud provider will deploy a kube-vip. I have to admit it's not thorough. 
What do you think? cc @guangbochen

**Comment by TachunLin** [comment]
For the second part feature of being able to assign multiple VIP addresses (/32 CIDR) per Harvester tenant (= namespace). We can use the following test plan for validation. 

#### Test Plan

1. Import Harvester to Rancher 
2. Access Harvester from Rancher
3. Create a namespace test1 under default project
4. Provision a RKE2 cluster and select test1 as the namespace 
5. Access Harvester from Rancher
6. Create an IP pool, select Project default, namespace: test1 and select the RKE2 cluster name 
7. Access RKE2 guest cluster on Rancher 
8. Create a nginx deployment on the customized namespace test1 
9. Create a load balancer service, 
10. On the ipam mode, select the Pool mode  
11. Use other namespace like `default` and `harvester-public` and follow above steps

**Comment by TachunLin** [comment]
During the verification of the IP pool on customized namespace 
After the load balancer created, it stuck in `Pending` state

![image](https://github.com/harvester/harvester/assets/29251855/96ab0835-2c21-46e0-b877-f240148441e8)

Check the Harvester load balancer logs, found the following error 
  ```
  allocate ip for lb test1/kubernetes-test1-lb-pool-test1-89014bb5 failed, error: fail to select the pool for lb test1/kubernetes-test1-lb-pool-test1-89014bb5, error: no matching IP pool with requirement &{Network: Project:c-m-rdn8fr4c/p-t5crm Namespace:test1 Cluster:kubernetes}
  ``` 

#### Test Information
* Test Environment: 3 nodes Harvester on bare machines
* Harvester version: `v1.2.0-rc3`
* Rancher version: `v2.7.5-rc6` 

#### Follow up 
A new issue created to track this behavior in #4232. Move to implement for further discussion.

**Comment by yaocw2020** [comment]
The issue is not clear enough. We split into two issues https://github.com/harvester/harvester/issues/4237 and https://github.com/harvester/harvester/issues/4232 after Harvester v1.2.0-rc2.
