### ISSUE TITLE
[BUG] No Management NIC selectable

### ISSUE THREAD

**Issue by ensec-apollods** [harvester/harvester#1581]
**Describe the bug**
It is not possible to select a Management NIC interface, there's no selection available, the field is just empty.

**To Reproduce**
Boot from ISO v0.3.0 on a Supermicro X8DTT Motherboard.

**Expected behavior**
Management NIC interfaces should be visible

**Environment:**
 - Harvester ISO version: v0.3.0 
 - Underlying Infrastructure Baremetal with Supermicro X8DTT (2 Blade Server)

**Additional context**
Please see screenshot.
<img width="927" alt="harvester_no_nic" src="https://user-images.githubusercontent.com/84436094/143138241-7b08f146-0645-4407-81c9-77f1811863d2.png">

**Comment by guangbochen** [comment]
use `tab` to open and `space` to select.

**Comment by guangbochen** [comment]
Close due to inactivity, thanks.
