### ISSUE TITLE
[BUG] Failed to start RKE2 server

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1582]
### Describe the bug
VM install with iPXE success, but starting rke2 fail as:
![image](https://user-images.githubusercontent.com/5169694/143169930-73a2ce25-500c-4342-bb6d-4410b870ebd8.png)

### To Reproduce
1. use ipxe-example to install harvester
2. use virt-manager to monitor session

### Expected behavior
rke2 start should success.

## Environment:
 - Harvester ISO version: **master-cdb4841-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

### Additional context
- [rk2e-server.log](https://github.com/harvester/harvester/files/7592526/rk2e-server.log)
- last tested success version: **master-f5bde7fa-head**

**Comment by guangbochen** [comment]
seems the default route is not found, did u rebase to the latest ipxe changes with https://github.com/harvester/ipxe-examples/commit/f99de09c33f1d82ddf53ab4ce98a213fdbf48d21

**Comment by lanfon72** [comment]
@guangbochen :thinking: i didn't pull the repo recently, do we change the default route policy in last few builds?
I will try the last commit (of ipxe-examples) again, if it is resolved, I will close this issue. :bow:

**Comment by lanfon72** [comment]
tested on Provo's machines and updated ipxe-examples, cant reproduce it...
this should be false alarm. :bowing_man:
