### ISSUE TITLE
[BUG] Support Bundle failed to create due to timeout

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1585]
**Describe the bug**
Support Bundle failed to create due to timeout，but the file has generated successfully on the support bundle's pod after a period of time.

**To Reproduce**
1. Create a support bundle via the support page
2. Wait for a period of time and get the wait timeout error 
```
# SupportBundle CR
status": {
"conditions": [
{
"error": true,
"lastUpdateTime": "2021-11-25T04:45:38Z",
"message": "fail to generate supportbundle: timeout",
"status": "False",
"transitioning": false,
"type": "Initialized"
}
],
"progress": 40,
"state": "error"
}
```

**Expected behavior**
- Increase the default timeout to 10 minutes as it will take a longer time for people having a larger cluster or cluster containing a long historical data
- Make the timeout configurable via setting or should only return error when the pod contains fatal.

**Support bundle**
```
 ks logs -f supportbundle-manager-bundle-wkoos-7dc8c58455-2qd5g
+ exec tini -- /usr/bin/support-bundle-kit manager
time="2021-11-25T04:37:36Z" level=info msg="running phase init"
time="2021-11-25T04:37:36Z" level=debug msg="Create a local state store. (harvester-system/bundle-wkoos)"
time="2021-11-25T04:37:36Z" level=debug msg="Get supportbundle harvester-system/bundle-wkoos state generating"
time="2021-11-25T04:37:36Z" level=info msg="succeed to run phase init. Progress (20)."
time="2021-11-25T04:37:36Z" level=info msg="running phase cluster bundle"
time="2021-11-25T04:37:36Z" level=debug msg="generating cluster bundle..."
time="2021-11-25T04:37:36Z" level=debug msg="Get supportbundle harvester-system/bundle-wkoos"
W1125 04:37:36.081898       7 warnings.go:70] v1 ComponentStatus is deprecated in v1.19+
W1125 04:37:36.103189       7 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W1125 04:37:37.503395       7 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1125 04:37:37.974792       7 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1125 04:37:38.559970       7 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1125 04:37:39.106501       7 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
W1125 04:37:39.680163       7 warnings.go:70] extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress
time="2021-11-25T04:38:04Z" level=info msg="succeed to run phase cluster bundle. Progress (40)."
time="2021-11-25T04:38:04Z" level=info msg="running phase node bundle"
time="2021-11-25T04:38:04Z" level=debug msg="expected bundles from nodes: map[harv-bm2: harv-bm3: harv-bm5:]"
time="2021-11-25T04:38:04Z" level=debug msg="creating daemonset supportbundle-agent-bundle-wkoos with image rancher/support-bundle-kit:v0.0.3"
time="2021-11-25T04:42:12Z" level=debug msg="handle create node bundle for harv-bm2"
time="2021-11-25T04:42:12Z" level=debug msg="complete node harv-bm2"
time="2021-11-25T04:42:15Z" level=debug msg="handle create node bundle for harv-bm3"
time="2021-11-25T04:42:15Z" level=debug msg="complete node harv-bm3"
time="2021-11-25T04:48:21Z" level=debug msg="handle create node bundle for harv-bm5"
time="2021-11-25T04:48:21Z" level=debug msg="complete node harv-bm5"
time="2021-11-25T04:48:21Z" level=debug msg="all nodes are completed."
time="2021-11-25T04:48:21Z" level=info msg="all node bundles are received."
time="2021-11-25T04:48:21Z" level=info msg="succeed to run phase node bundle. Progress (60)."
time="2021-11-25T04:48:21Z" level=info msg="running phase package"
time="2021-11-25T04:48:26Z" level=info msg="succeed to run phase package. Progress (80)."
time="2021-11-25T04:48:26Z" level=info msg="running phase done"
time="2021-11-25T04:48:26Z" level=info msg="support bundle /tmp/support-bundle-kit/supportbundle_a2c569fd-71d7-47d4-b073-3accc7193fe2_2021-11-25T04-37-36Z.zip ready to download"
time="2021-11-25T04:48:26Z" level=info msg="succeed to run phase done. Progress (100)."
```

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
I would suggest we revert the change: https://github.com/rancher/support-bundle-kit/pull/16#discussion_r702025213 to collect node bundles even some nodes don't push bundle ack in time.

**Comment by guangbochen** [comment]
> I would suggest we revert the change: [rancher/support-bundle-kit#16 (comment)](https://github.com/rancher/support-bundle-kit/pull/16#discussion_r702025213) to collect node bundles even some nodes don't push bundle ack in time.

as an enhancement, I think it makes sense, we can resolve it after the timeout bug.

**Comment by WuJun2016** [comment]
The latest UI has added `support-bundle-timeout` setting. You can take the latest UI to test whether the function is available,  thanks.   @FrankYang0529

**Comment by lanfon72** [comment]
Verfied the bug has been fixed with new feature `support-bundle-timeout` introduced in settings.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: master-655c251a-head
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Navigate to Advanced Settings, modify `support-bundle-timeout` to `2`
3. Navigate to Support, Click **Generate Support Bundle**, and force shut down one of the node in the mean time.
4. **2** mins later, the function will failed with an Error message pop up as the snapshot
![image](https://user-images.githubusercontent.com/5169694/145191630-27ef156c-d8dd-4480-811c-c1ce39142491.png)

**Comment by guangbochen** [comment]
can we confirm if the default timeout is set to `0` the SB will be downloaded even if the node is force shutdown, thanks?

**Comment by lanfon72** [comment]
tested `support bundle` will be generated and downloaded when timeout set to `0`.
(either the node is off before generated or during the generating)

But as the verify steps, generate function will stop if hit the timeout.

**Comment by guangbochen** [comment]
I have logged an issue and we can track it in the https://github.com/harvester/harvester/issues/1646, thanks.
