### ISSUE TITLE
would this work on a rancher cluster?

### ISSUE THREAD

**Issue by ghost** [harvester/harvester#159]
if this was running on a rancher cluster, could you then dedicate the whole cluster to one vm, effectively creating a single system image cluster where regular programs treat it as one big system?

**Comment by mkoperator** [comment]
Your title and message ask two different questions. This would work on a Rancher cluster, though it is recommended to host workloads on downstream clusters. However, the answer is no to your second question. The VM would be limited to the spare capacity of a single node and would not span the entire cluster.
