### ISSUE TITLE
[BUG] Harvester installer can't resolve hostnames

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1590]
**Describe the bug**

When installing Harvester through ipxe with a static network config, the nameservers are missing from `/etc/resolv.conf`, which causes the installer not being able to download the Harvester config URL or ISO.

**To Reproduce**
This does work in a different environment but not in the current one. The hardware is slightly different, in that it contains less memory and networking interfaces.

- ipxe boot with the following ipxe config
```
#!ipxe

set net0/ip 10.2.53.10 && echo Setting ip on net0
set net0/netmask 255.255.255.0 && echo Setting netmask on net0
set net0/gateway 10.2.53.1 && echo Setting gateway on net0
set dns 8.50.250.2 && echo Setting dns server
ifopen net0 && echo Enable network device net0
iflinkwait --timeout 20000 net0 && echo Detected link on net0
sleep 10
chain http://harvester-helper-node.domain/clustera/ipxe-create-node1?mac=${net0/hwaddr}&asset=${asset}&uuid=${uuid}&serial=${serial}
```
- loading chain
```
#!ipxe

kernel http://harvester-helper-node.domain/clustera/harvester-v0.3.0-vmlinuz-amd64 bond=harvester-mgmt:eno1,ens1f1:mode=802.3ad,lacp_rate=slow,updelay=1000,miimon=100,xmit_hash_policy=layer2+3 nameserver=8.50.250.2 nameserver=8.50.252.2 root=live:http://harvester-helper-node.domain/clustera/harvester-v0.3.0-rootfs-amd64.squashfs harvester.install.config_url=https://harvester-helper-node.domain/clustera/config-create-node1.yaml ip=10.2.53.10::10.2.53.1:255.255.255.0:node1:harvester-mgmt:off:8.50.250.2:8.50.252.2 rd.debug rd.cos.disable rd.noverifyssl net.ifnames=1 console=tty1 harvester.install.automatic=true ipv6.disable=1 networkstatic=yes rd.peerdns=0 rd.live.debug=1
initrd http://harvester-helper-node.domain/clustera/harvester-v0.3.0-initrd-amd64
boot
```
- Wait for the Harvester installer to start. Then it will show the following message:
```
time="2021-11-27T11:14:08Z" level=error msg="Get \"https://harvester-helper-node.domain/clustera/config-create-node1.yaml\": dial tcp: lookup harvester-helper-node.domain on [::1]:53: dial udp [::1]:53: socket: address family not supported by protocol"
```

**Expected behavior**
Make sure that resolving works in the harvester installer and that the statically configured nameservers are included in `/etc/resolve.conf`.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
The `resolv.conf` doesn't contain any entries:
```
### /etc/resolv.conf is a symlink to /var/run/netconfig/resolv.conf
### autogenerated by netconfig!
#
# Before you change this file manually, consider to define the
# static DNS configuration using the following variables in the
# /etc/sysconfig/network/config file:
#     NETCONFIG_DNS_STATIC_SEARCHLIST
#     NETCONFIG_DNS_STATIC_SERVERS
#     NETCONFIG_DNS_FORWARDER
# or disable DNS configuration updates via netconfig by setting:
#     NETCONFIG_DNS_POLICY=''
#
# See also the netconfig(8) manual page and other documentation.
#
### Call "netconfig update -f" to force adjusting of /etc/resolv.conf.
```
Dracut sees the nameservers and it seems to configure those in the interface-specific files, but it seems like they don't end up in `/etc/resolv.conf`. Or they might be overwritten by wicked.

**Comment by alexdepalex** [comment]
[journalctl.txt](https://github.com/harvester/harvester/files/7611697/journalctl.txt)

**Comment by janeczku** [comment]
Could it be possible that DHCP is enabled on the other interfaces and so dhclient overwrites the /etc/resolv.conf? 
See the behavior described here: https://github.com/coreos/fedora-coreos-tracker/issues/393#issuecomment-587119013

If this is the case one could possibly adding “ip=none” to disable DHCP in dracut.

**Comment by alexdepalex** [comment]
That was my first idea as well, but it's disabled on that subnet. The interface did get an IPv6 address through SLAAC, but I've disabled ipv6 by setting `ipv6.disable=1`. Unless loading of the live root enables it in some way.

**Comment by bk201** [comment]
We only carry non-bonding interface config (DHCP only) from initrd stage to OS wicked: https://github.com/harvester/harvester-installer/blob/cdb484109cff55ac7e4d0f6a03e3a08ffdb2ea56/package/harvester-os/files/system/oem/90_network.yaml#L13-L19
Static IP + bonding interfaces config was not tested before.

**Comment by alexdepalex** [comment]
The bonding interface is just a by-product of me trying to use different network configs to remediate the issue. It also manifest when using a single interface.

Besides the dns issue, the bonding interface works perfectly when using an ip instead of a hostnames.

**Comment by alexdepalex** [comment]
> Static IP + bonding interfaces config was not tested before.

So setting a static ip through kernel parameters isn't supported? @janeczku

**Comment by janeczku** [comment]
**Summary of issue:**

- Network configuration during the installation stage (harvester installer) is hardcoded to use DHCP mode ([see](https://github.com/harvester/harvester/issues/1590#:~:text=https%3A//github.com/harvester/harvester-installer/blob/cdb484109cff55ac7e4d0f6a03e3a08ffdb2ea56/package/harvester-os/files/system/oem/90_network.yaml%23L13-L19))
- Static Network configuration provided as kernel parameters (including nameservers) is not applied
- If there is no DHCP server, the `/etc/resolv.conf` will remain empty
- This blocks the installation of Harvester in network environments without DHCP service.

**Requirement:**

Initial network configuration must be configurable through kernel cmdline, and that information either passed throught into the live root, or the wicked version in the live root upgraded to a version that supports parsing network config from cmdline ([see here](https://github.com/openSUSE/wicked/blob/master/client/dracut/cmdline.c)).

**Comment by johnliu55tw** [comment]
I think we could leverage Dracut module [`ifcfg`](https://github.com/openSUSE/dracut/tree/SUSE/055/modules.d/45ifcfg) to create the `ifcfg-<iface>` and `resolv.conf` files for our use after switching root. But there are some catches:
- Based on my testing, the module can correctly create ifcfg files for static IP configuration, but **not for DHCP configuration**. It always generates ifcfg file with `BOOTPROTO=none` for DHCP configuration. I submitted a [bug report](https://bugzilla.opensuse.org/show_bug.cgi?id=1193518) for this issue.
- Even if I provided multiple `ip=...` kernel cmdline args to configure multiple interfaces, only one of the interfaces would have corresponding `ifcfg-<iface>` file generated. I think this is more related to the Dracut `network` module, not specifically related to `ifcfg` module.

**Comment by johnliu55tw** [comment]
Please check https://github.com/harvester/harvester-installer/pull/187 for testing this.

**Comment by noahgildersleeve** [comment]
Tested with nightly build on vagrant using ipxe environment according to https://github.com/harvester/harvester-installer/pull/187. It did not assign the new nameserver to /etc/resolv.conf. It just has the preloaded ones. I modified the ipxe files as well and tried recreating the VMS.
![Screenshot from 2021-12-15 17-47-48](https://user-images.githubusercontent.com/83787952/146293136-dd50bc53-fc3c-41d4-ba7d-cdf6aa5c4c7c.png)
![Screenshot from 2021-12-15 17-35-30](https://user-images.githubusercontent.com/83787952/146293137-2d00899f-19b0-476f-ab81-4d2ba5048186.png)

**Comment by noahgildersleeve** [comment]
It turns out I was checking the `/etc/resolv.conf` after reboot and install. I cleared the vagrant setup and redid it to make sure that I got it before the reboot and it did show `nameserver 1.1.1.1` in `/etc/resolv.conf` Closing ticket.
![Screenshot from 2021-12-15 18-01-25](https://user-images.githubusercontent.com/83787952/146294408-c84072e8-e45b-489b-8a6f-d223a6708cbe.png)
