### ISSUE TITLE
[BUG] PXE installer fails for multiple nodes

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1598]
**Describe the bug**

When you run an install via PXE boot it fails
**To Reproduce**
1. Run the installer from the vagrant environment at https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester
2. Check the output
**Expected behavior**

The install should complete
**Support bundle**

[supportbundle_58e77be5-990a-4856-aafd-fe6845985a5f_2021-11-30T21-10-50Z.zip](https://github.com/harvester/harvester/files/7628881/supportbundle_58e77be5-990a-4856-aafd-fe6845985a5f_2021-11-30T21-10-50Z.zip)

**Environment:**
 - Harvester ISO version: master-f510945f-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant

**Additional context**
This seems to be happening after the install of the first node when adding the second. The install of the first node seems to be completing. Also this is happening when doing deploys via Jenkins. I ran a manual install in a virtualized environment from mounted ISO and was able to set up a working 2 node cluster just fine.

**Comment by gitlawr** [comment]
Addressed in https://github.com/harvester/ipxe-examples/pull/37

**Comment by guangyee** [comment]
Why was port 30443 removed?

**Comment by guangyee** [comment]
We still have other monitoring scripts that are looking for port 30443. Can you please confirm that it is no longer supported and why as this is a backward incompatible change?

**Comment by guangyee** [comment]
https://github.com/harvester/harvester/pull/1584

**Comment by gitlawr** [comment]
We set up the ingress controller and Harvester service can be accessed via the 443 port

**Comment by guangyee** [comment]
Vagrant installation is working now.
