### ISSUE TITLE
websocket continue to push deleted image

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#16]
**Problem:**

When a user deletes an image from the UI the API shows the object is successfully removed, but the WebSocket will continue to push the deleted object to the frontend.

**Expected Solution:**

WebSocket should not continue to pushing deleted objects.

**Comment by gitlawr** [comment]
![image](https://user-images.githubusercontent.com/5697937/89363446-cc8e3680-d702-11ea-8fbc-745990a83835.png)
Frontend sets a stale resource version for the watch.

**Comment by guangbochen** [comment]
close as this is fixed in the UI
