### ISSUE TITLE
A template can be created though no image is selected

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#160]
**Steps to reproduce:**
1. Create a template, fill in template name, CPU, and memory
2. Selecting no image and click the create button

**Result:**
A template can be created though no image is selected
![image](https://user-images.githubusercontent.com/57614736/93744352-441d1400-fc24-11ea-806c-9d67dfa8b5cb.png)

**Comment by guangbochen** [comment]
@DoNotSayYes vm image is not required for VM template.

**Comment by DoNotSayYes** [comment]
On the template create page, when modifying the default disk, what's the purpose of selecting image. @guangbochen 
![image](https://user-images.githubusercontent.com/57614736/93746417-a6c3df00-fc27-11ea-8650-de1d7159f156.png)

**Comment by guangbochen** [comment]
user has to choose the image when creating the VM, we just don't want to force them to select one when creating a VM template.

but we should possibly change the `Select Image` to `Image` and make it optional in the VM template page,
also add `(optional)` next to the choose an image label, thanks cc @WuJun2016

**Comment by DoNotSayYes** [comment]
> user has to choose the image when creating the VM, we just don't want to force them to select one when creating a VM template.
> 
> but we should possibly change the `Select Image` to `Image` and make it optional in the VM template page,
> also add `(optional)` next to the choose an image label, thanks cc @WuJun2016

If users select an image when creating a template, it will be populated in the image dropdown and not editable when editing the default disk, this doesn’t seem like optional at all. @guangbochen

**Comment by DoNotSayYes** [comment]
While editing a disk on the VM template create page, why the image marks as a required field, but actually, it is not. @WuJun2016 
![image](https://user-images.githubusercontent.com/57614736/99922587-4ad31f00-2d6c-11eb-86bf-396371606b8b.png)

**Comment by DoNotSayYes** [comment]
Validated
