### ISSUE TITLE
Adjust the sequence of error messages and unify the units of memory

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#161]
**Steps to reproduce:**
1. On the template page, fill the page with nothing and click the save button
2. Check on the error message

**Result:**
- [ ] 1. An error message says: "Cpu" is required, even though the template is not populated as well
- [ ] 2. Unify the units of Memory. (MiB, GiB, and TiB)
![image](https://user-images.githubusercontent.com/57614736/93744755-f359eb00-fc24-11ea-8202-eae1e24c523a.png)
![image](https://user-images.githubusercontent.com/57614736/93746250-64020700-fc27-11ea-9815-c5537f61d155.png)

**Suggestion:**
It's better to make the error messages in sequence, which can reflect the textbox sequence from the top down on the page

**Comment by guangbochen** [comment]
can we please help to validate those on the latest UI, thanks

**Comment by DoNotSayYes** [comment]
UI design changed
