### ISSUE TITLE
[BUG]  InvalidImageName for network helper image

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1611]
**Describe the bug**

```
Events:
  Type     Reason          Age                     From               Message
  ----     ------          ----                    ----               -------
  Normal   Scheduled       6m24s                   default-scheduler  Successfully assigned harvester-system/default-vlan1238-4h24n to harvester-lk7nr
  Normal   AddedInterface  6m24s                   multus             Add eth0 [10.52.3.34/32]
  Normal   AddedInterface  6m24s                   multus             Add net1 [] from default/vlan1238
  Warning  Failed          4m23s (x12 over 6m24s)  kubelet            Error: InvalidImageName
  Warning  InspectFailed   80s (x26 over 6m24s)    kubelet            Failed to apply default image tag "\"rancher/harvester-network-helper:v0.2.5\"": couldn't parse image reference "\"rancher/harvester-network-helper:v0.2.5\"": invalid reference format
```

**To Reproduce**
1. Enable VLAN network
2. Create a VLAN network with route auto mode

**Expected behavior**

The pod for getting the route information from the DHCP server should be completed successfully.

**Environment:**
 - Harvester ISO version: 0.1.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal 

**Additional context**

**Comment by noahgildersleeve** [comment]
How do you specify 

> 2. Create a VLAN network with route auto mode
Would that just be any VLAN network that is pulling via DHCP?

**Comment by noahgildersleeve** [comment]
Ah. I see now that it was on the most recent nightly build, not on the RC1. Tested in master-655c251a-head. Added in external-vlan. Job completed without error in embedded Rancher
![Screenshot from 2021-12-07 15-15-13](https://user-images.githubusercontent.com/83787952/145120633-3be53e95-1f8f-403a-870f-9c9d856c55e0.png)
.

**Comment by Aixleft723** [comment]
@yaocw2020  by the way, the question had beed solved?

**Comment by Aixleft723** [comment]
@noahgildersleeve  hello, i have meet this quesion again, and i dot not know how to solve it, can you help me?

**Comment by noahgildersleeve** [comment]
@sunkai-XDD Try with the final `v1.0.0` build at https://github.com/harvester/harvester/releases. Let me know if you're still having the issue. It should be resolved, but there isn't an upgrade path from any of the release candidates.So if you're running RC1 or RC2 you're probably going to have to reinstall.
