### ISSUE TITLE
[BUG] Node's resource information mismatch to details view

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1612]
### Describe the bug
overall
![image](https://user-images.githubusercontent.com/5169694/144383147-226e5a2f-60ab-4aaf-8bc9-0d861a96caa6.png)
node-0 details
![image](https://user-images.githubusercontent.com/5169694/144383182-775ed1b4-8f99-4247-85ce-49a157a8a50c.png)
node-1 details
![image](https://user-images.githubusercontent.com/5169694/144383228-4578e509-00ee-4087-b181-dd150e6bb729.png)
node-2 details
![image](https://user-images.githubusercontent.com/5169694/144383264-01bbac3c-bbee-4607-8405-b257330cee2c.png)

login to console, the resource usage more close to Monitor data.

### To Reproduce
1. Install Harvester with nodes
2. compare monitor data between Hosts and details of host (click the host name)

### Expected behavior
monitor data should display consistently.

## Environment:
 - Harvester ISO version: **v1.0.0-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3nodes**

### Additional context
Hosts test case No.1

**Comment by lanfon72** [comment]
I remembered there were an issue about this (but I can't find it), and it had fixed in few weeks ago?

**Comment by n313893254** [comment]
**Test Plan**
Check list/detail pages resource information

**Comment by lanfon72** [comment]
verified this issue has been fixed.

Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **master-3b5fe2e0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with nodes
2. compare monitor data between Hosts and details of host (click the host name)
