### ISSUE TITLE
[FEATURE] Ability to add non VLAN tagged networks

### ISSUE THREAD

**Issue by David-VTUK** [harvester/harvester#1618]
**Is your feature request related to a problem? Please describe.**
Currently, when specifying a network in Harvester, a VLAN ID must be provided:
![image](https://user-images.githubusercontent.com/5892615/144427906-26de30c8-6a02-4a9a-9206-2dc1a23ce18f.png)

This is not always applicable to all environments.

**Describe the solution you'd like**
Like with other Hypervisors, (ESXi, Hyper-V, etc) specifying a VLAN ID is _optional_. Some network devices may not expect to receive explicitly tagged VLAN ID's that match the native/default VLAN on the switch the uplink belongs to.

Having this  as an optional configuration may also help those migrate from the aforementioned Hypervisors due to familiarity with options.

**Describe alternatives you've considered**
N/A

**Additional context**
For reference, vSphere port group VLAN options:
![image](https://user-images.githubusercontent.com/5892615/144428654-b88a79fe-e9c0-4a71-91d5-9e72101d4b3d.png)

For reference, Hyper-V network adapter options:
![image](https://user-images.githubusercontent.com/5892615/144428946-c301f99d-719c-4054-9cdf-8c070961ec6b.png)

**Comment by guangbochen** [comment]
we may leverage the https://www.cni.dev/plugins/v0.7/main/bridge/ CNI as an option through the Multus NAD config, but will need some investigation on it.

**Comment by tjjh89017** [comment]
@David-VTUK 
Did your env only contain 1 subent (L2 broadcast domain)?
If so, you can set VLAN 1 as non-VLAN network by default settings.

**Comment by tjjh89017** [comment]
Please refer to the docs page about [VLAN network best practice](https://docs.harvesterhci.io/v1.0/networking/best-practice-vlan-aware-switch/)
We will close this ticket.
If you still have some question about this, feel free to re-open the ticket
thanks a lot

**Comment by yaocw2020** [comment]
We have to provide a more user-friendly way to support non VLAN tagged network. @tjjh89017 
- Enable the VLAN network, and bind the bridge with a NIC during the installation.
- Create the non VLAN tagged network by default.

**Comment by tjjh89017** [comment]
> We have to do some enhancements to support non VLAN tagged network. @tjjh89017
> 
> * Enable the VLAN network, and bind the bridge with a NIC during the installation.

This is related to https://github.com/harvester/harvester-installer/pull/227
but we need UI, right?
and probably need a `harvester-vlan` bonding to attach.
I will do some research to fit if we need to setup vlan on harvester-mgmt

> * Create the non VLAN tagged network by default.

Note:
setup a bootstrap net-att-def in installer.

**Comment by yaocw2020** [comment]
Test plan:
- Create a network with the type UntaggedNetwork.
- It could be used as VLAN 1.

**Comment by irishgordo** [comment]
@tjjh89017 should we be able to provision a 3 node RKE2 cluster with an untagged network?
(was using Rancher v2.6.9)
Of:
```
Provisioner: RKE2
Machine Provider: Harvester
Kubernetes Version: v1.24.7+rke2r1
Machine Pools: 1
Machines: 3
```

I'm noticing from the provisioning log:
```
(HarvesterMachine)  for machine test-untagged-clstr-pool1-79fb74b95-n7gmp in infrastructure  provider: CreateError: Downloading driver from  https://192.168.1.117/assets/docker-machine-driver-harvester
--
Error
 creating machine: Error in driver during machine creation: Too many 
retries waiting for machine to be Running.  Last error: Maximum number 
of retries (120) exceeded
```
1 node seems to provision but the other 2 seem to be hung.
So I'm not able to fullly provision the entire cluster.
The underlying Harvester VM is 40GB Mem & 20CPU

I did notice however that the VMs seem to look good :smile: 
![Screenshot from 2022-11-15 15-24-38](https://user-images.githubusercontent.com/5370752/202056327-20aba47b-e5e2-4fd4-b908-0f810fb54c8c.png)
![Screenshot from 2022-11-15 16-52-53](https://user-images.githubusercontent.com/5370752/202056584-651d7f42-6a76-4d17-9391-fbfb5f32c943.png)
![Screenshot from 2022-11-15 16-52-34](https://user-images.githubusercontent.com/5370752/202056587-a7093e68-8c63-4f84-b53c-181a37bcd4c4.png)

**Comment by tjjh89017** [comment]
@irishgordo I think this issue should be related to @yaocw2020 's PR
Please check with Canwu
Thanks a lot

**Comment by irishgordo** [comment]
@yaocw2020  - is this what you're seeing with the PR you have open?
Do you happen to have the link?
If it's already being worked on to allow for RKE2 to use untagged networks, I could close this one out.

**Comment by yaocw2020** [comment]
> @yaocw2020 - is this what you're seeing with the PR you have open? Do you happen to have the link? If it's already being worked on to allow for RKE2 to use untagged networks, I could close this one out.

Yes, it's allowed for RKE2.

**Comment by irishgordo** [comment]
@tjjh89017 @yaocw2020 upon snagging the latest master-head -> Harvester Version: master-25799b96-head
RKE2 looks good with an untagged network & rancher v2.6.9, so I'll go ahead and close this out :smile: :+1: 
![Screenshot from 2022-11-17 20-41-54](https://user-images.githubusercontent.com/5370752/202618634-90421806-096b-4135-ba53-c3efebd064a4.png)
![Screenshot from 2022-11-17 20-32-21](https://user-images.githubusercontent.com/5370752/202618636-d7ecf721-1387-4cf2-9f53-960811469709.png)
