### ISSUE TITLE
[BUG] User is unable to create ssh key through the `templates` page

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1619]
**Setup**
- Rancher version: n/a (through harvester UI)
- Browser type & version: chrome

**Describe the bug**

User is unable to create ssh key on the `templates` page

**To Reproduce**

* on a harvester deployment, navigate to `advanced` -> `templates` and click `create`
* under the `ssh key` option, click `create new`
* enter valid credentials and save

**Result**
* 404 error -- the server could not find the requested resource

**Expected Result**

users should be able to create ssh keys from the template page

**Screenshots**

<img width="693" alt="Screen Shot 2021-12-02 at 7 18 20 AM" src="https://user-images.githubusercontent.com/16691014/144456006-c0acc925-250f-46a8-bb66-459993ed3003.png">

**Additional context**
<!--Add any other context about the problem here.—>
this feature works on the `virtual machine` and `ssh keys` pages

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Verified that SSH key could be added via teamplates page
