### ISSUE TITLE
Unable to select network When adding a network interface

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#162]
**Steps to reproduce:**
1. On the template create page, add a new network interface
2. On the popup window, check on the network dropdown

**Result:**
There is nothing that can be selected
![image](https://user-images.githubusercontent.com/57614736/93747274-0b336e00-fc29-11ea-8e3b-dff6742694a4.png)

Moreover, why users are not able to add Mac Address when modifying the default network interface?
![image](https://user-images.githubusercontent.com/57614736/93747964-120eb080-fc2a-11ea-9571-419f969c07be.png)

**Comment by guangbochen** [comment]
1. add a second network requires [Multus](https://github.com/intel/multus-cni) network plugin to be installed in the user's cluster and associated NAD(network attachment definition) is required to be added in each namespace (additionally, multi-network is not in our current scope so the user has to config it manually in their environment).
2. default `pod network` does not support config the mac address.

we can possibly add an additional enchantment to the UI to distinguish the pod and Multus network configuration.

**Comment by guangbochen** [comment]
close as the `multus` is added by default in the harvester ISO installation mode, helm installation is still required to handle the pre-network-configuration manually.
