### ISSUE TITLE
[Rancher Integration] User is unable to use template to create cluster through virtualization management 

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1620]
This bug is filed in rancher/dashboard repo : https://github.com/rancher/dashboard/issues/4689

**Comment by WuJun2016** [comment]
Waiting for upstream pr merge:  https://github.com/rancher/dashboard/pull/4697

**Comment by TachunLin** [comment]
Verified `fixed` on harvester `master-5d6f3db0-head` with rancher `v2.6-head`. Close this issue. 

### Result 
Access harvester from Rancher, on virtual machine page can load default three template to create VM. 

**iso image base template**

![image](https://user-images.githubusercontent.com/29251855/145583546-59cea4ea-4072-437e-9cf7-2449776abb56.png)

**raw image base template**
![image](https://user-images.githubusercontent.com/29251855/145583593-5aa7c897-f3dc-4fa1-9b94-750794a3e88e.png)

**windows iso image base tempalte**
![image](https://user-images.githubusercontent.com/29251855/145583672-72255932-72ee-4a88-b38a-8830789040c8.png)

**Create vm with iso template**
![image](https://user-images.githubusercontent.com/29251855/145586368-5a5b640b-3955-403b-8149-ff8657e2aa26.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-5d6f3db0-head (12/10 based on v1.0.0-rc1)
* Rancher version: v2.6.-head

### Verify Steps

1. Import harvester from rancher through harvester settings
2. Access harvester from rancher virtualization management page
3. Open Virtual Machine page 
4. Click create 
5. Check `Use VM Template`
6. Select one of the template
7. Create VM according to the template
