### ISSUE TITLE
[BUG] sometimes VM gets stuck in `Virt-launcher pod is terminating` when using harvester node driver for deletion

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1621]
**Describe the bug**

When using harvester node driver, sometimes the backend VMs get stuck in `Virt-launcher pod is terminating` in the following cases:
* rancher decides to destroy + re-create a vm 
* user manually removes a cluster through rancher that is unhealthy

**To Reproduce**
1. provision a single node rke1 cluster with some incorrect parameters (i.e. specify `none` in the docker machine version and use an image that doesn't have docker preinstalled)
2. wait for the cluster to fail to provision
  * rancher will delete the old VM and start a new one

1.  provision an rke2 cluster with dedicated nodes per role (3etcd, 2cp, 3worker)
2. wait for VMs to create in the backend
3. delete the cluster before cluster comes to active state

**Expected behavior**

* harvester VMs should all be removed

**Support bundle**

[supportbundle_147f1b83-cdc7-432c-9a01-7b12448d236a_2021-12-02T18-37-29Z.zip](https://github.com/harvester/harvester/files/7644398/supportbundle_147f1b83-cdc7-432c-9a01-7b12448d236a_2021-12-02T18-37-29Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.0-rc1
 - Rancher version: v2.6.3-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dolphins (baremetal)

note: some VMs will still delete, but occasionally there are some that get stuck in this state
<img width="482" alt="Screen Shot 2021-12-02 at 10 29 08 AM" src="https://user-images.githubusercontent.com/16691014/144486550-2562df95-04a4-4b13-bbe4-06880201c071.png">

**Comment by guangbochen** [comment]
can't be reproduced in the current `master-head` version, can we please help to re-validate it, thanks.

**Comment by yasker** [comment]
Move to v1.0.1 due to unable to reproduce.

**Comment by TachunLin** [comment]
Unable to reproduce for the single node `RKE1 scenario` on harvester v1.0.0 with rancher 2.6.3 

### Result
When RKE1 cluster provisioning failed with incorrect `None` docker install URL parameter set.
We can delete RKE1 cluster in rancher. At that moment, the VM still exists on harvester virtual machine dashboard.
When we click the VM, it will start terminating and remove it correctly without stuck.

1. Provision RKE1 cluster with `None` docker install URL
![image](https://user-images.githubusercontent.com/29251855/149897157-89c59649-71af-4eab-a088-1c74608459c5.png)

2. RKE1 provisioning failed with timeout
![image](https://user-images.githubusercontent.com/29251855/149904923-2a355c13-cdbe-4b24-9fb0-0de28c24ec53.png)

3. Waiting for RKE1 cluster provisioning 
![image](https://user-images.githubusercontent.com/29251855/149905053-426ccf03-cf0a-4054-b4a4-b1495ffc0cf1.png)

4. Click the RKE1 cluster VM on harvester, it start terminating  
![image](https://user-images.githubusercontent.com/29251855/149906044-405a3fc1-c0a2-4a1b-96e0-34b513e8cecf.png)

5. Successfully remove RKE1 cluster VM
![image](https://user-images.githubusercontent.com/29251855/149906298-9798c312-5d1e-4637-a0de-2f701a6a8c41.png)

### Test environment
* Harvester version: master-8d0d8aea-head (22/01/17)
* Rancher version: v2.6.3
* Kubernetes version: v1.21.8

**Comment by TachunLin** [comment]
Unable to reproduce for the 3 nodes `RKE2 scenario` on harvester v1.0.0 with rancher 2.6.3 

### Result
When the 3 nodes RKE2 cluster provisioning into active `running` status
We can delete RKE2 cluster in rancher. At that moment, the all vm will be automatically removed from harvester 

1. 3 nodes RKE2 cluster in active state
![image](https://user-images.githubusercontent.com/29251855/150056369-d64576c7-167d-4681-a05d-8a9bb9d491b5.png)
 

![image](https://user-images.githubusercontent.com/29251855/150056337-e8e592ec-e5bb-4e7e-b95e-13bc6a05d9bf.png)

2. Delete RKE2 cluster, all related VM in terminating state
![image](https://user-images.githubusercontent.com/29251855/150072163-fd4749d1-5346-4795-9584-9a5175add862.png)

3. In one minutes all VM have been removed from harvester
![image](https://user-images.githubusercontent.com/29251855/150072928-808348b8-8e0a-4512-b01f-95a7ee3da42d.png)

### Test environment
* Harvester version: master-8d0d8aea-head (22/01/17)
* Rancher version: v2.6.3
* Kubernetes version: v1.21.8

**Comment by TachunLin** [comment]
@slickwarren, according to above test result, this issue can't be reproduced under latest rancher v2.6.3 with harvester v1.0.0 master head. 
I think in previous v2.6.3-rc3, if rancher failed to provision RKE1 or RKE2 VM in harvester, it will continue in a loop to recreate VM. At this moment when we try to delete cluster, it may cause VM deletion stuck in `Virt-launcher pod is terminating`. 
 
After several trials, on latest rancher and harvester release, I haven't encounter the vm deletion stuck with such error message.
Could you help to check whether it still happen in your environment if available. Thanks you.

**Comment by irony** [comment]
I have this exact problem in Harvester 1.2.1 - also on Dell PowerEdge 630 running Harvester. I'm stuck here and nothing works. Please advice?
