### ISSUE TITLE
[BUG] Unable to add additional disks to host config 

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#1623]
**Describe the bug**
We're trying to configure additional NVMe disks in the host config UI. The disks show up in the drop-down menu, but the item is disabled.

**To Reproduce**
I can only reproduce this on specific servers and devices. Devices have been used previously by another product, but disks are zapped using sgdisk.
1. In the Harvester UI go to Hosts
2. Pick a host and select *Edit Config* from the context menu
3. Select *Disks*
4. Select drop-down menu

**Expected behavior**
Disks should be available to be configured.

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0-rc1

**Additional context**

**Comment by alexdepalex** [comment]
sgdisk and object config.

```
node1 :~ # kubectl get blockdevices.harvesterhci.io/c3c3365dfe86e88b61d0fa0a6bb275fa -n longhorn-system -o yaml
apiVersion: harvesterhci.io/v1beta1
kind: BlockDevice
metadata:
  creationTimestamp: "2021-12-02T16:59:55Z"
  finalizers:
  - wrangler.cattle.io/harvester-block-device-handler
  generation: 1849
  labels:
    kubernetes.io/hostname: bmitacnapc1n10
    ndm.harvesterhci.io/device-type: disk
  name: c3c3365dfe86e88b61d0fa0a6bb275fa
  namespace: longhorn-system
  resourceVersion: "630393"
  uid: 4d9ae832-90bc-41a7-a870-60e737950fd1
spec:
  devPath: /dev/nvme5n1
  fileSystem:
    mountPoint: ""
  nodeName: bmitacnapc1n10
status:
  conditions:
  - lastUpdateTime: "2021-12-03T00:07:56Z"
    status: "False"
    type: Mounted
  deviceStatus:
    capacity:
      physicalBlockSizeBytes: 512
      sizeBytes: 1600321314816
    details:
      busPath: unknown
      deviceType: disk
      driveType: SSD
      model: Dell Express Flash PM1725b 1.6TB SFF
      serialNumber: S5CUNEUMB04072
      storageController: NVMe
      vendor: unknown
      wwn: eui.354355554db040720025384500000004
    fileSystem:
      isReadOnly: true
      mountPoint: ""
      type: ""
    partitioned: false
  state: Active
```

```
node1:~ # sgdisk -p /dev/nvme5n1
Creating new GPT entries.
Disk /dev/nvme5n1: 3125627568 sectors, 1.5 TiB
Logical sector size: 512 bytes
Disk identifier (GUID): 0F5B1770-B4CF-4E37-B586-52D5B2E16115
Partition table holds up to 128 entries
First usable sector is 34, last usable sector is 3125627534
Partitions will be aligned on 2048-sector boundaries
Total free space is 3125627501 sectors (1.5 TiB)

Number  Start (sector)    End (sector)  Size       Code  Name
```

**Comment by alexdepalex** [comment]
[supportbundle_cb3b2b70-8c36-47cc-9bc9-b4a233e053cb_2021-12-03T00-11-30Z.zip](https://github.com/harvester/harvester/files/7645863/supportbundle_cb3b2b70-8c36-47cc-9bc9-b4a233e053cb_2021-12-03T00-11-30Z.zip)

**Comment by alexdepalex** [comment]
Please notice that an iDRAC attached cd-drive also shows up in the drop-down menu.

![Annotation 2021-12-03 011959](https://user-images.githubusercontent.com/713019/144523465-0e0a037b-54fc-4771-b624-cc4bd41e21d4.png)

**Comment by weihanglo** [comment]
Hi, @alexdepalex. 
Could you try refreshing the page and see if the disks is enabled again? I observed that websocket update message doesn't work on dropdown menu of additional disks. Need you confirm that you faced the same issue.

**Comment by guangbochen** [comment]
@n313893254 can u please help to double-check on the UI side of the `BlockDevice` CR subscription.

**Comment by n313893254** [comment]
Hi, @weihanglo. Now the UI will get the latest BlockDevice when the user clicks disk dropdown. You can use the latest UI to test it.

**Comment by weihanglo** [comment]
### Test scenario: attach and detach disks 

1. Head to "Hosts" page
1. Click "Edit Config" on a node and switch to "Disks" tab
1. **Validate:** Open dropdown and see no disks
1. Attach a disk on that node
1. **Validate:** Open dropdown and see some disks
1. Detach a disk on that node
1. **Validate:** Open dropdown and see no disks

BTW, I've tested latest UI and confirmed it resolved from my side.

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head. It's worth noting that you have to format the disk before it will show up as available in Harvester. This isn't uncommon with disk utilities though.
## Test steps 
1. Add new disk to VM
2. format disk via command line in host OS
3. Add disk to host
4. Verify that host shows new disk as available storage and Longhorn is showing new schedulable space
![Screenshot from 2021-12-15 17-10-21](https://user-images.githubusercontent.com/83787952/146289651-3c8b8da7-5ba1-4a15-aa4f-32f24af4b8dc.png)
