### ISSUE TITLE
[BUG] Harvester 1.0.0-rc1 fails to install on NVMe M.2 SSD

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1627]
**Describe the bug**
I tried to install Harvester 1.0.0-rc1 on an Intel NUC with a new 1TB Crucial P5 NVMe M.2 SSD but after providing installation options it stopped soon on in the actual install with the message

mkfs.vfat: unable to open /dev/nvme0n11: No such file or directory

I then successfully installed Harvester 0.3.0 on same machine with same SSD so retried the 1.0.0-rc1 install but hit the same problem.

Given reference to /dev/nvme0n11 I can't help wondering whether an additional 1 is being appended to nvme0n1 ... ?

**To Reproduce**
Hard to say but ...
1. Download Harvester 1.0.0-rc1 ISO and copy to Zalman ZM-VE200 USB HDD
2. Verify SHA256 checksum
3. Boot NUC from USB HDD (with Harvester 1.0.0-rc1 ISO as virtual CD-ROM)
4. Provide all installation options
5. Soon after actual starts it stops with message

**Expected behavior**
Harvester 1.0.0-rc1 should install!

**Support bundle**
Unable to create as Harvester not installed.

**Environment:**
 - Harvester ISO version: 1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Intel NUC8i5BEH and new 1TB Crucial P5 NVMe M.2 SSD

**Additional context**
Attached are some photos of relevant screens.

Choose installation target - nvme0n1
![IMG_20211203_141051707](https://user-images.githubusercontent.com/8300801/144627535-74948abe-2649-4816-89ae-582f5214c335.jpg)
Your disk will be formatted and Harvester will be installed
![IMG_20211203_141359331](https://user-images.githubusercontent.com/8300801/144627587-8d7da962-6294-497a-bc23-f3172fc1fc78.jpg)
mkfs.vfat: unable to open /dev/nvme0n11: No such file or directory
![IMG_20211203_113455402](https://user-images.githubusercontent.com/8300801/144627617-3c0bdfe7-2e3e-42d0-b6d7-18f0e3d8d040.jpg)

**Comment by acortina-git** [comment]
I am also experiencing same issue

**Comment by bk201** [comment]
`/dev/nvme0n11` is used rather than `/dev/nvme0np1`. Might need help from cOS team: https://github.com/rancher-sandbox/cOS-toolkit/blob/1128618eb838261702aff788f46e41973ecc99eb/packages/installer/cos.sh#L393-L396

**Comment by johnliu55tw** [comment]
This issue occurs when the system firmware is UEFI and is installing on NVMe drives. Should be fixed in the latest master ISO.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM**
* Harvester Version: **master-5d739671-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Create block image as NVMe disk
    - Run `dd if=/dev/zero of=/var/lib/libvirt/images/nvme145.img bs=1M count=148480`
    - Then Change file owner `chown qemu:qemu /var/lib/libvirt/images/nvme145.img`
2. Create VM via _virt-manager_
    - Select _Manual install_, set **Generic OS**, `Memory:9216`, `CPUs:8`, Uncheck _**enable storage...**_ and check **customize configuration before install**
    - Select _Firmware_ to use **UEFI x86_64** (use `usr/share/qemu/ovmf-x86_64-code.bin` in SUSE Leap 15.3)
    - Select _Chipset_ to use **i440FX**
    - Click **Add Hardware** to add CD-ROM including Harvester iso
    - Update **Boot Options** to **Enable boot menu** and enable the CD-ROM
    - edit XML with update `<domain type="kvm">` to `<domain type="kvm" xmlns:qemu="http://libvirt.org/schemas/domain/qemu/1.0">`
    - append NVMe xml node into **domain**, then Begin Installation
```xml
  <qemu:commandline>
    <qemu:arg value="-drive"/>
    <qemu:arg value="file=/var/lib/libvirt/images/nvme.img,if=none,id=D22,format=raw"/>
    <qemu:arg value="-device"/>
    <qemu:arg value="nvme,drive=D22,serial=1234"/>
  </qemu:commandline>
```
3. Install Harvester by the console UI
4. When rebooting, _**Press ESC**_ to enter UEFI
![image](https://user-images.githubusercontent.com/5169694/146147904-26c50129-020b-4e52-ac1a-95a6814edde7.png)
    - If you miss the screen, VM will entering the Grub with **Harvester Installer** option, you have to reboot again
5. Select **Boot Manager**
![image](https://user-images.githubusercontent.com/5169694/146148422-eab0f144-3b52-455a-b372-e2237001e567.png)
6. Select **UEFI QEMU NVME Ctrl ...**
![image](https://user-images.githubusercontent.com/5169694/146148533-aeb502c3-52f8-4f1b-bc2a-b213ed4fee03.png)
7. VM should boot into Harvester successfully
