### ISSUE TITLE
[BUG] rke1 load balancer is unable to provision `0/8 nodes are available: 2 node(s) had taint {node-role.kubernetes.io/controlplane: true}, that the pod didn't tolerate, 6 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.`

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1628]
**Describe the bug**

unable to provision a load balancer when using harvester cloud provider on an rke1 cluster

**To Reproduce**
1. deploy an rke1 cluster using harvester node driver
  * enable harvester node driver 
2. once the rke1 cluster comes to active, deploy a load balancer either while deploying a workload or stand alone (serviceDiscovery -> services ->  create)
3. service deployment fails with error 

```
0/1 nodes are available: 1 node(s) had taint {node.cloudprovider.kubernetes.io/uninitialized: true}, that the pod didn't tolerate.
```

**Expected behavior**

rke1 cluster should be able to provision a load balancer 

**Support bundle**

n/a

**Environment:**
 - Harvester ISO version: v1.0.0-rc1
 - rancher version: v2.6.3-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): fremont datacenter

**Additional context**
this is working on rke2 clusters

**Comment by yaocw2020** [comment]
For rke1, users have to deploy harvester-cloud-provider from rancher market manually.

**Comment by guangbochen** [comment]
@yaocw2020 we will need to update the doc on how to setup the Harvester CCM in RKE1 with the new v1.0.0 release https://docs.harvesterhci.io/v1.0/rancher/cloud-provider/#deploying-to-the-rke1-cluster-with-harvester-node-driver
- the testing purpose u may need to provide a quick-to-test method since the Harvester CCM chart is not released.

**Comment by guangbochen** [comment]
close as documented on the https://docs.harvesterhci.io/v1.0/rancher/cloud-provider/#deploying-to-the-rke1-cluster-with-harvester-node-driver
