### ISSUE TITLE
[BUG] Welcome screen asks to agree to T&Cs for using Rancher not Harvester

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1634]
**Describe the bug**
The Harvester welcome screen post-install has a checkbox to agree to the T&Cs for using Rancher - shouldn't this be for using Harvester?

**To Reproduce**
1. Install Harvester
2. Go to management page and see last line (before Continue button)

**Expected behavior**
Whilst Rancher (software) is obviously being used for Harvester admin interface I expected to agree to T&Cs for using Harvester (not Rancher).

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: 0.3.0
 - Underlying Infrastructure: Baremetal with Intel NUC8i5BEH

**Additional context**
Screenshot
![Screenshot from 2021-12-03 13-51-17](https://user-images.githubusercontent.com/8300801/144879222-1f196ca4-80f0-4cd6-ae75-c1c518e41684.png)

It's possible the Rancher reference could refer to company but if so I'd expect that to be Rancher Labs, SUSE, or SUSE Rancher not plain Rancher.

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head went to https://rancher.com/eula although that redirects to https://www.suse.com/licensing/eula/ . Is that acceptable?

**Comment by wjimenez5271** [comment]
I see in the PR language now states "for using {vendor}". What does {vendor} get substituted with? Also the grammar isn't correct, you don't use a company, you use the product/software. Why not say "for using a Rancher Product"?

**Comment by noahgildersleeve** [comment]
> I see in the PR language now states "for using {vendor}". What does {vendor} get substituted with? Also the grammar isn't correct, you don't use a company, you use the product/software. Why not say "for using a Rancher Product"?

@wjimenez5271 What page are you referring to? I don't see that in the eula page. Also Is it acceptable for the link to go to https://rancher.com/eula and redirect to https://www.suse.com/licensing/eula/, or should it go somewhere else?

**Comment by guangbochen** [comment]
@WuJun2016 we should display either `Harvester` or `Rancher` upon the single or multi-cluster UI, should not use vendor here, thanks.

**Comment by WuJun2016** [comment]
I based on the default value in the ui-pl to determine whether it is harvester or rancher, if the default value is Harvester will be displayed as Harvester, other cases are displayed as Rancher.   
@guangbochen  @wjimenez5271 @noahgildersleeve   Do you think this is okay ?

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Verified that the text is changed and that the URL is linking to the SUSE EULA page
![Screenshot from 2021-12-10 16-37-13](https://user-images.githubusercontent.com/83787952/145657167-2d8ebd33-14d6-4c78-a30f-37075b206219.png)
.
