### ISSUE TITLE
[Question] No network interface has been specified yet after initial installation

### ISSUE THREAD

**Issue by oxr463** [harvester/harvester#1636]
I installed harvester on a single node and during the installation I chose `eno1` as the Management NIC and now I'm getting this message:

>  No network interface has been specified yet

URL: https://10.0.0.218/dashboard/c/local/harvester/harvesterhci.io.host/harvester#basics

![image](https://user-images.githubusercontent.com/43783393/144893226-d1c2b670-6a15-4866-bdd0-66bbcb0ee802.png)

I tried setting it to the management interface but it says that is not recommended.

![image](https://user-images.githubusercontent.com/43783393/144893465-b8f8f957-83a3-4ae8-9636-b73bd5e49fa0.png)

Reference(s):
- https://docs.harvesterhci.io/v0.3/install/iso-install

**Comment by yaocw2020** [comment]
It means you have not enabled the VLAN network. @oxr463 

Documentation: https://docs.harvesterhci.io/v1.0/networking/harvester-network/
