### ISSUE TITLE
Unfriendly error messages and memory units unification on Volumes page 

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#164]
**Steps to reproduce:**
1. Left the source and size blank, click the create button
2. Only left the source blank, click the create button

**Result:**
- [x] In the above cases, the error messages seem unfriendly
![image](https://user-images.githubusercontent.com/57614736/93753873-6702f480-fc33-11ea-9341-778b3eec7ff5.png)
![image](https://user-images.githubusercontent.com/57614736/93753896-7124f300-fc33-11ea-879f-ec57da348c14.png)

It's better to unify the units of memory
![image](https://user-images.githubusercontent.com/57614736/93754019-a5001880-fc33-11ea-91c5-b6eeee435bc1.png)

**Comment by guangbochen** [comment]
let's add `required` validation to the DV page first and leave the units as what it is for now since this is designed in purpose.

**Comment by DoNotSayYes** [comment]
Validated on 2019/09/25
![image](https://user-images.githubusercontent.com/57614736/94256053-c3c81d00-ff5b-11ea-8e43-1f9f0ba3536e.png)
![image](https://user-images.githubusercontent.com/57614736/94256083-d0e50c00-ff5b-11ea-83b7-ffe75a5174bf.png)
