### ISSUE TITLE
Request to have a different password between the root password for the Harvester install and the password for UI access[FEATURE]

### ISSUE THREAD

**Issue by aeppsSUSE** [harvester/harvester#1640]
**Is your feature request related to a problem? Please describe.**

For government, financial, and military contractor Clients there will be a requirement to have different passwords between the root account at the core of the Harvester install and the UI access. Segregation of duties requirements in these industries will not allow a datacenter UI user to have access to the core root password.
**Describe the solution you'd like**

Please allow an option for setting a separate password between the Harvester install root password and the UI access user password. Having the ability to define multiple UI access users would also be desirable
**Describe alternatives you've considered**

Not really any alternatives to this unless there is some sort of integration into a registry of some kind
**Additional context**

**Comment by ibrokethecloud** [comment]
I had a quick chat with @aeppsSUSE.

The node install password is already different from the harvester admin password for the cluster.

The ask seems to be more about ability to do fine grained RBAC for harvester workloads, which can be done via Rancher virtualization-management integration.

This documented here: https://docs.harvesterhci.io/v1.0/rancher/virtualization-management/#multi-tenancy
