### ISSUE TITLE
Setting Up Harvester Development Environment

### ISSUE THREAD

**Issue by wangpan-hqu** [harvester/harvester#1643]
I follow wiki Setting Up Harvester Development Environment, encountered a problem

FATA[0000] failed to create harvester server: Failed to create virtualMachineTemplateVersion harvester-public/iso-image-base-version: the server could not find the requested resource (post virtualmachinetemplateversions.meta.k8s.io)

**Comment by FrankYang0529** [comment]
Hi @wangpan-hqu, sorry for the inconvenience. We will update our documents for it.

Currently, for backup features, we will create a folder and mount NFS on it. It may need other permission to run `harvester` or `harvester-webhook` locally. We suggest replacing images in `harvester` and `harvester-webhook` deployments in `harvester-system` namespace to run them in the cluster. If you want to use the latest harvester image, you can run the following steps:

1. `kubectl edit deploy harvester -n harvester-system` to use `rancher/harvester:master-head` image.
2. `kubectl edit deploy harvester-webhook -n harvester-system` to use `rancher/harvester-webhook:master-head` image.

If you want to modify code and build your images, you can run the following steps:

1. Run `make default` in the harvester repository.
2. Run `docker images | grep harvester` and you will get images like `rancher/harvester:dev` and `rancher/harvester-webhook:dev`.
3. Rename images like `docker tag rancher/harvester:dev <username>/harvester:dev`.
4. Push to your DockerHub. `docker push <username>/harvester:dev`
5. `kubectl edit deploy harvester -n harvester-system` to use `<username>/harvester` image.
6. `kubectl edit deploy harvester-webhook -n harvester-system` to use `<username>/harvester-webhook` image.
