### ISSUE TITLE
[BUG] Switch kubevip pod in harvester cluster under dhcp (dnsmasq) the VIP is missing and failed to access harvester

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1645]
**Describe the bug**

In a 3 nodes harvester cluster with VIP setup on DHCP (dnsmasq), when kubevip switch from one node to another can make VIP out of connectivity. User can no longer able to access harvester dashboard by VIP. 

**Where to find** 
This issue discovered during the verification of upgrading harvester from v0.3.0 to v1.0.0-rc1

* vip br0 shutdown after reboot
```
33: vip-4b6f8081@harvester-br0: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default 
    link/ether 0e:93:58:8a:70:ab brd ff:ff:ff:ff:ff:ff
```

* kubevip pod log 
![image](https://user-images.githubusercontent.com/29251855/145182950-8d1ea35c-ca8c-4e58-9d75-a355b0ec9e26.png)

**Issue scope**
It is possible to affect user scenarios related to reboot and power cycle harvester nodes. 

**Steps to reproduce the behavior:**
1. Download harvester v0.3.0 iso and do checksum
2. Download harvester v1.0.0 iso and do checksum
3. Use ISO Install a 4 nodes harvester cluster 
4. Create several OS images from URL
5. Create ssh key
6. Enable vlan network with `harvester-mgmt`
7. Create virtual network `vlan1` with id `1`
8. Create 2 virtual machines
- ubuntu-vm: 2 core, 4GB memory, 30GB disk
- centos-vm: 2 core, 4GB memory, 30GB disk

![image](https://user-images.githubusercontent.com/29251855/144856833-1fccfb10-b9b2-4f5d-a9e5-c0cbbb4b0aca.png)

9. Setup backup target
![image](https://user-images.githubusercontent.com/29251855/144973526-7fc71bc4-8a95-41f7-b660-5aa22a8fe7be.png)

10. Take a backup from ubuntu vm
![image](https://user-images.githubusercontent.com/29251855/144973570-4db239c1-421a-4932-9780-1ed154e27c7d.png)

**upgrade process**
Follow the manual upgrade steps to upgrade from v0.3.0 to v1.0.0-rc1
https://github.com/harvester/docs/pull/67/files

**Expected behavior**

Can manual upgrade harvester from v0.3.0 to v1.0.0-rc1 with vm backup.
Harvester pods keeps working without crash

**Support bundle**

[bundle.zip](https://github.com/harvester/harvester/files/7673834/bundle.zip)

**Environment:**
 - Harvester ISO version before upgrade: v0.3.0
 - Harvester ISO version after upgrade: v1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes harvester cluster on local kvm machines

**Harvester network information**
 - VIP: 192.168.122.194
 - node1: 192.168.122.36
 - node2: 192.168.122.85
 - node3: 192.168.122.186
 - node4: 192.168.122.97

![image](https://user-images.githubusercontent.com/29251855/145160943-2668ba4f-45ff-4859-8614-c61d9e423adc.png)

**Additional context**

* workaround to access VIP 

1. Run `ip a` to check the vip-xxx@harvester-br0 device status
2. bring vip device up `ip link set vip-4b6f8081 up`
3. delete vip device `ip l del vip-4b6f8081`
4. `ip neigh flush all`
5. check kubevip pod log and status with the management role.

**Comment by TachunLin** [comment]
According to [issues/1681/comment](https://github.com/harvester/harvester/issues/1681#issuecomment-995389197) 

**As a workaround:**
>In case of user encounter the situation that they can't access harvester dashboard by VIP but they can still access (ssh) to each node ip. They can use the delete all kube-vip pod to make the VIP come back. 

> But please be noted, it based on you still can run `kubectl get pods` command 

```
harvester-node02-1216:/home/rancher # kubectl get pods -A | grep kube-vip
harvester-system kube-vip-cloud-provider-0 1/1 Running 4 88m
harvester-system kube-vip-f97km 1/1 Running 0 2m43s
harvester-system kube-vip-j79zd 1/1 Running 0 3m3s
harvester-system kube-vip-wbvhc 1/1 Running 0 3m55s

harvester-node02-1216:/home/rancher # kubectl delete pods -n harvester-system kube-vip-f97km
pod "kube-vip-f97km" deleted
harvester-node02-1216:/home/rancher # kubectl get pods -A | grep kube-vip
harvester-system kube-vip-cloud-provider-0 1/1 Running 4 92m
harvester-system kube-vip-j79zd 1/1 Running 0 7m11s
harvester-system kube-vip-jnsp9 1/1 Running 0 10s
harvester-system kube-vip-wbvhc 1/1 Running 0 8m3s
```

**We still need to reproduce and verify it after we fixed it in the v1.0.0-rc manual upgrade process**

**Comment by yaocw2020** [comment]
Log from kube-vip.
[kube-vip.log](https://github.com/harvester/harvester/files/7880915/kube-vip.log)

**Comment by gitlawr** [comment]
We can restart kube-vip pods in the `Upgrade Harvester and Monitoring services` stage to resolve it @bk201

**Comment by TachunLin** [comment]
On provo bare machines, I tried using `kubectl delete pods` to delete all nodes kube-vip pods to rebuild it. 
But still not able to access harvester dashboard via VIP.

**Comment by gitlawr** [comment]
@TachunLin Can you try applying https://github.com/gitlawr/upgrade-helpers/commit/4637dbd3a14630b5100506549f223fa0d0c88b14 before running `harv-upgrade-harvester.sh`

**Comment by yaocw2020** [comment]
During upgrading from 0.3 to 1.0, the ingress-expose svc and rancher-expose svc have the same VIP and mac address, so the macvlan interface for the ingress-expose svc used to request the IP has the same mac as the one for the rancher-expose. That is the reason of `address already in use`.

**Comment by TachunLin** [comment]
@gitlawr, @yaocw2020 after applying [gitlawr/upgrade-helpers@4637dbd](https://github.com/gitlawr/upgrade-helpers/commit/4637dbd3a14630b5100506549f223fa0d0c88b14) to `harv-upgrade-harvester.sh` before upgrade.

We can access harvester dashboard by VIP after manual upgrade from v0.3.0 to v1.0.0 GA

Can you create a pull request to [upgrade-helpers](https://github.com/harvester/upgrade-helpers) to add this fix. Thank you.

![image](https://user-images.githubusercontent.com/29251855/150323427-6e6f5f5c-2d62-4053-8926-e3f361fa88fd.png)

### Test Information
Test Environment: 3 nodes harvester cluster on local kvm machines
Harvester version before upgrade: v0.3.0
Harvester version upgrade target: v1.0.0 

### Upgrade Steps
Follow the [manual upgrade document ](https://github.com/harvester/docs/blob/a4be9a58441eeee3b5564b70e499dc69c6040cc8/docs/upgrade.md)

### Additional context
* Check kube-vip after upgrade done
```
rancher@hpd8s7:/usr/local/harvester-upgrade> sudo -i kubectl get pods -A | grep kube-vip
harvester-system kube-vip-cloud-provider-0 1/1 Running 2 98m
harvester-system kube-vip-dppt6 1/1 Running 0 86s
harvester-system kube-vip-mm5z7 1/1 Running 0 95s
harvester-system kube-vip-x74mk 1/1 Running 0 99s
```     
* Check IP address status after upgrade done 
```
rancher@hpd8s7:~> ip a | grep 10.84
     inet 10.84.44.114/23 brd 10.84.45.255 scope global harvester-mgmt
     inet 10.84.44.114/23 brd 10.84.45.255 scope global harvester-br0
     inet 10.84.44.124/32 scope global harvester-br0
```

**Comment by TachunLin** [comment]
After adding restart kube-vip pod mechanism into `harv-upgrade-harvester.sh`, after manual upgrade this issue did not happen.
Close this issue since the fix have already merged to the [upgrade-helper](https://github.com/harvester/upgrade-helpers)
