### ISSUE TITLE
[FEATURE] Support Bundle timeout enhancement 

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1646]
I would suggest we revert the change: rancher/support-bundle-kit#16 (comment) to collect node bundles even some nodes don't push bundle ack in time.

Related to: https://github.com/harvester/harvester/issues/1585

**Comment by Yu-Jack** [comment]
It's related to https://github.com/rancher/support-bundle-kit/issues/73

**Comment by Yu-Jack** [comment]
Some findings from @albinsun , some minimum value should not be `30`. It's default. PR https://github.com/harvester/docs/pull/646 for this.

**Comment by albinsun** [comment]
Test PASS, close as done.

Note that current [doc](https://docs.harvesterhci.io/v1.4/advanced/index/#support-bundle-node-collection-timeout) does not mention about the definition of `0` like [`support-bundle-timeout`](https://docs.harvesterhci.io/v1.4/advanced/index/#support-bundle-timeout) and should be an enhancement.
CC. @Yu-Jack 


### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: 3 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: Auto
 

### Verification
Define settings > support-bundle-node-collection-timeout (unit is minute)
Create support bundle
Check SUPPORT_BUNDLE_NODE_TIMEOUT of support bundle manager deployment.apps

#### Positive
1. :green_circle: Default value and successful donwload
   <details>
   <summary> <i>Given</i> <b>support-bundle-node-collection-timeout</b> is <code>30</code> (default)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f814575c-3c41-4bdc-a34a-638bd4358af6)
   </details>

   <details>
   <summary> <i>When</i> <b>Generate a Support Bundle</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a8323423-a51f-4f6a-8c59-929f4bf8ac86)
   </details>

   <details>
   <summary> <i>Then</i> SB deployment's <code>SUPPORT_BUNDLE_NODE_TIMEOUT</code> is <code>30</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/589e7473-c0a4-46ac-93a6-55554febc6bd)
   </details>

   <details>
   <summary> <i>And</i> SB download successfully and contains all 3 nodes log
   </summary>
   
   ![image](https://github.com/user-attachments/assets/df5329a5-af46-4119-abfd-7a52b4034e02)
   </details>


1. :green_circle: Longer value and successful donwload
   <details>
   <summary> <i>Given</i> <b>support-bundle-node-collection-timeout</b> is <code>180</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5f02a9b1-c593-419d-8683-4f7b9104f595)
   </details>

   <details>
   <summary> <i>When</i> <b>Generate a Support Bundle</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4668b355-8c5a-4b91-ae8b-d1cfb96cd640)
   </details>

   <details>
   <summary> <i>Then</i> SB deployment's <code>SUPPORT_BUNDLE_NODE_TIMEOUT</code> is <code>180</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/4668b355-8c5a-4b91-ae8b-d1cfb96cd640)
   </details>

   <details>
   <summary> <i>And</i> SB download successfully and contains all 3 nodes log
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a6e8186c-e33b-43dd-91d5-2a02ec4c45c9)
   </details>


1. :green_circle: Shorter value and successful donwload
   <details>
   <summary> <i>Given</i> <b>support-bundle-node-collection-timeout</b> is <code>3</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/10f0d89c-9142-43e8-a0ba-87873dd84012)
   </details>

   <details>
   <summary> <i>When</i> <b>Generate a Support Bundle</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e4c7c36d-e0d6-4c6d-86c8-aa6bb5e68158)
   </details>

   <details>
   <summary> <i>Then</i> SB deployment's <code>SUPPORT_BUNDLE_NODE_TIMEOUT</code> is <code>3</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/e4c7c36d-e0d6-4c6d-86c8-aa6bb5e68158)
   </details>

   <details>
   <summary> <i>And</i> SB download successfully and contains all 3 nodes log
   </summary>
   
   ![image](https://github.com/user-attachments/assets/91ed3225-e1ad-4531-8224-98719fbe280f)
   </details>

 
#### Negtive
1. :green_circle: Timeout
   <details>
   <summary> <i>Given</i> <b>support-bundle-node-collection-timeout</b> is <code>1</code> (min value)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c2f6574f-5b00-48ef-adac-ffae6e03f0b4)
   </details>

   <details>
   <summary> <i>When</i> <b>Generate a Support Bundle</b>
   </summary>

   ![image](https://github.com/user-attachments/assets/19246f60-81b3-4953-957f-a1e8a0f55d95)
   </details>

   <details>
   <summary> <i>And</i> force shutdown <b>node-1</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e1a7766c-464f-44f2-ab67-efca1efb2a5a)
   </details>

   <details>
   <summary> <i>Then</i> SB deployment's <code>SUPPORT_BUNDLE_NODE_TIMEOUT</code> is <code>1</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/19246f60-81b3-4953-957f-a1e8a0f55d95)
   </details>

   <details>
   <summary> <i>And</i> SB download successfully but only contains 2 nodes log
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5c9ca166-618d-406c-8452-aeb8e67512ec)
   </details>


1. :yellow_circle: Invalid values (0, minus, string...)
   * <details>
     <summary> :heavy_check_mark: decimal number should be invalid.
     </summary>
     
     ![image](https://github.com/user-attachments/assets/3da52bb5-811f-41b0-a1b1-785f4edf942d)
     </details>

   * <details>
     <summary> :heavy_check_mark: negtive number should be invalid.
     </summary>
     
     ![image](https://github.com/user-attachments/assets/d8ed46e1-135c-4bb7-8d51-d0b0b765a33c)
     </details>

   * <details>
     <summary> :heavy_check_mark: text should be invalid.
     </summary>
     
     ![image](https://github.com/user-attachments/assets/b9da04b3-9641-40b5-ae61-7da37cf2ad1a)
     </details>

   * <details>
     <summary> :heavy_check_mark: empty should be convert to default value.
     </summary>
     
     ![image](https://github.com/user-attachments/assets/b8380f16-a99c-4110-acea-a1bed3b6cb42)
     </details>

   * <details open>
     <summary> 0's behavior.
     </summary>
     
     > :question: `0` will convert to default value `30` mins.
     > ![image](https://github.com/user-attachments/assets/a8e4f608-fc81-4dda-9c38-96d493590262)
     </details>


### Supportbundle


### QA Check List
1. Update labels
   - [x] This ticket: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
   - [x] tests ticket: <TICKET>
