### ISSUE TITLE
[FEATURE] Support configuring a VLAN at the management interface in the ISO installer UI

### ISSUE THREAD

**Issue by bashofmann** [harvester/harvester#1647]
**Is your feature request related to a problem? Please describe.**
As a follow up to https://github.com/harvester/harvester/issues/1390, it should be possible to also support setting a vlan for the management interface in the ISO installer UI.

**Describe the solution you'd like**
The installer UI has an additional input field for the vlan id in the network step.

**Additional context**
The vlan id can be necessary to get a working network.

If you use the ISO installer, you can’t edit the config file manually in the ISO installer UI (https://github.com/harvester/harvester/issues/1391). 

And since you don’t have a working network without a vlan id, you also can’t load the config from an external server.

**Comment by johnliu55tw** [comment]
This issue depends on #1390.

**Comment by tjjh89017** [comment]
wait for new VLAN design

**Comment by tjjh89017** [comment]
## Test plan

### No vlan

1. boot installer
2. set VLAN=1 or leave VLAN field empty
3. keep installing
4. no error found
5. harvester has network connectivity
6. `ip a show dev mgmt-br` has IP

### VLAN

1. setup VLAN env
2. boot installer
3. set VLAN id
4. keep installing
5. no error found
6. harvester has network connectivity
7. `ip a show dev mgmt-br.<VLAN ID>` has IP
e.g `ip a show dev mgmt-br.100`

**Comment by TachunLin** [comment]
### Test plan 
We have the following test plan for ISO installation on create and join mode with no and valid vlan configuration.

### Create mode
#### No VLAN 
|                 | DHCP VIP | static VIP |
|-----------------|:--------:|:----------:|
| DHCP node ip    |   PASS       |            |
| Static node ip  |   PASS       |            |

#### VLAN 
|                 | DHCP VIP | static VIP |
|-----------------|:--------:|:----------:|
| DHCP node ip    |   PASS   |            |
| Static node ip  |         |            |


### Join mode
#### No VLAN 
|                 | DHCP VIP | static VIP |
|-----------------|:--------:|:----------:|
| DHCP node ip    |      |            |
| Static node ip  |      |            |

#### VLAN 
|                 | DHCP VIP | static VIP |
|-----------------|:--------:|:----------:|
| DHCP node ip    |   PASS   |            |
| Static node ip  |      |            |

**Comment by lanfon72** [comment]
Closed along with #1390, configuration will settled correctly after UI options filled in.
For Test cases listed in https://github.com/harvester/harvester/issues/1647#issuecomment-1259120715, there is no obvious different for vlan configuration between DHCP and static IP, so we just test one of it.
