### ISSUE TITLE
[BUG] Restoring status from backup never changes to running

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1650]
**Describe the bug**

When you restore a vm from backup it goes to restoring status, but never back to running
**To Reproduce**
1. Create new VM
2. Take backup
3. restore from backup
**Expected behavior**

After restore is done the status should go back to running
**Support bundle**

[supportbundle_754ee1c7-96c6-45f2-98a9-705f42b7a2f6_2021-12-09T01-38-27Z.zip](https://github.com/harvester/harvester/files/7681560/supportbundle_754ee1c7-96c6-45f2-98a9-705f42b7a2f6_2021-12-09T01-38-27Z.zip)

**Environment:**
 - Harvester ISO version: master-655c251a-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node vagrant ipxe setup

**Additional context**
If you refresh the page it will update with running, but it requires a manual page load

### Test plan

Take Backup without error.

1. Create a VM.
2. Setup Backup Target.
3. Take a VMBackup for the VM.
4. Before VMBackup is ready, there should not have any error message in `VMBackup.status`.

**Comment by yasker** [comment]
sounds like the websocket problem. can you check if there are error messages in the developer's console? Reenable the warning should solve it.

**Comment by noahgildersleeve** [comment]
I tried it again and checked the web console and the network traffic via developer tools and didn't see anything. I also did all of this after resetting the enable warning setting on the SSL cert. A refresh still fixed the issue.

**Comment by noahgildersleeve** [comment]
When you create a backup the label updates after creation with an error. I tested this on an NFS server that was created on the embedded Rancher, but it should do it on any one.
## Validation steps
1. Set a valid NFS target in settings
2. Create a new VM
3. Log into VM and create a file and put some text in it
4. run `sync` to write out memory to the disk
5. run a NFS backup
6. immediately check backups page in Harvester UI
![Screenshot from 2022-01-28 12-17-29](https://user-images.githubusercontent.com/83787952/151616869-885dec3e-4297-40db-a832-12b644a480f9.png)
[supportbundle_a321024d-5846-41f4-afc3-6ac406a12476_2022-01-28T20-17-44Z.zip](https://github.com/harvester/harvester/files/7961659/supportbundle_a321024d-5846-41f4-afc3-6ac406a12476_2022-01-28T20-17-44Z.zip)

**Comment by WuJun2016** [comment]
@guangbochen  This may be a backend issue.

**Comment by noahgildersleeve** [comment]
It shows the error then it continues to create the backup. the issue is that it shouldn't be showing the error.

**Comment by FrankYang0529** [comment]
> It shows the error then it continues to create the backup. the issue is that it shouldn't be showing the error.

This is related LH issue https://github.com/longhorn/longhorn/issues/3392. We parse status in VolumnSnapshot. If there is an error message in VolumnSnapshot, we also set it in VMBackup. However, this error message is temporary, so we will clear the error status and get a healthy VMBackup after VolumnSnapshot is done.

![Screen Shot 2022-02-09 at 11 42 27 AM](https://user-images.githubusercontent.com/4927361/153117872-7e101875-6681-430e-90c5-61f3aec35ec7.png)

**Comment by rebeccazzzz** [comment]
PR has been created https://github.com/longhorn/longhorn-manager/pull/1233. Longhorn will backport it to 1.2.4. Moving this issue out of the icebox.

**Comment by rebeccazzzz** [comment]
Moving this back to icebox until Longhorn RC

**Comment by rebeccazzzz** [comment]
Longhorn v.1.2.4 RC1 is available. Moving this issue out of the icebox and into implement. https://github.com/longhorn/longhorn/releases/tag/v1.2.4-rc1

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/157408769-c00660d3-524a-4e1a-8c9b-8727753c847e.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-fd872c99-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow the steps in https://github.com/harvester/harvester/issues/1650#issuecomment-1024612633
