### ISSUE TITLE
Can Harvester monitoring host hardwares?

### ISSUE THREAD

**Issue by coption** [harvester/harvester#1652]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FrankYang0529** [comment]
Hi @coption, yes, I think so. Harvester is designed as a Hyperconverged infrastructure (HCI) solution for bare metal servers.

https://harvesterhci.io/

**Comment by yasker** [comment]
Duplicate with https://github.com/harvester/harvester/issues/2318
