### ISSUE TITLE
[BUG] Create new VLAN shows duplicate records on networks page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#1653]
**Describe the bug**

Create new VLAN shows duplicate record on networks page
![image](https://user-images.githubusercontent.com/29251855/145393032-4209fe43-ca84-4905-a62d-bb4cb966d163.png)

**To Reproduce**
1. Enable vlan with `harvester-mgmt`
2. Access Network page
3. Click Create
4. Given name and vlan id
5. Select `Manual` mode 
6. Give `CIDR` and `Gateway`
7. Click Create
8. Check result in Network page

**Expected behavior**

Should only show one record of the newly created VLAN

**Support bundle**

[supportbundle_64c6765c-8ac9-4828-925b-70e99e39da01_2021-12-09T12-08-04Z.zip](https://github.com/harvester/harvester/files/7684910/supportbundle_64c6765c-8ac9-4828-925b-70e99e39da01_2021-12-09T12-08-04Z.zip)

**Environment:**
 - Harvester ISO version: master-ee09e0c8-head (12/7 after v1.0.0-rc1)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes bare machines in provo

**Additional context**
Refresh page is a workaround

**Comment by n313893254** [comment]
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/be90151e-6d02-4914-9bf4-b6df4db7ab3d)

Reproduce the issue randomly, maybe **Reproduce Steps**
- Create a resource
- Delete the resource
- Create a resource with the name as the first create

There has some console errors about resourceVersion throw by WebSocket subscribe:
`failed to list kubevirt.io.virtualmachine: The resourceVersion for the provided list is too old.`

**Addictional Context**
![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/52fc28de-6fb5-471d-957b-329493e92df4)

**Comment by n313893254** [comment]
Closed the issue in favor same as https://github.com/harvester/harvester/issues/1111.
