### ISSUE TITLE
[BUG] When using a VM Template the Network Data in the template is not displayed

### ISSUE THREAD

**Issue by roncterry** [harvester/harvester#1655]
**Describe the bug**
When creating a VM using a VM template that contains both user data and network data the network data is not displayed on the Virtual Machine: Create - Advanced Options screen. After creating the VM it appears that the network data was used even though it was not displayed on the create screen because it is displayed on the Advanced Options screen of the running VM.

**To Reproduce**
Create a VM template with network data. Create a VM using the VM template. View the Virtual Machine: Create - Advanced Options screen.

**Expected behavior**
The Network Data should be displayed like the User Data is.

**Support bundle**

[supportbundle_bf7fcf45-64e7-4b57-9499-30359d8de5ba_2021-12-09T20-01-19Z.zip](https://github.com/harvester/harvester/files/7688087/supportbundle_bf7fcf45-64e7-4b57-9499-30359d8de5ba_2021-12-09T20-01-19Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal

**Additional context**
(none)

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Verified that network template data showed up after VM creation.
![Screenshot from 2021-12-12 15-58-19](https://user-images.githubusercontent.com/83787952/145734902-5e8a9f3c-12b9-4d96-ad5e-42e0f1b94cec.png)

**Comment by roncterry** [comment]
I think you misunderstood the problem. The network data always appeared after VM creation. The problem is that the network data doesn’t show up _before_ VM creation when selecting a VM template and then looking at the Virtual Machine: Create - Advanced Options screen.

**Comment by guangbochen** [comment]
Can we re-validate this issue, IIUC, this is also fixed using the master-head version:
- create a VM template on the templates page and add `network-data` config on the advanced option
- save the template and launch a new VM from the template
- check thew new VM created by the template contains the `network-data` specified on the VM template.

**Comment by noahgildersleeve** [comment]
Tested in master-5e8d9764-head. Verified as fixed.
## Test Steps
1. Create new VM template with network data in advanced settings
2. Create new VM and select template
3. Verify that network data is in advanced network config
