### ISSUE TITLE
[FEATURE] update RKE2 default cloud config path

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1658]
**Is your feature request related to a problem? Please describe.**
related to https://github.com/harvester/charts/pull/58

**Describe the solution you'd like**
- should set RKE2 default cloud config path to  `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` via `helmChartConfig` as the default path of chart is updated via https://github.com/harvester/charts/pull/58/files#diff-00e1ad718da686a8dd7b7dd718d74b46cbf640b160fcd09e51e4ef5edcb59922R14

**Comment by noahgildersleeve** [comment]
Tested in Harvester in version master-a67f96d0-head and Rancher in version de87624 (off of v2.6-head with docker install) and I got errors on provisioning RKE2 clusters. This was in v1.22.5, v1.21.8 and v1.21.7. RKE1 in v1.21.8 worked fine. The RKE2 clusters didn't even create a VM in Harvester. Got error 
```
Failed to create fleet-default/rke2 cluster.x-k8s.io/v1beta1, Kind=Cluster for rke-cluster fleet-default/rke2: Internal error occurred: failed calling webhook "default.cluster.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-cluster?timeout=10s": service "webhook-service" not found, failed to create fleet-default/rke2-opensuse cluster.x-k8s.io/v1beta1, Kind=MachineDeployment for rke-cluster fleet-default/rke2: Internal error occurred: failed calling webhook "default.machinedeployment.cluster.x-k8s.io": Post "https://webhook-service.cattle-system.svc:443/mutate-cluster-x-k8s-io-v1beta1-machinedeployment?timeout=10s": service "webhook-service" not found
```
![Screenshot from 2022-01-27 16-27-50](https://user-images.githubusercontent.com/83787952/151465895-625255f3-251e-41e9-8446-3bca73224a05.png)
![Screenshot from 2022-01-27 16-25-36](https://user-images.githubusercontent.com/83787952/151465901-3e73fbf5-7212-45cd-bba5-08797d17069e.png)

This might be dependent on fixing whatever the provisioning error is.

**Comment by bashofmann** [comment]
Current status with Rancher 2.6.3 and RKE2 1.21.8+rke2r2:

When you provision an RKE2 cluster through Rancher with the harvester node driver, the cloud config path for the harvester-cloud-provider helm chart is correctly set by the UI (https://github.com/rancher/dashboard/blob/master/edit/provisioning.cattle.io.cluster/rke2.vue#L1027).

But the cloud config path in the harvester-csi-driver helm chart is not adapted and points to `/etc/kubernetes/cloud-config` which breaks the CSI driver.

I'm also not sure, if the UI is the correct location for such logic. By only having this in the UI, every other client that you use for automation (Terraform, GitOps, client using the rest api such as ansible) would need to implement the same logic.

**Comment by guangbochen** [comment]
We are now setting the `/var/lib/rancher/rke2/etc/config-files/cloud-provider-config` as the default cloud-config file path of both CSI and Harvester CCM chart so it will be compatible with RKE2. If the above-provided path is not found the [code](https://github.com/harvester/harvester-csi-driver/commit/5700629c292bf005e3c5042553ee1fedc654e5e6) will check the path `/etc/kubernetes/cloud-config`  again before returning an error. Therefore it should make the other automation deployment integration fully compatible. 
This can be validated together with the issue https://github.com/harvester/harvester/issues/1895, thanks.

**Comment by guangbochen** [comment]
@bashofmann close as the proposed solution will be fixed on the https://github.com/harvester/harvester/issues/1895, feel free to reopen this one if u have any further questions, thanks.
