### ISSUE TITLE
[BUG] The volume unit on the vm details page is incorrect

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1660]
**Describe the bug**

size 100M volume,  when added to a VM, it is shown as 107374182400m 
![image](https://user-images.githubusercontent.com/24985926/145540880-cf65034c-56c4-4821-9098-1fbd023b72eb.png)

**To Reproduce**
1. Create a volume of size 0.1Gi in the volume page
2. Create a vm and add the previously created volume
3. Go to the vm details page, click on the volume tab, and check the size display

**Expected behavior**

The units displayed in the volume should be the same as when it was created

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
Fixed:
![image](https://user-images.githubusercontent.com/24985926/145541635-3470ddcc-5229-4679-938b-6741f19348aa.png)

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. Verified as fixed.
## Test Steps
1. Create new .1G volume
2. Create new VM
3. Create with raw-image template
4. Add opensuse base image
5. Add .1G Volume
6. Verify size in VM details on volume tab
![Screenshot from 2021-12-10 17-12-05](https://user-images.githubusercontent.com/83787952/145658516-73f5c72c-2543-46cd-9f90-8bc47f5ce2d4.png)
