### ISSUE TITLE
[BUG] You can create a VM with an image that isn't finished downloading

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1663]
**Describe the bug**

You can create 
**To Reproduce**
1. Start a download of an image via URL
2. Create a VM before the image is finished downloading
**Expected behavior**

You should only see images that are marked as ready in the image dropdown
**Support bundle**

[supportbundle_11313be7-18bf-4a72-adf9-c47bb28f06b5_2021-12-12T22-10-51Z.zip](https://github.com/harvester/harvester/files/7699960/supportbundle_11313be7-18bf-4a72-adf9-c47bb28f06b5_2021-12-12T22-10-51Z.zip)

**Environment:**
 - Harvester ISO version: master-655c251a-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node vagrant setup

**Additional context**
This is a little hard to repro if you don't have a slow connection to the download URL. I would recommend picking a mirror for an img that is geographically far from you, or restrict bandwidth on the machine.

**Comment by yasker** [comment]
Might be too late to solve in 1.0. Need to triage and potentially reschedule

**Comment by n313893254** [comment]
Add/Update image validation when creating VM

- [x] RKE1 node driver
- [x] RKE2 node driver
- [x] VM page
- [x] Image list page

**Comment by yasker** [comment]
We're running out of time for v1.0.0 release. Move this to v1.0.1.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

- [x] Volume Creation
- [x] VM page
- [x] RKE1 node driver
- [x] RKE2 node driver


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-a67f96d0-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6.3**

### Verify Steps:
1. Install Harvester with any Nodes
2. Create a Image from URL and need long downloading
3. Navigate to **Volumes** page, Create Volume from **Source: VM Image**
4. Downloading Image should not listed in the following **Image** field
5. Navigate to **Virtual Machines** page, Create VM then click **Volumes** tab
6. Downloading Image should not listed in the **Image** field
7. Install Rancher then login to Cluster Management
8. Navigate **RKE1 Configuration** -> **Node Templates**
9. Create Template for Harvester
    - The **Network Name** field name must to be available in Harvester **Networks** page
    - The **Image** field name must to be the image name(`metadata.name`, auto-generated), not displayName (configured by user)
9. Navigate to **Clusters** and Create Harvester Cluster (RKE1 and RKE2)
9. The Cluster should failed on Provisioning with **Image not exists** error when the Image still in downloading progress
