### ISSUE TITLE
[FEATURE] Manual upgrade from 0.3.0 to 1.0.0

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1665]
This is the epic issue to track all manual upgrade issues:

- [ ] Document: https://github.com/harvester/docs/pull/67
- [x] https://github.com/harvester/harvester/issues/1644
- [x] https://github.com/harvester/harvester/issues/1645
- [x] https://github.com/harvester/harvester/issues/1666
- [x] https://github.com/harvester/harvester/issues/1738
- [x] https://github.com/harvester/harvester/issues/1742
- [ ] https://github.com/harvester/harvester/issues/1741

**Comment by TachunLin** [comment]
@bk201, @guangbochen, Update the latest test result of manual upgrade on provo bare machine:

Follow the enhanced scripts and steps according to the [manual upgrade document](https://github.com/harvester/docs/blob/a4be9a58441eeee3b5564b70e499dc69c6040cc8/docs/upgrade.md) 
Now we can successful perform manual upgrade from existing v0.3.0 to v1.0.0 GA 

**Successful Check point** 

- [x] Upgrade to target version v1.0.0 
- [x] All pods is running correctly
- [x] Can access dashboard by VIP
- [x] Can use original password to login
- [x] Can start VM in running status
- [x] Image exists without corrupted
- [x] Volume exists
- [x] SSH key exists
- [x] Virtual network exists
- [x] Backup exists
- [x] Setting value exits

**Existing issue check result** 
* #1645 : 
    - `PASS`: We can access harvester by DHCP VIP after manual upgrade by adding the restart kube-vip pod to the `harv-upgrade-harvester.sh` 
* #1741: 
    - `PASS`: Images exists after manual upgrade on provo bare machine (with sufficient resource)
* #1742: 
    - `PASS`: CPU usage stable on host page after manual upgrade on provo bare machine (with sufficient resource)

**Comment by TachunLin** [comment]
Close this issue, since the related dependency issue #1741 and #1742 only exists when harvester system resource almost close to full usage and we also validate these issue did not happen on bare metal machine with plenty of available resource. 
We can add reminder to document to notify user beware of available usage before doing manual upgrade
