### ISSUE TITLE
Edit a template, only name and description are populated with what were previously filled in

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#167]
**Steps to reproduce:**
1. Create a template, fill in all the fields with values
2. After the template is created, choose it and to edit as form/edit as YAML

**Result:**
 Only name and description are populated with what were previously filled in, other fields are blank
![image](https://user-images.githubusercontent.com/57614736/93853691-e56c9e80-fce6-11ea-9235-473f45fc9122.png)

**Comment by WuJun2016** [comment]
Now we can't edit the template. Some actions have been deleted.  @DoNotSayYes
