### ISSUE TITLE
Task: mark external Harvester cluster provisioning support as experimental 

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1671]
Need it in the release note and the doc. 

It’s due to lacks of automatically field population #1244

**Comment by guangbochen** [comment]
Note: 
- RKE1 node driver is GA
- RKE2 node driver is experimental
- External Harvester is experimental

**Comment by yasker** [comment]
Test with Rancher 2.6.3-rc5 with UI set to `remote`.

**Test result: Failed** 

Reopen the issue.

Verified that `Experimental` label has been added to the `Cloud Credentials` for `External Harvester`
<img width="881" alt="Screen Shot 2021-12-15 at 9 14 22 AM" src="https://user-images.githubusercontent.com/3344618/146233410-d3f11b88-f4fa-4ee8-a0f5-fb6f70f86e70.png">

And cloud credential creation.
<img width="810" alt="Screen Shot 2021-12-15 at 9 16 10 AM" src="https://user-images.githubusercontent.com/3344618/146233518-ae9777a8-0753-4137-8df1-2976a5df72e7.png">

**However, it's not in the RKE1 Node template.**
<img width="825" alt="Screen Shot 2021-12-15 at 9 17 23 AM" src="https://user-images.githubusercontent.com/3344618/146233709-bdaaba60-5667-432f-a28a-0d6b8ed6f004.png">

**Comment by noahgildersleeve** [comment]
Verified in Rancher v2.6.3-rc5, although to get latest upstream UI changes I specified `ui-offline-preferred` to be `Remote`. Verified using previous steps. Closing as fixed.

> Test with Rancher 2.6.3-rc5 with UI set to `remote`.
> 
> **Test result: Failed**
> 
> Reopen the issue.
> 
> Verified that `Experimental` label has been added to the `Cloud Credentials` for `External Harvester` <img alt="Screen Shot 2021-12-15 at 9 14 22 AM" width="881" src="https://user-images.githubusercontent.com/3344618/146233410-d3f11b88-f4fa-4ee8-a0f5-fb6f70f86e70.png">
> 
> And cloud credential creation. <img alt="Screen Shot 2021-12-15 at 9 16 10 AM" width="810" src="https://user-images.githubusercontent.com/3344618/146233518-ae9777a8-0753-4137-8df1-2976a5df72e7.png">
> 
> **However, it's not in the RKE1 Node template.** <img alt="Screen Shot 2021-12-15 at 9 17 23 AM" width="825" src="https://user-images.githubusercontent.com/3344618/146233709-bdaaba60-5667-432f-a28a-0d6b8ed6f004.png">

**Comment by noahgildersleeve** [comment]
![Screenshot from 2022-01-05 16-07-11](https://user-images.githubusercontent.com/83787952/148307474-93d06531-0835-4312-b5d0-e9131309d2ad.png)
