### ISSUE TITLE
[FEATURE] Provide VIP load balancer service for VM workloads

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1676]
Currently, the VIP feature only works for applications deployed in a guest K8s cluster. 
There is a requirement to also provision VIPs for traditional VM workloads deployed on Harvester, including for the following use cases:

- Expose a VM workload on a secondary public IP (similar to AWS elastic IP, or Openstack floating IP feature)
- Provide failover mechanism for high available applications deployed across multiple VM instances
- Support the horizontal scaling of VM applications (load balancing)
- etc.

**Comment by Yabbo** [comment]
second this

**Comment by yaocw2020** [comment]
If we adopt OSPF/IS-IS/BGP protocol to expose the VIP for the VM workloads, is it convenient in the real environment?

**Comment by yaocw2020** [comment]
If we adopt OSPF/IS-IS/BGP protocol to expose the VIP for the VM workloads, is it OK in the real environment? @janeczku @Yabbo

**Comment by yaocw2020** [comment]
https://github.com/kube-vip/kube-vip/issues/244

**Comment by tjjh89017** [comment]
> Expose a VM workload on a secondary public IP (similar to AWS elastic IP, or Openstack floating IP feature)

Note:
Load balancer (L4) is different from OpenStack Floating IP (L3).
Need to check the requirement to determine LB or floating ip.

**Comment by abonillabeeche** [comment]
Second this...!

**Comment by inmanturbo** [comment]
What is the status on this? It looks like it was mentioned in #2337, but that PR does nothing to provide this feature.

**Comment by guangbochen** [comment]
This issue is expected to be addressed at the ~~v1.1.2~~ v1.2 milestone and mainly depends on the PRs mentioned in https://github.com/harvester/harvester/issues/2134.

**Comment by jmcglock** [comment]
Can we get another status update on this?
Thanks!

**Comment by yaocw2020** [comment]
> Can we get another status update on this? Thanks!

The Pr https://github.com/harvester/load-balancer-harvester/pull/13 is reviewing.

**Comment by yaocw2020** [comment]
https://github.com/harvester/harvester/blob/cc849f78afb0d676a5485ddac7d1ee687a7e4505/enhancements/20220214-harvester-cloud-provider-enhancement.md

**Comment by yaocw2020** [comment]
Provide failover mechanism for high available applications deployed across multiple VM instances

----
For this requirement, we integrate the kube-vip into harvester cloud provider. Thus, VIPs would be scattered to various guest clusters.  This is not a thorough approach, but it can provide a degree of fault tolerance.

**Comment by TachunLin** [comment]
## Test Plan 

- New Features in Network > Load Balancer

More test plans are under description 

#### Basic operation

- [x] Create
- [x] Delete
- [x] Edit config
- [x] Edit YAML
- [x] Download YAML
- [x] Clone

#### IPAM mode

- [x] DHCP mode to Harvester dhcp service
  - [x] Bind LB to existing VM workload and check the route connectivity

- [x] Pool mode to each types of IP pools
  - [x] Bind LB to existing VM workload and check the route connectivity

#### Negative of binding server

- [x] Check it is prohibited if the load balancer can't match any vm by using server selector
     - [x]  Prompt no virtual machine instance matched

- [x] Check any abnormal behavior when we edit load balancer server selector config or delete the binded vm workload

    - [x]    When we delete the backend vm server, the load balancer can keep in `Active` status
    - [x]    When we edit the LB selector to the none exists VM: 
         - Prompt no virtual machine instance matched
    - [x]    When we edit the LB selector to another running VM: (e.g from nginx2 to nginx1) 
    
- [x] When Load balancer can't find available IP address in the given IP Pool
      - The load balancer would display `Not ready` state
     ![image](https://github.com/harvester/harvester/assets/29251855/c02c99fa-d686-4ff6-9446-cd1eb77bef68)

#### Namespace

- [x] Set LB to the corresponding to the VM on default and harvester-public namespace
- [x] Create the LB to the customized namespace and can set it to the corresponding VM

#### Listeners

- [x] Set different  `Protocol` , `Port` and `Backend Port` as the listener and test the route connectivity
    - [x] Bind different lb ports to the same backend port should be prohibited
       - [Enhancement] should be blocked with prompt message
    - [x] Bind the same lb ports to diffrent backend ports should be prohibited
       - [Enhancement] should be blocked with prompt message
    - [x] Bind the same lb port to the same backend port should be prohibited
       - [Enhancement] should be blocked with prompt message
    - [x] Bind different lb ports on separate LB to the same backend port should be allowed
- [x] Remove listeners 

#### Server Selector
- [x] Check the key value pair can match to specific vm
- [x] Mutiple server selector
- [x] Remove sever selector


#### Health Check 
Ref: #4135 [[BUG] Load Balancer creation with Health Check creates data-type unmarshalling error](https://github.com/harvester/harvester/issues/4135)
- [x] Check the Health check on DHCP load balancer and functionality works as expected 
- [x] Check the Health check on Pool load balancer and functionality works as expected 

### Reference test plan
https://harvester.github.io/tests/manual/harvester-rancher/62-configure-k3s-dhcp-loadbalancer/
https://harvester.github.io/tests/manual/harvester-rancher/63-configure-k3s-pool-loadbalancer/
https://harvester.github.io/tests/manual/harvester-rancher/65-configure-k3s-pool-lb-healthcheck/

**Comment by TachunLin** [comment]
## Issues found and enhancement list 

1. [Bug] When we edit config of the existing load balancer, click `Edit as Yaml`, don't change anything then save directly. The state of load balancer become `Not Read` 


      ![image](https://github.com/harvester/harvester/assets/29251855/29d168cc-f2f8-4355-a21d-050db891e76e)

2. [Bug] Follow the previous steps, when a load balancer status become `Not Ready`.  After we 
      - Delete the not ready load balancer 
      - Create a new load balancer using the same name and configuration 
    Then I found the load balancer state also display `Not Ready` and have `Resource scheduled for deletion` message 
    
    ![image](https://github.com/harvester/harvester/assets/29251855/5c78c342-be6c-4176-b1a2-af6839525e76)


3. [Bug] Follow the step 2, when we have a  load balancer status in `Not Ready` already set on the VM. After we delete VM, it will stuck at `Terminating` state 

    ![image](https://github.com/harvester/harvester/assets/29251855/99fdcc95-aa00-4f8f-a42e-1b2ea6513afd)

4. [Enhancement] The IP address field of load balancer should display ip adress plus `port number`  
![image](https://github.com/harvester/harvester/assets/29251855/3d01e261-683f-4723-a0f0-d1591a32e6a3)

5. [Enhancement] We can add mechanism to prevent user to:
    - Let two lb use different ports bind to the same backend port 
      ![image](https://github.com/harvester/harvester/assets/29251855/4ba15fba-c007-4936-815a-76157c988bb4)

    - Let two lb use the same ports to different backend ports
      ![image](https://github.com/harvester/harvester/assets/29251855/02b53d38-e108-4233-8286-2fa9df4bf086)

   
    - Let two lb use the same ports to the same backend port 
      ![image](https://github.com/harvester/harvester/assets/29251855/997fac6c-7a57-4496-8caa-da04413f9295)

6. [Bug] Failed to clone load blanacer, stuck in `Not Ready` State 
  ![image](https://github.com/harvester/harvester/assets/29251855/0e7735d1-e7b1-42cd-84bc-3a265ba255e0)
  ![image](https://github.com/harvester/harvester/assets/29251855/939afe31-4ed0-4d96-ae64-e46b6b2d81bd)

7. [Bug] When we delete a `Not Read` load balancer, it would failed and dispay `Resource scheduled for deletion`. And we can't delete the VM too. 
  ![image](https://github.com/harvester/harvester/assets/29251855/13537c8f-3b99-48b3-b539-5c3bf4a47ac4)

8. **[Bug]** We need to pay attention to the situation: When there is any Load balancer in `Not Ready` state, we can't remove the existing load balancer nor deleting the related VMs

9. **[Bug]** When we edit the LB selector to another running VM: (e.g from nginx2 to nginx1), The load balancer did not actually transfer traffic to backend nginx2 server
      ![image](https://github.com/harvester/harvester/assets/29251855/6a94fe88-4236-4818-9e9a-56aec97581c8)

**Comment by TachunLin** [comment]
Move to implement for the next run rc2 testing

**Comment by TachunLin** [comment]
### Re-test failed issues on v1.2.0-rc2

1. - [x] **Fixed** [Bug] When we edit config of the existing load balancer, click `Edit as Yaml`, don't change anything then save directly. The state of load balancer become `Not Ready` 

2. - [x] **Fixed** Unable to delete a `Not ready`  load balancer
https://github.com/harvester/harvester/issues/3970#issuecomment-1614279844

3. - [x] **Fixed** [Bug] - Delete the not ready load balancer then create a new load balancer using the same name and configuration, the load balancer state also display `Not Ready` and have `Resource scheduled for deletion` message 
    
4. - [x] **Fixed** [Bug] When we have a  load balancer status in `Not Ready` already set on the VM. After we delete VM, it will stuck at `Terminating` state 

    ![image](https://github.com/harvester/harvester/assets/29251855/99fdcc95-aa00-4f8f-a42e-1b2ea6513afd)

5. - [x] **Fixed** [Enhancement] The IP address field of load balancer should display ip adress plus `port number`  
  ![image](https://github.com/harvester/harvester/assets/29251855/4d7cd820-d938-4b39-bb12-e60ef1e49779)


6. - [x] **Fixed** [Enhancement] We can add mechanism to **prevent** user to:

    - [x] Let two lb use different ports bind to the same backend port 
    ![image](https://github.com/harvester/harvester/assets/29251855/c33f8970-aca3-4ff3-a3e4-c152c87cb435)

    - [x]  Let two lb use the same ports to different backend ports
    ![image](https://github.com/harvester/harvester/assets/29251855/93613e4d-1da0-4788-a324-2c2bfd261bca)

    - [x] Let two lb use the same ports to the same backend port 
    ![image](https://github.com/harvester/harvester/assets/29251855/4991d9ac-b34c-4c18-9483-6ce65b35bdcb)


7. - [x] **Fixed** [Bug] Failed to clone load blanacer, stuck in `Not Ready` State 
  ![image](https://github.com/harvester/harvester/assets/29251855/e9780d97-bfd0-451f-9029-27a246dd7c1a)


8. - [x] **Fixed** [Bug] When we delete a `Not Read` load balancer, it would failed and dispay `Resource scheduled for deletion`. And we can't delete the VM too. 

9. - [x] **Fixed** [Bug] We need to pay attention to the situation: When there is any Load balancer in `Not Ready` state, we can't remove the existing load balancer nor deleting the related VMs

10. - [x] **Fixed** [Bug] When we edit the LB selector to another running VM: (e.g from nginx2 to nginx1), The load balancer did not actually transfer traffic to backend nginx2 server

    ![image](https://github.com/harvester/harvester/assets/29251855/4e3d16b1-2889-4e7a-be2d-79f536d26f72)

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2.0-rc2` and `v1.2-ef92b143-head` (06/29). Close this issue.

### Result
* Verified can **complete** all designed test plan scenarios: 
https://github.com/harvester/harvester/issues/1676#issuecomment-1569691582

* Verified all found issues and enhancement have been **fixed** in 
https://github.com/harvester/harvester/issues/1676#issuecomment-1614403099
* Verified the health check port can be created as stated in 
#4135

### Test Information
* Test Environment: 
  - 4 nodes Harvester bare machines
  - single nodes on local kvm machine
* Harvester version: `v1.2.0-rc2` and `v1.2-ef92b143-head` (06/29)
* Network: working external vlan network and vlan1

### Verify Steps
https://github.com/harvester/harvester/issues/1676#issuecomment-1569727330
https://github.com/harvester/harvester/issues/1676#issuecomment-1614403099
https://github.com/harvester/harvester/issues/4135#issue-1775468325
