### ISSUE TITLE
[FEATURE] Harvester NODE IP change notification enhancement

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#1683]
**Is your feature request related to a problem? Please describe.**

The NODE IP may change due to various reasons, e.g., #1682,  but there is no explicit check in starting stage.
 should check if node IP is changed when starting

In the WEB UI, add place to show Vritual MAC and VIP,  reminder the user to add VIP/VMAC binding to DHCP server when they choose DHCP mode.

**Describe the solution you'd like**

Due to the fact that the NODE IP is critical in K8S, consider:
 Save NODE IP in node, and check it in starting stage, if IP changed, warn or stop

The VIP also needs to be checked in booting/leader change, when it is different than saved, report error.

**Describe alternatives you've considered**

Highlight those in user documents about the setting of IP; VIP; DHCP etc.

**Additional context**

https://github.com/harvester/harvester/issues/1682

**Comment by guangbochen** [comment]
TODO: we may consider storing the node original IP and mac info to the Harvester CRD annotations e.g,`nodenetwork`. And when the current IP is changed we should add a proper error message to the web UI of the host page.

**Comment by tjjh89017** [comment]
If the node's ip is changed, cluster will treat that node as dead.
in rke2-server.service logs
It shows rke2 will start some program and attach the original IP.
Once IP is changed, rke2 will still try to connect to original IP and throw exception.
If we restart rke2-server or rke2-agent at that time. (or reboot it)
it will restart the service, attach to new IP and re-connect back to cluster.
Cluster will update node IP into "Node" and work as usual.

Even we add annotations for this, and it will not be useful for all because once node comes back, it will update node ip directly and remove old ip.
We should add some docs for best practice to highly recommend to set static dhcp server option for nodes.

Logs
[rke2-server.txt](https://github.com/harvester/harvester/files/7948243/rke2-server.txt)

cc @guangbochen

**Comment by tjjh89017** [comment]
Rke2 already stored IP info in Node annatations
- current ip: `rke2.io/internal-ip`
- init ip: `etcd.rke2.cattle.io/node-address`

Once IP was changed, node will fail to join etcd cluster and couldn't update IP info in Node CR.
Cluster will consider that node is dead.
If more than one node change, it will occur split brain.

**Comment by bk201** [comment]
We don't support changing VIP ATM because it's used in each node to join the cluster.

**Comment by WuJun2016** [comment]
Test step:

1. Create a harvester cluster to add 3 nodes, (two nodes will not show the ip change prompt)
2. Simulation of IP change

- Create `harvester-master` cluster, add `harvester-node1` and `harvester-node2` to the `harvester-master` cluster
- After waiting for 3 nodes to be ready, enter `harvester-node1`，run the following command
```
ip a flush dev harvester-mgmt
ip a add <new IP>/<CIDR> dev harvester-mgmt
# ip a add 192.168.0.123/24 dev harvester-mgmt
```
- go to `harvester-node2`, get the gw-ip,   `sudo ip r show default`
- go to `harvester-node1`,  run 
```
sudo ip r add default via <gw-ip>
sudo systemctl restart rke2-server
```
- Waiting for the node to restart


![image](https://user-images.githubusercontent.com/24985926/163532129-3b035b0b-ec0a-4d25-9576-316e88952204.png)

4. UI expects to display an alert message for ip change

<img width="1343" alt="image" src="https://user-images.githubusercontent.com/24985926/163748848-67431d0d-9770-4603-93fa-28e6c818a11d.png">

**Comment by lanfon72** [comment]
@WuJun2016, based on the test plan https://github.com/harvester/harvester/issues/1683#issuecomment-1099898121
The dashboard start freezing after `restart rke2-server`. (as the screen record below)
It could be recovered when I restart the Node which changed IP.  I think we should fix the freezing problem with the feature implementation.

https://user-images.githubusercontent.com/5169694/164032434-b2801bcf-d065-4a79-87ac-ea4273f27c58.mp4

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/164191008-baa55ddc-9ca3-46c2-a091-928b98b065af.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-b20a3b47-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow the test plan in https://github.com/harvester/harvester/issues/1683#issuecomment-1099898121
