### ISSUE TITLE
[BUG] When provisioning an RKE1 node drivercluster Harvester went down

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1684]
**Describe the bug**

When I was provisioning a RKE1 node driver cluster (1 node) my Harvester cluster lost network connectivity
**To Reproduce**
I'm not sure if this is reproducible. I'm looking into it
1. Provision RKE1 node driver cluster (1 node) on single node Harvester cluster. 
2. Wait for RKE1 node to go active

**Expected behavior**

Harvester networking shouldn't crash
**Support bundle**

[supportbundle_d3bbb44a-07f9-44ce-9d87-d31e6ef4ace6_2021-09-16T17-22-10Z.zip](https://github.com/harvester/harvester/files/7722516/supportbundle_d3bbb44a-07f9-44ce-9d87-d31e6ef4ace6_2021-09-16T17-22-10Z.zip)
**Environment:**
 - Harvester ISO version: master-3d096946-head
 - Rancher version: 2.6.3-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM virtual machine 16 cores 16GB RAM

**Additional context**
The RKE1 cluster went active then seemed to go down. When looking into it I realized that I couldn't ping or SSH into my harvester host. I rebooted the machine and it came back up fine. This was a RKE1 cluster with the Harvester cloud provider included. In the RKE1 node template I added this in the user data
```
#cloud-config
password: password
chpasswd: {expire: False}
```

**Comment by guangbochen** [comment]
@noahgildersleeve can u please re-check if this can still be reproduced with the latest master version, thanks.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-da3f1778-head` and Rancher `v2.6-3f9109c3f3a1ea482f66f7e3700e495d36517e10-head`.
## Verification steps
1. Import Harvester into Rancher
2. Provision RKE1 cluster in Harvester
3. Check if you still have connectivity with Harvester, Rancher, and RKE1
![Screenshot from 2022-03-07 16-18-51](https://user-images.githubusercontent.com/83787952/157140717-286412fd-c52a-49d7-a548-d77c42e43184.png)
![Screenshot from 2022-03-07 16-18-46](https://user-images.githubusercontent.com/83787952/157140718-d8469528-9703-449a-8faf-c27e56e567cd.png)
![Screenshot from 2022-03-07 16-20-46](https://user-images.githubusercontent.com/83787952/157140728-c176b086-8c08-4fe1-9510-5cef04c1d450.png)
