### ISSUE TITLE
[BUG] Backup's default value not work properly

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1687]
**Describe the bug**
1. Click `Use the default value` then click `Save`
![image](https://user-images.githubusercontent.com/5169694/146370610-9d7142b4-89a9-4405-8644-f4bc4c8c8456.png)
2. Select `Type: NFS` then click `Save` (Please notice that `Endpoint` is not marked required(`*`)
![image](https://user-images.githubusercontent.com/5169694/146370673-f10f014f-6ed1-4dbc-8306-6d336d773e48.png)
3. Select `Type: S3` then click `Save` (Please notice that there have many fields be marked as required(`*`)
![image](https://user-images.githubusercontent.com/5169694/146375953-15fdfbb0-b73b-4eaf-89c1-39253e06dc41.png)
3a. Able to `Save` without error
![image](https://user-images.githubusercontent.com/5169694/146370729-7ebf0526-4d43-4645-be70-bb4ca5bd4c55.png)

**Expected behavior**
`Use the default value` should purge the content of `backup-target` as the initial value `{}`

**Environment:**
 - Harvester ISO version: **master-3d096946-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

**Comment by w13915984028** [comment]
The commit 26deb4cdb2d  solved those faults.

The version you tested (not including 26deb4cdb2d)  still has such bugs 

![image](https://user-images.githubusercontent.com/31133476/146378262-afee83c7-f600-40a1-8c34-97d709a78ed5.png)

**Comment by lanfon72** [comment]
let me test on the version

**Comment by lanfon72** [comment]
Verified the bug has been fixed on **master-5e8d9764-head**
