### ISSUE TITLE
Keep showing exact error messages could better help address the root cause of errors on the volumes page 

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#169]
**Steps to reproduce:**
1. Create a volume with a size of 1 GiB, mount to an image
2. Check on its detail page

**Result:**
- [x] 1. An error message shows for few seconds and finally turns to a meaningless one
![image](https://user-images.githubusercontent.com/57614736/93863730-726b2400-fcf6-11ea-8a31-de3d70d6dc9f.png)
![image](https://user-images.githubusercontent.com/57614736/93864185-15bc3900-fcf7-11ea-8d87-e66b033a38f4.png)
- [ ] 2. The process in the list is N/A
![image](https://user-images.githubusercontent.com/57614736/93864735-e2c67500-fcf7-11ea-877e-f1628344983d.png)

**Suggestion:**
Maybe keep showing the exact error message that would better help users to address the root cause of errors

**Comment by WuJun2016** [comment]
case 2,  When the size is too small, the progress of volume will be in N / A.   @DoNotSayYes  @guangbochen

**Comment by guangbochen** [comment]
> case 2, When the size is too small, the progress of volume will be in N / A. @DoNotSayYes @guangbochen

what is the minimum size to make it show correctly, if this is an API issue, mark it as backend and will make an enhancement fix later.

**Comment by WuJun2016** [comment]
Case 1 has been fixed

**Comment by DoNotSayYes** [comment]
Nothing changed
