### ISSUE TITLE
[FEATURE] Optimization for the Harvester load balancer

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1697]
**Is your feature request related to a problem? Please describe.**

![image](https://user-images.githubusercontent.com/7421463/146503909-1027e033-7b36-47bd-8694-a5f6a3e5c090.png)
1. The modification of the IPAM configuration won't take effect. Users are not allowed to modify it.
2. The healthy check port should be a node port that is not user-friendly. We can add a dropbox to let users select one service port. The harvester cloud provider can get the node port corresponding with the service port.
3. Add the ipam box when adding the port during the progress of editing the workload.
![image](https://user-images.githubusercontent.com/7421463/150759479-c7b69d5c-c5f0-4b41-9c65-459a623a44b9.png)

**Describe the solution you'd like**

- Users are not allowed to modify IPAM configuration.
- To allow users to select the service port rather than filling in a node port.  The harvester cloud provider can get the node port corresponding with the service port.

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in Rancher da382a8 and Harvester master-1a861fc1-head. Validated that you could create LB with specified IPAM with steps

## Verification Steps

1. Install the latest rancher and import a Harvester cluster
2. Create a cluster by Harvester node driver
3. Navigate to the workload Page, create a workload
4. Click "Add ports", select type as LB, protocol as TCP
5. Check IPAM selector
6. Navigate to the service page, create a LB
7. Click "Add-on config" tab and check IPAM and port
![Screenshot from 2022-02-02 10-05-14](https://user-images.githubusercontent.com/83787952/152212105-2b2335be-b12b-42ac-bfcf-aa1d2aeb6fd3.png)
![Screenshot from 2022-02-02 10-05-07](https://user-images.githubusercontent.com/83787952/152212109-039a3e23-9eae-4ffc-9318-58f048a112c1.png)

**Comment by noahgildersleeve** [comment]
Closing as already verified 
> Tested in Rancher da382a8 and Harvester master-1a861fc1-head. Validated that you could create LB with specified IPAM with steps
> 
> ## Verification Steps
> 1. Install the latest rancher and import a Harvester cluster
> 2. Create a cluster by Harvester node driver
> 3. Navigate to the workload Page, create a workload
> 4. Click "Add ports", select type as LB, protocol as TCP
> 5. Check IPAM selector
> 6. Navigate to the service page, create a LB
> 7. Click "Add-on config" tab and check IPAM and port
>    ![Screenshot from 2022-02-02 10-05-14](https://user-images.githubusercontent.com/83787952/152212105-2b2335be-b12b-42ac-bfcf-aa1d2aeb6fd3.png)
>    ![Screenshot from 2022-02-02 10-05-07](https://user-images.githubusercontent.com/83787952/152212109-039a3e23-9eae-4ffc-9318-58f048a112c1.png)
