### ISSUE TITLE
[FEATURE] Add helper text to certain areas similar to what the Rancher dashboard UI offers today

### ISSUE THREAD

**Issue by davidnuzik** [harvester/harvester#1701]
**Is your feature request related to a problem? Please describe.**

No.

**Describe the solution you'd like**

It would be nice if the Harvester UI contained some helper text where necessary. For example, consider this helper text in the Rancher dashboard UI that provides additional context on node draining here on the cluster creation form:

It has a little `i` bubble to the right of the text/content and if you hover over it, helpertext is shown that provides additional useful info.
![image](https://user-images.githubusercontent.com/45179589/146569523-359e92ab-c055-4f52-bbc9-f831f0190a66.png)
![image](https://user-images.githubusercontent.com/45179589/146569574-fafa3633-c239-4f38-b8b0-1a346655718b.png)

I would like to propose that this or a similar method is provided in the Harvester UI. For example, the Enable USB Tablet option may not be clear to everyone. It isn't necessarily for if you are using a USB table on the client side, rather it can make mouse movement easier when leveraging the remote admin tool VNC.
It would be nice if for things like this that could be ambiguous we supply some helper text when necessary.
![image](https://user-images.githubusercontent.com/45179589/146573487-73750002-af74-43ac-9fe0-b9883530a2be.png)

**Describe alternatives you've considered**

Instead of having a little `i` bubble like Rancher Dashboard UI has, could just have helpertext on these UI elements. However, I think that not everyone knows that you can rest your mouse over UI elements to get helpertext. The `i` is more intuitive.

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-9d9778c6-head with external UI-index to verify the most recent dashboard changes. 
## Verification steps
1. Create a new VM
2. Navigate to advanced options
3. Mouse over Info icon on Enable 
![Screenshot from 2022-01-10 11-11-08](https://user-images.githubusercontent.com/83787952/148825171-3003334f-6abb-4817-99cf-e10a5fc798cf.png)
