### ISSUE TITLE
[BUG] Can not use Bridged Network in harvester 1.0.0-rc2

### ISSUE THREAD

**Issue by Yabbo** [harvester/harvester#1704]
**Describe the bug**
When creating a VM in harvester with the network set to Bridge it will create the VM with a masquerade network. any attempt to change it to bridge doesnt seam to do anything even though it looks like it saves the change.

**To Reproduce**
create a vm with bridge network 

**Expected behavior**
it should allow me to place the VM on my main network and not be an internal harvester network only.

**Environment:**
 - Harvester ISO version: 1.0.0-rc2
 - Underlying Infrastructure Baremetal with a 10G fiber nic

**Additional context**
I have even tried to delete the VM and recreate it to ensure i choose bridge when i built the VM with no luck.

**Comment by yaocw2020** [comment]
Harvester have not provide bridge network yet. Please take a look at the documentation.
https://docs.harvesterhci.io/v1.0/networking/harvester-network/

**Comment by Yabbo** [comment]
documentation of the networking needs to be reviewed and extended. I was able to create a VLAN on my switch and utalize my management network with a vlan ID to get an IP on my local LAN which is what i expected the bridge setting to do.. it only works when you use a vlan network.

**Comment by guangbochen** [comment]
Thank you for sharing your use case. The `management network` is an internal network that only forwards traffic and routing within the cluster. I think we should emphasize this part of the document more, thank you.
