### ISSUE TITLE
[BUG] Zero downtime upgrade stuck in "Waiting for VM live-migration or shutdown..."

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1707]
**Describe the bug**
As title, `hvst-upgrade` pod keeps waiting for VM live-migration or shutdown. VM pods are stuck in `Terminating` state, so `hvst-upgrade` pod can't go to the next step.

**To Reproduce**
1. Setup 1 node environment with harvester version 1.0.0-rc2.
2. Start a VM on it.
3. Run commands to apply a new version.
```
$ cat > versions.yaml <<EOF
apiVersion: harvesterhci.io/v1beta1
kind: Version
metadata:
  name: 1.0.2
  namespace: harvester-system
spec:
  isoChecksum: 2765d89e5e8024347c81d36cc84b7168bf358a3a2f4da0c63164ad834a94bcbbaa13af4900aad4caa0a27550e4b4db5bf2c4726daa88664378e0c581a79ad2cb
  isoURL: http://10.10.0.1/harvester/harvester.iso
  minUpgradableVersion: 0.3.0
  releaseDate: "20211231"
  tags:
  - dev
  - test
EOF
$ kubectl apply -f versions.yaml
```
4. Click upgrade on the dashboard.

**Expected behavior**
Zero downtime upgrade should be successful.

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by bk201** [comment]
The job is stuck because VMI on the host exists:
```
NAMESPACE          NAME                              AGE   PHASE       IP           NODENAME   READY
default            vm                                61m   Succeeded   10.52.0.80   node1      False
harvester-system   upgrade-repo-hvst-upgrade-62mbg   44m   Succeeded   10.52.0.82   node1      False
```

VM Pods are stuck at terminating.

**Comment by bk201** [comment]
The reason VM pods are stuck at Terminating is that the node enters NotReady for a short period of time. Turn out it's because RKE2 server is restarted when upgrading Rancher.
- Rancher is upgraded.
  - rancher-system-agent is upgraded and a new plan is executed
  - The new plan restarts rke2-server because `RESTART_STAMP` is different from the previous value.
- Then we shut down VM, but the VM pod will be stuck in terminating.

**Comment by bk201** [comment]
This issue should be fixed after bumping Longhorn to 1.2.4. The engines don't fail if a node goes into `NotReady` state for a short period. I'd suggest keeping monitoring this issue for a while since we can only test this by upgrading to the next release.

**Comment by TachunLin** [comment]
As per discussed, this issue could be verified in the upgrade path from `v1.0.1` to `v1.0.2`. We will check it at the next upgrade test for v1.0.2 release

**Comment by TachunLin** [comment]
Verified fixed during the upgrade from `v1.0.1` to `v1.0.2-rc1, we did not encounter such failure scenario.

### Result
Can upgrade correctly with all VMs remain in `running`
![image](https://user-images.githubusercontent.com/29251855/166430303-376d9e30-bf92-49eb-b3e2-8eeeb2375702.png)

![image](https://user-images.githubusercontent.com/29251855/166430680-bb9e14fe-7da5-4b73-9ec8-47a780b4914c.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: v1.0.1 to v1.0.2-rc1

### Verify Steps
1. Create a ubuntu image from URL
2. Enable Network with `management-mgmt`
3. Create a virtual network `vlan1` with id `1`
4. Setup backup target
5. Create a VM backup
6. Follow the guide to do upgrade test 
https://github.com/harvester/docs/blob/42598035cfe79856f7e159d4c47c4d7d29178900/docs/upgrade/automatic.md

  ![image](https://user-images.githubusercontent.com/29251855/166428121-391f5321-ec8e-46ce-9a96-ea92f04b3907.png)
  ![image](https://user-images.githubusercontent.com/29251855/166429966-b08cea0e-c457-41b2-a647-b6d3ac00aa58.png)

**Comment by TachunLin** [comment]
@guangbochen , @bk201 
Though we did not encounter the VM pods are stuck in `Terminating` during this upgrade test. 
But this probably because we not yet bumped longhorn and RKE2 version from v1.0.1 to v1.0.2 

Thus I would suggest to double check this issue on the next release (with bumped longhorn and RKE2) upgrade test and change the milestone accordingly.

**Comment by bk201** [comment]
Keep this in the icebox because we at least need v1.0.3-rc1 to test again.

**Comment by TachunLin** [comment]
After testing the upgrade from `v1.0.2` to `v1.0.3-rc1`, we did not encounter upgrade stuck for VM migration.
Close this issue. 

### Result
* Can upgrade correctly 
  ![image](https://user-images.githubusercontent.com/29251855/180775238-c1ee13f7-d117-4f26-aefa-369fefd3ce2b.png)
* All VMs are shutdown after upgrade
![image](https://user-images.githubusercontent.com/29251855/180775359-2b9fb6e2-f974-49d3-bfbf-6831898945f8.png)

* Can start all VMs correctly
![image](https://user-images.githubusercontent.com/29251855/180775898-1fe0fb5f-3ef0-453d-bf03-b19fb72eee62.png)


### Test Information
* Test Environment: 1 node on local kvm machine
* Harvester version: v1.0.2 to v1.0.3-rc1
