### ISSUE TITLE
[BUG] After click "Detach volume" button, nothing happend

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1708]
**Describe the bug**

After "Detach volume", nothing happend
![image](https://user-images.githubusercontent.com/15064560/146765349-1452573e-1d13-4671-8ae8-4f0d7c91ee64.png)

**To Reproduce**
1. create a vm "test"
2. create a volume "test" in the namespace
![image](https://user-images.githubusercontent.com/15064560/146765070-ab52a8f3-7a50-457f-a281-ada8381e175e.png)
3. add the volume to the vm
![image](https://user-images.githubusercontent.com/15064560/146765567-c9921a97-6271-4994-8a30-a613fb59732a.png)
4. click the "Detach volume" button 
![image](https://user-images.githubusercontent.com/15064560/146765200-e1dd74af-5ece-446b-9229-932015e8ef97.png)

**Expected behavior**

user can detach volume in the UI

**Support bundle**

**Environment:**
 - Harvester ISO version:  v1.0.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-b9613f90-head (12/11). Close this issue.

### Result
Currently when click the **Detach volume** button, attached volume can be detach successfully.  

![image](https://user-images.githubusercontent.com/29251855/146901702-9914241c-60fb-4fc9-a03a-4d72e979e20a.png)

![image](https://user-images.githubusercontent.com/29251855/146901739-7e8d0303-a753-4c02-bb33-fdf7188a65b0.png)

![image](https://user-images.githubusercontent.com/29251855/146901821-3bbc71a3-6f06-4d37-a0e2-53ee0a420f61.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-b9613f90-head

### Verify Steps

1. Create several new volume in volumes page
![image](https://user-images.githubusercontent.com/29251855/146900871-50fad5fa-2d25-4559-b10b-55e276d7edb8.png)
2. Create a virtual machine
3. Click the config button on the selected virtual machine 
4. Click Add volume and add at least two new volume 
![image](https://user-images.githubusercontent.com/29251855/146901117-dac73494-d8fd-4e1c-9a74-eed76fc14511.png)
5. Click the `Detach volume` button on the attached volume 
![image](https://user-images.githubusercontent.com/29251855/146901585-51df212b-5443-4961-b648-6db265c272c2.png)

![image](https://user-images.githubusercontent.com/29251855/146901235-6607a936-884b-41d9-94e2-372e8c028334.png)
6. Repeat above steps several times
