### ISSUE TITLE
[BUG] Missing volumes post-install

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1709]
**Describe the bug**
According to the Dashboard on newly installed Harvester 1.0.0-rc2 there are two volumes but when you click to see what they are none are listed.

**To Reproduce**
1. Install Harvester 1.0.0-rc2
2. Post-install set Admin password and log in to dashboard
3. Note the Volumes "bar" shows a count of 2
4. Click the Volumes "bar" (or in side-menu)
5. Note no volumes are listed

**Expected behavior**
If 2 volumes are already created then I expect to see them listed under Volumes, even if they are "greyed out" (i.e. you can't click on them). Otherwise the volume count is wrong.

**Support bundle**
[supportbundle_f57a0770-a430-46d9-8127-07d119e2f40a_2021-12-20T13-32-32Z.zip](https://github.com/harvester/harvester/files/7745633/supportbundle_f57a0770-a430-46d9-8127-07d119e2f40a_2021-12-20T13-32-32Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Intel NUC8i5BEH and Crucial P5 1TB NVMe SSD

**Additional context**
Two screenshots:
![Screenshot from 2021-12-20 13-26-08](https://user-images.githubusercontent.com/8300801/146775253-5ade479e-0d4f-40d4-828c-e1e28781fae9.png)
![Screenshot from 2021-12-20 13-26-16](https://user-images.githubusercontent.com/8300801/146775263-2e4aaa3b-3646-4fda-8541-6f6efdcded9e.png)

**Comment by guangbochen** [comment]
I think those are default system volumes e.g the one used by the built-in monitoring system, and we should skip counting those 2 volumes on the dashboard page.

**Comment by TachunLin** [comment]
Verified **fixed** on master-82c4225b-head. Close this issue.

### Result 
The default system volumes won't be counted on the dashboard page
![image](https://user-images.githubusercontent.com/29251855/148723426-aff65740-0aca-46c8-83d2-7109b328552b.png)

And also there is no default volume show up the volumes page
![image](https://user-images.githubusercontent.com/29251855/148723461-0035e0e5-e2c2-406f-b1b9-53332115c473.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machines
* Harvester version: master-82c4225b-head (22/01/10)

### Verify Steps

1. ISO install harvester
2. After setup complete and post-install 
3. Open Dashboard page
4. Check the volume count number
5. Open Volumes page
6. Check the volume page content
