### ISSUE TITLE
Even though a volume has been removed from a VM, it is still being attached to the VM on the volumes page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#171]
**Steps to reproduce:**
1. Create a volume, name it as Test-VM
2. Create/Edit a VM, add a disk from existing volume and choose Test-VM, then save it
2. Edit the same VM again, remove the disk that just added
4. Get to the volume page, check on the list

**Result:**
Even though the disk has been removed from the VM, can see Test-VM is still being attached to the VM on the volume page list 
![image](https://user-images.githubusercontent.com/57614736/93870511-e8c05400-fcff-11ea-8754-d122c25bca8b.png)
![image](https://user-images.githubusercontent.com/57614736/93867291-6afa4980-fcfb-11ea-98ea-0d602f8af046.png)

**Comment by guangbochen** [comment]
should be addressed in https://github.com/rancher/harvester-ui/pull/177

**Comment by DoNotSayYes** [comment]
Validated
