### ISSUE TITLE
[FEATURE] USB passthrough support

### ISSUE THREAD

**Issue by msnelling** [harvester/harvester#1710]
Will there be the option to pass through USB devices plugged into a Harvester node to a running VM? Example use-cases could be
* Security dongles
* Zigbee tranceivers
* HID
* External storage

**Comment by Yabbo** [comment]
would like to add the ability to boot from a local USB drive (users desktop not the server) when installing VMs into the harvester cluster.

**Comment by msnelling** [comment]
> would like to add the ability to boot from a local USB drive (users desktop not the server) when installing VMs into the harvester cluster.

This isn't really what I meant. I'm talking about passing through a USB device attached to the server running Harvester, similar to GPU/PCIe passthrough. Currently I'm using this functionality in ESXi

**Comment by FrankYang0529** [comment]
@msnelling Not sure whether this can solve your problem? Thank you.

https://github.com/kubevirt/kubevirt/pull/4089

**Comment by soderstrom-rikard** [comment]
> @msnelling Not sure whether this can solve your problem? Thank you.
> 
> [kubevirt/kubevirt#4089](https://github.com/kubevirt/kubevirt/pull/4089)

This looks very interesting and I assume that any client that wants to forward this will need to have the usbredirect package installed?

Sorry if I'm hijacking this issue slightly but I really want to highlight that this would help creating a cloud-native solution for developers in the embedded industry. So I'm very interested in trying this out with multiple local clients connecting external harvester nodes.

**Comment by tlehman** [comment]
If you have a USB Controller that is a PCI device, you can use PCI passthrough to get direct access to the USB device in a VM. Is there some usecase for USB passthrough that doesn't involve PCI?

If so, I can look into making a separate feature for this.

**Comment by tlehman** [comment]
@msnelling does PCI passthrough of a USB controller work?

**Comment by msnelling** [comment]
@tlehman in my particular use case I don't believe so. In the case of a single USB controller, this would limit USB to a single VM correct?

**Comment by tlehman** [comment]
That's right, each controller would be limited to a single VM. I'll look into USB passthrough without getting the PCI bus involved

**Comment by frodriguezp** [comment]
Is possible redirect the usb from Web Console? In our case we have Jubikey security devices to login in windows servers in Vmware, so the usb redirect must be work from Web VNC Console.

**Comment by hunghvu** [comment]
Intel 12-14th gen (consumer product line), as far as I know, has all USB ports under one controller. For example, mine is an Intel I7 13700k with a B660m Mortar Wifi DDR4 motherboard. Although the motherboard has multiple USB hub controllers, there is only one shown in `lspci`. I don't have the motherboard diagram so I'm not sure how they are connected physically.

```
00:14.0 USB controller: Intel Corporation Alder Lake-S PCH USB 3.2 Gen 2x2 XHCI Controller (rev 11)
00:14.2 RAM memory: Intel Corporation Alder Lake-S PCH Shared SRAM (rev 11)
00:14.3 Network controller: Intel Corporation Alder Lake-S PCH CNVi WiFi (rev 11)
```

![image](https://github.com/harvester/harvester/assets/62678592/e1550492-19e9-4642-9118-da9dc8ddb64d)

The USB controller can be passed through to the guest, but it affects all USB ports on the system. Meaning there is the host no longer has an HID.

I may need to look over Kubevirt documentation to see if they support USB passthrough (via YAML config).

It would be nice if Harvester supported this feature natively. Another hypervisor like Proxmox has this future built-in.

**Comment by frodriguezp** [comment]
> Will there be the option to pass through USB devices plugged into a Harvester node to a running VM? Example use-cases could be
> 
> * Security dongles
> * Zigbee tranceivers
> * HID
> * External storage

Yubikey usb connected to pc/mac , USB pass through from Web Console to pc/mac connected from.

**Comment by Yu-Jack** [comment]
> Yubikey usb connected to pc/mac , USB pass through from Web Console to pc/mac connected from.

Hi @frodriguezp, we'll focus on USB pass through from node instead of Web Console.

**Comment by Yu-Jack** [comment]
Summary overall tickets here.

Before implementation, need to check HEP and bump related dependency:

- https://github.com/harvester/harvester/issues/5430
- https://github.com/harvester/harvester/issues/5746
- https://github.com/harvester/harvester/issues/5166

Backend (harvester/pcidevices)

- https://github.com/harvester/harvester/issues/5762

Frontend (harvester/dashboard)

- https://github.com/harvester/harvester/issues/5763

**Comment by SlavikCA** [comment]
I see that `[v1.3.1-rc1]` release notes saying, that this issue is included in it:
> [FEATURE] USB passthrough support

However, I can't see it anywhere in UI.
Is it because UI is not enabled yet? Or is because I do not know where to look?

**Comment by Yu-Jack** [comment]
Currently, It's still on the Implement phase.

**Comment by irishgordo** [comment]
@Yu-Jack - I'm noticing a bit of an issue passing through multiple devices to the VM, it seems to always have the pod at "Unschedulable" 

[supportbundle_a47c6b11-180a-4b89-97aa-3bbff55004af_2024-10-15T22-04-54Z.zip](https://github.com/user-attachments/files/17386309/supportbundle_a47c6b11-180a-4b89-97aa-3bbff55004af_2024-10-15T22-04-54Z.zip)

**Comment by Yu-Jack** [comment]
> @Yu-Jack - I'm noticing a bit of an issue passing through multiple devices to the VM, it seems to always have the pod at "Unschedulable"
> 
> [supportbundle_a47c6b11-180a-4b89-97aa-3bbff55004af_2024-10-15T22-04-54Z.zip](https://github.com/user-attachments/files/17386309/supportbundle_a47c6b11-180a-4b89-97aa-3bbff55004af_2024-10-15T22-04-54Z.zip)

Hi @irishgordo ,  your VM has five USB devices.

![image](https://github.com/user-attachments/assets/dbe95c85-1869-4d8d-abdc-3572e390eee0)

But, there is no `046d-085c-005005` USB device. After removing it from VM spec, VM can start.

![image](https://github.com/user-attachments/assets/d5e64512-b2bd-4f76-af4b-b40e0de3a514)

That's why this VM can't be scheduled. I added a caution about this behavior in [Harvester Docs](https://docs.harvesterhci.io/v1.4/advanced/addons/pcidevices#usb-devices). Before removing the USB device, please remember to  detach and disable the USB device first. 

![image](https://github.com/user-attachments/assets/111f0f9a-9632-46a0-9245-b68075df1b9b)

I was thinking whether it's a good idea to help users to remove USB device in VM spec if this USB device is already removed. But if VM is running, it's not appropriate to remove USB device VM spec. In that case, we need to shutdown VM, which is not a good option. So, I added that caution to remind users.

BTW, restarting might result in the same case. As I know, it seems you restarted your node once, that's why it was from `005005` to `005002`. In this case, after node restarting, the VM spec is still `005005`. But, it's actually `005002`

**Comment by irishgordo** [comment]
@Yu-Jack thanks for investigating that and thanks for the doc edit :smile: :+1: 

Also, this in general looks good :smile: :+1:  - thanks for this new feature!

1. :green_circle: USB device can be attached and used by VM a variety (webcam, usb network adapters, usb storage, etc.)
2. :green_circle: Multiple USB devices can be attached and used by VM
3. :green_circle: Can not migrate VM to another node when using USB devices
4. :green_circle: USB devices can be removed from a VM and used on another VM
5. :green_circle: USB devices get cleaned up when not present on physical nodes
6. :green_circle: Can restore a VM with USB devices (snapshot & backup)
7. :green_circle: Can clone a powered off VM with USB devices
8. :green_circle: Can have multiple of same USB products used in VM (same vendor/product-model)
9. :green_circle: USB device enabling works with both: integrated-usb-controller-hub and PCIe/PCI USB Controller Card(s) on node -> all USB devices are shown available from all available sources 
10. :green_circle: USB devices can move locations on Node(s) and still be accessible 
11. :green_circle: If USB Devices being used by VM from USB PCI Controller, the PCI USB Controller can not be enabled, from PCI Devices

Harvester v1.4.0-rc2
2 Node Cluster (1 Dell PowerEdge R720, 1 HP DL 160 Gen9)

USB Integrated & PCI Controller:
```bash
rancher@test-r720-v140rc2:~> sudo lspci | grep -ie "USB"
00:1a.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #2 (rev 05)
00:1d.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #1 (rev 05)
06:00.0 USB controller: ASMedia Technology Inc. ASM2142/ASM3142 USB 3.1 Host Controller
0b:00.0 USB controller: ASMedia Technology Inc. ASM2142/ASM3142 USB 3.1 Host Controller
```

Supporting Screengrabs:

![Screenshot from 2024-10-16 10-58-06](https://github.com/user-attachments/assets/fda3d868-3514-4281-8c9f-d20a71e443bb)

![Screenshot from 2024-10-16 10-55-43](https://github.com/user-attachments/assets/c3a66789-f014-4558-b2ed-47ab277532dc)

![Screenshot from 2024-10-16 10-04-22](https://github.com/user-attachments/assets/ee311f32-7f1a-4626-a960-5bd7c647faf7)

![Screenshot from 2024-10-15 13-59-14](https://github.com/user-attachments/assets/4b4441a0-aa22-4f9f-b963-48866eee982a)

![Screenshot from 2024-10-15 13-58-42](https://github.com/user-attachments/assets/e56bb0d0-545a-41e7-85cf-c83463bf9920)

![Screenshot from 2024-10-15 13-57-57](https://github.com/user-attachments/assets/c3171390-2ae6-4332-a2de-109650367fb0)

![Screenshot from 2024-10-15 13-57-11](https://github.com/user-attachments/assets/17f53302-8d70-4b58-929d-8da9d5a92a85)



I'll go ahead and close this out :smile: :+1: 


I'll leave open the additional issues found w/ USB testing to track:
- #6790 
- #6805 
- #6806 
- #6809 
- #6779
