### ISSUE TITLE
[BUG] When creating a new template from an existing template, the  volume size should be editable

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1711]
**Describe the bug**

![image](https://user-images.githubusercontent.com/24985926/146780842-963bdf1a-129e-45f1-be25-253cf515ad94.png)

**To Reproduce**
1.  Create a vm template
![image](https://user-images.githubusercontent.com/24985926/146781221-3831053a-1c9e-485e-a05c-7178ab498f72.png)
2. Click on the action menu of the template (Modify template)
3. Click volume tab  (image and size should be editable)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version:  v1.0.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-0345caa9-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any Nodes
2. Login to Dashboard
2. Create Image for Template Creation
3. Create Template `T1` with _Image Volume_ and additional _Volume_
4. Modify Template `T1` with update _Volume_ size
5. Volume size should be editable
6. Click Save, then edit new version of `T1`
7. Volume size should be updated as expected
