### ISSUE TITLE
[BUG] Harvester "Hosts" MEMORY shows incorrect data

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#1712]
**Describe the bug**

Harvester "Hosts" MEMORY shows incorrect data
![image](https://user-images.githubusercontent.com/31133476/146785050-b16421ce-47e7-4acf-b6e2-20501535ac37.png)

**To Reproduce**
1. A fresh Harvester v1.0.0 rc2 installation with 2 nodes, the second node uses around 848 MiB memory, on the WEB UI, it shows `848 of 16 GiB`

**Expected behavior**

Memory should be converted to unified format, e.g. `0.848 of 16 GiB`.
Meanwhile, the first node, shows` 2.91 of 16 GiB`

**Support bundle**

no

**Environment:**
 - Harvester ISO version: v1.0.0 rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): PROVO DAY0, SUSE SLE15 SP2, KVM

**Additional context**

**Comment by futuretea** [comment]
"MEMORY" should be "Memory"

**Comment by w13915984028** [comment]
Harvester metrics:

main node:
![image](https://user-images.githubusercontent.com/31133476/146797187-f2f06b00-7fa5-4671-9b0c-a553bd0fc944.png)

node2:
![image](https://user-images.githubusercontent.com/31133476/146797504-b878a34d-b098-405c-a527-9ce8610d85ef.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/150968160-df93b19a-142a-43fc-88c8-aefca480ff89.png)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-a67f96d0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Login to Harvester and Navigate to **Hosts**
3. Node's **Memory** should display correct as the calculation
    - the format: `Reserved a of b GiB / c %`
    - the calculation: c% ~= a / b * 100%
