### ISSUE TITLE
[BUG] The volume size  in backup is displayed incorrectly

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1713]
**Describe the bug**

**To Reproduce**
1. create a vm with 10Gi rootdisk
![image](https://user-images.githubusercontent.com/15064560/146786337-e9501e33-8f07-4632-8a24-ecfed51eeea2.png)

2. take backup

UI display backup volume is 50Gi not 10Gi, but only 10Gi in the backup yaml
![image](https://user-images.githubusercontent.com/15064560/146786844-a2aafaec-cb25-4c89-9566-f48ca2e3c46e.png)

**Expected behavior**

UI display backup volume size should display correctly

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-82c4225b-head. Close this issue.

### Result
The volume size in backup now is identical with virtual machine volume setting
![image](https://user-images.githubusercontent.com/29251855/148718073-6d24027c-955c-4501-a28a-32f36b98ca70.png)

![image](https://user-images.githubusercontent.com/29251855/148721589-f95f1347-622b-4351-b11f-c17ad200443a.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machines
* Harvester version: master-82c4225b-head (22/01/10)

### Verify Steps

1. Create an image
2. Create a virtual machine with 10GB volume size
3. Set backup target in settings
4. Take backup from the virtual machine
5. Check the volume size in backup when the process complete
