### ISSUE TITLE
task: Remove the `Upgrade` button in the setting

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1719]
Due to https://github.com/harvester/harvester/issues/1717 , we want to make sure the user doesn't have direct access to the upgrade path until we've completed the validation. So we want to remove the following button.
![settings](https://user-images.githubusercontent.com/3344618/146807017-4bcecdc0-b79c-43a8-8db8-7cb6c8ba2a79.png)

Since the automatic upgrade is controlled by the upgrade responder, that button won't show up until we upgrade the upgrade responder, so that would be fine.

Notice the URL is still available and it can be used for QA purpose.

**Comment by yasker** [comment]
cc @bk201

**Comment by TachunLin** [comment]
Verified **fixed** on master-0345caa9-head (12/21).Close this issue.

### Result
`Upgrade` button has been removed by default havester setting 
Currently in settings page, click the config button on server-version only display `No actions available`  

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-0345caa9-head 


### Verify Steps

1. Open harvester setting page
2. Click the config button on server-version
