### ISSUE TITLE
[BUG] 'auto-disk-provision-paths' not available on the setting page UI

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#1721]
**Describe the bug**
The setting `auto-disk-provision-paths` is not appearing on v1.0.0-rc2

**To Reproduce**
1. Create a Harvester cluster
2. Go to setting page, the setting `auto-disk-provision-paths` is not available.

**Expected behavior**
The setting `auto-disk-provision-paths` should be available.

**Environment:**
 - Harvester ISO version: v1.0.0-rc2

**Comment by yasker** [comment]
@guangbochen is it intended? the setting is available in the `harvester-system` namespace.

**Comment by guangbochen** [comment]
it has not been added to the setting page, but will be addressed by https://github.com/harvester/dashboard/pull/210

**Comment by yasker** [comment]
@guangbochen @WuJun2016 please hold the merge for this. We don't know if we can fix this or can test it well enough. It's better to probably keep it hidden for the time being until v1.0.1

**Comment by guangbochen** [comment]
sure, the `auto-disk-provision-paths` setting actually has already been verified on https://github.com/harvester/harvester/issues/1241, it may encounter cases like https://github.com/harvester/harvester/issues/1718, but would be good if users can modify this setting since they can already config it during the installation.

**Comment by lanfon72** [comment]
Verified the Option is available on UI's setting page.
![image](https://user-images.githubusercontent.com/5169694/148912658-2b5ab1ff-ed18-43eb-a298-1f244c7ea1e3.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-177ab565-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard, then navigate to _Advanced Settings_
3. Option `auto-disk-provision-paths` should be available in the list
