### ISSUE TITLE
[Enhancement] Data sync is required before taking backup of a VM

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#1723]
**Describe the bug**
Data sync should happen before taking backup of a vm. Sometimes the data of backup miss content from vm because the data is still in buffer and haven't written on the disk. 

**To Reproduce**
1. Create a vm.
2. Write multiple files in a loop.
3. Take backup
4. Restore the backup, verify not all the content of the files which are written in the last are there in the restored data.

**Expected behavior**
Sync should be done before taking the backup so that all the data can be backed up.

**Environment:**
 - Harvester ISO version:  v1.0.0-rc2

**Comment by futuretea** [comment]
link to https://github.com/harvester/harvester/issues/2279

**Comment by rodrigo14miguel** [comment]
This might need volume snapshot #553 #2294. Backup solutions normally use snapshots for either k8s or hypervisors.

**Comment by albinsun** [comment]
Can reproduce in `v1.1.2` with following steps. Will verify fix in `v1.2.0-rc2+`.

## Verification Steps
1. Create a VM.
2. Open console and create 100 txt files using loop.
4. Take backup
5. Restore backup (Replace Existing)
6. Files created in step 2 should still exist. :x:

[repro-112-render1.webm](https://github.com/harvester/harvester/assets/2773781/9e623b36-6d41-441a-840e-178570828996)

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc2`, verified as fixed.

## Test Environment
* Harvester
  * version: `v1.2.0-rc2`
  * profile: KVM, single node
  * **ui-source**: Auto

## Verification Steps
### Scenario: Replace Existing
1. Create a VM.
2. Open console and create 100 txt files using loop.
3. Take backup
4. Restore backup (Replace Existing)
5. Files created in step 2 should still exist. :heavy_check_mark:
### Scenario: Restore New
1. Create a VM.
2. Open console and create 100 txt files using loop.
3. Take backup
4. Restore backup (Restore New)
5. Files created in step 2 should still exist. :heavy_check_mark:

[repro-120rc2-render.webm](https://github.com/harvester/harvester/assets/2773781/db52020e-de7b-4631-aae2-778b81abe4c2)
