### ISSUE TITLE
[BUG] Remove server-url setting in the UI

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1724]
It is not in use.

**Environment:**
 - Harvester ISO version: v1.0.0-rc2

**Comment by TachunLin** [comment]
Verified **fixed** on master-82c4225b-head. Close this issue.

### Result 
The `server-url` content have been removed from settings  
* **latest master head** settings
![image](https://user-images.githubusercontent.com/29251855/148722582-4e80b18d-be3a-4ba3-8735-e6406c43523e.png)

* **v1.0.0** settings
![image](https://user-images.githubusercontent.com/29251855/148722626-43288792-a3ce-4ea2-b2f3-1d3ff8890c59.png)


### Test Information
* Test Environment: 1 nodes harvester on local kvm machines
* Harvester version: master-82c4225b-head (22/01/10)

### Verify Steps

1. Open settings
2. Check the `server-url` setting exists
