### ISSUE TITLE
[BUG] Move support bundle image version out of the backend code

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1727]
**Describe the bug**
Support bundle kit image is coded as the default value of a setting in the backend. https://github.com/bk201/harvester/blob/d52cb934ed7bc2c1a22d693b6d56709e18b1d190/pkg/settings/settings.go#L29
This makes harvester-installer hard to automate the image pulling process. (Currently, it's a hard-coded value: https://github.com/harvester/harvester-installer/blob/3af28b4701bc5cd05f9ec3e8ac1b0111cf36de39/scripts/build-bundle#L108

We need to move the image value out of the code.
A proposal is to move to the chart values file.

**Comment by FrankYang0529** [comment]
Proposal:
1. Add support bundle image value to `harvester/deploy/charts/harvester/values.yaml` and remove `support-bundle-image` in Settings.
2. Get ManagedChart `fleet-local/harvester`. If there is support bundle image value, it means users replace the default helm chart value, so we use it to create support bundle Deployment.
3. If there is not, we get Apps `harvester-system/harvester` to get the default support bundle image value.

**Comment by FrankYang0529** [comment]
### Test plan

1. Check the controller can get support bundle image version from App.

* Set following yaml in `spec.chart.values` of `harvester-system/harvester` app:
```
support-bundle-kit:
  image:
    imagePullPolicy: Always
    repository: rancher/support-bundle-kit
    tag: v0.0.4
```
* Create a support bundle.
* Check image pull policy is `Always`, repository is `rancher/support-bundle-kit`, and tag is `v0.0.4` in support bundle pod.
* Check default value of `support-bundle-image` setting is `{"repository":"rancher/support-bundle-kit","tag":"v0.0.4","imagePullPolicy":"Always"}`.

2. Check the controller can merge support bundle image value in App and ManagedChart.

* Following above case, set following yaml in `spec.values` of `fleet-local/harvester` managed chart:
```
support-bundle-kit:
  image:
    imagePullPolicy: IfNotPresent
```
* Create a support bundle.
* Check image pull policy in support bundle pod is `IfNotPresent`.
* Check default value of `support-bundle-image` setting is `{"repository":"rancher/support-bundle-kit","tag":"v0.0.4","imagePullPolicy":"IfNotPresent"}`.

3. Check value from users can override the default value in `support-bundle-image` setting

* Set value in `support-bundle-image` setting as `{"repository":"rancher/support-bundle-kit","tag":"v0.0.5","imagePullPolicy":"IfNotPresent"}`.
* Create a support bundle.
* Check image tag is `v0.0.5` in support bundle pod.

4. Check `support-bundle-image` webhook can work
* Empty value should pass.
* Non-JSON value should fail.
* Value with any blank field (repository, tag, or imagePullPolicy) should fail.
* Valid value like `'{"repository": "rancher/support-bundle-kit","tag":"v0.0.5","imagePullPolicy":"IfNotPresent"}'` should pass.

**Comment by TachunLin** [comment]
@FrankYang0529, @guangbochen 
Regarding to above test plan 3 and 4, I checked the latest master head version it seems can't find `support-bundle-image` in harvester  settings. Whether there is UI related PR need to be merged for this issue.

**Comment by noahgildersleeve** [comment]
Tested in master-1a861fc1-head. Followed previously outlined test steps 

> ### Test plan
> 1. Check the controller can get support bundle image version from App.
> 
> * Set following yaml in `spec.chart.values` of `harvester-system/harvester` app:
> 
> ```
> support-bundle-kit:
>   image:
>     imagePullPolicy: Always
>     repository: rancher/support-bundle-kit
>     tag: v0.0.4
> ```
> 
> * Create a support bundle.
> * Check image pull policy is `Always`, repository is `rancher/support-bundle-kit`, and tag is `v0.0.4` in support bundle pod.
> * Check default value of `support-bundle-image` setting is `{"repository":"rancher/support-bundle-kit","tag":"v0.0.4","imagePullPolicy":"Always"}`.
> 
> 2. Check the controller can merge support bundle image value in App and ManagedChart.
> 
> * Following above case, set following yaml in `spec.values` of `fleet-local/harvester` managed chart:
> 
> ```
> support-bundle-kit:
>   image:
>     imagePullPolicy: IfNotPresent
> ```
> 
> * Create a support bundle.
> * Check image pull policy in support bundle pod is `IfNotPresent`.
> * Check default value of `support-bundle-image` setting is `{"repository":"rancher/support-bundle-kit","tag":"v0.0.4","imagePullPolicy":"IfNotPresent"}`.
> 
> 3. Check value from users can override the default value in `support-bundle-image` setting
> 
> * Set value in `support-bundle-image` setting as `{"repository":"rancher/support-bundle-kit","tag":"v0.0.5","imagePullPolicy":"IfNotPresent"}`.
> * Create a support bundle.
> * Check image tag is `v0.0.5` in support bundle pod.
> 
> 4. Check `support-bundle-image` webhook can work
> 
> * Empty value should pass.
> * Non-JSON value should fail.
> * Value with any blank field (repository, tag, or imagePullPolicy) should fail.
> * Valid value like `'{"repository": "rancher/support-bundle-kit","tag":"v0.0.5","imagePullPolicy":"IfNotPresent"}'` should pass.

I used the advanced settings page in Harvester rather than manually editing the charts. I also verified in the YAML of the pods via embedded Rancher on the Harvester node. This was on a 1 node Harvester setup in KVM.
