### ISSUE TITLE
[BUG] When the cluster storage is large (eg: 100TiB), but the usage is small (eg: 100Mib), the progress bar is not displayed.

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1729]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/16abe1e5-55dc-445a-bed7-c7ece6f1f431)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/7b1c7a1c-c4ea-45ad-9586-d1cfb6cd1616)
**To Reproduce**
1.   Create a cluster with larger storage
2.  Go to the dashboard page
3.  Check the percentage of Storage usage

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-a67f96d0-head (1/28). Close this issue.

### Result
The storage usage display correctly on dashboard even with harvester installed on large storage machine.
![image](https://user-images.githubusercontent.com/29251855/151535253-8f505b0a-49b6-4e85-b6f3-3910d89ddbff.png)


### Test Information
* Test Environment: 1 nodes harvester on local kvm machine
* Harvester version: master-a67f96d0-head (1/28)

### Verify Steps
1. Prepare a kvm virtual machine with 4TiB storage
2. Install harvester on the 4TiB storage
  ![image](https://user-images.githubusercontent.com/29251855/151532230-780bcc96-f1ef-43da-adbf-10c89df6e2dd.png)
3. Wait for installation complete
4. Access harvester dashboard
5. Check storage status


### Additional Context
* v1.0 GA status
![image](https://user-images.githubusercontent.com/29251855/151530540-6966e049-eb3e-4b7d-a745-579a273c6fdd.png)
