### ISSUE TITLE
Users are allowed to create a volume whose disk size could exceed the total disk size of the machine

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#173]
**Steps to reproduce:**
1. Create a volume filling size 1000000000 GiB whose disk size could exceed the total disk size of the machine
2. Check the volume state on the list

**Result:**
The volume can be created with no any errors but only in N/A state
![image](https://user-images.githubusercontent.com/57614736/93989198-313d4780-fdbc-11ea-8405-a05f9f3ea9d4.png)
![image](https://user-images.githubusercontent.com/57614736/93990886-3e5b3600-fdbe-11ea-85d5-330613947a42.png)

**Comment by guangbochen** [comment]
as long as there is a proper error message when the user clicks to view the detail page, this is enough for now. cc @WuJun2016

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1400
