### ISSUE TITLE
[BUG] Uploading images from files seemed to time out and now can't upload files

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1736]
**Describe the bug**
Uploading two image files from locally mounted NAS folder seemed to timeout with no error. Deleting then retrying displays a network error. Dashboard and other pages are still responding.

The two images files are for SLES15 SP3 JeOS which are not available publicly (hence downloading then trying to upload them).

simon@linux:~> ls -lah /mnt/data/ISOs/SUSE-Linux-Enterprise-15-SP3/*.qcow2
-rwxr-xr-x 1 simon root 239M Oct  9 15:03 /mnt/data/ISOs/SUSE-Linux-Enterprise-15-SP3/SLES15-SP3-JeOS.x86_64-15.3-kvm-and-xen-GM.qcow2
-rwxr-xr-x 1 simon root 224M Oct  9 15:03 /mnt/data/ISOs/SUSE-Linux-Enterprise-15-SP3/SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2

I started the OpenStack one first, saw the message about not closing or moving from screen and then uploaded the KVM/Xen one. One seemed to stick at 49%, the other at 6%. Perhaps I should only be doing one at a time but it didn't stop me (and now it won't let me  retry).

**To Reproduce**
1. Go to Images tab
2. Click Create button
3. Upload image file from a local file
4. Wait a bit
5. Upload second image file from a local file
6. Wait a bit
7. Observe both get stuck
8. Delete both
9. Try repeating - will see red Network Error (and Create button changes to red Error button)

**Expected behavior**
If I am supposed to be able to upload two files at the same time then it should work. Otherwise it should stop/warn me from doing second one until first has finished.

**Support bundle**
See #1731 I created yesterday.

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure: Baremetal with 2x Intel NUC7i7DNxE

**Additional context**
None

**Comment by simonflood** [comment]
Trying to upload these local files via Python HTTP server shows that file upload is now broken for files and URLs.

**Comment by simonflood** [comment]
Hmm just tried logging out which showed the "Logging out..." message but didn't seem to be as I then reloaded main Harvester page where it prompted re certificate. After that I was still logged in and could then successfully upload from file. My suspicion is that the web session timed out during first file upload(s) but nothing changed on screen.

BTW I'm using Firefox 91.3.0 ESR on openSUSE Leap 15.3.

**Comment by simonflood** [comment]
My immediate second upload from file has got stuck at 2% after 49 mins - I left it whilst I had lunch. I've refreshed the page (yes I know it said not to) and time has increased to 50 mins. I've now deleted it and retried - after 38 secs I got a red Failed with Context cancelled.

**Comment by simonflood** [comment]
After going to Dashboard then back to Images page I could then retry and this time it completed. There's definitely something odd going on somewhere.

**Comment by simonflood** [comment]
Uploading images seems to be very hit and miss (mostly the latter) whether directly from Internet (Debian and Fedora cloud images are latest problematic ones), downloaded locally then uploaded as files, or downloaded locally then served via Python HTTP Server module (python3 -m http.server).

I find things work a bit better if I refresh the page and/or navigate to other pages before returning to Images page and retrying.

**Comment by w13915984028** [comment]
Issue was solved in v1.0.0 and later. Thanks.
