### ISSUE TITLE
Users are allowed to create a VM whose CPU/Memory could exceed the total CPU/Memory of the machine

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#174]
**Steps to reproduce:**
1. Create a VM filling 10000 cores CPU and 10000 GiB Memory whose CPU/Memory could exceed the total CPU/Memory of the machine
2. Check on the VM list page and detail page 

**Result:**
- [ ] 1. Users are allowed to create a VM whose CPU/Memory could exceed the total CPU/Memory of the machine, and no explicit error messages are provided
- [x] 2. The LAUNCHER_POD_ERROR state could overlap the VM name in the list
![image](https://user-images.githubusercontent.com/57614736/93994233-4026f880-fdc2-11ea-8990-64dee416c9ea.png)
![image](https://user-images.githubusercontent.com/57614736/93995584-c728a080-fdc3-11ea-95da-c79bc30b431f.png)

**Comment by WuJun2016** [comment]
case 1 fix in next version

**Comment by DoNotSayYes** [comment]
Validated case 2, by the way, it's better to apply this change to the other pages because it could happen on any one. @WuJun2016 
![image](https://user-images.githubusercontent.com/57614736/94360242-817b1900-00de-11eb-9696-3c7745b104ac.png)

I'd remove the `to-test` tag in order to keep tracking case 1

**Comment by guangbochen** [comment]
for case 1, can we update the `LAUNCHER_POD_ERROR` to `LAUNCHER_ERROR` and explicit error messages should be available when describing the events? cc @WuJun2016

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/1242
