### ISSUE TITLE
[BUG] Installing failed when some disks using SCSI

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#1745]
### Describe the bug
Harvester unable to be installed when the machine have any disk using `SCSI`, otherwise installer will entering `Dracut Emergency Shell`.

This issue discovered by https://github.com/harvester/harvester/issues/1718#issuecomment-1000710949

### To Reproduce
1. Install Harvester with any disks using SCSI protocol
2. Installer will take several minutes after `Attached SCSI disk`
3. Installer will showing `dracut-initqueue timeout  - starting timeout scripts`
4. Installer will entering `Dracut Emergency Shell`

### Expected behavior
Despite SAS(Serial Attached SCSI) has been replaced with SATA and PCI-E (NVMe), but `SCSI` protocol still using on several environment(iSCSI, UAS...etc), so we will need to fix this bug to provide variety storage connectivity options.

### Additional Content
**take several minutes to process after `Attached SCSI disk`**
![image](https://user-images.githubusercontent.com/5169694/147331021-0a41f26c-6434-4e64-b029-07af509dcf78.png)

**then entering `Dracut Emergency Shell`** (the **sdb** disk is `uas` bus)
![image](https://user-images.githubusercontent.com/5169694/147331300-61c1e53a-efa1-4e13-8c44-18ce4c62f0b0.png)

**Comment by lanfon72** [comment]
To reproduce this based on https://github.com/harvester/ipxe-examples using vagrant, you can just update following snippets in `Vagrantfile`:
```ruby
        libvirt.storage :file,
          size: @settings['harvester_network_config']['cluster'][node_number].key?('disk_size') ? @settings['harvester_network_config']['cluster'][node_number]['disk_size'] : @settings['harvester_node_config']['disk_size'],
          type: 'qcow2',
          bus: 'virtio',
          device: 'vda'
        # new added SCSI additional disk
        libvirt.storage :file,
          size: '20G',
          type: 'qcow2',
          bus: 'scsi',
          device: 'sda',

``

**Comment by bk201** [comment]
@lanfon72  Is this reproduced in KVM VM only or also on real hardware?

A typo?
```
          bus: 'scci',

```

**Comment by lanfon72** [comment]
yes :joy_cat: , let me update it
It should also on real hardware, as I tried it happen on `UAS` too (which was additional disk pass through)

**Comment by kajla** [comment]
Hello, 
Any news?

**Comment by bk201** [comment]
@lanfon72 When adding a SCSI disk to Vagrant VMs, a new bus is added. Thus network interface names are also changed. (The two interfaces are changed from `[ens5, ens6]` to `[ens6, ens7]`.

When performing iPXE installation, we append kernel parameter `ip=ens5:dhcp` to specify the boot interface. This parameter and some settings need to be adjusted accordingly. You can check my [commit](https://github.com/bk201/ipxe-examples/commit/e8683d917e7ab531a91008fccbd05026e151f04a) for a working sample.

**Comment by bk201** [comment]
@kajla Did you see a similar issue in real hardware? Feel free to share more details. Thanks.

**Comment by kajla** [comment]
@bk201 No, I didn't, just interested.
We plan to install Harvester on HP c7000 Bladesystem (15xHP BL460c blade) with HP MSA2040 storage. SAN is attached to blades by SCSI. We thought we will allocating disks for VMs from a SCSI LUN.
Each blade has small SD card, witch we plan to upgrade to SSD for Harvester OS.
We plan to buy a Harvester license for support.

**Comment by lanfon72** [comment]
Tested this bug can be resolved when update NIC interface name.
(ref: https://github.com/harvester/harvester/issues/1745#issuecomment-1031196059)

- [x] bus SCSI
- [x] attached SCSI
