### ISSUE TITLE
[FEATURE]The IP addresses of multiple NETWORK interface cards (nics) of the VM are displayed

### ISSUE THREAD

**Issue by zhilong-rancher** [harvester/harvester#1746]
**Is your feature request related to a problem? Please describe.**
After a VM is created, multiple nics are configured, but only the IP address of the first NIC is displayed on the page. 

**Describe the solution you'd like**
If a VM is configured with multiple nics, the IP addresses of the first two nics should be displayed on the page.

**Comment by WuJun2016** [comment]
After discussion, the UI will show all ipv4 addresses


![image](https://user-images.githubusercontent.com/24985926/149878311-4e391d41-e1ad-4296-8fe0-694150946f74.png)

**Comment by lanfon72** [comment]
Verified this feature has been implemented as expected.

![image](https://user-images.githubusercontent.com/5169694/150086532-a973ba28-9a04-431b-a376-e8b26c34dd9a.png)

Test Information
----
* Environment: **Bare metal DL360 3 nodes**
* Harvester Version: **v1.0.0-rc2**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with any Nodes (node required 2 ports)
2. Create Image for VM Creation
3. Create VM with 2 NICs, then start VM
4. VM should start successfully
5. List of VMs should display all IPv4 IPs from the VM
