### ISSUE TITLE
[BUG] Add volume not mounted to vm

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#1747]
**Describe the bug**
Use vm's Add volume function to see that the volume is not eventually mounted on vm
![image](https://user-images.githubusercontent.com/15829074/147351444-2b88dd78-ae47-4e45-86e0-8f7ce2c5fdd5.png)

**To Reproduce**
1. create a vm with the name ltang
2. create a volume named ltang-test
3. Add the volume ltang-test to the virtual machine ltang through the Add volume function of ltang
4. Connect to the virtual machine ltang and use the `fdisk -l` command to view the volume mount，there is no mounted volume
![image](https://user-images.githubusercontent.com/15829074/147351741-e96aecd1-0db2-4e73-9534-e7b4c2145d2e.png)
![image](https://user-images.githubusercontent.com/15829074/147351777-1c709e7f-cb15-4c36-8035-97b80f5b6698.png)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
@TangStone  the added volume was mounted as "/dev/sda"

```bash
{"component":"virt-launcher","kind":"","level":"info","msg":"Attaching disk hot1, target sda","name":"test1","namespace":"default","pos":"manager.go:868","timestamp":"2021-12-27T02:36:48.997696Z","uid":"12daffe5-faf5-4ef3-a738-f68626dbc18c"}
```

**Comment by TangStone** [comment]
@futuretea  I made a mistake in observation
