### ISSUE TITLE
[FEATURE]Install qemu-guest-Agent in an offline environment

### ISSUE THREAD

**Issue by zhilong-rancher** [harvester/harvester#1749]
**Is your feature request related to a problem? Please describe.**

During VM installation, qemu-guest-agent can be installed on the operating system (OS) by configured in user data. However, the installation can be successful only when the OS is connected to the Internet, because the software package may not exist in the OS image.

**Describe the solution you'd like**

Put the qemmu-guest-agent package for common operating systems (such as suse, redhat/centos, and ubuntu) in the harvester iso directly, or as a docker image. When harvester is installed, it serves as a software repository for the virtual machine's operating system.

**Comment by yasker** [comment]
@zhilong-rancher Normally it's the responsibility of the image to have the right driver. And all the vendors you mentioned above already have the daily build cloud image with the right driver. The only one who doesn't have the right driver built-in is Windows, which Harvester would provide the driver to.

I am not sure what value can Harvester add to serve the os-specific qemu-guest-agent when os vendors already have those drivers built-in with the cloud image.

**Comment by zhilong-rancher** [comment]
> @zhilong-rancher Normally it's the responsibility of the image to have the right driver. And all the vendors you mentioned above already have the daily build cloud image with the right driver. The only one who doesn't have the right driver built-in is Windows, which Harvester would provide the driver to.
> 
> I am not sure what value can Harvester add to serve the os-specific qemu-guest-agent when os vendors already have those drivers built-in with the cloud image.

Thank you very much. 
The operating system image already comes with this package, so Harvester doesn't have to provide it.
I use the Ubuntu system. Maybe in an offline environment, before installing qemu-guest-agent , there was an operation to update the software source (apt update), but the apt update could not be completed, so qemu-guest-agent could not be installed successfully.

**Comment by yasker** [comment]
If it's Ubuntu, are you using something like https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-disk-kvm.img ? This is a cloud image that contains the `qemu-guest-agent`. I am fairly sure it doesn't need to run `apt update/install` to install the guest agent.

**Comment by zhilong-rancher** [comment]
I'm using this image ： https://cloud-images.ubuntu.com/releases/focal/release-20211129/ubuntu-20.04-server-cloudimg-amd64.img .
In offline environments, qemu-guest-Agent is not automatically installed, nor  it cannot be installed manually.
Maybe this image not contains the qemu-guest-Agent.
<img width="719" alt="image" src="https://user-images.githubusercontent.com/62644977/155283987-6899e533-fe22-4186-b002-d4ca76807a74.png">

**Comment by yasker** [comment]
It does look like a cloud image specific problem. OpenSUSE 15.3 cloud image (e.g. https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2 ) does have qemu-guest-agent (`qemu-ga`) contained in the image.
<img width="1055" alt="Screen Shot 2022-02-23 at 7 46 29 AM" src="https://user-images.githubusercontent.com/3344618/155354750-1b792a08-85cc-4d7d-ae07-8f153fb135d9.png">
