### ISSUE TITLE
The harvester node automatically restarts at regular intervals

### ISSUE THREAD

**Issue by wangpan-hqu** [harvester/harvester#1753]
**Describe the bug**

The harvester node automatically restarts at regular intervals
![屏幕截图 2021-12-28 152601](https://user-images.githubusercontent.com/74587498/147540063-6a89e689-a6c5-4a3e-aa24-5f8fac9d6fae.png)

**To Reproduce**
Cannot reproduce

**Expected behavior**

The node is running normally

**Environment:**
 - Harvester ISO version:  0.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

Can you provide some suggestions for reference
@guangbochen

**Comment by guangbochen** [comment]
this might be identical to the kernel panic error of https://github.com/harvester/harvester/issues/1342, can u please help to try the latest v1.0.0 version, thanks.

**Comment by wangpan-hqu** [comment]
> this might be identical to the kernel panic error of #1342, can u please help to try the latest v1.0.0 version, thanks.

I installed v1.0.0 version by ISO still restarts
![lQLPDhsC51NGXX3NARDNBi2wxaePN0RwxZcB1W4zG8CbAA_1581_272](https://user-images.githubusercontent.com/74587498/147808384-ffbe3ee5-8b0c-4ba7-aad9-139ceda5197a.png)

**Comment by bk201** [comment]
Hi, @wangpan-hqu Collecting the crash log of the node might help, please see https://docs.harvesterhci.io/v1.0/troubleshooting/os/#collect-crash-dumps to enable it.

**Comment by wangpan-hqu** [comment]
> Hi, @wangpan-hqu Collecting the crash log of the node might help, please see https://docs.harvesterhci.io/v1.0/troubleshooting/os/#collect-crash-dumps to enable it.
I uploaded the log of the latest crash in debug mode. Can you help me see what the problem is? Thank you very much
@guangbochen @bk201 
[README.txt](https://github.com/harvester/harvester/files/7806882/README.txt)
[dmesg.txt](https://github.com/harvester/harvester/files/7806852/dmesg.txt)

**Comment by w13915984028** [comment]
@wangpan-hqu Did you solve this issue?

From the log, your server is using a 2.2.2 BIOS, and the new version is 2.9.0. You may try to upgrade BIOS.

[    0.000000] DMI: Dell Inc. PowerEdge R620/0XWDCF, BIOS 2.2.2 01/16/2014

https://www.dell.com/support/home/en-uk/drivers/driversdetails?driverid=w1wjw&oscode=sle12&productcode=poweredge-r620

**Comment by w13915984028** [comment]
Close. Feel free to reopen in case it occurs again. Thanks.
