### ISSUE TITLE
[BUG] The console can only scroll half of the content of the window 

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#1756]
**Describe the bug**
The console can only scroll half of the content of the window ，The vertical scroll bar cannot be pulled down to the bottom

**To Reproduce**
1. Create a VM
2. Wait for the VM to become active, and then connect the console to the VM
3. The scroll bar of the console window cannot be pulled down to the bottom
![image](https://user-images.githubusercontent.com/15829074/147623686-d85c6238-f92c-42d2-a86d-df8e77978667.png)

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-1be9cb5e-head (1/23). Close this issue.

### Result
We can scroll down to the bottom of the serial console window in virtual machine  
![image](https://user-images.githubusercontent.com/29251855/150713015-ea59f7fc-9263-4564-bb49-c8f823686695.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-1be9cb5e-head (1/23)

### Verify Steps
1. Create a ubuntu virtual machine 
2. Set the following user data in cloud config 
  ```
  password: 123456
  chpasswd: { expire: False }
  ssh_pwauth: True
  ```
3. Open virtual machine in serials console
4. Login with default user ubuntu
5. Run command to output large amount of content to console 
6. Scroll down console to the bottom of the window
