### ISSUE TITLE
 helm install harvester, the service is normal, open the UI is rancher UI, not harvester UI

### ISSUE THREAD

**Issue by wangpan-hqu** [harvester/harvester#1759]
![屏幕截图 2021-12-30 174228](https://user-images.githubusercontent.com/74587498/147740321-857e085f-dc22-47eb-b192-a0b2320366eb.png)
![屏幕截图 2021-12-30 174304](https://user-images.githubusercontent.com/74587498/147740334-98b62637-602a-4767-9a61-d0a2a5d1d37f.png)
@guangbochen

**Comment by futuretea** [comment]
@wangpan-hqu 
need set cluster's 'status.provider' to "harvester"
```bash
kubectl edit clusters.management.cattle.io local
```

**Comment by futuretea** [comment]
@wangpan-hqu 
I'm submitting a PR https://github.com/harvester/docs/pull/108. It might help

**Comment by guangbochen** [comment]
close in favor of the doc https://docs.harvesterhci.io/v1.0/dev/dev-mode/, feel free to reopen if u encounter any additional issues, thanks.
