### ISSUE TITLE
Users are able to view all the items created using the same pub key if only is selected on VM detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#176]
**Steps to reproduce:**
1. Create several SSH key with different names by using the same pub key
2. Create a VM by using one of the SSH keys that created above
3. After the VM is created, check on its detail page and click the SSH-keys icon

**Result:**
 Though just one of the SSH-keys is selected, users are able to view all the items created using the same pub key
![image](https://user-images.githubusercontent.com/57614736/94005034-399f7d80-fdd0-11ea-8f7a-3f06a010c89c.png)

**Comment by WuJun2016** [comment]
Can I put this issue in the next version ？ In the next version, I will add `harvester / annotations: UI` to all CRDs created through UI to solve such problems. @guangbochen

**Comment by DoNotSayYes** [comment]
Validated
