### ISSUE TITLE
[BUG] CTRL+C can't stop system from rebooting after installation

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1761]
**Describe the bug**
After the installation, Console would prompt
```
 * Rebooting system in 5 seconds (CTRL+C to cancel)
```
But pressing CTRL+C can't stop the system from rebooting.

![image](https://user-images.githubusercontent.com/5047724/147896093-fc5d88d6-6975-40c3-9798-9d2e99eb6919.png)

**To Reproduce**

1. Install Harvester using 1.0.0 ISO on KVM
2. When console prompted ` * Rebooting system in 5 seconds (CTRL+C to cancel)`, press CTRL+C
3. The system reboots

**Expected behavior**
Pressing CTRL+C should stop the system from rebooting.

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on master-82c4225b-head. Close this issue.

### Result
Click `CTRL+C` while console installation finished loading, it will stop the system and back to the console login. 
 ![image](https://user-images.githubusercontent.com/29251855/148715296-615a3b30-30d0-498d-96b6-a1f89599fc8c.png)

If we proceed to manual install, it will continue to booting and finish the follow up setup
![image](https://user-images.githubusercontent.com/29251855/148715419-ec0856c0-f991-43d7-b2af-11e6fe336ff8.png)

![image](https://user-images.githubusercontent.com/29251855/148715910-d722de85-2c5c-46c0-beeb-9684e1ec331a.png)

### Test Information
* Test Environment: 1 nodes harvester on local kvm machines
* Harvester version: master-82c4225b-head (22/01/10)

### Verify Steps

1. Use ISO install harvester 
2. While loading file and finish installation prompt `Rebooting system in 5 seconds`
3. Click the `CTRL+C` 
4. Check system should stop to reboot
