### ISSUE TITLE
[BUG] Windows virtio drivers not signed for UEFI BIOS

### ISSUE THREAD

**Issue by nunix** [harvester/harvester#1767]
**Describe the bug**
When creating a Virtual Machine (VM) with the Windows template, which provides the SUSE virtio drivers for Windows, upon the first reboot after the installation, Windows cannot boot due to the drivers signature missing.

**To Reproduce**
I'm currently using Windows Server 2022, however I face the same issue with Windows Server 2019.

Prerequisites:
1. Download Windows Server 2019 ISO
2. Go to Harvester dashboard > Images
3. Create a new `image` in Harvester with the Windows Server 2019 ISO
![image](https://user-images.githubusercontent.com/905874/148035992-c3a9606e-8942-48b9-8d02-2db8a4857664.png)

1. Go to Harvester dashboard > Virtual Machines
2. Click `Create`
3. On the header, enter a `Name` and click `Use VM Template`
3.1. On the `template` dropdown list, select `harvester-public/windows-iso-image-base-template`
3.2. Keep the `1 (default)` version
4. On the `Basics` tab, adjust (if needed) the `CPU` and `Memory` values (i.e. CPU 4 / Memory 8)
![image](https://user-images.githubusercontent.com/905874/148036879-c5a5442d-5c12-477e-8220-0d3b348e8b6f.png)
5. Click on the `Volumes` tab
5.1. On the first `Image Volume`, click on the `Image` dropdown list and select the Windows Server 2019 image
5.2. If the `Type` changed to `disk`, change it back to `cd-rom`
![image](https://user-images.githubusercontent.com/905874/148037780-c0455bf9-a63a-45b7-b668-d1c98b1326ee.png)
6. You can keep the default settings for both `Networks` and `Node Scheduling` tabs
7. Click on the `Advanced Options`
7.1. Click on the `OS Type` dropdown list and select `Windows`
![image](https://user-images.githubusercontent.com/905874/148038064-a3d0a766-c227-4a8e-a100-48c9d222c5a2.png)
8. On the footer, click on `Edit as YAML`
9. Add the following lines in the node `spec.spec.domain`:
```yaml
        features:
          acpi: {}
          smm:
            enabled: true
        firmware:
          bootloader:
            efi:
              secureBoot: true
```
![image](https://user-images.githubusercontent.com/905874/148038530-f30b88cc-b134-404f-a77d-0f25effaf126.png)
9. Click on `Create`
10. Once the VM is running, click on `Console` and select `Open in Web VNC`
11. The UEFI boot will be running, click on the Window and press a key to start the installation
12. Select the lang and the keyboard, click `Next`
13. Click `Install now`
14. Select the version to install (i.e. Windows Server 2019 Standard (Desktop Experience)), click `Next`
15. Click the checkbox `I accept the license terms`, click `Next`
16. Select the option `Custom: Install Windows only (advanced)`
17. Click `Load driver`
17.1. Click `Browse` on the popup
17.2. Click on `>` of the `vmdp-200205_virt` CD Drive
17.3. Click on `>` of the `win10-2019` directory
17.4. Click on `>` of the `x64` directory
17.5. Click on `pvvx` directory to select it, click `OK`
17.6. Select all the drivers (i.e. press `CTRL+A`), click `Next`
![image](https://user-images.githubusercontent.com/905874/148041107-3bfe222d-0890-4c72-aa6e-0e197763309e.png)
18. Select the disk you want to install Windows Server on, click `New`
18.1. Keep the suggested sized, click `Apply`
18.2. Click `OK`
![image](https://user-images.githubusercontent.com/905874/148041490-84b29d7b-aad5-450d-94ed-102a552fc870.png)
19. Keep the selected partition (should be the bigger in size), click `Next`

Once the installation is done, the VM will reboot and the following error will appear:
![image](https://user-images.githubusercontent.com/905874/148042223-e1499145-e66b-4dd5-898d-c56a525b0211.png)

**Expected behavior**
When using the same process as described above with the [`virtio` drivers](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md), Windows Server can boot successfully

**Support bundle**
This issue is related to the Guest VM drivers only.

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal on Asus laptop (8 cores / 32Go RAM)

**Additional context**
N/A

**Comment by guangbochen** [comment]
As an enhancement of windows server 2022 support, we can mitigate it by:
- Allowing users to enable [`Booting in EFI mode`](https://docs.openshift.com/container-platform/4.8/virt/virtual_machines/advanced_vm_management/virt-efi-mode-for-vms.html) directly via adding a new option in the advance tab.
- bump the built-in vmdp container image version to be compatible with the [virtio-win ISO](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md)

**Comment by n313893254** [comment]
I also see the `KMODE exception not handled` error, which might block by the [issue](https://github.com/harvester/harvester/issues/276)

Next, I will use ubuntu to verify the EFI mode.

**Comment by n313893254** [comment]
Verified EFI mode enabled as expect for ubuntu

<img width="1066" alt="image" src="https://user-images.githubusercontent.com/18737885/157016433-34911eea-55c5-45fb-9f66-34d04fc46201.png">

**Comment by FrankYang0529** [comment]
Verified on master-head harvester. Both windows-2019 and windows-2022 can work with EFI.

**Comment by lanfon72** [comment]
verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/157618821-f15aa2e0-09ad-4344-90df-467034168643.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-fd872c99-head**
* **ui-source** Option: **Auto**
* **Virtio-win ISO**: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/stable-virtio/virtio-win.iso

### Verify Steps:
- Follow the **Steps to reproduce** in https://github.com/harvester/harvester/issues/1767#issue-1093194711
- Download [virtio-win ISO](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md), drivers might be placed in **amd64/win2k19**
