### ISSUE TITLE
The VM description is duplicate in annotations

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#177]
**Steps to reproduce:**
1. Create a VM filling something in the description
2. After the VM is created, check on the VM detail page

The description is duplicate in annotations

**Results:**
- [x] 1. The description is added as an annotation, nothing is populated in description
![image](https://user-images.githubusercontent.com/57614736/94094648-96dc1300-fe52-11ea-953e-70422cc3bdae.png)

- [x] 2. Edit description filling something in and save, another annotation is added
![image](https://user-images.githubusercontent.com/57614736/94094930-444f2680-fe53-11ea-9699-03bf664160a2.png)
![image](https://user-images.githubusercontent.com/57614736/94095067-7fe9f080-fe53-11ea-9141-3d3f9afa1992.png)

- [x] 3. Erase the description content then save it, the annotation `description` is not deleted accordingly
![image](https://user-images.githubusercontent.com/57614736/94095887-40bc9f00-fe55-11ea-8574-c0d0da1c0736.png)

**Suggestion:**
Though the description is saved as an annotation, it makes no sense to display it in annotations, because a description has been provided

**Comment by DoNotSayYes** [comment]
The description is still only added to annotations, I suppose that the description should be only shown in the description but not in annotations. @DaiYuzeng 
![image](https://user-images.githubusercontent.com/57614736/97842593-cff58600-1d22-11eb-96b0-e18b95497327.png)
![image](https://user-images.githubusercontent.com/57614736/97842566-c3712d80-1d22-11eb-8def-4a6af17d0803.png)

**Comment by DaiYuzeng** [comment]
@DoNotSayYes Please validate it again, thanks!

**Comment by DoNotSayYes** [comment]
Is that necessary to display the description again in annotations? Maybe suppress it in annotations, just displaying in the description would be better? @DaiYuzeng 
![image](https://user-images.githubusercontent.com/57614736/99790587-500f4e80-2b5f-11eb-9e17-0a7aafef3a7e.png)

**Comment by DaiYuzeng** [comment]
@DoNotSayYes Sorry, could you tell me how to reproduce it? In my environment , it isn't displayed in the annotation modal.

![image](https://user-images.githubusercontent.com/15041915/99791837-30792580-2b61-11eb-8100-f48b2d631b37.png)
![image](https://user-images.githubusercontent.com/15041915/99791850-353dd980-2b61-11eb-82d4-6b9d19461f51.png)

**Comment by DaiYuzeng** [comment]
Or could you provide me the environment which can reproduce. Thanks!

**Comment by DaiYuzeng** [comment]
annotations modal was removed from the details page of vm.

**Comment by DoNotSayYes** [comment]
Label & Annotation tab has been removed
