### ISSUE TITLE
[BUG] LoadBalancer service stuck in pending with valid names

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1770]
harvester 1.0.0
rancher 2.6.3

**To Reproduce**
1. Configure VIP Pool in Harvester -> Settings
2. Provision RKE2 cluster, enabling Harvester Cloud Provider
3. Create a service type LoadBalancer in the default namespace with IPAM->Pool and the following name: `rke2-ingress-nginx-controller`

**Expected behavior**
Loadbalancer service is provisioned

**Actual behavior**
LoadBalancer service is stuck in `pending` indefinitely. This is triggered by using specific, valid service names (exceeding specific length, characters, etc...)

harvester-cloud-provider log:
```
E0104 11:03:07.933006 1 controller.go:307] error processing service default/rke2-ingress-nginx-controller (will retry): failed to ensure load balancer: wait ip timeout
Tue, Jan 4 2022 12:03:07 pm | I0104 11:03:07.933221 1 event.go:291] "Event occurred" object="default/rke2-ingress-nginx-controller" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: wait ip timeout"
```
kube-vip-cloud-provider log:

```
<empty>
```

**Comment by yaocw2020** [comment]
It works with the name `rke2-ingress-nginx-controller` in my environment.

In pool mode, the log `wait ip timeout` indicates the kube-vip-cloud-provider failed to allocate an IP for the load balancer. Could you help to check the kube-vip-cloud-provider again?

**Comment by janeczku** [comment]
@yaocw2020 Nothing is logged in `kube-vip-cloud-provider` when this issue occurs.
Bug is reproducable every time when creating this service object:
[rke2-ingress-nginx-controller.yaml.txt](https://github.com/harvester/harvester/files/7813413/rke2-ingress-nginx-controller.yaml.txt)

When shortening the service name to  `rke2-ingress` then the issue does not occur.


harvester-cloud-provider repeatedly logs same error:

```
Wed, Jan 5 2022 9:48:09 am | I0105 08:48:09.891137 1 event.go:291] "Event occurred" object="default/rke2-ingress-nginx-controller" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
Wed, Jan 5 2022 9:48:15 am | E0105 08:48:15.004301 1 controller.go:307] error processing service default/rke2-ingress-nginx-controller (will retry): failed to ensure load balancer: wait ip timeout
Wed, Jan 5 2022 9:48:15 am | I0105 08:48:15.005022 1 event.go:291] "Event occurred" object="default/rke2-ingress-nginx-controller" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: wait ip timeout"
Wed, Jan 5 2022 9:48:20 am | I0105 08:48:20.005082 1 event.go:291] "Event occurred" object="default/rke2-ingress-nginx-controller" kind="Service" apiVersion="v1" type="Normal" reason="EnsuringLoadBalancer" message="Ensuring load balancer"
Wed, Jan 5 2022 9:48:25 am | E0105 08:48:25.025153 1 controller.go:307] error processing service default/rke2-ingress-nginx-controller (will retry): failed to ensure load balancer: wait ip timeout
Wed, Jan 5 2022 9:48:25 am | I0105 08:48:25.026202 1 event.go:291] "Event occurred" object="default/rke2-ingress-nginx-controller" kind="Service" apiVersion="v1" type="Warning" reason="SyncLoadBalancerFailed" message="Error syncing load balancer: failed to ensure load balancer: wait ip timeout"
```

**Comment by janeczku** [comment]
@yaocw2020  To reproduce the issue, ensure that the name of your RKE2 cluster is 10 characters or more 😉  (in my case the guest cluster is named `production-cluster`).

The bug seems to be related to the length of the (parent) service names generated in Harvester cluster. That service name is generated based on cluster name, namespace, service name + uuid. And if that generated name exceeds 64 characters the issue is triggered.

Here you can see the service loadBalancer named `rke2-ingress` which is successfully created. The service named `rke2-ingress-nginx-controller` is never created here:
```
harvester: $ kubectl get svc -n default
kubernetes                                             ClusterIP      10.53.0.1       <none>            443/TCP                      7d18h
production-cluster-kube-system-rke2-ingress-1e0fea5a   LoadBalancer   10.53.64.109    192.168.200.215   80:32255/TCP                 13m

**Comment by yaocw2020** [comment]
> @yaocw2020 To reproduce the issue, ensure that the name of your RKE2 cluster is 10 characters or more 😉 (in my case the guest cluster is named `production`).
> 
> The bug seems to be related to the length of the (parent) service names generated in Harvester cluster. That service name is generated based on cluster name, namespace, service name + uuid. And if that generated name exceeds 64 characters the issue is triggered.
> 
> Here you can see the service loadBalancer named `rke2-ingress` which is successfully created. The service named `rke2-ingress-nginx-controller` is never created here:
> 
> ```
> harvester: $ kubectl get svc -n default
> kubernetes                                             ClusterIP      10.53.0.1       <none>            443/TCP                      7d18h
> production-cluster-kube-system-rke2-ingress-1e0fea5a   LoadBalancer   10.53.64.109    192.168.200.215   80:32255/TCP                 13m
> ```

The load balancer name is composed of the cluster name, namespace, svc name, and suffix. I guess its length is beyond what the Kubernetes supports if your cluster name and svc name are long.

**Comment by janeczku** [comment]
Yes, it seems harvester-cloud-controller does not observe the Kubernetes naming conventions and tries to create some resource with illegal names.

**Comment by yaocw2020** [comment]
https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
The name contains at most 63 characters, not 253.
If the name has more than 63 characters, the harvester cloud provider will truncate it and reserve the first 63 characters.

**Comment by Jellyfrog** [comment]
I'm getting the same error after deploying a rke2 cluster via rancher.
I created a cluster called "rke2" (so 4 chars) and setup a loadbalancer (Pool or DHCP doesn't matter)
The network got DHCP and ive setup a vip pool in harvester.

It still says " Error syncing load balancer: failed to ensure load balancer: wait ip timeout "

[supportbundle_fb3938fa-4c03-4c20-984c-bc4a41394efc_2022-01-14T09-35-37Z.zip](https://github.com/harvester/harvester/files/7869379/supportbundle_fb3938fa-4c03-4c20-984c-bc4a41394efc_2022-01-14T09-35-37Z.zip)

So not sure if related or not.

**Comment by yaocw2020** [comment]
To test:
- Create a guest cluster.
- Create a deployment and the related load balancer service. To make the load balancer name composed of the cluster name, namespace, svc name, and suffix more than 63 characters.

**Comment by lanfon72** [comment]
I can't create the test environment in the combination:
- qemu/KVM 3/2/1 node(s) with Rancher v2.6.3
- Bare metal DL360 3 nodes with Rancher v2.6.3

Mostly stucked on `Provisioning` as the snapshot:
![image](https://user-images.githubusercontent.com/5169694/155499402-413f07c7-083a-43ec-874b-718dff729500.png)

**Comment by TachunLin** [comment]
Can't reproduce the test environment since rke2 deployment stuck in `provisioning` to join url to be available on bootstrap node
It could related to issue https://github.com/rancher/rancher/issues/36716. Move it to implement pipeline

  ![image](https://user-images.githubusercontent.com/29251855/156093343-c1d8339b-5c51-4421-9813-e043fc20cb5d.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-bfd6a8a9-head (2/27)
* Rancher version: v2.6-head (e93a53c) 

### Support Bundle
[supportbundle_3ea3dae4-0b40-4bb8-8c90-55edad2438ec_2022-03-01T02-51-20Z.zip](https://github.com/harvester/harvester/files/8158439/supportbundle_3ea3dae4-0b40-4bb8-8c90-55edad2438ec_2022-03-01T02-51-20Z.zip)

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-088a020f-head` (03/09) with Rancher v2.6-head (47c2238). 
Move the issue to implement stage.

### Result
The load balancer deployment stuck in `pending` status with `wait ip timeout error`. 
Load balancer name: `rke2-cluster-1211-one-node-defult-ingress-nginx-controller-prod` (63 characters, exceed will display error message)

![image](https://user-images.githubusercontent.com/29251855/157476646-a3ab17a9-a3cd-47b3-b364-777a752c2031.png)

![image](https://user-images.githubusercontent.com/29251855/157476765-e55b5df2-2cea-431d-8cb1-ca8fca622ef2.png)

  ```
  # Run kubectl commands inside here
  # e.g. kubectl get all
  > kubectl get svc -n default
  NAME                                                              TYPE           CLUSTER-IP     EXTERNAL-IP   PORT(S)        AGE
  kubernetes                                                        ClusterIP      10.43.0.1      <none>        443/TCP        92m
  rke2-cluster-1211-one-node-defult-ingress-nginx-controller-prod   LoadBalancer   10.43.51.220   <pending>     80:30000/TCP   12m
  ```

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-088a020f-head` (03/09) 
* Rancher version: v2.6-head (47c2238)
* Kubernetes version: v1.21.10+rke2r1 
* OS image: Ubuntu cloud focal


### Verify Steps
1. Provision a RKE2 cluster in rancher with kubernetes version: v1.21.10+rke2r1 
2. Deploy a nginx workload
3. Create a load balancer service in service discovery 
4. Make the load balancer name composed of the cluster name, namespace, svc name, and suffix with 63 characters.
  ![image](https://user-images.githubusercontent.com/29251855/157474486-35ba9c88-2305-4d35-b407-64b1b3d2b4b5.png)
5. Set IPAM -> Pool 
  ![image](https://user-images.githubusercontent.com/29251855/157473519-e8806b12-2129-44aa-84c4-440cdcfe64a7.png)
6. Check the load balancer deployment

**Comment by TachunLin** [comment]
This issue will be fixed at the latest harvester cloud provider version bumped to next rancher release.  
Currently we can use the workaround to manually upgrade cloud provider image to `0.1.2` to make load balancer work even with long pod name. 
Move this issue to ice box and add it to the regression test for next rancher release with harvester testing. 

![image](https://user-images.githubusercontent.com/29251855/157631075-3b2d385f-fb52-47f2-a0a8-069aefe49eef.png)

### Workaround   
To update the image version you can:
1. Expand Workload -> Deployment 
2. Edit yaml of `harvester-cloud-provider`
3. Update the image version from `v0.1.0` to `v0.1.2`
  ![image](https://user-images.githubusercontent.com/29251855/157631709-dccff994-11e7-45c0-a952-a4ea0ffdd9c9.png)
4. Save the changes and wait for cloud provider update complete
5. Deploy a nginx service 
  ![image](https://user-images.githubusercontent.com/29251855/157631928-46204089-96fa-4909-bf9c-218646443fff.png)
6. Expand Service Discovery -> Services
7. Create a LoadBalancer service with long name (e.g rke2-cluster-1211-one-node-defult-ingress-nginx-controller-prod)
8. Edit the yaml of nginx 
9. Find the select key values 
 ![image](https://user-images.githubusercontent.com/29251855/157632455-6691fd37-852e-480c-b598-0e0d74c77d79.png)
10. Input the selector key values in Selectors page 
 ![image](https://user-images.githubusercontent.com/29251855/157632670-5ea5f2db-2466-424b-9ba5-95c194d1b0e1.png)
11. Create a VIP pool in harvester settings 
  ![image](https://user-images.githubusercontent.com/29251855/157632893-c895cd80-64be-4b17-b47a-c73fce1d53be.png)
12. Select IPAM -> Pool
13. Create the LoadBalancer

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Name: test-cluster-local-harvester-default-rancher-rke2-load-balancer (63 chars)
![image](https://user-images.githubusercontent.com/5169694/158772313-70030042-2874-47ca-9a6c-8a6cc962fcad.png)
![image](https://user-images.githubusercontent.com/5169694/158776281-71b556b6-ab0b-4762-a9f6-ef539948d0ed.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.1-rc1**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6-5bb08b3692ac3c18ec1361694a095e2c25eb0346-head** (docker Image ID: **7a5207887b1a**)

### Verify Steps:
- same as https://github.com/harvester/harvester/issues/1770#issuecomment-1063069590
