### ISSUE TITLE
[BUG] HarvesterMachines resources are not cleaned up

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1774]
**Describe the bug**

HarvesterMachine resources are not cleaned up after removing Harvester RKE2 clusters that contained machines which were not fully provisioned.

This causes Rancher logs to be spammed with errors and increases the load on `local` cluster control plane over time due to constant retries.

**To Reproduce**

1. Provision a Harvester RKE2 cluster in such way that provisioning of the VMs will not succeed, e.g. by attaching VMs to a VLAN w/o DHCP.
2. Delete the "failed" cluster
3. Check HarvesterMachine resources in the `local` Cluster
4. Check Rancher logs 

```
022/01/05 12:17:01 [ERROR] error syncing 'fleet-default/thorenexttry-pool1-fb8e624e-zmmkt': handler machine-provision-remove: cannot delete machine thorenexttry-pool1-fb8e624e-zmmkt because c │
│ reate job has not finished, requeuing                                                                                                                                                            │
│ 2022/01/05 12:17:01 [ERROR] error syncing 'fleet-default/ubuntucluster-pool2-dfa5c3cc-btjtx': handler machine-provision-remove: machines.cluster.x-k8s.io "ubuntucluster-pool2-dfc84888-5cqzx" n │
│ ot found, requeuing                                                                                                                                                                              │
│ 2022/01/05 12:17:01 [ERROR] error syncing 'fleet-default/ubuntucluster-pool2-dfa5c3cc-hl22q': handler machine-provision-remove: machines.cluster.x-k8s.io "ubuntucluster-pool2-dfc84888-zv2sc" n │
│ ot found, requeuing                                                                                                                                                                              │
│ 2022/01/05 12:17:01 [ERROR] error syncing 'fleet-default/ubuntucluster-pool2-dfa5c3cc-z6snq': handler machine-provision-remove: machines.cluster.x-k8s.io "ubuntucluster-pool2-dfc84888-rxbhx" n │
│ ot found, requeuing                                                                                                                                                                              │
│ 2022/01/05 12:17:01 [ERROR] error syncing 'fleet-default/cs2canal-pool1-a1661b5e-x9dwd': handler machine-provision-remove: cannot delete machine cs2canal-pool1-a1661b5e-x9dwd because create jo │
│ b has not finished, requeuing   
```
HarvesterMachine CR:

[cs2canal-pool1-a1661b5e-x9dwd.yaml.txt](https://github.com/harvester/harvester/files/7814810/cs2canal-pool1-a1661b5e-x9dwd.yaml.txt)

**Comment by yasker** [comment]
Hi @joshmeranda , can you help to check on this one? You can check with @dweomer on details.

**Comment by joshmeranda** [comment]
Finally was able to reproduce with help from @dweomer. I'll start drilling to find a cause for this

**Comment by joshmeranda** [comment]
Looks like this is a result of the failing pod for the provisioning job. When rancher creates a new cluster it starts a job. If the cluster does not report back that it is running after 10 minutes (120 attempts with 5s interval) the pod's status is set to `Error`, the job is left uncompleted, and the cluster pod left in `ContainerCreating`.

When you try to delete the cluster, rancher sees that the create job isn't finished yet (and won't be until the cluster gets an ssh server established) so to avoid leaving the cluster VMs hanging around after the cluster is deleted, it logs that the create job hasn't finished and checks back later.

We need either be smarter about how we delete the cluster with unfinished create jobs, or how we handle the failed create jobs.

**Comment by yasker** [comment]
@joshmeranda what's the exact type of `HarvesterMachine` resource @janeczku mentioned in the issue? This looks like a Rancher issue instead of the Harvester node driver issue per your description.

**Comment by joshmeranda** [comment]
@yasker The rancher job, and the pod on the harvester cluster are both left without being cleaned up. Once rancher sees the unfinished complete job it looks like it ignores the related resources.

I think it depends on what approach makes the most sense. If we are going to change how we handle unfinished create jobs when deleting clusters thats a rancher issue, but if we want to change how we handle the failed create job that would be a node driver issue.

**Comment by janeczku** [comment]
Its a Rancher issue as I have seen this issue with other node drivers, e.g. vSphere. It probably must be addressed upstream. Although based on my experience so far the issue is more notorious with Harvester provisioning.

**Comment by guangbochen** [comment]
@TachunLin @lanfon72 can we please re-validate this with Harvester v1.0.3 + Rancher v2.6.7 when it is released since this is more considered as an upstream issue? thanks.

**Comment by lanfon72** [comment]
@guangbochen is this has been fixed or we just need to re-validate the bug still here?

**Comment by joshmeranda** [comment]
@lanfon72 There is a [PR](https://github.com/rancher/rancher/pull/37765) up for this issue but it has not been merged.

**Comment by lanfon72** [comment]
As this issue opened 8 months ago, It should happened in the combination: Rancher `v2.6.3` with Harvester `v1.0.0`.

Able to be reproduced in:
- Rancher `v2.6.3` with Harvester `v1.0.0`
- Rancher `v2.6.6` with Harvester `v1.0.0`
- Rancher `v2.6.3` with Harvester `v1.0.3`
- Rancher `v2.6.6` with Harvester `v1.0.3`

Log messages be reduced in:
- Rancher `v2.6.7-rc9` with Harvester `v1.0.0`
- Rancher `v2.6.7-rc9` with Harvester `v1.0.3`

**Comment by guangbochen** [comment]
@ttpcodes can u please help to check if this is resolved with new Rancher versions like`v2.6-head` + `Harvester v1.1.2-rc1` ? thanks.

**Comment by bk201** [comment]
@ttpcodes Could you help check https://github.com/harvester/harvester/issues/1774#issuecomment-1371821095, thank you!

**Comment by FrankYang0529** [comment]
Validate on `Rancher v2.6-head` + `Harvester v1.1.2-rc1`. If `HarvesterMachine` is not removed, `Cluster` will be kept in the `Deleting` phase. So this issue has been fixed.  Following are my testing steps:

* Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples) to provision a Harvester cluster.
* Import the Harvester cluster to Rancher `v2.6-head`.
* Create a RKE2 cluster.
* When the first VM is provisioned and before it gets an IP. Run `sudo systemctl stop isc-dhcp-server.service` in pxe server.
* After the Harvester cluster get into NotReady. Remove the RKE2 cluster in Rancher.
* Run `sudo systemctl start isc-dhcp-server.service` in pxe server.
* RKE2 and HarvesterMachine will be removed in the Rancher server.

**Comment by lanfon72** [comment]
Verified as resolved.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1-054b48bf-head**
* **ui-source** Option: **Auto**
* Rancher Version:
    - **v2.7-23074b5a970e0c982a1d6bc556eaf02982cab4cd-head (Docker Image: e85cbd4d828c)**
    - **v2.6-8b48bef808b640bd59d29a9a99865c6d6aa709a2-head (Docker Image: 4f4b6e35fb8d)**

### Verify Steps:
1. Install Harvester with any nodes
2. Install Rancher
3. Login to Harvester dashboard, create an image for VM creation
4. Create a VLAN which NOT able to route to Rancher (or external network)
5. Import Harvester into Rancher
6. Create RKE2 cluster
7. Wait until VM created and Cluster showing `Ready (False)`, delete the cluster
8. Cluster should be deleted successfully (this may take few minutes)
9. In **local** cluster, **HarvesterMachines** (by search, all namespaces) should not have VMs which be deleted.

**Comment by lanfon72** [comment]
There have a similar case that if Rancher can NOT access Harvester (either `cluster-registration-url` changed or harvester cluster is not accessible), delete cluster will stuck then _HarvesterMachines_ will not be cleaned up.
