### ISSUE TITLE
[BUG] Cluster Member can not create namespace

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#1776]
**Describe the bug**
1. Add a user as "Cluster Member" to Virtualization -> Harvester -> Edit -> Member Roles
2. Create a new project in Virtualization -> Harvester -> Project/Namespaces
3. Add the new user to this project as Project Member
4. Login as the new user and navigate to Virtualization -> Harvester -> Project/Namespaces

**Expected behavior**
Project member can create namespace in the project

**Actual behavior**
Project member can not create namespace in the project because the "Create Namespace" button is not displayed.

Harvester 1.0.0
Rancher 2.6.3

**Comment by janeczku** [comment]
Observation: If the cluster owner creates an initial namespace in that project, then the Create Namespace button is suddenly visible to the project member. Sounds like an UI bug...

**Comment by gitlawr** [comment]
https://github.com/rancher/rancher/issues/36088

**Comment by guangbochen** [comment]
move the issue to the next milestone as this will need upstream Rancher fix of https://github.com/rancher/rancher/issues/35453 and is scheduled on the v2.6.5.

**Comment by DaiYuzeng** [comment]
@janeczku This issue probably has been fixed.
I didn't reproduce it on rancher/dashboard master branch.
Closed, reopen it please if there is any concern.
![截屏2022-04-21 下午3 34 51](https://user-images.githubusercontent.com/15041915/164404102-e8ed220f-972d-48d4-a876-1f4528f6cff2.png)

![截屏2022-04-21 下午3 34 57](https://user-images.githubusercontent.com/15041915/164404025-22e07a80-c612-4bc5-9c78-4975fbfc527a.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/165258945-afbbefdf-ccb6-446d-8795-9ecdc53e90e5.png)
![image](https://user-images.githubusercontent.com/5169694/165258987-c63d86dd-1b33-4002-a4ce-1ef046980737.png)


Test Information
----
* Environment: **qemu/KVm single node**
* Harvester Version: **master-05b5da2d-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6.4**

### Verify Steps:
- Follow steps in **Describe the bug** in https://github.com/harvester/harvester/issues/1776#issue-1094380313
