### ISSUE TITLE
[BUG] Cluster fails to upgrade to HA after adding 2 nodes

### ISSUE THREAD

**Issue by bgulla** [harvester/harvester#1778]
**Describe the bug**
I went from 1 node to 3, after several hours, the `control-plane` only existed on the first node and not all 3.

**Support bundle**

**Environment:**
 - Harvester ISO version:  1.0

**Comment by bgulla** [comment]
[supportbundle_13416f71-2817-44ca-ac1c-9a9ea173a4cd_2022-01-05T22-02-09Z.zip](https://github.com/harvester/harvester/files/7818049/supportbundle_13416f71-2817-44ca-ac1c-9a9ea173a4cd_2022-01-05T22-02-09Z.zip)

**Comment by bk201** [comment]
Log of pod `harvester-promote-ryzen16-2445v`:

```
2022-01-05T19:18:56.267594206Z Error from server (NotFound): nodes "ryzen" not found
```

The promoting node is named `ryzen16` but the hostname `ryzen` is used.
We need to use node name instead of hostname in the promote script: https://github.com/harvester/harvester/blob/8021f2dc92bd0ab1e4ea67eff20a063d0df7a2f6/deploy/charts/harvester/templates/configmap.yaml#L37

**Comment by bgulla** [comment]
good find, thanks @guangbochen 
closing

**Comment by bk201** [comment]
Reopen this, we can enhance the promotion script by using node name instead of hostname.

**Comment by lanfon72** [comment]
It seems the feature #1793 not implemented as expected?
![image](https://user-images.githubusercontent.com/5169694/149112139-ea356735-f42a-45ec-8e7d-439d2b8a83e6.png)
![image](https://user-images.githubusercontent.com/5169694/149112326-e35a593f-439a-4ebb-8cd9-561bf3bd490d.png)

Test Information
----
* Environment: **qemu/KVM 3nodes**
* Harvester Version: **master-ebde990d-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with 3 nodes
2. Force delete 3rd VM ( and `kubectl get nodes` will show the node is **NotReady**)
3. install another node **3** with different host name
4. When the node is ready, login to console and update host name
5. Delete the 3rd Node to reduce **control-plane** amount
6. Wait until the node **3** to be promoted as **control-plane** and the name in `kubectl get nodes` should not show as the modified host name

**Comment by bk201** [comment]
@lanfon72 #1793 changes the node name in promote script in case there is a mismatch between node name and hostname. It doesn't mean we support changing the hostname.

**Comment by lanfon72** [comment]
@bgulla would you mind to explain your steps to reproduce the case?

**Comment by lanfon72** [comment]
close as can't reproduce the case.
