### ISSUE TITLE
[Question] Creating RKE1 cluster using API doesn't show on Rancher cluster management UI

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#1779]
**Describe the bug**
 I am trying to create RKE1 cluster using the APIs. I am using API
Post https://<rancher-endpoint>/v3/cluster?_replace=true with payload - 
```
{"dockerRootDir":"/var/lib/docker","enableClusterAlerting":false,"enableClusterMonitoring":false,"enableNetworkPolicy":false,"windowsPreferedCluster":false,"type":"cluster","name":"<name>","rancherKubernetesEngineConfig":{"addonJobTimeout":45,"enableCriDockerd":false,"ignoreDockerVersion":true,"rotateEncryptionKey":false,"sshAgentAuth":false,"type":"rancherKubernetesEngineConfig","kubernetesVersion":"v1.21.8-rancher1-1","authentication":{"strategy":"x509","type":"authnConfig"},"dns":{"type":"dnsConfig","nodelocal":{"type":"nodelocal","ip_address":"","node_selector":null,"update_strategy":{}}},"network":{"mtu":0,"plugin":"canal","type":"networkConfig","options":{"flannel_backend_type":"vxlan"}},"ingress":{"defaultBackend":false,"defaultIngressClass":true,"httpPort":0,"httpsPort":0,"provider":"nginx","type":"ingressConfig"},"monitoring":{"provider":"metrics-server","replicas":1,"type":"monitoringConfig"},"services":{"type":"rkeConfigServices","kubeApi":{"alwaysPullImages":false,"podSecurityPolicy":false,"serviceNodePortRange":"30000-32767","type":"kubeAPIService","secretsEncryptionConfig":{"enabled":false,"type":"secretsEncryptionConfig"}},"etcd":{"creation":"12h","extraArgs":{"heartbeat-interval":500,"election-timeout":5000},"gid":0,"retention":"72h","snapshot":false,"uid":0,"type":"etcdService","backupConfig":{"enabled":true,"intervalHours":12,"retention":6,"safeTimestamp":false,"timeout":300,"type":"backupConfig"}}},"upgradeStrategy":{"maxUnavailableControlplane":"1","maxUnavailableWorker":"10%","drain":"false","nodeDrainInput":{"deleteLocalData":false,"force":false,"gracePeriod":-1,"ignoreDaemonSets":true,"timeout":120,"type":"nodeDrainInput"},"maxUnavailableUnit":"percentage"}},"localClusterAuthEndpoint":{"enabled":true,"type":"localClusterAuthEndpoint"},"labels":{},"scheduledClusterScan":{"enabled":false,"scheduleConfig":null,"scanConfig":null}}
```

Post https://<rancher-endpoint>/v3/nodepool with payload 
```
{"type":"nodePool", "controlPlane":true, "deleteNotReadyAfterSecs":0, "drainBeforeDelete":true, "etcd":true,   "quantity":1, "worker":true, "nodeTemplateId":"cattle-global-nt:nt-dgjvx",  "clusterId":"fleet-default", "name":"<name>" , "hostnamePrefix": "<host-prefix-name>"}
```
The VM is created in imported harvester cluster but the created cluster is not visible on Rancher Cluster Management UI

**To Reproduce**
1. Create RKE1 cluster using APIs mentioned in bug description

**Expected behavior**
The RKE1 cluster should display on Rancher Cluster Management UI

**Support bundle**

**Environment:**
 - Harvester ISO version: main
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):Rancher and Harvester installed on Jenkins 

**Additional context**

**Comment by futuretea** [comment]
@chajain  The nodepool payload provided is different from that sent by the UI in two points:
1. The payload sent by UI does not contain the 'name' field
2. The 'clusterId' field sent by the UI is prefixed with "c-" followed by five random characters

**Comment by chajain** [comment]
@futuretea If I try to use c-12345 in 'clusterId' field in nodepool payload the POST REST API fails with error ```{"baseType":"error","code":"NotFound","message":"namespaces \"c-12345\" not found","status":404,"type":"error"}```
 
The REST API only works if I use 'fleet-default' in clusterId field but the cluster doesn't show up on the UI

When I use 'fleet-default' as clusterId field the response is
```{"annotations":{},"baseType":"nodePool","clusterId":"fleet-default","controlPlane":true,"created":"2022-01-06T17:27:20Z","createdTS":1641490040000,"creatorId":"user-v8s2k","deleteNotReadyAfterSecs":0,"drainBeforeDelete":true,"driver":"harvester","etcd":true,"hostnamePrefix":"cjain-rke1-1000","id":"fleet-default:np-ks9xt","labels":{"cattle.io/creator":"norman"},"links":{"nodes":"https://10.84.128.164/v3/nodes?nodePoolId=fleet-default%3Anp-ks9xt","remove":"https://10.84.128.164/v3/nodePools/fleet-default:np-ks9xt","self":"https://10.84.128.164/v3/nodePools/fleet-default:np-ks9xt","update":"https://10.84.128.164/v3/nodePools/fleet-default:np-ks9xt"},"name":"np-ks9xt","namespaceId":null,"nodeTemplateId":"cattle-global-nt:nt-dgjvx","quantity":1,"state":"active","transitioning":"no","transitioningMessage":"","type":"nodePool","uuid":"be933e96-acd7-48e2-b092-66ff2d86393d","worker":true}```

**Comment by chajain** [comment]
@futuretea I am finally able to create RKE1 cluster using the apis I mentioned in the previous msg but the Machine Provider Harvester is not showing on the created cluster. Where do I specify the machineProvider in the templates? (edited) 
![Screenshot from 2022-01-06 14-41-52](https://user-images.githubusercontent.com/28453288/148472110-8a06301d-7c8f-4208-a13e-d0cfd24b3a9f.png)

**Comment by futuretea** [comment]
@chajain  should be the nodeTemplate's 'driver' field ![image](https://user-images.githubusercontent.com/15064560/148478440-134e7620-a27d-4cf5-b1a1-7bd5bc2305b6.png)

**Comment by chajain** [comment]
@futuretea In cloudConfig field, do I need to put the harvester kubeconfig?

**Comment by futuretea** [comment]
> @futuretea In cloudConfig field, do I need to put the harvester kubeconfig?

@chajain  no

**Comment by rebeccazzzz** [comment]
@chajain: Have you received the answer to your question. If so, can we close this ticket? Thank you so much.

**Comment by chajain** [comment]
Issue resolved
