### ISSUE TITLE
[FEATURE] Optimize the way to configure the static VIP

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#1782]
**Is your feature request related to a problem? Please describe.**

Related with https://github.com/harvester/harvester/issues/1772, if the kube-vip supports allocating a static VIP address to service by setting the spec.loadBalancerIP field in the service manifest, we don't have to set it in the configmap anymore.

**Describe the solution you'd like**

Set the harvester cluster VIP in the spec.loadBalancerIP field of the service `kube-system/ingress-expose`, ranther than saving in the configmap and allocating by the kube-vip cloud provider.

**Describe alternatives you've considered**

**Additional context**

**Comment by yaocw2020** [comment]
For testing:
Use the master-head to spin up the Harvester and the VIP will be normal.

**Comment by TachunLin** [comment]
Verified **fixed** on master-9091d7d0-head (02/14) . Wait for #1772 verification status to close this issue.

### Result
Create a 3 nodes harvester with static VIP in the following scenarios, 
the harvester cluster can work as normal and access dashboard via VIP

1. Bare metal machine with static VIP on pxe install
2. Local kvm machine with static VIP on ipxe vagrant example

### Test Information
* Test Environment1: 3 nodes harvester on provo bare machine
* Test Environment2: 3 nodes harvester on local kvm
* Harvester version: master-9091d7d0-head (02/14)

### Verify Steps
1. Use static VIP to setup a 3 nodes harvester cluster on bare machine
2. Check harvester cluster work as normal, 
3. Check can access dashboard via the static VIP
4. Use ipxe example to setup a 3 nodes harvester cluster on local kvm machine
5. Check harvester cluster work as normal, 
6. Check can access dashboard via the static VIP

### Additional Context

**Comment by yaocw2020** [comment]
If this issue is verified successfully, the issue [1772](https://github.com/harvester/harvester/issues/1772) could be closed as well because this issue is a real case of issue 1772. In other words, this optimization must not be completed if issue 1772 is still not fixed. @TachunLin

**Comment by TachunLin** [comment]
Close this issue since the related issuse #1772 have been verified and close.
