### ISSUE TITLE
[FEATURE] Add the ability to view the logs of pods in the vm

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1784]
**Is your feature request related to a problem? Please describe.**

Let the user view the vm's pod information

**Describe the solution you'd like**

**Describe alternatives you've considered**

1. click VM action
2.  add `View Logs`  action

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/d893f3b8-5a73-44ae-942d-74009e304af8)
**Additional context**

**Comment by WuJun2016** [comment]
### test step

1. click vm action
2. click `View Logs`

![image](https://user-images.githubusercontent.com/24985926/148716521-54b67082-973b-47a7-bdc4-a907ebb1fa35.png)

**Comment by lanfon72** [comment]
Verified `View Logs` in VM's Options works as expected.
![image](https://user-images.githubusercontent.com/5169694/148914362-7d34806c-6067-4903-a53e-18047ebc2c42.png)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-177ab565-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM, then start it
4. Click `View Logs` in the VM (both the VMs list and VM's details)
5. restart/migrate VM
6. **Logs** should show in the log panel
