### ISSUE TITLE
[FEATURE] include fdisk, wipefs and or parted in the installation iso

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#1796]
**Is your feature request related to a problem? Please describe.**
Trying to clear a disk while doing the installation or to ensure other disks can be cleaned to use for Longhorn

**Describe the solution you'd like**
Include fdisk, parted, wipefs in the installation media

**Comment by bk201** [comment]
@abonillabeeche Those utilities should be included already, could you test them with `sudo` or switch to `root` user first? Thanks!

**Comment by bk201** [comment]
@abonillabeeche Could you take a look if these tools are available as root?  Thanks!

**Comment by abonillabeeche** [comment]
this can be closed. Available as root

**Comment by bk201** [comment]
@abonillabeeche , Thanks!
