### ISSUE TITLE
[FEATURE] Multidisk Install

### ISSUE THREAD

**Issue by Steven-Beasley** [harvester/harvester#1798]
**Describe the solution you'd like**
I would like to see the installer have a target for OS, and Target(s) for longhorn disks.  Possibly with auto formatting options.

**Comment by bk201** [comment]
@Steven-Beasley I believe the request is the same as https://github.com/harvester/harvester/issues/1728 could you take a look? Thanks!

**Comment by Steven-Beasley** [comment]
Yes I think that one would cover what I’d like to see

**Comment by bk201** [comment]
Thanks, I'll close this one.
