### ISSUE TITLE
SSH key popup window is populated with content that filled previously on the VM detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#180]
On the Virtual Machine create page, to add a new SSH key. Stay on the page and add another SSH key again, when the popup window is open, it will be populated with content that filled previously

Moreover, every time click the save button without filling anything, an error message will show, close the window and open it again, the error message will still be there

![image](https://user-images.githubusercontent.com/57614736/94383259-1713b880-0172-11eb-8d11-fc2e0f3effd2.png)
![image](https://user-images.githubusercontent.com/57614736/94383286-272b9800-0172-11eb-99a7-c58226da018a.png)

**Comment by DaiYuzeng** [comment]
1. The form will reset fields if save successfully.
2. Remove error messages before open the modal.

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/203
