### ISSUE TITLE
[FEATURE] Allow scrolling up installing logs

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1800]
**Is your feature request related to a problem? Please describe.**
Sometimes, it's hard to debug an installation failure because of missing logs.

The following screenshot is taken when the installer invokes cOS install scripts:

![148959889-62a7f0a8-696f-4b23-8d24-611a5f4da3ef](https://user-images.githubusercontent.com/1691518/149061112-d7597687-1bf4-4f4d-8acd-8b0c731bec2e.png)

The messages can't be scrolled up to know what happened previously.

**Describe the solution you'd like**

There are some ways to improve:
- Make the panel scrollable with keys.
- Log the output to installer logs, currently we don't log it.
- The output messages have stdout data first and stderr data at the end. It's easier to debug if the stdout and stderr are logged in the correct order.

**Describe alternatives you've considered**

**Additional context**

**Comment by yasker** [comment]
Having enough information in the installer for debugging purposes is important.

Scrolling up would be good, though I am not sure how easy to implement it.

I agree that we should log the output to the installer logs, maybe make it available via the serial port, as well as accessible if switching the console and find it e.g. `/var/log/xxxx.log`(is this the installer log?).

I think we should schedule this enhancement item sooner than later. @bk201 Do you think it's doable in v1.0.1 or we can leave it for v1.0.2?

**Comment by bk201** [comment]
@yasker Let's make it to 1.0.1, it's really hard to debug without those messages. At least we need to record them in `/var/log/console.log`.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.
![image](https://user-images.githubusercontent.com/5169694/156122252-38385fc1-9139-4680-88b3-dd22d472147c.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-bfd6a8a9-head**

### Verify Steps:
1. Install Harvester with any Nodes
2. Login to Console
3. File `/oem/install/console.log` should contain Installing logs

**Comment by bk201** [comment]
@guangbochen could we close https://github.com/harvester/tests/issues/185?
I feel there is nothing we can do.

**Comment by guangbochen** [comment]
Yep, also we can skip creating the e2e test issue via adding the label `not-require/test-plan` thanks.
