### ISSUE TITLE
[BUG] install fails at grub2-install

### ISSUE THREAD

**Issue by kkaempf** [harvester/harvester#1813]
**Describe the bug**

Fresh install on a dual-cpu, dual-ssd server. Installer chooses `/dev/sdb` (to my surprise) and stops after a while with
```
grub2-install: error: failed to get canonical path of '/run/cos/target/boot/efi'
```

**To Reproduce**

- boot from iso image
- accept defaults (only `/dev/sdb` was offered)
- wait

**Expected behavior**

Installation to succeed :wink:

**Support bundle**

**Environment:**
 - Harvester ISO version: harvester-v1.0.0-amd64.iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
2x AMD EPYC 7282 (Zen-Rome) 16-Core CPU,
2x SSD 1,9TB SAS3, 24x7, 1 DWPD, Samsung PM1643

**Additional context**

**Comment by kkaempf** [comment]
![CaptureScreen](https://user-images.githubusercontent.com/37742/149401772-5c951c37-4f33-4aa6-995a-ac0016d68bd9.jpeg)

screen capture of remote console

**Comment by bk201** [comment]
@kkaempf Can you change to TTY2 and capture the output of `sudo lsblk` and `sudo blkid`? Thanks!

**Comment by kkaempf** [comment]
Sorry, the system has a broken serial console and (apparently) there's no other way to access it :-(
Will retry on a similar system 🤞🏻

**Comment by kkaempf** [comment]
Turns out that the problem probably was caused by a broken `/dev/sda`. As the drive was replaced meanwhile, I cannot reproduce the problem.
Closing for now. Will re-open if/when new logs are available,

**Comment by patrickdk77** [comment]
I had this same issue, it seems if you already have an efi partition, it doesn't wipe it out correctly and the old label remains, in my case VMWARE label still existed. after doing a zero wipe of the first gig of the drive, reinstalling worked fine and blkid shows the name of the EFI partition as  COS_GRUB instead of VMWARE.....
