### ISSUE TITLE
Fixing the CI release of Release Branch

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#1817]
We would like to fix the CI release of the Release Branch, e.g https://github.com/harvester/harvester/tree/v1.0
So the full-regression test can be performed on the tagged branch with specific versions.

**Comment by futuretea** [comment]
**Test plan**：
1. Download and Install the following Harvester iso
2. After Harvester become Ready, use command:
```bash
kubectl -n harvester-system get po -l app.kubernetes.io/name=harvester -l app.kubernetes.io/component=apiserver \
-o custom-columns='IMAGE:spec.containers[*].image,CHART:metadata.labels.helm\.sh/chart,APP_VERSION:metadata.labels.app\.kubernetes\.io/version'
```
to check the Harvester version and tag.

For example, If the output is:
```bash
  IMAGE                                 CHART                    APP_VERSION         
rancher/harvester:master-head  harvester-0.0.0-master-31626fax  master-31626fax   
```
That means:
| IMAGE_TAG| COMMIT_ID| CHART_VERSION| APP_VERSION| 
| ----------- | ----------- | ----------- | ----------- |
| master-head|31626fax| 0.0.0-master-31626fax| master-31626fax|

**Excepted Version/Tag results**

1. master branch

| ISO URL| IMAGE_TAG| CHART_VERSION| APP_VERSION| 
| -----------| ----------- | -----------  | ----------- |
| https://releases.rancher.com/harvester/master/harvester-master-amd64.iso| master-head|0.0.0-master-`commit id`| master-`commit id`|

2. v1.0 branch

| ISO URL| IMAGE_TAG| CHART_VERSION| APP_VERSION| 
| -----------| ----------- | ----------- | ----------- |
| https://releases.rancher.com/harvester/v1.0/harvester-v1.0-amd64.iso| v1.0-head| 0.0.0-v1-0-`commit id`| v1.0-`commit id`|

3. v1.0 branch + v1.0.1-rc1 tag

| ISO URL| IMAGE_TAG| CHART_VERSION| APP_VERSION| 
| -----------| ----------- | ----------- | ----------- |
| https://releases.rancher.com/harvester/v1.0/harvester-v1.0.1-rc1-amd64.iso| v1.0.1-rc1| v1.0.1-rc1| v1.0.1-rc1|

**Comment by lanfon72** [comment]
Verified this issue has been fixed.

**mater-head**
![image](https://user-images.githubusercontent.com/5169694/160360523-a580cc2f-4a7d-4d2a-b077-5550ac1fec42.png)
**v1.0.1-rc1**
![image](https://user-images.githubusercontent.com/5169694/160360585-9adee821-d453-4ceb-a4a1-8a583fffafe6.png)
**v1.0-head**
![image](https://user-images.githubusercontent.com/5169694/160360656-0de192b7-47b2-4b54-b4a3-a151be88aada.png)


Test Information
----
* Environment: **qemu/KVM single node**

### Verify Steps:
Follow **Test Plan** in https://github.com/harvester/harvester/issues/1817#issuecomment-1069191043
