### ISSUE TITLE
Create KB article tab and blog tab on harvesterhci.io

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#1818]
We would like to create knowledge base articles to help users troubleshoot various failure scenarios. This could be set up like the knowledge base for Longhorn, which can be found here: https://longhorn.io/kb/

**Comment by rebeccazzzz** [comment]
We'd like to add a blog tab to the harvesterhci.io website, so we're updating this ticket to include setting up the KB article tab and setting up the blog tab on harvesterhci.io. Examples for both can be found at https://longhorn.io/.

**Comment by nunix** [comment]
Hi @rebeccazzzz ,

as the Harvester documentation framework (Mkdocs) is not the same as Longhorn (Hugo), I'm checking with my team if something like this has already been done and how best to implement it.
I will provide an update in the coming days (as today is an holiday in US).

**Comment by guangbochen** [comment]
@nunix the [harvesterhci.io ](https://harvesterhci.io/) home page is hosted on https://github.com/harvester/harvester.github.io and it was also using the Hugo with a [customized template](https://github.com/rancherlabs/projects-theme).

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvesterhci.io, and now we can add KB article to this repo and please refer to https://docusaurus.io/docs/blog as a reference.
