### ISSUE TITLE
task: Add a bot to post pre-merge check list in the issue

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#1819]
Make it easy for developers to get the most updated pre-merge check list in the issue.

**Comment by guangbochen** [comment]
TO TEST:
- Added harvester/bot via https://github.com/harvester/bot and the [pre-merge check list](https://github.com/harvester/bot/blob/harvester/github-bot/harvester_github_bot/templates/pre-merge.md) will be added when moving the issue to the `Review` pipeline.
- A test issue will be auto-created on the `harvester/tests` repo when moving the `harvester/harvester` issue to either the `review, ready-for-testing or testing` pipeline. When the issue contains a `not-require/test-plan` label it will be bypassed.
   -  the test template is defined in the [harvester/test repo](https://github.com/harvester/tests/blob/main/.github/ISSUE_TEMPLATE/test.md).

**Comment by noahgildersleeve** [comment]
Tested by moving ticket into ready for testing pipeline. Checklist was attached and task was created at  https://github.com/harvester/tests/issues/238 . Closing as fixed.
