### ISSUE TITLE
[FEATURE] choose disk by label or something

### ISSUE THREAD

**Issue by szthanatos** [harvester/harvester#1820]
**Is your feature request related to a problem? Please describe.**
I use Harvester on a PC with 2 disk -- a 256G NVME SSD & a 1T SATA HDD.
I can add both disk in host management, but can't choose which disk my vm's volume will use.

**Describe the solution you'd like**
I think it's a good idea to give disk labels, 
so when you create a VM, you can use labels to make the volume using right disk.

Longhorn already support this feature([storage-tags](https://longhorn.io/docs/1.2.3/volumes-and-nodes/storage-tags/)).

Just expose it in harvester's UI.

**Comment by bk201** [comment]
Perhaps it's similar to https://github.com/harvester/harvester/issues/2147

**Comment by guangbochen** [comment]
Close as this is duplicate with https://github.com/harvester/harvester/issues/2147, feel free to reopen it if u have different concerns, thanks.
