### ISSUE TITLE
[BUG] Cluster CPU reserved is not correct when on of node power off

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1821]
**Describe the bug**

CPU reserved is not correct when one of the nodes power off.

**To Reproduce**

1. Install harvester with at least 2 nodes()
2. Create a VM on host A
3. Power off host B and wait until it state becomes 'Unavailable'

**Expected behavior**

Cluster CPU reserved should be the same as node CPU reserved.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
![image](https://user-images.githubusercontent.com/18737885/149488840-62d5067e-648d-47f8-9405-c3d3df770cb8.png)
![image](https://user-images.githubusercontent.com/18737885/149489351-5a979237-a572-4055-95de-41c4f60790aa.png)

**Comment by lanfon72** [comment]
Verified the bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/150682013-5103f466-d00b-45af-b3f1-549fe0465c0f.png)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-1be9cb5e-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Create Image for VM creation
3. Create VM on `host 1` then start it.
4. Power off `host 2` and wait its **State** become **Unavailable**
5. Navigate to _Dashboard_ Page, **Capacity** of **CPU** should update the calculation of remaining **Active** Hosts as `<Total_Reserved>/<Total_CPUs>`
