### ISSUE TITLE
[BUG] Node disk manager should prevent too many concurrent disk formatting occur within a short period

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#1831]
**Describe the bug**
Node disk manager should have burst control to prevent too many concurrent disk formatting occur within a short period.

**To Reproduce**
1. See https://github.com/harvester/node-disk-manager/pull/23#discussion_r782325562

**Expected behavior**
Limit the maximum amount of concurrent format being executed within a period of time.

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by weihanglo** [comment]
We could use something like [workqueue](https://pkg.go.dev/k8s.io/client-go/util/workqueue) for this feature. Just beware of race conditions of updatings blockdevice CR. At this moment, we should do our best to consolidate all blockdevice updating logic within [`OnBlockDeviceChange`](https://github.com/harvester/node-disk-manager/blob/85c6bae556866724748c24c90716f65a7052b588/pkg/controller/blockdevice/controller.go#L92). All the other places should be limited their operations to only enqueue updates.

**Comment by lanfon72** [comment]
Hi @Vicente-Cheng, could you help update test plan for this issue?
I saw [the comment](https://github.com/harvester/node-disk-manager/pull/37#issue-1247664430) but there still have some questions:
1. How **many** additional disks will hit the concurrent count, is it user configurable? if so, how to configure it?
2. What's the default concurrent count?
3. this (quote below) more like console behavior, does it able to be executed on dashboard?
> Simultaneously set all `blockdevices` resource under namespace `longhorn-system` with `spec.fileSystem.forceFormatted = true` and `spec.fileSystem.provisioned = true`

**Comment by Vicente-Cheng** [comment]
> Hi @Vicente-Cheng, could you help update test plan for this issue? I saw [the comment](https://github.com/harvester/node-disk-manager/pull/37#issue-1247664430) but there still have some questions:
> 
> 1. How **many** additional disks will hit the concurrent count, is it user configurable? if so, how to configure it?

It depends on your number of concurrent ops, you could use `--max-concurrent-ops` to configure it. If you do not config, the default value is `5`. We should add the number of disks is bigger than `--max-concurrent-ops` then you could check the related logs described as original pull requests. 

> 2. What's the default concurrent count?

The default value is `5`.

> 3. this (quote below) more like console behavior, does it able to be executed on dashboard?
> 
> > Simultaneously set all `blockdevices` resource under namespace `longhorn-system` with `spec.fileSystem.forceFormatted = true` and `spec.fileSystem.provisioned = true`

I thought that the `forceFormatted` option is on disk-related GUI each time. Then I am not sure about the `provisioned` option. Seems like we could not set it up on the dashboard.  I will check it again later.

Hi @lanfon72, 

I reply directly to your questions above. If you still have any questions, feel free to let me know :)

**Comment by lanfon72** [comment]
Verified not fixed.

The `node-disk-manager` keeping requeuing devices, and no disks formatted successfully.
Dashboard info:
![image](https://user-images.githubusercontent.com/5169694/174996723-2f739bb9-6bc5-4c98-9c0d-02a485a93f5d.png)
Console Info:
![image](https://user-images.githubusercontent.com/5169694/174997958-1aac9f08-c881-4bfb-9501-107a0f68d258.png)
Vagrant disk configuration:
![image](https://user-images.githubusercontent.com/5169694/174998535-b9cafa75-e675-4638-b0d7-36ca27cde8cd.png)
ndm log:
[ndm.log](https://github.com/harvester/harvester/files/8956396/ndm.log)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-96b90714-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any node having at least 6 additional disks
2. Login to console and execute command to watch node-disk-manager log
    (By executing `kubectl logs -f -n harvester-system harvester-node-disk-manager-<RandomID>`)
3. Login to dashboard then navigate and edit host to add multiple disks
4. In the console log, should display `Hit maximum concurrent count. Requeue device <device id>`
5. In the dashboard, disks should be added successfully.

**Verify Steps** will be update when it comes **testing** again.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

- [x] exceed the maximum, there should have requeue devices which equals the exceeds
- [x] hit the maximum, there should not have requeue devices
- [x] less than maximum, there should not have requeue devices

![image](https://user-images.githubusercontent.com/5169694/177324553-3b4800b2-9db9-45ec-a3cf-a630acb384cf.png)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-08af3d7c-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any node having at least 6 additional disks
2. Login to console and execute command to update log level to `debug` and `max-concurrent-ops` to `1` (On KVM environment, we have to set to `1` to make sure the _requeuing_ will happen.)
    - `kubectl patch ds -n harvester-system harvester-node-disk-manager --type=json -p'[{"op":"replace", "path":"/spec/template/spec/containers/0/command", "value": ["node-disk-manager", "--debug", "--max-concurrent-ops", "1"]}]'`
3. Watching log output by executing `kubectl get pods -A | grep node-disk | awk '{system("kubectl logs -fn "$1" "$2)}'`
4. Login to dashboard then navigate and edit host to add more than `1` disks
5. In the console log, should display `Hit maximum concurrent count. Requeue device <device id>`
6. In the dashboard, disks should be added successfully.
7. Login to console and execute command to update log level to `debug` and `max-concurrent-ops` to `2`
    - `kubectl patch ds -n harvester-system harvester-node-disk-manager --type=json -p'[{"op":"replace", "path":"/spec/template/spec/containers/0/command", "value": ["node-disk-manager", "--debug", "--max-concurrent-ops", "2"]}]'`
8. Watching log output by executing `kubectl get pods -A | grep node-disk | awk '{system("kubectl logs -fn "$1" "$2)}'`
9. Login to dashboard then navigate and edit host to add `2` disks
10. In the console log, there should not display `Hit maximum concurrent count. Requeue device <device id>`
11. In the dashboard, disks should be added successfully.
12. Login to console and execute command to update log level to `debug`
    - `kubectl patch ds -n harvester-system harvester-node-disk-manager --type=json -p'[{"op":"replace", "path":"/spec/template/spec/containers/0/command", "value": ["node-disk-manager", "--debug"]}]'`
13. Watching log output by executing `kubectl get pods -A | grep node-disk | awk '{system("kubectl logs -fn "$1" "$2)}'`
14. Login to dashboard then navigate and edit host to add less than `5` disks
15. In the console log, there should not display `Hit maximum concurrent count. Requeue device <device id>`
16. In the dashboard, disks should be added successfully.
