### ISSUE TITLE
Support Data Sources in the Terraform Provider

### ISSUE THREAD

**Issue by phillipsj** [harvester/harvester#1838]
**Is your feature request related to a problem? Please describe.**

There aren't currently any data sources listed as being supported by the Terraform provider. It would be a nice feature if support was added for pulling information about an existing resource. Here is the current example.

```HCL
resource "harvester_image" "k3os" {
  name      = "k3os"
  namespace = "harvester-public"

  display_name = "k3os"
  source_type  = "download"
  url          = "https://github.com/rancher/k3os/releases/download/v0.20.6-k3s1r0/k3os-amd64.iso"
}

resource "harvester_virtualmachine" "k3os" {
  depends_on = [harvester_image.k3os, harvester_network.vlan1]
  name        = "k3os"

  disk {
    name       = "cdrom-disk"
    type       = "cd-rom"
    size       = "10Gi"
    bus        = "sata"
    boot_order = 2

    image       = "harvester-public/k3os"
    auto_delete = true
  }
}
```

**Describe the solution you'd like**

If a data source was available, then I could use an existing image that already exists. This would also give more fine grained control over which images could be allowed.

```HCL
data "harvester_image" "k3os" {
  name      = "k3os"
  namespace = "harvester-public"
}

resource "harvester_virtualmachine" "k3os" {
  name        = "k3os"

  disk {
    name       = "cdrom-disk"
    type       = "cd-rom"
    size       = "10Gi"
    bus        = "sata"
    boot_order = 2

    image_id    = data.harvester_image.k3os.id
    auto_delete = true
  }
}
```

**Comment by futuretea** [comment]
**Test plan**:
1. Create test resources in Harvester cluster (clusternetwork,image,network,ssh_key,virtualmachine,volume)
1. Use the master head docker image for testing refer to this [wiki page](https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing)
1. Use terraform configurations refer to [data source examples](https://github.com/harvester/terraform-provider-harvester/tree/master/docs/data-sources) and the created test resouces in step1
1. Get resources states by `terraform show`

**Comment by lanfon72** [comment]
pending on the fix https://github.com/harvester/terraform-provider-harvester/pull/29

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-bfd6a8a9-head**
* **ui-source** Option: **Auto**
* terraform-provider-harvester Version: [05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf](https://github.com/harvester/terraform-provider-harvester/commit/05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf)

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Spawn Docker container environment for terraform (based on https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing)
4. Create the `image.tf` file as below, update `<THE_IMAGE_NAME>` then execute `terraform apply`
```terraform
data "harvester_image" "k3os" {
  name      = "<THE_IMAGE_NAME>"
  namespace = "default"
}

resource "harvester_virtualmachine" "k3os" {
  name        = "k3os"

  disk {
    name       = "disk-0"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image    = data.harvester_image.k3os.id
    auto_delete = true
  }

 network_interface {
    name = "nic1"

 }
}
```
5. The VM **k3os** should be created
6. The VM's volume should be the assigned image
7. The VM should start successfully
