### ISSUE TITLE
[FEATURE] Support provisioning raw block devices directly as extra disks for Harvester hosts

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#1839]
**Is your feature request related to a problem? Please describe.**
Support provisioning raw block devices directly as extra disks for Harvester hosts.

Currently, provisioning a raw block device directly is impossible in Harvester. Whne one is trying to provision a raw block device, the node disk manager automatically creates a single root partition on that block device and use the partition instead. It should be no harm to use the raw block device directly and it can also reduce the steps and complexity of the current flow to provision disks.

**Describe the solution you'd like**
Do not perform partition automatically when user want to provision raw block device as a whole. If the user wants to provision partitions instead of raw blocks, they can still partition them manually

**Describe alternatives you've considered**
Keep the current behavior.

**Additional context**

**Comment by weihanglo** [comment]
## UI Change

According to https://github.com/harvester/node-disk-manager/pull/26#pullrequestreview-886896073, "Add Disk" dropdown menu should only show available devices with `blockdevice.status.deviceStatus.details.deviceType == disk`.

For the default value of `Force Formatted` option, here are the rules:

- Unchecked by default and **cannot** be modified by user
  - `blockdevice.status.deviceStatus.FileSystem.LastFormattedAt != null`
- Checked by default and **cannot** be modified by user
  - `blockdevice.status.deviceStatus.FileSystem.LastFormattedAt == null`
  - AND `blockdevice.status.deviceStatus.fileSystem.type == ""`
- Checked by default and **can** be modified by user
  - `blockdevice.status.deviceStatus.FileSystem.LastFormattedAt == null`
  - AND `blockdevice.status.deviceStatus.fileSystem.type == ext4 or XFS`


Other parts of the UI remains unchanged. The already provisioned disk with `deviceType == part` should continue being provisioned as extra disks for backward compatibility.

For example, the dropdown menu in the image below must display only `/dev/sda`, `/dev/sdd`, and `/dev/sdf`. And partitions such as `/dev/sdd1` and `/dev/sdf1` should be removed.

![](https://user-images.githubusercontent.com/5047724/154406840-018adf9a-8006-4711-be14-14af1709bcf0.png)

cc @n313893254

**Comment by WuJun2016** [comment]
Hi, @weihanglo  The frontend pr has been merged, please help test it and move it to ready-for-testing.  thanks.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-da3f1778-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with Any Nodes which had raw disk (including WWN)
2. Login to Dashboard then Click *Edit Config* of the host
3. Navigate to Disks, raw disks should be displayed in the dropdown list of **Add Disk**
4. Add one of disks then click *Save*
5. Added Disk should be `provisioned` and `Schedulable` in the view of Disks
6. Login to console, and execute `lsblk -f`
7. Added Disk should be mounted
8. Reboot the node
9. Added Disk should be mounted as the same
