### ISSUE TITLE
[BUG]  The cpu/memory/storage chart does not show data

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1841]
**Describe the bug**

Login to harvester with member role, the cpu/mem/storage chart on the dashboard home page is empty, and there is no node information on the host list page.
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/2f447209-f703-4dae-a09f-b859fdd3c4e4)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/2d3e7d97-9889-4ae1-82ba-b9ac78711ee0)

**To Reproduce**
1.  Create a member user
2.  login with the created member user

**Expected behavior**

When the user does not have access to the node, the host page and related chart should be hidden

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-1a861fc1-head` and Rancher `v2.6-948355cc596b8466a77aec5276640425a5935852-head`.
## Verification Steps
1. Create new user in Rancher
2. Import Harvester
3. Add new user as member user in RBAC in Harvester through virtualization management console
4. Log into Rancher with new user
5. Check dashboard for Harvester through Rancher RBAC login
![Screenshot from 2022-02-07 13-36-59](https://user-images.githubusercontent.com/83787952/152876443-7a93947b-62c5-4426-8e70-9dd4dd2fae37.png)

## Notes
I used external preferred ui-index and changed it to the Harvester one for validating the change in the Harvester dashboard.
