### ISSUE TITLE
[BUG] Incorrect memory usage in VM metrics

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#1842]
**Describe the bug**
The usage showing in the dashboard is not the same as the usage in guest OS

**To Reproduce**
1. Create a 8Gi VM
2. Write some data, e.g., `dd if=/dev/zero of=testfile bs=1024 count=5024000`
3. Check memory usage. 
```
$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.7Gi       166Mi       4.6Gi       1.0Mi       2.9Gi       7.2Gi
Swap:            0B          0B          0B
```
4. Check VM metrics in the VM detail page
![image](https://user-images.githubusercontent.com/5697937/150108074-5ad7efbf-8a17-4709-9f0f-b4739db360f7.png)

**Environment:**
 - Harvester ISO version: v1.0.0

**Comment by slickwarren** [comment]
just an update - still seeing this on v1.0.1-rc1

**Comment by w13915984028** [comment]
```
Create a 8Gi VM
Write some data, e.g., dd if=/dev/zero of=testfile bs=1024 count=5024000
Check memory usage.
$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.7Gi       166Mi       4.6Gi       1.0Mi       2.9Gi       7.2Gi
Swap:            0B          0B          0B

```
**Per investigation, there may be some mis-understanding here:**

The caculation of used memory is :  1 - (free/total) = 1 - (4.6/7.7) = 1-59.7%,  roughly  40%;   it includes not only the `"used"` part, but also the `"shared"` and ` "buff/cache"`

Important thing is,  the` "buff/cache"`, which is 2.9Gi,  hot memory used by command dd `dd if=/dev/zero of=testfile bs=1024 count=5024000`

for example, the following dd command  caused `"free"` memory decreased dramatically, notice the difference

![image](https://user-images.githubusercontent.com/31133476/163154751-dfe4221d-514b-44d6-bef2-568f7f16e0bc.png)

![image](https://user-images.githubusercontent.com/31133476/163154862-55b642d5-8c56-4472-b982-dcd0941a7b14.png)

used increased to:
![image](https://user-images.githubusercontent.com/31133476/163164292-31a68c78-9add-4c8e-b4a6-6a0eab6958f7.png)

**Comment by w13915984028** [comment]
@slickwarren could you please double check it,  use `1 - (free/total)` to compute the used memory, thanks.

**Comment by w13915984028** [comment]
**How "used" memory is calculated:**


https://github.com/kubernetes-monitoring/kubernetes-mixin/issues/234#issuecomment-521929614

node_exporter mixin doesn't have this problem as it already uses memory calculation mentioned in https://github.com/prometheus-operator/prometheus-operator/issues/1310#issue-320923699 as seen in https://github.com/prometheus/node_exporter/blob/master/docs/node-mixin/dashboards/node.libsonnet#L77-L85


![image](https://user-images.githubusercontent.com/31133476/163350068-d6d584c3-3ea2-4c25-a139-b4391ed2f9d6.png)

The related explaination:
```
Many load balancing and workload placing programs check /proc/meminfo to
estimate how much free memory is available.  They generally do this by
adding up "free" and "cached", which was fine ten years ago, but is
pretty much guaranteed to be wrong today.
```
https://github.com/prometheus-operator/prometheus-operator/issues/1310#issuecomment-387216413

**Comment by w13915984028** [comment]
**Conclusion:**

The current implementation of "memory usage" of prometheus/grafana, is aligned with industry main stream calculation.

The "memory usage" is via: `1 - (free/total)`,  **NOT** `used/total`

```
(notice: total, used, free ...)
$ free -h
              total        used        free      shared  buff/cache   available
Mem:          7.7Gi       166Mi       4.6Gi       1.0Mi       2.9Gi       7.2Gi
Swap:            0B          0B          0B
```

Not an issue, will not fix.

**Comment by w13915984028** [comment]
Will write "memory usage" calculation into Harvester DOC.

**Comment by guangbochen** [comment]
Close as the doc PR  https://github.com/harvester/docs/pull/14 is merged and added a more detailed explanation of the metrics calculation per https://docs.harvesterhci.io/v1.0/monitoring/monitoring/#vm-detail-metrics.
