### ISSUE TITLE
Modify a disk/network could affect the Add Disk/Add Network Interface button

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#185]
**Steps to reproduce:**
1. On the VM create page, modify a disk or a network interface
2. Once the popup window is open, check the `Add Disk`/`Add Network Interface` button

**Results:**
The `Add Disk`/`Add Network Interface` button turns to `Edit Disk`/`Edit Network Interface` button
![image](https://user-images.githubusercontent.com/57614736/94412853-e43ae600-01ac-11eb-97f7-197adf31e8f9.png)

**Comment by gitlawr** [comment]
Validated
