### ISSUE TITLE
[Enhancement] Remove duplicated images on the installer dependency bump

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1851]
**Is your feature request related to a problem? Please describe.**
Currently, the `bump-rancher` script on the installer side doesn't know how to remove duplicated images list in the `rancher image-list` file. We need to do this manually.

**Describe the solution you'd like**
Consider enhancing the bump script, check if images are duplicated, and give a warning message in case existing.

**Additional context**
e.g., https://github.com/harvester/harvester-installer/pull/219

**Comment by weihanglo** [comment]
I wonder how to determine if an image is really a duplicate. What if the version we consider as duplicate is required for that exact version?

**Comment by guangbochen** [comment]
Close as the best option in the current stage is still to check it manually.
