### ISSUE TITLE
[BUG] Can't install additional packages if guest agent installed

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#1856]
**Describe the bug**
If "Install guest agent" is ticked on the Advanced Options page when creating a Virtual Machine, any additional packages added to the User Data section of the Cloud Config page are silently removed with just the original qemu-guest-agent left to be installed.

The same is also true if editing the config to add in additional packages of an existing VM (although probably too late at that point since VM has been created).

**To Reproduce**
1. Create a new VM - I used openSUSE Leap 15.3 JeOS (OpenStack image)
2. On the Advanced Options page ensure "Install guest agent" is ticked (default)
3. Add additional packages to the User Data section - I used docker and apparmor-parser
4. Click the Create button
5. Edit Config of your newly created VM
6. Note the packages in the User Data section on the Advanced Options page - only qemu-guest-agent will be listed with others AWOL

**Expected behavior**
Regardless of whether "install guest agent" is ticked, you should be able to add additional packages to be installed

**Support bundle**
[supportbundle_af6572d3-42b1-43d1-8145-ce13e92f0e69_2022-01-21T15-22-29Z.zip](https://github.com/harvester/harvester/files/7914762/supportbundle_af6572d3-42b1-43d1-8145-ce13e92f0e69_2022-01-21T15-22-29Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with 2x Intel NUC7i7DNxE

**Additional context**
Installing other packages used to be possible, seems installing the guest agent is enforcing just that.

A workaround is to include the appropriate command to install additional packages as one of the runcmd statements but it's a pain!

**Comment by simonflood** [comment]
It wouldn't be so bad if the QEMU Guest Agent actually installed cleanly but on openSUSE it doesn't - see #1833 

My "workaround" with openSUSE Leap 15.3 JeOS image for OpenStack is to not tick "install guest agent" as the qemu-guest-agent package is already installed by default with the correct service enabled and running. With "install guest agent" unticked packages is left untouched and works as expected.

**Comment by lanfon72** [comment]
Verified this issue has been fixed.

![image](https://user-images.githubusercontent.com/5169694/154220902-c77ab2cc-1f6d-4d41-8aab-b688572a31f3.png)
![image](https://user-images.githubusercontent.com/5169694/154220940-e0245e7c-9b2f-49ef-a894-0c2ffca31776.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-9091d7d0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Follow **Reproduce Steps** in https://github.com/harvester/harvester/issues/1856#issue-1110592636
