### ISSUE TITLE
MTU size on mgmt Interface (no Cluster Metrics, no Grafana)

### ISSUE THREAD

**Issue by cybaware** [harvester/harvester#1859]
Hi

I have added a third node to a Harvester cluster. Now the dashboard shows an "Events" section but no "Cluster Metrics" section. Also the link to Grafana is gone. I did not change anything, just added the third node.

Why do I no longer see a graph for Cluster Metrics?

I have already restarted all nodes, no display to Cluster Metrics.

Harvester 1.0.0 on bare metal
Clean install
logged in as admin

Best Regards

**Comment by cybaware** [comment]
![image](https://user-images.githubusercontent.com/11486351/150703357-32b3a50f-a841-479d-a904-51ab9e759845.png)

**Comment by guangbochen** [comment]
@kinchlo can u please help to upload a generated support bundle via clicking the support page on the left bottom corner.

**Comment by cybaware** [comment]
Hello Guangbochen

Thank you for your message

I encountered another problem as I could not download the support package 0_o. 
For now I was able to fix the problem, it has to do with MTU. 
Now I also see the "Cluster Metrics" section in the dashboard again. 

Node3 is connected through an IPsec tunnel. Since I had problems with some applications, I calculated the header and set the MTU value for the IPsec tunnel to 1444 Bytes. Now Harvester doesn't seem to be able to handle this, or the IPsec endpoints were processing the packets incorrectly.

I found this out because in the firewall log all UDP packets from Node3 were exactly 1444Bytes. I have now set MTU to 1500 and downgraded MSS since the problems i had with other applications were affecting TCP connections.
Now I see that the cluster metrics section and Grafana are working again. 

I dare not say that Harvester caused the problem, but it could be that Harvester gets problems when the UDP packets are segmented by the firewall.

It is interesting to me that the whole cluster became unstable just because one node had a "bad" connection.

Now I can also download the support package. I will be happy to provide more information should it be of any help.
[supportbundle_96ed9837-06c7-4336-bed1-793597bb6632_2022-01-24T15-37-44Z.zip](https://github.com/harvester/harvester/files/7927061/supportbundle_96ed9837-06c7-4336-bed1-793597bb6632_2022-01-24T15-37-44Z.zip)

BR
k

**Comment by cybaware** [comment]
i did more tests::::

I have tested different MTU values (1420,1440,1444,1460,1480,1500)

The Cluster Metrics section works only if the MTU value for the IP/UDP packet is 1500Byte. With MTU values <1500Byte Cluster Metrics section and Grafana does not work. Grafana and Cluster Metrics section work only if IP/UDP MTU =1500Byte (I didn't test higher MTU). This also means that packets with IPsec header are >1500Byte and segmented in WAN/Internet.

additional information:::::
I assume that the UDP traffic is the Grafana traffic. 
I have set the MTU value on the IPsec interface.
WAN interface has always had 1500 by default.
At the moment I have no impact. Except the IPsec performance is a bit worse because the packets with IPsec header now exceed 1500MTU and thus are segmented by the WAN interface.
i use VTI (route-based) IPsec VPN (s2s)

I hope I could explain it.

BR
k

**Comment by guangbochen** [comment]
thanks for the detailed info, I think the issue is caused by the default MTU value configured by the `harvester-mgmt` bond(this is also the internal cluster management network) which is set to 1500, so if u prefer to use a different MUT config on your environment u should update this value accordingly.

```
6: harvester-mgmt: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master harvester-br0 state UP group default qlen 1000
    link/ether b8:ca:3a:f9:9b:5c brd ff:ff:ff:ff:ff:ff
    inet 172.16.4.3/16 brd 172.16.255.255 scope global harvester-mgmt
```

As an enhancement, I think we need to expose this one as a configuration via the `harvester-installer` and the harvester configuration file.

**Comment by cybaware** [comment]
i tried to add MTU to my harvester-mgmt interface with following line:  MTU='1444' to the file:
(/etc/sysconfig/network/ifcfg-harvester-mgmt) 
but it is not persitent, means my new line with the MTU Value is gone after reboot.
i was thinking its the correct file for persistency. Can you Please provide me the information where i have to add the MTU Value with persitency.

i really appreciate it
Thank you

**Comment by cybaware** [comment]
am not sure if it is correct,

I have changed the MTU value here:
/oem/99_custom.yaml

After a reboot the new MTU value remained. :)


The entry is also present here /etc/sysconfig/network/ifcfg-harvester-mgmt. So the script from 99_custom.yaml pushes the config to /etc/sysconfig/network/ifcfg-harvester-mgmt.
Would be great if someone could verify it.

99_custom content

> name: Harvester Configuration
> 
> stages:
>   initramfs:
>   - commands:
>     - sed -i 's/^NETCONFIG_DNS_STATIC_SERVERS.*/NETCONFIG_DNS_STATIC_SERVERS="*.*.*.*"/'
>       /etc/sysconfig/network/config
>     files:
>     - path: /etc/rancher/rancherd/config.yaml
>       permissions: 384
>       owner: 0
>       group: 0
>       content: |
>         server: https://*.*.*.*:8443
>         role: agent
>         token: "******************"
>         kubernetesVersion: v1.21.7+rke2r1
>         labels:
>          - harvesterhci.io/managed=true
>       encoding: ""
>       ownerstring: ""
>     - path: /etc/rancher/rke2/config.yaml.d/90-harvester-agent.yaml
>       permissions: 384
>       owner: 0
>       group: 0
>       content: |2+
> 
>       encoding: ""
>       ownerstring: ""
>     - path: /etc/sysconfig/network/ifcfg-harvester-mgmt
>       permissions: 384
>       owner: 0
>       group: 0
>       content: |
>         STARTMODE='onboot'
>         BONDING_MASTER='yes'
>         BOOTPROTO='static'
> 
>         MTU=1400
> 
>         IPADDR=*.*.*.*
>         NETMASK=255.255.0.0
>         BONDING_SLAVE_0='eno1'
>         BONDING_SLAVE_1='eno2'
> 
>         BONDING_MODULE_OPTS='miimon=100 mode=802.3ad '
> 
>         DHCLIENT_SET_DEFAULT_ROUTE='yes'
>       encoding: ""

**Comment by cybaware** [comment]
Have now set all nodes to MTU 1400. Firewalls logs all look good. No segmentation on LAN side and no segmentation on WAN side. 

I also restarted all nodes again.

Unfortunately the Cluster Metrics and Grafana section is not displayed again.

I will generate a new support package tomorrow

**Comment by cybaware** [comment]
Hi, after some days of testing and running, i think there is a problem inside harvester to handle packets with Size MTU <1500 for example 1400Bytes. (UDP)
All my nodes have MTU1400.
No Metrics Data or Grafana is shown on the dashboard. Node 1 and Node 2 are in the same Layer 2 subnet. Node 3 is connected over a routed VPN. 
in the Attachement, a new support packet. 

Please let me know if you need more information.
[supportbundle_96ed9837-06c7-4336-bed1-793597bb6632_2022-01-31T15-54-12Z.zip](https://github.com/harvester/harvester/files/7972214/supportbundle_96ed9837-06c7-4336-bed1-793597bb6632_2022-01-31T15-54-12Z.zip)

@johnliu55tw
@guangbochen


Best Regards
k

**Comment by cybaware** [comment]
![image](https://user-images.githubusercontent.com/11486351/151888456-73dcc4bb-7e51-4a8e-8a63-c64bc0cff73f.png)

**Comment by cybaware** [comment]
![image](https://user-images.githubusercontent.com/11486351/151889902-07dcf460-d908-4a40-b536-e114316952cc.png)

**Comment by johnliu55tw** [comment]
Hi @kinchlo, we will make MTU configurable in the next release (https://github.com/harvester/harvester/issues/1934), but currently we won't support connecting nodes to the cluster using VPN tunnels.

**Comment by cybaware** [comment]
> Hi @kinchlo, we will make MTU configurable in the next release (#1934), but currently we won't support connecting nodes to the cluster using VPN tunnels.

thank you!
