### ISSUE TITLE
[Question] Update existing Harvester Configuration

### ISSUE THREAD

**Issue by jadenlemmon** [harvester/harvester#1862]
I have a question about updating an existing Harvester configuration. 

For example, if I want to change the management address on an existing host, what is the best practice for doing so? 

I see in the docs where it talks about the configuration https://docs.harvesterhci.io/v1.0/install/harvester-configuration/. But how do I update an existing configuration, not a new install? 

I don't really see in the docs how to edit existing configurations. Would appreciate any help here! TIA

**Comment by bk201** [comment]
The harvester configuration is stored as `/oem/harvester.config` for reference after installation. Changing this file has no effect after a system is provisioned.
Behind the scene, the config file is converted into cOS cloud-init file `/oem/99_custom.yaml`, so if we want something on the system to change, that's the right place to go.

Please be aware we don't support and didn't test changing management addresses before.

**Comment by jadenlemmon** [comment]
Thanks for the help!
