### ISSUE TITLE
[Question]install harvester v1.0 mount /tmp/mnt/STATE cannot find in /etc/fstab

### ISSUE THREAD

**Issue by liusl12** [harvester/harvester#1863]
![image](https://user-images.githubusercontent.com/29368695/150897899-81c98630-980d-4035-a385-00536858e0ef.png)

**Comment by bk201** [comment]
@liusl12 Does this always happen? Does re-installing solve the problem?

Could you change to second TTY (CTRL+ALT+F2) and log in with rancher/rancher to dump output of these commands:
- `sudo lsblk`
- `sudo blkid`
- `sudo dmesg`

Thanks.
