### ISSUE TITLE
[FEATURE] Support bundle for a single node (Live/Installed)

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1864]
**Is your feature request related to a problem? Please describe.**

It's hard to debug a failed installation or un-provisioned node without asking for much info from users.
e.g., https://github.com/harvester/harvester/issues/1863

**Describe the solution you'd like**

It would be nice to add a command to generate a node support bundle for a node that is in live mode or installed mode.

We can leverage or extend node collector https://github.com/rancher/support-bundle-kit/blob/master/hack/collector-harvester. Another idea is to use OpenSUSE supportutils (supportconfig).

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
@bk201 I've had a chance to validate this:

## The Setup:
- VM in virt-manager, 8 core, 18GiB RAM, 200GiB disk

## The ISO Used For Install Test's `md5sum`:
```
4fe096476e1205c05096f4be70cb0db8  harvester-master-amd64.iso
```

## Results
Following the steps I was able to replicate the test strategy and validate that the support config gets generated and provides an available path.
I validated that the `.txz` can be extracted with `tar xvf`. 


![Screenshot from 2022-04-27 15-33-00](https://user-images.githubusercontent.com/5370752/165647582-d487b4ec-dcf1-451d-a063-6502ebd97012.png)
![Screenshot from 2022-04-27 15-02-39](https://user-images.githubusercontent.com/5370752/165647594-b3529472-e606-4d12-8953-54ff5d86c00e.png)

This looks good to me :smile:

**Comment by irishgordo** [comment]
Opened PR to update manual test doc.
Will close this ticket out in the meantime
