### ISSUE TITLE
[Question] install v1.0 loading image spend too much time, almost 1hour

### ISSUE THREAD

**Issue by liusl12** [harvester/harvester#1865]
![image](https://user-images.githubusercontent.com/29368695/150962723-c7d1b91d-be1c-4890-9986-fb382584ecc6.png)

**Comment by liusl12** [comment]
![image](https://user-images.githubusercontent.com/29368695/150962897-64cc5b9c-dfe3-480c-93aa-7a40c8379507.png)
![image](https://user-images.githubusercontent.com/29368695/150962960-d96cafb6-6b96-46a2-a617-278483491b16.png)
![image](https://user-images.githubusercontent.com/29368695/150963009-d0b61778-37f1-4255-b9eb-2f9277268a8d.png)

**Comment by liusl12** [comment]
![image](https://user-images.githubusercontent.com/29368695/150967005-77498340-3265-4dd8-a16c-c2ca127eb14f.png)
checking too slow

**Comment by bk201** [comment]
@liusl12 Is the `sda` a HDD or SSD? What's the disk bus controller? SATA or SAS?  
From the `dmesg` output, we can see it actually took very long between certain mounts (873 -> 2472), there might be some I/O issues to the disk.

Sharing file `/run/cos/target/rke2.log` when loading images might help too.

**Comment by liusl12** [comment]
@bk201 install success, but spend 1 hour😄

**Comment by simonflood** [comment]
Surprisingly I've hit this issue myself although my installs got "stuck" on checking 32 images. After an hour I restarted & tried again - 4.5 hours later no progress! So I restarted & tried yet again leaving it overnight - 18 hours! Didn't matter whether I tried joining my existing cluster or creating new. I grabbed all the logs but can't see anything.

Given this was with a second NUC7i7DNKE with a Crucial P5 1TB NVMe SSD I knew it worked so was beginning to suspect the hardware though both NUC and SSD seemed okay in other combos. Searching for Intel NUC slow SSD I found https://www.intel.co.uk/content/www/uk/en/support/articles/000029915/intel-nuc.html and I thankfully the documented fix of reflashing the NUC's BIOS using the Security Jumper recovery method worked and a test install of Harvester 1.0.0 has just successfully completed!

**Comment by w13915984028** [comment]
@liusl12 Any updates, how did you solve it? thanks.

**Comment by liusl12** [comment]
可以看看你的磁盘性能咋样？我最后换了台物理机就好了，我用过几台物理机 有的快又很慢，感觉像是磁盘的性能问题


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "harvester/harvester"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月6日(星期三) 晚上8:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [harvester/harvester] [Question] install v1.0 loading image spend too much time, almost 1hour (Issue #1865)





 
@liusl12 Any updates, how did you solve it? thanks.

**Comment by w13915984028** [comment]
The issue was caused by slow storage I/O. Updating BIOS or using qualified storage solves it.

Close issue.
