### ISSUE TITLE
There is no prompt after the session expires. You need to refresh manually to return to the login page

### ISSUE THREAD

**Issue by wangpan-hqu** [harvester/harvester#1867]
**Describe the bug**

There is no prompt after the session expires. You need to refresh manually to return to the login page
**To Reproduce**
1. Log in to harvester
2. Wait about ten hours
3. No response when clicking on the page
4. Manually refresh and return to the login page

**Expected behavior**
Click the page prompt to automatically return to the login page after the session expires
**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
Hi @mantis-toboggan-md  I created an issue in the rancher repo that we can rebase to harvester after the upstream fix, thanks!
https://github.com/rancher/dashboard/issues/6686

**Comment by WuJun2016** [comment]
It was normal when I tested it. Please QA team to confirm it again.  thanks

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.1.0-rc2`. 

## Verification Steps

1. Navigate to embedded Rancher global settings at `https://<harvesterIp>/dashboard/c/_/settings/management.cattle.io.setting`
2. Edit user auth TTL settings to be 10 mins
![Greenshot 2022-10-11 13 13 25](https://user-images.githubusercontent.com/83787952/195207565-926ced54-0b95-443d-a03b-e2cf4a1f2889.png)
3. Log out of Harvester
4. Log back into Harvester
5. Navigate to Virtual Machines Page
6. Let sit for 15 mins

### Expected Results
- You should be redirected to the Login page and asked to login
![Greenshot 2022-10-11 15 02 04](https://user-images.githubusercontent.com/83787952/195207730-3df4e1fb-3663-4228-abfa-13e03f1e680c.png)
