### ISSUE TITLE
[FEATURE] Switch Harvester components base image to SLE BCI

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#1868]
It's maintained much better than e.g. alpine.

The scope includes all the Harvester components, e.g. cloud provider etc. 

E.g. https://github.com/rancher/rancher/blob/release/v2.6/package/Dockerfile

**Comment by bk201** [comment]
Harvester image list that we might want to switch:
- [x] https://github.com/harvester/harvester
  - [x] rancher/harvester
  - [x] rancher/harvester-upgrade
  - [x] rancher/harvester-webhook
  - [x] rancher/harvester-cluster-repo
- [x] https://github.com/harvester/harvester-installer
- [x] https://github.com/harvester/network-controller-harvester
  - [x] rancher/harvester-network-controller
  - [x] rancher/harvester-network-helper
- [x] https://github.com/harvester/node-disk-manager
  - [x] rancher/harvester-node-disk-manager
- [x] https://github.com/harvester/load-balancer-harvester
  - [x] rancher/harvester-load-balancer
- [x] https://github.com/harvester/cloud-provider-harvester
- [x] https://github.com/harvester/terraform-provider-harvester
- [x] https://github.com/harvester/docker-machine-driver-harvester
- [x] https://github.com/harvester/harvester-csi-driver - will be fixed separately via https://github.com/harvester/harvester/issues/1995
- [x] [rancher/support-bundle-kit](https://github.com/rancher/support-bundle-kit)

**Comment by guangbochen** [comment]
Close as a majority of the Harvester components is migrated to use the SLE BCI image, during the Harvester v1.0.1 regression test we should be able to verify if it will cause any side effects.
