### ISSUE TITLE
[Question]  install complete，restart server，back to install 

### ISSUE THREAD

**Issue by liusl12** [harvester/harvester#1869]
![image](https://user-images.githubusercontent.com/29368695/151106594-0fe0f977-519f-40a4-b843-480025d1a8ea.png)

![image](https://user-images.githubusercontent.com/29368695/151106410-2eaf7852-edc0-4fb1-bbbe-7044ee202e6f.png)

**Comment by wangpan-hqu** [comment]
You should restart from the hard disk instead of CD or USB
