### ISSUE TITLE
[BUG]  Overwritten cloud-config

### ISSUE THREAD

**Issue by dev01d** [harvester/harvester#1871]
**Describe the bug**

It looks like the cloud-config is being overwritten during save with a partial version of the default settings. 

**To Reproduce**
1. Create VM with appropriate resource
2. Paste cloud-config in Advanced Options section
3. Uncheck "Start virtual machine on creation"
4. Click Save
5. Go back to edit config 
6. Select Advanced Options

**Expected behavior**

Cloud-config should not be altered (other than linting) when clicking save.

**Support bundle**

[supportbundle_e5474c55-a444-408f-bf4d-0f680c651c0f_2022-01-26T13-31-14Z.zip](https://github.com/harvester/harvester/files/7942070/supportbundle_e5474c55-a444-408f-bf4d-0f680c651c0f_2022-01-26T13-31-14Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare Metal Dell Precision T5600

**Additional context**

I apologize if this is a duplicate, I couldn't find a similar issue while searching.

Screen recording of issue. 

https://user-images.githubusercontent.com/18254823/151168879-620fe0e6-c97f-41f2-86d9-22f0c0f62e46.mov

**Comment by TachunLin** [comment]
Verified **fixed** on master-9091d7d0-head (02/14). Close this issue.

### Result
Install guest agent will not overwrite the cloud config user data in advanced options.  
![aa](https://user-images.githubusercontent.com/29251855/154092274-7394e7bd-fea6-4246-90c4-efc236cc03aa.gif)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: master-9091d7d0-head (02/14)

### Verify Steps

1. Create VM with basic settings
2. Paste cloud-config user data in advanced options section
3. Uncheck the "Start virtual machine on creation"
4. Check the install guest agent
5. Click Save
6. Edit the VM config
7. Select Advanced Options
8. Do nothing
9. Click Save
10. Edit the VM config again
11. Check the cloud-config user data in advanced options
