### ISSUE TITLE
[FEATURE] harvester api for deploying exporters and collectors

### ISSUE THREAD

**Issue by ravarga** [harvester/harvester#1872]
As an Enterprise organization, it is required to collect and store certain information about our hardware inside a CMDB. In order to collect this information, we created collectors and exporters for Prometheus. 

Collectors for retrieving hardware information and firmware versions.
Exporters for exposing required hardware metrics, like smart metrics of hard drives. (e.g. NVME available spare, and available spare threshold), network interfaces and, network health & quality.

With Harvester being an appliance and not exposing the raw Kubernetes API, we miss the functionality to deploy such tools.

Next to this specific use case, there might be situations in the future where we, because of compliance or regulatory reasons, need to deploy additional containers.

To clarify, we are not looking for a way to deploy workload, but to run administrative, and required tooling as platform administrators.

**Comment by DonThorntonJr** [comment]
use Ansible:
`# ansible all -i "nljharv1," -u rancher -m setup`

**Comment by andrehofman** [comment]
To clarify the enhancement, it would be nice / better if the Harvester API would be made accessible to the "admins" somehow from Rancher for this purpose. Not having this kind of access sucks as it might be necessary to modify the configuration of the components like Prometheus to ship metrics of the platform or install certain log forwarders besides the aforementioned use-case. Think of it as the "local" cluster of Rancher.

**Comment by yasker** [comment]
Based on the internal discussion, we will produce a guideline first to achieve this feature using the existing functionality of Rancher. The basic idea is to create a project/namespace in Harvester with quota and allow users to use it for 3rd party monitoring purposes.

**Comment by futuretea** [comment]
## The administrator operation
1. Create tenants with global permission `Standard User` via the Rancher `Users & Authentication` page
![image](https://user-images.githubusercontent.com/15064560/159168162-920c7c1e-c0e4-4211-ae62-ba5bcfe2baef.png)
![image](https://user-images.githubusercontent.com/15064560/159168174-74355102-d2d9-455a-9c2a-a59e8c945788.png)
![image](https://user-images.githubusercontent.com/15064560/159168180-386e4d89-d842-4477-9af0-757c40054350.png)

2. Access the imported Harvester cluster UI via the Rancher `Virtualization Management` page, 
![image](https://user-images.githubusercontent.com/15064560/159168190-77eafc44-5e66-4c37-9406-978e0db90711.png)
![image](https://user-images.githubusercontent.com/15064560/159168196-172e47c1-3c08-4ad9-964a-29ccf78b5323.png)

3. Create project and namespace via the Harvester `Projects/Namespaces` tab, during creating projects, set project `Resource Quotas` and add users to the project, assign them `Project Owner` permission.
![image](https://user-images.githubusercontent.com/15064560/159168206-fd0b192d-e39e-43da-8265-ac2eb668bcf6.png)
![image](https://user-images.githubusercontent.com/15064560/159168209-b6de1a50-ab59-4265-b627-5cd40f3a358e.png)
![image](https://user-images.githubusercontent.com/15064560/159168213-d415616d-d451-4bdf-8a63-845c3fe8d0af.png)

## The tenant operation
1. Download the Rancher generated Harvester kubeconfig file via Rancher `Virtualization Management` > `Harvester Clusters` > `Download KubeConfig`
![image](https://user-images.githubusercontent.com/15064560/159168224-079ea924-c50d-4b7a-87ed-fd236fdb0e7c.png)

**Comment by guangbochen** [comment]
@ravarga please help to check if https://github.com/harvester/harvester/issues/1872#issuecomment-1073267033 answers your questions, and prefer to close this issue if it does, thanks.

**Comment by bk201** [comment]
@ravarga Please re-open if https://github.com/harvester/harvester/issues/1872#issuecomment-1073267033 doesn't help.
