### ISSUE TITLE
[BUG] Install fails at HostName

### ISSUE THREAD

**Issue by elegasoft** [harvester/harvester#1873]
**Describe the bug**
Install fails at hostname

**To Reproduce**
1. Boot Install ISO
2. Choose Create or Join (doesn't matter)
3. Choose Installation Disk (doesn't matter)
4. Enter Custom HostName and press Enter
5. Install fails and returns you to Step 2

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure: Baremetal with Supermicro X9-DRL-if with E5-2690v2 (x2) or E5-2609 (x2) and any combination of CPUs, I've also tried many SSDs

**Comment by bk201** [comment]
@elegasoft 
When you say after `4. Enter Custom HostName and press Enter, install fails and return to step 2`. Does the installation progress start and the node is rebooted? Or the installer just got back to step 2. Thanks.

**Comment by elegasoft** [comment]
The installer returns to Step 2. There is an audible beep which occurs and a screen flash. If there is a way to debug/access install logs I would be happy to provide that information for you.

**Comment by bk201** [comment]
@elegasoft Does the screen resolution looks small (maybe only 640*480). I wonder if the display area is too small to fit the info text at the bottom or center:

![Screen Shot 2022-01-27 at 10 41 12 AM](https://user-images.githubusercontent.com/1691518/151282387-5e944257-e010-45dd-9b20-9360fcd6cb68.png)

Add `nomodeset` kernel parameter when booting the ISO might fix the resolution issue.


Capturing these logs might help as well. You can change to the second TTY and logging with rancher/rancher:
- `journalctl -u getty@tty1.service`
- `/var/log/console.log`

**Comment by elegasoft** [comment]
Adding nomodeset does not change the behavior and I have no trouble seeing the full screen.

Running `journalctl -u getty@tty1.service` doesn't give me any useful information but you can see for yourself.

![20220126_191231](https://user-images.githubusercontent.com/16218581/151286067-553eceb2-5270-4b2b-a739-718db2fb5edd.jpg)

and the /var/log/console.log is empty

![20220126_191350](https://user-images.githubusercontent.com/16218581/151285727-a6d30b0e-05f2-475f-b225-f0eff01aa86f.jpg)
 
Here's a video of what happens so that you can see it yourself [https://www.youtube.com/watch?v=twidFMXwiYo](https://www.youtube.com/watch?v=twidFMXwiYo)

There is a quick error message flash about invalid dimensions and logging a panic. It does look like the issue may be with the graphics but appending nodemodeset to the install flags doesn't resolve the issue.

**Comment by elegasoft** [comment]
After using the CLR_CMOS jumper to clear the bios and attempting a reinstall without appending nodemodeset I was able to finally get passed that field and completed the install.

**Comment by bk201** [comment]
@elegasoft Good to hear you managed to install it. Could you share what kind of VGA card you have on this machine? Thanks.

**Comment by elegasoft** [comment]
@bk201 Actually, when I first began experiencing the issue I didn't have a GPU installed at all, I was using the integrated VGA. I then tried installs with these cards: GT240, GTX680, GTX760, GTX1060-6GB, RX6600 (non-xt) which all resulted in the same error.  But I believe the video was captured using the GTX680 and a single E5-2609 with only 8GB of RAM, there's more on that GPU later.

Although, I had even cleared the BIOS before trying to boot the installer between a few of the GPU swaps I was still running into the same error.

Finally, I cleared the BIOS 3 times back to back powering it off after a successful POST between each reset. As usual I ensured that Virtualization was enabled and that it was still set for booting "UEFI only" and I believe I left everything else on their defaults before attempting to install it without a GPU again.  The first install attempt I made the mistake of including the 'nomodeset' flag and the error again presented itself again, but letting the installer proceed with the default flags worked without an issue.

After successfully installing I have not tried installing with any of the GPUs on the same board to rule out a BIOS issue, but I noticed that on a later reboot the machine hung with a 2F code indicating a memory error although during my troubleshooting it had previously passed a few hours on memtest86, so this could be a contributing factor. FYI - Installed RAM is 64GB (8x8GB) DDR3 ECC.

Curiously, I was able to perform the install without having to set the 'nomodeset' flag while using the GTX680 on an Asus P9X79 without any issues with both an i7-3730K and one of the E5-2690v2s. 

Not surprisingly, I also tried installing with a cheap Jingsha X79 board without integrated graphics and was never to get passed the error with any GPU, but I know they are hacked BIOS boards so I wasn't expecting much from them anyway other trying to determine if the issue was board specific. 

Somewhat surprising, I was successfully able to install with a Ryzen 3 2200/MSI B350M/12GB.

My next install will be on a HP Proliant DL580 4xE7-4780v2 and 512GB for further testing before moving it to more recent generation staging machines and hopefully eventually into my in-house production environment which has ML GPU work loads. 

Thanks for the help and let me know if I can provide any more info.

**Comment by bk201** [comment]
@elegasoft Thanks for the detailed comments. AMD's graphic driver is open-sourced and included, so users normally see fewer issues when using Radeon cards.

**Comment by 0x1001u** [comment]
> After using the CLR_CMOS jumper to clear the bios and attempting a reinstall without appending nodemodeset I was able to finally get passed that field and completed the install.

I had the same issues. but clean the bios with clk_cmos jumper not work for me! any other way?

**Comment by elegasoft** [comment]
Did you try jumping CLR_CMOS multiple times back to back? Are you on the same motherboard? If so, I can go through exactly what BIOS/UEFI settings worked for me.

**Comment by 0x1001u** [comment]
> Did you try jumping CLR_CMOS multiple times back to back? Are you on the same motherboard? If so, I can go through exactly what BIOS/UEFI settings worked for me.

I did three times jumping clr_cmos.now it work. but I don't know why...

**Comment by 0x1001u** [comment]
> Did you try jumping CLR_CMOS multiple times back to back? Are you on the same motherboard? If so, I can go through exactly what BIOS/UEFI settings worked for me.

thanks!!!

**Comment by ciybe** [comment]
I had the exact same issue on the v1.0.2-rc2 ISO with a Gigabyte GV-N210SL Graphics Card. The resolution was low.
After removing the card and using the onboard graphics, the resolution was higher and the described issue was gone.

**Comment by megabreit** [comment]
Same issue with v1.1.0-rc3 inside of Virtual Box 6.1.40. v1.1.0-rc1 is working.

**Comment by megabreit** [comment]
Same issue with v1.1.0 GA inside of Virtual Box.

**Comment by simsicon** [comment]
Experiencing the same issue with V1.1.0 and Nvida Quadro P620

**Comment by guangbochen** [comment]
please refer to https://github.com/harvester/harvester/issues/2937#issuecomment-1300635489 as a temp workaround for now, thanks, Also please let us know if it will work for u guys, thanks.
