### ISSUE TITLE
[BUG] Shutdown sequence is unexpected. Umount overlayfs before stop containers

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#1876]
**Describe the bug**

Shutdown sequence is unexpected. Umount overlayfs before stop containers
cause some ext4 error log in console

**To Reproduce**
1. Shutdown harvester node
2. check console logs

**Expected behavior**

No ext4 error log of Prometheus container or other containers

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Libvirt/qemu

**Additional context**

![2022-01-20 14-43-33 的螢幕擷圖](https://user-images.githubusercontent.com/2821179/151306226-9d65e123-bfbf-439a-acb3-ad46fe41e653.png)

systemd-analyze plot > a.svg
PS: shutdown-rke2.service is added by me manually to shutdown container before umount via rke2-killall.sh
![a](https://user-images.githubusercontent.com/2821179/151306545-002c2a67-be96-44c7-b0d0-91f3a61ebf41.svg)

# Dev updates
### Enable Kubernetes Graceful Node Shutdown
- https://kubernetes.io/blog/2021/04/21/graceful-node-shutdown-beta/

### Calling `rke2-killall.sh` before shutdown
- https://github.com/rancher/rke2/issues/2411

**Comment by johnliu55tw** [comment]
Related to RKE2 issue https://github.com/rancher/rke2/issues/2411

**Comment by bk201** [comment]
We also need to consider we will migrate to SLE micro for Rancher.

**Comment by tjjh89017** [comment]
This issue probably related to the fix https://github.com/systemd/systemd/commit/aebff2e7ce209fc2d75b894a3ae8b80f6f36ec11

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Shutdown and power on the node
3. Login to console, execute `journactl -b1 | grep "EXT4"`, there should not have `EXT4-fs error ....`
4. execute `journactl -b1 | grep "rke2-shutdown"`, there should have logs about executing `rke2-shutdown.yml`
5. Reboot the node, repeat Step 3 and 4.
