### ISSUE TITLE
[BUG] Builder package user data / network data mismatch

### ISSUE THREAD

**Issue by jadenlemmon** [harvester/harvester#1878]
**Describe the bug**

My use case for encountering this bug was through the [Terraform Provider](https://github.com/harvester/terraform-provider-harvester). I was creating a virtual machine with cloud-init data passing secret values for user data and network data. However, the network data was not persisting. 

Upon further investigation, it seems in the go package consumed by the terraform provider is not properly associating the network and user data. 

**To Reproduce**
1. Create a secret with user data and network data in the harvester cluster. 
2. Create a virtual machine with the terraform provider. 
2. Pass the values `network_data_secret_name` and `user_data_secret_name` into the `cloud-init` block. I used the same secret value for both as I had network data and user data stored in the same secret.
3. Apply the update for the VM and observe only user data being mounted to the VM.

**Expected behavior**

I should expect to see both user data and network data mounted to the VM by the secret value. 

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

I believe the inconsistencies are located on these particular lines:
https://github.com/harvester/harvester/blob/master/pkg/builder/cloudinit.go#L44
https://github.com/harvester/harvester/blob/master/pkg/builder/cloudinit.go#L67

**Comment by futuretea** [comment]
Generally, users do not input node driver's networkData with a length greater than 2048. 
But for safely, also update dependencies in Harvester Node driver(https://github.com/harvester/docker-machine-driver-harvester/pull/29)

**Comment by lanfon72** [comment]
@futuretea could you provide some test plan?
I not sure I can reproduce the bug by _reproduce steps_.

**Comment by futuretea** [comment]
@lanfon72 
**Test Plan**
1. create a secret contains cloudinit config:
```bash
cat >userdata.txt <<EOF
#cloud-config
password: 123456
chpasswd:
  expire: false
ssh_pwauth: true
ssh_authorized_keys: []
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent
EOF
cat >networkdata.txt <<EOF
network:
  version: 1
  config:
    - type: physical
      name: enp1s0
      subnets:
         - type: static
           address: 192.168.5.111/24
           gateway: 192.168.5.1
EOF
kubectl -n default create secret generic ubuntu-dev-cloudinit --from-file=userdata=userdata.txt --from-file=networkdata=networkdata.txt
```

2. Use the master head docker image for testing refer to this [wiki page](https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing)

3. use terraform configurations as follow (harvester-public/image-57hzg is a image which created from ubuntu-20.04-minimal-cloudimg-amd64.img):
```hcl
data "harvester_image" "ubuntu20" {
  name      = "image-57hzg"
  namespace = "harvester-public"
}
data "harvester_network" "vlan1" {
  name      = "vlan1"
  namespace = "harvester-public"
}
resource "harvester_virtualmachine" "ubuntu20-dev" {
  name      = "ubuntu-dev"
  namespace = "default"

  cpu    = 1
  memory = "2Gi"

  start        = true
  hostname     = "ubuntu-dev"
  machine_type = "q35"

  network_interface {
    name         = "nic-1"
    network_name = data.harvester_network.vlan1.id
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = data.harvester_image.ubuntu20.id
    auto_delete = true
  }

  cloudinit {
    user_data_secret_name    = "ubuntu-dev-cloudinit"
    network_data_secret_name = "ubuntu-dev-cloudinit"
  }
}
```
4. Go to VM UI cloud config page, userdata and networkdata should be displayed correctly.
5. After a few minutes, the IP of vm ubuntu-dev should be '192.168.5.111'

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/155116327-d28a2e3b-b36b-4dfe-9864-2ce8dfdd3f3c.png)
![image](https://user-images.githubusercontent.com/5169694/155116367-a1afb669-84f3-4ece-bc76-a24db65792bf.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-bfd6a8a9-head**
* **ui-source** Option: **Auto**
* terraform-provider-harvester Version: [05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf](https://github.com/harvester/terraform-provider-harvester/commit/05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf)

### Verify Steps:
1. Follow the Test Plan https://github.com/harvester/harvester/issues/1878#issuecomment-1047630941
