### ISSUE TITLE
[BUG] Missing active network indication in UI when provisioning with Terraform

### ISSUE THREAD

**Issue by lucasajackson** [harvester/harvester#1883]
**Describe the bug**
Networks created with Terraform do not show a green "active" label in the UI like they do when they're created in the UI.

**To Reproduce**
Create a new network in the Rancher UI and select "Auto(DHCP)" in the route section.  After the network is created it will indicate it's active under "Route Connectivity".

1. Create a network using Terraform using the resource below.  It won't indicate the network is active in the UI.

resource "harvester_network" "vlan193" {
  name      = "name-of-some-networkr"
  namespace = "default"

  vlan_id = 193
}

**Expected behavior**
The Terraform created network will report that it's active in the UI after creation. 

**Support bundle**
I'm going to reuse a support bundle I generated earlier; as the problem was present when it was created. 

The included screenshot shows two networks.  Stealthcloud-dmz-pets was created in the UI and is showing as active under "Route Connectivity", and stealthcloud-dmz was created with Terraform.   I know these are in the same VLAN, but this also happens when I create networks in different VLANS. 
<img width="1178" alt="image" src="https://user-images.githubusercontent.com/15188477/151558315-41e28d2b-86c0-4ff7-aca7-a26d1ce1d649.png">

**Environment:**
 - Harvester ISO version:  1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal - Dell Precision Workstation T5600

[supportbundle_cb61fc33-2eb0-45c5-b007-5e2b3079352f_2022-01-27T02-22-45Z.zip](https://github.com/harvester/harvester/files/7959083/supportbundle_cb61fc33-2eb0-45c5-b007-5e2b3079352f_2022-01-27T02-22-45Z.zip)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

- [x] Create exists VLAN
![image](https://user-images.githubusercontent.com/5169694/155111535-2cbbd292-5525-4f46-8946-5196a600f7f4.png)
- [x] Create new VLAN
![image](https://user-images.githubusercontent.com/5169694/155111356-e20ba5a7-e2bd-4f0b-8c20-e60c6015e73b.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-bfd6a8a9-head**
* **ui-source** Option: **Auto**
* terraform-provider-harvester Version: [05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf](https://github.com/harvester/terraform-provider-harvester/commit/05ee443a699f6ebf1b0da5e87f3f9fdcbfd9c4cf)

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to Advanced Settings, enable VLAN
3. Spawn Docker container environment for terraform (based on https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing)
4. Create the `vlan.tf` file as below, then execute `terraform apply`
```terraform
resource "harvester_network" "vlan1" {
  name      = "vlan1"
  vlan_id   = 1
}
```
5. Login to Dashboard then navigate to Advanced Networks, **vlan1** should be created
6. **Route Connectivity** should displays `Active`
