### ISSUE TITLE
[FEATURE] Ability to provide NetworkInterface details via kernel arguments

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#1889]
**Is your feature request related to a problem? Please describe.**

Ability to pass harvester-mgmt interfaces objects via kernel arguments during PXE booting nodes

**Describe the solution you'd like**

Currently we can pass some of the harvester installation options present in the HarvesterConfig via the kernel arguments during the PXE boot process. 

The harvester-installer reads the arguments from /proc/cmdline and then parses them into HarvesterConfig. 
The current logic only allows the harvester-installer to parse the cmdline arguments into a map or array objects. This doesnt work as expected when we need to pass the mac address of the nodes.

The ability to pass hwAddr which can then be parsed into NetworkInterfaces is needed to mass PXE boot nodes in public cloud providers like equinix.

Using additional kernel arguments as shown below, the management address can be looked up by the installer as part of the installation. 

```
harvester.install.networks.harvester-mgmt.interfaces="hwAddr: ${net0/mac}" harvester.install.networks.harvester-mgmt.method=dhcp harvester.install.networks.harvester-mgmt.bond_options.mode=balance-tlb harvester.install.networks.harvester-mgmt.bond_options.miimon=100
```
**Describe alternatives you've considered**

**Additional context**

Why would be need this? This is needed because in public cloud providers where metal instances are in use, the mac address of the interfaces is unknown until the instance is booted. Interface name cant be used reliably since the same instance type can assign different instance names based on the location of the interface on the PCI bus.

**Comment by guangbochen** [comment]
@ibrokethecloud can u please help to provide the proper reproducible and verification steps so the QA can help to verify and close this issue, thanks.

**Comment by ibrokethecloud** [comment]
@guangbochen the easiest way to test this would be in equinix metal to pxe boot the node with a custom iPXE script. The ipxe needs an Elastic IP to be provisioned in advance. 

The elastic ip and the base address of artifacts needs to be changed since we need a http only endpoint.

```
#!ipxe
dhcp
iflinkwait -t 5000 && echo Detected link on ${ifname} 
set base LOCATION_OF_BASE
set vip ELASTIC_IP
kernel ${base}/harvester-master-vmlinuz-amd64 ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:${base}/harvester-master-rootfs-amd64.squashfs harvester.install.networks.harvester-mgmt.interfaces="hwAddr:${net0/mac}" harvester.install.networks.harvester-mgmt.method=dhcp harvester.install.networks.harvester-mgmt.bond_options.mode=balance-tlb harvester.install.networks.harvester-mgmt.bond_options.miimon=100 console=ttyS1,115200 harvester.install.automatic=true harvester.install.vip=${vip} harvester.install.vip_mode="static" boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online" harvester.install.config_url=https://metadata.platformequinix.com/userdata
initrd ${base}/harvester-master-initrd-amd64
boot
```

The userdata to be passed to instance is

```
token: "token"  # replace with a desired token
os:
  ssh_authorized_keys:
  - github:ibrokethecloud
  password: "password"  # replace with a your password
  hostname: "node1"
install:
  mode: create
  device: /dev/sda
  iso_url: https://releases.rancher.com/harvester/master/harvester-master-amd64.iso
  tty: ttyS1,115200n8
```

An easier way may be to just use this terraform example I have as well.

https://github.com/ibrokethecloud/harvester-equinix-terraform-sample

I would just change the IPXE script variable to point to your custom ipxe endpoint on github. This example uses a dirty build I did from master with my changes.

I hope this helps.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

- [x] `harvester.install.networks.harvester-mgmt.interfaces`
- [x] `harvester.install.networks.harvester-mgmt.method`
- [x] `harvester.install.networks.harvester-mgmt.bond_options.mode`
- [x] `harvester.install.networks.harvester-mgmt.miimon`

** Other options not listed in the original post
- [ ] `harvester.install.networks.bond0`
- [ ] `harvester.install.networks.harvester-mgmt.mtu`


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-75cc3ced-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester via PXE boot with **new** iPXE kernel arguments listed above
2. Harvester should be installed successfully
3. Options should be applied
