### ISSUE TITLE
[BUG] URL for copying an image is for the harvester dashboard instead of a link to the image

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#1892]
**Describe the bug**

* when selecting an image, user is brought to a page that shows the image path on the harvester setup. This link is copy-able, but link is incorrect. It is for the dashboard of harvester. 

**To Reproduce**
1. download an image in your harvester setup
2. select the image from list of images
3. click `copy` button for the image

**Expected behavior**

expecting user to have a link that would download the image from the harvester setup

**Support bundle**
n/a

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal with dell poweredge r510

**Additional context**

![Screen Shot 2022-02-03 at 3 18 01 PM](https://user-images.githubusercontent.com/16691014/152445747-f2d08238-b719-4282-bf14-e534b043d0d3.png)

**Comment by WuJun2016** [comment]
Hi, @slickwarren  I was not able to reproduce the problem according to the steps you provided, can you upload a video of the reproduction steps to help me reproduce the problem Thanks。

**Comment by slickwarren** [comment]
I was not able to reproduce this on another setup, I will close this issue.
