### ISSUE TITLE
Why does it enter the harvester login interface when accessing the rancher service in nodeport mode

### ISSUE THREAD

**Issue by wangpan-hqu** [harvester/harvester#1897]

**Comment by wangpan-hqu** [comment]
![屏幕截图 2022-02-08 182907](https://user-images.githubusercontent.com/74587498/152969467-982638f1-b497-4871-8c16-c2027c7dbd3c.png)

**Comment by tlehman** [comment]
Could you provide steps to reproduce this and include version number?
