### ISSUE TITLE
[Question]Not able to boot on Cisco UCS

### ISSUE THREAD

**Issue by zlojadmin** [harvester/harvester#1898]
Cisco UCS  B200 M2 Server (rather old) with 96Gig of ram and 320Gb HDD. Installed fine, but not booting up.

**Comment by bk201** [comment]
@zlojadmin Did you see the GRUB menu? Are you using UEFI mode or legacy mode? Thanks.

**Comment by zlojadmin** [comment]
@bk201 No, no GRUB menu. It's Legacy at the moment. Which mode should I use?

**Comment by bk201** [comment]
@zlojadmin Harvester should support both modes. If you are using UEFI mode, you can check if a correct boot partition is selected in the BIOS menu. For legacy mode, selecting the install disk should be fine.

**Comment by zlojadmin** [comment]
@bk201 Reinstalled from scratch, no luck booting. Is there a way to get installation logs maybe? There is installers console available after ATLT+F2, but I have no idea what is username/password. I can try to login and check if all components are installed maybe?

**Comment by bk201** [comment]
@zlojadmin you can log in with rancher/rancher.

**Comment by zlojadmin** [comment]
Looks like installer is not creating anything for Legacy boot. Tried to enable EFI boot, but server does not support it. I'm not expert on EFI boot at all. Only thing I have noted that none of 6 partitions are marked as "bootable". Tried to Trigger boot flag for first partition - no luck. Also Cisco USC is rather "interesting" platform by itself. Maybe I can provide you some kind of info to try to resolve boot issue for Cisco UCS M2 b200 Blade servers

**Comment by w13915984028** [comment]
@zlojadmin any new updates? thanks.
