### ISSUE TITLE
Authentication timeout

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#190]
Authentication timeout encountered in some cases somehow, though users are still manipulating Harvester pages.

![image](https://user-images.githubusercontent.com/57614736/94547010-4107d080-0281-11eb-961f-1e80979204e5.png)
![image](https://user-images.githubusercontent.com/57614736/94547036-4b29cf00-0281-11eb-8913-b7e6f2730e37.png)

**Comment by gitlawr** [comment]
The token is expired as expected. TTL is configurable via the setting. We will introduce a token refresh mechanism as the enhancement

**Comment by guangbochen** [comment]
TTL is now configurable via settings and close in favor of https://github.com/rancher/harvester/pull/182
