### ISSUE TITLE
[FEATURE] Obsoleting the Harvester configuration "no_data_partition"

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1907]
**Is your feature request related to a problem? Please describe.**
This configuration was provided to users who have multiple disks and want to use one of them as the VM data disk, so they might not want to create a dedicated VM data partition in the OS disk. Now we are [adding the functionality](https://github.com/harvester/harvester/issues/1728) to choose a different disk as the default disk during installation, this config should no longer be required.

**Describe the solution you'd like**
Remove the Harvester configuration [no_data_partition](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#installno_data_partition) to reduce system complexity.

**Describe alternatives you've considered**
None.

**Additional context**
Related: https://github.com/harvester/harvester/issues/1728

**Comment by lanfon72** [comment]
Can not verify this because **upgrade** is not ready yet.
@guangbochen is it ok to keep this one in _testing_ pipeline?

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/161098383-65a3971c-e3e9-4922-aef7-5c1bdcd52b2c.png)
![image](https://user-images.githubusercontent.com/5169694/161098958-9fbb22bb-c062-4587-87f1-22477cae1e04.png)
![image](https://user-images.githubusercontent.com/5169694/161099028-ce62ee72-11c3-4bbd-88b1-8487b2a7b666.png)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0.0** to **v1.0.1-rc2**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow the case in https://github.com/harvester/tests/issues/225#issue-1163575155

**Comment by wzrdtales** [comment]
this completely forgot about the existence of SATA  DOMs, which should only hold the base but nothing else.
