### ISSUE TITLE
Remove unused nfs.go file

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#1908]
`pkg/controller/master/backup/nfs.go` is not referenced by any file. We've already changed to use LH [backupstore](https://github.com/longhorn/backupstore) to operate NFS/S3 backup.

**Comment by lanfon72** [comment]
Does this need any tests?

**Comment by FrankYang0529** [comment]
> Does this need any tests?

No, I think it's good to close it.

**Comment by noahgildersleeve** [comment]
Tested in `master-45182389-head`.

## Verification steps

1. Create new VM
2. Add file1 and content
3. create backup
4. edit file1 and add file2
5. create backup
6. edit file2 create file3 and content
7. Create backup
8. Restore to backup1
9. Verify that only original file1 exists
