### ISSUE TITLE
[Question] Instructions on building ISOs?

### ISSUE THREAD

**Issue by victorhooi** [harvester/harvester#1911]
Are there instructions anywhere for building new ISOs? (i.e. if we want to build a ISO from master, rather than going back to the last release).

I couldn't see any in the README, or linked anywhere.

**Comment by futuretea** [comment]
In the harvester-installer repo:

https://github.com/harvester/harvester-installer/blob/master/README.md#building

https://github.com/harvester/harvester-installer/wiki/Development-ISO-Build

**Comment by FrankYang0529** [comment]
* If you only modify `harvester` repo, you can run `make build-iso` in `harvester` repo. ISO will be under `dist/artifacts`.
* If you only modify `harvester-installer` repo, you can run `make build` in `harvester-installer` repo. ISO will be under `dist/artifacts`.
* If you modify both repositories, you can update [this line](https://github.com/harvester/harvester-installer/blob/2199e99e2f3546e16b26426b6e19770fb3d3f2c3/Dockerfile.dapper#L42) as the following and run `make build` in `harvester-installer` repo.

```
ENV DAPPER_RUN_ARGS "-v /var/run/docker/containerd/containerd.sock:/run/containerd/containerd.sock -v /path/to/local/harvester/repo:/go/src/github.com/harvester/harvester"
```

**Comment by guangbochen** [comment]
@FrankYang0529 can we add it to the [wiki doc](https://github.com/harvester/harvester/wiki) as a new page, thanks.

**Comment by FrankYang0529** [comment]
Added it. https://github.com/harvester/harvester/wiki/Build-ISO-images
