### ISSUE TITLE
[BUG] Prometheus OOMKilled

### ISSUE THREAD

**Issue by fadjar340** [harvester/harvester#1912]
**Describe the bug**
Prometheus got OOMKilled on several minutes. It's same as [#1531](https://github.com/harvester/harvester/issues/1531)

**Expected behavior**
No OOMKilled anymore

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure:  Baremetal with Fujitsu PRIMERGY RX2520 M4 10 nodes

**Comment by alexdepalex** [comment]
#1531

**Comment by fadjar340** [comment]
Hi,

Since I change the rancher-monitoring-prometheus.yml inside Menu Monitoring - Advanced - Promethei as follow:

```
.
.
.
 resources:
    limits:
      cpu: 1000m
      memory: 3000Mi
    requests:
      cpu: 500m
      memory: 1000Mi
  retention: 5d
  retentionSize: 50GiB
.
.
.
```

The prometheus working as expected without restarting.


Regards,
Fadjar Tandabawana

**Comment by guangbochen** [comment]
The proper workaround steps can be found on the https://github.com/harvester/harvester/issues/1887#issuecomment-1038605654

**Comment by w13915984028** [comment]
@fadjar340 Do you have any updates?

How to set resources of Prometheus is documented at https://docs.harvesterhci.io/v1.0/monitoring/monitoring/ .

BTW: the latest Harvester release fixed the OOM issue, welcome to try it.
https://github.com/harvester/harvester/releases/tag/v1.0.2

**Comment by fadjar340** [comment]
Thanks @w13915984028,

I'll try it, perhaps in the near future.. Still do something else.. BTW, it'w great to get new version..


Regards
Fadjar

**Comment by w13915984028** [comment]
Close as solved.
