### ISSUE TITLE
The migration error message popups need to be dismissed

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#192]
**Steps to reproduce:**
1. Select a VM which cannot be migrated
2. Do the migration

**Result:**
The error message popups don't dismiss themselves, even if users turn the page forward or backward
![image](https://user-images.githubusercontent.com/57614736/94586480-dde36180-02b3-11eb-9834-5d18d98ea033.png)

**Comment by WuJun2016** [comment]
next version fix

**Comment by guangbochen** [comment]
close as migration is currently move-out.
