### ISSUE TITLE
[BUG] GUI allows selecting the default data disk as an additional disk

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1924]
**Describe the bug**
GUI allows selecting the default data disk (introduced in feature https://github.com/harvester/harvester/issues/1728) being selected to be added as additional disks.
![image](https://user-images.githubusercontent.com/5047724/154406840-018adf9a-8006-4711-be14-14af1709bcf0.png)
> `/dev/sda` is the default data disk

**To Reproduce**
1. Install Harvester with default data disk set to a disk different from the OS disk, e.g. `/dev/sda`
2. Go to "Hosts" page -> Select the node -> "Edit Config" -> "Disks" page -> Click "Add Disk"
3. The default data disk appears in the drop-down list.

**Expected behavior**
The default disk should not be shown in the "Add Disk" drop-down list.

**Support bundle**

**Environment:**
 - Harvester ISO version: master (2022-02-17)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
The default data disk formats the **whole disk** as EXT4 filesystem instead of creating a partition. Although the filesystem still has the label `HARV_LH_DEFAULT` which should be recognized by NDM to skip this disk, NDM for now only applies [label filter](https://github.com/harvester/node-disk-manager/blob/master/pkg/filter/label_filter.go) on partitions, so the disk is not skipped and is added as a `BlockDevice` resource.

**Comment by TachunLin** [comment]
Verified **fixed** on master-bfd6a8a9-head (02/28). Close this issue. 

### Result 
Add extra disk in host page now won't display default data disk `/dev/sdb` 
![image](https://user-images.githubusercontent.com/29251855/155999062-a63e0d20-188f-490f-9c2a-8dc2443832f6.png)

```
harvester-one-220228:~ # lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
loop0    7:0    0  3.2G  1 loop /
sda      8:0    0   70G  0 disk 
sdb      8:16   0  200G  0 disk 
├─sdb1   8:17   0  960K  0 part 
├─sdb2   8:18   0   50M  0 part /oem
├─sdb3   8:19   0   15G  0 part /run/initramfs/cos-state
├─sdb4   8:20   0    8G  0 part 
├─sdb5   8:21   0   60G  0 part /usr/local
└─sdb6   8:22   0  117G  0 part /var/lib/harvester/defaultdisk
sdc      8:32   0   80G  0 disk 
sdd      8:48   0   50G  0 disk 
sde      8:64   0   60G  0 disk 
sdf      8:80   0   10M  0 disk /var/lib/kubelet/pods/c50d56e7-71f2-4412-88b5-e4b25fb29634/volumes/kubernetes.io~csi/pvc-0db8b29e-fceb-4ad1-9df3
sdg      8:96   0   50G  0 disk /var/lib/kubelet/pods/79ed0a5d-6214-4b38-90a8-58d3cbdaea0e/volume-subpaths/pvc-060537d1-24fa-492e-a988-8d99e1f0a
sr0     11:0    1 1024M  0 rom
```

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-bfd6a8a9-head (02/28)

### Verify Steps
1. Prepare a kvm virtual machine
2. Add 4 extra disks 
3. Install harvester on the first disk
  ![image](https://user-images.githubusercontent.com/29251855/155996412-7530e6a8-f04c-429c-9245-5af7d1794150.png)
  ![image](https://user-images.githubusercontent.com/29251855/155996465-5e2553cd-31dd-4148-a94c-643045d114c7.png)
4. After harvester node active 
5. ssh login to harvester VIP
6. Run `gdisk /dev/sda`, gdisk /dev/sdc`, gdisk /dev/sdd`, gdisk /dev/sde` 
7. Press w to create partition 
8. Relogin harvester
9. Edit config in host page
10. Add extra disk in disk page
11. Check `/dev/sdb` won't display on the list
