### ISSUE TITLE
[BUG] Refreshing the Virtual Machine page changes the status from "Running" to "Starting"

### ISSUE THREAD

**Issue by johnliu55tw** [harvester/harvester#1925]
**Describe the bug**
Refreshing the browser on Virtual Machine page would cause the status of the VM to change from "Running" to "Starting".

https://user-images.githubusercontent.com/5047724/154439287-e27a2e46-4713-424f-9bf6-f872e0dc2685.mp4

**To Reproduce**
1. Create a VM and make sure it's in "Running" status
2. Go to the VM's page, and make sure you see its status is "Running"
3. Click refresh
4. The status becomes "Starting"

**Expected behavior**
The status should still show "Running" even after browser refresh.

**Support bundle**

**Environment:**
 - Harvester ISO version: master (2022-02-17)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 1 node** and **Bare metal DL360 3 nodes **
* Harvester Version: **v1.0.0** and **master-bfd6a8a9-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any Nodes
2. Create image for VM creation
3. Create VM and wait until its state become `Running`
4. Navigate to VM's details
5. Refresh the Page, VM's state should display `Running` (fail case will shows `Starting`)
