### ISSUE TITLE
Start time and end time are not updated after the first migration on the VM detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#193]
**Steps to reproduce:**
1. Migrate a VM for several times
2. Check on the Migration tab the detail page

**Result:**
Start time and end time are not updated after the first migration
![image](https://user-images.githubusercontent.com/57614736/94588273-492e3300-02b6-11eb-87e6-a08a8cf6daac.png)

![image](https://user-images.githubusercontent.com/57614736/94588223-3e739e00-02b6-11eb-91aa-9c1901686f41.png)

![image](https://user-images.githubusercontent.com/57614736/94588366-606d2080-02b6-11eb-9ff4-4f493ed5e4cc.png)

**Comment by WuJun2016** [comment]
It can't be reproduced

**Comment by DoNotSayYes** [comment]
Unable to reproduce it for now.
