### ISSUE TITLE
[Question]  Harvester 1.0.0 : How to remove "hanging" Backups?

### ISSUE THREAD

**Issue by ugar-ugar** [harvester/harvester#1930]
Hi,
I have lost my NFS - Backupstore (Disk failure). All Data is gone.
Harvester UI did not allow changing the NFS-URL because of running jobs.
Therefore an (enpty) replacement for this is setup on the on the same NFS-URL path. 
I tried to delete all backups and backupjobs from Harvester and Longhorn UI without sucsess.
Now I can see an "hanging" backup job in "not ready" state and new scheduled Backups are never starting.

How can i "cleanup" the hanging Backupjobs and restart with an fresh empty NFS - backupstore?
A fresh supportbundle is attached
[supportbundle_4ae9227d-94b8-4a13-82a5-3be245f162b6_2022-02-18T08-53-32Z.zip](https://github.com/harvester/harvester/files/8095778/supportbundle_4ae9227d-94b8-4a13-82a5-3be245f162b6_2022-02-18T08-53-32Z.zip)

**Comment by FrankYang0529** [comment]
Hi @ugar-ugar, do you create `Recurring Job` in Longhorn page and you can't cleanup the hanging `Recurring Job`? If yes, I will create another issue in Longhorn.

https://longhorn.io/docs/1.2.3/snapshots-and-backups/scheduling-backups-and-snapshots/

**Comment by ugar-ugar** [comment]
Hello FrankYang0529,
my backup was created from Harvester-VirtualMachines-Take Backup.
The backup configuration is also done from Harvester.
The Longhorn-UI does not show any backup activity or pending jobs.
It does not look like a Longhorn related problem.

Regards
Ulrich

**Comment by FrankYang0529** [comment]
> How can i "cleanup" the hanging Backupjobs and restart with an fresh empty NFS - backupstore?

Hi @ugar-ugar, I misunderstood `backupJob` as the `Job` resource in Kubernetes. I think what you want to say is how to clean up `VirtualMachineBackup` in Harvester.

Harvester leverages [Longhorn CSI](https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi/#create-a-backup-via-the-csi-mechanism) to create Longhorn `Backup`. When users delete `VirtualMachineBackup`, we have a finalizer in it to remove `VolumeSnapshot` and `VolumeSnapshotClass`. However, `VolumeSnapshot` and `VolumeSnapshotClass` also have finalizers to do some cleanup. It looks there is some error, so `VolumeSnapshot` and `VolumeSnapshotClass` can't finish their cleanup and they will be stuck in deleting status.

If you want to clean up `VirtualMachineBackup`, you can remove finalizers in `VirtualMachineBackup`, `VolumeSnapshot`, `VolumeSnapshotClass`, and Longhorn `Backup`. You can get correspond resources like the following:
* Longhorn `Backup` Name: `VirtualMachineBackup.status.volumeBackups[].longhornBackupName`
* `VolumeSnapshot` Name: `VirtualMachineBackup.status.volumeBackups[].name`
* `VolumeSnapshotContent` Name: `Backup.status.snapshotName`

**Comment by ugar-ugar** [comment]
Hello FrankYang0529,
thank you for your hints,
I was able to CleanUp the leftovers. 
Now new Backups are working again.

**Comment by depasseg** [comment]
> > How can i "cleanup" the hanging Backupjobs and restart with an fresh empty NFS - backupstore?
> 
> Hi @ugar-ugar, I misunderstood `backupJob` as the `Job` resource in Kubernetes. I think what you want to say is how to clean up `VirtualMachineBackup` in Harvester.
> 
> Harvester leverages [Longhorn CSI](https://longhorn.io/docs/1.2.3/snapshots-and-backups/csi-snapshot-support/create-a-backup-via-csi/#create-a-backup-via-the-csi-mechanism) to create Longhorn `Backup`. When users delete `VirtualMachineBackup`, we have a finalizer in it to remove `VolumeSnapshot` and `VolumeSnapshotClass`. However, `VolumeSnapshot` and `VolumeSnapshotClass` also have finalizers to do some cleanup. It looks there is some error, so `VolumeSnapshot` and `VolumeSnapshotClass` can't finish their cleanup and they will be stuck in deleting status.
> 
> If you want to clean up `VirtualMachineBackup`, you can remove finalizers in `VirtualMachineBackup`, `VolumeSnapshot`, `VolumeSnapshotClass`, and Longhorn `Backup`. You can get correspond resources like the following:
> 
> * Longhorn `Backup` Name: `VirtualMachineBackup.status.volumeBackups[].longhornBackupName`
> * `VolumeSnapshot` Name: `VirtualMachineBackup.status.volumeBackups[].name`
> * `VolumeSnapshotContent` Name: `Backup.status.snapshotName`

I'm having this same issue in 1.0.3.   Could you give me a hint on how I can remove the finalizers that you mention?  Thank you!

**Comment by FrankYang0529** [comment]
You can use `kubectl edit` to open resource YAML and remove `finalizers` from it. Thanks.

**Comment by depasseg** [comment]
> You can use `kubectl edit` to open resource YAML and remove `finalizers` from it. Thanks.

Thank you, I was able to remove them using kubectl VirtualMachineBackup, VolumeSnapshot,and VolumeSnapshotClass, but I can't figure out Longhorn.  I can see the 2 failed snapshots:

greg@Gregs_XPS-15:~$ kubectl get VolumeSnapshotContent
NAME                                                                     READYTOUSE   RESTORESIZE    DELETIONPOLICY   DRIVER               VOLUMESNAPSHOTCLASS   VOLUMESNAPSHOT                                                                                                    AGE

portainer-backup-2022-11-20-volume-portainer-rootdisk-1xzml-vsc          true         0              Delete           driver.longhorn.io   longhorn              portainer-backup-2022-11-20-volume-portainer-rootdisk-1xzml                                                       19d

snapcontent-0a8ade12-21d6-44d0-b905-133eb93732fe                         true         137438953472   Delete           driver.longhorn.io   longhorn              unms-2022-11-28-volume-restore-unms-backup-2022-11-20-a9b02439-155d-405f-bead-9c9aa9bb6ed4-rootdisk               14d

snapcontent-1679edbf-6cc4-4c6b-878c-04fbbe0526fc                         true         10737418240    Delete           driver.longhorn.io   longhorn              testvm-2022-11-28-volume-restore-test-machine-backup-2022-11-20-17d3a754-a7bb-4250-a1fd-4e9930744e7d-cdrom-disk   14d

snapcontent-513eee45-836c-4bb3-a9d1-99ef77f75544                         true         137438953472   Delete           driver.longhorn.io   longhorn              portainer-2022-11-28-volume-restore-portainer-backup-2022-11-20-bb98a916-c2cb-4c4c-a341-569c38a0bbf3-rootdisk     13d

**snapcontent-63cc5bcc-1561-49d9-98c5-c326534d4e6b                        false                       Delete           driver.longhorn.io   longhorn              unmsbackup2-volume-restore-unms-backup-2022-11-20-a9b02439-155d-405f-bead-9c9aa9bb6ed4-rootdisk                   23h**

**snapcontent-b79d838f-b9ca-4ff6-afd7-0fc9f19baa08                         false                       Delete           driver.longhorn.io   longhorn              unms-2022-12-11-volume-restore-unms-backup-2022-11-20-a9b02439-155d-405f-bead-9c9aa9bb6ed4-rootdisk               24h**

snapcontent-fa123c21-739c-4dcf-a85a-f071bbe68939                         true         107374182400   Delete           driver.longhorn.io   longhorn              testvm-2022-11-28-volume-restore-test-machine-backup-2022-11-20-17d3a754-a7bb-4250-a1fd-4e9930744e7d-rootdisk     14d

test-machine-backup-2022-11-20-volume-2204-test-1-cdrom-disk-mkbwp-vsc   true         0              Delete           driver.longhorn.io   longhorn              test-machine-backup-2022-11-20-volume-2204-test-1-cdrom-disk-mkbwp                                                19d

test-machine-backup-2022-11-20-volume-2204-test-1-rootdisk-zjjox-vsc     true         0              Delete           driver.longhorn.io   longhorn              test-machine-backup-2022-11-20-volume-2204-test-1-rootdisk-zjjox                                                  19d

unms-backup-2022-11-20-volume-unms-rootdisk-te40s-vsc                    true         0              Delete           driver.longhorn.io   longhorn              unms-backup-2022-11-20-volume-unms-rootdisk-te40s                                                                 19d`

Oh and if I go to the backups tab in the Longhorn UI, I get the following error:

`error listing backup volume names: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.2.4/longhorn [backup ls --volume-only s3://harvester@main/], output failed to list objects with param: { Bucket: "harvester", Delimiter: "/", Prefix: "/" } error: AWS Error: NotFound Not Found <nil> 404 , stderr, time="2022-12-12T18:49:14Z" level=error msg="Fail to list s3: failed to list objects with param: {\n Bucket: \"harvester\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} error: AWS Error: NotFound Not Found <nil>\n404 \n" pkg=s3 time="2022-12-12T18:49:14Z" level=error msg="failed to list objects with param: {\n Bucket: \"harvester\",\n Delimiter: \"/\",\n Prefix: \"/\"\n} error: AWS Error: NotFound Not Found <nil>\n404 \n" , error exit status 1`
