### ISSUE TITLE
Image is only black and white

### ISSUE THREAD

**Issue by MasIgor** [harvester/harvester#1932]
Hello all!

First off thank you for this!

I'm trying to read a genie nano color c1920, and to use the image with yoloV5. 

The script loads a jpg file (first rows) and I am trying to replace that code with the frame taken from the camera. Problem is that it only reads one channel and the size of the array is wrong. the array that cv2.imread(path) generates is 3 dimensional: {640,640,3} with a total size of 1228800. the array that the GigE code generates is 1 dimensional {409600} so just one third of the expected size. Also if I use Harvester GUI, the image is black and white. Why? What am I doing wrong?

Thanks, any help appreciated.

```
    self.count += 1
            img0 = cv2.imread(path)  # BGR
            print(img0.size)
            # GigE
            h = Harvester()
            h.add_file('C:\\Program Files\\MATRIX VISION\\mvIMPACT Acquire\\bin\\x64\\mvGenTLProducer.cti')
            h.update()
            print(h.device_info_list)
            ia = h.create_image_acquirer(0)
            ia.remote_device.node_map.Width.value = 640
            ia.remote_device.node_map.Height.value = 640
            print(ia.remote_device.node_map.PixelFormat.symbolics)
            ia.remote_device.node_map.PixelFormat.value = 'BayerRG8'
            ia.start_acquisition()
            with ia.fetch_buffer() as buffer:
                component = buffer.payload.components[0]
                data_format = component.data_format
                print("data format: ", data_format)
                _1d = component.data
                print('1D: {0}'.format(_1d))
                print(_1d.size)
            ia.stop_acquisition()
            ia.destroy()
            h.reset()
            img0 = _1d
```

**Comment by bk201** [comment]
@tanzerlana I guess you filed the issue in the wrong project, maybe you are referring to https://github.com/genicam/harvesters?

**Comment by MasIgor** [comment]
you are right.. sorry..
