### ISSUE TITLE
[BUG] Adapt RKE2 runtime upgrade change from Rancher

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1935]
**Describe the bug**

When bumping rancher image to version `v2.6-e55a04c1915c62bbc23ee1e5db70208ce2a11679-head`, two issues are found for the upgrade feature:

1. RKE2 upgrade procedure doesn't start at all (e. g., `1.0.0` -> `master build with the latest rancher`).
2. Pre-drain/post-drain hooks don't work. We need to watch plan secret rather than CAPI machine. See https://github.com/rancher/rancher/issues/36536#issuecomment-1044987549
 

**To Reproduce**

1. Build a Harvester ISO with changes in: https://github.com/harvester/harvester-installer/pull/229
2. Deploy a Harvester 1.0.0 cluster
3. Upgrade to the build ISO
4. The RKE2 upgrade doesn't start.

**Expected behavior**

RKE2 upgrade should start, a Harvester upgrade should be complete.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
this should be fixed on rc3 as #2112 has been verified.
