### ISSUE TITLE
cloud config validation

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#194]
From https://github.com/rancher/harvester/issues/136#issuecomment-700616450

If users input invalid cloud-init configuration, we don't set it in API and give users no notice.
![image](https://user-images.githubusercontent.com/5697937/94650766-e8d8d900-0329-11eb-9150-88d55e4461e2.png)

**Comment by yasker** [comment]
Close as stale. Feel free to reopen if needed.
