### ISSUE TITLE
[BUG] After uploading large ISO file you get an error on refresh

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1940]
**Describe the bug**

When you refresh the page after a large ISO image upload the web ui won't load
**To Reproduce**
1. Upload a multi-gig (>1GB) iso image to the images section of Harvester
2. As soon as it finishes refresh the page
**Expected behavior**

It should load without error
**Support bundle**

[supportbundle_f3da3adc-2aef-401f-beaa-bb13ac005b1c_2022-02-24T22-59-06Z.zip](https://github.com/harvester/harvester/files/8137165/supportbundle_f3da3adc-2aef-401f-beaa-bb13ac005b1c_2022-02-24T22-59-06Z.zip)

**Environment:**
 - Harvester ISO version: master-bfd6a8a9-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM virtualized environment 12vCPU 16GB memory

**Additional context**
This was originally found in #1904 . @w13915984028 said that if you wait long enough it will resolve itself. The first time I did the upload it only lasted a minute or so. The second time it didn't end immediately, and I just got a blank screen on refresh no error message. If you delete the harvester pod in harvester-system it will recreate it. I'm attaching screenshots, the support bundle, and the logs from the pod. 
[harvester-pod-2.log](https://github.com/harvester/harvester/files/8137172/harvester-pod-2.log)
This is the support bundle after the delete of the pod and it reloading.
[supportbundle_f3da3adc-2aef-401f-beaa-bb13ac005b1c_2022-02-24T23-19-54Z.zip](https://github.com/harvester/harvester/files/8137176/supportbundle_f3da3adc-2aef-401f-beaa-bb13ac005b1c_2022-02-24T23-19-54Z.zip)
![Screenshot from 2022-02-24 15-20-57](https://user-images.githubusercontent.com/83787952/155624016-516f2d2c-a820-45fe-93fe-458a6f2e1b7c.png)

**Comment by w13915984028** [comment]
In the PROVO environment, when digging #1904,  I encountered ` "handler disconnect" `  issue, it can only be recovered via rebooting or deleting the harvester POD,
described in : https://github.com/harvester/harvester/issues/1904#issuecomment-1049834241



error message `"remotedialer buffer exceeded, length: 4224768"`, seems self-healing,
 it was frequently seen in my laptop based Harvester (fast uploading speed),
 and once in PROVO DC Harvester (slow uploading speed, from my PC via VPN to PROVO),

https://github.com/harvester/harvester/issues/1904#issuecomment-1050322077
`time="2022-02-24T21:59:11Z" level=error msg="remotedialer buffer exceeded, length: 4224768"`

**GUESS**: maybe in different network environment, `"remotedialer buffer exceeded"` may finally cause  ` "handler disconnect" `

will continue to investigate

**Comment by w13915984028** [comment]
One way to reproduce the `Handler disconnected` is : scale down the `Harvester `POD.

In Harvester, the web browser http request will run through

**Web browser--------------NGINX--------------Rancher POD---------------Harvester POD**

1. Web browser: `Handler disconnected`  is `http get return code 503`
![image](https://user-images.githubusercontent.com/31133476/156134747-e0559e43-b17b-4693-b078-c7e63c8dc093.png)

`2. The NGINX log shows 503 `
```
10.163.24.194 - - [28/Feb/2022:21:57:20 +0000] "GET /v1/harvester/subscribe?sockId=3 HTTP/1.1" 503 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 701 15.009 [cattle-system-rancher-80] [] 10.52.0.114:80 21 15.012 503 57acc9b6650c244c7974f4c45e60e607

10.163.24.194 - - [28/Feb/2022:21:57:22 +0000] "GET /dashboard/c/local/harvester/harvesterhci.io.virtualmachineimage HTTP/2.0" 503 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 69 15.021 [cattle-system-rancher-80] [] 10.52.0.114:80 21 15.020 503 74d8cefbd30df1bbe86315f65ce81755

10.163.24.194 - - [28/Feb/2022:21:58:09 +0000] "GET /dashboard/c/local/harvester/harvesterhci.io.virtualmachineimage HTTP/2.0" 503 21 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36" 69 15.020 [cattle-system-rancher-80] [] 10.52.0.114:80 21 15.020 503 6c9f0902adf516209fdb1e215abbb1fd
```

![image](https://user-images.githubusercontent.com/31133476/156137480-df30f100-3ee2-4a20-b2f2-27e6f3fd9b27.png)


`3. Rancher shows error websocket connect with Harvester`
![image](https://user-images.githubusercontent.com/31133476/156134968-20f9d3a6-a437-4f04-94d1-109b76fd546f.png)

![image](https://user-images.githubusercontent.com/31133476/156134919-02384782-6609-4c6f-95b2-a5ae847db914.png)

**Comment by w13915984028** [comment]
When investigating, another temp file issue is filed to track:

https://github.com/harvester/harvester/issues/1947
https://github.com/longhorn/longhorn/issues/3682

**Comment by w13915984028** [comment]
The analysis to first support bundle in this issue:

[supportbundle_f3da3adc-2aef-401f-beaa-bb13ac005b1c_2022-02-24T22-59-06Z.zip]

rke2-server.log
**21:17:31** 
**rke2-server started**
![image](https://user-images.githubusercontent.com/31133476/156657146-2d05744e-9ce8-476a-96b4-ec8484b018c8.png)

**Comment by w13915984028** [comment]
**21:20:27**

**rke2 restarted**

**Harvester (PID 14362) and its owner Tini (PID 14321) were here, the new rke2-server service reused them**


```
Feb 24 21:20:27 harvester-master rke2[2282]: time="2022-02-24T21:20:27Z" level=info msg="Shutting down k3s.cattle.io/v1, Kind=Addon workers"
Feb 24 21:20:27 harvester-master rke2[2282]: time="2022-02-24T21:20:27Z" level=fatal msg="context canceled"

Feb 24 21:20:27 harvester-master systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE

...
Feb 24 21:20:27 harvester-master systemd[1]: rke2-server.service: Unit process 14321 (tini) remains running after unit stopped.
Feb 24 21:20:27 harvester-master systemd[1]: rke2-server.service: Unit process 14362 (harvester) remains running after unit stopped.
```

![image](https://user-images.githubusercontent.com/31133476/156657471-c8fb561e-8f13-4097-8390-eeac1b5e7a2b.png)

![image](https://user-images.githubusercontent.com/31133476/156657692-17407e35-099b-4aa0-9c44-1a35ffabaa19.png)

![image](https://user-images.githubusercontent.com/31133476/156657970-37570118-ee24-4a0a-b57d-e490419b3198.png)

**Comment by w13915984028** [comment]
**22:53:33**  
**rke2 server restart again**

Notice the tricky thing: **Harvester (PID 14362) is NOT here, but its owner Tini (PID 14321) was here**

```
Feb 24 22:53:33 harvester-master rke2[22232]: E0224 22:53:33.628403   22232 leaderelection.go:301] Failed to release lock: Operation cannot be fulfilled on configmaps "rke2": the object has been modified; please apply your changes to the latest version and try again
Feb 24 22:53:33 harvester-master rke2[22232]: time="2022-02-24T22:53:33Z" level=fatal msg="leaderelection lost for rke2"
```


Feb 24 22:53:33 harvester-master systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE

![image](https://user-images.githubusercontent.com/31133476/156658120-f27ad99c-c1b8-43d7-946f-db2f4a54d114.png)

Only `tini`, no `Harvester`
![image](https://user-images.githubusercontent.com/31133476/156658373-155c286c-c5b2-45fe-9302-f460d62b7626.png)

**Comment by w13915984028** [comment]
The timeline:

![image](https://user-images.githubusercontent.com/31133476/156659258-5dc6eeb0-573a-44f4-8a4c-2f9c2a1f7320.png)

**Comment by w13915984028** [comment]
Summary:

1. both #1904 and #1940 were tested in similar environment: 12 Core,16G RAM,    uploading has incredible fast speed

2. when uploading, Harvester POD was caching big amount of data due to super fast networking speed (possible KVM virtualized network), the available memory was reducing quickly

in #1904,  kernel had OOM log that Harvester process was killed.

in #1940, RKE2-server happened to reboot at the moment of this bug,   said `"leaderelection.go:301] Failed to release lock: Operation cannot be fulfilled on configmaps "rke2"
`
the log booked one tricky thing: **Harvester (PID 14362) was NOT here, but its owner Tini (PID 14321) was here**,  kernel did not log OOM.



The Harvester POD is designed to run 2 processes: `tini `and `Harvester`, e.g.:
![image](https://user-images.githubusercontent.com/31133476/156660401-caabf326-3c2c-4a2f-a866-44ac6b04b349.png)

**Comment by w13915984028** [comment]
Due to the similar test environment and test steps, #1940 is also highly possible due to the low system available memory.

Next steps to investigate:

1. Why `RKE2-server` restarted as per `"leaderelection.go:301] Failed to release lock: Operation cannot be fulfilled on configmaps "rke2"`

2. Why `Harvester `process exited silently without any kernel/rke2 log, logrus log was also lost/not effectively fetched in support bundle, will `tini ` restart the `Harvester `process inside POD, or the POD will be deleted and restarted?

cc @yasker @guangbochen

**Comment by w13915984028** [comment]
Update:
After the fix of OOM, this issue is not reproducable. It is quite possible to be the side effect of OOM.
Will try to reproduce for more days, and notice if others encounter it in v1.0.1

cc @guangbochen @rebeccazzzz

**Comment by noahgildersleeve** [comment]
Tested in master-0eab7caa-head. Fixed.
## Validation Steps
1. Upload large ISO (>5GB) on local VM to recreate fast network speed
2. Refresh page after completion

**Comment by it-pappa** [comment]
Cant upload the RHEL 8.5 iso tho. its 10 gb. fails at 99%

**Comment by noahgildersleeve** [comment]
@it-pappa I have a few questions. 

1. Is that a consistent issue? 
2. Are you uploading that from file, or from a web server location?
3. If it's by file are you seeing any errors in the browser console (I'm wondering if you're getting some kind of a timeout?
4. What kind of network speed is the network from your file location to the server, and is it going over a WAN or LAN?

**Comment by it-pappa** [comment]
Hi. i have tested harvester and actually went back to another hypervisor. The test was good tho. 
Also, vCenter and proxmox also have issues uploading the 10gb rhel iso, i just moved the file to an apache server and downloaded it successfully from that url path. 

So this issue is not only happening to Harvester but all providers and large iso files, openstack included.

**Comment by it-pappa** [comment]
the fix on proxmox and vcenter (if not downloaded thru url) is to move it by ssh
