### ISSUE TITLE
[BUG] Live Migration to other node then cannot ping

### ISSUE THREAD

**Issue by fadjar340** [harvester/harvester#1944]
**Describe the bug**
I tried to live migrate the VM to node2 from node1, after the VM running in node2, then the VM cannot ping inbound or outbound

**To Reproduce**
1. Go to VM1 in node1, ping from VM2
2. Ping VM1 from VM2 and reply (OK)
3. Ping VM2 from VM1 and reply (OK)
4. Select Migrate of VM1, then select the node2 as target
5. In Migrate status, ping from VM2 to VM1 works as expected (OK)
6. In Running state of the VM1 in node2, the ping from VM2 to VM1 is unreachable (NOK)
7. Ping from VM1 to VM2 unreachable (NOK)
8. When I migrate back to the node1, the ping to VM1 worked again on both VMs (OK)

**Expected behavior**
The ping from outside VM to migrated VM, vice versa,  should working in the new node

**Support bundle**
I can send the support bundle if needed.

**Environment:**
 - Harvester ISO version: 1.0.0 
 - Underlying Infrastructure Baremetal with Primergy: 15 nodes

**Additional context**
This also happened in DHCP or Static IP

**Comment by bk201** [comment]
@fadjar340 Thanks for reporting. After the VM is migrated, its IP is also changed (you can tell it from GUI). Did you ping the original IP?

**Comment by fadjar340** [comment]
Hi @bk201, since I tested using 2 mode, static and DHCP, the static IP supposed to be the same as in the previous node. In DHCP, because of the same MAC, it should be use the DHCP lease from the DHCP server.
In the VM, when use static IP, the IP still same but no successful ping. With DHCP, there is no IP get from DHCP server.

It's make frustrated when the IP changed without control... :)


Regards,
Fadjar T

**Comment by tjjh89017** [comment]
@fadjar340 Do you use VLAN network or Management Network?
Please refer the docs to determine the term [docs](https://docs.harvesterhci.io/v1.0/networking/harvester-network/)

**Comment by fadjar340** [comment]
Hi @tjjh89017 ,

The VM use VLAN Network only. Is it need management network for migration?
I use my own DHCP server inside the VLAN network that bring the IP for my VM's

Regards,
Fadjar Tandabawana

**Comment by fadjar340** [comment]
Is there any workaround to solve this issue?

Regards,
Fadjar T

**Comment by tjjh89017** [comment]
Please check your network switch config first.
https://docs.harvesterhci.io/v1.0/networking/best-practice-vlan-aware-switch/

**Comment by fadjar340** [comment]
Hi @tjjh89017 ,

I just use VLAN 1 for my VM's, and the operational VM can access outside network, just the migration and DHCP that have problems.
For my setup, is it necessary to config the switchports following that document?

Following this [https://docs.harvesterhci.io/v1.0/networking/harvester-network/](https://docs.harvesterhci.io/v1.0/networking/harvester-network/), I just need VLAN 1 to as PVID to communicate as untagged traffic and VM's can communicate as log as same VLAN ID, CMIIW...

Regards,
Fadjar T

**Comment by tjjh89017** [comment]
> For my setup, is it necessary to config the switchports following that document?

If your switch is VLAN-aware switch, I will suggest to follow https://docs.harvesterhci.io/v1.0/networking/best-practice-vlan-aware-switch/ to config your switch.
and make sure your switch didn't config "private vlan" or ACL

Please also test the ping from VM1 to DHCP server or your gateway and migrate VM1 to another node (don't stop ping)

tks a lot

**Comment by fadjar340** [comment]
I'll try...
Ask the netops guy first, then I;ll come back with the result...

Thanks..

**Comment by fadjar340** [comment]
Hi all,

After I asked the network guys and they change the config of the switch, everything works seamless.


Thanks for the suggestion...


Regards,
Fadjar T

**Comment by tjjh89017** [comment]
@fadjar340 good news!
if possible, could you share to us what the network guys did to fix this issue?
thanks a lot

**Comment by fadjar340** [comment]
@tjjh89017 ..

The network guys just add mac address of the harvester into the config each of the switch interface as follow:
![image](https://user-images.githubusercontent.com/1247073/157579739-23003e68-c424-47e1-bc02-dc19e7e80bbf.png)


The mode still in access mode, not in trunk mode, because I need only single subnet to handle my requirement.

Regards,
Fadjar T

**Comment by tjjh89017** [comment]
it seems your switch disable mac learning or enable port security.
it will be fixed mac and port mapping in switch, so if you migrate VM, switch will not allow it.
thanks for sharing!

**Comment by tjjh89017** [comment]
@fadjar340 If you have no further issue on this ticket, I will close it.
if need, please reopen this issue
thanks a lot

**Comment by wzg8723** [comment]
Hi all,
I don't have much knowledge about networks and would like to ask for some advice. Would mac learning aging time cause a connection interruption during the vm live migration?

**Comment by starbops** [comment]
> Hi all,
> I don't have much knowledge about networks and would like to ask for some advice. Would mac learning aging time cause a connection interruption during the vm live migration?

Hi @wzg8723, a few packets might be dropped during the live migration, but it won't cause connection interruption. The MAC addressing table aging time is for standard cases. For the VM live migration case, if a new switch port of a specific MAC address is learned, the new one will supersede the existing one almost immediately.
