### ISSUE TITLE
[BUG] Can delete the last host in the hosts list

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1948]
**Describe the bug**

You can delete the last host in the hosts list, but it never finishes. It just schedules it for removal
**To Reproduce**
1. Create 1 node harvester cluster
2. Log in
3. Navigate to hosts page
4. Delete host
**Expected behavior**

I'm not sure what the desired functionality is here, but here's a few options
1. We could disable the host delete button when there is only 1 host in the list (i'd probably recommend this)
2. We could make the host removal work
3. We could throw an error when trying to remove the last host
**Support bundle**

[supportbundle_2bd06f00-af9f-4a16-aded-42e4f232944f_2022-03-01T19-43-13Z.zip](https://github.com/harvester/harvester/files/8164537/supportbundle_2bd06f00-af9f-4a16-aded-42e4f232944f_2022-03-01T19-43-13Z.zip)

**Environment:**
 - Harvester ISO version: master-bfd6a8a9-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM virtualized environment 1 node

**Additional context**
![Screenshot from 2022-03-01 11-31-07](https://user-images.githubusercontent.com/83787952/156264870-a5beca4f-14b3-4710-b949-6b577d12c148.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-03ee6213-head`(04/15). Close this issue.

### Result
When there is only one node on the Hosts page, Harvester won't provide the `Delete` host button and relative menu options
to prevent user deleting the last node
![image](https://user-images.githubusercontent.com/29251855/163746761-1410fab6-4096-4089-a617-0d3e6e807d8d.png)

### Test Information
* Test Environment: 1 node harvester on local kvm
* Harvester version: `master-03ee6213-head`

### Verify Steps
1. Prepare a one node harvester cluster
2. Access Hosts page
3. Check if there is any delete button or options in this page
