### ISSUE TITLE
[FEATURE] Add VM Access Credential on VM Create Page

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1949]
**Is your feature request related to a problem? Please describe.**

- [https://github.com/harvester/harvester/issues/1538](https://github.com/harvester/harvester/issues/1538)

**Describe the solution you'd like**

We need to support users add Access Credentials on VM Create phase and VM Template Create phase.

**Describe alternatives you've considered**

**Additional context**

**Comment by DaiYuzeng** [comment]
We remove the access credentials yaml if the VM is created by VM Template, need to enhance it in 1.0.2
https://github.com/harvester/harvester/issues/1989

**Comment by guangbochen** [comment]
close as this feature is overlapped with the existing cloud-init template which is more simple and straightforward, thanks.
