### ISSUE TITLE
`runStrategy` is changed when pressing "Stop" button

### ISSUE THREAD

**Issue by nunix** [harvester/harvester#1953]
Depending on how we stop the VM, the setting `runStrategy`, when availalbe, will change to a different state than the original one. 

Here is two scenarios showing the different behaviors.

**Prerequisites**
- Create/Choose a VM and start it
- Edit the `yaml` config
  - Replace `Spec > running` by `Spec > runStrategy`
  - Set the value to `RerunOnFailure`
  - Save the config

**Working**
- Connect to the VM via the Web VNC
- Shutdown from the OS
- The VM will stay in "Starting" state in Harvester UI
  - Edit the `yaml` config
  - `runStrategy` is set to `RerunOnFailure`
- Click the `Start` or `Restart` and wait for the state to be `Running`
  - Edit the `yaml` config
  - `runStrategy` is set to `RerunOnFailure`

**Not working**
- Click the `Stop` button
  - The `Spec > runStrategy` is set to `Halted`
- Click the `Start` button
  - The `Spec > runStrategy` is set to `Always`

## Desired behavior
The issue about the GUI not "updating" to the correct state is followed here: https://github.com/harvester/harvester/issues/1882

For this issue, the desired behavior is to have the second scenario described above, setting the `runStrategy` to the inital state `RerunOnFailure`, instead of `Always` when we click the button `Start`.

Hope this is clear and if I need to provide any further information.

**Comment by tjjh89017** [comment]
related to kubevirt behavior https://github.com/kubevirt/kubevirt/issues/7295
related to kubevirt PR https://github.com/kubevirt/kubevirt/pull/7294

**Comment by tjjh89017** [comment]
according to https://kubevirt.io/user-guide/virtual_machines/run_strategies/#virtctl
![image](https://user-images.githubusercontent.com/2821179/157809119-7766d7fb-f0cf-41cb-b56b-0a3332b0763e.png)

Kubevirt will stop VM with RerunOnFailure with Halted.
Kubevirt didn't have any plan to change the Strategy policy at this stage.
Put this to icebox first.

**Comment by tjjh89017** [comment]
We decided to change default runStrategy to Manual because of minimal side effect and common hypervisor's behavior.
related to https://github.com/harvester/harvester/issues/2060
