### ISSUE TITLE
[BUG] When adding a user via text in access control settings you can get an error

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#1961]
**Describe the bug**

You can add an invalid user to Access credentials page to 
**To Reproduce**
1. Create a new VM
2. Edit config of VM
3. Go to access credentials
4. Add new SSH credential
5. Enter invalid user
6. Select valid SSH key
7. Hit save
8. You get an error
9. Click in username
10. Click the invalid username
11. Click Save
**Expected behavior**

You should not get that error and you should be prompted to either create a user, or entering in the name should create the user
**Support bundle**

[supportbundle_807e9b2e-db5d-4f21-b155-d71c4dbb8a00_2022-03-03T22-10-28Z.zip](https://github.com/harvester/harvester/files/8181486/supportbundle_807e9b2e-db5d-4f21-b155-d71c4dbb8a00_2022-03-03T22-10-28Z.zip)

**Environment:**
 - Harvester ISO version: master-9ecb4f9d-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM single node

**Additional context**
If you go into the username field then click add new user it works the way you would expect and doesn't error out. This is pretty specific so I attached a GIF of the issue
![access-credentials-error](https://user-images.githubusercontent.com/83787952/156661434-65bd41db-c68d-40bc-8d34-4964fab9153c.gif)
![Screenshot from 2022-03-03 14-01-20](https://user-images.githubusercontent.com/83787952/156661556-e47af7c5-8e93-4bce-a65a-028c8d61dd8a.png)

This is a bug in #1538

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

https://user-images.githubusercontent.com/5169694/158533791-2eb58e84-0f6f-4b3e-b8a4-efef18f9102d.mp4


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-60b2fe4d-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/1961#issue-1158954926
