### ISSUE TITLE
[BUG]  login with member role, the harvester dashboard page does not display correctly.

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1962]
**Describe the bug**

The user login with the member role,   Entering the harvester cluster, the dashboard page reports an error
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/f7a8cffc-8eb3-4a68-a537-4f8bacaf7393)
**To Reproduce**

  1. login with member role
  2. click Virtualization Management menu
  3. Select a harvester cluster to enter
  4. Page Error （Unknown schema for type: harvesterhci.io.upgrade）

**Expected behavior**

The page should display normally.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/157842335-9c7dae85-1b4f-4847-8493-fc847b74ed07.png)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-75cc3ced-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6.3-patch2-rc1**

### Verify Steps:
1. Install Harvester with any Nodes
2. Install Rancher and Create **Standard User** `test` in _Users & Authentication_
3. Import Harvester into **Virtualization Management** and add `test` in **Member Roles** tab
4. Login as user `test` then navigate to Virtualization Management
5. Imported Harvester should be available
6. Imported Harvester should be accessible
