### ISSUE TITLE
[BUG]  access credentials is empty

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1967]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/f9b8fe44-5df3-4935-bab5-0562e6a1f4b3)

**To Reproduce**
1.  create a vm  （need Install quem-guest-agent）
2.  When the vm is successfully created, edit the vm, click access Credentials tab
3.  click `add basic Auth`,   add user,  Enter an invalid user  (e.g:  user:  text:,  password: password1234)
4.  click save
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/b2846b67-fbd9-444b-86f6-e0a7de93abe8)
5. click cancel
6.  edit vm again
7.   save vm
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/02356c6c-72de-4cd8-8b0c-b0952bcb3183)

**Expected behavior**

vm can edit successfully

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/157410162-053ac0ac-8182-48b2-b8c8-e74a060b14c1.png)

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-fd872c99-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- follow **steps to reproduce** in https://github.com/harvester/harvester/issues/1967#issue-1160550362
