### ISSUE TITLE
[BUG] "Default version" doesn't work on Modify template page

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#1968]
**Describe the bug**

"Default version" doesn't work on Modify template page

**To Reproduce**
1. Go to Advanced -> Templates
2. Select a template (e.g. windows-iso-image-base-version), select "Modify template" on the right side menu
3. Checked "Default version"
4. Click the save button

**Expected behavior**

The new template should be the default version

**Environment:**
 - Harvester ISO version: master-dba85940-head

**Comment by TachunLin** [comment]
Verified **fixed** on master-da3f1778-head (3/07). Close this issue.

### Result
When we modify the template to create a new version, after checking `default version`
The new created template will be set as default 

![image](https://user-images.githubusercontent.com/29251855/157045906-cd32af97-a634-4942-b7ff-62050487729d.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machines
* Harvester version: master-da3f1778-head (3/07)

### Verify Steps
1. Go Advanced -> Templates
2. Modify the windows-iso-image-base-version to create new version
3. Checked the `default version` and save
4. Verify the new template set as the default
