### ISSUE TITLE
[Question]The NTP address is required for deployment？

### ISSUE THREAD

**Issue by Vanlius** [harvester/harvester#1969]
I deploy Harvester on a LAN and cannot connect to the extranet.
If I need to enter the NTP service address, can't I skip some options during deployment?
How to skip if you can.

**Comment by bk201** [comment]
@Vanlius I believe you can press enter again to skip the NTP dialog in the installer. NTP server is not a hard requirement to install Harvester, but we highly recommend it.

**Comment by Vanlius** [comment]
thsnks，have been passed.
