### ISSUE TITLE
Login failed by using kubeConfig

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#197]
**Steps to reproduce:**
1. Login in a kubeConfig way
2. Use the kubeConfig file and log in

**Result:**
The page keeps logging and the API returns 500 error
![image](https://user-images.githubusercontent.com/57614736/95648948-a07da000-0b0d-11eb-8bee-87a4733915bd.png)
![image](https://user-images.githubusercontent.com/57614736/95649026-09fdae80-0b0e-11eb-97c9-8efaacac3782.png)

**Comment by DoNotSayYes** [comment]
**Result:**
No error message shows and the page keeps logging in when the server does not respond. @DaiYuzeng 

**Steps to reproduce:**
1. On the login page
2. Disconnect the network
3. Upload the config file to log in

![image](https://user-images.githubusercontent.com/57614736/99942143-20a05200-2daa-11eb-8142-bac0119a9fe7.png)

**Comment by DaiYuzeng** [comment]
we add a timeout configuration of the login api.

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/101451417-16b04e80-3967-11eb-842a-a8fba2169938.png)
