### ISSUE TITLE
[BUG]  Delete the edit feature of the backup details page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1978]
**Describe the bug**

The edit feature here is redundant for the user
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/c4e3bf17-a6a8-4b18-ac92-f68ed6289d0a)
**To Reproduce**
1. go to backup page
2. Click the existing backup to enter the details page

**Expected behavior**

Remove the config option from the details page

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified _Backup_'s `Edit Config` option has been removed.

![image](https://user-images.githubusercontent.com/5169694/164724714-1a1d0f11-e1dc-449c-b9e6-64cd8b5c0a8f.png)
![image](https://user-images.githubusercontent.com/5169694/164724734-8814f58d-6707-424b-8485-4e8f30e6125c.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.1**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with any nodes
2. Setup Backup target
3. Create an Image for VM creation
4. Create VM `v1` then backup it as `v1b`
5. Navigate to _Backups_, click options button of _v1b_, the option **Edit Config** should not exist
6. View backup _v1b_, tab **Config** should not exist
