### ISSUE TITLE
[Question]how to access minio

### ISSUE THREAD

**Issue by iamwlb** [harvester/harvester#1980]
harvest use minio to storage.
i want know how to access minio and manage the file in minio?

**Comment by tlehman** [comment]
I don't see an minio pods, you can see all pods in your harvester cluster by using `Ctrl-backtick` and typing `kubectl get pods --all-namespaces`

Also in the go.sum file in the source code: https://github.com/harvester/harvester/blob/master/go.sum#L1311-L1316 it shows that only minio clients are pulled in my harvester.

I'll pass this one over to the team to see if they see anything I might have missed, but I think this it not available.

**Comment by iamwlb** [comment]
@tlehman 
you know we upload docker-images and iso files to harvester.
Earlier versions, the harvester used minio storage.
I'm not sure whether the harvester still uses minio in the current version.
Sometimes, I need to check whether the files uploaded by users have viruses, how can I access the files uploaded by users.

**Comment by yasker** [comment]
@iamwlb Longhorn is no longer using Minio.

In the future, we might introduce a native S3 feature to Harvester, but it will take a while.
