### ISSUE TITLE
[Question]how to communicate from pod to VM

### ISSUE THREAD

**Issue by iamwlb** [harvester/harvester#1981]
in the default namespace.
1. i create a pod and a vm.
2. create a pod-svc and vm-svc.
but how to communicate from pod to vm?

**Comment by yaocw2020** [comment]
You can use the management network for the VM.

**Comment by tlehman** [comment]
@iamwlb The way to use the management network for the VM is to go into Networks, create a VLAN that uses the management network, set the VLAN ID = 1, and then edit the VM network config to use that VLAN.

**Comment by iamwlb** [comment]
@tlehman thank you very much.
i will try this later.
