### ISSUE TITLE
[BUG] upgrade_manifest enhancements

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#1982]
**Describe the bug**

In [upgrade_manifest](https://github.com/harvester/harvester/blob/master/package%2Fupgrade%2Fupgrade_manifests.sh) stage, we bump Rancher and ManagedChart versions. There are several things that needed be done here to smoothen the upgrade.

- Wait for Rancher ready
  - Wait for rancher, fleet, and system-upgrade-controller pods to be upgraded.
  - After this, we need to ensure cluster provision is done. This somehow can minimize the impact of [RKE2 restart].(https://github.com/harvester/harvester/issues/1707#issuecomment-998484833)
- Pause managedchart: I saw situation managechart bundles go into `ErrApplied` when changing cluster-repo.
- Need a way to refresh the cluster-repo. Rancher seems to update chart index only for a certain period.
  - [By default the index is updated every 5 minutes, we can use `forceUpdate` field to trigger an update ](https://github.com/rancher/rancher/blob/47c22388c5451c74f55e162d1e60b4e6dcfd0800/pkg/controllers/dashboard/helm/repo.go#L290-L294 )
- Wait for Harvester ready
  - We can't simply bump the Harvester managed chart version, because the upgrade might involve many components upgrade. We need to wait them to settle down.
- Wait for Monitoring ready

**Comment by TachunLin** [comment]
Verified **fixed** on one click upgrade to v1.0.1-rc2. Close this issue.

### Result
After the enhancement of upgrade_manifest stage stage, we can 100% complete the **`Upgrade System Service`** stage for the one click upgrade on 3 nodes harvester cluster. 

![image](https://user-images.githubusercontent.com/29251855/162130756-562a7082-6ee5-4428-aba9-ac7f36b9f86e.png)
 
### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: v1.0.0 GA to v1.0.1-rc2

### Verify Steps
1. Prepare v1.0.0 three nodes harvester cluster on Provo machines
3. Create a ubuntu and SLES JeOS image
4. Create a ubuntu and SLES virtual machine
5. Enable network to `harvester-mgmt`
6. Create a virtual network `vlan1` with id `1`
7. Setup back target to AWS S3
8. Create two backups for the ubuntu and SLES VM
9. Shutdown all VMs
10. Follow the steps to upgrade to v1.0.1-rc2
https://github.com/harvester/docs/blob/42598035cfe79856f7e159d4c47c4d7d29178900/docs/upgrade/automatic.md
11. Check the upgrade status on dashboard UI
12. Check can 100% complete the `Upgrade System Service` stage

### Additional Context
* Support Bundle
[supportbundle_138129b2-b170-4944-bcae-bc40ff88707e_2022-04-07T05-48-23Z.zip](https://github.com/harvester/harvester/files/8439975/supportbundle_138129b2-b170-4944-bcae-bc40ff88707e_2022-04-07T05-48-23Z.zip)
