### ISSUE TITLE
[BUG][Multiple Cluster]Project Member cannot create resources in harvester-public ns

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1986]
**Describe the bug**

**To Reproduce**
1. Go to Template Create Page
2. Switch to harvester-public namespace
3. Create Template faile

webhook throw errors
```
[virtualmachinetemplates.harvesterhci.io](http://virtualmachinetemplates.harvesterhci.io/) is forbidden: User "u-h4m68" cannot create resource "virtualmachinetemplates" in API group "[harvesterhci.io](http://harvesterhci.io/)" in the namespace "harvester-public"
```

**Expected behavior**

1. Member role could create resources in harvester-public namespace

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
Project Members only have `Read-Only` permission in `harvester-public`.

**Comment by WuJun2016** [comment]
filter the options for `harvester public` in the namespace drop-down box on the resource creation page.

**Comment by n313893254** [comment]
Requires backend help. The harvester-public namespace should not be edited on the namespace page. Thus UI can filter the namespace select options by `links.update`. Feel free to assign me again when the backend is ready.

**Comment by guangbochen** [comment]
@n313893254 this issue is identical to the https://github.com/harvester/harvester/issues/2485, can u please help to take a look, thanks. cc @futuretea

**Comment by n313893254** [comment]
Also the same as https://github.com/harvester/harvester/issues/2485#issuecomment-1252333909

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.1.0-rc1` and Rancher `v2.6.9-rc2` with the appropriate remote ui-index for the 2.6.9 branch and external on Harvester. 

## Verification Steps
1. Import Harvester into Rancher
2. Create cluster member user
3. Add user to be a cluster member in Harvester via RBAC
4. Log out and log back in as cluster member
5. Navigate to Harvester dashboard via virtualization management
6. Navigate to templates page
7. Try to create a new template in `harvester-public` namespace

## Expected Results
- You can create a new template

## Actual Results
- There was no option to create a new template
![Screenshot_20220928_162417](https://user-images.githubusercontent.com/83787952/192905961-1b42dee3-a998-4ea4-acdc-2ac1aed7c3e4.png)
I might be misunderstanding the original steps. It said project member, but harvester-public is a namespace that isn't in a project. Did we just remove the option since it sounds like that was a read only space anyways? If this is the expected behavior let me know. CC @n313893254 @DaiYuzeng

**Comment by n313893254** [comment]
@noahgildersleeve Thanks for your testing. Sorry for the reproduced steps are not detailed. And there have a backend issue [2788](https://github.com/harvester/harvester/issues/2788) that makes harvester-public very confused.

Here are my reproduce steps:

1. Import Harvester into Rancher
2. Create cluster member user
3. Add a user to be a cluster member in Harvester via RBAC
4. Log out and log back in as a cluster member
5. Navigate to the Harvester dashboard via virtualization management
6. Create a project and a namespace
7. Navigate to the templates page
8. Try to create a new template in the harvester-public namespace

**Expected Results**
Users can see the harvester-public namespace in the dropdown but cannot create it successfully. 

And after issue [2788](https://github.com/harvester/harvester/issues/2788) was fixed, the harvester-public namespace will be hidden in the dropdown.

**Explorer Test case**:
1. Login Rancher as an admin user
2. Create a user whose name is "member"
3. Go to the local cluster -> Cluster member, Add a custom role: "View All Projects" for "member" 
4. Create a new project with a new namespace, and then add "member" as the project read-only member.
5. Add a custom role: "Manage Workloads" for "member" 
![image](https://user-images.githubusercontent.com/18737885/193199646-9c2979e4-a16e-4d51-a3ef-1c9c89008562.png)
6. Login as the "member" user
7. Go to create workload page, check the dropdown menu

**Expected Results**
No namespace options can be selected.

![image](https://user-images.githubusercontent.com/18737885/193202580-769505f4-dc26-447c-9da7-879e90c0fd10.png)

**Comment by noahgildersleeve** [comment]
I tested this on Harvester tried the following steps and got this error on trying to create a project
![Screenshot_20221005_144607](https://user-images.githubusercontent.com/83787952/194181172-06a2c31d-bdb2-4fd4-8684-6e9e36fe1a93.png)

However the projects were created

![Screenshot_20221005_161903](https://user-images.githubusercontent.com/83787952/194181205-0ad26c8d-03e4-4bcc-8161-c8ad9595befb.png)

I created the namespace and then when I tried to create the template I got this error

![Screenshot_20221005_162000](https://user-images.githubusercontent.com/83787952/194181233-d1bc8127-3533-4f33-9dc0-1e0416665b31.png)



> Here are my reproduce steps:
> 
> 1. Import Harvester into Rancher
> 2. Create cluster member user
> 3. Add a user to be a cluster member in Harvester via RBAC
> 4. Log out and log back in as a cluster member
> 5. Navigate to the Harvester dashboard via virtualization management
> 6. Create a project and a namespace
> 7. Navigate to the templates page
> 8. Try to create a new template in the harvester-public namespace
> 
> **Expected Results** Users can see the harvester-public namespace in the dropdown but cannot create it successfully.
> 
> And after issue [2788](https://github.com/harvester/harvester/issues/2788) was fixed, the harvester-public namespace will be hidden in the dropdown.
> 
> **Explorer Test case**:
> 
> 1. Login Rancher as an admin user
> 2. Create a user whose name is "member"
> 3. Go to the local cluster -> Cluster member, Add a custom role: "View All Projects" for "member"
> 4. Create a new project with a new namespace, and then add "member" as the project read-only member.
> 5. Add a custom role: "Manage Workloads" for "member"
>    ![image](https://user-images.githubusercontent.com/18737885/193199646-9c2979e4-a16e-4d51-a3ef-1c9c89008562.png)
> 6. Login as the "member" user
> 7. Go to create workload page, check the dropdown menu
> 
> **Expected Results** No namespace options can be selected.
> 
> ![image](https://user-images.githubusercontent.com/18737885/193202580-769505f4-dc26-447c-9da7-879e90c0fd10.png)

**Comment by n313893254** [comment]
> I created the namespace and then when I tried to create the template I got this error

Yep, as the issue [2788](https://github.com/harvester/harvester/issues/2788), The harvester-public can select but cannot create successfully.

> I tested this on Harvester tried the following steps and got this error on trying to create a project

That might be another issue, are you reproduce it always and can you submit the issue?

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-61a6124a-head` and Rancher `v2.6.9-rc4`.

When trying to create a template with a cluster member in harvester-public NS I got this error again.

![Screenshot_20221013_172532](https://user-images.githubusercontent.com/83787952/195735400-d1163cf8-039a-4459-9842-0bee1486abe4.png)

**Comment by WuJun2016** [comment]
The UI part is complete and the rest needs to be enhanced with the backend in v1.1.2.

1. If you use project-member login, the harvester-public namespace should not have the `link.update` interface， because `link.update` determines whether the user can update and create resources

**Comment by futuretea** [comment]
Problem: https://github.com/harvester/harvester/issues/2485#issuecomment-1252333909
Harvester issue: https://github.com/harvester/harvester/issues/2788
Rancher issue: https://github.com/rancher/rancher/issues/39129

**Comment by guangbochen** [comment]
Move the issue to the v1.2.0 milestone; this is related to MCM and depends on https://github.com/rancher/rancher/issues/39129.

**Comment by guangbochen** [comment]
The root cause depends on the fix of https://github.com/rancher/rancher/issues/39129, close as this is already mitigated on the Harvester UI and will be tracked separated by the https://github.com/harvester/harvester/issues/2788.
