### ISSUE TITLE
[BUG]  stop VM, the state of the VM changes to VM error,    pause a vm, an inappropriate message will be displayed in the vm list

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#1987]
**Describe the bug**

1. Stop a running vm, the vm status will have an error intermediate state，  
![image](https://user-images.githubusercontent.com/24985926/157437312-a56da312-ecf4-4827-9df8-1cc58693d21f.png)

2. pause a vm, an inappropriate message will be displayed in the vm list
![image](https://user-images.githubusercontent.com/24985926/157438405-7cd34679-1ab9-4a4f-b331-a506db22ac78.png)

**To Reproduce**
stop vm:
1.  create a vm
2. Wait for vm to turn into running
3. Stop the VM
4. The VM displays an incorrect state  （VM error）

pause vm：
1.  create a vm
2. Pause this vm 

**Expected behavior**

1.  The `VM Error` state should not be visible to the user

2.  pause vm, the user should not see this alert message

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
After @FrankYang0529  investigation, it may be caused by the following lines of code (kubevirt)

https://github.com/kubevirt/kubevirt/blob/f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3/pkg/virt-controller/watch/vm.go#L726-L727

https://github.com/kubevirt/kubevirt/blob/f8160a0b5eac2acafab74fd7916bfcaf0c39a6a3/pkg/virt-controller/watch/vmi.go#L821-L831

https://github.com/kubevirt/kubevirt/commit/2d13c83ab6379357833531cb4c9d0674dee95513

**Comment by FrankYang0529** [comment]
Failure message in stop-action: https://github.com/kubevirt/kubevirt/pull/7340

**Comment by WuJun2016** [comment]
`Paused` will be enhanced on the frontend, and the `stop` problem will be fixed by the back end.
cc @FrankYang0529

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

https://user-images.githubusercontent.com/5169694/157844455-50526e3f-bab0-49cd-a974-e9f36d48f124.mp4

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-75cc3ced-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/1987#issue-1163856304
