### ISSUE TITLE
[BUG]VM created by VM Template with Access Credentials use the same secret

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#1989]
**Describe the bug**

**To Reproduce**
1. Create a VM A
2. Add Access Credentials to VM A
3. Generate VM Template
4. Create VM B via the VM Template
5. The VM B created by VM Template use the same secret to VM A

**Expected behavior**

VM created by VM Template could create secrets correctly

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
We remove the access credentials yaml if the VM is created by VM Template, need to enhance it in 1.0.2

https://github.com/harvester/harvester/issues/1949

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
VM created by template will not have any **Access Credentials**.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-75cc3ced-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to Reproduce** in https://github.com/harvester/harvester/issues/1989#issue-1164669600
- The VM in `step 5.` should not have any **Access Credentials**
