### ISSUE TITLE
[Question] About kubeconfig (String) harvester kubeconfig in terraform 

### ISSUE THREAD

**Issue by ziyi-bear** [harvester/harvester#1994]
I have study the configuration on tereaform, but i cant figure out how to use kubeconfig as a string. Is this means to convert the kubeconfig as single line string? Or as json format?

 Try to move some server from exsi to harvester, i have manage to installed it, but still stuck at terraform, thanks

**Comment by futuretea** [comment]
@ziyi-bear just use the path of your kubeconfig file, such as `/home/ubuntu/.kube/config`
