### ISSUE TITLE
[FEATURE] Switch Harvester CSI driver base image to SLE BCI

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#1995]
**Is your feature request related to a problem? Please describe.**
Switch Harvester CSI driver base image to SLE BCI as It's maintained much better than e.g. alpine.

**Additional context**
refer to: https://github.com/harvester/harvester/issues/1868

**Comment by bk201** [comment]
@yaocw2020 Do you remember what blocks the migrations? Thanks.

**Comment by yaocw2020** [comment]
> @yaocw2020 Do you remember what blocks the migrations? Thanks.

nfs-common

**Comment by guangbochen** [comment]
may refer to https://github.com/harvester/harvester/blob/master/package/Dockerfile#L3, also please help to bump the [golang build version](https://github.com/harvester/harvester-csi-driver/blob/master/Dockerfile.dapper#L1) to v1.18.3

**Comment by Vicente-Cheng** [comment]
It can be tested with https://github.com/harvester/harvester/issues/3052. Just noted

**Comment by bk201** [comment]
Will be verified in https://github.com/harvester/harvester/issues/3052
