### ISSUE TITLE
[BUG] Dashboard UI time out does not work as expected.

### ISSUE THREAD

**Issue by rsguru** [harvester/harvester#1997]
**Describe the bug**
The dashboard UI time out does not work as expected. If you leave for a while opened in your browser, the dashboard won't give you time out ( log you out), but it will give you an error on anything that you want to modify or create. The error message also very limited with not much information there. The error message that gives to you is: {data:} in read on the bottom left side on dashboard page.
However, if you force log out and log back in, you would be able to create/modify what you were working before. ( example: create a vm, edit a volume, etc)

**To Reproduce**
1. Login to the Harvester dashboard UI on your web browser and leave it without forcing login out for a while ( about 12 hours in my case). When you go back and try to do any tasks (modify/create), you will get the error message  {data:} in red and won't be able to conclude the task. ( example: create a vm, edit a volume, etc)

**Expected behavior**
The normal behavior of a GUI would be one of the 2 options:
1 - The time out in the dashboard takes longer and after a while leaving the dashboard on your web browser, you would be able to continue work as normal. You don't need to force a log out in order to be able to work on your dashboard.
2- The time out happens and you get the login screen to be able to log back in to the UI.

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
  2 X Baremetal ProLiant DL360 Gen9 
  I am using chrome Version 99.0.4844.51 on OpenSUSE15.3

**Comment by torchiaf** [comment]
@rsguru Thanks for the bug report. Are you accessing Harvester UI from the Rancher dashboard ?

**Comment by votdev** [comment]
With Harvester >= 1.3 there is no such option in the Harvester UI. So i think @rsguru is talking about 

![grafik](https://github.com/harvester/harvester/assets/1897962/77381900-fa67-447c-907c-35ea822cdabf)

which is in Rancher.

> The dashboard UI time out does not work as expected. If you leave for a while opened in your browser, the dashboard won't give you time out ( log you out), but it will give you an error on anything that you want to modify or create.

This is the intended behavior as mentioned in the settings page:
```
When enabled and the user is inactive past the specified timeout, the UI will no longer fresh page content and the user must reload the page to continue.
```
![grafik](https://github.com/harvester/harvester/assets/1897962/106e71db-2263-4d86-817c-0bec0ac9e30a)


With the following settings
![grafik](https://github.com/harvester/harvester/assets/1897962/478df1b0-d690-4393-b9d3-531bd3fe420c)
i got logged out automatically.
![grafik](https://github.com/harvester/harvester/assets/1897962/14c20885-4f5d-4d30-b3eb-ae38cabbf189)

**Comment by bk201** [comment]
close as it should be a rancher issue, feel free to open again if needed.
