### ISSUE TITLE
add local auth user of harvester

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#200]
**Description:**
1. support basic auth login with the default username and password.
2. support multi-users, user can only create the admin user for now from the UI.
3. when adding an admin user, create an associated role and rolebinding for it.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/199

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/199 https://github.com/rancher/harvester-ui/pull/141

**Comment by gsuess** [comment]
So is it possible to setup multiple users now?

**Comment by flapili** [comment]
@gsuess and others, I got it to work by creating a new user from [ui](https://123.123.123.123/dashboard/c/local/explorer/management.cattle.io.user) (I got this url with few kubectl get crd & some describe)

but you have to deal with role too, I just added a [clusterRoleBindings](https://123.123.123.123/dashboard/c/local/explorer/rbac.authorization.k8s.io.clusterrolebinding) to the fresh user, even if it's not the best way to deal with security it's a good start for now

(replace 123.123.123.123 by your real harvester VIP)
