### ISSUE TITLE
[BUG] Project view shows another project resouces

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2001]
**Describe the bug**

Project view shows other project resources.

<img width="1573" alt="image" src="https://user-images.githubusercontent.com/18737885/157829881-4035c961-3743-4477-983a-53b74e549a74.png">

 Related manual test case: https://harvester.github.io/tests/manual/harvester-rancher/11-create-project-harvester/

**To Reproduce**
1. Create a project named "testProject".
2. Create a namespace named "test-project".
3. Change to "Project: testProject" view on the top-right nav menu selector.
4. Go to VM page
5. Logout and then log in.

**Expected behavior**

Only shows VMs which belong to "test-project", which means the list should be empty.

**Additional context**
Refresh page can easily reproduce

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/164724111-75d3826f-f254-41cd-805d-3b2b932a2740.png)
![image](https://user-images.githubusercontent.com/5169694/164724150-e6aff4e5-c892-473b-bde2-743ae2cdda0e.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.1**
* **ui-source** Option: **External**
* Rancher Version: **v2.6.4**

### Verify Steps:
- Install Rancher and Harvester
- Import Harvester into Rancher
- Login to Rancher dashboard, navigate to Virtualization Management to access Harvester
- Navigate to **Projects/Namespaces**, Create a Project and Namespace
- Navigate to **Virtual Machines**, the filter of _Namespaces_ should filter out unrelated projects/namespaces.
