### ISSUE TITLE
[Feature]  Enhancement of qemu-guest-agent design

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2002]
**Describe the bug**

The qemu-guest-agent related design may be confusing to users.  

**To Reproduce**
Reproduction steps：
case 1:
1. go to `Cloud Config Templates` page
2. Create a `user data` template with the following yarm,  
```
#cloud-config
password: root
chpasswd: { expire: False }
ssh_pwauth: True
```
3. go to `Virtual Machines` page
4. click `Create` button
5. Enter `name`、`cpu`、`memory`
6. click `volume` tab，  choose image
7. click  `Advanced Options`,  check `Install guest agent`
8. Select the previously created `User Data` template 

The` Install guest agent` checkbox will be unchecked automatically

case 2:
1. go to `Cloud Config Templates` page
2. Create a `user data` template with the following yarm,  
```
#cloud-config
package_update: true
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - '--now'
    - qemu-guest-agent.service
```
3. go to `Virtual Machines` page
4. click `Create` button
5. Enter `name`、`cpu`、`memory`
6. click `volume` tab，  choose image
7. click  `Advanced Options`,  uncheck `Install guest agent`
8. Select the previously created `User Data` template 

`Install guest agent` is automatically checked

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/3ece9b85-4fb4-447e-be70-829984ae716b)

**Expected behavior**

case 1 expected behavior:   Perform merge operation
case 2 expected behavior:  Take the value in the template as the first priority

The rules are as follows：
1.  We use the value in the template as the first priority, and when there is a conflict between the value in the template and the external one, we do a merge operation on the user data and map it to the external checkbox

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-b20a3b47-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **To reproduce** in https://github.com/harvester/harvester/issues/2002#issue-1166278490
