### ISSUE TITLE
[BUG] Harvester UI cloudconfig `packages` option being overwritten on VM creation

### ISSUE THREAD

**Issue by nikitawootten** [harvester/harvester#2006]
**Describe the bug**

When configuring a VM with cloud config, the `package` field is being overwritten, preventing additional packages from being provisioned.

**To Reproduce**
1. Create a VM that uses cloud config. I'm using the Ubuntu focal image
2. Under "Advanced Options", add a package to the cloud config user data (being sure to select the Ubuntu OS type):
    ```yaml
    ...
    packages:
      - qemu-guest-agent
      - docker.io
    ...
    ```
    ![image](https://user-images.githubusercontent.com/8916363/158083823-36f77a73-f679-475c-94ad-5596cd9c1718.png)

3. Create the VM

**Expected behavior**
The newly created VM's `Cloud Config` tab should reflect the options I gave it, but the package has been removed:
![image](https://user-images.githubusercontent.com/8916363/158083863-3adb9ac3-35bc-44e4-9b6d-45fff2e47724.png)
When the VM is created, the added package should be installed:
```
ubuntu@test:~$ dpkg -l docker.io
dpkg-query: no packages found matching docker.io
```

Is there some weird templating going on that overrides certain options in a way that is opaque to the user?

Also notice, in the first screenshot I emptied the `ssh_authorized_keys` setting, but when the VM was created that option was repopulated. I suspect this behavior is related.

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure: Baremetal with Dell PowerEdge R710

**Additional context**
I ran into this issue while attempting to create a template with Docker pre-configured.

**Comment by nikitawootten** [comment]
Note: this seems to even happen if I uncheck the guest additions installation.

**Comment by WuJun2016** [comment]
Hi,  @lanfon72    I accidentally lost some code to fix the problem when I rebase the code （https://github.com/harvester/harvester/issues/1856）,  which caused the problem to reappear， 
 please help to revalidate the problem,  thanks a lot.

**Comment by lanfon72** [comment]
@WuJun2016 so it's the duplication of #1871 ?

**Comment by WuJun2016** [comment]
> 

yep

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

https://user-images.githubusercontent.com/5169694/158143094-7fc2ca97-7a38-4ba5-b950-9a56ac02fc59.mp4


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-75cc3ced-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Same as https://github.com/harvester/harvester/issues/1871#issuecomment-1040402823
