### ISSUE TITLE
support for VLAN network of vms

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#201]
**Description:**
support for VLAN network of VMs

Requirements:
1. cluster-admin will be able to configure the cluster network configuration(i,e set the default NIC of VLAN bridge) using the harvester settings CRD
2. the network setting will have 2 fields, NIC: the physical network interface card used by the VLAN bridge, configured-NIC: previous configured NIC using for network re-setting(default to empty and will be automatically updated when updated).
3. creating a new `harvester-network-controller` to list and watch the settings CRD, this will be running as a Daemonset to manage the host bridge network configuration/re-configuration, by default when the network setting is empty it will do nothing until the admin configured the 1st  NIC in network settings.
4. will add the `harvester-network-controller` to the helm-chart as a sub-chart.

**Comment by guangbochen** [comment]
link to the [harvester-network-controller](https://github.com/rancher/harvester-network-controller)

**Comment by DoNotSayYes** [comment]
Validated
