### ISSUE TITLE
[Question] Security updates?

### ISSUE THREAD

**Issue by ghost** [harvester/harvester#2017]
Hi,

I have been looking at Harvester for a bit, and I was just wondering how security updates are handled? Just as an example let's say a root escalation bug has been fixed in the linux kernel, or some other security bug.

How would I patch something like that? I didn't find any info about this. Would you need to release a new harvester iso, like 1.0.2, or is there some other way of applying updates?

**Comment by simonflood** [comment]
The online docs at https://docs.harvesterhci.io/v1.0/upgrade/automatic/ only has "One-click upgrade will be supported starting with the v1.0.0 release."

When I've previously asked this (elsewhere) the answer has been that this would be handled by a new release which you then use to upgrade your Harvester node(s).

**Comment by yasker** [comment]
Yes, the security update will be handled as a part of Harvester's update in future releases.
