### ISSUE TITLE
[BUG] Harvester WebUI VM page sorting per NODE is not working correctly

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2020]
**Describe the bug**

Harvester WebUI VM page sorting per NODE is not working correctly

**To Reproduce**
1. Deploy a couple of VMs
2. View the VM page, and click "Node" to sort,  the result is not as expected

![image](https://user-images.githubusercontent.com/31133476/158578594-5e5581d4-b522-45ab-ba07-c312dacad707.png)
![image](https://user-images.githubusercontent.com/31133476/158578629-beb2d96f-efa5-4196-b22b-1d2da1a09564.png)
![image](https://user-images.githubusercontent.com/31133476/158578733-7f1be3f5-ad94-40a4-a272-dc4e39cf4f96.png)

**Expected behavior**

VM should be sorted per node as expected 

**Support bundle**

**Environment:**
 - Harvester ISO version:  master-75cc3ced-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-c5f4564f-head` (04/19). Close this issue.

### Result
* VM items **can sort correctly** per `node` in ascend and descend order
  ![image](https://user-images.githubusercontent.com/29251855/163973568-ec62aea8-fdb9-43ff-a829-2c8cbd9a8065.png)
  ![image](https://user-images.githubusercontent.com/29251855/163973630-2707f987-1241-4e77-94d2-8f977ac8a15b.png)

* VM **before** sorting per `node` for comparison
  ![image](https://user-images.githubusercontent.com/29251855/163972937-8ebafa5b-76c2-4678-a86d-3314d86ad767.png)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `master-c5f4564f-head` (04/19)

### Verify Steps
1. Prepare different types of OS images
2. Create at least two VMs for each OS and assign them to different node
3. Open the Virtual Machines page
4. Click the `Node` on the title bar to sort VMs
5. Check the sorting in
