### ISSUE TITLE
[BUG] Harvester reports `ready` status shortly after booting, but user gets 503 errors when visiting VIP.  Harvester then shows `not ready` status for a time, until finally getting to a real `ready` state. 

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2022]
**Describe the bug**

When booting harvester, it reaches a `ready` state. However it quickly goes back to a `not ready` state. This entire time, the cluster is not reachable through the UI (user gets 503 errors). After some time harvester eventually gets to a `ready` state where the user can access harvester UI through the URL. 

**To Reproduce**
1. Install harvester on a machine
2. wait for it to show the 1st `ready` status
3. try to access harvester via the URL

**Expected behavior**

harvester should only show `ready` status once it is fully ready.

**Support bundle**

[supportbundle_ef00de77-99f1-4876-a619-0b061548de01_2022-03-17T00-58-27Z.zip](https://github.com/harvester/harvester/files/8278884/supportbundle_ef00de77-99f1-4876-a619-0b061548de01_2022-03-17T00-58-27Z.zip)

**Environment:**
 - Harvester ISO version:  v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal with dell poweredge r510

**Comment by bk201** [comment]
We need to add a better condition to check the cluster is really ready for service:
https://github.com/harvester/harvester-installer/blob/ededb753e24b2b345c7643da2a66b9912cbbf5c8/pkg/console/dashboard_panels.go#L372-L376

**Comment by emilyastranova** [comment]
I can confirm the same happens for me on every harvester machine I've added, v1.0 release

**Comment by w13915984028** [comment]
I also noticed this scenario. 

In the Console, the management IP/port will be  NODE_IP:6443 at beginning.  The VIP will replace NODE_IP:6443 later.
When it shows "Ready", ping the VIP, which is not reachable, nearly until the second time of "Ready", the VIP is pingable.

**Comment by TachunLin** [comment]
Verified **fixed** master-9285ca26-head (03/25). Close this issue.

### Result
Now once Harvester console UI display `Ready` status, we can directly visit Harvester VIP to enter the bootstrap mode.
It did not go through ready -> no ready -> ready status nor gets 503 nginx error.

![Peek 2022-03-25 22-25](https://user-images.githubusercontent.com/29251855/160141743-a9512489-3906-416b-8332-9137a3385e77.gif)


### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: master-9285ca26-head (03/25)


### Verify Steps
1. ISO install one node harvester
2. Wait for harvester installer boot up 
3. Monitor the console UI 
4. Wait the console display `Ready` status and show VIP
5. Open browser and visit Harvester by VIP
6. Check can directly display bootstrap page without showing nginx 503 error
