### ISSUE TITLE
[Feature] Legacy Iso for older servers

### ISSUE THREAD

**Issue by BobTheDestroyer** [harvester/harvester#2023]
I have an old DL360 G6 currently running Windows Server 2022 that I would like to convert into a Harvester server, however the BIOS does not support UEFI or recognise it as a thing (Illegal OpCode). 

Is it possible to have the ISO support legacy systems (IE UEFI with CSM)?

Thank you

(P.S. if my issue needs a certain format or etc, sorry, I dont use github very often)

**Comment by bk201** [comment]
@BobTheDestroyer I've been running Harvester with legacy BIOS mode as my daily driver. UEFI is not a requirement.
Do you encounter any issues when running Harvester on your server? Thanks.

**Comment by BobTheDestroyer** [comment]
@bk201 , I am not even able to boot from the bootable USB as the ISO is "UEFI (non CSM)", which means that the BIOS on the server can not even interpret the ISO correctly and generates an "Illegal OpCode" error (Red screen of death) when trying to boot from the USB.

To clarify, there is no "UEFI or Legacy mode" in the BIOS, it straight up cannot run UEFI code. It is BIOS only.

**Comment by aperez900907** [comment]
I have the same issue on boot after the installation process.
I was able to begin the installer from the USB stick, then when finished none system booted from the LSI array disks.
any suggestion?

thanks.

**Comment by BobTheDestroyer** [comment]
@aperez900907 What hardware is it running on? If you where able to use the USB booting image, it might be a different problem than the one I highlighted. 

Does your motherboard support UEFI booting?

**Comment by Bebs01** [comment]
I am also interested in this feature. I have a few HP DL380p Gen8 servers that I would like to have running with Harvester. These machines do not support UEFI and will not boot with the current ISO.

**Comment by aperez900907** [comment]
> @aperez900907 What hardware is it running on? If you where able to use the USB booting image, it might be a different problem than the one I highlighted.
> 
> Does your motherboard support UEFI booting?

I am testing on an **Inspur server blade system**, model **NX5760M3** from 2013, 
It enables to boot and load the iso install and forward to the final steps, but after rebooting the system doesn't come up.

Thanks in advance

Best regards.

**Comment by BobTheDestroyer** [comment]
@aperez900907 Dont know too much about that system, but from checking on the documentation found here:
https://www.manualslib.com/manual/1769788/Inspur-Ob5161m5.html?page=20
It seems it supports UEFI. 

Is your bios in CSM enabled or not?

What happens when you check the boot order on startup?

**Comment by tlehman** [comment]
The legacy ISO would have to use a Master Boot Record (MBR), which is a 512 byte sequence that always ends with the bytes `0x55aa`. From the screenshot below, you can see the first 512 bytes (`head -c 512` takes the first 512 bytes of a file) ends with the magic number `0x55aa`, so the harvester ISO is hybrid, meaning it contains a valid MBR and can boot in legacy mode.

I validated this by booting the harvester-master-amd64.iso in qemu using BIOS mode and it booted. I also burned it to a DVD and it booted on my Dell server that has a non-UEFI legacy BIOS.

![image](https://user-images.githubusercontent.com/261552/160877383-5b1ecc59-bc38-455f-8667-2dfba703196a.png)

Also @bk201's [comment](https://github.com/harvester/harvester/issues/2023#issuecomment-1070384164) shows that legacy booting works fine.

As @BobTheDestroyer is getting at, this might be an issue with UEFI with CSM, which this [SU post](https://superuser.com/questions/1284392/what-exactly-is-uefi-with-csm-boot-mode) shows is a distinct mode from legacy BIOS and regular UEFI.

**Comment by lee-b** [comment]
+1, could use in earnest, but cannot even trial/homelab on older/simpler/cheaper boxes without legacy BIOS support.  Give it another half decade at least, before dropping that.

**Comment by tlehman** [comment]
# Current status of this issue

- Legacy BIOS mode is supported and currently boots
- UEFI mode is supported and currently boots
- Possible issue with CSM (Compatibility Support Module being enabled maybe prevent boot, need more input from @aperez900907 )

What I need in order to make progress on this issue are the specs of some common hardware where this issue is happening. We need to be able to reproduce this. If this is only an issue with 9+ year old hardware, then we may have to de-prioritize this.

**Comment by DonThorntonJr** [comment]
I realize that 9+ year old hardware may not be an immediate priority but I was tasked with finding a bare-metal Kubernetes/VM (HCI?) solution (not Tanzu) that would run on recycled hardware that is about 9-10 years old (non-UEFI) for DARPA/USAF.

Harvester WAS the leading choice due to USAF familiarity with Rancher but now that TrueNAS Scale has been released I may have to look at that though it suffers from similar issues on non-UEFI platforms.

I have a number of HP ProLiant DL360p Gen8 1U RackMount 64-bit Server with 2×6-Core E5-2670 Xeon 2.5GHz CPUs + 64GB PC3-10600R RAM + 8×300GB 10K SAS SFF HDD, P420i RAID, 4×GigaBit NIC, 2×Power Supplies that I can test on.

**Comment by BobTheDestroyer** [comment]
@DonThorntonJr I notice that both the hardware you're talking about and mine are HP hardware before UEFI was integrated on their MoBos.

@tlehman  After verification in the Harvester-Installer Github I found that the GRUB code [doesn't do anything if the system isnt UEFI](https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/iso/boot/grub2/grub.cfg) (Line 10 to 15).

This means that it supports Legacy *booting*, but not *actual* old school BIOS motherboards (vs their BIOS via UEFI counterparts) as the instructions sets used don't match.

I use the example of the grub in the harverter-installer, but even after tweaking the GRUB to be compatible with BIOS MoBos and recompiling, there are issues with running the ISO code on old hardware.

As @DonThorntonJr said, there are quite a few large organisations that still use "old" hardware that would benefit from Harvester.

**Comment by DonThorntonJr** [comment]
installing from harvester-v1.0.1-rc2-amd64.iso in VMware Fusion to clean SSD using MBR:

<img width="705" alt="Screen Shot 2022-04-04 at 18 58 27" src="https://user-images.githubusercontent.com/2985322/161657785-55716905-2230-4b4e-8def-f3f0a57a84d1.png">

**Comment by DonThorntonJr** [comment]
I etcher'ed the harvester-v1.0.1-rc2-amd64.iso image to a clean SSD and installed by way of USB to clean SSD using MBR with no issues that I could discern on HP ProLiant DL360p Gen8 with BIOS restored to defaults. - it booted on first try with no issues:
```
Disk /dev/sdi: 465.76 GiB, 500107862016 bytes, 976773168 sectors
Disk model: Samsung SSD 860 
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xbdd1b4cc

Device     Boot    Start       End   Sectors   Size Id Type
/dev/sdi1           2048     98303     96256    47M 83 Linux
/dev/sdi2  *       98304  29394943  29296640    14G 83 Linux
/dev/sdi3       29394944  45019135  15624192   7.5G 83 Linux
/dev/sdi4       45019136 976773119 931753984 444.3G 83 Linux
```
I don't recall if tried MBR on 1.0.x but pretty sure it did not work on 0.3.0

@BobTheDestroyer - thanks for pointing that out!

**Comment by tlehman** [comment]
@DonThorntonJr DARPA and USAF are definitely worthy customers :us:

@BobTheDestroyer If I am reading this grub.cfg right, the default for `${grub_platform} != "efi"` has already been set on [lines 5-6](https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/iso/boot/grub2/grub.cfg#L5-L13), then the EFI case just overwrites those variables. Could you share what changes you made to the grub.cfg? 

If it's true that legacy booting works but then it doesn't support older BIOS motherboards, that would explain @aperez900907 's problem where the installer 
finished, but then the system wouldn't boot afterward. But since lines 5-6 set the non-EFI variables for linux and initrd, I'm not sure I understand the problem.

@DonThorntonJr @aperez900907 @BobTheDestroyer would either of you be interested in a call where you can talk through your setups and help me better understand what's failing?

**Comment by BobTheDestroyer** [comment]
@tlehman As the ``set linux=linux`` flag is specific to [64 bit IBM POWER kernels instead of x86_64 bit BIOS kernels](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/system_administrators_guide/ch-working_with_the_grub_2_boot_loader) (second paragraph in "Menu Entries in grub.cfg"), that line functionally does not work for BIOS Motherboards. 

My modifications where to change that line to ``set linux=linux16`` and splice in the boot files from an Ubuntu 18.04 ISO I had on my hard drive.

After these modifications, the grub worked but once it transferred from the GRUB to the Harvester installer it ended up failing.

Looking at @DonThorntonJr 's installation that worked, I am curious as to the possibility of it working if the SSD containing Harvester is configured from an other device that accepts the ISO. That would mean that the MBR configuration in Harvester is correctly configured, and the problem would be more in the Installer itself.

For the call, i'd be happy to help!

Edit: I will admit that my knowledge of ISO configuration is limited, so it is likely that I have completely missed certain elements of the installer that would have made it work.

**Comment by tlehman** [comment]
@BobTheDestroyer Good catch! I can fix the grub config to include a `set linux=linux16` conditional. I'll try to reproduce the issue that @DonThorntonJr ran into with the installer and then debug from there. Thanks again for all the input!

I'll post a status update at 1pm PDT today. If there are any blockers to identifying what's wrong with the installer, I'll arrange for a call where we can debug this interactively and get this issue resolved.

**Comment by tlehman** [comment]
I [added a check](https://github.com/tlehman/harvester-installer/commit/60eeffee6575bbadfbd27512daedd324b6c5afd1) for `grub_plaform == "pc"` in the grub.cfg, let me know if this looks right.

**Comment by BobTheDestroyer** [comment]
> I [added a check](https://github.com/tlehman/harvester-installer/commit/60eeffee6575bbadfbd27512daedd324b6c5afd1) for `grub_plaform == "pc"` in the grub.cfg, let me know if this looks right.

Seems legit! Thanks again for all the help!

**Comment by tlehman** [comment]
Update: I'm attempting to reproduce the error on a legacy BIOS motherboard (Dell Precision T7500), I'll test out a build with the grub.cfg change as well, and then I'll gather the logs on what failed after the post-install boot.

**Comment by tlehman** [comment]
Using the [d0f7376](https://github.com/harvester/harvester/commit/d0f7376ae3204579bdc40bcf2cec7cf8a4191c80) build (without my grub.cfg change), I installed on a Dell Precision T7500 and it booted without issue. I chose MBR partitioning scheme, and the BIOS (version A16 from 2013) doesn't support UEFI.

Should I go older? I can find some older used machines if it would help provide a more representative background for testing.

**Comment by BobTheDestroyer** [comment]
Does the server see the UEFI options? On my DL360 G6, it could not see the UEFI options.

**Comment by BobTheDestroyer** [comment]
To be more precice, as it is a BIOS motherbord, it *cant* see the UEFI options. Does the Dell Precision T7500 show the UEFI options?

**Comment by tlehman** [comment]
What UEFI options? The T7500 does not have UEFI anywhere in the system setup, and I confirmed that my firmware version (A16) does not support UEFI.

**Comment by tlehman** [comment]
@BobTheDestroyer would you like to hop on the [Slack](https://slack.rancher.io/) and we can talk over audio? It might save some time

**Comment by BobTheDestroyer** [comment]
@tlehman Sent a message on the Slack.

**Comment by tlehman** [comment]
> installing from harvester-v1.0.1-rc2-amd64.iso in VMware Fusion to clean SSD using MBR:
> 
> <img alt="Screen Shot 2022-04-04 at 18 58 27" width="705" src="https://user-images.githubusercontent.com/2985322/161657785-55716905-2230-4b4e-8def-f3f0a57a84d1.png">

That "will not proceed with blocklists" error from grub looks like there's not enough space at the beginning of the disk before the first partition ([link](https://wiki.gentoo.org/wiki/GRUB2/Troubleshooting#:~:text=grub%2Dinstall%3A%20error%3A%20will,the%20beginning%20of%20the%20drive.))

**Comment by DonThorntonJr** [comment]
this was a clean 500GB SSD (not initialized) so not sure if being uninitialized was the issue but saw this twice using Fusion->USB to perform install before Etcher'ing the install ISO to the 500GB SSD directly and installing the system from that.

**Comment by tlehman** [comment]
Summary from talking with @BobTheDestroyer 

On an HP ProLiant DL360 G6 Server (BIOS motherboard without UEFI support):
- USB booting gives a RSoD (Red Screen of Death), and multiple USB keys and multiple etcher programs ruled out a bad flashing
- USB booting of Ubuntu Server and TrueNAS was successful on this machine
- Modifying the [harvester-installer's grub.cfg](https://github.com/harvester/harvester/issues/2023#issuecomment-1088686087) allowed the USB installation to proceed to GRUB, and then it failed after the timer

On an HP ProLiant DL360p Gen8 Server, @DonThorntonJr  experience a similar issue. 

The go-to solution of switching to UEFI mode for installation will filter out a lot of potential users, so we should invest in resolving this issue. Based on this discussion so far, it sounds like it's a problem with harvester-installer.

## Problems with harvester-installer
- Grub must set linux16 if `grub_platform = "pc"`, (fixed in commit [60eeff](https://github.com/tlehman/harvester-installer/commit/60eeffee6575bbadfbd27512daedd324b6c5afd1))
- The failure after the timer needs to be addressed
- Possibly something else after that which hasn't been observed because of earlier failures

I will look at the Ubuntu Server and TrueNAS installers to see what they are doing, and use that to inform what changes we need to make to fix the installer for legacy BIOS mode.

**Comment by DonThorntonJr** [comment]
looking at fdisk, it may be the partition ID's:
```
# fdisk -l /dev/sda
Disk /dev/sda: 465.76 GiB, 500107862016 bytes, 976773168 sectors
Disk model: SSD 870 EVO 500G
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 33553920 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device     Boot   Start     End Sectors  Size Id Type
/dev/sda1  *         64 7928935 7928872  3.8G cd unknown
/dev/sda2       7928936 7937127    8192    4M ef EFI (FAT-12/16/32)
```

**Comment by tlehman** [comment]
Is that `fdisk -l /dev/sda` output from your SSD you etchered the installer onto?

**Comment by tlehman** [comment]
@DonThorntonJr Interesting about the partition ids, @BobTheDestroyer installed ubuntu server with no issues, so I checked and mounted the latest harvester-master-amd64.iso and ubuntu-server-20.04.iso 

```
tobi@earth:~/dl % df -h | tail -2   
/dev/loop13     1.3G  1.3G     0 100% /mnt/iso-ubuntu
/dev/loop11     4.0G  4.0G     0 100% /mnt/iso-harvester
```

Ubuntu:
```
tobi@earth:~/dl % sudo fdisk -l /dev/loop13
Disk /dev/loop13: 1.25 GiB, 1331691520 bytes, 2600960 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x492bdcc4

Device        Boot Start     End Sectors  Size Id Type
/dev/loop13p1 *        0 2600959 2600960  1.2G  0 Empty
/dev/loop13p2       2908   10907    8000  3.9M ef EFI (FAT-12/16/32)
```

Harvester (note the `cd` id and `unknown` type) vs the (`0` id and `Empty` type on the Ubuntu output)
```
tobi@earth:~/dl % sudo fdisk -l /dev/loop11 
Disk /dev/loop11: 3.102 GiB, 4286382080 bytes, 8371840 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0x00000000

Device        Boot   Start     End Sectors Size Id Type
/dev/loop11p1 *         64 8363523 8363460   4G cd unknown
/dev/loop11p2      8363524 8371715    8192   4M ef EFI (FAT-12/16/32)
```

**Comment by tlehman** [comment]
@BobTheDestroyer noted that TrueNAS installed just fine, from looking at the [truenas-installer](https://github.com/truenas/truenas-installer/blob/master/usr/sbin/truenas-install#L392-L400), it uses `sgdisk` to create a BIOS boot partition _and_ an EFI partition, just in case the user wants to switch later. From looking at the [sgdisk manpage](https://linux.die.net/man/8/sgdisk#:~:text=Upon%20start%2C%20sgdisk%20attempts%20to%20identify%20the%20partition%20type%20in%20use%20on%20the%20disk.%20If%20it%20finds%20valid%20GPT%20data%2C%20sgdisk%20will%20use%20it.%20If%20sgdisk%20finds%20a%20valid%20MBR%20or%20BSD%20disklabel%20but%20no%20GPT%20data%2C%20it%20will%20attempt%20to%20convert%20the%20MBR%20or%20disklabel%20into%20GPT%20form), 

> Upon start, sgdisk attempts to identify the partition type in use on the disk. If it finds valid GPT data, sgdisk will use it. If sgdisk finds a valid MBR or BSD disklabel but no GPT data, it will attempt to convert the MBR or disklabel into GPT form. 

The harvester installer does not use sgdisk, I'll look into how we set up the MBR partition table, as that's far more limited, and it's not being done with sgdisk.

**Comment by DonThorntonJr** [comment]
yep - I have had issues with non-standard partition id's on "boot" media mainly with FreeNAS and other BSD installers

**Comment by DonThorntonJr** [comment]
another interesting side effect of installation seems to be the default ntp server 0.suse.pool.ntp.org causes my AT&T  Hotspot to go offline for ~5 min - weird!?!

**Comment by tlehman** [comment]
That is weird! Have you tried other NTP servers? 

I've heard of problems with HTTP and AT&T's transparent proxy, but I'm not sure that's related.

**Comment by tlehman** [comment]
Update: I ordered an HP ProLiant DL360P G8 Server 2.60Ghz 16-Core 96GB 2X 300GB Enterprise (Renewed), it will arrive April 22-26. Once I have the server, I can get a proper repro of this issue and debug it then.

**Comment by rebeccazzzz** [comment]
Moving the community issue review status to "resolved/scheduled" because this issue has been scheduled for an upcoming Harvester release.

**Comment by tlehman** [comment]
The HP ProLiant DL 360p Gen 8 server arrived early, returning to working on this issue

**Comment by tlehman** [comment]
I installed Harvester 1.0.1 using a USB key on this HP ProLiant DL360p Gen8, used MBR partitioning scheme and it booted up and went into a ready state without problems. I used NIC 1 for management network, what's everyone's network setup? Are you using the iLO interface for management or just one of the regular NICs?

![IMG_7600](https://user-images.githubusercontent.com/261552/164107827-313eb939-d556-4775-b80f-6244554d1545.PNG)

![IMG_7602](https://user-images.githubusercontent.com/261552/164107838-21e1370e-45d9-4884-bac5-1cfffd1502da.PNG)

**Comment by tlehman** [comment]
@DonThorntonJr @BobTheDestroyer have either of you tried the latest 1.0.1 release on your DL360 servers?

**Comment by DonThorntonJr** [comment]
not yet - 1.0.1-rc2 is what worked for me

**Comment by yasker** [comment]
Move to Icebox. Waiting for the response from @BobTheDestroyer to confirm if it's fixed in v1.0.1.

**Comment by guangbochen** [comment]
@BobTheDestroyer can u please check if the latest Harvester v1.0.3 release has addressed your issue? Thanks.

**Comment by guangbochen** [comment]
Close due to inactivity, also can't reproduce it in our QA/lab env with the latest v1.0.3 release. Feel free to re-open it if u reencountering this issue, thanks.
