### ISSUE TITLE
[Question]Does harvester support multi-master?

### ISSUE THREAD

**Issue by wonleing** [harvester/harvester#2024]
I want to deploy harvester with 2LB 3masters 3 nodes architecture.
Does it support multi masters and multi nodes? Any doc about this setup?

**Comment by tlehman** [comment]
Harvester does support multi-node setup. The way to achieve this is by installing Harvester on Node 1, setting the token. Then install Harvester on Node 2, but this time select "Join existing cluster" and enter the IP and the token so Node 2 joins the existing Harvester cluster. Do the same for Node 3.

As for multi-masters, I'm not sure what you mean, could you clarify?

**Comment by rodrigo14miguel** [comment]
Hi.
I think master and nodes are referred to master nodes and worker nodes for kubernetes.
@wonleing I have made a new 3 node installation from version 1.0.2 to test this and here is what happend:

- the first node to come up is promoted to master node.
- when you add a second node to the cluster (like @tlehman says), the second node is assigned a compute role (worker node)
- when you add a 3rd node, both the second and 3rd node are promoted to master nodes, making it a multi master cluster

I have not tested adding more nodes but what I see from documentation is that from nodes 4 upwards, they are all assigned compute role (worker nodes).
So yes, you can have a multi master multi worker setup.
Regarding the loadbalancing, i'm not sure what you intend to do but the management VIP changes to another surviving master node when I reboot masters on my cluster.

keep a few things in mind:

- this solution is intended for VMs at the moment. What I see in the community questions is that if you want to use it for kubernetes you should create kubernetes clusters on top of it (with rancher for example).
- the master nodes are schedulable by default (at least for my 2 node and 3 node clusters)

Hope to have helped!

**Comment by wonleing** [comment]
thanks @rodrigo14miguel 
I managed to setup this cluster with 8 physical machine: 2 for load balancer, 3 for master node, 3 for work node.
Make harvester run as a service on this K8s cluster.
