### ISSUE TITLE
[Enhancement] Harvester CPI chart asks for cluster name in UI

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2031]
**Describe the bug**
when deploying harvester CPI chart, it asks for the cluster name. 

**To Reproduce**
1. in rancher, go to `apps & marketplace` and deploy the harvester cpi chart

**Expected behavior**
If this field was necessary, I would expect us to be able to infer the cluster name instead of making the user enter it

**Support bundle**

**Comment by yaocw2020** [comment]
We are unable to get the cluster name on the apps & marketplace question page.

**Comment by guangbochen** [comment]
@n313893254 can u please help to evaluate if the cluster name can be retrieved and set automatically for the users from the front-end side, thanks?

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/165716201-878e2254-9567-438f-b00f-db58098a9592.png)


Test Information
----
* Rancher Version: **v2.6-head-311f462** (Docker Image ID: **f45bf0b95dee**)

### Verify Steps:
1. Install Rancher
2. Login to Rancher, navigate to User's Preference page and switch helm chart option to **Include prerelease versions**
3. Navigate to a cluster
1. Go to Apps/Repositories, Create a repository with Target: **Git repository**, Git Repo URL: **https://github.com/harvester/charts.git**, Git Branch: **release**
1. Go to Apps/Charts and select Harvester cloud provider chart with version **0.1.12**
1. Install the chart, field of **Cluster name** should not exist in **Step2 Change how the App works**
