### ISSUE TITLE
[BUG] VM IP addresses should be labeled per network interface

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2032]
**Describe the bug**

currently, it is unclear why/which IP is relevant for the user. i.e. the vm in screenshot with 2 IPs was provisioned through harvester. The ones with 3 IPs were through rancher. I'm assuming this is something like <clusterIP> , <hostIP>, <vlan/current_networkIP>
<img width="1029" alt="Screen Shot 2022-03-17 at 1 57 45 PM" src="https://user-images.githubusercontent.com/16691014/158894480-66bf008a-4bcc-4203-9b77-f7c98f4c1df6.png">

**To Reproduce**
1. deploy a VM through harvester
2. deploy a VM using harvester node driver through rancher

**Expected behavior**
UI Should display clearly what is shown to the user

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal, dell poweredge r510)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-26bff4f1-head` (06/10) with Rancher v2.6.5. Close this issue.

### Result
Now the VM list only show IP which related to user access. 
And provide hover message on each displayed IP address
  ![image](https://user-images.githubusercontent.com/29251855/173749441-06fdad41-147a-4703-b19f-eafb1af9f18d.png)
  ![image](https://user-images.githubusercontent.com/29251855/173750324-9f26bcd2-024c-428f-a8bd-2a564c6078f2.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-26bff4f1-head (06/10)

### Verify Steps
1. Enable network with magement-mgmt interface
2. Create vlan network `vlan1` with id `1`
3. Check the IP address on the VM page
4. Create a VM with mangement-mgmt network
5. Import Harvester in Rancher 
6. Provision a RKE2 cluster from Rancher 
7. Check the IP address on the VM page
