### ISSUE TITLE
[Question] Harvester basic installation question.

### ISSUE THREAD

**Issue by abarbier05** [harvester/harvester#2036]
Hello,

Trying to install Harvester for the first time on an SMCI server which previously was running Ubuntu. The system has multiple drives.

I ran into the error (see screenshot below): "mount: /tmp/mnt/STATE: unknown filesystem type 'ext4'.

Any guidance on how to move past this error?

Thank you!

[](url)
<img width="1260" alt="Screen Shot 2022-03-17 at 11 45 04 PM" src="https://user-images.githubusercontent.com/40880436/158950885-0278e130-90aa-417f-861e-5c8bc182a80a.png">

**Comment by joshmeranda** [comment]
@abarbier05  were you using the ISO or helm installation method?
