### ISSUE TITLE
[BUG] report internal error validator when using runStrategy: Manual

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2037]
**Describe the bug**

Create a VM with `runStrategy: Manual`
and remove `running: true`
It will create a stopped VM.
Press start button to start, it will report an internal error in webhook validator.

**To Reproduce**
1. create VM with `runStrategy: Manual` and remove `running: true` in YAML
2. start the VM

**Expected behavior**

It should run properly.

**Support bundle**

**Environment:**
 - Harvester ISO version: 1.0.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Test plan**

test case 1:
1. create VM with runStrategy: Manual and remove running: true in YAML
2. start the VM
3. it should run properly without error.

test case 2:
1. create VM with runStrategy: Always and remove running: true in YAML
2. run properly and no error

test case 3:
1. create VM with runStrategy: Always and remove running: true in YAML
2. start the VM
3. start VM backup
4. during backup, press stop or restart
5. should report error "there is vmbackup in progress for vm <NAMEAPCE>/<VM NAME>, please wait for the vmbackup or remove it before stop/restart the vm"
6. stop or restart should be canceled.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

- [x] `spec.runStrategy: Manual` and ~~`spec.running:true`~~
- [x] `spec.runStrategy: Always` and ~~`spec.running:true`~~
- [x] `spec.runStrategy: Always` and ~~`spec.running:true`~~ and `restart/stop` the VM when backup is processing
![image](https://user-images.githubusercontent.com/5169694/159662507-965a4d22-9a0d-4edb-ab49-ed8597dfae66.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-2a657038-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Test Plan** in https://github.com/harvester/harvester/issues/2037#issue-1173296996
