### ISSUE TITLE
[BUG] Harvester Cluster does not connect back to rancher when harvester is restarted in nested environment

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2040]
**Describe the bug**
If user restarts harvester once it is connected to rancher, harvester cluster (through virtualization management) is in `cluster agent is not connected`

**To Reproduce**
1. deploy rancher on a harvester VM, and import a harvester cluster through `virtualization management`
2. deploy a harvester node driver cluster through rancher (let it get to an active state)
3. shut down the harvester cluster
4. Shut down the Rancher cluster
5. start the harvester cluster again and wait for it to get to a ready state
6. Start the Rancher cluster again
* Note: the node driver cluster will come back to a ready state but the Virtualization management won't. The management cluster never comes back online.
![Screenshot from 2022-03-18 12-18-46](https://user-images.githubusercontent.com/83787952/159070952-90a3fb2e-d9ea-4d09-91ef-196214d874d6.png)
* Note: if you reboot the Harvester cluster after this and make sure that the Rancher cluster is on while Harvester comes online then it will reconnect.

**Expected behavior**
harvester management cluster should come back to an active state after a restart. 

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - rancher version: v2.6.4-rc9
 - Underlying Infrastructure: dell poweredge r510
   - SSDs
   - single node Harvester cluster

[supportbundle_ef00de77-99f1-4876-a619-0b061548de01_2022-03-18T17-41-51Z.zip](https://github.com/harvester/harvester/files/8306592/supportbundle_ef00de77-99f1-4876-a619-0b061548de01_2022-03-18T17-41-51Z.zip)

**Additional context**
this workflow was working fine on v1.0.0 + rancher v2.6.3

**Comment by dweomer** [comment]
This sounds like https://github.com/harvester/harvester/issues/1846 which should have been fixed by:
- https://github.com/harvester/harvester/issues/1770

**Comment by guangbochen** [comment]
Seems the Harvester cluster's agent node is able to resolve the Rancher serve URL.
```
2022-03-18T17:40:59.981230986Z ERROR: https://<IP>:3018/ping is not accessible (Could not resolve host: <IP>)
```

@TachunLin can u please help to double-check if u can reproduce this with ur env, thanks.

**Comment by TachunLin** [comment]
@guangbochen, I can't reproduce this issue after restarting Harvester cluster on my local environment. 

### Reproduce Result
According to the steps in issue description, The RKE2 cluster can connect back to rancher after harvester restarted. 

* Condition:  Harvester and Rancher virtual network remain unchanged 

* After rancher restart, the RKE2 cluster try to re-provision the disconnected cluster
  ![image](https://user-images.githubusercontent.com/29251855/159198986-9a31ecb5-bdff-4808-9c9a-76f4211839b1.png)

* The Mgmt cluster and CAPI cluster are not ready at this time
  ![image](https://user-images.githubusercontent.com/29251855/159199015-f8046bf5-3037-4b46-981c-3f63f16ad2ca.png)

* Wait for about 10 minutes, the RKE2 cluster connect back
  ![image](https://user-images.githubusercontent.com/29251855/159199098-5bc8cedb-11ac-4136-bb3f-76cac1a793d4.png)

* Mgmt cluster and CAPI cluster come back  
  ![image](https://user-images.githubusercontent.com/29251855/159199139-f7556f32-93f0-47a8-b838-05e549eeec25.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine 
* Harvester version: v1.0.1-rc1
* Rancher version: v2.6.4-rc10
* Network: Harvester and Rancher under the same virtual network 

### Verify Steps
https://github.com/harvester/harvester/issues/2040#issue-1173798898 

### Support Bundle
[supportbundle_44e2941d-a97d-4430-ac49-cc799a75bd17_2022-03-21T03-01-40Z.zip](https://github.com/harvester/harvester/files/8312824/supportbundle_44e2941d-a97d-4430-ac49-cc799a75bd17_2022-03-21T03-01-40Z.zip)

### Rancher log
[issue_2040_rancher.log](https://github.com/harvester/harvester/files/8313351/issue_2040_rancher.log)

**Comment by slickwarren** [comment]
I've updated the original ticket, but for clarity I reproduce this consistently with my setup when running rancher on a harvester VM.

**Comment by guangbochen** [comment]
@slickwarren just wondering are u able to resolve `$nslookup <domain>` on the Harvester node?

**Comment by slickwarren** [comment]
@guangbochen that is my personal setup that I currently have shut down. Please ping me when you need it and I can power it back on for you

**Comment by tlehman** [comment]
@slickwarren  For step 1., does "deploy rancher on a harvester VM, and import a harvester cluster through virtualization management" mean I create a VM on a harvester cluster, and that VM is a rancher cluster? Then I use the rancher cluster VM to import the host (harvester cluster)?

![image](https://user-images.githubusercontent.com/261552/162829675-86fbc4b2-5851-475d-a0d1-a3a22bd42e30.png)

**Comment by slickwarren** [comment]
@tlehman yes!

**Comment by tlehman** [comment]
@slickwarren I have Harvester 1.0.1 set up and running to reproduce this, what OS are you using in your Rancher VM? [k3os](https://github.com/rancher/k3os)? [os2](https://github.com/rancher/os2)?

**Comment by tlehman** [comment]
I am using openSUSE Leap 15.3 for the VM image, let me know if there's a better choice. 

![image](https://user-images.githubusercontent.com/261552/163249583-35c58d9d-3482-4aba-ae21-0efc87bdb205.png)

**Comment by tlehman** [comment]
I think I ran into #1736 while uploading that image. I used a URL as a workaround. That worked

**Comment by slickwarren** [comment]
I was using ubuntu 20 but your image should be fine

**Comment by tlehman** [comment]
I have ubuntu 20 with rancher 2.6.4 set up, and I imported the host harvester cluster and have it in an active state (step 2)

For step 3, does "shut down the harvester cluster" mean physically shut down the host harvester cluster? Or does it mean shut down the representation of the Harvester cluster in the Rancher VM?

The reason I ask is that if I shut down the host, then the VM (Rancher cluster) also shuts down too.

**Comment by slickwarren** [comment]
in this case, the host was shut down

**Comment by tlehman** [comment]
My setup: Harvester 1.0.1 bare metal, Rancher 2.6.4 on running as a docker image on an ubuntu vm.

I rebooted the host, and then whenI reconnected to the VM, the Management Cluster was in an Active state.

I'll try with Rancher 2.6.4-rc10 to see if I can reproduce the issue. One detail I want to check is how Rancher was installed on the VM: was it run as a docker container? or was it an RKE cluster with Rancher helm-installed into it?

**Comment by tlehman** [comment]
I reproduced this issue, but I don't think it has to do with the fact that I used Rancher 2.6.4-rc10 instead of 2.6.4, I think it has to do with DHCP. 

Look at this screenshot: 
![image](https://user-images.githubusercontent.com/261552/163873362-d9246ea9-3f87-41cc-a19b-6d5ce6195a1d.png)

Notice that the rancher VM on the right is 192.168.1.186 (current DHCP IP, but initially it was 182, which you can see is in the registration url on the harvester cluster on the right)

The reason I hadn't encountered this before was because I was using the hostnames, and my OpenWRT router resolved the names correctly, regardless of the IP address. But I tried using the IP addresses and that caused the Mgmt Cluster to become Unavailable.

**Comment by tlehman** [comment]
Oh, also, when I delete the Harvester cluster entry from the Rancher VM and try to re-import it, the Rancher cluster returns the old saved IP address as part of the registration URL.

What's the best way to handle this failure? I think it would be worth adding some validation code that looks at the stored cluster-registration-url and check if it matches the current IP

**Comment by slickwarren** [comment]
I don’t think this is what was happening with my setup because I’d set a static IP for my VM running rancher, but its possible and I can try to reproduce once I get to harvester testing.

**Comment by tlehman** [comment]
I'll recreate this using a static IP too

**Comment by tlehman** [comment]
Interesting, the Mgmt cluster is now stuck in pending, but the Harvester host and the Rancher VM can both resolve each other's hostnames. The error seems to be with the websocket to the rancher shell on the Harvester host. From the chrome console:

```
2subscribe.js:400 Ping [management] from dev
xterm.js:1 Uncaught Error: This API only accepts integers
    at e._verifyIntegers (xterm.js:1:101319)
    at e.resize (xterm.js:1:98430)
    at e.fit (xterm-addon-fit.js:1:1568)
    at fit (ContainerShell.vue:296:21)
    at ContainerShell.vue:112:1
subscribe.js:400 Ping [management] from dev
socket.js:81 Socket connecting (id=12, url=wss://issue-2040-vm/v3/clusters/c-m-lbqsn444...)
DevTools failed to load source map: Could not load content for chrome-extension://hponfflfgcjikmehlcdcnpapicnljkkc/static/js/get-video-id.esm.js.map: System error: net::ERR_FILE_NOT_FOUND
socket.js:86 WebSocket connection to 'wss://issue-2040-vm/v3/clusters/c-m-lbqsn444?shell=true&stdout=1&stdin=1&stderr=1&tty=1&command=%2Fbin%2Fsh&sockId=12' failed: 
value @ socket.js:86
socket.js:313 Socket error (state=connecting, id=12)
```

That's only when I try to connect to the harvester kubectl shell. The local rancher one works great.

These might be related, if the harvester cluster is unreachable for making a websocket connection that could explain why it can't connect to manage the cluster

**Comment by guangbochen** [comment]
@slickwarren can u please help to revalidate it with Harvester v1.0.3 + Rancher v2.6.7(when it is released), please let us know if this is still an issue, thanks.

**Comment by guangbochen** [comment]
close due to inactivity and can't reproduce it in our env with the latest v1.0.3 release, feel free to re-open it if u encounter it again, thanks.

**Comment by slickwarren** [comment]
Tested using v1.0.3 on a nested install of rancher v2.6.7 and did not see this issue reproduce.

**Comment by irony** [comment]
I have the same issue in version 1.3 of harvester
