### ISSUE TITLE
[Question] Help troubleshooting a possible longhorn issue.

### ISSUE THREAD

**Issue by RHudsonH** [harvester/harvester#2042]
I have a two node harvester cluster setup on bare metal.

I then deployed a VM and set it up as a single node k3s cluster and installed Rancher Server.

Then using Rancher I Selected the Harvester Node Driver to deploy a 3 node RKE2 cluster. However, there are three pods in the kube-system namespace that are stuck in `ContainerCreating`

```
> kubectl -n kube-system get pods | grep ContainerCreating
harvester-csi-driver-gst7r                                           0/2     ContainerCreating   0              3h24m
harvester-csi-driver-kl2wv                                           0/2     ContainerCreating   0              3h24m
harvester-csi-driver-zvrql                                           0/2     ContainerCreating   0              3h29m
```

and I'm seeing the following events:
```
kubectl -n kube-system get events
LAST SEEN   TYPE      REASON        OBJECT                           MESSAGE
77s         Warning   FailedMount   pod/harvester-csi-driver-gst7r   MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
5m23s       Warning   FailedMount   pod/harvester-csi-driver-gst7r   (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[pods-mount-dir kubernetes-csi-dir host kube-api-access-ptxmz lib-modules socket-dir cloud-config host-dev host-sys registration-dir]: timed out waiting for the condition
6s          Warning   FailedMount   pod/harvester-csi-driver-kl2wv   MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
4m14s       Warning   FailedMount   pod/harvester-csi-driver-kl2wv   (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[pods-mount-dir lib-modules host-dev host registration-dir cloud-config socket-dir kube-api-access-5shxr kubernetes-csi-dir host-sys]: timed out waiting for the condition
4m48s       Warning   FailedMount   pod/harvester-csi-driver-zvrql   MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
20m         Warning   FailedMount   pod/harvester-csi-driver-zvrql   (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[registration-dir kube-api-access-64xtj host-sys host lib-modules kubernetes-csi-dir host-dev socket-dir pods-mount-dir cloud-config]: timed out waiting for the condition
```

Events for all three pods show the following two lines:
```
Events:
  Type     Reason       Age                      From     Message
  ----     ------       ----                     ----     -------
  Warning  FailedMount  13m (x96 over 3h39m)     kubelet  MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
  Warning  FailedMount  4m19s (x100 over 3h19m)  kubelet  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[cloud-config], unattached volumes=[socket-dir pods-mount-dir kube-api-access-64xtj kubernetes-csi-dir host-sys registration-dir cloud-config host-dev host lib-modules]: timed out waiting for the condition
```

Looking in the logs for the 3 harvester-csi-driver-controller pods (which show as `Running` all three pods have the same line repeated over and over for each of the 3 containers in each pod:
```
W0318 21:47:42.496819       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:47:52.504990       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:48:02.496684       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:48:12.497146       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:48:22.497012       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:48:32.497087       1 connection.go:172] Still connecting to unix:///csi/csi.sock
W0318 21:48:42.497155       1 connection.go:172] Still connecting to unix:///csi/csi.sock
```

I'm not really sure where to look from this point. None of the errors above speak to me as far as how I would go about correcting the problem. Any help would be appreciated.

**Comment by w13915984028** [comment]
@RHudsonH Is this issue solved? or how did you bypass it? thanks.

**Comment by RHudsonH** [comment]
> @RHudsonH Is this issue solved? or how did you bypass it? thanks.

I never did get it working. That issue along with a couple of other convinced me that Harvester just wasn't ready yet and I went with a different hypervisor for now. I'm keeping an eye on this project though because I really like the idea of it.

**Comment by w13915984028** [comment]
Anyway, we can try to move it on together.

Which Harvester version did you used?

How about the resource capacity (cpu cores, memeory, storage) of you 2-NODE cluster ?

Harvester itself uses resources in each NODE, the VM to setup Rancher also takes resources, and the provisioned 3-NODE RKE2 cluster also needs resources for each of those 3 NODEs. 

Not sure your resources are enough.

**Comment by RHudsonH** [comment]
Each machine of the cluster had 8 cores (16 threads) and at least 32GB of RAM (one had 64GB). Both had a 500GB SSD for booting and a 1TB NVMe as additional storage.

This was on Harvester 1.0.0

The 3 node RKE cluster on VMs was given 4vcpu each and 8gb ram. Which are more resources than my current virtual RKE cluster

I think my issue was with the Harvester CSI driver not getting properly installed/setup. But this was months ago and that environment isn't around anymore for me to check.

**Comment by w13915984028** [comment]
@yaocw2020 Have you ever heared such issue? thanks.

**Comment by tlehman** [comment]
@RHudsonH The error "mount setup failed, /etc/kubernetes/cloud-config is not a file", the best way forward would be to look at the filesystem and see if that file is there. [This SO question](https://stackoverflow.com/questions/67322950/kubernates-hostpath-type-check-failed-is-not-a-file) shows another instance of that problem, and it can be caused by a missing file causing the Go type check to fail. 

Also try your RKE2 cluster on Harvester 1.1.1, there are lots of upgrades (harvester-network-controller, harvester-pcidevices-controller, etc.), as well as newer Longhorn and other components.
