### ISSUE TITLE
[BUG] Asus KFN4-D16 / AMD Bulldozer cpu unable to initialize network.

### ISSUE THREAD

**Issue by rave-net** [harvester/harvester#2045]
**Describe the bug**

Install hangs/fails on network devices with Asus KGN4-D16 dual opteron, Nvidia NForce 2200 chipset motherboard both with forcedeth onboard gigabit lan enabled or disabled, and no matter what 10Gbe intel or marvell or brocade CNA network adapter is installed

**To Reproduce**

1. Launch 1.0 installer and get to page to set hostname and choose network.  
2. As soon as you fill in hostname and tab to choose management network, the install UI flips back to previous storage config page.  No way to get past.

or

1. Launch 1.0.1 RC1 installer
2. Boot hangs after complaining of inability to enable usb2-port6, and then bringing up ixgbe network adapters.  

**Expected behavior**

Os and installer should support and properly initialize these network adapters on this motherboard.
Have tested board with Suse MicroOS, Opensuse and other linux distros with no issues.

**Support bundle**
1.0.1 will not even reach installer UI.

**Environment:**
 - Harvester ISO version:  Both 1.0 and 1.0.1RC1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Asus KFN4-D16 and dual Opteron

**Additional context**
![20220319_174408](https://user-images.githubusercontent.com/83302930/159185767-52cdf5bc-d726-4a41-868a-5a32a6ed6e54.jpg)
![20220319_170536](https://user-images.githubusercontent.com/83302930/159185768-9915f390-0f49-4c5e-9493-d4a38750dd4e.jpg)

**Comment by DonThorntonJr** [comment]
I'm seeing the same:
![IMG_0987](https://user-images.githubusercontent.com/2985322/159188548-4cec3dca-f535-47f0-a10e-a58ec50338a1.jpeg)

**Comment by rave-net** [comment]
I tested on another AMD dozer based system, a Phenom II X6 1090T on an Asus M4A785TD-V-Evo motherboard.  Same issue as it hangs initializing the network.
Possibly a more general AMD bulldozer compatibility bug?

**Comment by w13915984028** [comment]
@bk201 @tjjh89017 any idea? thanks.

**Comment by w13915984028** [comment]
@rave-net Do you have futher update of this issue, thanks.

**Comment by rave-net** [comment]
> @rave-net Do you have futher update of this issue, thanks.

This appears to have been resolved in 1.0.3.  I will retest 1.1.0rc3 on both my opteron kgpe-d16 and phenomII x6 systems tonight

**Comment by jeff-radick-suse** [comment]
This is pretty old and presumably has been resolved.
