### ISSUE TITLE
[Question] why harvester add a "REJECT" iptables rule

### ISSUE THREAD

**Issue by wonleing** [harvester/harvester#2047]
![微信图片_20220321085449](https://user-images.githubusercontent.com/105055/159193733-c734e72a-b1c6-44b4-8540-73dfcf53ae57.png)
I am using harvester1.0, sometimes 6443 is unreachable. I found it caused by this iptables rule. Why it is generated? Any problem if I delete this rule mannually?

**Comment by yaocw2020** [comment]
Related issue: https://github.com/harvester/harvester/issues/2041

**Comment by yaocw2020** [comment]
If there is no any harvester pod ready, Kubernetes will add the iptables rule.

**Comment by connorkuehl** [comment]
@wonleing Please feel free to re-open if any more clarification is needed 🙂
