### ISSUE TITLE
[BUG] clusternetwork:vlan can't be enabled via terraform (harvester_clusternetwork)

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2052]
### Describe the bug
resource **harvester_clusternetwork** not work as expected.

when `apply`:
```terraform
resource "harvester_clusternetwork" "vlan" {
  lifecycle {
    prevent_destroy = true
  }
  name                 = "vlan"
  enable               = true
  default_physical_nic = "harvester-mgmt"
}
```
![image](https://user-images.githubusercontent.com/5169694/159223796-7f5097ad-91e8-487f-82fc-0eafa827d42e.png)

### To Reproduce
1. Install Harvester with any nodes
2. Install terraform on another machine
3. Initial terraform harvester provider with Harvester kubeconfig
4. Apply terraform harverster_clusternetwork resource to enable `ClusterNetwork:vlan`
5. Apply should success
6. Login to Harvester dashboard then navigate to Advanced Settings, VLAN should be enabled

### Expected behavior
clusternetwork should be enabled after apply.

## Environment:
 - Harvester ISO version: **v1.0.1-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

**Comment by futuretea** [comment]
https://github.com/harvester/terraform-provider-harvester/blob/master/docs/resources/clusternetwork.md#import
Use the following command to import existing resources first
```bash
terraform import harvester_clusternetwork.vlan vlan
```

**Comment by lanfon72** [comment]
I also tested to apply the resource which created from `terraformer`:
```bash
root@pxe-server:/home/vagrant# ls generated/harvester/clusternetwork/
clusternetwork.tf  outputs.tf  provider.tf  terraform.tfstate
root@pxe-server:/home/vagrant# cat generated/harvester/clusternetwork/clusternetwork.tf 
resource "harvester_clusternetwork" "vlan" {
  enable = "false"
  name   = "vlan"
}
root@pxe-server:/home/vagrant# cp generated/harvester/clusternetwork/clusternetwork.tf .  
root@pxe-server:/home/vagrant# vim clusternetwork.tf 
root@pxe-server:/home/vagrant# 
root@pxe-server:/home/vagrant# terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # harvester_clusternetwork.vlan will be created
  + resource "harvester_clusternetwork" "vlan" {
      + enable = true
      + id     = (known after apply)
      + name   = "vlan"
      + state  = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harvester_clusternetwork.vlan: Creating...
╷
│ Error: enable is true, please specify default_physical_nic
│ 
│   with harvester_clusternetwork.vlan,
│   on clusternetwork.tf line 1, in resource "harvester_clusternetwork" "vlan":
│    1: resource "harvester_clusternetwork" "vlan" {
│ 
╵
root@pxe-server:/home/vagrant# vim clusternetwork.tf 
root@pxe-server:/home/vagrant# terraform apply

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  + create

Terraform will perform the following actions:

  # harvester_clusternetwork.vlan will be created
  + resource "harvester_clusternetwork" "vlan" {
      + default_physical_nic = "harvester-mgmt"
      + enable               = true
      + id                   = (known after apply)
      + name                 = "vlan"
      + state                = (known after apply)
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harvester_clusternetwork.vlan: Creating...
╷
│ Error: clusternetworks.network.harvesterhci.io "vlan" already exists
│ 
│   with harvester_clusternetwork.vlan,
│   on clusternetwork.tf line 1, in resource "harvester_clusternetwork" "vlan":
│    1: resource "harvester_clusternetwork" "vlan" {
│ 
╵
```

**Comment by lanfon72** [comment]
> https://github.com/harvester/terraform-provider-harvester/blob/master/docs/resources/clusternetwork.md#import Use the following command to import existing resources first
> 
> ```shell
> terraform import harvester_clusternetwork.vlan vlan
> ```

@futuretea, I tested it works if we import the resource first. (log as below)
But for other resources, user don't need to do _import_ before apply, should we add a caveat for the resource?
User can also change the `name` to create another _vlan_ but will not be displayed in dashboard. (and can't destroy), it would be another problem if user assign other `name` to create the resource.



```bash
root@pxe-server:/home/vagrant# 
root@pxe-server:/home/vagrant# terraform import harvester_clusternetwork.vlan vlan
Error: resource address "harvester_clusternetwork.vlan" does not exist in the configuration.

Before importing this resource, please create its configuration in the root module. For example:

resource "harvester_clusternetwork" "vlan" {
  # (resource arguments)
}

root@pxe-server:/home/vagrant# vim clusternetwork.tf
root@pxe-server:/home/vagrant# cat clusternetwork.tf 
resource "harvester_clusternetwork" "vlan" {
  enable = "false"
  name   = "vlan"
}
root@pxe-server:/home/vagrant# terraform import harvester_clusternetwork.vlan vlan
harvester_clusternetwork.vlan: Importing from ID "vlan"...
harvester_clusternetwork.vlan: Import prepared!
  Prepared harvester_clusternetwork for import
harvester_clusternetwork.vlan: Refreshing state... [id=vlan]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

root@pxe-server:/home/vagrant# cat clusternetwork.tf 
resource "harvester_clusternetwork" "vlan" {
  enable = "false"
  name   = "vlan"
}
root@pxe-server:/home/vagrant# vim clusternetwork.tf 
root@pxe-server:/home/vagrant# cat clusternetwork.tf 
resource "harvester_clusternetwork" "vlan" {
  enable = "true"
  name   = "vlan"
  default_physical_nic = "harvester-mgmt"
}
root@pxe-server:/home/vagrant# terraform apply
harvester_clusternetwork.vlan: Refreshing state... [id=vlan]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the
following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # harvester_clusternetwork.vlan will be updated in-place
  ~ resource "harvester_clusternetwork" "vlan" {
      + default_physical_nic = "harvester-mgmt"
      ~ enable               = false -> true
        id                   = "vlan"
        name                 = "vlan"
        tags                 = {}
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

harvester_clusternetwork.vlan: Modifying... [id=vlan]
harvester_clusternetwork.vlan: Modifications complete after 0s [id=vlan]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Apply before import
![image](https://user-images.githubusercontent.com/5169694/160344844-ac763dab-f9ab-441b-9831-f9163b7cd904.png)
Apply with another `name`
![image](https://user-images.githubusercontent.com/5169694/160344898-9bc83daf-6ec2-438b-b7db-e5ad65345522.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-9285ca26-head**
* **ui-source** Option: **Auto**
* terraform-provider-harvester Version: **master-58774ee0-head** (docker image ID: **2e4b31541ae1**)

### Verify Steps:
1. Install Harvester with any nodes
2. Install terraform on another machine
3. Initial terraform harvester provider with Harvester kubeconfig
4. Apply terraform harverster_clusternetwork resource to enable `ClusterNetwork:vlan`
```terraform
resource "harvester_clusternetwork" "vlan" {
  name                 = "vlan"
  enable               = true
  default_physical_nic = "harvester-mgmt"
}
```
5. Apply should fail with error message: _can not create the existing vlan clusternetwork, to avoid this error and continue with the plan, use `terraform import harvester_clusternetwork.vlan vlan` to import it first_
6. Update `name` of harvester_clusternetwork resource to any words, then do `terraform apply`
7. Apply should fail with error message: _can not create clusternetwork, to avoid this error and continue with the plan, either move clusternetwork to another module or reduce the scope of the plan using the -target flag_
8. do `terraform import harvester_clusternetwork.vlan vlan`
9. Update `name` of harvester_clusternetwork resource to **vlan**, then do `terraform apply`
10. Apply should success
11. Login to Harvester dashboard then navigate to Advanced Settings, VLAN should be enabled
