### ISSUE TITLE
[BUG] Unable to delete the stuck provisioning RKE2 cluster if cluster VM have no IP assign

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2054]
**Describe the bug**

When RKE2 cluster VM can't get IP address and stuck in provisioning status
Unable to delete the RKE2 cluster and VM correctly if Harvester VM did not get IP address on it. 

* Delete the RKE2 cluster stuck in `Removing`  
![image](https://user-images.githubusercontent.com/29251855/159274536-70252a13-50a4-4a8b-8deb-68611b935183.png)

* Harvester cluster VM keep in `Terminating`
![image](https://user-images.githubusercontent.com/29251855/159274645-52a0e8e3-5987-416f-9c76-dabbae990912.png)

* Harvester cluster VM events show deleted
![image](https://user-images.githubusercontent.com/29251855/159274947-e4513c33-19c0-4f73-9511-11660f292080.png)

**To Reproduce**
1. Import Harvester from Rancher
2. Provision a 1 node RKE2 cluster in Harvester (v1.22.7+rke2r2)
3. RKE2 cluster stuck in provisioning status
4. RKE2 cluster VM created on Harvester but can't get IP assigned 
5. Delete the RKE2 cluster from Rancher UI
6. Check can delete RKE2 cluster and Harvester cluster VM

**Expected behavior**

Should be able to delete RKE2 cluster from Rancher and delete cluster VM from Harvester when VM did not get IP address

**Support bundle**

[supportbundle_58124c47-18ab-424a-9971-5e78b768f145_2022-03-21T13-40-36Z.zip](https://github.com/harvester/harvester/files/8315966/supportbundle_58124c47-18ab-424a-9971-5e78b768f145_2022-03-21T13-40-36Z.zip)

**Rancher logs**
[0321_regression.log](https://github.com/harvester/harvester/files/8316049/0321_regression.log)

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Rancher version: v2.6.4-rc10
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 nodes harvester cluster 
 - RKE2 version: v1.22.7+rke2r2

**Additional context**

**Comment by tlehman** [comment]
Reading through the attached rancher audit log, I noticed this: 

```
2022/03/21 11:01:33 [INFO] Machine rke-machine.cattle.io/v1, 
  Kind=HarvesterMachine rke2-cluster-v1234-pool1-24c97fd2-xp8nl 
  has already been deleted

2022/03/21 11:01:33 [ERROR] error syncing 'fleet-default/rke2-cluster-v1234-pool1-24c97fd2-xp8nl': 
  handler machine-provision-remove: Operation cannot be fulfilled on harvestermachines.rke-machine.cattle.io 
  "rke2-cluster-v1234-pool1-24c97fd2-xp8nl": 
    StorageError: invalid object, 
    Code: 4,
    Key: /registry/rke-machine.cattle.io/harvestermachines/fleet-default/rke2-cluster-v1234-pool1-24c97fd2-xp8nl,
    ResourceVersion: 0,
    AdditionalErrorMsg: 
      Precondition failed: UID in precondition: 56973b14-ad86-4fe0-b034-312844955b1a, UID in object meta: , requeuing
```

It looks like there is a StorageError because of an invalid Kubernetes object. I'll look into the StorageMachine kind tomorrow morning. That looks like the cause of this problem.

**Comment by tlehman** [comment]
Just confirming, I am using the `rke` binary to provision the vm was an RKE2 cluster. The get.rke2.io shell script pulled in v1.22.8, but these repro steps called for 1.22.7, so I will stick to that version unless it doesn't matter. 

The command `rke config --list-version --all | grep 1.22.7` returns `v1.22.7-rancher1-2`, is that the same as `v1.22.7+rke2r2`?

**Comment by tlehman** [comment]
Could you give some detailed repro steps for the provisioning an RKE2 cluster?

I used the `rke` binary on an Ubuntu 20 vm, but it failed part of the install

**Comment by TachunLin** [comment]
Hi @tlehman , I think the issue can still exists on v1.22.8 rke2 version. I guess you are using v2.6-head for the investigation. 

According to the dev-2.6 rke-config, I think the `v1.22.7-rancher1-2` should be identical with `v1.22.7+rke2r2`
https://releases.rancher.com/kontainer-driver-metadata/dev-v2.6/data.json

![image](https://user-images.githubusercontent.com/29251855/164592652-f808d825-0030-4bb0-b574-a10063257a60.png)

![image](https://user-images.githubusercontent.com/29251855/164592622-72017e65-33da-4032-b0c3-bb0b5f888a61.png)

**Comment by TachunLin** [comment]
To reproduce this issue, we need to fulfill the situation that the guest RKE2 cluster can't retrieve IP from Harvester cluster  
I think we can achieve before we start provisioning the RKE2 cluster by removing the qemu-guest agent in the cloud-config user data or maybe remove the `ssh_pwauth: true`.  

Then follow the steps to proceed
1. Provision a 1 node RKE2 cluster in Harvester (v1.22.7+rke2r2)
2. RKE2 cluster stuck in provisioning status
3. RKE2 cluster VM created on Harvester but can't get IP assigned
4. Delete the RKE2 cluster from Rancher UI

**Comment by tlehman** [comment]
~~Where is the cloud-config user-data?~~

UPDATE: I found it, it's here when creating the cluster: https://issue-2054-vm/dashboard/c/local/explorer/provisioning.cattle.io.cluster/create?type=harvester#basic

**Comment by tlehman** [comment]
I `docker exec`ed into the virt-launcher pod's container and deleted the /var/lib/libvirt/qemu/channel/target/domain-1-default_issue-2054/org.qemu.guest_agent.0 socket. I'll try provisioning now

**Comment by tlehman** [comment]
I have the rke2-cluster stuck in provisioning (30 minutes), the provisioning log just says `[INFO ] waiting for at least one bootstrap node`

But when I delete it the delete operation succeeded. I'm digging through the support bundle now and comparing it to the analogous logs on my harvester cluster. I want to see what's different between the two

**Comment by tlehman** [comment]
What I had was not a good repro, since the "PUT failure" was actually telling me that Rancher never succeeded in creating a VM on Harvester, even though it created the object visible in the UI that could be deleted. I need to debug the PUT error first

**Comment by tlehman** [comment]
Oh, after digging through the support bundle, I can tell I'm provisioning the rke2 cluster in the wrong namespace (fleet-defauilt instead of fleet-local), trying in fleet-local now.

**Comment by tlehman** [comment]
When I attempt to provision an RKE2 cluster with the Harvester provider and add `ssh_pwauth: false` to the cloud-config userdata, I get this error: 

> Provisioning bootstrap node(s) rke2-cluster-no-sshpwauth-pool1-79f7c7857d-jsgqt: failed creating server (HarvesterMachine) in infrastructure provider: CreateError: Downloading driver from https://issue-2054-vm/assets/docker-machine-driver-harvester Doing `/etc/rancher/ssl docker-machine-driver-harvester docker-machine-driver-harvester`: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key Running pre-create checks... Error with pre-create check: "an error on the server (\"error trying to reach service: cluster agent disconnected\") has prevented the request from succeeding (get settings.harvesterhci.io server-version)" The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag., waiting for agent to check in and apply initial plan

**Comment by guangbochen** [comment]
@TachunLin  can we please help to revalidate this case when Rancher v2.6.7 is released(with Harvester v1.0.3)? Thanks.

**Comment by FrankYang0529** [comment]
I can't reproduce this issue with following steps on Harvester v1.1.0 with Rancher v2.6.9:

1. Create a harvester cluster.
2. Import the harvester cluster to a rancher cluster.
3. Create the harvester cluster credential in the rancher.
4. Create a VLAN which is not connectable in the harvester cluster.
5. Provision an RKE2 on the rancher with the VLAN.
6. The VM can't get an IP.
7. Delete the RKE2 on the rancher. The RKE2 will be deleted but this step will take about 10 minutes.

**Comment by TachunLin** [comment]
Checked also **can't reproduce** on Rancher `v2.7-head` (d1813a2) with Harvester `v1.1.1-rc1`. Close this issue 

### Result
While we create an vlan with no connectivity and provision the RKE2 cluster with this vlan. 
The guest cluster keep in provisioning and Harvester virtual machine can't retrieve IP address. 

When we delete the RKE2 cluster, the provisioning job in Rancher will be removed and also delete the created VM on Harvester too.  

### Reproduce steps
Ref to https://github.com/harvester/harvester/issues/2054#issuecomment-1319626895
