### ISSUE TITLE
[FEATURE] UI enable/disable secure boot for EFI system

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2059]
**Is your feature request related to a problem? Please describe.**

Not related to a problem

**Describe the solution you'd like**

UI could set up EFI boot with secure boot.
Need another option to set up EFI boot without secure boot.

**Describe alternatives you've considered**

**Additional context**

**Comment by WuJun2016** [comment]
Hi, @tjjh89017 , This should be a duplicate issue, We have integrated this feature in another [issue](https://github.com/harvester/harvester/issues/2128)， if so, please close this issue， thanks a lot. https://github.com/harvester/harvester/issues/2128#issuecomment-1094596475

**Comment by tjjh89017** [comment]
Dup issue https://github.com/harvester/harvester/issues/2128#issuecomment-1094596475
