### ISSUE TITLE
Adding/Scanning for newly added disk(s)

### ISSUE THREAD

**Issue by kingnarmer** [harvester/harvester#2062]
How to to scan for new added disks to harvester node. I tried rescan-scsi-bus.sh -a -l and rebooting node. 

Also is there a way to use locally attached storage via fiber channel to each node ?

**Comment by futuretea** [comment]
Can the following command work?
```
for i in `ls /sys/class/scsi_host/*/scan`;do echo "- - -" > $i;done
```
