### ISSUE TITLE
[BUG] Additional IP assigned to VM after editing yaml without change any content

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2067]
**Describe the bug**

After edit VM config, change Network from `vlan` to `management Network` 
Then open `edit yaml` page and save it directly without any change
There will be an additional IP assigned to VM (10.0.2.x) 

* IP before saving yaml 
  - 10.52.3.141
  ![image](https://user-images.githubusercontent.com/29251855/159661340-3ba8e098-a638-4516-9a80-e90c9398f871.png)

* IP after saving yaml 
  - 10.52.3.141
  - 10.0.2.2
  ![image](https://user-images.githubusercontent.com/29251855/159663788-c02aca9a-31f2-423f-b3fc-5cda13efdaab.png)

**To Reproduce**
1. Create a VM with `vlan` network 
  ![image](https://user-images.githubusercontent.com/29251855/159659309-8bbc1030-ebdf-4ef6-b86d-402c0ae49784.png)
2. Wait for VM ready
3. Edit the VM config
4. Change network from `vlan` to `management Network`
  ![image](https://user-images.githubusercontent.com/29251855/159659995-db39c491-f0b5-4d5d-85c4-764b2135e956.png)
  ![image](https://user-images.githubusercontent.com/29251855/159660145-004aa03a-1b62-4980-99cc-0fad5a91e1ba.png)
5. Save the config
6. Wait for VM restart and get new IP
   ![image](https://user-images.githubusercontent.com/29251855/159661340-3ba8e098-a638-4516-9a80-e90c9398f871.png)
7. Edit the yaml of VM
  ![image](https://user-images.githubusercontent.com/29251855/159663585-79bd3d35-423f-46d9-b417-f13e815df5fd.png)
8. Save directly without any change
9. Check the VM network status 
  ![image](https://user-images.githubusercontent.com/29251855/159663788-c02aca9a-31f2-423f-b3fc-5cda13efdaab.png)

**Expected behavior**

Edit yaml of VM without change anything should retain the IP setting

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes harvester on brown bare machines

**Additional context**
[test_vlan_to_mgmt_yaml.txt](https://github.com/harvester/harvester/files/8331646/test_vlan_to_mgmt_yaml.txt)

**Comment by TachunLin** [comment]
Checked with @tjjh89017, the additional IP address `10.0.2.2` bind to `eth0` interface of virtual machine is the expected behavior. While the exposed IP address `10.52.3.141` was bind to the virt-launcher pod of virtual machine.  

@WuJun2016 , Can you help to identify whether IP `10.0.2.2` display on the virtual machine page should be addressed from frontend or backend perspective. Thank you.

**Comment by WuJun2016** [comment]
@TachunLin  I think it should be handled by the frontend.
This is a known issue, but the frontend filtering needs to know what conditions to filter on.  
Requires @yaocw2020  to provide filter conditions.
I suggest moving this issue to v1.02 to fix.   cc @guangbochen

**Comment by WuJun2016** [comment]
@TachunLin  I wasn't able to reproduce the problem.  Are there any requirements for vlan configuration？
![image](https://user-images.githubusercontent.com/24985926/161191392-1e975a08-b795-4d33-b01a-df7ae54feef7.png)

**Comment by noahgildersleeve** [comment]
Tested in `master-0eab7caa-head`. Tested with included verification steps. Fixed.

> **Describe the bug**
> 
> After edit VM config, change Network from `vlan` to `management Network` Then open `edit yaml` page and save it directly without any change There will be an additional IP assigned to VM (10.0.2.x)
> 
> * IP before saving yaml
>   
>   * 10.52.3.141
>     ![image](https://user-images.githubusercontent.com/29251855/159661340-3ba8e098-a638-4516-9a80-e90c9398f871.png)
> * IP after saving yaml
>   
>   * 10.52.3.141
>   * 10.0.2.2
>     ![image](https://user-images.githubusercontent.com/29251855/159663788-c02aca9a-31f2-423f-b3fc-5cda13efdaab.png)
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a VM with `vlan` network
>    ![image](https://user-images.githubusercontent.com/29251855/159659309-8bbc1030-ebdf-4ef6-b86d-402c0ae49784.png)
> 2. Wait for VM ready
> 3. Edit the VM config
> 4. Change network from `vlan` to `management Network`
>    ![image](https://user-images.githubusercontent.com/29251855/159659995-db39c491-f0b5-4d5d-85c4-764b2135e956.png)
>    ![image](https://user-images.githubusercontent.com/29251855/159660145-004aa03a-1b62-4980-99cc-0fad5a91e1ba.png)
> 5. Save the config
> 6. Wait for VM restart and get new IP
>    ![image](https://user-images.githubusercontent.com/29251855/159661340-3ba8e098-a638-4516-9a80-e90c9398f871.png)
> 7. Edit the yaml of VM
>    ![image](https://user-images.githubusercontent.com/29251855/159663585-79bd3d35-423f-46d9-b417-f13e815df5fd.png)
> 8. Save directly without any change
> 9. Check the VM network status
>    ![image](https://user-images.githubusercontent.com/29251855/159663788-c02aca9a-31f2-423f-b3fc-5cda13efdaab.png)
> 
> **Expected behavior**
> 
> Edit yaml of VM without change anything should retain the IP setting
> 
> **Support bundle**
> 
> **Environment:**
> 
> * Harvester ISO version: v1.0.1-rc1
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes harvester on brown bare machines
> 
> **Additional context** Add any other context about the problem here. [test_vlan_to_mgmt_yaml.txt](https://github.com/harvester/harvester/files/8331646/test_vlan_to_mgmt_yaml.txt)
