### ISSUE TITLE
[BUG] VM can't get IP from external VLAN network after adding additional network to the VM

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2068]
**Describe the bug**

Add addition external VLAN network to the VM already have management network. 
The added VLAN network interface is not enabled and retrieve external IP 

* VM can't get IP from the addition VLAN network interface
![image](https://user-images.githubusercontent.com/29251855/159682136-4b415e6d-b0e8-4a8e-993d-af4368f8f013.png)

* VM can't get additional IP from external VLAN network,  the additional network interface display `DOWN` in virtual machine

  ```
  opensuse@test-multi-network:~> ip a
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
      inet6 ::1/128 scope host 
         valid_lft forever preferred_lft forever
  2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast state UP group default qlen 1000
      link/ether 52:54:00:d9:f4:02 brd ff:ff:ff:ff:ff:ff
      altname enp1s0
      inet 10.0.2.2/24 brd 10.0.2.255 scope global eth0
         valid_lft forever preferred_lft forever
      inet6 fe80::5054:ff:fed9:f402/64 scope link 
         valid_lft forever preferred_lft forever
  3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
      link/ether e6:5e:10:ec:9a:d9 brd ff:ff:ff:ff:ff:ff
      altname enp2s0
  ```

**To Reproduce**
1. Create virtual machine with default management network 
2. Edit config of the VM
3. Click `Add Network`
4. Select external vlan network 
  ![image](https://user-images.githubusercontent.com/29251855/159682040-6847d96f-722a-4ff8-a407-49256fe9c331.png)
5. Wait for VM restart complete
6. Check VM status on Virtual Machine page 
7. SSH to the VM 
8. Run `ip a` to check the network status

**Expected behavior**

1. Can get IP from external VLAN and the network interface is UP
2. Should display additional IP from the external VLAN network on virtual machine page 

**Support bundle**

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes harvester on brown bare machines

**Additional context**
Confirm can get IP from external VLAN network if only one network interface set.
  ![image](https://user-images.githubusercontent.com/29251855/159722540-dc03b520-3397-4fb4-9e72-826b7ef515de.png)

**Comment by TachunLin** [comment]
After discussed with @tjjh89017 and checked the [network document](https://docs.harvesterhci.io/v1.0/networking/harvester-network/#management-network).
In this case, once the VM already started with default management network.  
The `Add Network` feature in virtual machine can only add a new network interface to virtual machine. 
User need to connect to VM and manually configure the second additional interface to get IP.  

If user need to create multiple network interface once, they can add the cloud-init network configs in VM creation.
  ```
  version: 1
  config:
    - type: physical
      name: enp1s0 # name is varies upon OS image
      subnets:
        - type: dhcp
    - type: physical
      name: enp2s0
      subnets:
        - type: DHCP
  
  ```
But the above config need to be update since the know issue #1059 

@guangbochen, not sure if you have any concern or comment about the current design.

**Comment by guangbochen** [comment]
@TachunLin Feel free to close this issue as this is expected behavior, thanks.

**Comment by TachunLin** [comment]
Close since it's the expected behavior.
