### ISSUE TITLE
[BUG] Unable to install via USB ISO

### ISSUE THREAD

**Issue by admun** [harvester/harvester#2069]
I am unable to install Harvester using USB ISO.

**To Reproduce**
1. using a ventoy USB booting the havester v1.0.0 iso
2. select create a new cluster
3. select the SSD on the hw
4. fill in the hostname, management NIC is empty and cannot tab into it. Hitting down arrow or enter key jump back to the main menu. 

**Expected behavior**
User should be able to install harvester via USB boot ISO

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): MSI A320M-A Pro Max, 32GB RAM, 512G SSD, Ryzen 5 1600af CPU

**Comment by zpatten** [comment]
I'm hitting this issue as well using v1.0.0; going to try v1.0.1rc1 to see if I get better luck there.

**Comment by zpatten** [comment]
Looks like v1.0.1rc1 is doing the same for me.

**Comment by zpatten** [comment]
OK so I was able to get past this.  For me it was due to not booting in UEFI.  Once I realized it wasn't booting the USB ISO in UEFI and I switched it everything went as expected and worked (so far at least).  Had the installer crash on me due to another error but that's a different story.

**Comment by zpatten** [comment]
```
panic: invalid dimensions


goroutine 1 [running]:
log.PanicIn(0xc0003a7f68, 0x1, 0x1)
    /usr/local/src/go/src/log/log.go:368 +0xae
main.main()
    /go/src/github.com/harvester/harvester-installer/main.go:11 +0x73
```

**Comment by admun** [comment]
I confirmed I had the same issue as @zpatten . By booting from UEFI, I get passed the issue of missing network device.

**Comment by admun** [comment]
I don't think the installer can detect the issue (not running in UEFI when it should), right?

Maybe the doc should update in https://docs.harvesterhci.io/v1.0/install/usb-install/#common-issues for the solution to the issue.

**Comment by burgoyn1** [comment]
@admun I am having the same issue. Management NIC is empty and can not see the on board one. If I plug in a USB 3.0 ethernet adapter, that does show up. The on board card is a 2.5GB adapter, could that be the problem?

**Comment by putz612** [comment]
Ran into this one too, no network card seen and installer just bounces back to the start.  Dropping into the shell I do see a network card though.

**Comment by putz612** [comment]
Still having the same issue with v1.0.2

**Comment by ibrokethecloud** [comment]
@putz612 are you able to generate a support config by dropping into the shell and following the instructions here:

https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information

**Comment by asemen2608** [comment]
Same issue here. I tried to Install Harvester v1.0.2 from iso. No Network could be slected. Hiting "Enter" loops back to the disk selection. 
Steps to reproduce are:
Select "Create a new Harverster cluster" -> choose disk sda or sdb -> USE MBR "No" -> Use the installation disk -> 
HostName:  [harvester] -> "Enter" -> loops back to "Create a new Harvester cluster" . There is no chance to set Management NIC or Bond Mode or IPvR Method.
I created a supportconfig file of the system as described in https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information

**Comment by asemen2608** [comment]
Tar file upload is not support in github where to upload best the supportconfig tar file?
Temporary to be downloaded from: 
http://www.liniq.de/hv/scc_rancher_220630_1534.txz
http://www.liniq.de/hv/scc_rancher_220630_1534.txz.md5

Environment:
    Harvester ISO version: v1.0.2
    Underlying Infrastructure (e.g. Baremetal with Dell Tower 5810):32GB RAM, 447GB SSD, 931GB HD

Looks like no network was set up

**Comment by lenkeybalis** [comment]
Hi all,

Is there any new information about this problem? Today I tried to install it with v1.1.0 version, but the situation is same for me as well,

Thank you!

**Comment by futuretea** [comment]
The installer crash part `panic: invalid dimensions` should be the same as https://github.com/harvester/harvester/issues/2937

**Comment by dlaidlaw** [comment]
This is also a problem for me. The same panic message. I tried setting vga=792 and also 791 and 795. None of those worked. Using Harvester 1.1.1, the "Harvester Installer (VGA 1024x768)" Grub boot option also does not work.

What is consistent is on the "Configure network" screen (after the screen entering the host name), I can select the "Management NIC", but after that I cannot arrow down to the next parameters (VLAN ID, Bond Mode, and IPv4 Method). The only thing I can do at that point is hit enter, and when I do, I get the panic invalid dimensions flash by quickly, and then back to the "Choose installation mode" screen.

I am not convinced it is a VGA issue. Would that explain why I cannot arrow down to the next config parameter? 

Since I am using 1.1.1, the fix in [#2937](https://github.com/harvester/harvester/issues/2937) did not work for me.

**Comment by SteamMenace** [comment]
I have this issue also, but it does seem to detect my NICs:

![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)

First time I hit down arrow after I escaped the NIC dialog, second time, enter.  I am using a USB converter to CF for the install drive since I am just trying this out and it doesn't seem to detect my NVMe drives.

Downloaded this last night so I am using v1.1.1

As well, I cannot capture the supportconfig: 
![image](https://user-images.githubusercontent.com/12906022/222897968-608c403a-eacc-4e89-b39d-d1ba30848e2f.png)

Nothing from the other commands, either under https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information

But I found if I sudo dmesg I do get some output, I have no way to capture it though since there is no IP on the NICs, I can only take a screenie from my KVM:
![image](https://user-images.githubusercontent.com/12906022/222898469-2097bacb-b24a-497c-8265-61e9e0b02e10.png)

I will see if I can do MBR so I can try to continue with my testing.

**Comment by davy-tw** [comment]
same on v1.1.1

but it works if I boot up with 1024x768 option in GRUB

**Comment by Flou21** [comment]
same on v1.1.2

**Comment by shanduur** [comment]
Seeing the issue on v1.1.2.

**Comment by shanduur** [comment]
For more context: 

1. I am seeing this issue when booting in legacy mode.
2. UEFI mode dumps me into GRUB shell, I am not able to load grub.cfg from harvester installer partitions.
3. Installer panics with the following message:

```log
2023/07/26 05:21:21 invalid dimensions
panic: invalid dimensions

goroutine 1 [running]:
log.Panicln({0xc00041ff60?, 0x0?, 0x0?})
	/usr/local/go/src/log/log.go:399 +0x65
main.main()
	/go/src/github.com/harvester/harvester-installer/main.go:11 +0x46
```

**Comment by Onceuponayea** [comment]
> I have this issue also, but it does seem to detect my NICs:
> 
> ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif) [ ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif) ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif) [ ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> 
> First time I hit down arrow after I escaped the NIC dialog, second time, enter. I am using a USB converter to CF for the install drive since I am just trying this out and it doesn't seem to detect my NVMe drives.
> 
> Downloaded this last night so I am using v1.1.1
> 
> As well, I cannot capture the supportconfig: ![image](https://user-images.githubusercontent.com/12906022/222897968-608c403a-eacc-4e89-b39d-d1ba30848e2f.png)
> 
> Nothing from the other commands, either under https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information
> 
> But I found if I sudo dmesg I do get some output, I have no way to capture it though since there is no IP on the NICs, I can only take a screenie from my KVM: ![image](https://user-images.githubusercontent.com/12906022/222898469-2097bacb-b24a-497c-8265-61e9e0b02e10.png)
> 
> I will see if I can do MBR so I can try to continue with my testing.

found any solution yet?

**Comment by SteamMenace** [comment]
> > I have this issue also, but it does seem to detect my NICs:
> > ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >       
> >         [
> >           
> >         
> >             ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >           ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >         
> >        [ ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif) ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >       
> >         [
> >           
> >         
> >             ![msedge_CuDj2AqJiy](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >           ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >         
> >         
> >           
> >             
> >               
> >             
> >             
> >               
> >               
> >             
> >           
> >           [
> >             
> >               
> >             
> >           ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> >         
> >        [ ](https://user-images.githubusercontent.com/12906022/222897499-784f082c-ce9a-4983-94bf-8d2eed5c0f6c.gif)
> > First time I hit down arrow after I escaped the NIC dialog, second time, enter. I am using a USB converter to CF for the install drive since I am just trying this out and it doesn't seem to detect my NVMe drives.
> > Downloaded this last night so I am using v1.1.1
> > As well, I cannot capture the supportconfig: ![image](https://user-images.githubusercontent.com/12906022/222897968-608c403a-eacc-4e89-b39d-d1ba30848e2f.png)
> > Nothing from the other commands, either under https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information
> > But I found if I sudo dmesg I do get some output, I have no way to capture it though since there is no IP on the NICs, I can only take a screenie from my KVM: ![image](https://user-images.githubusercontent.com/12906022/222898469-2097bacb-b24a-497c-8265-61e9e0b02e10.png)
> > I will see if I can do MBR so I can try to continue with my testing.
> 
> found any solution yet?

Nope, I gave up.

**Comment by shanduur** [comment]
> found any solution yet?

For me this was caused by incorrectly set resolution of display. I used ssh to connect to the installation OS, and installed through remote terminal instead using local display.
