### ISSUE TITLE
[Question] Recommended default network?

### ISSUE THREAD

**Issue by radioflyer28** [harvester/harvester#2074]
When configuring my setup I saw an annotation "harvester-mgmt (not recommended)" for selecting a default network config. Unfortunately, after searching again, I cannot find where this is mentioned again. Can someone shed some light on this and why this is so? It seems to go against the networking best-practice doc (https://docs.harvesterhci.io/v1.0/networking/harvester-network/)
Thanks!

P.S. for context, my building's network is forcing me to use a non-VLAN setup: https://docs.harvesterhci.io/v1.0/networking/best-practice-non-vlan-aware-switch/

**Comment by guangbochen** [comment]
There are two types of networks in Harvester, `management network` and `VLAN network`. 

The management network is mainly used for internal service and storage network communication. If your node has only one NIC, you can put the VLAN network on the `harvester-mgmt` NIC, but we usually recommend using separate NICs for better network isolation and performance.

We have updated the docs recently, and u may take a look at https://docs.harvesterhci.io/v1.0/networking/best-practice/overview/

**Comment by w13915984028** [comment]
@radioflyer28 Any update of your setting?
As of Harvester v1.0.2, the `management network` does not support VLAN yet, namely, the ethernet frame outing of the NIC of the NODE, has no VLAN tag.  

`management network` supports VLAN is an under-development feature.

For study/experiment of Harvester, it's OK to use management network to carry all traffic.

More practical, it's better to have separated `management network` and ` VLAN network` , it requires each NODE has at least 2 NICs. With proper setting per https://docs.harvesterhci.io/v1.0/networking/harvester-network/ , VM can have multi-nic to separate traffic.
