### ISSUE TITLE
[FEATURE] WebUI adds setting of monitoring-prometheus-node-exporter

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2075]
**Is your feature request related to a problem? Please describe.**

Per #1531, the resources setting of prometheus-node-exporter is exposed to ManagedChart, please UI aslo adds setting of it.

**Describe the solution you'd like**

Users can change resources setting from Harvester WebUI

**Describe alternatives you've considered**

**Additional context**
The ManagedChart:
https://github.com/harvester/harvester-installer/pull/250

Doc:
https://github.com/harvester/docs/pull/124

cc @WuJun2016 @DaiYuzeng @guangbochen

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/165040672-19375aba-34c9-4d7b-a38a-8165e79de54c.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-0eab7caa-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Verify Steps** in https://github.com/harvester/dashboard/pull/291
