### ISSUE TITLE
[BUG] IPAM deployment through rancher is not working -> `health checks` disabled by default

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2077]
**Describe the bug**

**To Reproduce**
* deploy a workload with a load balancer service through rancher v2.6.4-rc12
* click the link once the load balancer comes up
-> service is created and `active` but is not routing to the service properly

**Expected behavior**
LB should route to the service

**Support bundle**
[supportbundle_099d3b86-89b8-45f6-aa02-748fb08ad44e_2022-03-24T20-40-50Z.zip](https://github.com/harvester/harvester/files/8345172/supportbundle_099d3b86-89b8-45f6-aa02-748fb08ad44e_2022-03-24T20-40-50Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge r510

**Additional context**
* manually updating the harvester LB to have `health checks` enabled fixes this issue.

**Comment by yaocw2020** [comment]
Do you mean you could not access the service? If so, where's the client? Could you provide more information about the network/route connectivity? @slickwarren

**Comment by slickwarren** [comment]
I was able to test it on a previous version of rancher here https://github.com/rancher/dashboard/issues/5438
The workload and service(s) created come to an active state, but the service is not accessible to the user (when clicking the link to the loadbalancer, the service is not found)

after editing the LB service to have health checks enabled, the service is then accessible through the LB

**Comment by yaocw2020** [comment]
Same as https://github.com/harvester/harvester/issues/2041

**Comment by noahgildersleeve** [comment]
Is this going to be dependent on #1762  ?

**Comment by yaocw2020** [comment]
> Is this going to be dependent on #1762 ?

No, it will be fixed in the pr https://github.com/harvester/cloud-provider-harvester/pull/15

**Comment by yaocw2020** [comment]
Workaround:
https://github.com/harvester/harvester/issues/2041#issuecomment-1091002704

**Comment by yaocw2020** [comment]
Close as it's duplicated with https://github.com/harvester/harvester/issues/2041
