### ISSUE TITLE
[QUESTION] Document a single-node setup used for testing/homelab etc.

### ISSUE THREAD

**Issue by victorhooi** [harvester/harvester#2079]
**Is your feature request related to a problem? Please describe.**

Previously, setting up a single-node k3s cluster was possible - either for learning, or for very small-scale setups, or a homelab.

It's a little unclear if this is possible with Harvester - would be good to document somewhere.

**Describe the solution you'd like**

Add notes somewhere (README or docs?) about whether single-node setups are possible, and if so, how to achieve them, as well as the caveats/tradeoffs.

Questions that I can think of, that could be covered:

1. Is it possible to setup a single-node Harvester setup currently? Are there any special steps, or changes you need to make to the installation to make this work? (e.g. I noticed [hardware requirements](https://docs.harvesterhci.io/v1.0/#hardware-requirements) mentions three nodes for management - I assume this means the control plane/etcd - can you do a 1-node setup, with control plane and workload on the same box?)
2. Are there any caveats this this kind of setup? What is likely to be slow/unreliable? Any other sorts of pitfalls to watch out for?
3. In terms of storage - would still use the included Longhorn for storage? If the single-node has multiple disk-drives, will that change anything?

**Describe alternatives you've considered**

**Additional context**

**Comment by yasker** [comment]
Hi @victorhooi ,

1. Harvester can run with single node well. It doesn't have HA of course, but all the functionality works.
2. The performance would be the same. The only downside is you won't have high availability (of course..).
3. Yes, Longhorn will be running with single replica. By default Longhorn is running hard anti-affinity across the nodes, so even more disk won't make Longhorn put more replicas on different disks.

**Comment by w13915984028** [comment]
Update Harvester document about the single-node Harvester cluster setup and the limitations like LH replica.
