### ISSUE TITLE
[BUG] Vlan not working after restart

### ISSUE THREAD

**Issue by felixtegelkamp** [harvester/harvester#2081]
**Describe the bug**
Setup Harvester VLan settings and Vlan for host and a new network.
It does work fine at first.
However on restart, the vlan configuration is not working anymore and the VMs using the network cannot be accessed from outside anymore (ping/ssh).
When I ssh into the host the vm is pingable/sshable.

![Bildschirmfoto 2022-03-25 um 16 19 54](https://user-images.githubusercontent.com/9285028/160153109-93ebf3e8-efea-4619-8574-f2a694793fc9.png)

![Bildschirmfoto 2022-03-25 um 16 22 11](https://user-images.githubusercontent.com/9285028/160153123-86d7076a-d84b-442c-84e9-a8fef9c2e514.png)

The management network nic is within a the subnet xxx.0.0.1/24 configured via router/firewall (Dreamachine Pro)
The second nic eno2 is within the subnet xxx.0.10.1/24 configured via router/firewall (Dreamachine Pro)

After restart I have to switch the vlan to management and back to eno2 to get the Vlan working again.

**Environment:**
 - Harvester ISO version: 1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
   Supermicro Barebone SuperServer SYS-5019C-M4L
   Intel(R) Xeon(R) E-2236 CPU @ 3.40GHz
   32GiB DIMM DDR4 Synchronous 2667 MHz
   /dev/sda   disk           1TB SanDisk SSD PLUS
   /dev/sdb   disk           1TB SanDisk SSD PLUS

**Comment by Tanksta** [comment]
Ok I guess I found the actual problem.
On my Dreammachine Switch is set a the subnet with vlan_id 3 but in the harvester network it was set to vlan id 1

**Comment by yaocw2020** [comment]
Could you provide the support bundle?

**Comment by felixtegelkamp** [comment]
[supportbundle_a9ecd02f-0ba4-4b37-8681-42070ea54dac_2022-03-28T11-17-49Z.zip](https://github.com/harvester/harvester/files/8362171/supportbundle_a9ecd02f-0ba4-4b37-8681-42070ea54dac_2022-03-28T11-17-49Z.zip)

**Comment by felixtegelkamp** [comment]
Actually this does not only happen on restart. 
The vlan network drops from time to time and does not recovery.
The fix is to switch the hosts vlan nic to management nic and then back to the second nic.

**Comment by yaocw2020** [comment]
Maybe you collected the support bundle after switching and could not see the abnormal things. Could you try to upgrade to the latest version v1.0.1? I believe It will behave better.

**Comment by felixtegelkamp** [comment]
Thank you. I will try to upgrade.

**Comment by felixtegelkamp** [comment]
> Maybe you collected the support bundle after switching and could not see the abnormal things. Could you try to upgrade to the latest version v1.0.1? I believe It will behave better.

Thank you very much for your advice and patience! The upgrade fixed this issue.
