### ISSUE TITLE
[Question] VM not starting after installation from ISO

### ISSUE THREAD

**Issue by klinux** [harvester/harvester#2085]
i'm trying to install Linux from ISO, I'm using **harvester-public/iso-image-base-template**, the installation complete successfully, by not start, there something that I need to configure to boot VM?

Thank you

**Comment by w13915984028** [comment]
@klinux  Is this issue solved later ?

And, do you have more details:
The Harvester version;  installed from ISO/PXE or `dev-mode`
The cluster scale, how many nodes and roughly resources in each node (cpu cores, memory, storage)

The log from the related POD which hold the VM. thanks.

**Comment by w13915984028** [comment]
Close.

@klinux Please feel free to reopen when you still have such issue, thanks.
