### ISSUE TITLE
[BUG] Installation failed due to unintended activation of LVM vgs on installer start up

### ISSUE THREAD

**Issue by ghost** [harvester/harvester#2086]
**Is your feature request related to a problem? Please describe.**
If installing onto a system where the target disk is a pre-existing LVM pv, the installer's OS activates the vg, causing installation to fail the first time around (can't update disk because it is in use, prompts to reboot to update partition table of the disk) unless the user takes steps to avoid this.

**Describe the solution you'd like**
If LVM is configured not to scan for / activate volume groups, this should easily avoid the issue.

**Describe alternatives you've considered**
Workaround: The user can use the login console and deactivate things manually using lvm cli tools before completing installation to avoid a reboot.

**Additional context**
Thanks for building such a wonderful tool.

**Comment by bk201** [comment]
@lotyrin Thanks for reporting. This is duplicated with https://github.com/harvester/harvester/issues/2230, let's track by that one.
