### ISSUE TITLE
[FEATURE] show `harvester-mgmt` IP info in console not only VIP

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2087]
**Is your feature request related to a problem? Please describe.**

Nope

**Describe the solution you'd like**

Show `harvester-mgmt` IP info in console for debug and determine the node to access (e.g. ssh)

It will check the interface with the default route to have the primary/first IP from it.
If not, it will fall back to `harvester-mgmt` and get IP from it.

**Describe alternatives you've considered**

**Additional context**

PR: https://github.com/harvester/harvester-installer/pull/289

### Test plan

1. build harvester-installer with `make`
2. copy harvester-installer with `scp bin/harvester-installer rancher@<IP>:<PATH>
3. Switch harvester console to TTY2 or other (press CTRL+ALT+F2)
4. execute harvester-installer in current TTY `DEBUG=true HARVESTER_DASHBOARD=true TTY=/dev/tty <PATH>/harvester-installer`
5. check the screen has Node IP and IP address (refer the figure below)
![Screenshot_node1_2022-06-14_10:53:17](https://user-images.githubusercontent.com/2821179/173483721-98e4c124-0689-4bbf-ba45-3a60faefb3ea.png)

**Comment by yasker** [comment]
@tjjh89017 You're talking about the console on the node after boot up, right?

**Comment by tjjh89017** [comment]
> @tjjh89017 You're talking about the console on the node after boot up, right?

Yes, it is.

**Comment by bk201** [comment]
Let's backport this change too, it should be straightforward.

**Comment by tjjh89017** [comment]
Update backport PR https://github.com/harvester/harvester-installer/pull/290

**Comment by TachunLin** [comment]
Verified **fixed** on `master-96b9071-head`. Close this issue.

### Result
The console UI of node after boot up now also display the `harvester-mgmt` IP and `hostname` info of the current node
![image](https://user-images.githubusercontent.com/29251855/174704175-b04b79eb-19b4-4cae-9162-ca11497fdcc5.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-96b9071-head

### Verify Steps
1. ISO install harvester
2. Provide DHCP VIP and node IP
3. Wait until the installation complete and node boot up 
4. Check the console UI display

### Additional Context
The follow up enhancement can refer to #2402
