### ISSUE TITLE
[Question] Does harvester support linked clone?

### ISSUE THREAD

**Issue by wonleing** [harvester/harvester#2090]
Does harvester support clone VM base on a template, then all changes go into a delta storage? Just like linked clone in openstack.
Any plan or doc about this?

**Comment by joshmeranda** [comment]
As of now harvester does not support this type of functionality, but may in a future release. It looks like there is an existing issue to support a similar functionality: https://github.com/harvester/harvester/issues/571

**Comment by tlehman** [comment]
Closing this given that there exists #571 to track this feature request.
