### ISSUE TITLE
[BUG] Upgrade: use an alternative location for version details

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2091]
**Describe the bug**

Harvester backend periodically pulls new versions from the upgrade responder.
But per the discussion in https://github.com/harvester/harvester/issues/1849, we need to pull version details like `ISOURL` and `ISOChecksum` from other locations instead of the responder.

Possible choices are
- Release artifacts (same with Harvester ISO).
- Github artifacts

This needs to be included in `v1.0.1`.

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
@FrankYang0529 base on the instruction https://github.com/harvester/tests/issues/257,
In Phase 3, `release-download-url` is not available in the dashboard (`v1.0.0`).

I think the test plan should be updated.

**Comment by FrankYang0529** [comment]
@lanfon72 for `v1.0.0` to `v1.0.1`, we expect users to apply `version.yaml` manually ([ref](https://github.com/harvester/docs/blob/9c69ade632f1761a1dd3efa3725628ceae028771/docs/upgrade/automatic.md)), so we don't need `release-download-url` for `v1.0.0`, because we don't automatically get a new `Version` in `v1.0.0`.

To test the function, we can update the image of `harvester-system/harvester` deployment to the `master-head` version and follow **Phase 3** test steps to see whether controller can automatically get a new `Version`.  Thank you.

**Comment by lanfon72** [comment]
I think the setting `release-download-url` is not added in UI. (tested on `v1.0.1-rc1` and `v1.0.1-rc2` with **ui-source=External**)

cc @guangbochen

**Comment by WuJun2016** [comment]
Hi,  @lanfon72   frontend pr has been merged, please help to test the issue,  thanks

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

**upgrade-responder**
![image](https://user-images.githubusercontent.com/5169694/162403408-518c28d2-ffa7-4d0b-b9e8-31e6bf89268c.png)
**media server**
![image](https://user-images.githubusercontent.com/5169694/162403458-fdc36711-19e4-41ca-9dee-b8d22ff26821.png)
**node's log**
![image](https://user-images.githubusercontent.com/5169694/162403685-866afcb6-d756-431a-95b2-84de86c743aa.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.1-rc3** to **v1.0.1-rc2**
* **ui-source** Option: **External**

### Verify Steps:
** modified Steps from https://github.com/harvester/tests/issues/257#issue-1185103373
#### Setup upgrade-responder
1. Deploy influxdb. `docker run -d --name influxdb -p 8086:8086 influxdb:1.8`
1. Clone https://github.com/harvester/upgrade-responder.
1. Edit `config/response.json` as following:
1. Run `go run main.go --debug start --upgrade-response-config config/response.json --influxdb-url http://localhost:8086 --geodb geodb/GeoLite2-City.mmdb`.
```json
{
	"Versions": [{
		"Name": "v1.0.1-rc2-local",
		"ReleaseDate": "2022-04-07T22:00:00Z",
		"Tags": ["dev","latest"]
	}]
}
```

#### Setup media server
1. Download `v1.0.1-rc2` from [github](https://github.com/harvester/harvester/releases/tag/v1.0.1-rc2)
1. Download `version.yaml` from https://releases.rancher.com/harvester/v1.0.1-rc2/version.yaml
1. Put those files into the folder `./v1.0.1-rc2`
1. Update **version.yaml**
    a. name: `v1.0.1-rc2` => `v1.0.1-rc2-local`
    b. isoURL: `https://.....` => `http://<your_media_server_ip>:8080/v1.0.1-rc2/harvester-amd64.iso`
1. Start a http server for it: `python3 -m http.server`
#### Install Harvester cluster
  1. If the cluster will be installed on KVM, disable host's firewall
  3. Login to Dashboard then navigate to settings
  4. Modify **ui-source** to `External`
  5. Modify **upgrade-checker-url** to `http://<your_upgrade-responder-ip>:8314/v1/checkupgrade`
  7. Login to console(server node), delete the pod of node (naming like: harvester-<random_string>-<random_string>)
  8. Login to Dashboard, the **upgrade button** should appear
  9. Click the **upgrade button**, `v1.0.1-rc2` should appear in the list
  10. Login to Dashboard then navigate to settings
  11. Modify **release-download-url** to `http://<your_media_server_ip>:8000/`
  12. Login to console(server node), delete the pod of node
  13. Login to Dashboard, the **upgrade button** should appear
  14. Click the **upgrade button**, `v1.0.1-rc2-local` should appear in the list
