### ISSUE TITLE
[BUG] create vm by using terraform-provider-harvester failed when  set `ssh_authorized_keys` in cloud-init users section (not the root)

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2095]
**Describe the bug**

**To Reproduce**
1. Use the master head docker image for testing refer to this [wiki page](https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing)
2.  `terraform apply` the following config
```hcl
resource "harvester_virtualmachine" "opensuse-dev" {

  name        = "opensuse-dev"
  description = "test raw image"

  tags = {
    ssh-user = "opensuse"
  }

  cpu    = 1
  memory = "1Gi"

  start        = true
  hostname     = "opensuse-dev"
  machine_type = "q35"

  ssh_keys = [<THE_EXISTED_SSH_KEY>]

  network_interface {
    name         = "nic-1"
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = "default/<THE_IMAGE_NAME>"
    auto_delete = true
  }

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      user: opensuse
      password: root
      chpasswd:
        expire: false
      ssh_pwauth: true
      users:
      - name: opensuse
        ssh_authorized_keys:
          - >-
            <THE SSH KEY>
      EOF
    network_data = ""
  }
}
```

Error:
```bash
missing ssh public keys in cloud-int userdata ssh_authorized_keys section, ssh_keys: [<THE SSH KEY>].
Either remove unused ssh keys from "ssh_keys" or add ssh public keys to cloud-int userdata ssh_authorized_keys section. 
```

**Expected behavior**

- If you specify ssh key names in harvester_virtualmachine's ssh_keys, but missing ssh public keys in cloud-int userdata users and root ssh_authorized_keys section, will failed.
- If you specify ssh key names in harvester_virtualmachine's ssh_keys, and specify the ssh public keys in cloud-int userdata  users and root ssh_authorized_keys section, will succeed.
- If you do not specify ssh key names in harvester_virtualmachine's ssh_keys, will succeed.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
issue for ssh_authorized_keys in the root section: https://github.com/harvester/harvester/issues/1807

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.1-GA**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2095#issue-1185808425

**Comment by khushboo-rancher** [comment]
For future, when doing this kind of testing we can post the tested steps in details with scripts used (here test result with  terraform config), so that it will help when we are revisiting it or implementing test automation.

cc: @harvester/qa
