### ISSUE TITLE
[BUG] typo in error message

### ISSUE THREAD

**Issue by dexwood** [harvester/harvester#2105]
**Describe the bug**
I found a typo in an error message dealing in persistentvolumeclaim/validator.go

admission webhook "validator.harvesterhci.io" denied the request: resizing is only supported for detached volumes. The volueme is being used by VM default/testubuntu. Please stop the VM first.

**To Reproduce**
1. Try to edit a persistent volume claim while it is attached.

**Expected behavior**
The following error message is expected:

admission webhook "validator.harvesterhci.io" denied the request: resizing is only supported for detached volumes. The volume is being used by VM default/testubuntu. Please stop the VM first.

**Environment:**
 - Harvester ISO version: 1.0.0

**Comment by slash2314** [comment]
See pull request #2106

**Comment by guangbochen** [comment]
close as the PR https://github.com/harvester/harvester/pull/2106 is merged, thanks for ur contribution!
