### ISSUE TITLE
An ambiguous error message shows up while creating a VM without selecting an image

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#211]
**Steps to reproduce:**
1. Create a VM, fill in all the required fields but having the image not selected
2. Click the create button

**Result:**
An ambiguous error message shows up
![image](https://user-images.githubusercontent.com/57614736/97851424-54023a80-1d30-11eb-8528-441704988bd2.png)

If having the image selected but not filling anything in CPU and Memory, another familiar error message will be encountered.
![image](https://user-images.githubusercontent.com/57614736/97852533-d2131100-1d31-11eb-8276-866bbd0a9265.png)

**Comment by guangbochen** [comment]
close in favor of the latest UI on 16/11
