### ISSUE TITLE
[FEATURE] Allow for disabling some 

### ISSUE THREAD

**Issue by joshmeranda** [harvester/harvester#2111]
**Is your feature request related to a problem? Please describe.**

Some functionality is not strictly necessary for harvester to perform its core functionality, and may waste resources or add constraints on some smaller deployments. Seen in https://github.com/harvester/harvester/issues/2051 where too little storage breaks Prometheus monitoring.

![graphs-no-load](https://user-images.githubusercontent.com/43455015/161339390-082ef1fe-56e1-46a3-b189-cd33bdd266f8.png)

**Describe the solution you'd like**

Allow for disabling some non-vital functionality to limit resource utilization such as Prometheus monitoring in Harvester / Rancher dashboard.

In the Prometheus example this would probably require stopping the pods and services in the `cattle-monitoring-system` namespace, and adding a new setting scoped to a new role.

**Comment by bk201** [comment]
Close because monitoring is now moved into optional add-ons.
