### ISSUE TITLE
[BUG] Harvester clusters should use v3.4.x version of etcd

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2112]
**Describe the bug**
At present, Harvester v1.0.1-rc2 has upgraded its RKE2 version to v1.22.7+rke2r1· and uses etcd [v3.5.1-k3s1](https://github.com/rancher/rke2/releases/tag/v1.22.7%2Brke2r1) version by default, we need to either downgrade or upgrade the RKE2 version that only uses v3.4.x etcd version,

https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc/m/rSgNOzV2BwAJ?pli=1

**Expected behavior**
Only use v3.4.x etcd version of the Harvester cluster.

**Environment:**
 - Harvester ISO version: v1.0.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): All

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in v1.0.1-rc3.
## Validation steps
1. Deploy a new Harvester v1.0.1-rc3 1 node cluster from ISO
2. Check `kubectl version`
![Screenshot from 2022-04-07 21-39-51](https://user-images.githubusercontent.com/83787952/162364782-a429ddd8-29c2-40b2-b6ab-fe257343400c.png)

---

1. Deploy v1.0.0 Harvester node
2. Run upgrade to v1.0.1-rc3
3. Check version with `kubectl version`
![Screenshot from 2022-04-07 20-52-50](https://user-images.githubusercontent.com/83787952/162359528-6c31d33e-b092-42e8-82c5-cd83ae03a851.png)
