### ISSUE TITLE
[Question] Unable to mount disk in ISO installation

### ISSUE THREAD

**Issue by klinux** [harvester/harvester#2113]
I'm using the windows template: **windows-iso-image-base-version**

And I can't start the installation the VM can´t boot and in the events I get this error bellow:

`MapVolume.MapPodDevice failed for volume "pvc-58dea4ba-00e0-4221-a061-b088c5c0633a" : rpc error: code = Internal desc = Could not mount "/dev/longhorn/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a" at "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a/c8c79ec0-f606-4232-9cf5-4d43d19640a1": mount failed: exit status 32 Mounting command: mount Mounting arguments: -o bind /dev/longhorn/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a/c8c79ec0-f606-4232-9cf5-4d43d19640a1 Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a/c8c79ec0-f606-4232-9cf5-4d43d19640a1: special device /dev/longhorn/pvc-58dea4ba-00e0-4221-a061-b088c5c0633a does not exist.`

If I let only cdrom disk, the VM can boot, but  if I add disk the VM don't start.

There something that I can do to solve this problem?

Thank you

**Comment by w13915984028** [comment]
@klinux Could you add more details, thanks.

```
Harvester release:
Cluster NODE count and NODE resources:

For this VM:
The detailed operation steps in WebUI of creating the VM.
The CPU, memory, volume for it.
The related POD state.
The related full log.
...
```

If a support-bundle is attached, it will be great.
