### ISSUE TITLE
[BUG] You can see cattle-monitoring-system volumes as restricted admin in Harvester

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2116]
**Describe the bug**

When you log in via Rancher RBAC with restricted admin you can see cattle-monitoring-system volumes in the volumes page
**To Reproduce**
1. Import Harvester to Rancher
2. Create restricted admin in Rancher
3. Log out of rancher
4. Log in as restricted admin
5. Navigate to Harvester ui in virtualization management
6. Navigate to volumes page

**Expected behavior**

You shouldn't see cattle-monitoring-system volumes in the volumes page
**Support bundle**

[supportbundle_5b73698a-923a-4155-9d46-5ad228783b25_2022-04-06T01-25-35Z.zip](https://github.com/harvester/harvester/files/8422850/supportbundle_5b73698a-923a-4155-9d46-5ad228783b25_2022-04-06T01-25-35Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.0
 - Rancher Version: v2.6.4 in single node docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node virtualized environment

**Additional context**
This was in Rancher v2.6.4 and Harvester v1.0.0. The dark mode screenshot is from the Harvester UI while logged in via the Harvester VIP
![Screenshot from 2022-04-05 18-29-44](https://user-images.githubusercontent.com/83787952/161877774-dda67082-7076-4a72-ab60-458db3c915ad.png)
![Screenshot from 2022-04-05 18-25-08](https://user-images.githubusercontent.com/83787952/161877775-d5847551-b145-4cd1-b570-8b76f133f6bb.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-c2960206-head` (06/17) with Rancher `v2.6.5` . Close this issue.

### Result
Login Rancher with restricted admin and access Harvester volume page. 
Now it won't display the cattle-monitoring-system volumes. 
  ![image](https://user-images.githubusercontent.com/29251855/174289481-00e74f70-c773-47af-847c-9ca6ecd86e1d.png)

### Test Information
* Test Environment: 1 node harvester on local bare machine
* Rancher version: v2.6.5
* Harvester version: `master-c2960206-head` (06/17)
* ui-dashboard-url: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html 

### Verify Steps
1. Import Harvester to Rancher
2. Create restricted admin in Rancher
3. Log out of rancher
4. Log in as restricted admin
5. Navigate to Harvester ui in virtualization management
6. Navigate to volumes page
