### ISSUE TITLE
[BUG]  Incorrect style of global message alert

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2117]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/cd2003bd-091e-40c8-af0c-4ba085b77714)

**To Reproduce**
1. create a vm
2. take a backup
3. there is a global message when the backup is created successfully  (incorrect style)
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/be6579e6-4726-4669-a712-1d679c9b3ca9)

**Expected behavior**

The message alert should be at the top
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/e9076dfa-3a71-4cf6-be8e-2a686228d896)

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/162256713-c19417cc-9d0d-4b78-8976-475c79c99cdd.png)

Test Information
----
* Environment: **Bare metal DL360 3 nodes**
* Harvester Version: **v1.0.1-rc2**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2117#issue-1194114773
