### ISSUE TITLE
harvester minio HA setup

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#212]
**Description:**
configure harvester to support minio HA by default, it should tolerant of a single minio pod failure.

**Comment by guangbochen** [comment]
link to pr https://github.com/rancher/harvester/pull/243

**Comment by gitlawr** [comment]
Validated in master 12/16
1. Deploy harvester by chart
2. Delete one of the minion pod

Result:
When the pod is terminating, I can import VM images successfully.
The mini pod will recover to a running state.
