### ISSUE TITLE
[BUG] Updating Rancher CA will not update the cacerts hash in harvester

### ISSUE THREAD

**Issue by bgulla** [harvester/harvester#2121]
This may be a rancher bug or harvester, starting here first.

**Describe the bug**
I recently updated the CA of my Rancher (`kubectl get setting cacerts -n cattle-system`) instance and then starting getting x509 errors from my harvester provisioner. Provisioning would then fail.

In order for me to have Rancher successfully manage my downstream harvester cluster, I had to go to the harvester ui, clear the `cluster-registration-url` and re-add it. Then it seems that harvester re-pulled the cacerts value.

**Comment by guangbochen** [comment]
This is the expected behavior of Rancher and please refer to [update-ca-cert](https://rancher.com/docs/rancher/v2.6/en/installation/resources/update-ca-cert/#why-is-this-step-required) for more details.
> When Rancher is configured with a certificate signed by a private CA, the CA certificate chain is downloaded into Rancher agent containers. Agents compare the checksum of the downloaded certificate against the CATTLE_CA_CHECKSUM environment variable. This means that, when the private CA certificate is changed on Rancher server side, the environvment variable CATTLE_CA_CHECKSUM must be updated accordingly.

**Comment by guangbochen** [comment]
close as of the above description, and feel free to re-open it if u have any better suggestions, thanks.
