### ISSUE TITLE
[BUG] VMs stuck terminating when provisioning through rancher

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2123]
**Describe the bug**
When provisioning through rancher, some nodes did not get to the final step to register with k8s. Rancher deleted the existing node and brought up a new one, however that existing node never deleted in harvester. 

**To Reproduce**
1. provision a single node-per-role rke1 cluster through rancher using rke1
2. wait for nodes to become active

**Expected behavior**
all nodes should come to a healthy state. any node(s) removed in the process should be properly removed from harvester. 

**Support bundle**

[supportbundle_f97ef78f-9917-4e2e-bcec-e8cf206e1090_2022-04-07T06-10-02Z.zip](https://github.com/harvester/harvester/files/8440088/supportbundle_f97ef78f-9917-4e2e-bcec-e8cf206e1090_2022-04-07T06-10-02Z.zip)

**Environment:**
 - Harvester ISO version:  1.0.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge r510

this setup has rancher running on one of the harvester VMs. 
<img width="1022" alt="Screen Shot 2022-04-06 at 11 09 07 PM" src="https://user-images.githubusercontent.com/16691014/162133360-5bc34755-2810-43a2-8f07-c013c92515c8.png">

**Comment by FrankYang0529** [comment]
Hi @slickwarren, I cannot reproduce this issue in Harvester `v1.0.1` with Rancher `v2.6.4`. I can create RKE1 `v1.22.7` with focal image (2 vCPU, 4G RAM and 40G storage).

![Screen Shot 2022-04-14 at 2 01 58 PM](https://user-images.githubusercontent.com/4927361/163327182-1759490f-5dce-49d5-89f9-44f81919d223.png)
![Screen Shot 2022-04-14 at 2 02 06 PM](https://user-images.githubusercontent.com/4927361/163327192-df4af758-eab6-440a-8895-b9768cfdd87f.png)


Based on your support-bundle, I think you environment is:
* 1-node Harvester (24 CPU, 126G RAM)
* 9 VMs with 2 vCPU and 4G RAM
* 1 VM with 4 vCPU, 8G RAM

So your cluster should have enough resource to afford 10 VMs. However, in `pods.yaml`, it shows 6 VM pods has exited code 137 which is OOMKilled. Previously, we also have some VM OOMKilled issues, but they are not like this one.

* https://github.com/harvester/harvester/issues/1823#issuecomment-1040004927
* https://github.com/harvester/harvester/issues/1730#issuecomment-1057655226

I also notice there are some weird message in `rke2-server.log`:

```
rke2-server.service: Found left-over process 18135 (kubectl) in control group while starting unit. Ignoring.
This usually indicates unclean termination of a previous run, or service implementation deficiencies.
```

```
rke2[18551]: time="2022-04-06T21:54:22Z" level=warning msg="Failed to remove cgroup (will retry)" error="rmdir /sys/fs/cgroup/devices/kubepods/burstable/pod44d948f2100daf9e648ed38764ed4af7/32bb12a089a423d87ac14497b56e4f017e43632b59573eec61361fb3a08a1402: device or resource busy"
```

May you help me clarify these questions? Thank you!
* Is this issue always reproducible on your cluster? If yes, may you try to run `systemctl restart rke2-server.service` and try again? Thank you.
* Is there any special setting about RKE1?
* Did you restart Harvester cluster with any error?

**Comment by slickwarren** [comment]
* this is not consistently reproducible for me
* there isn't anything special afaik about rke1/settings
* I regularly restart my harvester setup, but this was on a fresh install of the RC.

**Comment by FrankYang0529** [comment]
RKE2 version is different on Harvester. `v1.0.1-rc2` uses RKE2 `1.22.7+rke2r1` and `v1.0.1` uses RKE2 `1.21.11+rke2r1`.

On Harvester `v1.0.1-rc2` cluster,  there is log like `Failed to remove cgroup (will retry)" error="rmdir /sys/fs/cgroup/systemd/kubepods/burstable/podc37b8b12c8f57845c0ed443b5ac3d1ee/4f8391cfb6dea799bbaabcec3655eba00ea0728b83dc9f097cd8036b24d31279: device or resource busy`, but this doesn't happen in Harvester `v1.0.1`.

I also can provision RKE1 on Harvester `v1.0.1-rc2` without error.

**Comment by FrankYang0529** [comment]
In support-bundle, we can see the `robustness` of LH Volume is `unknown`. Also, logs in LH engine manager show `Setting replica tcp://xxx to ERR due to: r/w timeout` first, and then many `I/O error: No backend available`. So I think there may be network issue between the LH engine manager and replica manager.

I try to kill the connection between the engine manager and replica manager with the following steps. VM pod will be stuck in `Terminating` and its `containerStatuses` shows `exitCode: 137`. Also, logs in kubelet are similar to https://github.com/harvester/harvester/issues/2137.

```
E0428 08:10:24.558722   15240 nestedpendingoperations.go:335] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-d042adad-8254-4eba-b4dd-b378647e276f podName:c67e7a78-d489-4cf8-acb9-e8da287db975 nodeName:}" failed. No retries permitted until 2022-04-28 08:12:26.558706566 +0000 UTC m=+14240.221959502 (durationBeforeRetry 2m2s). Error: UnmapVolume.UnmapBlockVolume failed for volume "disk-0" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-d042adad-8254-4eba-b4dd-b378647e276f") pod "c67e7a78-d489-4cf8-acb9-e8da287db975" (UID: "c67e7a78-d489-4cf8-acb9-e8da287db975") : blkUtil.DetachFileDevice failed. globalUnmapPath:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-d042adad-8254-4eba-b4dd-b378647e276f/dev, podUID: c67e7a78-d489-4cf8-acb9-e8da287db975, bindMount: true: failed to unmount linkPath /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-d042ada
d-8254-4eba-b4dd-b378647e276f/dev/c67e7a78-d489-4cf8-acb9-e8da287db975: unmount failed: exit status 32
Unmounting arguments: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-d042adad-8254-4eba-b4dd-b37864
7e276f/dev/c67e7a78-d489-4cf8-acb9-e8da287db975
Output: umount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-d042adad-8254-4eba-b4dd-b378647e276f
/dev/c67e7a78-d489-4cf8-acb9-e8da287db975: target is busy.
```

Reproduce steps:
* Start a 1-node cluster with harvester version `v1.0.1-rc2`.
* Create a VM.
* Get volume name of VM.
* Login `instance-manager-r-xxx`.
* Use `ss` to list socket connections and `ss -K` to kill connection.
```
root@instance-manager-r-37fa71ad:/# ss
Netid    State    Recv-Q    Send-Q             Local Address:Port               Peer Address:Port     Process
tcp      ESTAB    0         0            [::ffff:10.52.0.37]:10001       [::ffff:10.52.0.36]:38406
tcp      ESTAB    0         0            [::ffff:10.52.0.37]:8500        [::ffff:10.52.0.26]:41918
tcp      ESTAB    0         0            [::ffff:10.52.0.37]:10016       [::ffff:10.52.0.36]:38832
tcp      ESTAB    0         0            [::ffff:10.52.0.37]:10031       [::ffff:10.52.0.36]:57766
root@instance-manager-r-37fa71ad:/# ss -K dport = 57766
Netid    State    Recv-Q    Send-Q             Local Address:Port               Peer Address:Port     Process
tcp      ESTAB    0         0            [::ffff:10.52.0.37]:10031       [::ffff:10.52.0.36]:57766
```

I try the above steps on harvester `master-head` and I cannot reproduce anymore,  so I think the root cause is the same as #2137.

**Comment by guangbochen** [comment]
close as this issue can't be reproduced after fixing the issue https://github.com/harvester/harvester/issues/2137, feel free to reopen it if u encounter it again, thanks.
