### ISSUE TITLE
[BUG] rancher provisioned rke2 control plane went down when adding a new cluster through rancher

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2124]
**Describe the bug**
An rke2 cluster provisioned through rancher had been up for nearly 6 hours. I then provisioned a separate rke1 cluster through rancher, and about at the same time the control plane node of the rke2 cluster went down. 

**To Reproduce**
1. provision a single node-per-role rke2 cluster through rancher using rke2
2. wait for nodes to become active
3. provision an rke1 cluster through rancher

**Expected behavior**
though rancher is reporting the control plane node down, (see screenshot) harvester shows the etcd node has restarted/is in a bad state

**Support bundle**

[supportbundle_f97ef78f-9917-4e2e-bcec-e8cf206e1090_2022-04-07T06-10-02Z.zip](https://github.com/harvester/harvester/files/8440088/supportbundle_f97ef78f-9917-4e2e-bcec-e8cf206e1090_2022-04-07T06-10-02Z.zip)

**Environment:**
 - Harvester ISO version:  1.0.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge r510

this setup has rancher running on one of the harvester VMs. 

<img width="1022" alt="Screen Shot 2022-04-06 at 11 09 07 PM" src="https://user-images.githubusercontent.com/16691014/162133360-5bc34755-2810-43a2-8f07-c013c92515c8.png">

<img width="284" alt="Screen Shot 2022-04-06 at 11 09 31 PM" src="https://user-images.githubusercontent.com/16691014/162133820-c58a04e2-a6df-4a07-9c0d-9388f9e7324c.png">

**Comment by bk201** [comment]
We can't reproduce this in the newer version (Rancher 2.6.9 + Harvester v1.1.0). Please reopen if see this again. Thanks.
