### ISSUE TITLE
[BUG] OS: need to catch up cos-toolkits

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2133]
**Describe the bug**

Try to catch up latest cos-toolkits today and got this error:

![Screen Shot 2022-04-11 at 3 00 45 PM](https://user-images.githubusercontent.com/1691518/162682392-ecc1c480-d02f-4f25-ad64-5008bb2be33b.png)

**To Reproduce**
1. clone harvester/os2 repo.
2. Remove this line in `etc/luet/luet.yaml`:
```
reference: 20220302065613-repository.yaml
```
3. build OS
4. Use the OS in the harvester-installer.

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
```
 INFO    Repository cOS revision: 278 (2022-04-07 1227 +0000 UTC)
 INFO    Repository: cos Priority: 1 Type: docker
 INFO   Packages that are going to be installed in the system:

Program Name            | Version    | License | Repository
system/cos-setup        | 0.6.2      |         | cos
system/immutable-rootfs | 0.4-1      |         | cos
selinux/k3s             | 1.1.1      |         | cos
utils/nerdctl           | 0.18.0     |         | cos
toolchain/elemental-cli | 0.20220405 |         | cos
system/grub2-config     | 0.0.15     |         | cos
utils/k9s               | 0.25.18-5  |         | cos
selinux/rancher         | 0.2.1-5    |         | cos
system/cos-wrapper      | 0.32       |         | cos
toolchain/luet          | 0.30.3     |         | cos
toolchain/yq            | 4.24.2     | MIT     | cos
toolchain/yip           | 0.10.1-3   |         | cos
```

**Comment by TachunLin** [comment]
Verified **fixed** on `master-fdb64376-head` (05/10). Close this issue.

### Result
Test the following cos-toolkit parameter works in https://github.com/harvester/harvester-installer/pull/273
- ForceEFI: `ELEMENTAL_FORCE_EFI`
  - [x] `Force MBR` installation on BIOS firmware virtual machine 
    ![image](https://user-images.githubusercontent.com/29251855/167598271-62adad98-3021-4145-bcdb-351255b69266.png)
    ![image](https://user-images.githubusercontent.com/29251855/167598339-d1bbfdba-1bdb-41e3-8d05-ad0c5ca5d152.png)

- Device: Positional arg or `ELEMENTAL_TARGET`
  - [x] Machines with two or more disks can assign the data disk
    ![image](https://user-images.githubusercontent.com/29251855/167603688-f7de6c34-3f5b-43b0-974f-2b457f04cb88.png)
    ![image](https://user-images.githubusercontent.com/29251855/167609905-b660db24-b5df-439c-bf6a-757bb271c8a1.png)
    
    ```
    rancher@harvester-0510:~> lsblk
    NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
    loop0    7:0    0     3G  1 loop /
    sda      8:0    0   150G  0 disk 
    ├─sda1   8:1    0     1M  0 part 
    ├─sda2   8:2    0    64M  0 part /oem
    ├─sda3   8:3    0    15G  0 part /run/initramfs/cos-state
    ├─sda4   8:4    0     8G  0 part 
    └─sda5   8:5    0 126.9G  0 part /usr/local
    sdb      8:16   0   150G  0 disk /var/lib/harvester/defaultdisk
    sdc      8:32   0    10M  0 disk /var/lib/kubelet/pods/c4c40ded-fee5-4c13-9d45-999acd13a154/volumes/kubernetes.io~csi/pvc-7c064d58-e3e8-4d71-8d0
    sdd      8:48   0    50G  0 disk /var/lib/kubelet/pods/acc8e8f6-35be-4a2c-86c1-add111a83a4d/volume-subpaths/pvc-c899caee-d710-4ae7-951b-584d262d
    sr0     11:0    1  1024M  0 rom
    ```
  
  - [x] Machines with two or more disks can choose the same disk as OS and data disk
    ![image](https://user-images.githubusercontent.com/29251855/167613320-7ca461c9-949b-4233-8b0d-684f8bd6b4de.png)
    ![image](https://user-images.githubusercontent.com/29251855/167613556-4c78eb49-e256-4df7-bc4a-c582dd289e50.png)
    
    ```
    rancher@harvester-0510:~> lsblk
    NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
    loop0    7:0    0    3G  1 loop /
    sda      8:0    0  150G  0 disk 
    ├─sda1   8:1    0    1M  0 part 
    ├─sda2   8:2    0   50M  0 part /oem
    ├─sda3   8:3    0   15G  0 part /run/initramfs/cos-state
    ├─sda4   8:4    0    8G  0 part 
    ├─sda5   8:5    0   50G  0 part /usr/local
    └─sda6   8:6    0 76.9G  0 part /var/lib/harvester/defaultdisk
    sdb      8:16   0  150G  0 disk 
    sdc      8:32   0   50G  0 disk /var/lib/kubelet/pods/1862b9a1-3d0e-4f0b-83b7-438841b797e2/volume-subpaths/pvc-dec3b8a7-c31a-4793-aaf3-49e41237c
    sdd      8:48   0   10M  0 disk /var/lib/kubelet/pods/bbcb9e16-562f-4309-8cbd-79ade2c70221/volumes/kubernetes.io~csi/pvc-70acdfa1-51e7-4575-a736
    sr0     11:0    1 1024M  0 rom
    ```

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-fdb64376-head


### Verify Steps
1. `Force MBR` installation on BIOS firmware virtual machine in [comment](https://github.com/harvester/harvester/issues/1241#issuecomment-979307330)
2. Machines with two or more disks can assign the data disk in [comment](https://github.com/harvester/harvester/issues/1728#issuecomment-1056303138)
3. Machines with two or more disks can choose the same disk as OS and data disk in [comment](https://github.com/harvester/harvester/issues/1728#issuecomment-1056716471)
