### ISSUE TITLE
[BUG] Add edit VM related doc

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2136]
**Describe the bug**
Need to add the edit VM documentation page, e.g, https://docs.harvesterhci.io/v1.0/vm/edit-vm/
- general VM editing and expected results.
- describe features like support dynamic ssh key/password injection via AccessCredentials #1538

**Comment by bk201** [comment]
Need to also include `runStrategy: Manual` change from https://github.com/harvester/harvester/issues/2060

**Comment by guangbochen** [comment]
close as the doc is merged via https://github.com/harvester/docs/pull/150
