### ISSUE TITLE
[BUG] Harvester "make package" fails

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2139]
**Describe the bug**

```
/go/src/github.com/harvester/harvester$ make package
...
IMAGE_PUSH_TAG: debug-2013-head
./scripts/package: line 11: cd: ./scripts/package: Not a directory
FATA[0011] exit status 1                                
make: *** [Makefile:11: package] Error 1
...
```

**To Reproduce**
1. Harvester source code master-head
2. make build
3. make package, the failure occurs

**Expected behavior**

`make package` should be successful

**Support bundle**

**Environment:**
 - Harvester ISO version: V1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Linux, X86

**Additional context**

**Comment by w13915984028** [comment]
unfortunately, directly "make package-webhook" is also failed,  only "make package-upgrade " is successful

```
/go/src/github.com/harvester/harvester$ make package-webhook 

ARCH: amd64
VERSION: cf837a6f-dirty
CHART_VERSION: 0.0.0-fix-2139-cf837a6f-dirty
APP_VERSION: fix-2139-cf837a6f-dirty
SUFFIX: -amd64
REPO: rancher
TAG: dev
IMAGE_PUSH_TAG: fix-2139-head
./scripts/package-webhook: line 11: cd: ./scripts/package: Not a directory
FATA[0010] exit status 1                                
make: *** [Makefile:11: package-webhook] Error 1


```

**Comment by w13915984028** [comment]
There is conflict between `"make ci" `and `"make package/package-webhook"`

A straightforward fix helps` "make package" `but breaks` "make ci"`
![image](https://user-images.githubusercontent.com/31133476/162944590-9a69074d-b5ca-4060-8d49-56926951f797.png)


`make ci `fails
![image](https://user-images.githubusercontent.com/31133476/162945119-fef90f2f-7655-4365-afbf-1321fa6c7b79.png)

**Comment by noahgildersleeve** [comment]
Tested on harvester master `05b5da2dff3a9188a9d1defca30d905e326e7083` with included repro steps. Fixed.



> **Describe the bug**
> 
> ```
> /go/src/github.com/harvester/harvester$ make package
> ...
> IMAGE_PUSH_TAG: debug-2013-head
> ./scripts/package: line 11: cd: ./scripts/package: Not a directory
> FATA[0011] exit status 1                                
> make: *** [Makefile:11: package] Error 1
> ...
> ```
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Harvester source code master-head
> 2. make build
> 3. make package, the failure occurs
> 
> **Expected behavior**
> 
> `make package` should be successful
> 
> **Support bundle**
> 
> **Environment:**
> 
> * Harvester ISO version: V1.0.1
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Linux, X86
> 
> **Additional context** Add any other context about the problem here.
