### ISSUE TITLE
[BUG] Unable to provision Harvester v1.23.4 RKE2 cluster in Rancher v2.6.4

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2143]
**Describe the bug**

While provisioning v1.23.4 RKE2 cluster in Rancher v2.6.4, it can't finish and stuck in the
`waiting for probes: calico, etcd, kube-vipserver, kube-controller-manager, kube-scheduler, kubelet`
![image](https://user-images.githubusercontent.com/29251855/162962283-a2ec2d1d-cabf-487a-8b4c-79d724c477eb.png)

![image](https://user-images.githubusercontent.com/29251855/162962439-d9e34156-9c8d-4be5-98cf-cb3cf3389c0c.png)

![image](https://user-images.githubusercontent.com/29251855/162962493-3f98d222-3a54-4b52-9260-fc085b465105.png)

**To Reproduce**
1. Prepare one node or three nodes v1.0.1 harvester cluster 
2. Import Harvester to Rancher v2.6.4
3. Create cloud credential 
4. Provision a RKE2 cluster with v1.23.4+rke2r2 (4 core, 8GB ram)
5. Check the provisioning process

**Expected behavior**

Can correctly provision Harvester v1.23.4 RKE2 cluster in Rancher v2.6.4

**Support bundle**
[supportbundle_9069abf1-4703-4a99-85fd-d963655fccb9_2022-04-12T12-29-14Z.zip](https://github.com/harvester/harvester/files/8473784/supportbundle_9069abf1-4703-4a99-85fd-d963655fccb9_2022-04-12T12-29-14Z.zip)

**Rancher log**
[0412_v264.log](https://github.com/harvester/harvester/files/8473790/0412_v264.log)

**Environment:**
 - Harvester ISO version: v1.0.1
 - Rancher version: v2.6.4
 - OS image: ubuntu focal image (04/11)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node kvm machine and 3 nodes bare metal machines

**Additional context**
* Can provision correctly with RKE2 v1.22.7+rke2r1
![image](https://user-images.githubusercontent.com/29251855/162984443-c4f195fb-3d03-460c-bef5-7d278d9fe95e.png)

**Comment by FrankYang0529** [comment]
I can provision RKE2 1.23.4+rke2r2 on master-c5bfa702-head (a version after v1.0.1).

![image](https://user-images.githubusercontent.com/4927361/163113115-36c1f490-1cba-4e33-99c1-5082c9b8b4f5.png)

**Comment by TachunLin** [comment]
Double checked again on my laptop, also can provision RKE2 v1.23.4+rke2r2 on `v1.0.1` with Rancher `v2.6.4` (Ubuntu focal)
The previous symptom may related to network or the date of OS image. 

![image](https://user-images.githubusercontent.com/29251855/163129037-0f0921bd-cc50-4e56-92d8-5b0f23c15661.png)
