### ISSUE TITLE
[BUG]  After the upgrade is complete, the image percentage becomes 0%

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2145]
**Describe the bug**

After a successful upgrade, the upgraded image will be deleted automatically.  At this point the progress bar of image is displayed as 0 %

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/b6eb5544-f883-4024-b4a0-3a8347bc5810)

**To Reproduce**
1. Upgrade from Harvester 1.0.0 to Harvester 1.0.1
2. After the upgrade is successful, check whether the image progress bar still exists  （Expect to hide the progress bar）

**Expected behavior**

After the upgrade is successful, the image progress bar should be hidden

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/163349281-c71d0aac-034c-4481-bee0-59d0eadcd127.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.0** to **master-c5bfa702-head**
* **ui-source** Option: **External**

### Verify Steps:
1. Follow [the upgrade instruction](https://docs.harvesterhci.io/v1.0/upgrade/automatic/) to perform upgrade from **v1.0.0** to **v1.0.1**
2. Update **ui-source Settings**  to External
3. The **Downloaded Upgrade Image** should be hidden
