### ISSUE TITLE
[BUG] VM still got IP Address when poweroff

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2154]
### Describe the bug
The VM still displays `IP Address` with the state `Off`.
The VM was powered off via executing command `sudo poweroff` inside the VM.
refer to #1882 

### To Reproduce
1. Create VM
2. Login to VM and execute `sudo poweroff`
3. VM's **State** become `Off` and the `IP Address` still available

### Expected behavior
VM should not display IP Address.

## Environment:
 - Harvester ISO version: **master-03ee6213-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

### Additional context
**The VM still had IP Address**
![image](https://user-images.githubusercontent.com/5169694/163550961-77e304cb-dc61-48f8-b1e4-f555ee254773.png)
**VM's Restart Button is Enabled**
![image](https://user-images.githubusercontent.com/5169694/163550992-49ccbb38-501d-46dd-a59c-c5a173cd9e2b.png)
**VM's Restart Button is Disabled** when the VM was stopped via dashboard
![image](https://user-images.githubusercontent.com/5169694/163551010-79f1e436-e995-40d5-8db7-db54b3123f1d.png)
**Pod of VM `s1` been removed, but VM `s3b` still exists**
![image](https://user-images.githubusercontent.com/5169694/163551050-9633b6c1-ae81-45f1-8d9e-a58d49821451.png)

**Comment by WuJun2016** [comment]
Current vmi has not been removed, The ip will disappear after a few seconds.

**Comment by lanfon72** [comment]
In the case, VM `s3b` execute `sudo poweroff` inside the VM, then I start VM `s1` and stop it via dashboard.
As the snapshot, IP of VM `s1` been cleared, but the VM `s3b` still shows its IP address.

I think the mainly different is the way of poweroff.

**Comment by WuJun2016** [comment]
> 

Both ways of stopping the vm will have the problem that the ip does not disappear immediately.
The frontend is enhanced, when the vm stops, the UI will hide the IP information

**Comment by lanfon72** [comment]
I think there still have something different between _execute `poweroff`_ and _click `stop`_.

The VM `s1` execute `poweroff` to stop, and the VM `s2` click `stop` button to stop.
and as the screenshots, **s1**'s pod will remaining with **completed** status; in the dashboard, **Restart** Button will appear and clickable, showing scheduled Node.

I also tested when click **Restart / Start** VM `s1`, **completed** will be removed and create new pod for it. (the behavior same as VM `s2` which click `stop` button to stop.)
I'm thinking should we just hide the IP Address and scheduled Node ? or we can terminate the **completed** VM to let behaviors consistent with other VM?

@guangbochen do you have some suggestions?

https://user-images.githubusercontent.com/5169694/163952478-b34bf53a-b4d4-45a7-8713-6e8933f4a979.mp4

![image](https://user-images.githubusercontent.com/5169694/163952194-74982590-5010-4492-9d09-ab231bea9baa.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed as the screenrecord in https://github.com/harvester/harvester/issues/2154#issuecomment-1102244829

The remaining displayed **Node** will not affect other function, so it is fine to keep it.
