### ISSUE TITLE
[QUESTION] Interface name has changed after removal of NIC

### ISSUE THREAD

**Issue by LukasCoder** [harvester/harvester#2155]
I removed a NIC from the server and the other NIC's interface name have changed, leading to me losing connection to the UI since the Harvester Bond now points to an interface that does not exist anymore. How can I change the interface of the bond, since no modifications I do to the system persist after reboot?

**Comment by johnliu55tw** [comment]
To make the config persist across reboots, you have to update `/oem/99_custom.yaml`. Look for the following content in the file:
```
    ...
    - path: /etc/sysconfig/network/ifcfg-harvester-mgmt
      permissions: 384
      owner: 0
      group: 0
      content: |+
        STARTMODE='onboot'
        BONDING_MASTER='yes'
        BOOTPROTO='dhcp'
        BONDING_SLAVE_0='enp9s0'
        BONDING_MODULE_OPTS='miimon=100 mode=balance-tlb '
        DHCLIENT_SET_DEFAULT_ROUTE='yes'
      encoding: ""
      ownerstring: ""
    - path: /etc/sysconfig/network/ifcfg-enp9s0
      permissions: 384
      owner: 0
      group: 0
      content: |
        STARTMODE='hotplug'
        BOOTPROTO='none'
      encoding: ""
      ownerstring: ""
    ...
```
The content here will create the `ifcfg` files for interfaces `harvester-mgmt` and `enp9s0`. Let's say your NIC has been renamed to `enp7s0`, then you would have to replace the two `enp9s0` here with `enp7s0`.
