### ISSUE TITLE
[BUG] Unable to create image by uploading from file, prompt `harvesterhci.io/os` and `harvesterhci.io/image-type` is required

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2158]
**Describe the bug**

Unable to create image from uploading existing ISO file, prompt error message 
1. "harvesterhci.io/os" is required
2. "harvesterhci.io/image-type" is required
  ![image](https://user-images.githubusercontent.com/29251855/163747911-a530f935-08d3-4818-89e5-a1b6bf316bd9.png)
  ![image](https://user-images.githubusercontent.com/29251855/163748084-e62686c4-a598-44d3-8871-65558f1f4ac8.png)

Verified with the following images
1. focal-server-cloudimg-amd64.img
2. SLES15-SP3-JeOS.x86_64-15.3-OpenStack-Cloud-GM.qcow2

**To Reproduce**
1. Go to Images page
3. Select File -> Upload File
4. Select an OS image from local drive
5. Click the create button

**Expected behavior**

Can create image by uploading file correctly without prompting error

**Support bundle**

[supportbundle_28479d0f-c787-4ec6-b759-673c63ce6c76_2022-04-18T03-10-58Z.zip](https://github.com/harvester/harvester/files/8503220/supportbundle_28479d0f-c787-4ec6-b759-673c63ce6c76_2022-04-18T03-10-58Z.zip)

**Environment:**
 - Harvester ISO version: `master-03ee6213-head` (04/15)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node harvester on local kvm machine

**Comment by WuJun2016** [comment]
@TachunLin  Please see the description of the changes in this  [issue](https://github.com/harvester/harvester/issues/2057)

**Comment by TachunLin** [comment]
By setting the `image-type` and `os-type` in Labels. We can create image by uploading image from file 
  ![image](https://user-images.githubusercontent.com/29251855/163762774-14fcd640-5faa-4263-b9fa-485b28d4573d.png)
  ![image](https://user-images.githubusercontent.com/29251855/163762869-c85f5c00-19d8-49ad-ac77-2f9ea01fa8a5.png)

@WuJun2016, @guangbochen, a suggestion is we can add this change for the upcoming v1.0.2 document

**Comment by guangbochen** [comment]
@WuJun2016  @TachunLin I prefer to set those labels as an optional field instead of required, if the user didn't fill it then by default the image will be treated as a disk volume. Also adding an appropriate doc to the [upload image](https://docs.harvesterhci.io/v1.0/upload-image/) page on how to specify the image disk type would be helpful, thanks.

**Comment by TachunLin** [comment]
Verified **fixed** on master-03ee6213-head. (04/18) Close this issue.

### Result
* Now can upload the `.img`, `.iso` and `qcow2` type of image file without adding the `os` and `image-type` by default. 
  ![image](https://user-images.githubusercontent.com/29251855/164357146-22a28f69-be4e-472e-aa95-e41c16878d46.png)
  ![image](https://user-images.githubusercontent.com/29251855/164357945-a8127e0a-7624-4e78-8773-9ea91317d88f.png)

* We can also edit the `os` and `image-type` value, it still can create image without error
![image](https://user-images.githubusercontent.com/29251855/164359232-43ba1372-4ae9-43e9-994d-ed86b36e5012.png)

* Also checked can upload image via URL correctly. 

### Test Information
* Test Environment: 1 node harvester on provo bare machine
* Harvester version: master-03ee6213-head

### Verify Steps=
1. Go to Images page
2. Select File -> Upload File
3. Select an OS image from local drive
4. Click the create button
