### ISSUE TITLE
[BUG] Fail to upgrade nodes' OSes when upgrading from 1.0.1 to master ISO

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2162]
**Describe the bug**

Node OS can't be upgraded when upgrading Harvester from 1.0.1.

**To Reproduce**
1. Build the master ISO.
2. Create a v1.0.1 Harvester cluster and upgrade to the master ISO.
3. post-drain jobs fail with

```
Upgrading to image /tmp/tmp.yoqRYbIVet
+ '[' 1 -gt 2 ']'
+ INTERACTIVE=true
+ _COS_IMAGE=/tmp/tmp.yoqRYbIVet
+ break
+ find_upgrade_channel
+ '[' -n true ']'
+ '[' true == true ']'
+ _CHANNEL_UPGRADES=false
Upgrading system..
+ '[' -n /tmp/tmp.yoqRYbIVet ']'
+ _UPGRADE_IMAGE=/tmp/tmp.yoqRYbIVet
+ echo 'Upgrading to image /tmp/tmp.yoqRYbIVet'
+ trap upgrade_cleanup exit
+ '[' -n '' ']'
+ echo 'Upgrading system..'
+ find_partitions
++ blkid -L
blkid: option requires an argument -- 'L'
Try 'blkid --help' for more information.
++ true
+ _STATE=
+ '[' -z '' ']'
+ echo 'State partition cannot be found'
+ exit 1
+ upgrade_cleanup
State partition cannot be found
+ EXIT=1
+ upgrade_cleanup2
+ return 1
```
**Expected behavior**

Node OS should be upgraded.
**Support bundle**

**Environment:**
 - Harvester ISO version: A local master build
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
The cause is we didn't chroot when invoking `cos upgrade`: https://github.com/harvester/harvester/blob/c5f4564f60ed557259cd06bb35ee114065715d8e/package/upgrade/upgrade_node.sh#L274
And the `cos` script in v1.0.0 loads some variables from host's config file: https://github.com/rancher-sandbox/cOS-toolkit/blob/087d40ce5c8c0a2c2160803491733a67f981a635/packages/backports/installer/cos.sh#L153-L155

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/164188957-1a6cc52d-787c-46a6-b65c-be30ca611ba3.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.0.1** to **master-b20a3b47-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow [the instruction](https://docs.harvesterhci.io/v1.0/upgrade/automatic/) to do upgrade.
