### ISSUE TITLE
[FEATURE] Support PXE boot deployment of ISO similar to Canonical MaaS

### ISSUE THREAD

**Issue by wjimenez5271** [harvester/harvester#217]
In an environment of any significant scale, PXE boot is an effective and proven way to manage hardware imaging. Since Harvester is working on an ISO based deployment, providing a PXE server that can be used to deploy that image would enhance its utility. Canonical's Metal-as-a-Service is a good example of this functionality.

**Comment by innobead** [comment]
@guangbochen if no objection, my team will help with this after discussed with @yasker.

cc @cclhsu @bk201

**Comment by innobead** [comment]
This epic will be broken down into several phases. @bk201 will help to drive the feature development. 

**Phase 1: 0.2.0**
- Support Harvester Installer PXE boot awareness (this needs to update harvester-installer to make sure it have unattended installation mode)

**Phase 2: 0.3.0**
- Support In-Cluster PXE boot service and artifact management (it can be leveraged with other open projects)
- Recognize the nodes to join the cluster (auto or manual) (UX)

**Comment by yasker** [comment]
We also want to support booting Harvester using Equinix Metal since it's one of the most popular baremetal cloud provider there. We should be able to support the iPXE option once phase one is done.

**Comment by wjimenez5271** [comment]
Have we considered UFEI's HTTP support for imaging in addition to TFTP? https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-deployment-prep-uefi-httpboot.html

**Comment by innobead** [comment]
> Have we considered UFEI's HTTP support for imaging in addition to TFTP? https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-deployment-prep-uefi-httpboot.html

Except for PXE boot, users can also use iPXE for HTTP protocol. @bk201 has written the documentation in https://github.com/rancher/harvester/pull/478.

**Comment by bk201** [comment]
> Have we considered UFEI's HTTP support for imaging in addition to TFTP? https://documentation.suse.com/sles/15-SP2/html/SLES-all/cha-deployment-prep-uefi-httpboot.html

I verify it works with UEFI HTTP boot and added the document: https://github.com/rancher/harvester/pull/478/files#diff-094185991127c17e6f9bd32997c402acc413b512cdaca655aeeb8e6354fbad8bR189

**Comment by yasker** [comment]
@guangbochen Has this issue passed the QA? Not sure why it's closed.

**Comment by yasker** [comment]
I see. I think it's because of the keyword `fixes` in the commit message of https://github.com/rancher/harvester-installer/pull/33 . Not sure if we can disable this behavior, otherwise we need to stop using the keyword `fixes`/`fix` etc.

**Comment by vielmetti** [comment]
It's been a few months since the last update on this issue - would be happy to get a current readout of status on it, and any help that we at Equinix Metal could provide for testing.

**Comment by bk201** [comment]
> It's been a few months since the last update on this issue - would be happy to get a current readout of status on it, and any help that we at Equinix Metal could provide for testing.

The feature (Phase 1) is already merged and will be available in release 0.2.0.
There are some supplement documents:
- [Automatic installation](https://github.com/harvester/harvester/blob/master/docs/automatic-installation.md)
- [Example](https://github.com/harvester/ipxe-examples/tree/main/equinix) to deploy on Equinix Metal

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc5

1. Follow [automatic-installation](https://github.com/harvester/harvester/blob/master/docs/automatic-installation.md) to successfully install harvester on bare metal or Equinix Metal or vmware esxi
2. The harvester installation can be initialized according to the [harvester-configuration](https://github.com/harvester/harvester/blob/master/docs/harvester-configuration.md)

**Comment by mimizone** [comment]
was the phase 2 abandoned completely?

**Comment by yasker** [comment]
@mimizone Not really. We've built [Seeder](https://github.com/harvester/seeder) to manage our in-house hardware provisioning need, but haven't prioritized bringing it to public usage yet.

**Comment by hwinkel** [comment]
I there any progress with BM management? we are a rancher (and maybe) Harvester user if it would expand into the BM Management
