### ISSUE TITLE
[BUG] VM created from windows-iso-image template can't start automatically, need the extra manual start effort  

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2172]
**Describe the bug**

When create a windows virtual machine from windows-iso-image template.
The virtual machine can't start automatically and stay in the `off` 

```
start virtual machine default/windows-template failed, persistentvolumeclaims "windows-template-cdrom-disk-rvk33" not found
```
![image](https://user-images.githubusercontent.com/29251855/164446279-949ffce1-c7f6-46c4-9b90-4c04a4b63d80.png)

User need to manual start the windows VM to make it running. 

**To Reproduce**
1. Create a windows iso image from file or upload via URL
  https://storage.googleapis.com/harvester/windows_server_2019_essentials.iso
2. Create a VM , select `windows-iso-image-base-version` template
3. Edit the appropriate CPU and memory
  ![image](https://user-images.githubusercontent.com/29251855/164449378-22ee09a9-6487-4893-95fe-304399035319.png)
4. Select windows iso image with type `cd-rom`
![image](https://user-images.githubusercontent.com/29251855/164449439-7d1a1895-2c7f-4af2-bc04-f4fc5feb7817.png)
5. Click the create button

**Expected behavior**

VM created from windows-iso-image template can start automatically without error 

**Support bundle**

[supportbundle_28479d0f-c787-4ec6-b759-673c63ce6c76_2022-04-21T11-38-33Z.zip](https://github.com/harvester/harvester/files/8530610/supportbundle_28479d0f-c787-4ec6-b759-673c63ce6c76_2022-04-21T11-38-33Z.zip)

**Environment:**
 - Harvester ISO version: `master-03ee6213-head` (04/18) 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node harvester on local kvm machine

**Additional context**
  ![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/bcc7793e-25bc-41f5-9966-c511a27c3084)
  ![image.png](https://images.zenhubusercontent.com/61519853321ea20d65443929/6ee9cf32-c4f9-4d62-9a57-74fde8844e9d)

**Comment by WuJun2016** [comment]
It's not a problem that happens 100% of the time.  It is not necessarily related to whether or not the window template is selected to create the vm.     Need  @tjjh89017  to help troubleshoot this issue.

**Comment by tjjh89017** [comment]
@WuJun2016 Could you help us to modify the code for starting VM on creation?
We might need to check the VM CR is created and send start request after that.
thanks a lot

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

UI change:
- Remove `Start virtual machine on creation`
- Set **Run Strategy** to `RerunOnFailure` by default in _Advanced Options_

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.2-rc2**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2172#issue-1210911515
