### ISSUE TITLE
[Question] VM image management for productive environment: best practices

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#2174]
What are best practices and recommendations for VM image management? (Assume several OS options and regular image updates with latest OS versions.) If we create new images for each new OS build, then there might be a huge number of images that become unmanageable. If we override an image with a new build, we might get unpredictable behavior on the downstream cluster level. Any guidance you could provide would be very much appreciated.

**Comment by guangbochen** [comment]
Please consider the following enhancement on the UI side:
- [ ] filtering images by labels https://github.com/harvester/harvester/issues/2319 - on the image page.
- [ ] when creating a guest k8s cluster, allowing users to search images by name and sort it in either ascending or descending.

**Comment by WuJun2016** [comment]
> Please consider the following enhancement on the UI side:
> 
> * [ ]  filtering images by labels [[FEATURE] Image filtering by labels #2319](https://github.com/harvester/harvester/issues/2319) - on the image page.
> * [ ]  when creating a guest k8s cluster, allowing users to search images by name and sort it in either ascending or descending.

duplicated ， The problem has been solved in the [issue](https://github.com/harvester/harvester/issues/2474)， so close this issue
