### ISSUE TITLE
[BUG] protobuf namespace conflict

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#2178]
**Describe the bug**
When compiling harvester using `scripts/build`, the binary `./bin/harvester` panics with the [protocol buffers namespace conflict](https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict). To get around this, the user needs to suppress this using an environment variable: `GOLANG_PROTOBUF_REGISTRATION_CONFLICT=warn ./bin/harvester --kubeconfig ~/etc/local.yaml  --namespace harvester-system  --hci-mode true`

This should be fixed instead of suppresed

**To Reproduce**
1. Check out harvester repo
2. run `./scripts/build`
3. run `./bin/harvester --kubeconfig $KUBECONFIG --namespace harvester-system  --hci-mode true`
4. there should be a go panic `panic: proto: message VersionResponse is already registered`

**Expected behavior**
The newly built harvester binary should run without panicing, and not have to require an error-suppression flag to run.

**Additional context**
Current master branch: b20a3b47fb06b649ea5762be021372a8a728411e

**Comment by guangbochen** [comment]
related to https://github.com/longhorn/longhorn/issues/3343, will be addressed after we bump the [dependency LH version](https://github.com/harvester/harvester/pull/2163) in the next release, thanks.

**Comment by bk201** [comment]
Confirm the service is running and no warning messages after [removing the workaround](https://github.com/harvester/harvester/pull/2373) ([commit](https://github.com/harvester/harvester/pull/2373/commits/9fa164402cdfd1b007cf2d65a932482bceac3dfa)).
