### ISSUE TITLE
More than one VMs could be created at one time

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#218]
More than one VMs could be created at one time somehow, refresh the page, one of them will no longer exist
![image](https://user-images.githubusercontent.com/57614736/98091656-aa9e7e80-1ec0-11eb-8d56-c5239073c78b.png)

**Comment by guangbochen** [comment]
can't be reproduced with the latest UI on 16/11, feel free to re-open it when encounters.

**Comment by WuJun2016** [comment]
May have solved the problem, but because there is no way to reproduce again, so there is no way to verify
