### ISSUE TITLE
[BUG]Harvester Network label polish

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2181]
**Describe the bug**

**To Reproduce**
1. Go to Network page
<img width="1670" alt="image (4)" src="https://user-images.githubusercontent.com/15041915/164970163-d0efe1c8-bee4-4598-b145-81c12bbfa47b.png">
2. Go to Dashaboard page
<img width="1649" alt="image (5)" src="https://user-images.githubusercontent.com/15041915/164970199-03a0df6c-9daf-4f4e-9192-e6ea22fb3ded.png">

**Expected behavior**

Harvester network should not use `k8s.cni.cncf.io.networkattachmentdefinitio` to display List/Detail.
We intend to replace `k8s.cni.cncf.io.networkattachmentdefinitio` with `harvesterhci.io.networkattachmentdefinition`

1. Page label should be `Network(s)`

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
https://github.com/rancher/dashboard/issues/4962

**Comment by TachunLin** [comment]
Verified **fixed** on `master-66e4f8f8-head` (04/26). Close this issue.

### Result
Network represent in the following page label set as `Network(s)`
  ![image](https://user-images.githubusercontent.com/29251855/165278737-79eaa3fd-bd26-444a-af2e-240e99233603.png)
  ![image](https://user-images.githubusercontent.com/29251855/165278899-212abe44-3ad9-4abd-88d3-ee2378e3e25d.png)
  ![image](https://user-images.githubusercontent.com/29251855/165278972-06ea1f44-8c51-46fa-85c0-98533dd2f450.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-66e4f8f8-head` (04/26)

### Verify Steps
1. Enable virtual network and create some VLAN network
2. Check the network label on Dashboard page
3. Check the network label on Network page
4. Check the network label on VM creation page
