### ISSUE TITLE
[BUG] Viewing harvester resources through the k8s container, the page crashes

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2184]
**Describe the bug**
In a multicluster, viewing harvester resources via the k8s container page, the page crashes

![截屏2022-04-25 上午11 51 47](https://user-images.githubusercontent.com/15041915/165024016-e28116f3-bb99-40d2-a6fc-3b0147e40655.png)

**To Reproduce**
1. Creating multiple clusters， Importing harvester clusters
1. click `Virtualization management`
1. go to harvester cluster
1. Change` harvester/harvesterhci.io.dashboard#vm` => `explorer` in the url
1. click `More Resources`
1. click `kubevirt.io

**Expected behavior**
1. Harvester CRD in Explorer should display correctly

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.7-head` (9bb8d56) with Harvester `master-14bbee2c-head`. 
Close this issue.

### Result
Verified on Single and Multiple nodes Harvester cluster

We can view the following Harvester resources in Rancher explorer 
* harvesterhci.io
  - Settings
  - Virtualmachineimages
  - VirtualmachineTemplates
  - VirtualMachineTemplateVersions
* kubevirt.io 
  - VirtualMachineInstances
  - VirtualMachines 
* network.harvesterhci.io
  - ClusterNetworks
  - LinkMonitors
* node.harvesterhci.io
  - ksmtuneds

* Can only create and edit harvester resource from YAML 


### Test Information
* Test Environment: one and two nodes harvester on local kvm machine
* Harvester version: master-1be9cb5e-head (1/23)
* Rancher version: v2.7-head (9bb8d56)

### Verify Steps
1. Prepare a single or multi nodes Harvester cluster
2. Import Harvester from Rancher 
3. Open Preference page
4. Enable extension developer features
5. Access Harvester from Rancher virtualization management
6. Open Support page
7. Open Access Embedded Rancher UI
8. Expand More Resources
9. Check can view harvester.io type resource can display correctly

### Additional Context 
We can also use the following URL to view harvester resources 
Single node:  `<Your Host>/dashboard/c/local/explorer#cluster-metrics`
Multi nodes:  `<Your Host>/dashboard/c/<Cluster ID>/explorer/harvesterhci.io.virtualmachinetemplateversion`
