### ISSUE TITLE
[BUG] Unable to import Harvester in Rancher UI, stuck in Waiting with message "Waiting for API to be available"

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2185]
**Describe the bug**

Can't import Harvester in Rancher v2.6.4, it always stuck in the `Waiting` status with message `Waiting for API to be available`
  ![image](https://user-images.githubusercontent.com/29251855/165015660-2cf698a2-a692-4bcf-99b9-43136f2f4631.png)

**To Reproduce**
1. Prepare an one node harvester 
2. Create an ubuntu focal image from file
3. Enable virtual network with `management-mgmt` 
4. Create a virtual network `vlan1` with id `1`
5. Access Rancher UI
6. Go to Global Settings → rke-metadata-config
7. Update the url to value 
  ```
  https://raw.githubusercontent.com/nikolaishields/kontainer-driver-metadata/april_release_rke2/data/data.json
  ```
8. Import Harvester from Rancher virtualization management page  

**Expected behavior**

Can't import Harvester in Rancher virtualization management correctly without stuck in `Waiting`

**Support bundle**

[supportbundle_303d7d91-fb29-40bf-9a47-f4c0401ed7ad_2022-04-25T05-59-57Z.zip](https://github.com/harvester/harvester/files/8551983/supportbundle_303d7d91-fb29-40bf-9a47-f4c0401ed7ad_2022-04-25T05-59-57Z.zip)

**Rancher log**
[issue_2185_rancher.log](https://github.com/harvester/harvester/files/8551999/issue_2185_rancher.log)

**Environment:**
 - Harvester ISO version: `master-0eab7caa-head` (04/24)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node Harvester on local kvm machine
 - Rancher version: v2.6.4

**Additional context**
If works on Harvester master release `master-03ee6213-head` (04/18)

**Comment by ibrokethecloud** [comment]
@TachunLin  I tried the same setup using current master `05b5da2` but could not re-produce the issue.

In the original support bundle the cattle-cluster-agent is deployed, and redeployed by rancher after the import processes as seen below:

```
2022-04-25T03:21:06.942567347Z INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.53.0.10 options ndots:5
2022-04-25T03:21:06.957607278Z INFO: https://192.168.122.224//ping is accessible
2022-04-25T03:21:06.997739275Z INFO: Value from https://192.168.122.224//v3/settings/cacerts is an x509 certificate
2022-04-25T03:21:07.137891801Z time="2022-04-25T03:21:07Z" level=info msg="Listening on /tmp/log.sock"
2022-04-25T03:21:07.137917818Z time="2022-04-25T03:21:07Z" level=info msg="Rancher agent version v2.6.4 is starting"
2022-04-25T03:21:07.148690447Z time="2022-04-25T03:21:07Z" level=info msg="Connecting to wss://192.168.122.224/v3/connect/register with token starting with xccmzgsmp28mjrzwgsd5c82qdd8"
2022-04-25T03:21:07.148709335Z time="2022-04-25T03:21:07Z" level=info msg="Connecting to proxy" url="wss://192.168.122.224/v3/connect/register"
2022-04-25T03:21:07.289404177Z time="2022-04-25T03:21:07Z" level=info msg="Starting /v1, Kind=Service controller"
```

The only difference seems to be the websocket error in the rancher container logs:

```2022/04/25 03:21:51 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:21:51 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:25:48 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:25:48 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:26:16 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:26:16 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:48:51 [ERROR] Error during subscribe websocket: close sent
2022/04/25 03:48:51 [ERROR] Error during subscribe websocket: close sent
2022/04/25 05:51:16 [ERROR] Error during subscribe websocket: close sent
2022/04/25 05:51:16 [ERROR] Error during subscribe websocket: close sent
```
One important thing to notice is I see no `VirtualMachine` object in the support bundle generated. Can we confirm that the rancher VM was actually running on the same harvester cluster?

**Comment by TachunLin** [comment]
@ibrokethecloud, 
The Rancher and Harvester built on two separate VMs under the same virtual network (e.g 192.168.122.0/24)
Thus the rancher VM did not run on the same harvester cluster. The reason for no `VirtualMachine` object on the support bundle I think it because since Harvester is not yet imported to Harvester, so we can't proceed to provision the guest cluster VM on Harvester node.

**Comment by TachunLin** [comment]
Re-validate the issue did not exists on latest master-head `master-66e4f8f8-head` with Rancher v2.6.4. Close this issue.

### Result
We can import Harvester in Rancher `with` and `without` updating the RKE KDM release URL. 
  ![image](https://user-images.githubusercontent.com/29251855/165500640-395c6e4f-5010-461f-90ad-58e1d59f078f.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-66e4f8f8-head
* Rancher version: v2.6.4
