### ISSUE TITLE
[FEATURE] Add websocket disconnect notification

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2186]
**Is your feature request related to a problem? Please describe.**

Currently, when webSocket disconnects, the user only sees the webSocket disconnection message in the Console, which is not user-friendly. 
We want to see the WebSocket message at the top of the page when webSocket disconnects.
When the WebSocket connection succeeds, the message is automatically hidden

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WuJun2016** [comment]
https://github.com/harvester/harvester/issues/1731#issuecomment-1107794611

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/177529443-a9478e33-a955-4b48-8485-ab6eabbf3824.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-08af3d7c-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
3. Login to Dashboard via Node IP
4. Navigate to _Advanced/Settings_ and update **ui-index** to `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html` and force refresh to make it applied.
5. restart the Node which holding the IP
6. Notification of websocket disconnected should appeared
