### ISSUE TITLE
[BUG] No IP address displayed for a VM

### ISSUE THREAD

**Issue by poldiderjungdrache** [harvester/harvester#2188]
**Describe the bug**

I created a ubuntu VM. However no IP address is shown on the UI although IP is assigned:
<img width="1504" alt="2022-04-25_09-17-48" src="https://user-images.githubusercontent.com/59320185/165039246-8936c177-79ad-48e4-bc0c-ff478a8d0885.png">

In console ip a shows the IP as 192.168.30.139:
<img width="910" alt="2022-04-25_09-20-06" src="https://user-images.githubusercontent.com/59320185/165039623-ed1e5bfc-a7ff-4a37-8034-e09b5ec2df48.png">

Below is the network config for the VM:
<img width="1137" alt="2022-04-25_09-21-37" src="https://user-images.githubusercontent.com/59320185/165039799-fb57492f-c018-4eed-9e2e-df4d66ff2f0d.png">

**To Reproduce**
not sure how to reproduce

**Expected behavior**

VM shows assigned IP.

**Support bundle**

[supportbundle_17ecbbe0-3abd-43f0-9267-4cbb33e6282d_2022-04-25T07-22-57Z.zip](https://github.com/harvester/harvester/files/8552459/supportbundle_17ecbbe0-3abd-43f0-9267-4cbb33e6282d_2022-04-25T07-22-57Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal (HP ProDesk 400 G6)

**Additional context**

**Comment by WuJun2016** [comment]
What are the values of ui-source and ui-index in settings?

<img width="1671" alt="image" src="https://user-images.githubusercontent.com/24985926/165062222-cb66a245-f5b7-4195-b258-95c68e696ca6.png">

**Comment by poldiderjungdrache** [comment]
That is the same for my install:
<img width="890" alt="2022-04-25_16-44-34" src="https://user-images.githubusercontent.com/59320185/165113387-fa32e946-9394-49bb-9dc0-262eb2fdcb83.png">

**Comment by w13915984028** [comment]
@poldiderjungdrache Could you please check  https://docs.harvesterhci.io/v1.0/vm/create-vm/#installing-the-qemu-guest-agent , thanks.

**Comment by poldiderjungdrache** [comment]
Sorry I remove these VMs already. However I have just deployed some VMs via Rancher and with those the IP shows up and qemu-guest-agent is set correctly in cloud.init.
I have also updated to 1.0.2 in the meantime. Looks like the issue is fixed.

Simon

**Comment by tjjh89017** [comment]
I will close this ticket.
If you have further issues, feel free to reopen it.
thanks a lot
