### ISSUE TITLE
[BUG] CD-ROM device should not need size

### ISSUE THREAD

**Issue by poldiderjungdrache** [harvester/harvester#2189]
**Describe the bug**

There is a bit of wired UI behaviour with CD-ROM devices for VMs.
When creating a VM and adding a device of type CD-ROM, size remains as mandatory field although the ISO image should define the size:
<img width="1851" alt="2022-04-25_09-29-05" src="https://user-images.githubusercontent.com/59320185/165041153-c4ee0642-052e-4bf6-8dc8-38ac6d88060d.png">

**To Reproduce**
1. Create VM
2. fill basic data
3. Go to Volumes tab
4. Select type CD-ROM and select ISO image, size field remains active and is mandatory

**Expected behavior**

When selecting type CD-ROM size should be not required as it is denied by the image assigned. 

**Support bundle**

[supportbundle_17ecbbe0-3abd-43f0-9267-4cbb33e6282d_2022-04-25T07-22-57Z.zip](https://github.com/harvester/harvester/files/8552550/supportbundle_17ecbbe0-3abd-43f0-9267-4cbb33e6282d_2022-04-25T07-22-57Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal (HP ProDesk 400 G6)

**Additional context**

**Comment by poldiderjungdrache** [comment]
Funny thing is if you under provision the CD-ROM (like lets say set it to 1GB although the ISO is larger than 1GB).
The VM does not boot off the install ISO and dumbs me in the EFI Shell:

<img width="1859" alt="2022-04-25_16-50-33" src="https://user-images.githubusercontent.com/59320185/165114833-ecd4bdea-b463-44fa-bfdb-9311797fdd8e.png">

**Comment by w13915984028** [comment]
@FrankYang0529 your idea? thanks.

**Comment by simonflood** [comment]
I bumped into this one today in that I tried booting a VM from a newly uploaded ISO and my first thought it was a corrupt download. After comparing the MD5 checksum of the original file (itself checked against source) with corresponding backing image in Harvester I knew the upload was sound.

The ISO is 11,231,297,536 bytes in size which Harvester lists as 10 GB but it's slightly over which caused the boot to trip. Stopping the VM and increasing the size of the CD-ROM device(!) to 11G allowed the VM to boot from the ISO.

Here's some screenshots showing the failed boot and change of CD-ROM device size(!)

![Screenshot from 2023-08-10 17-47-28](https://github.com/harvester/harvester/assets/8300801/9339d45f-40e7-443c-829f-09c3bec72769)
![Screenshot from 2023-08-10 17-56-48](https://github.com/harvester/harvester/assets/8300801/c04fa637-c501-40b3-8c17-5c8204b9eaf6)

Time to remove the CD-ROM device size or at least automatically set it to match the corresponding ISO (although that would cause a problem if you subsequently change the ISO to a different one which is smaller as it seems you can't reduce the size of the CD-ROM device as I found out in my playing).

**Comment by tserong** [comment]
I'm looking at this as part of https://github.com/harvester/harvester/issues/4905

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Follow reproduce step in https://github.com/harvester/harvester/issues/2189#issuecomment-2128343086
3. Size of CD-ROM should round up to GB by ISO image size.

**Comment by lanfon72** [comment]
@bk201 do we need to backport this?
