### ISSUE TITLE
VMs could not be created successfully, with a pending state all the time

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#219]
VMs could not be created successfully, with a pending state all the time, no explicit errors can be found on the page.

![image](https://user-images.githubusercontent.com/57614736/98092527-bcccec80-1ec1-11eb-950d-a7cc362196e6.png)

![image](https://user-images.githubusercontent.com/57614736/98092940-3bc22500-1ec2-11eb-96af-5327a578d2c5.png)

**Comment by guangbochen** [comment]
This is an environmental issue related to the storage provisioner of PV and PVCs.

Close and please feel free to open an issue with a more specific storage error.
