### ISSUE TITLE
[Question] Hardvester on vmware and meraki VIP ip

### ISSUE THREAD

**Issue by it-pappa** [harvester/harvester#2193]
Hi,

I used to have harvester nested on my vCenter server and worked fine when i had unifi network with subnetting etc.
Now i have a meraki go network, new vcenter etc (6,7) and harvester cant get an vip DHCP? 

I try to set static but still doesnt work. Any idea? 

Network config: 
all is in one network and no vlan same on vms in vcenter
Harvester has DHCP and can get an IP but vip dhcp cant.

**Comment by tjjh89017** [comment]
Could you check the vSwitch config?
MAC Address Changes, Forged Transmits, Promiscuous Mode Operation
These three option need to be enabled.
