### ISSUE TITLE
[BUG] Some text is invisible or illegible at https://docs.harvesterhci.io/v1.0/reference/api/ dependent on if the website is in light mode or dark mode

### ISSUE THREAD

**Issue by jhhudso** [harvester/harvester#2200]
**Describe the bug**
Some text is invisible or illegible at https://docs.harvesterhci.io/v1.0/reference/api/ dependent on if the website is in light mode or dark mode.

**To Reproduce**
1. Go to https://docs.harvesterhci.io/v1.0/reference/api/ and utilize the API browser while clicking the button at the top of the website to enable dark mode or light mode and compare results.
2. An example of where the text is invisible would be enable dark mode and look at the API calls. The URLs to be used with GET or POST are a dark gray color on a dark grayish blue, green, orange or red background making them invisible or illegible depending on the background used.
3. An example of where the text is illegible would be enable light mode, click one of the API calls, fill out the required fields and click Execute. The resulting curl based example uses a low intensity green on a white background for most of the arguments passed to curl. In dark mode the same text is legible.

**Expected behavior**
Be able to read all text with good contrast and color choice in both light and dark mode.

Invisible text with dark mode
![image (1)](https://user-images.githubusercontent.com/426967/165604525-b05e68ac-2909-41f6-9398-c46b9437b640.png)
Same text but legible with light mode
![image (2)](https://user-images.githubusercontent.com/426967/165604685-1f7b7064-fcc7-4cc1-a0d9-4b3dd2a656ac.png)

Illegible text with light mode
![image (4)](https://user-images.githubusercontent.com/426967/165604803-01253853-24fe-4034-8a24-446747f9ac22.png)
Same text but legible with dark mode
![image (3)](https://user-images.githubusercontent.com/426967/165604764-08e9149d-31aa-430e-a7b1-e0a77aa54f44.png)

**Comment by w13915984028** [comment]
@WuJun2016 your idea? thanks.

**Comment by guangbochen** [comment]
We are migrating our docs to Docusaurus. Let's plan to fix it in the new platform. cc @vickyhella

**Comment by guangbochen** [comment]
Let's track this issue along with https://github.com/harvester/harvester/issues/3042 since we need to add the API docs back to the new framework.
