### ISSUE TITLE
[BUG] image clone unusable

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#2202]
## Describe the bug
can not clone a image

## To Reproduce
1. web ui, select an image, choose clone
2. jumps to image create page
3. change namespace/name
4. we have to re-upload the same image file again. 

this is not `clone` but a pure `create new` 

## Expected behavior
clone the old image without url-download/local-upload

## Environment:
 - Harvester ISO version:  v1.0.1

**Comment by futuretea** [comment]
Currently (1.0.3),  `Clone` only means `clone yaml` in Harvester
