### ISSUE TITLE
[Question]Manage node role for HA cluster

### ISSUE THREAD

**Issue by Abbos92** [harvester/harvester#2203]
I have a 3 nodes for Harvester cluster, version is latest 1.0.1 . After install cluster with 3 nodes all of nodes was set master role, I had testing for fail tolerance, after reboot first one I was rejoined like worker node, If I power off another master node cluster isn't available.
NAME              STATUS   ROLES                                         AGE    VERSION
hd-harvester-01   Ready    <none>                                   142m   v1.21.11+rke2r1
hd-harvester-02   Ready    control-plane,etcd,master   14h      v1.21.11+rke2r1
hd-harvester-04   Ready    control-plane,etcd,master   14h      v1.21.11+rke2r1

Can I change role in node manually, or how can I manage fail tolerance for getting HA cluster ?
In installation process it will not be able to change join method for managing ROLE for node, I want cluster should be able when other 2 nodes will fail and one will still alive

**Comment by w13915984028** [comment]
@Abbos92 Any updates after this issue, how did you recover the cluster, and did you test more?

(1) After you reboot one node, then it has 2-master and 1-worker. Is it reproducable? A support-bundle is helpful.
https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#generate-a-support-bundle.

(2)After you power off another master, I guess you mean the cluster management IP (VIP) was not available. Did you try to SSH into the node IP ?  `kubectl get pods -A ` `kubectl get service -A ` ... will reveal more.

(3) For each node, how about the CPU/memory/storage resources ?

thanks.
