### ISSUE TITLE
[FEATURE] build-iso: migrate luet-makeiso to `elemental build-iso`

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2204]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher-sandbox/cOS-toolkit/issues/1217

cOS team build the luet-makeiso feature into elemental command. We should migrate to get further support.

https://github.com/harvester/harvester-installer/blob/1c1b8c4dfb7aa11fb7e912e1f3f5ca9414259e0f/Dockerfile.dapper#L2
https://github.com/harvester/harvester-installer/blob/1c1b8c4dfb7aa11fb7e912e1f3f5ca9414259e0f/scripts/package-harvester-os#L67

https://github.com/harvester/harvester/blob/e2985453c65193b407d47d53c3c96a249e2cf474/Dockerfile.dapper#L2

**Comment by bk201** [comment]
Move to v1.2.0, luet-makeiso still works and this is only for the building process.

**Comment by bk201** [comment]
Try to bump elemental to build ISO, but seems can't boot the ISO due to the change that only supports UEFI.

**Comment by bk201** [comment]
Add `require/release-note`. Dropping legacy support needs a heads-up in the release note.

**Comment by irishgordo** [comment]
@bk201 for validation should I also check the ability to upgrade to an iso built by `harvester-installer`?

I validated the artifacts were built:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester-installer/dist on master✔
╰─± ls -alh artifacts 
total 6.6G
drwxr-xr-x 2 mike mike 4.0K May 23 12:43 .
drwxr-xr-x 3 mike mike 4.0K May 23 12:41 ..
-rw-r--r-- 1 mike mike  60M Jul  1  2022 harvester-ea2c3e7-dirty-initrd-amd64
-rw-r--r-- 1 mike mike 735M Jul  1  2022 harvester-ea2c3e7-dirty-rootfs-amd64.squashfs
-rw-r--r-- 1 mike mike 8.7M Jun 17  2022 harvester-ea2c3e7-dirty-vmlinuz-amd64
-rw-r--r-- 1 mike mike 5.1G May 23 12:43 harvester-master-amd64.iso
-rw-r--r-- 1 mike mike  647 May 23 12:43 harvester-master-amd64.sha512
-rw-r--r-- 1 mike mike  86M May 23 12:41 harvester-master-initrd-amd64
-rw-r--r-- 1 mike mike 594M May 23 12:43 harvester-master-rootfs-amd64.squashfs
-rw-r--r-- 1 mike mike  11M May  3 02:09 harvester-master-vmlinuz-amd64
-rw-r--r-- 1 mike mike 1.8K May 23 12:43 image-lists.tar.gz
```
![Screenshot from 2023-05-23 14-35-00](https://github.com/harvester/harvester/assets/5370752/05b8216e-5686-4626-b2c6-f2776c2255a2)
![Screenshot from 2023-05-23 12-36-02](https://github.com/harvester/harvester/assets/5370752/84bff8f4-1554-4d4b-b5e2-af7e0e061f39)

And I was able to use the amd64.iso in an install on qemu/kvm with the configuration of:
[a sample remote config with uefi](https://raw.githubusercontent.com/irishgordo/scratch-dump/main/test-vm.yaml)

![Screenshot from 2023-05-23 14-52-44](https://github.com/harvester/harvester/assets/5370752/5085cf2a-6042-4745-be34-56d2598dfa0a)

**Comment by bk201** [comment]
>  should I also check the ability to upgrade to an iso built by harvester-installer?

@irishgordo, that will be nice; feel free to include the test path in any upgrade testing. `v1.2.0-rc1` contains this change. Thanks!

**Comment by masteryyh** [comment]
@irishgordo It seems I forgot to record where test steps located ;) it's in https://github.com/harvester/harvester-installer/pull/486#issue-1681042323

**Comment by irishgordo** [comment]
@masteryyh thank you for sharing the test steps plan :smile: 

**Validation Failure**

When attempting to build via [scripts/build-iso](https://github.com/harvester/harvester/blob/master/scripts/build-iso) it seems to fail with:
```
Successfully copied 560kB to /tmp/tmp.n15uKpYA1T/rancher-charts.yaml
1106c11980c00450cf90c01bb1c8b7daa93d63f68a88bcdbcdfcacc364fe59a3
Error: open /tmp/tmp.n15uKpYA1T/rancher-charts.yaml: no such file or directory
```
But that file does indeed exist there:
```
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester on master✔
╰─± ls -alh /tmp/tmp.n15uKpYA1T/rancher-charts.yaml
-rwxr-xr-x 1 mike mike 546K Apr 24 08:51 /tmp/tmp.n15uKpYA1T/rancher-charts.yaml
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester on master✔
╰─± file /tmp/tmp.n15uKpYA1T/rancher-charts.yaml 
/tmp/tmp.n15uKpYA1T/rancher-charts.yaml: ASCII text
╭─mike at suse-workstation-team-harvester in ~/Projects/harvester on master✔
╰─± head -n 15 /tmp/tmp.n15uKpYA1T/rancher-charts.yaml 
apiVersion: v1
entries:
  epinio:
  - annotations:
      artifacthub.io/license: Apache-2.0
      catalog.cattle.io/auto-install: epinio-crd=match
      catalog.cattle.io/certified: rancher
      catalog.cattle.io/display-name: Epinio
      catalog.cattle.io/experimental: "true"
      catalog.cattle.io/kube-version: '>= 1.20.0-0 < 1.26.0-0'
      catalog.cattle.io/namespace: cattle-epinio-system
      catalog.cattle.io/permits-os: linux,windows
      catalog.cattle.io/rancher-version: '>= 2.7.0-0 < 2.8.0-0'
      catalog.cattle.io/release-name: epinio
      catalog.cattle.io/type: app
```

Using the last commit on master-head of [2d5a3a9aca32574a54e8be8baa44b13bea998ce2](https://github.com/harvester/harvester/commit/2d5a3a9aca32574a54e8be8baa44b13bea998ce2)

**Comment by irishgordo** [comment]
@masteryyh 

So far what passes is:

1. Fresh install with iso built from `harvester-installer` 's `make`:
- BIOS based VM
- UEFI based VM

2. Upgrade from v1.1.2 -> iso built from `harvester-installer`'s `make`

But the [scripts/build-iso](https://github.com/harvester/harvester/blob/master/scripts/build-iso) inside `harvester` that does download the `harvester-installer` repository, that script fails to build any artifacts so I have not been able to validate that.

![Screenshot from 2023-05-25 13-09-58](https://github.com/harvester/harvester/assets/5370752/9b1fa76a-f96f-4504-8ea1-6bd2b5364a13)

**Comment by irishgordo** [comment]
Was able to validate (w/ Version: master-29bcdcc3-head) harvester repo's `make build iso` - the artifacts work great for both fresh install and upgrade :smile: :+1: 
So I will go ahead and close this out.
