### ISSUE TITLE
[BUG]failed to create harvester server

### ISSUE THREAD

**Issue by iamwlb** [harvester/harvester#2206]
**Describe the bug**

> kubectl -n harvester-system get po                             uos: Fri Apr 29 03:39:00 2022

NAME                                       READY   STATUS             RESTARTS   AGE
harvester-798866ff75-vbwlv                 0/1     CrashLoopBackOff   6    	 14m
harvester-load-balancer-59bf75f489-9pcrf   1/1     Running            0    	 14m
harvester-webhook-54ff6b4f57-pbflq         1/1     Running            0    	 14m
kube-vip-cloud-provider-0                  1/1     Running            0    	 14m
virt-api-79448ff685-7zv7n                  1/1     Running            0    	 13m
virt-api-79448ff685-qdzrk                  1/1     Running            0    	 13m
virt-controller-6c7f5d4fbf-4tcgk           1/1     Running            0          13m
virt-controller-6c7f5d4fbf-jq5bj           1/1     Running            0          13m
virt-handler-66whv                         1/1     Running            0          13m
virt-operator-78b84587c9-dp4xp             1/1     Running            0    	 14m

> kubectl -n harvester-system logs harvester-798866ff75-vbwlv
WARNING: proto: message VersionResponse is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

WARNING: proto: file "rpc.proto" is already registered
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

WARNING: proto: file "rpc.proto" has a name conflict over VersionResponse
See https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

time="2022-04-28T19:30:41Z" level=info msg="Starting controller"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD KeyPair"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Upgrade"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Version"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD VirtualMachineImage"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD VirtualMachineTemplate"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Setting"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD APIService"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Setting"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD User"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Group"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD GroupMember"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD Token"
time="2022-04-28T19:30:41Z" level=info msg="Do not update the existing CRD NodeDriver"
time="2022-04-28T19:30:41Z" level=fatal msg="failed to create harvester server: failed inspecting type v1beta1.VirtualMachineTemplateVersion, field spec: failed inspecting type v1beta1.VirtualMachineTemplateVersionSpec, field vm: failed inspecting type v1beta1.VirtualMachineSourceSpec, field spec: failed inspecting type v1.VirtualMachineSpec, field template: failed inspecting type v1.VirtualMachineInstanceTemplateSpec, field spec: failed inspecting type v1.VirtualMachineInstanceSpec, field domain: failed inspecting type v1.DomainSpec, field devices: failed inspecting type v1.Devices, field disks: failed inspecting type v1.Disk, field bootOrder: unknown type kind uint"

**To Reproduce**
helm install harvester harvester \
--namespace harvester-system \
--set longhorn.enabled=true,minio.persistence.storageClass=longhorn,service.harvester.type=NodePort

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by iamwlb** [comment]
> helm install harvester harvester --namespace harvester-system --set service.harvester.type=NodePort
the same problems

**Comment by iamwlb** [comment]
![截屏2022-05-05 23 43 19](https://user-images.githubusercontent.com/7825358/166961544-a7be37c1-c94f-401e-95c6-631d7f29785c.png)
the bug still exist.

**Comment by w13915984028** [comment]
Harvester needs to be installed via Harvester ISO manually or via PXE, many underlayer works are needed and done at installation stage.  Directly install Harvester via Helm is not supported.

Please refer: https://docs.harvesterhci.io/v1.0/install/iso-install/

**Comment by iamwlb** [comment]
@w13915984028 
thanks for your answer.
havester support many kinds install way.
for example:
1. iso
2. kubernetes
3. rancher

**Comment by w13915984028** [comment]
@iamwlb Please refer https://docs.harvesterhci.io/v1.0/install/iso-install/  and related parts.

Directly use HELM to install Harvester into a existing kubernetes is not supported.

Please take a look of the ISO-install guide, it is not only the deployment of Harvester into kubernetes, but also a lot of work about OS, about related base components.

**Comment by votdev** [comment]
Closing because Harvester can not be installed via Helm only. See [here](https://github.com/harvester/harvester/issues/2206#issuecomment-1129767159) for a detailed explanation.

Harvester can be installed via:
- [ISO](https://docs.harvesterhci.io/v1.3/install/index)
- [USB](https://docs.harvesterhci.io/v1.3/install/usb-install)
- [PXE](https://docs.harvesterhci.io/v1.3/install/pxe-boot-install)
