### ISSUE TITLE
[BUG] The browser will crash if the page is opened for a long time

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2207]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
@WuJun2016 is this still an issue that can be spotted in the latest version? if not we may close and reopen it when encounter it again, thanks.
