### ISSUE TITLE
Cannot delete vm

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#221]
# step
1. create vm
2. Delete the associated volume first
3. delete vm
![image](https://user-images.githubusercontent.com/24985926/98193393-09fb9d80-1f58-11eb-9d75-9444eb25da5b.png)

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/244

**Comment by DoNotSayYes** [comment]
Now deleting the mounted volumes are not allowed
