### ISSUE TITLE
[FEATURE] Enhance Harvester doc 'monitoring'

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2211]
**Is your feature request related to a problem? Please describe.**

Harvester v1.0.1 has enhancement in 'monitoring', the related method can also be used in v1.0.0 manually, but it is not clearly documented. Users need such guide to adjust the resource setting in their deployed Harvester cluster.

**Describe the solution you'd like**

Add description of usage in earlier versions.

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
![2211-looks-good](https://user-images.githubusercontent.com/5370752/168136581-719a98d7-e001-4e8d-9f68-9b718729aa20.png)

This renders correctly and looks good locally!
I'll go ahead and close this out :smile:

**Comment by irishgordo** [comment]
![2211-looks-good](https://user-images.githubusercontent.com/5370752/168136581-719a98d7-e001-4e8d-9f68-9b718729aa20.png)

This renders correctly and looks good locally!
I'll go ahead and close this out :smile:
