### ISSUE TITLE
[BUG] Can't select image after modifying template

### ISSUE THREAD

**Issue by depasseg** [harvester/harvester#2212]
**Describe the bug**

**To Reproduce**
1. Go to the built-in template for deploying linux from ISO.
2. Adjust rootdisk volume size to 20 (from 10).
3. Save template.
4. Open template and notice that the cdrom is no longer a disk image
5. Deploy from that version of the template and notice there isn't a way to choose the ISO image. 

**Expected behavior**
It is expected that changing the template and saving a new version will keep all other template settings (including the cdrom disk image option)

**Support bundle**
[supportbundle_30b7dab9-6e74-44e7-aa6e-f87361d90cf6_2022-04-29T17-34-11Z.zip](https://github.com/harvester/harvester/files/8592643/supportbundle_30b7dab9-6e74-44e7-aa6e-f87361d90cf6_2022-04-29T17-34-11Z.zip)

**Environment:**
 - Harvester ISO version:  1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 Intel NUCs and one VM on ESX

**Additional context**
Here is version 3 of the template after changing the root disk size.  Notice there isn't a place to choose the ISO image.
![image](https://user-images.githubusercontent.com/3201827/165994269-9e5f4121-ba7e-42fb-857e-fab8b0944180.png)

Here is the original version 1 of the template:
![image](https://user-images.githubusercontent.com/3201827/165994446-868a8709-af37-45ff-b1fc-476ebfcf55d3.png)

**Comment by noahgildersleeve** [comment]
Tested in master-0f590757-head.
## Verification Steps

1. Add new version of the ISO template from the templates page
![Screenshot_20220712_104904](https://user-images.githubusercontent.com/83787952/178559388-42e4f05a-390e-405e-8180-e4bfe9e6a944.png)
2. Change size of root volume to 20GB
![Screenshot_20220712_104920](https://user-images.githubusercontent.com/83787952/178559415-23c1fd21-4bd6-4be1-a7f3-0c53bf087f94.png)
![Screenshot_20220712_104904](https://user-images.githubusercontent.com/83787952/178559418-6b3f07f1-249a-4a7a-8207-aecd647aa2a4.png)
3. Save new version
4. Create new VM with new version of template.
5. Validate that VM starts
