### ISSUE TITLE
[Question] Access to the API

### ISSUE THREAD

**Issue by LukasAfonso** [harvester/harvester#2214]
Hello, I would like to develop an application using the harvester API, however, I can't figure out how to connect to the API, I keep getting 401 Unauthorized. I understand that I either need a token or pass my credentials, but how?
If possible this could be included in the API reference page on the main site to help others that are starting with this API.
Thanks!

**Comment by WuJun2016** [comment]
request `v3-public/localProviders/local?action=login`，  This will give you the cookies you need.
