### ISSUE TITLE
[Question] How to configure harvester-mgmt networking with VLAN 

### ISSUE THREAD

**Issue by koyasuri** [harvester/harvester#2215]
How to configure harvester-mgmt networking with VLAN ?
Currently existing Physical nics is trunked  with Multiple VLANS and i don't see option at harvester end to enable VLAN tagging for Management interface.
Can some one guide me please ?

**Comment by w13915984028** [comment]
@koyasuri 
As of Harvester v1.0.2,  Harvester does not support configure management network with VLAN yet.

It is a feature under developing, will be released this year.

**Comment by rodrigo14miguel** [comment]
I have a similar setup (with only one NIC) and what I did was configure my VLAN trunk with a native VLAN on the upstream switch so the management network wont need VLAN ID taging. You can then use the same management NIC for the VLAN network after finishing the installation.
@koyasuri  Hope it helps with your setup.

**Comment by w13915984028** [comment]
@koyasuri Was this issue solved?

FYI: Please refer below document, even though it is not explicitly noted, the VLAN network can use haverster-mgmt NIC as the default uplink, thus the management network and VLAN network share the same NIC, meanwhile, you need to set your SWITCH to accept all of them. Thanks.

https://docs.harvesterhci.io/v1.0/networking/harvester-network/#enabling-default-vlan-network

**Comment by kfehrenbach** [comment]
Hi,
How is this solved now? The documentation is not really there...
Thanks!

**Comment by ibrokethecloud** [comment]
Step 6 in the install guide: https://docs.harvesterhci.io/v1.3/install/index shows an option to define vlanid with management interface.
