### ISSUE TITLE
[FEATURE] A document to list all open ports on Harvester nodes

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2216]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

We need a document to list all open ports on Harvester nodes.

**Describe alternatives you've considered**

**Additional context**

- [RKE2 ports can be found here](https://docs.rke2.io/install/requirements/#networking). Just be aware not every items are required.
- Rancher host ports and ingress ports. We use the port to join new nodes.
- GUI ports

**Comment by guangbochen** [comment]
close as the doc is added via https://docs.harvesterhci.io/v1.0/install/requirements.

**Comment by Martin-Weiss** [comment]
I believe this is wrong: „Typically, all outbound traffic will be allowed.“ users / customers do not have a change to open all outgoing traffic so this needs to be specified, too. (Is DNS and NTP sufficient?)

**Comment by yaocw2020** [comment]
> I believe this is wrong: „Typically, all outbound traffic will be allowed.“ users / customers do not have a change to open all outgoing traffic so this needs to be specified, too. (Is DNS and NTP sufficient?)

@Martin-Weiss For example, if a new TCP connection from one node to another happens, the OS will select a random port as the source port, which is the reason why said: "Typically, all outbound traffic will be allowed".
