### ISSUE TITLE
Unable to create VMs if user data is populated

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#222]
**Steps to reproduce:**

Create a VM, along with user data
```
#cloud-config
password: abcdefgh
chpasswd: { expire: False }
```

**Result：**
The VM keeps in the pending state all the time, however, VMs can be created without the user data 
![image](https://user-images.githubusercontent.com/57614736/98209372-c1ed7280-1f79-11eb-8d6f-794107153477.png)

**Comment by guangbochen** [comment]
can't reproduce with the latest version on 16/11.
