### ISSUE TITLE
[BUG] Cannot delete user created VM template

### ISSUE THREAD

**Issue by easmithdev** [harvester/harvester#2223]
**Describe the bug**
I created a VM template, but could not delete the template afterwards.

**To Reproduce**
1. Within Harvester UI, go to Advanced
2. Click templates
3. Click create
4. Define parameters, and save
5. Select template, and then click delete. 

**Expected behavior**
I should be able to delete a template I created. 

**Support bundle**
[supportbundle_973354bc-43fa-4848-af0a-37e6f9489876_2022-05-05T12-26-15Z.zip](https://github.com/harvester/harvester/files/8631181/supportbundle_973354bc-43fa-4848-af0a-37e6f9489876_2022-05-05T12-26-15Z.zip)

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure: Baremetal

**Comment by WuJun2016** [comment]
Do you delete the entire template or the default version of the template?
The default template version cannot be deleted directly.

**Comment by easmithdev** [comment]
The template I created does indeed have the "default" flag, and I cannot
remove the "default" flag from that template. Why is this? I don't want the
template to exist anymore. So, I should be able to remove the "default"
flag, and delete it. This is not possible.

**Comment by WuJun2016** [comment]
case 1:
If there is only one version in the test template, you can only delete this version by deleting the template.
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/24985926/167089664-82ef1fc8-dc23-4f32-9b28-e5ccdc1add59.png">

case 2:
If there are multiple versions under the template and the one you want to delete is the default version, then you can set the other versions as the default version and then delete the previous version。
<img width="1450" alt="image" src="https://user-images.githubusercontent.com/24985926/167089798-556f7449-7012-42bc-bdfe-bff821430d3f.png">
