### ISSUE TITLE
[BUG] Error messages are trimmed and not fully displayed in harvester-installer

### ISSUE THREAD

**Issue by joshmeranda** [harvester/harvester#2224]
**Describe the bug**
Long harvester installer errors do not wrap lines and are not fully displayed to the user.

![clipped_harvester_install_error_msg](https://user-images.githubusercontent.com/43455015/166971047-f727d9cb-6113-4f1e-9451-adf0101f1160.png)

In this case the full error message should be `unable to receive an offer: got an error while the discovery request: no matching response packet received`

**To Reproduce**
1. Setup network where DHCP will not work when setting up the VI (ex DISCOVER packets sent over unicast seem to be ignored or "unreceivable")
2. Attempt to configure VIP using DHCP

**Expected behavior**
The full error message should be displayed and line wrapped.

**Environment:**
 - Harvester ISO version:
   - Harvester v1.0.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
   - Harvester deployed on virtualbox VM on internal network using pfsense to provide routing to external WAN and DHCP

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/172823840-ebc957ed-83b1-482e-8403-622555b97760.png)
