### ISSUE TITLE
[BUG] Terraformer import vm failed

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2225]
### Describe the bug
Unable to import vm resources with following error:
![image](https://user-images.githubusercontent.com/5169694/166973918-f666b872-1b0a-4e07-a55a-14b550c71884.png)

### To Reproduce
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create the VM
4. download harvester's terraformer v1.0.0 from https://github.com/harvester/terraformer/releases
5. execute `terraformer import harvester -r virtualmachine`

### Expected behavior
VM's terraform files should be generated

## Environment:
 - Harvester ISO version: **v.1.0.2-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes** and **qemu/KVM single node**

**Comment by futuretea** [comment]
Test Plan:
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create the VM
4. Use the master head docker image for testing: https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing
5. download  terraformer v1.0.1-harvester
6. execute terraformer import harvester -r virtualmachine

**Comment by lanfon72** [comment]
@futuretea I can't do `terraform init` on generated resource in the docker container:
![image](https://user-images.githubusercontent.com/5169694/167593290-36eb4898-95c3-49ee-8b54-4ec923d265e3.png)

**Comment by futuretea** [comment]
@lanfon72 refer to  https://github.com/harvester/harvester/issues/943#issuecomment-886431707

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/167613667-7bfa369c-21f1-4d8d-941d-df842dd51d42.png)


Test Information
----
* Environment: **Bare metal DL360 3 nodes**
* Harvester Version: **v1.0.2-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow the **Steps to reproduce** in https://github.com/harvester/harvester/issues/2225#issue-1226948550
- Use latest **[v1.0.1](https://github.com/harvester/terraformer/releases)** release
