### ISSUE TITLE
[BUG] input nic ip and vip with same ip address in Harvester-Installer

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#2229]
**Describe the bug**
when input nic ip and vip with same ip address, not any verify message.

**To Reproduce**
1. set the nic ip first, eg: 192.168.31.100, and next.
<img width="823" alt="image" src="https://user-images.githubusercontent.com/3347460/167097642-974fd008-690e-4e8f-941d-4d3751a1e6f8.png">

2. set the vip ip, eg: 192.168.31.100.
<img width="900" alt="image" src="https://user-images.githubusercontent.com/3347460/167097792-e2180443-65cb-40a4-870e-79d1073d27de.png">

**Expected behavior**
 they mustn't be same, mustn't to continue

**Environment:**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): intel xeon e5-2678

**Comment by TachunLin** [comment]
Verified **fixed** on `master-26bff4f1-head` (6/10). Close this issue

### Result
During Harvester ISO installer process, when we set static node IP address with the same one as the VIP IP address
There will be an error message to prevent the installation process
`VIP must not be the same as Management NIC IP`
![image](https://user-images.githubusercontent.com/29251855/173719257-f60b55fd-0211-4fb7-8f45-3176eef4e577.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-26bff4f1-head` 

### Verify Steps
1. Launch ISO install process 
2. Set static node IP and gateway
![image](https://user-images.githubusercontent.com/29251855/173719118-1fd1609d-74f2-4f7d-9ff3-e1d21227e542.png)
3. Set the same node IP to the VIP field and press enter  
![image](https://user-images.githubusercontent.com/29251855/173719257-f60b55fd-0211-4fb7-8f45-3176eef4e577.png)

**Comment by w13915984028** [comment]
@chrisho 

Please also update doc, claim that the VIP should be different than any NODE IP. Thanks.

https://docs.harvesterhci.io/v1.0/install/management-address/

**Comment by Vicente-Cheng** [comment]
Just NOTE, backport PR is on https://github.com/harvester/harvester/issues/2377
