### ISSUE TITLE
[BUG] harvester installer - always first attempt failed if before was linux installed

### ISSUE THREAD

**Issue by mczka** [harvester/harvester#2230]
**Describe the bug**

reboot linux
boot and run harvester installer and setup
installation started and after Formating Drives ..

Error: Partitions(s) 3 on /dev/sda have been written, but we have unable inform the kernel of the change, probably because it/they are in use. As a result, the old partition(s) remain in use. You should reboot now before making further changes.

second installation sucess.

**Environment:**
 - Harvester ISO version: 1.0.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R6515

**Comment by BringerOD** [comment]
+1

**Comment by w13915984028** [comment]
@johnliu55tw @bk201 any idea? thanks.

**Comment by bk201** [comment]
@mczka @BringerOD Thanks for reporting. What is the original OS distribution on the disk before the installation?

**Comment by mczka** [comment]
not dependent on any particular version of OS
I have installed centos8, redhat8, proxmox_ve_7/debian and then reinstalling to harvester first attempt always failed.

**Comment by mczka** [comment]
see picture from dell console:
https://github.com/mczka/vSRX/blob/main/instaler_failed.png

**Comment by bk201** [comment]
The new partition tables can't reflect due to LVs on the original OS are activated.
Here is the step to repro: (Either with Harvester v1.0.2 ISO or `cOS-Seed-green-0.8.10-gc981c45e-x86_64.iso`):
- Install Centos8, I chose DVD ISO but I guess the key is using LVs.
- Reboot with Harvester ISO, run the installer or elemental command manually:
```
cos:~ # dmsetup ls --tree -o inverted
 (253:2)
 ├─centos-home (254:1)
 ├─centos-swap (254:0)
 └─centos-root (254:2)

cos:~ # ls -l /dev/vda
brw-rw---- 1 root disk 253, 0 May 23 02:31 /dev/vda

cos:~ # elemental --debug install /dev/vda
INFO[2022-05-23T02:36:54Z] Starting elemental version v0.0.14
DEBU[2022-05-23T02:36:54Z] Full config loaded: &{RecoveryLabel:COS_RECOVERY PersistentLabel:COS_PERSISTENT StateLabel:COS_STATE OEMLabel:COS_OEM SystemLabel:COS_SYSTEM ActiveLabel:COS_ACTIVE PassiveLabel:COS_PASSIVE Target: Source: CloudInit: ForceEfi:false ForceGpt:false PartLayout: Tty:0 NoFormat:false Force:false Strict:false Iso: DockerImg: NoVerify:false CloudInitPaths: GrubDefEntry:cOS 0.8.10 Reboot:false PowerOff:false ChannelUpgrades:true UpgradeImage:system/cos RecoveryImage:recovery/cos RecoveryUpgrade:false ImgSize:3072 Directory: ResetPersistent:false EjectCD:false PartTable: BootFlag: GrubConf:/etc/cos/grub.cfg Partitions:[] Images:map[] Config:{Logger:0xc0003fe310 Fs:0x1eabfc0 Mounter:0xc000532600 Runner:0xc000075e80 Syscall:0x1eac588 CloudInitRunner:0xc0002eb710 Luet:<nil> Client:0xc000516260 Cosign:false CosignPubKey: Repos:[] Arch:x86_64 SquashFsCompressionConfig:[]}}
DEBU[2022-05-23T02:36:54Z] Running cmd: 'udevadm settle'
DEBU[2022-05-23T02:36:55Z] Running cmd: 'udevadm settle'
DEBU[2022-05-23T02:36:56Z] Running cmd: 'udevadm settle'
DEBU[2022-05-23T02:36:57Z] Running cmd: 'udevadm settle'
DEBU[2022-05-23T02:36:58Z] Running cmd: 'udevadm settle'
DEBU[2022-05-23T02:36:59Z] Loading luet config from /etc/luet/luet.yaml
INFO[2022-05-23T02:36:59Z] Install called
INFO[2022-05-23T02:36:59Z] Running before-install hook
INFO[2022-05-23T02:36:59Z] Partitioning device...
DEBU[2022-05-23T02:36:59Z] Creating partition table...
DEBU[2022-05-23T02:36:59Z] Running cmd: 'parted --script --machine -- /dev/vda unit s mklabel msdos'
ERRO[2022-05-23T02:37:01Z] Failed creating new partition table: Error: Partition(s) 2 on /dev/vda have been written, but we have been unable to inform the kernel of the change, probably because it/they are in use.  As a result, the old partition(s) will remain in use.  You should reboot now before making further changes.
Error: 1 error occurred:
	* exit status 1
```

If we tear down the LVs, the installation goes fine.
```
cos:~ # vgchange -an centos
  0 logical volume(s) in volume group "centos" now active
cos:~ # dmsetup ls
No devices found
cos:~ # elemental --debug install /dev/vda
<Install OK>
```

**Comment by bk201** [comment]
@mczka  @BringerOD Could you help confirm if the previous OS uses the LVM scheme? Thanks.

**Comment by BringerOD** [comment]
@bk201, I had Ubuntu Server 22.04 LTS, installed prior to installing harvester.  

What is interesting, is once I did get harvester installed, I was only able to add 3 of the 4 drives to node.  My guess is there is still an issue with the way I have the drives configured.  

Any idea how to reset or reconfigure the drives.

**Comment by mczka** [comment]
centos8 and rhel8 by default is used LVM
debian/proxmox as well:
root@1-r6515:~# lsblk
NAME                         MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda                            8:0    0   1.1T  0 disk
├─sda1                         8:1    0  1007K  0 part
├─sda2                         8:2    0   512M  0 part /boot/efi
└─sda3                         8:3    0   1.1T  0 part
  ├─pve-swap                 253:0    0     8G  0 lvm  [SWAP]
  ├─pve-root                 253:1    0    96G  0 lvm  /
  ├─pve-data_tmeta           253:2    0    10G  0 lvm
  │ └─pve-data-tpool         253:4    0 976.8G  0 lvm
  │   ├─pve-data             253:5    0 976.8G  1 lvm
  │   ├─pve-vm--100--disk--0 253:6    0    16G  0 lvm
  │   ├─pve-vm--101--disk--0 253:7    0    32G  0 lvm
  │   ├─pve-vm--100--disk--1 253:8    0    18G  0 lvm
  │   ├─pve-vm--102--disk--0 253:9    0    32G  0 lvm
  │   └─pve-vm--102--disk--1 253:10   0    18G  0 lvm
  └─pve-data_tdata           253:3    0 976.8G  0 lvm
    └─pve-data-tpool         253:4    0 976.8G  0 lvm
      ├─pve-data             253:5    0 976.8G  1 lvm
      ├─pve-vm--100--disk--0 253:6    0    16G  0 lvm
      ├─pve-vm--101--disk--0 253:7    0    32G  0 lvm
      ├─pve-vm--100--disk--1 253:8    0    18G  0 lvm
      ├─pve-vm--102--disk--0 253:9    0    32G  0 lvm
      └─pve-vm--102--disk--1 253:10   0    18G  0 lvm
sdb                            8:16   0   3.3T  0 disk

**Comment by noahgildersleeve** [comment]
Tested in master-08af3d7c-head. 
## Verification steps
1. Installed Ubuntu 20.04 in LVM configuration
2. rebooted
3. Installed Harvester via ISO over previous linux install
4. Verified Harvester install by changing password and logging in.

**Comment by depasseg** [comment]
I ran into this same exact issue with a 1.3.0 install on 2 different Dell R730's that I think had Ubuntu installed.  I had to use gparted to delete all of the partitions (various ZFS, XFS, and others) for the install to be successful.

Here's a random snippet of the /var/log/console.log during install.
![Screenshot 2024-04-10 220328](https://github.com/harvester/harvester/assets/3201827/e8d37592-d343-42a1-b567-369055af1572)

**Comment by bk201** [comment]
@depasseg looks quite similar to https://github.com/harvester/harvester/issues/5398

**Comment by noahgildersleeve** [comment]
I imagine this is probably a result of #4527 / #5174. Basically if you don't use the flag the installer won't wipe the partition tables every time. We added the flag, but it's a manual thing that you need to enable when running the installer either in ISO or PXE boot.

**Comment by tserong** [comment]
@depasseg were you PXE booting the installer, or was this a manual install using the ISO image? AFAIK it shouldn't make any difference for this issue, but I'm trying to gather all the information I can.

**Comment by depasseg** [comment]
@tserong I was using the ISO (via local USB drive).  I'm not sure if it matters, but this was in a Dell R730 that had 8 HDs and 2 SSDs.  So I was installing to /dev/sdj and using /dev/sda as the data disk.
