### ISSUE TITLE
[BUG] Restricted admin can't see cluster in removing status

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2232]
**Describe the bug**

Restricted admin can't see cluster in removing status
**To Reproduce**
1. Import Harvester into rancher
2. Create RKE2 cluster in Node driver
3. Create RKE1 cluster in Node driver
4. Create restricted admin user
5. Delete RKE1 and RKE2 cluster
6. log out as admin
7. Log in as restricted admin
8. Check cluster management cluster list page

**Expected behavior**

clusters should show up
**Support bundle**

[supportbundle_f640d504-eb80-4df5-a6b0-acccf5932679_2022-05-06T23-04-33Z.zip](https://github.com/harvester/harvester/files/8644002/supportbundle_f640d504-eb80-4df5-a6b0-acccf5932679_2022-05-06T23-04-33Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.2-rc1
 - Rancher version: v2.6.5-rc8 single node docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node vagrant libvirt setup

**Additional context**
![Screenshot from 2022-05-06 15-59-02](https://user-images.githubusercontent.com/83787952/167226656-d1732331-3ee0-4180-89a7-965c397fb641.png)
![Screenshot from 2022-05-06 15-58-48](https://user-images.githubusercontent.com/83787952/167226659-62f5b45d-c017-4ada-ab89-328b83f420f4.png)
![Screenshot from 2022-05-06 15-58-40](https://user-images.githubusercontent.com/83787952/167226660-a9d56ce7-449e-48bd-bae5-6a10c3f0423a.png)

**Comment by FrankYang0529** [comment]
Hi @noahgildersleeve, I think the issue has already been fixed in Rancher v2.8.5. I can't reproduce it.

![Screenshot 2024-07-04 at 4 56 04 PM](https://github.com/harvester/harvester/assets/4927361/b95ab356-91ad-4098-bede-bd54de8b1314)
![Screenshot 2024-07-04 at 4 58 27 PM](https://github.com/harvester/harvester/assets/4927361/592e7e16-4aa0-4545-b2ee-0a1d4a21ec5b)

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-09f3ca1-head` and Rancher `v2.8.5` with restricted admin user in Rancher. Verified as fixed.

![Screenshot_20240709_112215](https://github.com/harvester/harvester/assets/83787952/3db0c656-50d6-4829-ae5e-2329b797defc)
![Screenshot_20240709_112152](https://github.com/harvester/harvester/assets/83787952/d1b19a76-62b3-422f-b4d9-ea4ffdc2ff66)
