### ISSUE TITLE
[FEATURE] Restore vm backup to other harvester cluster

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#2237]
**Is your feature request related to a problem? Please describe.**

my harvester cluster crash down. 
so I reinstall a new harvester, 
import all vm backups (nfs), restore them, but fail.

the direct reason is `ProvisioningFailed: Storageclass.storage.k8s.io "longhorn-image-xxxxx" not found`

**Describe the solution you'd like**

* set old nfs backup dir to new harvester (or copy one backup file)
* restore this backup in harvester ui
* need to edit some config different from old harvester env: 
  * namespace/cpu/ram/sshkey/network  (already editable in current harvester version)
  * base-image/image-storageclass...

**Describe alternatives you've considered**

* export volume from old-harvester to image
* backup this image to nfs  (or download to local file)
* restore this image in new-harvester, create new vm

any idea is welcome.
we need a persistence backup method, not bound to a running cluster.

**Comment by yasker** [comment]
There are a few complications regarding restoring a VM into a new Harvester cluster. We will investigate to understand the effort first.

**Comment by dseralathan** [comment]
Backup target is set to a NFS on both clusters . 
I have created a "VMBackup" from cluster 1 and power off VM and try to restore to the cluster 2. 
On cluster 2 the there is no backup available to restore . any idea how we can get the backup sync from cluster1 to 2

**Comment by albertkohl-monotek** [comment]
@dseralathan this is a known issue w/ v1.1.0, i believe it should have been fixed in v1.1.1 (i'm not running it yet, so i cant confirm that. 

what version of harvester are you running?

**Comment by dseralathan** [comment]
Thanks Albert, I am running with v1.1.0 ..

**Comment by albertkohl-monotek** [comment]
@dseralathan I’m about to test-upgrade a couple nodes tonight/tomorrow. I’ll let you know if the upgrade to v1.1.1 fixes it 😊

**Comment by dseralathan** [comment]
I have upgraded my cluster to v1.1.1  and it works super cool . Thanks Albert . good  success in cross cluster  VM re-store  !

**Comment by albertkohl-monotek** [comment]
@dseralathan great news! i just finished backup/restore from v1.0.3 > v1.0.3, getting ready to upgrade my second cluster to v1.1.1 and try again. happy to hear it worked well for you. i'm a little gun-shy upgrading my prod cluster from v1.0.3 > v1.1.1 considering all of the issues users had going to v1.1.0, so i'm dotting i's and crossing t's, just incase :)

**Comment by dseralathan** [comment]
on existing v.1.1.0 cluster  - When we delete and re-add the "backup target"  getting below  error 

admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting
<img width="1476" alt="Screen Shot 2022-12-02 at 10 29 29 AM" src="https://user-images.githubusercontent.com/117767598/205361320-54f91801-da44-4359-aa7a-8c1459b91bba.png">

But there is no VM in that state .

**Comment by Remigius2011** [comment]
Any reason for postponing this issue? imho this is an essential feature if virtualization - being able to backup a vm and restore it on a newly created environment - in case the old one is in a very unhealthy state or just to reorganize environments. I would not like to run production-ish workloads without this.

**Comment by albertkohl-monotek** [comment]
@Remigius2011 you can restore backups from one cluster to another. i've done it myself several times. if your vm is using a backing-image you have to make that image available first. review: [https://docs.harvesterhci.io/v1.1/vm/backup-restore](url)

the issue they are pushing back just has to do with how the cluster scans the backup target. you might have to cleanup vm migrations / backups in rancher if you have any open.

**Comment by dseralathan** [comment]
backup sync from cluster1 to 2 with same NFS is getting delayed , any idea how we can get the sync quickly ?

**Comment by ne0YT** [comment]
is ther a  way to get the missing image sot the 2nd cluster? smh I can restore some vms on another cluster and some others not, but even if I donwload the image used on a non restorable vm and upload it, it fials as there will be a different id. what can I do? I want to use it in a way to use Backups to deploy a bse VM on another site.

**Comment by WebberHuang1118** [comment]
@ne0YT 
Did you follow this https://docs.harvesterhci.io/v1.2/vm/backup-restore#restore-a-new-vm-on-another-harvester-cluster?
you have to create the same image on the new cluster.

**Comment by ne0YT** [comment]
@WebberHuang1118 I uploaded the image but it doesn't get the same internal name.. how can I do this to make it have the same name in "image-..." ?

**Comment by WebberHuang1118** [comment]
As the mentioned link https://docs.harvesterhci.io/v1.2/vm/backup-restore/#restore-a-new-vm-on-another-harvester-cluster

`Apply a VM image YAML with the same name and content in the new cluster.`

**Comment by ne0YT** [comment]
@WebberHuang1118 ok, it worked like this.. is quite complicated though and I think especially if you have a lot of backups and don't have the original cluster anmyore.

**Comment by WebberHuang1118** [comment]
We will include the image in the VM backup on Harvester v1.3.0

**Comment by noahgildersleeve** [comment]
Validated in GUI ticket #6371 . Test plan [here](https://github.com/harvester/harvester/issues/6371#issuecomment-2369884683) . Closing as complete. The only issues found while testing are #6630 and #6696

**Comment by FrankYang0529** [comment]
Hi @noahgildersleeve, could you take a look for comment https://github.com/harvester/harvester/issues/6721#issuecomment-2398505724? Restore v1.3.2 backup to v1.4.0 cluster is not supported. It needs another operation to restore VMImage like we did in previous clusters. I have created a document PR https://github.com/harvester/docs/pull/647 for it.

**Comment by noahgildersleeve** [comment]
Closing with working as designed due to feedback.
