### ISSUE TITLE
[BUG] Some settings don't have `configured` condition

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2238]
**Describe the bug**
Even if we configure some settings successfully like `backup-target` to NFS or `release-download-url`, they don't have condition `configured` in `status`. This may make some functions broken:

* https://github.com/harvester/harvester/blob/7fcf04f8df9797020d51d72e0d2ff9aa8c84b904/pkg/api/vm/handler.go#L414-L427

![Screen Shot 2022-05-09 at 4 28 00 PM](https://user-images.githubusercontent.com/4927361/167370695-5c7af656-db2c-4de9-a8f6-769642c01e64.png)

**To Reproduce**
1. Setup a harvester clusetr.
2. Configure `backup-target` to NFS. (LH NFS ref: https://longhorn.io/docs/1.2.4/snapshots-and-backups/backup-and-restore/set-backup-target/#nfs-backupstore)
3. Check status in `backup-target`. It's empty.
4. Configure `release-download-url` to a random URL.
5. Check status in `release-download-url`. It's empty.

**Expected behavior**
They should have condition `configured` as `true` in the `status`.

**Environment:**
 - Harvester ISO version: master-head
 - Underlying Infrastructure: KVM

**Comment by lanfon72** [comment]
is this a case of #2209 ?

**Comment by FrankYang0529** [comment]
@lanfon72, if kinchlo's backup-target doesn't have `configured` condition, I think these two cases are the same. Let me check in issue #2209.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/167804005-c685f4fa-1476-4d80-a5da-7a215eb2c287.png)
![image](https://user-images.githubusercontent.com/5169694/167803727-f02f0bc2-f6cd-4030-9baa-94b1c3875cd1.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.2-rc2**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow steps in https://github.com/harvester/tests/issues/335#issue-1230650793

**Comment by janeczku** [comment]
https://github.com/harvester/harvester/issues/2209#issuecomment-1124049483

**Comment by dseralathan** [comment]
kubectl create -f backup-target.yaml

Error from server (BadRequest): error when creating "backup-target.yaml": admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting

but there is no VM on that state
