### ISSUE TITLE
[BUG] Install extremely slow and hangs

### ISSUE THREAD

**Issue by crazyelectron-io** [harvester/harvester#2241]
I have a system with Intel i9-10850K CPU, Z490 chipset, 64GB RAM and 3 Samsung SSDs (1 NVME 1TB, 2 SATA 8TB). The Harvester bare metal install from USB is extremely slow and hangs - reproducible - after quite a while at:

```
...
[ 1417.423856 ] squashfs: version 4.0 (2009/01/31) Phillip Lougher
[ 1417.551756 ] loop0: detected capacity change from 0 to 1445624
```
I don't get to the install menu/questions. 
I tried both v1.0.1 and v1.0.2-rc1 (flashed with balenaEtcher), same result. The system is in UEFI mode.
BTW, it has an existing Proxmox installation on disk.

**Comment by bk201** [comment]
@crazyelectron-io Could you try plugging the installation USB stick into a USB 2.0 connector? I saw some issues when using a USB 3.x sockets before.

**Comment by crazyelectron-io** [comment]
Thanks for your quick response.
Unfortunately, I get the same result when installing from USB 2.0.

**Comment by crazyelectron-io** [comment]
Tried with AHCI and RAID/Octane mode for the NVME SSD, same result... there are no errors displayed, it just takes a long time between each step/logged line (up to a few minutes) and finally hangs.

**Comment by oivindoh** [comment]
@crazyelectron-io this sounds a bit like the [graphics issue](https://docs.harvesterhci.io/v1.0/install/usb-install/#graphics-issue) I experienced on a similar setup. You might want to give the kernel parameter change here a try. Also note the console=ttyS0 removal under Other issues.

**Comment by crazyelectron-io** [comment]
Thanks @oivindoh for this suggestion!
It turned out to be the `console=ttyS0` parameter that was mentioned at the bottom of the page. The first Harvester node has just been installed...
