### ISSUE TITLE
[BUG] The VM Web VNC console connection is disconnected after around 10 minutes open usage 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2242]
**Describe the bug**

Open VM in Web VNC console, after 10 minutes usage it suddenly  display error **"Web VNC console connection is disconnected"**
![image](https://user-images.githubusercontent.com/29251855/167386765-285cf94f-5acb-4f61-9226-18c12e72502c.png)

![image](https://user-images.githubusercontent.com/29251855/167385214-780f5c3b-d0b4-4ee2-adf9-f70afeca2fe7.png)

**To Reproduce**
1. Create a Ubuntu desktop image
2. Enable virtual network with `harvester-mgmt`
3. Create a virtual network `vlan806` with id `806`
4. Create a virtual machine with Ubuntu desktop and vlan 806
5. Finish the config and installation steps
6. Open VM from WebVNC
7. Install chrome and docker CE
8. Create rancher container from command 
`sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.6.5-rc6`
10. Use VM for around 10 minutes
11. Check the Web VNC connection status

**Expected behavior**

Web VNC should not disconnect while the VM is in usage

**Support bundle**

[supportbundle_2175eb63-d1a2-4efa-9174-7b9cae83c3d7_2022-05-09T09-58-25Z.zip](https://github.com/harvester/harvester/files/8650703/supportbundle_2175eb63-d1a2-4efa-9174-7b9cae83c3d7_2022-05-09T09-58-25Z.zip)

**Environment:**
 - Harvester ISO version: v1.0.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes harvester on Provo bare machines

**Comment by WuJun2016** [comment]
Results of the survey：

VNC disconnection is caused by a close event initiated by the backend.
case 1:
If the user is doing something in VNC like typing continuously, the websocket link will not be broken, otherwise the websocket will be broken.

case 2:
I found that this may be related to the environment, some environments may keep the websocket link for a long time, more than half an hour, and some environments will automatically disconnect after 2 minutes。

Need help from back-end engineers to continue to troubleshoot the problem。

**Comment by Martin-Weiss** [comment]
Just hitting this issue, too - it would be nice if we could implement a re-connect from the client side.. In case I refresh the browser it does a re-connect but this should be more or less automatic if possible.

**Comment by irishgordo** [comment]
@jeff-radick-suse is noticing this on v1.1.2 as well in Firefox - I'm not sure if this has been seen on v1.2.0-rc5 yet

**Comment by ianb-mp** [comment]
I'm seeing this issue on v1.2.1 using Chrome on MacOS. It is very inconsistent i.e. the same VM will do it sometimes, and not other times. I did wonder if the issue was more likely on console output where nothing is changing e.g. static GUI screen...but that's just a guess.

**Comment by turnerd10** [comment]
Having the same issue on v1.2.1 -- drops due to inactivity, consistently, and within 5 minutes.

**Comment by irishgordo** [comment]
This looks good on master-head, thanks for the fix @Yu-Jack :smile: :+1: 

https://github.com/harvester/harvester/assets/5370752/3005fe7b-6824-4882-b52a-abfd22653f55
