### ISSUE TITLE
[BUG] VM template is not working with Node scheduling

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2244]
### Describe the bug
When Creating VM with _**multiple instance**_, the **Node Scheduling** is not working as expected.

### To Reproduce
1. Install Harvester with any nodes
2. Create an Image for VM creation
3. Create VM with _**Multiple Instance**_ and _**Use VM Template**_, In **Node Scheduling** tab, select `Run VM on specific node(s)`
4. Created VMs should be scheduled on the specific node

### Expected behavior
all of VMs should be scheduled on the node which specified.

## Environment:
 - Harvester ISO version: **v1.0.2-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
https://user-images.githubusercontent.com/5169694/167416344-8e2a8246-319a-4205-9736-030a800c183b.mp4

**Comment by lanfon72** [comment]
and the describe on Node Scheduling: `Run VM on specific node(s) - (Live migration is not supported)`, as it can only select one node, so **`(s)`** should be removed?

**Comment by weihanglo** [comment]
I can reproduce this issue. When creating multiple VMs with VM template pre-filled, the modified value of node scheduling is not included in the HTTP request to `https://cluster-vip/v1/harvester/kubevirt.io.virtualmachines/default`, whereas the payload of the request of single VM creation is correct.

@WuJun2016 Can you help investigate the frontend part? I've read a bit but no luck to understand it 🥲

**Comment by WuJun2016** [comment]
This is an issue of the frontend  @weihanglo

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/177742575-31730953-5ffd-4018-b5ce-1b1e487ee14c.png)


Test Information
----
* Environment: **Baremetal 5 nodes**
* Harvester Version: **master-a926a44e-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Step to Reproduce** in https://github.com/harvester/harvester/issues/2244#issue-1229687887
