### ISSUE TITLE
[BUG] Backup Detail Page has incorrect title

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2247]
**Describe the bug**
Harvester 1.0.0

The title of the backup detail page is always set to "Restore Virtual Machine" instead of the name of the backup.

<img width="1686" alt="Screenshot 2022-05-09 at 15 14 31" src="https://user-images.githubusercontent.com/3813921/167450343-7c1745bf-c1db-4cba-8ee9-3a0d1369d30b.png">

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/167601831-246cc970-80c4-4c3e-99bc-4415032664e2.png)


Test Information
----
* Environment: **Bare metal DL360 3 nodes**
* Harvester Version: **v1.0.2-rc1**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with any nodes
2. Create an Image for VM creation
3. Setup **backup-target**
4. Create VM `vm1`, after VM started, take backup on the VM, named `vm1b`.
5. Navigate to _Backups_ and the details of `vm1b`, the title should displays `vm1b`.
