### ISSUE TITLE
[FEATURE] Allow VLAN tagged traffic to management interface in installer

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2257]
**Is your feature request related to a problem? Please describe.**

related to VLAN enhancement https://github.com/harvester/harvester/issues/2236
some network switch didn't have native vlan settings for harvester installation.
Allow users assign vlan id in installer UI.

**Describe the solution you'd like**

Please refer HEP
https://github.com/harvester/harvester/pull/2161

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
close this issue as it is duplicated with https://github.com/harvester/harvester/issues/1390.
