### ISSUE TITLE
[BUG] Server is duplicated and corrupted during the upgrade process

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2258]
**Describe the bug**
While performing the 1.0.0 -> 1.0.1 upgrade one of the servers was "duplicated" causing the duplicated server to malfunction and the cluster to be reduced to just 2 working nodes when the upgrade completed.

**To Reproduce**
1. Install Harvester 1.0.0 on 3 servers
2. Perform the upgrade to 1.0.1 following the documentation (including all the preparations, such as shutting down VMs): https://docs.harvesterhci.io/v1.0/upgrade/automatic/

The screenshot below shows how the server `harvey` was duplicated as a server named `192.168.200.5` (note the identical host IP).

![image](https://user-images.githubusercontent.com/3813921/167808432-fcd3c751-9809-4923-806b-e4c43d72853d.png)

Here is the in-progress upgrade, showing how the duplicate server appeared when the server `harvey´ was in "post-draining" phase.

![image](https://user-images.githubusercontent.com/3813921/167808691-d6d78cbe-6c83-4010-b658-863c3293360b.png)

Support Bundle (after cleaning up the duplicated node and removing the non-working server "harvey" from the cluster).

[supportbundle_e040cc7c-fcf3-4892-bcf4-514bca7bf53b_2022-05-10T11-26-09Z.zip](https://github.com/harvester/harvester/files/8668262/supportbundle_e040cc7c-fcf3-4892-bcf4-514bca7bf53b_2022-05-10T11-26-09Z.zip)

**Comment by w13915984028** [comment]
the panic stack in https://gist.github.com/janeczku/7d42329f40154776c4f2b108ab8db1aa 

```
May 10 08:13:48 harvey rke2[15992]: panic: removed all voters
May 10 08:13:48 harvey rke2[15992]: goroutine 358 [running]:
May 10 08:13:48 harvey rke2[15992]: go.etcd.io/etcd/raft.(*raft).applyConfChange(0xc000ea0280, 0x0, 0xc004259b90, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
May 10 08:13:48 harvey rke2[15992]:         /go/pkg/mod/github.com/k3s-io/etcd@v0.5.0-alpha.5.0.20220113195313-6c2233a709e8/raft/raft.go:1514 +0x225
```

is similar to :

https://github.com/rancher/rke2/issues/2829

**Comment by guangbochen** [comment]
Can't reproduce it with the latest version; please feel free to re-open it if u have more detailed info, thanks.
