### ISSUE TITLE
Data format unification on VM detail page's migration tab

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#226]
On the VM detail page's migration tab, the source node and the target node are populated with a dash when there is no data. Howver, the started, ended, and Message are populated withe N/A when there is no data.

Maybe it is better to unify the format?

![image](https://user-images.githubusercontent.com/57614736/98315100-5d322680-2012-11eb-8a5f-64b345aa5ec8.png)

**Comment by guangbochen** [comment]
close as migration is current move-out to the scope.
