### ISSUE TITLE
[BUG] VM's RunStrategy will be updated to `Halted` when stop the VM

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2265]
### Describe the bug
There have two different behaviors:
- Stop the VM by clicking **Stop** Button, RunStrategy will be updated `RerunOnFailure -> Halted`
- Stop the VM by executing `poweroff` insidie the VM, RunStrategy _**will not be update**_, but user can still click **Stop** Button to stop the VM again. (even if the VM is in `Off` state)

### To Reproduce
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create the VM `vm1`
4. Login to `vm1`, execute `sudo poweroff`
5. The VM's state should be `Off`
6. Navigate to VM's Config, **RunStrategy** in _Advanced Options_ should be `RerunOnFailure`
7. Select the VM, **Stop** Button is not disabled
8. Click **Stop** button, then navigate to VM's Config
9. **RunStrategy** in _Advanced Options_ will be updated to `Halted`

### Expected behavior
No idea, at least they should be consistent?

## Environment:
 - Harvester ISO version: **v1.0.2-rc2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

### Additional context
**Generate Template** function will be affected, if user do **Generate Template** on the VM which is `Off`, the default `RunStrategy` will be **Halted**.

related issues: #2172, #1953, #574, #1882, #2154

**Comment by FrankYang0529** [comment]
VMI has many phases. If we run `sudo poweroff` in the VM, the pod of the VM will become `complete` and VMI will become `Succeed`. We should also determine the phase of VMI in `canStop`.

https://github.com/kubevirt/kubevirt/blob/a3aaf1ace40c44c9dafaf2c091851d5cdb829fd7/staging/src/kubevirt.io/api/core/v1/types.go#L648-L668

**Comment by lanfon72** [comment]
@guangbochen please help to update the milestone and priority accordingly.

**Comment by FrankYang0529** [comment]
@lanfon72, sending a stop request through UI to a VM with `RerunOnFailure` or `Always` RunStrategy and it becomes `Halted` is a known issue. Please check https://github.com/kubevirt/kubevirt/issues/7295.

I think it's better to change the issue title to `UI should not show the stop button when users already run "poweroff" in the VM`.

**Comment by lanfon72** [comment]
@FrankYang0529 yes, I knew `RunStrategy` would be **Halted** if user use **Stop** Button to stop the VM, as the attached image in https://github.com/harvester/harvester/issues/1953#issuecomment-1064792750
I tend to keep the tittle for users, they can use the keywords like _Halted_, _RunStrategy_ and _stop VM_ to find this.
And I would suggest to add the image (in the link above) to our document or reference it to the origin document, so that user will get more information about **RunStrategy**.

For the issue, as you mentioned in https://github.com/harvester/harvester/issues/2265#issuecomment-1124735599, the pod will be **completed** if user use `poweroff` or `shutdown` in the VM, and RunStrategy will not be `Halted`. (unless user stop it again by the button)

**Comment by lanfon72** [comment]
Verified VM will not be able to `Stop` again if it already be `poweroff` inside.
(But I think **RunStrategy** still inconsistent)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-a242948b-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow the **Steps to reproduce** in https://github.com/harvester/harvester/issues/2265#issue-1232804974
