### ISSUE TITLE
[Doc] HDD support

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#2271]
**Is your feature request related to a problem? Please describe.**
SSD is not economical for cold/archival storage.

**Describe the solution you'd like**
HDD support (Western Digital VelociRaptor 10k)

**Additional context**
Typical capacity of cluster: 16TB up to 1PB

Note:

Related issue: https://github.com/harvester/harvester/issues/2147
Also, depends on Longhorn's support for HDD.

**Comment by bk201** [comment]
We can have a doc to describe use cases after #2147 is done.
- HDD tiering is not recommended for RKE2 clusters and regular use.
- Users can also reduce replica count in the storage class (for cold storage).

**Comment by bk201** [comment]
Close, the doc PR is merged.
