### ISSUE TITLE
[Question] How do I create or download and run a container image?

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#2277]
Hello,

Sorry for the extremely basic question, but I feel like I'm totally missing something here

What options are there for running containers on Harvester?  Is there information on how to create a container, or install a docker/OCI image, or something, etc. somewhere? 

I can only seem to find documentation on creating virtual machines.

Edit: I'd like to refine this question

Upon more reading, I am seeing provisioning of RKE1 and 2 - is this what I am expected to use for containers?

I am reading documentation here: https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

I have two bare metal servers provisioned with harvester 1.0.2-rc2 up and running. They appear to be working fine, that is the bare minimum for Rancher (RKE) deployment, correct?  

I have not deployed anything to my Harvester cluster yet because I am confused, I thought I would be able to download a container image and run it once Harvester cluster was up and running. 

Would a 3rd node or witness be helpful to avoid split-brain? I seem to have seen some info warning against even-number clusters, but I cannot remember if that is Kubernetes or ceph. I have separate vSphere cluster on which I can run another VM, please advise.

Trying to understand all this stuff coming it to it from the ground level, it's a bit daunting jumping straight into Harvester after only having experience with `podman` on a laptop lol.

Thanks for the hand-holding.

**Comment by bk201** [comment]
> I can only seem to find documentation on creating virtual machines.

Yes, VM is the primary user-faced interface to the platform. https://harvesterhci.io/img/Harvester-Architecture-3.2-Outlines.svg

The platform is built on Kubernetes and you certainly can run containers in it if you own the cluster. But we don't recommend it.

> Upon more reading, I am seeing provisioning of RKE1 and 2 - is this what I am expected to use for containers?

A more recommended approach is to provision Kubernetes clusters inside VMs to run your workload. You can do this by yourself or import the Harvester cluster to an existing Rancher service, and let the Rancher service create Kubernetes clusters within VMs for you. Just as the link you post:
- https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/
- https://docs.harvesterhci.io/v1.0/rancher/rke2-cluster/

And bear in mind that the VMs layer introduces overheads.

> Would a 3rd node or witness be helpful to avoid split-brain? I seem to have seen some info warning against even-number clusters, but I cannot remember if that is Kubernetes or ceph.

3-nodes cluster is recommended in production environments.

**Comment by averyfreeman** [comment]
This is extremely clarifying

So then, could I create first node for Rancher in a vSphere VM and then add the 2 bare-metal harvester nodes to provision Rancher in each of those (for 3 total nodes)?

What do you think the easiest way to go about getting kubernetes platform (for containers) with 3 nodes via my current setup? 

Thanks again

**Comment by bk201** [comment]
> This is extremely clarifying
> 
> So then, could I create first node for Rancher in a vSphere VM and then add the 2 bare-metal harvester nodes to provision Rancher in each of those (for 3 total nodes)?

Sorry, perhaps I didn't explain clearly. The Rancher service is outside of Harvester deployment (it can even run in a docker pod for dev purposes). I think the first step is you can find a way to provision Rancher, and "import" the Harvester into it.


> What do you think the easiest way to go about getting kubernetes platform (for containers) with 3 nodes via my current setup?
>

You probably need another bare-metal node to form a 3-node cluster. For your current setup, the first node acts as control plane node and the second one runs as a worker. (Although both can schedule VM workloads).

 
 
> Thanks again

**Comment by averyfreeman** [comment]
>The Rancher service is outside of Harvester deployment (it can even run in a docker pod for dev purposes). I think the first step is you can find a way to provision Rancher, and "import" the Harvester into it.

No I think I followed correctly, thanks for explaining this all to me.  I'll try setting up RKE in a few vSphere VMs just to get it started.

Once Harvester is imported into Rancher, though, can its compute + storage resources be used for containers, or is it only for Rancher to have control over Harvester's VMs?

I mistakenly thought since Harvester was scheduled by Kubernetes that it would have container capabilities built-in, which was a big oversight on my part.

Thanks again

**Comment by victorhooi** [comment]
Is there a particular reason that it's not possible to run user containers directly on Harvester?

As in, why do you need to deploy another Rancher cluster, inside of Harvester, just to run containers? I assume that would introduce overheads, as well as additional operational complexity.

```
Bare Metal -> Harvester - > VM running Rancher -> Container with your workload
```

Also - there seems to be slightly confusing messaging from Harvester itself around this as well - e.g. https://harvesterhci.io/:

> Containers and VMS in the Same Environment

Was this something possible in the past and removed? Or just something that is planned for the future version of Harvester?

**Comment by averyfreeman** [comment]
> The Rancher service is outside of Harvester deployment . . . the first step is you can find a way to provision Rancher, and "import" the Harvester into it.

Still hoping to understand best how Harvester is situated in the ecosystem

Say I had a new datacenter and I wanted to set up an all-OpenSUSE shop:

Would it be most logical to do something like set up Uyuni for BM provisionining ---> RKE for the overall orchestration platform and then ---> Harvester for VMs? 

Should I be viewing Harvester as more of a bolt-on feature to add VM workloads to RKE since you're saying it's not well suited to running containers on its own?  And start with Rancher/RKE as the starting point for all orchestration methods?

If you were setting up this proposed datacenter, how would you do it, in a nutshell? 

Thank you

**Comment by jarriagad** [comment]
> Also - there seems to be slightly confusing messaging from Harvester itself around this as well - e.g. https://harvesterhci.io/:
> 
> > Containers and VMS in the Same Environment
> 
> Was this something possible in the past and removed? Or just something that is planned for the future version of Harvester?

This messaging is a bit confusing. There is kubectl access via the root user and I guess nothing is stopping you from running a pod within the same cluster that manages the same VM. But I have not found a native way for harvester to run container. Especially deploying them from the UI

**Comment by MegaShinySnivy** [comment]
Will running K8s workloads and VMs side by side be possible in the future? Currently, I would rather not deal with the overhead of running 2 longhorn storage providers one atop the other, meaning it would be better for me to run the k8s workload directly on harvester instead of in a set of VMs.

**Comment by zengqingfu1442** [comment]
It seems cannot create a container directly on harvester in a native way.

**Comment by bk201** [comment]
@zengqingfu1442 starts from v1.2.0, there is a experimental support of baremetal container workload support: https://docs.harvesterhci.io/v1.3/rancher/rancher-integration#harvester-baremetal-container-workload-support-experimental
