### ISSUE TITLE
[FEATURE] Add BIOS or EFI boot option for the bootloader

### ISSUE THREAD

**Issue by Chrisputer** [harvester/harvester#2278]
**Is your feature request related to a problem? Please describe.**

When booting an ISO, I expect to not see the EFI Interactive Shell. There are still quite a few ISOs that cannot use EFI for booting and need to use BIOS.

**Describe the solution you'd like**

I'd like to see a toggle option for BIOS or EFI Bootloader

**Describe alternatives you've considered**

Right now I have to go into YAML to change this. This has caused some issues when trying to learn about this new system.

**Additional context**

http://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#biosuefi
This Doc is not accurate. It is set to boot in EFI by default.

**Comment by yasker** [comment]
Should be fixed in v1.0.2 : https://github.com/harvester/harvester/issues/2210
