### ISSUE TITLE
[FEATURE] Freeze VM before live backup

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#2279]
**Is your feature request related to a problem? Please describe.**
Freeze VM to avoid users keep writing data during live backup.

**Describe the solution you'd like**
Try to call `freeze` and `unfreeze` for VMI.

**Additional context**
https://github.com/kubevirt/kubevirt/pull/5942

**Comment by yasker** [comment]
Duplicate of #1723 .
