### ISSUE TITLE
[BUG] Failed to wait for processing start in 60 seconds — Labels issue?

### ISSUE THREAD

**Issue by axsms** [harvester/harvester#2283]
**Describe the bug**
On both a 1.0.1 and 1.0.2 cluster, when attempting to upload varying images, I get "Failed to wait for processing start in 60 seconds". I have been trying to do this through an RKE2 Rancher 2.6.4 cluster. These attempts were without adding labels. I just attempted to do this directly on a single 1.0.2 node and it failed again. However, I decided to look at the label option and discovered there were two label keys and dropdowns for each. When I selected the dropdowns and then selected create, everything works as expected. 

Keys:
harvesterhci.io/os-type
harvesterhci.io/image-type

On the Harvester nodes, this appears to either be a bug or a process that is not defined in the GUI. On Rancher, the experience is different — no predefined keys and associated dropdowns in the labels area. This looks like an unintended variation in UX. I'm not sure if it is an issue with Rancher or the Harvester driver, for bug reporting purposes?

**To Reproduce**

Rancher managed Harvester cluster from Rancher:
1. On a Rancher managed Harvester cluster, go to and select the `File` radio button and then select `Upload File`...choose any image (I tried iso, img, qcow2).
2. Go to the `Labels` options and view the options available, but do not create any labels. Notice that there are no predefined keys here.
3.  Select `Create`
4. After 60 seconds have passed, this will fail with the message `Failed to wait for processing start in 60 seconds`

Directly on the Harvester node:
1. Go to and select the `File` radio button and then select `Upload File`...choose any image (I did two...img and iso)
2. Go to the `Labels` options and view the options available. You should see two predefined keys and dropdown options for each. Select the appropriate dropdown options.
3. Select `Create`
4. An upload begins and completes. 

**Expected behavior**
The user experience regarding uploading images should be the same, whether being executed in Rancher or on Harvester nodes directly. The uploads should succeed either without labels, or with preconfigured labels, or with label instructions provided while creating the image. Further, if not using a particular label is expected to cause failure, a failure message would be helpful. 

**Support bundle**
If this is required, I will scrub mine for security purposes and post upon request. 

**Environment:**
 - Harvester ISO version: 1.0.1 and 1.0.2. Cluster management conducted through Rancher 2.6.4
 - Underlying Infrastructure: Bare metal DL 360 G9 (x3)

**Additional context**
This may be another bug to report...After deleting the failed uploads and refreshing the page, they appear gone. Coming back to the Images area later often shows those deleted failures again, so they must not get purged completely.

**Comment by WuJun2016** [comment]
Hi, @axsgitty   harvester v1.0.2 corresponds to rancher v2.6.5, and their UX behavior is basically the same.

**Comment by WuJun2016** [comment]
Whether the upload fails or not is not related to the labels, you need to provide more information, such as the yaml file

**Comment by axsms** [comment]
I considered this a bug because I get "Failed to wait for processing start in 60 seconds". I wasn't interested in reporting this bug, frankly. However, I thought the labels part of this was interesting as a workaround or perhaps a separate bug and I wasn't sure others would find the specific pattern I was finding and decided to go ahead and report this. 

I'll check my yaml for security and scrub if required and get it to you later today. 

For visual reference to the difference that I see, below are the ss from Rancher (red) and Harvester (blue). If this is by design, please close this. I have a workaround to the failures and would be happy not to spend one minute where it's not helpful. 

![_Screenshot 2022-05-18 071450](https://user-images.githubusercontent.com/83303625/169026846-624e6e06-7fa1-48f5-846a-8ed6800f6a99.png)

![_Screenshot 2022-05-18 071714](https://user-images.githubusercontent.com/83303625/169026881-5ad24545-f748-4236-bb5f-e794a7461b92.png)

**Comment by simonflood** [comment]
Related to #2158 ?

**Comment by axsms** [comment]
[node3.zip] (https://github.com/harvester/harvester/files/8718178/node3.zip)
scrubbed yaml

**Comment by axsms** [comment]
@simonflood Looks like that may be related.

**Comment by axsms** [comment]
Closed as likely a duplicate of #2158, as mentioned by @simonflood.
