### ISSUE TITLE
[Question] Since harvester is already based on rke2, should you run a cluster on top or use the existing cluster

### ISSUE THREAD

**Issue by jhoelzel** [harvester/harvester#2284]
Hey guys,

first of all thank you for harvester it has huge potential and I really enjoy the concept.

The question I have is:

Harvester already runs a cluster for me, so if i want to use it in my baremetal setup, would you advise to run another cluster -on top- of Harvester or to use the provided kubeconfig to work in the already provisioned cluster at hand?

The basic idea is to run cluster and VM side by side and i am aware that running a cluster on top is basically using kubernetes in kubernetes, but i would like to find out what the best practise for a bare metal deployment would be.

Thank you in advance!

**Comment by w13915984028** [comment]
@jhoelzel thanks for your question, we need to know more details:
How is the current Harvester cluster built, in bare metal servers or like KVM VMs ? how many nodes?  (let's say cluster A)
For you baremetal setup, what is it targeting for ? (let's say potential cluster B), the relationship of A and B.

When A is built on top of baremetal, then add those new nodes in B into A is OK.
When A is built on top of say KVM VM, then A and B have different CPU/memory/storage/networks, 2 clusters look better. And an indepedent Rancher setup can manage those 2 clusters in one UI. 
Per https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

and more ...

**Comment by jhoelzel** [comment]
@w13915984028 first of all thank you for your help!

We have deployed harvester over bare-metal-iso install with 3 nodes and it works nicely in principle. 

The question that we have is that if we should add yet another layer of kubernetes onto the existing metal? Since Harvester already provisions a working cluster with Longhorn, Metrics, Kube-VIP and more, we are, apart from ipv6 support, ready to go.

With the death of k3os we are looking for a nice bare metal distro that also is able to hosts Virtual Machines for software we have not yet have a chance to port (and some we probably never will) and harvester seems perfect for that.

We also have already played with rancher to provision harvester, but still, having a cluster in a cluster still seems very much like the Inception movie =)

**Comment by yaocw2020** [comment]
I believe it's a common question. What about writing a KB to explain it?

**Comment by guangbochen** [comment]
In Harvester v1.2.0, we are planning to [add bare-metal container and MCM support ](https://github.com/harvester/harvester/issues/2679), so both options would work. It depends on whether you want to spin up different guest k8s clusters for every business or run container and VM side-by-side in the same cluster on edge, branch, or home-lab cases.
Before Harvester v1.2.0, using a separated cluster for multi-cluster or container management with either your own providers or using VM is still recommended, this is more choices of product positioning instead of tech limitations only, thanks.
