### ISSUE TITLE
[BUG]  The project-owner user will see an additional alert

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2288]
**Describe the bug**

<img width="765" alt="image" src="https://user-images.githubusercontent.com/24985926/169199139-dc269e99-f2f5-4513-b6f4-b39796b29338.png">

**To Reproduce**
1. Importing a harvester cluster in a rancher cluster
2. enter the imported harvester cluster from the `Virtualization Management` page
3. create a new Project  (test), Create a test namespace in the test project.
4. go to `Network` page, add `vlan 1`
5. create a vm，  choose  `test namespace`,  choose `vlan network`, click save
6. create a new user (test),  choose `Standard User`
7. go to the `project page`, edit `test` Project, set `test` user to Project Owner。
<img width="1543" alt="image" src="https://user-images.githubusercontent.com/24985926/169200683-2532871a-980e-43b2-ae76-87b1d44f5a35.png">
8. login again with `test user`
9. go to the vm page。

**Expected behavior**

 `test` vm should not show `VLAN network is inactive`

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-26bff4f1-head` (6/10) with Rancher `v2.6.5`. 
Move to implement pipeline. 

Harvester ui-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html 
Rancher ui dashboard-index: https://releases.rancher.com/dashboard/latest/index.html
Rancher offline preferred: `Remote` 


### Result
Use rancher standard user `test` with project owner permission to access Harvester.
The VM created on vlan1 still show error message
```
VLAN network is inactive
```
  ![Screenshot from 2022-06-13 19-56-05](https://user-images.githubusercontent.com/29251855/173348394-307ba163-544f-4537-a5ab-ab9949fb499f.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-26bff4f1-head` 

### Verify Steps
Follow the issue description https://github.com/harvester/harvester/issues/2288#issue-1241173686

**Comment by WuJun2016** [comment]
sorry,  My low-level mistake.  repushed pr.

**Comment by TachunLin** [comment]
Move to ready for test and verify with #2394

**Comment by TachunLin** [comment]
Verified **fixed** on `master-96b90714-head` (6/20) with Rancher `v2.6.5`. Close this issue

Harvester ui-index: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
Rancher ui dashboard url: https://releases.rancher.com/harvester-ui/dashboard/latest/f8fc153d786193df9676.js
Rancher offline preferred: `Remote` 


### Result
Use rancher standard user `test` with project owner permission to access Harvester.
Now there is no error alert on the created VM with vlan1 network 
![image](https://user-images.githubusercontent.com/29251855/174733151-c8bcffdd-50e0-404e-a5b6-a9ff2f1a7387.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-96b90714-head` (6/20)

### Verify Steps
Follow the issue description https://github.com/harvester/harvester/issues/2288#issue-1241173686
