### ISSUE TITLE
[Question] ISO install on single NIC, yet warning against using the mgmt for VLAN use?

### ISSUE THREAD

**Issue by axsms** [harvester/harvester#2290]
I have two NIC nodes and using ISO to install. If I upload a config, I suppose I could take advantage of the second NIC, but I'm trying to find clear docs on whether that is what I should be doing with an example yaml/config. However, if a second NIC is recommended, shouldn't the default ISO install ask for the configuration details required to use a second NIC? 

I am presenting this as a question, rather than as a feature request, because it's entirely possible that I am misunderstanding some fundamental that makes my enquiry a silly question. If that's the case, could someone help me understand how I should be thinking of this and the best practices, so I can learn and implement them? I have read every page of every document on Harvester Docs multiple times over the past month and I'm still missing something here.

**Comment by rodrigo14miguel** [comment]
Hi @axsgitty 
from the documentation and what I encountered in my lab on version 1.0.2, when installing from ISO, you configure the management network only.
After the installation is complete you can access the management UI and then assign your second NIC as the VLAN network interface (in advanced->settings->vlan in the left menu of the UI).
Having your VLAN network interface assigned, you can then create VLAN networks (left menu in the UI advanced->networks) that are served by that second NIC that you configure as VLAN network interface.

**Comment by ibrokethecloud** [comment]
Hi @axsgitty, please let us know if the comment from @rodrigo14miguel helps clarify.

Additional docs are available here: https://docs.harvesterhci.io/v1.0/networking/best-practice/overview/

**Comment by axsms** [comment]
@ibrokethecloud Thanks for the reminder. I read the comment between meetings and forgot to reply. My scenario/question isn't clear in the docs. From above..."However, if a second NIC is recommended, shouldn't the default ISO install ask for the configuration details required to use a second NIC?". Please consider switches are not VLAN aware and there is no DHCP. 

@rodrigo14miguel Thank you for taking the time to note those details. I am still not sure the best way to setup the second NIC with a static IP. Our remote hosting service doesn't offer DHCP options, though our servers are isolated to communicating with only our other servers.

**Comment by axsms** [comment]
Opened #2330 a few days ago.

**Comment by rodrigo14miguel** [comment]
Hi @axsgitty 

Do you have a usecase for setting a static IP on your second NIC?

The second NIC is recommended for VM network traffic but it is not required to setup harvester. You configure your second NIC after the installation process. Additionally, you do not need your harvester host to have static IP on your second NIC, as it will server VM network traffic.

You should end up with:
- NIC1 -> static IP for management (and floating VIP), network connection configured with access mode on the uplink switch.
- NIC2 -> no static IP, VLAN trunk configured in the upstream switch.

**Comment by axsms** [comment]
That clarification is excellent, and I believe clears up my confusion. Thank you. I have been thinking I must configure the 2nd NIC on each node to be able to communicate, but I now understand that the Trunk in the upstream switch will pass VLAN traffic identified by selecting the NIC, as described by you above (and in the docs) and then identifying the VLAN for the VMs. Do I have that correct?

**Comment by rodrigo14miguel** [comment]
@axsgitty that is correct.

**Comment by axsms** [comment]
Thank you for that clarification. Closing.
