### ISSUE TITLE
[FEATURE] collect Fleet logs and YAMLs in support bundles

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2297]
**Is your feature request related to a problem? Please describe.**

Fleet controller and agent logs are not included in support bundles.
They are essential to debugging upgrade-related issues.

**Describe the solution you'd like**

Add those logs.

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Verified log files be added.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-a242948b-head** for `v1.1.0`, **v1.0-ce8b57fd-head** for `v1.0.3`
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to support page
3. Click **Generate Support Bundle** and do Generate
4. log files should be exist in the zipfile of support bundle:
    - `logs/cattle-fleet-local-system/fleet-agent-<randomID>/fleet-agent.log`
    - `logs/cattle-fleet-system/fleet-controller-<randomID>/fleet-controller.log`
    - `logs/cattle-fleet-system/gitjob-<randomID>/gitjob.log`
