### ISSUE TITLE
[BUG] IP Address Not Populating On "Basics" Section of VM

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2300]
**Describe the bug**
The IPv4 Address doesn't populate on the basics section of the VM yet it's the MAC address has received an IPv4 Address

**To Reproduce**
1.  Using Ubuntu Server 22.04 Image, upload image
2.  Create a VLAN Network for the VM
3.  Install VM from .iso to a disk that's mounted
4.  Shutdown VM, remove .iso based mount
5.  Power back up VM 

**Expected behavior**
Would expect the IPv4 address to be populated out to the "Basics" section of the VM in Harvester GUI.

**Support bundle**
[supportbundle_3fe19489-485c-4e96-b4cb-b89709a476f0_2022-05-20T18-24-23Z.zip](https://github.com/harvester/harvester/files/8743274/supportbundle_3fe19489-485c-4e96-b4cb-b89709a476f0_2022-05-20T18-24-23Z.zip)

**Environment**
 - Harvester ISO version: v1.0.2
 - **Bare Metal Single Harvester Node:**
  - SuperMicro Board: [2 Intel Xeon Processors, 32 Cores In Total](https://www.supermicro.com/products/motherboard/Xeon/C600/X9DRD-iT_.cfm)
  - SuperMicro RAM: 64GB DDR3 ECC
  - 2 1TB SATA6 SSDS
  - Ethernet:
    - Failover-2Port-10GiB NIC Card
    - 4 Port, 1GiB NIC Card
 
**Additional context**
![ip_address_not_showing](https://user-images.githubusercontent.com/5370752/169590884-5fed2b18-c98e-4cc7-b5ce-83cc4682ee29.png)

**Comment by irishgordo** [comment]
Oh!
So sorry for the spam!
Realized `qemu-guest-agent` needed to be installed in order for all that information to be filled in.
![had_to_install_qemu_guest_agent](https://user-images.githubusercontent.com/5370752/169591529-1de735f5-bb53-4856-a10f-dc48e5e6c0db.png)

Once `qemu-guest-agent` was installed IPv4 address was populated and everything else :smile:

**Comment by w13915984028** [comment]
@irishgordo  Wonderful!

Is https://github.com/harvester/harvester/issues/2188 also caused by this ?  
cc @WuJun2016

**Comment by irishgordo** [comment]
@w13915984028 - #2188 seems similar - it may be caused by not having `qemu-guest-agent` installed and started via `systemctl` :smile:

**Comment by qing-geng** [comment]
may i ask how to install it

**Comment by WuJun2016** [comment]
> may i ask how to install it

Are you asking how to install qemu-guest-agent?

https://docs.harvesterhci.io/v1.1/vm/create-vm

**Comment by qing-geng** [comment]
> > may i ask how to install it
> 
> Are you asking how to install qemu-guest-agent?
> 
> https://docs.harvesterhci.io/v1.1/vm/create-vm

thank you ， here is ok


Do I need to input any commands in the virtual machine

**Comment by WuJun2016** [comment]
> > > may i ask how to install it
> > 
> > 
> > Are you asking how to install qemu-guest-agent?
> > https://docs.harvesterhci.io/v1.1/vm/create-vm
> 
> thank you ， here is ok
> 
> Do I need to input any commands in the virtual machine

No

**Comment by qing-geng** [comment]
> > > > may i ask how to install it
> > > 
> > > 
> > > Are you asking how to install qemu-guest-agent?
> > > https://docs.harvesterhci.io/v1.1/vm/create-vm
> > 
> > 
> > thank you ， here is ok
> > Do I need to input any commands in the virtual machine
> 
> No

Okay, thank you
