### ISSUE TITLE
[Feature] Enabling and Tuning KSM

### ISSUE THREAD

**Issue by unnamedjk** [harvester/harvester#2302]
I have been going through the OS vonfig and noticed the KSM is not enabled as well as any configurations for zswap.

Is there a branch or FR for including these configurations as part of the harvester deployment?

KSM has been a long standing industry standard for improving density in HCI deployments with VMware.

**Comment by ibrokethecloud** [comment]
@guangbochen we should try benchmarking harvester build with these changes.

**Comment by guangbochen** [comment]
Yes, I think we can start with benchmarking the [KSM config](https://www.linux-kvm.org/page/KSM) first and add related monitoring metrics to it. This issue can be tracked via the epic issue https://github.com/harvester/harvester/issues/1899, any additional concerns @chrisho @bk201? thanks.

**Comment by bk201** [comment]
@guangbochen no objection. Benchmark is needed and perhaps we need to pre-allocate some CPU resources for ksmd.

**Comment by lanfon72** [comment]
Verified this feature not fully implemented.

Ksmtuned enabled but still in `Stopped` phase.
![image](https://user-images.githubusercontent.com/5169694/192497518-9f9f9afd-8597-4168-8f54-ae56a4daf916.png)
![image](https://user-images.githubusercontent.com/5169694/192497413-fb51bcea-9c70-4f85-9c5a-fa5be6d23743.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-af5215bb-head** (the version after `rc1`, also tested on `rc1` with baremetals)
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard and Navigate to hosts
3. Edit _node1_'s **Ksmtuned** to `Run` and Click **Save**
4. Login to _node1_'s console, execute `kubectl get ksmtuned -oyaml --field-selector metadata.name=<node1>`
5. Fields in `spec` should be the same as Dashboard configured
6. Execute `cat /sys/kernel/mm/ksm/run` should display `1`

**Comment by lanfon72** [comment]
The value of `/sys/kernel/mm/ksm/run` will entering `1` then be updated to `0` in few seconds

**Comment by chrisho** [comment]
Each period is 1 minute, so if you want to see the statistics,  wait at least 2 minutes.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **Baremetal DL360G9 4 nodes**
* Harvester Version: **v1.1.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard and Navigate to hosts
3. Edit _node1_'s **Ksmtuned** to `Run` and **ThresCoef** to `85` then Click **Save**
4. Login to _node1_'s console, execute `kubectl get ksmtuned -oyaml --field-selector metadata.name=<node1>`
5. Fields in `spec` should be the same as Dashboard configured
6. Create an image for VM creation
7. Create multiple VMs with 2Gi+ memory and schedule on `<node1>` (memory size reflect to <node1>'s maximum size, total of VMs' memory should greater than 40%) 
8. Execute `watch -n1 grep . /sys/kernel/mm/ksm/*` to monitor ksm's status change
    - `/sys/kernel/mm/ksm/run` should be update to `1` after VMs started
    - `/sys/kernel/mm/ksm/page_*` should updating continuously
9. Login to Dashboard then navigate to _Hosts_, click <node1>
10. In the Tab of **Ksmtuned**, values in Statistics section should not be `0`.  (data in this section will be updated per min, so it not equals to console's output was expected.)
11. Stop all VMs scheduling to `<node1>`, the monitor data `/sys/kernel/mm/ksm/run` should be update to `0` (this is expected as it is designed to dynamically spawn ksm up when `ThresCoef` hits)
12. Update <node1>'s **Ksmtuned** to `Run: Prune`
13. Monitor data in Step.8 should reflect to:
    - `/sys/kernel/mm/ksm/run` should be update to `2`
    - `/sys/kernel/mm/ksm/pages_*` should be update to `0`
14. Update <node1>'s **Ksmtuned** to `Run: Stop`
15. Monitor data in Step.8 should reflect to:
    - `/sys/kernel/mm/ksm/run` should be update to `0`
