### ISSUE TITLE
[Task] Migrate Harvester documents to Docsaurus

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#2307]
As part of the effort to use Docsaurus for documentation, we want to migrate Harvester documents from the legacy framework to Docsaurus.

**Comment by guangbochen** [comment]
some related discussion on https://github.com/harvester/docs/pull/148, also the Docsaurus code repo is on https://github.com/harvester/harvesterhci.io.

**Comment by divya-mohan0209** [comment]
Thank you @rebeccazzzz for the tag. I shall be checking with @nunix and commencing work on this shortly!

**Comment by guangbochen** [comment]
close as the doc is migrated and available at https://docs.harvesterhci.io/
