### ISSUE TITLE
[BUG] Cluster member and cluster owner see inconsistent statistics

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2310]
**Describe the bug**

cluster owner:
![image](https://user-images.githubusercontent.com/24985926/169994337-00ed7ab8-4acf-41bd-8930-2d32347efb48.png)
![image](https://user-images.githubusercontent.com/24985926/169994374-c49e8999-5cda-4833-89de-9df498023897.png)

cluster member:
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/24985926/169994497-4f3efca5-f067-496f-87a4-e55bc4f28cb3.png">
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/24985926/169994541-aad53650-c713-403c-aeb1-876d22fedb6d.png">

**To Reproduce**
1. Create two users and assign cluster member and cluster owner privileges respectively
2. go to harvester, View CPU, Memory, Storage statistics

**Expected behavior**

expect to see consistent statistics

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by n313893254** [comment]
Notice that the rancher cluster shows statistics using `status.requested` of the crd `management.cattle.io.cluster`. Which API endpoint is `/v1/management.cattle.io.clusters/[CLUSTER_ID]`

But for the Harvester cluster, the `status.requested` is zero, Cloud we return the CPU and memory data as the Rancher cluster like?

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/0f9600e4-6ffe-440c-91ff-5c624ee71790)

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/31671732-3265-4c9d-b6c6-00965d35ed34)

**Comment by TachunLin** [comment]
Verified **not fixed** on `master-8f01b558-head` with Rancher `v2.6.6`. Move this issue to implement stage.

ui-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html
version: index.8caabe861906430877bf.js

### Result
The `cluster_member` rule can't see the correct resource usage statistics on host and dashboard page
Most of the statistics are empty. 

* Dashboard page of cluster_owner
![image](https://user-images.githubusercontent.com/29251855/179163953-bcde4607-ca0a-4a01-aed1-38c47a94b710.png)

* Dashboard page of cluster_member
![image](https://user-images.githubusercontent.com/29251855/179164336-a727deb3-38fc-4476-939b-644696d1b1f7.png)

* Host page of cluster_owner
![image](https://user-images.githubusercontent.com/29251855/179164025-c5c7c97b-f2f5-452a-bc1d-f64e159d8d1b.png)

* Host page of cluster_member
![image](https://user-images.githubusercontent.com/29251855/179164190-799f2c99-2622-4d73-ae2a-2a9ad11a41f0.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-8f01b558-head
* Rancher version: v2.6.6

### Verify Steps

1. Create two users and assign cluster member and cluster owner privileges respectively
2. Login with cluster member and owner 
3. Go to harvester, View CPU, Memory, Storage statistics in host and dashboard page

**Comment by TachunLin** [comment]
Re-validate **fixed** on `master-8f01b558-head` with Rancher `v2.6.6`. Close this issue to implement stage.

Should use master ui-index for testing
ui-index: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html

### Result
The `cluster_member` rule can see the resource usage statistics on host and dashboard page
Since the member privilege can't access longhorn storage, thus the storage already been hided on these pages

* Dashboard page of cluster_member
  ![image](https://user-images.githubusercontent.com/29251855/179201640-b4e5dcf6-bde2-4474-b9ef-792138f49eb4.png)

* Host page of cluster_member
  ![image](https://user-images.githubusercontent.com/29251855/179201686-f4540046-292e-4cb8-ab59-4774e2519830.png)
