### ISSUE TITLE
[FEATURE] Visibility into bare metal node hardware / hardware error detection

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#2318]
**Is your feature request related to a problem? Please describe.**
Running on the bare metal, it's necessary to know the hardware condition. Hardware like disks might fail and require replacement. It's necessary to see the hardware condition directly in the Harvester UI. 

**Describe the solution you'd like**
Detect and show node hardware condition in the Harvester UI.

**Describe alternatives you've considered**
Setup third party software to achieve the same result

**Additional context**
Might be able to use projects below:
https://github.com/bmc-toolbox/bmclib
https://github.com/tinkerbell/rufio

**Comment by guangbochen** [comment]
@ibrokethecloud can u please help to explain a little bit how the seeder chart integration will address the node visibility feature, thanks.

**Comment by albinsun** [comment]
Hi @n313893254  and @ibrokethecloud 
Do we have document for this? or could you provide how seeder addon address the node visibility feature works?
It will surely helps testing and futher development.

**Comment by ibrokethecloud** [comment]
## Test plan
The hardware discovery feature is only supported for underlying hardware supporting redfish, as we leverage the redfish api to query hardware information.

To leverage this feature, `harvester-seeder` addon needs to be enabled. 

Once enabled, users can configure `Out-of-Band Access` for node and map the corresponding underlying hardware to the node.

![image](https://github.com/harvester/harvester/assets/19664014/a6224770-3100-449a-9007-66c8caa6f5ae)

Please ensure `Events` are enabled.

seeder will now start performing the following:

* query the underyling hardware for information such as manufacturer, model and serial number. these will now be added to the k8s node object and will show up in. the UI as follows:
![image](https://github.com/harvester/harvester/assets/19664014/ccf61d97-6479-49d7-8790-2e12072cb4e9)

* query the underyling hardware for the following system information:
  - thermal health
  - drive health
  - power supply health
  - network adapter health
  - pcidevice health
  - cpu health
  - memory health
 
If any of these objects are unhealthy a k8s event is generated and associated with the correct node. This shows up in the harvester UI under host health.

Fan temperatures are always reported, while hardware failure is only reported if something is detected as being unhealthy.

![image](https://github.com/harvester/harvester/assets/19664014/0045366c-3103-4d06-8d09-c88f6c1da629)

**Comment by albinsun** [comment]
Provide test result for `v1.2.0-rc3`.

For addon enable, works fine if enable via settings page.
But if enable via link, it shows "This page could not be found".
Please help to check

For addon config, invalid "Polling Interval" seems not leads error, is this expected?


## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: QEMU/KVM, single node (48C/128G/1T)
  * **ui-source**: Auto

## Support Bundle
[supportbundle_2de3452d-1525-42a3-919e-47bc13d58ff7_2023-07-20T05-20-21Z.zip](https://github.com/harvester/harvester/files/12102293/supportbundle_2de3452d-1525-42a3-919e-47bc13d58ff7_2023-07-20T05-20-21Z.zip)

## Test Cases
> **Note** Click "►" to expand details.
### Positive TC
1. Enable **harvester-seeder** addon via Settings $~~$ $\color{green}{\textsf{PASS}}$
   1. <details><summary>Go to 'Advanced' -> 'Addons' -> 'harvester-seeder', Enable </summary>
        
      ![image](https://github.com/harvester/harvester/assets/2773781/450af6bd-2fad-436c-8e84-51efab494e2e)

      </details>
   1. <details><summary>Should Enabled and DeploySuccessful $~~$ :heavy_check_mark: </summary>
        
      ![image](https://github.com/harvester/harvester/assets/2773781/9c8f3497-a81f-46b2-a99a-efdf43993809)

      </details>


1. Enable **harvester-seeder** addon via tips on Host $~~$ $\color{red}{\textsf{FAIL}}$
   1. Disable **harvester-seeder**
   1. <details><summary>Go to 'Hosts' -> host entry -> 'Config' -> 'Out-of-Band Access', enable via "click here" in tip </summary>
        
      ![image](https://github.com/harvester/harvester/assets/2773781/209c4b01-9833-42a6-b399-f42aa0af2972)

      </details>
   1. <details open><summary>Should enable or go to enable page $~~$ :x: $\color{red}{\textsf{Show "This page could not be found"}}$</summary>   
      
      ![image](https://github.com/harvester/harvester/assets/2773781/3a5c5c89-214d-4539-9580-b8668148b3cb)

      </details>


1. Enable **Out-of-Band Access** on host with valid parameters $~~$ $\color{green}{\textsf{PASS}}$
   1. <details><summary>Enable harvester-seeder on host</summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/e529f2d1-ca80-4f24-ac0b-b61bac0b72bc)

      </details>
   1. Wait about 5 mins
   1. <details><summary>Related host lables are shown $~~$ :heavy_check_mark: </summary>
      
      ![image](https://github.com/harvester/harvester/assets/2773781/3ad42c9b-2511-4023-9daa-a4ca7510aabb)

      </details>
   1. <details><summary>Related events are shown $~~$ :heavy_check_mark:</summary>
      
      On Host
      ![image](https://github.com/harvester/harvester/assets/2773781/b1cadcef-db5b-4408-91e2-76fe40dc54e3)
      On Dashboard
      ![image](https://github.com/harvester/harvester/assets/2773781/ba7b4598-4506-48cf-8ca4-bd7a3931bacd)

      </details>


### Negtive TCs
1. Enable **harvester-seeder** on host with invalid host $~~$ $\color{green}{\textsf{PASS}}$
   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid host "no.such.host.perhaps"
   1. <details><summary>Should be error when or after save $~~$ :heavy_check_mark: </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/fb1dd939-f500-4cfd-bfe9-b98a385f5110)

      </details>


1. Enable **harvester-seeder** on host with invalid string port $~~$ $\color{green}{\textsf{PASS}}$
   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid port "NoSuchPort"
   1. <details><summary>Should be error when or after save $~~$ :heavy_check_mark: </summary>
      
      ![image](https://github.com/harvester/harvester/assets/2773781/12c620e8-cf42-45db-8192-09d5a3c666c0)

      </details>


1. Enable **harvester-seeder** on host with invalid number port $~~$ $\color{green}{\textsf{PASS}}$
   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid port "12345"
   1. <details><summary>Should be error when or after save $~~$ :heavy_check_mark: </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/c80abd89-b2b2-41bb-8f1e-a869f1c4bea8)

      </details>


1. Enable **harvester-seeder** on host with wrong credential $~~$ $\color{green}{\textsf{PASS}}$
   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with wrong credential
   1. <details><summary>Should be error when or after save $~~$ :heavy_check_mark: </summary>
      
      ![image](https://github.com/harvester/harvester/assets/2773781/6c60b75f-4ce6-4020-b6f5-269f60c4d873)

      </details>


1. Enable **harvester-seeder** on host with invalid polling interval $~~$ $\color{red}{\textsf{FAIL}}$
   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid polling interval "NoSuchInterval"
   1. <details open><summary>Should be error when or after save $~~$ :x: $\color{red}{\textsf{No error when/after save}}$ </summary>
          
      ![image](https://github.com/harvester/harvester/assets/2773781/fda3d202-fa80-48d5-b060-1341c4e9a498)

      </details>

**Comment by ibrokethecloud** [comment]
Newest image contains additional validation on the Interval field to ensure that its of type duration:

![image](https://github.com/harvester/harvester/assets/19664014/678e0ec7-c323-44f8-b80f-e9a3d6329771)

Associated PR: https://github.com/harvester/seeder/pull/18

**Comment by albinsun** [comment]
Thanks, will test in next release.

**Comment by albinsun** [comment]
Tested in `v1.2-37aeb5ff-head`, close as done.

Still an UI issue, trace by [harvester#4302](https://github.com/harvester/harvester/issues/4302)

## Test Environment
* Harvester
  * version: `v1.2-37aeb5ff-head`
  * profile: QEMU/KVM, 3 nodes (48C/128G/1T)
  * **ui-source**: Auto


## Test Cases
> **Note** Click "►" to expand details.

### Positive TC
1. <details>
   <summary>
   Enable harvester-seeder addon via Settings $~~$ :heavy_check_mark:
   </summary>
   
   1. Go to 'Advanced' -> 'Addons' -> 'harvester-seeder', Enable
   1. Should Enabled and DeploySuccessful
      ![image](https://github.com/harvester/harvester/assets/2773781/6ddcbdf3-9aa6-467f-b71c-63a87c757ca2)

   </details>


1. <details>
   <summary>
   Enable harvester-seeder addon via tips on Host $~~$ :heavy_check_mark: 
   </summary>

   1. Disable **harvester-seeder**
   1. Go to 'Hosts' -> host entry -> 'Config' -> 'Out-of-Band Access', enable via "click here" in tip 
      ![image](https://github.com/harvester/harvester/assets/2773781/1f86b071-247a-4fbe-919d-1d5510885b2b)

   1. Should enable or go to enable page
      ![image](https://github.com/harvester/harvester/assets/2773781/8278e227-9dd1-4e8d-9b48-b93194a0b330)

   1. Enable, and should be DeploySuccessful
      ![image](https://github.com/harvester/harvester/assets/2773781/db6c4c8b-46d0-41e0-9b16-13ab4fdbb8ca)

   </details>


1. <details>
   <summary>
   Enable Out-of-Band Access on host with valid parameters $~~$ :heavy_check_mark: 
   </summary>

   1. Enable harvester-seeder on host
   1. Wait about 5 mins
   1. Related host lables are shown
      ![image](https://github.com/harvester/harvester/assets/2773781/cb396a00-d6dd-4957-87eb-e137f7293652)

   1. Related events are shown
      On Host
      ![image](https://github.com/harvester/harvester/assets/2773781/d8f26c15-8901-4f93-9b63-1b1b3b0a0b1b)
      On Dashboard
      ![image](https://github.com/harvester/harvester/assets/2773781/e6023d8c-315c-4d00-bba2-5a6289e482f2)

   </details>


### Negtive TCs
1. <details>
   <summary>
   Enable harvester-seeder on host with invalid host $~~$ :heavy_check_mark: 
   </summary>

   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid host "no.such.host.perhaps"
   1. Should be error when or after save
      ![image](https://github.com/harvester/harvester/assets/2773781/fc19f294-93ef-4e6c-b346-43e99b4656aa)

   </details>


1. <details>
   <summary>
   Enable harvester-seeder on host with invalid string port :heavy_check_mark:
   </summary>

   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid port "NoSuchPort"
   1. Should be error when or after save $~~$ :heavy_check_mark: 
      ![image](https://github.com/harvester/harvester/assets/2773781/3ea24810-7483-4fdc-b0c6-7f1304c438e2)

   </details>
   
   > **Note**
   > Extend issue: https://github.com/harvester/harvester/issues/4302


1. <details>
   <summary>
   Enable harvester-seeder on host with invalid number port :heavy_check_mark:
   </summary>

   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid port "12345"
   1. Should be error when or after save
      ![image](https://github.com/harvester/harvester/assets/2773781/a575812d-c27d-478d-adaa-e629f171d9c5)

   </details>


1. <details>
   <summary>
   Enable harvester-seeder on host with wrong credential $~~$ :heavy_check_mark: 
   </summary>

   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with wrong credential
   1. Should be error when or after save
      ![image](https://github.com/harvester/harvester/assets/2773781/7e3ee026-236b-4092-837d-5addc6e898dc)

   </details>


1. <details>
   <summary>
   Enable harvester-seeder on host with invalid polling interval $~~$ :heavy_check_mark: 
   </summary>

   1. Disable Out-of-Band Access
   1. Enable Out-of-Band Access on host with invalid polling interval "NoSuchInterval"
   1. Should be error when or after save
      ![image](https://github.com/harvester/harvester/assets/2773781/cba14347-9e41-4db3-b531-22cd55766e67)

   </details>
