### ISSUE TITLE
[FEATURE] Image filtering by labels

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#2319]
**Request description:**

When an image is created in Harvester, labels can be attached to it. However these labels are nowhere to be seen.

We'd like to use labels to filter images for a better image management. Also it would help to have such label accessible during VM creation process or in a template.

Goal is to mark some images as "latest" or "prod" instead of scrolling through a long drop-down list of images created on a daily basis.

**Actual behavior:**

All images are shown by name only. With large amount of images filtering or selecting in drop down can become problematic

**Expected behavior:**

Images should be filtered by labels.

During VM creation or within a template it should be possible to enter image label instead of name, ideally combining them like "ubuntu" "latest"

**Workaround:**

There is no workaround atm

**Additional notes:**

With images produced daily by automation tools the image section can be populated with hundreds of images soon. It is not easy to manage it then but it's even more challenging to pick the right image during VM creation. We would also like to use templates where addressing images by labels instead of a name would be beneficial.

**Comment by kwwii** [comment]
I have been working on UX patterns for filtering, labeling, and tables recently. This sounds very similar, which makes me wonder how we could use some of the work I've been doing to help here.

**Comment by WuJun2016** [comment]
The user has a requirement that the user will build an image every day, with a name format like "20220601-Ubuntu. imag", so we want the user to be able to not only search the image in the input box, but also sort the large number of images that are found.
Hi, @kwwii  Do you have any design suggestions?  thanks a lot.

![image](https://user-images.githubusercontent.com/24985926/174565002-499dfd54-99bb-4d8e-ab84-72bb494fdf12.png)

<img width="600" alt="image" src="https://user-images.githubusercontent.com/24985926/174567303-ec8a74cd-eda8-4254-9933-98cc50532560.png">

**Comment by kwwii** [comment]
The user can already add labels when creating the image.

The table with the image list could display these labels by adding a column titled "Labels" with a comma separated list of labels. The filter would also filter for the labels in this new column.

Note that the table currently already shows a column "Age", so ordering the table by the Age column should also help to identify the latest image.

Additionally, we could order the list in the dropdown by Age instead of Alphabetically. I do not think that adding a switch to change the order of the drop-down is going to work well, and would need to be tested as it might have a negative effect on usability/accessibility. 

The dropdown image suggested above will not work, as the space at top right of every input is reserved for the new field validation.

**Comment by WuJun2016** [comment]
FYI：
In order to be consistent with the style of the rancher 2.7.0 component, we need to modify the design in harvester 1.1.0.

**Comment by TachunLin** [comment]
Verified on `master-779c1585-head` (09/14) with Rancher v2.6.8. 

### Result
Pass the following image filter scenarios

- [x] **PASS** Filter label in Harvester images page 
- [x] **PASS** Sort and search image in the VM creation page 
- [x] **PASS** Sort and search image in the create RKE2 page (multi cluster) 

#### Case 1:
The image list page can be filtered by label in the following cases

* All image list without filter, image list by created time
 ![image](https://user-images.githubusercontent.com/29251855/190093902-3b9f2627-cd85-49af-8dc6-07f934143297.png)

1. One key, no value 
  ![image](https://user-images.githubusercontent.com/29251855/190094849-d24061b6-c682-428f-b58e-7d9745c75da4.png)

2. One key with value 
  ![image](https://user-images.githubusercontent.com/29251855/190094975-7bb648f3-096a-45f9-ad18-fb5313ac8d1d.png)

3. Two keys, no value
  ![image](https://user-images.githubusercontent.com/29251855/190095123-2b05a1a3-90c2-448b-9223-46855c35e8c6.png)

4. Two keys, one key have no value
  ![image](https://user-images.githubusercontent.com/29251855/190095239-2e77e399-8b75-45ed-9ae6-74bb6fe0197c.png)

5. Two keys with values
  ![image](https://user-images.githubusercontent.com/29251855/190095348-0a4bf56b-4735-4ccf-b54b-77f67fdcaa26.png)

#### Case 2:
In the VM creation page, 
* Image are lists according to the added time
  ![image](https://user-images.githubusercontent.com/29251855/190096010-2aff9cef-d1c3-430e-a2bd-7552051e8a62.png)

* Can search specific image by name
  ![image](https://user-images.githubusercontent.com/29251855/190096119-d5d9ef5a-b035-4646-82fa-f366050a1163.png)

#### Case 3:
In the provision RKE2 cluster page, 
* Image are lists according to the added time
  ![image](https://user-images.githubusercontent.com/29251855/190097495-4645830d-c943-41f7-b449-1a59d86bb587.png)

* Can search specific image by name
 ![image](https://user-images.githubusercontent.com/29251855/190097577-c42b6602-4ac0-4956-9da8-5a7227ffee0b.png)

### Test Information
* Test Environment: 1 node harvester on local kvm
* Harvester version: `master-779c1585-head` (09/14)
* Rancher version: v2.6.8

### Verify Steps
1. Upload several images and add related label
2. Go to the image list page 
3. Add filter according to test plan 1
4. Go to VM creation page 
5. Check the image list and search by name
6. Import Harvester in Rancher
7. Go to cluster management page
8. Create a RKE2 cluster 
9. Check the image list and search by name

**Comment by TachunLin** [comment]
During the test, I noticed when we have some search filters and click the `Clear All` button 
![image](https://user-images.githubusercontent.com/29251855/190102053-7c765b9c-a57f-4b75-a90c-3e4939161d42.png)

The the search result can't restore to display all items 
![image](https://user-images.githubusercontent.com/29251855/190102095-5d34807d-1a04-4ab4-8795-5118f11e3395.png)

We need to re-enter the images page again or click the add button to restore all image lists
  ![image](https://user-images.githubusercontent.com/29251855/190102329-11c55154-7381-46d3-9686-1dac685eb237.png)
  ![image](https://user-images.githubusercontent.com/29251855/190102431-b20e2789-5c69-4475-a8ad-605f36bd6d8b.png)

Suggest can improve the clear all button behavior. Thus move issue to implement stage.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-3bcba9d3-head` (09/16). Close this issue.

### Result
Now when we click the `Clear All` button, all filter label will be cleaned up and restore all the image item lists 
![image](https://user-images.githubusercontent.com/29251855/190657534-846723a4-238d-46bc-910e-eb0f2bb7388c.png)

https://user-images.githubusercontent.com/29251855/190658054-bbba4163-df45-4730-9113-b8e85225d95a.mp4

### Test Information
* Test Environment: 1 nodes Harvester on local kvm machine
* Harvester version: master-3bcba9d3-head

### Verify Steps
1. Upload several images and add related label
2. Go to the image list page
3. Add filter according to test plan 1
4. Go to VM creation page
5. Check the image list and search by name
6. Click the `Clear All` button
7. Check the image item lists
