### ISSUE TITLE
Some fields seem incorrect and the table header layout needs to adjust on the VM detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#232]
**Steps to reproduce:**
1. Create a VM selecting a ubuntu OS
2. Check on the detail page

**Result:**
1. `Operating System `and `Time Zone` are populated with `Guest agent required`, are these expected?
2. The tables are not in the same header layout
![image](https://user-images.githubusercontent.com/57614736/98753757-0eb0cd80-2400-11eb-8f2d-d0b534e4c078.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/205
