### ISSUE TITLE
[FEATURE] Distribute disk volume replicas across zones

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2323]
Harvester should support setting soft and hard anti-affinity to distribute disk volume replicas across zones defined with the well-known node label `topology.kubernetes.io/zone` 

https://longhorn.io/docs/1.2.4/references/settings/#replica-zone-level-soft-anti-affinity

**Comment by yasker** [comment]
It's automatically done via Longhorn soft anti-affinity across zones. https://longhorn.io/docs/1.2.4/references/settings/#replica-zone-level-soft-anti-affinity

The user needs to add label to the node, and Longhorn will do the right thing automatically.

**Comment by votdev** [comment]
@janeczku Could you please go into detail what you want to see here? E.g. by describing the expected workflow.

Are you talking about setting `topology.kubernetes.io/zone=xyz` on the Harvester UI? This is already handled correctly, see the attached video.

[Bildschirmaufzeichnung vom 2024-05-27, 13-05-12.webm](https://github.com/harvester/harvester/assets/1897962/e577693b-9529-4408-86c6-ee3306aaa82a)

**Comment by bk201** [comment]
@votdev If the feature works, can we have a document and close the issue?

**Comment by brandboat** [comment]
Test OK, will close the issue

# Environment
- ipxe 3 nodes (8c/16G/250GB)
- 1.4.0-rc3

# Test Plan
Setup 3 nodes harvester, all nodes are in 2 different zones `z1`, `z2`. Then create a 2 replica storage class, and create a volume using the SC and check if LH correctly scheduled all replicas to different zones.

<details>
  <summary>Set LH `Replica Zone Level Soft Anti-Affinity` to `false` (<s>force LH to schedule replicas to different zones</s> not required, no need to set to false)</summary>

  ![image](https://github.com/user-attachments/assets/25e55783-1104-4abd-99eb-a3d5871fb699)
</details>

<details>
  <summary>Set harvester-node-0, harvester-node-1 to zone `z2`, harvester-node-2 to `z1`</summary>

  <img width="1480" alt="image" src="https://github.com/user-attachments/assets/dd491865-e41c-4f81-9747-61abbeaafc27">
</details>

<details>
  <summary>Create a storage class which replica count is 2</summary>

  ![image](https://github.com/user-attachments/assets/4f808d11-e0b3-403d-94b8-6cc9f18e1994)
</details>

<details>
  <summary>Create a volume `test` and attach the volume to a VM (make LH replica in running state)</summary>

  ![image](https://github.com/user-attachments/assets/4e69f57a-584f-45cf-9d05-1a816c632adb)
  ![image](https://github.com/user-attachments/assets/4b13f655-d28f-4668-b150-bd381d0d7c4d)
</details>

<details>
  <summary>Validate the replicas are in different zones (harvester-node-0 -> z2, harvester-node-2 -> z1)</summary>

  ![image](https://github.com/user-attachments/assets/47d0ed50-27c5-4de6-9e82-b35969b711e9)
</details>

<details>
  <summary>Set LH `Replica Auto Balance` to `best-effort` (default is disabled, which doesn't rebalance replicas on the fly)</summary>

  ![image](https://github.com/user-attachments/assets/9808c1c2-bfc5-41ff-a479-58e913ce175a)
</details>

<details>
  <summary>Set harvester-node-0 to `z1` (now harvester-node-0, harvester-node-2 are in zone `z1`, harvester-node-1 is in zone `z2`)</summary>

  <img width="1485" alt="image" src="https://github.com/user-attachments/assets/7bbb4afd-0f75-4620-a231-262e0bf7ef5f">
</details>

<details>
  <summary>Validate the replicas are rebalanced to different zones (harvester-node-0 -> z1, harvester-node-1 -> z2)</summary>

  ![image](https://github.com/user-attachments/assets/7ecdcf7c-3af9-43fe-8782-b5779f5116ef)
</details>

**Comment by brandboat** [comment]
~~During the test, I realized that to force all disk volume replicas placed in different zones. We also need to disable `Replica Zone Level Soft Anti-Affinity` setting in LH side, but the doc doesn't mention that. [topology-spread-constraints](https://docs.harvesterhci.io/v1.3/host/#topology-spread-constraints). Not sure if this is a problem.~~ (please check https://github.com/harvester/harvester/issues/2323#issuecomment-2431672417)
c.c. @votdev , @bk201 , @WebberHuang1118

**Comment by WebberHuang1118** [comment]
Had a discussion with @brandboat, and we found:
- The zone label only affects replica distribution during volume creation
- If the volume already has enough replicas, applying the different zone labels will not affect the replica distribution

Maybe we can also mention this on [topology-spread-constraints](https://docs.harvesterhci.io/v1.3/host/#topology-spread-constraints)

**Comment by brandboat** [comment]
I checked again and found that setting `Replica Zone Level Soft Anti-Affinity` to true also make Longhorn to schedule replicas in different zones.

On the other hand, setting it to false prevents more than one replica from being scheduled in the same zone. As a result, if the zone count is less than the replica count, setting this to false will lead to degraded volumes.
