### ISSUE TITLE
[FEATURE] Auto-detect and allow static configuration of NICs for MGMT and VIP with ISO install

### ISSUE THREAD

**Issue by axsms** [harvester/harvester#2330]
**Is your feature request related to a problem? Please describe.**
NIC configuration at remote hosting providers can be a challenge when neither VLAN or DHCP is available.

**Describe the solution you'd like**
Allowing static IP configuration of both MGMT and VIP at initial setup during ISO installations and autodetect Up status for connected devices, even if DHCP not available.

**Describe alternatives you've considered**
Adding an external DHCP server — Adds expense and complexity. This also may not be reasonable when bare-metal options with the provider are limited. E.g., my main provider offers no VMs and no physical servers with less than 2 CPUs and 128GB ram. This would be a horrible waste of resources for a simple DHCP requirement.

Nested Virtualization — Adds unnecessary complexity. Install a hypervisor, then install a DHCP server and Harvester on top. This may be a good option to test drive Harvester, but not for production.

**Additional context**
I know we could create a custom config and upload it during ISO install, but this would be easier. Further, since I see lots of confusion in Slack about networking, I believe it would improve user adoption. Especially for sys admins that are used to setting up other hypervisors with a similar feature available to them.

**Comment by yasker** [comment]
@axsgitty , Static IP is supported during installation. You will need to manually configure it. Have you encountered a problem with the feature?

**Comment by axsms** [comment]
I think I may have been confused. I was wanting to configure two different static IPs. One for MGMT and another for VIP. Environment being two NICs, no DHCP, upstream switch is not VLAN aware.

**Comment by ibrokethecloud** [comment]
@axsgitty using something like this in the config.yaml you should be able to assign static addresses for both interfaces.

The same should also be possible via the installer UI.

```
install:
  mode: create
  automatic: true
  debug: true
  device: /dev/sda
  iso_url: http://172.16.135.50:8080/harvester-v1.0.2-amd64.iso
  poweroff: false
  vip: 172.16.128.12
  vip_mode: static
  networks:
    harvester-mgmt:
      interfaces:
      - hwAddr: '0c:c4:7a:6b:84:20'
      default_route: true
      method: static
      ip: 172.16.128.7
      subnetMask: 255.255.255.0
      gateway: 172.16.128.1
      bond_options:
        mode: balance-tlb
        miimon: 100
```

**Comment by axsms** [comment]
Thank you for that example, that is a helpful example config to do what we are wanting to do and can in many situations. 

It looks like I may be trying to force a specific use case a little too hard. So, I am going to back away from the use case and develop our requirements to accommodate either using a custom yaml or having DHCP and VLAN aware switch in the DCs we target for edge/regional use.

To perhaps provide a better explanation of the use case we had in mind, below are the parameters we often find ourselves in. Context is that we are a managed services provider (MSP) of IT services. We are looking to expand our ability to support clients with both legacy and modern apps and infrastructure requirements. We have been supporting traditional infrastructure for over 20 years and attempting to modernize our own ways of doing things. So, we bring our own learning curve to the table, which is probably obvious to many reading my questions here and on slack. 

Typical scenario: Client is moving offices or going full remote, they have a lot of investment in infrastructure in an onsite datacenter and either want to move their services fully to the cloud or to a new site or colo site or a combination of any of these. 

Often the only reason a client needs any servers on site is for legacy apps and Active Directory. So, we want to offer them options in remote datacenters. Some colo situations have longer lead times than we can provide, and clients often have limited budgets that put cloud services out of reach. So, we want to have the option to go to companies like hivelocity, purevoltage, serverdime, or some other providers of baremetal to deploy Harvester and handle the legacy and modern apps at a fraction of the cost of other options. 

The main issues I am seeing is that we have to deploy extra servers, switches, and firewalls at each DC to mimic the on prem environments we require. This increases costs and complexity to make traditional cloud and colo be more competitive. We were trying to find a way to avoid the deployment of the servers, firewalls, and switches at these no-frills (no dhcp, no vlans, small IP subnets) providers and have the speedy deployment they offer, which would help us meet the often-unreasonable timelines clients have. Perhaps there are other ways of accomplishing this that I haven't considered. 

Happy to abandon this feature request, since what I propose doesn't seem to be a common use case. Thank you for your time and efforts.

**Comment by axsms** [comment]
I believe the presented situation may be too narrow a use case.
