### ISSUE TITLE
[BUG] New install displays Rancher (rather than Harvester) login screen

### ISSUE THREAD

**Issue by gregwbrooks** [harvester/harvester#2331]
**Describe the bug**
New install of Harvester 1.0.2 via Github Releases ISO shows "Welcome to Rancher" login screen once the installation is complete. I am unclear on whether this is merely a typo (other installations did not have this issue) or something deeper. A possibly related issue: Inability to find/input bootstrap password so the initial admin password can be created.

**To Reproduce**
1. Install Harvester via ISO
2. Navigate to https://virtual-ip
3. Presented with Rancher (rather than Harvester) first-time login screen (this could just be a typo - it says "Welcome to Rancher."
4. **As an aside:** The bootstrap password that should work (both Harvester and Rancher defaults tried, as well as passwords entered during installation) fail. Documentation recommendations for recovery, including using
`kubectl get secret --namespace cattle-system bootstrap-secret -o go- template='{{.data.bootstrapPassword|base64decode|| {{"\n"}}'` do not work. In the latter case, system reports back kubectl is not installed.
 

**Expected behavior**
1. See Harvester login screen
2. Be able to create default password and log in.

**Environment**
 - Harvester ISO version: 1.0.2
 - Underlying Infrastructure: 2x Intel Deca-Core E5-2660v2 - 128GB - 480GB SSD + 2x 1TB HDD

**Additional context**
The installation was handled by a remote team at a datacenter. Although I provided very detailed installation instructions, it's possible this is tied to an installation error of some sort.

**Comment by DacoDev** [comment]
Ran into this as well, wasn't able to get past the Bootstrap Password requirement so I re-installed and it landed on the correct login screen just requiring the new password. Didn't change anything between installs at all.

**Comment by ibrokethecloud** [comment]
@gregwbrooks are you please able to provide information on where the URL redirect takes you when enter https://virtual-ip

**Comment by gregwbrooks** [comment]
Standard Rancher first-time login screen requesting bootstrap password and first-time password setup. URL looks normal for a Rancher install, but virtual IP is that if the bare-metal Harvester install.Get Outlook for Android

**Comment by ibrokethecloud** [comment]
would it be possible to see the logs for the rancher pod.

To reset the password the `kubectl` is available to the root user so you should be able to sudo and reset the password.

**Comment by gregwbrooks** [comment]
Unfortunately, no - the server had to be put into production so we wiped it and went with Proxmox to get live.I'll see if I can recreate the error on another box.Get Outlook for Android

**Comment by ibrokethecloud** [comment]
@gregwbrooks i am closing this issue for now. please feel free to reopen if you run into this again.
