### ISSUE TITLE
When adding a disk to a running VM, actually two are added

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#234]
**Steps to reproduce:**
1. Create a VM
2. Edit it as form, add a new disk to the VM, and save it

**Result:**
When adding a disk to a running VM, actually two are added
![image](https://user-images.githubusercontent.com/57614736/98793847-658bc680-2443-11eb-94d8-f95e9f910ba4.png)
![image](https://user-images.githubusercontent.com/57614736/98793911-750b0f80-2443-11eb-9ab8-c91b99e1874e.png)
![image](https://user-images.githubusercontent.com/57614736/98794037-8eac5700-2443-11eb-886d-2848c7b15992.png)

**Comment by guangbochen** [comment]
will be addressed in https://github.com/rancher/harvester-ui/pull/206

**Comment by DoNotSayYes** [comment]
Validated
