### ISSUE TITLE
[Question] Try to install OpenSuse Micro OS

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#2344]
I tried to install Open SuSe Micro OS current. My system is 8 Core Intel CPU with 32 GB Ram and I use kvm.

Harvester: 2 hosts with 8 cores, 16GB Ram and 200 GB storage each.
When I tried to install the Micro OS with 1 Core, 4 GB ram and 20 GB Storage I got this error

![grafik](https://user-images.githubusercontent.com/85644625/171401164-6ff76544-3308-4f42-926c-6969427b10ed.png)

The installer isn't able to create the needed partitions, have you some hints, where is my error

**Comment by jrlittlefoot64** [comment]
I use harvester 1.0.2 and the Mirro OS is working under kvm without problems

**Comment by ibrokethecloud** [comment]
@jrlittlefoot64 are you please able to provide more details of the Harvester VM config? The error seems to indicate that installer cant find the disk.

**Comment by jrlittlefoot64** [comment]
Here my yaml files for vm and disk

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    harvesterhci.io/imageId: default/image-jcvww
    harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/vm-01"]}]'
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2022-06-02T06:04:03Z"
  finalizers:
  - kubernetes.io/pvc-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:harvesterhci.io/imageId: {}
          f:harvesterhci.io/owned-by: {}
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: harvester
    operation: Update
    time: "2022-06-02T06:04:03Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2022-06-02T06:04:17Z"
  name: vm-01-disk-0-uxvrz
  namespace: default
  resourceVersion: "827168"
  uid: be8c38d6-2373-4efd-927d-48a6d74ce866
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-image-jcvww
  volumeMode: Block
  volumeName: pvc-be8c38d6-2373-4efd-927d-48a6d74ce866
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  phase: Bound

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    harvesterhci.io/vmRunStrategy: RerunOnFailure
    harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"vm-01-disk-0-uxvrz","annotations":{"harvesterhci.io/imageId":"default/image-jcvww"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"20Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-jcvww"}}]'
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    network.harvesterhci.io/ips: '[]'
  creationTimestamp: "2022-06-02T06:04:03Z"
  finalizers:
  - wrangler.cattle.io/VMController.UnsetOwnerOfPVCs
  generation: 2
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/os: ""
  managedFields:
  - apiVersion: kubevirt.io/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:harvesterhci.io/vmRunStrategy: {}
          f:harvesterhci.io/volumeClaimTemplates: {}
          f:network.harvesterhci.io/ips: {}
        f:finalizers:
          .: {}
          v:"wrangler.cattle.io/VMController.UnsetOwnerOfPVCs": {}
        f:labels:
          .: {}
          f:harvesterhci.io/creator: {}
          f:harvesterhci.io/os: {}
      f:spec:
        .: {}
        f:runStrategy: {}
        f:template:
          .: {}
          f:metadata:
            .: {}
            f:annotations: {}
            f:labels: {}
          f:spec:
            .: {}
            f:domain:
              .: {}
              f:cpu:
                .: {}
                f:cores: {}
                f:sockets: {}
                f:threads: {}
              f:devices:
                .: {}
                f:disks: {}
                f:inputs: {}
                f:interfaces: {}
              f:features:
                .: {}
                f:acpi:
                  .: {}
                  f:enabled: {}
              f:machine:
                .: {}
                f:type: {}
              f:resources:
                .: {}
                f:limits:
                  .: {}
                  f:cpu: {}
                  f:memory: {}
            f:evictionStrategy: {}
            f:hostname: {}
            f:networks: {}
            f:volumes: {}
    manager: harvester
    operation: Update
    time: "2022-06-02T06:04:04Z"
  - apiVersion: kubevirt.io/v1alpha3
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version: {}
          f:kubevirt.io/storage-observed-api-version: {}
      f:status:
        .: {}
        f:conditions: {}
        f:created: {}
        f:printableStatus: {}
        f:ready: {}
        f:volumeSnapshotStatuses: {}
    manager: Go-http-client
    operation: Update
    time: "2022-06-02T06:04:44Z"
  name: vm-01
  namespace: default
  resourceVersion: "827504"
  uid: 71f7246e-788a-473d-9afb-be594e1cf033
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      annotations:
        harvesterhci.io/sshNames: '[]'
      creationTimestamp: null
      labels:
        harvesterhci.io/vmName: vm-01
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: disk-0
          - disk:
              bus: virtio
            name: cloudinitdisk
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - macAddress: 52:54:00:76:84:a9
            masquerade: {}
            model: virtio
            name: default
        features:
          acpi:
            enabled: true
        machine:
          type: q35
        memory:
          guest: 3996Mi
        resources:
          limits:
            cpu: "1"
            memory: 4Gi
          requests:
            cpu: 62m
            memory: 2730Mi
      evictionStrategy: LiveMigrate
      hostname: vm-01
      networks:
      - name: default
        pod: {}
      volumes:
      - name: disk-0
        persistentVolumeClaim:
          claimName: vm-01-disk-0-uxvrz
      - cloudInitNoCloud:
          networkDataSecretRef:
            name: vm-01-tph5p
          secretRef:
            name: vm-01-tph5p
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-06-02T06:04:43Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  created: true
  printableStatus: Running
  ready: true
  volumeSnapshotStatuses:
  - enabled: true
    name: disk-0
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]

Please tell me if you need more. In the manual disk installer I see the 20 GB Disk

**Comment by aaannz** [comment]
I have the same problem. I managed to deploy one microos VM which after some time I decided to redeploy and since then I cannot create new VM. I tried both kvm and cloudinit based images.

If I drop to dracut emergency shell I can confirm that main disk is not present. Regardless if I use virtio, scsi or sata mounting, the only disk present is cloudinit disk.

**Comment by aaannz** [comment]
If I let to describe virt-launcher then I see two warnings:
```
Events:
  Type     Reason                  Age    From                     Message
  ----     ------                  ----   ----                     -------
  Warning  FailedScheduling        5m11s  default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
  Warning  FailedScheduling        5m10s  default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims
```

**Comment by ibrokethecloud** [comment]
@aaannz the scheduling is failing due to PVC claim not being fulfilled.

Any chance you could please provide us a support bundle?

**Comment by aaannz** [comment]
@ibrokethecloud Sorry for the late answer. Seems like problem with pvc scheduling was just timing issue. Apparently sometimes longhorn takes little while to provision it. Not related to this issue.

**Comment by jrlittlefoot64** [comment]
I think this question depends on my question #3236

**Comment by jrlittlefoot64** [comment]
> This repository uses an automated workflow to automatically label issues which have not had any activity (commit/comment/label) for 60 days. This helps us manage the community issues better. If the issue is still relevant, please add a comment to the issue so the workflow can remove the label and we know it is still valid. If it is no longer relevant (or possibly fixed in the latest release), the workflow will automatically close the issue in 14 days. Thank you for your contributions.

For me its still open

**Comment by w13915984028** [comment]
@jrlittlefoot64 How about your cluster later ?

**Comment by jrlittlefoot64** [comment]
since 1.2.0 it works as expected. Thank you
