### ISSUE TITLE
[Backport v1.0] The project-owner user will see an additional alert

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2350]
This is a backport issue for [#2288](https://github.com/harvester/harvester/issues/2288).

**Comment by TachunLin** [comment]
Move to ready for test and verify with #2394

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.0-ec0bb4be-head` (6/10) with Rancher `v2.6.5`. Close this issue 

Harvester ui-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html 
Rancher ui dashboard-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/dd7c9a1cbc6251cd5e0e.js
Rancher offline preferred: `Remote` 


### Result
Use rancher standard user `test` with project owner permission to access Harvester.
Now there is no error alert for VM created on vlan1 
![image](https://user-images.githubusercontent.com/29251855/174726793-37bfd8a2-d5da-4fbb-9e16-abc251202635.png)



### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `v1.0-ec0bb4be-head`
* Rancher version: `v2.6.5`

### Verify Steps
Follow the issue description https://github.com/harvester/harvester/issues/2288#issue-1241173686
