### ISSUE TITLE
[Backport v1.0] You can see cattle-monitoring-system volumes as restricted admin in Harvester

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2351]
This is a backport issue for [#2116](https://github.com/harvester/harvester/issues/2116)

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.0-9e056ebc-head` with Rancher `v2.6.5`. Close this issue.

### Result
Login Rancher with restricted admin and access Harvester volume page. 
Now it won't display the cattle-monitoring-system volumes. 
  ![image](https://user-images.githubusercontent.com/29251855/174298875-65b7e4ae-97a1-4771-9987-cb86af626c70.png)

### Test Information
* Test Environment: 1 node harvester on local bare machine
* Rancher version: v2.6.5
* Harvester version: `v1.0-9e056ebc-head` 
* ui-dashboard-url: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html 

### Verify Steps
1. Import Harvester to Rancher
2. Create restricted admin in Rancher
3. Log out of rancher
4. Log in as restricted admin
5. Navigate to Harvester ui in virtualization management
6. Navigate to volumes page
