### ISSUE TITLE
[FEATURE] Add v1.0.3 UI related CI/CD

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2353]
**Is your feature request related to a problem? Please describe.**

UI branch:   https://github.com/harvester/dashboard/tree/harvester-release-v1.0

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
@WuJun2016 u can use the `release-harvester-*` branch name, and therefore we don't need to change the existing drone CI.

**Comment by WuJun2016** [comment]
Now CI/CD is available， so close.
