### ISSUE TITLE
[FEATURE] Limit all VMs of the Harvester guest cluster in the same namespace

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2354]
**Is your feature request related to a problem? Please describe.**

Harvester load balancer allows users to configure an IP pool for the specified project/namespace, but the VMs created by the Harvester node driver can be in different project/namespace. 

**Describe the solution you'd like**

Limit all VMs of the Harvester guest cluster in the same namespace.

**Describe alternatives you've considered**

**Additional context**

**Comment by n313893254** [comment]
## Pre Ready-For-Testing Checklist
~* [ ] **If labeled: require/HEP** Has the Harvester Enhancement Proposal PR submitted?
  The HEP PR is at:~

* [x] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at: 

- https://github.com/harvester/harvester/issues/2354#issue-1261421773

~* [ ] Is there a workaround for the issue? If so, where is it documented?
The workaround is at:~


* [x] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at:

- https://github.com/rancher/ui/pull/4853
- https://github.com/rancher/dashboard/pull/6174

~* [ ] **If labeled: require/doc, require/knowledge-base** Has the necessary document PR submitted or merged?
The documentation/KB PR is at:~


~* [ ] **If NOT labeled: not-require/test-plan** Has the e2e test plan been merged? Have QAs agreed on the automation test case? If only test case skeleton w/o implementation, have you created an implementation issue?
    - The automation skeleton PR is at:
    - The automation test case PR is at:~

~* [ ] **If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at:~

**Comment by TachunLin** [comment]
Verified **fixed** on `master-08af3d7c-head` (07/06) with Rancher v2.6.5. Close this issue.

Rancher ui-dashboard-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html
Harvester ui index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html

### Result
* On RKE2 cluster page, when we select the first machine pool to specific namespace, then the second pool will automatically and can only use the same namespace as the first pool 
  - Using `default` namespace  
    ![image](https://user-images.githubusercontent.com/29251855/177543321-b7ebe517-d18d-469b-953e-d3534109d367.png)
  - Using custrom namespace
    ![image](https://user-images.githubusercontent.com/29251855/177543795-93f419b6-f083-49b2-9374-42de55d5abd7.png)

* On RKE1 node template page, when we create two node template with different namespace 
![image](https://user-images.githubusercontent.com/29251855/177544417-e82410b6-e0c0-47bf-9dd6-8da42bfd4cc4.png)

  - In RKE1 cluster page, pool 1 can select both `rke1-template` and `rke1-template2`
    ![image](https://user-images.githubusercontent.com/29251855/177546440-876c05a6-80a5-4b6b-83c9-d46ff90b8923.png)

  - But pool 2 can't select `rke1-template2` if `rke1-template` have already selected by pool
    ![image](https://user-images.githubusercontent.com/29251855/177546289-a7b7c17e-2e42-47c6-baf4-7811de1b5c62.png)


### Test Information
* Test Environment: 1 node harvester on provo bare machine
* Harvester version: master-08af3d7c-head
* Rancher version: v2.6.5

### Verify Steps
1. Import Harvester from Rancher 
2. Access Harvester via virtualization management 
3. Create a test project and `ns1` namespace 
4. Create two RKE1 node template, one set to default namespace and another set to ns1 namespace
5. Create a RKE1 cluster, select the first pool using the first node template
6. Create another pool, check can't select the second node template 
7. Create a RKE2 cluster, set the first pool using specific namespace 
8. Add another machine pool, check it will automatically assigned the same namespace as the first pool
