### ISSUE TITLE
[BUG] VMIs created from VM Template don't have LiveMigrate evictionStrategy set

### ISSUE THREAD

**Issue by iwilltry42** [harvester/harvester#2357]
**Describe the bug**

I noticed, that when I create VMs from a pre-made template (with no special settings), they won't have `evictionStrategy: LiveMigrate` set on the VMI, which is why `Cordon` and `Maintenance Mode` fail to enable on the node they're on.

However, when I just create them "manually" without a template, but with the exact same settings, the evictionStrategy will be set correctly.

I noticed, that this setting is also not set in the template YAML and probably isn't injected later for some reason.

**To Reproduce**
1. Create a VM Template in the Harvester UI
```yaml
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineTemplateVersion
metadata:
  annotations:
    template-version.harvesterhci.io/customName: TxFz0NrDsU
  creationTimestamp: "2022-06-06T11:20:37Z"
  generateName: ubuntu-focal-2-4-iwilltry42-insecure-
  generation: 2
  labels:
    template.harvesterhci.io/templateID: ubuntu-focal-2-4-iwilltry42-insecure
  managedFields: [] # truncated for readability  	
    manager: harvester
    operation: Update
    time: "2022-06-06T11:20:37Z"
  name: ubuntu-focal-2-4-iwilltry42-insecure-c4mz7
  namespace: default
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineTemplate
    name: ubuntu-focal-2-4-iwilltry42-insecure
    uid: cd6c53e0-f2bc-4707-8205-b802e19c85af
  resourceVersion: "16583195"
  uid: 333af4ab-1712-44e7-9635-2cbeaa81e570
spec:
  templateId: default/ubuntu-focal-2-4-iwilltry42-insecure
  vm:
    metadata:
      annotations:
        harvesterhci.io/volumeClaimTemplates: '[{"metadata":{"name":"-disk-0-wqp6z","annotations":{"harvesterhci.io/imageId":"default/image-qz5bs"}},"spec":{"accessModes":["ReadWriteMany"],"resources":{"requests":{"storage":"10Gi"}},"volumeMode":"Block","storageClassName":"longhorn-image-qz5bs"}}]'
      creationTimestamp: null
      labels:
        harvesterhci.io/os: ubuntu
    spec:
      runStrategy: RerunOnFailure
      template:
        metadata:
          annotations:
            harvesterhci.io/sshNames: '["default/iwilltry42-de"]'
          creationTimestamp: null
          labels:
            harvesterhci.io/vmName: ""
        spec:
          domain:
            cpu:
              cores: 2
              sockets: 1
              threads: 1
            devices:
              disks:
              - bootOrder: 1
                disk:
                  bus: virtio
                name: disk-0
              - disk:
                  bus: virtio
                name: cloudinitdisk
              inputs:
              - bus: usb
                name: tablet
                type: tablet
              interfaces:
              - masquerade: {}
                model: virtio
                name: default
            features:
              acpi:
                enabled: true
            machine:
              type: ""
            resources:
              limits:
                cpu: "2"
                memory: 4Gi
          networks:
          - name: default
            pod: {}
          volumes:
          - name: disk-0
            persistentVolumeClaim:
              claimName: -disk-0-wqp6z
          - cloudInitNoCloud:
              networkDataSecretRef:
                name: ubuntu-focal-2-4-iwilltry42-insecure-q2ugw
              secretRef:
                name: ubuntu-focal-2-4-iwilltry42-insecure-q2ugw
            name: cloudinitdisk
status:
  conditions:
  - lastUpdateTime: "2022-06-06T11:20:37Z"
    status: "True"
    type: assigned
  version: 2
```

2. Create a VM using this template
3. Use kubectl to check if `evictionStrategy: LiveMigrate` is set on the resulting VMI

**Expected behavior**

All VMs that follow the "rules" should have `evictionStrategy: LiveMigrate` set

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal, 2xHPE, 1xNEC

**Additional context**

Discussion on Slack: https://rancher-users.slack.com/archives/C01GKHKAG0K/p1654518543285929

**Comment by iwilltry42** [comment]
# Reproduce

1. Create template: only set the required fields (Name and CPU + Memory), save it
2. Click "Launch Instance from Template"
3. Click "Edit as YAML"
4. See that `evictionStrategy: LiveMigrate` is missing there
5. Go on to create VM **without** template
6. Click "Edit as YAML"
7. See that `evictionStrategy: LiveMigrate` is set there

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **baremetal DL160G9 5 nodes**
* Harvester Version: **master-0f590757-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with at least 2 nodes
2. Create Image for VM Creation
3. Navigate to _Advanced/Templates_ and create a template `t1`
4. Create VM `vm1` from template `t1`
5. Edit YAML of `vm1`, field `spec.template.spec.evictionStrategy` should be `LiveMigrate`
6. Enable Maintenance Mode on the host which hosting `vm1`
7. `vm1` should start migrating automatically
8. Migration should success
