### ISSUE TITLE
Inaccurate detail provided by hostname comment

### ISSUE THREAD

**Issue by mallardduck** [harvester/harvester#2359]
Per the title, this line seems to provide inaccurate details based on my first hand testing.

https://github.com/harvester/ipxe-examples/blob/601ffd0e1e56a10b96c7ec2eb235848f071f2972/general/config-join.yaml#L4

This implies that DHCP server set hostnames should be respected, however that is not the case in my experience setting up a Harvester cluster via pxe/ipxe and using ISC DHCPD.

Obviously, it would be ideal if I could exclude the hostname field from the yaml config for joining a cluster, because then every node could use the same exact yaml. So that is my root motivation for wishing this worked as the comment implies.

---

From my investigation I found that the installer - [specifically here](https://github.com/harvester/harvester-installer/blob/742b776e251c074471c7f52e0029e543b40260a6/pkg/console/install_panels.go#L1516) - seems to generate the hostname I'm seeing being used.

I'm wondering if this comment is in reference to old behavior that was removed, or maybe new behavior that hasn't shipped yet?

**Comment by guangbochen** [comment]
Transfer the issue to `harvester/harvester` repo since that is the right place to track all harvester issues, thanks.

**Comment by mallardduck** [comment]
From what I can see in the code this issue is still relevant - I'm not seeing any changes to either the example repo, or the installer which would make things consistent. My impression from the comment would be that the `generateHostName` function should use the DHCP hostname if one is set, otherwise defaulting to current behaviour makes sense.

Alternatively, it may just be easier to just update the examples repo to remove the comment saying hostname is optional if DHCP is used. Personally I think the former solution is nicer for end users though.
