### ISSUE TITLE
[BUG] - new VM's are unschedulable after hard VM crash

### ISSUE THREAD

**Issue by try2codesecure** [harvester/harvester#2363]
**Describe the bug**
Assumption:
- Maybe this bugs hits after cluster extension from one to two nodes.
or
- This bug hits after an running VM is completely run out of disc space & crashed unfortunately.

After that, I can't start the VM anymore. I erased the crushed VM but then also no new VM's can't be created & started.
Existing VM's & volumes are not affected & are fully operable.

**To Reproduce**
Maybe hard to reproduce. Try to create a VM & complete fill the disk space & wait until the VM crashes.
Try to start the crashed VM.
If it fails => erase the failing VM & volume.
Try to create and start new VM's.

**Expected behavior**
VM's can be normally scheduled

**Support bundle**
[supportbundle_304fc76c-a328-4321-8bf5-f225c7994734_2022-06-09T06-46-38Z.zip](https://github.com/harvester/harvester/files/8867624/supportbundle_304fc76c-a328-4321-8bf5-f225c7994734_2022-06-09T06-46-38Z.zip)

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure: 2(3)xBaremetal with Dell PowerEdge R730

**Workaround**
As a workaround i had to upload new images, update the template & recreate a new VM from that.
Than the VM will be scheduled & started.

**Additional context**
I guess this is longhorn related issue.
(csi_handler.go # https://github.com/longhorn/external-attacher/blob/930d4a0b85eef5bd0c5d012b0e7ed8bb44d60a09/pkg/controller/csi_handler.go#L253)

Error log of csi-attacher pod: 
[csi-attacher-6845f6bf75-8lhj7.log](https://github.com/harvester/harvester/files/8867457/csi-attacher-6845f6bf75-8lhj7.log)

The event log of an example VM:
![grafik](https://user-images.githubusercontent.com/4202158/172778485-4e264318-e28f-41f8-a1c6-49a80befcbd9.png)

**Comment by try2codesecure** [comment]
The following things I have already tried & did not work or had no effect:
- Rollout restart of csi-attacher, csi-provisioner, csi-resizer & csi-snapshotter (kubectl rollout restart deployment ... -n longhorn-system )
- create a new VM & mount an existing volume & tried to start.
- use an "old" existing VM & mount an newly created volume & tried to start.
- workaround https://github.com/longhorn/longhorn/issues/2618#issuecomment-858377173 ( https://github.com/rancherlabs/support-tools/pull/121/files#diff-76674445973181d3c4329d6cc84310a85d702061b8a6473495090cb6e8ad7ac9 )
- workaround # https://github.com/longhorn/longhorn/issues/3778#issuecomment-1085219265
- create new VM & manually create new volume & mount to VM
- restart VM
- restart harvester nodes

**Comment by try2codesecure** [comment]
Maybe related to:
- https://github.com/harvester/harvester/issues/2156
- https://github.com/harvester/harvester/issues/1695

**Comment by try2codesecure** [comment]
virt-launcher pod error logs (example virt-launcher-eraseme-8b47q):
```bash
(combined from similar events): Unable to attach or mount volumes: unmounted volumes=[disk-1], unattached volumes=[private public ephemeral-disks container-disks cloudinitdisk-udata disk-1 cloudinitdisk-ndata hotplug-disks libvirt-runtime sockets]: timed out waiting for the condition

Unable to attach or mount volumes: unmounted volumes=[disk-1], unattached volumes=[cloudinitdisk-udata sockets private ephemeral-disks container-disks libvirt-runtime hotplug-disks cloudinitdisk-ndata disk-1 public]: timed out waiting for the condition
```
error log from csi-attacher for related pvc (fresh start, after manual erase):
```bash
I0609 08:30:31.341206       1 main.go:96] Version: v3.2.1
I0609 08:30:31.344499       1 common.go:111] Probing CSI driver for readiness
I0609 08:30:31.347555       1 main.go:152] CSI driver name: "driver.longhorn.io"
I0609 08:30:31.353908       1 main.go:208] CSI driver supports ControllerPublishUnpublish, using real CSI handler
I0609 08:30:31.357792       1 leaderelection.go:243] attempting to acquire leader lease longhorn-system/external-attacher-leader-driver-longhorn-io...
I0609 08:30:50.661972       1 leaderelection.go:253] successfully acquired lease longhorn-system/external-attacher-leader-driver-longhorn-io
I0609 08:30:50.662094       1 leader_election.go:205] became leader, starting
I0609 08:30:50.662132       1 controller.go:128] Starting CSI attacher
I0609 08:30:50.662374       1 reflector.go:219] Starting reflector *v1.VolumeAttachment (10m0s) from k8s.io/client-go/informers/factory.go:134
I0609 08:30:50.662426       1 reflector.go:219] Starting reflector *v1.PersistentVolume (10m0s) from k8s.io/client-go/informers/factory.go:134
I0609 08:30:50.662378       1 reflector.go:219] Starting reflector *v1.CSINode (10m0s) from k8s.io/client-go/informers/factory.go:134
I0609 08:30:50.762445       1 csi_handler.go:245] Attaching "csi-be488a64e038ed996059d902924bfb0a0e03d5287c0c591b00fd05e1acc48655"
I0609 08:32:20.778883       1 csi_handler.go:228] Error processing "csi-be488a64e038ed996059d902924bfb0a0e03d5287c0c591b00fd05e1acc48655": failed to attach: rpc error: code = DeadlineExceeded desc = volume pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf failed to attach to node bm-001
I0609 08:32:21.779955       1 csi_handler.go:245] Attaching "csi-be488a64e038ed996059d902924bfb0a0e03d5287c0c591b00fd05e1acc48655"
```

**Comment by try2codesecure** [comment]
describe volume:
```bash
bm-001:~ # kubectl describe volume -n longhorn-system pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf 
Name:         pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
Namespace:    longhorn-system
Labels:       longhornvolume=pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
              recurring-job-group.longhorn.io/default=enabled
Annotations:  <none>
API Version:  longhorn.io/v1beta1
Kind:         Volume
Metadata:
  Creation Timestamp:  2022-06-09T04:43:12Z
  Finalizers:
    longhorn.io
  Generation:  12
  Managed Fields:
    API Version:  longhorn.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .:
          v:"longhorn.io":
        f:labels:
          .:
          f:longhornvolume:
          f:recurring-job-group.longhorn.io/default:
      f:spec:
      f:status:
    Manager:         longhorn-manager
    Operation:       Update
    Time:            2022-06-09T04:43:12Z
  Resource Version:  8572430
  UID:               a4fb5c90-bd49-4c47-99c0-8f957f3bb405
Spec:
  Standby:                    false
  Access Mode:                rwx
  Backing Image:              default-image-h2wxc
  Base Image:                 
  Data Locality:              disabled
  Data Source:                
  Disable Frontend:           false
  Disk Selector:              <nil>
  Encrypted:                  false
  Engine Image:               longhornio/longhorn-engine:v1.2.4
  From Backup:                
  Frontend:                   blockdev
  Last Attached By:           
  Migratable:                 true
  Migration Node ID:          
  Node ID:                    bm-002
  Node Selector:              <nil>
  Number Of Replicas:         3
  Replica Auto Balance:       ignored
  Revision Counter Disabled:  false
  Size:                       10737418240
  Stale Replica Timeout:      30
Status:
  Actual Size:  0
  Clone Status:
    Snapshot:       
    Source Volume:  
    State:          
  Conditions:
    Restore:
      Last Probe Time:       
      Last Transition Time:  2022-06-09T04:43:15Z
      Message:               
      Reason:                
      Status:                False
      Type:                  restore
    Scheduled:
      Last Probe Time:       
      Last Transition Time:  2022-06-09T07:28:39Z
      Message:               
      Reason:                ReplicaSchedulingFailure
      Status:                False
      Type:                  scheduled
    Toomanysnapshots:
      Last Probe Time:       
      Last Transition Time:  2022-06-09T04:43:15Z
      Message:               
      Reason:                
      Status:                False
      Type:                  toomanysnapshots
  Current Image:             longhornio/longhorn-engine:v1.2.4
  Current Node ID:           bm-002
  Expansion Required:        false
  Frontend Disabled:         false
  Is Standby:                false
  Kubernetes Status:
    Last PVC Ref At:  
    Last Pod Ref At:  
    Namespace:        infrastructure
    Pv Name:          pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
    Pv Status:        Bound
    Pvc Name:         eraseme-disk-0-5w3ai
    Workloads Status:
      Pod Name:          virt-launcher-eraseme-z5644
      Pod Status:        Pending
      Workload Name:     eraseme
      Workload Type:     VirtualMachineInstance
  Last Backup:           
  Last Backup At:        
  Last Degraded At:      
  Owner ID:              bm-002
  Pending Node ID:       
  Remount Requested At:  
  Restore Initiated:     false
  Restore Required:      false
  Robustness:            unknown
  Share Endpoint:        
  Share State:           
  State:                 attaching
Events:                  <none>
```

**Comment by try2codesecure** [comment]
As a workaround i had to upload new images, update the template & recreate a new VM from that.
Than the VM will be scheduled & started.

**Comment by ibrokethecloud** [comment]
I had a quick look at the support bundle and I suspect the issue may be that the pv is still tied to a non existent PVC claim reference:

```
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
    sim.harvesterhci.io/creationTimestamp: "2022-06-09T04:43:16Z"
  creationTimestamp: "2022-06-09T04:43:16Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
  resourceVersion: "947"
  uid: e5e8f96d-ad28-459f-b65d-925897e27137
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: eraseme-disk-0-5w3ai
    namespace: infrastructure
    uid: 2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
  csi:
    driver: driver.longhorn.io
    volumeAttributes:
      backingImage: default-image-h2wxc
      migratable: "true"
      numberOfReplicas: "3"
      share: "true"
      staleReplicaTimeout: "30"
      storage.kubernetes.io/csiProvisionerIdentity: 1654700831549-8081-driver.longhorn.io
    volumeHandle: pvc-2542da48-8aa9-4922-8fa4-3c70ee4e6fcf
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn-image-h2wxc
  volumeMode: Block
status:
  phase: Bound
(⎈ |default:harvester-system)➜  supportbundle_304fc76c-a328-4321-8bf5-f225c7994734_2022-06-09T06-46-38Z k get pvc -A |grep eraseme-disk-0-5w3ai
```

No pvc by the name `eraseme-disk-0-5w3ai` exists in the cluster.

**Comment by zp4rand0miz31** [comment]
Hi, we are  experiencing the same problem. Our cluster of 5 servers had a hard crash (DIMM outage) and we cannot recover a stable cluster from then. 
Some VMs seems unschedulable, some other works perfectly, we are getting mad about this situation. This is critical for us. 

We tried to upgrade longhorn engine image to 1.2.6 but the system did rollback to 1.2.4 after some reboots. Not sure how we can control and debug harvester.  The longhorn upgrade procedure do not apply with harvester, or at least we fail to upgrade.

We also tried to recreate images but this does not help.

We are still in 1.0.3, because the 1.1.1 upgrade process seems to be more than dangerous from what we read.

(Bundle is too big to be uploaded)

We are now considering a clean reinstall of a fresh k3s cluster with kubevirt on our own, without the longhorn component that seems to be creating many or all the problems we had to far with Harvester, regarding stability.

Thank you.

**Comment by chrisho** [comment]
@try2codesecure @zp4rand0miz31 Could you provide more details reproduce steps, I didn't reproduce in Harvester v1.0.3 and 3 nodes of the cluster. 
My reproduction steps:
1. Install Harvester 3 nodes with v1.0.3.
2. Create a 1c2G vm with a 10Gi volume
3. login the VM and fill the disk (`dd if=/dev/zero of=largefile.txt bs=1M count=10000`)
4. Wait a long time, but still running.

**Comment by bk201** [comment]
@FrankYang0529 can you help check if this issue is still present? Thank you!

**Comment by FrankYang0529** [comment]
> @FrankYang0529 can you help check if this issue is still present? Thank you!

Hi @bk201, I create multiple VMs in Harvester v1.3.0-rc4 and write random data to make disk full. The VMs are not crashed and the cluster is healthy. I think we can close the issue.

**Comment by bk201** [comment]
I'll close this for now since the last comment is from 2022 and PoAn can't reproduce the issue. Please try the latest version and open a new issue if this still happens.
