### ISSUE TITLE
[BUG] Invalid NTP server could be assigned in ISO install

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2367]
### Describe the bug
The invalid NTP server could be bypass by enter twice.

### To Reproduce
1. Install Harvester with ISO install
2. Enter invalid NTP server IP then click enter twice
3. The invalid NTP server could be assigned into configuration

### Expected behavior
Maybe we should detect the error and prevent the invalid NTP server to be assigned?

## Environment:
 - Harvester ISO version: **master-a242948b-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

### Additional context
![image](https://user-images.githubusercontent.com/5169694/172824802-3b6ae4b3-2676-496c-bd07-3f2e2e4ff3ff.png)
![image](https://user-images.githubusercontent.com/5169694/172824894-24eeb1d9-ad43-46bb-aa0e-11b93565dcf8.png)

**Comment by bk201** [comment]
> Enter invalid NTP server IP then click enter twice

@lanfon72 I remember there is a warning to ask users if they really want to proceed? Do you feel a hard requirement is better at this stage? cc @FrankYang0529

**Comment by lanfon72** [comment]
As the error message:
> ...Press Enter to continue or change the input to revalidate.

This would confuing user when they want to revalidate **the same** NTP server, what should they do?
And as we can't update NTP server after installed, I think there should be more seriously to tell user choice the accessible NTP server before they install it.[^1][^2]

[^1]:https://github.com/harvester/harvester/issues/2119
[^2]:https://github.com/harvester/harvester/issues/1969

**Comment by tjjh89017** [comment]
So do we want to have force NTP setting even in air-gap env?
cc @guangbochen & @bk201

**Comment by guangbochen** [comment]
I think we may improve it via:
1. emphasis the warning message to highlight the importance of the NTP configuration(but not force required?)
   - remove `Optional`
   - Note: recommended configuring the NTP server to make sure all nodes' times are synchronized.
3. check if there is a method to allow to do a post configuration of the NTP server. - provide doc for manual configuration.

**Comment by bk201** [comment]
> I think we may improve it via:
> 
> 1. emphasis the warning message to highlight the importance of the NTP configuration(but not force required?)
>    
>    * remove `Optional`
>    * Note: recommended configuring the NTP server to make sure all nodes' times are synchronized.
> 2. check if there is a method to allow to do a post configuration of the NTP server. - provide doc for manual configuration.

2. will be fixed in https://github.com/harvester/harvester/issues/2418

**Comment by starbops** [comment]
> I think we may improve it via:
> 
> 1. emphasis the warning message to highlight the importance of the NTP configuration(but not force required?)
>    
>    * remove `Optional`
>    * Note: recommended configuring the NTP server to make sure all nodes' times are synchronized.
> 2. check if there is a method to allow to do a post configuration of the NTP server. - provide doc for manual configuration.

Improved the note message and warning message shown for users to decide their next move.

<img width="1023" alt="Screen Shot 2022-08-25 at 12 47 33" src="https://user-images.githubusercontent.com/1827717/186578515-f13b44df-6900-40df-8acc-fc6feb1843c6.png">

<img width="1022" alt="Screen Shot 2022-08-25 at 12 45 28" src="https://user-images.githubusercontent.com/1827717/186578522-d4c0316a-8436-45df-8d48-945bdc0fbe30.png">

**Comment by lanfon72** [comment]
@starbops Is it possible to change `Press Enter to proceed without NTP servers configured` to `Press Enter again to use current configuration anyway` ?  I think latter would be more clear that (unreachable servers') configration will still be applied.

**Comment by starbops** [comment]
> @starbops Is it possible to change `Press Enter to proceed without NTP servers configured` to `Press Enter again to use current configuration anyway` ? I think latter would be more clear that (unreachable servers') configration will still be applied.

Sure, I think the word “again” is more explicit. Thanks for the suggestion.

**Comment by lanfon72** [comment]
Verified this bug has been resolved.

![image](https://user-images.githubusercontent.com/5169694/188434688-ad200760-1c82-4d87-b9f9-09a8b8f3e9a7.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-606acc52-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2367#issue-1265932814
