### ISSUE TITLE
The state of VMs on detail page is not reflecting the actual state

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#237]
**Steps to reproduce:**
1. Create a VM adding a CDROM
2. Get to its detail page and Eject the CDROM

**Result:**
The CD-ROM will be ejected and the VM will restart, but the state on the detail page stays active all the time, not reflect the actual state
![image](https://user-images.githubusercontent.com/57614736/98882221-c27c9080-24c6-11eb-821b-3bd6d21366b3.png)

**Comment by WuJun2016** [comment]
@DoNotSayYes  It can't be reproduced. It may not be a problem. When the second eject happens, the startup speed is slow.

**Comment by DoNotSayYes** [comment]
Validated
