### ISSUE TITLE
[backport v1.0.3] VM IP addresses should be labeled per network interface

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2370]
**Describe the bug**

This is a backport issue for https://github.com/harvester/harvester/issues/2032

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on the backport version `v1.0-9e056ebc-head`. Close this issue.
It's the backport issue of #2032 

The VM list only show IP which related to user access. 
It can provide hover message on each displayed IP address
  ![image](https://user-images.githubusercontent.com/29251855/174025182-6639443b-ba3d-4581-b45b-43c062b18e7d.png)
  ![image](https://user-images.githubusercontent.com/29251855/174025281-f341cc47-9d58-4f94-9930-60c35a49902d.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `v1.0-9e056ebc-head` 

### Verify Steps
1. Enable network with magement-mgmt interface
2. Create vlan network `vlan1` with id `1`
3. Check the IP address on the VM page
4. Create a VM with mangement-mgmt network
5. Import Harvester in Rancher 
6. Provision a RKE2 cluster from Rancher 
7. Check the IP address on the VM page
