### ISSUE TITLE
[BUG] Cannot delete Template

### ISSUE THREAD

**Issue by eshenayo** [harvester/harvester#2376]
**Describe the bug**
A template cannot be deleted when it is the default version, but there is no way to remove the 'default version' designation for the last remaining version, leaving the template unable to be deleted.

![image](https://user-images.githubusercontent.com/8902109/173663034-8cd7fed7-d011-4a01-85a1-6043c2b809b3.png)

![image](https://user-images.githubusercontent.com/8902109/173663188-419db9f3-1d4e-4ba4-bc6a-11e5b059bf7c.png)

**To Reproduce**
1. Go to Advanced --> Templates
2. Create a new template
3. Delete the template from either the elipses menu or top delete button

**Expected behavior**
Would expect to be able to either delete the template without error or be able to remove the default version designation so it can be deleted.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal ProLiant BL460c Gen9

**Additional context**

**Comment by ibrokethecloud** [comment]
@eshenayo I think we can improve the UI, but to delete the default version you will need to delete the template itself.

![image](https://user-images.githubusercontent.com/19664014/173712872-b57c2900-6195-43cf-88c1-167ac720ccc0.png)

On the main template name there should be an option for deleting the template:

![image](https://user-images.githubusercontent.com/19664014/173712947-493a9c67-84b2-4c5a-91b1-0b54cf9b63d1.png)

If you could please try that, it should remove the template.

**Comment by WuJun2016** [comment]
made ui enhancement:  if it is the default version, the delete button is not shown

**Comment by TachunLin** [comment]
Verified **fixed** on `master-26bff4f1-head` (06/10). Close this issue.
ui-index: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html

### Result
* If the template is the `default version`, it will not display the `delete` button 
  ![image](https://user-images.githubusercontent.com/29251855/174030567-b2c6ae52-40d1-4dd6-9ede-783409bd3c87.png)

* If the template is **not** the `default version`, it will display the `delete` button 
  ![image](https://user-images.githubusercontent.com/29251855/174030720-5fb040e0-73f8-4697-8b0f-ee02d407b5d4.png)

* We can also delete the entire template from the config button
  ![image](https://user-images.githubusercontent.com/29251855/174030849-5f4ed7c8-1351-4b13-b3ca-d377b5b4f6c0.png)

### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: master-26bff4f1-head (06/10)

### Verify Steps
1. Go to advanced -> tempaltes
2. Create a new template
3. Modify the template to create a new version
4. Click the config button of the `default version` template
5. Click the config button of the `non default version` template
