### ISSUE TITLE
[Backport v1.0.3] input nic ip and vip with same ip address in Harvester-Installer

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#2377]
This is a backport related to https://github.com/harvester/harvester/issues/2229

**Comment by noahgildersleeve** [comment]
Tested in v1.0-3b6ab0d1-head. Verified as fixed

## Verification Steps
1. Build ISO from v1.0 branch
2. Boot into ISO
3. Specify same IP for NIC and VIP
4. Verify that error message is displayed
![Screenshot_20220707_170815](https://user-images.githubusercontent.com/83787952/178049998-e4eec9fe-d687-4efc-9618-940432d37a3d.png)
