### ISSUE TITLE
[backport v1.0.3] Cannot delete Template

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2379]
This is a backport issue for https://github.com/harvester/harvester/issues/2376

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.0-9e056ebc-head` (06/10). Close this issue.

### Result
* If the template is the `default version`, it will not display the `delete` button 
  ![image](https://user-images.githubusercontent.com/29251855/174036010-1e7b3b2c-0536-4be1-b8a8-5491acae2f10.png)
 
* If the template is **not** the `default version`, it will display the `delete` button 
 ![image](https://user-images.githubusercontent.com/29251855/174035877-b7b588ac-c480-4aa3-a088-bd90a2638447.png)

* We can also delete the entire template from the config button
 ![image](https://user-images.githubusercontent.com/29251855/174036113-6c022db5-8aa3-4ab3-8b0d-935bd988a1ff.png)

### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: master-26bff4f1-head (06/10)

### Verify Steps
1. Go to advanced -> tempaltes
2. Create a new template
3. Modify the template to create a new version
4. Click the config button of the `default version` template
5. Click the config button of the `non default version` template
