### ISSUE TITLE
[Backport v1.0] Improved resource reservation

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2381]
This is a backport issue for https://github.com/harvester/harvester/issues/2347.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/175259460-2be09c45-286d-4a6d-bd77-bc2aaf0c954e.png)
![image](https://user-images.githubusercontent.com/5169694/175259513-e55b5302-945c-412a-afe6-b0c48f645e59.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0-ec0bb4be-head**
* **ui-source** Option: **Auto**
* **ui-index**: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html

### Verify Steps:
1. Install Harvester with any nodes
2. Login and Navigate to Hosts
3. CPU/Memory/Storage should display **Reserved** and **Used** percentage.
4. Navigate to Host's details
5. Monitor Data should display **Reserved** and **Used** percentage, and should equals to the value in Hosts.
