### ISSUE TITLE
[BUG] Backport issues are not automatically associated with release

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#2385]
**Describe the bug**
Release is not automatically associated when a backport issue is created.

**To Reproduce**
1. Add `backport-needed/$version` label to issue.
2. View backport issue.

**Expected behavior**
Release is automatically associated when a backport issue is created.

**Additional context**

**Comment by guangbochen** [comment]
close as fixed via https://github.com/harvester/bot/pull/9
