### ISSUE TITLE
[Doc] Use toolbox container for debugging Harvester OS and reduce base installation

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2391]
**Is your feature request related to a problem? Please describe.*
The Harvester OS image contains a number of packages and utilities that are merely included to facilitate debugging but not required for normal operations (e.g. `zypper`).

In order to reduce attack surface and security patch cycles we should not include these tools in the base image. Instead we should adopt a toolkit that allows troubleshooting Harvester OS from within a privileged container.

https://documentation.suse.com/sle-micro/5.1/html/SLE-Micro-all/article-administration-slemicro.html#sec-admin-toolbox

**Comment by guangbochen** [comment]
We may consider adding a doc to provide a guideline for users on how to use the container tools box, e.g., https://harvesterhci.io/kb/scan-and-repair-vm-root-filesystem

**Comment by bk201** [comment]
Doc update: mentioning the KB in https://github.com/harvester/docs/pull/364

**Comment by bk201** [comment]
The doc PR is merged and published: https://docs.harvesterhci.io/dev/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only, close the issue after developer reviews.
