### ISSUE TITLE
Use helm install harvester，I need use helm install harvester-crd first?

### ISSUE THREAD

**Issue by Captured77** [harvester/harvester#2399]
I use helm install harvester APP model. But harvester deployment expose error。

**Comment by Captured77** [comment]
C:\Users\shangbing.huo\code\架构图\image\tmp\1655308478466.png

**Comment by Captured77** [comment]
> I use helm install harvester APP model. But harvester deployment expose error。 C:\Users\shangbing.huo\code\架构图\image\tmp\1655366498176.png

**Comment by futuretea** [comment]
Yes, you need to install harvester-crd first

**Comment by Captured77** [comment]
> Yes, you need to install harvester-crd first

 /deploy/charts  path
first： helm install harvester-crd harvester-crd --namespace harvester-system
second：helm install harvester harvester --namespace harvester-system --set service.harvester.type=NodePort 

longhorn is required？
Now error：

time="2022-06-23T01:57:56Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:01Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:06Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:11Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:16Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:21Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"
time="2022-06-23T01:58:26Z" level=error msg="Failed to dial steve aggregation server: x509: certificate is valid for 10.42.0.97, 10.42.0.98, not 10.43.114.8"

request：http://10.209.0.14:31890
response： Client sent an HTTP request to an HTTPS server.

Does harvester support rke cluster installation?

**Comment by Captured77** [comment]
helm install harvester，path /deploy/charts/harvester/README.md 
### Prerequisites
- Kubernetes 1.16+.
- Helm 3.2+.
- [Multus CNI](https://github.com/k8snetworkplumbingwg/multus-cni). An [example chart](https://github.com/rancher/rke2-charts/tree/main-source/packages/rke2-multus/charts).
- [Harvester CRDs](https://github.com/harvester/harvester/tree/master/deploy/charts/harvester-crd)

To install harvester,I need  install kubevirt operator crds(/deploy/charts/harvester/dependency-charts/kubevirt-operator/crds) first?

**Comment by w13915984028** [comment]
@Captured77

Please refer following doc to try. 

https://docs.harvesterhci.io/v1.0/dev/dev-mode/

For testing/experimenting Harvester, it's strongly recommended to install via ISO or PXE. After having an overall impression of Harvester's components, and still having interests, try the `dev-mode`. Thanks.

https://docs.harvesterhci.io/v1.0/install/iso-install/
