### ISSUE TITLE
[FEATURE] Enhance the information display of ISO installation console UI (tty) 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2402]
**Is your feature request related to a problem? Please describe.**

Current console UI display of ISO installation result not user friendly to provide clear information 
From user perspective, they may not be able to find the information needed at the first glance 
![image](https://user-images.githubusercontent.com/29251855/174580498-13225952-6f58-4b84-a38b-c950e5ee2267.png)

**Describe the solution you'd like**

The cluster and node information could be better display in a table view 

For example, consolidate cluster and node status into the following table 
And add the mechanism to check the current node status  

|                   |         Management Info         |       Status       |
|-------------------|:-------------------------------:|:------------------:|
| Harvester Cluster | http://10.84.103.178            | Setting up Cluster |
| Node              | host name: gc-t1<br />10.84.103.126 |        Ready       |

**Describe alternatives you've considered**

**Additional context**

**Comment by mallardduck** [comment]
Am i following correctly that this enhancement should be included in 1.0.3 when that's released?

**Comment by guangbochen** [comment]
We will probably doing the console UI display enhancement in v1.1.0 since the current one has already provided the correct information, let me know if u have any additional concerns, thanks.

**Comment by starbops** [comment]
Test Plan
=========

Steps
-----

1. Install Harvester with updated harvester-installer
1. After the installation is completed, check the dashboard console, its layout should look like the following:
<img width="806" alt="Screen Shot 2022-08-18 at 16 38 27" src="https://user-images.githubusercontent.com/1827717/185572813-d0b063a4-933e-4eb0-8da9-b74d3a714e3c.png">

**Comment by TachunLin** [comment]
Verified **fixed** on `master-dc6a3089-head` (08/23). Close this issue.

### Result
The ISO installation console UI enhancement can display correctly under the following single and multiple nodes scenarios.

#### Single node harvester
* Setting up Harvester cluster
![image](https://user-images.githubusercontent.com/29251855/186304660-e13f682c-68a0-4d8b-b6b9-a69ccccd492f.png)

* Finish installation
![image](https://user-images.githubusercontent.com/29251855/186321594-0dba5968-6898-4b91-b2c1-ba163411e643.png)

* Switch to F12 and turn back
![image](https://user-images.githubusercontent.com/29251855/186322340-d586b885-5c64-4a86-985e-0a2916debc18.png)
![image](https://user-images.githubusercontent.com/29251855/186322482-2aff0cd8-524f-4d8f-a728-2fa25b6acdf0.png)

#### Three nodes harvester cluster
* Setting up first node 
![image](https://user-images.githubusercontent.com/29251855/186342615-81c132c5-a7d3-4266-8315-40a293721a1a.png)

* first node finished
![image](https://user-images.githubusercontent.com/29251855/186343556-b50d46f0-ed03-4fd2-95cb-e9fecf90be4a.png)

* Second node finished 
![image](https://user-images.githubusercontent.com/29251855/186347502-488ef9e3-9c8c-4885-ab06-dd7558624afb.png)

* Third node finished
![image](https://user-images.githubusercontent.com/29251855/186349516-15ee3f63-bb7a-449e-bece-9e8699c9a391.png)

### Test Information
* Test Environment: single nodes harvester on local kvm machine
* Harvester version:  master-dc6a3089-head (08/23)

### Verify Steps
1. ISO install a single node Harvester
2. Monitoring the ISO installation console UI
3. ISO install a three node Harvester cluster
4. Monitoring the ISO installation console UI of the first node
5. Monitoring the ISO installation console UI of the second node
6. Monitoring the ISO installation console UI of the third node
