### ISSUE TITLE
[FEATURE] Adding Storage Class selector to Harvester UI

### ISSUE THREAD

**Issue by MikeTolkachev** [harvester/harvester#2403]
I added tags to the Longhorn nodes and created a new Storage Class to select from those tags.
When creating a new virtual machine, I would like to have a choice of storage class.

**Comment by bk201** [comment]
I guess this request is similar to https://github.com/harvester/harvester/issues/2147
There is a on-going HEP: https://github.com/harvester/harvester/pull/2335

**Comment by bk201** [comment]
Close since it's duplicated with #2147
