### ISSUE TITLE
[FEATURE]Harvester support third-party storage for non-root disks of VM

### ISSUE THREAD

**Issue by 290760647** [harvester/harvester#2405]
Harvester currently only supports the use of longhorn to store virtual machine data, and does not support the use of external storage to store virtual machine data, it is recommended that we can install CSI in the harvester cluster to support external storage, we can choose to use external storage as the VM's non-system data partition when creating the VM, in order to let customers store some application data, the system partition of the virtual machine can still use longhorn.

**Comment by yasker** [comment]
Related to #1199

**Comment by leovigna** [comment]
Is there any update on the progress of this issue? Multi-CSI support is critical for our Harvester use case as some of our workloads won't work optimally with Longhorn (IOPS). Is this the proper issue to track or should I look into another issue?
It looks like the UI was implemented (https://github.com/harvester/harvester/issues/3686) so not sure if this works or not at the moment. It's unclear from (https://docs.harvesterhci.io/v1.1/rancher/csi-driver#deploying-1) whether the custom storage class can use any provisioner or whether it is limited to Longhorn only.

**Comment by yasker** [comment]
@leovigna it's an upcoming feature for the v1.2.0 release. You can take a look at HEP https://github.com/harvester/harvester/pull/3666 to see what would the designed experience like.

**Comment by leovigna** [comment]
Ok thanks for the info. Is there an estimated timeline for that release (eg. 1mo, 6mo, 1yr)? Would just help us out for planning our migration to Harvester. Thx!

**Comment by yasker** [comment]
V1.2.0 release is targeting June/Q2 2023. You can check https://github.com/harvester/harvester/wiki/Roadmap for details.

**Comment by futuretea** [comment]
## Test Plan
**Setup Base Cluster** 

1. Prepare Harvester master iso
2. Prepare a custom Harvester config
```yaml
os:
  persistentStatePaths:
    - /var/lib/rook
  modules:
    - rbd
    - nbd
```
ceph needs the rbd module, rook will `modprobe rbd` in pod, but will fail in 1.11, it is safer to run modprobe from the host

3. Create a Harvester cluster
- use the master iso
- use the custom Harvester config
- the cluster has two nodes
- each Harvester node has two disks

You can also try the [harvester-auto](https://github.com/futuretea/harvester-auto) project, just only send one message to the slack bot:
```text
v2c master http://bit.ly/harvester-rook-config
```

**Setup Rook Ceph**

4. Install rook-ceph operator to the Harvester cluster
```bash
helm repo add rook-release https://charts.rook.io/release
helm repo update
helm upgrade --install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph --version v1.11.1
kubectl -n rook-ceph wait --for=condition=Available deploy rook-ceph-operator
```

5. create rook-ceph cluster,storageclass,snapshotclass
```bash
git clone -b v1.11.1 https://github.com/rook/rook.git && cd rook/deploy/examples
kubectl apply -f ./cluster-test.yaml
kubectl apply -f ./csi/rbd/storageclass-test.yaml
kubectl apply -f ./csi/rbd/snapshotclass.yaml
watch 'kubectl --namespace rook-ceph get pods'
```
**Test**

6. Configure the Harvester `csi-driver-config` settings from Harvester UI

7. Test all volume-related functions
- vm create
- vm clone
- vm backup & restore
- vm snapshot & restore
- vm live migration
- volume create
- volume clone
- volume snapshot & restore
- volume resize

8. Reboot Harvester node, All functions still work

**Comment by lanfon72** [comment]
As #3688 will use the same test plan, I think this could be verified along with it? cc @irishgordo

**Comment by irishgordo** [comment]
@lanfon72  - I've not had a chance to look at #3688 but I believe this and 3688 could be verified together :smile:

**Comment by lanfon72** [comment]
Verified this feature has been implemented but test plan have some problems
![image](https://github.com/harvester/harvester/assets/5169694/2309bd6b-68e5-4b40-ae20-0cb3c8793d13)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-b49e264e-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 2 nodes with configure options:
```yaml
os:
  persistentStatePaths:
    - /var/lib/rook
  modules:
    - rbd
    - nbd
```
2. Login to one of host, install helm
```bash
mkdir -p /usr/local/bin \
&& curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 \
&& chmod 700 get_helm.sh \
&& ./get_helm.sh
```
3. Install rook `v1.11.1` and deploy resources
```bash
helm repo add rook-release https://charts.rook.io/release \
&& helm repo update \
&& helm upgrade --install --create-namespace --namespace rook-ceph rook-ceph rook-release/rook-ceph --version v1.11.1
# check operator is ready, expected output: deployment.apps/rook-ceph-operator condition met
kubectl -n rook-ceph wait --for=condition=Available deploy rook-ceph-operator
# apply resources from offical examples
curl -fsSLo rook.tar.gz https://github.com/rook/rook/archive/refs/tags/v1.11.1.tar.gz \
&& tar -zxf rook.tar.gz \
&& cd rook-1.11.1/deploy/examples \
&& kubectl apply -f ./cluster-test.yaml \
&& kubectl apply -f ./csi/rbd/storageclass-test.yaml \
&& kubectl apply -f ./csi/rbd/snapshotclass.yaml
```
4. Login to dashboard, navigate to `Advanced/Settings`
5. Edit `csi-driver-config` to add `rook-ceph.rbd.csi.ceph.com` Provisioner and relevant class name
6. Create an image for VM creation
7. Create volumes `rook-vol`, `rook-vol2` using `rook-ceph-block` storage class
8. Create VM `vm1` with additional data disk using `rook-ceph-block` storage class and existing `rook-vol`
9. VM should created and started successfully
10. Add Volume `rook-vol2` to VM `vm1`
11. Login to VM, format additional disks, mount to folders and write data and checksum
```bash
# format disk: fdisk and mkfs.ext4
# write 512MB and checksum
dd if=/dev/urandom of=dummy bs=1M count=512
md5sum dummy > wrote.md5
```
12. Test Following functionality, data should not lost or corrupt
  - volume snapshot, restore
  - volume clone
  - volume resize
  - VM snapshot with data volume
  - VM clone with data volume
  - VM backup & restore with data volume
  - VM live migration with data volume
13. Reboot the node hosting `vm1`, data should not lost or corrput
14. Reboot node which not hosting `vm1`, data should not lost or corrupt

**Comment by lanfon72** [comment]
Verified this feature has been implemented

There have few different compare to previous test plan:
- Use rook `1.11.6`
- Install operator by the example's configuration, not helm
- More persistentStatePaths: `/var/lib/ceph`, `/etc/ceph`, `/etc/webhook`

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-b49e264e-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 3 nodes having configure options:
```yaml
os:
# ref: https://github.com/rook/rook/blob/v1.11.6/deploy/examples/operator.yaml#L570
  persistentStatePaths:
    - /var/lib/rook
    - /var/lib/ceph
    - /etc/ceph
    - /etc/webhook
  modules:
    - rbd
    - nbd
```
2. Login to one of hosts, install `rook-ceph`
```bash
curl -fsSLo rook.tar.gz https://github.com/rook/rook/archive/refs/tags/v1.11.6.tar.gz \
&& tar -zxf rook.tar.gz && cd rook-1.11.6/deploy/examples
# apply configurations ref: https://rook.github.io/docs/rook/v1.11/Getting-Started/example-configurations/
kubectl apply -f crds.yaml -f common.yaml -f operator.yaml
kubectl apply -f ./cluster.yaml -f ./csi/rbd/storageclass-test.yaml -f ./csi/rbd/snapshotclass.yaml
```
3. Login to dashboard, navigate to `Advanced/Settings`
4. Edit `csi-driver-config` to add `rook-ceph.rbd.csi.ceph.com` Provisioner and relevant class name
5. Create an image for VM creation
6. Create volumes `rook-vol`, `rook-vol2` using `rook-ceph-block` storage class
7. Volumes should created successfully
8. Create VM `vm1` with additional data disk using `rook-ceph-block` storage class and existing `rook-vol`
9. VM should created and started successfully
10. Add Volume `rook-vol2` to VM `vm1`
11. Login to VM, format additional disks, mount to folders and write data and checksum
```bash
# format disk: fdisk and mkfs.ext4
# write 512MB and checksum
dd if=/dev/urandom of=dummy bs=1M count=512
md5sum dummy > wrote.md5
```
12. Test Following functionality, data should not lost or corrupt
    - volume snapshot, restore
    - volume clone
    - volume resize
    - VM snapshot with data volume
    - VM clone with data volume
    - VM backup & restore with data volume
    - VM live migration with data volume
13. Reboot node which not hosting `vm1`, data should not lost or corrput
    - VM should started successfully
    - Restore VM/volume snapshot
    - Restore backup with replace/new
14. Reboot the node which hosting `vm1`, data should not lost or corrupt[^1][^2]
    - VM should started successfully
    - Restore VM/volume snapshot
    - Restore backup with replace/new


[^1]: reboot might stuck in ceph connection error, we were use force-reset after all others commands been done
[^2]: When not adding `/var/ceph` to persistentStatePaths, encountering `rook-ceph-osd` pod _CrashBackOff_, that's the mainly reason adding `/var/ceph` to state path.
![image](https://github.com/harvester/harvester/assets/5169694/b09a59bd-b016-4acf-a36f-72176dd18ff0)

**Comment by LucasSaintarbor** [comment]
Hi @futuretea @lanfon72 @WuJun2016, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [x] New documentation/KB
- [ ] Updated documentation/KB
- [x] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!

**Comment by lanfon72** [comment]
Hi @LucasSaintarbor, this issue is part of #3666 (another one is #3688), please help to add document based on #3666, thanks.
