### ISSUE TITLE
How to migrate a Virtual Machine from Vmware vsphere to harvester?

### ISSUE THREAD

**Issue by KarlSK8** [harvester/harvester#2411]
I have recently started working on harvester virtualization, and I am willing to transfer VMs that are already running in vSphere to harvester. What is the best way to do that?

**Comment by himslm01** [comment]
I don't know whether this is the *best* way, but it's *a* way...

I’ve moved a Windows10 host from ESXi to Harvester 1.0.2 like this:

* stopped the VM on ESXi
* scped the disk volume (a <name>.vmdk ~500 byte text file, and a <name>-flat.vmdk binary fie) from the ESXi host to a Linux host
* converted the disk volume to qcow2
```
$ qemu-img convert \
  -f vmdk \
  -O qcow2 \
  <name>.vmdk <name>.qcow
```
* uploaded that qcow2 to Harvester
* created a VM using the ‘raw image base template’
  * on the volume tab I selected the image I’d just uploaded, and made it a SATA type (neither VirtIO nor SCSI worked, for me - OS could not find the boot disk)
* started the VM
It booted.

Make it better with some drivers…

* in Images I created a new image using the URL of the Windows driver ISO file from [here](https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.215-2/)
* in Volumes I use the Add VM Image option to add a volume of type cd-rom using the image I just added
* rebooted the VM
* In the Windows 10 VM I installed the drivers from the CD-ROM - D:\

Once the drivers were installed, In Harvester
* alter VM to switch the root disk from SATA to VirtIO
* reboot

When the Windown 10 VM had rebooted the copied VM continued to work.

**Comment by KarlSK8** [comment]
Thank you @himslm01. 
I figured out this technique after posting here and it worked fine. I've used the same procedure as you mentioned, it isn't a straight forward technique but it did the job. 
I have one more question, do you think that if i convert the other disks from vmdk to qcow2 and mounted them in the volumes tab, will I be able to use all the data that was stores in that VM when it was running on ESXi?

**Comment by futuretea** [comment]
With this method, in theory, all data saved on the disk should be migrated except the snapshots. 
CPU and memory need to be set manually.

**Comment by guangbochen** [comment]
The migration can be done by leveraging the  https://docs.harvesterhci.io/v1.1/advanced/vmimport addon with Harvester >= v1.1.0.
