### ISSUE TITLE
[BUG]VM Restarting occurred error

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2415]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/2a090711-8d96-48da-a0f0-7caa9f3e2b64)

**To Reproduce**
1. Create a VM
2. Go to VM Edit page
3. Check `Restart Now`
4. Save

**Expected behavior**

1. VM can be restarted when it's off.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
I realized why we restart the VM which is off status will throw errors.
There is no restart action if VM is off.

#### Off VM
<img width="645" alt="image" src="https://user-images.githubusercontent.com/15041915/176082182-46fd02d1-0cc7-4de5-9a73-90cd2c98e333.png">


#### Running VM
<img width="638" alt="image" src="https://user-images.githubusercontent.com/15041915/176081935-97aa18ff-b90d-4c04-97ee-be2ea99b35f8.png">

And then should we hide the restart button on VM edit page?
Or we should use `start` action to replace the `restart` action if VM is off.

@WuJun2016

**Comment by WuJun2016** [comment]
@DaiYuzeng 
1. disable `Restart Now` button
2. If restart exists, use restart, otherwise use start, if neither exists, disable the restart button

**Comment by lanfon72** [comment]
verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/177363223-5901972e-0097-4cf6-9d27-a48d28e04350.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-08af3d7c-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM
4. Edit Config of the VM, Checkbox **Restart Now** should be visible
5. Stop the VM
6. Edit Config of the VM, checkbox **Start Now** should be visible
