### ISSUE TITLE
[Doc] describe how to update the system configuration after installation

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2418]
**Is your feature request related to a problem? Please describe.**
Describe how to update the system configuration after installation.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
`/oem/99_custom.yaml`

**Comment by bk201** [comment]
Here are some items users might need to change:

- [x] Bonding slaves
- [x] DNS nameservers
- [x] NTP servers
- [x] SSH keys
- [x] Passwords

**Comment by Martin-Weiss** [comment]
Does this also cover expansion of the size for /usr/local? (just in case there is not sufficient)

**Comment by Martin-Weiss** [comment]
We also need to cover the change of timezone settings.

**Comment by bk201** [comment]
> Does this also cover expansion of the size for /usr/local? (just in case there is not sufficient)

@Martin-Weiss , do you mean removing the Longhorn default disk partition and extending the persistent partition?
```
vda    253:0    0   200G  0 disk
├─vda1 253:1    0     1M  0 part
├─vda2 253:2    0    50M  0 part /oem
├─vda3 253:3    0    15G  0 part /run/initramfs/cos-state
├─vda4 253:4    0     8G  0 part
├─vda5 253:5    0    60G  0 part /usr/local            <--- persistent partition
└─vda6 253:6    0 116.9G  0 part /var/lib/harvester/defaultdisk  <--- Longhorn default disk partition
```

This involves removing a Longhorn disk (move replicas on it), re-partitioning the disk, and growing persistent partition FS.
On the other hand, If the user chooses another disk for Longhorn during the installation, the persistent partition occupies all left space on the disk.

**Comment by Martin-Weiss** [comment]
> > Does this also cover expansion of the size for /usr/local? (just in case there is not sufficient)
> 
> @Martin-Weiss , do you mean removing the Longhorn default disk partition and extending the persistent partition?
> 
> ```
> vda    253:0    0   200G  0 disk
> ├─vda1 253:1    0     1M  0 part
> ├─vda2 253:2    0    50M  0 part /oem
> ├─vda3 253:3    0    15G  0 part /run/initramfs/cos-state
> ├─vda4 253:4    0     8G  0 part
> ├─vda5 253:5    0    60G  0 part /usr/local            <--- persistent partition
> └─vda6 253:6    0 116.9G  0 part /var/lib/harvester/defaultdisk  <--- Longhorn default disk partition
> ```
> 
> This involves removing a Longhorn disk (move replicas on it), re-partitioning the disk, and growing persistent partition FS. On the other hand, If the user chooses another disk for Longhorn during the installation, the persistent partition occupies all left space on the disk.

There are many ways how this could be done - maybe the answer is “remove longhorn disk and expand” or “reinstall node” or “use LVM and add an additional disk to the VG / expand the PV” or “use BTRFS and add an additional partition to the filesystem”..  basically this might come back to the question about the disk layout / file system design.. 

Background: the problem we ran into was to use a 140 GB disk as documented for “minimal” with 1.0.0 and then upgrade to 1.0.1 and here /usr/local has been too small.. so probably we should not even allow to install Harvester with a 140 GB disk?

**Comment by bk201** [comment]
@Martin-Weiss A minimum of 140GB is only for testing or development purposes. 500 GB+ is preferred.
For the disk layout or file system choices, it's the design of the elemental toolkit.

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss A minimum of 140GB is only for testing or development purposes. 500 GB+ is preferred.
> For the disk layout or file system choices, it's the design of the elemental toolkit.

And in a testing / dev environment we do not support upgrading? ;-)

I believe we have to increase the 140 GB to “enough”.. so that we can remove the “verify /usr/local free disk space” before doing an upgrade. As long as we have a “check disk space” in the docs for upgrading we also need to provide a guideline on how to solve the “not enough free disk space” situation.

**Comment by Martin-Weiss** [comment]
This also needs to document how to deal with "/oem/harvester.config" and it need to explain how to change settings WITHOUT rebooting..

**Comment by trexmaster** [comment]
@bk201 I would be in need of such a documentation as I need to update the DNS servers on our harvester cluster (DNS servers are being migrated) and would really like to avoid having to reboot the nodes for just that.

**Comment by qrkourier** [comment]
I have taken the new doc for a test drive and still have some questions about updating configuration after install. On my Harvester 1.1.1 bare metal installed from ISO the file is named `/oem/99_custom.yaml`, not `/oem/90_custom.yaml`.

Additionally, modifying the `initramfs` commands array has no effect. It seems those commands are not in fact executed.

I have documented my investigation in [this Rancher Slack thread](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1682266609585079?thread_ts=1682258209.835869&cid=C01GKHKAG0K).

My goal in that thread is to update the management VIP after rehoming the node in a new network.

**Comment by bk201** [comment]
Doc published: https://docs.harvesterhci.io/v1.1/install/update-harvester-configuration

**Comment by bk201** [comment]
@qrkourier we'll help you in the Slack thread. If there is an issue, feel free to open a new one.
