### ISSUE TITLE
Changing a VM's image does not change the running os

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#242]
**Steps to reproduce:**
1. Create a VM running a ubuntu OS
2. Edit it and change its image to k3os, then save it
3. Open the console and check its detail page

**Result:**
Nothing happens other than the VM name in detail page which is changed, the running os is still ubuntu

**Comment by WuJun2016** [comment]
@guangbochen  Can we modify image after VM is created successfully?

**Comment by guangbochen** [comment]
if it is the root-disk, then the answer is no, also we should disable modification of root image from the UI on VM upgrade.

**Comment by WuJun2016** [comment]
When editing, the image cannot be changed @DoNotSayYes

**Comment by DoNotSayYes** [comment]
Now the VM image is not allowed to change
![image](https://user-images.githubusercontent.com/57614736/101323271-5ca3de80-38a3-11eb-8aa5-adac1cf5d0c6.png)
