### ISSUE TITLE
[FEATURE] support bundle: support SLE Micro OS

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2420]
**Is your feature request related to a problem? Please describe.**

We'll rebase to SLE Micro https://github.com/harvester/harvester/issues/1933 base image and want to keep its `os-release` file.
The ID is changed to `sle-micro-rancher` and it will break support-bundle-kit collector.

**Describe the solution you'd like**

Support the ID too.

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-0f590757-head`. Close this issue.

### Result
Check can download support bundle correctly, check can access every file without empty


Checked every harvester nodes, the ID have changed to `sle-micro-rancher`
  - ID=`sle-micro-rancher`

  ```
  harvester-gv2ks:~ # cat /etc/os-release
  NAME="SLE Micro"
  VERSION="5.2"
  VERSION_ID="5.2"
  PRETTY_NAME="Harvester master"
  ID="sle-micro-rancher"
  ID_LIKE="suse"
  ANSI_COLOR="0;32"
  CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.2"
  VARIANT="Harvester"
  VARIANT_ID="Harvester-20220705"
  GRUB_ENTRY_NAME="Harvester master"
  ```


### Test Information
* Test Environment: 4 nodes harvester on dolphin bare machine
* Harvester version: master-0f590757-head

### Verify Steps
1. Download support bundle in support page
2. Extract the support bundle, check every file have content
3. ssh to harvester node
4. Check the /etc/os-release file content
