### ISSUE TITLE
[FEATURE] Export API and Scheme via go mod

### ISSUE THREAD

**Issue by orangedeng** [harvester/harvester#2427]
The [autok3s](https://github.com/cnrancher/autok3s) are using harvester as the k3s cluster provider. We hope that harvester can export `pkg/apis` and `pkg/generated` as go module which we need to import.

**Comment by orangedeng** [comment]
Please also consider export `pkg/builder` as it is the code entry to create VM in harvester.

**Comment by futuretea** [comment]
~Seems users can just import `github.com/harvester/harvester` directly, even if split into different packages, import these packages via go.mod will still have a lot of dependence~

**Comment by futuretea** [comment]
~currently, the block problem is the `pkg/generated` is a generated dir~

**Comment by bk201** [comment]
no plan to support this. Please re-open if have strong need.
