### ISSUE TITLE
Hardware Passthrough Support

### ISSUE THREAD

**Issue by mircea-pavel-anton** [harvester/harvester#2429]
**Is your feature request related to a problem? Please describe.**

I have tried migrating my Proxmox workloads to Harvester and I was faced with a lack of support for configuring hardware passthrough from the GUI. Among those workloads are things such as:

- virtualizing a TrueNAS instance -> passing through an HBA
- virtualizing a pfSense instance -> passing through multiple NICs
- virtualizing a workstation -> passing through GPUs and USB controllers

While I'd have no problem configuring these from the command line if needed, i also couldn't find proper documentation on how to implement these things.

**Describe the solution you'd like**

Ideally, after configuring the devices to use the vfio drivers, a drop down should be present allowing us to pick available devices to pass through, just like proxmox does it.

**Describe alternatives you've considered**

Alternatively, providing some documentation and examples of configuring such setups by hand would be a great first step, and much quicker than the "full" solution.

**Additional context**

N/A

**Comment by fanlix** [comment]
follow #1029  #1710

**Comment by mircea-pavel-anton** [comment]
> follow #1029  #1710

I am. I also replied to that thread and did some preliminary testing myself on the GPU passthrough, but i didn't manage to find anything on, for example, passing through a NIC or a HBA.

The progress on this topic will be tracked in that thread, i assume?

**Comment by kingnarmer** [comment]
Hello,

I need to be able to add storage LUNs presented to harvester nodes via Fiber Channel Qlogic HBA card. I can see the LUNs on OS level using "cat /proc/partitions", however I don't see them when I try to add disks. 

Appreciate help getting them added. 

Thanks

**Comment by tlehman** [comment]
This feature is now present as an addon in [release 1.1.0](https://github.com/harvester/harvester/releases/tag/v1.1.0). I have a video walkthrough of how to use the feature [here](https://tobilehman.com/posts/suse-harvester-pci/).

**Comment by mircea-pavel-anton** [comment]
@tlehman thanks for that! I will take a look tomorrow and set it up in my homelab.

**Comment by AndreiLazarescu** [comment]
Hello,

Does it support Qlogic NetXtreame 10Gb SPF NIC?

Kind regards,
Andrei
