### ISSUE TITLE
[BUG] Documentation needs to be changed for minimum disk size and minimum network connectivity

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2433]
**Describe the bug**
1 Gbit/s NICs are JUST useful / valid for PoCs
140 GB disk size is too smal as an upgrade to 1.0.1 will not work due to disk pressure (tested with 150 GB).

**Expected behavior**
Having longhorn replication, live migration and kubernetes communication - all on one 1 Gbit/s interface will not work stable and is not useful for production usage. So we must state clear that 1 Gbit/s interfaces are just for PoCs and not for production usage.

Upgrade 1.0.0 to 1.0.1  or any other upgrade should work with the minimum disk size.

It should also be documented how the space for upgrades can be increased in case there is not sufficient space available.

**Environment**
 - Harvester ISO version: 1.0.0 with upgrade to 1.0.1

**Comment by guangbochen** [comment]
Updated in the doc https://docs.harvesterhci.io/v1.0/#hardware-requirements to specify that the 140GB root disk and 1Gbps network card are just for testing purposes; a large size is required for production env. Feel free to reopen this issue if found this is not clear, thanks.
