### ISSUE TITLE
[BUG] Wrong mgmt bond MTU size during initial ISO installation

### ISSUE THREAD

**Issue by cognoz** [harvester/harvester#2437]
**Describe the bug**
Failed to configure network devices due to wrong mgmt bond's mtu
No configurable option.
![image](https://user-images.githubusercontent.com/32709700/177047833-d26ac5f1-abf0-4cc3-9fde-631550d42675.png)
![image](https://user-images.githubusercontent.com/32709700/177047838-3143539b-f693-4887-8290-b43c41c89d46.png)
![image](https://user-images.githubusercontent.com/32709700/177047844-6022a425-11b2-4199-8c0c-16178bf1693d.png)

**To Reproduce**
1. Create Virtual Machine/ Run server in network with supported mtu size < 1500
2. Run ISO installation

**Expected behavior**
Installation wizard automatically detects correct mtu size for bond
OR
Installation wizard support mtu customization option

**Support bundle**
**Environment**
 - Harvester ISO version:  v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 Openstack instance (10cpu/32 ram/150 ssd/2 vxlan interfaces with internet access)

**Additional context**
Tried to workaround problem with network scripts (setting up mtu in ifcfg-*) - no luck, bond's mtu persists at 1500 byte.

**Comment by Martin-Weiss** [comment]
As a workaround - could you try to adjust the MTU via /oem/99_custom.sh?

**Comment by cognoz** [comment]
> 

Hm, I cant find the file, directory is empty
![image](https://user-images.githubusercontent.com/32709700/177118315-5c1d57d7-aef8-4ad1-88ef-6c9523418b75.png)

**Comment by Martin-Weiss** [comment]
Ah - sorry - I misunderstood the problem.. the issue shows up already during installation... 

Could it be, that ens7 is not connected? ens3 shows "up" and ens7 shows "down".. maybe no link / no cable connected?

**Comment by w13915984028** [comment]
@bk201 @tjjh89017 
Please take a look, does the installer check and reuse, calculate the harvester-mgmt MTU based on the NIC's MTU?  Seemed if the NIC MTU is set to be a smaller value, the installer failed.

cc @guangbochen @yaocw2020

**Comment by guangbochen** [comment]
Users can config the MTU value via the [ipxe install ](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#installnetworks) but not exposed via the installer yet, seems we also need to support this config in the installer UI.
Additionally, the default MTU value is set to 1500 automatically of the `harvester-mgmt` bond and is not inherited from any NIC device.

**Comment by starbops** [comment]
In the PR harvester/harvester-installer#332, we'll make manually configuring the MTU size of `harvester-mgmt` bond possible. Users can specify the desired value of MTU right under the gateway field.

**Comment by lanfon72** [comment]
Verified this bug has been resolved.

![image](https://user-images.githubusercontent.com/5169694/192757588-73484301-07e7-4a37-9d1e-cbcada9b5774.png)
![image](https://user-images.githubusercontent.com/5169694/192758868-422887df-557c-4d8c-9ee8-2ab0f863f97a.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-7dd398f0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester via ISO and configure **IPv4 Method** with _static_
2. Inputbox `MTU (Optional)` should be available and optional
3. Configured MTU should reflect to the port's MTU after installation
