### ISSUE TITLE
[BUG] Harvester CSI persistent volumes are marked as "unsupported" in Rancher UI

### ISSUE THREAD

**Issue by janeczku** [harvester/harvester#2446]
**Describe the bug**
1. Create an RKE2 guest cluster on Harvester
2. Create PVC for the Harvester storage class
3. Navigate to the list of persistent volumes in the Cluster Explorer

**Actual Behavior**
The source for the persistent volume is set to "CSI (Unsupported)"

**Expected Behavior**
The source for the persistent volume should be set to "CSI (Harvester)" or similar

<img width="1159" alt="Screenshot 2022-07-05 at 13 22 59" src="https://user-images.githubusercontent.com/3813921/177316783-dd59eb4a-8739-49a4-adce-77ab5095cbb6.png">

**Comment by janeczku** [comment]
Ref: https://github.com/rancher/dashboard/issues/6270

**Comment by WuJun2016** [comment]
Already fixed

<img width="1712" alt="image" src="https://user-images.githubusercontent.com/24985926/208044580-eee8231d-87ce-475d-bea3-e6ce224f96cd.png">

**Comment by irishgordo** [comment]
Thanks @WuJun2016 ,
This looks good as mentioned and seems to be fixed.
Tested with Rancher v2.7.0 & Harvester Version: master-929b6de2-head.
RKE2 Guest Cluster was built with Kubernetes Version: v1.24.8.
![Screenshot from 2023-01-03 11-17-16](https://user-images.githubusercontent.com/5370752/210426204-c189ec53-92d8-4a0e-8eb3-c6f0d2f94e18.png)
I'll go ahead and close this out :smile:

**Comment by irishgordo** [comment]
@WuJun2016 
Re-opening this as I'm noticing this on RKE1 v1.23.16 w/:
- v1.1.2-rc3 Harvester
- v2.6.11 Rancher

![Screenshot from 2023-03-13 11-37-35](https://user-images.githubusercontent.com/5370752/224798288-14ed2ae6-c9ca-46c2-8a70-6ceb18b11524.png)
![Screenshot from 2023-03-13 11-34-25](https://user-images.githubusercontent.com/5370752/224798291-07ddce81-3475-4d3e-93ff-92c93a14d8ee.png)

**Comment by WuJun2016** [comment]
Hi,  @irishgordo  This was fixed by rancher in 2.7-head.

Rancher v2.6.11 is already released, So we can't fix this in 2.6.11.

**Comment by bk201** [comment]
Move to v1.2.0 and be fixed in Rancher 2.7.2.

**Comment by WuJun2016** [comment]
@WuJun2016   need backport to `release-2-6`

**Comment by WuJun2016** [comment]
Hi @irishgordo   `rancher 2.6` is in the `EOL` stage, so we're not going to fix this issue.  I think we can close this issue.

**Comment by irishgordo** [comment]
@WuJun2016 that sounds good :smile:  - I'll go ahead and close this out
