### ISSUE TITLE
[backport v1.0][BUG] harvester installer - always first attempt failed if before was linux installed

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2450]
backport the issue https://github.com/harvester/harvester/issues/2230

Test plan: https://github.com/harvester/tests/issues/351

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM**
* Harvester Version: **v1.0-3b6ab0d1-head**

### Verify Steps:
1. Install Ubuntu with LVM configured disk
2. Install Harvester on the disk which ubuntu installed
3. Harvester should be installed successfully
