### ISSUE TITLE
[FEATURE] Bump CCM to golang v1.18.3

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#2456]
**Is your feature request related to a problem? Please describe.**
Need to bump the CCM dependency libraries, harvester to master, golang to v1.18.3, and k8s version to v1.23.x respectively.

**Describe the solution you'd like**
- [x] harvester:master
- [x] golang:v1.18.3
- [x] k8s:v1.23.x

**Comment by guangbochen** [comment]
close as the Golang version bump of Harvester cloud provider is addressed via https://github.com/harvester/cloud-provider-harvester/pull/22 and the image CI build is successful.
