### ISSUE TITLE
[Question] Why is the alert manager not functional inside the embedded Rancher dashboard?

### ISSUE THREAD

**Issue by KarlSK8** [harvester/harvester#2459]
This is most probably preventing me from creating email alerts, because it keeps on asking for alert manager config whenever I try to save the alert configuration.
![harv2](https://user-images.githubusercontent.com/79142047/177571725-e7836e42-83bc-494c-95ab-6efdb04c9ed6.PNG)
![harv3](https://user-images.githubusercontent.com/79142047/177571729-fb4cb2d9-a7e1-4b02-bacc-af6291836a21.PNG)

**Comment by w13915984028** [comment]
Sorry. The rancher-monitoring `alter manager` is not enabled in Harvester by default. The related CRD/POD are not existing. That's the reason.

It is not in the Harvester feature set yet.

**Comment by KarlSK8** [comment]
So creating alerts is still not possible in harvester?

**Comment by w13915984028** [comment]
Not possible now.
