### ISSUE TITLE
[BUG] Standard user with project owner permissions can see namespaces not in projects

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2460]
**Describe the bug**

When you create a standard user with project owner permissions to a new project they can see harvester-public in the namespaces, although they don't have write access to it.
**To Reproduce**
1. Install Harvester via ipxe-examples
2. Install Rancher v2.6.6 via Docker
3. import Harvester into Rancher
4. Create new project via admin user in imported Harvester
5. Create new namespace in project
6. Create new standeard user
7. Assign new user to project as project owner
8. Log in as new standard user
9. Navigate to Harvester dashboard via virtualization management in Rancher
10. Create a new image
11. Check in projects which namespaces and projects that user has access to.

**Expected behavior**

User should only be abl,e to see projects and namespaces that they have access to.
**Support bundle**
[supportbundle_2bab88e4-c449-4ef7-9c7a-b96e177c9714_2022-07-06T19-17-31Z.zip](https://github.com/harvester/harvester/files/9057508/supportbundle_2bab88e4-c449-4ef7-9c7a-b96e177c9714_2022-07-06T19-17-31Z.zip)

**Environment**
 - Harvester ISO version: master-a926a44e-head
 - Rancher version: v2.6.6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe vagrant setup with 3 nodes

**Additional context**

I had to change the ui-index for Rancher v2.6.6 to https://releases.rancher.com/harvester-ui/dashboard/latest/index.html in order to get the projects tab to show up on the Harvester dashboard through Rancher virtualization.

It looks like the standard user shows they have access to `harvester-public`. It looks like this is because it isn't in a project. However the user can't create any resources in that namespace. This is an issue though because in this case the harvester-public namespace is alphabetically higher in the list so it's what all new requests default to unless you change them. I'm closing this issue since that issue is out of scope
![Screenshot_20220706_120420](https://user-images.githubusercontent.com/83787952/177627026-2d69e3db-67fa-45ef-bde2-329ad1d5bb5c.png)

**Comment by futuretea** [comment]
@noahgildersleeve  harvestre-public can be seen because we add special rbac to make it readable for all authenticated users
https://github.com/harvester/harvester/blob/0f5907575a3ef486a89e2d1f6dd60912feb613b2/pkg/data/public.go#L14
https://github.com/harvester/harvester/blob/0f5907575a3ef486a89e2d1f6dd60912feb613b2/pkg/data/rbac.go#L9
Other not in project namespaces will not be seen.
Users can select public images and networks in the harvester-public namespace when they are creating vms

**Comment by WuJun2016** [comment]
We will make enhancements in this issue，  https://github.com/harvester/harvester/issues/1986 ， So I think we can close this issue.  @noahgildersleeve

**Comment by noahgildersleeve** [comment]
Tested with harvester v1.1.1 and Rancher v2.7.0. Verified that standard user with project permissions could only see

## Verification Steps

1. Install Harvester via ipxe-examples
2. Install Rancher v2.6.6 via Docker
3. import Harvester into Rancher
4. Create new project via admin user in imported Harvester
5. Create new namespace in project
6. Create new standard user
7. Assign new user to project as project owner
8. Create a new namespace in the not in a project section
![Screenshot_20230208_113713](https://user-images.githubusercontent.com/83787952/217634164-e016633e-5177-4c43-8a24-f83f8ba74a5a.png)

9. Log in as new standard user
10. Navigate to Harvester dashboard via virtualization management in Rancher
11. Create a new image
12. Check in projects which namespaces and projects that user has access to.

## Expected Results
- You should see the test project and harvester-public, but not the other namespace in no project

![Screenshot_20230208_113648](https://user-images.githubusercontent.com/83787952/217634203-b7063c11-5144-4a69-a7df-72e95775ac45.png)
