### ISSUE TITLE
[BUG] [terraform provider] wrong harvester_network assigned when using data source

### ISSUE THREAD

**Issue by andrewg-xyz** [harvester/harvester#2461]
**Describe the bug**
When using the harvester_network data source, the namespace is [documented](https://registry.terraform.io/providers/harvester/harvester/latest/docs/data-sources/network) as optional. When not included, the wrong network is assigned to the VM.

**To Reproduce**
1. Use terraform provider to provision a VM 
```terraform
...
resource "harvester_virtualmachine" "vm" {
...
  network_interface {
    name         = "nic"
    network_name = data.harvester_network.vlan1.id
  }
...
}

data "harvester_network" "vlan1" {
  name      = var.vlan_name
#  namespace = "harvester-public"
}
```
2. terraform apply
3. Harvester UI reports "management Network" (which is not the network specified)
![image](https://user-images.githubusercontent.com/46836330/177653636-e22d0a58-894c-4a3f-bc38-09156d30b1b7.png)
4. VM does not connect to the desired network

NOTE: When the `namespace = "harvester-public"` is specified in the data source, the appropriate network is associated with the VM.

**Expected behavior**
Either:
 The provider assigned the specified vlan/network
Or:
 The provider documents the required argument "namespace" 

**Support bundle**
Can provide if needed.

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell R620 (2x)

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/178469413-b3a5cd6b-73dc-4981-93d6-45aba160ab7f.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0-3b6ab0d1-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Install **terraform-harvester-provider** (using [master-head](https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-master-head-docker-image-for-testing) for testing)
3. Execute `terraform init`
4. Create the file `network.tf` as following snippets, then  execute `terraform import harvester_clusternetwork.vlan vlan` to import default vlan settings
```terraform
resource "harvester_clusternetwork" "vlan" {
  name                 = "vlan"
  enable               = true
  default_physical_nic = "harvester-mgmt"
}
resource "harvester_network" "vlan1" {
  name      = "vlan1"
  namespace = "harvester-public"

  vlan_id = 1
  route_mode = "auto"
}
```
5. execute `terraform apply`
6. Append following snippets into `network.tf`, then execute `terraform apply` again
```terraform
data "harvester_network" "vlan1" {
  name      = "vlan1"
  # namespace = "harvester-public"
}
```
7. Error message `Error: network-attachment-definitions.k8s.cni.cncf.io "vlan1" not found` should displayed
8. Update `# namespace = "harvester-public"` to `namespace = "harvester-public"` in file `network.tf`, then execute `terraform apply` again
9. No Error message should displayed, and No Changes will applied.
