### ISSUE TITLE
[backport v1.0][FEATURE] Rebase Harvester on SLE Micro for Rancher

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2463]
backport the issue https://github.com/harvester/harvester/issues/1933

**Comment by tjjh89017** [comment]
PR: https://github.com/harvester/harvester-installer/pull/300

**Comment by lanfon72** [comment]
Verified this feature have a case not fixed:
- Files of nodes in support bundle are missing

![image](https://user-images.githubusercontent.com/5169694/178741917-646e95f3-daae-42bd-8775-43e46831cdfd.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.0-416db269-head**
* **ui-source** Option: **Auto**
* **ui-index**: **https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html**

### Test cases:
- [ ] support bundle generate and files
- [x] API P1 test cases on [harvester e2e tests](https://github.com/harvester/tests/tree/main/harvester_e2e_tests)
- [x] Node's version check
![image](https://user-images.githubusercontent.com/5169694/178742887-4d7a48e6-11b9-43c4-9254-37cac789b764.png)

**Comment by bk201** [comment]
@lanfon72 Is the support bundle the only missing thing? The support bundle needs [this issue](https://github.com/harvester/harvester/issues/2420) (and its backport) to be resolved. Could close this one and verify the support bundle feature until https://github.com/harvester/harvester/issues/2464 is done.

**Comment by lanfon72** [comment]
the test case of support bundle be verified via #2464
