### ISSUE TITLE
[BUG] VM shows "off" after clicking on "stop" but the VM is still running / in shutdown process

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2465]
**Describe the bug**
When stopping a VM via the UI by hitting the "stop" button - the UI instantly shows the VM as "off" but in reality the VM is still running and "shutting down".

**To Reproduce**
See above. Create VM, start VM with processes that take a long time to shutdown, click on "stop" for the VM and see the VM shown "off" in the UI while the console of the VM still shows the running server.

**Expected behavior**
The UI should show the real status  - either "Running" or better "Send Shutdown to Guest OS" / "Shutting Down".

**Environment**
 - Harvester ISO version: 1.0.2

**Comment by guangbochen** [comment]
Seems the UI will set the VM state to `off` immediately while the user clicks the stop action button, however, the VMI's status is still `Running`, @WuJun2016 can u please take a look to see if we can make an improvement of this, thanks.

**Comment by lanfon72** [comment]
Verified this bug had few cases not fixed:
- executing `poweroff` inside the VM
- executing `shutdown now` inside the VM

The VM's State will not be updated into `Stop`.

![image](https://user-images.githubusercontent.com/5169694/178206560-32b59bb7-888c-44dc-8099-556f9be6a00d.png)
![image](https://user-images.githubusercontent.com/5169694/178206646-6013acda-c4fb-469a-9ebe-2167b47a5360.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-0f590757-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM `vm1` and wait until it started
4. Stop the VM `vm1` with following methods: Clicking `Stop` button, executing `shutdown now` and `poweroff` inside the VM
5. VM should entering `Stopping` State
6. VM's State should be updated from `Stopping` into `Stop` in few minutes

**Comment by WuJun2016** [comment]
HI，@FrankYang0529 ，  I noticed that when the user shuts down the VM by `poweroff` or `shutdown now`, the vmi is not deleted, is this as expected ?  
https://github.com/harvester/dashboard/blob/81d50b32762c489a47fabf4c756872be4c35aac7/shell/models/harvester/kubevirt.io.virtualmachine.js#L501

**Comment by lanfon72** [comment]
the root cause: https://github.com/harvester/harvester/issues/2154

**Comment by WuJun2016** [comment]
I've noticed that if you shut down a VM via `shutdown now` or `poweroff`, the vm is usually stopped immediately.

**Comment by Martin-Weiss** [comment]
> I've noticed that if you shut down a VM via `shutdown now` or `poweroff`, the vm is usually stopped immediately.

I believe this really depends on the services / workload within the VM and the speed of the hardware. I have rke2 cluster nodes that need much more time to shut down (much more than 30 seconds)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/178458370-7141dca2-81f1-444d-9e4b-f7ae340123f2.png)

Test Information
----
* Environment: **baremetal DL160 5 nodes**
* Harvester Version: **master-0f590757-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM `vm1` and wait until it started
4. Stop the VM `vm1` with following methods: Clicking `Stop` button, executing `shutdown now` and `poweroff` inside the VM
5. VM should entering `Stopping` State
6. VM's State should be updated from `Stopping` into `Stop` in few minutes
