### ISSUE TITLE
[BUG] Web VNC Console does not resize window properly during initial start

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2467]
**Describe the bug**
When ever we open a console in "web vnc" the new window is too small and needs to be resized manually to see the full screen / command line.

**To Reproduce**
Install a VM i.e. with SLES 15 SP4 (without graphical console) - and then open web vnc.

Examle:
![grafik](https://user-images.githubusercontent.com/13362573/177739625-d3472d84-a7e8-4fae-9075-7f4e282dd1c2.png)

**Expected behavior**
The window should open with the correct size and without scroll bars so that the user does not have to re-size the window, always.

Example:
![grafik](https://user-images.githubusercontent.com/13362573/177739963-73b0a8e0-3bec-42ab-a535-ae91ace407a3.png)

**Environment**
 - Harvester ISO version: 1.0.2

**Comment by torchiaf** [comment]
@mergify backport release-harvester-v1.2 release-harvester-v1.3

**Comment by TachunLin** [comment]
Verified **fixed** on `master-3a70b75-head`  (24/07/30). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Web vnc window with the correct size and without scroll bars $~~$</summary>

  1. On Laptop of smaller screen, after open the web vnc console of SLES15 sp3 VM, the window display the correct size without scroll that user don't need to resize the window to see full content 

  ![image](https://github.com/user-attachments/assets/6ab9f36a-eb59-4cbb-97ae-bcd094f76621)


  https://github.com/user-attachments/assets/2d8c8c98-6521-4d36-82fa-1e9d5589d7f5


  
  
  2. Also tested on the desktop with larger screen, the window can also display the correct size


  ![image](https://github.com/user-attachments/assets/0953694a-5e68-45a1-8b81-f655441ca17e)
  
  
  https://github.com/user-attachments/assets/3e134021-cd8b-4403-9174-1cb58e74ab4a




 </details>


### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: `master-3a70b75-head`  (24/07/30)

### Verify Steps
<details><summary> Content </summary>

  1. Create a SLES15 sp3 virtual machine
  2. After the virtual machine in running state
  3. Open the web vnc of the vm
  4. Check the window size and content without scroll bar

</details>
