### ISSUE TITLE
[FEATURE] Harvester uses active-backup as the default bond mode

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2472]
**Is your feature request related to a problem? Please describe.**

Harvester uses balance-tlb mode (5) as the default bond mode of management NICs, it's advantage is the peer SWITCH does not need additional config.
https://github.com/harvester/harvester-installer/pull/128

When it comes to Harvester network for guest VM, this mode has potential limitations, as the `balance-tlb` may rewrite SRC MAC of guest VM.

**Describe the solution you'd like**

Use `active-backup` as the default `bond` mode.

And also has clear document about those `bond` modes and how to use them. How to change the `bond` mode after installation.

**Describe alternatives you've considered**

**Additional context**

A mentioned limitation:
https://serverfault.com/questions/788480/linux-bonding-balance-tlb-kvm-guests-and-l2-switches-unicast-flooding

**Comment by tjjh89017** [comment]
### Test Plan

1. check installer UI has default bond mode as active-backup mode.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/184838334-a723f066-8eef-4cbc-ab66-6e02b758823d.png)
![image](https://user-images.githubusercontent.com/5169694/184839241-3702fa7c-950e-4b51-8c18-d29d4121f848.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-d2faf778-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester via ISO
2. The default **Bond Mode** should select `active-backup`
3. Ater installed with `active-backup` mode, login to console
4. Execute `cat /etc/sysconfig/network/ifcfg-harvester-mgmt`, **BONDING_MODULE_OPTS** should contains `mode=active-backup`
