### ISSUE TITLE
[BUG] Hosts page showing incorrect Disk State

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2478]
### Describe the bug

https://user-images.githubusercontent.com/5169694/178231169-bf6f0015-8c25-43b1-8209-00995e584871.mp4

### To Reproduce
1. Install Harvester master-head
2. Login to Dashboard then navigate to Hosts page
3. **Disk State** should be `Health` if it is not encountering any isuses

### Expected behavior
1. Hosts' **Disk State** should be health (in the health cluster)
2. `Ready` and `Schedulable` should be green color in disk condition of host's details

## Environment:
 - Harvester ISO version: **master-0f590757-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
In the cluster of `v1.0-head`, it displays correctly.

https://user-images.githubusercontent.com/5169694/178236140-98fe17e5-8983-4730-99fb-0c16addddf56.mp4

**Comment by lanfon72** [comment]
It works on `v1.0-head` correctly, remove label `backport-needed/1.0.3`
![image](https://user-images.githubusercontent.com/5169694/178713104-62e645e9-03ac-4d22-a770-a289c4f4bb15.png)

**Comment by n313893254** [comment]
Move pipeline to implement as storage used is zero on the dashboard page. Will be fixed in this [PR](https://github.com/harvester/dashboard/pull/380).

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-aa3d95d2-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2478#issue-1300461060
