### ISSUE TITLE
volume is not attach with vm

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#248]
Steps to reproduce:

On the VM create page, add a disk
Volume is not associated with VM

![image](https://user-images.githubusercontent.com/24985926/99232207-96497280-282c-11eb-9620-d002d47ab769.png)

**Comment by futuretea** [comment]
* On the create page, this problem did not reproduce.
* If it is edit page, it will not mount automatically now.
 
KVM can hotplug disk,  in the latest kubevirt release `v0.36.0-rc.0`, kubevirt can hotplug DataVolume and PVC volumes into a running Virtual Machine

links:
* https://github.com/kubevirt/kubevirt/issues/4250
* https://github.com/kubevirt/kubevirt/pull/4458

/cc @guangbochen @WuJun2016

**Comment by futuretea** [comment]
After editing the vm and restarting the vm, it should be mounted normally.

**Comment by futuretea** [comment]
There is a time difference between the time when the volume is added to the vm‘s filed and the volume is created.
So after adding the volume, `Attached VM` may not be displayed immediately.

**Comment by DoNotSayYes** [comment]
It takes time to have the volumes mounted to the VM, validated.
