### ISSUE TITLE
[BUG] 3rd node hangs on 'NotReady' after fresh install.

### ISSUE THREAD

**Issue by crazyelectron-io** [harvester/harvester#2481]
**Describe the bug**
3rd node gets stuck at 'NotReady' after fresh install. When SSH-ing into the server the `console.log` shows:

```
...
time="2022-07-11T19:09:44Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:12:29Z" level=info msg="state: {installed:false firstHost:false managementURL:}"
time="2022-07-11T19:12:29Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:12:29Z" level=error msg="exit status 1%!(EXTRA string=)"
...
time="2022-07-11T19:27:59Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:27:59Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:28:29Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:28:29Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:28:59Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:28:59Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:29:29Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:29:29Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:29:59Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:29:59Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:30:29Z" level=error msg="exit status 1%!(EXTRA string=)"
time="2022-07-11T19:30:29Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:30:59Z" level=error msg="exit status 1error: You must be logged in to the server (Unauthorized)\n"
time="2022-07-11T19:30:59Z" level=error msg="exit status 1%!(EXTRA string=)"
```

**To Reproduce**
1. Flash Harvester 1.02 iso (amd64) on USB-stick and boot into it.
2. Select to Join a node.
3. Fill in name, IP details, join-token, password, DNS, etc.
4. Installation completes and reboots to fresh install of Harvester.
5. Console is stuck at 'NOT READY'.

**Environment**
 - Harvester ISO version: Harvester 1.02 (amd64)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
Baremetal on Intel Core i9-10900 CPU with 128GB RAM and 1TB NVMe SSD.

**Additional context**
This node worked just fine as a Proxmox cluster node for the last few weeks.

**Comment by bk201** [comment]
@crazyelectron-io Thanks for reporting.
Does the 3rd node appear in your existing Harvester cluster? If possible, could you provide a support bundle:
cluster: https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#generate-a-support-bundle
3rd node: https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information

**Comment by crazyelectron-io** [comment]
Thanks for your suggestions, but I have meanwhile reinstalled successfully (just by repeating the installation from scratch one more time). Since I am in the process of configuring a Kubernetes cluster with Longhorn storage, I don't want to redo the Harvester installation at this time...

**Comment by bk201** [comment]
@crazyelectron-io Thanks for the feedback. Feel free to re-open the issue if you see it again.
