### ISSUE TITLE
[BUG] After clearing the userData, then select install guest agent is invalid

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2487]
**Describe the bug**

After clearing the userData, then select `install guest agent` is invalid

**To Reproduce**
1.  go to vm create page
2.  Fill name, cpu, memory, select image 
3. click `Advanced Options` tab
4.  uncheck `install guest agent`,  
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/246abfe0-b6fc-4bed-a98d-54b1336824bb)
5. Clear the userData
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/508c11cd-9d05-4f6e-b12c-648cc3db3c84)
6. check `install guest agent`
7. userData is still empty

**Expected behavior**

At this point the userData should contain the data of the quem guest agent

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
Hi @TachunLin  ,    here is a little enhancement.
1. If there is no `#cloud-config` in userData when you check install guest agent, UI need to add it automatically, otherwise it will not take effect.

test step:
1. go to create vm page, click `Advanced Options` tab
2. uncheck `inatall guest agent`,  clear user data
![image](https://user-images.githubusercontent.com/24985926/197158184-07da136c-f9a0-4ba0-a91f-b85ff7a08860.png)
3. check `install guest agent`
4. we need to add `#cloud-config` comment automatically at this time
<img width="1721" alt="image" src="https://user-images.githubusercontent.com/24985926/197158546-24b32012-f826-4802-a8b2-647df80f38b6.png">
5. However, if #cloud-config already exists, checking the intall guest agent will not automatically add this comment
e.g: 
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/24985926/197159291-9aa487b0-39a6-44cd-9c51-566cef0b221e.png">

<img width="1697" alt="image" src="https://user-images.githubusercontent.com/24985926/197159345-d0ebe687-19d3-4b63-804d-7a92f1bd269f.png">

**Comment by TachunLin** [comment]
Verified **fixed** on `master-7b698413-head` (10/22). Close this issue.

### Result
* After unchecking the `Install guest agent` all user data would be cleaned, then when we check it again, the guest agent user data will be added back 

https://user-images.githubusercontent.com/29251855/197442365-5cdc476e-0cd7-47f2-82e4-c3653f277243.mp4



* When user data already have `#cloud-config`, checking the install guest agent will not add the #cloud-config again 


https://user-images.githubusercontent.com/29251855/197442505-f4a2489f-2883-4c46-b94e-8f8b3aee938a.mp4



### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-7b698413-head` (10/22)

### Verify Steps
1. Go to create vm page, click `Advanced Options` tab
2. Uncheck the `inatall guest agent` to clear user data
3. check the `install guest agent`
4. Manually add `#cloud-config` comment to user data
5. Check the `install guest agent` again
