### ISSUE TITLE
[FEATURE] VM's detail UI need to add node scheduling, need to add pod scheduling to VM config

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#2491]
**Describe the solution you'd like**

1. VM's detail UI needs to add node scheduling.
<img width="1112" alt="image" src="https://user-images.githubusercontent.com/3347460/178639809-4a348a20-3663-44ad-bfe9-8aeed304dcbc.png">

2. VM's config UI needs to add pod scheduling (include create, edit, view. ).

**Describe alternatives you've considered**

**Additional context**

**Comment by WuJun2016** [comment]
To be consistent with rke2,  do not add this feature for now.

**Comment by WuJun2016** [comment]
@guangbochen   I think if this feature is not needed now, we can close this issue or move it out of v1.1.0 milestone.

**Comment by DaiYuzeng** [comment]
Duplicated with https://github.com/harvester/harvester/issues/2317
