### ISSUE TITLE
[FEATURE] Add rancherd integration test for Harvester needs in the Rancher repo

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2492]
**Is your feature request related to a problem? Please describe.**
Harvester is using [rancherd](https://github.com/harvester/rancherd) for its initial RKE2 cluster bootstrap and configuration, it also involves the embedded Rancher to adapt the node management through the [plans](https://github.com/rancher/rancher/tree/release/v2.6/pkg/provisioningv2/rke2/planner), will need to add integration test to the Rancher repo for Harvester dependency checks. 

**Describe the solution you'd like**
Add rancherd integration test for Harvester needs in the rancher repo.

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
One idea is to integrate with https://github.com/harvester/vagrant-rancherd and use a customer runner.

**Comment by bk201** [comment]
Can be closed if we move to the direction in https://github.com/harvester/harvester/issues/5278
