### ISSUE TITLE
Windows 10 and Server 2019 virtual machines have a unknown device vport0p1

### ISSUE THREAD

**Issue by ssdabl** [harvester/harvester#2495]
What is this device used for (vport0p1), and is there a driver for Windows 10 and Server 2019 and Server 2022?

**Comment by guangbochen** [comment]
may refer to https://github.com/harvester/harvester/issues/276#issuecomment-745155932

**Comment by ssdabl** [comment]
It's a Redhat VIO Serial Port - I can't find drivers for it.

**Comment by ssdabl** [comment]
it's created in every Windows virtual machine.

**Comment by ssdabl** [comment]
> may refer to [#276 (comment)](https://github.com/harvester/harvester/issues/276#issuecomment-745155932)

That's using an old version of the guest drivers - I'm using a new version and the device is still showing up as unknown
