### ISSUE TITLE
How do you rename a virtual machine?

### ISSUE THREAD

**Issue by ssdabl** [harvester/harvester#2496]
I edited the YAML file, but the name of the virtual machine was not changed.  How can I rename a vm?

**Comment by ssdabl** [comment]
I figured it out

**Comment by BringerOD** [comment]
How do you do it?

**Comment by ssdabl** [comment]
It didn't work - I edited the yaml configuration, but the name did not update on the console.  Is there a way to rename vms?

**Comment by guangbochen** [comment]
You are not allowed to change the metadata name as it is a unique ID and an immutable field in the k8s world, but we could consider adding a `displayName` field so users can update it when needed.
