### ISSUE TITLE
vm event logs shows vms are tainted

### ISSUE THREAD

**Issue by ssdabl** [harvester/harvester#2497]
[virt-launcher-vm1-m4l8l_undefined.log](https://github.com/harvester/harvester/files/9104438/virt-launcher-vm1-m4l8l_undefined.log)

These messages are constantly scrolling in all virtual machine event logs.

**Comment by guangbochen** [comment]
I found a similar case in the kubevirt and it only occurs with migration tests https://github.com/kubevirt/kubevirt/issues/2704, have u done any similar operation to ur VMs?

**Comment by ssdabl** [comment]
Migration works fine.  Everything looks ok - no major issues, but the messages are constantly scrolling when windows server 2019 or windows 10 is running.
