### ISSUE TITLE
[Doc] Harvester CSI driver attaches via SCSI instead of VirtIO

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2501]
**Describe the bug**
When using the harvester CSI we can see that the bus used for attaching harvester volumes is SCSI and not VirtIO (used for the OS disks).

**To Reproduce**
Deploy downstream RKE2 cluster on top of harvester and use the harvester CSI / harvester storage class.

**Expected behavior**
The bus used for attaching volumes should be the same as the one used for the OS, per default.
A configuration option (in the CSI helm chart) or a specification in the storage class should be available where we can speficy this.

**Environment**
 - Harvester ISO version: 1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM
 - Rancher 2.6.6
 - RKE2 v1.22.10+rke2r2

**Comment by futuretea** [comment]
KubeVirt only support SCSI for hotplug volume
https://github.com/kubevirt/kubevirt/issues/5080#issuecomment-785183128

**Comment by Martin-Weiss** [comment]
Thanks for that update. Could we get this info added as hint to the documentation? 
Maybe in the volumes section or in the harvester csi section?

**Comment by guangbochen** [comment]
Close as the doc PR is merged and available on https://docs.harvesterhci.io/v1.1/vm/hotplug-volume
