### ISSUE TITLE
[BUG] UI can't show Terraform applied user data

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2503]
### Describe the bug
When creating VM by terraform provider, `cloudinit.user_data` will not be applied to the VM.

### To Reproduce
1. Create file `vm.tf` with following snippet
```tf
resource "harvester_image" "issue-2255" {
  name      = "issue-2255"
  namespace = "harvester-public"

  display_name = "issue-2255"
  source_type  = "download"
  url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}


resource "harvester_virtualmachine" "issue-2255" {
  name      = "issue-2255"
  namespace = "harvester-public"
  description = "test issue-2255"
  restart_after_update = false

  cpu    = 2
  memory = "2Gi"

  run_strategy = "RerunOnFailure"
  hostname     = "issue-2255"
  machine_type = "q35"

  network_interface {
    name         = "default"
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = harvester_image.issue-2255.id
    auto_delete = true
  }

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      user: ubuntu
      password: root
      chpasswd:
        expire: false
      ssh_pwauth: true
      package_update: true
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent
      EOF
    network_data = ""
  }
}
```
2. execute `terraform apply`
3. Image will be created, VM will be created with empty **User Data**

### Expected behavior
**User Data** should be applied

## Environment:
 - Harvester ISO version: **v1.0-416db269-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**

### Additional context

https://user-images.githubusercontent.com/5169694/178966790-9a8d8126-d5a8-47ec-a75a-7a1f1d97dc12.mp4

issue discovered when testing #2452

**Comment by futuretea** [comment]
terraform provider harvester support three methods to add userdata like kubevirt http://kubevirt.io/api-reference/v0.49.0/definitions.html#_v1_cloudinitnocloudsource
1. user_data
2. user_data_base64
3. user_data_secret_name 

Harvester UI only use secret to apply userdata

If you check the vm yaml, you will see the user_data is applied
just Harvester UI didn't show the user data content configured by the first way

**Comment by guangbochen** [comment]
can we default to use `user_data_secret_name` as it will be consistent with the UI behavior, thanks?

**Comment by lanfon72** [comment]
This bug more like a integration case, when user deployed VMs via terraform, and they should still able to modify _User Data_ via dashboard UI.

**Comment by lanfon72** [comment]
As this also happened when user update the VM with `Edit as YAML`, update labels to mark it is UI issue.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/186118757-79a584f5-e11e-4f68-b2ff-21fb980d45c6.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-dc6a3089-head**
* **ui-source** Option: **Auto**
* Harvester Terraform Provider Version: **v0.5.1**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2503#issue-1304616932
