### ISSUE TITLE
[Question] Longhorn and disk allocation for K8s cluster PV's

### ISSUE THREAD

**Issue by crazyelectron-io** [harvester/harvester#2507]
What I want to setup with Harvester v1.02 is a multi-node (3 bare metal systems for starters) Harvester cluster running a few plain vanilla VM's and 2 Kubernetes (RKE2 and/or K3s) clusters. I am struggling with the disk configuration for such a setup.

The physical configuration details: 3 bare metal nodes with 20 cores each, 128GB RAM, 1TB NVMe disks for Harvester installation (and some generic VM storage), 4x 8TB SSD for Kubernetes PV storage on each node.

The vanilla VM workloads are straightforward. I can just give them a volume from the Harvester (Longhorn-based) storage created during Harvester installation and let them run. One question I have to make sure I understand the architecture: are these volumes - that are based on the default Harvester/Longhorn storage created at install time on the NVMe disks - replicated across the 3 physical nodes? So, can I just failover and let it run on another node?

The real confusion comes from the Kubernetes storage configuration. I have created a 6 node RKE2 cluster and want to provide that cluster with persistent storage (PV/PVC) that is replicated across all Harvester nodes/hosts so I can leverage the HA/Failover features. As an example scenario: when running a pod on Harvester node 1 which has persistent storage that fails-over to Harvester node 2, its persistent  storage should be available on node 2 as replicated storage when the pod spins up there.

Now the confusion...
Longhorn is part of the Harvester setup and I was wondering if I could/should use that to add those 4 SSD's to each Harvester host/node and create Harvester/Longhorn volumes for the cluster VM's to provision K8s PV's. Also, when adding those 4 disks to the Harvester host (or combine them with LVM), will any LH volume created out of that and assigned to a K8s cluster VM/node be covered by Longhorn replication across the Harvester nodes?
Or...
Should I install Longhorn on the RKE2 cluster and somehow(?) attach the disks to the VMs of that cluster, mount them in the VM, and add them to Longhorn running in the Kubernetes Cluster?
Or...
Should I add the disks to the Harvester nodes, create volumes in Harvester/Longhorn and add those volumes to the Kubernetes nodes/VMs to create PVs?

I suppose there are multiple options, but what are the key pro's and con's when it comes to performance (loss) and redundancy/failover (particularly across Harvester nodes)?

**Comment by Martin-Weiss** [comment]
In case you give the 8 TB disks to the Harvester "longhorn" and use them via Harvester CSI in the downstream cluster I believe you have more flexibilty especially because you can add additional clusters and workload to the environment without having the large 8 TB disks locked to a subset of VMs..

Let Harvesters Longhorn distribute the data and take care about fault tolerance - yes - Longhorn will create three replicas of the volumes per default and distribute them among the physical nodes.

**Comment by crazyelectron-io** [comment]
@Martin-Weiss Thanks for your reply. That makes totally sense.

**Comment by dseralathan** [comment]
https://github.com/harvester/harvester/issues/3342

We have 4 node cluster, on one node I have added a 40 TB NFS disk . On longhorn I can see the space is scheduled and shows the size of 40 TB . when I try to create a VM on that disk the volume or replica creation getting failed .

I read a doc and it says as below  - 

Longhorn will detect the storage information (e.g. maximum space, available space) about the disk automatically, and start scheduling to it if it’s possible to accommodate the volume.
