### ISSUE TITLE
Cannot connect to the management URL when multiple nodes are added

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#251]
Reproduce steps:
1. Set up harvester from ISO(IP: 172.16.0.4)
2. Add a compute node(IP: 172.16.0.56)
3. Check dashboard

The dashboard shows that the management URL is https://172.16.0.4:8443, while the external IP of the lb svc is 172.16.0.56
```
$ kubectl get svc -n harvester-system
harvester                     LoadBalancer   10.43.91.47     172.16.0.56   8443:30892/TCP   20m
```

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-installer/pull/7 and the management URL is designed to use the first management node.
