### ISSUE TITLE
[BUG] cluster-registration-url is lack of essential check and no clear error message in dashboard when registration fails

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2510]
**Describe the bug**

It is possible to set any string (e.g. `abc`) in Harvester setting `cluster-registration-url`, and save OK. No check. Dashboard seems no place to find the status of the registration.

https://docs.harvesterhci.io/v1.0/rancher/virtualization-management/

In Harvester POD, there are error messages every 30 seconds. (of the invalid input `abc`)
`
time="2022-07-15T11:30:36Z" level=error msg="error syncing 'cluster-registration-url': handler harvester-setting-controller: Get \"abc\": unsupported protocol scheme \"\", requeuing"
`

`
time="2022-07-15T11:31:06Z" level=error msg="error syncing 'cluster-registration-url': handler harvester-setting-controller: Get \"abc\": unsupported protocol scheme \"\", requeuing"
`

**To Reproduce**
1. Go to Harvester dashboard setting
2. Set anything in `cluster-registration-url`  (e.g. `abc`, it is clearly not a valid http url in most cases), save
3. Looks good, no clear error message in Harvester dashboard

**Expected behavior**

Check the registration url.

Add error message to dashboard when registration fails.

**Support bundle**

**Environment**
 - Harvester ISO version:  master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM based.

**Additional context**

**Comment by WuJun2016** [comment]
@guangbochen   When I first configure an incorrect address, an error message appears, then I configure a correct address, the cluster is imported correctly, but the error message does not disappear. 
![image](https://user-images.githubusercontent.com/24985926/180752498-20adf096-0763-4aa9-9788-6189159a6551.png)

**Comment by irishgordo** [comment]
I was noticing similar behaviors @w13915984028 - was also curious about the ReplicaSet that builds the cattle-cluster-agent / ensures that at most two of the cattle-cattle-cluster-agent are running.  Sometimes it also seemed that when a modification was made to the cluster-registration-url, that change doesn't take effect for some time.

**Comment by irishgordo** [comment]
@WuJun2016 I recorded a short video of some of the behaviors I've been seeing working with `cluster-registration-url`, adding a Harvester cluster into Rancher - removing, then re-adding back into Rancher.  It seems like there is a bit of a hang or it's hard to tell when the `modified` will trigger, and if there isn't any value in `cluster-registration-url` it seems like it just stays empty but never mentions that it was `modified`.

https://user-images.githubusercontent.com/5370752/183522749-7f134fd8-e9ee-4988-8ec0-224a20837540.mp4

## Environment:
- Harvester Single Node Bare-Metal:
    - Harvester Version: v1.0.3-rc2
    - Dell PowerEdge R720:
        - 2 x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (total of 20cores)
        - 64GB DDR3 ECC RAM
        - 1TB Samsung SSD
- 3 Node K3OS Rancher Cluster:
    - User: Admin
    - K3OS Installed On Bare-Metal: k3os version v0.21.5-k3s2r1
    - Rancher Version: v2.6.7-rc6
    - Modded Lenovo ThinkCentre:
        - Intel Xeon E3-1265L v3 @ 2.50GHz
        - 16GB DDR3 NON-ECC RAM 
        - 480 Kingston SSD

**Comment by WuJun2016** [comment]
> @WuJun2016 I recorded a short video of some of the behaviors I've been seeing working with `cluster-registration-url`, adding a Harvester cluster into Rancher - removing, then re-adding back into Rancher. It seems like there is a bit of a hang or it's hard to tell when the `modified` will trigger, and if there isn't any value in `cluster-registration-url` it seems like it just stays empty but never mentions that it was `modified`.
> 
>  cluster-registration-url-issues.mp4 
> ## Environment:
> * Harvester Single Node Bare-Metal:
>   
>   * Harvester Version: v1.0.3-rc2
>   * Dell PowerEdge R720:
>     
>     * 2 x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (total of 20cores)
>     * 64GB DDR3 ECC RAM
>     * 1TB Samsung SSD
> * 3 Node K3OS Rancher Cluster:
>   
>   * User: Admin
>   * K3OS Installed On Bare-Metal: k3os version v0.21.5-k3s2r1
>   * Rancher Version: v2.6.7-rc6
>   * Modded Lenovo ThinkCentre:
>     
>     * Intel Xeon E3-1265L v3 @ 2.50GHz
>     * 16GB DDR3 NON-ECC RAM
>     * 480 Kingston SSD



HI， @irishgordo  I've tested the steps you provided, and I think the behavior is as expected.    
'Modified' means you modified the original default value, which is empty, so if you set its value to empty, 'Modified' will not be displayed.

**Comment by WuJun2016** [comment]
@irishgordo  I created another issue to track some strange phenomena.   https://github.com/harvester/harvester/issues/2650

**Comment by WuJun2016** [comment]
> @guangbochen When I first configure an incorrect address, an error message appears, then I configure a correct address, the cluster is imported correctly, but the error message does not disappear. ![image](https://user-images.githubusercontent.com/24985926/180752498-20adf096-0763-4aa9-9788-6189159a6551.png)

I was not able to reproduce this phenomenon.

**Comment by irishgordo** [comment]
@WuJun2016 thanks for looking into that :+1: !
:smile: - I'll also keep an eye on https://github.com/harvester/harvester/issues/2650

**Comment by DaiYuzeng** [comment]
> > @guangbochen When I first configure an incorrect address, an error message appears, then I configure a correct address, the cluster is imported correctly, but the error message does not disappear. ![image](https://user-images.githubusercontent.com/24985926/180752498-20adf096-0763-4aa9-9788-6189159a6551.png)
> 
> I was not able to reproduce this phenomenon.

I can reproduce, follow steps below:

1. Input correct address
2. Input incorrect address
3. Error message is visible
4. Input correct address
5. Error message is still visible
6. Input another incorrect address
7. Error message can be updated

@guangbochen @WuJun2016

**Comment by irishgordo** [comment]
Tested on Master-9631b136, master.iso:

Validated error messages get updated to different messages.
Validated that when provided the correct url that the error message disappears.

Test ENV:
- qemu/kvm , harvester, 8c 20354MiB memory
- 3 Node K3OS Rancher Cluster:
    User: Admin
    K3OS Installed On Bare-Metal: k3os version v0.21.5-k3s2r1
    Rancher Version: v2.6.7-rc6
    Modded Lenovo ThinkCentre:
        Intel Xeon E3-1265L v3 @ 2.50GHz
        16GB DDR3 NON-ECC RAM
        480 Kingston SSD


### Supporting Screenshots:

![succeeds-and-error-goes-away](https://user-images.githubusercontent.com/5370752/184995179-9329b5cc-0063-4634-acb2-4460cf90c806.png)
![shows-errors-3](https://user-images.githubusercontent.com/5370752/184995181-4629033b-19e3-47f0-a785-9e0609dce9c9.png)
![can-see-errors-too](https://user-images.githubusercontent.com/5370752/184995182-e4c4d4e9-27ce-4bc6-b0fc-e37291421186.png)
![can-see-errors](https://user-images.githubusercontent.com/5370752/184995183-bd2d058a-5e96-458a-bd5f-13cbadbbecae.png)

This looks good! :smile: :+1:
