### ISSUE TITLE
[DOC] Document inbound and outbound port requirements for Harvester

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2512]
For customers trying to understand the ports they need to have open between Harvester hosts in a cluster and to access services on the Harvester stack remotely.

Document inbound and outbound ports that are used between Harvester hosts. Explain what ports are used for intra-cluster traffic vs external access of the Harvester stack's services. For example: https://documentation.suse.com/suma/4.2/en/suse-manager/installation/ports.html

**Comment by guangbochen** [comment]
seems this is already included in the https://docs.harvesterhci.io/v1.1/install/requirements#networking
