### ISSUE TITLE
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: resource mapping not found for name: "sync-additional-ca" namespace: "cattle-system" from "": no matches for kind "Plan" in version "upgrade.cattle.io/v1"

### ISSUE THREAD

**Issue by cai648971528** [harvester/harvester#2515]

**Comment by w13915984028** [comment]
@cai648971528 Could you add more information, thanks.

Harvester Version.
Installation in baremetal server or virtual machine, hardware resource capaciy (cpu cores, memory, storage)
ISO mode installation or `dev-mode`.
Are there more logs when failures happen? Please also add them.

**Comment by rookieduqi** [comment]
@w13915984028 
采用的开发者模式安装，在本地有个k8s的集群，然后按照文档https://docs.harvesterhci.io/zh/v1.0/dev/dev-mode/，目前出现的这个问题，切换到稳定版本后，pod报错
