### ISSUE TITLE
[FEATURE] Harvester supports alertmanager

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2517]
**Is your feature request related to a problem? Please describe.**

Alertmanager (of `rancher-monitoring`)  related features are not supported in Harvester.

**Describe the solution you'd like**

Support alertmanager. 

Support config various types of receivers.

Support customized alert rules definition.

**Describe alternatives you've considered**

**Additional context**

**Comment by KarlSK8** [comment]
Hi @w13915984028,
So will the alert-manager be available soon in harvester?

**Comment by w13915984028** [comment]
An imporant tip about how to view alerts from `Prometheus` directly

https://github.com/prometheus/alertmanager/issues/2858

The key is to configure externalUrl in both `alertmanager` and `Prometheus`

In Harvester, from following similar path to view alert information in `Prometheus`

https://192.168.122.200/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-prometheus:9090/proxy/alerts

**Comment by w13915984028** [comment]
All sub-stories are done, close EPIC.
