### ISSUE TITLE
[FEATURE] enable/disable alertmanager on demand

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2518]
**Is your feature request related to a problem? Please describe.**

Enable alertmanager by default.

**Describe the solution you'd like**

Alertmanager is enabled by default, user can disable it after installation from Harvester dashboard.

**Describe alternatives you've considered**

**Additional context**

HEP PR:
HEP: Harvester supports alertmanager
https://github.com/harvester/harvester/pull/2545

**Comment by w13915984028** [comment]
Resource usage of `Alertmanager`:

Alertmanager has one POD in the cluster, it takes around 50Mi of memory.

```
harv1:~ # kubectl top pod -A
..
NAMESPACE                   NAME                                                     CPU(cores)   MEMORY(bytes)   

cattle-monitoring-system    alertmanager-rancher-monitoring-alertmanager-0           1m           50Mi            

cattle-monitoring-system    prometheus-rancher-monitoring-prometheus-0               78m          530Mi           
harvester-system            harvester-756cd66d6d-dcv2g                               23m          375Mi           
harvester-system            harvester-load-balancer-59bf75f489-sm5kv                 2m           29Mi 

```
Data storage:
PVC: 5GB to store data.

**Comment by w13915984028** [comment]
`enable/disable` alertmanager is available via 
PR: https://github.com/harvester/dashboard/pull/411
UI Issue: https://github.com/harvester/harvester/issues/2643

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/193554680-c2d6f7c0-5cf0-44ee-803e-c7abda408774.png)
![image](https://user-images.githubusercontent.com/5169694/193554761-1f28c3b9-8964-4bfa-8069-d5bcc7d8d837.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-0d929ef2-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard, navigate to **Monitoring & Logging/Monitoring/Configuration** then select **Alertmanager** tab
3. Option Button `Enabled` should be checked
4. Select **Grafana** tab then access Grafana
5. Search _Alertmanager_ to access _Overview_ dashboard
6. Data should be available and keep updating
