### ISSUE TITLE
[FEATURE] Alertmanager is backed by PVC

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2519]
**Is your feature request related to a problem? Please describe.**

Alertmanager needs to persisstant user data.

**Describe the solution you'd like**

Alertmanager is backed by PVC, default PVC size is 5 Gi.

**Describe alternatives you've considered**

The PVC size is NOT configable via dashboard.

**Additional context**

HEP PR:
HEP: Harvester supports alertmanager #2545
https://github.com/harvester/harvester/pull/2545

Code PR to set default PVC type (longhorn) and size (5 Gi):
https://github.com/harvester/harvester-installer/pull/322
feat2517 Harvester-installer support alertmanager

**Comment by noahgildersleeve** [comment]
Tested in upgrade from `v1.0.3` to `master-47a3af23-head` and fresh install of `master-67b93cd5-head`

## Verification Steps
### Case 1 upgrade from v1.0.3
1. Installed 3 node ipxe setup on v1.0.3 and verified that there was no alert-manager present
2. Created a manual upgrade `version.yaml` similarly to the [steps in the airgap upgrade setup](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade)
3. Run the upgrade
4. Verify that the upgrade was successful

### Expected Results
- The alert manager pods was created and is in the reporting system
![Screenshot_20220920_113250](https://user-images.githubusercontent.com/83787952/191337834-c0b9fccf-d471-49ba-85ad-dbb6a61e22b7.png)
![Screenshot_20220920_113254](https://user-images.githubusercontent.com/83787952/191337867-a6d95f41-9b67-42b6-b7a2-208ccd2c9f1c.png)
- The alertmanager is backed by PVC
![Screenshot_20220920_113342](https://user-images.githubusercontent.com/83787952/191392567-ef996543-9d06-472f-8a6f-5dd0a24b8267.png)

### Case 2 fresh install
1. Installed 3 node ipxe setup
2. Verify that install was successful

### Expected Results
- The alert manager pods was created and is in the reporting system
![Screenshot_20220920_180858](https://user-images.githubusercontent.com/83787952/191392336-709aacb7-7201-4779-b229-17ca008ef5aa.png)
![Screenshot_20220920_180852](https://user-images.githubusercontent.com/83787952/191392337-84479c3c-e947-4e90-bf39-33e8b7e5f7ee.png)
- The alertmanager is backed by PVC
![Screenshot_20220920_180931](https://user-images.githubusercontent.com/83787952/191392371-5890a011-a680-450f-b0f9-40fe06229073.png)
