### ISSUE TITLE
Cannot join a management node to an existing cluster

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#252]
**Steps to reproduce:**
1. install by iso and join to an existing cluster as a management node
2. As a result, the node does not join after installation.

**Other details:**
The latest K3OS embeds K3S v1.18.9, and embedded etcd HA is available as of K3S v1.19.1.

**Comment by yasker** [comment]
I saw the node name for the management node is `harvester-1` while additional nodes are `harvester-<uuid>`. Maybe the duplicate name is the issue.

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/issues/252 as the node management will be auto managed by the harvester controller.
