### ISSUE TITLE
[FEATURE] Add rules for Harvester, Longhorn, kubevirt

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2520]
**Is your feature request related to a problem? Please describe.**

There are rules defined in `rancher-monitoring`, from the view of Harvester, more rules are needed.

https://github.com/rancher/charts/tree/dev-v2.6/charts/rancher-monitoring/100.1.0%2Bup19.0.3/templates/prometheus/rules-1.14

**Describe the solution you'd like**

Add rules for Harvester, Longhorn, kubevirt and other related.

**Describe alternatives you've considered**

There are ways to define new rules in running Harvester clusters.

**Additional context**

Harvester:
https://github.com/harvester/harvester/issues/1781

Longhorn:
https://github.com/longhorn/longhorn/issues/1473
https://github.com/longhorn/longhorn/pull/3580

Code PR:
https://github.com/harvester/harvester/pull/2678
feat2517 harvester support alertmanager #2678
```
Longhorn alert is available
  Add Longhorn ServiceMonitor and PrometheusRule, prometheus will grab data from Longhorn and fire the defined alert

KubeVirt alert is available
  KubeVirt existing alert has an issue of VirtOperatorDown, which is solved in deployment.yaml and kubevirt-operator-0.1.0.tgz
```

HEP PR:
HEP: Harvester supports alertmanager #2545
https://github.com/harvester/harvester/pull/2545

To test this issue, please togethe with: https://github.com/harvester/harvester/issues/2518 , which will enable alertmanager when installation,  otherwise, user need to enable alertmanager manually.

**Comment by w13915984028** [comment]
Note:
To `TEST` this issue, please togethe with: https://github.com/harvester/harvester/issues/2518 , which will enable alertmanager when installation,  otherwise, user need to enable `alertmanager` manually  via  `kubectl edit managedchart rancher-monitoring` to set `alertmanager.enabled` as `true`

**Comment by guangbochen** [comment]
@w13915984028 Harvester metrics are not exposed yet; should we track it in a separate ticket?

**Comment by w13915984028** [comment]
@guangbochen 

We have one #1781 , but it's not directly related to alert rules, a new ticket is created: https://github.com/harvester/harvester/issues/2850 (harvester alter rules)

https://github.com/harvester/harvester/issues/1781  (harvester performance metrics)

**Comment by lanfon72** [comment]
@w13915984028 It seems we will add **Harvester** rules and track the implementation in #2850, can we remove `Harvester` from this issue's title?

**Comment by lanfon72** [comment]
Verified rules of Longhorn and Kubevirt has been added.

Harvester's rules will be tracking in #2850 

![image](https://user-images.githubusercontent.com/5169694/193562166-641453b1-3bff-44d8-a5de-6110ccc0aeb1.png)
![image](https://user-images.githubusercontent.com/5169694/193562250-1d505225-8fa1-45d9-ab3f-0681d52126c0.png)

Test Information
----
* Environment: **baremetals DL360G9 4 nodes**
* Harvester Version: **master-4c79967e-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard, navigate to **Monitoring & Logging/Monitoring/Configuration**
3. Select **Prometheus** tab then access **Prometheus Graph**
4. Navigate to _Alerts_, rules of Longhorn (longhorn.rules) and Kubevirt (kubevirt.rules) should be available
