### ISSUE TITLE
[BUG] Windows VMs crashing

### ISSUE THREAD

**Issue by tgazik** [harvester/harvester#2522]
**Describe the bug**
Windows VM crashing. When i use image with preinstalled windows server 2019 or trying to install VM from iso image the VM restarted by itself after some period (seconds, 2-3 minutes). I`m using Windows VM template as described in documentation.
When i use resources like 2CPU and 4GB RAM the VM is stable, when i use 4CPU and 8GB RAM the VM is crashing.
Tested on 3 different environments with 3 nodes and also with single node cluster.

**To Reproduce**
each time trying to run or install windows

**Environment**
 - Harvester ISO version: 1.0.2
 - Underlying Infrastructure: tried with different platforms and environments. 3x Supermicro, Intel XEON D2183IT, 256GB RAM

** support bundle **
i have uploaded the supportbundle by ftp

**Comment by janeczku** [comment]
@tgazik Could you please amend the steps to reproduce, e.g.:

- How was Windows 2019 installed
- Which additional Windows drivers were installed (e.g. virtio drivers)
- What settings did you configure when creating the VM in Harvester, e.g. did you follow https://docs.harvesterhci.io/v1.0/vm/create-windows-vm/

**Comment by janeczku** [comment]
Potential duplicate of https://github.com/harvester/harvester/issues/276

**Comment by janeczku** [comment]
@tgazik Can you confirm whether the VM crashes with "KMODE exception not handled" as described in the other issue?

**Comment by janeczku** [comment]
I can reproduce the issue by following the steps here to provision a Windows 2019 VM using 4 CPU and 8 GB Ram: https://github.com/harvester/harvester/issues/1767#issue-1093194711

After creating the VM, wait for 1-2 hours, then connect via Web VNC. If the user is logged out, send CTRL-Alt-Del to login.

Result: The VM crashes
<img width="1198" alt="Screenshot 2022-07-18 at 16 33 56" src="https://user-images.githubusercontent.com/3813921/179554181-5d5011a9-72f0-4700-90d9-0bc8fbf2a75f.png">

**Comment by janeczku** [comment]
The timestamps of the VM crashing correspond to the timestamps of OOM killer events in `dmesg`. This host has 260GB of free memory.
```
Jul 19 06:36:06 donna kernel: rpc-worker invoked oom-killer: gfp_mask=0x40cd0(GFP_KERNEL|__GFP_COMP|__GFP_RECLAIMABLE), order=0, oom_score_adj=978
Jul 19 06:36:06 donna kernel:  oom_kill_process+0xe8/0x130
Jul 19 06:36:06 donna kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jul 19 06:36:06 donna kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=6f6ea7744b5188b65e918882444cd0e3ac3e796f218ce998ca901fd7d35af54e,mems_allowed=0,oom_memcg=/kubepods/burstable/pod3821d51a-f352-4a36-8aca-490f1483b8b7/6f6ea7744b5188b65e918882444cd0e3ac3e796f218ce998ca901fd7d35af54e,task_memcg=/kubepods/burstable/pod3821d51a-f352-4a36-8aca-490f1483b8b7/6f6ea7744b5188b65e918882444cd0e3ac3e796f218ce998ca901fd7d35af54e,task=qemu-system-x86,pid=49691,uid=107
Jul 19 06:36:06 donna kernel: oom_reaper: reaped process 49691 (qemu-system-x86), now anon-rss:0kB, file-rss:36kB, shmem-rss:4kB
Jul 19 06:37:06 donna kernel: qemu-system-i38 invoked oom-killer: gfp_mask=0xcc0(GFP_KERNEL), order=0, oom_score_adj=978
Jul 19 06:37:07 donna kernel:  oom_kill_process+0xe8/0x130
Jul 19 06:37:07 donna kernel: [  pid  ]   uid  tgid total_vm      rss pgtables_bytes swapents oom_score_adj name
Jul 19 06:37:07 donna kernel: oom-kill:constraint=CONSTRAINT_MEMCG,nodemask=(null),cpuset=a364a750d2cd5dd858b30095532a0813d613f4beac9b493fc3546c1331728d70,mems_allowed=0,oom_memcg=/kubepods/burstable/podc40fd299-14b7-4e88-af84-7b70fab76d12/a364a750d2cd5dd858b30095532a0813d613f4beac9b493fc3546c1331728d70,task_memcg=/kubepods/burstable/podc40fd299-14b7-4e88-af84-7b70fab76d12/a364a750d2cd5dd858b30095532a0813d613f4beac9b493fc3546c1331728d70,task=qemu-system-x86,pid=15073,uid=107
Jul 19 06:37:07 donna kernel: oom_reaper: reaped process 15073 (qemu-system-x86), now anon-rss:0kB, file-rss:56kB, shmem-rss:4kB
```

**Comment by janeczku** [comment]
Free memory on the server is 260GB

**Comment by janeczku** [comment]
Possibly a regression of https://github.com/harvester/harvester/issues/1234 @guangbochen @futuretea 

Could it be that our resource overhead calculation to reserve qemu memory is not correct anymore? https://github.com/harvester/harvester/commit/39c76d70e7ce178a26142bac43d09fc0002e1290

**Comment by janeczku** [comment]
Potential fix upstream: https://github.com/kubevirt/kubevirt/pull/7264

**Comment by futuretea** [comment]
For windows vm, we should increase reserved memory in the `Advanced Options`
refer to https://github.com/harvester/harvester/issues/1730#issuecomment-1063878424,

**Comment by janeczku** [comment]
@futuretea @guangbochen 

It seems unexpected that Harvester is automatically applying memory limits to the VMI: Normally, the memory limit is a user controlled parameter in Kubevirt.

If Harvester wants to be in control of the memory limit, then it must properly calculate the overhead required to avoid OOM killer.

Currently, Harvester uses a hardcoded overhead of 100MiB for the qemu process. Clearly, this overhead is insufficient and this causes the OOM events.
https://github.com/harvester/harvester/commit/39c76d70e7ce178a26142bac43d09fc0002e1290

Advanced Options -> Reserved Memory does not appear to be the issue here.

VMI launched by Harvester:

```
    memory:
      guest: 8092Mi   <- Configured by Harvester (using hardcoded 100MiB overhead)
    resources:
      limits:
        cpu: "4"
        memory: 8Gi <- Limit configured by Harvester
      requests:
        cpu: 250m
        memory: 5461Mi
```

**Comment by guangbochen** [comment]
Actually, the resource limits are configured by the users, and the requests are automatically set by the Harvester webhook in combination with the [overcommit configs](https://docs.harvesterhci.io/v1.0/settings/settings/#overcommit-config).

The guest memory is reserved with 100MiB by default and can be configured manually in the advance tab as u have described above, for most Linux VMs the default value is sufficient, but apparently not good for Windows VM with large memory sizes.

As discussed in the issue https://github.com/harvester/harvester/issues/1730 it would be a little bit hard for us to predict the desired reserved memory for each OS in the current design, as a future enhancement I would suggest: cc @FrankYang0529 
- Ask the user to provide more details when uploading the OS images, e.g. OS type+version, so we can add more best-reserved memory calculations based on the image info.
- Use the existing reserved memory configuration and create a VM template to reuse it (more like are workaround solution).

**Comment by Martin-Weiss** [comment]
For memory overcommit I highly recommend 100% or less as default. Keep in mind that an "OOM" kill for a VM is basically data-loss.

What means "most Linux VMs"? Can you give details which Linux VMs are on risk?

Why don´t we see this proplem when we use KVM natively?

How can the user know / calculate how much additional memory he needs to deduct from the OS / reserve for qemu etc.? 
Could we change the 100MiB to a 100% save value for all guests that a user can change if he wants to squeeze out the max possible?

**Comment by janeczku** [comment]
Configuring 256MiB in the VM Advanced Options->Reserved Memory option seems **not sufficient** to mitigate the crash issue. I will try with a higher value.

<img width="816" alt="image" src="https://user-images.githubusercontent.com/3813921/180396648-34c94f44-93bd-45c9-aee6-c48342e60900.png">

**Comment by janeczku** [comment]
After configuring 512MiB reserved memory my Windows 2019 Server VM has been running for 10 days without any crash.
CPU: 4
Memory: 8GiB

**Comment by johnlaur** [comment]
Windows Server 2022 guest with 16GB of memory configured with 1 virtio NIC and 2 virtio disks of 512GB and 2TB respectively requires > 256MiB of reserved memory in our environment not to be OOM killed. We have set Reserved Memory to 512MiB and the VM is stable. I speculate the amount of additional host memory needed by QEMU is related to virtqueues and buffers necessarily to implement the paravirtualized devices but haven't found any documentation to demystify it completely.

**Comment by RegisWeduLabs** [comment]
Hey, had the same issue and setting the reserved memory to 512MiB fixed the issue for me.  256 still caused issues on our side.

**Comment by SnelsSM** [comment]
Same problem, but for linux guests.
We cannot manually set reserved memory for all VMs because they are created automatically from rancher (k8s clusters). 
There is no option for reserved memory.

**Comment by johanot** [comment]
I might be asking a stupid question here, because I don't have any raw-Kubervirt environment to test with right now, but:

What would be the consequence of simply not setting `resources.limits.memory` on the VM (and hence the virt-laucher)? After all, `domain.memory.guest` should limit how much the qemu process gets to play with and in case of runtime overhead, the OOM-killer will eventually find a target with bad score, regardless of cgroup limit or no limit. But it would only do so in a system starvation scenario.

I guess what I'm saying is: I kinda don't want OOM-kill of my VM under any circumstances - except if my host is reeeally in trouble. Maybe the limit could be an "opt-out" thing? If it's possible with Kubevirt.

**Comment by bk201** [comment]
We'll investigate and fine-tune a value in https://github.com/harvester/harvester/issues/5768
