### ISSUE TITLE
[BUG] Disk doesn't show up in Windows VM install

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2526]
**Describe the bug**

When you create a VM with the Windows template the root disk doesn't show up in the installer
**To Reproduce**
1. Upload a Windows installer ISO
2. Create a new windows VM with the windows template
3. Make sure that the ISO is a CDROM volume so that you can boot to the ISO [Bug](https://github.com/harvester/harvester/issues/2057)
**Expected behavior**

The root disk should 
**Support bundle**
[supportbundle_51a68deb-608a-46a6-bf00-024022c19929_2022-07-18T19-09-05Z.zip](https://github.com/harvester/harvester/files/9134687/supportbundle_51a68deb-608a-46a6-bf00-024022c19929_2022-07-18T19-09-05Z.zip)

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Vagrant box 16GB RAM 12C

**Additional context**
I believe that this is being caused by the template having the root disk as VirtIO. If you change it to SATA it shows up in the installer. Server versions 2012, 2019, and 2022 all didn't show the disks and trying to load the driver from the ISO that was included didn't work. It said that no signed drivers were present. 

![Screenshot_20220718_123857](https://user-images.githubusercontent.com/83787952/179603846-e2801a07-1594-4514-8d5f-1a5b1d78948d.png)
![Screenshot_20220718_123730](https://user-images.githubusercontent.com/83787952/179603849-474ff265-2ff4-4ce2-87e9-5fc1dbe438f6.png)
![Screenshot_20220718_123652](https://user-images.githubusercontent.com/83787952/179603851-5f65b5fa-60f4-4f32-84d5-95bc40a31cdd.png)

**Comment by w13915984028** [comment]
Suggest to add the `workaround` into `Harvester doc`, e.g. `troubleshooting`.

**Comment by lanfon72** [comment]
For windows disk, we need to load and install drivers as https://github.com/harvester/harvester/issues/1730#issuecomment-1024014419 mentioned.

Currently, the **vmdp** container in `windows-base-template` not includes windows 2019, so we would need to update the document that they would need to use other driver source such like [virtio](https://github.com/virtio-win/virtio-win-pkg-scripts)

**Comment by guangbochen** [comment]
Need to update the [Create a Windows VM page](https://docs.harvesterhci.io/v1.0/vm/create-windows-vm/#header-section) to include more details of both Windows installation steps and related driver configurations. e.g.,
- pre-requisite and known limitations (e.g. increase reserved memory for Windows VM with memory size >= 8G https://github.com/harvester/harvester/issues/2522#issuecomment-1192314750).
- a [step-by-step configuration](https://github.com/harvester/harvester/issues/1730#issuecomment-1024014419).
- a table to describe the supported version and driver configs.

Windows Version | Driver Image | driver path | supported |
---------- |  ---------- | ---------- | ---------- |
Windows 2019 | `registry.suse.com/suse/vmdp/vmdp:2.5.3`(built-in)  |  `/path/to/the/driver` | `yes,no or experimental` |

**Comment by guangbochen** [comment]
Added Windows installation guidelines and know issues to the https://docs.harvesterhci.io/v1.0/vm/create-windows-vm/#installation-of-windows; feel free to re-open this issue or submit a doc enhancement PR if required, thanks.

**Comment by manju7860** [comment]
Unable to install windows VM in suse harvester hypervisor(v1.5.0-rc3)

**Comment by manju7860** [comment]
how to resolve it, can some one provide the steps to fix it
