### ISSUE TITLE
[BUG] Image failed to download with `connection reset` error

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2535]
### Describe the bug
Image failed to download with error: `connection reset by peer`

![image](https://user-images.githubusercontent.com/5169694/179716316-f0f50824-fc9c-42c9-a8b1-3303e259193e.png)

### To Reproduce
1. Install Harvester with any nodes
2. Create a large Image via **URL**

### Expected behavior
This bug happened rarely, user can re-create the Image to download it.
But when it is a large image file, it would be a pity to re-download the whole image.

## Environment:
 - Harvester ISO version: **master-aa3d95d2-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL160 5 nodes**

### Additional context
Discovered by daily e2e testing.

It will happened on public http(s) servers such like https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/

Longhorn issue: https://github.com/longhorn/longhorn/issues/5307

**Comment by guangbochen** [comment]
Moved to v1.3 as this will depend on https://github.com/longhorn/longhorn/issues/5307

**Comment by bk201** [comment]
We'd close the issue since retry is already implemented on the Harvester side. https://github.com/harvester/harvester/issues/3144
Please reopen if the resume feature is still needed.
