### ISSUE TITLE
[FEATURE] Add "shutdown" and "reboot" option on harvester nodes

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2538]
**Is your feature request related to a problem? Please describe.**
When ever we have configuration changes (i.e. bonding mode, nameserver, additional NICs) we need to reboot the nodes to ensure the new configuration is used. At the moment this is not possible via UI:

![grafik](https://user-images.githubusercontent.com/13362573/179912775-93d34886-b4e0-4a4b-9411-8936ecfae9f9.png)

**Describe the solution you'd like**
After putting a cluster node into "maintance" we need to be able to "shutdown" or "reboot" a node via UI.

**Describe alternatives you've considered**
Using CLI is possible but not convinient.

**Comment by yasker** [comment]
@Martin-Weiss It seems those operations are done via CLI instead of UI. I would expect user to `Enable Maintainence Mode` then reboot the node from CLI since they're already in the CLI.

**Comment by Martin-Weiss** [comment]
Can´t we add the "shutdown" or "reboot" in the UI, too? (where the enable maintenance is)

Setting to maintenance in the UI and then having the additional need for console access or SSH access seems to be not very userfriendly.

**Comment by yasker** [comment]
Yes, we can. Since those nodes are Harvester-managed nodes, yes those operations should be possible via Harvester UI.

**Comment by zatricky** [comment]
In a test cluster, I put a node into maintenance mode then accidentally rebooted the wrong node via ssh, causing the *only* VM in the cluster to be broken while I tried for several hours to figure out how _gracefully_ to get that VM online again. I got it fixed and learned a lot about kubevirt - but I'm sure this is the "hard way" to learn. :-)

**Comment by ibrokethecloud** [comment]
Current master can leverage seeder to trigger power actions on underlying baremetal nodes.

To test:

* ensure harvester-seeder addon is enabled: 
![image](https://github.com/harvester/harvester/assets/19664014/43ddd6c1-1fa7-4c1b-a470-aa5031907e60)

* once addon is deployed the user can configure the Out Of Band access for the nodes on the config page: 
![image](https://github.com/harvester/harvester/assets/19664014/4299cd0c-3647-4f5f-8ee7-a4f842a68063)

* place node in maintenance mode to trigger drain of workloads

* once node is in maintenance mode, the power actions are available in the UI

<img width="1518" alt="image" src="https://github.com/harvester/harvester/assets/19664014/a1a4b92c-6f20-41b4-8330-8a3cfd27f320">

**Comment by albinsun** [comment]
Provide test result for `v1.2.0-rc3`

## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: Baremetal, 3 nodes (24C/128G/1.5T)
  * **ui-source**: Auto
* Nodes and its Out-of-Band Access (Management) IP

  | Name  | IP        | OOBA IP     |
  | ---   | ---       | ---         |
  | node0 | 172.x.x.3 | 172.x.x.172 |
  | node1 | 172.x.x.4 | 172.x.x.151 |
  | node2 | 172.x.x.5 | 172.x.x.153 |

## Verification
> **Note** Click TC to expand details.
### Positive TCs
1. <details><summary>Enable Power Actions $~~$ $\color{green}{\textsf{PASS}}$</summary>
   
   **Steps**
   1. All nodes are `Active`
      ![image](https://github.com/harvester/harvester/assets/2773781/3a07a46d-c937-4e24-bfa6-ee17996a551b)
   1. **harvester-seeder** addon is `Disabled`
      ![image](https://github.com/harvester/harvester/assets/2773781/10796666-54f1-4f55-ae7c-940990a477f9)
   1. Enable **harvester-seeder** addon
      ![image](https://github.com/harvester/harvester/assets/2773781/911e517c-3303-4412-ac01-ac6807639164)
   1. Power actions should not available yet
      ![image](https://github.com/harvester/harvester/assets/2773781/91b91ba2-8767-4a0a-be1e-2697afdd3f5a)
   1. Config **Out-of-Band Access** on node2
      ![image](https://github.com/harvester/harvester/assets/2773781/0cda6afa-c9b2-4c7f-a7ac-5bd8cd7c1cc3)
   1. Power actions should not available yet
      ![image](https://github.com/harvester/harvester/assets/2773781/91b91ba2-8767-4a0a-be1e-2697afdd3f5a)
   1. **Enable Maintenance Mode** on node2
      ![image](https://github.com/harvester/harvester/assets/2773781/0587b421-a677-4824-b393-bb2365ec861f)
   1. Power actions should be available
      ![image](https://github.com/harvester/harvester/assets/2773781/475905ff-d813-4d6e-a8ba-efb7ddd703a7)

   </details>

1. <details><summary>Reboot $~~$ $\color{green}{\textsf{PASS}}$</summary>
   
   **Steps**
   1. node2 is in `Maintenance`
   1. Reboot node2
   1. node2 is `Rebooting`
      ![image](https://github.com/harvester/harvester/assets/2773781/8461054f-276b-4c56-9913-fa99b8f92790)
   1. node2 back to `Maintenance` (Takes ~10min)
      ![image](https://github.com/harvester/harvester/assets/2773781/55cc808a-aadd-4d38-bbd2-4fba070f5cea)
  
   </details>

1. <details><summary>Shutdown -> Power On $~~$ $\color{green}{\textsf{PASS}}$</summary>
   
   **Steps**
   1. node2 is in `Maintenance`
   1. Shutdown node2
   1. node2 `Stopping`
      ![image](https://github.com/harvester/harvester/assets/2773781/c8f53f1f-5ead-49fc-a05a-dd37a08c52ef)

   1. node2 `Off`
      ![image](https://github.com/harvester/harvester/assets/2773781/a00e77a9-8a11-47e0-9aa5-43734ffccdb1)
   1. Power On node2
      ![image](https://github.com/harvester/harvester/assets/2773781/fdcba877-ae37-435e-b48d-054eb6f0cf09)
   1. node2 `Starting`
      ![image](https://github.com/harvester/harvester/assets/2773781/3db82da1-3088-419e-9060-019b090cf549)
   1. node2 back to `Maintenance` (Takes ~10min from `Stopping`)
      ![image](https://github.com/harvester/harvester/assets/2773781/bd96c818-0cad-4dd0-82f7-4e9caf9379b7)
   1. **Disable Maintenance Mode** on node2
   1. node2 back to `Active`, Power actions are hided.
      ![image](https://github.com/harvester/harvester/assets/2773781/15ddea0d-d75f-4069-b992-9cd24e681cde)

   </details>

1. <details><summary>Edit OOBA IP and Reboot $~~$ $\color{red}{\textsf{FAIL}}$</summary>
   
   **Steps**
   1. Config node2's OOBA IP as 172.x.x.151 (node1's OOBA IP)
      ![image](https://github.com/harvester/harvester/assets/2773781/b64dc079-492c-408c-9ddf-dfbc828ee779)
   1. Correct node2's OOBA IP to 172.x.x.153
      ![image](https://github.com/harvester/harvester/assets/2773781/36dcb2f3-55ab-4ce4-85f4-906217f7ccd7)
      ![image](https://github.com/harvester/harvester/assets/2773781/1e513fa3-0c60-41a4-bd06-91fb09432866)
   1. **Enter Maintenance Mode** on node2
   1. Reboot node2
      ![image](https://github.com/harvester/harvester/assets/2773781/f3c1260c-e972-4910-863e-f33bf2710551)
   1. node2 should `Rebooting` and back to `Maintenance` $~~$ :x: $\color{red}{\textsf{Reboot is triggerred on node1, node state is messed up}}$
      ![image](https://github.com/harvester/harvester/assets/2773781/d3b7d909-ec8c-43be-8643-068d67ce4a62)

   </details>

### Negtive TCs
1. <details><summary>Nodes Should NOT Have Same OOBA Config $~~$ $\color{red}{\textsf{FAIL}}$</summary>
   
   **Steps**
   1. Config node1's OOBA IP as 172.x.x.151
      ![image](https://github.com/harvester/harvester/assets/2773781/c46c0546-4935-49f4-8e7c-9b4aee8bf0b2)
   1. Should NOT be able to config node2 with same config as node1 $~~$ :x: $\color{red}{\textsf{Can config, but should popup error like "Same IP address is used on node1."}}$
      ![image](https://github.com/harvester/harvester/assets/2773781/ed8c9a93-6f74-411e-9570-e9d9e4d14d5b)

   </details> 

## Support Bundle
[supportbundle_c44677c3-0322-4c83-920f-0068b0f3e856_2023-07-11T10-11-06Z.zip](https://github.com/harvester/harvester/files/12015353/supportbundle_c44677c3-0322-4c83-920f-0068b0f3e856_2023-07-11T10-11-06Z.zip)

**Comment by ibrokethecloud** [comment]
For item 4, i am not sure we can do anything.

That would count as a user config error where they have defined incorrect out of band access details. there is no way for controller to reconcile actual node name from out of band access.

For Negative TC: That does sound like a good idea and I will check if there is anything that can be done in the api layer.

**Comment by albinsun** [comment]
> For item 4, i am not sure we can do anything.
> 
> That would count as a user config error where they have defined incorrect out of band access details. there is no way for controller to reconcile actual node name from out of band access.
> 
> For Negative TC: That does sound like a good idea and I will check if there is anything that can be done in the api layer.

@ibrokethecloud ,
Thanks, let's check whether can handle it in the API layer.
For TC **Edit OOBA IP and Reboot**, the node have not go maintenance or trigger any power action yet, so it's a pure config editing. I think it's a real case that user may give wrong info and edit/correct it then.

On the other hand
FYR, we found there are many sessions from harvester on each iLos, not sure it's expected or not?
![image](https://github.com/harvester/harvester/assets/2773781/0fafba8a-7d86-4a4f-96ec-9299a5d600f7)

**Comment by ibrokethecloud** [comment]
@albinsun i am just going to check and verify both these.

**Comment by ibrokethecloud** [comment]
These have been addressed in: https://github.com/harvester/seeder/pull/17

**Comment by albinsun** [comment]
Thanks, will test it with [harvester#2318](https://github.com/harvester/harvester/issues/2318).

**Comment by albinsun** [comment]
Provide test result for `v1.2-37aeb5ff-head`

## Test Environment
* Harvester
  * version: `v1.2-37aeb5ff-head`
  * profile: Baremetal, 3 nodes (48C/128G/1T)
  * **ui-source**: Auto
* Nodes and its Out-of-Band Access (Management) IP

  | Name  | IP        | OOBA IP     |
  | ---   | ---       | ---         |
  | node0 | 172.x.x.3 | 172.x.x.151 |
  | node1 | 172.x.x.4 | 172.x.x.153 |
  | node2 | 172.x.x.5 | 172.x.x.172 |


## Verification
> **Note** Click "►" to expand details.
### Positive TCs
1. <details>
   <summary>
   Enable Power Actions $~~$ :heavy_check_mark: 
   </summary>

   1. All nodes are `Active`
   1. **harvester-seeder** addon is `Disabled`
   1. Enable **harvester-seeder** addon
   1. Power actions should not available yet
      ![image](https://github.com/harvester/harvester/assets/2773781/26b90548-1746-4978-b2c3-07a33ecc668a)
   1. Config **Out-of-Band Access** on node2
      ![image](https://github.com/harvester/harvester/assets/2773781/449701db-8f85-4905-8f6d-dc14d375f1df)
   1. Power actions should not available yet
   ![image](https://github.com/harvester/harvester/assets/2773781/8e4cdc50-eaa2-4c0f-863a-fd3ab1617629)
   1. **Enable Maintenance Mode** on node2
   1. Power actions should be available
   ![image](https://github.com/harvester/harvester/assets/2773781/17bb6869-ace5-4a1a-b1a1-1a6fcc7f254b)

   </details>


1. <details>
   <summary>
   Reboot $~~$ :heavy_check_mark: 
   </summary>
   
   1. node2 is in `Maintenance`
   1. Reboot node2
   1. node2 is `Rebooting`
      ![image](https://github.com/harvester/harvester/assets/2773781/f3add356-40f9-47e6-9d82-2f4ce00a60ed)
   1. node2 back to `Maintenance` (Takes ~15m)
      ![image](https://github.com/harvester/harvester/assets/2773781/05e3f157-d842-46f9-bc30-79cf5f2e6506)
      ![image](https://github.com/harvester/harvester/assets/2773781/581e209f-9e84-434b-9fe8-f17b5c9d05dd)

   </details>


1. <details>
   <summary>
   Shutdown -> Power On $~~$ :heavy_check_mark:
   </summary>
   
   1. node2 is in `Maintenance`
   1. Shutdown node2
   1. node2 `Stopping`
      ![image](https://github.com/harvester/harvester/assets/2773781/50e0ad71-6abe-4ccf-abb0-75fa0539d96e)
   1. node2 `Off`
      ![image](https://github.com/harvester/harvester/assets/2773781/f294b11b-848f-4f4d-8c2c-d14db7582292)
   1. Power On node2 via mgmt service
   1. node2 `Starting`
      ![image](https://github.com/harvester/harvester/assets/2773781/0a99fbd2-c65e-4435-be9a-01cb993f3026)
   1. node2 back to `Maintenance` (Takes ~15m)
      ![image](https://github.com/harvester/harvester/assets/2773781/410c6c86-dd05-46f6-ac0a-f7dd444d26ce)
      ![image](https://github.com/harvester/harvester/assets/2773781/bc420f6a-15a6-4599-ad91-ad6148925d8f)
   1. **Disable Maintenance Mode** on node2
   1. node2 back to `Active`, Power actions are hided.
      ![image](https://github.com/harvester/harvester/assets/2773781/841c7c98-24c8-4294-8aed-8e42a74d4685)

   </details>


1. <details>
   <summary>
   Edit OOBA IP, enable maintenance and Reboot $~~$ :heavy_check_mark:
   </summary>
   
   1. Disable node1 OOBA
   1. Config node1's OOBA IP as 172.x.x.172 (node2's OOBA IP)
      ![image](https://github.com/harvester/harvester/assets/2773781/4a4daf65-cdd2-493d-9fca-9708ccd9e3e1)
   1. Correct node1's OOBA IP to 172.x.x.153
      ![image](https://github.com/harvester/harvester/assets/2773781/9d55a4d4-5327-4986-ac01-781aea04a0ec)
   1. **Enter Maintenance Mode** on node1
   1. Reboot node1
      ![image](https://github.com/harvester/harvester/assets/2773781/99b2eb3b-b3a9-45e2-9c6b-46472420a067)
   1. node1 should `Rebooting` and back to `Maintenance` (Takes ~15m)
      ![image](https://github.com/harvester/harvester/assets/2773781/419d93c9-b9f1-4475-aebd-35f07ae444c9)

   </details>


1. <details>
   <summary>
   Enable maintenance, edit OOBA IP and Reboot $~~$ :heavy_check_mark: 
   </summary>
   
   1. Disable node1 OOBA
   1. Config node1's OOBA IP as 172.x.x.172 (node2's OOBA IP)
      ![image](https://github.com/harvester/harvester/assets/2773781/74765f2c-a07e-45ed-8e1c-0cad65c539b3)
   1. **Enter Maintenance Mode** on node1
      ![image](https://github.com/harvester/harvester/assets/2773781/04becdfc-0e55-465a-94fa-5512779406f1)
   1. Correct node1's OOBA IP to 172.x.x.153
      ![image](https://github.com/harvester/harvester/assets/2773781/e266df69-090e-4ed6-82d3-39c8ac99e05a)
   1. Reboot node1
      ![image](https://github.com/harvester/harvester/assets/2773781/1f2d98c6-8d64-4637-a7d7-f61eb1966700)
   1. node1 should `Rebooting` and back to `Maintenance` (Takes ~15m)
      ![image](https://github.com/harvester/harvester/assets/2773781/1f351405-8aa1-414a-b75e-e7f3178a5dc0)

   </details>


### Negtive TCs
1. <details>
   <summary>
   Nodes Should NOT Have Same OOBA Config $~~$ :heavy_check_mark:
   </summary>
   
   1. Config node2's OOBA IP as 172.x.x.172
   1. Should NOT be able to config node2 with same config as node1
      ![image](https://github.com/harvester/harvester/assets/2773781/3d1568bb-aa52-4584-8830-9b78dd6fed89)

   </details>

**Comment by albinsun** [comment]
Tested in `v1.2-37aeb5ff-head`, close as done.


> **Note**
Since the mapping between node & out-of-band-access service depends on user's env.
it will be good to add warning in 1.2.0 document to let user becareful not to misplace other node's Out-of-Band Access IP or it may cause unexpected/confused nodes' status.

![image](https://github.com/harvester/harvester/assets/2773781/d3b7d909-ec8c-43be-8643-068d67ce4a62)
