### ISSUE TITLE
[FEATURE] Show "safe to reboot" in the harvester UI (longhorn replication)

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2540]
**Is your feature request related to a problem? Please describe.**
Especially in situations where a given volume in longhorn is deprecated it is important to be very careful during maintenance processes and ensure that enough healthy replicas of data exist in case a given node is rebooted to avoid data loss.

The harvester UI should show the status on a per node basis if it is "safe" to reboot a given node or if rebooting would cause data redundancy to be reduced / data could get lost.

**Describe the solution you'd like**
On the harvester hosts add a visible indication about the longhorn replication status for all the volumes that have a replication to the given node.
Also a "safe to reboot" indication should be there - especially in case the node is cordoned / drained.

**Describe alternatives you've considered**
Check in the longhorn UI - but that is not very convinient.

**Comment by bk201** [comment]
One idea is to add the check in the webhook and some UI enhancement.

**Comment by bk201** [comment]
https://github.com/harvester/harvester/issues/2723 is supposed to address the issue too.
If https://github.com/harvester/harvester/issues/2723 is implemented, we can ensure the node is safe to reboot or shutdown.

**Comment by bk201** [comment]
After https://github.com/harvester/harvester/issues/2723 is implemented, setting a node to maintenance also means it's safe to shut down the node. Feel free to reopen the issue if needed.

**Comment by Martin-Weiss** [comment]
> After #2723 is implemented, setting a node to maintenance also means it's safe to shut down the node. Feel free to reopen the issue if needed.

Will this  also cover the case where i.e. two of three masters would be "off"?
