### ISSUE TITLE
[BUG] [backport 1.0] Can't display dashboard page, keep in the Loading state after finishing first time login

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2542]
**Describe the bug**

After iso installing harvester and login. 
The dashboard display empty page and keep in `Loading` state after first time login
![image](https://user-images.githubusercontent.com/29251855/179945542-647c112a-0563-4bc5-90a8-19aec200a416.png)

**Reproduce rate**
* Attempts/failure: 3/3 (100%)

**To Reproduce**
1. ISO install one node harvester
2. Complete the first time login process
3. Access the Harvester dashboard page

**Expected behavior**

Dashboard page should display correctly after installation

**Support bundle**

v1.0-9bba3dfd-head:
[supportbundle_e4751ae8-a0e8-4572-890d-e3c7c60e972a_2022-07-20T09-17-23Z.zip](https://github.com/harvester/harvester/files/9148437/supportbundle_e4751ae8-a0e8-4572-890d-e3c7c60e972a_2022-07-20T09-17-23Z.zip)
 

v1.0-f2860d3b-head: 
[supportbundle_6f757226-7c2e-49d2-930b-6dd6f4649645_2022-07-19T10-45-45Z.zip](https://github.com/harvester/harvester/files/9148435/supportbundle_6f757226-7c2e-49d2-930b-6dd6f4649645_2022-07-19T10-45-45Z.zip)
[supportbundle_ea9110e9-fa4a-4bb2-9c1f-d77175a3e958_2022-07-20T08-55-36Z.zip](https://github.com/harvester/harvester/files/9148436/supportbundle_ea9110e9-fa4a-4bb2-9c1f-d77175a3e958_2022-07-20T08-55-36Z.zip)

**Environment**
 - Harvester ISO version: v1.0-f2860d3b-head (07/19) , v1.0-9bba3dfd-head (07/20)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node on local kvm machine

**Additional context**

**Comment by n313893254** [comment]
Hi, @TachunLin. It is caused by the UI version doesn't match Harvester's version. You could change the ui-index to `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html` as the Harvester is v1.0. The difference between v1.0 Harvester and v1.1 Harvester is that Longhorn is a different version. The API change would affect the storage data on the dashboard page. Here is related [issue](https://github.com/harvester/harvester/issues/2478).

**Comment by TachunLin** [comment]
By changing the ui-index in settings to https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html for Harvester v1.0. 
Then Harvester can display dashboard page correctly. Close this issue.
![image](https://user-images.githubusercontent.com/29251855/180113623-4b60944d-8a7f-4366-b39d-325015462c0a.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `v1.0-9bba3dfd-head` (07/20)
