### ISSUE TITLE
Upload image failed

### ISSUE THREAD

**Issue by Captured77** [harvester/harvester#2544]
App mode harvester, when I upload image from local.Waiting for 5 minutes, server response this error "timeout waiting for backing image data source to be ready". I look in this words in harvester code. I find this error from function “waitForBackingImageDataSourceReady”. In k8s cluster, I don't find this resource. why?

I want to know How to upload image by harvester?

**Comment by w13915984028** [comment]
Harvester uses Longhorn as the backend storage. When uploading image, it waits Longhorn to prepare, then does the uploading.

Per your description, does your `App mode harvester` has proper setting of storage?, or check your `stroageclass` via `kubectl`.

**Comment by Captured77** [comment]
> Harvester uses Longhorn as the backend storage. When uploading image, it waits Longhorn to prepare, then does the uploading.
> 
> Per your description, does your `App mode harvester` has proper setting of storage?, or check your `stroageclass` via `kubectl`.

Is this storageclass？

> allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
        annotations:
          storageclass.kubernetes.io/is-default-class: "true"
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: "Delete"
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fromBackup: ""
        baseImage: ""
        migratable: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2022-07-20T12:12:34Z"
  name: longhorn
  resourceVersion: "15038082"
  uid: eaa5e59e-a029-4f95-a6b7-c9fb8d0aaa60
parameters:
  baseImage: ""
  fromBackup: ""
  migratable: "true"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

**Comment by Captured77** [comment]
> 

I need install harvester-node-disk-manager?

**Comment by w13915984028** [comment]
@Captured77  Not sure if you follow the guide of    https://docs.harvesterhci.io/v1.0/dev/dev-mode/

In step 9, it says:
```
## In order to use the service type LoadBalancer and create a vip in control-plane nodes, we need to enable kubevip.
VIP_IP="replace with your vip ip, such as 192.168.5.10"
VIP_NIC="replace with your vip interface name, such as eth0"
helm install harvester ./harvester --namespace harvester-system \
--set harvester-node-disk-manager.enabled=true \
--set harvester-network-controller.enabled=true \
--set harvester-load-balancer.enabled=true \
--set kube-vip.enabled=true \
--set kube-vip.config.vip_interface=${VIP_NIC} \
--set kube-vip.config.vip_address=${VIP_IP} \
--set service.vip.enabled=true \
--set service.vip.ip=${VIP_IP}
```

**Comment by w13915984028** [comment]
As of `Harvester` V1.1.0, it is strongly recommended to use `ISO`/`PXE` mode to install the full set of `Harvester`. Thanks.

https://docs.harvesterhci.io/v1.0/install/iso-install
