### ISSUE TITLE
[FEATURE] Perform e2e tests on stable branches periodically

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2547]
**Is your feature request related to a problem? Please describe.**

We have daily e2e tests on the `master` branch, we need to enable tests on the `v1.0` branch as well, since `v1.0` is a maintenance branch.

**Describe the solution you'd like**

Add the tests to CI.

**Describe alternatives you've considered**

**Additional context**
Need support from automation QA test.

**Comment by bk201** [comment]
Moving to 1.2.0, we can manually trigger tests on the branch.

**Comment by lanfon72** [comment]
ref to https://github.com/harvester/tests/issues/718

**Comment by lanfon72** [comment]
Applied on our Jenkins starts from this week.
