### ISSUE TITLE
Fields should not be editable due to data volume spec is not allowed to update

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#255]
**Steps to reproduce:**
1. Select one of the volumes, click the ellipsis and choose the Edit As Form option
2. Edit any field except annotations and labels, then save

**Result:**
An error message shows: `admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request: Cannot update DataVolume Spec`
![image](https://user-images.githubusercontent.com/57614736/99606613-0e8a8080-2a45-11eb-95ce-9a9ac344099d.png)

**Suggestion:**
If the data volume spec is not allowed to update, users should not be able to edit the fields on UI anyhow.

**Comment by DaiYuzeng** [comment]
@guangbochen These fields will be set to read-only when users edit the volume. Does this make sense?
![截屏2020-11-19 上午11 24 53](https://user-images.githubusercontent.com/15041915/99617374-32a48c80-2a5a-11eb-820c-a742c0f41b22.png)

**Comment by guangbochen** [comment]
yep, and here are few design changes that are required for the volume page and please apply it to the lastest UI design: @DaiYuzeng 
1. [ ] on the volume listing page remove the `Access Mode` column
1. [ ] when the volume is `Ready` while not `In-Use` or attachment to any VM, change the banner's border color from green to blue.
1. [ ] on creating page set the default `Source` to blank, and rename the `Blank` to `New`
1. [ ] on creating/editing page, hide the `Access Mode` for now and the default value is auto-set to `RWO`, btw(typo: Access Model -> Access Mode)

**Comment by DaiYuzeng** [comment]
Got it thanks!

**Comment by DaiYuzeng** [comment]
There are screenshots of new UI.

#### remove Access Mode column & change border color
![截屏2020-11-24 下午1 36 06](https://user-images.githubusercontent.com/15041915/100053191-7a605500-2e5a-11eb-98c6-11ff7c4318bd.png)

#### set the default Source to blank
![截屏2020-11-24 下午1 37 20](https://user-images.githubusercontent.com/15041915/100053194-7b918200-2e5a-11eb-9a79-752af41da2b2.png)

#### hide the Access Mode and set default to RWO
![截屏2020-11-24 下午1 37 35](https://user-images.githubusercontent.com/15041915/100053203-7df3dc00-2e5a-11eb-9398-72de42661f1f.png)

**Comment by DoNotSayYes** [comment]
Validated
