### ISSUE TITLE
[Question] How to access/mount VM volume of crashed VM from other VM

### ISSUE THREAD

**Issue by crazyelectron-io** [harvester/harvester#2550]
I just installed and configured several containers and volumes in a VM on a Harvester node (1.0.2). It worked fine for a day but just before I was about to create a backup of the VM it crashed and doesn't boot anymore.
After a long delay, it ends with `No root device specified. Boot arguments must include a root = parameter.` and  a prompt `(initramfs)`.

When typing `exit` I get the following:
```
Warning: Type of root file system is unknown, so skipping check.
Usage: mount [-r] [-w] [-o options] [-t type] [-f] [-i] [-n] device directory
Failed to mount as root file system.
(initramfs)
```
Not sure what/how to mount to get the root file system mounted.

Alternatively I wanted to attache the volume to another VM but I have no clue how to attach it as an extra disk to a VM. Any suggestions?

**Comment by w13915984028** [comment]
Please generate a supportbundle first, it will include as more information as possible.

https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#generate-a-support-bundle

**Comment by crazyelectron-io** [comment]
Since I needed that system up and running one way or the other, I was fiddled around and ended up recreating the VM (now with immediate backup).
Next time I will directly create a support bundle if an issue occurs. For now, I'll close this issue.
