### ISSUE TITLE
[BUG] Unable to add addition disks on Host

### ISSUE THREAD

**Issue by scan-dev** [harvester/harvester#2551]
**BUG Description:**

I have the following baremetal node with following disk config:

```
rancher@harvest1:~ # lsblk

NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
loop0    7:0    0     3G  1 loop /
loop1    7:1    0    16G  0 loop
loop2    7:2    0    16G  0 loop
sda      8:0    0 557.9G  0 disk
├─sda1   8:1    0    64M  0 part /oem
├─sda2   8:2    0    15G  0 part /run/initramfs/cos-state
├─sda3   8:3    0     8G  0 part
└─sda4   8:4    0 534.8G  0 part /usr/local
sdb      8:16   0   2.7T  0 disk /var/lib/harvester/defaultdisk
sdc      8:32   0   2.7T  0 disk
└─sdc1   8:33   0   2.7T  0 part
sdd      8:48   0   3.3T  0 disk
└─sdd1   8:49   0   3.3T  0 part
sde      8:64   0    50G  0 disk /var/lib/kubelet/pods/c7f16a8b-30ed-42c5-9b71-829581484f6e/volume-subpaths/pvc-a4825c24-8aee-4455-957e-9e1580d4bbfa/promethe
sdg      8:96   0    10M  0 disk /var/lib/kubelet/pods/67b9e439-2acd-48b3-9bcc-51e780af4752/volumes/kubernetes.io~csi/pvc-c10f7213-a4c8-4141-9917-09f9727ee8f
sdh      8:112  0    16G  0 disk
├─sdh1   8:113  0     1M  0 part
├─sdh2   8:114  0   1.8G  0 part
└─sdh3   8:115  0  14.2G  0 part
sdi      8:128  0    16G  0 disk
├─sdi1   8:129  0     1M  0 part
├─sdi2   8:130  0   1.4G  0 part
└─sdi3   8:131  0  14.6G  0 part
```

I want to extend default disk (/dev/sdb) with sdc and sdd so to have all disk capacity available

I followed this instructions : 
[https://docs.harvesterhci.io/v1.0/host/host/#multi-disk-management-tech-preview](https://docs.harvesterhci.io/v1.0/host/host/#multi-disk-management-tech-preview)

**Reproduce**

Go through Web-UI options:
 - Harvester - Hosts
 - Select Host - on right menu <...> select "Edit Config"
 - Under Basics - select Disks
 - Select "Add Disks" - here unable to select the listed disks (forbidden-icon shown)

**Expected behavior**

when clicking/selecting "Add Disks" be able to add/extend the current disk-partition with the selected disk.
if needed to perform all basic disk instruction to add the disk (partition, format & extend to current disk-partition)

**Support bundle**

**Environment**
 - Harvester ISO version: **Harvester v1.0.2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  barematel - SUN FIRE X4270 M2 SERVER, ILOM v3.0.16.10.a, r68533

**Additional context**
![Screenshot from 2022-07-21 21-45-36](https://user-images.githubusercontent.com/64983025/180304294-0cf1447a-cde8-4732-8f7d-1aa3acc80c40.png)

**Comment by scan-dev** [comment]
[supportbundle_e5052400-6aee-4b82-9628-009ac31b8e5c_2022-07-21T20-19-38Z.zip](https://github.com/harvester/harvester/files/9162551/supportbundle_e5052400-6aee-4b82-9628-009ac31b8e5c_2022-07-21T20-19-38Z.zip)

**Comment by Vicente-Cheng** [comment]
Hi @scan-dev,

It seems both of your disks `sdc` and `sdd` have partition.
UI would not allow adding disk with partition.  (Thanks @n313893254 confirm that)

Maybe you could try to manually remove whole partitions on both `sdc` and `sdd` and then try to add them again?

https://docs.harvesterhci.io/v1.0/host/host/#multi-disk-management-tech-preview
You could try to read the above reference and try to follow it to add multi-disk.

**Comment by scan-dev** [comment]
deleting the partition solved my problem and was able to add disks as documented.
why the disk were partitioned is strange as I installed the hosts with default iso installer.

maybe feature to have more disk-mgmt steps avaialble in the UI (like delete existing partitions)

grts

**Comment by guangbochen** [comment]
Reopen the issue since we can make some further improvements on this one with:
1. Add a proper message to the UI if a partitioned disk can't be added as additional disks directly.
2. (To discuss/investigate) add an additional action to allow users to remove the disk partitions directly through the UI.

**Comment by Vicente-Cheng** [comment]
Hi 

> Reopen the issue since we can make some further improvements on this one with:
> 
> 1. Add a proper message to the UI if a partitioned disk can't be added as additional disks directly.
> 2. (To discuss/investigate) add an additional action to allow users to remove the disk partitions directly through the UI.

For 2. 
I think we could re-use the force format. That means we may let people choose the whole disk even if there is a partition (also proper warning message to tip user to know the partition would be destoried).

Then NDM would handle the following thing with force format (remove partitions and format again).

What do you think?  @guangbochen @bk201

**Comment by bk201** [comment]
@Vicente-Cheng that's indeed what the field is for.

**Comment by khushboo-rancher** [comment]
The backend test should be added for adding a new disk. https://github.com/harvester/tests/issues/450

**Comment by lanfon72** [comment]
Verified this bug has been resolved.
![image](https://user-images.githubusercontent.com/5169694/185803007-62aafe18-c7be-4996-b663-2c4d437ce7fd.png)
![image](https://user-images.githubusercontent.com/5169694/185803025-ad4e0c92-15ed-4065-a5a0-8306f97a45e8.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-9631b136-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with additional volumes (for qemu/KVM environment, WWN is required)
3. Login to console, make partitions for additional volumes (by the command `fdisk`)
4. Login to Dashboard then navigate to host details, add new disks
5. The volume should be appeared in the dropdown list of **Add Disk**
6. THe volume should be able to added
