### ISSUE TITLE
[BUG] kubectl on host gives permission denied / command not found

### ISSUE THREAD

**Issue by crazyelectron-io** [harvester/harvester#2556]
**Describe the bug**
After installing 3 Harvester nodes I started an SSH session to run `kubectl`. When run without `sudo` it gives a permission denied error on `/etc/rancher/rke2/rke2.yaml`. When running the command with `sudo` it gives a command not found error.
So, either the PATH should be adjusted during installation or the access rights of the RKE2 yaml-file should be adjusted.

I run Harvester v1.0.2 (amd64).

**To Reproduce**
1. Install a 3 node Harvester cluster (number of nodes probably not relevant).
2. Add it to Rancher.
3. Install a RKE2 cluster with default values for all optional parameters.
4. SSH into one of the Harvester hosts with the `rancher` user.
5. Run a `kubectl` command with and without `sudo`.

**Comment by guangbochen** [comment]
U may just execute `sudo su` first and then run the `kubectl` command.

**Comment by crazyelectron-io** [comment]
Of course... :O)
Thanks.
