### ISSUE TITLE
[BUG] Harvester POD has a high CPU usage

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2558]
**Describe the bug**

The `harvester` POD takes roughly 1 cpu, nothing specil in the log.

![image](https://user-images.githubusercontent.com/31133476/180756525-ee18dee2-99d5-43f6-977c-211d29ab9a9a.png)

![image](https://user-images.githubusercontent.com/31133476/180756587-09c6520f-b849-4e38-9446-fd674d75606c.png)

Inside the POD, it shows `harvester` process is very busy.
```
harvester-756cd66d6d-x4gm6:/var/lib/harvester/harvester # 

Tasks:   4 total,   1 running,   3 sleeping,   0 stopped,   0 zombie
%Cpu(s): 17.3 us,  1.4 sy,  0.0 ni, 78.4 id,  2.9 wa,  0.0 hi,  0.0 si,  0.0 st
MiB Mem : 16002.84+total, 1420.094 free, 12233.33+used, 2349.410 buff/cache
MiB Swap:    0.000 total,    0.000 free,    0.000 used. 3433.902 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                              
    8 root      20   0 1111168 232776  27632 S 93.75 1.420   6:18.50 harvester                                                                                                                            
    1 root      20   0    4564    712    620 S 0.000 0.004   0:00.01 tini                                                                                                                                 
   22 root      20   0   15124   4184   2988 S 0.000 0.026   0:00.01 bash                                                                                                                                 
   49 root      20   0   40448   4132   3576 R 0.000 0.025   0:00.01 top                                                                                                                                  

```
There is no flooding log.
```
time="2022-07-22T12:44:13Z" level=info msg="Watching metadata for longhorn.io/v1beta2, Kind=Snapshot"
time="2022-07-22T12:44:13Z" level=info msg="Watching metadata for fleet.cattle.io/v1alpha1, Kind=ClusterGroup"
time="2022-07-22T12:44:13Z" level=info msg="Watching metadata for management.cattle.io/v3, Kind=FleetWorkspace"
W0722 12:44:13.478881       8 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
..
W0722 13:53:10.579244       8 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
W0722 14:00:43.580306       8 warnings.go:70] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
harv1:~ # 
```
**To Reproduce**

It occus in my local `master-head` build version, not sure is reproducable.

In `v1.0.3 rc1` release, it does not exist.
https://github.com/harvester/harvester/releases/tag/v1.0.3-rc1

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  master-head, 2022.07.20
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM based

**Additional context**

**Comment by w13915984028** [comment]
In debugging this issu, I found it is caused by below API.

https://github.com/rancher/dynamiclistener/blob/master/listener.go#L167

```
func (l *listener) WrapExpiration(days int) net.Listener {
	ctx, cancel := context.WithCancel(context.Background())
	go func() {
		// busy-wait for certificate preload to complete
		for l.cert == nil {
			runtime.Gosched()
		}
```
Though I am not fully sure how this issue is produced, but when such condition is met, the WrapExpiration indeed causes deadloop.

It is tracked with https://github.com/rancher/dynamiclistener/issues/63

**Comment by w13915984028** [comment]
In Harvester startup log, has following info:

```
time="2022-07-24T19:19:09Z" level=info msg="Listening on :8443"
time="2022-07-24T19:19:09Z" level=warning msg="dynamiclistener [::]:8443: no cached certificate available for preload - deferring certificate load until storage initialization or first client request"
```

With debug, it showed
```
time="2022-07-25T10:07:16Z" level=warning msg="dynamiclistener [::]:8443: no cached certificate available 
for preload - deferring certificate load until storage initialization or first client request, 
id:4 name:secret:
&Secret{ObjectMeta:{      0 0001-01-01 00:00:00 +0000 UTC <nil> <nil> map[] map[] [] []  []},
Data:map[string][]byte{},Type:,StringData:map[string]string{},Immutable:nil,}"
```

With debug
```
func (l *listener) WrapExpiration(days int) net.Listener {
	ctx, cancel := context.WithCancel(context.Background())

	go func() {
		// busy-wait for certificate preload to complete
	  cnt :=0
		for l.cert == nil {
			cnt += 1
			if cnt == 1000 {
				logrus.Errorf("dynamiclistener WrapExpiration loop 1000 times")
			} else if cnt == 50000 {
				logrus.Errorf("dynamiclistener WrapExpiration loop 50000 times")
			}
			runtime.Gosched()
		}
```		
it showed
```
time="2022-07-24T19:19:09Z" level=error msg="dynamiclistener WrapExpiration loop 1000 times"
time="2022-07-24T19:19:09Z" level=error msg="dynamiclistener WrapExpiration loop 50000 times"
```
The `Harvester` process in the POD, is forced to `runtime.Gosched()`, even though there is noting to do. 

It causes CPU to be 100%, but from the LOG, we did not find any controller/CRD is abnormal.

**Comment by w13915984028** [comment]
workaround, as following, the CPU is not busy anymore 

```
func (l *listener) WrapExpiration(days int) net.Listener {
	ctx, cancel := context.WithCancel(context.Background())

	go func() {
		// busy-wait for certificate preload to complete
		for l.cert == nil {
			time.Sleep(time.Millisecond)
		}
        }
```

**Comment by guangbochen** [comment]
@w13915984028, can u please help to bump the [dynamiclister](https://github.com/harvester/harvester/blob/master/go.mod#L74) of both the master and v1.0 branches, thanks.

**Comment by w13915984028** [comment]
@guangbochen  Please double check v1.0

The `dynamiclistener` used in Harvester v1.0 branch, seemed does not have this issue, it was caused by later change, we may keep v1.0 unchanged:

github.com/rancher/dynamiclistener v0.3.1-0.20211104200948-cd5d71f2fe95  //// Harvester v1.0 go.mod, it's v.0.3.1, but at 2021.11.04

https://github.com/rancher/dynamiclistener/releases/tag/v0.3.1  //// formal relase, at 2021.11.24

The bug related change was at committed at 2021.11.24
https://github.com/rancher/dynamiclistener/commit/284cc004e84101e4a5b9fa50c00e101095db83f6#diff-52136e2f401dea328d50069c304fe222eb004d0ca7b8b12e6e6c4adbc9df6979L165



In Harvester master branch, I will bump the `dynamiclistener`.

**Comment by guangbochen** [comment]
Cool thanks, let's move the issue target milestone to v1.1.0.

**Comment by w13915984028** [comment]
Summary of how to trouble-shooting this issue:

https://github.com/w13915984028/harvester-develop-summary/blob/main/harvester-pod-100-cpu-usage-issue-2558.md

**Comment by noahgildersleeve** [comment]
Tested in master-4ea12f4f-head. CPU usage looks good with low utilization.
![Screenshot_20220831_142114](https://user-images.githubusercontent.com/83787952/187787300-a051785b-6e7c-4fd8-b405-90b32f981ca6.png)
