### ISSUE TITLE
[BUG] Backup unable to be restored and the VM can't be deleted

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2559]
### Describe the bug
VM hanging on `restoring` state and can not be removed.

### To Reproduce
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to _Advanced/Settings_, setup `backup-target` with NFS or S3
3. Create Image for VM creation
4. Create VM `vm1`
5. Take backup from `vm1` as `vm1b`
6. Take backup from `vm1` as `vm1b2`
7. Click **Edit YAML** of `vm1b`, update field `status.source.spec.spec.domain.cpu.cores`, increase `1`
8. Stop VM `vm1`
9. Restore backup `vm1b2` with **Replace Existing**
10. Restore backup `vm1b` with **Replace Existing** when the VM `vm1` still in state `restoring`

### Expected behavior
VM should be restored successfully.

## Environment:
 - Harvester ISO version: **v1.0.3-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context

https://user-images.githubusercontent.com/5169694/180805112-2d6f3c5e-1f4e-486d-9441-010ecf8e8f24.mp4

**Comment by lanfon72** [comment]
update to `reproduce/often` because I can delete the VM sometimes.

**Comment by irishgordo** [comment]
While the `vm1` is in the 'restoring' state from replace-existing of backup `vm1b2` - then trying to immediately 'replace existing' with `vm1b` I'm noticing that there is an error of:
```
admission webhook "validator.harvesterhci.io" denied the request. Please wait for the previous VM restore on the default/vm1 to be complete first.
```
![must-wait](https://user-images.githubusercontent.com/5370752/182722180-3e2f606b-beef-4f8b-8f33-8d235587db4b.png)

But then if you wait just a few seconds it does go through 
![right-after-works](https://user-images.githubusercontent.com/5370752/182723481-c9eceaf8-e817-4c2e-b7a4-cf50c72507e3.png)

@lanfon72 was that error something you were seeing if you tried to restore while it was restoring?

I built the harvester iso by checking out harvester-installer at branch `v1.0`, then ran `make` then used that in a qemu/kvm vm with Harvester version: v1.0-60921953-head

**Comment by FrankYang0529** [comment]
Hi @irishgordo, I think that error is added from https://github.com/harvester/harvester/pull/2608. We would like to prevent users from restoring an existing VM which is in the `Restoring` state because this will have a race condition. I think the behavior that you got is expected.

**Comment by lanfon72** [comment]
@irishgordo as Frank's replied, we fix this bug by blocking restore a restoring VM.

So the criteria change to:
- User should NOT able to restore the VM which in restoring **state**
- The VM should be restored successfully

**Comment by irishgordo** [comment]
Awesome!
Thanks @FrankYang0529 & @lanfon72 - based around that this looks good so I'll go ahead and close it out :smile:
