### ISSUE TITLE
No description field on the volume edit page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#256]
**Steps to reproduce:**
1. Create a volume, then edit it
2. On the edit page, check on the page 

**Result:**
There is no description field on the edit page
![image](https://user-images.githubusercontent.com/57614736/99607812-8bb6f500-2a47-11eb-8502-bcc080e74843.png)

**Comment by DaiYuzeng** [comment]
![截屏2020-11-24 上午11 40 14](https://user-images.githubusercontent.com/15041915/100044134-dec6e880-2e49-11eb-9c81-c19463fa9063.png)

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/101323422-9d035c80-38a3-11eb-99ec-64cf385f2a94.png)
