### ISSUE TITLE
[BUG] VM hanging on restoring state when backup-target disconnected suddenly

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2560]
### Describe the bug
When restoring a VM and the backup-target suddenly disconnected, the VM will hang on `restoring` state and can not be deleted.

### To Reproduce
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to _Advanced/Settings_, setup `backup-target` with NFS or S3
3. Create Image for VM creation
4. Create VM `vm1`
5. Take Backup `vm1b` from `vm1`
6. Restore the backup `vm1b` to New/Existing VM
7. When the VM still in `restoring` state, update **backup-target** settings to _Use the default value_ then setup it back.

### Expected behavior
VM might not be able to restore successfully, but at least to be deleted successfully.

## Environment:
 - Harvester ISO version: **v1.0.3-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
N/A

**Comment by lanfon72** [comment]
update to `reproduce/often` because I can delete the VM sometimes.

**Comment by FrankYang0529** [comment]
Hi @lanfon72, thanks for filing the issue. I will add a webhook to prevent user update backup-target when there is any in progressing VMBackup/VMRestore. If you want to simulate network issues, probably you need to cut off network on KVM. It's cause that updating backup-target, LH will try to remove old LH Backup on system.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/182815313-71dd4e4e-51a2-4510-a70a-180765848334.png)
![image](https://user-images.githubusercontent.com/5169694/182815277-98baa7bc-42d1-4404-be87-d60f3b6ba1fd.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0-fc72be9f-head**
* **ui-source** Option: **Auto**
* **ui-index** URL: https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to _Advanced/Settings_ and update **ui-index** to `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html` and force refresh to make it applied.
3. Create a Image for VM creation
4. Create VM `vm1` and add some files or execute `ping 127.0.0.1 > hello`
5. Setup backup-target
    - To simply the disconnection, you can setup a *Minio* for S3 target by executing `docker run --name minis3 -dp 9000:9000 -p 9001:9001 minio/minio server /data --console-address ":9001"`
7. Take a backup `vm1b` of VM `vm1`
8. Delete `vm1`
9. Restore `vm1b` into `vm2`, and Restore `vm1b` into `vm3`
10. Disconnect backup-target connection
    - Execute `docker network disconnect bridge minis3` to disconnect the *Minio* container connection
12. Following Cafeterias should be fulfilled:
    - Delete `vm2`, it should be deleted successfully
    - Re-connect backup-target, `vm3` should be restored successfully
