### ISSUE TITLE
[BUG] harvesterhci.io.virtualmachineimage spec.displayName displays differently in single view of image

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2563]
**Describe the bug**
The `harvesterhci.io.virtualmachineimage` 's `spec.displayName` displays differently in the list view of images and in the single view of the image.  It looks like the image's `spec.displayName` doesn't currently implement [RFC 1123 Kubernetes naming](https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#names).

**To Reproduce**
1. Go to images.
2. Click "Create"
3. Upload an image or leverage an url - but name the image something like: 
```
<strong><em>something_interesting</em></strong>
```
4. Wait for upload to complete.
5. Observe the display name within the list of images
6. Compare that to clicking into the single image and viewing it and observe the display name there would render as:
```
&lt;strong&gt;&lt;em&gt;something_interesting&lt;/em&gt;&lt;/strong&gt;
```
7. Cross validate with a GET Request out to:  "https://your_harvester_vip/apis/harvesterhci.io/v1beta1/namespaces/default/virtualmachineimages", with the bearer token etc something like:
```
curl --location --request GET 'https://192.168.1.215/apis/harvesterhci.io/v1beta1/namespaces/default/virtualmachineimages' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer token-something:a_unique_string'
```
Would return JSON chunk of:
```
...
            "spec": {
                "checksum": "",
                "displayName": "<strong><em>something_interesting</em></strong>",
                "pvcName": "",
                "pvcNamespace": "",
                "sourceType": "upload",
                "url": ""
            },
...
```
**Expected behavior**
That the list view naming would be the same as the single view of the image - or that RFC 1123 would be implmented on harvesterhci.io.virtualmachineimage.spec.displayName.
It looks like currently via harvester/dashboard there is no additional things that might prevent it from just using the `spec.displayName`: https://github.com/harvester/dashboard/blob/master/shell/models/harvester/harvesterhci.io.virtualmachineimage.js#L234-L248 - so I'm not initially sure why the rendering of the display name breaks given an unconventional naming scheme. 

**Support bundle**

[supportbundle_ca07f9bc-bcd0-47a1-af4b-cdba61337945_2022-07-25T19-49-29Z.zip](https://github.com/harvester/harvester/files/9184370/supportbundle_ca07f9bc-bcd0-47a1-af4b-cdba61337945_2022-07-25T19-49-29Z.zip)

**Environment**
Dell PowerEdge R720, 2 x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (total of 20cores)
64GB DDR3 ECC RAM, 1TB Samsung SSD
Harvester-Version: v1.0.3-rc1

**Additional context**
![example-of-image-problem](https://user-images.githubusercontent.com/5370752/180862966-81027fbf-1561-452b-80b5-1ac6243a62fd.png)

**Comment by WuJun2016** [comment]
~@irishgordo  The displayName is now verified using the rules of RFC 1123~

**Comment by irishgordo** [comment]
@WuJun2016 thanks for adding the validation and placeholder to the harvester/dashboard frontend :smile: :+1: 

I validated via running dashboard in `yarn dev --spa` with the `.env` file holding the API to my bare-metal Harvester node.
(with last commit being: commit dad3cdf3018990eba34a03ca71ca8c70bd1b849c (HEAD, upstream/release-harvester-v1.0))

As noted validation on harvester/dashboard front-end does take place:
![validation-takes-place](https://user-images.githubusercontent.com/5370752/181099140-b57a4381-228b-4dec-9244-a9091591c6cd.png)

Placeholder also gets filled given an image first prior:
![placeholder-fires](https://user-images.githubusercontent.com/5370752/181099211-cc72cbcd-e6c2-415c-8bd4-87e5aa830e15.png)

I was curious @WuJun2016 did we want to leave this open until backend validation for Harvester has been implemented for RFC 1123, or do we not intend to implement backend validaton? 

As you can create an image with a name via the API call that doesn't follow RFC1123 via:
```
curl --location --request POST 'https://192.168.1.215/apis/harvesterhci.io/v1beta1/namespaces/default/virtualmachineimages' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer token-yourtoken:uniquethings' \
--header 'Content-Type: application/json' \
--data-raw '{
    "apiVersion": "harvesterhci.io/v1beta1",
    "kind": "VirtualMachineImage",
    "metadata": {
        "annotations": {
            "field.cattle.io/description": "test-image-created-via-api-POST",
            "harvesterhci.io/image-name": "<strong>some_test_name_made_by_api</strong><em>this-was-created-via-api-call</em>"
        },
        "labels": {
            "harvesterhci.io/image-type": "",
            "harvesterhci.io/os-type": ""
        },
        "name": "2395-something"
    },
    "spec": {
        "checksum": "",
        "displayName": "<strong>some_test_name_made_by_api</strong><em>this-was-created-via-api-call</em>",
        "pvcName": "",
        "pvcNamespace": "",
        "sourceType": "download",
        "url": "https://cloud-images.ubuntu.com/releases/jammy/release-20220712/ubuntu-22.04-server-cloudimg-amd64-disk-kvm.img"
    }
}'
```

Which then still renders, a `201` Created on the API side:
![still-can-create-via-api](https://user-images.githubusercontent.com/5370752/181099628-2abba7aa-b7f5-41cf-8688-d7de7a0dbabd.png)

Then when viewing the image as a single view, you will still see the name be rendered like:
![still-shows-if-via-api-displayed-interestingly](https://user-images.githubusercontent.com/5370752/181099886-88d44aaf-98fd-4d4a-8458-10a0191c545e.png)

And the list view call from the API on the images, will also still display it as it was created:
![listing-still-shows-image-as-display-name](https://user-images.githubusercontent.com/5370752/181099970-2c0d26cc-3c8e-49b5-aebf-432e56a4e395.png)

**Comment by WuJun2016** [comment]
@irishgordo  I don't think it's necessary to add checks on the backend。     cc @guangbochen you think ?

**Comment by guangbochen** [comment]
I don't think we should add any RFC1123 validations to the display name since it is designed to be a string value. For the above case, would prefer to fix the UI display name correctly.

**Comment by WuJun2016** [comment]
@irishgordo  The frontend removed the RFC1123 validate and now handles the display of the html.
<img width="1491" alt="image" src="https://user-images.githubusercontent.com/24985926/181199576-1f003343-2ae0-4fec-a7e9-3970c7911243.png">

**Comment by irishgordo** [comment]
@WuJun2016  thanks for those edits :smile: !
I've validated that they look good on your branch.
I know harvester/dashboard#392 is still pending getting merged into release-harvester-v1.0 but I've gone ahead and validated on your branch.
![Screenshot from 2022-07-27 10-08-31](https://user-images.githubusercontent.com/5370752/181307917-16292fdf-0aa1-46b6-b52e-7833e988fcce.png)
![Screenshot from 2022-07-27 10-08-05](https://user-images.githubusercontent.com/5370752/181307921-f50cf1af-1079-485a-b397-05e462bf925c.png)
Looks good to me :smile:

**Comment by irishgordo** [comment]
@WuJun2016 it looks like harvester/dashboard#392 got moved back to a draft PR, since it's not been merged into harvester/dashboard:release-harvester-v1.0 - I can move this back to Implementation if that works :smile: ?  I can re-validate / re-review later on this :+1:

**Comment by WuJun2016** [comment]
I'm waiting for the rancher team to review the code, if there are no more problems, I will merge it on my side.

**Comment by irishgordo** [comment]
Reviewed this again :smile:  - looks good, tested off `release-harvester-v1.0` - I'll go ahead and close this out

![works-with-naming](https://user-images.githubusercontent.com/5370752/182219721-bf3b58a8-fced-4c4c-8fe2-9d11c761adff.png)
