### ISSUE TITLE
[BUG] Press the Enter key, the page will be refreshed automatically

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2569]
**Describe the bug**

Press the Enter key, the page will be refreshed automatically

**To Reproduce**
1. go to setting page
2. edit `cluster-registration-url` setting.   (The same problem exists with `ui-index`， `upgrade-checker-url`， `support-bundle-timeout`)
3. Focus the mouse on the input box
4. Press enter   key（The page will refresh）

https://images.zenhubusercontent.com/279592699/06360e66-f2ba-40a5-8b9b-f2a17c1a1ce0/____2022_07_26_19_38_12.mov

**Expected behavior**

Pressing Enter should not refresh the page，  

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.0-b6244fcd-head` (220801, backport v1.0). Close this issue

### Result
On v1.0.3 backport, when we press the `Enter` key in the following page fields, it will not being refreshed automatically.

* Cluster registration 
![image](https://user-images.githubusercontent.com/29251855/182070054-6dbaa021-f1de-436e-8117-bd3ece64dfea.png)

* ui-index
![image](https://user-images.githubusercontent.com/29251855/182070120-70fdd0de-62f6-4005-a920-56fbd939483b.png)

* upgrade-checker-url
![image](https://user-images.githubusercontent.com/29251855/182076320-1d836590-a245-4123-9756-e0504b001a3d.png)

* support-bundle-timeout
![image](https://user-images.githubusercontent.com/29251855/182076508-d98091b3-d62b-45d1-961f-69728cb33194.png)

Also checked the following pages

* http proxy
* overcommit-config
* support-bundle-image
* vm-force-reset-policy
* backup target
* release download url

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `v1.0-b6244fcd-head` (220801, backport v1.0)

### Verify Steps
1. Check every page have input filed in the Settings page
2. Move cursor to any input field 
3. Click the `Enter` button 
4. Check the page will not be automatically loaded
