### ISSUE TITLE
N/A appears in progress column at the beginning of creating a volume

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#257]
**Steps to reproduce:**
1. Create a new volume
2. Check the progress on the volume list

**Result:**
N/A appears in the progress column at the beginning of creating a the volume
![image](https://user-images.githubusercontent.com/57614736/99613710-046f7e80-2a53-11eb-8adc-77b8deb1c6c8.png)

**Comment by guangbochen** [comment]
@DoNotSayYes it is better to elaborate on what is ur expectation of the correct status should be.

**Comment by DoNotSayYes** [comment]
> @DoNotSayYes it is better to elaborate on what is ur expectation of the correct status should be.

Displaying 0% would be better if it must have something to show at the beginning of creating a volume

**Comment by DaiYuzeng** [comment]
Display nothing if the progress of volume status is 'N/A'

**Comment by DoNotSayYes** [comment]
Validated
