### ISSUE TITLE
[BUG] Websocket connection issues with Harvester Rancher integration

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2572]
**Describe the bug**

You get continued websocket errors from Rancher while navigating the UI and timeouts and errors while doing Harvester related tasks
**To Reproduce**
1. Create a single node Rancher Docker instance
2. Create a 3 node harvester instance
3. Import Harvester into Rancher
4. Try to create a RKE cluster

**Expected behavior**

You shouldn't get errors while using Rancher or Harvester
**Support bundle**
[supportbundle_4cd8547e-c79d-4eee-8060-fbc4b0bb7bcd_2022-07-26T18-57-24Z.zip](https://github.com/harvester/harvester/files/9192630/supportbundle_4cd8547e-c79d-4eee-8060-fbc4b0bb7bcd_2022-07-26T18-57-24Z.zip)

**Environment**
 - Harvester ISO version: v1.0.3-rc1
 - Rancher version: v2.6.7-rc3 single node docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe-examples Vagrant 3 node

**Additional context**
You can get some of the tasks to complete if you retry. There are numerous websocket errors in the browser console. Also RKE1 and RKE2 deployments seem to be failing, although the VMs are being created on Harvester.
![Screenshot_20220726_111359](https://user-images.githubusercontent.com/83787952/181115316-69a6a21b-98ad-4cf5-866a-219502421a4f.png)
![Screenshot_20220726_111227](https://user-images.githubusercontent.com/83787952/181115317-651a61a2-9ee0-4d2e-9167-f17628a23d92.png)
![Screenshot_20220726_110200](https://user-images.githubusercontent.com/83787952/181115318-42915a2a-a4bd-4995-99e7-d8480e2408d2.png)

**Comment by n313893254** [comment]
The issue can be reproduced by the following steps:

1. Deploy a rancher server by docker run
2. Access the rancher UI
3. Remove the rancher server and deploy the same version rancher server, make sure to use the same endpoint
4. Refresh the Rancher UI, which will require resetting the password
5. Websocket can not connect succeed

The workaround can be clear the browser cache ~~or use the helm chart installation.~~

Might be caused by the certificate on the browser, change to v1.1.0 as it needs to investigate further.

**Comment by guangbochen** [comment]
@noahgildersleeve did u re-deployed the Rancher server to the same node or use the same IP, a `docker run` Rancher will use a self-signed cert and the chrome will not update the subject alt name(SAN) automatically, so u will need to re-enable the cert trust manually again. (Note: Docker run Rancher is not supported for production and users are expecting to use a proper helm install method only.)
<img width="429" alt="image" src="https://user-images.githubusercontent.com/4569037/181445096-6a680f52-ca78-4127-80f5-f0c2877be2ea.png">

**Comment by noahgildersleeve** [comment]
@guangbochen I rebuilt my VM that I was running Rancher on and re-deployed it. During subsequent testing I couldn't reproduce the issue. I'm running through some more integration tests and will keep an eye out for the issue. I haven't seen it since the re-deploy though and I haven't heard of anyone else having the issue during testing.

**Comment by bk201** [comment]
Close since it can't be produced. Please re-open if you hit this issue again.
