### ISSUE TITLE
[BUG] Virtualization Management has no option to delete cluster(s) from rancher

### ISSUE THREAD

**Issue by slickwarren** [harvester/harvester#2574]
**Describe the bug**
there is no option to delete a cluster through virtualization management

**To Reproduce**
1. import a harvester cluster through virtualization management (in rancher)
2. try to delete the cluster

**Expected behavior**
you should have the option to delete a cluster through rancher

**Support bundle**
[supportbundle_06891336-f7b4-4869-8c05-43e7d679310d_2022-07-26T19-39-29Z.zip](https://github.com/harvester/harvester/files/9192865/supportbundle_06891336-f7b4-4869-8c05-43e7d679310d_2022-07-26T19-39-29Z.zip)

**Environment**
 - Harvester ISO version: 1.0.3-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge 510

**Additional context**
related to https://github.com/rancher/rancher/issues/38429
<img width="1552" alt="Screen Shot 2022-07-26 at 12 31 02 PM" src="https://user-images.githubusercontent.com/16691014/181098200-3cb4de43-ad6d-4175-afd6-4a814c98d31c.png">

**Comment by noahgildersleeve** [comment]
Tested with Harvester v1.0.3-rc1 and Rancher v2.6.7-rc5. Verified as fixed.

## Verification Steps

1. import a harvester cluster through virtualization management (in rancher)
2. Delete cluster
