### ISSUE TITLE
[BUG] Boot in EFI mode not selected when creating multiple VM instances using VM template with EFI mode selected.

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#2577]
**Describe the bug**
I created a VM template and selected **Boot in EFI mode**. When creating instances the UI shows **Boot in EFI mode** selected but after that VM boots with legacy BIOS mode, and EFI mode checkbox was not checked, and there is no /sys/firmware/efi present.

**To Reproduce**
1. Go to **Template**, create a VM template with **Boot in EFI mode** selected. (For this case I'm using Ubuntu Server Jammy cloud image)
![截屏2022-07-27 16 09 59](https://user-images.githubusercontent.com/9990804/181196319-d95a4d23-ea31-418c-9fd2-152821d56930.png)
2. Go to **Virtual Machines**, click **Create**, select **Multiple instance**, type in a random name prefix, and select the VM template we just created.
![截屏2022-07-27 16 12 36](https://user-images.githubusercontent.com/9990804/181196711-5af5f3df-6f3f-4538-b6b0-78870cf06b0a.png)
3. Go to **Advanced Options**, for now this EFI checkbox should be checked without any issue.
![截屏2022-07-27 16 13 50](https://user-images.githubusercontent.com/9990804/181196934-1249902f-47dd-44dc-bced-5911ffcfdf16.png)
4. Click **Create**, and go to any VM we just created using this template, select **Config**, and we will see this **Boot in EFI mode** not checked.
![截屏2022-07-27 16 15 58](https://user-images.githubusercontent.com/9990804/181197442-1be8af10-5c97-41e6-9a0f-96b67592a0ca.png)
5. Boot up any VM we just created if it's not booted up, login into the system, and we can see no /sys/firmware/efi present.
![截屏2022-07-27 16 18 54](https://user-images.githubusercontent.com/9990804/181197951-40fbd3ee-5df1-4ac1-90d0-b184b15388a5.png)

**Expected behavior**
VM instances should boot in EFI mode correctly, not in legacy BIOS mode.

**Support bundle**

[supportbundle_f72326aa-4348-419e-935c-b561533d8249_2022-07-27T08-02-23Z.zip](https://github.com/harvester/harvester/files/9196459/supportbundle_f72326aa-4348-419e-935c-b561533d8249_2022-07-27T08-02-23Z.zip)

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Dell PowerEdge R630

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.0-b6244fcd-head` (08/01). Close this issue.

### Result
Now we can create multiple VM instance using VM template with EFI mode selected

* All VMs are running
![image](https://user-images.githubusercontent.com/29251855/182343361-532a7cee-04de-4a0e-9bc6-803f7cc66e94.png)

* Check VM setting, the booting in EFI mode is checked
![image](https://user-images.githubusercontent.com/29251855/182343254-4a421a04-aa3f-471c-a258-930a98cc84d3.png)

* Access each VM we can see `/sys/firmware/efi` present
  ```
  ubuntu@efi-01:~$ ls /sys/firmware/
  acpi  dmi  efi  memmap
  ```
  ```
  ubuntu@efi-02:~$ ls /sys/firmware/
  acpi  dmi  efi  memmap
  ```
  ```
  ubuntu@efi-03:~$ ls /sys/firmware
  acpi  dmi  efi  memmap
  ```

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `v1.0-b6244fcd-head`

### Verify Steps
1. Create a VM template, check the `Booting in EFI mode`
2. Create multiple VM instance and use the VM template have `Booting in EFI mode` checked
3. Wait for all VM running
4. Check the EFI mode is enabled in VM config
5. ssh to each VM
6. Check the /etc/firmware/efi file
