### ISSUE TITLE
[BUG] When first entering the harvester cluster from Virtualization Managements, some vm's in namespace are not shown in the list

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2578]
**Describe the bug**

When the namespace filter is `All Namespace`, all vm's should be displayed

**To Reproduce**
1. Create a harvester cluster
2. Create a VM in the `default` namespace
3. Creating a Namespace  (eg: `test-vm`)
4. Import the Harvester cluster in Rancher
5. access to the harvester cluster from `Virtualization Management`
6. click `Virtual Machines` tab
7. The vm list is displayed as follows
![image](https://user-images.githubusercontent.com/24985926/181213378-bb8d9c72-302b-4559-87f4-7fe6f99fd8ab.png)

NOTO:   This problem exists if you come in from `Virtualization Management` and do not refresh the page.

**Expected behavior**

`test-vm-1 `should also be shown in the list

![image](https://user-images.githubusercontent.com/24985926/181211867-4f3889cd-a14e-463c-9a7f-0aee2d5f358e.png)

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **not fixed** on Rancher `v2.6.7-rc5` with Harvester `v1.0.3-rc1`. Move the issue to implement

### Result
While accessing Harvester virtual machine page from Rancher virtualization management
Under all `All Namespaces` we still can't see the custom namespace `test-vm` and related vm `test-vm-1`  
![image](https://user-images.githubusercontent.com/29251855/182092099-8baf85b4-e615-4393-bfed-aec62bdaac32.png)

### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: `v1.0.3-rc1` 
* Rancher version: `v2.6.7-rc5`
* Rancher ui-dashboard-index: 
* Rancher `https://releases.rancher.com/dashboard/latest/index.html`
* Rancher ui-offline-preferred: Dynamic

### Verify Steps
1. Create a namespace `test-vm` in Harvester
  ![image](https://user-images.githubusercontent.com/29251855/182091299-c439bf4b-7e57-454f-9203-bfb4f45bb174.png)
2. Create a virtual machine `test-vm-1` in the `test-vm` namespace 
  ![image](https://user-images.githubusercontent.com/29251855/182092148-fff3bda4-4fa7-4dc7-b881-76d68249d350.png)
3. Import the Harvester cluster in Rancher
4. Access to the harvester cluster from Virtualization Management
5. click Virtual Machines tab
6. Check the test-vm-1 can display in the virtual machine page

**Comment by n313893254** [comment]
Hi, @TachunLin. Could you set `ui-offline-preferred: Remote` and verify again? I think the server loaded the local UI-index which does not contain the commit.

**Comment by TachunLin** [comment]
Hi @n313893254 
By setting `ui-offline-preferred: Remote` and verify it again. 
Now I can see the custom namespace test-vm and related vm test-vm-1 from Rancher virtualization management. Close this issue. 
![image](https://user-images.githubusercontent.com/29251855/182337711-cd810744-ad6c-4419-8131-c5d4e1f037a6.png)

### Test Information
* Test Environment: 1 node1 harvester on local kvm machine
* Harvester version: `v1.0.3-rc1` 
* Rancher version: `v2.6.7-rc5`
* Rancher ui-dashboard-index: 
* Rancher `https://releases.rancher.com/dashboard/latest/index.html`
* Rancher ui-offline-preferred: `Remote`
* UI version: `https://releases.rancher.com/dashboard/latest/39ab4ff30bdc5b23312f.js`
