### ISSUE TITLE
[BUG] 3 nodes setup: VM crashed on running node while 2 nodes are down

### ISSUE THREAD

**Issue by tgazik** [harvester/harvester#2581]
**Describe the bug**
In 3 nodes cluster, when 2 nodes are powered off (hard reset) the VMs on running node should survive. The VM where in time off 2 went down were some data write ongoing crashed and didn`t recovered despite it was running on node, which was not turned off.

**To Reproduce**
1. 3 nodes cluster - node01, node02, node03
2. create standart VM (in our case ubuntu focal cloudimage) with second volume of 600GB. Let`s assume VM was assigned to node01.
3. login to VM, format second 600GB volume and mount. Write 500GB of zero data with f.e dd if=/dev/zero of=500GB.txt count=1024 bs=524288000
4. while writing data with dd turn off node02, node03 (hard reset).
5. created VM with dd write running on node01 crashed with IOerror and it`s not recovered until remaining nodes are up.

other "idle" VMs running on node01 are running fine

**Expected behavior**
VM will continue running without any problem

**Support bundle**
can provide if needed

**Environment**
 - Harvester ISO version: v1.0.2
 - Underlying Infrastructure: 3 nodes setup

**Additional context**

**Comment by w13915984028** [comment]
Harvester has Longhorn as the CSI layer, by default it will have 3 replicas for PVC, in your setup, there are 3 nodes, each node will hold one replica.

When writing data to VM's disk, in the background, the data will be replicated to another 2 replicas (in another 2 nodes) in paralle. Then you forcely power off the other 2 nodes, the onging writing action is broken.

Please generate a support bundle: https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#generate-a-support-bundle

@PhanLe1010 any idea of this issue? thanks.

**Comment by tgazik** [comment]
Support bundle uploaded to ftp server /incomming/supportbundle_github_issue-2581_ec3d3da9-5634-46d1-aed0-f28845f1da00_2022-07-27T12-58-51Z.zip
VM name used for tests: tg-hatest-dd and tg-hatest2-dd
![image (1)](https://user-images.githubusercontent.com/76015208/181261318-3c8e8231-9980-46b2-ab2a-87cda4d807df.png)

**Comment by Martin-Weiss** [comment]
Is a "double failure" a valid test in a 3 node deployment? 
Kubernetes (and due to that harvester) requires the majority of the control plan to be running for any proper functionality.

**Comment by PhanLe1010** [comment]
> Harvester has Longhorn as the CSI layer, by default it will have 3 replicas for PVC, in your setup, there are 3 nodes, each node will hold one replica.
> 
> When writing data to VM's disk, in the background, the data will be replicated to another 2 replicas (in another 2 nodes) in paralle. Then you forcely power off the other 2 nodes, the onging writing action is broken.
> 
> Please generate a support bundle: https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#generate-a-support-bundle
> 
> @PhanLe1010 any idea of this issue? thanks.

If there is a replica on node01, the ongoing writing action is broken because Longhorn return error for that IO. However, when the application (the dd command) retry the write it should succeed. Can we double check if there is a replica on node01?

**Comment by tgazik** [comment]
i tried now again and check the volume in longhorn, it was healthy and running on all 3 nodes and it was attached to the node where VM was running. I run dd command and turned off again the rest 2 nodes. The result was same, VM is frozen and after nodes came back online i can see in GUI that IO error which i pasted above.

**Comment by PhanLe1010** [comment]
Can we have yaml for the VM, PVC, PV, longhorn volume, volume replicas, volume engine?

**Comment by tgazik** [comment]
[harv_github_issue_2581.zip](https://github.com/harvester/harvester/files/9288720/harv_github_issue_2581.zip)
@PhanLe1010 sending you requested files. Regarding "longhorn volume, volume replicas, volume engine" i was not sure what you need, so i made a screenshot, hope it will be enough. In case you need something else please just let me know and i will send you.

btw: i tested the same scenario on our second testing cluster and there it was working fine, dd was continuing writing and VM was up.
Thanks

**Comment by Vicente-Cheng** [comment]
Update my local test scenario:

1. Create 3 nodes (node-0, node-1, node-2) harvester cluster.

2. Create 1 VM (based on ubuntu 20.04 focal) on node-0

3. do action

    `root@vm002:~# dd if=/dev/zero of=file001 bs=4k count=5242880 oflag=sync`

4. shutdown (node-1, node2) with `virsh destroy` on the host

5. try to connect back to VM and write a file.

```
    ubuntu@vm002:~# echo "hello world" > hello.txt
    ubuntu@vm002:~$ cat hello.txt
    hello world!
```

6. wait until the dd is complete (node-1, node-2 are still down)

```
    root@vm002:~# dd if=/dev/zero of=file001 bs=4k count=5242880 oflag=sync
    dd: error writing 'file001': No space left on device --> sorry I calculate wrong size 
    2094044+0 records in
    2094043+0 records out
    8577200128 bytes (8.6 GB, 8.0 GiB) copied, 4249.1 s, 2.0 MB/s
```

The write operation looks fine (NO EIO) and makes sense.

Would try to do some tests to investigate how it happen.

**Comment by guangbochen** [comment]
close as this can't be reproduced and has inactivity status, please reopen it when encountering this again by providing proper reproduction steps, thanks.
