### ISSUE TITLE
[BUG] VM Template's default network model is empty

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2583]
### Describe the bug
https://user-images.githubusercontent.com/5169694/181250903-91007cea-54e5-4e05-8591-70090411bef4.mp4

### To Reproduce
1. Install Harvester with any nodes
2. Create a Image for VM creation
3. Create VM `vm1` via `raw-image-base-template`
4. Navigate to Networks tab, field `Model` should not be empty

### Expected behavior
As it is marked with asterisk (**required**), it should not be empty, or the `Create` button should show errors to ask user to update it.

## Environment:
 - Harvester ISO version: **v1.0.3-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

**Comment by irishgordo** [comment]
@lanfon72 I was also noticing a few issues with networking, though possibly unrelated, and it may have been due to something on my home lab switch.

I was briefly seeing:
```
{
  "type": "error",
  "links": {},
  "code": "InternalError",
  "message": "admission webhook \"mutator.harvesterhci.io\" denied the request: json: cannot unmarshal object into Go struct field Interface.spec.template.spec.domain.devices.interfaces.model of type string",
  "status": 500
}
```
But after removing the VM and just rebuilding, it was fine.
It's been hard to reproduce since.

Rancher: v2.6.6
Harvester: v1.0.3-rc1
Bare-metal for both

**Comment by guangbochen** [comment]
When the `model` is not defined it will default to the value `virtio `, however, this will not block users from success creating VMs in the current UI, discussed this with the UI team and prefer to fix it in the v1.1.0.

**Comment by lanfon72** [comment]
@guangbochen this probably not UI bug, I checked those default templates, **Model** field is empty.
I think we probably need to update the template configuration in backend.

ref to #2592

**Comment by guangbochen** [comment]
@lanfon72 yes we can mitigate the issue by setting the template's network model value to `virtio`, and it would be good to fix another template issue https://github.com/harvester/harvester/issues/2592 at the same time.

But what I mean in the above comment is that the model field is optional, so when it is either empty or not specified, it will always default to use `virtio` driver when converting the YAML into the `qemu-kvm` process, so from the UI side, what we really need to fix is either make this field as optional or set it defaults to `virtio` even if the value is empty.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0-2ddbc24c-head**
* **ui-source** Option: **Auto**
* **ui-index** URL: `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html`

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2583#issue-1319526281
