### ISSUE TITLE
[BUG] VM's Reserved Memory field will reload old value automatically

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2589]
### Describe the bug

https://user-images.githubusercontent.com/5169694/181459759-9930ab98-afbb-40b9-a417-0a41c170929c.mp4

### To Reproduce
1. same as the video record

### Expected behavior
Field value should be able to input new value.

## Environment:
 - Harvester ISO version: **v1.0.3-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

**Comment by lanfon72** [comment]
The VM is created via `windows-iso-image-base-template`, field **OS Type** was empty but fill **Linux** automatically.

**Comment by WuJun2016** [comment]
The reason for this is that the websocket keeps pushing vm-related information, causing the front-end page to be re-rendered all the time (kubevirt.io.virtualmachine, kubevirt.io.virtualmachineinstance).    

Moved to v1.1.0 fix.    

workaround:  If the websocket push is fast, you can edit this value via yaml.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0-2ddbc24c-head**
* **ui-source** Option: **Auto**
* **ui-index** URL: `https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html`

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2589#issue-1320585631
