### ISSUE TITLE
auto config a new joined node as management node or compute node

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#259]
when adding a new node to the existing harvester cluster using ISO installation we should allow auto-configuration of the role to either be management or compute node(by default).

1. [x] auto promotes the compute node to be a management node when meets the criteria.
1. [ ] <s>remove the management node and promote a new one when the downtime is overdue.</s>
1. [x] remove node roles from the listing page but kept on the detail page

**Comment by guangbochen** [comment]
- [x] the node name for the management node is `harvester-1` while other nodes use `harvester-<uuid>`. Maybe the duplicate name is the issue. can we check from the ISO side, thanks to @gitlawr

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/270, https://github.com/rancher/harvester-installer/pull/10

**Comment by futuretea** [comment]
link to PR https://github.com/rancher/harvester-installer/pull/42

**Comment by DoNotSayYes** [comment]
Test completed
