### ISSUE TITLE
[BUG] Unable to provision RKE2 cluster from external Harvester cloud credential

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2590]
**Describe the bug**

Unable to provision RKE2 cluster with external Harvester cloud credential 
It stuck in `waiting for cluster agent to connect` 
![image](https://user-images.githubusercontent.com/29251855/181463626-84628c2a-3a58-4e6f-8c16-2b9c95fd41c1.png)
![image](https://user-images.githubusercontent.com/29251855/181464248-d2e14aea-cf67-4e86-af36-6e283add8cd1.png)

**To Reproduce**
1. Import Harvester from Rancher
2. Download Kubeconfig from Harvester support page 
3. Copy the kubeconfig content
4. Open Cluster Management -> Cloud credential
5. Select Harvester
6. Check External Harvester 
7. Copy the kubeconfig content
![image](https://user-images.githubusercontent.com/29251855/181478887-903bea84-0abb-4563-97e4-4cb4f76a1a49.png)
8. Provision a RKE2 cluster 
9. Add user data 
  ```
  password: 123456
  chpasswd: { expire: False }
  ssh_pwauth: True
  
  ```
10. Start provisioning 

**Expected behavior**

Can provision RKE2 cluster correctly with external Harvester cloud credential

**Support bundle**

[supportbundle_65a13b64-766b-4b32-aa59-a40e087c70f5_2022-07-28T10-38-26Z.zip](https://github.com/harvester/harvester/files/9208307/supportbundle_65a13b64-766b-4b32-aa59-a40e087c70f5_2022-07-28T10-38-26Z.zip)

**RKE2 log**
[rke2-server.log](https://github.com/harvester/harvester/files/9208379/rke2-server.log)

**Environment**
 - Harvester ISO version: v1.0.3-rc1 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node Harvester on local kvm machine 
 - Rancher version: v2.6.7-rc4

**Additional context**

**Comment by guangbochen** [comment]
External Harvester node driver is still an experimental support feature, but would be good if we can take a look at this issue, thanks cc @yaocw2020

**Comment by irishgordo** [comment]
@TachunLin 
@guangbochen 

Working through [Setting Up Experimental External Harvester Cloud Credential](https://harvester.github.io/tests/manual/harvester-rancher/42-add-cloud-credential-kubeconfig/) - I was able to reproduce this same issue with the following setup:

#### Environment:
**Harvester Node:**
- bare-metal Dell PowerEdge R720:
    - 64GB DDR3 ECC RAM
    - 2 x Intel(R) Xeon(R) CPU E5-2670 v2 @ 2.50GHz (total of 20cores)
    - 1TB Samsung SSD
    - 1 GB Ethernet Integrated NIC: Intel(R) GbE 4P I350-t rNDC
    - 1 GB Ethernet Additional NIC Card:  Intel(R) PRO/1000 PT Quad Port LP server Adapter
    - iDRAC 7 Card Installed	
    - Harvester Version: v1.0.3-rc1
    
**HA Rancher:**
- 3 node highly-available bare-metal k3os cluster running Rancher:
    - Intel Xeon E3-1265L v3 @ 2.5 ghz (8 cores)
    - 16 GB DDR3 Memory
    - 400GB Kingston SSD
    - Integrated 1GB Ethernet 
    - Rancher Version: v2.6.6
 
#### Notes:
- when adding the experimental external harvester cloud credential that is able to complete successfully 
- when creating an rke2 cluster using that external harvester cloud credential, there is a **404** that fires first, yielding this:
```
### REQUEST ###
GET /v3/cloudcredentials/[object%20Object] HTTP/2
Host: k3scluster.localdomain
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:101.0) Gecko/20100101 Firefox/101.0
Accept: application/json
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
x-api-csrf: af309f726d
Connection: keep-alive
Referer: https://k3scluster.localdomain/dashboard/c/c-m-n59bx9p6/manager/provisioning.cattle.io.cluster/create?type=harvester
Cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; CSRF=af309f726d; R_SESS=token-kvnvh:kbnzh75bkld2b6xrlpg2m6ztv6thldw2966zknt72prtrn64cdl2r4
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
TE: trailers

### RESPONSE ####
{"baseType":"error","code":"NotFound","message":"failed to find resource by id","status":404,"type":"error"}
``` 
- when ignoring that, but manually filling out things within the form on the rke2 cluster configuration, (example: manually entering the cloud image typing it in as:  default/image-file-name-that-was-uploaded-on-harvester.iso), then submitting, that submission is successful but rke2 does not provision

#### Provisioning Loop:
- upon manually entering / filling-out the rke2 since the images from external harvester cloud credentials don't auto-populate as a drop down we see the following pattern:
```
-  Creating server [fleet-default/test-rke2-pool1-799222e1-2fgsl] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-4pf4g in infrastructure provider 
-  Deleting server [fleet-default/test-rke2-pool1-799222e1-2fgsl] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-4pf4g in infrastructure provider 
-  Creating server [fleet-default/test-rke2-pool1-799222e1-5nwzr] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-48njq in infrastructure provider 
-  Deleting server [fleet-default/test-rke2-pool1-799222e1-5nwzr] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-48njq in infrastructure provider 
-  Creating server [fleet-default/test-rke2-pool1-799222e1-64hhh] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-gg67w in infrastructure provider 
-  Failed creating server [fleet-default/test-rke2-pool1-799222e1-4vtnz] of kind (HarvesterMachine) for machine test-rke2-pool1-76d4c44598-btzfj in infrastructure provider: CreateError: Downloading driver from https://k3scluster.localdomain/assets/docker-machine-driver-harvester Doing /etc/rancher/ssl docker-machine-driver-harvester docker-machine-driver-harvester: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped Trying to access option which does not exist THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR Type assertion did not go smoothly to string for key Running pre-create checks... Error with pre-create check: "invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable" The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag. 
```
while watching the Cluster Management -> Clusters (index) page.

#### Jobs in Highly Available K3OS Rancher Cluster
- from within the Jobs under the `fleet-default` namespace, during the provisioning loop we see:
```
┌─────────────────────────────────────────────────────────────────────────────────────────── Logs(fleet-default/test-rke2-pool1-799222e1-z98cb-machine-provision)[1m] ───────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                Autoscroll:On     FullScreen:Off     Timestamps:Off     Wrap:Off                                                                                                │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Downloading driver from https://k3scluster.localdomain/assets/docker-machine-driver-harvester                                                                                                           │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Doing /etc/rancher/ssl                                                                                                                                                                                  │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg docker-machine-driver-harvester                                                                                                                                                                         │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg docker-machine-driver-harvester: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), statically linked, stripped                                                                                       │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Trying to access option  which does not exist                                                                                                                                                           │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg THIS ***WILL*** CAUSE UNEXPECTED BEHAVIOR                                                                                                                                                               │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Type assertion did not go smoothly to string for key                                                                                                                                                    │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Running pre-create checks...                                                                                                                                                                            │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg Error with pre-create check: "invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"                                                            │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg The default lines below are for a sh/bash shell, you can specify the shell you're using, with the --shell flag.                                                                                         │
│ test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg                                                                                                                                                                                                         │
│ Stream closed EOF for fleet-default/test-rke2-pool1-799222e1-z98cb-machine-provision-72lqg (machine)                                                                                                                                                           │
```

#### Support Bundle:
- [supportbundle_39281acf-aaae-4d94-8bc4-c243480fc296_2022-07-28T18-14-13Z.zip](https://github.com/harvester/harvester/files/9213243/supportbundle_39281acf-aaae-4d94-8bc4-c243480fc296_2022-07-28T18-14-13Z.zip)

#### Additional Supporting Screenshots
![int-17-ext-cloud-credential-harvester](https://user-images.githubusercontent.com/5370752/181609486-018685b6-68ed-456e-9e09-f53e599e536a.png)
![int-17-manually-filling-out](https://user-images.githubusercontent.com/5370752/181609488-0596ac4d-aa6c-4684-967a-0b01d5013f02.png)

**Comment by yaocw2020** [comment]
The reason for this issue is clear now. Using the external cloud credential to create a guest cluster(rke1 or rke2) with the harvester cloud provider, Rancher frontend could not access the harvester kubeconfig generation API to get the cloud config. 
We will forbid harvester cloud provider for this case on the UI in the v1.0.3 release because the external cloud credential is still an experimental feature. If our users want to use harvester cloud provider with external cloud credential, they need to generate and place the cloud config to the cluster nodes manually. In the future, if it's a must requirement, we'll back to make it better. 
@guangbochen @TachunLin @n313893254 @irishgordo

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-032742f0-head` and Rancher `v2.6-28a74733d5a7bf24f114b4ad4daf84d663b6a683-head`. 

## Verification Steps
### Case 1 RKE2

1. Import Harvester from Rancher
2. Download Kubeconfig from Harvester support page
3. Copy the kubeconfig content
4. Open Cluster Management -> Cloud credential
5. Select Harvester
6. Check External Harvester
7. Copy the kubeconfig content
8. Provision a RKE2 cluster

### Expected Results
- RKE2 cluster provisions correctly

Passed

### Case 2 RKE1
1. Import Harvester from Rancher
2. Download Kubeconfig from Harvester support page
3. Copy the kubeconfig content
4. Open Cluster Management -> Cloud credential
5. Select Harvester
6. Check External Harvester
7. Copy the kubeconfig content
8. Provision a RKE1 cluster

### Expected Results
- RKE1 cluster provisions correctly

Failed

The VM starts provisioning and then deletes before going live. It just loops.
![Screenshot_20220916_124257](https://user-images.githubusercontent.com/83787952/190725640-a8b9f3c9-758f-4985-a487-d20963336c51.png)
![Screenshot_20220916_131710](https://user-images.githubusercontent.com/83787952/190725914-909b5c0c-7161-4f9d-8a6c-a04c4724c9cc.png)
![Screenshot_20220916_131656](https://user-images.githubusercontent.com/83787952/190725917-e4f5d799-6aab-4556-86b1-f27ec0e6d6af.png)
[supportbundle_8564fbde-3716-4bac-8050-f049dbf319e4_2022-09-16T19-43-38Z.zip](https://github.com/harvester/harvester/files/9587043/supportbundle_8564fbde-3716-4bac-8050-f049dbf319e4_2022-09-16T19-43-38Z.zip)

**Comment by n313893254** [comment]
Hi, @noahgildersleeve. Sorry I cannot reproduce this issue. Could you use the Rancher v2.6.9-rc1 and Harvester v1.1.0-rc1 test again?

**Comment by noahgildersleeve** [comment]
I retested this and could reproduce. However it seems to work with Ubuntu focal, but not opensuse Leap. For reference I was using `openSUSE-Leap-15.3.x86_64-1.0.1-NoCloud-Build2.46.qcow2`. Could you try checking with that @n313893254 . I double checked with Rancher v2.6.9-rc1 and the external ui-index pointed at the 2.6.9 ui. This was with `v1.1.0-rc1`.

**Comment by guangbochen** [comment]
Closing this issue, external cloud credential support will become deprecated in the next version 
 https://github.com/harvester/harvester/issues/3319.
