### ISSUE TITLE
[Question] vm volume cost too much space

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#2595]
## Vm running for a month
* volume setup 50G
* df shows 30% usage
* actual cost 105G physical disk space. (200% setup size.   700% data size)

![hv-volume-size](https://user-images.githubusercontent.com/987637/181679801-6d70aab9-3ae4-418e-987c-ad2e987da8c7.PNG)

### longhorn doc about volume size
* https://longhorn.io/docs/1.3.0/volumes-and-nodes/volume-size/

## question
* is there any hidden snapshot holding volume size?
* any good idea to speed up triggering longhorn pruning job? or manual way?

**Comment by bk201** [comment]
@fanlix Does the volume contain some snapshots?
You can click the volume and hover the mouse on snapshots to see their space usage.

**Comment by w13915984028** [comment]
LH has a good writing explaining the `volume size` and `actual size`, please take a look.

https://longhorn.io/docs/1.3.0/volumes-and-nodes/volume-size/

**Comment by fanlix** [comment]
@w13915984028 I'v read that link before post this issue.

* there is no snapshot by longhorn ui, (maybe some hidden snapshots)
* volume size keep growing

After many tries, there are 2 way may help:
* add-then-delete a snapshot by hand, trigger the longhorn gc task.
  * After 10min deleting. volume size drop down from 250% to 110%.
* backup the whole vm, restore the backup.
  * volume size drop down too.

**Comment by fanlix** [comment]
found a best solution.  
In longhorn webui, create a recuring job to the `default` group (which is added to every volume). 
* task=snapshot
* Retain=2 
* Cron=midnight 3:00

this job makes a snapshot everyday midnight, keeps totally 2 copies.
* longhorn gc the volume everyday midnight, remove useless data layers, avoid cost too much disk space for weeks.
* Only gc at midnight, avoid daytime random gc (caused by vm-user huge creating/deleting tasks)

This method decrease my host disk space usage by 40%. 
By watching disk io metrics chart in hv dashboard, almost all busy disk IO happens at midnight.
