### ISSUE TITLE
[BUG]Polish harvester machine config

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2598]
**Describe the bug**

https://github.com/harvester/dashboard/pull/391#pullrequestreview-1055169778

1. Namespace options of pod affinity should be in harvester cluster.

<img width="1673" alt="image" src="https://user-images.githubusercontent.com/24985926/181735326-c1562fc6-dd90-44ba-bae3-09fc572a9bb9.png">

2. If is a imported cluster, the namespaces field should be selectable.
4. The namespace is not updated when editing.

**To Reproduce**
#### Aspect of namespace options(_Both of RKE1 and RKE2_)
1. Go to create Harvester cluster
3. Add pod affinity
4. Options for namespaces are affiliated in management cluster

#### Aspect of the namespace field(_Both of RKE1 and RKE2_)
1. Go to create Harvester cluster
2. The Namespace filed of pod affinity is only inputable if the cluster is imported and the user logged in only has local owner role.

#### Aspect of namespace field updating
1. Go to create Harvester cluster
2. Add pod affinity with namespaces
3. Edit the cluster config is just created
5. Modify the namespaces of pod affinity
6. The namespaces of pod affinity cannot update.

**Expected behavior**

#### Aspect of namespace options
The options for namespaces should belong to harvester cluster.
#### Aspect of the namespace field
The namespace field should be selectable if the cluster is imported.
#### Aspect of namespace field updating
The namespace filed can update as expected.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified on Harvester `v1.0-60921953-head` with Rancher `v2.6.7-rc6`. 

### Result
Checked the following test plan for `RKE2` cluster are working as expected

- [x] Case 1: Available namespace options are affiliated with (the same as) what we show in the management cluster namespace list
  ![image](https://user-images.githubusercontent.com/29251855/182752411-b970a295-96d8-4576-a4db-d397953c7249.png)
  ![image](https://user-images.githubusercontent.com/29251855/182752437-733a7843-2f06-4a38-a810-5b9a42916f24.png)

- [x] Case 2 We can input the topology key in the Topology key field of the pod selector
![image](https://user-images.githubusercontent.com/29251855/182752496-1fa49c1d-1b93-4147-9d5b-ef3a56d5bd2b.png)

- [ ] Case 3 We can get the updated namespace list of cluster in the pod selector
![image](https://user-images.githubusercontent.com/29251855/182754019-b2aab60f-1060-49e2-8442-543195b805bc.png)

### Test Information
 - Harvester ISO version: `v1.0-60921953-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 nodes Harvester on local kvm machine
 - Rancher version: `v2.6.7-rc6`
 - Rancher dashboard-index: https://releases.rancher.com/dashboard/latest/index.html 
 - Rancher offline-preferred: Remote

### Verify Steps
1. Import Harvester from Rancher 
2. Create a standard user `local` in Rancher User & Authentication
3. Open Cluster Management page 
4. Edit cluster config 
![image](https://user-images.githubusercontent.com/29251855/182781682-5cdd3c6a-517b-4f61-980d-3ee3cab86745.png)
5. Expand Member Roles
6. Add `local` user with Cluster Owner role
![image](https://user-images.githubusercontent.com/29251855/182781823-b71ba504-6488-4581-b50d-17c333496b8c.png)
7. Create cloud credential of Harvester
8. Login with `local` user
9. Open the provisioning RKE2 cluster page 
10. Select Advanced settings
11. Add Pod Scheduling
12. Select `Pods in these namespaces`
13. Check the list of available pods with the namespaces options above
14. Check can input Topology key value 
15. Access Harvester UI (Not from Rancher)
16. Open project/namespace
17. Create several namespaces 
18. Login `local` user to Rancher 
19. Open the the provisioning RKE2 cluster page 
20. Check the available `Pods in these namespaces` list have been updated

**Comment by TachunLin** [comment]
We found when using local owner on the provision RKE1 cluster page.  
* We can't get the available namespace options in the Instance options section 
![image](https://user-images.githubusercontent.com/29251855/182796323-029d8713-f14b-4da2-8705-0d1acd1fc20c.png)

* And also no available options in the `Pods in these namespace` field of pod selector
![image](https://user-images.githubusercontent.com/29251855/182796919-df5a4f38-3ba7-424d-959b-41daae752e86.png)

Thus move this issue to implement for further investigation.

**Comment by DaiYuzeng** [comment]
> We found when using local owner on the provision RKE1 cluster page.
> 
> * We can't get the available namespace options in the Instance options section
>   ![image](https://user-images.githubusercontent.com/29251855/182796323-029d8713-f14b-4da2-8705-0d1acd1fc20c.png)
> * And also no available options in the `Pods in these namespace` field of pod selector
>   ![image](https://user-images.githubusercontent.com/29251855/182796919-df5a4f38-3ba7-424d-959b-41daae752e86.png)
> 
> Thus move this issue to implement for further investigation.


We will verify this issue on v1.1.0 since the [fixed PR](https://github.com/rancher/ui/pull/4882) will be merged on Rancher v2.7.0

#### There is a workaround

This issue can be resolved when the local owner also is harvester cluster member/owner then the node request won't block the namespace request.

**Comment by DaiYuzeng** [comment]
Hi @TachunLin ! Accroding to the discussions of Harvester UI team, `Pod Scheduling` is not applicable in harvester cluster config page and then it has been removed. Can you please verify this issue agian? Thanks!

**Comment by TachunLin** [comment]
Verified on Harvester `master-538d41fe-head` with Rancher `v2.6.7-rc7`. Close this issue. 

### Result
1. Currently the `Pod Scheduling` did not show on the RKE2 cluster config page
  ![image](https://user-images.githubusercontent.com/29251855/184342130-9291c640-ea49-4640-a8a8-575aa4484b72.png)
  
2. Also the `Pod Scheduling` did not show on the RKE1 template cluster config page 
  ![image](https://user-images.githubusercontent.com/29251855/184342202-61b3ee6f-d96d-4426-a106-343d329b1003.png)

### Test Information
 - Harvester ISO version: `master-538d41fe-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 nodes Harvester on local kvm machine
 - Rancher version: `v2.6.7-rc7`
 - Rancher ui-index: https://releases.rancher.com/ui/latest2/index.html
 - Rancher dashboard-index: https://releases.rancher.com/dashboard/latest/index.html 
 - Rancher offline-preferred: Remote

### Verify Steps
Follow the steps in https://github.com/harvester/harvester/issues/2598#issuecomment-1204903212
