### ISSUE TITLE
[Question] Is it not recommended to deploy directly to Harvester's kubernetes cluster?

### ISSUE THREAD

**Issue by radioflyer28** [harvester/harvester#2599]
Is it not recommended to deploy directly to Harvester's kubernetes cluster? I ask because Harvester already sets up a cluster that can be managed by kubectl and its existing Rancher install (see link below) before even bothering with a separate Rancher server. I'm on the learning curve of Kubernetes, so please set me straight.
https://[your cluster ip]/dashboard/c/local/explorer

The docs show a separate Rancher server integration as a more conventional setup. After experimenting with the Rancher integration, I do see that adds the benefit of choosing different kubernetes versions and networks and creating multiple clusters. 
https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

**Comment by futuretea** [comment]
Refer to https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#access-embedded-rancher
We only support to use the embedded Rancher dashboard for debugging and validation purpose

**Comment by cai648971528** [comment]
> 参考https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#access-embedded-rancher 我们仅支持使用嵌入式Rancher仪表板进行调试和验证

我们如果想在K8S集群内使用helm chart部署harvester，是否需要部署rancher？直接部署harvester会存在helmchartconfig资源，请问这个问题是什么原因？
