### ISSUE TITLE
windows server network with virtio support

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#260]
allow the user to configure windows server network with virtio support

**Comment by yaocw2020** [comment]
Virtio can be supported by updating driver in windows. The update steps are describe as follows.
- Open device manager, find other devices in warning state
![image](https://user-images.githubusercontent.com/7421463/100066223-c1a51080-2e6f-11eb-8119-a2aa532c8f8d.png)
- Choose one device, right click and choose「Update driver」
![image](https://user-images.githubusercontent.com/7421463/100067072-c4543580-2e70-11eb-95ee-3254ee976613.png)
- Choose 「Browse my computer for device software」and choose 「virtio-win-0.1.1」
![image](https://user-images.githubusercontent.com/7421463/100067479-4a707c00-2e71-11eb-936c-1baab37c71e5.png)
![image](https://user-images.githubusercontent.com/7421463/100067606-70961c00-2e71-11eb-9223-0e83da47ee48.png)
- Windows will find driver automatically, click 「install」to install driver and we will see driver is updated successfully.
![image](https://user-images.githubusercontent.com/7421463/100068025-ef8b5480-2e71-11eb-890f-cc2806d99c2d.png)
![image](https://user-images.githubusercontent.com/7421463/100068158-1ba6d580-2e72-11eb-9af6-77a51cc8c919.png)
- Update drivers of the rest of warning device except 「Unknown device 」

**Comment by futuretea** [comment]
Validated
