### ISSUE TITLE
[Question] how can i change args during installation.

### ISSUE THREAD

**Issue by esakarya** [harvester/harvester#2600]
I have a cluster running with RKE2.
I'm thinking of switching to Harvester...

In the RKE2 installation, I was able to make settings as follows from config.yaml.

```
kube-controller-manager-arg:
- "pod-eviction-timeout=30s"
- "node-monitor-period=2s"
- "node-monitor-grace-period=16s"
kubelet-arg:
- "node-status-update-frequency=4s"
- "system-reserved=cpu=100m,memory=200Mi"
- "kube-reserved=cpu=100m,memory=300Mi"
kube-apiserver-arg: 
- "default-not-ready-toleration-seconds=20"
- "default-unreachable-toleration-seconds=20"
disable:
 - traefik
 - servicelb
 - local-storage
disable-cloud-controller: true
```

In https://docs.harvesterhci.io/v1.0/install/harvester-configuration/ I couldn't find any information where to put similar settings.
**Can you give an example about this?
And how can I move my old RKE2 cluster to Harvaster?**

**Comment by bk201** [comment]
@esakarya You can create additional RKE2 config files in `/etc/rancher/rke2/config.yaml.d` after installation (and restart rke2-server or rke-agent). But we **don't** recommend modifying the RKE2 settings. The RKE2 runtime is dedicated to Harvester system services and VMS, it's not meant to be consumed as a normal Kubernetes workload directly.

If you plan to host Kubernetes workload, the supported approach is to provision guest clusters with VMs and use them. Please see https://docs.harvesterhci.io/v1.0/rancher/rancher-integration/

**Comment by w13915984028** [comment]
Close.

Please feel free to reopen when you have more questions, thanks.
