### ISSUE TITLE
[BUG] Disable Harvester cloud provider when the credential is external

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2605]
**Describe the bug**

Per this [comment](https://github.com/harvester/harvester/issues/2590#issuecomment-1200931573), disable the Harvester cloud provider when the credential is external. 

**To Reproduce**
1. Access Rancher and import a Harvester cluster
2. Create an external credential
3. Create a RKE1/RKE2 Harvester cluster

**Expected behavior**

The RKE2/RKE1 harvester cloud provider can not be selected, and the default selection is "none"

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
Move the issue to v1.1.0 since the CF date is passed on the upstream rancher repo.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-032742f0-head` and Rancher `v2.6-28a74733d5a7bf24f114b4ad4daf84d663b6a683-head`.

## Verification Steps
### Case 1 RKE1

1. Import Harvester from Rancher
2. Download Kubeconfig from Harvester support page
3. Copy the kubeconfig content
4. Open Cluster Management -> Cloud credential
5. Select Harvester
6. Check External Harvester
7. Copy the kubeconfig content
8. Create a RKE1 cluster
9. Add node template for RKE1
10. Verify that cloud provider is not a selectable option

### Expected results
- There should be no option for cloud provider
![Screenshot_20220916_101732](https://user-images.githubusercontent.com/83787952/190726481-88b3e644-cefe-42b9-90d9-1ea07f50f51f.png)

### Case 2 RKE2

1. Import Harvester from Rancher
2. Download Kubeconfig from Harvester support page
3. Copy the kubeconfig content
4. Open Cluster Management -> Cloud credential
5. Select Harvester
6. Check External Harvester
7. Copy the kubeconfig content
8. Create a RKE1 cluster
9. Verify that cloud provider is not a selectable option

### Expected results
- There should be no option for cloud provider
![Screenshot_20220915_171455](https://user-images.githubusercontent.com/83787952/190726606-e3167a08-5a27-4174-b8b0-8fd8d52cafe1.png)
