### ISSUE TITLE
windows server bridge vlan network support

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#261]
allow the user to config second NIC with bridge VLAN support in the Windows VM

**Comment by yaocw2020** [comment]
https://www.cni.dev/plugins/main/win-bridge/

**Comment by yaocw2020** [comment]
Drivers should be updated if using virtio mode. The update steps refer [here](https://github.com/rancher/harvester/issues/260).

**Comment by futuretea** [comment]
Validated
