### ISSUE TITLE
[BUG] Endpoint is still being required even if S3 Backup Type

### ISSUE THREAD

**Issue by grassbl8d** [harvester/harvester#2618]
**Describe the bug**

In the latest version of Harvester, when I choose the S3 as a backup source. The endpoint is mandatory although the documentation states that if S3 is the type then there it shouldn't be mandatory

**To Reproduce**

1. Go to Settings
2. Go to backup target
3. Choose Type as S3
4. Enter all details except endpoint and click on Save.

**Expected behavior**

The application should allow me to proceed even with no endpoint as long as the other required detials are supplied.

**Environment**
 - Harvester ISO version: 1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Beelink GR9

**Additional context**

When I use Chrome Tamper extension and remove the endpoint in the request body, the backup settings work. 

![image](https://user-images.githubusercontent.com/93050/182408931-d272dd4b-5791-45f5-87f7-4c418963e568.png)

![image](https://user-images.githubusercontent.com/93050/182409292-4aa85846-f74a-49fc-b74d-b62ae0346395.png)

**Comment by WuJun2016** [comment]
[UI change] 
* If the selected type is s3, the endpoint is not checked.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/186125774-784b39c1-49a4-4b87-9ef1-963d0a5dc170.png)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-dc6a3089-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2618#issue-1326005220
