### ISSUE TITLE
bump kubevirt and cdi version

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#262]
need to bump the kubevirt and CDI version to the current latest version
- bump kubevirt to v0.35.0
- bump CDI to v1.26.1

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/269

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/101450584-b8cf3700-3965-11eb-96d5-e4c466996cc0.png)
![image](https://user-images.githubusercontent.com/57614736/101450126-f8e1ea00-3964-11eb-8383-d15cb1ff138d.png)
