### ISSUE TITLE
[BUG] The backup data in cluster A fails to be used to restore VM in cluster B

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2621]
**Describe the bug**

The vm backup data may be shared by more than one harvester, so if the vm backup in cluster `A` goes to restore in cluster `B`, the restore operation will not succeed.

**To Reproduce**
1. Create two harvester clusters, A and B
2. Upload an image  in cluster A, create a vm (vm-a), then configure NFS and backup this vm (backup-a)
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/aa1dd86c-450a-4768-bf63-35666da0a5d5)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/68257d87-2d28-4bfa-932c-32c733af52a4)

3. Upload an image in cluster B, create a vm (vm-a), The vm name in cluster B is the same as in cluster A, then configure NFS（Note that NFS should be the same in both clusters）
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/a634ad53-b3e9-4d03-bab9-f7e83d506e99)

4. The backups created in cluster A are visible in cluster B.   （May need to wait a while）
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/c4197a59-d045-42d6-a577-7b37967932e9)

**Expected behavior**

There are several questions.
1. The backup(vm-a) displayed in cluster B at this time does not belong to the vm-a created in cluster B.  
Expected behavior:  At this point target-vm should not be able to link to vm-a in cluster b

2. Stop vm-a in cluster B, click on vm-a action menu, click on restore, You can see the option of backup-a in the drop-down list.
Expected behavior:   backup-a should not be shown because it is not part of this vm’s backup.
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/9f2d7304-2e64-47f9-875d-dbc2301abd85)

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.0.3-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
**Additional context**

**Comment by bk201** [comment]
Related: https://github.com/harvester/harvester/issues/2237

**Comment by WuJun2016** [comment]
duplicate ,  features are tracked in another issue https://github.com/harvester/harvester/issues/2237，  so close this issue.

**Comment by dseralathan** [comment]
on version v.1.1.1 issue is fixed ..
