### ISSUE TITLE
[BUG] Access Harvester project/namespace page hangs with no response timeout with local owner role from Rancher   

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2626]
**Describe the bug**

Create a standard user and grant local owner role in Rancher
When accessing project/namespace page in Harvester from Rancher virtualization management.
The namespace page will hang with no response timeout

https://user-images.githubusercontent.com/29251855/182780615-c93ce884-b719-4478-9836-6e77687a2f01.mov

![image](https://user-images.githubusercontent.com/29251855/182780804-066c9edf-38c1-451f-8151-5e81367d86ea.png)

**To Reproduce**
1. Import Harvester from Rancher 
2. Create a standard user `local` in Rancher User & Authentication
3. Open Cluster Management page 
4. Edit cluster config 
![image](https://user-images.githubusercontent.com/29251855/182781682-5cdd3c6a-517b-4f61-980d-3ee3cab86745.png)
5. Expand Member Roles
6. Add `local` user with Cluster Owner role
![image](https://user-images.githubusercontent.com/29251855/182781823-b71ba504-6488-4581-b50d-17c333496b8c.png)
7. Logout Admin 
8. Login with `local` user
9. Access Harvester from virtualization management 
10. Click the Project/Namespace page

**Expected behavior**

Local owner role user can access and display Harvester project/namespace place correctly without hanging to timeout

**Support bundle**

**Environment**
 - Harvester ISO version: `v1.0-60921953-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 nodes Harvester on local kvm machine
 - Rancher version: `v2.6.7-rc6`
 - Rancher dashboard-index: https://releases.rancher.com/dashboard/latest/index.html 
 - Rancher offline-preferred: Remote

**Additional context**
Admin user can display project/namespace page correctly

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Also tested on Rancher `v2.6.6`, didn't encounter this bug.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.0.3-rc2**
* **ui-source** Option: **Bundled**
* **ui-index** URL: **https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.0/index.html**
* **Rancher** Version: **v2.6-e9e88db363ae369bec044372cae8a36c66c042c9-head**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2626#issue-1328160313
