### ISSUE TITLE
A volume must be selected while adding a disk to a VM

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#263]
**Steps to reproduce:**
1. Edit a VM, add a disk, choose `Existing Volume` in the source dropdown
2. Not selecting any volume, then save
3. Edit the disk, select a volume
4. Then save the changes for VM
5. Edit the VM again and try to save it again

**Result:**
1. It makes no sense that the volume is not forced to select while adding an existing volume
2. The Access Mode is lost while users edit the disk
3. A disk which is missing access mode can be added to VM and saved, actually, the corresponding disk is not added to the VM by observing on UI
4. Moreover, when users edit the VM again and try to save the changes, it is not allowed to proceed, along with an error message
![image](https://user-images.githubusercontent.com/57614736/99754731-06edd900-2b24-11eb-93e5-e70a14a28b58.png)
![image](https://user-images.githubusercontent.com/57614736/99755177-10c40c00-2b25-11eb-947e-3090199a9ffa.png)

**Comment by DoNotSayYes** [comment]
The volume is still not forced to select when adding an existing volume? @WuJun2016 
![image](https://user-images.githubusercontent.com/57614736/101322196-983da900-38a1-11eb-8c2a-41033218df82.png)

**Comment by WuJun2016** [comment]
@DoNotSayYes  Please confirm whether it can be reproduced now？If you can, please tell me the steps to reproduce。

**Comment by DoNotSayYes** [comment]
Validated
