### ISSUE TITLE
[FEATURE] Sync image `display_name` to image labels

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2630]
**Is your feature request related to a problem? Please describe.**

For cli tools for Harvester, such as terraform-provider-harvester, when get image by `display_name`
need a quick get method rather than list all images

**Describe the solution you'd like**

add/update this label in vmimage controller `OnChange` 
add label selector to List method

**Describe alternatives you've considered**

**Additional context**

**Comment by futuretea** [comment]
For test:
check images name duplicate validation still works as excepted:
![image](https://user-images.githubusercontent.com/15064560/187172259-3ea6aaa0-4564-4c22-8b6d-c00d8ef73f37.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-69a6b1b2-head` (08/29). Close this issue.

### Feature description
Add image displayName to image's labels thus we can use labelSelector to get images when we needed

### Result
* In image API content, label `harvesterhci.io/imageDisplayName` added to labels, and it's value should be the displayName value
  ![image](https://user-images.githubusercontent.com/29251855/187353496-39c20027-f438-43de-a212-4f38b2dfbbae.png)
* Image with the same display name in label would be denied by admission webhook "validator.harvesterhci.io"
  ![image](https://user-images.githubusercontent.com/29251855/187354352-ea2f08f3-01a1-4088-899b-d92e25433781.png)
* Image with the same display name but different url would also be denied 
  ![image](https://user-images.githubusercontent.com/29251855/187355241-845b09b5-953b-4e90-9948-ca8b025a6f5d.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: `master-69a6b1b2-head` (08/29)

### Verify Steps
1. Login harvester dashboard
2. Access the Preference page
3. Enable developer tool 
  ![image](https://user-images.githubusercontent.com/29251855/187353113-495af11e-a3e5-4f8e-b03b-174b4f0660ea.png)
4. Create an ubuntu focal image from url  https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64.img
  ![image](https://user-images.githubusercontent.com/29251855/187353177-52516c6d-8e68-4ac5-8b40-4006f6460773.png)
5. View API of the created image 
  ![image](https://user-images.githubusercontent.com/29251855/187353338-1f0691f3-b19a-4382-a26f-ab5897842474.png)
6. Check can found the display name in the image API content 
7. Create the same ubuntu focal image from previous url again which would bring the same display name
8. Check would be denied with error message
9. Create a different ubuntu focal image with the same display name
