### ISSUE TITLE
[BUG] Hostname Given Via Remote Harvester Configuration Not Respected

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2632]
**Describe the bug**
The Hostname/hostname that is displayed/created is different from the hostname given via remote harvester configuration.

**To Reproduce**
1. Create a [Harvester Configuration that can be accessed remotely](https://docs.harvesterhci.io/v1.0/install/harvester-configuration/#configuration-example)
2. Enter a hostname (os.hostname)
3. Run the installer from the .iso file
4. Input a hostname when prompted
5. When reaching the screen for inputting a remote Harvester Configuration, provide your config URL.
6. Finish install, Harvester will reboot - you'll be able to see that both in Harvester Dashboard and Harvester Terminal User Interface UI that the `Hostname` is not the `hostname` given from the Harvester configuration

**Expected behavior**
Hostname would be over-written by a remote Harvester Configuration given - or - if not documentation updates to mention during the installation step when it prompts for a hostname to simply not input one if using a configuration.

**Support bundle**
- from the bare-metal: 
[supportbundle_3de3c3cc-e038-482d-8022-ebd20e69ed9e_2022-08-04T20-06-43Z.zip](https://github.com/harvester/harvester/files/9262970/supportbundle_3de3c3cc-e038-482d-8022-ebd20e69ed9e_2022-08-04T20-06-43Z.zip)
- from the video:
[supportbundle_6ca3a4c3-c883-488d-9f99-57c702f4292d_2022-08-04T20-10-09Z.zip](https://github.com/harvester/harvester/files/9262977/supportbundle_6ca3a4c3-c883-488d-9f99-57c702f4292d_2022-08-04T20-10-09Z.zip)
 

**Environment**
 - Harvester ISO version: v1.0.3-rc2
 - Underlying Infrastructure:
   - dell poweredge r720
   - qemu/kvm

**Additional context**
It looks like it does get parsed from JSON [here]lhttps://github.com/harvester/harvester-installer/blob/v1.0.3-rc2/pkg/config/config.go#L138) - but it doesn't seem to persist or override what initally gets put in.
Also looking at `sudo /oem/harvester.config` on the Node itself, the hostname is not the one provided from the configuration.

Configuration Example for the qemu/kvm install: 
- https://raw.githubusercontent.com/irishgordo/harvester-dell-config/main/new-harvester-demo-config.config

Configuration used for the bare-metal:
- https://raw.githubusercontent.com/irishgordo/harvester-dell-config/main/harvester.config

Video:
https://user-images.githubusercontent.com/5370752/182944026-ed59dd59-09bc-44e4-9672-53e37a1c72f0.mp4

![Screenshot from 2022-08-04 13-01-05](https://user-images.githubusercontent.com/5370752/182944212-49808c91-3476-41ef-8b8e-222f56186dbb.png)
![hostname](https://user-images.githubusercontent.com/5370752/182944215-263b6c71-b279-4cc5-b065-3685c21e4929.png)
![hostname-from-config-on-oem-harvester-config-not-there](https://user-images.githubusercontent.com/5370752/182944218-a8856d2b-3d67-4c8f-889c-2ecdec15d977.png)
![hostname-from-config-not-working](https://user-images.githubusercontent.com/5370752/182944219-f41f6d92-7e7c-4d81-beca-55f303aac785.png)
![maybe-wrap-config_url-since-you-cant-read-it-all](https://user-images.githubusercontent.com/5370752/182944220-8d173905-a7b2-447e-9f6b-8265b9c772f1.png)

**Comment by bk201** [comment]
The local-input configuration has a higher priority than the remote one. Code:
- https://github.com/harvester/harvester-installer/blob/2c953220773e78a0ec1f197d8b7956355f5e5f5b/pkg/console/install_panels.go#L1492
- https://github.com/harvester/harvester-installer/blob/2c953220773e78a0ec1f197d8b7956355f5e5f5b/pkg/config/config.go#L265

The initial thought was what a user input could be more important.
We need to discuss if we want the remote configuration to have higher priority. I guess this depends on the config field. For example, normally a user might not want the target installing disk and network configuration to be overridden. But for hostname, it should be OK.

**Comment by irishgordo** [comment]
Thanks for that info @bk201 !
I'll close this out as this is more of a design based decision and I agree that the user input can be more important than the remote Harvester Configuration file - having that flexibility to override some elements during install via entering/selecting values in the installation panels could come in handy for a lot of different use-cases.
I've created a PR in docs here:
https://github.com/harvester/docs/pull/187
To just add a small note to the documentation that mentions the Harvester Configuration file's priority.
