### ISSUE TITLE
[BUG] After configuring http-proxy, harvester is not accessible

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2633]
**Describe the bug**

http-proxy configure some wrong values, harvester will be inaccessible, the page appears 503 error

**To Reproduce**
1. Go to the http-proxy setting page
2. Set the values as follows,  click `Save` button.
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/204d378e-838d-4c94-9dc8-cad4ab45ecc3)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/992b8810-f136-4872-ae68-1423b6b5379c)

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.0.3-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
Changing this setting might cause a short downtime for single-node clusters.

https://docs.harvesterhci.io/v1.0/settings/settings/
![image](https://user-images.githubusercontent.com/15064560/182996270-ab2ccfbe-d64e-4395-96da-cc27b8faf5b3.png)

**Comment by WuJun2016** [comment]
This is as expected, so close the issue.
