### ISSUE TITLE
[Question] How can I access the Virtual Machines externally using noVNC ?

### ISSUE THREAD

**Issue by RicheyJang** [harvester/harvester#2636]
Hi everyone,

I'm developing a web application that uses Harvester as virtual machine management platform. I want to access the virtual machines through [novnc](https://github.com/novnc/noVNC) externally instead of Harvester UI, and I don't want to install a VNC server on every virtual machine.

How can I do this?

Thanks.

**Comment by futuretea** [comment]
@RicheyJang Maybe you can try this method: https://kubevirt.io/2019/Access-Virtual-Machines-graphic-console-using-noVNC.html
