### ISSUE TITLE
[BUG] Upgrade is stuck in "Pre-drained" state (Volume has too many system snapshots)

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2640]
**Describe the bug**

The upgrade is stuck and one node is in `pre-drained`.

<img width="454" alt="Screen Shot 2022-08-09 at 12 32 06 PM" src="https://user-images.githubusercontent.com/1691518/183588423-d0d84e3f-2210-4e15-bed0-fcfe99b78cac.png">

By looking Longhorn GUI, we know the node can't de drained due to it contain the last healthy replica:
<img width="1287" alt="Screen Shot 2022-08-08 at 5 42 23 PM" src="https://user-images.githubusercontent.com/1691518/183589182-a1acc14f-31f9-48dd-aaee-af27a1f27889.png">

The volume seem to have 249 system snapshots and can't continue the rebuilding process.
<img width="392" alt="Screen Shot 2022-08-08 at 6 17 48 PM" src="https://user-images.githubusercontent.com/1691518/183589230-10fb842c-bc94-4019-b7af-396349b5e85b.png">

Here is the file list to list replica directory on draining node:
https://gist.github.com/bk201/30a1ea0b250b04fa3da1f7e3147dfae0

**Workaround**
Delete the latest system snapshot:
<img width="648" alt="Screen Shot 2022-08-09 at 12 23 27 PM" src="https://user-images.githubusercontent.com/1691518/183590895-12a5af6f-121c-48bb-ab56-dd54ae4dd39a.png">

**To Reproduce**
1. Upgrade from Harvester v1.0.2 to v1.0.3-rc2.

**Expected behavior**

The upgrade should not be stuck.

**Support bundle**

[supportbundle_fef3afe2-169c-42e8-b98e-221821a50467_2022-08-09T07-21-58Z.zip](https://github.com/harvester/harvester/files/9288142/supportbundle_fef3afe2-169c-42e8-b98e-221821a50467_2022-08-09T07-21-58Z.zip)
Note: the support bundle is captured after applying workaround.

**Environment**
 - Harvester ISO version: v1.0.3-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare-metal servers

**Additional context**
The volume somehow was already in this state before performing the upgrade, we can have a check to prevent user from upgrading Harvester if there are abnormal volumes .

Related longhorn issue: ~~https://github.com/longhorn/longhorn/issues/2988~~
https://github.com/longhorn/longhorn/issues/3828

**Comment by bk201** [comment]
The fix https://github.com/longhorn/longhorn/issues/3828 is merged. Need to bump Longhorn to 1.3.3 or 1.4.0

**Comment by guangbochen** [comment]
in the Harvester v1.2.0-rc1, LH is already bumped to v1.4.2 , close as this is verified on https://github.com/longhorn/longhorn/issues/3828#issuecomment-1321512609
