### ISSUE TITLE
[FEATURE] add caveat for live migration

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2641]
### The problem
Live migration will fail if the VM having any volumes which is `CD-ROM` type.

### The solution
It is expected behavior that CD-ROM volume is read-only, so we should add caveat to let user know the behavior.
(Currently, dashboard will only display live migration failed without any advanced information)

### The Alternatives
- Add some checker on `migrate` function to ask user to eject CD-ROM before migration
- Improve the error message of live migration

**Comment by guangbochen** [comment]
Will need to add the following enhancement:
- improve the doc to add the above constraints to https://docs.harvesterhci.io/v1.1/vm/live-migration/#starting-a-migration
- add validation to the backend actions where applicable.

**Comment by irishgordo** [comment]
@w13915984028 - was this generally already validated with?

https://github.com/harvester/harvester/issues/3429
back in March?

**Comment by w13915984028** [comment]
@irishgordo You have validated this feature in https://github.com/harvester/harvester/issues/3429, and https://github.com/harvester/harvester/issues/3600 is for another enhancement.

Could we close this issue ? thanks.

**Comment by irishgordo** [comment]
Yes @w13915984028  - that sounds good to me :smile:  :+1:  - as this was validated w/ #3429 back in March - so we can close this out.
