### ISSUE TITLE
[FEATURE] Config Alertmanager in Dashboard

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2643]
**Is your feature request related to a problem? Please describe.**

The coming feature of `Alertmanager` will be configuable in Harvester dashboard.

**Describe the solution you'd like**

  Enable/disable Alertmanager.
  Adjust Alertmanager POD resources.
  Add/change/remove receiver.

It will be similar to:
https://docs.harvesterhci.io/v1.0/monitoring/monitoring/#from-webui

For multi receivers, if following `Rancher` feature could be imported to `Harvester`, that will be better. (Please UI team investigate)
https://rancher.com/docs/rancher/v2.6/en/monitoring-alerting/configuration/receiver/
Configuring Multiple Receivers
`It is also possible to send alerts to multiple notification systems. One way is to configure the Receiver using custom YAML, in which case you can add the configuration for multiple notification systems, as long as you are sure that both systems should receive the same messages.`

**Describe alternatives you've considered**

**Additional context**

EPIC:
https://github.com/harvester/harvester/issues/2517

HEP:
Document:
https://github.com/w13915984028/harvester/blob/fix2517/enhancements/20220720-alertmanager.md

PR:
https://github.com/harvester/harvester/pull/2545

**Comment by lanfon72** [comment]
Close as this has been verified along with #2521.
UI still need some enhancement described in #2798
