### ISSUE TITLE
[FEATURE] Logging is backed by PVC

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2645]
**Is your feature request related to a problem? Please describe.**

Logging data should be persistant in the cluster.

**Describe the solution you'd like**

Use PVC to store the data, PVC needs a proper initial size.

**Describe alternatives you've considered**

**Additional context**

EPIC:
https://github.com/harvester/harvester/issues/577

HEP DOC:
https://github.com/joshmeranda/harvester/blob/logging/enhancements/20220525-system-logging.md

update 2022.09.16: 
This feature is moved out from `v1.1.0`.

To persistant logging, user normally have dedicated logging servers. Meanwhile, Harvester may have limited storage, the logging PVC is difficult to set a proper size.

@joshmeranda

**Comment by w13915984028** [comment]
When local test and debugging, a LH issue is encountered and tracked in :

https://github.com/longhorn/longhorn/issues/4546

In single-node cluster, the workaround is to add a 1-replica storageclass for usage of `rancher-monitoring` etc.

**Comment by w13915984028** [comment]
update 2022.09.16:

This feature is moved out from v1.1.0.

To persistant logging, user normally have dedicated logging servers. Meanwhile, Harvester may have limited storage, the logging PVC is difficult to set a proper size.

**Comment by guangbochen** [comment]
@w13915984028 should we close this issue since currently logging is managed by the users? Users may refer to https://github.com/harvester/harvester/blob/master/enhancements/20220525-system-logging.md#viewing-logs-via-grafana-loki if they want to set up the logging system manually within the Harvester cluster.

**Comment by w13915984028** [comment]
@guangbochen I close it.

Not an requirement at the moment.
