### ISSUE TITLE
[FEATURE] Config logging in Harvester Dashboard

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2646]
**Is your feature request related to a problem? Please describe.**

The logging feature is configurable in Harvester Dashboard.

**Describe the solution you'd like**

Configure Harvester logging:
```
  fluentbit, fluentd POD memory, CPU resources.
  cluster & namespace leve flows and ouputs:
```

Please UI team investigate following Rancher feature, when reusing the YAML input feature is possilbe, that will be great.

https://rancher.com/docs/rancher/v2.5/en/logging/custom-resource-config/flows/
https://rancher.com/docs/rancher/v2.5/en/logging/custom-resource-config/outputs/

**Describe alternatives you've considered**

**Additional context**

EPIC:
https://github.com/harvester/harvester/issues/577

HEP DOC:
https://github.com/joshmeranda/harvester/blob/logging/enhancements/20220525-system-logging.md

**Comment by w13915984028** [comment]
@WuJun2016 @joshmeranda @guangbochen

**Comment by DaiYuzeng** [comment]
Hello @w13915984028 ! Can you please complement the checklist? Thanks! (#2749, #2643 also need to be complemented)

**Comment by w13915984028** [comment]
FOR TEST:

In v1.1.0, test `logging/event/audit` output type of: Graylog, Splunk, they are required by customers;  
webhook server is for quick validation.

Set output manually :
How to send log to graylog:
https://github.com/w13915984028/harvester-develop-summary/blob/main/integrate-harvester-logging-with-log-servers.md

Test logging, audit, event with webhook server
https://github.com/w13915984028/harvester-develop-summary/blob/main/test-log-event-audit-with-webhook-server.md


Set output in UI:
https://github.com/harvester/harvester/issues/2646
[FEATURE] Config logging in Harvester Dashboard

https://github.com/harvester/harvester/issues/2749
[FEATURE] Harvester UI support config (cluster) flow & output for kube-audit log and event log

**Comment by DaiYuzeng** [comment]
The PR from GUI side had been merged so I moved this issue to the `Ready For Testing` panel.
If you have any concerns, just ping me, thank you! @w13915984028 @WuJun2016

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/191697822-6bc0d7b8-2c56-42e0-805a-408c1ef19845.png)
![image](https://user-images.githubusercontent.com/5169694/191697860-7ef66c19-cd3e-4e4c-b485-315e7eec771d.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-250f41e4-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to _Monitoring & Logging/Logging_
3. Configurations of Fluentbit and Fluentd should be available in _Logging/Configuration_
