### ISSUE TITLE
[FEATURE] Collect system logs

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2647]
**Is your feature request related to a problem? Please describe.**

Collect system level log.
It should be possible to collect log from given path.
Avoid duplicated logs from same path.

**Describe the solution you'd like**

Collect 
following UNITs of journal: `rke2-server.service, rke2-agent.service, rancherd.service,rancher-system-agent.service, wicked.service, iscsid.service`
`kernel message`
`/var/lib/rancher/rke2/agent/logs/kubelet.log`
`/var/log/audit/audit.log`

**Describe alternatives you've considered**

**Additional context**

EPIC:
https://github.com/harvester/harvester/issues/577

HEP DOC:
https://github.com/joshmeranda/harvester/blob/logging/enhancements/20220525-system-logging.md

**Comment by w13915984028** [comment]
FOR TEST:

In v1.1.0, test `logging/event/audit` output type of: Graylog, Splunk, they are required by customers;  
webhook server is for quick validation.

Set output manually :
How to send log to graylog:
https://github.com/w13915984028/harvester-develop-summary/blob/main/integrate-harvester-logging-with-log-servers.md

Test logging, audit, event with webhook server
https://github.com/w13915984028/harvester-develop-summary/blob/main/test-log-event-audit-with-webhook-server.md


Set output in UI:
https://github.com/harvester/harvester/issues/2646
[FEATURE] Config logging in Harvester Dashboard

https://github.com/harvester/harvester/issues/2749
[FEATURE] Harvester UI support config (cluster) flow & output for kube-audit log and event log

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-250f41e4-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install _Graylog_ via docker[^1]
2. Install Harvester with any nodes
3. Login to Dashboard then navigate to _Monitoring & Logging/Logging_
4. Create **Cluster Output** with following:
    - **Name**: gelf-evts
    - **Type**: `Logging/Event`
    - **Output**: GELF
    - **Target**: `<Graylog_IP>, <Graylog_Port>, <UDP>`
5. Create **Cluster Flow** with following:
    - **Name**: gelf-flow
    - **Type** of Matches: `Logging`
    - **Cluster Outputs**: `gelf-evts`
6. Create an Image for VM creation
7. Create a vm `vm1` and start it
8. Login to `Graylog` dashboard then navigate to search
9. Select update frequency
![image](https://user-images.githubusercontent.com/5169694/191725169-d1203674-13d8-487b-9fa2-e1d9394fa5c0.png)
10. New logs should be posted continuously.


### code snippets to setup Graylog
```bash
docker run --name mongo -d mongo:4.2.22-rc0
sysctl -w vm.max_map_count=262145
docker run --name elasticsearch -p 9200:9200 -p 9300:9300 -e xpack.security.enabled=false  -e node.name=es01 -it docker.elastic.co/elasticsearch/elasticsearch:6.8.23
docker run --name graylog --link mongo --link elasticsearch -p 9000:9000 -p 12201:12201 -p 1514:1514 -p 5555:5555 -p 12202:12202 -p 12202:12202/udp -e GRAYLOG_PASSWORD_SECRET="Graypass3WordMor!e" -e GRAYLOG_ROOT_PASSWORD_SHA2=899e9793de44cbb14f48b4fce810de122093d03705c0971752a5c15b0fa1ae03   -e GRAYLOG_HTTP_EXTERNAL_URI="http://127.0.0.1:9000/"  -d graylog/graylog:4.3.5
```
- Login to _Graylog_ dashboard by the URL `http://<server_ip>:9000/` with `admin`/`ROOT_PASSWORDa1`
- Navigate to _System/Inputs_ then select input **GELF UDP**, update the port to `12202`
![image](https://user-images.githubusercontent.com/5169694/191723749-7d796243-5996-4884-90b4-d8227f81adc5.png)
