### ISSUE TITLE
[FEATURE] Harvester UI plugin

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2654]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher/dashboard/issues/4109
 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
#### Test plan 
1. Regression test of Rancher `v2.6.9-rc2` integrate with Harvester `v1.1.0-rc1`
  - Access Harvester cluster from Rancher 
  - RBAC related Harvester permission on Harvester 
 
2. Regression test of Rancher `v2.6.9-rc2` integrate with Harvester `v1.0.3`
  -  Access Harvester cluster from Rancher 
  - RBAC related Harvester permission on Harvester 

Test plan stated in https://harvester.github.io/tests/manual/harvester-rancher/

**Comment by lanfon72** [comment]
Both test plan should be verified in Rancher `v2.6.9-rc2`, so this issue still pending on Rancher's docker image release

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

https://user-images.githubusercontent.com/5169694/192982019-616e6e23-281a-4e93-a018-f6fc3ed5840e.mp4


Test Information
----
* Environment: **baremetal DL360G9 4 nodes** and **qemu/KVM 2 nodes**
* Harvester Version: **master-7dd398f0-head** and **v1.0.3**
* **ui-source** Option: **External** and **Bundled**
* **Rancher** Version: **v2.6.9-rc2**
* **Rancher** _ui-offline-preferred_: **Dynamic**

### Verify Steps:
1. Install Rancher `v2.6.9-rc2`
2. Navigate to _Virtualization Management_, Import Existing Harvester
3. Harvester should imported successfully
4. Access Harvester by Rancher's _Virtualization Management_
5. Harvester's dashboard pages should display correctly
6. Create an image for VM then create a VM from it
7. Page's state (viewing from Rancher) should synced with Harvester Dashboard
