### ISSUE TITLE
[Question] How to use harvester's CSI and CNI inside the VM's

### ISSUE THREAD

**Issue by migs35323** [harvester/harvester#2658]
All the documentation that i can find uses rancher. I am trying to setup a cluster in harvester's VMs
So, in a normal k8s created with kubeadm init inside harvester, how can i use the network plugins and storage class provided from harvester?

**Comment by FrankYang0529** [comment]
Hi @migs35323, thanks for filing the question.

1. For both [harvester-csi-driver](https://github.com/harvester/harvester-csi-driver) and [cloud-provider-harvester](https://github.com/harvester/cloud-provider-harvester), you can find `generate_addon.sh` script under `deploy` folder. Run it with Harvester kubeconfig to generate a new service account and kubeconfig.
2. Move generated kubeconfig to guest cluster's folder `/etc/kubernetes/cloud-config`.
3. You can install them by helm. Their charts are in [harvester/charts](https://github.com/harvester/charts).
4. For harvester-csi-driver, remember to change [cloudConfig.hostPath](https://github.com/harvester/charts/blob/5449938d02bf8e32c45b0bf9ff4f76ba279fae81/charts/harvester-csi-driver/values.yaml#L31) to `/etc/kubernetes/cloud-config`.
