### ISSUE TITLE
[Question] How do you correct disk warnings on hosts?  

### ISSUE THREAD

**Issue by BringerOD** [harvester/harvester#2660]
Warning Message
**"the disk xxx has xxx available, but requires reserved xxx, minimal 25% to schedule more replicas. "**

![image](https://user-images.githubusercontent.com/7971305/184274941-5e55673d-3889-42fe-a4a3-3a814175de67.png)

Just not sure exactly what to do with this warning message.

What causes this warning?  Is it just to much allocated?  If so,  can I tell the system to reduce what that drive can take?

**Comment by BringerOD** [comment]
Follow up,  the message is now gone.   Which is good.  I did not do anything to remove it.

My concern is still there though.  

What happens if it comes back and do I have something miss configured.


![image](https://user-images.githubusercontent.com/7971305/184385752-3bd78699-b94d-4482-9725-a560111b90ae.png)

**Comment by Vicente-Cheng** [comment]
Hi @BringerOD, 

Sorry for the late update. For your questions.
I thought the original warning message tips users to know that the disk is on low capability.
(we need to keep some space for replication due to thin-provision design)

For the second picture, Longhorn (Harvester volume backend) has some mechanism to release the disk space by cleaning up the system snapshot, orphaned data, or backing image  I am not sure how your system status (like pods, nodes status) but release some disk space is respectable.

Hope the above information would be helpful for you :)

**Comment by BringerOD** [comment]
Thanks for the response!  

One of the issues I have is I have 4x900GB drives each separately provisioned.  I am not sure how longhorm\harvester decides where data goes,  and why it would chose one drive over the other.  

Reading through some of the docs,  I think it suggested I combine all the drives.  Is that true?

Do you have any suggestions on how to configure the drives in this scenario?  Are there any docs on what the best practices are?

**Comment by Martin-Weiss** [comment]
The logic how do distribute the data between drives is based on the logic Longhorn has implemented.

In case I understand this right - the data distribution should be more or less „automatic“ and Longhorn could even be configured to re-distribute data automatically.

Combining the disks would be possible in case you have a raid controller in the server - then you could i.e. build a RAID 5 out of the disks and present only one drive.. but yes - this would reduce capacity.. an other option (maybe complex to be done with Harvester) would be to combine the drives in a LVM VG - but that would also have a potential single point of failure in case one of the disk fails.

So - for the time being - do you still see a problem with one disk running out of available disk space?

P.S. Longhorn does not support sharding - so having very large volumes also can cause a challenge in case a single disk does not have enough capacity left and that might also cause not all disks having the same usage - see also https://github.com/longhorn/longhorn/issues/1061

**Comment by BringerOD** [comment]
@Martin-Weiss thanks for your help here.  Is there a guide on how to combine the disks.  It makes sense to combine the drives,  especially if it has a replica.  

Do you combine the drives before you install harvester?  Or can you combine them after it is installed.  I am not that great at disk management on linux.  Conceptually I get it,  but do it is anther thing.  

The problem I had today was I had a 500gb volume and it failed.  It was 800gb + on disk,  and there was not space left.  The replicas failed.  Lost the whole volumne.  I have to find a solution to it.

My plan was to restore,  but restore is not working either.

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss thanks for your help here. Is there a guide on how to combine the disks. It makes sense to combine the drives, especially if it has a replica.
> 

I prefer "combining" disks with a hardware based RAID controller.

> Do you combine the drives before you install harvester? 

Yes

>Or can you combine them after it is installed. I am not that great at disk management on linux. Conceptually I get it, but do it is anther thing.

I am pretty sure we do not support "combining" disks i.e. via LVM or MDRAID on Harvester.

> 
> The problem I had today was I had a 500gb volume and it failed. It was 800gb + on disk, and there was not space left. The replicas failed. Lost the whole volumne. I have to find a solution to it.
> 

It is possible to reduce the "reserved" space and to allow overprovisioning as a workaround but for production usage I would not want to do that.. 

> My plan was to restore, but restore is not working either.

In case there is not sufficient disk space - the only chance I see is to add more / bigger disks.
