### ISSUE TITLE
[BUG] VM label names should be consistent before and after the restore task is done

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#2662]
**Describe the bug**

There's a label in the VirtualMachine resource called `harvesterhci.io/vmName`, which will propagate to the respective launcher Pod `virt-laucher-xxxxx`. Backing up a VM and restoring a new VM with the backup causes the label name to change from `harvesterhci.io/vmName` to `harvesterhci.io/vm-name`, which is inconsistent behavior.

VM before restore:
<img width="731" alt="Screen Shot 2022-08-11 at 15 16 49" src="https://user-images.githubusercontent.com/1827717/184329408-f3d9df93-e4b7-42e6-b58a-9a762dc8434f.png">

VM after restore:
<img width="958" alt="Screen Shot 2022-08-11 at 16 01 25" src="https://user-images.githubusercontent.com/1827717/184329454-0c8e297e-9e02-4136-a8c2-6165df219f30.png">

**To Reproduce**

1. Create one VM (use defaults)
2. Make sure that the label name is `harvesterhci.io/vmName` by checking its YAML
3. Wait for the VM to fully boot up then take a backup
4. After the backup task is done, delete the VM
5. Restore a new VM with the same name using the newly created backup (This is just for the sake of highlighting the inconsistency. Using a different name will still cause the problem. The name of the VM is not the point.)
6. After the restore task is completed, check its YAML for the label name, it should be changed to `harvesterhci.io/vm-name`

**Expected behavior**

The label name should be consistent before and after the backup/restore, i.e. `harvesterhci.io/vmName`.

**Support bundle**

**Environment**

- Harvester ISO version: v1.0.2
- Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal (Supermicro X10DRL-i/Intel Xeon E5-2680 v4/64GB RAM)

**Additional context**

I was creating a Service resource with `harvesterhci.io/vmName` label on the Harvester node for preventing the application endpoint from changing across VM reboots. However, the application endpoint is no longer reachable after I restored a new VM from the backup. The application running on the VM functions normally and the listening port is opened on all interfaces. I can reach the application endpoint from another VM directly using that VM's IP address, so the problem is not on the application side. After checking the Service and Endpoint resources, I found that the endpoints are gone, which means the Service cannot associate with the corresponding Pod I specified using labels. I checked the labels on the launcher Pod and realized that the respective label name was changed to `harvesterhci.io/vm-name` after the restoration.

Workaround: Manually editing the label name and restarting the VM solves my issue. But still, the label name should be consistent at the beginning.

**Comment by starbops** [comment]
Is there any potential impact on the UI regarding changing `harvesterhci.io/vm-name` to `harvesterhci.io/vmName`? cc @WuJun2016 Thanks!

**Comment by WuJun2016** [comment]
> Is there any potential impact on the UI regarding changing `harvesterhci.io/vm-name` to `harvesterhci.io/vmName`? cc @WuJun2016 Thanks!


@starbops  There is no impact, I think the backend should keep the label consistent when restoring via backup.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-caada0e6-head` (09/05). Close this issue.

### Result
The vm lable name is consistent to display `harvesterhci.io/vmName` after restore from the backup.


* When created a new VM, the vm label name marked with `harvesterhci.io/vmName`
![image](https://user-images.githubusercontent.com/29251855/188374691-b36db1bc-2e2e-447b-96e1-699aa5e0ffee.png)

* After new VM restored from backup with the same name, the vm label name still marked with `harvesterhci.io/vmName`
![image](https://user-images.githubusercontent.com/29251855/188379642-a699f0ba-5731-41ae-be18-de5603744b8c.png)

### Test Information
* Test Environment: 4 nodes harvester on dolphin bare machine
* Harvester version: `master-caada0e6-head` (09/05).

### Verify Steps
1. Create a VM named `ubuntu`
2. Check the label name in virtual machine yaml content, label marked with `harvesterhci.io/vmName`
  ![image](https://user-images.githubusercontent.com/29251855/188374691-b36db1bc-2e2e-447b-96e1-699aa5e0ffee.png)
3. Setup the S3 backup target 
4. Take a S3 backup with name 
5. After the backup task is done, delete the current VM
6. Restore VM from the backup with the same name `ubuntu` (Create New)
  ![image](https://user-images.githubusercontent.com/29251855/188378123-9af171af-c992-4e78-bdbb-8627903502ff.png)
7. Check the yaml content after VM fully operated
