### ISSUE TITLE
[FEATURE] Boot harvester live iso without launcing harvester-installler

### ISSUE THREAD

**Issue by hernad** [harvester/harvester#2663]
**Problem**

I regularly starting harvester-live configuration on an node for debugging and inspecting purposes. 

This is extract from my ipxe configuration
<pre>
:harvester_live
kernel ${http_harvester}/harvester${harvester_release}-vmlinuz-amd64 ${k_cmd} ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl root=live:${http_harvester}/harvester${harvester_release}-rootfs-amd64.squashfs
initrd ${http_harvester}/harvester${harvester_release}-initrd-amd64
boot
</pre>

The problem is it always launches harvester-installer, which we don't want in that scenario.

**Solution**

The solution that satisfies me is additional kernel parameter which prevents harvester-installer start:

<pre>
harvester.setupinstaller=false
 </pre>

I have implemented that with this commit:

https://github.com/hernad/harvester-installer/commit/abbdd359eebbc33ed9de746123a1a71d4d27d9f9

**Comment by hernad** [comment]
Additional commit to fix yaml:

https://github.com/hernad/harvester-installer/commit/56e0829c0a043ae6a029283f139820a28091519c

**Comment by yasker** [comment]
Hi @hernad 

Can you elaborate on the use for preventing harvester-installer to start? You can still jump to the console quickly using `Alt-F2` I remember.

**Comment by bk201** [comment]
@hernad Do you still need the feature and could you submit a PR? As Sheng mentioned, [switching to another TTY](https://docs.harvesterhci.io/v1.1/troubleshooting/installation#logging-into-the-harvester-installer-a-live-os) does the trick too.

> Additional commit to fix yaml:
> 
> [hernad/harvester-installer@56e0829](https://github.com/hernad/harvester-installer/commit/56e0829c0a043ae6a029283f139820a28091519c)

**Comment by hernad** [comment]
@bk201 I am running harvester live via iPXE and remote IPMI console. Switch to another TTY console doesn't work for me in that scenario. This patch have provided me login to system.
Anyway, if this is not generally useful to others, close feature request.

**Comment by irishgordo** [comment]
@Vicente-Cheng thanks for this feature! :raised_hands: 
 
Following the test steps highlighted on https://github.com/harvester/harvester-installer/pull/428 - This looks good :smile: 

Tested on Harvester Version: **master-f93d67e1-head** (02/22/23 master-head).  I'll go ahead in close this out.  Testing artifact video attached :smile: 

https://user-images.githubusercontent.com/5370752/220797792-16c91086-71c6-41f5-b6f5-95010bfe20e1.mp4
