### ISSUE TITLE
[FEATURE] Generate and upload code coverage report for integration tests

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2666]
**Is your feature request related to a problem? Please describe.**

https://github.com/harvester/harvester/pull/2637#discussion_r944305074

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

https://onsi.github.io/ginkgo/#computing-coverage
https://github.com/onsi/ginkgo/issues/990

**Comment by guangbochen** [comment]
may continue the investigation after bump golang v1.20 with https://go.dev/blog/integration-test-coverage support

**Comment by bk201** [comment]
@lanfon72 can you help turn on this in the daily e2e test pipeline?

**Comment by lanfon72** [comment]
> @lanfon72 can you help turn on this in the daily e2e test pipeline?

@bk201, the PR https://github.com/harvester/harvester-baremetal-ansible/pull/10 not ready yet.  @FrankYang0529

**Comment by FrankYang0529** [comment]
The Coverage Report is added to pipeline. Close the issue.

<img width="1288" alt="Screenshot 2024-03-08 at 5 01 10 PM" src="https://github.com/harvester/harvester/assets/4927361/e17aa0c6-9bad-4a86-ae48-449722a057fd">
