### ISSUE TITLE
Automate VMs template creation

### ISSUE THREAD

**Issue by kingnarmer** [harvester/harvester#2667]
I have harvester cluster running 1.0.3. I can create template and deploy VM from gui. I am looking for guidance on how to  automate VM template creation with company customization. End goal is to automate VMs template creation and VMs deployment.  ,

Right now , I use packer to create template on vmware and run commands to customize template before saving it. 

I am looking for guidance on how to accomplish this on Harvester.

Thanks

**Comment by FrankYang0529** [comment]
Hi @true64gurus, what do mean about the template here? Do you mean the template to create VM on the harvester?

![Screen Shot 2022-08-17 at 2 30 45 PM](https://user-images.githubusercontent.com/4927361/185050236-555001d5-bc81-44af-a15c-176e990217c3.png)

**Comment by kingnarmer** [comment]
@FrankYang0529  Thanks for response. Yes, I am looking for guidance on how to automate VM template creation. I can create simple template from GUI.

**Comment by FrankYang0529** [comment]
@true64gurus if we have a `harvester_template` resource in the harvester terraform provider, will it be helpful to you?

https://registry.terraform.io/providers/harvester/harvester/latest/docs

**Comment by kingnarmer** [comment]
@FrankYang0529 Sure , that actually will work better.

**Comment by kingnarmer** [comment]
@FrankYang0529  one other suggestion is to add "mount point" option to secondary disk on template .

Something like 

```
disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = harvester_image.ubuntu20.id
    auto_delete = true
  }

  disk {
    name        = "emptydisk"
    type        = "disk"
    size        = "20Gi"
    bus         = "virtio"
    mount     = "/var/lib/docker"
    auto_delete = true
  }

```
