### ISSUE TITLE
[FEATURE] Harvester logging supports sending log to Graylog via UDP based syslog

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2669]
**Is your feature request related to a problem? Please describe.**

Harvester logging supports send log to Graylod via udp based syslog

**Describe the solution you'd like**

The logging center in cluster sends log to different log server via related plugin.

**Describe alternatives you've considered**

**Additional context**

The integration with Graylog is summarized in

https://github.com/w13915984028/harvester-develop-summary/blob/main/integrate-harvester-logging-with-log-servers.md

EPIC:
https://github.com/harvester/harvester/issues/577

HEP DOC:
https://github.com/joshmeranda/harvester/blob/logging/enhancements/20220525-system-logging.md

**Comment by w13915984028** [comment]
About TEST:

WAIT unti  https://github.com/harvester/harvester-installer/pull/331  is merged.

Manual test is ready:  (use `kubectl` to create `flow`, `receiver`)
refer: https://github.com/w13915984028/harvester-develop-summary/blob/main/integrate-harvester-logging-with-log-servers.md

UI based test,  ((use `Harvester UI' to create `flow`, `receiver`)
wait: https://github.com/harvester/harvester/issues/2646

**Comment by w13915984028** [comment]
FOR TEST:

In v1.1.0, test `logging/event/audit` output type of: Graylog, Splunk, they are required by customers;  
webhook server is for quick validation.

Set output manually :
How to send log to graylog:
https://github.com/w13915984028/harvester-develop-summary/blob/main/integrate-harvester-logging-with-log-servers.md

Test logging, audit, event with webhook server
https://github.com/w13915984028/harvester-develop-summary/blob/main/test-log-event-audit-with-webhook-server.md


Set output in UI:
https://github.com/harvester/harvester/issues/2646
[FEATURE] Config logging in Harvester Dashboard

https://github.com/harvester/harvester/issues/2749
[FEATURE] Harvester UI support config (cluster) flow & output for kube-audit log and event log

**Comment by lanfon72** [comment]
Closed as verified along with #2647, #2747, #2748
