### ISSUE TITLE
CRD version deprecated warnings in helm deployment

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#267]
**Harvester version:**
Chart on master(4c23af8)

**Helm version:**
v3.4.1

**kubernetes version**
v1.19.3+k3s3

**Steps to reproduce:**
Deploy the harvester chart to the Kubernetes cluster, and get a bunch of warnings printed:
```
W1124 10:49:41.174497   31308 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1124 10:49:41.364780   31308 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
W1124 10:49:41.549079   31308 warnings.go:67] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
...
```

Related to the generated CRD [version](https://github.com/rancher/harvester/blob/4c23af8bf032693ac1886c6ec2240d55fe37b479/deploy/charts/harvester/crds/harvester.cattle.io_keypairs.yaml#L3).

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/269

**Comment by DoNotSayYes** [comment]
Validated
