### ISSUE TITLE
[TASK] Publish `rancher/harvester-cluster-repo` image

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2670]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
The image `rancher/harvester-cluster-repo` is built on the installer side and shipped in the package tarball.
We need to publish the image to the docker hub as well, sometimes it's easier to debug.

**Describe alternatives you've considered**

**Additional context**

**Comment by RegisWeduLabs** [comment]
Will probably make remote install (IPMI) quicker too?

**Comment by bk201** [comment]
Close the issue since we publish the image: https://hub.docker.com/r/rancher/harvester-cluster-repo/tags
