### ISSUE TITLE
[BUG] Failed to resize Harvester persistent volume in Rancher PersistentVolume page of RKE2 cluster

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2672]
**Describe the bug**

Unable to resize the Harvester persistent volume created with nginx deployment.  
![image](https://user-images.githubusercontent.com/29251855/185100482-9c59034e-1900-4dc4-a2cf-aa8784cde187.png)

It prompt error message
```
PersistentVolume "pvc-debb3311-9d20-4a59-96b4-0e29d962d7fb" is invalid: [spec.csi.controllerPublishSecretRef.name: Required value, spec.csi.controllerPublishSecretRef.namespace: Required value, spec.csi.controllerExpandSecretRef.name: Required value, spec.csi.controllerExpandSecretRef.namespace: Required value, spec.csi.nodePublishSecretRef.name: Required value, spec.csi.nodePublishSecretRef.namespace: Required value, spec.persistentvolumesource: Forbidden: spec.persistentvolumesource is immutable after creation
  core.PersistentVolumeSource{
   ... // 19 identical fields
   Local: nil,
   StorageOS: nil,
   CSI: &core.CSIPersistentVolumeSource{
   ... // 3 identical fields
   FSType: "ext4",
   VolumeAttributes: {"storage.kubernetes.io/csiProvisionerIdentity": "1660724401239-8081-driver.harvesterhci.io"},
-  ControllerPublishSecretRef: nil,
+  ControllerPublishSecretRef: &core.SecretReference{},
-  NodeStageSecretRef: nil,
+  NodeStageSecretRef: &core.SecretReference{},
-  NodePublishSecretRef: nil,
+  NodePublishSecretRef: &core.SecretReference{},
   ControllerExpandSecretRef: nil,
   },
  }
]
```

**To Reproduce**
1. Provision an Harvester RKE2 guest cluster from Rancher 
2. Wait for guest cluster ready
3. Open Workload -> Deployments 
4. Create a `nginx` deployment 
5. Create Persistent Volume Claim
6. Select Harvester as storage class
7. Select `Single-Node Read/Write` mode 
8. Add `/test` to mount point
9. Wait for nginx deployment ready
10. Open Storage -> PersistentVolumes page
11. Edit the created Harveter PV
12. Change the capacity value 
13. Click save button

**Expected behavior**

Should be able to change the capacity of Harvester persistent volume

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node Harvester on local kvm machine
 - Rancher version: v2.6.7-rc9
 - cloud provider chart version: harvester-csi-driver:0.1.1100

**Additional context**
Can resize volume from Harvester dashboard

**Comment by FrankYang0529** [comment]
I think the correct way to resize volume in the guest cluster is to update PVC. Following is a result I got when I tried to resize the PVC.

![Screen Shot 2022-08-18 at 11 58 23 AM](https://user-images.githubusercontent.com/4927361/185290648-cda58694-3b11-4354-a7fb-5d32f06db0e1.png)
![Screen Shot 2022-08-18 at 11 58 53 AM](https://user-images.githubusercontent.com/4927361/185290659-7d3aebcb-9f71-48ee-ae83-20eb2db7f364.png)

**Comment by TachunLin** [comment]
As @FrankYang0529 mentioned, currently we only support resizing PVC in the following way. 
1. Deattach the PVC from existing service then edit PVC to change request storage size
2. Edit a stand alone PVC and change its size   

The capacity of PV will be changed accordingly after we modify the PV 
This would be the correct and supported way to resize volume in the guest cluster
Thus close this issue. 

#### Steps to resize Harvester PV volume
1. Delete the nginx service in Workload -> Deployments (Deattach)
2. Edit the PVC 
3. Change the request storage size 
4. Wait for a short time 
5. The PVC capacity have been changed
![image](https://user-images.githubusercontent.com/29251855/185341620-a296c071-8b03-4be5-a713-df1e2227ae25.png)
6. Check the PV capacity also changed
![image](https://user-images.githubusercontent.com/29251855/185341875-bb2d1a1c-2e34-4e8d-9609-3fc43ea1853f.png)
7. Check the volume size in Harvester also changed
![image](https://user-images.githubusercontent.com/29251855/185342066-e38507e8-2646-4fad-8b0f-09cf8d6c16e9.png)
