### ISSUE TITLE
[FEATURE] S.M.A.R.T. Status in Disks view on nodes

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#2674]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
It would be great to see the Smart Status of the disks within the UI under a specific node - Disks:

**Describe alternatives you've considered**
N/A

**Additional context**

![screenshot_2022-08-17-171100](https://user-images.githubusercontent.com/25985730/185244192-5869716e-3679-48a9-9e65-61362a48e222.png)

**Comment by yasker** [comment]
Will be included in #2318 .
