### ISSUE TITLE
Websocket breaks due to ERR_CERT_AUTHORITY_INVALID in fresh setup

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#268]
**Version**
master(4c23af8)

**Steps to reproduce:**
1. Prepare a Kubernetes cluster
2. Deploy harvester by 
```
helm install harvester deploy/charts/harvester -n harvester-system --set service.harvester.type=NodePort
```
3. Access harvester UI by `https://<nodeIP>:<nodePort>`
4. Trust the self-signed certificate in Chrom browser.
5. Add a VM image with url=`http://example.com/a.img` and name=`test` 

**Result:**
1. The created VM image didn't shown up in the UI.
2. The browser console printed the following errors:
![image](https://user-images.githubusercontent.com/5697937/100056799-43417200-2e61-11eb-8c08-e87ac3b6f88a.png)

**Other details:**
Open another browser window in Incognito mode and access the UI. You will get a ERR_CERT_AUTHORITY_INVALID warning and be asked to trust the self-signed cert again. After that, the websocket should work as expected.

**Comment by gitlawr** [comment]
It should be a backend issue. The cause is that the `serving-cert` TLS secret is changed.
It can be observed by watching the `serving-cert` secret in `kube-system` namespace:
```
# The first revision of the serving-cert secret
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJU...BVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBFQyBQ...BLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    listener.cattle.io/cn-10.42.0.38: 10.42.0.38
    listener.cattle.io/hash: 489a0479e5d5678ce94e7f42cf1c692af352a32a0808e297cecc1a8d2809f5c0
  creationTimestamp: "2020-11-24T06:16:03Z"
  name: serving-cert
  namespace: kube-system
  resourceVersion: "10004"
  selfLink: /api/v1/namespaces/kube-system/secrets/serving-cert
  uid: 48461bef-6337-47d8-ad97-2c0218979ab2
type: kubernetes.io/tls
---
# The second revision of the serving-cert secret
apiVersion: v1
data:
  tls.crt: LS0tLS1CRUdJ...tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  tls.key: LS0tLS1CRUdJTiB...JJVkFURSBLRVktLS0tLQo=
kind: Secret
metadata:
  annotations:
    listener.cattle.io/cn-10.42.0.38: 10.42.0.38
    listener.cattle.io/cn-xx.xx.xx.xx: xx.xx.xx.xx
    listener.cattle.io/hash: cffb69563034b471c0287b815e60d88ccd15218d0ce527c2f46a53b3eaca6ed9
  creationTimestamp: "2020-11-24T06:16:03Z"
  name: serving-cert
  namespace: kube-system
  resourceVersion: "10022"
  selfLink: /api/v1/namespaces/kube-system/secrets/serving-cert
  uid: 48461bef-6337-47d8-ad97-2c0218979ab2
type: kubernetes.io/tls
```

**Comment by futuretea** [comment]
After trust the self-signed cert, chrome doesn't update the `subject alt name(SAN)`, still use the old one(missing `nodePort IP`, only `pod IP`).
Reenable warning, and trust the self-signed cert again will solve it.
![image](https://user-images.githubusercontent.com/15064560/100731075-df411f80-3405-11eb-9552-6a1aade339cc.png)
Using firefox does not have this problem.
The Secret `serving-cert` was updated because a new subject alt name was added. That should be normal.

**Comment by gitlawr** [comment]
In v0.1.0-rc1
With the following steps:
1. Install harvester
2. Add harvester CA cert to the system trusted Certificate
3. Access harvester

The certificate is invalid with the following error
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by gitlawr** [comment]
In version v0.1.0-rc2
The browser will prompt  cert invalid warning twice. After users ignore the warnings, websocket works as expected.
After the CA cert is trusted, the certificate is valid.

**Comment by gitlawr** [comment]
We still need an improvement so that users don't need to skip cert validation twice

**Comment by yasker** [comment]
Had the issue again for a v0.2.0 demo.

**Comment by gitlawr** [comment]
To reproduce in master 3d4a599,
Case 1:
1. Install harvester and access the dashboard, trust the self-signed certificate in Chrome.
2. delete one of the harvester pod.
3. refresh the browser

Result: unable to load the UI, some of the API calls fail.
![image](https://user-images.githubusercontent.com/5697937/111961641-40fbd580-8b2c-11eb-8e77-2030740e2cf6.png)

Case 2:
Trust the root CA generated by Harvester in OS.
access Harvester UI.
It shows ERR_CERT_COMMON_NAME_INVALID
![image](https://user-images.githubusercontent.com/5697937/111957605-33901c80-8b27-11eb-8a88-5d7249686d35.png)

**Comment by gitlawr** [comment]
We have 3 harvester replicas now, when the certificate is updated it may be inconsistent in different replicas.
Now we use Nodeport to expose Harvester, it DNATs the requests using the pod ip so the generated certificate SANs do not include the access url.

**Comment by TangStone** [comment]
### Validation version v0.2.0-rc1
**Steps**
1. Deployment with harvester ISO
2. Access harvester
3. Certificate of Trust
- kubectl -n kube-system get secret serving-ca -o jsonpath='{.data.tls\.crt}'|base64 --decode>ca.pem
- Double-click ca.pem
- Find this ca certificate in the key string (should system) and set always trust
- Configure server-url in settings
![image](https://user-images.githubusercontent.com/15829074/113232332-85773600-92cf-11eb-8f65-f80a095a0cae.png)
4. Change to another browser to access harvester
5. delete one of the harvester pod
6. refresh the browser

**Results**
1. No re-authentication required
2. Refresh access is normal
