### ISSUE TITLE
[FEATURE] support bundle: collect more kernel logs

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2693]
**Is your feature request related to a problem? Please describe.**

Sometimes, it's helpful to have kernel logs of previous boots. But we only have the current boot: https://github.com/rancher/support-bundle-kit/blob/448b4e020a5d92f0ced0e75c1f62e6ca5fb29ff8/hack/collector-harvester#L82

**Describe the solution you'd like**

Including previous boot log 

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
We can test the feature with the latest master ISO.

**Comment by noahgildersleeve** [comment]
Tested in master-18e09a26-head. Verified multiple kernel logs after reboots in support bundle. 
[supportbundle_c19e635c-2847-4532-a2cc-e43bcc35dae7_2022-09-02T22-58-52Z.zip](https://github.com/harvester/harvester/files/9481405/supportbundle_c19e635c-2847-4532-a2cc-e43bcc35dae7_2022-09-02T22-58-52Z.zip)
