### ISSUE TITLE
[Question] How to get Mellanox ConnectX-3 Infiniband to Ethernet working

### ISSUE THREAD

**Issue by alch3mistdev** [harvester/harvester#2694]
Hi,

I've got an Mellanox ConnectX-3 infiniband NIC and I need to switch to ethernet mode. This is usually done through their MFT firmware tool which is asking me to install rpm / make / kernel-source.

I'm trying to use zypper but not having much luck.

Does anyone know how to install https://network.nvidia.com/products/adapter-software/firmware-tools/

**Comment by bk201** [comment]
@anixon604 does the firmware comes with a single RPM? You can temporarily enable RW mode to see if it works: https://docs.harvesterhci.io/v1.0/troubleshooting/os/#how-can-i-install-packages-why-are-some-paths-read-only

**Comment by alch3mistdev** [comment]
@bk201 thanks I followed that guide and in line with that - I found the easiest way was to use the "inbox driver" already included in the kernel and switch the mode from infiniband to eth via these instructions:


## Inbox Driver

```
Options 1:

In order to change the port mode without the script (Inbox support):

echo “mode” >/sys/bus/pci/devices/”pci device”/mlx4_port1

echo “mode” >/sys/bus/pci/devices/”pci device”/mlx4_port2

For Example:

# lspci | grep Mellanox

01:00.0 InfiniBand: Mellanox Technologies MT26428 [ConnectX IB QDR, PCIe 2.0 5GT/s] (rev b0)

#echo ib > /sys/bus/pci/devices/0000\:01\:00.0/mlx4_port1

#echo eth > /sys/bus/pci/devices/0000\:01\:00.0/mlx4_port2

Note: This option is not persistent.
```

```
Option 2 (in case RDMA is in use):

Edit the file /etc/rdma/mlx4.conf:

Note: This file is read when the mlx4_core module is loaded and used to set the port types for any hardware found.

Format:

<pci_device_of_card> <port1_type> [port2_type]

port1 and port2: One of "auto", "ib", or "eth". port1 is required at all times, port2 is required for dual port cards.

For example:

0000:05:00.0 eth eth
Perform reboot to reload the modules

#reboot
```

Source: https://support.mellanox.com/s/article/howto-change-port-type-in-mellanox-connectx-3-adapter

For anyone else who encounters this issue.

**Comment by bk201** [comment]
@anixon604 thanks for the guide!
