### ISSUE TITLE
[Question] How to persist new password for user rancher@node-ip

### ISSUE THREAD

**Issue by kingnarmer** [harvester/harvester#2699]
I did ssh to node as rancher@node-ip , then ran passwd to change the password. 

The old password came back after reboot. 

How to persists new password for user rancher@node-id ?

Thanks

**Comment by bk201** [comment]
Hi @kingnarmer , for persistence, you can edit `/oem/99_custom.yaml` and search for
```
      users:
        rancher:
          passwd: '***'
```

The password will take effect and be persistent between  reboots.
I'll close this one because this will be added in https://github.com/harvester/harvester/issues/2418
