### ISSUE TITLE
[Question] Memory usage very high for edge cases.

### ISSUE THREAD

**Issue by MarkLFT** [harvester/harvester#2702]
I was considering changing our edge servers to use Harvester instead of ESXI, I like the remote console, and the Rancher integration. 
But the resource usage seems to be huge, or am I doing something wrong.

I have a test system with just Harvest 1.0.3, with 8 cpu cores and 12 Gb Memory, most of our edge servers only have 8 Gb. On this Harvester installation currently there is a single Ubuntu Server installation with 2 Cores and 2Gb RAM, with no apps running only the OS.  But the host is already reporting it is using 9.5 of 12Gb, for Edge scenarios that seems a lot. 

Is there a way to trim right down what is installed / used?

My aim is to run one Windows Core VM with 4Gb (Required Windows Services) and one single node k3s cluster.  With ESXi I can do this easily in 8Gb and it runs without issues or OOM problems.  But it seems with Harvester I would require 16 or 24 Gb of memory to even consider doing this.

**Comment by fanlix** [comment]
you can login hv host with `ssh rancher@your-ip`, 
run `top c` to check out which process costs 7.5G ram.

**Comment by MarkLFT** [comment]
It does not appear to be a single process.
RES
kube-apiserver  1.9G
qemu-system  632M
rancher 329M
etc 243M
harvester 218
fleet 187M
kube-controller 
virt-operator

According to top we are using 74.6% of the memory, which tallies with the 9Gb from 12Gb.

**Comment by fanlix** [comment]
You should copy the full output of `top`.  Then others may have a check

* `qemu-system-xxx` process is the real ubuntu vm process. (you offer 2G ram, but only using 632M for now)
* `kube-apiserver` is  k8 process (in my cluster, 1.9G same as yours)

**Comment by MarkLFT** [comment]
Prior to reporting this, I have installed all updates, tried several reboots etc.  But the memory usage still remained unacceptably high, so I was forced to find another solution. 

Unfortunately, I have torn this system down now and installed Proxmox to test that for the moment.  If I install Harvester again in the future, I will look at this again, and provide more details.   

As a side note, on the same hardware, Proxmox is using only 1.4Gb before any VM usage, and just over 2Gb with the same VM created as above. 

Please note I have no great affinity to VMWare or Proxmox, I am simple trying to find the best working solution for us.

**Comment by fanlix** [comment]
I used to try harvester last year on my rpi-4G, it works fine with 2 ubuntu vm. 
but after v1.0, harvester does not use k3s core anymore (which may cost as low as 200M for a full k8s system).

**Comment by w13915984028** [comment]
The planned feature: https://github.com/harvester/harvester/issues/2676

**Comment by pavel-d11** [comment]
Experiencing totally the same behavior but with bigger effort (~14 Gi RAM used on a cluster with single stopped vm). And it doesn`t look like only monitoring feature affects high RAM consumption.
![image](https://user-images.githubusercontent.com/49352048/202860769-f410e596-b2c4-4907-9e60-a5f18c902eb0.png)

**Comment by w13915984028** [comment]
Many optimizations are don in #3262 

But https://github.com/harvester/harvester/issues/2702#issuecomment-1320914701 still encourage us to optimize the system continuously.
