### ISSUE TITLE
[Question] List of OS images to deploy in harvester?

### ISSUE THREAD

**Issue by migs35323** [harvester/harvester#2704]
Hello, is there a "curated" list of OS images that work wonderfully in harvester?

I was trying to create a cluster in harvester through rancher and I was wondering what good OS images that work very well with harvester.
I tried a ubuntu minimal cloud image and the vnc screen was throwing a boot error

**Comment by RegisWeduLabs** [comment]
+1, while youtube videos and some how-tos articles usually uses ubuntu minimal 20.04, it would be helpful to have more documentation and a list of officially supported images along with some basics cloud-init config examples.  Also, as Elemental development seems to be coming to an official release soon, I would suspect that using Elemental as a base image should be pretty straightforward?
