### ISSUE TITLE
[BUG] Virtual Machines page sort by Memory fails

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#2710]
**Describe the bug**
virtual machine page ui sort fails.

**To Reproduce**
1. Host -> any Node -> Virtual Machines
2. sort the table by `Memory` column
3. the effect is not by memory size, but name string alphabetical order.

**Expected behavior**
sort vm by memory size

**Environment**
 - Harvester ISO version:  v1.0.2

**Comment by fanlix** [comment]
v1.1.1 this ui bug still exists.   cpu & memory column

**Comment by TachunLin** [comment]
Verified **fixed** on `master-714ee3fb-head`. (23/01/09). Close this issue.

### Result
Now we can sort virtual machines by `CPU` and `Memory` in order on Host page. 
* Can sort VMs by CPU
![image](https://user-images.githubusercontent.com/29251855/211263520-92815b38-fc4c-4b5e-b1ce-55627f6098a8.png)

* Can sort VMs by Memory 
![image](https://user-images.githubusercontent.com/29251855/211263615-e893dfd4-fdde-4650-ae6e-90c1744155c0.png)


### Test Information
* Test Environment: 1 nodes Harvester local kvm machine
* Harvester version: `master-714ee3fb-head`

### Verify Steps
1. Create virtual machine with 1 CPU, 2 GiB memory
2. Create virtual machine with 2 CPU, 3 GiB memory
3. Create virtual machine with 3 CPU, 4 GiB memory
4. Open virtual machine in Host page 
5. Sort VMs by CPU and Memory
