### ISSUE TITLE
[FEATURE] Upgrade patch of Alertmanager

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2712]
**Is your feature request related to a problem? Please describe.**

`Alertmanager` will be enabled in v1.1.0 by default, it needs to be enabled when upgrading.

**Describe the solution you'd like**

Add upgrade patch of `Alertmanager`

**Describe alternatives you've considered**

**Additional context**

https://github.com/harvester/harvester/issues/2517

**Comment by noahgildersleeve** [comment]
Tested in upgrade from v1.0.3 to master-47a3af23-head. 

## Verification Steps
1. Installed 3 node ipxe setup and verified that there was no alert-manager present
2. Created a manual upgrade `version.yaml` similarly to the [steps in the airgap upgrade setup](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade)
3. Run the upgrade
4. Verify that the upgrade was successful

### Expected Results
- The alert manager pods was created and is in the reporting system
![Screenshot_20220920_113250](https://user-images.githubusercontent.com/83787952/191337834-c0b9fccf-d471-49ba-85ad-dbb6a61e22b7.png)
![Screenshot_20220920_113254](https://user-images.githubusercontent.com/83787952/191337867-a6d95f41-9b67-42b6-b7a2-208ccd2c9f1c.png)
