### ISSUE TITLE
[FEATURE] Update prometheus, grafana, alertmanager, logging related storageclass to harvester related one

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2714]
**Is your feature request related to a problem? Please describe.**

A harvester specific storageclass will be created.
https://github.com/harvester/harvester/issues/2692

**Describe the solution you'd like**

Prometheus, grafana, alertmanager, logging should use this storageclass by default.

After merge of https://github.com/harvester/harvester/issues/2692, update those.

**Describe alternatives you've considered**

**Additional context**

Related issues:
https://github.com/harvester/harvester/issues/2519  Alertmanager is backed by PVC

https://github.com/harvester/harvester/issues/2282   rancher-monitoring-grafana is too small and it keeps growing

https://github.com/harvester/harvester/issues/2645 Logging is backed by PVC

PR: 
Alertmanager feature in harvester-installer: https://github.com/harvester/harvester-installer/pull/322

Alertmanager upgrade patch:
https://github.com/harvester/harvester/pull/2721

**Comment by w13915984028** [comment]
Harvester related `storageclass` is created, `Alertmanager`'s PVC storageclass is aslo patched when upgrading:
https://github.com/harvester/harvester/pull/2768

The `storageclass` of PVC of `Alertmanager`, `Grafana`, `Prometheus` are changed to new default value.
https://github.com/harvester/harvester-installer/pull/336

`logging` feature does NOT use PVC in v1.1.0.

For TEST:

A newly installed cluster with above PRs:
`Alertmanager`, `Grafana`, `Prometheus`  storageclass is the new default value `harvester-longhorn`


For upgrade cluster (to v1.1.0):
`Alertmanager` is enabled, and using the new default value `harvester-longhorn` as `storageclass`
 `Grafana`, `Prometheus`  storageclass are the original default value `longhorn`, not changed in upgrading.

**Comment by guangbochen** [comment]
close as this is duplicate with https://github.com/harvester/harvester/issues/2692.
