### ISSUE TITLE
[FEATURE] Adapt alertmanager to dedicated storage network

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2715]
**Is your feature request related to a problem? Please describe.**

For feature https://github.com/harvester/harvester/issues/1055 Dedicated storage network, the coming feature alertmanager in v1.1.0 should also adpat to it.

**Describe the solution you'd like**

Add `alertmanager` into the processing of `enable/disable dedicated storage network`

`alertmanager` USES the storage-network as others.

**Describe alternatives you've considered**

<del>
Keep those internal PVC out of dedicated storage network, to avoid affect user. @tjjh89017 @bk201 @guangbochen 
</del>

[note, this ALTERNATIVE solution, is not implemented in v1.1.0, add del line]

**Additional context**

https://github.com/harvester/harvester/issues/1055  [FEATURE]Dedicated storage network #1055

https://github.com/harvester/harvester/issues/2518  [FEATURE] enable alertmanager by default

https://github.com/harvester/harvester/issues/2517  feature: Harvester supports alertmanager

**Comment by tjjh89017** [comment]
> Keep those internal PVC out of dedicated storage network, to avoid affect user. 

Currently, Longhorn didn't support this.
We need to configure storage network in LH for global setting

**Comment by tjjh89017** [comment]
This issue will be solved directly via https://github.com/harvester/harvester/issues/1055

**Comment by lanfon72** [comment]
As this requires #1055 implemented and could be verify along with, let this blocked by it.

**Comment by lanfon72** [comment]
Verified this feature not been implemented.
When dedicated storage network is NOT connectable, dashboard becomes inaccessible too.
PVCs loop in `Attaching -> Detached`.


https://user-images.githubusercontent.com/5169694/196937291-3bae97e0-2828-47e5-ba90-5d68273a3676.mp4

Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **master-bd1d49a9-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to _Networks -> Cluster Networks/Configs_, create Cluster Network named `vlan`, create **Network Config** for all nodes
3. Navigate to _Advanced -> Settings_, edit `storage-network`
4. Select `Enable` then select `vlan` as cluster network, fill in **VLAN ID** and **IP Range** that NOT have any network connectivity.
5. Navigate to _Monitoring & Logging -> Monitoring -> Configuration_
6. Dashboard of Prometheus Graph, Grafana and Altertmanager should able to access

**Comment by tjjh89017** [comment]
Grafana and Alertmanager need Longhorn Volume.
If storage network is dead, Longhorn will be dead too.
Grafana and Alermanager will not be able to run.

This issue is for storage network controller process to stop/restart Alertmanager without manual operation.

**Comment by lanfon72** [comment]
@w13915984028 could you update test plan for this issue? from the description:
> Keep those internal PVC out of dedicated storage network, to avoid affect user

It looks like the traffic from those PVCs will not through dedicated storage network. but as @tjjh89017 replied:
> This issue is for storage network controller process to stop/restart Alertmanager without manual operation.

It means PVCs still using dedicated storage network, but will re-attach automatically.

**Comment by tjjh89017** [comment]
> Keep those internal PVC out of dedicated storage network, to avoid affect user

This is not supported by Longhorn, currently.
All volumes need to be detached while setting storage network.

**Comment by lanfon72** [comment]
If it the feature is intent to let internal PVCs not use dedicated storage network, I would suggest reschedule the milestone (as it would be blocked by longhorn).

cc @guangbochen, @bk201

**Comment by bk201** [comment]
@lanfon72 The issue is merely for tracking that we should handle the alert manager's PVC when enabling/disabling the dedicated network. At this moment, all volumes can only reside on the same network, either management or storage. I believe the implementation already meet the expectation.

**Comment by w13915984028** [comment]
I updated the issue description. The `Alertmanger`'s PVC should follow others to use dedicated storage network, when it is enabled.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.
PVCs (alertmanager/grafana/Prometheus) will attach back after dedicated storage network switched.


Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **master-bd1d49a9-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to _Networks -> Cluster Networks/Configs_, create Cluster Network named `vlan`, create **Network Config** for all nodes
3. Navigate to _Advanced -> Settings_, edit `storage-network`
4. Select `Enable` then select `vlan` as cluster network, fill in **VLAN ID** and **IP Range**
5. Wait until error message (displayed under _storage network_ setting) disappeared
6. Navigate to _Monitoring & Logging -> Monitoring -> Configuration_
7. Dashboard of Prometheus Graph, Grafana and Altertmanager should able to access, and should contain old data.
