### ISSUE TITLE
[FEATURE] Harvester supports enable/disable managedchart in day2

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2719]
**Is your feature request related to a problem? Please describe.**

The `managedchart` is installed in day1 bootstrap stage, disable it is not allowed.

**Describe the solution you'd like**

Harvester supports `enable/disable managedchart`  in day2, which includes `monitoring, logging` etc. enhancement features.

Benifits:
```
Reduce system resources requirements.
Speed up system installation and cluster setup.
When installed in `edge` mode,  user can still enable some enhanced features selectively.
```
**Describe alternatives you've considered**

**Additional context**

`edge mode`:
 https://github.com/harvester/harvester/issues/2676.

Also solve:
https://github.com/harvester/harvester/issues/2702

**Comment by w13915984028** [comment]
Future enhancement:

For feature: `monitoring`, `logging`, `event`, `alert`...,  those can be `enabled/disable` in Harvester UI, and in `edge` mode installation, they can be disabled by default.

For feature like `loki`, it could also be treated as `plugin` for Harvester.

https://github.com/harvester/harvester/issues/2517  alertmanager
https://github.com/harvester/harvester/issues/577    logging
https://github.com/harvester/harvester/issues/578    audit and event


@guangbochen @bk201 @rebeccazzzz @yasker @joshmeranda

**Comment by yasker** [comment]
I feel we should design this in #2769

**Comment by Martin-Weiss** [comment]
Disabling monitoring might not fulfill the existing monitoring and alerting requirements.. But maybe we can change the monitoring to "rollup" to a central instance instead of having the full blown stack in each harvester cluster?

**Comment by w13915984028** [comment]
close
#3262 will have an overall design about how to reduce system footprints, it covers #2719 and has more optimization
https://github.com/harvester/harvester/issues/3262
