### ISSUE TITLE
 CRD objects do not show up in the harvester API

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#272]
**version: **
master(5ce34c93d7b2aa50b23f16d67d3100a8a47495b7)

**Steps to reproduce: **

1. Install harvester
2. Add a vm image
3. After the import completes, refresh the UI.

**Result: **
1. the image object is not shown in the UI/API.
2. It is available using `kubectl get vmimage`

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/273

**Comment by DoNotSayYes** [comment]
Validated
