### ISSUE TITLE
[Doc] Update doc about how to extend running PVC size

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2724]
**Describe the bug**

After fix of #2282, it is observed that the upgrade patch is not able to extend `grafana` PVC size easily, user needs to do it manually.

fix2282 adjust grafana POD PVC size to 2GiB
https://github.com/harvester/harvester/issues/2282

Upgrade patch:
https://github.com/harvester/harvester/pull/2711

**To Reproduce**

**Expected behavior**

Update `Harvester doc`, add a guide about how to extend running PVC size, and also add limitation and workaround of #2282 into v1.1.0 release notes.

**Support bundle**

**Environment**
 - Harvester ISO version:  master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
The doc PR: https://github.com/harvester/docs/pull/212 is merged
