### ISSUE TITLE
[BUG] ISO install on Bare Metal ImagePullBackOff

### ISSUE THREAD

**Issue by axsms** [harvester/harvester#2726]
**Describe the bug**
Bare metal install via ISO results in incomplete install with Harvester-Cluster-Repo in cattle-system showing ImagePullBackOff. Multiple attempts, same results. 

**To Reproduce**
1. Install using virtual cd-rom/DVD on HP DL360 Gen 9 servers
2. After many hours (16-24 waited) a reboot reveals a status of `Setting up Harvester`
3. login to shell and get pods for all namespaces to find the issue
4. `describe` the offending pod for full details

**Expected behavior**
Install completes without issue. 

**Support bundle**
UI not available. 

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure: Baremetal HP DL360 Gen 9

**Additional context**
These screenshots show all pods, the ability to ping both local and internet resources, and `describe harvester-cluster-repo...` 
![Screenshot 2022-09-02 152304](https://user-images.githubusercontent.com/83303625/188223246-df043d64-b92b-4696-a31f-b376e0039fe6.png)
![Screenshot 2022-09-02 145805](https://user-images.githubusercontent.com/83303625/188223244-124226af-9109-4df1-9c24-1eb9385ff290.png)

This may be expected since the install has not completed...Browsing to the node shows the RANCHER setup page `http://<node>/dashboard/auth/setup`.

**Comment by bk201** [comment]
@axsms Could you provide a support config? https://docs.harvesterhci.io/v1.0/troubleshooting/installation/#collecting-troubleshooting-information

The harvester-cluster-repo image is not published, we did see a user has a similar issue when he attempts to iPXE boot an installation without providing an ISO URL.

**Comment by RegisWeduLabs** [comment]
Hi @axsms, I had the same issue.  Please look at https://github.com/harvester/harvester/issues/2651#issuecomment-1218389598 as a workaround.  It should work, as the issue is pretty much the same.

**Comment by axsms** [comment]
Happy to close this since the issue appears to be the same as #2651, as noted by @RegisHubelia. I will try the workaround to see if it resolves the issue.
