### ISSUE TITLE
[Question] R610 server issues, en0

### ISSUE THREAD

**Issue by mikecarr** [harvester/harvester#2727]
How can I get logs or debug an issue that occurs in the installer? 

The installer sees my Nic's but it seems the installer is unable to start them.

![crash](https://user-images.githubusercontent.com/1970342/188275152-bee89af1-742f-47bb-85c1-c6b30be179ba.jpg)

**Comment by futuretea** [comment]
@mikecarr Hi, can you provide the Harvester iso version and try another NIC to see if it is OK?

**Comment by mikecarr** [comment]
This was 1.0 I have since upgraded my server and found that I can install using USB method
