### ISSUE TITLE
[Question]how to remove broken disk

### ISSUE THREAD

**Issue by 362475097** [harvester/harvester#2728]
I install harvester in vmware. After I remove a disk and reboot harvster,it display the disk is not ready and not scheduleable.So I want to remove this disk.

  My question is how to remove this broken disk, I can't find the button.
![img](https://user-images.githubusercontent.com/22928574/188294200-3e370601-bc75-4768-bd69-d83d087d69ad.png)

**Comment by fanlix** [comment]
you will see a "x" button on `Edit Config` - `disk` ui page.

**Comment by 362475097** [comment]
> you will see a "x" button on `Edit Config` - `disk` ui page.

There is no "x" button for this broken disk
![1](https://user-images.githubusercontent.com/22928574/188487235-9e5b4270-87ca-4de5-9b0d-5e080ab7db2d.JPG)

**Comment by w13915984028** [comment]
@362475097 Is this issue solved later ?

@chrisho Do we support to do so in GUI? I did not find an option. thanks.

**Comment by chrisho** [comment]
> @362475097 Is this issue solved later ?
> 
> @chrisho Do we support to do so in GUI? I did not find an option. thanks.

Currently, disks can only be removed by Longhorn, we could consider enhancing this feature.
