### ISSUE TITLE
[BUG] Node join fails with self-signed certificate

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2736]
**Describe the bug**
Joining a node to a v1.0.3 harvester cluster fails with untrusted SSL certificate authority

**To Reproduce**
1. Install the first harvester node with a self-signed SSL certificate using v1.0.3
2. Add an additional node

**Expected behavior**
Join works

**Support bundle**
-> ping me in Slack

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**
```
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: time="2022-09-06T05:50:15Z" level=info msg="Rancher System Agent version v0.2.3 (00181cd) is starting"
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: time="2022-09-06T05:50:15Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: time="2022-09-06T05:50:15Z" level=info msg="Starting remote watch of plans"
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: time="2022-09-06T05:50:15Z" level=info msg="Initial connection to Kubernetes cluster failed with error Get \"https://harvester.production/version\": x509: certificate signed by unknown authority, removing CA data and trying again"
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: panic: error while connecting to Kubernetes cluster with nullified CA data: Get "https://harvester.production/version": x509: certificate signed by unknown authority
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: goroutine 14 [running]:
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: [github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc000456000](http://github.com/rancher/system-agent/pkg/k8splan.(*watcher).start(0xc000456000), 0x17de640, 0xc000540240)
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:94 +0xcc5
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]: created by [github.com/rancher/system-agent/pkg/k8splan.Watch](http://github.com/rancher/system-agent/pkg/k8splan.Watch)
Sep 06 05:50:15 niam-msl-def-prod-hvm2 rancher-system-agent[10142]:         /go/src/github.com/rancher/system-agent/pkg/k8splan/watcher.go:58 +0xbe
```

**Comment by Martin-Weiss** [comment]
Hint: hacky workaround was to manually replace the symbolic link

/var/lib/ca-certificates/ca-bundle.pem ->  /usr/share/factory/var/lib/ca-certificates/ca-bundle.pem 

with a ca-bundle.pem file having the certificate of the used CA included.

**Comment by FrankYang0529** [comment]
It looks like we get the wrong certificate in new nodes. The certificate in `/var/lib/rancher/agent/rancher2_connection_info.json` doesn't use our CA. Following are my reproduced steps and workaround. I will figure out how rancher-system-agent gets `kubeconfig` tomorrow.


**Create first node**
* Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) to setup 1-node cluster.
* Generate self-signed certificate. Remember to change `IP.1` value to your VIP.
```console
cat <<EOF > ssl.conf
[req]
prompt = no
default_md = sha256
default_bits = 2048
distinguished_name = dn
x509_extensions = v3_req

[dn]
C = TW
ST = Taiwan
L = Taipei
O = Test Inc.
OU = IT Department
emailAddress = admin@example.com
CN = localhost

[v3_req]
subjectAltName = @alt_names
basicConstraints = CA:TRUE

[alt_names]
IP.1 = 192.168.0.30
EOF

openssl req -x509 -new -nodes -sha256 -utf8 -days 3650 -newkey rsa:2048 -keyout server.key -out server.crt -config ssl.conf
```
* Upload `server.crt` to `Public Certificate` and `CA` in the `ssl-certificates` setting. Upload `server.key` to `Private Key` in the `ssl-certificates` setting.

**Update pxe server**
* Update [`harvester_cluster_nodes`](https://github.com/harvester/ipxe-examples/blob/4122862dd35e59ea034ac851262f47a914927ba8/vagrant-pxe-harvester/settings.yml#L25) to `2`.
* Use `vagrant ssh pxe_server` to login pxe server.
* Add following content to `/etc/dhcp/dhcpd.conf`. Remember to change you `fixed-address` to your second node IP.
```
host harvest_node_1 {
    hardware ethernet 02:00:00:35:86:92;
    fixed-address 192.168.0.31;
    server-name "harvester-node-1";
}
```
* Restart dhcp server `systemctl restart isc-dhcp-server.service`.

**Create second node**
* Under [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester) folder and run `vagrant up harvester-node-1`.
* After second installed, we can use `journalctl -u rancher-system-agent.service` to see error logs.
* Also, we can see that `certificate-authority-data` in `/var/lib/rancher/agent/rancher2_connection_info.json` is old value.

**Fix second node**
* In the first node, run a command `kubectl get sec -n cattle-system tls-ingress -o yaml`.
* Paste value `tls.crt` in the secret to `certificate-authority-data` in `/var/lib/rancher/agent/rancher2_connection_info.json`.
* Finally, run `systemctl restart rancher-system-agent.service` in the second node.

**Comment by Martin-Weiss** [comment]
Are you sure we should use the tls.crt in certificate-authority-data?
I would expect this to be the CA certificate, instead..
(we should trust the CA and not the servers certificate)

**Comment by FrankYang0529** [comment]
Hi @Martin-Weiss, I used same content for `Public Certificate` and `CA` in my testing.

ref: https://github.com/harvester/harvester/issues/761#issuecomment-992638166

**Comment by Martin-Weiss** [comment]
> Hi @Martin-Weiss, I used same content for `Public Certificate` and `CA` in my testing.
> 
> ref: [#761 (comment)](https://github.com/harvester/harvester/issues/761#issuecomment-992638166)

Ok - maybe this needs to be enhanced in testing and a CA certificate needs to be used "separate". So one CA cert and one server cert signed by that CA..
 
Basically new SSL verifications do not allow CA certificates to be used for Server communication.. there are browser warnings and even connection might not be allowed at all.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-032742f0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow Steps in https://github.com/harvester/harvester-installer/pull/335

**Comment by Martin-Weiss** [comment]
It seems I have this issue "still" or "again" in harvester 1.1.1!

-> have my own ssl certificate in ssl-certificates including "ca"/"publicCertificate"/"privateKey"
-> have the CA in additional-ca

And the new node join fails.. - can we re-open this one?

**Comment by bk201** [comment]
@FrankYang0529 Please help recheck the issue.

**Comment by Martin-Weiss** [comment]
FYI - my current workaround is to add the trusted CA here:

```
os:
  write_files:
  - path: /etc/pki/trust/anchors/trusted-ca.pem
    owner: root:root
    permissions: '0644'
    content: |
      -----BEGIN CERTIFICATE-----
```

even though the CA is part of  `ssl-certificates` and `additional-ca` as below:

```
system_settings:
  ssl-certificates: |-
    { "ca": "-----BEGIN CERTIFICATE-----
```

and 

```
system_settings:
  additional-ca: |
    -----BEGIN CERTIFICATE-----
```

**Comment by MaksimRudakov** [comment]
During node joining process we are experiencing TLS certificate verification issues in our 3-node Harvester v1.4.0 cluster.

Error logs from the node:
```
level=info msg="Rancher System Agent version v0.3.9 (0d64f6e) is starting"
level=info msg="Using directory /var/lib/rancher/agent/work for work"
level=info msg="Starting remote watch of plans"
level=fatal msg="error while connecting to Kubernetes cluster: Get "https://harvester-sdlc[...]"
tls: failed to verify certificate: x509: certificate signed by unknown authority"
exited, code=exited, status=1/FAILURE
```

We are using wildcard SSL certificate which is already added to Harvester configuration in two ways:

1. As write_files:
```yaml
write_files:
  - path: /etc/pki/trust/anchors/trusted-ca.pem
    owner: root:root
    permissions: '0644'
```

2. In system settings:
```yaml
systemsettings:
  ssl-certificates: |
  additional-ca: |
```

Despite these configurations, the SSL verification error persists. As a temporary workaround, the node can be added by manually running the command:
```bash
/opt/rancher-system-agent/bin/rancher-system-agent sentinel
```
