### ISSUE TITLE
[BUG] server_url with https but without :443 causes node join to fail

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2737]
**Describe the bug**
Joining an additional node to a harvester 1.0.3 cluster fails in case the port :443 is not part of the server_url specified with https://<vip> in the join-node.yaml

**To Reproduce**
1. install harvester 1.0.3 initial server
2. add additional node via join-node.yaml and specify the URL with https://<vip> and do not add :443

**Expected behavior**
Join should work in case port 443 is used - there should not be any need to add the port :443.

**Support bundle**
-> ping me in slack

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**

```
Sep 06 05:58:01 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
Sep 06 05:58:01 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + RKE2_VIP_CONFIG_FILE=/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Sep 06 05:58:01 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + case $1 in
Sep 06 05:58:01 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + update_agent_conf
Sep 06 05:58:01 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13017]: ++ yq -e e .serverurl /oem/harvester.config
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + server_url=https://harvester.production
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + '[' -z https://harvester.production']'
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13026]: + echo https://harvester.production.niam22.stc.com.sa
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13027]: + grep -E '^https://(.*):(8443|443)'
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + echo '[Error] server port is not 8443 or 443.'
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: [Error] server port is not 8443 or 443.
Sep 06 05:58:02 niam-msl-def-prod-hvm2 harv-update-rke2-server-url[13016]: + exit 1
```

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/218432845-17a36c6c-2320-4afb-9526-935a3240e29e.png)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-0f10441a-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester via PXE installation that not configure `server_url` with `443` port, at least 2 nodes
2. 2nd and others nodes should able to join to first node.
