### ISSUE TITLE
[BUG] - cattle-cluster-agent CrashLoopBackoff exec /usr/bin/run.sh: exec format error

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#2740]
**Describe the bug**
When creating a RKE2 cluster in Rancher using harvester, I sometime have the error on one or more nodes in the cattle-cluster-agent pod that shows "exec /usr/bin/run.sh: exec format error". This usually mean trying to run a binary from another arch (ie: trying to run arm64 binary on a x86 arch).  Deleting the nodes in the cluster within rancher sometimes fixes the issue, sometime deleting the pod and re-create fixes it, sometime I need to completely delete the cluster and recreate it (using the exact same configuration).  Using the minimal 20.04 or 22.04 ubuntu image.  The weird thing is sometime, it goes smoothly with the exact same configuration.  I'm not sure if it is a harvester or Rancher bug, or a configuration issue.

**To Reproduce**
1. 2 Harvester Nodes 1.0.3
2. In Rancher, create a new harvester cluster.
3. 3 Control Planes/etcds
4. 3 Workers node
5. Network Project Isolation
6. Image ubuntu-22.04-minimal-cloudimg-amd64.img or ubuntu-20.04-minimal-cloudimg-amd64.img

**Expected behavior**
I would expect the pods to come up without issues.

**Environment**
 - Harvester ISO version: 1.0.3
 - Kubernetes Version: v1.24.4+rke2r1
 - Underlying Infrastructure: 2x Bare Metal - SuperMicro (OVH HCI-6)

**Comment by w13915984028** [comment]
@RegisHubelia It has been some days after this bug was logged, did you still encounter such ?

**Comment by RegisWeduLabs** [comment]
Yes, It's quite random, I end up deleting the node and it recreates a new one, usually after 2-3 tried, it ends up working...

**Comment by RegisWeduLabs** [comment]
This seems to have been fixed in the latest release as I haven't had this issue since.  Closing.
