### ISSUE TITLE
[BUG] Cannot create namespace into a project

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2742]
**Describe the bug**

**To Reproduce**
1. Go to Projects/Namespaces(multiple cluster)
2. Create `test-ns` namespace into `default` project
3. You'll find out `test-ns` in `Not Namespaced`

![Kapture 2022-09-07 at 10.57.49.gif](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/5ee00ed4-8931-4310-a52f-9ee4163bfd6d)

**Expected behavior**

1. `test-ns` should be created into `default` project

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
This issue will be fixed when harvester/dashboard repo is rebased to rancher/dashboard.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-779c1585-head` (09/14) with Rancher `v2.6.8`. Close this issue.

### Result
Create `test-ns` namespace in default project. 
The `test-ns` namespace will correctly located in default after creation.

https://user-images.githubusercontent.com/29251855/190129028-16727045-221d-4cf0-840c-8c952bb16024.mp4

![image](https://user-images.githubusercontent.com/29251855/190126544-0ddb2026-147a-45ba-ac2b-412ed08ed7ac.png)

### Test Information
* Test Environment: 1 nodes Harvester on local kvm machine
* Harvester version: `master-779c1585-head` (09/14)
* Rancher version: v2.6.8

### Verify Steps
1. Import Harvester from Rancher 
2. Access Harvester from virtualization management 
3. Open Project/Namespace page
4. Click create namespace in project `Default`
5. Provide name `test-ns`
6. Check the `test-ns` namespace project after creation.
