### ISSUE TITLE
[FEATURE] Harvester UI support config (cluster) flow & output for `kube-audit` log and `event` log

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2749]
**Is your feature request related to a problem? Please describe.**

Requirement: https://github.com/harvester/harvester/issues/578

**Describe the solution you'd like**

To support sending (k8s) `audit` and `event` logs to general log servers, `Harvester UI` needs to be able to config (cluster) flow & output for them, adding related filters/references based on log type.

Detailed solution is described in HEP.

**Describe alternatives you've considered**

**Additional context**

HEP PR:
https://github.com/harvester/harvester/pull/2684
HEP 578 event and audit log [CI SKIP] #2684

**Comment by lanfon72** [comment]
Closed as verified along with #2647, #2747, #2748
