### ISSUE TITLE
[FEATURE] Harvester Cloud Provider compatibility check enhancement

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2753]
**Is your feature request related to a problem? Please describe.**

Harvester Load Balancer feature contians a support matrix of RKE2 and Harvester compatible versions, from the UI, we should consider to disable the Harvester cloud provider option when the RKE2 version is not compatible with the Harvester version.

e.g., related LB enhencment issue [2134](https://github.com/harvester/harvester/issues/2134) will only works with Harvester v1.1.1 and upcoming RKE2 versions.

**Describe the solution you'd like**
- From the UI, we should consider to disable the Harvester cloud provider option when the RKE2 version is not compatible with the Harvester version.
- If the compatibility check fails. Show a warning banner upon the create button to tell the user the reason and a doc link.

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-7783939e-head` (09/30) with Rancher `v2.6.9-rc3`. Close this issue.

### Result
1. When we change the cloud provider and csi-driver chart version in Rancher `rke-metadata-config` setting,
Then we select the incompatibility RKE2 version, the Harvester cloud provider is `disabled` and there will be a warning banner
![image](https://user-images.githubusercontent.com/29251855/193209810-214210ae-59ad-438f-bed3-d1ba1ae07cab.png)

2. When we change the cloud provider and csi-driver chart version in Harvester `csi-ccm-versions` according to  [Semver](https://www.npmjs.com/package/semver) expression
Then we select the incompatibility RKE2 versions, the Harvester cloud provider is `disabled` and there will be a warning banner
![image](https://user-images.githubusercontent.com/29251855/193209926-5ed58f92-d1f2-4274-b147-919ea82362b0.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-7783939e-head` (09/30)
* Rancher version: v2.6.9-rc3
* Harvester ui-source: Auto
* Rancher ui-offline-preferred: Dynamic

### Verify Steps
1. Open Rancher Global settings
2. Edit the `rke-metadata-config`
3. Change the default url to `https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/Untitled-1.json` which include the following cloud provider and csi-driver chart changes
```
"charts": {
     "harvester-cloud-provider": {
      "repo": "rancher-rke2-charts",
      "version": "1.1.0"
     },
     "harvester-csi-driver": {
      "repo": "rancher-rke2-charts",
      "version": "1.1.0"
     },
```
4. Save and reload page
5. Open the create RKE2 cluster page 
6. Select the incomparable RKE2 version 
7. Check the Cloud provider drop down 
8. Enable Harvester API in Preference -> Enable Developer Tools & Features
9. Open settings 
10. Click view API of any setting
11. Click up
12. open the  id": "harvester-csi-ccm-versions"
13. Or directly access https://192.168.122.162/v1/harvester/harvesterhci.io.settings/harvester-csi-ccm-versions 
14. Click Edit button
15. Change the default value to `{"harvester-cloud-provider":">=0.0.1 <0.1.2","harvester-csi-provider":">=0.0.1 <0.1.2"}` 
![image](https://user-images.githubusercontent.com/29251855/193208619-fd35fc50-9cff-433a-8f7f-ef59420031d6.png)
16. Show and Send request 
17. Repeat step 5 - 7
