### ISSUE TITLE
[Question] Adding more Disks to store vm's

### ISSUE THREAD

**Issue by mmisworking** [harvester/harvester#2759]
Hello, 

Our hw config
- 6 supermicro microcloud nodes 
- xeon cpu
- 128GB mem
- 1x nvme / 1TB 1x ssd / 2TB 1x hdd 12TB

Installation
- 6 nodes in one cluster 'Harvester OS' installed on the nvme
- connected to rancher 2.6.x

What works
- Everything seems to work, but ....(see our question)

Our question
- We installed harvester on the NVME, but dont want to store VM's on that. Via the settings we are able to add the other drives. But when we add multiple vm's they are randomly stored on the three drives. Is there a possibility to enforce a disk during deploying a vm?

Thanks in advance

**Comment by bk201** [comment]
@mmisworking The best way is select another disk as a data disk during the installation, but I guess you already finish the installation. So an option is to [disable and evict disks](https://longhorn.io/docs/1.3.1/volumes-and-nodes/disks-or-nodes-eviction/#select-disks-or-nodes-for-eviction).
- Visit Longhorn GUI (https://docs.harvesterhci.io/v1.0/troubleshooting/harvester/#access-embedded-longhorn)
- First, you must ensure the free space on the other disks is enough.
- Go to the `Volume` page and **make sure every volume is healthy**.
- Go to the `Node` page. For each node
  - Click `edit node and disks`.
  - Go to the unwanted disk panel (in your case, it should be the one mounted at `/var/lib/harvester/defaultdisk`). Disable scheduling and evict the disk. 
    <img width="472" alt="Screen Shot 2022-09-13 at 2 29 35 PM" src="https://user-images.githubusercontent.com/1691518/189828193-97ed0c9e-f9e9-429a-a08a-2a371d945d79.png">

  - Go to the `Volume` page and wait until all volumes **become healthy** again.
  - Continue to the next node.

**Comment by mmisworking** [comment]
Thanks for the quick response, we dig into this and report back.

**Comment by dorianhhuc** [comment]
Thank you for the response @bk201 , the answer is for a slightly different question although it did guide us to find a desired solution for our issue (except in one particular situation, I will explain it below):

1. Add all available physical disks to each node, using the Harvester web interface.
2. Use the built-in Longhorn UI and assign tags to the different disks as described [here](https://longhorn.io/docs/1.1.1/volumes-and-nodes/storage-tags/).
3. Define a new storageClass and use those tags as the value for the diskSelector parameter.
4. Use the new storageClass as the storageClassName in the metadata for the PersistentVolumeClaimSpec belonging to some VM disk when deploying a new VM.
5. See the desired result: individual VM disks are created on the desired physical disks, this can be verified in the Longhorn UI.

Although regarding VM disks cloned from uploaded disk images when deployed from a VM template (like the general use case for cloud images): they use their own storageClass which links to the source disk image (parameter backingImage). So we wonder: is there a way to force such a cloned disk image to a different storageClass than the default one?

Thanks in advance.

**Comment by bk201** [comment]
@dorianhhuc Thanks for the reply. [The storage tiering feature](https://github.com/harvester/harvester/issues/2147) will be in v1.1.0 to make it possible to add more storage classes. I'd suggest not defining other storage classes at this point because many places need to be taken care of, for example, live migration and backup restore features.

**Comment by w13915984028** [comment]
@mmisworking Did you ever try the Harvester v1.1.1 with the new storage tiering feature, which looks to be a solution for your issue? thanks.
