### ISSUE TITLE
windows server 2019 essentail failed to launch with KMODE exception

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#276]
**Description:**
Windows Server 2019 essential failed to launch with `KMODE exception not handled`

![WX20201130-175659](https://user-images.githubusercontent.com/4569037/100692235-5e623380-33c5-11eb-8ef4-8538dcc5571d.png)

**Comment by futuretea** [comment]
I followed the steps below and successfully installed it, but I am not sure which ones are necessary, so I need to test more：
1. add `options kvm ignore_msrs=1` to /etc/modprobe.d/kvm.conf (requied)
2. reboot  (requied)
3. modify rootdisk size to 50G (option, but 32G is too small, will cause the virtual machine to run slowly)
4. use latest virtio-win driver https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso  (option)
```bash
wget https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/archive-virtio/virtio-win-0.1.190-1/virtio-win-0.1.190.iso
chmod 440 virtio-win-0.1.190.iso
cat << END > Dockerfile
FROM scratch
ADD --chown=107:107 virtio-win-0.1.190.iso /disk/
END

docker build -t kubevirt/virtio-container-disk:latest .
```
5. modify rootdisk bus to SCSI  (option，if you use virtio-win-0.1.190.iso)
6. load drivers:
* Balloon\2k19\amd64  (requied)
* vioscsi\2k19\amd64 (scsi) or viostor\2k19\amd64 (virtio) (requied)

**Comment by futuretea** [comment]
![win2019](https://user-images.githubusercontent.com/15064560/102201576-47612c80-3f01-11eb-9d58-2b151f6a251b.gif)

**Comment by lanfon72** [comment]
encountered this error when testing #1730 with large CPUs allocated(over-committed).

The Node:
![image](https://user-images.githubusercontent.com/5169694/157640862-9c8d9e60-7cb3-4931-97fb-8c47d2d852fc.png)

The VM:
![image](https://user-images.githubusercontent.com/5169694/157641360-1772d12e-df40-41d6-a169-9b409d10b5a9.png)

The VM can successfully boot into OS occasionally, but most time, hit _KMODE EXCEPTION NOT HANDLED_ and restarting.

**Comment by pizzaoven** [comment]
I do not understand how installing the balloon driver fixes the boot issue.  But it fixed my issue.  THANK YOU!

**Comment by guangbochen** [comment]
Windows installation steps is documented at https://docs.harvesterhci.io/v1.0/vm/create-windows-vm/#installation-of-windows; move this to v1.2 to further investigate the impact of enabling the `options kvm ignore_msrs=1` config.
