### ISSUE TITLE
[FEATURE] Migrate `harvester-mgmt` to new mechanism of VLAN config in /oem/99_custom.yaml

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2761]
**Is your feature request related to a problem? Please describe.**

Migrate `harvester-mgmt` to new mechanism of VLAN config in /oem/99_custom.yaml

**Describe the solution you'd like**

Currently, using a shell script with yq to patch /oem/99_custom.yaml to new version directly for upgrade.

**Describe alternatives you've considered**

**Additional context**

related to https://github.com/harvester/harvester/issues/2236
https://github.com/harvester/harvester/issues/1390
https://github.com/harvester/harvester/issues/1647

**PR**
https://github.com/harvester/harvester-installer/pull/334

**Test plan**

1. Install v1.0.3 Harvester
2. backup /oem/99_custom.yaml
3. execute `migrate_harv_mgmt_to_mgmt_br.sh` with root permission
4. check new /oem/99_custom.yaml inherts IP address or DHCP into `mgmt-br`

**Comment by tjjh89017** [comment]
## Test plan

1. make iso with this PR (without vlan enhancement PR)
2. install via ISO
3. check /oem/99_custom.yaml.<TIMESTAMP> is existing
4. check /oem/99_custom.yaml has mgmt-br & mgmt-bo
5. check node's network is ok
6. check `ip link | grep harvester-mgmt` didn't have anything.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/196409316-00dae770-d0ea-44ac-8e65-cd1864dbe7d7.png)


Test Information
----
* Environment: **baremetals DL360G9 4 nodes**
* Harvester Version: **v1.0.3** upgrade to **v1.1.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester `v1.0.3` with any nodes
2. Perform upgrade, same as https://harvester.github.io/tests/manual/_incoming/1707-zero-downtime-upgrade/
3. check /oem/99_custom.yaml. is existing
4. check /oem/99_custom.yaml has mgmt-br & mgmt-bo
5. Check network connectivity
6. Check `harvester-mgmt` is gone, by executing `ip a show harvester-mgmt`
