### ISSUE TITLE
[FEATURE] Add Longhorn and Rancher dashboard links in Support section

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#2765]
For troubleshooting and observability, it is necessary sometimes to go into the Longhorn or Rancher Dashboards. 

The request is to add a link to both within the Support section or anywhere else it makes sense.

**Comment by guangbochen** [comment]
Will add those two dashboard page links on the support page, and more importantly,  it will only be used for debugging and troubling shooting purposes. 
Note: the URL link for single cluster and multiple-cluster dashboards would be different cc @WuJun2016

**Comment by TachunLin** [comment]
Verified **fixed** on master-1646cb66-head. (11/18). Close this issue.

### Result
1. Rancher link and longhorn link display on the support page after enable the dev mode
![image](https://user-images.githubusercontent.com/29251855/202689994-dc45e93a-9e89-4a24-a9e7-780233137701.png)

2. Click the `Rancher Access Embedded Rancher UI` will open a new page and direct to the content
![image](https://user-images.githubusercontent.com/29251855/202690157-1c3f8f9c-5adb-4e3a-a309-afea8c268f80.png)

3.  Click the `Access Embedded Longhorn UI` will open a new page and direct to the content
![image](https://user-images.githubusercontent.com/29251855/202690600-81136390-8e51-4af1-af21-6a9da40b82d9.png)

### Test Information
* Test Environment: 1 node local kvm machine
* Harvester version: master-1646cb66-head. (11/18)

### Verify Steps
1. Go to support page
2. Both of rancher link and longhorn link will not be visible.
3. Go to user preference page
4. Enable DEV mode
5. Back to support page
6. Both of rancher link and longhorn link will be visible.
7. Click links will open a new tab with rancher/longhorn embedded UI.
