### ISSUE TITLE
[BUG] vm cannot backup

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2767]
**Describe the bug**

Install harvester with the latest harvester iso, vm cannot backup.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/974c48ae-06d3-4ab4-9d7a-19d84c4c10e9)

**To Reproduce**
1. Create a vm
2. backup this vm

**Expected behavior**

Can backup normally

**Support bundle**

**Environment**
 - Harvester ISO version:  master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by FrankYang0529** [comment]
It looks like using a default value in kubebuilder is not enough. I will try to add `kubebuilder:validation:Optional` and see whether it can auto set to `backup`.

https://github.com/harvester/harvester/blob/032742f0508935c47a785f1434cb373e8826464c/deploy/charts/harvester-crd/templates/harvesterhci.io_virtualmachinebackups.yaml#L79-L87

**Comment by TachunLin** [comment]
Verified **fixed** on `master-9c3f8a63-head` (09/20). Close this issue.

### Result
* Can initialize the VM backup to Amazon S3 
  ![image](https://user-images.githubusercontent.com/29251855/191224295-4e2ed661-1deb-418a-ad7a-5de44270f453.png)
* And complete the backup
![image](https://user-images.githubusercontent.com/29251855/191226026-8d292375-447f-4580-b486-10e43e126875.png)
 
* Can initialize the VM backup to NFS 
  ![image](https://user-images.githubusercontent.com/29251855/191235390-fd02a76e-eb80-49fa-a8b1-53563b730482.png)

### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-9c3f8a63-head` (09/20)

### Verify Steps
1. Create a virtual machine
2. Setup the Amazon S3 backup target 
3. Create a VM backup to S3 
4. Set the NFS backup target on longhorn, refer to https://github.com/harvester/harvester/issues/2725#issuecomment-1244959046
5. Create a VM backup to NFS
