### ISSUE TITLE
[FEATURE] Harvester extension

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#2769]
**Is your feature request related to a problem? Please describe.**
Harvester extension is a way to expand Harvester's functionality by installing additional components.

**Describe the solution you'd like**
1. Each extension might have it's own UI (depends on https://github.com/rancher/rancher/issues/36972 )
2. Extension can be installed as a Helm chart, or as VMs.
    * VM should be deployed in the HA mode by default. The main use case in mind is Rancher.

**Describe alternatives you've considered**
Reuse Rancher's chart ability. But it won't integrate well with Harvester's experience.

**Additional context**
Potential extensions:
1. [Seeder](https://github.com/harvester/seeder)
4. A local logging viewer using e.g. Loki.
5. [Rancher](related to https://github.com/harvester/harvester/issues/2679 )

**Comment by davidspek** [comment]
I think Loki would make most sense when Longhorn has a S3 compatible storage added, which I believe is planned to happen soon.

**Comment by guangbochen** [comment]
Close as the addon extension is already implemented in Harvester v1.1.0 per https://docs.harvesterhci.io/v1.1/advanced/addons. For those potential extensions, we will track them individually via GH issues, thanks.
