### ISSUE TITLE
[Feature] How can we configure a single IP load balancer for a RKE2 guest cluster hosted on top of Harvester?

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2772]
We deploy RKE2 downstream clusters using Rancher into Harvester.
During this process we also deploy CPI and CSI.

Now we need to expose :6443 / :9345 / :80 and :443 via a loadBalancer VIP provided via Harvesters load balancer.
:6443 and :9345 are provided by the RKE2 masters and :80/:443 via ingress-nginx on all nodes in the RKE2 cluster.

How can we configure a service in the downstream RKE2 cluster to expose these ports via the same external VIP?

**Comment by w13915984028** [comment]
@yaocw2020 any idea? thanks.

**Comment by yaocw2020** [comment]
> @yaocw2020 any idea? thanks.

Util Harvester v1.0.3, the load balancer provided by Harvester is actually a service load balancer in the front of a set of pods. 
In the new coming load balancer version planed to be released in v1.1.1, we'll provide load balancer for the VM workloads which may meet the requirement. Let me confirm it again.

**Comment by n313893254** [comment]
@yaocw2020 Does the backend PR merge?

**Comment by yaocw2020** [comment]
> @yaocw2020 Does the backend PR merge?

Not yet.

**Comment by yaocw2020** [comment]
Test plan:
- Create a guest RKE2 with the harvester cloud provider
- Create a load balancer service. 
- Create another load balancer service. Choose the previous service to share the IP. These two services will have the same load balancer IP.
- Create another load balancer service with the same port as one of the previous services. Choose the first service to share the IP. It will be pending because the same port is not allowed.

**Comment by TachunLin** [comment]
**Verifying** on on v1.2-f4968e49-head (06/30) with Rancher v2.7.5-rc6.

### Result
* We **can** create second load balancer to use the **same** `VIP` address shared from an existing load balancer (with **different** port)
  ![image](https://github.com/harvester/harvester/assets/29251855/f691537d-de3c-48e5-badb-33ebe85a22e8)

* Also we can create the third load balancer with different port and use the shared VIP from the existing one
  ![image](https://github.com/harvester/harvester/assets/29251855/5d425ae3-a3d2-4cb8-991f-5e86f7b28d75)
  


### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `v1.2-f4968e49-head` (06/30) 
* Rancher version:  `v2.7.5-rc6`
* cloud provider version: `0.2.2`

### Verify Steps
1. Import Harvester to Rancher and create cloud credential 
2. Provision a RKE2 guest cluster 
3. Update cloud provider to latest 0.2.2, refer to the steps in https://github.com/harvester/harvester/issues/1762#issuecomment-1611073439
4. Create a nginx deployment
5. Access Harvester in Rancher virtualization management 
6. Create an IP pool, set the network, project, namespace and guest cluster to the correct value 
7. Create a load balancer `lb-pool1` service on RKE2 guest cluster, select Pool mode
8. Create another load balancer use the different port with `lb-pool1` 
9. On the add-on config, select `Use share IP` and select `lb-pool1` 
![image](https://github.com/harvester/harvester/assets/29251855/cb311249-e4dc-4de0-bf1f-96586c646c0e)
10.   Create another load balancer use the same port with `lb-pool1` and select it as the shared target 


### Require further discussion

* When we create a second load balancer with the same port and VIP shared from another load balancer, it will keep in the `pending` state.  But we can still **access** to it. 

  ![image](https://github.com/harvester/harvester/assets/29251855/9d0cd378-1928-4521-9b0d-94f8d2348f8e)

**Comment by yaocw2020** [comment]
@TachunLin 
Require further discussion
When we create a second load balancer with the same port and VIP shared from another load balancer, it will keep in the pending state. But we can still access to it.
-----
Actually, we are accessing the previous service, not the pending service.

**Comment by TachunLin** [comment]
After discussion, when the second load balancer use the same VIP and port as the previous one. 
It will keep in pending but actually connect to the previous load balancer.

(By checking the URL: https://192.168.50.104/k8s/clusters/c-m-qj2kmkql/api/v1/namespaces/default/services/http:lb-pool3:8080/proxy/)

  ![image](https://github.com/harvester/harvester/assets/29251855/9333b5d8-f3c8-49c2-8339-668b639de840)

This would be the expected result. Thus can close this issue.
