### ISSUE TITLE
[Question] How to ZFS boot drive?

### ISSUE THREAD

**Issue by Ashkaan** [harvester/harvester#2775]
Hi, I'm hoping to install Harvester on a ZFS array as the boot drive, but the installer doesn't seem to have the option in the GUI the way that Proxmox does.  How do we do this?  Does someone have a guide?

**Comment by bk201** [comment]
Hi @Ashkaan, thanks for asking. We currently don't have a plan to support installing Harvester on ZFS array. There are some reasons for this:
- We ship Harvester with SLE base OS and ZFS is not a supported FS.
- ZFS is not supported in [elemental toolkit](https://rancher.github.io/elemental-toolkit/), we use it to manage OS lifecycles.
- ZFS is not a supported FS for longhorn.

**Comment by Ashkaan** [comment]
Thank you so much for the clear explanation!

Is there anything on the roadmap for intel softRAID?

**Comment by bk201** [comment]
@Ashkaan Software RAID is not in our roadmap either. We have seen deployments on hardware RAID only.

**Comment by Ashkaan** [comment]
Thank you
