### ISSUE TITLE
[FEATURE] remove some dead OS types

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2776]
**Is your feature request related to a problem? Please describe.**

When creating images in Harvester, there
are entries to set OS type to defunct Linux
distributions (Turbolinux - dead for 3 years,
Mandriva - dead for 11 years, Xandros - dead for 15
years) that show up as options along with
competitors like Red Hat and Oracle, but SLES is
relegated to "Other Linux".

**Describe the solution you'd like**

remove some dead OS types,  add  `SUSE Linux Enterprise` OS

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-3bcba9d3-head` (09/13). Close this issue.

### Result
The following OS types already been removed from list 

- Turbolinux 
- Mandriva
- Xandros

Compared to v1.0.3 os type list
![image](https://user-images.githubusercontent.com/29251855/190972855-e12b4a22-0cdf-4db3-8439-55af23bf69b4.png)

In v1.1.0 master  we add the `SUSE Linux Enterprise` in the VM creation page
![image](https://user-images.githubusercontent.com/29251855/190973269-764e425f-20be-4cb1-8334-e7af668a7798.png)

In the image create page
![image](https://user-images.githubusercontent.com/29251855/190973576-bbc25dd7-9ffe-4f8e-92c2-604defe9eb2b.png)

In the template create page
![image](https://user-images.githubusercontent.com/29251855/190973689-65943f6e-59da-4f45-88dd-3b8cf17ca0e2.png)


### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: `master-3bcba9d3-head` (09/13)

### Verify Steps
1. Login harvester dashboard
2. Open the VM create page, check the OS type list
3. Open the image create page, check the OS type list 
4. Open the template create page, check the OS type list
