### ISSUE TITLE
[BUG] Installation fail : Failed mounting device /dev/sda1 with label COS_GRUB,  mount: /run/cos/efi: unknown filesystem type 'VMFS_volume_member'.

### ISSUE THREAD

**Issue by MLaudren** [harvester/harvester#2781]
**Describe the bug**
The setup process is not able to complete, and fail at the step to copy files to one of the partition.
I have tried to erase the disk, reinitialize it, change the boot partition to MBR or GPT, use WipeFS, nothing changed.
The same error come again and again.
I'm not able to identify why it come, and the log does not provide much indication to other potential causes.

**To Reproduce**
1. start the install procedure
2. Select the drive to install the OS
3. Provide the machine name
4. Select the NIC to be used
5. Set all the network parameters
6. Validate all the config and launch the setup

**Expected behavior**
Setup to complete without issue

**Support bundle**
Not available

**Environment**
 - Harvester ISO version: 1.0.1, 1.0.2, 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HP Z420, Xeon E3 4c/8t, 24G Ram, 480G disk

**Additional context**
Disked wiped with wipefs, and easus disk utility
Using Ventoy to load the ISO, and burned on a USB stick as well
[console.log](https://github.com/harvester/harvester/files/9599436/console.log)

**Comment by w13915984028** [comment]
@MLaudren What was the usage of your baremetal server before? The error message is about the unknow filesystem type `VMFS_volume_member`.

`mount: /run/cos/efi: unknown filesystem type 'VMFS_volume_member'."`

``` VMFS(Virtual Machine File System) is a clustered filesystem designed to store virtual machine disks for VMware ESX or ESXi Server hosts. ```

**Comment by w13915984028** [comment]
It seems the `wipefs -a` can NOT fully wipe it. From following similar situation, they said 

> I had this same issue, it seems if you already have an efi partition, it doesn't wipe it out correctly and the old label remains, in my case VMWARE label still existed. after doing a zero wipe of the first gig of the drive, reinstalling worked fine and blkid shows the name of the EFI partition as COS_GRUB instead of VMWARE.....

https://github.com/harvester/harvester/issues/2066#issuecomment-1078731977

https://github.com/harvester/harvester/issues/1813#issuecomment-1068674094

@MLaudren would you like to try such solution? thanks.


cc @bk201 @guangbochen @rebeccazzzz add the workaround to `troubleshooting` ?

**Comment by MLaudren** [comment]
@w13915984028
Yes I will try to perform a dd to clean the disk partition table.
I will update this ticket with result of the setup once I have them.

**Comment by votdev** [comment]
Fixed with https://github.com/harvester/harvester-installer/pull/660
