### ISSUE TITLE
How To - Import working kvm qcow2 image

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#2784]
Hello Everyone, i've made a few attempts at digging and tinkering, and i cant seem to figure this out. 

does anyone have a recommendation on how to import a currently working, windows 10 vm, from a kvm host.

the current host is running kvm on ubuntu 20.04. it has a windows 10 guest i'm trying to migrate into my harvester cluster. the vm is about 200gb large. i've tried manually updating the drivers before uploading to harvester, and i've tried letting the machine do a boot repair, but it seems to keep comming up with innaccessable_boot_device bsod's when it tries to boot.

again, this is basically migrating an existing windows vm, not a clean install. i can do a clean install of server 2022 just fine.

Thanks!

**Comment by albertkohl-monotek** [comment]
[#2950 how to migrate windows hyper-v guest into harvester ](url)

**Comment by xeruf** [comment]
proper link: https://github.com/harvester/harvester/issues/2950
