### ISSUE TITLE
[BUG] ClusterFlow/ClusterOutput is unvisible now

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2786]
**Describe the bug**

We will save `clusterFlow`/`clusterOutput` in the particular namespace `cattle-logging-system`.

https://github.com/rancher/dashboard/blob/c9a993f197973d9568af674742e338aa11cd996f/shell/edit/logging.banzaicloud.io.clusteroutput.vue#L8

`cattle-logging-system` will be identified as system namespace since it ends with `system`.
https://github.com/rancher/dashboard/blob/c9a993f197973d9568af674742e338aa11cd996f/shell/models/namespace.js#L88

And we set `hideSystemResources ` as true in harvester product.

https://github.com/rancher/dashboard/blob/c9a993f197973d9568af674742e338aa11cd996f/pkg/harvester/config/harvester.js#L68

It caused `clusterFlow`/`clusterOutput` resources to be unvisible in resource list page in harvester product.

**To Reproduce**
1. Go to create a logging output.
2. The created output is not visible in resource list

**Expected behavior**

1. We should have alternatives for filtering resources. (filter or display all of resources in any namespace)

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/191696592-595d6472-3455-4571-b5b9-bc885d6a6628.png)
![image](https://user-images.githubusercontent.com/5169694/191696621-c2c2ebeb-02e1-483d-8fcb-d0aa3174d430.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-250f41e4-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to _Monitoring & Logging/Logging_
3. Create _Cluster Output_ and _Cluster Flow_, and they should be available after created.
