### ISSUE TITLE
[BUG] Sometimes fluentd-configcheck POD is in Unknown status

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2787]
**Describe the bug**

Rarely, in a newly installed cluster, following POD are in `Unknown` status.

```
NAMESPACE                   NAME                                                              READY   STATUS              RESTARTS   AGE
cattle-logging-system       rancher-logging-kube-audit-fluentd-configcheck-ac2d4553           0/1     Unknown             0          10m
cattle-logging-system       rancher-logging-root-fluentd-configcheck-ac2d4553                 0/1     Unknown             0          10m
```

When user creates `ClusterFlow`, `ClusterOutput`, it can be recovered.  When there are already existing `ClusterFlow`, `ClusterOutput`, rebooting the cluster, no such issue.

It seems to be related to: when there are no `clusterflow/output`, it may hit potential bug of `fluentd`.

It is first discovered in: https://github.com/harvester/harvester-installer/pull/333#issuecomment-1249560785.

**To Reproduce**
1. Install a Harvester cluster with feature #577 #578 
2. Check POD status

**Expected behavior**

For newly installed system, PODs should be in normal status.

**Support bundle**

**Environment**
 - Harvester ISO version:  master-head 2022.09.20
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM based

**Additional context**

**Comment by w13915984028** [comment]
<del> One suspect commit: </del>  Following commit is in Harvester current used `logging-operator` image `rancher/mirrored-banzaicloud-logging-operator:3.17.7`.

https://github.com/banzaicloud/logging-operator/commit/70adfef1878a39e46fad673641d71c0cadc4d5bb

![image](https://user-images.githubusercontent.com/31133476/191282496-86f2f37e-58f6-4aaf-b9b1-5ad4bc241685.png)

**Comment by w13915984028** [comment]
Update:

With 10+ times of fresh installing a Harvester cluster, 10+ times of rebooting a newly installed cluster, the issue is not reproduced.

Additional information of the BUG when it happpened:

kubectl can NOT `get pod` or `describe pod` of those 2 `Unknown` PODs. `fluentbit`, `fluend` PODs are not deployed yet, due to `configcheck` POD is not finishied successfully.

```
harv31:~ # kk get pods -A
NAMESPACE                   NAME                                                              READY   STATUS              RESTARTS   AGE
cattle-logging-system       harvester-default-event-tailer-0                                  1/1     Running             0          10m

cattle-logging-system       rancher-logging-574448c578-t746l                                  1/1     Running             0          10m

cattle-logging-system       rancher-logging-kube-audit-fluentd-configcheck-ac2d4553           0/1     Unknown             0          10m

cattle-logging-system       rancher-logging-rke2-journald-aggregator-lb22b                    1/1     Running             0          10m

cattle-logging-system       rancher-logging-root-fluentd-configcheck-ac2d4553                 0/1     Unknown             0          10m


harv31:~ # kk describe pod -n cattle-logging-system rancher-logging-root-fluentd-configcheck-ac2d4553
Error from server (NotFound): pods "rancher-logging-root-fluentd-configcheck-ac2d4553" not found

harv31:~ # kk get pod -n cattle-logging-system rancher-logging-root-fluentd-configcheck-ac2d4553
Error from server (NotFound): pods "rancher-logging-root-fluentd-configcheck-ac2d4553" not found
harv31:~ # 
```

Deploy a new `ClusterFlow & ClusterOutput`, the `rancher-logging-root-fluentd*` POD are recovered. The `audit` related PODs are still in `Unknown` status.

```
harv31:~ # kk get pods -A
NAMESPACE                   NAME                                                              READY   STATUS              RESTARTS   AGE
cattle-logging-system       harvester-default-event-tailer-0                                  1/1     Running             0          15m
cattle-logging-system       rancher-logging-574448c578-t746l                                  1/1     Running             0          16m
cattle-logging-system       rancher-logging-kube-audit-fluentd-configcheck-ac2d4553           0/1     Unknown             0          15m

cattle-logging-system       rancher-logging-rke2-journald-aggregator-lb22b                    1/1     Running             0          16m

cattle-logging-system       rancher-logging-root-fluentbit-tqfqf                              1/1     Running             0          96s
cattle-logging-system       rancher-logging-root-fluentd-0                                    2/2     Running             0          96s
cattle-logging-system       rancher-logging-root-fluentd-configcheck-b55a4e4c                 0/1     Completed           0          100s
```

**Comment by guangbochen** [comment]
For the v1.1.0 release, we may consider providing the manual workaround solution here if users encounter it, further investigation and solution can be done via the v1.1.1 release, thanks.

**Comment by joshmeranda** [comment]
Setup an automated harvester deployer to deploy a harvester cluster and check the `fluentd-configcheck` pods for an unknown state 100x times and ran over the weekend. I still wasn't able to reproduce.

I was only deploying a single node harvester cluster, so it could be an issue caused by some multi-node shenanigans but seems unlikely.

https://github.com/joshmeranda/MyJournal/tree/main/harvester/investigating-2787

**Comment by bk201** [comment]
Close due to un-reproduce. Please reopen if see this again.
