### ISSUE TITLE
[BUG] Cant access embedded longhorn or rancher

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2789]
**Describe the bug**

When trying to access embedded longhorn or Rancher I get the fail whale
**To Reproduce**
1. Navigate to https://{{HARVESTER_IP}}/dashboard/c/local/explorer or https://{{HARVESTER_IP}}/dashboard/c/local/longhorn
![Screenshot_20220920_111846](https://user-images.githubusercontent.com/83787952/191334835-73b4a52f-8b25-4bc6-b8b8-3e6c9f624455.png)
**Expected behavior**
You should get Longhorn or the Rancher cluster explorer
**Support bundle**
[supportbundle_c60fac5a-e48a-4640-a573-0dcc073a6abe_2022-09-20T18-21-36Z.zip](https://github.com/harvester/harvester/files/9610327/supportbundle_c60fac5a-e48a-4640-a573-0dcc073a6abe_2022-09-20T18-21-36Z.zip)

**Environment**
 - Harvester ISO version: master-47a3af23-head

 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant ipxe 3 node setup

**Additional context**
I tried https://192.168.0.131/dashboard/explorer and https://192.168.0.131/dashboard/longhorn too and they didn't work.

**Comment by w13915984028** [comment]
Confirm it's broken in master-head now.

An replacement solution for accessing embedded `longhorn`.

https://the-vip/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/

**Comment by masteryyh** [comment]
It seems unable to reproduce in rc2 environment, both `https://{{HARVESTER_IP}}/dashboard/c/local/explorer` and `https://{{HARVESTER_IP}}/dashboard/c/local/longhorn` can be accessed directly through browser.
@noahgildersleeve can you confirm it still can be reproduced in current rc2 build? CC @w13915984028 @guangbochen

**Comment by guangbochen** [comment]
Can't reproduce it either in v1.1.0-rc2, @noahgildersleeve please help to validate it again and close it if this is not an issue, thanks.
<img width="723" alt="image" src="https://user-images.githubusercontent.com/4569037/195034005-81f8b47d-336c-4bb0-aec9-82a1ae7c9685.png">

**Comment by noahgildersleeve** [comment]
Retested in v1.1.0-rc2. I think that the issue I was having was I was trying to navigate to `dashboard/harvester/c/local/longhorn|explorer` not `dashboard/c/local/longhorn|explorer`. I'm closing this as not an issue. I think that the relative path for Harvester dashboard changed at some point and I didn't realize it.

I think there might have been a redirect in previous versions.

**Comment by noahgildersleeve** [comment]
After reviewing things it looks like I wasn't going to the wrong URLs, but maybe it was fixed at some point during the release cycle. There were several changes to the UI framework during the v1.1.0 release.
