### ISSUE TITLE
[FEATURE] Add terraform support for the VLAN enhancement

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2790]
**Is your feature request related to a problem? Please describe.**

Add terraform support for the VLAN enhancement.
The details about VLAN enhancement refer to https://github.com/harvester/harvester/pull/2161

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by futuretea** [comment]
track in https://github.com/harvester/harvester/issues/2957
