### ISSUE TITLE
[BUG]Can't delete multiple namespaces at once

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2791]
**Describe the bug**

**To Reproduce**
1. Go to Namespace page
2. Select two or more namespaces
3. Delete
4. You'll find out only the first namespace which you selected is removed

**Expected behavior**

1. Delete multiple namespaces correctly

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-250f41e4-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2791#issue-1380199435
