### ISSUE TITLE
[FEATURE]Should we display logging nav tabs if there are no logging resources

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2792]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
cc @joshmeranda , your suggestion is tracked here, thanks.

**Comment by DaiYuzeng** [comment]
@w13915984028 @joshmeranda @guangbochen 
this issue is duplicated with #2750, so I closed it.
