### ISSUE TITLE
[FEATURE] Network interface UI enhancement for network configs

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#2794]
**Is your feature request related to a problem? Please describe.**

- Save network interface status information in a configmap or a new CR.
- Add a dropdown box for users to select NICs when creating or updating vlanconfigs.
- Update the network interface status in the host/network tab.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
@n313893254  this looks great!
I went through and checked that the CRDs are present and things in the UI look good too.
I created different network configs, networks, vlans - some that used multiple nics and others that used single nics.

![Screenshot from 2022-10-17 16-32-30](https://user-images.githubusercontent.com/5370752/196302597-b7782b09-8d84-439f-be67-895f6449359b.png)
![Screenshot from 2022-10-17 16-31-21](https://user-images.githubusercontent.com/5370752/196302601-b0103a66-c112-4244-9f1b-03146e628027.png)
![Screenshot from 2022-10-17 16-14-19](https://user-images.githubusercontent.com/5370752/196302602-458ecb5f-aab0-41dc-8358-93f92ab71b1c.png)
![Screenshot from 2022-10-17 15-15-27](https://user-images.githubusercontent.com/5370752/196302669-ebe1042b-76db-4871-916e-d4f10e1d9178.png)
