### ISSUE TITLE
[BUG] Alertmanager config page should prevent using empty name to add receiver   

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2798]
**Describe the bug**

In the Alertmanager config page, when we add template but did not provide any name, we can still click the create button.
But after that nothing happened. 

https://user-images.githubusercontent.com/29251855/191482627-e231a72e-4ed7-4535-b6cc-04d7da377d32.mp4

**To Reproduce**
1. Go to Monitoring and Logging page 
2. Open Alertmanager Configs page 
3. Create a new alertmanager config 
4. Access the alertmanager config 
5. Click Add Receiver 
6. Input necessary field 
7. `Did not` input name 
8. Click the `Create` button 

**Expected behavior**

Should have asterisk besides name field and prompt error if user did not provide a name 

**Support bundle**

[supportbundle_d95e07f7-9176-4a6f-9393-f8d03af4a213_2022-09-21T10-38-16Z.zip](https://github.com/harvester/harvester/files/9615780/supportbundle_d95e07f7-9176-4a6f-9393-f8d03af4a213_2022-09-21T10-38-16Z.zip)

**Environment**
 - Harvester ISO version: 1 node Harvester on local kvm machine 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `master-4c2242cd-head` (09/21)

**Additional context**

**Comment by w13915984028** [comment]
connect to https://github.com/harvester/harvester/issues/2643

**Comment by lanfon72** [comment]
UI need to re-design as the dropdown list of Receiver in `Route` tab, require receivers which reflect to config itself.

![image](https://user-images.githubusercontent.com/5169694/192582516-65be5b39-63af-410e-a862-642274aae83f.png)
![image](https://user-images.githubusercontent.com/5169694/192582688-7c804436-00da-4b9f-b15e-d153714a3942.png)
![image](https://user-images.githubusercontent.com/5169694/192582733-50a66054-1b2a-47c1-b035-4af7a76b6459.png)

**Comment by TachunLin** [comment]
The original issue have been fixed on `master-a310138d-head` (12/27). 

### Test Result
When we use empty name to add receiver, it would prompt error to prevent creating.

https://user-images.githubusercontent.com/29251855/210317596-1f6ff870-ee1a-4dde-ba68-b59c765ae971.mp4

### Test Information
* Test Environment: 1 nodes Harvester on local kvm machine
* Harvester version: master-a310138d-head

### Verify Steps

1. Go to Monitoring and Logging page
2. Open Alertmanager Configs page
3. Create a new alertmanager config
4. Access the alertmanager config
5. Click Add Receiver
6. Input necessary field
7. Did not input name
8. Click the Create button

**Comment by TachunLin** [comment]
Verified the UI re-design comment of https://github.com/harvester/harvester/issues/2798#issuecomment-1259760028 on `master-a310138d-head` (12/27).

It looks like the behavior remain the same as it was. 

https://user-images.githubusercontent.com/29251855/210320703-3881c14c-662a-4152-90ee-29cf1943a50d.mp4

Suggest we can investigate more of the behavior dropdown list of Receiver in Route tab. Move to implement stage.

**Comment by n313893254** [comment]
Also found a minor issue in the latest UI index（1/19）: The tooltip of the "Add Receiver" button can be clicked and then throw an error with the page crash.

![image](https://user-images.githubusercontent.com/18737885/213353895-5d7c2753-2494-40fc-8bac-770194367f4e.png)

https://user-images.githubusercontent.com/18737885/213353584-be2727bf-1b3a-4389-8310-973496cf3370.mov

**Comment by TachunLin** [comment]
Verified **fixed** on `master-aa7fcafc-head` (02/07). Close this issue.

Checked with development team, the new enhancement including:
1. The tooltip besides the "Add Receiver" now is not clickable
2. Prevent user to create receiver with the same name 

For the rest of the suggested changes, development will track with Rancher team afterward.

### Result
1. When we create receiver without name, it will prompt warning message and grey out the Create button
  ![image](https://user-images.githubusercontent.com/29251855/218032250-88013efd-d103-4de1-8650-f8432280314b.png)

2.  Now we can't click the tooltip besides the "Add Receiver" 
  ![image](https://user-images.githubusercontent.com/29251855/218027243-996e63bb-2d2d-4b84-b2a2-8c92413d8141.png)

3. There is a warning message and grey out the Create button to prevent creating duplicate name of receiver
  ![image](https://user-images.githubusercontent.com/29251855/218027313-263009f6-ed18-42db-96bf-6d5d576fe73c.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-aa7fcafc-head` (02/07)

### Verify Steps

1. Go to Monitoring and Logging page
2. Open Alertmanager Configs page
3. Create a new alertmanager config
4. Access the alertmanager config
5. Click Add Receiver
6. Input necessary field
7. Did not input name
8. Click the Create button
9. Input receiver name 1 and create 
10. Create another receiver with the same name 1
