### ISSUE TITLE
[BUG]  Console button enhancement

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2806]
**Describe the bug**

When the user does not fill in any url values, the jump button should not be clickable

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/c83a5dae-e7e6-4cd9-96cc-df84c1e8bd30)

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
Test steps:

1. Go to host list
2. Console button should be disabled
3. Go to edit host page
4. Input console url
5. Go to host list
6. Console button should be abled

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/193023236-e1366c5a-79d0-48c4-8b68-28bb4839029d.png)
![image](https://user-images.githubusercontent.com/5169694/193023259-03936e3b-f77c-45c5-b36e-70750a6f930d.png)


Test Information
----
* Environment: **baremetal DL360G9 4 nodes**
* Harvester Version: **master-7dd398f0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Same as https://github.com/harvester/harvester/issues/2806#issuecomment-1261827778
