### ISSUE TITLE
[FEATURE] image config display enhancement

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2807]
**Is your feature request related to a problem? Please describe.**

create a image by download from url
click config show:
![image](https://user-images.githubusercontent.com/15064560/191651280-e6317150-59da-4c76-bf31-066e0d343d91.png)

edit config show:
![image](https://user-images.githubusercontent.com/15064560/191651720-4b6d166f-4dbf-4d43-9c05-9e57eb42b0f9.png)

**Describe the solution you'd like**

show url in image config if the image source type is download

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-714ee3fb-head` (23/01/09). Close this issue.

### Result
* Can display URL in the image config page when created from download url. 
![image](https://user-images.githubusercontent.com/29251855/211259596-98b0055d-df1f-45b9-859c-77a81b69924a.png)

* Can display file name in the image config page name when uploaded from file.  
![image](https://user-images.githubusercontent.com/29251855/211259721-0f199e4a-4879-4a64-b908-9aa5728681cf.png)


### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-714ee3fb-head`

### Verify Steps
1. Download an image from URL 
2. After finish, open the edit page 
3. Click the config tab 
4. Check the content 
5. Upload an image from file
6. Repeat step 2 - 4
