### ISSUE TITLE
[BUG] VLAN cannot view detail page

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2815]
**Describe the bug**

VLAN cannot view detail

**To Reproduce**
1. Go to Network -> VLAN
2. Create a VLAN
3. Click the VLAN name in the table

**Expected behavior**

Go to detail page

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/191705510-c3d8f613-5ec4-47c8-b7b5-c242593991e1.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **DL360G9 4 nodes**
* Harvester Version: **v1.1.0-rc1**
* **ui-source** Option: **External**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2815#issue-1382101193
