### ISSUE TITLE
[BUG] Projects/Namespaces display wrongly

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2816]
**Describe the bug**

**To Reproduce**
1. Prepare rancher cluster
2. Import harvester cluster
3. Go go Projects/Namespaces page

<img width="1192" alt="image (1)" src="https://user-images.githubusercontent.com/15041915/191718235-a2d40314-c05d-430e-ae92-a6c86194f0d0.png">

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.1.0-rc1` and Rancher `v2.6.9-rc2` with remote ui-dashboard-index. I tested with an admin user and a cluster mmember. It looks good. 
![Screenshot_20220928_163219](https://user-images.githubusercontent.com/83787952/192906403-e5b3215e-896b-409d-ba33-e33b920dad9a.png)
![Screenshot_20220928_163201](https://user-images.githubusercontent.com/83787952/192906407-e6df6899-919d-4003-8af4-a4b3c64ca255.png)
