### ISSUE TITLE
[BUG] Admin user can not access Harvester cluster by Rancher

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2818]
**Describe the bug**

Admin user can not access Harvester cluster by Rancher

**To Reproduce**
1. v2.6.9-rc1 Rancher import a v1.10-head Harvester
2. log in as an admin user
3. Edit Rancher setting `ui-offline-preferred` to `External`
4. Go to Harvester endpoint and Edit Harvester setting `ui-source` is `External`
5.  Edit Rancher setting `ui-offline-preferred` to `Dynamic` (Use default value)
6. Access Harvester cluster by Rancher UI

**Expected behavior**

Go to Harvester UI

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/191767846-1249f8fc-29c0-4fac-bcd7-78bda52b862d.png)

https://user-images.githubusercontent.com/18737885/191767491-7bfe2bd2-29ba-4fd1-8f5e-cd2b4ff9c9fa.mov

**Comment by WuJun2016** [comment]
Fixed:  https://github.com/rancher/dashboard/commit/c413322de501249f91790e372d5736fb5dece01c ,  Please use master-head to test， thanks

**Comment by TachunLin** [comment]
#### Test Plan 
1. Verify on Rancher `v2.6.9-rc1` with Harvester `v1.1.0-rc1` 
   - Set Rancher ui-dashboard-index to https://releases.rancher.com/dashboard/release-2.6.9/index.html 
   - Set Rancher ui-offline-preferred to `Remote`
   - Set  Harvester ui-source is `External`

2. Verify on Rancher `v2.6.9-rc2` with Harvester `v1.1.0-rc2` 
   - Set Rancher ui-offline-preferred to default `Dynamic`
   - Set Harvester ui-source to default `Auto`

**Comment by lanfon72** [comment]
As this bug be includes in existing Rancher Integration test cases, we can just verify it on Rancher `v2.6.9-rc2` with Harvester `v1.1.0-rc2`

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/192963749-ebb32897-565f-405d-a3f2-c1d86e8c47b9.png)


Test Information
----
* Environment: **baremetal DL360G9 4 nodes**
* Harvester Version: **master-7dd398f0-head**
* **ui-source** Option: **External** and **Bundled**
* **Rancher** Version: **v2.6.9-rc2**
* **Rancher** _ui-offline-preferred_: **Dynamic**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2818#issue-1382509041
