### ISSUE TITLE
[BUG] Host storage can not see disk status

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2822]
**Describe the bug**

Host storage can not see disk status

**To Reproduce**
1. Go to Host -> Storage

**Expected behavior**

Can see the disk status

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/191883027-fd528c4d-34aa-4455-8268-146364059dfa.png)

![image](https://user-images.githubusercontent.com/18737885/191882960-fcba1cdb-fffe-407b-be93-7171c9a09854.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/192958600-801c0ac1-2a29-4c57-8200-976e6c89acfd.png)


Test Information
----
* Environment: **bare metal DL360G9 4 nodes**
* Harvester Version: **master-7dd398f0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2822#issue-1383224187
