### ISSUE TITLE
[BUG] Storage Class can be created with 3 replicas when disk has 0 replicas

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2826]
**Describe the bug**
"Number Of Replicas" for Storage Class creation doesn't audit replicas available on extra-disk that has been force-formatted with ext4 from Host Storage Config, with disk selector label added.

**To Reproduce**
1. Add an extra disk to the node, Hosts -> Edit Config -> Storage -> Add Disk -> Force Format Ext4
1. Add tags to the disk you just added
1. Go-to Advanced ->  Storage Classes -> Create
1. Fill out, keep "Number Of Replicas: 3", select node, select disk selector with the same tag that you used for the extra disk, "Provisioner: Longhorn", keep everything in Customize as default
1. Go-to Image -> Create, fill out, go-to "Storage" select Storage Class to the one you just created

**Expected behavior**
That the storage class would check the disk with the Longhorn provisioner to validate that if the user specified "Number Of Replicas: 3" that the Longhorn extra-disk has 3 replicas - validating that # of replicas are accurate.

**Support bundle**
[supportbundle_22241fc2-4f6e-4105-9483-178b97ed77b8_2022-09-24T00-40-56Z.zip](https://github.com/harvester/harvester/files/9637595/supportbundle_22241fc2-4f6e-4105-9483-178b97ed77b8_2022-09-24T00-40-56Z.zip)

**Environment**
 - Harvester ISO version: v1.0.1-rc1
 - Underlying Infrastructure: **bare-metal** Dell PowerEdge R720

**Additional context**
When image is uploaded you can see that it persists to the disk on the host `/dev/sda` at 546MB the same size as the `ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img` that was uploaded.  It is persisting the image to that disk but the disk itself doesn't have any replicas in Longhorn.
It can be noticed that we do have tests that cover both "1" and "3" replicas:
https://github.com/futuretea/harvester/blob/218dfd23449a2b393e20ac80a40a0072f970cad6/pkg/webhook/resources/virtualmachineimage/mutator_test.go#L49-L80

**Supporting Screenshots**

![Screenshot from 2022-09-23 15-53-59](https://user-images.githubusercontent.com/5370752/192072836-c6fe81c8-e645-4e14-9b04-dc59bacc6f7d.png)
![disk-with-storage-class](https://user-images.githubusercontent.com/5370752/192072840-ddba55b4-f2d7-4eda-aacb-99ea43d5c254.png)
![Screenshot from 2022-09-23 15-27-37](https://user-images.githubusercontent.com/5370752/192072842-e3cc2529-3393-4baf-a232-4789f20cf1d7.png)
![Screenshot from 2022-09-23 14-53-41](https://user-images.githubusercontent.com/5370752/192072844-0ca8442d-0eb3-4e07-a136-44a99e837efa.png)
![Screenshot from 2022-09-23 14-41-48](https://user-images.githubusercontent.com/5370752/192072846-d3376882-3596-40e6-b13d-d44ece180159.png)

**Comment by futuretea** [comment]
@irishgordo 
The number of replicas on a disk is the sum of the volume replicas that are currently scheduled to the disk

**Comment by irishgordo** [comment]
@futuretea thanks for looking at this :smile: ! 
So all that happens when replicas are set for the StorageClass is that it just makes sure that any Volumes created using that StorageClass have "N" number of replicas in Longhorn?

**Comment by futuretea** [comment]
> @futuretea thanks for looking at this 😄 ! So all that happens when replicas are set for the StorageClass is that it just makes sure that any Volumes created using that StorageClass have "N" number of replicas in Longhorn?

Yes

**Comment by irishgordo** [comment]
@futuretea - thanks for helping me understand that.
Given that is the case, I'll go ahead and close this out as this isn't a bug :smile:
