### ISSUE TITLE
[FEATURE] Add more checks before upgrading

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2833]
**Is your feature request related to a problem? Please describe.**

We need to add some webhook validation checks to forbid users from performing upgrades in some cases.
This gives the user a smooth upgrade experience and ensures data reliability. 

Related issue: https://github.com/harvester/harvester/issues/2741

**Describe the solution you'd like**

Add a validation webhook and reject creating an upgrade if:
- There is any degraded volume (when node count >= 3).
- Node space is not enough. We need ~25GB of free space to preload images.

Add a validation webhook to reject deleting upgrades if
- CAPI cluster is under-provisioning. This is controlled by Rancher, and we should not start over an upgrade again.
  - `kubectl get clusters.cluster.x-k8s.io/local -n fleet-local`
  - Add an exception if there is a special annotation on upgrade to skip.

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
Note, so far, we can't find a way to detect free space in root fs. We can see if this can be done.

**Comment by noahgildersleeve** [comment]
Is this being implemented in v1.1.0? If so would the testing path be for us to simulate an upgrade from v1.1.0 to another version? Mostly I'm asking if this will work in an upgrade from v1.0.3 to v1.1.0. CC @FrankYang0529

**Comment by bk201** [comment]
@noahgildersleeve Yes, The feature will only appear in new v1.1.0 cluster. It doesn't exist in v1.0.3.

**Comment by noahgildersleeve** [comment]
Tested the degraded volume functionality in `v1.1.0-rc2` with an upgrade to the same version `v1.1.0-rc2`. 

## Verification Steps

1. Create an upgrade version.yaml and upload the ISO as outlined [here](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade)
2. Before running the upgrade navigate to the Longhorn UI at `https://<harvesterIp>/dashboard/c/local/longhorn`
![Screenshot_20221011_152637](https://user-images.githubusercontent.com/83787952/195209777-44287fc3-ba9c-4b00-bb3b-6e85cf3c040f.png)
3. Navigate to the volume tab then open one of the volumes. 
![Screenshot_20221011_152544](https://user-images.githubusercontent.com/83787952/195209854-6157273b-9305-49c1-a8bc-bfc9d2c63972.png)
![Screenshot_20221011_152554](https://user-images.githubusercontent.com/83787952/195209861-0f635d36-ea2a-439c-842a-7cc6244f3d5f.png)
4. Delete one of the volumes
![Screenshot_20221011_152605](https://user-images.githubusercontent.com/83787952/195209896-2c116802-eb54-4e1d-bc9e-d87d777ceaf8.png)
5. Try to run the upgrade

### Expected Results
- You should get an error that the volume is degraded and the upgrade shouldn't run
![Screenshot_20221011_152245](https://user-images.githubusercontent.com/83787952/195210007-c027cd68-ff93-4327-b070-31a727047ece.png)

**Comment by noahgildersleeve** [comment]
I checked and we are moving part of this ticket into another ticket

> Node space is not enough. We need ~25GB of free space to preload images.

I'm creating a new ticket [here](https://github.com/harvester/harvester/issues/2935) to track it and closing this ticket as complete.

**Comment by w13915984028** [comment]
Question:

We are targeting v1.0.3 to v1.1.0/v1.1.1 upgrade, how can such check be effective in v1.0.3 version ?  should the ugprade script itself checks such condition in the very beginning of upgrade, fail asap, to avoid the upgrade stucking in middle state ?
