### ISSUE TITLE
[Doc] Documentation missing: how to deal with volumes?

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#2838]
**Describe the bug**
The documentation seems to be missing explanations on how to deal with volumes in harvester.

**To Reproduce**
Try to find out 

- what this does:

![grafik](https://user-images.githubusercontent.com/13362573/192485960-08d0cf04-e06e-49a5-b972-9a26073301df.png)

- Find out in the documentation that online expansion of existing volumes is not possible.
- Find out how to deal with left over / orphaned volumes (i.e. deleted RKE2 downstream cluster that had CSI)
- more?

**Expected behavior**
We should have a chapter that explains how to deal with volumes in harvester.
How to verify that they have three replicas.
How to export / download images.. how to backup and restore volumes (not only VMs).
Maybe how to create snapshots?

**Environment**
 - Harvester ISO version: 1.0.3

**Comment by futuretea** [comment]
@Martin-Weiss Added Volume docs in v1.1 https://docs.harvesterhci.io/v1.1/volume/create-volume/
![image](https://user-images.githubusercontent.com/15064560/201573983-b4ddc5fc-e5c1-442d-88c8-7458081438cf.png)

**Comment by Martin-Weiss** [comment]
Thanks! Where can we see the replication / health status and is it supported to change the storage class on an existing volume (i.e. to move the volume from SSD to HDD or the other way)?

**Comment by futuretea** [comment]
> Where can we see the replication / health status?

Only in longhorn UI https://docs.harvesterhci.io/v1.1/troubleshooting/harvester#access-embedded-longhorn

>  is it supported to change the storage class on an existing volume?

image volumes -> no support
other volumes -> supported by:
1. take volume snapshot
2. using other storageclasses to restore the snapshot https://docs.harvesterhci.io/v1.1/volume/volume-snapshots#restore-a-new-volume-using-volume-snapshot

**Comment by Martin-Weiss** [comment]
@futuretea  - thanks for the feedback! Could you add this info also to the Volumes docs section? Thanks!!

**Comment by futuretea** [comment]
> @futuretea - thanks for the feedback! Could you add this info also to the Volumes docs section? Thanks!!

OK
