### ISSUE TITLE
Fail to import ssh key from github

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#284]
**version:**
master(881bed33a68bac90066b28bc660c87d971ae9274)

**Steps to reproduce:**
1. Install by ISO image
2. Add SSH key URL

**Result:**
![image](https://user-images.githubusercontent.com/5697937/100987242-37ecf580-3589-11eb-845a-ae1f6786823f.png)

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester-installer/pull/12

**Comment by futuretea** [comment]
Validated
