### ISSUE TITLE
[FEATURE] Allow users to enable/disable vm-import on demand

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2845]
**Is your feature request related to a problem? Please describe.**
Should allow users to enable/disable vm-import and pci-device on demand

**Describe the solution you'd like**
- Allow users to enable/disable vm-import and pci-devices feature on demand
- Support configuring exposed parameters only via the UI.

**Describe alternatives you've considered**
N/A
**Additional context**

**Comment by irishgordo** [comment]
@ibrokethecloud following the test plan that you documented here:

https://github.com/harvester/harvester/pull/2829#issue-1385380724

I see no issues, this all looks good :smile: !

I also noted that the Harvester instance did see an increase in system load etc, as it was working to bring in the addons, that then subsided afterwards.

Validating your tests, is there other elements that we should be auditing when looking at this?
If there isn't I'd feel comfortable closing this out.

Tested in: qemu/kvm
Harvester Version: v1.1.0-rc2

![Screenshot from 2022-10-06 15-27-50](https://user-images.githubusercontent.com/5370752/194430346-3fc7ff5a-caf9-4b71-8460-b8d4fd5b9e1c.png)

**Comment by ibrokethecloud** [comment]
@irishgordo there is not much else to do yet. For now it should only enable and disable the addons to allow users to save resources when said addon is not needed.

**Comment by irishgordo** [comment]
@ibrokethecloud that sounds good to me!
It all checked out :smile: .
I also like the idea behind it, allowing users to save resources when it isn't needed.

**Comment by guangbochen** [comment]
reopen this for UI changes, cc @n313893254

**Comment by WuJun2016** [comment]
Hi, @ibrokethecloud  The addon function for UI has been completed, here are some test steps, can you help to see if there is anything to add ?   thanks https://github.com/harvester/dashboard/pull/465#issue-1402917555

cc @irishgordo

**Comment by irishgordo** [comment]
@WuJun2016  -as I've been testing this - I happened to notice this and opened:
https://github.com/harvester/harvester/issues/2948

**Comment by irishgordo** [comment]
@WuJun2016 I validated that aside from #2948 
Everything else checks out :smile: 
I can import a VM once it's turned on from OpenStack.
I can use a custom storage class PVC - and it seems to be using that for the backing-image and pvc.
![Screenshot from 2022-10-14 14-03-21](https://user-images.githubusercontent.com/5370752/195944463-18a92b64-5663-4583-98a4-040751ad1755.png)
![Screenshot from 2022-10-14 14-01-50](https://user-images.githubusercontent.com/5370752/195944465-3387de40-469d-4a0f-93d7-04944572b5f9.png)
![Screenshot from 2022-10-14 13-51-55](https://user-images.githubusercontent.com/5370752/195944466-3ca95109-45b4-467c-8987-bfa5047ed82c.png)
![Screenshot from 2022-10-14 13-51-37](https://user-images.githubusercontent.com/5370752/195944467-6b025145-79c4-4f3a-840d-a3a87538c5ec.png)
![Screenshot from 2022-10-14 13-41-49](https://user-images.githubusercontent.com/5370752/195944468-e59c2085-5afa-4473-8b13-b6ca7fb96d3d.png)
![Screenshot from 2022-10-14 13-39-48](https://user-images.githubusercontent.com/5370752/195944469-274dcefc-a66f-45be-8171-c434874fddff.png)
