### ISSUE TITLE
[FEATURE] Dedicated storage network configuration guide

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2846]
**Is your feature request related to a problem? Please describe.**

We'll have a dedicated storage network feature in v1.1.0, before https://github.com/harvester/harvester/pull/2706 is done, we need a guide to tell users how to enable it.

**Describe the solution you'd like**

Create a guide in the Harvester doc.

**Describe alternatives you've considered**

**Additional context**

Related issue: https://github.com/harvester/harvester/issues/1055

**Comment by bk201** [comment]
Close this since we have the controller. We can use this as a reference in the future.
@tjjh89017 Could you mention this [PR](https://github.com/harvester/docs/pull/197) in the HEP? Thanks.

**Comment by tjjh89017** [comment]
Update HEP
mentioned [PR](https://github.com/harvester/docs/pull/197) in HEP
