### ISSUE TITLE
[BUG] Bump embedded Rancher to v2.6.9

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2847]
**Describe the bug**

We need to bump the embedded Rancher to v2.6.9.

Known issues:
- [ ] ~~(v2.6.9-rc2) https://github.com/rancher/rancher/issues/39167~~ Tacked in https://github.com/harvester/harvester/issues/2872

**Comment by bk201** [comment]
Alone with https://github.com/harvester/harvester/issues/2785, the test plan is to verify versions of master ISO:
- Rancher: v2.6.9-rc3
- RKE2: v1.24.6+rke2r1

**Comment by noahgildersleeve** [comment]
Tested in `master-75876dee-head`. 

## Verification steps

1. Deploy Harvester node from master
2. SSH into node
3. get versions of RKE and embedded rancher from `kubectl`

### Expected Results

Versions match 
- Rancher: v2.6.9-rc3
- RKE2: v1.24.6+rke2r1

![Greenshot 2022-10-04 13 17 51](https://user-images.githubusercontent.com/83787952/193918487-b2a70b3c-aa61-4526-92d6-e22ad62a5bb5.png)
![Greenshot 2022-10-04 13 15 54](https://user-images.githubusercontent.com/83787952/193918495-05ab3601-9616-48ba-a20c-9e382d299593.png)
