### ISSUE TITLE
[BUG] Virt-Launcher Pods Hung in "ContainerCreating" State While Spinning Multiple Instances On Custom StorageClass

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2854]
**Describe the bug**
On a custom StorageClass, launching a "Multi Instance" collection of VMs launched from VM Template - get hung in "ContainerCreating" state and never provision, 30+ min waiting for state to change, doesn't happen.  Discovered while testing: https://github.com/harvester/harvester/issues/2147

**To Reproduce**
1. Build a 3 Node Harvester Cluster
1. On each host, edit each host to have a unique "Host Tag", like `top`, `middle`, `bottom`
1. On each host, edit the main disk to have the `Disk Tags` of "main"
1. Build a VLAN, using the `mgmt` Network Config cluster, with VLAN ID of 1
1. Create a Storage Class, call it something unique like: `main-sc` , Provisioner Longhorn, Number of Replicas: 3, Stale Replica Timeout: 30, Disk Selector: main, Migratable: Yes, Node Selector: (top, middle, bottom)
1. Upload an image, select your `main-sc` storage class (or whatever you named the storage class)
1. Goto Advanced -> Templates, build a template, using the image, and mgmt vlan
1. Virtual Machine -> Create -> Multiple Instance, count 4, check Use VM Template, select the template, click create

**Expected behavior**
Multiple Instances get provisioned instead of being stuck in ContainerCreating State

**Support bundle**
[supportbundle_bae67098-bc85-4bb1-a4ff-ac36530988a9_2022-09-29T22-09-25Z.zip](https://github.com/harvester/harvester/files/9679414/supportbundle_bae67098-bc85-4bb1-a4ff-ac36530988a9_2022-09-29T22-09-25Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc1
 - Underlying Infrastructure Baremetal: ThinkCentre 3 node cluster 8C 16GB Mem 350GB disk each

**Additional context**
![Screenshot from 2022-09-29 15-26-47](https://user-images.githubusercontent.com/5370752/193153509-b5fd1973-50cd-45f8-b56e-dc4147d5721f.png)
![Screenshot from 2022-09-29 15-24-12](https://user-images.githubusercontent.com/5370752/193153512-92dff96e-c0e7-4bb6-9c17-b1843c7850ea.png)
![Screenshot from 2022-09-29 15-20-59](https://user-images.githubusercontent.com/5370752/193153513-95c8167c-c9a8-4fb2-8a37-0346a90ba200.png)
![Screenshot from 2022-09-29 15-14-35](https://user-images.githubusercontent.com/5370752/193153515-ae4db1b8-5d48-420b-aff9-bdf5ce797208.png)
![Screenshot from 2022-09-29 15-10-42](https://user-images.githubusercontent.com/5370752/193153516-a13960d3-7a93-4253-937c-9f554d4dc356.png)

**Comment by irishgordo** [comment]
I'm able to consistently reproduce this so I will be changing this from `reproduce/often` to `reproduce/always`


https://user-images.githubusercontent.com/5370752/193156031-22ab5f89-0520-4cc9-9e19-956eb7cd9c87.mp4


I only recorded the video for a small amount of time, but they follow the same pattern of hanging in their state indefinitely

**Comment by irishgordo** [comment]
It looks as if all of their pvc's that were created successfully but are detached seem to have a "replica scheduling failed" error
![Screenshot from 2022-09-29 19-34-53](https://user-images.githubusercontent.com/5370752/193177938-5fef105c-98c4-40ed-aa4c-5093420729d0.png)

**Comment by futuretea** [comment]
refer to https://longhorn.io/docs/1.3.1/volumes-and-nodes/storage-tags/#usage

When multiple tags are specified for a volume, the disk and the node (the disk belong to) must have all the specified tags to become usable.

**Comment by irishgordo** [comment]
@futuretea thanks for that link!

So just to validate:
```
kubectl --kubeconfig ~/.kube/thinkcentre_cluster.yaml describe storageclass main-sc           
Name:                  main-sc
IsDefaultClass:        No
Annotations:           field.cattle.io/description=main
Provisioner:           driver.longhorn.io
Parameters:            diskSelector=main,migratable=true,nodeSelector=top,bottom,middle,numberOfReplicas=3,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
```

"Node Selector" in the Parameters is would look to find a Node that had the tags of: "top" && "bottom" && "middle" - to evaluate to be Truthy
It's behavior _would not_ be to look for a Node that had:
"top" || "bottom" || "middle"

I think this is making more sense now.
I apologize as I didn't know that was the behavior of Longhorn :sweat_smile: 

Thanks for helping me understand this better - I will go ahead and close this out, as this is a user error on my end when building the StorageClass and is not an issue with the functionality of the StorageClass itself :smile:
