### ISSUE TITLE
[BUG]Integrate clone volume dialog

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2855]
**Describe the bug**

**To Reproduce**

1. Go to Volume list
2. Click menu action
3. You'll see both of `Clone Volume` and `Clone`
![image (3).png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/e69faf13-3176-47b9-a55e-51237c0aebae)

**Expected behavior**

It's expected to integrate that two action like below.
![image.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/77a96c9e-0302-4055-9dc1-7cea8335e741)

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
close as resolved.

![image](https://user-images.githubusercontent.com/5169694/195351832-78ed46ca-91f9-413e-945c-f391e4124fd6.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-937f333c-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2855#issue-1391947204
