### ISSUE TITLE
[FEATURE] Display detailed info in volumes page

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2856]
**Is your feature request related to a problem? Please describe.**

Users need to access Longhorn GUI to see volumes' state.

**Describe the solution you'd like**

It would be nice to expose volumes' state in Harvester GUI.

We can't tell if a volume is degraded in Harvester GUI:
<img width="713" alt="Screen Shot 2022-09-30 at 11 34 47 PM" src="https://user-images.githubusercontent.com/1691518/193306108-40320e68-3b00-4bdf-82ab-969293dbbe04.png">

There is more helpful info in Longhorn GUI. The GUI contains `state`, `size`, and `actual size`.
<img width="590" alt="Screen Shot 2022-09-30 at 11 35 04 PM" src="https://user-images.githubusercontent.com/1691518/193306153-f26c4e92-e903-442c-b7ca-717be82c510f.png">

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **Baremetal DL360 3 nodes**
* Harvester Version: **v1.2.0-rc1**
* **ui-source** Option: **External**

### Verify Steps
1. Install Harvester with any nodes
2. Follow https://github.com/harvester/dashboard/pull/735#issue-1721635040
