### ISSUE TITLE
[BUG] Terraform created networks with DHCP fails on apply after DHCP-network is registered in terraform

### ISSUE THREAD

**Issue by nerok** [harvester/harvester#2857]
**Describe the bug**
I created multiple networks with the harvester_network resource, some with static addressing and some with dynamic addressing(DHCP). On initial creation all worked, they all use the same module. After some minutes the networks which has a DHCP-server began to fail on terraform apply with a message saying that route_mode "auto" can't be used when route_cidr is defined. When checking the state I see that the DHCP lease is present in the route_cidr, and I can't seem to bypass sending the value.

**To Reproduce**
1. Create a terraform definition for a Harvester which has a vlan containing a DHCP-server
2. Create a network definition for the vlan using harvester_network resource.
3. Wait for harvester to pick up a DHCP-lease
4. Apply any change to the network resource (description change for instance).

**Expected behavior**
Terraform changes what ever change is planned in 4.

**Support bundle**
I can create one if need be and pass it on to a developer

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Dell PowerEdge R730, Juniper routers and LACP (802.3ad) redundant uplink

**Additional context**
I think this feature-issue is related to my issue: https://github.com/harvester/harvester/issues/2261

**Comment by futuretea** [comment]
@nerok you can try the latest terraform-provider-harvester v0.5.3 for Harvester v1.0.3 or  terraform-provider-harvester v0.6.0for Harvester v1.1.0

**Comment by nerok** [comment]
Hi, we are using 0.5.3 already on v1.0.3. Can't test v0.6.0 as we are waiting for v1.1.1 before upgrading, and we don't have any test clusters yet.

**Comment by futuretea** [comment]
> Hi, we are using 0.5.3 already on v1.0.3. Can't test v0.6.0 as we are waiting for v1.1.1 before upgrading, and we don't have any test clusters yet.

Thanks, I'll try to reproduce and fix this issue

**Comment by futuretea** [comment]
@nerok workaround: If you can, leave the `route_dhcp_server_ip` to empty.

**Comment by nerok** [comment]
Thanks, I can't seem to get that to work:
```terraform
resource "harvester_network" "network" {
  name                 = var.network_name
  namespace            = "harvester-public"
  route_cidr           = null
  route_dhcp_server_ip = ""
  route_mode           = "auto"
  vlan_id              = var.network_vlan
  description          = var.network_description
  tags                 = var.network_tags
}
```
I have tested both route_cidrand route_dhcp_server_ip as bot empty string and null, I also tried removing route_cidr, but it always returns:
```
│ Error: can not use route_mode auto when route_cidr has been specified
│ 
│   with module.networks["vlan760"].harvester_network.network,
│   on common/networks/main.tf line 15, in resource "harvester_network" "network":
│   15: resource "harvester_network" "network" {
│ 
```

**Comment by futuretea** [comment]
The route_dhcp_server_ip needs to be left empty before the first apply

**Comment by TachunLin** [comment]
Verified **fixed** on harvester-terraform provider `master` with Harvester `v1.1.1`. Close this issue.

### Result
1. We can set `route_mode = "auto"` and also specify the `route_dhcp_server_ip` to apply the network resource correctly. 
  (Use v1.1.0 cluster network feature)
  ```
  resource "harvester_network" "mgmt-vlan1" {
    name      = "mgmt-vlan1"
    namespace = "default"
    description = ""
  
    vlan_id = 1
  
    route_mode           = "auto"
    route_dhcp_server_ip = "192.168.122.1"
  
    cluster_network_name = "mgmt"
  }
  ```
![image](https://user-images.githubusercontent.com/29251855/207499278-8aa402d2-5274-4186-af70-d52ae04df109.png)

2. And we can also edit the description and apply again 

  ```
  c0e03db26271:/data # terraform apply -auto-approve
  harvester_network.mgmt-vlan1: Refreshing state... [id=default/mgmt-vlan1]
  
  Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
    ~ update in-place
  
  Terraform will perform the following actions:
  
    # harvester_network.mgmt-vlan1 will be updated in-place
    ~ resource "harvester_network" "mgmt-vlan1" {
        + description          = "test"
          id                   = "default/mgmt-vlan1"
          name                 = "mgmt-vlan1"
          tags                 = {}
          # (6 unchanged attributes hidden)
      }
  
  Plan: 0 to add, 1 to change, 0 to destroy.
  harvester_network.mgmt-vlan1: Modifying... [id=default/mgmt-vlan1]
  harvester_network.mgmt-vlan1: Modifications complete after 1s [id=default/mgmt-vlan1]
  
  Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
  
  ```
  ![image](https://user-images.githubusercontent.com/29251855/207786372-d00f5185-044e-4a59-a0aa-0c2305b3b91f.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.1.1
* Terraform version: master 

### Verify Steps
1. Prepare Harvester cluster 
2. ssh to Harvester and get kubeconfig content in `/etc/rancher/rke2/rke2.yaml` 
3. Copy the content to host machine ~/.kube/config 
4. Update the `server:` to harvester management ip
5. Run the following command to startup a terraform-provider container 
  ```
  docker pull rancher/terraform-provider-harvester:master-head-amd64
  docker rm -f terraform-provider-harvester-master-head
  docker run -itd --name terraform-provider-harvester-master-head rancher/terraform-provider-harvester:master-head-amd64 bash
  docker cp ~/.kube/config terraform-provider-harvester-master-head:/tmp/kubeconfig
  docker exec -it terraform-provider-harvester-master-head bash
  ```
6. (optional) install kubectl on terraform-provider container follow the [instruction](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)

7. Check the connectivity to Harvester cluster 
  ```
  kubectl --kubeconfig=/tmp/kubeconfig get no
  ```
8. vim `providers.tf` , add the following content 
  ```
  terraform {
    required_providers {
      harvester = {
        source = "harvester/harvester"
        version = "0.0.0-master"
      }
    }
  }
  
  provider "harvester" {
    kubeconfig = "/tmp/kubeconfig"
  }
  ```
9. Run `terraform init` to initialize it.
10. Create a test config file `vim main.tf`
11. Add resource harvester_network with route_mode = "auto" and route_dhcp_server_ip = "<replace to your dhcp server>"

  ```
  resource "harvester_network" "mgmt-vlan1" {
    name      = "mgmt-vlan1"
    namespace = "default"
    description = ""
  
    vlan_id = 1
  
    route_mode           = "auto"
    route_dhcp_server_ip = "192.168.122.1"
  
    cluster_network_name = "mgmt"
  }
  
  ```
12. Apply the resource `terraform apply -auto-approve` 
  ```
  c0e03db26271:/data # terraform apply -auto-approve
  
  Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
    + create
  
  Terraform will perform the following actions:
  
    # harvester_network.mgmt-vlan1 will be created
    + resource "harvester_network" "mgmt-vlan1" {
        + cluster_network_name = "mgmt"
        + config               = (known after apply)
        + id                   = (known after apply)
        + message              = (known after apply)
        + name                 = "mgmt-vlan1"
        + namespace            = "default"
        + route_cidr           = (known after apply)
        + route_connectivity   = (known after apply)
        + route_dhcp_server_ip = "192.168.122.1"
        + route_gateway        = (known after apply)
        + route_mode           = "auto"
        + state                = (known after apply)
        + vlan_id              = 1
      }
  
  Plan: 1 to add, 0 to change, 0 to destroy.
  harvester_network.mgmt-vlan1: Creating...
  harvester_network.mgmt-vlan1: Creation complete after 1s [id=default/mgmt-vlan1]
  
  Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
  ```
13. Edit the main.tf, update the description 
14. Apply the resource again `terraform apply -auto-approve`

**Comment by TachunLin** [comment]
For the issue introduced in v1.0.3, we would track in #3284 accordingly.
