### ISSUE TITLE
[BUG] Container VM Fails to Create

### ISSUE THREAD

**Issue by joelmacklow** [harvester/harvester#2858]
**Describe the bug**
When creating a VM wiht the Volume type of Container and choosing a docker hub image (e.g. caddy) the VM creation process starts but fails with the following error:
`Failed to find a sourceFile in containerDisk disk-1: Failed to check /proc/1/root/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/6c772a1b10b8843aee4591f3026a721d1251a166142f4f71f34c96dd201aa696/rootfs/disk for disks: open /proc/1/root/run/k3s/containerd/io.containerd.runtime.v2.task/k8s.io/6c772a1b10b8843aee4591f3026a721d1251a166142f4f71f34c96dd201aa696/rootfs/disk: no such file or directory`

**To Reproduce**
1. Create a new VM with CPU and RAM allocation
2. Select Volumes tab.
3. Click "Add Container"
4. Specify caddy in the Docker Image field
5. Create VM

**Expected behavior**
I expected the container to start and download the image from the docker hub and then run

**Support bundle**
Support bundle to be generated. Also posted in Slack on #harvester

**Environment**
 - Harvester ISO version: 1.0.3
 - Baremetal install on Intel NUC.

**Comment by w13915984028** [comment]
@FrankYang0529 please take a look, thanks.

**Comment by futuretea** [comment]
@joelmacklow  refer to https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example

`Disks must be placed into the /disk directory inside the container. Raw and qcow2 formats are supported.`

**Comment by w13915984028** [comment]
@joelmacklow We will close this issue. Fell free to reopen when you needs more help, thanks.
