### ISSUE TITLE
[BUG] Unable to create vlan network on default `mgmt` cluster network on Networks page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2861]
**Describe the bug**

When we try to create the `vlan1` network with vlan id: `1` on Networks page, can't select the default `mgmt` cluster network 
The option is grayed out.
![image](https://user-images.githubusercontent.com/29251855/193517830-306fb81d-bd08-4f7e-ac2d-d8d72b5943c7.png)

Thus can't proceed to create vlan
![image](https://user-images.githubusercontent.com/29251855/193520340-e2532ccb-ad1e-4bde-afcf-ab7bd1f769af.png)

The default cluster network
![image](https://user-images.githubusercontent.com/29251855/193515900-21950523-1f84-4623-a712-5d50aec6d16c.png)

We did not provide any VLAN ID (empty) during the ISO installer console
![image](https://user-images.githubusercontent.com/29251855/193491326-551c5a81-ef62-4834-9403-ceddc93d1a87.png)

**To Reproduce**
1. ISO install Harvester
2. Leave VLAN ID empty 
3. Use DHCP node and VIP configuration
4. Complete the installation
5. Create a vlan in Networks page 
6. Create vlan named `vlan1` and id `1`
7. Select the Cluster Network dropdown

**Expected behavior**

Should be able to create vlan on the default mgmt cluster network

**Support bundle**

[supportbundle_f2b4368d-ceb4-4e1b-94e7-d3b86e21b150_2022-10-03T07-15-23Z.zip](https://github.com/harvester/harvester/files/9695383/supportbundle_f2b4368d-ceb4-4e1b-94e7-d3b86e21b150_2022-10-03T07-15-23Z.zip)

**Environment**
 - Harvester ISO version: `master-6dc3fc77-head` (09/30)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 node Harvester on local kvm machine

**Additional context**
Please feel free to correct if it's the expected behavior of the new feature enhancement

**Comment by bk201** [comment]
I guess this is intentional to avoid the failing route issue. @yaocw2020 @tjjh89017 Could you take a look?

**Comment by guangbochen** [comment]
@TachunLin can u please validate it again using Harvester v1.1.0-rc2, thanks.

**Comment by TachunLin** [comment]
This issue can't be reproduced and have been fixed on `v1.1.0-rc2`, now we can create vlan1 network on `mgmt` cluster network
![image](https://user-images.githubusercontent.com/29251855/195109313-1afa9865-1a2d-4cd0-bcc2-40a3d4624242.png)

**Comment by bk201** [comment]
@TachunLin Feel free to reopen if you see this again. Thanks.
