### ISSUE TITLE
[BUG] First Volume (disk-0) on VirtualMachineImport Resource Goes Missing - Doesnt Allow For VM To Be Modified After Import

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2864]
**Describe the bug**
The first volume associated with the `VirtualMachineImport` of an OpenStack resource, goes missing from GUI.

**To Reproduce**
1. Create a `VirtualMachineImport` for a device that has one or two volumes. 
1. Import the VM (either openstack or vsphere).
1. View the VM starting up and running - head to the Volumes section of the VM, notice that the 'Volume' under 'disk-0' is empty
1. Try to edit to add an SSH Key for instance, you will see something like: `volume disk-0: "Volume" is required!` 
1. Try to add a Disk, you'll see something like: `volume disk-0: "Volume" is required!` 
1. Try to adjust / modify CPU / Memory, you'll see the error of: `volume disk-0: "Volume" is required!` 

**Expected behavior**
That the volume under `disk-0` would not be empty
I believe this may be front-end only due to noticing that the claim name is present in an API call out like:
`https://your_vip_ip/v1/harvester/kubevirt.io.virtualmachine/default/6db2da60-813b-4bb6-96ac-46c85c1bc522?mode=edit#Volume`

**Support bundle**
[supportbundle_287fe6a4-7974-4609-983a-4a61acd31a78_2022-10-04T00-30-40Z.zip](https://github.com/harvester/harvester/files/9701922/supportbundle_287fe6a4-7974-4609-983a-4a61acd31a78_2022-10-04T00-30-40Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc1
 - Underlying Infrastructure: qemu/kvm

**Additional context**

![Screenshot from 2022-10-03 17-31-59](https://user-images.githubusercontent.com/5370752/193710472-d21ccff3-9e1c-4db1-bce2-aa28a5b2a852.png)
![Screenshot from 2022-10-03 17-23-40](https://user-images.githubusercontent.com/5370752/193710476-12e359d6-b8f0-4820-b5b2-eaf85da08182.png)
![Screenshot from 2022-10-03 17-23-09](https://user-images.githubusercontent.com/5370752/193710478-691fe937-b2ac-497e-93eb-91f38f170503.png)
![volumes-exist](https://user-images.githubusercontent.com/5370752/193710480-15733a96-856c-4251-b19e-73093f5c6442.png)
![volume-is-missing](https://user-images.githubusercontent.com/5370752/193710482-b136e97a-121b-4ccc-a2d7-6db843c469d3.png)
![Screenshot from 2022-10-03 17-19-01](https://user-images.githubusercontent.com/5370752/193710483-0c3bab95-895a-40e7-8bea-aedd024953fa.png)

**Comment by irishgordo** [comment]
Still noticing this on Harvester Version: master-61a6124a-head 

cc: @ibrokethecloud

**Comment by irishgordo** [comment]
![Screenshot from 2022-10-14 14-24-59](https://user-images.githubusercontent.com/5370752/195946423-070e18ae-54b4-46fe-be6c-f26c9b2605b2.png)

**Comment by irishgordo** [comment]
![Screenshot from 2022-10-14 14-53-47](https://user-images.githubusercontent.com/5370752/195949752-cef29751-b924-43e8-9e93-562ea6440d98.png)
I validated with a new vm running Harvester Version: master-61a6124a-head
Against another OpenStack enviornment, instead of my homelab openstack, OpenStack in the DC

**Comment by irishgordo** [comment]
This is effecting both:
- OpenStack, version stable/train , their VM imports
- vSphere/VMWare, version 6.8, their VM imports

[supportbundle_a97aaa7b-153a-40fb-87f0-c0745d6d4a24_2022-10-14T22-03-18Z.zip](https://github.com/harvester/harvester/files/9790415/supportbundle_a97aaa7b-153a-40fb-87f0-c0745d6d4a24_2022-10-14T22-03-18Z.zip)

![Screenshot from 2022-10-14 15-02-31](https://user-images.githubusercontent.com/5370752/195950880-b51fb3a5-a2ca-4b26-8294-0f6ae7d3bd70.png)

Validated again on Harvester Version: master-61a6124a-head

cc: @ibrokethecloud

**Comment by irishgordo** [comment]
I believe this is UI related, as I can with kubectl, edit the virtualmachine, changing the Cpu.(cores|sockets|threads) and the limits.cpu & limits.memory for instance - persist those changes and then reboot the VM and it shows.
![Screenshot from 2022-10-14 18-04-10](https://user-images.githubusercontent.com/5370752/195962177-9cacb000-c60b-4197-b50f-6d19a160f904.png)

But that's by editing the VM through kubectl, not through the UI in order to get the changes to persist.

**Comment by irishgordo** [comment]
I'm not sure if the severity should be decreased - but we could change it possibly - because it is possible to make changes to the VM through `kubectl` as a "workaround" so to say - just the UI is limiting at this point

**Comment by ibrokethecloud** [comment]
This is being caused due to missing annotations the UI relies on. 

Fix is available now: https://github.com/harvester/vm-import-controller/pull/7

**Comment by irishgordo** [comment]
@ibrokethecloud thanks for the aweome fix!
Using: master-61a6124a-head 
Now with the annotations in this all looks good :smile: - I tested teh VMs could be edited in all sorts of ways.
Leveraging modifying the deployment:
- gmehta3/harvester-vm-import-controller:dev
- "Always" for image pull policy 
Both with OpenStack & vSphere.

![Screenshot from 2022-10-16 20-55-55](https://user-images.githubusercontent.com/5370752/196086620-9cdbc3ab-c706-4970-8a63-735a9fec4846.png)
![Screenshot from 2022-10-16 20-54-01](https://user-images.githubusercontent.com/5370752/196086626-c4a14fcf-925f-4ae8-8be7-930181414d96.png)
![Screenshot from 2022-10-16 20-52-05](https://user-images.githubusercontent.com/5370752/196086628-11d6e64d-ef64-4909-9ce1-27f92a53fc56.png)
![Screenshot from 2022-10-16 20-50-45](https://user-images.githubusercontent.com/5370752/196086634-ae8ee474-f1e4-46da-ac3f-e1095b6aa024.png)
![Screenshot from 2022-10-16 20-49-40](https://user-images.githubusercontent.com/5370752/196086636-5ef54fb4-5353-4eb3-9cf5-15dad1ec0629.png)

After https://github.com/harvester/vm-import-controller/pull/7 gets merged in - pending, there are not any sweeping code changes that alter the current flow from the testing I just ran 10/16/22, I would be comfortable closing this out.

**Comment by irishgordo** [comment]
@ibrokethecloud this looks great!
I went ahead and bumped the image to - `v0.1.1` and pull policy always - and it looks good!
![Screenshot from 2022-10-16 22-56-51](https://user-images.githubusercontent.com/5370752/196100042-b23e8a4e-93ee-4112-9100-16eef87ae9da.png)
I'll go head and close this out :smile:
