### ISSUE TITLE
[BUG] Upgrade: kube-apiserver is not ready after node reboots

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2865]
**Describe the bug**

RKE2 keeps displaying the log after a node is upgraded and rebooted.

```
Sep 29 10:23:39 node4 rke2[2050]: time="2022-09-29T10:23:39Z" level=info msg="Latest etcd manifest deployed"
Sep 29 10:23:39 node4 rke2[2050]: time="2022-09-29T10:23:39Z" level=info msg="kube-apiserver pod not found, retrying"
Sep 29 10:23:40 node4 rke2[2050]: time="2022-09-29T10:23:40Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 29 10:23:45 node4 rke2[2050]: time="2022-09-29T10:23:45Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 29 10:23:50 node4 rke2[2050]: time="2022-09-29T10:23:50Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 29 10:23:55 node4 rke2[2050]: time="2022-09-29T10:23:55Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Sep 29 10:23:59 node4 rke2[2050]: time="2022-09-29T10:23:59Z" level=info msg="Latest etcd manifest deployed"
```

**To Reproduce**
1. Upgrade Harvester from v1.0.3 to master code.
2. Once a controller node reboots, we can see these messages in its rke2-server log.
https://gist.githubusercontent.com/bk201/ea92100fb4c6d168ca8503f3c8cc0593/raw/3b2a87fe3acbf8a90a0497eb56f550ce88f7cccc/rke2-server.log

rke2-server will eventually timeout, and systemd will restart it. The kube-apiserver is healthy after restarting the service.

**Expected behavior**

kube-apiserver should be ready.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

- RKE2 thinks kube-apiserver is not ready.

  We saw the kube-apiserver static pod has a different `uid` from what's defined in its manifest (`/var/lib/rancher/rke2/agent/pod-manifests/kube-apiserver.yaml`).

  The manifest file seems to be generated after the static pod is started by kubelet (with a previous manifest).

  ```
  node3:~ # crictl ps | grep kube-api
  770c48d34db1c       0a5067ab04e9a       23 minutes ago      Running             kube-apiserver                  1                   
  a7fe4e2cf0adf       kube-apiserver-node3
  node3:~ # crictl inspect 770c48d34db1c | grep At
      "createdAt": "2022-10-03T08:06:32.110052642Z",
      "startedAt": "2022-10-03T08:06:32.439802516Z",
      "finishedAt": "0001-01-01T00:00:00Z",
  ```

  ```
  node3:/var/lib/rancher/rke2/agent/pod-manifests # stat kube-apiserver.yaml
    File: kube-apiserver.yaml
    Size: 8655      	Blocks: 24         IO Block: 4096   regular file
  Device: fd05h/64773d	Inode: 1318859     Links: 1
  Access: (0644/-rw-r--r--)  Uid: (    0/    root)   Gid: (    0/    root)
  Access: 2022-10-03 08:06:35.935490460 +0000
  Modify: 2022-10-03 08:06:35.795490460 +0000
  Change: 2022-10-03 08:06:35.799490460 +0000
  ```

- Different uid

  We installed a new package `ca-certificates` in the new OS images and directory `/etc/ca-certificates/` exists. This causes RKE2 generate a new uid:  https://github.com/rancher/rke2/blob/eb7a82f3070138cc8b2b2c9ed868789fa0f6d94b/pkg/podexecutor/staticpod.go#L281
  
  v1.24.x also counts the NODE_NAME (not quite sure if that's included in v1.22.x):
https://github.com/rancher/rke2/blob/eb7a82f3070138cc8b2b2c9ed868789fa0f6d94b/pkg/staticpod/staticpod.go#L100

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/196393001-c0dfebcc-3838-4f40-9eb0-1329ea3c36e3.png)


Test Information
----
* Environment: **baremetals DL360G9 4 nodes**
* Harvester Version: **v1.0.3** upgrade to **v1.1.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps:
- Same as https://harvester.github.io/tests/manual/_incoming/1707-zero-downtime-upgrade/
- check the rke2 log via `journalctl -u rke2-server`
