### ISSUE TITLE
[BUG] Upgrade: fail to start repo VM in single node case

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2867]
**Describe the bug**

In the single node upgrade case, there is a chance upgrade-repo VM can't start due to API not being ready.

**To Reproduce**
1. Upgrade v1.0.3 to master ISO.
2. In the upgrade-node job, we can see this failure:
```
+ local repo_vm_status
++ kubectl get virtualmachines.kubevirt.io upgrade-repo-hvst-upgrade-4q6hf -n harvester-system '-o=jsonpath={.status.printableStatus}'

Upgrade single node
+ repo_vm_status=Stopped
+ '[' Stopped '!=' Running ']'
+ virtctl start upgrade-repo-hvst-upgrade-4q6hf -n harvester-system
Error starting VirtualMachine the server is currently unable to handle the request
+ true
+ curl -sfL http://upgrade-repo-hvst-upgrade-4q6hf.harvester-system/harvester-iso/harvester-release.yaml
+ echo 'Wait for upgrade repo ready...'
+ sleep 5
```
3. The VM can be started with the `virtctl` command after a while.

**Expected behavior**

The upgrade repo VM should start to serve ISO contents.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/194038219-d50e0be0-043b-4496-999e-5835e00652c6.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.0.3** to **master-797245b6-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester `v1.0.3` with single node
2. Perform Upgrade to master-head via https://docs.harvesterhci.io/v1.0/upgrade/automatic#prepare-an-air-gapped-upgrade
3. Execute command as following to monitor status:
    - `kubectl get jobs -A | grep single-node-upgrade` (to check the _upgrade-node_ job applied)
    - `kubectl logs -fn harvester-system hvst-upgrade-<random_num>-single-node-upgrade-<node-name>`
4. When error message displayed after **Try to bring up the upgrade repo VM...**, it should retry after few seconds.
