### ISSUE TITLE
Unable to view users YAML on detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#287]
**Steps to reproduce:**
On the user detail page, toggle to YAML

**Result:** 
Unable to view YAML
![image](https://user-images.githubusercontent.com/57614736/100991649-35d96580-358e-11eb-9493-e9a5f5de3f9e.png)

**Comment by DaiYuzeng** [comment]
@guangbochen need to add the view api of user, thanks!

![截屏2020-12-04 下午1 36 32](https://user-images.githubusercontent.com/15041915/101126315-2e6d9700-3636-11eb-948c-02496b52ec3d.png)

**Comment by DoNotSayYes** [comment]
Validated
