### ISSUE TITLE
[Question] - Deleting First Node

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#2875]
Hi,

I see a few issues where people are trying to re-install the 1st node and there seems to be a few issues with the process currently.

My question is - is there a specific process if I want to remove the 1st node without reinstalling it?  Will I run into any issues?

Thanks!

**Comment by w13915984028** [comment]
Please check 

https://docs.harvesterhci.io/v1.0/host/#deleting-a-node

**Comment by w13915984028** [comment]
The detailed test steps about how to remove a node and how to add new / reinstall nodes.

https://github.com/harvester/harvester/issues/2665#issuecomment-1280711371

**Comment by RegisWeduLabs** [comment]
Thanks!

**Comment by w13915984028** [comment]
@RegisHubelia We will close this issue.

Feel free to re-open or fire new ones for any issues you encounter in the future, thanks.
