### ISSUE TITLE
[BUG] Prefilled Image Labels Do Not Render Values in UI

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2888]
**Describe the bug**
When creating Images for Harvester inside the "Labels" section, after selecting a file or URL to upload. 
Selecting the dropdown from:
- harvesterhci.io/os-type
- harvesterhci.io/image-type
The Values do not persist in the box.
Classes on the HTML elements do change.
But the values on those two specific pre-defined keys do not persist in the UI.

**To Reproduce**
1. Go to Images
1. Click Create
1. Fill out basic section
1. Head to Labels section
1. Attempt to select a:
- harvesterhci.io/os-type
- harvesterhci.io/image-type
1. Visually audit that the value selected from the drop-down does not persist in the UI
1. Add a regular label, with value, that will persist

**Expected behavior**
That a user would be able to select a value from the drop down for the labels of:
- harvesterhci.io/os-type
- harvesterhci.io/image-type
And that it would persist in the UI

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure: qemu/kvm & Dell PowerEdge R720
 - Firefox: v103
 - Chromium v106

**Additional context**
Tested in Chromium & Firefox.
Videos attached.

https://user-images.githubusercontent.com/5370752/194423237-d7d3391e-805e-4cc1-bd27-75dffa9862ce.mp4

https://user-images.githubusercontent.com/5370752/194423238-17e47e98-9ec3-4d72-ba1f-f3a8108d8df2.mp4

**Comment by khushboo-rancher** [comment]
Looks like this is ready for Testing, @WuJun2016 Can you confirm?

**Comment by WuJun2016** [comment]
@khushboo-rancher  Yes, It's ready for testing, I moved to `ready-for-testing`

**Comment by irishgordo** [comment]
@WuJun2016 thanks for the fix!
This looks great!
I validated on
 Harvester, ISO: master-39c2bb2a-head
 
 
![Screenshot from 2022-10-11 12-40-04](https://user-images.githubusercontent.com/5370752/195183650-28fa9375-cea4-47ea-a45e-b1e574f81f16.png)
![Screenshot from 2022-10-11 12-37-40](https://user-images.githubusercontent.com/5370752/195183651-eb7fa0c1-891d-4e52-9fd0-96faf6ed9fdd.png)

I'll go ahead and close this out :smile:
