### ISSUE TITLE
[BUG] Can't provision RKE2 cluster in Rancher

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2889]
**Describe the bug**

When you try to provision RKE2 in Rancher 
**To Reproduce**
1. Import Harvester into Rancher
2. Create cloud creds
3. Start to provision RKE2 cluster
4. Try to complete

**Expected behavior**
RKE2 should provision
**Support bundle**
[supportbundle_ba2138e2-7e7f-4493-acbb-16d3edd63195_2022-10-06T23-57-31Z.zip](https://github.com/harvester/harvester/files/9729328/supportbundle_ba2138e2-7e7f-4493-acbb-16d3edd63195_2022-10-06T23-57-31Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Rancher version: v2.6.9-rc3 on single node docker
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant ipxe-examples

**Additional context**
This seems to be working on RKE1. There is a 400 error on `https://192.168.0.50/k8s/clusters/c-m-d24lpbml/v1/harvester/kubeconfig` I'm attaching screenshots of the errors as well
![Screenshot_20221006_165443](https://user-images.githubusercontent.com/83787952/194439287-575a0a83-b2ca-4b60-97a9-cbac0cbbbba5.png)
![Screenshot_20221006_165338](https://user-images.githubusercontent.com/83787952/194439288-1986cecc-edb2-4452-b9cd-8d0c7613f0e5.png)
![Screenshot_20221006_165302](https://user-images.githubusercontent.com/83787952/194439289-2391fd6a-a45b-4c9e-9a3a-e8d2e9795dd5.png)

**Comment by khushboo-rancher** [comment]
@bk201 Do you think this could be a Rancher issue?

cc: @rebeccazzzz

**Comment by guangbochen** [comment]
could be related to https://github.com/rancher/dashboard/issues/7125, cc @n313893254

**Comment by futuretea** [comment]
refer to https://github.com/rancher/rancher/issues/37711#issuecomment-1126413928

**Comment by guangbochen** [comment]
@n313893254 can we show the kubeconfig error message more obviously on the UI, this will benefit non-developer users, thanks.

**Comment by guangbochen** [comment]
This is now fixed on the master-head version of the Harvester, to test the fix u can update the Harvester API image manually via `$ kubectl set image deployment harvester -n harvester-system apiserver=rancher/harvester:master-head`

**Comment by noahgildersleeve** [comment]
Tested in Rancher `v2.6.9-rc3` and Harvester `master-39c2bb2a-head`. Verified as fixed

## Verification Steps
1. Import Harvester into Rancher
2. Create cloud creds
3. Try to provision RKE2 cluster

### Expected Results

- RKE2 cluster should provision

![Screenshot_20221011_164154](https://user-images.githubusercontent.com/83787952/195218142-25ae86c1-dd01-45e4-83a8-4f1186d68a09.png)
![Screenshot_20221011_164146](https://user-images.githubusercontent.com/83787952/195218146-02f62db2-c9f9-46ff-817f-320bc2e4ed4f.png)
