### ISSUE TITLE
Setting list is not reflecting the changes

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#289]
**Steps to replicate:**
1. On the settings page, choose one of the settings and edit
2. Change anything editable, then save

**Result:**
The setting list is not reflecting the changes that have been made
![image](https://user-images.githubusercontent.com/57614736/100998770-e3507700-3596-11eb-9548-183e76f711ef.png)
![image](https://user-images.githubusercontent.com/57614736/100999124-50640c80-3597-11eb-98d0-f2154008d296.png)
![image](https://user-images.githubusercontent.com/57614736/100999084-43471d80-3597-11eb-84cd-b17d658afded.png)

**Comment by WuJun2016** [comment]
@DoNotSayYes  This is not a bug, we should show value instead of default, we will add edit form

**Comment by DoNotSayYes** [comment]
> @DoNotSayYes This is not a bug, we should show value instead of default, we will add edit form

That comes to a question, what if users do not add any custom value but only modify the default value, like the circumstance above, the default version has been changed to `v0.1.10`, but it still displays `v0.1.19` on the page, it makes no sense since `v0.1.19` is no longer available, am I right? @WuJun2016

**Comment by DoNotSayYes** [comment]
UI displays the value of the setting YAML
![image](https://user-images.githubusercontent.com/57614736/101130628-c8394200-363e-11eb-8374-d14f16f4c0e1.png)
