### ISSUE TITLE
[BUG] Upgrade stuck: kube-controller-manager fail to start

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2893]
**Describe the bug**

An upgrade is stuck in the pre-drained state and won't continue.

**To Reproduce**
1. Upgrade from v1.0.3 to v1.1.0-rc2
2. There is a chance to stuck in the pre-drained state.
![image](https://user-images.githubusercontent.com/1691518/194473786-6f871217-5cb8-4494-ac18-0b5e4780636b.png)

**Expected behavior**

The upgrade should finish.

**Support bundle**

[supportbundle_1525861a-48d6-4313-a67b-eb93485b6081_2022-10-07T05-24-13Z.zip](https://github.com/harvester/harvester/files/9730909/supportbundle_1525861a-48d6-4313-a67b-eb93485b6081_2022-10-07T05-24-13Z.zip)
[debug.tar.gz](https://github.com/harvester/harvester/files/9730911/debug.tar.gz)

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
- From rancher log:
```
rancher-68c449f596-qqhmj 2022/10/07 03:23:57 [INFO] [planner] rkecluster fleet-local/local: waiting: configuring bootstrap node(s) custom-df5877e771dd: waiting for probes: kube-controller-manager
rancher-68c449f596-qqhmj 2022/10/07 03:24:20 [INFO] [planner] rkecluster fleet-local/local: waiting: configuring bootstrap node(s) custom-df5877e771dd: waiting for probes: kube-controller-manager
```

- Check `custom-df5877e771dd` (node `harvester-vtgk8`). kube-controller-manager fails to start:
```
harvester-vtgk8:/var/log/containers # crictl ps -a | grep kube-controller-manager
3ed94fe307847       0a5067ab04e9a       17 hours ago        Exited              kube-controller-manager            2                   9bf00efca6127       kube-controller-manager-harvester-vtgk8
```

```
harvester-vtgk8:/var/log/containers # cat cloud-controller-manager-harvester-vtgk8_kube-system_cloud-controller-manager-b153f14e940006b6257cb8ea67c129837a649d10257379e5d6b43bdb72892ff0.log
2022-10-06T11:50:32.955155052Z stderr F goroutine 179 [chan receive]:
2022-10-06T11:50:32.955158109Z stderr F k8s.io/client-go/util/workqueue.(*Type).updateUnfinishedWorkLoop(0xc00078ab40)
2022-10-06T11:50:32.955161199Z stderr F 	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.22.1-k3s1/util/workqueue/queue.go:204 +0xac
2022-10-06T11:50:32.955164359Z stderr F created by k8s.io/client-go/util/workqueue.newQueue
2022-10-06T11:50:32.955167426Z stderr F 	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.22.1-k3s1/util/workqueue/queue.go:62 +0x154
2022-10-06T11:50:32.955170391Z stderr F
2022-10-06T11:50:32.955173435Z stderr F goroutine 180 [select]:
2022-10-06T11:50:32.955176488Z stderr F k8s.io/client-go/util/workqueue.(*delayingType).waitingLoop(0xc00078ad80)
2022-10-06T11:50:32.955179542Z stderr F 	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.22.1-k3s1/util/workqueue/delaying_queue.go:231 +0x3df
2022-10-06T11:50:32.955182614Z stderr F created by k8s.io/client-go/util/workqueue.newDelayingQueue
2022-10-06T11:50:32.955185677Z stderr F 	/go/pkg/mod/github.com/k3s-io/kubernetes/staging/src/k8s.io/client-go@v1.22.1-k3s1/util/workqueue/delaying_queue.go:68 +0x185
```

- workaround: restart rke2-server on the node.

**Comment by lanfon72** [comment]
Add the context when performing upgrade:
- 1 Image for VM creation
- 1 Cloud Config
- 1 VLAN configured NOT on mgmt port
- 3 VMs running
    - 1C2M, 1 image volume, default network, cloud config loaded
    - 1C2M, 1 image volume, VLAN network, cloud config loaded
    - 1C2M, 1 image volume, 1 data volume, default and VLAN network, cloud config loaded
    - added some data for backup purpose.
- 3 Backups created by each VM
- Perform upgarde
- **Update Backup-target** (this might be the root cause)

**Comment by starbops** [comment]
After restart rke2-server on the problematic node, we have spotted the same issue happened again in the following upgrade.

<img width="570" alt="image" src="https://user-images.githubusercontent.com/1827717/194983232-fcd691f7-4275-4eba-a0f5-71c9cb09b5cf.png">

Role:

- harvester-vtgk8: server
- harvester-4b8xc: server
- harvester-s4wfw: server
- harvester-gc46b: agent

Upgrade order:

```
1. harvester-vtgk8
2. harvester-4b8xc
3. harvester-s4wfw
4. harvester-gc46b <- stuck here
```

`harvester-4b8xc` kube-controller-manager has died:

```bash
harvester-4b8xc:~ # crictl ps -a | grep kube-controller-manager
61bdf73a9ee27       0a5067ab04e9a       3 days ago          Exited              kube-controller-manager           1                   c98d5e6d1626c       kube-controller-manager-harvester-4b8xc
```

Check the log of `kube-controller-manager-harvester-4b8xc`:

```
harvester-4b8xc:~ # cat /var/log/containers/kube-controller-manager-harvester-4b8xc_kube-system_kube-controller-manager-61bdf73a9ee2778f8ca11db336265f0bf33b560521f84ba7325ddd0985cbccbe.log
2022-10-07T05:37:31.582883023Z stderr F unable to load configmap based request-header-client-ca-file: Get "https://127.0.0.1:6443/api/v1/namespaces/kube-system/configmaps/extension-apiserver-authentication": dial tcp 127.0.0.1:6443: connect: connection refused
```

**Comment by Vicente-Cheng** [comment]
Update the root cause here.

I thought that the issue happened with the side-effect when we try to resolve the apiserver issues ([[BUG] Upgrade: kube-apiserver is not ready after node reboots](https://github.com/harvester/harvester/issues/2865#top)).

We remove the `kube-apiserver` YAML so the kubelet would wake up `kube-apiserver` after the other static pods but the `kube-controller-manager` need to authorize from `kube-apiserver`. So that would lead to the `kube-controller-manager` fail.

To resolve it, we need to hold the starting sequence that apiserver should start before other static pods.

**Comment by lanfon72** [comment]
Tested upgrade from `v1.0.3` to `master-61a6124a-head`, not encounter this issue.

will re-test it when `v1.1.0-rc3` released.

**Comment by lanfon72** [comment]
Verified this bug has been resolved.

![image](https://user-images.githubusercontent.com/5169694/196394209-ab987e2c-0783-4176-a100-6ee8d81bc697.png)


Test Information
----
* Environment: **baremetals DL360G9 4 nodes**
* Harvester Version: **v1.0.3** upgrade to **v1.1.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps:
- Prepare the environment as https://github.com/harvester/harvester/issues/2893#issuecomment-1271188125
- Perform upgrade, same as https://harvester.github.io/tests/manual/_incoming/1707-zero-downtime-upgrade/
