### ISSUE TITLE
[BUG] Upgrade stuck in upgrading first node: Job was active longer than specified deadline

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2894]
**Describe the bug**

When upgrading from v1.0.3 GA to v1.1.0-rc2, the upgrade stuck in the stage of upgrading the first node (management role)
`Job was active longer than specified deadline`

![image](https://user-images.githubusercontent.com/29251855/194512389-26310448-6821-46a4-97df-809b6f51151f.png)

**To Reproduce**
1. Prepare a v1.0.3 GA on 4 nodes Harvester
2. Prepare the offline download image 
3. Upgrade from v1.0.3 GA to v1.1.0-rc2
4. The upgrade stuck while upgrading the first node and can't proceed

**Expected behavior**

Should be able to upgrading all nodes and complete all upgrade stages to v1.1.0-rc2

**Support bundle**

[supportbundle_1e1d02cc-9096-4ccd-9b5a-97bbc818a692_2022-10-07T08-25-38Z.zip](https://github.com/harvester/harvester/files/9732302/supportbundle_1e1d02cc-9096-4ccd-9b5a-97bbc818a692_2022-10-07T08-25-38Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes Harvester on bare machines

**Additional context**

* Environment setup before upgrade 

* 3 VMs 
![image](https://user-images.githubusercontent.com/29251855/194484599-0443b9c0-5977-46bc-b515-2e2048721629.png)
![image](https://user-images.githubusercontent.com/29251855/194492479-4f453dca-c38a-43d8-bd81-84e8474a28d0.png)

* Node status
![image](https://user-images.githubusercontent.com/29251855/194484649-007634f0-915b-4efa-a171-8ac5f063fc16.png)

* 3 Backup status
![image](https://user-images.githubusercontent.com/29251855/194491767-2bf2e7cc-5c71-4aab-b9d6-eadde8806102.png)

* 3 volume status
![image](https://user-images.githubusercontent.com/29251855/194484542-045df6d5-35ea-486b-a6dd-cebd075776ec.png)

 * 1 Network VLAN (1216) status 
![image](https://user-images.githubusercontent.com/29251855/194484741-6af9a97c-c7f0-492c-8bb4-2bdc6734895e.png)

**Comment by TachunLin** [comment]
Encounter the same error while upgrading to v1.1.0-rc2 on 3 nodes Harvester cluster, 

  ![image](https://user-images.githubusercontent.com/29251855/194683545-aeb7cfb7-808c-4a39-9881-a98b81108f52.png)


#### Support bundle 
[supportbundle_2a8a3634-ecaf-4942-8139-70360f556cfa_2022-10-08T02-25-23Z.zip](https://github.com/harvester/harvester/files/9738216/supportbundle_2a8a3634-ecaf-4942-8139-70360f556cfa_2022-10-08T02-25-23Z.zip)

**Comment by khushboo-rancher** [comment]
@TachunLin Is there any workaround for this, Looks like Sev1 to me?

**Comment by w13915984028** [comment]
@khushboo-rancher 

The failure is due to the  storage & network read/write speed, the upgrade tries to spread images to all nodes, that's a big impact to storage and network, and the storage may be the main bottleneck. In our local test on KVM based cluster, that seems OK.

The workaround will be test it in newer/faster servers.

cc @bk201 @starbops

**Comment by TachunLin** [comment]
@khushboo-rancher, 
The issue was stuck in the upgrading node stage, which according to the [Harvester upgrade documentation](https://docs.harvesterhci.io/next/upgrade/troubleshooting/), we can use the workaround to restart the upgrade  https://docs.harvesterhci.io/next/upgrade/troubleshooting/#start-over-an-upgrade 

According to it, thus I set severity 2 on this issue.

**Comment by bk201** [comment]
The cause is preload job takes more than 15 minutes to load images ([We use SUC plan to spawn jobs, and its default timeout is 15 minutes](https://github.com/rancher/charts/blob/c8e0f1b2f5650d54b9245c9ea41f77f43198b9ef/charts/system-upgrade-controller/100.0.2%2Bup0.3.2/templates/configmap.yaml#L9)). In this release we have more images to preload.
I've checked David's two environments, one has SAS HDD, and the other one has an SMR HDD. Neither can survive the images preload stage.

[containerd.log](https://github.com/harvester/harvester/files/9751081/containerd.log)

```
time="2022-10-11T03:19:23.951938936Z" level=info msg="StartContainer for \"d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182\" returns successfully"

<...
time="2022-10-11T03:32:12.900717689Z" level=info msg="ImageCreate event &ImageCreate{Name:sha256:57070fe87937e599433c74eeea6b8be7f804dc121d2f42960e39a9923cf6ec15,Labels:map[string]string{io
.cri-containerd.image: managed,},XXX_unrecognized:[],}"
time="2022-10-11T03:32:12.901859283Z" level=info msg="ImageUpdate event &ImageUpdate{Name:docker.io/rancher/harvester-cluster-repo:v1.1.0-rc2,Labels:map[string]string{io.cri-containerd.imag
e: managed,},XXX_unrecognized:[],}"
time="2022-10-11T03:34:20.046354983Z" level=info msg="StopContainer for \"d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182\" with timeout 30 (s)"
time="2022-10-11T03:34:20.047112338Z" level=info msg="Stop container \"d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182\" with signal terminated"
time="2022-10-11T03:34:20.621575157Z" level=info msg="StopContainer for \"19c87bd3460f813216db8f2e6e7bdd1c4a776ddf6ff62d3cb990dd2f36f10222\" with timeout 60 (s)"
time="2022-10-11T03:34:20.622383185Z" level=info msg="Stop container \"19c87bd3460f813216db8f2e6e7bdd1c4a776ddf6ff62d3cb990dd2f36f10222\" with signal terminated"
time="2022-10-11T03:34:23.513366732Z" level=error msg="(*service).Write failed" error="rpc error: code = Canceled desc = context canceled" ref=tar-e9606b43b68a94da4bb940d9b519a2691e8fd2569e
823811fc3555da41c972b0/layer.tar total=94569472
time="2022-10-11T03:34:28.033964681Z" level=error msg="collecting metrics for d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182" error="cgroups: cgroup deleted: unknown"
time="2022-10-11T03:34:30.107030186Z" level=error msg="failed to handle container TaskExit event &TaskExit{ContainerID:d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182,ID:d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182,Pid:16704,ExitStatus:143,ExitedAt:2022-10-11 03:34:20.105466463 +0000 UTC,XXX_unrecognized:[],}" error="failed to stop container: context deadline exceeded: unknown"
time="2022-10-11T03:34:31.632701731Z" level=info msg="TaskExit event &TaskExit{ContainerID:d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182,ID:d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182,Pid:16704,ExitStatus:143,ExitedAt:2022-10-11 03:34:20.105466463 +0000 UTC,XXX_unrecognized:[],}"
time="2022-10-11T03:34:33.633018154Z" level=error msg="get state for d83ec0cfda8e8a81df999796b34c38ac449fb59813e12ed239ad29c0f099c182" error="context deadline exceeded: unknown"
```


Ideally, the job should retry, but we mark an upgrade as a failure and delete upgrade repo VM after the first failure. There are some ways to work around this on slow disks:
- Increase the job deadline before upgrading:
  ```
  $ cat > /tmp/fix.yaml <<EOF
  spec:
    values:
      systemUpgradeJobActiveDeadlineSeconds: "3600"
  EOF

  $ kubectl patch managedcharts.management.cattle.io local-managed-system-upgrade-controller --namespace fleet-local --patch-file=/tmp/fix.yaml --type merge
  $ kubectl -n cattle-system rollout restart deploy/system-upgrade-controller
  ```
- Delete the upgrade and start over again (This might need several times). Preload time will reduce due to some images are already in.
- Manually preload images from ISO on each node first.

**Comment by Martin-Weiss** [comment]
Could we use longer job timeouts than “just” 15 Minutes?

**Comment by bk201** [comment]
> Could we use longer job timeouts than “just” 15 Minutes?

Yes, but we can only fix them in a future version because the preload code is in the "previous version." For running cluster, I added instructions to the [comment](https://github.com/harvester/harvester/issues/2894#issuecomment-1274069690).

**Comment by Martin-Weiss** [comment]
> > Could we use longer job timeouts than “just” 15 Minutes?
> 
> Yes, but we can only fix them in a future version because the preload code is in the "previous version." For running cluster, I added instructions to the [comment](https://github.com/harvester/harvester/issues/2894#issuecomment-1274069690).

Sure - thanks.. this is just based on some experience with the SUC where we had the issue often, that i.e. the drain took longer than expected (i.e. due to longhorn PodDisruptionBudget) - so maybe and endless timeout and and endless retries might be better..

**Comment by TachunLin** [comment]
Rerun the upgrade with the workaround stated in https://github.com/harvester/harvester/issues/2894#issuecomment-1274069690

By preparing all Harvester cluster nodes on SSD drive 
And increase the job deadline before clicking the upgrade button on dashboard:
```
$ cat > /tmp/fix.yaml <<EOF
spec:
  values:
    systemUpgradeJobActiveDeadlineSeconds: "3600"
EOF

$ kubectl patch managedcharts.management.cattle.io local-managed-system-upgrade-controller --namespace fleet-local --patch-file=/tmp/fix.yaml --type merge
$ kubectl -n cattle-system rollout restart deploy/system-upgrade-controller
```


* We can complete the image preload stage
![image](https://user-images.githubusercontent.com/29251855/195338806-e10879b6-8817-4d27-9e18-610b0d10375c.png)

* Proceed to upgrade node
![image](https://user-images.githubusercontent.com/29251855/195344669-eae29afc-aa12-47c8-94ea-e97da726d789.png)

* And Successfully upgrade to `v1.1.0-rc2`
![image](https://user-images.githubusercontent.com/29251855/195350369-67d9befc-637a-48a8-b6dc-d834028facb6.png)

**Comment by khushboo-rancher** [comment]
@TachunLin Thanks for rerunning it, but if you're using SSD you didn't have to increase the job deadline. Just to check the default deadline is okay for an SSD disk.

**Comment by irishgordo** [comment]
@TachunLin @bk201 thanks for sharing the workaround.
I ran into a similar situation in my homelab currently where this same thing occurred.  But the workaround seems to have fixed it.
Should we mention this workaround in release notes for v1.1.0?
I was running an instance of Harvester that was virtualized, not running on bare metal, using /vda based mount point for virtio drive - the underlying hardware however was a SATA3 Based SSD, on my 1U SuperMicro:
https://www.supermicro.com/products/archive/motherboard/x9drd-it_
(using 1 of the 2 SATA 3 Ports)

**Comment by TachunLin** [comment]
@khushboo-rancher, 
I tried running the upgrade to v1.1.0-rc3 on 3 nodes Harvester, all nodes are installed on SSD disk. 
Without setting the increase job workaround https://github.com/harvester/harvester/issues/2894#issuecomment-1274069690 
In this trial we can still upgrade successfully.

**Comment by dseralathan** [comment]
While doing upgrade from v.1.0 to v.1.1  , we got below error and not able to proceed after that 

Upgrading Monitoring
managedchart.management.cattle.io/rancher-monitoring-crd patched (no change)
managedchart.management.cattle.io/rancher-monitoring unchanged
managedchart.management.cattle.io/rancher-monitoring patched
managedchart.management.cattle.io/rancher-monitoring-crd patched
Waiting for ManagedChart fleet-local/rancher-monitoring from generation 19
Target version: 100.1.0+up19.0.3, Target state: ready
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 19
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 20
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 20
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 20

**Comment by khushboo-rancher** [comment]
@dseralathan This looks like similar to https://github.com/harvester/harvester/issues/1983
Could you please try to delete the latest harvester-crd secret and related rancher-monitoring secret?

**Comment by dseralathan** [comment]
Thanks Khushboo,   My issue has been fixed by adding more value to requested memory for Prometheus Node Exporter

Error: on  "kubectl get bundles -A" 

fleet-local   mcc-rancher-monitoring                        0/1                       ErrApplied(1) [Cluster fleet-local/local: cannot patch "rancher-monitoring-prometheus-node-exporter" with kind DaemonSet: DaemonSet.apps "rancher-monitoring-prometheus-node-exporter" is invalid: spec.template.spec.containers[0].resources.requests: Invalid value: "10Gi": must be less than or equal to memory limit]
fleet-local   mcc-rancher-monitoring-crd                    1/1

2. we have edited the value for 10Gi for Prometheus Node Exporter  Requested memory  to 20 MI and worked good . The upgrade continued after this change

**Comment by dseralathan** [comment]
Now this is new issue , not able to delete the upgrade and re-start it 

We have 4 node cluster - 3 nodes upgraded . the 4th node was not part of it and its rebooted during upgrade and joined the cluster automatically .  I ran the cluster upgrade again and got below error 

#kubectl get bundles -A 
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps harvester-system/harvester [progressing] Available: 2/3; deployment.apps harvester-system/harvester-webhook [progressing] Deployment does not have minimum availability., Available: 2/3; kubevirt.kubevirt.io harvester-system/kubevirt [progressing] Deploying version 0.54.0-150400.3.7.1 with registry registry.suse.com/suse/sles/15.4, Resource is current


 # kubectl get upgrade.harvesterhci.io -n harvester-system -l harvesterhci.io/latestUpgrade=true
NAME                 AGE
hvst-upgrade-m8z28   62m
# 
# kubectl delete upgrade.harvesterhci.io/hvst-upgrade-m8z28 -n harvester-system
Error from server (BadRequest): admission webhook "validator.harvesterhci.io" denied the request: cluster fleet-local/local status is provisioning, please wait for it to be provisioned
l# 
 #

**Comment by bk201** [comment]
To add a suggestion for HDD users in the upgrade doc first.

**Comment by bk201** [comment]
Thank @connorkuehl. Upstream PR merged: https://github.com/rancher/system-upgrade-controller/pull/244
Also need to check if the SUC change will make it to Rancher 2.7.5. If not, we probably need to wait for the next milestone.

**Comment by connorkuehl** [comment]
Upstream fix is in rancher/system-upgrade-controller v0.12.0[1].

I've opened a bug against rancher/rancher to include system-upgrade-controller v0.12.0[2].

[1] https://github.com/rancher/system-upgrade-controller/releases/tag/v0.12.0
[2] https://github.com/rancher/rancher/issues/42049

**Comment by connorkuehl** [comment]
rancher/system-upgrade-controller >= v0.12.0 appears to be included with Rancher 2.8.1 and 2.8.2. The embedded Rancher in the Harvester 1.2[1], 1.3[2], and master[3] branches should be compatible.

[1] https://github.com/harvester/harvester-installer/blob/f187e16bea0523c84b9cc40f91879caf5719903b/package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml#L4
[2] https://github.com/harvester/harvester-installer/blob/1f12b0a50c5cc49a951ca8333de91350603463b0/package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml#L4
[3] https://github.com/harvester/harvester-installer/blob/ff64a85e38168afe5c1b982948b5f159a59ca8d1/package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml#L4

**Comment by khushboo-rancher** [comment]
@lanfon72 Could you check if the upgrade in running ok on master and not timing out in preupgrade stage?

This is ok to close if we are not seeing this issue on our upgrade pipeline.

**Comment by lanfon72** [comment]
close as we didn't hit the bug in our daily upgrade testing for months.
