### ISSUE TITLE
[FEATURE] - Bandwith limiting/reservation for different components/services (network QoS)

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#2895]
**Is your feature request related to a problem? Please describe.**
In some use cases, bare-metal servers only have 2 network adapters in LACP Mode (OVH for example).  So your WAN, harvester management and vlans all go trough the same 2 physical adapters.  This setup works just fine, but when dealing with network-intensive processes (big vm images, longhorn replicas rebuild) - we end up with packet loss on VM networks causing all kind of unexpected behavior.

While I agree that this setup is not the recommended one, IMHO, it will happen more often that not.

**Describe the solution you'd like**
It would be nice to be able to easily configure bandwidth limit/reservation based on the speed of the underlying bond/network interface (my case 50G LACP) for the following components:

- VM Networks
- VM Migrations
- Longhorn
- Images-related operations (this is the most problematic one for our use case - when a new vm created and attached to 2-3 different images, this is when the problems happens most often)

**Comment by yasker** [comment]
One thing that might help with the usage right now is the #1055 feature in v1.1.x. 

Though I don't really expect that kind of issue happens on 50G bonded nic. #2541 should be the main issue for the network QoS.

Bump the priority of #2541 in this case. And close this as the duplicate issue for #2541
