### ISSUE TITLE
[FEATURE] bot to auto add releases when milestone is set

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2896]
**Is your feature request related to a problem? Please describe.**
- [x] bot to auto add releases when milestone is set https://github.com/harvester/bot/pull/15
- ~~[ ] need to migrate bot env to fremont~~
- [x] make the bot to ignore PR pipelines, e.g., https://github.com/harvester/harvester/pull/3966

**Describe the solution you'd like**
bot to auto add releases when milestone is set

**Comment by bk201** [comment]
also need to handle the case the bot can't create two backport issues.

**Comment by Yu-Jack** [comment]
@bk201 these two features are already done and tested, I think we could just close this one? @bk201
