### ISSUE TITLE
[BUG] Update deprecated label of beta.kubernetes.io/os to kubernetes.io/os

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2899]
**Describe the bug**
Warning: 
```
spec.template.spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].key: beta.kubernetes.io/os is deprecated since v1.14; use "kubernetes.io/os" instead
deployment.apps/harvester edited
```

**Expected behavior**
change desired label to 
Related to: 
- https://github.com/harvester/harvester/search?q=beta.kubernetes.io%2Fos
- https://github.com/harvester/charts/search?q=beta.kubernetes.io%2Fos
- other harvester dependency charts/repos where applicable.

Make sure those changes will not break the upgrade case.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): all

**Additional context**

**Comment by tlehman** [comment]
Since kubernetes.io/os label is already present, this issue involves just removing the old beta label. For the upgrade case, we simply remove it if present right? Should be straightforward

**Comment by tlehman** [comment]
Upgrade path: https://github.com/harvester/harvester/blob/master/package/upgrade/upgrade_node.sh#L497

**Comment by lanfon72** [comment]
@guangbochen are we going to remove label `beta.kubernetes.io/os` on ondes?  it looks fresh new cluster will still have it.

**Comment by lanfon72** [comment]
@guangbochen are we going to remove label `beta.kubernetes.io/os` on ondes?  it looks fresh new cluster will still have it.

**Comment by guangbochen** [comment]
Yep, this label is deprecated but has yet to be removed; it was also shipped by the k8s out-of-the-box. For the testing scope, we only need to ensure that the Harvester component didn't use this label as the node selector terms.
```
$ kubectl get pod -n harvester-system -oyaml | grep "beta.kubernetes.io/os" # should not exist
```

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/b78e3ec5-a897-42e7-a8e2-bec1a782e94a)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.1.2** upgrade to **v1.2-bd26e791-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
    - Upgrade from `v.1.1.2`[^1]
    - Latest version
2. Login to console, Output of command `kubectl get pods -A | grep 'beta.kubernetes.io' | wc -l` should be `0`


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
