### ISSUE TITLE
[BUG] VirtualMachineImports Don't Respect Default StorageClass For Volumes

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2902]
**Describe the bug**
Having a custom "default" StorageClass provided resources created of kind VirtualMachineImport, the "images" downloaded respect the Default StorageClass, yet the Volume that gets created does not.

**To Reproduce**
1. have a multi-node cluster
1. have 1 node in the multi-node cluster that has an extra large disk
1. `gdisk /dev/disk` on the node
1. add a tag for the node and the node's main disk
1. add the secondary disk to the node
1. add a unique tag for that disk that's extra large
1. build a storageclass that points to that disk with 1 replica
1. set the new storageclass is default
1. reset the default of the 'harvester-longhorn' one
1. then create yaml to import either vSphere or OpenStack resource 
1. create that resource against the cluster 
1. you'll notice that the image downloaded will use the default storage class, yet the volume will not

**Expected behavior**
That the volume built from the image would use the default storage class.

**Support bundle**
[supportbundle_8f951168-f084-47ce-952d-29ecc55a4ffd_2022-10-11T02-20-17Z.zip](https://github.com/harvester/harvester/files/9750504/supportbundle_8f951168-f084-47ce-952d-29ecc55a4ffd_2022-10-11T02-20-17Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - vm-import-controller custom image used: https://hub.docker.com/r/gmehta3/harvester-vm-import-controller/tags @ tag "dev"
 - Underlying Infrastructure: qemu/kvm

**Additional context**
![Screenshot from 2022-10-10 19-19-16](https://user-images.githubusercontent.com/5370752/194983303-bbbb75cd-8e65-47f3-93e4-dd88369d1db8.png)
![Screenshot from 2022-10-10 19-17-14](https://user-images.githubusercontent.com/5370752/194983306-c12cfd88-c6fb-449f-bd16-a0f0309b168f.png)
![Screenshot from 2022-10-10 19-16-40](https://user-images.githubusercontent.com/5370752/194983307-b783c2d7-b363-4cf0-97e7-521f50514149.png)
![Screenshot from 2022-10-10 19-15-46](https://user-images.githubusercontent.com/5370752/194983310-1779bb20-46cd-49cb-9a3c-57eed135be54.png)

**Comment by guangbochen** [comment]
The multi-tiering feature is introduced afterward, so may need to consider allowing users to specify the storage class or get the default one via API if not specified. cc @ibrokethecloud

**Comment by ibrokethecloud** [comment]
@guangbochen currently a VirtualMachineImage uses the default storage class to create a new longhorn backing image, which in turn uses a custom storage class.

When a VM or volume is launched from said image, the storage class generated for the backing image is used to create the PVC claim. 

```
(⎈|default:default)➜  ~ k get pvc
k geNAME                STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE
demo-disk-0-i3mm3   Bound    pvc-a6f4658d-7a95-4623-b084-e0f34d819761   5Gi        RWX            longhorn-image-45tb2   5m51s
sample1             Bound    pvc-0d45f6bc-f96d-4af6-bb06-8b74a0cdc0df   1Gi        RWX            longhorn-image-45tb2   8m12s
(⎈|default:default)➜  ~ k get virtualmachineimage
NAME          DISPLAY-NAME   SIZE        AGE
image-45tb2   ubuntu         660996096   13h
```

The vm import controller is doing the same. I am not sure we can change the virtualmachineimage storage class once its created.

**Comment by irishgordo** [comment]
@guangbochen I can go ahead and close this out as I just didn't connect the dots that indeed there is no bug.
If a default storage class is set, with Importing a VM, the whole process will use that default storage class.
```
suse-workstation-team-harvester➜  testing_gaurav_vm_migration  ᐅ  kubectl describe storageclasses/longhorn-image-8pbr4                                                                                                               
Name:                  longhorn-image-8pbr4
IsDefaultClass:        No
Annotations:           <none>
Provisioner:           driver.longhorn.io
Parameters:            backingImage=default-image-8pbr4,diskSelector=big-node-2,migratable=true,nodeSelector=node-2,numberOfReplicas=1,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>
suse-workstation-team-harvester➜  testing_gaurav_vm_migration  ᐅ  kubectl describe storageclasses/big-node-2          
Name:                  big-node-2
IsDefaultClass:        Yes
Annotations:           field.cattle.io/description=big node 2 disk,storageclass.beta.kubernetes.io/is-default-class=true,storageclass.kubernetes.io/is-default-class=true
Provisioner:           driver.longhorn.io
Parameters:            diskSelector=big-node-2,migratable=true,nodeSelector=node-2,numberOfReplicas=1,staleReplicaTimeout=30
AllowVolumeExpansion:  True
MountOptions:          <none>
ReclaimPolicy:         Delete
VolumeBindingMode:     Immediate
Events:                <none>

```
The `longhorn-image-8pbr4` that gets built is using the `diskSelector=big-node-2` with the `nodeSelector=node-2` which is the default storage class set up 
I was just unfamiliar with how Longhorn was creating the longhorn backing image :sweat_smile:

**Comment by irishgordo** [comment]
Closing this out, as I wasn't understanding how backing images were built with longhorn :smile: 
Apologies for the spam @ibrokethecloud & @guangbochen
