### ISSUE TITLE
[BUG] VM failed to get IP after node reboot

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2903]
**Describe the bug**
VM with VLAN network failed to get IP after node reboot

**To Reproduce**
1. Create a new cluster network and add related network configs
2. Create networks with associated vlan id
3. Create a new VM using this VLAN network and after it starts successfully reboot the node
4. After the node reboot, the VM failed to retrieve the IPv4.
5. Check the bridge vlan the associated PVID does not exist.

**Expected behavior**
VM should be able to get IP back after node reboot.

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
@guangbochen  - this looks good - testing on a single node v1.1.0-rc3

I do notice that the pvid is correct on the bridge used for one of the cluster networks:
```
rancher@v110-rc3-vm-node:~> ip -d link show dev test-net-1-br | grep -ie 'vlan'
    bridge forward_delay 1500 hello_time 200 max_age 2000 ageing_time 30000 stp_state 0 priority 32768 vlan_filtering 1 vlan_protocol 802.1Q bridge_id 8000.0:0:0:0:0:0 designated_root 8000.0:0:0:0:0:0 root_port 0 root_path_cost 0 topology_change 0 topology_change_detected 0 hello_timer    0.00 tcn_timer    0.00 topology_change_timer    0.00 gc_timer   43.52 vlan_default_pvid 1 vlan_stats_enabled 0 vlan_stats_per_port 0 group_fwd_mask 0 group_address 01:80:c2:00:00:00 mcast_snooping 1 mcast_router 1 mcast_query_use_ifaddr 0 mcast_querier 0 mcast_hash_elasticity 16 mcast_hash_max 4096 mcast_last_member_count 2 mcast_startup_query_count 2 mcast_last_member_interval 100 mcast_membership_interval 26000 mcast_querier_interval 25500 mcast_query_interval 12500 mcast_query_response_interval 1000 mcast_startup_query_interval 3124 mcast_stats_enabled 0 mcast_igmp_version 2 mcast_mld_version 1 nf_call_iptables 0 nf_call_ip6tables 0 nf_call_arptables 0 addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 

```

As well as upon multiple cluster networks and multiple reboots the IPvv4 address.
Additional test artifacts:
![Screenshot from 2022-10-17 15-22-05](https://user-images.githubusercontent.com/5370752/196297808-4925aa80-f942-4131-b72c-15cc00b83f22.png)
![Screenshot from 2022-10-17 15-15-27](https://user-images.githubusercontent.com/5370752/196297810-701df36a-5661-4fe5-9b1f-d3b7e7214ef4.png)
![Screenshot from 2022-10-17 14-59-39](https://user-images.githubusercontent.com/5370752/196297812-66a93652-1e4a-43f9-bf9c-5b847810732d.png)

https://user-images.githubusercontent.com/5370752/196297902-1e9cc399-b156-4fe2-acf4-caf584875ed1.mp4

I'll go ahead and close this out.
Tested with multiple reboots.
