### ISSUE TITLE
[BUG] Unable to update default image labels

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2904]
### Describe the bug
Default image labels can not be updated but deleted.

https://user-images.githubusercontent.com/5169694/195018291-b2879f9d-d376-4773-95b6-3f862e0a12f6.mp4

### To Reproduce
1. Install Harvester with any nodes
2. Create an Image
3. Edit Image Labels by _Edit Config_

### Expected behavior
Default Labels should able to be updated or freeze modification, and should not able to be deleted.

## Environment:
 - Harvester ISO version: **v1.1.0-rc2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

**Comment by futuretea** [comment]
The label imageDisplayName is automatically updated by the backend and will change with the actual DisplayName of the image. prefer to hide it

Other labels cannot be modified need to be checked by the UI team

**Comment by WuJun2016** [comment]
Hi,  @lanfon72  duplicate with https://github.com/harvester/harvester/issues/2888,  We can close this issue

**Comment by lanfon72** [comment]
closed as duplicated in #2888
