### ISSUE TITLE
[BUG] vm-import-controller status keeps changing

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2905]
**Describe the bug**

The `vm-import-controller` status changes between `AddonEnabled` and `AddondeploySuccessful`

**To Reproduce**
1. setting vm-import-controller to `enabled` equals true

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

https://user-images.githubusercontent.com/24985926/195018953-e1c1920f-d832-4c5a-9a76-bd1532d6003f.mov

**Comment by irishgordo** [comment]
@WuJun2016  I was able to reproduce this in the UI and also with calling describe on the resource using `kubectl` on the Harvester cluster.
Environment: qemu/kvm
Harvester Version: v1.1.0-rc2

Based around some tests it seems that more often it's shown as "AddonEnabled" than it is shown as "AddonDeploySuccessful":
```
#######################
####### SUMMARY #######
#######################
Total Number Of Times, Status was seen as AddonEnabled: 65

Total Number Of Times, Status was seen as AddonDeploySuccessful: 36

```


This is the small bash script I wrote to audit this with `kubectl`:

```bash
#! /bin/bash
ADDON_ENABLED_COUNT=0
ADDON_DEPLOY_SUCCESSFUL_COUNT=0
for i in {1..101}; 
do 
  echo "on $i iteration - for checking addons.harvesterhci.io vm-import-controller status...";
  RESULT=$(kubectl describe addons.harvesterhci.io vm-import-controller -n harvester-system | grep -e "Status:")
  echo $RESULT;
  if [[ "$RESULT" == *"AddonEnabled"* ]]; then
    echo "found AddonEnabled as the status for addons.harvesterhci.io vm-import-controller";
    ADDON_ENABLED_COUNT=$((ADDON_ENABLED_COUNT+1));
  fi
  if [[ "$RESULT" == *"AddonDeploySuccessful"* ]]; then
    echo "found AddonDeploySuccessful as the status for addons.harvesterhci.io vm-import-controller";
    ADDON_DEPLOY_SUCCESSFUL_COUNT=$((ADDON_DEPLOY_SUCCESSFUL_COUNT+1));
  fi
  sleep 1; 
  echo "current AddonEnabled Count of Number of times seen as status: $ADDON_ENABLED_COUNT";
  echo "current AddonDeploySuccessful Count of Number of times seen as status: $ADDON_DEPLOY_SUCCESSFUL_COUNT";
done
echo "#######################";
echo "####### SUMMARY #######";
echo "#######################";
echo "Total Number Of Times, Status was seen as AddonEnabled: $ADDON_ENABLED_COUNT";
echo "";
echo "Total Number Of Times, Status was seen as AddonDeploySuccessful: $ADDON_DEPLOY_SUCCESSFUL_COUNT";
echo "";
```
cc: @ibrokethecloud

**Comment by ibrokethecloud** [comment]
This is fixed in  master builds.

**Comment by irishgordo** [comment]
This stays at "AddonDeploySuccessful" on Harvester Version: master-937f333c-head.

Tested for 5x what was previously tested.
500 runs. Status stays on correct value.

[test_results_2905.log](https://github.com/harvester/harvester/files/9779433/test_results_2905.log)

This looks great!
Thanks for the fix @ibrokethecloud :smile:  - I'll go ahead and close this out :+1:
