### ISSUE TITLE
VM management IP is down when the VM is restarted

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#291]
**Description:**
VM management IP is down when the VM is restarted

**Expectation:**
Persist the VM management IP on VMI restart.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/301

**Comment by DoNotSayYes** [comment]
**Steps to verify:**
1. Create a VM, login to it, and check on its mac address
2. Restart the VM, check the mac address again

**Result:** 
Mac address persists
![image](https://user-images.githubusercontent.com/57614736/101570406-4f0c6700-3a11-11eb-929a-9ed5a44b947d.png)
![image](https://user-images.githubusercontent.com/57614736/101577302-7add1c00-3a14-11eb-819c-d5a61ae42d05.png)
