### ISSUE TITLE
[BUG] Longhorn could schedule all volume replicas to a single node

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#2911]
**Describe the bug**

In a single-node deployment, Longhorn could schedule all three replicas of a volume to the same node.
Note this issue is captured from https://github.com/longhorn/longhorn/issues/4546 for tracking in Harvester milestone and it was initially reported by @w13915984028 .

**To Reproduce**
1. Deploy Harvester v1.1.0-rc2 or master (with Longhorn v1.3.1) in single node.
2. Reboot the node.
3. All replicas can reside on the node.
![image](https://user-images.githubusercontent.com/1691518/195139296-d2c9454d-b694-476d-8e06-c994a6abfc97.png)
![image](https://user-images.githubusercontent.com/1691518/195139329-e2fb3f0c-2768-4f66-85b1-20c6b7922ec9.png)

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
The issue is supposed to be fixed in Longhorn v1.3.2-rc2.

**Comment by bk201** [comment]
We'll bump Longhorn to v1.3.2-rc2.

**Comment by masteryyh** [comment]
Test steps:
1. Deploy a harvester 1.1.0-rc3 single node environment with default settings;
2. Create a volume with 5Gi size (volume size can be changed);
3. Navigate to `https://HARVESTER_BASE_URL/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/dashboard` to go to longhorn dashboard;
4. Go to `Volume` tab, and enter the volume created before;
5. Check `Replicas` section, and see if only one replica can be scheduled to the only node in the environment, other 2 replicas cannot (How to tell if replica cannot be scheduled: both `Node ID` and `Disk Path` are `N/A`).

cc @guangbochen @bk201 @Vicente-Cheng

**Comment by irishgordo** [comment]
Validated in v1.1.0-rc3 that this looks good :smile: :+1: 

![Screenshot from 2022-10-20 11-13-20](https://user-images.githubusercontent.com/5370752/197026365-fd989355-f360-40cd-a085-c39efa5ae7f6.png)

I'll go ahead and close this out.

**Comment by w13915984028** [comment]
note: This issue exists in Longhorn old version. It may also affect Harvester v1.0.0, v1.0.1, v1.0.2, v1.0.3
