### ISSUE TITLE
[BUG]  cancel button will save the change when restarting vm

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#2915]
**Describe the bug**

**To Reproduce**
https://github.com/harvester/dashboard/pull/463#pullrequestreview-1135826382

**Expected behavior**

Cancel button should not save the change

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
This is a generic issue.

**Comment by noahgildersleeve** [comment]
tested in master-14bbee2c-head. Verified that you can't hit cancel while in restart modal.
