### ISSUE TITLE
[BUG] go to the namespace details page is not supported in the harvester ui

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2916]
**Describe the bug**

All harvester pages have this problem

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/096a82df-7f55-42cb-b3fc-dab59cba1e94)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/58519011-2fb6-4a89-8013-ff4e29bba2f1)

**To Reproduce**
1.  go to the details page of any resource
2. click `Namespace`

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-14bbee2c-head. I verified that this was happening both in ui-source set as auto and external. It seems that it's not going to the error code page buit it's getting the same error.

## Verification Steps
1. Open up existing VM from VM list
2. Click the namespace (default in this case)
![Screenshot_20230118_164949](https://user-images.githubusercontent.com/83787952/213330163-e6471660-25aa-4935-99ef-60a6f0be49a1.png)
![Screenshot_20230118_165004](https://user-images.githubusercontent.com/83787952/213330158-2aae1262-9d62-40cb-b31b-f1ccf94d4592.png)
![Screenshot_20230118_164959](https://user-images.githubusercontent.com/83787952/213330162-0a919474-9f43-44ca-9afe-296c31857105.png)

**Comment by noahgildersleeve** [comment]
Tested in master-8c620b7d-head. Verified that namespace is no longer clickable. 
![Screenshot_20230208_091727](https://user-images.githubusercontent.com/83787952/217604118-c38a909e-d0ea-4915-b2cc-d15f68a823b4.png)
