### ISSUE TITLE
[BUG] multus cni is unauthorized and failed to create/delete related containers

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2917]
**Describe the bug**
For Harvester v1.1.0-rc2 version, after the cluster is running for a while, the kubelet will encounter the following errors:
```
  Warning  FailedKillPod  4m33s (x117 over 29m)  kubelet  error killing pod: failed to "KillPodSandbox" for "796e0849-9fdf-48ad-b399-e5f5bbd74735" with KillPodSandboxError: "rpc error: code = Unknown desc = failed to destroy network for sandbox \"03ed6185a8b08a2dd6d080f9e8a78886d2bbb064b63637f5fd6e47b509f2ad50\": plugin type=\"multus\" name=\"multus-cni-network\" failed (delete): delegateDel: error invoking ConflistDel - \"k8s-pod-network\": conflistDel: error in getting result from DelNetworkList: error getting ClusterInformation: connection is unauthorized: Unauthorized"
``` 

**To Reproduce**
1. Spin up a Harvester cluster using the `v1.1.0-rc2` version
2. Leave the cluster for a period of time >= 24 hrs, and try to either create/delete the VM/pod
3. it will be stuck in terminating or creating due to the above-unauthorized issues

**Expected behavior**
User should not expect to encounter the unauthorized issues

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): all

**Additional context**
Related to: https://github.com/rancher/rke2/issues/3425

**Comment by guangbochen** [comment]
This is related to https://github.com/rancher/rke2/issues/3425 and a temp workaround to renew the token can be done via:
`$ kubectl delete pod -l k8s-app=canal -n kube-system`
Will need to wait and bump the RKE2 to a newer version that includes the above issue's fix.

**Comment by bk201** [comment]
Waiting for RKE2 v1.24.7, we've bumped to v1.24.7-rc2 so far.

**Comment by bk201** [comment]
We've updated RKE2 to v1.24.7, https://github.com/harvester/harvester-installer/pull/369.
To test the issue is verified:
- Create a cluster.
- Wait for 24 hours.
- Ensure VMs can still be created.

**Comment by lanfon72** [comment]
reproducible on `v1.1.0-rc3`

**Comment by bk201** [comment]
@lanfon72 Please try master or v1.1-head ISO. We bumped RKE2 last Friday.

**Comment by lanfon72** [comment]
Yeah, as this requires 24hrs to reproduce, I just make sure it was not fixed in RC3.

**Comment by guangbochen** [comment]
Verified with the mater-head build using commit [380ddce](https://github.com/harvester/harvester/commit/380ddce19052b64cb93e5f5a17ab43db3b71f26b), the cluster CNI and kubelet is still function well after 24 hrs, moving this to v1.1.1 and QA can have a double-check on it, thanks.

**Comment by lanfon72** [comment]
Verified this bug has been resolved.

Tested on `v1.1-47710e8a-head` (1.4 days ago), `master-402df54b-head` (1 days ago), VM started successfully, webVNC and network connectivity work as normally.
