### ISSUE TITLE
[BUG] enhance VM viewLogs action

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2919]
**Describe the bug**

if vm stops, `ViewLogs` is not available at this time

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/5e401f23-13ed-44bf-abd1-b9f804582b71)

**To Reproduce**
1.  stop vm
2. click `View Logs`

**Expected behavior**

If view Logs is not available, it should not be displayed

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
@n313893254, I try to verify this issue on `master-bbc2b33f-head` (12/16).  
But it looks like on the vm context menu there is no `view log` item available to click. 
![image](https://user-images.githubusercontent.com/29251855/208147850-b2d8e16e-2776-47b9-bee2-22fd90b9af12.png)

May I know how to properly activate this feature or it requires Rancher integration to view in virtualization management. Thanks.

**Comment by n313893254** [comment]
@TachunLin Thanks for your testing. That is the expected result, the VM has no pods and should not have logs. The "View Logs" action should be hidden.

**Comment by TachunLin** [comment]
After discussion and checked on on Harvester `master-bbc2b33f-head` 
The `view log` option also not exists while the VM is in running state. Suggest we can have a fix on it. 
![image](https://user-images.githubusercontent.com/29251855/208565923-77f122f6-75e5-4e30-8c72-30211a40a640.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-a310138d-head` (12/27). Close this issue.

### Result
* When VM stopped in `off` state, we can's see the `View logs` option display on menu
![image](https://user-images.githubusercontent.com/29251855/210297784-e3b5b198-7765-47bd-9e65-57b50a431bc9.png)

* When VM started in `running` state, we can see and use the `View logs` option instead 
![image](https://user-images.githubusercontent.com/29251855/210297746-0e72c241-8a65-4af5-85ac-3b5dd96254e2.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: master-a310138d-head 

### Verify Steps
1. Create a VM 
2. Start VM to running state 
3. Check the view log option
4. Stop VM to off state
5. Check the view log option disappear
