### ISSUE TITLE
[BUG] Edit Storage Class Config `Allow Volume Expansion` and `Description`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2921]
**Describe the bug**

Edit storage class
1. `Description` cannot be edited
2. `Customize > Allow Volume Expansion` can be edited
![image](https://user-images.githubusercontent.com/15064560/195304792-5e6da7a2-ba18-4575-bfd3-ac30624f4ac4.png)
![image](https://user-images.githubusercontent.com/15064560/195304850-0a84c951-36c7-48f8-a076-bc3197d00415.png)

**To Reproduce**
1. Go to **Advanced > Storage Classes** page.
2. Create a storage class
3. `Edit Config`

**Expected behavior**

After a storage class is created, nothing can be changed except `Description`
Edit storage class
1. `Description` can be edited
2. `Customize > Allow Volume Expansion` cannot be edited

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
![Screenshot from 2022-10-14 13-02-33](https://user-images.githubusercontent.com/5370752/195932372-5cdedc30-8030-4dda-aadc-7a068271ed79.png)

Validated on Harvester Version: master-61a6124a-head 

This looks great!
Thanks for the fix @n313893254 !
I'll go ahead and close this out
