### ISSUE TITLE
[BUG] Error when opening PCI device in dashboard

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2925]
**Describe the bug**

When you click on a PCI device name in the PCI devices section of settings you get an error
**To Reproduce**
1. Deploy Harvester
2. Navigate to PCI devices page
3. Click on one of the device names

**Expected behavior**

You should be able to access the item 

**Environment**
 - Harvester ISO version: v1.1.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal DL360 Single node

**Additional context**
It seems to not be loading the dashboard parts. I'm going to double check with a custom iso with some of the other PCI-E fixes

![Greenshot 2022-10-12 13 11 07](https://user-images.githubusercontent.com/83787952/195480450-4faedfac-4c11-478a-9e54-6678de0f445e.png)
![Greenshot 2022-10-12 13 11 02](https://user-images.githubusercontent.com/83787952/195480452-d8548fdf-131e-445e-8706-e923747d113a.png)
![Greenshot 2022-10-12 13 10 58](https://user-images.githubusercontent.com/83787952/195480453-ce6ff7f9-8bf5-44d6-8055-26a0c3806b85.png)
![Greenshot 2022-10-12 13 07 32](https://user-images.githubusercontent.com/83787952/195480454-6e215522-995a-4d64-9977-e8c21d77b7fd.png)

**Comment by WuJun2016** [comment]
@mantis-toboggan-md    I want to confirm, do we support clicking to the details page ?

**Comment by tlehman** [comment]
@WuJun2016 There isn't a great need for it now, we can just remove the link and not make it clickable.

**Comment by noahgildersleeve** [comment]
Also @WuJun2016 If you click the triple button and click `edit YAML` or `Clone` it will give you that same error.

**Comment by noahgildersleeve** [comment]
Tested in master-5149fc95-head. Verified that the PCI device name is no longer clickable.

![Greenshot 2022-10-14 13 58 03](https://user-images.githubusercontent.com/83787952/195942964-51d42a22-a461-4ebb-b4e7-b3688c827a0a.png)
