### ISSUE TITLE
[BUG] Cannot edit storage class when adding volume on edit VM page

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2926]
**Describe the bug**

Cannot edit storage class when adding volume on edit VM page

**To Reproduce**
1. Go to edit VM page
2. Go volume tab
3. Click the "Add Volume" button

**Expected behavior**

"Storage class" should be editable

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/195532628-92345b26-ccae-4c86-aa1d-adac49448a20.png)

**Comment by irishgordo** [comment]
Thanks for this fix @n313893254  - this looks great :smile: :+1: 

Validated on Harvester Version: master-61a6124a-head 

![Screenshot from 2022-10-14 16-43-07](https://user-images.githubusercontent.com/5370752/195958336-6d0866d4-2e2a-4171-894b-0011c58fd66a.png)
![Screenshot from 2022-10-14 14-16-39](https://user-images.githubusercontent.com/5370752/195958352-407030e0-5aa2-4b09-b5ff-836b08f7afcb.png)
