### ISSUE TITLE
[BUG] Clone default storage also clone the default annotaion

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2928]
**Describe the bug**

**To Reproduce**
1. Go to Advanced -> Storage Classes
2. Clone a storage class which is the default

**Expected behavior**

The storage class which is cloned from the default storage class should not be the default.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/195564276-36262ca0-a204-4098-9a28-593ed5c9fbf6.png)

**Comment by irishgordo** [comment]
@n313893254 thanks for the fix :smile:  - :+1: 
I validated on Harvester Version: master-61a6124a-head 
That this looks good :smile: 
![Screenshot from 2022-10-14 14-13-47](https://user-images.githubusercontent.com/5370752/195945084-e6db6921-293e-4002-93bb-06ba9a1bf8f8.png)
