### ISSUE TITLE
[BUG] All title content in Rancher create loadBalancer Add-on Config page display incorrectly with %variable_name% 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2929]
**Describe the bug**

Open the Create loadBalancer Add-on Config page in Rancher RKE2 cluster management page. 
All title value displayed incorrect %variable_name%  

![image](https://user-images.githubusercontent.com/29251855/195595283-7cfa3fe1-27a2-4891-9a65-98eb8f388c8f.png)

**To Reproduce**
1. Import Harvester to Rancher 
2. Create cloud credential 
3. Provision an RKE2 cluster (V1.24.4)
4. Wait for RKE2 cluster provisioning complete
5. Access RKE2 cluster in Cluster Management page
6. Open Service Discovery -> Services
7. Create a Load Balancer
8. The the Add-on config tab of (replaced by `%harvester.service.title%`)
9. Enable the health check 
10. Check the title content on UI

**Expected behavior**

All title content in Rancher create loadBalancer Add-on Config page should display correctly (e.g)

![image](https://user-images.githubusercontent.com/29251855/195597960-db4336bb-bc93-42b5-a453-dea89f0be46c.png)

**Support bundle**

**Environment**
 - Harvester ISO version: `master-5ee476dd-head` (10/12)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 1 nodes local kvm machine
 - Rancher version: `v2.6.9-rc4`
 - Rancher ui-index: https://releases.rancher.com/ui/release-2.6.9/index.html
 - Rancher ui-dashboard-index: https://releases.rancher.com/dashboard/release-2.6.9/index.html
 - Rancher ui-offline-preferred: Dynamic
 - Harvester ui-index: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html
 - Harvester ui-plugin-index: https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js
 - Harvester ui-source: Auto
 
**Additional context**

**Comment by WuJun2016** [comment]
Hi,  @mantis-toboggan-md   can this issue still be merged into rancher 2.6.9 after the fix ?    If it still merges, can you help fix it?  thanks

**Comment by mantis-toboggan-md** [comment]
Hey @WuJun2016, yes this is small enough to still go in 2.6.9.  I have fixes merged in rancher/dashboard `master` and `release-2.6.9`. The harvester/dashboard port is here: https://github.com/harvester/dashboard/pull/470

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.6.9-rc4` with latest ui-dashboard-index. Close this issue.

### Result
The title content in Add-on Config page of load balancer can display correctly
![image](https://user-images.githubusercontent.com/29251855/195814916-0fd9edbf-5293-46ad-bb47-1a359934d3d5.png)


### Test Information
* Test Environment: 1 node local kvm machine
* Harvester version: `master-0a9538a1-head` (10/14)
* Rancher version: `v2.6.9-rc4`
* ui-dashboard-index: https://releases.rancher.com/dashboard/latest/index.html
* ui-offline-preferred: Remote

### Verify Steps
Refer to reproduce steps in https://github.com/harvester/harvester/issues/2929#issue-1407734440
