### ISSUE TITLE
[BUG] `Install guest agent` is not checked in default templates

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2932]
### Describe the bug
In `v1.0.3`, `Install guest agent` checked by default in all default templates except _windows-iso-image_, but it changed to NOT checked in `v1.1.0-rc2`.

### To Reproduce
1. Create VM by default temlates

### Expected behavior
This more like a breaking change of default template, consider user might use _raw image_ template to create VM without check cloud-config directly, we should bring it back or document it.

## Environment:
 - Harvester ISO version: **v1.1.0-rc2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 5 nodes**

**Comment by chrisho** [comment]
Since the vm template is not configured with cloud-config, add cloud-config raw config to vm template definition.
windows only support cloudbase-init, so define the Linux related template first.

**Comment by chrisho** [comment]
> Since the vm template is not configured with cloud-config, add cloud-config raw config to vm template definition. windows only support cloudbase-init, so define the Linux related template first.

Use secret instead of raw data.

**Comment by noahgildersleeve** [comment]
Tested in master-380ddce1-head. Verified that Guest agent was enabled by default in all templates except for Windows.
![Greenshot 2022-10-21 10 32 56](https://user-images.githubusercontent.com/83787952/197255475-e7dc2cc1-9ed8-4e8f-8468-71bdebbb6a12.png)
![Greenshot 2022-10-21 09 53 24](https://user-images.githubusercontent.com/83787952/197255479-6f0dc2d8-ba6d-4cb8-aa5a-7157560e5e9b.png)
