### ISSUE TITLE
[Question] time and interface mapping

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#2936]
is there a better spot to ask questions? seems the slack channel is relatively dark.

got 3 questions if possbile.

- any pointers on how i can set timezone of my nodes after already forming a cluster?
- is there a way to prevent vms from syncing time with the host? (windows vms specifically)
- how do i map non-default networks to specific interfaces? in my case, i want to map eno4 to a specific network on a vm. i have a 4-port nic, 2 are bonded (10gb) for mtg network, and 1 is assigned to vms as default, i'd like the 4th to be set for a wan-port for a software gateway i'm playing with.

great project btw, i'm using harvester to migrate way from Hyper-V. if anyone needs pointers on converting vms i'd be happy to help. i've successuflly migrated windows (10 and 2012-r2), centos 6/7, and ubuntu 20 vms from hyper-v to Harvester. it was a rough road, but we did it! :) 

Thanks!

**Comment by Aixleft723** [comment]
@albertkohl-monotek  Can you provide me with a document? which is about the migrate vms

**Comment by albertkohl-monotek** [comment]
@sunkai-XDD i made two posts in the issues for a "tutorial"
see: 
#2949 [Tutorial] how to migrate linux hyper-v guest into harvester
#2950 [Tutorial] how to migrate windows hyper-v guest into harvester

**Comment by albertkohl-monotek** [comment]
@guangbochen any thoughts on this question? been open for a while, seems fairly simple. also tried on slack, no response :(

**Comment by w13915984028** [comment]
@albertkohl-monotek   For question 3, please take a look.

https://docs.harvesterhci.io/v1.0/networking/best-practice/multiple-nics-vlan-aware-switch

And could you add a simple digram about your network design. How would you map your HOST's network into VM side.

**Comment by w13915984028** [comment]
For question 2, what is the reason to stop time syncing with host ?

https://stackoverflow.com/questions/42367977/kvm-libvirt-how-to-disable-clock-sync-for-guests

**Comment by albertkohl-monotek** [comment]
@w13915984028 for question 2, one of our machines is a mail server on server 2012. when it first boots up, it gets the hosts time, which is correctly set in utc, but the vm is taking it as the same time, but local. so for example, the host is set to 12pm utc, the host will pick up 12pm MST,  but then sync up with the domain controller for the correct time (i.e. 6am MST). the minute or two it takes to sync can some times cause issues with mail flow. 

same type of issue with domain controller. and from everything i've seen, its usually a best practice to NOT sync time w/ host for these reasons at the vm level. 



as for question 3, i'm not super-great at vlans, i recently wrapped my head around it and my understanding is basically you would bond up mutilple nics if you want to get the througput, but more or less you use vlans to route trunk and route traffic to specific vlans. but thanks for the link, i recently found it and it did help w/ understanding how i had to set things up. i plan to implement it in a few days.

**Comment by albertkohl-monotek** [comment]
@w13915984028  any feedback on the time issue?

**Comment by ibrokethecloud** [comment]
are you please able to try this: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#timezone

`spec.domain.clock` should set the TZ to one of your choice.

**Comment by albertkohl-monotek** [comment]
that worked. specifically:
    spec.domain.clock.timer.kvm: {}   and spec.domain.clock.timezone: America/TZ

the edit yaml page wouldnt let me add just the timezone, without the timer.kvm element as well.

Thanks!
