### ISSUE TITLE
[BUG] installer crashes after inputting hostname

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#2937]
**Describe the bug**

![screenshots](https://user-images.githubusercontent.com/15064560/195757446-04b95ad0-9c16-45ee-b416-0fd74efa8d26.gif)

![image](https://user-images.githubusercontent.com/15064560/195759190-73efdfaf-9c83-43e9-8912-cbd13154fcac.png)

**To Reproduce**
1. use the master-head iso from https://releases.rancher.com/harvester/master/harvester-master-amd64.iso 2022/10/14

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 2022/10/14
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
@futuretea, what's the VGA card? It looks like the dimension is too small to contain all widgets.

**Comment by tjjh89017** [comment]
Do you use VM to test?
Could you provide Libvirt XML for us to test?
thanks a lot

**Comment by bk201** [comment]
Related to https://github.com/harvester/harvester/issues/2708

**Comment by guangbochen** [comment]
there are two ways to workaround, @futuretea can u check if any of them works for u, thanks; move to v1.1.1 and may consider refactoring the network console to a separate page.
- Increasing the VGA resolution. either using some kernel parameters
- Switch to tty2 and manually get IP first. SSH into the node to run the installer

**Comment by futuretea** [comment]
> Do you use VM to test?
> Could you provide Libvirt XML for us to test?

Yes.  The dimension is too small, but I cannot increase the VGA resolution

> Switch to tty2 and manually get IP first. SSH into the node to run the installer

Works

**Comment by codeagencybe** [comment]
@futuretea 
How did you do this: 

_Switch to tty2 and manually get IP first. SSH into the node to run the installer_

I'm facing exactly same problem but I'm not using any serial console. 
My setup is just using an HX90 from minisforum directly connected via HDMI to a monitor. 
I'm a beginner in this area, so any help how I can do workaround 1 or 2 with the the "tty2" would be helpful. 

Thanks!

**Comment by albertkohl-monotek** [comment]
Try something like this:
https://askubuntu.com/questions/66195/what-is-a-tty-and-how-do-i-access-a-tty


Albert Kohl
Director of I.T.
[o.]  (602) 445-3422
[e.] ***@***.******@***.***>
[w.]  www.natimark.com<https://www.natimark.com> | counts.natimark.com<https://counts.natimark.com>
[Better Results through Better Data.]

**Comment by bk201** [comment]
SSH workaround:
- Switch to tty2 (ctrl + alt + f2)
- Login with rancher/rancher and switch to root (`sudo -i`).
- Bring up the network interface; you can use `ip a` to list interfaces first. Take `ens5` as example:
  - Static IP case: `ip a add <addr> dev <interface>`. For example: `ip a add 10.10.0.15/24 dev ens5`.
  - DHCP IP case:
      ```
      echo BOOTPROTO=dhcp > /etc/sysconfig/network/ifcfg-ens5
      wicked ifreload ens5
      ```
- Connect to the machine with ssh (`ssh rancher@<IP>`, **NOTE** maximize the terminal of the ssh session) and run:
  ```
  $ echo $SSH_TTY
  /dev/pts/0
  $ sudo -i
  # TTY="/dev/pts/0" harvester-installer
  ```

**Comment by bk201** [comment]
We also see configuring the `vga` kernel parameter to adjust the resolution might work. Here is an example:
- Stop at GRUB menu.
- Edit first menu entry (`e`)
- Append `vga=792` to the end of the `$linux` line and `Ctrl` + `x` to boot.
<img width="891" alt="image (4)" src="https://user-images.githubusercontent.com/1691518/200271069-17428383-4d17-4c25-91ca-3baf362f3a06.png">

**Comment by guangbochen** [comment]
**To Test:**
- option 1: move the hostname to a new page to avoid the possibility of hitting the crash issue
- option 2: you can choose to use the `VGA 1024x768` entry menu if your output is limited to small dimensions
![image](https://user-images.githubusercontent.com/4569037/200855700-b5cbfcdd-c496-44d0-af30-042d24fd2b64.png)

the long-term solution will depend on the console UI refactoring of https://github.com/harvester/harvester/issues/1422.

**Comment by irishgordo** [comment]
I validated on Harvester Version v1.1.1-rc1 that the options on the grub menu work / exist.
That we can launch installer from both menu options.

And for the work-arounds, validated that:
- a user can use ssh, to complete the install for Harvester as mentioned in: https://github.com/harvester/harvester/issues/2937#issuecomment-1300635489
- a user can modify the first grub entry to add `vga=792` to the args to continue with install, based on: https://github.com/masteryyh/docs/blob/d624b71272c2a4f56f9aa9aef28dbab9eba667dc/docs/install/iso-install.md

Supporting screenshots:
![Screenshot from 2022-11-10 10-30-31](https://user-images.githubusercontent.com/5370752/201178092-cc998452-72a0-4ca2-bc0d-f4e76bff70e3.png)
![Screenshot from 2022-11-10 10-29-24](https://user-images.githubusercontent.com/5370752/201178094-3e10d7e3-d341-414f-a13b-3ba2ffa3634c.png)
![Screenshot from 2022-11-10 10-19-54](https://user-images.githubusercontent.com/5370752/201178095-a012aa8f-908e-4286-8e0c-31c380b436b2.png)
![Screenshot from 2022-11-10 10-16-33](https://user-images.githubusercontent.com/5370752/201178097-7a280b84-d4fd-4301-92ee-02d3e535a288.png)


This looks good :smile: :+1:  - I'll go ahead and close it out!

**Comment by bcdurden** [comment]
> We also see configuring the `vga` kernel parameter to adjust the resolution might work. Here is an example:
> 
> * Stop at GRUB menu.
> * Edit first menu entry (`e`)
> * Append `vga=792` to the end of the `$linux` line and `Ctrl` + `x` to boot.
> 
> <img alt="image (4)" width="891" src="https://user-images.githubusercontent.com/1691518/200271069-17428383-4d17-4c25-91ca-3baf362f3a06.png">

Unfortunately, the fix above did not work for me. The only fix that has worked thus far is the manual running of the installation from an SSH session.

My video device is not limited to a low resolution so I am not certain if this is the core issue. I am using an MSI RTX3060 12gb model as a graphics card.

**Comment by dlaidlaw** [comment]
@bcdurden I have the exact same issue. However, I cannot find any instructions for "manual running of the installation from and SSH session". Any pointers you can give?

**Comment by bcdurden** [comment]
> @bcdurden I have the exact same issue. However, I cannot find any instructions for "manual running of the installation from and SSH session". Any pointers you can give?

This specific comment outlines it and is what I used to bypass the issue.
https://github.com/harvester/harvester/issues/2937#issuecomment-1300635489

I'm happy to report that Harvester 1.1.1 fixes this issue for me, I suspect the real problem ran deeper than a simple resolution issue though these things are quite hard to test for every variation in hardware

**Comment by dlaidlaw** [comment]
@bcdurden Thank you. That got me past the error with Harvester running. I am running 1.1.1 and still had the problem!

**Comment by bcdurden** [comment]
Oh really? I would open a new issue and link this one if someone hasn’t
done that already!
