### ISSUE TITLE
[FEATURE] Reset the NIC input when the NIC does not exist on the selected nodes

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2942]
**Is your feature request related to a problem? Please describe.**

Reset the NIC input when the NIC does not exist on the selected nodes

**Describe the solution you'd like**

- Reset the NIC input when the NIC does not exist on the selected nodes
- Add selected node info upon the selected nodes radio buttons

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/195793660-5c41a7a1-3ae4-4a21-ac61-c077edaf3f6f.png)

![image](https://user-images.githubusercontent.com/18737885/195793686-fc0b7e19-8fd7-41b5-aa35-8ad1bad7c0dc.png)

**Comment by irishgordo** [comment]
@n313893254 this looks good! :+1: 
I tested on Harvester Version: master-7b47d0b7-head.
When the uplink doesn't exist on the selected nodes it does reset as expected :smile: !
