### ISSUE TITLE
[BUG] Can't create VMs

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2947]
**Describe the bug**

When you try to create a VM you get an error and a 500 response
**To Reproduce**
1. Create a new VM

**Expected behavior**

You should be able to create a VM
**Support bundle**

[supportbundle_d8c81821-1508-4c07-9ea6-eb3af635b671_2022-10-14T18-41-32Z.zip](https://github.com/harvester/harvester/files/9789221/supportbundle_d8c81821-1508-4c07-9ea6-eb3af635b671_2022-10-14T18-41-32Z.zip)

**Environment**
 - Harvester ISO version: master-5149fc95-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe-examples Vagrant 3 node

**Additional context**
When creating a VM it seems to be getting a 500 error. The actual response to the POST request is this
```
{"type":"error","links":{},"code":"InternalError","message":"Internal error occurred: failed calling webhook \"virtualmachines.kubevirt.io-tmp-validator\": failed to call webhook: Post \"https://fake-validation-service.harvester-system.svc:443/fake-path/virtualmachines.kubevirt.io?timeout=10s\": service \"fake-validation-service\" not found","status":500,"type":"error"}
```
This seems to happen with both raw image template and ISO template VMs
![Screenshot_20221014_113721](https://user-images.githubusercontent.com/83787952/195918514-2293c5eb-7c96-4937-9861-99e86cd42cb2.png)
![Screenshot_20221014_113653](https://user-images.githubusercontent.com/83787952/195918517-a5395d2a-3adb-4d80-a086-ee6059a349ca.png)

**Comment by tlehman** [comment]
I am also running into this. I found [this issue](https://github.com/kubevirt/hyperconverged-cluster-operator/issues/143) but I don't see anywhere we use the Hyperconverged Cluster Operator.

**Comment by tlehman** [comment]
on version 1.1.0-rc1, there are virt- pods running that aren't running on 1.1.0-rc3:

## 1.1.0-rc1
```
> kubectl -n harvester-system get po | grep virt
virt-api-bdc94b6d9-mwlr9                                    1/1     Running            1 (11m ago)     17d
virt-controller-744978949c-5pmqv                            1/1     Running            2 (11m ago)     17d
virt-controller-744978949c-5zv2c                            1/1     Running            1 (11m ago)     17d
virt-handler-fcdmc                                          1/1     Running            1 (11m ago)     17d
virt-operator-894555c9-ccpd8                                1/1     Running            2 (11m ago)     17d
```

## 1.1.0-rc3

```
> kubectl -n harvester-system get po | grep virt
virt-operator-7f6497cb97-x5ss4
```

**Comment by futuretea** [comment]
Errors in virt-operator pod :
`Failed to create all resources: unable to create crd \u0026CustomResourceDefinition{ObjectMeta:{virtualmachineinstances.kubevirt.io   `
 `customresourcedefinitions.apiextensions.k8s.io \"virtualmachineinstances.kubevirt.io\" already exists`

**Comment by khushboo-rancher** [comment]
Already verified by @noahgildersleeve. Closing this one. Feel free to reopen if you see this again.
