### ISSUE TITLE
[BUG] Default Values Don't Reset To Default After Enabling -> Disabling -> Enabling vm-import Addon

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#2948]
**Describe the bug**
The default values per:
https://github.com/n313893254/dashboard/blob/c8a2774b953ad4e3172bc66ca3b3be9a503260be/pkg/harvester/edit/harvesterhci.io.addon/vm-import-controller.vue#L24-L32

Are not being brought in if a user enables `vm-import` addon, changes the CPU Limit and Memory Limit for instance.
Allows the deployment to be successful for vm-import.
Then disables the vm-import controller.
Waits for vm-import deployment to disappear and other things to clean up.
Then enables vm-import controller for the second time.

**To Reproduce**
1. Go to Advanced Addons
1. elipsis, edit config of VM Import Controller addon
1. Enable, modify CPU Limit & Memory Limit
1. Wait for AddonDeploySuccessful
1. Disable VM Import Controller
1. Wait for deployment to get cleaned up - vm-import-controller to go away, and others
1. Then Enable (for the second time) VM Import Controller
1. You'll notice you have the same CPU Limit & Memory Limit that you did when you enabled it last time

**Expected behavior**
Expecting if it's toggeled (enabled/disabled) - always upon "enable" field values get reset to default.
Per: https://github.com/n313893254/dashboard/blob/c8a2774b953ad4e3172bc66ca3b3be9a503260be/pkg/harvester/edit/harvesterhci.io.addon/vm-import-controller.vue#L24-L32

**Environment**
 - Harvester ISO version:  Version: master-61a6124a-head 
 - Underlying Infrastructure: 3 Node QEMU/KVM , 8C 16Gib Mem

**Additional context**
![default-doesnt-reset-after-upon-re-enabling](https://user-images.githubusercontent.com/5370752/195937696-3a146af5-65f2-4cf1-8401-e87ccb981388.png)

**Comment by WuJun2016** [comment]
Hi,  @irishgordo  I think it's expected that when a user changes the default value we provide the first time, then we consider that value to be meaningful to the user, so we don't automatically reset that value unless the user changes it themselves

**Comment by irishgordo** [comment]
@WuJun2016  - that makes sense to me :smile: 

Since it is intended, should I go ahead and close this out :smile: ?

**Comment by WuJun2016** [comment]
@irishgordo  Yes, I think we can close this issue.  thanks

**Comment by irishgordo** [comment]
@WuJun2016 - sounds good, I'll go ahead and close this out then :smile:
