### ISSUE TITLE
[Tutorial] how to migrate linux hyper-v guest into harvester

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#2949]
brief disclaimer, i make no warrents or guarantees that this'll work and or will not harm your pc. this all worked for me, if it doest work for you or causes you any issues, i'm sorry, but TEST TEST TEST. dont trust me, try it yourself in a non-production enviornment.

### Convert Linux Hyper-V Guest to Harvester
_this worked on centos 6.4/7, and ubuntu 20._
_this requires a middle-man linux machine with virt-v2v installed_

**On Hyper-V:**
- 	Get [qemu-img](https://cloudbase.it/qemu-img-windows/) for windows, and [nginx](http://nginx.org/download/nginx-1.23.1.zip) for windows
- Shutdown Guest, disable auto start and set network adapters to Not Connected to prevent accidental spinup.
- Export the VM to local disk, notate the disk size.
- Convert the image from .vhdx -> sudo using qemu-img:
  - qemu-img convert -O qcow2 $vm.vhdx $vm.qcow2
- Move the $vm.qcow2 file into the html folder on nginx.

**On KVM**
- Download and convert the image
  - Vm=”myvmname”
  - curl "[http://{url}/$vm.vhdx](http://%7Burl%7D/$vm.vhdx)" -o $vm.vhdx
- convert the disk using virt-v2v, I had better results with linux vms using this
  - sudo virt-v2v -i disk $vm.vhdx -o local -of qcow2 -os .
- Place the generated -sdx files into a folder that can can be used to download. i.e. nginx server.
- If you have non-system disks you also have to convert, you have to use qemu-img to convert them because it seems like virt-v2v only looks at system disks.
  - qemu-img convert -O qcow2 $vm.vhdx $vm.qcow2

**On Harvester:**
- Import the qcow2 images from your kvm server using download file (large files will fail uploads).
- Create a VM using Raw Image Template 
  - make sure to set your root disk to the image you downloaded
  - Make the size is at least as large as the disk size from the original vm
  - Make sure to select "Booting in EFI mode" at the bottom of the advanced section, if this was a UEFI vm.

**Comment by guangbochen** [comment]
Harvester upcoming v1.1 release will introduce the https://github.com/harvester/vm-import-controller to help to migrate VMs from another platform into Harvester, loop @ibrokethecloud to check if this is already implemented or can be taken as some reference or future enhancement, thanks.
