### ISSUE TITLE
[Tutorial] how to migrate windows hyper-v guest into harvester

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#2950]
brief disclaimer, i make no warrents or guarantees that this'll work and or will not harm your pc. this all worked for me, if it doest work for you or causes you any issues, i'm sorry, but TEST TEST TEST. dont trust me, try it yourself in a non-production enviornment.

### Convert Windows Hyper-V Guest to Harvester
_this worked on windows 10, and server 2008-r2_

**On Hyper-V:**

- Get [qemu-img](https://cloudbase.it/qemu-img-windows/) for windows, and [nginx](http://nginx.org/download/nginx-1.23.1.zip) for windows
- Shutdown Guest, disable auto start and set network adapters to Not Connected to prevent accidental spinup.
- Export the VM to local disk, notate the disk size.
- Convert the image from .vhdx -> sudo using qemu-img:
  - qemu-img convert -O qcow2 $vm.vhdx $vm.qcow2
- Move the $vm.qcow2 file into the html folder on nginx.

**On Harvester:**
- Import the qcow2 images from your hyper-v server using download file (large files will fail uploads).
- Create a VM using ISO Windows Template 
  - make sure to set your root disk to the image you downloaded
  - Make the size is at least as large as the disk size from the original vm
  - Make sure to select "Booting in EFI mode" at the bottom of the advanced section, if this was a UEFI vm.
- Boot into the Windows install cd for the version of windows the vm was. Select Repair
- Enter Command Prompt
- Commands:
  - wmic logicaldisk get caption
- find the disk that has suse drivers, in my case, it was e:
  - e:
  - cd win8.1-2012r2\x64\pvvx   
    - you can find the correct driver version here: https://docs.harvesterhci.io/v1.0/vm/create-windows-vm/ search for the phrase: "support matrix"
  - drvload pvvxblk.inf
    - This command makes your original vhdx's visible to windows
- Run wmic to find system drive now, in my case it was c:
  - wmic logicaldisk get caption
  - c:
  - dism /image:c:\ /add-driver /driver:e:pvvxblk.inf
  - exit
- turn off pc
- Edit the VMs config and move the rootdisk to the top of the boot order
- Save and start the VM, and it should boot into windows.

**Comment by guangbochen** [comment]
Harvester upcoming v1.1 release will introduce the https://github.com/harvester/vm-import-controller to help to migrate VMs from another platform into Harvester, loop @ibrokethecloud to check if this is already implemented or can be taken as some reference or future enhancement, thanks.

**Comment by averyfreeman** [comment]
This is extremely helpful, thanks! 👍
