### ISSUE TITLE
[BUG] enable storage-network, Networks statistics are incorrect

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2952]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/b62d7e58-a43d-44e6-bd4d-41902b5b5306)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/6e375017-763c-4683-878b-c32b0aa263de)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/b1f3c6bc-04a6-4ea3-ac32-d75c3d72906f)

**To Reproduce**
1. go to setting page
2. enable `storage-network`

**Expected behavior**

The network created by `storage-network` should not be counted

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/196633529-84bb4d68-9ec6-47e0-a30f-d7dad5672b8e.png)
![image](https://user-images.githubusercontent.com/5169694/196633641-81d34b15-777b-4e61-942c-979a3dd25f60.png)


Test Information
----
* Environment: **baremetal DL360G9 4 nodes**
* Harvester Version: **v1.1.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2952#issue-1410829036
