### ISSUE TITLE
[Enhancement]Switch pci-device base image to SLES BCI image

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2954]
**Is your feature request related to a problem? Please describe.**
Replace pci-devices base image with SLE BCI since it is more secure and better maintained. 
refer to https://github.com/harvester/harvester/issues/1868

**Describe the solution you'd like**
- replace the package base image in https://github.com/harvester/pcidevices/blob/master/package/Dockerfile

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by tlehman** [comment]
I'm using this base image: https://github.com/harvester/harvester/blob/v1.1.0-rc3/package/Dockerfile#L1

**Comment by tlehman** [comment]
Testing steps: Install Harvester, check that the PCI devices list is built (after enabling addon), this will be sufficient to test that the base image worked. The only thing we need to make sure is that the pcidb is there, and can be used by the pcidevices-controller to populate the fields of the PCIDevice CRs

**Comment by noahgildersleeve** [comment]
Verified while testing #992 with Harvester master-7b698413-head. Closing as fixed.
