### ISSUE TITLE
[BUG] Terraform Harvester Provider for v1.1.0

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2957]
### Describe the bug
- [ ] **Clusternetwork**: not work
  - ![image](https://user-images.githubusercontent.com/5169694/196163882-b153aa94-de59-433d-a3e9-7322bfc8d21d.png)
- [ ] **network**: blocked by **clusternetwork**

### To Reproduce
1. regression test cases in https://harvester.github.io/tests/manual/_incoming/2261-terraform-import-vlan/

### Expected behavior
should import correctly

## Environment:
 - Harvester ISO version: **v1.1.0-rc2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**
 - Terraform Harvester Provider version: **v0.5.2**

**Comment by futuretea** [comment]
@lanfon72 how do I update the https://harvester.github.io/tests/manual/_incoming/2261-terraform-import-vlan/ docs?

**Comment by lanfon72** [comment]
@futuretea you can submit a PR after modify [this file](https://github.com/harvester/tests/blob/main/docs/content/manual/_incoming/2261-terraform-import-vlan.md), or just add test plan in this issue, we (QA) will update it accordingly.

**Comment by lanfon72** [comment]
When updating vlanconfig's name field, encounter error as below:
![image](https://user-images.githubusercontent.com/5169694/197251054-54e14a38-a6b6-4ccf-95dc-e015c83c36f7.png)

the config could be updated after apply again.
the error might related to #2987

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-f96827b2-head**
* **ui-source** Option: **Auto**
* Terraform Harvester Provider version: **v0.5.3**

### Verify Steps:
- **Steps to reproduce** in https://github.com/harvester/harvester/issues/2957#issue-1411431956,
    relevant regression test cases and https://github.com/harvester/terraform-provider-harvester/pull/54
