### ISSUE TITLE
[BUG] exported tf from Terraformer unable to apply on another cluster

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#2958]
### Describe the bug
- [ ] **Image**: Restore uploaded image not work
- [x] **Network**: Unable to import exported networks
  - The exported `network.tf`
  - ![image](https://user-images.githubusercontent.com/5169694/196156583-ddf9dd50-50ac-4162-a82e-f41484f0e1b5.png)
  - Remove `route_cidr` and `route_gateway`
  - ![image](https://user-images.githubusercontent.com/5169694/196157573-49fe0b16-d9b7-440e-b92d-4e80cf84cbe3.png)
- [x] **Virtualmachine**: `couldinit` not export correctly
  - ![image](https://user-images.githubusercontent.com/5169694/196161185-6f8d261a-580b-408d-9874-46dc9cc57cf4.png)

### To Reproduce
1. regression test cases in https://harvester.github.io/tests/manual/terraformer/

### Expected behavior
should import correctly

## Environment:
 - Harvester ISO version: **v1.1.0-rc2**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**
 - Terraformer Harvester version: **v1.0.1-harvester**
 - Terraform Harvester Provider version: **v0.5.2**

**Comment by futuretea** [comment]
HI @lanfon72 I can't reproduce the `Image`, `Network` and `Virtualmachine` issues.

**Comment by lanfon72** [comment]
update the title and separate volume related issue into #2979 (majoring fix on _Terraformer_)

**Comment by FrankYang0529** [comment]
Hi @lanfon72, it looks like Image and Network are fixed in v1.1.0-harvester terraformer. For `cloudinit` in Virtualmachine, we will introduce a new resource `harvester_secret` for it. Thanks.

**Comment by futuretea** [comment]
1. for the **Restore uploaded image not work**,  we cannot support it for now. related issue: https://github.com/harvester/harvester/issues/2237
3. for the **Unable to import exported networks**, already fixed.
4. for the **couldinit not export correctly**, will be fixed in https://github.com/harvester/terraformer/pull/8

**Comment by futuretea** [comment]
terraform-provider-harvester [v0.6.3](https://github.com/harvester/terraform-provider-harvester/releases/tag/v0.6.3) and terraformer [v1.1.1-harvester](https://github.com/harvester/terraformer/releases/tag/v1.1.1-harvester) released

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/375d94b2-8572-4b69-906d-5655f8531f97)

Image related problem will be tracked in #2237 

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2.0-rc5**
* **ui-source** Option: **Auto**
* **Terraformer** Harvester Version: **v1.1.1-harvester**
* Terraform Harvester Provider Version: **v0.6.3**

### Verify Steps
1. Install Harvester with any nodes
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2958#issue-1411431986
