### ISSUE TITLE
[FEATURE] add hwinfo to supportbundle

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#2961]
Gather hwinfo or dmidecode output to supportbundle.

The hwinfo would need to be added to SLE Micro for Rancher and hwinfo added to the bundle. This is to understand any potential hardware issues, compatibility and scheduling availability for virtual machines. Also to understand longhorn-available hardware like controllers, SSDs. But not limited because we may also need to see GPUs, chipsets and further information for SR-IOV, etc.

**Comment by tjjh89017** [comment]
added in baseos.
It would be fixed in https://github.com/harvester/harvester-installer/pull/367

**Comment by tjjh89017** [comment]
## Test step

1. install harvester
2. switch to root shell
3. check "hwinfo" and "lsusb" commands is existing.

**Comment by abonillabeeche** [comment]
Included. Feel free to close.
