### ISSUE TITLE
[BUG] Host IP is inconsistent

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#2962]
**Describe the bug**
The host is fetching an IPv6 IP from the local network even if the host and VIP config is set to Static. VirtualMachines are not schedulable and they will fail with

> 0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.

and the hosts section show as

<img width="1508" alt="Screenshot 2022-10-17 at 1 50 31 PM" src="https://user-images.githubusercontent.com/5146963/196251117-c8a7c099-b0a6-424c-bfc3-ccd521173375.png">

**To Reproduce**
1. Install harvester 1.1.0rc2-rc3
2. Configure Static node and VIP IPs
3. System boots, I configured custom cert, created a vlan1 network using mgmt
4. Hosts section shows "Host IP is inconsistent, current IP: 10.0.0.22,2601:347:4200:7c30:a9d3:4d0b:4fa6:7b9d, initial IP: 10.0.0.22"

**Expected behavior**
The static IP for VIP and node should be respected/used.

**Support bundle and supportconfig**

[ipv6dhcp-onstatic-setup-supportbundle.zip](https://github.com/harvester/harvester/files/9803336/ipv6dhcp-onstatic-setup-supportbundle.zip)
[scc_glass_221017_1757.txz.zip](https://github.com/harvester/harvester/files/9803345/scc_glass_221017_1757.txz.zip)

**Environment**
 - Harvester ISO version: 1.1.0rc2 and rc3
 - Underlying Infrastructure: AMD Generic system

**Comment by abonillabeeche** [comment]
`rke2.io/internal-ip: 10.0.0.22,2601:347:4200:7c30:a9d3:4d0b:4fa6:7b9d`

```
Addresses:
  InternalIP:  10.0.0.22
  InternalIP:  2601:347:4200:7c30:a9d3:4d0b:4fa6:7b9d
  Hostname:    glass
```

**Comment by abonillabeeche** [comment]
Fix: Disable IPv6

_https://www.suse.com/support/kb/doc/?id=000016980_


```
In the file /etc/sysctl.conf add the following lines:
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```

but of course these don't hold across reboots in harvester.

**Comment by abonillabeeche** [comment]
After
```
# systemctl stop rke2-server
# rke2-killall.sh
# echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6
# systemctl start rke2-server
```

the issue at hand is

`0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
`

New supportbundle after trying to start 2 VMs

[supportbundle-Nopreemptionvictimsfoundforincomingpod.zip](https://github.com/harvester/harvester/files/9805303/supportbundle-Nopreemptionvictimsfoundforincomingpod.zip)

**Comment by bk201** [comment]
> but of course these don't hold across reboots in harvester.

To make it persistent: create a config file under `/usr/local/lib/sysctl.d/` cc @abonillabeeche

**Comment by ibrokethecloud** [comment]
To test using libvirt:

**Create a custom network:**
* create a new network using sample here: https://github.com/harvester/harvester-installer/pull/363#issuecomment-1299388805. This will create a network with ipv6 dhcp enabled.

**New Install path:**
* install harvester v1.1.0 using iso method on a VM and using the network defined above.
* once install is complete, the user should see ipv6 address allocated to nodes. This can be verified in UI and using `kubectl get nodes -o json | jq '.items[].status.addresses'`

* on another VM install harvester master using iso method on a VM and using the network defined above.
* once install is complete, the user should not see ipv6 address allocated to nodes. This again can be verified using `kubectl get nodes -o json | jq '.items[].status.addresses'`

**Upgrade path:**

To produce issue:
* install harvester v1.0.3 using iso method on a VM and using the network defined above.
* once install is complete, the user should see no ipv6 addresses allocated to node. This can be verified using `kubectl get nodes -o json | jq '.items[].status.addresses'`
* Perform offline upgrade to v1.1.0. 
* Once upgrade is complete the harvester cluster should see the "Host IP is incosistent" error.
* The upgraded node will have an additional ipv6 address.  This can be verified using `kubectl get nodes -o json | jq '.items[].status.addresses'`

To check the fix:
* install harvester v1.0.3 using iso method on a VM and using the network defined above.
* once install is complete, the user should see no ipv6 addresses allocated to node. This can be verified using `kubectl get nodes -o json | jq '.items[].status.addresses'`
* Perform offline upgrade to master image 
* During upgrade there may be a transient "Host IP is incosistent error"
* This will disappear post the node reboot performed by the upgrade process.
* The upgraded node will have no ipv6 addresses.  This can be verified using `kubectl get nodes -o json | jq '.items[].status.addresses'`

**Comment by lanfon72** [comment]
@ibrokethecloud, @bk201, I can not confirm that the bug has been resolved.

- In my environment, I have to update `accept_ra=2` before create the virtual network
- qemu/KVM network lost external network after few minutes
- `v1.0.3` can' not offline upgrade to `master-head`
- `v1.1.0` and `master-head` installed successfuly, but VIP is not ready, dashboard is not accessible (with 502 bad gateway)

I tried to use **link-local** or **unique-local** IP range still not able to verify this issue.
I guess it might be my environment issue, I would ask others to verify this bug again.

**Comment by TachunLin** [comment]
### New install path

#### On master including PR 
When we install new Harvester **master** using the customized defined IPv6 DHCP enabled network 
Then ISO install v1.1.0 with DHCP node IP and DHCP VIP

* We did not encounter the Host IP is inconsistent error on Host page
![image](https://user-images.githubusercontent.com/29251855/200791493-542f05ee-3c9d-4526-bb7d-c8a7de336695.png)

* User could not see ipv6 address allocated to nodes. 
  ```
  harv-1109-dhcp:~ # kubectl get nodes -o json | jq '.items[].status.addresses'
  [
    {
      "address": "192.168.101.228",
      "type": "InternalIP"
    },
    {
      "address": "harv-1109-dhcp",
      "type": "Hostname"
    }
  ]
  
  ```

#### On v1.1.0 
When we install new Harvester **v1.1.0** using the customized defined IPv6 DHCP enabled network 
Then ISO install v1.1.0 with DHCP node IP and DHCP VIP

* We could encounter the Host IP is inconsistent error on Host page
![image](https://user-images.githubusercontent.com/29251855/200778501-52c8db9a-06e0-4c1f-aa3b-3587139f68d0.png)

* User could see ipv6 address allocated to nodes. 
  ```
  harv110-dhcp:~ # kubectl get nodes -o json | jq '.items[].status.addresses'
  [
    {
      "address": "192.168.101.167",
      "type": "InternalIP"
    },
    {
      "address": "fd7d:844d:3e17:f3ae::117",
      "type": "InternalIP"
    },
    {
      "address": "harv110-dhcp",
      "type": "Hostname"
    }
  ]
  
  ```

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-f8547728-head` (11/08)

### Verify Steps
1. Create a new network in KVM manger (refer to https://github.com/harvester/harvester-installer/pull/363#issuecomment-1299388805.), which have ipv6 DHCP enabled. 
2. Create a VM and use the ipv6 network. 
3. ISO install v1.1.0 
4. Select DHCP node ip and DHCP vip during the installation
5. Check host IP on Host page 
6. Check the ip allocated to node `kubectl get nodes -o json | jq '.items[].status.addresses'`

**Comment by TachunLin** [comment]
### Upgrade path: v1.0.3 to master 

* When we Install v1.0.3 on IPv6 dhcp enabled custom network, we should not see ipv6 addresses allocated to node. 
![image](https://user-images.githubusercontent.com/29251855/201016382-87c74496-1efd-4b83-a004-8d89e41c8eb4.png)

  ```
  harv103-master:~ # kubectl get nodes -o json | jq '.items[].status.addresses'
  [
    {
      "address": "192.168.101.162",
      "type": "InternalIP"
    },
    {
      "address": "harv103-master",
      "type": "Hostname"
    }
  ]
  
  ```

* Then we do offline upgrade to master 

* During upgrade we encounter "Host IP is incosistent error" during the post-drain upgrading node 
  ![image](https://user-images.githubusercontent.com/29251855/201026247-0d4bf819-012a-452e-92ee-3e7fb7adc237.png)
  
  ```
  harv103-master:~ # kubectl get nodes -o json | jq '.items[].status.addresses'
  [
    {
      "address": "192.168.101.162",
      "type": "InternalIP"
    },
    {
      "address": "fd7d:844d:3e17:f3ae::19f",
      "type": "InternalIP"
    },
    {
      "address": "harv103-master",
      "type": "Hostname"
    }
  ]
  
  ```

* This will disappear after we completely upgrade to master release
  ![image](https://user-images.githubusercontent.com/29251855/201028253-5dee39dd-67d4-41c0-a38d-09ac397f3983.png)
  
  ```
  harv103-master:~ # kubectl get nodes -o json | jq '.items[].status.addresses'
  [
    {
      "address": "192.168.101.162",
      "type": "InternalIP"
    },
    {
      "address": "harv103-master",
      "type": "Hostname"
    }
  ]
  
  ```

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-f8547728-head` (11/08)

### Verify Steps
1. Create a new network in KVM manger (refer to https://github.com/harvester/harvester-installer/pull/363#issuecomment-1299388805.), which have ipv6 DHCP enabled. 
2. Create a VM and use the ipv6 network. 
3. ISO install v1.0.3
4. Select DHCP node ip and DHCP vip during the installation
5. Offline upgrade to master release
6. Check host IP on Host page 
7. Check the ip allocated to node `kubectl get nodes -o json | jq '.items[].status.addresses'`

**Comment by TachunLin** [comment]
Verified the Host IPv6 address would not appear in new install and upgrade path to master release.  
Close this issue.
