### ISSUE TITLE
[BUG] The namespace link of detail page is a wrong route

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2967]
**Describe the bug**

The namespace link of the detail page is a wrong route

**To Reproduce**
1. Create a VM
2. Go to the VM detail page
3. Click the link of the namespace 

**Expected behavior**

Go to the namespace detail page or not allow click the namespace link
**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/196387978-f8d09c6a-40ca-4a19-ab4f-13bf32c9ddea.png)

**Comment by WuJun2016** [comment]
duplicate with https://github.com/harvester/harvester/issues/2916 , so close this issue
