### ISSUE TITLE
[Doc] add pci-devices related docs

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#2970]
**Is your feature request related to a problem? Please describe.**
need to add the pci-devices docs to the v1.1 release. https://docs.harvesterhci.io/next/

**Additional context**
Related to : https://github.com/harvester/harvester/issues/992

**Comment by tlehman** [comment]
PR posted: https://github.com/harvester/docs/pull/210

**Comment by bk201** [comment]
Close, the doc PR is merged.
