### ISSUE TITLE
[BUG] unable to upgrade because of an previous failed upgrade

### ISSUE THREAD

**Issue by try2codesecure** [harvester/harvester#2972]
**Describe the bug**
I tried to upgrade the system from 1.0.2 to 1.0.3.
While the first upgrade process i was hit by this bug:
https://github.com/harvester/harvester/issues/2280#issuecomment-1132410796
https://github.com/harvester/harvester/issues/1983
After an rollback & upgrade of the "rancher-monitoring" & "rancher-monitoring-crd" charts, the system-services successfully upgraded to 1.0.3 but the upgrade process stucks again in the pre-drain state of the first node (phase 4).

![grafik](https://user-images.githubusercontent.com/4202158/196456788-77482662-e68c-45a3-bb60-f03176eb3b78.png)

Against the recommendation (which i read later on) i restarted the upgrade process after a long time of awaiting the stucked upgrade ....

This upgrade stucks again because the annotation from the first upgrade are still present
![grafik](https://user-images.githubusercontent.com/4202158/196459612-c25985da-58bd-4abf-911b-6c36644d316c.png)
![grafik](https://user-images.githubusercontent.com/4202158/196459712-6324dad1-28ab-4e37-a896-9286c89752d4.png)

These pre-drain annotation hooks always retains, even if i try to erase it:
`kubectl -n fleet-local get secrets custom-9b1ce903dca4-machine-plan -o jsonpath='{.metadata.annotations}' | jq .
{
...
  "rke.cattle.io/labels": "{\"harvesterhci.io/managed\":\"true\"}",
  "rke.cattle.io/pre-drain": "{\"IgnoreErrors\":false,\"deleteEmptyDirData\":true,\"enabled\":true,\"force\":true,\"ignoreDaemonSets\":true,\"postDrainHooks\":[{\"annotation\":\"harvesterhci.io/post-hook\"}],\"preDrainHooks\":[{\"annotation\":\"harvesterhci.io/pre-hook\"}],\"timeout\":0}"
}
`

Meanwhile i started all VM's again & all hosts running fine & all volumes are in healthy state.
But i just can't upgrade from this state because of the existing annotations.

**To Reproduce**
1. prepare an 3 node cluster (1.0.2)
2. start an upgrade to 1.0.3
3. hopefully get hit the the bug i described
4. delete an (stucked) ugprade in phase 4
5. try an upgrade again & get stuck because the previous failed upgrade (left annotations)

**Expected behavior**
Able to restart upgrade again & finish the upgrade process.

**Support bundle**
[supportbundle_304fc76c-a328-4321-8bf5-f225c7994734_2022-10-18T14-29-18Z.zip](https://github.com/harvester/harvester/files/9811481/supportbundle_304fc76c-a328-4321-8bf5-f225c7994734_2022-10-18T14-29-18Z.zip)

**Environment**
 - Harvester ISO version: 1.0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by try2codesecure** [comment]
The following things I have already tried & did not work or had no effect:
- restart the upgrade multiple times
- restarted all cluster nodes (one by one)
- delete the annotations
- rollout of system upgrade controller (kubectl -n cattle-system rollout restart deploy/system-upgrade-controller)
- restart rke2-server
- https://docs.harvesterhci.io/v1.0/upgrade/v1-0-2-to-v1-0-3#2-an-upgrade-is-stuck-a-node-is-in-pre-drained-state-case-1 (all longhorn volumes in healthy state, max. 1 snapshot)
- Workaround in https://github.com/harvester/harvester/issues/2907
- manually cordon & uncordon all hosts

**Comment by w13915984028** [comment]
@starbops @bk201  any suggestion ?

**Comment by bk201** [comment]
@try2codesecure Somehow, the support bundle doesn't contain the YAMLs files. Could you help dump:
```
kubectl get nodes -o yaml
kubectl get machines -A -o yaml
```
And plan secrets. `kubectl get secrets  -n fleet-local --selector=cluster.x-k8s.io/cluster-name=local -o yaml` (Suggest DM me).

**Comment by try2codesecure** [comment]
> @try2codesecure Somehow, the support bundle doesn't contain the YAMLs files. Could you help dump:
> 
> ```
> kubectl get nodes -o yaml
> kubectl get machines -A -o yaml
> ```
> 
> And plan secrets. `kubectl get secrets -n fleet-local --selector=cluster.x-k8s.io/cluster-name=local -o yaml` (Suggest DM me).

served on slack ;)

**Comment by try2codesecure** [comment]
@bk201 helped me solving this issue & i finished the upgrade to v1.0.3 on all cluster nodes.
To sum it all up, the following steps resolved the issue:
- the guided use of the "drain" cluster scripts from @bk201 https://github.com/bk201/misc/tree/main/rancher
- cleaned up/removed unused longhorn replica volumes on 1.st harvester node (some of the stopped VM's, had an unreplicated volume (ReplicationCount=1) on that node)
- freed up some space on the 3.rd harvester node (was pretty full, maybe had no effect)
- enabled "Allow Node Drain with the Last Healthy Replica" longhorn option (maybe had no effect)
![image](https://user-images.githubusercontent.com/4202158/199430002-1a9c38ef-aac3-45d6-b819-327550009f6d.png)

Afterwards the "blocking" annotations get removed & i started the upgrade over again & it finished like a charm.

Thanks for the amazing support, specially from @bk201
