### ISSUE TITLE
[BUG] Filter the network created by storage-network in the node drive

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2977]
**Describe the bug**

`storage-network` will automatically create a network, and we should filter it.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/14205b73-424e-4f77-a085-8739b57afbe1)

**To Reproduce**
1. go to setting page,  enable `storage-network`
2. Importing harveste into rancher
3. create harvester node driver

**Expected behavior**

we should filter the network created by `storage-network` in the node drive.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Add any other context about the problem here

**Comment by DaiYuzeng** [comment]
This issue can be verified on rancher master-head.

**Comment by TachunLin** [comment]
Verified **not fixed** on Rancher `v2.7-head` (d1813a2) with Harvester `v1.1.1-rc1`. Move to implement page.

### Result
* The `storage network` seems not been filtered in RKE1 template page 
![image](https://user-images.githubusercontent.com/29251855/202191580-2be38b67-f107-4dfb-a6d3-962dab0d1231.png)


* The network created by `storage-network` can be filtered in the RKE2 cluster provisioning page, 
![image](https://user-images.githubusercontent.com/29251855/202189972-9ee98d13-afcb-4000-a491-ae81ac50a4ba.png)


### Test Information
* Test Environment: 1 node local kvm machine
* Harvester version: v1.1.1-rc1
* Rancher version: `v2.7-head` (d1813a2)

### Verify Steps
1. Open Harvester settings page
2. Enable `Storage Network` 
  ![image](https://user-images.githubusercontent.com/29251855/202191044-bfa83324-080a-4ffc-b3ba-ffb558be936c.png)
3. Import Harvester in Rancher
4. Create cloud credential 
5. Open RKE2 provisioning page 
6. Check the network name field 
7. Create a RKE1 node template 
8. Check the  network name field

**Comment by WuJun2016** [comment]
@TachunLin , because rancher 2.7.0 has been released, the RKE1 issue will be fixed in the next release.  I created a new issue to track the filtering problem of RKE1. https://github.com/harvester/harvester/issues/3163,

**Comment by TachunLin** [comment]
Close this issue. We could track the RKE1 behavior on #3163
