### ISSUE TITLE
All the page content will be highlighted if the ssh is selected on detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#298]
**Steps to reproduce:**
1. On the ssh keys detail page, select the ssh key value to make it be highlighted
2. Go back to the previous page

**Result:**
While going back to the previous page, all the page content will be highlighted
![image](https://user-images.githubusercontent.com/57614736/101318206-e56a4c80-389a-11eb-8232-451175e914a8.png)
![image](https://user-images.githubusercontent.com/57614736/101318214-ebf8c400-389a-11eb-8818-60a17ec7b099.png)

**Comment by DoNotSayYes** [comment]
Validated

**Comment by WuJun2016** [comment]
modification causes other problems, go back first

**Comment by DoNotSayYes** [comment]
Validated
