### ISSUE TITLE
[BUG] enhance node scheduling when vm selects network

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#2982]
**Describe the bug**

When the vm is created, the node matched by the network may be different from the node scheduled by the final vm.

**To Reproduce**
1. go to `Cluster Networks / Config` page,  create a new Cluster Network (eg: test)
2. Create a new `network config` in the `test` Cluster Network. (Select a specific node)
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/431ba9b2-56e7-48af-bf4d-6e0ba964ebd3)
3. go to `Network` page
4. to create a new network (e.g:  `test-untagged`), select `UntaggedNetwork` type and select `test` cluster network. click `Create` button
5. go to VM create page,    fill all required value,  Click `Networks` tab,   select `default/test-untagged` network,  click `Create` button
6. The VM is successfully created, but the scheduled node may not match the Network Config
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/e7e942d2-4200-481d-a96a-8038bdc74ae0)

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/ff9c6ad9-1cb0-4d8e-8728-2f93576d0238)

**Expected behavior**

The node that the VM actually schedules should match the node that the Network Config selects

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Scheduling rule added automatically when select specific network
![image](https://user-images.githubusercontent.com/5169694/197729616-a6fcda2e-42ba-469f-b6c1-9c297bef1a45.png)


Test Information
----
* Environment: **baremetal DL360G9 4 nodes**
* Harvester Version: **master-402df54b-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/2982#issue-1414522175
