### ISSUE TITLE
[FEATURE] Bump snapshot-controller version.

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#2983]
**Describe the solution you'd like**

Bump snapshot-controller from `k8s.gcr.io/sig-storage/snapshot-controller:v4.0.0` to `k8s.gcr.io/sig-storage/snapshot-controller:v5.0.1`

**Test plan**
1. Create a virtual machine with an extra 5Gi volume (volume size can be changed);
2. Create a snapshot for extra volume;
3. Enter the directory mounted using extra volume and create a file named `test`;
4. Execute `ls`, a file named `test` can be seen;
5. Use the snapshot just created to create a restored volume;
6. Wait the volume until its status is `Ready`;
7. Power down VM, use the restored volume to replace the extra volume;
8. Power up VM, enter the directory mounted using extra volume, execute `ls` and `test` file is gone.

**Comment by guangbochen** [comment]
Depends on https://github.com/longhorn/longhorn/issues/4785

**Comment by guangbochen** [comment]
Note: let's switch to using `registry.k8s.io/sig-storage/snapshot-controller` since `k8s.gcr.io` will become deprecated.

**Comment by guangbochen** [comment]
consider to add https://github.com/kubernetes-csi/external-snapshotter/tree/v5.0.1/deploy/kubernetes/webhook-example

**Comment by irishgordo** [comment]
@masteryyh this looks good :smile: 
Built ISO off of master-head,  Version: master-2473b296-head 

Validated that the volume snapshot comes back and if the VM had /etc/fstab setup, the uuid on the drive is the same and everything automounts when the vm comes back up :smile: 

Also validated the webhook as well w/ invalid yaml files.

Also see snapshot-validation-webhook & snapshot-controller - both at v5.0.1 as expected :smile: 

![Screenshot from 2023-07-05 17-14-08](https://github.com/harvester/harvester/assets/5370752/c445dce1-52b2-4ca2-9745-03257e40a211)
![Screenshot from 2023-07-06 15-16-12](https://github.com/harvester/harvester/assets/5370752/260d397b-652e-4897-8b99-3ef0f071d02d)
![Screenshot from 2023-07-06 15-21-35](https://github.com/harvester/harvester/assets/5370752/0d7bfa29-e7b4-46b6-a405-d7a02030006d)
