### ISSUE TITLE
[BUG] Can't display monitoring dashboard after upgrade, alertmanager, prometheus and grafana monitoring pods Terminating

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#2984]
**Describe the bug**

After upgrade from v1.0.3 to `v1.1.0-rc3` finished, we found the grafana monitoring dashboard display empty with error
![image](https://user-images.githubusercontent.com/29251855/196621376-d1840592-7324-46a9-ab4e-a691e05659bc.png)

Further check the following pods display `Terminating` status:
1. alertmanager-rancher-monitoring-alertmanager
2. prometheus-rancher-monitoring-prometheus-0 
3. rancher-monitoring-grafana-647fd577f4-mszdm

![image](https://user-images.githubusercontent.com/29251855/196623294-760be695-5a85-4130-a8d7-4e716168c305.png)

**To Reproduce**
1. Steps to reproduce the behavior:
2. Prepare a 4 nodes v1.0.3 Harvester cluster
3. Install several images
4. Create three VMs
5. Enable Network
6. Create vlan1 network
7. Shutdown all VMs
8. Upgrade to v1.1.0-rc3

**Expected behavior**

1. The Grafana motoring dashboard of cluster and VM metrics should display correctly after upgrade complete
2. The `alertmanager-rancher-monitoring-alertmanager`, `prometheus-rancher-monitoring-prometheus-0` and `rancher-monitoring-grafana-647fd577f4-mszdm` pods have correct  running status 

**Support bundle**

[supportbundle_d28e7921-aa9a-40e9-8e4f-55404b168291_2022-10-19T07-33-59Z.zip](https://github.com/harvester/harvester/files/9817913/supportbundle_d28e7921-aa9a-40e9-8e4f-55404b168291_2022-10-19T07-33-59Z.zip)

**Environment**
 - Harvester ISO version: `v1.1.0-rc3`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes bare metal machines

**Additional context**
After the upgrade, the vip connection lost for several hours, then it come back to normal

**Comment by bk201** [comment]
The pods are stuck with terminating. Take pod `prometheus-rancher-monitoring-prometheus-0` as an example (uid: `4f20ef1b-45be-431c-ae31-ebe6696135fc`).

We see these messages flooding the kuebelet log:
```
E1020 07:13:13.983871    8716 reconciler.go:198] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"pvc-da01983c-4012-488b-837d-c6dc7fdaea76\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-da01983c-4012-488b-837d-c6dc7fdaea76\") pod \"4f20ef1b-45be-431c-ae31-ebe6696135fc\" (UID: \"4f20ef1b-45be-431c-ae31-ebe6696135fc\") : UnmountVolume.NewUnmounter failed for volume \"pvc-da01983c-4012-488b-837d-c6dc7fdaea76\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-da01983c-4012-488b-837d-c6dc7fdaea76\") pod \"4f20ef1b-45be-431c-ae31-ebe6696135fc\" (UID: \"4f20ef1b-45be-431c-ae31-ebe6696135fc\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/vol_data.json]: open /var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"pvc-da01983c-4012-488b-837d-c6dc7fdaea76\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-da01983c-4012-488b-837d-c6dc7fdaea76\") pod \"4f20ef1b-45be-431c-ae31-ebe6696135fc\" (UID: \"4f20ef1b-45be-431c-ae31-ebe6696135fc\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/vol_data.json]: open /var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/vol_data.json: no such file or directory"
```

```
# find /var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/prometheus
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/prometheus/6322ec93
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/prometheus-proxy
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/prometheus-proxy/c375fec5
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/init-config-reloader
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/init-config-reloader/559b0f74
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/config-reloader
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/containers/config-reloader/ecb6f936
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/plugins
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/plugins/kubernetes.io~empty-dir
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volume-subpaths
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volume-subpaths/pvc-da01983c-4012-488b-837d-c6dc7fdaea76
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volume-subpaths/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/prometheus
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volume-subpaths/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/prometheus/2
find: ‘/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volume-subpaths/pvc-da01983c-4012-488b-837d-c6dc7fdaea76/prometheus/2’: Input/output error
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/etc-hosts
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~configmap
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~csi
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~empty-dir
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~secret
/var/lib/kubelet/pods/4f20ef1b-45be-431c-ae31-ebe6696135fc/volumes/kubernetes.io~projected
```

From Longhorn GUI, the PVC is already detached.

Found a similar issue in Longhorn: https://github.com/longhorn/longhorn/issues/2368

**Comment by PhanLe1010** [comment]
This one seem to be related to the upstream issue
* https://github.com/kubernetes/kubernetes/issues/101378
* https://github.com/kubernetes/kubernetes/issues/101911

What is the Kubernetes version in this ticket?

**Comment by Vicente-Cheng** [comment]
We still investigate the root cause of this issue. And looks like this issue does not easy to reproduce.

There is a workaround that forces delete the pods that are stuck on the terminating status.

using the following command for it:
`kubectl delete pod <name of pod that is stuck on the terminating status> --force -n <related namespace>`
e.g.
`kubectl delete pod kuberancher-monitoring-grafana-647fd577f4-mszdm  --force -n cattle-monitoring-system`
`kubectl delete pod alertmanager-rancher-monitoring-alertmanager  --force -n cattle-monitoring-system`
`kubectl delete pod prometheus-rancher-monitoring-prometheus-0 --force -n cattle-monitoring-system`

**Comment by FrankYang0529** [comment]
I found a way to reproduce this, but it can't always be successful.

1. Run `systemctl stop rke2` on each node.
2. After 10 seconds.
3. Run `systemctl restart rke2` on each node.
4. Check the status of pod `prometheus-rancher-monitoring-prometheus-0` and `alertmanager-rancher-monitoring-alertmanager-0`.

**Comment by bk201** [comment]
Thank @FrankYang0529, somehow related to we [set rkeConfig back to default value after an upgrade](https://github.com/harvester/harvester/pull/2918). It triggers rke2-server/agent simultaneous restarts on all nodes.

**Comment by w13915984028** [comment]
@bk201 @FrankYang0529 :

Just a question: what is the internal relationship between `stop&start rke2` and `prometheus pod stucks in terminating` ?  Does it mean `stop&start rke2 will cause all PODs are replaced` ?  thanks.

**Comment by FrankYang0529** [comment]
> Just a question: what is the internal relationship between `stop&start rke2` and `prometheus pod stucks in terminating` ? Does it mean `stop&start rke2 will cause all PODs are replaced` ? thanks.

I only observed that prometheus pods might be terminated and run again; other pods look fine. Please check the pod age time.

```bash
$ kubectl get pod -A | grep prometheus
cattle-monitoring-system    prometheus-rancher-monitoring-prometheus-0               3/3     Running     0             100s
cattle-monitoring-system    rancher-monitoring-prometheus-adapter-8846d4757-wb2j8    1/1     Running     0             90m
cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-sxhd9        1/1     Running     0             90m
```

**Comment by w13915984028** [comment]
The `prometheus` POD uses PV(LH volume) to store data.  Most of the other PODs are not using PV.

Maybe: the `stop&start rke2` triggers some logic in LH, and LH deletes the `prometheus` POD, then causes it to be forcely replaced.  

The `grafana` POD is also using PV, it should also be affected.

**Comment by w13915984028** [comment]
When LH tries to delete the POD is described here:  https://github.com/harvester/harvester/issues/2013#issuecomment-1196944952

@PhanLe1010 Regarding our previous discussion in #2013, the `stop&start rke` seems also trigger LH to delete the POD, this sounds a bit strange.

**Comment by TachunLin** [comment]
Verified **not fixed** on `v1.1.1-rc1`. Move to implement stage.

### Result
After completely upgrade to v1.1.1-rc1, we check the monitoring dashboard for 60 minutes

* The monitoring chart display `Fail to load graph` 
![image](https://user-images.githubusercontent.com/29251855/201316898-47650065-011a-4d59-8a61-798f120117ee.png)

* Dashboard display empty and keeps in `Loading`
![image](https://user-images.githubusercontent.com/29251855/201317889-aa812437-2087-4124-ad8d-56b7b96fb1df.png)

* Check the `alertmanager-rancher-monitoring-alertmanager`, `prometheus-rancher-monitoring-prometheus-0` and `rancher-monitoring-grafana` pods **did not** terminating 
![image](https://user-images.githubusercontent.com/29251855/201318168-232b4d53-cd16-42d9-80cc-bd55d1ec8b1b.png)


### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: `v1.1.1-rc1`

### Verify Steps

1. Prepare a 4 nodes v1.0.3 Harvester cluster
2. Install several images
3. Create three VMs
4. Enable Network
5. Create vlan1 network
6. Shutdown all VMs
7. Upgrade to v1.1.1-rc1 
8. Monitoring the dashboard page 
9. Use K9s to monitor pods status

### Support Bundle
[supportbundle_10acb06a-f083-467e-ab87-c23d8e8aeeeb_2022-11-11T10-13-39Z.zip](https://github.com/harvester/harvester/files/9989377/supportbundle_10acb06a-f083-467e-ab87-c23d8e8aeeeb_2022-11-11T10-13-39Z.zip)

**Comment by w13915984028** [comment]
In the grafana.log in the support-bundle, there are many such error:

> 2022-11-11T10:07:01.127109457Z t=2022-11-11T10:07:01+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr=10.84.132.10 referer="https://10.84.132.32/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light" error="http: proxy error: context canceled"

>2022-11-11T10:07:01.127160977Z t=2022-11-11T10:07:01+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=10.84.132.10 time_ms=180003 size=0 referer="https://10.84.132.32/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light"

In grafana-proxy.log, there are:

> 2022-11-11T10:07:22.198546569Z 2022/11/11 10:07:22 [warn] 23#23: *1497 upstream server temporarily disabled while reading response header from upstream, client: 10.52.2.0, server: , request: "GET /api/datasources/proxy/1/api/v1/query_range?query=sum(node_load5%20OR%20avg_over_time(windows_system_processor_queue_length%5B5m%5D))%20by%20(instance)&start=1668160740&end=1668161040&step=60 HTTP/1.1", upstream: "http://[::1]:3000/api/datasources/proxy/1/api/v1/query_range?query=sum(node_load5%20OR%20avg_over_time(windows_system_processor_queue_length%5B5m%5D))%20by%20(instance)&start=1668160740&end=1668161040&step=60", host: "10.84.132.32", referrer: "https://10.84.132.32/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light"

> 2022-11-11T10:07:22.198684774Z 2022/11/11 10:07:22 [error] 23#23: *1497 upstream timed out (110: Operation timed out) while reading response header from upstream, client: 10.52.2.0, server: , request: "GET /api/datasources/proxy/1/api/v1/query_range?query=sum(node_load5%20OR%20avg_over_time(windows_system_processor_queue_length%5B5m%5D))%20by%20(instance)&start=1668160740&end=1668161040&step=60 HTTP/1.1", upstream: "http://[::1]:3000/api/datasources/proxy/1/api/v1/query_range?query=sum(node_load5%20OR%20avg_over_time(windows_system_processor_queue_length%5B5m%5D))%20by%20(instance)&start=1668160740&end=1668161040&step=60", host: "10.84.132.32", referrer: "https://10.84.132.32/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light"

**Comment by w13915984028** [comment]
Meanwhile, I can `create` the screnario of `Faild to load graph` via steps:
1. create a 2-node cluster
2. via `kubectl delete pods -n cattle-monitoring-system prometheus-rancher-monitoring-prometheus-0` to let this pod to be replaced to 2rd node
3. power off the 2rd node
4. now there `Failed to load graph` will come.

The difference is, the `grafana` pod has such error log:

>t=2022-11-14T15:54:00+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=192.168.122.1 time_ms=7227 size=0 referer="https://192.168.122.131/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light"

>t=2022-11-14T15:54:00+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=0 orgId=1 uname= path=/api/datasources/proxy/1/api/v1/query_range remote_addr=192.168.122.1 referer="https://192.168.122.131/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&kiosk&from=now-5m&to=now&refresh=30s&theme=light" error="http: proxy error: dial tcp 10.53.222.169:9090: connect: connection refused"




![image](https://user-images.githubusercontent.com/31133476/201706398-a2ae33bb-fe57-4052-8852-9a854171b1f4.png)

(Even click `Reload`, the graph still fail)

**Comment by w13915984028** [comment]
The difference between the error message of `grafana` POD:

In David's support bundle
` msg="Data proxy error" ...  error="http: proxy error: context canceled" `

In manual created scenario:
` msg="Data proxy error" ... error="http: proxy error: dial tcp 10.53.222.169:9090: connect: connection refused"`

Will continue to investigate.

**Comment by TachunLin** [comment]
Continue checking the monitoring chart in 3 hours, encounter once the `failed to load graph` then after 2-3 minutes the chart can recover to display content.  

![failed](https://user-images.githubusercontent.com/29251855/201810858-78390838-947a-4398-aa8a-d132969e9833.png)
![recovered](https://user-images.githubusercontent.com/29251855/201810862-ad8f4eb0-8d9f-4211-bfdb-3919d651da99.png)

And during the monitoring period, never encounter the `Terminating` status on the following pods:

1. alertmanager-rancher-monitoring-alertmanager
2. prometheus-rancher-monitoring-prometheus-0
3. rancher-monitoring-grafana-647fd577f4-mszdm

**Comment by w13915984028** [comment]
connect with a previous issue : #2150 ` [[BUG] The Prometheus monitoring chart become empty after staying on dashboard page for a period of time]`

**Comment by bk201** [comment]
@TachunLin We fixed issues that the pods are staying in terminating. Should we track the Grafana loading issue with another new one or use #2150?

**Comment by TachunLin** [comment]
I suggest we can track the Grafana loading issue in #2150 and close the this one. 
Since the they have similar behavior of dashboard somehow become empty but can recover after a short period.
