### ISSUE TITLE
[BUG] Can't remove or reassign a PCI device

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#2991]
**Describe the bug**

When you try to remove or reassign a PCI device it will give an error.
**To Reproduce**
1. Add a GPU for passthrough
2. Assign it to a VM
3. Make sure it shows up
4. Unassign it by adding the Available device then removing it in edit config and hit save
5. Make sure it's removed
6. Assign it to a new VM or re-add it to the same one

**Expected behavior**

You should be able to reassign a PCI device
**Support bundle**

[supportbundle_5a4d5e9f-2ca8-4245-a40a-571728dce3fb_2022-10-19T20-13-28Z.zip](https://github.com/harvester/harvester/files/9823958/supportbundle_5a4d5e9f-2ca8-4245-a40a-571728dce3fb_2022-10-19T20-13-28Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node DL160

**Additional context**
This might be related to the UI bug https://github.com/harvester/harvester/issues/2975 . The only way I found of getting the device back to available is by reinstalling the node.

![Greenshot 2022-10-19 13 13 04](https://user-images.githubusercontent.com/83787952/196795173-c179e32b-7d7a-4c20-ad85-3f04f2624262.png)

**Comment by tlehman** [comment]
Possibly a duplicate of #2820

**Comment by tlehman** [comment]
This will be solved by the implementation of this [DevicePlugin HEP](https://github.com/tlehman/harvester/blob/hep-dp/enhancements/20221028-pci-deviceplugin.md). The reason this will fix it is that the device plugin will correctly account for the number of allocatable devices. Currently this has to be done by changing the KubeVirt CR.

**Comment by tlehman** [comment]
I just verified that the branch in the DevicePlugin PR https://github.com/harvester/pcidevices/pull/35 fixes this issue

**Comment by noahgildersleeve** [comment]
Tested in `v1.1-e1905897-head`. 
## Verification Steps
1. Add a GPU for passthrough
2. Assign it to a VM
![Greenshot 2023-03-14 13 21 21](https://user-images.githubusercontent.com/83787952/225128692-d42d2d69-bc0a-414f-b74a-38b32c6f6075.png)
3. Make sure it shows up
4. Install cuda samples
5. Run Cuda verification
![Greenshot 2023-03-14 13 19 22](https://user-images.githubusercontent.com/83787952/225128773-3f7ef551-4dcb-495d-b4dd-79e4331459d3.png)
6. Remove GPU from PCI devices on VM
7. Reboot VM
8. Verify that you can't run the cuda samples again
![Greenshot 2023-03-14 13 22 44](https://user-images.githubusercontent.com/83787952/225128817-68b7e18e-d8ee-4d85-a7d4-fc49aae6482d.png)
9. Add the GPU back
10. Reboot
11. Verify that you can run the cuda Samples again
![Greenshot 2023-03-14 13 24 38](https://user-images.githubusercontent.com/83787952/225128876-80964f78-335c-41b0-8a76-88d48d8cca6d.png)
