### ISSUE TITLE
[BUG] Cluster member should hide the add-on link on PCI-device page

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2994]
**Describe the bug**

Cluster members should hide the add-on link on the PCI-device page

**To Reproduce**
1. Go to the PCI-device page
2. Click the link of the warning banner

**Expected behavior**

Hide the link or navigate to add-on page

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
![image](https://user-images.githubusercontent.com/18737885/196841929-fff01310-e51f-4496-a824-d40110d977d1.png)

**Comment by noahgildersleeve** [comment]
Tested in Harvester v1.1.0-rc3 with forced external ui-index source and Rancher v2.6.9. Verified that link was removed from PCI devices page

![Screenshot_20221020_132558](https://user-images.githubusercontent.com/83787952/197050959-11476819-be23-4753-989c-3a187e7ccec6.png)
