### ISSUE TITLE
[BUG] Verify ClusterNetwork & VLAN Config for storage network setting in backend

### ISSUE THREAD

**Issue by tjjh89017** [harvester/harvester#2995]
**Describe the bug**

Storage Network didn't verify cluster network and VLAN config are correct and expected.
Users must ensure the Cluster Network is configured and VLAN Config will cover all nodes and ensure the network connectivity is working and expected in all nodes.

Currently, Harvester cannot import Network Controller's module, so webhook cannot verify cluster network and vlan config.

**To Reproduce**

1. Create ClusterNetwork
2. Don't create VLAN Config
3. assign ClusterNetwork to the storage network setting

**Expected behavior**

get an error or warning message.

**Support bundle**

**Environment**
 - Harvester ISO version:  1.1.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
@bk201 could we schedule this issue for a specific milestone?

**Comment by bk201** [comment]
I temporarily moved it to 1.2.0 for now, but we still need to check our items.

**Comment by rrajendran17** [comment]
The bug mentioned in this ticket #2995 is not valid anymore as without vlan config, the cluster network will not move to Ready state and storage network cannot be configured on a cluster network which is not in ready state.

The two issues that has to be fixed as part of this ticket are,
1.deleting a cluster network should give a warning/error when storage network is attached to that cluster network
2.deleting a vlanconfig should give a warning/error when storage network is attached to that vlan config.

**Comment by rrajendran17** [comment]
@WebberHuang1118 
I see currently we use caches like vlanCanche, ClusterCache,nadCache etc to validate configs within the webhook.
For example, cluster network uses the vlancache (https://github.com/harvester/network-controller-harvester/blob/7384dcc0485e280dc2c0f64d7f2949b1fa60fb9d/pkg/generated/controllers/network.harvesterhci.io/v1beta1/vlanconfig.go#L66)
 to validate if it any vlanconfig still exists and cluster network deletion will be prevented based on this check.
https://github.com/harvester/network-controller-harvester/blob/9892fc188d42b327e968acd2827038142f2085ad/pkg/webhook/clusternetwork/validator.go#L56


Storage network stores the config(vlan,IP Range,cluster network etc) in longhornSettingCache 
https://github.com/harvester/harvester/blob/1de62862996e666078180d391def496abb00d528/pkg/controller/master/storagenetwork/storage_network.go#L791

If the cluster network webhook validator has to validate if there are any references to the cluster network is still active by storage networks, then cluster network has to know about the longhornSettingCache.
Our current network-controller-harvester code do not have any references to longhorn settings now.
I am not sure if it is straight  forward to import longhorn settings to network-controller-harvester. Are there any dependencies associated with importing a longhorn settings to network-controller-harvester code ?

Also do you know if there is a command from harvester node to view all these caches created ?

**Comment by rrajendran17** [comment]
I can try using the following resource (it says its stored in kubernetes) from longhorn for storage networks in harvester network-controller.

// SettingClient interface for managing Setting resources in Kubernetes.
type SettingClient interface {
	generic.ClientInterface[*v1beta2.Setting, *v1beta2.SettingList]
}

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 I see currently we use caches like vlanCanche, ClusterCache,nadCache etc to validate configs within the webhook. For example, cluster network uses the vlancache (https://github.com/harvester/network-controller-harvester/blob/7384dcc0485e280dc2c0f64d7f2949b1fa60fb9d/pkg/generated/controllers/network.harvesterhci.io/v1beta1/vlanconfig.go#L66) to validate if it any vlanconfig still exists and cluster network deletion will be prevented based on this check. https://github.com/harvester/network-controller-harvester/blob/9892fc188d42b327e968acd2827038142f2085ad/pkg/webhook/clusternetwork/validator.go#L56
> 
> Storage network stores the config(vlan,IP Range,cluster network etc) in longhornSettingCache
> 
> https://github.com/harvester/harvester/blob/1de62862996e666078180d391def496abb00d528/pkg/controller/master/storagenetwork/storage_network.go#L791
> 
> If the cluster network webhook validator has to validate if there are any references to the cluster network is still active by storage networks, then cluster network has to know about the longhornSettingCache. Our current network-controller-harvester code do not have any references to longhorn settings now. I am not sure if it is straight forward to import longhorn settings to network-controller-harvester. Are there any dependencies associated with importing a longhorn settings to network-controller-harvester code ?
> 
> Also do you know if there is a command from harvester node to view all these caches created ?

Hi @rrajendran17 

We can track through `clusternetworks` -> `vlanconfigs` -> `vlanstatuses` to verify if the storage network covers all the nodes. The Harvester controller doesn't have some of the above resources' cache currently, so we need to add the implementation.

**Comment by w13915984028** [comment]
When analyzing https://github.com/harvester/harvester/issues/4355 also noticed that, the storage-network seems not closely collaborating with network controller. E.g. the validator & controller does not check if the target `clusternetwork` is existing. From UI it is OK, but from kubectl/api it seems not fully ok.

https://github.com/harvester/harvester/blob/3bba1d6dcc17589fe9607aff38bea7614065b8be/pkg/webhook/resources/setting/validator.go#L979

```
type Config struct {
	ClusterNetwork string   `json:"clusterNetwork,omitempty"`
	Vlan           uint16   `json:"vlan,omitempty"`
	Range          string   `json:"range,omitempty"`
	Exclude        []string `json:"exclude,omitempty"`
}
```

**Comment by rrajendran17** [comment]
@w13915984028 Thanks, you are right,  this was one of the things we were discussing yesterday
(me and @WebberHuang1118 ).
Currently we need to fix the following.I am working on the changes.

1.storage network in harvester need to validate if cluster network is ready and also confirm if 
  underlying vlanconfig covers all nodes in the cluster.
2.cluster network in network-controller should validate if any storage network is still attached to it during its deletion.
3.vlan config in network-controller should validate if any storage network is still attached to it during its deletion.

**Comment by rrajendran17** [comment]
case 2 and case 3 (harvester-network-controller).Posted for review
https://github.com/harvester/network-controller-harvester/pull/115

**Comment by w13915984028** [comment]
Please also take a look of document PR: https://github.com/harvester/docs/pull/640, which mentions how to change the MTU of a StorageNetwork.

**Comment by rrajendran17** [comment]
case 1:
storage network in harvester need to validate if cluster network is ready and also confirm if
underlying vlanconfig covers all nodes in the cluster.

https://github.com/harvester/harvester/pull/6538/ 

Case 2

vlan config in network-controller should validate if any storage network is still attached to it during its deletion.

https://github.com/harvester/network-controller-harvester/pull/115

**Comment by rrajendran17** [comment]
Pull requests:
https://github.com/harvester/network-controller-harvester/pull/115
https://github.com/harvester/harvester/pull/6538/

**Comment by w13915984028** [comment]
@mingshuoqiu Please do not close the issue directly, it should move to `Ready for Testing` for QA to validate. .

@rrajendran17 Please fill this form https://github.com/harvester/harvester/issues/2995#issuecomment-2349363892 to include the related PRs, and add a (link to) test plan in the issue.

thanks.

**Comment by lanfon72** [comment]
Verified this bug not been fixed yet, move back to implement.

Network configuration could be deleted in **Case 2 and 3**, which will let the cluster network (using by storage network) not includes all nodes.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-97e60e1-head**
* **ui-source** Option: **Auto**

### Verify Steps
#### Prerequisite
1. Install Harvester with at least 2 nodes
2. Create Cluster network `CN1` then create network configuration map to each nodes

#### Case 1
1. Delete one of network configuration, so the cluster network `CN1` will not includes all nodes
2. Enable storage network on cluster network `CN1`
3. Storage network should not able to be enabled

#### Case 2
1. Enable storage network on cluster network `CN1`
2. Delete one of network configuration, so the cluster network `CN1` will not includes all nodes.
3. Network configuration under `CN1` should not able to be deleted

#### Case 3
1. Enable storage network on cluster network `CN1`
2. Create an image for VM creation
3. Create VM `vm1` with mgmt network and make sure it is running
4. Delete one of network configuration, so the cluster network `CN1` will not includes all nodes.
5. Network configuration under `CN1` should not able to be deleted

#### Case 4
1. Enable storage network on cluster network `CN1`
2. Create an image for VM creation
3. Create VM `vm1` with mgmt network and make sure it is running
4. Disable storage network
5. Storage network should not able to be disabled

**Comment by rrajendran17** [comment]
@lanfon72 case 2 and case 3 depends on changes from harvester-network-controller.The following webhook in harvester-network-controller takes care of preventing the deletion of vlanconfig if storage network is still attached to the cluster network.
(master)
https://github.com/harvester/network-controller-harvester/blob/f81a6225dc7fc135b0ca1e28f1da109b8e4b66b6/pkg/webhook/vlanconfig/validator.go#L236

I see harvester v1.4 is still pointing to the v1.3.1 of harvester-network-controller (https://github.com/harvester/harvester/blob/2895569b0674b205afa2007e82c7dc0c816dac4f/go.mod#L74)which does not have the changes
https://github.com/harvester/network-controller-harvester/pull/115

I believe that could be the reason its not working.Do I have to back port the changes of https://github.com/harvester/network-controller-harvester/pull/115 to v1.3.1 ?

**Comment by bk201** [comment]
@rrajendran17 I guess we will have the correct version after merging this PR: https://github.com/harvester/harvester/pull/6654 (can you double check).

@w13915984028 
please help verify the corresponding change is in the stable branch (in this case it's v1.4) before moving an issue to ready for testing (merge in the master is not enough).

**Comment by starbops** [comment]
@rrajendran17 There are two kinds of dependencies: code-level and behavior-level. I don't see that #6538 depends on any change introduced in harvester/network-controller-harvester#115 at the code level. So bumping go.mod will not solve the issue. However, we need the new behavior, which is the validator change, to be effective in Harvester v1.4. That means we need to bump the network controller's images (precisely, harvester-network-webhook). Does that make sense to you?

**Comment by rrajendran17** [comment]
@bk201 @starbops Thanks, you are right.The changes in harvester-network-controller relevant to this bug is released in v0.5.3 tag.
https://github.com/harvester/network-controller-harvester/releases/tag/v0.5.3

https://github.com/harvester/harvester/pull/6654/files took care of bumping the harvester-network-controller version to v0.5.3 which was merged yesterday.
Is there a way to check if particular build has specific changes expected ? I usually get build from the below path
http://172.19.96.23/iso/v1.4/

**Comment by tserong** [comment]
> Is there a way to check if particular build has specific changes expected ? 

If you've got harvester installed, you can run `cat /etc/harvester-release.yaml`, or you can loopback mount the ISO image and check there as it also includes this file. You'll see a list of component versions. For release builds it'll just be the tagged version (e.g. v1.3.2 or whatever), but for daily builds from master or stable branches you'll see a commit hash, for example I have build of master from a few days ago which shows:

```
harvester: 606f4855
harvesterChart: 0.0.0-master-606f4855
installer: 2429491
os: Harvester master
kubernetes: v1.29.8+rke2r1
rancher: v2.9.2
monitoringChart: 103.1.1+up45.31.1
loggingChart: 103.1.0+up4.4.0
kubevirt: 1.2.2-150500.8.21.1
minUpgradableVersion: ''
rancherDependencies:
  fleet:
    chart: 104.0.2+up0.10.2
    app: 0.10.2
  fleet-crd:
    chart: 104.0.2+up0.10.2
    app: 0.10.2
  rancher-webhook:
    chart: 104.0.2+up0.5.2
    app: 0.5.2
```

In this case, I've got everything up to and including https://github.com/harvester/harvester/commit/606f4855 from the main harvester repo, and everything up to and including  https://github.com/harvester/harvester-installer/2429491 from harvester-installer.

(If you're looking at v1.4 ISOs or v1.3 ISOs, they will have been built from the v1.4 and v1.3 branches, not from master)

**Comment by rrajendran17** [comment]
I also realized that relevant  changes for this bug (https://github.com/harvester/harvester/pull/6538)) from "harvester repo" are only in master and needs a backport to v1.4 harvester.
Created a backport PR https://github.com/harvester/harvester/pull/6697

@lanfon72 Possibly case 1 and case 4 worked because I believe you verified via UI and frontend already have the changes long back and this bug takes care of backend changes and its missing in v1.4 branch of harvester repo.

**Comment by rrajendran17** [comment]
@lanfon72 v1.4-rc2 has all the changes (network-controller and harvester).And I verified from dev perspective and it works fine.Moving it to "Ready to Testing"

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/efc43626-4d87-4311-a789-40d7c536ae0f)
![image](https://github.com/user-attachments/assets/6a150513-f1e9-4681-95e2-4761177dfd58)



Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.4.0-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/2995#issuecomment-2383122113
