### ISSUE TITLE
[Enhancement] Allow Rancher to edit ui-source and ui-index that belongs to Harvester.

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#2996]
**Is your feature request related to a problem? Please describe.**

Allow Rancher to edit ui-source and ui-index that belongs to Harvester. Without this enhancement, the user needs to go to login Harvester and edit these tow settings.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in Harvester v1.1.0 and Rancher v2.6.9. Verified as fixed.
