### ISSUE TITLE
[ENHANCEMENT] remove command from pod-container definition in network related charts

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#2997]
**Describe the bug**

There are `command` defined in harvester-network-controller charts, it will overwrite the related value defind in container.

As the container `Dockerfile` has already defined `[CMD]`, it is redundant. And the change in `Dockerfile` will also have no effect.

```
e.g.

          command:
            - harvester-network-webhook
```

https://github.com/harvester/charts/blob/master/charts/harvester-network-controller/templates/deployment.yaml#L41

https://github.com/harvester/charts/blob/master/charts/harvester-network-controller/templates/deployment.yaml#L104

**To Reproduce**
1. Change `[CMD]` in Dockerfile, build docker image
2. Re-deploy POD, the POD-container still use the command defined in chart.

**Expected behavior**

Unless special consideration, do not overwrite the `[CMD]` defined in `Dockerfile` for those purpose POD.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.1.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

cc @yaocw2020

**Comment by w13915984028** [comment]
Encountered in debugging #2941 , the change to webhook `Dockerfile [CMD] ` did no work.

**Comment by yaocw2020** [comment]
The `command` is required, otherwise, the error following will occur. @w13915984028 
```
Warning  Failed     6s (x2 over 10s)  kubelet            Error: failed to create containerd task: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "manager": executable file not found in $PATH: unknown
```

**Comment by guangbochen** [comment]
Close as this will not be fixed.

**Comment by w13915984028** [comment]
Even though we may not enhance it at this moment, but understanding a bit more does no harm:

Simply remove the `command `will cause error like ` "manager": executable file not found in`, because `manager` is the first param to `command`.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/31133476/220098544-d06be73e-aa82-4827-b606-71090d9fa77d.png">

Lets have a look how Harvester does:

<img width="982" alt="image" src="https://user-images.githubusercontent.com/31133476/220098876-9a11d246-0de4-424d-ab78-57ba2dcba31d.png">

why use `tini`  ass root process https://github.com/krallin/tini

https://github.com/harvester/harvester/blob/master/package/Dockerfile#L46
<img width="434" alt="image" src="https://user-images.githubusercontent.com/31133476/220099024-aa873ade-1fdf-411d-90ec-43b15b70627c.png">


https://github.com/harvester/network-controller-harvester/blob/master/package/Dockerfile#L6

https://github.com/harvester/network-controller-harvester/blob/master/cmd/network-controller/main.go

The main differences are:

```
                             harvester             network-controller-harvester
 tini as root process        yes                       no
all params can be ENV        yes                       no
directly modif 
  docker image to debug      yes                       no
```
