### ISSUE TITLE
[Question] Possible to copy file to node from locally-attached disk?

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#3002]
Currently previewing Harvester-20221014 aka v1.1.0-rc3

I'm wanting to migrate some systems to Harvester, but uploading images from the web UI is time-consuming and unreliable.

I'd rather copy the image files via a disk connected physically to a node to a specified location on the filesystem.  

Is this possible?

**Comment by w13915984028** [comment]
There is no handy solution for it now.

Technically speaking, Harvester utilizes Longhorn as the persistant storage, and when creating image in WebUI, the source file can be either an remote http link, or from local file in the client PC.  Longhorn will download this file and convert it into an image file. It does not support using a local file in the the Cluster NODE path as the source file yet.

**Comment by w13915984028** [comment]
One hack you may try:

Navigate to your file local of your local disk, start a simple http server via python3

```
harv31:~ # python3 -m http.server
Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...

```
suppose your Harvester cluster NODE ip is `192.168.122.200`, then use `http://192.168.122.200:8000/....full path of your file` as the URL in Harvester WebUI to create image.

It will be much faster than downloading from public network, and also re-use Harvester exsting solution to create image.

**Comment by averyfreeman** [comment]
> There is no handy solution for it now.
> 
> Technically speaking, Harvester utilizes Longhorn as the persistant storage, and when creating image in WebUI, the source file can be either an remote http link, or from local file in the client PC. Longhorn will download this file and convert it into an image file. It does not support using a local file in the the Cluster NODE path as the source file yet.

Thank you for the clarification, 

I used the python simple http server option mentioned in https://github.com/harvester/harvester/issues/3002#issuecomment-1286852891 last night, after attempts to perform local upload resulted in a failure at 99% complete multiple times (error msg "context cancelled"). URL currently seems like the far preferable option IMO as of now.

Let's close this issue.

**Comment by averyfreeman** [comment]
> One hack you may try:
>```
> harv31:~ # python3 -m http.server
> Serving HTTP on 0.0.0.0 port 8000 (http://0.0.0.0:8000/) ...
> ```
> It will be much faster than downloading from public network

Yeah, I came across this solution last night after local upload failed on me right at the end (23GB file - was excruciating). If anyone who sees this issue thread is looking for more guidance, I posted a write-up on my blog: https://develmonk.com/2022/10/20/simple-http-server-for-sending-local-images-to-ranchers-harvester-hci-os/

BTW, I just used port 80 to avoid port notation.
