### ISSUE TITLE
[BUG] The count of volume snapshots should not include VM's snapshots.

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3004]
**Describe the bug**

**To Reproduce**

1. Go to Create a vm `vm-1`.
2. Take a snapshot of it.
3. The count of volume snapshots on Volume list is `1`

**Expected behavior**

The count of volume snapshots should not include VM's snapshots.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-7b698413-head` (10/12). Close this issue.

### Result
* When one VM is created 
![image](https://user-images.githubusercontent.com/29251855/197482909-baf7d1f4-4032-4180-bb88-22aac8b9a8bc.png)

* Only VM snap are created
![image](https://user-images.githubusercontent.com/29251855/197484294-46b89b29-78be-4d28-a33c-77aa525850a8.png)

* The count of volume snapshots should not include VM's snapshots.
![image](https://user-images.githubusercontent.com/29251855/197484528-ed4c562b-782b-400e-99ec-fa97e292568d.png)

### Test Information
* Test Environment: 3 nodes harvester on local kvm machine
* Harvester version: `master-7b698413-head` (10/12)

### Verify Steps
1. Create a VM `vm1`
2. Take a VM snapshot
3. Check the volume snapshot page
4. Check the VM snapshot page
