### ISSUE TITLE
[Test] Add unit test for virtualmachine mutator

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3007]
**Is your feature request related to a problem? Please describe.**

Add unit test cases to test patchAffinity in virtualmachine mutator.

https://github.com/harvester/harvester/pull/3000#discussion_r1001552711

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
Need to backport to v1.1 branch as well.

**Comment by guangbochen** [comment]
Close as the unit test has been added to both master https://github.com/harvester/harvester/pull/3405 and the v1.1 branch.
