### ISSUE TITLE
[Question] - Downloaded VM Images

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#3016]
Hi Harvester team,

When we migrate an existing VM from other virtualization platform / virtualized physical server, we need to use the URL option as the upload doesn't work for big Images.

That's fine and it works fine - but we ended up having to create a "temporary" http server so Harvester can download the images.

I came across an issue where when I remove the image from the http server, it seems like it still tries to get the images from the URL for new nodes, and because the image doesn't exists on the HTTP server anymore, it fails.  Same applies for some ISOs.

This is a problem in that we want to remove this temporary http server at some point, and we don't want to get into a situation where it  creates issues.  Is there a system in place to sync the images across nodes without downloading the images from the URL?

Thanks,

**Comment by albertkohl-monotek** [comment]
bump this. i'm going to have the same issue when adding nodes. also, is there a way to export backing-images? this might be a good short-term workaround, export the image, and put in on a web server again for harvester to redownload

**Comment by RegisWeduLabs** [comment]
Bump

**Comment by w13915984028** [comment]
update:

The `image downloading` feature is released in `Harvester v1.1.0`, there is a button to download an existing image.

For `retriggering the download of image` when new node is added, it is under investigation.  thanks.

**Comment by albertkohl-monotek** [comment]
@w13915984028 is there a manual process, you could provide for v1.0.3? considering the upgrade issues for v1.1.0 it would be a good failsafe to be able to export my backing images before upgrading (once v1.1.1 is released)

thanks!

**Comment by RegisWeduLabs** [comment]
Awesome, thank you!

**Comment by w13915984028** [comment]
> @w13915984028 is there a manual process, you could provide for v1.0.3? considering the upgrade issues for v1.1.0 it would be a good failsafe to be able to export my backing images before upgrading (once v1.1.1 is released)
> 
> thanks!

@FrankYang0529 Do you know if there is a feasible/hack way to achieve the `image download` in v1.0.3 ?  Is it possible to  replace the `harvester` POD image to new one and create the related CRD? thanks.

**Comment by w13915984028** [comment]
FYI: Related feature in Harvester v1.1.0:

https://docs.harvesterhci.io/v1.1/volume/export-volume/

**Comment by shuo-wu** [comment]
Theoretically, Longhorn won’t re-download the existing image unless all image files are unavailable. What’s the Harvester and Longhorn version you are using? If it’s Longhorn v1.2.x or v1.3.x, the pod of the tmp server should be like `backing-image-ds-<backing image name>`, do you observe this pod running when the issue happens?

**Comment by albertkohl-monotek** [comment]
@FrankYang0529 any thoughts on this? i'm at a point now where i'm trying to manually migrate from a v1.0.3 cluster into another v1.1.0 cluster (considering the upgrade issues currently for v1.1.0).

backup/restore would be create, but i dont know how to export the backing images from the current v1.0.3 cluster. 


any additional thoughts on migrating vms from harvester v1.0.3 cluster to different v.1.1.0 cluster would be great too! (or i can make a new question if need be)

**Comment by FrankYang0529** [comment]
Backing images are stored in the `/data/backing-images` folder of `<backing-image-manager-xxxx-xxxx>` pod. You can copy them with kubectl.
```bash
$ kubectl cp -n longhorn-system backing-image-manager-c00e-56e0:/data/backing-images/default-image-ns2sx-c6ff494f/backing test.img
```

**Comment by albertkohl-monotek** [comment]
Thanks @FrankYang0529, i'll give it a try!

**Comment by albertkohl-monotek** [comment]
@FrankYang0529 
periodically when i cp these files, i get an EOF error. here's an example of the feedback:

`
C:\software\>kubectl cp -n longhorn-system backing-image-manager-c00e-9552:data/backing-images/. backing-image-manager-c00e-9552/.
`
Dropping out copy after 0 retries
error: unexpected EOF

would you recommend re-trying the copy?

**Comment by FrankYang0529** [comment]
> C:\software\>kubectl cp -n longhorn-system backing-image-manager-c00e-9552:data/backing-images/. backing-image-manager-c00e-9552/.

Probably need a backslash before data. Like `kubectl cp -n longhorn-system backing-image-manager-c00e-9552:/data/backing-images/. backing-image-manager-c00e-9552/.`

If it's also failed, you can try
```
kubectl exec -n longhorn-system backing-image-manager-c00e-9552 -- cat /data/backing-images/<backing image name>/backing > tmp.img
```

**Comment by albertkohl-monotek** [comment]
sorry, i should clarify, this only happens "sometimes", and it does copy the data, it just ends w/ that msg. so i could copy like 100gb images out, and at the end, i'll get that error. 

but other times, it will finish with no error. is there maybe something i can run to check integrity?

**Comment by FrankYang0529** [comment]
You can run `sha512sum` on your file and check whether it's the same as the `status.checksum` on BackingImage.

**Comment by albertkohl-monotek** [comment]
@FrankYang0529 thanks! is there a way i can track down what what backing-image-manager holds the backing image i'mlooking for? or do i have to just interate through each pod till i find it?
