### ISSUE TITLE
Volume size incorrect

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#302]
**Steps to reproduce:**
1. Create a volume, with size 100000000000000000Gi
2. The volume is in `NotReady` state, check the size in the list
3. Edit it as form, check the size on the edit page
4. Click the volume name, navigate to its detail page

**Result:**
The size is not displaying 100000000000000000Gi on the detail page, list page, and edit page. A decimal size like 0.1 will also lead to the same output
![image](https://user-images.githubusercontent.com/57614736/101334404-c972a500-38b2-11eb-8f88-ccc3a4df5929.png)
![image](https://user-images.githubusercontent.com/57614736/101333644-d17e1500-38b1-11eb-9750-36035abb9560.png)
![image](https://user-images.githubusercontent.com/57614736/101333676-db077d00-38b1-11eb-950d-7e0789d24777.png)

**Suggestion:**
A maximum limit should be added to the volume size

**Comment by DaiYuzeng** [comment]
The size of the vm's volume must be integer and between 1 and 999999.

**Comment by DoNotSayYes** [comment]
Another case. @DaiYuzeng 
![image](https://user-images.githubusercontent.com/57614736/101612688-e25f8f80-3a45-11eb-9d9a-1e36fd66fc4b.png)

**Comment by DaiYuzeng** [comment]
~If the length of the size value is longer than 20, the value will be converted to exponential.~
~We should remove the unit of UnitInput component.~

**Comment by DaiYuzeng** [comment]
https://github.com/rancher/harvester-ui/blob/5ab2e1cb1c260891aab63c9ef21335e24bcd278a/utils/units.js#L64

the max safe integer in javascript is (2 ** 53 -1) = 9007199254740991
UnitInput will convert the value from String to Number, so you will come across the bug if you input a huge size.

**Comment by guangbochen** [comment]
close in favor of v0.3.0
