### ISSUE TITLE
[BUG] Project member can not see the volume which is created by self

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3020]
**Describe the bug**

project member can not see the volume which is created by self

**To Reproduce**
1. Install Rancher v2.6.9
2. Import a master Harvester(10/24)
3. Go to the Harvester cluster
4. Log in as the admin user, create project "test", and add a project member for "test"
5. Log in as a project member, create a namespace "test"
6. Go to the Volume page and create a volume
7. Volume created successfully
8. Check the volume list

**Expected behavior**

Can see the created volumes

**Support bundle**

**Environment**
 - Harvester ISO version: master-7b698413-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

https://user-images.githubusercontent.com/18737885/197463758-b6e963c5-2fe8-492d-8c07-4739208b7c47.mov

**Comment by irishgordo** [comment]
Thanks for the fix @WuJun2016 - I validated in Harvester Version: master-402df54b-head - w/ Rancher v2.6.9 that this looks good :smile: :+1: 
I'll go ahead and close this out
![Screenshot from 2022-10-24 17-10-55](https://user-images.githubusercontent.com/5370752/197653311-c19548ec-f1af-49d9-af79-af7f40e9aef1.png)
