### ISSUE TITLE
[Enhancement] Upgrade stop at upgrading node3 stage, stuck in Pre-drained state

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3021]
**Describe the bug**

When upgrading from v1.0.3 to v1.1.0-rc3 with VLAN created, the upgrade stop at upgrading node 3
The node3 stuck in the `Pre-drainded` status
![image](https://user-images.githubusercontent.com/29251855/197462402-c4529e4b-4347-44fd-8424-e3c40e8f59d8.png)

* Node status
  ```
  n2-103upd:~ # kubectl get nodes
  NAME        STATUS                     ROLES                       AGE     VERSION
  n1-103upd   Ready                      control-plane,etcd,master   2d19h   v1.24.6+rke2r1
  n2-103upd   Ready                      control-plane,etcd,master   2d15h   v1.22.12+rke2r1
  n3-103upd   Ready,SchedulingDisabled   control-plane,etcd,master   2d14h   v1.24.6+rke2r1
  ```

* Upgrade job status
  ```
  n2-103upd:~ # kubectl get jobs -n harvester-system -l harvesterhci.io/upgradeComponent=node
  NAME                                      COMPLETIONS   DURATION   AGE
  hvst-upgrade-48xdf-post-drain-n1-103upd   1/1           2m55s      26h
  hvst-upgrade-48xdf-post-drain-n3-103upd   1/1           103s       26h
  hvst-upgrade-48xdf-pre-drain-n1-103upd    1/1           7s         26h
  hvst-upgrade-48xdf-pre-drain-n3-103upd    1/1           3m6s       26h
  ```

* rancher logs
  ```
  n2-103upd:~ # kubectl logs deployment/rancher -n cattle-system
  
  2022/10/23 04:35:51 [ERROR] Error during subscribe websocket: close sent
  W1023 04:35:52.490222      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  2022/10/23 04:35:52 [INFO] Watching metadata for flowcontrol.apiserver.k8s.io/v1beta2, Kind=PriorityLevelConfiguration
  2022/10/23 04:35:52 [INFO] Watching metadata for storage.k8s.io/v1, Kind=CSIStorageCapacity
  2022/10/23 04:35:52 [INFO] Watching metadata for flowcontrol.apiserver.k8s.io/v1beta2, Kind=FlowSchema
  2022/10/23 04:35:52 [INFO] Stopping metadata watch on flowcontrol.apiserver.k8s.io/v1beta1, Kind=FlowSchema
  2022/10/23 04:35:52 [INFO] Stopping metadata watch on flowcontrol.apiserver.k8s.io/v1beta1, Kind=PriorityLevelConfiguration
  2022/10/23 04:35:52 [INFO] Stopping metadata watch on storage.k8s.io/v1beta1, Kind=CSIStorageCapacity
  2022/10/23 04:36:04 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=32995, ErrCode=NO_ERROR, debug=""
  2022/10/23 04:36:04 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=32995, ErrCode=NO_ERROR, debug=""
  2022/10/23 04:36:04 httputil: ReverseProxy read error during body copy: http2: server sent GOAWAY and closed the connection; LastStreamID=32995, ErrCode=NO_ERROR, debug=""
  W1023 04:36:04.064799      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1023 04:36:04.064827      33 warnings.go:80] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated
  W1023 04:36:05.067111      33 warnings.go:80] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated
  W1023 04:36:05.093352      33 warnings.go:80] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated
  W1023 04:36:06.097380      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  2022/10/23 04:40:48 [ERROR] Error during subscribe write tcp 10.52.1.34:80->10.52.0.29:53972: write: connection timed out
  W1023 04:41:22.059387      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1023 04:42:00.031322      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1023 04:42:04.937419      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1023 04:42:09.630198      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1023 04:42:14.662228      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  
  ```

  ```
  $ kubectl logs deployment/rancher -n cattle-system
  
  W1024 03:39:43.414966      33 warnings.go:80] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated
  E1024 03:40:59.288573      33 upgradeaware.go:399] Error proxying data from client to backend: read tcp 10.52.1.34:80->10.52.2.172:33846: read: connection reset by peer
  2022/10/24 03:40:59 [ERROR] Error during subscribe write tcp 10.52.1.34:80->10.52.2.172:33852: write: broken pipe
  W1024 03:45:31.415882      33 warnings.go:80] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated
  W1024 03:45:32.374363      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  W1024 03:52:31.375506      33 warnings.go:80] policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+
  
  ```

**To Reproduce**
1. Provision 3 nodes Harvester v1.0.3 cluster 
2. After Harvester ready
3. Enable network on `enp129s0` 
  ![image](https://user-images.githubusercontent.com/29251855/197371510-7f3bec68-3348-4123-ab4f-6b72507db4fc.png)

4. Create vlan id `91` on 
  ![image](https://user-images.githubusercontent.com/29251855/197371569-f7572b00-a262-4422-9406-80f77462f7b0.png)
  ![image](https://user-images.githubusercontent.com/29251855/197371584-5251ba57-e237-4342-b450-6320fcd49bd2.png)

5. Create two VMs, one set to vlan 91 and another use harvester-mgmt
  ![image](https://user-images.githubusercontent.com/29251855/197371971-4dd4b1f6-ecc7-4511-b262-467061204239.png)
6. Shutdown all VMs 
7. Perform upgrade to `v1.1.0-rc3` (refer to [upgrade document](https://docs.harvesterhci.io/v1.1/upgrade/automatic))

**Expected behavior**

Can completely pass all upgrade stage from v1.0.3 to v1.1.0-rc3 without stuck or error when Harvester have valid VLAN setup prior to upgrade task

**Support bundle**

* Support bundle within 3 hours
 [supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-23T13-17-59Z.zip](https://github.com/harvester/harvester/files/9849383/supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-23T13-17-59Z.zip)

* Support bundle after 24 hours
[supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-24T06-48-58Z.zip](https://github.com/harvester/harvester/files/9849403/supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-24T06-48-58Z.zip)

**Environment**
 - Harvester ISO version: `v1.1.0-rc3`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes bare metal machine

**Additional context**

**Comment by bk201** [comment]
Added a SB with YAMLs: 
[supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-24T08-25-09Z.zip](https://github.com/harvester/harvester/files/9850793/supportbundle_280eb9a1-5735-4766-9ae5-b6075d91db1d_2022-10-24T08-25-09Z.zip)

The node `n3-103upd` is upgraded, but the upgrade CR has the wrong node status:
```
n2-103upd:~ # kubectl get jobs -n harvester-system -l harvesterhci.io/upgradeComponent=node
NAME                                      COMPLETIONS   DURATION   AGE
hvst-upgrade-48xdf-post-drain-n1-103upd   1/1           2m55s      29h
hvst-upgrade-48xdf-post-drain-n3-103upd   1/1           103s       29h      <-- post drain done and check already rebooted
hvst-upgrade-48xdf-pre-drain-n1-103upd    1/1           7s         29h
hvst-upgrade-48xdf-pre-drain-n3-103upd    1/1           3m6s       29h
```

```
$ kubectl describe upgrades/hvst-upgrade-48xdf -n harvester-system
  Node Statuses:
    n1-103upd:
      State:  Succeeded
    n2-103upd:
      State:  Images preloaded
    n3-103upd:
      State:         Pre-drained 
```

From harvester pod log, we can see it's want to move the node from pre-drained to post-draining (by turning on debug)
```
time="2022-10-24T08:31:41Z" level=debug msg="Create post-drain job on n3-103upd"
time="2022-10-24T08:31:41Z" level=error msg="error syncing 'fleet-local/custom-20a8676f63ae-machine-plan': handler harvester-upgrade-secret-controller: jobs.batch \"hvst-upgrade-48xdf-post-drain-n3-103upd\" already exists, requeuing"
```

I didn't find any suspicious log that failed to update the Upgrade CR.

--
The workaround: delete the post-drain job of the node, and the upgrade continues:

```
kubectl delete jobs hvst-upgrade-48xdf-post-drain-n3-103upd -n harvester-system
```

**Comment by starbops** [comment]
I once encountered this same issue upgrading from v1.0.3 to v1.1-head and collected the logs with rancher-logging from the very beginning of the upgrade (but didn't enable debug mode on harvester).

All logs: [all-upgrade-log.csv](https://github.com/harvester/harvester/files/9865044/all-upgrade-log.csv)
From the beginning of node-2 pre-drain job was started: [upgrade-log.csv](https://github.com/harvester/harvester/files/9865030/upgrade-log.csv)

`node-0` & `node-1` were upgraded, and `node-2` was actually post-drained and rebooted but both the annotations and the `nodeStatus` in the upgrade CR imply the node was still in the "Pre-drained" state.

I then deleted the post-drain job for `node-2`, and the upgrade continued till the end without problems.

**Comment by bk201** [comment]
Please reopen if we see the issue again.
