### ISSUE TITLE
[BUG] Project member can not see the volume snapshots which is created by self

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3023]
**Describe the bug**

Project member can not see the volume snapshots which is created by self

**To Reproduce**

1. Install Rancher v2.6.9
2. Import a master Harvester(10/24)
3. Go to the Harvester cluster
4. Log in as the admin user, create project "test", and add a project member for "test"
5. Log in as a project member, create a namespace "test"
6. Go to the Volume page and create a volume
7. Volume created successfully
8. Click the right menu "Take Snapshot"
9. Go to the volume snapshot page and check

**Expected behavior**

Can see the volume snapshot that is created by the project member

**Support bundle**

**Environment**
 - Harvester ISO version: master-7b698413-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
Additional test result:
Only "Cluster Owner" can see volume snapshots

**Comment by guangbochen** [comment]
Can we please help provide a workaround if this is a known limitation? Thanks.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2.0-rc1**
* **ui-source** Option: **Auto**
* Rancher Version:
    - **v2.6-a4b924d21cd5d90b28ab8009edc18d96542952ac-head**, Docker Image: **a1d1e43988d2**
    - **v2.7-6ce75a0b57ad9e88cf135254a9b3b40082788eb6-head**, Docker Image: **cabaf5fe17df**

### Verify Steps
1. Install Harvester with any nodes
2. Install Rancher, create **Standard User** `pm1`
3. Import Harvester into Rancher
4. Access Harvester via Rancher's _Virtualization Management_
5. Create a project `proj-a`, add user `pm1` as member
6. Create a namespace `ns1` to `proj-a`
7. Login Rancher by the user `pm1` then access Harvester
8. Create a volume `v1` and take snapshot `v1s`
9. `v1s` should be available in page **Volume Snapshots**
