### ISSUE TITLE
[BUG] Volume shows `Ready` but Longhorn shows `Not Ready`

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3026]
### Describe the bug
sub issue of #3024, when user use customized storage class, the volume created in Harvester dashboard and shows `Bound` and `Ready`, but in Longhorn dashboard, the volume is NOT ready for workload with _scheduling failure_.

### To Reproduce
1. Same as #3024 

### Expected behavior
As we don't expect user to visit longhorn dashboard, Volume's status should align with Longhron's.

## Environment:
 - Harvester ISO version: **master-f96827b2-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

**Comment by patjsimpson** [comment]
Is there a link to a workaround on this. I am hitting this consistently. I am building harvester out in a vm on truenas scale and all goes well. harvester boots up everything looks good in harvester but storage is saying offline in the longhorn dashboard.  Happy to provide any more data.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/217808999-ea5e3972-f87e-4e7f-9705-d0effa6be861.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1-f280b2c0-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Follow **Steps to Reproduce** in https://github.com/harvester/harvester/issues/3026#issue-1420555551
