### ISSUE TITLE
[Question] - How to test Harvester HCI using VirtualBox on Windows?

### ISSUE THREAD

**Issue by DmitriZV** [harvester/harvester#3033]
Unable to work with Harvester HCI using VirtualBox.
During the work / testing of Harvester using VirtualBox (on a Windows computer) I encounter various errors / problems.
For example:
1) It was not possible to connect to Harvester using the "NAT + Only-Host" Internet settings, as in the instructions, only when I changed it to "Bridged" network
2) It was difficult to add OS images (only local files)
3) When creating a VM, it is impossible to manage, the eternal status "machine is not ready for work" ...

Does anyone have a successful experience with Harvester HCI using VirtualBox ?
Maybe there is an information / instructions for working using VirtualBox that works?

**Comment by w13915984028** [comment]
@DmitriZV   Did you try following in your Windows VirtualBox?

(1) Install Ubuntu in VirtualBox VM, create VM in this Ubuntu via `virsh` or `virt-manager` ?  (note: you need to enable `nested virtualization` in your PC/Server's BIOS)

(2) Install a couple of VirtualBox VM with Ubuntu or other Linux distro, then install k8s cluster on those VMs.

When those are well working, Harvester will be similar. thanks.

**Comment by DmitriZV** [comment]
> @DmitriZV Did you try following in your Windows VirtualBox?
> 
> (1) Install Ubuntu in VirtualBox VM, create VM in this Ubuntu via `virsh` or `virt-manager` ? (note: you need to enable `nested virtualization` in your PC/Server's BIOS)
> 
> (2) Install a couple of VirtualBox VM with Ubuntu or other Linux distro, then install k8s cluster on those VMs.
> 
> When those are well working, Harvester will be similar. thanks.

Thank you for your advice, I'll try it.

**Comment by DmitriZV** [comment]
Finally, I used Harvester on Wmware with a 'Bridged' type of internet adapter (to access from the local machine and other Virtual Machine)
Thank to always for your help!
