### ISSUE TITLE
[BUG] Adding a third node mades the second one to fail

### ISSUE THREAD

**Issue by lkoba** [harvester/harvester#3039]
**Describe the bug**
When adding a third node the second one starts failing. SSHing into the failing node shows that a promotion was triggered by the cluster and it failed. rke2 agent is down and rke2 server fails to start.

![image](https://user-images.githubusercontent.com/168509/197899333-b73b0d7a-8758-4625-827d-485e59ff7074.png)

![image](https://user-images.githubusercontent.com/168509/197899424-ad85cc3e-5a8e-454c-8c11-cb902bcfd31b.png)

```
Oct 25 23:16:41 harvester-2 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 402.
Oct 25 23:16:41 harvester-2 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).
Oct 25 23:16:41 harvester-2 systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
Oct 25 23:16:41 harvester-2 sh[1695]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
Oct 25 23:16:41 harvester-2 sh[1701]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
Oct 25 23:16:41 harvester-2 harv-update-rke2-server-url[1707]: + HARVESTER_CONFIG_FILE=/oem/harvester.config
Oct 25 23:16:41 harvester-2 harv-update-rke2-server-url[1707]: + RKE2_VIP_CONFIG_FILE=/etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Oct 25 23:16:41 harvester-2 harv-update-rke2-server-url[1707]: + case $1 in
Oct 25 23:16:41 harvester-2 harv-update-rke2-server-url[1707]: + rm -f /etc/rancher/rke2/config.yaml.d/90-harvester-vip.yaml
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="Unknown flag --apiVersion found in config.yaml, skipping\n"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="Unknown flag --kind found in config.yaml, skipping\n"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="Unknown flag --omitStages found in config.yaml, skipping\n"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="Unknown flag --omitStages found in config.yaml, skipping\n"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="Unknown flag --rules found in config.yaml, skipping\n"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=warning msg="not running in CIS mode"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=info msg="Starting rke2 v1.24.7+rke2r1 (5fd5150f752a663efa16ac3ae2aac5d6bba6c364)"
Oct 25 23:16:41 harvester-2 rke2[1711]: time="2022-10-25T23:16:41Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
Oct 25 23:16:42 harvester-2 rke2[1711]: time="2022-10-25T23:16:42Z" level=warning msg="Cluster CA certificate is not trusted by the host CA bundle, but the token does not include a CA hash. Use the full token from the server's node-token file to enable Cluster CA validation."
Oct 25 23:16:42 harvester-2 rke2[1711]: time="2022-10-25T23:16:42Z" level=info msg="Reconciling bootstrap data between datastore and disk"
Oct 25 23:16:42 harvester-2 rke2[1711]: time="2022-10-25T23:16:42Z" level=fatal msg="/var/lib/rancher/rke2/server/tls/service.key, /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt, /var/lib/rancher/rke2/server/tls/etcd/server-ca.key, /var/lib/rancher/rke2/server/cred/encryption-state.json, /var/lib/rancher/rke2/server/tls/request-header-ca.crt, /var/lib/rancher/rke2/server/tls/request-header-ca.key, /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt, /var/lib/rancher/rke2/server/cred/ipsec.psk, /var/lib/rancher/rke2/server/tls/server-ca.key, /var/lib/rancher/rke2/server/tls/client-ca.crt, /var/lib/rancher/rke2/server/tls/client-ca.key, /var/lib/rancher/rke2/server/cred/passwd, /var/lib/rancher/rke2/server/tls/server-ca.crt, /var/lib/rancher/rke2/server/tls/etcd/peer-ca.key, /var/lib/rancher/rke2/server/cred/encryption-config.json newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore."
Oct 25 23:16:42 harvester-2 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Oct 25 23:16:42 harvester-2 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Oct 25 23:16:42 harvester-2 systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
```

**To Reproduce**
1. Create 3 vms using virt-manager with 32 cores / 64 gb ram / 500 gb of storage / single nic, using the master, 1.1.0 or 1.0.3 iso to boot the system, waiting until one node is fully installed before installing the next one.
2. When the third node is added the second node will get cordoned when the promotion is triggered and then kubelet stops responding.

**Expected behavior**
We expect the second node not to fail the promotion process.

**Support bundle**
- 
[supportbundle_5c04607a-f1df-4da1-b131-87db50c43651_2022-10-25T22-55-24Z.zip](https://github.com/harvester/harvester/files/9864556/supportbundle_5c04607a-f1df-4da1-b131-87db50c43651_2022-10-25T22-55-24Z.zip)
[scc_harvester-2_221025_2256.txz.zip](https://github.com/harvester/harvester/files/9864570/scc_harvester-2_221025_2256.txz.zip) (generated with supportconfig -k -c on the node that failed the promotion)

**Environment**
 - Harvester ISO version: master (as of 2022-10-25), 1.0.3 and 1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): qemu, each vm with a single nic, 32 cores, 64 gb ram, and a 500gb disk

**Additional context**

**Comment by bk201** [comment]
@lkoba Could you provide logs on the `harvester-2` node? Thanks!
- /var/lib/rancher/rke2/agent/containerd/containerd.log
- /var/lib/rancher/rke2/agent/logs/kubelet.log

**Comment by w13915984028** [comment]
@lkoba As you mentioned  `When the third node is added the second node will get cordoned when the promotion is triggered and then kubelet stops responding.`, 

Is the `the promotion is triggered` triggered automatically or manually from the WebUI ?

**Comment by lkoba** [comment]
@bk201 
> @lkoba Could you provide logs on the harvester-2 node? Thanks!

[harvester-2-logs.tar.gz](https://github.com/harvester/harvester/files/9869974/harvester-2-logs.tar.gz)

@w13915984028 
> Is the the promotion is triggered triggered automatically or manually from the WebUI ?

it's triggered automatically.

**Comment by rajesh1084** [comment]
[supportbundle_e0c89d97-df4a-47cd-820b-554fc23bcc38_2022-10-27T05-29-56Z.zip](https://github.com/harvester/harvester/files/9876059/supportbundle_e0c89d97-df4a-47cd-820b-554fc23bcc38_2022-10-27T05-29-56Z.zip)

Repeat of this issue.

**Comment by irishgordo** [comment]
@rajesh1084 @lkoba I am able to reproduce the issue easily.
Environment:
- Harvester Version: v1.1.0
- Infra: qemu/kvm, 8-10C & 16-18GiB Mem on each node 

Attaching a lot of files, if any kubelet - journalctl - or containerd logs from the second node help:

(the video is sped up)

https://user-images.githubusercontent.com/5370752/198406663-c7d96461-caf5-4e6b-a487-2eac64df6bd7.mp4

(logs)
[node-2-kubelet.log](https://github.com/harvester/harvester/files/9883380/kubelet.log)
[node-2-containerd.log](https://github.com/harvester/harvester/files/9883381/containerd.log)
[log-node-2-large-journalctl-tail-log.log](https://github.com/harvester/harvester/files/9883382/log-node-2-large-journalctl-tail-log.log)


Support Bundle:
[supportbundle_68f9c6f7-1e17-429c-9e67-4aac29379d39_2022-10-27T21-35-20Z.zip](https://github.com/harvester/harvester/files/9883384/supportbundle_68f9c6f7-1e17-429c-9e67-4aac29379d39_2022-10-27T21-35-20Z.zip)

I did note, that it does seem to resolve itself after a while.
While the second node did become cordoned & unschedulable for a period of time - it did return to a management status node after a period of time.
But yes, the second node did "go offline" so to speak for a period of time.
Without any work-around, preventing the second node from going offline for a period of time.

In an upgrade, it also seems to be noted that the second node went into a cordoned / unschedulable state here, tho this may not be related:
https://github.com/harvester/harvester/issues/3041#issuecomment-1291845922

**Comment by bk201** [comment]
Related issue in Slack: https://rancher-users.slack.com/archives/C01GKHKAG0K/p1666335034681119

**Comment by w13915984028** [comment]
@lkoba @rajesh1084 Were your cluster back to normal after some time?

From @irishgordo 's test, it recovers.

**Comment by rajesh1084** [comment]
No, it's been 7 days in this state - 
![image](https://user-images.githubusercontent.com/108651299/198568425-8c016f6d-12ab-4825-8bc7-1c99af87aed7.png)

**Comment by lkoba** [comment]
> @lkoba @rajesh1084 Were your cluster back to normal after some time?
> 
> From @irishgordo 's test, it recovers.

In my case it doesn't recover. Even leaving it up for a few days.

**Comment by futuretea** [comment]
The node becomes unavailable during the promotion as expected. After the promotion, the node will recover. 
I was unable to reproduce this problem on 1.1.0 and 1.0.3

**Comment by futuretea** [comment]
@lkoba in the support bundle, the Harvester version is master-head. 

> Harvester ISO version: master (as of 2022-10-25), 1.0.3 and 1.1.0

Do you mean `master (as of 2022-10-25), between 1.0.3 and 1.1.0` not `both 1.0.3 and 1.1.0`？

**Comment by futuretea** [comment]
@lkoba It also looks like your nodes are having a hard time keeping up with etcd. The most common cause of this is insufficient disk IO. Do you have SSD or NVME disk in your nodes? If only have HDD disks, you can use [RAID](https://en.wikipedia.org/wiki/RAID) to increase the disk iops( I am using RAID10 in my environment）. 

```log
2022-10-25T22:55:34.264223292Z {"level":"warn","ts":"2022-10-25T22:55:34.264Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"609.907228ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/whereabouts.cni.cncf.io/overlappingrangeipreservations/\" range_end:\"/registry/whereabouts.cni.cncf.io/overlappingrangeipreservations0\" count_only:true ","response":"range_response_count:0 size:6"}
2022-10-25T22:55:34.264226077Z {"level":"warn","ts":"2022-10-25T22:55:34.264Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"522.609755ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/leases/kube-system/kube-controller-manager\" ","response":"range_response_count:1 size:514"}
2022-10-25T22:55:34.264235194Z {"level":"warn","ts":"2022-10-25T22:55:34.264Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"745.257171ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/leases/longhorn-system/driver-longhorn-io\" ","response":"range_response_count:1 size:487"}
2022-10-25T22:55:34.264238010Z {"level":"warn","ts":"2022-10-25T22:55:34.264Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"747.426068ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/crd.projectcalico.org/ipamconfigs/\" range_end:\"/registry/crd.projectcalico.org/ipamconfigs0\" ","response":"range_response_count:0 size:6"}

```

You can refer to https://www.ibm.com/cloud/blog/using-fio-to-tell-whether-your-storage-is-fast-enough-for-etcd to check the disk performance.

Another possible cause is the use of an unsafe disk caching mode. refer to https://doc.opensuse.org/documentation/leap/virtualization/html/book-virtualization/cha-cachemodes.html


A similar issue: https://github.com/k3s-io/k3s/issues/5714

**Comment by lkoba** [comment]
> @lkoba It also looks like your nodes are having a hard time keeping up with etcd. The most common cause of this is insufficient disk IO. Do you have SSD or NVME disk in your nodes? If only have HDD disks, you can use [RAID](https://en.wikipedia.org/wiki/RAID) to increase the disk iops( I am using RAID10 in my environment）.
> 

This particular test was done over HDD but I tested multiple times over NVME and even ramdisks with the same results . I ran some fio tests on the same VMs and netted around 3gb/sec with enough iops for etcd when I was doing some tests for longhorn.

If it helps, I managed to get a 3 node cluster running with https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester on the same host. However, I tried the same VM configuration generated by that tool with the ISO manual installer (both master and stable versions) but it still fails as described in this issue.

**Comment by w13915984028** [comment]
From the log attached in the issue description, there is a `fatal` error when restarting `rke2 service`

> Oct 25 23:16:42 harvester-2 rke2[1711]: time="2022-10-25T23:16:42Z" level=fatal msg="/var/lib/rancher/rke2/server/tls/service.key, /var/lib/rancher/rke2/server/tls/etcd/server-ca.crt, /var/lib/rancher/rke2/server/tls/etcd/server-ca.key, /var/lib/rancher/rke2/server/cred/encryption-state.json, /var/lib/rancher/rke2/server/tls/request-header-ca.crt, /var/lib/rancher/rke2/server/tls/request-header-ca.key, /var/lib/rancher/rke2/server/tls/etcd/peer-ca.crt, /var/lib/rancher/rke2/server/cred/ipsec.psk, /var/lib/rancher/rke2/server/tls/server-ca.key, /var/lib/rancher/rke2/server/tls/client-ca.crt, /var/lib/rancher/rke2/server/tls/client-ca.key, /var/lib/rancher/rke2/server/cred/passwd, /var/lib/rancher/rke2/server/tls/server-ca.crt, /var/lib/rancher/rke2/server/tls/etcd/peer-ca.key, /var/lib/rancher/rke2/server/cred/encryption-config.json newer than datastore and could cause a cluster outage. Remove the file(s) from disk and restart to be recreated from datastore."


@brandond any idea of this fatal error ? thanks.

**Comment by w13915984028** [comment]
The fatal is from here:

https://github.com/k3s-io/k3s/blob/master/pkg/cluster/bootstrap.go#L356

And the code said:
```
// ReconcileBootstrapData is called before any data is saved to the
// datastore or locally. It checks to see if the contents of the
// bootstrap data in the datastore is newer than on disk or different
// and depending on where the difference is. If the datastore is newer,
// then the data will be written to disk. If the data on disk is newer,
// k3s will exit with an error.
```

**Comment by w13915984028** [comment]
In @lkoba 's case, the NODE `harvester2` is `promoted`  (from rke2-agent to rke2-server), it will start `rke2-server` service but fail due to this `fatal` error. It causes the `hanging` status.

Will check @rajesh1084's support-bundle, he also reports the similar bug.

**Comment by w13915984028** [comment]
Update: For @rajesh1084 's case, the direct fatal error seems a bit different, it is logged in #3091

etcd error:
> Oct 21 11:29:26 harv-node3 rke2[27529]: {"level":"warn","ts":"2022-10-21T11:29:26.901Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc00017b340/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing dial tcp 127.0.0.1:2379: connect: connection refused\""}

service is failed, stopped and rebooted 
> Oct 21 11:29:41 harv-node3 rke2[27529]: time="2022-10-21T11:29:41Z" level=fatal msg="Tunnel watches failed to wait for apiserver ready: timed out waiting for the condition, failed to get apiserver /readyz status: Get \"https://127.0.0.1:6443/readyz\": dial tcp 127.0.0.1:6443: connect: connection refused"

> Oct 21 11:29:46 harv-node3 systemd[1]: rke2-server.service: Scheduled restart job, restart counter is at 67.
Oct 21 11:29:46 harv-node3 systemd[1]: Stopped Rancher Kubernetes Engine v2 (server).

**Comment by brandond** [comment]
Appears to be the same as https://github.com/harvester/harvester/issues/3091#issuecomment-1301255783 - need to check additional logs to see why the containers aren't coming up.

**Comment by w13915984028** [comment]
We figured out a similar issue #3091 was caused by `http-proxy` configuration. 

@lkoba  In your cluster, is `http-proxy` used?

**Comment by lkoba** [comment]
> We figured out a similar issue #3091 was caused by `http-proxy` configuration.
> 
> @lkoba In your cluster, is `http-proxy` used?

no, we did not use http proxy in any of our tests.

**Comment by w13915984028** [comment]
@lkoba thanks for your update. Is the cluster re-installed or still left there?

@brandond It loosk different with #3091, any suggestions for further analysis ? thanks.

> Oct 25 23:16:42 harvester-2 rke2[1711]: time="2022-10-25T23:16:42Z" level=fatal msg="
/var/lib/rancher/rke2/server/tls/service.key, 
/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt, 
..., 
/var/lib/rancher/rke2/server/cred/encryption-config.json 
newer than datastore and could cause a cluster outage. 
Remove the file(s) from disk and restart to be recreated from datastore."

**Comment by brandond** [comment]
Can you attach the same information requested in https://github.com/harvester/harvester/issues/3091#issuecomment-1302630734?

**Comment by lkoba** [comment]
> @lkoba thanks for your update. Is the cluster re-installed or still left there?

I just tested reinstalling the cluster with the lastest master image https://releases.rancher.com/harvester/master/harvester-master-amd64.iso and it's working! Adding the 3rd node triggers the promotions but now it completes perfectly.

**Comment by w13915984028** [comment]
Close as issue solved.
