### ISSUE TITLE
An inappropriate error message shows when requests time out

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#304]
**Steps to reproduce:**
1. Create a new volume/VM
2. Somehow the request times out. (Can manipulate by setting the VPN to `Global Mode`

**Result:**
An inappropriate error message shows when creating a new volume times out. 0ms is definitely incorrect

`Error: timeout of 0ms exceeded`
![image](https://user-images.githubusercontent.com/57614736/101431532-0f2a7e80-3942-11eb-8c83-2772dad01c6a.png)
![image](https://user-images.githubusercontent.com/57614736/101431546-15b8f600-3942-11eb-9866-20be3c9d6b49.png)
![image](https://user-images.githubusercontent.com/57614736/101431844-a394e100-3942-11eb-8819-1e509d6eae52.png)

**Comment by DaiYuzeng** [comment]
> https://github.com/axios/axios/issues/2103

It seems like a bug caused by axios, we will add the timeout to global config of it.

**Comment by DaiYuzeng** [comment]
@WuJun2016 @DoNotSayYes 
The timeout has been added to global config of axios.
If the request takes longer than 20s, the request will be aborted.

![截屏2020-12-17 下午3 17 15](https://user-images.githubusercontent.com/15041915/102455952-6e436e00-407b-11eb-8145-0b8bd3fda990.png)

**Comment by guangbochen** [comment]
can u change the message to `timeout of 20s exceeded`

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/103404513-cb1c4980-4b8e-11eb-8771-86b8c0aa20e1.png)
