### ISSUE TITLE
[BUG] stuck at "Upgrade system services" from v1.0.3 to v1.1.0 upgrading progress

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#3041]
**Describe the bug**

In a progress that upgrade from v1.0.3 to v1.1.0, I stuck at "Upgrade system services" for a long time( about 3 hours).
![image](https://user-images.githubusercontent.com/38560218/197971033-0067ab5e-80b4-4bef-99df-3e9d61f70748.png)

Here is my upgrade status: 
```yaml
apiVersion: v1
items:
- apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    creationTimestamp: "2022-10-26T07:05:45Z"
    finalizers:
    - wrangler.cattle.io/harvester-upgrade-controller
    generateName: hvst-upgrade-
    generation: 14
    labels:
      harvesterhci.io/latestUpgrade: "true"
      harvesterhci.io/upgradeState: UpgradingSystemServices
    name: hvst-upgrade-fnlkm
    namespace: harvester-system
    resourceVersion: "32750759"
    uid: b96a9405-07b0-4705-b3fc-004155958201
  spec:
    image: ""
    version: v1.1.0
  status:
    conditions:
    - status: Unknown
      type: Completed
    - lastUpdateTime: "2022-10-26T07:11:43Z"
      status: "True"
      type: ImageReady
    - lastUpdateTime: "2022-10-26T07:15:30Z"
      status: "True"
      type: RepoReady
    - lastUpdateTime: "2022-10-26T07:15:50Z"
      status: "True"
      type: NodesPrepared
    - status: Unknown
      type: SystemServicesUpgraded
    imageID: harvester-system/harvester-iso-ncqn7
    nodeStatuses:
      harvester0:
        state: Images preloaded
      harvester1:
        state: Images preloaded
      harvester2:
        state: Images preloaded
    previousVersion: v1.0.3
    repoInfo: |
      release:
          harvester: v1.1.0
          harvesterChart: 1.1.0
          os: Harvester v1.1.0
          kubernetes: v1.24.7+rke2r1
          rancher: v2.6.9
          monitoringChart: 100.1.0+up19.0.3
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

Here is my log of `jobs/hvst-upgrade-fnlkm-apply-manifests`:
```yaml
harvester: v1.1.0
harvesterChart: 1.1.0
os: Harvester v1.1.0
kubernetes: v1.24.7+rke2r1
rancher: v2.6.9
monitoringChart: 100.1.0+up19.0.3
loggingChart: 100.1.3+up3.17.7
kubevirt: 0.54.0-150400.3.3.2
minUpgradableVersion: 'v1.0.3'
rancherDependencies:
  fleet:
    chart: 100.1.0+up0.4.0
    app: 0.4.0
  fleet-crd:
    chart: 100.1.0+up0.4.0
    app: 0.4.0
  rancher-webhook:
    chart: 1.0.6+up0.2.7
    app: 0.2.7
Current version: 1.0.3
Minimum upgradable version: 1.0.3
Current version is supported.
Executing v1.0.3 pre-hook...
Remove rke.cattle.io/init-node-machine-id label in fleet-local/local cluster
label "rke.cattle.io/init-node-machine-id" not found.
cluster.provisioning.cattle.io/local not labeled
managedchart.management.cattle.io/harvester patched (no change)
managedchart.management.cattle.io/harvester-crd patched (no change)
managedchart.management.cattle.io/rancher-monitoring patched (no change)
managedchart.management.cattle.io/rancher-monitoring-crd patched (no change)
Upgrading Rancher
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   117  100   117    0     0  16714      0 --:--:-- --:--:-- --:--:-- 16714
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 57.9M  100 57.9M    0     0  29.1M      0  0:00:01  0:00:01 --:--:-- 29.1M
time="2022-10-26T07:15:56Z" level=info msg="Extract mapping / => /tmp/upgrade/rancher"
time="2022-10-26T07:15:56Z" level=info msg="Checking local image archives in /tmp/upgrade/images for index.docker.io/rancher/system-agent-installer-rancher:v2.6.9"
time="2022-10-26T07:15:57Z" level=info msg="Extracting file run.sh to /tmp/upgrade/rancher/run.sh"
time="2022-10-26T07:15:58Z" level=info msg="Extracting file rancher-2.6.9.tgz to /tmp/upgrade/rancher/rancher-2.6.9.tgz"
time="2022-10-26T07:15:58Z" level=info msg="Extracting file helm to /tmp/upgrade/rancher/helm"
Rancher values:
antiAffinity: required
bootstrapPassword: admin
features: multi-cluster-management=false,multi-cluster-management-agent=false
hostPort: 0
ingress:
  enabled: false
noDefaultAdmin: false
rancherImage: rancher/rancher
rancherImagePullPolicy: IfNotPresent
rancherImageTag: v2.6.4-harvester3
replicas: -3
systemDefaultRegistry: ""
tls: external
useBundledSystemChart: true
```

I have even tried some commands from https://docs.harvesterhci.io/v1.1/upgrade/previous-releases/v1-0-0-to-v1-0-1#stuck-in-upgrading-system-service , but it doesn't work for me.

**To Reproduce**
1. Click `Upgrade` at harvester UI

**Support bundle**

[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2022-10-26T08-00-43Z.zip](https://github.com/harvester/harvester/files/9867428/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2022-10-26T08-00-43Z.zip)

**Environment**
 - Harvester ISO version:  v1.0.3
 - Underlying Infrastructure: Baremetal with PowerEdge R740

**Comment by w13915984028** [comment]
How about the resource of each NODE? CPU cores,memory and storage.

The v1.1.0 needs more resources ( 12+ cores each node ) .

**Comment by Martin-Weiss** [comment]
My upgrade is stuck in exactly the same situation. For some reason the upgrade pod states that it wants to upgrade Rancher but I can not find why the helm deployment did not get upgraded. Where can we check what the failure is / what the upgrade pod is waiting for?

**Comment by w13915984028** [comment]
@Martin-Weiss Do you have related logs?  
cc @bk201 @starbops

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss Do you have related logs? cc @bk201 @starbops

@w13915984028  - which logs do we need to look into exactly?

Here a supportbundle:

[supportbundle_0ed34b76-5048-40e2-a2ac-da9798f550fb_2022-10-26T09-42-35Z.zip](https://github.com/harvester/harvester/files/9868227/supportbundle_0ed34b76-5048-40e2-a2ac-da9798f550fb_2022-10-26T09-42-35Z.zip)

**Comment by W0n9** [comment]
> How about the resource of each NODE? CPU cores,memory and storage.
> 
> The v1.1.0 needs more resources ( 12+ cores each node ) .

Per Node Spec is 64C64G with 2x 512G SSD

**Comment by bk201** [comment]
@W0n9 Did you have some fail-to-joined nodes before? From Rancher's log, rancher is provisioning two ghost machine:

```
2022-10-26T07:56:41.439986349Z 2022/10/26 07:56:41 [INFO] [planner] rkecluster fleet-local/local: waiting: provisioning worker node(s) custom-24ae94037853,custom-fa54219f944c
```

You can check the machine list with the command, and I guess two of them don't have a `PROVIDERID`.
```
$ kubectl get machines -n fleet-local
```

[The upgrade script is waiting for the cluster to become "Provisioned"](https://github.com/harvester/harvester/blob/a4872361145e0d0b99c4afeb6052f344acd48f30/package/upgrade/upgrade_manifests.sh#L245). And it won't continue until the CAPI cluster turns into "Provisioned". To check its status:
```
kubectl get clusters.cluster.x-k8s.io local -n fleet-local
```

**Comment by bk201** [comment]
@Martin-Weiss Your cluster has a similar situation, except Rancher is waiting for a node to be uncordoning:
```
2022-10-26T09:36:09.399636200Z 2022/10/26 09:36:09 [INFO] [planner] rkecluster fleet-local/local: waiting: uncordoning bootstrap node(s) custom-18f4ec0eb29e: waiting for uncordon to finish
```
The cluster is upgraded from v1.0.0 -> v1.0.1 -> v1.0.2 -> v1.0.3 and then to v1.1.0. The Upgrade resources look good, but did you encounter any failures before? Please dump machine plan secrets and DM to me if possible (secrets are not captured in the support bundles):
```
kubectl get secret -n fleet-local --field-selector type=rke.cattle.io/machine-plan -o yaml
```

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss Your cluster has a similar situation, except Rancher is waiting for a node to be uncordoning:
> 
> ```
> 2022-10-26T09:36:09.399636200Z 2022/10/26 09:36:09 [INFO] [planner] rkecluster fleet-local/local: waiting: uncordoning bootstrap node(s) custom-18f4ec0eb29e: waiting for uncordon to finish
> ```
> 

I have realized that the node harvester2 went into "cordoned" but I can not say way.

```
NAME         STATUS                     ROLES                       AGE    VERSION
harvester1   Ready                      control-plane,etcd,master   118d   v1.22.12+rke2r1
harvester2   Ready,SchedulingDisabled   control-plane,etcd,master   118d   v1.22.12+rke2r1
harvester3   Ready                      control-plane,etcd,master   118d   v1.22.12+rke2r1
```

I did a manual uncordon but after some time it has been cordoned, again.

> The cluster is upgraded from v1.0.0 -> v1.0.1 -> v1.0.2 -> v1.0.3 and then to v1.1.0. The Upgrade resources look good, but did you encounter any failures before? 

Not that I can remember.

>Please dump machine plan secrets and DM to me if possible (secrets are not captured in the support bundles):
> 
> ```
> kubectl get secret -n fleet-local --field-selector type=rke.cattle.io/machine-plan -o yaml
> ```

DM send..

**Comment by bk201** [comment]
@Oats87 Is it possible to "cancel" an in-provisioning cluster? I guess in Martin's case, he might need to manually pre-drain/post-drain nodes and settle down the cluster. But just wonder if we can skip this.

**Comment by W0n9** [comment]
> @W0n9 Did you have some fail-to-joined nodes before? From Rancher's log, rancher is provisioning two ghost machine:
> 
> ```
> 2022-10-26T07:56:41.439986349Z 2022/10/26 07:56:41 [INFO] [planner] rkecluster fleet-local/local: waiting: provisioning worker node(s) custom-24ae94037853,custom-fa54219f944c
> ```
> 
> You can check the machine list with the command, and I guess two of them don't have a `PROVIDERID`.
> 
> ```
> $ kubectl get machines -n fleet-local
> ```
> 
> [The upgrade script is waiting for the cluster to become "Provisioned"](https://github.com/harvester/harvester/blob/a4872361145e0d0b99c4afeb6052f344acd48f30/package/upgrade/upgrade_manifests.sh#L245). And it won't continue until the CAPI cluster turns into "Provisioned". To check its status:
> 
> ```
> kubectl get clusters.cluster.x-k8s.io local -n fleet-local
> ```
I have checked the machine list, there indeed 2 machines under provisioning, but I didn't find it until today.
I deleted these 2 machines and the upgrade progress seems continue again.

**Comment by Martin-Weiss** [comment]
> @Oats87 Is it possible to "cancel" an in-provisioning cluster? I guess in Martin's case, he might need to manually pre-drain/post-drain nodes and settle down the cluster. But just wonder if we can skip this.

@bk201 - what do you mean with manually pre-drain/post-drain and settle down the cluster? How can I do that?

**Comment by W0n9** [comment]
> > @W0n9 Did you have some fail-to-joined nodes before? From Rancher's log, rancher is provisioning two ghost machine:
> > ```
> > 2022-10-26T07:56:41.439986349Z 2022/10/26 07:56:41 [INFO] [planner] rkecluster fleet-local/local: waiting: provisioning worker node(s) custom-24ae94037853,custom-fa54219f944c
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > You can check the machine list with the command, and I guess two of them don't have a `PROVIDERID`.
> > ```
> > $ kubectl get machines -n fleet-local
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [The upgrade script is waiting for the cluster to become "Provisioned"](https://github.com/harvester/harvester/blob/a4872361145e0d0b99c4afeb6052f344acd48f30/package/upgrade/upgrade_manifests.sh#L245). And it won't continue until the CAPI cluster turns into "Provisioned". To check its status:
> > ```
> > kubectl get clusters.cluster.x-k8s.io local -n fleet-local
> > ```
> 
> I have checked the machine list, there indeed 2 machines under provisioning, but I didn't find it until today. I deleted these 2 machines and the upgrade progress seems continue again.

The upgrade progress continue again, but it raised a new problem. #3043

**Comment by bk201** [comment]
> @bk201 - what do you mean with manually pre-drain/post-drain and settle down the cluster? How can I do that?

@Martin-Weiss There are some helper scripts: https://github.com/bk201/misc/tree/main/rancher
But this needs some knowledge of plan secrets. Do you already pass this stage?

**Comment by Martin-Weiss** [comment]
> > @bk201 - what do you mean with manually pre-drain/post-drain and settle down the cluster? How can I do that?
> 
> @Martin-Weiss There are some helper scripts: https://github.com/bk201/misc/tree/main/rancher But this needs some knowledge of plan secrets. Do you already pass this stage?

What so you mean with "this stage"?

This is the status I have:
![grafik](https://user-images.githubusercontent.com/13362573/198204745-2e6c4131-98d0-4abd-a16b-b282fabcb238.png)

![grafik](https://user-images.githubusercontent.com/13362573/198204798-20cf1a98-8b5e-4224-bcd7-3c27039052fe.png)

![grafik](https://user-images.githubusercontent.com/13362573/198204932-10acd415-070f-44bf-b9cc-c680404c88c1.png)

I can see that something cordons the node harvester2 and the machine status is "waiting for uncordon to finish"

-> what is cordoning the node and what should happen / what is doing the "uncordon"?

One other thing I can see is this:

![grafik](https://user-images.githubusercontent.com/13362573/198211987-d27e1386-adcc-4a8a-bcb9-b4eedbca0ee8.png)

-> `Modified(1) [Cluster fleet-local/local]; configmap.v1 longhorn-system/longhorn-storageclass missing`

Is this related?

**Comment by janeczku** [comment]
Hitting same issue after failed upgrade.

**Comment by bk201** [comment]
>> What so you mean with "this stage"?

Never mind, the cluster has already passed the "Updating system services" stage (phase). Thanks.

**Comment by Martin-Weiss** [comment]
> >> What so you mean with "this stage"?
> 
> 
> 
> Never mind, the cluster has already passed the "Updating system services" stage (phase). Thanks.

Sure - but my cluster still does not continue..

**Comment by irishgordo** [comment]
On a single node cluster that had HDDs not SSDs.
Prior to the upgrade I had set:
```
cat > /tmp/fix.yaml <<EOF\nspec:\n  values:\n    systemUpgradeJobActiveDeadlineSeconds: "3600"\nEOF
```
then:
```
kubectl patch managedcharts.management.cattle.io local-managed-system-upgrade-controller --namespace fleet-local --patch-file=/tmp/fix.yaml --type merge
```
then:
```
kubectl -n cattle-system rollout restart deploy/system-upgrade-controller
```
Prior to starting the upgrade.  Since the disks are slow.  On a single-node, upgrades seem to perhaps not be as effected and the upgrade seems to finish without problem.
I will look into a multi-node bare-metal next and update the thread.

**Comment by irishgordo** [comment]
To follow-up.
On an environment with 3 Bare-Metal Nodes each:
- 8 Core Intel(R) Xeon(R) CPU E3-1265L v3 @ 2.50GHz
- 16GiB Mem DDR3 1333 MT/s
- 480GB Kingston SATA SSD
- 1GB Integrated Intel NIC (1port)

I was not able to see "Upgrade System Services" hang.  On an upgrade from v1.0.3 to v1.1.0, manually using a file-server and a version.yaml.

I was able to note a few other things however.

### Findings:
1. For 2 out of the 3 nodes, when they hit the "Waiting for Reboot" stage they required human intervention by manually cold-booting the node pressing the power.  The first node I waited for 2hrs on "Waiting for Reboot" before pressing power.  On the first node on the first manual boot back, it hung with a kernel panic something like:
```
Kernel panic - not syncing: Hard LOCKUP
Shutting down cpus with NMI
Kernel Offset: 0x1d000000 from 0xffffffff81000000 (relocation range: 0xffffffffff80000000-0xffffffffbffffffff)
```
  - And needed to be power-cycled again, after the second hard-shutdown the 1st node moved on from the "Waiting to Reboot" stage.  The 2nd node needed a hard reset as it hung on Waiting for Rebbot for 1.5hrs.  Then I just powercycled it and it was fine.
2. For the nodes that needed to be manually powered off since waiting for long time at `waiting for reboot stage` I noticed lots of these logs:
```
time="2022-10-28T19:57:41Z" level=error msg="error syncing 'cattle-system/apply-system-agent-upgrader-on-thinkcentre-harvester-node-17d60': handler system-upgrade-controller: jobs.batch \"apply-system-agent-upgrader-on-thinkcentre-harvester-node-17d60\" not found, requeuing"
time="2022-10-28T19:57:42Z" level=error msg="error syncing 'cattle-system/apply-system-agent-upgrader-on-thinkcentre-harvester-node-e6213': handler system-upgrade-controller: jobs.batch \"apply-system-agent-upgrader-on-thinkcentre-harvester-node-e6213\" not found, requeuing"
time="2022-10-28T19:57:42Z" level=error msg="error syncing 'cattle-system/apply-system-agent-upgrader-on-thinkcentre-harvester-node-231c2': handler system-upgrade-controller: jobs.batch \"apply-system-agent-upgrader-on-thinkcentre-harvester-node-231c2\" not found, requeuing"
time="2022-10-28T19:59:00Z" level=error msg="error syncing 'cattle-system/apply-sync-additional-ca-on-thinkcentre-harvester-node-3-6d2035': handler system-upgrade-controller: jobs.batch \"apply-sync-additional-ca-on-thinkcentre-harvester-node-3-6d2035\" not found, requeuing"
time="2022-10-28T19:59:03Z" level=error msg="error syncing 'cattle-system/apply-sync-containerd-registry-on-thinkcentre-harvester-n-0c087': handler system-upgrade-controller: jobs.batch \"apply-sync-containerd-registry-on-thinkcentre-harvester-n-0c087\" not found, requeuing"
time="2022-10-28T19:59:07Z" level=error msg="error syncing 'cattle-system/apply-sync-additional-ca-on-thinkcentre-harvester-node-2-e4e977': handler system-upgrade-controller: jobs.batch \"apply-sync-additional-ca-on-thinkcentre-harvester-node-2-e4e977\" not found, requeuing"
time="2022-10-28T19:59:15Z" level=error msg="error syncing 'cattle-system/apply-sync-additional-ca-on-thinkcentre-harvester-node-1-fe0556': handler system-upgrade-controller: jobs.batch \"apply-sync-additional-ca-on-thinkcentre-harvester-node-1-fe0556\" not found, requeuing"
time="2022-10-28T19:59:19Z" level=error msg="error syncing 'cattle-system/apply-sync-containerd-registry-on-thinkcentre-harvester-n-abeac': handler system-upgrade-controller: jobs.batch \"apply-sync-containerd-registry-on-thinkcentre-harvester-n-abeac\" not found, requeuing"
time="2022-10-28T19:59:22Z" level=error msg="error syncing 'cattle-system/apply-sync-containerd-registry-on-thinkcentre-harvester-n-74fad': handler system-upgrade-controller: jobs.batch \"apply-sync-containerd-registry-on-thinkcentre-harvester-n-74fad\" not found, requeuing"
time="2022-10-28T19:59:26Z" level=error msg="error syncing 'cattle-system/apply-sync-containerd-registry-on-thinkcentre-harvester-n-ce5dc': handler system-upgrade-controller: jobs.batch \"apply-sync-containerd-registry-on-thinkcentre-harvester-n-ce5dc\" not found, requeuing"
``` 
3. I noted from all nodes multiple `chroot failed to run command 'update-ca-certificates':
```
Update additional ca ...
chroot: failed to run command 'update-ca-certificates': No such file or directory
Done
Update additional ca ...
chroot: failed to run command 'update-ca-certificates': No such file or directory
Done
```

### Additional Info:
[node_3_kubelet.log](https://github.com/harvester/harvester/files/9892477/node_3_kubelet.log)
[node_3_containerd.log](https://github.com/harvester/harvester/files/9892478/node_3_containerd.log)
[node_2_kubelet.log](https://github.com/harvester/harvester/files/9892479/node_2_kubelet.log)
[node_2_containerd.log](https://github.com/harvester/harvester/files/9892480/node_2_containerd.log)
[node_1_kubelet.log](https://github.com/harvester/harvester/files/9892481/node_1_kubelet.log)
[node_1_containerd.log](https://github.com/harvester/harvester/files/9892482/node_1_containerd.log)

**Comment by dseralathan** [comment]
Got below error  during upgrade 

Upgrading Monitoring
managedchart.management.cattle.io/rancher-monitoring-crd patched (no change)
managedchart.management.cattle.io/rancher-monitoring unchanged
managedchart.management.cattle.io/rancher-monitoring patched
managedchart.management.cattle.io/rancher-monitoring-crd patched
Waiting for ManagedChart fleet-local/rancher-monitoring from generation 7
Target version: 100.1.0+up19.0.3, Target state: ready
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 7
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8
Sleep for 5 seconds to retry
Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8
Sleep for 5 seconds to retry

**Comment by albertkohl-monotek** [comment]
Upgrading from v1.0.3 > v1.1.0 is ill-advised. Tons of users had issues.
See release notes for v1.1.0: https://github.com/harvester/harvester/releases/tag/v1.1.0

**Comment by dseralathan** [comment]
two of our clusters got upgraded with same config successfully  , only 3rd cluster showed above error ..

**Comment by dseralathan** [comment]
New issue - Upgrade got stuck for already upgraded node - 

out of 4 nodes we upgrades 3 and when we try to re-run the upgrade its trying to corden the master node and got stuck 
Any way we can upgrade only a single node in cluster  :- 

# kubectl get bundles -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       NotReady(1) [Cluster fleet-local/local]; deployment.apps harvester-system/harvester [progressing] Available: 2/3; deployment.apps harvester-system/harvester-webhook [progressing] Deployment does not have minimum availability., Available: 2/3; kubevirt.kubevirt.io harvester-system/kubevirt [progressing] Deploying version 0.54.0-150400.3.7.1 with registry registry.suse.com/suse/sles/15.4, Resource is current
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   1/1                       
fleet-local   mcc-rancher-logging                           1/1                       
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring                        1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1

**Comment by dseralathan** [comment]
Not able to kill an running upgrade 

kubectl delete  upgrade.harvesterhci.io/hvst-upgrade-m8z28  -n harvester-system --force
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
Error from server (BadRequest): admission webhook "validator.harvesterhci.io" denied the request: cluster fleet-local/local status is provisioning, please wait for it to be provisioned

**Comment by bk201** [comment]
> Got below error during upgrade
> 
> Upgrading Monitoring managedchart.management.cattle.io/rancher-monitoring-crd patched (no change) managedchart.management.cattle.io/rancher-monitoring unchanged managedchart.management.cattle.io/rancher-monitoring patched managedchart.management.cattle.io/rancher-monitoring-crd patched Waiting for ManagedChart fleet-local/rancher-monitoring from generation 7 Target version: 100.1.0+up19.0.3, Target state: ready Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 7 Sleep for 5 seconds to retry Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8 Sleep for 5 seconds to retry Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8 Sleep for 5 seconds to retry Current version: 100.1.0+up19.0.3, Current state: ErrApplied, Current generation: 8 Sleep for 5 seconds to retry

@dseralathan is this still an issue, it could be https://github.com/harvester/harvester/issues/1983 and could you see if https://github.com/harvester/harvester/issues/2280#issuecomment-1132446373 helps?

**Comment by bk201** [comment]
The ghost machines are the cause of the issue.
https://github.com/harvester/harvester/issues/3104 displays more info in upgrade_manifest.sh logs. And the in-provisioning state check of the CAPI ill be addressed at https://github.com/harvester/harvester/issues/3067, close this one.

**Comment by felixtegelkamp** [comment]
> kubectl get clusters.cluster.x-k8s.io local -n fleet-local

Had the same issue, that the cluster did not get the status provisioned. The probes failed due to expired certificates. Was able to mitigate the issue creating (deleting old) new certs on host.
 
https://github.com/rancher/rancher/issues/41125#issuecomment-1506620040
