### ISSUE TITLE
[Doc] Add API docs

### ISSUE THREAD

**Issue by vickyhella** [harvester/harvester#3042]
We need to add the API reference pages to the new Docusaurus-based site.

I suppose we can use [this plugin](https://github.com/PaloAltoNetworks/docusaurus-openapi-docs) (or some better solutions) to implement this, but the API config files need to be reconfigured accordinlgy.

**Comment by guangbochen** [comment]
Close as the API doc is added in https://docs.harvesterhci.io/v1.1/category/api for both v1.1 and v1.2 versions.
