### ISSUE TITLE
[BUG] Network config lost during upgrade from v1.0.3 to v1.1.0

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#3043]
**Describe the bug**

In upgrade progress, after the first node reboot, I found that I lost the network connection to this node and got an error at harvester GUI `Host IP are inconsistent`.
![image](https://user-images.githubusercontent.com/38560218/198021891-f2da242c-428f-45e1-95e6-4e9c842f5ec5.png)
And then, I found that I have lost **all** network scripts in `/etc/sysconfig/network`.
![image](https://user-images.githubusercontent.com/38560218/198022148-18cd5206-eba6-427e-99d1-eff81ad35ef6.png)

**To Reproduce**
1. Click `Upgrade` at harvester GUI

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure: Baremetal with PowerEdge R740 64C64G with 2x 512G SSD

**Comment by Martin-Weiss** [comment]
I have exactly the same problem - installed with 1.0.3 and upgraded to 1.1.0 - first node got rebooted and now is stuck here without network:

![grafik](https://user-images.githubusercontent.com/13362573/198026988-a8a7820f-4933-4330-a11d-36f8a581963a.png)

**Comment by bk201** [comment]
Related issue: https://github.com/harvester/harvester/issues/2962
cc @guangbochen @ibrokethecloud

**Comment by bk201** [comment]
@tjjh89017 Do you know if any OS change could lead to this?

**Comment by tjjh89017** [comment]
I don't think OS will cause this problem.
Could you provide /oem/99_custom.yaml and /oem/99_custom.yaml.<TIMESTAMP> for us to debug?
Thanks a lot

**Comment by Martin-Weiss** [comment]
> I don't think OS will cause this problem. Could you provide /oem/99_custom.yaml for us to debug? Thanks a lot

Send you a PM with a link to my supportbundle - is this sufficient?

**Comment by tjjh89017** [comment]
> > I don't think OS will cause this problem. Could you provide /oem/99_custom.yaml for us to debug? Thanks a lot
> 
> Send you a PM with a link to my supportbundle - is this sufficient?

You could send it to me first. Let me check it.
But I think the better way is using Linux command to connect the server and then SCP those files to me

**Comment by guangbochen** [comment]
@W0n9 can u check if the following workaround would mitigate the issue in your env, thanks
1. ssh to the `harvester0` node
2. run `sudo su` and  create a config file under the `/usr/local/lib/sysctl.d/` path.
```shell
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
net.ipv6.conf.lo.disable_ipv6 = 1
```
3. reboot the node and check if the IPv4 is resumed
4. follow the same steps for all of your nodes if it works

**Comment by tjjh89017** [comment]
@W0n9 Do you use harvester-mgmt as VLAN network interface?
and provide `cluster_networks` config in deploy stage

**Comment by ghadeb** [comment]
Hi guys, I'm having a similar issue, but with a fresh install.

The network is accessible from the mgmt interface, but from the internal scope, there's no communication. I'm literally looking at the console dmesg now and the last messages I see are all related to IPv6, with a bpfilter started message just previous of that, and I can't progress from the "harvester host is being setup" page.

Anything I can look just now for you guys to help us out?

**Comment by W0n9** [comment]
> @W0n9 Do you use harvester-mgmt as VLAN network interface? and provide `cluster_networks` config in deploy stage

In v1.0.3, I use harvester-mgmt(bond-alb eno0 and eno1) for Management Network, And harvester-vlan(bond-alb eno2 and eno3) for VLAN Network.
Finally, I did not notice `cluster_networks` config in upgrade progress, can you share where it should be?

**Comment by W0n9** [comment]
> @W0n9 can u check if the following workaround would mitigate the issue in your env, thanks
> 
> 1. ssh to the `harvester0` node
> 2. run `sudo su` and  create a config file under the `/usr/local/lib/sysctl.d/` path.
> 
> ```shell
> net.ipv6.conf.all.disable_ipv6 = 1
> net.ipv6.conf.default.disable_ipv6 = 1
> net.ipv6.conf.lo.disable_ipv6 = 1
> ```
> 
> 3. reboot the node and check if the IPv4 is resumed
> 4. follow the same steps for all of your nodes if it works

I have tried this, but it doesn't recover.
I think the network configuration file was lost during the upgrade.

**Comment by tjjh89017** [comment]
@W0n9 Could you try this workaround step?
https://github.com/harvester/harvester/issues/3045#issuecomment-1292685394

**Comment by W0n9** [comment]
> @W0n9 Could you try this workaround step?
> https://github.com/harvester/harvester/issues/3045#issuecomment-1292685394

It seems work for me.
Network recovered.

**Comment by noahgildersleeve** [comment]
This looks like possibly the same issue as #3045

**Comment by Martin-Weiss** [comment]
> ```shell
> net.ipv6.conf.all.disable_ipv6 = 1
> net.ipv6.conf.default.disable_ipv6 = 1
> net.ipv6.conf.lo.disable_ipv6 = 1
> ```

FYI - this is required in any case if there is a IPv6 DHCP server available..

And I am not sure if /usr/local/lib/sysctl.d/ is the right place.

I would expect this in `/etc/sysctl.d/99-no-ipv6.conf `or similar and after creating this file.
Then execute `sysctl -p /etc/sysctl.d/99-no-ipv6.conf` and restart rke2-server.

Should we use `/usr/local/lib/sysctl.d/`  or `/etc/sysctl.d/`?

-> Answer to myself after testing - for some reason `/etc/sysctl.d/` is not persistent during a reboot.. so `mkdir -p /usr/local/lib/sysctl.d/` and create `/usr/local/lib/sysctl.d/99-no-ipv6.conf` ..

**Comment by noahgildersleeve** [comment]
I was able to repro this in a libvirt virtualized environment with two pairs of bonded NICs setup during install. The workaround [here](https://github.com/harvester/harvester/issues/3045#issuecomment-1292685394) brought back up the network and the upgrade seemed to be fixed. However I actually used the script for replacement from [here](https://gist.github.com/tjjh89017/dc3c91384aa14764a9458be6de3c8e5c#file-workaround_migrate_harv_mgmt_to_mgmt_br-sh-L143)

**Comment by bk201** [comment]
Close this issue with:
- https://github.com/harvester/harvester/issues/2962: Track the IPv6 issues.
- https://github.com/harvester/harvester/issues/3047 and https://github.com/harvester/harvester/issues/3045: Track the network interruption issue.

**Comment by bk201** [comment]
>> Should we use `/usr/local/lib/sysctl.d/`  or `/etc/sysctl.d/`?

@Martin-Weiss yeah, somehow I can't make `/etc/sysctl.d/` work even adding it to persistent path in elemental toolkit, thus suggest using `usr/local/lib/sysctl.d/ ` since it's in the man page.
