### ISSUE TITLE
[BUG] Harvester version control on upgrades

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#3044]
**Describe the bug**
Versions should be defined as approved for the air-gapped upgrade procedure.

**To Reproduce**
1. Create air gapped upgrade config 
2. use version 1.1.0-rc3
3. The version is accepted but the upgrade match is later discarded.

**Expected behavior**
A version that is acceptable/approved should be documented/specified in the upgrade documentation that works for future upgrades and/or a revision number should be acceptable for unofficial releases/fixes. ie 1.1.0-1, 1.1.0-2

**Comment by bk201** [comment]
We'll not support an upgrade from RC to a formal release but will remove the restriction in the code.
Also, we can add a pop-warning in the GUI if the current version is RC or master head builds.

**Comment by bk201** [comment]
> A version that is acceptable/approved should be documented/specified in the upgrade documentation that works for future upgrades and/or a revision number should be acceptable for unofficial releases/fixes. ie 1.1.0-1, 1.1.0-2

@abonillabeeche, I'll close the issue. Upgrading from RC will not be officially supported. The supported upgrade paths are documented at https://docs.harvesterhci.io/v1.1/upgrade/automatic#upgrade-support-matrix

To upgrade from an RC version for test purposes, we'll implement it in https://github.com/harvester/harvester/issues/3040
