### ISSUE TITLE
[BUG] Harvester Upgrade 1.0.3 to 1.1.0 does not handle multiple SLAVE in BOND for management interface

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3045]
**Describe the bug**
During upgrade of Harvester cluster the network is lost during in case there are two SLAVEs in the bond configuration for the management interface.

**To Reproduce**
Deploy Harvester 1.0.3 with a single bond for management using two NICs as slaves.
Run the upgrade and realize that the network is not available / not included in 99_custom.yaml, anymore.

**Expected behavior**
Upgrade works as expected.

**Environment**
 - Harvester ISO version: 1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal
 - Two NICs (eno1 + eno2 as bond0 for management)

**Additional context**
Problem seems to be here:
![grafik](https://user-images.githubusercontent.com/13362573/198071940-8e23ce07-1033-4f83-a444-cdfa282386b1.png)

When we have two SLAVEs in the bond config this is the error we get from the script:

![grafik](https://user-images.githubusercontent.com/13362573/198072208-3907a97a-fd37-4c79-9be9-3e8581f5549a.png)

-> the intention of the second BONDING_SLAVE_1 is not correct

**Comment by Martin-Weiss** [comment]
Workaround:
![grafik](https://user-images.githubusercontent.com/13362573/198072960-bf5fbbc1-2f95-44fe-9bae-9fc0c34689d9.png)

And then use the backed up /oem/99_custom.yaml.<date> and convert it with the adjusted script and then put it as 99_custom.yaml / reboot.

**Comment by Vicente-Cheng** [comment]
@tjjh89017 Hi Date,  
Could we temporarily remove one slave (if we have two slaves for this bonding) from bonding as a workaround?
It seems like the script should work if the mgmt network only has one slave, WDUT.

**Comment by tjjh89017** [comment]
> @tjjh89017 Hi Date, Could we temporarily remove one slave (if we have two slaves for this bonding) from bonding as a workaround? It seems like the script should work if the mgmt network only has one slave, WDUT.

The problem will be the migration script itself.
We have to avoid running that script twice and in error.
So currently, we might need to execute workaround script to do the right thing.

**Comment by noahgildersleeve** [comment]
I was able to reproduce this with a virtualized environment. I set it up with two NICs. On install via ISO I set both NICs as active and bonded in `balance-tlb`. 
![Screenshot_20221026_121006](https://user-images.githubusercontent.com/83787952/198138366-472d4432-839a-4d9d-a942-d55fe8f6f6d8.png)
I set up a single VM with a network that was on the harvester-mgmt VLAN interface with a VLAN ID of 1. I then turned off the VM and started the upgrade. It lost network connectivity.

![Screenshot_20221026_141121](https://user-images.githubusercontent.com/83787952/198139033-a9757395-9c1c-4cec-8c6a-53f905b385d9.png)

**Comment by tjjh89017** [comment]
## manual workaround full step:
1. cd /oem
2. restore 99_custom.yaml with v1.0.3 version, find the smallest timestamp and override 99_custom.yaml (`cp 99_custom.yaml.<TIME> 99_custom.yaml`)
3. copy the script `/usr/sbin/migration/migrate_harv_mgmt_to_mgmt_br.sh` to `/oem/migrate_harv_mgmt_to_mgmt_br.sh`
4. search the line `$(echo "$IFCFG" | grep "BONDING_SLAVE_")` in `/oem/migrate_harv_mgmt_to_mgmt_br.sh` and replace it with `$(echo "$IFCFG" | grep "BONDING_SLAVE_0")`  and `$(echo "$IFCFG" | grep "BONDING_SLAVE_1")`  (you will need to have 4 space in the beginning of those line) (If you have more than 2 bonding slaves, you will need to increase the number and put the additional lines.)
5. as figure ![](https://user-images.githubusercontent.com/13362573/198072960-bf5fbbc1-2f95-44fe-9bae-9fc0c34689d9.png)
6. execute `/oem/migrate_harv_mgmt_to_mgmt_br.sh` again without error and check the /oem/99_custom.yaml  has correct config.
7. reboot

## script workaround full step:
1. cd /oem
2. setup temporary network
3. `ip link set <NIC> up` (`ip link set eth0 up`)
4. `ip addr add <IP_CIDR> dev <NIC>` (`ip addr 192.168.0.2/24 dev eth0`)
5. ssh into that node and copy this script into /oem/a.sh (https://gist.github.com/tjjh89017/dc3c91384aa14764a9458be6de3c8e5c)
6. execute /oem/a.sh
7. open /oem/99_custom.yaml to check if the file is correct.
8. reboot node.

**Comment by Martin-Weiss** [comment]
Seems the workaround is not complete - the node comes back and has network - BUT - canal does not start properly:

```
[root@is1 ~]# kubectl -n kube-system logs rke2-canal-d4c7n kube-flannel
I1027 07:28:50.964085       1 main.go:205] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.co                                                  m/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefi                                                  x:flannel.alpha.coreos.com kubeConfigFile: iface:[harvester-mgmt] ifaceRegex:[] ipMasq:true subnetFile:/run/flannel/subnet.env publicIP: publ                                                  icIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-fla                                                  nnel/net-conf.json setNodeNetworkUnavailable:true}
W1027 07:28:50.964142       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might                                                   not work.
I1027 07:28:50.975846       1 kube.go:120] Waiting 10m0s for node controller to sync
I1027 07:28:50.976075       1 kube.go:378] Starting kube subnet manager
I1027 07:28:51.977138       1 kube.go:127] Node controller sync successful
I1027 07:28:51.977179       1 main.go:225] Created subnet manager: Kubernetes Subnet Manager - niam-msl-def-dr-hvm1
I1027 07:28:51.977200       1 main.go:228] Installing signal handlers
I1027 07:28:51.977518       1 main.go:454] Found network config - Backend type: vxlan
I1027 07:28:51.978324       1 main.go:276] Could not find valid interface matching harvester-mgmt: error looking up interface harvester-mgmt:                                                   route ip+net: no such network interface
E1027 07:28:51.978336       1 main.go:300] Failed to find interface to use that matches the interfaces and/or regexes provided
```

Before the upgrade we had harvester-mgmt and harvester-br0 (still the case on all other nodes that are not upgraded, yet) and on the upgraded node with the workaround canal is right - there is no harvester-mgmt interface - there is now mgmt-br and mgmt-bo but the canal config is still having  `iface: harvester-mgmt`

-> seems the helm upgrade process is stuck

`helm-install-rke2-canal-jtxxl                           0/1     CrashLoopBackOff   123 (17s ago)     16h`

**Comment by tjjh89017** [comment]
> Seems the workaround is not complete - the node comes back and has network - BUT - canal does not start properly:
> 
> ```
> [root@is1 ~]# kubectl -n kube-system logs rke2-canal-d4c7n kube-flannel
> I1027 07:28:50.964085       1 main.go:205] CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.co                                                  m/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefi                                                  x:flannel.alpha.coreos.com kubeConfigFile: iface:[harvester-mgmt] ifaceRegex:[] ipMasq:true subnetFile:/run/flannel/subnet.env publicIP: publ                                                  icIPv6: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-fla                                                  nnel/net-conf.json setNodeNetworkUnavailable:true}
> W1027 07:28:50.964142       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might                                                   not work.
> I1027 07:28:50.975846       1 kube.go:120] Waiting 10m0s for node controller to sync
> I1027 07:28:50.976075       1 kube.go:378] Starting kube subnet manager
> I1027 07:28:51.977138       1 kube.go:127] Node controller sync successful
> I1027 07:28:51.977179       1 main.go:225] Created subnet manager: Kubernetes Subnet Manager - niam-msl-def-dr-hvm1
> I1027 07:28:51.977200       1 main.go:228] Installing signal handlers
> I1027 07:28:51.977518       1 main.go:454] Found network config - Backend type: vxlan
> I1027 07:28:51.978324       1 main.go:276] Could not find valid interface matching harvester-mgmt: error looking up interface harvester-mgmt:                                                   route ip+net: no such network interface
> E1027 07:28:51.978336       1 main.go:300] Failed to find interface to use that matches the interfaces and/or regexes provided
> ```
> 
> Before the upgrade we had harvester-mgmt and harvester-br0 (still the case on all other nodes that are not upgraded, yet) and on the upgraded node with the workaround canal is right - there is no harvester-mgmt interface - there is now mgmt-br and mgmt-bo but the canal config is still having `iface: harvester-mgmt`

This will be the upgrade script in Harvester.
It didn't remove Canal config.

@yaocw2020 could we execute those two command to remove the Canal command after upgrading? (If upgrade didn't remove those.)
https://github.com/harvester/harvester/blob/master/package/upgrade/upgrade_manifests.sh#L345-L348

**Comment by guangbochen** [comment]
the configmap is expected to be removed by [the script](https://github.com/harvester/harvester/pull/2971/files) during the upgrade, can u please check if either `kubectl get  configmap rke2-canal-config -oyaml | grep canal_iface` and `ls -la /var/lib/rancher/rke2/server/manifests/rke2-canal-config.yaml` contains any output?

**Comment by Martin-Weiss** [comment]
The config map is correct and the iface is "" - but the helm upgrade job hangs / fails.

It seems the problem is that the helm upgrade is scheduled on the node that has the broken canal:

```
helm-install-rke2-canal-jtxxl                           1/1     Running            124 (4m24s ago)   16h     10.171.1.94    niam-msl-def-dr-hvm1   <none>           <none>
rke2-canal-d4c7n                                        1/2     CrashLoopBackOff   197 (112s ago)    7d21h   10.171.1.94    niam-msl-def-dr-hvm1   <none>           <none>
```

From the helm-install logs:

```
+ helm_v3 upgrade --set-string global.cattle.systemDefaultRegistry= --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterCIDRv6= --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 --set-string global.systemDefaultRegistry= rke2-canal /tmp/rke2-canal.tgz --values /config/values-10_HelmChartConfig.yaml
Upgrading rke2-canal
Error: UPGRADE FAILED: create: failed to create: Internal error occurred: failed calling webhook "rancher.cattle.io": failed to call webhook: Post "https://rancher-webhook.cattle-system.svc:443/v1/webhook/mutation?timeout=10s": context deadline exceeded
+ exit

```

**Comment by Martin-Weiss** [comment]
Seems I could find a further workaround in case the helm upgrade is scheduled on the upgraded node where canal is not running as the configured interface is not available, anymore!

`
kubectl -n kube-system edit configmap rke2-canal-config`

-> remove the interface specified in

```
data:
  canal_iface: ""
```

and then delete the canal pod in CrashLoopBackOff

**Comment by tjjh89017** [comment]
## Test Step

1. Install harvester v1.0.3 with two NICs in harvester-mgmt
2. upgrade to new version of Harvester.
3. Management Network should not be disconnected. (harvester-mgmt or mgmt-br)

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-47a3af23-head`. 

I tested this with two configurations. The support bundles are for after the upgrade. I ran the upgrades using the walkthrough for [airgapped upgrades](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade). 

## First Config

- Single node libvirt setup
   - 12 cores
   - 24GB RAM
   - SATA SSD
- bonded NIC setup during ISO install for management network
   - I setup the VLAN interface to use `harvester-mgmt` on VLAN 1
[bonded nic on management interface with VLAN on management.zip](https://github.com/harvester/harvester/files/9976600/bonded.nic.on.management.interface.with.VLAN.on.management.zip)

   
## Second config

- Single node libvirt setup
   - 12 cores
   - 24GB RAM
   - SATA SSD
- Two bonded NICs setup via harvester config during ISO install
[harvester.config.txt](https://github.com/harvester/harvester/files/9976640/harvester.config.txt)
   - First bonded NIC is the bonded management interface
   - Second bonded NIC is for the VLAN interface and is `harvester-vlan`
   - I setup the VLAN interface to use the second bonded nic `harvester-vlan`
[dual bonded nics with vlan on harvester-vlan bonded interface.zip](https://github.com/harvester/harvester/files/9976599/dual.bonded.nics.with.vlan.on.harvester-vlan.bonded.interface.zip)

### Other info

I saw that when I was done running these upgrades that the cluster network was created, but no network was. The VLAN network was created and up. It also still worked with VMs from before the upgrade. However none of the NICs are shown as available, including the management  network that should have been unused in the Second Config. In the VLAN networks if you try to create another one the cluster network shows as unavailable. 

So both of the environments will come up, but then the network configuration options seem to become unusable. I have more screenshots of the setups before and after the upgrade if needed

![Screenshot_20221109_174456](https://user-images.githubusercontent.com/83787952/200981543-6421e8d4-26f4-4d42-9790-65ca61e9e591.png)
![Screenshot_20221109_174128](https://user-images.githubusercontent.com/83787952/200981546-5bdd5f3a-dee7-4f49-8045-fd45e98cd960.png)
![Screenshot_20221109_174114](https://user-images.githubusercontent.com/83787952/200981548-85b03330-de42-43b5-b99f-cdd2ae6a2deb.png)
![Screenshot_20221109_174109](https://user-images.githubusercontent.com/83787952/200981549-7df424d1-15ad-40ca-a4da-4829082e4d53.png)

**Comment by tjjh89017** [comment]
@noahgildersleeve It looks the harvester-mgmt or mgmt-br is working fine after upgrade.
 `harvester-vlan` problem is not in the scope of this issue.
Could you file a new issue for those problem?
Thanks a lot

**Comment by yaocw2020** [comment]
> Tested in Harvester `master-47a3af23-head`.
> 
> I tested this with two configurations. The support bundles are for after the upgrade. I ran the upgrades using the walkthrough for [airgapped upgrades](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade).
> 
> ## First Config
> * Single node libvirt setup
>   
>   * 12 cores
>   * 24GB RAM
>   * SATA SSD
> * bonded NIC setup during ISO install for management network
>   
>   * I setup the VLAN interface to use `harvester-mgmt` on VLAN 1
>     [bonded nic on management interface with VLAN on management.zip](https://github.com/harvester/harvester/files/9976600/bonded.nic.on.management.interface.with.VLAN.on.management.zip)
> 
> ## Second config
> * Single node libvirt setup
>   
>   * 12 cores
>   * 24GB RAM
>   * SATA SSD
> * Two bonded NICs setup via harvester config during ISO install
>   [harvester.config.txt](https://github.com/harvester/harvester/files/9976640/harvester.config.txt)
>   
>   * First bonded NIC is the bonded management interface
>   * Second bonded NIC is for the VLAN interface and is `harvester-vlan`
>   * I setup the VLAN interface to use the second bonded nic `harvester-vlan`
>     [dual bonded nics with vlan on harvester-vlan bonded interface.zip](https://github.com/harvester/harvester/files/9976599/dual.bonded.nics.with.vlan.on.harvester-vlan.bonded.interface.zip)
> 
> ### Other info
> I saw that when I was done running these upgrades that the cluster network was created, but no network was. The VLAN network was created and up. It also still worked with VMs from before the upgrade. However none of the NICs are shown as available, including the management network that should have been unused in the Second Config. In the VLAN networks if you try to create another one the cluster network shows as unavailable.
> 
> So both of the environments will come up, but then the network configuration options seem to become unusable. I have more screenshots of the setups before and after the upgrade if needed
> 
> ![Screenshot_20221109_174456](https://user-images.githubusercontent.com/83787952/200981543-6421e8d4-26f4-4d42-9790-65ca61e9e591.png) ![Screenshot_20221109_174128](https://user-images.githubusercontent.com/83787952/200981546-5bdd5f3a-dee7-4f49-8045-fd45e98cd960.png) ![Screenshot_20221109_174114](https://user-images.githubusercontent.com/83787952/200981548-85b03330-de42-43b5-b99f-cdd2ae6a2deb.png) ![Screenshot_20221109_174109](https://user-images.githubusercontent.com/83787952/200981549-7df424d1-15ad-40ca-a4da-4829082e4d53.png)

Where is the mgmt cluster network? Did the harvester network controller manager initialize failed?

**Comment by noahgildersleeve** [comment]
I'm not sure where the mgmt cluster network is. It should show up, although it won't show in the cluster network section. I'm creating another ticket to track this issue and closing this one as fixed.

cc: @bk201 @guangbochen
