### ISSUE TITLE
[Question] - upgrade from 1.0.3 to 1.1.0

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#3048]
Hi,

Seeing the few issues that has come up since the 1.1.0 release, I guess it's probably better to wait a bit and for production environment.

Will there be another patch release that would include the few fixes in the coming days/weeks?

Thanks
Regis

**Comment by guangbochen** [comment]
Yes, a patch release of v1.1.1 will be scheduled and support upgrading from the previous v1.0.3 version. The date is not confirmed yet, but please keep an eye on the [releases](https://github.com/harvester/harvester/releases), thanks.

**Comment by RegisWeduLabs** [comment]
Thank you!

**Comment by guangbochen** [comment]
reopen and keep it as a reference for our community users, will close once the v1.1.1 is released, thanks.
