### ISSUE TITLE
[Question] (Discussion/Opinion) - Current Upgrade system sustainable?

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#3053]
Hi,

I've been watching Harvester for the last few months now, and also have a production cluster up and running.

It is such a great product in so many different aspects.

That said, looking at the upgrade experience for some users, I don't think it is sustainable on the long term for production environments...

I'm just thinking out loud here, but:

Harvester is a combination of different concepts and packages/components, and all of these are upgraded all at once:
- Harverter itself
- Operating System (elemental)
- Rancher
- RKE
- Kubevirt
- Rancher
- Rancher-monitoring
- Longhorn

A lot can go wrong here when upgrading - there could be issues with the different components for different reasons, and it can sometime be way more complicated to find out what component is failing.  Would it be a possibility to upgrade those packages separatly (using helm, or an upgrade dashboard from the UI)?

Of course, when upgrading the operating system/harvester itself, there is a need to reboot.  But for packages like Rancher, Monitoring,longhorn, kubevirt - these could be upgraded separatly?  This would also allow your users to patch critical security issues found in Rancher or a critical bug in longhorn without having to wait for the next release, while potentially enjoying new features of the different packages/components.  It would also help troubleshooting/rolling back more easilly if one upgrade fails.  At the moment, there is so many potential changes that it could be difficult to pinpoint what's wrong in a timely manner.  Might also help for QA as users could raise issues encountered using specific package versions - making it easier when bumping versions.

Of course, this is just an idea, and I'm sure it was discussed at some point.  But for the moment, it's a bit scary to upgrade a cluster as there is a lot that can go wrong - and since sometime you need to shut down all vms while upgrading (v1.1.0), it can cause a significant downtime.  I also understand the complexity of maintaining a compatibility matrix across different packages, testing them etc, and I have little idea on the implication of such a change.

Toughts?

Best Regards

**Comment by bk201** [comment]
@RegisHubelia Thanks for the great feedback. We understand the frustration and uncertainty you see.
Upgrade is a complicated task, especially if a project has many components involved. And it would be more challenging when all those components are bumped simultaneously.

We put user put users in the first place. That is the direction we are working toward, and that's why we use the one-click approach to make user's life easier. The team is working hard on the stability of the upgrade path, and feedback from the community is helpful.

**Comment by RegisWeduLabs** [comment]
@bk201, thank you.  Don't get me wrong, I have no frustration and fully respect/understand the dev efforts.  Uncertainty, sure, it's stressful currently to do an upgrade in a production environment.  And I fully understanding your mission to democratize the HCI management, and I really appreciate the approach.  

I still think that having "rolling updates" on the different components would ease the process (development and upgrade by end users), and also users would have the flexibility to patch different components, and I think mainly about security/vulnerabilities in one of those components.  I also think that it wouldn't make it harder for the users to be able to update components from the UI - but instead of having 1 main upgrade button, we'd end up in a controller where we could upgrade components (Basically, a glorified Rancher Apps section when using helm, if that makes sense).

Again, just throwing ideas...  Upgrading everything at once will always be a whole lot of work for the dev team and stressfull to the end users.  And when, for example, we upgrade longhorn, then we can monitor just the longhorn upgrade and volumes to make sure it goes smoothly.  I just find it's difficult to look out for every potential issue when upgrading the whole bunch of components at once.

Would be nice to have other feedbacks from other users about this I think  Hopefully a few other people will give their inputs.

Thank you and best regards.

**Comment by Martin-Weiss** [comment]
One of the challenges I see with updating all the different components in different order and not combined is the effort of testing and dealing with dependencies. 

I.e. new kube-virt feature requires new RPM installed on the OS side of things and new kube-virt first requires update of harvester and harvester upgrade requires new version of....

From my point of view - dependency management in relation to support matrix and proper testing is the nightmare of cloud-native infrastructures these days ;-).

**Comment by RegisWeduLabs** [comment]
Fair points.  That said, if that's the case for kuve-virt/harverster/os - this should be done together.  But does the dependencies with Rancher and longhorn would cause the same problem?

So having 3 upgrade options:
1) Harvester (includes kube-virt, harvester and elemental) - and would update everything if choosen (rancher, longhorn, etc...)
2) Rancher
3) Longhorn

If you've done Rancher/Longhron, when upgrading Harvester, it wouldn't need to do the Rancher/Longhorn upgrade.

**Comment by Martin-Weiss** [comment]
The "challenge" is, that there are also dependencies between Rancher and Harvester... (rancher within harvester and remote rancher UI integration, Provisioning integration, CSI/CPI..) and also between Harvester / Kube-VIP and Longhorn... i.e. managing the storage network via harvester in longhorn..

**Comment by w13915984028** [comment]
It is helpful to have those ideas/suggestions. Thanks.

We will break down the upgrade process, and find ways to optimize and enhance.
