### ISSUE TITLE
[Question] Storage tiering - non migratable storage class

### ISSUE THREAD

**Issue by dmytrobabeshko** [harvester/harvester#3054]
Hello,

The question related to the new storage tiering feature.
I created a new storage class with `Migratable=false` parameter.
- A new volume is provisioned using this new storage class in the harvester.
- This storage class is specified for VM image (A new VM is provisioned using this image. From Harvester UI or from rancher RKE2 node driver)
- New volume is provisioned from downstream RKE2 cluster (storage class in the downstream cluster uses this new non-migratable storage class in harvester)

I see in Longhorn that for all these cases RWX volumes are created. This type of volume is created using the longhorn NFS backend.
Is it the expected behavior for non-migratable volumes?

I would expect RWO volumes to be created for non-migratable storage classes. This type of volume is created using the iSCSI backend.

It is desired because it brings much better storage performance. It can be used in an environment where the Live migration feature can be sacrificed, e.g. single node harvester cluster.

Is it planned to have the ability to create RWO volumes?

**Comment by Martin-Weiss** [comment]
I believe RWX within Harvester for Block devices is required for VM migration.. and I am not sure if this RWX is NFS - I thought it is iSCSI in this case.. but did not verify..

**Comment by dmytrobabeshko** [comment]
I agree about VM migration, but I am about the case when it is not needed. I would like to set `migratable=false` on the storage class thus getting RWO and better IO performance.

AFAIK RWX is supported in Longhorn only by using the NFS backend https://longhorn.io/docs/1.3.2/advanced-resources/rwx-workloads/

**Comment by Martin-Weiss** [comment]
In Harvester I can see iSCSI connections to the block device volumes that have RWX. So I believe this is a different / new way and not the rwx via NFS. See also https://github.com/longhorn/longhorn/blob/master/enhancements/20210216-volume-live-migration.md#creating-a-migratable-storage-class - but as said I am not deep enough in this..

Regarding the "better IO performance" - what problem do you have with the performance and how much imporovement do you expect?

**Comment by futuretea** [comment]
@dmitrybabeshko For your case, you can change the accessModes `ReadWriteMany`  to `ReadWriteOnce` by `Edit Yaml` when creating vms/volumes
