### ISSUE TITLE
[BUG] Upgrade UI - can not be scrolled down

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3056]
**Describe the bug**
Upgrade Harvester 1.0.3 with a cluster having "many" nodes (in our case 16) and try to monitor the status with the UI.
Here we see this:
![grafik](https://user-images.githubusercontent.com/13362573/198277937-2ebbb1e5-bd19-4902-bae5-bff2f7bcb84b.png)

-> we can not scroll down to see the lower nodes.

**To Reproduce**
See above screenshot during upgrade and try to scroll down in firefox.

**Expected behavior**
Status can be scrolled down.

**Environment**
 - Harvester ISO version: 1.0.3

**Comment by lanfon72** [comment]
@WuJun2016 is it possible to use `max-height: 90vh` instead of `max-height: 800px`?
some display might use `1024 * 768` (less than 800, few pixel still not visible) and some display might use `1920 * 1200`.

**Comment by WuJun2016** [comment]
> @WuJun2016 is it possible to use `max-height: 90vh` instead of `max-height: 800px`? some display might use `1024 * 768` (less than 800, few pixel still not visible) and some display might use `1920 * 1200`.

good catch, thanks, i will change it

**Comment by WuJun2016** [comment]
Done.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/199507389-a54ca65f-cdf6-4898-820f-18fefc8b17cd.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.0** to `v1.1.0-master-68e78c87-head` (get trouble to upgrade from `v1.0.3`)
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. perform upgrade
3. Upgrade Info should be able to scrolled when it is large then the window.
