### ISSUE TITLE
[BUG] Failed to start Rancher Kubernetes Engine v2 (server)

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3060]
### Describe the bug
**NOTE: this happens very rarely in testing - low impact - eventually node resolves itself**
On a create node, very rarely, tested 5 times, I did encounter however the create-node throwing a temporary error:
```
[FAILED] Failed to start Rancher Kubernetes Engine v2 (server).
```
I think this is very rare to reproduce.

### To Reproduce
( this can not consistently be reproduced )
1. Provision a create-node, on v1.1.0
1. You "might" (though this is very rare in my attempts to reproduce) see the error
1. The node will eventually become ready and seems to resolve itself

### Expected behavior
It seemed to resolve itself, but the error was surprising.

### Support bundle
[supportbundle_68f9c6f7-1e17-429c-9e67-4aac29379d39_2022-10-27T18-52-39Z.zip](https://github.com/harvester/harvester/files/9882629/supportbundle_68f9c6f7-1e17-429c-9e67-4aac29379d39_2022-10-27T18-52-39Z.zip)

### Environment
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure: qemu/kvm 10C 18GiB Mem

### Additional context
[containerd.log](https://github.com/harvester/harvester/files/9882644/containerd.log)
[kubelet.log](https://github.com/harvester/harvester/files/9882645/kubelet.log)
![Screenshot from 2022-10-27 11-47-19](https://user-images.githubusercontent.com/5370752/198382859-4efe4a20-053b-47b1-a61f-4c7c87b32605.png)

**Comment by w13915984028** [comment]
@irishgordo As your description `qemu/kvm 10C 18GiB Mem`,  how did you stop the Harvester cluster and stop the `kvm/vm` ? If you use `force power off`, it may break `etcd`'s db and cause such error in next time's restart, but it can recover.


such log is found from the support-bundle, in rke2-server.log.  
```
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: panic: freepages: 
failed to get all reachable pages (page 5997: out of bounds: 5968)
```

Per https://github.com/etcd-io/etcd/issues/10722, it said `seems powerdown cause db corruption. `


> Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: {"level":"info","ts":"2022-10-27T18:46:53.382Z","caller":"embed/etcd.go:308","msg":"starting an etcd server","etcd-version":"3.5.4","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.18.1b7","go-os":"linux","go-arch":"amd64","max-cpu-set":10,"max-cpu-available":10,"member-initialized":true,"name":"harvester-node-1-v110-1d7d724a","data-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp","wal-dir":"","wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initial-election-tick-advance":true,"snapshot-count":10000,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-size-bytes":2147483648,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-interval":"5s"}

```
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: panic: freepages: failed to get all reachable pages (page 5997: out of bounds: 5968)
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: goroutine 232 [running]:
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: go.etcd.io/bbolt.(*DB).freepages.func2()
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1056 +0x99
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]: created by go.etcd.io/bbolt.(*DB).freepages
Oct 27 18:46:53 harvester-node-1-v110 rke2[17638]:         /go/pkg/mod/go.etcd.io/bbolt@v1.3.6/db.go:1054 +0x1ea
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Unit process 2309 (containerd-shim) remains running after unit stopped.
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Unit process 2397 (containerd-shim) remains running after unit stopped.
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Unit process 2511 (containerd-shim) remains running after unit stopped.
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Unit process 2522 (containerd-shim) remains running after unit stopped.
Oct 27 18:46:53 harvester-node-1-v110 systemd[1]: rke2-server.service: Unit process 2683 (containerd-shim) remains running after unit stopped.
```

**Comment by irishgordo** [comment]
@w13915984028 thanks for looking into this - I believe it may have been caused by a force shutoff on the VM - which probably broke `etcd`'s db.  But I don't 100% recall how it was shutdown.  I could go ahead and close this out as this was rare to reproduce consistently, and it did recover, if that sounds good? :smile: :+1:

**Comment by chrisho** [comment]
> @w13915984028 thanks for looking into this - I believe it may have been caused by a force shutoff on the VM - which probably broke `etcd`'s db. But I don't 100% recall how it was shutdown. I could go ahead and close this out as this was rare to reproduce consistently, and it did recover, if that sounds good? 😄 👍

How many nodes do u test??

**Comment by irishgordo** [comment]
@chrisho  - this was just experienced on 1 node

**Comment by chrisho** [comment]
@irishgordo ok. Is there any VMS in harvester? and when to force shutdown. 

I'm still trying hard to reproduce the problem, it is better to provide detailed steps, recording screen is also possible.

thanks.

**Comment by irishgordo** [comment]
@chrisho I've been unable to find a way to reproduce this.  Was testing a few different scenarios yesterday and wasn't able to find a way to reproduce this.  I'll go ahead and close this out- as it seems that there's not a consistent way to reproduce this.
