### ISSUE TITLE
[FEATURE] Bump support-bundle kit version

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3061]
**Is your feature request related to a problem? Please describe.**
Bump the support-bundle-kit to a newer version to align with go 1.18 and k8s client-go v1.23.x

https://github.com/rancher/support-bundle-kit

**Comment by irishgordo** [comment]
This looks good :smile: :+1: - I'll go ahead and close this out per testing preformed on:
https://github.com/harvester/harvester/issues/3064#issuecomment-1322843500
Validated, manually building the binaries in dist/artifacts at v0.0.12 worked great too.
