### ISSUE TITLE
[BUG] Upgrade: pre-drain/post-drain jobs fail an upgrade on first error pod

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3062]
**Describe the bug**

We've spotted that if the first pod of pre-drain/post-drain fails, the upgrade is marked as fail.
The retry mechanism of jobs is not respected.

<img src="https://user-images.githubusercontent.com/1691518/198494429-3e00a850-37bb-4716-a898-37f768c9dcc4.png" width="400">

There are still pods:

```
hvst-upgrade-xpf52-post-drain-harvester1-527kb          0/1     Error     0               143m
hvst-upgrade-xpf52-post-drain-harvester1-7qj7f          0/1     Error     0               141m
hvst-upgrade-xpf52-post-drain-harvester1-cht6v          0/1     Error     0               141m
hvst-upgrade-xpf52-post-drain-harvester1-czfbw          0/1     Error     0               141m
hvst-upgrade-xpf52-post-drain-harvester1-lgptq          1/1     Running   0               141m
hvst-upgrade-xpf52-post-drain-harvester1-tngv7          0/1     Error     0               141m
hvst-upgrade-xpf52-post-drain-harvester1-v4t89          0/1     Error     0               141m
hvst-upgrade-xpf52-post-drain-harvester1-w9hsk          0/1     Error     0               141m
```

```
++ kubectl get [virtualmachines.kubevirt.io](http://virtualmachines.kubevirt.io/) upgrade-repo-hvst-upgrade-xpf52 -n harvester-system '-o=jsonpath={.status.printableStatus}'
Error from server (NotFound): [virtualmachines.kubevirt.io](http://virtualmachines.kubevirt.io/) "upgrade-repo-hvst-upgrade-xpf52" not found
+ [[ '' == \R\u\n\n\i\n\g ]]
+ echo 'Try to bring up the upgrade repo VM...'
+ virtctl start upgrade-repo-hvst-upgrade-xpf52 -n harvester-system
Try to bring up the upgrade repo VM...
Error starting VirtualMachine [virtualmachine.kubevirt.io](http://virtualmachine.kubevirt.io/) "upgrade-repo-hvst-upgrade-xpf52" not found
+ true
+ sleep 10
```

**To Reproduce**
1. Find a way to make the pre-drain or post-drain job fail.
2. Upgrade fails, and the upgrade controller deletes upgrade VMs, despite jobs still retries.

**Expected behavior**

We should respect the retry.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.0.3 -> v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
We should also see if we want to avoid failure. Stuck with rancher provisioning is hard to recover and debug.

**Comment by Martin-Weiss** [comment]
I assume one way to force this initial failure might be to have problems on the storage side of things.. too large volumes that take too long to replicate or have failures before the upgrade gets started. Filesystem corruption on top of a volume might also be a way..

**Comment by FrankYang0529** [comment]
It looks like a job doesn't have failed condition when the first pod fails. We don't set `backoffLimit`, but the default value is `6`. A job has a failed condition only if it retries more than `backoffLimit` times.

```
status:
  conditions:
  - lastProbeTime: "2022-10-31T03:50:11Z"
    lastTransitionTime: "2022-10-31T03:50:11Z"
    message: Job has reached the specified backoff limit
    reason: BackoffLimitExceeded
    status: "True"
    type: Failed
```

**Comment by bk201** [comment]
Confirm the jobs do retry, and this is not an issue. Thanks, @FrankYang0529

**Comment by bk201** [comment]
> Additional context
We should also see if we want to avoid failure. Stuck with rancher provisioning is hard to recover and debug.

Tracked in another issue https://github.com/harvester/harvester/issues/3073
