### ISSUE TITLE
[FEATURE] upgrade shoud take log from `elemental upgrade` and process its return code

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3069]
**Is your feature request related to a problem? Please describe.**

In upgrade `post-drain` code, the `upgrade_os` will call `elemental upgrade`
`chroot $HOST_DIR elemental upgrade --directory ${tmp_rootfs_mount#"$HOST_DIR"}`

But for it's running log and return code, there is no proper processing now.

**Describe the solution you'd like**

`Elemental` supports setting a log file `cmd.PersistentFlags().String("logfile", "", "Set logfile")`

Upgrade could use this parameter, set a file to capture log, and alos catch the return code, when it is `1`, add proper output and print the log.

Note: At shell script view, `elemental` only returns `1` when error happens.
```
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}
```

**Describe alternatives you've considered**

`elemental` should also enrich it's return code to reflect proper error.

**Additional context**

**Comment by w13915984028** [comment]
Observed when trouble-shooting issue: 
https://github.com/harvester/harvester/issues/3070

Another similar issue:
https://github.com/harvester/harvester/issues/3062

**Comment by bk201** [comment]
@starbops Please help add the log; we can save the log to a directory under `/host/usr/local/`.
As a further enhancement, adding a trap to clean the [downloaded file ](https://github.com/harvester/harvester/blob/a4872361145e0d0b99c4afeb6052f344acd48f30/package/upgrade/upgrade_node.sh#L426), in case jobs are retried.

**Comment by noahgildersleeve** [comment]
Tested with upgrade from `v1.0.3` to `v.1.1.1-rc1` per instructions [here](https://github.com/harvester/harvester/pull/3099#issue-1434253056)
![Screenshot_20221110_145919](https://user-images.githubusercontent.com/83787952/201224059-663fafc5-df2f-408c-965a-dccbd46b36cc.png)


> Signed-off-by: Zespre Chang [zespre.chang@suse.com](mailto:zespre.chang@suse.com)
> 
> **IMPORTANT: Please do not create a Pull Request without creating an issue first.**
> 
> **Problem:**
> 
> We need more information about the execution of `elemental upgrade`.
> 
> **Solution:**
> 
> * Set up log file for `elemental upgrade`, the log file will be put under `/usr/local/upgrade_tmp/` on each node.
> * Clean up downloaded large files (squashfs) before exit
> 
> **Related Issue:**
> 
> #3069
> 
> **Test plan:**
> 
> 1. Prepare a v1.0.3 Harvester cluster with any number of nodes
> 2. Kickstart the upgrade to v1.1.0 (contains the changes in this PR)
> 3. After the upgrade succeeded, check the log file under `/usr/local/upgrade_tmp/elemental-upgrade-*.log`, and there shouldn't be any squashfs file
> 
> ```
> node-0:~ # ls -ltrh /usr/local/upgrade_tmp/
> total 12K
> -rw------- 1 root root   58 Nov  3 09:27 tmp.Gxer603C2T
> -rw------- 1 root root   58 Nov  3 09:33 tmp.7ho2PcdZH2
> -rwxr-xr-x 1 root root 1.4K Nov  3 09:34 elemental-upgrade-20221103093405.log
> ```
> 
> ```
> node-0:~ # cat /usr/local/upgrade_tmp/elemental-upgrade-20221103093405.log
> INFO[2022-11-03T09:34:05Z] Starting elemental version v0.0.14
> INFO[2022-11-03T09:34:05Z] Upgrading active partition
> INFO[2022-11-03T09:34:05Z] Creating file system image /run/initramfs/cos-state/cOS/transition.img
> INFO[2022-11-03T09:34:05Z] Running before-upgrade hook
> INFO[2022-11-03T09:34:05Z] Copying COS_ACTIVE image...
> INFO[2022-11-03T09:34:36Z] Finished copying COS_ACTIVE...
> INFO[2022-11-03T09:34:38Z] Running after-upgrade-chroot hook
> INFO[2022-11-03T09:34:38Z] Running after-upgrade hook
> INFO[2022-11-03T09:34:39Z] Backing up current active image
> INFO[2022-11-03T09:34:39Z] Moving /run/initramfs/cos-state/cOS/active.img to /run/initramfs/cos-state/cOS/passive.img
> INFO[2022-11-03T09:34:39Z] Finished moving /run/initramfs/cos-state/cOS/active.img to /run/initramfs/cos-state/cOS/passive.img
> INFO[2022-11-03T09:34:39Z] Moving /run/initramfs/cos-state/cOS/transition.img to /run/initramfs/cos-state/cOS/active.img
> INFO[2022-11-03T09:34:39Z] Finished moving /run/initramfs/cos-state/cOS/transition.img to /run/initramfs/cos-state/cOS/active.img
> INFO[2022-11-03T09:34:39Z] Upgrade completed
> ```
