### ISSUE TITLE
[BUG] Installer does not create UEFI boot entry on Dell PowerEdge systems

### ISSUE THREAD

**Issue by BTGUK** [harvester/harvester#3071]
**Describe the bug**
After installing Harvester on a Dell PowerEdge 12G and 13G server the server does not boot into the new Harvester installation. Further investigation showed that there is no boot entry in the server's UEFI setting for the new Harvester installation, which should have been created by the Harvester installer. 
This issue has been found with Harvester 1.0.3 and Harvester 1.1.0, however it is likely to affect all releases up to 1.1.0 as well.

**To Reproduce**
1. Connect USB memory stick or load DVD with Harvester 1.1.0 installation
2. Go into the server's boot menu (F11)
3. Select the Harvester installation medium for boot
4. Once the installer has loaded, perform a installation of Harvester onto local storage
5. At the end of the installation, the server reboots and goes back into the Harvester installer
6. When the installation medium is removed, the server no longer boots into an OS.

**Expected behavior**
After completion of the install process, the server boots into the new Harvester installation. 

**Environment**
 - Harvester ISO version: 1.1.0 and 1.0.3
 - Underlying Infrastructure: baremetal on Dell PowerEdge T320 and PowerEdge T630 using latest BIOS/firmware

**Additional context**
Support bundle sent to harvester-support-bundle@suse.com

**Comment by Itxaka** [comment]
This is due to the underlying elemental-cli installer not creating the proper entry. From version 7550964b03eac0e69ba350ba68f328ebd12168ca and onward, it creates an entry in the bootloader.

Up until this point we relied into the default EFI boot order which would try to use /EFI/BOOT/BOOTX64.efi as a fallback mechanism, so on reboot you would get the system to boot using that, but that is not reliable if using with USB boot media (We can eject CD/DVD but not USB) and we also discovered that on some EFI systems the system would fail to boot from disk unless you had a default entry (Like in this case)

Released versions of elemental-cli that fixexs this would be v0.0.16 and latest v0.1.0

**Comment by masteryyh** [comment]
Tested with v1.1.2-rc1 installed on VM with EFI and SecureBoot enabled, a boot entry called `elemental-shim` added to UEFI boot menu
<img width="1011" alt="image" src="https://user-images.githubusercontent.com/9990804/220503413-94c217cb-41e5-4e00-a009-cb9cb127f6c8.png">

**Test steps:**
1. Prepare a baremental or virtualized environment, with UEFI enabled;
2. Use newest Harvester ISO to boot up and install;
3. After rebooted, enter machine's UEFI boot menu, check if `elemental-shim` entry has been added.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.1.2-rc1`. Close this issue.

### Result
After VM machine booted, we can find the `elemental-shim` entry have been added to the Boot Manager Menu
![image](https://user-images.githubusercontent.com/29251855/220805906-2b88c2b4-2dc2-4dce-82f0-1cc670a5abc2.png)

And we can proceed to correctly install Harvester on `v1.1.2-rc1`
![image](https://user-images.githubusercontent.com/29251855/220807796-68482910-5f6d-4869-b713-e9e9f87d13fb.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `v1.1.2-rc1`

### Verify Steps
1. Prepare a qemu virtual machine which enabled UEFI by selecting `/usr/share/qemu/ovmf-x86_64-code.bin` firmware while creating VM
  ![image](https://user-images.githubusercontent.com/29251855/220807900-9ffafec5-c455-4a1d-82e1-37c7dbbb3ae2.png)
2. Boot with Harvester ISO
3. Wait for installation files loaded and reboot 
4. After rebooted, at the moment to enter UEFI page, press `F2` to enter BIOS setting 
5. Open the Boot manager setting
