### ISSUE TITLE
[BUG] The default value of the ui-index should match the harvester version

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3078]
**Describe the bug**

If the installed harvester is an official release version, the default value of ui-index should match this version，

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/e001a850-e7fd-4492-a9e1-0df8a43d762c)

**To Reproduce**

**Expected behavior**

In v1.1.0, the default value should be `https://releases.rancher.com/harvester-ui/dashboard/v1.1.0/index.html`

**Support bundle**

**Environment**
 - Harvester ISO version:  harvester-v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
should use v1.1 latest https://releases.rancher.com/harvester-ui/dashboard/release-harvester-v1.1/index.html instead.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/201147342-3af1587a-888a-4b89-bb3a-41b809379d83.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1.1-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to _Advanced/Settings_
3. `ui-index` should showing the version reflect to cluster version
