### ISSUE TITLE
Remove kubeconfig & token authentication

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#308]
Need to remove kubeconfig & token authentication in ISO installation
![image](https://user-images.githubusercontent.com/57614736/101455050-e9669f00-396c-11eb-9d8d-588d6576162a.png)

**Comment by guangbochen** [comment]
the login method is configurable via `HARVESTER_AUTHENTICATION_MODE` with options like `kubernetesCredentials,localUser` and on the ISO mode it will be set to local auth only.
