### ISSUE TITLE
[Question] How should I properly shut down Harvester cluster?

### ISSUE THREAD

**Issue by averyfreeman** [harvester/harvester#3080]
Not sure how I'm supposed to do this.  Googled the question and got SUSE guide for RKE, but is not useful - there's no `docker` service, and `kubectl get nodes` unfruitful [reference](https://www.suse.com/support/kb/doc/?id=000020031)

Still setting up 3-node cluster, I currently have two Harvester 1.1.0 nodes. Have noticed my longhorn-harvester PVE is degraded, but I'm assuming because 3 replica default and I haven't set up 3rd node yet, but I want to know how I can avoid making things worse. 

Need to shutdown all nodes so I can move stuff around.  I've just been hitting F12 and running "poweroff" in the past, is there a better way I should be shutting these things down? 

Would be nice to put in FAQ, let me know if need PR for docs/wiki.

**Comment by albertkohl-monotek** [comment]
@averyfreeman  i did the same. the drives go into a degraded state because they are out of sync when the nodes come back up, so Longhorn rebuilds the image. i THINK this is by-design. but not sure.

hope this is helpful.

**Comment by KyleSponz** [comment]
following this is something to write in the wiki or knowledge base as well

**Comment by averyfreeman** [comment]
This seems ridiculously basic, so ... dev team has an answer for this, right?

**Comment by ibrokethecloud** [comment]
the easiest way to shutdown the cluster would be to shutdown the VM's and then shutdown the nodes.

**Comment by albertkohl-monotek** [comment]
@ibrokethecloud does shutting down the vms prevent the nodes from having to rebuild volumes after they start back up? if so, that's good info to know.

**Comment by ibrokethecloud** [comment]
yes.. stopping the IO should ensure consistency of longhorn volumes.

**Comment by averyfreeman** [comment]
@ibrokethecloud this is very helpful.  Is a simple `poweroff` command as `root` user appropriate after stopping all the VMs, or would using the init layer offer some benefit (e.g. `systemctl poweroff` or `systemctl shutdown now`)?

Is there a command to stop all the VMs at once? 

I apologize for all the questions, if there's a reference you could point me towards I'd be happy to RTFM.  Just not really sure where to start looking (is it `kubectl`(?))

**Comment by starbops** [comment]
Hi @averyfreeman, for shutting down all the VMs you can either use:

- The UI, simply checks all the running VMs and then clicks the "Stop" button
- [`virtctl`](https://kubevirt.io/user-guide/operations/virtctl_client_tool/), try `virtctl stop <vm-name>` to stop a VM. Since the command only supports one VM at a time, you might have to loop through all your running VMs.

**Comment by averyfreeman** [comment]
> * The UI,

Sorry if I'm dense, but I've looked through all these menus several times and I don't see anything saying `shutdown` or `poweroff` 🤔

**Comment by albertkohl-monotek** [comment]
@averyfreeman in the website, you go to virtual machines, tick the checkbox next to STATE heading to check all vms, click the stop button.

(stop = shutdown)

**Comment by averyfreeman** [comment]
@albertkohl-monotek my apologies, I didn't read #issuecomment-1299515618_ closely enough, I thought @starbops was talking about shutting down the node.

**Comment by mircea-pavel-anton** [comment]
I would also add that an option to shutdown the server from the UI would be a nice addition. I was quite surprised when I initially set up Harvester to test it out, and the only way I managed to power off the server is to physically press the power button 😆

**Comment by albertkohl-monotek** [comment]
/bump, i agree. a shutdown / reboot button would be great!

**Comment by guangbochen** [comment]
Close as this is duplicate with https://github.com/harvester/harvester/issues/3261
