### ISSUE TITLE
[Doc]NICS not showing up

### ISSUE THREAD

**Issue by KyleSponz** [harvester/harvester#3081]
Cluster config is as follows
3 nodes each node with 2 gbe ports and 2 SFP ports with 10gb fiber sfps in them 

Not sure if it is a bug or not I have 2 GBE ports and a pair of SFP+ ports the SFP ports are each using 10gb SFPs bonded and are being used as the management nics, the other 2 ports I wanted to use to create two networks across the cluster with each one having nic dedicated to it 

There should be eno1 and eno2 available they are not, I do see eno3 and eno4 as network interfaces which are the SFPs and are configured as managmeent interfaces 

I did see eno1 and eno2 before I installed the sfps when I was flashing the server. The ports are showing on the network from the switches as green and passing traffic 

here is the result of ip -a
lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP mode DEFAULT group default qlen 1000
    link/ether b8:ca:3a:6b:c9:fc brd ff:ff:ff:ff:ff:ff
    altname enp7s0f0
3: eno4: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP mode DEFAULT group default qlen 1000
    link/ether b8:ca:3a:6b:c9:fc brd ff:ff:ff:ff:ff:ff
    altname enp7s0f1
4: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether b8:ca:3a:6b:c9:fc brd ff:ff:ff:ff:ff:ff
5: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP mode DEFAULT group default qlen 1000
    link/ether b8:ca:3a:6b:c9:fc brd ff:ff:ff:ff:ff:ff
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 26:a5:f3:e1:f9:e2 brd ff:ff:ff:ff:ff:ff
11: calicc039c9060e@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-b6fce60c-7bf8-02c0-1a0d-b096c6585394
12: cali15d30924c18@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-e8051f8d-80cf-bc6c-8beb-ff73e5475e51
13: cali51226030881@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-d65b5be2-adc8-a482-3ac7-b6f667f38c35
14: calid815d4f0bbb@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-bc5b7f76-4fa8-362d-d720-fcd89ed7c6c8
15: calie36acb4f0a4@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-bbc5685c-c93d-9337-dafc-7c622602fbdb
17: cali27209187884@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-e8ef2878-a8f1-a16d-0613-22f2be35b55b
18: calie481dbc6da2@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-4a8b713e-6d84-7f60-78e9-6d06e0cdc447
19: cali45df719fccf@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-9aa1dd10-5fee-e432-480c-a992143eda64
20: cali91c1c6069c5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-6c74148c-df02-80b2-3c1f-011a3bc3a96a
21: cali7ce990c3ef7@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-eeff94a4-f384-7c0a-6ab7-222757b258a0
22: cali3864ae613f4@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-55dcba84-48e5-9789-b398-fd0ca968f559
23: cali50c2afcacd1@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-9a94feb7-cb26-b765-c8c1-a608f1003515
24: cali9cc57a10af5@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-4bdb96ca-0507-2fd4-50b6-2ff721b4d933
25: cali2262559e39a@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-981ebdff-6439-8f9e-644d-b2212c661be6
26: cali4fe8a5ee53d@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-37a35889-e4e3-adbb-93b0-5e2e9fb40575
27: calibc42eac0f75@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-1ef05db2-37ad-30c4-b3de-3ccad79693bc
28: calif83974f8c40@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ee:ee:ee:ee:ee:ee brd ff:ff:ff:ff:ff:ff link-netns cni-340344f8-1aec-fbaf-060b-27378a90dc2c
72: vmclusternet-bo: <NO-CARRIER,BROADCAST,MULTICAST,MASTER,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 82:5f:05:b7:85:13 brd ff:ff:ff:ff:ff:ff

**Comment by ibrokethecloud** [comment]
Hi @KyleSponz are you please able to confirm the version of harvester and if possible please provide a support bundle?

**Comment by KyleSponz** [comment]
@ibrokethecloud 

Cluster version: v1.1.0-rc2

Output from one of the events creating the vm
apiVersion: v1
count: 1
eventTime: null
firstTimestamp: "2022-11-01T22:42:08Z"
involvedObject:
  apiVersion: v1
  kind: Pod
  name: harvester-public-nodenetwork-k5rq4
  namespace: harvester-system
  resourceVersion: "10103115"
  uid: 0434d6ed-1b4f-4f74-afbc-afeea9c8846a
kind: Event
lastTimestamp: "2022-11-01T22:42:08Z"
message: 'cannot find a network-attachment-definition (nodenetwork) in namespace (harvester-public):
  network-attachment-definitions.k8s.cni.cncf.io "nodenetwork" not found'
metadata:
  creationTimestamp: "2022-11-01T22:42:08Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:count: {}
      f:firstTimestamp: {}
      f:involvedObject: {}
      f:lastTimestamp: {}
      f:message: {}
      f:reason: {}
      f:source:
        f:component: {}
      f:type: {}
    manager: multus
    operation: Update
    time: "2022-11-01T22:42:08Z"
  name: harvester-public-nodenetwork-k5rq4.172397323233639d
  namespace: harvester-system
  resourceVersion: "10492266"
  uid: ca3e1138-fa76-4009-bda6-93192f7b9647
reason: NoNetworkFound
reportingComponent: ""
reportingInstance: ""
source:
  component: multus
type: Warning

Screenshot from one of the nodes the support bundle seems to time out 
![Screen Shot 2022-11-01 at 6 47 05 PM](https://user-images.githubusercontent.com/2746903/199356473-3e5bbc1c-4e0b-4ff6-9a25-ac7913fe13c0.png)

error shown
![Screen Shot 2022-11-01 at 6 53 04 PM](https://user-images.githubusercontent.com/2746903/199357075-4d563d8d-abb7-443c-bcab-4002b0a2ed6d.png)

**Comment by KyleSponz** [comment]
just had an idea ran 
lshw -class network

Its showing that the two SFPs are net1 and net0 unclaimed with the two gbe ports also as net1 and net0

lshw -class network
  *-network:0 UNCLAIMED     
       description: Ethernet controller
       product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress vpd cap_list
       configuration: latency=0
       resources: memory:d8d00000-d8dfffff ioport:fcc0(size=32) memory:d8ff8000-d8ffbfff memory:d8000000-d807ffff memory:d5000000-d50fffff memory:d5100000-d51fffff
  *-network:1 UNCLAIMED
       description: Ethernet controller
       product: 82599ES 10-Gigabit SFI/SFP+ Network Connection
       vendor: Intel Corporation
       physical id: 0.1
       bus info: pci@0000:01:00.1
       version: 01
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress vpd cap_list
       configuration: latency=0
       resources: memory:d8e00000-d8efffff ioport:fce0(size=32) memory:d8ffc000-d8ffffff memory:d8080000-d80fffff memory:d5200000-d52fffff memory:d5300000-d53fffff
  *-network:0
       description: Ethernet interface
       product: I350 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0
       bus info: pci@0000:07:00.0
       logical name: eno3
       version: 01
       serial: ec:f4:bb:de:4e:bc
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress vpd bus_master cap_list rom ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.6.0-k duplex=full firmware=1.67, 0x80000fab, 19.5.12 latency=0 link=yes multicast=yes port=twisted pair slave=yes speed=1Gbit/s
       resources: irq:19 memory:dae80000-daefffff memory:daff8000-daffbfff memory:da000000-da07ffff
  *-network:1
       description: Ethernet interface
       product: I350 Gigabit Network Connection
       vendor: Intel Corporation
       physical id: 0.1
       bus info: pci@0000:07:00.1
       logical name: eno4
       version: 01
       serial: ec:f4:bb:de:4e:bc
       size: 1Gbit/s
       capacity: 1Gbit/s
       width: 32 bits
       clock: 33MHz
       capabilities: pm msi msix pciexpress vpd bus_master cap_list rom ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
       configuration: autonegotiation=on broadcast=yes driver=igb driverversion=5.6.0-k duplex=full firmware=1.67, 0x80000fab, 19.5.12 latency=0 link=yes multicast=yes port=twisted pair slave=yes speed=1Gbit/s
       resources: irq:18 memory:daf00000-daf7ffff memory:daffc000-daffffff memory:da080000-da0fffff

**Comment by ibrokethecloud** [comment]
do you see anything in `dmesg`? 

you could also run `supportconfig` command to collect some common logs that we can use. I am available on rancher-users slack if you wish to DM me the file

**Comment by KyleSponz** [comment]
I cant get access to the slack Id be happy to contribute it wont let me login Ive also never used it might be just a user error 

I generated the file it wont let me sftp to the box to pull it and I do not have physical access to it at this time so how do I DL it?

**Comment by KyleSponz** [comment]
ran this as well 

lspci -vv | grep Ethernet
01:00.0 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
        Subsystem: Dell Ethernet 10G 4P X520/I350 rNDC
01:00.1 Ethernet controller: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection (rev 01)
        Subsystem: Dell Ethernet 10G 4P X520/I350 rNDC
pcilib: sysfs_read_vpd: read failed: Input/output error
07:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
07:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)

**Comment by ibrokethecloud** [comment]
do you see an unsupported sfp+ message in the system logs? `dmesg |grep -i sfp`

**Comment by KyleSponz** [comment]
dmesg |grep -i sfp
[    8.221619] ixgbe 0000:01:00.0: failed to load because an unsupported SFP+ or QSFP module type was detected.
[    8.419793] ixgbe 0000:01:00.1: failed to load because an unsupported SFP+ or QSFP module type was detected.

Let me guess the SFP isnt supported? Is there a list I could go check out?

**Comment by ibrokethecloud** [comment]
its more a hardware vendor enforced limit. I have run into the same issue in our labs.

I used the following config.yaml at time of installation.

It forces the kernel to ignore the unsupported sfp+ module.

```yaml
os:
  write_files:
  - content: |
     options ixgbe allow_unsupported_sfp=1
    path: /etc/modprobe.d/ixgbe.conf
  - content: |
      name: "reload ixgbe module"
      stages:
        boot:
          - commands:
            - rmmod ixgbe && modprobe ixgbe
    path: /oem/99_ixgbe.yaml
```

On a running cluster you could create the file `/etc/modprobe.d/ixgbe.conf` manually with the contents 
```
options ixgbe allow_unsupported_sfp=1
```

Then run: 
```
 rmmod ixgbe && modprobe ixgbe
```

However this will not survive a reboot. Injecting the same via config.yaml during node install will allow changes to persist.

**Comment by KyleSponz** [comment]
@ibrokethecloud 

What are your thoughts about this fix?
https://serveradminz.com/blog/unsupported-sfp-linux/

Fix the issue permanently
Perform the below commands, add the parameter to the grub file and update the grub file.

1. [root@xyz ~]# vi /etc/default/grub

2. GRUB_CMDLINE_LINUX=”ixgbe.allow_unsupported_sfp=1″ [adding the parameter to the line GRUB_CMDLINE_LINUX=”” ]

3. [root@xyz ~]# grub-mkconfig -o /boot/grub/grub.cfg [ upgrading the grub with the command]

4. [root@xyz ~]# rmmod ixgbe && modprobe ixgbe

5. Finally, reboot the system and see that the interface comes up right.


Just add that line to the grub.conf in the standard image?

**Comment by ibrokethecloud** [comment]
grub config is not directly exposed via harvester. That work around deploys a script which ensures that the `rmmod and modprobe` is always executed on boot.

**Comment by KyleSponz** [comment]
How did you inject that? I only have the capability to deploy ISOs via a usb at this time.

**Comment by ibrokethecloud** [comment]
when you deploy via USB, one of the last steps in the configuration of node would be to point to a config url. The contents of the file can be placed on a http endpoint and the same referred in the config url.
Harvester will pull that config yaml and merge it with the configuration.

**Comment by KyleSponz** [comment]
@ibrokethecloud 

od virt-launcher-prysmtest-q26zb
Failed to create pod sandbox: rpc error: code = Unknown desc = failed to setup network for sandbox "c6e2b3d33a3307c4c1b0180ccec8eab78510db96d835d3d69a08afe3039b2ec7": plugin type="multus" name="multus-cni-network" failed (add): [consortia/virt-launcher-prysmtest-q26zb:k8s-pod-network]: error adding container to network "k8s-pod-network": error getting ClusterInformation: connection is unauthorized: Unauthorized

Still getting this when launching but the networks are working any ideas?

**Comment by ibrokethecloud** [comment]
if you are still using rc2 then there is a known issue with the underlying rke2: https://github.com/rancher/rke2/issues/3425

This has been fixed in v1.1.0

**Comment by KyleSponz** [comment]
Implemented fix @ibrokethecloud suggested nics show up

**Comment by KyleSponz** [comment]
@ibrokethecloud the extra line in the config worked here is my yaml as promised 

`scheme_version: 1

os:
  write_files:
  - content: |
     options ixgbe allow_unsupported_sfp=1
    path: /etc/modprobe.d/ixgbe.conf
  - content: |
      name: "reload ixgbe module"
      stages:
        boot:
          - commands:
            - rmmod ixgbe && modprobe ixgbe
            - ip link set eno1 up && ip link set eno2 up
    path: /oem/99_ixgbe.yaml
`

**Comment by guangbochen** [comment]
reopen for doc enhancement.

**Comment by guangbochen** [comment]
Close and the doc is added in https://docs.harvesterhci.io/dev/troubleshooting/harvester#network-interfaces-are-not-showing-up

**Comment by gregkonush** [comment]
link for docs no longer working 
![image](https://github.com/harvester/harvester/assets/12027037/1cb71be5-769d-4be9-97f5-6b77134ccdf8)

**Comment by Vicente-Cheng** [comment]
Hi @gregkonush, I thought we were now using the version as the `dev` version.
https://docs.harvesterhci.io/v1.4/troubleshooting/harvester#network-interfaces-are-not-showing-up

Is this the link you are looking for?
