### ISSUE TITLE
Trying to PXE kickstart Dell Hardware (Not supporting IPXE)

### ISSUE THREAD

**Issue by yashi4engg** [harvester/harvester#3082]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Comment by yashi4engg** [comment]
We tried kickstart with VM which support IPXE and that works perfect. 

But Dell H/w (PowerEdge C6420) which dont support IPXE , I am unable to kick with harvester . 

I tried to kick using UEFI and Legacy boot mode options but no success. I followed below document - 
https://docs.harvesterhci.io/v0.3/install/pxe-boot-install/

**Comment by ibrokethecloud** [comment]
Hi @yashi4engg are you please able to advise what version of harvester you are using? 
There has been a small change to the config.yaml schema post v1.1.0, details of same are available here:

https://docs.harvesterhci.io/v1.1/install/pxe-boot-install

**Comment by yashi4engg** [comment]
I am trying to install harvester v.1.1.0

**Comment by ibrokethecloud** [comment]
are you please able to confirm the config spec is used from v1.1.0 docs. The network interface definition section has changed and in addition there is a `scheme_version` introduced.

If this fails, there should be a failure logged in `/var/log/console.log` which may provide information on possible issues with config spec.

**Comment by yashi4engg** [comment]
As per above comment I am able to kick a host with same config which supports IPXE . But My H/w dont support IPXE and now I am trying to kick it with Legacy boot mode ...I am able to get IP assign and also able to download pxelinux.cfg/default file but contents of file it wont understand so seems there should be some syntax change 

Any way you can let me know what should be syntax for defining default file to specify  below parameters :- 
root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs 
harvester.install.automatic=true harvester.install.config_url=http://$ENDPOINT/harvester/config-join.yaml

currently when i am trying to kick with below default file host went to halt state with erroe - 
" Fatal error - Dont Know how to handle root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs "

My current default file is - 
LABEL ipxe-join-efi
        kernel Images/harvester-v1.1.0-vmlinuz-amd64 initrd=Images/harvester-v1.1.0-initrd-amd64
        MENU DEFAULT
        initrd Images/harvester-v1.1.0-initrd-amd64
        append root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs harvester.install.automatic=true harvester.install.config_url=http://$ENDPOINT/harvester/config-join.yml

**Comment by ibrokethecloud** [comment]
the rootfs image location doesnt seem to have a valid address could that be the issue?

**Comment by ibrokethecloud** [comment]
```
LABEL ipxe-join-efi
  KERNEL Images/harvester-v1.1.0-vmlinuz-amd64
  MENU DEFAULT
  append initrd=Images/harvester-v1.1.0-initrd-amd64 root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs harvester.install.automatic=true harvester.install.config_url=http://$ENDPOINT/harvester/config-join.yml
```
I am not entirely sure on the PXE setup but would something like above work? 

I used this as a reference: https://wiki.syslinux.org/wiki/index.php?title=PXELINUX

**Comment by yashi4engg** [comment]
location is correct but error I am getting is below which suggest its unable to understand what to do with rootfs squash image .

dracut: don't know how to handle 'root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs'

**Comment by ibrokethecloud** [comment]
before the dracut error, do you see a network transfer trying to pull the image?

**Comment by yashi4engg** [comment]
No network error ...this error is there before trying to download.

**Comment by yashi4engg** [comment]
Hi Team .. I made some changes and now syntax works fine and able to download root=live:http://$ENDPOINT/harvester/harvester-v1.1.0-rootfs-amd64.squashfs file . But now my host is going to emergency mode during installation with below error :- 

[OK] Finished Wait for udev to Complete Device Initialization.
[Time] Timed out waiting for device /dev/disk/by-lable/COS_OEM
[DEPEND] Dependency failed for /oem
[DEPEND]  Dependency failed for Local File System
[Time] Timed out waiting for device /dev/disk/by-lable/COS_PERSISTENT
[DEPEND]  Dependency failed for /usr/local
[OK] Stopped Dispatch Password Requests to Console Directory Watch.

**Comment by yashi4engg** [comment]
I am now stuck with above error ...with above error host failed and trying to go to emergency mode , even in. emergency mode it found root user locked.

**Comment by ibrokethecloud** [comment]
is there sos log generated?

**Comment by yashi4engg** [comment]
No as after above error host went to emergency mode but not allowing do anything . Below is message while going to emergency - 

You are in emergency mode .After logging in ,type "journelctl -xb" to view system log, systemctl reboot to reboot, systemctl default or esit to boot in default mode.

Cannot open access to console,the root account is locked. 
see sulogin main page for more details .

Press Enter to continue.

**Comment by yashi4engg** [comment]
Issue resolved..I did some changes in default file and config-join.yml ...
