### ISSUE TITLE
[Not able to create Cluster network when we select all nodes]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3085]
**Describe the bug**
It's not allowing to create cluster network if we select all nodes. When we select all nodes in node selector, it's not showing any interfaces (Sorry no matching options).

But if we select specific node in node selector, it showing the interface for every node.

If we use specific node option in Node selector, we able to see interface. please below screen shot.

<img width="1218" alt="Screen Shot 2022-11-01 at 6 19 45 PM" src="https://user-images.githubusercontent.com/62717435/199372436-9bf32690-5d75-48fd-97e5-545073f175a3.png">

But if we select all nodes in cluster, there is no matching interfaces.

<img width="1197" alt="Screen Shot 2022-11-01 at 6 22 05 PM" src="https://user-images.githubusercontent.com/62717435/199372577-3a1e6434-b0f3-4bc3-9d37-0143035fa5a1.png">

As of now, these Dell nodes having 2 x 10G interfaces (enp24s0f0,enp24sof1).

enp24s0f0 - We are using for management network with balance-tlb bond mode with single interface.

Now we able to see enp24s0f1 is available in every node but couldn't able to configure it. We have to configure this interface for VM management.

Note:- These cluster was working fine with 1.0.3 version. We see issue after upgrade to 1.1.0 version. Now VM's in the cluster not able to communicate.

**Environment**
 - Harvester ISO version: 1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge C6420):

**Comment by ibrokethecloud** [comment]
are you please able to provide a support bundle? 

so if my understanding is correct enp24s0f0 was using for management interface as a single nic bond and enp24s0f1 was being used for workload networks via VLAN config?

**Comment by ApolloDS** [comment]
I had the same problem here with 4 nodes setup.

As a workaround I label each node with hv1=true (my cluster name is hv1).
Then I select nodes(s) matching rules and take key=hv1, value=true.
Then all the interfaces are displayed in the selector field.

**Comment by midhunthampi** [comment]
Thanks @ApolloDS 

This workaround worked out. 

@ibrokethecloud 

yes, We are using single interface bond for both management and VM traffic.

**Comment by n313893254** [comment]
Hi, @midhunthampi. Thanks for your description. It is a bug that may be caused by node filtering. And I want to further validate my assumption, could you provide a host list page screenshot? I want to check the host state. I think it will help to find the root cause.

**Comment by midhunthampi** [comment]
It got fixed with latest version. Now we are able to select all nodes. Thanks.
