### ISSUE TITLE
[BUG] image download error Pod spec node ID doesn't match the desired node ID

### ISSUE THREAD

**Issue by ApolloDS** [harvester/harvester#3086]
**Describe the bug**
I try to download a 36GB image from a web-server. Image is downloaded but the following error is displayed then:
"Pod spec node ID harvester-9mx7t doesn't match the desired node ID hv11"

I have the following nodes active:
* hv11
* harvester-2gmcg
* harvester-9mx7t
* harvester-jkvk6

**To Reproduce**
1. Go to Images - Create
2. Type in URL of a local HTTP Server -> http://host1:8080/image.qcow2
3. Image is then downloaded
4. After some while the error above is displayed.

**Expected behavior**
Should add the image to the image store.

**Support bundle**
Not yet.

**Environment**
 - Harvester ISO version: 1.1.0
 - 4 * Baremetal with Supermicro X8DTT

**Additional context**
Tried repeated download, it always leads to the same error.

**Comment by irishgordo** [comment]
@ApolloDS I was not able to reproduce this with the setup of:

3 Node bare-metal Harvester Cluster each node with:
- 16GiB DDR3 RAM
- 480 GB SSD Kingston 
- Intel(R) Xeon(R) CPU E3-1265L v3 @ 2.50GHz (8 Cores)

Harvester v1.1.0

File-Server:
[Caddy](https://caddyserver.com/) running on HTTP as well, not HTTPS:
- 4CPU
- 8GB Mem

![Screenshot from 2022-11-02 14-36-27](https://user-images.githubusercontent.com/5370752/199608223-82ae84a5-cf73-4477-abd2-573a0c3d1a91.png)

I am able to have the image download from the Caddy file server into the 3 node Harvester cluster and spin up a VM from the image.  And change the various nodes it runs on with Node Scheduling.
![Screenshot from 2022-11-02 14-52-18](https://user-images.githubusercontent.com/5370752/199609807-e86dc866-a950-4547-8730-c5e556aa571d.png)
![Screenshot from 2022-11-02 14-50-57](https://user-images.githubusercontent.com/5370752/199609809-5a5b3031-25ca-488b-812e-0685cf959dd8.png)
![Screenshot from 2022-11-02 14-49-35](https://user-images.githubusercontent.com/5370752/199609810-f41c66fd-97f0-48b1-9f37-cde2f0373789.png)

I was not able to see that error in the "Images" section.
![Screenshot from 2022-11-02 14-58-35](https://user-images.githubusercontent.com/5370752/199610514-203204a5-de73-45e5-88a4-d4d4564c16eb.png)

For the 36GB qcow2 Image, are you using a custom storage class, something other than `harvester-longhorn (default)`?
![Screenshot from 2022-11-02 15-00-36](https://user-images.githubusercontent.com/5370752/199611006-b273a671-cd0c-49b7-bd7c-a1d34cca1d7a.png)

Video, sped up fast:

https://user-images.githubusercontent.com/5370752/199612283-6a6e2c4e-76aa-40e7-b2a7-d48f7e6379a6.mp4

**Comment by ibrokethecloud** [comment]
are you please able to generate a support bundle when this import error is reported?

**Comment by ApolloDS** [comment]
> are you please able to generate a support bundle when this import error is reported?

Can you tell me where I can upload the support bundle?
I don't want to put it here.

Thanks.

**Comment by ApolloDS** [comment]
Here is the status I see:
![image](https://user-images.githubusercontent.com/3502089/199749423-51fe4da8-e259-4379-829d-77e297a28f09.png)

Some Images are ok, some just don't work.

**Comment by futuretea** [comment]
@ApolloDS Hi, you can send the bundle to harvester-support-bundle@suse.com with the correct issue ID.

**Comment by ApolloDS** [comment]
Hi @futuretea , 
I just sent out the support file.

Thank you very much

**Comment by w13915984028** [comment]
@ApolloDS Is this issue solved?

Could you clarify the sotrage size in each NODE, are there only one disk or several disks.

To download an image into cluster, it will take some temp space to store the image fisrt, then into PV. Suspect there is disk pressure in Node.  It is also helpful to do `df -H` in each NODE.

**Comment by ApolloDS** [comment]
Hi @w13915984028 ,
No, the issue still persists, also the cluster is very unstable after a clean install of v1.1.1. It seems that longhorn has a lot of problems with stability.
I have 4 node setup (Supermicro X8DTT), each with exactly the same config: defaultdisk SSD 1TB, extra-disk 2TB HDD.
Freespace on defaultdisk is 300GB - 600GB on each node.
Storage Class is ssd and hdd, hdd is default.
I have setup a storage vlan.

Cluster is in general very unstable. Also the nodes of 3 RKE2 clusters are always in reconciling state etc.

**Comment by w13915984028** [comment]
@ApolloDS Did you ever try to test only with SSD? What is the speed of your HDD ?

https://longhorn.io/docs/archives/1.2.4/best-practices/#minimum-recommended-hardware

**Comment by ApolloDS** [comment]
> @ApolloDS Did you ever try to test only with SSD? What is the speed of your HDD ?
> 
> https://longhorn.io/docs/archives/1.2.4/best-practices/#minimum-recommended-hardware

I can do that...
How can I move all the vm volumes from storageclass hdd to ssd?

**Comment by w13915984028** [comment]
The root cause is in https://github.com/harvester/harvester/issues/3450, 

and it has been fixed in https://github.com/longhorn/longhorn/issues/5443

Harvester track the issue via:

https://github.com/harvester/harvester/issues/3555
