### ISSUE TITLE
[BUG] Networks should be renamed to VM Networks

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3088]
**Describe the bug**
Harvester 1.1.0 looks a bit strange when configuring the network setup:

![grafik](https://user-images.githubusercontent.com/13362573/199489393-716a58e7-597f-4c13-9108-afb26eeb3247.png)

-> Networks / Networks

**To Reproduce**
See above

**Expected behavior**
A more logical way for the user - Networks as headline and then a child "VM networks"

**Environment**
 - Harvester ISO version: 1.1.0

**Comment by TachunLin** [comment]
Verified **fixed** on `master-25799b96-head` (11/17). Close this issue.

### Result
VLAN related page have been renamed to `VM Networks`
![image](https://user-images.githubusercontent.com/29251855/202437187-7f4f58b7-17ad-46e1-a81f-2c67ee45ead6.png)

![image](https://user-images.githubusercontent.com/29251855/202437243-5f477611-d7a2-47f2-9235-ff683f9f1481.png)

### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: master-25799b96-head

### Verify Steps
1. Check VM Networks page name and title in Network
