### ISSUE TITLE
[BUG] Harvester 1.1.0 does not properly import existing backups

### ISSUE THREAD

**Issue by bclinuxco** [harvester/harvester#3095]
**Describe the bug**
Backup import fails when following the procedure for restoring VMs from one cluster to a new cluster as outlined in the Harvester documentation. v1.1.0 admission controller wants the VM to have already existed in the cluster before it will register the backup metadata.

From harvester pod logs:
time="2022-11-02T21:23:33Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:23:38Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:23:43Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:23:48Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:23:53Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:23:58Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:03Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:08Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:13Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:18Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:23Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:28Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:33Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:38Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"
time="2022-11-02T21:24:43Z" level=error msg="can't sync vm backup metadata, target:nfs:nfs://10.0.2.50:/mnt/vol01/harvest_backup, err: admission webhook \"validator.harvesterhci.io\" denied the request: virtualmachines.kubevirt.io \"gitlab\" not found"

**To Reproduce**
1. Install new Harvester v1.1 cluster from ISO
2. Create the images and backup target to match existing v1.1 system
3. Wait for backups to be synced and available for restore to new cluster

**Expected behavior**
Backups should appear in the UI available for restore to recreate VMs in new cluster as they did in V1.0

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure : Bare Metal on Dell R610 /w original source cluster on Dell R620

**Comment by bk201** [comment]
@FrankYang0529 Could you take a look? Thanks!

**Comment by irishgordo** [comment]
@FrankYang0529  - this looks good :smile: :+1: !

I tested with Harvester Version v1.1.1-rc1.
Tested different combinations of:
https://github.com/harvester/harvester/pull/3107#issue-1435649785
Like having multiple volumes associated with the vm and writing data to those, then restoring to a new vm as well.

*supporting screenshots*
![Screenshot from 2022-11-10 12-18-50](https://user-images.githubusercontent.com/5370752/201197552-7c552254-b1c5-40d1-837c-9ed7dfa2c03a.png)
![Screenshot from 2022-11-10 12-16-13](https://user-images.githubusercontent.com/5370752/201197556-22d801b4-1902-4638-97f2-48bab6edbc42.png)
![Screenshot from 2022-11-10 12-13-13](https://user-images.githubusercontent.com/5370752/201197558-af305816-30c6-4e42-a4a6-61eb31712c6d.png)
![Screenshot from 2022-11-10 11-58-08](https://user-images.githubusercontent.com/5370752/201197559-748cfab8-16a9-4a61-9f86-66937f44c810.png)

I'll go ahead and close this out :smile: :+1:
