### ISSUE TITLE
[BUG] Can not specify multiple vip pool CIRDs with comma separation

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3100]
**Describe the bug**
Trying to specify multiple vip-pools in the default namespace comma separated: 

![grafik](https://user-images.githubusercontent.com/13362573/199679678-23ae8b29-4032-4de4-8790-04f4e7e21dc4.png)

**To Reproduce**
Try to specify two CIDRs with comma separated for the default namespace.

**Expected behavior**
Multiple CIDRs should be able to be specified.

**Environment**
 - Harvester ISO version: 1.1.0

**Comment by Martin-Weiss** [comment]
We have multiple VLANs and we need LoadBalancer VIPs via CPI in different ones. Not sure how this should/will work from a conceptional point of view via the Harvester CPI..

VM: VLAN1, VLAN2, VLAN3 and in each VLAN we need different VIPs..

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/200796787-4ca57ef9-540b-4ea4-8974-f8f79f39ca95.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-1a7693fd-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard then navigate to _Advanced/Settings_
3. Edit `vip-pools` and add multiple CIDR which separated by comma (no space between)
4. CIDR should able to added

**Comment by guangbochen** [comment]
reopen for doc, @futuretea can u please help to add the `vip-pools` setting to the https://docs.harvesterhci.io/v1.1/advanced/settings page, thanks.

**Comment by guangbochen** [comment]
close as the doc PR is added via https://github.com/harvester/docs/pull/256.
