### ISSUE TITLE
disable edit network vlanID

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#311]
**Description:**
1. user should not allow editing the vlan ID of the existing networks, this is because for existing VM the VLAN ID will not be changed until the user restart the VM, and for new created VM they will not be able to comminute with the existing VM with the previous VLAN ID.
2. on the network listing page, change the type of bridge's display name to `L2VlanNetwork ` to make it consistent.

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/101608769-1a180880-3a41-11eb-811e-e53356597b8b.png)
![image](https://user-images.githubusercontent.com/57614736/101608830-2e5c0580-3a41-11eb-9fc4-80c72978566d.png)
