### ISSUE TITLE
[Not able to see Storageclass parameter options while creating]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3110]
**Describe the bug**
We are not able to see parameter options to set replica and other settings when we create storageclass.

<img width="1227" alt="Screen Shot 2022-11-04 at 12 50 56 PM" src="https://user-images.githubusercontent.com/62717435/200063108-da4fc084-1a91-43b6-a3b2-d729ea8184cc.png">

**Comment by ibrokethecloud** [comment]
are you please able to provide us information on what version of harvester you are using, details of your environment.

any chance we could also look at the network request/responses from your browser when this happens?

it is likely some resource is not loading, and the network request information should help us identify what is likely to be causing this.

**Comment by midhunthampi** [comment]
We could able to create storage class with edit yaml option

**Comment by janeczku** [comment]
Could you please reopen. This is a UI bug. It also affects the ability to modify existing storage classes.
@rebeccazzzz


<img width="302" alt="Bildschirmfoto 2023-01-03 um 15 36 05" src="https://user-images.githubusercontent.com/3813921/210378336-263b8ce3-32ba-4d4f-bffd-1879cfd59092.png">

**Comment by midhunthampi** [comment]
Reopened the request as still UI issue there.

**Comment by Vicente-Cheng** [comment]
This is duplicated with https://github.com/harvester/harvester/issues/3348.
@midhunthampi, feel free to reopen it if it happens again after the fixed version `v1.1.2`.
