### ISSUE TITLE
[BUG] Installer crashes when MTU in network config is empty and pressing up arrow key

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#3112]
**Describe the bug**

Installer will crash when using static IPv4 configuration and leave `MTU` blank.

**To Reproduce**
1. Go to `Network configuration` page in Harvester Installer;
2. Select `Static` for `IPv4 Method`;
3. Fill in IP address and gateway, leave `MTU` blank;
4. When cursor is on `MTU` input field, press up arrow key to return to `Gateway` and installer will crash.

**Expected behavior**

Installer will continue working without any issue.

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Nested in Proxmox

**Comment by ibrokethecloud** [comment]
are you please able to provide us the /var/log/console.log

**Comment by irishgordo** [comment]
@masteryyh - I was curious, should it be adding `nbsp;`/`space`/non-breaking-whitespace of sorts when you hit the arrow up key after adding a value and then return into the input of the `MTU`?

It doesn't crash currently on the Harvester Version: master-be92fd08-head.
But it does seem to add an additional white space, when you head up, then you head back down into the field to edit the MTU.
When we input "0" as the value for MTU, head up with the "up arrow", it clears the MTU field, then heading back down into the MTU field with the down arrow, it puts a space there where the 0 was and the cursor is now not at the start of the input field for MTU.


https://user-images.githubusercontent.com/5370752/200968428-d319c8a8-d908-4139-ae53-a9442ccdc768.mp4

**Comment by irishgordo** [comment]
@masteryyh  - I'll go ahead and close this out as the installer doesn't crash per testing :smile: :+1: - I'll open up something else to track: https://github.com/harvester/harvester/issues/3112#issuecomment-1309568467
