### ISSUE TITLE
[Installer BUG] harvester installer crashed in "Config network connection" step.

### ISSUE THREAD

**Issue by ezware** [harvester/harvester#3113]
**Describe the bug**
harvester installer crashed after enter hostname and press enter or down arrow key.

Error message:
2022/11/07 03:28:16 invalid dimensions
panic: invalid dimensions

goroutine 1 [running]:
log.Panicln({0xc00029ff60?, 0x0?, 0x0?})
        /usr/local/go/src/log/log.go:399 +0x65
main.main()
        /go/src/github.com/harvester/harvester-installer/main.go:11 +0x46

**To Reproduce**

1. Create a new Harvester cluster
2. step to "Config network connection"
3. press ENTER key or DOWN ARROW key
4. crashed

Test command
rancher:/home/rancher # TTY=/dev/pts/0 TERM=linux DEBUG=true harvester-installer

**Expected behavior**
continue to install

**Support bundle**

**Environment**
 - Harvester ISO version:  https://releases.rancher.com/harvester/v1.1.0/harvester-v1.1.0-amd64.iso
 - Underlying Infrastructure (): Virtualbox VM in Windows 10 host.

rancher:/home/rancher # cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 60
model name      : Intel(R) Core(TM) i5-4570 CPU @ 3.20GHz
stepping        : 3
microcode       : 0xffffffff
cpu MHz         : 3192.606
cache size      : 6144 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 13
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx rdtscp lm constant_tsc rep_good nopl xtopology nonstop_tsc cpuid tsc_known_freq pni pclmulqdq ssse3 cx16 pcid sse4_1 sse4_2 movbe popcnt aes rdrand hypervisor lahf_lm abm invpcid_single pti fsgsbase bmi1 bmi2 invpcid md_clear flush_l1d arch_capabilities
bugs            : cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf mds swapgs itlb_multihit srbds
bogomips        : 6385.21
clflush size    : 64
cache_alignment : 64
address sizes   : 39 bits physical, 48 bits virtual
power management:

rancher:/home/rancher # free -h
              total        used        free      shared  buff/cache   available
Mem:          3.8Gi       350Mi       3.4Gi        28Mi       308Mi       3.5Gi
Swap:            0B          0B          0B
 
**Additional context**

**Comment by FrankYang0529** [comment]
Hi @ezware, this is probably not directly related to your question, but may you try to enable [Nested Virtualization](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html) on your VirtualBox? I can't find `vmx` in your flags.

**Comment by ezware** [comment]
> Hi @ezware, this is probably not directly related to your question, but may you try to enable [Nested Virtualization](https://docs.oracle.com/en/virtualization/virtualbox/6.0/admin/nested-virt.html) on your VirtualBox? I can't find `vmx` in your flags.

hi, @FrankYang0529 
thanks for your reply
I've tried the virtualbox nested virtualization option, and it does't work, also have no vmx;
but in linux kvm, i got vmx and the installer works well.

**Comment by vjz224** [comment]
I am getting the same on baremetal fresh install.
I can type in a hostname, but tabbing down to network config doesn't work (stays on hostname). Enter causes a crash. The message is too fast to read, but I assume it's the same as above.
HW = Beelink GTR5 GR9 (5900HX)
Nics chips are RTL8125BG / RTL81538

**Comment by vjz224** [comment]
> 

FYI, it is not happening with the v1.1.1-rc1 install. The install screens are different (hostname and network config are separate) so I'm guessing this is already known and in the pipeline.
I'll hold tight for the next stable release.

**Comment by futuretea** [comment]
close in favor of https://github.com/harvester/harvester/issues/3113#issuecomment-1310945276
