### ISSUE TITLE
[FEATURE] Terraform Input Device Support

### ISSUE THREAD

**Issue by justin0mcateer** [harvester/harvester#3119]
**Is your feature request related to a problem? Please describe.**
The VNC console (with Windows at least) is very problematic without the 'USB Tablet' input option specified (under Advanced). So far as I can determine, this flag cannot currently be enabled in the VM definition using the latest version of the Harvester and the Harvester Terraform provider.

**Describe the solution you'd like**
Ideally, all of the options which can be specified in the UI (at least) should be specifiable from the Terraform resource definition. This item (USB Tablet interface) in particular is very important in our use case, because the Windows UI seems to be unusable from the Console without it.

**Describe alternatives you've considered**
The only alternative that we can see is manually enabling the option in the Harvester web UI after the VM is created. This requires a restart of the VM, which is less than ideal.

**Additional context**
I have done some initial research on what would be required to add this capability into the Harvester Terraform provider. Unfortunately, it appears that the required schema is not currently exposed by the 'Builder.VM' struct in Harvester. 
[https://github.com/harvester/harvester/blob/9c3f8a635e371674dd9b2a9ff0c9b4bbafa07afe/pkg/builder/vm.go#L63]

Therefore, it appears the feature enhancement will require improvements to _both_ Harvester and the Harvester Terraform provider. On the plus side, this capabilty appears to be cleanly/simply exposed by the KubeVirt API on which the Harvester Builder API depends.
[https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go#L512]

We are willing to help when possible with this, given some guidance, help with testing/validation, etc. However, our team has very limited Go experience.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://user-images.githubusercontent.com/5169694/218440278-e0d2ccc7-9e55-497d-8acd-1da617a501da.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **master-0f10441a-head**
* **ui-source** Option: **Auto**
* Harvester Terraform Provider Version: **master** or **>0.6.1**

### Verify Steps:
1. Install Harvester with any nodes
2. Setup Harvester Terraform Provider[^1]
3. Apply a VM with **usb inputs** (example snippet as below)
4. Login to dashboard, navigate to Virtual Machines page
5. The VM should be created and **Enable Usb Tablet** should be checked


```terraform
resource "harvester_image" "ubuntu20" {
  name      = "ubuntu20"
  namespace = "harvester-public"

  display_name = "ubuntu-20.04-server-cloudimg-amd64.img"
  source_type  = "download"
  url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}

resource "harvester_virtualmachine" "ubuntu20" {
  name                 = "ubuntu20"
  namespace            = "default"
  restart_after_update = true

  description = "test ubuntu20 raw image"
  tags = {
    ssh-user = "ubuntu"
  }

  cpu    = 2
  memory = "2Gi"

  efi         = true
  secure_boot = true

  run_strategy    = "RerunOnFailure"
  hostname        = "ubuntu20"
  reserved_memory = "100Mi"
  machine_type    = "q35"

  network_interface {
    name           = "nic-1"
    wait_for_lease = true
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = harvester_image.ubuntu20.id
    auto_delete = true
  }

  disk {
    name        = "emptydisk"
    type        = "disk"
    size        = "20Gi"
    bus         = "virtio"
    auto_delete = true
  }

  input {
   name         = "tablet"
   type         = "tablet"
   bus          = "usb"
}

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      password: 123456
      chpasswd:
        expire: false
      ssh_pwauth: true
      package_update: true
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent
      EOF
    network_data = ""
  }
}
```


[^1]: https://github.com/harvester/terraform-provider-harvester/wiki/Use-the-prebuilt-docker-image-for-testing
