### ISSUE TITLE
[VM traffic is not working for additional hypervisor, which added after cluster network creation]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3122]
**Describe the bug**

We have created the Harvester cluster with 6 nodes and added cluster network and network config. It's working fine for all 6 nodes, which is added before creating cluster network.

Later we added some nodes in the cluster, which also part of same cluster network but VM network/traffic is not working for these hosts.

We used select all nodes, when we create cluster network.

**To Reproduce**
Create Harvester cluster with some nodes, add cluster network and check VM traffic. Later add more nodes in same cluster network and see VM traffic.

**Expected behavior**
We need to have traffic for all hosts, when we add nodes in cluster.

**Environment**
 - Harvester ISO version: 1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell C6420

**Comment by ibrokethecloud** [comment]
are you please able to provide us a support bundle?

**Comment by midhunthampi** [comment]
We can't share support bundle in open community.

**Comment by ibrokethecloud** [comment]
dm'd you users slack

**Comment by midhunthampi** [comment]
We could able to figure out the issue. IT was issue with firewall side. Closingit
