### ISSUE TITLE
[BUG] DAS - Partitions lost

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#3128]
**Describe the bug**
yesterday out of no where, i noticed a number of volumes were degraded in Longhorn. after digging into it, i realized that the 10 disks in my JBOD enclosure were all missing. I put the server into maint. and rebooted it. System came back up with the drives missing (check with lsblk). i shut down again, reconnected the cables going from the server into the enclosure, and spun the server back up. now the drives show up, the partitions are gone.

**To Reproduce**
maybe disconnect jbod enclosure and reboot the node. then shut down the node again and reconnect the enclosure, and power it back up.

**Expected behavior**
drives should come back online after jbod enclosure is reconnected

**Support bundle**
Sent to harvester-support-bundle@suse.com

**Environment**
v1.0.3
Dell Poeredge R620 (3 nodes)
Dell MD1210 DAS JBOD w/ 10 disks
LSI HBA controllers

Pics attached. if i use fdisk, it shows and ext signature.
![image](https://user-images.githubusercontent.com/60982735/200930369-31411fa4-f78d-45f4-9895-76d39b1d2d67.png)

**Comment by Vicente-Cheng** [comment]
hi @albertkohl-monotek, 

Did you set up the auto provision?
https://docs.harvesterhci.io/v1.0/settings/#auto-disk-provision-paths-experimental

And did you try to mount any one of the missing disks to a temporary folder manually?

thanks!

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng the auto-disk-provision-paths is not set, the disks were added, and being used by the cluster a couple weeks ago, and were in good working order until the jbod enclosure lost connectivity. it sounds like if i try to set auto-provisioning now, it wold destory what data is on the disk.

as for if i'm tried mounting the disks. the just show up as a device, no partition data, however if i open the disk with fdisk /dev/sd_ command, it warns that it sees an ext4 signature. seems like something wrecked the partitions, and i'm not sure of how to get it back without messing up the data on the drives.

i'm not too concerned with the data considering i could just nuke, remount, and resilver the volumes, but i feel like this could be a catastrophic failure for someone else in a similar position, so it'd be worth documenting.

**Comment by albertkohl-monotek** [comment]
as a side note, i've used testdisk on ubuntu before to recover a deleted partition. not sure how to get that onto rancher, but maybe that would be an option to recover the partition? any other suggestions?

**Comment by Vicente-Cheng** [comment]
hi @albertkohl-monotek, 
For auto-provisioned disks, NDM(node-disk-manager) should not `mkfs` again for the disks that are provisioned by NDM.

For your case, I see the picture that you attached.  Somehow metadata would be broken. Could you also check your kernel log at the disk unplug time?
I thought that we do not create any partitions when we provision the disk to LH so the `lsblk` looks like correct with no partition info.
The weird thing is why your metadata is broken.

Maybe you could also try to use e2fsck to check the disks? 

thanks!

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng i tried: 
rancher@harvester-01:~> sudo mke2fs -n /dev/sdn
mke2fs 1.43.8 (1-Jan-2018)
/dev/sdn contains a ext4 file system
        created on Thu Oct 20 00:31:25 2022
Proceed anyway? (y,N) y
Creating filesystem with 244190646 4k blocks and 61054976 inodes
Filesystem UUID: 264c4e67-016b-4050-b5a2-484c94915610
Superblock backups stored on blocks:
        32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208,
        4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968,
        102400000, 214990848

it had some errors saying inodes could be narrower, i yes-ed through those, then i started with free blocks count wrong errors, 
seemed like those errors went on forever. 

i also tried:
rancher@harvester-01:~> sudo e2fsck -pf -b 32768 /dev/sdn
/dev/sdn: Padding at end of inode bitmap is not set. FIXED.
/dev/sdn: 108/61054976 files (13.0% non-contiguous), 167674168/244190646 blocks

but it shows no partition still after completing. just /dev/sdn

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng i tried: rancher@harvester-01:~> sudo mke2fs -n /dev/sdn mke2fs 1.43.8 (1-Jan-2018) /dev/sdn contains a ext4 file system created on Thu Oct 20 00:31:25 2022 Proceed anyway? (y,N) y Creating filesystem with 244190646 4k blocks and 61054976 inodes Filesystem UUID: 264c4e67-016b-4050-b5a2-484c94915610 Superblock backups stored on blocks: 32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 102400000, 214990848
> 
> it had some errors saying inodes could be narrower, i yes-ed through those, then i started with free blocks count wrong errors, seemed like those errors went on forever.
> 
> i also tried: rancher@harvester-01:~> sudo e2fsck -pf -b 32768 /dev/sdn /dev/sdn: Padding at end of inode bitmap is not set. FIXED. /dev/sdn: 108/61054976 files (13.0% non-contiguous), 167674168/244190646 blocks
> 
> but it shows no partition still after completing. just /dev/sdn

Hi @albertkohl-monotek, 
Thanks for your quick update. 
For the usage of Longhorn on Harvester, we **do not** create any partitions.
We use the whole disk (yes, do `mkfs.ext4 /dev/sdx`).

So I thought that `lsblk` output looks like correct without any partition.
From your information, the metadata of ext4 has some problems (as the above you mention).
After e2fsck, could you try to mount it to the temporary folder for checking the content of this disk?
thanks for your help!!

**Comment by albertkohl-monotek** [comment]
oh, that makes sense. seeing all of the partitions on my other nodes made me think you did, but it looks like those are mounts for the vms.

 if i mount to a temp folder it does show data, how do i get harverster to mount the disk properly? 
 
 rancher@harvester-01:/tmp/sdm> mkdir /tmp/sdm
rancher@harvester-01:/tmp/sdm> sudo mount /dev/sdm /tmp/sdm
rancher@harvester-01:/tmp/sdm> ls -l /tmp/sdm
total 28
drw-r--r-- 6 root root  4096 Nov  3 05:19 backing-images
-rw-r--r-- 1 root root    51 Oct 20 00:31 longhorn-disk.cfg
drwx------ 2 root root 16384 Oct 20 00:31 lost+found
drwxr-xr-x 7 root root  4096 Nov  3 04:25 replicas

**Comment by Vicente-Cheng** [comment]
hi @albertkohl-monotek,

The `node-disk-manager` would handle the mount operation.
In your case, looks like the `/dev/sdm` is OK after e2fsck.
So just trigger node-disk-manager to remount it. (you could delete this pod and it should respwan)

For example,
```
harvester-node-0:~ # kubectl get pods -l app.kubernetes.io/name=harvester-node-disk-manager -n harvester-system
NAME                                READY   STATUS    RESTARTS   AGE
harvester-node-disk-manager-l2xxz   1/1     Running   0          31m
harvester-node-disk-manager-q7hcv   1/1     Running   0          19h
harvester-node-disk-manager-wh6nf   1/1     Running   0          19h
```
In your single node case, it would be only one harvester-node-disk-manager pod.
And try to kill it. And it should respawn like following
```
harvester-node-0:~ # kubectl delete pods harvester-node-disk-manager-l2xxz -n harvester-system
pod "harvester-node-disk-manager-l2xxz" deleted
harvester-node-0:~ # kubectl get pods -l app.kubernetes.io/name=harvester-node-disk-manager -n harvester-system
NAME                                READY   STATUS    RESTARTS   AGE
harvester-node-disk-manager-m9cb6   1/1     Running   0          9s
harvester-node-disk-manager-q7hcv   1/1     Running   0          19h
harvester-node-disk-manager-wh6nf   1/1     Running   0          19h
```
Then you could check your extra mount point again.
Thanks!

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng just ran through the steps mentioned, no luck. i was able to find the pod mentioned running on that node, i deleted it, it spun back up right away, but if i go into the server and refresh the disks, it's still showing 0/0 GiBs, and Unprovisioned. 

here's a screenshot of the disk list in the harvesterui
![image](https://user-images.githubusercontent.com/60982735/202099106-fe62f487-8f4b-4975-8f3e-bd1b39ed19c2.png)

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng just ran through the steps mentioned, no luck. i was able to find the pod mentioned running on that node, i deleted it, it spun back up right away, but if i go into the server and refresh the disks, it's still showing 0/0 GiBs, and Unprovisioned.
> 
> here's a screenshot of the disk list in the harvesterui ![image](https://user-images.githubusercontent.com/60982735/202099106-fe62f487-8f4b-4975-8f3e-bd1b39ed19c2.png)

Hi @albertkohl-monotek,
Could you get the log from `harvester-node-disk-manager` pod and attached it here?

Looks like the mount operation still fails.
Thanks!

**Comment by albertkohl-monotek** [comment]
not much...

>:~$ k logs harvester-node-disk-manager-4dzf9 -n harvester-system
`time="2022-11-16T06:03:08Z" level=info msg="Node Disk Manager v0.4.5 (120f93d) is starting"
time="2022-11-16T06:03:08Z" level=info msg="Starting node disk manager controller"
time="2022-11-16T06:03:08Z" level=info msg="register exclude filters"
time="2022-11-16T06:03:08Z" level=info msg="register auto provision filters"
time="2022-11-16T06:03:09Z" level=info msg="Starting harvesterhci.io/v1beta1, Kind=BlockDevice controller"
time="2022-11-16T06:03:09Z" level=info msg="Start monitoring udev processed events"
time="2022-11-16T06:03:09Z" level=info msg="Starting longhorn.io/v1beta1, Kind=Node controller"`

**Comment by Vicente-Cheng** [comment]
Hi @albertkohl-monotek, 
could you try to set up the NDM debug flag by the following command and re-run it to collect log again?
```
kubectl patch ds -n harvester-system harvester-node-disk-manager --type=json -p'[{"op":"replace", "path":"/spec/template/spec/containers/0/command", "value": ["node-disk-manager", "--debug"]}]'
```
Thanks!

**Comment by albertkohl-monotek** [comment]
log attached. Thanks!
[log.txt](https://github.com/harvester/harvester/files/10034334/log.txt)

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng any thoughts? still high-and-dry with these disks not spinning up in harvester. this seems like it could be a catastrophic issue for someone w/ a single-node cluster.

**Comment by Vicente-Cheng** [comment]
hi @albertkohl-monotek, 
I am trying to figure out why NDM does not work on your environment.
Could you help to get your block devices information? by the following command

```
kubectl get blockdevices -A -o yaml > blockdevices.txt
```
Thanks!

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng output attched. note the only Node with this issue is Harvester-01
[blockdevices.txt](https://github.com/harvester/harvester/files/10059286/blockdevices.txt)

**Comment by Vicente-Cheng** [comment]
Hi @albertkohl-monotek, 
Sorry for the late update, I just tested with serval cases for you.

For now, it is hard to recover the devices that temporarily drop when the system is running.
That is caused by two components, the scanning mechanism of NDM and the rebuild mechanism of Longhorn.

When your devices temporarily drop, NDM would remove this from the `blockdevices` until these devices are coming back.
But even though the devices are coming back, some status tag is not correct. That would be caused NDM not to do automount because NDM thought these devices are new and did not belong to the system.

Sure, you could manually mount it back to the system in the correct folder. But some data is not recognized by Longhorn. That means that still need to rebuild.

If your environment is more than two nodes (which means we have another replica), maybe you could try to re-add these disks then they could rebuild.

Thanks!
vicente.

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng thanks for the info. it's more so i wanted to understand that if this happens, and i dont have replicas for some reason, how i can force the mount to get the data back. so from the sounds of it, i basically just would force mount the folders and grab data if needed. but if the data is not critical, nuke the drives, re-add them and let everything replicate back sounds like the normal way of dealing with this.

**Comment by albertkohl-monotek** [comment]
@Vicente-Cheng i tried to remove the sdl drive, but when i edit disk, and remove it, it shows back up.
i've also already ran fdisk, wiped the drive, and reformatted it to ext4, but it wont let me remove the old one, and add back the new one. any advice?

**Comment by Vicente-Cheng** [comment]
Hi @albertkohl-monotek
Just open an issue for your case. #3218
I thought that should be auto-mount back. (For the data validation, the longhorn side would care about it).

For your latest questions, maybe you could try to remove the disk from the longhorn UI. I thought that can not remove from the harvester UI now.

When this disk is removed from the longhorn side, you could try to remove from the harvester side again and add it back.
Thanks!

**Comment by albertkohl-monotek** [comment]
Thanks @Vicente-Cheng i was able to remove it in longhorn, that caused it to disappear from Harvester UI and then i could add it back and force-format.

appreciate the help! :)
