### ISSUE TITLE
[FEATURE] Add volume encryption support for Harvester

### ISSUE THREAD

**Issue by nikolaishields** [harvester/harvester#3129]
**Is your feature request related to a problem? Please describe.**
 Presently volumes provisioned within harverster via the longhorn provisioner do not support the creation of encrypted volumes. It would be beneficial to security conscious users to have the ability to enable volume encryption at the storage class level. 

**Describe the solution you'd like**

By adding `volumeMode: block encryption` support to the harvester pvc request users could freely create both encrypted or non-encrypted volumes.

**Describe alternatives you've considered**

**Additional context**

https://longhorn.io/docs/1.4.0/advanced-resources/security/volume-encryption/

**Comment by Yu-Jack** [comment]
HEP: https://github.com/harvester/harvester/pull/6270
Backend: https://github.com/harvester/harvester/pull/6348

**Comment by lanfon72** [comment]
Verified this feature has been applied but with some minor problem:

1. There is not a way to verify VM image is encrypted or not. (or should we verify it?)
2. The way to verify the passphrase is not work, the pvc located in `/dev/longhorn` will only appear when it is attached to a running VM, but we can't open, if we stop the VM, the file will be removed. (as the snapshot)
![image](https://github.com/user-attachments/assets/9f37f11f-71e8-4a2f-8c5f-bc1297a10c38)

Both are not affect to the implementation, but we would need update HEP/Document to clarify it. 

move back to ready for testing.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-rc1**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.8.2** (VCluster)[^2]

### Verify Steps
#### Prerequisite
1. Install Harvester with any nodes
3. Create an image `img1` as the base image.
4. Create a secret `en-1` with data keys (in namespace `default`)
    - CRYPTO_KEY_CIPHER: aes-xts-plain64
    - CRYPTO_KEY_HASH: sha512
    - CRYPTO_KEY_PROVIDER: secret
    - CRYPTO_KEY_SIZE: 512
    - CRYPTO_KEY_VALUE: the encryption passphrase
    - CRYPTO_PBKDF: argon2i
5. Create a storage class `sc-en1` with volume encryption enabled by using secret `en-1`

#### Case 1 : image creation
1. Create encrypt image `en-img1` from `img1`, use storage class `en-1`
2. Image should created successfully
3. Create decrypt image `de-en-img1` from `en-img1`, use storage class `harvester-longhorn`
4. Image should created successfully

#### Case 2 : volume creation
1. Create data volume  `en-v1` with storage class `sc-en1`
2. Volume should be created successfully
3. Volume should be encrypted. [^1]
4. Create volume `en-v-img1` from VM image `en-img1`
6. Volume should be created successfully
7. Volume should be encrypted. [^1]
8. Create volume `de-en-v-img1` from VM image `de-en-img1`
9. Volume should be created successfully
10. Volume should not be encrypted. [^1]

#### Case 3 : VM creation
1. Create VM `en-vm1` with image `en-img1`
2. VM should created and started successfully
3. The volume created for the VM should be encrypted. [^1]
4. Create VM `vm1` with image `de-en-img1`
5. VM should created and started successfully
6. The volume created for the VM should not be encrypted.[^1]

#### Case 4: attach volumes (**Based on : Case 2**)
1. Create VM `vm1` with image `img1`
2. VM should created and started successfully
3. Attach volume `en-v1`, `en-v-img1` and `de-en-v-img1`
4. Volumes should be attached successfully
5. Migrate VM to other node
6. VM should be migrated successfully

#### Case 5: Verify volume encrypted with the passphrase  (** Based on Case 4**)
1. Login to the node which volume (`en-v1`, `en-v-img1` and `de-en-v-img1`) attached[^1]
2. execute `cryptsetup luksOpen <volumePath> <CRYPTO_KEY_VALUE>` to check the encryption


#### Case 6: Multi users
1. Import Harvester into Rancher
2. Access Harvester via Rancher
3. Create Project `proj1`
4. Create user `test1` and add as member or cluster and project `proj1`
5. Login to Rancher as user `test1` then access Harvester
6. Create namespace `ns1`
7. Create image `img1` (in namespace `ns1`)
8. Create encrypted image `en-img1` from image `img1` and select storage class `sc-en1` (in namespace `ns1`)
9. Encrypted image `en-img1` should be created successfully


[^1]: To verify the volume is encrypted or not, enable `Enable extension developer features` in preferences, then access the link aside the volume to check volume details; in `Attached Node & Endpoint:`, login to the node and execute `cryptsetup luksDump <volumePath>` to check the details as the HEP described.
[^2]: enable as https://github.com/harvester/harvester/issues/2679#issuecomment-1669828538 described.

**Comment by Yu-Jack** [comment]
Hi @lanfon72 

> There is not a way to verify VM image is encrypted or not. (or should we verify it?)

After vm starts, it only shows a volume in `/dev/longhorn` (If you only have a vm without extra volumes). It's enough to use `cryptsetup luksDump` to check it's encrypted. If you'd like to check the decrypted volume, you could check `/dev/mapper`. I'll add `/dev/mapper` part to HEP.

> The way to verify the passphrase is not work, the pvc located in /dev/longhorn will only appear when it is attached to a running VM, but we can't open, if we stop the VM, the file will be removed. (as the snapshot)

 It already proved that your passphrase is correct when showing `which is in use (already mapped or mounted)`. If your passphrase is wrong, it shows `No key available with this passphrase.`.

**Comment by lanfon72** [comment]
> Hi @lanfon72
> 
> > There is not a way to verify VM image is encrypted or not. (or should we verify it?)
> 
> After vm starts, it only shows a volume in `/dev/longhorn` (If you only have a vm without extra volumes). It's enough to use `cryptsetup luksDump` to check it's encrypted. If you'd like to check the decrypted volume, you could check `/dev/mapper`. I'll add `/dev/mapper` part to HEP.
> 

I mean that the VM image we just created in Image pages; when we create a VM from a image, we will create a volume from it first. (even select a image directly)

So my question is, as the page showing that the VM image is encrypted (from a no-encrypted image), but we didn't explain how can we identify it is encrypted and correctly encrypted.

For example in https://github.com/harvester/harvester/issues/6493#issuecomment-2400758163, we can still create a storage class without any encrypt keys(or input wrong value), then use it to encrypt the image, and the UI will shows that the image is encrypted, but actually not.

> > The way to verify the passphrase is not work, the pvc located in /dev/longhorn will only appear when it is attached to a running VM, but we can't open, if we stop the VM, the file will be removed. (as the snapshot)
> 
> It already proved that your passphrase is correct when showing `which is in use (already mapped or mounted)`. If your passphrase is wrong, it shows `No key available with this passphrase.`.

**Comment by Yu-Jack** [comment]
> I mean that the VM image we just created in Image pages; when we create a VM from a image, we will create a volume from it first. (even select a image directly)
> 
> So my question is, as the page showing that the VM image is encrypted (from a no-encrypted image), but we didn't explain how can we identify it is encrypted and correctly encrypted.
>
> For example in https://github.com/harvester/harvester/issues/6493#issuecomment-2400758163, we can still create a storage class without any encrypt keys(or input wrong value), then use it to encrypt the image, and the UI will shows that the image is encrypted, but actually not.

I got your point. This is result that I try to create a encrypted image with invalid secret. About the locker icon, [these codes](https://github.com/harvester/dashboard/blob/c2f1a47e3810f2a61dde9fa02284c047cbaa317c/pkg/harvester/models/harvesterhci.io.virtualmachineimage.js#L192-L197) are how we check. This UI part won't be changed, and I've opened a https://github.com/harvester/harvester/pull/6735 for validating that the secret should be valid. Thanks.

![image](https://github.com/user-attachments/assets/eaba3b7f-7035-42cc-b761-e751a06ddba2)

**Comment by lanfon72** [comment]
close as HEP/Document has been updated.
