### ISSUE TITLE
[Enhancement] Restricts user access to ports other than the load balancer service port through the VIP

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3132]
**Describe the bug**

When using the load balancer feature via CPI for a downstream cluster running within Harvester - it seems that RKE2 of the Harvester cluster also listens on :6443 on that load balancer VIP (instead of just the VIP we specified during Harvester installation).
It's a potential security problem. Refer to https://github.com/kube-vip/kube-vip/issues/479 for more details.

**To Reproduce**
Steps to reproduce the behaviour:
1. Set up a Harvester and a guest cluster with the Harvester cloud provider.
2. Deploy an Nginx and the related load balancer services.
3. We can not only access the Nginx but also port 6443 by VIP.

**Expected behavior**

It's not allowed for users to access ports other than the load balancer service port through the VIP.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.0.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by Martin-Weiss** [comment]
6443 does NOT go to the downstream cluster in this case. I goes to the Harvester RKE2..

We need a way to specify a single load balancer VIP for the downstream cluster where :9345/:6443 go to the „masters“ of the downstream cluster and :80/:443 to the „workers“ in the downstream cluster. 
And via that VIP only these four ports are reachable not not connected to anything else in the Harvester environment..

**Comment by yaocw2020** [comment]
https://github.com/kube-vip/kube-vip/pull/560

**Comment by guangbochen** [comment]
Moved this to Harvester v1.2.1 as we have missed the upstream May CF date, the target releases of this feature in RKE2 and RKE1 are in the June release(Rancher KDM release will need to be checked later).

**Comment by yaocw2020** [comment]
Test plan:
Case 1:
- Set up a Harvester and a guest cluster with the Harvester cloud provider.
- Deploy an Nginx and the related load balancer services with service port 8080.
- We can only access the load balancer service port.

Case2:
Port access restriction is ignored for VIP(a special load balancer IP). You use the VIP to access port 6443 or any other available ports.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2-f4968e49-head` (06/30) with Rancher `v2.7.5-rc6`. Close this issue.

### Result
Verified we can restrict user access only the load balancer specified port on single and multiple cluster scenarios as following result 

#### Case 1: Multi cluster load balancer VIP restriction
* We can only access the load balancer port in multi cluster RKE2 guest cluster (ipam mode: DHCP)
![image](https://github.com/harvester/harvester/assets/29251855/78b81c6f-ed95-4a81-8f2f-697d1ae8170e)

* We can only access the load balancer port in multi cluster RKE2 guest cluster (ipam mode: Pool)
![image](https://github.com/harvester/harvester/assets/29251855/3091b3c1-41cc-4187-aa2d-9478243db6ed)

#### Case 2: Single cluster load balancer VIP restriction

* We can only access the load balancer port on Harvester (ipam mode: Pool)
![image](https://github.com/harvester/harvester/assets/29251855/a2bf633c-7ee8-492d-97fd-0fbcb5e22de8)

* We can only access the load balancer port on Harvester (ipam mode: DHCP)
![image](https://github.com/harvester/harvester/assets/29251855/aceedff2-6fe1-4ef7-9125-ae852817673a)

#### Case 3: port restriction on Harvester management VIP
* We can access Harvester VIP on port 6443
![image](https://github.com/harvester/harvester/assets/29251855/525bbbbc-5e56-4bfc-88da-370523f92a3c)

### Test Information
* Test Environment: 3 nodes harvester on provo bare machine
* Harvester version: `v1.2-f4968e49-head` (06/30) 
* Rancher version:  `v2.7.5-rc6`
* cloud provider version: `0.2.2`

### Verify Steps
#### Multiple cluster
1. Import Harvester to Rancher and create cloud credential 
2. Provision a RKE2 guest cluster 
3. Update cloud provider to latest 0.2.2, refer to the steps in https://github.com/harvester/harvester/issues/1762#issuecomment-1611073439
4. Create a nginx deployment
5. Access Harvester in Rancher virtualization management 
6. Create an IP pool, set the network, project, namespace and guest cluster to the correct value 
7. Create a load balancer service on RKE2 guest cluster, select Pool ipam mode 
8. Check can only curl tot he load balancer VIP with port 
9. Check can't ping the load balancer VIP 
10. Create another IP pool with DHCP ipam mode and check step 8, 9

#### Single Cluster
1. Create a VM with nginx service on Harvester 
2. Set label to the VM (app: nginx)
3. Create an IP pool 
4. Create a load balancer with DHCP mode
5. Check can only curl tot he load balancer VIP with port 
6. Check can't ping the load balancer VIP 
7. Create a load balancer with Pool mode and check step 5, 6

**Comment by LucasSaintarbor** [comment]
Hi @yaocw2020 @TachunLin, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [ ] New documentation/KB
- [ ] Updated documentation/KB
- [ ] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!
