### ISSUE TITLE
[BUG] When upgrading with bonded NICs uplinks stop showing up in UI and management interface disappears

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3139]
**Describe the bug**

When you run an upgrade with bonded NICs the network section of the UI stops showing things as it should.
- You can't add a network config to the existing cluster network.
- You don't see any uplinks available in the dropdown for network configs
- The existing cluster network shows as unavailable
- The network does still work though on the VM after upgrade
 
**To Reproduce**
I tested this with two configurations. The support bundles are for after the upgrade. I ran the upgrades using the walkthrough for [airgapped upgrades](https://docs.harvesterhci.io/v1.0/upgrade/automatic/#prepare-an-air-gapped-upgrade). After install of `v1.0.3` I created a VLAN network before upgrade and assigned a VM to it to test with.

## First Config

- Single node libvirt setup
   - 12 cores
   - 24GB RAM
   - SATA SSD
- bonded NIC setup during ISO install for management network
   - I setup the VLAN interface to use `harvester-mgmt` on VLAN 1
[bonded nic on management interface with VLAN on management.zip](https://github.com/harvester/harvester/files/9976600/bonded.nic.on.management.interface.with.VLAN.on.management.zip)

   
## Second config

- Single node libvirt setup
   - 12 cores
   - 24GB RAM
   - SATA SSD
- Two bonded NICs setup via harvester config during ISO install
[harvester.config.txt](https://github.com/harvester/harvester/files/9976640/harvester.config.txt)
   - First bonded NIC is the bonded management interface
   - Second bonded NIC is for the VLAN interface and is `harvester-vlan`
   - I setup the VLAN interface to use the second bonded nic `harvester-vlan`
[dual bonded nics with vlan on harvester-vlan bonded interface.zip](https://github.com/harvester/harvester/files/9976599/dual.bonded.nics.with.vlan.on.harvester-vlan.bonded.interface.zip)

**Expected behavior**

**Support bundle**

[dual bonded nics with vlan on harvester-vlan bonded interface.zip](https://github.com/harvester/harvester/files/9976599/dual.bonded.nics.with.vlan.on.harvester-vlan.bonded.interface.zip)
[bonded nic on management interface with VLAN on management.zip](https://github.com/harvester/harvester/files/9976600/bonded.nic.on.management.interface.with.VLAN.on.management.zip)

**Environment**
 - Harvester ISO version: master-47a3af23-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node virtualized environment. Specified in repro steps
 
 

**Additional context**
This was found while testing #3045 .

I saw that when I was done running these upgrades that the cluster network was created, but no network was. The VLAN network was created and up. It also still worked with VMs from before the upgrade. However none of the NICs are shown as available, including the management  network that should have been unused in the Second Config. In the VLAN networks if you try to create another one the cluster network shows as unavailable. 

So both of the environments will come up, but then the network configuration options seem to become unusable. I have more screenshots of the setups before and after the upgrade if needed

![Screenshot_20221109_174456](https://user-images.githubusercontent.com/83787952/200981543-6421e8d4-26f4-4d42-9790-65ca61e9e591.png)
![Screenshot_20221109_174128](https://user-images.githubusercontent.com/83787952/200981546-5bdd5f3a-dee7-4f49-8045-fd45e98cd960.png)
![Screenshot_20221109_174114](https://user-images.githubusercontent.com/83787952/200981548-85b03330-de42-43b5-b99f-cdd2ae6a2deb.png)
![Screenshot_20221109_174109](https://user-images.githubusercontent.com/83787952/200981549-7df424d1-15ad-40ca-a4da-4829082e4d53.png)

**Comment by yaocw2020** [comment]
The support bundles look like for the v1.0.3. @noahgildersleeve

**Comment by bk201** [comment]
@noahgildersleeve I checked both support bundles, and looks like the cluster was upgraded to a master ISO build in Sep. 
```
harvester: 47a3af23
harvesterChart: 0.0.0-master-47a3af23
os: Harvester master
kubernetes: v1.22.12+rke2r1
rancher: v2.6.4-harvester3
monitoringChart: 100.1.0+up19.0.3
kubevirt: 0.54.0
rancherDependencies:
  fleet:
    chart: 100.0.3+up0.3.9
    app: 0.3.9
  fleet-crd:
    chart: 100.0.3+up0.3.9
    app: 0.3.9
  rancher-webhook:
    chart: 1.0.4+up0.2.5
    app: 0.2.5
```
Could you check if the ISO is correct? And maybe we can double verify again with 1.1.1-rc2.

**Comment by noahgildersleeve** [comment]
I'll rerun the test with v1.1.1-rc2.

**Comment by noahgildersleeve** [comment]
I retested this with the first and second config. It seems to be working from a functionality standpoint. However the VLAN network that is there from the upgrade won't show the cluster network in the VM Network list in the UI. That seems like a smaller issue.
![Screenshot_20221122_144630](https://user-images.githubusercontent.com/83787952/203437254-786bc440-ff72-4c99-b3ff-27e11313929d.png)
![Screenshot_20221122_144624](https://user-images.githubusercontent.com/83787952/203437255-24842d8f-2295-4323-a592-27d1c77cd8bf.png)

**Comment by noahgildersleeve** [comment]
Closing due to functionality working and created ticket for UI issue at #3198 3198
