### ISSUE TITLE
Cant power up cluster 

### ISSUE THREAD

**Issue by KyleSponz** [harvester/harvester#3140]
What is the procedure to power up a cluster after a hard down? We had a power outage and the genset failed so the cluster went offline. 

It was stuck in this screen and the other nodes showed not ready 
![IMG_1342](https://user-images.githubusercontent.com/2746903/201207628-595f4f96-e082-40e5-aaef-17f574ec6c0b.jpg)

**Comment by RegisWeduLabs** [comment]
If you can ping the hosts - I would suggest you go on the hosts via ssh and chech for the logs...  Power outage are hard on etcd, and sometime it might fail to sync the etcds node - so I would 1st look there.

**Comment by KyleSponz** [comment]
I am going to simulate it virtually I had to run a config update so I had to reflash the cluster were not in prod yet anyway.

**Comment by ibrokethecloud** [comment]
like @RegisHubelia  mentioned, i would check etcd logs
