### ISSUE TITLE
[BUG] Unable to pcie passthrough 2x 1080ti on 1 VM

### ISSUE THREAD

**Issue by orange8882** [harvester/harvester#3146]
**Describe the bug**

Two gpus of the same type (such as 2x 1080ti) are on a node. When the PCIE passthrough is selected, the same Device ID  will be assigned to the two gpus. 

When editing the virtual machine configuration and selecting the PCIE passthrough device, you can only select one gpu with the same name, not multiple gpus

**To Reproduce**
1. Advanced-->PCI Device-->filter"NVIDIA"
2.Virtual Machines-->Edit Config -->PCI Devices -->Available PCI Devices
![20221114151112](https://user-images.githubusercontent.com/88642721/201599582-b27faec5-bd53-4933-9297-170f54f3c42c.jpg)

**Comment by futuretea** [comment]
related docs:
https://kubevirt.io/user-guide/virtual_machines/host-devices/#nvme-pci-passthrough
```
Currently, the KubeVirt device plugin doesn't allow the user to select a specific device by specifying the address. Therefore, if multiple NVMe devices with the same vendor and product id exist in the cluster, they could be randomly assigned to a VM. If the devices are not on the same node, then the nodeSelector mitigates the issue
```

**Comment by orange8882** [comment]
> related docs: https://kubevirt.io/user-guide/virtual_machines/host-devices/#nvme-pci-passthrough
> 
> ```
> Currently, the KubeVirt device plugin doesn't allow the user to select a specific device by specifying the address. Therefore, if multiple NVMe devices with the same vendor and product id exist in the cluster, they could be randomly assigned to a VM. If the devices are not on the same node, then the nodeSelector mitigates the issue
> ```

Now, I can add 2 1080ti in a VM by editing the VM's yaml.


![20221117161717](https://user-images.githubusercontent.com/88642721/202393474-d1073559-fd22-44b8-8f8e-250e91c2fa0e.png)

But it seems that we can't add a second GPU through this Harvester UI .
We can't select the second GPU in this page ' PCI Device'.

![220](https://user-images.githubusercontent.com/88642721/202394194-b5c0fd9c-bec8-4f25-9d65-e7b0a24b6d81.png)

**Comment by futuretea** [comment]
> Now, I can add 2 1080ti in a VM by editing the VM's yaml.

Can you see 2 1080Ti inside the VM (not yaml)?

**Comment by orange8882** [comment]
yes ,it' works
![gpu](https://user-images.githubusercontent.com/88642721/202403318-0aba3c47-0899-422d-8676-9d15c3552938.png)

**Comment by tlehman** [comment]
This will be solved by the DevicePlugin I am working on in this [HEP](https://github.com/tlehman/harvester/blob/hep-dp/enhancements/20221028-pci-deviceplugin.md).

**Comment by tlehman** [comment]
This also requires UI changes to enable the user to request multiple devices with the `resourceName`

**Comment by tlehman** [comment]
This is currently handled by [PR 35](https://github.com/harvester/pcidevices/pull/35). Multiple instances of the same device will get counted, and then they can be requested by the VM.

**Comment by noahgildersleeve** [comment]
Tested in `v1.1-510a0256-head`. When I enabled the pcidevices addon there was no list of devices. I think this might be a UI issue, but I can't test because the external ui-source is broken #3618 .

![Screenshot_20230308_194117](https://user-images.githubusercontent.com/83787952/223911026-7d3ebe78-4a7b-4573-8fe7-5b63230651e4.png)
![Screenshot_20230308_194250](https://user-images.githubusercontent.com/83787952/223911105-0999ac39-a02b-4f2a-b156-965f707321ff.png)
[supportbundle_75442969-7c14-4617-8ea7-a13fb7d17276_2023-03-09T03-42-45Z.zip](https://github.com/harvester/harvester/files/10927454/supportbundle_75442969-7c14-4617-8ea7-a13fb7d17276_2023-03-09T03-42-45Z.zip)

**Comment by DaiYuzeng** [comment]
Hi @noahgildersleeve ! May I know the `Get` requests of `/v1/harvester/devices.harvesterhci.io.pcidevices` and `/v1/harvester/devices.harvesterhci.io.pcideviceclaims` respond successfully?

Hi @tlehman ! Could you help us to confirm the environment of @noahgildersleeve is ready for enabling PCI Passthrough?

**Comment by tlehman** [comment]
@DaiYuzeng Sure, 

pcidevices:

```js
fetch("https://192.168.1.185/v1/harvester/devices.harvesterhci.io.pcidevices", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    // sec headers scrubbed for security
  },
  "referrer": "https://192.168.1.185/dashboard/harvester/c/local/devices.harvesterhci.io.pcidevice",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by tlehman** [comment]
pcideviceclaims

```js
fetch("https://192.168.1.185/v1/harvester/devices.harvesterhci.io.pcideviceclaims", {
  "headers": {
    "accept": "application/json",
    "accept-language": "en-US,en;q=0.9",
    // sec headers scrubbed for security
  },
  "referrer": "https://192.168.1.185/dashboard/harvester/c/local/devices.harvesterhci.io.pcidevice",
  "referrerPolicy": "strict-origin-when-cross-origin",
  "body": null,
  "method": "GET",
  "mode": "cors",
  "credentials": "include"
});
```

**Comment by tlehman** [comment]
I got those by opening the UI in Chrome, then going to the Network tab and selecting "Copy as fetch"

<img width="799" alt="image" src="https://user-images.githubusercontent.com/261552/224394500-f18a937f-9de7-48f0-ba03-9555dac937a1.png">

**Comment by DaiYuzeng** [comment]
Thank you @tlehman ! May I know the response body of these two requests? I can't access this env... I would like to confirm that there are some PCI devices on this env. Thanks!

**Comment by noahgildersleeve** [comment]
Tested with `v1.1-e1905897-head` on single node physical server with NICS.

## Verification Steps
1. Enable PCI devices
2. Enable passthrough on two NICs with same vendor ID
![Greenshot 2023-03-14 18 36 57](https://user-images.githubusercontent.com/83787952/225182205-2a0fc67d-69be-4de2-82c7-0eda1e51025f.png)
3. Add both NICs to new VM
![Greenshot 2023-03-14 18 31 29](https://user-images.githubusercontent.com/83787952/225182240-f6ca234c-36ce-4136-a377-65d784740a99.png)
4. Check that NICs are both showing up in VM
![Greenshot 2023-03-14 18 35 59](https://user-images.githubusercontent.com/83787952/225182257-3b1aabf8-08b5-4356-b41a-114644a43681.png)
