### ISSUE TITLE
[BUG] Upgrade stuck at upgrading node stage, node1 display Waiting Reboot with Kubelet stopped posting status

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3147]
**Describe the bug**

Upgrade from v1.0.3 to v1.1.1-rc1 with Harvester node machine on IPv6 DHCP enabled network
* When node 1 enter upgrading node stage, it stuck at `Waiting Reboot` and can't proceed.
* Node 1 display `Kubelet stopped posting node status` 
![image](https://user-images.githubusercontent.com/29251855/201803266-d328ae51-5ffc-47b0-9b79-8056e8484126.png)

* Check the pods status in K9s, `harvester-promote-n2-103-111` got **Error** and `harvester-webhook` got **pending**
![image](https://user-images.githubusercontent.com/29251855/201806588-5ac71a67-a504-4af5-bcd3-45a26d05ba83.png)

* Found error on `CrashLoopBackOff` on `helm-install-rke2-canal` and `helm-install-rke2-coredns` and `helm-install-rke2-multus`
![image](https://user-images.githubusercontent.com/29251855/201806614-558e8712-9f0d-4e77-b858-93ce79ba30a2.png)

**To Reproduce**
1. Create a new network in KVM manger (refer to https://github.com/harvester/harvester-installer/pull/363#issuecomment-1299388805.), which have ipv6 DHCP enabled. 
2. Create a VM and use the ipv6 network. 
3. ISO install v1.0.3
4. Select DHCP node ip and DHCP vip during the installation
5. Offline upgrade to master release
6. Check host IP on Host page 
7. Check the ip allocated to node `kubectl get nodes -o json | jq '.items[].status.addresses'` 

**Expected behavior**

Should complete the Harvester cluster upgrade from v1.0.3 to v1.1.1-rc1 with Harvester node machine on IPv6 DHCP enabled network

**Support bundle**

[supportbundle_5db36550-eae2-454f-97e9-11e67b3e8ca8_2022-11-15T02-00-15Z.zip](https://github.com/harvester/harvester/files/10008472/supportbundle_5db36550-eae2-454f-97e9-11e67b3e8ca8_2022-11-15T02-00-15Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): local kvm machine

**Comment by bk201** [comment]
etcd fail to join cluster:
```
Nov 15 05:28:59 n1-103-111 rke2[9323]: time="2022-11-15T05:28:59Z" level=info msg="Failed to test data store connection: this server is a not a member of the etcd cluster. Found [n1-103-111-f6117101=https://192.168.101.184:2380/ n2-103-111-980037af=https://192.168.101.249:2380/ n3-103-111-5bb8aa33=https://192.168.101.158:2380/], expect: n1-103-111-f6117101=https://192.168.101.185:2380/"
```

The IP change after rebooting, might be DHCP lease issue:
```
n1-103-111:~ # ip a show dev mgmt-br
4: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:de:04:4c brd ff:ff:ff:ff:ff:ff
    inet 192.168.101.185/24 brd 192.168.101.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
```

**Comment by TachunLin** [comment]
As a workaround. 

After setting the fixed IP mapping in customized virtual network
`<host mac="52:54:00:de:04:4c" name="nic1" ip="192.168.101.184"/>` 

Then restart network by running `virsh net-destroy workload` and `virsh net-destroy workload`

And restart all node VM by running `virsh destroy <node-name>` and `virsh start <node-name>`

We can continue to finish the upgrade process to `v1.1.1-rc1` 
![image](https://user-images.githubusercontent.com/29251855/201938106-64a0855d-4301-4cc1-b8c6-1f3ca8db1213.png)

**Comment by w13915984028** [comment]
@TachunLin 

A question: the NODE ip and VIP need to be stable in the life cycle of a cluster, were those NODEs(virt-manager VMs)  not using fixed IP in the past ?

**Comment by TachunLin** [comment]
This issue was found while setting the nodes on customized IPv6 enabled network for the regression testing. 
Where I use ISO install with DHCP node IP and VIP. 
Typically the IP did not changing during the upgrade. 
This time looks like a special case, not sure whether it somehow been affected by IPv6.

**Comment by TachunLin** [comment]
For the network environment setup. 
We could set longer DHCP lease time in virtual network or provide fixed IP to mac address to avoid the IP changing after rebooting. Close this issue.
