### ISSUE TITLE
[Enhancement] Bump Harvester components base image to SLE BCI 15.4

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3149]
**Is your feature request related to a problem? Please describe.**
Bump Harvester components base image to SLE BCI 15.4 for better maintenance and security update.

**Describe the solution you'd like**
Harvester image list that we might want to update:
@masteryyh 
- [x] https://github.com/harvester/harvester
  - [x] rancher/harvester
  - [x] rancher/harvester-upgrade
  - [x] rancher/harvester-webhook
  - [x] rancher/harvester-cluster-repo
- [x] https://github.com/harvester/harvester-installer
- [x] https://github.com/harvester/network-controller-harvester
  - [x] rancher/harvester-network-controller
  - [x] rancher/harvester-network-helper

@starbops 
- [x] https://github.com/harvester/node-disk-manager
  - [x] rancher/harvester-node-disk-manager
- [x] https://github.com/harvester/load-balancer-harvester
  - [x] rancher/harvester-load-balancer
- [x] https://github.com/harvester/cloud-provider-harvester
- [x] https://github.com/harvester/node-manager
- [x] https://github.com/harvester/terraform-provider-harvester
- [x] https://github.com/harvester/docker-machine-driver-harvester
- [x] https://github.com/harvester/harvester-csi-driver https://github.com/harvester/harvester/issues/1995
- [x] [rancher/support-bundle-kit](https://github.com/rancher/support-bundle-kit)

**Comment by bk201** [comment]
Close because we bumped images to bci 15.4.
