### ISSUE TITLE
[BUG] Wrong dependency versions in ISO image

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#315]
**Describe the bug**
With the v0.1.0-rc1 release we notice several incorrect dependency version issues:

- [x] harvester/harvester-network-controller images with `master-head` tag are packaged.
- [x] UI is out of date.
- [x] console dashboard is showing `version: dev`

**Environment:**
 - Harvester ISO version: v0.1.0-rc1

**Comment by guangbochen** [comment]
validation steps:
1.  get the  image with tagged version `rancher/harvester-network-controller:v0.1.1`
```➜  harvester-network-controller git:(upstream) ks describe pod -n harvester-system harvester-network-controller-wqrmz  | grep image
  Normal  Pulled     55m        kubelet, harvester-z5kmr  Container image "rancher/harvester-network-controller:v0.1.1" already present on machine
```
2. UI is using a tagged version `v0.1.0-rc3`
3. 
![image](https://user-images.githubusercontent.com/4569037/102360769-650bc000-3fed-11eb-8471-77e8069d3416.png)
