### ISSUE TITLE
[FEATURE] bump fleet-agent to v0.5.0

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3150]
**Is your feature request related to a problem? Please describe.**

https://github.com/rancher/fleet/releases/tag/v0.5.0

It solves https://github.com/rancher/fleet/issues/760 and https://github.com/harvester/harvester/issues/1893

**Describe the solution you'd like**

the current fleet-agent version is v0.4.0, bump the version to v0.5.0

**Describe alternatives you've considered**

**Additional context**
Also need to verify: https://github.com/harvester/harvester/issues/1893

**Comment by w13915984028** [comment]
How to validate:
1. create a 2-node cluster
2. power off the 2rd node, you will hit `fleet-agent is extremely busy`
![image](https://user-images.githubusercontent.com/31133476/201924057-eb5a0b59-d0af-45dd-93f4-def6faa1d1e5.png)

3. edit fleet-agent pod, set image version as v0.5.0, the issue is gone
![image](https://user-images.githubusercontent.com/31133476/201924193-7c6f5b0c-ee7a-4904-b78d-0b3ebf9fefa9.png)

**Comment by w13915984028** [comment]
`fleet-agent` is integrated in `Rancher`, we need to wait for the new release of `Rancher` which includes it, then bump `Rancher`.

**Comment by guangbochen** [comment]
depends on https://github.com/rancher/fleet/issues/1174

**Comment by guangbochen** [comment]
This is included in the Harvester `v1.1.2-rc1` by https://github.com/harvester/harvester-installer/pull/411. Please help to validate it again, thanks.

**Comment by w13915984028** [comment]
Verified in master-head version Harvester (built 2023.02.20), the images are bumped.

```
rancher:      image: rancher/rancher:v2.6.10
fleet-agent:  image: rancher/fleet-agent:v0.5.1
```

**Comment by w13915984028** [comment]
With similar steps as issue described,

Power off one NODE
![image](https://user-images.githubusercontent.com/31133476/220085110-1b03ff3c-a230-459a-8e68-16283761ec81.png)

The `bundledeployment` has ongoing deployment
![image](https://user-images.githubusercontent.com/31133476/220085184-aa6b0f09-f851-4b9a-8387-09f4abb2be72.png)

fleet-agent is not too busy
![image](https://user-images.githubusercontent.com/31133476/220085230-5a9ebd15-d612-4120-af42-ed1f86e96d97.png)
