### ISSUE TITLE
[BUG] new API `NetworkAttachmentDefinition` is inconsistent to `v1.0.3`

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3151]
### The problem
When request create network with payload as below, in `v1.0.3`, server will return `422` and `Invalid`, but after `v1.1.0`, it will be silently changed to create **UntaggedNetwork**.
```python
{'apiVersion': 'k8s.cni.cncf.io/v1',
 'kind': 'NetworkAttachmentDefinition',
 'metadata': {'labels': {'network.harvesterhci.io/type': 'L2VlanNetwork'},
              'name': '11-15-21h33m52s710643',
              'namespace': 'default'},
 'spec': {'config': '{"cniVersion": "0.3.1", "name": "11-15-21h33m52s710643", '
                    '"type": "bridge", "bridge": "mgmt-br", "promiscMode": '
                    'true, "vlan": 0, "ipam": {}}'}}
```

### The solution
In the UI, we will NOT input `vlan` field for **UntaggedNetwork**, so we should still keep the `vlan` id check (for _L2VlanNetwork_) to compatible with old version.

### Additional Context
Discovered by e2e's API testing.

**Comment by yaocw2020** [comment]
A null value is equivalent to 0 for the vlan field. We don't need to specify the label `'network.harvesterhci.io/type': 'L2VlanNetwork'` because the webhook mutator will distinguish and tag them automatically.

**Comment by guangbochen** [comment]
@lanfon72 can u please help to check if removing the network label will address the above issue on the e2e API testing? thanks.

**Comment by lanfon72** [comment]
> @lanfon72 can u please help to check if removing the network label will address the above issue on the e2e API testing? thanks.

@guangbochen yes it will still be changed to `UntaggedNetwork`.
![image](https://user-images.githubusercontent.com/5169694/202103854-f522c3ce-921b-48ff-8a1c-d1ac52115331.png)

there was a typo to use network**s** in labels, so I don't think it is cause by labels.[^1]

[^1]: https://github.com/harvester/tests/blob/d4dbacbdb15b780c3c7e7d46e8e43c8bc75f4943/harvester_e2e_tests/templates/basic_network.json.j2#L16

**Comment by guangbochen** [comment]
seems the webhook will automatically convert VLAN 0 to untaggedVLAN, per the 802.1q specification, the all-zero and all-one tag (i.e. VLAN 0 and VLAN 4095) are not used, so we may need to check the VLAN id range as well in the https://github.com/harvester/network-controller-harvester/blob/master/pkg/webhook/nad/mutator.go#L50-L55, cc @yaocw2020

**Comment by yaocw2020** [comment]
> seems the webhook will automatically convert VLAN 0 to untaggedVLAN, per the 802.1q specification, the all-zero and all-one tag (i.e. VLAN 0 and VLAN 4095) are not used, so we may need to check the VLAN id range as well in the https://github.com/harvester/network-controller-harvester/blob/master/pkg/webhook/nad/mutator.go#L50-L55, cc @yaocw2020

The webhook judges the value 0 to confirm whether the vlan field is empty. What the webhook cares about is the empty value, not the number 0.  Assume that vlan field is a string type and then the empty value will be blank, the webhook would not allow the number 0. I hope I explain it clearly. 
It would be better to limit the number 0 for the VLAN type NAD.

**Comment by guangbochen** [comment]
@lanfon72 let's move this to v1.1.2 and prefer to update the testing case since this is now expected in the backend.

**Comment by lanfon72** [comment]
@guangbochen we are just skip the test case after `v1.0.3`, when this issue be resolved, we will update the test case.

**Comment by guangbochen** [comment]
Close this one and have checked with @lanfon72 that we will update the testing cases instead, thanks.
