### ISSUE TITLE
[Question] configuring a VLAN at the management interface in the ISO installer UI

### ISSUE THREAD

**Issue by mikemendis** [harvester/harvester#3154]
I am trying to use the new VLAN install feature, I enter my VLAN ID but I always get a error requesting a IP through DHCP.   If I do the same with Esxi and specify my VLAN ID, i get a IP.   Is there a way I can debug this further
<img width="1094" alt="Screen Shot 2022-11-15 at 3 45 36 PM" src="https://user-images.githubusercontent.com/13985055/202021963-62440f5f-3af6-47ce-9afd-58e9b9c01b3a.png">
?

**Comment by futuretea** [comment]
@mikemendis Hi, can you help to collect troubleshooting information and what is the version of harvester iso?
Refer to https://docs.harvesterhci.io/v1.1/troubleshooting/installation#collecting-troubleshooting-information

**Comment by mikemendis** [comment]
I am using v1.1.0.   I was able to get around by specifying a static ip address and going to the next screen, I than logged on to node and manually setup the networking in the ifcfg-enXXX files.  I restarted the network and got a IP from dhcp.   I switched back to the UI and continued normally.

**Comment by tjjh89017** [comment]
@mikemendis Could you provide your switch config to us to debug?
If you modify the `ifcfg-enXXX` file and it worked, I think you use native vlan inyour switch side.
Probably, you don't need to specific vlan for installation
