### ISSUE TITLE
[Question] Run "zypper install" to result in "filesystem is mounted as read-only".

### ISSUE THREAD

**Issue by n-guitar** [harvester/harvester#3160]
# Situation
I would like to set up a NIC (wifi) and would like to install the "ConnMan" Tool with "zypper command" on Harvester Node.
However, when I run "zypper install", I get the following message and cannot install it.
```sh
The target filesystem is mounted as read-only. Please make sure the target filesystem is writeable
```

## What I want to do
I want to set up wifi to Harvester Node.
I am thinking of creating a NW for VLANs in addition to the Manegiment NW.
(Edit "fstab" and reboot, but the setting is back.)

## Confirmed
root device is read-only
![image](https://user-images.githubusercontent.com/27879320/202160473-4cd17542-fb7f-4c10-8894-93cbf5e28d64.png)
![image](https://user-images.githubusercontent.com/27879320/202160575-5891dafe-64bf-4350-8f81-3e14ae03f2bd.png)

## Additional
- version
![image](https://user-images.githubusercontent.com/27879320/202160769-76025be2-65af-4bc7-b008-973b995e16d7.png)

- harvester is working
![image](https://user-images.githubusercontent.com/27879320/202161295-68db55c6-b7d9-4b1b-adc0-c0756ef5e93b.png)

**Comment by futuretea** [comment]
Refer to: https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only

**Comment by n-guitar** [comment]
I see that it was already documented !
Thank you!
