### ISSUE TITLE
[Question] Deleting a vm object does not delete longhorn replica

### ISSUE THREAD

**Issue by zp4rand0miz31** [harvester/harvester#3161]
Hi, 

Context: using harvester 1.0.3 in production, on a 5 server (Dell baremetal) install.

Problem: when deleting VM via "kubectl delete vm -n namespace vmname", we observe that longhorn replicas are not deleted. 
We also observe this behavior when we delete the namespaces, and, as a consequence, the virtual machines of this one. Replicas are in the "stopped" state, and do allocate resources, that creates a production incident on our side, because the cluster can't schedule any vm at some time. 

Is this expected ? What is the right way to ensure trashed replicas are destroyed ? Do we need some finalizers on the VM spec ?

Some more information to help: 

- we use VM images with replicasCount = 1 (because we observe slowliness otherwise)
- we use ephemeral storage

**Comment by w13915984028** [comment]
Pleaes take a look of the Harvester WEBUI, from there, when you delete an VM, it will ask you weather delete the `volume` as well, `yes` by default.

When you do it via `kubectl delete vm -n namespace vmname`, you need to do this manually, e.g. `kubectl delete volume ...`

![image](https://user-images.githubusercontent.com/31133476/202199647-8bf34d02-aad0-4dab-beb6-9659fa65f7f3.png)

**Comment by zp4rand0miz31** [comment]
Hi, thanks. We'll update our scripts logic. 
We can close.

**Comment by futuretea** [comment]
If it is not deleted through UI, you need to manually delete it through `kubectl -n <namespace> delete pvc <pvcname>`

**Comment by zp4rand0miz31** [comment]
We use ephemeral storage, I would expect to have no leftover after a VM is destroyed, to be honest.

**Comment by futuretea** [comment]
Close in favor of  https://github.com/harvester/harvester/issues/3161#issuecomment-1317081187
