### ISSUE TITLE
[BUG] Filter the network created by storage-network in the node drive   (RKE1)

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3163]
**Describe the bug**

storage-network will automatically create a network, and we should filter it.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/319c7ae0-8e91-4103-8b2c-4f94acd33a81)
**To Reproduce**
1. go to setting page, enable storage-network
2. Importing harveste into rancher
3. create harvester node driver  (RKE1)

**Expected behavior**

we should filter the network created by storage-network in the node drive.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-714ee3fb-head` (01/09) with Rancher `v2.7-head` (8062f1e). Close this issue.

### Result
* The network created by storage-network did not show on the RKE1 node template form
![image](https://user-images.githubusercontent.com/29251855/211513701-2b09c764-12ab-455e-b693-3c625d001a47.png)

* Also did not show on the RKE2 cluster provisioning page
![image](https://user-images.githubusercontent.com/29251855/211513830-0193eca9-6c25-48ed-a6f8-1a460831e1be.png)

### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-714ee3fb-head` (01/09)
* Rancher version: `v2.7-head` (8062f1e)

### Verify Steps
1. Create vlan 1 network on Harvester cluster 
2. Enable storage network and set it to vlan1 CIDR
3. Import Harvester in Rancher
4. Create cloud credential
5. Check the RKE1 node template page
6. Check the RKE2 cluster provisioning page
