### ISSUE TITLE
[BUG] Cluster field is not really *required* when creating RKE2/K3s Harvester

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3165]
### Describe the bug
When Creating Harvseter RKE2/K3s cluster in Rancher's Cluster Management, the field **Cluster** is marked as `Required` but it could still be empty.

https://user-images.githubusercontent.com/5169694/202425725-2beced69-5505-4cae-8cd3-2b8f918d5978.mp4

### To Reproduce
1. Install Harvester with any nodes
2. Install Rancher `v2.6.9`
3. Import Harvester in _Virtualization Management_
4. Create Harvester RKE2/K3s Cluster in _Cluster Management_
5. In _Create Harvester_, select **Imported Harvester**, keep **Cluster\*** field empty then click **Continue**

### Expected behavior
Error message should pop-up to ask user to select Cluster.

## Environment:
 - Harvester ISO version: **v1.1.1-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**
 - Rancher Version: **v2.6.9** (via docker image)

**Comment by lanfon72** [comment]
@n313893254 will this not fix on `v2.6-head`?

**Comment by n313893254** [comment]
@lanfon72 Thank you! The v2.6-head PR is https://github.com/rancher/dashboard/pull/7785 and can test it with https://releases.rancher.com/dashboard/release-2.6/index.html

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/210339674-fb6e909c-1a52-4b74-820d-fec72a801cd5.png)


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **master-37ff3072-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6-head**(Docker Image: **d6b73f4a7976**) and **v2.7-head**(Docker Image: **964d1d1fd7a0**)

### Verify Steps:
- Follow **Steps to Reproduce** in https://github.com/harvester/harvester/issues/3165#issue-1453129704
- For `v2.6-head`, update _Global Settings_' **ui-dashboard-index** to `https://releases.rancher.com/dashboard/release-2.6/index.html`
