### ISSUE TITLE
[BUG] The NICs should remain up after deleting the VLAN config

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3166]
**Describe the bug**

After deleting the VLAN config, the NICs of the uplink will be down. If users want to use those NICs as the uplink again, they have to set them up manually, which is very user-unfriendly. 

**To Reproduce**
1.  Create a new clusternetwork and add a config
2. Delete the config

**Expected behavior**

The NICs should keep up after deleting the VLAN config

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by yaocw2020** [comment]
Test plan:
- Create a new clusternetwork and add a config
- Delete the config
- Create a new clusternetwork again and you'll find that you can choose NICs used before.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-b0d883ce-head` (11/22) . Close this issue.

### Result
* When we delete a network config and create a new config on the same cluster network, all NICs are UP and can be selected in Uplink page. 

https://user-images.githubusercontent.com/29251855/203341150-673d7b31-4dde-42c9-b5de-e71381ba3dc9.mp4

* Also when we delete a network config and create a new config on different cluster network, all NICs are UP and can still be selected in Uplink page. 

https://user-images.githubusercontent.com/29251855/203341228-a81e3b8d-b150-4b45-aacd-d9baf3d156c2.mp4



### Test Information
* Test Environment: 3 nodes harvester on bare machines
* Harvester version: master-b0d883ce-head

### Verify Steps
1. Prepare bare machines, each have 3 NICs, one for management interface, another two for vlan network
2. Create  a 3 nodes Harvester with latest master-release
3. Plugin cable to all NICs on bare machines
4. Create a cluster network `cnetwork`
5. Create the network config `config1` and set Uplink NICs to `enp179s0f0 (Up)` and `enp179s0f1 (Up)`
  ![image](https://user-images.githubusercontent.com/29251855/203307540-7ca61c21-273b-4bfd-a512-3eda69e2a2c2.png)
  ![image](https://user-images.githubusercontent.com/29251855/203307165-f74c8931-f53a-4b6d-b10e-255e02b174db.png)

6. Delete the network config `config1`
7. Create another network config `config2` and still can set Uplink NICs to `enp179s0f0 (Up)` and `enp179s0f1 (Up)`
  ![image](https://user-images.githubusercontent.com/29251855/203308117-19f200b9-9856-4231-82e2-ff757ab11c22.png)

8. Delete the network config `config2` 
9. Create another network config `config3` and still can set Uplink NICs to `enp179s0f0 (Up)` and `enp179s0f1 (Up)`
10. Create another cluster network `cnetwork2`
11. Delete the network config `config3` 
12. Create another network config `config3` on `cnetwork2` and still can set Uplink NICs to `enp179s0f0 (Up)` and `enp179s0f1 (Up)`
