### ISSUE TITLE
[BUG] upgrade stuck in *Images preloaded* caused by connection reset by peer

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3167]
### Describe the bug
When upgrading Cluster `v1.0.3` to `v1.1.1-rc1`, status showing `Image preloaded` for a long time, check the upgrade infos in the consoel, it shows: `read: connection reset by peer`

![snapshot](https://user-images.githubusercontent.com/5169694/202432511-8301a1ff-190f-4fee-9dfc-925475bf90be.png)

### To Reproduce
1. Install Harvester `v1.0.3` with any nodes
2. Upgrade Harvester to `v1.1.1-rc1`
3. when the upgrade status pending in `Image preloaded`
4. Login to console, and check the upgrade status by executing `kubectl get upgrades -nharvester-system -ojson | jq '.items[] | {name: .metadata.name, conditions: .status.conditions}'`

### Expected behavior
upgrade successfully

## Environment:
 - Harvester ISO version: **v1.0.3** to **v1.1.1-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360G9 3 nodes**

### Additional context
Similar error message when downloading image: https://github.com/harvester/harvester/issues/2535

### Support bundle
[supportbundle_bde2ac18-6ac1-4581-923e-ba41633dbdb6_2022-11-17T10-59-58Z.zip](https://github.com/harvester/harvester/files/10031065/supportbundle_bde2ac18-6ac1-4581-923e-ba41633dbdb6_2022-11-17T10-59-58Z.zip)

**Comment by lanfon72** [comment]
Also happened when Downloading upgrade Image:

![image](https://user-images.githubusercontent.com/5169694/202468489-c70f73b7-7bcf-4361-9818-6a43cee228b1.png)

**Comment by noahgildersleeve** [comment]
When this happened to me I was able to just start the upgrade again and it worked the second time.

**Comment by guangbochen** [comment]
Close as this is duplicate with https://github.com/harvester/harvester/issues/2535.
