### ISSUE TITLE
[Question] Manage a cluster with non uniform host hardware

### ISSUE THREAD

**Issue by ginjiruu** [harvester/harvester#3171]
I have a 5 node cluster made up of various old computers that I have laying around and as such not everything shows up the exact same.

Some network adapters will will show up as enp1s0 and some as enp3s0f0, sometimes the root device is /dev/sda other times it's /dev/nvme0n1 

With that in mind I'm a little confused about how to setup a cluster network under these conditions. In my previous setup using proxmox I would just pre-create a network bond on each device which would provide the standardized naming for a cluster network. Here in harvester though I don't see the menu to do that and so when I go to to the cluster network tab to setup my network I can't since every host has different interface names.

Similarly in proxmox I could manually select the disks I wanted to use for the ceph storage pools but I don't see how to do that via harvester or the built in longhorn webgui. 

I'm sure there are ways to do this in harvester I'm just drawing a blank on what those ways are and where to find the documentation on doing it.

Thank you very much for any assistance with this.

**Comment by futuretea** [comment]
For network part, you can refer to https://docs.harvesterhci.io/v1.1/networking/clusternetwork#custom-cluster-network
For storage part, you can refer to https://docs.harvesterhci.io/v1.1/host/#multi-disk-management
