### ISSUE TITLE
[BUG] After configuring http and https proxy, harvester is not accessible

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3172]
### Describe the bug
after input http/https proxy in the same time, harvester will be inaccessible and will not bring back.

![image](https://user-images.githubusercontent.com/5169694/202597880-61581b9f-887d-470c-8768-6de554b919ea.png)

### To Reproduce
1. Install Harvester in air-gaped environment with any nodes
2. Login to dashboard and navigate to Settings
3. Edit http-proxy to input the **HTTP** proxy into http-proxy and https-proxy field then click **Save**

### Expected behavior
HTTP proxy should works for https one

## Environment:
 - Harvester ISO version: **v1.1.1-rc1**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
When only input the field of http-proxy, cluster will be accessible.

**Comment by futuretea** [comment]
Harvester v1.1.0 single node,  cannnot be reproduced.

Harvester v1.1.1-rc1 single node,  cannnot be reproduced.

Harvester v1.1.1-rc1 three nodes, can be reproduced.

Harvester v1.1.1-rc1 three nodes, when configuring http-proxy, configure no-proxy as the CIDR of node node, this problem does not occur
![image](https://user-images.githubusercontent.com/15064560/203027519-a350082a-6b2d-4f1d-ad0e-cfad7c5672b1.png)

**Comment by futuretea** [comment]
We need a note in https://docs.harvesterhci.io/v1.1/advanced/settings#http-proxy

**Comment by lanfon72** [comment]
close as resolved when CIDR added.
