### ISSUE TITLE
[BUG] Network webhook can not add the clusternetwork label

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3173]
**Describe the bug**

Network webhook can not add the clusternetwork label for the existing network.

**To Reproduce**
1. Create a network
2. Edit the nad to delete the clusternetwork label
3. Delete the network webhook pod. A new pod could not add the clusternetwork label to the nad automatically.

**Expected behavior**

The network webhook should ensure the clusternetwork label for existing nads.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by yaocw2020** [comment]
Test plan:
- Create a network
- Edit the nad to delete the clusternetwork label
- Check the nad again, and you'll find the clusternetwork label resuming.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-b0d883ce-head` (11/22). Close this issue.

### Result
After deleting the clusternetwork label of `vlan1` and `vlan101` 
The clusternetwork label will resume to added back to nad. 

```
  labels:
      network.harvesterhci.io/clusternetwork: mgmt
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "1"

 labels:
      network.harvesterhci.io/clusternetwork: cnetwork
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "101"

```

### Test Information
* Test Environment: 3 nodes harvester on bare machines
* Harvester version: master-b0d883ce-head

### Verify Steps
1. Prepare bare machines, each have 3 NICs, one for management interface, another two for vlan network
2. Create  a 3 nodes Harvester with latest master-release
3. Plugin cable to all NICs on bare machines
4. Create a vlan network `vlan1` 
![image](https://user-images.githubusercontent.com/29251855/203323366-8cf28167-5cff-4844-ae7c-3ef76ad0f430.png)

5. Edit the nad of vlan1
  ```
  kubectl edit net-attach-def -n default vlan1
  ```
 6. Delete the clusternetwork label
  ```
  labels:
      network.harvesterhci.io/clusternetwork: mgmt
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "1"
  ```
 
  ```
  # Please edit the object below. Lines beginning with a '#' will be ignored,
  # and an empty file will abort the edit. If an error occurs while saving this file will be
  # reopened with the relevant failures.
  #
  apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      network.harvesterhci.io/route: '{"mode":"auto","cidr":"192.168.50.0/24","gateway":"192.168.50.1","connectivity":"true"}'
    creationTimestamp: "2022-11-22T13:16:05Z"
    finalizers:
    - wrangler.cattle.io/harvester-network-nad-controller
    - wrangler.cattle.io/harvester-network-manager-nad-controller
    generation: 1
    name: vlan1
    namespace: default
    resourceVersion: "56969"
    uid: b39cf60b-9e19-491e-a58f-151b4e607e3a
  spec:
    config: '{"cniVersion":"0.3.1","name":"vlan1","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":1,"ipam":{}}'
  
  ```
 
7. Check the nad again, and you'll find the clusternetwork label resuming.

  ```
  # Please edit the object below. Lines beginning with a '#' will be ignored,
  # and an empty file will abort the edit. If an error occurs while saving this file will be
  # reopened with the relevant failures.
  #
  apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    annotations:
      network.harvesterhci.io/route: '{"mode":"auto","cidr":"192.168.50.0/24","gateway":"192.168.50.1","connectivity":"true"}'
    creationTimestamp: "2022-11-22T13:16:05Z"
    finalizers:
    - wrangler.cattle.io/harvester-network-nad-controller
    - wrangler.cattle.io/harvester-network-manager-nad-controller
    generation: 1
    labels:
      network.harvesterhci.io/clusternetwork: mgmt
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "1"
    name: vlan1
    namespace: default
    resourceVersion: "61755"
    uid: b39cf60b-9e19-491e-a58f-151b4e607e3a
  spec:
    config: '{"cniVersion":"0.3.1","name":"vlan1","type":"bridge","bridge":"mgmt-br","promiscMode":true,"vlan":1,"ipam":{}}'
  ```

8. Create a cluster network 
9. Create a network config and set Uplink NICs
10. Create another vlan network `vlan101` and use `cnetwork`
11. 2. Edit the nad of vlan101
  ```
  kubectl edit net-attach-def -n default vlan101
  ```
12. Delete the clusternetwork label
  ```
   labels:
      network.harvesterhci.io/clusternetwork: cnetwork
      network.harvesterhci.io/type: L2VlanNetwork
      network.harvesterhci.io/vlan-id: "101"
  ```
13. Check the nad again, and you'll find the clusternetwork label resuming.

**Comment by aleberkn** [comment]
does this fix allow me to create a net-attach-def w/o a CRD?  I want to use holder pods, with privileged host networking to create a bridge and attach it to a NAD but a mutating admission webhook is preventing NAD creation because it requires a Cluster Network CR.   I think I answered this on my own...no it doesn't address initial creation, just ensures recreation..so the mutatiing admission webhook would still require a CRD for the NAD.

**Comment by rrajendran17** [comment]
This issue is about deleting a cluster network label in a NAD and eventually the mutating webhook adds the cluster network label to the NAD.In Harvester, yes you will need a cluster network CRD as we manage linux bridge/bond and its associated network config across the nodes using the cluster network CRD and the NAD needs to be attached to a cluster network.
