### ISSUE TITLE
[FEATURE] When entering harvester in multiple clusters, a loading icon should be displayed when the network is slow

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3174]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher v2.7-head and v2.6-head. Close this issue.

### Result
When internet connection of Rancher is slow and try to access Harvester in Rancher virtualization management page

We can see a loading icon display besides the server name and disappear after we can access the Harvester cluster,
![image](https://user-images.githubusercontent.com/29251855/219324726-b8629843-11c6-4d13-b971-1ebe1ec06da7.png)

### Test Information
- Test Environment: 1 node Harvester on local kvm machine
- Harvester version: master-213d4af7-head (02/14)
- Rancher version: v2.7-head (1dd2af2), v2.6-head (4db94f6)

### Verify Steps
1. Import Harvester in Rancher
2. Open Virtualization Management page
3. Open browser development console (F12) 
4. Switch to network 
5. Set the throttling to `slow 3G` 
![image](https://user-images.githubusercontent.com/29251855/219327703-2229385a-7e68-4ba7-9a90-8a1080243783.png)
6.  Check the loading icon
