### ISSUE TITLE
Add a hover tips for the resource external link

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3178]
**Describe the bug**

We would like to add a hover tips for the resource external link.
![image (6).png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/89efb0a2-af63-4d52-a9f5-cc4784a87aba)
**To Reproduce**
1. Go to preference page and enable DEV mode
2. Go to create a volume.
3. Go to volume detail page.
4. Hover the external link.
5. Tips should be visible.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in v1.1.1-rc2 with UI index set to external. I didn't see any external resource link. This was in Chrome.

![Greenshot 2022-11-21 16 49 59](https://user-images.githubusercontent.com/83787952/203187902-ff79a05c-e2fe-4d51-b4a5-b7372136dd3d.png)
![Greenshot 2022-11-21 16 55 43](https://user-images.githubusercontent.com/83787952/203188315-bd158514-21f7-4496-b0d4-d108e0f5b19d.png)

**Comment by DaiYuzeng** [comment]
Sorry! Steps above are not integral. You should enable DEV mode at preference page beforehand.
![image](https://user-images.githubusercontent.com/15041915/203246216-9664e4ac-a50b-4a4d-b2dc-653ad34082a3.png)
![image](https://user-images.githubusercontent.com/15041915/203246269-5b04cf74-7fb0-4b00-b698-0ccf69cd5e6e.png)

LH external resource link only be visible when DEV mode is enabled.
If the link is consistently hidden, may I know the url of your external UI-index? I would like to confirm.

Thanks! @noahgildersleeve

**Comment by noahgildersleeve** [comment]
Tested in `v1.1.1-rc2` with UI index set to external. Verified that tooltip showed on hover and that link went to Longhorn.
![Greenshot 2022-11-22 09 40 38](https://user-images.githubusercontent.com/83787952/203384176-847fe00e-50cb-4257-9a06-b40421627703.png)
![Greenshot 2022-11-22 09 40 28](https://user-images.githubusercontent.com/83787952/203384180-78faed7b-26ef-4a02-81a1-d8b416a9efea.png)
