### ISSUE TITLE
[Question] I want to build a Homelab with harvester and TinyMiniMicro PCs, anything worth mentioning?

### ISSUE THREAD

**Issue by char-iot** [harvester/harvester#3179]
I'd get couple TinyMiniMicro PCs ( https://www.servethehome.com/introducing-project-tinyminimicro-home-lab-revolution/ ) and install  harvester on them.

How should I go about it? just download iso and install?

Is it possible to remotely shutdown or put these PC nodes to sleep and wake or boot them? Would I need Intel vPro for it?

---edit
currently working with TrueNAS Scale and Proxmoxx. Future looks like Harvester and unraid (for tiered Cached and HDD spin down)

**Comment by futuretea** [comment]
harvester hardware requirements: https://github.com/harvester/harvester#hardware-requirements

> Is it possible to remotely shutdown or put these PC nodes to sleep and wake or boot them?

remotely shutdown: ssh
remotely power on: WOL https://en.wikipedia.org/wiki/Wake-on-LAN

**Comment by char-iot** [comment]
"8 cores" is bit difficult for TinyMiniMicro PCs.

Used WOL on Proxmox, was hoping for something native on harvester
