### ISSUE TITLE
How to add email receiver on Alertmanager Configs  at Harvester

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3180]
Hi Team,

I have added receiver email ID and send relay server details but after adding not able to see any receiver info .

Could you please share the info for how to configure email alerts in harvester .

**Comment by futuretea** [comment]
Harvester alertmanager docs: https://docs.harvesterhci.io/v1.1/monitoring/#alertmanager
CC @w13915984028

**Comment by dseralathan** [comment]
Thanks ,I have the doc already in handy .

After adding email receivers , receiver info is not showing . Can you please provide a sample email configuration.

**Comment by dseralathan** [comment]
Attached the screenshot 
<img width="1312" alt="Screen Shot 2022-11-28 at 12 16 51 PM" src="https://user-images.githubusercontent.com/117767598/204372577-8c0060d0-8603-46b6-b11f-ea91dde9e39d.png">

**Comment by DaiYuzeng** [comment]
> Thanks ,I have the doc already in handy .
> 
> After adding email receivers , receiver info is not showing . Can you please provide a sample email configuration.

Hi @dseralathan ! FYI: Do you remember to input the receiver name on the receiver creation page?

There is a related issue: https://github.com/harvester/harvester/issues/2798

Consequently, I guess you may forget to input the receiver name, could you have a try? Thanks!

**Comment by DaiYuzeng** [comment]
#### Name field on receiver creation page
![image](https://user-images.githubusercontent.com/15041915/204486579-94db976e-86b2-4d1e-8ba4-27a7e770d19c.png)

Please be aware on the field which is encompassed by red line in the screenshot, it's required field.

**Comment by dseralathan** [comment]
Thanks Dai, My bad ,its showing after I add the name for receiver .

![Screen Shot 2022-12-05 at 12 19 01 PM](https://user-images.githubusercontent.com/117767598/205734916-a10259c1-6352-416d-aacd-552b7555ccfa.png)
