### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Ali-Gamal** [harvester/harvester#3187]
How can I configure multiple IP addresses on Harvester nodes (physical hosts)?

My use case, I want to connect all hosts to a dedicated network on the 10G bond for backup/snapshot.

All hosts have only a single IP address from MGM network on another 1G interface

**Comment by futuretea** [comment]
@Ali-Gamal This doc should be helpful: https://docs.harvesterhci.io/v1.1/advanced/storagenetwork
