### ISSUE TITLE
[Question] Installing proprietary drivers

### ISSUE THREAD

**Issue by mircea-pavel-anton** [harvester/harvester#3196]
Is there any way I could perform some setup tasks that are persistent across reboots?

More specifically, I am migrating from a Proxmox setup in which i was using the vGPU unlock script to enable vGPU support on my consumer Nvidia card.
This procedure requires downloading, patching and installing the nvidia driver.

One solution i thought of, is to define the process as a list of commands under `/oem/99...`, but that would most definitely massively slow down the boot times of the system. Is there any way I could set up the drivers once and have them persist?

**Comment by futuretea** [comment]
> Is there any way I could set up the drivers once and have them persist?

Your needs seem to call for a custom iso

**Comment by abonillabeeche** [comment]
@mirceanton are you still trying to achieve this? There are docs in the Harvester site under Operating System that describe some details. Also vGPU is in our Roadmap.

**Comment by mircea-pavel-anton** [comment]
@abonillabeeche  I have dropped the ideea for now, and I was looking into rolling out my own system with kubevirt on top of kubernetes. This is planned for later on in the year, though. If vGPU is in the roadmap and gets to a beta at least by that point, I'll be happy to check it out!
