### ISSUE TITLE
[BUG] Docs link in support gets 404

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3197]
**Describe the bug**

When you click the 

**To Reproduce**
1. Navigate to support on the UI in the bottom left
2. Click Docs link
**Expected behavior**

You should go to the correct page
**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal DL160

**Additional context**
This is pointing at https://docs.harvesterhci.io/latest/ . This doesn't seem to be a valid page.

**Comment by irishgordo** [comment]
On Harvester Version: master-b0d883ce-head - this looks great :+1: :smile:  
Validated the link navigates correctly, has been updated and validated via Vue DevTools extension that the elements have the correct data.
I'll go ahead and close this out :smile: - thanks for the fix @WuJun2016 !

https://user-images.githubusercontent.com/5370752/203634509-c1b8dbd6-2e95-414c-8ffe-c243cb1f5bf1.mp4
