### ISSUE TITLE
Clarify the env names of VM storage service in Harvester

### ISSUE THREAD

**Issue by thxCode** [harvester/harvester#32]
**Improvement:**

The meaning of the env names of VM storage service is not clear enough, it should be compatible with other S3(Object storage) services.

**Reference:**

Clarify the env names of VM storage service, the following is a feasible proposal.

- `MINIO_ACCESS_KEY` -> `VM_STORAGE_ACCESS_KEY`
- `MINIO_SECRET_KEY` -> `VM_STORAGE_SECRET_KEY`
- `MINIO_URL` -> `VM_STORAGE_ENDPOINT`

**TODO:**

- [x] Adjust Harvester.
- [x] Change the envs of installation charts.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/46

**Comment by guangbochen** [comment]
close in favor of #46
