### ISSUE TITLE
user password is clear-text passwords

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#320]
**Describe the bug**
The user password is clear-text passwords

**To Reproduce**
1.  Create a user
2. Edit this created user

![image](https://user-images.githubusercontent.com/24985926/101856328-03d48e80-3ba0-11eb-894a-b6ba5bd22ea6.png)

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/101879938-12856a80-3bcd-11eb-8045-7a8c5ceab5d7.png)
