### ISSUE TITLE
[BUG] restricted admin can't add cluster members in RBAC Harvester menu

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3204]
**Describe the bug**

You get an error when trying to add a cluster member via RBAC in the Harvester UI through Rancher virtualization management
**To Reproduce**
1. Import Harvester into Rancher
2. Add a restricted admin user named rstradmin
3. Add a user named cluster that is a standard user
4. Log out of admin and log in as rstradmin
5. Navigate to virtualization management and open up the Harvester UI
6. Navigate to RBAC
7. Add cluster as a cluster member

**Expected behavior**

They should add with no error
**Support bundle**

[supportbundle_ea1fee70-66c4-48e4-aecd-e4c0104857cf_2022-11-23T22-24-13Z.zip](https://github.com/harvester/harvester/files/10079485/supportbundle_ea1fee70-66c4-48e4-aecd-e4c0104857cf_2022-11-23T22-24-13Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1-rc2
 - Rancher version: v2.7.0 (single docker node install)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node vagrant install with bonded NIC on management interface

**Additional context**
This works fine with admin. I haven't had a chance to see if this is happening on v2.6.9 yet.
![Screenshot_20221123_142014](https://user-images.githubusercontent.com/83787952/203655997-3d9722cf-cf5a-4ae7-aa4c-c3729b152a32.png)

**Comment by guangbochen** [comment]
Probably an upstream issue in the previous version, I have verified that with Harvester `v1.2.0-rc2` and Rancher `v2.7.5-rc5`, a restricted admin can add standard users to the cluster as cluster members correctly. @noahgildersleeve, please help to check it again using the latest version, thanks.
<img width="2553" alt="image" src="https://github.com/harvester/harvester/assets/4569037/2d24abad-9831-4ded-b929-d59e8ebc0900">

**Comment by noahgildersleeve** [comment]
Tested in Harvester `master-20ca0b3e-head` and Rancher `v2.7.5`. Verified that cluster member could be added to RBAC.
![Screenshot_20230630_123142](https://github.com/harvester/harvester/assets/83787952/64586c91-603f-425b-979c-188eb0273b34)
