### ISSUE TITLE
[BUG] No Management Nic can be choosed when install using ISO

### ISSUE THREAD

**Issue by Pilipupu** [harvester/harvester#3207]
**Describe the bug**
I use Parallels Desktop to install Harvester with ISO, but no management nic can be choosed.
![image](https://user-images.githubusercontent.com/40445907/203716634-5cf1a74d-b954-4c0d-8a6e-4bf4e0db91e8.png)

**Environment**
 - Harvester ISO version: harvester-v1.1.0-amd64.iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Parallel Desktop

**Comment by jrlittlefoot64** [comment]
Think you must use TAB here to see the available NIC
