### ISSUE TITLE
[FEATURE] Display CCM events in the load balancer service tabs

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3208]
**Is your feature request related to a problem? Please describe.**

If the CCM calls the load balancer API failed, users can only check the log of the pods, which is very inconvenient. CCM will broadcast an event when errors happen. We can display CCM events in the load balancer service tabs.

**Describe the solution you'd like**

Display CCM events in the load balancer service tabs

**Describe alternatives you've considered**

**Additional context**

**Comment by n313893254** [comment]
Checked that the Rancher latest UI has an event tab on the service detail page. @yaocw2020 Do you need further improvement?

![image](https://user-images.githubusercontent.com/18737885/207801447-ff929212-4f82-4367-b9b8-d7d2ae14fefc.png)

**Comment by yaocw2020** [comment]
> Checked that the Rancher latest UI has an event tab on the service detail page. @yaocw2020 Do you need further improvement?
> 
> ![image](https://user-images.githubusercontent.com/18737885/207801447-ff929212-4f82-4367-b9b8-d7d2ae14fefc.png)

It's good enough for me.

**Comment by guangbochen** [comment]
@yaocw2020 @n313893254 can we close this one if no further implementation is required?

**Comment by n313893254** [comment]
The upstream PR is 
- https://github.com/rancher/dashboard/pull/7540
- https://github.com/rancher/dashboard/pull/7882

Will be released in Rancher v2.7.2 and v2.6.11. cc @yaocw2020

**Comment by yaocw2020** [comment]
It'll be released in rancher v2.7.2.
