### ISSUE TITLE
[BUG] Both name and custom name for the host are displayed

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#321]
**Version**
master 12/11

![image](https://user-images.githubusercontent.com/5697937/101859293-64ff6080-3ba6-11eb-8380-4d0acfc4159e.png)
We are showing both name and custom name. This is confusing.
We should remove the custom name column. If there's a custom name for the host, show it in the name column instead of the generated name.

**Comment by DoNotSayYes** [comment]
Validated, removed the custom name column from the page.
