### ISSUE TITLE
[Doc] Harvester DOC enhancement

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3210]
**Is your feature request related to a problem? Please describe.**

Customer SREs are expecting more details from Harvester DOC.

**Describe the solution you'd like**

Harvester DOC enhancement:
* Dedicated chapter to introduce K8S CSI, PVC, VOLUME, LH basic etc.,  and link to LH doc
* Add LH troubleshooting chapter (to link LH doc)
* List all Harvester used CRDs
* How to collect all upgrade related detailed logs, how to better trouble-shooting
* How to use kubectl to start/stop/create/delete VM, and other frequently used resources
* OS layout, partitions ...
...

**Describe alternatives you've considered**

**Additional context**

**Comment by robv8r** [comment]
Please include Harvester Network Configuration in your documentation enhancement.  Specifically, how to assign externally accessible IP addresses to VMs.

[Edit]

Our company's policy is to use Static IP Addresses.  Without DHCP, provisioning a Rancher Cluster via Harvester has been challenging.

**Comment by w13915984028** [comment]
Documents have been widely and continuously updated, close as finished.

Fell free to open new issues on specific topics.
