### ISSUE TITLE
[FEATURE] qcow2: warn user about insufficient volume size

### ISSUE THREAD

**Issue by tacerus** [harvester/harvester#3212]
**Is your feature request related to a problem? Please describe.**
If an image volume with not enough space is created off an qcow2 image, a resulting VM may not boot with obscure error messages, such as the root partition UUID not being found.

**Describe the solution you'd like**
Harvester could read and store the partition sizes inside the qcow2 image, and warn the user if they are about to create a volume with less disk space than the partitions inside the selected image.

**Describe alternatives you've considered**
Manually track partition sizes inside all qcow2 images uploaded to Harvester, making the user compare against a list before creating their volumes.

**Additional context**
I only tested this with Kiwi+Ignition based SLE Micro images, which grow, but will not shrink, their partition on the first boot, resulting in the error if the grow is attempted on a volume with not enough size.

**Comment by Vicente-Cheng** [comment]
Hi @tacerus, 
Thanks for your suggestions.
Yes, `Harvester` does not introduce any trick to check the minimal size of volume with the guest VM image.

Maybe we could consider that add some label or annotation from the image uploaded user. Then the volume could check with that. What do you think about that?

**Comment by tacerus** [comment]
Hi, thanks for your response! Using labels or annotations sounds like a good idea - that way it's additionally directly visible to the user.

**Comment by markhillgit** [comment]
We are tracking this issue in https://github.com/harvester/harvester/issues/4905. Closing this one as duplicate.
