### ISSUE TITLE
[BUG] After upgrade complete, the harvester-upgrade image exists on VM creation page 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3217]
**Describe the bug**

After completely upgrade from v1.1.0 to v1.1.1 master, (master-0cdb5a5b-head)
Open the create VM page, we can see the `harvester-upgrade-xxx-master-1128` image exists on the image list
![image](https://user-images.githubusercontent.com/29251855/204263768-b25eb9e7-f5bb-4063-8391-9c10376248fc.png)

**To Reproduce**
1. Prepare 4 nodes v1.0.3 Harvester cluster 
2. Prepare some image and create some VMs
3. Upgrade to v1.1.1 master head release 
4. Wait upgrade complete and system up 
5. Open VM creation page 
6. Check the images drop down list 

**Expected behavior**

The harvester-upgrade image should not exists in VM creation page after upgrade complete 

**Support bundle**

[supportbundle_aaf2ddcc-54b9-481d-87b1-c7dbf39fd400_2022-11-28T11-35-22Z.zip](https://github.com/harvester/harvester/files/10103252/supportbundle_aaf2ddcc-54b9-481d-87b1-c7dbf39fd400_2022-11-28T11-35-22Z.zip)

**Environmt
 - Harvester ISO version: `master-0cdb5a5b-head` 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes bare machines

**Additional context**

**Comment by lanfon72** [comment]
is this duplicated in #3604 ?

**Comment by WuJun2016** [comment]
@lanfon72  Yes, they are duplicates, maybe you can close the issue.

**Comment by WuJun2016** [comment]
close.   https://github.com/harvester/harvester/issues/3217#issuecomment-1525357710
