### ISSUE TITLE
[FEATURE][BUG] Harvester CPI Error: failed to get node modifiers from cloud provider: failed to find kubelet node IP from cloud provider, requeuing

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3219]
**Describe the bug**
Removed a node object from a downstream RKE2 cluster and re-joined the node with restarting rke2-agent.

Now we see this in the cloud provider logs:

I1128 15:16:08.586900       1 node_controller.go:390] Initializing node node17 with cloud provider
E1128 15:16:08.598477       1 node_controller.go:212] error syncing 'node17': failed to get node modifiers from cloud provider: failed to find kubelet node IP from cloud provider, requeuing

**To Reproduce**
Have a downstream RKE2 cluster on top of Harvester with 3 server and several agents and having harvester CPI/CSI deployed using Rancher
.
On one agent do a 
`rke2-killall.sh`
On a master do a 
`kubectl delete node node17`
And then on the agent do a 
`systemctl start rke2-agent`

Now check the logs of the harvester cloud controler and see the above errors.

**Expected behavior**
Harvester CPI should not have these errors and remove the taint "node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule" from the node.

**Environment**
 - Harvester ISO version: 1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by Martin-Weiss** [comment]
Some more information - our nodes have two IP addresses - one on eth0 and one on eth1 and we have specified node-ip: to the one that should be used a  "internal ip" for the node.

How can we see what exactly is going wrong when we get the above error?

**Comment by Martin-Weiss** [comment]
One more thing - the default gateway is on eth1 where the node-ip is on eth0 - is this a potential problem with the harvester CPI?

**Comment by yaocw2020** [comment]
The error message comes from https://github.com/kubernetes/cloud-provider/blob/f443498b5ec49e0c9e52935e0ff9fbbd37862340/controllers/node/node_controller.go#L492

@Martin-Weiss Could you provide the yaml of nodes?

**Comment by futuretea** [comment]
> Some more information - our nodes have two IP addresses - one on eth0 and one on eth1 and we have specified node-ip: to the one that should be used a "internal ip" for the node.

@Martin-Weiss  Are you assigning multiple ip networks here through `network data` ? 
Currently, node driver cannot add multiple NIC to a guest cluster node. 
Only `network data` is not enough, need node driver support first.

https://github.com/harvester/harvester/issues/2426
https://github.com/harvester/harvester/issues/2733

**Comment by Martin-Weiss** [comment]
Our current way is to add the second NIC (eth1) manually via Harvester UI after the VM has been created. In this case the network_data will be taken also for eth1 as configured.

But - the node-ip we use is pointing to eth0 IP address, anyway.

**Comment by yaocw2020** [comment]
We should add a new feature to support multiple IPs in the Harvester cloud provider.

**Comment by yaocw2020** [comment]
The whole multiple NICs solution is at https://github.com/harvester/harvester/issues/2426

**Comment by lanfon72** [comment]
Hi @Martin-Weiss, I would like to double confirm some details of the environment (to reproduce the bug):
1. Harvester cluster with 3+ nodes
2. RKE2 cluster (4 nodes+) with 2 NIC and both able to access harvester
3. Rejoin RKE2 agent node

Thanks.

**Comment by Martin-Weiss** [comment]
> Hi @Martin-Weiss, I would like to double confirm some details of the environment (to reproduce the bug):
> 
>     1. Harvester cluster with 3+ nodes
> 
>     2. RKE2 cluster (4 nodes+) with 2 NIC and both able to access harvester
> 
>     3. Rejoin RKE2 agent node
> 
> 
> Thanks.

@lanfon72 yes - this is more or less what we have done. Not sure what else you want to know?

**Comment by lanfon72** [comment]
thank you @Martin-Weiss.

Hi @yaocw2020, we don't have any environment to create 2 VLANs and both ports able to interact with RKE2 cluster, does the CPI Error (root cause) is not related to multi NICs? If so, I think we could verify this bug on 1 VLAN environment.

cc @guangbochen, @bk201

**Comment by yaocw2020** [comment]
This issue is part of the multiple NICs solution https://github.com/harvester/harvester/issues/2426. Multiple VLAN environment is not required.

**Comment by Martin-Weiss** [comment]
I think you need a router outside of the environment to route betweent the VLANs - but the root cause might be the difference of node-ip vs. ip for default gateway...

**Comment by lanfon72** [comment]
Move back to implement because the latest rancher `v2.7-head` still unable to create rke2 with 2 NICs.

**Comment by lanfon72** [comment]
remove dependency as we could still use another network data format to spawn RKE2.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **baremetals DL360G9 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6-5d91d1afdd7d88da6c0530080b16a5ad6dae8d17-head** (Docker Image ID: **d645e74d343f**)

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard
3. Create Image for VM creation
4. Create 2 VLANs, at least 1 is able to access Rancher
5. Import Harvester into Rancher
6. Create RKE2 cluster with 2 pools
    - first pool (servers) configured with 3 machines, 2 NICs and `etcd/ControlPlane/Worker`
    - second pool (agents) configured with 3 machines, 2 NICs and `Worker`
    - **Network Data** need to be configured in both pools[^1]
7. Login to one of VMs in second pool, execute `sudo rke2-killall.sh`
8. Login to one of VMs in first pool, execute commands as below:
```bash
sudo -s
export KUBECONFIG=/etc/rancher/rke2/rke2.yaml
/var/lib/rancher/rke2/bin/kubectl get nodes
/var/lib/rancher/rke2/bin/kubectl delete node "THE_AGENT_NODE_NAME_IN_STEP_7"
```
9. Login to the VM in __step 7__, execute `sudo systemctl start rke2-agent`
10. The agent node should join back successfully
11. No Error message displayed in **harvester-cloud-provider** (browsing from __cluster -> explore -> Workload -> Deployments__)


[^1]: https://docs.harvesterhci.io/v1.1/vm/create-vm#cloud-init , **name** in the configuration would be variety in different cloud image.

**Comment by lanfon72** [comment]
Hi @Martin-Weiss, If you still encounter this bug after Rancher **v2.6.11-rc8** or Rancher **2.7.2-rc3**, we might not fix it correctly, please reopen the issue.

Please be awarded that **Network Data** in Rancher need to use the format (with top-level `network` key) as following:
```yaml
network:
  version: 1
  config:
   - type: physical
     name: enp1s0
     subnets:
     - type: dhcp
   - type: physical
     name: enp2s0
     subnets:
     - type: dhcp
```

And in Harvester, both formats (described in our document[^1] and above) are supported, the problem be tracked in #3443 


Thanks

[^1]: https://docs.harvesterhci.io/v1.1/vm/create-vm#cloud-init
