### ISSUE TITLE
[BUG] Backup and Restore UI and network option not showing properly in Rancher integrated Harvester UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3220]
**Describe the bug**

The backup and restore menu option and the network option (it looks like a camelCase class and doesn't match the capitalization so it's probably the same issue) isn't showing correctly.
**To Reproduce**
1. Import Harvester into Rancher
2. Open up Harvester UI from Rancher virtualization management

**Expected behavior**

It should show the same as it does in the Harvester UI
**Support bundle**

[supportbundle_81fc1123-53e0-4f03-9f4b-305735bd9969_2022-11-29T00-42-08Z.zip](https://github.com/harvester/harvester/files/10108729/supportbundle_81fc1123-53e0-4f03-9f4b-305735bd9969_2022-11-29T00-42-08Z.zip)

**Environment**

 - Harvester ISO version: v1.1.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Harvester vagrant environment 12c 24g
 - Rancher version: v2.7.0 (single node docker instance)

**Additional context**
This is showing properly in the Harvester UI. I tested this and it's showing incorrectly in both admin and restricted admin users.

![Screenshot_20221128_163634](https://user-images.githubusercontent.com/83787952/204410953-af6f8d51-8499-4f8d-a044-07cf4c0c39ec.png)
![Screenshot_20221128_163606](https://user-images.githubusercontent.com/83787952/204410954-5f3286fb-58a1-4c83-9589-9a49e13483f9.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-37ff3072-head` (12/1) with Rancher `v2.7.0`. Close this issue.

### Result
Use admin` and restricted admin to access Harvester through Rancher virtualization management page

The `Network` and the `Backup & Snapshot` item showing correctly as the same with in Harvester UI
![image](https://user-images.githubusercontent.com/29251855/205007277-2257e08b-04ba-492c-800e-ad32c504087b.png)

### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-37ff3072-head` (12/1)
* Rancher version: `v2.7.0`

### Verify Steps
1. Import Harvester in Rancher 
2. Create a restricted admin user `radmin` in User & Authentication page 
3. Add `radmin` as cluster member role in Harvester cluster 
4. Use admin user to access Harvester from virtualization management page 
5. Check the wording of the left item 
6. Login with `radmin` user 
7. Use `radmin` to access Harvester from virtualization management page 
8. Check the wording of the left item

**Comment by dseralathan** [comment]
Geeting below error when trying to re-add the backup-target 

admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting

But there is no VM is that state .
