### ISSUE TITLE
[Question] Is Harvester 1.1.x supported with Rancher 2.7.0?

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#3222]
Rancher 2.7.0 was released 13 days ago so after Harvester 1.1.0 but before Harvester 1.1.1.  I know Rancher 2.7.0 introduces extensions and I'm keen to play with Elemental.

Am I likely to run into issues if I use Rancher 2.7.0 with Harvester 1.1.0 or 1.1.1 (when released and I upgrade my home lab cluster).

**Comment by RegisWeduLabs** [comment]
I'm running Rancher 2.7.0 mamagement cluster with Harvester 1.0.3 without any issues, so I would guess that it should run without issues...  But just to make sure, you are talking about the Management Rancher cluster - not the actual Rancher version bundled within harvester correct?  I wouldn't try to upgrade the rancher version in harvester separately from Harvester...

**Comment by simonflood** [comment]
Yes I'm asking about the separate, "management" Rancher (the one we should install ourselves to manage Kubernetes and Harvester) and not anything built into Harvester itself.

**Comment by RegisWeduLabs** [comment]
Then like I said, I'm using Rancher 2.7.0 to manage my current 1.0.3 Harvester cluster with no issues I didn't have on 2.6.9

**Comment by Martin-Weiss** [comment]
In my case Rancher 2.7.0 works with Harvester 1.1.0 - but obviously I could not test "everything" ;-).
P.S. also keep in mind that Rancher 2.7.0 is not marked as stable - it is "just" latest...
