### ISSUE TITLE
[Doc] After upgrade from v1.0.3 to v1.1.1 when you add a node it doesn't assign cluster network

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3223]
**Describe the bug**

When you upgrade a v1.0.3 cluster with a VLAN network to v1.1.1 it assigns only the existing nodes to the cluster network. If you add a node it won't assign the network to the node. This is an issue when you try to migrate a VM to the new node.
**To Reproduce**
1. Create v1.0.3 cluster
2. Add VLAN network
3. Create VM and assign it to the VLAN network
4. Shutdown VM
5. Upgrade to v1.1.1
6. Turn on VM
7. Add new node to Harvester cluster
8. Live migrate the VM to the new node
9. Try to SSH to the VM

**Expected behavior**

We should either add the new node to the cluster network or give a warning when trying to migrate a VM to a node without the assigned cluster network.

**Support bundle**

[cluster network defaulted to one node.zip](https://github.com/harvester/harvester/files/10118274/cluster.network.defaulted.to.one.node.zip)

**Environment**
 - Harvester ISO version: v1.0.3 -> v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Vagrant setup (12c 24g) then adding a second node with 6c 8g.

**Additional context**
For a workaround you can just add the node to the cluster network in the network config. Then reboot the VM. This was done on a single node and adding a node to make it a 2 node cluster, so I don't know if it will have the same issue with clusters of other sizes. I think it probably will.

**Comment by yaocw2020** [comment]
The converted network config from nodenetwork takes effect on only one node. Therefore, users have to add a new network config for newly added nodes.

**Comment by yaocw2020** [comment]
@noahgildersleeve I wonder why you can migrate the VM to the newly added node. It should be failed because the webhook will add the nodeaffinity to the VM to avoid migrating to nodes where the clusternetwork doesn't work.  Could you provide the support bundle before migration?

**Comment by noahgildersleeve** [comment]
@yaocw2020 I just tried to repro this and grab the logs. It assigned the VM to the new node. I'm thinking now that the issue might be with having the VM up on the network when adding in the new node. I'll check and update the ticket afterwards.

Here's the support bundles though from the steps
[Before migration.zip](https://github.com/harvester/harvester/files/10136876/Before.migration.zip)
[After upgrade.zip](https://github.com/harvester/harvester/files/10136877/After.upgrade.zip)
[Before upgrade.zip](https://github.com/harvester/harvester/files/10136878/Before.upgrade.zip)

**Comment by yaocw2020** [comment]
From the support bundle before migration, I find that the VM to be migrated only has a network within the built-in cluster network `mgmt`. The migration of the VM would be successful because the mgmt cluster network is effective on all nodes automatically.

**Comment by yaocw2020** [comment]
After merging the PR https://github.com/harvester/network-controller-harvester/pull/67, the harvester network controller now support changing the vlanconfig and Nad to make it easy to adjust the network configuration when adding a new node.

**Comment by guangbochen** [comment]
Can we add the doc to describe both the steps and required versions? thanks.

**Comment by guangbochen** [comment]
@yaocw2020 can you please help to add this as a known limitation before v1.1.2 and add vlanconfig enhancement changes to the doc, thanks.

**Comment by guangbochen** [comment]
Close as this a designed behavior also added the explanation in the https://github.com/harvester/docs/pull/291, starting from v1.1.2, users can now modify the vlanconfig to select all nodes config.
