### ISSUE TITLE
[FEATURE] Clean up PCIDevice and PCIDeviceClaim objects when Node leaves cluster

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#3224]
**Is your feature request related to a problem? Please describe.**
When a node is removed from the cluster, or becomes cordoned, the pcidevices controller doesn't clean up the PCIDevice and PCIDeviceClaim objects. Issue #2960 sparked the creation of this issue.

**Describe the solution you'd like**
A goroutine in pcidevices and pcideviceclaims controller that checks for nodes being removed from the cluster, and if a node is removed, a loop that cleans up those PCIDevice and PCIDeviceClaim objects.

**Describe alternatives you've considered**
N/A

**Additional context**
Look at #2960 for context on what motivate this issue.

**Comment by bk201** [comment]
@tlehman @ttpcodes Do we have a draft PR for this issue? Thanks.

**Comment by tlehman** [comment]
Working on it at the moment

**Comment by tlehman** [comment]
https://github.com/harvester/pcidevices/pull/40

**Comment by irishgordo** [comment]
@tlehman  noticing validation issues with the cleanup.
**Validation Failed**
Tested on Harvester Version: v1.1-a72900af-head ( created: Wed 01 Mar 2023 05∶18∶17 PM PST )
On 3 Node Bare-Metal (1 Node Dell PowerEdge R720) with:
[the intel PCI network card](https://www.intel.com/content/www/us/en/products/sku/20720/intel-82571eb-gigabit-ethernet-controller/specifications.html)
And utilizing `lshw` providing:
```
           *-pci
                description: PCI bridge
                product: PES12N3A 12-lane 3-Port PCI Express Switch
                vendor: Microsemi / PMC / IDT
                physical id: 0
                bus info: pci@0000:03:00.0
                version: 0e
                width: 32 bits
                clock: 33MHz
                capabilities: pci pciexpress pm normal_decode bus_master cap_list
                resources: ioport:d000(size=8192) memory:d9000000-daffffff
              *-pci:0
                   description: PCI bridge
                   product: PES12N3A 12-lane 3-Port PCI Express Switch
                   vendor: Microsemi / PMC / IDT
                   physical id: 2
                   bus info: pci@0000:04:02.0
                   logical name: /dev/fb0
                   version: 0e
                   width: 64 bits
                   clock: 33MHz
                   capabilities: pci pciexpress pm msi normal_decode bus_master cap_list fb
                   configuration: depth=32 driver=pcieport mode=1024x768 visual=truecolor xres=1024 yres=768
                   resources: iomemory:e1e10-e1e0f irq:32 ioport:e000(size=4096) memory:d9000000-d9ffffff
                 *-network:0
                      description: Ethernet interface
                      product: 82571EB/82571GB Gigabit Ethernet Controller (Copper)
                      vendor: Intel Corporation
                      physical id: 0
                      bus info: pci@0000:05:00.0
                      logical name: enp5s0f0
                      version: 06
                      serial: 00:14:5e:ea:33:81
                      size: 1Gbit/s
                      capacity: 1Gbit/s
                      width: 32 bits
                      clock: 33MHz
                      capabilities: pm msi pciexpress bus_master cap_list rom ethernet physical tp 10bt 10bt-fd 100bt 100bt-fd 1000bt-fd autonegotiation
                      configuration: autonegotiation=on broadcast=yes driver=e1000e driverversion=5.14.21-150400.24.41-default duplex=full firmware=5.12-2 latency=0 link=yes multicast=yes port=twisted pair speed=1Gbit/s
```
PCI Device Passthrough was enabled for:
```
## the product: 82571EB/82571GB Gigabit Ethernet Controller (Copper)
bus info: pci@0000:05:00.0
```
PCI Device Claim built.
```
address: "0000:05:00.0"
classId: "0200"
description: 'Ethernet controller: Intel Corporation 82571EB/82571GB Gigabit Ethernet Controller (Copper)'
deviceId: 10bc
iommuGroup: "20"
kernelDriverInUse: vfio-pci
nodeName: test-v11-head
resourceName: intel.com/82571EB_82571GB_GIGABIT_ETHERNET_CONTROLLER_COPPER
vendorId: "8086"
```

Also had followed up by uninstalling rke2- on the node via as `sudo su` / root:
```
./opt/rke2/bin/rke2-uninstall.sh
```

Supporting test video artifact:

https://user-images.githubusercontent.com/5370752/223287125-29ba9c6e-735f-4f89-8b55-9eb4f92456a9.mp4


Support Bundle:

[supportbundle_33261b79-d6ba-4094-afbb-35feeaa8c932_2023-03-07T00-26-59Z.zip](https://github.com/harvester/harvester/files/10904072/supportbundle_33261b79-d6ba-4094-afbb-35feeaa8c932_2023-03-07T00-26-59Z.zip)

**Comment by irishgordo** [comment]
Tested on Harvester Version: v1.1-054b48bf-head.
3 Node Cluster.
PCI Devices & PCIDeviceClaims do get removed/cleanedup.

https://user-images.githubusercontent.com/5370752/223761656-c601f8c6-895e-45b4-819f-1d6c337db34f.mp4

Closing out :+1: :smile:
