### ISSUE TITLE
[BUG] VNC and Serial Console is blank when accessed through Rancher Manager

### ISSUE THREAD

**Issue by dnoland1** [harvester/harvester#3229]
**Describe the bug**
After adding my Harvester environment to Rancher Manager, cannot access a Virtual Machine's VNC and serial console. Both just show a blank screen. Works fine if accessing Harvester directly. These screen captures show Harvester on the left and Rancher Manager on the right:
![image](https://user-images.githubusercontent.com/468462/204932904-b7a8461f-163b-4bbc-8557-b72a35f564a3.png)

**To Reproduce**
1. Add Harvester to Rancher Manager
2. Create a Virtual Machine
3. In the Rancher Manager UI, navigate to Harvester.
4. Once VM is running, select the Console, Open in Web VNC or Open in Serial Console options.

**Expected behavior**
VM consoles are accessible when accessed through Rancher Manager.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Equinix m3.small.x86 (2 nodes)

**Additional context**
None

**Comment by WuJun2016** [comment]
Hi @dnoland1  I imported harvester v1.1.0 into rancher 2.7.0 and both open VNC and open Serial Console worked fine.

1. What is the image used by your VM ?  
2. I noticed that you're using Serial Console in rancher and you're opening web VNC in harvester,  I want to confirm, can you check in rancher to see if web VNC is working fine ？
3. What version of rancher are you using?

![image](https://user-images.githubusercontent.com/24985926/204960516-9df4c9b4-08a7-4ddc-b319-931f1b03032f.png)

![image](https://user-images.githubusercontent.com/24985926/204960543-8e500a9a-1f0d-456d-a298-7ad01909c681.png)

**Comment by dnoland1** [comment]
>     1. What is the image used by your VM ?
https://cloud-images.ubuntu.com/lunar/current/lunar-server-cloudimg-amd64.img

>     2. I noticed that you're using Serial Console in rancher and you're opening web VNC in harvester,  I want to confirm, can you check in rancher to see if web VNC is working fine ？
Both give me a blank screen in Rancher.
> 
>     3. What version of rancher are you using?
v2.6.9

**Comment by WuJun2016** [comment]
@dnoland1  I used the information you provided to reproduce this problem, but everything is working as expected.  
![image](https://user-images.githubusercontent.com/24985926/205584733-367c2e5f-4ca7-436a-83fc-786d3beebffe.png)

![image](https://user-images.githubusercontent.com/24985926/205584620-a2f482cf-0f6f-4ebd-8ac2-e3ef69cbb795.png)

Does this problem occur 100%?
Maybe it was just a broken link from rancher's websocket at the time ？

Can you check if the websocket link works?
![image](https://user-images.githubusercontent.com/24985926/205585498-b793e24a-8d5b-4eb8-88dc-12de343dbd6c.png)

**Comment by WuJun2016** [comment]
@dnoland1  I used the information you provided to reproduce this problem, but everything is working as expected.  
![image](https://user-images.githubusercontent.com/24985926/205584733-367c2e5f-4ca7-436a-83fc-786d3beebffe.png)

![image](https://user-images.githubusercontent.com/24985926/205584620-a2f482cf-0f6f-4ebd-8ac2-e3ef69cbb795.png)

Does this problem occur 100%?
Maybe it was just a broken link from rancher's websocket at the time ？

Can you check if the websocket link works?
![image](https://user-images.githubusercontent.com/24985926/205585498-b793e24a-8d5b-4eb8-88dc-12de343dbd6c.png)

**Comment by dnoland1** [comment]
@WuJun2016 I'm not able to reproduce it. If it happens again, I'll check the websocket in developer tools and reopen the issue if needed. Thanks for looking into it.
