### ISSUE TITLE
[BUG] Tips of deleting vm is not accurate

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3231]
**Describe the bug**

**To Reproduce**
1. Go to create a vm
2. Delete the vm just created
3. Tips of deleting vm is not accurate

![image.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/e42c75f3-1ae0-4b72-b82f-4d6ab9f04780)

**Expected behavior**

Tips of deleting vm should be `Warn: The snapshots of vm and volume will be deleted with VM.`

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
Validated on Harvester Version: master-bbc2b33f-head 
This looks good :smile: 
Thanks @DaiYuzeng !
![Screenshot from 2022-12-22 16-00-19](https://user-images.githubusercontent.com/5370752/209245115-6cfa8fe1-42d5-4877-93fd-314912bc48a4.png)
I'll go ahead and close this out
