### ISSUE TITLE
[Question] Harvester support for native KVM VM without KubeVirt

### ISSUE THREAD

**Issue by rafiqkattangere** [harvester/harvester#3233]
We have several VM's which aren't supported in KubeVirt environments. Rather they work well with KVM. Is there a way Harvester could support native KVM VM's without going through KubeVirt?

**Comment by Vicente-Cheng** [comment]
hi @rafiqkattangere, 
Thanks for your question.
I think harvester could not support native KVM now. Could you share the limitations on your cases that KVM but not KubeVirt?

Maybe that would be good feedback for us.
Thanks!
