### ISSUE TITLE
[FEATURE] UI enhancements for logging, monitoring as addon

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3235]
**Is your feature request related to a problem? Please describe.**

There are UI enhancements for `logging`, `monitoring`  as addon.

**Describe the solution you'd like**

(1) New addons do not automatically have enable/disable menu in UI
(2) The resource setting of `logging`, `monitoring` is against ManagedChart now, it needs to be changed to addon valueContent string
(3) When logging is disabled, need to consider to collaborate with (Cluster)Flow/(Cluster)Output, should those be also disabled? or allow to continue add/modify/delete;  for monitoring, it is same
(4) The monitoring, logging will be disabled by default, user will enable them by addon menu, or harvester config
(5) Monitoring is disabled by default, the harvester dashboard will have no data to show about `cluster metrics, VM metrics`
(6) Potential more

**Describe alternatives you've considered**

**Additional context**

https://github.com/harvester/harvester/issues/2992 [FEATURE] Provide Monitoring and or Logging as an AddOn

backend code PR:
https://github.com/harvester/harvester-installer/pull/402

<img width="570" alt="image" src="https://user-images.githubusercontent.com/31133476/205261917-15cad760-12a7-44d4-8d17-519721aa4d74.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/31133476/205261977-74bf2b82-2b91-4ebf-9ac2-a5eeb2821760.png">

**Comment by w13915984028** [comment]
cc @WuJun2016 @DaiYuzeng @guangbochen @bk201

**Comment by w13915984028** [comment]
backend code PR is ready for develp&test of UI part

https://github.com/harvester/harvester-installer/pull/402

**Comment by WuJun2016** [comment]
Hi  @w13915984028 It seems that all backend PRs have been merged. Can we now move this issue to the `Ready For testing `?

**Comment by w13915984028** [comment]
@DaiYuzeng You are the assignee of this issue, please move it to `ready for testing`, thanks.

**Comment by irishgordo** [comment]
**Validation Issue**
@w13915984028 for validating that the values can be passed in at configuration is:
https://github.com/irishgordo/scratch-dump/blob/main/test-vm.yaml

A valid configuration?

I'm running into issues where the installer encounters an error:
![Screenshot from 2023-05-15 16-01-32](https://github.com/harvester/harvester/assets/5370752/eb74bae5-da4b-4a2b-bec9-b866029446a4)

Attaching the console.log here:
[console.log](https://github.com/harvester/harvester/files/11482621/console.log)

**Comment by irishgordo** [comment]
@DaiYuzeng  closing this out as from the UI side in relation to this it looks good :smile: :+1: 

Tested on master-head (05-15)
![Screenshot from 2023-05-15 10-43-32](https://github.com/harvester/harvester/assets/5370752/a512e644-f2ad-439c-a9ce-6143de381920)
