### ISSUE TITLE
[Question] Embedded Rancher show no etcd leader

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#3236]
In the embedded rancher, Grafana (ETCDMetrics) shows "Etcd has a leader: NO". Is this correct?

My hardware: Harvester Cluster with three hosts, 12 Cores and 32GB Memory each, Harvester 1.1.1

**Comment by Vicente-Cheng** [comment]
hi @jrlittlefoot64, 
I do not meet this situation.
Could you describe more about this or try to get a support bundle for us?

Did you fresh installation or upgrade from an older version?
Thanks!

**Comment by jrlittlefoot64** [comment]
hi @Vicente-Cheng , it was a fresh 1.0.3 installation and then update to 1.1.1.
I think my disks to slow, I send you the outout from fio from my system

 fio --rw=write --ioengine=sync --fdatasync=1 --directory=test-data --size=22m --bs=2300 --name=mytest
mytest: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
fio-3.32
Starting 1 process
mytest: Laying out IO file (1 file / 22MiB)
Jobs: 1 (f=1): [W(1)][100.0%][w=233KiB/s][w=104 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=8065: Tue Dec  6 10:24:47 2022
  write: IOPS=286, BW=644KiB/s (659kB/s)(22.0MiB/34981msec); 0 zone resets
    clat (usec): min=6, max=2049, avg=43.92, stdev=122.38
     lat (usec): min=6, max=2050, avg=44.56, stdev=122.39
    clat percentiles (usec):
     |  1.00th=[   12],  5.00th=[   16], 10.00th=[   19], 20.00th=[   23],
     | 30.00th=[   26], 40.00th=[   28], 50.00th=[   30], 60.00th=[   31],
     | 70.00th=[   34], 80.00th=[   37], 90.00th=[   41], 95.00th=[   47],
     | 99.00th=[  840], 99.50th=[ 1090], 99.90th=[ 1401], 99.95th=[ 1614],
     | 99.99th=[ 1778]
   bw (  KiB/s): min=   62, max=  745, per=100.00%, avg=645.77, stdev=157.61, samples=69
   iops        : min=   28, max=  332, avg=287.74, stdev=70.16, samples=69
  lat (usec)   : 10=0.35%, 20=13.84%, 50=82.00%, 100=2.29%, 500=0.02%
  lat (usec)   : 750=0.32%, 1000=0.47%
  lat (msec)   : 2=0.70%, 4=0.01%
  fsync/fdatasync/sync_file_range:
    sync (usec): min=1187, max=79452, avg=3436.82, stdev=3195.35
    sync percentiles (usec):
     |  1.00th=[ 1287],  5.00th=[ 1352], 10.00th=[ 1401], 20.00th=[ 1614],
     | 30.00th=[ 2245], 40.00th=[ 2507], 50.00th=[ 2933], 60.00th=[ 3130],
     | 70.00th=[ 4015], 80.00th=[ 4555], 90.00th=[ 4883], 95.00th=[ 5276],
     | 99.00th=[15795], 99.50th=[29230], 99.90th=[45876], 99.95th=[47449],
     | 99.99th=[63177]
  cpu          : usr=0.42%, sys=2.75%, ctx=39161, majf=0, minf=13
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10029,0,0 short=10029,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=644KiB/s (659kB/s), 644KiB/s-644KiB/s (659kB/s-659kB/s), io=22.0MiB (23.1MB), run=34981-34981msec

Disk stats (read/write):
    dm-2: ios=0/41565, merge=0/0, ticks=0/57256, in_queue=57256, util=99.51%, aggrios=0/41257, aggrmerge=0/463, aggrticks=0/56691, aggrin_queue=89199, aggrutil=99.49%
  sda: ios=0/41257, merge=0/463, ticks=0/56691, in_queue=89199, util=99.49%

**Comment by jrlittlefoot64** [comment]
Here the support bundle
[supportbundle_07c9406d-71f0-4273-a597-f1381cf27eb6_2022-12-06T09-44-37Z.zip](https://github.com/harvester/harvester/files/10164803/supportbundle_07c9406d-71f0-4273-a597-f1381cf27eb6_2022-12-06T09-44-37Z.zip)

**Comment by abonillabeeche** [comment]
@jrlittlefoot64 is this still an issue? Your disk may definitely be too slow.

**Comment by jrlittlefoot64** [comment]
@abonillabeeche I will try it again with new SSDs, close this issue for now

**Comment by jrlittlefoot64** [comment]
Hello, I change my hardware setup, now two SSD 870 EVO  a 2 TB and have the same issue. No leader

**Comment by ibrokethecloud** [comment]
are you please able to provide a new support bundle from this setup?

**Comment by jrlittlefoot64** [comment]
@ibrokethecloud  It is a fresh 1.1.1 installation, the output from fio is:
juergen@localhost:~> fio --rw=write --ioengine=sync --fdatasync=1 --directory=test-data --size=22m --bs=2300 --name=mytest
mytest: (g=0): rw=write, bs=(R) 2300B-2300B, (W) 2300B-2300B, (T) 2300B-2300B, ioengine=sync, iodepth=1
fio-3.33
Starting 1 process
Jobs: 1 (f=1): [W(1)][100.0%][w=2805KiB/s][w=1249 IOPS][eta 00m:00s]
mytest: (groupid=0, jobs=1): err= 0: pid=6016: Tue Feb  7 12:14:44 2023
  write: IOPS=1264, BW=2841KiB/s (2909kB/s)(22.0MiB/7929msec); 0 zone resets
    clat (usec): min=4, max=1389, avg=72.22, stdev=92.78
     lat (usec): min=4, max=1389, avg=72.58, stdev=92.80
    clat percentiles (usec):
     |  1.00th=[    5],  5.00th=[    7], 10.00th=[    8], 20.00th=[   11],
     | 30.00th=[   14], 40.00th=[   20], 50.00th=[   68], 60.00th=[   80],
     | 70.00th=[   94], 80.00th=[  120], 90.00th=[  139], 95.00th=[  153],
     | 99.00th=[  570], 99.50th=[  693], 99.90th=[  955], 99.95th=[ 1139],
     | 99.99th=[ 1385]
   bw (  KiB/s): min= 2632, max= 3009, per=100.00%, avg=2847.07, stdev=115.28, samples=15
   iops        : min= 1172, max= 1340, avg=1267.80, stdev=51.35, samples=15
  lat (usec)   : 10=16.26%, 20=24.28%, 50=2.93%, 100=28.31%, 250=26.53%
  lat (usec)   : 500=0.40%, 750=0.92%, 1000=0.27%
  lat (msec)   : 2=0.10%
  fsync/fdatasync/sync_file_range:
    sync (usec): min=605, max=12919, avg=713.93, stdev=205.79
    sync percentiles (usec):
     |  1.00th=[  627],  5.00th=[  635], 10.00th=[  644], 20.00th=[  660],
     | 30.00th=[  668], 40.00th=[  685], 50.00th=[  693], 60.00th=[  709],
     | 70.00th=[  717], 80.00th=[  734], 90.00th=[  750], 95.00th=[  775],
     | 99.00th=[ 1352], 99.50th=[ 1434], 99.90th=[ 2311], 99.95th=[ 4359],
     | 99.99th=[ 8848]
  cpu          : usr=1.37%, sys=6.63%, ctx=41003, majf=0, minf=16
  IO depths    : 1=200.0%, 2=0.0%, 4=0.0%, 8=0.0%, 16=0.0%, 32=0.0%, >=64=0.0%
     submit    : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     complete  : 0=0.0%, 4=100.0%, 8=0.0%, 16=0.0%, 32=0.0%, 64=0.0%, >=64=0.0%
     issued rwts: total=0,10029,0,0 short=10029,0,0,0 dropped=0,0,0,0
     latency   : target=0, window=0, percentile=100.00%, depth=1

Run status group 0 (all jobs):
  WRITE: bw=2841KiB/s (2909kB/s), 2841KiB/s-2841KiB/s (2909kB/s-2909kB/s), io=22.0MiB (23.1MB), run=7929-7929msec

Disk stats (read/write):
    dm-2: ios=5609/22058, merge=0/0, ticks=484/7876, in_queue=8360, util=99.51%, aggrios=2817/16440, aggrmerge=0/13, aggrticks=231/4312, aggrin_queue=8070, aggrutil=99.41%
  sda: ios=5634/21640, merge=0/26, ticks=463/7683, in_queue=14573, util=99.32%
  sdb: ios=1/11241, merge=0/0, ticks=0/942, in_queue=1567, util=99.41%

And here is the supportbundle:
[supportbundle_ed97587e-bde7-4e2d-a539-d2a7c11ad2b3_2023-02-07T11-14-00Z.zip](https://github.com/harvester/harvester/files/10674412/supportbundle_ed97587e-bde7-4e2d-a539-d2a7c11ad2b3_2023-02-07T11-14-00Z.zip)

**Comment by ibrokethecloud** [comment]
I can see quite a few errors in the logs which seem to indicate etcd is not healthy.
```
etcd-harvester-02 etcd 2023-02-07T07:55:50.927555561Z {"level":"warn","ts":"2023-02-07T07:55:50.927Z","caller":"etcdserver/corrupt.go:289","msg":"failed hash kv request","local-member-id":"2ba0b20bf4d0840e","requested-revision":186961,"remote-peer-endpoint":"https://192.168.178.126:2380","error":"Get \"https://192.168.178.126:2380/members/hashkv\": dial tcp 192.168.178.126:2380: connect: connection refused"}
etcd-harvester-02 etcd 2023-02-07T07:56:05.928721634Z {"level":"warn","ts":"2023-02-07T07:56:05.928Z","caller":"etcdserver/corrupt.go:289","msg":"failed hash kv request","local-member-id":"2ba0b20bf4d0840e","requested-revision":186961,"remote-peer-endpoint":"https://192.168.178.123:2380","error":"Get \"https://192.168.178.123:2380/members/hashkv\": net/http: request canceled"}
etcd-harvester-02 etcd 2023-02-07T07:56:05.937306445Z {"level":"warn","ts":"2023-02-07T07:56:05.936Z","caller":"etcdserver/corrupt.go:377","msg":"failed to get hashKV","requested-revision":186963,"error":"mvcc: required revision is a future revision"}
etcd-harvester-02 etcd 2023-02-07T07:56:05.937315013Z {"level":"warn","ts":"2023-02-07T07:56:05.936Z","caller":"etcdserver/corrupt.go:377","msg":"failed to get hashKV","requested-revision":186963,"error":"mvcc: required revision is a future revision"}
```

Are you please able to exec into the etcd-harvester-01 pod in kube-system namespace and run the following

```
kubectl exec -it etcd-harvester-01 -n kube-system -- /bin/sh
```

Once in can you please run the following commands:

```
etcdctl --cacert=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key member list

etcdctl --cacert=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key check perf

etcdctl --cacert=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --cert=/var/lib/rancher/rke2/server/tls/etcd/server-client.crt --key=/var/lib/rancher/rke2/server/tls/etcd/server-client.key endpoint health --endpoints=192.168.178.123:2379,192.168.178.125:2379,192.168.178.126:2379
```

**Comment by jrlittlefoot64** [comment]
Thank you for your reply, I will try it tomorrow

**Comment by jrlittlefoot64** [comment]
@ibrokethecloud  Hello, the result of "member list" is false, the "check perf" is pass and the "endpoint health" is is healthy:successfully commited proposal

**Comment by ibrokethecloud** [comment]
any chance i could please see the full command and outputs?

**Comment by jrlittlefoot64** [comment]
@ibrokethecloud sorry for the late answer, I reinstall harvester-01 -03 and have the same error here is my output

![Screenshot_20230217_112438](https://user-images.githubusercontent.com/85644625/219619050-bc48af35-d01c-46cf-bd85-2560a42a4539.png)

[supportbundle_c26570e7-2b82-4db1-8797-b9079df611d4_2023-02-17T10-28-16Z.zip](https://github.com/harvester/harvester/files/10765800/supportbundle_c26570e7-2b82-4db1-8797-b9079df611d4_2023-02-17T10-28-16Z.zip)

**Comment by jrlittlefoot64** [comment]
This issue insn't solved, with 1.1.2 I have the same

**Comment by jrlittlefoot64** [comment]
sorry,issue not solved

**Comment by w13915984028** [comment]
More investigation is required.
