### ISSUE TITLE
[Question] Upload large image error: Websocket Disconnected 

### ISSUE THREAD

**Issue by Captured77** [harvester/harvester#3237]
When I upload large image, harvester ui appear websocket disconnected. As follow:

Websocket Disconnected
The connection to wss://harvester.iluvatar.com.cn/v1/subscribe closed unexpectedly at Fri, Dec 2 2022 8:14:55 pm. Disconnected after 4 reconnect attempts. Check your network connection and reload the page

Harvester server error:
Error during subscribe write tcp 10.42.0.40:8080->10.42.0.65:47108: write: broken pipe

**Comment by w13915984028** [comment]
Which Harvester version are you using ?

In version v1.0.0 or v0.3.0, there is an known issue: https://github.com/harvester/harvester/issues/1904 , it is fixed from v1.0.1.

**Comment by Captured77** [comment]
> 

I use harvester v1.1.0.
