### ISSUE TITLE
[Question] Install the Rancher UI for remote integration with Harvester

### ISSUE THREAD

**Issue by DmitriZV** [harvester/harvester#3240]
Hi all!

How to install Rancher Desktop (UI version) for remote access from other compute? (by IP address, etc.)
In order for it to be available for connection/import from a remote Harvester server? (another computer that is not on the local network with the computer which has running Rancher Desktop)?

My problem:
I’m able to install Rancher Desktop UI accessed at “localhost”, but it’s not enough to access Rancher from a remote computer (running Harvester).

My computer for the Rancher Desktop UI:
Windows 10 with WSL2
Subsystem: Debian

P.s. Also created this question in the Rancher forum: https://forums.rancher.com/t/install-the-rancher-desktop-ui-for-remote-integration-with-harvester/39595/1

**Comment by simonflood** [comment]
I believe the Rancher Dashboard included in Rancher Desktop is for working with the local cluster provided by Rancher Desktop - see https://www.suse.com/c/rancher_blog/rancher-desktop-now-includes-the-rancher-dashboard/ - so it's not for managing external (to Rancher Desktop) clusters.

I'm not sure if installing "regular" Rancher in Rancher Desktop - see https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop - will help as you'll need to have Rancher hosted on a "real" IP address, not localhost, for it to be externally accessible.

**Comment by DmitriZV** [comment]
> I believe the Rancher Dashboard included in Rancher Desktop is for working with the local cluster provided by Rancher Desktop - see https://www.suse.com/c/rancher_blog/rancher-desktop-now-includes-the-rancher-dashboard/ - so it's not for managing external (to Rancher Desktop) clusters.
> 
> I'm not sure if installing "regular" Rancher in Rancher Desktop - see https://docs.rancherdesktop.io/how-to-guides/rancher-on-rancher-desktop - will help as you'll need to have Rancher hosted on a "real" IP address, not localhost, for it to be externally accessible.

Thank you for your response!
Now I try to communicate the Harvester (VM in the VMware 17 player with 'bridged' internet adapter) and Rancher (installed on Ubuntu 20.04 V Mn the VMware 17 player with 'bridged' internet adapter), both without "Replicate physical network"

Is it the best solution (using the 'homelab' and VMs) to integrate Harvester in the Rancher ?
UPD: set the static IP for the Rancher and successfully imported the Harvester in the Rancher
