### ISSUE TITLE
[Question] Configure network failed: fork/exec /usr/bin/yip: input/output error via ISO installation

### ISSUE THREAD

**Issue by bingo4933** [harvester/harvester#3245]
I'm new to deploy Harvester via ISO image on DELL R640.
I run into the issue from `Configure network connection` wizard page.
```
Configure network failed: fork/exec /usr/bin/yip: input/output error
```

what happened and how to fix it??
![Image 16](https://user-images.githubusercontent.com/56991619/205886746-b86673fa-871a-48eb-bb54-ac3790ea7e5c.png)

**Comment by Vicente-Cheng** [comment]
hi @bingo4933, how did you mount the ISO to virtual media?

I am afraid the network connection may be lost, so some binary could not be used.

**Comment by bingo4933** [comment]
hello @Vicente-Cheng thanks for reply. I remounted the virtual ISO image to machine. it worked, thank you

**Comment by Vicente-Cheng** [comment]
@bingo4933, NP! If you have other questions, feel free to open another issue.

I just closed this as resolved.
