### ISSUE TITLE
[BUG] Havester 1.1.0 upgrade to 1.1.1 is missing image docker.io/longhornio/longhorn-ui:v1.3.2

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3246]
**Describe the bug**
After the upgrade from harvester 1.1.0 to 1.1.1 I can see this:

`longhorn-ui-94b465b84-2d2zx                    0/1     ImagePullBackOff   0              59m`

and

`Failed to pull image "longhornio/longhorn-ui:v1.3.2`

**To Reproduce**

Upgrade Harvester 1.1.0 to 1.1.1 in air gapped

**Expected behavior**
Harvester should have all the required images included on the ISO

**Environment**
 - Harvester ISO version: 1.1.1

**Comment by Martin-Weiss** [comment]
Maybe the reason is that the image has been removed due do disk pressure? I can see two nodes have the image but one node does not.. so "if" we have disk pressure and the pre-load of images is not sufficient - how to we deal with this?

**Comment by Martin-Weiss** [comment]
Is there a good reason why we do not use the same images in Harvester that we already use with Rancher?

I already had the image longhorn-ui:v1.3.2 in the registry due to Rancher air-gapped etc. but this has been:

`docker.io/rancher/mirrored-longhornio-longhorn-ui:v1.3.2`

and Harvester is using:
`docker.io/longhornio/longhorn-ui:v1.3.2`

So it seems we have two issues, here:
1. pre-loaded images get removed due to disk pressure
2. re-loading them from the on-premise registry (configured via containerd registries.yaml) does not work as the images are not uploaded, there.

So to address this:

1. could we get the problem with disk pressure for images addressed via adjusted partitioning and resizing and requirements adjustments
2. could we publish a list of images required for Harvester air-gapped so that customers can pre-replicate them to their on-premise registry?

**Comment by starbops** [comment]
> 2. could we publish a list of images required for Harvester air-gapped so that customers can pre-replicate them to their on-premise registry?

An image-lists tarball was generated during the ISO build (ref: harvester/harvester-installer#318). Maybe we can publish this along with other artifacts at each release?

cc @bk201

**Comment by Martin-Weiss** [comment]
> > 2. could we publish a list of images required for Harvester air-gapped so that customers can pre-replicate them to their on-premise registry?
> 
> An image-lists tarball was generated during the ISO build (ref: [harvester/harvester-installer#318](https://github.com/harvester/harvester-installer/pull/318)). Maybe we can publish this along with other artifacts at each release?
> 
> cc @bk201

Do we have these artifacts already available to download "somewhere" or are they somewhere on the ISO?

**Comment by Vicente-Cheng** [comment]
> > > 2. could we publish a list of images required for Harvester air-gapped so that customers can pre-replicate them to their on-premise registry?
> > 
> > 
> > An image-lists tarball was generated during the ISO build (ref: [harvester/harvester-installer#318](https://github.com/harvester/harvester-installer/pull/318)). Maybe we can publish this along with other artifacts at each release?
> > cc @bk201
> 
> Do we have these artifacts already available to download "somewhere" or are they somewhere on the ISO?

You could check the `bundle/harvester` in ISO. There are image-list and images.

**Comment by bk201** [comment]
Looks like disk pruning due to disk pressure. In the short term, we can add checks in https://github.com/harvester/harvester/issues/3067 or https://github.com/harvester/harvester/issues/2935 to ensure there is enough space.

**Comment by Martin-Weiss** [comment]
> Looks like disk pruning due to disk pressure. In the short term, we can add checks in #3067 or #2935 to ensure there is enough space.

And I believe we have to add a process to cleanup the right old images duing an upgrade and provide docs which images should be available via an on-premise registry and with proper containerd-registries config...

**Comment by bk201** [comment]
- pre-check will be worked in https://github.com/harvester/harvester/issues/3067
- Clean image enhancement: https://github.com/harvester/harvester/issues/2132
Close this one.
