### ISSUE TITLE
[BUG] failed to update vm using terraform apply

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3248]
**Describe the bug**

**To Reproduce**
1. use terraform-provider-harvester v0.6.0
2. terraform apply
```hcl
resource "harvester_image" "ubuntu20" {
  name      = "ubuntu20"
  namespace = "harvester-public"

  display_name = "ubuntu-20.04-server-cloudimg-amd64.img"
  source_type  = "download"
  url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
}

resource "harvester_virtualmachine" "ubuntu20" {
  name                 = "ubuntu20"
  namespace            = "default"
  restart_after_update = true

  description = "test ubuntu20 raw image"
  tags = {
    ssh-user = "ubuntu"
  }

  cpu    = 2
  memory = "2Gi"

  efi         = true
  secure_boot = true

  run_strategy = "RerunOnFailure"
  hostname     = "ubuntu20"
  machine_type = "q35"

  network_interface {
    name           = "nic-1"
    wait_for_lease = true
  }

  disk {
    name       = "rootdisk"
    type       = "disk"
    size       = "10Gi"
    bus        = "virtio"
    boot_order = 1

    image       = harvester_image.ubuntu20.id
    auto_delete = true
  }

  disk {
    name        = "emptydisk"
    type        = "disk"
    size        = "20Gi"
    bus         = "virtio"
    auto_delete = true
  }

  cloudinit {
    user_data    = <<-EOF
      #cloud-config
      password: 123456
      chpasswd:
        expire: false
      ssh_pwauth: true
      package_update: true
      packages:
        - qemu-guest-agent
      runcmd:
        - - systemctl
          - enable
          - '--now'
          - qemu-guest-agent
      EOF
    network_data = ""
  }

}
```
3. change vm description
4. `terraform apply` again

```bash

harvester_virtualmachine.ubuntu20: Modifying... [id=default/ubuntu20]
╷
│ Error: the storage_class_name of an image can only be defined during image creation
│
│   with harvester_virtualmachine.ubuntu20,
│   on main.tf line 6, in resource "harvester_virtualmachine" "ubuntu20":
│    6: resource "harvester_virtualmachine" "ubuntu20" {
```

**Expected behavior**

update vm success

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested with  locally compiled master with commit 274a844f9dd3d403a188f2455fc06ba857d96b7d and I was able to update the VM description.
![Screenshot_20221213_163601](https://user-images.githubusercontent.com/83787952/207475747-2d7b14b5-374b-4c23-ba77-f6fb78d9c25f.png)
![Screenshot_20221213_163547](https://user-images.githubusercontent.com/83787952/207475749-87f002e6-76b2-4d4c-b0dd-06c114382b9e.png)
![Screenshot_20221213_163528](https://user-images.githubusercontent.com/83787952/207475750-b3d356a0-1795-4081-85e5-f44dbbb7d6a6.png)
![Screenshot_20221213_163455](https://user-images.githubusercontent.com/83787952/207475752-084e0eaa-accb-4f10-9b30-0bdc68664021.png)



> **Describe the bug**
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. use terraform-provider-harvester v0.6.0
> 2. terraform apply
> 
> ```terraform
> resource "harvester_image" "ubuntu20" {
>   name      = "ubuntu20"
>   namespace = "harvester-public"
> 
>   display_name = "ubuntu-20.04-server-cloudimg-amd64.img"
>   source_type  = "download"
>   url          = "http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64.img"
> }
> 
> resource "harvester_virtualmachine" "ubuntu20" {
>   name                 = "ubuntu20"
>   namespace            = "default"
>   restart_after_update = true
> 
>   description = "test ubuntu20 raw image"
>   tags = {
>     ssh-user = "ubuntu"
>   }
> 
>   cpu    = 2
>   memory = "2Gi"
> 
>   efi         = true
>   secure_boot = true
> 
>   run_strategy = "RerunOnFailure"
>   hostname     = "ubuntu20"
>   machine_type = "q35"
> 
>   network_interface {
>     name           = "nic-1"
>     wait_for_lease = true
>   }
> 
>   disk {
>     name       = "rootdisk"
>     type       = "disk"
>     size       = "10Gi"
>     bus        = "virtio"
>     boot_order = 1
> 
>     image       = harvester_image.ubuntu20.id
>     auto_delete = true
>   }
> 
>   disk {
>     name        = "emptydisk"
>     type        = "disk"
>     size        = "20Gi"
>     bus         = "virtio"
>     auto_delete = true
>   }
> 
>   cloudinit {
>     user_data    = <<-EOF
>       #cloud-config
>       password: 123456
>       chpasswd:
>         expire: false
>       ssh_pwauth: true
>       package_update: true
>       packages:
>         - qemu-guest-agent
>       runcmd:
>         - - systemctl
>           - enable
>           - '--now'
>           - qemu-guest-agent
>       EOF
>     network_data = ""
>   }
> 
> }
> ```
> 
> 3. change vm description
> 4. `terraform apply` again
> 
> ```shell
> harvester_virtualmachine.ubuntu20: Modifying... [id=default/ubuntu20]
> ╷
> │ Error: the storage_class_name of an image can only be defined during image creation
> │
> │   with harvester_virtualmachine.ubuntu20,
> │   on main.tf line 6, in resource "harvester_virtualmachine" "ubuntu20":
> │    6: resource "harvester_virtualmachine" "ubuntu20" {
> ```
> 
> **Expected behavior**
> 
> update vm success
> 
> **Support bundle**
> 
> **Environment**
> 
> * Harvester ISO version: v1.1.1
> * Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
> 
> **Additional context** Add any other context about the problem here.
