### ISSUE TITLE
[Question] stuck installation to Harvester for hours

### ISSUE THREAD

**Issue by bingo4933** [harvester/harvester#3249]
hello,
I ran into this issue like stuck installation for hours while deployment harvester.

seem like it  was trying to download container image at that time. My machine is running behind proxy, so maybe I need to configure proxy for `docker` or `containerd` in deployment stage.

How to configure it??
![Image 20](https://user-images.githubusercontent.com/56991619/206093569-c13468d2-4ad7-4508-9204-de8d670be363.png)

**Comment by starbops** [comment]
Hi @bingo4933, may I ask you what the installation method you used is (PXE or ISO)?

**Comment by bingo4933** [comment]
hello @starbops I use ISO

**Comment by starbops** [comment]
Is this a VM or bare-metal machine? If it is the latter, this might be related to issue #2651. 

The point you are stuck at is the stage of preloading images from a local image tarball provided by the ISO image. Mounting the ISO image over an unstable network can cause the connection to be broken. The workaround is stated in the [comment](https://github.com/harvester/harvester/issues/2651#issuecomment-1218389598) of the reported issue. Maybe you can give it a try.

**Comment by bingo4933** [comment]
thank you for reply and help. 

I tried irishgordo's workaround but hit another ERROR.

**Comment by simonflood** [comment]
@bingo4933 When you installed Harvester did you configure a proxy during the install?

**Comment by w13915984028** [comment]
@bingo4933   Is proxy URL configured in ISO installation guide?

https://docs.harvesterhci.io/v1.1/install/iso-install
Step 11: `(Optional) If you need to use an HTTP proxy to access the outside world, enter the proxy URL address here. Otherwise, leave this blank.`
