### ISSUE TITLE
[BUG] Creating Image counts down from 30 secs then back up

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#3251]
**Describe the bug**
When creating an Image by either using a URL or uploading a file a timer in the Age column next to the new image name counts down from 30 secs and then when it reaches 0 secs counts back up for the duration of the creation process.

**To Reproduce**
1. Go to Images
2. Click Create button
3. Paste in a URL (I used 64-bit openSUSE Leap 15.4 JeOS image for OpenStack Cloud) or upload a file from local storage
4. Observe timer counting down in Age column then when it reaches 0 secs starts incrementing

**Expected behavior**
The first time I noticed this I thought 30 secs would be a bit quick to create image from URL and then when it counted back I realised it wasn't estimated time left. I expect time to start at 0 secs then count up for however long. Once created I expect that time to be start of the actual age.

**Support bundle**
[supportbundle_af6572d3-42b1-43d1-8145-ce13e92f0e69_2022-12-07T12-54-49Z.zip](https://github.com/harvester/harvester/files/10176208/supportbundle_af6572d3-42b1-43d1-8145-ce13e92f0e69_2022-12-07T12-54-49Z.zip)

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure: Baremetal with 2x Intel NUC7i7DNxE

**Additional context**
Cluster originally installed with Harvester 1.0.0 and has then been upgraded through all subsequent versions in turn

**Comment by rrajendran17** [comment]
@simonflood I checked this on latest harvester versions (v1.3.1) and looks like age starts from 0 seconds and progresses correctly.
Can you confirm this on latest and we can close this issue ?

**Comment by simonflood** [comment]
@rrajendran17 yes this seems to be fixed, at least with 1.3.2. Timer starts at zero and continues as image is created and time passes.
