### ISSUE TITLE
[BUG] Creating VM counts down from 30 secs then back up

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#3252]
**Describe the bug**
Similar to  #3251 , creating a Virtual Machine shows a countdown from 30 secs in the Age column which when it reaches 0 secs counts back up and continues for age of VM.

**To Reproduce**
1. Go to Virtual Machines
2. Click the Create button
3. On Basics tab fill in Name, CPU (1), and Memory (1) fields
4. On Volumes tab pick an Image
5. Click the Create button
6. Observe countdown from 30 secs which then goes back up when it hits 0 secs

**Expected behavior**
Timer should start from 0 secs

**Support bundle**
This was generated for #3251 

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure : Baremetal with 2x Intel NUC7i7DNxE

**Additional context**
Cluster was originally installed as 1.0.0 then upgraded through all subsequent released versions.

**Comment by rrajendran17** [comment]
@simonflood I checked this on latest harvester versions (v1.3.1) and looks like age starts from 0 seconds and progresses correctly.
Can you confirm this on latest and we can close this issue ?

**Comment by simonflood** [comment]
@rrajendran17 yes this seems to be fixed, at least with 1.3.2. Timer starts at zero and continues as VM is created and time passes.
