### ISSUE TITLE
backup sync delayed for NFS Target 

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3253]
Hi Team,

we have set the backup target with NFS on two cluster  and took backup of VMs.

We have 4 backups and its not synced to the second cluster . with a small VM it synced quickly. 

Could you please let us know how to check the backup sync status and how we can speed up the sync .

**Comment by albertkohl-monotek** [comment]
/bump on this. i also asked similar in slack:

albert
 [Yesterday at 2:46 PM](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1670363202310959)
is there a way to force harvester to re-scan an NFS backup target?
i have two clusters, and if i backup in one cluster, and want to restore into the second cluster, i have to wait a file for the backup to show up once it's done.
white_check_mark
eyes
raised_hands




2 replies


Vicente Cheng
  [9 hours ago](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1670424337326099?thread_ts=1670363202.310959&cid=C01GKHKAG0K)
Hi 
[@albert](https://rancher-users.slack.com/team/U0462V7B2SW)
,
Did you mean you could not see the NFS backup target on the restore side? If yes, you could simply remove/add backup target again to trigger re-scan.


albert
  [1 hour ago](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1670451738843299?thread_ts=1670363202.310959&cid=C01GKHKAG0K)
[@Vicente Cheng](https://rancher-users.slack.com/team/U03KDGP3RL4)
 yes, kinda. in v1.0.3 it wont let me delete / re-add. but it's okay, i just had to wait for it to show up. i was more wondering if there's a pod i could kill that makes it re-scan when it re-launches or something. #impatient :slightly_smiling_face:

**Comment by dseralathan** [comment]
Thanks Albert,. yeah even I thought same that any pod - the tech doc says the backup controller will sync the data . Sync taking a while and if we try to delete and re-add NFS backup target it throw error

**Comment by Vicente-Cheng** [comment]
hi @dseralathan, could you describe in more detail these 4 backup VMs?
(like how many disks are attached and their size)

Also, does this situation not happen on a small VM?
What is the network bandwidth between your cluster and the NFS backup target?

Thanks!

**Comment by dseralathan** [comment]
We have 35 TB single (raid 5 -7TB x 6 Disks) , bandwidth of 10 Gig ethernet per node ( 4 node cluster) .

NFS Target a a OEL 7 VM with 5 TB disk from V-Center .

**Comment by dseralathan** [comment]
@Vicente-Cheng  can you help to get a clear clarity how the backup & restore works, we noticed in longhorn for two clusters have the same backup volumes. if we delete them from longhorn cannot we restore the VM ?

**Comment by dseralathan** [comment]
@Vicente-Cheng  bandwidth we have 10Gig nic on both source and target .
VM disk size are 2 TB each 

in longhorn the volumes are reflected on backup  at 300 secs interval as per settings

**Comment by Vicente-Cheng** [comment]
Hi @dseralathan, Thanks for the ping again (Also sorry for I missed it). I will update your questions ASAP!

> in longhorn the volumes are reflected on backup at 300 secs interval as per settings

Could you describe in more detail your backup flow (operations)?
Thanks!!

**Comment by dseralathan** [comment]
We have same  NFS target for two clusters . On one cluster I am taking backup and its getting late to get reflect on another cluster . eg : in below screenshots a backup name called test-deva-backup ( 50 GB +100 GB)   is not reflected quick on the second cluster 

<img width="618" alt="Screen Shot 2023-01-09 at 11 18 55 AM" src="https://user-images.githubusercontent.com/117767598/211389921-70eb84b4-0f6d-4e59-ae44-b34b06088904.png">
<img width="647" alt="Screen Shot 2023-01-09 at 11 19 11 AM" src="https://user-images.githubusercontent.com/117767598/211389985-67983551-ad07-45a4-b979-e391c345ab6b.png">

**Comment by dseralathan** [comment]
@Vicente-Cheng any idea why the delay  from cluster to cluster

**Comment by Vicente-Cheng** [comment]
hi @dseralathan,
Is your scenario back up to the same NFS target on two clusters.
One shows quickly, and another one will delay, right?

If yes, did you run this behavior at the same time?
Could you share what configuration of your NFS server? (Maybe running protocol V3 or V4, the kernel nfs or nfs-ganesha...etc)

Thanks!

**Comment by dseralathan** [comment]
My NFS server is a  nfs V4 with OEL 7.9 ..
