### ISSUE TITLE
[Not able to edit VM via Terraform - Storage Class issue]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3254]
Hi Team,

We have created the VM in harvester with terraform but later when we tried to add the resources in that VM via terraform, its not allowing to edit it and getting below error

╷
│ Error: the storage_class_name of an image can only be defined during image creation
│
│   with harvester_virtualmachine.vm["kubemaster12.p21"],
│   on resource.tf line 1, in resource "harvester_virtualmachine" "vm":
│    1: resource "harvester_virtualmachine" "vm" {

We didn't specify any storage class in Terraform Code but we added new Storage class in UI and made that one as default.
How we can fix it.

Harvester Version - v1.1.1
Hardware :- Dell C6420

**Comment by Vicente-Cheng** [comment]
hi @midhunthampi, 
This is duplicated with https://github.com/harvester/harvester/issues/3248
You can check on the above issues. (There is a WIP PR)

**Comment by guangbochen** [comment]
close as duplicate with https://github.com/harvester/harvester/issues/3248
