### ISSUE TITLE
[Doc] How to verify potential data corruption of Harvester VMs

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3258]
**Is your feature request related to a problem? Please describe.**
The best would be to provide some sort of step by step guide on how to stop all VMS, attach their volumes on a harvester node and then do fs check agains them.. problem I see is that not all fs check tools might be installed on the harvester nodes.. (verification of the filesystem from within the VM might not be easy as you might need to dismount the root FS to repair)
And check / repair guideline should also include backup and restore / snapshot steps.

**Describe the solution you'd like**
Maybe the steps will be
-> unmount the problematic volume
-> check by fsck
-> backup the volume
-> fix by fsck to see if it can be fixed
-> if not fixable, check the replicas or something at longhorn level

**Describe alternatives you've considered**
References:
- https://longhorn.io/kb/troubleshooting-volume-filesystem-corruption/#solution

**Additional context**
Related Issue: https://github.com/harvester/harvester/issues/2906

**Comment by Martin-Weiss** [comment]
This also needs to handle all filesystems that potentially can exist in VMs
- BTRFS
- XFS
- EXT2/3/4
- NTFS

And the check and repair tools used need to be in the right versions corresponding to the VMs versions dealing with this filesystems,

And this also needs to deal properly with volumes provisioned via the Harvester-CSI in case we have kubernetes clusters running on top of Harvester.

**Comment by Vicente-Cheng** [comment]
We already published the related Knowledge Base on [here](https://harvesterhci.io/kb/scan-and-repair-vm-root-filesystem), so I closed this issue.
If any concerns, feel free to reopen this or create another issue.
