### ISSUE TITLE
[FEATURE] QA Cluster Improvements

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#3264]
**Describe the solution you'd like**
Implement a scenario with "aging" cluster that has some load and VMs being moved around. 

**Is your feature request related to a problem? Please describe.**
Things are working with one node when the load is static, but when starting to scale out or migrating VMs there are various errors and issues. This may be due to the fact that we test with a fresh environment each time.

**Steps to completion**

- [x] Setup Harvester utility node

- [x] Setup DNS

- [x] Setup proxy

- [ ] Setup Harvester workload/Rancher nodes

- [ ] Setup private registry

- [ ] Setup load balancer

- [ ] Setup Rancher cluster

**Comment by khushboo-rancher** [comment]
We are working on it. We are targeting to get it done before 1.2

**Comment by noahgildersleeve** [comment]
This has been addressed with increased [air-gap automation testing](https://github.com/harvester/tests/issues/967). Closing as N/A anymore.
