### ISSUE TITLE
[FEATURE] Support 2 Node / Witness Configuration

### ISSUE THREAD

**Issue by rebeccazzzz** [harvester/harvester#3266]
**Describe the solution you'd like**
Enable Harvester to be deployed on 2 Nodes with HA, or allow a Witness server to be a tie-breaker or etcd node.

**Is your feature request related to a problem? Please describe.**
We can only support/allow 3 nodes due to quorum and the Kubernetes architecture.

We would like a two-node configuration, to minimize footprint and keep costs low while having an additional node for HA.

**Describe alternatives you've considered**
Workaround:
1. During the installation, allow the node to work the role of master, but not a worker.
2. Allow configuration after the cluster is up is also needed if the user doesn't configure during installation or changes their mind.
3. Allow manual pick and promote, instead always promote automatically.

**Comment by Vicente-Cheng** [comment]
This issue has the same purpose as #4840, so we can test it together.

**Comment by albinsun** [comment]
Test plan refer to HEP
https://github.com/harvester/harvester/blob/v1.3.0-rc1/enhancements/20231113-witness-node-support.md#note-optional.

## Environment
* Harvester
  * Version: `v1.3.0-rc1`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
    * Default: 8C / 16G / 500G
    * Witness: 4C / 8G / 500G
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.6`
  * Profile: rancher-vcluster


## Checks
1. Node role and behavior
   * Should be only one witness node.
   * When user config more than 1 witness node, it will be regard as Mangement.
1. Basic functions: Creat a VM with some data
   1. Reboot -> Data check
   9. Restore -> Data check
1. `rancher-vcluster` can be created and works as well.
1. Can adding 4th node
3. Can drop witness node


## Scenarios

> Please refer following comments for detail test steps 

### Positive
1. D -> D -> W :heavy_check_mark: 
   * #5029
     -> Known UI issue but not relate to witness
2. D -> W -> D :heavy_check_mark: 
   * #5029
     -> Known UI issue but not relate to witness 
3. D -> W -> W :heavy_check_mark: 
   * #5070
     -> Fixed
   * #5071
     -> Can NOT reproduce, should be env. issue.

### Negtive
1. <details>
   <summary> First node should NOT be Witness :heavy_check_mark: 
   </summary>
   
   Config witness and system setup as management.
   ![image](https://github.com/harvester/harvester/assets/2773781/8a927ef3-307e-4ed6-aadd-d71f41f9a7a5)
   </details>

### Upgrade
1. `v1.3.0-rc1` -> `v1.3.0-rc2` :question: TODO
   > Wait `v1.3.0-rc2`

**Comment by albinsun** [comment]
Provide test Result for scenario 1 (DDW), basically works fine.


## Steps
1. Setup DDW cluster
   <details>

   1st node
   ![image](https://github.com/harvester/harvester/assets/2773781/d125fe7a-25f5-457d-8fd0-882fba0243ba)
   ![image](https://github.com/harvester/harvester/assets/2773781/eee96d47-1ae9-4cff-8f24-1a9343d40c43)

   2nd node (Currently compute node)
   ![image](https://github.com/harvester/harvester/assets/2773781/f2bb5362-9029-4ee3-a8b5-35af2bc10d5d)
   ![image](https://github.com/harvester/harvester/assets/2773781/53121fb0-89b6-4a7a-8bc7-9db41441b1b8)

   3rd node
   ![image](https://github.com/harvester/harvester/assets/2773781/0aa70dba-5d7b-4fcf-935c-1b4fad505ae3)
   ![image](https://github.com/harvester/harvester/assets/2773781/64b73fa6-1811-4008-aa69-5b3bc8c7948a)
   ![image](https://github.com/harvester/harvester/assets/2773781/1b43dd2c-3b7f-4f2d-8fa6-ffd2f4814b00)
   </details>


1. CHECK
   * <details>
     <summary> Node roles: Should be only one witness node. :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/162c20d4-10f7-4634-8f96-5513e91d0f4b)
     </details>

   * <details>
     <summary> Default storage class harvester-longhorn's replica should NOT satisfied when 3 nodes witness mode (2 defauls + 1 witness, not achieve quorum) :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d8d7fa01-c3ac-49cb-8afa-08df42c6a2dd)
     ![image](https://github.com/harvester/harvester/assets/2773781/fc97a1d5-d3c5-409a-a0b4-e76d2ab7e80c)
     ![image](https://github.com/harvester/harvester/assets/2773781/b592a9c1-b5f8-4ca9-8f02-351fa6000200)
     </details>
     
   * <details>
     <summary> Can NOT migrate VM to witness node :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0a10825d-91e9-4d1c-993d-89c84708d2fa)
     ![image](https://github.com/harvester/harvester/assets/2773781/810f1402-3ca6-4091-80aa-3745575786a8)
     </details>
     
   * <details>
     <summary> Reboot and data check :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9f38002e-53bd-4e77-8796-ac4a8a06463a)
     ![image](https://github.com/harvester/harvester/assets/2773781/c6d8e33a-254d-4f2f-bb97-2abefefb9068)
     ![image](https://github.com/harvester/harvester/assets/2773781/37bfa7d8-6424-4207-8df8-06e65bc37475)
     Both not migrate to witness node
     ![image](https://github.com/harvester/harvester/assets/2773781/292bb45b-48e9-411e-8ca3-1d8fdb14fbb2)
     ![image](https://github.com/harvester/harvester/assets/2773781/97db734f-f8f7-4065-93b2-84b4ef088e60)
     </details>

   * <details>
     <summary> Snapshot -> Restore Existing -> Data check  :warning: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/67b947a7-487e-455f-8714-70a33b3d6a06)
     ![image](https://github.com/harvester/harvester/assets/2773781/97fc3354-1536-4d4f-813d-26d10efe3c84)
     ![image](https://github.com/harvester/harvester/assets/2773781/ae3c7faf-61cb-4ab2-b867-ebbfe611e608)
     ![image](https://github.com/harvester/harvester/assets/2773781/e6d4e8a7-386f-4bbc-9996-03cde5a010d9)
     </details>

     > Restore filew show progress 0%, need check normal setup hit this too or not.

   * <details>
     <summary> rancher-vcluster works for basic operations :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d505eb8f-fe52-4081-a129-57bfce542bbf)
     ![image](https://github.com/harvester/harvester/assets/2773781/3081f952-91f1-4732-a436-16ad4b2de0d7)
     ![image](https://github.com/harvester/harvester/assets/2773781/6766f216-5b25-4657-b96d-9fd0f47963e2)
     Import Harvester
     ![image](https://github.com/harvester/harvester/assets/2773781/fc4633ee-d12a-47be-9739-cb86ada43240)

     Create RKE2 cluster
     ![image](https://github.com/harvester/harvester/assets/2773781/bab42425-1c7b-45f3-b926-d851401c95a8)
     ![image](https://github.com/harvester/harvester/assets/2773781/2bda7f6e-8d60-47b0-ae19-53c380c701a4)


     Deploy Pod and LB
     ![image](https://github.com/harvester/harvester/assets/2773781/bb861606-dada-45f0-8bf6-3fade9a048c8)
     ![image](https://github.com/harvester/harvester/assets/2773781/34079f99-608b-4a59-a773-e5554024ccb0)
     </details>
     

1. Setup 4th D node
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/d9c7dcd5-e313-47e3-91b0-4cffe08c8c47)
   Compute Node
   ![image](https://github.com/harvester/harvester/assets/2773781/9df72c96-1456-4c50-84ab-0125afed12ac)
   </details>



1. CHECK
   * <details>
     <summary> Node roles: 4th node should be compute node and cluster has only one witness node. :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/266c9c85-70db-492e-8c3a-d7782c5d1ac3)
     </details>

   * <details>
     <summary> Default storage class harvester-longhorn's replica should be satisfied when 4 nodes witness mode (3 defauls + 1 witness, achieve quorum) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/02312af7-2db6-48c6-98e3-243d11feab56)
     ![image](https://github.com/harvester/harvester/assets/2773781/868a4665-c665-4366-a858-45f9dfbc98d7)
     </details>
          
   * <details>
     <summary> Reboot and data check :warning: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/82447855-1e0a-453e-803e-4cd8580d4ea2)
     ![image](https://github.com/harvester/harvester/assets/2773781/d56f65cb-99f9-48c4-982b-19abd44ca2e4)
     Rebooted on new node3 but fail
     ![image](https://github.com/harvester/harvester/assets/2773781/767429e2-391c-49d4-b5da-c3cffa98989e)
     
     [supportbundle_ext4error_after_vm_restart_2024-01-29T13-29-03Z.zip](https://github.com/harvester/harvester/files/14085095/supportbundle_ext4error_after_vm_restart_2024-01-29T13-29-03Z.zip)
     </details>

     > Reboot fail with EXT4-fs error (low reproducibility)

   * <details>
     <summary> Snapshot -> Restore Existing -> Data check  :heavy_check_mark: 
     </summary>

     Restore replace
     ![image](https://github.com/harvester/harvester/assets/2773781/a864eac9-a91c-4093-9240-4f9859037ab8)
     Data check ok
     ![image](https://github.com/harvester/harvester/assets/2773781/24e00b75-0718-44a6-8b79-d2ed5346fb25)     
     </details>

   * <details>
     <summary> rancher-vcluster: Deploy Pod and LB still works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/03c8c41f-bcb5-44cf-aa6f-19c741e02e18)
     ![image](https://github.com/harvester/harvester/assets/2773781/2b5d676d-85b7-4031-bd4a-6e7d946eb45f)     
     </details>

1. Drop W node
   <details>

   * Maintenance
![image](https://github.com/harvester/harvester/assets/2773781/09fc98c7-2550-481e-9982-d69af7552e03)
   Delete
   ![image](https://github.com/harvester/harvester/assets/2773781/a8401197-70f3-4028-ac94-8acc9c4c2df1)
   ![image](https://github.com/harvester/harvester/assets/2773781/337a2e6e-7829-42a2-b93c-6982f66ac4b5)
   </details>



1. CHECK
   * <details>
     <summary> Node roles: 3 nodes are all master nodes, no witness node. :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cc6c25da-e0a4-4d42-87b7-6b1cf3794e85)
     </details>

   * <details>
     <summary> Default storage class harvester-longhorn's replica should be satisfied (3 defauls, achieve quorum) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/4d12aacf-e13d-403a-acbe-5a3916ccfc22)
    ![image](https://github.com/harvester/harvester/assets/2773781/ce5f8032-384c-4488-af07-30031d4c39a2)
     </details>
          
   * <details>
     <summary> Reboot and data check :warning: 
     </summary>
         
     ![image](https://github.com/harvester/harvester/assets/2773781/18cfd7cf-638d-4127-8891-bc14d8249bca)
     ![image](https://github.com/harvester/harvester/assets/2773781/7f8a9b22-e9b3-485f-a71d-79ea2cfcfed0)
     ![image](https://github.com/harvester/harvester/assets/2773781/85377dc3-acec-431f-b89b-958898e964e0)
     [supportbundle_ext4error_after_vm_restart_2_2024-01-29T14-50-52Z.zip](https://github.com/harvester/harvester/files/14085741/supportbundle_ext4error_after_vm_restart_2_2024-01-29T14-50-52Z.zip)
     </details>

     > Reboot fail with EXT4-fs error (low reproducibility)

   * <details>
     <summary> Snapshot -> Restore Existing -> Data check  :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/160fd029-ddbc-4a04-82e6-11dcb0a46665)
     ![image](https://github.com/harvester/harvester/assets/2773781/bffc3ab6-2913-48ac-a5ec-372e364a2abc)
     </details>

   * <details>
     <summary> rancher-vcluster: Deploy Pod and LB still works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/3424370a-3f47-47dd-8225-ee8080df8e01)
     </details>

**Comment by albinsun** [comment]
Provide test Result for scenario 2 (DWD), basically works fine.

## Test Steps
1. Setup 3 nodes cluster (Default, Witness, Default)
   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c8f1f94f-bbed-4b77-a9a8-0d49aa129a7a)
     </details>
 
   * <details>
     <summary> <b>node-1</b> is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7a647c0d-4264-4b72-9b19-43ce5d4fd77b)
     </details>

   * <details>
     <summary> <b>node-2</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6f10757e-232b-49c6-8680-8c3fa40591a7)
     </details>

   * <details>
     <summary> Longhorn should have 2 nodes :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f9e04229-ff66-4d67-aaba-cd13415571ec)
     </details>


1. VM Operations
   * <details>
     <summary> Create VM and test data :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/280695cb-0763-4573-a610-87a2c6713c9d)
     </details>

     > :warning: VM got IP but not shown in UI
     
   * <details>
     <summary> Volume should be <code>Ready</code> but <code>Degraded</code> due to 2 replicas :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a659fce0-371c-425c-8645-1776821f7d29)
     ![image](https://github.com/harvester/harvester/assets/2773781/bcfb210c-a03b-4bb4-a067-a5578b4a1ec2)
     </details>

   * <details>
     <summary> Stop VM and take snapshot :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a7f49a7e-922e-401c-8ea5-e03853adb4e3)
     </details>

   * <details>
     <summary> Restore VM :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/696b0eb5-7029-4beb-9dd4-be57c726e33b)
     check data
     ![image](https://github.com/harvester/harvester/assets/2773781/0e9a4db7-6aad-493e-97fc-f2a28da298b3)
     </details>

   * <details>
     <summary> Restart VM :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/4da39d09-2789-4436-85d6-939d3d131092)
     check data
     ![image](https://github.com/harvester/harvester/assets/2773781/691ad1a4-f386-444f-9b09-b77311517554)
     </details>


1. Rancher by `rancher-vcluster`
   * <details>
     <summary> Enable <b>rancher-vcluster</b> and can access Rancher :heavy_check_mark:  
     </summary>
     
     Install
     ![image](https://github.com/harvester/harvester/assets/2773781/769e71c2-296b-436c-8b14-10e1250d184f)
     Enable
     ![image](https://github.com/harvester/harvester/assets/2773781/84add497-93bd-4ae2-8aa8-b5ff9eda4681)
     ![image](https://github.com/harvester/harvester/assets/2773781/13aeb30e-664c-4d33-9813-6d99c282a298)
     ![image](https://github.com/harvester/harvester/assets/2773781/e1f6eefa-c208-406d-a11b-5131d7278cf0)
     </details>
     
   * <details>
     <summary> Import Harvester to Rancher :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d6a460c6-2056-4d62-bbc4-632ceec9b982)
     </details>

   * <details>
     <summary> Create RKE2 cluster :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2fc08f90-2d03-4cf4-b019-f1aca6214aaf)
     ![image](https://github.com/harvester/harvester/assets/2773781/788d551a-d7ee-40e9-b581-b667af105740)
     </details>

   * <details>
     <summary> Deploy Nginx w/ pvc and LB :heavy_check_mark: 
     </summary>
     
     Deployment
     ![image](https://github.com/harvester/harvester/assets/2773781/8facaec3-db13-4031-99fe-094c47b652e2)
     PVC is mount
     ![image](https://github.com/harvester/harvester/assets/2773781/24f070e9-81fc-441d-97c2-936150f97dee)
     LB works
     ![image](https://github.com/harvester/harvester/assets/2773781/6dd7a1d0-f6c6-42df-9dcb-0e0499aa325b)
     </details>


1. Join 4th node (Default)
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/92665e44-22df-4e0f-be5b-e53a256d4c5e)
     </details>
     
   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b6db7b7a-d43b-4f73-af76-1ba2dbc2dcc1)
     </details>
 
   * <details>
     <summary> <b>node-1</b> is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f9e09c96-8c74-401c-bc87-43375b570c50)
     </details>

   * <details>
     <summary> <b>node-2</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0cc20b4a-ff50-4996-a533-9f4a3f342e3b)
     </details>

   * <details>
     <summary> <b>node-3</b> is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/da84bd97-ba14-4c38-8007-452ff455f23d)
     </details>

   * <details>
     <summary> Longhorn should have 3 nodes (node-0, node-2 and node-3) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/de37a334-e624-4544-a6eb-dea3c600f2fd)
     </details>

1. Check
   * <details>
     <summary> Restart VM :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/606f04a3-d4b0-46d9-b727-194e41db46c5)
     </details>

   * <details>
     <summary> Stop and Restore VM :heavy_check_mark: 
     </summary>
     
     Before
     ![image](https://github.com/harvester/harvester/assets/2773781/f0befe4c-8b2d-462b-a2ef-bd34079745c6)
     Restore
     ![image](https://github.com/harvester/harvester/assets/2773781/194572f3-39f8-48e4-9925-d7a44f089142)
     ![image](https://github.com/harvester/harvester/assets/2773781/30c68538-5a3a-4cd6-841c-7c5ccfc57963)
     </details>


   * <details>
     <summary> Rancher and Nginx deployment still works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6087bd34-214d-49b7-9fcb-bea6460111db)
     ![image](https://github.com/harvester/harvester/assets/2773781/ac0bc21f-22c5-4f87-9641-4e499de57e07)
     </details>


1. Drop Witness node-1
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
     
     Maintenance and Delete node-1
     ![image](https://github.com/harvester/harvester/assets/2773781/45ba16c2-bb0c-4e68-b076-3cf97aa6fe76)
     ![image](https://github.com/harvester/harvester/assets/2773781/25d101b2-c759-46f2-8b6d-5c62b9f8315b)
     </details>

   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7ac72cd6-a71c-4d1e-9544-19005d26b911)
     </details>
 
   * <details>
     <summary> <b>node-2</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/13bb618c-192c-49e1-b531-f87bbfc10760)
     </details>

   * <details>
     <summary> <b>node-3</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/1a54715e-0f3f-46ea-9885-73145d6337df)
     </details>

   * <details>
     <summary> Longhorn should have 3 nodes :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cc5ffbcd-ccf4-4cd7-aebb-8c35f17cb7f9)
     </details>


1. Check
   * <details>
     <summary> Restart VM :heavy_check_mark: 
     </summary>
     
     Before
     ![image](https://github.com/harvester/harvester/assets/2773781/af824068-2847-4086-9551-43be1d565034)
     Restart
     ![image](https://github.com/harvester/harvester/assets/2773781/c71b7943-4cad-4092-97ec-8677476ee87f)
     Data check
     ![image](https://github.com/harvester/harvester/assets/2773781/0e92c54a-dd1b-4380-b319-c9bfa042d1c8)
     </details>

   * <details>
     <summary> Stop and Restore VM :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/fb67d15a-70a0-43ee-a889-10ae229aba8d)
     ![image](https://github.com/harvester/harvester/assets/2773781/0fd3adf7-7d2f-42fe-91d4-3c2dc9406652)
     </details>

   * <details>
     <summary> Nginx still works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2411c4f1-391a-4e84-ad8c-44f67a30c243)
     ![image](https://github.com/harvester/harvester/assets/2773781/0550636f-8c94-4b6a-abaa-7a3aba833652)
     </details>

**Comment by albinsun** [comment]
For scenario 3 (DWW), we hit node behavior issue.
Detail please refer to [[BUG] Second witness node's role is Management but NOT behave like management node #5070](https://github.com/harvester/harvester/issues/5070#top)

**Comment by albinsun** [comment]
Basic scenarios works fine but still need to verify upgrade, move back to ReadyForTesting temporaily.

**Comment by Vicente-Cheng** [comment]
Update the case DWW expectation:
The new mechanism (for DWW configuration) is that the promote controller will not count the other witness nodes into the management node number. So, this case does not have any promoted job. This means we still have one management node (1st default node). You need to add 4th node as default or management role to trigger promote.

related PR: https://github.com/harvester/harvester/pull/5082

**Comment by albinsun** [comment]
Provide test Result for scenario 3 (DWE), basically works fine.
Detail: https://github.com/harvester/harvester/issues/5070#issuecomment-1929783891

Remaining `upgrade` scenario will be test as we have `v1.3.0-rc2+`.

**Comment by albinsun** [comment]
Provide test Result for upgrade scenario.
We found witness node will timeout fail when preloading image since we try it 3 rounds but this only happen on the etcd node.

Please help to check, thanks.


## TC1: Clean DDW `v1.3.0-rc2` -> `v1.3.0-rc3`
1. Setup DDW cluster using `v1.3.0-rc2` :heavy_check_mark: 
   * Environment: QEMU/KVM, 3 nodes (8C/16G/500G)
   * <details>

     ![image](https://github.com/harvester/harvester/assets/2773781/54e6be4a-fddb-4603-947e-6223f84af584)
     </details>
3. Extending job time out to `7200`
   Ref. https://github.com/harvester/harvester/issues/2894#issuecomment-1274069690

2. Perform a airgapped upgrade to `v1.3.0-rc3` :x: ${\color{red} \text{Witness node preloading image timed out}}$
   * Reproducibility: 3/3
   * Upgrade log: [hvst-upgrade-jnhpk-upgradelog-archive-2024-02-22T00-51-53Z.zip](https://github.com/harvester/harvester/files/14367087/hvst-upgrade-jnhpk-upgradelog-archive-2024-02-22T00-51-53Z.zip)

   * Support bundle: [supportbundle_002bb4fc-a3f3-4a75-bae8-b045cbeaec97_2024-02-22T00-53-54Z.zip](https://github.com/harvester/harvester/files/14367088/supportbundle_002bb4fc-a3f3-4a75-bae8-b045cbeaec97_2024-02-22T00-53-54Z.zip)

   * <details open>
  
     ![image](https://github.com/harvester/harvester/assets/2773781/05c97aac-ef69-4218-a7de-9f6a65e1cbab)
     </details>


## TC2: DDW `v1.3.0-rc2` with VM and `rancher-vcluster` -> `v1.3.0-rc3` (TODO)
1. Setup DDW cluster using `v1.3.0-rc2`
   * <details>
     <summary> Cluster is Active 
     </summary>
   
     </details>

   * <details>
     <summary> Create a replica = 2 storeate class and set as default 
     </summary>
     
     </details>

1. Basic operations
   * <details>
     <summary> Create a VM with extra volume and data 
     </summary>

     </details>

   * <details>
     <summary> RKE2 cluster via <code>rancher-vcluster</code> 
     </summary>
     

     Deployment and PVC
     LB works
     </details>

1. Upgrade cluster to `v1.3.0-rc3`
   * <details>
     <summary> Can not upgrade if having degraded volumes 
     </summary>
     
     </details>
     
   * <details>
     <summary> Upgrade successfully 
     </summary>

     </details>
     
   * <details>
     <summary> VM still works 
     </summary>

     </details>
     
   * <details>
     <summary> <code>rancher-vcluster</code> still works
     </summary>
     
     </details>

## TC3: DW `v1.3.0-rc2` -> `v1.3.0-rc3` -> Join D (TODO)

## TC4: DD `v1.2.1` -> `v1.3.0-rc3` -> Join W (TODO)

**Comment by ibrokethecloud** [comment]
I was able to reproduce the issue, and this is being caused as the launcher pod is unable to tolerate the etcd taint:
```
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  14s   default-scheduler  0/3 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/etcd: true}, 2 node(s) didn't match Pod's node
 affinity/selector. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling..
```

**Comment by ibrokethecloud** [comment]
already addressed by: https://github.com/harvester/harvester/pull/5202

fixes should already be available in master.

**Comment by albinsun** [comment]
Provide test Result for upgrade scenario on `v1.3.0-rc4`, close as done.



## Environment
* Harvester
  * Version: `v1.2-a822a3a4-head` -> `v1.3.0-rc4`
  * Profile: QEMU/KVM, 3 nodes with witness (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.8.2`
  * Profile: rancher-vcluster

## Note
1. Following https://github.com/harvester/harvester/pull/5208#issue-2150394040 to annotate upgrade after triggering.


## Steps 
1. Create a 2 nodes <code>v1.2-head</code> cluster
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/97b59f89-debe-4e6f-a008-ab8ea568e158)
     </details>

   * <details>
     <summary> Make default storage class <code>replicas=2</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/d88e3ad3-63a7-4453-82fc-90d32b10fc3a)
   </details>
   
1. Create RKE2 cluster with **rancher-vcluster**
   * <details>
     <summary> deployments works :heavy_check_mark: 
     </summary>

     harvester apps
     ![image](https://github.com/harvester/harvester/assets/2773781/27198b2c-4f74-4937-a06d-d2eff03936ec)
     Nginx deployment
     ![image](https://github.com/harvester/harvester/assets/2773781/fd3afd8f-6d33-4cc1-9e58-200c7885f50f)
     </details>

   * <details>
     <summary> Load balancer works :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/c20b7321-4e71-4fd5-a502-c5b4392d5c04)
     </details>


1. Upgrade to `v1.3.0-rc4`
   * <details>
     <summary> Upgrade successfully  :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/72d246a0-db42-4eb9-be7d-d620d4dafcab)
     ![image](https://github.com/harvester/harvester/assets/2773781/80db5402-f133-47ca-a948-b63a5ef2435a)
     </details>
   * <details>
     <summary> RKE2 cluster still works  :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/0ee066c6-300c-4f06-9190-3016621665e9)
     ![image](https://github.com/harvester/harvester/assets/2773781/4589dfd2-9c13-4090-b502-4a7cb1eb43f7)
     </details>

1. Join witness **node-2**
   * <details>
     <summary> Cluster is Active, <b>node-1</b> is promoted. :heavy_check_mark: 
     </summary>

     Before
     ![image](https://github.com/harvester/harvester/assets/2773781/bad0963b-b6b6-48aa-b4a8-a3af7dd23131)
     After
     ![image](https://github.com/harvester/harvester/assets/2773781/14f73902-1277-4e58-83c2-05ee792f2045)
     </details>

   * <details>
     <summary> RKE2 cluster still works :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/78042a92-29b3-417e-83d6-9899a9ac8b1a)
     ![image](https://github.com/harvester/harvester/assets/2773781/85313e83-056c-40a7-937a-25d389ba98de)
     ![image](https://github.com/harvester/harvester/assets/2773781/3b70b8a7-7ea5-4fa8-895b-2785ead1683c)
     </details>


1. Self upgrade to `v1.3.0-rc4`
   * <details>
     <summary> Upgrade successfully  :heavy_check_mark:  
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/7446db95-defd-4061-909f-687d66608368)
     ![image](https://github.com/harvester/harvester/assets/2773781/5b1ec886-e04a-4eb2-b6e0-f5470f8abe30)
     </details>
   * <details>
     <summary> RKE2 cluster still works :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/77549d9d-051c-4931-8a8b-1d753738b4bd)
     ![image](https://github.com/harvester/harvester/assets/2773781/e6abd648-4511-4f73-82f8-f65e03ecf9e3)
     </details>
