### ISSUE TITLE
[BUG] Volume created by the Harvester CSI driver gets deleted after RKE2 node reprovisioning

### ISSUE THREAD

**Issue by brian9206** [harvester/harvester#3272]
**Describe the bug**
After reprovisioning all RKE2 nodes by editing the disk size in Cluster Management in Rancher. The PV in the RKE2 cluster is still there, but the underlying volume in the Harvester Longhorn is disappeared.

**To Reproduce**
1. Create a RKE2 cluster in the Harvester cluster in Rancher Cluster Management
2. Install official elasticsearch helm chart. It will use the "harvester" StorageClass to create PVC by default
3. After getting the chart running, go to Rancher > Cluster Management > Edit Config
4. Change disk size
5. Wait for the reprovisioning
6. Go to kubectl shell of the RKE2 cluster. run: `kubectl describe pod elasticsearch-master-0 -n elastic`. You will see the error message: ` Warning  FailedAttachVolume  77s (x1246 over 26m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-85d99fdf-9a43-4800-b17a-42354d53b1a9" : rpc error: code = Internal desc = Failed to get PVC pvc-85d99fdf-9a43-4800-b17a-42354d53b1a9: persistentvolumeclaims "pvc-85d99fdf-9a43-4800-b17a-42354d53b1a9" not found`
7. Go to Harvester internal longhorn UI `https://<your harvester VIP>/dashboard/c/local/longhorn` > Longhorn > Volume, and you cannot find the volume

**Expected behavior**
The volume in the Harvester longhorn should not be deleted

**Environment**
 - Harvester ISO version: 1.1.0

**Comment by dmytrobabeshko** [comment]
I see no big reaction, although it seems really critical to me.

We faced exactly the same issue with Harvester v1.1.0 and RKE2 not long after the release of v1.1.0.
My company tested Harvester with production workloads in our internal environment on PowerEdge R740.
We had an RKE2 downstream cluster of about 10 worker nodes. 3 replicas for all Longhorn PVCs. After the configuration change in Rancher, it started to recreate worker VMs one by one. During this, all PVCs of the entire RKE2 cluster were eventually deleted during reprovisioning. You see PVC and PV resources in the RKE2 downstream cluster. But none of the workloads can start because the volume can't be attached. If you open Longhorn in the Harvester cluster it doesn't show any volume available. Longhorn logs show that all volumes were deleted via API. 

Unfortunately, we had to give up on Harvester and switch to another mature HCI solution after this.

**Comment by futuretea** [comment]
@brian9206 @dmitrybabeshko Sorry for the late reply. I think we may make an enhancement to node driver. When deleting the volume of the guest cluster node, we will make a judgment and keep the pvc created by the user. We can try it and see if there are any other problems. CC @guangbochen

**Comment by futuretea** [comment]
**Problem**
the pvc created by the harvester csi driver in the guest cluster would be deleted in the host cluster after editing/deleting the guest cluster.

**Cause**
1. If a user uses pvc in the guest cluster, the pvc is mounted to the guest node (a vm in host Harvester clustet) as a hotplug disk by harvester csi driver.
2. After the guest cluster is edited, rancher always creates a new guest node and deletes the old one.
3. When node driver deletes the guest node and all pvcs attached to the guest node will be deleted.

**Discuss**
I would like to make an enhancement to harvester  node driver: do not automatically delete pvc if it is hotplugable.
And the UI maybe can display some information about the guest cluster on the host Harvester volume page.

**Comment by bk201** [comment]
To add a release note: we need to advise user to upgrade the node-driver to [v0.6.3](https://github.com/harvester/docker-machine-driver-harvester/releases/tag/v0.6.3)

**Comment by lanfon72** [comment]
Tested this bug be resolved on Rancher **v2.6.11** with the specific Harvester Node Driver version.


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.1.2-rc3** and **v1.1.1**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6.11**

### Verify Steps:
- Same as **Test Plan** described in https://github.com/harvester/docker-machine-driver-harvester/pull/44#issue-1604039754

**Comment by guangbochen** [comment]
@lanfon72 can u verify again using Rancher v2.7.2 since its built-in Harvester node driver is updated to the desired version.

**Comment by lanfon72** [comment]
Tested this bug be resolved on Rancher **v2.7.2** with the builtin Harvester Node Driver(v0.6.3).


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1-cff1d5b5-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7.2**

### Verify Steps:
- Same as **Test Plan** described in https://github.com/harvester/docker-machine-driver-harvester/pull/44#issue-1604039754
