### ISSUE TITLE
[BUG] upgrade fail , node cordon every 10min.  rebuild the cluster

### ISSUE THREAD

**Issue by fanlix** [harvester/harvester#3276]
**Describe the bug**
* cluster of 2 nodes.
* upgrade from v1.0.2 to v1.0.3
* download by air-gapped method
*  master-node data-nic changed. 
* start upgrade by webui button

**To Reproduce**
first try: 
* all ok until master-node stuck at node state (Phase 4):  **pre-draining**. 
* wait hours. 
* search pages. found a longhorn volume problem: 2 node but replica=3. fix by hand change.
* stop the upgrade by `kubectl delete -n harvester-system upgrade.harvesterhci.io/hvst-upgrade-xxxx `

second try:
* start the upgrade again
* stuck at node state (Phase 4): **images preloaded**
* wait one hour
```
$ kubectl get jobs -n harvester-system -l harvesterhci.io/upgradeComponent=node
No resources found in harvester-system namespace.
```

more tries all stuck at "images preloaded"

**support bundle**
sent by email by name "issue 3276 supportbundle file"
* supportbundle_0ff7ea84-929b-458c-832d-d5aba4ccd359_2022-12-12T18-09-27Z.zip

**Environment**
 - Harvester ISO version:  v1.0.2 
 - Underlying Infrastructure: Baremetal with Dell  R440 & R750

**some not fixed**
*  master node keep dropping to **cordoned** state every 10min. cant find any event reason.  
*  too many longhorn error events. should be the result other than the reason
*  upgrade-repo-hvst-upgrade-vx5wn  readiness probe faild: get http://10.52.0.191:80/harvester-iso/harvester-release.yaml : dail connect no route to host 
*  this pod always want migrate from master node to  slave node. but my 2 machine not same cpu. stuck.  ( I stop/start/bind this vm to slave node,  then met same error : "no route to host"
* the volume virt-launcher-upgrade-repo-hvst-upgrade-26bw7-xxx actual size is 0
*  after stop the upgrade .   webui show system at v1.0.3 version.    but kubectl show node at v1.0.2 version.

**Question**
* how to stop node from keep dropping to cordoned state? (webui & kubectl uncordon works for minutes only).  this is a production server
* what cause upgrade failure. 
* how to upgrade to v1.0.3, v1.1.1

**Comment by fanlix** [comment]
related issues
- #3041
- #2088

```
hv:~ # kubectl get node
NAME    STATUS   ROLES                       AGE    VERSION
hv      Ready    control-plane,etcd,master   190d   v1.21.11+rke2r1
hv-n1   Ready    <none>                      140d   v1.21.11+rke2r1
hv:~ # kubectl get clusters.cluster.x-k8s.io local -n fleet-local
NAME    PHASE          AGE    VERSION
local   Provisioning   190d
hv:~ # kubectl get bundles -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; configmap.v1 longhorn-system/longhorn-storageclass missing
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-monitoring                        1/1
fleet-local   mcc-rancher-monitoring-crd                    1/1
hv:~ # kubectl get bundledeployment -A
NAMESPACE                                NAME                                          DEPLOYED   MONITORED   STATUS
cluster-fleet-local-local-1a3d67d0a899   fleet-agent-local                             True       True
cluster-fleet-local-local-1a3d67d0a899   local-managed-system-agent                    True       True
cluster-fleet-local-local-1a3d67d0a899   mcc-harvester                                 True       True        configmap.v1 longhorn-system/longhorn-storageclass missing
cluster-fleet-local-local-1a3d67d0a899   mcc-harvester-crd                             True       True
cluster-fleet-local-local-1a3d67d0a899   mcc-local-managed-system-upgrade-controller   True       True
cluster-fleet-local-local-1a3d67d0a899   mcc-rancher-monitoring                        True       True
cluster-fleet-local-local-1a3d67d0a899   mcc-rancher-monitoring-crd                    True       True
hv:~ #
hv:~ # kubectl get managedchart harvester -n fleet-local -o yaml
apiVersion: management.cattle.io/v3
kind: ManagedChart
spec:
  chart: harvester
  defaultNamespace: harvester-system
  paused: false
  releaseName: harvester
  repoName: harvester-charts
  targets:
  - clusterName: local
    clusterSelector:
      matchExpressions:
      - key: provisioning.cattle.io/unmanaged-system-agent
        operator: DoesNotExist
```
* https://github.com/longhorn/longhorn/issues/1527

**Comment by bk201** [comment]
@fanlix, the second try won't continue. Because when you delete the first upgrade, the rancher is still in his upgrade cycles.
Could you run `drain-status.sh` here https://github.com/bk201/misc/tree/main/rancher to reveal the current cluster state? This might help resolve the cordon issue. cc @starbops to have an eye on this.

**Comment by fanlix** [comment]
I already rebuilt the whole cluster yesterday, after all I could try and no feedback.

## 10min auto-cordon problem
I didnt find the real reason.  
longhorn has a 5min loop check, apiserver has a 10min loop restart .... these should be the result of cordon. not reason 

after hard reboot master node machine. auto-cordon dissappears. 

## node Provisioning problem
This should be the reason why upgrade stuncks. 
I tried:
* delete related storageclass 
* stop each helm chart upgrading (cannot really stop) 
* hand create a storageclass what helm need
* copy longhorn-storageclass from a new created hv-cluster
* like #2088 , make a new helm chart by deleting xxx-override.yaml, upgrade by hand

all not works.

**Comment by w13915984028** [comment]
@fanlix Do you have new updates, which Harvester release is your cluster running now ?  thanks.

**Comment by fanlix** [comment]
@w13915984028  v1.1.1 now

**Comment by fanlix** [comment]
#3299
