### ISSUE TITLE
Email Config and Test alerts 

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3278]
We have setup email receiver (Receiver in AlertmanagerConfig )for our harvester cluster,  Any idea how we can test the alerts .

**Comment by dseralathan** [comment]
@rebeccazzzz  could you help , will be appreciated

**Comment by ibrokethecloud** [comment]
the alert will be fired when the alert condition is met.

easy way might be to negate the condition you are testing on, for example, change alert to "when vm is running", to ensure alert is generated.
