### ISSUE TITLE
Host Console URL strips colon from SSH URL

### ISSUE THREAD

**Issue by zanewgray** [harvester/harvester#3281]
**Describe the bug**
When an SSH URL (e.g. ssh://node-1.my.lab.net) is used for the console URL for a node, clicking on the Console button results in a browser tab/window with the colon stripped from the URL (e.g. ssh//node-1.my.lab.net).

Using a HTTPS URL does not strip the colon when passing the console URL to a new browser tab/window.

**To Reproduce**
1. Install Harvester on one or more nodes.
2. Choose a node and edit the config.
3. In the Console URL field, enter a SSH URL (e.g. ssh://rancher@10.0.0.2)
4. Save the changes
5. Click on the "Console" button of the adjusted node
6. Observe the URL in the new tab/window

**Expected behavior**
The SSH URL in the resulting browser tab/window should have a colon in it (e.g. ssh://rancher@10.0.0.2 and not ssh//rancher@10.0.0.2).

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  3-node baremetal with Dell PowerEdge R740XDs

**Comment by futuretea** [comment]
@zanewgray The Host console URL should be a HTTP url, you can input IPMI url or something like that.

**Comment by zanewgray** [comment]
Thank you.  I did not see this restriction in the docs.  I have it pointed at the IPMI (Dell iDRAC) now.

**Comment by FrankYang0529** [comment]
Hi @zanewgray, do you have other questions about this issue? If not, may I close it? Thanks.

**Comment by zanewgray** [comment]
No other questions.  You may close this issue.  Thanks!

________________________________
