### ISSUE TITLE
[Question] only enable ping function base on other VM create

### ISSUE THREAD

**Issue by bingo4933** [harvester/harvester#3283]
I have installed harvester already which version is 1.1

I created first VM `testping-vm-1`  completely then tried to ping GW but failed
```
[centos@testping-vm-1 ~]$ ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 6e:e8:22:0a:30:f3 brd ff:ff:ff:ff:ff:ff
    inet 10.138.181.238/24 brd 10.138.181.255 scope global dynamic eth0
       valid_lft 575sec preferred_lft 575sec
    inet6 fe80::6ce8:22ff:fe0a:30f3/64 scope link 
       valid_lft forever preferred_lft forever
[centos@testping-vm-1 ~]$ ping 10.138.181.1
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
^C
--- 10.138.181.1 ping statistics ---
82 packets transmitted, 0 received, 100% packet loss, time 80999ms
```

then, I created another VM `testping-vm-2` and return into `testping-vm-1` then tried again. I found it worked.
```
[centos@testping-vm-1 ~]$ ping 10.138.181.1
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
64 bytes from 10.138.181.1: icmp_seq=43 ttl=64 time=0.687 ms
64 bytes from 10.138.181.1: icmp_seq=44 ttl=64 time=0.679 ms
64 bytes from 10.138.181.1: icmp_seq=45 ttl=64 time=0.752 ms
64 bytes from 10.138.181.1: icmp_seq=46 ttl=64 time=0.642 ms
64 bytes from 10.138.181.1: icmp_seq=47 ttl=64 time=0.651 ms
64 bytes from 10.138.181.1: icmp_seq=48 ttl=64 time=0.637 ms
64 bytes from 10.138.181.1: icmp_seq=49 ttl=64 time=0.692 ms
...
```

I keep that ping network gateway action for a while in `testping-vm-1` host. then I removed `testping-vm-2` host on harvester dashboard. after that, I quit that ping job then re-run ping command again in `testping-vm-1` but I found it couldn't ping GW any more. not only GW, my dns/ntp/proxy which all can't ping.
```
[centos@testping-vm-1 ~]$ ping 10.138.181.1
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
^C
```

interesting thing. then I created a new virtual machine `testping-vm-3` . I found that all ping job to gw/dns/ntp etc could worked in `testping-vm-1` machine.
```
[centos@testping-vm-1 ~]$ ping 10.138.181.1 -c 3
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
64 bytes from 10.138.181.1: icmp_seq=1 ttl=64 time=0.608 ms
64 bytes from 10.138.181.1: icmp_seq=2 ttl=64 time=0.649 ms
64 bytes from 10.138.181.1: icmp_seq=3 ttl=64 time=0.735 ms

--- 10.138.181.1 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2000ms
rtt min/avg/max/mdev = 0.608/0.664/0.735/0.052 ms
[centos@testping-vm-1 ~]$ ping 10.136.80.2 -c 3
PING 10.136.80.2 (10.136.80.2) 56(84) bytes of data.
64 bytes from 10.136.80.2: icmp_seq=1 ttl=62 time=0.671 ms
64 bytes from 10.136.80.2: icmp_seq=2 ttl=62 time=1.42 ms
64 bytes from 10.136.80.2: icmp_seq=3 ttl=62 time=0.667 ms

--- 10.136.80.2 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2002ms
rtt min/avg/max/mdev = 0.667/0.921/1.426/0.357 ms
```

what's going on here??
please help.

**Comment by tjjh89017** [comment]
Could you help us to provide some info below to debug?
Thanks a lot

1. Create a support bundle and upload to us.
2. How to create your VM. You could give us the VirtualMachine CRD for vm1 & vm2
3. VM1 & VM2 are in the same host or not?
4. what's your harvester network config and vlan config. and we need the `net-attach-def` of your VM.

While VM1 cannot ping, could you help us to login to the harvester node of VM1, execute the following command and send us the result? (Please do those twice, for VM1 only, and VM1 & VM2 are existing and pingable)

1. `bridge -c vlan show`
2. `ip link`
3. `ip addr`

Thanks a lot

**Comment by w13915984028** [comment]
@yaocw2020 any insight ?

**Comment by bingo4933** [comment]
hello @tjjh89017 
thank you for reply.  let's close this ticket please as I found the first VM in harvester cluster are crashed, I'm unable to login its shell.

let me raise ticket again if I run into this similar issue.



Regards,
