### ISSUE TITLE
[backport v1.0][BUG] Terraform created networks with DHCP fails on apply after DHCP-network is registered in terraform

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3284]
backport the issue https://github.com/harvester/harvester/issues/2857

**Comment by TachunLin** [comment]
Verified **fixed** on harvester-terraform provider `v1.0` with Harvester `v1.0.3`. Close this issue.

### Result
1. We can set `route_mode = "auto"` and also specify the `route_dhcp_server_ip` to apply the network resource correctly. 
  (Use v1.0.3 cluster network feature)
    ```
    resource "harvester_network" "vlan1" {
      name      = "vlan1"
      namespace = "harvester-public"
      description = ""
    
      vlan_id = 1
    
      route_mode           = "auto"
      route_dhcp_server_ip = "192.168.122.1"
    }
    ```
  ![image](https://user-images.githubusercontent.com/29251855/207779832-e432eece-8cad-4019-abc8-d037afc4225b.png)



2. And we can also edit the description and apply again 
    ```
    Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
      ~ update in-place
    
    Terraform will perform the following actions:
    
      # harvester_network.vlan1 will be updated in-place
      ~ resource "harvester_network" "vlan1" {
          + description          = "test"
            id                   = "harvester-public/vlan1"
            name                 = "vlan1"
            tags                 = {}
            # (6 unchanged attributes hidden)
        }
    
    Plan: 0 to add, 1 to change, 0 to destroy.
    harvester_network.vlan1: Modifying... [id=harvester-public/vlan1]
    harvester_network.vlan1: Modifications complete after 0s [id=harvester-public/vlan1]
    
    Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
    ```
    ![image](https://user-images.githubusercontent.com/29251855/207778814-0f68b401-33c2-4899-8ae3-a1ee7e1494ca.png)

### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: v1.0.3
* Terraform version: master 

### Verify Steps
1. Prepare Harvester cluster 
2. ssh to Harvester and get kubeconfig content in `/etc/rancher/rke2/rke2.yaml` 
3. Copy the content to host machine ~/.kube/config 
4. Update the `server:` to harvester management ip
5. Run the following command to startup a terraform-provider container 

6. (optional) install kubectl on terraform-provider container follow the [instruction](https://kubernetes.io/docs/tasks/tools/install-kubectl-linux/)

7. Check the connectivity to Harvester cluster 
  ```
  kubectl --kubeconfig=/tmp/kubeconfig get no
  ```
8. vim `providers.tf` , add the following content 
  ```
  terraform {
    required_providers {
      harvester = {
        source = "harvester/harvester"
        version = "0.0.0-master"
      }
    }
  }
  
  provider "harvester" {
    kubeconfig = "/tmp/kubeconfig"
  }
  ```
9. Run `terraform init` to initialize it.
10. Enable network on default `harvester-mgmt` interface
11. Create a test config file `vim main.tf`
12. Add resource harvester_network with route_mode = "auto" and route_dhcp_server_ip = "<replace to your dhcp server>"
  ```
  resource "harvester_network" "vlan1" {
    name      = "vlan1"
    namespace = "harvester-public"
    description = ""
  
    vlan_id = 1
  
    route_mode           = "auto"
    route_dhcp_server_ip = "192.168.5.1"
  }
  ```

13. Apply the resource `terraform apply -auto-approve` 
  ```
  ffc4c643f5e6:/data # terraform apply -auto-approve
  
  Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
    + create
  
  Terraform will perform the following actions:
  
    # harvester_network.vlan1 will be created
    + resource "harvester_network" "vlan1" {
        + config               = (known after apply)
        + id                   = (known after apply)
        + message              = (known after apply)
        + name                 = "vlan1"
        + namespace            = "harvester-public"
        + route_cidr           = (known after apply)
        + route_connectivity   = (known after apply)
        + route_dhcp_server_ip = "192.168.122.1"
        + route_gateway        = (known after apply)
        + route_mode           = "auto"
        + state                = (known after apply)
        + vlan_id              = 1
      }
  
  Plan: 1 to add, 0 to change, 0 to destroy.
  harvester_network.vlan1: Creating...
  harvester_network.vlan1: Creation complete after 0s [id=harvester-public/vlan1]
  
  Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
  
  ```
14. Edit the main.tf, update the description 
15. Apply the resource again `terraform apply -auto-approve`
