### ISSUE TITLE
[Question]How can I assign a single ip address to a VM using a vlan

### ISSUE THREAD

**Issue by huangkaiyan10** [harvester/harvester#3286]
My scenario is 172.18.17.0/24  vlan, Many ip addresses has been used by other people. I can use only a few ip addresses, such as 172.18.17.238, 172.18.17.240, and 172.18.17.245,these ip addresses are discontinuous;.Or can i create a VM, install an operating system, and then log in to the VM to configure network interface ,Can i configure a fixed static ip address

**Comment by Martin-Weiss** [comment]
@huangkaiyan10  - this depends on the OS you are installing. In case you have cloud-init in the OS template - you an add the cloud-init network settings (including static IP) in the cloud-init network settings (network_data)..

Example for cloud-init network data:

```
version: 2
ethernets:
  eth0:
    dhcp4: false
    addresses:
      - 172.18.17.238/24
    gateway4: 172.18.17.1
    nameservers:
      search: lab.suse.com
      addresses: 8.8.8.8
```

**Comment by huangkaiyan10** [comment]
harvester created the virtual machine and configured the vlan network. But it can't communicate with other hosts outside of harvester, which are on the same network segment (172.18.17.0/24)

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/208344101-234c5d63-2940-4018-afe1-a67bbfc12e88.png)
![image](https://user-images.githubusercontent.com/5146180/208344123-d59f1c63-b620-4f63-bf36-4274360515a9.png)
![image](https://user-images.githubusercontent.com/5146180/208344170-e2f55ba2-8b73-4b92-94e7-158b5b3c5fe2.png)
![image](https://user-images.githubusercontent.com/5146180/208344206-25741cfa-add8-435e-940a-073362ea5113.png)

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/208344540-a6eabf9d-41ad-495a-8d3d-6d27c2a1fa84.png)

**Comment by huangkaiyan10** [comment]
![image](https://user-images.githubusercontent.com/5146180/208362186-96e8c8ab-db84-406b-9908-57cbce02396d.png)
![image](https://user-images.githubusercontent.com/5146180/208362284-11caeaa9-f9c3-4f18-9109-3778d37b3bcc.png)
![image](https://user-images.githubusercontent.com/5146180/208362363-4a02a6e3-bfb8-4e9b-b69e-c28604a2f072.png)

**Comment by fanlix** [comment]
try a easier network config. when creating the vm , use net-ip-243 network as the only network.

**Comment by huangkaiyan10** [comment]
![1-1](https://user-images.githubusercontent.com/5146180/208798725-ffb136a0-5fd7-4940-8319-5ff35628b9f4.png)
![1-2](https://user-images.githubusercontent.com/5146180/208798809-177569e6-5e5d-4bf2-8788-68d22cadfb47.png)
![1-3](https://user-images.githubusercontent.com/5146180/208798826-3c5daa4a-aec7-4041-a202-7ae7c0ea8b93.png)

**Comment by huangkaiyan10** [comment]
> try a easier network config. when creating the vm , use net-ip-243 network as the only network.

There is no management network, vlan ip can ping through; but if there is a management network, vlan ip can not ping through, how to troubleshoot this problem

**Comment by fanlix** [comment]
> There is no management network, vlan ip can ping through; but if there is a management network, vlan ip can not ping through, how to troubleshoot this problem

我的意思就是不要在vm上挂mgmt的网卡. vm只用一个vm-vlan即可.
* mgmt网本来就不是给vm用的. 自己单独建一个或多个vlan来用. (文档也是这样推荐的)
* 单vm多网卡, 比较复杂. 请详细阅读hv的文档.
  * 不同vlan间有隔离, 需要配置好vlan id和外部交换机的端口规则
  * vm内操作系统也要配置路由规则
  * 默认一般只使用第一个网卡

**Comment by robv8r** [comment]
`gateway4` is [deprecated](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#common-properties-for-all-device-types:~:text=%3A%20%3C(scalar)%3E-,Deprecated,-%2C%20see%20netplan%23default) in cloud-init v2.  It was originally intended to represent the "default route" for a given interface.  Try using [`routes`](https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#common-properties-for-all-device-types:~:text=routes%3A%0A%20%20%20%20%20%20%20%20%2D%20to%3A%20192.0.2.0/24%0A%20%20%20%20%20%20%20%20%20%20via%3A%2011.0.0.1%0A%20%20%20%20%20%20%20%20%20%20metric%3A%203) instead.

```
routes:
 - to: default
   via: 172.18.17.253
```

Note: [`default`](https://netplan.io/reference#default-routes:~:text=default%20%23%20could%20be%200/0%20or%200.0.0.0/0%20optionally) could be expressed as `0/0` or `0.0.0.0/0`.

If you have multiple virtual network adapters, try using a route for each link.

```
eth0:
  ...
  routes:
    - to: 10.43.0.0/24
      via: 10.43.0.1
      metric: 100
eth1:
  ...
  routes:
    - to: default
      via: 172.18.17.253
      metric: 200
```

Let me know how if this helps.

**Comment by huangkaiyan10** [comment]
你的邮件我已经收到。谢谢
 
                              黄开雁
