### ISSUE TITLE
[Question]The first volume is configured with a size of 50GB,but there is no disk space to partition

### ISSUE THREAD

**Issue by huangkaiyan10** [harvester/harvester#3288]
When creating a VM. The first volume is configured with a size of 50GB. However, when 	i attempt to install the operating system from web VNC, a message is displayed indicating that there is no disk space to partition.I'm using it wrong or it's a bug？

![113cbdaacbb8e1016e1e997f4639dc6](https://user-images.githubusercontent.com/5146180/208011977-8629de5b-3db9-47fb-a845-fe0d65eb6913.png)

![ba0b35211c66d0140de88e086fa7d50](https://user-images.githubusercontent.com/5146180/208011995-69e33be4-0732-463f-8c29-815f3f8cac7a.png)

![3812e33d5bdb5ebe80ff2cc6e91a2f6](https://user-images.githubusercontent.com/5146180/208012019-7a8f7b2c-0917-4cd1-967e-d47f6dd2ab7a.png)

**Comment by huangkaiyan10** [comment]
harvester 1.1.1

**Comment by huangkaiyan10** [comment]
centos7.9

**Comment by futuretea** [comment]
The image is an iso image. You can refer to iso templates

**Comment by huangkaiyan10** [comment]
你的邮件我已经收到。谢谢
 
                              黄开雁

**Comment by huangkaiyan10** [comment]
你的邮件我已经收到。谢谢
 
                              黄开雁
