### ISSUE TITLE
[Question]After ssh remotely logs in to the harvester host node, kubectl does not have permission

### ISSUE THREAD

**Issue by huangkaiyan10** [harvester/harvester#3291]
After ssh remotely logs in to the harvester host node, kubectl does not have permission

![cf5c20a1e117760020782c2da52d1e9](https://user-images.githubusercontent.com/5146180/208061696-3053919f-6118-4f35-b1c6-ad9576047bc9.png)

how to set so that i can Solve the problem

**Comment by ApolloDS** [comment]
Answer:

1. Use "sudo -i"
2. Then use kubectl and it will work

Reason:
Use kubectl as root

**Comment by huangkaiyan10** [comment]
test ok.

**Comment by bk201** [comment]
Closed due to the user having the answer.
