### ISSUE TITLE
[Enhancement] Add `containerd-registry` setting validation to installer

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#3295]
**Describe the bug**
If users give a wrong `containerd-registry` in [Harvester configuration](https://docs.harvesterhci.io/v1.1/install/harvester-configuration#system_settings), we didn't show any error message.

**To Reproduce**
1. Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester).
2. Add following in [config-create.yaml.j2](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2).
```
systemSettings:
  containerd-registry: '{"error json format"}'
```
3. Run `./setup_harvester.sh`
4. There is no error message in installer.

Another invalid value: 
* Add `""` around `rewrite` key and value. Please check golang playground https://go.dev/play/p/HaBDTFqp-vk.

**Expected behavior**
The installer should return error if the config is wrong.

**Environment**
 - Harvester ISO version: v1.1.1

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Case/Steps
1. Use [vagrant-pxe-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester).
2. Add following to [config-create.yaml.j2](https://github.com/harvester/ipxe-examples/blob/main/vagrant-pxe-harvester/ansible/roles/harvester/templates/config-create.yaml.j2).
   ```
   systemSettings:
     containerd-registry: '{"error json format"}'
   ```
3. Run ./setup_harvester.sh
4. The panel shows `could not parse containerd-registry as JSON`. :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/3941996d-7ef7-44f6-ac17-ba2a07a24ad4)


## Note
1. Step refer to https://github.com/harvester/harvester-installer/pull/571#pullrequestreview-1695251562
