### ISSUE TITLE
[Question] Is it possible to enable remote write on the prometheus in the Harvester cluster?

### ISSUE THREAD

**Issue by Joao-Alves** [harvester/harvester#3304]
Hello,

I have Harvester 1.1 installed in my cluster and I would like to change the values on the Prometheus deployment to enable remote write and the addition of a extra label?

We tried to change the values of the helm chart and deploy it, however a few hours afterwards the values are overridden by their default values? Is any way to change this or should we deploy another Prometheus instance to achieve this goal?

**Comment by Martin-Weiss** [comment]
While I assume this is not officially supported and will create issues during upgrades - check the objects "managedchart" in the namespace "fleet-local".

**Comment by Joao-Alves** [comment]
Thank you @Martin-Weiss! What type of issue you think this can create during upgrades? The remote-write flag is already present on the helm chart that is deploying in harvester

**Comment by Martin-Weiss** [comment]
> Thank you @Martin-Weiss! What type of issue you think this can create during upgrades? The remote-write flag is already present on the helm chart that is deploying in harvester!

@Joao-Alves - the risk I see is that your customization might be lost during an upgrade and you might have to do the config again after an upgrade.

**Comment by Joao-Alves** [comment]
I think if that is the issue it would be simple to integrate in our update process to check if this change is kept. 
With that in mind I also think that this could be a nice feature for harvester.

**Comment by w13915984028** [comment]
@Joao-Alves  The helm charts are not directly exposed for Monitoring in Harvester, it is encapsulated as an CRD "ManagedChart" as of v1.1.1.

(1) remoteWrite is defined in 
https://github.com/rancher/charts/blob/dev-v2.7/charts/rancher-monitoring/100.1.1%2Bup19.0.3/values.yaml#L3015

(2) the values are overwritten in
https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-13-monitoring.yaml#L78

For your purpose, please use `kubeclt edit managedchart -n fleet-local rancher-monitoring` to add the `remoteWrite: []` under `prometheusSpec`, thus it will be persistent.

Please note the potential memory pressue: https://prometheus.io/docs/practices/remote_write/#memory-usage.

**Comment by Joao-Alves** [comment]
Hello @w13915984028,

Thank you for the suggestion, he just implemented it and we are monitoring it to give feedback. 
Shouldn't this be in the documentation with the relevant warning, I think this use case should be very standard.
