### ISSUE TITLE
[Question] IP Address not being assigned

### ISSUE THREAD

**Issue by pkeech** [harvester/harvester#3305]
I have Harvester installed on a Single Node PowerEdge Server in a Lab Environment. When I go to deploy a cluster (via Rancher) or multiple Virtual Machines (from Harvester) it's a hit-or-miss if the Virtual Machine gets assigned an IP address. This is causing a knock-on effect where I can't provision a cluster (via Rancher) because it's waiting for the node to come online. 

![MissingIPAddress](https://user-images.githubusercontent.com/65731523/208758975-36c208e5-f1f8-4511-b10f-667eda7827c9.png)

I'm using the Generic Rocky Linux 9.x Cloud Image, and my Cloud-Init file only contains "ssh-authorized-keys" with my single key listed. With both deployment methods, nothing is changing but I'm getting different results. 

I must be missing something but I have no idea where to look first given the VM with the issue has no IP listed. Looking at my DHCP server and scanning my network it appears the Virtual Machine isn't get assigned an IP Address.

**Comment by pkeech** [comment]
The previous screenshot was generated by using the "Multiple Instance" option within Create Virtual Machine. This screenshot shows the same missing assigned IP addresses occuring when creating a Cluster (via Rancher).

![MissingIPAddressCluster](https://user-images.githubusercontent.com/65731523/208924502-3aa64343-3077-4965-a2fd-c3066c9f4397.png)

**Comment by FrankYang0529** [comment]
Hi @pkeech, can you always reproduce the bug? If yes, could you give me detailed steps? I can't reproduce it on my cluster. When I created 5 VMs, two VMs couldn't get IP at first, but they finally got IP in 5 minutes.

**Comment by pkeech** [comment]
Cheers @FrankYang0529 for your response.

Yes it's repeatable, but it's not predictable ... if that makes sense. I can deploy the same cluster 5 times and get different results each time. Sometimes all but 1 VM gets an IP address, other 3 or 4 VMs don't get IP Addresses. I usually give the VMs anywhere from 30minutes to 2 hours to see if they obtain an IP Address before deleting it and starting over. 

Additionally, I performed a test where I deployed a cluster (from Rancher) and left it for 24hours. When I came back the next day, all the VMs eventually got IP Addresses but the cluster was still pending all the Kubernetes Services.

I'm convinced this is just a simple "user error" but I'm coming up short when trying to troubleshoot.

**Comment by abonillabeeche** [comment]
@pkeech can you try with another OS image? With Rancher 2.7.0 I don't see Rocky 9 as supported. But up to 8.6 [See](https://www.suse.com/suse-rancher/support-matrix/all-supported-versions/rancher-v2-7-0/)

**Comment by w13915984028** [comment]
@pkeech We need more details, thanks.

```
1. The Harvester version.

2. Did you test deoplying several VMs one after another, can all of them obtain the IP address?

3. When you deploy a couple of VMs at the same time, it is also helpful to do tcpdump (e.g. tcpdump -e -i virbr1 port 67 or port 68) at both sides:
  The Harvester NODE, with sudo -i first,
  The DHCP server,
From the DHCP dump, we will see if the packets are not sent, or dropped at some point.
```

**Comment by ibrokethecloud** [comment]
When a VM is provisioned, harvester injects a cloud-init snippet to install the qemu agent. This is what is in turn used to report the IP assigned to the VM.

It is possible that either you are not getting an ip address from dhcp, or the ip is available, but the agent install fails which results in the ip address not being reported.

Are you please able to check on failed vm's:

* If you are able to get the IP, by logging into the VM from the console?
* The result of cloud-init application
