### ISSUE TITLE
[BUG] No error displayed when upgrading to use an invalid download url

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#3310]
**Describe the bug**
Create a version with an invalid iso URL, eg: `https://releases.rancher.com/harvester/invalid/harvester-invalid-amd64.iso`.
Click Upgrade on the dashboard and you will see in the upgrade panel that it is always in the pending status.

Backing image logs:
```
time="2022-12-22T02:11:01Z" level=debug msg="Sync Service: initialized" component=sync-server listen="0.0.0.0:8001"
time="2022-12-22T02:11:01Z" level=info msg="Started sync server at 0.0.0.0:8001"
time="2022-12-22T02:11:02Z" level=debug msg="DataSource Service: initializing" component=data-source-service diskUUID=af9319a4-a092-4d5c-81a3-7ea5ff998a89 expectedChecksum=8dd5203c111e4f78e8bb93bdca69e371260616f3e4062f974c61fb61f476ecb114fb809b3d63c5c69efb521ddc6c27937638c58fcfb96c9715cdc5e61a9597e2 filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 name=harvester-system-harvester-iso-g8h5w parameters="map[url:https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1]" sourceType=download uuid=a70abd68
time="2022-12-22T02:11:02Z" level=debug msg="Sync Service: initializing sync file /data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68" component=sync-server listen="0.0.0.0:8001"
time="2022-12-22T02:11:02Z" level=debug msg="DataSource Service: initialized" component=data-source-service diskUUID=af9319a4-a092-4d5c-81a3-7ea5ff998a89 expectedChecksum=8dd5203c111e4f78e8bb93bdca69e371260616f3e4062f974c61fb61f476ecb114fb809b3d63c5c69efb521ddc6c27937638c58fcfb96c9715cdc5e61a9597e2 filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 name=harvester-system-harvester-iso-g8h5w parameters="map[url:https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1]" sourceType=download uuid=a70abd68
time="2022-12-22T02:11:02Z" level=info msg="Started data source server at 0.0.0.0:8000"
time="2022-12-22T02:11:02Z" level=info msg="SyncingFile: cannot to reuse the existing file, will clean it up then start processing: stat /data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68: no such file or directory" component=sync-file filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 uuid=a70abd68
time="2022-12-22T02:11:03Z" level=info msg="SyncingFile: start to download sync file from URL https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1" component=sync-file filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 uuid=a70abd68
time="2022-12-22T02:11:03Z" level=debug msg="DataSource Service: datasource file is state starting, the processing is not begin yet" component=data-source-service diskUUID=af9319a4-a092-4d5c-81a3-7ea5ff998a89 expectedChecksum=8dd5203c111e4f78e8bb93bdca69e371260616f3e4062f974c61fb61f476ecb114fb809b3d63c5c69efb521ddc6c27937638c58fcfb96c9715cdc5e61a9597e2 filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 name=harvester-system-harvester-iso-g8h5w parameters="map[url:https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1]" sourceType=download uuid=a70abd68
time="2022-12-22T02:11:04Z" level=error msg="SyncingFile: failed to process sync file: expected status code 200 from https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1, got 404 Not Found" component=sync-file filePath=/data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68 uuid=a70abd68
time="2022-12-22T02:11:04Z" level=error msg="Sync Service: failed to download sync file /data/tmp/harvester-system-harvester-iso-g8h5w-a70abd68: expected status code 200 from https://releases.rancher.com/harvester/v1.1.1/harvester-v1.1.1-amd64.iso1, got 404 Not Found" component=sync-server listen="0.0.0.0:8001"
```

Try to create backing image manually in Longhorn will it displays failed:
![image](https://user-images.githubusercontent.com/3347460/209044596-8ee63841-f8ca-4163-b541-c02e120df8f1.png)

**To Reproduce**
1. Create a version resource with an invalid iso URL.
2. Click Upgrade on the dashboard.
3. See the upgrade panel or check the upgrade resource.

**Expected behavior**
Display error or tip when upgrading to use an invalid download URL.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
Is timeout observed in image downloading after certain time ? there are a few more possibilities that the download may fail, like: invalid file url, server is down, network is broken, http proxy issue,  CA issue, abnormal remote file size (too big, or bigger than the target PVC size)...

we may consider to enhance: in the validator check if remote file/url is valid (implicitly including all possible network issue, CA issue, proxy issue ...), check valid file size, and also time out in the POD for downloading itself.

**Comment by w13915984028** [comment]
code in this PR https://github.com/harvester/harvester/pull/3148 may be referred.

**Comment by FrankYang0529** [comment]
This issue will be fixed in https://github.com/harvester/harvester/pull/3148.

**Comment by irishgordo** [comment]
**validation passed**
Tested on v1.1.2.

Thanks for this @FrankYang0529 & @chrisho  this looks good :+1:  :smile:  - I'll go ahead and close this out.

![Screenshot from 2023-05-01 17-48-29](https://user-images.githubusercontent.com/5370752/235556440-af13e0fc-23ee-473a-a35e-63c9da4003b7.png)
![Screenshot from 2023-05-01 17-43-38](https://user-images.githubusercontent.com/5370752/235556443-f9ac75ac-494c-4d95-99fc-b0c108f97e4b.png)
![Screenshot from 2023-05-01 17-42-31](https://user-images.githubusercontent.com/5370752/235556444-c785619b-33d7-4006-ac76-d014426bb18b.png)
![Screenshot from 2023-05-01 17-40-50](https://user-images.githubusercontent.com/5370752/235556445-5abddc19-e771-46a9-b48d-f42a2849382a.png)
![Screenshot from 2023-05-01 17-37-43](https://user-images.githubusercontent.com/5370752/235556446-8b4bd5ea-3fa1-44d2-87da-e1cdaaedd60d.png)
