### ISSUE TITLE
[Question] Is it possible to deploy a daemon directly on the host which is running harvester?

### ISSUE THREAD

**Issue by jattind** [harvester/harvester#3311]
I believe harvester is running some version of OpenSUSE. If I ssh into the server and try to deploy say an snmp  daemon, I get an error.
"The target filesystem is mounted as read-only. Please make sure the target filesystem is writeable."

**Comment by bk201** [comment]
Hi, Harvester has an immutable OS design, so most paths are read-only. Can you try to deploy the workload with a Kubernetes daemon set? It's possible to [enable rw mode](https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only) for debugging purposes, but keep in mind the change is gone after an upgrade.
