### ISSUE TITLE
[Question] networking - masquerade vs bridge ip registration

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#3317]
Hello! i've noticed that if i'm using a bridge ip address on the management network, the vm is not migratable per the events:

VirtualMachineInstance vm-1
EvictionStrategy is set but vmi is not migratable; cannot migrate VMI which does not use masquerade to connect to the pod network

in my case, i want to use the management network because it's on 10gb interfaces, and my LAN vlan is on only a 1gb interface.

if i use masquerade, the IP that the vm registers with active directory / dhcp is different from the VM published on the harvester UI, so when other machines on the network try to communicate with it, they are not able to find a route. 

how can i get it so other vms can talk w/ this vm if it's on masquerade? 

Harvester: v1.1.1
VM-OS: windows 10

when bridge: 10.52.0.96 in Harvester UI (my network is 192.168.5.0, and i have a route to 10.52.0.0 to the Harvester Node that gets those addrs. Active Directory DNS registered ip as 10.52.0.96.

when masq: 10.52.0.97 in Harvester UI. the vm gets the ip 10.0.2.2 and that's what's registered in Active Directory. 

i guess i'm trying to figure out how to setup the correct route so that i can rdp into 10.0.2.2

**Comment by albertkohl-monotek** [comment]
anyone?

**Comment by pythoninthegrass** [comment]
~~I'm interested as well. Would like to be able to ssh/vnc/rdp into guests and seem to be missing something following [this guide](https://jmcglock.substack.com/p/harvester-rancher-) and the [docs](https://docs.harvesterhci.io/v1.1/networking/harvester-network/#create-a-vm-with-vlan-network).~~
Okay, looks like it was user error haha. I setup a vm network like so:
![Screenshot 2023-03-03 at 01-04-41 Harvester](https://user-images.githubusercontent.com/4097471/222934861-ffb8a2be-2bd2-462a-a6d9-21ab0418d47c.png)
![Screenshot 2023-03-03 at 01-05-42 Harvester](https://user-images.githubusercontent.com/4097471/222934862-04304956-7d76-42f4-aaf5-d82f522c3b6f.png)
Then in the VM config yaml:
```yaml
networks:
      - multus:
          networkName: default/wonderland
        name: default
```
And now my guests are reachable on the private IP subnet with dhcp leases.

Nothing to see here, move along 😅

**Comment by albertkohl-monotek** [comment]
Any feedback on this? 😊
