### ISSUE TITLE
[FEATURE] Remove External Harvester Cloud Credentails Support 

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3319]
**Is your feature request related to a problem? Please describe.**
Remove the external Harvester cloud credentials support in the newer version,  it has been marked as deprecated for multiple versions. It is recommended to use the Imported Harvester approach.

**Describe the solution you'd like**
Remove the external Harvester cloud credentials support in the multi-cluster view.

**Describe alternatives you've considered**
N/A

**Additional context**
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/4569037/209755973-ac11a0f5-4d32-4592-aa12-8594f8bbe263.png">

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.6-head` and `v2.7-head`. Close this issue.

### Result
* Verified on `v2.7-head` (9bb8d56) and `v2.6-head` (3bdc022), the import from external Harvester cloud credential have been removed in the Harvester cloud credential page

  ![image](https://user-images.githubusercontent.com/29251855/216874689-19109136-206b-4c18-966a-72f990026dd7.png)
  
  ![image](https://user-images.githubusercontent.com/29251855/216898787-a73a51ed-97c1-4ccd-bcc7-4905c4b0dfc5.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: master-14bbee2c-head (01/13)
* Rancher version: `v2.7-head` (9bb8d56) and `v2.6-head` (3bdc022)
* ui-index: default
* ui-dashboard-index: default
* ui-offline-preferred: Dynamic 


### Verify Steps
1. Import Harvester to Rancher
2. Open Cluster Management -> Cloud Credential
3. Click create
