### ISSUE TITLE
[FEATURE] Docs: Add Rancher quickstart for Harvester

### ISSUE THREAD

**Issue by davidspek** [harvester/harvester#3320]
**Is your feature request related to a problem? Please describe.**
The current [documentation](https://docs.harvesterhci.io/v1.1/rancher/rancher-integration) regarding the Rancher integration tell users to deploy Rancher using the quickstart examples. However, no quickstart example is provided for Harvester.

**Describe the solution you'd like**
Extend the quickstart terraform to support Harvester and add documentation telling users how to use it.

**Describe alternatives you've considered**
Native integration of Rancher in Harvester, which depends on https://github.com/harvester/harvester/issues/2769.

**Additional context**
PR for adding Harvester provider to the Rancher quickstart TF: https://github.com/rancher/quickstart/pull/218

**Comment by guangbochen** [comment]
Close as the upstream PR https://github.com/rancher/quickstart/pull/218 is merged; also in Harvester v1.2.0, we will consider adding built-in Rancher integration support in the bare-metal Harvester cluster.
Feel free to re-open it if you have any questions, thanks.
