### ISSUE TITLE
[BUG] unable to access the v1 API in ISO mode

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#333]
**Describe the bug**

unable to access the v1 API when the Harvester is installed with ISO mode

**To Reproduce**
1. after the Harvester is up and running
2. login to the UI and go to /v1 path
3. failed to view the API UI and the following error has occurred.
```
Uncaught TypeError: Cannot read property 'replace' of undefined
    at HTMLApi._fieldMunge (ui.min.js:sourcemap:7)
    at HTMLApi._schemaMunge (ui.min.js:sourcemap:7)
    at HTMLApi.schemasMunge (ui.min.js:sourcemap:7)
    at v (ui.min.js:sourcemap:5)
    at ui.min.js:sourcemap:5
    at Array.forEach (<anonymous>)
    at a (ui.min.js:sourcemap:5)
    at d (ui.min.js:sourcemap:5)
```

**Expected behavior**

able to view /v1 api

**Log**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
This is related to the changes in Longhorn v1.1.0 CRD [schema](https://github.com/longhorn/longhorn/blob/5ec0c5a261f4b0efb9f65f4a11a194279b491cff/chart/templates/crds.yaml#L22-L28)
The API schemas contain unknown type fields and it results in the API UI errors.

**Comment by futuretea** [comment]
Validated
