### ISSUE TITLE
[BUG] Harvester Cloud Provider truncates Harvester Loadbalancer name without checking for valid fqdn

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3333]
**Describe the bug**

The HCP in a Guest Cluster truncates the Harvester Load Balancer name to 64 characters, but does not check if the result is still a valid domain name.

Merging the Cluster Name, Namespace, the string “rke2-nginx-ingress-controller” and a hash with a dash (“-”) and then truncating it to 64 characters may result in an invalid domain name. This apparently is not validated or fixed, so it can generate the following Load Balancer name, resulting in the following error:

—
Error syncing load balancer: failed to ensure load balancer: LoadBalancer.loadbalancer.harvesterhci.io “bvis-central-rundeck-kube-system-rke2-ingress-nginx-controller-” is invalid: metadata.name: Invalid value: “bvis central-rundeck-kube-system-rke2-ingress-nginx-controller”: a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character ( e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9][a-z0-9])?(\.[a-z0-9]( [-a-z0-9][a-z0-9])?)*')

**To Reproduce**
Provision cluster in Harvester with specific name (see above) 

**Expected behavior**

**Support bundle**

**Environment**
This happens with:
— rancher/harvester-cloud-provider:v0.1.3
— rancher/harvester-cloud-provider:v0.1.4

**Additional context**

**Comment by yaocw2020** [comment]
Test case:
- Create an RKE2 named `kubernetes` with the Harvester cloud provider through the Harvester node driver
- Create Nginx deployment and the related lb service `default/thisisthetestcasethatisbelongerthan63charts`. It will fail to create the load balancer because of the invalid name `kubernetes-default-thisisthetestcasethatisbelongerthan63charts-`. 
- Update the harvester cloud provider deployment image to the master head. It will successfully create the load balancer with the valid name `kubernetes-default-thisisthetestcasethatisbelongerthan6xxxxxxxx`.

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher v2.7.1 with Harvester cloud provider master. Close this issue.

### Result
* By default cloud provider v0.1.4, when we create loadbalancer with name `default/thisisthetestcasethatisbelongerthan63chart`, it failed to create in pending state
![image](https://user-images.githubusercontent.com/29251855/217459246-2943517c-83c2-47e6-aa64-dbafc841b0e1.png)

* After we update cloud provider container image to `master-head` , we can create loadbalancer service correctly which result in an invalid domain name
![image](https://user-images.githubusercontent.com/29251855/217474399-284fee57-d869-45dd-865d-b0189e73b1be.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-aa7fcafc-head` (02/07)
* Rancher version: v2.7.1
* cloud provider version: master-head

### Verify Steps
1. Login harvester dashboard
2. Open images page
3. Create an image by using URL

### Additional Context
1. Prepare Rancher v2.7.1
2. Import Harvester, create cloud credential 
3. Provision a RKE2 cluster named `kubernetes`
4. Create a nginx deployment 
5. Create an load balancer service named `thisisthetestcasethatisbelongerthan63charts`
6. Check the installation state 
7. Edit cloud provider application deployment config 
8. Change the container image to `rancher/harvester-cloud-provider:master-head`
  ![image](https://user-images.githubusercontent.com/29251855/217465897-95364bc0-5c0a-4b76-870f-80bd52e1e724.png)

9. Delete previous cloud provider 0.1.4
10. Check the state of previous failed load balancer
11. Create another load balancer named `kubernetes-default-thisisthetestcasethatisbelongerthan688820819` 
12. Check the state
