### ISSUE TITLE
VM add batch operation

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#334]
**Feature**
Add the start, stop, restart drop-down button

**Comment by DaiYuzeng** [comment]
The state of VM is out of sync when i pause/unpause the VM.

![截屏2020-12-24 下午3 29 39](https://user-images.githubusercontent.com/15041915/103070750-1e295600-45fd-11eb-8c61-35d01b923c2a.png)

**Comment by DoNotSayYes** [comment]
**Steps to reproduce:**
1. Create two VMs A & B
2. Pause VM A, then Pause VM B
3. Open VM A's menubar again

**Result:**
The pause button is displaying instead of Unpause @DaiYuzeng 
![image](https://user-images.githubusercontent.com/57614736/103521633-0fbc2380-4eb4-11eb-83db-4207146c7656.png)

**Comment by DoNotSayYes** [comment]
Track by #407 and close the current issue since this is for enhancement
