### ISSUE TITLE
Longhorn NFS Disk addition - VM/Volume creation failed 

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3342]
Hi Team,

We have 4 node cluster, on one node I have added a 40 TB NFS disk . On longhorn I can see the space is scheduled  and shows the size of 40 TB . when I try to create a VM on that disk the volume or replica  creation getting failed .

<img width="1519" alt="Screen Shot 2023-01-05 at 4 34 27 PM" src="https://user-images.githubusercontent.com/117767598/210905910-20256d7c-aff1-4058-a6f6-51c1ecb3571b.png">
<img width="956" alt="Screen Shot 2023-01-05 at 4 33 56 PM" src="https://user-images.githubusercontent.com/117767598/210905955-73b224d5-e761-4669-8a64-e0429c4ab34e.png">

Please suggest

**Comment by dseralathan** [comment]
# kubectl get pods -A | egrep -v "Running|Completed"
NAMESPACE                   NAME                                                      READY   STATUS              RESTARTS      AGE
default                     virt-launcher-test-pfcq5                                  0/1     ContainerCreating   0             19h

below is the event for the VM creation :

Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Warning  FailedMount         76s (x499 over 18h)  kubelet                  (combined from similar events): Unable to attach or mount volumes: unmounted volumes=[disk-0], unattached volumes=[disk-2 hotplug-disks sockets cloudinitdisk-ndata public disk-0 disk-1 private ephemeral-disks container-disks libvirt-runtime cloudinitdisk-udata]: timed out waiting for the condition
  Warning  FailedAttachVolume  2s (x571 over 19h)   attachdetach-controller  AttachVolume.Attach failed for volume "pvc-604fb21c-d203-44df-8675-9186a7e3980c" : rpc error: code = DeadlineExceeded desc = volume pvc-604fb21c-d203-44df-8675-9186a7e3980c failed to attach to node test01

**Comment by bk201** [comment]
@dseralathan Harvester and Longhorn only support using dedicated disks. Please check: https://longhorn.io/docs/1.4.0/best-practices/#node-and-disk-setup
Digging the longhorn-manager or instance-manager-r pods' log on the NFS-attached node might provide some info about why it fails.

**Comment by dseralathan** [comment]
I read a doc and it says as below  - 

Longhorn will detect the storage information (e.g. maximum space, available space) about the disk automatically, and start scheduling to it if it’s possible to accommodate the volume.

**Comment by JWackerbauer** [comment]
The problem is that an NFS share is not a block device. We have a simillar use case to yours and adding disks to longhorn node through iscsi works fine.

**Comment by dseralathan** [comment]
thanks JWackerbauer
