### ISSUE TITLE
[BUG] Parameters Pane not showing Storage Classes

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#3348]
**Describe the bug**
when creating a storage class, the Parameters tab is empty

**To Reproduce**
assuming this might reproduce it:
install harvester v1.0.3
upgrade to v1.1.1
create a storage class
try to update the parameters

**Expected behavior**
user can configure Parameters for the Storage Class

**Support bundle**
https://drive.google.com/file/d/1i5iPV3sYr5nF60u-YaKB4jOEeIltRQXf/view?usp=sharing

Tokens, passwords, and secrets are automatically removed from support bundles. If you feel it's not appropriate to share the bundle files publicly, please consider:
- Wait for a developer to reach you and provide the bundle file by any secure methods.
- Join our Slack community (https://rancher-users.slack.com/archives/C01GKHKAG0K) to provide the bundle.
- Send the bundle to harvester-support-bundle@suse.com with the correct issue ID.  -->

**Environment**
 - Harvester ISO version: 1.0.3 upgraded to 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R620):

**Additional context**
also i see the following error in google-chromes developer console:
![image](https://user-images.githubusercontent.com/60982735/211237647-e2ec0f1e-fccd-4301-9fab-767e7d53d04a.png)

**Comment by albertkohl-monotek** [comment]
anyone have any feedback on this?

**Comment by ibrokethecloud** [comment]
are you trying to create and setup custom parameters during the creation of storage class, or are you trying to edit the parameters on an existing custom storage class

**Comment by albertkohl-monotek** [comment]
i would like to be able to do either if possible, the issue is, the PANE is totally gone. i'm assuming because of the java script errors

**Comment by albertkohl-monotek** [comment]
any feedback on this?

**Comment by w13915984028** [comment]
@WuJun2016 @n313893254 Any clue of such issue? thanks.

**Comment by WuJun2016** [comment]
According to the description, it should be a UI bug. I will try to reproduce it.

**Comment by WuJun2016** [comment]
Hi,  @albertkohl-monotek   
![image](https://user-images.githubusercontent.com/24985926/215730382-b9a809ea-5d57-4365-94f2-f8fa8783cea1.png)
If you change the `ui-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html` , change `ui-source` to `external`,  Then refresh the page, does it still report errors?

**Comment by WuJun2016** [comment]
I upgraded from v1.0.3 to v1.1.1 but failed to reproduce the problem.

@albertkohl-monotek  Can you look at the values returned by the `longhorn.io.nodes` api in your environment.   Whether the `spec.tags` attribute exists for each node。
<img width="1195" alt="image" src="https://user-images.githubusercontent.com/24985926/215756304-d3684583-081c-4f71-84a6-77e76ef10f6d.png">

**Comment by albertkohl-monotek** [comment]
@WuJun2016 : > Hi, @albertkohl-monotek If you change the `ui-index` to `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html` , change `ui-source` to `external`, Then refresh the page, does it still report errors?

yes, same issue still. 
tried clearing cache too for good measure.

**Comment by albertkohl-monotek** [comment]
@WuJun2016 
> Can you look at the values returned by the `longhorn.io.nodes` api in your environment. Whether the `spec.tags` attribute exists for each node。

how can i pull that? if i go to that url for the cluster vip, or any node, i get a refused to connect error.
![image](https://user-images.githubusercontent.com/60982735/215781998-4c86db15-43ed-4698-9e31-a9516e47c9b0.png)

**Comment by n313893254** [comment]
Hi, @albertkohl-monotek.  Try this URL: `<Harvester Endpoint>/v1/harvester/longhorn.io.nodes`

**Comment by albertkohl-monotek** [comment]
Thanks @n313893254 @WuJun2016 i see tags: [ ] at spec.tags and spec.disks.diskid.tags

in both cases, they are all empty

![image](https://user-images.githubusercontent.com/60982735/215801945-f9b3ea01-746e-4e88-9575-098e07ecda36.png)


i am noticing though, that one node, not all the disks have the tags: [ ] section.
![image](https://user-images.githubusercontent.com/60982735/215802136-e2b97b8c-5b28-4589-b257-b6796cb15f90.png)

**Comment by WuJun2016** [comment]
@albertkohl-monotek   It is caused by this  problem. I will fix it in the latest version。  thankns

**Comment by albertkohl-monotek** [comment]
@WuJun2016 anything i can do for a work-around to get it working until the next version update?

**Comment by WuJun2016** [comment]
> @WuJun2016 anything i can do for a work-around to get it working until the next version update?

@albertkohl-monotek  Wait for CI to complete， https://drone-publish.rancher.io/harvester/dashboard/770

workaround: https://github.com/harvester/harvester/issues/3348#issuecomment-1410403398
>

**Comment by WuJun2016** [comment]
> > @WuJun2016 anything i can do for a work-around to get it working until the next version update?
> 
> @albertkohl-monotek Wait for CI to complete， https://drone-publish.rancher.io/harvester/dashboard/770
> 
> workaround: [#3348 (comment)](https://github.com/harvester/harvester/issues/3348#issuecomment-1410403398)
> 
> >

@albertkohl-monotek  It is recommended to set the ui-index to the original address after setting the storageClass, otherwise new problems may be introduced。 thanks

**Comment by albertkohl-monotek** [comment]
That fixed it, thanks!
