### ISSUE TITLE
[Question] PCIe NIC not showing up in Harvester?

### ISSUE THREAD

**Issue by enp6s0** [harvester/harvester#3350]
I'm trying to run Harvester 1.1 on a server with a Supermicro X9DRD motherboard. UEFI boot is used.

During and after installation, Harvester doesn't seem to be able to detect my PCIe 10G NICs (tried both Mellanox ConnectX-3 and Broadcom 57810S). `lspci` doesn't show the card at all from within Harvester (only the onboard Intel I350 NICs are visible), but I was able to get the external NICs to show up with a live CD of Alpine Linux.

Am I missing something here? How can I make the NICs show up in Harvester so that I can utilize 10G networking, as recommended by the overview guide?

**Comment by tlehman** [comment]
@enp6s0 Have you tried `lspci -M` that does a thorough scan, here's more info from the man page:

```
       -M     Invoke  bus  mapping  mode  which performs a thorough scan of all PCI de‐
              vices, including those behind misconfigured  bridges,  etc.  This  option
              gives  meaningful  results only with a direct hardware access mode, which
              usually requires root privileges.  Please note that the bus  mapper  only
              scans PCI domain 0.
```

**Comment by enp6s0** [comment]
It did show up with `-M` (in debug mode, as I wasn't able to get Harvester to boot again from normal mode - that now gives me a black screen after a few reboots and I'm not sure why):

```
# lspci -M
...
06:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
06:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
86:00.0 Ethernet controller: Mellanox Technologies MT27500 Family [ConnectX-3]
...
```

The NIC now also shows up in Harvester's GUI for assignment. Will see if this comes up after a reinstall and update this thread accordingly.

**Comment by ibrokethecloud** [comment]
@enp6s0 just wondering if you managed to get this working?

**Comment by enp6s0** [comment]
@ibrokethecloud Yes, turned out to be hardware problem. Replaced the card and it's all working great now.
