### ISSUE TITLE
[BUG] harvester-installer: daily build on v1.1 branch doesn't publish a new ISO

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3352]
**Describe the bug**

Merging a pull request targeting the v1.1 branch omits the step to publish the build ISO. e.g.,
https://drone-publish.rancher.io/harvester/harvester-installer/1099

**To Reproduce**
1. Create a PR (to v1.1 branch) in the harvester-installer and merge it.

**Expected behavior**

A new ISO should published.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
Need to fix Cron job too (not publishing v1.1 ISO).

**Comment by guangbochen** [comment]
daily build on v1.1 branch still doesn't publish a new ISO, but the PR merge will work as expected, we will investigate this one v1.2 milestone, thanks.

**Comment by bk201** [comment]
It's working now after adding the cron job in the GUI, thanks @guangbochen 
https://drone-publish.rancher.io/harvester/harvester-installer/1300/1/1
