### ISSUE TITLE
[FEATURE] add image repository status to the harvester-ui

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#336]
**Is your feature request related to a problem? Please describe.**

1. [ ] Currently, there is no way for the user to know whether the Minio server up and running of the image repository, therefore when uploading the image it will always be failed and encounter some unexpected error messages.
1. [x] it will be failed to delete the image when the minion server is down or unreachable as it is blocked by the finalizer

**Describe the solution you'd like**

1. it will be better to adding image repository status to the Harvester UI
1.  allow the user to delete the image when the image hasn't been uploaded

**Comment by guangbochen** [comment]
case 2 is ready for testing

**Comment by guangbochen** [comment]
Validation steps for case 2: [passed]
1. adding an image with URL `http://a.img` and the following error is expected.
```
Get http://a.img: dial tcp: lookup a.img on 10.43.0.10:53: no such host
```
2. delete this image and it succeeded

**Comment by gitlawr** [comment]
For case 1, I suggest UI do polling at `<Harvester URL>/api/v1/namespaces/harvester-system/services/minio:http/proxy/minio/health/cluster`
and show a warning banner when minio is not available yet.

**Comment by DoNotSayYes** [comment]
Validated on master-head

**Steps:**
1. Add an image with URL http://a.img and the following error is expected.
`Get http://a.img: dial tcp: lookup a.img on 10.43.0.10:53: no such host`
2. Delete this image successfully
3. Delete the minio pods, UI will reflect the status of the image repository

![image](https://user-images.githubusercontent.com/57614736/105150376-aa1c9800-5b3f-11eb-839b-7d9a5bc72352.png)

![image](https://user-images.githubusercontent.com/57614736/105139648-7d618400-5b31-11eb-891a-035949d21dde.png)
