### ISSUE TITLE
[BUG] Volume setting missing from configured and running VM

### ISSUE THREAD

**Issue by depasseg** [harvester/harvester#3362]
**Describe the bug**
The volume information is missing (and can't be edited for a configured and  operational VM.  Because the volume configuration is missing, I am unable to save any other changes to the VM (if forces me to have the root volume configured, but prohibits me from making the change).

**To Reproduce**
I'm not sure what caused this, but it's happened a couple times and only seems to apply to VMs created with .IMG files as the root volume.

**Expected behavior**
The configured volume would be populated.

**Support bundle**

**Environment**
 - Harvester ISO version:  1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal cluster on 3 Intel NUCs, 64 GB RAM and 2TB NVMe SSD in each node.

**Additional context**
![image](https://user-images.githubusercontent.com/3201827/212138585-faa9719e-24f0-4e22-a6bf-af8097905a1e.png)

[supportbundle_a0df3d60-eb81-4f61-9325-274682f70c05_2023-01-12T17-29-14Z.zip](https://github.com/harvester/harvester/files/10406874/supportbundle_a0df3d60-eb81-4f61-9325-274682f70c05_2023-01-12T17-29-14Z.zip)

**Comment by ibrokethecloud** [comment]
@depasseg any chance we could please have a support bundle from this cluster?

**Comment by depasseg** [comment]
Oah sorry about that.  I created it and included the bug url in it, but I forgot to edit the bug report with the attachment.

**Comment by depasseg** [comment]
> @depasseg any chance we could please have a support bundle from this cluster?

It's there now.  Sorry about that.

**Comment by guntarsTB** [comment]
Same problem here.

Once I edit a working VM, I cannot save anything in the form, because volume becomes null. Editing as YAML works fine.
Workaround for the UI form:
1. Edit the VM in the form
2. Delete the volume from VM
3. Save the VM without a volume
4. Reopen the edit form
5. Add new Existing volume (but you still can't select any volume object, cause there are no matching options)
6. Add another Existing volume (even though there was one empty already)
7. For the second volume you can actually choose one
8. Remove the first one
9. Rename the second one to disk-1 (otherwise it would be disk-2)
10. Perform any other desired changes BEFORE you save the VM
Once you need to edit something more, the full list of steps can be repeated.

Version 1.1.1

**Comment by guntarsTB** [comment]
Another workaround that I just accidentally found:
1. Edit VM using the UI form
2. After editing (cannot save because Volume is missing) - click on Edit as YAML
3. Click on Show Diff
4. Find the line with "claimName: null" and copy the old value shown in Diff
5. Click on Continue editing
6. Replace the line with the old value
7. Click Save

**Comment by depasseg** [comment]
Good suggestion on the "Show Diff"  I didn't make any changes to the VM and it removed the volume from the config.
![image](https://user-images.githubusercontent.com/3201827/217075918-607ad805-48ab-4ece-b6a5-9022cd5a6e70.png)

**Comment by irishgordo** [comment]
I'm currently blocked in testing this on:
Harvester ISO version: Version: master-6fd9a5bb-head ( 02/10/23 master-head release )

Due to:
- https://github.com/harvester/harvester/issues/3462
- https://github.com/harvester/harvester/issues/3464

Since a backup-target can't be persisted/saved/created.

**Comment by irishgordo** [comment]
@n313893254 should the Volume that gets restored in "replace existing" vm be prefixed with "restore-"?

It looks like it does work but I want to validate that the volume naming is correct :smile: 

![Screenshot from 2023-02-16 18-48-39](https://user-images.githubusercontent.com/5370752/219537306-921967db-830f-4cab-9bc6-ccea2899958f.png)

**Comment by irishgordo** [comment]
@n313893254  - I did also notice that the Volume Snapshot name seems to be correct :smile: :
![Screenshot from 2023-02-22 11-56-11](https://user-images.githubusercontent.com/5370752/220744377-44bfc93b-d7a3-4b8c-a6f0-1a21c33249f5.png)
Just hoping to validate that a Volume that gets restored via "Replace Existing" becomes prefixed with "restore-*" in it's name.

**Comment by depasseg** [comment]
I'm sorry but I'm a little confused.  Nothing needs to be restored, and hopefully the name isn't being appended with anything.

The problem is that a running VM, using a root volume called  restore-myvirtualmachinenameblah (it was appended with restore when I originally restored that VM and has nothing to do with this issue)

The problem is that when I go into Edit the VM, the root volume is missing from the GUI, but if I look at the Diff, I can see that the GUI decided to remove the correct volume name. I shared up above.  I just need the GUI to decide to use the current volume name.

In the screenshot you can see the clainname on line 229 was changed to null for some unknown reason.  This can be edited via YAML which then allows me to edit other settings in the GUI. :
![image](https://user-images.githubusercontent.com/3201827/220747341-e5362f59-0597-4490-a3ea-b0b783d21004.png)

**Comment by irishgordo** [comment]
@depasseg thanks for the clarification :smile: 

With testing in v1.1.2-rc1 I'm noting that the `claimName` from the volume now is not appearing as `null` and does indeed show the correct current volume name :smile: :

![Screenshot from 2023-02-22 12-14-11](https://user-images.githubusercontent.com/5370752/220749147-c6d6565b-e325-4994-be59-e8a0030b7a7b.png)

I'll go ahead and close this out @n313893254 :smile:  - as validation passes on v1.1.2-rc1.
