### ISSUE TITLE
[DOC] Steps to evict a disk with CLI way

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3364]
**Is your feature request related to a problem? Please describe.**

Add steps to evict disks the CLI way.

**Describe the solution you'd like**

Add a KB document.

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
close as this is released on https://harvesterhci.io/kb/evicting-replicas-from-a-disk-the-cli-way
