### ISSUE TITLE
[BUG] disk expansion does not work with terraform provider

### ISSUE THREAD

**Issue by JWackerbauer** [harvester/harvester#3369]
I'm not sure if this is the right place to report issues with the harvester terraform provider but here it geos anyway: 

When modifying the size of a disk with the terraform provider the VM reboots as expected but no change is made to the disk. I suspect this is because the API call does not propperly wait for the disk to become detatched and silently fails.

**Comment by w13915984028** [comment]
cc @futuretea any idea? thanks.

**Comment by futuretea** [comment]
Same issue: https://github.com/harvester/harvester/issues/2810
Will support this feature in https://github.com/harvester/harvester/pull/3191
