### ISSUE TITLE
[BUG] App mode is failed to install with longhorn-namespace not found

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#337]
**Describe the bug**

App mode installation is failed due to an incorrect longhorn chart config

**To Reproduce**
1. Helm install the harvester chart

**Expected behavior**

`Failed to install app harvester-system. Error: namespaces "longhorn-system" not found`

**Log**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
Validated in master 12/16
Env: 
1. single AWS ubuntu node cluster
2. 3 nodes cluster

I can deploy harvester via `helm install`.
I can deploy harvester via rancher catalogs.
