### ISSUE TITLE
[BUG] Older versions of the Harvester plugin have style compatibility issues with the latest version of Rancher

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3373]
**Describe the bug**

Older versions of the Harvester plugin have style compatibility issues with the latest version of Rancher

**To Reproduce**

1. Install v2.7.0 Rancher and change the settings `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html` and `ui-offline-preferred ` to `Remote`
2. Install Harvester and change settings `ui-plugin-index` to `https://releases.rancher.com/harvester-ui/plugin/harvester-v1.1.1/harvester-v1.1.1.umd.min.js` and `ui-source` to `External`
3. Rancher Import Harvester cluster
4. Go to the Harvester from Rancher UI and check the VM create page

**Result**

The "Create" button styles have a compatibility issue, displayed on the left.

**Expected Result**

The "Create" button displayed on the right

**Screenshots**

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/18737885/212627830-fe6cff86-f008-456d-9a09-941d4262740d.png">

**Additional context**

The upstream issue is https://github.com/rancher/dashboard/issues/7942

**Comment by n313893254** [comment]
Validation the issue has been fixed, and move the pipeline to ready for testing. The validation steps are the same as the reproduce [steps](https://github.com/harvester/harvester/issues/3373#issue-1534490215).

![image](https://user-images.githubusercontent.com/18737885/213346539-b3530925-e045-4d1d-961c-52124eacf8dd.png)

**Comment by noahgildersleeve** [comment]
Tested in Harvester v1.1.0 and master with Rancher v2.7.0 with repro steps. I was unable to repro the fail state, but the UI looks correct in both circumstances. 

![Screenshot_20230119_134240](https://user-images.githubusercontent.com/83787952/213568479-302f0263-9bc2-44cf-9f69-e02927278664.png)

> **Describe the bug**
> 
> Older versions of the Harvester plugin have style compatibility issues with the latest version of Rancher
> 
> **To Reproduce**
> 
> 1. Install v2.7.0 Rancher and change the settings `ui-dashboard-index` to `https://releases.rancher.com/dashboard/latest/index.html` and `ui-offline-preferred ` to `Remote`
> 2. Install Harvester and change settings `ui-plugin-index` to `https://releases.rancher.com/harvester-ui/plugin/harvester-v1.1.1/harvester-v1.1.1.umd.min.js` and `ui-source` to `External`
> 3. Rancher Import Harvester cluster
> 4. Go the Harvester from Rancher UI and check the VM create page
> 
> **Result**
> 
> The "Create" button styles have a compatibility issue, displayed on the left.
> 
> **Expected Result**
> 
> The "Create" button display on the right
> 
> **Screenshots**
> 
> <img alt="image" width="1680" src="https://user-images.githubusercontent.com/18737885/212627830-fe6cff86-f008-456d-9a09-941d4262740d.png">
> 
> **Additional context**
