### ISSUE TITLE
[BUG] Can not create RKE2 cluster after enabling Elemental extension

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3374]
**Rancher Server Setup**

- Rancher version: v2.7.0

**Describe the bug**

Can not create RKE2 cluster after enabling Elemental extension

**To Reproduce**

1. Install Rancher v2.7.0 by docker
2. Enable the extension feature and install the Elemental extension
3. Go cluster create the page, and check to create an RKE2 cluster,  e.g. Harvester or Linode

**Result**

Can not create RKE2 cluster as pending in create new cloud credential.

**Expected Result**

Can create RKE2 cluster

**Screenshots**

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/18737885/212695788-98064405-635d-48f0-8069-04cfc755f939.png">

**Additional context**

The upstream issue is https://github.com/rancher/dashboard/issues/8059

**Comment by abonillabeeche** [comment]
Isn't this already resolved when using the Elemental 1.0.0 Plugin?

**Comment by n313893254** [comment]
There is a compatibility issue with the Elemental 1.0.0 Plugin, please wait for the release of v1.0.1 and upgrade it to v1.0.1 to fix the issue. As far as I know, v1.0.1 is expected to be released next week.

This issue can be tested after Elemental released v1.0.1.

Verify Steps:
1. Install the latest Rancher
2. Click the user menu and then go to the "Preferences" page, checked "Enable Extension developer features" under the "Advanced Features"
3. Go to "Extensions" on the left side menu, and then click the right side dropdown, select "Developer Load"
4. The "Extension URL" is `https://raw.githubusercontent.com/rancher/elemental-ui/70a3fed61790a35df59eb8b9a9e066ff193779f2/extensions/elemental/1.0.1/plugin/elemental-1.0.1.umd.min.js`. 
5. Checked "Persist extension by creating custom resource" and then click the save button.
6. There will be an error notification, ignore it. Click the cancel button and then click the reload button.
7. Now the elemental v1.0.1 has successfully loaded, the next steps are to check to create RKE2 clusters.

<img width="1139" alt="image" src="https://user-images.githubusercontent.com/18737885/219374535-5d0fb318-2f48-479f-8bab-46f3cace4a74.png">

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.7-head` (ab561bf) with Harvester `v1.1.2-rc1`. Close this issue.

### Result
After enable the extension support and install the Elemental extension v1.0.1 
We can create cloud credential and provision RKE2 cluster correctly
  
  ![image](https://user-images.githubusercontent.com/29251855/220080646-181dff7f-fe98-4d10-9fd6-71dfe88e2fc2.png)
  ![image](https://user-images.githubusercontent.com/29251855/220082306-7147aa01-0d87-416a-85b0-bf4148bb3525.png)


### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `v1.1.2-rc1`
* Rancher version: `v2.7-head` (ab561bf) 
* Elemental extension: v1.0.1 

### Verify Steps
https://github.com/harvester/harvester/issues/3374#issuecomment-1418491382
