### ISSUE TITLE
[FEATURE] codegen consistency by using dapper

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#3375]
**Is your feature request related to a problem? Please describe.**

Currently while developing harvester, the codegen utilities need to be executed locally.
However across different platforms it seems the openapi codegen indents code differently, as a result the CI reports failures as it detects a diff.

In addition, different version of openapi-gen / controller-gen can render slightly different generated code/manifests. 

**Describe the solution you'd like**

Create a new `generate` target for dapper builds allowing code generation to be run via Dapper in a container.
This should ensure consistent code generation environment.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
@ibrokethecloud The PR was merged, should we close this issue?

Meanwhile, seems many of Harvester repos do not have a dapper based `go generate`.
