### ISSUE TITLE
[ENHANCEMENT] validate not to add partitioned volumes as additional data volume

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3381]
**Is your feature request related to a problem? Please describe.**
As of Harvester v1.0.2, we no longer support adding partitions as additional disks. If you want to add it as an additional disk, be sure to delete all partitions first (e.g., using fdisk). 

But from the UI, we are missing proper warning messages and it is even better if we could prevent adding partition disks as additional volumes.

**Describe the solution you'd like**
1. adding proper warning messages on the UI.
2. prevent adding partition disks as additional volumes.

**Describe alternatives you've considered**
N/A

**Additional context**
refer to https://github.com/harvester/harvester/issues/2551

**Comment by torchiaf** [comment]
Ui side: 1. Add a warning message and 2. block additional partitions, based on some logic. It should be straightforward but depends on information provided by the backend.
