### ISSUE TITLE
[BUG] Downloading large supportbundle via weak connection fails / never completes

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3383]
**Describe the bug**
We are creating the supportbundle via Harvester UI and then the download starts but fails after downloading some data / partial download.

Client browser is firefox on windows, connection is via VPN and proxy.

Unfortunately there is no resume possible to download and the supportbundle can not be downloaded via other ways i.e. via scp.

Not sure if this is related - but In the logs of the supportbundle pod we see this:

```
time="2023-01-18T08:12:50Z" level=info msg="succeed to run phase package. Progress (80)."
time="2023-01-18T08:12:50Z" level=info msg="running phase done"
time="2023-01-18T08:12:50Z" level=info msg="support bundle /tmp/support-bundle-kit/supportbundle_1109c105-b0ef-44b0-a1c0-e00eff121ee7_2023-01-18T08-11-58Z.zip ready to download"
time="2023-01-18T08:12:50Z" level=info msg="succeed to run phase done. Progress (100)."
2023/01/18 08:13:21 http: superfluous response.WriteHeader call from github.com/rancher/support-bundle-kit/pkg/utils.HttpResponseErrorMsg (http.go:36)
time="2023-01-18T08:13:21Z" level=error msg="readfrom tcp 10.52.1.30:8080->10.52.0.84:35964: i/o timeout"
```

In addition to that we can not even find an already created supportbundle to be downloaded from an other machine. We always have to re-generate a complete support bundle from scratch.

**To Reproduce**
- connect to harvester UI via low bandwidth / high latency connection
- create support bundle and download it

**Expected behavior**
- download should complete
- resume of download should be possible
- download of previously generated support bundles should be possible

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**
Maybe we could store the generated supportbundles in a longhorn volume and provide the list of them via the harvester UI?

**Comment by Martin-Weiss** [comment]
Also a kubectl cp does not seem to work:

```
kubectl -n harvester-system cp supportbundle-manager-bundle-mdizv-79f46c7-c4vjc:/tmp/support-bundle-kit/supportbundle_1109c105-b0ef-44b0-a1c0-e00eff121ee7_2023-01-18T08-11-58Z.zip .
error: Internal error occurred: error executing command in container: failed to exec in container: failed to start exec "075f399b25a578032236e20165db49829891722c567f3cc0c3710021abfd1df9": OCI runtime exec failed: exec failed: unable to start container process: exec: "tar": executable file not found in $PATH: unknown
```

**Comment by bk201** [comment]
kubectl cp requires `tar` to present in the container, please try (if got Internet):
```
kubectl exec -it -n harvester-system supportbundle-manager-bundle-mdizv-79f46c7-c4vjc -- zypper in -y tar
```
and copy it out:
```
kubectl cp harvester-system/supportbundle-manager-bundle-mdizv-79f46c7-c4vjc:/tmp/support-bundle-kit/supportbundle_1109c105-b0ef-44b0-a1c0-e00eff121ee7_2023-01-18T08-11-58Z.zip bundle.zip
```

**Comment by Martin-Weiss** [comment]
Unfortunately we have air-gapped... and we still should find a way to keep previous supportbundles for download again ad we should add support for resume download..

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2.0-rc4**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, navigate to _Advanced/Settings_ page
3. Update `support-bundle-image` settings
```json
{
  "repository": "webberhuang/support-bundle-kit",
  "tag": "v0.0.25-2gb-sb-testing",
  "imagePullPolicy": "Always"
}
```
4. Navigate to _Support_ page, generate support bundle
5. Support bundle should be generated and downloaded successfully

**Comment by w13915984028** [comment]
Regarding @Martin-Weiss 's question, we can use following workaroud at the moment. I will add them to trouble-shooting

1. Click `Generate supportbundle` from Harvester WebUI
2. When the progress is about 20%, close the WebUI page
3. Check support-bundle status from kubectl
```
# kubectl get supportbundle -A -oyaml
apiVersion: v1
items:
- apiVersion: harvesterhci.io/v1beta1
  kind: SupportBundle
  metadata:
    creationTimestamp: "2024-02-02T11:18:09Z"
    generation: 5
    name: bundle-htl5f
    namespace: harvester-system
    resourceVersion: "1218311"
    uid: a3776373-05fe-4584-8a9a-baac3fa91bbf
  spec:
    description: sp1
    issueURL: ""
  status:
    conditions:
    - lastUpdateTime: "2024-02-02T11:18:38Z"
      status: "True"
      type: Initialized
    filename: supportbundle_db25ccb6-b52a-4f9d-97dd-db2df2b004d4_2024-02-02T11-18-10Z.zip
    filesize: 8868712
    progress: 100
    state: ready
kind: List
metadata:
  resourceVersion: ""
```
4. curl/wget the SB file via
```
curl -k https://192.168.122.199/v1/harvester/supportbundles/bundle-htl5f/download?retain=true -o sb2.zip
```
5. check the SB, it's still there
```
 # kubectl get supportbundle -A
NAMESPACE          NAME           ISSUE_URL   DESCRIPTION   AGE
harvester-system   bundle-htl5f               sp1           114s
```
6. Those 2 setting will help clean the resources.
https://docs.harvesterhci.io/v1.3/advanced/index#support-bundle-timeout
https://docs.harvesterhci.io/v1.3/advanced/index#support-bundle-expiration

And we can continue enhance:
(1) WebUI supports `retain` param when click `Generate supportbundle`
(2) WebUI supports download SB files from existing support-bundle, and user can still select `retain` to keep it.
Fetch all below if it's progress is 100
```
kubectl get supportbundle -A
```

I will log those in another issue.
