### ISSUE TITLE
CloudQuery Harvester Source Plugin

### ISSUE THREAD

**Issue by yevgenypats** [harvester/harvester#3387]
Hi Team, hopefully this is right place to ask, if not, I'd appreciate if you can direct me.

I'm the founder of [cloudquery.io](https://www.cloudquery.io/), a high performance open source ELT framework. 

Our users are interested in a Harvester plugin, but as we cannot maintain all the plugins ourselves, I was curious if this would be an interesting collaboration, where we would help implement an initial [source plugin](https://www.cloudquery.io/docs/plugins/sources/overview), and you will help maintain it.

This will give your users the ability to sync Harvester data to any of their datalakes/data-warehouses/databases easily using any of the growing list of CQ [destination plugins](https://www.cloudquery.io/docs/plugins/destinations/overview).

Best,
Yevgeny

**Comment by w13915984028** [comment]
@yevgenypats It sounds a good idea. How would you like to start ?

**Comment by yevgenypats** [comment]
@w13915984028 Awesome! Can you please open an empty repo at https://github.com/harvester/cq-source-harvester (with empty README) so we can fork and open a PR  ?

**Comment by w13915984028** [comment]
@yevgenypats We have an new repo now: https://github.com/harvester/cq-source-harvester

**Comment by w13915984028** [comment]
No further response, close. Feel free to reopen, thanks.
