### ISSUE TITLE
The network dropdown shows no matching options when adding a network to a VM

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#339]
**Steps to reproduce:**
1. Add a network on the VM create/edit page, name it `dolly-test001`
2. Expand the network dropdown, only one option is available, then expand the dropdown again

**Result:**
The dropdown shows no matching options
![image](https://user-images.githubusercontent.com/57614736/102037899-eeaa6a80-3e00-11eb-800a-d5345690a23e.png)
![image](https://user-images.githubusercontent.com/57614736/102037909-f5d17880-3e00-11eb-837e-ce107822e40f.png)

**Comment by WuJun2016** [comment]
fixed:   https://github.com/rancher/harvester/issues/330

**Comment by DoNotSayYes** [comment]
Still can be reproduced

**Steps:**
1. On the VM create page, add multiple networks
2. CHeck the network dropdown of the default network

![image](https://user-images.githubusercontent.com/57614736/102167108-aeaeba80-3ec8-11eb-84b6-098530d8c0b7.png)

**Comment by DoNotSayYes** [comment]
Validated
