### ISSUE TITLE
[BUG] Can not control qemu-guest-agent cloud-init from RKE2 & RKE1 Creation

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3392]
**Describe the bug**
When creating an RKE2 cluster on Harvester, there is no current way to prevent the injection of:
```yaml
packages:
  - qemu-guest-agent
runcmd:
  - - systemctl
    - enable
    - --now
    - qemu-guest-agent
```
In, https://github.com/harvester/harvester/issues/2002 , it was implemented to have the `install guest agent` box checked by default on VM creation.
And that seems to get merged into an RKE2 cloud-config user data, when blank or when there is content like:
```yaml
bootcmd:
  - echo "hello"
```

**To Reproduce**
1. Import Harvester into Rancher, build cloud-credentials
1. Create RKE2 Cluster, leaving user-data blank - validate that `qemu-guest-agent` on the VM provisioning exists
1. Create RKE2 Cluster, entering some user-data - validate that `qemu-guest-agent` on the VM provisioning exists
 
**Expected behavior**
There to be some method in place to replicate what VM Creation allows of either having the checkbox checked or not checked.  As to not break air-gapped cluster provisioning when air-gapped image already has qemu-guest

**Environment**
 - Harvester ISO version: v1.1.1
 - Rancher: v2.7.0
 - Underlying Infrastructure: 3 node bare metal harvester cluster, Rancher running in a Docker container

**Additional context**
![Screenshot from 2023-01-26 09-20-02](https://user-images.githubusercontent.com/5370752/214916909-de8e5ea1-5898-45b9-9eda-877378c85f39.png)
![Screenshot from 2023-01-26 09-11-02](https://user-images.githubusercontent.com/5370752/214916913-16067a05-a2d0-4bbe-93d9-805d4e078808.png)
![Screenshot from 2023-01-26 09-10-06](https://user-images.githubusercontent.com/5370752/214916917-134d9269-dfc7-456a-a8b8-4af9f8b082a0.png)
![Screenshot from 2023-01-26 09-11-25](https://user-images.githubusercontent.com/5370752/214916922-ba328881-621d-499d-a6d5-478351d2aade.png)

**Comment by abonillabeeche** [comment]
Please schedule for 1.2. We should have these fields as reference like we do for VMs and documented but we need to be able to remove these if necessary like on an air-gapped env.

**Comment by bcdurden** [comment]
I'm also having this issue. Harvester has a checkbox in the UI to disable this package, but the Harvester node provisioner in Rancher MCM does not. Would like to see this fixed in 1.1.2 if possible

**Comment by WuJun2016** [comment]
Hi @irishgordo  Can you help verify this problem first ？ It has been merged into rancher 2.7.2.    

Scope of verification: ` rke2` & `rke1`

**Comment by irishgordo** [comment]
**validation issue**
Hi @WuJun2016 
I did try validating this, but I'm having trouble importing the Harvester cluster v1.1.2-rc3 into Rancher v2.7.2-rc6:
Should I be using something like Harvester v1.1-head?
![Screenshot from 2023-03-16 16-41-26](https://user-images.githubusercontent.com/5370752/225776369-5aed5d8a-60fc-4ba4-99e1-ab2794df671f.png)
It seems like the `cattle-cluster-agent` in the `cattle-system` namespace on the deployment keeps having pods restart and the Harvester Cluster in the Virtualization Management section stays at the `unavailable` point:

SupportBundle:
[supportbundle_c4d2ad15-6a20-4ea3-9fe4-c548943c2b58_2023-03-16T23-45-43Z.zip](https://github.com/harvester/harvester/files/10996655/supportbundle_c4d2ad15-6a20-4ea3-9fe4-c548943c2b58_2023-03-16T23-45-43Z.zip)

**Comment by WuJun2016** [comment]
I think testing this issue with any `harvester` version should be fine.    
The problem you encountered can't be imported, it should be a other problem, it may be a problem of your environment, if you keep encountering it, you can file an issue, let the back-end colleagues help to investigate

**Comment by irishgordo** [comment]
**validation issue:**

@WuJun2016 I was able to import Harvester to Rancher, it may have just been an environmental issue more than anything else :sweat_smile: - thank you again for mentioning that.

Should I be editing Rancher's Global Settings to change the UI Source or KDM?
I'm unable to select:
"Harvester (Out-of-tree)"
When trying to build an RKE1 Cluster, without the "qemu-guest-agent" in validation/testing on Rancher v2.7.2-rc6
![Screenshot from 2023-03-17 15-17-21](https://user-images.githubusercontent.com/5370752/226062876-9af48cd9-d093-4f21-a9eb-ba0cd2e128c2.png)

**Comment by WuJun2016** [comment]
Hi, @irishgordo   
> I'm unable to select:
"Harvester (Out-of-tree)"

you should enter a "Cluster Name", select a node template and use imported credential to enable this option.


<img width="1693" alt="image" src="https://user-images.githubusercontent.com/24985926/226102272-ef96e8fb-a1b2-4fb3-96ec-c62f2d45e16f.png">
sorry, `rke1` is here, I forgot the screenshot

**Comment by irishgordo** [comment]
@WuJun2016  - this looks good on Rancher v2.7.2-rc6 w/ v1.1.2-rc3
Validated that the cloud-configs on vms also do not have the guest agent when the option on either RKE/RKE1 or RKE2 is toggled off.
![Screenshot from 2023-03-21 18-29-41](https://user-images.githubusercontent.com/5370752/226779851-04061ca4-040c-49f6-9b39-a4d947276001.png)
I'll go ahead and close this out :+1: :smile: !
