### ISSUE TITLE
[Question] Can you provide instructions to install harvester without VGA (headless)

### ISSUE THREAD

**Issue by thooooooomas** [harvester/harvester#3393]
Can you provide instructions to install harvester without VGA (headless)

When I launch harvester as a boot disk, I see this in the serial console (ttyS0)

Welcome to SUSE Linux Enterprise Micro for Rancher 5.2  (x86_64) - Kernel 5.3.18-150300.59.101-default (ttyS0).

ens4:  

rancher login: 

I can then input the rancher/rancher login and access the file system. However I am unsure how to input all the options to install harvester. When I see this prompt, is harvester installed fully? Would love directions here

**Comment by MaxRenaud** [comment]
+1

**Comment by abonillabeeche** [comment]
In order to do so without a monitor, please use [this](https://docs.harvesterhci.io/v1.1/install/harvester-configuration) which is referenced in our [PXE](https://docs.harvesterhci.io/v1.1/install/pxe-boot-install) docs.

**Comment by thooooooomas** [comment]
@abonillabeeche I'd like to avoid using PXE boot for now and go with a manual install, however in the manual install, how do I pass the config file?

In the manual install [doc](https://docs.harvesterhci.io/v1.1/install/iso-install), it references the config file only at step 13 - (Optional) If you need to customize the host with a [Harvester configuration](https://docs.harvesterhci.io/v1.1/install/harvester-configuration) file, enter the HTTP URL here. Which I cannot do as I have to install it headless

Is it possible to go through the steps through the serial console? This seems to be achievable from this issue: https://github.com/harvester/harvester/issues/485#issuecomment-810016351

**Comment by Martin-Weiss** [comment]
@thooooooomas - I have build some solution based on “mini boot ISO” - maybe this helps? 
https://github.com/Martin-Weiss/cif/tree/master/boot_cd_build 

On the ISO I “just” take the initrd and kernel for harvester and add the right boot parameters to specify the harvester configuration file…

**Comment by thooooooomas** [comment]
thanks @Martin-Weiss, I ended up changing this file and doing `make` to make a new iso
https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/iso/boot/grub2/grub.cfg#L25

I changed the `console=tty1 console=ttyS0` to `console=ttyS0 console=ttyS1`

**Comment by w13915984028** [comment]
@guangbochen @bk201 how do you think about this `feature` ?  was it ever discussed?

**Comment by thooooooomas** [comment]
I've managed to make it to the Configure Network page which I'm viewing through ttyS0
<img width="616" alt="Screenshot 2023-02-01 at 2 57 19 PM" src="https://user-images.githubusercontent.com/123783350/216184939-da1953d5-8a31-4b3c-8b5c-8e7a50a5253e.png">

I am having trouble moving forward. After selecting a Management NIC by pressing TAB and then Space to check the NIC I want to select, when I press enter it automatically goes back to the first page 
<img width="641" alt="Screenshot 2023-02-01 at 2 59 39 PM" src="https://user-images.githubusercontent.com/123783350/216185311-c6feee09-edd2-4433-9f43-ea55373a6fd9.png">

Why is this happening? Is there a specific key I need to press to move forward? Or is there some error?

**Comment by thooooooomas** [comment]
Seems the issue with it restarting at the first page is related to this issue and the workaround is detailed (setterm --resize)
https://github.com/harvester/harvester/issues/2708#issuecomment-1244965316

**Comment by thooooooomas** [comment]
After I put in my configuration, harvester starts installing and then it says it will restart after a few seconds. After restart, it just starts the installer again.. I don't think it installed properly, any tips on how to debug this?

**Comment by guangbochen** [comment]
> After I put in my configuration, harvester starts installing and then it says it will restart after a few seconds. After restart, it just starts the installer again.. I don't think it installed properly, any tips on how to debug this?

what is your disk boot order? you may need to eject the cd-rom first or set the boot order properly by booting from the disk if it is not empty.

**Comment by thooooooomas** [comment]
> > After I put in my configuration, harvester starts installing and then it says it will restart after a few seconds. After restart, it just starts the installer again.. I don't think it installed properly, any tips on how to debug this?
> 
> what is your disk boot order? you may need to eject the cd-rom first or set the boot order properly by booting from the disk if it is not empty.

I'm not too sure where to set the disk boot order.. I have a boot disk (in this case the harvester iso), the install disk where I told harvester installer to install to, and a vm disk where I told harvester installer to store VM data to.

I am looking at what happens to the install disk after harvester installs onto it and when I run 
`file -s /dev/sdb` it says `/dev/sdb: DOS/MBR boot sector` whereas if I run 
`file -s /dev/sda` (which is the harvester iso boot disk) it says
`/dev/sda: DOS/MBR boot sector; GRand Unified Bootloader, stage1 version 0x79, boot drive 0xbb, stage2 address 0x8e70, 1st sector stage2 0xb8db31c3, stage2 segment 0x201`

Is it expected that the install disk does not have GRUB installed? I'm trying to figure out what selects the install disk to boot instead of the iso boot disk and what should be the initial boot command after harvester is installed?

I tried to make the install disk be the boot disk but it did not boot. I believe this is what you meant by setting boot order correct? To make the install disk be the boot disk if it is not empty. My assumption is that it did not boot as it does not have GRUB on that disk after install

Let me know if anything I'm saying doesn't make sense, I'm quite new to this

**Comment by ibrokethecloud** [comment]
just to confirm, the installation must have been performed using the ISO based method? From what you have described whatever device the ISO was imaged to is prioritized in the boot order.

**Comment by thooooooomas** [comment]
> just to confirm, the installation must have been performed using the ISO based method? From what you have described whatever device the ISO was imaged to is prioritized in the boot order.

Correct it was installed from ISO. After install I removed the device that the ISO was imaged to and tried to boot from the install disk. It wouldn't boot, when I take a look at the install disk with `file -s /dev/sdb` it says `/dev/sdb: DOS/MBR boot sector` - it seems there is no GRUB on the install disk, is that expected?

When I look at the ISO disk (sda), in sda1 I see
EFI  boot  bundle  harvester-release.yaml  rootfs.squashfs
When I look at the install disk (sdb), in sdb1 I see 
99_custom.yaml	grubenv  harvester.config  install  lost+found
and in sdb2 I see
cOS  grub2  grub_oem_env  grubmenu  lost+found

There is no boot folder to be found in the install disk. When I look at the boot folder in the ISO disk, I see
grub2  kernel.xz  rootfs.xz  uefi.img  x86_64
In the ISO disk I can find the kernel just fine but I fail to find a kernel in the install disk. Is this expected? How do I further debug why my install disk is not bootable

**Comment by thooooooomas** [comment]
Nevermind my last command, I am able to boot from the install disk (not sure what changed on my end)

**Comment by thooooooomas** [comment]
I am able to boot from the install disk after appending 
`console=ttyS0,115200n8`
to the lines starting with `linux` in the grub2/grub.cfg file as detailed here:
https://docs.harvesterhci.io/v1.1/troubleshooting/os#collect-crash-log

This is because my system only has serial consoles and I don't have access to tty1 which is the default

Going to close as my other questions are post install, thanks for all the help everyone
