### ISSUE TITLE
[ENHANCEMENT] Allow customization of Harvester Web Page Name / Tab Name

### ISSUE THREAD

**Issue by Martin-Weiss** [harvester/harvester#3396]
**Is your enhancement related to a problem? Please describe.**
See this screenshot and try to identify which of the tabs belongs to which harvester instance:

![grafik](https://user-images.githubusercontent.com/13362573/215423284-61e694f3-2a5b-4247-9728-394d607f52dc.png)

**Describe the solution you'd like**
Each Harvester instance should allow customization / rename / logo change for the name in the browser.
i.e. harvester-staging, harvester-production, harvester-dr,..

**Describe alternatives you've considered**
Dids not find one

**Additional context**
I guess we need something similar in Longhorn and Rancher as well. https://github.com/harvester/harvester/issues/3442

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/cf0191ac-e71f-4f6f-8e90-239a41f4f393)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-27934bc3-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, navigate to `Advanced/Settings` -> UI
3. Edit `branding` settings, change every settings, UI should be updated accordingly
4. Remove customized options, UI should be updated accordingly
