### ISSUE TITLE
[Need solution to renew harvester CA certificate]

### ISSUE THREAD

**Issue by midhunthampi** [harvester/harvester#3401]
**Is your doc request related to a problem? Please describe or add related issue ID.**

**Describe the solution you'd like**

**Comment by midhunthampi** [comment]
We see the control plane certificate's are expiring in one year and Harvester CA certificate has 10 year validity. Here we are looking for solution to renew the certificates in every regular interval.

**Comment by Martin-Weiss** [comment]
@midhunthampi  - do you request to renew the Harvester CA more often than every 10 years or “just the control plane certificates”?

**Comment by midhunthampi** [comment]
yes @Martin-Weiss We need to renew the harvester CA more often than every 10 year and also need to know how to renew control plane certificates.

What will happen if these control certificates expire ?

**Comment by Martin-Weiss** [comment]
@midhunthampi  - how often do you need to replace the CA and why? 

What are your rules / best practices on how often to renew a CA certificate best practice for lifetime of CA cert in comparison to issued certificates? 

(Renewing ahead of time most often only makes sense in case certificate revocation lists are used.. )

Regarding the control plane certificates - this is part of RKE2 certificate renewal - see https://docs.rke2.io/advanced 

Regarding the Harvester UI / API certificate - that can be replaced trough the UI at any time.

**Comment by midhunthampi** [comment]
@Martin-Weiss Our best practices to renew all certificates in every 6 months.

**Comment by midhunthampi** [comment]
Regarding the Harvester UI / API certificate - that can be replaced trough the UI at any time. - How we can replace these certificates ?

**Comment by midhunthampi** [comment]
@Martin-Weiss I tried to renew control plane certificates on one of master node but service didn't come up after certificate rotation.

xxxxxxxxxxxxxxxxxxx:/var/lib/rancher/rke2/server/tls # systemctl stop rke2-server
xxxxxxxxxxxxxxxxxxx:/var/lib/rancher/rke2/server/tls # rke2 certificate rotate
INFO[0000] Server detected, rotating server certificates
INFO[0000] Rotating certificates for admin service
INFO[0000] Rotating certificates for etcd service
INFO[0000] Rotating certificates for api-server service
INFO[0000] Rotating certificates for controller-manager service
INFO[0000] Rotating certificates for cloud-controller service
INFO[0000] Rotating certificates for scheduler service
INFO[0000] Rotating certificates for rke2-server service
INFO[0000] Rotating dynamic listener certificate
INFO[0000] Rotating certificates for rke2-controller service
INFO[0000] Rotating certificates for auth-proxy service
INFO[0000] Rotating certificates for kubelet service
INFO[0000] Rotating certificates for kube-proxy service
INFO[0000] Successfully backed up certificates for all services to path /var/lib/rancher/rke2/server/tls-1675371119, please restart rke2 server or agent to rotate certificates
xxxxxxxxxxxxxxxxxxx:/var/lib/rancher/rke2/server/tls # systemctl start rke2-server

^C

**Comment by midhunthampi** [comment]
Seeing this error
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[25793]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See h>
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[25793]: Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config f>
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[25793]: Flag --stderrthreshold has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/mas>
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[25793]: Flag --tls-cert-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See>
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[25793]: Flag --tls-private-key-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config fl>
Feb 02 21:10:17 las01-harv-vhs02-3s rke2[18991]: time="2023-02-02T21:10:17Z" level=error msg="Kubelet exited: exit status 1"
Feb 02 21:10:20 las01-harv-vhs02-3s rke2[18991]: time="2023-02-02T21:10:20Z" level=info msg="Container for etcd not found (no matching container found), retrying"
Feb 02 21:10:20 las01-harv-vhs02-3s rke2[18991]: {"level":"warn","ts":"2023-02-02T21:10:20.427Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying>
Feb 02 21:10:20 las01-harv-vhs02-3s rke2[18991]: time="2023-02-02T21:10:20Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Feb 02 21:10:21 las01-harv-vhs02-3s rke2[18991]: time="2023-02-02T21:10:21Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1>

**Comment by midhunthampi** [comment]
We see these errors.

Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[25793]: Flag --resolv-conf has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See h>
Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[25793]: Flag --serialize-image-pulls has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config f>
Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[25793]: Flag --stderrthreshold has been deprecated, will be removed in a future release, see https://github.com/kubernetes/enhancements/tree/mas>
Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[25793]: Flag --tls-cert-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config flag. See>
Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[25793]: Flag --tls-private-key-file has been deprecated, This parameter should be set via the config file specified by the Kubelet's --config fl>
Feb 02 21:10:17 xxx-xxx-xxx-xx rke2[18991]: time="2023-02-02T21:10:17Z" level=error msg="Kubelet exited: exit status 1"
Feb 02 21:10:20 xxx-xxx-xxx-xx rke2[18991]: time="2023-02-02T21:10:20Z" level=info msg="Container for etcd not found (no matching container found), retrying"
Feb 02 21:10:20 xxx-xxx-xxx-xx rke2[18991]: {"level":"warn","ts":"2023-02-02T21:10:20.427Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying>
Feb 02 21:10:20 xxx-xxx-xxx-xx rke2[18991]: time="2023-02-02T21:10:20Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Feb 02 21:10:21 xxx-xxx-xxx-xxrke2[18991]: time="2023-02-02T21:10:21Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1

**Comment by midhunthampi** [comment]
Feb 02 21:17:25 xxx-xxx-xxx-xx rke2[26681]: {"level":"warn","ts":"2023-02-02T21:17:25.553Z","logger":"etcd-client","caller":"v3@v3.5.4-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed",>
Feb 02 21:17:25 xxx-xxx-xxx-xx rke2[26681]: time="2023-02-02T21:17:25Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Feb 02 21:17:26 xxx-xxx-xxx-xx rke2[26681]: time="2023-02-02T21:17:26Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal>
Feb 02 21:17:28xxx-xxx-xxx-xx rke2[3094]: I0202 21:17:28.009079    3094 log.go:195] http: TLS handshake error from xx.xx.xx.xxx:26036: remote error: tls: bad certificate

**Comment by Martin-Weiss** [comment]
@midhunthampi  - renewing server certificates every 6 months might be valid but renewing the CA certificate every 6 months is basically against the concept and idea behind the CA and certificate management. Keep in mind that the CA certificate needs to be added in all clients trusted CA store.

Regarding the issue above - I have no idea what is causing this..
Could you check if this issue goes away when rebooting the node?
Could you check if this issue goes away when adding the CA cert to /etc/pki/trust/anchors and running update-ca-certificates and rebooting after that?

There is a backup created - maybe you can rollback:

`INFO[0000] Successfully backed up certificates for all services to path /var/lib/rancher/rke2/server/tls-1675371119, please restart rke2 server or agent to rotate certificates`

For Harvester UI cert - see https://docs.harvesterhci.io/v1.1/advanced/settings#ssl-certificates . This is also available in the configuration via UI.

**Comment by midhunthampi** [comment]
@Martin-Weiss Host looks good after rebooting. Not sure why service was not starting before the reboot.
