### ISSUE TITLE
[Question]Pager Duty integration 

### ISSUE THREAD

**Issue by KyleSponz** [harvester/harvester#3403]
I am trying to wire up pagerduty in monitoring and it wont let me edit a to send alerts and I cant enter any of my pager duty credentials

No matter which I use eventsapi or promethus it will not let me enter anything other than none 

 please advise?

<img width="1319" alt="Screen Shot 2023-02-01 at 3 39 30 PM" src="https://user-images.githubusercontent.com/2746903/216158548-35b25ad8-e535-4606-a36c-fc569147a9c3.png">

**Comment by w13915984028** [comment]
@DaiYuzeng could you have a quick valdate of the related UI, thanks.
