### ISSUE TITLE
[BUG] fix invalid havester-csi-ccm-versions setting

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3404]
**Describe the bug**

The current default value for the `harvester-csi-ccm-versions` setting is invalid because it restricts to an invalid maximum version, and prevents users from successfully selecting the Harvester cloud provider when creating or modifying the RKE2 Kubernetes cluster.

Original issue： - https://github.com/harvester/harvester/issues/3389

Impacted version: Rancher >= v2.6.9, v2.7.0 + RKE2 with Harvester CCM >= v0.1.15 (starting from RKE Year 23 Jan. Releases)

`v1/harvester/harvesterhci.io.settings/harvester-csi-ccm-versions`   

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/1de4e9a3-3ee6-4e0f-8574-757a69d8f2e0)

**To Reproduce**
1. import Harvester (<= v1.1.2-rc3) into a upstream Rancher (v2.6.9 or v2.7-head)
2. trying to create a new RKE2 cluster with newer RKE2 versions
3. user will not be able to select the `Harvester` cloud provider as its default `harvester-csi-ccm-versions` setting version is less than the RKE2's built-in one.

**Expected behavior**
Users should still be able to select the `Harvester` cloud provider as the latest RKE2's built-in Harvester CSI & CCM chart is compatible with Harvester v1.1 clusters.
- [ ] remove `do not check when the Harvester version is <v1.2` constrain on the upstream Rancher UI (starting from v2.7.2) @n313893254 
- [ ] need to update the [SUSE Harvester support matrix ](https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-1-1/)of the above changes

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester >= v1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
#### Test plan 
Ensure the Rancher Kubernetes version can support CSI & CCM maximum versions of the following scenarios: 

| Harvester version | RKE2 with old CCM design | RKE2 with new CCM design( v0.2 - https://github.com/harvester/harvester/issues/2134) |
| -- | -- | -- |
| `>= v1.2` | Supported | Supported |
| `< v1.2` | Supported | Not Supported |

#### Test Environment
Harvester: v1.2.0 and v1.1.2
Rancher: v2.7.12 and v2.6.12
RKE metadata simulation: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json

**Comment by TachunLin** [comment]
Verifing on Rancher v2.7.2  

On Harvester >=1.2 and RKE2 with new CCM design:
It suppose to support cloud provider but actually it **prevent** user to select 

| Harvester version | RKE2 with old CCM design | RKE2 with new CCM design( v0.2 - https://github.com/harvester/harvester/issues/2134) |
| -- | -- | -- |
| `>= v1.2` | (PASS) Supported | **(FAILED)** Supported |
| `< v1.2` | (PASS) Supported | (PASS) Not Supported |



* Harvester version < 1.2 (v1.1.2) with RKE2 contains old CCM design
  - Use **can select** the cloud provider as the default in RKE2 guest provisioning 
![image](https://github.com/harvester/harvester/assets/29251855/6561c1f1-a229-41da-9c61-8c6cb8e35684)

* Harvester version >= 1.2 (v1.2.0) with RKE2 contains old CCM design
  - Use **can select** the cloud provider as the default in RKE2 guest provisioning
![image](https://github.com/harvester/harvester/assets/29251855/3461e721-d23d-469c-836c-2082bf4feaad)

* Harvester version < 1.2 (v1.1.2) with RKE2 contains new CCM design (2.0)
  - Use **can't select** the cloud provider in RKE2 guest provisioning
![image](https://github.com/harvester/harvester/assets/29251855/dfe2e2b2-b847-46df-ae9d-dce67adb2ec0)

* Harvester version >= 1.2 (v1.2.0) with RKE2 contains new CCM design (2.0)
  - Use **can't select** the cloud provider in RKE2 guest provisioning
![image](https://github.com/harvester/harvester/assets/29251855/39708a78-ee71-4c3e-b78a-b20a5120189e)

**Comment by TachunLin** [comment]
* When we set the Rancher rke2-metadata setting on k8s v1.25.9 using ccm-driver version >= 2.0   
  ![image](https://github.com/harvester/harvester/assets/29251855/97a71f59-b65b-4f66-a027-5567a04f5abb)

* And modify API setting, let Harvester version = v1.2.0
  ![image](https://github.com/harvester/harvester/assets/29251855/caa5ca4a-c336-4be5-a465-8bc16033e8dc)

* We can't select the Harvester cloud provider in RKE2 guest provisioning

* Check the downstream Harvester ccm and csi-driver default version setting did not update according to version change.  
  ![image](https://github.com/harvester/harvester/assets/29251855/273acaec-6b33-4660-9d76-10c6f37f498d)

Thus move to implement to further investigation.

**Comment by n313893254** [comment]
@guangbochen Can the issue be moved to ready for testing?

**Comment by noahgildersleeve** [comment]
@n313893254 How should I test this? Can I just check the cloud provider on the RKE2 cluster dropdowns per k8s version in node driver on a master-head version of harvester and Rancher v2.7.5-rc6, or is there some other way of  checking this?

**Comment by TachunLin** [comment]
Checked with @n313893254 and come out the following test plan for reference. 

### Test Plan

#### Purpose 
Ensure when the Harvester version >=1.2.0 and the RKE2 version used in Rancher set to cloud provider >= v0.2 (contains the new CCM design). In the RKE2 provisioning page:

* Cloud provider should display on list

Ref: https://github.com/harvester/harvester/issues/3404#issuecomment-1547959940


#### Test Environment 

- Harvester: master (change version to v1.2.0) 
- Rancher: v2.7.5-rc6
- RKE2: v1.26.4+rke2r1
- metadata: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json

#### Test Steps

1. Update rke-metadata-config in Rancher global setting
2. Set the meta to https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json and refresh 
3. Enable Harvester preferences page
4. Enable the `View in API` and `Extension developer features` 
5. View `server-version` in Harvester settings
6. Change the server-version to **v1.2.0**
7. Import Harvester in Rancher and create cloud credential 
8. Create a RKE2 guest cluster 
9. Select RKE2 version to **v1.26.4+rke2r1**
10. Check the cloud provider display on list

**Comment by noahgildersleeve** [comment]
Tested with Harvester `master-d23d5c57-head` and Rancher `v2.7.5-rc6`. I validated that Harvester  cloud provider  was available in k8s `v1.26.4` and wasn't in k8s `v1.25.9`.  
> ### Test Plan
> #### Purpose
> Ensure when the Harvester version >=1.2.0 and the RKE2 version used in Rancher set to cloud provider >= v0.2 (contains the new CCM design). In the RKE2 provisioning page:
> 
> * Cloud provider should display on list
> 
> Ref: [#3404 (comment)](https://github.com/harvester/harvester/issues/3404#issuecomment-1547959940)
> 
> #### Test Environment
> * Harvester: master (change version to v1.2.0)
> * Rancher: v2.7.5-rc6
> * RKE2: v1.26.4+rke2r1
> * metadata: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json
> 
> #### Test Steps
> 1. Update rke-metadata-config in Rancher global setting
> 2. Set the meta to https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json and refresh
> 3. Enable Harvester preferences page
> 4. Enable the `View in API` and `Extension developer features`
> 5. View `server-version` in Harvester settings
> 6. Change the server-version to **v1.2.0**
> 7. Import Harvester in Rancher and create cloud credential
> 8. Create a RKE2 guest cluster
> 9. Select RKE2 version to **v1.26.4+rke2r1**
> 10. Check the cloud provider display on list

![Screenshot_20230629_103708](https://github.com/harvester/harvester/assets/83787952/c1c77cc7-91ca-4c80-afca-11bf84a2e38c)
![Screenshot_20230629_103653](https://github.com/harvester/harvester/assets/83787952/cf789298-d4cc-4438-b58d-4f2d3dc35f2d)
![Screenshot_20230629_103644](https://github.com/harvester/harvester/assets/83787952/3c30703e-8fab-4d31-baf4-accc426137ac)

**Comment by LucasSaintarbor** [comment]
Hi @guangbochen @WuJun2016, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [ ] New documentation/KB
- [ ] Updated documentation/KB
- [ ] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!
