### ISSUE TITLE
[Question] How to debug why harvester does not start after install

### ISSUE THREAD

**Issue by thooooooomas** [harvester/harvester#3408]
I booted from iso and in ttyS0 I called `start-installer.sh` (which is by default on tty1 but I am installing on a system with only serial ports).

I am able to input all the configuration and harvester starts installing and reboots.

After reboot, I don't think harvester started or installed properly. For example I am not able to call `kubectl` which I believe I am supposed to. Running `ps aux` also shows that `harvester-installer` is running on tty1. I don't think that is expected right?

Is it possible to access the harvester GUI on another tty? I would change the grub config to change the `console` parameters to start the installer on ttyS0 but I found that I cannot go through the install properly unless I call `setterm --resize` before the installer starts. The `vga=792` kernel parameter did not work in my case

Are there any error logs stored anywhere for the install so I can also debug further?

**Comment by bk201** [comment]
Hi could you provide the command results:
```
cat /proc/cmdline
journalctl -u rancherd
```

**Comment by thooooooomas** [comment]
for `cat /proc/cmdline`
```
BOOT_IMAGE=(hd0)/boot/kernel.xz cdroot root=live:CDLABEL=COS_LIVE rd.live.dir=/ rd.live.squashimg=rootfs.squashfs console=tty1 console=ttyS0 rd.cos.disable net.ifnames=1
```

for `journalctl -u rancherd`
```
-- Logs begin at Fri 2023-02-03 19:19:51 UTC, end at Fri 2023-02-03 19:20:54 UT>
-- No entries --
lines 1-2/2 (END)
```

**Comment by ibrokethecloud** [comment]
looks like you are still booting of the iso and not from the installation disk.

**Comment by thooooooomas** [comment]
> looks like you are still booting of the iso and not from the installation disk.

You're right, I'll close this as I've been able to boot from the install disk
