### ISSUE TITLE
[BUG]Unable to add new disks to host / duplicate hosts listed in add disk

### ISSUE THREAD

**Issue by prabhu-madanagopal** [harvester/harvester#3412]
**Describe the bug**
Unable to add new disks to host / duplicate hosts listed in add disk

**To Reproduce**
1. Go to Hosts
2. Click Edit Config from hot dog menu on node
3. Go to Storage
4. Click Add Disks

**Expected behavior**
See a unique list of disks as listed in lsblk command in screenshot

**Observed behavior**
Duplicate disk names and when added error as attached in screenshot

**Support bundle**

[supportbundle_06420c6b-e482-4221-9e85-3bf12340fbc4_2023-02-04T19-18-47Z.zip](https://github.com/harvester/harvester/files/10609485/supportbundle_06420c6b-e482-4221-9e85-3bf12340fbc4_2023-02-04T19-18-47Z.zip)

![Screenshot 2023-02-04 at 11 22 56 AM](https://user-images.githubusercontent.com/9297630/216786325-73200439-60f2-48bb-97ed-bba00f784166.png)
![Screenshot 2023-02-04 at 11 23 28 AM](https://user-images.githubusercontent.com/9297630/216786327-e535dc9d-27c4-44f8-8398-5e35e575b5d8.png)
![Screenshot 2023-02-04 at 11 23 54 AM](https://user-images.githubusercontent.com/9297630/216786329-4ea7c76b-93dd-449a-b856-c90b65770d94.png)
![Screenshot 2023-02-04 at 11 24 22 AM](https://user-images.githubusercontent.com/9297630/216786331-af94d155-21f4-497a-ae9e-d513a6e44742.png)

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Supermicro with Intel Xeon E5 and 8 SSD hard drives

**Additional context**
Have tried fdisk, gdisk, fsck, wipefs, mkfs.ext4 several times to add the disks somehow, without luck.
It looks like only fresh disk with Force Format with only Yes option worked for one disk the first time. When added all other disks in one save, it somehow messed up the config and I could never add them. I have also tried reinstalling the harvester cluster again.

Can you let me know how to reset the hard drives so Harvester can list them with unique entries in add disk menu and add them without errors?

Thanks

**Comment by n313893254** [comment]
Hi, @prabhu-madanagopal. About the "Unable to add new disks to host". Could you provider the `<Harvester endponit>/v1/harvester/harvesterhci.io.blockdevices` API info, I want to check how many `/dev/sdh` in the API. And alse check the console error in the broswer.

**Comment by Vicente-Cheng** [comment]
This issue is that the device UI present does not match as the Blockdevice recorded. 
That may make the backend (NDM) happened some unexpected problems.

**Comment by Vicente-Cheng** [comment]
@prabhu-madanagopal could you try to reboot your host and then try again?

**Comment by prabhu-madanagopal** [comment]
@Vicente-Cheng I have tried rebooting, reformatting and even reinstalling Harvester cluster on all my hosts. My doubt is, it detected uniquely and correctly all the disks when they were brand new. But due to what seem to be concurrent addition issue, the config is somehow messed up. 

How can I reset the disks / config? Can you suggest specific fdisk or mkfs commands? 

Simple reboot did not help. I tried fdisk->mkfs->reboot sequence too. Is that right sequence?

**Comment by prabhu-madanagopal** [comment]
Any pointers to debug this issue? How to reset so the disks can be added?

**Comment by Vicente-Cheng** [comment]
@prabhu-madanagopal, sorry for the late reply.
Could you give the command `lsblk` result on your host?

Are all your local disks the same brand?

If you confirm all disks you want to use, maybe you could provision all after the first installation w/o reboot.

**Comment by prabhu-madanagopal** [comment]
attaching lsblk output.

![Screenshot 2023-02-15 at 10 29 30 AM](https://user-images.githubusercontent.com/9297630/219120830-7ab41d02-bae3-47cb-9b7d-9dcffc7f59cc.png)


They are all same brand new SSDs. Yes I want to add all of them.
How can I provision all? Do you mean reinstalling Harvester only on this host?
I tried reinstalling Harvester cluster including this host and still was not able to add the disks, the drop down had duplicate entries as in the screenshot in first post. Should I try this again?

**Comment by Vicente-Cheng** [comment]
Hi @prabhu-madanagopal,
Did you ever try to add any disk into harvester?
Please also provide the following command result.
```
kubectl get blockdevices -A -o wide
```
It looks like some device path is conflicted, even if you try re-install. The conflicted resource still existed.
But the weird thing is why you have this conflicted resource.

**Comment by prabhu-madanagopal** [comment]
Yes, before the reinstall, I was able to add my HDDs in other hosts successfully, after I had this issue with SSD, I added them one by one (click save for each add disk), HDDs worked. This issue is only with SSDs which I tried to add all of them in one save click.

Attached output:
![Screenshot 2023-02-17 at 4 20 49 PM](https://user-images.githubusercontent.com/9297630/219820464-de79820a-4b32-405e-8e73-3cd63f9fd578.png)

**Comment by Vicente-Cheng** [comment]
hi @prabhu-madanagopal, 
looks like all your disks were ever installed with NDM (node-disk-manager) so the `blockdevices` already have some record for them. Would the disk already have data on it? (I mean did you try to create image/vol/VM on it?)

**Comment by prabhu-madanagopal** [comment]
No, not using Harvester. It could be due to mkfs and other trails using fdisk on them. 

Is there a way to remove them? I tried some fdisk commands on them without luck.

**Comment by Vicente-Cheng** [comment]
Ah, sorry. Does this situation happened on server01 instead server02?
I see those blockdevices are on server02.

**Comment by prabhu-madanagopal** [comment]
No. The issue is only on server02. kubectl could not connect to localhost port on server02 hence I ran on server01, not sure if it is expected. 

server01 has no disks.

**Comment by Vicente-Cheng** [comment]
Hi @prabhu-madanagopal, did your cluster have any data in it?
If this cluster does not have any data, I recommend you could re-create a new one.

If not, you can try to clean up the `blockdevices` resource, and you should able to add disks again.
But remember, once you remove the blockdevice from `blockdevices` resource. That means all data on this blockdevice are not able to use.

**Comment by prabhu-madanagopal** [comment]
No it is empty new cluster. I am not concerned about data loss. 
But I tried re-creating the cluster, but still had the issue, hence I opened this issue.
I will try to remove blockdevices as you suggest, how do I do it?

**Comment by Vicente-Cheng** [comment]
> No it is empty new cluster. I am not concerned about data loss. But I tried re-creating the cluster, but still had the issue, hence I opened this issue. I will try to remove blockdevices as you suggest, how do I do it?

Hmm, do you mean the reinstall the node or reinstall whole nodes?

You could use the kubectl command to delete 
for example
```
// list blockdevices
# kubectl get blockdevices -A
NAMESPACE         NAME                               TYPE   DEVPATH    MOUNTPOINT   NODENAME           STATUS   AGE
longhorn-system   3d0cf8c2677e213aecdca43acd415092   disk   /dev/sda                harvester-node-0   Active   4d9h

// delete what you want
# kubectl delete blockdevices 3d0cf8c2677e213aecdca43acd415092 -n longhorn-system
blockdevice.harvesterhci.io "3d0cf8c2677e213aecdca43acd415092" deleted
```
Then the node-disk-manager should re-add this resource back. The `devPath` should consist of `Spec`/`Status`.

If the problems still occur, please try to do this operation again and generate the support-bundle for it.
I would like to recheck it. Thanks!

**Comment by prabhu-madanagopal** [comment]
I meant I have reinstall whole/all nodes in cluster already.
delete blockdevices seem to have same problem. Attaching some screenshot, see how the added disks are shown as 0GB or 5GB while they have 1TB capacity. The same happened even after reinstall of cluster, so I am not sure if it is going to be different this time. Attaching support bundle after delete and add.

Let me know if you still suggest reinstall and generate bundle to resolve this issue.

![Screenshot 2023-02-21 at 7 54 10 PM](https://user-images.githubusercontent.com/9297630/220519298-119edc02-bc44-4742-803f-98ff98399e00.png)
![Screenshot 2023-02-21 at 7 57 23 PM](https://user-images.githubusercontent.com/9297630/220519331-9d9493f7-46e9-436c-8f5f-e8a03cee0352.png)
![Screenshot 2023-02-21 at 7 59 53 PM](https://user-images.githubusercontent.com/9297630/220519335-fab998b8-6dc5-4799-b317-2f8533caba3f.png)
![Screenshot 2023-02-21 at 8 01 11 PM](https://user-images.githubusercontent.com/9297630/220519337-597f427b-5df6-4eb6-b97c-9c03c92ed1d6.png)
[supportbundle_06420c6b-e482-4221-9e85-3bf12340fbc4_2023-02-22T04-02-58Z.zip](https://github.com/harvester/harvester/files/10799933/supportbundle_06420c6b-e482-4221-9e85-3bf12340fbc4_2023-02-22T04-02-58Z.zip)

**Comment by prabhu-madanagopal** [comment]
I suspect it has to do with the state of disks, somehow they appear partitioned or having data, Harvester expects them to be clean state. How do I reset the disks so I can add them back. Is there any documentation on how to reset/format disks before adding?

**Comment by flapili** [comment]
exactly same issue, I tried a lot of thing without luck :/

**Comment by Vicente-Cheng** [comment]
> exactly same issue, I tried a lot of thing without luck :/

Hi @flapili, could you provide your SB and the detail about what disks have the above problems

**Comment by flapili** [comment]
[supportbundle_492528d7-1a40-4102-a8b8-3c8cc43a31a9_2023-06-12T10-25-29Z.zip](https://github.com/harvester/harvester/files/11721297/supportbundle_492528d7-1a40-4102-a8b8-3c8cc43a31a9_2023-06-12T10-25-29Z.zip)

**Comment by Vicente-Cheng** [comment]
Hi @flapili, I checked with your SB. Did not see a similar error on the NDM logs. Could you describe it in more detail?

**Comment by flapili** [comment]
Hi,
I recently bought 3 fujitsu primergy rx300 s7 + 3 LCI 9207 flashed for HBA + 12x pny cs9000 1To for lab (yes it does some noise 😅 )

The issue is I see duplicate path from the ui, as example only 2 /dev/sda when I should see 3 distinct paths (one is already used as default disk), also I don't know why but when I plug a usb key the usb key showed up correctly but paths of disks changed (2 /dev/sda to 2 /dev/sdc as example)

I checked/did (only focused on the first node)
- that disk UUID are constant even after a reboot
- disk test (copying 500Gb zip + compare hash) on every disk
- used the SAS directly from the motherboard instead of the 9207 card
- format in EXT4 myself
- dd first 16mo of /dev/zero
- reformat
- checked disk health from windows
- use a SAS 8087 => 4x SATA adaptater

**Comment by irishgordo** [comment]
**Validation Failure**

@Vicente-Cheng  - I'm seeing an issue of:
```go
time="2023-07-03T17:33:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:33:34Z" level=info msg="Add new block device 83eba81957165fbd40e3f94c9295dfed with device: /dev/sda"
time="2023-07-03T17:34:58Z" level=info msg="Prepare to force format device 83eba81957165fbd40e3f94c9295dfed"
time="2023-07-03T17:34:58Z" level=error msg="failed to force format device 83eba81957165fbd40e3f94c9295dfed: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1"
time="2023-07-03T17:34:58Z" level=info msg="Prepare to force format device 83eba81957165fbd40e3f94c9295dfed"
time="2023-07-03T17:34:58Z" level=error msg="failed to force format device 83eba81957165fbd40e3f94c9295dfed: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:59Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:34:59Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:35:01Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:35:03Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
time="2023-07-03T17:35:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:35:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:36:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:36:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:37:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:37:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:38:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:38:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:39:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:39:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:40:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:40:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:41:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:41:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:42:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:42:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
time="2023-07-03T17:43:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
```

On Harvester Version: master-b0555ae9-head.

With the SATA based 20G disk failing to add successfully.
It does show in the UI after:
```yaml
rancher@harvester-node-0:~> sudo fdisk /dev/sda

Welcome to fdisk (util-linux 2.37.2).
Changes will remain in memory only, until you decide to write them.
Be careful before using the write command.

Device does not contain a recognized partition table.
Created a new DOS disklabel with disk identifier 0xd7f5474d.

Command (m for help): w
The partition table has been altered.
Calling ioctl() to re-read partition table.
Syncing disks.

rancher@harvester-node-0:~> exit
logout

```
And can then be added w/ force-format - but the issue is the `node-disk-manager` can't parse the UUID of the disk:
```go
time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1, requeuing"
```

So it never shows up in `kubectl get blockdevices -A`.

![Screenshot from 2023-07-03 10-46-17](https://github.com/harvester/harvester/assets/5370752/92106a1a-dd24-4440-ba7b-06b2601207a3)
![Screenshot from 2023-07-03 10-46-03](https://github.com/harvester/harvester/assets/5370752/a6143deb-15d4-42a9-b5e9-f77d86e306c4)

[supportbundle_8a8ce6dc-3cd1-4b2c-be0d-247bd90a103a_2023-07-03T17-49-49Z.zip](https://github.com/harvester/harvester/files/11939919/supportbundle_8a8ce6dc-3cd1-4b2c-be0d-247bd90a103a_2023-07-03T17-49-49Z.zip)

**Comment by Vicente-Cheng** [comment]
> **Validation Failure**
> 
> @Vicente-Cheng - I'm seeing an issue of:
> 
> ```go
> time="2023-07-03T17:33:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:33:34Z" level=info msg="Add new block device 83eba81957165fbd40e3f94c9295dfed with device: /dev/sda"
> time="2023-07-03T17:34:58Z" level=info msg="Prepare to force format device 83eba81957165fbd40e3f94c9295dfed"
> time="2023-07-03T17:34:58Z" level=error msg="failed to force format device 83eba81957165fbd40e3f94c9295dfed: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1"
> time="2023-07-03T17:34:58Z" level=info msg="Prepare to force format device 83eba81957165fbd40e3f94c9295dfed"
> time="2023-07-03T17:34:58Z" level=error msg="failed to force format device 83eba81957165fbd40e3f94c9295dfed: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:59Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:34:59Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:35:01Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:35:03Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: lstat /dev/disk/by-uuid/d7f5474d: no such file or directory, requeuing"
> time="2023-07-03T17:35:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:35:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:36:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:36:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:37:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:37:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:38:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:38:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:39:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:39:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:40:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:40:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:41:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:41:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:42:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:42:34Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> time="2023-07-03T17:43:04Z" level=info msg="Skip adding non-identifiable block device /dev/sda"
> ```
> 
> On Harvester Version: master-b0555ae9-head.
> 
> With the SATA based 20G disk failing to add successfully. It does show in the UI after:
> 
> ```yaml
> rancher@harvester-node-0:~> sudo fdisk /dev/sda
> 
> Welcome to fdisk (util-linux 2.37.2).
> Changes will remain in memory only, until you decide to write them.
> Be careful before using the write command.
> 
> Device does not contain a recognized partition table.
> Created a new DOS disklabel with disk identifier 0xd7f5474d.
> 
> Command (m for help): w
> The partition table has been altered.
> Calling ioctl() to re-read partition table.
> Syncing disks.
> 
> rancher@harvester-node-0:~> exit
> logout
> ```
> 
> And can then be added w/ force-format - but the issue is the `node-disk-manager` can't parse the UUID of the disk:
> 
> ```go
> time="2023-07-03T17:34:58Z" level=error msg="error syncing 'longhorn-system/83eba81957165fbd40e3f94c9295dfed': handler harvester-block-device-handler: stderr: mke2fs 1.46.4 (18-Aug-2021)\n/dev/sda: could not parse UUID: d7f5474d\n\n, err: exit status 1, requeuing"
> ```
> 
> So it never shows up in `kubectl get blockdevices -A`.
> 
> ![Screenshot from 2023-07-03 10-46-17](https://user-images.githubusercontent.com/5370752/250631978-92106a1a-dd24-4440-ba7b-06b2601207a3.png) ![Screenshot from 2023-07-03 10-46-03](https://user-images.githubusercontent.com/5370752/250631979-a6143deb-15d4-42a9-b5e9-f77d86e306c4.png)
> 
> [supportbundle_8a8ce6dc-3cd1-4b2c-be0d-247bd90a103a_2023-07-03T17-49-49Z.zip](https://github.com/harvester/harvester/files/11939919/supportbundle_8a8ce6dc-3cd1-4b2c-be0d-247bd90a103a_2023-07-03T17-49-49Z.zip)

Hi @irishgordo, did you use the physical disk for testing?
If not, we may need to add the wwn for testing.

You can refer to https://github.com/harvester/node-disk-manager#appendix

**Comment by irishgordo** [comment]
@Vicente-Cheng  thanks for that info :smile: :+1: - after attaching a `wwn` within the xml I was not encountering the same issue.

**validation question:**
While validating on Harvester Version: v1.2-7a8ac2c2-head - I did want to ask, on the `blockdevice` - will the `Status.State` always show as "Active"?
I do note that the `Status.ProvisionPhase` does change between Provisioned & Unprovisioned - but the `State` does not change from Active -> InActive.

Aside from that, all other validations do look good :smile: 

Validation Artifacts:
![Screenshot from 2023-07-05 15-14-27](https://github.com/harvester/harvester/assets/5370752/eed348b3-9c30-4412-bc68-3e44362c4b24)
![Screenshot from 2023-07-05 14-54-03](https://github.com/harvester/harvester/assets/5370752/a423935b-3548-44a9-9df9-f395ba825c55)
![Screenshot from 2023-07-05 14-53-42](https://github.com/harvester/harvester/assets/5370752/86d74109-f03e-432d-99ce-97d45692342e)
![Screenshot from 2023-07-05 14-53-25](https://github.com/harvester/harvester/assets/5370752/9c1e63bd-b81b-42ef-aa1e-d76928a35f5f)
![Screenshot from 2023-07-05 14-49-54](https://github.com/harvester/harvester/assets/5370752/b779bf15-5c93-45a4-b57f-7b712d294e29)
![Screenshot from 2023-07-05 14-47-12](https://github.com/harvester/harvester/assets/5370752/b79179b8-7b3f-4a12-b778-5020ebb516ba)
![Screenshot from 2023-07-05 14-14-03](https://github.com/harvester/harvester/assets/5370752/b6d0d1b9-c7a0-483d-903e-c53b01a7347b)
![Screenshot from 2023-07-05 14-11-38](https://github.com/harvester/harvester/assets/5370752/9545eaf0-466c-4009-b4db-0b526ff4bf51)
![Screenshot from 2023-07-05 14-09-49](https://github.com/harvester/harvester/assets/5370752/ef930758-7429-457c-9ea0-57357382ebb0)
![Screenshot from 2023-07-05 14-08-49](https://github.com/harvester/harvester/assets/5370752/58ad9c94-3adf-451f-bed5-e2c163d66c19)

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng thanks for that info 😄 👍 - after attaching a `wwn` within the xml I was not encountering the same issue.
> 
> **validation question:** While validating on Harvester Version: v1.2-7a8ac2c2-head - I did want to ask, on the `blockdevice` - will the `Status.State` always show as "Active"? I do note that the `Status.ProvisionPhase` does change between Provisioned & Unprovisioned - but the `State` does not change from Active -> InActive.
> 
> Aside from that, all other validations do look good 😄
> 

Hi @irishgordo, thanks for the validation!

The `Inactive` state is for the disk hot plug.
This test plan on this issue would be more like a filesystem corrupted.

You could also refer to the whole test plan on the original PR. (https://github.com/harvester/node-disk-manager/pull/55)
Thanks!

**Comment by irishgordo** [comment]
Ahhh thank you for the additional info surrounding hot-plug @Vicente-Cheng  - I tested this on bare metal Dell PowerEdge R720 - leveraging USB and I was able to get it all working correctly with the State shifting from "Active" -> "Inactive" :smile: 

![Screenshot from 2023-07-06 12-07-53](https://github.com/harvester/harvester/assets/5370752/da085186-9aa3-4f1e-b673-6ee6be47a04c)
![Screenshot from 2023-07-06 12-06-50](https://github.com/harvester/harvester/assets/5370752/6a7d707d-999d-4690-b4ea-bdb87c872884)
![Screenshot from 2023-07-06 12-06-14](https://github.com/harvester/harvester/assets/5370752/c05d9126-3e99-472d-8395-a69fdf6df721)

This was on Harvester Version: v1.2-56e9844d-head :+1: 

I will go ahead and close this out as this looks good to me :smile: :+1: 

I did open up a small UI issue I saw at:
https://github.com/harvester/harvester/issues/4198

**Comment by irishgordo** [comment]
@Vicente-Cheng pending:
https://github.com/harvester/harvester/issues/3218

With what was discovered by @albinsun  - I'll be reopening this.
https://github.com/harvester/harvester/issues/3218#issuecomment-1624628144

With hot-plug I had only focused the testing on the bare-metal with an external USB based disk to get the "Active" -> "Inactive" status changing on the blockdevices

**Comment by irishgordo** [comment]
> > @Vicente-Cheng thanks for that info smile +1 - after attaching a `wwn` within the xml I was not encountering the same issue.
> > **validation question:** While validating on Harvester Version: v1.2-7a8ac2c2-head - I did want to ask, on the `blockdevice` - will the `Status.State` always show as "Active"? I do note that the `Status.ProvisionPhase` does change between Provisioned & Unprovisioned - but the `State` does not change from Active -> InActive.
> > Aside from that, all other validations do look good smile
> 
> Hi @irishgordo, thanks for the validation!
> 
> The `Inactive` state is for the disk hot plug. This test plan on this issue would be more like a filesystem corrupted.
> 
> You could also refer to the whole test plan on the original PR. ([harvester/node-disk-manager#55](https://github.com/harvester/node-disk-manager/pull/55)) Thanks!

Oh, pending that #3218 - will just be handling the hot-plug validation more in depth and this had preformed that validation w/ external usb on physical device as well as the validation of the corrupted file system check - I will close this out again as 3218 can just be left open to track more the hot-plug validation :smile:

**Comment by albinsun** [comment]
FYI, just verified SCSI hot-plug in [harvester#3218](https://github.com/harvester/harvester/issues/3218).
