### ISSUE TITLE
[BUG] vm volumes claimName is null, cause to the vm can not be edited

### ISSUE THREAD

**Issue by fangfenghuang** [harvester/harvester#3413]
**Describe the bug**

**To Reproduce**
1. create vm by iso image, install operating system, eject cdrom
1. backup vm 
2. restore new vm
3. Virtual Machines > Edit Config > volumes (Edit as Yaml)

**Expected behavior**

vm volumes claimName is null, cause to the vm can not be edited

but, if edit yaml as :Virtual Machines > Edit YAML, the config is correct 

**Support bundle**

 Edit Config:
![image](https://user-images.githubusercontent.com/49675127/216879064-9f49002c-2684-41b4-ac54-4d190887ae87.png)
 Edit YAML：
![image](https://user-images.githubusercontent.com/49675127/216879139-eb239e9b-27c5-40d7-a6eb-568ceda9a593.png)

**Environment**
 - Harvester ISO version:  v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
Hi @fangfenghuang   I haven't been able to reproduce the problem. Is it stable to reproduce ?    If it's convenient, you can record a short video, thank you

**Comment by fangfenghuang** [comment]
> Hi @fangfenghuang I haven't been able to reproduce the problem. Is it stable to reproduce ? If it's convenient, you can record a short video, thank you

I update the reproducing step, can you create vm by iso image?  and eject cdrom after install operating system, it can't be reproduced by qcow2 images.  if you can't reproduce it, i will check it by myself.

**Comment by ibrokethecloud** [comment]
similar to: https://github.com/harvester/harvester/issues/3362

**Comment by n313893254** [comment]
Close in favor of same as https://github.com/harvester/harvester/issues/3362
