### ISSUE TITLE
[BUG]when the vm vlan network segment is the same as the host, host can not connection to vm

### ISSUE THREAD

**Issue by fangfenghuang** [harvester/harvester#3414]
**Describe the bug**

**To Reproduce**
1. create vm network(L2VlanNetwork): network segment is the same as the host
2. create vm with vlan network
3. config vlan ip
4. ping/ssh vlan ip from host or ping/ssh host ip from vm, ping/ssh connection failed

**Expected behavior**

host can connect to vm always

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
when vm vlan network segment is not the same as the host, it behaves normal

**Comment by RegisWeduLabs** [comment]
I have a similar issue - I cannot access the IP of the host that the vm is on, nor can I get access to VIP address...  I need to go trough the IP of one of the other host in order to manage the cluster.  Load Balancers aren't working either from the vm.

**Comment by w13915984028** [comment]
**We need to write this into Harvester DOC trouble-shooting, it is not a BUG. Users want VLAN isolation, but forget to separate the network segment and related routing.**

As a general rule, each VLAN (strictly speacking exept VLAN 1) network should have a separate IP segment. 

When management and VM network are in same IP segment, their communication will have following issue: 

Simply speaking, as IPs are in same segment, L3 routing will not be invoked, only L2 switching is required. (e.g. VM vlan ID is 100, management VLAN ID is default or other value.) Then the MAC learning/ARP will have issue. VLAN limits the range of MAC/any broadcast.

**Comment by fangfenghuang** [comment]
> **We need to write this into Harvester DOC trouble-shooting, it is not a BUG. Users want VLAN isolation, but forget to separate the network segment and related routing.**
> 
> As a general rule, each VLAN (strictly speacking exept VLAN 1) network should have a separate IP segment.
> 
> When management and VM network are in same IP segment, their communication will have following issue:
> 
> Simply speaking, as IPs are in same segment, L3 routing will not be invoked, only L2 switching is required. (e.g. VM vlan ID is 100, management VLAN ID is default or other value.) Then the MAC learning/ARP will have issue. VLAN limits the range of MAC/any boradcast.

got it, thank you for your kind and detailed reply.
