### ISSUE TITLE
[Question] VM stuck in starting, insufficient devices.kubevirt.io/kvm

### ISSUE THREAD

**Issue by thooooooomas** [harvester/harvester#3415]
I have a 1 node harvester cluster. I tried to create a new VM using openSUSE Leap 15.4 in the default namespace
When I try to start it, it becomes stuck in "Starting" state and in kubectl I see these 2 events when I describe the pod

  Warning  FailedScheduling  2m38s (x3 over 2m49s)  default-scheduler  0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  2m33s                  default-scheduler  0/1 nodes are available: 1 Insufficient devices.kubevirt.io/kvm. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod.
  
I couldn't find much info on the issues for these 2 events, could I get some help in how to fix them?

I also see two errors elsewhere in the UI
In Hosts - the disk state says "Warning" - Host has unready or unschedulable disks
and in Volumes - the VM's volume says "Not ready" - Disks are unavailable

**Comment by thooooooomas** [comment]
My system did not have nested virtualization enabled properly, once it was, this issue went away, closing

**Comment by J1a-wei** [comment]
Can you share how to enable virtual nesting?

I use pve and install two haverster node. Same issue @thooooooomas

**Comment by thooooooomas** [comment]
> Can you share how to enable virtual nesting?
> 
> I use pve and install two haverster node. Same issue @thooooooomas

this was on google cloud platform so may not apply to your case, sorry for late reply
