### ISSUE TITLE
[Doc] Update monitoring logging as addons

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3423]
**Is your doc request related to a problem? Please describe or add related issue ID.**

**Describe the solution you'd like**

Logging, monitoring will be addon in v1.2.0, and they can be enabled/disabled in Harvester configuration file, users are flexible to control them before installation.

The related harvester configuration document needs to be updated.

Update harvester-configuration to expose install.addons
Update monitoring chapter
Update logging chapter
Update addons list in v1.2.0

https://github.com/harvester/harvester/issues/3262

Epic: https://github.com/harvester/harvester/issues/3262

**Comment by guangbochen** [comment]
Close as the doc [PR](https://github.com/harvester/docs/pull/282) is merged and currently available on https://docs.harvesterhci.io/dev/install/harvester-configuration#installaddons
