### ISSUE TITLE
[BUG] Setting backup target admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting

### ISSUE THREAD

**Issue by Sepiidae** [harvester/harvester#3424]
**Describe the bug**
Even after a reboot of our cluster, we are unable to configure the backup-target and receive 

admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting

**To Reproduce**
1. Go to Settings
2. Go to backup-target
3. Configure backup target
4. Add s3 or nfs
5. enter values
6. click save

Responds with: admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting

**Expected behavior**
Updated backup settings

**Support bundle**
On the way.

**Environment**
 - Harvester ISO version: 1.1.1
 - Baremetal with PowerEdge R6525Enterprise (3) nodes

**Additional context**
None at the moment

**Comment by ibrokethecloud** [comment]
are you please able to provide a support-bundle from this cluster?

**Comment by ibrokethecloud** [comment]
similar to https://github.com/harvester/harvester/issues/3277

**Comment by Sepiidae** [comment]
I sent a support-bundle to the email address in the ticket template. 

We discovered the issue was a very stuck and upset vm that wasn't visible. Connected via kubectl, located it, and deleted the vm pod. 

Our cluster had somehow gotten into a state when a network did not exist but was referenced by the vm/pod. The UI could not resolve the issue in config or yaml mode.
