### ISSUE TITLE
[BUG] Request IP from windows DHCP server failed during installation

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3428]
**Describe the bug**

![image](https://user-images.githubusercontent.com/7421463/217470992-7687b5e7-b7ae-4171-9d11-e01dc8e3ec2d.png)

**To Reproduce**
1. Set up windows DHCP server 2016
2. Set up a new Harvester and use DHCP mode to request the IP

**Expected behavior**

Request IP from windows DHCP server successfully.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R630

**Additional context**

**Comment by bk201** [comment]
Update workaround for 1.1.2: https://github.com/bk201/harvester-installer/blob/sure-5716-2/doc/skip-code-dhcp.md

**Comment by Daxcor69** [comment]
ok, so this is still an issue for 1.20?  The work around says 1.1.2 iso.  So is the work around then install 1.1.2 install workaround, then upgrade to 1.2.0?

**Comment by w13915984028** [comment]
@Daxcor69 Have you already encountered such issue in your environment? When yes, could you confirm:

(1) Was it same to get management-IP through Windows DHCP server failed?
(2) Was >= 2 interfaces used or only 1 interface used in management network?
(3) Was VLAN ID also used?

We are looking for an reproduceable setting, if it is simple enough, with only one interface and without VLAN ID, will be helpful for trouble-shooting, thanks.

**Comment by w13915984028** [comment]
Though no windows dhcp server on hand, there are some useful information to refer:

https://learn.microsoft.com/en-us/windows-server/troubleshoot/dynamic-host-configuration-protocol-basics

This error comes from 
https://github.com/insomniacslk/dhcp/blob/ddd8a41251c972b56f2e360558a0dd156851f921/dhcpv4/nclient4/client.go#L464

the first DHCPDiscover has no response, most probably, some options are wrong/missing.

**Comment by w13915984028** [comment]
The most notable difference between Harvester installer dhcp client and a normal vm dhcp client:

it sets the `MSZ Option 57` with `1500` instead of normal value `576`

![image](https://github.com/user-attachments/assets/3427834c-bb16-4f96-b305-43492fab9cd6)

https://github.com/insomniacslk/dhcp/blob/ddd8a41251c972b56f2e360558a0dd156851f921/dhcpv4/nclient4/client.go#L38
```
	// MaxMessageSize is the value to be used for DHCP option "MaxMessageSize".
	MaxMessageSize = 1500
```

And it forcely set this option on client side

```
// DiscoverOffer sends a DHCPDiscover message and returns the first valid offer
// received.
func (c *Client) DiscoverOffer(ctx context.Context, modifiers ...dhcpv4.Modifier) (offer *dhcpv4.DHCPv4, err error) {
	// RFC 2131, Section 4.4.1, Table 5 details what a DISCOVER packet should
	// contain.
	discover, err := dhcpv4.NewDiscovery(c.ifaceHWAddr, dhcpv4.PrependModifiers(modifiers,
		dhcpv4.WithOption(dhcpv4.OptMaxMessageSize(MaxMessageSize)))...)
	if err != nil {
		return nil, fmt.Errorf("unable to create a discovery request: %w", err)
	}
```

Given the fact that the MTU is 1500 and L2 head with VLAN ID, the DHCPDiscover message itself to be max 1500 is making no sense.

Maybe due to this, it caused the `DHCPDiscover` was dropped by windows server.

**Comment by bk201** [comment]
@w13915984028 Does https://github.com/harvester/harvester-installer/pull/779 fix the issue? I'm planning 1.3.2 and want to see if we should include https://github.com/harvester/harvester/issues/6259

**Comment by w13915984028** [comment]
@bk201 [PR 779](https://github.com/harvester/harvester-installer/pull/779) seems not the direct cause, but bump package won't hurt.  
[PR 767](https://github.com/harvester/harvester-installer/pull/767) has chance to fix this issue..

**Comment by w13915984028** [comment]
Unfortunately, this bug is caused by a code bug, the VLAN based DHCP does not use the VLAN interface.

A fix https://github.com/harvester/harvester-installer/pull/879 is in review now.

**Comment by w13915984028** [comment]
The root cause of this issue is same as https://github.com/harvester/harvester/issues/6959, and https://github.com/harvester/harvester/issues/6959 has been verified on Harvester v1.4.0, refer the validation test: https://github.com/harvester/harvester/issues/6959#issuecomment-2469553979
