### ISSUE TITLE
[BUG] Cannot Migrate a VM from one Host to another (3 host-cluster)

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#3429]
**Describe the bug**
under "Events" I only see this:
```
SuccessfulUpdate | VirtualMachineInstance testw11Expanded PodDisruptionBudget kubevirt-disruption-budget-8p2dk
```
around 15 minutes later it will tell me this:
```
SuccessfulUpdate | VirtualMachineInstance testw11Shrank PodDisruptionBudget kubevirt-disruption-budget-8p2dk
```

it will stay there forever.
Under "Migration" it just says nothing.

In the overview it has the red trianlge telling me the last migration failed. I dont see why anywhere.

**To Reproduce**
I select "migrate" on a VM and select the target host.

**Expected behavior**
The VM gets migrated.

**Support bundle**
[supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-02-08T10-59-36Z.zip](https://github.com/harvester/harvester/files/10684872/supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-02-08T10-59-36Z.zip)

**Environment**
 - Harvester ISO version: Harvester v1.1.1 fresh install.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by ne0YT** [comment]
just as an additional related question. But it's already satified if needed..
Do I need a manamgement-network (type is masquerade) on my vms if I want to migrate them?
I currently do have this, but would remove it if it's not really needed.

**Comment by ne0YT** [comment]
I now also created two vms for testing which only have the masquarade - mgmt network, they have this output in "Events":
```
SuccessfulUpdate	
VirtualMachineInstance windows.server.2022-01
Shrank PodDisruptionBudget kubevirt-disruption-budget-g2sg7
1.8 mins ago
SuccessfulUpdate	
VirtualMachineInstance windows.server.2022-01
Expanded PodDisruptionBudget kubevirt-disruption-budget-g2sg7
16 mins ago
Created	
VirtualMachineInstance windows.server.2022-01
VirtualMachineInstance defined.
17 mins ago
Started	
VirtualMachineInstance windows.server.2022-01
VirtualMachineInstance started.
17 mins ago
Started	
Pod virt-launcher-windows.server.2022-01-k4rt9
Started container volumevirtio-container-disk
17 mins ago
Created	
Pod virt-launcher-windows.server.2022-01-k4rt9
Created container volumevirtio-container-disk
17 mins ago
Created	
Pod virt-launcher-windows.server.2022-01-k4rt9
Created container compute
17 mins ago
Started	
Pod virt-launcher-windows.server.2022-01-k4rt9
Started container compute
17 mins ago
Pulled	
Pod virt-launcher-windows.server.2022-01-k4rt9
Container image "registry.suse.com/suse/sles/15.4/virt-launcher:0.54.0-150400.3.7.1" already present on machine
17 mins ago
Pulled	
Pod virt-launcher-windows.server.2022-01-k4rt9
Container image "registry.suse.com/suse/vmdp/vmdp:2.5.3" already present on machine
17 mins ago

Created	
Pod virt-launcher-windows.server.2022-01-k4rt9
Created container container-disk-binary
17 mins ago
Pulled	
Pod virt-launcher-windows.server.2022-01-k4rt9
Container image "registry.suse.com/suse/sles/15.4/virt-launcher:0.54.0-150400.3.7.1" already present on machine
17 mins ago
Started	
Pod virt-launcher-windows.server.2022-01-k4rt9
Started container container-disk-binary
17 mins ago
Pulled	
Pod virt-launcher-windows.server.2022-01-k4rt9
Container image "registry.suse.com/suse/vmdp/vmdp:2.5.3" already present on machine
17 mins ago
Created	
Pod virt-launcher-windows.server.2022-01-k4rt9
Created container volumevirtio-container-disk-init
17 mins ago
Started	
Pod virt-launcher-windows.server.2022-01-k4rt9
Started container volumevirtio-container-disk-init
17 mins ago
AddedInterface	
Pod virt-launcher-windows.server.2022-01-k4rt9
Add eth0 [10.52.1.182/32] from k8s-pod-network
17 mins ago
SuccessfulMountVolume	
Pod virt-launcher-windows.server.2022-01-k4rt9
MapVolume.MapPodDevice succeeded for volume "pvc-77a9060d-43e2-4033-83bd-c316eae5438f" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-77a9060d-43e2-4033-83bd-c316eae5438f/dev"
17 mins ago
SuccessfulMountVolume	
Pod virt-launcher-windows.server.2022-01-k4rt9
MapVolume.MapPodDevice succeeded for volume "pvc-77a9060d-43e2-4033-83bd-c316eae5438f" volumeMapPath "/var/lib/kubelet/pods/25965bc2-ea01-4893-b989-ab82354dcc6c/volumeDevices/kubernetes.io~csi"
17 mins ago
SuccessfulCreate	
VirtualMachineInstance windows.server.2022-01
Created virtual machine pod virt-launcher-windows.server.2022-01-k4rt9
17 mins ago
SuccessfulCreate	
VirtualMachineInstance windows.server.2022-01
Created PodDisruptionBudget kubevirt-disruption-budget-g2sg7
17 mins ago
SuccessfulCreate	
VirtualMachine windows.server.2022-01
Started the virtual machine by creating the new virtual machine instance windows.server.2022-01
17 mins ago
Deleted	
VirtualMachineInstance windows.server.2022-01
Signaled Deletion
18 mins ago
Stopped	
VirtualMachineInstance windows.server.2022-01
The VirtualMachineInstance was shut down.
18 mins ago
ShuttingDown	
VirtualMachineInstance windows.server.2022-01
Signaled Graceful Shutdown
18 mins ago
SuccessfulDelete	
VirtualMachine windows.server.2022-01
Stopped the virtual machine by deleting the virtual machine instance 8d7325f2-9f6d-48ea-b6a7-27669775c6df
18 mins ago
SuccessfulDelete	
VirtualMachineInstance windows.server.2022-01
Deleted virtual machine pod virt-launcher-windows.server.2022-01-vbvp5
18 mins ago
SuccessfulDelete	
VirtualMachineInstance windows.server.2022-01
Deleted PodDisruptionBudget kubevirt-disruption-budget-8g6x2
18 mins ago
SuccessfulUpdate	
VirtualMachineInstance windows.server.2022-01
Shrank PodDisruptionBudget kubevirt-disruption-budget-8g6x2
25 mins ago
SuccessfulUpdate	
VirtualMachineInstance windows.server.2022-01
Expanded PodDisruptionBudget kubevirt-disruption-budget-8g6x2
40 mins ago
Created	
VirtualMachineInstance windows.server.2022-01
VirtualMachineInstance defined.
49 mins ago
Started	
VirtualMachineInstance windows.server.2022-01
VirtualMachineInstance started.
49 mins ago
ProvisioningSucceeded	
PersistentVolumeClaim windows.server.2022-01-rootdisk-hfr4j
Successfully provisioned volume pvc-77a9060d-43e2-4033-83bd-c316eae5438f
50 mins ago
ExternalProvisioning	
PersistentVolumeClaim windows.server.2022-01-rootdisk-hfr4j
Waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
50 mins ago
Provisioning	
PersistentVolumeClaim windows.server.2022-01-rootdisk-hfr4j
External provisioner is provisioning volume for claim "default/windows.server.2022-01-rootdisk-hfr4j"
50 mins ago
SuccessfulCreate	
VirtualMachineInstance windows.server.2022-01
Created PodDisruptionBudget kubevirt-disruption-budget-8g6x2
50 mins ago
SuccessfulCreate	
VirtualMachineInstance windows.server.2022-01
Created virtual machine pod virt-launcher-windows.server.2022-01-vbvp5
50 mins ago
```

**Comment by ibrokethecloud** [comment]
are you please able to start the migration again?

kubevirt should be creating a new virt-launcher pod in the default ns, which seems to be shutdown.

unfortunately support bundle has no logs of this pod, only references in the controller logs.

```
virt-controller-6f649f4578-49rr5 virt-controller 2023-02-08T10:51:23.005591521Z {"component":"virt-controller","level":"info","msg":"TSC Freqency node update status: 0 updated, 3 skipped, 0 errors","pos":"nodetopologyupdater.go:44","timestamp":"2023-02-08T10:51:23.005437Z"}
virt-controller-6f649f4578-49rr5 virt-controller 2023-02-08T10:51:56.550724274Z {"component":"virt-controller","kind":"","level":"info","msg":"expanding pdb for VMI default/testw11 to protect migration testw11-znkkt","name":"testw11","namespace":"default","pos":"migration.go:647","timestamp":"2023-02-08T10:51:56.550598Z","uid":"ab59e872-cfdd-4567-ac95-6c71abc3ff4c"}
virt-controller-6f649f4578-49rr5 virt-controller 2023-02-08T10:51:56.558841845Z {"component":"virt-controller","kind":"","level":"info","msg":"arguments for container-disk \"volumevirtio-container-disk\": --copy-path /var/run/kubevirt-ephemeral-disks/container-disk-data/ab59e872-cfdd-4567-ac95-6c71abc3ff4c/disk_1","name":"testw11","namespace":"default","pos":"container-disk.go:315","timestamp":"2023-02-08T10:51:56.558716Z","uid":"ab59e872-cfdd-4567-ac95-6c71abc3ff4c"}
virt-controller-6f649f4578-49rr5 virt-controller 2023-02-08T10:51:56.558919154Z {"component":"virt-controller","kind":"","level":"info","msg":"cpu model label selector (\"cpu-model-migration.node.kubevirt.io/Haswell-noTSX-IBRS\") defined for migration target pod","name":"","pos":"migration.go:1615","timestamp":"2023-02-08T10:51:56.558873Z","uid":""}
virt-controller-6f649f4578-49rr5 virt-controller 2023-02-08T10:51:56.574965304Z {"component":"virt-controller","kind":"","level":"info","msg":"Created migration target pod default/virt-launcher-testw11-2hd72 with uuid f2ed5267-74b0-466d-84bf-887138e4fe13 for migration testw11-znkkt with uuid 90625894-7126-4d42-8e14-4ba1ed0639bb","name":"testw11","namespace":"default","pos":"migration.go:627","timestamp":"2023-02-08T10:51:56.574863Z","uid":"ab59e872-cfdd-4567-ac95-6c71abc3ff4c"}
```

are you please able to generate a support bundle when this new launcher pod is running.

Or collect logs from the new launcher pod?

**Comment by ibrokethecloud** [comment]
I also noticed your cluster has only 1 windows VM.

Any chance you are able to also create a linux VM' and try migrating the same?

**Comment by ne0YT** [comment]
with a linux vm it works.

**Comment by ne0YT** [comment]
so weird.. I tried with 4 windows vms now.. and they all just dont work. for a linux vm it just works..

**Comment by ne0YT** [comment]
new support-bundle:
[supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-02-10T13-15-07Z.zip](https://github.com/harvester/harvester/files/10707700/supportbundle_1ff7ac40-4dd0-4c22-be92-f57e89363d99_2023-02-10T13-15-07Z.zip)

**Comment by bk201** [comment]
The windows VM contains a container disk with the image `registry.suse.com/suse/vmdp/vmdp:2.5.3`, could you try removing it from the VM and migrating again? (VM will need to be stopped first)

**Comment by ne0YT** [comment]
> The windows VM contains a container disk with the image `registry.suse.com/suse/vmdp/vmdp:2.5.3`, could you try removing it from the VM and migrating again? (VM will need to be stopped first)

hey there

yes this works absolutely perfect !
maybe you can answer me why the agent is not showing up when installing the drivers & guest agent using the setup?

**Comment by bk201** [comment]
Reopen to mention the limitation in the doc.

**Comment by w13915984028** [comment]
will add check of container disk before migration in PR https://github.com/harvester/harvester/pull/3463

**Comment by irishgordo** [comment]
This looks good @w13915984028  - thanks for the fix :smile: , I'll go ahead and close this out
Tested on Harvester Version: v1.1-a72900af-head (03/01/23, v1.1-head)
Bare metal, 3-node cluster (NVMe drives on each).
Tested with the permutations of:
- attempt migrate with 1 container disk & 1 container cd rom
- attempt migrate with 1 container cd rom
- attempt migrate with 1 container disk

Leveraging, `kubevirt/cirros-registry-disk-demo`

some screenshots:
![Screenshot from 2023-03-02 10-53-04](https://user-images.githubusercontent.com/5370752/222525343-060dde12-ae2f-4c06-8cd0-88e86cefd6c2.png)
![Screenshot from 2023-03-02 10-49-23](https://user-images.githubusercontent.com/5370752/222525344-537c04ff-2ee9-4d80-a040-8bbe7036e596.png)
![Screenshot from 2023-03-02 10-48-48](https://user-images.githubusercontent.com/5370752/222525345-c547aa13-35c0-4be5-b3fb-415fe6fd9266.png)
![Screenshot from 2023-03-02 10-48-17](https://user-images.githubusercontent.com/5370752/222525347-4b9e9924-c227-4b24-8f7e-d45897bc1618.png)

**Comment by irishgordo** [comment]
@w13915984028  - Re-opening -for a validation question:

> Is it allowed for VMs running on a Node that has both a CD-ROM Container & Disk Container to be live-migrated when that Node gets put into maintenece mode?  I noticed that the VM migrated, though it had both a CD ROM Container & Disk Container, when I put the Node into Maintenence Mode.

![Screenshot from 2023-03-02 14-52-08](https://user-images.githubusercontent.com/5370752/222578523-60a9e410-5535-4c10-88d8-4f2ee1ff0b59.png)
![Screenshot from 2023-03-02 14-50-47](https://user-images.githubusercontent.com/5370752/222578526-fbf7bd16-b50d-41a0-a354-75f11882f01a.png)
![Screenshot from 2023-03-02 14-49-48](https://user-images.githubusercontent.com/5370752/222578527-9b5ab069-0cc2-4b17-ae72-77b35aa943b2.png)

**Comment by bk201** [comment]
>> I noticed that the VM migrated, though it had both a CD ROM Container & Disk Container, when I put the Node into Maintenence Mode.

@irishgordo I think this is in a different path, @ibrokethecloud looks like we need to check this in the maintenance mode.

**Comment by irishgordo** [comment]
@bk201 thanks for looking into that! 😃

Should I open up a separate issue for that case?

**Comment by irishgordo** [comment]
I'll close this and open up a separate issue for that :smile: :
https://github.com/harvester/harvester/issues/3600
