### ISSUE TITLE
[BUG] Cannot edit namespace on single cluster

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3435]
**Describe the bug**

**To Reproduce**
1. Go to Namespace List
2. Click `Edit Config`
3. Chrome console will throw errors
4. Errors only occured on single cluster
![image (11).png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/7f14db1b-b703-4a11-b057-76792ca0cf8f)
**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/219313272-343c0e95-5da2-485c-96be-d5d7155b33f9.png)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1-d18bb5e8-head**
* **ui-source** Option: **Auto**
* **ui-index**: `https://releases.rancher.com/harvester-ui/dashboard/latest/index.html`
* **ui-plugin-index**: `https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js`

### Verify Steps:
1. Install Harvester with 1 node
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/3435#issue-1577467205
