### ISSUE TITLE
[ENHANCEMENT]users can set Banners and Branding in Harvester UI 

### ISSUE THREAD

**Issue by 290760647** [harvester/harvester#3442]
Like Rancher , We should allow users can setting Banners and Branding in Harvester UI .
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/42170674/218046438-bea89880-4815-44ec-a1b3-2ab54fb593bc.png">

**Comment by Martin-Weiss** [comment]
Maybe a duplicate of https://github.com/harvester/harvester/issues/3396 ?

**Comment by guangbochen** [comment]
close as duplicate with https://github.com/harvester/harvester/issues/3396
