### ISSUE TITLE
Follow IOMMU rules

### ISSUE THREAD

**Issue by tlehman** [harvester/harvester#3451]
Created this here to track https://github.com/harvester/pcidevices/issues/29

**Comment by bk201** [comment]
@tlehman You can use the transfer feature to transfer the issue to the harvester repo to keep all descriptions.

**Comment by tlehman** [comment]
I am about to push a new branch for this, it handles the iommu siblings in the PCIDeviceClaims controller. The UX will improve, what to expect is that you select a device to enable for passthrough, and then the other IOMMU siblings are enabled automatically.

**Comment by tlehman** [comment]
I tested the mutating webhook and it worked as expected, using the latest in 1.1-head
