### ISSUE TITLE
[ENHANCEMENT] Show disk count in dashboard overview

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3455]
**Is your enhancement related to a problem? Please describe.**

To see the status of the disks added to the node you need to check the host list page, hopefully, can check it in the dashboard overview

**Describe the solution you'd like**

Add block device count and status in the dashboard overview

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
Thanks for this @n313893254 
This looks great :smile: :+1: 

I'll go ahead and close this out!

Tested on Harvester Version: master-d739c2a4-head 
![Screenshot from 2023-05-19 04-59-20](https://github.com/harvester/harvester/assets/5370752/9b757aaa-7382-49c7-9b01-c929cea8f9fd)
