### ISSUE TITLE
[BUG] support-bundle-namespaces edit page style error

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3456]
**Describe the bug**

When the customer is selecting the namespaces which should be included in the support bundle, there is a visual bug on the page making the list run away to the right side.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/3a7be8e5-4595-4919-b0d6-8c084381ee18)

**To Reproduce**
1. click Setting tab
2. go to support-bundle-namespaces edit page
3. Select multiple namespaces

**Expected behavior**

The list should be properly wrapped to the next line and fit within the box

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/219038052-682e78be-53d2-4991-9886-1a3d86153d6d.png)


Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.1-3e543a64-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Navigate to _Advanced/Settings_, then **Edit Setting** of _support-bundle-namespaces_
3. Dropdown list of Namespace should display correctly.
