### ISSUE TITLE
[BUG] cluster-registration-url should utilize additional-ca

### ISSUE THREAD

**Issue by tacerus** [harvester/harvester#3457]
**Describe the bug**

If trying to connect Harvester with Rancher using the `cluster-registration-url` feature, the YAML file download fails if the Rancher webserver is using a certificate signed by a custom certificate authority for HTTPS.

**To Reproduce**
1. Add a custom CA certificate using `additional-ca` in the Harvester settings
2. Add a `cluster-registration-url` pointing to a Rancher webserver using a certificate signed by this CA
3. Inspect the logs of the `cattle-cluster-agent` pods - they return:

```
time="2023-01-24T16:51:22Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://rancher-cluster1.suse.de\": x509: certificate signed by unknown authority"
```

**Expected behavior**

The pods downloading the YAML file from Rancher should have the `additional-ca` CA certificate installed, in order for them to correctly verify the authenticity of the webserver.

**Support bundle**

Where should I upload this?

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): n/a

**Additional context**
This has been discussed internally in https://suse.slack.com/archives/C02CN3TT61M/p1674559727853219.

**Comment by ibrokethecloud** [comment]
hi @tacerus are you please able to confirm the rancher cluster setup? I assume we are using a private ca signed cert, and that was added via additional ca certs

https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/installation-references/helm-chart-options#additional-trusted-cas

**Comment by tacerus** [comment]
Yes, that is correct - it was added using the additional CA certs option in the Harvester settings/GUI.

**Comment by ibrokethecloud** [comment]
issue was related to custom cert settings while installing rancher

**Comment by iosifnicolae2** [comment]
It seems that we have a regression in https://github.com/harvester/harvester/issues/3676
