### ISSUE TITLE
[BUG] S3 Backup Target Fails `Driver s3 is not supported!` 

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3462]
**Describe the bug**
When setting up a backup target via S3 - a failure is encountered.
Either in an attempt to set up a backup target with Minio or AWS S3.

**Pre-reqs**
1.  Either a Minio bucket or AWS S3 bucket

**To Reproduce**
1. Go to Settings -> Backup Target -> Edit Setting
1. Select S3, fill out details for either a Minio bucket or AWS S3 Bucket
1. Click Save

**Expected behavior**
S3 be able to be configured as a backup-target without issue for AWS S3 or Minio.

**Environment**
 - Harvester ISO version:  Version: master-6fd9a5bb-head ( 02/10/23 master-head release )
 - Underlying Infrastructure: qemu/kvm

**Additional context**
(S3 Req - Response shown)
A PUT to: `https://harvester-vip-ip/v1/harvester/harvesterhci.io.settings/backup-target`
Yields the response of:
```
{
  "type": "error",
  "links": {},
  "code": "Invalid",
  "message": "admission webhook \"validator.harvesterhci.io\" denied the request: Driver s3 is not supported!",
  "status": 422
}
```
With the request body of:
```
{
  "id": "backup-target",
  "type": "harvesterhci.io.setting",
  "links": {
    "remove": "https://192.168.122.57/v1/harvester/harvesterhci.io.settings/backup-target",
    "self": "https://192.168.122.57/v1/harvester/harvesterhci.io.settings/backup-target",
    "update": "https://192.168.122.57/v1/harvester/harvesterhci.io.settings/backup-target",
    "view": "https://192.168.122.57/apis/harvesterhci.io/v1beta1/settings/backup-target"
  },
  "apiVersion": "harvesterhci.io/v1beta1",
  "kind": "Setting",
  "metadata": {
    "creationTimestamp": "2023-02-10T17:29:50Z",
    "fields": [
      "backup-target",
      null
    ],
    "generation": 2,
    "managedFields": [
      {
        "apiVersion": "harvesterhci.io/v1beta1",
        "fieldsType": "FieldsV1",
        "fieldsV1": {
          "f:status": {
            ".": {},
            "f:conditions": {}
          }
        },
        "manager": "harvester",
        "operation": "Update",
        "time": "2023-02-10T17:29:51Z"
      }
    ],
    "name": "backup-target",
    "relationships": null,
    "resourceVersion": "7719",
    "state": {
      "error": false,
      "message": "Resource is current",
      "name": "active",
      "transitioning": false
    },
    "uid": "f9ee218c-9ef3-47d5-80f8-8811212b5d0d"
  },
  "status": {
    "conditions": [
      {
        "error": false,
        "lastUpdateTime": "2023-02-10T17:29:51Z",
        "status": "False",
        "transitioning": false,
        "type": "configured"
      }
    ]
  },
  "value": "{\"type\":\"s3\",\"endpoint\":\"\",\"bucketName\":\"generictest\",\"bucketRegion\":\"us-west-2\",\"accessKeyId\":\"COMMENTINGOUTFORSECURITY\",\"secretAccessKey\":\"REMOVEDFORSECURITY\"}"
}
```

**AWS S3 Bucket Result:**
![Screenshot from 2023-02-10 11-41-23](https://user-images.githubusercontent.com/5370752/218829471-3861f160-ca36-4d7f-ac68-382fa3c968ec.png)

**Minio Bucket Result:**
![Screenshot from 2023-02-10 12-09-02](https://user-images.githubusercontent.com/5370752/218829609-c77cac7e-6316-4bf1-9ed7-f1748b4a81cc.png)

**Comment by FrankYang0529** [comment]
It looks like it's caused by this fix. Since we remove `_ "github.com/longhorn/backupstore/nfs"` and `_ "github.com/longhorn/backupstore/s3"`, go module doesn't include nfs and s3 in vendors.

https://github.com/harvester/harvester/commit/18c51c9dc1b6c874946731ff696d30b63692d732#diff-90074475cdf11ead1ad94efcfe5805ec16d81241f2c7f4d7f71bc6c89cfe740d

**Comment by irishgordo** [comment]
**validation passed**
Thanks for the fix @FrankYang0529  - looks like setting up a backup-target for S3 works again now.
Tested on v1.1.2-rc1.
Closing this out :smile: 

![Screenshot from 2023-02-16 17-54-29](https://user-images.githubusercontent.com/5370752/219529549-78c4c2a7-6b02-488e-930b-f9b14c599753.png)
![Screenshot from 2023-02-16 17-55-54](https://user-images.githubusercontent.com/5370752/219529725-5a1f2d9e-721f-440f-a17b-fc76d4a7f7b5.png)
