### ISSUE TITLE
[BUG] after Edit as yaml, the source.http.url of vm's datevolume change to empty

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#347]
**Describe the bug**

after `Edit as yaml` , the `source.http.url` of vm's datevolume change to empty.
vm error
![image](https://user-images.githubusercontent.com/15064560/102185732-79b45f00-3eec-11eb-8afb-7a6487d9db49.png)

**To Reproduce**
1. click create on vm page
2. use iso template
3. select vm image
4. click `Edit as yaml`
![image](https://user-images.githubusercontent.com/15064560/102187009-61ddda80-3eee-11eb-85d1-631afe3115f4.png)
![image](https://user-images.githubusercontent.com/15064560/102187034-6c986f80-3eee-11eb-9b5e-b6c5011ed3aa.png)
5. click create

**Expected behavior**

1. in vm yaml, source.http.url is not empty
2. vm pending not vm error
**Log**

![image](https://user-images.githubusercontent.com/15064560/102186077-0bbc6780-3eed-11eb-817d-e48961f45b3a.png)

**Environment:**
 - Harvester commit `3efa979`

**Additional context**

**Comment by DaiYuzeng** [comment]
Hi, @futuretea !
I can't reproduce it on my environment by following your steps.
Could you try to reproduce it once again?

**Comment by DaiYuzeng** [comment]
![截屏2020-12-21 下午4 12 43](https://user-images.githubusercontent.com/15041915/102754087-63544a80-43a7-11eb-9035-ee2ba0be9688.png)

**Comment by DaiYuzeng** [comment]
If the form fields have value before using template, it will be lost.
It looks good, i think the template should only fill in the form and don't care about the existing value of it.
Would you give us some advice?
@guangbochen

**Comment by futuretea** [comment]
Close in favor of  after using backing image, source.http.url is unused, and `Edit by yaml` is removed.
