### ISSUE TITLE
[BUG] app mode installation by default is not successful

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#348]
**Describe the bug**

app mode installation by default is not successful with either using helm or from the catalog apps

**To Reproduce**
1. refer to the https://github.com/rancher/harvester/tree/master/deploy/charts/harvester to install the Harvester app 
1. install the Harvester as Rancher Catalog Apps

**Expected behavior**

1. the app is installed successfully

**Log**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
Same as #337
Validated
