### ISSUE TITLE
[BUG] Cluster network stuck in *Not Ready* 

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3482]
### Describe the bug
Cluster Network/Config could be created successfully, but unable to select (the created Cluster Network) in VM Network because it shows **Not Ready**.
re-create it will not fix the bug.

### To Reproduce
1. Install Harvester with any nodes
2. Create Cluster Network and relevant Cluster Config
3. Create VM Networks

### Expected behavior
Cluster Network should not stuck in **Not Ready** status or User should able to know why it stuck.

## Environment:
 - Harvester ISO version: **master-8f2dbbd3-head**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
![image](https://user-images.githubusercontent.com/5169694/219277472-cd8536ba-7dd4-49aa-8684-53b46db37dfb.png)
![image](https://user-images.githubusercontent.com/5169694/219277499-54141977-880b-402c-b518-8f9c27fe83c4.png)

### Support bundle
[supportbundle_6cf40dbc-5754-4b3a-927d-c1887885ae33_2023-02-16T05-28-14Z.zip](https://github.com/harvester/harvester/files/10752498/supportbundle_6cf40dbc-5754-4b3a-927d-c1887885ae33_2023-02-16T05-28-14Z.zip)

**Comment by n313893254** [comment]
The issue has been fixed in https://github.com/harvester/charts/pull/141, and could be tested in v1.1.2-rc1.

The UI issue will track in https://github.com/harvester/harvester/issues/3488

**Comment by lanfon72** [comment]
Verified this bug probably fixed, I tested in 31 times and didn't encounter it.


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Run the code snippets[^1] as below to retry
```python
import sys
import json
from datetime import datetime, timedelta

import urllib3

from harvester_api import API

urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)


def loop(api, n=30):
    for idx in range(n):
        print(f"tick {idx}")
        code, data = api.clusternetworks.create('vlan1238')
        assert 201 == code, (code, data)
        code, data = api.clusternetworks.create_config("port1", "vlan1238", "eno50")
        assert 201 == code, (code, data)
        code, data = api.networks.create('1238', 1238, cluster_network='vlan1238')
        assert 201 == code
        endtime = datetime.now() + timedelta(seconds=60)
        while endtime > datetime.now():
            code, data = api.networks.get('1238')
            assert 200 == code
            route = data['metadata']['annotations']['network.harvesterhci.io/route']
            if "connectivity" in route:
                break
        assert json.loads(route).get('connectivity'), route
        print("tock")
        assert 200 == api.networks.delete('1238')[0]
        assert 200 == api.clusternetworks.delete_config('port1')[0]
        assert 200 == api.clusternetworks.delete('vlan1238')[0]


if __name__ == '__main__':
    endpoint = sys.argv[0]
    password = sys.argv[1]
    api = API.login(endpoint, 'admin', password, ssl_verify=False)
    loop(api)
```

[^1]: `harvester_api` could be installed in https://github.com/harvester/tests
