### ISSUE TITLE
[BUG] VlanConfig state display active but actual is "Not Ready"

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3488]
**Describe the bug**

VlanConfig state display is active but the actual is "Not Ready".

**To Reproduce**

https://github.com/harvester/harvester/issues/3482#issue-1587050378

**Expected behavior**

When a VLAN config has an error in the status of a VLAN status on the corresponding node or no corresponding VLAN status, the status should be "Not Ready".

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
@n313893254 thanks for this :smile: :+1:  

Tested on Harvester Version: v1.1-68cb406a-head 

Had 30 iterations, building cluster network config via Harvester API plus additional networks & creating cluster network.
Leveraging two virtualized nics:
```python
        code, data = api.clusternetworks.create_config("ports", "vlan1", "enp4s0", "enp3s0")
```
30 iterations, looked good - all 200s.
![Screenshot from 2023-02-28 11-28-34](https://user-images.githubusercontent.com/5370752/221958625-f023c8d9-a6bb-4cce-9351-50eb4a4098d0.png)
