### ISSUE TITLE
[BUG] virtio-container-disk: "Name" cannot be more than 20 characters

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#3492]
**Describe the bug**
Saving a VM on 1.1.2-rc1 I see `virtio-container-disk: "Name" cannot be more than 20 characters`

**To Reproduce**

Edit a VM that has a container disk

**Expected behavior**
The container disk name size should be restricted before or not limited.

<img width="729" alt="Screenshot 2023-02-16 at 1 17 59 PM" src="https://user-images.githubusercontent.com/5146963/219453782-9615ff00-df01-401a-881a-d9e35f9542a1.png">

**Environment**
 - Harvester ISO version: 1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
According to the k8s specification, I now set the maximum length of the name to 63 characters.

**Comment by irishgordo** [comment]
@WuJun2016 ,
Validated that on Harvester Version: master-f93d67e1-head - creating/editing of the name length to be more than 20 characters does work:
![Screenshot from 2023-02-22 13-22-08](https://user-images.githubusercontent.com/5370752/220762085-663e0165-b568-449c-bfe1-e7855637a5b0.png)

I'll go ahead and close this out :smile:
