### ISSUE TITLE
[BUG] Templates not clickable in VM creation

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3493]
**Describe the bug**

When you try to select a template, such as raw image, in VM creation it won't allow you to click them. You can just enter in the info manually though and it works.
**To Reproduce**
1. Create new VM
2. Enter name
3. Try to select a template

**Expected behavior**

You should be able to select a template
**Support bundle**

[supportbundle_f654ae19-7d6b-443b-af7a-05166afe3e59_2023-02-16T23-18-03Z.zip](https://github.com/harvester/harvester/files/10762260/supportbundle_f654ae19-7d6b-443b-af7a-05166afe3e59_2023-02-16T23-18-03Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node bare metal HP Proliant

**Additional context**

It looks like there might be an issue with the ui-plugins. I tried this with both the default v1.1.2 ui-index and ui-plugin-index as well as https://releases.rancher.com/harvester-ui/dashboard/latest/index.html and https://releases.rancher.com/harvester-ui/plugin/harvester-latest/harvester-latest.umd.min.js

![Greenshot_2023-02-16_15_06_50](https://user-images.githubusercontent.com/83787952/219523237-83252181-7619-4393-b32d-44f710789d34.jpg)
![Greenshot 2023-02-16 15 05 42](https://user-images.githubusercontent.com/83787952/219523247-c3320729-efb3-47f8-a71f-7003b1807dca.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/222100977-909cd75e-d3a5-4f58-abce-961555d47212.png)

Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **External**

### Verify Steps:
1. Follow **Step to reproduce** in https://github.com/harvester/harvester/issues/3493#issue-1588603156
