### ISSUE TITLE
[Doc] install.management_interface contains old description from `networks` (<v1.1)

### ISSUE THREAD

**Issue by johanot** [harvester/harvester#3496]
https://docs.harvesterhci.io/v1.1/install/harvester-configuration#installmanagement_interface says:

>  Each key-value pair represents a network interface. The key name becomes the network name, and the values are configurations for each network.

This is no longer true since v1.1.

**Comment by bk201** [comment]
@johanot Thanks for reporting this!

**Comment by LucasSaintarbor** [comment]
@guangbochen Which key-value pairs no longer represent a network interface? Should this section clarify the key-value pairs that represent a network interface vs. key-value pairs that do not?

**Comment by bk201** [comment]
@LucasSaintarbor I think we just need to remove the sentence completely.

>Each key-value pair represents a network interface. The key name becomes the network name, and the values are configurations for each network.

New (`install. management_interface`): https://docs.harvesterhci.io/v1.1/install/harvester-configuration/#example-12
Old (`install.networks.<network_name>`): https://docs.harvesterhci.io/v1.0/install/harvester-configuration#example-11
