### ISSUE TITLE
[ENHANCEMENT] Add backward compatibility support and integration tests for Harvester terraform

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3497]
**Is your enhancement related to a problem? Please describe.**
Add backward compatibility support and integration tests for Harvester terraform.

**Describe the solution you'd like**
- For Harvester terraform releases, we should provide N-1 backward compatibility support, e.g., Terraform's new release for Harvester v1.2 should be compatible with Harvester v1.1 clusters.
- Add integration/e2e test to the https://github.com/harvester/terraform-provider-harvester repo to cover its example resource validation and upgrade tests.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by FrankYang0529** [comment]
After discussing with @bk201, we will combine this issue with [e2e tests](https://github.com/harvester/tests/blob/main/harvester_e2e_tests/integrations/test_z_terraform.py). However, currently, it only supports released versions([ref](https://github.com/harvester/tests/blob/98c2cbb39687612dd4703a45cd4e1c4e228e0bf9/harvester_e2e_tests/fixtures/terraform.py#L170-L177)). We would like to add support for branch head version. This issue will focus on add branch head testing to https://github.com/harvester/tests.

**Comment by FrankYang0529** [comment]
I think we can close the issue, because the latest daily e2e test already cover PR in this issue. Also, most of terraform looks good, so it means we can test master branch harvester terraform provider now.

cc @khushboo-rancher

**Comment by khushboo-rancher** [comment]
Thanks @FrankYang0529. Closing this as we can run e2e with master branch
