### ISSUE TITLE
[BUG] Failed to log in if extra cloud init file is configured on install

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#350]
**Describe the bug**
v0.1.0-rc2

**To Reproduce**
1. Serve the following file in HTTP server:
```
run_cmd:
- "echo test>/tmp/test"
```
2. install harvester by ISO, input URL for the above file in cloud init URL
3. complete installation and do log in with the password set.

**result**
Fail to log in

**Comment by futuretea** [comment]
Validated
