### ISSUE TITLE
[BUG] The test connectoin backup-target button on the setting page is invalid in multiple clusters

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3510]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/16f225e7-e692-4119-af9b-23c602003b60)

**To Reproduce**
1. Import a harvester into the rancher,
2. Enter the harvester cluster from the rancher
3. go to setting page
4. Click the `Test Connection` button in the backup-target configuration 

**Expected behavior**

The correct `backup-targe` test information should be returned

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.2-head  (v1.1-13b484cb-head)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/220703293-1c25fccd-67cb-46be-af73-2737c8a60721.png)


Test Information
----
* Environment: **baremetal DL369G9 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **External**
* Rancher Version: **v2.6-5d91d1afdd7d88da6c0530080b16a5ad6dae8d17-head**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Rancher, Import Harvester
3. Access Harvester via _Virtualization management_
4. Navigate to _Advanced/Settings_, setup **backup-target**
5. Click **Test connection**, notification message should displayed
