### ISSUE TITLE
[ENHANCEMENT] Include virtctl in the os

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3514]
**Is your enhancement related to a problem? Please describe.**

It's handy to control VMs with the CLI way.

**Describe the solution you'd like**

Include the virtctl CLI which matched our KubeVirt version.

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Verified this feature has been implemented.
![image](https://user-images.githubusercontent.com/5169694/223391590-2cea83d4-7178-4c7c-ae7b-6b0ad6bea47a.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1-054b48bf-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Console, `virtctl` should be available in `/usr/bin`
