### ISSUE TITLE
[BUG] Cluster members page is unavailable

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3515]
**Describe the bug**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/4830a4b4-4291-4aef-9b35-81698c795d19)

**To Reproduce**
1. Create a `v1.1.1 Harvester` cluster
2. Import the Harvester cluster into the latest rancher cluster (v2.7-head)
3. Enter Harvester from rancher
4. Click `RBAC` tab to enter the `Cluster Members` page

**Expected behavior**

The page can be displayed normally

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Rancher issue: https://github.com/rancher/rancher/issues/40663

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/222106690-4b68f94d-6615-4c9b-9217-ece30316bf51.png)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.1-a002d078-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-4ca4a7622b23634b5b4da02807943b2965e8b0d6-head**
* Rancher **ui-source** Option: **Auto**

### Verify Steps:
1. Follow **Step to reproduce** in https://github.com/harvester/harvester/issues/3515#issue-1594327639
