### ISSUE TITLE
[ENHANCEMENT]  enable addon by clicking the right menu

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3516]
**Is your enhancement related to a problem? Please describe.**

Now you can only enable `pcidevices-controller` when you enter the editing page. It is hoped that you can directly click the menu on the right to enable relevant configurations.

**Describe the solution you'd like**

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/7679447c-30db-432a-b545-0096b4e27948)

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
:+1: :smile:  this looks good @DaiYuzeng 
Tested on Harvester Version: master-c9d8825c-head 

![Screenshot from 2023-05-15 10-43-32](https://github.com/harvester/harvester/assets/5370752/d811730e-9196-4c90-adf8-5090831e7176)
![Screenshot from 2023-05-15 10-38-49](https://github.com/harvester/harvester/assets/5370752/5a55828d-6e0e-4c37-8332-ad1e4cc4309e)

I'll go ahead and close this out.
