### ISSUE TITLE
[BUG] The preset namespace on resource edit page is not correct

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3517]
**Describe the bug**

**To Reproduce**
1. Go to create a Secret in `cattle-logging-system`.
2. Go to Volume create page.
3. The current namespace is `cattle-logging-system`

**Expected behavior**

We can not create Volume in `cattle-logging-system`, we should improve the filter logic of namespace dropdown component.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-398d492b-head` (05/11). Close this issue.

### Result
When we create secret under the following namespace
1. cattle-logging-system
2. cattle-monitoring-system
3. fleet-default
4. harvester-public

  ![image](https://github.com/harvester/harvester/assets/29251855/a9d50738-84c3-4194-a301-e481d4193733)

Then create volume, the namespace all set the `default` 
  ![image](https://github.com/harvester/harvester/assets/29251855/d916164b-95cc-47aa-9ad3-b07cd983a19d)
  
  
  ![image](https://github.com/harvester/harvester/assets/29251855/eeb31056-06fb-42d9-b6fd-dcd8fc0430f1)




### Test Information
* Test Environment: single nodes Harvester bare machines
* Harvester version: `master-398d492b-head` (05/11)

### Verify Steps
1. Create the new secret, set namespace to `cattle-logging-system` 
2. Create a volume
3. Check the default namespace should not be the same with `cattle-logging-system` 
4. Repeat step 1 - 3 on cattle-monitoring-system, fleet-default and harvester-public

### Additional Context
Same behavior on creating image and virtual machine
