### ISSUE TITLE
[ENHANCEMENT] need to disable the management network and vlan network from switching to each other

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3518]
**Is your enhancement related to a problem? Please describe.**

When editing the vm network, we need to disable switching from management network to vlan network, or from vlan network to management network.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

When creating or editing a new network, you can switch between networks, but a saved network can only switch between networks of the same type.

**Comment by lanfon72** [comment]
Verified this enhancement has been implemented.

![image](https://user-images.githubusercontent.com/5169694/222109581-0c0d44d1-33ba-4175-9bc1-1ab29b8f4002.png)
![image](https://user-images.githubusercontent.com/5169694/222109632-beb0894d-756c-4dd3-8393-f77f75675a5c.png)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.1-a002d078-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create 2 VLANs
4. Create VM `vm1` with VLAN network as `nic-1`
5. Edit `vm1`, network `nic-1` should NOT able to be changed to `management network`
6. Add **management network** as `nic-2` to `vm1`
7. Edit `vm1`, network `nic-2` should NOT able to be changed to other VLANs
