### ISSUE TITLE
[BUG] Setting controller doesn't process the value when there is an error

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#3519]
**Describe the bug**
When we update a value in the setting, we always [add a hash to an annotation](https://github.com/harvester/harvester/blob/affd8002d97ea9a1ac96c03de577fe63cd751daa/pkg/controller/master/setting/handler.go#L85). If there is an error from [syner](https://github.com/harvester/harvester/blob/affd8002d97ea9a1ac96c03de577fe63cd751daa/pkg/controller/master/setting/handler.go#L89), the setting controller doesn't run syner again, because the hash is same. For some syncer, like [ssl-certificate](https://github.com/harvester/harvester/blob/affd8002d97ea9a1ac96c03de577fe63cd751daa/pkg/controller/master/setting/ssl_certificate.go#L20), we would like the setting controller to apply it again when [updating some k8s resources](https://github.com/harvester/harvester/blob/affd8002d97ea9a1ac96c03de577fe63cd751daa/pkg/controller/master/setting/ssl_certificate.go#L56-L91) has conflicts.

**To Reproduce**
1. Give a wrong value to `log-level` setting, like `test`.
2. We can only see one error message in the harvester pod. The setting controller doesn't process it again.

**Expected behavior**

Their is many error message in the harvester pod.

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-1222750f-head` (04/25). Close this issue.

### Result
After we set the wrong value `test` to `log-level`, the `harvester` deployment log will continuously prompt error process with the setting controller   

```
 harvester-b5d7b65bd-mktwc W0428 07:38:51.767341       7 warnings.go:70] network.harvesterhci.io/v1beta1 NodeNetwork is deprecated                          │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:38:30Z" level=info msg="set log level to info"                                                               │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:10Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus │
│ harvester-b5d7b65bd-r2t92 time="2023-04-28T07:39:11Z" level=error msg="error syncing 'log-level': handler harvester-setting-controller: not a valid logrus
```

![image](https://user-images.githubusercontent.com/29251855/235098945-7d12a7e2-8fab-4164-9664-ff47e0be27e3.png)


### Test Information
* Test Environment: 1 node Harvester local kvm machine
* Harvester version: `master-1222750f-head` (04/25)

### Verify Steps
1. On Harvester setting UI, set the log-level setting to `Info`
2. Access to Harvester master node and switch to root
3. Run K9s, edit the settings -> log-level 
4. Set the value to `test` and save
5. Search deployment -> Harvester 
6. Check the Harvester deployment log
