### ISSUE TITLE
[ENHANCEMENT] improve the pci-device addon as a stable feature release

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3524]
**Is your enhancement related to a problem? Please describe.**
Enhancement of the pci-device addon and make it a stable feature release.

**Describe the solution you'd like**
- more automation test coverage of the https://github.com/harvester/pcidevices repo.
- potential controller refactoring to remove its infinite loop.
- CVE fixies.
- documentation improvement.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by ibrokethecloud** [comment]
Ensure unwanted manifests and crd files are removed as they are not needed

**Comment by noahgildersleeve** [comment]
Tested in v1.2.0-rc3

- [x] Enable PCI Devices addin

- [x] Enable PCI passthrough on GPU

- [x] Disable PCI passthrough on GPU

- [x] Assign device

- [x] Run CUDA tests

- [x] remove device

- [x] Negative add device that is already assigned

- [x] Negative disable passthrough on device that has already been assigned to VM

- [x] Reassign device that has been removed

- [x] Negative Try to run CUDA tests on Machine without PCI device assigned

**Comment by noahgildersleeve** [comment]
PCI Devices with upgrade from v1.1.2 -> v1.2.0-rc4.

- [x] Enable PCI Devices addin

- [x] Enable PCI passthrough on GPU

- [x] Disable PCI passthrough on GPU

- [x] Assign device

- [x] Run CUDA tests

- [x] remove device

- [x] Assign device after removal, disabling PCI passthrough, then re-enabling PCI passthrough

- [x] Negative add device that is already assigned

- [x] Negative disable passthrough on device that has already been assigned to VM

- [x] Reassign device that has been removed

- [x] Negative Try to run CUDA tests on Machine without PCI device assigned

- [x] Upgrade cluster with PCI passthrough enabled and with a device assigned

**Comment by noahgildersleeve** [comment]
Closing as Verified. Found small UI bug and created new ticket #4319
