### ISSUE TITLE
[ENHANCEMENT] NICs that do not match the rules are still displayed after changing the node selector

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3525]
**Is your enhancement related to a problem? Please describe.**

When editing the VLAN config, the NICs that are now selected should be shown (marked as selected by default), leaving them empty looks like a strange interaction

**Describe the solution you'd like**

Leave the original options in place when filtering

**Describe alternatives you've considered**

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/220681949-6dd11fe0-a224-488a-9622-96424c055413.png)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-bac4bef9-head` (05/04). Close this issue.

### Result
* When one of the NIC `down` on the single node Harvester, edit the network config can display `not available` message correctly
![image](https://user-images.githubusercontent.com/29251855/236481165-67fa2a8b-d247-4cc7-9dfa-edfc5f93495c.png)

* When all of the specific NIC `down` on three nodes Harvester, edit the network config can also display `not available` message correctly and the down count number
![image](https://user-images.githubusercontent.com/29251855/236484648-a0c325ec-9c98-4b5f-9330-ff981d7608f6.png)

* When we recover the NIC up and edit the network config, the warning message disappear 
![image](https://user-images.githubusercontent.com/29251855/236485207-7602fb0d-6a8d-44a1-b2e5-fbeb953ca9c7.png)

### Test Information
* Test Environment: one and three nodes Harvester bare machines
* Harvester version: `master-bac4bef9-head` (05/04)

### Verify Steps
1. Create a cluster network
2. Create a network config and select one of the uplink NIC
3. ssh to node 
4. Make the uplink NIC down with command `ip link set <ens8> down`
5. Edit the network config and check the uplink state 
6. ssh to node 
7. Make the uplink NIC up with command `ip link set <ens8> up`
8. Edit the network config and check the uplink state 
9. Repeat above steps on three nodes harvester, each node have the same NIC `enp179s0f1`
