### ISSUE TITLE
[BUG] Correct URL for cloud-init Network Data "Learn More"

### ISSUE THREAD

**Issue by vincemulhollon** [harvester/harvester#3528]
**Describe the bug**
For a specific VM in Harvester, "Cloud Config" "Network Data" "Learn more" is a hyperlink to

https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html

Which is 404

**To Reproduce**

Log into Rancher 2.7.1, select any Harvester 1.1 HCI cluster, "Virtual Machines", select any VM, "Cloud Config", scroll down to Network Data, read the text "The network-data configuration allows you to customize the instance’s networking interfaces by assigning subnet configuration, virtual device creation (bonds, bridges, vlans) routes and DNS configuration. Learn more"

Note that "Learn More" links to:

https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html

Which is 404

**Expected behavior**

"Learn more" AFAIK should link to

https://cloudinit.readthedocs.io/en/latest/reference/network-config-format-v1.html

Note it's a "reference" now instead of a "topic".

**Environment**
 - Harvester ISO version: 1.1 recently installed a week ago

**Comment by futuretea** [comment]
Thank you very much for your feedback, we will fix it. CC @WuJun2016

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/222112481-44d7de42-10d8-446a-bd1d-7189e935aa4c.png)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.1-a002d078-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to dashboard, navigate to page _Virtual Machines_
3. Click **Create** and navigate to tab _Advanced Options_
4. Link of `Learn More` should point to correct page
