### ISSUE TITLE
[BUG] Harvester management URL shows Unavailable in the console

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#353]
**Describe the bug**
After installation the console shows:
![image](https://user-images.githubusercontent.com/5697937/102295936-538fcd00-3f87-11eb-8de4-858bb31767a0.png)

**Log**
Logs in `/var/log/console.go`:
![image](https://user-images.githubusercontent.com/5697937/102295884-3eb33980-3f87-11eb-98e0-c04032abeabb.png)

**Environment:**
 - Harvester ISO version: v0.1.0-rc2

**Comment by DreamTeamWangbowen** [comment]
I have the same problem，URL is unavailable，status is settingup... @guangbochen

**Comment by gitlawr** [comment]
Can you access the UI by `https://<node-ip>:8443`?

**Comment by DreamTeamWangbowen** [comment]
> Can you access the UI by `https://<node-ip>:8443`?

node-ip ？I can't , it seems that static ip cannot be configured，my previous ip eth0 is 200.201.9.128，now ip eth0 is 169.254.45.193，the network segment has changed.

**Comment by gitlawr** [comment]
DHCP service is required at the moment, static IP support is tracked in https://github.com/rancher/harvester/issues/367

**Comment by DreamTeamWangbowen** [comment]
> DHCP service is required at the moment, static IP support is tracked in #367
root@colibri-t30:~# connmanctl
connmanctl> config ethernet_00142d259a48_cable --ipv4 manual 192.168.10.2 255.255.255.0 192.168.10.1
connmanctl> exit
like this, I configured the static IP， --ipv4 manual 200.201.9.128 255.255.248.0 200.201.15.254，the status changed to running state，but still can't ping.

**Comment by DreamTeamWangbowen** [comment]
okay! thank you very much,I try to reboot the host,
it's succeessful! now，not only can ping, but can also log in dashboad！

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester-installer/pull/47

**Comment by DoNotSayYes** [comment]
Validated on master-head, that kind of error messages were not found.
![image](https://user-images.githubusercontent.com/57614736/110315030-9d96c500-8043-11eb-8517-d91fd6eff200.png)
![image](https://user-images.githubusercontent.com/57614736/110315286-00885c00-8044-11eb-926a-d0a1a6f23f73.png)

**Comment by zengqingfu1442** [comment]
I also came across this error.
