### ISSUE TITLE
[BUG] You can see VMs in harvester-system namespace in Rancher virtual machine management

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3530]
**Describe the bug**

You can see VMs that are in the harvester-system namespace in the virtual machine list from an upstream Rancher cluster.
**To Reproduce**
1. Create a VM on Harvester in the harvester-system namespace
2. Import Harvester into Rancher
3. Navigate to VM list from virtual machine management with admin Rancher user
**Expected behavior**

**Support bundle**

[support bundle still showing upgrade thing.zip](https://github.com/harvester/harvester/files/10808415/support.bundle.still.showing.upgrade.thing.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc1
 - Rancher version: single node Docker v2.7.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Harvester libvirt VM

**Additional context**
This seems to be an issue with filtering the namespaces. We don't see this in the Harvester dashboard, but we do in the Rancher integrated dashboard. I saw this when a VM was left in terminating after an upgrade with #3529 . In the screenshots the darkmode is Harvester dashboard, and the light mode is Harvester through Rancher virtual machine management. I'm going to see if I can get this to repro with less steps.

![Screenshot_20230222_130823](https://user-images.githubusercontent.com/83787952/220761859-fdbf7f9a-82ca-4f59-aa46-d32ea70ebfd5.png)
![Screenshot_20230222_130812](https://user-images.githubusercontent.com/83787952/220761863-f3a7fab1-77b6-4c88-aa83-d94bfa742493.png)

**Comment by WuJun2016** [comment]
Hi @noahgildersleeve  namespace filtering is a known issue in `rancher 2.7.1` and has been fixed in `rancher 2.7.2-head`,
Normally, users cannot create VMS in the h`arvester-system` namespace.  The vm you see `upgrade-repo-hvst-upgrade-p9w6j` in `harvester-system` is created when the backend is upgraded.

**Comment by irishgordo** [comment]
This looks to be good :smile:  - tested on v2.7.2-rc5 w/ v1.1.2-rc3
I'll go ahead and close this out
![Screenshot from 2023-03-10 16-02-43](https://user-images.githubusercontent.com/5370752/224451880-3f9f6884-9ca6-4cab-9009-5dbd6404b541.png)
