### ISSUE TITLE
[BUG] A untagged network's bond and bridge not exists after reboot

### ISSUE THREAD

**Issue by zealoussnow** [harvester/harvester#3532]
**Describe the bug**
Create a UntaggedNetwork, after reboot the system, the bond and bridge not exists

**To Reproduce**
1. Go to 'Cluster Networks/Config', create a cluster network
2. Go to  'VM Networks', create a Untagged network, has bond and bridge
<img width="350" alt="image" src="https://user-images.githubusercontent.com/2801287/220851902-ab23e0ab-16e6-4133-bd49-9f9a987d1959.png">

4. Reboot the system

**Expected behavior**

1. Untagged network's bond and bridge exists

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1

**Comment by w13915984028** [comment]
This bug, should have been solved in https://github.com/harvester/harvester/issues/3337.

cc @yaocw2020

**Comment by w13915984028** [comment]
The fix have been verified  https://github.com/harvester/harvester/issues/3337#issuecomment-1431579574

thanks @zealoussnow  for reporting 

close issue.
