### ISSUE TITLE
[BUG] The namespace and name field of the created page disappear 

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3533]
**Describe the bug**

Import `v1.2-head` harvester in `2.7.1` rancher. 

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/055e5953-d07e-4ad2-8190-b4fa21d0638c)

**To Reproduce**
1. Create a v2.7.1 rancher
2. Create a v1.1.2-head harvester
3. Import the `harvester` into the `rancher`
4. Go to the `harvester` page
5. Click `Volume` tab
6. Click `Create` button
7. name and namespace filed are not visible in the header of the creation page

**Expected behavior**

The name and namespace filed are displayed normally

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **baremetal DL360 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **External**
* Rancher Version: **v2.6-5d91d1afdd7d88da6c0530080b16a5ad6dae8d17-head**

### Verify Steps:
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Access Harvester via _Virtualization Management_
4. Fields (_Name_, _Namespace_, _Description_) should displayed correctly in Create pages (eg: VM, Volume, Image, Template..etc)
