### ISSUE TITLE
Failure to attach PCI network adapter to VM Harvester v1.1.1

### ISSUE THREAD

**Issue by wstutt** [harvester/harvester#3534]
**Describe the bug**
Attempting to enable a Broadcom BCM57416 NetXtreme-E Dual-Media 10G RDMA Ethernet controller as a PCI Passthrough device.
PCI Passthrough is successfully created in the Advanced/PCI devices tab.
Device shows as available to virtual machines.
When device is attached to virtual machine, virtual machine will not power on and throws an unschedulable error. 0/3 nodes are available, node affinity selector, No preemption victims found for incoming pod, 2 Premption is not helpful for scheduling.

PCI Device can be attached after VM creation, but does not show as a device to the VM Post-power-on

**To Reproduce**
1. Enable PCI Passthrough
2. Create PCI Device
3. images -> Create Virtual Machine -> select PCI Device
4. VM Tab
5. View error

**Expected behavior**
Our expected end state is to be able to create a pci network adapter that can be used as a network tap for virtual machines.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.1
 - Underlying Infrastructure (SuperMicro SN5000):

**Additional context**

**Comment by tlehman** [comment]
I'm performing a reproduction of this on an HP Gen10 server, using 1.1-head (newer than 1.1.1), and I noticed that the devices say they are passthrough enabled, but they are not bound to the vfio-pci driver, this prevents them from being used in the VM, investigating.

**Comment by tlehman** [comment]
Okay I am testing this on 1.1-head (version 20b8db05), which will be included in 1.1.2-rc2. I was able to attach a NIC to the VM, it was an Intel Corporation Cannon Lake PCH HECI Controller.

Caveats:
- I had to attach both it and "Intel Corporation Cannon Lake PCH HECI Controller #2" to the VM because both were in the same IOMMU Group. I am actively working on a fix that will automatically take care of this IOMMU constraint in #3451

**Comment by tlehman** [comment]
I tried again creating a new VM and enabling passthrough on a NIC, attached it from the VM tab, and it booted up. ~~Confirming now if it's properly attached and usable, one moment~~

Confirmed: it booted up and both NICs are connected:
![Screenshot from 2023-03-06 12-42-46](https://user-images.githubusercontent.com/261552/223226270-9ae4523d-87b8-4cba-af8d-0811716bf02b.png)

**Comment by tlehman** [comment]
Both received IP addresses as well, network connections on both are healthy

**Comment by markhillgit** [comment]
In our testing it is possible to do this in the upcoming 1.1.2, so please retry in 1.1.2 when it is available.

**Comment by wstutt** [comment]
> In our testing it is possible to do this in the upcoming 1.1.2, so please retry in 1.1.2 when it is available.

It's been a while, but this issue was resolved.  My issues were two-fold:
1) Broadcomm Network Drivers 
2) Intel Network Cards with more than one NIC were only showing up as a single device to the PCI-Passthrough tab.

Release 1.1.2 resolved issue 2) and I was able to accomplish my goals.
