### ISSUE TITLE
[Question] Can start but not boot a VM I migrated from Proxmox

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#3536]
this was its config:
boot:  
cores: 1
ide0: storage_ceph:vm-101-disk-0,size=563M
ide1: storage_ceph:vm-101-disk-1,size=1G
ide2: storage_ceph:vm-101-disk-2,size=307M
ide3: storage_ceph:vm-101-disk-3,size=102M
kvm: 0
memory: 2048
meta: creation-qemu=7.1.0,ctime=1676805514
name: ipvm
net0: pcnet=7A:8E:65:29:FB:00,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsihw: virtio-scsi-single
smbios1: uuid=0c3fe7c3-48b4-4cba-94be-f16aecdcaae5
sockets: 1
vmgenid: 91259bde-18c5-4fef-acb4-4e77d6667325

I configured the pcnet and used scsi for the volumes.
for the chipset I tried both  q35 and pc.

the VM will try to boot but has errors.
I didnt convert it or anything only uploaded the .qcow2 images. also I tried a few times to re-upload.

**Comment by ne0YT** [comment]
still relevant

**Comment by w13915984028** [comment]
@ne0YT could you please add more details about the process of VM migrations, how the VM image was generated, how to start it in Harvester,  was it  from `download/upload an image`. If there are some pictures about the `VM` start and `not boot`, that will be help.

Btw, we also need the information of Harvester version, the cluster setup.

thanks.
