### ISSUE TITLE
[BUG] Grafana monitor metric is not visible

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3537]
### Describe the bug
It's not visible in both fresh new and upgraded cluster.

### To Reproduce
1. Install Harvester with any nodes
2. Login to dashboard, navigate to _Dashboard_ page

### Expected behavior
Section contains _Cluster Metrics_ and _VM Metrics_ should be visible

## Environment:
 - Harvester ISO version: **v1.1.2-rc1** (fresh new and upgraded from **v1.1.1**)
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

### Additional context
1. Grafana is working and accessible via _Monitoring & Logging/Monitoring/Configuration:Grafana_
2. **Metrics** in VM's details page also invisible.

**Comment by w13915984028** [comment]
cc @WuJun2016, we discussed this before.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://user-images.githubusercontent.com/5169694/222099320-69b9e003-df00-4920-9a33-ec5dd85507ea.png)

Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.1.2-rc1**
* **ui-source** Option: **External**

### Verify Steps:
1. Follow **Step to reproduce** in https://github.com/harvester/harvester/issues/3537#issue-1597380910
