### ISSUE TITLE
[BUG] VM stuck in stopping state. Then after delete stuck in terminating phase

### ISSUE THREAD

**Issue by AdamJSoftware** [harvester/harvester#3539]
**Describe the bug**
One of my VM's crashed so it stopped itself. However, it wouldn't leave the stopping phase no matter what I did. So I tried deleting it after backing up the volume and now it's stuck in the terminating phase.

![image](https://user-images.githubusercontent.com/42972871/221042837-a906563e-6a3a-4e8f-b170-58b9cb3ae7e1.png)

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Supermicro HS11 + AMD EPYC 7551P

**Additional context**
One of my nodes stopped due to a power outage (VM was running on another node though). Don't think it's the issue though but guess it's worth mentioning.

**Comment by dseralathan** [comment]
Please try delete the VM using CLI

#kubectl get vms | grep -v Running        (it will list the vms which are not running 
#kubectl delete <vmname>

or check the POD status why its got stuck 

#kubectl get pods | grep -v Running       (it will list the pods which are not running )
#kubectl describe pod <podname>       ( check events ) due to volume or any other issue 

#if not needed delete that pod kubectl delete pod <podname>

**Comment by dseralathan** [comment]
Even after deleting using CLI and GUI ,  there is no POD related to VM when its in stopped state 

GUI still having the VM in Terminating state (yellow color)   . How to get ride of that 

# kubectl get vms | grep -i vm2
vm2     9d     Stopped    False
#kubectl get pods -A | grep -i vm2
#
#
 # kubectl delete vm vm2
virtualmachine.kubevirt.io "vm2 deleted
 #

**Comment by tomaszov** [comment]
We are facing the exact same issue on Harvester 1.1.2
I can get rid of it from the GUI by running this:

kubectl delete pod <PODNAME> --grace-period=0 --force --namespace <NAMESPACE>

But we get this message, that indicates it might not be the best solution:

warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.

**Comment by AdamJSoftware** [comment]
@tomaszov I ran force but nothing really happened, it just moved to the next terminating state (forget what it was). It only fully deleted after I rebooted the actual machine/node running the VM.

**Comment by AdamJSoftware** [comment]
well I had a power outage so it was involuntary forced reboot lol

**Comment by xeruf** [comment]
Also have a stuck VM and would prefer not to delete it or have stale resources around...

**Comment by w13915984028** [comment]
Suspect the root cause is same as https://github.com/harvester/harvester/issues/4033, the PVC/LH volume can't be un-mounted by kubelet, and in Harvester v1.3.0, this issue should be solved.

**Comment by w13915984028** [comment]
#4033 is validated to be fixed in v1.3.0, close this issue.
