### ISSUE TITLE
[BUG] backup restore does not carry the same MAC address

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#3541]
**Describe the bug**
When restoring a VM from backup, the MAC address isn't the same.

**To Reproduce**
1. Perform a VM backup on a harvester cluster
2. Power off the VM
3. Restore the VM on another cluster
4. The VM will have a different MAC address

**Expected behavior**
The new VM definition should be exact to the original backup

**Comment by w13915984028** [comment]
Together with https://github.com/harvester/harvester/issues/3682, https://github.com/harvester/harvester/issues/3602.

@FrankYang0529 any idea of this issue, is it lost or stripped ? thanks.

**Comment by FrankYang0529** [comment]
The `MacAddress` field is kept in VMBackup object, but we remove it when we restore a VM: https://github.com/harvester/harvester/blob/398d492b81aa6fcc60bdea3d270f501bd5e1eea9/pkg/controller/master/backup/restore.go#L570-L573

We may need to add an option to use the same `MacAddress`.

**Comment by w13915984028** [comment]
When the restored VM is targeting for an replacement of the original VM, the MAC address seems better to be kept.

But if the backup can be restored into a couple of VMs, then the MAC address cannot be identical.

An option to keep/drop MAC, will be a good enhancement.

**Comment by albinsun** [comment]
Provide test plan.
Let's test after UI side backport.
Ref. dashboard/pull/957 [Add KeepMacAddress checkbox to Backup restore page](https://github.com/harvester/dashboard/pull/957#top)

# Test Plan
## Environment
* Harvester
  * Version: `v1.3-071de3aa-head`
  * Profile: QEMU/KVM, 3 nodes w/ witness (8C/16G/500G)
  * ui-source: `Auto`

## Test Suites
### Prerequisites
1. <details>
   <summary> Create a VM
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/289cf4b2-05cc-4492-a52e-6a081ddfe536)
   </details>

1. <details>
   <summary> Take VM backup
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f676f7fc-c30e-4692-a206-ee9777173868)
   </details>

### Restore New
| Existence \ `KeepMac` | `True`                   |  `False`                 |
|:---------------------:|:------------------------:|:------------------------:|
|       `True`          |  Deny (TC1)              | Yes w/ **new** MAC (TC2) |
|       `False`         | Yes w/ **old** MAC (TCX) | Yes w/ **new** MAC (TCX) |


### Restore Replace
| Existence \ `KeepMac` | `True`                   |  `False`                 |
|:---------------------:|:------------------------:|:------------------------:|
|       `True`          | Yes w/ **old** MAC (TCX) | Yes w/ **new** MAC (TC2) |
|       `False`         | n/a                      | n/a                      |

**Comment by lanfon72** [comment]
Verified this feature has been applied.

![image](https://github.com/harvester/harvester/assets/5169694/38b1970c-a142-4459-82c1-88edfa343124)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create Cluster Network and VM Network
4. Create VM `vm1` with non-mgmt NIC
5. Setup **backup-target**
6. Backup `vm1` into `vm1b`
7. Restore `vm1b` into new VM `vm1bn`
8. Error message should displayed
9. Record mac address of `vm1` then delete `vm1`
10. Restore `vm1b` into new VM `vm1bnk` with **Keep Mac Address**
11. Mac address should be the same of the recorded from `vm1`
12. VM `vm1bnk` should restored successfully and operate normally
13. Restore `vm1b` into new VM `vm1bnk2` with **Keep Mac Address**
14. Error message should displayed
