### ISSUE TITLE
[BUG]  Not displayed after a cluster member is added

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3542]
**Describe the bug**

After importing harvester v1.1.2-head in the rancher 2.7.1 cluster, go to the harvester page to add cluster member. Adding cluster member succeeded, but it is not displayed on the page
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/8107e799-83e6-4c1a-9c74-2692757999ac)

**To Reproduce**
1. install rancher 2.7.1
2. install harvester v1.1.2-head
3. import harvester to rancher
4. Enter harvester and click `RBAC` => `cluster member`
5. click `Add` button,  input `admin`,  select `Default Admin`,  click Create
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/62a81c5e-cd20-4803-920b-6a7ef68dfe52)

**Expected behavior**

The information about the added member should be displayed。

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-616d751f-head` (03/01). Close this issue.

### Result
After adding member in RBAC -> Cluster member. 
We can user correctly added on the page

![image](https://user-images.githubusercontent.com/29251855/222121190-ef9bc8e0-173d-4b3c-9ec1-5e6514b850c1.png)

![image](https://user-images.githubusercontent.com/29251855/222121250-71653d2e-4907-4191-bcdc-1414d2bdd53b.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-616d751f-head` (03/01)
* Rancher version: v2.7.1

### Verify Steps
1. install rancher 2.7.1
2. install harvester v1.1.2-head
3. import harvester to rancher
4. Enter harvester and click RBAC => cluster member
5. click Add button, input admin, select Default Admin, click Create
