### ISSUE TITLE
[FEATURE] Use VMTemplate with data to create RKE node

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#3546]
**Describe the solution you'd like**
Based on https://github.com/harvester/harvester/issues/571, we can have VMTemplate with data now. Node-driver can use this feature to add new RKE nodes very fast. For example, we can add a new method - "Create from a template" and users can choose a template to spin up new nodes with data.

![Screen Shot 2022-05-19 at 5 07 24 PM](https://user-images.githubusercontent.com/4927361/169257020-022534be-7c45-4e08-b287-06411219793e.png)

**Comment by bk201** [comment]
There is no plan to support this.
