### ISSUE TITLE
[ENHANCEMENT] Add *What's news* information before or after cluster upgraded

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3551]
### The problem
Users need to visit our [release page](https://github.com/harvester/harvester/releases) to get to know what thing changed.

### The solution
Before / after user perform upgrade, pop up a message to show what's changed in the new version.

### The Alternatives
Add a link in the upgrade message box for user to reference.

### Additional Context
We can just reuse the information written in releases like https://github.com/harvester/harvester/releases/tag/v1.1.1

**Comment by guangbochen** [comment]
@WuJun2016 feel free to ping me and @bk201 to discuss the design enhancement about this, thanks.

**Comment by WuJun2016** [comment]
Hi,  @lanfon72 
Enhancement for this issue:
1. We plan to display the information of [gitHub release notes](https://github.com/harvester/harvester/releases/tag/v1.1.2) to users through an iframe.
2. Add a `checkbox` to confirm that users have understood the upgrade information.

**Comment by WuJun2016** [comment]
> Hi, @lanfon72 Enhancement for this issue:
> 
> 1. We plan to display the information of [gitHub release notes](https://github.com/harvester/harvester/releases/tag/v1.1.2) to users through an iframe.
> 2. Add a `checkbox` to confirm that users have understood the upgrade information.

@lanfon72   GitHub prohibits users from using iframes to display GitHub-related pages, so we will only implement the enhancement for the second point.

**Comment by lanfon72** [comment]
Can we also add it to the upgrade information section (it displays upgrade progress), it would help user to check the release note when upgrade completed or stuck in some upgrade phase.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/261c6e3b-1f18-4866-92d9-d4b9f6d401f1)
![image](https://github.com/harvester/harvester/assets/5169694/f5668546-45f7-47af-b61e-6ab3b50cb30a)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-a5e74302-head** (same version upgrade)
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade[^1]
3. There should have a link for targeting version, and user will need to double confirm it

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
