### ISSUE TITLE
[BUG] both upload and download may fail due to LH GetFileChecksum in last step

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3555]
**Describe the bug**
 GetFileChecksum

The `GetFileChecksum` is in a defer func, it executes in the last step of upload or download, when this takes long time, it will cause some network components (e.g. the NGINX in Harvester) assumes the connection is dead

```

finishProcessing -> finishProcessingNoLock

DownloadFromURL
...
	defer func() {
		if finalErr := sf.finishProcessing(err); finalErr != nil {
			err = finalErr
		}
	}()


IdleTimeoutCopyToFile
...
	defer func() {
		if finalErr := sf.finishProcessing(err); finalErr != nil {
			err = finalErr
		}
	}()  
```

**To Reproduce**

1. Upload or download big image, (the size depends on the CPU computing power)
2. It may fail at 99%

**Expected behavior**

should not fail

LH needs to move `GetFileChecksum` out from upload/download, let `checksum` be an indepedent state.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Found in issue: https://github.com/harvester/harvester/issues/3450

Some user also mentioned the download big image failure (will add link when found the issue)

LH's enhancement: https://github.com/longhorn/longhorn/issues/5443

**Comment by WebberHuang1118** [comment]
This is already fixed in #3450 , by LH issue [#5443](https://github.com/longhorn/longhorn/issues/5443).
