### ISSUE TITLE
[BUG] When you use a VM template it clears out the list of networks

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3557]
**Describe the bug**

When you select a template for creating a VM it clears out the list of networks and only leaves the management network
**To Reproduce**
1. Start creating a new VM
2. Check the available networks
3. Select Use VM Template
4. Select raw image template
5. Check available networks
**Expected behavior**

You should be able to select a network while using a template
**Support bundle**

[supportbundle_d7f2c74f-c9df-4bef-8319-a5f2f54fdc44_2023-02-24T21-37-17Z.zip](https://github.com/harvester/harvester/files/10829013/supportbundle_d7f2c74f-c9df-4bef-8319-a5f2f54fdc44_2023-02-24T21-37-17Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node libvirt VM

**Additional context**
I was using the external UI-source on this and the default `ui-plugin-index` and `ui-index` due to current issues with the bundled ui assets.
![Screenshot_20230224_134112](https://user-images.githubusercontent.com/83787952/221298760-783483c0-ffde-42af-8bbe-2f1954d3dc3a.png)

![Screenshot_20230224_133501](https://user-images.githubusercontent.com/83787952/221299032-917021d7-4153-4f6e-a481-66dc033b5d8e.png)
![Screenshot_20230224_133452](https://user-images.githubusercontent.com/83787952/221299037-8244f582-8aa8-4dc5-a41f-fa1c3e4f2f2c.png)

**Comment by irishgordo** [comment]
Thanks for the fix @n313893254  - this looks good :smile:  :+1:  
Tested on v1.1.2-rc3
![Screenshot from 2023-03-10 12-27-35](https://user-images.githubusercontent.com/5370752/224423922-bb12707d-4355-4e13-ba51-4ff7105cba9e.png)
![Screenshot from 2023-03-10 12-24-54](https://user-images.githubusercontent.com/5370752/224423925-7bccb70d-c58d-4f52-9512-c68a737e45c1.png)
I'll go ahead and close this out :smile: :+1:
