### ISSUE TITLE
[BUG] Can't upgrade from v1.1.2-rc1 to v1.1.2-rc1

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3559]
**Describe the bug**

When you try to upgrade to the same version it hangs then eventually errors out saying `The current version v1.1.2-rc1 is less than the minimum upgradable version v1.1.0.`

**To Reproduce**
1. Install v1.1.2-rc2
2. Do an upgrade to the same ISO in the same way as the [air-gap upgrade](https://docs.harvesterhci.io/v1.1/upgrade/automatic/#prepare-an-air-gapped-upgrade)
3. Wait for upgrade to finish

**Expected behavior**

The upgrade should complete
**Support bundle**

[supportbundle_d7f2c74f-c9df-4bef-8319-a5f2f54fdc44_2023-02-25T21-39-45Z.zip](https://github.com/harvester/harvester/files/10832377/supportbundle_d7f2c74f-c9df-4bef-8319-a5f2f54fdc44_2023-02-25T21-39-45Z.zip)

**Environment**

 - Harvester ISO version: v1.1.2-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node libvirt VM

**Additional context**
I did this upgrade test on a single node that had all of the upgrade test pre-upgrade tasks done. I'm going to try to reproduce it without any of those tasks and will update this ticket. It looks like this might be an issue with the upgrade version checker. The upgrade from v1.1.1 worked fine.

![Screenshot_20230225_133931](https://user-images.githubusercontent.com/83787952/221380926-753a8fbd-ffa3-41ba-adb9-06ac324ed460.png)

**Comment by noahgildersleeve** [comment]
I checked this again and just a basic install and upgrade causes this error

**Comment by khushboo-rancher** [comment]
This needs to be tested with 1.1.2-rc2

**Comment by khushboo-rancher** [comment]
@noahgildersleeve Same upgrade should work now as v1.1.2 rc2 is available.

cc: @harvester/qa

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.1.2-rc2`. Close this issue.

### Result
We can upgrade the  three nodes Harvester cluster from v1.1.2-rc2 to v1.1.2-rc2 to the success state
![image](https://user-images.githubusercontent.com/29251855/224253262-23b857aa-308a-42d0-aca1-17577ccc2886.png)


### Test Information
* Test Environment: 3 nodes harvester on bare machines
* Harvester version: `v1.1.2-rc2`

### Verify Steps
1. Install v1.1.2-rc2 
2. Do an upgrade to the same ISO in the same way as the [air-gap upgrade](https://docs.harvesterhci.io/v1.1/upgrade/automatic/#prepare-an-air-gapped-upgrade)

  ![image](https://user-images.githubusercontent.com/29251855/224246819-ac2cf53d-d43c-40fc-9a2d-571bf1428d7b.png)
  
3. Wait for upgrade to finish
