### ISSUE TITLE
[BUG] Node/Disk Selector does not clone when clone a storage class 

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3560]
**Describe the bug**

Node/Disk Selector does not clone when clone a storage class 

**To Reproduce**
1. Go to the Storage Classes page
2. Create a storage class named "test" with Node/Disk Selector
3. Clone "test" storage class
4. Check the clone page

**Expected behavior**

The Node/Disk Selector should same as "test" storage class

**Comment by TachunLin** [comment]
Verified **fixed** on `master-616d751f-head` and `v1.1-a72900af-head`. Close this issue.

### Result
After we clone the storage class, the Node and Disk selector exists on the cloned storage class
![image](https://user-images.githubusercontent.com/29251855/222348724-6eff4da3-dc1b-4729-99f4-d358470bbab4.png)

![image](https://user-images.githubusercontent.com/29251855/222348772-09c12172-982e-4c69-abbf-991481e80f98.png)

![image](https://user-images.githubusercontent.com/29251855/222354866-3670ebc3-e03e-43d3-b6a5-8079344513ec.png)


### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: `master-616d751f-head` and `v1.1-a72900af-head`

### Verify Steps
1. Open Host -> Storage page
2. Add host tags 
3. Add disk tags
4. Go to the Storage Classes page
5. Create a storage class named "test" with Node/Disk Selector
6. Clone "test" storage class
7. Check the clone page
