### ISSUE TITLE
VM went to Offline  - Need that VM POD info

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3561]
Hi Team,

We have few VMs on a cluster and it went to powered off state , we are not able to get  any info about that VM .

How we can check why the VM went offline and any info .. ?  

node1:~ # kubectl get vms | grep -v Running
NAME                                  AGE    STATUS    READY
vm4   3d3h   Stopped   False
vm8   3d3h   Stopped   False
node1:~ #
node1:~ # kubectl get pods -A | grep -i vm4
node1:~ #
node1:~ # kubectl get pods -A | grep -i vm8
node1:~ #

We have 12 node cluster and many VMs running on it and only these 2 went offline .. 
cluster health looks good and I can see only one node went high load last night .

<img width="1610" alt="Screenshot 2023-02-27 at 2 41 21 PM" src="https://user-images.githubusercontent.com/117767598/221702477-ad8c4ebd-eef1-4166-8fca-32b050a15fb2.png">

**Comment by w13915984028** [comment]
@dseralathan Guess you have solved it. Below is FYI.

When you want to get the POD information, which carry the VM, you can: `kubectl get pods -A | grep "virt-launcher"`

The POD names like:
```
   virt-launcher-upgrade-repo-hvst-upgrade-qfqwl-tjtjd
```

And you can use `kubectl get virtualmachineinstance -A -oyaml` to get the VM instance detailed information.
