### ISSUE TITLE
[ENHANCEMENT] Bump Harvester csi and ccm on the rancher/charts repo

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3571]
**Is your enhancement related to a problem? Please describe.**
Need to bump Harvester csi and ccm on the rancher/charts repo

**Describe the solution you'd like**
bump Harvester csi and ccm on the rancher/charts repo

**Describe alternatives you've considered**

**Additional context**

**Comment by Vicente-Cheng** [comment]
RKE2 PR: 
- https://github.com/rancher/rke2-charts/pull/326

RKE PRs:
- https://github.com/rancher/charts/pull/2450 (for v2.7)
- https://github.com/rancher/charts/pull/2452 (for v2.6)

**Comment by guangbochen** [comment]
@Vicente-Cheng can u please help to bump the csi-driver chart in the [rke2 repo](https://github.com/rancher/rke2/blob/master/Dockerfile#L131), the minimum required k8s version to backport should be v1.24.x.
Also, we can move this issue to test, and the QA team should be able to test it by adding a custom catalog repo and verifying rke1 + ccm/csi chart installation.

**Comment by noahgildersleeve** [comment]
Validated that v1.24 had versions bumped in dev-v2.6. We are still waiting for the merge of dev-v2.7. This was validated in Rancher `v2.6-16a06b91c2faa94ed02abef77ed3ed63134b1f41-head` and Harvester `v1.1.2-rc4`

**Comment by noahgildersleeve** [comment]
I tested the [PR](https://github.com/rancher/charts/pull/2450) for dev-v2.7 and the versions matched up, but I couldn't get it to install. This was the case on RKE1 v1.24 and RKE1 v1.25. I changed the charts repo to `https://github.com/Vicente-Cheng/rke1-charts` and the branch to `bump-harvester-csi-driver-0.1.16`. It also looked like there might have been a problem with rancher-webhook deploying.
![Screenshot_20230329_175659](https://user-images.githubusercontent.com/83787952/228701467-c455734d-529b-4622-bde9-cc47493e7fe9.png)
I tested this with a single node docker deploy of Rancher v2.7-head and Harvester 3 node ipxe-examples setup on libvirt with Harvester v1.1.2-rc5.

**Comment by guangbochen** [comment]
@noahgildersleeve the `rancher-webhook` is not a part of the Harvester CCM or CSI driver chart, can you check your cluster deployment first? and remember to select to show all namespaces when checking the app deployment.

**Comment by noahgildersleeve** [comment]
Tested in Harvester v1.1.1 and Rancher v2.7-head and RKE1 with 1.25 and RKE1 with 1.24. Versions were bumped on both. CSI Driver deployed on both. Harvester Cloud Provider failed on both. I'm going to check v1.1.2-rc5 next and I'll update the ticket.

**Comment by noahgildersleeve** [comment]
I tested this with Harvester v1.1.2-rc5 and Rancher v2.7-head. I checked with RKE1 1.25 and RKE1 1.24. CSI driver worked with 0.1.16 fine, but cloud provider failed to create in all cases for both version 0.1.14 and 0.1.13 in all cases.

**Comment by noahgildersleeve** [comment]
It turns out that you can't install the cloud provider from the chart if you don't select Harvester (out of tree) as the cloud provider for RKE1 in the node driver provisioning step. @khushboo-rancher  validated this on v1.1.2-rc5. I'm going to recheck on v1.1.1.

**Comment by noahgildersleeve** [comment]
The versions were bumped correctly. This was validated on Harvester v1.1.1 and v1.1.2-rc5. It was also validated on Rancher v2.6-head and v2.7-head. There seem to be other issues with the deploys, but that is out of scope for this ticket.
