### ISSUE TITLE
[BUG] RKE2 cluster stuck in *Deleting* State after Harvester upgraded

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3572]
### Describe the bug
After upgrade Harvester to `v1.1.2-rc1`, existing VMs (RKE2 cluster) can't be deleted correctly.

![image](https://user-images.githubusercontent.com/5169694/222237075-1df5ea92-3d50-4a9d-b138-ba2b0b30b7a7.png)
![image](https://user-images.githubusercontent.com/5169694/222237125-40e2a2c0-3f9b-4fb1-abc9-d8e52bfa4459.png)

### To Reproduce
1. Install Harvester `v1.1.0` or `v.1.1.1` with 3 or 4 nodes
2. Import Harvester into Rancher
3. Create RKE2 cluster with 3 machines
4. upgrade Harvester

### Expected behavior
VMs should able to be deleted correctly

## Environment:
 - Harvester ISO version: **v1.1.2-rc1** (upgraded from `v1.1.0` or `v1.1.1`)
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
Volume and VMI been removed, but `virt-handler` still exists.
Delete the VM from Rancher or Harvester will both encounter this bug.

### Support bundle
[supportbundle_3eb39533-52d9-45a0-bae0-ab3db3613bcd_2023-03-01T18-58-39Z.zip](https://github.com/harvester/harvester/files/10864457/supportbundle_3eb39533-52d9-45a0-bae0-ab3db3613bcd_2023-03-01T18-58-39Z.zip)

**Comment by khushboo-rancher** [comment]
A similar issue - https://github.com/harvester/harvester/issues/3529

**Comment by lanfon72** [comment]
It looks duplicated, let me update it.

**Comment by khushboo-rancher** [comment]
Let this be open as the scenario looks little different from https://github.com/harvester/harvester/issues/3529

**Comment by chrisho** [comment]
I've verified that it looks like a VM Finalizer compatibility issue, but it's been fixed in the latest master release.
related PR: https://github.com/harvester/harvester/pull/3508.

**Comment by lanfon72** [comment]
Thanks @chrisho, confirmed this bug been fixed when upgraded to `v1.1-20b8db05-head`, close as this resolved.
