### ISSUE TITLE
[BUG] Add CIDR format validation

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3580]
**Describe the bug**

The CIDR here is invalid. The format of CIDR should be like `172.16.10.0/24`. We'll add a validation. 

<img width="561" alt="image-2023-03-02-17-52-29-340" src="https://user-images.githubusercontent.com/18737885/223009256-35dc1800-2053-463c-ad84-abac9c987ab3.png">

**To Reproduce**
1. Go to Networks -> Networks
2. Input an invalid CIDR
3. Click Save

**Expected behavior**

UI should prevent creating and throw an error

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-152642c2-head` (03/08). Close this issue.

### Result
When we add or update invalid CIDR in the following scenarios.
It will prompt error message to prevent to proceed. 

* Update CIDR without subnet mask `e.g 192.168.101.0`
![image](https://user-images.githubusercontent.com/29251855/223715020-b7bc7e05-16b0-4ef7-b81b-bff9622336e5.png)


* Use incorrect subnet mask value `e.g 192.168.101.0/0.5` or `192.168.101.0/33, ` 
![image](https://user-images.githubusercontent.com/29251855/223715204-fc66c644-d4de-4f67-b515-387a2675868a.png)

* Use unsupported character `e.g 192,168,101,0/24` 

* Use empty CIDR or empty gateway
![image](https://user-images.githubusercontent.com/29251855/223722379-a67075ea-dc17-43cb-ab5c-b9d9b2d944f4.png)

* Update invalid CIDR from edit yaml 
![image](https://user-images.githubusercontent.com/29251855/223723864-463bc5eb-8a6f-48c2-9220-43189695d161.png)


* Update existing vlan network config with incorrect CIDR
![image](https://user-images.githubusercontent.com/29251855/223722818-467b10d0-6eda-4a59-bf2d-23c397dbc994.png)

### Test Information
* Test Environment: 2 nodes Harvester on local kvm machine
* Harvester version: `master-152642c2-head` (03/08)

### Verify Steps
1. Prepare multi nodes Harvester cluster with multiple NICs 
2. Prepare network have multiple vlan network
3. Create a cluster network
4. Create a vlanconfig and set uplink to one available NICs (e.g ens7) 
5. Create a VM network and change to manual mode 
6. Add invalid CIDR format
7. Create a VM network with correct CIDR format
8. Update VM network with invalid CIDR
9. Edit yaml of VM network
10. Set invalid CIDR
