### ISSUE TITLE
[BUG] Harvester Master ISO Install Fails On Network Section: `Configure network failed: fork/exec : usr/bin/yip no such file or directory`

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3584]
**Describe the bug**
Filling out the network section, during the install the Harvester Master AMD64 iso fails.
```
Configure network failed: fork/exec : usr/bin/yip no such file or directory
```

**To Reproduce**
1. Use master iso, configure network section should show error

**Expected behavior**
Install to not fail

**Environment**
 - Harvester ISO version:  (03/02/23) Master Head
 - Underlying Infrastructure: qemu/kvm & bare-metal ssd based thinkcentre

**Additional context**
![Screenshot from 2023-03-02 11-15-04](https://user-images.githubusercontent.com/5370752/222540105-425d0e2c-2628-41f9-8f69-d7bdf4a83545.png)
![PXL_20230302_200014166](https://user-images.githubusercontent.com/5370752/222540137-6365541b-390b-42d8-a882-dd365a2e8de6.jpg)

**Comment by bk201** [comment]
@irishgordo Thanks for spotting this, we'll fix it.

**Comment by Vicente-Cheng** [comment]
hi @irishgordo,
I added `yip` back and tested the interactive installation.
It looks normal now.

Please help to verify. Thanks!!

**Comment by noahgildersleeve** [comment]
Tested in `master-0ef61127-head`.  Verified that install completed and basic health checks on VM looked good.
[supportbundle_8dc8f916-282a-417d-874d-71469cc54459_2023-03-03T20-07-55Z.zip](https://github.com/harvester/harvester/files/10885752/supportbundle_8dc8f916-282a-417d-874d-71469cc54459_2023-03-03T20-07-55Z.zip)
