### ISSUE TITLE
[BUG] hotplug volume of VM will perform IO error on the specific scenario

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#3586]
**Describe the bug**
hotplug volume will perform an IO error when it dead twice. In detail, this behavior would cause the related iSCSI connection to re-login. After that, the original hotplug volume does not use anymore on the VM. You may see the IO error message on the VM side or the VM will hang on when you try to access this hotplug volume.

**To Reproduce**
1. create one VM instance.
2. attach the hotplug volume.
3. manually delete the hp-volume-xxx.
4. manually delete the hp-volume-xxx (newly hp-volume- pod) again.
5. You could check the iSCSI connection that will logout and then login. Also, the disk on the VM should be broken.

**Expected behavior**
Even the hp-volume pod is killed more than twice. The volume should work as usual.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
It is related to kubevirt behavior. 
Kubevirt issue: https://github.com/kubevirt/kubevirt/issues/9263

**Comment by TachunLin** [comment]
Verified **fixed** on `master-35717460-head` (05/26). Close this issue.

### Result

After manually delete the volume pods attached on virtual machine with two and several times.
  ```
  harv0526:~ # kubectl get pods -A -o wide | grep hp-volume 
  default                     hp-volume-tm5nr                                         1/1     Running     0               4h3m    10.52.0.79        harv0526   <none>           <none>
  harv0526:~ # kubectl delete pods hp-volume-tm5nr
  pod "hp-volume-tm5nr" deleted
  harv0526:~ # kubectl get pods -A |grep hp-volume
  default                     hp-volume-bb6wl                                         1/1     Running     0               12s
  harv0526:~ # kubectl delete pods hp-volume-bb6wl
  pod "hp-volume-bb6wl" deleted
  ```

- The hp-volume pod can work as usual and do IO on the attached volume in VM
- VM don't have IO error message and the VM did not hang on when you try to access this hotplug volume.

After two times deletion of hp-volume pod, we can still write file to the disk
  ```
  vm:/mnt/data # lsblk
  NAME   MAJ:MIN RM SIZE RO TYPE MOUNTPOINT
  sdb      8:16   0   5G  0 disk 
  └─sdb1   8:17   0   5G  0 part 
  vda    253:0    0  20G  0 disk 
  ├─vda1 253:1    0   2M  0 part 
  ├─vda2 253:2    0  20M  0 part /boot/efi
  └─vda3 253:3    0  20G  0 part /
  vdb    253:16   0   1M  0 disk 
  vm:/mnt/data # sudo mkdir /data
  vm:/mnt/data # sudo mount /dev/sdb1 /data
  vm:/mnt/data # echo "This is a file on the second disk" > /data/02_file_on_second_disk.txt
  vm:/mnt/data # cat /data/02_file_on_second_disk.txt
  This is a file on the second disk
  ```
After several times deletion on hp-volume pod, we can still write file to the disk

  ```
  vm:/mnt/data # mkdir /data2
  vm:/mnt/data # sudo mount /dev/sdc1 /data2
  vm:/mnt/data # echo "This is a 5th delete on the second disk" > /data2/05_file_on_second_disk.txt
  vm:/mnt/data # cat /data2/05_file_on_second_disk.txt
  This is a 5th delete on the second disk
  ```


### Test Information
* Test Environment: single nodes Harvester on local kvm machine
* Harvester version:`master-35717460-head` (05/26)

### Verify Steps
1. Create a new volume with default storage-class
2. Create a VM in running state
3. Add volume to the VM 
4. Check the current hotplug volume 
  ```
  kubectl get pods -A | grep hp-volume 
  ```
5. Manually delete the hp-volume-xxx.
  ```
  kubectl delete pods hp-volume-tm5nr
  ```
6. Manually delete the newly created hp-volume-xxx again.
7. ssh to the VM
8. mount the attached volume 
9. Create file and write content to the attached volume
10. Check the volume can work as expected with IO
