### ISSUE TITLE
[BUG]Confirm opensearch component of logging is available in v1.2.0

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3589]
**Describe the bug**

**To Reproduce**
1. Go to `Logging / Output`
2. Opensearch component of logging should be available.

![image.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/c4c6f64f-0934-4547-a50a-5e0e1fef321b)

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verifing on `master-1222750f-head` (04/25).

### Result
Now we could select `opensearch` option when we create `Output` and `Cluster Output`. 
![image](https://user-images.githubusercontent.com/29251855/234217997-496c7f83-7945-4547-9b5e-0592c8241bf7.png)

With `opensearch` as the provider
![image](https://user-images.githubusercontent.com/29251855/234217871-19069fc7-af04-439d-9650-3aea1b774461.png)

* Harvester can integrate with external opensearch server to output logs to 
![image](https://user-images.githubusercontent.com/29251855/234841008-abf23eae-f5fd-44dc-81ea-b9f8369036bb.png)

### Test Information
* Test Environment: 2 nodes local kvm machine
* Harvester version: `master-1222750f-head` 

### Verify Steps
1. Open Logging Output 
2. Create an output 
3. Select opensearch option 
4. Provider related value and create 


### Steps to integrate with external opensearch service

1. Use docker-compose to provision the opensearch nodes and dashboard
2. Enable logging Addon on Harvester 
3. Create a secret in `cattle-logging-system` namespace, named with secret, set key=`password` , value=`admin`
4. Create a cluster output, set the scheme=`https`, port=`9200` , Index Name=`harvester`
5. Set user=`admin` and select `secret` as the password
6. Uncheck the `Verify SSL` 
7. Create a cluster flow and select the cluster output in step 3
8. Open opensearch dashboard, create a index named `harvester` under Index Management -> Indices
9. Create a index pattern in Stack management -> Index patters, select index `harvester`
10. Go back to Harvester, edit the yaml of cluster output 
11. Add the parameter under opensearch  and save
  ```
  suppress_type_name: true
  ```
12. On opensearch dashboard, add a filter in Discover page and select `id` -> find `harvester` 
13. Switch to harvester filter to display the logs

**Comment by TachunLin** [comment]
@DaiYuzeng, 
Since when we test the integration with opensearch version v2.6.0
We need to edit yaml of the `Cluster Output` and add the following parameter 
```
suppress_type_name: true
```
Without this steps, the opensearch server would reject the Harvester request with 400 error
As per discussed, we would suggest to having an enhancement to expose this parameter on UI when user select opensearch as the output provider to reduce the configuration effort.

**Comment by TachunLin** [comment]
Verified on `master-2ba017d4-head` (05/08)

### Result
Verified can pass the following functionality, positive and negative test 

- [x] `suppress_type_name` attribute exists when we select `opensearch` in output and cluster output page 
- [x]  `suppress_type_name` attribute default state is `checked`

    ![image](https://user-images.githubusercontent.com/29251855/236789386-46f91ba6-91bb-40b2-a5df-c8498f6f77ec.png)


- [x]  `suppress_type_name` should display true when we edit yaml content `suppress_type_name: true`
- [x]  With the new `suppress_type_name` attribute,  we can correctly integrate Harvester logging output to opensearch dashbaord
    ![image](https://user-images.githubusercontent.com/29251855/236788911-c647b690-bebe-4d11-b3b2-34d5c3a2b396.png)
- [x]  When we check / uncheck the supress_type_name attribute, the yaml content can change accordingly. 



### Test Information
* Test Environment: single nodes harvester on local kvm machine
* Harvester version: `master-2ba017d4-head` (05/08)


### Verification Steps
Verifing on `master-1222750f-head` (04/25).

### Result
Now we could select `opensearch` option when we create `Output` and `Cluster Output`. 
![image](https://user-images.githubusercontent.com/29251855/234217997-496c7f83-7945-4547-9b5e-0592c8241bf7.png)

With `opensearch` as the provider
![image](https://user-images.githubusercontent.com/29251855/234217871-19069fc7-af04-439d-9650-3aea1b774461.png)

* Harvester can integrate with external opensearch server to output logs to 
![image](https://user-images.githubusercontent.com/29251855/234841008-abf23eae-f5fd-44dc-81ea-b9f8369036bb.png)

### Test Information
* Test Environment: 2 nodes local kvm machine
* Harvester version: `master-1222750f-head` 

### Verify Steps
1. Open Logging Output 
2. Create an output 
3. Select opensearch option 
4. Provider related value and create 


### Steps to integrate with external opensearch service

1. Use docker-compose to provision the opensearch nodes and dashboard
2. Enable logging Addon on Harvester 
3. Create a secret in `cattle-logging-system` namespace, named with secret, set key=`password` , value=`admin`
4. Create a cluster output, set the scheme=`https`, port=`9200` , Index Name=`harvester`
5. Set user=`admin` and select `secret` as the password
6. Uncheck the `Verify SSL`
7. Ensure the `supress_type_name` is checked by default then click the create 
8. Create a cluster flow and select the cluster output in step 3
9. Follow the same steps 3 - 8 to create output and flow , remember to select `cattle-logging-system` namespace
10. Open opensearch dashboard, create a index named `harvester` under Index Management -> Indices
11. Create a index pattern in Stack management -> Index patters, select index `harvester`
12. Go back to Harvester, edit the yaml of cluster output 
13. On opensearch dashboard, add a filter in Discover page and select `id` -> find `harvester` 
14. Switch to harvester filter to display the logs

**Comment by TachunLin** [comment]
But verified `failed` on the following scenario. Thus move to implement for further checking

* When we fill in all the necessary field of opensearch cluster output and output content, click the edit yaml to create or save, it will display error message to prevent saving chagnes 

`Output.logging.banzaicloud.io "output2" is invalid: [spec.logz.endpoint: Required value, spec.forward.servers[0].host: Required value, spec.kafka.brokers: Required value]`


 

https://user-images.githubusercontent.com/29251855/236792019-ebd6fb6a-a759-43db-bf1b-fbd249746d51.mp4




![image](https://user-images.githubusercontent.com/29251855/236777903-4572c552-b6cf-44b9-a99e-13910e3607a4.png)

**Comment by DaiYuzeng** [comment]
> But verified `failed` on the following scenario. Thus move to implement for further checking
> 
> * When we fill in all the necessary field of opensearch cluster output and output content, click the edit yaml to create or save, it will display error message to prevent saving chagnes
> 
> `Output.logging.banzaicloud.io "output2" is invalid: [spec.logz.endpoint: Required value, spec.forward.servers[0].host: Required value, spec.kafka.brokers: Required value]`
> 
>  vokoscreenNG-2023-05-08_17-43-06.mp4 
> ![image](https://user-images.githubusercontent.com/29251855/236777903-4572c552-b6cf-44b9-a99e-13910e3607a4.png)


I am going to confirm, thank you!

cc @WuJun2016

**Comment by DaiYuzeng** [comment]
Also reproduced at rancher v2.7.2, do you think we should fix it at harvester v1.2.0 or just file a new issue to track? @WuJun2016

![image](https://user-images.githubusercontent.com/15041915/237027279-f31c14c8-5ae2-4083-ba71-4d40e77dea80.png)

**Comment by DaiYuzeng** [comment]
Hi @TachunLin ! I'm afraid that `Cluster Output/ Output` can not be created via yaml now. This error also occured at rancher v2.7.2. This will happen regardless of which provider you choose. Can you please help me to file a new issue to track? And I am going to move this issue to `ready-for-testing`. If you have any concern please just let know, thanks! cc @WuJun2016

**Comment by WuJun2016** [comment]
> Hi @TachunLin ! I'm afraid that `Cluster Output/ Output` can not be created via yaml now. This error also occured at rancher v2.7.2. This will happen regardless of which provider you choose. Can you please help me to file a new issue to track? And I am going to move this issue to `ready-for-testing`. If you have any concern please just let know, thanks! cc @WuJun2016

We could create a new issue to track this problem, but I think we could put it in v1.2.1 to fix it.

**Comment by w13915984028** [comment]
@TachunLin A new ticket to track the UI yaml edit issue will be better, thanks.

**Comment by TachunLin** [comment]
File the new issue #3877 to track the behavior of creating cluster output and output from edit yaml

**Comment by TachunLin** [comment]
Verified **fixed** on master-2ba017d4-head (05/08). Close this issue.

### Result

- Verified can pass functionality test of the cluster output and output integration with opensearch service. 
- And pass the positive and negative test of the new attribute `suppress_type_name` 
https://github.com/harvester/harvester/issues/3589#issuecomment-1538060692


### Test Information
* Test Environment: single nodes on local kvm mahince
* Harvester version: master-2ba017d4-head (05/08)

### Verify Steps
https://github.com/harvester/harvester/issues/3589#issuecomment-1538060692
