### ISSUE TITLE
[Doc] Provide Information On Interactive ISO Install grub.cfg Location

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3590]
**Is your doc request related to a problem? Please describe or add related issue ID.**
There may be times where someone may be dropped into grub2 while the USB based ISO is hooked up.
Knowing what partition to set as root & where to located the grub.cfg from the iso would be useful for installation.

**Describe the solution you'd like**
Something that provides information of mentioning to have:
```
set root=(hdN,msdos1)
```
(Whereas, "N" denotes N number of possible drives, they'd have to determine which is their USB drive that is mounted)
And also mentioning where once `root` has been set on Grub2 where the grub.cfi is located.
I didn't manage to write down where I found it, but I believe it's located at something like:
```
chainloader /boot/grub2/something/x86_64-efi/something/grub.cfg
```
Then they'd be able to fire off the `boot` command from Grub2 and be taken to the interactive ISO installation.

**Comment by irishgordo** [comment]
`chainloader /boot/grub2/x86_64-efi/grub.efi`

**Comment by LucasSaintarbor** [comment]
@irishgordo is the following a good starting point for documenting this? Is there anything you want added or linked to? Could this be added to this page https://docs.harvesterhci.io/v1.1/install/usb-install? 

---
If you use a USB to mount the Harvester ISO disk, you may be directed to Grub2. In this case, it helps to know where to locate the `grub.cfg`, the root partition, and how to set a new root is helpful.

You can see the current root partition in the `crub.cfg`. To view the grub.cfg from the ISO, go to `chainloader /boot/grub2/x86_64-efi/grub.efi`.

To set a new root partition, run `set root = (hdN,msdos1)`, where `N` denotes N numbers of possible drives. `N` should be the drive your USB is mounted to.

**Comment by irishgordo** [comment]
I think that could be a good spot for the docs :smile: :+1:

**Comment by guangbochen** [comment]
Move this to v1.1.3 since the problem doesn't exist in Harvester v1.2.0; the doc PR is pending on https://github.com/harvester/docs/pull/298
