### ISSUE TITLE
[ENHANCEMENT] Get Image Repo/Tag Information from rancher-logging Addon CR

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3595]
**Is your enhancement related to a problem? Please describe.**

https://github.com/harvester/harvester/pull/3379#issuecomment-1455785614

We fall back to a hardcoded method for the image repo and tag info we need to construct the Logging resource for the upgrade log enhancement in #3379. The reason is, in the previous implementation, we retrieve that info from the `harvester-cluster-repo` Pod. But the info is wrong/outdated (the fluent-bit's tag is by default `1.9.3`). The actual tag is `1.9.5` because we specify it in the values section of the `rancher-logging` ManagedChart. Also, the image we bundled and shipped is in version `1.9.5`, too. In the end, we cannot treat the `harvester-cluster-repo` as a single source of truth for images we use in the cluster.

**Describe the solution you'd like**

We should reference the `rancher-logging` Addon for the newest image repo and tag information in the next version. If there is still missing, use the value from `harvester-cluster-repo`.

**Describe alternatives you've considered**

**Additional context**

Related issue: #1926
Previous PR: #3379

**Comment by irishgordo** [comment]
**_Testing Results:_**

_Harvester v1.2.0-rc3 -> v1.2-head Air-Gapped w/ Rancher Logging Disabled prior to upgrade:_  **PASS**
Validated:
- enabling of logging successful after upgrade
- upgrade log can be downloaded:
  - job.batch/hvst-upgrade-*-upgradelog-archive-timestamp, SuccessfulCreate & Completed
  - `image: rancher/harvester-upgrade:v1.2.0-rc3`
- once logs enabled, visibly see `kubectl logs services/rancher-logging -n cattle-logging-system --follow`
  - has: `rancher/mirrored-fluent-fluent-bit:1.9.5` image

_Artifacts:_
![Screenshot from 2023-07-12 15-02-51](https://github.com/harvester/harvester/assets/5370752/854d775b-5b40-4930-b7b0-64288672ed99)
![Screenshot from 2023-07-12 15-02-04](https://github.com/harvester/harvester/assets/5370752/3ec8c218-ea93-4cab-a7d6-059cbe25a3f8)
![Screenshot from 2023-07-12 14-58-49](https://github.com/harvester/harvester/assets/5370752/1d26b45a-30f0-4bee-8a01-70178ecc2161)
![Screenshot from 2023-07-12 12-00-32](https://github.com/harvester/harvester/assets/5370752/87b2a3bd-438b-4ff2-aafa-881a24632fde)
![Screenshot from 2023-07-12 11-59-33](https://github.com/harvester/harvester/assets/5370752/6952fd38-6d36-4ce4-81db-cf456908a793)
![Screenshot from 2023-07-12 11-59-14](https://github.com/harvester/harvester/assets/5370752/50836270-bd19-4b4c-a5dc-108767dd1407)
![Screenshot from 2023-07-12 11-58-45](https://github.com/harvester/harvester/assets/5370752/f61338c0-1965-4e6f-b20f-08e642de5796)
![Screenshot from 2023-07-12 11-56-46](https://github.com/harvester/harvester/assets/5370752/ea880818-53ef-43c3-bfef-363fd309fa0c)
![Screenshot from 2023-07-12 11-33-45](https://github.com/harvester/harvester/assets/5370752/5c6325e1-6b51-4226-ba70-43e5841ef05f)


_Harvester v1.2.0-rc3 -> v1.2-head Air-Gapped w/ Rancher Logging Enabled prior to upgrade:_ **PASS**
Validated:
- disabling of logging successful after upgrade
- upgrade log can be downloaded:
  - job.batch/hvst-upgrade-*-upgradelog-archive-timestamp, SuccessfulCreate & Completed
  - `image: rancher/harvester-upgrade:v1.2.0-rc3`
- when logs were enabled, visibly see `kubectl logs services/rancher-logging -n cattle-logging-system --follow`
  - has: `rancher/mirrored-fluent-fluent-bit:1.9.5` image

_Artifacts:_
![Screenshot from 2023-07-12 16-10-45](https://github.com/harvester/harvester/assets/5370752/a2d847a2-923a-4d79-98d2-c0ff14bc1da0)
![Screenshot from 2023-07-12 16-08-15](https://github.com/harvester/harvester/assets/5370752/f4c1dcf5-d4aa-49da-b6c7-ae538b4e8d08)
![Screenshot from 2023-07-12 16-07-07](https://github.com/harvester/harvester/assets/5370752/b874af53-87ec-4a35-88a4-3225255ef5c3)
![Screenshot from 2023-07-12 16-05-55](https://github.com/harvester/harvester/assets/5370752/271bca58-6117-4021-b380-5527364807ad)
![Screenshot from 2023-07-12 16-04-33](https://github.com/harvester/harvester/assets/5370752/123d08e0-a54e-47f4-9399-18b3341762ac)
![Screenshot from 2023-07-12 15-48-23](https://github.com/harvester/harvester/assets/5370752/0247dfc1-9c62-418d-b78d-ba697a0d2123)
![Screenshot from 2023-07-12 15-45-52](https://github.com/harvester/harvester/assets/5370752/1a787dc3-bbf8-4e11-a55f-5396f28ff278)

_Harvester v1.2.0-rc3 -> v1.2-head NON-Air-Gapped (using releases.rancher for iso) w/ Rancher Logging Disabled prior to upgrade:_  **PASS**
Validated:
- enabling of logging successful after upgrade
- upgrade log can be downloaded:
  - job.batch/hvst-upgrade-*-upgradelog-archive-timestamp, SuccessfulCreate & Completed
  - `image: rancher/harvester-upgrade:v1.2.0-rc3`
- once logs enabled, visibly see `kubectl logs services/rancher-logging -n cattle-logging-system --follow`
  - has: `rancher/mirrored-fluent-fluent-bit:1.9.5` image

_Artifacts:_
![Screenshot from 2023-07-12 17-05-40](https://github.com/harvester/harvester/assets/5370752/5890572a-5978-45b9-b298-da6e59db72e8)
![Screenshot from 2023-07-12 16-58-18](https://github.com/harvester/harvester/assets/5370752/a629a258-4dee-4cdf-8522-f873f069c8f2)
![Screenshot from 2023-07-12 16-57-04](https://github.com/harvester/harvester/assets/5370752/2ab5a7e0-b2a3-4ce3-a2e8-a5b93458c2dc)
![Screenshot from 2023-07-12 16-41-17](https://github.com/harvester/harvester/assets/5370752/5665b7df-2365-4480-98bb-6769fb80ba48)
![Screenshot from 2023-07-12 16-40-37](https://github.com/harvester/harvester/assets/5370752/c493e5aa-1457-4fea-8091-1c61fabd45e4)
![Screenshot from 2023-07-12 16-40-09](https://github.com/harvester/harvester/assets/5370752/31899da3-7f09-4454-9dff-0df2b7a555c3)
![Screenshot from 2023-07-12 16-39-49](https://github.com/harvester/harvester/assets/5370752/c442fcf4-baa6-4f71-a685-de8faa1e49cc)
![Screenshot from 2023-07-12 16-39-29](https://github.com/harvester/harvester/assets/5370752/145c412a-925a-494c-9db8-1f6f9023db96)
![Screenshot from 2023-07-12 16-39-05](https://github.com/harvester/harvester/assets/5370752/fe619d26-7387-47a4-8421-0087f6dfa481)

_Harvester v1.2.0-rc3 -> v1.2-head NON-Air-Gapped (using releases.rancher for iso) w/ Rancher Logging Enabled prior to upgrade:_  **PASS**
Validated:
- disabling of logging successful after upgrade
- upgrade log can be downloaded:
  - job.batch/hvst-upgrade-*-upgradelog-archive-timestamp, SuccessfulCreate & Completed
  - `image: rancher/harvester-upgrade:v1.2.0-rc3`
- when logs were enabled, visibly see `kubectl logs services/rancher-logging -n cattle-logging-system --follow`
  - has: `rancher/mirrored-fluent-fluent-bit:1.9.5` image

_Artifacts:_
![Screenshot from 2023-07-12 17-52-52](https://github.com/harvester/harvester/assets/5370752/abcd017e-4d41-474c-a074-a96db431cba1)
![Screenshot from 2023-07-12 17-50-33](https://github.com/harvester/harvester/assets/5370752/3717ecc6-3e0e-46ba-8064-78320ababf29)
![Screenshot from 2023-07-12 17-50-07](https://github.com/harvester/harvester/assets/5370752/9e7a1bf1-edd5-4ea9-a08a-8621be9cc024)
![Screenshot from 2023-07-12 17-05-40](https://github.com/harvester/harvester/assets/5370752/e6092710-d133-4719-98a3-c752ec769918)
![Screenshot from 2023-07-12 16-58-18](https://github.com/harvester/harvester/assets/5370752/541069f4-5c22-47b9-90d2-b6495c379c6f)
![Screenshot from 2023-07-12 16-57-04](https://github.com/harvester/harvester/assets/5370752/3cf8501c-0ad3-4fa6-ab6d-a9d2389e6eab)

@starbops  - the main tests seem good, I did note that it seems there might be a slight UI bug on the path of
Non-Airgapped, w/ rancher-logging addon enabled prior to upgrade, v1.2.0-rc3 -> v1.2-head 
w/ issue:
https://github.com/harvester/harvester/issues/4225
But I'm not sure how reproducible 4225 is.
Should I go ahead and close this out?

**Comment by irishgordo** [comment]
I think #4225 seems independent of this issue :smile:  - @starbops  - should I go ahead and close this out?

**Comment by starbops** [comment]
Hi @irishgordo, I think #4225 does not relate to this issue. Please go ahead. Thank you.

**Comment by irishgordo** [comment]
Sounds good @starbops  - thanks :smile: :+1:
