### ISSUE TITLE
[BUG] VMs with CD ROM Container or Container Disk Migrate When Node is in Maintenance Mode

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3600]
**Describe the bug**
A VM with a CD ROM Container or Container Disk live-migrates when its Host Node is put into Maintenance Mode

**Expected behavior**
That the VM would not Live-Migrate because of the constraints of:
- with 1 container disk & 1 container cd rom
- with 1 container cd rom
- with 1 container disk

**Environment**
 - Harvester ISO Version: v1.1-a72900af-head (03/01/23, v1.1-head)
 - Underlying Infrastructure: 3-Node Bare metal ThinkCentre Cluster
 
**Additional context**
![Screenshot from 2023-03-02 14-52-08](https://user-images.githubusercontent.com/5370752/223180512-64962d3c-94fe-4f99-b6d1-5b5e72328bd2.png)
![Screenshot from 2023-03-02 14-50-47](https://user-images.githubusercontent.com/5370752/223180519-9e8e821b-6372-481b-8ad2-52d31bb82b42.png)
![Screenshot from 2023-03-02 14-49-48](https://user-images.githubusercontent.com/5370752/223180525-eacd1620-d307-4c4e-8654-c1cf0d61a91d.png)

**Comment by irishgordo** [comment]
Also cross-ref: https://github.com/harvester/harvester/issues/3522

**Comment by w13915984028** [comment]
looks battling :)
the `maintenance mode` will forcely migrate all VMs automatically (?), and the #3522 will block user migration operation if those disks are attached to VM

cc @guangbochen @bk201 @ibrokethecloud

**Comment by ibrokethecloud** [comment]
Added an additional check to query VM's with cd-rom or container disk when putting node in maintenance mode

![image](https://github.com/harvester/harvester/assets/19664014/54b1d875-f3bc-4cf8-a0cd-84f66b592748)

**Comment by w13915984028** [comment]
As a further enhancement, we may consider to support eject CD automatically.

https://github.com/harvester/harvester/issues/3880

**Comment by irishgordo** [comment]
This works great :smile: :+1: !
Thanks for the fix @ibrokethecloud 
Tested on Harvester Version: master-a0aed9f2-head w/ bare-metal single node dell poweredge r720

![Screenshot from 2023-05-22 16-44-55](https://github.com/harvester/harvester/assets/5370752/2340d8a4-5ffb-49c6-a709-7ca44683c096)

**Comment by ibrokethecloud** [comment]
@Mergifio backport v1.1
