### ISSUE TITLE
[BUG] Failed to delete the existing VMs after upgrade, it stuck in Terminating state

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3605]
**Describe the bug**

After upgrade from v1.1.1 to v1.1.2-rc1, when we try to delete the existing VM before upgrade. 
We can't delete the VM, it stuck in terminating state
  ![image](https://user-images.githubusercontent.com/29251855/223362656-227b0e1c-6383-4c9a-8e29-9fb4a1f40415.png)
  
  
  ![image](https://user-images.githubusercontent.com/29251855/223360588-d0de22e9-8092-45d8-9eb9-da2cf2170d47.png)

The VM attached volume have already been deleted
  ![image](https://user-images.githubusercontent.com/29251855/223363206-6b8dafca-21a1-4c1f-83c7-f8f1ab3da821.png)

**To Reproduce**
1. Prepare a two nodes Harvester cluster with v1.1.1 release
2. Set up node and disk tags on each Node's host page
3. Create a new storage class the set as the default 
4. Prepare two virtual machines evenly on node1 and node2
5. Upgrade to v1.1.2-rc2
6. Wait until upgrade complete 
7. Update the config of the first VM, increase the memory and attach a new volume 
8. Delete the first existing VM
9. Delete the second existing VM

**Expected behavior**

Can delete both existing VMs (one of them already updated) correctly

**Support bundle**

[supportbundle_2df5f22c-bf4c-41ad-a11f-e72b673a480a_2023-03-07T08-24-26Z.zip](https://github.com/harvester/harvester/files/10907182/supportbundle_2df5f22c-bf4c-41ad-a11f-e72b673a480a_2023-03-07T08-24-26Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1 to v1.1.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 nodes bare machines

**Additional Context**
We can delete the newly created VM

**Comment by lanfon72** [comment]
The bug has been fixed after rc1, same as https://github.com/harvester/harvester/issues/3572
