### ISSUE TITLE
[BUG] Visual bug if the node has more than 1000 GB

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3607]
**Describe the bug**

When a node has more than 1TB of RAM there is a visual bug in UI. UI displays memory size correctly, but on nodes with >1TB od RAM the formatting is broken and info takes 2 lines.

**To Reproduce**
1. Go to the Host list page
2. Check the host memory size

**Expected behavior**

UI should display memory size correctly formatted even on nodes with a lot of memory.

**Support bundle**

**Environment**
 - Harvester ISO version: SUSE Harvester 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verifing **fixed** on `master-2ba017d4-head` (05/05). Close this issue.  

### Result
* When the nodes contains cpu, memory and disk size between 1000 GiB to 1023GiB ( four digits), the node resource column display layout should display correctly without wrapping to the newline 
![image](https://github.com/harvester/harvester/assets/29251855/fd14d85b-c4fb-4ba2-a437-5e8b1b7f7c6a)

* And on edge case, we can also set the the cpu, memory and disk size to extremely large digits (10 digits) , the node resource column display layout should display correctly without wrapping to the newline 
![image](https://github.com/harvester/harvester/assets/29251855/89283644-4dff-49f8-9475-0970e2ef89b5)


### Test Information
* Test Environment: single node harvester on local kvm machine
* Harvester version: `master-2ba017d4-head` (05/05) 

### Verify Steps
1. Use ipxe-example to provision Harvester cluster 
2. edit settings.yml
3. Set cluster.disk_size to `1145G` 
4. Check the host page after Harvester cluster provisioning ready
5. Use developer tool to change the value of Reserved and Used CPU, Memory and Storage size 
6. Check the host page for the layout
