### ISSUE TITLE
[BUG] Same version upgrade with the ISO image downloaded from releases.rancher.com will fail

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3610]
**Describe the bug**

When upgrading with the same ISO image used to provision the cluster and downloaded from `https://releases.rancher.com/harvester/master/harvester-master-amd64.iso`, the upgrade will fail at the very beginning of the image-preloading phase.

<img width="578" alt="Screen Shot 2023-03-07 at 23 42 00" src="https://user-images.githubusercontent.com/1827717/223472421-aba23cba-8a88-41d8-aed3-72d3909f8714.png">

The image-preloading Pod is in a `ErrImagePull` state:

```
$ kubectl -n cattle-system get pods
NAME                                                              READY   STATUS         RESTARTS   AGE
apply-hvst-upgrade-zhlsj-prepare-on-node-0-with-b4e7c390a-l5xkq   0/1     ErrImagePull   0          11s
harvester-cluster-repo-b96bd7cd5-58hj2                            1/1     Running        0          6h29m
rancher-6d8c977495-2hq9k                                          1/1     Running        0          6h26m
rancher-webhook-54797bf8cb-hzkdq                                  1/1     Running        0          6h29m
system-upgrade-controller-79fc9c84b7-mmwfx                        1/1     Running        0          6h29m
```

The required image tag of the image-preload Pod is `master-ce5aff93-head`:

```
$ kubectl -n cattle-system get po apply-hvst-upgrade-zhlsj-prepare-on-node-0-with-b4e7c390a-l5xkq -o yaml
...
    image: rancher/harvester-upgrade:master-ce5aff93-head
...
```

However, the image `rancher/harvester-upgrade:master-ce5aff93-head` does not even exist on the node. Not to mention the image was never published to the public. There's no place for the kubelet to pull that image, therefore the entire upgrade procedure is going to end here inevitably.

```
$ ctr -n k8s.io i ls | grep harvester-upgrade
docker.io/rancher/harvester-upgrade:ce5aff93                                      application/vnd.docker.distribution.manifest.v2+json sha256:9226ea2373e57eb25c82fbeb8f7c4d182b26d3bff52b046b59ade387607f3da2 396.8 MiB linux/amd64 io.cri-containerd.image=ma
naged
docker.io/rancher/harvester-upgrade:master-head                                   application/vnd.docker.distribution.manifest.v2+json sha256:9226ea2373e57eb25c82fbeb8f7c4d182b26d3bff52b046b59ade387607f3da2 396.8 MiB linux/amd64 io.cri-containerd.image=ma
naged
```

To work around this, just retag the image:

```
ctr -n k8s.io i tag docker.io/rancher/harvester-upgrade:master-head docker.io/rancher/harvester-upgrade:master-ce5aff93-head
```

**To Reproduce**
1. Grab an ISO image from `https://releases.rancher.com/harvester/master/harvester-master-amd64.iso` and provision a Harvester cluster (single-node is fine)
2. Upgrade the cluster with the very same ISO image
3. The upgrade should fail at the image-preloading phase

**Expected behavior**

Upgrade to the same version, especially with the master-head image downloaded from `https://releases.rancher.com/harvester/master/harvester-master-amd64.iso`, should succeed.

**Support bundle**

**Environment**
 - Harvester ISO version: master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

cc @bk201 @TachunLin

**Comment by TachunLin** [comment]
Verified **fixed** on `master-9f440f9f-head` (03/09) . Close this issue.

### Result
Verified five times, we can sucessfully upgrade from the master-head to the same master-head in `Running` state
Did not encounter stuck in the pre-load image stage with exceed deadline error

  ![image](https://user-images.githubusercontent.com/29251855/224251019-cf4673c2-fa82-412b-a714-549ba8f2f150.png)

### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-9f440f9f-head` (03/09) 

### Verify Steps
1. Prepare a master-head release Harvester 
2. Upgrade from v1.1.2 master-head to the same master-head
  ![image](https://user-images.githubusercontent.com/29251855/224249562-572faa8e-1feb-477f-a796-2f1af211928a.png)

3. Check the upgrade state
