### ISSUE TITLE
Enable Nested Virtualization

### ISSUE THREAD

**Issue by Sepiidae** [harvester/harvester#3617]
Several of our users quested the ability to run WSL in Windows VM's, and Rancher Desktop on Linux VM;s. Is there a way to enable nested virtualization in Harvester?

**Comment by Vicente-Cheng** [comment]
Hi @Sepiidae, is your scenario using Rancher Desktop and creating a harvester cluster with WSL?
If yes, did you find any problems with this configuration?

I did not check this case about the windows VM + WSL. Could you share more detail about your configuration and any issues?
Thanks!

**Comment by Sepiidae** [comment]
> Hi @Sepiidae, is your scenario using Rancher Desktop and creating a harvester cluster with WSL? If yes, did you find any problems with this configuration?
> 
> I did not check this case about the windows VM + WSL. Could you share more detail about your configuration and any issues? Thanks!

Have a harvester cluster on bare metal. We want to install Windows 10/11 machines on this cluster and have them be able to run WSL.

To this point we have been unsuccessful as we need nested virtualization enabled on the kubevirt host.

**Comment by masteryyh** [comment]
@Sepiidae if you can't use WSL or other nested virtualization in Harvester, you can try out this command to check if you have enabled KVM nested virtualization:
```
ls -l /sys/module/kvm_intel/parameters/nested
```
If this parameter exists that means KVM nested virtualization has been enabled and there should be no issue with WSL
If not you can try to enable it by executing the command below per node and reboot:
```
# yq -i e '.stages.network[0].commands[0] = "modprobe kvm_intel nested=1"' /oem/99_custom.yaml
```
(if `/oem/99_custom.yaml` not exists you can try `/oem/90_custom.yaml`)
cc @Vicente-Cheng @futuretea

**Comment by Sepiidae** [comment]
Just commenting that nested virtualization is enabled in on our nodes. I am retesting WSL on a new vm.

**Comment by zanewgray** [comment]
Just tried this on Harvester v1.2 with a fresh Windows 11 install (loving the virtual TPM!).  WSL2 installed without issue.  However, after reboot, the Windows 11 VM appears to hang at the TianoCore BIOS splash screen.  After a few forced reboots, Windows 11 kicked off the "Automatic Repair" process, which failed.

During boot, I managed to catch this error:

![image](https://github.com/harvester/harvester/assets/16705219/9b7eb824-3230-4cb8-b651-0b22c9a20557)

I am interested to see if anyone else managed to get this (nested virtualization - specifically WSL2 on a Windows VM on Harvester) working.

**Comment by r19rcv20** [comment]
Has there been a resolution to @zanewgray issue? I have ran into the same problem. The is after I have enabled virtualization in the Windows 11 VM

**Comment by krumware** [comment]
@nunix, maybe a good one for your input?

**Comment by krumware** [comment]
@r19rcv20 do you remember which harvester version you have tested on? are you still having the issue?
