### ISSUE TITLE
[BUG] external ui-source breaks v1.1.1 Harvester

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3618]
**Describe the bug**

When you select external ui-source for Harvester `v1.1.1` it breaks the UI
**To Reproduce**
1. Deploy `v1.1.1` harvester
2. set ui-source to external
3. refresh page
**Expected behavior**

UI should come back up on refresh
**Support bundle**

There's not really asupport bundle since it's a UI issue and if you trigger it then you can't load the UI.

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single node virtualized libvirt

**Additional context**
`v1.1.1` harvester is pointing at `v1.1-head` assets instead of a pinned `v1.1.1` version. This means that if you select the external `ui-source` it breaks the ui.

![Greenshot 2023-03-08 13 17 38](https://user-images.githubusercontent.com/83787952/223856480-5eddd238-50e3-4f34-9abb-7f2396a12c84.png)
![Greenshot 2023-03-08 13 17 46](https://user-images.githubusercontent.com/83787952/223856482-108ebd3a-2091-4715-9901-efa696baf7be.png)

**Comment by noahgildersleeve** [comment]
This seems to be happening in `v1.1-head` as well. So we need to fix that, but also we should probably be pointing to a separate `v1.1.1` set of assets on `v1.1.1`

**Comment by n313893254** [comment]
Hi, @noahgildersleeve. Sorry for I can not reproducing this issue. Could you provide a video to let me investigate further? 

> we should probably be pointing to a separate `v1.1.1` set of assets on `v1.1.1`

For the external UI, we want the user to have access to the latest UI, so the default value of ui-index points to the latest UI.
If the user wants to use the version-specific UI, he can select the `bundle` option.

**Comment by noahgildersleeve** [comment]
I think this might have been resolved with some of the RC3 fixes. I'll test and verify.

**Comment by noahgildersleeve** [comment]
Tested in v1.1.1 and it seems to be working now. Closing as fixed.
