### ISSUE TITLE
[FEATURE] add physical nic dropdown box

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#362]
**Describe the solution you'd like**

- Add physical NIC dropdown box when selecting physical NIC for bridge network
- Add hint for the physical NIC which used by management network
- Add suggestion that prefer to use physical NIC that has not been use by management network

![image](https://user-images.githubusercontent.com/7421463/102355351-b2d0fa00-3fe6-11eb-86e6-170f99a823d6.png)

**Comment by TangStone** [comment]
Validated https://github.com/rancher/harvester/issues/369#issuecomment-805692471
