### ISSUE TITLE
[BUG] Inconsistent versions and image tags with ISO images

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3621]
**Describe the bug**

There exists an inconsistency between the ISO images built within the `harvester` and `harvester-installer` repo. The reason is we use `git rev-parse --short HEAD` without specifying the minimum length of characters to construct the version strings and image tags. The built artifacts will have different ones depending on the arguments used while cloning the repo. For example:

```
$ git clone --single-branch --depth=1 https://github.com/harvester/harvester.git harvester-single
Cloning into 'harvester-single'...
remote: Enumerating objects: 11666, done.
remote: Counting objects: 100% (11666/11666), done.
remote: Compressing objects: 100% (8183/8183), done.
remote: Total 11666 (delta 3347), reused 8079 (delta 2680), pack-reused 0
Receiving objects: 100% (11666/11666), 23.06 MiB | 9.98 MiB/s, done.
Resolving deltas: 100% (3347/3347), done.
Updating files: 100% (9579/9579), done.

$ cd harvester
$ git rev-parse --short HEAD
152642c
```

The length of the commit hash is different from the following, which is 8 digits:

```
$ git clone https://github.com/harvester/harvester.git harvester-full
Cloning into 'harvester-full'...
remote: Enumerating objects: 42075, done.
remote: Counting objects: 100% (406/406), done.
remote: Compressing objects: 100% (315/315), done.
remote: Total 42075 (delta 127), reused 279 (delta 65), pack-reused 41669
Receiving objects: 100% (42075/42075), 48.45 MiB | 9.55 MiB/s, done.
Resolving deltas: 100% (22274/22274), done.
Updating files: 100% (9579/9579), done.

$ cd harvester-full
$ git rev-parse --short HEAD
152642c2
```

Therefore the container images packaged by Drone CI will have a mismatched tag:

```
rancher/harvester-upgrade:master-152642c-head   # the one got packaged into the ISO and preloaded on the system
rancher/harvester-upgrade:master-152642c2-head  # the one needed when doing upgrades which does not exist on the system
```

This will cause issues when doing upgrades since the upgrade controller uses the 8-character constructed `server-version` as the `previousVersion` and spawns Jobs according to that version string. Thus getting an `ErrPullImage` error.

**To Reproduce**
1. Clone the `harvester` repo with `git clone --single-branch --depth=1 https://github.com/harvester/harvester.git`
2. Build the ISO image with `make && make build-iso`
3. Either use `isoinfo` or mount the ISO image directly to check the harvester-upgrade's image tag:

```
$ isoinfo -J -i dist/artifacts/harvester-master-amd64.iso -x /bundle/harvester/images-lists/harvester-extra-master.txt
docker.io/rancher/harvester-upgrade:152642c
docker.io/rancher/harvester-upgrade:master-152642c-head
```

The commit hash may vary but should be only 7 characters long by now.

**Expected behavior**

The generated `server-version` should match the tag of the built and packaged container images.

**Support bundle**

**Environment**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Related thread: https://github.com/harvester/harvester-installer/pull/447#issuecomment-1460212586

**Comment by TachunLin** [comment]
Verified **fixed** on `master-41b46ac3-head` (03/13). Close this issue.

### Result
* Check the harvester-upgrade image tag of master-head ISO, it contains 5 digit commit hash

  ```
  davidtclin@localhost:~/Documents/Harvester/Daily_Build/230313> isoinfo -J -i harvester-master-amd64.iso -x /bundle/harvester/images-lists/harvester-extra-master.txt
  Setting input-charset to 'UTF-8' from locale.
  docker.io/rancher/harvester-upgrade:41b46ac3
  docker.io/rancher/harvester-upgrade:master-41b46ac3-head
  ```

* And we can upgrade to the same master-head version correctly without error
![image](https://user-images.githubusercontent.com/29251855/224967407-d4e90c65-e209-4cde-ace4-b95317fe07fa.png)

### Test Information
* Test Environment: 1 node1 Harvester local kvm machine
* Harvester version: `master-41b46ac3-head` (03/13)

### Verify Steps
1. Get master ISO
2. Execute command
  ```
  isoinfo -J -i dist/artifacts/harvester-master-amd64.iso -x /bundle/harvester/images-lists/harvester-extra-master.txt
  ```
3. The listed tags should consist of an 8-char commit hash
4. Provision a single node Harvester
5. Upgrade to the same version
