### ISSUE TITLE
[BUG] After creating a VM, we can see duplicate VM records on Virtual Machine page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3624]
**Describe the bug**

When we create a VM, the Virtual machines page display duplicate VM records
![image](https://user-images.githubusercontent.com/29251855/223971884-cd0b2ffb-31c7-464d-840b-60f92facacc2.png)

After we refresh the page, the duplicate VM record will disapper
![image](https://user-images.githubusercontent.com/29251855/223972297-58d95743-6aa2-474b-90fa-789faff83afb.png)

**To Reproduce**
1. Provision a two nodes Harvester cluster 
2. Create a cluster network 
3. Create a vlanconfig
4. Create a valid VM network `vlan101`
5. Create a virtual machine and set network to `vlan101`
6. Check the Virtual Machines page

**Expected behavior**

Should display only one VM record on Virtual Machine page

**Support bundle**

[supportbundle_91d087e6-38ef-47a8-a7cf-5231eff6cedc_2023-03-09T09-04-21Z.zip](https://github.com/harvester/harvester/files/10929688/supportbundle_91d087e6-38ef-47a8-a7cf-5231eff6cedc_2023-03-09T09-04-21Z.zip)

**Environment**
 - Harvester ISO version: `v1.1-0fe9676b-head` (03/08)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 nodes Harvester on local kvm machine

**Comment by WuJun2016** [comment]
duplicate :  https://github.com/harvester/harvester/issues/1111 ,  close this issue.
This is a known problem, but there are no stable recurrence steps.
