### ISSUE TITLE
[BUG] Can't create a VM network

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3629]
**Describe the bug**

When you try to create a VM network it gives you a webhook validation CIDR error on submission
**To Reproduce**
1. Create a new VM network on the management cluster network with VLAN 1

**Expected behavior**

You should be able to create a VM network
**Support bundle**

[supportbundle_ad71cfdd-bf67-4625-b50d-ed274226f8a8_2023-03-09T20-33-12Z.zip](https://github.com/harvester/harvester/files/10935870/supportbundle_ad71cfdd-bf67-4625-b50d-ed274226f8a8_2023-03-09T20-33-12Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node ipxe-examples libvirt VMs

**Additional context**
This happens on local ui-source as well as remote. Also it happens on the management cluster network as well as on a separate one that I created. This is the payload of the submission to the webhook.
```
{
    "type": "k8s.cni.cncf.io.networkattachmentdefinition",
    "metadata": {
        "namespace": "default",
        "annotations": {
            "network.harvesterhci.io/route": "{\"mode\":\"auto\",\"serverIPAddr\":\"\",\"cidr\":\"\",\"gateway\":\"\"}"
        },
        "name": "ext"
    },
    "spec": {
        "config": "{\"cniVersion\":\"0.3.1\",\"name\":\"ext\",\"type\":\"bridge\",\"bridge\":\"ext-br\",\"promiscMode\":true,\"vlan\":1,\"ipam\":{}}"
    }
}
```
There's also a typo in the error message

![Screenshot_20230309_123257](https://user-images.githubusercontent.com/83787952/224151994-96d86810-49be-4bfd-9c3d-36d03edb9f3d.png)
![Screenshot_20230309_123251](https://user-images.githubusercontent.com/83787952/224152073-b6a25c0b-fa4c-45a2-ad9b-5579e701b92b.png)
![Screenshot_20230309_123217](https://user-images.githubusercontent.com/83787952/224152074-a9135478-2fc0-4a6c-bf75-1182b5a08e80.png)

**Comment by guangbochen** [comment]
seems `CIDR != ""` or `networkConf.Mode == Manual` check is still needed in https://github.com/harvester/network-controller-harvester/blob/master/pkg/utils/nad.go#L61, @yaocw2020 can u please help to fix it. cc @bk201 we may re-tag the Harvester `v1.1.2-rc2` for this if needed, thanks.

**Comment by guangbochen** [comment]
the proper workaround is via editing the NAD yaml by removing its `cidr` field.
```
            "network.harvesterhci.io/route": "{\"mode\":\"auto\",\"serverIPAddr\":\"\",\"gateway\":\"\"}"

```

**Comment by noahgildersleeve** [comment]
Tested in v1.1.2-rc3. Verified that networking was working in
- VM network created on mgmt cluster network with VLAN ID 1
- cluster network created and then VM network created on cluster network with VLAN ID 1
