### ISSUE TITLE
[BUG] Edit YAML of VM w/ PCI Passthrough Devices Shows Same Device(s) Multiple Times

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3631]
**Describe the bug**
Duplicate entries exist for the PCI Passthrough devices when the PCI Passthrough devices are enabled / attached to the VM.

**To Reproduce**
1. Enable PCI Devices
1. Bring in PCI Devices for VM
1. Boot VM
1. Edit YAML of VM, multiple entries of same PCI Device exist in YAML of VM

**Expected behavior**
Duplicate entries not existing for PCI Passthrough on edit YAML of vm

**Environment**
 - Harvester ISO version: v1.1-head
 - Underlying Infrastructure: R720

**Additional context**
-  duplicate records when all pcidevices for an iommu group are added
![Screenshot from 2023-03-09 16-20-54](https://user-images.githubusercontent.com/5370752/224199151-97cb5969-a4c5-4413-b227-383e456d58f4.png)

**Comment by DaiYuzeng** [comment]
Hi @irishgordo ! May I know how many PCI devices you actually added into VM?

Hi @ibrokethecloud ! It seems like `iommu group` affect? I can't conclude, could you double check this issue? 
And I realized the filed `name` seems to be duplicated?

**Comment by irishgordo** [comment]
Hi @DaiYuzeng  - this seems to be addressed already (as I'm unable to reproduce) with the loadout adjustments of:
Utilizing the new:
```
gmehta3/pcidevices:dev
Digest:sha256:e86f89562a997dd54677eee9e945a1cadefa8cfa103267edf01d380ede39c9a5
```
( https://hub.docker.com/layers/gmehta3/pcidevices/dev/images/sha256-e86f89562a997dd54677eee9e945a1cadefa8cfa103267edf01d380ede39c9a5?context=explore )
perhaps containing: https://github.com/harvester/pcidevices/compare/master...ibrokethecloud:pcidevices:missing_new_id 
Also perhaps related to: https://github.com/harvester/pcidevices/pull/51
For replacing:
```
rancher/harvester-pcidevices:v0.2.4-rc2
```
( in `kubectl -n harvester-system edit ds harvester-pcidevices-controller` )
And updating image pull policy to `Always`.

![Screenshot from 2023-03-10 10-58-11](https://user-images.githubusercontent.com/5370752/224404105-3dd2628c-999b-47de-9774-4b79112c9b42.png)
![Screenshot from 2023-03-10 10-49-34](https://user-images.githubusercontent.com/5370752/224404110-324e7495-4072-422e-aba2-1a59847edee1.png)
![Screenshot from 2023-03-10 10-27-51](https://user-images.githubusercontent.com/5370752/224404112-b3bd989f-c5ed-4074-b727-8d71b8d73881.png)

I would like to retest this when everything is on v1.1-head :smile: - after that I could then go ahead and close this out.
cc:
@ibrokethecloud @tlehman

**Comment by tlehman** [comment]
Assigning this to myself, even if it's ultimately a UI issue, we can guard against it easily on the backend

**Comment by irishgordo** [comment]
Closing this out as on  Version: v1.1-e1905897-head  - I'm not seeing this as an issue :smile: :+1: 
![Screenshot from 2023-03-14 16-06-44](https://user-images.githubusercontent.com/5370752/225161797-3a35567f-f721-4032-aadc-d5d783dc74a6.png)

Seems to be fixed by:
https://github.com/harvester/pcidevices/pull/51
