### ISSUE TITLE
[BUG] Cannot upgrade from v1.1.0 to v1.1.2-rc2

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3633]
**Describe the bug**

Upgrading from v1.1.0 to v1.1.2-rc2 fails as the image preloading Pods keep erroring. After exceeding the max retry limit, the Job becomes failed.

<img width="576" alt="image" src="https://user-images.githubusercontent.com/1827717/224219634-0bde72d0-47a7-4fb8-b6d2-41d82a307a26.png">

From the log of the image preloading Pod:

```
++ yq e .status.previousVersion -
+ UPGRADE_PREVIOUS_VERSION=v1.1.0
+ check_version
Current version: 1.1.0
Minimum upgradable version: 1.1.0-0
+ CURRENT_VERSION=1.1.0
+ MIN_UPGRADABLE_VERSION=1.1.0-0
+ echo 'Current version: 1.1.0'
+ echo 'Minimum upgradable version: 1.1.0-0'
+ '[' -z 1.1.0-0 ']'
+ VERSIONS_TO_COMPARE='1.1.0-0
1.1.0'
++ sort -V
Current version is not supported. Abort the upgrade.
+ '[' '1.1.0-0
1.1.0' = '1.1.0
1.1.0-0' ']'
+ echo 'Current version is not supported. Abort the upgrade.'
+ exit 1
```

It is the minimum-upgradable-version check and the newly introduced suffix that prevent us from upgrading.

**To Reproduce**
1. Provision a v1.1.0 cluster
2. Upgrade to v1.1.2-rc2
3. The upgrade will fail at the early stage of image preloading

**Expected behavior**

The upgrade from v1.1.0 to v1.1.2-rc2 should succeed. In general, upgrading to an RC version from a supported version should not be blocked.

**Support bundle**

[supportbundle_164b8415-82b5-4452-b85c-5a2c1cd9766b_2023-03-10T04-04-34Z.zip](https://github.com/harvester/harvester/files/10938380/supportbundle_164b8415-82b5-4452-b85c-5a2c1cd9766b_2023-03-10T04-04-34Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0 upgrades to v1.1.2-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Related issue: #3040

Upgrading from v1.1.1 to v1.1.2-rc2 is fine.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1.0** upgrade to **v1.1.2-rc3**
* **ui-source** Option: **Auto**

### Verify Steps:
- Follow **Step to Reproduce** in https://github.com/harvester/harvester/issues/3633#issue-1618327193
- Cluster should be upgraded successfully
