### ISSUE TITLE
[BUG] Rancher v2.6.11 w/ RKE1 Kubernetes Version: v1.23.16 -Fails Install Harvester Cloud-Provider

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3637]
**Describe the bug**
Rancher v2.6.11 that has a Harvester v1.1.2-rc3 cluster imported.
Fails to install the harvester-cloud-provider chart in RKE1 v1.23.16 3 node cluster.

**To Reproduce**
1. Import Harvester into Rancher v2.6.11
1. Create RKE1 v1.23.16 Cluster
1. Attempt to install Harvester Cloud-Provider

**Expected behavior**
That Harvester Cloud Provider would install and not timeout.

**Attempted Workarounds**
- Attempted to change the Server Version on Harvester Cluster from v1.1.2-rc3 to v1.1.2 - then re-attempt to install harvester-cloud-provider, but with no success

**Environment**
 - Harvester ISO version: v1.1.2-rc3
 - Rancher: v2.6.11
 - RKE1: v1.23.16
 - Underlying Infrastructure: bare-metal 

**Additional context**
![Screenshot from 2023-03-12 17-46-04](https://user-images.githubusercontent.com/5370752/224585229-fae5bae6-6868-4cca-9039-a7d885a89dba.png)
![Screenshot from 2023-03-12 17-44-44](https://user-images.githubusercontent.com/5370752/224585230-b7f85068-4742-494b-abb3-cb7bf9bcbc11.png)
![Screenshot from 2023-03-12 17-32-44](https://user-images.githubusercontent.com/5370752/224585231-0790ee05-5dea-47c4-9e20-af7290b66ab9.png)

**Comment by irishgordo** [comment]
Harvester-CSI-Driver also failing:
![Screenshot from 2023-03-12 18-22-33](https://user-images.githubusercontent.com/5370752/224587654-bee47032-ddb0-459c-b050-9fd21bc566f9.png)

**Comment by yaocw2020** [comment]
```
...
spec:
  ...
  rancherKubernetesEngineConfig:
    addonJobTimeout: 45
    authentication:
      strategy: x509|webhook
    authorization: {}
    bastionHost: {}
    cloudProvider: {}
    ...
```
By checking the RKE cluster YAML, we found the cloud provider is empty. 
If we want to use the Harvester cloud provider, we have to select Harvester(out-of-tree) when creating RKE. Refer to 
https://docs.harvesterhci.io/dev/rancher/cloud-provider#deploying-to-the-rke1-cluster-with-harvester-node-driver
![image](https://user-images.githubusercontent.com/7421463/224684129-2fe1d354-369b-4ada-ab7c-a27e94f8f866.png)

**Comment by irishgordo** [comment]
@yaocw2020 thank you for looking into this - I will go ahead and close this out :smile: :+1:
