### ISSUE TITLE
[BUG] 3 Node AirGap Harvester w/ AirGap Rancher v2.6.9 Fails v1.1.1 -> v1.1.2-rc3 Upgrade

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3648]
**Describe the bug**
3 node airgap harvester cluster w/ Rancher v2.6.9 fails upgrade 

**To Reproduce**
1. Create airgap 3 node Harvester 1 rancher node
1. Have file server on Rancher node
1. create version.yaml, process upgrade

**Expected behavior**
Node not to be stuck in `pre-drained` state

**Environment**
 - Harvester ISO version: v1.1.1 -> v1.1.2-rc3
 - Underlying Infrastructure: qemu/kvm
 
**Additional context**
![Screenshot from 2023-03-08 18-22-00](https://user-images.githubusercontent.com/5370752/225095030-5db4de56-14cc-4798-b1e6-8b4312f388e4.png)

**Comment by TachunLin** [comment]
In the latest trial on 3 nodes fully airgapped upgrade from v1.1.1 to v1.1-head

The upgrade process stuck in `Pre-drained` state of the first node
![image](https://user-images.githubusercontent.com/29251855/225567775-c74dc1f1-b3c5-4cf3-b8b1-3d9619e4cd19.png)


* Attach the support bundle for the reference.
[supportbundle_cf38f094-f41b-41c6-8727-822b498a7fb1_2023-03-16T08-38-38Z.zip](https://github.com/harvester/harvester/files/10988755/supportbundle_cf38f094-f41b-41c6-8727-822b498a7fb1_2023-03-16T08-38-38Z.zip)

**Comment by irishgordo** [comment]
The latest trial on 3 nodes fully airgapped no proxy with the loadout of:
Rancher-v2.6.11
Harvester-v1.1.1 -> with upgrade to -> v1.1.2-rc3
Failed in the same state

![Screenshot from 2023-03-16 09-26-16](https://user-images.githubusercontent.com/5370752/225691885-7a02b9b4-5e28-4eed-8927-d59b0d20ca12.png)
![Screenshot from 2023-03-16 09-24-47](https://user-images.githubusercontent.com/5370752/225691888-40714cf5-7b3e-4613-83fe-c7998b899eb2.png)
![Screenshot from 2023-03-15 18-02-13](https://user-images.githubusercontent.com/5370752/225691889-dc17138a-7f9f-4e41-adf8-cbf9ef56e3e3.png)
![Screenshot from 2023-03-15 18-01-47](https://user-images.githubusercontent.com/5370752/225691892-434b9a9c-86c5-4bf4-bf80-f522c67836d2.png)

[support_bundle_failed_predrain_first_node_for_rancher_v2611_w_harvester_v111_to_v112-rc3.zip](https://github.com/harvester/harvester/files/10993461/support_bundle_failed_predrain_first_node_for_rancher_v2611_w_harvester_v111_to_v112-rc3.zip)

**Comment by bk201** [comment]
To reproduce:
- Create some VMs.
- Shutdown VMs.
- Create backups on VMs.
- Start upgrade.
- The draining process could be stuck because backing up a shutdown VM attaches its volume to a node.

**Comment by irishgordo** [comment]
![Screenshot from 2023-03-27 14-13-13](https://user-images.githubusercontent.com/5370752/228079856-74a60f6c-9b95-4bda-9fdc-6456eea6cec6.png)

Closing this out as this looks good from v1.1.1 -> v1.1.2-rc4 w/ volume-snapshots, vm-backups and vm-snapshots w/ restores/replaces etc.

Thanks for the fix @FrankYang0529 :+1: :smile:
