### ISSUE TITLE
[BUG] Cannot Import AirGapped Harvester 3 Node Cluster Into AirGapped Rancher v2.6.11

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3649]
**Describe the bug**
Having a running AirGapped Rancher Instance v2.6.11, cannot import v1.1.1 3 Node Harvester AirGapped cluster.

**To Reproduce**
1. In Rancher v2.6.11 create Virtualization Import for Harvester
1. Paste link in Cluster Registration URL for Harvester VIP

**Expected behavior**
Status of Import to not hang at "Pending"

**Support bundle**

[supportbundle_9e07aaf9-d1e5-4793-92a1-5e9710c5a7a7_2023-03-14T18-02-29Z.zip](https://github.com/harvester/harvester/files/10972236/supportbundle_9e07aaf9-d1e5-4793-92a1-5e9710c5a7a7_2023-03-14T18-02-29Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure: qemu/kvm
 - Rancher: v2.6.11

**Additional context**
- On Harvester Nodes:
    - configmap/rke2-coredns-rke2-coredns has been created and patched in deployment/rke2-coredns-rke2-coredns
- On Rancher Node:
    - configmap/coredns & deployment/coredns leveraged
![Screenshot from 2023-03-14 11-08-18](https://user-images.githubusercontent.com/5370752/225098231-3fece6f2-2be7-4983-91c8-7f2cf49a135e.png)

**Comment by khushboo-rancher** [comment]
@TachunLin helped in trying to check this in his airgap setup and didn't encounter the issue.

@TachunLin Could you please share the details of your set up and result. Thanks for the help.

**Comment by irishgordo** [comment]
That would be great to see :smile: :+1: 

As in the other loadout...
It looks like for some reason the image is present but doesn't show in the catalog?
Opened -> https://github.com/harvester/tests/issues/747

Then we could close this out, as I believe it's related to something with the docker-registry.

**Comment by irishgordo** [comment]
Actually the image is 100% there.
![Screenshot from 2023-03-15 15-36-20](https://user-images.githubusercontent.com/5370752/225458907-cc7f8aff-9bdc-41c3-9c27-05aeff73ff7a.png)
![Screenshot from 2023-03-15 15-35-32](https://user-images.githubusercontent.com/5370752/225458910-4dafcc49-f8db-4483-a5e3-7c4624f3e0b2.png)

:thinking:

**Comment by irishgordo** [comment]
![Screenshot from 2023-03-15 16-05-47](https://user-images.githubusercontent.com/5370752/225463147-28b2bc17-a08d-4aeb-ba49-1f94142bde7c.png)
![Screenshot from 2023-03-15 16-04-59](https://user-images.githubusercontent.com/5370752/225463153-41249e11-368c-4bcd-8fab-3bb3e0f7c40e.png)


I can import it, entirely airgapped.
The problem is the cert is 'self-signed' ....

**Comment by TachunLin** [comment]
Try to implement an airgapped environment with proxy support for Harvester and Rancher instance in the following manner:

We can import Harvester v1.1.1 to Rancher v2.6.11 with proxy setting on each side. 

1. Use ipex-example, set `offline: true` in the settings.yaml 
2. Provision an airgapped Harvester cluster 
3. Prepare another VM for the Rancher instance
4. Set the VM using the same internal virtual network same with ipxe-example (Harvester)
5. Pull image of Rancher v2.6.11 on the new VM
6. Cut the outbound network of the new VM
7. Create the Rancher v2.6.11 instance with the proxy setting 
  ```
  docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e HTTP_PROXY="http://192.168.0.254:3128" -e HTTPS_PROXY="http://192.168.0.254:3128" -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.0.0/16,.svc,.cluster.local,example.com" --privileged rancher/rancher:v2.6.11
     44  sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 -e HTTP_PROXY="http://192.168.0.254:3128" -e HTTPS_PROXY="http://192.168.0.254:3128" -e NO_PROXY="localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,cattle-system.svc,192.168.0.0/16,.svc,.cluster.local,example.com" --privileged rancher/rancher:v2.6.11
  ```
8. Open Harvester settings 
9. Add proxy in settings
  ```
  {
    "httpProxy": "http://192.168.0.254:3128",
    "httpsProxy": "http://192.168.0.254:3128",
    "noProxy": "localhost,127.0.0.1,0.0.0.0,10.0.0.0/8,192.168.0.0/16,cattle-system.svc,.svc,.cluster.local,<internal domain>"
  }
  ```
10. Import Harvester in Rancher 


* Attach the small clip for the reference

https://user-images.githubusercontent.com/29251855/225532746-463e6e72-36c2-4f0a-a0e2-6df0a4f40183.mp4
