### ISSUE TITLE
[ENHANCEMENT] Improve the user experience of downloading the upgrade log archive

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3655]
**Is your enhancement related to a problem? Please describe.**

By clicking the "Download Log" button, users can get an archive file containing the logs collected during an upgrade. If there is something wrong in the backend, especially if the log packager fails to complete its duty, users can only perceive the stuck and wait for the endless spinning circle like below:

![](https://user-images.githubusercontent.com/1827717/224903760-54b4bc68-1d0c-41d8-a737-6d8bae80c02c.png) 

After waiting a while, users may try to refresh the page and download it again because they don't have a clear message about what just happened. They may go through the same journey again as the backend problem remains. This isn't good in terms of user experience.

**Describe the solution you'd like**

We shall present meaningful responses while the backend fails to package the logs.

**Describe alternatives you've considered**

**Additional context**

According to https://github.com/harvester/harvester/issues/1926#issuecomment-1467684880, the log packager crashed due to a failure in processing truncated log lines. We fixed the issue in #3646 by ignoring the problematic files to ensure the log packager could execute successfully. But there might be more potential failure cases, and we still need a proper way to handle the failure case and not just hang there.

**Comment by lanfon72** [comment]
Verified this feature not fully implemented.

https://github.com/harvester/harvester/assets/5169694/d0a2bd30-eb21-4742-b692-5b249cb1f947

[supportbundle_f97f07ca-1711-4782-9ba7-d381f970f288_2023-05-30T12-33-16Z.zip](https://github.com/harvester/harvester/files/11600120/supportbundle_f97f07ca-1711-4782-9ba7-d381f970f288_2023-05-30T12-33-16Z.zip)

@starbops, please take a look.

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-a5e74302-head** (same version upgrade)
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade[^1] with **Enable Logging**
3. Access `upgradelog-infra-fluentd` to destroy the logs folder
    - The pod will spawn up when upgrade initialing, execute `kubectl get pods -nharvester-system | grep upgradelog-infra-fluentd` to get its name
    - Or simply execute `kubectl -nharvester-system exec -it -c fluentd $(kubectl get pods -nharvester-system | grep upgradelog-infra-fluentd | awk '{print $1}') -- sh` to access the shell
    - In the shell, execute `touch /archive/logs` to imitate the folder is not accessible 
4. Click `Download Log` on UI
5. UI should show `Log Download Status: fail to...`

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade

**Comment by starbops** [comment]
The enhancement is cherry-picked to the v1.2 branch in #4023.

**Comment by lanfon72** [comment]
blocked by https://github.com/harvester/harvester-installer/pull/492

![image](https://github.com/harvester/harvester/assets/5169694/5d3bcb77-e6fd-42f6-9bc2-2cea61a4217f)
![image](https://github.com/harvester/harvester/assets/5169694/dd79e474-5de4-443a-b0c5-16cb3ce9dab9)
![image](https://github.com/harvester/harvester/assets/5169694/e9be11d8-cc6d-4e2f-9c33-c2549736025a)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/bddb41ca-7750-4f11-96c2-dfaaa734acca)

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-27934bc3-head** (same version upgrade)
* **ui-source** Option: **Auto**


### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade[^1] with **Enable Logging**
3. Access `upgradelog-infra-fluentd` to destroy the logs folder
    - The pod will spawn up when upgrade initialing, execute `kubectl get pods -nharvester-system | grep upgradelog-infra-fluentd` to get its name
    - Or simply execute `kubectl -nharvester-system exec -it -c fluentd $(kubectl get pods -nharvester-system | grep upgradelog-infra-fluentd | awk '{print $1}') -- sh` to access the shell
    - In the shell, execute `touch /archive/logs` to imitate the folder is not accessible 
4. Click `Download Log` on UI
5. UI should show `Log Download Status: fail to...`

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
