### ISSUE TITLE
[ENHANCEMENT] UI shouldn't present "Enable Logging" checkbox before v1.1.2

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3656]
**Is your enhancement related to a problem? Please describe.**

Users can change `ui-source` setting to `External` in a v1.1.0 or v1.1.1 Harvester cluster. This will use v1.1-head dashboard in `ui-index`. An "Enable Logging" checkbox shows up when users try to upgrade the cluster, but in fact, the upgrade log feature isn't ready for upgrades from v1.1.0/v1.1.1 to v1.1.2. The "Enable Logging" checkbox shouldn't appear on the UI in such circumstances.

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/1827717/225201043-81fbded6-df06-4466-9d1e-2a4d308015ed.png">

After changing `ui-source` to `External` and refresh the dashboard:

<img width="1784" alt="image" src="https://user-images.githubusercontent.com/1827717/225202312-3c56344b-7743-4219-a291-88e5f3733862.png">

**Describe the solution you'd like**

Check the schema, if it doesn't exist, just don't show the checkbox.

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/226911533-fd066490-5710-4ce0-8018-1fda3fbef979.png)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1.0** and **v1.1.1** upgrade to **v1.1.2-rc3**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with any nodes
2. Login to Dashboard, navigate to _Advanced/Settings_
3. Update **ui-source** to `External`
4. Perform Upgrade
5. There should not have Checkbox **Enable Logging**
