### ISSUE TITLE
[BUG] Cloud provider should set none when the Harvester  cloud provider is disabled

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3657]
**Describe the bug**

The cloud provider should set none when the Harvester  cloud provider is disabled

**To Reproduce**
1. Install Rancher v2.6.11 and import Harvester v1.1.2-rc3
2. Go to create a cluster by Harvester node driver
3. The "Kubernetes Version" select `v1.22.17`, and the cloud provider selects `Harvester`
4. The "Kubernetes Version" select `v1.24.10`.
5. Check the cloud provider selection

**Expected behavior**

The cloud provider selection should be `none` as the option Harvester is diabled.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.2-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
After discussion, we plan to validate this issue along with #3404 after it's ready for testing.

**Comment by noahgildersleeve** [comment]
I didn't see the dependency on #3404 so I'm moving this back to ready for testing. I'm adding the dependency.

**Comment by noahgildersleeve** [comment]
@n313893254 How should I test this? Can I just check the cloud provider on the RKE2 cluster dropdowns per k8s version in node driver on a master-head version of harvester and Rancher v2.7.5-rc6? I didn't see any versions that didn't have Harvester available as a cloud provider. I saw a few in RKE1  though. I wanted to be sure how to check this properly.

**Comment by TachunLin** [comment]
Checked with @n313893254 and come out the following test plan for reference. 

### Test Plan

#### Purpose 
Ensure when the Harvester and Rancher RKE2 cloud provider version are incompatible,
On the RKE2 provisioning page: 
  
* The cloud provider should display `none` 

#### Test Environment  
- Harvester: v1.1.2 GA
- Rancher: v2.7.5-rc6
- RKE2: v1.25.9+rke2r1 (experimental)
- metadata: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json

#### Test Steps

1. Update rke-metadata-config in Rancher global setting
2. Set the meta to https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json and refresh 
3. Enable Harvester preferences page
4. Import Harvester in Rancher and create cloud credential 
5. Create a RKE2 guest cluster 
6. Enable the `show Deprecated Kubernetes patch versions
7. Select RKE2 version to **v1.25.9+rke2r1**
8. Check the cloud provider state

**Comment by noahgildersleeve** [comment]
Tested with Harvester `v1.1.2` and Rancher `v2.7.5-rc6`. I validated that Harvester  cloud provider  wasn't available in  k8s `v1.25.9`.  It's showing as `Default - RKE Embedded` for cloud provider. You only get the none option in RKE1 node driver deployment. Is this the desired result @n313893254 ?


> Checked with @n313893254 and come out the following test plan for reference.
> 
> ### Test Plan
> #### Purpose
> Ensure when the Harvester and Rancher RKE2 cloud provider version are incompatible, On the RKE2 provisioning page:
> 
> * The cloud provider should display `none`
> 
> #### Test Environment
> * Harvester: v1.1.2 GA
> * Rancher: v2.7.5-rc6
> * RKE2: v1.25.9+rke2r1 (experimental)
> * metadata: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json
> 
> #### Test Steps
> 1. Update rke-metadata-config in Rancher global setting
> 2. Set the meta to https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/rke-meta-data.json and refresh
> 3. Enable Harvester preferences page
> 4. Import Harvester in Rancher and create cloud credential
> 5. Create a RKE2 guest cluster
> 6. Enable the `show Deprecated Kubernetes patch versions
> 7. Select RKE2 version to **v1.25.9+rke2r1**
> 8. Check the cloud provider state&
![Screenshot_20230629_165855](https://github.com/harvester/harvester/assets/83787952/bf4da57f-6899-47ac-8993-a0d7c6aff6ac)
