### ISSUE TITLE
[BUG] Rancher v2.6.10 and Harvester v1.1.2-rc3 compatibility error in setting and project/namespace

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3658]
**Describe the bug**

Rancher v2.6.10 and Harvester v1.1.2-rc3 compatibility error in setting and project/namespace

**To Reproduce**
1. Install Rancher v2.6.10 and import Harvester v1.1.2-rc3
2. Check Harvester setting page and Project/Namespace page

**Expected behavior**

Work as expected

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.2-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
![image](https://user-images.githubusercontent.com/18737885/225246635-63c274cd-d64a-4b8a-a139-a9cc1d795703.png)

**Comment by WuJun2016** [comment]
@n313893254   need support  `>= rancher 2.6.9`

**Comment by lanfon72** [comment]
@n313893254, Page `Projects/Namespaces` is not available in **Rancher 2.6.9** with Harvester **v1.1-e257df76-head**
![image](https://user-images.githubusercontent.com/5169694/226555582-7700738e-2f04-4cd1-9389-a0d37246ea53.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

#### Tested on
- [x] Rancher **2.6.9**
- [x] Rancher **2.6.10**
- [x] Rancher **2.6.11**
- [x] Rancher **v2.6-d146e2b5a5b97944e1aeff828a74c21205a5c59e-head**
- [x] Rancher **2.7.0**
- [x] Rancher **2.7.1**
- [x] Rancher **v2.7-89f1ec4f0c9d0f492c70046048adada1c225e45d-head**

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.1-e257df76-head**
* **ui-source** Option: **Auto**
* Rancher Version: Listed above

### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Access Harvester via Rancher
4. Page _Projects/Namespaces_ and _RBAC/Cluster Members_ should exists and displayed correctly
5. **Default Admin (Role: Cluster Owner)** should not displayed in _Cluster Members_
6. Other pages should displayed and worked as Harvester's dashboard
