### ISSUE TITLE
[ENHANCEMENT] add webhook to validate addons

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3660]
**Is your enhancement related to a problem? Please describe.**

<del>
Logging, monitoring are converted to addons, and the values are in a string field valuesContent, it should be at least valid JSON format.
</del>

Logging, monitoring are converted to addons, webhook is needed to check certain cases

**Describe the solution you'd like**

<del>
Use webhook to validate the valuesContent  in json format
</del>

With the wide usage of harvester addon, webook is required for following scenarios.
(1) cannot create more than one instance for one addon
(2) cannot change addon field chart

We did not find feasible solution for below 2 checks, leave them blank now.

(3) check the existing of given chart (chart + repo + version) (TBD)
(4) check the valuesContent is an valid yaml/json format (TBD)

**Describe alternatives you've considered**

**Additional context**

related issue:
https://github.com/harvester/harvester/issues/2992
UI enhancement:
https://github.com/harvester/harvester/issues/3235

Epic:
https://github.com/harvester/harvester/issues/3262

**Test plan:**

please refer `test plan` description in PR:  https://github.com/harvester/harvester/pull/3704

**Comment by irishgordo** [comment]
@w13915984028  I'm noticing that it seems the validation fails on v1.2.0-rc1 as user is not suppose to be able to edit the chart?

**validation failed**

To reproduce:
- create v1.2.0-rc1 cluster
- once cluster is up and running, do not manually enable addons
- download kubeconfig
- `kubectl edit addons.harvesterhci.io -n harvester-system pcidevices-controller`
- edit spec.chart
- save

You can successfully edit spec.chart.
In the attached example, an extra "r" was added to become: `harvester-pcidevices-controllerr`
![Screenshot from 2023-06-08 11-33-22](https://github.com/harvester/harvester/assets/5370752/c6addecf-ddae-4bc2-b1ee-39e1ae573d83)

**Comment by w13915984028** [comment]
@irishgordo Looks the PR is not in RC1, please validate it with master-head.

https://github.com/harvester/harvester/commits/v1.2
![image](https://github.com/harvester/harvester/assets/31133476/f67ab797-b7a0-4338-8488-13140745594e)

https://github.com/harvester/harvester/releases/tag/v1.2.0-rc1

**Comment by irishgordo** [comment]
Ahh thanks @w13915984028  - I'll re-validate with master-head release :smile:

**Comment by irishgordo** [comment]
This looks good :+1: :smile:  - thanks for the enhancement @w13915984028 
Tested on
Harvester Version: master-4a139bbc-head 

I'll go ahead and close this out :+1:
