### ISSUE TITLE
[BUG] Node failing to bring cluster network bridge status to UP after reboot, leaving it in state UNKNOWN

### ISSUE THREAD

**Issue by oivindoh** [harvester/harvester#3664]
**Describe the bug**

Followed the documentation to set up separate VM and Storage networks for a harvester 1.1.1 cluster, and successfully migrated all workloads to the new storage and vm cluster network attached vlanconfigs.

However, on rebooting one of six nodes, the bridge associated with the new networks won't come up, showing the following in dmesg. The physical links are up and the bond appears fine:

```
[Fri Mar 10 20:03:13 2023] vm-bo: (slave eno1): Enslaving as a backup interface with an up link
[Fri Mar 10 20:03:14 2023] i40e 0000:01:00.1 eno2: set new mac address 24:6e:96:46:f2:ba
[Fri Mar 10 20:03:14 2023] 8021q: adding VLAN 0 to HW filter on device eno2
[Fri Mar 10 20:03:14 2023] vm-bo: (slave eno2): Enslaving as a backup interface with an up link
[Fri Mar 10 20:03:14 2023] device vm-br entered promiscuous mode
[Fri Mar 10 20:03:14 2023] A link change request failed with some changes committed already. Interface vm-br may have been left with an inconsistent configuration, please check.
[Fri Mar 10 20:03:14 2023] vm-bo (unregistering): (slave eno1): Releasing backup interface
[Fri Mar 10 20:03:14 2023] i40e 0000:01:00.0 eno1: already using mac address 24:6e:96:46:f2:ba
[Fri Mar 10 20:03:14 2023] vm-bo (unregistering): (slave eno2): Removing an active aggregator
[Fri Mar 10 20:03:14 2023] vm-bo (unregistering): (slave eno2): Releasing backup interface
[Fri Mar 10 20:03:14 2023] i40e 0000:01:00.1 eno2: returning to hw mac address 24:6e:96:46:f2:bc
[Fri Mar 10 20:03:14 2023] vm-bo (unregistering): Released all slaves
[Fri Mar 10 20:03:14 2023] 8021q: adding VLAN 0 to HW filter on device vm-bo
[Fri Mar 10 20:03:14 2023] i40e 0000:01:00.0 eno1: already using mac address 24:6e:96:46:f2:ba
[Fri Mar 10 20:03:14 2023] 8021q: adding VLAN 0 to HW filter on device eno1
[Fri Mar 10 20:03:14 2023] vm-bo: (slave eno1): Enslaving as a backup interface with an up link
[Fri Mar 10 20:03:15 2023] i40e 0000:01:00.1 eno2: set new mac address 24:6e:96:46:f2:ba
[Fri Mar 10 20:03:15 2023] 8021q: adding VLAN 0 to HW filter on device eno2
[Fri Mar 10 20:03:15 2023] vm-bo: (slave eno2): Enslaving as a backup interface with an up link
[Fri Mar 10 20:03:15 2023] vm-br: port 1(vm-bo) entered blocking state
[Fri Mar 10 20:03:15 2023] vm-br: port 1(vm-bo) entered disabled state
[Fri Mar 10 20:03:15 2023] device vm-bo entered promiscuous mode
[Fri Mar 10 20:03:15 2023] device eno1 entered promiscuous mode
[Fri Mar 10 20:03:15 2023] device eno2 entered promiscuous mode
[Fri Mar 10 20:03:15 2023] vm-br: port 1(vm-bo) entered blocking state
[Fri Mar 10 20:03:15 2023] vm-br: port 1(vm-bo) entered forwarding state
```

interface:

```
25: vm-br: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default
    link/ether 9e:a1:5f:e7:ee:74 brd ff:ff:ff:ff:ff:ff
```

controller log:

```
time="2023-03-10T20:03:15Z" level=error msg="error syncing 'har-04': handler harvester-network-vlanconfig-controller: set up VLAN failed, vlanconfig: har-04, node: har-04, error: ensure bridge vm-br failed, error: set vlan filtering failed, error: invalid argument, iface: &{0xc0006de140}, requeuing"
I0310 20:03:15.252249       1 controller.go:75] vlan config har-04 has been changed, spec: {Description: ClusterNetwork:vm NodeSelector:map[kubernetes.io/hostname:har-04] Uplink:{NICs:[eno1 eno2] LinkAttrs:0xc001c85e30 BondOptions:0xc00052ad50}}
```

**To Reproduce**

I don't _think_ these steps are necessarily a good path to reproduction. These nodes have been rebooted several times before without issue.

1. Start with everything on 10Gbe bond (management, storage, vm traffic)
2. Migrate to 1Gbe bond for management (by modifying yaml in /oem to configure different interface pairs
3. Reboot cluster
4. Create cluster network selecting old interfaces on each node to be used for VMs and storage
5. Migrate workloads to new network's vlanconfigs
6. Wait
7. Reboot one node
8. Observe bridge associated with new VM and storage networks not coming up

**Expected behavior**

vm-br / cluster network should come up as long as there is connectivity

**Support bundle**
Sent support bundle via email

**Environment**
 - Harvester ISO version: 1.1.1 (upgraded from 1.1.0)
 - Underlying Infrastructure: Baremetal Dell PowerEdge R730 (there are also R7525s in the cluster)

**Additional context**

@yaocw2020 pointed (on [slack](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1678480205106369)) towards this being an issue setting vlanfiltering=true for the bridge in https://github.com/harvester/network-controller-harvester/blob/master/pkg/network/iface/bridge.go#L55

**Comment by oivindoh** [comment]
After further testing, the bridge appears to be functional even though its state is UNKNOWN.

I migrated in a VM from another node, and the migration was successful. VM stayed online on network connected to vm-br with state UNKNOWN even after migration.

Then deleted a replica of this VM's volume and observed a successful rebuilt replica get spawned on node with vm-br in state UNKNOWN.

**Comment by w13915984028** [comment]
@oivindoh do you know the types and vendors of the NICs  in your hardware ? thanks.

below answer is not directly related to this issue, but can be an reference
https://superuser.com/questions/1463162/unknown-state-of-network-interface

maybe Linux deduce the (virtual) Bridge state from the related physical link, need further check.

**Comment by oivindoh** [comment]
@w13915984028 the interfaces in question are Intel Ethernet Controller X710 for 10GbE SFP+

Other nodes with the same harvester version and same config have a successful state. I'll migrate some VMs to the UNKNOWN state node and see if I can cause the same issue on the others.

**Comment by oivindoh** [comment]
I see the same issue on other nodes after rebooting. I thought it might be related to a custom yaml file in /oem related to #3476 :

```yaml
stages:
name: "Run customization"
stages:
  "network.after":
    - commands:
      # workaround for fragmentation issue when using ipv6 and large packets
      - sysctl -w net.bridge.bridge-nf-call-ip6tables=0
```

But I verified that booting without this file present leads to the same symptom. I'll change the description though - it does not seem to affect availability of the cluster-produced bridge (it is up OK and vlans appear to work as expected), just its STATE is bad.

Perhaps this issue is not worth pursuing?
