### ISSUE TITLE
[BUG] harvester terraform provider 6.0 cleans up resource but reports timeout error

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3668]
**Describe the bug**
Resource gets deleted correctly but terraform reports timeout issue.
Noticed when cleaning vlan vm-network on management network via `terraform delete` 

**To Reproduce**
1. Create mgmt vlan vm-network (vlan_id=1) via terraform
1. Delete mgmt vlan vm-network via terraform

**Expected behavior**
A timeout error on Terraform to not be displayed

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure: bare-metal hp machine
- Harvester Terraform:
```
    harvester = {
      source = "harvester/harvester"
      version = "0.6.0"
    }
```

**Additional context**
Log:
```
harvester_virtualmachine.dr27-head-vm: Destroying... [id=default/docker-rancher-27-head]
harvester_virtualmachine.dr27-head-vm: Destruction complete after 1s
harvester_ssh_key.dr27-head-ssh-key: Destroying... [id=default/dr27-head-ssh-key]
harvester_network.mgmt-vlan1-dr27-head: Destroying... [id=default/mgmt-vlan1-dr27-head]
harvester_image.ubuntu2204-jammy-dr27-head: Destroying... [id=default/ubuntu-2204-dr27-head]
kubernetes_secret.dr27-head-cloud-config-secret: Destroying... [id=default/dr27-head-cc-secret]
harvester_ssh_key.dr27-head-ssh-key: Destruction complete after 0s
harvester_image.ubuntu2204-jammy-dr27-head: Destruction complete after 0s
kubernetes_secret.dr27-head-cloud-config-secret: Destruction complete after 0s
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 10s elapsed]
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 20s elapsed]
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 30s elapsed]
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 40s elapsed]
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 50s elapsed]
harvester_network.mgmt-vlan1-dr27-head: Still destroying... [id=default/mgmt-vlan1-dr27-head, 1m0s elapsed]
╷
│ Error: timeout waiting for network default/mgmt-vlan1-dr27-head to be deleted
│ 
│ 
╵
```

**Comment by irishgordo** [comment]
updated reproducibility as this seems very easy to reproduce consistently with vm-networks based on mgmt vlan

**Comment by futuretea** [comment]
@irishgordo I tried to reproduce the issue on Harvester v1.1.1 + terraform v0.6.0, using the following terraform configuration, but I could not reproduce the issue:

```hcl
resource "harvester_network" "mgmt-vlan1" {
  name      = "mgmt-vlan1"
  namespace = "harvester-public"

  vlan_id = 1

  route_mode           = "auto"
  route_dhcp_server_ip = ""

  cluster_network_name = "mgmt"
}
```
Can you provide your terraform network configuration?

**Comment by irishgordo** [comment]
@futuretea  - thanks for looking into this :smile: :+1: 

Here is the outline of some of the files that were part of the rollout:
https://github.com/irishgordo/crop-bushels/tree/main/terraform/applications/docker-rancher269

**Comment by guangbochen** [comment]
@irishgordo @futuretea would be good if we can double-check this issue with the Harvester v1.1.2-head version, thanks.

**Comment by futuretea** [comment]
@irishgordo @guangbochen I tried to reproduce the issue on Harvester v1.1.1/v1.1-head (today) + terraform v0.6.0, using the  terraform configuration https://github.com/irishgordo/crop-bushels/tree/main/terraform/applications/docker-rancher-27-head, but I could not reproduce the issue:
```bash
harvester_virtualmachine.dr27-head-vm: Destroying... [id=default/rancher27head]
harvester_virtualmachine.dr27-head-vm: Still destroying... [id=default/rancher27head, 10s elapsed]
harvester_virtualmachine.dr27-head-vm: Destruction complete after 13s
harvester_network.mgmt-vlan1-dr27-head: Destroying... [id=default/mgmt-vlan1-dr27-head]
harvester_ssh_key.dr27-head-ssh-key: Destroying... [id=default/dr27-head-ssh-key]
harvester_image.ubuntu2204-jammy-dr27-head: Destroying... [id=default/ubuntu-2204-dr27-head]
kubernetes_secret.dr27-head-cloud-config-secret: Destroying... [id=default/dr27-head-cc-secret]
harvester_ssh_key.dr27-head-ssh-key: Destruction complete after 0s
harvester_image.ubuntu2204-jammy-dr27-head: Destruction complete after 0s
kubernetes_secret.dr27-head-cloud-config-secret: Destruction complete after 0s
harvester_network.mgmt-vlan1-dr27-head: Destruction complete after 0s

Destroy complete! Resources: 5 destroyed.
```

**Comment by irishgordo** [comment]
I am unable to consistently reproduce the issue too.
I just updated my local binary version of Terraform as well to 1.4.2 which is the latest - which may have had an impact but I'm unsure.
Thanks for looking into this @futuretea  - I'll go ahead and close this out for now :smile: :+1:
