### ISSUE TITLE
[FEATURE] Support static IP address

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#367]
**Describe the solution you'd like**

- The harvester bridge now only supports dynamic IP address requested from DHCP server. The static IP address also needs to be supported.
- Support to configure static IP address for management network NIC. It should be able to specify in the installation process.

**Comment by yaocw2020** [comment]
> * The harvester bridge now only supports dynamic IP address requested from DHCP server. The static IP address also needs to be supported.

We refactor Harvester network controller. You can use `connman` to modify IP address of physical NIC attached with bridge manually , then Harvester network controller can monitor the change of IP address and reset the IP address for bridge.

**Comment by DoNotSayYes** [comment]
**Scenarios：**
Assuming the management host is: https://172.16.0.123
- [x] 1. Configure a static IP that is in the same subnet as the management host. 
- IP: 172.16.0.111/16
- Gateway: 172.16.0.1
- DNS: 0.0.0.0,8.8.8.8
- [x] 2. Configure a static IP that is in another subnet. 
- IP: 172.15.0.111/16
- Gateway: 172.15.0.1
- DNS: 0.0.0.0,8.8.8.8
- [ ] 3. Assuming the nic state is down, try to set up a static IP. A related issue: #516 

![image](https://user-images.githubusercontent.com/57614736/110431690-16039180-80e9-11eb-921e-bceca9c182ba.png)
![image](https://user-images.githubusercontent.com/57614736/110444462-00499880-80f8-11eb-811c-fdb985179106.png)
