### ISSUE TITLE
[BUG] After installation getting "Cannot open access to console the root account is locked"

### ISSUE THREAD

**Issue by robcxyz** [harvester/harvester#3672]
**Describe the bug**

I installed harvester per the instructions and am getting "Cannot open access to console the root account is locked". I am setting up on a VPS based bare metal server where I have access via kvm. To install, I copied the harvester ISO over to a spare drive where I then booted into. I then went through the harvester installation process choosing to install on the original disk. When I try to boot into harvester I get the above error `Cannot open access to console the root account is locked`

**To Reproduce**
1. Copy harvester with `dd` to extra drive - `/dev/nvme1n1
2. Boot into spare drive and walk through harvester installation
3. Choose the original disk as the target  - `/dev/nvme0n1`
4. Reboot 
5. `Cannot open access to console the root account is locked`

**Expected behavior**

I should be able to reboot into harvester. 

**Support bundle**

**Environment**
 - Harvester ISO version: [v1.1.2-rc3](https://github.com/harvester/harvester/releases/tag/v1.1.2-rc3)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Supermicro bare metal on Vultr 

**Additional context**

**Comment by bk201** [comment]
> 1. Copy harvester to extra drive - `/dev/nvme1n1

@robcxyz Did you dd the ISO file to the device?

**Comment by robcxyz** [comment]
@bk201 - Yes I did. 

Since then I have also tried to recover with some instructions from https://suay.site/?p=1681 which did not help.

**Comment by robcxyz** [comment]
Issue was an incomplete installation of  harvester. Sorry for late update. Closing.
