### ISSUE TITLE
[BUG] Not able to join nodes in case of SSL enabled using private CA

### ISSUE THREAD

**Issue by prashantgnet** [harvester/harvester#3676]
**Describe the bug**
Created initial harvester cluster using 5 nodes without SSL certificate which works perfectly fine. 
Enabled SSL certificate and tried to join 6th node which fails with CA cert related error messages in rachard service.
Able to Join 6th node when disable the SSL certificate.

**To Reproduce**
1. Create cluster 
2. Join node without enabling SSL 
3. Enable SSL
4. Join node is failing.

**Expected behavior**
Node must able to join cluster in case of SSL enabled.

**Support bundle**
NA

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal DELL PowerEdge servers

**Additional context**
Please document in case of manual steps to follow. I don't saw any installer prompt which asked for SSL certificate for joining node.

**Comment by guangbochen** [comment]
May refer to https://github.com/harvester/harvester/issues/2736#issuecomment-1346207402 as a temp workaround. This will need further enhancement to support this configuration during the installation.

**Comment by iosifnicolae2** [comment]
Any idea how to solve this problem? https://github.com/harvester/harvester/issues/2736#issuecomment-1346207402 doesn't seem to solve the problem for me

**Comment by bk201** [comment]
Can be fixed with https://github.com/harvester/harvester/issues/4603
