### ISSUE TITLE
[BUG] Upgrade hung after image downloaded

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3677]
**Describe the bug**

When you try to upgrade a single node v1.1.1 Harvester cluster it hangs after downloading the image
**To Reproduce**
1. Deploy a single node Harvester cluster
2. Upload an image
3. Create a VM network based on the management cluster network
4. Create a VM with the image and network
5. Run an upgrade to v1.1.2-rc3
**Expected behavior**

**Support bundle**

[supportbundle_c737ea4e-2183-47a1-9e4f-3b938a8b845b_2023-03-17T23-22-41Z.zip](https://github.com/harvester/harvester/files/11007022/supportbundle_c737ea4e-2183-47a1-9e4f-3b938a8b845b_2023-03-17T23-22-41Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node libvirt VM 12c 26GB RAM

**Additional context**
I'm testing this with v1.1-head as well and will update the ticket with the results.

**Comment by starbops** [comment]
From the support-bundle, the launcher Pod of the upgrade repo VM was not ready (readiness probe failed):

```
harvester-system            virt-launcher-upgrade-repo-hvst-upgrade-5rktl-8vwq2      ●   0/1              0 Running      10.52.0.103    harvester-v111-upgrade    2d8h
```

And the relevant event shows:

```
action: sim-generated
apiVersion: v1
eventTime: "2023-03-17T22:10:36.000000Z"
firstTimestamp: null
involvedObject:
  apiVersion: v1
  fieldPath: spec.containers{compute}
  kind: Pod
  name: virt-launcher-upgrade-repo-hvst-upgrade-5rktl-8vwq2
  namespace: harvester-system
  uid: b810a77b-8e38-4986-90f4-fb934408cd5b
kind: Event
lastTimestamp: null
message: 'Readiness probe failed: Get "http://10.52.0.103:80/harvester-iso/harvester-release.yaml":
  dial tcp 10.52.0.103:80: connect: no route to host'
metadata:
  annotations:
    sim.harvesterhci.io/creationTimestamp: "2023-03-17T22:10:36Z"
  creationTimestamp: "2023-03-17T22:10:36Z"
  name: virt-launcher-upgrade-repo-hvst-upgrade-5rktl-8vwq2.174d5466cc0a6212
  namespace: harvester-system
  resourceVersion: "2158"
  uid: eab9e590-ee24-4efe-92e6-0c5d08a2e152
reason: Unhealthy
reportingComponent: sim-generated
reportingInstance: sim-generated
source: {}
type: Warning
```

The upgrade was stuck at the waiting of the repo VM.

**Comment by bk201** [comment]
@noahgildersleeve the checksum seems to be different from what we published, could you help check if the ISO is correct:

The virtualmachine image `harvester-iso-rnl67`:
```
  spec:
    checksum: 66bed73799b6c2f272222c2fc4ef808ce1915c3ae39802443218faf37b4e41400143db8e242a8dcbf68db6b9741b3d31392c0f2a83c939655c814c84c2d39db9
    displayName: hvst-upgrade-5rktl-v1.1.2-rc3
    pvcName: "null"
    pvcNamespace: "null"
    sourceType: download
    storageClassParameters:
      migratable: "true"
      numberOfReplicas: "3"
      staleReplicaTimeout: "30"
    url: http://10.0.5.154/harvester/harvester-v1.1.2-rc3-amd64.iso
```

What we publish https://releases.rancher.com/harvester/v1.1.2-rc3/version.yaml:
```
spec:
  isoChecksum: 'a9ccaf0294d96e0d23baaa0765aab1cecb5de79e1dca8686137147bebafb03e96ed1fb2122f2a2ab577270aa98a0f01182dff478e1a558742791c10db8394ab0'
  isoURL: https://releases.rancher.com/harvester/v1.1.2-rc3/harvester-v1.1.2-rc3-amd64.iso
  releaseDate: '20230310'
```

**Comment by w13915984028** [comment]
@bk201 Seemed I also encountered this issue when forgot to change the checksum of the `version`.

On the other hand, can `upgrade` have effective way to detect this error and show the error in the popup window or some other places.

This can be an further enhancment.

**Comment by starbops** [comment]
The checksum is the same observed from the BackingImage:

```
apiVersion: longhorn.io/v1beta1
kind: BackingImage
metadata:
  annotations:
    harvesterhci.io/imageId: harvester-system/harvester-iso-rnl67
    sim.harvesterhci.io/creationTimestamp: "2023-03-17T22:09:20Z"
  creationTimestamp: "2023-03-17T22:09:20Z"
  finalizers:
  - longhorn.io
  generation: 1
  name: harvester-system-harvester-iso-rnl67
  namespace: longhorn-system
  resourceVersion: "1860"
  uid: 854de048-452f-4534-953e-e94034365fac
spec:
  checksum: 66bed73799b6c2f272222c2fc4ef808ce1915c3ae39802443218faf37b4e41400143db8e242a8dcbf68db6b9741b3d31392c0f2a83c939655c814c84c2d39db9
  disks: {}
  sourceParameters:
    url: http://10.0.5.154/harvester/harvester-v1.1.2-rc3-amd64.iso
  sourceType: download
status:
  checksum: 66bed73799b6c2f272222c2fc4ef808ce1915c3ae39802443218faf37b4e41400143db8e242a8dcbf68db6b9741b3d31392c0f2a83c939655c814c84c2d39db9
  diskDownloadStateMap: {}
  diskFileStatusMap:
    4d2baff7-dec3-42ff-be92-63895f84c807:
      lastStateTransitionTime: "2023-03-17T22:09:58Z"
      progress: 100
      state: ready
  diskLastRefAtMap: {}
  ownerID: harvester-v111-upgrade
  size: 4865110016
  uuid: ea0521c5
```

Seemed not related to #3123

**Comment by noahgildersleeve** [comment]
I checked into this @bk201 . You were correct and the checksum didn't match. It seems that my ISO was corrupt or having some issue. I'm rerunning the upgrade tests and will update this ticket once I know more.

**Comment by noahgildersleeve** [comment]
I reran the upgrade with the correct ISO. All upgreade tests passed for v1.1.1 -> v1.1.2-rc3 on single node install. Should we close this ticket? CC @rebeccazzzz

**Comment by noahgildersleeve** [comment]
I checked with @rebeccazzzz and I'm closing this as not an issue.
