### ISSUE TITLE
[BUG] Upgrade 3 nodes Harvester stuck in `Pre-drained` of the first node (create volume with snapshot)

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3681]
**Describe the bug**

* When upgrade from v1.1.1 to v1.1.2-rc3, the upgrade stuck in the `Pre-drained` state of the first node
![image](https://user-images.githubusercontent.com/29251855/226308714-98299bdc-f672-438a-a76b-77476d2b8c6a.png)

* Prior to upgrade, we have vm backup created while vm is running, create vm snapshot and create volume with volume snapshot. 

* Some pod keep in pending state `rancher-7d68567b9d-ldvwz`, `harvester-8546cc6cf4-jln8c` and `harvester-webhook-79df879d8b-gv4z8` 
![image](https://user-images.githubusercontent.com/29251855/226308111-3ac897d1-3125-4a23-b14a-f5e73c7edcea.png)

**To Reproduce**
1.  Provision a three nodes `v1.1.1` Harvester cluster 
2. Create three images
3. Create three virtual machines separate on each node
4. Create three VM backups
5. Add some file to running VM
6. create two VM snapshots 
7. Create two new volume `opensuse-volume`, `ubuntu-volume` 
8. Create two volume snapshots
9. Perform offline upgrade to v1.1.2-rc3

**Expected behavior**

Should be able to upgrade successfully with no stuck in the `Pre-drained` node state when we have vm backup, vm and volume snapshot

**Support bundle**

[supportbundle_cf1194db-d39e-42a4-81f3-153e3d2c7a92_2023-03-20T10-05-48Z.zip](https://github.com/harvester/harvester/files/11016869/supportbundle_cf1194db-d39e-42a4-81f3-153e3d2c7a92_2023-03-20T10-05-48Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1 -> v1.1.2-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes bare machines

**Comment by bk201** [comment]
This is a similar issue with https://github.com/harvester/harvester/issues/3648 and will be addressed together in https://github.com/harvester/harvester/pull/3670.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.1.2-rc4` (3/24). Close this issue.

### Result
We can upgrade successfully with no stuck in the Pre-drained node state when Harvester have vm backup, vm snapshot and volume snapshot created before upgrade


![image](https://user-images.githubusercontent.com/29251855/227908703-0ca3f9c3-f0b0-4ae6-a9fc-8bc68d48de6a.png)

### Test Information
* Test Environment: 3 nodes harvester on bare machines
* Harvester version: `v1.1.2-rc4` (3/24)

### Verify Steps
Steps to reproduce the behavior:
1.  Provision a three nodes `v1.1.1` Harvester cluster 
2. Create three images
3. Create three virtual machines separate on each node
4. Create three VM backups
5. Add some file to running VM
6. create two VM snapshots 
7. Create two new volume `opensuse-volume`, `ubuntu-volume` 
8. Create two volume snapshots
9. Perform offline upgrade to v1.1.2-rc3
