### ISSUE TITLE
[Question] How to ensure permanent static IP assigned to newly built VMs?

### ISSUE THREAD

**Issue by haiwu** [harvester/harvester#3682]
I  could not find this info from harvester doc. 

One way is to create a MAC->IP static mapping in DHCP server first. But this means end user would have to know such mapping before trying to create a new VM via Harvester UI, and end user would have to know the mapping picked is not in use yet by any other production running/stopped VMs. Another way is to create the new VM via Harvester UI first, without specifying its MAC address, harvester will auto-assign a new MAC address to the new VM. Then we have another process to create the MAC->IP static mapping in DHCP server, the VM will fail to boot initially due to no such mapping exists in the beginning. I am not sure if there's any hooks in kubevirt/harvester that we could use to auto-create such static MAC->IP mapping in DHCP server. 

Another way is to reserve a static IP via Harvester/Kubevirt built-in IPAM first. Is this way even possible with harvester/kubevirt? This is possible in Opensteack via `openstack port` command.

**Comment by w13915984028** [comment]
Solid IP for VM is important. Generally, there could be 2 options:

(1) Use static IP, in `guest agent command` to config this IP, thus each VM will have this IP and can carry it when migrating.

(2) Allow user to input `MAC` when creating VM, user can prepare IP/MAC mapping in DHCP server, and configure this MAC when creating VM.

I am not fully sure the availability of (1) and (2) at the moment.

Harvester-installer allows user to configure MAC (not from UI, but harvester-configuration file), that can work together with DHCP server IP/MAC binding to make sure NODE IP stable.
![image](https://github.com/harvester/harvester/assets/31133476/4dbef692-57d4-4843-a402-0874ace5ca26)

@yaocw2020 @FrankYang0529 @futuretea   Any idea of this topic? thanks.

cc @guangbochen @bk201

**Comment by w13915984028** [comment]
Add for reference in https://github.com/harvester/harvester/pull/4960

**Comment by w13915984028** [comment]
@haiwu How did you achieve this later?
