### ISSUE TITLE
[FEATURE] Support configure rootfs layout (PERSISTENT_STATE_PATHS) through Harvester configuration

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3688]
Currently, the rootfs layout is hardcoded in
https://github.com/harvester/harvester-installer/blob/111c75b62326b40dfefcefdc5f7ce0c657b7d0dd/pkg/config/templates/cos-rootfs.yaml#L9

Users must build their custom iso if they want to add some dirs to the PERSISTENT_STATE_PATHS.

**Describe the solution you'd like**

Support configure rootfs layout through Harvester configuration

**Describe alternatives you've considered**

**Additional context**

**Comment by futuretea** [comment]
Test Plan follow https://github.com/harvester/harvester/issues/2405#issuecomment-1549634520

**Comment by lanfon72** [comment]
Verified this feature has been implemented.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-b49e264e-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes with configure option:
```yaml
os:
  persistentStatePaths:
    - /var/lib/rook
```
2. Harvester should installed successfully
3. Login to console, folder `/var/lib/rook` should exist
4. Reboot the node, folder `/var/lib/rook` should still exist
