### ISSUE TITLE
[BUG] Failed to install additional selinux policy by semodule

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3690]
**Describe the bug**

```bash
libsemanage.semanage_commit_sandbox: Error while renaming /var/lib/selinux/targeted/active to /var/lib/selinux/targeted/previous. (Invalid cross-device link).
/usr/sbin/semodule:  Failed!
```
**To Reproduce**
1. install an rpm package that includes selinux policies, refer to https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only

**Expected behavior**

install additional selinux policy successfully
**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

workaround:
```bash
mv /var/lib/selinux/targeted/active /var/lib/selinux/targeted/previous
cp --link --recursive /var/lib/selinux/targeted/previous /var/lib/selinux/targeted/active
```

**Comment by innobead** [comment]
Let's reopen this if this is still a valid issue.
