### ISSUE TITLE
[Enhancement] Support for configuring StorageClass in the Harvester node driver

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3691]
**Is your feature request related to a problem? Please describe.**
Support for configuring StorageClass in the Harvester node driver.

The current default StorageClass  for volumes in the guest cluster is the system's default StorageClass.

**Describe the solution you'd like**
allowing admin users to select storageClass when creating a new guest RKE2 cluster. 
 <img width="2174" alt="image" src="https://github.com/harvester/harvester/assets/4569037/a0030908-f5e7-49e0-a23b-d9d51306ff19">
- [ ] Rancher UI
- [ ] terraform-provider-rancher2

**Describe alternatives you've considered**

**Additional context**
- May need to consider non-admin RBAC users, e.g., restricted admin of the Harvester cluster

**Comment by FrankYang0529** [comment]
I think we don't need UI change. For Volume, we can specify storage class. For Image Volume, I think the name is fixed and we can get it from utility function:

https://github.com/harvester/harvester/blob/0c47319a9e57711cfd3289a36f3e9df5e477f786/pkg/util/image.go#L52-L54

<img width="818" alt="Screenshot 2024-01-10 at 11 42 30 AM" src="https://github.com/harvester/harvester/assets/4927361/e6fab7ba-744d-448f-99a8-b2ebc61c6f74">


@WebberHuang1118, may you double confirm that whether we can just use the utility function to get image storage class? Thanks!

**Comment by WebberHuang1118** [comment]
Yes, the image-backed volume's storage class is decided during image creation.

**Comment by FrankYang0529** [comment]
For terraform-provider-rancher2, we already can specify StorageClass for different volumes.

```tf
     disk_info = <<EOF
     {
         "disks": [{
             "imageName": "default/focal-image",
             "size": 20,
             "bootOrder": 1
         },{
             "storageClassName": "harvester-longhorn",
             "size": 10,
             "bootOrder": 2
         }]
     }
     EOF
```

ref: https://registry.terraform.io/providers/rancher/rancher2/latest/docs/resources/machine_config_v2#disk_info

**Comment by bk201** [comment]
Thank guys, I'll close this one since we already have everything.
