### ISSUE TITLE
[Question] Harvester CSI disk selector

### ISSUE THREAD

**Issue by codot-fr** [harvester/harvester#3695]
Hello,

I have an harvester cluster with two storage classes : one for SSD and one for HDD. SSD is set as default.

I created a RKE2 cluster on top with the harvester CSI through Rancher and the infrastructure driver. Problem is that the PV created through the kubernetes harvester storage class translate to Longhorn volumes without diskSelector tags set and I don't know what to do to pin them to the default SSD class.

Any Idea?

Thanks.

**Comment by Martin-Weiss** [comment]
There is a enhancement developed to allow the configuration of the storage class that should be used via helm values in the harvester-csi driver.

In the meantime you can add an additional parameter "manually" to the daemonset

`kubectl -n kube-system edit daemonsets.apps harvester-csi-driver`

and then add

```
        - name: HOST_STORAGE_CLASS
          value: <your storage class name>
```

to the container with the image `image: rancher/harvester-csi-driver:v0.1.3`

**Comment by codot-fr** [comment]
Thank you Martin!
