### ISSUE TITLE
[ENHANCEMENT] Rancher 2.6.11 allows to create a cluster where each node has the same mac address

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3698]
**Is your enhancement related to a problem? Please describe.**

There is a critical issue in the newly released Rancher 2.6.11 where customers can specify a mac address in the machine pool. The same mac address will then be allocated on each node. This is an invalid configuration breaking the cluster, but also it allows anyone to re-use the mac address of a critical component like switch, router or node.

The same problem is in Harvester 1.1.1 where VM can be created with defined mac address that already exists on the network.

This can cause production to go down when the router/switch/node mac address is mistakenly used when creating a cluster.

**Describe the solution you'd like**

**Describe alternatives you've considered**

It should not be possible to specify the mac address. 

UI change:
1. Hide macAddress filed on rke2&rke1 page.
2. VM create page
-  When creating a single vm, click the `Show More` button to display the `macAddress` field
-  Hide `macAddress` filed when creating multiple instances

**Additional context**

**Comment by WuJun2016** [comment]
UI change:
we need test version:  
harvester:  `v1.1.2-rc4`  `master`
rancher: ` 2.6-head` `2.7.2-head`. `master`

1. rke2 & rke1
<img width="1726" alt="image" src="https://user-images.githubusercontent.com/24985926/227093116-897e5395-a1d5-4619-8a00-4a14f437a1fb.png">


![image](https://user-images.githubusercontent.com/24985926/227091064-ede9d1e7-573b-4b7f-b287-db1343c8028d.png)

2. vm create page:
When creating a single vm, click the `Show More` button to display the macAddress field
Hide macAddress filed when creating multiple instances

**Comment by lanfon72** [comment]
Verified this enhancement not fully implemented.

![image](https://user-images.githubusercontent.com/5169694/227933552-5b473cb7-3d72-4e59-a031-25e86017912e.png)


### Tested On
- Harvester **v1.1.2-rc4** with Rancher **v2.7-7913e283ff90eebd1f8cc48860a6b410d72cd4dd-head**
    - [x] Harvester dashboard
    - [x] Harvester dashboard in Rancher
    - [x] RKE1
    - [x] RKE2
- Harvester **v1.1.2-rc4** with Rancher **v2.6-16a06b91c2faa94ed02abef77ed3ed63134b1f41-head**
    - [x] Harvester dashboard
    - [x] Harvester dashboard in Rancher
    - [x] RKE1
    - [ ] RKE2


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.2-rc4**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-7913e283ff90eebd1f8cc48860a6b410d72cd4dd-head** and **v2.6-16a06b91c2faa94ed02abef77ed3ed63134b1f41-head** (Docker Image ID: _4c4b8cfe485d_ and _82fd1a913a60_)

### Verify Steps
1. Install Harvester with any nodes
2. Login to Dashboard, navigate to page _Virtual Machines_
3. Create VM with option _Multiple Instance_
4. In **Networks** tab, field _Mac Address_ should NOT displayed
5. Create VM with option _Single Instance_
6. In **Networks** tab, field _Mac Address_ should be able to toggled in **Show/Hide More**
7. Import Harvester into Rancher
8. Access Harvester dashboard via Rancher
9. Behaviors should be the same as steps 3 to 6
10. Navigate to _Cluster Management_
11. Create RKE1, field _Mac Address_ should NOT displayed in **Node Template**
12. Create RKE2, field _Mac Address_ should NOT displayed in **Networks** section

**Comment by WuJun2016** [comment]
Hi @lanfon72 ， sorry,  I didn't notice that this PR hasn't been merged yet.    https://github.com/rancher/dashboard/pull/8503

**Comment by lanfon72** [comment]
Verified this enhancement has been implemented.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.2-rc4**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6-16a06b91c2faa94ed02abef77ed3ed63134b1f41-head** (Docker Image ID: _82fd1a913a60_)

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/3698#issuecomment-1485007197
