### ISSUE TITLE
[BUG]Incorrect memory displayed in Edit VM Form UI

### ISSUE THREAD

**Issue by chrisurwin** [harvester/harvester#370]
**Describe the bug**
When creating a VM you can type in any value into the memory box, going back in to view the machine it displays the memory incorrectly in form view, but correctly in yaml view

**To Reproduce**
1. create a new VM
2. set the memory to 2048 GB (this is regardless of what is available in the cluster)
3. pick image and allow it to create, it will get stuck in starting and a describe on the pod will show the error
```Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  11m   default-scheduler  0/1 nodes are available: 1 Insufficient memory.
  Warning  FailedScheduling  11m   default-scheduler  0/1 nodes are available: 1 Insufficient memory.
```
4. go back to the UI and view the node and edit it as a form and it will show:
![image](https://user-images.githubusercontent.com/13744596/102502593-ba3fe400-4076-11eb-8efc-87aae6c986f7.png)
Which will show 2GB not the 2048GB that was requested
5. Go back out and edit it as yaml and it will show
![image](https://user-images.githubusercontent.com/13744596/102502855-05f28d80-4077-11eb-91be-320d8b020a85.png)

**Expected behavior**
That it would so the correct amount of memory in the UI

**Log**
NA

**Environment:**
 - Harvester ISO version: N/A
 - k3s running on baremetal Lenovo TS140, Xeon proc with 32GB Ram
git clone of master-91ad1487-head

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/103637166-069b8700-4f86-11eb-93d7-4db6462ed82e.png)
![image](https://user-images.githubusercontent.com/57614736/103637229-1dda7480-4f86-11eb-9843-134fbe3d5e72.png)
