### ISSUE TITLE
[BUG] When a new Rancher import a Harvester, project/namespace and RBAC menu will disappear

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3701]
**Describe the bug**

When a new Rancher imports a Harvester, project/namespace and RBAC menu will disappear

**To Reproduce**
1. Install a new Rancher and then import a v1.1.1 Harvester
2. Go to Harvester and check the left-side menu

**Expected behavior**

The left side menu shows project/namespace and RBAC

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

There have a [PR](https://github.com/harvester/dashboard/pull/671) fixed in Harvester v1.1.2, use v1.1.2 and the master UI won't reproduce it.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://github.com/harvester/harvester/assets/5169694/498fd31f-ccef-482d-bf12-de8dc06c3100)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2.0-rc1**
* **ui-source** Option: **Auto**
* Rancher Version:
    - **v2.6-a4b924d21cd5d90b28ab8009edc18d96542952ac-head**, Docker Image: **a1d1e43988d2**
    - **v2.7-6ce75a0b57ad9e88cf135254a9b3b40082788eb6-head**, Docker Image: **cabaf5fe17df**

### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Access Harvester via Virtualization Management
4. Page `Projects/Namespaces` should exist, accessible and able to create/edit/delete Projects
5. Page `RBAC/Cluster Members` should exist, accessible and able to add/remote Cluster Members
