### ISSUE TITLE
[FEATURE] arm64 support

### ISSUE THREAD

**Issue by vielmetti** [harvester/harvester#371]
**Is your feature request related to a problem? Please describe.**

Please provide arm64 support for Harvester, once all of the related dependencies have been built for that platform.

**Describe the solution you'd like**

#30 removes a build of Harvester for arm64, because Kubevirt is missing arm64 support
based on https://github.com/kubevirt/kubevirt/pull/3415 PR that has not yet landed.

**Describe alternatives you've considered**

No good alternatives.

**Additional context**

Happy to take a proposal through @worksonarm if test infra is needed.

**Comment by guangbochen** [comment]
thanks for the info and we will consider bringing back the multi-arch support when it is available on the `kubevir` side.

**Comment by rmohr** [comment]
@guangbochen our main issue in kubevirt right now for supporting this is actually having ARM64 machines for building and CI. If rancher depends on it, maybe you can start a thread on the kubevirt-dev mailing list and see what we can do about this?

**Comment by vielmetti** [comment]
@rmohr @guangbochen 

In https://github.com/WorksOnArm/cluster/issues/203 the @worksonarm project provided an Ampere system for kubevirt for building and CI on arm64 - perhaps the project could leverage that existing resource or ask for additional equipment as needed.

**Comment by belgaied2** [comment]
Kubevirt has now an ARM64 build as the above Kubevirt issue ([kubevirt/kubevirt#3415](https://github.com/kubevirt/kubevirt/pull/3415) is now merged. Do we have any timeline for this support in Harvester?

**Comment by yasker** [comment]
KubeVirt ARM64 support is not completed yet. See the tracking issue at: https://github.com/kubevirt/kubevirt/issues/3558

**Comment by vielmetti** [comment]
From the tracking issue:  nightly developer releases of `kubevirt` are available at https://kubevirt.io/user-guide/operations/installation/#experimental-arm64-developer-builds.

**Comment by wonleing** [comment]
Now kubevirt on arm64 basically works fine. We have resolved graphic, mouse, keyboard problem, and arm64 desktop system installation verified OK. https://github.com/kubevirt/kubevirt/issues/3558
So we can go on exploring install and run arm64 system with harvester now, hope to get more support here @yasker

**Comment by yasker** [comment]
Since Harvester v0.3.0, we've switched to using RKE2 which doesn't have an ARM64 version yet.

REF: https://github.com/rancher/rke2/issues/1946 https://github.com/rancher/rke2/issues/817

**Comment by wonleing** [comment]
so for harvester v0.2.0 there should not have significant block. right?
We can try on that way.

**Comment by newhuangchuan** [comment]
Hello, does the current `harvester` 1.0 version support installation and deployment under the CPU of arm64 architecture?

I checked the current official documents, only the x86 architecture is supported, is there any plan for the arm64 architecture?

**Comment by newhuangchuan** [comment]
> thanks for the info and we will consider bringing back the multi-arch support when it is available on the `kubevir` side.

Hello, both `kubevirt` and `longhorn` have supported arm64 architecture and can be deployed. Can harvester support deployment on servers with arm64 architecture?

**Comment by arbrog** [comment]
> Hello, both kubevirt and longhorn have supported arm64 architecture and can be deployed. Can harvester support deployment on servers with arm64 architecture?

@newhuangchuan Harvester uses Ranchers `RKE2` which does not support ARM64 yet. There are a couple of issues open related to ARM64 support: [rke2#817](https://github.com/rancher/rke2/issues/817) (yasker linked this one above as well). Ultimately the main blocker seems to be a go lang issue related to `boringcrypto` not supporting ARM64 ([golang#39760](https://github.com/golang/go/issues/39760)).

**Comment by wonleing** [comment]
Combine harvester with RKE2 is not a good idea... :)

**Comment by Codispatch** [comment]
Looks like The main blocker "Support BoringCrypto ARM64" for Go-lang is pending in go.dev/cl/423362 branch

**Comment by codispatch** [comment]
Looks like The main blocker "Support BoringCrypto ARM64" for Go-lang is almost done and it is pending in go.dev/cl/423362 branch

**Comment by Aixleft723** [comment]
Is anyone else following this issue now？

**Comment by codispatch** [comment]
Harvester is dependent on rke2 and rke2 arm64 support is under development.

**Comment by 3goats** [comment]
Any updates on this ?

**Comment by kMaiSmith** [comment]
It looks like the rke2#817 closed out 3 weeks ago, i am now able to download an arm64 release of RKE2.   Is there anything i can do as an OSS contributor to advance the ARM64 image?

**Comment by krumware** [comment]
Also wondering, now that RKE2 seems ready

**Comment by markhillgit** [comment]
move to 1.4.0 per the roadmap

**Comment by markhillgit** [comment]
pulling this back into 1.3.0 but this is pending confirmation of something in the build

**Comment by khushboo-rancher** [comment]
Testing scope should be running e2e automation on ARM machines

**Comment by lanfon72** [comment]
e2e automation will fail because we fix images to use x86-based.

**Comment by lanfon72** [comment]
Tested `v1.3.0-rc4` ISO installation work as expected.

**Comment by lanfon72** [comment]
Test Information
----
* Environment: **MegaRAC SP-X 2 nodes**
* Harvester Version: **v1.3.0-rc4**
* **ui-source** Option: **Auto**


Test Fails
----
### Storage Network
Unable to setup `storage-network`
![image](https://github.com/harvester/harvester/assets/5169694/20f9e83c-09b0-4830-a337-ba8f46c33edf)

### Host Info
Host's details showing **Hardware-based virtualization is disabled or not supported.**
![image](https://github.com/harvester/harvester/assets/5169694/0f025fbc-19bf-4bb7-a553-91bd2718646c)

### VM migration
Unable to trigger migration by UI or API
![image](https://github.com/harvester/harvester/assets/5169694/c572deb8-84f3-4a49-9bc6-d45ebf713b34)
![image](https://github.com/harvester/harvester/assets/5169694/70f99633-3c22-4fb5-9461-c4ec4ff1e037)

**But we can still trigger migration via `virtctl` command tool**

**Comment by lanfon72** [comment]
Add E2E test reports: [test_result.zip](https://github.com/harvester/harvester/files/14586953/test_result.zip)

### Not Tested (by automation)
- Host power cycle related test cases (the cluster have only 2 nodes)
- RKE1/RKE2 (automation bugs)
- Update VM machine types (automation bug)

Other fails described in https://github.com/harvester/harvester/issues/371#issuecomment-1992017605, the part of **migration** had been resolved and be tested by automation.

Now we would need to know whether #5351 will be included in `v1.3.0` and we will need to re-test the part of **storage network**, otherwise we can close this issue and document it in release note.

**Comment by lanfon72** [comment]
Close as this feature has been applied.
There still have some minor bugs would be track in other issues.

[test_result_head.zip](https://github.com/harvester/harvester/files/14601260/test_result_head.zip)

Test Information
----
* Environment: **MegaRAC SP-X 2 nodes**
* Harvester Version: **v1.3-2c8332b7-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform automation tests and do smoke test manually
