### ISSUE TITLE
[BUG] When in Rancher Harvester dashboard and adding a network config with an empty NIC you get the wrong error

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#3716]
**Describe the bug**

When you are 
**To Reproduce**
1. Navigate to the Harvester dashboard from an upstream Rancher cluster
2. Add a cluster network
3. Start to add a network config with a name
4. For uplink select Add NIC
5. Put in a NIC for one of the entries and leave the otehr blank
6. Click create
**Expected behavior**

You should get the same error that you see in the Harvester dashboard
**Support bundle**

[supportbundle_66d0018e-bc98-4375-9cc8-af8500be7163_2023-03-23T22-08-39Z.zip](https://github.com/harvester/harvester/files/11056731/supportbundle_66d0018e-bc98-4375-9cc8-af8500be7163_2023-03-23T22-08-39Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2-rc3
 - Rancher version: v2.7.2-rc6 single node Docker
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): libvirt 3 node with ipxe-examples

**Additional context**
This error show properly in the Harvester dashboard. You can see in the screenshots. The darkmode screenshot it the native Harvester dashboard. The error that is showing in Rancher is `%validation.arrayCountRequired(key: NICs, count: 1)%`
![Screenshot_20230323_151147](https://user-images.githubusercontent.com/83787952/227376372-7357f8b3-ad47-4a60-acfd-be551c61dbf5.png)
![Screenshot_20230323_150647](https://user-images.githubusercontent.com/83787952/227376373-98ab97df-9130-486e-a8f9-d20b8a08f7db.png)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/227921688-c2fd675b-beb7-4c22-b05c-123e2b9eb9c4.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.2-rc4**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-7913e283ff90eebd1f8cc48860a6b410d72cd4dd-head** (Docker Image ID: _4c4b8cfe485d_)

### Verify Steps
1. Install Harvester with any nodes
2. Follow **Steps to Reproduce** in https://github.com/harvester/harvester/issues/3716#issue-1638413542
