### ISSUE TITLE
[BUG] VLAN config state displays "active" when the selected node is being deleted

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3717]
**Describe the bug**

VLAN config state displays "active" when the selected node is being deleted

**To Reproduce**

1. Install Harvester and then join another node named "node-new"
2. Create a VLAN config with node selector select the "node-new" host
3. Delete the "node-new" host
4. Check VLAN config state

**Expected behavior**

The VLAN config should show "Not Ready"

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://user-images.githubusercontent.com/18737885/227471039-3b00b767-9232-4e9b-9e93-cf160ef6b622.png)

**Comment by lanfon72** [comment]
The state will not become **active** due to the bug in #3723

**Comment by noahgildersleeve** [comment]
Tested in `v1.1.2-rc4` with latest dashboard by setting `ui-source` to `external`.
## Verification steps

1. Install Harvester and then join another node named "node-new"
2. Create a VLAN config with node selector select the "node-new" host
![Screenshot_20230327_160352](https://user-images.githubusercontent.com/83787952/228086569-10edb5ee-fb6b-4000-9185-345318a62817.png)
3. Delete the "node-new" host
![Screenshot_20230327_160439](https://user-images.githubusercontent.com/83787952/228086592-ea9afb23-e4d9-48c4-ade7-04b1bf67da65.png)
4. Check VLAN config state
![Screenshot_20230327_160446](https://user-images.githubusercontent.com/83787952/228086609-8611d63b-a134-4909-86cc-f168e58f528b.png)
