### ISSUE TITLE
[Doc] adjust Longhorn pod CPU reservation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3721]
**Is your enhancement related to a problem? Please describe.**

By default, Longhorn [requests 12% of node CPU](https://longhorn.io/docs/1.3.2/references/settings/#guaranteed-engine-manager-cpu) for the instance-manager-e and instance-manage-r pods.
For some use cases (line single node with only a few volumes), the reservation might be too much.

**Describe the solution you'd like**

A guideline or feature to configure the reservation.
Note, the value can't be changed when the engine pod or replica pod is in use; the pods will be restarted and disrupts volumes' I/O.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
document PR https://github.com/harvester/docs/pull/301 was merged, and is available at Harvester doc: https://docs.harvesterhci.io/dev/install/harvester-configuration/#installharvesterstorage_classreplica_count, close issue.
