### ISSUE TITLE
[Question] IAM solutions integrated to Harvester?

### ISSUE THREAD

**Issue by mohaa7** [harvester/harvester#3722]
To manage users and resource quota, is there any Identity and Access Management (IAM) solution for Harvester?

**Comment by masteryyh** [comment]
Hi @mohaa7
If you are simply using Harvester itself there is no such thing, but you can use Rancher to integrate with Harvester cluster to provide user and resource management.

**Comment by mohaa7** [comment]
I was doing R&D on KeyCloak. If there's an integrity with Rancher, well, I'll check it. Thanks

**Comment by ibrokethecloud** [comment]
hope this helps: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/authentication-config/configure-keycloak-oidc
