### ISSUE TITLE
[BUG] Upgrade the four nodes airgapped Harvester stop with context deadline exceeded error

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3729]
**Describe the bug**

When upgrade the 4 nodes airgapped Harvester cluster from v1.1.1 to v1.1.2-rc4
After Download Upgrade Image complete and enter `Creating Upgrade Repository` stage

The upgrade process stopped with error
```
Get "http://upgrade-repo-hvst-upgrade-mldzx.harvester-system/harvester-iso/harvester-release.yaml": 
context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```

![image](https://user-images.githubusercontent.com/29251855/228260746-ffed74e1-2645-4f07-8687-21ca256f2a08.png)

**To Reproduce**
1. Use ipxe-example to provision an airgapped four nodes `v1.1.1` Harvester cluster 
2. After cluster ready, vagrant ssh to pxe_server
3. Setup vlan network to the dhcpd service of pxe_server 
4. Install and setup nfs server on pxe_server
5. Create the vlan1 network on management interface of Harvester
6. Create a new cluster network and related network config 
7. Create a vlan network 101 with manual route 
8. Create three images from File
9. Create three virtual machines separate on each node 
10. Backup each virtual machine 
11. Get harvester v1.1.2-rc4 iso file on pxe_server 
12. Perform offline upgrade to `v1.1.2-rc4` 

**Expected behavior**

Should be able to complete all upgrade process without error

**Support bundle**

[supportbundle_143ea7c3-25c1-4d61-8f42-c4ff10856943_2023-03-28T14-08-57Z.zip](https://github.com/harvester/harvester/files/11090437/supportbundle_143ea7c3-25c1-4d61-8f42-c4ff10856943_2023-03-28T14-08-57Z.zip)

**Environment**
 - Harvester ISO version: v1.1.1 to v1.1.2-rc4
 - Underlying Infrastructure: 4 nodes Harvester on local kvm machines

**Additional context**
* Nodes resource usage 
![image](https://user-images.githubusercontent.com/29251855/228264867-937835da-1954-463e-a497-26eacde084d9.png)

**Comment by bk201** [comment]
Same issue as https://github.com/harvester/harvester/issues/3550 and fix in https://github.com/harvester/harvester/pull/3593. For v1.1.1 clusters, the workaround is to [start the upgrade again](https://docs.harvesterhci.io/v1.1/upgrade/troubleshooting#start-over-an-upgrade).

**Comment by TachunLin** [comment]
After delete the upgrade and [start the upgrade again](https://docs.harvesterhci.io/v1.1/upgrade/troubleshooting#start-over-an-upgrade). 

This time we can proceed the creating upgrade repository stage and completely upgrade to v1.1.2-rc4

![image](https://user-images.githubusercontent.com/29251855/228513762-0b15d82f-023a-4005-a84a-5de96e802211.png)

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/3550
