### ISSUE TITLE
[BUG] install failed, chart not found, harvester os

### ISSUE THREAD

**Issue by ekristen** [harvester/harvester#373]
**Describe the bug**

Installed the OS on reboot the console indicated that harvester was setting things up. Never left this state.

After SSH-ing in (which my SSH key did not work) it seems the batch job responsible for installing harvester failed not being able to find the helm chart locally? 

**To Reproduce**
1. Install Harvester OS
2. ...

**Expected behavior**

**Log**

```
+ helm_v3 install --namespace harvester-system --set-string containers.apiserver.authMode=localUser --set-string containers.apiserver.image.imagePullPolicy=IfNotPresent --set-string harvester-network-controller.image.pullPolicy=IfNotPresent --set longhorn.enabled=true --set-string minio.persistence.storageClass=longhorn --set multus.enabled=true --set-string service.harvester.type=LoadBalancer harvester https://10.43.0.1:443/static/charts/harvester-0.1.0.tgz
Error: failed to download "https://10.43.0.1:443/static/charts/harvester-0.1.0.tgz" (hint: running `helm repo update` may help)
```

**Environment:**
 - Harvester ISO version: 0.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with HP Proliant ML350P G8

**Additional context**

**Comment by gitlawr** [comment]
Can you run the following to see if the chart file is present?
```
ls /var/lib/rancher/k3s/server/static/charts/
```

**Comment by ekristen** [comment]
Unfortunately no I cannot, next time I install it, I can check again.

**Comment by guangbochen** [comment]
closed due to inactivity, and now the helm chart is marked as dev mode only.
