### ISSUE TITLE
[BUG] After Upgrade From 3 Node AirGapped v1.1.0->v1.1.2-rc4 Rancher v2.6.11 Virtualization Management Complains `cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.53.0.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded`

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3731]
**Describe the bug**
Rancher v2.6.11, that had imported airgapped 3 node cluster of v1.1.0 - prior to upgrade to v1.1.2-rc4 no issues - post upgrade error on Virtualization Cluster of:
```
cluster health check failed: Failed to communicate with API server during namespace check: Get "https://10.53.0.1:443/api/v1/namespaces/kube-system?timeout=45s": context deadline exceeded 
```
Though, when you click into the cluster, you can view it eventually and interact with it.
Controlling VMs etc.

**To Reproduce**
1. 3 node airgap v1.1.0 integrated with v2.6.11 Rancher - upgrade to v1.1.2-rc4
1. After Upgrade, from Rancher v2.6.11, error is displayed.
1. Can click the Harvester cluster and then be dropped into cluster management however

**Expected behavior**
There not to be an error displayed.
When the interaction with the cluster from the Rancher v2.6.11 GUI seems to work.

**Support bundle**
[supportbundle_5b973679-4d7f-4f84-9ff0-f4ed114ff03c_2023-03-28T23-32-32Z.zip](https://github.com/harvester/harvester/files/11095194/supportbundle_5b973679-4d7f-4f84-9ff0-f4ed114ff03c_2023-03-28T23-32-32Z.zip)

**Environment**
 - Harvester ISO version: v1.1.0->v1.1.2-rc4
 - Underlying Infrastructure: qemu/kvm

**Additional context**
![Screenshot from 2023-03-28 16-31-48](https://user-images.githubusercontent.com/5370752/228390363-cf554b88-2e74-486f-8f28-06bd714873c1.png)
![Screenshot from 2023-03-28 16-31-12](https://user-images.githubusercontent.com/5370752/228390365-69002d73-660d-4d3f-b2c9-c2698bfd12de.png)
![Screenshot from 2023-03-28 16-29-20](https://user-images.githubusercontent.com/5370752/228390367-a0853723-2e3d-4ca0-9de4-dac3ab3cf922.png)
![Screenshot from 2023-03-28 16-27-44](https://user-images.githubusercontent.com/5370752/228390368-ed85329d-1ca6-4875-aa5b-9a7af79510a5.png)
![Screenshot from 2023-03-28 16-20-42](https://user-images.githubusercontent.com/5370752/228390369-384179c5-1b7f-464f-9521-22a0fd4c40e6.png)

All managed charts & bundle seems ready:
```

# Run kubectl commands inside here
# e.g. kubectl get all
> kubectl get bundle -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 1/1                       
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   1/1                       
fleet-local   mcc-rancher-logging                           1/1                       
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring                        1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1                       
> kubectl get managedcharts -A
NAMESPACE     NAME                                      AGE
fleet-local   harvester                                 16h
fleet-local   harvester-crd                             16h
fleet-local   local-managed-system-upgrade-controller   16h
fleet-local   rancher-logging                           16h
fleet-local   rancher-logging-crd                       16h
fleet-local   rancher-monitoring                        16h
fleet-local   rancher-monitoring-crd                    16h
```

**Additional**

It seems to be in a loop pulling running destroying `rancher/rancher-agent` from the myregistry.local:5000 Docker Registry.

![Screenshot from 2023-03-28 16-49-48](https://user-images.githubusercontent.com/5370752/228392023-29946ff9-54fb-4758-b79f-c47b420251d4.png)
![Screenshot from 2023-03-28 16-49-14](https://user-images.githubusercontent.com/5370752/228392025-eb2757ae-37d0-45da-88c5-3a1ddd655915.png)

**Comment by khushboo-rancher** [comment]
Is it intermittent issue?

**Comment by irishgordo** [comment]
@khushboo-rancher I updated to reproduce/rare as this just might be related to the problems with the provisioning in all things virtualized

**Comment by irishgordo** [comment]
This also wasn't noticed significantly with rc3 - so this could be intermittent - or even related to the underlying hardware storage

**Comment by irishgordo** [comment]
Previously, prior to upgrade - there weren't any issues with `cattle-cluster-agent`.
![Screenshot from 2023-03-28 12-39-21](https://user-images.githubusercontent.com/5370752/228394522-e5b63424-ec92-4bd1-ac8e-eef149ceb9a5.png)
![Screenshot from 2023-03-28 12-37-11](https://user-images.githubusercontent.com/5370752/228394525-c8cbb330-470e-4d7b-91be-911e180f406a.png)
![Screenshot from 2023-03-28 12-03-55](https://user-images.githubusercontent.com/5370752/228394526-daf59d5f-f88f-4bf9-bec0-0c8ad7bd3d0e.png)
![Screenshot from 2023-03-28 12-00-22](https://user-images.githubusercontent.com/5370752/228394527-8cca38da-2d13-4148-b3a5-a933d4d85dd0.png)
![Screenshot from 2023-03-28 11-44-23](https://user-images.githubusercontent.com/5370752/228394528-9e15c3e1-7a3d-4e8d-84b4-a9b2e6f27c33.png)
![Screenshot from 2023-03-28 11-40-49](https://user-images.githubusercontent.com/5370752/228394530-ec8f4319-343d-47bf-8c04-9851cfd0e482.png)

**Comment by irishgordo** [comment]
dropping the severity from 1->2, as you can still leverage that from the virtualization management page, click in and preform work, though the error message is present...

Example video:


https://user-images.githubusercontent.com/5370752/228397426-f38ead3b-83b7-4fae-8eb4-1fd555c57e5c.mp4

**Comment by FrankYang0529** [comment]
The `cattle-cluster-agent` deployment can't resolve `rancher-vagrant-vm.local`, so Rancher can't do health check. I update  `kube-system/rke2-coredns-rke2-coredns` configmap with following content and add `customdomains.db` to `kube-system/rke2-coredns-rke2-coredns` deployment. Finally, the health check can work.

```
data:
  Corefile: ".:53 {\n    errors \n    health  {\n        lameduck 5s\n    }\n    ready
    \n    kubernetes   cluster.local  cluster.local in-addr.arpa ip6.arpa {\n        pods
    insecure\n        fallthrough in-addr.arpa ip6.arpa\n        ttl 30\n    }\n    prometheus
    \  0.0.0.0:9153\n   hosts /etc/coredns/customdomains.db rancher-vagrant-vm.local
    {\n    fallthrough\n    }\n forward   . /etc/resolv.conf\n    cache   30\n    loop
    \n    reload \n    loadbalance \n}"
  customdomains.db: 192.168.2.34 rancher-vagrant-vm.local
```
![Screenshot 2023-03-29 at 10 38 46 AM](https://user-images.githubusercontent.com/4927361/228412300-c89e4b7d-aca2-4755-9e80-a23e34a65773.png)

**Comment by irishgordo** [comment]
Thanks for checking that @FrankYang0529 - since this is just tied to the dns, and everything else looks good I'll go ahead and close this out :smile: :+1:
