### ISSUE TITLE
[FEATURE] Add helm-chart tgz to releases

### ISSUE THREAD

**Issue by ekristen** [harvester/harvester#374]
I think it would be beneficial to package up the helm release and add it to the releases alongside the iso for easier download and reference.

Specifically related to https://github.com/rancher/harvester/issues/373 if it was published I could quickly fix the helm chart install.

**Comment by chifu1234** [comment]
... and adding it to https://releases.rancher.com/server-charts/latest

**Comment by yasker** [comment]
Close as stale. Feel free to reopen if needed.
