### ISSUE TITLE
[BUG] After the weekend, VM on one node can't connect to outside network 

### ISSUE THREAD

**Issue by delongdk** [harvester/harvester#3745]
**Describe the bug**

We have a working cluster created by the following steps
1. A three node cluster (pros-a、pros-b、pros-c). 
2. Configure a cluster network called 'pros-net' using web UI with bonding using active-backup and two 1Gbe interfaces. 
3. Create a vlan VM networks on top of cluster network 
4. Create static IP VM by cloud-init script, using the VM networks above 

It works well since Feb. 14.  
After a weekend (Mar. 27), we found all VM working on node 'pros-c' can't connect to outside network, but the node network is fine. 
After a lengthy adjustment process, we restored the network (Mar. 29). Until Friday of that week (Mar. 31) it seemed to be working fine.
Similarly, after the weekend(Apr. 03), all VM working on node 'pros-b' can't connect to outside network.....

At the time, I caught the ARP broadcast via tcpdump, the broadcast link looks like this

* ping from vm working on node 'pros-a' to vm working on node 'pros-b'

![image](https://user-images.githubusercontent.com/30656093/229436871-47f9c492-41e4-46cc-9fce-04c7d278c6a1.png)

* ping from vm working on node 'pros-b' to vm working on node 'pros-a'

![image](https://user-images.githubusercontent.com/30656093/229436948-988cfa3b-fa34-4ad4-8070-0b68c9ef5f4f.png)

This time we just reconnect the network cable of node 'pros-b' to the switch, then the network recovered.

We are very confused about why this happened, could you please help analyze where the problem is occurring?

**To Reproduce**
No idea.

**Expected behavior**

VM networks should be stable.

**Support bundle**

[supportbundle_1dfc0125-2b6a-43f3-ba7b-9c40974583b6_2023-04-03T06-02-55Zｚ.zip](https://github.com/harvester/harvester/files/11135807/supportbundle_1dfc0125-2b6a-43f3-ba7b-9c40974583b6_2023-04-03T06-02-55Z.zip)

**Environment**
* Harvester V1.1.1
* 3 nodes
* management network, 2*10Gbe devices: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 02)
* cluster network, 2*1Gbe devices: Intel Corporation I350 Gigabit Network Connection (rev 01)
* Static Nodes IP - Static VIP
* Static VM IP

**Additional context**

**Comment by starbops** [comment]
Hi @delongdk, the broadcast packet didn't arrive at `ens25f0` from the first graph you attached in the description. And from the second graph, it looks like the ARP request didn't even receive by the switch. In summary, the switch port which connected to pros-b's `ens25f0` could be disabled by some switch mechanisms like STP. Could you help check the status of the switch port and also the switch config?

From the support bundle, we observed there are link-flapping issues:

```
Mar 31 16:41:58 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered disabled state
Mar 31 16:41:58 pros-b kernel: device pros-net-bo left promiscuous mode
Mar 31 16:41:58 pros-b kernel: device ens25f0 left promiscuous mode
Mar 31 16:41:58 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered disabled state
Mar 31 16:41:58 pros-b kernel: pros-net-bo (unregistering): (slave ens25f0): Releasing backup in
terface
Mar 31 16:41:58 pros-b kernel: pros-net-bo (unregistering): (slave ens25f2): Releasing backup in
terface
Mar 31 16:41:58 pros-b kernel: pros-net-bo (unregistering): Released all slaves
Mar 31 16:41:59 pros-b kernel: pros-net-bo: (slave ens25f0): making interface the new active one
Mar 31 16:41:59 pros-b kernel: pros-net-bo: (slave ens25f0): Enslaving as an active interface wi
th an up link
Mar 31 16:41:59 pros-b kernel: pros-net-bo: (slave ens25f2): Enslaving as a backup interface wit
h an up link
Mar 31 16:41:59 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered blocking state
Mar 31 16:41:59 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered disabled state
Mar 31 16:41:59 pros-b kernel: device pros-net-bo entered promiscuous mode
Mar 31 16:41:59 pros-b kernel: device ens25f0 entered promiscuous mode
Mar 31 16:41:59 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered blocking state
Mar 31 16:41:59 pros-b kernel: pros-net-br: port 1(pros-net-bo) entered forwarding state
Mar 31 16:42:02 pros-b kernel: igb 0000:ca:00.0 ens25f0: igb: ens25f0 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX/TX
Mar 31 16:42:02 pros-b kernel: igb 0000:ca:00.2 ens25f2: igb: ens25f2 NIC Link is Up 1000 Mbps Full Duplex, Flow Control: RX
```

And the interval between the flapping events is about 10 hours, quite the same as #3744.

cc @yaocw2020

**Comment by delongdk** [comment]
Thank you very much for your reply @starbops .

All NICs of our nodes are connected to the same switch. All the switch ports is working in `access` mode and configed same vlan ID with given vm network which based `pros-net`.  We confirmed that switch STP is up, but the switch status and relevant logs at that time were no longer present. We are going to investigate this information when this problem occurs again (but not sure when and if it will happen).

When the previous event occurred, we adjusted the switch port type to `trunk` mode as the [instructions](https://docs.harvesterhci.io/v1.1/networking/deep-dive/#external-networking), but it seems that the problem has not been resolved, and we recoverd it to `access` type.

During the problem, the VM on the node could not be connected through the cluster network `pros-net`, but could be accessed through the web console, so it proves that management network `mgmt` was working well and we noticed that management network does not arise flapping.

So do you tend to believe that this problem is caused by the flapping?

**Comment by delongdk** [comment]
This problem was reproduced. 

A Harvester node experienced link-flapping at 04:24 on Apr. 27, and as a result, all VMs on this node lost external network connection. We checked the switch ports and did not find any STP loops. 

The network was restored by reconnect the network cable.

So what should we do next. Does this mean we have to wait for the release of the v1.2.0 version and then upgrade Harvester?

**Comment by starbops** [comment]
Hi @delongdk, sorry for the late reply. The problem here is slightly different from what we saw on #3744. But the link-flapping did happen and might trigger the later network outage. If possible, we suggest upgrading to v1.1.2 which the flapping issue was fixed, and observing whether the problem happens again. Thank you.

**Comment by delongdk** [comment]
Currently there seems to be no other way. We are evaluating the risk of upgrading. Thank you.

**Comment by w13915984028** [comment]
@delongdk As this issue has difference with #3744. We can check further:

Is your management network also VLAN based?
What is the `Create a vlan VM networks on top of cluster network`  VM VLAN network VLAN ID?

From your diagram, the network is 10.0.92.0/23, the IP range is 10.0.92.1~10.0.93.254. It looks, your VLAN IP segment is same as management IP segment. If it is true, then you may hit this issue: https://github.com/harvester/harvester/issues/3414.

**Comment by w13915984028** [comment]
You cannot put VM network and management network in same IP segment, unless you use VLAN 1.

VM network -> management network works, as MAC address happens to be in ARP table.
VM network -> management network does not work, as MAC address is aged out from ARP table, and the MAC broadcast won't cross different VLAN.

**Comment by w13915984028** [comment]
connect https://github.com/harvester/harvester/issues/3852, similar scenario

**Comment by delongdk** [comment]
> @delongdk As this issue has difference with #3744. We can check further:
> 
> Is your management network also VLAN based? What is the `Create a vlan VM networks on top of cluster network` VM VLAN network VLAN ID?
> 
> From your diagram, the network is 10.0.92.0/23, the IP range is 10.0.92.1~10.0.93.254. It looks, your VLAN IP segment is same as management IP segment. If it is true, then you may hit this issue: #3414.

The configurations mentioned here as follows.

Cluster network called `pros-net`.
![image](https://github.com/harvester/harvester/assets/30656093/090db746-a4fc-47c3-94d0-672d796e4a50)

Host IP segment `10.0.92.0/23`, IPs as follow.
![image](https://github.com/harvester/harvester/assets/30656093/8495c97f-3827-40d4-868c-c1f2cff44c9e)

Network config.
![image](https://github.com/harvester/harvester/assets/30656093/9d6eebcf-029b-413e-96b7-c80c0b2cb5c5)

VM network called `pros-vlan-net` based cluster network `pros-net`.
![image](https://github.com/harvester/harvester/assets/30656093/231cd109-e504-4b3a-87a4-7da5f72ab36c)

DHCP but without server.
![image](https://github.com/harvester/harvester/assets/30656093/01766f77-b1b8-4f60-a46a-7e06e7e8edd5)

VM network config.
![image](https://github.com/harvester/harvester/assets/30656093/639a699f-c447-467d-bc6d-c1ae0565c266)

VM setup a static IP.
![image](https://github.com/harvester/harvester/assets/30656093/42d5a548-c641-4863-926b-c5bf2f982478)

IP configuration shows.

Host 
```
pros-a:/home/rancher # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: ens27f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP group default qlen 1000
    link/ether 9c:c2:c4:2b:7a:30 brd ff:ff:ff:ff:ff:ff
    altname enp203s0f0
3: ens27f1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP group default qlen 1000
    link/ether 9c:c2:c4:2b:7a:30 brd ff:ff:ff:ff:ff:ff
    altname enp203s0f1
4: ens25f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master pros-net-bo state UP group default qlen 1000
    link/ether 9c:c2:c4:28:07:47 brd ff:ff:ff:ff:ff:ff
    altname enp202s0f0
5: ens25f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 9c:c2:c4:28:07:48 brd ff:ff:ff:ff:ff:ff
    altname enp202s0f1
6: ens25f2: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master pros-net-bo state UP group default qlen 1000
    link/ether 9c:c2:c4:28:07:47 brd ff:ff:ff:ff:ff:ff
    altname enp202s0f2
7: ens25f3: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether 9c:c2:c4:28:07:4a brd ff:ff:ff:ff:ff:ff
    altname enp202s0f3
8: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 9c:c2:c4:2b:7a:30 brd ff:ff:ff:ff:ff:ff
    inet 10.0.92.1/23 brd 10.0.93.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
    inet 10.0.92.4/32 scope global mgmt-br
       valid_lft forever preferred_lft forever
9: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP group default qlen 1000
    link/ether 9c:c2:c4:2b:7a:30 brd ff:ff:ff:ff:ff:ff
10: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default
    link/ether be:14:ac:54:35:3f brd ff:ff:ff:ff:ff:ff
    inet 10.52.0.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
26: pros-net-br: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN group default
    link/ether 02:52:17:37:27:a4 brd ff:ff:ff:ff:ff:ff
2185: pros-net-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master pros-net-br state UP group default qlen 1000
    link/ether 9c:c2:c4:28:07:47 brd ff:ff:ff:ff:ff:ff
```
```shell
pros-a:/home/rancher # bridge -c vlan show
port    vlan ids
mgmt-br  1 PVID Egress Untagged
         2-4094
mgmt-bo  1 PVID Egress Untagged
         2-4094
pros-net-br      1 PVID Egress Untagged
pros-net-bo      1 PVID Egress Untagged
         92
```

VM 
```shell
[root@test-oracle centos]# ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 4e:98:a1:6e:4b:b5 brd ff:ff:ff:ff:ff:ff
    inet 10.0.92.209/23 brd 10.0.93.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::4c98:a1ff:fe6e:4bb5/64 scope link
       valid_lft forever preferred_lft forever
```

As #3414 and #3852 said, VM network and host network in same IP segment should hit network issus. 

But  in our cluster the fact is, the network connection of the VM created according to the above configuration is normal, and only during a certain flapping as #3744 said will triggered something that caused the VM on a node to lose network connectivity.

**Comment by w13915984028** [comment]
@delongdk When you break the general rule of VLAN/IP setting, it may happen to work (depends on the switch and others), but there may be various kinds of issues, you need to spend time to troubleshooting and it is difficult to get answer quickly.

If you still want to continue, then, check the arp tables in your switch and server side, tcudump the related packet, notice their VLAN ID;  when network is un-reachable, do them again.

I would suggest plan&config the VLAN/IP/router correctly at first. thanks.

**Comment by delongdk** [comment]
I understand what you mean. Thank you very much for your help.

**Comment by iosifnicolae2** [comment]
> You cannot put VM network and management network in same IP segment, unless you use VLAN 1.
> 
> VM network -> management network works, as MAC address happens to be in ARP table. VM network -> management network does not work, as MAC address is aged out from ARP table, and the MAC broadcast won't cross different VLAN.

@w13915984028  I suggest to include this observation in Harvester UI (I spent a lot of time trying to debug why I had a lot of problems in VMs because I was using VLAN 2 on mgmt network).

Thank you!

**Comment by w13915984028** [comment]
Issue solved, close.
