### ISSUE TITLE
[BUG] [UI] unable to login to the UI with any credentials

### ISSUE THREAD

**Issue by ekristen** [harvester/harvester#375]
**Describe the bug**

I was unable to login to the harvester ui with any sort of credentials that I set or would be assumed to be default.

**To Reproduce**
1. Install Harvester OS

**Expected behavior**
Be Able to login

**Log**
401 Unauthorized

**Environment:**
 - Harvester ISO version: 0.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HP Proliant ML350P G8

**Additional context**

**Comment by aredan** [comment]
user: admin
pass:  password

https://github.com/rancher/harvester/blob/master/docs/authentication.md

Did you tested that ?

**Comment by ekristen** [comment]
I thought I tried that combo, but I'd rather assume user-error than 0.1.0 shipped with a busted login, I already reset the account, I'll have to re-install later and try again.
