### ISSUE TITLE
[BUG] After you delete the cluster network and network configuration, you can no longer select the released NIC

### ISSUE THREAD

**Issue by techstudio-project** [harvester/harvester#3755]
**Describe the bug**
After you delete the cluster network and network configuration, you can no longer select the released NIC

**To Reproduce**
1.Create a cluster network
2.Create a network configuration
3.Select an available NIC , Created successfully
4. then delete the cluster network and network configuration
5. Repeat step 123, but the previously available NIC is grayed out and cannot be selected

**Expected behavior**
After deletion, I can select it again

**Environment**
 - Harvester ISO version:  1.1.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by starbops** [comment]
Hi @techstudio-project, as a workaround, could you please try bringing up the interface manually and creating the "cluster network" and "network config" again?

It seems the network controller only set no master for the uplink interface while removing Vlanconfig. The interface becomes "down," so the UI grays out the option.

@yaocw2020 could provide more insight on this. Thanks.

**Comment by yaocw2020** [comment]
Duplicated with https://github.com/harvester/harvester/issues/3166. Close it.
