### ISSUE TITLE
Harvester 1.1.2 [Question]

### ISSUE THREAD

**Issue by Aixleft723** [harvester/harvester#3768]
When will harvester 1.1.2 be released?

**Comment by guangbochen** [comment]
most likely, it will be on the next Tuesday 04/18, thanks.

**Comment by Aixleft723** [comment]
@guangbochen  in 1.1.2 the sriov function will be released?

**Comment by noahgildersleeve** [comment]
That's currently scheduled for v1.2.0 as far as I'm aware. Here's the [feature ticket](https://github.com/harvester/harvester/issues/2763) for it for reference.

**Comment by Aixleft723** [comment]
Ok, I misunderstood the relationship between 1.1.2 and 1.2.0... ,When will 1.2.0 be released?

**Comment by RegisWeduLabs** [comment]
It seems to be scheduled for May 30th.  You can check the milestones here:
https://github.com/harvester/harvester/milestones

**Comment by w13915984028** [comment]
Please refer https://github.com/harvester/harvester/releases/tag/v1.1.2 to get it.
