### ISSUE TITLE
[Question] How many NIC per node?

### ISSUE THREAD

**Issue by aredan** [harvester/harvester#377]
I know that more NIC is better, but what about a homelab with Intel NUCs for testing or daily usage. The majority of NUCs have just one NIC, I have two of those and want to migrate them from VMware to Harvester as soon as the platform gets more stable.

 The hardware requirements don't list how many NICs are needed.

**Comment by yaocw2020** [comment]
Harvester can work with only one NIC, but It's better to have at least 2 NICs, one for manager network, the other for VLAN.

**Comment by worm-za** [comment]
Will the 2 NICs be able to be backup for the other?

**Comment by guangbochen** [comment]
from v0.3.0 now users can use the bond NIC if they want to provide fault-tolerant or fail-over of NICs.
https://docs.harvesterhci.io/v0.3/install/pxe-boot-install/#create-mode
