### ISSUE TITLE
[BUG] No Management NIC selectable upon installing from ISO

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#3770]
Describe the bug
It is not possible to select a Management NIC interface, there's no selection available, the field is just empty.

Expected behavior
Management NIC interfaces should be visible

**Environment**
 - Harvester ISO version: 1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HPE Cloudline CL3100 G3 Server

**Additional context**
Tried TAB already as mentioned in https://github.com/harvester/harvester/issues/1581 and https://github.com/harvester/harvester/issues/3207, but the popup is empty.

<img width="397" alt="image" src="https://user-images.githubusercontent.com/13354331/231888542-ac83b4ea-af0b-43f3-bc72-0d19d5072a3c.png">

May be related to https://github.com/harvester/harvester/issues/2708 or https://github.com/harvester/harvester/issues/3081

**Comment by w13915984028** [comment]
@xeruf 

Please try `F2, or alt+F2 or ctrl+F2` to switch to Linux shell in the step of selecting network, it maybe that your network card is not loaded correctly in this step.

when it is in shell, try `rancher/rancher` to login into shell, then `sudo -i`,  `ip link` to show show devices

![image](https://user-images.githubusercontent.com/31133476/231997923-b2c83fc4-24bf-4155-a48f-2776c823e7cc.png)

switch to shell
![image](https://user-images.githubusercontent.com/31133476/231996799-bcb9de71-217c-4b1d-a45b-139e2e4043ec.png)

normally, the loadded nics are selectable in the install GUI.

**Comment by agustaf9** [comment]
I am having the same issue using an ASUS Pro WS W680-ACE motherboard. No devices show when running `ip link`

**Comment by w13915984028** [comment]
@bk201 
Per @agustaf9 's description, the `dual Intel® 2.5Gb Ethernet` are not loaded by the OS, do you know any workarounds ?

https://www.asus.com/motherboards-components/motherboards/workstation/pro-ws-w680-ace/

> Next-gen connectivity: Dual PCIe 5.0 SafeSlots, dual PCIe 3.0 slots, 3 x M.2 PCIe 4.0, SlimSAS, dual Intel® 2.5Gb Ethernet, front panel USB 3.2 Gen2x2 Type-C®, Thunderbolt™ 4 header support, TPM header, LPT header

**Comment by xeruf** [comment]
Alt-F2 did it, but nothing there:
![image](https://user-images.githubusercontent.com/13354331/233200759-7f4a8774-4e0e-46cf-929b-68e983452ec9.png)

Model Info:
https://support.hpe.com/hpesc/public/docDisplay?docLocale=en_US&docId=c05352944
OCP Mezzanine connector

Interestingly the latest Debian does not seem to recognize it either, but the networking does work from the BMC/IPMI, hmm...

We want to foster sustainability by reviving such hardware, and also have a first peek into the SUSE world, thought Harvester looks awesome for this, so some assistance could earn a loyal customer ;P

**Comment by w13915984028** [comment]
@xeruf Could you try to download sle15 sp3/sp4 and install on this server, then we can know if the network nic can be installed correctly and what is the right diver for it. thanks.

https://www.suse.com/download/sles/

BTW, guess the BMC/IPMI can work with the network card, as they have already included related drivers.

**Comment by bk201** [comment]
Hy @xeruf, could you provide the output of `lspci -v ` and the log of `dmesg`. Thank you.

**Comment by agustaf9** [comment]
> I am having the same issue using an ASUS Pro WS W680-ACE motherboard. No devices show when running `ip link`

Works fine in V1.1.2-rc8

**Comment by xeruf** [comment]
We found the issue: The BMC has its own network card, but the machine itself was actually delivered without network card.
Will reopen in case this surfaces again.
