### ISSUE TITLE
[Question] Installing via helm chart "ManagedChart" CRD isn't installed?

### ISSUE THREAD

**Issue by ScionOfDesign** [harvester/harvester#3777]
I have been trying to get Rancher installed via the provided helm chart. Everything seems to spin up and start running, but the following error always occurs and the primary Harvester pod seems to get stuck in a reboot loop (and I am not able to access the dashboard).
```reflector.go:324] github.com/rancher/lasso/pkg/cache/cache.go:145: failed to list *v3.ManagedChart: the server could not find the requested resource (get managedcharts.meta.k8s.io```

In versions `v1.0.0`-`v1.0.3` this error occurs in the Harvester pod.
In versions `v1.1.0`-`v1.1.2-rc7` this error occurs in the Harvester-Webhook pod, and the Harvester pod simply says `Waiting for ValidatingWebhookConfiguration harvester-validator...` until it restarts.

I followed the instructions and:
1. Installed Multus CNI `v3.9.3`
2. Installed the corresponding `harvester-crd` chart.
3. Installed the `harvester` helm chart with minimal modifications. Only reducing the `replicas` to 1 and disabling longhorn (as I already have it installed).

This is a Rancher-created RKE2 cluster.

Am I doing something wrong or is this an issue with the helm chart? Where can I find the `ManagedChart` CRD (if that is the blocking issue)?
Harvester seemed awesome when I demoed it, and I really would like to be able to install Harvester as an app on our clusters, instead of needing to use the whole OS.

**Comment by w13915984028** [comment]
@ScionOfDesign 

Before v1.0.0, Harvester supports `dev` mode, installed via helm in k8s clusters.

From v1.0.0, the `dev` mode is no longer formally supported. Installation from ISO (GUI/PXE) image is required. thanks.

**Comment by ScionOfDesign** [comment]
This is extremely unfortunate, as we were planning on using Harvester in App mode for quite a few things in the future.
I may continue to investigate getting the helm chart to work, but otherwise, we may be stuck with using raw Kubevirt.
