### ISSUE TITLE
[BUG]UI doesn't show the error message in the status of vm

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3783]
**Describe the bug**

**To Reproduce**
1. Go to create a VM with attatched pcidevice at v1.1.1.
2. Upgrade v1.1.1 to v1.1.2.
3. Clone the VM and go to start at v1.1.2.
4. The error message in the status of VM should be visible in VM's yaml

**Expected behavior**

The table cell of VM should display the error message.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
There is no way to reproduce it, the error message is displayed normally. 
<img width="1378" alt="image" src="https://github.com/harvester/harvester/assets/24985926/04903524-e3f9-4749-8dff-6314fa6c6377">
