### ISSUE TITLE
[Question] Restart Button Web VNC window

### ISSUE THREAD

**Issue by tinohager** [harvester/harvester#379]
Today we have tested the 0.1 release of harvester.
Is it possible to implement a restart button in the Web VNC window?

**Comment by TachunLin** [comment]
Verified **fixed** on `master-949bbb0c-head` (06/25). Close this issue.

### Result
Verified the soft reboot keys can display and reboot correctly on Linux OS VM (Ubuntu desktop 20.04)
![image](https://user-images.githubusercontent.com/29251855/177100026-e67d0101-0a5b-433c-b9ab-e2b4af1a8d0f.png)


### Test Information
* Test Environment: 1 node harvester on local kvm machine
* Harvester version: master-949bbb0c-head
* os image: ubuntu-20.04.4-desktop-amd64.iso

### Verify Steps
1. Create a new VM with Ubuntu desktop 20.04 
2. Prepare two volume
3. Complete the installation process
4. Open a web browser on Ubuntu desktop
5. Check the shortcut keys combination
