### ISSUE TITLE
Maximum CPUs greater than specified machine type limit 288[Question]

### ISSUE THREAD

**Issue by dseralathan** [harvester/harvester#3790]
When we try to create a 512C VM  the pod showing below error  "Maximum CPUs greater than specified machine type limit 288"

Is this the limit or how Harvester works in limit for VM CPU 

{"component":"virt-launcher","level":"error","msg":"unsupported configuration: Maximum CPUs greater than specified machine type limit 288","pos":"qemuValidateDomainVCpuTopology:659","subcomponent":"libvirt","thread":"31","timestamp":"2023-04-18T22:25:41.515000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"test","namespace":"default","pos":"libvirt_helper.go:133","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: Maximum CPUs greater than specified machine type limit 288')","timestamp":"2023-04-18T22:25:41.516191Z","uid":"99799888-e16b-4a11-be2b-3ee65e8f0ebd"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"test","namespace":"default","pos":"server.go:184","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: Maximum CPUs greater than specified machine type limit 288')","timestamp":"2023-04-18T22:25:41.516242Z","uid":"99799888-e16b-4a11-be2b-3ee65e8f0ebd"}

**Comment by FrankYang0529** [comment]
Probably, the limitation is from libvirt.

https://github.com/libvirt/libvirt/blob/master/docs/formatcaps.rst

**Comment by dseralathan** [comment]
thanks
