### ISSUE TITLE
[Doc] Add instruction to add container disk in virtual machine volume page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3791]
**Is your doc request related to a problem? Please describe or add related issue ID.**
Currently on Harvester document https://docs.harvesterhci.io/v1.1/vm/create-vm#volumes
We not yet have more precise instruction for how to add a container image as a volume in the virtual machine volume page. 

If user trying to add a container disk to virtual machine but provide the unsupported image format. 
It would cause the virtual machine keep in `Running` state with event error

![image](https://user-images.githubusercontent.com/29251855/233023706-70083543-7aa5-4ab2-bb86-8cda292f8bc3.png)

![image](https://user-images.githubusercontent.com/29251855/233020561-d5e2d17b-6688-4897-97df-9467d134806e.png)

**Describe the solution you'd like**

1. Suggest we can provide more information about how to add container disk in volume. 
2. Provide the following URL to reader indicating how to build up the supported image  
https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#custom-disk-image-path
3. Given a working example [registry.suse.com/suse/vmdp/vmdp](http://registry.suse.com/suse/vmdp/vmdp)
4. The requirement to build up image e.g
    - image should contain the directory `/disk`
    - `/disk` directory should contain only `qcow2` and `ISO` file type

**Comment by bk201** [comment]
@LucasSaintarbor Please see if you can help on this one. The container image needs to follow the rule in the description.

**Comment by bk201** [comment]
Add `require-ui/small.` It would be nice to have a link to the doc if the user selects container disk volumes.
