### ISSUE TITLE
[ENHANCEMENT] Enhance the settings page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3796]
**Is your enhancement related to a problem? Please describe.**

Enhance the settings page. Currently, all settings are grouped together. We hope to categorize them so that users can easily find the settings they need.

![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/5d8cf036-6909-4282-933c-113c59e6c3e3)
**Describe the solution you'd like**

Categorize the settings here according to their different types.

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Tested in `master-942e20a5-head`, verified as done.

## Test Environment
* Harvester
  * version: `master-942e20a5-head`
  * profile: KVM, single node
  * **ui-source**: Auto

## Verification Steps
1. Open Advanced -> Settings :heavy_check_mark:

1. Settgins should be grouped :heavy_check_mark:
   <details>

   Settings are grouped in JS tab with `role="tabpanel"`
   ![grouped_settings](https://github.com/harvester/harvester/assets/2773781/64b7ac23-8443-436b-90d3-cbf821816c7f)
   
   </details>

1. UI can be displayed normally in each groups :heavy_check_mark:
   <details>

   * Settings -> Advanced
   ![advanced_tab](https://github.com/harvester/harvester/assets/2773781/37944484-43a9-4d36-992a-8048ea49c757)
   * Settings -> UI
   ![ui_tab](https://github.com/harvester/harvester/assets/2773781/ce8baffe-1da3-43ab-8a6b-71feea3d0451)

   </details>

## Note
1. Settings are grouped in JS tab with `role="tabpanel"`
2. For now we have **advanced** and **ui** tabs
