### ISSUE TITLE
[BUG] When cloning a VM, an alert message appears on the Volume tab page ('replica scheduling failed').

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3798]
**Describe the bug**

When cloning a VM, an alert message appears on the Volume tab page ('replica scheduling failed').
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/41c76813-0003-404d-9743-6b9914703f9e)

**To Reproduce**
1. go to vm create page
2. fill Name/CPU/Memory
3. click Volume tab:  
    1. select a image
    2. click `Add Volume` button
    3. Exchange the order of two volumes
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/dedb30d9-9d69-47fc-abd4-893568f81a20)
4. Click `Create` button
5. Click this VM，  （not choose `Clone Volume data`）
6.  Click Volume Tab
**Expected behavior**

The alert message should not be displayed when cloning

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-1222750f-head` (04/25). Close this issue.

### Result
When we clone a VM and uncheck the `clone volume data`, in the volume page of clone VM. 
The `replica scheduling failed` message no longer exists
![image](https://user-images.githubusercontent.com/29251855/234211230-e61d0a2e-813a-4488-bb21-758533554ef3.png)


### Test Information
* Test Environment: 1 node Harvester on local kvm machine
* Harvester version: `master-1222750f-head`

### Verify Steps
1. Set the ui-source to `external` in settings and refresh the page
2. Create a VM
3. Add a volume `disk-1` in the VM creation page 
4. Swap the order of `disk-0` and `disk-1`
5. Click the create and wait for VM running
6. Clone the VM
7. Uncheck the `clone volume data` 
8. Check the volume page in clone vm process
