### ISSUE TITLE
[BUG] mcc-harvester bundle contain errApplied status after setting a different default storageClass

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#3802]
**Describe the bug**
the `mcc-harvester` bundle CR will contain an errApplied status after setting a different default storageClass

**To Reproduce**
1. spin up a new harvester cluster with v1.1.2-rc8
2. config a new storage class and set it as a default
3. check the bundle status of `mcc-harvester` later, and it will contain the following errors
```
ks get bundles -n fleet-local
NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-agent-local                             1/1
local-managed-system-agent                    1/1
mcc-harvester                                 0/1                       ErrApplied(1) [Cluster fleet-local/local: cannot patch "harvester-longhorn" with kind StorageClass: admission webhook "validator.harvesterhci.io" denied the request: default storage class %!s(MISSING) already exists, please reset it first]; storageclass.storage.k8s.io harvester-longhorn modified {"metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}
mcc-harvester-crd                             1/1
mcc-local-managed-system-upgrade-controller   1/1
mcc-rancher-logging                           1/1
mcc-rancher-logging-crd                       1/1
mcc-rancher-monitoring                        1/1
mcc-rancher-monitoring-crd                    1/1
```

**Expected behavior**
Fleet bundle should ignore the diff of default storage class since Harvester is allowing to set different default storageClass.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.2-rc8
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in v1.1.2-rc9. Verified as fixed. I reproduced the issue in RC8 and verified it wasn't happening in RC9 after changing default storage class

![image](https://user-images.githubusercontent.com/83787952/233749164-185a6133-9aa0-406f-974d-684d14416440.png)
