### ISSUE TITLE
[BUG] crashed VM id not deleted, when I delete it.

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#3807]
**Describe the bug**
![image](https://user-images.githubusercontent.com/97364807/233573252-cb2c3fb7-f0b5-4887-8097-741a07b0eb5a.png)

**To Reproduce**
1. create a new vm.
2. Disconnect Network-connection form all Servers to replace Switch.
3. see that it cannot start anymore one out of 60 VMs after reconnecting.
4. try to delete the VM. Its marked as delted but it stays ther since nearly 3 days

**Expected behavior**
The VM doesnt crash and if it does. I can at least delete it.

**Environment**
 - Harvester ISO version: 1.1.1

**Comment by w13915984028** [comment]
@ne0YT 
Did you try to get more information then, about the related POD, VMI, VM crd object. (e.g.  `kubectl get virtualmachine -n default/the-name vm-name -oyaml` ,  `kubectl get virtualmachineinstance -n default/the-name vm-name -oyaml`),  or generate a support-bundle file per 
https://docs.harvesterhci.io/v1.1/troubleshooting/harvester/#generate-a-support-bundle . thanks.

**Comment by ne0YT** [comment]
@w13915984028 I was able to remove it by spaming remove using this tool:
https://github.com/harvester/harvester/issues/3807#issuecomment-1542061551

so sadly no, I didnt collect data on it.

**Comment by w13915984028** [comment]
From the descripton, suspect the pending VM deleting may be related to volume detaching/deleting.

Feel free to contact us when it happens again or you recalled something, thanks.
