### ISSUE TITLE
[BUG]  vm affinity rule with vlan network didn't work

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3816]
**Describe the bug**

**To Reproduce**
Create a vm with mgmt network and add a vm affinity rule `topology.kubernetes.io/zone` `In` `zone1`

![image](https://user-images.githubusercontent.com/15064560/233761317-e2d148e9-f17f-4fb3-bb7f-b10896024db6.png)
![1682136255386](https://user-images.githubusercontent.com/15064560/233761347-faaeab62-e37d-46a6-9b65-5cceeeb2effb.png)

**Expected behavior**

The created vm's yaml contains the vm affinity rule

**Actual behavior**
The created vm's yaml doesn't contain the vm affinity rule

![image](https://user-images.githubusercontent.com/15064560/233761503-cf32d1ab-c050-4737-9d48-09a4d61af6ed.png)

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.2-rc8
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
@futuretea  May be  this is a UI bug, and we should add an `area/ui` label ?

**Comment by futuretea** [comment]
@WuJun2016 not UI bug, Thanks

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://user-images.githubusercontent.com/5169694/233939387-f53556b2-2724-42a1-ac2a-f00185c56069.png)
![image](https://user-images.githubusercontent.com/5169694/233939978-8e00c657-978e-4d41-a2d0-cded74afcb67.png)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1-cff1d5b5-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 2 nodes
2. Create an image for VM creation
3. Create Cluster Network and VM Network
4. Create VM `vm1` with VLAN network and configure **Node Scheduling** to `Required` match specific key `host-region: zone1` which not available
5. VM `vm1` applied with two affinity  rules and not able to start
6. Update one of the host node to add the specific key `host-region` with value `zone1`
7. VM `vm1` should be scheduled to host node with the specific key and started successfully.
