### ISSUE TITLE
[BUG] rancher2 rancher2_cloud_credential's `kubeconfig_content` has issues parsing data.

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3817]
**Describe the bug**
From https://github.com/rancher/terraform-provider-rancher2/pull/861 
The [rancher2_cloud_credential](https://github.com/rancher/terraform-provider-rancher2/blob/v3.0.0-rc1/docs/resources/cloud_credential.md?plain=1#L31-L39) has issues getting passed data that mimics the documentation.

**Pre-reqs**
- Using [setup_provider shell script](https://github.com/rancher/terraform-provider-rancher2/blob/master/setup-provider.sh) provision rancher2 Terraform Provider at either a:
    - v3.0.0-rc1
    - v3.0.0-rc2
- Have a Harvester v1.1.1 Cluster of N nodes
- Have an instance of Rancher v2.7.2 running, with the Harvester cluster imported

**To Reproduce**
1. Follow the doc to set up a `rancher2_cloud_credential` 
1. You will notice:
```
Error: "harvester_credential_config.0.kubeconfig_content": required field is not set
```

**Expected behavior**
The rancher2 cloud credential should provision with terraform for v1.1.1 Harvester in v2.7.2 Rancher on either v3.0.0-rc1 or v3.0.0-rc2 

**Environment**
 - Harvester ISO version: v1.1.1
 - Bare-Metal
 - Rancher: v2.7.2
 - Rancher2 Terraform Provider: ["v3.0.0-rc1", "v3.0.0-rc2"]

**Additional context**

This resource has been adjusted multiple times on the `kubeconfig_content` of which can be seen in the commented out portion:
```terraform
#Create a new Cloud Credential for an imported Harvester cluster
resource "rancher2_cloud_credential" "foo-harvester" {
  name = "test-cc"
  harvester_credential_config {
    cluster_id = data.rancher2_cluster_v2.foo-harvester.cluster_v1_id
    #cluster_id = "c-m-6szpgknw"
    cluster_type = "imported"
    kubeconfig_content = local.kubeconfig_pasted
    #kubeconfig_content = data.rancher2_cluster_v2.foo-harvester.kube_config
    #kubeconfig_content = [ tostring(data.rancher2_cluster_v2.foo-harvester.kube_config) ]
    #kubeconfig_content = file("${path.module}/foo-harvester-v2-cloud-provider-kubeconfig")
  }
}

```

I have tried multiple variations to pass the data, the only thing that seemed to work for the kubeconfig_content was with the local.kubeconfig_pasted run.
But again, that led to

Instance A:
```
2023-04-21T17:43:51.059-0700 [ERROR] vertex "rancher2_cloud_credential.foo-harvester" error: Incorrect attribute value type
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 44, in resource "rancher2_cloud_credential" "foo-harvester":
│   44:     kubeconfig_content = [ tostring(data.rancher2_cluster_v2.foo-harvester.kube_config) ]
│ 
│ Inappropriate value for attribute "kubeconfig_content": string required.
```

Instance B:
```
Planning failed. Terraform encountered an error while generating this plan.

╷
│ Error: "harvester_credential_config.0.kubeconfig_content": required field is not set
│ 
│   with rancher2_cloud_credential.foo-harvester,
│   on main.tf line 38, in resource "rancher2_cloud_credential" "foo-harvester":
│   38: resource "rancher2_cloud_credential" "foo-harvester" {
│ 
╵
```

Instance C:
```
2023-04-21T17:42:49.504-0700 [ERROR] vertex "rancher2_cloud_credential.foo-harvester" error: Incorrect attribute value type
╷
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 44, in resource "rancher2_cloud_credential" "foo-harvester":
│   44:     kubeconfig_content = [ data.rancher2_cluster_v2.foo-harvester.kube_config ]
│ 
│ Inappropriate value for attribute "kubeconfig_content": string required.
```

**Comment by futuretea** [comment]
I only tested applying kubeconfig with data.rancher2_cluster_v2, and it work
refer to https://github.com/rancher/terraform-provider-rancher2/blob/master/docs/resources/cluster_v2.md
```hcl
resource "rancher2_cloud_credential" "foo-harvester" {
  name = "test-cc"
  harvester_credential_config {
    cluster_id = data.rancher2_cluster_v2.foo-harvester.cluster_v1_id
    #cluster_id = "c-m-6szpgknw"
    cluster_type = "imported"
    #kubeconfig_content = local.kubeconfig_pasted
    kubeconfig_content = data.rancher2_cluster_v2.foo-harvester.kube_config
    #kubeconfig_content = [ tostring(data.rancher2_cluster_v2.foo-harvester.kube_config) ]
    #kubeconfig_content = file("${path.module}/foo-harvester-v2-cloud-provider-kubeconfig")
  }
}
```

**Comment by irishgordo** [comment]
@futuretea what version of Terraform were you using with that?

I was encountering issues trying to set up the cloud credential as it seemed to denote that there was some issue parsing the data but I wasn't able to figure out why.

**Comment by futuretea** [comment]
@irishgordo 
Terraform v1.3.9
terraform-provider-rancher v3.0.0-rc2

**Comment by irishgordo** [comment]
@futuretea  thanks for that insight :smile: :+1: 

Closing this as this was a configuration issue on my end surrounding the rancher2 provider.
