### ISSUE TITLE
[BUG] Cluster Config stuck in `Not Ready`

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3827]
### Describe the bug
![image](https://user-images.githubusercontent.com/5169694/234268067-ff05870e-e2e8-4b84-8be4-09b4d4ab7e9c.png)
![image](https://user-images.githubusercontent.com/5169694/234268633-fa348c40-d43e-4389-85ec-ccde825611e4.png)
![image](https://user-images.githubusercontent.com/5169694/234268865-4a774c10-12b3-4c8f-9682-846594181981.png)
![image](https://user-images.githubusercontent.com/5169694/234268927-15884820-2748-484e-a86f-7327e97dce82.png)

### To Reproduce
1. Install Harvester with any nodes
2. Create Cluster Network then create Cluster Config
3. Delete Cluster Config and cluster network
4. Repeat Step 2 and 3 few times

### Expected behavior
Cluster Config should be created successfully

## Environment:
 - Harvester ISO version: **v1.1-cff1d5b5-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
Discovered by API calls

### Support bundle
[supportbundle_e13bfc43-46d7-441b-931d-65234ce6d9b7_2023-04-25T11-57-12Z.zip](https://github.com/harvester/harvester/files/11322203/supportbundle_e13bfc43-46d7-441b-931d-65234ce6d9b7_2023-04-25T11-57-12Z.zip)

**Comment by rrajendran17** [comment]
Could not reproduce this locally on a cluster v1.2.2. Discussed with @lanfon72  and looks like this issue is fixed via
https://github.com/harvester/harvester/issues/3482.
So closing this bug.

**Comment by rrajendran17** [comment]
Fixed via https://github.com/harvester/harvester/issues/3482
