### ISSUE TITLE
[FEATURE] support zero downtime upgrade of Harvester

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#383]
**Is your feature request related to a problem? Please describe.**

Support zero downtime upgrade of Harvester, allow VMs to be migrated to another running node when it has enough resources.

**Describe the solution you'd like**

1. change the node to maintenance mode and allows the VM to schedule to other nodes automatically
1. after all the VMs has been migrated to the other node, the user is optionally to upgrade the Harvester node manually
1. after the upgrade is done, the node will be resumed automatically and allow the user to deploy the VM to this node again.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by gitlawr** [comment]
Check https://github.com/rancher/harvester/pull/716/files for reference.

For upgrade test in the UI:
1. Serve a file with the following content(assume it is available from http://10.0.0.10/version-metadata.json):
```
[
  {
    "version": "v0.2.0-rc3",
    "minUpgradableVersion": "v0.2.0-rc2"
  }
]
```
1. deploy a v0.2.0-rc2 cluster.
2. Run the following commands
```
# Note: update the URL in the command accordingly
kubectl patch setting version-metadata-url --type merge --patch '{"value": "http://10.0.0.10/version-metadata.json"}'

# update server-version so that we can get upgrade versions from version-metadata-url immediately without waiting for another sync interval. 
kubectl patch setting server-version --type merge -p '{"metadata":{"labels":{"foo":"bar"}}}'
```
3. Proceed in the UI as the documentation suggests

**Comment by TangStone** [comment]
### Updating harvester from v0.2.0-rc2 to v0.2.0-rc3 on UI failed  @gitlawr 
1. Deploy harvester v02.0-rc2 cluster 
- The node information is as follows

| Name | CPU | Memory 
| --- | --- | --- 
| harvester | 4c | 8G 
| harvester2 | 4c | 8G 
| harvester3 | 4c | 8G 

2. Serve a file with the following content(assume it is available from http://172.16.0.71/version-metadata.json):
![image](https://user-images.githubusercontent.com/15829074/115806272-09c56080-a419-11eb-9830-e8cc1ff89feb.png)
3. Run the following commands 
```
kubectl patch setting version-metadata-url --type merge --patch '{"value": "http://172.16.0.71/version-metadata.json"}'

kubectl patch setting server-version --type merge -p '{"metadata":{"labels":{"foo":"bar"}}}'
```
4. Login to harvester, set username and password, and create vm
5. Go to the Dashboard page of harvester UI, the upgrade button appears, select upgrade to v0.2.0-rc3

![image](https://user-images.githubusercontent.com/15829074/115691962-1bfbbc00-a391-11eb-8d76-7afa944bcc12.png)

5. the update failed, the relevant information is as follows
![image](https://user-images.githubusercontent.com/15829074/115807243-d8e62b00-a41a-11eb-8345-da61dc850526.png)
![image](https://user-images.githubusercontent.com/15829074/115807261-e3a0c000-a41a-11eb-8e00-d8bac02c15c7.png)
![image](https://user-images.githubusercontent.com/15829074/115807297-f1564580-a41a-11eb-9a44-6c9072b4d48a.png)
![image](https://user-images.githubusercontent.com/15829074/115807407-29f61f00-a41b-11eb-8e47-109ece738ef2.png)
![image](https://user-images.githubusercontent.com/15829074/115807441-34b0b400-a41b-11eb-8ed6-9966f6093c97.png)

**Comment by TangStone** [comment]
v0.2.0-rc2 upgrade v0.2.0-rc3 @gitlawr 
After checking the upgrade harvester, the node automatically restarts, and then the interface appears again, and the cycle repeats
![image](https://user-images.githubusercontent.com/15829074/115996615-9129f400-a612-11eb-8e65-5836b76f6d99.png)

**Comment by gitlawr** [comment]
@TangStone You need to boot from the disk after the upgrade is completed

**Comment by gitlawr** [comment]
For the failure case:
Logs from the initial helm install pod:
```
...
+ helm_v3 upgrade --namespace harvester-system --set-string containers.apiserver.authMode=rancher --set containers.apiserver.hciMode=true --set-string containers.apiserver.image.imagePullPolicy=IfNotPresent --set-string harvester-network-controller.image.pullPolicy=IfNotPresent --set-string longhorn.defaultSettings.taintToleration=kubevirt.io/drain:NoSchedule --set longhorn.enabled=true --set-string minio.persistence.storageClass=longhorn --set multus.enabled=true --set rancherEmbedded=true --set service.harvester.httpsNodePort=30443 --set-string service.harvester.type=NodePort harvester https://10.53.0.1:443/static/charts/harvester-0.2.0-rc3.tgz
Error: UPGRADE FAILED: cannot patch "kubevirt" with kind KubeVirt: Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": Post "https://kubevirt-operator-webhook.harvester-system.svc:443/kubevirt-validate-update?timeout=30s": dial tcp 10.53.207.208:443: connect: connection refused
```

Logs from the helm install pod when it restarted once:
```
...
+ '[' install = delete ']'
+ '[' -z v0.2.0-rc3 ']'
+ '[' failed = deployed ']'
+ '[' failed = failed ']'
+ '[' helm_v3 == helm_v3 ']'
+ helm_v3 uninstall harvester --namespace harvester-system
release "harvester" uninstalled
+ echo Deleted
+ helm_v3 install --namespace harvester-system --set-string containers.apiserver.authMode=rancher --set containers.apiserver.hciMode=true --set-string containers.apiserver.image.imagePullPolicy=IfNotPresent --set-string harvester-network-controller.image.pullPolicy=IfNotPresent --set-string longhorn.defaultSettings.taintToleration=kubevirt.io/drain:NoSchedule --set longhorn.enabled=true --set-string minio.persistence.storageClass=longhorn --set multus.enabled=true --set rancherEmbedded=true --set service.harvester.httpsNodePort=30443 --set-string service.harvester.type=NodePort harvester https://10.53.0.1:443/static/charts/harvester-0.2.0-rc3.tgz
Deleted
Error: failed to create resource: serviceaccounts "longhorn-service-account" is forbidden: unable to create new content in namespace longhorn-system because it is being terminated
```

**Comment by TangStone** [comment]
### After the upgrade is completed, the accessKeyID or secretAccessKey of backup-target is empty @gitlawr 
**v0.2.0-rc4 upgrade to master-d026b5be-head**
**Upgrade method:Upgrade using the ISO image**

**Reproduction steps**
1. deploy harvester v0.2.0-rc4
2. configure backup-target
3. create vm and backup successfully
4. upgrade harvester successfully

**result**
![image](https://user-images.githubusercontent.com/15829074/116520544-70f58000-a905-11eb-964e-61a34dbcba4d.png)

**Comment by TangStone** [comment]
### Upgrade from v0.2.0-rc4 to head-master using the UI was successful
**3 nodes (8c,8g)**
1. deploy harvester v0.2.0-rc4
2. create 3 vm's
3. execute command `kubectl patch setting upgradable-versions --type=merge -p 'value: master-head'`
4. Go to Dashboard and click upgrade

**Comment by TangStone** [comment]
> @TangStone You need to boot from the disk after the upgrade is completed

Installation operation upgrade successful
