### ISSUE TITLE
[ENHANCEMENT] Check volume status when adding existing volumes to VM.

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#3831]
**Is your enhancement related to a problem? Please describe.**

It's for mitigating a problem described [here](https://github.com/harvester/harvester/pull/2980#issuecomment-1286486710).
For now, when trying to attach a volume that is in `Pending` state to a VM and try to boot up, the VM will stuck in `Starting` state.

**Describe the solution you'd like**

When showing existing volumes that can be attached to the VM, check the status of the volume and select only volumes that are in `Ready` state.

**Additional context**

It's an issue at longhorn: https://github.com/longhorn/longhorn/issues/4785

**Comment by noahgildersleeve** [comment]
Tested in v1.2.0-rc1 on single node bare metal machine (HP DL160)

## Verification Steps

1. Create a new VM
2. Add a large file to the base volume (I downloaded the Harvester ISO)
3. Shutdown the VM
4. Create a volume snapshot of the VM volume
5. Restore the volume snapshot to a new volume
6. Try to add the volume to the VM as an existing volume while it is still initializing

## Expected Results
- While the volume is not ready it shouldn't be shown in the dropdown list
- When the volume is ready it should show in the dropdown list

## Notes
- This happens quickly so you will probably have to have the edit config window open while you are restoring the volume
