### ISSUE TITLE
[BUG] PCI passthrough keeps retrying

### ISSUE THREAD

**Issue by hsinhoyeh** [harvester/harvester#3833]
**Describe the bug**

As followed [the doc](https://docs.harvesterhci.io/v1.1/advanced/pcidevices/) describes how PCI passthrough can work, it didn't work well on our machines (basically we run harvester on one single machines). From the screenshots, the device is in 'In progress' state

![Screenshot 2023-04-27 at 11 04 46 AM](https://user-images.githubusercontent.com/2792682/234749215-c6ebd534-6c67-47aa-baf9-4b8ca8f3667c.png)

we run the `kubectl  -n harvester-system logs -f harvester-pcidevices-controller-xxxx` from the node itself, we found the following error messages:

```
time="2023-04-27T03:07:31Z" level=info msg="Adding harvester01-000001000 to KubeVirt list of permitted devices"
time="2023-04-27T03:07:31Z" level=info msg="Enabling passthrough for PDC: harvester01-000001000"
time="2023-04-27T03:07:31Z" level=info msg="Binding device harvester01-000001000 [10de 2204] to vfio-pci"
time="2023-04-27T03:07:31Z" level=info msg="Binding device 0000:01:00.0 vfio-pci"
time="2023-04-27T03:07:31Z" level=error msg="error syncing 'harvester01-000001000': handler PCIDeviceClaimReconcile: error writing to bind file: write /sys/bus/pci/drivers/vfio-pci/bind: invalid argument, requeuing"
```

**To Reproduce**
1. install harvester 1.1.2 on single machine with gpu 3090
2. enable pcidevices-controller
3. select nvidia devices and click enable passthrough
4.  the state is in 'In Progress' for more than one day..

**Expected behavior**
at step 4, it should display 'enabled' on the selected pci devices

**Support bundle**
[supportbundle_167a246e-a1c5-4648-94c2-f2c1f6570591_2023-04-27T03-02-05Z.zip](https://github.com/harvester/harvester/files/11339218/supportbundle_167a246e-a1c5-4648-94c2-f2c1f6570591_2023-04-27T03-02-05Z.zip)

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremental machine with one 3090 graphic device

**Comment by hsinhoyeh** [comment]
the originam image was `rancher/harvester-pcidevices:v0.2.4` and from the #3609 we switched to `gmehta3/pcidevices:dev` image, but error messages keep showing up:
```
time="2023-04-27T03:28:19Z" level=info msg="[PCIDeviceController] Device harvester01-000004000 does not exist"
time="2023-04-27T03:28:19Z" level=info msg="Creating PCI Device: pcidevices.devices.harvesterhci.io \"harvester01-000004000\" not found\n"
time="2023-04-27T03:28:32Z" level=info msg="Reconciling PCI Devices list"
time="2023-04-27T03:28:39Z" level=info msg="Adding harvester01-000001000 to KubeVirt list of permitted devices"
time="2023-04-27T03:28:39Z" level=info msg="Enabling passthrough for PDC: harvester01-000001000"
time="2023-04-27T03:28:39Z" level=info msg="Binding device harvester01-000001000 [10de 2204] to vfio-pci"
time="2023-04-27T03:28:39Z" level=info msg="Binding device 0000:01:00.0 vfio-pci"
time="2023-04-27T03:28:39Z" level=error msg="error syncing 'harvester01-000001000': handler PCIDeviceClaimReconcile: error writing to bind file: write /sys/bus/pci/drivers/vfio-pci/bind: invalid argument, requeuing"
```

**Comment by hsinhoyeh** [comment]
Thanks gauravm's help over the slack channel, I got it work finally.

It is `vt-d` setting on bios are NOT turn on, after that we are able to passthrough gpu.

here are some message to help debug:

```
kubectl get pcidevices  -n <device-name> -o yaml

apiVersion: devices.harvesterhci.io/v1beta1
kind: PCIDevice
metadata:
  annotations:
    harvesterhci.io/pcideviceDriver: ""
  creationTimestamp: "2023-04-26T02:07:48Z"
  generation: 1
  labels:
    nodename: harvester01
  name: harvester01-000001000
  resourceVersion: "1774055"
  uid: <uid>
spec: {}
status:
  address: "0000:01:00.0"
  classId: "0300"
  description: 'VGA compatible controller: NVIDIA Corporation GA102 [GeForce RTX 3090]'
  deviceId: "2204"
  iommuGroup: "13"
  kernelDriverInUse: vfio-pci
  nodeName: harvester01
  resourceName: nvidia.com/GA102_GEFORCE_RTX_3090
  vendorId: 10de
```

`iommuGroup` should contain a valid string (i.e. "13" ), if that value is empty, then you probably needs to configure vt-d from BIOS.

**Comment by ibrokethecloud** [comment]
re-opened issue to ensure we can catch this case via pcidevices webhook.

**Comment by irishgordo** [comment]
Thanks for the fix @ibrokethecloud  - the webhook now catches the issue and doesn't allow the device to be enabled :smile: :+1: 

![Screenshot from 2023-06-01 19-40-15](https://github.com/harvester/harvester/assets/5370752/1b6251f7-dc9e-4127-93c4-d20a7887e0f0)
![Screenshot from 2023-06-01 19-23-27](https://github.com/harvester/harvester/assets/5370752/72b1a2e1-d761-4da5-a685-9a57a82708c5)

I'll go ahead and close this out!
Tested v1.2.0-rc1
