### ISSUE TITLE
[Doc] Unable to load custom kernel modules using elemental cloud-init config.

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#3835]
**Describe the bug**

It's for tracking the upstream issue https://github.com/rancher/elemental-toolkit/issues/1733.

**To Reproduce**
Steps to reproduce the behavior: https://github.com/rancher/elemental-toolkit/issues/1733#issue-1588634589

**Expected behavior**

Kernel modules like `nvme` can be loaded normally.

**Additional context**
This is an issue separated from https://github.com/harvester/harvester/issues/3366, that issue is fixed by a workaround and is ready for testing.

**Comment by masteryyh** [comment]
As elemental team might want to delete this feature in the future, we may need to update document about this, no code needs to be updated.
Related upstream issue: https://github.com/rancher/elemental-toolkit/issues/1768

**Comment by bk201** [comment]
Close this since we can use modprobe in commands as a solution.
