### ISSUE TITLE
[ENHANCEMENT] To include current image list of each node in the support bundle

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#3838]
**Is your enhancement related to a problem? Please describe.**

Sometimes essential images are pruned by the image GC mechanism due to the node disk pressure event, and it causes various types of failure. We can peek at the `kubelet.log` from the support bundle to see if there's such an event, but it's hard to tell precisely what images are GC'ed. Commonly, users imported the missing image and solved the problem, but then they reencountered another issue with a similar root cause (image missing).

If we could have that information from the support bundle, we would have a chance to know what images need to be reimported on the nodes to prevent that trial-and-error style of troubleshooting.

**Describe the solution you'd like**

To include the current image list files of each node in the generated support-bundle file

**Describe alternatives you've considered**

Access the nodes and execute `ctr -n k8s.io i ls`.

**Additional context**

**Comment by Yu-Jack** [comment]
Add more context about image GC. There are some interesting configurations [3] we might use. 

For example, there are three parameters related to image GC

- imageMinimumGCAge, default: 2m
- imageGCHighThresholdPercent, default: 85
- imageGCLowThresholdPercent, default: 80

Click [3] link and search with `image` to find more details. We maybe could use those parameters to tune it. But, I'm still thinking what if kubelet doesn't remove image, is it a good option to do that?

### References
1. [Clean up old containers and images in your kubernetes cluster](https://technotes.adelerhof.eu/containers/kubernetes/clean-up-old-containers-and-images-in-your-kubernetes-cluster/#container-images)
2. [Garbage collection of unused containers and images](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#containers-images)
3. [Kubelet Configuration](https://kubernetes.io/docs/reference/config-api/kubelet-config.v1beta1/)

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Case
Compare to `v1.2.1`, can see containerd-images.log which contains image list. :ballot_box_with_check: 
![image](https://github.com/harvester/harvester/assets/2773781/6bc0d420-483a-4bc1-ae74-be38ce84ebc9)
[supportbundle_v121.zip](https://github.com/harvester/harvester/files/13770164/supportbundle_v121.zip)
[supportbundle_v130.zip](https://github.com/harvester/harvester/files/13770167/supportbundle_v130.zip)
