### ISSUE TITLE
[BUG] "Add Disk" fails with "Sorry, no matching options" on blank disk

### ISSUE THREAD

**Issue by silug** [harvester/harvester#3840]
**Describe the bug**
Attempting to add a blank disk (in my case, a newly-created virtual disk) shows the following:
![image](https://user-images.githubusercontent.com/206992/234992722-d7ef1d95-ce5a-4d46-9ebe-a44b1df5586d.png)

After creating a GPT partition table on the drive (using `sudo parted /dev/vdb mklabel gpt` from a shell), it shows up in the UI.

**To Reproduce**
1. Add a completely zeroed disk to a node
2. Under `Hosts`, select `Edit Config` on the node
3. Select `Storage` and click on `Add Disk`

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure: libvirt/kvm

**Additional context**
As mentioned above, adding a GPT partition table worked around the issue.  Adding a MSDOS partition table caused an error that might be related to #3694.

**Comment by Vicente-Cheng** [comment]
Hi @silug
Sorry for the late reply. 
Did you mean that if you do not create gpt label with the virtual disk, it does not show up in the UI?

Could you describe more about how you added this vdb?
I try to add a disk via the virsh command, and it works well.

**Comment by silug** [comment]
> Hi @silug Sorry for the late reply. Did you mean that if you do not create gpt label with the virtual disk, it does not show up in the UI?

Exactly.

> Could you describe more about how you added this vdb? I try to add a disk via the virsh command, and it works well.

It was added during initial VM creation.  In theory there should be no difference between that and adding the disk after the VM is running.

**Comment by Vicente-Cheng** [comment]
> > Could you describe more about how you added this vdb? I try to add a disk via the virsh command, and it works well.
> 
> It was added during initial VM creation. In theory there should be no difference between that and adding the disk after the VM is running.

OK, that's a good point. I could check again with your operation.
Thanks!

**Comment by felixn-unity** [comment]
Hi

Issue is likely related to new disks is not formattet with ext4/xfs. When disks are formattet it will show up on the the host -> node -> config -> storage "add new disk"

Example:

I added 3 new virtual disks on my esxi VM:

**lsblk | grep 60**

sda      8:0    0   60G  0 disk
sdc      8:32   0   60G  0 disk
sdd      8:48   0   60G  0 disk

**mkfs.ext4 /dev/sda**
**mkfs.ext4 /dev/sdc**
**mkfs.ext4 /dev/sdd**

**Then Add New Disk under host -> node -> config -> storage**

/dev/sda
/dev/sdc
/dev/sdd

**lsblk | grep 60**

sda      8:0    0   60G  0 disk /var/lib/harvester/extra-disks/f6439d17a300a39045eea81c52e6f5bf
sdc      8:32   0   60G  0 disk /var/lib/harvester/extra-disks/89d95ef692e3e908139b1b790f3129de
sdd      8:48   0   60G  0 disk /var/lib/harvester/extra-disks/b91baf2097a1acb5bcee2a00a815fcb2

Thanks
Felix

**Comment by Vicente-Cheng** [comment]
I already replied to this on the Slack channel but also commented here. (for recording)

Hi @felixn-unity, 
Thanks for your sharing.
Yes, manually formatting the disks to ext4/xfs would be good to let the harvester-node-disk-manager easy to know them.

But the harvester-node-disk-manager should be able to recognize the raw device.
That is probably an issue with @silug 's case.

I added a disk and tried msdos or gpt label. I could recognize them on the UI config page.
~@silug, would you like to reproduce this case and generate the SB for us to debug?~
I will still try to reproduce it. Just keep your running cluster :D

Thanks!

**Comment by iosifnicolae2** [comment]
The solution in our case was to:
0. Format the nvme disk
```bash
sudo mkfs -t ext4 /dev/nvmeX
```
2. Delete all blockdevices which might have been attached before but currently are not used by Longhorn
```bash
kubectl get blockdevices -A | grep nvme
kubectl delete -n longhorn-system blockdevice xxxxxxx
```
3. Kill `harvester-node-disk-manager` pods from `harvester-system` namespace
4. Try adding the disk again

**Comment by Vicente-Cheng** [comment]
Thanks @iosifnicolae2 for sharing this.
This is the simple way to reset the blockdevice CR and NDM process.

But be careful; this operation will erase all the data on this disk. If you are a single node with one replica, please do not do that without any backup/snapshot.

**Comment by rrajendran17** [comment]
@Vicente-Cheng I believe there is no pending tasks on this.Can I resolve this ?

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng I believe there is no pending tasks on this.Can I resolve this ?

Thanks for the reminder! @rrajendran17 

This issue is related to the disk w/o/ WWN. There are some discussion above and I would like to close it this moment.
If there is anything need to discuss, feel free to re-open/create another issue. Thanks!
