### ISSUE TITLE
[BUG] Stuck in 'Setting up node/Harvester' after install harvester

### ISSUE THREAD

**Issue by GoodGoodJM** [harvester/harvester#3844]
**Describe the bug**
I tried to install harvester(1.1.2) my server. Install seems to be success but after reboot, it stuck in boot. Status never change from "Setting up Harvester/node" .

also i tried 1.1.1 version but it cannot boot(see #3789)

**To Reproduce**

Try to install 1.1.2 harvester using usb boot disk. (used UEFI)

**Expected behavior**

After booting, the server must boot and have access to the harvester web console.

**Support bundle**
Cannot access web console

**Environment**
- Harvester ISO version: 1.1.2-amd64
- Underlying Infrastructure: Baremetal, dell T430(e5 2650v4 *2, 256GB, 1TB SATA SSD(MICRON)

**Remote console using iDRAC**

**Additional context**
I wathed #3789 , but I think it's a little different from my situation. I've been try to install several versions for two weeks, but when I installed the 1.1.1 version like #3789, I was wondering that only BIOS boot would work. The same error also occurs.

**Comment by w13915984028** [comment]
@GoodGoodJM Suppose you are installing with Harvester v1.1.2 and it is in `setting up harvester`, please:

`ssh`  into the harvester from the NODE IP (not the VIP)
`sudo -i`
then get following information into one txt/log file and add it here:
```
ip link
ip addr
ps aux
uname -a
cat /proc/cpuinfo
systemctl status rke2-server.service
jounalctl

kubectl get pods -A -o wide
kubectl get service -A
kubectl get node -A
kubectl get managedchart -A
kubectl get bundle -A
kubectl get bundledeployment -A
```

thanks.

**Comment by GoodGoodJM** [comment]
@w13915984028 , Here is logs you requested.

[00_ip-link.txt](https://github.com/harvester/harvester/files/11416984/00_ip-link.txt)
[01_ip-addr.txt](https://github.com/harvester/harvester/files/11416985/01_ip-addr.txt)
[02_ps-aux.txt](https://github.com/harvester/harvester/files/11416986/02_ps-aux.txt)
[03_uname.txt](https://github.com/harvester/harvester/files/11416987/03_uname.txt)
[04_cat-cpuinfo.txt](https://github.com/harvester/harvester/files/11416988/04_cat-cpuinfo.txt)
[05_systemctl-status-rke2.txt](https://github.com/harvester/harvester/files/11416989/05_systemctl-status-rke2.txt)
[06_journalctl.txt](https://github.com/harvester/harvester/files/11416990/06_journalctl.txt)
[07_kb-get-pods.txt](https://github.com/harvester/harvester/files/11416991/07_kb-get-pods.txt)
[08_kb-get-service.txt](https://github.com/harvester/harvester/files/11416992/08_kb-get-service.txt)
[09_kb-get-node.txt](https://github.com/harvester/harvester/files/11416993/09_kb-get-node.txt)
[10_kb-get-managedchart.txt](https://github.com/harvester/harvester/files/11416994/10_kb-get-managedchart.txt)
[11_kb-get-bundle.txt](https://github.com/harvester/harvester/files/11416995/11_kb-get-bundle.txt)
[12_kb-get-bundledeployment.txt](https://github.com/harvester/harvester/files/11416996/12_kb-get-bundledeployment.txt)

thanks :)


----

And while I was collecting logs, I find a pad that is not working and attach the describe screen.
![스크린샷 2023-05-08 오전 10 30 16](https://user-images.githubusercontent.com/8029093/236714778-dd18d772-86fc-4be5-9d16-30c32b02eb48.png)

**Comment by w13915984028** [comment]
@GoodGoodJM Is your server air-gapped?

@bk201 In the `setting up cluster` stage, it is `ImagePullBackOff` on POD `harvester-cluster-repo-67ddddf8d7-zc7zd`, any insights? thanks.

All the then running POD are listed:

```
NAMESPACE                   NAME                                                    READY   STATUS             RESTARTS      AGE   IP              NODE            NOMINATED NODE   READINESS GATES
cattle-fleet-local-system   fleet-agent-6ffcdc7f94-62kwm                            1/1     Running            0             56m   10.52.0.54      harvester-001   <none>           <none>
cattle-fleet-system         fleet-controller-5d546cc5b8-9pgmf                       1/1     Running            0             56m   10.52.0.49      harvester-001   <none>           <none>
cattle-fleet-system         gitjob-5c5979d844-9lgm5                                 1/1     Running            0             56m   10.52.0.48      harvester-001   <none>           <none>
cattle-system               harvester-cluster-repo-67ddddf8d7-zc7zd                 0/1     ImagePullBackOff   0             56m   10.52.0.55      harvester-001   <none>           <none>
cattle-system               helm-operation-5btlx                                    0/2     Completed          0             56m   10.52.0.51      harvester-001   <none>           <none>
cattle-system               helm-operation-jjfz6                                    0/2     Completed          0             56m   10.52.0.47      harvester-001   <none>           <none>
cattle-system               helm-operation-m22vd                                    0/2     Completed          0             57m   10.52.0.46      harvester-001   <none>           <none>
cattle-system               rancher-5b6ff45f9-flkdz                                 1/1     Running            0             11d   10.52.0.38      harvester-001   <none>           <none>
cattle-system               rancher-webhook-7577bd9c47-mldxp                        1/1     Running            0             56m   10.52.0.53      harvester-001   <none>           <none>
cattle-system               system-upgrade-controller-79fc9c84b7-2gkfj              1/1     Running            0             56m   10.52.0.57      harvester-001   <none>           <none>
kube-system                 cloud-controller-manager-harvester-001                  1/1     Running            7 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 etcd-harvester-001                                      1/1     Running            4 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 helm-install-rke2-canal-7rnv7                           0/1     Completed          0             11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 helm-install-rke2-coredns-mjd4c                         0/1     Completed          0             11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 helm-install-rke2-ingress-nginx-gp8j8                   0/1     Completed          0             56m   10.52.0.56      harvester-001   <none>           <none>
kube-system                 helm-install-rke2-metrics-server-96mhl                  0/1     Completed          0             11d   10.52.0.37      harvester-001   <none>           <none>
kube-system                 helm-install-rke2-multus-6zr5c                          0/1     Completed          0             11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 kube-apiserver-harvester-001                            1/1     Running            5 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 kube-controller-manager-harvester-001                   1/1     Running            8 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 kube-proxy-harvester-001                                1/1     Running            5 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 kube-scheduler-harvester-001                            1/1     Running            5 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 rke2-canal-g69zw                                        2/2     Running            2 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
kube-system                 rke2-coredns-rke2-coredns-58fd75f64b-wc2jg              1/1     Running            0             11d   10.52.0.41      harvester-001   <none>           <none>
kube-system                 rke2-coredns-rke2-coredns-autoscaler-768bfc5985-q5frk   1/1     Running            0             11d   10.52.0.39      harvester-001   <none>           <none>
kube-system                 rke2-ingress-nginx-controller-hq298                     1/1     Running            0             56m   10.52.0.60      harvester-001   <none>           <none>
kube-system                 rke2-metrics-server-74f878b999-79bkm                    1/1     Running            0             57m   10.52.0.43      harvester-001   <none>           <none>
kube-system                 rke2-multus-ds-wxmt5                                    1/1     Running            1 (58m ago)   11d   192.168.0.200   harvester-001   <none>           <none>
```

**Comment by GoodGoodJM** [comment]
@w13915984028  My server is not air-gapped, i can request and receive other network.

**Comment by w13915984028** [comment]
When you install the Harvester, what is the partition size selected fo installation?

And please ssh into the NODE ip, `sudo -i`, then `docker image ls`, we will check if the `harvester-cluster-repo` required image is there, with `kubectl get pods -n cattle-system harvester-cluster-repo-67ddddf8d7-zc7zd -oyaml`. thanks.

**Comment by bk201** [comment]
cluster-repo image is not published to dockerhub. The main reason the image is missing is due to the image preloading fails. Probably related to https://github.com/harvester/harvester/issues/2651, it will be fixed in 1.2.0.

**Comment by bk201** [comment]
@GoodGoodJM If it's in a non-air gapped env, you can try import the image by yourself. The rest images can be download from the Internet.

- Mount the v1.1.2 ISO to find the image tarball. Assume the ISO is mounted to `/tmp/mnt` (You could get it from the USB you made too):
  ```
  $ ls -alh /tmp/mnt/bundle/harvester/images/harvester-repo-images-v1.1.2.tar.zst
  -rw-r--r-- 1 root root 55M Apr 25 18:16 /tmp/mnt/bundle/harvester/images/harvester-repo-images-v1.1.2.tar.zst
  ```

- scp the zstd tarball to your Harvester node. Assume the tarball is placed in `/tmp/harvester-repo-images-v1.1.2.tar.zst`
- log in to the Harvester node and do the import
  ```
  sudo -i
  cd /tmp
  zstd -d harvester-repo-images-v1.1.2.tar.zst
  ctr -n k8s.io image import harvester-repo-images-v1.1.2.tar
  ```

**Comment by bk201** [comment]
@GoodGoodJM Please see if the above recommendation helps, we'll close the issue for now.

**Comment by johnwc** [comment]
@bk201 Had this same thing happen today when adding a node to a v1.2.2 cluster via pxe boot. So, I don't think it is fully fixed.

**Comment by bk201** [comment]
@johnwc It's hard to tell if the issue you saw is identical to this one, can you create a new issue with more info? Thanks.

**Comment by johnwc** [comment]
@bk201 sorry, got my tabs mixed up and thought I was commenting on the #4058 issue that was pointing to the above comment referencing a potential fix. I will delete my comment above and place in the correct issue.
