### ISSUE TITLE
[FEATURE] support VM backup and restore

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#385]
**Is your feature request related to a problem? Please describe.**

support VM <del>snapshot</del>., backup, and restore using the build-in distributed block storage

**Describe the solution you'd like**

Work process in the UI:   
1. need to specify a backup target(both NFS and S3 are supported) before config the backup.
1. <del>Users can take a snapshot of an existing VM without downtime.</del>
1. Users can take a backup of an existing VM without downtime.
1. Users can use the backup to roll-back the existing VM to a certain point in time [VM should be stopped].
1. Users can use a backup to restore a new VM.

**Describe alternatives you've considered**

**Additional context**

**Comment by TangStone** [comment]
There are problems with this scenario @guangbochen 

Restoring a new vm after multiple backups of the same vm successfully

**Steps**
1. Create vm successfully and login
2. add back1.txt to save and backup vm to vm-back1
3. add back2.txt to save and backup vm to vm-back2
4. install docker on vm, backup vm to vm-back3-with-docker
6. wait for vm-back1, vm-back2, vm-back3-with-docker to finish backup
7. restore vm-back1, vm-back2, vm-back3-with-docker to vm-back1-restore, vm-back2-restore, vm-back3-with-docker-restore in order

**Results**

- See vm-back1-restore, vm-back2-restore and vm-back3-with-docker-restore as the same with docker

**Comment by TangStone** [comment]
Whether NFS or S3 is used as backup-target, deleting backups on the UI will not actually change the size of backup-target.

**Comment by TangStone** [comment]
@WuJun2016 
Steps
1. Successfully create a VM
2. Use the VM to create two backups with the same name

Results
- There will be two alert boxes, success and failure
- No backups were eventually created
![image](https://user-images.githubusercontent.com/15829074/111994836-330d7b00-8b53-11eb-9340-48fd37e28e76.png)

Expectation

-  only failed box

**Comment by guangbochen** [comment]
> Whether NFS or S3 is used as backup-target, deleting backups on the UI will not actually change the size of backup-target.

this actually is managed by the longhorn and will check it with @yasker, since we are deleting the volumesnapshot CR directly on the Harvester side, just wondering if there is any other object we need to handle from the longhorn side, maybe cc @shuo-wu.

**Comment by yasker** [comment]
@TangStone Backup blocks are referenced and GCed, so as long as one block is still being used by any backup, it's not going to be freed. Can you try if you delete all backups, does it clean up the directory and free the space?

**Comment by TangStone** [comment]
I delete all backups, it doesn't clean up the directory and free the space @yasker  It seems that volumesnapshot is not deleted @guangbochen

**Comment by yasker** [comment]
@innobead Can someone help to look into this?

**Comment by innobead** [comment]
https://github.com/longhorn/longhorn/issues/2417 created.

@TangStone Next time. Please help also create a corresponding issue on longhorn, then the issue will be tackled. Thanks.

**Comment by jenting** [comment]
> I delete all backups, it doesn't clean up the directory and free the space @yasker It seems that volumesnapshot is not deleted @guangbochen

@TangStone,
I didn't deploy Harvester to test it but I create a Longhorn cluster with version v1.1.0 and v1.1.1-preview1 respectively and deploy an Elasticsearch cluster (StatefulSet) on it. However, I can't reproduce the issue you described. I delete all VolumeSnapshot CR of specific volume, the `backups/` and `blocks/` folder both got deleted in MinIO.

Questions:
1. For the directory that doesn't clean up: do you mean the `backups/` and `blocks/` folder in MinIO?
2. The space did not free: could you please capture the screen to us about this?
3. Do you know which Longhorn version Harvester is using?

**Comment by TangStone** [comment]
Validate the version in master-67244e23-head
Backup rename prompt problem solved https://github.com/rancher/harvester/issues/385#issuecomment-804058048

**Comment by guangbochen** [comment]
I will take a look at the backup clean up issue first, thanks

**Comment by TangStone** [comment]
@jenting @guangbochen 

 Questions:
> 1. For the directory that doesn't clean up: do you mean the `backups/` and `blocks/` folder in MinIO?
> 2. The space did not free: could you please capture the screen to us about this?
> 3. Do you know which Longhorn version Harvester is using?

**First question answer**
The backup and blocks folders are not cleaned

**Answer to the second question**
1. Before creating a VM backup
![image](https://user-images.githubusercontent.com/15829074/112969367-c2ccae00-917f-11eb-89b7-53cb9d06fbff.png)
2. After creating a VM backup
![image](https://user-images.githubusercontent.com/15829074/112969752-222abe00-9180-11eb-8feb-4e866c7cbb8c.png)
![image](https://user-images.githubusercontent.com/15829074/112969850-379fe800-9180-11eb-870f-dded4579232b.png)
![image](https://user-images.githubusercontent.com/15829074/112970080-6918b380-9180-11eb-855c-f08ded1e536f.png)
3. After deleting the VM backup
![image](https://user-images.githubusercontent.com/15829074/112970297-a2512380-9180-11eb-89f2-9b62996794a2.png)
![image](https://user-images.githubusercontent.com/15829074/112970402-bd239800-9180-11eb-9294-30c36e79ce27.png)
![image](https://user-images.githubusercontent.com/15829074/112970467-ca408700-9180-11eb-90c0-8b3cf3165ddb.png)
4. If you manually delete the volumesnapshot in the harvester host using the command
![image](https://user-images.githubusercontent.com/15829074/112970939-4b981980-9181-11eb-8185-71facb35c01f.png)
5.  it clean up the directory and free the space
![image](https://user-images.githubusercontent.com/15829074/112971604-f9a3c380-9181-11eb-9748-5efcbb94b150.png)

**Answer the third question**
![image](https://user-images.githubusercontent.com/15829074/112971948-51dac580-9182-11eb-885c-a2fabc0f18b0.png)

**Comment by innobead** [comment]
> 1. Before creating a VM backup
> 2. After creating a VM backup
> 3. After deleting the VM backup
> 4. If you manually delete the volumesnapshot in the harvester host using the command
> 5. it clean up the directory and free the space

Ok. Because the volumesnapshot operation works (the K8s interface to operate LH), this should be related to Longhorn integration at Harvester. Please check if the API integration is correct from the frontend to the backend at Harvester.

**Comment by guangbochen** [comment]
this should be addressed in the master-head version @TangStone, u may also test using the v0.2.0-rc1 release.

**Comment by TangStone** [comment]
Validate the version in v0.2.0-rc1
Solved the problem of deleting all backups and not releasing the target space  https://github.com/rancher/harvester/issues/385#issuecomment-810092427

**Comment by TangStone** [comment]
Validate the version in v0.2.0-rc1
Solved the issue  https://github.com/rancher/harvester/issues/385#issuecomment-801860005
