### ISSUE TITLE
[Question] Unable to add nodes & resources from other bare metal setup

### ISSUE THREAD

**Issue by rpartapsing** [harvester/harvester#3854]
Hi,

Currently I have a working k8s cluster setup with rancher and Harvester on my PC.
My management URL (kube-vip.io/requestedIP) is 192.168.68.191.
![Capture1](https://user-images.githubusercontent.com/59692703/236306375-d4f8d5e6-259f-4b91-934d-f905b8e78cdc.JPG)

Now I also have a NUC which I want to couple to my cluster.
When I say `join an existing cluster` and I refer to the same IP address I get the error
```
Get "https://192.168.68.191:8443/ping": dial tcp 192.168.68.191:8443: connect: connection refused
```

p.s. I also checked here https://github.com/harvester/harvester/issues/1830 and made sure rancher and the VIP are running on the same node. 
![Capture](https://user-images.githubusercontent.com/59692703/236305892-bb235ac9-7b3d-4a12-91a5-b9ca046d94a1.JPG)
![Capture3](https://user-images.githubusercontent.com/59692703/236306808-b0db5a56-a318-4dc7-9305-ca0638b89dfa.JPG)

How to fix this?

**Comment by starbops** [comment]
Hi, @rpartapsing! What version of Harvester are you installing? In recent versions, we change to probe port 443 instead of 8443. Thanks!

**Comment by rpartapsing** [comment]
@starbops thanks for your quick reply. My management service is running v1.1. Can I boot my NUC with a higher version to join the cluster or do I need to upgrade my management node also?

**Comment by rpartapsing** [comment]
Got it to work wohoo. You can boot another hardware with a different harvester version. But indeed take the latest ones. With the probing changed to port 443, all works seeminglessly
