### ISSUE TITLE
[BUG] Modify `local-rke-state` secret to allow upgrade from previous version

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#3858]
**Describe the bug**

Rancher will check the secret, and upgrading RKE2 will fail.
The change causes it: https://github.com/rancher/rancher/pull/41088
Related rancherd issue: https://github.com/rancher/rancherd/issues/29, we need to make sure new clusters have the right secret too.

**To Reproduce**
- Upgrade to a newer Harvester version contains the Rancher change.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
This looks good :smile: :+1: 
Tested upgrade from v1.1.2 ->  master-173b0824-head 

Looking at secret after upgrade, via: `kubectl get secrets local-rke-state -o yaml -n fleet-local`
Noting:
```yaml
apiVersion: v1
data:
  agentToken: dG9rZW4=
  serverToken: dG9rZW4=
kind: Secret
metadata:
  annotations:
    field.cattle.io/projectId: local:p-n7s5k
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"agentToken":"dG9rZW4=","serverToken":"dG9rZW4="},"kind":"Secret","metadata":{"annotations":{"field.cattle.io/projectId":"local:p-n7s5k"},"creationTimestamp":"2023-06-22T19:03:29Z","name":"local-rke-state","namespace":"fleet-local","resourceVersion":"129156","uid":"b7ea30a0-0024-4d92-83e8-d8ab01c66127"},"type":"rke.cattle.io/cluster-state"}
  creationTimestamp: "2023-06-22T21:09:59Z"
  name: local-rke-state
  namespace: fleet-local
  resourceVersion: "132410"
  uid: 19fba33b-4d49-4dc1-befa-fb8ee562e220
type: rke.cattle.io/cluster-state
```

![Screenshot from 2023-06-22 14-50-57](https://github.com/harvester/harvester/assets/5370752/7bd22153-b7f8-47c0-b8e0-0c85d5051622)
![Screenshot from 2023-06-22 14-48-02](https://github.com/harvester/harvester/assets/5370752/f7bb51b6-864c-486a-ba8e-e814b845704f)
![Screenshot from 2023-06-22 13-57-13](https://github.com/harvester/harvester/assets/5370752/fa5ad6d9-6ee7-4309-8b75-82e1d18eff7f)


I'll go ahead and close this out :smile:
