### ISSUE TITLE
[BUG] Harvester node becomes unresponsive when updating from 1.1.1 => 1.1.2 or installing 1.1.2 when Intel E810 NIC bond is created 

### ISSUE THREAD

**Issue by moon-kim** [harvester/harvester#3860]
**Describe the bug**
Harvester node becomes unresponsive when updating from 1.1.1 to 1.1.2 or installing 1.1.2 when Intel E810 NICs bond is created.

**To Reproduce**
1. Update from a harvester node with 1.1.1 to 1.1.2 with Intel E810 NIC bond. The issue seems to be similar to this issue from suse linux: https://www.suse.com/support/kb/doc/?id=000020969
2. Or try to install harvester 1.1.2 and select Intel E810 NIC as management interface, then a bond gets created automatically and the os freezes

**Expected behavior**
 Intel E810 NIC can be used in bond.

**Environment**
 - Harvester 1.1.2
 - Underlying Infrastructure (Baremetal with Dell PowerEdge R6615):

**Additional context**

**Comment by w13915984028** [comment]
@moon-kim What is your server detailed type? Is it `Baremetal with Dell PowerEdge R6615` as listed above, thanks.

cc @bk201 @starbops

**Comment by w13915984028** [comment]
@moon-kim could you help pick some logs:

Install v112, unitil it is hanging in network setup page, use try`Alt + F2` or `Alt + F3` unitl `Alt + F6` to switch to another shell, `rancher/rancher` to login, `sudo -i dmesg`.   (`Alt + F1` to switch back to install UI)

If it is not able to switch to shell, try to reboot the NODE, in the Install first page, try again to switch to shell and pick log.

We will know if there is something wrong, thanks.

**Comment by moon-kim** [comment]
On the former Dell PowerEdge, we installed 1.1.1 again. I could reproduce the same problem with a Dell PowerEdge R750xa:

When trying to switch to shell while the system is hanging, it shows only a black screen. With Alt + F1 I could still switch back to install UI, which remains unresponsive. 

We cannot pick the log from the first page, because the idrac KVM of dell has no possibilities to copy the generated log. I created a screenshot, but I hardly imagine that it is helpful:

![image](https://github.com/harvester/harvester/assets/76114025/68c381b2-598b-44ca-ad23-4a1eb77828e2)

Be assured that we can reproduce the problem, whenever we tried to setup network for the Intel E810 NIC.

**Comment by moon-kim** [comment]
The exact model of the network card is: Intel(R) Ethernet 100G 2P E810-C Adapter

**Comment by moon-kim** [comment]
On current Ubuntu 22.04.2 we have got exakt the same problem, which we can resolve by installing the official intel ice driver 1.11.14.
https://www.intel.com/content/www/us/en/download/19630/intel-network-adapter-driver-for-e810-series-devices-under-linux.html

**Comment by w13915984028** [comment]
@moon-kim Thanks for your help.

We have received a couple of similar reports, they all have **Intel E810 NIC used on servers**.

**In the Harvester v1.1.2 ISO installation UI**, 
(1) if it directly runs to apply networkk, switch to other tty via `Alt+F2...Alt+ F6`  wont work, system hang, nothing can be done except rebooting the server.

(2) before applying network, use `Alt+F2` to open tty2, user can log into shell and run commands;   then `Alft + F1` switch back to installation UI, continue to apply network, the UI  will hang, luckily user can still use `Alt+F2` to switch to the already opened tty2, but in shell a command like `ip link` will also hang there, Ctrl+C won't work.

**When user tries to upgrade from v1.1.2 to v1.2.0, the NODE will also hang if it has Intel E810 NIC.**

We are adding this specific case of **Inter E810 NIC** to Harvester v1.1.2 DOC at first,  https://github.com/harvester/docs/pull/311,  

Meanwhile, we are working for patch and final solution, thanks.

**Comment by bk201** [comment]
This should be fixed with `kernel-default-base-5.14.21-150400.24.63.1.150400.24.27.1`.
bsc #1210158

**Comment by guangbochen** [comment]
@moon-kim wondering if u can help to validate this issue with harvester [v1.2.0-rc4](https://github.com/harvester/harvester/releases/tag/v1.2.0-rc4), thanks in advance.

**Comment by bk201** [comment]
Test with Equinix metal instance `a3.large.x86` that has an E810 card:
```
Ethernet controller: Intel Corporation Ethernet Controller E810-C for SFP (rev 02)
```

- iPXE installation succeeds, and the cluster runs well.
- System doesn't freeze after adding the NIC into a bonding device.

```
2: eno12399: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:b8 brd ff:ff:ff:ff:ff:ff
    altname enp51s0f0
3: eno12409: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:b9 brd ff:ff:ff:ff:ff:ff
    altname enp51s0f1
4: eno12419: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:ba brd ff:ff:ff:ff:ff:ff
    altname enp51s0f2
5: eno12429: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:bb brd ff:ff:ff:ff:ff:ff
    altname enp51s0f3
6: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:b8 brd ff:ff:ff:ff:ff:ff
    inet 147.28.157.201/31 scope global mgmt-br
       valid_lft forever preferred_lft forever
    inet 86.109.14.248/32 scope global mgmt-br
       valid_lft forever preferred_lft forever
7: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP group default qlen 1000
    link/ether 40:a6:b7:a0:96:b8 brd ff:ff:ff:ff:ff:ff
```

**Comment by bk201** [comment]
Close since we verified in Equinix Metal and one partner also verified 1.2.0-rc6 works for them.

**Comment by belgaied2** [comment]
This issue is marked as closed, however, I do not see a suggestion solution for upgrading, neither a KB article for working around it.

**Comment by Vicente-Cheng** [comment]
> This issue is marked as closed, however, I do not see a suggestion solution for upgrading, neither a KB article for working around it.

Hi @belgaied2, 
I thought a kernel update fixed this issue.
You could check on this [comment](https://github.com/harvester/harvester/issues/3860#issuecomment-1547050687)

It is contained in the v1.2.0 release. That might be why you do not find the apparent suggestion here.

**Comment by Martin-Weiss** [comment]
And how do we upgrade 1.1.1 to 1.2.0 when we have this type of NIC? Is it supported to skip 1.1.2?

**Comment by Vicente-Cheng** [comment]
IIRC, we have v1.1.3, which will include this kernel fix.
For the upgrade, v1.1.1 should be able to upgrade to v1.1.3. However, I am not really sure about the upgrade matrix.
cc @bk201 might have a clear answer.

**Comment by bk201** [comment]
Yeah, this will require an upgrade to 1.1.3 first.
