### ISSUE TITLE
[Question] When a harvester host unexpected shutdown or reboot, the VMs on the host will not failover to the other nodes on the cluster

### ISSUE THREAD

**Issue by demimraz** [harvester/harvester#3864]
I have a four nodes harvester cluster. No node selector setting on the nodes which means the VMs can be scheduled on each node. When I tried live migration, it worked fine with random 0~4 ping lost. But if I tried to shutdown or reboot one node, the VMs on the node will be shutdown until the mode came back. Is it a normal behavior? 

https://harvester.github.io/tests/manual/hosts/negative-reboot-node/

**Comment by w13915984028** [comment]
@demimraz 

At the moment, A VM can be live-migrated manually, or maintain the NODE. 

In your case, the system has no further automatic action yet. thanks.

Please refer:

https://docs.harvesterhci.io/v1.1/vm/live-migration/#starting-a-migration

https://docs.harvesterhci.io/v1.1/host/#node-maintenance

**Comment by Borisyang3321** [comment]
May I ask when Harvester is expected to support this feature? Thanks

**Comment by w13915984028** [comment]
Not planned yet, need to collect requirements and define user sotries at first. It will be kind of auto-migration strategy for user to configure/enable, certain controller watchs it and triggers the action when un-planned rebooting/shutdown happens.

If wanted, please try to define your user story/requirements here. Thanks.

**Comment by w13915984028** [comment]
connect with https://github.com/harvester/harvester/issues/3600, https://github.com/harvester/harvester/issues/3880, they are the fundmental features of auto-migration

**Comment by w13915984028** [comment]
update:

Harvester has a feature `vm-force-reset-policy`, am checking how to work smoothly in such scenario, thanks.

The feature targets to delete VM based POD when the hosted NODE is not ready for certain time.

**Comment by w13915984028** [comment]
Close as finished in v1.3.0.

Refer: https://github.com/harvester/harvester/issues/3896#issuecomment-1916248492
