### ISSUE TITLE
[Question] Support channels?

### ISSUE THREAD

**Issue by mohaa7** [harvester/harvester#3870]
Apart from this GitHub issues section, are there any online groups we can chat with about this product? (in places like IRC, Discord, or Slack)

**Comment by w13915984028** [comment]
Please visit https://slack.rancher.io/    `Rancher Users -> harvester`

It is also listed in GH: https://github.com/harvester/harvester#community

![image](https://user-images.githubusercontent.com/31133476/236790962-b741f9d6-c5e9-454b-af44-3d24eb470aa5.png)

**Comment by w13915984028** [comment]
Finished.
