### ISSUE TITLE
[BUG]  project member can't view the created volume on the UI

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3873]
**Describe the bug**

The volume list does not display any created data

**To Reproduce**
- Install Rancher
- Import Harvester
- Go to the Harvester cluster from `Virtualization Management`
- Create a project `test`, and add a project member for the project `test`
- Log in as the project member, create a namespace `test`
- Go to the Volume page and create a volume
- Volume created successfully
- There seems to be a bug in the UI, we can not see the created volume)

**Expected behavior**

Users can see the created volume data

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verifing on `master-398d492b-head` (05/11) with Rancher v2.6.12

### Result
* With Rancher `project_member` have `member` permission on the 
   1. Customized project with namespace `test`
   2. Customized namespace `default-public` on `Default` project

* We can create volume with user `project_member` and display correctly  
  ![image](https://github.com/harvester/harvester/assets/29251855/c8061b7b-5d33-4fce-a9e5-b4790b400787)

### Test Information
* Test Environment: single nodes Harvester bare machines
* Harvester version: `master-398d492b-head` (05/11)
* Rancher version: v2.6.12

### Verify Steps

1. Install Rancher
2. Import Harvester
3. Create a user `project_member` as standard user in Rancher 
4. Go to the Harvester cluster from Virtualization Management
5. Create a project `test`, and add the `project_member` for the project test
6. Log in as the `project_member`, create a namespace test
7. Go to the Volume page and create a volume
8. Can create volume successfully
9. Refresh the volume page, should display the created volume

**Comment by TachunLin** [comment]
Verified **Failed** on Rancher v2.7.2. Blocked by issue #3895. Move the issue to ready for testing. 

When we access Harvester from Rancher v2.7.2 virtualization management, create a project test and set user project_member to the member of test project.

After we login with project_member and try to access Harvester, it will display The page could not be found

![image](https://github.com/harvester/harvester/assets/29251855/7c7e49f5-fc8e-40f9-97fb-08133e3e05ba)

**Comment by khushboo-rancher** [comment]
Moved it back to implement as this is not working with Rancher v2.7

**Comment by guangbochen** [comment]
@WuJun2016 after this issue is fixed and verified please help to cut a `harvester-v1.1.2-patch1` release, and we will also need to update the upgrade doc and maybe the release note. cc @bk201

**Comment by WuJun2016** [comment]
Hi @TachunLin 
These are two different issues, and the problem is steadily recurring in the following way https://github.com/rancher/dashboard/pull/8890#issue-1711665829

After refreshing the page, it should work normally. I think we can proceed with testing this issue because they are not interdependent.

**Comment by TachunLin** [comment]
Remove the blocker issue of #3895 since we can refresh the Rancher and enter Harvester from virtualization management as the workaround. 

Verifing **fixed** on `master-942e20a5-head` (05/12) with Rancher v2.7.2. Close this issue. 

### Result
* With Rancher `project_member` have `member` permission on the 
   1. Customized project with namespace `test`
   2. Customized namespace `default-public` on `Default` project

* We can create volume with user `project_member` and display correctly  
![image](https://github.com/harvester/harvester/assets/29251855/885a5772-48e7-4d56-8428-3115343bacc3)


### Test Information
* Test Environment: single nodes Harvester bare machines
* Harvester version: `master-942e20a5-head` (05/12)
* Rancher version: v2.6.12 and v2.7.2

### Verify Steps
https://github.com/harvester/harvester/issues/3873#issuecomment-1544255105

**Comment by LucasSaintarbor** [comment]
Hi @WuJun2016 @TachunLin, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [ ] New documentation/KB
- [ ] Updated documentation/KB
- [ ] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!

**Comment by WuJun2016** [comment]
> Hi @WuJun2016 @TachunLin, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following?
> 
> * [ ]  New documentation/KB
> * [ ]  Updated documentation/KB
> * [ ]  Release note
> * [ ]  None of the above
> 
> If it does, may you please open a PR or share details on what needs to be created or updated? Thanks!

@LucasSaintarbor  I think that this issue does not require adding documentation for the v1.2.0 release. Instead, we need to update the upgrade document for v1.1 and add a release note.

https://github.com/harvester/harvester/issues/3873#issuecomment-1549303972

 cc @bk201  @guangbochen

**Comment by bk201** [comment]
I suggest putting the info in the [known issue section](https://github.com/harvester/harvester/releases/tag/v1.1.2) of the v1.1.2 release note, including a link to the workaround (how to apply the `harvester-v1.1.2-patch1` ui-index). Or create a known issues section in the v1.1 document. The [known issues section](https://docs.harvesterhci.io/v1.1/upgrade/v1-1-to-v1-1-2#known-issues) of the upgrade is mainly for upgrade-related issues.
