### ISSUE TITLE
[Question] same circumstance of ping function issue.

### ISSUE THREAD

**Issue by bingo4933** [harvester/harvester#3876]
I got a chance to rebuild harvester with latest version(1.1.2)

I meet the same issue to the early one on #3283 

summary of issue again:
- create the fist VM, but can't ping GW
- it worked to ping function after the second VM creation.

the same at this time
```
[root@firstvm ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ae:b4:eb:ee:c1:27 brd ff:ff:ff:ff:ff:ff
    inet 10.138.181.2/24 brd 10.138.181.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::acb4:ebff:feee:c127/64 scope link 
       valid_lft forever preferred_lft forever
[root@firstvm ~]# ping 10.138.181.1
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
^C
--- 10.138.181.1 ping statistics ---
650 packets transmitted, 0 received, 100% packet loss, time 648999ms

[root@firstvm ~]# ping 10.138.181.1
PING 10.138.181.1 (10.138.181.1) 56(84) bytes of data.
64 bytes from 10.138.181.1: icmp_seq=9 ttl=64 time=0.704 ms
64 bytes from 10.138.181.1: icmp_seq=10 ttl=64 time=0.729 ms
64 bytes from 10.138.181.1: icmp_seq=11 ttl=64 time=0.652 ms
64 bytes from 10.138.181.1: icmp_seq=12 ttl=64 time=0.636 ms
64 bytes from 10.138.181.1: icmp_seq=13 ttl=64 time=0.732 ms
64 bytes from 10.138.181.1: icmp_seq=14 ttl=64 time=0.641 ms
64 bytes from 10.138.181.1: icmp_seq=15 ttl=64 time=0.710 ms
64 bytes from 10.138.181.1: icmp_seq=16 ttl=64 time=0.703 ms
64 bytes from 10.138.181.1: icmp_seq=17 ttl=64 time=0.687 ms
64 bytes from 10.138.181.1: icmp_seq=18 ttl=64 time=0.717 ms
64 bytes from 10.138.181.1: icmp_seq=19 ttl=64 time=0.672 ms
64 bytes from 10.138.181.1: icmp_seq=20 ttl=64 time=0.663 ms
64 bytes from 10.138.181.1: icmp_seq=21 ttl=64 time=0.632 ms
^C
--- 10.138.181.1 ping statistics ---
21 packets transmitted, 13 received, 38% packet loss, time 19999ms
rtt min/avg/max/mdev = 0.632/0.682/0.732/0.049 ms
```

@tjjh89017 
as your request in comment
```
Could you help us to provide some info below to debug?
Thanks a lot

Create a support bundle and upload to us.
How to create your VM. You could give us the VirtualMachine CRD for vm1 & vm2
VM1 & VM2 are in the same host or not?
what's your harvester network config and vlan config. and we need the net-attach-def of your VM.
While VM1 cannot ping, could you help us to login to the harvester node of VM1, execute the following command and send us the result? (Please do those twice, for VM1 only, and VM1 & VM2 are existing and pingable)

bridge -c vlan show
ip link
ip addr
Thanks a lot
```

could you please help support explanation or command?
1. how to make `support bundle` 
2. what's or how to get `VirtualMachine CRD` ? is it VM's yaml file
3. vm1 and other vm which they are on the same host.

at this time in harvester 1.1.2 installation,  I will upload these files as below while `firstvm` cann't ping.
```
bridge-vlan-show-while-firstvm-cannot-ping.output
ip-addr-while-firstmv-cannot-ping.output
ip-link-while-firstmv-cannot-ping.output
```

then, I will upload attachment after the second vm creation.
```
bridge-vlan-show-while-secondvm-creation.output
ip-addr-while-secondvm-creation.output
ip-link-while-secondvm-creation.output
```

Thanks a lot for help.

Regards,

**Comment by bingo4933** [comment]
here is related yaml and output files
[05-09.zip](https://github.com/harvester/harvester/files/11431625/05-09.zip)

**Comment by bk201** [comment]
Cc @yaocw2020 please take a look.

**Comment by yaocw2020** [comment]
Please try to disable `net.bridge.bridge-nf-call-iptables`.
```
sysctl -w net.bridge.bridge-nf-call-iptables=0
```

**Comment by devclef** [comment]
> -

Hi, here from https://github.com/harvester/harvester/issues/3924 

@yaocw2020  That solves the issue -- specifically executing it on the harvester node which the VM is running on is what is needed. The setting on the VM makes no difference whether set or unset.

Reverting it back to enabled (1) on the harvester node, brings back the issue!

Let me know here or in the other ticket what more I can do to help with this. 

On VM
```
#net.bridge.bridge-nf-call-iptables=0 on harvester host
root@rancher:/home/dopey# curl 10.21.10.3
<a href="https://10.21.10.3/">Found</a>.

#net.bridge.bridge-nf-call-iptables=1 on harvester host (Curl hangs)
root@rancher:/home/dopey# curl 10.21.10.3
^C
#net.bridge.bridge-nf-call-iptables=0 on harvester host (works immediately again)
root@rancher:/home/dopey# curl 10.21.10.3
<a href="https://10.21.10.3/">Found</a>.

root@rancher:/home/dopey# 
```

**Comment by iosifnicolae2** [comment]
any idea on what's causing the real issue?

In our case, we observed that by setting `net.bridge.bridge-nf-call-iptables=1`, TCP fragments coming from `veth` interfaces were reconstructed in `mgmt-br`, and the ping with size 5000 bytes was failing.

**Comment by devclef** [comment]
I still experience this.

Fresh v1.2.0 cluster
Rancher(Addon)
RKE2 cluster provisioned

Nodes will hang claiming issues towards rancher. 

Work around is setting the iptables above. 

There is a single NIC, with single cluster network defined. There is multiple tagged vlans coming into the nic, and tagged vlan VM networks created. I can provide logs or support if helpful

**Comment by SeanKnight** [comment]
Fresh v1.2.0 cluster, 3 dual nic nodes 802.3ad, VLANS
Rancher(Addon)
Manually create bast node in Harvester
Can't reach Rancher from bast node
Lookup IP of Rancher and see that it uses the Harvester VIP
Can ping the VIP and the host nodes, can't reach them on HTTPS
Reinstall without 802.3ad, put mgmt on first nic with a vlan, setup VM network for second nic with other vlan
Works

**Comment by connorkuehl** [comment]
If anyone here still has the appetite to help collect iptables logs to see why the packets are being filtered, I left some instructions on how to do so here: https://github.com/harvester/harvester/issues/3960#issuecomment-1834160541

**Comment by bk201** [comment]
cc @mingshuoqiu

**Comment by mingshuoqiu** [comment]
@bingo4933 per the description of the bug report, could you help attach the output of the following command executed on the management node? I expect to see the vlan and route settings on `mgmt-br` and the `veth` interface.
```
bridge -d vlan show
ip route show
```
