### ISSUE TITLE
[ENHANCEMENT] remove rke1 harvester cpu max value limit

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3878]
**Is your enhancement related to a problem? Please describe.**

Currently, when creating a guest cluster through rke1, there is a maximum value limit for the CPU set at 32, which is not very appropriate. We should remove this limitation.

**Describe the solution you'd like**

Remove the maximum value limit.

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested with Harvester `master-2dc1dc0d-head`, and Rancher `v2.7-5a8b3bd03fb13b3d87aa38bdd25568de5a119b74-head`. I was able to add the node template with 4444 cpus and it was marked as unschedulable, but it did try to create.
![Screenshot_20230531_200635](https://github.com/harvester/harvester/assets/83787952/dc2605e9-2601-499f-ade0-88edc16fadbd)

>   The reproduce steps/test steps are at:
> 
> 1. install rancher use `rancher-2.7-head`
> 2. import a harvester
> 3. go to rancher` Golbal Settiings` page
> 4. You need to make sure that the value of ui-index is `https://releases.rancher.com/ui/latest2/index.html`
> 5. Click `Cluster Management` menu,
> 6. Choose `Harvester`, create `RKE1` cluster
> 7. The cpu inside the template should be able to fill in numbers greater than 32
>    ![image](https://user-images.githubusercontent.com/24985926/241598471-bb85c3a8-852f-4663-a12c-480165df2dbe.png)
