### ISSUE TITLE
[BUG] v1.2.0 Welcome to Harvester page has Server URL and it is editable

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3886]
**Describe the bug**

A newly installed v1.2.0 cluster with master-head local built ISO image, in the `Welcome to Harvester` page, the `Server URL` is exposed and editable.
![image](https://github.com/harvester/harvester/assets/31133476/b963c2a2-8e12-4f3c-8fed-c2f79f9775e8)

**To Reproduce**
1. Install v1.2.0 in KVM VM
2. Https to VIP

**Expected behavior**

ServerURL should be invisiable, or read-only

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM

**Additional context**

**Comment by w13915984028** [comment]
cc @WuJun2016

**Comment by w13915984028** [comment]
reproduced in another v1.2.0-master-head release, built&installed today

<img width="640" alt="image" src="https://github.com/harvester/harvester/assets/31133476/5c237cbc-ea97-47e3-9499-67aa55a1f6e7">

**Comment by n313893254** [comment]
Can not reproduce with Harvester master (5/17) (https://releases.rancher.com/harvester/master/harvester-master-amd64.iso). 

@w13915984028 Could you provide the YAML when you are reproducing it? 

```
kubectl get features.management.cattle.io multi-cluster-management -oyaml

apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  creationTimestamp: "2023-05-17T04:12:52Z"
  generation: 1
  name: multi-cluster-management
  resourceVersion: "1257"
  uid: 489a585b-6294-4f81-b8fc-10cf4040fd9f
spec:
  value: null
status:
  default: false
  description: Multi-cluster provisioning and management of Kubernetes clusters.
  dynamic: false
  lockedValue: null
```

**Comment by w13915984028** [comment]
@n313893254    my v1.2.0 cluster was built and set-up yesterday

```
harv120:~ # kubectl get features multi-cluster-management -oyaml
apiVersion: management.cattle.io/v3
kind: Feature
metadata:
  creationTimestamp: "2023-05-16T15:21:23Z"
  generation: 2
  name: multi-cluster-management
  resourceVersion: "9073"
  uid: 10837c9e-c86f-4a6d-8aa2-38a55da963e1
spec:
  value: null
status:
  default: true
  description: Multi-cluster provisioning and management of Kubernetes clusters.
  dynamic: false
  lockedValue: true
```

**Comment by w13915984028** [comment]
@n313893254 @ibrokethecloud could it be related to `mcm` feature ?

**Comment by WuJun2016** [comment]
> @n313893254 @ibrokethecloud could it be related to `mcm` feature ?

After installing Harvester, users need to configure a password and log in before they can enable the MCM (Multi-Cluster Management) related features. Therefore, I believe there is no direct relationship between the two.

**Comment by w13915984028** [comment]
@WuJun2016 please double check
https://github.com/harvester/harvester-installer/pull/468
https://github.com/harvester/harvester/pull/3894

**Comment by noahgildersleeve** [comment]
Tested in v1.2.0-rc1. Verified that you can still edit the URL
![Screenshot_20230524_162848](https://github.com/harvester/harvester/assets/83787952/74b181ca-0a38-468b-8c3b-4e6ce9eda06c)

**Comment by irishgordo** [comment]
When testing off of master-head 2d5a3a9a - it can not be edited:
![Screenshot from 2023-05-24 16-33-19](https://github.com/harvester/harvester/assets/5370752/32de6575-ca72-42a1-ae3b-897d27a2456b)

**Comment by irishgordo** [comment]
When upgrading from v1.1.2 -> Harvester  Version: master-2d5a3a9a-head
After the upgrade is present, there is no `server url` adjustment available on the main login screen as `server url` has been set prior to upgrade and isn't unset.
![Screenshot from 2023-05-25 13-11-05](https://github.com/harvester/harvester/assets/5370752/ab43095e-3fa2-42f1-a2c8-5ba575670358)
![Screenshot from 2023-05-25 13-09-58](https://github.com/harvester/harvester/assets/5370752/3077079a-aacc-44d6-bb93-4ac8c25b8e91)

**Comment by irishgordo** [comment]
I'm going to go ahead and close this out as this has been fixed on master-head releases since testing and seems to no longer be an issue :smile: :+1:
