### ISSUE TITLE
[ENHANCEMENT] UI related enhancement on rancher-monitoring addon

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3887]
**Is your enhancement related to a problem? Please describe.**

In one newly installed v1.2.0 master-head cluster:

1. All addons are disabled by default
![image](https://github.com/harvester/harvester/assets/31133476/ea324faa-132e-460a-875f-5196f3c6ee8c)

2. When navigating to 'Monitoring`, it does not hint to enable `monitoring`, by contrast, the `Logging` has such info.
![image](https://github.com/harvester/harvester/assets/31133476/5f6a8948-6e45-4a68-bf26-c011073ec353)

3. When `rancher-monitoring` addon is enabled, the `dashboard` page, shows grafana side-bar, it is different with v1.1.2.
![image](https://github.com/harvester/harvester/assets/31133476/20050b55-d0e8-4466-a596-752fbd7fbd5d)

**Describe the solution you'd like**

1. Add hint to enable monitoring addon
2. Keep cluster-metrics and vm-metrics same as v1.1.1

**Describe alternatives you've considered**

**Additional context**

cc @DaiYuzeng

**Comment by khushboo-rancher** [comment]
Validation - PASS

Validated on 1.2.0-rc1

1. By default all the addons are disabled.
2. Enabling monitoring message is in place.
    a. Monitoring disabled
      
<img width="1426" alt="Screenshot 2023-05-24 at 4 37 52 PM" src="https://github.com/harvester/harvester/assets/60111667/24b55da0-b69b-4c73-ad35-4e064888d81b">
   
   b. Monitoring enabled, Alerting disabled.
   
<img width="1050" alt="Screenshot 2023-05-24 at 4 46 54 PM" src="https://github.com/harvester/harvester/assets/60111667/cd386277-1bf6-4c6e-aae2-e256b9b40370">

3. Grafana monitoring dashboard is normal.
<img width="1504" alt="Screenshot 2023-05-24 at 4 44 57 PM" src="https://github.com/harvester/harvester/assets/60111667/a792873c-9540-4c47-bd30-96d4d1c79a59">
