### ISSUE TITLE
[BUG] When we use project_member user access Harvester it display page not be found on Rancher v2.7.2

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3895]
**Describe the bug**

When we access Harvester from Rancher v2.7.2 virtualization management, create a project `test` and set user `project_member` to the `member` of test project. 

After we login with `project_member` and try to access Harvester, it will display `The page could not be found` 

![image](https://github.com/harvester/harvester/assets/29251855/533a59fa-71a4-441a-9966-7d9bc6589f1d)

https://github.com/harvester/harvester/assets/29251855/66ef81f1-05c9-4fb5-aca9-411b983b33ba

**To Reproduce**
1. Import Harvester to Rancher
2. Create a user `project_member` as standard user 
3. Access Harvester from Rancher virtualization management
4. Create a project `test`
5. Given the `project_member` the member role of `test` project 
6. Logout and login with `project_member`
7. Access Harvester from Rancher virtualization management

**Expected behavior**

Can access Harvester with user `project_member` when there already have the member role in `test` project 

**Support bundle**

[supportbundle_5008ea65-2182-4cc9-99a2-ed4b531176d2_2023-05-12T09-44-26Z.zip](https://github.com/harvester/harvester/files/11461713/supportbundle_5008ea65-2182-4cc9-99a2-ed4b531176d2_2023-05-12T09-44-26Z.zip)

**Environment**
 - Harvester ISO version: `master-398d492b-head` (05/11)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine
 - Rancher version: v2.7.2

**Additional context**

This issue did not happen on Rancher v2.6.12

**Comment by TachunLin** [comment]
A quick workaround is we can refresh the page and access Harvester through virtualization management again.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222` with both Rancher `v2.7.7` and `v2.7.9`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.7` & `v2.7.9`
  * Profile: Docker (1C/4G)


## Test Steps
1. Import Harvester to Rancher
2. Create a user project_member as standard user
3. Access Harvester from Rancher virtualization management
4. Create a project test
5. Given the project_member the member role of test project
6. Logout and login with project_member
7. Access Harvester from Rancher virtualization management

* Rancher `v2.7.7`

  https://github.com/harvester/harvester/assets/2773781/8cb37e41-9a26-4f6e-928a-a87d4ecc6333

* Rancher `v2.7.9`
  
  https://github.com/harvester/harvester/assets/2773781/2017452a-4a82-4340-937f-6c8e847bae7f
