### ISSUE TITLE
[ENHANCEMENT] Harvester supports VM `auto-migration` when HOST is accidently down

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3896]
**Is your enhancement related to a problem? Please describe.**

Any HOST in the cluster could be down/off in the cluster accidently, the VMs will NOT be migrated to other NODEs automatically now.

**Describe the solution you'd like**

Harvester supports `auto-migration`, it will monitor the NODEs, in certain defined cases, migrate the affected VMs to other NODEs when possible.

For those VMs which are not able to be migrated, e.g. has CD/container disk attached, Harvester has places to warn the customer, and has menus to `check the possibility of migration`.

**Describe alternatives you've considered**

**Additional context**

Related issues:

[Question] When a harvester host unexpected shutdown or reboot, the VMs on the host will not failover to the other nodes on the cluster
https://github.com/harvester/harvester/issues/3864

VMs with CD ROM Container or Container Disk Migrate When Node is in Maintenance Mode
https://github.com/harvester/harvester/issues/3600

[ENHANCEMENT] Harvester supports new option to eject CD automatically after VM installation
https://github.com/harvester/harvester/issues/3880

**The user story is being added continuously. Welcome your new feedbak, thanks.**

**Comment by w13915984028** [comment]
Note, Harvester has following features, but sees not working fully as expectation, under investigation now.

The feature targets to delete VM based POD when the hosted NODE is not ready for certain time.

<img width="398" alt="image" src="https://github.com/harvester/harvester/assets/31133476/fc09f70c-814f-48ef-995c-c03862b871dc">

**Comment by guangbochen** [comment]
It is common to ignore the default `node-monitor-grace-period` time(5 minutes) in k8s, so the force-reset controller will only begin to work after 10 minutes(5 minutes + $vm-force-reset value), and this is not well documented on both the UI and doc, we should add more description to it.

**Comment by w13915984028** [comment]
@guangbochen For #3864 , any insights ? could it be related to the detach/unmout failure of volume ?

**Comment by bk201** [comment]
@w13915984028 Can you check if the issue is still relevant? I guess we fixed the issue that a migration takes too long while a node is down.

**Comment by w13915984028** [comment]
This feature is implemented by Harvester setting `vm-force-reset-policy`, it depends on the detection of `node status change`. It is the last way to force reset a VM and then it is scheduled to other nodes.

Due to known issue https://github.com/harvester/harvester/issues/4033, the VM may stuck in `deleting` because the volume can't be un-mounted. Fortunately, in Harvester v1.3.0, the bug will be fixed.

Close this issue as finished.
