### ISSUE TITLE
[Question] How to Disable PCI Devices Addon

### ISSUE THREAD

**Issue by albertkohl-monotek** [harvester/harvester#3897]
hopefully a simple question? how can i disable the PCI Devices Addon? i no longer need it, but the disable option is disabled in the addon menu.

**Comment by w13915984028** [comment]
try the right-side `edit` menu on addon page.

if no success, try `kubectl get addons.harvesterhci.io -A`, then edit the related one, change `enabled` to false.

**Comment by albertkohl-monotek** [comment]
edit menu worked. you have to select config and then you and disable it. but if you click it, it's grayed out. i guess i should have looked for the "config" option!

**Comment by w13915984028** [comment]
solved.
