### ISSUE TITLE
[ENHANCEMENT] support elemental cloud-init via harvester-node-manager

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#3902]
**Is your enhancement related to a problem? Please describe.**

Extend harvester-node-manager to support elemental cloud-init

**Describe the solution you'd like**

With v1.2.0 we will be introducing changes for ntp-server setting via the harvester-node-manager.
This already sets up the base for leveraging elemental for configuring node settings at runtime.
We should look at extending this to include support for elemental cloud-init or subset or cloud-init instructions.
This can be used for ensuring node OS level configuration via k8s crds. 

---

Requirements drawn from: https://github.com/harvester/harvester/pull/4713

CloudInit controller

- [x] MatchSelector field describes which nodes the CloudInit CR applies to
- [x] Paused field disables syncing the file to the node while Paused == true
- [x] Filename is the base name (i.e., `a.yaml` -> `/oem/a.yaml`)
- [x] Contents is an Elemental cloud-init-style file
- [x] Emits a Kubernetes event when it modifies a file on disk that includes which file, CloudInit resource, and node were involved
- [x] Maintains the status on the CloudInit resource which provides an "at-a-glance" summary of how a CloudInit resource is rolled out across the cluster
- [x] Removes a file from `/oem` if its corresponding CloudInit object is deleted or if the match selector is updated and the node no longer matches

File watcher

- [x] Installs inotify watch on `/oem`. If a file is modified that corresponds to a CloudInit resource, it will enqueue the CloudInit object so the controller may reconcile it

---

**Describe alternatives you've considered**

**Additional context**

Ability to configure OS level changes by NodeConfig crds will allow us to leverage GitOps based approaches to address backup/restores.

**Comment by ibrokethecloud** [comment]
related to: https://github.com/harvester/harvester/issues/3263

once implemented users should be able to define a cluster/node state via git repo + fleet.

**Comment by w13915984028** [comment]
connect this feature with following
epic: https://github.com/harvester/harvester/issues/3261
sub-story: https://github.com/harvester/harvester/issues/4450

**Comment by connorkuehl** [comment]
Added requirements that came out of the HEP review process to the original comment

**Comment by irishgordo** [comment]
Opening, https://github.com/harvester/harvester/issues/5110 , as it seems that there may be an issue with building `CloudInit` resource from a `gitrepo.fleet.cattle.io` baked into Harvester

**Comment by irishgordo** [comment]
Additionally, noting: https://github.com/harvester/harvester/issues/5119

**Comment by irishgordo** [comment]
Additionally, noticed: https://github.com/harvester/harvester/issues/5130

**Comment by irishgordo** [comment]
@connorkuehl  - do you feel that it makes sense to go ahead and close this out :smile: - as pending those other open issues?

**Comment by irishgordo** [comment]
@connorkuehl - based on that there are just the docs & hep ( that are currently open ) and the other item for the UI is moved to v1.4.0 Milestone I'm going to go ahead and close this out as the feature functionality (w/out UI or Terraform) looks good :smile: :+1:
