### ISSUE TITLE
[BUG] VM Clones Don't Copy Over `metadata.annotations.harvesterhci.io/reservedMemory` key or value

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3912]
**Describe the bug**
Clone VMs do not copy the original VM's `metadata.annotations.harvesterhci.io/reservedMemory` - the key & value are missing

**To Reproduce**
1. Go to create a vm
1. Provide a reserved memory count for the vm (good for windows vms)
1. Clone the vm
1. Check both `edit as yaml` and also just the `config -> advanced options -> show more`

**Expected behavior**
When cloning the VM, the VM will truly be a clone with a 1:1 from the original VM

**Environment**
 - Harvester ISO Version: master-c9d8825c-head 
 - Underlying Infrastructure: 3 Node HP Proliant Bare Metal Cluster
 
**Additional context**
![Screenshot from 2023-05-16 12-34-17](https://github.com/harvester/harvester/assets/5370752/08e99ce8-4f7e-4207-a2d0-287008f6701b)

**Comment by WuJun2016** [comment]
This is a clone that contains the volume data.
<img width="1608" alt="image" src="https://github.com/harvester/harvester/assets/24985926/ea772dde-ce7c-40ad-8833-d79be71f176c">

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/5dcae6a1-99bd-4d2a-8cb0-5ef8e03178bb)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-d739c2a4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create VM `vm1` with **Reserved Memory** (in advanced options) added
4. Clone `vm1` into `vm2` with volume data
5. `vm2` should also have **Reserved Memory** configured and the value should be the same as `vm1`
