### ISSUE TITLE
[BUG] ejectcdrom didn't remove containerDisk volume(cd-rom type)

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3914]
**Describe the bug**

enjectcdrom didn't remove containerDisk volume(cd-rom type)

![image](https://github.com/harvester/harvester/assets/15064560/078cc529-f037-45d1-b24e-845fc619e735)

this will cause migration error
![image](https://github.com/harvester/harvester/assets/15064560/78049a3d-7644-4287-a6d3-7ae2583eaf4f)

more info: https://github.com/harvester/harvester/issues/2910#issuecomment-1550476502

**To Reproduce**
1. Create a windows vm from iso template
2. Enject all cd-rom disk by `EnjectCDROM`
3. check yaml by `Edit Yaml`

**Expected behavior**

containerDisk volume should be removed

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/15858e3f-ae7b-4747-804f-9aeb044a6c1a)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-d739c2a4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create VM `vm1` with Container volume `type:cd-rom`
4. `vm1 should started successfully
5. Click VM **Eject CDROM** option, the container volume should able to be select to delete
6. Select container volume to eject, it should be ejected successfully
