### ISSUE TITLE
[BUG] Failed to snapshot a shutdown virtual machine (only master branch)

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3917]
**Describe the bug**

![image](https://github.com/harvester/harvester/assets/15064560/fa4e0189-bf8b-4622-b2e5-43ab9ba106ce)

**To Reproduce**
1. Create a vm
2. shutdown the vm
3. take vm snapshot

**Expected behavior**

vm snapshot should be ready for use after a while

**Support bundle**

**Environment**
 - Harvester ISO version: master branch
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
will be fixed by https://github.com/harvester/harvester/pull/3910

**Comment by noahgildersleeve** [comment]
I tested this on `master-d739c2a4-head` with the above steps.

**To Reproduce**
Steps to reproduce the behavior:
1. Create a vm
2. shutdown the vm
3. take vm snapshot

I still saw the error message briefly before it resolved. It was up for around 10 seconds or so. Is that acceptable @futuretea ? 

![Screenshot_20230518_172301](https://github.com/harvester/harvester/assets/83787952/11dfc5f5-c9ca-4a85-ab5c-17287210adf3)

![Screenshot_20230518_172308](https://github.com/harvester/harvester/assets/83787952/edc4d98f-1761-4dc5-bcd5-41070edce209)

**Comment by futuretea** [comment]
> I still saw the error message briefly before it resolved. It was up for around 10 seconds or so. Is that acceptable

@noahgildersleeve, sounds like a bug,  I will check it today. move this issue to implement

**Comment by futuretea** [comment]
> I still saw the error message briefly before it resolved. It was up for around 10 seconds or so. Is that acceptable

@noahgildersleeve, This is another issue, and the root cause of this issue is different and the severity level is different, so I created a new issue to track it: https://github.com/harvester/harvester/issues/3938
moved this issue to `Testing`

**Comment by noahgildersleeve** [comment]
Tested with v1.2.0-rc1 with previous repro steps.  No error message was seen

> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Create a vm
> 2. shutdown the vm
> 3. take vm snapshot
