### ISSUE TITLE
[BUG]VM can't start or migrate after reinstall harvester

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#3918]
**Describe the bug**

I have 3 node of harvester.
I changed the system disk from RAID-1 to RAID-0 then reinstall harvester on it, but I faced some problem:
1. I can't migrate a VM from one node to another node.
2. I can't start a VM which is off before reinstall harvester, it stuck at `Containers with unready status: [compute]` and raised an error that `AttachVolume.Attach failed for volume "pvc-7e98d58d-e894-465c-a82f-f53f669eeabc" : rpc error: code = DeadlineExceeded desc = volume pvc-7e98d58d-e894-465c-a82f-f53f669eeabc failed to attach to node harvester2`.
3. Some VM lost network connection after migration.

**To Reproduce**
1. Create a 3 nodes harvester cluster.
2. Change a node into Maintained Mode, delete this node, and reinstall harvester on this node then join the cluster using the same hostname.

**Expected behavior**

I can migrate and start VM from off status.

**Support bundle**

[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2023-05-17T08-24-54Z.zip](https://github.com/harvester/harvester/files/11495829/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2023-05-17T08-24-54Z.zip)

**Environment**
 - Harvester ISO version:  v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R740

**Additional context**

**Comment by W0n9** [comment]
I think I have found the problem. It is a problem linked to longhorn.
I run `kubectl get replicas.longhorn.io -n longhorn-system` , and found that longhorn claims to have a replica on the node, but the path cannot actually be found on the node.
I delete this bad replica then wait longhorn to rebuild a new replica, and it backed to normal.

**Comment by chrisho** [comment]
Just as you mentioned, delete the bad replica before migration to enable successful VM migration.
