### ISSUE TITLE
[ENHANCEMENT] polish the description of monitoring and logging addons

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3921]
**Is your enhancement related to a problem? Please describe.**

UI has description for each addons, the `rancher-monitoring` and `rancher-logging`'s descriptions need to be updated

**Describe the solution you'd like**

A draft description for them:

`rancher-monitoring is an addon to collect Harvester cluster and VM metrics, view them on embedded dashboard, send alert to remote servers.
`
`rancher-logging is an addon to collect versatile logs, events and audits from the Harvester cluster and route them to many kinds of servers based on flows.`

**Describe alternatives you've considered**

**Additional context**

EPIC:
https://github.com/harvester/harvester/issues/3262

**Comment by w13915984028** [comment]
cc @WuJun2016 @DaiYuzeng

**Comment by khushboo-rancher** [comment]
Validated on master-2d5a3a9a-head

Validation - **Failed**

The description for logging is switched with monitoring.
<img width="1346" alt="Screenshot 2023-05-24 at 4 08 35 PM" src="https://github.com/harvester/harvester/assets/60111667/e8c244a2-f3ba-44f7-af30-88f19f7d5fa3">

**Comment by khushboo-rancher** [comment]
Validated on v1.2-a5e74302-head

Validation - LGTM

<img width="1688" alt="Screenshot 2023-05-25 at 5 38 00 PM" src="https://github.com/harvester/harvester/assets/60111667/ab5cfa37-d31d-4644-86a8-dcd483819dab">
