### ISSUE TITLE
[BUG] - Harvester UI shows upgrade "Pending" when nodes joining a cluster using 1.1.2 ISO on an upgraded cluster (1.1.1->1.1.2)

### ISSUE THREAD

**Issue by RegisHubelia** [harvester/harvester#3926]
**Describe the bug**
The Harvester UI shows upgrades are pending on nodes that were joined using ISO 1.1.2 on a cluster that was upgraded from 1.1.1 to 1.1.2.

**To Reproduce**
1. install a 1.1.1 cluster
2. upgrade it to 1.1.2
3. join a new node
4. the UI shows the upgrade is sucessfull but shows "Pending" on nodes that were joined via 1.1.2 installation ISO after an upgrade

![image](https://github.com/harvester/harvester/assets/25985730/39137d29-61ad-4227-9289-1a6e77c10d17)

**Expected behavior**
I would expect either to see that the upgrade is done or not see the new nodes at all in the UI.

**Environment**
 - Harvester ISO version: 1.1.1 upgraded to 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by chrisho** [comment]
Hi @RegisHubelia 

Do you mean that join the new node during upgrading?

**Comment by RegisWeduLabs** [comment]
No, the nodes were joined about 1 week after a successful (not without some workarounds described in the docs) update...

**Comment by chrisho** [comment]
cc @bk201

**Comment by RegisWeduLabs** [comment]
Last upgrade, I did not have this behaviour.  Closing as it seems resolved.
