### ISSUE TITLE
[BUG] kdump failed to start in Harvester 1.1.2 

### ISSUE THREAD

**Issue by tresegiangi** [harvester/harvester#3928]
**Describe the bug**
kdump failed to start when Harvestewr 1.1.2 is running on debug mode

**To Reproduce**
1. From Grub start the "Hervester (Debug)" item in the menu list in order to collect kernel crash dump
2. Enter via cli or ssh and perform  "systemctl status kdump.service" 

**Expected behavior**
I expect that kdump service is up and running 

**Support bundle**

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**
I have kernel crash when running Harvester 1.1.2 in normal mode. So I run the debug version to collect the kernel logs and dumps, but nothing is reported in "/var/crash" directory, Checking the kdump service It is failed to start. Attached I reported the logs when starting the server (first log using journalctl, the second starting the service manually).
  
[log.txt](https://github.com/harvester/harvester/files/11501973/log.txt)
[log2.txt](https://github.com/harvester/harvester/files/11501974/log2.txt)

There is some parameters/configurations that is missing?
Thanks in advance for the reply.

**Comment by masteryyh** [comment]
@tresegiangi Thanks for reporting this bug.
I already worked out a fix, the `kdump.service` can start normally, but the crash report still not generated, I need more time to investigate this.

**Comment by irishgordo** [comment]
@masteryyh this looks great :smile: :+1: !

Tested off of v1.2 branch, from harvester-installer building the artifacts:
```
Drive current: -outdev '/go/src/github.com/harvester/harvester-installer/dist/artifacts/harvester-master-amd64.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data,  401g free
xorriso : UPDATE : 646 files added in 1 seconds
Added to ISO image: directory '/'='/tmp/tmp.Ob1BShOXXL'
xorriso : NOTE : Copying to System Area: 512 bytes from file '/tmp/tmp.Ob1BShOXXL/boot/x86_64/loader/boot_hybrid.img'
xorriso : UPDATE : Writing:      49152s    1.8%   fifo 100%  buf  50%
xorriso : UPDATE : Writing:     610208s   22.1%   fifo  99%  buf  50%  828.7xD 
xorriso : UPDATE : Writing:    1181913s   42.8%   fifo 100%  buf  50%  844.3xD 
xorriso : UPDATE : Writing:    1753088s   63.4%   fifo 100%  buf  50%  843.4xD 
xorriso : UPDATE : Writing:    2321264s   84.0%   fifo  99%  buf  50%  839.2xD 
ISO image produced: 2764219 sectors
Written to medium : 2764240 sectors at LBA 48
Writing to '/go/src/github.com/harvester/harvester-installer/dist/artifacts/harvester-master-amd64.iso' completed successfully.

image-lists/
image-lists/harvester-extra-master.txt
image-lists/rancher-images-v2.7.5-rc5.txt
image-lists/harvester-images-master.txt
image-lists/harvester-repo-images-master.txt
image-lists/rancherd-bootstrap-images-master.txt
image-lists/rke2-images.linux-amd64-v1.25.9-rke2r1.txt
image-lists/rke2-images-multus.linux-amd64-v1.25.9-rke2r1.txt
╭─mike at suse-workstation-team-harvester in ~/Projects/masteryyh-harvester-installer/harvester-installer on v1.2✔
╰─± git log | head -n 5 
commit 15523694d5bdf83e831b9cc46facb417615ef065
Author: masteryyh <yanhong.yang@suse.com>
Date:   Mon May 29 10:57:21 2023 +0800

    Specify --xz explicitly when calling dracut to make initrd.

```

I'll go ahead and close this out :smile: 
![Screenshot from 2023-07-03 12-05-21](https://github.com/harvester/harvester/assets/5370752/c684beb4-35ca-4b69-809d-7f096828a953)
![Screenshot from 2023-07-03 12-04-41](https://github.com/harvester/harvester/assets/5370752/60955f89-2245-4312-829c-7b87a522d308)
![Screenshot from 2023-07-03 11-53-39](https://github.com/harvester/harvester/assets/5370752/f1b4da05-d47c-4c86-a21e-93207176cf8f)
![Screenshot from 2023-07-03 11-53-20](https://github.com/harvester/harvester/assets/5370752/122f95b4-a79a-4ea2-a725-afceda95fc70)
![Screenshot from 2023-07-03 11-52-03](https://github.com/harvester/harvester/assets/5370752/93f92287-223e-49d1-96e7-e10ab80d0c18)
