### ISSUE TITLE
[BUG] Windows 11 Enterprise VM Fails `Replace Existing` from Snapshot

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3929]
**Describe the bug**
When `Replacing Existing` vm from Snapshot - restore hangs for 15~min - vm never becomes running

**To Reproduce**
1. Create a Windows 11 Enterprise Eval VM, w/ 100G main vol - following other steps [outlined in windows vm in harvester docs](https://docs.harvesterhci.io/dev/vm/create-windows-vm#volumes-tab)
1. Install Driver -> then install Windows
1. Eject CD ROM & Container Disk
1. Take Snapshot
1. Restore "new" first (creating new vm from snapshot) - ensure running
1. Take snapshot of "new" vm (based on snapshot of prior vm)
1. Stop "new" vm
1. `Replace Existing` w/ snapshot on "new" VM
1. Note it hangs, VM never starts

**Expected behavior**
On NVMe Based storage "restore" for replace existing on windows vm would succeed.

**Support bundle**
[supportbundle_a28daacd-3732-4413-be4a-2879e4439fd7_2023-05-17T19-41-26Z.zip](https://github.com/harvester/harvester/files/11501981/supportbundle_a28daacd-3732-4413-be4a-2879e4439fd7_2023-05-17T19-41-26Z.zip)

**Environment**
 - Harvester ISO Version: master-25d478c0-head 
 - Underlying Infrastructure: 3 Node Bare-Metal HP Proliant

**Additional context**
![Screenshot from 2023-05-17 12-45-11](https://github.com/harvester/harvester/assets/5370752/a40e3a8e-e266-407e-a15b-ec007294da9d)
![Screenshot from 2023-05-17 12-39-56](https://github.com/harvester/harvester/assets/5370752/fa6634ec-7c3c-45f9-8b1c-b4bfd94b5b16)
![Screenshot from 2023-05-17 12-39-08](https://github.com/harvester/harvester/assets/5370752/6a0e5287-be99-4cbb-bcd1-817faad2d320)
![Screenshot from 2023-05-17 12-26-37](https://github.com/harvester/harvester/assets/5370752/f9dce824-646a-45d8-b6b9-46cd51c73af8)
![Screenshot from 2023-05-17 12-25-35](https://github.com/harvester/harvester/assets/5370752/e4472061-4582-413f-bd55-6b3eb3dbb90c)
![Screenshot from 2023-05-17 12-24-46](https://github.com/harvester/harvester/assets/5370752/35ef6999-b43c-4778-bf94-7b5c2cfddc9d)

**Comment by futuretea** [comment]
The root cause is the same as this https://github.com/harvester/harvester/issues/3917
(need use longhorn v1beta2 client to mount longhorn volume)

**Comment by futuretea** [comment]
will be fixed by https://github.com/harvester/harvester/pull/3910

**Comment by irishgordo** [comment]
Thanks for the fix @futuretea  - this looks good on the latest master-head Harvester Version: master-d739c2a4-head 
:+1: :smile: 

![Screenshot from 2023-05-18 15-50-46](https://github.com/harvester/harvester/assets/5370752/9efdb270-c35d-4bac-bc65-091414995384)

I'll go ahead and close this out
