### ISSUE TITLE
[BUG] `\t* Variables not supported"` when passing Harvester Remote Configuration w/ Addons

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3930]
**Describe the bug**
When passing Addons map in Harvester Remote Configuration at Interactive ISO install time, install fails `\t* Variables not supported`

**To Reproduce**
1. Create configuration enabling logging and monitoring via addons
1. Provide configuration URL to Harvester during interactive iso

**Expected behavior**
Addons passed in the configuration that yield:
```
Addons:map[rancher_logging:{Enabled:true ValuesContent:} rancher_monitoring:{Enabled:true ValuesContent:}]
```
Shouldn't cause `\t* Variables not supported` error during interactive iso install on single node Harvester

**Environment**
 - Harvester ISO Version: master-25d478c0-head 
 - Underlying Infrastructure: qemu/kvm
 
**Additional context**
```go
time="2023-05-17T21:22:05Z" level=info msg="Local config (merged): {SchemeVersion:1 ServerURL: Token:*** OS:{AfterInstallChrootCommands:[] SSHAuthorizedKeys:[ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIBzZT+yXkr28BJzki4WdisefgyR1hKMXWlJCd9KfajEm ssh-ed25519 AAAAC3Nz
aC1lZDI1NTE5AAAAIE2eLlYwcrlf2AGg2P/2jG0GwVE6FT1H/SUHcHMyByWV] WriteFiles:[] Hostname:test Modules:[kvm vhost_net] Sysctls:map[] NTPServers:[0.suse.pool.ntp.org] DNSNameservers:[192.168.1.251] Wifi:[] Password:*** Environment:map[] Labels:map[] PersistentState
Paths:[]} Install:{Automatic:false Mode:create ManagementInterface:{Interfaces:[{Name:enp1s0 HwAddr:52:54:00:0a:d6:87} {Name:enp1s0 HwAddr:}] Method:dhcp IP: SubnetMask: Gateway: DefaultRoute:true BondOptions:map[miimon:100 mode:active-backup] MTU:0 VlanID:0}
 Vip:192.168.122.170 VipHwAddr:46:ac:39:6d:7e:de VipMode:dhcp ForceEFI:true Device:/dev/vda ConfigURL:https://raw.githubusercontent.com/irishgordo/scratch-dump/main/test-vm.yaml Silent:false ISOURL: PowerOff:false NoFormat:false Debug:false TTY: ForceGPT:fals
e ForceMBR:false DataDisk: Webhooks:[] Addons:map[rancher_logging:{Enabled:true ValuesContent:} rancher_monitoring:{Enabled:true ValuesContent:}] Harvester:{StorageClass:{ReplicaCount:0} Longhorn:{DefaultSettings:{GuaranteedEngineManagerCPU:<nil> GuaranteedRe
plicaManagerCPU:<nil>}}}} RuntimeVersion: RancherVersion: HarvesterChartVersion: MonitoringChartVersion: SystemSettings:map[] LoggingChartVersion:}"
```

Was using:
[https://raw.githubusercontent.com/irishgordo/scratch-dump/main/test-vm.yaml](https://raw.githubusercontent.com/irishgordo/scratch-dump/main/test-vm.yaml)

As the remote url harvester configuration
Cross-Ref: https://github.com/harvester/harvester/issues/3235#issuecomment-1548754124

![Screenshot from 2023-05-17 14-22-53](https://github.com/harvester/harvester/assets/5370752/a18a6a2c-54e7-41b2-b78e-7772d94fb5bd)

**Comment by w13915984028** [comment]
@irishgordo I check below yaml file, there is no `\t`  (TAB) included, does your original test file have any tab included? thanks.
https://raw.githubusercontent.com/irishgordo/scratch-dump/main/test-vm.yaml

I used the yaml file included in this PR, it works normally.
https://github.com/harvester/harvester-installer/pull/402

**Comment by irishgordo** [comment]
@w13915984028 running:
```bash
╭─mike at suse-workstation-team-harvester in ~/Projects/scratch-dump on main✘✘✘
╰─± file test-vm.yaml 
test-vm.yaml: ASCII text
╭─mike at suse-workstation-team-harvester in ~/Projects/scratch-dump on main✘✘✘
╰─± cat -A test-vm.yaml 
scheme_version: 1$
token: token$
install:$
  mode: create$
  management_interface:$
    interfaces:$
      - name: enp1s0$
    method: dhcp$
  force_efi: true$
  device: /dev/vda$
  addons:$
    rancher_logging:$
      enabled: true$
    rancher_monitoring:$
      enabled: true$
```
From: 
https://man7.org/linux/man-pages/man1/cat.1.html
I notice:
>        -T, --show-tabs
>              display TAB characters as ^I
> 
>       -A, --show-all
>              equivalent to -vET

As far as I can tell the file does not, at least according to `cat` have tabs in it. 
Does the interactive iso install's Remote Harvester Config URL file need additional properties that I'm currently missing?

The `\t` error, denotes that there was an unexpected tab in the configuration or is that noting there's an unexpected tab in the remote harvester url configuration used for the interactive iso?

Is it because I fed it the URL as `https` and not `http`?
>13. (Optional) If you need to customize the host with a [Harvester configuration](https://docs.harvesterhci.io/v1.1/install/harvester-configuration) file, enter the HTTP URL here.
https://docs.harvesterhci.io/dev/install/iso-install

I'll try to feed it the configuration over http, not https and see.

**Comment by irishgordo** [comment]
@w13915984028 I tried just over HTTP not HTTPS and it's yielding the same result:

![Screenshot from 2023-05-18 17-34-25](https://github.com/harvester/harvester/assets/5370752/3d198928-890a-4066-9403-22ca54b9e3d2)
![Screenshot from 2023-05-18 17-33-31](https://github.com/harvester/harvester/assets/5370752/21319172-3079-4417-8474-de10b273d54d)

[console-new-test.log](https://github.com/harvester/harvester/files/11512461/console-new-test.log)

**Comment by irishgordo** [comment]
Would the `merging` of the Local config file add a tab somewhere?
```bash
...
level=info msg="Local config (merged): {SchemeVersion:1 ServerURL: Token:***
... 
```

**Comment by irishgordo** [comment]
Just tested on [harvester-master-head #b90f8de8](https://drone-publish.rancher.io/harvester/harvester/1013)

**Comment by w13915984028** [comment]
@irishgordo 

I misunderstood the issue at before, ineed, the error is from following code, harvester processing code has finished, there is no error in the `harvester-cofiguration` file.

![image](https://github.com/harvester/harvester/assets/31133476/09130156-414e-4804-9754-7bdd99312dbf)

in your config, there is
```
force_efi: true$
```
please check your KVM VM's firmware, by default, it is `BIOS`, modify either to validate again. thanks.
![image](https://github.com/harvester/harvester/assets/31133476/1b28f628-124a-4ff4-8822-4cd9ce07fefb)

**Comment by w13915984028** [comment]
Smoothly reproduced it with `force_efi: true` in the configuration file.

![image](https://github.com/harvester/harvester/assets/31133476/4b4210f2-80ac-4a95-b844-27e73656bc11)

![image](https://github.com/harvester/harvester/assets/31133476/c99be5e5-6f89-4002-9ec1-36ec35920604)

**Comment by irishgordo** [comment]
@w13915984028  ahh, thank you for explaining that more.
The problem was indeed the `force_efi: true` - as the VM was created with BIOS and not UEFI x86_64.
The addon configuration works as expected :smile: 

I'll go ahead and close this out :+1:
