### ISSUE TITLE
[BUG] Unable to restore existing vm snapshot after upgrade from v1.1.2 to master

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#3943]
**Describe the bug**

**To Reproduce**
1. Create a VM in Harvester v1.1.2 (a **three nodes** cluster)
1. Take VM snapshot
1. Upgrade Harvester Cluster to master
1. Restore the VM snapshot to Create a new VM
1. The restore VM will stuck in Pending

**Expected behavior**

the restored VM will be Ready

**Support bundle**

[supportbundle_1aacd0f0-be3a-4ad7-bf25-aa999544ad84_2023-05-20T14-01-39Z.zip](https://github.com/harvester/harvester/files/11522495/supportbundle_1aacd0f0-be3a-4ad7-bf25-aa999544ad84_2023-05-20T14-01-39Z.zip)

**Environment**
 - Harvester ISO version: master-b90f8de-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
longhorn issue: https://github.com/longhorn/longhorn/issues/5992

**Comment by bk201** [comment]
To add a doc/release note about this problem.
If a user wants to avoid losing snapshots, he needs to shutdown the VMs to detach volumes.

**Comment by mantissahz** [comment]
The longhorn issue https://github.com/longhorn/longhorn/issues/5992 will be fixed in v1.5.0, v1.4.3 and v1.3.4
Yes, as @bk201 mentioned, the only way is to detach volume first and recommend to backup the volume first.

**Comment by guangbochen** [comment]
This is covered in the LH [v1.4.3-rc1](https://github.com/longhorn/longhorn/releases/tag/v1.4.3-rc1) release, please help to verify it first using the rc version, thanks.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.1.2** -> **v1.2.0-rc4**
* **ui-source** Option: **Auto**

### Verify Steps
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/3943#issue-1718130585
- VM should be restored and started successfully
- Data in VM should be restored to snapshot state

**Comment by LucasSaintarbor** [comment]
Hi @futuretea @lanfon72, just following up on any issue with a `require/doc` label for the 1.2.0 release. Does this issue require any of the following? 

- [ ] New documentation/KB
- [ ] Updated documentation/KB
- [x] Release note
- [ ] None of the above

If it does, may you please open a PR or share details on what needs to be created or updated?
Thanks!
