### ISSUE TITLE
[BUG] Unable to create VM from existing image volume

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3948]
### Describe the bug
![image](https://github.com/harvester/harvester/assets/5169694/b08480c1-674b-4037-8de6-495e16e8b991)

### To Reproduce
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create an image volume `os-disk`
4. Create VM with existing volume `os-disk` and *bootOrder:1*
5. VM should created and started successfully

### Expected behavior
User should able to create VM from the existing Image volume

## Environment:
 - Harvester ISO version: **master-b49e264e-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 3 nodes**

### Additional context
This bug appeared on UI only.

**Comment by bk201** [comment]
@WuJun2016, please help investigate the issue.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://github.com/harvester/harvester/assets/5169694/e087df3d-2aa4-419e-b7bc-2150f54a6763)


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.2.0-rc2**
* **ui-source** Option: **External**

### Verify Steps
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/3948#issue-1719811883
