### ISSUE TITLE
[ENHANCEMENT] Filter list of storage class in `restore snapshot`

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#3949]
### The problem
![image](https://github.com/harvester/harvester/assets/5169694/517c2ef5-5b19-4110-987b-decc5900d1f2)

based on #2405, restoring volume snapshots will list all storage classes of all provisioners, but as the error message above, we can only use storage classes created by the provisioner that same as the source volume, and user can't easily know which storage class is able to be use to restore the snapshot.

### The solution
Showing storage classes only belonging to the source volume's provisioner

### The Alternatives
add provisioner's name after storage class' name

**Comment by bk201** [comment]
@torchiaf Can you help check if we can move to ready for testing and confirm we have this in v1.3.0+. Thanks.

**Comment by irishgordo** [comment]
@torchiaf  - just wanted to ask, is it expected that the list of all storage classes will still be accessible when clicking the dropdown list?

As, it shows the correct storage class by default - but curious if listing all the other available storage classes if the drop down box is clicked is to be expected :smile: 

![Screenshot from 2024-07-08 19-24-57](https://github.com/harvester/harvester/assets/5370752/5eb0593d-a444-4215-8aed-ec30b1822518)
![Screenshot from 2024-07-08 19-24-16](https://github.com/harvester/harvester/assets/5370752/cf2b687c-0f11-4195-918f-5d5c5953536b)

**Comment by torchiaf** [comment]
> @torchiaf - just wanted to ask, is it expected that the list of all storage classes will still be accessible when clicking the dropdown list?

If all those classes belong to the provisioner the behavior is correct, otherwise bug is not fixed.

**Comment by irishgordo** [comment]
@torchiaf  -thanks for that mention - upon building a `rook-ceph-block` based storage class that is utilizing a separate provisioner:
https://github.com/harvester/harvester/issues/2405#issuecomment-1559880174
I can validate that I do only see the storage classes belonging to the provisioner, and upon restore it selects the correct default one - and does indeed exclude the other provisioner's storage-classes
![Screenshot from 2024-07-10 13-16-13](https://github.com/harvester/harvester/assets/5370752/1cb56ec1-3951-4bc8-9391-0c63d0661f1a)
![Screenshot from 2024-07-10 13-05-35](https://github.com/harvester/harvester/assets/5370752/cbdf899f-6166-40e4-b1a2-0852b27b9e11)


This looks good :smile:  :+1:  - I'll go ahead and close this out
