### ISSUE TITLE
[BUG] After upgrade to v1.2.0 master, no rancher-logging and rancher-monitoring exists on Addons page

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#3956]
**Describe the bug**

After we upgrade from v1.1.2 to v1.2.0 master-b49e264e-head, there is no `rancher-logging` and `rancher-monitoring` on the `Addon` page
![image](https://github.com/harvester/harvester/assets/29251855/e239e62a-bbb4-4740-a77c-e136a21fc504)

In comparison with v1.2.0-rc1, we can see the these items exists on the `Addon` page and enable it.
![image](https://github.com/harvester/harvester/assets/29251855/1cd06e2d-e8f0-41dd-8410-1187c5d172d7)

**To Reproduce**
1. Upgrade from v1.1.2 to v1.2.0 master 
2. After upgrade complete, open Addons page
3. Check the content

**Expected behavior**

After upgrade from v1.1.2 to v1.2.0, The `rancher-logging` and `rancher-monitoring` should exists on the `Addons` page.
And we can enable these items too.

**Support bundle**

[supportbundle_ebea348e-b561-4725-8608-26223fe6f392_2023-05-24T05-51-02Z.zip](https://github.com/harvester/harvester/files/11550900/supportbundle_ebea348e-b561-4725-8608-26223fe6f392_2023-05-24T05-51-02Z.zip)

**Environment**
 - Harvester ISO version: master-b49e264e-head (05/22)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes bare machines

**Comment by bk201** [comment]
I guess we need https://github.com/harvester/harvester/pull/3380 
cc @w13915984028

**Comment by w13915984028** [comment]
yes, the upgrade PR is not merged yet

@guangbochen do we have a plan when to start the ugprade test to v1.2.0 ?  thanks.

**Comment by w13915984028** [comment]
No such issue on formal releases.
