### ISSUE TITLE
[BUG] The saved preference will be reset after the page is refreshed

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#3958]
**Describe the bug**

The saved preference will be reset after the page is refreshed  （May not be saved in the api）。

**To Reproduce**
1. go to the preference page and check `Enable 'View in API'`.  
2. Refresh page

**Expected behavior**

Saved configurations should not be reset。

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in dashboard for `master-f9254bf4-head`. As well as upstream Rancher cluster with `v2.7-dbe4b1bc739ae4b06d8b10405bfe5697b164a785-head`. Verified as fixed.
