### ISSUE TITLE
[ENHANCEMENT] Add Cypress automation test for UI.

### ISSUE THREAD

**Issue by masteryyh** [harvester/harvester#3968]
**Is your enhancement related to a problem? Please describe.**

We need a environment to run Cypress automation test for UI.

**Describe the solution you'd like**

1. Install a VM for running tests;
2. Create a Jenkins pipeline and use Vagrant to create a 3 nodes cluster;
3. Run Cypress tests.
4. Upload Cypress test report to Minio
5. View the test report

***Support incremental testing based on the changes in a PR:***
  - [x] Configure the integration between Jenkins and GitHub
  - [x] Configure the Jenkins pipeline
    - [x] Source code management
    - [x] Build environment
    - [x] Build steps
   - [ ] Configure GitHub Webhooks
     - [ ] Require a public endpoint like https://ci.harvesterhci.io/
  - [x] Configure incremental testing scripts. // above @masteryyh 
  - [x] Run Cypress tests with a 3 nodes cluster
  - [x] Upload test report.  // below @n313893254 
  - [x] View test reports
    - [x] View screenshot
 
***Support test Harvester with Rancher:***
- [x] Configure depoloy a Rancher server
- [x] Configure import 3 nodes Harvester cluster to Rancher server
- [ ] Run Cypress test (RBAC)

**Comment by n313893254** [comment]
There is a [case](https://harvester.github.io/tests/manual/virtual-machines/edit-vm-and-insert-ssh-and-check-the-ssh-key-is-accepted-for-the-login/) that needs to use SSH to log in to the VM, and I need @masteryyh  to help generate an SSH key for testing and put it into Cypress image.

**Comment by bk201** [comment]
@masteryyh @n313893254 , @TachunLin will continue finishing the rest of the items. Thanks!

**Comment by TachunLin** [comment]
We will continue to work on the PR https://github.com/harvester/harvester-baremetal-ansible/pull/18 to make the pipeline been merged to master. 

Next step would be fix the failed cypress test items toward v1.3.0-rc.

**Comment by khushboo-rancher** [comment]
>1. Install a VM for running tests;
>2. Create a Jenkins pipeline and use Vagrant to create a 3 nodes cluster;
>3. Run Cypress tests.
>4. Upload Cypress test report to Minio
>5. View the test report

@irishgordo As mentioned in the task description, cypress test is running everyday on Jenkins. We have achieved what was expected from this ticket. If any item is remaining, let's create those tickets in the test repo and we'll track those there.
