### ISSUE TITLE
[BUG] failed to update status subresource: prometheuses.monitoring.coreos.com "rancher-monitoring-prometheus" not found

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#3969]
**Describe the bug**

After bumping `rancher-monitoring` to latest release `102.0.0+up40.1.2`

https://github.com/harvester/harvester/issues/3780
https://github.com/harvester/harvester-installer/pull/492

https://github.com/harvester/harvester/issues/3780#issuecomment-1550187525

comparing to Harvester v1.1.2, after upgrade rancher-monitoring to `102.0.1+up40.1.2` in Harvester v1.2.0, a new error from `rancher-monitoring-operator-76476f6486-jl9gh` is found.

> level=error ts=2023-05-16T18:40:42.151369158Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status "cattle-monitoring-system/rancher-monitoring-prometheus" failed: failed to update status subresource: prometheuses.monitoring.coreos.com "rancher-monitoring-prometheus" not found"

```
...
level=info ts=2023-05-16T18:40:40.097052363Z caller=operator.go:1390 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="sync prometheus"
level=info ts=2023-05-16T18:40:40.099566719Z caller=operator.go:753 component=alertmanageroperator key=cattle-monitoring-system/rancher-monitoring-alertmanager msg="sync alertmanager"
level=info ts=2023-05-16T18:40:42.122103431Z caller=operator.go:1559 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="update prometheus status"

level=error ts=2023-05-16T18:40:42.151369158Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"cattle-monitoring-system/rancher-monitoring-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"rancher-monitoring-prometheus\" not found"
```

**To Reproduce**
1. Install v120 cluster with the PR https://github.com/harvester/harvester-installer/pull/492
2. Enable `rancher-monitoring` addon from Harvester WebUI
3. Wait until the addon is deployed
4. Check the log of `rancher-monitoring-operator-*`

**Expected behavior**

The error message is gone.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM, single-node cluster

**Additional context**

**Test**
Test steps are described in PR https://github.com/harvester/harvester-installer/pull/492

**Comment by jonathon2nd** [comment]
I am also seeing this error, but I do not use harvester.

```
level=info ts=2023-06-06T16:12:27.310105857Z caller=operator.go:1390 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="sync prometheus"
level=info ts=2023-06-06T16:12:27.31056516Z caller=operator.go:1559 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="update prometheus status"
level=error ts=2023-06-06T16:12:27.384378052Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"cattle-monitoring-system/rancher-monitoring-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"rancher-monitoring-prometheus\" not found"
level=info ts=2023-06-06T16:12:32.294838245Z caller=operator.go:1559 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="update prometheus status"
level=error ts=2023-06-06T16:12:32.312849497Z caller=klog.go:116 component=k8s_client_runtime func=ErrorDepth msg="status \"cattle-monitoring-system/rancher-monitoring-prometheus\" failed: failed to update status subresource: prometheuses.monitoring.coreos.com \"rancher-monitoring-prometheus\" not found"
level=info ts=2023-06-06T16:15:42.785859012Z caller=operator.go:1390 component=prometheusoperator key=cattle-monitoring-system/rancher-monitoring-prometheus msg="sync prometheus"
```

This is on the Rancher management cluster.

![image](https://github.com/harvester/harvester/assets/52681917/5615c616-9af8-4145-b76d-ab04353e6cc9)

**Comment by moshiaiz** [comment]
I'm using Rancher management cluster as well, and it seems like Prometheus operator is not functioning at all.
When adding CRDs such as "ServiceMonitor", operator cannot update it.
Only after restarting the Prometheus pod, I can see the new ServiceMonitor in Prometheus targets.

**Comment by moshiaiz** [comment]
Same as issue: https://github.com/rancher/rancher/issues/43418

The issue is a missing subresource status on prometheuses.monitoring.coreos.com CRD.

To fix this:
I fixed it locally first on the cluster. I edited prometheuses.monitoring.coreos.com CRD changing subresoruces section from:
```
subresources: {}
```
To:  
```
subresources:
   status: {}
```

Now the operator showed no errors in the logs and was able to update ServiceMonitor CRDs, etc.


Then, I looked at Rancher charts page, and found that status is already included in the [prometheuses.monitoring.coreos.com CRD](https://github.com/rancher/charts/blob/release-v2.7.4/charts/rancher-monitoring-crd/102.0.0%2Bup40.1.2/crd-manifest/crd-prometheuses.yaml#L8800-L8801).
So I just reinstalled rancher-monitoring chart on all of my Rancher clusters (with the same version - 102.0.0+up40.1.2) and the correct CRD was deployed. Now the operator works well.

**Comment by w13915984028** [comment]
This issue is reproducable in Harvester v1.2.0 master-head.

First, the `substatus` is correctly defined in the CRD.
https://github.com/rancher/charts/blob/ca5a1fd305a27a8c2bdde00e09e1eaed8b1cd107/charts/rancher-monitoring-crd/102.0.0%2Bup40.1.2/crd-manifest/crd-prometheuses.yaml#L8800

In Harvester, the `rancher-monitoring-crd` is set as a `managedchart`, and run in bootstrap stage, the final `prometheuses crd` is as below, it is not correct.

```
harv41:~ # kk get crd prometheuses.monitoring.coreos.com -oyaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: "2023-06-11T18:47:04Z"
  generation: 1
  name: prometheuses.monitoring.coreos.com
  resourceVersion: "1677"
  uid: 02c44a49-a875-4904-8a20-674586caec5e
spec:
  conversion:
    strategy: None
  group: monitoring.coreos.com
  names:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    singular: prometheus
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        type: object
        x-kubernetes-preserve-unknown-fields: true
    served: true
    storage: true
status:
  acceptedNames:
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    singular: prometheus
  conditions:
  - lastTransitionTime: "2023-06-11T18:47:04Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-06-11T18:47:04Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```

But when we delete this `managedchart` and create it again, the `prometheuses crd` is correct.


Compare with previous version, the `job.yaml` has this important change.
![image](https://github.com/harvester/harvester/assets/31133476/7cd60dfb-b35c-4cab-b5be-ffcf0b703a4c)

And, maybe the root cause is that there is no `update` in RBAC.
[ refer here ](https://github.com/rancher/rancher/issues/43418)
![image](https://github.com/harvester/harvester/assets/31133476/f061b3ae-e272-4c5d-9c63-fcfeb3ee5665)

Will try a fix and report the effect.

**Comment by w13915984028** [comment]
This issue is verified to be fixed with PR https://github.com/harvester/harvester-installer/pull/505 in Harvester cluster:

From the `generation`, it looks this chart/crd was installed&updated twice during the bootstrap stage.

But if we delete the `managedchart` and create it again (already after bootstrap), it is successful.

```
harv41:~ # kk get crd prometheuses.monitoring.coreos.com -oyaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.9.2
  creationTimestamp: "2023-06-11T21:09:48Z"
  generation: 2
  name: prometheuses.monitoring.coreos.com
  resourceVersion: "5260"
  uid: e9af42d6-9c89-421c-a632-785431d21d75
spec:
  conversion:
    strategy: None
  group: monitoring.coreos.com
  names:
    categories:
    - prometheus-operator
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    shortNames:
    - prom
    singular: prometheus
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The version of Prometheus
      jsonPath: .spec.version
      name: Version
      type: string
    - description: The desired replicas number of Prometheuses
      jsonPath: .spec.replicas
      name: Replicas
      type: integer

...


    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    categories:
    - prometheus-operator
    kind: Prometheus
    listKind: PrometheusList
    plural: prometheuses
    shortNames:
    - prom
    singular: prometheus
  conditions:
  - lastTransitionTime: "2023-06-11T21:09:48Z"
    message: no conflicts found
    reason: NoConflicts
    status: "True"
    type: NamesAccepted
  - lastTransitionTime: "2023-06-11T21:09:48Z"
    message: the initial names have been accepted
    reason: InitialNamesAccepted
    status: "True"
    type: Established
  storedVersions:
  - v1
```

**Comment by w13915984028** [comment]
This is another breaking issue in rancher monitoring `102.0.0+up40.1.2`, the upstream issue is https://github.com/rancher/rancher/issues/43418.

cc @guangbochen @bk201 @rebeccazzzz

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc2`, verified as fixed.

## Test Environment
* Harvester
  * version: `v1.2.0-rc2`
  * profile: KVM, single node
  * **ui-source**: Auto

## Verification Steps
1. Enable rancher-monitoring addon 
2. Check rancher-monitoring addon is DeploySuccessful :heavy_check_mark: 
    ![image](https://github.com/harvester/harvester/assets/2773781/f49e10ba-d9fa-4295-84d0-7e1979b50f66)
3. Download support-bundle
4. Check no subresource error in **rancher-monitoring-operator** pod log :heavy_check_mark: 
```
$ kubectl -n cattle-monitoring-system get pods
NAME                                                     READY   STATUS      RESTARTS      AGE
alertmanager-rancher-monitoring-alertmanager-0           2/2     Running     1 (44m ago)   45m
helm-install-rancher-monitoring-qpgvx                    0/1     Completed   0             45m
prometheus-rancher-monitoring-prometheus-0               3/3     Running     0             45m
rancher-monitoring-grafana-7fc56c48dc-2gzlw              4/4     Running     0             45m
rancher-monitoring-kube-state-metrics-65cd94fffc-4s6wb   1/1     Running     0             45m
rancher-monitoring-operator-56f6964d8f-8pzwg             1/1     Running     0             45m
rancher-monitoring-prometheus-adapter-786df96896-ncvtc   1/1     Running     0             45m
rancher-monitoring-prometheus-node-exporter-lwnb6        1/1     Running     0             45m

$ kubectl -n cattle-monitoring-system logs --all-containers rancher-monitoring-operator-56f6964d8f-8pzwg | grep -i 'subresource' 
$ kubectl -n cattle-monitoring-system logs --all-containers rancher-monitoring-operator-56f6964d8f-8pzwg | grep -i 'error' 
```
