### ISSUE TITLE
[BUG] Could not delete VM load balancer if it's not created successfully

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#3970]
**Describe the bug**

Could not delete VM load balancer if it's not created successfully.

**To Reproduce**
1. Create a load balancer with pool. Don't create pool.
2. Try to delete the load balancer.

**Expected behavior**

Delete the VM load balancer successfully.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2.0-rc2`.  Close this issue.

### Result
When we create a load balancer into `Not Ready` state
  1. Create load balancer without pool created
  ![image](https://github.com/harvester/harvester/assets/29251855/7b252532-b9b8-4d38-bbe4-9c330d8585eb)
  2. Create load balancer with no DHCP route 
  ![image](https://github.com/harvester/harvester/assets/29251855/e77c4eee-dc4c-4c51-9b42-ee37e4e35ff1)
  3. Create load balancer with no available IP in Pool 
  ![image](https://github.com/harvester/harvester/assets/29251855/8bd3d27a-c09d-48f4-9a9c-a7c5e16fa5f3)


In all of these cases, we can delete this load balancer correctly. 
  ![image](https://github.com/harvester/harvester/assets/29251855/de4e6334-053d-4449-9dd0-f9f89a164155)



### Test Information
* Test Environment: 4 nodes Harvester bare machines
* Harvester version: v1.2.0-rc2

### Verify Steps
1. Create a vm with external vlan1216  
2. Set the vm with label `app: nginx1`
3. Create a load balancer and select default pool (Auto select), and select `app: nginx1`
4. Delete the `Not Ready` load balancer 
5. Create a load balancer and select DHCP, and select `app: nginx1`
6. Delete the `Not Ready` load balancer
7. Create a IP pool with only one available IP address 
8. Create another vm and set the load blancer to this vm
![image](https://github.com/harvester/harvester/assets/29251855/9632cbfc-916f-41b4-b0e5-a301bcea3304)
9. Create a load balancer and select the pool that already have no available IP to allocate 
10. Delete the `Not Ready` load balancer
