### ISSUE TITLE
[BUG] SR-IOV Virtual Functions can be 0 or -N integers

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#3977]
**Describe the bug**
Can pass in 0 or negative numbers for enabling virtual functions on sr-iov.

**To Reproduce**
1. Go to addons, enable pci devices
1. Goto SR-IOV devices, enable, pass in 0
1. Disable
1. Enable, pass in -230

**Expected behavior**
Not allow negative integers or 0 when specifiying the number of virtual functions on sr-iov

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure: 2 node bare metal

**Additional context**

![Screenshot from 2023-05-25 16-10-05](https://github.com/harvester/harvester/assets/5370752/5bf48032-bfa2-469a-88fe-8b07851e2f2d)

**Comment by irishgordo** [comment]
Not sure if the drafted pr from above fixes what's happening :sweat_smile:  - but was thinking perhaps something along those lines for the implementation of the fix :smile:  - if the fix might work I can un-draft that PR :smile: 

cc: @DaiYuzeng

**Comment by DaiYuzeng** [comment]
Thanks for your dedication! I sent a [PR](https://github.com/irishgordo/dashboard/pull/1) to your branch. Could you take a look when you are free? Thanks!

**Comment by irishgordo** [comment]
Looks great :smile:  - I've gone ahead and merged that in :+1: 
Thanks for the PR addition

**Comment by WuJun2016** [comment]
@DaiYuzeng   We need to raise a pr upstream (component or vue directive) to solve the problem of inputting negative numbers.

**Comment by bk201** [comment]
@torchiaf Can you help check if we can move to ready for testing and confirm we have this in v1.3.0+. Thanks.

**Comment by torchiaf** [comment]
I confirm this has been fixed in 1.2 and 1.3.0. Moving in Ready for tests.

**Comment by irishgordo** [comment]
Thanks for the fix @torchiaf :smile: :+1: 
Validated this looks good on v1.2-head
 Version: v1.2-4db9146e-head 
 
 
![Screenshot from 2024-04-16 14-26-04](https://github.com/harvester/harvester/assets/5370752/a225d686-20d6-456b-b770-8539c570b9dd)
