### ISSUE TITLE
[BUG] IP Pool lack of project when Harvester enable MCM feature

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3984]
**Describe the bug**

![image](https://github.com/harvester/harvester/assets/18737885/2dbe179c-968d-4ef0-8418-87baeffc988e)

**To Reproduce**
1. Install Harvester v1.2.0-rc1 and enable MCM(rancher-manager-support) setting
2. Go to Create an IP pool
3. Check the Scope on the "Selector" tab

**Expected behavior**

MCM Harvester: Show has 3 inputs: "Project", "Namespace" and "Guest k8s cluster"
Single Harvester: Only has one input: "Namespace"

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2-3d1c031a-head` (06/14). Close this issue.

### Result
* Can display Project on multi-cluster environment of both embedded and external Rancher
![image](https://github.com/harvester/harvester/assets/29251855/a7a7dad6-574b-42c1-8f3b-144792ec5682)

* On load balancer, we can see the Pool default option have more detailed description
![image](https://github.com/harvester/harvester/assets/29251855/6789736b-755c-4a53-94db-f10be3224fa1)

* Can display default project provided on Harvester 
![image](https://github.com/harvester/harvester/assets/29251855/5833c29e-383d-4490-8fd9-69fb8bc546b6)

* Can display the newly created project and namespace from multi-cluster   
![image](https://github.com/harvester/harvester/assets/29251855/f6e18bde-1bf6-40bf-91d7-61594a72342b)
![image](https://github.com/harvester/harvester/assets/29251855/0cafbbb9-84b9-4cfc-a6de-9d1c0c286a26)

* Can display ip address with ports on load balancer with default value (8080) 
![image](https://github.com/harvester/harvester/assets/29251855/4e8a5cab-682e-4b50-b596-fc677ad4ee04)



### Test Information
* Test Environment: Single node Harvester on kvm machine
* Harvester version: `v1.2-3d1c031a-head` (06/14)
* Rancher version: v2.7.5-rc4

### Verify Steps
1. Enable embedded rancher or use external Rancher instance 
2. Provision a guest RKE2 cluster on Rancher 
3. Access Harvester from Rancher virtualization management page 
4. Create an IP Pools
5. Check the Project, Namespace and Guest Kubernetes cluster options 
6. Create a new project and namespace 
7. Check the new project and namespace can be found on IP pool page 
8. Create a VM on Harvester with nginx services installed
9. Set the vm labels
10. Create a load balancer, use the default value 
11. Check the load balance IP and port display
