### ISSUE TITLE
[ENHANCEMENT] Show a banner on the Out-of-band Access tab of the Host page when seeder addon disabled.

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#3988]
**Is your enhancement related to a problem? Please describe.**

Currently, if the seeder addon is disabled, it is hidden on the host page. We should display the tab page, hide only the form, and display the banner, providing a prompt to enable the addon on the addon page. For users who do not have permission to enable it, they should contact the cluster administrator.

**Describe the solution you'd like**

Show a banner on the Out-of-band Access tab of the Host page.

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Per discussed, this issue depends on [harvester#2318](https://github.com/harvester/harvester/issues/2318). Should test after harvester#2318 committed.

**Comment by albinsun** [comment]
Referring to the [PR](https://github.com/harvester/dashboard/pull/747), the banner message is determined by 2 variables: `hasSeederAddon` and `hasAddonSchema` with logic:
| seederEnabled==False| $\color{green}{\textsf{hasSeederAddon}}$ | $\color{red}{\textsf{!hasSeederAddon}}$ |
|---|---|---|
| $\color{green}{\textsf{hasAddonSchema}}$ | `Addon "harvester-seeder" is disabled now, click here to enable it.` | `Addon "harvester-seeder" is not exist, please check if it is installed.` |
| $\color{red}{\textsf{!hasAddonSchema}}$ | `Please contact system admin to enable the Out-of-Band Access first.` | `Addon "harvester-seeder" is not exist, please check if it is installed.` |


## Test Plan
* Check "harvester-seeder" is disabled

### TC1: hasSeederAddon and hasAddonSchema
* harvester-seeder is disabled.
* Expectation: `harvester-seeder is disabled: Addon "harvester-seeder" is disabled now, click here to enable it.`

### TC2: NOT hasAddonSchema
* User have no access to addon list
* Expectation: `Please contact system admin to enable the Out-of-Band Access first.`

### TC3: NOT hasSeederAddon
* harvester-seeder does not exist
* Expectation: `Addon "harvester-seeder" is not exist, please check if it is installed.`

**Comment by albinsun** [comment]
Hi @n313893254,

We see unexpect result in TC2 (NOT hasAddonSchema), please help to check.

Thanks

## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: QEMU/KVM, 3 nodes (8C/16G/250G per node)
  * **ui-source**: Auto
* Rancher `v2.7.4`

## Verification
Prerequisite:
1. Import harvester to rancher
2. seeder addon is disabled

### TC1: hasSeederAddon and hasAddonSchema $~~~~$ $\color{green}{\textsf{PASS}}$
1. Login as admin
2. Go to 'Hosts -> node -> Config'
3. 'Out-of-Band Access' shows `harvester-seeder is disabled: Addon "harvester-seeder" is disabled now, click here to enable it.` $~~~~$ :heavy_check_mark: 
![admin](https://github.com/harvester/harvester/assets/2773781/7215a726-3ed6-4c45-9df6-8556f9dc60d0)

### TC2: NOT hasAddonSchema $~~~~$ $\color{red}{\textsf{FAIL}}$
1. Login as cluster-member
2. Go to 'Hosts -> node -> Config'
3. 'Out-of-Band Access' shows `Please contact system admin to enable the Out-of-Band Access first.` $~~~~$ :x:
   > It shows `Addon "harvester-seeder" is not exist, please check if it is installed.`
   > ![clustermember](https://github.com/harvester/harvester/assets/2773781/455a7704-5830-4bd6-85b4-62a8d0e535d3)

**Comment by n313893254** [comment]
@albinsun 

## Test Plan
* Check "harvester-seeder" is disabled

### TC1: hasSeederAddon and hasAddonSchema
* harvester-seeder is disabled.
* Expectation: `harvester-seeder is disabled: Addon "harvester-seeder" is disabled now, click here to enable it.`

### TC2: NOT hasAddonSchema
* User have no access to addon list
* Expectation: Can not see "Out-of-band Access" tab

### TC3: NOT hasSeederAddon
* harvester-seeder does not exist
* Expectation: `Addon "harvester-seeder" is not exist, please check if it is installed.`

**Comment by albinsun** [comment]
## Test Environment
* Harvester
  * version: `v1.2-7f87c261-head`
  * profile: QEMU/KVM, 2 nodes (8C/16G/250G per node)
  * **ui-source**: Auto
* Rancher `v2.7.4`


## Test Cases
### Prerequisite
1. Import harvester to rancher $~~$ :heavy_check_mark:
1. <details><summary> harvester-seeder addon is disabled $~~$ :heavy_check_mark:</summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/9a2faf55-b067-4fcf-921d-c37222fd8e50)

   </details>

### Test Cases
1. hasSeederAddon and hasAddonSchema $~~$ :heavy_check_mark:
   1. Login as **admin**
   2. Go to **Hosts** -> node -> **Config** -> **Out-of-Band Access** tab
   3. Should see `harvester-seeder is disabled: Addon "harvester-seeder" is disabled now, click here to enable it.`
      ![image](https://github.com/harvester/harvester/assets/2773781/a1db0453-18e5-4aad-a07f-98f0dc92b971)

1. NOT hasAddonSchema $~~$ :heavy_check_mark:
   1. Login as **cluster-member**
   2. Go to **Hosts** -> node -> **Config** -> **Out-of-Band Access** tab
   3. Should NOT see "Out-of-band Access" tab
      ![image](https://github.com/harvester/harvester/assets/2773781/45dffcac-c0f4-486f-a917-863d7c5da2ab)

1. NOT hasSeederAddon $~~$ :heavy_check_mark:
   1. Delete harvester-seeder addon in kubernetes
      <details>

      ![image](https://github.com/harvester/harvester/assets/2773781/e794f963-c05d-46a6-8a4f-75250277ee52)
      ![image](https://github.com/harvester/harvester/assets/2773781/793427eb-1e7d-4263-8a01-459d21d6f0cf)

      </details>
   1. Login as **admin**
   1. Should NOT see harvester-seeder in Addons
      <details>
      
      ![image](https://github.com/harvester/harvester/assets/2773781/db97e837-1481-48c1-b436-eb19a1f1bed0)

      </details>
   1. Go to **Hosts** -> node -> **Config** -> **Out-of-Band Access** tab
   1. Should see `Addon "harvester-seeder" is not exist, please check if it is installed.`
      ![image](https://github.com/harvester/harvester/assets/2773781/8fcc555d-235f-40e7-9ba0-68a1dcab5fbd)
   1. Login as **cluster-member**, Should NOT see "Out-of-band Access" tab.
