### ISSUE TITLE
[ENHANCEMENT] Expose more shortcut keys

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#3989]
**Is your enhancement related to a problem? Please describe.**

We should expose more key sequences in vnc console.

- Trigger kernel memory dump via crash in Windows Server (CTRL-SCROLL LOCK-SCROLL LOCK) See https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/forcing-a-system-crash-from-the-keyboard?redirectedfrom=MSDN
- Trigger kernel memory dump via crash in Linux (ALT-SYSRQ-c or depending on keyboard it's ALT-PRINT SCREEN-c) See https://www.kernel.org/doc/html/v4.11/admin-guide/sysrq.html
- Restart X11 Server (CTRL-ALT-BACKSPACE) See https://manpages.opensuse.org/Tumbleweed/xorg-x11-server/xorg.conf.5.en.html
- Access Linux console at tty1 from X11 Server (CTRL-ALT-F1, also CTRL-ALT-F2, etc for other TTYs) See https://manpages.opensuse.org/Tumbleweed/xorg-x11-server/xorg.conf.5.en.html

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

![image.png](https://images.zenhubusercontent.com/60370508fd3d02bfb6c4ba36/39073412-5169-4d7e-8519-6264af5de31e)

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/fa6960eb-b282-479f-858b-f25394a4840f)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2.0-rc2**
* **ui-source** Option: **External**


### Verify Steps:
1. Install Harvester with any nodes
2. Create Image for VM creation
3. Create VM `vm1` and Login via **Web VNC**
4. Click `Custom Shortcut Keys` -> `Management Shortcut Keys` then record customized keys
5. execute `showkey` in console, then click customized shortcut keys via **Custom Shortcut Keys** dropdown button and the same keys via keyboard
6. All shortcut keys from **Shortcut Keys** dropdown list should send the same **keycode** as keyboard
