### ISSUE TITLE
[BUG] Cannot view VM detail page on Rancher Virtualization Management, error "rancher-monitoring" not found.

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#3992]
**Describe the bug**
After creating a VM on the Rancher Virtualization Management cluster, viewing the VM detail page would display the error: "rancher-monitoring" not found. Since the rancher-monitoring default is disabled in v1.2.0-rc1.

**To Reproduce**
1. Import existing v1.2.0-rc1 cluster.
2. Create a VM.
3. Click the created VM name.
![image](https://github.com/harvester/harvester/assets/3347460/bb8bc9cd-0085-487c-a2ad-cadb76417705)

**Expected behavior**
Expect to view the VM detail page.

**Support bundle**

**Environment**
 - Rancher Image Tag: v2.7-head
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
I tested this with Rancher v2.7.2 and Harvester v1.2.0-rc1. This is working there. It might be an issue with the unstable nature of v2.7-head. It will be worth checking once we get RC versions of v2.7.5.

**Comment by noahgildersleeve** [comment]
Tested with Harvester `master-2dc1dc0d-head`, and Rancher `v2.7-5a8b3bd03fb13b3d87aa38bdd25568de5a119b74-head` . 

![Screenshot_20230531_175229](https://github.com/harvester/harvester/assets/83787952/5f27fb37-28a8-4e82-9bfe-99f316915547)
![Screenshot_20230531_175218](https://github.com/harvester/harvester/assets/83787952/cc1ba161-93af-4a7a-adc9-9a4a4e7ca3c2)
