### ISSUE TITLE
no bootable disk found

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#40]
**Description:**
no bootable disk found after creating VM using CDI volume.

**Comment by gitlawr** [comment]
Check the volume/image file being used. For example, in the download list from https://launchpad.net/cirros/+download, `cirros-0.x.x-x86_64-disk.img` is bootable while some others are not.

**Comment by guangbochen** [comment]
@gitlawr can u please help the UI to figure out what filetypes are supported by the kubevirt as a bootable image.
and the UI should only allow uploading those images that are compatible with bootable disk cc @WuJun2016 .

**Comment by gitlawr** [comment]
As far as I can tell there's no deterministic way to validate if the provided image is valid or not.
A single URL does not provide much help for it. We can't rely on the file extension(if there's any) for validation.
Even if we have the downloaded file at hand, it may be a raw image which by definition does not have any bytes serving as the "metadata".

**Comment by guangbochen** [comment]
I agree, but I would prefer to filter out those unsupported filenames and ask the user to make its filename to be compatible with the validation, according to the [official doc](https://kubevirt.io/2019/How-To-Import-VM-into-Kubevirt.html) the supported image formats are:
```
.img
.iso
.qcow2
Compressed (.tar, .gz or .xz) of the above formats.
```
will discuss off-line on this Thursday, thanks.

**Comment by guangbochen** [comment]
as discussed with @gitlawr, we will add validation of the filename extension check, but the user can still continue to upload the file if they choose to ignore the warning message.  cc @WuJun2016

**Comment by gitlawr** [comment]
`.raw` is also commonly used(http://cdimage.debian.org/cdimage/openstack/10.5.0/)

**Comment by guangbochen** [comment]
when creating VM with `.iso` the image user will need to add minimum two disks, the root-disk with boot-order `1` and CDROM disk with boot-order `2` respectively.
we will add some default template so the user can reference it later via https://github.com/rancher/harvester/issues/72

**Comment by guangbochen** [comment]
close in favor of vm template of https://github.com/rancher/harvester/issues/72
