### ISSUE TITLE
[BUG] Volumes removed from VMs cannot be deleted

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#400]
**Describe the bug**
I’ve got two volumes which are not in use which I want to delete.
Even though the volumes are `Ready` and not `In-use`, when I select `Delete` Harvester says the volumes are currently owned…

<img width="1366" alt="Screenshot 2020-12-31 at 20 21 45" src="https://user-images.githubusercontent.com/1175979/103465782-c72b2b80-4d36-11eb-94f9-ae5142b0bd4f.png">

<img width="375" alt="Screenshot 2020-12-31 at 20 22 21" src="https://user-images.githubusercontent.com/1175979/103465786-d4e0b100-4d36-11eb-819a-5400c16b877b.png">

<img width="1366" alt="Screenshot 2020-12-31 at 20 23 33" src="https://user-images.githubusercontent.com/1175979/103465792-e1650980-4d36-11eb-8c57-5ac32b17e153.png">

**To Reproduce**
1. create a VM - do not use the ISO template, instead create 2 volumes, one disk using an ISO image and one disk being the blank you will install the operating system onto.
2. install the operating system and power off the VM
3. edit the created VM to delete that volume from the VM
4. start the VM
5. attempt to delete the volume
6. see the error

**Expected behavior**
The volume should be deleted.

**Environment:**
 - Harvester ISO version: 0.1.0 alpha
 - Installation Mode: ISO
 - Underlying Infrastructure: Baremetal with ASUS PN50

**Comment by DoNotSayYes** [comment]
Validated on master-head
The unmounted volumes can be deleted accordingly
![image](https://user-images.githubusercontent.com/57614736/105165407-44d1a280-5b51-11eb-811f-b7ca1d2d428c.png)
![image](https://user-images.githubusercontent.com/57614736/105165432-4b601a00-5b51-11eb-9660-bf9383c7a74d.png)
