### ISSUE TITLE
[BUG] Backups and snapshots don't restore properly on NFS after upgrade

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4003]
**Describe the bug**

After upgrade from v1.1.2 -> v1.2.0-rc1 backups and VM snapshots aren't restoring. The files are empty.
**To Reproduce**
1. create two new VMs and run through backup tests while the VMs are on
2. Create a snapshot of one of them after the first file operations
3. Upgrade
4. Restore the backups and VM snapshot
**Expected behavior**

The backups/snapshots should restore properly.
**Support bundle**

[supportbundle_4561a7d5-0ffa-401b-80c4-37c54df69b98_2023-05-30T21-52-53Z.zip](https://github.com/harvester/harvester/files/11606374/supportbundle_4561a7d5-0ffa-401b-80c4-37c54df69b98_2023-05-30T21-52-53Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2 -> v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Harvester baremetal on DL160

**Additional context**
I think this is probably just the result of not running sync after the file operations. The VM that was off worked fine. I'll try to reverify this on my next set of upgrade tests
![Greenshot 2023-05-30 14 28 18](https://github.com/harvester/harvester/assets/83787952/3747a281-d147-4636-886b-67123dcb5400)
![Greenshot 2023-05-30 15 09 53](https://github.com/harvester/harvester/assets/83787952/c0958ce7-877d-44dc-8903-6360b986b5d9)

**Comment by bk201** [comment]
Probably can be improved by https://github.com/harvester/harvester/pull/3976

**Comment by guangbochen** [comment]
~~@noahgildersleeve can u PTAL again with v1.2.0-rc2 since #3976 is merged, thanks.~~
may be pending on https://github.com/harvester/harvester/issues/3943, after the upgrade, the snapshot can't be restored correctly.

**Comment by noahgildersleeve** [comment]
I retested this with single node upgrade v1.1.2 -> v1.2.0-rc4. This worked fine with the upgrade and the restores of backups and snapshots worked fine.
