### ISSUE TITLE
[BUG] Edit Harvester cluster did not display admin user as cluster member

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#4008]
**Describe the bug**

- Edit Harvester cluster did not display the admin user as a cluster member
- Click the save button, and the route redirects to the cluster detail page instead of the cluster list page

**To Reproduce**
1. Install Rancher v2.7.3 and Harvester v1.2.0-rc1
2. Import Harvester cluster
3. After the Harvester cluster is ready, edit the cluster and try to add a cluster member

**Expected behavior**

Admin user should display as a cluster owner and save route work as expected.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://github.com/harvester/harvester/assets/18737885/6df0d666-91ce-4e34-9ce3-deb19df91510)

**Comment by n313893254** [comment]
Closed in favor can not reproduce in Rancher v2.7-head

**Comment by n313893254** [comment]
Repon issue because it was accidentally reproduced in the master version

![image](https://github.com/harvester/harvester/assets/18737885/dedfab21-03ec-4a51-b916-5069ef82965c)

**Comment by torchiaf** [comment]
I can't replicate the issue in Rancher >= v2.8.3, everything works as expected. @bk201

**Comment by bk201** [comment]
Thanks, close since can't repro.
