### ISSUE TITLE
[FEATURE] ability to send special keys / key combinations in web VNC console

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#401]
**Is your feature request related to a problem? Please describe.**
I would like to be able to send special keys / key combinations in web VNC console.
These keys / key combinations may include print-screen, ctrl-alt-delete, alt-Fn key, etc...

**Describe the solution you'd like**
Maybe a set of buttons in the web page which send *standard* keyboard keys / key combinations directly to the guest OS?

**Describe alternatives you've considered**
None came to mind.

**Additional context**
It's worth looking at how VirtualBox, VNC, Android and iPad applications do this.

**Comment by DaiYuzeng** [comment]
Hi @DoNotSayYes , we implemented several combination keys:
1. `Ctrl + N` _e.g. open new window in IE_
2. `Ctrl + T` _e.g. open new tab in IE_
3. `Ctrl + W` _e.g. close the tab in IE_
4. `Print Screen` _screenshots were saved at /Users/***/Pictures/Screenshots/** on Windows_
5. `Ctrl + Alt + Delete`

**Comment by futuretea** [comment]
Validated on latest master-head

**Comment by himslm01** [comment]
Can you include F keys and Alt-F keys?

**Comment by shodanx2** [comment]
There is a distinction between the vnc client taking a screenshot itself
And asking the remote system to press the print screen key
I had a specific case where it was exponentially more convenient to take a screenshot using the remote system's own screen grab software.

Maybe a low difficulty solution to take care of all edge cases would simply be a location to enter a keycode and then user can press whatever key they want by using a lookup table
