### ISSUE TITLE
[BUG] Rancher v2.7.3 with Harvester v1.2.0-rc1 "VM Scheduling" translation error

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#4011]
**Describe the bug**

Rancher v2.7.3 with Harvester v1.2.0-rc1 "VM Scheduling" translation error

**To Reproduce**
1. Go to the Harvester cluster
2. Go to create a VM
3. Check "VM Scheduling" tab

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

![image](https://github.com/harvester/harvester/assets/18737885/b42238c9-a8f4-4da4-89a2-bfbc31baca23)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/524f1df2-325b-40d6-af0e-edfb20995f5b)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-d1c90dc4-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-f0d4078f4fa75b303ce276c3f4b12fc465b1ba2a-head** (Docker Image: `sha256:5f03db286465685fa9c912bb6e6dd510a4b6549795c5db0047f66b4697999bc3`)

### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Access Harvester via Rancher _Virtualization Management_
4. Create a image for VM creation
5. Create a VM `vm1`
6. View configuration of `vm1`, tab **VM Scheduling** should display correctly.
