### ISSUE TITLE
[ENHANCEMENT] Add namespace resource quota help text

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#4012]
**Is your enhancement related to a problem? Please describe.**

~Add tooltip about reousouce quota for namespace limit memory~

The message will show on the title around.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc2`

## Test Environment
* Harvester
  * version: `v1.2.0-rc2`
  * profile: KVM, single node
  * **ui-source**: Auto
* Rancher
  * version: `v2.7-0bcf068e1237acafd4aca01385c7c6b432e22fd7-head`

## Verification Steps
1. Login Rancher and Import a Harvester 
1. Go to **Virtualization Management** -> **Harvester Clusters**
1. Click harvester name to enter imported Harvester
1. Go to **Projects/Namespaces**
1. Create a project with limit memory
1. Create a namespace, should see help text :heavy_check_mark: 
    Compare to v1.1.2, do see added help text "**VMs need to reserve additional memory overhead.**"
    ![help_text-120rc2](https://github.com/harvester/harvester/assets/2773781/d924410c-6cb7-4cef-b49a-371ca6175342)

## Note
1. v1.1.2 text
![help_text-112](https://github.com/harvester/harvester/assets/2773781/89fcc35a-db47-47a8-8468-c6fc9900c819)

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc2`, close as fixed.
