### ISSUE TITLE
[BUG] favicon for Harvester is showing as Rancher favicon

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4014]
**Describe the bug**

The Harvester favicon is the Rancher logo
**To Reproduce**
1. Install Harvester cluster
2. Login and navigate to dashboard

**Expected behavior**

It should have the Harvester favicon
**Support bundle**

[supportbundle_ffd3e83f-6995-4f44-bdf5-c4ec6a5c3917_2023-05-31T22-33-37Z.zip](https://github.com/harvester/harvester/files/11619311/supportbundle_ffd3e83f-6995-4f44-bdf5-c4ec6a5c3917_2023-05-31T22-33-37Z.zip)

**Environment**
 - Harvester ISO version: master-2dc1dc0d-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): vagrant ipxe-examples 3 node setup

**Additional context**
This is happening on master-head with virtualized 3 node setup and v1.2.0-rc1 with 1 node bare metal setup.

![Screenshot_20230531_153042](https://github.com/harvester/harvester/assets/83787952/685a8fcf-e5d1-417a-b650-21e3d5681bbd)

**Comment by WuJun2016** [comment]
Hi @noahgildersleeve ,  This is a known issue, and we can test it together with the support for custom icons and names：   https://github.com/harvester/harvester/issues/3396

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/f657021b-be5c-44b4-913d-3b0d8ed78366)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-27934bc3-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, navigating every pages, `favicon` should always presents Harvester's one.
