### ISSUE TITLE
[BUG] Maintenance Mode of Node w/ SR-IOV VFs in Use Causes Cordon & Empty/`null` Error

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4015]
**Describe the bug**
When a node that is being used for its physical Network hardware NIC, that has Virtual Functions (VFs) created on it with SR-IOV, that are currently in use by one or more VMs, the node when put into maintenance mode is cordoned and then when attempting again to enable maintenance mode the error back is `null`

**To Reproduce**
1. Create a 3 node harvester bare metal cluster
2. Enable PCI Devices Add-on
3. Use one host for enabling SR-IOV 
4. Create a VM, adding the SR-IOV Virtual Function, keep it running
5. Attempt to migrate the VM, you will see error as expected
6. Then go to hosts -> enable maintenance mode on the host
7. You will be able to enable maintenance mode, with no error, the host will be in cordon state
8. Attempt to enable maintenance mode again, then error returns with `null` 

**Expected behavior**
Perhaps not have a `null` state on error - or not allow user to put host into maintenance mode until certain criteria is met?

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure: 3 node HP Proliant
 
**Additional context**
![Screenshot from 2023-05-31 15-20-44](https://github.com/harvester/harvester/assets/5370752/083ee298-12bc-44bd-a5a8-af4580e238d2)
![Screenshot from 2023-05-31 15-19-37](https://github.com/harvester/harvester/assets/5370752/e827fdaa-059f-4f05-9e76-827018adfea2)
![Screenshot from 2023-05-31 15-25-24](https://github.com/harvester/harvester/assets/5370752/6774b31d-3777-4caa-b32f-59578219d817)
![Screenshot from 2023-05-31 15-26-22](https://github.com/harvester/harvester/assets/5370752/80b1d8f2-1c46-4ced-955f-caa6b98b638d)

**Comment by ibrokethecloud** [comment]
the `null` error may be transient. I will try and check if i can re-produce it.

We however do need to figure out how we want to handle forced maintenance on node with VM's having pcidevices.

These VM's are non migratable. May be we should treat them like VM's with last healthy replicas, which are shutdown or provide a warning to users that they should power these off.

@bk201 @guangbochen appreciate your feedback on this.

**Comment by irishgordo** [comment]
@ibrokethecloud  I agree, the `null` error does indeed seem to be transient - I am not able to replicate seeing the `null` error.

**Comment by ibrokethecloud** [comment]
Added a check in maintenance api to check for vm's with pcidevices and provide a warning:

![image](https://github.com/harvester/harvester/assets/19664014/e2d627bd-045a-47ba-815e-9081d3f267f3)

once user shuts down these workloads, the node can be placed into maintenance mode.

**Comment by irishgordo** [comment]
After checking, that looks great :smile: :+1: tested on Harvester Version: 2dc1dc0d-dirty 
![Screenshot from 2023-06-01 12-07-57](https://github.com/harvester/harvester/assets/5370752/3dfd6384-cd82-4c69-b66f-e3f314b74823)
![Screenshot from 2023-06-01 12-04-45](https://github.com/harvester/harvester/assets/5370752/4a2c848d-e506-4cb2-be96-a6555a863f36)

I'll go ahead and close this out :smile:
