### ISSUE TITLE
[ENHANCEMENT] Should give a chance to force format or fsck for the corrupted additional disks

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4016]
**Is your enhancement related to a problem? Please describe.**
We could provision additional disks to Longhorn by this section https://docs.harvesterhci.io/v1.1/host/#multi-disk-management.
If the additional disks are corrupted, we cannot force format again by UI. Described the following steps

1. add additional disk /dev/sdb
2. let it corrupted
3. try to remove/re-add this like the following figure.
![截圖 2023-05-31 下午4 01 40](https://github.com/harvester/harvester/assets/1615081/bfa4de18-222d-46fb-a2a2-91c01e9c5a4f)
4. Then, you will see the mount fail.
![截圖 2023-05-31 下午4 02 06](https://github.com/harvester/harvester/assets/1615081/8ab85402-4ba2-4c27-bcd1-37907fe55007)

We could manually force the format again (make it normal and add it back). 

**Describe the solution you'd like**
Give a chance to force format or manually fsck here.

**Describe alternatives you've considered**
We could manually make it normal.

**Additional context**
None

**Comment by n313893254** [comment]
Hi, @Vicente-Cheng. Could we move this issue to ready for testing?

**Comment by Vicente-Cheng** [comment]
> Hi, @Vicente-Cheng. Could we move this issue to ready for testing?

Sure, I miss this one. Thanks for the reminder!

**Comment by irishgordo** [comment]
@Vicente-Cheng & @n313893254  - this looks good, validated that we can indeed force format a corrupted disk :smile: :+1: - I'll go ahead and close this out

Validated on Harvester Version: v1.2-7a8ac2c2-head 


https://github.com/harvester/harvester/assets/5370752/8ea7b708-06b8-4ecc-8678-10aef95fef6a
