### ISSUE TITLE
[ENHANCEMENT] Enable gosec in golint

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#4019]
**Is your enhancement related to a problem? Please describe.**

linter: [gosec](https://github.com/securego/gosec) - Inspects source code for security problems by scanning the Go AST.
rule: [G601 - Implicit memory aliasing of items from a range statement](https://github.com/securego/gosec#usage)

- [x] Harvester network controller - @yaocw2020 
  -  https://github.com/harvester/network-controller-harvester/pull/84
- [x] Harvester load balancer - @yaocw2020 
  - [x] https://github.com/harvester/load-balancer-harvester/pull/15
- [x] Harvester cloud provider - @yaocw2020 
  - [x] https://github.com/harvester/cloud-provider-harvester/pull/32
- [x] harveter/harvester - @futuretea 
  - https://github.com/harvester/harvester/pull/4009
 - [x] harvester/node-manager @Vicente-Cheng 
   - [x] https://github.com/harvester/node-manager/pull/12/
 - [x] harvester/node-disk-manager @Vicente-Cheng 
   - [x] https://github.com/harvester/node-disk-manager/commit/e6c1457751aca6b4a9af71b14b85806cfba7ebd3
 - [x] harvester/harvester-installer @Vicente-Cheng 
   - [x] https://github.com/harvester/harvester-installer/pull/535
 - [x] harvester/pcidevices @ibrokethecloud 
   - https://github.com/harvester/pcidevices/pull/55

**Describe the solution you'd like**
please refer to https://github.com/harvester/harvester/pull/4009 as an example.

**Comment by guangbochen** [comment]
Close this as the `gosec` lint has been added to all of the above repos.
