### ISSUE TITLE
[BUG] Setting the language to none causes the page to mess up

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#402]
**Steps to reproduce:**
On the login page, click the language, setting the language to none

**Result:**
Setting the language to none causes the page to mess up
![image](https://user-images.githubusercontent.com/57614736/103496595-ccdd5a00-4e79-11eb-9e61-3e3e288497d5.png)
![image](https://user-images.githubusercontent.com/57614736/103496829-948a4b80-4e7a-11eb-850b-30119dbb94b7.png)

**Comment by DaiYuzeng** [comment]
@DoNotSayYes 
The option of `none` should only be displayed in develop environment. 
Did you come across this bug in production environment?

**Comment by DoNotSayYes** [comment]
> @DoNotSayYes
> The option of `none` should only be displayed in develop environment.
> Did you come across this bug in production environment?

I installed Harvester in ISO installation way and the iso file was officially released

**Comment by DaiYuzeng** [comment]
API: v1/userpreferences

`dev` of the response data is `true`.

The option of `none` is displayed or hide according to it.

Could you check it? @guangbochen 

![image](https://user-images.githubusercontent.com/15041915/103756420-4a57c480-504a-11eb-9a7a-ed633ad42f21.png)

**Comment by c3y1huang** [comment]
I've also tried with [v0.1.0](https://github.com/rancher/harvester/releases/tag/v0.1.0) ISO and not seeing this issue. Not sure if I'm doing things differently?

However, noticed that my UI didn't get the `Local`, `Kubeconfig`, `Token` tabs as showed [here](https://user-images.githubusercontent.com/57614736/103496595-ccdd5a00-4e79-11eb-9e61-3e3e288497d5.png).

Here is my UI.
![Screenshot-2021-01-14-14:09:16](https://user-images.githubusercontent.com/22583541/104556088-ee102880-5679-11eb-8c8a-f59176a8a4b6.png)

Here is my harvester version from the main console.
![Screenshot-2021-01-14-14:03:02](https://user-images.githubusercontent.com/22583541/104556587-d7b69c80-567a-11eb-98db-a22a49fc78b4.png)

**Comment by guangbochen** [comment]
the default auth mode is `localUser` and is configurable via https://github.com/rancher/harvester/blob/master/deploy/charts/harvester/values.yaml#L251-L253

**Comment by DoNotSayYes** [comment]
Validated on master-head 
![image](https://user-images.githubusercontent.com/57614736/105810935-c2306380-5fe6-11eb-9b2a-ca9b4d52fb28.png)
