### ISSUE TITLE
[BUG] After power off Harvester nodes then power on for days, all VMs display `Stopping` state and can't launch

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4033]
**Describe the bug**

When we have several VM in running state, directly power off the Harvester node VM. 

* After power on node VM, found all VMs are in `Stopping` state
![image](https://github.com/harvester/harvester/assets/29251855/6e9bb243-0ba7-4bc0-b6b8-86d1c48ddd76)

* If we click `Start`, it would prompt error message
```
Operation cannot be fulfilled on virtualmachine.kubevirt.io "vm-nginx-2": 
RerunOnFailure does not support starting VM from failed state
```

![image](https://github.com/harvester/harvester/assets/29251855/05e9a2f8-ff75-405a-89aa-78cd620f026f)

* Check the vm events
![image](https://github.com/harvester/harvester/assets/29251855/0af14dda-855a-4378-a9e7-10b87efae3c4)

* VMs state in K9s display `stopped` and `Not Ready` 
![image](https://github.com/harvester/harvester/assets/29251855/1b2a5b37-10d9-44df-8de6-8bebd7c1ee32)

**To Reproduce**
1. Create a vlan 1 network on management interface
2. Create two VMs on vlan 1 network with nginx service installed 
3. Set vm labels to each VM
  ![image](https://github.com/harvester/harvester/assets/29251855/81be8fc3-c576-4d6c-a054-dba9aed17488)

4. Create two IP pools one for default and another for harvester-public namespace
  ![image](https://github.com/harvester/harvester/assets/29251855/4dacb52b-f01b-4cfe-9342-bc32a5a61d18)

5. Create some load balancer set on the above IP pools and bind to the VMs
  ![image](https://github.com/harvester/harvester/assets/29251855/c0e128f3-bd75-4f95-afbe-0a7b1e9f2cc0)

6. Power off the Harvester node VM 
7. Power on the Harvester node VM again after 48 hours
8. Check the VM status

**Expected behavior**

* After power off and power on Harvester nodes, all VMs should back to it's original status correctly

**Support bundle**

[supportbundle_d57cd921-1fda-4f75-b018-666d5753cb71_2023-06-05T06-49-34Z.zip](https://github.com/harvester/harvester/files/11649516/supportbundle_d57cd921-1fda-4f75-b018-666d5753cb71_2023-06-05T06-49-34Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine

**Additional context**
* Found during test issue #1676
* We also can't delete the VM, it will keep in `Terminating` state
  ![image](https://github.com/harvester/harvester/assets/29251855/193701a2-790d-4dc5-964b-4c331a8bce74)

**Comment by w13915984028** [comment]
@ejweber @PhanLe1010

Is this a known issue, as kubelet can't unmount the PVC after cluster rebooting ?   thanks.
> Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/5c80253b-13fe-4def-8288-c7433c08a3df/volumeDevices/kubernetes.io~csi/pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc

From Harvester's view, those VM's were pendng deleting/stopping, the vmi `deletionTimestamp: "2023-06-05T06:11:33Z"` was set.


e.g. pvc `pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc`

LH volume
```
    kubernetesStatus:
      lastPVCRefAt: "null"
      lastPodRefAt: "2023-06-05T06:12:22Z"
      namespace: default
      pvName: pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc
      pvStatus: Bound
      pvcName: vm-nginx-2-disk-0-ttafd
```

vmi
```
    name: vm-nginx-2
    namespace: default
..
        volumes:
        - name: disk-0
          persistentVolumeClaim:
            claimName: vm-nginx-2-disk-0-ttafd
```

kubelet.log

```
harv120rc1/logs/kubelet.log:I0605 06:10:44.645857    2075 reconciler.go:211] "operationExecutor.UnmountVolume started for volume \"pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc\") pod \"5c80253b-13fe-4def-8288-c7433c08a3df\" (UID: \"5c80253b-13fe-4def-8288-c7433c08a3df\") "
harv120rc1/logs/kubelet.log:W0605 06:10:44.645970    2075 volume_path_handler.go:217] Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/5c80253b-13fe-4def-8288-c7433c08a3df/volumeDevices/kubernetes.io~csi/pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc
...

harv120rc1/logs/kubelet.log:I0605 06:48:57.554454    2075 reconciler.go:211] "operationExecutor.UnmountVolume started for volume \"pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc\") pod \"5c80253b-13fe-4def-8288-c7433c08a3df\" (UID: \"5c80253b-13fe-4def-8288-c7433c08a3df\") "
harv120rc1/logs/kubelet.log:W0605 06:48:57.554548    2075 volume_path_handler.go:217] Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/5c80253b-13fe-4def-8288-c7433c08a3df/volumeDevices/kubernetes.io~csi/pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc
```

**Comment by w13915984028** [comment]
Looks https://github.com/longhorn/longhorn/issues/6919 also mentioned the error message:

> Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/5c80253b-13fe-4def-8288-c7433c08a3df/volumeDevices/kubernetes.io~csi/pvc-40df082e-2ac6-4beb-97a2-9a58de527fcc

**Comment by w13915984028** [comment]
Similar to https://github.com/harvester/harvester/issues/4633

With
LH fix: from v1.4.x
Fix engine migration crash (backport #2275) https://github.com/longhorn/longhorn-manager/pull/2287

K8s fix from v1.26
Automated cherry pick of #122211: Fix device uncertain errors on reboot https://github.com/kubernetes/kubernetes/pull/122398

This issue could be validated in Harvester v1.3.0.

cc @bk201 @markhillgit @TachunLin

**Comment by w13915984028** [comment]
Per https://github.com/harvester/harvester/issues/4633#issuecomment-1915955357

>Currently, we are still waiting for RKE2 release. Both v1.26.13 and v1.27.10 are pre-released.
https://github.com/rancher/rke2/releases/tag/v1.26.13-rc2%2Brke2r1
https://github.com/rancher/rke2/releases/tag/v1.27.10-rc2%2Brke2r1

This issue can validated after RKE2 new version is bumped in Harvester v1.3.0.  in https://github.com/harvester/charts/pull/220

**Comment by irony** [comment]
Please if we could backport this issue to stable 1.2 version - this is a real problem in production for us again now.

**Comment by w13915984028** [comment]
To QA:

When validating this issue, please note those issues are caused by same root cause though they have slightly different phenomenon.
#4633 
#4033
#3539
#4789

**Comment by irishgordo** [comment]
@w13915984028 I've not had a chance to look at this yet, but was curious, do you believe that issue:

https://github.com/harvester/harvester/issues/5109

Is also caused by the same root cause?
Even though different phenomenon as well?

**Comment by w13915984028** [comment]
@irishgordo I will take a look of #5109 , if they are belonging to the same root cause, then we are lucky :)

**Comment by w13915984028** [comment]
@irishgordo FYI:
In the supporte-bundle file attached in #4033, there are 129 times of such keywords
  `failed to unmap device from map path. mapPath is empty` 
  mentioned in https://github.com/longhorn/longhorn/issues/6919:
```
grep "failed to unmap device from map path. mapPath is empty" kubelet.log  | wc
    129    6579  102556
```

But the keyword was not existing in the support bundle file of #5109, it should be another issue.

**Comment by irishgordo** [comment]
@w13915984028 - thanks for that mention :smile:  - I've updated 5109 additionally with RC3 and shared out further info too.

**Comment by TachunLin** [comment]
Verifying on `v1.3-50a00ad1-head` (24/02/21).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ VM status after power off then power on node machine after 12 hours $~~$</summary>

* All vm display `running` state after power on node machine after 12 hours
![image](https://github.com/harvester/harvester/assets/29251855/2965132f-0b11-4c19-82a1-88cc0119c277)


 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ VM status after restart node machine several times $~~$</summary>

* After restart node machine, all vm stuck in Starting state

![image](https://github.com/harvester/harvester/assets/29251855/caf200d0-c5a7-4c2f-9958-6b23334adf67)
![image](https://github.com/harvester/harvester/assets/29251855/a1446457-464e-4398-8f2f-4c756a956057)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Ensure bumped Rancher to 2.8.2 and RKE2 to 1.27.10  $~~$</summary>

refer to #5041 
```
harv13-240221:~ # kubectl get settings.management.cattle.io server-version
NAME             VALUE
server-version   v2.8.2
harv13-240221:~ # kubectl get nodes
NAME            STATUS   ROLES                       AGE   VERSION
harv13-240221   Ready    control-plane,etcd,master   78m   v1.27.10+rke2r1
```

 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ Check issue #4633 VM got IO error after host restart  $~~$</summary>

* After restart node machine, all vm stuck in Starting state

![image](https://github.com/harvester/harvester/assets/29251855/caf200d0-c5a7-4c2f-9958-6b23334adf67)
![image](https://github.com/harvester/harvester/assets/29251855/a1446457-464e-4398-8f2f-4c756a956057)


```
harv13-240221:~ # kubectl get vmi -w
NAME        AGE   PHASE        IP    NODENAME   READY
vm1-nginx   73m   Scheduling                    False
vm2-nginx   73m   Scheduling                    False
```


 </details>


<details><summary>$\color{red}{\textsf{Failed}}$ Check issue #5109 Single Node Cluster Fails To Have VMs Come Back Post Restart w/ Storage Network Configured $~~$</summary>

After configure the storage class and create a virtual machine.

* The virtual machine keep in `Starting` state
![image](https://github.com/harvester/harvester/assets/29251855/44384d2c-abef-43dc-86e9-692b3f4cbd5d)

* The events indicate failed to attach node
![image](https://github.com/harvester/harvester/assets/29251855/0b688e29-9fbe-4544-a8e3-d389c78f2417)

 </details>


### Test Information
* Test Environment: Single node harvester on local kvm machine 
* Harvester version: `v1.3-50a00ad1-head` (24/02/21)

### Verify Steps
<details><summary> Cold restart node machine </summary>

https://github.com/harvester/harvester/issues/4033#issue-1741095323

</details>

<details><summary> Check issue #4633  </summary>

https://github.com/harvester/harvester/issues/4633#issue-1951158726

</details>

<details><summary> Check issue #5109 </summary>

https://github.com/harvester/harvester/issues/5109#issue-2119476374

</details>

**Comment by TachunLin** [comment]
When I restart the node machine, after node restart:

* All vm stuck in `Starting` state

![image](https://github.com/harvester/harvester/assets/29251855/caf200d0-c5a7-4c2f-9958-6b23334adf67)
![image](https://github.com/harvester/harvester/assets/29251855/a1446457-464e-4398-8f2f-4c756a956057)

* Check the vmi state kept in Scheduling 
```
harv13-240221:~ # kubectl get vmi -w
NAME        AGE   PHASE        IP    NODENAME   READY
vm1-nginx   73m   Scheduling                    False
vm2-nginx   73m   Scheduling                    False
```

#### Support bundle
[supportbundle_a14146bc-4915-498b-81b4-bdbf20c4c0ae_2024-02-26T05-10-25Z.zip](https://github.com/harvester/harvester/files/14399952/supportbundle_a14146bc-4915-498b-81b4-bdbf20c4c0ae_2024-02-26T05-10-25Z.zip)

The behavior looks like similar to #4633

**Comment by TachunLin** [comment]
While checking issue #5109, follow the [steps](https://github.com/harvester/harvester/issues/5109#issue-2119476374) to reproduce issue. 

After configure the storage class and create a virtual machine.

* The virtual machine keep in `Starting` state
![image](https://github.com/harvester/harvester/assets/29251855/44384d2c-abef-43dc-86e9-692b3f4cbd5d)

* The events indicate failed to attach node
![image](https://github.com/harvester/harvester/assets/29251855/0b688e29-9fbe-4544-a8e3-d389c78f2417)

#### support bundle
[supportbundle_53208c16-ff37-4aba-8411-55b425b775bb_2024-02-26T08-39-43Z.zip](https://github.com/harvester/harvester/files/14401954/supportbundle_53208c16-ff37-4aba-8411-55b425b775bb_2024-02-26T08-39-43Z.zip)

**Comment by TachunLin** [comment]
While we encounter issue while restarting node would cause all VMs in `Starting` state in [test result](https://github.com/harvester/harvester/issues/4033#issuecomment-1963336920) for issue #4633 

And encounter issue can't create VM while configured storage network with excluded ip in [test result](https://github.com/harvester/harvester/issues/4033#issuecomment-1963603972) for issue #5109 

Thus I would suggest to move this issue to implement first for further investigation.

**Comment by w13915984028** [comment]
@TachunLin Thanks for your update.

In #5109 , at least 2 addtional bugs are found, and they all cause the similar phenomenon: 
`VM stucks at starting`.

Let's keep working on them.

**Comment by TachunLin** [comment]
Trying to validate this issue on `v1.3.0-rc3`, 
This time when I power off node machine, wait around 1 hour to power on machine.

Like the previous test result in https://github.com/harvester/harvester/issues/4033#issuecomment-1963336920
All the VMs are stuck in `Starting` state
![image](https://github.com/harvester/harvester/assets/29251855/ca60645a-2382-4790-9552-e9e79726025a)

Check the events of vm, all indicate in the steps
```
Pod virt-launcher-vm1-nginx-ltmzp
Container image "registry.suse.com/suse/sles/15.5/virt-launcher:1.1.0-150500.8.6.1" already present on machine
```
![image](https://github.com/harvester/harvester/assets/29251855/846a85a6-7c7c-4cda-8c97-2871e8ed55b2)



https://github.com/harvester/harvester/assets/29251855/0fabdfcc-c2c9-422c-9f49-f085d5fe22bf


#### Reproduce steps
1. Create a vlan 1 network on management interface
2. Create two VMs on vlan1 and mgmt network with nginx service installed
  ```
  #cloud-config
  package_update: true
  packages:
    - qemu-guest-agent
    - nginx
  runcmd:
    - - systemctl
      - enable
      - --now
      - qemu-guest-agent.service
      - systemctl start nginx
      - systemctl enable nginx
  password: 123456
  chpasswd: { expire: false }
  ssh_pwauth: True
  ``` 
3. Set vm labels to each VM
4. Create two IP pools one for default and another for harvester-public namespace
5. Create some load balancer set on the above IP pools and bind to the
6. Power off the Harvester node VM 
7. Power on the Harvester node VM again after 1 hour
8. Check the VM status and events

#### Support bundle
[supportbundle_e9d19d9f-3065-416e-b76d-1dcd5bf5d828_2024-03-01T10-31-24Z.zip](https://github.com/harvester/harvester/files/14459895/supportbundle_e9d19d9f-3065-416e-b76d-1dcd5bf5d828_2024-03-01T10-31-24Z.zip)


@w13915984028,
Do you think we need to create another ticket to track the symptom encountered on v1.3.0-rc3 or just track here is enough. 
Since the reproduce steps is the same while the error message looks different, it looks like once I restart the node machine would encounter the VM stuck in starting issue.

**Comment by w13915984028** [comment]
@TachunLin

Please add another issue to track, thanks.

**Comment by w13915984028** [comment]
Issue #5272 is the output when verifing #4033, and #5272 is caused by the same root cause from #5109.

Those issues caused similar user experience: the VM failed to restart after cluster/Node rebooting, though their root causes were different.

@bk201 @TachunLin:
Could we close #4033, #5272, and use #5109 to track ? thanks.

**Comment by TachunLin** [comment]
As per discussed, close this issue and we will track in [#5109](https://github.com/harvester/harvester/issues/5109) since they all caused by the same root cause.
