### ISSUE TITLE
[BUG] Installation ends up in grub rescue mode

### ISSUE THREAD

**Issue by abdullahgill** [harvester/harvester#404]
**Describe the bug**

UEFI BOOT Issue i am facing following error on boot
`grub rescue>`

**To Reproduce**
UEFI BOOT Issue i am facing following error on boot
`grub rescue>`

**Environment:**
 - Harvester ISO version:  v0.1.0
 - Installation Mode: ISO
 - Underlying Infrastructure:  Baremetal with Dell PowerEdge R720):

**Comment by gitlawr** [comment]
The `grub rescue` may indicate corruption in configurations, e.g. missing the `/boot/grub` directory.
1. Can you check the integrity of the ISO image?
2. Can you check the files in grub rescue console:
```
# ls partitions, output may vary in different environments
grub rescue> ls
(proc) (hd0) (hd0,msdos1)

# check if /boot/grub and /k3os are present in any of the partition
grub rescue> ls (hd0,msdos1)
lost+found/ boot/ k3os/ sbin/ proc/ dev/ 
```
3. Are you able to boot an Ubuntu server image using the same hardware?

**Comment by rrrai** [comment]
I had a similar issue with install on bare metal node using USB drive. On boot the disk would go into rescue mode. I was using rufus-3.13 to create usb disk using defaults. Creating the disk with gpt partion and with dd write resulted in a viable usb drive that worked.
<img width="392" alt="rufus-3 13-Harvester" src="https://user-images.githubusercontent.com/50937667/111266603-c5b09600-85f8-11eb-947f-64cee8031dba.png">

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/releases/tag/v0.3.0, if u have encountered this issue in the latest release please let us know, thanks.
