### ISSUE TITLE
[BUG]  Visual Bug during the Harvester upgrade

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4040]
**Describe the bug**

During the ongoing Harvester upgrade, when someone logs in to the Rancher GUI and selects the Harvester environment (Hamburger Menu -> Virtualization Management -> Harvester cluster), the green circle does not show up on the top right corner. However, when the page is reloaded, it appears.

**To Reproduce**
1. install `v.1.1.1` harvester ,  (Other versions are available, as long as you can choose any version to upgrade)
2. Import this cluster into Rancher
3. Go to the `Virtualization Management` ->` Harvester cluster`
4. The page header does not show the upgrade icon
![image.png](https://images.zenhubusercontent.com/60345555ec1db310c78aa2b8/fd79b84a-651f-4f09-9aa0-25b13bae2d37)

**Expected behavior**

You should see the upgrade icon at this point

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verify **failed** on  `master-d3dc81ca-head` (24/01/04) with Rancher `v2.7.9` 

The original upgrade icon disappear issue did not happen, while we encounter a new UI display issue during the test. 
Thus we suggest move to the `implement` for further investigation. 

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ First time enter Harvester from Rancher virtualization management, the upgrade icon can display correctly $~~$</summary>

* Please refer to the following video 

https://github.com/harvester/harvester/assets/29251855/c1dab6f0-fc5f-4df2-b359-4ae4adb20c77

 </details>

<details><summary>$\color{red}{\textsf{New issue}}$ When we reload the page in Rancher virtualization management, the upgrade icon disappear  $~~$</summary>

Found new issue after reloaded the Harvester page in Rancher virtualization management

https://github.com/harvester/harvester/assets/29251855/fb3a39cb-71ac-43fb-b76b-cf4fc1d5dd31

Compared with Harvester, the issue only happened on Rancher side 

https://github.com/harvester/harvester/assets/29251855/805fc638-eea3-4ec1-8675-0b0eeb08c53a

 </details>

### Test Information
* Test Environment: 3 nodes Harvester on remote kvm machines
* Harvester version: `master-d3dc81ca-head` (24/01/04) 
* Rancher version: v2.7.9

### Verify Steps
<details><summary>Test steps </summary>

  1. Prepare the 3 nodes Harvester cluster
  2. Import Harvester with Rancher v2.7.9
  3. Prepare the offline Harvester upgrade manifest
  4. Trigger Harvester upgrade 
  5. Access Harvester from Rancher `Virtualization Management` -> `Harvester cluster`
  6. Check the upgrade icon on Host page

</details>

**Comment by torchiaf** [comment]
@TachunLin I tested it on my environment, Rancher UI v2.8.0 + harvester master and everything works fine. I think your are using an old Rancher manager UI version. Could you give it another try with the latest Rancher UI ?

**Comment by TachunLin** [comment]
Tested the issue when reload the page in Rancher virtualization management, the upgrade icon would disappear 
On Rancher `v2.8.1` and `v2.7.9` with Harvester `v1.3.0-rc1`, we can reproduce this issue


https://github.com/harvester/harvester/assets/29251855/8f7eafaa-6df3-43df-9084-09d17cb7430b

The reproduce steps would be:

1. Prepare the 3 nodes Harvester cluster
2. Import Harvester with Rancher v2.7.9
3. Prepare the offline Harvester upgrade manifest
4. Trigger Harvester upgrade
5. Access Harvester from Rancher Virtualization Management -> Harvester cluster
6. Check the upgrade icon on Host page
7. Use ctrl+r to reload the current page
8. Check the upgrade icon

**Comment by torchiaf** [comment]
@TachunLin @bk201 I managed to replicate the issue in Rancher 2.8 and 2.9. I've the PRs up, just need to confirm the release milestones.

**Comment by torchiaf** [comment]
Merged in Rancher 2.9.3 & 2.8.9.

**Comment by khushboo-rancher** [comment]
@TachunLin Let's test this during upgrade testing part of the release test.

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher `v2.8.9` and `v2.9.3` with Harvester v1.3.2 upgrade to `v1.4.0-rc4`. 
Close this issue.
 
### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Harvester upgrade dashboard icon exists after refresh page on Rancher v2.8.9 
 $~~$</summary>


https://github.com/user-attachments/assets/324e6f61-86d0-47af-adef-72745d412bba




 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Harvester upgrade icon exists after refresh page on Rancher v2.9.3
 $~~$</summary>


https://github.com/user-attachments/assets/b615e874-c09f-48fe-8c6c-c146ce424b4f


 </details>

### Test Information
* Test Environment: Single node harvester on kvm machine
* Harvester version: v1.3.2 upgrade to v1.4.0-rc4
* Rancher version: v2.8.9 and v2.9.3

### Verify Steps
<details><summary>Check upgrade button after refreshing page </summary>

1. Prepare single Harvester cluster
2. Import Harvester with Rancher
3. Prepare the offline Harvester upgrade manifest
4. Trigger Harvester upgrade
5. Access Harvester from Rancher Virtualization Management -> Harvester cluster
6. Check the upgrade icon on Host page
7. Use ctrl+r to reload the current page
8. Check the upgrade icon

</details>
