### ISSUE TITLE
[ENHANCEMENT] Improve Harvester & Rancher integration test

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#4048]
**Is your enhancement related to a problem? Please describe.**
Currently, we have Harvester Rancher integration test based on dockerized Rancher and covers importing Harvester and creating rke1 and rke2 guest cluster. We don't have an option to provide Rancher, rke1 & rke2 versions when running through Jenkins.

**Describe the solution you'd like**

- Jenkins should have the option to take Rancher, rke1 & rke2 versions along with Harvester. 
- Add test cases to cover csi-driver & cloud provider deployment and their checks
- Good to have upgrade included in the integration test.
    - Deploy Rancher & Harvester, do the integration test
    - Upgrade to set up to desired version
    - Run the post upgrade checks

**Sub Tickets**
- Jenkins Job: https://github.com/harvester/tests/issues/794
- RKE2 TCs: https://github.com/harvester/tests/issues/948
- RKE TCs: https://github.com/harvester/tests/issues/973
- K3s TCs: https://github.com/harvester/tests/issues/974

**Comment by albinsun** [comment]
Close and trace by https://confluence.suse.com/display/HARV/Automation+Tasks
