### ISSUE TITLE
[Doc] update the disk space force check before upgrade, and how to adjust the min disk space

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4052]
**Is your doc request related to a problem? Please describe or add related issue ID.**

After following enhancement, the Harvester doc needs also be updated to reflect the latest requirements, and how to adjust it.

https://github.com/harvester/harvester/issues/2935
https://github.com/harvester/harvester/pull/3700

**Describe the solution you'd like**

In some clusters, the free disk space may be less than required, user should have chance to try upgrade.

**Comment by guangbochen** [comment]
Close since the doc PR is merged, and more details can be checked via https://docs.harvesterhci.io/dev/upgrade/automatic/
