### ISSUE TITLE
[Doc] add upgradelog to Harvester Doc

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4056]
**Is your doc request related to a problem? Please describe or add related issue ID.**

The `upgradelog` is released, the document needs also be updated.

**Describe the solution you'd like**

Update the document.

**Comment by starbops** [comment]
The related sections are added to
- https://docs.harvesterhci.io/dev/upgrade/troubleshooting#download-upgrade-logs
- https://docs.harvesterhci.io/v1.1/upgrade/troubleshooting#download-upgrade-logs
