### ISSUE TITLE
[Question] ISO file gets "Context Canceled" Error

### ISSUE THREAD

**Issue by Chrome772** [harvester/harvester#4057]
Everytime I upload an iso file it gets to 99% and then says "Context Canceled" can anyone help?

![error](https://github.com/harvester/harvester/assets/136072811/7a015606-b2e3-4820-8697-a100b351ce5c)

**Comment by Martin-Weiss** [comment]
Just guessing - looks a bit like you might be hitting a timeout... 
Can you try to host the iso on an http server and specify that source when creating the image?

**Comment by w13915984028** [comment]
@Chrome772 

root cause and workaround are in  https://github.com/harvester/harvester/issues/3450
