### ISSUE TITLE
[Question] Installation from ISO Stuck at `ctr: failed to dial "/run/k3s/containerd/containerd.sock"` - connection refused

### ISSUE THREAD

**Issue by gsuess** [harvester/harvester#4058]
When attempting to install harvester v1.1.2 amd64, during the "Installing harvester"  step I get this error repeatedly at which the installation progress freezes: 

```
ctr: failed to dial "/run/k3s/containerd/containerd.sock": connection error: desc =
"transport: error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: connection refused"
```

![image](https://github.com/harvester/harvester/assets/1558575/0367dec0-7221-4c7c-bc15-e5828728b561)

I think this is the relevant extract from the logs:

```
time="2023-06-08T22:57:30Z" level=info msg="[stdout]: Checking 38 images in /tmp/images-lists/harvester-images-v1.1.2.txt..."
time="2023-06-08T23:00:03Z" level=info msg="[stderr]: ctr: failed to list images: error reading from server: read unix @->/run/k3s/containerd/containerd.sock: read: connection reset by peer: unavailable"
time="2023-06-08T23:00:05Z" level=info msg="[stderr]: ctr: failed to dial \"/run/k3s/containerd/containerd.sock\": connection error: desc = \"transport: error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""
time="2023-06-08T23:00:07Z" level=info msg="[stderr]: ctr: failed to dial \"/run/k3s/containerd/containerd.sock\": connection error: desc = \"transport: error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""
time="2023-06-08T23:00:09Z" level=info msg="[stderr]: ctr: failed to dial \"/run/k3s/containerd/containerd.sock\": connection error: desc = \"transport: error while dialing: dial unix /run/k3s/containerd/containerd.sock: connect: connection refused\""
```

This is pretty much as standard bare-metal on Dell PowerEdge R550. What would be the next steps to troubleshoot this?

**Comment by gsuess** [comment]
After rebooting, the harvester does boot fine, however. Not sure there are any installation steps that we are missing out on now.

**Comment by w13915984028** [comment]
A known issue, when the Harvester NODE and the ISO server have poor network performance.
https://github.com/harvester/harvester/issues/2651

You may try  https://github.com/harvester/harvester/releases/tag/v1.2.0-rc1, it resolved the issue. thanks.

**Comment by gsuess** [comment]
Thanks for confirming. I have originally thought it was an intermittent issue, but it happened three times in a row, on a 1gbps connection to the iso server, but mounted via IDRAC.

I wonder if my installation is health now? As in are there any software packages missing?

We want to go production soon, so I will consider v1.2.0 once its a officially released.

**Comment by w13915984028** [comment]
> I wonder if my installation is health now? As in are there any software packages missing?

To be honest, it is hard to sure this, the installation itself it not fully finished.

After rebooting, if you run into https://github.com/harvester/harvester/issues/3844, then may try the workaround https://github.com/harvester/harvester/issues/3844#issuecomment-1545062052

**Comment by w13915984028** [comment]
@gsuess Any updates of your cluster ? thanks.

**Comment by gsuess** [comment]
> @gsuess Any updates of your cluster ? thanks.

So far I could not detect anything out of the ordinary. Thanks for your help.

**Comment by johnwc** [comment]
@w13915984028 Had this same thing happen today when adding a node to a v1.2.2 cluster via pxe boot. So, I don't think it is fully fixed.
