### ISSUE TITLE
[Question] no vm on on 1/3 hosts

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4064]
Do I need to have more hosts to balance it? I have 20 vms running on a 3 node cluster. all of those servers have the same hardware. but smh vms always go to harvster 2 and 3, never to the first host. I can move them manually there but they will move back after some time.

**Comment by bk201** [comment]
@ne0YT Did you spawn all VMs together? wondering if the KB can explain this: https://harvesterhci.io/kb/vm-scheduling

**Comment by ne0YT** [comment]
no. I started them over multiple months. often creating new and deleting old ones.

**Comment by w13915984028** [comment]
@ne0YT 

could you add support-bundle file ? https://docs.harvesterhci.io/v1.1/troubleshooting/harvester/#generate-a-support-bundle

did you compare the details of those NODEs, are there anything different in the spec/status ?

`kubectl get nodes -A -oyaml`

**Comment by ne0YT** [comment]
somehow it's not happening anymore, gonna close it.
