### ISSUE TITLE
[BUG] Rancher Monitoring AddOn Fails Silently - Doesn't Bubble Up Information to Addon Index

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4067]
**Describe the bug**
When the Rancher Monitoring AddOn fails it won't ever bubble up the error to the UI in the Addons index, seems to just say Deployment Successful or Active

**To Reproduce**
1. Go to addons -> enable monitoring
1. Prometheus tab -> Retention -> input "-99d" for instance
1. On the index of Addons you will see that Rancher Monitoring just stays at "Enabled"
1. Open up integrated/embedded rancher from Support -> Embedded Rancher -> All Namespaces -> Installed Apps, you will see Failure & Un-install loop

**Expected behavior**
Errors to be bubbled up from Embedded Rancher if the Addon Fails

**Environment**
 - Harvester ISO Version: master-e3c0f41c-head
 - Underlying Infrastructure: qemu/kvm

**Additional context**
- Related: https://github.com/harvester/harvester/issues/4065

https://github.com/harvester/harvester/assets/5370752/001156d8-3876-4c94-b517-e8035936d725

**Comment by w13915984028** [comment]
@ibrokethecloud @DaiYuzeng cc @WuJun2016 

any insights? thanks.

**Comment by w13915984028** [comment]
BTW:  @ibrokethecloud Do we have stauts like `DeployFailed` after certain time ?

`
On the index of Addons you will see that Rancher Monitoring just stays at "Enabled"
`

**Comment by DaiYuzeng** [comment]
It seems like we don't have the `failed` status when addon deployed failed, but I think there is error state in related pod.
@ibrokethecloud @w13915984028 
![image (1)](https://github.com/harvester/harvester/assets/15041915/b85c2d2c-98f8-4945-bece-4e6ad094f95d)

**Comment by w13915984028** [comment]
will be solved in https://github.com/harvester/harvester/pull/4127

**Comment by irishgordo** [comment]
Thanks for the fix @DaiYuzeng  - this looks good :+1: :smile: 

Tested on Version: v1.2-37aeb5ff-head 

![Screenshot from 2023-07-19 14-35-02](https://github.com/harvester/harvester/assets/5370752/a147077b-0b8c-4b0e-a7e6-b632388954ff)

Opened up:
https://github.com/harvester/harvester/issues/4279
As a small issue discovered with form & default values.

I'll go ahead and close this out :smile:
