### ISSUE TITLE
[BUG] Grafana do not show data for Availability (API-Server) for the last 30 days

### ISSUE THREAD

**Issue by thorebahr** [harvester/harvester#4069]
**Describe the bug**
Grafana do not show data for Availability (API-Server) for the last 30 days

**To Reproduce**
1. change the retention time to 30 days
2. wait 30 days to grab all the metrics
3. open the grafana dashboard and select "General / Kubernetes / API server" dashboard
4. 
**Expected behavior**
all provided metrics must contain valid data. 

**Support bundle**

**Environment**
 - Harvester ISO version: v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal, 3 nodes (64 Core, 256 GB RAM, 960GB SSD)

**Additional context**

**Comment by w13915984028** [comment]
Test from my local v1.3.0 cluster, it seems grafana is showing related data.

![image](https://github.com/harvester/harvester/assets/31133476/0e572855-1fb5-4cc2-93d8-cf220ee042ce)

![image](https://github.com/harvester/harvester/assets/31133476/bec13fe9-4695-45c8-b29b-b227cfd41121)

**Comment by thorebahr** [comment]
in the meantime, we reinstalled our cluster with v 1.3.0 and I can confirm - I see also the expected 100% ... seems to be fixed
