### ISSUE TITLE
[BUG] A pause button is displaying on the menubar though the VM is already paused

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#407]
**Steps to reproduce:**
1. Create two VMs A & B
2. Pause VM A, then Pause VM B
3. Open VM A's menubar again

**Result:**
The pause button is displaying instead of Unpause
![image](https://user-images.githubusercontent.com/57614736/103521633-0fbc2380-4eb4-11eb-83db-4207146c7656.png)

**Comment by DaiYuzeng** [comment]
Reproduced.

And i realized that the data received from WS was unexpected.

The actions of Virtual Machine didn't have `unpause`

![image](https://user-images.githubusercontent.com/15041915/103605786-c6211680-4f4f-11eb-8079-25061df8cd86.png)

**Comment by WuJun2016** [comment]
WS push data is different from API data

**Comment by guangbochen** [comment]
can we re-validate this issue on the latest version, thanks?

**Comment by DoNotSayYes** [comment]
Unable to reproduce on master-head
![image](https://user-images.githubusercontent.com/57614736/110307613-15f88880-803a-11eb-818c-f7984a8d7859.png)
