### ISSUE TITLE
[ENHANCEMENT] Try best to keep grafana PV when upgrading from v112 to v120

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4071]
**Is your enhancement related to a problem? Please describe.**

The `rancher-monitoring managedchart` is converted to `addon` in  https://github.com/harvester/harvester/issues/2992, and the grafana PV is deleted and re-created. When user have customized data, which may be a loss.

PR: https://github.com/harvester/harvester/pull/3380#issuecomment-1588746799

> This should not be a blocker, but may be we should still look at additional logic in the upgrade path to patch the grafana pv's volume retention policy: https://kubernetes.io/docs/tasks/administer-cluster/change-pv-reclaim-policy/

> This existing pv can then be re-purposed for the upgrade path, but will mean some additional changes to be generated for the values of the addon.

> Or we can document how to export/import custom dashboards from grafana, which user may have to perform post the upgrade.

**Describe the solution you'd like**

First, add this to document.

Second, try to keep the PV.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
Plan:
(1) In upgrade, patch the ClaimPolicy of Grafana PV, and deleting `rancher-monitoring` managedchart, remove the ClaimRef to PVC.  Create new addon, it will reuse the PV.

(2) In v1.2.0, via https://github.com/harvester/harvester/issues/4118 (on top of #4108), repeat the actions in (1) when addon is disabled, enabled. Thus the grafana PV will remain there even when `rancher-monitoring` addon is disabled.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.1.2** -> **v1.2.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to console, record current PVs and PVCs by executing following commands:
    - `kubectl get pv -A | awk '{print $1" "$6}' > pvs`
    - `kubectl get pvc -A | awk '{print $2" "$4}' > pvcs`
3. Perform upgrade[^1]
4. Upgrade should completed successfully
5. Login to console, compare upgrade PVs and PVCs by executing following commands:
    - `kubectl get pv -A | awk '{print $1" "$6}' | diff pvs -`, output should be empty
    - `kubectl get pvc -A | awk '{print $2" "$4}' | diff pvcs -`, output should be empty


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
