### ISSUE TITLE
How to install packages[Question]

### ISSUE THREAD

**Issue by Delta-VII** [harvester/harvester#4080]
Noob question here: How do I install packages?

**Comment by noahgildersleeve** [comment]
Harvester uses an immutable operating system layer and all of the other functionality is mostly taken care of by VMs. You can create VMs then install packages there. So the short answer is that mostly you can't install packages.

If you really need something on your host then it's outlined [here](https://docs.harvesterhci.io/v1.1/troubleshooting/os/#how-can-i-install-packages-why-are-some-paths-read-only).

For workload tasks you might check [here](https://docs.harvesterhci.io/v1.1/rancher/rancher-integration) for some more info. That outlines how to create a Rancher cluster then import Harvester. You can then create downstream k8s clusters in Harvester. I'm not sure if that's what you're asking about though.
