### ISSUE TITLE
Hardware make and model to be considered for harvestor in production

### ISSUE THREAD

**Issue by sudheermygapula** [harvester/harvester#4081]
Hello Team ,

i have checked the specs but would like to know if you could provide concreate details about hardware ( Make and model ) that can be recommended or tested by harvestor team would be great.

Thanks in advance.

**Comment by xeruf** [comment]
I fail to see what they could answer. This greatly depends on your needs, from a small cluster for SME to big enterprise servers everything is possible.

**Comment by sudheermygapula** [comment]
we would like to evalute the features of the harvestor and also use for development purpose , so just to make sure we buy right hardware ( for example 64 GB ram and 16 core machine ) seeking for information if such kind of qualified hardware details availble from team .

**Comment by w13915984028** [comment]
Sorry, it seems we did not have a guide document or certificated hardware list for such now.

The Harvester document describes a basic requirement to hardware: https://docs.harvesterhci.io/v1.1/install/requirements, with such, the Harvester cluster itself could be installed and set.  

Then it is related to your `workload` plan in Harvester cluster. Run VM or other kind of workload, and what is the expected specifications.

Suppose your plan is to run 100 VMs in 5 NODEs, each VM needs 4core 16G memeory 100G volume, a sum can be  calculated and devided to NODEs.

The Harvester  basic requriement + workload requirement will be a guide to target hardware.

BTW, Harvester is on top of k8s, you can add more NODEs anytime.

**Comment by sudheermygapula** [comment]
Thanks it would be also nice to publish information some thing similar to https://ranchermanager.docs.rancher.com/pages-for-subheaders/installation-requirements , where it will be clear from system spec to how many VM/Cluster could be provisioned.

**Comment by xeruf** [comment]
For experimenting, we bought some old HP Servers, they can be acquired cheaply and should be good enough.
