### ISSUE TITLE
[BUG] Cannot pull docker image rancher/harvester-cluster-repo:v1.1.2

### ISSUE THREAD

**Issue by drivard** [harvester/harvester#4082]
**Describe the bug**

I am trying to reinstall my cluster with harvester v1.1.2 

During the bootstrap step of the first node after the `Create a new cluster` step. I get the error on the first node `Back-off pulling image "rancher/harvester-cluster-repo:v1.1.2"`.

Message on the first node is `Status: Setting up Harvester`

When I ssh on the node and I describe the failing pod and I get

`kubectl describe pod harvester-cluster-repo-67ddddf8d7-pw4s7 -n cattle-system`

I get the following error

```
Events:
  Type     Reason          Age                 From               Message
  ----     ------          ----                ----               -------
  Normal   Scheduled       35m                 default-scheduler  Successfully assigned cattle-system/harvester-cluster-repo-67ddddf8d7-pw4s7 to node1
  Normal   AddedInterface  35m                 multus             Add eth0 [10.52.0.28/32] from k8s-pod-network
  Normal   Pulling         33m (x4 over 35m)   kubelet            Pulling image "rancher/harvester-cluster-repo:v1.1.2"
  Warning  Failed          33m (x4 over 35m)   kubelet            Failed to pull image "rancher/harvester-cluster-repo:v1.1.2": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/rancher/harvester-cluster-repo:v1.1.2": failed to resolve reference "docker.io/rancher/harvester-cluster-repo:v1.1.2": docker.io/rancher/harvester-cluster-repo:v1.1.2: not found
  Warning  Failed          33m (x4 over 35m)   kubelet            Error: ErrImagePull
  Warning  Failed          33m (x6 over 35m)   kubelet            Error: ImagePullBackOff
  Normal   BackOff         1s (x151 over 35m)  kubelet            Back-off pulling image "rancher/harvester-cluster-repo:v1.1.2"
```

If I tried to pull the image locally and I got the following error

```
docker pull rancher/harvester-cluster-repo:v1.1.2
Error response from daemon: manifest for rancher/harvester-cluster-repo:v1.1.2 not found: manifest unknown: manifest unknown
```

**To Reproduce**

1. Boot from harvester-v1.1.2-amd64.iso on a node and try to create a new cluster
2.  Complete the installer steps
3. reboot
4. wait for the harvester bootstrap to fail

**Expected behavior**

docker pull would go through

**Support bundle**

the ui is not yet available

**Environment**
 - Harvester ISO version: v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal with AMD 5600X

**Additional context**

**Comment by w13915984028** [comment]
A known issue, when the Harvester NODE and the ISO server have poor network performance.
https://github.com/harvester/harvester/issues/2651

You may try https://github.com/harvester/harvester/releases/tag/v1.2.0-rc1, it resolved the issue. thanks.

**Comment by drivard** [comment]
I have relaunched the iso installer and this time it passed. I will wait until the stable release.
The iso was mounted directly through usb on the hardware and bandwidth should not have been a matter with a 400/50Mbps.
