### ISSUE TITLE
[BUG] RKE2 Custom Cluster Cloud Provider RKE2 Embedded After Delete of Node used for RKE2 Snapshot Restore - causes `init: node not found` 

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4083]
**Describe the bug**
Following `Scenario 2` from [here](https://github.com/rancher/rancher/issues/41080#issuecomment-1563269826).

Noting:
> There seems to be some interesting things that show up.

> If VMs ( those that are for the RKE2 nodes in Harvester ) are powered off (through Harvester UI), it seems that the Custom RKE2 Cluster hangs in an "Update" state.  If in this "Update" state, the user were to try to register a new "all roles (worker, control-plane, etcd)" node, it will hang in perpetually and never become registered.  A work-around discovered: was to delete the original "control-plane" & "etcd" nodes from the Cluster Management UI in Rancher - and re-run the registration on the new third (all-roles: etcd, control-plane, worker) node - then eventually the cluster would be at an "Active" state.

> W/ Work-Around from above mentioned, was able to notice that a restore was able to successfully be preformed to the third node.  But this cluster isn't a Harvester Cloud Provider based RKE2 Custom Cluster.

> The Third Node, that gets added, will need to have the snapshot restored shortly after it's registered, or else it will just hang and the cluster will never become ready but I believe this is expected as we encounter the:

> [INFO ] rkecontrolplane was already initialized but no etcd machines exist that have plans, indicating the etcd plane has been entirely replaced. Restoration from etcd snapshot is required.

> But then if you delete the third node that was added, after adding back a new worker & control-plane&etcd node,
There is an error of:
"init node not found"
And the cluster state ends up staying in "Provisioning".
So the "All Roles" Node, upon deletion, is causing the RKE2 Custom Cluster to become unusable.

Also noting:
For workload, NGINX was just used as Deployment, for testing.

**Env to Utilize**
1. Minio with https certs to allow for S3 Backups
1. Rancher v2.7.5-rc4
1. Helm install based Rancher w/ K3s: `curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION="v1.25.9+k3s1" sh -s - server --cluster-init` 

**To Reproduce**
1. Follow along in Scenario 2, with workaround steps.
1. After Step 10, the deletion of the `all-roles` node, will cause the error

**Expected behavior**
There to not be an error present when removing the node that was used for temporary RKE2 Snapshot Restore.

**Environment**
 - Harvester ISO version:  Version: v1.2-0d1cf827-head 
 - Rancher Version: v2.7.5-rc4
 - Underlying Infrastructur: Bare Metal, for both Rancher & Harvester
 - Helm install based Rancher w/ K3s: `curl -sfL https://get.k3s.io/ | INSTALL_K3S_VERSION="v1.25.9+k3s1" sh -s - server --cluster-init`
 - `helm install rancher rancher-latest/rancher --devel --version v2.7.5-rc4 ......`

**Additional context**
![Screenshot from 2023-06-13 17-52-10](https://github.com/harvester/harvester/assets/5370752/d03fbe21-a844-47f1-bd01-b826e9100341)

**Comment by irishgordo** [comment]
The workaround doesn't always work but this behavior seems similar across multiple Rancher versions v2.7.2-v2.7.4.
It seems interesting that if both nodes are down and still a part of the cluster that a third node can't always be added - it will talk to Rancher and generate a cattle-id, the VM in Harvester that is - but it always times out and fails to register.

**Comment by nickvth** [comment]
Same issue here with rke2 via CAPI vmware: After Delete of Node used for RKE2 Snapshot Restore - causes init: node not found

**Comment by irishgordo** [comment]
@nickvth I was curious -was this just with RKE2 via CAPI VMWare (not Harvester) - or was this also with:
- Rancher v2.7.5?
- Harvester v1.1.2?

**Comment by nickvth** [comment]
@irishgordo  just with RKE2 via CAPI VMWare (not Harvester).
Rancher v2.7.5

**Comment by futuretea** [comment]
Hi @irishgordo 
> If VMs ( those that are for the RKE2 nodes in Harvester ) are powered off (through Harvester UI), it seems that the Custom RKE2 Cluster hangs in an "Update" state. 

This is an expected behavior.

> If in this "Update" state, the user were to try to register a new "all roles (worker, control-plane, etcd)" node, it will hang in perpetually and never become registered. A work-around discovered: was to delete the original "control-plane" & "etcd" nodes from the Cluster Management UI in Rancher - and re-run the registration on the new third (all-roles: etcd, control-plane, worker) node - then eventually the cluster would be at an "Active" state.

This is not in the Scenario 2 test steps from https://github.com/rancher/rancher/issues/41080#issuecomment-1563269826
user need:
> Once cluster "dies", navigate to Cluster Management > Cluster Details > Machines and delete both nodes

And I think this is an expected behavior, because there are two etcd nodes in the cluster, but one of them fails, so the cluster  will not be at  an "Active" state.

I followed the all steps of https://github.com/rancher/rancher/issues/41080#issuecomment-1563269826, all is well.
do you still have any issues if you follow the test steps?

**Comment by irishgordo** [comment]
@futuretea  - sorry about the delay in getting back to you on this :sweat_smile:  - 
I seem to have not pasted the correct Scenario 2 link:
https://github.com/rancher/rancher/issues/41080#issuecomment-1558134028

**Comment by futuretea** [comment]
> But then if you delete the third node that was added, after adding back a new worker & control-plane&etcd node,
There is an error of:
"init node not found"

> So the "All Roles" Node, upon deletion, is causing the RKE2 Custom Cluster to become unusable.

Hi @irishgordo  The `delete the third node that was added` is not in the Scenario 2 test steps from https://github.com/rancher/rancher/issues/41080#issuecomment-1558134028

**Comment by irishgordo** [comment]
@futuretea from:
https://github.com/rancher/rancher/issues/41080#issuecomment-1558134028
Seems to be stuck on step 7 of scenario 2 with:
v2.7.6 Rancher -> v2.7.7-rc4
and
v1.2.0 Harvester

**Comment by futuretea** [comment]
> @futuretea from: [rancher/rancher#41080 (comment)](https://github.com/rancher/rancher/issues/41080#issuecomment-1558134028) Seems to be stuck on step 7 of scenario 2 with: v2.7.6 Rancher -> v2.7.7-rc4 and v1.2.0 Harvester

@irishgordo from https://github.com/rancher/rancher/issues/41080#issuecomment-1558134028, we should test the upgrade from 2.7.3 to 2.7.6

**Comment by irishgordo** [comment]
Hi @futuretea , thanks for explaining that more :smile: - 
After checking from v2.7.3 -> v2.7.6, it seems to be hung at step 7 still:
```
ubuntu@all-roles-vm-new:~$ curl --insecure -fL https://the-ipv4-address-of-the-rancher-vm-that-was-running-v273-that-then-was-upgraded-to-v276.nip.io/system-agent-install.sh | sudo  sh -s - --server https://the-ipv4-address-of-the-rancher-vm-that-was-running-v273-that-then-was-upgraded-to-v276.nip.io --label 'cattle.io/os=linux' --token 4h7rn4mgrqbg87tl6cq9wvfqj97jv86lhnnn879nvthcnm4p7d98qv --ca-checksum 00e5a268ec3d5fb7bff2369021078fd8452b1c4148cf59c12a251c6f7595c440 --etcd --controlplane --worker
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 30867    0 30867    0     0   115k      0 --:--:-- --:--:-- --:--:--  115k
[INFO]  Label: cattle.io/os=linux
[INFO]  Role requested: etcd
[INFO]  Role requested: controlplane
[INFO]  Role requested: worker
[INFO]  Using default agent configuration directory /etc/rancher/agent
[INFO]  Using default agent var directory /var/lib/rancher/agent
[INFO]  Determined CA is necessary to connect to Rancher
[INFO]  Successfully downloaded CA certificate
[INFO]  Value from https://the-ipv4-address-of-the-rancher-vm-that-was-running-v273-that-then-was-upgraded-to-v276.nip.io/cacerts is an x509 certificate
[INFO]  Successfully tested Rancher connection
[INFO]  Downloading rancher-system-agent binary from https://the-ipv4-address-of-the-rancher-vm-that-was-running-v273-that-then-was-upgraded-to-v276.nip.io/assets/rancher-system-agent-amd64
[INFO]  Successfully downloaded the rancher-system-agent binary.
[INFO]  Downloading rancher-system-agent-uninstall.sh script from https://the-ipv4-address-of-the-rancher-vm-that-was-running-v273-that-then-was-upgraded-to-v276.nip.io/assets/system-agent-uninstall.sh
[INFO]  Successfully downloaded the rancher-system-agent-uninstall.sh script.
[INFO]  Generating Cattle ID
curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
curl: (28) Operation timed out after 60001 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
curl: (28) Operation timed out after 60000 milliseconds with 0 bytes received
[ERROR]  000 received while downloading Rancher connection information. Sleeping for 5 seconds and trying again
```
For some reason it seems to think that the worker-node is still up and running - but both - had been powered off prior to upgrade from v2.7.3->v2.7.6 - and the cluster was seen as "dies"...
I'm not sure why the custom rke2 cluster after upgrade to v2.7.6 seems to think that the original worker node is still on :thinking: 
![Screenshot from 2023-09-15 11-55-40](https://github.com/harvester/harvester/assets/5370752/d2af3755-8929-44de-80d4-483b168ad94b)

**Comment by alex-isv** [comment]
I can confirm the similar issue on Harvester 1.2.0 VMs. Using Rancher 2.7.6 and creating RKE2 cluster. All hanging when adding VMs to the cluster with " Rkecontrolplane was already initialized but no etcd machines exist that have plans, indicating the etcd plane has been entirely replaced. Restoration from etcd snapshot is required. "  Rancher 2.7.4 didn't have this issue.

**Comment by FrankYang0529** [comment]
Hi @irishgordo, since there was error link in previous comment, I copy full scenario 2 steps here. The original step is not clear about how to handle old stopped worker, so I also remove it in step 7.

1. Fresh install of Rancher v2.7.9.
2. Provision a downstream RKE2 Custom cluster w/ 1 etcd/cp node and 1 wkr node w/ s3 snapshots configured.
3. Once active, deploy a workload in default namespace.
4. Take a snapshot (s3).
5. Once snapshot is successfully captured, power down all nodes.
6. Once cluster "dies", upgrade Rancher to v2.8.2.
7. Register 1 new node - all-roles to cluster, then delete the existing etcd/cp/worker nodes.
8. Once active, restore to snapshot taken in step 4.
9. Observe restore worked by confirming workload deployed in step 3 is still seen in cluster.
10. Register 2 more nodes - 1 etcd/cp, and 1 worker.
11. Verified - RKE2 cluster successfully restored from snapshot when cluster is down.

When I delete old worker node, it can't be removed smoothly. The reason is that CAPI try its best to drain workload and detach volume on the node. If we don't set `nodeDrainTimeout` and `nodeVolumeDetachTimeout`, CAPI will keep trying. However, I don't think this is a bug, because CAPI wants to safely remove node and it also provides options to skip the check. I think we can have a known issue document to guide users to remove old nodes if the cluster is down caused of restoring snapshot.

cc @bk201 

https://github.com/harvester/harvester/assets/4927361/2982a4b7-1f70-4c67-91cd-7e4dc3bef3a9

**Comment by bk201** [comment]
@irishgordo can you check PoAn's comment and see if this is still a high-priority issue? Thanks.

**Comment by irishgordo** [comment]
@bk201 
I do think that if there's a document to highlight this guide like @FrankYang0529 mentions:
> I think we can have a known issue document to guide users to remove old nodes if the cluster is down caused of restoring snapshot.

Then we can close this out.
I believe it is less common to see custom cloud provider rke2 clusters generally w/ Harvester, but still unsure :thinking:  -so not sure on the priority but a document to highlight modifying `nodeDrainTimeout` &  `nodeVolumeDetachTimeout` that would be good :smile:

**Comment by FrankYang0529** [comment]
Hi @irishgordo, the root cause here is not about custom cloud provider. Also, the drain options are about Rancher. Probably, we can leave Rancher to document it and we can close this issue? Thanks.

https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/nodes-and-node-pools#aggressive-and-safe-draining-options

**Comment by irishgordo** [comment]
Yeah that sounds good to me :smile: :+1: - thanks @FrankYang0529  - I'll go ahead and close this out
