### ISSUE TITLE
[BUG] Booting into installation process hangs

### ISSUE THREAD

**Issue by fwbochum** [harvester/harvester#4086]
**Describe the bug**
I can't get to the installation process because the boot process from the USB stick hangs. I waited more than 2 hours but nothing happens. Cursor is blinking all the time.

**To Reproduce**
Boot from USB drive. Choose Harvester. Wait.

**Expected behavior**
I want to install Harvester and go through the installation process.

**Support bundle**
Output:
[ 1282.389599][ T203] input: Logitech Wireless Device PID:4069 Keyboard as /devices/pc 10000:00/0000:00:14.0/usb1/1-12/1-12.1/1-12.1:1.2/0003:046D: C52B.0005/0003:046D: 4069.0007/ input/ input 12
[ 1282.589372][ T203] input: Logitech Wireless Device PID: 4069 Mouse as /device s/pc i0000:00/0000:00:14.0/usb1/1-12/1-12.1/1-12.1:1.2/0003 :046D: C52B. 0005/0003: 046D: 4069. 0007/ input/ input13
[ 1282.786071][ T203] hid-generic 0003:046D: 4069.000?: input,hidraw: USB HID U1.11 Keyboard [Logitech Wireless Device PID: 4069] on usb-0000:00:14.0-12.1/ input2:2
[ 1282.963848][ T203] logitech-hidpp-device 0003:046D :402D.0008: hidraw5: USB HID U1.11 Keyboard [Logitech M5601 on usb-0000:00:14.0-12.1/ input2:4
[ 1283.28399][ T891] input: Logitech Craft as /devices/pc i0000:00/0000:00:14.0/usb1/1-12/1-12.1/1-12.1:1.2/0003:046D:C52B.0005/0003:046D: 4066.0006/ input/ input17
[ 1283.455005][ T891] logitech-hidpp-device 0003:046D : 4066 .0006: input, hidraw3:USB HID v1.11 Keyboard [Logitech Craft] on usb-0000:00:14.0-12.1/ imput2:1
[ 1283.771995][ T891] input: Logitech MX Master 2S as /devices/pc i0000:00/0000:00:14.0/usb1/1-12/1-12.1/1-12.1:1.2/0003:046D: C52B. 0005/0003:046D: 4069. 0007/ inpu t/input18
[ 1283.950240][ T891] logitech-hidpp-device 0003:046D:4069.0007: input,hidraw4 : USB HID U1.11 Keyboard [Logitech MX Master 2S] on usb-0000:00: 14.0-12. 1/ input2:2
[ 1360.203906][ T1202) squashfs: version 4.0 (2009/01/31) Phillip Lougher
[ 1360.324843][ T1212] loop0: detected capacity change from 0 to 1215312
_
^ *Blinking Cursor*

**Environment**
 - Harvester ISO version: harvester-v1.1.2-amd64.iso
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with
 -- MSI MAG Z690 TOMAHAWK WIFI
 -- Intel Core i5-13600K
 -- Corsair VENGEANCE DDR5 RAM 128GB (4x32GB) 5600MHz
 -- NVMe SSD 2 TB

**Additional context**
I used Balena Etcher and the dd command. I downloaded the ISO file a second time and tried several USB sticks and different USB ports, but the result is the same. Even without any USB device attached.

**Comment by bk201** [comment]
Thanks for reporting. It seems that you already tried another USB port, can you verify if using a USB 2.0 port works? If there is one.

**Comment by fwbochum** [comment]
Editing the boot options and removing "console=ttyS0" solved the problem. 🙌🏻
Source: https://docs.harvesterhci.io/dev/install/usb-install#other-issues
