### ISSUE TITLE
[BUG]When accessing imported Harvester in Rancher, Grafana metrics don't work correctly

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#4087]
**Describe the bug**

**To Reproduce**
Preparation:

1. Go to Rancher.
2. Go to import existing Harvester cluster.
3. Access Harvester cluster.
4. Go to Harvester Dashboard page.
5. Grafana metrics display `page not found`

**Expected behavior**

The grafana metrics of the imported Harvester cluster should be displayed.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
The `appSubUrl` changes from `100.1.1+up19.0.3` to `102.0.0+up40.1.2` to `102.0.1+up40.1.2`

```
/go/src/github.com/rancher/charts/charts/rancher-monitoring/100.1.1+up19.0.3$ 
charts/grafana/templates/nginx-config.yaml:          

         sub_filter '"appSubUrl":""' '"appSubUrl":"."';

/go/src/github.com/rancher/charts/charts/rancher-monitoring/102.0.0+up40.1.2$
charts/grafana/templates/nginx-config.yaml:          

         sub_filter '"appSubUrl":""' '"appSubUrl":"/k8s/clusters/{{ .Values.global.cattle.clusterId }}/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';

/go/src/github.com/rancher/charts/charts/rancher-monitoring/102.0.1+up40.1.2$ 
charts/grafana/templates/nginx-config.yaml:          

         {{- if eq .Values.global.cattle.clusterId "local" -}}
         sub_filter '"appSubUrl":""' '"appSubUrl":"/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
         {{- else -}}
         sub_filter '"appSubUrl":""' '"appSubUrl":"/k8s/clusters/{{ .Values.global.cattle.clusterId }}/api/v1/namespaces/{{ template "grafana.namespace" . }}/services/http:{{ template "grafana.fullname" . }}:{{ .Values.service.port }}/proxy"';
         {{- end -}}
```

The previous issue https://github.com/harvester/harvester/issues/3780 and PR https://github.com/harvester/harvester-installer/pull/492.  Can work for local mode, but not for multi-cluster mode.

**Comment by w13915984028** [comment]
But there is a limitation:

The `Values.global.cattle.clusterId` will decide the value of `appSubUrl` in a configMap, one cluster can only have one role.

This is OK, when the `chart` is installed in an Rancher downstream cluster.

But it does not work well for `Harvester`.

When `Harvester` is accessed directly, the role is `local`.

When `Harvester` is imported into Rancher and accessed from Rancher , the role is a cluster, named like `c-m-75b2hnlw`.

The UI needs to deal with those 2 scenarios.

The backend fix https://github.com/harvester/harvester-installer/pull/512, is utilizing the nginx customization:.

**Comment by w13915984028** [comment]
@WuJun2016 @DaiYuzeng 

With the fix, there is still one issue, if we click `grafana` from `Rancher->Harvester`, the newly opened window, has no `Referer` field, thus the backend does not know where it comes from.  Please take a look, if UI can add this field when click the link.

When we refresh the Harvester dashboard, there always has an `Referer` on `grafana` related request.

![image](https://github.com/harvester/harvester/assets/31133476/831d7a23-1b52-49db-baf0-a86e3650dfd2)


![image](https://github.com/harvester/harvester/assets/31133476/1f9e7d77-4732-4be3-8c6d-3898da138520)

**Comment by noahgildersleeve** [comment]
Tested in Harvester master-173b0824-head and Rancher v2.7.5-rc5 with single node Docker instance. Verified that Grafana was showing up on both dashboard and in Grafana dashboard.

![Screenshot_20230622_195245](https://github.com/harvester/harvester/assets/83787952/fe17d8c1-b30f-4bc0-a894-9746dabb3f34)
![Screenshot_20230622_195239](https://github.com/harvester/harvester/assets/83787952/5ec2a9ef-d69e-4718-9339-117d57016079)
