### ISSUE TITLE
[BUG] Page Projects/Namespaces is not available

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4094]
### Describe the bug
![image](https://github.com/harvester/harvester/assets/5169694/bdaf6032-9285-404b-9ac9-1239b96f3e92)

### To Reproduce
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Access Harvester from Rancher

### Expected behavior
Page `Projects/Namespaces` should available

## Environment:
 - Harvester ISO version: **v1.2-3ea43d86-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM single node**
 - Rancher Version: **v2.7.5-rc5** and **v2.6.13**

**Comment by WuJun2016** [comment]
waiting pr merge:  https://github.com/rancher/rancher/pull/41710

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/ef87b99a-1113-47b0-a7ed-37e9df164d7a)


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2.0-rc2**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.7-9a33c24de30c81f2ecd900d923d16d7fb2020929-head** (Docker Image: **sha256:3c0baa609934e8b1c90fde38d9f96526ac0dc52c00702d130480ac5792922e15**)

### Verify Steps
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/4094#issue-1758848617
