### ISSUE TITLE
[BUG] errors from `systemd-timesyncd` on Harvester nodes don't bubble up to Harvester after setting NTP servers

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4099]
**Describe the bug**
Harvester UI currently doesn't receive any information from the Nodes `systemd-timesyncd`.
Where there could be errors if a user sets a bad NTP server:
```
Jun 16 23:02:26 harvester-node-0 systemd-timesyncd[23739]: Server has too large root distance. Disconnecting.
Jun 16 23:02:58 harvester-node-0 systemd-timesyncd[23739]: Server has too large root distance. Disconnecting.
Jun 16 23:04:01 harvester-node-0 systemd[1]: Stopping Network Time Synchronization...
Jun 16 23:04:01 harvester-node-0 systemd[1]: systemd-timesyncd.service: Deactivated successfully.
Jun 16 23:04:01 harvester-node-0 systemd[1]: Stopped Network Time Synchronization.
Jun 16 23:04:01 harvester-node-0 systemd[1]: Starting Network Time Synchronization...
Jun 16 23:04:02 harvester-node-0 systemd[1]: Started Network Time Synchronization.
Jun 16 23:04:02 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:04:02 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:04:02 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:04:02 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
```
Additionally, you can see:
```
Jun 16 23:42:36 harvester-node-0 systemd[1]: systemd-timesyncd.service: Deactivated successfully.
Jun 16 23:42:36 harvester-node-0 systemd[1]: Stopped Network Time Synchronization.
Jun 16 23:42:36 harvester-node-0 systemd[1]: Starting Network Time Synchronization...
Jun 16 23:42:37 harvester-node-0 systemd[1]: Started Network Time Synchronization.
Jun 16 23:42:47 harvester-node-0 systemd-timesyncd[31671]: Timed out waiting for reply from 192.168.1.120:123 (192.168.1.120).
Jun 16 23:43:30 harvester-node-0 systemd-timesyncd[31671]: Timed out waiting for reply from 192.168.1.120:123 (192.168.1.120).

```

**To Reproduce**
1. Create a purposefully bad NTP server
2. Modify the NTP server settings in Harvester
3. Validate that the settings are persisting / passing validation via: `kubectl logs --follow services/harvester-webhook -n harvester-system` will see content like:
```
time="2023-06-16T21:55:26Z" level=info msg="ntpSettings: &{NTPServers:[0.suse.pool.ntp.org 1.suse.pool.ntp.org]}"
time="2023-06-16T21:55:26Z" level=info msg="NTP servers validation passed"
time="2023-06-16T22:30:44Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
time="2023-06-16T22:30:44Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
time="2023-06-16T22:30:44Z" level=info msg="NTP servers validation passed"
time="2023-06-16T22:30:44Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
time="2023-06-16T22:30:44Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
time="2023-06-16T22:30:44Z" level=info msg="NTP servers validation passed"
```
4. On a Harvester cluster of N nodes, validate that on the node the Server is what was set via the Harvester settings UI for the NTP servers, like:
```
harvester-node-0:/home/rancher # timedatectl timesync-status
       Server: 192.168.1.120 (192.168.1.120)
Poll interval: 34min 8s (min: 32s; max 34min 8s)
 Packet count: 0
```
5. Audit the logs from systemd:
```
harvester-node-0:/home/rancher # journalctl --unit=systemd-timesyncd.service | tail -n 15
Jun 16 23:07:47 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:07:47 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:07:47 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:12:03 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.
Jun 16 23:20:36 harvester-node-0 systemd-timesyncd[26646]: Server has too large root distance. Disconnecting.

```

**Expected behavior**
Something in the UI to let the Administrator know that the NTP server(s) used are causing those `systemd-timesyncd` errors.

**Environment**
 - Harvester ISO version: v1.2.0-rc2
 - Underlying Infrastructure: qemu/kvm

**Comment by irishgordo** [comment]
What additionally I'm noticing from the `kubectl logs --follow services/harvester-webhook -n harvester-system` is it seems that the `validation` will always pass, regardless of the IPv4 Address?

```
time="2023-06-16T22:30:44Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
time="2023-06-16T22:30:44Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
time="2023-06-16T22:30:44Z" level=info msg="NTP servers validation passed"
time="2023-06-16T23:44:39Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.121\"]}"
time="2023-06-16T23:44:39Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.121]}"
time="2023-06-16T23:44:39Z" level=info msg="NTP servers validation passed"
time="2023-06-16T23:44:39Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.121\"]}"
time="2023-06-16T23:44:39Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.121]}"
time="2023-06-16T23:44:39Z" level=info msg="NTP servers validation passed"
time="2023-06-16T23:45:11Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
time="2023-06-16T23:45:11Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
time="2023-06-16T23:45:11Z" level=info msg="NTP servers validation passed"
time="2023-06-16T23:45:11Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
time="2023-06-16T23:45:11Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
time="2023-06-16T23:45:11Z" level=info msg="NTP servers validation passed"
```

Even though those addresses on the nodes in Harvester are causing the:
```
Jun 16 23:44:51 harvester-node-0 systemd-timesyncd[2876]: Timed out waiting for reply from 192.168.1.121:123 (192.168.1.121).
Jun 16 23:46:05 harvester-node-0 systemd-timesyncd[3931]: Timed out waiting for reply from 192.168.1.120:123 (192.168.1.120).

```

Is the "NTP servers validation passed" for the webhook just validating that the user provided an IPv4 address and passing when that happens?

**Comment by Vicente-Cheng** [comment]
> What additionally I'm noticing from the `kubectl logs --follow services/harvester-webhook -n harvester-system` is it seems that the `validation` will always pass, regardless of the IPv4 Address?
> 
> ```
> time="2023-06-16T22:30:44Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
> time="2023-06-16T22:30:44Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
> time="2023-06-16T22:30:44Z" level=info msg="NTP servers validation passed"
> time="2023-06-16T23:44:39Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.121\"]}"
> time="2023-06-16T23:44:39Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.121]}"
> time="2023-06-16T23:44:39Z" level=info msg="NTP servers validation passed"
> time="2023-06-16T23:44:39Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.121\"]}"
> time="2023-06-16T23:44:39Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.121]}"
> time="2023-06-16T23:44:39Z" level=info msg="NTP servers validation passed"
> time="2023-06-16T23:45:11Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
> time="2023-06-16T23:45:11Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
> time="2023-06-16T23:45:11Z" level=info msg="NTP servers validation passed"
> time="2023-06-16T23:45:11Z" level=info msg="Prepare to validate NTP servers: {\"ntpServers\":[\"192.168.1.120\"]}"
> time="2023-06-16T23:45:11Z" level=info msg="ntpSettings: &{NTPServers:[192.168.1.120]}"
> time="2023-06-16T23:45:11Z" level=info msg="NTP servers validation passed"
> ```
> 
> Even though those addresses on the nodes in Harvester are causing the:
> 
> ```
> Jun 16 23:44:51 harvester-node-0 systemd-timesyncd[2876]: Timed out waiting for reply from 192.168.1.121:123 (192.168.1.121).
> Jun 16 23:46:05 harvester-node-0 systemd-timesyncd[3931]: Timed out waiting for reply from 192.168.1.120:123 (192.168.1.120).
> ```
> 
> Is the "NTP servers validation passed" for the webhook just validating that the user provided an IPv4 address and passing when that happens?

We do not do the live NTP server validation like the installer because if we have different (maybe cross-rack) nodes, they only could connect with a partial NTP server. The live validation may cause some problems. The webhook only validates the FQDN, IPv4 style.

Also, we do not expose the systemd error. The end user could see three status `disabled`, `unsync` and `sync` on the host page.

related to issue: https://github.com/harvester/harvester/issues/3133

Thanks!

**Comment by irishgordo** [comment]
@Vicente-Cheng ahh okay :smile: :+1:  - those three statuses will be useful :smile: 

And if the user desired to look at the systemd logs they could always navigate to the nodes directly and examine them.
So I'll go ahead and close this out :smile:
