### ISSUE TITLE
[Question] The network of the node is unreachable when haverster is ready

### ISSUE THREAD

**Issue by tossmilestone** [harvester/harvester#410]
We are using a single baremetal node to install the harvester, and when the harvester is installed and running, the node is unable to access from network anymore. The eth0 interface of the node has a new ip with 169 prefix. What cause the network problem? Please help us.

**Comment by yaocw2020** [comment]
It's very likely that DHCP request failed. You need an available DHCP server in your network.

**Comment by tossmilestone** [comment]
@yaocw2020 We will have a try, thanks. Does the harvester could not support static ip?

**Comment by yaocw2020** [comment]
> @yaocw2020 We will have a try, thanks. Does the harvester could not support static ip?

Yes, Harvester v0.1.0 only supports DHCP. Static IPv4 address support is in the process. We hope it merged in the next release version.
