### ISSUE TITLE
[FEATURE]DataLocality support in storageclass

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4101]
**Is your feature request related to a problem? Please describe.**

Harvester we have created storageclasses where the parameter dataLocality is set to best-effort and another where the paramter is set to strict local.
When we create a image from a download url we have to select a storaceclass which is referenced to the image. It seems to be in the background harvester is creating another storageclass only for the image which will be used when creating a volume from the image source. This storageclass take over the parameters from the selected storageclass except the dataLocality parameter. After creating the image the storaceclass paramters cannot be edited.

After creating a volume from the image source, in longhorn the paramter dataLocality in set to the system default (in our case "disabled").

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by WebberHuang1118** [comment]
Required document to explain `best-effort` data locality, and why Harvester prevents `strict-local` locality for VM migration and ugrade.

**Comment by lanfon72** [comment]
Move back to implement.
UI and doc should also have a PR for this.

**Comment by WebberHuang1118** [comment]
@lanfon72 
DataLocality could be configured via SC's Parameters with key `dataLocality`
![sc-bf](https://github.com/harvester/harvester/assets/19387129/ad585c42-a7b0-4c19-ba0d-c3e84dc214b2)

And we will have a document update afterwards, thanks.

**Comment by WebberHuang1118** [comment]
Updated with [draft doc PR](https://github.com/harvester/docs/pull/506), thanks.

**Comment by lanfon72** [comment]
Verified this feature has been implemented.

![image](https://github.com/harvester/harvester/assets/5169694/6a1231fd-f642-44df-a144-2ddee7f43579)
![image](https://github.com/harvester/harvester/assets/5169694/c4defdda-48a7-4af2-95ab-3460e149a452)

Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.3.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create new storage class with **parameter** `dataLocality`
    a. storage class should able to be created when the value in  `best-effort` or `disabled`
    b. storage class should prompt error message **not allowed** when the value set as `strict-local`
    c. storage class should prompt error message **invalid** when the value is not listed above
3. Create images from created storage class, image should be created successfully
4. Create VMs from created images, VM should be created successfully
