### ISSUE TITLE
[FEATURE]Need a detailed progress and estimation for backup (maybe also restore) of VMs and volumes

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4102]
**Is your feature request related to a problem? Please describe.**

We need a visibal and CLI way to check the status of a backup and restore of VMs and also for volumes being backed up / restored.

The status / progress needs to show the total capacity that needs to be backed up, the percentage that has been backed up, already and the estimated time for completion based on the current backup performance. 

Especially with large size volumes and VMs this is important as admins need to be able to plan acordingly.

Even after a backup admins should be able to see how much data has been backed up and how long the backup required. (same also for restores)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by torchiaf** [comment]
UI side, this will require an additional modal dialog or a progress bar on top right side, showing the information from the backend. It could be the same component for both Volumes and VMs.

**Comment by bk201** [comment]
Reopen. QA should verify the issue before closing it.

**Comment by TachunLin** [comment]
Verifyied **fixed** on `master-6ca6acfd-head` (24/01/23). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Take vm backup progress bar and state $~~$</summary>

* Can display progress bar with percentage rate during vm backup process (On backup page)

![image](https://github.com/harvester/harvester/assets/29251855/0ab2aef2-f169-46ea-8ae4-e6b00ffe8b4b)


https://github.com/harvester/harvester/assets/29251855/cf2cb91e-bd58-431b-9259-3caf2310379d


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Restore vm from backup progress bar and state  $~~$</summary>

* Can display progress bar with percentage rate during restore vm process (Create new VM) 

https://github.com/harvester/harvester/assets/29251855/0e887661-ecd4-43c8-9326-b20e28f62a3b

![image](https://github.com/harvester/harvester/assets/29251855/389ece87-3538-4421-b340-d31389ca1307)


* Can display progress bar with percentage rate during restore vm process (Replace existing VM -> Retain volume)  

https://github.com/harvester/harvester/assets/29251855/c1fa5cc5-8c92-4e5a-8641-4c31d0e54905

* Can display progress bar with percentage rate during restore vm process (Replace existing VM -> Delete volume)  

https://github.com/harvester/harvester/assets/29251855/727f674b-c856-4914-99d9-ee74658373f4


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ volume backup state and percentage $~~$</summary>

* Can display the volume backup percentage on the backup progress bar
![image](https://github.com/harvester/harvester/assets/29251855/57bb39e7-135b-4310-a055-c1a4d334c71b)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ volume restore state and percentage $~~$</summary>

* Can display the volume restore percentage on the restore progress bar
![image](https://github.com/harvester/harvester/assets/29251855/e658041a-3155-41c8-b996-5081ae7ec1ad)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Progress bar for large size vm backup and restore $~~$</summary>

* Backup large size disk on vm, can display volume backup percentage on the backup progress bar well



https://github.com/harvester/harvester/assets/29251855/bf0b79b2-94d9-4b55-b164-55c1abc5ff76




 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ multiple (intense) backup and restore progress bar $~~$</summary>

* Backup multiple vms in short time, the progress bar and volume status can work well 



https://github.com/harvester/harvester/assets/29251855/bef406b1-4866-467b-a7ab-514480add2d9



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Negative: failed to create backup  $~~$</summary>

* When backup target service failed to connect, the backup would prompt error message with the correct progress bar state
![image](https://github.com/harvester/harvester/assets/29251855/3608c24d-55ec-4ff7-9453-5bd1b7a4b11a)



 </details>



### Test Information
* Test Environment: 3 nodes harvester on baremetal machines
* Harvester version: v1.1-340486a3-head (23/11/20)

### Verify Steps
<details><summary>Take vm backup progress bar and state </summary>


</details>

<details><summary>Restore vm from backup progress bar and state  </summary>


</details>

<details><summary>volume backup state and percentage  </summary>


</details>

<details><summary>volume restore state and percentage </summary>


</details>

<details><summary>Progress bar for large size vm backup and restore </summary>


</details>

<details><summary>multiple (intense) backup and restore progress bar </summary>


</details>

**Comment by TachunLin** [comment]
Tested on most of the scenarios, the progress bar and volume percentage works well on backup and restore actions.
Just found something strange in the negative testing. 
When we try to restore from backup to create a new vm, but the remote NFS backup service failed to connect. (By disable the service). 
The restore progress would not display any error message, and the restore progress bar and volume state seems not well reflect actual behavior. 

https://github.com/harvester/harvester/assets/29251855/220efb28-7b85-4872-9062-e7012aefa12a

Thus I create another ticket #5038 for us to track as enhancement.
