### ISSUE TITLE
[BUG] Popup JSON parse error on the node host page in a fresh-installed machine w/o any configuration. 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4103]
## Describe the bug
Popup JSON parse error on the node host page in a clean Harvester (fresh-installed w/o configuration)

## To Reproduce
1. Fresh install Harvester
2. Go to 'Hosts'
3. Click node name
4. Popup error on upper-right corner
   > **Note** : No explict error found in browser dev tool
   > ![error_json_parse](https://github.com/harvester/harvester/assets/2773781/5201c092-71f0-4646-9149-74e350e887f4)

## Expected behavior
1. Node host info page should not show ambiguous error in a fresh-installed machine w/o any configuration. 
2. All notifications should be clear after press "Clear All Notifications" button but still one error left.

## Support bundle
[supportbundle_14827ffe-4d40-4f8f-83f1-e158b32ac6ff_2023-06-19T02-34-28Z.zip](https://github.com/harvester/harvester/files/11783636/supportbundle_14827ffe-4d40-4f8f-83f1-e158b32ac6ff_2023-06-19T02-34-28Z.zip)

## Environment
 - Harvester ISO version: 1.2.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM, single node
 - Browser:
   - Chrome 114.0.5735.133
   - Firefox 102.12.0esr

## Additional context
Video example

https://github.com/harvester/harvester/assets/2773781/d6045b2d-3641-4221-b76f-c867c68b86fb

**Comment by noahgildersleeve** [comment]
Tested in Harvester version `master-173b0824-head`. Pop up did not show up when testing.

## Validation steps

1. Fresh install Harvester
2. Go to 'Hosts'
3. Click node name


![Screenshot_20230623_112807](https://github.com/harvester/harvester/assets/83787952/53149f60-32db-4de5-bb4a-147f2f5b5682)
![Screenshot_20230623_112800](https://github.com/harvester/harvester/assets/83787952/89880862-2e99-4c0c-9098-8d0644359968)
