### ISSUE TITLE
[ENHANCEMENT] Harvester Addon needs to improve the processing of disable

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4108]
**Is your enhancement related to a problem? Please describe.**

Harvester addon needs to improve the processing of disable.

For large `addon` like `rancher-monitoring`, the `enable` and `disable` will take some time to finish the action

**Describe the solution you'd like**

When an `Addon` is disabled, it should become a new `disabling` status, and if user click `enable` again, the action should be denied, to make sure the `enable` will wait until the previous `disable` action is finished. To avoid potential race condition.

The `enable` -> `disable` will also be double checked.

**Describe alternatives you've considered**

**Additional context**

issue https://github.com/harvester/harvester/issues/4125 will also be solved in this enhancement,

In the enhancement of https://github.com/harvester/harvester/issues/4071, we need to wait the `addon` is disabled, and then remove the reference of PV toward PVC

cc @guangbochen @ibrokethecloud

**Comment by w13915984028** [comment]
Encounter such issue:

disable/enable `rancher-monitoring` for first time, it is OK.

delete Harvester POD

disable/enable `rancher-monitoring` for second  time

(1)  Disable `rancher-monitoring`, but UI still shows `DeploySuccessful`

![image](https://github.com/harvester/harvester/assets/31133476/dcfc9743-63b5-4c66-ab6c-c51de1ec8019)

But the status is `""` .
```
harv41:~ # kk get addons.harvesterhci.io -n cattle-monitoring-system rancher-monitoring -ojsonpath={".status"}
{}
```

Similar with https://github.com/harvester/harvester/issues/4125

(2) The `delete job` was there for a short while
```
harv41:~ # kk get jobs -A
NAMESPACE                  NAME                               COMPLETIONS   DURATION   AGE
cattle-monitoring-system   helm-delete-rancher-monitoring     1/1           4s         4m54s
cattle-monitoring-system   helm-install-rancher-monitoring    1/1           40s        2m21s
```

(3) The `jobs` are gone, both `helm-install` and `helm-delete`
```
harv41:~ # kk get jobs -A
NAMESPACE     NAME                               COMPLETIONS   DURATION   AGE
kube-system   helm-install-rke2-canal            1/1           10s        19d
```

(4) All pods of `rancher-monitoring` are left untouched
```
harv41:~ # kk get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS        AGE
alertmanager-rancher-monitoring-alertmanager-0           2/2     Running   1 (2m40s ago)   2m54s
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0               2m52s
rancher-monitoring-grafana-7fc56c48dc-tk8z7              4/4     Running   0               2m58s
rancher-monitoring-kube-state-metrics-65cd94fffc-dkbrl   1/1     Running   0               2m58s
rancher-monitoring-operator-56f6964d8f-7r2fw             1/1     Running   0               2m58s
...
```

**Comment by w13915984028** [comment]
The root cause is:

The `helm-install` /`helm-delete` job is not deleted automatically.  As long as we disable/enable the addon continuously, the previous remaing `job` will after later action.


e.g:

After one round of `disable/enable` `rancher-monitoring`, there are 2 jobs
```
harv41:/home/rancher # kk get job -A
NAMESPACE                  NAME                               COMPLETIONS   DURATION   AGE
cattle-monitoring-system   helm-delete-rancher-monitoring     1/1           4s         3m28s
cattle-monitoring-system   helm-install-rancher-monitoring    1/1           41s        65s
kube-system                helm-install-rke2-canal            1/1           10s        19d
```

disable `rancher-monitoring` again:

```
harv41:/home/rancher # kk get job -A
NAMESPACE                  NAME                               COMPLETIONS   DURATION   AGE
cattle-monitoring-system   helm-delete-rancher-monitoring     1/1           4s         3m47s
cattle-monitoring-system   helm-install-rancher-monitoring    1/1           41s        84s
kube-system                helm-install-rke2-canal            1/1           10s        19d
kube-system                helm-install-rke2-coredns          1/1           11s        19d
kube-system                helm-install-rke2-ingress-nginx    1/1           14s        19d
kube-system                helm-install-rke2-metrics-server   1/1           28s        19d
kube-system                helm-install-rke2-multus           1/1           10s        19d
```

After a few seconds, both `jobs` are gone, and the `rancher-monitoring` pods are left.

```
harv41:/home/rancher # kk get job -A
NAMESPACE     NAME                               COMPLETIONS   DURATION   AGE
kube-system   helm-install-rke2-canal            1/1           10s        19d
kube-system   helm-install-rke2-coredns          1/1           11s        19d
kube-system   helm-install-rke2-ingress-nginx    1/1           14s        19d
kube-system   helm-install-rke2-metrics-server   1/1           28s        19d
kube-system   helm-install-rke2-multus           1/1           10s        19d
```


We need to remove remaing previous jobs when click `enable` and `disable`.

Refer: https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/

**Comment by w13915984028** [comment]
will be solved in https://github.com/harvester/harvester/pull/4127

**Comment by w13915984028** [comment]
I suspect we hit an upstream bug https://github.com/k3s-io/helm-controller/issues/177#issuecomment-1612900992

As a workaround, now we try had to remove all potential left jobs before any new action.

cc @ibrokethecloud @guangbochen @bk201

**Comment by lanfon72** [comment]
Hi @DaiYuzeng, I think the UI would need a improvement for the state.

https://github.com/harvester/harvester/assets/5169694/b0d52e06-c28d-40c7-a1fd-01f9e3220b2b

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2-a0d3269e-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Navigate to _Advanced/Addons_, enable and disable **rancher-monitoring**
3. While addon enabling/disabling, notification message should displayed to notify user it's enabling/disabling

**Comment by DaiYuzeng** [comment]
There will be some UI changes so I'll move this issue to `Implement` tab.

**Comment by DaiYuzeng** [comment]
The title of error message will be like:

![image](https://github.com/harvester/harvester/assets/15041915/37c32c77-b870-4c4e-8b46-677abf478d77)

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.2.0-rc4**
* **ui-source** Option: **External**

### Verify Steps
1. Install Harvester with any nodes
2. Navigate to _Advanced/Addons_, enable and disable **rancher-monitoring**
3. While addon enabling/disabling, notification message should displayed to notify user it's enabling/disabling
