### ISSUE TITLE
[BUG] Harvester POD has error log of checkHelmChartExists helmcharts not found

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4109]
**Describe the bug**

Following error is observed in Harvester POD

> time="2023-06-19T18:38:48Z" level=error msg="error syncing 'cattle-logging-system/rancher-logging': handler monitor-addon: error querying helmchart in checkHelmChartExists: helmcharts.helm.cattle.io \"rancher-logging\" not found, requeuing"

> time="2023-06-19T18:38:48Z" level=error msg="error syncing 'harvester-system/vm-import-controller': handler monitor-addon: error querying helmchart in checkHelmChartExists: helmcharts.helm.cattle.io \"vm-import-controller\" not found, requeuing"

>time="2023-06-19T18:38:48Z" level=error msg="error syncing 'harvester-system/pcidevices-controller': handler monitor-addon: error querying helmchart in checkHelmChartExists: helmcharts.helm.cattle.io \"pcidevices-controller\" not found, requeuing"

>time="2023-06-19T18:38:48Z" level=error msg="error syncing 'cattle-monitoring-system/rancher-monitoring': handler monitor-addon: error querying helmchart in checkHelmChartExists: helmcharts.helm.cattle.io \"rancher-monitoring\" not found, requeuing"

All addons are disabled:
```
kubectl get addons.harvesterhci.io -A
NAMESPACE                  NAME                    HELMREPO                                                 CHARTNAME                         ENABLED
cattle-logging-system      rancher-logging         http://harvester-cluster-repo.cattle-system.svc/charts   rancher-logging                   false
cattle-monitoring-system   rancher-monitoring      http://harvester-cluster-repo.cattle-system.svc/charts   rancher-monitoring                false
harvester-system           pcidevices-controller   http://harvester-cluster-repo.cattle-system.svc/charts   harvester-pcidevices-controller   false
harvester-system           vm-import-controller    http://harvester-cluster-repo.cattle-system.svc/charts   harvester-vm-import-controller    false
```

**To Reproduce**
1. install V1.2.0 Harvester cluster
2. check log of `Harvester POD`
3. if not found, kill Harvester POD and re-check

**Expected behavior**

There is no such error log.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Observed when developing https://github.com/harvester/harvester/issues/4071

**Comment by guangbochen** [comment]
might be identical to https://github.com/harvester/harvester/issues/4108

**Comment by w13915984028** [comment]
This error log described in this issue, is fixed on addon refactor https://github.com/harvester/harvester/pull/4127.

**Comment by irishgordo** [comment]
**Validation Question**
@w13915984028 things seem to look good but just wanted to check the validation process :smile: 

- validate that when addons are enabled, no pod that corresponds with the addon has the `checkHelmChartExists` error present in the logs?
- ensure addons CRDs reflect enabling / disabling?

![Screenshot from 2023-07-25 12-19-59](https://github.com/harvester/harvester/assets/5370752/4fd9ee6a-4686-48e5-89d5-c38aeec285c7)
![Screenshot from 2023-07-25 12-18-33](https://github.com/harvester/harvester/assets/5370752/7b1f55e8-160a-4bb5-b410-f77e3330642b)
![Screenshot from 2023-07-25 12-17-29](https://github.com/harvester/harvester/assets/5370752/1a7368ab-4170-4908-8c6c-17f4bb9383c1)
![Screenshot from 2023-07-25 12-16-04](https://github.com/harvester/harvester/assets/5370752/ce5b3b4e-3a89-4da0-bf7c-ab984278267a)
![Screenshot from 2023-07-25 12-14-09](https://github.com/harvester/harvester/assets/5370752/8f857eed-a8c4-482c-b0b6-9a6091705222)
![Screenshot from 2023-07-25 12-12-13](https://github.com/harvester/harvester/assets/5370752/ba70e41e-286b-4a6a-abf0-6c626d2019d2)

**Comment by irishgordo** [comment]
@w13915984028 I'm going to go ahead and close this out as there were no corresponding helm chart exists / helm charts not found in the error log of the addon pods - thanks for the fix :smile: :+1:
