### ISSUE TITLE
[ENHANCEMENT] Bump elemental-toolkits

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4113]
**Is your enhancement related to a problem? Please describe.**
Bump the new elemental-toolkits with Harvester OS.
We use the elemental-cli from luet. That is an old version. We want to use newer elemental-toolkits on OBS.

**Describe the solution you'd like**
Bump elemental-toolkits

**Describe alternatives you've considered**
None

**Additional context**
Another similar issue: https://github.com/harvester/harvester/issues/3587

**Comment by irishgordo** [comment]
@Vicente-Cheng this seems to look good :smile: :+1: 

I'm able to note:
```
t:/home/rancher # cat /etc/os-release 
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester v1.2"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-v1.2-20230629"
GRUB_ENTRY_NAME="Harvester v1.2"
t:/home/rancher # env
HOSTTYPE=x86_64
LESSCLOSE=lessclose.sh %s %s
XKEYSYMDB=/usr/X11R6/lib/X11/XKeysymDB
LANG=POSIX
WINDOWMANAGER=xterm
LESS=-M -I -R
SUDO_GID=1000
HOSTNAME=t
KUBECONFIG=/etc/rancher/rke2/rke2.yaml
CSHEDIT=emacs
GPG_TTY=/dev/pts/0
LESS_ADVANCED_PREPROCESSOR=no
COLORTERM=1
SUDO_COMMAND=/usr/bin/su
MACHTYPE=x86_64-suse-linux
MINICOM=-c on
CONTAINERD_ADDRESS=/run/k3s/containerd/containerd.sock
OSTYPE=linux
XDG_SESSION_ID=2
USER=root
PAGER=less
MORE=-sl
PWD=/home/rancher
HOME=/root
LC_CTYPE=en_US.UTF-8
HOST=t
SUDO_USER=rancher
XNLSPATH=/usr/X11R6/lib/X11/nls
XDG_SESSION_TYPE=tty
XDG_DATA_DIRS=/usr/share
PROFILEREAD=true
IMAGE_SERVICE_ENDPOINT=unix:///var/run/k3s/containerd/containerd.sock
SUDO_UID=65535
MAIL=/var/mail/root
LESSKEY=/etc/lesskey.bin
SHELL=/bin/bash
TERM=xterm-256color
XDG_SESSION_CLASS=user
CONTAINER_RUNTIME_ENDPOINT=unix:///var/run/k3s/containerd/containerd.sock
SHLVL=1
MANPATH=
LOGNAME=root
XDG_RUNTIME_DIR=/run/user/0
XDG_CONFIG_DIRS=/etc/xdg
PATH=/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/var/lib/rancher/rke2/bin
G_BROKEN_FILENAMES=1
HISTSIZE=1000
CPU=x86_64
LESSOPEN=lessopen.sh %s
_=/usr/bin/env
t:/home/rancher # rpm -qa | grep virtctl
kubevirt-virtctl-0.54.0-150400.3.18.10.x86_64
t:/home/rancher # rpm -qa | grep yip
yip-v1.0.0-150400.1.1.x86_64
```

Also able to visually audit the grub kernel edits:
![Screenshot from 2023-07-06 16-25-37](https://github.com/harvester/harvester/assets/5370752/5b9871b6-d223-4c4b-8966-b182da32eae9)
![Screenshot from 2023-07-06 16-23-50](https://github.com/harvester/harvester/assets/5370752/416ade3f-c21c-4445-85a4-062ac10d5f82)
![Screenshot from 2023-07-06 16-23-28](https://github.com/harvester/harvester/assets/5370752/c9df27c3-d65f-4a2a-948b-a132afe65560)
![Screenshot from 2023-07-06 16-16-26](https://github.com/harvester/harvester/assets/5370752/cb821520-3450-4271-a2c0-c5ce67be0a07)

And also able to verify:
```
t:/home/rancher # rpm -qa | grep -ie "elemental"
elemental-dracut-config-0.10.7-150400.1.1.noarch
elemental-grub-config-0.10.7-150400.1.1.noarch
elemental-immutable-rootfs-0.10.7-150400.1.1.noarch
elemental-cli-0.3.1-150400.2.2.x86_64
elemental-init-setup-0.10.7-150400.1.1.noarch
elemental-init-services-0.10.7-150400.1.1.noarch
elemental-init-recovery-0.10.7-150400.1.1.noarch
elemental-init-network-0.10.7-150400.1.1.noarch
elemental-init-live-0.10.7-150400.1.1.noarch
elemental-init-boot-assessment-0.10.7-150400.1.1.noarch
elemental-init-config-0.10.7-150400.1.1.noarch
elemental-toolkit-0.10.7-150400.1.1.noarch
t:/home/rancher # elemental version
0.3.1+gbab71d1
```

**Validation Question:**
- Is there something additionally with regards to the elemental-toolkits that I should look at on the built iso?

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng this seems to look good 😄 👍
> 
> **Validation Question:**
> 
> * Is there something additionally with regards to the elemental-toolkits that I should look at on the built iso?

Hi @irishgordo,
Let's check the installation, and the upgrade should work as usual.
The main changes for us with bumping elemental version would be the bootup flow and partition label.
These two cases could be validated by installation and upgrade. 
So we need to check the elemental version and ensure the installation (both ipxe/interactive mode) and upgrade work well as usual.

**Comment by irishgordo** [comment]
@Vicente-Cheng 
Testing the upgrade from v1.1.2 -> v1.2.0-rc3 (2 node qemu/kvm) looks good :smile: 
The Labels seem to look good too.
And the ipxe install works great as well.
![Screenshot from 2023-07-10 11-42-17](https://github.com/harvester/harvester/assets/5370752/6238514a-87f9-453b-83b2-742ed120aeae)
![Screenshot from 2023-07-10 11-14-54](https://github.com/harvester/harvester/assets/5370752/657872e2-2948-4329-819c-9b06bb2eed79)
![Screenshot from 2023-07-10 11-14-27](https://github.com/harvester/harvester/assets/5370752/a112101d-ee31-49e0-bad1-0461a65ac491)
![Screenshot from 2023-07-10 11-14-05](https://github.com/harvester/harvester/assets/5370752/b8650aae-1e2a-436a-9a84-1b658b012f1f)
![Screenshot from 2023-07-10 11-10-57](https://github.com/harvester/harvester/assets/5370752/2ebc261b-553d-4f82-a5f2-d1a51c301443)
So I'll go ahead and close this out :+1: :smile:
