### ISSUE TITLE
[Doc] Document how to replace faulty disks

### ISSUE THREAD

**Issue by N0rthg4t3** [harvester/harvester#4115]
**Is your doc request related to a problem? Please describe or add related issue ID.**
No.

**Describe the solution you'd like**
I am currently testing harvester in a 3 node setup. For this, I have been using version 1.1.1 and 1.2.0-rc1.
As for testing this setup, me and my colleagues simulated some common datacenter failure scenarios, like a faulty disk.

Beforehand, I noticed that there does not seem to be a documentation on how to properly replace faulty or ejected disks.
Even if an older and faulty disk can just be replaced by injecting a newer one and formatting it for use with Longhorn, the documentation should mention it at some point, at least to prevent misunderstandings.

We eventually managed to solve this with a combination of cordoning, evicting, wiping and then re-adding a disk but that made me wonder even more if there is a guide on how to properly replace disks. Above all because this is a scenario that - at least from a modern datacenters perspective - should be expected and properly planned for.

Maybe there already is some guide on this and I am missing something.

**Comment by Vicente-Cheng** [comment]
Hi @N0rthg4t3, 
We have the document https://docs.harvesterhci.io/v1.1/host/#remove-disks for removing disks.
Could you try this?

**Comment by N0rthg4t3** [comment]
Hi @Vicente-Cheng ,
thank your for pointing me towards this part of the documentation.
I will test if this procedure is viable for replacing a faulty disk and report back.

**Comment by N0rthg4t3** [comment]
Can be closed since we no longer pursue or evaluate Harvester for our production environment.

For the core of this issue: 
- Removing the disk according to the documentation and re-adding them proved to be viable
- Maybe you should outline in your documentation explicitly how to treat failed disks and what if multiple disks fail
