### ISSUE TITLE
[ENHANCEMENT] Try best to keep grafana PV when rancher-monitoring addon is disabled

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4118]
**Is your enhancement related to a problem? Please describe.**

The user may disable `rancher-monitoring` temporarily and enable it later. The potential customization in Grafana will be lost, as the PVC&PV are removed when addon is disabled.

**Describe the solution you'd like**

Try best to keep grafana PV when rancher-monitoring addon is disabled

**Describe alternatives you've considered**

Add `Caution` in the Harvester doc.

**Additional context**

The effort in upgrade to keep grafana pv:
Issue: https://github.com/harvester/harvester/issues/4071
PR: https://github.com/harvester/harvester/pull/4117

The effort to enhance the `disable` processing of addon, which will be the basis of this issue.
Issue https://github.com/harvester/harvester/issues/4108
PR https://github.com/harvester/harvester/pull/4110

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.2.0-rc3** (upgrade from **v1.1.2**)
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, access embedded Rancher UI
3. Navigate to _Storage/PersistentVolumes_, the PV for PVC `rancher-monitoring-grafana` should be `Reclaim Policy: Retain`
4. In Harvester UI, navigate to _Advanced/Addons_, disable `rancher-monitoring`
5. Addon `rancher-monitoring` should be disabled successfully
6. In Rancher UI, navigate to _Storage/Volumes_, Volume `rancher-monitoring-grafana` should be removed
7. Navigate to _Storage/PersistentVolumes_, the PV with `Reclaim Policy: Retain` should not have PVC
8. In Harvester UI, navigate to _Advanced/Addons_, enable `rancher-monitoring`
9. In Rancher UI, navigate to _Storage/PersistentVolumes_, PVC `rancher-monitoring-grafana` should attached to the PV with `Reclaim Policy: Retain`
10. Access Grafana dashboard from **rancher-monitoring** addon
11. Panels should display normally and contain old data
