### ISSUE TITLE
[BUG][RKE1]VM scheduling enhancement

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#4121]
**Describe the bug**

**To Reproduce**

**Expected behavior**

1.~Add `All namespaces` option for vm scheduling.~
2. Support terraform configurations.
       - https://github.com/harvester/harvester/issues/2317#issuecomment-1589442468

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
@torchiaf Please help look into the state of the issue, I saw some references in the history but not sure if it's already resolved. Thanks.

**Comment by bk201** [comment]
@TachunLin FYI. We are not going to implement this: 
> 2. Support terraform configurations.
> - https://github.com/harvester/harvester/issues/2317#issuecomment-1589442468

All RKE1 features need to be re-prioritized.

**Comment by TachunLin** [comment]
I see, thanks for sharing the information.
