### ISSUE TITLE
[Question] `elemental upgrade` error `invalid upgrade command setup undefined upgrade source`

### ISSUE THREAD

**Issue by gsuess** [harvester/harvester#4126]
I am trying to install cryptsetup and dm-crypt [as described here](https://rancher.github.io/elemental-toolkit/docs/customizing/runtime_persistent_changes/). 

For this I have created a file `/oem/95-luks.yaml`:

```yaml
name: Install LUKS
stages:
  after-upgrade-chroot:
    - commands:
      - zypper in -y cryptsetup dm-crypt
```

And then I tried to run `elemental upgrade`:

```
harvester-1:/oem # elemental upgrade
INFO[2023-06-21T18:00:06Z] Starting elemental version v0.1.0            
ERRO[2023-06-21T18:00:06Z] invalid upgrade command setup undefined upgrade source
```

What does this error mean?

**Comment by Vicente-Cheng** [comment]
hi @gsuess

The error means you need an upgrade source.
You could use the `--directory` for the upgrade source for running system.
or `--system.uri` for system image source.

Or you can find more information on follows page
https://rancher.github.io/elemental-toolkit/docs/getting-started/upgrading/

**Comment by gsuess** [comment]
@Vicente-Cheng what I am missing the meaning of "upgrade-source" here. Is it the zypper repository where the packages are sourced from, or is it referring to a container registry? In what way is a container registry needed?

**Comment by Vicente-Cheng** [comment]
Hi @gsuess, 
IIRC, the upgrade source should be a bootable image like your system.

And for your original question, how to install cryptsetup and dm-crypt
Maybe you could refer to this https://docs.harvesterhci.io/v1.1/troubleshooting/os/#how-can-i-install-packages-why-are-some-paths-read-only

**Comment by gsuess** [comment]
@Vicente-Cheng i saw that however I am looking for less hacky solution. I managed to get dm-crypt module loaded by adding it to the harvester.conf (had to load it during installation, not after and had to use 1.2.0-rc2, didn't work in prior versions).

As for cryptsetup, still no luck.
