### ISSUE TITLE
[BUG] VMs removed a few days ago will still be pushed in

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#413]
**Describe the bug**
Open the VM list page, delete some VMs, don't close them, don't do anything, look at the list page later and sometimes you will see the deleted VMs

![image](https://user-images.githubusercontent.com/24985926/104142859-4637f800-53f8-11eb-8c91-7d0c829ba556.png)

![image](https://user-images.githubusercontent.com/24985926/104142863-4e903300-53f8-11eb-8937-054efc2a3daa.png)

May be to re-subscribe to the cause of problems

**Comment by futuretea** [comment]
Can't reproduce now, will follow up if there is any update

**Comment by futuretea** [comment]
May be an issue on k3s version v.1.20+
link to #446

**Comment by WuJun2016** [comment]
**To Reproduce**
1. create new vm
2. delete vm
3. Disconnect the network
4. Waiting for websock to disconnect  (Console will print (socket closed))
5. Reconnecting the network

**Comment by TangStone** [comment]
**Validation Version**
- master-85a12ff7-head

**Steps**
https://github.com/rancher/harvester/issues/413#issuecomment-794735413

**Result**

- Can't reproduce
