### ISSUE TITLE
[BUG] VM keep FailedCreate if using a Preferred node scheduling rule

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#4136]
**Describe the bug**

![image](https://github.com/harvester/harvester/assets/15064560/5c9938b8-5db3-4979-82b1-832c0fda8ed4)

**To Reproduce**
1. Create a VM with a Preferred node scheduling rule
![image](https://github.com/harvester/harvester/assets/15064560/e6227b6e-91b0-4bd9-aee4-51ec9af8c603)

**Expected behavior**

VM will become Running

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
Tested on Harvester Version: v1.2-e4aa22c3-head.

Node Scheduling with Preferred & Required of a VM looks good :smile: :+1: 
![Screenshot from 2023-06-28 16-44-14](https://github.com/harvester/harvester/assets/5370752/f51d3360-7c15-4b84-9d5d-c5800297fea7)
![Screenshot from 2023-06-28 16-43-52](https://github.com/harvester/harvester/assets/5370752/5354de55-fc41-4bc1-add8-0925c037f16a)
![Screenshot from 2023-06-28 16-39-49](https://github.com/harvester/harvester/assets/5370752/119200ea-24d4-424d-83d5-f559496294ca)
![Screenshot from 2023-06-28 16-39-30](https://github.com/harvester/harvester/assets/5370752/fd93556c-d6df-459d-95b8-f7b30245ef60)

I'll go ahead and close this out - thanks for the fix @futuretea :smile: :+1: :raised_hands:
