### ISSUE TITLE
[ENHANCEMENT] Speed up replica rebuild during upgrade

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4144]
**Is your enhancement related to a problem? Please describe.**

To speed up replica rebuild after an upgrading node is rebooted.

**Describe the solution you'd like**

- Enable fast replica rebuild: https://longhorn.io/docs/1.4.2/references/settings/#fast-replica-rebuild-enabled
- Manually take volume snapshots before offline a node. (capture from @yasker ) If we have a manual snapshot before cutting off a node, whatever data on the volume-head will be in the snapshot, so volume-head can be kept as small as possible. otherwise, you might have a gigabytes of data in the volume-head that needs to be rebuilt on the disconnected node

**Describe alternatives you've considered**

**Additional context**

**Comment by WebberHuang1118** [comment]
LH setting [Fast Replica Rebuild](https://longhorn.io/docs/1.7.0/references/settings/#fast-replica-rebuild-enabled) depends on setting [snapshot data integrity](https://longhorn.io/docs/1.7.0/references/settings/#snapshot-data-integrity)

Function details:
-  Snapshot data integrity:
   - https://github.com/longhorn/longhorn/blob/master/enhancements/20220922-snapshot-checksum-and-bit-rot-detection.md
- Fast Replica Rebuild:
  - https://github.com/longhorn/longhorn/issues/4783

On LH v1.7.0, the above default settings are:
- `snapshot-data-integrity` is `fast-check` by default https://github.com/longhorn/longhorn-manager/blob/38a74bb562208d4617d80f2cc9898b4b4fbcbe63/types/setting.go#L1178-L1195
- `fast-replica-rebuild-enabled` is `true` by default https://github.com/longhorn/longhorn-manager/blob/38a74bb562208d4617d80f2cc9898b4b4fbcbe63/types/setting.go#L1240-L1248

**Comment by WebberHuang1118** [comment]
Conducting the following testing plan to verify `fast-replica-rebuild` on Harvester master-head (commit `c5d790422fbf02fecbd7401113183cdf95bc8cfc`)
- Settings
  - `snapshot-data-integrity` to `fast-check` (by default)
  - `snapshot-data-integrity-immediate-check-after-snapshot-creation` to `true`
  - `fast-replica-rebuild-enabled` to `true` (by default)
- Creating a volume with 2 replicas
- Creating a VM with the volume
- Creating multiple VM snapshots
- Powering off the node which the running VM is not attached to
- Waiting a few minutes, and powering on the node
- The replica will be rebuilt, Only the latest snapshot disk file will be synchronized. Others will be skipped.

The `fast-replica-rebuild` is enabled and works as expected on Harvester.
