### ISSUE TITLE
[BUG] Checkbox "Booting in EFI mode" is not working correctly with Terraform Harvester Provider

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4145]
### Describe the bug
The VM created from Terraform Harvester Provider with
```tf
resource "harvester_virtualmachine" "The_VM" {
  # ...
  efi = true
  secure_boot = false
  # ...
``` 

![image](https://github.com/harvester/harvester/assets/5169694/7fa3be9d-c439-4eb7-95a8-09bf8a1e5c1e)

### To Reproduce
1. Install Harvester with any nodes
2. Create VM `vm1` from Terraform Harvester Provider with configure `efi=true` and `secure_boot = false`
3. Edit `vm1` on dashboard, In **Advanced Options**, checkbox `Booting in EFI mode` should be checked

### Expected behavior
UI checkbox Booting in EFI mode should be checked, regardless of whether SMM is explicitly disabled

## Environment:
 - Harvester ISO version: **v1.2.0-rc2**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 2 nodes**
 - **Harvester Terraform Provider** Version: **v0.6.2**

### Additional context
regression

**Comment by albinsun** [comment]
Tested in `master-226cc36e-head`, verified as fixed.

## Test Environment
* Harvester
  * version: `master-226cc36e-head`
  * profile: qemu/KVM, single node
  * **ui-source**: Auto
* terraform-provider-harvester
  * version: `v0.6.2`

## Verification
1. Create VM via terraform script $~~~~$ $\color{green}{\textsf{PASSED}}$
   ```
   resource "harvester_image" "ubuntu" {
       name      = "ubuntu"
       namespace = "harvester-public"
       display_name = "focal-server"
       source_type  = "download"
       url          = "http://172.17.0.1:8080/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img"
   }

   resource "harvester_network" "vlan1" {
       name      = "vlan1"
       namespace = "harvester-public"
       vlan_id = 1
       route_mode           = "auto"
       route_dhcp_server_ip = ""
       cluster_network_name = "mgmt"
   }

   resource "harvester_virtualmachine" "ubuntu" {
     count = 1
     name                 = "ubuntu"
     namespace            = "harvester-public"
     restart_after_update = true
     efi = true
     secure_boot = false

     description = "test ubuntu"
     tags = {
       ssh-user = "ubuntu"
     }

     cpu    = 1
     memory = "1Gi"

     run_strategy = "RerunOnFailure"
     hostname     = "ubuntu"
     machine_type = "q35"

     network_interface {
       name           = "nic-1"
       network_name = harvester_network.vlan1.id
     }

     disk {
       name       = "rootdisk"
       type       = "disk"
       size       = "10Gi"
       bus        = "virtio"
       boot_order = 1

       image       = harvester_image.ubuntu.id
       auto_delete = true
     }
   }
   ```

2. "Booting in EFI mode" should be checked $~~~~$ $\color{green}{\textsf{PASSED}}$
    * GUI (Virtual Machines -> <VM> -> Config -> Advanced Options)
       ![efi_true](https://github.com/harvester/harvester/assets/2773781/91ea0263-ba05-4b46-b921-44bcd06b588f)
     * YAML compare to VM w/o `efi: true`
        ![yaml-diff](https://github.com/harvester/harvester/assets/2773781/71c9f7f1-2017-4297-bc51-1d38b07e9769)
  
## Note
1.  Can reproduce in `1.2.0-rc2`
      ![without_any](https://github.com/harvester/harvester/assets/2773781/94656711-7b2b-4c54-81fd-665eca50fbed)

**Comment by lanfon72** [comment]
@albinsun as the milestone is v1.2.0, we should verify it with v1.2-head

**Comment by albinsun** [comment]
## Update
Also tested in `v1.2-db0f79d4-head`

"Booting in EFI mode" should be checked $~~~~$ $\color{green}{\textsf{PASSED}}$
* GUI (Virtual Machines -> -> Config -> Advanced Options)
  ![efi_true-12head](https://github.com/harvester/harvester/assets/2773781/11071ae6-3555-4ed5-be62-a2a347784461)
* YAML
  ![efi_true_yaml-12head](https://github.com/harvester/harvester/assets/2773781/7d8dd8a5-cbcb-4f75-bf2d-e4c4d6ae5d40)
