### ISSUE TITLE
[Question] Single node Setup

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4159]
hey everyone
I have a few three node clusters running perfectly fine since some time.
Now I wanted to migrate everything to harvester to have the same workflow everywhere.
Is it possible to change some settings to make it also operateable as a single node?

**Comment by Martin-Weiss** [comment]
Not sure if I understand your question - but AFAIK harvester can be deployed as a single node..

**Comment by ne0YT** [comment]
> Not sure if I understand your question - but AFAIK harvester can be deployed as a single node..

I thought the same.
but my 3 node clusters all run perfectly well.. but this one node I setup always has "insufficient storage" (It has more than 8TB available) but 3 is to much to allocate and working volumes (2* smaller than 50gb) are degraded

**Comment by w13915984028** [comment]
For single-node cluster, it is necessary to create a StorageClass https://docs.harvesterhci.io/dev/advanced/storageclass to set replica to 1, and set it as default. Otherwise, the default 3 replicas will cause Longhorn always try and complain about more replicas.

You may further optimize per following PR, to lower the default reserved CPU by Longhorn in single-node cluster.
https://github.com/harvester/docs/pull/301

The coming Harvester v1.2.0 will have more enhancements for single-node cluster.

**Comment by ne0YT** [comment]
thanks, works perfectly well :)

**Comment by ne0YT** [comment]
@w13915984028 
hey there
did somethign change now with the latest versions?

**Comment by connorkuehl** [comment]
> @w13915984028 hey there did somethign change now with the latest versions?

Are you running into some kind of single-node issue with the latest version? Or are you just asking what's changed. In case of the latter:

The latest version of Harvester does "slim" down the runtime footprint by moving things like monitoring/logging into its own addon and leaving it disabled by default (unless your node upgraded to one of these versions and it'll just leave it enabled iirc). There are probably other substantive things that I'm just not recalling off the top of my head :sweat_smile:

**Comment by ne0YT** [comment]
@w13915984028 cool :)
yes that was the question. 
Do I still need to make manual changes?

**Comment by connorkuehl** [comment]
> @w13915984028 cool :) yes that was the question. Do I still need to make manual changes?

Yeah, Jian's suggestions in this comment[1] would still need to be done manually. AFAIK, there's no automation in Harvester that automatically optimizes those for single node.

[1] https://github.com/harvester/harvester/issues/4159#issuecomment-1618105925
