### ISSUE TITLE
[BUG] when switching users in rancher and opening Harvester you get an error

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4162]
**Describe the bug**

When you log out of Rancher and log in as another user and open Harvester you get an error on dashboard load
**To Reproduce**
1. Create  a restricted admin user in Rancher
2. Import Harvester into Rancher
3. Open up Harvester as admin
4. Verify it opens
5. Log out of rancher
6. Log on as restricted admin
7. Try to open Harvester dashboard again

**Expected behavior**

**Support bundle**

[supportbundle_28fde15c-4b22-4193-b531-9f400d14fb46_2023-06-30T19-38-46Z.zip](https://github.com/harvester/harvester/files/11922804/supportbundle_28fde15c-4b22-4193-b531-9f400d14fb46_2023-06-30T19-38-46Z.zip)

**Environment**
 - Harvester ISO version: master-20ca0b3e-head
 - Rancher version: v2.7.5 single node docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node libvirt VMs

**Additional context**
If you refresh the page after logging back in as a different user it will load fine, and  if you get the error and then refresh and navigate to it again you don't get the error. Error is `r["".concat(...)] is not a function`

![Screenshot_20230630_131047](https://github.com/harvester/harvester/assets/83787952/f45c9a4d-ebba-4d87-a7ba-94a6ac197eff)
![Screenshot_20230630_131038](https://github.com/harvester/harvester/assets/83787952/0b37f63b-52f3-4915-bddb-f6cd64b42747)

**Comment by WuJun2016** [comment]
It could be the same issue:  https://github.com/harvester/harvester/issues/3895

**Comment by WuJun2016** [comment]
https://github.com/rancher/dashboard/pull/8890

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.9`
  * Profile: Docker8 (1C/4G)


## Test Steps
1. <details>
      <summary> On Rancher, create a restricted admin
      </summary>

      Go to **Users & Authentication** -> **Create**
      ![image](https://github.com/harvester/harvester/assets/2773781/ff2a5265-e06c-40ae-978c-04015de8a97b)
      ![image](https://github.com/harvester/harvester/assets/2773781/1f89a3e1-f160-44b0-87f2-4b88dafd5585)
   </details>


1. <details>
      <summary> Import Harvester into Rancher
      </summary>
   
      Go to **Virtualization Management** -> **Import Extsting**
      ![image](https://github.com/harvester/harvester/assets/2773781/f6b94ce9-6891-4b85-bdf9-6b6613934c1c)
      **harvester131** is `Active`
      ![image](https://github.com/harvester/harvester/assets/2773781/9efb8a48-7093-4bd3-aba1-43d4e80fa1e9)
   </details>


1. <details>
      <summary> Open up Harvester as admin
      </summary>
   
      ![image](https://github.com/harvester/harvester/assets/2773781/a757d263-3aaa-4ed4-b264-5d292d2ceb69)
      ![image](https://github.com/harvester/harvester/assets/2773781/65efbae1-24be-47dc-91d0-41402c2db7be)
   </details>


1. <details>
      <summary> Log out of rancher and Log on as restricted admin
      </summary>

      Logout **admin**
      ![image](https://github.com/harvester/harvester/assets/2773781/ac7f1ee6-d896-41aa-a51e-0fd34301ec61)
      Loging as restricted admin **radmin**
      ![image](https://github.com/harvester/harvester/assets/2773781/5e27f5a1-e051-431e-a7c5-5804f5904b63)
   </details>


1. <details open>
      <summary> open Harvester dashboard again :ballot_box_with_check: 
      </summary>
   
      ![image](https://github.com/harvester/harvester/assets/2773781/6cbfd21e-e72b-4c9b-a0cf-bb8bd1f6f4d1)
   </details>


## Note
1. Can reproduce in `harvester-v1.1.2` + `rancher-v2.7.5`
   ![image](https://github.com/harvester/harvester/assets/2773781/4c930c60-fa06-45fe-aa00-0d1a4f52ed5e)
