### ISSUE TITLE
[Enhancement] double check if klipper-helm image is included in Harvester

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4176]
**Describe the bug**

When enable/diable addon, both `helm-install-` and `helm-delete-` are using image `rancher/klipper-helm:v0.7.6-build20230223`, please check if it it included in Harvester ISO

And, how to track the bump of `helm-controller`.

```
Controlled By:  Job/helm-delete-rancher-monitoring
Containers:
  helm:
    Container ID:  containerd://48f3f41a8f74781c79818685b156a26e4d388472e608ad64922db6805bf38861
    Image:         rancher/klipper-helm:v0.7.6-build20230223
```

From rancher-images.txt, https://github.com/harvester/harvester-installer/pull/518/files#diff-08a2aea3ce711fa199b168518cdea1b9b77d7bdd47ba4c1174a0edf65473ab5e, it seems not.

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.2.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Observed when debugging https://github.com/harvester/harvester/pull/4127

**Comment by guangbochen** [comment]
The `kilpper-helm` should already be packaged via the https://github.com/harvester/harvester-installer/blob/master/scripts/build-bundle#L137; please take an investigation of whether it has encountered image GC like https://github.com/harvester/harvester/issues/4210

**Comment by chrisho** [comment]
@w13915984028 Could you replenish the reproduction steps? I tried on the airgap cluster but it cannot reproduce.

**Comment by w13915984028** [comment]
After a successful ISO building, there should be some kind of container image list txt files to check if image is there/or not. But when I searched those text files under Harvester installer, the `klipper-helm` was not found. Seems we did not save the `rke2-images.linux-amd64.txt`  file under https://github.com/harvester/harvester-installer/tree/master/scripts/images, and also not under build output.

Ideally, we need to have a single txt file to list all container images in the Harvester ISO, and publish it to path like https://github.com/harvester/harvester/releases/tag/v1.2.0-rc4, it will be much helpful.

**Comment by w13915984028** [comment]
checked the image is in file:

dist/artifacts/image-lists/rke2-images.linux-amd64-v1.25.9-rke2r1.txt ( extracted from dist/artifacts/image-lists.tar.gz )

```
docker.io/rancher/klipper-helm:v0.7.6-build20230223
```

**Comment by w13915984028** [comment]
I added a PR https://github.com/harvester/harvester-installer/pull/558 to generate a single text file, which collects all container images.

**Comment by w13915984028** [comment]
Finished.
