### ISSUE TITLE
[BUG] Project member can't see any volumes

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4178]
### Describe the bug
https://github.com/harvester/harvester/assets/5169694/da8a9e3b-cd0c-4cd8-83fd-e3f237080a32

### To Reproduce
1. Install Harvester with any nodes
2. Install Rancher, create **Standard User** `pm1`
3. Import Harvester into Rancher
4. Access Harvester via Rancher's _Virtualization Management_
5. Create a project `proj-a`, add user `pm1` as member
6. Create a namespace `ns1` to `proj-a`
7. Login Rancher by the user `pm1` then access Harvester
8. Create a volume `v1`, `v1` should created and visible in the Volumes page

### Expected behavior
Project member should able to view volumes belongs to it's project

## Environment:
 - Harvester ISO version: **v1.1-d6ecf288-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 2 nodes**
 - Rancher Version:
     - **v2.6-96f5ed3c4faefa8580ab9a5ceae204c74c058f86-head**, Docker Image: **sha256:dd76cf25fbadcce647af14c40845f3a0b16ef54685c5a2650c8322bd1b4b9ace**
     - **v2.7-c402790306de21f88a0a5bcb7ca3a2f69ba12ba6-head**, Docker Image: **sha256:2a8a8a29e779dbbca58025b7338378139331a6d3762cbcfd3bcfb0bde51d3b88**

### Additional context
Discovered when testing #3907

**Comment by WuJun2016** [comment]
duplicate  with: https://github.com/harvester/harvester/issues/3874

**Comment by lanfon72** [comment]
@WuJun2016, #3874 been moved to ready for testing, so this bug been fixed?

**Comment by lanfon72** [comment]
close as duplicated.

**Comment by WuJun2016** [comment]
> @WuJun2016, #3874 been moved to ready for testing, so this bug been fixed?

Yes
