### ISSUE TITLE
[BUG] Unable to assign CPU or Memory to a new VM when using up/down arrows.

### ISSUE THREAD

**Issue by coltho02** [harvester/harvester#4179]
**Describe the bug**

Unable to create a VM in Harvester when using the up/down arrows to select CPU/Memory. The error ' "CPU" is required" or '"Memory" is required'. 

When you go back to the Basics tab, both fields are usually empty. To overcome this, the entry must be made using a keyboard. 
 
**To Reproduce**

1. Create a new VM in Harvester
2. In the Basics tab, use the up/down arrows to select the number of CPU and Memory. 
3. Continue the rest of the VM setup
4. Click Create

**Expected behavior**

We would expect the up/down arrows to function in an identical manner as entering a value using the keyboard. 

**Environment**
 - Harvester v1.1.1
 - Rancher v2.6.9

**Comment by coltho02** [comment]
![Harvester-github](https://github.com/harvester/harvester/assets/54437706/76236a9d-2d80-4884-901e-e90b6f06b479)

**Comment by WuJun2016** [comment]
Hi, @coltho02  I was not able to reproduce this problem in `v1.1.1` can you provide more information or help me to see if this problem can be reproduced stably by following your steps, thanks

https://github.com/harvester/harvester/assets/24985926/e30cb3cd-fd43-4f81-be90-2305a8200b39

**Comment by coltho02** [comment]
I've just tested directly on Harvester, not through Rancher and I get the same issue. 

What information would you like me to provide that could help you?

**Comment by abonillabeeche** [comment]
I cannot reproduce on 1.1.2 with Chrome Version 114.0.5735.133 (Official Build) (x86_64)

**Comment by WuJun2016** [comment]
I also tested directly on harvester, and it did not reproduce. 
Need to provide the `support bundle` file
![image](https://github.com/harvester/harvester/assets/24985926/7da15614-086c-4ce5-9bf2-d4724c3388a8)

**Comment by coltho02** [comment]
Is there a way i can get the support bundle to you? It was over the 25mb limit.

**Comment by WuJun2016** [comment]
@coltho02  You can provide me with information about the following configurations in the setting.
![image](https://github.com/harvester/harvester/assets/24985926/782a4a2e-90a0-4b0a-b271-056b869d1aba)

**Comment by coltho02** [comment]
![Harvester-bug](https://github.com/harvester/harvester/assets/54437706/0cf7e750-8a5b-4ea8-8105-24223c435963)

Please let me know if you need anything else

**Comment by WuJun2016** [comment]
hi @coltho02 , We haven't been able to reproduce the problem so far based on the information you provided (and tested in different browsers).     We will continue to troubleshoot the issue if we have additional information.

**Comment by coltho02** [comment]
@WuJun2016 , Thanks for looking into this. If it would be easier we can jump on a call and have a dig about?

**Comment by WuJun2016** [comment]
> @WuJun2016 , Thanks for looking into this. If it would be easier we can jump on a call and have a dig about?

ok

**Comment by coltho02** [comment]
Thanks for your time @WuJun2016 . 

To confirm what we discussed on the call, this issue should be resolved in a future release.

**Comment by WuJun2016** [comment]
The issue can be reproduced in the `Firefox` browser,  there are no problems in Chrome and Safari.

**Comment by mortenn** [comment]
I just tried increasing the memory of a VM, but it didn't actually get changed when I used the arrows.
it told me I had to restart and gave me options save and restart and save.
I did restart and save, but memory remained the original value.
tried again while the server was off and hit save, it remained at the original value.
I typed in the new value on my keyboard and hit save, and it got changed successfully.

**Comment by torchiaf** [comment]
Reopening as requires tests.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20240105` with **ui-source** `External`, close as fixed.

Hi @bk201, please help to include this fix into next sprint build to have it in `Auto` **ui-index**, thank you.

## Environment
* Harvester
  * Version: `v1.3.0-dev-20240105`
  * Profile: QEMU/KVM, single node (8C/32G/500G)
  * ui-source: `Auto` and `External`


## Test Cases
1. Chrome `120.0.6099.199`
   <details>
 
     https://github.com/harvester/harvester/assets/2773781/fa0bcc05-318c-4158-86b8-b07d9a8faba3
   </details>

   * **ui-index** `Auto` should works :ballot_box_with_check: 
   * **ui-index** `External` should works :ballot_box_with_check: 
   
1. Firefox `115.6.0esr`
   <details>
 
     https://github.com/harvester/harvester/assets/2773781/c7c9705a-134b-403c-8f36-e8c013d11067
   </details>

   * **ui-index** `Auto` should NOT work (yet) :ballot_box_with_check: 
   * **ui-index** `External` should work :ballot_box_with_check:
