### ISSUE TITLE
[BUG] Failed to create image from uploading file, prompt "Dial tcp 10.53.159.208:9500: i/o timeout"

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4182]
**Describe the bug**

When we try to upload a file to create the image, it would stuck then failed with error message
`Dial tcp 10.53.159.208:9500: i/o timeout`

![image](https://github.com/harvester/harvester/assets/29251855/435e0e0d-5167-4fd4-8151-553715f1278e)

https://github.com/harvester/harvester/assets/29251855/d7d57c75-fd0a-4b5a-8439-36b5346b2fe3

**To Reproduce**
1. Create image
2. Upload and select file 
3. Check the image state

**Expected behavior**

Should be able to create image from uploading file correctly. 

**Support bundle**

[supportbundle_b987380e-ab22-4683-9846-de2f1de55352_2023-07-05T08-36-52Z.zip](https://github.com/harvester/harvester/files/11955774/supportbundle_b987380e-ab22-4683-9846-de2f1de55352_2023-07-05T08-36-52Z.zip)

**Environment**
 - Harvester ISO version: `v1.2-4d7b1196-head` (07/05)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single node on local kvm machine

**Additional context**
Create image from url works in comparison to upload by file
![image](https://github.com/harvester/harvester/assets/29251855/b1c95b02-f3f5-435b-8553-319df226b6f3)

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc3`, close as fixed.

## Test Environment
* Harvester
  * version: `v1.2.0-rc3`
  * profile: QEMU/KVM, 3 nodes (8C/16G/250G)
  * **ui-source**: Auto
* Browser: Firefox `102.12.0esr`

## Verification
1. Go to 'Images -> Create'
2. Create via file upload (qcow2, 563MB) $~~$ :heavy_check_mark:
3. Create via file upload (ISO, 4.3GB) $~~$ :heavy_check_mark:
4. Create via file upload (ISO, 70GB) $~~$ :heavy_check_mark: 

![image](https://github.com/harvester/harvester/assets/2773781/a9aa18aa-cb8d-4da8-b6ba-5889795862f6)

## Note
1. Create via URL also tested ok.
2. Big ISO is a regression for [harvester#3450](https://github.com/harvester/harvester/issues/3450)
