### ISSUE TITLE
[BUG] State of Storage Class doesn't update when Disk(s) that represent disk selector are removed from nodes

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4186]
**Describe the bug**
State of "Active" on a custom storage class never changes, when there are no disks that match host & disk selector combination.

**To Reproduce**
1. Go to add disk to node
1. Tag disk and host on node
1. Create custom storage class
1. Wait for storage class to become active
1. Remove disk from node
1. Run `lsblk` on node to double verify - ensure not mounted 
1. Check Custom Storage Class state, will show "Active"

**Expected behavior**
Long polling/receiving a message from the host, like listening to `ds/harvester-node-disk-manager` when:
```
time="2023-07-05T21:23:22Z" level=info msg="Prepare to stop provisioning device 989754e4e66edadfd3390974a1aba3f8 to node harvester-node-0"
time="2023-07-05T21:23:22Z" level=info msg="Update existing block device status 989754e4e66edadfd3390974a1aba3f8"
```
Takes place, audit all existing "Active" storage classes, and update state of storage class to shift from Active -> InActive?

Maybe it would change from "Active" to "Not Ready", like Volumes do, if for instance:
1. Create custom storage class
1. Remove disk that matches disk selector
1. Create Volume, the volume will stick in "Not Ready" - but the State of the Storage class always stays in "Active"

**Environment**
 - Harvester ISO version: v1.2-head ->  Harvester Version: v1.2-7a8ac2c2-head 
 - Underlying Infrastructure: qemu/kvm

**Comment by Vicente-Cheng** [comment]
Hi @irishgordo.
StorageClass should not have any status; it is more like the volume description.
You could refer to https://kubernetes.io/docs/concepts/storage/storage-classes/

The UI status depends on our framework (maybe `wrangler`, not sure).

The situation you mentioned might be another point we need to consider to remind users, we could discuss how to do it.
cc @guangbochen, @bk201

**Comment by bk201** [comment]
@irishgordo We have some offline discussion; here is a summary:
- The active state means nothing; it doesn't represent whether we can create a volume with it. It's pure Kubernetes design.
- @Vicente-Cheng will help add a doc to address this limitation. One suggestion is on the storage class page (https://docs.harvesterhci.io/dev/advanced/storageclass).

We might need storage-specific support (from Longhorn) and custom APIs to achieve what the issue description wants. Please help create another enhancement ticket to track it. Thank you.

**Comment by irishgordo** [comment]
@bk201  @Vicente-Cheng  thanks for that info :smile:  - I'll go ahead and close this out and I've opened up:
https://github.com/harvester/harvester/issues/4320
To track that enhancement :+1: :smile:
