### ISSUE TITLE
[FEATURE] Submit harvester/dashboard dependency code to upstream branch

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4188]
**Is your feature request related to a problem? Please describe.**

In harvester v1.3.0, we will switch to the `@rancher/shell` provided by the rancher/dashboard， 
So we need to commit the dependencies in harvester/dashboard/shell to the upstream branch。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by torchiaf** [comment]
This should be evaluated as part of architectural enhancements / Vue3 Migration.

**Comment by a110605** [comment]
Done in https://github.com/rancher/dashboard/issues/12347 which already commited harvester dashboard shell to rancher shell.

And [harvester-ui-extension](https://github.com/harvester/harvester-ui-extension/blob/59aec78631325b60160038534869597375ff6e7a/package.json#L9) is already using @rancher/shell as dependency.
