### ISSUE TITLE
[FEATURE] Use @rancher/shell in the harvester/dashboard repo

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4189]
**Is your feature request related to a problem? Please describe.**

In harvester v1.3.0, we will switch to the `@rancher/shell` provided by the rancher/dashboard，

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by a110605** [comment]
This issue is not required at this moment as we are working on harvester/dashboard migration to [harvester-ui-extension](https://github.com/harvester/harvester-ui-extension) which uses @rancher/shell as core library.
cc @torchiaf , @bk201
