### ISSUE TITLE
[FEATURE] Add harvester cluster monitoring dashboard

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#419]
**Is your feature request related to a problem? Please describe.**

Add harvester cluster monitoring dashboard

**Describe the solution you'd like**

1. allow the user to enable and deploy Harvester cluster monitoring with Prometheus integration
1. add Harvester cluster monitoring dashboard includes CPU, memory, disk, network I/O, etc

**Comment by wjimenez5271** [comment]
Would it be possible to build this in such a way that one dashboard could show status of the VMs across more than 1 cluster? I.e. not limit it to just one cluster view?

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/576
