### ISSUE TITLE
[ENHANCEMENT] sort by "IP Address"

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4197]
**Is your enhancement related to a problem? Please describe.**
You can sort by everything but IP-Address.
It would be great to allow to sort by IP too

**Describe the solution you'd like**
Adding sorting to the IP-Address field.

**Comment by irishgordo** [comment]
@torchiaf  -thanks for this enhancement :smile: :+1:  - this looks great on Harvester Version: v1.4.0-dev-20240705 


https://github.com/harvester/harvester/assets/5370752/a7200a20-6539-4f32-b0ed-eea1c14f3b5b



https://github.com/harvester/harvester/assets/5370752/e83fe377-db44-4a8c-9536-66ac1fa3993f



I'll go ahead and close this out :smile:
