### ISSUE TITLE
UI design

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#42]
few harvester-UI designs and feature changes:
1. [x] vm delete logo
1. [x] vm adjust the location of the namespace
1. [x] networking todo
1. [x] rootdisk can get source: image ，size： imageSize
1. [x] vm add ssh key default select
1. [x] start vm default true
1. [x] template delete namespace (set default namespace)
1. [x] ssh key add a search input
1. [x] ssh key name set the default name
1. [x] vm template option is hidden by default (rancher rke)
1. [x] ssh key The content disappears after input
1. [x] image action launch 
1. [x] add disk spell error
1. [x] template describe position adjustment
1. [x] select all position
1. [x] storageclass need to get the first default through API, it cannot be written to hostpath

**Comment by brandboat** [comment]
gentle ping @votdev , why do we reopen this issue ?

**Comment by votdev** [comment]
I'm closing the issue again as it has somehow been reopened accidentally and unintentionally.
