### ISSUE TITLE
[BUG] Image label "easy bulk entry" seems not work

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4206]
**Describe the bug**
In Images -> Create -> Labels, follow the tooltip `Paste lines of key=value or key: value into any key field for easy bulk entry` and try to paste key=value lines, but not convert to lables automatically.
![image](https://github.com/harvester/harvester/assets/2773781/07cc0cb6-f955-4d63-bf05-2f72e5daec6d)

**To Reproduce**
1. Go to 'Images -> Create'
2. In Basics, enter image URL, image Name is filled automatically.
   <details>

   ![image](https://github.com/harvester/harvester/assets/2773781/ee35f4fd-740c-4c58-8ac5-c3098270029f)
   </details>
   
4. In Labels, enter custom key=value lines, but not convert to labels.
   * Content
     ```
     user-firstname=John
     user-lastname=Doe
     user-id=123
     ```
   * lines does not convert to lables
     ![image](https://github.com/harvester/harvester/assets/2773781/2d70e13f-abfe-4d1e-88a1-e83a5d69e9d0)

**Expected behavior**
lines should be convert to lables like:
  | Key | Value |
  | --- | ----- |
  | user-firstname | John |
  | user-lastname | Doe |
  | user-id | 123 |

**Support bundle**
[supportbundle-easy_bulk_entry_labels.zip](https://github.com/harvester/harvester/files/11994568/supportbundle-easy_bulk_entry_labels.zip)

**Environment**
 - Harvester ISO version: `v1.2.0-rc3`
 - Underlying Infrastructure: QEMU/KVM, 3 nodes (8cores/16GB/250G)

**Additional context**
1. Reference: https://docs.harvesterhci.io/v1.1/upload-image#image-labels
1. No explicit error in dev tool
  ![image](https://github.com/harvester/harvester/assets/2773781/8685f4fa-cc00-435d-bf32-985309dcd737)

**Comment by a110605** [comment]
Same issue also happened in pages
-  Virtual Machine -> Create
- Network -> Load Balancer -> Create 
![label-instance](https://github.com/harvester/harvester/assets/5744158/3f58426a-6612-4fb3-a937-eb3d0f6f73a0)
 
There is logic bug during parsing the separator. ([code](https://github.com/a110605/dashboard/blob/bbc89cc7da51a98d216e96390bf2babfe30a0c02/shell/components/form/KeyValue.vue#L498-L502))

Since the code is from rancher shell, same issue happened on rancher dashboard.

**Comment by irishgordo** [comment]
@a110605 this looks good on Harvester  Version: master-9c0a3a1-head  :+1:  :smile: 
I'll go ahead and close it out

https://github.com/harvester/harvester/assets/5370752/e436737b-5b6e-408a-963a-435d152cd4d8
