### ISSUE TITLE
[ENHANCEMENT] Upgrade: speed up image preloading time and space utilization

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4208]
**Is your enhancement related to a problem? Please describe.**

There are some optimizations we can do in the prepare script.

**Describe the solution you'd like**

- Chain commands with pipes, this reduces the image loading time and eliminates temporary space requirement.
- Do not unpack the image in containerd.

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
@bk201  this looks good :smile: :+1:  - I'll go ahead and close this out.

**Test-Results:**

**v1.1.2->master-head: PASS**
Artifacts:
![Screenshot from 2023-07-13 15-16-02](https://github.com/harvester/harvester/assets/5370752/aa0aeed3-d913-40f2-88b6-9016792bc915)
![Screenshot from 2023-07-13 12-13-10](https://github.com/harvester/harvester/assets/5370752/57bb1d22-01e1-43d6-a993-81f8913514d9)

**v1.1.2->v1.1-head: PASS**
Artifacts:
![Screenshot from 2023-07-13 16-18-33](https://github.com/harvester/harvester/assets/5370752/e3da4a76-85bc-4c29-8c39-f55d5bace811)
![Screenshot from 2023-07-13 15-54-33](https://github.com/harvester/harvester/assets/5370752/937b6609-14de-4439-88a4-f884c561c1b6)

**v1.1.2->v1.2-head: PASS**
Artifacts:
![Screenshot from 2023-07-13 17-16-26](https://github.com/harvester/harvester/assets/5370752/1d9d672d-f435-4534-bd78-bf172c7e71e1)
![Screenshot from 2023-07-13 16-38-20](https://github.com/harvester/harvester/assets/5370752/6d2e8501-9077-4780-84ec-b07af507e18d)
