### ISSUE TITLE
[DOC/ENHANCEMENT] Improve the upgrade behavior for small disk

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4210]
**Is your enhancement related to a problem? Please describe.**
When upgrading from v1.1.2 to v1.2.0-rc3. We found that GC (Garbage Collection) occurs, and some images be removed.
That will cause the upgrade to get stuck due to lacking specific images.

**Describe the solution you'd like**
We may improve the upgrade behavior to make the upgrade smooth.

**Describe alternatives you've considered**

**Additional context**
Workaround: Import the specific images we needed

Also, giving the usage for root partition usage:
```
Filesystem      Size  Used Avail Use% Mounted on
/dev/vda5        59G   53G  3.8G  94% /usr/local
```

Detailed partition table as below:
```
vda    253:0    0   250G  0 disk
├─vda1 253:1    0     1M  0 part
├─vda2 253:2    0    50M  0 part /oem
├─vda3 253:3    0     8G  0 part
├─vda4 253:4    0    15G  0 part /run/initramfs/cos-state
├─vda5 253:5    0    60G  0 part /var/lib/longhorn
│                                /var/crash
│                                /var/lib/cni
│                                /var/lib/wicked
│                                /var/lib/kubelet
│                                /var/lib/rancher
│                                /var/log
│                                /usr/libexec
│                                /root
│                                /opt
│                                /home
│                                /etc/pki/trust/anchors
│                                /etc/cni
│                                /etc/iscsi
│                                /etc/ssh
│                                /etc/rancher
│                                /etc/systemd
│                                /usr/local
└─vda6 253:6    0 166.9G  0 part /var/lib/harvester/defaultdisk
```

**Comment by guangbochen** [comment]
Below are the options that we may consider to add:
- ~~clean up purge images via SUC plan.（could prune rancher/harvester-upgrade:<previous-version> image, suitable for non-airgapped env)~~
- use https://github.com/harvester/harvester/issues/2132#issuecomment-1534347958 to clean up the legacy images manually.
- (not preferred option) Increase the kubelet's image garbage collection threshold(image-gc-high-threshold) to higher percentage(e.g., 90%)
- (to verify) erase the LH partition and add it as part of the persistence partition (requires migrating LH data first and manual operation). - may use KB if possible.

**Comment by guangbochen** [comment]
Moving the issue to v1.2.1 for further tracking. In Harvester v1.2.0, it has already:
- added a [script](https://github.com/harvester/upgrade-helpers/blob/main/bin/harv-purge-images.sh) that can help to clean up legacy images manually before the upgrade.
- added free space check on the harvester webhook, and documentation is added via https://docs.harvesterhci.io/dev/upgrade/automatic#free-system-partition-space-requirement

**Comment by bk201** [comment]
> Moving the issue to v1.2.1 for further tracking. In Harvester v1.2.0, it has already:
> 
> * added a [script](https://github.com/harvester/upgrade-helpers/blob/main/bin/harv-purge-images.sh) that can help to clean up legacy images manually before the upgrade.
> * added free space check on the harvester webhook, and documentation is added via https://docs.harvesterhci.io/dev/upgrade/automatic#free-system-partition-space-requirement

The enhancement was done and we have https://github.com/harvester/harvester/issues/4425 in 1.3.0 to free more images.
