### ISSUE TITLE
[BUG] Addon, rancher-logging only shows "processing" after it had been DeploySuccessful prior to Upgrade

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4225]
**Describe the bug**
Addon, rancher-logging, when enabled (and DeploySuccessful) prior to upgrade from v1.2.0-rc3 -> v1.2-head - when Upgrade is finished and log is downloaded - state of Rancher-Logging Addon remains in "Processing"

**To Reproduce**
1. Start w/ v1.2.0-rc3 Cluster
1. Enable Logging, wait till DeploySuccessful
1. Upgrade to v1.2-Head  Version: v1.2-7f87c261-head , enabling Upgrade Log
1. Download Upgrade Log after Upgrade is Successful
1. Check Addons page, in Private Browsing Window & Normal Window, UI seems to note state of rancher-logging addon is "processing"

**Expected behavior**
Post-Upgrade from v1.2.0-rc3 to v1.2-head, not see rancher-logging Addon that had prior state of DeploySuccessful, shift to "Processing" state.

**Support bundle**
[supportbundle_8f7aa758-dfa8-4514-ad65-aaf4e988cb4e_2023-07-13T00-59-01Z.zip](https://github.com/harvester/harvester/files/12034358/supportbundle_8f7aa758-dfa8-4514-ad65-aaf4e988cb4e_2023-07-13T00-59-01Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc3 ->  Version: v1.2-7f87c261-head 
 - Underlying Infrastructure: qemu/kvm

**Additional context**
![Screenshot from 2023-07-12 18-05-57](https://github.com/harvester/harvester/assets/5370752/1d61bf7a-1e24-40b6-8d6e-f5bb790ef3be)

**Notes**
- As a workaround, disabling and then re-enabling seems to fix the status :smile: 
- The backend seems to note that it was running

Related: https://github.com/harvester/harvester/issues/3595

**Comment by irishgordo** [comment]
updated the reproducability to 'rare' as I'm not sure yet how reproducible this is

**Comment by irishgordo** [comment]
Possibly related to: https://github.com/harvester/harvester/issues/2992

**Comment by starbops** [comment]
Do you know if this only happens after downloading the upgrade log archive? The `rancher-logging` addon is missing from the support bundle file you attached.

<img width="1496" alt="image" src="https://github.com/harvester/harvester/assets/1827717/8e42d776-74d0-48a2-baa3-e0ed9893822c">

**Comment by irishgordo** [comment]
@starbops  - I'm not sure - I will recheck to validate that order :smile:

**Comment by irishgordo** [comment]
@starbops at least in this most recent run I noticed:
v1.2.0-rc3 -> v1.2-head (single node qemu/kvm)  Version: v1.2-1bfcb55e-head 

That when logging was enabled prior to upgrade.

After successful upgrade, logging in the UI shows as disabled seemingly :thinking: 

But in K9s shows as enabled.

I'm thinking the "downloading of the log" doesn't seem to effect what's taking place, as I didn't download the log this time.

Prior to upgrade:
![Screenshot from 2023-07-18 20-13-08](https://github.com/harvester/harvester/assets/5370752/63bd4c33-005c-4b93-bb57-c5c165a4c9a9)

After upgrade:
![Screenshot from 2023-07-18 20-42-07](https://github.com/harvester/harvester/assets/5370752/b41acaed-1e08-4e76-ac92-731ab813da96)

Support Bundle:
[supportbundle_5010d6df-f0f0-4491-9327-5beebd26be55_2023-07-19T03-44-57Z.zip](https://github.com/harvester/harvester/files/12090859/supportbundle_5010d6df-f0f0-4491-9327-5beebd26be55_2023-07-19T03-44-57Z.zip)

Maybe this is just related entirely to 2992?  And this could be closed out?

**Comment by irishgordo** [comment]
And additionally, after downloading the log, the Rancher-Logging Addon's status doesn't shift from "Disabled" to any other state.
Upgrade-Log:
[hvst-upgrade-n9cgc-upgradelog-archive-2023-07-19T03-47-39Z.zip](https://github.com/harvester/harvester/files/12090869/hvst-upgrade-n9cgc-upgradelog-archive-2023-07-19T03-47-39Z.zip)

**Comment by w13915984028** [comment]
@DaiYuzeng @WuJun2016  @ibrokethecloud 

Any insight of https://github.com/harvester/harvester/issues/4225#issuecomment-1641370638 ? why the `Enabled` addon is shown as `Disabled` in UI.  (v1.2.0-rc3 -> v1.2-head (single node qemu/kvm) Version: v1.2-1bfcb55e-head)

could it be related to some out of synced UI enhancments?  The addon status are redefined now, and the UI needs to be updated accordingly.

> https://github.com/harvester/harvester/blob/master/pkg/apis/harvesterhci.io/v1beta1/addon.go#L12

**Comment by w13915984028** [comment]
@ibrokethecloud 
<del>`In v1.2.0-rc3, the addon is `enabled` and in status `deployedsuccessful`; when upgrading to v1.2.0-master-head, should the new addon implementation do something on controller side or upgrade script ?`</del>

this issue was raised 2 weeks ago, the new addon was not there yet, should be related to other issues.

**Comment by w13915984028** [comment]
@starbops could you double check the `cattle-monitoring-system` and `cattle-logging-system`; and all the `addons` are fetched by the `support-bundle-tool`? the related yamls/logs are not in the SB file, thanks.

**Comment by w13915984028** [comment]
> Possibly related to: #2992

@irishgordo   #2992 worked against v112->v120;  here it is from v120-rc3 --> v120-master-head; and both rancher-monitoring and rancher-logging addons have no version changes, the upgrade script did nothing to them;  should not be related.



@DaiYuzeng @WuJun2016 

As @irishgordo encountered both `Disabled` and `Processing` status when upgrading to v120 master-head, when rancher-logging is enabled and deployed successfully, but k9s showed correctly. I meant an random status was shown on UI.

I suspect the below code:

```
  get stateDisplay() {
    if (!this?.status?.status) {
      return this.spec.enabled === false ? 'Disabled' : 'Processing';
    }
```

When system is just updated, if the UI fetch `this?` failed, what could be displayed ? and will the UI re-fresh is such case?

@irishgordo Did you tried to force re-fresh the Web browser after upgrade? Was the above web stopped on `addon` page during the whole upgrade process?

**Comment by DaiYuzeng** [comment]
We have simplified the logic of state displaying. The latest code is as follows:

```
get stateDisplay() {
    const out = this?.status?.status;

    if (!out) {
      return 'Disabled';
    }

    if (out.startsWith('Addon')) {
      return out.replace('Addon', '');
    }

    return out;
  }
```

It should be displayed as `Disabled` on the latest UI if `this.status.status` is `undefined` or `null`. The status should be updated automatically if the UI detects any changes from the websocket.

**Comment by w13915984028** [comment]
@DaiYuzeng In the upgrading, the backend `harvester` POD will be rebooted.  When `addon` web page stays there and has no manual re-refresh, will UI detect the broken websocket and re-connect automatically?

**Comment by DaiYuzeng** [comment]
I think it should reconnect automatically, but I can't confirm. @WuJun2016, did you look into the re-connection of the websocket?

**Comment by w13915984028** [comment]
@irishgordo Please also help validate on latest master-head, the UI change may fix it. And also force re-fresh the web page to check if something will change.

If it happens again, please also help fetching information via `kubectl get addons.harvesterhci.io -n cattle-logging-system rancher-logging -oyaml`, thanks.

**Comment by WuJun2016** [comment]
> I think it should reconnect automatically, but I can't confirm. @WuJun2016, did you look into the re-connection of the websocket?

It will connect automatically and you can see the connection and disconnection information in the browser's console

**Comment by irishgordo** [comment]
@w13915984028 @DaiYuzeng @starbops @WuJun2016 
This looks good :smile:  :+1: 
The UI Change on master-head seems to have fixed this :+1: 
Upgrading from v1.2.0-rc3 -> master-head there is no issue present with displaying the `rancher-logging` addon's status correctly 

So I'll go ahead and close this out
![Screenshot from 2023-07-24 10-11-45](https://github.com/harvester/harvester/assets/5370752/82d8dcca-b247-4b02-991b-4c6a8c5db0a1)
