### ISSUE TITLE
[BUG]Redundant NAD created during applying Storage-Network change

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4226]
**Describe the bug**

Longhorn only requires one NAD for Storage Network. However, if applying Storage Network change, there are multiple identical NADs could be found on Harvester

**To Reproduce**
1. Enable Storage-Network and apply configuration ![storage-network](https://github.com/harvester/harvester/assets/19387129/47104b5a-11f6-42d2-90af-4745283eb49f)
2. After applying Storage-Network, there are multiple NADs could be found on Harvester, for example:
```
   kubectl -n harvester-system get network-attachment-definitions.k8s.cni.cncf.io -o wide
   NAME                   AGE
   storagenetwork-25c9h   10m
   storagenetwork-2wkbw   10m
   storagenetwork-9snqr   10m

```
3. Longhorn only leverages one of the NADs ![longhorn-storage-network](https://github.com/harvester/harvester/assets/19387129/0b18c243-8cee-4427-97f1-a77674012272)

**Expected behavior**

There should be only one NAD existing for Storage-Network

**Comment by guangbochen** [comment]
can't reproducible this issue in my `v1.2.0-rc4` 3 nodes cluster with the above steps, wondering if any step is missing?
```
ks get network-attachment-definitions.k8s.cni.cncf.io -n harvester-system
NAME                   AGE
storagenetwork-jl9qj   31m
```

**Comment by WebberHuang1118** [comment]
From my experience,
It does not always happen. I think it is related to the timing affecting on https://github.com/harvester/harvester/blob/2e0a773e2d21880442d605cce412dd6f5978a0e2/pkg/controller/master/storagenetwork/storage_network.go#L317-L326

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create cluster network and configuration
3. enable storage network
4. Execute following script to test `storage-network` switching (update required info which quote with `<>`)
```python
from harvester_api import API  # install from https://github.com/harvester/tests
from time import sleep
from datetime import datetime, timedelta

import urllib3
urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
api = API('https://<cluster_VIP>')
api.session.verify = False
api.authenticate('admin', '<password>')

cidrs = ["<Add more than 2 CIDRs for switching>"]

code, data = api.settings.get('storage-network')
spec = api.settings.StorageNetworkSpec.from_dict(data)

for i in range(40):
    spec.value['range'] = cidrs[i % len(cidrs)]
    code, data = api.settings.update('storage-network', spec)
    assert 200 == code, (code, data)
    endtime = datetime.now() + timedelta(seconds=120)
    while endtime > datetime.now():
        code, data = api.settings.get('storage-network')
        conds = data.get('status', {}).get('conditions', [])
        if conds and 'True' == conds[-1].get('status') and 'Completed' == conds[-1].get('reason'):
            break
        sleep(1)
    else:
        raise AssertionError(
            "Storage network updated but not completed.\n"
            f"API Status({code}): {data}"
        )
    nads = api._get('v1/k8s.cni.cncf.io.network-attachment-definitions').json()['data']
    print([n['id'] for n in nads])
    sleep(1)

```
5. The output should not have more than `2` NADs
6. Access API endpoint `https://<ClusterVIP>/v1/k8s.cni.cncf.io.network-attachment-definitions`, there should finally have only `1` NAD.
7. Create an image for VM creation
8. Create VM `vm1` and start it
9. VM should operate normally
