### ISSUE TITLE
The virtual machine crashes and restarts under high load

### ISSUE THREAD

**Issue by delongdk** [harvester/harvester#4229]
**Describe the bug**
Recently, we have been experiencing interruptions in the testing process of a VM used as a database server. Upon investigation, we found that the VM crashes and is automatically restarted by the platform.

However, neither within the VM kernel  nor in the cluster log of the harvester can we identify the cause of the virtual machine crashes.

The following is a crash event.

* Event occurrence time: UTC 2023-07-11 10:41:27
* VM namespace: eb-division
* VM name: vm02-postgres
* Harvester log Timezone: UTC
* VM log Timezone: CST
* VM os: RHEL 8.4 / Linux 4.18.0-305.el8.x86_64
* VM resource: 8 vCPU / 48G mem / 3T disk

Zip file contains: VM kernel log / resource monitor log / harvester cluster flow log

[logs.zip](https://github.com/harvester/harvester/files/12034761/logs.zip)

There's no commands to kill any processes in the VM. 

What we only found in the VM logs, the monitoring information was interrupted at 10:41:26, and the OS was restarted at 10:41:58. 
In the harvester logs, a VM crash notification at 10:41:40.379. No exact reason for the VM crashes.

The frequency of these crashes is quite high. It's nearly impossible to complete a full stress test.
So we need your help to analyze and find a solution to solve this problem.

**To Reproduce**

**Expected behavior**

**Support bundle**
[supportbundle_1dfc0125-2b6a-43f3-ba7b-9c40974583b6_2023-07-13T02-12-06Z.zip](https://github.com/harvester/harvester/files/12034871/supportbundle_1dfc0125-2b6a-43f3-ba7b-9c40974583b6_2023-07-13T02-12-06Z.zip)

**Environment**
* Harvester V1.1.1 with 3 nodes
* management network, 2*10Gbe devices: Intel Corporation Ethernet Controller X710 for 10GbE SFP+ (rev 02)
* cluster network, 2*1Gbe devices: Intel Corporation I350 Gigabit Network Connection (rev 01)

**Additional context**

**Comment by masteryyh** [comment]
Hi @delongdk thanks for reporting!
Just wondering, you are using `high load` in your title, what kind of high load is your VM been experiencing?

**Comment by delongdk** [comment]
@masteryyh Kindly for your reply.

Our scenario is similar to creating database indexes, executing procedures and manipulating data in multiple tables.

**Comment by bk201** [comment]
@delongdk By viewing the support bundle, I saw lot of oom logs:
```
# grep "usage" **/kernel.log* | grep memory | grep -v swap
...
pros-c/logs/kernel.log.2:Jul 05 07:29:13 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 66
pros-c/logs/kernel.log.2:Jul 06 03:55:31 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 49
pros-c/logs/kernel.log.2:Jul 06 04:43:30 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 28
pros-c/logs/kernel.log.2:Jul 06 05:49:36 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 162
pros-c/logs/kernel.log.2:Jul 07 18:23:56 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 300
pros-c/logs/kernel.log.2:Jul 07 18:23:56 pros-c kernel: memory: usage 50671616kB, limit 50671616kB, failcnt 374

```

KubeVirt reserves some memory (besides VM's request memory) for qemu process, which might not be enough when VM has intensive I/O (or maybe high memory). Can you try increasing the reserved memory and see if it help?
https://docs.harvesterhci.io/v1.1/vm/create-windows-vm#vm-crashes-when-reserved-memory-not-enough

Given you have a beefy machine, I will probably start from 1G.

**Comment by delongdk** [comment]
@bk201 Thank you very much for your help. 

I think we have found the cause of the crashes. I will increase the reserved memory for this type of VM and observe if there will be any more crashes occurring.
