### ISSUE TITLE
[BUG/DOC] Failed to pass guest cluster name into Harvester cloud provider

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#4232]
**Describe the bug**

**To Reproduce**
1. Spin up Harvester and import into Rancher v2.7.5
2. Spin up an RKE2 guest cluster with Harvester cloud provider
3. Deploy an Nginx and create the related load balancer service. Harvester cloud provider will create an LB whose name prefix will be always `kubernetes`. Normally, it should be the name of the RKE2.
4. Check the HelmChartConfig in the RKE2. You will see the following YAML.
```
apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  annotations:
    objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4SRPU/DMBCG/wq6OanbNE2KJQbUBYmFATF1udiXxsQfkX0JQlX/O0oLEgylo2W/j5/37gg4mDeKyQQPEjqybqGQ2dLCBDGtIIPeeA0Snsi6XYeRd8G35gAZOGLUyAjyCOh9YGQTfJqPoXknxYl4EU34BTQzCbKr9+HDU8wPUw8S+nX6o5LdPRuvHx61Dv4mwqMjkODQ44F0rmbxXP2Y386mAdUM6MeG8vSZmBycMlCRziVfjaPE6AaQfrQ2A4sN2X+rd5g6kKDbulpWShcF1m19vyqrdYtYl6ttuVxvN6rcNEWltzj/9l2iwzhRYoq5smHU+RDDZDRFuLy4opoGUrPPhHaktAueyTNIOO7hjLms8QW524Pcg5gwCmsaEdGrjqKIPRWCWInL1PLWWEriHIXT6SsAAP//kKHxnTgCAAA
    objectset.rio.cattle.io/id: ""
    objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
    objectset.rio.cattle.io/owner-name: managed-chart-config
    objectset.rio.cattle.io/owner-namespace: kube-system
  creationTimestamp: "2023-07-13T02:45:20Z"
  generation: 1
  labels:
    objectset.rio.cattle.io/hash: df7606cd22a7f791463faa741840385c45b26d8a
  name: harvester-cloud-provider
  namespace: kube-system
  resourceVersion: "313"
  uid: d5d8ec35-e4f2-4194-997e-c57a1ab08167
spec:
  valuesContent: '{"cloudConfigPath":"/var/lib/rancher/rke2/etc/config-files/cloud-provider-config","clusterName":"rke-old","global":{"cattle":{"clusterId":"c-m-k5q865r6"}}}'
```

In the field `spec.valuesContent`, the `clusterName` should be the `global.cattle.clusterName`.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.2.0-rc2/Rancher v2.7.5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by n313893254** [comment]
Hi, @TachunLin. As the Rancher v2.7.6 will be released in the next month. Could you verify this issue with Rancher 2.7-head before the doc is provided? cc @guangbochen @WuJun2016

**Comment by TachunLin** [comment]
Verified **fixed** on Rancher v2.7-head (6742277) with Harvester v1.2.0-rc4. 

### Result
* We can create load balancer on Rancher, running correctly and assigned by IP pool created of given RKE2 guest cluster name on customized `default` namespace
![image](https://github.com/harvester/harvester/assets/29251855/c3e4deb6-c08a-4f11-a85d-11bed2e46f4c)
  

* Check the HelmChartConfig in the RKE2. we can find the guest cluster name have been passed to `spec.valuesContent.global`
  ```
  > kubectl get helmchartconfigs.helm.cattle.io -n kube-system harvester-cloud-provider -o yaml
  apiVersion: helm.cattle.io/v1
  kind: HelmChartConfig
  metadata:
    annotations:
      objectset.rio.cattle.io/applied: H4sIAAAAAAAA/4SRPU/DMBCG/wq6OanbNE2KJQbUBYmFATF1udiXxsQfkX0JQlX/O0oLEgylo2W/j5/37gg4mDeKyQQPEjqybqGQ2dLCBDGtIIPeeA0Snsi6XYeRd8G35gAZOGLUyAjyCOh9YGQTfJqPoXknxYl4EU34BTQzCbKr9+HDU8wPUw8S+nX6o5LdPRuvHx61Dv4mwqMjkODQ44F0rmbxXP2Y386mAdUM6MeG8vSZmBycMlCRziVfjaPE6AaQfrQ2A4sN2X+rd5g6kKDbulpWShcF1m19vyqrdYtYl6ttuVxvN6rcNEWltzj/9l2iwzhRYoq5smHU+RDDZDRFuLy4opoGUrPPhHaktAueyTNIOO7hjLms8QW524Pcg5gwCmsaEdGrjqKIPRWCWInL1PLWWEriHIXT6SsAAP//kKHxnTgCAAA
      objectset.rio.cattle.io/id: ""
      objectset.rio.cattle.io/owner-gvk: k3s.cattle.io/v1, Kind=Addon
      objectset.rio.cattle.io/owner-name: managed-chart-config
      objectset.rio.cattle.io/owner-namespace: kube-system
    creationTimestamp: "2023-07-25T09:42:23Z"
    generation: 1
    labels:
      objectset.rio.cattle.io/hash: df7606cd22a7f791463faa741840385c45b26d8a
    name: harvester-cloud-provider
    namespace: kube-system
    resourceVersion: "302"
    uid: f92b6da0-6f56-4109-a963-ba6e8a3bf7fd
  spec:
    valuesContent: '{"cloudConfigPath":"/var/lib/rancher/rke2/etc/config-files/cloud-provider-config","global":{"cattle":{"clusterId":"c-m-7b5dt6sd","clusterName":"rke2-v1266"}}}'
  ```

* Also confirm we can create load balancer on Rancher, running correctly and assigned by IP pool created of given RKE2 guest cluster name on customized `test1` namespace
![image](https://github.com/harvester/harvester/assets/29251855/9e04a394-0195-4369-8b5b-5a2fa7ef34c9)

![image](https://github.com/harvester/harvester/assets/29251855/28a9ee9c-5923-4e59-b58f-16ab8d41d155)

### Test Information
* Test Environment: single nodes Harvester on kvm machine
* Harvester version: v1.2.0-rc4
* Rancher version: v2.7-head (6742277)

### Verify Steps
<details><summary>Execution Steps</summary>

  1. Import Harvester to Rancher 
  2. Access Harvester from Rancher
  3. Create a namespace test1 under default project
  4. Provision a RKE2 cluster and select test1 as the namespace 
  5. Access Harvester from Rancher
  6. Create an IP pool, select Project default, namespace: test1 and select the RKE2 cluster name 
  7. Access RKE2 guest cluster on Rancher 
  8. Create a nginx deployment on the customized namespace test1 
  9. Create a load balancer service, 
  10. On the ipam mode, select the Pool mode  
  11. Use other namespace like `default` and `harvester-public` and follow above steps  

</details>

**Comment by WuJun2016** [comment]
Hi @TachunLin  Because upstream switched a new `2.7.6` branch to fix the problem. Could you please help revalidate this issue on the `2.7.6-rc2` branch of Rancher with the upstream issue https://github.com/rancher/dashboard/issues/9472,  thanks.

**Comment by albinsun** [comment]
FYI, also hit with Harvester `v1.2.0-rc5` + Rancher `v2.7.6-rc2`

Namespace `All` & guest cluster `All` :heavy_check_mark: 
![image](https://github.com/harvester/harvester/assets/2773781/ebf8788f-fd7c-44a6-8370-9898912d69cb)

Namespace `All` & specified guest cluster :x: 
![image](https://github.com/harvester/harvester/assets/2773781/a1214d84-caa0-44cd-a7b1-d1adcae7f76f)

Namespace `default` & guest cluster `All` :x: 
![image](https://github.com/harvester/harvester/assets/2773781/75af4a19-c953-4dc9-8beb-4af5e6ed41b8)

Namespace `default` & specified guest cluster :x: 
![image](https://github.com/harvester/harvester/assets/2773781/9845eac8-d92a-46d1-87c3-f94ff572cf8a)

**Comment by TachunLin** [comment]
Appreciated for Albin checking on the document validation. 

@WuJun2016, sorry I did not link the latest test result which was tested on Rancher v2.7.6-rc2 with Harvester v1.2.0-rc5 which was done in
https://github.com/rancher/dashboard/pull/9381#issuecomment-1669014539

I re-verify on Rancher v2.7.6-rc2 with Harvester v1.2.0-rc5, the test result looks good in the following scenarios:

* With namespace `All` and specify the guest cluster we created, we can create load balancer to use IP pool on Harvester 

  ![image](https://github.com/harvester/harvester/assets/29251855/3dfac4dd-ca62-49c4-aae1-05d8a0334cb1)
  
  
  ![image](https://github.com/harvester/harvester/assets/29251855/122f38aa-eed4-467b-89b5-60037ef89935)


* With namespace `default` and guest cluster `all`, we can create load balancer to use IP pool on Harvester

![image](https://github.com/harvester/harvester/assets/29251855/47276cf8-8365-4bd2-af9d-f06e97edc700)

![image](https://github.com/harvester/harvester/assets/29251855/b23bbf46-b9ab-4c50-b11a-4aae33ca1779)


* With namespace `default` and specify the guest cluster we created, we can create load balancer to use IP pool on Harvester

![image](https://github.com/harvester/harvester/assets/29251855/ea8a672e-f629-4380-a173-172301b0420b)

![image](https://github.com/harvester/harvester/assets/29251855/5b23d94b-2495-4d45-a1e0-658353e517eb)


I think the difference would be when we create the IP pool in multi-cluster view, we need to specify the `vm network` to make the load balancer can have the correct route.

**Comment by starbops** [comment]
The fix has been included in Rancher v2.7.6. I verified that the bug no long exists with the test plan above in the following combinations:

- Rancher v2.7.10 + Harvester v1.2.1 + RKE2 guest cluster v1.26.14
- Rancher v2.7.10 + Harvester v1.3.0-rc4 + RKE2 guest cluster v1.26.14

We can close this issue as completed. cc @bk201

**Comment by SnelsSM** [comment]
And now in Rancher v2.8.3 and Harvester v1.2.1, the problem is back.

**Comment by bk201** [comment]
@starbops please help check if we need to re-open the issue. Thank you!
