### ISSUE TITLE
[BUG] Cannot login to migrated VM

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#4235]
**Describe the bug**
I migrated a VM from Proxmox, now try to log in with root and the password, but it keeps saying Login incorrect, even though I can easily log in to the original VM with the exact same data.
Any idea what is causing that?

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HPE

**Comment by masteryyh** [comment]
Hi @xeruf 
Can you give some details about how did you migrate a VM from Proxmox to Harvester?

**Comment by xeruf** [comment]
I extracted and converted a backup:  

    lzop -d vzdump-qemu-102-2022_07_30-17_29_21.vma.lzo
    vma extract vzdump-qemu-102-2022_07_30-17_29_21.vma 102pve
    qemu-img convert 102pve/disk-drive-scsi0.raw -O qcow2 102.qcow2

Then uploaded it into Harvester and created a VM with it as disk.  
Hostname and everything look fine, it is oddly simply not accepting my login.

**Comment by xeruf** [comment]
Tried again with another user which has a different password, same result.
Maybe something wrong with special files or so?

**Comment by xeruf** [comment]
oops, seems like an old VM version with different password was the issue :sweat_smile:
