### ISSUE TITLE
[BUG] harvester process spike to ~50% CPU after sometimes

### ISSUE THREAD

**Issue by c3y1huang** [harvester/harvester#424]
**Describe the bug**
Noticed the harvester process spike to ~50% CPU after some time (for me, 1 - 2 hours).

**To Reproduce**
1. Install k3s and harvester.
2. Monitor harvester process on the host and eventually it spikes to ~50% CPU.
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                
17944 root      20   0  215396 143708  28592 S 50.00 1.410   2:53.99 harvester 
```

**Expected behavior**

Should not spike to ~50% CPU

**Log**

`none`

**Environment:**
 - Harvester ISO version: 0.1.0
 - Installation Mode: both app-mode and ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
No operation in between.

**Comment by guangbochen** [comment]
should be addressed via https://github.com/rancher/harvester/pull/434 and could be tested using the `rancher/harvester:master-head` image.

**Comment by DoNotSayYes** [comment]
Validated on master-head, keep watching harvester process on the host, its CPU usage seems not staying at 50%
![image](https://user-images.githubusercontent.com/57614736/105813690-2c4b0780-5feb-11eb-8a9d-7a3b67ca066e.png)

**Comment by DoNotSayYes** [comment]
Reopen the issue, need to keep focusing on the high CPU utilization
The basic info of the environment:
![image](https://user-images.githubusercontent.com/57614736/105826306-8fdd3100-5ffb-11eb-888d-0550b0b89f7b.png)
![image](https://user-images.githubusercontent.com/57614736/105826423-adaa9600-5ffb-11eb-881e-cd36bbc7183d.png)
![image](https://user-images.githubusercontent.com/57614736/105827021-6cff4c80-5ffc-11eb-9e0e-e4cb2425f0b8.png)

**Comment by DoNotSayYes** [comment]
The host CPU utilization seems not getting high anymore.
![image](https://user-images.githubusercontent.com/57614736/109615509-f14e6d80-7b6e-11eb-8409-419f253996e6.png)
