### ISSUE TITLE
[Question] How to programmatically restore VMs

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#4241]
I now have a pipeline to create qcow images from Proxmox VMs, but how can I programmatically import them into Harvester, ideally uploading the image via scp or the like?

**Comment by masteryyh** [comment]
Maybe you can upload images directly by calling Harvester API?
You can find image API here: `https://<your-cluster-vip>/v1/harvester/harvesterhci.io.virtualmachineimages`
Currently we don't have documents about calling API directly.

**Comment by xeruf** [comment]
That sounds useful, but I'd need more info, as I need multiple calls:
Upload the image, create a Volume, create and configure and launch a Virtual Machine.

Is somebody from the engineering team willing to have a little call about such things? We would be happy to pay if we finally get all our little issues resolved, which is taking us weeks already...

**Comment by xeruf** [comment]
Any help here regarding the automation?
