### ISSUE TITLE
[BUG] In VM:Create -> Advanced Options, dropdown tip "Select a template" can be select but should not.

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4243]
**Describe the bug**
In VM:Create -> Advanced Options -> Cloud Config
1. Can chose "Select a template" and create VM
   ![TipShouldNotBeSelected](https://github.com/harvester/harvester/assets/2773781/f219cf0e-3260-4270-898d-1718d648e299)

2. Occasionally, 2 entries will be create for the same VM.
   > **Note**
   > Hit occasionally, not easy to reproduce.
   
   ![OneVMButTwoEntries](https://github.com/harvester/harvester/assets/2773781/f11ea6ac-80b7-4a3b-b4bc-3796d524751b)

**To Reproduce**
1. Create an image
5. Go to 'Virtual Machines' -> 'Create', fill in necessary fields
6. Go to 'Advanced Options' tab, chose 'Select a Template' in Cloud Config's User/Network Data Template
7. Create VM

**Expected behavior**
1. Tip "Select a template" should not be chose or can drop directly 
   e.g. Can refer to SSH key UI
   ![expected](https://github.com/harvester/harvester/assets/2773781/78009096-bd0d-46b3-99a9-da82d2456d24)

**Environment**
 - Harvester ISO version: `v1.2.0-rc3`
 - Underlying Infrastructure: QEMU/KVM, single node (8C/16G/250G)

**Comment by a110605** [comment]
`Select a template` option should not pop up. 
 Should show `Create new...` option and a list of created template for user to choose.

Same issue for below `Network Data Template`

<img width="1495" alt="Screenshot 2024-05-06 at 10 31 59 AM" src="https://github.com/harvester/harvester/assets/5744158/e8531261-c675-4fa4-8a8f-9f82be8dd6de">

**Comment by irishgordo** [comment]
Thanks for the fix @a110605  - this looks good on Harvester  Version: master-9c0a3a1-head 

:+1: :smile: 
I"ll go ahead and close this out
![Screenshot from 2024-07-05 14-08-06](https://github.com/harvester/harvester/assets/5370752/336995f4-955a-4502-9553-823ea7189629)
