### ISSUE TITLE
[Doc] Storage network: considering backing image pods in IP Plan

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4244]
**Is your doc request related to a problem? Please describe or add related issue ID.**

In the [document](https://docs.harvesterhci.io/dev/advanced/storagenetwork#configuration-example) of storage network configuration:

> IP range should be IPv4 CIDR format and 4 times the number of your cluster nodes. Longhorn will use 2 IPs per node, and the upgrade process will run two versions of Longhorn simultaneously. It will consume 4 IPs per node in the upgrade process.

This doesn't mention backing image pods. Backing image pods also need IPs in the storage network.

**Describe the solution you'd like**

Add docs about estimating needed IPs for backing image pods:
- backing-image-ds pods
- backing-image-manager pods

Add GUI hints:
<img width="538" alt="Screenshot 2023-07-17 at 5 03 50 PM" src="https://github.com/harvester/harvester/assets/1691518/e7466ffa-750b-40c2-9a0b-bf73198eccdd">

Ref: https://docs.harvesterhci.io/dev/advanced/storagenetwork#configuration-example

**Comment by janeczku** [comment]
Documentation should provide an easy formula to calculate required number of storage network IP addresses. E.g:
Required number of IP addresses = `Number of servers in the cluster + total number of physical discs in the cluster`

**Comment by bk201** [comment]
- The doc is published at: https://docs.harvesterhci.io/v1.2/advanced/storagenetwork#configuration-example
- GUI enhancement is added in 1.2.0:
<img width="1315" alt="Screenshot 2023-11-30 at 6 05 29 PM" src="https://github.com/harvester/harvester/assets/1691518/8d2eb2f4-b342-4a6b-a0af-f7edda6befcd">
