### ISSUE TITLE
[BUG/DOC] Upgrade will stuck in Pre-drained if there are vms in the cluster before the upgrade

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#4249]
**Describe the bug**

![](https://github.com/harvester/harvester/assets/15064560/d98dfdbb-1671-4f8b-9130-cfb2071aa28f)

**To Reproduce**

1. create a VM in Harvester v1.1.2 (a three nodes cluster)
2. take VM snapshot
3. upgrade the Harvester cluster by the v1.2 iso image https://releases.rancher.com/harvester/v1.2/harvester-v1.2-amd64.iso

**Expected behavior**

upgrade successfully

**Support bundle**

[supportbundle_8720e2f8-e42d-4704-9ed2-f315b54b755f_2023-07-18T01-22-58Z.zip](https://github.com/harvester/harvester/files/12074926/supportbundle_8720e2f8-e42d-4704-9ed2-f315b54b755f_2023-07-18T01-22-58Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2 -> v1.2 head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM 3node Harvester VM

**Additional context**

**Comment by bk201** [comment]
The issue is caused by single replica volumes. Longhorn can't drain a node if the node contains the last replica. Adding a document to this and how to mitigate it.

**Comment by guangbochen** [comment]
Close as the workaround is available on https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#5-an-upgrade-is-stuck-in-the-pre-drained-state
