### ISSUE TITLE
[BUG] Broken ISO Mode link in README

### ISSUE THREAD

**Issue by c3y1huang** [harvester/harvester#425]
**Describe the bug**

ISO Mode link is broken in https://github.com/rancher/harvester/blob/master/docs/README.md

**To Reproduce**
`none`

**Expected behavior**

`none`

**Log**

`none`

**Environment:**
`none`

**Additional context**
`none`

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/426
