### ISSUE TITLE
[Question]import kvm to harvester platform

### ISSUE THREAD

**Issue by chloe6888** [harvester/harvester#4269]
After installing harvester cluster, we want to import a lot of bare kvms to harvester platform. The currently provided vm-import-controller plug-in only supports two sources: OpenStack and VMware vSphere. Is there a way to quickly complete batch migration of kvm?

**Comment by masteryyh** [comment]
Hi @18707602767
Currently we don't support importing bare KVM VMs directly, maybe you can try to make qcow2 images and upload them to your Harvester cluster? 😄
