### ISSUE TITLE
[BUG] Create a new image with same url but different name, it would stuck and failed with error

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4273]
**Describe the bug**

When we add an image from url and create a VM. 

After we create another image with the same url but different name 

* The image will first in `Pending` state  for a long time (more than 10 minutes) 
![image](https://github.com/harvester/harvester/assets/29251855/ab2cdb5f-5320-4cda-8824-1b4449ef4ca4)

* And finally failed and display the error message
  ```
  Failed to process sync file: Get "https://mirror.tspu.ru/opensuse/repositories/Cloud%!A(MISSING)/Images%!A(MISSING)/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2": context deadline exceeded
  ```

  ![image](https://github.com/harvester/harvester/assets/29251855/c926e3f9-b394-4f3d-b1b0-65735b34acd3)

* If we delete both of the images and recreate them using the same name and url , It will failed with response `503` error 

**To Reproduce**
1. Create an image from url given name `opensuse` 
https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2
2. And create a VM using image `opensuse`
3. Then create another image with the same url but different name `suse` 
4. Check the image creation state
5. Delete both image `opensuse` and `suse`
6. Create another image with the same name `opensuse` and the same url
7. Check the image creation state

**Expected behavior**

Can create image using same url but different name correctly. 

**Support bundle**

[supportbundle_28daee29-b546-41a9-85e7-a4d2ca5e1c51_2023-07-19T09-51-01Z.zip](https://github.com/harvester/harvester/files/12093609/supportbundle_28daee29-b546-41a9-85e7-a4d2ca5e1c51_2023-07-19T09-51-01Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine

**Additional context**
Volume state
![image](https://github.com/harvester/harvester/assets/29251855/c83be40a-0795-41f3-9419-fe1eb7d624d6)

**Comment by bk201** [comment]
https://download.opensuse.org has a mirror system, and it might return a different source each time. Probably the URL in the second try has some issues.

**Comment by TachunLin** [comment]
Indeed, on the second try in a short interval would also encounter the same error. 
![image](https://github.com/harvester/harvester/assets/29251855/75988b61-047a-45f8-85d9-3e8dfc5b0264)

Let me wait for longer time and try the create image from url for the check.

**Comment by TachunLin** [comment]
In the another try, I can create the opensue image from the same URL with different image name 
https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2 

The original case might be I got the different download source from mirror system. 

![image](https://github.com/harvester/harvester/assets/29251855/8860f9d9-6985-4956-b28b-c98de3b8e231)

**Comment by bk201** [comment]
The download failed due to a different mirrored site; please re-open if needed.
