### ISSUE TITLE
[Question] Fiber/iSCSI SAN shared storage

### ISSUE THREAD

**Issue by TomDeSchutter** [harvester/harvester#4276]
My google-fu fails me finding results on how to deal with more conventual setups. How would I go about using storage aside the volume(s) in use on every node, converged by Longhorn? Can I use any form of local-path provisioner, and if so, how...? Any direction would be appreciated.

Edit: I am aware this falls outside of Harvesters' nature. Obviously written specifically for HCI setups and all.

**Comment by noahgildersleeve** [comment]
If you are still wondering about this, it was addressed in v1.2.0 with #2405 and #1199
