### ISSUE TITLE
[BUG] Missing Monitoring Dashboard in v1.1

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#4277]
**Describe the bug**
I am logged in as admin user, and cannot find prometheus anywhere as explained in the docs:
https://docs.harvesterhci.io/v1.1/monitoring/
Neither any metrics on the dashboard.

Links to Prometheus and Grafana give me 503 with a message like 'no endpoints available for service "http:rancher-monitoring-prometheus:9090"'

**Expected behavior**
Monitoring is visible somewhere, with a message of temporary unavailability if needed.

**Environment**
 - Harvester ISO version:  1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): HPE Cloudline

**Additional context**

**Comment by connorkuehl** [comment]
Is this issue persistent for you or does it go away after the node has been online for a little bit?

I noticed just now when I spun up a v1.1.2 Harvester install that if I raced to the sidebar and clicked "Monitoring & Logging" > "Monitoring" > "Grafana" in sidebar > "Grafana" button that I was able to get the 503 as well. A short time after that, all of the monitoring processes were online though, and then metrics were working fine for me.

If it's persistent, could you share the output of:

```console
harvester:~ # kubectl get pods -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS      AGE
alertmanager-rancher-monitoring-alertmanager-0           2/2     Running   0             11m
prometheus-rancher-monitoring-prometheus-0               3/3     Running   0             11m
rancher-monitoring-grafana-8559b68898-b968d              3/3     Running   0             12m
rancher-monitoring-kube-state-metrics-77ddfd789b-7p296   1/1     Running   2 (15m ago)   31d
rancher-monitoring-operator-bd988f5fb-qtzxl              1/1     Running   2 (15m ago)   31d
rancher-monitoring-prometheus-adapter-79d8db9697-dxq2g   1/1     Running   2 (15m ago)   31d
rancher-monitoring-prometheus-node-exporter-rzqfz        1/1     Running   2 (15m ago)   31d
```

**Comment by xeruf** [comment]
Our server situation changed substantially, will reopen if needed
