### ISSUE TITLE
[BUG] Addons form doesn't revert to default values when second time enabling a given Addon

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4279]
**Describe the bug**
The rancher monitoring addon if enabled - and have set custom values like Prometheus date retention to something other than `5d`, to something like `10d`, when addon is enabled - then addon is disabled - then when the user goes to enable the addon again, the values in the form for the addon remain at `10d` instead of the default of `5d`.

**To Reproduce**
1. Go to addons
1. Enable rancher-monitoring
1. Set Prometheus section's `retention` from default value of `5d` to `10d`
1. Save
1. Wait for addon to have deploy successful
1. Disable addon
1. Go back to re-enable addon of rancher-monitoring
1. You'll see that default value is no longer present in Prometheus section's `retention` and is not `5d` as expected, but rather at `10d` to what it was previously set to

**Expected behavior**
Default values to come across instead of custom values.

**Environment**
 - Harvester ISO version: v1.2-head /  Version: v1.2-37aeb5ff-head 
 - Underlying Infrastructure: qemu/kvm

**Comment by WuJun2016** [comment]
Hi @irishgordo   I think this is expected user behavior, because it's a value set by the user, which means he'll use it again, so we shouldn't set all values to default after the user disables them.

**Comment by irishgordo** [comment]
Oh okay :+1: :smile:  - that makes sense - thanks for providing that insight @WuJun2016  - I'll go ahead and close this out :smile:
