### ISSUE TITLE
[BUG] Fail to access UI via rancher proxy

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#428]
**To Reproduce**
1. Add a rancher catalog 
```
Name: harvester
Catalog URL: https://github.com/rancher/harvester
Branch: v0.1.0
Scope: global
Helm Version: Helm v3
```
2. install Harvester app to a project, use all the default configurations
3. Go to the apps page, Click the index.html link of the Harvester app to access Harvester UI

**Results**
Failed to load the UI.
Saw the following errors in the browser console:
![image](https://user-images.githubusercontent.com/5697937/104551661-46dbc300-5672-11eb-93fa-a4bd588358fe.png)

**Environment:**
 - Harvester version: v0.1.0
 - Installation Mode: app-mode

**Additional context**
It works using the master branch, so it may be related to the bundled UI.

**Comment by DoNotSayYes** [comment]
Validated on master-head, the harvester UI was loaded successfully, only the redirect error could be encountered.
![image](https://user-images.githubusercontent.com/57614736/105828568-3de9da80-5ffe-11eb-92ec-3fb4057cfe4c.png)
