### ISSUE TITLE
[ENHANCEMENT] add webhook validation of the http proxy config

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4282]
**Is your enhancement related to a problem? Please describe.**
If you configure `httpProxy` and `httpsProxy`, you must also put Harvester node's CIDR into noProxy, otherwise, the Harvester cluster will be broken. It would be nice to add proper validation to prevent misconfiguration.

**Describe the solution you'd like**
We can add a webhook to validate the user input; it should reject if the node IP is not included in the no_proxy CIDR range.

**Describe alternatives you've considered**
Add the `caution` text to the UI before implementing the webhook.

**Additional context**
doc ref: https://docs.harvesterhci.io/v1.1/advanced/index/#http-proxy

**Comment by futuretea** [comment]
If user configure cluster-registration-url setting, user might need to put the host of cluster-registration-url into noProxy too, otherwise, the Harvester cluster cannot be accessed from upstream Rancher

**Comment by irishgordo** [comment]
@votdev thanks for this enhancment :smile: :+1: 
This looks good on  Version: v1.4.0-dev-20240830 

With just the added context about the open issues/enhancments:
- https://github.com/harvester/harvester/issues/6539
- https://github.com/harvester/harvester/issues/6440

Everything looks good :smile: from all test-cases.
Some small artifacts:
![Screenshot from 2024-09-10 11-49-20](https://github.com/user-attachments/assets/9cf35e96-f76e-4b1f-8ed8-819854968bd8)
![Screenshot from 2024-09-10 11-48-16](https://github.com/user-attachments/assets/d634e3eb-b41d-4f57-a1a7-74b074bb32af)

I'll go ahead and close this out :+1:
