### ISSUE TITLE
[Question] Using tmux?

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#4284]
Most CLI work on a server is unfeasible without tmux, could it be added to the image or could I permanently add it for our servers?

**Comment by Vicente-Cheng** [comment]
Hi @xeruf
Please refer to https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only for installation of your packages.

Also, I thought maybe we could have tmux/screen package for CLI work more convenient.
WDYT?  cc @bk201, @guangbochen

**Comment by bk201** [comment]
+1 to ship it, it's handy when debugging.

**Comment by Vicente-Cheng** [comment]
The related PR: https://github.com/harvester/harvester-installer/pull/552
Should be involved with v1.2.0-rc5

**Comment by irishgordo** [comment]
This is excellent!
Thanks so much @Vicente-Cheng !

`tmux` offers such fantastic utility! I've been a long time fan!
This looks phenomenal in v1.2.0-rc5 :smile: :tada: :+1: :100: 

I'll go ahead and close this out :smile: 


https://github.com/harvester/harvester/assets/5370752/a993e66a-81a1-459a-9f73-dc38a4dc70f8
