### ISSUE TITLE
[BUG] 3 Node AirGap Upgrade from v1.1.2 -> v1.2.0-rc4 stuck in 'Images Preloaded'

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4288]
**Describe the bug**
AirGap Upgrade from v1.1.2 -> v1.2.0-rc4 seems to have 3 nodes all stuck in images preloaded state

**To Reproduce**
1. Create airgap 3 node v1.1.2 cluster
2. Create version.yaml
3. Begin upgrade

**Expected behavior**
Upgrade would pass images preloaded state

**Support bundle**
[supportbundle_b3d480e8-9ce0-4a8c-a0cd-a622c4ee72de_2023-07-20T22-50-24Z.zip](https://github.com/harvester/harvester/files/12114679/supportbundle_b3d480e8-9ce0-4a8c-a0cd-a622c4ee72de_2023-07-20T22-50-24Z.zip)

**Upgrade Log**
[hvst-upgrade-xwpj2-upgradelog-archive-2023-07-20T21-34-26Z.zip](https://github.com/harvester/harvester/files/12114680/hvst-upgrade-xwpj2-upgradelog-archive-2023-07-20T21-34-26Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2->v1.2.0-rc4
 - Underlying Infrastructure: qemu/kvm

**Additional context**
![Screenshot from 2023-07-20 12-45-06](https://github.com/harvester/harvester/assets/5370752/5baabe4a-0e13-49ec-a6fa-e29224aa5e96)
![Screenshot from 2023-07-20 14-34-12](https://github.com/harvester/harvester/assets/5370752/16494cb3-0a97-41af-b502-982a4e0badd0)

**Comment by bk201** [comment]
The upgrade passed the image preload stage and is now upgrading the system service. By checking the bundle it's waiting for grafana:
```
2023-07-20T21:41:40.730119891Z Waiting for deployment "rancher-monitoring-prometheus-adapter" rollout to finish: 0 of 1 updated replicas are available...
2023-07-20T21:42:12.719067102Z deployment "rancher-monitoring-prometheus-adapter" successfully rolled out
2023-07-20T21:42:12.908051598Z deployment "rancher-monitoring-kube-state-metrics" successfully rolled out
2023-07-20T21:42:13.074279014Z Waiting for deployment "rancher-monitoring-grafana" rollout to finish: 0 of 1 updated replicas are available...
2023-07-20T21:42:26.195694881Z deployment "rancher-monitoring-grafana" successfully rolled out
2023-07-20T21:42:26.446439521Z Waiting for 1 pods to be ready...
```

**Comment by bk201** [comment]
@irishgordo I see imagePullbackoff on many pods:
```
│ cattle-monitoring-system    prometheus-rancher-monitoring-prometheus-0                ●    2/3                0 ImagePullBackOff     10.52.0.139      harvester-node-0     3h50m          │
│ cattle-monitoring-system    rancher-monitoring-prometheus-node-exporter-d2lv2         ●    0/1                0 ImagePullBackOff     192.168.2.30     harvester-node-0     3h51m          │
│ cattle-system               rancher-79f468d8b6-czs5m                                  ●    0/1                0 ImagePullBackOff     10.52.0.92       harvester-node-0     4h33m          │
```
I guess it hits https://github.com/harvester/harvester/issues/4210.
Does this upgrade runs on ipxe-example without tuning disk size? I'll suggest use a bigger disk size first: https://github.com/harvester/ipxe-examples/pull/63

**Comment by irishgordo** [comment]
@bk201  - thanks for that info - definitely bumping up the bigger disk size was the issue :smile:  - I'll go ahead and close this out as I'm not able to reproduce after bumping up the disks size - :smile: :+1:
