### ISSUE TITLE
[Question] Harvester rke support

### ISSUE THREAD

**Issue by chifu1234** [harvester/harvester#429]
Hi Guys, is it (or in future) possible to stage a k8s cluster on harvester via rke ?

**Comment by gitlawr** [comment]
Why do you prefer rke to k3s in your use case?

**Comment by chifu1234** [comment]
I use rke because i deploy all of my k8s clusters with rancher/rancher via Vsphere. Now I woulk like to migrate from Vsphere to Harvester.  But as far as I know there is no docker-machine driver for harvester today.

**Comment by chifu1234** [comment]
@gitlawr  Do you have any news for me ? =)

**Comment by gitlawr** [comment]
The node driver stuff is irrelevant to RKE. It is done on the Rancher side. If I understand correctly your request is to have a Harvester node driver in Rancher

**Comment by chifu1234** [comment]
yes or kubevirt.

**Comment by chifu1234** [comment]
@gitlawr Do you have a roadmap for this implementation?

**Comment by gitlawr** [comment]
Hi Kevin, It's not on the radar at the moment.

**Comment by chifu1234** [comment]
https://github.com/rancher/rancher/issues/27065

**Comment by guangbochen** [comment]
link to https://github.com/rancher/harvester/issues/512
