### ISSUE TITLE
[BUG] 3 nodes upgrade to v1.2.0-rc4 stuck in node3 waiting reboot.

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4290]
**Describe the bug**

* When upgrade from v1.1.2 to v1.2.0-rc4, the process stuck in node 3 `waiting reboot` 

* And Node 3 display `cordened` with `Kubelet stopped posting node status'

  ![image](https://github.com/harvester/harvester/assets/29251855/1e2ab363-9001-4e33-be69-9821920f3873)

* Check node 3 console, it looks like can't join to the cluster
  ![image](https://github.com/harvester/harvester/assets/29251855/b8eaa716-6832-4a39-b856-f0e6fe59ed1d)

* Check the node status, node 3 display in NotReady
  ```
  node2:~ # kubectl get nodes
  NAME    STATUS                        ROLES                       AGE     VERSION
  node1   Ready                         control-plane,etcd,master   2d2h    v1.25.9+rke2r1
  node2   Ready                         control-plane,etcd,master   2d1h    v1.24.11+rke2r1
  node3   NotReady,SchedulingDisabled   control-plane,etcd,master   4h52m   v1.25.9+rke2r1
  ```

* Check the virtual machines are running
  ![image](https://github.com/harvester/harvester/assets/29251855/0c07d4b9-a0fd-4d0d-aac6-0be0c487df4f)

* Pods `rancher-78b5854fb7-qzf9r`, `harvester-7657f4bf9c-w6vkr` and `harvester-webhook-b4d659867-p5pwn` keep in `pending` state
![image](https://github.com/harvester/harvester/assets/29251855/accbf19a-5f16-4ae2-9538-8cf5f228476c)

* pre-drain and post-drain jobs completed on node 1 and node 3
```
node2:~ # kubectl get jobs -n harvester-system -l harvesterhci.io/upgradeComponent=node
NAME                                  COMPLETIONS   DURATION   AGE
hvst-upgrade-6lpxx-post-drain-node1   1/1           3m1s       3h1m
hvst-upgrade-6lpxx-post-drain-node3   1/1           2m7s       164m
hvst-upgrade-6lpxx-pre-drain-node1    1/1           12s        3h4m
hvst-upgrade-6lpxx-pre-drain-node3    1/1           3m35s      173m
```

* Network information on node 3
  ```
  node3:~ # ip a
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
      inet 127.0.0.1/8 scope host lo
         valid_lft forever preferred_lft forever
  2: enp179s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
      link/ether 00:1b:21:38:5c:74 brd ff:ff:ff:ff:ff:ff
  3: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP group default qlen 1000
      link/ether e4:54:e8:7c:f2:78 brd ff:ff:ff:ff:ff:ff
      altname enp0s31f6
  4: enp179s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
      link/ether 00:1b:21:38:5c:75 brd ff:ff:ff:ff:ff:ff
  5: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
      link/ether e4:54:e8:7c:f2:78 brd ff:ff:ff:ff:ff:ff
      inet 192.168.50.103/24 brd 192.168.50.255 scope global mgmt-br
         valid_lft forever preferred_lft forever
  6: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP group default qlen 1000
      link/ether e4:54:e8:7c:f2:78 brd ff:ff:ff:ff:ff:ff
  ```

**To Reproduce**

1. Steps to reproduce the behavior:
2. Prepare a four nodes v1.1.2 Harvester cluster
3. Create an external vlan network
4. Create two vms, one set external vlan and another use management network
5. Prepare offline upgrade to v1.2.0-rc4
6. Set the increase upgrade deadline
7. Monitor the upgrade process

**Expected behavior**

Should be able to complete the four nodes upgrade to v1.2.0-rc4 without hanging on the post-draining state of any node

**Support bundle**

[supportbundle_261f5541-a387-4a89-8a8d-5a3800a59441_2023-07-21T13-38-37Z.zip](https://github.com/harvester/harvester/files/12126691/supportbundle_261f5541-a387-4a89-8a8d-5a3800a59441_2023-07-21T13-38-37Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2 to v1.2.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes on bare machine

**Comment by bk201** [comment]
Check with David. Node3's IP change causes this. There are two DHCP server in the network.

The etcd member list:
```
18ba5cd9e5272a3e, started, node2-7804b1f1, https://192.168.50.102:2380, https://192.168.50.102:2379, false
2fb0c810ec24d217, started, node3-cbb52c99, https://192.168.50.79:2380, https://192.168.50.103:2379, false
9fdaf6a25119065e, started, node1-73520b48, https://192.168.50.101:2380, https://192.168.50.101:2379, false
```

etcd log on node1:
```
{"level":"warn","ts":"2023-07-24T07:39:26.320Z","caller":"rafthttp/snapshot_sender.go:102","msg":"failed to send database snapshot","snapshot-index":30658859,"remote-peer-id":"2fb0c810ec24d217","bytes":416082573,"size":"416 MB","error":"dial tcp 192.168.50.79:2380: connect: no route to host"}
{"level":"warn","ts":"2023-07-24T07:39:26.320Z","caller":"etcdserver/snapshot_merge.go:72","msg":"failed to send database snapshot to writer","size":"0 B","error":"meta 0 copy: io: read/write on closed pipe"}
```

But node3's IP change to `192.168.50.103`:
```
rancher@node3:~> ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp179s0f0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:38:5c:74 brd ff:ff:ff:ff:ff:ff
3: eno1: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP group default qlen 1000
    link/ether e4:54:e8:7c:f2:78 brd ff:ff:ff:ff:ff:ff
    altname enp0s31f6
4: enp179s0f1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:1b:21:38:5c:75 brd ff:ff:ff:ff:ff:ff
5: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether e4:54:e8:7c:f2:78 brd ff:ff:ff:ff:ff:ff
    inet 192.168.50.103/24 brd 192.168.50.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
```

**Comment by TachunLin** [comment]
This issue should be caused by during upgrade node 3 to reboot. The node 3 request IP address to another DHCP server which caused the leased IP address differ from the one assigned before upgrade. 
It should belongs to unstable environment setup. Thus close this issue. 
Appreciated for the check.
