### ISSUE TITLE
[Doc] Document harvester-csi-driver hostname requirements

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4291]
It is possible to configure a Harvester VM with a different hostname than its VM name, then install a Kubernetes distribution onto it, import it into Rancher, and install the harvester-csi-driver. For example, the cloud-init userdata could specify a hostname that is different from the VM name; the Terraform provider also allows users to specify a different hostname from the VM's name.

The trouble is, mounting volumes via the harvester-csi-driver will fail because the harvester-csi-driver will send the VM's _hostname_ to Harvester as a way of identifying itself and Harvester assumes this hostname matches the VM's name. So if the hostname is different from the VM name, the volume hotplug will fail to attach to the expected VM.

**Describe the solution you'd like**

Add a warning to the "Install CSI Driver Manually" section advising users against setting hostnames that are different from the Harvester VM's name.

**Comment by Martin-Weiss** [comment]
We really should fix the dependency on hostname instead of documenting this.. the CSI driver must use a unique identifyer and must not rely on hostname to be identical to VM name - just think about VM restore with different VM name etc..

**Comment by connorkuehl** [comment]
> We really should fix the dependency on hostname instead of documenting this.. the CSI driver must use a unique identifyer and must not rely on hostname to be identical to VM name - just think about VM restore with different VM name etc..

Sorry to have missed this!! I've filed an enhancement issue for fixing this, but I am going to proceed with the docs change since that will merge faster and at the very least might help readers avoid being bitten by this until the actual fix is made.

**Comment by connorkuehl** [comment]
![Screenshot 2023-08-16 at 10 56 03 AM](https://github.com/harvester/harvester/assets/5227338/7dbbdf7d-9f59-4518-9d2b-ca201fba236f)
