### ISSUE TITLE
[BUG] Can't delete a "Cordoned" host from the list of hosts

### ISSUE THREAD

**Issue by aleveille** [harvester/harvester#4292]
**Describe the bug**
Can't delete a "Cordoned" host from the list of hosts

**To Reproduce**
1. Set-up HA Harvester cluster with three nodes and add the Rancher integration
2. Wipe/destroy/lose a host
3. Remove the host from the list of hosts in Harvester (and don't remove it in Rancher)
4. Replace the host (reinstall the host using the same hostname and IP) and make it join the existing Harvester cluster
5. The host will be Cordoned as something prevents the node from successfully joining the Harvester cluster (something about the node already existing in an etcd)
6. In the Harvester UI, you can't delete that host. Regardless of whether you decide to reinstall the host using different hostname & IP, the host reference created from Step 4 will be impossible to remove from the UI.

**Expected behavior**
Being able to fully and properly remove a host from the list of hosts. Maybe "force" remove.

**Support bundle**
I'll provide the bundle securely upon request.

**Environment**
 - Harvester ISO version: 
 - 3 x baremetal with Dell PowerEdge R820

**Additional context**
I lost the raid array configuration following a pretty bad storm. I decided it was a good opportunity to re-configure the array (something I meant to do anyway) since https://github.com/harvester/harvester/issues/2665 seemed to suggest that it was possible to reinstall the first node/host of a cluster

**Comment by aleveille** [comment]
After having the physical host shut down overnight, the host finally disappeared from the UI. I can't say why it took 3+ hours, but it finally worked.

**Comment by aleveille** [comment]
As an added thought on this, it'd be really nice to have a "force delete" on `host` and `virtual machine` resources. It's not the first time I struggle to delete something.

**Comment by SlavikCA** [comment]
Same experience in version 1.4.0:
- I have 3 nodes cluster (2 nodes + witness)
- One node stopped working due to hardware issues
- I added new node
- Tried to delete non-existing node from UI, from CLI - nothing happens
- After few hours - non-existing node got deleted.
