### ISSUE TITLE
[ENHANCEMENT] Publish net-install ISO

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4295]
**Is your enhancement related to a problem? Please describe.**

Some users [encounter installation problems](https://github.com/harvester/harvester/issues/2651) when mounting Harvester ISO via BMC. The cause is image preloading is I/O intensive.
We can consider shipping a net-install ISO to let users skip the preloading-image stage.
The ISO is also suitable for users who are not willing to download a big ISO or burn the ISO to a double layer DVD.

**Describe the solution you'd like**

We can ship a net-install ISO without image tarballs since we already [publish the cluster-repo image](https://github.com/harvester/harvester/issues/2670).

**Describe alternatives you've considered**

A flag in the installation to skip the preloading stage can be a workaround.

**Additional context**

For such an ISO, we also need to consider if we want to support an upgrade with it.

**Comment by bk201** [comment]
Add release note: to mention the net-install ISO in the **Download -> ISO** section.

**Comment by lanfon72** [comment]
@bk201 document for network installation with PXE boot is required.
Otherwise users will hit the error: `'/var/lib/rancher/agent/image/rancherd-bootstrap-images-*.txt': No such file or directory` when using PXE boot with net-install ISO.

**Comment by bk201** [comment]
Thanks, before I have the doc PR ready please add `harvester.install.with_net_images=true` to the kernel parameters.

**Comment by lanfon72** [comment]
Move back to implement as the node installed from net-install ISO unable to join existing cluster.

The log from `journalctl -u rancher-system-agent.service -f`
![image](https://github.com/harvester/harvester/assets/5169694/bf2bef01-a816-47d2-93c0-570fbe702df5)

**Comment by bk201** [comment]
It's caused by dockerhub's rate limitation: https://docs.docker.com/docker-hub/download-rate-limit/
Will add this info to doc too.

**Comment by bk201** [comment]
Doc PR under review: https://github.com/harvester/docs/pull/516

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM 2 node**
* Harvester Version: **v1.3.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
**Case 1**
1. Install Harvester main node with net-iso via CUI
2. Install Harvester with net-install ISO via CUI to join the main node
3. Install Harvester with net-install ISO via PXE boot to join the main node
4. Install Harvester with normal ISO to join the main node
5. Perform Harvester API tests in https://github.com/harvester/tests/tree/main/harvester_e2e_tests

**Case 2**
1. Install Harvester main node with net-iso via PXE boot
2. Install Harvester with net-install ISO via CUI to join the main node
3. Install Harvester with net-install ISO via PXE boot to join the main node
4. Install Harvester with normal ISO to join the main node
5. Perform Harvester API tests in https://github.com/harvester/tests/tree/main/harvester_e2e_tests

**Case 3**
1. Install Harvester main node with normal ISO
2. Install Harvester with net-install ISO via CUI to join the main node
3. Install Harvester with net-install ISO via PXE boot to join the main node
4. Perform Harvester API tests in https://github.com/harvester/tests/tree/main/harvester_e2e_tests
