### ISSUE TITLE
[ENHANCEMENT] upgrade needs to handle eventrouter image bump in v1.2.0 rc upgrade path

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4296]
**Is your enhancement related to a problem? Please describe.**

With the PR https://github.com/harvester/harvester/pull/4251, the eventrouter image is bumped during the upgrade path of v112->v120. But for v120-rc1/2/3 to v120-rc4 or later, the image is not bumped.

**Describe the solution you'd like**

Add related processing to upgrade script.

**Describe alternatives you've considered**

**Additional context**

refer: https://github.com/harvester/harvester/blob/master/package/upgrade/upgrade_manifests.sh#L1217

**Comment by guangbochen** [comment]
we do not support upgrading from RC version to a stable version in any official release, so would prefer to just patch those image manually via kubectl.

**Comment by w13915984028** [comment]
When QA/DEV test via those none formal releases, this issue may be encountered.

We may keep this issue as an reference.

**Comment by w13915984028** [comment]
Close as not required in new releases.
