### ISSUE TITLE
[Doc] add document for *support-bundle-image* in settings

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4298]
**Is your doc request related to a problem? Please describe or add related issue ID.**
There is no document for `support-bundle-image` setting

**Describe the solution you'd like**
Add document for the setting to explain how to use it.

**Comment by bk201** [comment]
<img width="740" alt="Screenshot 2023-07-24 at 10 57 34 PM" src="https://github.com/harvester/harvester/assets/1691518/f67192d3-2382-4021-9612-e4d69928c318">

The doc can leverage the GUI setting page and might be a complement to the section: https://docs.harvesterhci.io/dev/troubleshooting/harvester#generate-a-support-bundle

**Comment by bk201** [comment]
Doc published: https://docs.harvesterhci.io/v1.3/advanced/index#support-bundle-image
cc @lanfon72
