### ISSUE TITLE
[BUG] rancher-monitoring addon's `Alertmanager` form can be edited from a "view" state on Harvester

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4299]
**Describe the bug**
Addon rancher-monitoring, when enabled via the index page, when viewing it (not editing config) the Alertmanager section's radio button can be toggled

**To Reproduce**
1. Goto Advanced Addons -> enable rancher-monitoring
2. After deploy successful, click into the rancher-monitoring addon, to view it
3. Navigate to the Alertmanager tab
4. The Alertmanager tab's radio button can be toggled from the "view" state

**Expected behavior**
Alertmanager's radio button to not be able to be toggled when not in "edit" mode of the addon. That it would be `disabled` much like the `Basic` tab on the rancher-monitoring addon behaves.

**Environment**
 - Harvester ISO version: v1.2.0-rc4 
 - Underlying Infrastructure: qemu/kvm
 
**Additional context**
![Screenshot from 2023-07-24 15-07-41](https://github.com/harvester/harvester/assets/5370752/5d047f64-4ee3-45d2-b8cf-d0655c35dd65)
![Screenshot from 2023-07-24 15-06-55](https://github.com/harvester/harvester/assets/5370752/8b821dcd-bbcc-4e0c-b30d-6c9fd6c8d304)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/019c3189-3f6e-4e41-8aa1-05eda80fa0f1)


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.2.0-rc4**
* **ui-source** Option: **External**

### Verify Steps
1. Install Harvester with any nodes
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/4299#issue-1819222420
