### ISSUE TITLE
UI websocket

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#43]
when add a new vm, state is not refresh

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/commit/fdc0c0c073092b028b5bcf906bf72e480570b167

**Comment by DoNotSayYes** [comment]
It still can be encountered that the state does not refresh when adding a new VM, can you help confirm it again @WuJun2016 
![image](https://user-images.githubusercontent.com/57614736/93453699-943a6480-f90c-11ea-9e3f-193b0bcb77e6.png)

**Comment by guangbochen** [comment]
close as it is resolved in the harvester-ui.

**Comment by WuJun2016** [comment]
Every once in a while, the frontend receives the following push. 
![image](https://user-images.githubusercontent.com/24985926/101456026-69413900-396e-11eb-9141-36f75e95b93f.png)

At this time, the frontend is actively subscribing, and always fails
![image](https://user-images.githubusercontent.com/24985926/101456416-f71d2400-396e-11eb-944b-2e92eb2f1dae.png)

**Comment by DoNotSayYes** [comment]
Unable to reproduce for the last few weeks.
