### ISSUE TITLE
[BUG] Incorrect storage size displayed in host detail page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#430]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5697937/104678159-c7a7c700-5725-11eb-91d9-bca58200ff2a.png)

The storage size from the API shows:
![image](https://user-images.githubusercontent.com/5697937/104678202-df7f4b00-5725-11eb-96ae-d523043e9306.png)

**To Reproduce**
1. Install Harvester to a server with a 1.8T disk.
2. Check in the UI.

**Environment:**
 - Harvester ISO version: v0.1.0
 - Installation Mode: ISO-mode
 - Underlying Infrastructure: Baremetal

**Comment by DoNotSayYes** [comment]
Validated on master-head

![image](https://user-images.githubusercontent.com/57614736/105289532-1d331680-5bf3-11eb-9f04-6ed1fdb63f0f.png)

![image](https://user-images.githubusercontent.com/57614736/105274702-aa1ca680-5bd8-11eb-8b82-d1993b14f5ea.png)
