### ISSUE TITLE
[ENHANCEMENT] VM backup with snapshot status report

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4303]
**Is your enhancement related to a problem? Please describe.**

We implement filesystem freeze/thaw for VM backup in https://github.com/harvester/harvester/pull/3976. However, in the current implementation, we only freeze the filesystem for a pre-defined period (1 second), regardless of the snapshot status from  CSI driver. This could lead the backup result to be non-deterministic with potential issue.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by connorkuehl** [comment]
Hi Webber,

I think https://github.com/harvester/harvester/issues/4098 includes this enhancement in its scope.

**Comment by bk201** [comment]
Close with https://github.com/harvester/harvester/issues/4098
