### ISSUE TITLE
[Enhancement] In seeder addon, update config needs about 2 minutes to reflect on UI. Is that expected?

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4304]
Please help to comment.
If it's not expected, should convert to bug.

1. Enable harvester-seeder addon
2. Enable Out-of-Band Access with wrong port 12345
   ![image](https://github.com/harvester/harvester/assets/2773781/b0e0e387-b6f2-415f-8905-6688c9bd3658)
3. Correct to right port 623 and save
   ![image](https://github.com/harvester/harvester/assets/2773781/9c2b0df9-b216-40eb-827e-6088f717f2ea)
4. It takes about 2 minutes to see the UI update
   ![image](https://github.com/harvester/harvester/assets/2773781/105623a2-28c6-418e-a387-728dc063eb74)

**Comment by ibrokethecloud** [comment]
## To test 
use v1.2-head image

* enable harvester-seeder addon
* define out-of-band access for a node with an invalid endpoint
* wait for the inventory check to fail, and failure condition to be populated
* edit node config, and update the out-of-band access to valid endpoint
* the failure condition should be removed quicker

**Comment by albinsun** [comment]
Hit #4387 during verifying. Need to wait it resolved first.

**Comment by albinsun** [comment]
Provide test result for `v1.2-57b26312-head`.
The time to see config take affect reduces to 1m (2m before), close as fixed.

## Environment
* Harvester
  * Version: `v1.2-57b26312-head`
  * Profile: QEMU/KVM, 1 node (24C/24G/1.6T)
  * **ui-source**: Auto


## Test Cases
> **Note** Click "►" to expand details.
1. <details open>
   <summary>
   Enable with wrong port (takes ~1m for error msg)
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/b9c9517b-f09d-41c4-b1f8-4500550927e5)
   </details> 

1. <details open>
   <summary>
   Update with correct port (takes ~1m for error msg gone)
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/2b3b74d9-da05-4c7e-88f5-52bf1a78d16e)
   </details>
