### ISSUE TITLE
[BUG] VM stuck in *Restoring* state

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4307]
### Describe the bug
Restoring snapshot to the (existing) VM, it will stuck in *Restoring* state if the VM was stopped by shell command.

![image](https://github.com/harvester/harvester/assets/5169694/45a31f43-8be1-4561-89ff-dc1b5bfee9d5)

### To Reproduce
1. Install Harvester with any nodes
2. Create an Image for VM creation
3. Create VM `vm1` and write some data
4. Take snapshot `vm1-s` for `vm1`
5. Stop `vm1` by executing command `sudo shutdown now`
6. Restore snapshot `vm1-s` to existing

### Expected behavior
VM should restored and started successfully

## Environment:
 - Harvester ISO version: **v1.2.0-rc4**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
- The bug could be resolved by restart the **Restoring** VM
- Cluster was upgraded from **v1.1.2**

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Steps
1. <details>
      <summary> Create an Image for VM creation
      </summary>
   
   focal-server-cloudimg-amd64.img
   ![image](https://github.com/harvester/harvester/assets/2773781/45a070fb-9383-4bb6-a748-fb7ded6b0d59)
   </details>


1. <details>
      <summary> Create VM <b>vm1</b> and write some data
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/798745b0-9281-4398-b26e-f1a42b4aa9b8)
   </details>


1. <details>
      <summary> Take snapshot <b>vm1-s</b> for <b>vm1</b>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/a45e2eef-c1a3-4879-9e9d-03fdd001ff24)
   </details>


1. <details>
      <summary> Stop <b>vm1</b> by executing command <code>sudo shutdown now</code>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/41ec6d4f-c977-4cee-a9d3-1118480a31d3)
   </details>


1. <details>
      <summary> Restore snapshot <b>vm1-s</b> to existing
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/b0ae0a48-40e1-4ad2-99aa-8f94c91d6a0a)
   ![image](https://github.com/harvester/harvester/assets/2773781/0bf05af9-7915-422f-b6e5-ea322abfe22e)
   ![image](https://github.com/harvester/harvester/assets/2773781/b7218fa8-7435-4c04-bd80-876c21838f1b)
   </details>


1. <details>
      <summary> VM should restored and started successfully, and data should still valid
      </summary>
   
      ![image](https://github.com/harvester/harvester/assets/2773781/829c94b5-881e-4ec2-9648-607ec9241153)
   </details>


## Note
1. <details>
      <summary> Can reproduce in <code>v1.1.2</code>, <b>vm1</b> <b>Restoring</b> over 10 mins.
      </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/b5a857ca-80bf-46ea-9aad-fe05726ac6a7)
      ![image](https://github.com/harvester/harvester/assets/2773781/db30feb2-ede1-4750-8a1b-9187ca1bfa68)
   </details>
