### ISSUE TITLE
[ENHANCEMENT] Add cattle-logging-system to default namespace of support-bundle

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4309]
**Is your enhancement related to a problem? Please describe.**

The `cattle-logging-system` is not added to support-bundle by default.

**Describe the solution you'd like**

Add it default namespace.

**Describe alternatives you've considered**

In Harvester WebUI, add `cattle-logging-system` namespace to settings->support-bundle namespace manually. 

**Additional context**

Observed in: https://github.com/harvester/harvester/issues/4225, did not find `cattle-logging-system` related information from the attached SB file.

**Comment by lanfon72** [comment]
Verified this improvement has been applied.

![image](https://github.com/harvester/harvester/assets/5169694/d244c903-d51c-42e1-8972-f4ed07c5104f)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2-4f8a9df2-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Generate Support Bundle
3. folder `cattle-logging-system` should be available in Support Bundle
