### ISSUE TITLE
[BUG] Can't upload a 6GB image to Harvester when in multi-cluster context, the Rancher has limitation

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4311]
**Describe the bug**

Can't upload a 6GB image to Harvester when in multi-cluster context, the Rancher has limitation

**To Reproduce**
1. Import  a Harvester v1.1.1 cluster into Rancher
2. Access this Harvester from Rancher
3. Create VM image via uploading local image file
4. For big files > 6GB size, the upload will fail, the Web browser has http error code 413

<img width="935" alt="image" src="https://github.com/harvester/harvester/assets/31133476/f676b225-a85b-4815-97ea-dfe95479d0d2">

backend POD has such error log:
>2023-07-18T10:58:39.908086486Z time="2023-07-18T10:58:39Z" level=error msg="Backing image data source failed to prepare the file, error message: timeout waiting for the datasource file processing begin" backingImageDataSource=default-image-n6hw5 controller=longhorn-backing-image-data-source diskUUID=5f881c48-28cc-49c7-acf4-50b5b1a9ca7e node=harvester02 nodeID=harvester02 parameters="map[]" sourceType=upload

5. By contrast, when user access Harvester directly (via Harvester VIP), the uploading does not fail.

**Expected behavior**

No failure.

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

This issue is different with: https://github.com/harvester/harvester/issues/3450 

LH ever had such an issue: https://github.com/longhorn/longhorn/issues/2937 and is referenced.

@WebberHuang1118 did following test:
>I tried to build Rancher with RKE2 from scratch and imported Harvester into Rancher.
If I upload a big image from multi-cluster UI, it would get a status code 413,
because the RKE2 ingress nginx default setting for client_max_body_size is only 1m
(specific to RKE2)
$ kubectl -n kube-system exec --stdin --tty rke2-ingress-nginx-controller-gxqkp -- bash
www-data@rke2-ingress-nginx-controller-gxqkp:/etc/nginx> cat nginx.conf | grep client_max_body_size 
                       client_max_body_size                   1m; 
                       client_max_body_size                   1m; 
                       client_max_body_size                   21M;
if I change the RKE2 ingress nginx client_max_body_sizeto a bigger size (e.q. 10250m), the VM image could be uploaded successfully

**Comment by bk201** [comment]
@WebberHuang1118 will help update the Harvester doc first. The doc should include dev, v1.2, and v1.1 versions.

**Comment by WebberHuang1118** [comment]
PR for document update is merged https://github.com/harvester/docs/pull/513.
