### ISSUE TITLE
[BUG] VMs fall into a cycle of Running -> Paused

### ISSUE THREAD

**Issue by sam-ulrich1** [harvester/harvester#4316]
**Describe the bug**
After a time, certain VMs fall into a perpetual cycle of Running->Paused. Sometimes they show an IOError sometimes not. The most common IOError when shown is a volume that is mounted does not have enough space but upon inspection of Longhorn shows none of the volumes are near the storage limit and all show healthy with multiple replicas.

**To Reproduce**
I have no idea. It seems randomly consistent

**Expected behavior**
VMs don't pause for seemingly no reason

**Support bundle**
I've shared the bundle on slack but if it is needed by someone else let me know

**Environment**
 - Harvester ISO version: v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 Baremetal on Supermicro 1U (can't remember the model)

**Comment by starbops** [comment]
Hi @sam-ulrich1, it would be nice if you could attach the SB file here. Any chance you got screenshots when the issue happened?

Thank you!

**Comment by sam-ulrich1** [comment]
https://drive.google.com/file/d/10wPWAXqq7f91BBzVWPvEOFDKkpWzMvx0/view?usp=sharing
It's too big to upload here

**Comment by sam-ulrich1** [comment]
@starbops

**Comment by sam-ulrich1** [comment]
Additional Info:
The issue happens seemingly randomly on nodes that host a volume provisioned by the internal harvester longhorn but supplied to an RKE2 cluster running on top of the harvester vms. The RKE2 cluster uses harvester as the cloud provider in this situation. Nodes that do not host volumes for the RKE2 cluster never have this issue.

Unfortunately, I did not know I needed to expand the scope of the support bundle so that the support bundle will not show the namespace that contains the failing VMs. I will update the ticket with a new support bundle when it happens again. It normally happens every 2-4 days so shouldn't be long

Rancher Version: 2.7.4
RKE2 Version: v1.25.10 +rke2r1

**Comment by ibrokethecloud** [comment]
please define the extra namespaces in the `support-bundle-namespaces` setting

![image](https://github.com/harvester/harvester/assets/19664014/39c8346b-b39d-4741-8be2-e95cdd75ed32)

**Comment by sam-ulrich1** [comment]
Updated with the namespace where the failure is happening
https://drive.google.com/file/d/1ZYzws_aUhBlqTfjcrBd2JiigMAwPHLg6/view?usp=sharing
@ibrokethecloud

**Comment by ibrokethecloud** [comment]
the VM paused is running on hm9.

The kernel seems to indicate a few messages about link status changing..

```
Aug 16 17:10:26 hm9 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Aug 16 17:26:41 hm9 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Aug 16 17:35:54 hm9 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
Aug 16 17:48:29 hm9 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

This seems to correlate with some iscsi logout/login messages for a pvc in use by vm:

```
Aug 03 03:36:32 hm9 iscsid[25737]: iscsid: Connection280:0 to [target: iqn.2019-10.io.longhorn:pvc-13a285e4-4d6a-4deb-99bf-e1f35e9a1e20, portal: 10.52.8.250,3260] through [iface: default] is operational now
Aug 16 17:35:43 hm9 iscsid[25737]: iscsid: Connection280:0 to [target: iqn.2019-10.io.longhorn:pvc-13a285e4-4d6a-4deb-99bf-e1f35e9a1e20, portal: 10.52.8.250,3260] through [iface: default] is shutdown.
Aug 16 17:35:51 hm9 iscsid[25737]: iscsid: Connection294:0 to [target: iqn.2019-10.io.longhorn:pvc-13a285e4-4d6a-4deb-99bf-e1f35e9a1e20, portal: 10.52.8.250,3260] through [iface: default] is operational now
```

I suspect the network may not be stable which may be causing the volumes to be unreachable followed by the IO error in launcher pod, which results VM being paused.

**Comment by sam-ulrich1** [comment]
We will review the HW this weekend to better understand what might be causing it. The net HW is slightly more complicated than most since it's running a qsfp+ card so it could be a bad card, driver malfunction or some other funky config

**Comment by sam-ulrich1** [comment]
Closing since this seems to be resolved with HW repairs. Thanks so much for the help in both this case and helping me understand the support bundle
