### ISSUE TITLE
[BUG] After two nodes Harvester upgrade to v1.2.0-rc4, all virtual machines are in shutdown (off) state

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4317]
**Describe the bug**

After we successfully upgrade from v1.1.2 to v1.2.0-rc4, all virtual machines are in `Off` state
(Except the RKE1 guest cluster VM)

  ![image](https://github.com/harvester/harvester/assets/29251855/2968bf05-a1f6-438f-93dd-69b2ac6b432d)

* Before upgrade, one VM in running and anther in off state, after upgrade all vms keep in off state
* This would probably affect some running service. 

**To Reproduce**
1. Create two VM, one in running and another in off state
2. Provision a RKE1 cluster from external Rancher
3. Create backup and snapshot for VMs
4. Upgrade to v1.2.0-rc4
5. Check the VM state after the upgrade complete

**Expected behavior**

All VMs should keep it's original status after the upgrade complete. 

**Support bundle**

[supportbundle_fb7d82fb-6347-4d68-ad9f-923d4996b5f1_2023-07-26T13-58-39Z.zip](https://github.com/harvester/harvester/files/12173394/supportbundle_fb7d82fb-6347-4d68-ad9f-923d4996b5f1_2023-07-26T13-58-39Z.zip)

**Upgrade log**

[hvst-upgrade-bc7g6-upgradelog-archive-2023-07-26T13-26-18Z.zip](https://github.com/harvester/harvester/files/12173332/hvst-upgrade-bc7g6-upgradelog-archive-2023-07-26T13-26-18Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2 to v1.2.0-rc4 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Two nodes

**Comment by bk201** [comment]
The VM 'running` is pined to node1. It will be shut down during the upgrade (non-migratable):
```
      nodeSelector:
        kubernetes.io/hostname: node1
```

As an enhancement plan, we may show non-migratable VMs to users before an upgrade.

**Comment by TachunLin** [comment]
Thanks for the check. I created an enhancement ticket #4321 to suggest notifying user which types of virtual machines would be shutdown during upgrade.
