### ISSUE TITLE
[BUG] Logging and monitoring is in error state after upgraded to v1.2.0-rc4

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4318]
### Describe the bug
Grafana and Prometheus start working after upgraded completed (and several minutes), but dashboard will still showing `...is in error state`

![image](https://github.com/harvester/harvester/assets/5169694/fc823bf0-86f1-48cb-8309-6b1d1aeac885)
![image](https://github.com/harvester/harvester/assets/5169694/ffdc04d9-9143-496e-a572-12ce32639f26)
![image](https://github.com/harvester/harvester/assets/5169694/ff488491-1ef9-423a-a5ec-77c0d2c06d7f)
![image](https://github.com/harvester/harvester/assets/5169694/1ef76443-f7e4-4aaf-88a3-d4786472996d)

### To Reproduce
1. Install Harvester with 3 nodes
2. Create an image for VM creation
3. Create VLAN `vlan`
4. Create Storage Class `sc1`
5. Create Volume `v1` by storage class `sc1`
6. Create `vm1` with mgmt, vlan, and existing volume `vol1`
7. Manipulate `vm1` then take backup and snapshot
    - Write data into both image disk and existing volume
8. Clone volume `vol1` into `vol2`
9. Create `vm2` with mgmt and vlan NICs
10. Manipulate `vm2` then stop it
    - Attach `vol2`
    - Write data into both image disk and `vol2`
11. Take backup and snapshot for `vm2`
12. Import Harvester into Rancher 2.7.4
13. Create RKE1 and RKE2 cluster (3 nodes)
    - RKE2: `v1.24.14+rke2r2` with Harvester Cloud Provider
    - RKE1: `v1.25.11-rancher1-1`  with Harvester Cloud Provider
14. Install Harvester Cloud Provider and CSI Driver
15. Create Nginx deployment with new Harvester PVC
16. Create DHCP load balancer service for Nginx deployment
17. Upgrade Rancher to 2.7.5
18. Upgrade Harvester

### Expected behavior
Addons should show correct state.

## Environment:
 - Harvester ISO version: **v1.1.2** -> **v1.2.0-rc4**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
[supportbundle_c5d86a24-e00e-4d0c-ac3f-5f40ed9c5e2a_2023-07-26T14-48-11Z.zip](https://github.com/harvester/harvester/files/12173964/supportbundle_c5d86a24-e00e-4d0c-ac3f-5f40ed9c5e2a_2023-07-26T14-48-11Z.zip)

**Comment by lanfon72** [comment]
The error message could be eliminated by disable then enable those addons.

**Comment by irishgordo** [comment]
:thinking: hmm, seems similar to:
- https://github.com/harvester/harvester/issues/4306
- https://github.com/harvester/harvester/issues/4125

**Comment by lanfon72** [comment]
🤔 should be the same of #4306 as it is fresh new cluster

**Comment by w13915984028** [comment]
confirm this issue #4318, is due to the same root cause as observed in #4306

we are working to avoid touching the Rancher reserved condition `Failed` in `addon` context.

**Comment by lanfon72** [comment]
Close as this is duplicated of #4306
