### ISSUE TITLE
[ENHANCEMENT] Prompt to indicate user which types of VM would be shutdown during upgrade

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4321]
**Is your enhancement related to a problem? Please describe.**

Requirement found in issue https://github.com/harvester/harvester/issues/4317#issuecomment-1652865172

When we create vm and set node selector to pin vm to specific node. 

After we complete upgrade Harvester to latest version, the non-migratable vm would be shutdown. 
![image](https://github.com/harvester/harvester/assets/29251855/3c2763eb-f929-4228-9e0c-4862733160ba)

**Describe the solution you'd like**

We can provide a prompt to inform user which types of vm would be shutdown during upgrade. (e.g non-migratable)
At the time before we start upgrade.  To notify user to take care of these VMs.  

**Describe alternatives you've considered**

It's the kubernetes design. Not yet have suitable alternatives.

**Comment by starbops** [comment]
Hi @TachunLin, could you help verify that the requirement is fully covered by #4984 (original issue: #3019)? Thank you.

**Comment by TachunLin** [comment]
Hi @starbops,
I think the requirement list in this ticket can be well covered in #4984. 

With webhook pre-ugrade check message: 
```
There are non-migratable VMs that need to be shutoff before the upgrade: <namespace>/<vm name>
```

Thus I think we could close the enhancement request in this ticket. Thank you for bringing the enhancement.
