### ISSUE TITLE
[BUG] tempate cloud-init not shown during VM creation

### ISSUE THREAD

**Issue by swill** [harvester/harvester#433]
**Describe the bug**
If you create a Template which includes a cloud-init script and then create a VM from that template, the cloud-init which you specified in the template is not shown in the cloud-init section of the create VM form interface.  Interestingly, if you don't specify anything in the VM create cloud-init section, the template cloud-init configuration is applied to the VM.  That is a bit confusing.

**To Reproduce**
1. Go to Template and create a new Template
2. When creating the template, specify some configuration in the cloud-init section
![image](https://user-images.githubusercontent.com/13644/104774685-1dd83280-5745-11eb-93b2-d733dd84a023.png)
3. Create a VM from the newly created template
4. Notice that the cloud-init information specified in the template is not visible in the cloud-init section of the VM create form
![image](https://user-images.githubusercontent.com/13644/104774740-35afb680-5745-11eb-8108-ce3eeb490584.png)

**Expected behavior**
When creating a VM from a template which has cloud-init details specified in the template, the VM create form should be populated with the cloud-init details from the template.

Interestingly, even though the configuration is not visible in the cloud-init form during the VM create process, the configuration that was defined in the template is applied to the newly created VM.  That is pretty confusing if you didn't create the template.

**Environment:**
 - Harvester ISO version: v0.1.0
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare Metal

**Comment by swill** [comment]
As I dig deeper into things, I suspect this is actually related to this code: https://github.com/rancher/harvester-ui

I just clicked on the "create an issue" button in the UI and I ended up here.  Should this get closed and I move the issue to the other repo?

**Comment by guangbochen** [comment]
it is ok to submit a UI issue against this repo, thanks.

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/105314812-58384880-5bf9-11eb-85f4-85d9d9827668.png)

**Comment by swill** [comment]
It appears that you are validating on an Edit and not a Create?  Did you also validate on a Create?  If it is not populated on the Create then the user will likely try to specify something and I am not sure what will happen then.  Does the template get overwritten?
