### ISSUE TITLE
[BUG] Harvester 1.1.2 OS stuck on boot with BOSS-S1 hardware RAID

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4334]
**Describe the bug**

The bootup procedure stuck on the "Welcome to GRUB!" screen for 30+ minutes. The node has a BOSS-S1 hardware RAID-card.
 
**To Reproduce**
1. Install Harvester v1.1.2.
2. Reboot
3. The OS hangs on "Welcome to GRUB!" for 30+ minutes.

**Expected behavior**

The OS should boot immediately.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

- Related issue: https://github.com/harvester/harvester/issues/2115
- It's caused by a new search in the `/etc/cos/grub.cfg` file:
  ```
  # Load custom config file
  set custom="/grubcustom"
  search --no-floppy --file --set=custom_blk "${custom}"
  ```

**Comment by bk201** [comment]
The workaround is:
- If the system manages to boot into the OS: After booting, create a grubcustom file and try reboot
  ```
  grub2-editenv /oem/grubcustom create
  ```
- If it takes too long to boot, boot the live ISO and mount the OEM partition to create the file.
  ```
  mkdir /tmp/oem
  mount -L COS_OEM /tmp/oem
  grub2-editenv /tmp/oem/grubcustom create
  ls -l /tmp/oem/grubcustom
  umount /tmp/oem
  ```

**Comment by bk201** [comment]
The search is removed in 1.2.0, but we need to confirm again.

**Comment by masteryyh** [comment]
Tested with Dell R6515 with a BOSS-S1 RAID card and v1.2.0-rc5 seems not stuck on boot menu.

**Comment by bk201** [comment]
@masteryyh Thanks. Move the issue to v1.1.3.

**Comment by bk201** [comment]
@masteryyh I think we also need to fix the upgrade path (1.1.2 -> 1.1.3). Like: https://github.com/harvester/harvester/blob/f77ef49db2cea24d934ef0a6db957e225d2b6f46/package/upgrade/upgrade_node.sh#L576-L582

**Comment by TachunLin** [comment]
According to the above comment, move the issue to implement for investigation.

**Comment by TachunLin** [comment]
Verifying **fixed** on `v1.1-340486a3-head` (11/20). Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Installation path: Can boot Harvester on BOSS-S1 RAID machine without hanging $~~$</summary>

  1. On the Dell power edge R6535 with BOSS-S1 RAID hardware
           ![image](https://github.com/harvester/harvester/assets/29251855/793d8e19-0e2a-44f2-ad29-16080622f4b1)
  2. Can boot into GRUB page without hanging 
           ![image](https://github.com/harvester/harvester/assets/29251855/9ff73053-9303-420e-8ed2-87e63ae58155)
  3. Can successfully provision Harvester cluster 
          ![image](https://github.com/harvester/harvester/assets/29251855/273683f0-a896-4103-8dc3-19ff4af5db68)
          ![image](https://github.com/harvester/harvester/assets/29251855/caa3d912-5480-4f62-b6ca-9d9c60866233)
 </details> 

<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade path: /oem/grubcustom exists after upgrade complete $~~$</summary>

  1. After upgrade from v1.1.2 to v1.1.3-head, the `/oem/grubcustom` file exists
      ```
      harv112-113:~ # ls /oem/grubcustom
      /oem/grubcustom
      ```
  2. Can reboot Harvester correctly
    ![image](https://github.com/harvester/harvester/assets/29251855/cb818411-788b-43bf-a1a7-14284dd4ce9d)

 </details> 

### Test Information
* Test Environment: Single nodes harvester on equinix bare machines
* Harvester version: v1.1-340486a3-head (23/11/20)

### Verify Steps
<details><summary>Harvester installation path</summary>

  1. Access Equinix platform console
  2. Get the API key
  3. Prepare a VM machine on cloud can be accessed by Equinix platform
  4. Use harvester-equinix-terraform to provision Harvester 
  5. Copy the out-of-band console information
  6. ssh to the console page 
  7. Wait for the installation finish and booting the GRUB!
  8 Check can provision Harvester correctly

</details>

<details><summary>Harvester upgrade path</summary>

  1. Upgrade Harvester from v1.1.2 to v1.1.3
  2. After upgrade complete, check the `/oem/grubcustom` file exists
  3. Reboot the machine

</details>

**Comment by megabreit** [comment]
This issue is back in 1.2.1... including the workaround to create /oem/grubcustom

**Comment by bk201** [comment]
> * Install Harvester v1.1.2.
> * Reboot
> * The OS hangs on "Welcome to GRUB!" for 30+ minutes.

@megabreit Track with a new ticket: https://github.com/harvester/harvester/issues/4784
