### ISSUE TITLE
[BUG] OpenStack VM Import Stuck At 99% on `Images`

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4338]
**Describe the bug**
Seems to be downloading two separate images when VM only has one root disk in OpenStack.
Image seems to be stuck at 99% - other image is finished - might be duplicate images?

**To Reproduce**
1. Have an OpenStack Instance Available
1. Build VM Import Source: https://docs.harvesterhci.io/v1.1/advanced/vmimport/#sources
1. Create an Instance on OpenStack, mapping the VirtualMachineImport CRD settings to the right places
1. Create the CRD against the Harvester Cluster
1. Two Images, download, 1 hangs at 99% the other finishes, both represent the disk size of the VM in openStack

**Expected behavior**
Image to not have issues, not produce duplicates in UI / backing-image-manager?
Not be stuck at 99%

**Support bundle**
[supportbundle_c1fbb825-5d97-4361-9e1c-69bd3e9fca32_2023-07-31T02-08-58Z.zip](https://github.com/harvester/harvester/files/12210873/supportbundle_c1fbb825-5d97-4361-9e1c-69bd3e9fca32_2023-07-31T02-08-58Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc3
 - OpenStack Version: Zed
 - Underlying Infrastructure: BareMetal, for Harvester - VM for OpenStack

**Additional context**
![Screenshot from 2023-07-30 19-07-49](https://github.com/harvester/harvester/assets/5370752/18781e9c-a8c6-4005-b3bd-313e6171882d)
![Screenshot from 2023-07-30 19-10-06](https://github.com/harvester/harvester/assets/5370752/e9a79ca0-25bb-4516-b5c6-2b35799f92ad)
![Screenshot from 2023-07-30 18-35-02](https://github.com/harvester/harvester/assets/5370752/d25b46e5-832d-43c7-9f10-e00fce8fd63c)
![Screenshot from 2023-07-30 18-34-18](https://github.com/harvester/harvester/assets/5370752/923a4427-7711-4f2f-856e-1b4c3d49b360)

Additionally, the VM Import Controller Addon, when Enabled was Configured with the following resource loadout:
![Screenshot from 2023-07-30 19-35-10](https://github.com/harvester/harvester/assets/5370752/cd28723a-7932-4a3c-9fde-83a0f2c5b8e5)

**Comment by ibrokethecloud** [comment]
looks like duplicate images. clearing the first image results in image upload to be completed.

are we able to please re-run this test?

**Comment by irishgordo** [comment]
@ibrokethecloud re-running the same thing was encountered after:
- wiping the image
- removing the vm, w/ vol
- removing the CRD

This seems to also carry over to multiple disks - if VM from OpenStack Zed has multiple disks tied to it.

![Screenshot from 2023-07-31 13-58-19](https://github.com/harvester/harvester/assets/5370752/934d9374-11af-4838-bc0b-05d0e05af592)
![Screenshot from 2023-07-31 13-57-41](https://github.com/harvester/harvester/assets/5370752/a3425228-5190-45ff-b0e2-7b9bcce6c4e1)


Support Bundle:
[supportbundle_c1fbb825-5d97-4361-9e1c-69bd3e9fca32_2023-07-31T21-00-53Z.zip](https://github.com/harvester/harvester/files/12222244/supportbundle_c1fbb825-5d97-4361-9e1c-69bd3e9fca32_2023-07-31T21-00-53Z.zip)

**Comment by ibrokethecloud** [comment]
fix is available with vm-import-controller image available in rc5.

**Comment by irishgordo** [comment]
Tested on rc5 - this looks great!
Thanks for the fix @ibrokethecloud ! :smile: :+1: 
I'll go ahead and close this out.
![Screenshot from 2023-08-08 15-29-42](https://github.com/harvester/harvester/assets/5370752/c05d8c87-0673-4d40-a154-a5b0815c1cbe)
![Screenshot from 2023-08-08 15-22-57](https://github.com/harvester/harvester/assets/5370752/1bfbe598-056e-4453-88ab-bed34ed7865f)

**Comment by ne0YT** [comment]
@irishgordo 
hey there
maybe you can update the docs or give me a clear tutorial on how to do this VM-import?
