### ISSUE TITLE
[BUG] Text-form target port not working in Load balancer in RKE2 cluster with Harvester node driver

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4339]
**Describe the bug**
Load balancer in RKE2 cluster with Harvester node driver, text-form target port not working (but numerical form works)
Note that field tip shows both nuerical and text form are supported (eg. 80 or http)
![image](https://github.com/harvester/harvester/assets/2773781/fad39433-ad17-433a-a0e8-2d78b203e60d)

**To Reproduce**
1. Setup Harvester cluster
2. Setup Rancher and import Harvester
4. Create a RKE2 cluster with Harvester node driver
5. Create a deployment `test-nginx` using image `nginx:latest`
   Pod lable `mykey:myvalue`
   ![image](https://github.com/harvester/tests/assets/2773781/fd46ca30-bdb3-439d-a222-8579e595e409)
6. Create a Load Balancer `lb-dhcp-http` with target port "http" 
   * Should config selector with `mykey:myvalue` to select `test-ningx`
   * Config target port in text/protocol form (http)
   ![image](https://github.com/harvester/harvester/assets/2773781/09379004-9d78-4655-9681-b04ea9839104)
7. Browse `lb-dhcp-http`, should see nginx welcome page $~~$ :x: $\color{red}{\textsf{but works with nuerical form port (80)}}$
   ![image](https://github.com/harvester/harvester/assets/2773781/fcaefc0c-91a1-466f-8fa2-36ae332f4064)
   Worked LB with numerical port
   ![image](https://github.com/harvester/harvester/assets/2773781/a1868bd5-713a-45a7-8bd7-19799486d46f)

**Expected behavior**
Both nuerical and text form target port should work

**Support bundle**
[supportbundle_2aae0f9f-fd47-4a70-bf52-49aa596d4506_2023-07-31T07-43-59Z.zip](https://github.com/harvester/harvester/files/12212646/supportbundle_2aae0f9f-fd47-4a70-bf52-49aa596d4506_2023-07-31T07-43-59Z.zip)

**Environment**
* Harvester
  * version: `v1.2.0-rc4`
  * profile: QEMU/KVM, 3 nodes (8C/16G/250G)
  * **ui-source**: Auto
* Rancher `v2.7.5`

**Comment by albinsun** [comment]
FYI, also hit with Harvester `v1.2.0-rc5` + Rancher `v2.7.6-rc2`.

**Comment by guangbochen** [comment]
Sorry for the late reply. Can you please help if you have defined the appropriate port protocol when creating the Nginx workload? This works for me with the following steps:
1. add Nginx workload and add svc port 80 with name `http`
   <img width="1067" alt="image" src="https://github.com/harvester/harvester/assets/4569037/7e7580d9-2c2c-4694-a9e2-8664fc4ca60c">
1. create svc and define the target port with `http`
    <img width="1295" alt="image" src="https://github.com/harvester/harvester/assets/4569037/26cc3d36-67fa-44d9-91b2-19249f110a7c">
<img width="1017" alt="image" src="https://github.com/harvester/harvester/assets/4569037/617882bb-4612-46a1-bf94-63d73f7fe7c5">

**Comment by albinsun** [comment]
Provide test result with explicitly define service to expose in networking when create nginx deployment.

Thanks for comment.

Functions works fine, close as not an issue.

![image](https://github.com/harvester/harvester/assets/2773781/ba150653-dd66-4901-b66b-1a63c7fc9bac)


## Environment
* Harvester
  * Version: `v1.2.0-rc5`
  * Profile: QEMU/KVM, single node (8C/16G/500G)
  * **ui-source**: Auto
* Rancher
  * Version: `v2.7.6-rc4`
  * Profile: Docker

## Test Cases
> **Note** Click "►" to expand details.
### DHCP
1. <details>
   <summary>
   Number type Port
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/ae444d8c-659b-4725-b9a3-b69c1d43ff64)
   </details> 

1. <details>
   <summary>
   Text type Port
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/7c6614db-921b-4460-8140-3c571e4fb3c9)
   </details> 

### IP Pool
1. <details>
   <summary>
   Number type Port
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/1d29fa96-e67f-4874-9357-6c41693cedc3)
   </details> 

1. <details>
   <summary>
   Text type Port
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/a15eece7-91bd-4665-9ec1-366930da928b)
   </details>
