### ISSUE TITLE
[BUG] cuda program is unable to run on a VM with GPU passthrough

### ISSUE THREAD

**Issue by hsinhoyeh** [harvester/harvester#4344]
**Describe the bug**

#### prerequsite
** gpu testing setup:
1. install docker: https://github.com/FootprintAI/multikf/blob/main/hack/docker-install/install-docker-linux.sh
2. install cuda driver: https://github.com/FootprintAI/multikf/blob/main/hack/gpu/get-cudadriver.sh
3. install nvidia container runtime: https://github.com/FootprintAI/multikf/blob/main/hack/gpu/nvidia-container-runtime.sh
4. run https://github.com/wilicc/gpu-burn
** when gpu-burn is working, the program would return after few seconds
** when gpu-burn is not working, it would eat one of cpu core and never returned.

#### hardware configuration
my configuration has two machines, machine A is with Intel 13700k (w/natively integrated graphics) and Machine B is with AMD 5900x (w/o natively integrated graphics). Both machines are attached to external graphics (RTX 3090).
OS: ubuntu 2004

test scenario with natively:
1. when running machine B directly on top of ubuntu, running gpu-burn test is working. (this only shows the graphic devices is working properly)

#### test scenario w/harvester:
2. when attaching machines A and B to the harvester cluster, creating a VM(w/ GPU passthrough) located in machine A and running gpu-burn testing is working.
3. same as 1. but creating a VM(w/ GPU passthrough) located in machine B, gpu-burn is NOT working

**To Reproduce**
as described above.

**Expected behavior**
scenario 3 should working as expected.

**Support bundle**

[supportbundle_007cc9b3-1d94-4f5c-9c28-db80782d499b_2023-07-28T15-47-08Z.zip](https://github.com/harvester/harvester/files/12213145/supportbundle_007cc9b3-1d94-4f5c-9c28-db80782d499b_2023-07-28T15-47-08Z.zip)

**Environment**
 - Harvester ISO version: 1.12
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by hsinhoyeh** [comment]
finally, I got this machine B working. 

Previously, the RTX 3090 on machine B has plugged an HDMI with a monitor, and this caused the PCI passthrough not to work as expected (I guess the ownership of the graphic card is on the host as it is plugged mode).
After I remove the HMDI wire (and also disable/enable PCI passthrough), machine B is not plugged any with the 3090 graphic card. the GPU on VM is working as expected.

so I guess if you need a monitor for the machine with an integrated graphic chip, better come up with another one.

**Comment by ibrokethecloud** [comment]
closing based on user feedback.
