### ISSUE TITLE
[ENHANCEMENT] Required fields are not checked when saving (`via yaml save`)

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4350]
**Is your enhancement related to a problem? Please describe.**

Required fields are not checked when saving (`via yaml save`).

When we creates a new Harvester cluster, they can create a cluster without a network (from the GUI, via yaml save) which eventually breaks the whole cluster, according to their information it keeps creating and deleting nodes.

Steps to reproduce: Create new cluster, `cloud credentials` -> `Select RKE2 and Harvester node driver` -> `Type in the cluster name` -> `Switch to YAML view and click on Create`. There is nothing that prevents it.

**Describe the solution you'd like**

Save via yaml should also validate.

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Tested the enhancement applied on Harvester `v1.3.0-rc1` with Rancher `v.2.9-head`[^1] but not available on Rancher `v2.7.9` and `v2.8-head` [^2].

I can't confirm Rancher `v2.9.0` will ship with Harvester `v1.3.0`, so move this back to **Review**.

[^1]: Docker Image: `rancher/rancher@sha256:22b31c9b820ab88965f547a1d4a462856e8cea03084857eebb89d18064112a70`
[^2]: Docker Image: `rancher/rancher@sha256:0352298855f0452b651614a0f0dec4ed8708da3121ea9b325a56e8ca47218be7`

**Comment by bk201** [comment]
@torchiaf Is this in v1.3.0-rc3? Thanks.

**Comment by lanfon72** [comment]
Tested not applied on Harvester `v1.3.0-rc3` with Rancher `v2.8.1`

**Comment by bk201** [comment]
According to @torchiaf, the change is merged in https://github.com/rancher/dashboard/pull/10073 (target master code and supposed to be in dev-2.9). This needs to be backported to v2.7 and v2.8.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.3.0-rc4**
* **ui-source** Option: **Auto**
* Rancher Versions:
    - **v2.7-bd0bb772b60a447d352789b3d7c4368ffe50eecf-head**[^1]
    - **v2.8-19cfbb81afd2689dc055e03193264f9616707922-head**[^2]

### Verify Steps
1. Install Harvester with any nodes
2. Import Harvester into Rancher
3. Create RKE2 cluster and don't fill in any data, click `Edit as YAML`
4. Error message should prompted, and user should not able to switch to yaml editor


[^1]: Docker image: `rancher/rancher@sha256:3deedb983e5f80bfc154e20c7d434ffd74a51d8a121c314abbff7b2393f1d027`
[^2]: Docker image: `rancher/rancher@sha256:e273d4fa864ae3c26511ee613ba516e19aee84bd6634ac936e146ce2d4143b12`

**Comment by IsaSih** [comment]
Can issue https://github.com/rancher/dashboard/issues/10605 be closed too?
