### ISSUE TITLE
[BUG] The bridge MTU is not changed

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#4353]
**Describe the bug**

To set the MTU to 9000, but the Harvester is defaulting to 1500.
![image](https://github.com/harvester/harvester/assets/7421463/85f68640-202a-45a4-a0b6-f16de49ccf98)
![image](https://github.com/harvester/harvester/assets/7421463/62f13cbc-e9e2-46b6-8227-cd51aac85dcf)

**To Reproduce**
1. Create a cluster network and add a network config where the MTU of the uplink is set as 9000.
2. Create a VM network under this cluster network.
3. Create a VM using the VM network.
4. Check the related bridge. You will see the MTU of the bridge is still 1500 but the bond's is 9000.

**Expected behavior**

The bridge MTU should be the configured value.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by guangbochen** [comment]
@yaocw2020 please help create a new enhancement issue to track the proposed design changes in v1.3.0(may consider backporting to v1.2.1)

**Comment by yaocw2020** [comment]
> @yaocw2020 please help create a new enhancement issue to track the proposed design changes in v1.3.0(may consider backporting to v1.2.1)

https://github.com/harvester/harvester/issues/4355

**Comment by yaocw2020** [comment]
Workaround:

Case1: select the cluster network as the storage network.
1. stop all VMs since we need to update the storage network
2. backup the storage-network setting
   ```
   kubectl get settings.harvesterhci.io storage-network -oyaml > storage-setting.yaml
   ```
3. check its NAD name and save the related NAD to a yaml file. The NAD name is like `storagenetwork-xxxxx`.
   ```
   kubectl get network-attachment-definition -n harvester-system | grep storagenetwork
   kubectl get network-attachment-definition -n harvester-system $nad -o yaml > storage-nad.yaml
   ```
4. disable storage network
   a. wait for the longhorn-system's instannce-manager-e ,  instannce-manager-r and backing image pods to be ready after restart
   b. wait for the pod on cattle-monitoring-system  to be ready
   c. the MTU should be reset back to 9000 and you can check it on the host
5. modify the file storage-nad.yaml. Add the MTU to the spec.config and apply the file. The value will be like:
   ```
   '{"cniVersion":"0.3.1","type":"bridge","dns":{},"bridge":"test-br","mtu":9000,"promiscMode":true,"vlan":1,"ipam":{"type":"whereabouts","range":"192.168.70.0/24"}}
   ```
   ```
   kubectl apply -f storage-nad.yaml
   ```
6. delete the fields `metadata.creationTimestamp`,`metadata.generation`,`metadata.resourceVersion`,`metadata.uid` and `status` in storage-setting.yaml. Then apply storage-setting.yaml.
   ```
   kubectl apply -f storage-setting.yaml
   ```
7. wait for the longhorn-system and cattle-monitoring-system pods are restarted successfully, and check the host MTU again by `ip a| grep storage`

Case2: The cluster network is only used for VMs
1. Stop all the VMs.
2. Modify all the VM networks under the cluster network to add MTU value in the `spec.config` filed.
3. Restart all the VMs.

**Comment by albinsun** [comment]
Tested in `v1.2.0-rc5`, close as fixed.

> **Warning**
> Test do not cover 1.1.3 backport since not merge yet.
> Trace in https://github.com/harvester/harvester/issues/4364

## Environment
* Harvester
  * Version: `v1.2.0-rc5`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/250G)
  * **ui-source**: Auto


## Test Cases
> **Note** Click "►" to expand details.
1. <details>
   <summary>
   Create a cluster network and network config uplink w/ customized MTU.
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/6a927081-3652-4f7f-b521-a8ce377cec3c)
   </details> 


1. <details>
   <summary>
   Create a VM network (VLAN & Untagged) under this cluster network.
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   * VLAN 1 & Untagged
     ![image](https://github.com/harvester/harvester/assets/2773781/9e7595d5-110a-460d-8a8e-584be68ef248)
   </details> 


1. <details>
   <summary>
   Create vm1/vm2 using the VLAN/Untagged network.
   ${~~~\color{green}\textsf{V}}$
   </summary>
   
   * vm1
     ![image](https://github.com/harvester/harvester/assets/2773781/26608771-6285-47f9-aab6-a8e4b6486f88)
   * vm2
     ![image](https://github.com/harvester/harvester/assets/2773781/0901affb-6ef9-40dc-8d62-2de81b6f2d17)
   </details> 


1. <details>
   <summary>
   Check the MTU of the bridge should be the customized value
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   * vm1
     ![image](https://github.com/harvester/harvester/assets/2773781/f5aaff80-aa69-440d-b5d9-83f3304ba6d5)
   * vm2
     ![image](https://github.com/harvester/harvester/assets/2773781/77de22da-3607-4a4d-b607-1b63acfd42b0)
   </details>
