### ISSUE TITLE
[FEATURE]add debug mode to the harvester

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#436]
**Is your feature request related to a problem? Please describe.**

currently, the debug mode configuration is missing in the harvester.

**Describe the solution you'd like**

add debug mode to the harvester config

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by guangbochen** [comment]
1. user is able to enable and view the debug logs via set env `HARVESTER_DEBUG: true`.
2. user is able to view golang profiling with `http://server_url:6060/debug/pprof/`

**Comment by DoNotSayYes** [comment]
Validated case 1 on master-head, added the variable `HARVESTER_DEBUG: true` to the harvester, the debug log is available
![image](https://user-images.githubusercontent.com/57614736/105831985-56f48a80-6002-11eb-8adb-afd56a5d9855.png)

**Comment by guangbochen** [comment]
**Validation steps:**
After the harvester pod is up & running, users can either run `kubectl port-forwad $harvester_pod 9060:6060` and access via localhost:9060 to check it or manually expose port 6060 via a service.

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/109269788-fdbd8800-7847-11eb-915a-892c0661b182.png)
