### ISSUE TITLE
[ENHANCEMENT] More fine-grain checks before applying the storage network setting

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4363]
**Is your enhancement related to a problem? Please describe.**

When users try to update the storage network setting, it is required that all the VMs and Pods that use Longhorn volumes be shut down/stopped. If users stop the VMs from the Harvester dashboard, the underlying VirtualMachineInstance CRs and their corresponding `virt-launcher` Pods are removed so that the alternation request can pass [the validation in the setting webhook](https://github.com/harvester/harvester/blob/a3ee4dcb103286bb2eb6e468259aecd757871a46/pkg/webhook/resources/setting/validator.go#L834). However if users shut down the VMs from within their OSes with commands such as `shutdown`, the VirtualMahcineInstance CRs and the `virt-launcher` Pods remain on the Harvester cluster.

```
# After shutting down the VM named "test"
$ kubectl get vms test
NAME   AGE   STATUS    READY
test   18h   Stopped   False

# The VMI shouldn't exist according to the storage network alternation criterion
$ kubectl get vmis -l harvesterhci.io/vmName=test
NAME   AGE    PHASE       IP    NODENAME   READY
test   163m   Succeeded         node-1     False

$ kubectl get po -l vm.kubevirt.io/name=test
NAME                       READY   STATUS      RESTARTS   AGE
virt-launcher-test-n2kbm   0/1     Completed   0          163m
```

The VM page shows the message "virt-launcher pod is terminating," which also confuses users who already shut down the VM:

<img width="421" alt="image" src="https://github.com/harvester/harvester/assets/1827717/3d395ea4-4327-4696-9571-5a22e5a3aba9">

Though the behavior is expected from KubeVirt's point of view, it is relatively complex for Harvester users to understand the reason why they're still prohibited from updating the storage network setting.

<img width="840" alt="image" src="https://github.com/harvester/harvester/assets/1827717/edb32a24-73c0-4835-994b-51be69eb15fd">

The original objective is to make sure all the Longhorn volumes are detached. It does not matter if the VMs are shut down from the dashboard/API or within the OSes. In both cases, the volumes are detached, and we should be able to apply the new storage network setting.

**Describe the solution you'd like**

Instead of the rudimentary check against the number of VirtualMachineInstance CRs, we may want to check the VirtualMachine's status.

Maybe we can just examine the Longhorn volumes and ensure they are detached.

**Describe alternatives you've considered**

To work around this, simply removing the VMI CRs and their corresponding `virt-launcher` Pods does not help. We need to change the `runStrategy` from `RerunOnFailure` to `Halted` from the dashboard for every VMs that have already shut down from within the OS.

<img width="1006" alt="image" src="https://github.com/harvester/harvester/assets/1827717/801dfae9-e6a9-4af7-b9ea-e8e0ca9e85fa">

This is achievable from the command line, too. Just edit the VirtualMachine CR's `.spec.runStrategy`.

**Additional context**

Discussion thread on the Slack channel:
https://rancher-users.slack.com/archives/C01GKHKAG0K/p1690804156010279

**Comment by WebberHuang1118** [comment]
The storage network webhook issue is solved by #4886.


> The VM page shows the message "virt-launcher pod is terminating," which also confuses users who already shut down the VM:
> 
> <img width="421" alt="image" src="https://github.com/harvester/harvester/assets/1827717/3d395ea4-4327-4696-9571-5a22e5a3aba9">
> 
And check with master-head (`09f3ca172fc1dc1ce7cc4af840d32888f3365a79`), the frontend issue is no longer observed.
