### ISSUE TITLE
[ENHANCEMENT] bump vmdp driver version

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4365]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**
Need to bump the VMDP driver version to the latest one.

**Describe alternatives you've considered**
Bump VMDP driver to the current latest version [v2.5.4.2](https://github.com/SUSE/vmdp/releases/tag/v2.5.4.2)

**Additional context**
Refer to: https://www.suse.com/lifecycle#product-suse-linux-enterprise-virtual-machine-driver-pack

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/harvester/harvester/assets/5169694/8da3761f-4e4e-4890-9a6f-a017f16482d8)


Test Information
----
* Environment: **baremetal DL360G9 3 nodes**
* Harvester Version: **v1.2.0-rc5**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard, navigate to Advanced/Templates
3. View `windows-iso-image-base-version`
4. In Volume tab, The container **virtio-container-disk** should use `vmdp:2.5.4.2`
