### ISSUE TITLE
[BUG] Error message cpu, memory is required

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#4368]
**Describe the bug**
when try to create a new VM I got the error message cpu, memory required, in the yaml file both are null. When I edit the yaml file the vm is created, but in the vm view from harvester cpu is -

![Screenshot_20230803_110552](https://github.com/harvester/harvester/assets/85644625/be65edce-f678-4b62-b5cc-067b9ed8f6fd)

[supportbundle_67b96262-7790-4def-a014-6bb678af87bf_2023-08-03T09-17-34Z.zip](https://github.com/harvester/harvester/files/12249106/supportbundle_67b96262-7790-4def-a014-6bb678af87bf_2023-08-03T09-17-34Z.zip)

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with HP Z4 G4):
 - single Host
 - 16 cores, 32 GB memory

**Comment by WuJun2016** [comment]
@jrlittlefoot64  Can you provide steps to reproduce?  What browser was used?   Are you using the arrows to set cpu and memory?

**Comment by jrlittlefoot64** [comment]
@WuJun2016  the error is with firefox, I try it now with chrome and all is ok! Yes I do it with arrows to set cpu and memory. I think we can close this issue

**Comment by WuJun2016** [comment]
ok,  this issue is due to a limitation of firefox, we have an [issue](https://github.com/harvester/harvester/issues/4179) tracking the fix and we expect to fix it in the next release.

I'm closing the issue.

**Comment by WuJun2016** [comment]
duplicate with https://github.com/harvester/harvester/issues/4179.  close
