### ISSUE TITLE
[BUG] VM stuck at resizing

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4371]
**Describe the bug** / **To Reproduce**
I have a Windows VM with 50GB of Storage.
I stopped the VM and did a resize operation using the Harvester GUI to resize the disk to 100GB.
The disk is not resized even though I waited for a week now.

**Expected behavior**
The disk is done resizing after some time.

**Support bundle**
It failed to download the support-bundle.

**Environment**
 - Harvester ISO version: 1.1.1

**Comment by bk201** [comment]
@ne0YT Can you [log in to Longhorn GUI](https://docs.harvesterhci.io/v1.1/troubleshooting/harvester#access-embedded-rancher-and-longhorn-dashboards) and check if the volume is resized correctly?
Can you also check Windows disk manager to see if the disk is resized?
IIRC, the filesystem resize inside a VM relies on cloud-init. If the guest doesn't have it, it won't resize automatically.

**Comment by ne0YT** [comment]
@bk201 
I cannot check Windows disk manager as I cannot start the vm currently as it will always tell me it's still resizing.

it's not resized in longhorn:
![image](https://github.com/harvester/harvester/assets/97364807/ceb21d35-5b62-4c66-b4fe-5eb32e3de814)

**Comment by ne0YT** [comment]
![image](https://github.com/harvester/harvester/assets/97364807/0314f211-543d-45ea-ad07-4c78724c55b7)

**Comment by bk201** [comment]
> Harvester ISO version: 1.1.1

@ne0YT Just to check again, are you using 1.1.1?

**Comment by ne0YT** [comment]
> > Harvester ISO version: 1.1.1
> 
> @ne0YT Just to check again, are you using 1.1.1?

yes

**Comment by ne0YT** [comment]
> @bk201 I cannot check Windows disk manager as I cannot start the vm currently as it will always tell me it's still resizing.
> 
> it's not resized in longhorn: ![image](https://user-images.githubusercontent.com/97364807/258085499-ceb21d35-5b62-4c66-b4fe-5eb32e3de814.png)

I'm really wondering how the actual size is bigger than the size

**Comment by bk201** [comment]
> I'm really wondering how the actual size is bigger than the size

It could be caused by snapshot (sometimes it's Longhorn's system snapshot). Due to the copy-on-write design, the actual size may be greater than the volume size.

@WebberHuang1118 Can you help take a look at this issue, iirc we got the resize feature since 1.1.2 (https://github.com/harvester/harvester/issues/2810).

**Comment by WebberHuang1118** [comment]
Hi @ne0YT,

Maybe you specified a size larger than Longhorn's capacity during the expansion.

You could check with `kubectl describe persistentvolumeclaims <pvc name>`, and see if there is a similar message as following:
![volume_expand](https://github.com/harvester/harvester/assets/19387129/48bb3a55-8a8a-402a-9e02-64e5f0431549)

In order to have a larger volume,  it could be achieved by increasing Longhron [Storage Over Provisioning Percentage Setting](https://longhorn.io/docs/1.3.2/references/settings/#storage-over-provisioning-percentage) via `<Harvester Management IP>/dashboard/c/local/ -> Longhorn -> Longhorn UI`. If the allowed storage is enough, the volume expansion should restart automatically.

Since this increases the over-provision threshold, please be aware of the actual storage sufficiency.

BTW, Harvester officially supports expanding VM volume from Harvester 1.1.2, it should provide a better function checking and completeness.

Thanks

**Comment by ne0YT** [comment]
@WebberHuang1118 
output of the command:
```
Error from server (NotFound): persistentvolumeclaims "pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe" not found
```
I copied the name from longhorn GUI

I will upgrade now either way. But it's an air-gapped system.
so I need to get the version .yaml file,
those urls didnt work for me, maybe you can share me the working one?
https://releases.rancher.com/harvester/1.1.2/version.yaml
https://releases.rancher.com/harvester/release-harvester-v1.1.2/version.yaml

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 output of the command:
> 
> ```
> Error from server (NotFound): persistentvolumeclaims "pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe" not found
> ```
> 
> I copied the name from longhorn GUI
> 

The pvc name could be obtained from the volume page of Harvester GUI, Longhron GUI lists the `persistent volume`  name not `persistent volume claim`.


> I will upgrade now either way. But it's an air-gapped system. so I need to get the version .yaml file, those urls didnt work for me, maybe you can share me the working one? https://releases.rancher.com/harvester/1.1.2/version.yaml https://releases.rancher.com/harvester/release-harvester-v1.1.2/version.yaml

Please refer to https://github.com/harvester/harvester/releases for complete release information, and [here](https://releases.rancher.com/harvester/v1.1.2/version.yaml) is the version.yaml for Harvester v1.1.2.

Thanks.

**Comment by ne0YT** [comment]
@WebberHuang1118 
```
Name:          REDACTED
Namespace:     default
StorageClass:  harvester-longhorn
Status:        Bound
Volume:        pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe
Labels:        <none>
Annotations:   harvesterhci.io/owned-by: [{"schema":"kubevirt.io.virtualmachine","refs":["default/sabern-alarm"]}]
               pv.kubernetes.io/bind-completed: yes
               pv.kubernetes.io/bound-by-controller: yes
               volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
               volume.kubernetes.io/storage-provisioner: driver.longhorn.io
Finalizers:    [kubernetes.io/pvc-protection provisioner.storage.kubernetes.io/cloning-protection]
Capacity:      32Gi
Access Modes:  RWX
VolumeMode:    Block
DataSource:
  Kind:   PersistentVolumeClaim
  Name:   REDACTED-rootdisk-vy6d5
Used By:  <none>
Conditions:
  Type       Status  LastProbeTime                     LastTransitionTime                Reason  Message
  ----       ------  -----------------                 ------------------                ------  -------
  Resizing   True    Mon, 01 Jan 0001 00:00:00 +0000   Mon, 07 Aug 2023 07:30:23 +0000
Events:
  Type    Reason    Age                    From                                 Message
  ----    ------    ----                   ----                                 -------
  Normal  Resizing  28s (x14902 over 17d)  external-resizer driver.longhorn.io  External resizer is resizing volume pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe
```

**Comment by WebberHuang1118** [comment]
Please provide the support bundle, thanks

**Comment by ne0YT** [comment]
@WebberHuang1118 can I send it somewhere outside of github?

**Comment by WebberHuang1118** [comment]
@ne0YT github is suitable for our tracking,

If it doesn't work for you, 
maybe you could detail the steps, we would try to reproduce it on our site.

btw, I found your volume should be cloned from another one? Thanks.

**Comment by ne0YT** [comment]
I wanted to create a clone after some time as it just never resized. but I canceled the clone later.
the support bundle is 38MB. github allows me to upload only 25MB here.

**Comment by ne0YT** [comment]
@WebberHuang1118 where can I send the support bundle it is 38MB. github allows me to upload only 25MB here.

**Comment by WebberHuang1118** [comment]
@ne0YT 
https://github.com/harvester/harvester/issues/4371#issuecomment-1670900278 
so you cloned a new volume from the volume under resizing, and cancel the clone operation?

https://github.com/harvester/harvester/issues/4371#issuecomment-1667351634
it looks like the new volume was cloned from origin one.

Please provide your steps as detailed as possible, thanks.

**Comment by ne0YT** [comment]
@WebberHuang1118 
so you cloned a new volume from the volume under resizing, and cancel the clone operation? -> exactly!

is there any place I can send the support bundle?

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 so you cloned a new volume from the volume under resizing, and cancel the clone operation? -> exactly!

Please provide the describe of the original resizing pvc rather than the clone one, and also the detailed steps, it could give us more information.

> 
> is there any place I can send the support bundle?

If possible, you may have a network space for us to download. Or you can split the bundle into small ones, and provide the method to merge them back (please make sure it works on Linux), thanks.

**Comment by ne0YT** [comment]
@WebberHuang1118
The Support Bundle is here:
https://transfer.sh/FHCchnR57n/supportbundle_1d6d1171-a39f-45c0-8b38-1f5172e23967_2023-08-08T16-21-12Z.zip

Please provide the describe of the original resizing pvc rather than the clone one, and also the detailed steps, it could give us more information.
->
I shut down the VM and changed the size of the disk and saved. that's it.

**Comment by WebberHuang1118** [comment]
@ne0YT 
I found the pvc under resizing should be `sabern-alarm-rootdisk-rpx79`
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    harvesterhci.io/owned-by: '[{"schema":"kubevirt.io.virtualmachine","refs":["default/sabern-alarm"]}]'
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    sim.harvesterhci.io/creationTimestamp: "2023-04-12T09:40:18Z"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2023-04-12T09:40:18Z"
  finalizers:
  - kubernetes.io/pvc-protection
  - provisioner.storage.kubernetes.io/cloning-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:harvesterhci.io/owned-by: {}
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:sim.harvesterhci.io/creationTimestamp: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
          f:volume.kubernetes.io/storage-provisioner: {}
        f:finalizers:
          .: {}
          v:"kubernetes.io/pvc-protection": {}
          v:"provisioner.storage.kubernetes.io/cloning-protection": {}
      f:spec:
        f:accessModes: {}
        f:dataSource: {}
        f:dataSourceRef: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
        f:volumeName: {}
    manager: support-bundle-kit
    operation: Update
    time: "2023-08-14T03:18:40Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:conditions:
          .: {}
          k:{"type":"Resizing"}:
            .: {}
            f:lastProbeTime: {}
            f:lastTransitionTime: {}
            f:status: {}
            f:type: {}
        f:phase: {}
    manager: support-bundle-kit
    operation: Update
    subresource: status
    time: "2023-08-14T03:18:41Z"
  name: sabern-alarm-rootdisk-rpx79
  namespace: default
  resourceVersion: "1424"
  uid: f6f1852b-67ff-4849-abe2-c3ae50b3340d
spec:
  accessModes:
  - ReadWriteMany
  dataSource:
    apiGroup: null
    kind: PersistentVolumeClaim
    name: win11remote-rootdisk-vy6d5
  resources:
    requests:
      storage: 101Gi
  storageClassName: harvester-longhorn
  volumeMode: Block
  volumeName: pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 32Gi
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-08-08T16:25:27Z"
    status: "True"
    type: Resizing
  phase: Bound

```
And according to the logs from csi-resizer pod `csi-resizer-76fdffd797-ltkwr`, we could found such information
```
.....................
.....................
2023-08-08T16:25:27.194594643Z E0808 16:25:27.194548       1 controller.go:282] Error syncing PVC: resize volume "pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe" by resizer "driver.longhorn.io" failed: rpc error: code = OutOfRange desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to expand volume pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe: error while CheckReplicasSizeExpansion for volume pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe: cannot schedule 74088185856 more bytes to disk 1e1263e7-caad-4d5a-8adb-54ddf90ae767 with &{StorageAvailable:156657254400 StorageMaximum:294259032064 StorageReserved:88277709619 StorageScheduled:366145961984 OverProvisioningPercentage:200 MinimalAvailablePercentage:25}] from [http://longhorn-backend:9500/v1/volumes/pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe?action=expand]
2023-08-08T16:25:27.194626775Z I0808 16:25:27.194588       1 event.go:282] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"default", Name:"sabern-alarm-rootdisk-rpx79", UID:"4c617a34-2e35-4e1e-9359-d93b9a871bfe", APIVersion:"v1", ResourceVersion:"174338385", FieldPath:""}): type: 'Warning' reason: 'VolumeResizeFailed' resize volume "pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe" by resizer "driver.longhorn.io" failed: rpc error: code = OutOfRange desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to expand volume pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe: error while CheckReplicasSizeExpansion for volume pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe: cannot schedule 74088185856 more bytes to disk 1e1263e7-caad-4d5a-8adb-54ddf90ae767 with &{StorageAvailable:156657254400 StorageMaximum:294259032064 StorageReserved:88277709619 StorageScheduled:366145961984 OverProvisioningPercentage:200 MinimalAvailablePercentage:25}] from [http://longhorn-backend:9500/v1/volumes/pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe?action=expand]
```
This means you specified a size larger than Longhorn's capacity during the expansion.

For the disk Longhorn tries to schedule replica:
`StorageMaximum:294259032064 StorageReserved:88277709619 OverProvisioningPercentage:200`
So you can schedule a total of `411962644890B` Longhorn volumes ((294259032064 - 88277709619)*200%)

`cannot schedule 74088185856 more bytes and StorageScheduled:366145961984`
you already scheduled 366145961984B and tried to schedule 74088185856B more,
however, '(366145961984 + 74088185856B) > 411962644890B',
that's why Longhorn couldn't successfully expand the volume.

As I mentioned in https://github.com/harvester/harvester/issues/4371#issuecomment-1665090981,
please set the **Storage Over Provisioning Percentage** properly,
according to https://longhorn.io/docs/1.4.3/references/settings/#storage-over-provisioning-percentage and https://longhorn.io/docs/1.4.3/volumes-and-nodes/multidisk/#configuration.

Besides, since you already scheduled replicas more than the actual storage size, please be aware of the actual storage sufficiency.

Thanks

**Comment by ne0YT** [comment]
@WebberHuang1118 
Do I always need to reconfigure the Storage Over Provisioning Percentage ?
I thought it's a HCI system calculating what's needed on it's own smh :)

storage looks like this in the Dashboard:
![image](https://github.com/harvester/harvester/assets/97364807/8f305d47-4dfc-402f-a2de-e4b8a6658325)

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 Do I always need to reconfigure the Storage Over Provisioning Percentage ? I thought it's a HCI system calculating what's needed on it's own smh :)
> 
> storage looks like this in the Dashboard: ![image](https://user-images.githubusercontent.com/97364807/260401403-8f305d47-4dfc-402f-a2de-e4b8a6658325.png)

It reveals the data are actually written to storage, not related to the volumes' size already claimed.

According to https://longhorn.io/docs/1.4.3/references/settings/#storage-over-provisioning-percentage,
**Storage Over Provisioning Percentage** is a global setting, you only have to change it once specified a size larger than Longhorn's capacity.

IMHO, the user perhaps should be aware of the claimed volumes' size compared to real storage situations.

Although the Longhorn volume is thin-provisioned, the storage capacity is still limited.
Even the Storage Over Provisioning Percentage could be dynamically adjusted, if users doesn't check this part, the application still can face I/O error as storage is exhausted.

**Comment by ne0YT** [comment]
@WebberHuang1118 
I don't see how we should have this problem already?!
![image](https://github.com/harvester/harvester/assets/97364807/278933e0-2797-462f-addf-a83271d2e58e)

Those are all our volumes! and from images it's a total of less than 8GB.

291 GB is not 200% of 1'500 GB

**Comment by WebberHuang1118** [comment]
@ne0YT 
```
kubectl get pvc -o wide
NAMESPACE                  NAME                                                                                             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS           AGE     VOLUMEMODE
cattle-monitoring-system   alertmanager-rancher-monitoring-alertmanager-db-alertmanager-rancher-monitoring-alertmanager-0   Bound    pvc-8983bacb-2dd9-4a3d-ab8b-ff0c12a580fd   5Gi        RWO            harvester-longhorn     124d    Filesystem
cattle-monitoring-system   prometheus-rancher-monitoring-prometheus-db-prometheus-rancher-monitoring-prometheus-0           Bound    pvc-e97105f2-e6f4-4fed-9f12-64ec73fbd11b   50Gi       RWO            harvester-longhorn     124d    Filesystem
cattle-monitoring-system   rancher-monitoring-grafana                                                                       Bound    pvc-b9754376-23e5-4f8e-8c27-32c9ae0418c6   2Gi        RWO            harvester-longhorn     124d    Filesystem
default                    anotherbernremote-cdrom-disk-kql6l                                                               Bound    pvc-cb8b2624-4a92-49ec-b8c4-740ff207efb3   20Gi       RWX            longhorn-image-nw8cq   6d21h   Block
default                    anotherbernremote-rootdisk-31vzp                                                                 Bound    pvc-b5bbaf6e-2d08-4416-81ef-74bfccf9b849   60Gi       RWX            harvester-longhorn     6d21h   Block
default                    innova-rootdisk-baumf                                                                            Bound    pvc-1e7a24e7-889a-4fa8-9016-2d9d7cd00c45   50Gi       RWX            harvester-longhorn     111d    Block
default                    innova2-rootdisk-tt7t7                                                                           Bound    pvc-2133fc4c-78ee-421f-b60d-c3c26f01bf35   50Gi       RWX            harvester-longhorn     111d    Block
default                    sabern-alarm-rootdisk-rpx79                                                                      Bound    pvc-4c617a34-2e35-4e1e-9359-d93b9a871bfe   32Gi       RWX            harvester-longhorn     124d    Block
default                    sabern-alarmucs-rootdisk-3asqa                                                                   Bound    pvc-ca88ab7d-0c2f-4329-9a83-2b58c1203888   50Gi       RWX            harvester-longhorn     123d    Block
default                    win11remote-rootdisk-fwg8d                                                                       Bound    pvc-b12e9167-69fd-48b7-ba6e-890700c3a11d   32Gi       RWX            harvester-longhorn     123d    Block
```
the expanding size is not included, and there is a certain reserved space.

**Comment by ne0YT** [comment]
> 

when I add all those disks I see 351Gi. how can it be that my 1'500Gi over three nodes is not enough?
shouldn't I be able to use around 1000Gi?

**Comment by WebberHuang1118** [comment]
No, Longhorn has a replica design for high availability.

**Comment by ne0YT** [comment]
> No, Longhorn has a replica design for high availability.

so you tell me it uses a HA-setting which doesnt support to use even a thrid of the storage of my 3node cluster?
I think nearly 2/3 should be possible while having HA of one host failing

**Comment by WebberHuang1118** [comment]
Not exactly, users could customize replica policies through [StorageClass](https://docs.harvesterhci.io/v1.1/advanced/storageclass). The default replicas count is three.

**Comment by ne0YT** [comment]
after being able to cancel the stuck update, it started to work again.

**Comment by WebberHuang1118** [comment]
> after being able to cancel the stuck update, it started to work again.

@ne0YT 
Do you mean cancel resizing after changing **Storage Over Provisioning Percentage**?

**Comment by ne0YT** [comment]
@WebberHuang1118 
No
I didn't change any settings but deleted the update job which sat at 0% downloading on all three hosts.
After that it was able to resize the VM.
What's weird is that it never finished before I started the update as a way to fix the issue.
