### ISSUE TITLE
[BUG] Fail to enable Out-of-Band Access on host

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4387]
## Description
Successful enabling harvester-seeder addon, but fail to enable on node. 

## Environment
* Harvester
  * Version: `v1.2.0-rc5`
  * Profile: QEMU/KVM, 2 nodes (24C/128G/1.5T)
  * **ui-source**: Auto

## To Reproduce
1. Login as `admin` 
2. Go to "Advanced" -> "Addon" -> "harvester-seeder" -> Enable
   ![image](https://github.com/harvester/harvester/assets/2773781/6d2b87eb-ed64-4b2b-b3ae-84e21fc6bec9)
3. Go to "Hosts" -> select host -> "Edit Config" -> "Out-of-Band Access" -> "Enabled" -> "Save"
   ${~~~\color{red}\textsf{X, Error "Cannot read properties of undefined (reading 'linkFor')"}}$
   ![image](https://github.com/harvester/harvester/assets/2773781/1e23698e-4f67-4d35-9b54-7250d4415b79)

## Expected Behavior
With `harvester-seeder` addon enabled, Out-of-Band Access should be able to enable on node.

## Support Bundle
[supportbundle_FailToEnableOOBA_2023-08-07T06-43-47Z.zip](https://github.com/harvester/harvester/files/12272931/supportbundle_FailToEnableOOBA_2023-08-07T06-43-47Z.zip)

**Comment by n313893254** [comment]
I have added a banner to fixed the issues, but I also found another trick issue: The `/v1/harvester/subscribe` WebSocket sometimes can not get `metal.harvesterhci.io.inventory` of `resource.create` message, which will make my changes stuck in "Waiting for "inventories.metal.harvesterhci.io" to be ready". But sometimes I can get the message from WebSocket, here are my recordings:

This recording works as expected

https://github.com/harvester/harvester/assets/18737885/4c5c1e29-7a85-45fe-ad46-c73ee629df36

This recording only receives a message from `/v1/subscribe`

https://github.com/harvester/harvester/assets/18737885/339be3ce-c6c3-4a49-8a9d-59602f404446

This recording can not receive a message both from `/v1/subscribe` and `/v1/harvester/subscribe`. But the PCI device work as expected.


https://github.com/harvester/harvester/assets/18737885/e0552bd9-728a-4aa4-aea3-8dd9e6d1c128


Reproduce Steps:

- Install a v1.2.0-rc5 Harvester
- Login and change the ui-index to my private ui-index: https://harvester-dev.oss-cn-hangzhou.aliyuncs.com/bot-dashboard/n313893254-fix-seeder/index.html (optional, if not replace, the error will show as https://github.com/harvester/harvester/issues/4387#issue-1838795500)
- Take a snapshot for this Harvester (optional, easy to debug)
- Go to addons and enable harvester-seeder
- Check the WebSocket message or host detail page
- Restore the snapshot if you need to reproduce it again (optional)

**Comment by albinsun** [comment]
Hi @n313893254 ,

Per discussed, enablement works fine in `v1.2.0-rc4` and have this issue since `v1.2.0-rc5` after fresh install, or more precisely, user first time enable harvester-seeder addon.
Perhaps we can check whether there is any modification about websocket in between.

Following are my tests in `v1.2-57b26312-head` and `v1.2.0-rc4`
Note that refresh page is a workaround to show the enable form, may be a clue too.


### `v1.2.0-rc5` and `v1.2-57b26312-head` :x: (Workaround: Refresh)
https://github.com/harvester/harvester/assets/2773781/91666af9-42b7-4d85-a495-12fc3a4526b6


### `v1.2.0-rc4` :heavy_check_mark: 
https://github.com/harvester/harvester/assets/2773781/c62fbbe2-0716-44ba-9e05-9cc7f2645944

**Comment by n313893254** [comment]
> Per discussed, enablement works fine in v1.2.0-rc4 and have this issue since v1.2.0-rc5 after fresh install,

@albinsun This issue can reproduce in v1.2.0-rc4, the root cause is the  [Websocket](https://github.com/harvester/harvester/issues/4412) issue, I can not totally fix it without refreshing the page, so I just added the banner to info user. 

![image](https://github.com/harvester/harvester/assets/18737885/0edd86c3-7325-4d04-b382-60016e1bd86f)


**Note**

Due to this [issue](https://github.com/harvester/harvester/issues/4412), it takes a few more tries to verify this feature

The expected behavior will look like this recording:

https://github.com/harvester/harvester/assets/18737885/4c5c1e29-7a85-45fe-ad46-c73ee629df36

**Comment by albinsun** [comment]
* Workaround: "refresh page"
* Close and trace in https://github.com/harvester/harvester/issues/4412
* If this issue is not going to fix in `v1.2.0`, it's better to take action (e.g. doc) to let user know the workaround.
