### ISSUE TITLE
[BUG] API will stuck if delete the VM not existing

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4388]
### Describe the bug
API endpoint: `v1/harvester/kubevirt.io.virtualmachines/{namespace}/{vm_name}`

### To Reproduce
1. Install Harvester with any nodes
2. Call API endpoint to delete VM

### Expected behavior
API should return 404 error

## Environment:
 - Harvester ISO version: **v1.2.0-rc5**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 3 nodes**

### Additional context
API endpoint: `v1/harvester/persistentvolumeclaims/{namespace}/{vm_name}` will return 404 error.

**Comment by guangbochen** [comment]
Is this urgent for e2e testing? If not will prefer to leave it for v1.2.1, thanks.

**Comment by lanfon72** [comment]
It's not urgent, we can wait this to be fixed after `v1.2.0`.

**Comment by bk201** [comment]
@Yu-Jack can you help check this, deleting a non-existing VM blocks the API call.

**Comment by Yu-Jack** [comment]
I tried API endpoint `v1/harvester/kubevirt.io.virtualmachines/{namespace}/{vm_name}`, but I didn't get stuck. It returns http status code 500 error to me with following error message in v1.2.1 and v1.3 these two harvester versions.

```
{
    "type": "error",
    "links": {},
    "code": "ServerError",
    "message": "Failed to get vm default/testa, virtualmachines.kubevirt.io \"testa\" not found",
    "status": 500,
    "type": "error"
}
```

@lanfon72  Did I miss some steps to reproduce that? Or it just happened on RC version?

Here is my example API call:
```
# testa vm doesn't exist
curl --location --request DELETE 'https://192.168.122.61/v1/harvester/kubevirt.io.virtualmachines/default/testa' \
--header 'Content-Type: application/json' \
--header 'Accept: application/json' \
--header 'Authorization: Bearer token-xxxx'
```

**Comment by lanfon72** [comment]
The result from Postman
![image](https://github.com/harvester/harvester/assets/5169694/974efecb-7acd-4695-ad32-b7df97328176)

curl (http2)
![image](https://github.com/harvester/harvester/assets/5169694/a7c91250-9a56-4e0a-a8a7-a499242f148f)

curl (http1.1)
![image](https://github.com/harvester/harvester/assets/5169694/0c708972-620c-4aa9-8b38-32511d9f12e3)

and if i use Python's `aiohttp`, the result will be the same as Postman (code: 500)
![image](https://github.com/harvester/harvester/assets/5169694/69908e24-faf5-4b43-8b4f-f6d843b1cc76)

but use Python's `request` (used by our automation), the endpoint will make process stuck.  I think the implementation have something missing so Postman and curl got different result. (fallback by their own)

**Comment by Yu-Jack** [comment]
@bk201 This should return 404 when deleting non-existing VM instead of 500, so it's nothing related to blocking. I will focus on modifying this http response status code.

BTW, with `/apis/kubevirt.io/v1/namespaces/:namespace/virtualmachines/:name` this endpoint, it will return 404. So, if want to use normal behavior, you could use this for temporarily.

**Comment by bk201** [comment]
@lanfon72 Can you confirm Jack's statement? Can we change the issue title accordingly

**Comment by lanfon72** [comment]
I think the title is not the matter, I had described in the **Expected Behavior** section, we should get `404` error rather than others.

but as https://github.com/harvester/harvester/issues/4388#issuecomment-2042176716, in different client, the return code is inconsistent, and in Python's _requests_ `v2.31.0`, the request will stuck.

We can update the title to something like _API will not return `404` if delete the VM not existing_ or other title, but I don't think it is matter.

**Comment by Yu-Jack** [comment]
Just add more context. In automation code:

https://github.com/harvester/tests/blob/a269888b3e19a58bb07eac0dfe2e8d23715bdd09/apiclient/harvester_api/api.py#L120-L127

It seems it will retry after it receives `500` error code.

**Comment by lanfon72** [comment]
I thought I had explained clearly what the bug is, if not, you can try to reproduce it as the snapshot:
![image](https://github.com/harvester/harvester/assets/5169694/3662b4ee-90b7-4dcd-8f30-23965d3416b3)

When you use `requests v2.31.0`, it will raise a timed out after 3 mins around, because the server is not answer, to notice the **timed out** is client's behavior, which means server side is not handling the request correctly.

And the about the `500` error in automation would be something like:
![image](https://github.com/harvester/harvester/assets/5169694/342f0371-4362-4e64-9c39-f77c2b3841e6)

I thought snapshots in https://github.com/harvester/harvester/issues/4388#issuecomment-2042176716 already explain that server is not return a correct response so that different clients will get different results.

As **kubevirt**'s similar API will return `404` error, that's the main topic for this issue to be focused on.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
- Follow step to reproduce in https://github.com/harvester/harvester/issues/4388#issue-1839357854
