### ISSUE TITLE
[Question] Should updated MTU apply on existed VM network?

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4389]
During verifying #4353, we found that existed VM network will not affect by MTU update.
Should convert to BUG if this is NOT expected behavior

## Environment
* Harvester
  * Version: `v1.2.0-rc5`
  * Profile: QEMU/KVM, single node (8C/16G/250G)
  * **ui-source**: Auto

## Test Cases
> **Note** Click "►" to expand details.

1. <details>
   <summary>
   Create cluster network nonmgmt with MTU 6666
   </summary>
  
   
   ![image](https://github.com/harvester/harvester/assets/2773781/eee3b135-b2f8-4b8f-8ab6-3a6d61aced08)
   </details> 

1. <details>
   <summary>
   Create VM network vlan1-before
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/64046a0e-0273-4749-b4bf-ddc81d586b66)
   </details>

1. <details>
   <summary>
   Update cluster network's MTU to 7777
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/c2662187-0d33-4d4b-b41f-59c8a4bbd14a)
   </details>

1. <details>
   <summary>
   Create VM network untagged-after
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/9ca976fd-69d2-49d7-90ce-7aa7c304ad22)
   </details>

1. <details>
   <summary>
   Create a VM with these 2 VM networks
   </summary>
      
   ![image](https://github.com/harvester/harvester/assets/2773781/cf4543c6-8701-4307-82b7-f772d1099e3d)
   </details>

1. <details open>
   <summary>
   One network w/ MTU 6666, the other w/ 7777
   </summary>
      
   ![image](https://github.com/harvester/harvester/assets/2773781/2560ec93-c9cb-454c-b04c-76c0580c4916)
   * vlan1-before
     ![image](https://github.com/harvester/harvester/assets/2773781/edafe07d-be70-440f-9d05-51aa47bae570)
   * untagged-after
     ![image](https://github.com/harvester/harvester/assets/2773781/8f7a8136-bfd5-4dd4-9f34-08d83b019a60)
   </details>

**Comment by albinsun** [comment]
cc. @yaocw2020

**Comment by yaocw2020** [comment]
@albinsun  Yes, it's the expected result. I have filed an enhancement issue https://github.com/harvester/harvester/issues/4355, and we'll completely solve the MTU problem.

**Comment by albinsun** [comment]
@yaocw2020, thanks for the comment.
Close ticket as by design.
