### ISSUE TITLE
[Question]How should I reboot the host machine

### ISSUE THREAD

**Issue by 983183947** [harvester/harvester#4390]
How should I reboot the host machine? I execute the reboot prompt after logging in to the system through ssh and there is no such command

**Comment by Martin-Weiss** [comment]
Did you switch to user root?

**Comment by bk201** [comment]
As Martin pointed out, you need to switch to root first: https://docs.harvesterhci.io/v1.1/troubleshooting/os#how-to-log-into-a-harvester-node
And I suggest shutting down VMs on the rebooting node or going with the maintenance flow before the reboot: https://docs.harvesterhci.io/v1.1/host/#node-maintenance
The maintenance flow migrates VMs to other hosts.
