### ISSUE TITLE
[ENHANCEMENT] Add rancher-vcluster to storage-network setting processing

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4397]
**Is your enhancement related to a problem? Please describe.**

`Rancher-vcluster` addon is backed with PV by default from Harvester v1.2.0

It needs to be added to the storage-network related processing.
https://github.com/harvester/harvester/blob/master/pkg/controller/master/storagenetwork/storage_network.go#L730

**Describe the solution you'd like**

Add source code in Harvester v1.2.1

**Describe alternatives you've considered**

Add a workaround to Harvester doc in Harvester v1.2.0: suggest user to disable `rancher-vcluster` addon before stoarge-network setting will be changed, and enable the addon again after it.

**Additional context**

Observed in https://github.com/harvester/harvester/pull/4383

**Comment by WebberHuang1118** [comment]
We will improve the Storage Network's webhook during the vcluster is enabled. Since Vcluster may contain the running cluster, it's unsuitable to have an automatic mechanism to disable and enable the cluster. However, we can have a document update about the correct process for setting the Storage Network as Vcluster is running.

**Comment by WebberHuang1118** [comment]
For the webhook, we can identify the vcluster pvc naming by the vcluster charts:
- Statefulset naming https://github.com/loft-sh/vcluster/blob/d046a94bb6f7fdec7061589769e201d7e72f9fe4/charts/k3s/templates/syncer.yaml#L5-L6
- PVC naming https://github.com/loft-sh/vcluster/blob/d046a94bb6f7fdec7061589769e201d7e72f9fe4/charts/k3s/templates/syncer.yaml#L37-L47

**Comment by irishgordo** [comment]
@WebberHuang1118 thanks for this enhancement :smile: :+1: 
This looks good on v1.4.0-rc3 :smile: 
I'll go ahead and close this out
![Screenshot from 2024-10-21 16-19-25](https://github.com/user-attachments/assets/ab63afca-9b54-4d59-9a88-ee493105ab95)

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 thanks for this enhancement 😄 👍 This looks good on v1.4.0-rc3 😄 I'll go ahead and close this out ![Screenshot from 2024-10-21 16-19-25](https://private-user-images.githubusercontent.com/5370752/378623962-ab63afca-9b54-4d59-9a88-ee493105ab95.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk1NjAwMTAsIm5iZiI6MTcyOTU1OTcxMCwicGF0aCI6Ii81MzcwNzUyLzM3ODYyMzk2Mi1hYjYzYWZjYS05YjU0LTRkNTktOWE4OC1lZTQ5MzEwNWFiOTUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjJUMDExNTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MzhmMjEyOGIyNjc5N2VlMDlkZjRjODJjM2VkOWFlOTY5MWNlMmQ2ZjgwMWM4ZWNmMjhiNTljMzAxOWUzNzMxMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.tQR8K4R5kl5LptciBN_Db3z_AhA6KVeqmXb8dVkTyk8)

Thanks @irishgordo
