### ISSUE TITLE
[Question]The disk has already been force-formatted. Current file system is ext4, You can format it manually.

### ISSUE THREAD

**Issue by 983183947** [harvester/harvester#4398]
I found that my system does not seem to recognize my hard disk, and the prompt is as follows:
  The disk has already been force-formatted. Current file system is ext4, You can format it manually.

**Comment by Vicente-Cheng** [comment]
Hi @983183947,
That's weird.
Even if the disk is formatted, we should detect it.
Could you provide the support bundle or log of the harvester-node-disk-manager?

And what harvester version you use?
