### ISSUE TITLE
Unable to import image when content-length is missing from remote url

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#44]
Import an image from https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img

**Result:**
```
ERRO[4747] error importing image from https://launchpad.net/cirros/trunk/0.3.0/+download/cirros-0.3.0-x86_64-disk.img: strconv.Atoi: parsing "": invalid syntax
```

The server hosting the image file may return a chunked response without`Content-Length` header. In this case, the total file size is unknown until the import is finished. The percentage progress will be unavailable to the users. We might need to show the downloaded size instead(similar to chrome's download behavior).

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/60
