### ISSUE TITLE
[BUG]Image state displays failed even though the progress is completed

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#440]
**Steps to reproduce:**
1. Upload an image
2. While the image uploading progress is almost done, make the minion be unavailable. (Delete all the minio pods)

**Result:**
The image state displays failed but its progress is completed
![image](https://user-images.githubusercontent.com/57614736/105153581-92dfa980-5b43-11eb-80bd-e22a8d88adb1.png)

**Comment by WuJun2016** [comment]
@gitlawr  At this time, the status of API is shown below
![image](https://user-images.githubusercontent.com/24985926/105167951-5ff1e180-5b54-11eb-8e7a-94aac59e14ad.png)

**Comment by DoNotSayYes** [comment]
Validated on master-head
