### ISSUE TITLE
Will it support Software Firewalls like Pfsense or OPNsense 

### ISSUE THREAD

**Issue by ramzcode** [harvester/harvester#4400]
Can we use an FIrewall VM as the Firewall to my other VM's within the cluster ?

Kind of VPC with a Firewall within it.

Not sure and also I don't see any reference for the Firewall Option too.

**Comment by simonflood** [comment]
So create a VM for the firewall with it attached to whichever networks, then other VMs attached to those networks would be protected by the firewall VM? If so I don't see why not.

**Comment by ramzcode** [comment]
Is there any support Document that I can use ?

**Comment by w13915984028** [comment]
The said requirement (VPC similar) seems not supported now.
 
Refer:
https://docs.harvesterhci.io/dev/networking/clusternetwork#relationship-between-cluster-network-network-config-vm-network

Each VM's network is attached to the HOST network/indepedent VLAN network, there is no simple solution to configure one VM's network traffic should go through another VM first.

On the other hand, the Rancher integrated solution (https://docs.harvesterhci.io/dev/rancher/node/rke2-cluster), the Rancher can guide Harvester to create a couple of VM's to deploy guest RKE2 cluster, that's kind of k8s cluster. It is more complex than simple plain VM network.

**Comment by ramzcode** [comment]
@w13915984028 Thank you for the confirmation. All the Docs the Architectural images also did not show such feasibility except using an external box. 

Once again thank you team for such a wonderful platform.
