### ISSUE TITLE
[Doc]Update PCI devices docs

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4406]
**Is your doc request related to a problem? Please describe or add related issue ID.**
This is in reference to [this](https://docs.harvesterhci.io/v1.1/advanced/pcidevices/#enabling-passthrough-on-a-pci-device), but with PCI devices addon going out of experimental we should update some of the screenshots.
**Describe the solution you'd like**

-  Replace the screenshot that still says experimental and the screenshot with the addons since we added some since that was taken.
- We might want to call out that the PCI devices addon goes from enabled to deploy successful when the addon is actually deployed. I added a ton of screenshots to this ticket just in case any of them were needed.

Most of the ones near the end of the doc seemed fine.

![Greenshot 2023-07-12 14 23 28](https://github.com/harvester/harvester/assets/83787952/4294fbef-b385-4db2-ab55-4e4d2322f6d8)
![Greenshot 2023-07-12 14 23 12](https://github.com/harvester/harvester/assets/83787952/105adbcc-7596-415d-b9a8-5fbf4ad0d52c)
![Greenshot 2023-07-12 14 07 16](https://github.com/harvester/harvester/assets/83787952/9cdf12fa-eb35-40c2-984a-1bdce6781eb3)
![Greenshot 2023-07-12 14 07 09](https://github.com/harvester/harvester/assets/83787952/7f39de2c-6808-4830-acf3-15e458aa0cdd)
![Greenshot 2023-07-12 14 06 53](https://github.com/harvester/harvester/assets/83787952/d85cee72-5f35-482b-8dd6-c73a35cb4f23)
![Greenshot 2023-07-12 14 06 46](https://github.com/harvester/harvester/assets/83787952/092b75ae-87c1-4583-8526-204adc1274a8)
![Greenshot 2023-07-12 13 53 41](https://github.com/harvester/harvester/assets/83787952/45e69122-6e82-4d41-ad82-a31cd2a16637)
![Greenshot 2023-07-12 12 24 01](https://github.com/harvester/harvester/assets/83787952/2201c7a6-d0af-4eb7-a982-e00163e7669c)
![Greenshot 2023-07-12 12 23 57](https://github.com/harvester/harvester/assets/83787952/84311d88-f196-4ca9-9fde-8e51c5a97b96)
![Greenshot 2023-07-12 12 23 50](https://github.com/harvester/harvester/assets/83787952/0e87e165-88c0-4cc6-9a11-0a9b3bb6266e)
![Greenshot 2023-07-12 12 23 44](https://github.com/harvester/harvester/assets/83787952/eb0bc0c2-1771-4b9b-8e5b-bf96d1f47c4e)
![Greenshot 2023-07-12 12 23 37](https://github.com/harvester/harvester/assets/83787952/5e3f6950-fcbe-4bfd-97be-9bf8e1fde56c)
![Greenshot 2023-07-12 12 23 27](https://github.com/harvester/harvester/assets/83787952/96051f11-f1e5-4543-ae14-6a3db6a52199)
![Greenshot 2023-07-12 12 12 05](https://github.com/harvester/harvester/assets/83787952/6f4bc65a-7bbb-4fa1-9fcf-ad9b380ce4bb)
![Greenshot 2023-07-12 12 11 39](https://github.com/harvester/harvester/assets/83787952/a1b43527-1ce7-4ec4-86bf-5a12aeb9539f)
![Greenshot 2023-07-12 11 42 05](https://github.com/harvester/harvester/assets/83787952/4f907f09-a20f-4bc5-b2c2-60be1ce56bd5)
![Greenshot 2023-07-12 11 41 47](https://github.com/harvester/harvester/assets/83787952/fd5ecfb2-2d59-47a9-bbc0-907866bbbec7)
![Greenshot 2023-07-12 11 41 41](https://github.com/harvester/harvester/assets/83787952/15fac650-d540-4f22-889a-1d36c353a14d)
![Greenshot 2023-07-12 11 41 37](https://github.com/harvester/harvester/assets/83787952/2319cd9f-3e65-42ff-ad3a-5a77ba8fd2c6)
![Greenshot 2023-07-12 11 41 26](https://github.com/harvester/harvester/assets/83787952/b2bb149d-cd6f-4a75-93a9-716022191a2c)
![Greenshot 2023-07-12 11 41 15](https://github.com/harvester/harvester/assets/83787952/798321de-dfc4-4f6a-885d-b083aea51224)

**Comment by ibrokethecloud** [comment]
Introduced doc updates: https://github.com/harvester/docs/pull/390

**Comment by guangbochen** [comment]
Close as the doc is available on https://docs.harvesterhci.io/dev/advanced/pcidevices#sriov-network-devices
