### ISSUE TITLE
[BUG] The userPreferences API 404 NotFound,  All APIs are missing view links

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#441]
**Describe the bug**
![image](https://user-images.githubusercontent.com/24985926/105269638-522d7200-5bcf-11eb-8961-419ae72d98e2.png)
![image](https://user-images.githubusercontent.com/24985926/105269666-607b8e00-5bcf-11eb-81ea-ec1c6bc28a98.png)

**To Reproduce**
Reinstall a new environment  （System and havester are new）

**Comment by futuretea** [comment]
Test harvester master(73f18c6), views links is exists.

**Comment by DoNotSayYes** [comment]
Validated on master-head, the view link is visible in every API. And the `userpreferences` API is callable for now.
![image](https://user-images.githubusercontent.com/57614736/105818549-083ef480-5ff2-11eb-8677-a40375353891.png)
![image](https://user-images.githubusercontent.com/57614736/105818780-4b996300-5ff2-11eb-9f13-8359eb9e86ac.png)

**Comment by futuretea** [comment]
After use k3s v.1.20+ All APIs are missing view links
Link to #446

**Comment by futuretea** [comment]
if bump k3s version to v1.20+, need reopen this issue(All APIs are missing view links)

**Comment by TangStone** [comment]
**Validation Version**
- master-3d9efd26-head

**Verification steps**

-  use k3s v.1.20+

![image](https://user-images.githubusercontent.com/15829074/110918794-8531ed80-8356-11eb-8407-05b413488e47.png)

- the view link is visible in every API. And the userpreferences API is callable for now.

![image](https://user-images.githubusercontent.com/15829074/110925472-31c39d80-835e-11eb-9020-9ddf610cbf3a.png)

![image](https://user-images.githubusercontent.com/15829074/110925757-8d8e2680-835e-11eb-8e64-c6bbd13a7bbf.png)
![image](https://user-images.githubusercontent.com/15829074/110925848-a39be700-835e-11eb-8bee-a88433fc345d.png)
**Verification passed**
