### ISSUE TITLE
[BUG] Switch from admin to project-member user in Rancher to access Harvester will display empty page 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4413]
**Describe the bug**

In Rancher, when we switch user from `admin` to the project-member user `test` and access Harvester from virtualization management page. 

It will display empty page with message
`contact(...) is not a function` 
![image](https://github.com/harvester/harvester/assets/29251855/e45218d0-cfea-4c34-a097-6024324e77de)

https://github.com/harvester/harvester/assets/29251855/e69acbb4-55db-4140-8611-177bfd63d02a

**To Reproduce**
1. Prepare a v1.2.0-rc5 Harvester
2. Import Harvester to Rancher v2.7.6-rc2
3. Create a user `test` in Rancher User and Authentication 
4. Access Harvester in admin account 
5. Grant project-member permission on `default` project 
6. Logout admin and login with `test` user
7. Access Harvester from the virtualization management page 

**Expected behavior**

After switch from admin to user `test` with project-member permission on Harvester default project. 
Access Harvester from virtualization management should display correctly. 

**Support bundle**

[supportbundle_1f628130-c65a-4c76-a611-b9e73ad71456_2023-08-14T09-54-56Z.zip](https://github.com/harvester/harvester/files/12333589/supportbundle_1f628130-c65a-4c76-a611-b9e73ad71456_2023-08-14T09-54-56Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single nodes local kvm machine
 - Rancher version: v2.7.6-rc5

**Additional context**
Workaround: Refresh the page can access Harvester correctly. 
Found during the verification in https://github.com/harvester/security/issues/33

**Comment by WuJun2016** [comment]
Same as this issue：   https://github.com/harvester/harvester/issues/3895
