### ISSUE TITLE
[Question] Product roadmap and 1.0 release estimation?

### ISSUE THREAD

**Issue by maddie** [harvester/harvester#442]
I'm looking for an open-source HCI solution, and I found Harvester on Google. I've been watching Rancher (the tool) for a while, and pretty surprised to find this project.

Is there any kind of roadmap for Harvester, or an estimated release date for 1.0?

**Comment by guangbochen** [comment]
The roadmap is available at [here](https://github.com/rancher/harvester/milestones) and the next release would be v0.2.0.
Additionally, we have not scheduled an exact time of the GA release, it is not only about the product but we would like to gain more user cases and time-proven user cases before launching a good GA product, thanks for bearing with us.

**Comment by gitlawr** [comment]
The roadmap is available in https://github.com/harvester/harvester/wiki/Roadmap
