### ISSUE TITLE
[Doc] Suggest to enhance the multi-CSI document

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4420]
**Is your doc request related to a problem? Please describe or add related issue ID.**

Per issue https://github.com/harvester/harvester/issues/2405 and https://github.com/harvester/harvester/wiki/Roadmap#v120-q3-2023 ([Third-party storage support for non-root disk](https://github.com/harvester/harvester/issues/2405).

The multi-CSI is a new `highlighted` feature in Harvester v1.2.0.

But the current document PR https://github.com/harvester/docs/pull/372 split the information in different chapters and there is no single entrance for user to follow.

**Describe the solution you'd like**

Add an indepedent chapter in the document to describe the multi CSI feature, and list a few examples.

The test steps https://github.com/harvester/harvester/issues/2405#issuecomment-1559880174 are good drafts.

Also include the KB https://github.com/harvester/harvesterhci.io/pull/38

**Comment by guangbochen** [comment]
cc @futuretea

**Comment by futuretea** [comment]
Done
