### ISSUE TITLE
[BUG] Drive name incorrectly listed when adding drive to host.

### ISSUE THREAD

**Issue by mkoperator** [harvester/harvester#4426]
**Describe the bug**
When adding 2 additional drives by editing the host, the second drive gets listed under the same dev name instead of it's proper name as shown in linux.

Specifically added two SSDs. Show up in linux as /dev/sdh and /dev/sdi. In Harvester both listed as /dev/sdh and the second disk obviously does not mount.

**To Reproduce**
1. Plug in 2 drives 
2. Confirm they show up in `/dev`
3. Go to hosts and edit your host.
4. Select "Add Disk".
5. Drop down lists both drives as same drive letter

**Expected behavior**
Drive letters would match what is in linux.

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Harvester 1.2.0-rc4

**Comment by mkoperator** [comment]
I will add that after adding the first drive successfully, the second one is still listed with the improper drive letter and cannot be mounted.

**Comment by WebberHuang1118** [comment]
Hi @mkoperator,

According to https://docs.harvesterhci.io/dev/host/#multi-disk-management,
Could you help to check whether the disks' WWN is duplicated? If your disks have no WWN, you can format it with `EXT4` to help Harvester recognize it.

Thanks

**Comment by Vicente-Cheng** [comment]
Hi @mkoperator,
Could you provide the support bundle for further investigation?
Thanks!

**Comment by mkoperator** [comment]
We ended up switching out disks and are not able to recreate with new ones. Closing for now, will re-open if I have the same issues with 1.2.0

**Comment by Vicente-Cheng** [comment]
OK, feel free to reopen or create a new one if you meet different problems. Thanks!

**Comment by infi-cas** [comment]
### I'm having the same problem.
Describe:
I own a server on which there are 3 SSD disks with the same WWN, I have formatted them using the ext4 format, but when editing the host to add the disk, the 3 disks still show the same name, which is inconsistent with the one that is shown through the linux command lsblk, and only the first one works fine after being added, while the other two don't work properly.
Environment:

- HarvesterV1.2.0
- @Vicente-Cheng
