### ISSUE TITLE
[ENHANCEMENT] collect containerd.log in support-bundle-kit

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#4427]
**Is your enhancement related to a problem? Please describe.**

collect containerd.log in support-bundle-kit

**Describe the solution you'd like**

the harvester collector in support-bundle-kit needs to be enhanced to also collect containerd.log file.

At times this can be useful to troubleshoot issues with container runtime.

It is available at: /var/lib/rancher/rke2/agent/containerd/containerd.log

**Describe alternatives you've considered**

**Additional context**

**Note:**
Backport the fix to v1.2.1 and v1.1.3

**Comment by bk201** [comment]
@Yu-Jack I think we can resolve this once we have the correct SBK in 1.2

**Comment by Yu-Jack** [comment]
@bk201  Yeah, it's v0.0.28 now in v1.2. https://github.com/harvester/harvester/blob/d66812e66867f62f1f702d636f7e53d835d6456b/deploy/charts/harvester/values.yaml#L482-L486

I'll open a PR back to v1.2.

**Comment by albinsun** [comment]
Provide test result on `v1.2.2-dev-20240329`, do have **_containerd.log_** under _**nodes/**_, close as fixed.


## Environment
* Harvester
  * Version: `v1.2.2-dev-20240329`
  * Profile: QEMU/KVM, single nodes (16C/32G/500G)
  * ui-source: `Auto`


## Steps 
1. Download supportbundle and unzip **_nodes/harvester-node-0.zip_**

2. Check there is **_containerd.log_** :green_circle: 
   ![image](https://github.com/harvester/harvester/assets/2773781/31f46c76-ea4f-4399-b446-4e08ef96bb30)

3. Check **_containerd.log_** has content :green_circle: 
   ![image](https://github.com/harvester/harvester/assets/2773781/9dcc9500-09be-4dc0-91ac-6f5574972fb2)
