### ISSUE TITLE
[Question] vm's only run on node 1 and 2 not on node 3

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#4429]
Hello, I prepared 3 older HP workstations Z840 for testing Harvester. My question is, why are no VMs running on node 3, I created nine VMs with CPU =4, Memory= 8GB, and 10 GB disk size.

Node 1: 48 Cores, 256 GB Memory --> 7 VMs are running
Node 2: 48 Cores, 64 GB Memory --> 2 VMs are running
Node 3: 56 Cores, 64 GB Memory --> no VMs
each has 2 or 4-TB SSD Disk

I have only 1 GB Network, could this be the reason??

Second question, where can I edit the name of a running VM?

**Comment by guangbochen** [comment]
This is likely an expected behavior of the k8s scheduler when u have a limited number of VMs and large nodes, u may refer to https://harvesterhci.io/kb/vm-scheduling for a detailed explanation, if you like you can also use affinity rules to distribute ur VMs.

**Comment by jrlittlefoot64** [comment]
thank you
