### ISSUE TITLE
[BUG] Error after vm migation

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#4430]
**Describe the bug**
after VM migration  from node 1 to node 3 menu 'Virtual Machines' is short flickering and shows the error message:

firefox

<img width="566" alt="Screenshot_20230818_095345" src="https://github.com/harvester/harvester/assets/85644625/e8f653aa-0be2-480d-83d1-47e63d3f2b0d">

google chrome

<img width="511" alt="Screenshot_20230818_095459" src="https://github.com/harvester/harvester/assets/85644625/679ce882-7b4a-4d3c-b119-4a6616e8eb3a">

The rest is working, harvester 1.2.0-rc5

[supportbundle_34877e9f-e3d6-4f91-b579-a8f2f3bd41a0_2023-08-18T07-57-33Z.zip](https://github.com/harvester/harvester/files/12376951/supportbundle_34877e9f-e3d6-4f91-b579-a8f2f3bd41a0_2023-08-18T07-57-33Z.zip)

**Comment by WuJun2016** [comment]
Duplicate with:  https://github.com/harvester/harvester/issues/4394

We have fixed the issue.

**Comment by WuJun2016** [comment]
You can go to the setting page and change `ui-souce` to `external` to get the UI to work.

**Comment by jrlittlefoot64** [comment]
Thank you
