### ISSUE TITLE
[BUG] Longhorn Instance Manager Memory leak

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4431]
Harvester could reproduce the memory leak on Longhorn Instance Manager by intentionally misconfiguring NFS server

**Environment:**
- Harvester v1.2.0
- Longhorn v1.4.3

**Reproduce Steps:**
1. Creating a VM with one volume 
2. Configure NFS server with exports (e.q. /home/data/invalid)
3. Setting Harvester backup-target (Settings->backup-target)
4. Misconfigure NFS server, removing NFS export path
    - E.q. $ rm -rf  /home/data/invalid (on the target host)
6. Creating 100 VM backups (Virtual Machines -> Take Backup)
7. `instance-manager-r-xxxx` pod's memory usage climbs from 144MB for 1400MB in 15 hours

**Some Source Code Observation:**
1. For a newly created backup, it goes through the process of [backup controller reconcile](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L369-L406) -> [checkMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L525-L555) -> [enableBackupMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L620-L640) -> [NewBackupMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/engineapi/backup_monitor.go#L78-L114) to start backup operation
2. If the backup failed [other than DeadlineExceeded](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/engineapi/backup_monitor.go#L93-L97), the error bubbles up to [enableBackupMonitor without setting the monitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L634-L637) (since it's null).
3. And backup error bubbles up all the way to [backup controller reconcile without status update](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L341-L360)
4. For the next backup controller reconcile, it will treat the backup as newly created. Since [LastSyncedAt is null](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L369) and the backup [has no matched monitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L531-L533).  The above steps repeat over again and again.
5. This leads the `BackupInfo` structure keeps allocated in `instance-manager-r-xxxx` pods and introduces memory leak, as described [here](https://github.com/longhorn/longhorn/issues/6481#issue-1842216484).

**Related Longhorn Ticket:**
- [#6481](https://github.com/longhorn/longhorn/issues/6481)

**Comment by WebberHuang1118** [comment]
Follow this issue on Longhorn ticket [#6481](https://github.com/longhorn/longhorn/issues/6481),
It could be fixed on Longhorn v1.4.4 and v1.5.2

**Comment by WebberHuang1118** [comment]
After checking LH source code,
This should be fixed by LH manager PR [#2086](https://github.com/longhorn/longhorn-manager/pull/2086) and LH engine PR [#927](https://github.com/longhorn/longhorn-engine/pull/927)
- LH manager PR [#2086](https://github.com/longhorn/longhorn-manager/pull/2086) fixs repeatedly creating backup in the target is invalid
- LH engine PR [#927](https://github.com/longhorn/longhorn-engine/pull/927) fixes the memory leak on BackupInfo creation in LH engine

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/5f879eef-bd89-4fa0-a3bb-7ee8d01cb2ed)


Test Information
----
* Environment: **Baremetal DL360G9 5 nodes**
* Harvester Version: **v1.3.0-dev-20231222**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Setup a NFS Server
3. Login to Dashboard, create a VM `vm1` and write some data
4. Configure `backup-target` to the NFS server
5. Deactive the NFS Server
6. Take around 100 backups by `vm1`
7. Monitor resource of `instance-manager` pods
8. Memory usage should not continuing increase by hour (but It might floating a bit)
