### ISSUE TITLE
[BUG] failed to sync topology label on the custom rke2 cluster

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4432]
**Describe the bug**
With Rancher's MCM UI, when enabling the Harvester cloud provider on the custom cluster, the Harvester CCM pod will contains the following error:
```
time="2023-08-18T09:18:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-jqmd7': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-jqmd7\" not found, requeuing"
time="2023-08-18T09:18:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-4kbv5': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-4kbv5\" not found, requeuing"
time="2023-08-18T09:18:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-s2gzk': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-s2gzk\" not found, requeuing"
time="2023-08-18T09:20:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-jqmd7': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-jqmd7\" not found, requeuing"
time="2023-08-18T09:20:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-4kbv5': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-4kbv5\" not found, requeuing"
time="2023-08-18T09:20:08Z" level=error msg="error syncing 'default/rke2-pool1-da3fb914-s2gzk': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-da3fb914-s2gzk\" not found, requeuing
```
**To Reproduce**
1. Import Harvester(e.g., v.1.2.0) into a Rancher server(e.g., v2.7.6-rc3)
2. Manually create a VM on the Harvester cluster
3. On the Rancher UI, click `Cluster Management` and create a new custom cluster
    <img width="1288" alt="image" src="https://github.com/harvester/harvester/assets/4569037/dff6ee30-5ddc-4047-8679-0351256102c0">
4. Follow the [doc](https://docs.harvesterhci.io/dev/rancher/cloud-provider#deploying-to-the-rke2-custom-cluster-experimental) to deploy to the RKE2 Custom Cluster, and it will contain the above logs.

**Expected behavior**
- No error log should be shown.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Any

**Additional context**
- N/A

**Comment by TachunLin** [comment]
Currently when we use Harvester v1.4.0 master with Rancher v2.9.0 to provision the custom RKE2 cluster
It would stuck in `waiting for cluster agent to connect` 

![image](https://github.com/user-attachments/assets/db67a537-bfda-45d1-9aea-595e6b87b368)
 
This would prevent us to proceed to verify this issue. 
Track in issue #6286 and move this issue to ready for testing stage.

**Comment by albinsun** [comment]
Test PASS, close as fixed.


### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: Single node QEMU/KVM (8C/16G/500G)
  * ui-source: Auto
* Rancher
  * Version: v2.9.2
  * Profile: helm (v1.29.9+k3s1)
  * Apps:
    * harvester-cloud-provider:0.2.4


### Verification
1. <details>
   <summary> <i>Given</i> harvester is imported to rancher
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c0530232-2746-4c8f-8ed9-7e5d5ebb2cd9)
   </details>

1. <details>
   <summary> <i>When</i> create 2 custom RKE2 clusters in the default namespace
   </summary>
   
   * Harvester
     ![image](https://github.com/user-attachments/assets/ecac9fd9-9ace-4890-aa5b-37d7a8b29c45)
   * Rancher
     ![image](https://github.com/user-attachments/assets/9b2ac44b-639b-4d55-ac16-c48cc3637633)
   </details>

   > https://docs.harvesterhci.io/v1.4/rancher/cloud-provider#deploying-to-the-rke2-custom-cluster-experimental

1. <details>
   <summary> <i>Then</i> both custom RKE2 clusters should <code>Active</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c7b84f7e-f22a-4a3a-939a-b5bd9b424b0a)
   </details>

1. <details>
   <summary> <i>And</i> both RKE2 clusters' CCM pod has NO error syncing <code>error syncing 'default/rke2-pool1-...': handler harvester-cloudprovider-resync-topology: nodes \"rke2-pool1-...\" not found, requeuing"</code> or other explicit errors.
   </summary>
   
   * _myrke2_custom_
     ![image](https://github.com/user-attachments/assets/6e325b82-e805-4899-81f3-4bc28413b4a2)
   * _myrke2_custom2_
     ![image](https://github.com/user-attachments/assets/3a98a805-8a03-49b3-8c68-1ac0c8ff85c7)
   </details>

1. <details>
   <summary> <i>And</i> upgrade to harvester-cloud-provider:master-head should success and no explicit errors too.
   </summary>

   * _myrke2_custom_
     ![image](https://github.com/user-attachments/assets/97dae876-1535-437b-9dd2-22a0b39998f7)
   * _myrke2_custom2_ (w/ --disable-vmi-controller=true)
     ![image](https://github.com/user-attachments/assets/cf40f430-4678-412f-a3aa-8f4d03f0cb98)
     ![image](https://github.com/user-attachments/assets/0b53964a-de49-430a-8c5a-ab0fdecfc42a)


### Supportbundle


### QA Check List
1. Update labels
   - [x] This ticket: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
   - [x] tests ticket: harvester/tests/issues/1344
