### ISSUE TITLE
Support uploading local image

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#444]
**Is your feature request related to a problem? Please describe.**

I can't find a way to upload local images in the Harvester UI.

**Describe the solution you'd like**

N/A

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by DreamTeamWangbowen** [comment]
Can I upload the image directly to the server without passing the URL ？
because I am using the internal network，so I can't create a virtual machine, and all the status of the host is 0. It seems that there is a problem with the host monitoring. @guangbochen @gitlawr

**Comment by DreamTeamWangbowen** [comment]
Can I upload the image directly to the server without passing the URL ？
because I am using the internal network，so I can't create a virtual machine, and all the status of the host is 0. It seems that there is a problem with the host monitoring. @guangbochen @gitlawr

**Comment by DreamTeamWangbowen** [comment]
Because it is on the internal network, the screenshot cannot be displayed...

**Comment by gitlawr** [comment]
You can host your image files in internal web servers as the workaround before this issue is addressed

**Comment by DreamTeamWangbowen** [comment]
> You can host your image files in internal web servers as the workaround before this issue is addressed

My web server has an account and password, and access is denied.

like this, Get http://minio.harvester-system:9000/vm-images/?location=: dial tcp: lookup minio.harvester-system on 10.43.0.10:53: read udp 10.42.0.14:51739->10.43.0.10:53: read: connection refused

**Comment by DreamTeamWangbowen** [comment]
There is no web server without account password in my internal network..

**Comment by DreamTeamWangbowen** [comment]
URL
https://200.201.119.11/file/CentOS-6.3-x86_64-LiveCD.iso
Size
-
Description
-
Message
Get https://200.201.119.11/file/CentOS-6.3-x86_64-LiveCD.iso: x509: cannot validate certificate for 200.201.119.11 because it doesn't contain any IP SANs 

There is also a problem if there is no account password！

**Comment by DreamTeamWangbowen** [comment]
URL
http://200.201.119.11/file/CentOS-6.3-x86_64-LiveCD.iso
Size
-
Description
-
Message
Get http://minio.harvester-system:9000/vm-images/?location=: dial tcp: lookup minio.harvester-system on 10.43.0.10:53: read udp 10.42.0.14:40440->10.43.0.10:53: read: connection refused

**Comment by DreamTeamWangbowen** [comment]
“10.42.0.14:40440->10.43.0.10:53” is what？

**Comment by msj905** [comment]
Get http://minio.harvester-system:9000/vm-images/?location=: dial tcp 10.43.193.37:9000: connect: connection refused
我用虚拟机桥接网卡装的harvester，在添加github镜像和自定义镜像都出现怎么处理

**Comment by DoNotSayYes** [comment]
Tested on master-head

Files whose types are img, iso, qcow2 can be uploaded, moreover, VMs can be created by using those images. 
Remaining issues: #488, #489
