### ISSUE TITLE
[ENHANCEMENT] Remove descriptions for definitions and add a summary for each path

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#4443]
**Is your enhancement related to a problem? Please describe.**
Due to descriptions making the swagger.json too big, accessing the OpenAPI documents web page can cause stuck or crash issues.

**Describe the solution you'd like**
Accessing OpenAPI documentation pages without performance issues.

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
Close as the [PR](https://github.com/harvester/harvester/pull/4444) is merged and please refer to https://github.com/harvester/harvester/pull/4444#issuecomment-1694958573 for details.
