### ISSUE TITLE
[Question] Deploy Harvester without Longhorn

### ISSUE THREAD

**Issue by remipcomaite** [harvester/harvester#4454]
Hello everybody,

I would like to deploy Harvester without Longhorn.
Is it possible ?
And if so, is it possible to use another CSI for storing all VM data including the system image?

thank you for your answers

**Comment by WebberHuang1118** [comment]
Harvester will have Multi CSI Support from Harvester v1.2.0
https://github.com/harvester/harvester/blob/master/enhancements/20230316-multi-csi-support.md

However, Longhorn will still be necessary as in-house storage for VM Image (Backing Image), VM backup, and so on.

We will update related documents in the near future https://docs.harvesterhci.io/dev/.
Please feel free to follow it. Thanks.

**Comment by frasmarco** [comment]
Is this still true? I cannot find the relevant doc section

**Comment by w13915984028** [comment]
At the moment, it is not supported to deploy Harvester without Longhorn from the installation. There are some dependencies. And Harvester has no plan for it yet. thanks.
