### ISSUE TITLE
[Question] Use Kube-OVN with Harvester

### ISSUE THREAD

**Issue by remipcomaite** [harvester/harvester#4455]
Hello everybody,

Is it possible to use Kube-OVN with Harvester?

thank you for your answers

**Comment by Aixleft723** [comment]
Indeed, the network function of Harvester is limited to Layer 2 network now, without the concept of advanced routing and subnet, I hope the community can consider this point！

**Comment by haiker2011** [comment]
Hope the community can consider this feature

**Comment by remipcomaite** [comment]
Hello everyone,

I reiterate the request because I really think it would be a plus for the project.
