### ISSUE TITLE
[BUG] re-sync topology error: nodes not found in cloud-provider

### ISSUE THREAD

**Issue by chrisho** [harvester/harvester#4459]
**Describe the bug**
When multiple rke2 clusters exist in the same namespace, an error occurs where the nodes cannot be found in the cloud-provider controller.

```
time="2023-08-28T03:21:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:23:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:25:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:27:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:29:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:31:08Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
time="2023-08-28T03:31:38Z" level=error msg="error syncing 'default/rke2-cilium-pool1-eac30436-fq87k': handler harvester-cloudprovider-resync-topology: nodes \"rke2-cilium-pool1-eac30436-fq87k\" not found, requeuing"
```

Once the VMI has changed, the ccm controller will get the node by the VMI name. 
If there are multiple rke2 clusters in the same namespace, when the VMI of other clusters is changed, the current cluster also detects the change of the VMI and finds the node using the VMI name. However, it is important to note that the current cluster does not have this node.
https://github.com/harvester/cloud-provider-harvester/blob/c54a6eb6af98fbc415acf4df2c236c0023cb938a/pkg/controller/virtualmachineinstance/controller.go#L42-L58

**To Reproduce**
Provision multiple RKE2 clusters in the same namespace and check the logs of the cloud provider.

**Expected behavior**
No errors.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `master-df40d99-head` (24/08/01) with `cloud-provider:master-head` on Rancher `v2.8.5`.
Close this issue. 

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ No "re-sync topology" error on multiple RKE2 cluster using the same namespace $~~$</summary>

  1. The cloud-provider container log no longer display the  "nodes not found" error after setting the <strong>--disable-vmi-controller</strong> argument with cloud-provider:master-head image

  ![image](https://github.com/user-attachments/assets/63f7fae4-e87e-4e94-b694-7b8e42db4b55)

2. Compare with the other RKE2 cluster using cloud-provider:0.2.1 without the <strong>--disable-vmi-controller</strong> argument, there we still can find the "node not found" error

  ![image](https://github.com/user-attachments/assets/9426a256-73a9-4619-8944-1e3bd9db8ff6)



 </details>

### Test Information
* Test Environment: Three nodes harvester on remote kvm machines
* Harvester version: `master-df40d99-head` (24/08/01)
* Rancher version: v2.8.5
* Cloud provider image: master-head

### Verify Steps
<details><summary>Details </summary>

  1. Import Harvester to Rancher
  2. Provision the first RKE2 cluster with name `rke2` on the default namespace
  3. Provision the second RKE2 cluster with name `rke2-1` also on the default namespace
  4. Confirm two guest cluster are provisioned in `running` state
  5. Open the `rke2` cluster, check the cloud-provider deployment 
  6. Open the container log of cloud-provider, check the re-sync topology error: nodes not found exists
  7. Edit the yaml of the cloud-provider deployment 
  8. Change the cloud-provider image version to `master-head
  
      ![image](https://github.com/user-attachments/assets/da817eb3-3c67-4ab7-8b76-f2c049344464)

  9. Edit the config of the cloud-provider deployment 
  10. Add the `--disable-vmi-controller=true` to the Command Arguments field 
    ![image](https://github.com/user-attachments/assets/a39c5323-973e-448e-81d4-0dcd22e5b857)

  11. Save the config
  12. Delete the running cloud-provider of the old image version 
  13. Wait for the new container creating and running
  14. Check the cloud-provider container log again

</details>
