### ISSUE TITLE
[FEATURE] Bump k3s version to v1.20+

### ISSUE THREAD

**Issue by olljanat** [harvester/harvester#446]
**Is your feature request related to a problem? Please describe.**
I'm planning to start piloting Harvester and k3OS and would like to see latest new pre-release version which uses latest k3OS.

**Describe the solution you'd like**
v1.20.2+k3s1 version was marked as stable by https://github.com/k3s-io/k3s/pull/2821 so I think that it makes sense update Harvester to that one.

**Comment by brandond** [comment]
rancher/rancher does not support Kubernetes 1.20 yet; I am guessing harvester will support 1.20 after rancher does.

**Comment by olljanat** [comment]
OK. Issue related to that one looks to be https://github.com/rancher/rancher/issues/30134

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/110299015-2e63a580-8030-11eb-9ba6-493f3a7374b1.png)
