### ISSUE TITLE
Unable to provision RKE1 guest cluster on fully airgapped Ranhcer v2.6.11, stuck in waiting for API ...

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4461]
**Describe the bug**

In the fully airgapped Harvester v1.1.2 with Rancher v2.6.11 environment. 
We have a Harvester cluster imported with Rancher under the private docker image repository 

When we tried to provision a v1.23.16 `RKE1` guest cluster in a fully airgapped Rancher v2.6.11 with Harvester v1.1.2

* The RKE1 cluster provisioning process stuck in :  
  ```
  Waiting for API to be available
  ```

![image](https://github.com/harvester/harvester/assets/29251855/181abf2f-35c5-4b0a-905f-24bb9a15c3d0)

![image](https://github.com/harvester/harvester/assets/29251855/45c1be2b-77da-4227-ab74-4a800f175b72)
 

**To Reproduce**
1. Follow the environment preparation steps to build up an fully airgapped Rancher with Harvester: 
https://github.com/harvester/tests/blob/main/docs/content/manual/harvester-rancher/72-ipxe-auto-airgapped-rancher-integrate-harvester-.md
2. Set the "myregistry.local:5000" in Harvester `containerd-registry ` in settings 
3. Import Harvester to Rancher 
4. Create a node template
5. Specify the `Insecure Registries` and `Registry Mirrors` to "myregistry.local:5000"
![image](https://github.com/harvester/harvester/assets/29251855/da0b63b4-65d2-4320-b5dc-c124ea1ae879)
6. Provision the RKE1 v1.23.16 cluster 
7. Specify the private registry to "myregistry.local:5000"
![image](https://github.com/harvester/harvester/assets/29251855/b6501002-649a-4de2-90b2-9615b38c9370)
8. Start provisioning and monitor the guest cluster status

**Expected behavior**

Can provision RKE1 guest cluster into `running` state under fully airgapped Rancher and Harvester environment. 

**Support bundle**

**Related logs**

* [provisioning.log](https://github.com/harvester/harvester/files/12461317/provisioning.log)
 
* [kube-apiserver.log](https://github.com/harvester/harvester/files/12461546/kube-apiserver.log)

**Environment**
 - Harvester ISO version: v1.1.2
 - Rancher version: v2.6.11
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): four nodes on remote kvm machine 
 - kubernetes version: v1.23.16

**Additional context**
Both with and without installing Harvester cloud provide would encounter the same behavior

**Comment by bk201** [comment]
The cluster-agent in RKE cluster can't reach Rancher.

```
rke1-v12316-nocloud1:/tmp # kubectl --kubeconfig $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl/kubecfg-kube-node.yaml get pods -A
NAMESPACE       NAME                                      READY   STATUS             RESTARTS        AGE
cattle-system   cattle-cluster-agent-74f6755694-p4xqg     0/1     CrashLoopBackOff   188 (22s ago)   16h
cattle-system   cattle-node-agent-2m2gw                   1/1     Running            0               16h
cattle-system   kube-api-auth-hqg7v                       1/1     Running            0               16h
ingress-nginx   ingress-nginx-admission-create-dpbrk      0/1     Completed          0               16h
ingress-nginx   ingress-nginx-admission-patch-8mw6s       0/1     Completed          0               16h
ingress-nginx   nginx-ingress-controller-8zf8b            1/1     Running            0               16h
kube-system     calico-kube-controllers-ff6947446-5hcjm   1/1     Running            0               16h
kube-system     canal-7dtb4                               2/2     Running            0               16h
kube-system     coredns-7987c5cb7-b6dsj                   1/1     Running            0               16h
kube-system     coredns-autoscaler-56b4cc4db7-2dgbs       1/1     Running            0               16h
kube-system     metrics-server-97f564576-fs6m9            1/1     Running            0               16h
kube-system     rke-coredns-addon-deploy-job-wrkxj        0/1     Completed          0               16h
kube-system     rke-ingress-controller-deploy-job-2qf6b   0/1     Completed          0               16h
kube-system     rke-metrics-addon-deploy-job-l6thl        0/1     Completed          0               16h
kube-system     rke-network-plugin-deploy-job-jmgtg       0/1     Completed          0               16h
```

```
$ cd /var/log/pods
$ cat cattle-system_cattle-cluster-agent-74f6755694-p4xqg_a071c5bf-6cc3-4676-a92b-b26095a0e685/cluster-register/188.log
{"log":"dig: couldn't get address for 'resolver1.opendns.com': failure\n","stream":"stderr","time":"2023-08-29T09:04:36.205181399Z"}
{"log":"INFO: Environment: CATTLE_ADDRESS=10.42.0.9 CATTLE_CA_CHECKSUM=096e16f702ba56b8c9a64a303c573afb9992493f377d8d1e53db6c5fce2816b3 CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.43.44.68:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.43.44.68:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.43.44.68 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.43.44.68:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.43.44.68 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.43.44.68 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY=myregistry.local:5000 CATTLE_FEATURES=embedded-cluster-api=false,fleet=false,monitoringv1=false,multi-cluster-management=false,multi-cluster-management-agent=true,provisioningv2=false,rke2=false CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=f7ee87b4-4345-47a6-96ce-57d83c8b43f3 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=true CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-74f6755694-p4xqg CATTLE_SERVER=https://rancher-vagrant-vm.local CATTLE_SERVER_VERSION=v2.6.11\n","stream":"stderr","time":"2023-08-29T09:04:36.242864285Z"}
{"log":"INFO: Using resolv.conf: nameserver 10.43.0.10 search cattle-system.svc.cluster.local svc.cluster.local cluster.local options ndots:5\n","stream":"stderr","time":"2023-08-29T09:04:36.250096729Z"}
{"log":"ERROR: https://rancher-vagrant-vm.local/ping is not accessible (Could not resolve host: rancher-vagrant-vm.local)\n","stream":"stderr","time":"2023-08-29T09:04:40.326532715Z"}
```

**Comment by TachunLin** [comment]
Thanks for @irishgordo sharing all the steps to fix the provisioning the RKE1 guest cluster on the fully airgapped environment. We need to update the coredns file with the mapping to private registry to make it online

Just memo down all the steps here for the reference:

1. On the vm that is running RKE1, we need to scp the following binaries from your machine to the airgapped vm ip
2. Get the jq binary file 
  - Execute `wget https://github.com/jqlang/jq/releases/download/jq-1.6/jq-linux64` on the host machine, then `scp` over to the vm ip
3. Get the kubectl for the RKE1 guest cluster 
  - Execute `curl -LO https://dl.k8s.io/release/v1.28.1/bin/linux/amd64/kubectl` to get the kubectl binary, then also scp that over to the RKE1 vm
4. Log in to the RKE1 VM and set up the binaries: 
  - Make sure they are both executable `chmod +x` , and change the `jq-linux64`, to `jq`, then move that into `/usr/local/bin` (depends on your os release)
  - check kubectl, & jq can work on RKE1 guest cluster vm
5. Log in to the RKE1 VM that is stuck in the "waiting for api" state
  - switch to root user `sudo su -`
  - get the `cluster.rkestate` file from the RKE1 cluster 
    ```
        docker run --rm --net=host -v $(docker inspect kubelet --format '{{ range .Mounts }}{{ if eq .Destination "/etc/kubernetes" }}{{ .Source }}{{ end }}{{ end }}')/ssl:/etc/kubernetes/ssl:ro --entrypoint bash $(docker inspect $(docker images -q --filter=label=io.cattle.agent=true) --format='{{index .RepoTags 0}}' | tail -1) -c 'kubectl --kubeconfig /etc/kubernetes/ssl/kubecfg-kube-node.yaml get configmap -n kube-system full-cluster-state -o json | jq -r .data.\"full-cluster-state\" | jq -r .' > cluster.rkestate
    ```
  - Get the kubeconfig  admin from the `cluster.rkestate`
    ```
    cat cluster.rkestate | jq -r '.currentState.certificatesBundle."kube-admin".config' > kube-admin-kubeconfig.yml
    ```
  - validate admin kubeconfig is working
    ```
    kubectl --kubeconfig kube-admin-kubeconfig.yml get pods -A
    ```
  - edit the configmap
    ```
    kubectl --kubeconfig kube-admin-kubeconfig.yml edit cm/coredns -n kube-system
    ```
  - adding the ipv4 address of Rancher
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  Corefile: |
    .:53 {
        errors
        health {
          lameduck 5s
        }
        ready
        kubernetes cluster.local in-addr.arpa ip6.arpa {
          pods insecure
          fallthrough in-addr.arpa ip6.arpa
        }
        hosts threenode-rancher-vagrant-vm.local {
          192.168.3.34 threenode-rancher-vagrant-vm.local
          fallthrough
        }
        prometheus :9153
        forward . "/etc/resolv.conf"
        cache 30
        loop
        reload
        loadbalance
    } # STUBDOMAINS - Rancher specific change
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"Corefile":".:53 {\n    errors\n    health {\n      lameduck 5s\n    }\n    ready\n    kubernetes cluster.local in-addr.arpa ip6.arpa {\n      pods insecure\n      fallthrough in-addr.arpa ip6.arpa\n    }\n    prometheus :9153\n    forward . \"/etc/resolv.conf\"\n    cache 30\n    loop\n    reload\n    loadbalance\n} # STUBDOMAINS - Rancher specific change\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"coredns","namespace":"kube-system"}}
  creationTimestamp: "2023-08-27T23:32:10Z"
  name: coredns
  namespace: kube-system
  resourceVersion: "238185"
  uid: a2f7fb89-5dd7-463a-bc60-aa30d53b7c33
~       
```
  - (replacing the threenode-rancher-vagrant-vm.local) with the standard rancher-vagrant-vm.local and the proper ip, write & quit the file
6. Restart the `coredns`
  ```
  kubectl --kubeconfig kube-admin-kubeconfig.yml rollout restart deployments/coredns -n kube-system
  ```
7. Kill the pod of `cattle-cluster-agent`, and then allow it to rebuild another

It will create a fleet-agent pod and then everything should be good and the RKE1 cluster should come online

![image](https://github.com/harvester/harvester/assets/29251855/08b1cc5b-2422-4369-b9a9-a702524991d1)

**Comment by TachunLin** [comment]
According to the solution investigated in https://github.com/harvester/harvester/issues/4461#issuecomment-1707609144
After adding the dns mapping record and restart the coredns, we can provision RKE1 cluster under fully airgapped environment in Rancher. 
Thus close this issue.
