### ISSUE TITLE
[BUG]  The backup-target is not set to the latest value

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4463]
**Describe the bug**

The UI receives the websocket, but it is not rendered to the UI.

**To Reproduce**
1.  Add Custom additional-ca cert
2. then fill out the rest for the backup-target, the region, access key, secret access key
3. `access key` and `secret access key` will then be leaked to the front-end.   

**Expected behavior**

The UI should not display the access key and secret access key。  （If the websocket has pushed the right data）

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
https://github.com/harvester/harvester/issues/4360#issuecomment-1697147278

**Comment by WuJun2016** [comment]
One clue: websocket sometimes pushes an error message that  `failed to find schema harvesterhci.io.setting` 
reproduce step:
1. Generate S3 configuration `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.3.0/deploy/backupstores/minio-backupstore.yaml`
2. Configure `additional-ca`
3. Open the console in the UI, click `Network` , click `WS`, view websocket connections.   Select the ws that connects to `/v1/harvester` and view the message
![image](https://github.com/harvester/harvester/assets/24985926/ed49d12e-55ea-4f43-9e1d-57b04e58c8d9)

4. Configure a `backup-target`
5. Set the `additional-ca` configuration to null
6. Continue to configure ·backup-target· to save
7. Repeat steps 4, 5 and 6   （If the websocket connection is broken, you need to go check for a new link）

![image](https://github.com/harvester/harvester/assets/24985926/9b003197-3695-442f-8a61-2659933b9981)

and `resouce.stop`:
![image](https://github.com/harvester/harvester/assets/24985926/059ce4fd-2ac4-4d30-b9d3-a670ae2c0a71)


other clue:
Log in to the harvester cluster, open two tab pages, change the `backup-targe` in` tab A`, We should be able to receive websocket notifications in `tab B,` but we're not receiving them at the moment.

**Comment by WuJun2016** [comment]
@guangbochen  https://github.com/harvester/harvester/issues/4463#issuecomment-1698594370 This part needs the help of backend colleagues to check whether it meets the expectation

**Comment by WebberHuang1118** [comment]
Hi @torchiaf @a110605,

I can reproduce the `access key` and `secret access` exposure without CA in the following steps:
1. Preparing a S3 backup target
2. Setting Harvester backup target as the S3 backup
3. Refreshing browser
4. Setting the Harvester backup target to default
5. Setting the Harvester backup target back to the S3 backup
6. Checking if `access key` and `secret access` are exposed in the GUI
    ![key_pw](https://github.com/user-attachments/assets/8fff546f-c7c5-465d-80ea-2d25d63d5a74)
7. Continuing steps 4 - 6 if the exposure does not happen


Some information under the hood:
- The backend controller will set the `access key` and `secret access` in CR setting `backup-target`, after the setting sync with LH, it will set `access key` and `secret access` as empty

  - https://github.com/harvester/harvester/blob/d794ee0894eec1ff99c8d593cb619ec550a4c3a6/pkg/controller/master/backup/backup_target.go#L88-L96
  - https://github.com/harvester/harvester/blob/d794ee0894eec1ff99c8d593cb619ec550a4c3a6/pkg/controller/master/backup/backup_target.go#L136-L154
- We can find it from the web socket, generation `321` has `access key` and `secret access` content in the value field
  - ![bt_update321](https://github.com/user-attachments/assets/bd9258b6-cfcd-4458-9794-c5e842f0caf3)
- As generation `322`, `access key`, and `secret access` change to empty in the value field
  - ![bt_update322](https://github.com/user-attachments/assets/9d56c089-bf5f-45ab-b68f-95237d783b88)
- It seems GUI does not reflect the up-to-date status

**Comment by brandboat** [comment]
Test OK on [v1.4.0-dev-20240918](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918), close as fixed.

## Environment
* [`v1.4.0-dev-20240918`](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`

## Test Steps
- follow test steps in https://github.com/harvester/harvester/issues/4463#issuecomment-2328016995 and now 
`accessKeyId` and `secretAccessKey` in backup-target setting are empty.
  <img width="538" alt="image" src="https://github.com/user-attachments/assets/c77583d7-835b-4904-9c33-ac968b3db2bc">
- create a vm `test` with 2 cpu / 2 GB memory and create a vm backup
  <img width="1479" alt="image" src="https://github.com/user-attachments/assets/d0de3bbe-dca3-4980-ae20-5606f4615b1e">

- create vm `test2` from vm backup and all good.
  <img width="1476" alt="image" src="https://github.com/user-attachments/assets/0e3fdce8-bf81-4844-9216-fa3c61ce615c">
