### ISSUE TITLE
[Question] [help wanted] "Context canceled" while uploading image, how to solve this ?

### ISSUE THREAD

**Issue by JeroenProost** [harvester/harvester#4466]
Hello,

I know, there's #4057. It's probably me, but I can't find the solution in that thread.

I got my Harvester up and running. I even have a few vm's on there.

Only I want to create a vm running Suse Enterprise Linux 15 but I can't get the *.ISO (about 15 GB) uploaded to Images.
It always ends at 99% with the error "Context canceled". Any idea on what could be going wrong ?

Thank you very much,

**Comment by WebberHuang1118** [comment]
@JeroenProost 

The workaround is recorded at https://github.com/harvester/harvester/issues/3450#issuecomment-1443937746,

Since it changes the system ingress configuration,
Please make sure to understand every step before applying it.

And Harvester v1.2.0 should fix this issue. Thanks.

**Comment by JeroenProost** [comment]
@WebberHuang1118 

Thank you very much.
