### ISSUE TITLE
[BUG] OS and k3OS versions are reported incorrectly

### ISSUE THREAD

**Issue by olljanat** [harvester/harvester#447]
**Describe the bug**
Based on version history https://github.com/rancher/harvester-installer/commit/c462023fc110b49d38e0fe84fdab8cfa48855ca3 k3OS version on Harvester v0.1.0 should be at least "v0.19.4-dev.5" but now it is reported as "v0.1.3-dirty" which is harvester-installer version, not actual k3OS version.

Other issue is that on `/etc/os-release` is describing k3OS when it should describe Harvester and it's version (or example say `k3OS - Harvester edition` to clarify difference between these two.

**To Reproduce**
* Install Harvester v0.1.0
* Login to console
* Run these commands:
```bash
cat /etc/os-release
k3os --version
k3s --version
```

**Expected behavior**
OS and version informations are clear and unambiguous.

**Environment:**
 - Harvester ISO version: v0.1.0
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Surface Pro

**Comment by DoNotSayYes** [comment]
Validated on master-head

![image](https://user-images.githubusercontent.com/57614736/108674494-53302700-7520-11eb-979d-fa296f072cf3.png)
