### ISSUE TITLE
[BUG] Harvester Installer stuck at `A start job is running for /dev/mapper/live-rw`

### ISSUE THREAD

**Issue by mircea-pavel-anton** [harvester/harvester#4472]
**Describe the bug**

The installer for Harvester 1.2.0-rc6 hangs after the dracut pre-mount hook

**Environment**

 - Harvester ISO version: 1.2.0-rc6
 - Underlying Infrastructure:
   - CPU: Intel Core i9-7900X
   - RAM: 96Gb
   - Disks:
     - 1x 250Gb Intel NVMe
     - 2x 1Tb Samsung 970 Evo Plus
   - GPU:
     - Nvidia GTX 1050Ti

**Additional context**

![signal-2023-08-31-194540](https://github.com/harvester/harvester/assets/28601784/d5b332e0-20f2-4c71-b336-93c69527b03c)

**Comment by devclef** [comment]
I am currently experiencing this as well on a Dell optiplex, i5-12500. Nvme + SSD installed.

(I also had to remove ttys0 to get this far). 

Currently trying to boot via usb in uefi. Have tried two different usb sticks, and nearly every port.

I'm trying to wipe a install over an existing V1.1 install on the drives. If that somehow could be a cause . Did not expect to have issues installing on baremetal. 

Did you find a work around? If I do I'll share here.

**Comment by Taslack** [comment]
Had a similar error when I renamed the usb drive when creating the install drive.  Common issue explained here:

https://docs.harvesterhci.io/v1.2/install/usb-install#harvester-interactive-iso-hangs-with-the-usb-installation-method

**Comment by bk201** [comment]
This issue is also resolved in v1.2.1.
