### ISSUE TITLE
[BUG] Active/image OS image size become 1.5G

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4479]
**Describe the bug**

OS's active and passive image size becomes 1.5G in Harvester v1.2.0-rc6.
Its size is 3G in v1.1.2. It's not consistent.

**To Reproduce**
1. Install v1.2.0-rc6
2. Check image size
```
node1:~ # ls -alh /run/initramfs/cos-state/cOS
total 2.7G
drwxr-xr-x 2 root root 4.0K Aug 10 09:05 .
drwxr-xr-x 5 root root 4.0K Aug 10 09:31 ..
-rw-r--r-- 1 root root 1.5G Aug 10 09:15 active.img
-rw-r--r-- 1 root root 1.5G Aug 10 09:05 passive.img
```

**Expected behavior**

The image size should be 3G.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0-rc6.
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2-7007cb37-head` (09/08). Close this issue

### Test Result

- [x] New installation v1.2-head

   - [x] Check active.img and passive.img size is 3G.
   
    ```
      harv12-0908:~ # ls -alh /run/initramfs/cos-state/cOS/*
      -rw-r--r-- 1 root root 3.0G Sep  8 08:39 /run/initramfs/cos-state/cOS/active.img
      -rw-r--r-- 1 root root 3.0G Sep  8 08:34 /run/initramfs/cos-state/cOS/passive.img
    ```
   
- [x] Upgrading from v1.1.2 to v1.2-head

   - [x] Check active.img and passive.img size is 3G.
   ```
     harv112upd:~ # ls -alh /run/initramfs/cos-state/cOS/*
    -rw-r--r-- 1 root root 3.0G Sep  8 08:48 /run/initramfs/cos-state/cOS/active.img
    -rw-r--r-- 1 root root 3.0G Sep  8 08:48 /run/initramfs/cos-state/cOS/passive.img
   ```

### Test Information
* Test Environment: single nodes harvester on local kvm machine
* Harvester version: `v1.2-7007cb37-head` (09/08)

### Verify Steps
<details><summary>Execution Steps</summary>

  #### New installation 
  
  1. Create a new installation.
  2. Check active.img and passive.img size is 3G. 
  ```
  ls -alh /run/initramfs/cos-state/cOS/*
  ```

  #### Upgrade
  

  1. Create a 1.1.2 cluster.
  2. Upgrade to an ISO contains the PR change.
  3. Check active.img and passive.img size is 3G.

  ```
  ls -alh /run/initramfs/cos-state/cOS/*
  ```
</details>
