### ISSUE TITLE
[ENHANCEMENT] config sftp dynamically

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4480]
**Is your enhancement related to a problem? Please describe.**
Due to the security risk, the harvester disabled `sftp` by default.
We will provide the dynamic config way to let the user know the risk and still need `sftp`.

**Describe the solution you'd like**
Config when we create or join a cluster.

**Describe alternatives you've considered**
You could also refer to https://docs.harvesterhci.io/dev/install/update-harvester-configuration to update the related config.

**Additional context**
None

**Comment by TachunLin** [comment]
Verified **fixed** on `master-22d9e700-head` (24/01/10).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Fresh install: can use sftp to connect to Harvester node and /etc/ssh/sshd_config.d/sftp.conf exists $~~$</summary>

* On create node machine, we can sftp connect to the node and find the corresponding file
```
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> ssh rancher@192.168.0.131
Password: 
Last login: Wed Jan 10 05:42:44 2024 from 192.168.0.1
rancher@harvester-node-0:~> pwd
/home/rancher
rancher@harvester-node-0:~> vim test.txt
rancher@harvester-node-0:~> exit
logout
Connection to 192.168.0.131 closed.
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> sftp rancher@192.168.0.131
Password: 
Connected to 192.168.0.131.
sftp> ls -al
drwxr-xr-x    3 rancher  rancher      4096 Jan 10 05:48 .
drwxr-xr-x    3 root     root         4096 Jan 10 03:56 ..
-rw-------    1 rancher  rancher        92 Jan 10 05:48 .bash_history
drwx------    2 rancher  rancher      4096 Jan 10 03:56 .ssh
-rw-r-----    1 rancher  rancher         5 Jan 10 05:48 test.txt
sftp> get test.txt test.txt 
Fetching /home/rancher/test.txt to test.txt
/home/rancher/test.txt                                                                                                      100%    5     5.3KB/s   00:00
```
* On join node machine, we can sftp connect to the node and find the corresponding file
```
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> ssh rancher@192.168.0.32
Password: 
rancher@harvester-node-2:~> vim test.txt
rancher@harvester-node-2:~> exit
logout
Connection to 192.168.0.32 closed.
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> sftp rancher@192.168.0.32
Password: 
Connected to 192.168.0.32.
sftp> ls -al
drwxr-xr-x    3 rancher  rancher      4096 Jan 10 06:27 .
drwxr-xr-x    3 root     root         4096 Jan 10 04:27 ..
-rw-------    1 rancher  rancher        18 Jan 10 06:27 .bash_history
drwx------    2 rancher  rancher      4096 Jan 10 04:27 .ssh
-rw-r-----    1 rancher  rancher         5 Jan 10 06:27 test.txt
sftp> get test.txt test.txt 
Fetching /home/rancher/test.txt to test.txt
/home/rancher/test.txt               
```

* Include `/etc/ssh/sshd_config.d/*.conf` exists on node machine
```
rancher@harvester-node-2:~> sudo tail -n5 /etc/ssh/sshd_config
AllowAgentForwarding no
X11Forwarding no
AllowTcpForwarding no
MaxAuthTries 3
Include /etc/ssh/sshd_config.d/*.conf

rancher@harvester-node-1:~> cat /etc/ssh/sshd_config.d/sftp.conf
Subsystem	sftp	/usr/lib/ssh/sftp-server
```


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ After reboot machine, the sftp service and corresponding file exists  $~~$</summary>

* Check the sftp service and config file exists after reboot Harvester nodes
```
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> ssh rancher@192.168.0.32
Password: 
rancher@harvester-node-2:~> sudo tail -n5 /etc/ssh/sshd_config
AllowAgentForwarding no
X11Forwarding no
AllowTcpForwarding no
MaxAuthTries 3
Include /etc/ssh/sshd_config.d/*.conf
rancher@harvester-node-2:~> exit
logout
Connection to 192.168.0.32 closed.
harvester@localhost:~/Harvester/ipxe-examples/vagrant-pxe-harvester> sftp rancher@192.168.0.32
Password: 
Connected to 192.168.0.32.

```

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade from `v1.3.0-dev-20240105` to `master-0c47319a-head`,  the sftp service and corresponding file exists   $~~$</summary>

* The sftp service and corresponding file exists after upgrade to v1.3.0 master
```
rancher@harvester-node-0:~> cat /etc/ssh/sshd_config.d/sftp.conf
Subsystem	sftp	/usr/lib/ssh/sftp-server
rancher@harvester-node-0:~> exit
logout
Connection to 192.168.0.131 closed.
davidtclin@localhost:~/Documents/Project_Repo/ipxe-examples/vagrant-pxe-harvester> sftp rancher@192.168.0.131
Password: 
Connected to 192.168.0.131.
sftp>
```

 </details>


### Test Information
* Test Environment: 3 nodes harvester on remote kvm machine
* Harvester version: `master-22d9e700-head` (24/01/10)

### Verify Steps
<details><summary>Fresh installation</summary>

  1. Use ipex-example to provision Harvester
  2. Add the following sshd config to the config-create.yaml and config-join.yaml of Harvester configuration file
  ```
  os:
  sshd:
     sftp: true
  ```
  3. Provision the 3 nodes Harvester cluster
  4. After provisioning or upgrade complete, ssh to the management and worker node 
  5. Check the file exists 
  ```
  sudo tail -n5 /etc/ssh/sshd_config
  cat /etc/ssh/sshd_config.d/sftp.conf
  ```
  6. Use `sftp` to connect to Harvester, check the connection works
  ```
  sftp rancher@192.168.0.131
  ```
</details>
