### ISSUE TITLE
[BUG] Page Backup & Snapshot error after reset backup-target to default/empty value

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4483]
## Description
After reset **backup-target** back to default value, page **Backup & Snapshot** (**VM Backups**) shows error `"undefined" is not valid JSON`

## Environment
* Harvester
  * Version: `v1.2.0-rc6`
  * Profile: QEMU/KVM, single node (8C/16G/250G)
  * **ui-source**: Auto
* Chrome `116.0.5845.140` (Official Build) (64-bit)

## To Reproduce
> **Note** Click "►" to expand details.

1. <details>
   <summary>
   Go to "Backup & Snapshot", check page shows fine.
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/334812ce-dccb-4a8f-a379-2cfce1b37d10)
   </details>

1. <details>
   <summary>
   Go to "Advanced" -> "Settings" -> "backup-target" -> "Edit Setting", set a target (NFS or S3)
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/a9be8f8f-4a2a-497b-a924-b39aa363a210)
   </details>

1. <details>
   <summary>
   Create VM and take backup
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/8e0ab0d2-11bf-45a4-96b6-f370630113cc)
   </details>

1. <details>
   <summary>
   Go to "Backup & Snapshot", check page shows fine.
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/6a58dcc1-487d-4159-a6cf-92a74287717d)
   </details>

1. <details>
   <summary>
   Go to "Advanced" -> "Settings" -> "backup-target" -> "Edit Setting" -> "Use the default value" -> Save
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/7f1999c4-59c1-4dc8-b13e-b5dd85308991)
   ![image](https://github.com/harvester/harvester/assets/2773781/097ec293-80e7-47cd-af9e-63a153de4d9e)
   </details>

1. <details open>
   <summary>
   Go to "Backup & Snapshot", check page shows fine.
   ${~~~\color{red}\textsf{X, shows error "undefined" is not valid JSON}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/4a71bc0d-c097-4aad-93fd-0f0e5a7459fc)
   </details>

## Expected Behavior
Page "Backup & Snapshot" shows without problem.

## Note
1. Tried **clean cookie** and **incognito window**, but both not works.
2. Seems not happen when there is no backups (backup-target is empty)

**Comment by WuJun2016** [comment]
Hi， @albinsun   This issue is ready for testing.

**Comment by albinsun** [comment]
Provide test result for `v1.2-95dec1da-head` w/ ui-source `External`, close as fixed.


## Environment
* Harvester
  * Version: `v1.2-95dec1da-head`
  * Profile: QEMU/KVM, single node (8C/16G/250G)
  * ui-source: `External`
     ![image](https://github.com/harvester/harvester/assets/2773781/f3933de4-e45d-4f33-99c5-3a3d76641b9d)


## Test Steps
> **Note** Click "►" to expand details.

1. <details>
   <summary>
   Check "Backup & Snapshot" page
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/0ede3ad7-8908-40cf-b3b1-ba769fbed143)
   </details> 

1. <details>
   <summary>
   Go to "Advanced" -> "Settings" -> "backup-target" -> "Edit Setting", set NFS target
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/179802c0-95a7-441d-9471-be82b98cb50f)
   </details> 

1. <details>
   <summary>
   Check "Backup & Snapshot" page
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/2b30a5a0-0a30-4306-906c-540e1dca7c3e)
   </details> 

1. Create VM backup

1. <details>
   <summary>
   Check "Backup & Snapshot" page
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/3d36be0e-1ca7-4342-85b1-15a2b99d0d31)
   </details> 

1. <details>
   <summary>
   Go to "Advanced" -> "Settings" -> "backup-target" -> "Edit Setting" -> "Use the default value" -> Save
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/61df6255-6726-41e9-b1d8-5a7d8f63f62d)
   </details> 

1. <details>
   <summary>
   Check "Backup & Snapshot" page
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/f68e10a8-245c-4038-a5a1-b89c16bf5127)
   </details> 

1. <details>
   <summary>
   Go to "Advanced" -> "Settings" -> "backup-target" -> "Edit Setting", set Storage back
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/768f634f-a6fc-4f72-854a-92e69a47c34f)
   </details> 

1. <details>
   <summary>
   Check "Backup & Snapshot" page
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/1f977c1b-8b3a-4c29-9f00-3cc476ed6a7e)
   </details> 

1. <details>
   <summary>
   Restore New from backup
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/cd7c5ac1-acb4-4560-8b58-ddebb8753444)
   </details>
