### ISSUE TITLE
[BUG] The rancher-monitoring Pod stuck at terminating status when upgrading from v1.1.2 to v1.2.0-rc6

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4484]
**Describe the bug**

This is a tracking issue to the upstream one: kubernetes/kubernetes#116847

Basically, we found that it is possible to hit the issue when doing Harvester upgrades. The upgrade stuck in the apply-manifests phase.

<img width="572" alt="image" src="https://github.com/harvester/harvester/assets/1827717/bb55961b-65f9-4a28-8610-42ba7a65b396">

Take a deeper look into the apply-manifests Pod's log, it is waiting for all the monitoring-related Pods to terminate:

```
$ kubectl -n harvester-system logs hvst-upgrade-md6wr-apply-manifests-wqslg --tail=10
Tue Sep  5 10:20:39 UTC 2023
there are still 1 pods in cattle-monitoring-system to be deleted
Tue Sep  5 10:20:45 UTC 2023
there are still 1 pods in cattle-monitoring-system to be deleted
Tue Sep  5 10:20:50 UTC 2023
there are still 1 pods in cattle-monitoring-system to be deleted
Tue Sep  5 10:20:55 UTC 2023
there are still 1 pods in cattle-monitoring-system to be deleted
Tue Sep  5 10:21:00 UTC 2023
there are still 1 pods in cattle-monitoring-system to be deleted
```

The part of the script is doing a conversion that converts the `rancher-monitoring` ManagedChart to an Addon. After deleting the ManagedChart, it waits for all the dependents disappear before executing the conversion.

But one of the Pod is stuck in a terminating state, which is `prometheus-rancher-monitoring-prometheus-0`:

```
$ kubectl -n cattle-monitoring-system get pods                                  
NAME                                         READY   STATUS        RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0   0/3     Terminating   0          19d
```

```
$ kubectl -n cattle-monitoring-system get pod prometheus-rancher-monitoring-prometheus-0 -o jsonpath='{.metadata.uid}'
33f43165-6faa-4648-927d-69097901471c
```

Using the Pod's UID `33f43165-6faa-4648-927d-69097901471c` to search the kubelet's log in `/var/lib/rancher/rke2/agent/logs/kubelet.log`:

```
E0905 10:26:18.769199   17399 reconciler.go:208] "operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume \"pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\") pod \"33f43165-6faa-4648-927d-69097901471c\" (UID: \"33f43165-6faa-4648-927d-69097901471c\") : UnmountVolume.NewUnmounter failed for volume \"pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\") pod \"33f43165-6faa-4648-927d-69097901471c\" (UID: \"33f43165-6faa-4648-927d-69097901471c\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/vol_data.json]: open /var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/vol_data.json: no such file or directory" err="UnmountVolume.NewUnmounter failed for volume \"pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-7781c988-c35b-4cf8-89e6-f2907ef33603\") pod \"33f43165-6faa-4648-927d-69097901471c\" (UID: \"33f43165-6faa-4648-927d-69097901471c\") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/vol_data.json]: open /var/lib/kubelet/pods/33f43165-6faa-4648-927d-69097901471c/volumes/kubernetes.io~csi/pvc-7781c988-c35b-4cf8-89e6-f2907ef33603/vol_data.json: no such file or directory"
```

There are plenty lines of identical log indicating the same thing: the kubelet cannot unmount the volume used by the prometheus Pod because the `vol_data.json` file is missing.

**To Reproduce**

According to the upstream ticket, it cannot be reproduced reliably (in fact, almost not reproducible), probably caused by some peculiar race conditions.

**Expected behavior**

The volume should be unmounted correctly and the upgrade should be done successfully.

**Support bundle**

**Environment**
 - Harvester ISO version: upgrading from v1.1.2 to v1.2.0-rc6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VMs provisioned using ipxe-examples (air-gapped setup)

**Additional context**

Other related issues and previous fixes:

- longhorn/longhorn#5765
- kubernetes/kubernetes#116847
- kubernetes/kubernetes#120086

**Comment by starbops** [comment]
The workaround is to find out the stucking Pod and forcibly delete it.

```
$ kubectl get pods -n cattle-monitoring-system
NAME                                         READY   STATUS        RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0   0/3     Terminating   0          19d

$ kubectl delete pod prometheus-rancher-monitoring-prometheus-0 -n cattle-monitoring-system  --force
```

Thanks to @bk201 for providing the information!

**Comment by irishgordo** [comment]
> The workaround is to find out the stucking Pod and forcibly delete it.
> 
> ```
> $ kubectl get pods -n cattle-monitoring-system
> NAME                                         READY   STATUS        RESTARTS   AGE
> prometheus-rancher-monitoring-prometheus-0   0/3     Terminating   0          19d
> 
> $ kubectl delete pod prometheus-rancher-monitoring-prometheus-0 -n cattle-monitoring-system  --force
> ```
> 
> Thanks to @bk201 for providing the information!

Thanks for the workaround @bk201 @starbops :smile: :+1:   - this seems that this may need to be done multiple times before the upgrade can proceed - it does look to be working now after 2-3 times of forcefully deleting the prometheus pods and letting them be re-created.

**Comment by w13915984028** [comment]
When upgrading to v1.2.0/v1.2.1, the old `rancher-monitoring` and `rancher-logging` `managedchart` are deleted, and then two same naming objects of type addons.harvesterhci.io are created.  PR: https://github.com/harvester/harvester/pull/3380

But the deleting of `managedchart` seems not working fully as expected, a short summary of related phenomenon: https://github.com/harvester/harvester/issues/4488#issuecomment-1838904523

The workaround is booked: https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#6-an-upgrade-is-stuck-in-the-upgrading-system-service-state

**Comment by bk201** [comment]
The path (replacing a management chart with an RKE2 HelmChart) doesn't exist in recent versions, users are not supposed to hit this.
