### ISSUE TITLE
[BUG] Upgrade four nodes fully airgapped Harveter to v1.2.0-rc6 stuck in upgrading system service

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4488]
**Describe the bug**

When upgrade the four nodes fully airgapped Harvester from v1.1.2 to v1.2.0-rc6. 
The upgrade process stuck in `Upgrading System Service` and can't proceed. 

![image](https://github.com/harvester/harvester/assets/29251855/083c68bc-cdf0-4728-9abf-bd45c23d2995)

Check the apply-manifest job logs, it keeps prompting following message.
  ```
  $ kubectl logs jobs/hvst-upgrade-nsmms-apply-manifests -n harvester-system
  instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
  instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
  instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
  ```
 
**To Reproduce**
1. Use [vagrant-pxe-airgap-harvester](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-airgap-harvester) to provision a four nodes fully airgapped v1.1.2 Harvester with Rancher v2.6.11
2. Import Harvester to Rancher 
3. Provision an RKE2 guest cluster 
4. Upgrade the airgapped Rancher to v2.7.6 
5. Upgrade Harvester to v1.2.0-rc6
6. Encounter can't click the upgrade button, hit the known issue #3616, apply the workaround to proceed the upgrade 
7. The upgrade stuck in `creating upgrade repository` , hit another known issue #4246, 
8. Apply the workaround to delete the replica and start over the upgrade 
9. Upgrade failed at preloading image on node-0 
10. Found the date time not synced up between nodes machines
11. Setup an internal NTP server on pxe_server machine
12. Use datetimectl to sync date time with the internal NTP server 
13. Shutdown the Rancher VM and Harvester node VM machine in sequence
14. Start all above VM machines in the descending order 
15. Wait for the upgrade to proceed and monitor the process

**Expected behavior**

Can completely upgrade the four nodes fully airgapped Harvester from v1.1.2 to v1.2.0-rc6

**Support bundle**

[supportbundle_a6849751-146c-442d-8efa-20ab591b7694_2023-09-05T14-27-37Z.zip](https://github.com/harvester/harvester/files/12526120/supportbundle_a6849751-146c-442d-8efa-20ab591b7694_2023-09-05T14-27-37Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2 to v1.2.0-rc6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 4 nodes remote kvm machines
 - Rancher version: v2.6.11 to v2.7.6

**Additional context**
Found the etcd contains the following log
  ```
  {"level":"warn","ts":"2023-09-05T05:54:01.481Z","caller":"etcdserver/util.go:166","msg":"apply request took too long","took":"104.864456ms","expected-duration":"100ms","prefix":"read-only range ","request":"key:\"/registry/secrets/\" range_end:\"/registry/secrets0\" ","response":"range_response_count:195 size:20674007"}
  ```

**Comment by bk201** [comment]
When we checked the env, the issue is gone:
```
instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
instance-manager-r pod count is not 1 on node harvester-node-1, will retry...
Checking instance-manager-r pod on node harvester-node-1 OK.
Checking instance-manager-r pod on node harvester-node-2...
instance-manager-r pod count is not 1 on node harvester-node-2, will retry...
Checking instance-manager-r pod on node harvester-node-2 OK.
Checking instance-manager-r pod on node harvester-node-3...
Checking instance-manager-r pod on node harvester-node-3 OK.
```

But it's waiting for rancher-logging pods to be gone:
```
there are still 17 pods in cattle-logging-system to be deleted
Tue Sep  5 23:27:07 UTC 2023
there are still 17 pods in cattle-logging-system to be deleted
Tue Sep  5 23:27:13 UTC 2023
there are still 17 pods in cattle-logging-system to be deleted
Tue Sep  5 23:27:18 UTC 2023
there are still 17 pods in cattle-logging-system to be deleted
Tue Sep  5 23:27:23 UTC 2023
there are still 17 pods in cattle-logging-system to be deleted
```

**Comment by bk201** [comment]
> 
> ```
> there are still 17 pods in cattle-logging-system to be deleted
> Tue Sep  5 23:27:07 UTC 2023
> there are still 17 pods in cattle-logging-system to be deleted
> Tue Sep  5 23:27:13 UTC 2023
> there are still 17 pods in cattle-logging-system to be deleted
> Tue Sep  5 23:27:18 UTC 2023
> there are still 17 pods in cattle-logging-system to be deleted
> Tue Sep  5 23:27:23 UTC 2023
> there are still 17 pods in cattle-logging-system to be deleted
> ```

@w13915984028 It seems we have seen this before, do we have a related issue.

**Comment by w13915984028** [comment]
Regarding this issue, there are two types of phenomenon observed:

(1) One special POD is left, it may be related to an upstream issue
#4484 

(2) All PODs in cattle-logging-system or cattle-monitoring-system are left, it seems to: after deleting an `ManagedChart`, none of the PODs of the sub depolyment/statefulset/daemonset is deleted; suspect this is related to `fleet-agent` (may even further with `helm`, it gives up deleting `ManagedChart` derived resources implicitly due to `unknown` reason, causes those PODs are left.
#4488
#4698 

We did not try to forcely delete the remaining `deployment/statefulset/daemonset/pod/...` in the upgrade script.

**Comment by w13915984028** [comment]
When upgrading to v1.2.0/v1.2.1, the old `rancher-monitoring` and `rancher-logging` `managedchart` are deleted, and then two same naming objects of type addons.harvesterhci.io are created.  PR: https://github.com/harvester/harvester/pull/3380

But the deleting of `managedchart` seems not working fully as expected, a short summary of related phenomenon: https://github.com/harvester/harvester/issues/4488#issuecomment-1838904523

The workaround is booked: https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#6-an-upgrade-is-stuck-in-the-upgrading-system-service-state

**Comment by w13915984028** [comment]
@TachunLin Please double check, this ticket seems could be closed, thanks.

**Comment by TachunLin** [comment]
@w13915984028 
This issues was originally found during test the four nodes airgapped upgrade. 
The environment was built upon nested vm on a host machine. 

The resource allocated for each node would be limited which would cause unexpected broken of the pods or Harvester node. 

The I think we can close this issue since it's more of an environment related symptom and track the similar behavior in other issue https://github.com/harvester/harvester/issues/4698
