### ISSUE TITLE
[BUG] VM stuck in *Starting* state during upgrade (v1.1.2 -> v1.2.0-rc6)

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4489]
### Describe the bug
1. The node start pre-draining and migrating VMs to other nodes (spending long time), then VMs (RKE1 & RKE2) been shutdown and volume detached.
2. Start those VMs, one of VMs stuck in **Starting** status.
3. Attach those detached volumes, showing **Ready for workload: Not Ready**
![image](https://github.com/harvester/harvester/assets/5169694/a6058578-7a44-4908-8e00-6bee3953481d)
![image](https://github.com/harvester/harvester/assets/5169694/84a5bde4-4304-4cfa-90e0-4bbd3e116fba)
![image](https://github.com/harvester/harvester/assets/5169694/9daf65e4-86e2-46c9-80ef-4a21d8156db0)

### To Reproduce
1. Install Harvester with at least 4 nodes
2. Create an image for VM creation
3. Create VLAN
4. Create 2 VMs with 1 snapshot and 1 backup
5. Import Harvester into Rancher 2.7.6
6. Create RKE1 and RKE2 cluster (1 node)
7. Install Harvester Cloud Provider and CSI Driver
8. Create DHCP load balancer service (only RKE1 cluster)
9. Create Nginx deployment with new Harvester PVC
10. Upgrade Harvester

### Expected behavior
Cluster should be upgraded successfully

## Environment:
 - Harvester ISO version: **v1.1.2** -> **v1.2.0-rc6**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

### Additional context
1. The node was stuck in post-draining to wait the PVC (which was detached automatically) to be healthy.
2. The node was encountering **IOError** for those VMs hosted on it.

![image](https://github.com/harvester/harvester/assets/5169694/dfd807f9-4c52-4062-b267-0945814212bc)

### Support bundle
[harvester-vnjt8.zip](https://github.com/harvester/harvester/files/12526753/harvester-vnjt8.zip)
[harvester-m7kw2.zip](https://github.com/harvester/harvester/files/12526754/harvester-m7kw2.zip)
[harvester-zn8hn.zip](https://github.com/harvester/harvester/files/12526755/harvester-zn8hn.zip)
[harvester-c5624.zip](https://github.com/harvester/harvester/files/12526756/harvester-c5624.zip)
[supportbundle_99313229-b7fb-4458-9aa2-fc728f50e8d3_2023-09-05T17-41-18Z.zip](https://github.com/harvester/harvester/files/12526757/supportbundle_99313229-b7fb-4458-9aa2-fc728f50e8d3_2023-09-05T17-41-18Z.zip)

**Comment by bk201** [comment]
I'll close this for now, it's not easy to repro.
https://github.com/harvester/harvester/issues/4432 is fixed on the LH side, please reopen if see this again.
