### ISSUE TITLE
[BUG] image upload fail

### ISSUE THREAD

**Issue by caolizhong-pm** [harvester/harvester#449]
**Describe the bug**

image upload fail

**To Reproduce**
1. Go to 'image'，create
2. after sometime, display error "please reduce request"

**Expected behavior**

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
Can you provide more details? e.g. Installation mode, node number and size, etc.

**Comment by caolizhong-pm** [comment]
mode: helm chart; node number:2; size: any size

**Comment by gitlawr** [comment]
Can you ssh to the node and run `kubectl -n harvester-system get po -l "app=minio"` to check the MinIO component?

Did the error happen consistently or occasionally?

**Comment by caolizhong-pm** [comment]
all the pod this running when execute the command.
Error is always there.



Best Regards

产品部 曹力中

 杭州网银互联科技股份有限公司
   -企业级IT管理服务专家-
 
M/T：86+ 18768117657
E-mail：caolizhong@netbank.cn
WEB：http://www.netbank.cn
Add.：杭州市西湖区华星路96号互联网金融大厦16楼

 
From: Lawrence Li
Date: 2021-01-28 11:48
To: rancher/harvester
CC: caolizhong-pm; Author
Subject: Re: [rancher/harvester] [BUG] image upload fail (#449)
Can you ssh to the node and run kubectl -n harvester-system get po -l "app=minio" to check the MinIO component?
Did the error happen consistently or occasionally?

**Comment by gitlawr** [comment]
Can you check if there's any error logs in minio pods?

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/releases/tag/v0.3.0.
