### ISSUE TITLE
[BUG] Post Draining `return code: 32` on removal of Elemental issues

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4493]
**Describe the bug**

**_NOTE: This does not impact the upgrade process, the cluster was able to upgrade successfully_**

It seems at post-draining, there is a point where at least from the logs:
```
kubectl logs jobs/hvst-upgrade-md6wr-post-drain-harvester-node-1 -n harvester-system
```
It struggles to remove `elemental` binary:
```
+ GRUBENV_FILE=/oem/grubenv
+ chroot /host /bin/bash -c 'if ! [ -f /oem/grubenv ]; then grub2-editenv /oem/grubenv create; fi'
+ umount /host/usr/bin/elemental
+ umount /host/tmp/tmp.G0W6LinMB6
+ rm -rf /host/usr/local/upgrade_tmp/tmp.u8YWut8e3W
+ reboot_if_job_succeed
+ cat
+ cat
+ chmod +x /host/tmp/upgrade-reboot.sh
+ cat
+ chroot /host systemctl daemon-reload
+ chroot /host systemctl start upgrade-reboot
+ clean_up_tmp_files
+ '[' -n /host/tmp/tmp.G0W6LinMB6 ']'
Try to unmount /host/tmp/tmp.G0W6LinMB6...
+ echo 'Try to unmount /host/tmp/tmp.G0W6LinMB6...'
+ umount /host/tmp/tmp.G0W6LinMB6
umount: /host/tmp/tmp.G0W6LinMB6: not mounted.
+ echo 'Umount /host/tmp/tmp.G0W6LinMB6 failed with return code: 32'
+ '[' -n /host/usr/bin/elemental ']'
+ echo 'Try to unmount /host/usr/bin/elemental...'
+ umount /host/usr/bin/elemental
Umount /host/tmp/tmp.G0W6LinMB6 failed with return code: 32
Try to unmount /host/usr/bin/elemental...
umount: /host/usr/bin/elemental: not mounted.
+ echo 'Umount /host/usr/bin/elemental failed with return code: 32'
+ echo 'Clean up tmp files...'
+ '[' -n '' ']'
+ '[' -n /host/usr/local/upgrade_tmp/tmp.u8YWut8e3W ']'
+ echo 'Try to remove /host/usr/local/upgrade_tmp/tmp.u8YWut8e3W...'
+ rm -vf /host/usr/local/upgrade_tmp/tmp.u8YWut8e3W
Umount /host/usr/bin/elemental failed with return code: 32
Clean up tmp files...
Try to remove /host/usr/local/upgrade_tmp/tmp.u8YWut8e3W...
```

**To Reproduce**
1. Upgrade air-gap cluster from v1.1.2->v1.2.0-rc6

**Expected behavior**
That there wouldn't be issues unmounting or removing Elemental binary - exit codes would be 0.

**Environment**
 - Harvester ISO version: v1.1.2->v1.2.0-rc6
 - Underlying Infrastructure: qemu/kvm

**Additional context**
[kubect-post-drain-log.log](https://github.com/harvester/harvester/files/12541179/kubect-post-drain-log.log)

Seems that may be hard to reproduce, setting as `rare` for placeholder.

**Comment by starbops** [comment]
The `clean_up_tmp_files` function in the `upgrade_node.sh` is a registered handler that will take care of any abnormal exit if an error occured when executing `upgrade_os` function. So it's just a safety net for us to clean up any potential dangling mounts. In a normal execution, it will report errors on unmounting them because those two are already unmounted in the normal code path as you can see the following lines appeared in the upper part of the log you provided:

```
...
+ umount /host/usr/bin/elemental
+ umount /host/tmp/tmp.G0W6LinMB6
...
```

However, we could improve the condition checks against those two mount point to prevent those confusing logs.

**Comment by irishgordo** [comment]
@starbops thanks for this fix :smile: :+1: 

This looks great in the scenarios of:

- v1.2.1 -> v1.2-head

- v1.2-head -> v1.3-head

Attaching the logs.
I'll go ahead and close this out :smile: :+1: 

[upgrade-post-drain-job-v1.2-head-v1.3-head.txt](https://github.com/harvester/harvester/files/14487814/upgrade-post-drain-job-v1.2-head-v1.3-head.txt)
[upgrade-post-drain-job-v1.2.1-v1.2-head.txt](https://github.com/harvester/harvester/files/14487815/upgrade-post-drain-job-v1.2.1-v1.2-head.txt)
