### ISSUE TITLE
[BUG] Duplicated WWN blockdevice

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4494]
**Describe the bug**
There are two blockdevices with the same WWN if we use the dual port sas device.
If we try to provision these two devices, one of them would be broken. (due to force format)

**To Reproduce**
Try to attach the dual port sas device to the harvester.

**Expected behavior**
Blockdevices should not have more than one device have the same WWN.

**Support bundle**
[supportbundle_dfeb991a-3478-4ac7-869a-4fa4e4341c37_2023-09-04T22-40-14Z.zip](https://github.com/harvester/harvester/files/12544421/supportbundle_dfeb991a-3478-4ac7-869a-4fa4e4341c37_2023-09-04T22-40-14Z.zip)

**Environment**
 - Harvester ISO version: v1.2.0-rc6
 - Node-Disk-Manager version: v0.5.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Checking with following logs
```
2023-09-04T22:33:35.458406526Z time="2023-09-04T22:33:35Z" level=info msg="Create new device fe8eacdf009a23135a7ee8cf315f8bbc with wwn: 0x5f8db4c142300888"
2023-09-04T22:33:35.460543540Z time="2023-09-04T22:33:35Z" level=info msg="Add new block device fe8eacdf009a23135a7ee8cf315f8bbc with device: /dev/sdd"
2023-09-04T22:33:35.470381595Z time="2023-09-04T22:33:35Z" level=info msg="Create new device 591e66c592678b93954b28e641838f88 with wwn: 0x5f8db4c142300888"
2023-09-04T22:33:35.472632631Z time="2023-09-04T22:33:35Z" level=info msg="Add new block device 591e66c592678b93954b28e641838f88 with device: /dev/sde"
```

**Comment by flapili** [comment]
Hi, I was the guys on slack with the error 😅 if you need extra info you can @ me

**Comment by irishgordo** [comment]
**Validation Question:**

@Vicente-Cheng just wanted to check if:

```
rancher@testv130rc1singlenode:~> lsscsi --wwn
[0:0:0:0]    cd/dvd  QEMU     QEMU DVD-ROM     2.5+                                  /dev/sr0 
[6:0:0:1]    disk    QEMU     QEMU HARDDISK    2.5+  0x5000c50017654321              /dev/sda 
[6:0:0:2]    disk    QEMU     QEMU HARDDISK    2.5+                                  /dev/sdb 
rancher@testv130rc1singlenode:~> lsblk
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
loop0    7:0    0     3G  1 loop /
sda      8:0    0    20G  0 disk 
sdb      8:16   0    20G  0 disk 
sr0     11:0    1  1024M  0 rom  
vda    253:0    0   400G  0 disk 
├─vda1 253:1    0     1M  0 part 
├─vda2 253:2    0    50M  0 part /oem
├─vda3 253:3    0     8G  0 part 
├─vda4 253:4    0    15G  0 part /run/initramfs/cos-state
├─vda5 253:5    0   200G  0 part /var/lib/longhorn
│                                /var/crash
│                                /var/lib/third-party
│                                /var/lib/cni
│                                /var/lib/wicked
│                                /var/lib/kubelet
│                                /var/lib/rancher
│                                /var/log
│                                /usr/libexec
│                                /root
│                                /opt
│                                /home
│                                /etc/pki/trust/anchors
│                                /etc/cni
│                                /etc/iscsi
│                                /etc/ssh
│                                /etc/rancher
│                                /etc/systemd
│                                /usr/local
└─vda6 253:6    0 176.9G  0 part /var/lib/harvester/defaultdisk

```

Seeing the second block device present on the Harvester node is expected, even if there is no WWN coming down for the second block device?

It seems correct that it can only add `/dev/sda` as both sda & sdb have the same wwn, but wwn is not present for sdb in the node itself, the block device is present however.

![Screenshot from 2024-01-25 14-59-48](https://github.com/harvester/harvester/assets/5370752/95480540-4485-4e8b-952c-a3ad5db44cbe)
![Screenshot from 2024-01-25 14-56-58](https://github.com/harvester/harvester/assets/5370752/d0d6d97b-627a-406c-8597-aa0b0bbcb5b1)

**Comment by Vicente-Cheng** [comment]
Hi @irishgordo, I am not sure how the `lsscsi` works.
I also get the same result as you
```
harvester-node-0:~ # udevadm info /dev/sdd |grep WWN
E: ID_WWN_WITH_EXTENSION=0x5000c50015282379
E: ID_WWN=0x5000c50015282379
harvester-node-0:~ # udevadm info /dev/sdc |grep WWN
E: ID_WWN_WITH_EXTENSION=0x5000c50015282379
E: ID_WWN=0x5000c50015282379

harvester-node-0:~ # lsscsi --wwn
[4:0:0:0]    disk    QEMU     QEMU HARDDISK    2.5+  0x5000c50015282379              /dev/sdc
[4:0:0:1]    disk    QEMU     QEMU HARDDISK    2.5+                                  /dev/sdd
```

Seems UI and NDM work as expected.
So, we could ignore the `lsscsi` result.

**Comment by irishgordo** [comment]
Sounds good :smile: - I'll go ahead and close this out

**Comment by flapili** [comment]
hey (harvester 1.3 rc 3)

I'm still able to add duplicated devices from the UI
![image](https://github.com/harvester/harvester/assets/29481952/851fe34b-eab2-44d6-8116-042671903c51)

an example of missmatch /dev path
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: harvesterhci.io/v1beta1
kind: BlockDevice
metadata:
  creationTimestamp: "2024-03-01T01:09:39Z"
  finalizers:
  - wrangler.cattle.io/harvester-block-device-handler
  generation: 3
  labels:
    kubernetes.io/hostname: node-01
    ndm.harvesterhci.io/device-type: disk
  name: b1361d2d5c218bf031a92f5dda5e74ca
  namespace: longhorn-system
  resourceVersion: "40291"
  uid: b9288156-2f81-4cf1-9a97-eac42cee003f
spec:
  devPath: /dev/sdc
  fileSystem:
    mountPoint: ""
  nodeName: node-01
status:
  deviceStatus:
    capacity:
      physicalBlockSizeBytes: 512
      sizeBytes: 1000204886016
    details:
      busPath: pci-0000:01:00.0-sas-phy1-lun-0
      deviceType: disk
      driveType: SSD
      model: PNY_1TB_SATA_SSD
      ptUUID: 4fa29d11
      serialNumber: PNF14230008880900695
      storageController: SCSI
      vendor: ATA
      wwn: "0x5f8db4c142300888"
    devPath: /dev/sdd
    fileSystem:
      isReadOnly: true
      mountPoint: ""
      type: ""
    partitioned: false
  provisionPhase: Unprovisioned
  state: Active

```

**Comment by Vicente-Cheng** [comment]
Hi @flapili,

Did you add storage multiple times on UI?
Could you also share the logs from node-disk-manager? (or generate a support-bundle for it?)

**Comment by flapili** [comment]
Hi, @Vicente-Cheng 

I only added on disk this night and stopped when I saw the issue

[supportbundle_df5b45e1-d374-4db6-a812-3ba8ef4ff01a_2024-03-01T15-51-37Z.zip](https://github.com/harvester/harvester/files/14463190/supportbundle_df5b45e1-d374-4db6-a812-3ba8ef4ff01a_2024-03-01T15-51-37Z.zip)

does longhgorn v2 engine storage with block device will solve definively the wwn issue ?

ps: I tried to add disk as block from longhorn ui but can't enable v2 engine storage due to hugepages settings

**Comment by Vicente-Cheng** [comment]
> Hi, @Vicente-Cheng
> 
> I only added on disk this night and stopped when I saw the issue

Was your cluster created recently?
I can not find the adding logs from the SB.

I will reproduce your cases on my test environment. 
> 
> [supportbundle_df5b45e1-d374-4db6-a812-3ba8ef4ff01a_2024-03-01T15-51-37Z.zip](https://github.com/harvester/harvester/files/14463190/supportbundle_df5b45e1-d374-4db6-a812-3ba8ef4ff01a_2024-03-01T15-51-37Z.zip)
> 
> does longhgorn v2 engine storage with block device will solve definively the wwn issue ?
> 
> ps: I tried to add disk as block from longhorn ui but can't enable v2 engine storage due to hugepages settings

I think the Longhorn v2 engine uses the block device directly, but you still need to give the promising path.
The path like `/dev/sdx` is not guaranteed as the same device after reboot.

NDM does not support provision for v2 engine, so at this moment. If you want to use v2 engine, you might need to fill up the disk related info to longhorn.

**Comment by flapili** [comment]
> Was your cluster created recently?
yes, few hours ago (~12h maybe)

> NDM does not support provision for v2 engine, so at this moment. If you want to use v2 engine, you might need to fill up the disk related info to longhorn.

I'll try to update grub to use hugepages and pass `/dev/disk/by-id/scsi-SATA_PNY_1TB_SATA_SSD_PNF142300088` to longhorn

**Comment by Vicente-Cheng** [comment]
Reopen because the test is failed (REF: https://github.com/harvester/harvester/issues/5446#issuecomment-2112177685)

**Comment by Vicente-Cheng** [comment]
We had the backport issue for v1.3 milestone (https://github.com/harvester/harvester/issues/5944) and it was already closed.

Also, another user report the duplicated WWN issue again for v1.4 (https://github.com/harvester/harvester/issues/6604)
We could trace the above issue.

So, I closed this issue. If there is any wwn issue, please open a new one for tracking.
Thanks!
