### ISSUE TITLE
[BUG] cluster member should not show the save button in host edit page

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#4496]
**Describe the bug**

[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBZ1YyIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--b33cdc4c60079528f2bc092c4592b8a53aabe26e/image.png)

The host page shows a save button, but clicking on it gives an error.

**To Reproduce**
1. Importing harvester clusters into rancher
2. Create the cluster member user and assign cluster member privileges to the harvester cluster.
3. Go to the harvester host page and click the Save button.

**Expected behavior**

The save button should not be displayed (or the user should not go to the edit page)

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0-rc6
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
I wasn't able to reproduce the problem consistently (only one successful reproduction after many tries)

**Comment by torchiaf** [comment]
@bk201 I couldn't reproduce it in Rancher 2.9-head / Harvester v1.3-head. Should we keep it open for further investigations ?
