### ISSUE TITLE
[BUG] storage parameters of cloned vmimage cannot be changed

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#4506]
**Describe the bug**

**To Reproduce**
1. create a storageclass provider=longhorn, replicas=1
2. use the storageclass to create a vm image
3. clone the vmimage
4. change the storageclass to `harvester-longhorn`

**Expected behavior**

the newly created vmimage's replicas should be 3, not 1

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2-head. v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
**Workaround**
- **Avoid Using VM Image 'Clone'**: If possible, refrain from using the VM Image  'Clone' operation.
- **Do Not Modify StorageClass After Cloning**: If you choose to clone a VM Image, avoid making any modifications to the StorageClass associated with it after the cloning process.
- **Keep StorageClass Parameters Consistent After Cloning**: If you must modify the StorageClass after cloning, ensure that the parameters of the modified StorageClass remain the same as those of the original StorageClass.
- **Manual Editing of 'spec.storageClassParameters' After Cloning**: If you have cloned a VMImage and made modifications to the StorageClass, make sure to manually edit the 'spec.storageClassParameters' in the YAML file to align with your changes.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/250G)
  * ui-source: `Auto`

## Test Cases
### Customized storage class image -> Default storage class 
1. <details>
      <summary>
      Create a storage class <strong>mysc</strong> with provisioner <code>Longhorn(CSI)</code> and replicas <code>1</code>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/9a4f09e5-e52e-4281-a295-34c78b1156c6)
   </details>

2. <details>
      <summary>
      Create VM image <b>focal-mysc</b> using <b>mysc</b>
      </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/8cbae0a5-2ed3-4097-9ac4-71bef073d57f)
      ![image](https://github.com/harvester/harvester/assets/2773781/b1a7012d-9710-4a62-88eb-b1b2e917bc53)
   </details>

   * Check storage class is `mysc` :white_check_mark: 
   * Check image replica is `1` :white_check_mark: 

3. <details>
      <summary>
      Create VM image <strong>focal-clone2default</strong> by cloning <strong>focal-mysc</strong> using the default <code>harvester-longhorn</code>
      </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/37698d01-94df-4e21-bc34-eeb57a107db9)
      ![image](https://github.com/harvester/harvester/assets/2773781/00508e99-8eec-46bc-88e5-0e5141360bc7)
      ![image](https://github.com/harvester/harvester/assets/2773781/076c0712-b61f-4548-a6e6-dc0e66fec1ff)
      ![image](https://github.com/harvester/harvester/assets/2773781/fa35ec23-7ab5-47ad-b000-1e97045eae3f)
   </details>

   * Check storeage class is `harvester-longhorn` :white_check_mark: 
   * Check replicas should be `3` :white_check_mark: 

  
### Default storage class image -> Customized storage class 
1. <details>
      <summary>
      Create a storage class <b>mysc</b> with provisioner <code>Longhorn(CSI)</code> and replicas <code>1</code>
      </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/9a4f09e5-e52e-4281-a295-34c78b1156c6)   
   </details>

2. <details>
      <summary>
      Create VM image <strong>jammy-default</strong> using default <code>harvester-longhorn</code>
      </summary>
   
      ![image](https://github.com/harvester/harvester/assets/2773781/18abcfee-9ce8-4689-9d5c-ccdc42d92277)
      ![image](https://github.com/harvester/harvester/assets/2773781/212d2f11-4315-416f-ba3d-8bd73b953c2f)
   </details>

   * Check storage class is `harvester-longhorn` :white_check_mark: 
   * Check image replica is `3` :white_check_mark: 
   

3. <details>
      <summary>
      Create VM image <strong>jammy-clone2mysc</strong> by cloning <strong>jammy-default</strong> using the customized <code>mysc</code>
      </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/4f1a97b1-4978-4975-b94b-0be1316b3f79)
      ![image](https://github.com/harvester/harvester/assets/2773781/ccb2ef84-2f17-47b2-8e41-f6d7db132c15)
   </details>

   * Check storeage class is `mysc` :white_check_mark: 
   * Check replicas should be `1` :white_check_mark: 
   

## Note
1. This issue can be reproduce in `v1.1.2`
