### ISSUE TITLE
[FEATURE] Ability to save and export VM image without manual copy workaround

### ISSUE THREAD

**Issue by mkoperator** [harvester/harvester#451]
A non-manual way to copy and export VM images needed for our use-case where we set up and modify windows VMs before distribution.

Currently, if we update a VM and want to distribute it, we have to shut down the VM, attach the pv to a container, and create an image copy to upload manually.

Ideally, this would be done with a button click, crd, or API call.

**Comment by yasker** [comment]
Duplicate of https://github.com/rancher/harvester/issues/568

**Comment by yasker** [comment]
Close this as the duplicate of #568.
