### ISSUE TITLE
[BUG] Unable to install to MBR disks

### ISSUE THREAD

**Issue by jaevans** [harvester/harvester#4515]
**Describe the bug**

Unable to install to MBR disks.

**To Reproduce**
1. Start harvester install.
2. Set "Use MBR partitioning scheme" to "Yes" (or `force_mbr: true` in install script)
3. continue with install

**Expected behavior**

Install completes successfully

**Support bundle**

**Environment**
 - Harvester ISO version:  1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL380 

**Additional context**
The failure actually comes from elemental. The partition type should be "msdos" in `/tmp/elemental/config.yaml`, but is 'mbr'.

The exact error is 
```
time="2023-09-11T22:19:41Z" level=info msg="[stdout]: \x1b[36mINFO\x1b[0m[2023-09-11T22:19:41Z] Starting elemental version 0.3.1             "
time="2023-09-11T22:19:41Z" level=info msg="[stdout]: \x1b[36mINFO\x1b[0m[2023-09-11T22:19:41Z] reading configuration form '/tmp/elemental'  "
time="2023-09-11T22:19:41Z" level=info msg="[stdout]: \x1b[36mINFO\x1b[0m[2023-09-11T22:19:41Z] Install called                               "
time="2023-09-11T22:19:41Z" level=info msg="[stdout]: \x1b[36mINFO\x1b[0m[2023-09-11T22:19:41Z] Partitioning device...                       "
time="2023-09-11T22:19:41Z" level=info msg="[stderr]: Error: 1 error occurred:"
time="2023-09-11T22:19:41Z" level=info msg="[stdout]: \x1b[31mERRO\x1b[0m[2023-09-11T22:19:41Z] Failed creating new partition table:         "
time="2023-09-11T22:19:41Z" level=info msg="[stderr]: \t* Invalid partition table type, only msdos and gpt are supported"
```

and the `/tmp/elemental/config.yaml` is
```
install:
  target: /dev/sda
  part-table: mbr
  cloud-init: /tmp/cos.3978584157
  tty: tty1
  system:
    size: 3072
```

Looks like the problem is located in the installer at https://github.com/harvester/harvester-installer/blob/ed0b7813baeec9b56f59c2c1b3ddce3c5328faec/pkg/config/cos.go#L100

**Comment by masteryyh** [comment]
Hi @jaevans thanks for reporting and your quick fix, much appreciated.
I'm going to change the title of this issue first for better issue management.

**Comment by masteryyh** [comment]
Test Plan:
Find a machine or VM, boot up with legacy mode, try to install with MBR partition table without any issues.

**Comment by albinsun** [comment]
Verified on `v1.2.2-rc1`, cluster setup and in-service successfully with `force_mbr: true`, close as done.


## Environment
* Harvester
  * Version: `v1.2.2-rc1`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> ISO Setup <code>harvester-v1.2.2-rc1</code> with <code>Use MBR partitioning scheme</code> / <code>force_mbr: true</code>
   </summary>

   `Use MBR partitioning scheme`
   ![image](https://github.com/harvester/harvester/assets/2773781/d5831683-8f07-400b-8412-29b8c1ce0eaa)
   Namely `force_mbr: true` in config script
   ![image](https://github.com/harvester/harvester/assets/2773781/81ef77e8-4276-478e-9f36-dc64448a090e)
   </details>

2. <details open>
   <summary> Setup successfully and cluster is in-service :heavy_check_mark: 
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/7269db3a-59a3-4581-9156-0bc7baaf63cc)
   ![image](https://github.com/harvester/harvester/assets/2773781/365c7fc0-7f32-4c14-8b32-c1917729e5a7)
   </details>




## Note
1. Can reproduce in `harvester-v1.2.0`
   ![image](https://github.com/harvester/harvester/assets/2773781/7d3e2fcd-f63f-4a41-bafb-402cd2472f88)
