### ISSUE TITLE
[BUG] helm missing from Harvester install

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#4518]
**Describe the bug**

In troubleshooting #4509 @starbops asked me to run some helm commands. However helm is missing from Harvester (at least 1.1.2) so it first needs to be installed although the install noted git is required for plugin installation.

**To Reproduce**
1. SSH to a Harvester node as the rancher user
2. Run `helm --help` - this will fail
3. Become root - `sudo su -`
4. Run `helm --help` - this will also fail
5. Run `whereis helm` - this will not find helm

**Expected behavior**

Since helm is a useful command it should be available by default

**Support bundle**

See #4509 

**Environment**
 - Harvester ISO version: 1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal on 2x Intel NUC7i7DNxE

**Additional context**
I worked around the lack of helm by installing the latest from https://helm.sh/docs/intro/install/

```
dobby:~ # curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
dobby:~ # chmod 700 get_helm.sh
dobby:~ # ./get_helm.sh 
[WARNING] Could not find git. It is required for plugin installation.
Downloading https://get.helm.sh/helm-v3.12.3-linux-amd64.tar.gz
Verifying checksum... Done.
Preparing to install helm into /usr/local/bin
helm installed into /usr/local/bin/helm
```

**Comment by Vicente-Cheng** [comment]
This change is introduced on OBS side, and `helm` is installed with v1.4.0-rc1

**Comment by albinsun** [comment]
Test PASS, close as fixed.


## Environment
* _harvester-v1.4.0-rc2_
  * Profile: 2 nodes QEMU/KVM (amd64)
  * ui-source: `Auto`


## Prerequisite
1. SSH to a Harvester node as the rancher user
   ![image](https://github.com/user-attachments/assets/687bf601-7d91-4e06-a168-68a8ae41935f)
1. :heavy_check_mark: `helm --help`
   ![image](https://github.com/user-attachments/assets/40e630b3-07a0-418d-b9cf-67a3a2a58884)
1. `sudo su -`
1. :heavy_check_mark: `helm --help`
   ![image](https://github.com/user-attachments/assets/558ba744-cac0-4526-b06b-048f9aa2d252)
1. :heavy_check_mark: `whereis helm`
   ![image](https://github.com/user-attachments/assets/8153ab68-f5d0-4b71-aed8-e1ab8c6a296a)
