### ISSUE TITLE
[FEATURE] Support ingress configuration

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#452]
**Is your feature request related to a problem? Please describe.**

currently, users need to configure ingress to access harvester server by manual.

**Describe the solution you'd like**

- [ ] users can configure ingress from harvester ui.
- [ ] if ingress configured, harvester-installer's management URL show ingress domain instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/632
