### ISSUE TITLE
[BUG] Unable to use image that has a name more than ~40 characters long created through terraform

### ISSUE THREAD

**Issue by jaevans** [harvester/harvester#4520]
**Describe the bug**

Any image that has a name more than 32 characters long ends up with a backingImage with a different name than Harvester expects

**To Reproduce**
1. Use terraform to create a new Image
```
resource "harvester_image" "ubuntu_22_04" {
  display_name = "Ubuntu Cloud 22.04"
  name         = "jammy-server-cloudimg-amd64"
  namespace    = "harvester-public"
  description  = "Ubuntu 22.04 LTE Offical Cloud Image"
  source_type  = "download"
  url          = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img"
}
```
2. Create a VM from the image

**Expected behavior**
VM is created and starts correctly

**Support bundle**

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HP DL380

**Additional context**
The PVC reports an error:
```
3m9s        Warning   ProvisioningFailed       persistentvolumeclaim/test-disk-0-c0b7u                failed to provision volume with StorageClass "longhorn-jammy-server-cloudimg-amd64": rpc error: code = InvalidArgument desc = volume pvc-0c37e4c6-053c-4da2-93d7-fed52238a01b missing backing image harvester-public-jammy-server-cloudimg-amd64 unable to create volume
```
The `backingimage` name is truncated to 32 characters, and a random suffix is added. This seems to be a change in longhorn between harvester 1.1.2 and 1.2.0.
```
$ k get backingimage -n longhorn-system | grep jammy
harvester-public-jammy-server-c-32ce4c2c   f3dbe861   download     670302208    41h
```

This also causes restores of images created under 1.1.2 to fail. 

The same image created via the GUI results in a `backingimage` with a short, random name
```
longhorn-system   harvester-public-image-jgh7d               03d4c6d4   download     670302208    8m48s
```

**Comment by WebberHuang1118** [comment]
Longhorn has a 40 characters name length limitation for backing images. If it exceeds the limitation, [webhook will automatically change the backing image name](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/webhook/resources/backingimage/mutator.go#L50).

Considering Harvester's naming convention for `virtualimage`, `backingimage` and `storageclass`:
- `backingimage name`  = `<virutalimage namsespace>`-`<virutalimage name>`
- `storageclass name`  = `longhorn`-`<virutalimage name>`

If the virtualimage is created from Harvester GUI:
- Harvester names the virtualimage internally, it would not exceed the backingimage name limitation.

If the virtualimage is created from Terraform:
- Virtualimage name is define in the .tf file directly (for exmpale: [image.tf](https://github.com/SUSE-Technical-Marketing/harvester-terraform/blob/master/images.tf#L3)). The backingimage name has the chance to be truncated and decoupled with storageclass, and this could bring pvc provision issue.

To workaround:
- Please confirm the backing image name pattern `<virutalimage namsespace>`-`<virutalimage Name>` is shorter than 40 characters long.

Thanks.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.3-f132d7fa-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to Dashboard, create a image by URL and update (via _edit as yaml_) `metadata.name` to long than 40 chars like `image-56789-0123456789-0123456789`
3. Image should created successfully
4. Create a VM from the image
5. Image should create and started successfully
    - There should have a `storageclass` named ending with the image name
    - There should have a `backingimage` named as `default-<truncated_image_name>-xxxxxxxx`
    - The parameter value `backingImage` in `storageclass` should be the `backingimage` name
6. VM should able to be deleted successfully
7. Image should able to be deleted successfully
