### ISSUE TITLE
[ENHANCEMENT] Allow wiping of partitions during ISO and PXE install

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4527]
**Is your enhancement related to a problem? Please describe.**

There is an issue where if you run the installer over an existing Harvester install it won't wipe the files and will cause the system to fall into an error state. This is most often seen in VMs that are being used for testing, but also is an issue in PXE installs of previous environments. Here are a few of the bugs that I think are caused by this.

#2066 
#2781 

Currently I've been getting around this based on a recommendation from a dev with the following steps

1. Wait for installer to open
1. Open another tty with ctrl+alt+f2 or other function key
1. login with rancher/rancher
1. `sudo -i`
1.  `sgdisk -z /dev/sda`
  - You need to do this for every disk you want to wipe. For a VM I imagine it’s just the one, but you’ll have to change the device name for it. For disks it’s usually sda, but sometimes it’s vda depending on the driver being used.
  - This wipes the gpt tables from the disk so it will only work on gpt formatted disks, but that is the default in the installation unless you specify MBR.

**Describe the solution you'd like**

- I would like to change the default behavior for the installer to wipe the partitions if you finish the install. This would only be on the OS install disk, and the VM store disk if one is specified.
- For an upgrade via ISO the behavior shouldn't change
- I would like a flag to be available in the Harvester config for PXE installs. This would need to be available both for a `create node` and a `join node`
**Describe alternatives you've considered**

I considered keeping the original behavior and having this be an additional option, but currently the default behavior will not work properly if you run it on an existing install, and if it is a blank disk that doesn't have an install then it would functionally do the same thing.
**Additional context**

**Comment by irishgordo** [comment]
Somewhat relating to: 
- https://github.com/harvester/harvester/issues/4887

as well

**Comment by m-ildefons** [comment]
@khushboo-rancher @innobead 
This is a pre-requisite for automatically testing Harvester in our lab, since we re-install Harvester on machines that previously had Harvester installed.
Without this feature an installation may get stuck or fail, needing manual intervention to recover from.

A possible solution is to add a new configuration option for the installer, telling it to wipe the disks on the node. This can be either a boolean option:
```
install:
  nuke_disks: true
```
or it can be a list of disks to wipe:
```
install:
  nuke_disks:
    - /dev/sda
    - /dev/sdb
```
the latter puts more responsibility on the user to figure out what the right disks to wipe are, but is easier to implement and has the advantage that the user can distinguish between disks where the data should be kept and disks that need to be erased.
The default setting should of course be that no disks are wiped.

**Comment by innobead** [comment]
Sounds good to me. 

@tserong can you help check this? feasibility or any other concerns?

cc @bk201 @Vicente-Cheng

**Comment by Vicente-Cheng** [comment]
> Sounds good to me.
> 
> @tserong can you help check this? feasibility or any other concerns?
> 
> cc @bk201 @Vicente-Cheng

Could we split this operation into two different implementations?

For interactive mode, we need to let the user confirm the format operation, and then we execute.
For non-interactive mode, could we have another installation parameter with the `nuke_disk`? e.g. `install.testing`

Make this more complex to prevent the users from not knowing what they are doing.

WDYT?

Just curious, do we have any chance to do this operation before running the installation?

**Comment by irishgordo** [comment]
We may also want to support disks being declared as disks via their HP, Dell, Supermicro, etc. flavored way the volumes get defined via RAID controllers like:
> /dev/disk/by-id/scsi-0HP_LOGICAL_VOLUME_01000000

I'm not entirely sure how that's decoded but perhaps it's translated from something like:
```bash
harvester-9pjm9:/home/rancher # lsscsi --scsi_id
[0:0:0:0]    storage HP       P440ar           6.60  -          -
[0:1:0:0]    disk    HP       LOGICAL VOLUME   6.60  /dev/sda   3600508b1001cc8fc6ff89245b6b988a3
[0:1:0:1]    disk    HP       LOGICAL VOLUME   6.60  /dev/sdb   3600508b1001c54cbd70aa089df2eda5a
[1:0:0:0]    storage IET      Controller       0001  -          -
[1:0:0:1]    disk    IET      VIRTUAL-DISK     0001  /dev/sdc   360000000000000000e00000000010001
[2:0:0:0]    storage IET      Controller       0001  -          -
[2:0:0:1]    disk    IET      VIRTUAL-DISK     0001  /dev/sdd   33000000200000001
[3:0:0:0]    storage IET      Controller       0001  -          -
[3:0:0:1]    disk    IET      VIRTUAL-DISK     0001  /dev/sde   SIET_VIRTUAL-DISK_beaf31
[4:0:0:0]    storage IET      Controller       0001  -          -
[4:0:0:1]    disk    IET      VIRTUAL-DISK     0001  /dev/sdf   33000000400000001
[5:0:0:0]    storage IET      Controller       0001  -          -
[5:0:0:1]    disk    IET      VIRTUAL-DISK     0001  /dev/sdg   33000000500000001
harvester-9pjm9:/home/rancher # lsscsi -Hlv
[0]    hpsa          
  cmd_per_lun=1013 host_busy=0    sg_tablesize=543  unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host0
  device dir: /sys/devices/pci0000:00/0000:00:01.0/0000:03:00.0/host0
[1]    iscsi_tcp     
  cmd_per_lun=32   host_busy=0    sg_tablesize=4096 unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host1
  device dir: /sys/devices/platform/host1
[2]    iscsi_tcp     
  cmd_per_lun=32   host_busy=0    sg_tablesize=4096 unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host2
  device dir: /sys/devices/platform/host2
[3]    iscsi_tcp     
  cmd_per_lun=32   host_busy=0    sg_tablesize=4096 unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host3
  device dir: /sys/devices/platform/host3
[4]    iscsi_tcp     
  cmd_per_lun=32   host_busy=0    sg_tablesize=4096 unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host4
  device dir: /sys/devices/platform/host4
[5]    iscsi_tcp     
  cmd_per_lun=32   host_busy=0    sg_tablesize=4096 unchecked_isa_dma=?? 
  dir: /sys/class/scsi_host//host5
  device dir: /sys/devices/platform/host5
```
I'm not really familiar with the [lsscsi utility](https://sg.danny.cz/scsi/lsscsi.html)

**Comment by tserong** [comment]
@irishgordo I don't thing we need to worry too much about vendor specific raid stuff, because those things all ultimately map back to `/dev/something`. @ibrokethecloud's PR above uses `lsblk` which just pulls out those top-level devices and wipes all of them.

Thinking about this further though, some care must be taken before wiping everything that looks like a disk that's attached to a given host. Imagine you had a system that could see a bunch of random disks on a SAN. Wiping all of these might not be a good idea.

**Comment by bk201** [comment]
@ibrokethecloud We need a test plan and doc for this feature.

**Comment by lanfon72** [comment]
test plan or doc required for QA to verify this.

**Comment by albinsun** [comment]
A quick test using `v1.3.0-rc4`, but not observe reinstallation or disk wiping with `harvester.install.wipe_disks=true` PXE config.

@ibrokethecloud,
Are the test steps feasible?
Please help to for the test plan, thanks.


## Environment
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: QEMU/KVM, single nodes (8C/20G/500G)
  * ui-source: `Auto`


## Test Step
1. Prepare a previously installed harvester qcow2 
   * <details>
     <summary> <i>vagrant-pxe-harvester_harvester-node-0-vda.qcow2</i>
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/0d46179d-f38d-404f-ba0b-6850925f9e5b)
     </details>

1. Temporarily change ipxe-example to using existing volume.
   <details>
   <summary> Temporarily change ipxe-example to using existing volume.
   </summary>
 
   _vagrant-pxe-harvester/Vagrantfile_
   ![image](https://github.com/harvester/harvester/assets/2773781/591df308-7750-46dd-8cf8-9650d0062f59)
   </details>

1. Setup new cluster
   * <details>
     <summary> Cluster should has previous data (NOT clean)  :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/31318d08-bb63-4245-895b-38e5ac75672e)
     </details>

1. Setup new cluster w pxe config `harvester.install.wipe_disks=true`
   * <details>
     <summary> Adding <code>harvester.install.wipe_disks=true</code> to pxe config
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/ca0811fe-3d64-46aa-839f-e0df7f750097)
     </details>

   * <details open>
     <summary> Cluster is clean with reinstallation :x: ${\color{red} \text{Data still there}}$
     </summary>

     PXE do have config
     ![image](https://github.com/harvester/harvester/assets/2773781/17c6c03c-906c-46c8-9134-dbf84f8283e3)

     Can still see previous VM
     ![image](https://github.com/harvester/harvester/assets/2773781/275cb266-1405-4a52-b2b6-5cbe0e789fc1)
     </details>

**Comment by ibrokethecloud** [comment]
The easiest way to test is as follows:

* Create a KVM instance with 2 disks, in my case I created one with two 250G disks
![image](https://github.com/harvester/harvester/assets/19664014/312d6d72-418d-412d-8a6c-fbdf168842a7)
* Boot with rc4 ISO and trigger harvester install on first disk, say vda. Installation does not need to complete, just allow installer to run first few steps to partition and label partitions.
* Restart VM and trigger install on second disk, vdb. 
* While install is running switch console and verify partitions using `fdisk -l` and `blkid` 
* Partitions should be present on both disks
* Reboot VM, and edit kernel arguments in grub to add `harvester.install.wipe_disks=true`
* Walk through installer screens and let installation start.
* Once installation is running, switch console and run `grep -i wiping /var/log/console.log`
![image](https://github.com/harvester/harvester/assets/19664014/f7afeb4b-241f-4a9b-819e-3211fd117cbd)
* `fdisk -l` and `blkid` should only show partitions on the disk used for the current installation

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc4` for ISO installation.


## Environment
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Steps
1. <details>
   <summary> Create KVM instance with 2 disks (VirtIO, 250G each)
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/6113b32b-1eb5-420f-a63e-bc6386eb568a)
   </details>
   
1. Setup `v1.3.0-rc4` on first disk (vda)
1. Restart VM and setup `v1.3.0-rc4` on second disk (vdb)
2. <details>
   <summary> Check disk, both 2 disk has partitions.
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/6b9d4f78-d57b-4300-a549-e0684f6f2937)
   </details>

1. Reboot VM and setup again with grub option `harvester.install.wipe_disks=true`
   ![image](https://github.com/harvester/harvester/assets/2773781/4d55cc20-68b4-45a9-9255-35e113ae6841)

   * <details>
     <summary> <code>grep -i wiping /var/log/console.log</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2a9cb7f0-c143-449a-877f-befdffd43ea9)
     </details>
     
   * <details>
     <summary> <code>fdisk -l</code> and <code>blkid</code> should only show partitions on the disk used for the current installation :heavy_check_mark: 
     </summary>
    
     ![image](https://github.com/harvester/harvester/assets/2773781/d0c3a7f2-263c-4155-af02-b5c57b6f6570)
     ![image](https://github.com/harvester/harvester/assets/2773781/af2276aa-2ebd-4843-a118-30fa360e3154)
     </details>

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc4`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`


## Test Case
### ISO
1. <details>
   <summary> Create KVM instance with 2 disks (VirtIO, 250G each)
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/6113b32b-1eb5-420f-a63e-bc6386eb568a)
   </details>
   
1. Setup `v1.3.0-rc4` on first disk (vda)
1. Restart VM and setup `v1.3.0-rc4` on second disk (vdb)
2. <details>
   <summary> Check disk, both 2 disk has partitions.
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/6b9d4f78-d57b-4300-a549-e0684f6f2937)
   </details>

1. Reboot VM and setup again with grub option `harvester.install.wipe_disks=true`
   * <details>
     <summary> Update grub option
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/4d55cc20-68b4-45a9-9255-35e113ae6841)
     </details>

   * <details>
     <summary> <code>grep -i wiping /oem/install/console.log</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2a9cb7f0-c143-449a-877f-befdffd43ea9)
     </details>
     
   * <details>
     <summary> <code>fdisk -l</code> and <code>blkid</code> should only show partitions on the disk used for the current installation :heavy_check_mark: 
     </summary>
    
     ![image](https://github.com/harvester/harvester/assets/2773781/d0c3a7f2-263c-4155-af02-b5c57b6f6570)
     ![image](https://github.com/harvester/harvester/assets/2773781/af2276aa-2ebd-4843-a118-30fa360e3154)
     </details>


### PXE
1. <details>
   <summary> Use ipxe-example to create a single disk (vda) cluster
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/c2fb5b4d-825e-4e25-99e5-b0ab4837a2e3)
   </details>

1. Adding one more disk (vdb)
   * <details>
     <summary> Shutdown and add disk vdb 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/59a716ea-d870-4a04-b969-ef25c05167b6)
     </details>

   * <details>
     <summary> Change vdb to 1st order
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/be5190c6-23c2-46f5-8278-722f9cead81e)
     </details>

1. Update iPXE config
   * <details>
     <summary> change target disk in config-create to vdb
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/3df24c55-6952-499d-bc96-59480999ff1d)
     </details>

   * <details>
     <summary> Add grub option <code>harvester.install.wipe_disks=true</code>
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/c363fb5c-d651-488f-8e1c-a567b01a4125)
     </details>

1. Boot VM for iPXE setup
   * <details>
     <summary>
       :green_circle:
       Setup successfully 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/462c52ac-51ea-4a65-98dd-2d1ff1870f93)
     </details>

   * <details>
     <summary>
       :green_circle: 
       <code>grep -i wiping /oem/install/console.log</code> 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f59c15bc-42f3-48d5-8c43-00f4cf3163fd)
     </details>
     
   * <details>
     <summary>
       :green_circle: 
       <code>fdisk -l</code> and <code>blkid</code> should only show partitions on the disk used for the current installation 
     </summary>
    
     ![image](https://github.com/harvester/harvester/assets/2773781/93fc2671-202a-4b50-a0df-7d27e3696daa)
     </details>

**Comment by lanfon72** [comment]
doc is required. (no PR referred yet)
