### ISSUE TITLE
[BUG] invalid length 48 bytes (too large)

### ISSUE THREAD

**Issue by Rocky-Li-Adam** [harvester/harvester#4528]
Error reported during the first installation

device：DL580 Gen9
harvester version: harvester-v1.2.0-rc6-amd64

![Dingtalk_20230914110551](https://github.com/harvester/harvester/assets/19769704/710c9b8e-8499-4241-871e-391c16f2ea88)

**Comment by Rocky-Li-Adam** [comment]
Error: 1 error occurred:
  * cannot read device path: cannot decode node 0: invalid length 48 bytes (too large)

**Comment by guangbochen** [comment]
Can u please help to get the installation failed log as the steps described below, thanks.
<img width="717" alt="image" src="https://github.com/harvester/harvester/assets/4569037/2d949200-c058-450d-b4dd-42dedd0cd835">

**Comment by Rocky-Li-Adam** [comment]
@guangbochen 
[console.log](https://github.com/harvester/harvester/files/12604591/console.log)

**Comment by rjeschmi** [comment]
I did see this on an install. I deleted a few disabled entries manually using efibootmgr and it worked after that.

**Comment by ssusbauer** [comment]
I am having similar issues with 1.2.1, haven't tried with 1.2.0 yet. 1.1.2 shows the message but continues.

In my case the error message is:
> cannot read device path: cannot decode node: 1: invalid length 14 bytes (too large)

On the 1.1.2 installer it gives the same message as a warning but adds a preface that it is complaining specifically about boot entries 4, 5, and 7. These coincide to PXE-enabled NICs and a USB optical drive (IPMI virtual drive). I can't really disable them in my environment, and one of them is holding the installer iso itself (tried PXE and CD mount with the same behavior). The device entries it doesn't like are below (with mac addresses edited out).

```
Boot0004* UEFI: IP4 Intel(R) I210 Gigabit  Network Connection   PciRoot(0x0)/Pci(0x80,0x86)/Pci(0x80,0x86)/MAC(xxxxxxxxxxxx,0)/IPv4(0.0.0.00.0.0.0,0,0)
Boot0005* UEFI: IP4 Intel(R) I210 Gigabit  Network Connection   PciRoot(0x0)/Pci(0x80,0x86)/Pci(0x80,0x86)/MAC(xxxxxxxxxxxx,0)/IPv4(0.0.0.00.0.0.0,0,0)
Boot0007* UEFI: AMI Virtual CDROM0 1.00 PciRoot(0x0)/Pci(0x80,0x86)/USB(2,0)/USB(0,0)/CDROM(1,0x2681e8,0x2000)
```

**Comment by rjeschmi** [comment]
Are those the only three enabled? I didn't dig in much deeper, but trimming down the enabled list might help even if it is temporary.

**Comment by ssusbauer** [comment]
The only other entry was the EFI Shell. I attempted again with 1.2.1 after disabling the UEFI network stack so the only entries were the shell and CD drive and it still failed.

I gave it one more go where I deleted the CD drive entry in efibootmgr after booting but before starting the installer, leaving only the UEFI Shell in the list, and it was able to complete successfully that time, so there's an icky workaround at least.

**Comment by ssusbauer** [comment]
FWIW, I think the hard stop is coming from upstream elemental-toolkit and their bootloader install process responding to errors generated by go-efilib.

**Comment by frelon** [comment]
This should be fixed in https://github.com/rancher/elemental-toolkit/pull/2089, let us know if this should be backported to a minor release that can be consumed by harvester!

**Comment by Vicente-Cheng** [comment]
hi @frelon, 
Thanks for taking care of this!

Could you help backport this issue to elemental-toolkit v1.1.x? (currently is v1.1.5, maybe we should have v1.1.6.)
That would help us to involve this fix in the next release. Thanks!!

**Comment by frelon** [comment]
Hi @Vicente-Cheng!

Sure, I cut a new release on GitHub and in the `isv:Rancher:Elemental:Maintenance:5.5` project on OBS! Let me know if you use another channel for the artifacts and I will take a look! 👍

**Comment by Vicente-Cheng** [comment]
> Hi @Vicente-Cheng!
> 
> Sure, I cut a new release on GitHub and in the `isv:Rancher:Elemental:Maintenance:5.5` project on OBS! Let me know if you use another channel for the artifacts and I will take a look! 👍

Hi @frelon,

Thanks for the new v1.1.6 release!
We have OBS repo linked into the`isv:Rancher:Elemental:Maintenance:5.5` everything looks fine and I also checked the elemental as below:
```
1a7d13557be2:/ # elemental version
1.1.6+ge9f70ce
```

Seems it is a target version for this issue. So, thanks again for your effort!

**Comment by lanfon72** [comment]
Tested on `v1.4.0-dev-20240918`, the elemental toolkit still keep in `v1.1.5`, move back to review.

![image](https://github.com/user-attachments/assets/b9f80576-853d-4658-8760-6cf47d3843b5)

**Comment by w13915984028** [comment]
Just noticed this may also affect the potential upgrade from v1.3.2->v1.4.0->v1.4.0

https://github.com/harvester/harvester/issues/6646

**Comment by lanfon72** [comment]
Closed as elemental version has been bumped in `v1.4.0-rc3`

![image](https://github.com/user-attachments/assets/8514a923-399f-4569-8741-6d98708cf6d3)
