### ISSUE TITLE
[FEATURE] bump dependency components to the latest version

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#453]
**Is your feature request related to a problem? Please describe.**

bump dependency components like kubevirt, CDI, longhorn, minio to the latest version before the v0.2.0 release

**Describe the solution you'd like**

- [x] kubevirt v0.40.0
- [x] CDI v1.31.0
- [x] longhorn v1.1.1

**Describe alternatives you've considered**

N/A

**Additional context**

**Comment by TangStone** [comment]
Validation Version:master-4d96da79-head
To verify the method, use the command `sudo k3s ctr image ls | grep kubevirt`
![image](https://user-images.githubusercontent.com/15829074/110572446-5d932780-8194-11eb-8162-e37619196ef5.png)
Verification passed

**Comment by TangStone** [comment]
Validation Version:master-64e4d950-head
To verify the method, use the command `k3s crictl images | grep 'kubevirt\|longhorn'`
![image](https://user-images.githubusercontent.com/15829074/115981627-acbbdd00-a5c7-11eb-9ab5-35d4fce41c4d.png)
