### ISSUE TITLE
[BUG] invalid MCM doc link on the Harvester support page

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#4539]
**Describe the bug**
 MCM doc link on the Harvester support page is invalid.

**To Reproduce**
1. Click the support page in the bottom left corner.
2. Click the doc link and the URL address is invalid.
<img width="827" alt="image" src="https://github.com/harvester/harvester/assets/4569037/9de828fe-3459-47f8-b89c-912594cb393d">

**Expected behavior**
Fix the doc link for both v1.1 and v1.2 versions.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by albinsun** [comment]
Provide test result for `v1.2-a9968541-head`, close as fixed.

## Environment
* Harvester
  * Version: `v1.2-a9968541-head`
  * Profile: QEMU/KVM, single node (8C/16G/250G)
  * ui-source: `Auto`

## Test Cases
> **Note** Click "►" to expand details.
1. <details>
   <summary>
   "Account" -> "Preferences" -> "Advanced Features" -> "Enable Extension developer features"
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/d4aed155-0f54-470e-8f38-68fca76ce550)
   </details> 


1. <details open>
   <summary>
   "Support" -> "Access Embedded Rancher UI" -> "here" link 
   ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/7221d307-4e50-4c3a-9f8b-79f06ccc5c80)
   </details> 
 
## Note
1. Can reproduce in `v1.2.0`
   ![image](https://github.com/harvester/harvester/assets/2773781/f91b1420-092e-46d4-b696-69cb4a688f20)
