### ISSUE TITLE
[BUG] Unable to restore backup into new VM when the name starts with upper case

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4544]
### Describe the bug
https://github.com/harvester/harvester/assets/5169694/04ee7389-0049-4efb-8a29-9c0ae6ee6678

### To Reproduce
1. Install Harvester with any nodes
2. Setup backup-target
3. Create an image for VM creation
4. Create VM `vm1` and take backup `vm1b`
5. Restore `vm1b` into new VM `VM1r`

### Expected behavior
VM should be restored correctly, or error message should prompted.

## Environment:
 - Harvester ISO version: **v1.2-a9968541-head**
 - **ui-source** Option: **Auto**
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **Baremetal DL360 4 nodes**

### Additional context
N/A

### Support bundle
N/A

**Comment by albinsun** [comment]
Provide test result on `master-645d9e2d-head`, close as fixed
Backport  `v1.1`  (harvester#4552) is not merge yet, let's verify it separatly later


## Environment
* Harvester
  * Version: `master-645d9e2d-head`
  * Profile: QEMU/KVM, single node (8C/48G/250G)
  * ui-source: `Auto`


## Test Cases
> **Note** Click "►" to expand details.

lower alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character

### Positive TCs
1. Single lower ${~~~\color{green}\textsf{V}}$
1. Lowers ${~~~\color{green}\textsf{V}}$
1. Lowers contains '.'  ${~~~\color{green}\textsf{V}}$
1. Lowers contains '-' ${~~~\color{green}\textsf{V}}$
1. Lowers contains '.' and '-' ${~~~\color{green}\textsf{V}}$

![image](https://github.com/harvester/harvester/assets/2773781/17fea11e-a266-484d-a9d4-3e3af1624d45)


### Negtive TCs
1. <details>
   <summary>
   Upper
   ${~~~\color{green}\textsf{V}}$
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/b2411e02-e0c1-4fef-b996-997c8c827862)
   </details> 

1. <details>
   <summary>
   Upper infront of valid
   ${~~~\color{green}\textsf{V}}$
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/15f47599-19d8-470e-8c1a-bea7e9c3a28b)
   </details> 

1. <details>
   <summary>
   Upper append to valid   
   ${~~~\color{green}\textsf{V}}$
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/cbb30195-1abe-47fd-be9c-0938145e1d85)
   </details> 

1. <details>
   <summary>
   Upper in the middle of valid
   ${~~~\color{green}\textsf{V}}$
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/26737717-6f71-4707-8042-a7a05de0858e)
   </details> 
 
## Note
1. Can reproduce in `v1.2-dc171ff5-head`
    * vm1b ${~~~\color{green}\textsf{V}}$
    * VM1r ${~~~\color{red}\textsf{X}}$
