### ISSUE TITLE
[BUG] After promote node to master, storage class local-path was changed to default.

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#455]
**Describe the bug**

**To Reproduce**
1. setup 3 node cluster by iso
2. kubectl get sc
```bash
$ kubectl get sc
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  13m
longhorn (default)     driver.longhorn.io      Delete          Immediate              true                   51m

```
**Expected behavior**

only on storage class is default (longhorn)

**Environment:**
 - Harvester ISO version:  master (279c018)
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/270

**Comment by DoNotSayYes** [comment]
Validated on master-head.(3dd7670)
![image](https://user-images.githubusercontent.com/57614736/106710470-f3d1ac00-6630-11eb-869a-715a102fa2fe.png)

**Comment by futuretea** [comment]
Reopen by mistake
