### ISSUE TITLE
[BUG] Adding new backup target

### ISSUE THREAD

**Issue by Spaulus2017** [harvester/harvester#4558]
**Describe the bug**

first, we had issues with backing up servers (they backed up fine before until now), we used nfs as our backup target. We then removed this target and attempted to replace it with S3. The error we receive is "admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target. There is a VM either in the process of creating or deleting". We have looked at each VM, volume, and vlan to ensure that they are all healthy and are not reporting any error or terminating status. 
We cleaned up any VMs that were stuck in the terminating state. 

**To Reproduce**
1. Go to Backup & Snapshots tab
2. An error will pop up saying "You must configure the backup target in [setting ](https://10.116.8.20/dashboard/harvester/c/local/harvesterhci.io.setting/backup-target?mode=edit)before creating a new backup." 
3. Click "setting" in the error 
4. Select type: S3, enter endpoint, bucket name, region, access key, secret key 
5. Click save 
6. Error: admission webhook "validator.harvesterhci.io" denied the request: Can't update the backup target 

**Expected behavior**
The S3 backup target will be saved and backups will work

**Support bundle**

I attempted to upload the file but its too large. 

**Environment**
 - Harvester ISO version: V1.1.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell R6525
 - 

**Additional context**

**Comment by WebberHuang1118** [comment]
Hi @Spaulus2017,

According to https://github.com/harvester/harvester/blob/729ecc750b914896512dc8c1dfee86a51b178667/pkg/webhook/resources/setting/validator.go#L321-L323, it seems there is pending VMRestore in your cluster.

Please check with `$ kubectl get virtualmachinerestores.harvesterhci.io -A`, and try to delete the pending VMRestores if there are any. Thanks.

**Comment by Spaulus2017** [comment]
Hi @WebberHuang1118 

This is what I get after running the command:
harvester-8sc8d:~ # kubectl get virtualmachinerestores.harvesterhci.io -A
NAMESPACE   NAME                                    TARGET_KIND      TARGET_NAME       COMPLETE   AGE   ERROR
koko        restore-galaxy-backup-72123-n42cn       VirtualMachine   galaxy-centos     true       62d
koko        restore-galaxy-backup-72123-qzpfh       VirtualMachine   Galaxy2.0         false      62d
koko        restore-koko-slurm1-20230705-7f94p      VirtualMachine   koko-slurm1b      true       78d
koko        restore-koko-slurm1b-20230705-8j7lc     VirtualMachine   koko-slurm-test   true       78d
koko        restore-rocky-ondemand-20230830-j2224   VirtualMachine   ondemand3         true       22d

How do I delete the failed restore? 
Thanks!

**Comment by WebberHuang1118** [comment]
Hi @Spaulus2017,

From the information you provided, there is an uncompleted VMRestore `koko/restore-galaxy-backup-72123-qzpfh`. 
Please try `kubectl -n koko delete virtualmachinerestores.harvesterhci.io restore-galaxy-backup-72123-qzpfh` to delete it.

**Comment by Spaulus2017** [comment]
This resolved the issue, thank you!
