### ISSUE TITLE
[BUG] Logging to Minio mangles URL and crashes fluentd

### ISSUE THREAD

**Issue by andyrue** [harvester/harvester#4571]
**Describe the bug**
I'm trying to set up logging to an S3 compatible minio server. The URL seems to be getting mangled and causing `rancher-logging-root-fluentd-0` pod to crash repeatedly. I set a target endpoint of `http://10.111.104.14:9000` and bucket of `harvester-logs` and the resulting error in fluentd pod is:

```
fluentd 2023-09-27 00:05:50 +0000 [error]: fluent/log.rb:372:error: unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: Failed to open TCP connection to harvester-logs.10.111.104.14:9000 (getaddrinfo: Name does not resolve)>"
```

Note the `harvester-logs.10.111.104.14:9000` which is the incorrect URL.

**To Reproduce**
1. Create new Logging Output
2. Set Output to S3
3. Set endpoint to http://x.x.x.x:9000
4. Set bucket to anything

**Expected behavior**
Expect URL to not get mangled and for fluentd to not crashloop.

**Support bundle**
Bundle too big to upload.

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by w13915984028** [comment]
@andyrue Did you recover from this configuration? Seemed something was wrong.

**Comment by andyrue** [comment]
I am still experiencing it.

**Comment by andyrue** [comment]
I also noticed there isn't a place to specify the Region like there is when configuring Harvester Backups to S3, so maybe I'm using the wrong URL?

**Comment by w13915984028** [comment]
@andyrue 
Please get following, thanks.
```
kubectl get output -A -o yaml
kubectl get clusteroutput -A -o yaml
kubectl get flow -A -o yaml
kubectl get clusterflow -A -o yaml
```

**Comment by andyrue** [comment]
`kubectl get output -A -o yaml`
```
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Output
  metadata:
    creationTimestamp: "2023-09-26T15:37:13Z"
    generation: 5
    name: minio-logging
    namespace: default
    resourceVersion: "81627059"
    uid: ea3f6dff-3239-4857-8a01-138c3fe0fc6c
  spec:
    s3:
      aws_key_id:
        valueFrom:
          secretKeyRef:
            key: user
            name: harvester-minio-user
      aws_sec_key:
        valueFrom:
          secretKeyRef:
            key: password
            name: harvester-email-password
      overwrite: "false"
      path: ""
      s3_bucket: harvester-logs
      s3_endpoint: http://10.111.104.14:9000/
  status:
    active: true
kind: List
metadata:
  resourceVersion: ""
```

`kubectl get clusteroutput -A -o yaml`
```
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
  metadata:
    creationTimestamp: "2023-09-26T18:15:27Z"
    generation: 3
    name: minio-logging
    namespace: cattle-logging-system
    resourceVersion: "81627253"
    uid: aeb5500b-80af-4c4c-92a2-8f207daed451
  spec:
    s3:
      aws_key_id:
        valueFrom:
          secretKeyRef:
            key: user
            name: harvester-minio-user
      aws_sec_key:
        valueFrom:
          secretKeyRef:
            key: key
            name: harvester-minio-access-key
      overwrite: "false"
      path: ""
      s3_bucket: harvester-logs
      s3_endpoint: http://10.111.104.14:9000
  status:
    active: true
kind: List
metadata:
  resourceVersion: ""
```
`kubectl get flow -A -o yaml`
```
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: Flow
  metadata:
    creationTimestamp: "2023-09-26T15:42:38Z"
    generation: 1
    name: logging
    namespace: default
    resourceVersion: "81021647"
    uid: f239c666-533a-4e12-b16b-644c4f3fb77a
  spec:
    globalOutputRefs: []
    localOutputRefs:
    - minio-logging
  status:
    active: true
kind: List
metadata:
  resourceVersion: ""
```
`kubectl get clusterflow -A -o yaml`
```
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterFlow
  metadata:
    creationTimestamp: "2023-09-26T18:15:49Z"
    generation: 1
    name: logging
    namespace: cattle-logging-system
    resourceVersion: "81192741"
    uid: 11bd487d-0078-4878-b50c-5bfdb5e516d7
  spec:
    globalOutputRefs:
    - minio-logging
  status:
    active: true
kind: List
metadata:
  resourceVersion: ""
```
Thanks for looking!

**Comment by w13915984028** [comment]
@andyrue :

I tried, the error is similar

>2023-10-05 12:36:50 +0000 [error]: fluent/log.rb:372:error: unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: Failed to open TCP connection to harvester-logs.10.111.104.14:9000 (getaddrinfo: Name does not resolve)>"

Your post:
> fluentd 2023-09-27 00:05:50 +0000 [error]: fluent/log.rb:372:error: unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: Failed to open TCP connection to harvester-logs.10.111.104.14:9000 (getaddrinfo: Name does not resolve)>"


With a quick glance of the minio doc
https://min.io/docs/minio/linux/integrations/aws-cli-with-minio.html

It looks, the endpoint needs to be started with `dns` instead of IP directly, it will then resolve `bucket-name.endpoint` before connection.  Did you try to use a valid https path as the endpoint?

if you do not have such, you may try:
https://sslip.io/

I tried, and the log then became:

```
apiVersion: v1
items:
- apiVersion: logging.banzaicloud.io/v1beta1
  kind: ClusterOutput
...
      path: ""
      s3_bucket: harvester-logs
      s3_endpoint: http://10.111.104.14.sslip.io:9000
...
```

// as long as your setup is not air-gapped, the dns name `ip.sslip.io` will resolve the target ip.

> 2023-10-05 12:51:05 +0000 [error]: #0 unexpected error error_class=RuntimeError error="can't call S3 API. Please check your credentials or s3_region configuration. error = #<Seahorse::Client::NetworkingError: execution expired>"

It is simply because I did not set up an real minio server :)

**Comment by andyrue** [comment]
Ah, ok. Thank you! I will give that a try and reopen if I have further problems.
