### ISSUE TITLE
[BUG] UI does not show IP for Windows VMs outside the management network

### ISSUE THREAD

**Issue by pjbgf** [harvester/harvester#4579]
**Describe the bug**
The Harvester UI does not show IP addresses for Windows VMs that do not have a NIC from the management network.

**To Reproduce**
1. Create a Windows 2022 VM using the `windows-iso-image-base-template` template
2. On the Networks tab, add a NIC that is outside the management network.
3. Save

![image](https://github.com/harvester/harvester/assets/5452977/c0ce4ab5-128e-4531-8dfa-900057e6f751)

**Expected behavior**

Once the machine starts, it is expected that its IP address is displayed on the Virtual Machines page. However, although the VM starts and gathers an IP, it is not displayed on the UI.

Here are two VMs, one with a NIC from management and one with a NIC from the public network:

![image](https://github.com/harvester/harvester/assets/5452977/affe3962-db4c-4118-8259-d63c2ec49880)

The VM with the missing IP in the UI is still accessible through the network:
![image](https://github.com/harvester/harvester/assets/5452977/561c5158-1325-46fd-a60f-8405da55ba79)

**Support bundle**
Happy to provide the bundle upon request.

**Environment**
 - Harvester ISO version: `v1.1.2`
 - Underlying Infrastructure: `Custom Baremetal`

**Additional context**
I reproduced this with network model `e1000`, as [recommended on the documentation](https://docs.harvesterhci.io/v1.1/vm/create-windows-vm/), and also with `virtio`.

**Comment by Martin-Weiss** [comment]
Did you install the vmdp with the qemu-agent?

**Comment by pjbgf** [comment]
Hey @Martin-Weiss, thank you for the quick reply. Is there any info on how to do that? I did tried executing/installing them via the Web Console, but got messages confirmed whether it installed it properly - and the IP is still not showing up.

**Comment by Martin-Weiss** [comment]
@pjbgf  - maybe this helps? https://documentation.suse.com/sle-vmdp/2.5/html/vmdp/index.html#sec-vmdp-qemu-guest-agent

**Comment by pjbgf** [comment]
@Martin-Weiss thank you very much for that. For some reason trying to execute `qemu-ga.exe` at both CMD or Powershell seems to be a no op. No output for the commands, and the qemu-qa ends up not being installed:

![image](https://github.com/harvester/harvester/assets/5452977/0144757a-d857-4ea7-aa68-6ce07259650d)

**Comment by pjbgf** [comment]
I think I got it now. After going around through the vmdp for a bit, it seems that for VDMP version `2.5.3` you need to do this instead: `d:\x64\setup.exe /qemu-ga` 

![image](https://github.com/harvester/harvester/assets/5452977/7f260666-90b8-4985-811d-b3067c5ac329)
