### ISSUE TITLE
[BUG] The Harvester ISO boot extremly slow on Dell XR4000

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4586]
**Describe the bug**

The Harvester ISO boots slowly on the Dell XR4000. The process can't reach the installer.

**To Reproduce**
1. Boot V1.2.0 ISO on Dell XR4000.
2. The boot process is extremely slow and finally stuck here:
![image](https://github.com/harvester/harvester/assets/1691518/995c084e-5671-4d46-890f-f001a6dd6be2)

**Expected behavior**

The ISO should boot smoothly and display the installer.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
@bk201 this change looks great :smile: :+1: validated on Dell machine with v1.2.1-rc1 - I'll go ahead and close this out :smile: 

Artifacts:
![Screenshot from 2023-10-20 10-23-53](https://github.com/harvester/harvester/assets/5370752/9751137c-6aff-4554-9435-64435b1b1e3d)
![Screenshot from 2023-10-20 10-21-44](https://github.com/harvester/harvester/assets/5370752/3f8e05a5-2397-404e-8312-941890bd1f26)
![Screenshot from 2023-10-20 10-20-57](https://github.com/harvester/harvester/assets/5370752/e3a92ed4-c399-40b4-9465-7a793c50850d)
![Screenshot from 2023-10-20 10-20-12](https://github.com/harvester/harvester/assets/5370752/48249058-6e6d-41ae-9120-265dea6742a6)
![Screenshot from 2023-10-20 10-19-23](https://github.com/harvester/harvester/assets/5370752/a707f923-657e-42a0-8fbe-088af143656a)
![Screenshot from 2023-10-20 10-18-54](https://github.com/harvester/harvester/assets/5370752/f9d619fc-aca7-4083-b344-5a4dc89b0503)
![Screenshot from 2023-10-20 10-16-19](https://github.com/harvester/harvester/assets/5370752/e704b0c3-3857-42ed-b7af-167219e76239)
