### ISSUE TITLE
[BUG] Harvester v120 cann't start new VM from saved VM template

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4589]
**Describe the bug**

Seems the bug in here https://github.com/harvester/harvester/issues/4589#issuecomment-1750645974 is fixed (Harvester v1.1.2 LH v1.3.2), but another bug is imported in Harvester v1.2.0, LH v1.4.3

**To Reproduce**
1. Create VM
2. Generate VM templated, with `save Data` option
3. Start new VM with this template, the VM will stuck in starting
error is like:
![image](https://github.com/harvester/harvester/assets/31133476/577633de-a9a9-4d45-a221-ac25084512f5)

![image](https://github.com/harvester/harvester/assets/31133476/4ead8b91-4d2d-4656-be9f-04bbbf75eadc)

Node the naming difference:

```
harv41:~ # kk get backingimage -A
NAMESPACE         NAME                                       UUID       SOURCETYPE           SIZE         AGE
..
longhorn-system   default-templateversion-vm3-new-d4ee304a   0f8835be   export-from-volume   1073741824   3m2s


harv41:~ # kk get storageclass longhorn-templateversion-vm3-new-lkqjc-image-0  -n longhorn-system -oyaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  creationTimestamp: "2023-10-05T13:30:05Z"
  name: longhorn-templateversion-vm3-new-lkqjc-image-0
  resourceVersion: "3424464"
  uid: 99c8f7b9-32ab-408d-bee0-e5a4d4bebd54
parameters:
  backingImage: default-templateversion-vm3-new-lkqjc-image-0  ////////////
  migratable: "true"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Expected behavior**

VM should start.

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.2.0, LH v1.4.3, this issue is not existing in Harvester v1.1.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

In Harvester v1.1.2 (LH v1.3.2) https://github.com/harvester/harvester/issues/4589#issuecomment-1750645974, When template name is too long, the `template` itself will not be `Not Ready`.

But in Harvester v1.2.0, the template is `Ready`
![image](https://github.com/harvester/harvester/assets/31133476/3260efb5-429f-4808-8d32-5f79bdedc21f)

But, due to `storageclass` points to wrong `backingimage`
![image](https://github.com/harvester/harvester/assets/31133476/194a842e-9ec8-4278-b281-fd38873c68d4)

The feature, `start vm from template`, will always fail.

**Comment by bk201** [comment]
@WebberHuang1118 Please help check the issue, thanks!

**Comment by w13915984028** [comment]
The issue is due to this function:
https://github.com/harvester/harvester/blob/master/pkg/controller/master/image/vm_image_controller.go#L144

```
func (h *vmImageHandler) createBackingImageAndStorageClass(image *harvesterv1.VirtualMachineImage) (*harvesterv1.VirtualMachineImage, error) {
	if err := h.createBackingImage(image); err != nil && !errors.IsAlreadyExists(err) {
		return nil, err
	}
	if err := h.createStorageClass(image); err != nil && !errors.IsAlreadyExists(err) {
		return nil, err
	}
```

In Harvester v1.2.0 related Longhorn, the `backingimage` seems using `generated-name` instead of `fixed-name`. (need to confirm LH code change)

```
harv41:~ # kk get backingimage -A
NAMESPACE         NAME                                       UUID       SOURCETYPE           SIZE         AGE
longhorn-system   default-templateversion-vm3-new-d4ee304a   0f8835be   export-from-volume   1073741824   20h

harv41:~ # kk get virtualmachineimage -A
NAMESPACE   NAME                                    DISPLAY-NAME                            SIZE         AGE
default     templateversion-vm3-new-lkqjc-image-0   templateversion-vm3-new-lkqjc-image-0   1073741824   20h


harv41:~ # kk get storageclass -A
NAME                                             PROVISIONER          RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
longhorn-templateversion-vm3-new-lkqjc-image-0   driver.longhorn.io   Delete          Immediate           true                   20h

```

But Harvester code assumes it's fixed name:
```
func GetBackingImageName(image *harvesterv1.VirtualMachineImage) string {
	return fmt.Sprintf("%s-%s", image.Namespace, image.Name)
}
```

**Comment by WebberHuang1118** [comment]
This seems similar to https://github.com/harvester/harvester/issues/4520#issuecomment-1717029093 which was brought from LH's auto-correction on backing image name. There is a [PR](https://github.com/harvester/harvester/pull/4561) for fixing issue #4520, however, it requires further improvement for backward compatibility.

I will check if the root cause is exactly the same as #4520. Thanks.

**Comment by w13915984028** [comment]
Add a comment to https://github.com/harvester/harvester/pull/4561#issuecomment-1750453209

The silently changing name brings trouble, we can only know the affecting after full test.

cc @bk201 @markhillgit @khushboo-rancher

**Comment by w13915984028** [comment]
some tests in Harvester v1.1.2: (Longhorn v1.3.2:)

**The `backingimage` names seem not truncated, but when it's name is long enough, the image size is alway 0, and the image is not ready, further caused the template to be `Not Ready`.** Looks the behaviour depends on the `template` name, not `vm` name.


> vm name: `vm-with-a-long-name-to-work-in-harvesterv112`

> Three templates were created from this VM, tick the option `With Data`, are result varied:

(1) template name: `template-from-a-long-name-vm-v112-rvxrf`
template is `not ready`
![image](https://github.com/harvester/harvester/assets/31133476/b1a71f65-2dcf-440c-9c00-ecfc827c66be)

template complains:
![image](https://github.com/harvester/harvester/assets/31133476/72da22f9-5cd7-4801-a986-f7a7a5ff48c5)

The related backingimage is not ready
```
harv31:~ # kk get backingimage -A
NAMESPACE         NAME                                                                      UUID       SOURCETYPE           SIZE         AGE
longhorn-system   default-image-nhdpk                                                       dd777e8d   download             16300544     51m
longhorn-system   default-templateversion-template-from-a-long-name-vm-v112-rvxrf-image-0   41539a38   export-from-volume   0            49m
```

(2) template name: `template3-with-medium-sized-name`
template is `not ready`

![image](https://github.com/harvester/harvester/assets/31133476/569ef098-9998-4106-bb3d-839828c891fd)

```
harv31:~ # kk get backingimage -A
NAMESPACE         NAME                                                                      UUID       SOURCETYPE           SIZE         AGE
longhorn-system   default-image-nhdpk                                                       dd777e8d   download             16300544     51m
longhorn-system   default-templateversion-template3-with-medium-sized-name-v4dh8-image-0    9e16d28f   export-from-volume   0            118s
```

(3) template name: `template4-shot`
template is `ready`

```
harv31:~ # kk get backingimage -A
NAMESPACE         NAME                                                                      UUID       SOURCETYPE           SIZE         AGE
longhorn-system   default-image-nhdpk                                                       dd777e8d   download             16300544     51m
longhorn-system   default-templateversion-template4-shot-jw92x-image-0                      4a699dcc   export-from-volume   1073741824   20s
```

A new VM is created from this template:
![image](https://github.com/harvester/harvester/assets/31133476/6104c01d-c4ee-4ac1-93f3-da8222a6ee24)

**Comment by w13915984028** [comment]
clearly, in Harvester v1.2.0 (LH v1.4.3), the `generate template` derived `backingimage`s, are naming with truncated fashion. refer: https://github.com/harvester/harvester/pull/4561

```
harv41:~ # kk get backingimage -A
NAMESPACE         NAME                                       UUID       SOURCETYPE           SIZE         AGE
longhorn-system   default-image-7k9q7                        a37483e8   download             16300544     15d
longhorn-system   default-templateversion-templat-50bc7375   6194981a   export-from-volume   1073741824   5m16s
longhorn-system   default-templateversion-templat-9d4af93b   1c6eedd6   export-from-volume   1073741824   3m38s
longhorn-system   default-templateversion-vm3-new-d4ee304a   0f8835be   export-from-volume   1073741824   23h
```

**Comment by khushboo-rancher** [comment]
@irishgordo Could you please work on adding the e2e automation test for this case?

**Comment by WebberHuang1118** [comment]
This issue depends on #4799 and LH issue [#6899](https://github.com/longhorn/longhorn/issues/6899). 

#4799 is already [addressed](https://github.com/harvester/harvester/pull/4785), and LH issue [#6899](https://github.com/longhorn/longhorn/issues/6899) requires [an upgrade to LH v1.4.5 ](https://github.com/harvester/harvester/pull/5322)to include the solution.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.2-4db9146e-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create VM `vm1` and start it
4. Generate template from `vm1` with **Data** named `vm1t`
5. New image should created while generating template
6. Create VM `vm2` from template `vm1t`
7. VM should able to create and running normally
