### ISSUE TITLE
[BUG] The harvester is unavailable somehow by using the new IP to visit when the original host is down

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#459]
**Describe the bug**
The harvester status appears to double running in the console

**To Reproduce**
1. Install harvester via ISO installation. (`node01`)
2. Add two more nodes to the environment(`node02` and `node03`)
3. Shut down node01
4. Using the new IP to access Harvester

**Result:**
The harvester is unavailable somehow by using the new IP to visit
![image](https://user-images.githubusercontent.com/57614736/106447036-f8c11f00-64bb-11eb-953a-93087e4658e0.png)

**Environment:**
 - Harvester ISO version: master (716900d)
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by futuretea** [comment]
k3s-io/k3s#1264
Also need to up harvester deployment replicas to 3

**Comment by DoNotSayYes** [comment]
For now, all the harvester replicas are scheduled to one node, if that node is down, the harvester will be unreachable
![image](https://user-images.githubusercontent.com/57614736/109276915-93114a00-7851-11eb-994f-668b96cfc331.png)
![image](https://user-images.githubusercontent.com/57614736/109277044-bc31da80-7851-11eb-9a81-e09fc5ab33a5.png)

**Comment by DoNotSayYes** [comment]
Validated on master-head
