### ISSUE TITLE
[BUG] Management status is `NotReady` after power failure

### ISSUE THREAD

**Issue by andre0xFF** [harvester/harvester#4593]
**Describe the bug**
Harvester 1.2.0 was functioning correctly until a power outage occurred. Following the server's recovery, the management status displays as "NotReady," while the node status remains in the "Ready" state. Attempting to access the management URL results in an "ERR_ADDRESS_UNREACHABLE" error.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install Harvester 1.2.0 on a server and ensure it's functioning correctly.
2. Simulate a power failure or sudden shutdown of the server.
3. After the power failure, restart the server or bring it back online.
4. Check the management status, which should now display as "NotReady."
5. Verify that the node status remains in the "Ready" state.
6. Attempt to access the management URL, and observe the "ERR_ADDRESS_UNREACHABLE" error.

**Expected behaviour**
In the event of a power failure or sudden server shutdown, the system should gracefully handle the interruption. After the server is restarted or brought back online, the management status should automatically return to "Ready."

**Support bundle**

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal custom build running on Asus B760M-Plus and Intel i5 13500.

**Additional context**
Running **kubectl get pods -n kube-system**, the following pod statuses are observed:
```
- harvester-whereabouts-l9fwf is in a CrashLoopBackOff state.
- rke2-canal-sfzdz is in an Init:CrashLoopBackOff state.
```

When examining the logs with **kubectl logs -n kube-system harvester-whereabouts-l9fwf**, the following error is encountered:
`Error from server: Get "htts://192.168.1.7:10250/containerLogs/kube-system/harvester-whereabouts-l9fwf/whereabouts": proxy error from 127.0.0.1:9345 while dialing 192.168.1.7:10250, code 503: 503 Service Unavailable`

Thank you!

**Comment by w13915984028** [comment]
Please add more details:

```
1. Is this single-node cluster or multi-node cluster
2. The CPU core, memory and disk size of each NODE is this cluster
3. kubectl get pods -A
```

**Comment by andre0xFF** [comment]
> Please add more details:
> 
> ```
> 1. Is this single-node cluster or multi-node cluster
> 2. The CPU core, memory and disk size of each NODE is this cluster
> 3. kubectl get pods -A
> ```

1. It is a single-node cluster.
2. The i5 13500 is a 14 core CPU, it has 64 GB of memory and Harvester is installed in a 256 GB NVME SSD and data is using a 1TB SSD.

I'll post **kubectl get pods -A** when I get the chance because I can't ssh into the server.

**Comment by andre0xFF** [comment]
Here it is

![image](https://github.com/harvester/harvester/assets/12186770/f786e038-4604-4de5-b820-8dc28d23faf9)
![image](https://github.com/harvester/harvester/assets/12186770/fbbce317-c812-43dc-a72e-83139837ee8e)
![image](https://github.com/harvester/harvester/assets/12186770/eabe673d-29c9-4700-b263-16d9c98df088)

**Comment by w13915984028** [comment]
Did you use `dhcp` or `static` for the NODE IP ? Both NODE IP and VIP can't change, you need to make sure the DHCP server can offer the same IP in case it is used, normally via `IP/MAC` binding.

**Comment by andre0xFF** [comment]
It was configured with DHCP and I should've configured it with static. I guess I'll need to change **/etc/sysconfig/network** files to set static IPs. Is there a place I can look to see how it should look like?

**Comment by w13915984028** [comment]
Please check this file:  `/oem/90_custom.yaml` and `/oem/harvester.config`, there will be some contents as below, get the values of `BOOTPROTO`.

 `/oem/90_custom.yaml` :
```
    - path: /etc/sysconfig/network/ifcfg-mgmt-bo
      permissions: 384
      owner: 0
      group: 0
      content: |+
        STARTMODE='onboot'
        BONDING_MASTER='yes'
        BOOTPROTO='none'
        POST_UP_SCRIPT="wicked:setup_bond.sh"


        BONDING_SLAVE_0='ens3'

        BONDING_MODULE_OPTS='miimon=100 mode=active-backup '

        DHCLIENT_SET_DEFAULT_ROUTE='no'

    - path: /etc/sysconfig/network/ifcfg-ens3
      permissions: 384
      owner: 0
      group: 0
      content: |
        STARTMODE='hotplug'
        BOOTPROTO='none'
      encoding: ""
      ownerstring: ""
```

`/oem/harvester.config`
```
install:
  automatic: false
  mode: create
  managementinterface:
    interfaces:
    - name: ens3
      hwaddr: 52:54:00:6e:5c:2a
    method: dhcp
    ip: ""
    subnetmask: ""
    gateway: ""
    defaultroute: true
    bondoptions:
      miimon: "100"
      mode: active-backup
    mtu: 0
    vlanid: 0
  vip: 192.168.122.199
```

**Comment by w13915984028** [comment]
@andrewdafonseca 

Please also add those bundle of information:

```
# kubectl get pods -n harvester-system harvester-whereabouts-l9fwf -oyaml
# kubectl get pods -n cattle-system harvester-cluster-repo-67ddddf8d7-4n6bw -oyaml
# kubectl get managedchart -A
# kubectl get bundle -A

# ip addr show dev mgmt-br

3: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:6e:5c:2a brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.131/24 brd 192.168.122.255 scope global mgmt-br
       valid_lft forever preferred_lft forever
    inet 192.168.122.199/32 scope global mgmt-br
       valid_lft forever preferred_lft forever

container images, there should be many

#  crictl image ls

IMAGE                                                                       TAG                             IMAGE ID            SIZE
docker.io/banzaicloud/eventrouter                                           v0.1.0                          00f781432854f       67.7MB
docker.io/csiplugin/snapshot-controller                                     v4.0.0                          f1d8a00ae690f       47.8MB
docker.io/kubevip/kube-vip-cloud-provider                                   v0.0.1                          5d5b371eade4b       89.5MB
docker.io/library/alpine                                                    3                               9ed4aefc74f67       7.34MB
docker.io/library/busybox                                                   1.32.0                          219ee5171f800       1.45MB
docker.io/longhornio/backing-image-manager                                  v3_20221003                     1a7095f7e9bc9       343MB
docker.io/longhornio/csi-attacher                                           v3.4.0                          03e115718d258       56.2MB
docker.io/longhornio/csi-node-driver-registrar                              v2.5.0                          cb03930a2bd42       20.9MB
docker.io/longhornio/csi-provisioner                                        v2.1.2                          0f0a0f7990768       52.9MB
...
```

**Comment by andre0xFF** [comment]
I just booted the server and it was able to pick up the same IP as before. So it's working. Here's configuration:

**cat /oem/90_custom.yaml**

```
    - path: /etc/sysconfig/network/ifcfg-mgmt-bo
      permissions: 384
      owner: 0
      group: 0
      content: |+
        STARTMODE='onboot'
        BONDING_MASTER='yes'
        BOOTPROTO='none'
        POST_UP_SCRIPT="wicked:setup_bond.sh"


        BONDING_SLAVE_0='eno1'

        BONDING_MODULE_OPTS='miimon=100 mode=active-backup '

        DHCLIENT_SET_DEFAULT_ROUTE='no'

      encoding: ""
      ownerstring: ""
    - path: /etc/sysconfig/network/ifcfg-eno1
      permissions: 384
      owner: 0
      group: 0
      content: |
        STARTMODE='hotplug'
        BOOTPROTO='none'
      encoding: ""
      ownerstring: ""
    - path: /etc/sysconfig/network/ifcfg-mgmt-br
      permissions: 384
      owner: 0
      group: 0
      content: |+
        STARTMODE='onboot'
        BOOTPROTO='dhcp'
        BRIDGE='yes'
        BRIDGE_STP='off'
        BRIDGE_FORWARDDELAY='0'
        BRIDGE_PORTS='mgmt-bo'
        PRE_UP_SCRIPT="wicked:setup_bridge.sh"
        POST_UP_SCRIPT="wicked:setup_bridge.sh"




        DHCLIENT_SET_DEFAULT_ROUTE='yes'


      encoding: ""
      ownerstring: ""
```
**sudo cat /oem/harvester.config**
```
install:
  automatic: false
  mode: create
  managementinterface:
    interfaces:
    - name: eno1
      hwaddr: 08:bf:b8:35:04:40
    method: dhcp
    ip: ""
    subnetmask: ""
    gateway: ""
    defaultroute: true
    bondoptions:
      miimon: "100"
      mode: active-backup
    mtu: 0
    vlanid: 0
  vip: 192.168.1.7
```

**Comment by andre0xFF** [comment]
Also, this is a brand new installation so I'm ok with wiping it and installing it again if it's just easier to fix it

**Comment by w13915984028** [comment]
@andrewdafonseca What do you mean, the cluster is in running state now ? 

If not, please get more information: https://github.com/harvester/harvester/issues/4593#issuecomment-1757649291, thanks.

**Comment by andre0xFF** [comment]
Yes, yesterday I booted the server and it's in ready state. My guess is that the DHCP provided the same IP when the server was installed

**Comment by w13915984028** [comment]
Good, then you may close this issue, thanks.

**Comment by andre0xFF** [comment]
Thanks for all the help
