### ISSUE TITLE
[BUG] Cannot get any VM started on harvester v1.2.0

### ISSUE THREAD

**Issue by pauljfilmalter** [harvester/harvester#4594]
**Describe the bug** 
Cannot get any of my VMs on my harvester cluster (1.2.0) started... 
status stuck on  
Guest VM is not reported as running
 
**To Reproduce**
1. in the harvester dashboard 
2. Go to 'Virtual Machines'
3. Select any of the vm on the list
4. Click on start
5.  

**Expected behavior**
VM has to start and be able to vire progress in the console (Web VNC)
 
**Support bundle**

**Environment**
 - Harvester ISO version: 1.2.0
 - Underlying Infrastructure: Baremetal with thinkcenter M920q

**Additional context**

**Comment by Martin-Weiss** [comment]
Seems this is not enough information to help. Maybe not enough CPU/Memory or disk space or BIOS settings not having virtualization enabled.. lots of possible reasons.

I guess a supportbundle might give some more details - or a kubectl describe on the VM pod created..

**Comment by w13915984028** [comment]
ssh into the Harvester OS, 
```
sudo -i
ls /dev/kvm
```

if there is no `/dev/kvm`, it is related to your server does not enable `virtualization/nested-virtualization`.

**Comment by pauljfilmalter** [comment]
> Seems this is not enough information to help. Maybe not enough CPU/Memory or disk space or BIOS settings not having virtualization enabled.. lots of possible reasons.
> 
> I guess a supportbundle might give some more details - or a kubectl describe on the VM pod created..
