### ISSUE TITLE
[ENHANCEMENT] Bump SLE-for-rancher 5.4

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4595]
**Is your enhancement related to a problem? Please describe.**
Bump the SLE-for-rancher to 5.4 for harvester OS

**Describe the solution you'd like**
Bump the SLE-for-rancher to 5.4

**Describe alternatives you've considered**
None

**Additional context**
- [x] elemental enhancement (move to the latest stable version)
- [x] remove anything from `Luet`
  - https://github.com/harvester/harvester-installer/pull/606
  - https://github.com/harvester/harvester/pull/4795
  - https://github.com/harvester/os2/pull/82
- [x] Add `sensor` command - https://github.com/harvester/harvester/issues/4681
- [x] Bump `kubevirt-virtctl` to v1.1.0
- [x] Bump `yip` to latest (v1.4.6)

**Comment by jeff-radick-suse** [comment]
Based on what I have been told, this task has been completed so we can close this, right?

**Comment by bk201** [comment]
@jeff-radick-suse, in general, we need QA to verify the issue before closing it.
@Vicente-Cheng Maybe we can have a test plan here, but also add test plans for 
- https://github.com/harvester/harvester/issues/4745

**Comment by Vicente-Cheng** [comment]
Hi @jeff-radick-suse,
I added a test plan for the libnvme issue https://github.com/harvester/harvester/issues/4745 above; I thought we could verify it together.
```
# rpm -qa |grep nvme
libnvme1-1.0-150400.1.6.x86_64
nvme-cli-2.0-150400.1.6.x86_64
```

**Comment by jeff-radick-suse** [comment]
That looks good.  That is the test I was thinking.

**Comment by albinsun** [comment]
Provide test result on `master-6ca6acfd-head`, close as fixed.


## Environment
* Harvester
  * Version: `master-6ca6acfd-head`
  * Profile: QEMU/KVM, 2 nodes (8C/20G/500G)
  * ui-source: `Auto`


## Steps 
1. Should NOT have commands `/usr/bin/luet` :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/04319651-87be-4398-b9fb-096d1ae437b7)

1. Have `sensor` and `libsensors` installed :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/4ed0b5dc-96f5-4bac-b927-9d709b6d3ecf)

1. Have `nvme-cli` and `libnvme` installed :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/50a352ac-fc63-46c3-8982-da1e14ea1049)

1. Have `kubevirt-virtctl` with version `1.1.0` :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/0fbe9c6b-72ed-4354-bae5-3c699dd67d23)

1. Have `yip` with version `1.4.6` :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/24177bec-0feb-4a5d-bb6b-12e7fd15da9a)

1. OS bumped to `SLE 5.4` :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/20ac97d6-dc0a-4a3e-8554-6ef9ee8ec2e6)
