### ISSUE TITLE
[BUG] After promote node role, existing vmi will be recreated

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#460]
**Describe the bug**

**To Reproduce**
1. up one master A and one node B
2. create a vm on the node B
3. join another node C

node B and node C will be promoted to master
vmi on node B will be recreated

**Expected behavior**

vmi on the node B won't be recreated

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DoNotSayYes** [comment]
Validated on master-head

**Steps:**
1. Add one master A and one node B
2. Create a VM on the node B
3. Join another node C

**Result:**
After node B and C were promoted to master, the VM does not encounter restarting
