### ISSUE TITLE
[BUG] Avoid to delete LH settings

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4600]
**Describe the bug**
LH prevents users from deleting LH settings. Harvester tries to delete the `backup-target-credential-secret` setting when users update the `backup-target` setting. We have to refactor this part.

LH Ref: https://github.com/longhorn/longhorn/issues/4984
Harv Ref: https://github.com/harvester/harvester/blob/6da66dc6f7bdebf43bd4932eb5128642ec397e51/pkg/controller/master/backup/backup_target.go#L110-L124

**To Reproduce**
1. Run Harvester with latest LH version.
2. Setup the backup target and we will get an error.

**Expected behavior**
1. Users can setup the backup target.
2. All old test cases pass.

**Comment by lanfon72** [comment]
Verified NFS/S3 backup-target could be configured and spawn backups successfully.

(`test_restore_replace_with_delete_vols` is known issue in #4640)
![image](https://github.com/harvester/harvester/assets/5169694/ec26cf68-6a20-4dcd-92f6-cfad53dbafbe)


Test Information
----
* Environment: **Baremetal DL360G9 5 nodes**
* Harvester Version: **v1.3.0-dev-20231222**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create VM `vm1`
3. Setup NFS/S3 backup-target
4. Backup `vm1` and restore `vm1`
5. VM should be backup and restore successfully
6. Backup-target should able to configured and switched successfully
