### ISSUE TITLE
[ENHANCEMENT] Be able to join new nodes to clusters with a custom certificate configured

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4603]
**Is your enhancement related to a problem? Please describe.**

Users can't join new nodes into Harvester clusters with configured custom certificates. The Rancher System Agent that bootstraps the node will suffer from the "certificate signed by unknown authority" issue. We need a way to add the CA to the trust list of newly joined nodes.

**Describe the solution you'd like**

Since Rancherd will be brought up before the Rancher System Agent, injecting the CA into the system when Rancherd is processing the joining Plan is a good point in time. We already have the relevant code snippet in Rancherd, which [fetches the CA cert provided by the embedded Rancher Manager](https://github.com/rancher/rancherd/blob/f70e187c319d259058411e39d6dee7e036491693/pkg/cacerts/cacerts.go#L107). Adding the CA cert into the system's trust list with a few file and instruction in the joining Plan should be easy.

**Describe alternatives you've considered**

Let users manually provide the CA during node installation. That means users must find a place to serve the CA file and fill in the URL in the `harvester-installer`, which is a bit cumbersome regarding user experience.

**Additional context**

This is a follow-up issue for #4511. We only documented the workaround there.

**Comment by starbops** [comment]
**Test Plan**

1. Prepare a Harvester cluster using the ISO image built from the master branch
2. Configure `ssl-certificates` with a set of custom SSL certificates

```
# fill in the VIP of your setup
export VIP="192.168.48.240"

# root ca key
openssl genrsa -out ca.key 4096

# root ca cert
openssl req -x509 -new -nodes -key ca.key -sha256 -days 3650 -out ca.crt -subj "/CN=Root CA"

# key
openssl genrsa -out harvester.key 4096

# csr with IP SAN
openssl req -reqexts SAN -config <(cat /etc/ssl/openssl.cnf <(printf "\n[SAN]\nsubjectAltName=DNS:harvester.$VIP.sslip.io,IP:$VIP")) -new -sha256 -key harvester.key -subj "/CN=harvester.$VIP.sslip.io" -out harvester.csr

# signing cert with IP SAN
openssl x509 -req -extfile <(printf "subjectAltName=DNS:harvester.$VIP.sslip.io,IP:$VIP") -in harvester.csr -CA ca.crt -CAkey ca.key -CAcreateserial -out harvester.crt -days 3650 -sha256
```

![image](https://github.com/harvester/harvester/assets/1827717/c902eb29-6b44-431e-b3e2-5ebb353e86f4)

3. Prepare another node with the custom-built ISO image containing the enhancement acting as the joining node
4. Fill in the FQDN, e.g., `harvester.$VIP.sslip.io`, for the management address field during Harvester installation

![image](https://github.com/harvester/harvester/assets/1827717/825109d7-2d2e-4ab0-889f-d0f0cf91913b)

5. Go through the rest of the installation steps and wait for the node to reboot
6. The joining node should be in the "Ready/Ready" state eventually after reboot
7. (Optional) Check if the CA `/var/lib/ca-certificates/pem/Root_CA.pem` exists on the joining node

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/harvester/harvester/assets/5169694/b1825988-35da-4d1e-a11c-133d629b35d5)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-d3dc81ca-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Follow Test Plan in https://github.com/harvester/harvester/issues/4603#issuecomment-1759220970
