### ISSUE TITLE
[BUG] Restore from snapshot not work if target VM is restore-replaced from backup

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4604]
## Description
Restore from snapshot not work if target VM is restore-replaced from backup

## Environment
* Harvester
  * Version: `v1.2.1-rc1`
  * Profile: QEMU/KVM, 3 node (8C/16G/250G)
  * **ui-source**: Auto

## To Reproduce
> **Note** Click "►" to expand details.
1. <details>
   <summary>
   Config backup-target ${~~~\color{green}\textsf{V}}$
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/78ecbbf6-bfda-4fc2-b749-87985233422d)
   </details>

1. <details>
   <summary>
   Create VM, wait VM `Running` ${~~~\color{green}\textsf{V}}$
   </summary>
  
   ![image](https://github.com/harvester/harvester/assets/2773781/9146734b-4063-43b9-a737-20b3ef793a1d)
   ![image](https://github.com/harvester/harvester/assets/2773781/642898b7-5b67-48d7-b677-e91da17175ea)
   </details>

1. <details>
   <summary>
   Take Backup, wait backup `Ready` ${~~~\color{green}\textsf{V}}$
   </summary>

   Go to "Virtual Machines" -> VM -> "⋮" -> "Take Backup"
   ![image](https://github.com/harvester/harvester/assets/2773781/1995b671-ab46-4904-85c2-139b5b23a7d3)
   </details>

1. <details>
   <summary>
   Take VM Snapshot, wait snapshot `Ready` ${~~~\color{green}\textsf{V}}$
   </summary>

   Go to "Virtual Machines" -> VM -> "⋮" -> "Take VM Snapchot"
   ![image](https://github.com/harvester/harvester/assets/2773781/a11c5f1f-14dd-4469-9a22-fe94ee474e59)
   </details>

1. <details>
   <summary>
   Stop VM, wait VM `Off` ${~~~\color{green}\textsf{V}}$
   </summary>
   
   Go to "Virtual Machines" -> VM -> "Stop"
   ![image](https://github.com/harvester/harvester/assets/2773781/d91a00fc-0874-4ef8-8efb-66107928ca1c)
   </details>

1. <details>
   <summary>
   Restore (Replace) from backup, wait VM `Running` ${~~~\color{green}\textsf{V}}$
   </summary>
   
   Go to "Backup & Snapshot" -> "VM Backups" -> BACKUP -> "⋮" -> "Replace Existing" 
   ![image](https://github.com/harvester/harvester/assets/2773781/aa44c765-232e-411e-99f5-574596d4d12b)
   ![image](https://github.com/harvester/harvester/assets/2773781/38c9bb51-acf2-4e87-bffe-a992036cbb5a)
   ![image](https://github.com/harvester/harvester/assets/2773781/f3875bd6-240c-4b4a-b090-bcab61e86d1c)
   ![image](https://github.com/harvester/harvester/assets/2773781/6924adb4-67e3-4a8d-b520-fff6e8386a72)
   </details>

1. <details>
   <summary>
   Stop VM again ${~~~\color{green}\textsf{V}}$
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/40af9a4d-d41f-4e22-88e5-ab670aa26d04)
   </details>

1. <details>
   <summary>
   Restore (Replace) from snapshot ${~~~\color{red}\textsf{X, VM is not replaced and start.}}$
   </summary>

   Go to "Backup & Snapshot" -> "VM Snapshots" -> SNAPSHOT -> "⋮" -> "Replace Existing" 
   ![image](https://github.com/harvester/harvester/assets/2773781/674bc5bb-1e84-4565-b5e5-cb11088e5691)
   ![image](https://github.com/harvester/harvester/assets/2773781/88d2a5c4-feb1-4857-8598-3af520080ed2)
   ![image](https://github.com/harvester/harvester/assets/2773781/4c369855-ea79-49d4-b58e-f55345265a6c)
   </details>

1. <details>
   <summary>
   Restore (New) from snapshot ${~~~\color{red}\textsf{X, no new VM created.}}$
   </summary>
   
   Go to "Backup & Snapshot" -> "VM Snapshots" -> SNAPSHOT -> "⋮" -> "Restore New" 
   ![image](https://github.com/harvester/harvester/assets/2773781/8a0122c5-7f04-4033-bbd8-d851b57916af)
   ![image](https://github.com/harvester/harvester/assets/2773781/ce2866bd-6720-41be-8910-57c4499b8bdf)
   ![image](https://github.com/harvester/harvester/assets/2773781/e772aa80-9e33-450a-97ca-7dbceb716a3a)
   </details>

## Expected Behavior
If Harvester consider "Target VM" still there even the original VM is replaced by backup restore, and restore should work.
![image](https://github.com/harvester/harvester/assets/2773781/8fd2b18a-0636-4808-9536-00d9351cf2a4)

## Note
1. Reproduce both in single node and 3 nodes setup.

## Support Bundle
1. single node env.
[supportbundle_restore_existing_from_bak_then_snap-single_2023-10-12T05-27-41Z.zip](https://github.com/harvester/harvester/files/12877432/supportbundle_restore_existing_from_bak_then_snap-single_2023-10-12T05-27-41Z.zip)
1. 3 nodes env.
[supportbundle_restore_existing_from_bak_then_snap_2023-08-25T07-21-23Z.zip](https://github.com/harvester/harvester/files/12877065/supportbundle_restore_existing_from_bak_then_snap_2023-08-25T07-21-23Z.zip)

**Comment by TachunLin** [comment]
Verified **failed** on `v1.3-f132d7fa-head` (24/01/02) . Move this issue to implement. 

### Result
- [x] When vm have a backup and snapshot -> stopped the vm -> restore to replace from backup 
   Then do the **restore** vm from snapshot to **create new** one, there is no new VM created from the snapshot

    <details><summary>Test Result $~~$ $\color{red}{\textsf{Failed}}$ </summary>


    https://github.com/harvester/harvester/assets/29251855/8b750082-70ee-4b6c-8c08-61543ee04cf9


    </details>


### Test Information
* Test Environment: 3 nodes harvester on baremetal machines
* Harvester version: `v1.3-f132d7fa-head` (24/01/02)

### Verify Steps
<details><summary>Execution Steps</summary>

1. Config backup-target to NFS backup target
![image](https://github.com/harvester/harvester/assets/29251855/1952c096-5af3-4017-9b1a-07535f36bd59)

2. Create VM, wait VM to `Running` state
![image](https://github.com/harvester/harvester/assets/29251855/a57b7e13-b912-414c-a66f-81fde7229428)

3. Take Backup, wait backup `Ready` 
![image](https://github.com/harvester/harvester/assets/29251855/c09f6195-0e93-47f1-8df5-460e9deb398b)

4. Take VM Snapshot, wait snapshot `Ready
5. Stop VM, wait VM `Off`
6. Restore (Replace) from backup, wait VM `Running`
7. Stop VM again
8. Restore from snapshot, create a new VM
9. Check if new VM created

</details>


**Support bundle**
[supportbundle_d35d2a52-e5d8-423a-a932-f5b5eddd1acb_2024-01-02T10-11-53Z.zip](https://github.com/harvester/harvester/files/13809009/supportbundle_d35d2a52-e5d8-423a-a932-f5b5eddd1acb_2024-01-02T10-11-53Z.zip)

**Comment by FrankYang0529** [comment]
> Verified **failed** on `v1.3-f132d7fa-head` (24/01/02)

Hi @TachunLin, may you use master-head to test it? My commit `03039ce` has not been backported to v1.3 branch yet.

<img width="1050" alt="Screenshot 2024-01-04 at 2 56 28 PM" src="https://github.com/harvester/harvester/assets/4927361/dc1a5afc-c560-4cf9-ab60-5326285ee2a8">

<img width="1281" alt="Screenshot 2024-01-04 at 2 57 10 PM" src="https://github.com/harvester/harvester/assets/4927361/fdd5926b-351d-47ec-afd9-8e7d067c8e3c">

**Comment by TachunLin** [comment]
Verified **fixed** on `master-d3dc81ca-head` (23/01/05). Close this issue.

Test five times the scenario back and force in the row, did not encounter these issue during the verification process.

### Result
- [x] 1. Can restore the snapshot to replace original vm when the vm have been restored from backup

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>


    https://github.com/harvester/harvester/assets/29251855/3a8f12d6-7fdc-42af-8f51-c5d5bbfcb248



    </details>

- [x] 2. Can restore the snapshot to create the new vm when the vm when the vm have been restored from backup

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>

    https://github.com/harvester/harvester/assets/29251855/04034f93-2e35-4a13-9e05-71a671cfc7fe


    </details>


### Test Information
* Test Environment: 3 nodes harvester on bare metal machines
* Harvester version: `master-d3dc81ca-head` (23/01/05)

### Verify Steps
<details><summary>Execution Steps</summary>

  1. Config backup-target to NFS backup target
  2. Create VM, wait VM to Running state
  3. Take Backup, wait backup Ready
  4. Take VM Snapshot, wait snapshot `Ready`
  5. Stop VM, wait VM Off
  6. Restore (Replace) from backup, wait VM Running
  7. Stop VM again
  8. Restore from snapshot, replace the current VM
  9. Check the vm is running
  10. Restore from snapshot, create a new VM
  11. Check the new vm is created and running

</details>
