### ISSUE TITLE
[ENHANCEMENT] Bump LH to v1.5.x in Harv v1.3.0

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4606]
**Is your enhancement related to a problem? Please describe.**
LH v.14.x will be EOL in 2024/03/13. Also, LH only allows to upgrade 1 major or minor version after v1.5.x. If we don't bump LH to v1.5.x in Harv v1.2.x. We can't include LH v1.6 new features in Harv v1.3. For example:

* [[FEATURE] Longhorn snapshot space management](https://github.com/longhorn/longhorn/issues/6563#top)
* [[FEATURE] Restore BackingImage for BackupVolume in a new cluster](https://github.com/longhorn/longhorn/issues/4165#top)

**Comment by lanfon72** [comment]
close as verified.

![image](https://github.com/harvester/harvester/assets/5169694/0788ad02-7037-464b-b54a-df4d78d6feb7)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.3-f132d7fa-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Access embedded Longhorn UI
