### ISSUE TITLE
[Question] cluster-registration-url timeout

### ISSUE THREAD

**Issue by gsuess** [harvester/harvester#4609]
If get this error when trying to set `cluster-registration-url`:

```
Get "https://<domain redacted>/v3/import/<key readacted>.yaml": context deadline exceeded (Client.Timeout exceeded while awaiting headers).
```
Downloading the  file through curl on the same node works fine though. 

I have also tried rebooting and resetting the configuration.

On the host when I ping google or any other  internet resource, it resolves to the correct IP address. Within pods however `nslookup` still resolves the correct IP address, but the ping goes to public IP address of the network in which the cluster resides in.

- Which logs should look into to troubleshoot further?

**Comment by gsuess** [comment]
After some further troubleshooting I found that this is related to the DNS issue:

One the host a ping to `google.com` resolved the correct IP address:

```
# ping google.com
PING google.com (142.250.181.206) 56(84) bytes of data.
64 bytes from ham02s21-in-f14.1e100.net (142.250.181.206): icmp_seq=1 ttl=117 time=18.9 ms
64 bytes from ham02s21-in-f14.1e100.net (142.250.181.206): icmp_seq=2 ttl=117 time=18.9 ms
64 bytes from ham02s21-in-f14.1e100.net (142.250.181.206): icmp_seq=3 ttl=117 time=18.9 ms
^C
--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2003ms
rtt min/avg/max/mdev = 18.868/18.885/18.903/0.014 ms
```

The same is true on docker container, but not on a kubernetes pod, where an incorrect IP address is resolved.

In particular, within a pod `google.com` is being prepended to a search domain in `resolve.conf`. Since that domains containers a `*` wildcard record, it resolves for that record.

There reason for this is because there is a `ndots` option for resolv.conf that is set to 5:

```
search default.svc.cluster.local svc.cluster.local cluster.local harvester.<redacted domain>
nameserver 10.53.0.10
options ndots:5
```

Now the only question that remains is why it was set to 5.

**Comment by gsuess** [comment]
I fixed the issue by removing the local domain from the DHCP.

**Comment by gsuess** [comment]
I am closing this question, but it should be noted that an appropriate error message should be shown on the UI.

**Comment by w13915984028** [comment]
@gsuess:

Where is your Rancher server located? and were the `cluster-registration-url` in the format of DNS, not IP address?

When it is FQDN, then from the view of Harvester, it needs the help of certain DNS SERVER to solve this domain. Could this domain be ping-able from Harvester NODE ?

**Comment by gsuess** [comment]
@w13915984028 
The server is on an EKS cluster in the cloud with a FQDN and valid certificate. Every pod on the cluster thought that the FQDN is a subdomain of the local domain which hit the wildcard domain.

So that's why removing the local domain from the DHCP fixed the issue.
