### ISSUE TITLE
[ENHANCEMENT] Check free disk space percent before upgrade

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4611]
**Is your enhancement related to a problem? Please describe.**
From [container image lifecycle document](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#container-image-lifecycle), kubelet triggers grabage collection when disk free space percent is higher than `HighThresholdPercent`. This may make some risks in airgapped environment, because it can't get old images if we don't set container registry correctly.

For example, [missing vmdp image issue](https://github.com/harvester/harvester/issues/4534).

**Describe the solution you'd like**
Add a webhook to check free disk space percent like PR [Check disk space before upgrade](https://github.com/harvester/harvester/pull/3700#top).

**Comment by TachunLin** [comment]
Verified **fixed** on `master-d3dc81ca-head` (24/01/03). Close this issue.

### Result
- [x] 1. The node without enough disk spaces in `/usr/local` can't upgrade

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>

    When /usr/local did not have enough spaces
    
    ```
    rancher@n1-240104:~> df -h /usr/local
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda5       147G   28G  112G  21% /usr/local
    rancher@n1-240104:~> sudo dd if=/dev/zero of=/usr/local/test.img bs=1G count=93
    93+0 records in
    93+0 records out
    99857989632 bytes (100 GB, 93 GiB) copied, 327.656 s, 305 MB/s
    rancher@n1-240104:~> df -h /usr/local
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda5       147G  116G   24G  84% /usr/local
    ```
    
    If we trigger the upgrade, the webhook would prompt message to prevent to proceed
    
    ![image](https://github.com/harvester/harvester/assets/29251855/2e85353e-b05a-4c6c-b95b-b47680514d82)


    </details>

- [x] 2. When the cluster is ready, check Longhorn system-managed components have priority class set.

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>

    When we free the /usr/local spaces
    
    ```
    rancher@n1-240104:/usr/local> sudo rm test.img
    rancher@n1-240104:/usr/local> df -h /usr/local
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda5       147G   23G  118G  16% /usr/local
    ```
    
    We can continue to trigger the upgrade
    
    https://github.com/harvester/harvester/assets/29251855/353cea36-26bf-4fe0-b3b5-b38d1f1df111


    </details>


### Test Information
* Test Environment: 2 nodes harvester on local kvm machine
* Harvester version: `master-d3dc81ca-head` (24/01/03)

### Verify Steps
<details><summary>Execution Steps</summary>

https://github.com/harvester/harvester/pull/4701#issue-1975684372

</details>
