### ISSUE TITLE
[BUG] VMBackup metadata file name conflicts

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4612]
**Describe the bug**
We use `<vmbackup-namespace>-<vmbackup-name>.cfg` as metadata file in backup target. If there is a vmbackup with namespace `a` and name `b-c`, it conflicts with namespace `a-b` and name `c`.

**To Reproduce**
1. Create namespaces `a-b` and `a`.
```
kubectl create ns a-b
kubectl create ns a
```
2. Create two VMs. One is in namespace `a-b` and another in `a`.
3. Take a backup for each VM. The backup name is `c` for VM in namespace `a-b`. Another name is `b-c` for VM in namespace `a`.
4. Run `ls /opt/backupstore/harvester/vmbackups` in backup target. We can only see one `a-b-c.cfg` file.

**Expected behavior**
There are two metadata files. One is for `a-b/c` and another is for `a/b-c` VMBackup.

**Environment**
 - Harvester ISO version: v1.2.0

**Comment by bk201** [comment]
We need to add this information to the doc (e.g., https://docs.harvesterhci.io/v1.2/vm/backup-restore/)
- Path migration. Why it's needed and example.
- Best practice when using a backup store for multiple clusters.

Then mention the doc in the release note.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20240105`, close as fixed.


## Environment
* Harvester
 * Version: `v1.3.0-dev-20240105`
 * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
 * ui-source: `Auto`


## Steps
1. Create namespace **n1** and **n1-n2**
   <details>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/3366fc19-c472-4d6d-93f5-2690e2ac0189)
   </details>


1. Create 2 VMs
   <details>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/9037468f-b382-4e9d-9956-68e2ae9e7455)
   </details>
   
   * In **n1** namespace, create VM **n2-n3**
   * In **n1-n2** namespace, create VM **n3**


1. Create VM backup
   <details>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/838087d6-cb65-47a4-a065-5e25ffdad322)
   </details>
   
   * VM **n1** / **n2-n3** -> Backup name **n2-n3**
   * VM **n1-n2** / **n3** -> Backup name **n3**


1. Check expected VMBackup configs are there
   <details>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/b7200bd3-fad0-435b-89ad-d39b03ba563a)
   </details>

   * VM **n1** / **n2-n3** -> `/opt/backupstore/harvester/vmbackups/n1/n2-n3.cfg` :ballot_box_with_check: 
   * VM **n1-n2** / **n3** -> `/opt/backupstore/harvester/vmbackups/n1-n2/n3.cfg` :ballot_box_with_check:
