### ISSUE TITLE
Harvester VxLan support

### ISSUE THREAD

**Issue by cjohn001** [harvester/harvester#4622]
Hello together,
I am currently playing with Harvester. My initial intent was to deploy Harvester in a production setting at a Hetzner datacenter. Unfortunately, I am seeing 2 show stopper for such a setup. Therefore, for now I switched to a Proxmox installation. Nevertheless, my hope is that soon missing pieces in Harvester come together, as it to my opinion is a very nice product. The first show stopper  is described here https://github.com/harvester/harvester/issues/4608 , hence nothing to add.
The second show stopper is related to the amount of MAC addresses I can use per switch port when using VLans (Hetzner vSwitch feature). The amount of MAC addresses is limited to 30 addresses per switch port. In other words, with one network card I can only support 30 VMs. In Proxmox I can simply create an overlay network with VxLan. Hence, this limitation is resolved with a little overhead. Would be great if VxLan could be made available in Harvester as well.

**Comment by bk201** [comment]
@cjohn001 I'll link your description to https://github.com/harvester/harvester/issues/2322 and close this one since it's duplicated. Thanks for the suggestion.
