### ISSUE TITLE
[ENHANCEMENT] Add webhook for CRD virtualmachinetemplateversion.harvesterhci.io

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4625]
**Is your enhancement related to a problem? Please describe.**

When creating virtualmachinetemplateversion, the required fields `CPU` and `Memory` are not checked from UI or webhook
![image](https://github.com/harvester/harvester/assets/31133476/80745414-30b0-426c-b430-2c8d492acd00)

If it is not filled, later:
view the resource via link like 

> https://192.168.122.144/dashboard/harvester/c/local/harvesterhci.io.virtualmachinetemplateversion/default/t3-mm7w4

will get:
![image](https://github.com/harvester/harvester/assets/31133476/8a222537-b4ff-47c5-9041-80e6d42f42fb)

**Describe the solution you'd like**

Add webhook to check those mandatory fields.

**Describe alternatives you've considered**

Add check in UI.

**Additional context**

**Comment by w13915984028** [comment]
Local test with a webhook validator:

Without input the CPU and memory
![image](https://github.com/harvester/harvester/assets/31133476/b66c8320-39af-4426-b883-b56b66d898be)

Without Memory
![image](https://github.com/harvester/harvester/assets/31133476/df25a81f-2de2-476c-a02e-7c2aa1d69455)

Without CPU
![image](https://github.com/harvester/harvester/assets/31133476/e1f3b4bf-2f18-4d46-b8d7-58cdf6c603c3)

**Comment by w13915984028** [comment]
The PR https://github.com/harvester/harvester/pull/4626 is in v1.3.0 master-head. There is an backport PR in v1.2.2 https://github.com/harvester/harvester/pull/4736.

Verify this issue in v1.3.0 first.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-804669f7-head` (24/01/19).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Without input cpu and memory in vm creation, UI would check and prompt message to prevent $~~$</summary>

* Without input the cpu and memory
![image](https://github.com/harvester/harvester/assets/29251855/4f4ff2f0-bb9f-4ec6-8ef3-838e0ae8b931)

* Without input the cpu 
![image](https://github.com/harvester/harvester/assets/29251855/410ca551-1941-4292-99c3-559f9c5aaf99)

* Without input the memory
![image](https://github.com/harvester/harvester/assets/29251855/67c73db6-ac06-41d6-b3eb-8f756624cff4)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Without input name and image in vm creation, UI would also check and prompt message to prevent $~~$</summary>


* Without input the name and image 
![image](https://github.com/harvester/harvester/assets/29251855/e7bbbd0c-e00a-42bf-8470-47decd73dfb2)

 </details>

### Test Information
* Test Environment: Single node harvester on local kvm machine
* Harvester version: `master-804669f7-head` (24/01/19)

### Verify Steps
<details><summary>Test steps</summary>

  1. Create a virtual machine
  2. Leave the cpu and memory empty and click create 
  3. Check the UI message and reaction
  4. Leave only cpu or memory empty and click create
  5. Check the UI message and reaction
  6. Leave the name and image empty and click create
  7. Provide all the necessary information to click create 
  8. Check can create virtual machine correctly 

</details>
