### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AminGR** [harvester/harvester#4631]
**Describe the bug**

Hanging on " Confirm installation options " for few hours

 
![image](https://github.com/harvester/harvester/assets/33826995/608a500b-5da5-4fb1-ad53-6df68594615d)

**Environment**
 - Harvester ISO version:  v1.2.0 amd64
 - Underlying Infrastructure (e.g. Baremetal with HPE DL360P Gen9):
 - 64G RAM 
 - 1.4TB disk (SAS)

**Comment by bk201** [comment]
@AminGR can you share more details with us:
- How is the installation medium attached to the server?
- What's the server model?

The messages suggest it takes too long to copy image tarballs from the install medium to disk. Is it possible to install Harvester with a USB medium?

**Comment by AminGR** [comment]
Thanks for your reply and sorry for late response.

The above mentioned problem was occurred while using "Virtual Media" functionality ( HPE iLO ) over network .
Now I had time to test it using a USB device directly attached to the server, which resolved the issue for me.

All went well and now I have my second cluster running on v1.2.1:
![harvester 1 2 1](https://github.com/harvester/harvester/assets/33826995/64dc580f-cea4-42b5-a9b8-22d6ef915ff5)
