### ISSUE TITLE
[Question] Upgrading longhorn separately

### ISSUE THREAD

**Issue by sunny760408** [harvester/harvester#4647]
Hi there,

We are using Harverster v1.1.1 and Longhorn v1.3.2. Due to a bug encountered on Longhorn, we would like to upgrade Longhorn to v1.4.1. Can I update the Longhorn version separately?

**Comment by bk201** [comment]
Hi @sunny760408, this is not supported at this moment. Each Harvester version does tests with a Longhorn version. What issue do you see?

**Comment by sunny760408** [comment]
@bk201 this one ([4959](https://github.com/longhorn/longhorn/issues/4959)) and it was improved in [v1.4.0](https://github.com/longhorn/longhorn/releases/tag/v1.4.0).
