### ISSUE TITLE
[BUG] The installer occasionally doesn't run

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4648]
**Describe the bug**

Occasionally, the installer doesn't run when booting. This is spotted in one CI run: https://ci.harvesterhci.io/job/harvester-vagrant-installation-test/1169/

**To Reproduce**
1. Build ISO and run ipxe installation.
2. After booting, the Installer doesn't run and tty1 has an ordinary prompt.
<img width="1017" alt="Screenshot 2023-10-23 at 5 54 30 PM" src="https://github.com/harvester/harvester/assets/1691518/bef6a679-215f-4cda-906a-08ccb507f194">

**Expected behavior**

The installer should display.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
It looks like tty1 is started before we create the installer drop-in:

```
Oct 23 09:07:38 rancher iscsiadm[1711]: iscsiadm: Could not get list of targets from firmware. (err 21)
Oct 23 09:07:38 rancher systemd[1]: Finished Login and scanning of iSCSI devices.
Oct 23 09:07:38 rancher systemd[1]: Reached target Remote File Systems.
Oct 23 09:07:38 rancher systemd[1]: Starting Permit User Sessions...
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Processing stage step 'Copy resolv.conf generated by dracut'. ( commands: 1, files: 0, ... )
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Command output: /etc/resolv.conf is generated from each interface's resolv.conf
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Processing stage step ''. ( commands: 1, files: 0, ... )
Oct 23 09:07:38 rancher systemd[1]: Finished Permit User Sessions.
Oct 23 09:07:38 rancher systemd[1]: Started Getty on tty1.                     <---------- tty1 start
Oct 23 09:07:38 rancher systemd[1]: Reloading.
Oct 23 09:07:38 rancher sshd-gen-keys-start[1722]: ssh-keygen: generating new host keys: RSA DSA ECDSA ED25519
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Command output: Create installer drop-in in /run/systemd/system/getty@tty1.service.d...          <------- drop-in override
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Done executing stage 'boot'
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Running stage: boot.after
Oct 23 09:07:38 rancher elemental[1402]: INFO[2023-10-23T09:07:38Z] Done executing stage 'boot.after'
```

**Comment by bk201** [comment]
The workaround is:

```
systemctl restart getty@tty1.service
```

**Comment by bk201** [comment]
move to reproduce/often, I saw this couple times

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, do not observe hanging, close as fixed.

Provision 3 nodes Harvester for 2 rounds.
![image](https://github.com/harvester/harvester/assets/2773781/e810255d-91f8-4385-96d4-d1c9e24217b4)

## Environment
* Harvester
 * Version: `v1.3.0-dev-20231222`
 * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
 * ui-source: `Auto`


## Steps 
Provision 3 nodes Harvester
1. <details>
   <summary> Round 1 :ballot_box_with_check: 
   </summary>
 
   * node0
     ![image](https://github.com/harvester/harvester/assets/2773781/ed1c2cbe-3fe0-45a5-807a-1bfc3abce302)

   * node1
     ![image](https://github.com/harvester/harvester/assets/2773781/c165a7de-0a90-4b2e-9345-85f26eb0e232)

   * node2
     ![image](https://github.com/harvester/harvester/assets/2773781/3f42de7b-9f55-42dc-b66f-69b272970d68)
 </details>

2. <details>
   <summary> Round 2 :ballot_box_with_check: 
   </summary>
 
   * node0
     ![image](https://github.com/harvester/harvester/assets/2773781/7ff9a3e9-1169-40aa-9866-a1d494bea454)

   * node1
     ![image](https://github.com/harvester/harvester/assets/2773781/fa63d8f2-cc68-4bd9-a93c-1fc1637c6991)

   * node2
     ![image](https://github.com/harvester/harvester/assets/2773781/55cecc8a-6158-4f1a-aff0-1bbb7d443f76)
 </details>
