### ISSUE TITLE
[BUG] go mod tidy not work because jobq is removed

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4651]
**Describe the bug**
Run `go mod tidy` and we will get following response:

```
go: github.com/longhorn/longhorn-engine@v1.4.2-0.20230505032747-3343bb5fba06 requires
	github.com/honestbee/jobq@v1.0.2: reading github.com/honestbee/jobq/go.mod at revision v1.0.2: git ls-remote -q origin in /Users/poanyang/go/1.21.3/pkg/mod/cache/vcs/b7039093cfd5e54747139d9a392f45ffb733fb74488bd673022aa3b33e2ae79f: exit status 128:
	remote: Repository not found.
	fatal: repository 'https://github.com/honestbee/jobq/' not found
```

**To Reproduce**
Run `go mod tidy`.

**Expected behavior**
We can run the command without error.

**Comment by Yu-Jack** [comment]
Add more context. LH Engine already removed the honestbee/jobq after [1.5.0](https://github.com/longhorn/longhorn-engine/blob/v1.5.0/go.mod).

**Comment by FrankYang0529** [comment]
> Add more context. LH Engine already removed the honestbee/jobq after [1.5.0](https://github.com/longhorn/longhorn-engine/blob/v1.5.0/go.mod).

Yeah, they removed in this commit.

https://github.com/longhorn/longhorn-engine/commit/2d191ac0b90aa74e67cbcffa842d9895a6095838

**Comment by FrankYang0529** [comment]
PR is merged. Close the issue.
