### ISSUE TITLE
[ENHANCEMENT] Register API services with TokenRequest API

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4657]
**Is your enhancement related to a problem? Please describe.**

This is a heads-up from Rancher team:

> in Rancher we've made some updates to how service account tokens are handled as part of a k8s 1.27 issue (https://github.com/rancher/rancher/issues/42861). As part of this, this might affect the functionality of the v3.ApiService resource, which seems like it can be used by harvester as part of the dashboard functionality end (pr: https://github.com/rancher/rancher/pull/33830, linked issue: https://github.com/harvester/harvester/issues/1091 ). We'd like to ask you if you can do the following items before 2.8 goes live:
> Can you check your relevant use cases to see if this functionality is used?
> Can you do a basic test of the functionality to make sure that your use cases are not affected?

**Describe the solution you'd like**

Register API services with TokenRequest API

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
@FrankYang0529 Please help check if we still need this.

**Comment by FrankYang0529** [comment]
Hi @bk201, I import a Harvester cluster with v1.28.8 RKE2 and v2.8.3-rc6 embedded Rancher into v2.8.3-rc6 Rancher. The dashboard works fine. I can login and operate VM without error. Also, there is no error message in embedded Rancher.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/user-attachments/assets/314b256b-baa7-4594-b532-27194142e132)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4.0-dev-20240830**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Enable extension developer features
3. access embedded Rancher dashboard
4. All pages should work as expected
5. Embedded Rancher version should `> v2.8.3`
