### ISSUE TITLE
[BUG] The VM status appears to be running but the disk is not imported yet

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#466]
**Describe the bug**
The VM status appears to be running but the disk is not imported yet

**To Reproduce**
1. Create a VM configuring machine type: pc-q35-5.2
2. Wait for the VM to be brought up

**Result:**
The VM status appears to be `running` but the `importer-lily-001-disk-0-bolgx `status is `containerCreating`. After some time, its status changes to be `starting`. 
![image](https://user-images.githubusercontent.com/57614736/107019832-1dc7d180-67dd-11eb-845e-92819622e7cc.png)
![image](https://user-images.githubusercontent.com/57614736/107020381-c4ac6d80-67dd-11eb-862b-a57f34710e9a.png)
![image](https://user-images.githubusercontent.com/57614736/107021895-a9426200-67df-11eb-8e9a-4fba449ae90d.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
close in favor of v0.3.0 release.
