### ISSUE TITLE
[TASK] v1.1.3 dependencies

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4670]
Bump v1.1.3 dependencies

- Deps
  - [x] Longhorn (https://github.com/harvester/harvester/pull/4672)
  - Kubevirt
    - [x] https://github.com/harvester/harvester/pull/4598#top
    - [x] newer kubevirt https://github.com/harvester/harvester/pull/4718
  - [x] harvester-network-controller ([v0.3.5](https://github.com/harvester/network-controller-harvester/releases/tag/v0.3.5))
  - [x] harvester-node-disk-manager ([v0.5.2](https://github.com/harvester/node-disk-manager/releases/tag/v0.5.2))
  - [x] kube-vip (waiting for @w13915984028 to confirm, Jian suggested not bump)
  - [x] Deprecate kube-vip-cloud-provider? (@w13915984028 suggest not bump, too many changes)
  - [x] harvester-load-balancer ([v0.1.6](https://github.com/harvester/load-balancer-harvester/releases/tag/v0.1.6))
  - [x] whereabouts (https://github.com/harvester/harvester/pull/4261)
  - [x] harvester-node-manager ([v0.1.8](https://github.com/harvester/node-manager/releases/tag/v0.1.8))
  - [x] support-bundle-kit ([PR](https://github.com/rancher/support-bundle-kit/pull/85) in review) ([v0.0.32](https://github.com/rancher/support-bundle-kit/releases/tag/v0.0.32))
  - [x] Update values.yaml file
- [x] Add-ons (Need a new tag, new chart, and bump add-on versions in both harvester/harvester and harvester/installer)
  - [x] pcidevice
  - [x] vm-import-controller
- [x] Check monitoring and logging versions (not addon yet), Jian suggest not bump.
- [x] RKE2 (~~v1.25.15~~, v1.24.17) https://github.com/harvester/harvester-installer/pull/592
- [x] Rancher (v2.6.13) https://github.com/harvester/harvester-installer/pull/592
- [x] OS https://github.com/harvester/harvester-installer/pull/593
- [x] Go versions
  - [x] harvester/harvester https://github.com/harvester/harvester/pull/4732
  - [x] harvester/installer. https://github.com/harvester/harvester-installer/pull/590

**Comment by albinsun** [comment]
Provide test result on a local 3 nodes upgrade.

## Environment
* Harvester
  * Version: `v1.1.1` -> `v1.1.3-rc1`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * **ui-source**: Auto

## Checks
1. Upgrade cluster from `v1.1.1` -> `v1.1.3-rc1`
   ![image](https://github.com/harvester/harvester/assets/2773781/43ae343c-c6e4-4a25-9e94-3cf9ca677a89)

2. Check dependencies version

| Deps | Description[^1] | valus.yaml[^2]  | Test Env. | Comment |
|---   |---              |---              |---        |--       |
| Longhorn   |   |   |   |   |
| kubevirt  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |
| vmdp  |   |   |   |   |

[^1]: Description of this ticket
[^2]: https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml

Deps
 Longhorn (https://github.com/harvester/harvester/pull/4672)
Kubevirt
 https://github.com/harvester/harvester/pull/4598#top
 newer kubevirt https://github.com/harvester/harvester/pull/4718
 harvester-network-controller ([v0.3.5](https://github.com/harvester/network-controller-harvester/releases/tag/v0.3.5))
 harvester-node-disk-manager ([v0.5.2](https://github.com/harvester/node-disk-manager/releases/tag/v0.5.2))
 kube-vip (waiting for @w13915984028 to confirm, Jian suggested not bump)
 Deprecate kube-vip-cloud-provider? (@w13915984028 suggest not bump, too many changes)
 harvester-load-balancer ([v0.1.6](https://github.com/harvester/load-balancer-harvester/releases/tag/v0.1.6))
 whereabouts (https://github.com/harvester/harvester/pull/4261)
 harvester-node-manager ([v0.1.8](https://github.com/harvester/node-manager/releases/tag/v0.1.8))
 support-bundle-kit (https://github.com/rancher/support-bundle-kit/pull/85 in review) ([v0.0.32](https://github.com/rancher/support-bundle-kit/releases/tag/v0.0.32))
 Update values.yaml file
 Add-ons (Need a new tag, new chart, and bump add-on versions in both harvester/harvester and harvester/installer)
 pcidevice
 vm-import-controller
 Check monitoring and logging versions (not addon yet), Jian suggest not bump.
 RKE2 (v1.25.15, v1.24.17) https://github.com/harvester/harvester-installer/pull/592
 Rancher (v2.6.13) https://github.com/harvester/harvester-installer/pull/592
 OS https://github.com/harvester/harvester-installer/pull/593
 Go versions
 harvester/harvester https://github.com/harvester/harvester/pull/4732
 harvester/installer. https://github.com/harvester/harvester-installer/pull/590

**Comment by albinsun** [comment]
Provide test result on a local 3 nodes upgrade from `v1.1.1` to `v1.1.3-rc1`.
Dependencies version looks OK except **vmdp** in the upgrade case (correct in fresh install case).

## Environment
* Harvester
  * Version: `v1.1.1` -> `v1.1.3-rc1`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * **ui-source**: Auto

## Checks
1. longhorn :heavy_check_mark: 
   * Code: `1.3.3`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/Chart.yaml#L41
   * Env.: `1.3.3`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep longhorn-
      longhorn-admission-webhook longhornio/longhorn-manager:v1.3.3
      longhorn-conversion-webhook longhornio/longhorn-manager:v1.3.3
      longhorn-driver-deployer longhornio/longhorn-manager:v1.3.3
      longhorn-ui longhornio/longhorn-ui:v1.3.3
      ```

1. kubevirt :heavy_check_mark: 
   * Code: `0.54.0-150400.3.23.1`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L30
   * Env.: `0.54.0-150400.3.23.1`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep virt
      virt-api registry.suse.com/suse/sles/15.4/virt-api:0.54.0-150400.3.23.1
      virt-controller registry.suse.com/suse/sles/15.4/virt-controller:0.54.0-150400.3.23.1
      virt-operator registry.suse.com/suse/sles/15.4/virt-operator:0.54.0-150400.3.23.1
      ```
1. vmdp :x: 
   * Code: `2.5.4.2`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/pkg/data/template.go#L509
   * Env.: `2.5.3`
      ```
      harvester-node-0:~ # kubectl describe VirtualMachineTemplateVersion/windows-iso-image-base-version -n harvester-public | grep Image
                    Image:              registry.suse.com/suse/vmdp/vmdp:2.5.3
      ```
   * Note
     1. single node fresh install :heavy_check_mark: 
        ```
        harvester-node-0:~ # kubectl describe VirtualMachineTemplateVersion/windows-iso-image-base-version -n harvester-public | grep Image
              Image:              registry.suse.com/suse/vmdp/vmdp:2.5.4.2
        ```
     2. single node upgrade :x: 
        Before (`v1.1.1`)
        ```
        harvester-node-0:~ # kubectl describe VirtualMachineTemplateVersion/windows-iso-image-base-version -n harvester-public | grep Image
              Image:              registry.suse.com/suse/vmdp/vmdp:2.5.3
        ```
        After (`v1.1.3-rc1`)
        ```
        harvester-node-0:~ # kubectl describe VirtualMachineTemplateVersion/windows-iso-image-base-version -n harvester-public | grep Image
              Image:              registry.suse.com/suse/vmdp/vmdp:2.5.3
        ```


1. harvester-network-controller :heavy_check_mark: 
   * Code: `0.3.5`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L368
   * Env.: `0.3.5`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep network-
      harvester-network-controller-manager rancher/harvester-network-controller:v0.3.5
      harvester-network-webhook rancher/harvester-network-webhook:v0.3.5
      ```

1. harvester-node-disk-manager :heavy_check_mark: 
   * Code: `0.5.2`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L391
   * Env.: `0.5.2`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep disk-manager
      harvester-node-disk-manager-rfqks:      rancher/harvester-node-disk-manager:v0.5.2, 
      harvester-node-disk-manager-vn8px:      rancher/harvester-node-disk-manager:v0.5.2, 
      harvester-node-disk-manager-w54kn:      rancher/harvester-node-disk-manager:v0.5.2,
      ```

1. kube-vip :heavy_check_mark: 
   * Code: `0.5.10`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L461
   * Env.: `0.5.10`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep kube-vip:
      kube-vip-b5g42: ghcr.io/kube-vip/kube-vip:v0.5.10, 
      kube-vip-t26hf: ghcr.io/kube-vip/kube-vip:v0.5.10, 
      kube-vip-wb8f4: ghcr.io/kube-vip/kube-vip:v0.5.10, 
      ```

1. kube-vip-cloud-provider :heavy_check_mark: 
   * Code: `0.0.1`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L469 
   * Env.: `0.0.1`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep kube-vip-cloud
      kube-vip-cloud-provider-0:      kubevip/kube-vip-cloud-provider:v0.0.1, 
      ```

1. harvester-load-balancer :heavy_check_mark: 
   * Code: `0.1.6`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L455
   * Env.: `0.1.6`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep balancer
      harvester-load-balancer rancher/harvester-load-balancer:v0.1.6
      ```

1. whereabouts :heavy_check_mark: 
   * Code: `0.6.2-amd64`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L488
   * Env.: `0.6.2-amd64`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep whereabouts
      harvester-whereabouts-jcq57:    ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64, 
      harvester-whereabouts-qzg5h:    ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64, 
      harvester-whereabouts-xls75:    ghcr.io/k8snetworkplumbingwg/whereabouts:v0.6.2-amd64,
      ```

1. harvester-node-manager :heavy_check_mark: 
   * Code: `0.1.8` 
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L494
   * Env.: `0.1.8`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep node-manager
      harvester-node-manager-7kk5c:   rancher/harvester-node-manager:v0.1.8, 
      harvester-node-manager-lbslg:   rancher/harvester-node-manager:v0.1.8, 
      harvester-node-manager-lmb92:   rancher/harvester-node-manager:v0.1.8, 
      ```

1. support-bundle-kit :heavy_check_mark: 
   * Code: `0.0.32`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/deploy/charts/harvester/values.yaml#L475
   * Env.: `0.0.32`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep support
      supportbundle-manager-bundle-kmbxa rancher/support-bundle-kit:v0.0.32
      ```

1. pcidevice (Addon) :heavy_check_mark: 
   * Code: `0.2.6`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/package/upgrade/addons/pcidevices-controller.yaml
   * Env.: `0.2.6`
      ```
      harvester-node-0:~ # kubectl get pods --all-namespaces -o jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{range .spec.containers[*]}{.image}{", "}{end}{end}' | grep harvester-pci
      harvester-pcidevices-controller-8gkz2:  rancher/harvester-pcidevices:v0.2.6, 
      harvester-pcidevices-controller-9vp2p:  rancher/harvester-pcidevices:v0.2.6, 
      harvester-pcidevices-controller-qqbmm:  rancher/harvester-pcidevices:v0.2.6, 
      ```

1. vm-import-controller :heavy_check_mark: 
   * Code: `0.1.6`
     https://github.com/harvester/harvester/blob/v1.1.3-rc1/package/upgrade/addons/vm-import-controller.yaml
   * Env.: `0.1.6`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep vm-import-controller
      harvester-vm-import-controller rancher/harvester-vm-import-controller:v0.1.6
      ```

1. monitoring (Rancher Chart) :heavy_check_mark: 
   * Code: `100.1.0+up19.0.3`
     https://github.com/harvester/harvester-installer/blob/v1.1.3-rc1/scripts/version-monitoring
   * Env.: `100.1.0+up19.0.3`
    ![image](https://github.com/harvester/harvester/assets/2773781/c9cdeff3-8e51-4d2d-97f1-8b2d72d9a550)

1. logging (Rancher Chart) :heavy_check_mark: 
   * Code: `100.1.3+up3.17.7`
   * Env.: `100.1.3+up3.17.7`
    ![image](https://github.com/harvester/harvester/assets/2773781/4efd4750-2a01-4a08-827c-1fee25e5a1a5)


1. Rancher :heavy_check_mark: 
   * Code: `2.6.13`
     https://github.com/harvester/harvester-installer/blob/v1.1.3-rc1/scripts/version-rancher
   * Env.: `2.6.13`
      ```
      harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep rancher:
      rancher rancher/rancher:v2.6.13
      ```

1. OS :heavy_check_mark: 
   * Code: `1.1-20231121`
     https://github.com/harvester/harvester-installer/blob/v1.1.3-rc1/scripts/package-harvester-os#L20
   * Env.: `1.1-20231121`
      ```
      harvester-node-0:~ # cat /etc/*ease
      NAME="SLE Micro"
      VERSION="5.3"
      VERSION_ID="5.3"
      PRETTY_NAME="Harvester v1.1.3-rc1"
      ID="sle-micro-rancher"
      ID_LIKE="suse"
      ANSI_COLOR="0;32"
      CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
      VARIANT="Harvester"
      VARIANT_ID="Harvester-v1.1-20231121"
      GRUB_ENTRY_NAME="Harvester v1.1.3-rc1"
      
      ```

1. Go :heavy_check_mark: 
   * Code: `1.20.10-bookworm`
     * https://github.com/harvester/harvester/blob/v1.1.3-rc1/Dockerfile.dapper#L4
     https://github.com/harvester/harvester/blob/beb8f38c3c2c1c6c182318b2e23beeb5bb04f37b/Dockerfile.dapper#L4
