### ISSUE TITLE
[Question] Create or Join the original creation node

### ISSUE THREAD

**Issue by xeruf** [harvester/harvester#4671]
Once a HA cluster is setup with three management nodes, do the original roles of the nodes, whether they create or join the cluster, still matter? Because I do see significant deviations in the `/oem` config.

Here is why I am asking: Due to an issue I had to reformat the node that was the original cluster creation node. Do I now tell it to join the cluster, making all three nodes agents from perspective of the setup cofiguration?

**Comment by bk201** [comment]
@xeruf what's the state of the two remaining nodes, are they all promoted to control plane nodes?
(ROLE is `control-plane,etcd,master` in `kubectl get nodes`.

Does the cluster still run well and you can connect to the cluster with VIP?

**Comment by xeruf** [comment]
the cluster is running well, the other two are control plane nodes
not thinking too much about it I setup the node as cluster master, and might have screwed up my cluster now
I hope not, trying to demote it back to an agent now and tell the others to stay in control...

**Comment by bk201** [comment]
@xeruf You don't need to demote. By default, Harvester promotes workers into control nodes if the total number of nodes >= 3.

**Comment by xeruf** [comment]
no but I need to tell the newly setup node to join as agent rather than creating a new cluster ^^

**Comment by bk201** [comment]
Say, the node you re-formatted is `<node-name>`, the first thing is you need to remove it from the harvester cluster (do a `kubectl delete node <node-name>`. Please do this very carefully, not to delete nodes you still need.

When everything is fine, re-join the node to the existing cluster with VIP. The node will be promoted to control plane node again.

**Comment by xeruf** [comment]
I think I already screwed it up. I had setup the node as master node, it created a new cluster and the others updated their certificate data following it. Any way to restore them to the previous cluster?

**Comment by xeruf** [comment]
You can see here how not too long ago most of the config files were overwritten, but there is still the old server config, though without any keys...
```sh
rancher@raven:oem  1 $ ls -l /etc/rancher/rke2/
total 12
drw------- 2 root root 4096 Oct 29 17:22 config.yaml.d
-rw------- 1 root root    0 Oct 29 16:37 registries.yaml
-rw------- 1 root root  365 Oct 30 10:36 rke2-pss.yaml
-rw------- 1 root root 2969 Oct 30 10:36 rke2.yaml
rancher@raven:oem :) $ sudo ls -l /etc/rancher/rke2/config.yaml.d/
total 20
-rw-r--r-- 1 root root 102 Oct 29 17:22 40-disable-charts.yaml
-rw------- 1 root root 860 Oct 29 17:22 50-rancher.yaml
-rw------- 1 root root  31 Oct 30 10:02 90-harvester-agent.yaml
-rw-r--r-- 1 root root 207 Oct 29 17:22 90-harvester-server.yaml
-rw------- 1 root root 372 Oct 30 10:02 92-harvester-kube-audit-policy.yaml
```

**Comment by xeruf** [comment]
The nodes that were promoted to management are now stuck in NotReady and get this:
```sh
# kubectl get nodes
The connection to the server 127.0.0.1:6443 was refused - did you specify the right host or port?
```

**Comment by xeruf** [comment]
Will a node joining a cluster with existing data bring that data into the cluster with it?
How can I proceed now in a safe way, what to back up?

**Comment by xeruf** [comment]
@bk201 please return my hero :)

**Comment by xeruf** [comment]
Probably related to https://github.com/rancher/rancher/issues/38640

**Comment by xeruf** [comment]
Unfortunately had to recreate the cluster, good that I was not yet running any nodes in production ^^

**Comment by noahgildersleeve** [comment]
@xeruf What version of Harvester was this running on, and how did you originally install it (from an ISO, or PXE boot etc)?

**Comment by xeruf** [comment]
I think ISO 1.1.2

**Comment by bk201** [comment]
@xeruf Sorry, I didn't notice this until I saw the stale message. Do you still need to investigate this issue? I review the comments again and seems you re-install the first node to create a new cluster. If the new cluster has the same VIP as the initial one, then I guess there will be a problem.
