### ISSUE TITLE
[ENHANCEMENT] GUI: change from Ntp server to NTP servers in settings

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4673]
**Is your enhancement related to a problem? Please describe.**

![harvester-ntp-settings-multiple-c63a4bd21618d58889aade68d25749c8](https://github.com/harvester/harvester/assets/1691518/f4ed0b4f-f08c-4fbb-86a3-7e8b757a8e83)

Lower case "Ntp" server is displayed.

**Describe the solution you'd like**

We use the upper case "NTP" server conventionally, need to change from Ntp to NTP on the settings page.

**Describe alternatives you've considered**

**Additional context**

**Comment by simonflood** [comment]
Whilst changing "Ntp" to "NTP" you should also change "Ntp/NTP Servers Addresses" (the second red circle) to "NTP Server Addresses" (i.e. singular Server but with plural Addresses) as it is better grammar.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc3`, close as fixed.

![image](https://github.com/harvester/harvester/assets/2773781/6facd8c3-9fa8-406b-9e8a-7051131e9f2c)
