### ISSUE TITLE
[BUG] Do not activate the LVM device on the harvester node

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4674]
**Describe the bug**
Some Linux distributions like Ubuntu will create a root filesystem with LVM.
Once these PVCs are attached to the harvester node, we have a chance to activate them.

Then, if we activate the LVM device, we will see the DM IO Error when the related VM migration.

Related issue: https://github.com/harvester/harvester/issues/3843

**To Reproduce**
Please refer to this comment
https://github.com/harvester/harvester/issues/3843#issuecomment-1535689155

**Expected behavior**
Do not see the LVM device and any IO Error when VM migrate

**Support bundle**
None

**Environment**
 - Harvester ISO version: v1.2.0 rc version
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM-based harvester node

**Additional context**
We also have some solutions to the above issue.
The main concept is avoid to activating the LVM device on the host.

**Comment by w13915984028** [comment]
The #4674 is a good enhancement, should be also mentioned in #3261

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc1`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-rc1`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. Create VM with LVM
   * <details>
     <summary> Currently VM is on <b>harvester-node-1</b>
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/6d9516ae-0839-47df-9b56-9c5bcfbefd6b)
     </details>

2. Migrate VM to **node-0** and
   * <details>
     <summary> VM's LVM Will NOT mount by <b>node-0</b> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/bcb5bd55-0d20-4889-af09-436e1f4b7918)
     </details>

   * <details>
     <summary> No <code>I/O error on dev dm-</code> in kernel log :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2b34e1f2-b546-477f-811d-e0f3119a96b1)
     </details>

2. Migrate VM back to **node-1** and
   * <details>
     <summary> VM's LVM Will NOT mount by <b>node-1</b> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/70200004-3a95-4343-97f4-8d944f85ce14) 
     </details>

   * <details>
     <summary> No <code>I/O error on dev dm-</code> in kernel log :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/939b7ac8-dcaa-424e-97e2-57244c953d8a)
     </details>
   

## Note
Can reproduce in `v1.2.1`
  1. <details>
     <summary> Create a VM with LVM
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/05c2a08d-3904-4099-8e09-6f1b125d977f)
     </details>
   
  2. <details>
     <summary> Migrate to <b>node-0</b> and it mounts VM's LVM
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/d2f5b0c3-8311-467e-bbb3-9a2cfdf4160e)
     </details>
   
  3. <details>
     <summary> Migrate back to <b>node-1</b> and it mounts VM's LVM
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/e7083231-1fcb-42d2-a499-c7cff9569d75)
     </details>

  4. <details>
     <summary> Has <code>I/O error on dev dm-</code>
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/d9ae1148-ae66-48cc-8c75-4b78023666d8)
     </details>
