### ISSUE TITLE
[FEATURE] PXE POST-INSTALLATION

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#469]
**Is your feature request related to a problem? Please describe.**

Is it possible to have the option of adding commands to run on the system once the installation is complete, it will help to have it with https://github.com/rancher/harvester-installer/pull/33 in my use case this will be a callback to the provisioner so I can remove the iPXE script as all my bare-metal configure to look for network boot first and without removing the iPXE script the machine will keep the loop in the installation stage.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

This is migrated from https://github.com/rancher/harvester-installer/issues/37

**Comment by bk201** [comment]
Some initial thoughts after discussion:

The idea is to add a webhook. And users can specify an URL in the configuration file.
Once the installation is done (or failed), an event will be posted to the URL.

Any other takes @guangbochen ? Thanks.

**Comment by gitlawr** [comment]
@4msamir It would be appreciated to have your input as well since you are the author of the original issue

**Comment by 4msamir** [comment]
The webhooks solution is great fix to hook post/pre actions

**Comment by kingsd041** [comment]
Validated on v0.2.0-rc1
Verify the test case:
- During the ipxe installation of harvester, different events (`SUCCEEDED`, `STARTED`, `FAILED`) will be sent according to the set URL
- Verified `GET` and `POST` methods
- Verify that events are sent via `insecure` and `basicAuth`
- Verify can send events to the http server through `insecure` and `basicAuth`
