### ISSUE TITLE
[Question] sheduled and incremental backups using longhorn directly?

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4690]
Is there a way to shedule and create incremental backups using longhorn directly?

**Comment by WebberHuang1118** [comment]
We plan to provide recurring VM backup on Harvester v1.3.0

**Comment by ne0YT** [comment]
@WebberHuang1118 will it be incremental too?

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 will it be incremental too?

yes, Longhorn backup is incremental by design https://longhorn.io/docs/1.4.3/concepts/#3-backups-and-secondary-storage

**Comment by ne0YT** [comment]
> > @WebberHuang1118 will it be incremental too?
> 
> yes, Longhorn backup is incremental by design https://longhorn.io/docs/1.4.3/concepts/#3-backups-and-secondary-storage

but currently backups are not

**Comment by WebberHuang1118** [comment]
It should be incremental for the one particular volume, I'll double-check it.
