### ISSUE TITLE
[Question] Running virtualized ESXi 8 on Harvester

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4691]
I want to run a virtualized ESXi 8 on Harvester.
I am able to install it but it's impossible to upload a .ova or .ovf VM exported from another ESXi.
Ethernet Adapter is set to e1000e all others will not wok
Volumes are 
1x 32GB SATA for install
1x 50GB SATA for Datastore
Booting in EFI mode.

**Comment by ne0YT** [comment]
stay open

**Comment by starbops** [comment]
Hi @ne0YT could help confirm the feature request described in #4742 is what you need?
