### ISSUE TITLE
[Question] how to check current restore process if there is no VM created from it

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4693]
I started a restore process of a VM from a a backup on an S3 storage.
smh it didn't create a VM. 
I know it is running as when I try to recreate the S3 connection (nothing changed, just for troubleshooting) it tells me it's not possible to change as there is somehting runnign rn.

**Comment by WebberHuang1118** [comment]
We plan to implement detailed progress for VM backup on Harvester v1.3.0 https://github.com/harvester/harvester/issues/4102.

For VM restore, there isn't any progress for volume restore from Longhorn, however, I think maybe we could provide the VM restore current phase (i.e. volume creating/restoring, VM creating ... and so on)
