### ISSUE TITLE
[BUG] Using arrows to add CPU/Memory in the interface is not taking into account at VM creation

### ISSUE THREAD

**Issue by bloriot** [harvester/harvester#4702]
**Describe the bug**
When creating a Virtual Machine, if we use the little arrows to choose CPU/Memory and not enter it via keyboard it is displayed in the fields but not taken into account when clicking Create.

**To Reproduce**
1. Go to 'Virtual Machines'
2. Click 'Create' to create a new VM
3. Use arrows to add 1 CPU and 1 GiB of Memory
4. Click 'Create' button

**Expected behavior**
Adding CPU/Memory via arrows or keyboard in the interface should work.

**Environment**
 - Harvester ISO version: v1.1.2 and v1.2.0

**Comment by jrlittlefoot64** [comment]
If you use firefox, try chrome

**Comment by bloriot** [comment]
> If you use firefox, try chrome

Indeed it works with Chrome

**Comment by jrlittlefoot64** [comment]
@bk201 think it's duplicate with #4179

**Comment by bk201** [comment]
@jrlittlefoot64 Thanks, I'll close this one.
