### ISSUE TITLE
[ENHANCEMENT] Bump cloud-provider-harvester v0.2.3 to Rancher charts

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4703]
**Is your enhancement related to a problem? Please describe.**

~Harvester chart cloud-provider-harvester v0.2.2 (https://github.com/harvester/charts/releases/tag/harvester-cloud-provider-0.2.2) is released some days,but it is not bumped to Rancher charts~

Note: to solve a known issue in kube-vip deployment tolerances (https://github.com/harvester/harvester/issues/4678.), the cloud-provider-harvester has been updated to v0.2.3, there for we also update the bump with latest version v0.2.3:

Harvester chart cloud-provider-harvester v0.2.3 (https://github.com/harvester/charts/releases/tag/harvester-cloud-provider-0.2.3) is released some days,but it is not bumped to Rancher charts

https://github.com/rancher/charts/tree/dev-v2.8/charts/harvester-cloud-provider
https://github.com/rancher/charts/tree/release-v2.7/charts/harvester-cloud-provider

RKE2 charts: also will be bumped: https://github.com/rancher/rke2-charts/pull/394

**Describe the solution you'd like**

bump to Rancher charts

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
@w13915984028 please add milestone, thanks.

**Comment by khushboo-rancher** [comment]
@w13915984028 Tested on Harvester Master-head with Rancher 2.8-head. I see the cloud-provider v0.2.3 is available in Rancher v2.8 but by default I v0.2.2 is install when I create an 1.28 rke2 guest cluster. Is this expected?

<img width="1183" alt="Screenshot 2024-03-08 at 2 04 17 PM" src="https://github.com/harvester/harvester/assets/60111667/f804a9bf-0410-4e28-852b-a549871bb43a">

**Comment by w13915984028** [comment]
@khushboo-rancher I am taking a look.
cc @FrankYang0529

**Comment by khushboo-rancher** [comment]
As confirmed by @bk201, the default version of cloud provider will be v0.2.2 when deploy an rke2 guest cluster, closing the issue.
