### ISSUE TITLE
[BUG] Terraform destroy does not remove cluster network that has a vlanconfig

### ISSUE THREAD

**Issue by sirris-bat** [harvester/harvester#4704]
**Describe the bug**
When running `terraform destroy` command to tear down infrastructure, if you have configured and deployed a `harvester_clusternetwork` resource, and added a `harvester_vlanconfig` to that clusternetwork, terraform will fail to destroy the clusternetwork with the following message:
`Error: admission webhook "validator.harvester-system.harvester-network-webhook" denied the request: Internal error occurred: could not delete cluster network storage because vlanconfig(s) [storage-vlan-dragapult] under this clusternetwork is/are still exist(s)`
The cluster network will still be present, but the network config is gone. Both should be removed entirely.

**To Reproduce**
1. Configure terraform with the following resources:
```
resource "harvester_clusternetwork" "storage_clusternetwork" {
  name        = "storage"
}

resource "harvester_vlanconfig" "storage_network_vlanconfig" {
  cluster_network_name  = "storage"
  name                  = "storage-vlan-dragapult"

  uplink { 
    nics      = [
      "eth5",
      "eth6"
    ]

    bond_mode = "802.3ad"
    mtu       = 1500
  }

  node_selector         = { "kubernetes.io/hostname" = "dragapult" }
}
```
2. Run terraform plan and apply
3. Run terraform destroy and observe error
4. Check and see that the cluster network still exists, albeit without the vlanconfig

**Expected behavior**
The `harvester_vlanconfig` should be removed before attempting to remove the cluster network, and the cluster network should also be removed.

**Environment**
 - Harvester ISO version: 1.2.1
 - Terraform provider version: 0.6.3

**Comment by Martin-Weiss** [comment]
Just guessing - but could it be that this terraform script requires a dependency to delete the child before the parent?

**Comment by sirris-bat** [comment]
> Just guessing - but could it be that this terraform script requires a dependency to delete the child before the parent?

Thanks, that sorted it out. I'll close the issue.
