### ISSUE TITLE
[Question] how / when does the HA work?

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4706]
I rebooted one of my three hosts. and all his VMs went down.. for about five minutes when he was back again. while he was down harvester didn't migrate them to other hosts even though there are enough ressources. but after he was back they were running on another host. is there a way to speed this process up?

**Comment by connorkuehl** [comment]
5 minutes is the default value for `vm-force-reset-policy`[1]. If you adjust that setting to a smaller value and repeat the experiment, do the VMs spin up on available nodes quicker?

[1] https://docs.harvesterhci.io/v1.2/advanced/index#vm-force-reset-policy

**Comment by ne0YT** [comment]
@connorkuehl it works :)
