### ISSUE TITLE
[Doc] Document use of CloudInit CRD (kubectl-centric)

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4708]
**Is your doc request related to a problem? Please describe or add related issue ID.** https://github.com/harvester/harvester/issues/3902

**Describe the solution you'd like**

Perhaps as sub-headings under the "Host Management" page.

* Creating CloudInit objects via ~~the Harvester dashboard (GitHub issue TBD) and via~~ kubectl
* Using the CloudInit match selector to customize which nodes receive the CloudInit
* Expected behavior for updating match selectors which causes nodes to no longer match
* Expected behavior for deleting CloudInit objects

**Comment by irishgordo** [comment]
There's a possibility that it would be worthwhile to highlight to the User/Operator/Admin/Org that plans to use the CloudInit CRD functionality things like:
- the importance for the user/admin/operator/org to understand how Elemental Toolkit / Elemental Cloud-Init Executor works, as in - understanding how Elemental Toolkit Cloud-Init Executor will parse the data you feed into the creation of your Harvester CloudInit CRD
- how to "map" Harvester configuration (install configuration) properties to their appropriate:
    - Elemental Toolkit Stage
    - Elemental Toolkit's properties / objects / lists / items, etc.
    
As "if" the user/admin/operator/org do not understand those things prior to utilizing the Harvester CloudInit CRD, it may cause some adverse effects to their cluster.

**Comment by markhillgit** [comment]
@connorkuehl please work with @jillian-maroket on this
