### ISSUE TITLE
[BUG]Volume prompt "Replica scheduling failed" after created vm

### ISSUE THREAD

**Issue by charnet1019** [harvester/harvester#4716]
**Describe the bug**
Volume prompt "Replica scheduling failed" after created vm

**Expected behavior**
Ready

![image](https://github.com/harvester/harvester/assets/18616254/4ded0ad1-1610-4219-acad-536cd08aab49)

**Environment**
 - Harvester ISO version:  1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): R740

**Comment by ianb-mp** [comment]
I'm seeing the same error message for *running* VMs. Stopped VMs do not have this error. Running VMs appear to be functioning normally.

Installed from ISO v1.2.1 to bare metal on a single node cluster.
Using default `harvester-longhorn` for VM storage class.

**Comment by charnet1019** [comment]
Longhorn storage defaults to 3 replicas, but volumes created in a standalone environment also default to 3 replicas, resulting in multiple replica scheduling failures. Currently, by modifying the corresponding volume to 1 replica in the Longhorn management interface, normal operations have been restored


The underlying longhorn storage class defaults to 3 replicas, and newly created volumes also have 3 replicas. Will this lead to excessive data redundancy, reduced available storage space, and also affect storage performance.
