### ISSUE TITLE
[BUG] IO errors from fstrim cause a VM pause/unpause loop

### ISSUE THREAD

**Issue by ejweber** [harvester/harvester#4739]
**Describe the bug**

Currently, if a VM issues an UNMAP operation to a Longhorn volume (during an `fstrim` or if the volume is mounted with `discard`) while it is replicating, an IO error is returned. Longhorn is tracking this behavior in https://github.com/longhorn/longhorn/issues/7103 and looking for ways to improve it. This error is generally not harmful, and most workloads can essentially ignore it and continue. However, Harvester appears to repeatedly pause the VM, unpause the VM, and retry the IO when it occurs. Is there something that can be done in Harvester to avoid responding in this manner?

**To Reproduce**

Follow essentially the same steps as in https://github.com/longhorn/longhorn/issues/7103#issue-1993659460, except mount the volume to a Harvester VM instead of an arbitrary workload pod. In that reproduce, no "bad behavior" is observed other than kernel IO errors. However, in the Harvester case, the VM gets trapped in a pause/unpause loop until replication is finished.

**Expected behavior**

The kernel logs an IO error, but the VM continues operating.

**Support bundle**

There is a support bundle in SUSE internal Jira SURE-6935 demonstrating this happening in a production environment.

**Environment**

```
NAME="SLE Micro"
VERSION="5.3"
VERSION_ID="5.3"
PRETTY_NAME="Harvester v1.2.0"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.3"
VARIANT="Harvester"
VARIANT_ID="Harvester-v1.2-20230907"
GRUB_ENTRY_NAME="Harvester v1.2.0"
```

Embedded Longhorn `v1.4.3`.

**Comment by connorkuehl** [comment]
If the error from Longhorn is distinct from ENOSPC we may be able to set the disk error policy[1] to `enospace`.

[1] https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#error-policy

**Comment by ejweber** [comment]
Cool! That might be an option in the future. I tried playing with it to see if it would "just work", but unfortunately, that field was just added in KubeVirt v1.1.0, which we don't have in any Harvester versions yet.

**Comment by WebberHuang1118** [comment]
As I know, fstrim errors could bring potential data corruption for upcoming I/Os especially when there are massive concurrent I/Os, although the errors may not always happen or be observed immediately. The affection depends on the root cause of Longhorn fstrim error, but this possibly can let the filesystem and block layer have different cognition toward storage.

> If the error from Longhorn is distinct from ENOSPC we may be able to set the disk error policy[1] to `enospace`.
> 
> [1] https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#error-policy

I'm afraid it would make Harvester can not tell the fstrim errors from other I/O errors, and it has the chance to introduce severe data inconsistency between memory and storage for VMs ?

IMHO, before https://github.com/longhorn/longhorn/issues/7103 is addressed, if LH could report volume has fstrm error (e.q. via annotation or something), Harvester should stop the VM accordingly and suggest user have filesystem scan like https://harvesterhci.io/kb/scan-and-repair-vm-root-filesystem

WDYT? @Vicente-Cheng @FrankYang0529

Thanks

**Comment by bk201** [comment]
@Vicente-Cheng Before https://github.com/longhorn/longhorn/issues/7103 is addressed, please help add a document or KB to include recommendation from @ejweber:
- Do not mount Longhorn volumes into VMs with the discard option. If the VM base image automatically mounts its root file system with the discard option, modify its /etc/fstab so that it no longer does.
- Be aware that many VM OS distributions automatically schedule fstrim operations for once per week. If this scheduled fstrim occurs during a replica rebuild, the described behavior can occur. In many situations, the benefits (disk space usage reduction) outweigh the drawbacks (potential VM pausing in poor timing situations). However, automatic fstrim can be disabled within VMs if desired.

**Comment by Vicente-Cheng** [comment]
How to reproduce on the VM workload:
1. create VM and attach 5G volume vol001
2. make the ext4 filesystem with vol001 and try to write file on it
```
command: fio --name=test --ioengine=libaio --filename=./test/file1 --size=3G --rw=randwrite --bs=128k --direct=1 --numjobs=4 --group_reporting
```
3. manually delete the vol001 replica and do the fstrim in the meantime
4. we could see the VM temporarily hang (will resume running)

Checked the host logs:
```
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#96 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#96 Sense Key : Hardware Error [current]
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#96 Add. Sense: Internal target failure
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#96 CDB: Unmap/Read sub-channel 42 00 00 00 00 00 00 00 18 00
[Thu Jan 11 08:05:30 2024] blk_update_request: critical target error, dev sdb, sector 270360 op 0x3:(DISCARD) flags 0x800 phys_seg 1 prio class 0
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#97 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#97 Sense Key : Hardware Error [current]
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#97 Add. Sense: Internal target failure
[Thu Jan 11 08:05:30 2024] sd 3:0:0:1: [sdb] tag#97 CDB: Unmap/Read sub-channel 42 00 00 00 00 00 00 00 18 00
[Thu Jan 11 08:05:30 2024] blk_update_request: critical target error, dev sdb, sector 270360 op 0x3:(DISCARD) flags 0x800 phys_seg 1 prio class 0
[Thu Jan 11 08:05:40 2024] sd 3:0:0:1: [sdb] tag#85 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
[Thu Jan 11 08:05:40 2024] sd 3:0:0:1: [sdb] tag#85 Sense Key : Hardware Error [current]
[Thu Jan 11 08:05:40 2024] sd 3:0:0:1: [sdb] tag#85 Add. Sense: Internal target failure
[Thu Jan 11 08:05:40 2024] sd 3:0:0:1: [sdb] tag#85 CDB: Unmap/Read sub-channel 42 00 00 00 00 00 00 00 18 00
[Thu Jan 11 08:05:40 2024] blk_update_request: critical target error, dev sdb, sector 270360 op 0x3:(DISCARD) flags 0x800 phys_seg 1 prio class 0
```

Checked the instance-manager logs:
```
response_process: Receive error for response 3 of seq 181040
tgtd: bs_longhorn_request(183) Failed to punch hole for UNMAP at offset:138424320 length:12288
tgtd: bs_longhorn_request(210) io error 0x1763680 42 0 16 0, Success
response_process: Receive error for response 3 of seq 181041
tgtd: bs_longhorn_request(183) Failed to punch hole for UNMAP at offset:138424320 length:12288
tgtd: bs_longhorn_request(210) io error 0x1763680 42 0 16 0, Success
response_process: Receive error for response 3 of seq 181042
tgtd: bs_longhorn_request(183) Failed to punch hole for UNMAP at offset:138424320 length:12288
tgtd: bs_longhorn_request(210) io error 0x1763680 42 0 16 0, Success
```

Also, see the IOError event like following:
```
kind: Event
lastTimestamp: "2024-01-11T08:05:41Z"
message: 'VM Paused due to IO error at the volume: vol001'
metadata:
  creationTimestamp: "2024-01-11T08:05:31Z"
  name: vm001.17a93c634eba2b23
  namespace: default
  resourceVersion: "74216"
  uid: 5e5fc62a-65ab-41e0-9236-7e97e27a19a9
reason: IOerror
```

VM temporarily changes its state to pause due to IOError, but the Kubevirt will try to resume running.
Kubevirt has its mechanism to make the instance resume running. If the volume encounters no error, the instance will return to running as we want.
This volume works well after the replica is rebuilt for the above case. So the Kubevirt mechanism will help it get back to running.

We need to worry that the client application will temporarily fail if they want to do any IO on this filesystem at this time. (If the client application has the related error handling, it should not affected)

**Comment by RegisWeduLabs** [comment]
Hi,
Yes, I would of love to know this before upgrading harvester from 1.1.3 to 1.2.1.  this happened to us and was a very stressful upgrade...  When the 4th node finished upgrading, replicas started on a lot of our volumes, ALL vms would go paused/unpaused for hours, and it caused so many issues on all our K8s clusters , as all images had the discard option on prior to the upgrade (without issues).  I ended up changing the cloud-config and recreate all the nodes in rancher to add the nodiscard option in fstrim. I added this to the runcmd part of the cloud-config:

  - sed -i 's/discard/nodiscard/' /etc/fstab
  - mount -o remount /

There is a weekly fsctim schedule, and it runs quickly - so chances to have a replica rebuild at the same time as the fstrim is quite slim, but still a risk - so I suggest if you keep the scheduled trim, have different schedules for different vms, so if a node crash at the same time as the fstrim runs, it will only affect a few vms - not all of them.

**Comment by w13915984028** [comment]
link to #3261

**Comment by Vicente-Cheng** [comment]
Hi @ejweber, would you like to take a look at this PR? https://github.com/harvester/harvesterhci.io/pull/54

This is a KB for the fstrim topic.

**Comment by Vicente-Cheng** [comment]
> Hi, Yes, I would of love to know this before upgrading harvester from 1.1.3 to 1.2.1. this happened to us and was a very stressful upgrade... When the 4th node finished upgrading, replicas started on a lot of our volumes, ALL vms would go paused/unpaused for hours, and it caused so many issues on all our K8s clusters , as all images had the discard option on prior to the upgrade (without issues). I ended up changing the cloud-config and recreate all the nodes in rancher to add the nodiscard option in fstrim. I added this to the runcmd part of the cloud-config:
> 
> * sed -i 's/discard/nodiscard/' /etc/fstab
> * mount -o remount /
> 
> There is a weekly fsctim schedule, and it runs quickly - so chances to have a replica rebuild at the same time as the fstrim is quite slim, but still a risk - so I suggest if you keep the scheduled trim, have different schedules for different vms, so if a node crash at the same time as the fstrim runs, it will only affect a few vms - not all of them.

Hi @RegisHubelia, thanks for the reminder.
The case you mentioned is a pain point.

We write a KB for this issue. (The link is on the above comment)
BTW, seems the mount option does not have nodiscard but discard.

Update: with a reminder from https://github.com/longhorn/longhorn/issues/7103#issuecomment-1816651169, we need to take care of the `discard` option on fstab.
But maybe simply removing this option is enough.

So the discard on the OS depends on the `fstrim.timer`.

We can directly disable this timer on the OS side to prevent the `fstrim`.
Also, we can refer to your suggestions by editing the `fstrim.timer` to avoid executing `fstrim` at the same time.

Thanks for your suggestions!

**Comment by ejweber** [comment]
We are testing a fix for the underlying Longhorn issue: https://github.com/longhorn/longhorn/issues/7103. It should allow us to simply NOT respond with an error if an fstrim is issued during a rebuild. I intend to backport it to v1.6.1 and v1.5.x (maybe v1.5.4, but probably v1.5.5 since v1.5.4-RC1 is already out).

**Comment by gregkonush** [comment]
getting `VM Paused due to IO error at the volume: root`, how to disable fstrim? or how do I mount root volume without `discard` option?

**Comment by Vicente-Cheng** [comment]
> getting `VM Paused due to IO error at the volume: root`, how to disable fstrim? or how do I mount root volume without `discard` option?

Hi @gregkonush, could you check on this KB? https://harvesterhci.io/kb/the_potential_risk_with_filesystem_trim

It should have information, including instructions on how to check and disable it.

If you have any issues after this KB, please ask here again. Thanks!

**Comment by gregkonush** [comment]
I did disable it via cloud-init [here](https://github.com/gregkonush/lab/blob/b7158efe7bb132ceafc86bc617086c9cbaaf5913/terraform/harvester/main.tf#L191-L192) but still getting error and VM is paused afterwards

Here is output of VM machine
```
systemctl status fstrim.timer
× fstrim.timer
     Loaded: masked (Reason: Unit fstrim.timer is masked.)
     Active: failed (Result: resources)
    Trigger: n/a

Sep 23 00:27:44 kube-master-00 systemd[1]: Started Discard unused blocks once a week.
Sep 23 00:27:47 kube-master-00 systemd[1]: fstrim.timer: Unit to trigger vanished.
Sep 23 00:27:47 kube-master-00 systemd[1]: fstrim.timer: Failed with result 'resources'.
```

**Comment by Vicente-Cheng** [comment]
> Sep 23 00:27:44 kube-master-00 systemd[1]: Started Discard unused blocks once a week.
> Sep 23 00:27:47 kube-master-00 systemd[1]: fstrim.timer: Unit to trigger vanished.
> Sep 23 00:27:47 kube-master-00 systemd[1]: fstrim.timer: Failed with result 'resources'.

Hi @gregkonush,
It looks like it still runs Discard at `Sep 23 00:27:44`.

Could you confirm that again?
Or would you like to generate the SupportBundle (REF: https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle) for investigation?

Thanks!

**Comment by gregkonush** [comment]
hey @Vicente-Cheng thanks for you help and pointing this out! It works for me now. What I did is I masked both systemd units: `fstrim.timer` and `fstrim.service` 

https://github.com/gregkonush/lab/blob/cda0c05f166d1dd82b0783d75339ad73becfbf4e/terraform/harvester/main.tf#L200-L203

**Comment by gregkonush** [comment]
I am actually still getting crashes even though fstrim properly masked and never ran. Here is the support bundle. Thanks @Vicente-Cheng 

[supportbundle_f9e98723-3048-4efb-83a1-a424550c6ed0_2024-10-11T19-14-28Z.zip](https://github.com/user-attachments/files/17346669/supportbundle_f9e98723-3048-4efb-83a1-a424550c6ed0_2024-10-11T19-14-28Z.zip)

**Comment by Vicente-Cheng** [comment]
> I am actually still getting crashes even though fstrim properly masked and never ran. Here is the support bundle. Thanks @Vicente-Cheng
> 
> [supportbundle_f9e98723-3048-4efb-83a1-a424550c6ed0_2024-10-11T19-14-28Z.zip](https://github.com/user-attachments/files/17346669/supportbundle_f9e98723-3048-4efb-83a1-a424550c6ed0_2024-10-11T19-14-28Z.zip)

Hi @gregkonush, sorry for the late reply.
I will check the support bundle tomorrow and update here again.

Thanks for your patience.

**Comment by brandboat** [comment]
Test ok, will close the issue.

# Environment
- 3 nodes (8C/16G/250GB)
- v1.4.0-rc4

# Test Plan
Following the test plan outlined in https://github.com/harvester/harvester/issues/4739#issuecomment-1888262376, I observed no related errors in either the journalctl logs or the longhorn-instance-manager logs, and no IOError events were found.
