### ISSUE TITLE
[Question]  Enhancing Window RDS performance by modifying yaml config

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4741]
somehow performance of my widnows RDS is pretty bas as soon as there are more than 15 users on it.
I have 64 cpus and 128GB or RAM configured it is not used to crazy (about CPU @25% & 20% RAM usage).

I have 10gbit/s interfaces everywhere (2x per host) so it should not be a network thing too (also inside the VM 1*10gbit/s virtio)

maybe it makes sens eto giev the VM more cpu cache or something?

**Comment by starbops** [comment]
It's hard to say. Since the CPU and memory utilization are both moderate, maybe it's related to disk I/O?
