### ISSUE TITLE
[ENHANCEMENT] add libnvme, nvme-cli to harvester OS

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4745]
**Is your enhancement related to a problem? Please describe.**
To support NVME over TCP, we need `libnvme` and `nvme-cli` packages.

**Describe the solution you'd like**
- Install `libnvme` and `nvme-cli` by default
~- And `uuid-devel` (a requirement for Longhorn v2 engine).~

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by ibrokethecloud** [comment]
I used these repos for a custom build: https://github.com/ibrokethecloud/harvester-installer/blob/longhorn-v1.5.1/package/harvester-os/Dockerfile#L11-L14

May be we should look for sle micro based repos.

**Comment by jeff-radick-suse** [comment]
Changes are being tested in the OBS build Dockerfile for the baseos; it does not appear that a change is required in the github repository.

**Comment by jeff-radick-suse** [comment]
Also, the description mentions "libnvme".  The zypper package named "libnvme" is a source code package and it seems unlikely that the source code is what is required.  Installing the "nvme-cli" package will automatically bring in the runtime library  /usr/lib64/libnvme.so etc

**Comment by jeff-radick-suse** [comment]
uuid-devel is not in the available set of package repositories in the current way things build in OBS.  We'll have to figure out how to solve this.

**Comment by asettle** [comment]
@Vicente-Cheng could you clarify why the uuid-devel package is required for the Longhorn v2 engine?

**Comment by ibrokethecloud** [comment]
This was mentioned as requirement in the docs: 
https://longhorn.io/docs/1.5.0/spdk/quick-start/#install-nvme-userspace-tool-and-load-nvme-tcp-kernel-module

**Comment by Vicente-Cheng** [comment]
I think we can remove this after longhorn v1.5.2. It builds in on the instance-manager pod.
Related issue: https://github.com/longhorn/longhorn/issues/6798

**Comment by innobead** [comment]
It should be used for built time. If could, let's don't add this to the host.

**Comment by jeff-radick-suse** [comment]
I'm going to separate the uuid-devel package from this issue.

**Comment by jeff-radick-suse** [comment]
I believe this is now completed for 1.3.0

**Comment by jeff-radick-suse** [comment]
Closed prematurely, need to follow workflow

**Comment by Vicente-Cheng** [comment]
Close it because we can verify the whole package things together.
Ref: https://github.com/harvester/harvester/issues/4595#issuecomment-1899560946
