### ISSUE TITLE
[Question] Harvester iPXE automated installation add multiple datadisks

### ISSUE THREAD

**Issue by wi11-i-am** [harvester/harvester#4746]
For the create and join automated yaml files when doing an iPXE boot, is there a way to add multiple storage devices?

Example for Join/Create yaml
  device: /dev/nvme0n1
  datadisk: /dev/nvme1n1

If I also had datadisk /dev/nvme2n1 how could I also have that one added on installation as well?

**Comment by starbops** [comment]
It seems not possible at the time being. You'll need to [add additional data disks through the dashboard](https://docs.harvesterhci.io/v1.2/host/#add-additional-disks) after the installation is completed.

If you have hardware RAID on your machine, maybe pre-configuring the physical disks to form one logical disk could be a way to solve your question.

**Comment by bk201** [comment]
Can you see if the setting [`auto-disk-provision-paths` ](https://docs.harvesterhci.io/v1.2/advanced/index#auto-disk-provision-paths-experimental)works? 
It can be set during the installation (check the last time in the [example](https://docs.harvesterhci.io/v1.2/install/harvester-configuration#configuration-example)) or in the GUI on day 2.
