### ISSUE TITLE
[BUG] The MTU value does not propagate to all the interfaces if MTU is configured after the VlanConfig creation

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4752]
**Describe the bug**

When user changes the MTU value of the **Network Config** which contains the VM/storage networks, the MTU value does not get propagated to the referencing NetworkAttachmentDefinition objects.

![image](https://github.com/harvester/harvester/assets/1827717/902f25cc-cae0-40cf-8719-4bb08a383eab)

![image](https://github.com/harvester/harvester/assets/1827717/6b2a96ab-910c-4f7d-8370-ec0c4298d0bb)

```
kubectl get vlanconfigs enp3s0 -o yaml                                                                             
apiVersion: network.harvesterhci.io/v1beta1
kind: VlanConfig
metadata:
  annotations:
    network.harvesterhci.io/matched-nodes: '["harvester-vj7bs","harvester-pcwqz"]'
  creationTimestamp: "2023-11-22T05:49:57Z"
  finalizers:
  - wrangler.cattle.io/harvester-network-vlanconfig-controller
  generation: 2
  labels:
    network.harvesterhci.io/clusternetwork: storage
  name: enp3s0
  resourceVersion: "2155071"
  uid: 3b06d464-485b-4b27-aa79-c8efe3dd05c4
spec:
  clusterNetwork: storage
  uplink:
    bondOptions:
      miimon: -1
      mode: active-backup
    linkAttributes:
      mtu: 9000
      txQLen: -1
    nics:
    - enp3s0
```

```
kubectl -n harvester-system get net-attach-def storagenetwork-pd7dc -o yaml  
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    storage-network.settings.harvesterhci.io: "true"
  creationTimestamp: "2023-11-22T05:50:21Z"
  finalizers:
  - wrangler.cattle.io/harvester-network-nad-controller
  - wrangler.cattle.io/harvester-network-manager-nad-controller
  generateName: storagenetwork-
  generation: 1
  labels:
    network.harvesterhci.io/clusternetwork: storage
    network.harvesterhci.io/ready: "true"
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: "1"
  name: storagenetwork-pd7dc
  namespace: harvester-system
  resourceVersion: "2150992"
  uid: c78f8cf3-f84a-42f3-98ce-45ee81bc4ee3
spec:
  config: '{"cniVersion":"0.3.1","type":"bridge","dns":{},"bridge":"storage-br","promiscMode":true,"vlan":1,"ipam":{"type":"whereabouts","range":"10.172.0.0/16"}}'
```

Hence the interfaces' MTU are still configured with the original value.

```
rancher@harvester-pcwqz:~> ip link | grep storage
4: enp3s0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 9000 qdisc pfifo_fast master storage-bo state UP mode DEFAULT group default qlen 1000
152: storage-br: <BROADCAST,MULTICAST,PROMISC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
154: veth0cf4ff4c@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master storage-br state UP mode DEFAULT group default 
157: vethfe8ae8fd@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master storage-br state UP mode DEFAULT group default 
158: veth70d130a2@if4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue master storage-br state UP mode DEFAULT group default 
159: storage-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 9000 qdisc noqueue master storage-br state UP mode DEFAULT group default qlen 1000
```

**To Reproduce**
1. Create a new Cluster Network
2. Create a new Network Config under the created Cluster Network. Leave the MTU field empty.
3. Set up storage network with the created Cluster Network
4. After LH-related Pods settled, change the MTU field with a value, e.g., 9000, in the Network Config
5. Log in to the Harvester node and check the network interfaces' MTU value. They remain at the original default value of 1500.

**Expected behavior**

After applying the MTU value, all the workload that running with the VlanConfig should have the network interfaces with correct value set.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

The workaround is to manually patch the NetworkAttachmentDefinition with `"mtu": <value>` and restart all the workload that associates with the network. After that, the network interfaces will reflect the new value.

---

Restarting all the workload associated with the network merely due to a slight change seems a little scary. We should add a warning about the consequences of such action, if we're going to fix this.

**Comment by mauriiciodias** [comment]
@starbops What is the impact of this bug? Can the MTU with the default value of 1500 cause any type of performance drop in the VLAN? I ask this because I have a 50Gbps lacp and my virtual machines only reach 2Gbps.

**Comment by starbops** [comment]
Hi @mauriiciodias! Yes, it could be one of the reasons. With the same amount of data to transfer, there will be more packets to transmit, given a lower MTU value, hence increasing the overhead. I'd suggest to troubleshoot one at a time. Did you try the workaround to increase the MTU value and see if the problem still exists?

Besides that, there are several other places worth checking to locate the bandwidth bottleneck:

- Check if the VMs are attached to the correct VM Network that has the 50 Gbps uplink from the Harvester dashboard
- Check the NIC model of the VMs from the Harvester dashboard
- Check the NIC's negotiated speed from within the VMs' OS

Thank you.

**Comment by mauriiciodias** [comment]
@starbops 
The machines are connected to the VLAN, whose capacity is 50Gbps.

The name of this network in my cluster is cn001-bo (cluster network name).

Ethtool running on a node:

<img width="365" alt="image" src="https://github.com/harvester/harvester/assets/91493872/dd0e2129-dd60-4e75-806a-d1f1b6664613">

These are all the interfaces connected to this cluster network within the node:

<img width="1042" alt="image" src="https://github.com/harvester/harvester/assets/91493872/3f40ab37-9588-4ce6-8d6f-1bf165488cf7">

The default MTU for everything is 1500. On my edge switch, which delivers this 50Gbps bond, it is also 1500.

When running iperf on a cluster machine, the result is this:

```
Test Complete. Summary Results:
[ ID] Interval           Transfer     Bandwidth       Retr
[  4]   0.00-120.00 sec  20.8 GBytes  1.49 Gbits/sec  4077             sender
[  4]   0.00-120.00 sec  20.8 GBytes  1.49 Gbits/sec                  receiver
```
My vlans on the harvester have MTU 1500. Should I increase them? Won't this cause fragmentation and possible packet loss?

**Comment by starbops** [comment]
@mauriiciodias, I'm curious about the topology of your network on which you conducted the bandwidth test. Could you share if those two devices that run the `iperf` command are directly connected?

If you want to increase the MTU to a higher value, it is better to ensure the values are all the same along the transmission path. Otherwise, packet fragmentation will occur, adding latency and reducing the throughput. You can find the suitable MTU value with the `tracepath` command.

I saw that some retransmissions happened in your test results. It might cause the low bandwidth. But the real cause behind it is still unclear.

**Comment by starbops** [comment]
The planned fix is to replicate the `patchMTU` logic in the NAD mutator to the NAD controller and set up a resource watch to trigger the controller so that NADs are resynced every time their associated VlanConfig objects are modified.

IMO, this is a temporary solution as the MTU field in VlanConfig is under `.spec.uplink.linkAttributes`; it's meant to be part of the uplink's setting but not anything else. A formal way to make this right is to move the MTU setting all the way down to the ClusterNetwork CRD, like what #4355 suggested.

**Comment by bk201** [comment]
We prefer to fix the issue with https://github.com/harvester/harvester/issues/4355, it makes more sense.

**Comment by w13915984028** [comment]
FYI: We are working on an document about how to change the MTU on existing `Network Config/Cluster Network`.
