### ISSUE TITLE
[BUG] Grafana (Addon: rancher-monitoring) sign in is not working in Harvester 1.2.1

### ISSUE THREAD

**Issue by murgadani** [harvester/harvester#4756]
**Describe the bug**
Embeded grafana dashboard "sign in" button is not working.

**Workaround**
Update Feb. 23, 2024: 
**the workaroud link**: https://github.com/harvester/harvester/issues/4756#issuecomment-1874242139

The updated issue: https://github.com/harvester/harvester/issues/5221

**To Reproduce**
1. Enable rancher-monitoring addon (https://docs.harvesterhci.io/v1.2/monitoring/harvester-monitoring).
2. Go to grafana dashboard in main Harvester dashboard:
<img width="375" alt="image" src="https://github.com/harvester/harvester/assets/145478282/584cabb8-e7bc-46f8-8a6a-1b12dec18be3">
3. Click "sign in":
<img width="267" alt="image" src="https://github.com/harvester/harvester/assets/145478282/89c4a3c6-7fbf-4b8d-8863-128bd6ff01a9">
4. You'll get "page not found":
<img width="1451" alt="image" src="https://github.com/harvester/harvester/assets/145478282/4919ee23-9798-4aee-8583-9d2d99d8ced6">

**Expected behavior**
We expect to see the grafana "sign in" page, previous Harvester versions i.e. 1.1.0 is working fine
**Support bundle**
Support bundle file is too big. Please ask when needed.

**Environment**
 - Harvester ISO version: 1.2.1
 - Underlying Infrastructure: N/A

**Additional context**
The "sign in" endpoint is not available: 
https://[cluster_ip]/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/login
Other endpoints are working fine:
https://[cluster_ip]/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/metrics

**Comment by w13915984028** [comment]
The issue is reproducable in v1.2.1, such debug information is observed when login:

> logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2023-11-25T11:07:33.016145154Z level=error msg="Error from access control system" error="no resolver found"

**Comment by w13915984028** [comment]
The final workaround: https://github.com/harvester/harvester/issues/4756#issuecomment-1874242139

<del>
After a quite long time of investigating, a partial-working workaround is:

Add such a rule via `kubectl edit configmap -n cattle-monitoring-system grafana-nginx-proxy-config`

> proxy_redirect ~.*/login.* https://$host:443/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/login;

(note: this only works for stand-alone Harvester cluster, not Rancher managed cluster)

The root cause is that:
When click `login` in grafana web page, it will retuen a `302` code to client, but the returned `Location` field starts with `/api/v1/...` instead of `/k8s/clusters/local/api/v1...` or `/k8s/clusters/c-m-.../api/v1...`
The client will trigger a new request with URL as above `Location`, it will lead to 404 error

>192.168.122.141 - - [18/Dec/2023:16:21:33 +0000] "GET /d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&from=now-5m&to=now&refresh=30s&theme=light&forceLogin=true HTTP/1.1" 302 40 "https://192.168.122.141/k8s/clusters/local/api/v1/namespaces/cattle-monitoring-system/services/http:rancher-monitoring-grafana:80/proxy/d/rancher-cluster-nodes-1/rancher-cluster-nodes?orgId=1&from=now-5m&to=now&refresh=30s&theme=light" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36"
</del>

Still looking for a formal solution.

**Comment by w13915984028** [comment]
Workaround for this issue:

Note, the workaround  in Harvester v1.2.1 and v1.3.0 are slightly dfferent, please note.

**Harvester v1.2.1:**

1. edit following configmap to set the `map $http_referer $final_appSubUrl ` with new value

`kubectl edit configmap -n cattle-monitoring-system grafana-nginx-proxy-config`

copy the full context of `map $http_referer $final_appSubUrl`  from below URL:

Refer latest fix PR:  https://github.com/harvester/harvester-installer/pull/666

https://github.com/harvester/harvester-installer/blob/b61b877255572360b0f2f835ecb0cf2f71052e75/pkg/config/templates/patch/rancher-monitoring/102.0.0%2Bup40.1.2/nginx-config.yaml#L93

2. delete grafana pod to get a new replaced pod, which will load the above configmap
`kubectl delete pod -n $cm rancher-monitoring-grafana-7fc56c48dc-bx78b`

3. refresh `Harvester` WebUI, re-open the `grafana` link from Dashboard, try to `login` again.

**Harvester v1.3.0:**
The workaround steps are similar to above, for step 2, replace the content of `map $http_referer $final_appSubUrl` from following link:
Refer latest fix PR: https://github.com/harvester/harvester-installer/pull/665

**Comment by albinsun** [comment]
Provide test result on `master-6ca6acfd-head`, close as fixed.


## Environment
* Harvester
  * Version: `master-6ca6acfd-head`
  * Profile: QEMU/KVM, 2 nodes (8C/20G/500G)
  * ui-source: `Auto`


## Steps 
1. Enable `rancher-monitoring` addon
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/14bcc1b7-ed93-4cae-92f3-d28a50ab377b)
   </details>

1. Check `rancher-monitoring` chart are properly deployed
   <details>
   
   Chart
   ![image](https://github.com/harvester/harvester/assets/2773781/4336e383-e2a6-465c-b85c-4161258800ea)
   Pod
   ![image](https://github.com/harvester/harvester/assets/2773781/b1a49a77-008b-40c5-bd5b-5c6e3515be71)
   </details>

1. Go to grafana dashboard in from dashboard
   <details>

   ![image](https://github.com/harvester/harvester/assets/2773781/7488883a-597b-4f39-93f4-5444c7c7d6df)
   ![image](https://github.com/harvester/harvester/assets/2773781/45f1299d-7b74-4014-9694-4edcf1095d69)
   </details>


1. Click "Sign In", should see Grafana login page :ballot_box_with_check: 
   ![image](https://github.com/harvester/harvester/assets/2773781/de0ec7d1-ec2b-4cc1-9dc6-e424a578711a)
   ![image](https://github.com/harvester/harvester/assets/2773781/476a95bb-d225-4e2b-8931-2474a72461d2)

**Comment by RRadziejewski** [comment]
I'm facing the same issue with: (Harvester-v1.3.2)
