### ISSUE TITLE
[ENHANCEMENT] Bump base images to SLE 15 SP5

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4757]
**Is your enhancement related to a problem? Please describe.**
SLE 15 SP4 general ends on 31 Dec 2023. It's good to update to SP5.

**Images**
- [ ] docker.io/rancher/harvester-eventrouter:v0.1.1
- [ ] docker.io/rancher/harvester-load-balancer-webhook:v0.2.1
- [ ] docker.io/rancher/harvester-load-balancer:v0.2.1
- [ ] docker.io/rancher/harvester-network-controller:v0.3.4
- [ ] docker.io/rancher/harvester-network-helper:v0.3.4
- [ ] docker.io/rancher/harvester-network-webhook:v0.3.4
- [ ] docker.io/rancher/harvester-node-disk-manager:v0.5.1
- [ ] docker.io/rancher/harvester-node-manager:v0.1.7
- [ ] docker.io/rancher/harvester-pcidevices:v0.2.5
- [ ] docker.io/rancher/harvester-seeder:v0.1.0
- [ ] docker.io/rancher/harvester-upgrade:v1.2.1
- [ ] docker.io/rancher/harvester-vm-import-controller:v0.1.5
- [ ] docker.io/rancher/harvester-webhook:v1.2.1
- [ ] docker.io/rancher/harvester:v1.2.1
- [ ] docker.io/rancher/support-bundle-kit:v0.0.28
- [ ] docker.io/rancher/harvester-cluster-repo:v1.2.1
- [ ]  registry.suse.com/bci/bci-base:15.4

**Additional context**
https://www.suse.com/lifecycle/#suse-linux-enterprise-server-15

**Comment by bk201** [comment]
@FrankYang0529 Can you also help bump https://github.com/harvester/harvester/blob/69fd51debda28f122dbb0e89b46c88dd92c5d2e4/deploy/charts/harvester/values.yaml#L488-L492 ? Thanks!

**Comment by FrankYang0529** [comment]
> @FrankYang0529 Can you also help bump
> 
> https://github.com/harvester/harvester/blob/69fd51debda28f122dbb0e89b46c88dd92c5d2e4/deploy/charts/harvester/values.yaml#L488-L492


Update in https://github.com/harvester/harvester/issues/4839.

**Comment by lanfon72** [comment]
@FrankYang0529 any test plan for this? or pod name mapping to those images?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 any test plan for this? or pod name mapping to those images?

Hi @lanfon72, I think this issue can be checked by developer side. We will double check Dockerfile. If there is no issue, we will close it. Thanks.

**Comment by connorkuehl** [comment]
**Test Result: PASS**

---

Environment: QEMU, ISO built from head of v1.3 branch, commit 4372cbc4f9e3ab7ff05d89416a5582e47c732cfe.

The build process resulted in an images-list.txt that includes SLES SP5 (and 0 older bci-base images):

```console
> grep -F bci-base dist/artifacts/harvester-images-list.txt 
registry.suse.com/bci/bci-base:15.5
```

The only occurrence of the bci-base image in a fresh installation is SLES SP5:

```console
master-head-mar4-1:~ # ctr -n=k8s.io images list | grep -F bci-base
registry.suse.com/bci/bci-base:15.5                                                                     application/vnd.docker.distribution.manifest.v2+json sha256:d0f4729a65ab8505b3cf2661df2671c40ebb4a431c3877904f3cc236fbb9e819 118.5 MiB linux/amd64 io.cri-containerd.image=managed 
```

Install AddOns:

* nvidia-driver-toolkit
* rancher-logging
* rancher-monitoring

Confirm SLES 15.5 image is the only base SLES 15 image still on the system:

```console
master-head-mar4-1:~ # ctr -n=k8s.io images list | grep -F bci-base
registry.suse.com/bci/bci-base:15.5                                                                     application/vnd.docker.distribution.manifest.v2+json sha256:d0f4729a65ab8505b3cf2661df2671c40ebb4a431c3877904f3cc236fbb9e819 118.5 MiB linux/amd64 io.cri-containerd.image=managed 
```

Note:

I was unable to install these AddOns, though this is orthogonal to this specific GitHub issue and may be a result of how my ISO was built, etc. So I will investigate that separately and continue validating this issue.

| AddOn | Reason |
| - | - |
| pcidevices-controller | Error: INSTALLATION FAILED: chart "harvester-pcidevices-controller" matching 0.3.2 not found in pcidevices-controller index. (try 'helm repo update'): no chart name found |
| harvester-seeder | Error: INSTALLATION FAILED: chart "harvester-seeder" matching 0.1.1 not found in harvester-seeder index. (try 'helm repo update'): no chart name found |
| vm-import-controller | Error: INSTALLATION FAILED: chart "harvester-vm-import-controller" matching 0.1.7 not found in vm-import-controller index. (try 'helm repo update'): no chart name found |

For that reason, I manually inspected the Dockerfiles whose built images would be deployed as AddOns:

| AddOn | SLES BCI | Link |
| - | - | - |
| harvester-seeder | 15.5 | https://github.com/harvester/seeder/blob/709d84d0334d09814a342ba7372af5cbf2213cba/package/Dockerfile#L2 |
| pcidevices-controller | 15.5 | https://github.com/harvester/pcidevices/blob/82535bf09278420d225eaf3fe8dbff2e450b8f71/package/Dockerfile#L1 |
| vm-import-controller | 15.5 | https://github.com/harvester/vm-import-controller/blob/148cec8766d0dfa3d363f0b85d6ec327430d677d/package/Dockerfile#L1 |
