### ISSUE TITLE
"Please Reduce Your Request" (Q or Bug)

### ISSUE THREAD

**Issue by pineapple-vision** [harvester/harvester#476]
[BUG] Every time I try to download any image to harvester via URL, the download either stalls at some point or throws a "Please Reduce Your Request" error.   I have tried from different URLs, reset, reinstall, etc...

**Comment by gitlawr** [comment]
Can you ssh to the node and check the logs of the minIO pods?
```
$ kubectl get po -l app=minio -n harvester-system
$ kubectl logs -f minio-0 -n harvester-system
```

**Comment by gitlawr** [comment]
Duplicate of https://github.com/rancher/harvester/issues/449

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/releases/tag/v0.3.0, please re-open it if u encounter similar issues, thanks.
