### ISSUE TITLE
[Doc] Mention the 99_custom.yaml file change in the document

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4775]
**Is your doc request related to a problem? Please describe or add related issue ID.**

The cloud-init file `/ome/99_custom.yaml` changed to `/oem/90_custom.yaml` since v1.1.2, we should have this mentioned in the document. 

**Describe the solution you'd like**

The document could say:
- The new file name since v1.1.2.
- The file is not changed if a system is upgraded from previous versions And add the rationale why it's not changed to 90_custom.yaml in the upgrade path.

**Comment by Vicente-Cheng** [comment]
Close this because the document has already been updated.
Please check here https://docs.harvesterhci.io/v1.3/install/update-harvester-configuration/#configuration-persistence.
