### ISSUE TITLE
[FEATURE] Toolbox container image for packaing driver images

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4776]
**Is your feature request related to a problem? Please describe.**

We need toolbox container images for packaging driver images.

**Describe the solution you'd like**

- The image should be built in OBS and published to the SUSE registry.
- The image should contain toolchains, kernel headers, and common utilities.
- The image should map to released Harvester OS versions.

An example is https://github.com/ibrokethecloud/driver-packaging/blob/main/harvester-base-image/Dockerfile, which is use to build NVIDIA drivers. We need a SLE Micro counterpart.

cc @ibrokethecloud 

**Describe alternatives you've considered**

Include tool chain and kernel headers in harvester/os. This will increase the OS image size.

**Additional context**

**Comment by tserong** [comment]
@ibrokethecloud @jeff-radick-suse assuming you need to exactly match the kernel source you're installing, to the kernel that's currently installed, try this:
```
zypper in kernel-source=$(rpm -q --qf '%{Version}-%{Release}' kernel-default)
```

Or, in case you only need the headers, not the full kernel source:

```
zypper in kernel-default-devel=$(rpm -q --qf '%{Version}-%{Release}' kernel-default)
```

**Comment by tserong** [comment]
Oh, also, if you're doing this on OBS - in your Dockerfile, try _not_ adding any repos (i.e. don't do the `zypper ar` stuff) and see what happens - AIUI OBS should magically make the correct repositories available in the build environment somehow.

**Comment by tserong** [comment]
Unfortunately the `zypper in kernel-default-devel=$(rpm -q --qf '%{Version}-%{Release}' kernel-default)` trick won't work for images built in OBS. OBS parses `RUN` commands in Dockerfiles to check dependencies, and this of course can't work with embedded shell invocations - you'll see an error like "unresolvable: nothing provides kernel-default-devel = $, (got version 5.14.21-150400.24.100 provided by kernel-default-devel)".

What would work though, is creating a separate package alongside https://build.opensuse.org/package/show/isv:Rancher:Harvester:OS:v1.3/baseos, call it e.g. baseos-headers, with a Dockerfile something like this:

```Dockerfile
#!BuildTag: baseos-headers:latest
#

FROM baseos
RUN zypper --non-interactive install kernel-default-devel
```

Then we'd end up with two matching images:

* registry.opensuse.org/isv/rancher/harvester/os/v1.3/main/baseos:latest
* registry.opensuse.org/isv/rancher/harvester/os/v1.3/main/baseos-headers:latest

...and OBS will automatically rebuild the latter if the former is updated.

**Comment by tserong** [comment]
@ibrokethecloud pointed out that we could also use `#!ArchExcludedLine: ARCH_LIST` to make the OBS scheduler ignore the `RUN zypper install ... $(rpm ...)` line, which would allow us to continue to use that trick if necessary (see https://openbuildservice.org/help/manuals/obs-user-guide/cha.obs.supported_formats#id-1.5.10.8.5)

**Comment by jeff-radick-suse** [comment]
Based on what I've been told, this task is now completed by work Vicente has done.

**Comment by jeff-radick-suse** [comment]
I think I closed this prematurely.

**Comment by Vicente-Cheng** [comment]
It could be verified with the GPU enhancement.
Close it.

Feel free to re-open it if we need to verify this individually. cc @bk201, @ibrokethecloud
