### ISSUE TITLE
[BUG] Resizing Extra Volumes Fail if VM was shutdown via SSH `sudo shutdown -h now` (w/ 422: `admission webhook denied the request: please stop the VM before resizing volumes`)

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4778]
**Describe the bug**
Resizing an extra volume for the VM fails if the VM was shutdown by a user, via SSH with something like `sudo shutdown -h now`.

**To Reproduce**
1. Build a VM (I used Ubuntu based distro), in that VM add an extra disk (type disk)
2. Build a partition table with a single partition and mount that extra disk at somewhere like /mnt/extra, as if the disk were to be used by the os
3. Shutdown the VM with `sudo shutdown -h now` 
4. In the VM Index page on Harvester, you'll see the VM is off
5. Edit the config of the VM
6. Increase the extra-volume size
7. Attempt to save changes, you'll see that the admission webhook posts the error, `denied the request: please stop the VM before resizing volumes` - w/ 422

**Workaround**:
1. Start the VM from the UI
2. When the VM is running, just shut down the VM from the UI w/ "Stop"
3. Then you can resize the extra-volume successfully

**Expected behavior**
That it would be possible to resize an extra disk if the VM was shutdown via SSH command, like the UI "Stop" command.

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure: bare-metal 2 node

**Additional context**

![Screenshot from 2023-11-26 22-48-26](https://github.com/harvester/harvester/assets/5370752/6b007a55-1f7a-48d5-a02c-f99b5400802f)

Request:
```
curl 'https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver' --compressed -X PUT -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/119.0' -H 'Accept: application/json' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br' -H 'Content-Type: application/json' -H 'x-api-csrf: 9a70df5cd9c0aeec8cad19c5e798eb0a' -H 'Origin: https://tinycluster.localdomain' -H 'Connection: keep-alive' -H 'Referer: https://tinycluster.localdomain/dashboard/harvester/c/local/kubevirt.io.virtualmachine/default/caddy-fileserver?mode=edit' -H 'Cookie: R_PCS=light; R_LOCALE=en-us; R_REDIRECTED=true; CSRF=9a70df5cd9c0aeec8cad19c5e798eb0a; R_SESS=token-hk5jb:t5wp8g7ldh5wsz8h57wwht67jnk96pt5gq89zxzcgxcv66h574pxzq' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'TE: trailers' --data-raw '{"id":"default/caddy-fileserver","type":"kubevirt.io.virtualmachine","links":{"remove":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver","self":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver","update":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver","view":"https://tinycluster.localdomain/apis/kubevirt.io/v1/namespaces/default/virtualmachines/caddy-fileserver"},"actions":{"addVolume":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=addVolume","backup":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=backup","clone":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=clone","createTemplate":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=createTemplate","removeVolume":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=removeVolume","restart":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=restart","start":"https://tinycluster.localdomain/v1/harvester/kubevirt.io.virtualmachines/default/caddy-fileserver?action=start"},"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","metadata":{"annotations":{"harvesterhci.io/vmRunStrategy":"RerunOnFailure","harvesterhci.io/volumeClaimTemplates":"[{\"metadata\":{\"name\":\"caddy-fileserver-disk-0-krvos\",\"annotations\":{\"harvesterhci.io/imageId\":\"default/image-lzml6\"}},\"spec\":{\"accessModes\":[\"ReadWriteMany\"],\"resources\":{\"requests\":{\"storage\":\"10Gi\"}},\"volumeMode\":\"Block\",\"storageClassName\":\"longhorn-image-lzml6\"}},{\"metadata\":{\"name\":\"caddy-fileserver-disk-1-codr8\"},\"spec\":{\"accessModes\":[\"ReadWriteMany\"],\"resources\":{\"requests\":{\"storage\":\"161Gi\"}},\"volumeMode\":\"Block\",\"storageClassName\":\"harvester-longhorn\"}}]","kubevirt.io/latest-observed-api-version":"v1","kubevirt.io/storage-observed-api-version":"v1alpha3","network.harvesterhci.io/ips":"[]"},"creationTimestamp":"2023-11-15T21:47:13Z","fields":["caddy-fileserver","11d","Stopped","False"],"finalizers":["harvesterhci.io/VMController.UnsetOwnerOfPVCs"],"generation":4,"labels":{"harvesterhci.io/creator":"harvester","harvesterhci.io/os":"ubuntu"},"managedFields":[{"apiVersion":"kubevirt.io/v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:harvesterhci.io/vmRunStrategy":{},"f:harvesterhci.io/volumeClaimTemplates":{},"f:network.harvesterhci.io/ips":{}},"f:finalizers":{".":{},"v:\"harvesterhci.io/VMController.UnsetOwnerOfPVCs\"":{}},"f:labels":{".":{},"f:harvesterhci.io/creator":{},"f:harvesterhci.io/os":{}}},"f:spec":{".":{},"f:template":{".":{},"f:metadata":{".":{},"f:annotations":{".":{},"f:harvesterhci.io/sshNames":{}},"f:labels":{".":{},"f:harvesterhci.io/vmName":{}}},"f:spec":{".":{},"f:affinity":{".":{},"f:nodeAffinity":{"f:preferredDuringSchedulingIgnoredDuringExecution":{}}},"f:domain":{".":{},"f:cpu":{".":{},"f:cores":{},"f:sockets":{},"f:threads":{}},"f:devices":{".":{},"f:disks":{},"f:inputs":{},"f:interfaces":{}},"f:features":{".":{},"f:acpi":{".":{},"f:enabled":{}}},"f:machine":{".":{},"f:type":{}},"f:resources":{".":{},"f:limits":{".":{},"f:cpu":{},"f:memory":{}}}},"f:evictionStrategy":{},"f:hostname":{},"f:networks":{},"f:terminationGracePeriodSeconds":{},"f:volumes":{}}}}},"manager":"harvester","operation":"Update","time":"2023-11-27T06:40:57Z"},{"apiVersion":"kubevirt.io/v1alpha3","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{"f:kubevirt.io/latest-observed-api-version":{},"f:kubevirt.io/storage-observed-api-version":{}}},"f:spec":{"f:runStrategy":{}}},"manager":"Go-http-client","operation":"Update","time":"2023-11-27T06:41:14Z"},{"apiVersion":"kubevirt.io/v1alpha3","fieldsType":"FieldsV1","fieldsV1":{"f:status":{".":{},"f:conditions":{},"f:created":{},"f:printableStatus":{},"f:volumeSnapshotStatuses":{}}},"manager":"Go-http-client","operation":"Update","subresource":"status","time":"2023-11-27T06:53:33Z"}],"name":"caddy-fileserver","namespace":"default","relationships":[{"toId":"default/caddy-fileserver-g8y7g","toType":"secret","rel":"owner","state":"active","message":"Resource is always ready"},{"toId":"default/revision-start-vm-7ab40482-8f48-4738-951a-f9dd646c8e35-4","toType":"apps.controllerrevision","rel":"owner","state":"active","message":"Resource is current"},{"toId":"default/caddy-fileserver","toType":"kubevirt.io.virtualmachineinstance","rel":"owner","state":"succeeded","message":"virt-launcher pod is terminating"}],"resourceVersion":"13809828","state":{"error":false,"message":"virt-launcher pod is terminating","name":"unavailable","transitioning":true},"uid":"7ab40482-8f48-4738-951a-f9dd646c8e35"},"spec":{"runStrategy":"RerunOnFailure","template":{"metadata":{"annotations":{"harvesterhci.io/sshNames":"[\"default/michael.russell\"]"},"creationTimestamp":null,"labels":{"harvesterhci.io/vmName":"caddy-fileserver"}},"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"network.harvesterhci.io/extra-net","operator":"In","values":["true"]}]}]},"preferredDuringSchedulingIgnoredDuringExecution":[]}},"domain":{"cpu":{"cores":2,"sockets":1,"threads":1},"devices":{"disks":[{"name":"disk-0","disk":{"bus":"virtio"},"bootOrder":1},{"name":"disk-1","disk":{"bus":"virtio"},"bootOrder":2},{"name":"cloudinitdisk","disk":{"bus":"virtio"}}],"inputs":[{"bus":"usb","name":"tablet","type":"tablet"}],"interfaces":[{"bridge":{},"macAddress":"d2:a1:43:e8:4c:7c","model":"virtio","name":"default"}]},"features":{"acpi":{"enabled":true}},"machine":{"type":"q35"},"memory":{"guest":"1948Mi"},"resources":{"limits":{"cpu":"2","memory":"2Gi"},"requests":{"cpu":"125m","memory":"1365Mi"}}},"evictionStrategy":"LiveMigrate","hostname":"caddy-fileserver","networks":[{"name":"default","multus":{"networkName":"default/mgmt-net-on-extra"}}],"terminationGracePeriodSeconds":120,"volumes":[{"name":"disk-0","persistentVolumeClaim":{"claimName":"caddy-fileserver-disk-0-krvos"}},{"name":"disk-1","persistentVolumeClaim":{"claimName":"caddy-fileserver-disk-1-codr8"}},{"name":"cloudinitdisk","cloudInitNoCloud":{"secretRef":{"name":"caddy-fileserver-g8y7g"},"networkDataSecretRef":{"name":"caddy-fileserver-g8y7g"}}}]}}},"status":{"conditions":[{"error":false,"lastProbeTime":"2023-11-27T06:53:33Z","lastTransitionTime":"2023-11-27T06:53:33Z","lastUpdateTime":"2023-11-27T06:53:33Z","message":"virt-launcher pod is terminating","reason":"PodTerminating","status":"False","transitioning":true,"type":"Ready"},{"error":false,"lastProbeTime":null,"lastTransitionTime":null,"lastUpdateTime":"","status":"True","transitioning":false,"type":"LiveMigratable"}],"created":true,"printableStatus":"Stopped","volumeSnapshotStatuses":[{"enabled":false,"name":"disk-0","reason":"2 matching VolumeSnapshotClasses for longhorn-image-lzml6"},{"enabled":false,"name":"disk-1","reason":"2 matching VolumeSnapshotClasses for harvester-longhorn"},{"enabled":false,"name":"cloudinitdisk","reason":"Snapshot is not supported for this volumeSource type [cloudinitdisk]"}]}}'
```
Response:
```
{"type":"error","links":{},"code":"Invalid","message":"admission webhook \"validator.harvesterhci.io\" denied the request: please stop the VM before resizing volumes","status":422,"type":"error"}

```

**Comment by w13915984028** [comment]
This issue and https://github.com/harvester/harvester/issues/4699, are related the VM backed objects:
https://docs.harvesterhci.io/v1.2/troubleshooting/vm#general-vm-related-objects

`Stop VM from WebUI` and `Shutdown VM from inside the VM` are similar, but there are differences.

**Comment by Yu-Jack** [comment]
Find out because there is a validator to check vm.Spec.RunStrategy is Halt or not [here](https://github.com/harvester/harvester/blob/master/pkg/webhook/resources/virtualmachine/validator.go#L200-L202). 

When you use `poweroff` command to stop vm instead of GUI, the`vm.Spec.RunStrategy` will not be changed. That's the reason why validator rejects the request. It seems this issue exists for a while in accordance
with https://github.com/harvester/harvester/issues/2265#issue-1232804974 and https://github.com/harvester/harvester/issues/2265#issuecomment-1125758792.

**The first solution** occurred to me, we could only check `.Status.PrintableStatus` is equal to `Stopped` or not instead of `.Spec.RunStrategy`.  Or we could use one more condition which checks `.Status.PrintableStatus` is `Stopped` and VMI is `SUCCEDED`.

**The second solution** I tried is we could detect the `vm.Spec.RunStrategy` and `vm.Status.PrintableStatus` to sync the resources. For example, if we detect `vm.Spec.RunStrategy` is not Halt and `vm.Status.PrintableStatus` is Stopped, this case matches poweroff case. Then we could delete vmi and update RunStrategy to Halt if we could fetch the `SUCCEDED` vmi.

BTW, there is another case matches `vm.Spec.RunStrategy` is not Halt and `vm.Status.PrintableStatus` is Stopped. After I start VM, it goes from 1 to 2. That's why we should check vmi is null or not.

1. Strategy: Halt, PrintableStatus: Stopped
2. Strategy: RerunOnFailure, PrintableStatus: Stopped
3. Strategy: RerunOnFailure, PrintableStatus: Starting

**Comment by Yu-Jack** [comment]
There is another case I tested when setting `Strategy: Always`. If I run `poweroff` inside the VM, the VM will restart. This behavior is different to GUI. After clicking `STOP` button in GUI, it will be `Strategy: Halt` when it's `Strategy: Always` and the status will be `Stopped`.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.
> [!NOTE]
> Backport `v1.2.2` will be test seperately later.


## Environment
* Harvester
  * Version: `v1.3.0-dev-20231222`
  * Profile: QEMU/KVM, single node (8C/16G/500G)
  * ui-source: `Auto`


## Test Step
1. <details>
      <summary> Create a VM with extra 8G disk
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/42353bb2-d1c7-438f-9814-b1c5c4326d41)
   </details>

1. <details>
      <summary> SSH to VM, create partition and some test data
      </summary>
   
   * partition
   ![image](https://github.com/harvester/harvester/assets/2773781/31c99ba6-4f5c-4713-b9cb-a273cc30f5c4)
   * test data (root disk)
   ![image](https://github.com/harvester/harvester/assets/2773781/12ef6e66-aec7-4c48-947b-d90452906112)
   * test data (extra disk)
   ![image](https://github.com/harvester/harvester/assets/2773781/63ee3f23-729a-48eb-9fc4-7d0c4eb3a82b)
   </details>

1. <details>
      <summary> shutdown VM from inside VM CMD <code>sudo shutdown -h now</code>
      </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/6af2dfc8-e5a4-449a-8dfc-e9430d788b5d)
   </details>

1. <details open>
      <summary> Increase extra disk size to 16G from UI</code> :ballot_box_with_check: 
      </summary>

      * Edit
      ![image](https://github.com/harvester/harvester/assets/2773781/457352e0-b9ed-49cd-bf30-c90e7bfa925b)
      * Resizing
      ![image](https://github.com/harvester/harvester/assets/2773781/0421b0b6-7373-46ce-883b-4250058b30ca)
      * Ready
      ![image](https://github.com/harvester/harvester/assets/2773781/ed89ab96-3a17-4664-b649-f8933e8f5a0c)
   </details>

1. <details>
      <summary> Start VM, partition and data should still available</code> :ballot_box_with_check: 
      </summary>

      ![image](https://github.com/harvester/harvester/assets/2773781/9c12a5ac-b09e-499c-b5b6-bee34f118778) 
   </details>


## Note
1. Can reproduce in `v1.2.1`
   ![image](https://github.com/harvester/harvester/assets/2773781/ec39284c-5acc-45af-b059-926dbcbcdf76)
