### ISSUE TITLE
[TASK] Bump embedded Rancher to v2.7.9 and RKE2 to v1.26.x

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4782]
**Is your enhancement related to a problem? Please describe.**

Bump embedded Rancher and RKE2 to the next supported versions.

**Describe the solution you'd like**

- Rancher: v2.7.9
- RKE2: v1.26.x

**Describe alternatives you've considered**

**Additional context**

**Comment by lanfon72** [comment]
Verified this change has been applied.
To be noticed that this bug been fixed on `master-head` but not `v1.3` branch yet.

![image](https://github.com/harvester/harvester/assets/5169694/8372b699-23f5-44ec-a138-075e6c0cf282)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-d3dc81ca-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to console, execute `sudo ranchered info`
