### ISSUE TITLE
[ENHANCEMENT] Manually configure Harvester roles for hosts

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4786]
**Is your enhancement related to a problem? Please describe.**

Harvester automatically promotes random nodes into the controller node, there are situations we don't want a node to be promoted.

**Describe the solution you'd like**

- Specify node's role while installing the node. We can have "management", "witness", "compute", etcd.

**Describe alternatives you've considered**

**Additional context**

**Comment by Vicente-Cheng** [comment]
For this enhancement, we would like to do the following two things.
1. promote the specific node to mgmt node
2. prevent promote the specific node to mgmt node

We will define the following three role label
- management
- witness
- worker

The promote rule is as follows:
- without role definition: promote the ready worker node randomly
- with role definition:
  - promote the witness node to etcd node. (maximum: 1)
  - promote the mgmt node to mgmt node.
  - do not promote the worker node.

WDYT? cc @bk201, @ibrokethecloud

**Comment by bk201** [comment]
That sounds sane to me.

**Comment by albinsun** [comment]
## Test Plan

### Objective
1. Test the promotion behavior of each role when
   * Join a cluster which quorum is 1, 2, 3
   * Existed, but cluster quorum drops from 3 to 2 (one management down)
1. Worker will never be promoted
   * Setup initial condition as 1 D/M + 1 C
   * The C node-1 will never be promote.
1. Witness only promote when reach quorum.


### ExpeTest Matrix
We have 4 TCs each role, 16 total.

| **State When**     | **Join q=1** | **Join q=2** | **Join q=3** | **q=3->2 ** |
|:------------------:|:------------:|:------------:|:------------:|:-----------:|
| **management (M)** |  C (1M1C)    |   M (3M)     |   C (3M1C)   |  M (3M)     |
|   **default (D)**  |  C (1M1C)    |   M (3M)     |   C (3M1C)   |  M (3M)     |
|   **witness (W)**  |  W (1M1W)    |   M (3M)     |   W (3M1W)   |  M (3M)     |
|   **worker (C)**   |  C (1M1C)    |   C (2M1C)   |   C (3M1C)   |  C (2M1C)   |

> [!NOTE]
> Q: Quorum (3 here)
> q: Current number of management (candidates), namely `#M + #D + #W`

**Comment by albinsun** [comment]
Provide test result for `management` suite.

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 8C/10G/500G per node

 
## Steps
1. Setup D node-0 and C node-1
   ![image](https://github.com/harvester/harvester/assets/2773781/c3fe1933-88b8-4d6a-a467-14be322a6635)
   * `#D + #M + #W (1) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/993281f3-252b-4ae0-b6aa-e52a06342ca1)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ce3d2440-4e71-4d32-820c-0e630e976109)
     </details>

   * <details>
     <summary> Longhorn nodes is 2 :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/871c7e40-8638-4bce-a5c9-5657e7bf4f30)
     </details>


2. Join M node-2 (Join q=1)
   ![image](https://github.com/harvester/harvester/assets/2773781/2891ffd2-f548-45d5-8ffb-b94c123dbd40)
   * `#D + #M + #W (2) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/72308e48-b9c4-453f-b82b-4ee397158ead)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/db290e97-1b41-4505-999c-3cb8c90a4140)
     </details>

   * <details>
     <summary> node-2 (M) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/37a0b873-4800-498e-8709-223ef7dbb9b3)
     </details>

   * <details>
     <summary> Longhorn nodes is 3 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f36c9724-d5dc-48ed-b5b4-923c140e32a3)
     </details>


3. Join M node-3 (Join q=2)
   ![image](https://github.com/harvester/harvester/assets/2773781/7b81c64e-bae3-48bd-8b96-00d74253ef47)
   * `#D + #M + #W (3) == 3`, should promote! :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/bf955916-6696-4156-bf9e-5b504e6845af)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/474c9857-4064-4756-a9bd-a7a301727e50)
     </details>

   * <details>
     <summary> node-2 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/e3a9f145-dc3a-4cc6-967e-99d95a77c6d2)
     </details>

   * <details>
     <summary> node-3 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9d69eae4-0613-4ead-9391-e81933e6f5c5)
     </details>

   * <details>
     <summary> Longhorn nodes is 4 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9b9e130d-01bc-4b88-b3b6-0642775af7aa)
     </details>


4. Join M node-4 (Join q=3)
   ![image](https://github.com/harvester/harvester/assets/2773781/5e64e3cc-3f3f-44eb-b922-091b07b4af6e)
   * `#D + #M + #W (4) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f67995da-9d3b-47f0-8027-f1af55d50180)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/240f8efd-33fa-4d3a-a12c-6d22dc64dad7)
     </details>

   * <details>
     <summary> node-2 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/92da0260-43bd-4374-bcb0-baaa3109a898)
     </details>

   * <details>
     <summary> node-3 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7df65ae8-44a4-42f4-af99-70841d8f12e1)
     </details>

   * <details>
     <summary> node-4 (M) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a741789e-3362-43d6-9f36-781e3d69d1a8)
     </details>

   * <details>
     <summary> Longhorn nodes is 5 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5393bf7b-6c48-46ee-90d2-7a2008da5eea)
     </details>


5. Delete node-2 (M) (q=3->2)
   ![image](https://github.com/harvester/harvester/assets/2773781/3af93e80-385e-4cdc-a946-b8953ae7f691)
   * `#D + #M + #W (3) == 3`, should promote! :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/e08f879a-562d-4709-a0cb-335506e0cb9b)
     </details>
   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/4c8fc291-b51e-4fea-b142-54e547755111)
     </details>
   * <details>
     <summary> node-2 (M) is <code>n/a</code> :heavy_check_mark: 
     </summary>
     
     </details>
   * <details>
     <summary> node-3 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/8246ff8e-275a-4e5a-9b08-7636f3e44e4c)
     </details>
   * <details>
     <summary> node-4 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a53b6283-2605-4d08-a257-9e5aad3406d0)
     </details>
   * <details>
     <summary> Longhorn nodes is 4 :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a3fd4d3f-9bb4-4f3d-8f88-8d034f11e54a)
     </details>

**Comment by albinsun** [comment]
Provide test result for `defult` role suite.

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 5 nodes (8C/10G/500G)

 
## Steps
1. Setup M node-0 and C node-1
   ![image](https://github.com/harvester/harvester/assets/2773781/54ce8787-bd3f-4ead-afb1-8ea53b794032)
   * `#D + #M + #W (1) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (M) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/716707eb-cc7a-4116-85c1-de0ef4973a63)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0d6507f6-6cbf-422e-bb07-563b7070e28c)
     </details>

   * <details>
     <summary> Longhorn nodes is 2 :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6856073b-6a9f-4ef3-90b1-8435782f9e90)
     </details>


2. Join D node-2 (Join q=1)
   ![image](https://github.com/harvester/harvester/assets/2773781/39a95b54-8a9c-40f7-9e1e-8ad690b0927f)
   * `#D + #M + #W (2) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (M) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5caad411-ef05-4b9e-8003-e6490a0dedb7)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2f327685-58b8-485d-8a87-622ec96ffc27)
     </details>

   * <details>
     <summary> node-2 (D) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7daaa0bd-d331-48db-aa14-2f791c820e2d)
     </details>

   * <details>
     <summary> Longhorn nodes is 3 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d89484e2-98eb-4351-b4b3-c55bd97d501c)
     </details>


3. Join D node-3 (Join q=2)
   ![image](https://github.com/harvester/harvester/assets/2773781/5e8e2250-04f1-44d9-b4fc-ea4a126a2b00)
   * `#D + #M + #W (3) == 3`, should promote! :heavy_check_mark: 
   * <details>
     <summary> node-0 (M) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5768996e-e00a-4d3e-ae41-113639f2185a)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cec5d47e-aa93-4f04-b2be-c9de650a35b8)
     </details>

   * <details>
     <summary> node-2 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/21c19592-f2fb-4d18-847a-d57711edea1e)
     </details>

   * <details>
     <summary> node-3 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c1327d3f-300a-48fe-8124-d61c44754de8)
     </details>

   * <details>
     <summary> Longhorn nodes is 4 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c4d3a70a-1b7a-4cdc-a10a-aa9a5dc9ac7c)
     </details>


4. Join D node-4 (Join q=3)
   ![image](https://github.com/harvester/harvester/assets/2773781/9139f9c8-e7aa-4681-a09a-d19003335633)
   * `#D + #M + #W (4) != 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (M) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6d69cc10-97db-4a48-b10e-9cd1459932fa)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d37090ab-b092-4231-8a5b-d5beb16309a9)
     </details>

   * <details>
     <summary> node-2 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b63adc5c-7cb4-47ae-a85b-383338f7d911)
     </details>

   * <details>
     <summary> node-3 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/94078506-6546-42bc-a6df-8ba66856eeb8)
     </details>

   * <details>
     <summary> node-4 (D) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c45146ed-95da-48db-a716-11c5617370fc)
     </details>

   * <details>
     <summary> Longhorn nodes is 5 :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/861b90b3-3214-4b54-be5a-6d06c43a45b1)
     </details>


5. Delete node-3 (M) (q=3->2)
   ![image](https://github.com/harvester/harvester/assets/2773781/8f13c4c8-c458-42cf-9582-fc8167cca6fd)
   ![image](https://github.com/harvester/harvester/assets/2773781/cf2ea714-bb08-452a-8381-503caa0ba157)
   * `#D + #M + #W (3) == 3`, should promote! :heavy_check_mark: 
   * <details>
     <summary> node-0 (M) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/e59a819a-ea90-45c3-81dd-4fdd83b0d6e7)
     </details>
   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/823127f1-67b8-4fd8-ba14-64810bdf2f37)
     </details>
   * <details>
     <summary> node-2 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/492cfbcb-6aa9-4cfa-8fd8-1e559c527b82)
     </details>
   * <details>
     <summary> node-3 (D) is <code>n/a</code> :heavy_check_mark: 
     </summary>
     
     </details>
   * <details>
     <summary> node-4 (D) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a103dcba-efef-4180-9622-76f246554b04)
     </details>
   * <details>
     <summary> Longhorn nodes is 4 :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/d5a62980-6cce-412e-93f8-42254eb9b2e4)
     </details>

**Comment by albinsun** [comment]
Provide test result for `witness` role suite.

Issues:
1. #5161
2. #5163

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 5 nodes (8C/10G/500G)

 
## Test Cases
### DCWWM drop node-2 (promoted W)
1. Setup D node-0 and C node-1
   > Same as previous suites.

3. Join W node-2 (Join q=1)
   * `1D + 0M + 1W = 2 not 3`, should NOT promote. :heavy_check_mark:  
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/83abd860-31bb-4183-afc8-edfa0b389b78)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9660b65d-a231-418e-9b69-44290560ec23)
     </details>

   * <details>
     <summary> node-2 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f1d35c90-0cff-415d-9e98-daecdb4240e1)
     </details>

   * <details>
     <summary> Longhorn nodes is 2 (MC) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9ee81631-d6a0-4514-9fbc-42e780e40363)
     </details>


4. Join W node-3 (Join q=3)
   * `1D + 0M + 2W(1) = 2 not 3`, should NOT promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/1475998c-f0e5-4c67-bd88-a4347c78c2fb)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c8b848ce-47b0-407c-9955-c0f584b2cebf)
     </details>

   * <details>
     <summary> node-2 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cc586bbf-e4b1-471b-a97c-5342de733acc)
     </details>

   * <details>
     <summary> node-3 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5d290362-7e65-412b-a81b-5edbbe40ba9e)
     </details>

   * <details>
     <summary> Longhorn nodes is still 2 (MC) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/fcbdacae-8bb5-4526-a4ea-325884f27553)
     </details>


5. Join M node-4 (Join q=3)
   * `1D + 1M + 2W(1) = 3`, should promote. :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6b1a61f1-0c9e-46e0-8a8f-375748557da2)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/1c54fbb2-b635-458c-81da-03bbdcd665ef)
     </details>

   * <details open>
     <summary> node-2 (W) is <code>Witness (etcd)</code> :x: ${\color{red} \text{Still Witness (none), node-2 should have higher promotion priority than node-3 since join early. }}$
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0651a547-04e3-4b1b-815c-67b673fb29b9)
     </details>

   * <details open>
     <summary> node-3 (W) is <code>Witness</code>  :x: ${\color{red} \text{Promote to etcd, but node-2 should have higher promotion priority than node-3. }}$ 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ab61e3b5-b17e-4ad3-b041-6bf6f58cfb45)
     </details>

   * <details>
     <summary> node-4 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/309ea3ff-35db-44da-95f4-715245208397)
     </details>

   * <details>
     <summary> Longhorn nodes is 3 (node-0,1 and 4) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7ece1c2a-815f-457e-b8aa-cd68a9067f8b)
     </details>


6. Delete Witness(etcd) node-3 (q=3->2)
   * `#1 + #1 + 1W == 3`, should promote! :heavy_check_mark: 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/df8a299e-a2eb-4989-8688-a61a190cc964)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0b2c255e-fd0b-468a-9c6c-decdc452e07f)
     </details>

   * <details>
     <summary> node-2 (W) is <code>Witness (etcd)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ac6067b7-2b9c-4f62-bada-dbaa96a71f0b)
     </details>

   * <details>
     <summary> node-3 (W) is <code>n/a</code> :heavy_check_mark:  
     </summary>
     
     </details>

   * <details>
     <summary> node-4 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/2a7a49e8-7216-4f49-94b5-efc6554851b1)
     </details>

   * <details>
     <summary> Longhorn nodes is 3 (DCM) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/8506534b-ce6a-45a3-a58d-a872bf4a57b4)
     </details>

### DCWWM drop node-2 (promoted W)
#5163

**Comment by albinsun** [comment]
Provide test result for `worker` suite.

## Issues
1. #5175 


## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 5 nodes (8C/10G/500G)

 
## Test Cases
### Join q=1 and q=2 + q=3 -> 2
1. Cluster: DC
   * <details>
     <summary> Setup DCCD cluster, should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/081462c9-a5aa-4b68-9f5e-86c67c575ae0)
     </details>
     
   * <details>
     <summary> Join W node-4, should promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cf56fe0c-1352-476b-9f43-fde187d9be66)
     </details>     
     
   * <details>
     <summary> Delete node-2 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ad7b5392-79de-4f5b-8038-a3ffa373adf7)
     </details>

   * <details>
     <summary> Delete node-3 (D), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9f02c0e4-674d-4ac5-b7e8-ae0cff29cb94)
     </details>

   * <details>
     <summary> Delete node-4 (W), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a0448f8b-7faf-4bb2-b0e4-802c386b887f)
     </details>

1. Cluster: MC
   * <details>
     <summary> Setup MCMC cluster, should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6f07f9f5-f493-4ffb-bd44-e81b38b1a5ea)
     </details>
     
   * <details>
     <summary> Join W node-4, should promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/e5f85836-1dbd-47c1-a0d8-fe07661e31a6)
     ![image](https://github.com/harvester/harvester/assets/2773781/9cfbf67d-74dc-443d-83e2-5c64d90421e6)
     </details>     
     
   * <details>
     <summary> Delete node-4 (W), should NOT promote :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/d7c77040-e256-4c3b-b08e-7e112d7c4068)
     </details>

   * <details>
     <summary> Delete node-2 (M), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7ff05bb2-51d0-481b-a233-61ad1ce0465b)
     </details>

   * <details>
     <summary> Delete node-1 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/3e88a5ed-9a10-4e7c-a0f2-86de23df673b)
     </details>


### Join q=3 + q=3 -> 2
1. Cluster: DMMCC
   * <details>
     <summary> Setup DMMC cluster :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/4dc82639-3dfd-48f6-a3e9-0e691a0796b9)
     </details>

   * <details>
     <summary> Join node-4 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/77728a90-f7c5-4390-ae45-9ecade782df0)
     </details>
     
   * <details>
     <summary> Delete node-1 (M), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6dd49e0c-dae7-4e7b-b206-9b2adff62dce)
     </details>

   * <details>
     <summary> Delete node-3 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/71317bb6-968c-4775-9cc3-f76209d48562)
     </details>


2. Cluster: DMWCC
   * <details>
     <summary> Setup DMWC cluster, shoud promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/80598b5f-8e2e-4ebe-93c2-2a847dc6a212)
     ![image](https://github.com/harvester/harvester/assets/2773781/e4143d95-a402-4217-b226-bc287de97566)
     </details>

   * <details>
     <summary> Join node-4 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ce711e81-bb0e-40cb-a943-88ff19f2e31d)
     </details>
     
   * <details>
     <summary> Delete node-2 (W), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/25e5b996-b134-4a31-838c-cb840971e8d7)
     </details>

   * <details>
     <summary> Delete node-4 (C), should NOT promote :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c5f4c2ef-9c7a-47be-ab22-d4f2b7877877)
     </details>

**Comment by albinsun** [comment]
> ## Test Plan
> ### Objective
> 1. Test the promotion behavior of each role when
>    
>    * Join a cluster which quorum is 1, 2, 3
>    * Existed, but cluster quorum drops from 3 to 2 (one management down)
> 2. Worker will never be promoted
>    
>    * Setup initial condition as 1 D/M + 1 C
>    * The C node-1 will never be promote.
> 3. Witness only promote when reach quorum.
> 
> ### ExpeTest Matrix
> We have 4 TCs each role, 16 total.
> 
> **State When**	**Join q=1**	**Join q=2**	**Join q=3**	**q=3->2 **
> **management (M)**	C (1M1C)	M (3M)	C (3M1C)	M (3M)
> **default (D)**	C (1M1C)	M (3M)	C (3M1C)	M (3M)
> **witness (W)**	W (1M1W)	M (3M)	W (3M1W)	M (3M)
> **worker (C)**	C (1M1C)	C (2M1C)	C (3M1C)	C (2M1C)

Summarize test result on `v1.3.0-rc2`, features basically works as expect.
Following are issues found so far:
1. #5161 
2. #5163 
3. #5175 

Will close this ticket first and track each issue respectively.
