### ISSUE TITLE
Is this a typical problem with this harvester that the rke2 clusters above the harvester no longer start (remains in pending state) after rebooting the harvester nodes following a power outage for example? version 1.2

### ISSUE THREAD

**Issue by Oelyhasina** [harvester/harvester#4789]
Pending state of Kubernetes clusters on harvester after reboot

**Comment by Vicente-Cheng** [comment]
might be duplicated with https://github.com/harvester/harvester/issues/4633

**Comment by w13915984028** [comment]
@Oelyhasina:

Did you reproduce/encounter this in your cluster? For each phenomenon, we need enough debug information (e.g. support-bundle) to analyze the root cause, thanks.

**Comment by w13915984028** [comment]
Two similar issues https://github.com/harvester/harvester/issues/4033, #4633 are validated to be fixed in v1.3.0, close this issue.
