### ISSUE TITLE
[BUG] switch harvester UI to use rancher user id as backup  when local username is empty during PCIDeviceClaim creation

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#4796]
**Describe the bug**

**To Reproduce**
1. Configure rancher to use an identity provider, say Github.
2. Import a harvester cluster via Virtualization Management in Rancher.
3. Using a cluster admin role, enable a PCIDevice on Harvester cluster using the Rancher authentication.
4. Verify PCIDevice is enabled for passthrough
5. Go to VM creation page and create a VM with this PCIDevice

The PCIDevice view is empty and recently enabled PCIDevice does not show up in the UI.

**Expected behavior**

The PCIDevice should be visible during VM creation
**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Rancher v2.7.6

**Additional context**

The issue is being caused due to `Local Username` not being populated by Rancher against the rancher user id.

The Harvester UI passes the `Local Username` to PCIDeviceclaim. Currently when this is empty the `username` is left empty, which causes the UI behaviour.

![image](https://github.com/harvester/harvester/assets/19664014/3d90c930-2a0d-411a-9ff1-39789f27cf9f)

Sample users page when using Github:
![image](https://github.com/harvester/harvester/assets/19664014/630f318b-e959-47c4-952a-4af24afce973)

The easy fix would be change the Harvester UI code to switch to `ID` when `Local Username` is empty. This should allow the change to be backward compatible.

**Comment by torchiaf** [comment]
@ibrokethecloud I could replicate the issue by login with both admin & github user, and it seems not related to the user's role. I've fixed the bug making the device list reactive for the table component.

**Comment by torchiaf** [comment]
@ibrokethecloud based on our discussion, I changed the code to enable PCI devices using the `ID` in place of `username` for non-admin users. Thanks for the hints ! :smiley:

**Comment by ibrokethecloud** [comment]
@torchiaf is there a sample index that I can use to try out the changes?

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc1`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3.0-rc1`
  * Profile: QEMU/KVM, single nodes (12C/64G/2T)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.6`
  * Profile: rancher-vcluster [^1]


## Steps
1. Login Rancher as a standard user
   * <details>
     <summary> with role <code>Config Authentication</code> and <code>Create new Cluster</code>
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/01f4b8ed-b004-429d-957c-fd4cc3ae0071)
     </details>

1. Enable Rancher Github OAuth.
   * <details>
     <summary> Github OAuth is enabled :heavy_check_mark: 
     </summary>
     
     Go **Users & Authentication** -> **Auth Provider** -> following instruction to enable
     ![image](https://github.com/harvester/harvester/assets/2773781/12294179-b7e8-456a-96a0-06c253684911)
     </details>

   * <details>
     <summary> If success, current account will bind to your github account :heavy_check_mark:  
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b12c7150-0d8b-435b-8344-7a64fd64be78)
     Confirm only one standard user
     ![image](https://github.com/harvester/harvester/assets/2773781/b9e3b0cd-327b-4f16-ba6b-a675687124ed)
     </details>


1. Import Harvester and access it via Rancher
   * <details>
     <summary> Import Harvester and Access via Rancher :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/f3936d3f-ffd5-40d8-a28f-c74721d14e70)
     ![image](https://github.com/harvester/harvester/assets/2773781/4c1ee86c-c64d-498e-8fc9-c46b3e86124d)
     </details>

1. On Harvester, enable a PCI device [^2]
   * <details>
     <summary> Addon <b>pcidevices-controller</b> is enabled :heavy_check_mark: 
     </summary>
   
     Go to **Addons** -> **pcidevices-controller** -> **Enable**
     ![image](https://github.com/harvester/harvester/assets/2773781/809b7417-fbf6-486c-b08e-05abb0d6565e)
     </details>

   * <details>
     <summary> Enable a PCI device :heavy_check_mark: 
     </summary>
     
     go to **Addons** -> **pcidevices-controller** -> **Enable**
     ![image](https://github.com/harvester/harvester/assets/2773781/0cf03cff-fe3f-4b34-b47f-ce6e6a774c40)
     </details>


1. Create a VM
   * PCI Device list view should be visible :heavy_check_mark: 
   * The Enabled PCI device should be visible :heavy_check_mark:  
   ![image](https://github.com/harvester/harvester/assets/2773781/ce9e2a35-f6d8-40e1-bd7a-76f012d26b8c)
     


## Note
1. Both rancher **admin** and **standard user** are tested.
1. The PCI device used to test must be in the **iommuGroup** group or it can not be select.


[^1]: https://docs.harvesterhci.io/v1.2/advanced/addons/rancher-vcluster
[^2]: https://docs.harvesterhci.io/v1.2/advanced/addons/pcidevices
