### ISSUE TITLE
[BUG] rancher-system-agent keeps showing rke2 etcd-snapshot error log

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4803]
**Describe the bug**
Run `journalctl -u rancher-system-agent.service` in harvester node and we can see log like:

```
Dec 01 02:27:39 harvester-node-0 rancher-system-agent[15569]: time="2023-12-01T02:27:39Z" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
Dec 01 02:27:39 harvester-node-0 rancher-system-agent[15569]: time="2023-12-01T02:27:39Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 127"
```

The root cause is that the system can't find `rke2` command. The `rke2` binary is under `/opt/rke2/bin`.

**To Reproduce**
Install harvester and we can see it on each node.

**Expected behavior**
There is not error log in rancher-system-agent.

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Comment by TachunLin** [comment]
Verified **fixed** on `master-d3dc81ca-head` (24/01/03) . Close this issue.

### Result
- [x] On three node Harvester, each node did not have error log in `rancher-system-agent` service and the `rke2` binary is under `/opt/rke2/bin`.

    <details><summary>Test Result $~~$ $\color{green}{\textsf{PASS}}$ </summary>
    No error log in rke2-system-agent service 
     
    ```
    Jan 03 09:08:52 node1 rancher-system-agent[18014]: time="2024-01-03T09:08:52Z" level=info msg="[Applyinator] Running command: sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null]"
    Jan 03 09:08:52 node1 rancher-system-agent[18014]: time="2024-01-03T09:08:52Z" level=info msg="[b6fea2580dc36f38bb76a75802199f68e0604eeeacfd10bea135281e1d64327d_0:stdout]: Name Location Size Created"
    Jan 03 09:08:52 node1 rancher-system-agent[18014]: time="2024-01-03T09:08:52Z" level=info msg="[Applyinator] Command sh [-c rke2 etcd-snapshot list --etcd-s3=false 2>/dev/null] finished with err: <nil> and exit code: 0"
    ```

    The `rke2` binary is under `/opt/rke2/bin` of each node
    ```
    rancher@node1:~> ls -ltr /opt/rke2/bin
    total 85892
    -rwxr-xr-x 1 root root     3299 Dec  5 20:58 rke2-killall.sh
    -rwxr-xr-x 1 root root 87941448 Dec  5 21:13 rke2
    -rwxr-xr-x 1 root root     4082 Jan  3 08:58 rke2-uninstall.sh
    
    rancher@node2:~>  ls -ltr /opt/rke2/bin
    total 85892
    -rwxr-xr-x 1 root root     3299 Dec  5 20:58 rke2-killall.sh
    -rwxr-xr-x 1 root root 87941448 Dec  5 21:13 rke2
    -rwxr-xr-x 1 root root     4082 Jan  3 10:24 rke2-uninstall.sh
    
    rancher@node3:~> ls -ltr /opt/rke2/bin
    total 85892
    -rwxr-xr-x 1 root root     3299 Dec  5 20:58 rke2-killall.sh
    -rwxr-xr-x 1 root root 87941448 Dec  5 21:13 rke2
    -rwxr-xr-x 1 root root     4082 Jan  3 10:25 rke2-uninstall.sh
    
    ```

    </details>


### Test Information
* Test Environment: 3 nodes harvester on baremetal machines
* Harvester version: `master-d3dc81ca-head` (24/01/03)

### Verify Steps
<details><summary>Execution Steps</summary>

  1. Prepare 3 nodes Harvester cluster
  2. Check the `rke2` file is under `/opt/rke2/bin` 
  3. Check the rancher-system-agent log
  ```
  journalctl -u rancher-system-agent.service
  ```

</details>
