### ISSUE TITLE
[BUG] Download backing image failed with HTTP 502 error if Storage Network configured

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4807]
## Describe the bug (🐛 if you encounter this issue)
If the Storage Network is configured, downloading backing image will fail with `HTTP 502 error`, and LH manager appears error message `http: proxy error: dial tcp xxxxx:8001: i/o timeout` 

## To Reproduce
Steps:
- Creating Harvester cluster (single node is sufficient)
- Uploading an image to Harvester
- Enable Storage Network
- Download the image from Harvester UI

Result:
- Backing image download will fail with `HTTP 502 error`

## Expected behavior
Backing image download success

## Environment

 - Longhorn version: v1.4.3
 - Harvester version: v1.2.1

## Some LH source code observation
It's brought by LH manager tries to access backing-image-manager via URL from Storage-Network, but LH manager pods itself are not included in Storage-Network, following are the details:
- As LH manager receives download request, it gets the target backing image manager pod address by [gRPC PrepareDownload](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/api/forwarder.go#L253)
- Backing image manager server [response with the address of Storage-Network URL](https://github.com/longhorn/backing-image-manager/blob/00de674e0c86ecea5e65464bafc807c3b17c94d6/pkg/util/http_util.go#L61-L73)
- LH manager [forwards the request to backing image manager](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/api/forwarder.go#L214-L218) with the retrieved address, however, it's not accessible from LH manager

I've tried to [have modifications to LH manager](https://github.com/WebberHuang1118/longhorn-manager/tree/v1.4.3_bi_download) (force access backing image manager with pod IP) and updated it to my environment, the image could be downloaded during Storage-Network configured.

**Comment by WebberHuang1118** [comment]
The solution should be tracked on [LH issue #7326](https://github.com/longhorn/longhorn/issues/7236)

**Comment by irishgordo** [comment]
@WebberHuang1118  thanks for reporting this. I do have a 192.168.14.0/24 network configured as a storage-network for a 2 node bare-metal v1.2.1 Harvester cluster and attempted to reproduce this.
I'm not able to.
As I'm able to download the image from a file-server that the 14.0/24 network can communicate out to (and others) and not encounter the issue of that backing-image running into things.
I also am able to use that image in a VM - and validate that the replicas in longhorn have the corresponding Storage IPs I can see from the switch level on my network.

https://github.com/harvester/harvester/assets/5370752/29ea73c5-6c09-4635-bccb-528c8814c951

**Comment by WebberHuang1118** [comment]
> @WebberHuang1118 thanks for reporting this. I do have a 192.168.14.0/24 network configured as a storage-network for a 2 node bare-metal v1.2.1 Harvester cluster and attempted to reproduce this. I'm not able to. As I'm able to download the image from a file-server that the 14.0/24 network can communicate out to (and others) and not encounter the issue of that backing-image running into things. I also am able to use that image in a VM - and validate that the replicas in longhorn have the corresponding Storage IPs I can see from the switch level on my network.
> 
>  test4807.mp4

@irishgordo This issue is about **downloading an existing image from Harvester to local** rather than fetching an image to Harvester from a particular URL. Sometimes, the context is a little confusing, thanks for your verification :)

**Comment by bk201** [comment]
Tentative 1.3.0, if https://github.com/longhorn/longhorn/issues/7236 can't make it we move to the next milestone.

**Comment by WebberHuang1118** [comment]
Wating for LH v1.5.4

**Comment by WebberHuang1118** [comment]
LH PR https://github.com/longhorn/backing-image-manager/pull/151 is merged.
We can re-verify as Harvester bump LH to v1.6.0

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.3.0-rc1** with Longhorn **v1.6.0-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Follow **Steps** in https://github.com/harvester/harvester/issues/4807#issue-2022925151
