### ISSUE TITLE
[BUG]The prompt on the screen is not fully displayed in installation mode

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#481]
**Describe the bug**
The prompt on the screen is not fully displayed in installation mode

**To Reproduce**
1. In the installation mode, fill in something incorrect
2. See the prompt

**Expected behavior**
The prompt should be displayed correctly

**Result**
Part of the prompt is not displaying on the screen
![image](https://user-images.githubusercontent.com/57614736/108829371-0ec98780-7603-11eb-9049-7ad7b1ba68a8.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by kingsd041** [comment]
Version master-621eedd7-head has been fixed

![image](https://user-images.githubusercontent.com/19684717/113992132-b930fd80-9885-11eb-9a12-5d5153f49373.png)
