### ISSUE TITLE
[Doc] storage_class.replica_count is not available for v1.1

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#4810]
**Is your doc request related to a problem? Please describe or add related issue ID.**
Installer PR: https://github.com/harvester/harvester-installer/pull/402
Doc PR: https://github.com/harvester/docs/pull/301

**Describe the solution you'd like**
Tested on `v1.1.3-rc1` that `storage_class.replica_count` could **_NOT_** be injected via additional config file (`configurl`), but it's available for `v1.2`, so the feature might be mis-documented.

**Comment by lanfon72** [comment]
@harvesterhci-io-github-bot don't close my issue :crying_cat_face:

**Comment by w13915984028** [comment]
From the source code, the option is available on v1.2 and later

 https://github.com/harvester/harvester-installer/blob/3b0b2164b4630b5e110e5f9d40bd6a7f92bd3bbb/pkg/config/config.go#L124;  
 
 but not in v1.1 
 
 https://github.com/harvester/harvester-installer/blob/ff881353e87c6263ef92fb58ae7536a24d93ddf0/pkg/config/config.go#L102

Seems the document of v1.1 was mis-typed.

**Comment by w13915984028** [comment]
Document was updated.
