### ISSUE TITLE
[BUG] LoadBalancer allows Listeners whose ports conflict with host ports

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4815]
**Describe the bug**

Harvester allows adding/editing Listeners to a LoadBalancer that conflict with ports on the host, which results in the LoadBalancer sending the connection to the Node and not the target workload.

<img width="1365" alt="Screenshot 2023-12-04 at 4 44 52 PM" src="https://github.com/harvester/harvester/assets/5227338/83161a17-d224-4240-88b2-4f8267fc49df">

For example, after trying to SSH to the address specified in the LoadBalancer (login fails), if I SSH to the node where the VM is located on, my SSH client tells me that the Harvester node is also identified by that fingerprint at the LoadBalancer IP.

The SSH fingerprint should be that of the VM that the LoadBalancer should relay the connection to.

```
$ ssh rancher@192.168.88.181
The authenticity of host '192.168.88.181 (192.168.88.181)' can't be established.
ED25519 key fingerprint is SHA256:bNDQ416xdz1PZSuN0H3C88KU+YLWwu6NsqJ3DsNRrcg.
This host key is known by the following other names/addresses:
    ~/.ssh/known_hosts:165: 192.168.88.3
Are you sure you want to continue connecting (yes/no/[fingerprint])? no
```

**To Reproduce**
1. Go to **Networks** > **Load Balancers**
2. Create LoadBalancer
3. Add a Listener whose port conflicts with that of the host (i.e., 22)
4. Attempt to reach the workload service on that port

**Expected behavior**

Backend validates and rejects this request.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Minisforum UM480XT

**Additional context**

| ⚠️  | Workaround is to just use an unused port, like 2222 |
| - | - |

**Comment by starbops** [comment]
This looks like a security issue to me. Did you mean you tried to SSH to the load balancer IP address, but it connected to the node's port 22?

I'm unable to reproduce that. Please let me know if any of my steps were wrong/different from yours. Thank you.

1. Prepare a Harvester v1.2.1 cluster
2. Create a VM
3. Create an IPPool object
4. Create a VM workload-type LoadBalancer object with pool IPAM, SSH port 22 listener, and associated with the created VM
5. Try to SSH to the IP address allocated for the LB (entering the VM's shell)
6. Try to SSH to the node's IP address (entering the node's shell)

**Comment by connorkuehl** [comment]
> This looks like a security issue to me. Did you mean you tried to SSH to the load balancer IP address, but it connected to the node's port 22?

Yeah, with the intended result of SSH'ing into the VM.

> I'm unable to reproduce that. Please let me know if any of my steps were wrong/different from yours. Thank you.
> 
>     1. Prepare a Harvester v1.2.1 cluster
> 
>     2. Create a VM
> 
>     3. Create an IPPool object
> 
>     4. Create a VM workload-type LoadBalancer object with pool IPAM, SSH port 22 listener, and associated with the created VM
> 
>     5. Try to SSH to the IP address allocated for the LB (entering the VM's shell)
> 
>     6. Try to SSH to the node's IP address (entering the node's shell)

These steps appear identical to mine :thinking: I'll try to reproduce in the team's lab instead of my homelab.

**Comment by starbops** [comment]
Hi @connorkuehl Could you please let me know if you had a chance to reproduce it? Thank you.

**Comment by connorkuehl** [comment]
No, I was unable to. I'll re-open if it ever comes up again.
