### ISSUE TITLE
[ENHANCEMENT] Support creating placeholder LoadBalancer objects without the need to pre-fill backend server information

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#4821]
**Is your enhancement related to a problem? Please describe.**

Creating a new load balancer without filling the backend server information will result in rejection by the admission webhook with the reason `admission webhook "validator.harvester-system.harvester-load-balancer-webhook" denied the request: Internal error occurred: create load balancer default/test-vm-ssh failed: no virtual machine instance matched`.

<img width="1392" alt="image" src="https://github.com/harvester/harvester/assets/1827717/25cd003e-0c39-4c9a-8f16-dc6697be5f2f">

Or forge a selector to a non-existent VM:

<img width="1392" alt="image" src="https://github.com/harvester/harvester/assets/1827717/dcf09df6-5e35-4248-af33-2baa8b9c4bcd">

There are times that we need to pre-create a load balancer before actually spin up the VMs. We should consider to allow this kind of usage just like we can create Services without any backend Pods.

**Describe the solution you'd like**

Adjust the validator to let placeholder to pass. And the reconciliation logic needs to adapt, too. Skip the creation of the EndpointSlice object. Only create it when the backend VMs that match the selector become available (in later reconcile loops).

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
Test plan (Harvester ISO should be built after 2024.08.30):

Create one LB which has a selector, but the target VM is never created, or VM is ever there but stopped/removed, the LB can detect those correctly. The pre-existing of at least one VM is removed, but the LB still should have a selector.

When IP pool has no free IPs/DHCP fail to allocate IP for this LB, LB is `Not Ready`
When no backend server, LB is `Not Ready`
When all backend servers are down, LB is `Not Ready`
When none of the backed servers is health checked as active, LB is `Not Ready`

When an active backend server is up, LB changes to `Ready`.

Refer: https://github.com/harvester/load-balancer-harvester/pull/31#issue-2387926834

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-dev-20240918**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create load balance `lb1` with name and listeners
3. LB `lb1` should able to be created and showing `Not Ready` state
4. Create an IP Pool `pool1` and update `lb1` to use the IP Pool
5. LB `lb1` should be updated and showing IP address accordingly but state will keep in `Not Ready` with message **No running backend servers**
6. Create an image for VM creation
7. Create VM `vm1` with label `vmGroup: vmt`
8. Clone `vm1` into `vm2`
9. Update LB `lb1` with backend server select `vmGroup: vmt`
10. LB `lb1` should be updated and showing `Active` state
11. Stop `vm1` and `vm2`, the LB `lb1` should be updated and showing `Not Ready` state
12. Start `vm2`, the LB `lb1` should be updated and showing `Active` state
