### ISSUE TITLE
[TASK] v1.1.3-rc2 tasks

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4829]
- Installer:
  - [x] Bump OS @Vicente-Cheng https://github.com/harvester/harvester-installer/pull/610
- Base image bump (new tag or re-tag)
  - [x] [docker.io/rancher/harvester-network-controller:v0.3.5](http://docker.io/rancher/harvester-network-controller:v0.3.5) @starbops  (re-tag)
  - [x] [docker.io/rancher/harvester-node-disk-manager:v0.5.2](http://docker.io/rancher/harvester-node-disk-manager:v0.5.2) @Vicente-Cheng (re-tag)
  - [x] [docker.io/rancher/harvester-node-manager:v0.1.8](http://docker.io/rancher/harvester-node-manager:v0.1.8) @Vicente-Cheng (re-tag)
  - [x] [docker.io/rancher/harvester-pcidevices:v0.2.6](http://docker.io/rancher/harvester-pcidevices:v0.2.6) @bk201 (re-tag) 
  - [x] [docker.io/rancher/harvester-vm-import-controller:v0.1.6](http://docker.io/rancher/harvester-vm-import-controller:v0.1.6) @bk201 (re-tag)
  - [x] [docker.io/rancher/support-bundle-kit:v0.0.32](http://docker.io/rancher/support-bundle-kit:v0.0.32) @bk201, fixed in rancher/support-bundle-kit:v0.0.33
- [x] UI tag [v1.1.3-rc2](https://github.com/harvester/dashboard/releases/tag/v1.1.3-rc2)
- [x] Installer tag  ([v1.1.3-rc2](https://github.com/harvester/harvester-installer/releases/tag/v1.1.3-rc2))
 - [x] Bump Images in values.yaml https://github.com/harvester/harvester/pull/4838
 - [x] Release PR https://github.com/harvester/harvester/pull/4841

**Comment by Vicente-Cheng** [comment]
Update my side:
harvester-node-manager:v0.1.8
```
# docker run --rm  neuvector/scanner -i rancher/harvester-node-manager:v0.1.8
2023-12-06T16:51:01.366|INFO|SCN|container.Connect: - endpoint=unix:///var/run/docker.sock
2023-12-06T16:51:01.366|INFO|SCN|common.LoadCveDb: Expand new DB - version=3.277
Image: https://registry.hub.docker.comrancher/harvester-node-manager:v0.1.8
Base OS: sles:15.4
Created at: 2023-12-06T16:48:26Z

Vulnerabilities: 0, HIGH: 0, MEDIUM: 0, LOW: 0, UNKNOWN: 0
```

**Comment by bk201** [comment]
Bump SBK, the rest images are re-tagged thus no need to change. https://github.com/harvester/harvester/pull/4838

**Comment by bk201** [comment]
Close since rc2 is out.
