### ISSUE TITLE
[BUG] Upgrade three nodes Harvester from v1.1.2 to v1.1.3-rc1 until v1.2.1 stuck in `Pre-draining` on the last node 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#4830]
**Describe the bug**

When upgrade the three nodes Harvester cluster on baremetal machine from v1.1.2 -> v1.1.3-rc1 then upgrade to v1.2.1
The upgrade process stuck at the last node `Pre-draining` state. 

And the last node stays in `Cordened` state
![image](https://github.com/harvester/harvester/assets/29251855/a3623365-3b01-46c7-b532-1c20dd610ce9)

Checked the pre-drain log, it keeps looping in `waiting for volume to be ready`
  ```
  + sleep 10                                                                                                                                                 │
  │ + '[' true ']'                                                                                                                                             │
  │ + '[' 3 -gt 2 ']'                                                                                                                                          │
  │ ++ kubectl get volumes.longhorn.io/pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 -n longhorn-system -o 'jsonpath={.status.robustness}'                          │
  │ + robustness=degraded                                                                                                                                      │
  │ Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...                                                                               │
  │ + '[' degraded = healthy ']'                                                                                                                               │
  │ + '[' -f /tmp/skip-pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 ']'                                                                                            │
  │ + echo 'Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...'                                                                      │
  │ + sleep 10                                                                                                                                                 │
  │ + '[' true ']'                                                                                                                                             │
  │ + '[' 3 -gt 2 ']'                                                                                                                                          │
  │ ++ kubectl get volumes.longhorn.io/pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 -n longhorn-system -o 'jsonpath={.status.robustness}'                          │
  │ + robustness=degraded                                                                                                                                      │
  │ + '[' degraded = healthy ']'                                                                                                                               │
  │ + '[' -f /tmp/skip-pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 ']'                                                                                            │
  │ + echo 'Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...'                                                                      │
  │ Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...                                                                               │
  │ + sleep 10                                                                                                                                                 │
  │ + '[' true ']'                                                                                                                                             │
  │ + '[' 3 -gt 2 ']'                                                                                                                                          │
  │ ++ kubectl get volumes.longhorn.io/pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 -n longhorn-system -o 'jsonpath={.status.robustness}'                          │
  │ + robustness=degraded                                                                                                                                      │
  │ + '[' degraded = healthy ']'                                                                                                                               │
  │ + '[' -f /tmp/skip-pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 ']'                                                                                            │
  │ + echo 'Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...'                                                                      │
  │ + sleep 10                                                                                                                                                 │
  │ Waiting for volume pvc-566fe4bb-0774-43e3-bf8d-434f4e193e10 to be healthy...      
  ``` 

* The initial check indicate all the volumes are rebuilding 
https://172.19.108.0/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/volume

![image](https://github.com/harvester/harvester/assets/29251855/b119f769-d619-463b-a840-f07285f2d4ad)

**To Reproduce**
1. Prepare a three nodes Harvester v1.1.2 cluster
2. Create two virtual machines, one in running and another in stopped state
3. Prepare offline upgrade to v1.1.3-rc1 
4. After upgraded to v1.1.3-rc1
5. Use the upgrade responder to upgrade to v1.2.1
6. Check the upgrade status

**Expected behavior**

Can upgrade correctly on three nodes Harvester cluster from v1.1.2 to v1.1.3-rc1 until v1.2.1 smoothly without stuck

**Support bundle**

[supportbundle_3d4547ed-40b6-426a-ac04-163c2e8fa6df_2023-12-06T11-12-17Z.zip](https://github.com/harvester/harvester/files/13581734/supportbundle_3d4547ed-40b6-426a-ac04-163c2e8fa6df_2023-12-06T11-12-17Z.zip)

**Environment**
 - Harvester ISO version: v1.1.2, v1.1.3-rc1 and v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): three nodes baremetal machines

**Additional context**
* Upgrade log exceed the 10MB attachment limitation, would provide in the internal discussion thread.

**Comment by khushboo-rancher** [comment]
Longhorn CSI plugin was in `crashloop` in the setup that's why the volumes were unable to rebuild. On force deleting the pod, it got recreated successfully. I was able to see the rebuilding getting successful on the setup. 

However I deleted the longhorn-manager pods on the cordened node and other node accidentally and it messed up the setup.

If anyone encounters the reported issue, they can try to delete the CSI-plugin pod as a work around.

**Comment by Vicente-Cheng** [comment]
Thanks @khushboo-rancher, 

I also checked the SB and live environment last week. (Sorry, I forgot to update)
The rebuild failed because of the unhealthy CSI plugin. (rebuild needs to take snapshot first, and the unhealthy csi plugin can not handle it)

The CSI plugin failed might be because of the following logs: (This CSI plugin repeated fail, this is the latest log)
```
time="2023-12-06T11:10:20Z" level=fatal msg="Error starting CSI manager: Failed to initialize Longhorn API client: Get \"http://longhorn-backend:9500/v1\": dial tcp 10.53.87.75:9500: i/o timeout (Client.Timeout exceeded while awaiting headers)"
```

**Comment by TachunLin** [comment]
We tried on the the same baremetal machine environment and the steps
Then follow the upgrade path from v1.1.2 to `v1.1.3-rc2` until `v1.2.1`
 
After successfully upgraded to `v1.1.3-rc2`, and proceed to upgrade to `v1.2.1`

* The upgrade dashboard prompt the message to prevent trigger the next upgrade 
    ```
    admission webhook "validator.harvesterhci.io" denied the request: managed chart rancher-logging is not ready, please wait for it to be ready
    ```
    ![image](https://github.com/harvester/harvester/assets/29251855/6bdcb45c-fb00-4c63-bd6b-dbc55ec3e7d9)

* Check in the K9s indicate the `rancher-monitoring` and `rancher-logging` chart are in `pending-upgrade` status
![image](https://github.com/harvester/harvester/assets/29251855/e2e95b8e-16e8-4f5d-a57d-c3edb47f6cef)


Attached the support bundle for more information. 
[113rc2-112-monitoring-chart_2023-12-11T14-08-50Z.zip](https://github.com/harvester/harvester/files/13637225/113rc2-112-monitoring-chart_2023-12-11T14-08-50Z.zip)

Not sure whether we encounter a new or existing issue and any workaround we can use to proceed the upgrade to v1.2.1.

**Comment by TachunLin** [comment]
After adopting the [workaround solution](https://docs.harvesterhci.io/v1.2/upgrade/v1-1-to-v1-1-2#4-after-an-upgrade-a-fleet-bundles-status-is-errapplied1-cluster-fleet-locallocal-another-operation-installupgraderollback-is-in-progress) to rollback the problematic chart `rancher-logging`. 
We can proceed to upgrade from `v1.1.3-rc2` to `v1.2.1`. 

In this test, the upgrade process also stuck in the `Pre-draining` on the last node
![image](https://github.com/harvester/harvester/assets/29251855/0816d1d0-4fce-46af-b475-33b87b47405e)

Checking the csi-plugin is running on each node 
![image](https://github.com/harvester/harvester/assets/29251855/2de052ff-1980-40ce-ab92-decfc17903e2)

Attached the upgrade log and support bundle for more information:
* Upgrade log 
[113rc2-112-pre-drained-stuck-upgradelog-archive-2023-12-12T04-26-47Z.zip](https://github.com/harvester/harvester/files/13644643/113rc2-112-pre-drained-stuck-upgradelog-archive-2023-12-12T04-26-47Z.zip)

* Support bundle 
[supportbundle_7ac6c32e-222c-4a40-8a7b-84fcafa473f4_2023-12-12T04-28-27Z.zip](https://github.com/harvester/harvester/files/13644644/supportbundle_7ac6c32e-222c-4a40-8a7b-84fcafa473f4_2023-12-12T04-28-27Z.zip)

**Comment by TachunLin** [comment]
Tested on the latest Harvester `v1.1.3-rc3`. 
On both two and three nodes cluster upgrade test scenario from v1.1.2 to v1.1.3-rc3 until v1.2.1

* We can completely upgrade the two nodes Harvester (one joined after v1.1.3-rc3) to v1.2.1
![image](https://github.com/harvester/harvester/assets/29251855/3ba090b2-a986-4d5a-bbdd-7e2256400a08)

* We can also upgrade the three nodes Harvester to v1.2.1 smoothly
![image](https://github.com/harvester/harvester/assets/29251855/45364327-1f51-44ff-b9a7-306060e9b911)


**Environment**
 - Harvester ISO version: `v1.1.2`, `v1.1.3-rc3` and `v1.2.1`
 - Underlying Infrastructure: two and three nodes baremetal machines
 - Rancher version: v2.7.9 

**Reproduce steps**
Two nodes
1. Prepare a single node v1.1.2 Harvester
2. Upgrade to v1.1.3-rc3
3. Join the second node to Harvester cluster
4. Import Rancher v2.7.9 
5. Provision the RKE2 v1.24.14 cluster
6. Upgrade to v1.2.1

Three nodes
1. Prepare a three nodes v1.1.2 Harvester
2. Create two VMs
3. Upgrade to v1.1.3-rc3
4. Upgrade to v1.2.1
