### ISSUE TITLE
[ENHANCEMENT] Use generalJob image in promote jobs

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4839]
**Is your enhancement related to a problem? Please describe.**

The promote jobs use busybox images: https://github.com/harvester/harvester/blob/01417955824dbea8d6e3a22bc0d7caad77915973/pkg/controller/master/node/promote_controller.go#L48

**Describe the solution you'd like**

We can use the general job image: https://github.com/harvester/harvester/blob/01417955824dbea8d6e3a22bc0d7caad77915973/deploy/charts/harvester/values.yaml#L488

This can reduce 1 image dependency. It would be nice to check if we have other components that depend on the image too.

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20231222`, close as fixed.


## Environment
* Harvester
 * Version: `v1.3.0-dev-20231222`
 * Profile: QEMU/KVM, 3 nodes (8C/16,12,16/500G)
 * ui-source: `Auto`


## Steps 
1. <details>
     <summary> Provision 2 nodes Harvester cluster
     </summary>
 
     ![image](https://github.com/harvester/ipxe-examples/assets/2773781/54190777-07e3-4332-9cca-89a434de0899)
   </details>
   
   
2. Join node2 (3rd node)
   * <details open>
       <summary> Job <b>harvester-promote-harvester-node-1</b> uses <code>bci-base:15.5</code> image :ballot_box_with_check: 
       </summary>
 
       ![image](https://github.com/harvester/harvester/assets/2773781/26ab10fb-d2df-4aa6-8ca1-1657ffc93ee1)
     </details>

   * <details open>
       <summary> Job <b>harvester-promote-harvester-node-2</b> uses <code>bci-base:15.5</code> image :ballot_box_with_check: 
       </summary>
 
       ![image](https://github.com/harvester/harvester/assets/2773781/4be4acc8-ca01-4a70-8ae5-db6790b2bfdc)
     </details>

   * <details open>
       <summary> Promote jobs complete :ballot_box_with_check: 
       </summary>
 
       ![image](https://github.com/harvester/harvester/assets/2773781/5914fbeb-2fe8-4f3d-8d32-44c661ef79a9)
     </details>
