### ISSUE TITLE
[ENHANCEMENT] various witness mode related enhancement

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4840]
**Is your enhancement related to a problem? Please describe.**
We will introduce the witness mode support in v1.3 sprint release.
This issue will be used to record anything we need to improve. 

**Describe the solution you'd like**
Will be described individually on below

**Describe alternatives you've considered**
None

**Additional context**

Related to the original issue: https://github.com/harvester/harvester/issues/3266

**UI enhancement**
We saw the following figures. It needs to do some specific handling with that.

- [x]  node-2 is the `etcd` node, it should not show cordon here. 
<img width="1676" alt="Screenshot 2023-12-07 at 6 36 31 PM" src="https://github.com/harvester/harvester/assets/1615081/7851cafd-32ce-4df2-9553-cf75e37cda1a">

- [x] role should not be compute node
<img width="1195" alt="Screenshot 2023-12-07 at 6 39 18 PM" src="https://github.com/harvester/harvester/assets/1615081/1ea56c05-dbe8-4bd8-bb36-10de44416a8b">

**Backend related enhancement**
- [x] Should use exact match on the promote.sh for checking the etcd role
reference: https://github.com/harvester/harvester/pull/4781#discussion_r1418836758

- [x] Add the limitation for only one etcd node to be promoted (for promote-controller).
We need to make sure the kube-apiserver is good. Two etcd nodes currently would make some trouble for it.

- [x] Kick the witness node out of Longhorn nodes; it cannot be scheduled. (For longhorn UI issue: https://github.com/longhorn/longhorn/issues/7450)

- [x] Add unittest for promote-controller

**Document enhancement**
- [ ] Write the document for this feature and its limitation

**Comment by bk201** [comment]
<img width="1880" alt="截圖 2023-12-22 晚上8 05 38" src="https://github.com/harvester/harvester/assets/1691518/3be081a4-e4ce-4a7d-b66f-41adfdb3cc70">
The Longhorn GUI also displays the etcd node down. We might need to create a ticket in Longhorn.

**Comment by Vicente-Cheng** [comment]
> The Longhorn GUI also displays the etcd node down. We might need to create a ticket in Longhorn.

~Opened the longhorn issue: https://github.com/longhorn/longhorn/issues/7450~

Update another ToDo item for this case

**Comment by torchiaf** [comment]
@Vicente-Cheng what would be the status and the role labels for witness nodes ?

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng what would be the status and the role labels for witness nodes ?

We define the specific label for this `etcd` node role.
`node-role.harvesterhci.io/etcd=true`

And what do you mean by the status? I do not really understand. Could you elaborate more?

**Comment by torchiaf** [comment]
Based on offline discussion, We decide to assign 'Active' status and 'Etcd Node' role to witness (Etcd) nodes @bk201

**Comment by torchiaf** [comment]
Reopen for QA.

**Comment by albinsun** [comment]
Witness feature is testing with #3226.
Enhancements mentioned in this ticket are verified, close this first.
