### ISSUE TITLE
[ENHANCEMENT] Pull images from local distributed registries

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4842]
**Is your enhancement related to a problem? Please describe.**

We currently do image-preloading during the installation stage, which is time consuming and nodes might contain non-needed images.

**Describe the solution you'd like**

We can leverage distributed registries like https://github.com/XenitAB/spegel to speed up the image preloading or only pull images when they are needed. This could speed up node join and upgrades.
(k3s PR: https://github.com/k3s-io/k3s/pull/8977)

**Describe alternatives you've considered**

**Additional context**

- need to pay attention to image availability. Not every cluster has Internet connection.

**Comment by innobead** [comment]
In favor of https://github.com/harvester/harvester/issues/6188.
