### ISSUE TITLE
[Question] mcc-harvester bundle shows modified

### ISSUE THREAD

**Issue by prashantgnet** [harvester/harvester#4845]
mcc-harvester bundle shows modified since we applied patch "prometheus-longhorn-rules" prometheus rule.

We would like to run upgrade from v1.1.2 to v1.2.1 but check.sh is shows mcc-harvester is not ready since it's status is modified.

So how to revert back mcc-harvester bundle to original state?

Thanks a lot.

**Comment by connorkuehl** [comment]
Please share the output of

```
# kubectl get bundle mcc-harvester -n fleet-local -o yaml
```

It's a lot of output but we can help parse it here. If I recall correctly, there's usually a "patch" field buried in that output that describes what modifications have to be done to revert it back to stock.

**Comment by w13915984028** [comment]
Please follow below example to add related resource path to `ManagedChart` CRD object `harvester` (use `kubectl edit managedchart harvester -n ...`), wait a while, the complain will be gone.

```
    diff:
      comparePatches:
```

https://github.com/harvester/harvester-installer/blob/992750c810dc050d7811b2ce4e5fa1f98f5ce999/pkg/config/templates/rancherd-10-harvester.yaml#L80

**Comment by prashantgnet** [comment]
Hello [connorkuehl](https://github.com/connorkuehl)

Yes, you are right we applied patch for Prometheus Rule named "prometheus-longhorn-rules" under "longhorn-system" namespace, basically we increased the threshold value from 70% to 90% for few rules.

As you mentioned "kubectl get bundle mcc-harvester -n fleet-local -o yaml" output is too long so I just grab following patch portion, hope that is helpful. Let me know in case additional details are required. 

>   summary:
    desiredReady: 1
    modified: 1
    nonReadyResources:
    - bundleState: Modified
      modifiedStatus:
      - apiVersion: monitoring.coreos.com/v1
        kind: PrometheusRule
        name: prometheus-longhorn-rules
        namespace: longhorn-system
        patch: '{"spec":{"groups":[{"name":"longhorn.rules","rules":[{"alert":"LonghornVolumeActualSpaceUsedWarning","annotations":{"description":"The
          actual space used by Longhorn volume on node is at 90% capacity for more
          than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The
          actual used space of Longhorn volume is over 90% of the capacity."},"expr":"(longhorn_volume_actual_size_bytes
          / longhorn_volume_capacity_bytes) * 100 \u003e 90","for":"5m","labels":{"issue":"The
          actual used space of Longhorn volume on is high.","severity":"warning"}},{"alert":"LonghornVolumeStatusCritical","annotations":{"description":"Longhorn
          volume on is Fault for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn
          volume is Fault"},"expr":"longhorn_volume_robustness == 3","for":"5m","labels":{"issue":"Longhorn
          volume  is Fault.","severity":"critical"}},{"alert":"LonghornVolumeStatusWarning","annotations":{"description":"Longhorn
          volume is Degraded for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn
          volume is Degraded"},"expr":"longhorn_volume_robustness == 2","for":"5m","labels":{"issue":"Longhorn
          volume is Degraded.","severity":"warning"}},{"alert":"LonghornNodeStorageWarning","annotations":{"description":"The
          used storage of node is at 70% capacity for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The
          used storage of node is over 70% of the capacity."},"expr":"(longhorn_node_storage_usage_bytes
          / longhorn_node_storage_capacity_bytes) * 100 \u003e 70","for":"5m","labels":{"issue":"The
          used storage of node is high.","severity":"warning"}},{"alert":"LonghornDiskStorageWarning","annotations":{"description":"The
          used storage of disk is at 70% capacity for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The
          used storage of disk is over 70% of the capacity."},"expr":"(longhorn_disk_usage_bytes
          / longhorn_disk_capacity_bytes) * 100 \u003e 70","for":"5m","labels":{"issue":"The
          used storage of disk on node is high.","severity":"warning"}},{"alert":"LonghornNodeDown","annotations":{"description":"There
          are Longhorn nodes which have been offline for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn
          nodes is offline"},"expr":"(avg(longhorn_node_count_total) or on() vector(0))
          - (count(longhorn_node_status{condition=\"ready\"} == 1) or on() vector(0))
          \u003e 0","for":"5m","labels":{"issue":"There are Longhorn nodes are offline","severity":"critical"}},{"alert":"LonghornIntanceManagerCPUUsageWarning","annotations":{"description":"Longhorn
          instance manager has CPU Usage / CPU request is over 300% for more than
          5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn
          instance manager has CPU Usage / CPU request is over 300%."},"expr":"(longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu)
          * 100 \u003e 300","for":"5m","labels":{"issue":"Longhorn instance manager
          on consumes 3 times the CPU request.","severity":"warning"}},{"alert":"LonghornNodeCPUUsageWarning","annotations":{"description":"Longhorn
          node has CPU Usage / CPU capacity is over 90% for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn
          node experiences high CPU pressure for more than 5m."},"expr":"(longhorn_node_cpu_usage_millicpu
          / longhorn_node_cpu_capacity_millicpu) * 100 \u003e 90","for":"5m","labels":{"issue":"Longhorn
          node experiences high CPU pressure.","severity":"warning"}}]}]}}'
      name: fleet-local/local
    ready: 0
  unavailable: 0
  unavailablePartitions: 0

kubectl get bundle -A 

>  NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; prometheusrule.monitoring.coreos.com longhorn-system/prometheus-longhorn-rules modified {"spec":{"groups":[{"name":"longhorn.rules","rules":[{"alert":"LonghornVolumeActualSpaceUsedWarning","annotations":{"description":"The actual space used by Longhorn volume on node is at 90% capacity for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The actual used space of Longhorn volume is over 90% of the capacity."},"expr":"(longhorn_volume_actual_size_bytes / longhorn_volume_capacity_bytes) * 100 \u003e 90","for":"5m","labels":{"issue":"The actual used space of Longhorn volume on is high.","severity":"warning"}},{"alert":"LonghornVolumeStatusCritical","annotations":{"description":"Longhorn volume on is Fault for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn volume is Fault"},"expr":"longhorn_volume_robustness == 3","for":"5m","labels":{"issue":"Longhorn volume  is Fault.","severity":"critical"}},{"alert":"LonghornVolumeStatusWarning","annotations":{"description":"Longhorn volume is Degraded for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn volume is Degraded"},"expr":"longhorn_volume_robustness == 2","for":"5m","labels":{"issue":"Longhorn volume is Degraded.","severity":"warning"}},{"alert":"LonghornNodeStorageWarning","annotations":{"description":"The used storage of node is at 70% capacity for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The used storage of node is over 70% of the capacity."},"expr":"(longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 \u003e 70","for":"5m","labels":{"issue":"The used storage of node is high.","severity":"warning"}},{"alert":"LonghornDiskStorageWarning","annotations":{"description":"The used storage of disk is at 70% capacity for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"The used storage of disk is over 70% of the capacity."},"expr":"(longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 \u003e 70","for":"5m","labels":{"issue":"The used storage of disk on node is high.","severity":"warning"}},{"alert":"LonghornNodeDown","annotations":{"description":"There are Longhorn nodes which have been offline for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn nodes is offline"},"expr":"(avg(longhorn_node_count_total) or on() vector(0)) - (count(longhorn_node_status{condition=\"ready\"} == 1) or on() vector(0)) \u003e 0","for":"5m","labels":{"issue":"There are Longhorn nodes are offline","severity":"critical"}},{"alert":"LonghornIntanceManagerCPUUsageWarning","annotations":{"description":"Longhorn instance manager has CPU Usage / CPU request is over 300% for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn instance manager has CPU Usage / CPU request is over 300%."},"expr":"(longhorn_instance_manager_cpu_usage_millicpu/longhorn_instance_manager_cpu_requests_millicpu) * 100 \u003e 300","for":"5m","labels":{"issue":"Longhorn instance manager on consumes 3 times the CPU request.","severity":"warning"}},{"alert":"LonghornNodeCPUUsageWarning","annotations":{"description":"Longhorn node has CPU Usage / CPU capacity is over 90% for more than 5 minutes.","runbook_url":"https://longhorn.io/docs/1.3.0/monitoring/metrics/","summary":"Longhorn node experiences high CPU pressure for more than 5m."},"expr":"(longhorn_node_cpu_usage_millicpu / longhorn_node_cpu_capacity_millicpu) * 100 \u003e 90","for":"5m","labels":{"issue":"Longhorn node experiences high CPU pressure.","severity":"warning"}}]}]}}
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   1/1                       
fleet-local   mcc-rancher-logging                           1/1                       
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring                        1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1                       

patch files to identify resource  

> apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-longhorn-rules
  namespace: longhorn-system

JSON patch file

> [
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/3/expr",
    "value" : "(longhorn_node_storage_usage_bytes / longhorn_node_storage_capacity_bytes) * 100 > 90"
  },
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/3/annotations/description",
    "value" : "The used storage of node is at 90% capacity for more than 5 minutes"
  },
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/3/annotations/summary",
    "value" : "The used storage of node is over 90% of the capacity."
  },
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/4/expr",
    "value" : "(longhorn_disk_usage_bytes / longhorn_disk_capacity_bytes) * 100 > 90"
  },
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/4/annotations/description",
    "value" : "The used storage of disk is at 90% capacity for more than 5 minutes"
  },
  {
    "op" : "replace",
    "path" : "/spec/groups/0/rules/4/annotations/summary",
    "value" : "The used storage of disk is at 90% capacity."
  }
]

Command to apply patch

> kubectl patch --type json -f  resource.yaml --patch-file patch_file.yaml

Hope this helps!

Thanks for looking into it.

**Comment by prashantgnet** [comment]
Hello @w13915984028 

Thanks for sharing above details

I will try using example you mentioned.

Hope this is straightforward for our patches applied to Prometheus rule. 

Please share in case you have any example for modified Prometheus rule.

**Comment by prashantgnet** [comment]
Hello @w13915984028 

All the required entries are already present under harvester managed-chart, anything else to verify?

Thanks a lot.

> spec:
  chart: harvester
  defaultNamespace: harvester-system
  diff:
    comparePatches:
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: engineimages.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: nodes.longhorn.io
    - apiVersion: apiextensions.k8s.io/v1
      jsonPointers:
      - /status/acceptedNames
      - /status/conditions
      - /status/storedVersions
      kind: CustomResourceDefinition
      name: volumes.longhorn.io
    - apiVersion: storage.k8s.io/v1
      jsonPointers:
      - /metadata/annotations
      kind: StorageClass
      name: harvester-longhorn
    - apiVersion: storage.k8s.io/v1
      jsonPointers:
      - /metadata/annotations
      kind: StorageClass
      name: harvester-longhorn

**Comment by prashantgnet** [comment]
mcc-harvester bundle shows in ready state after adding following lines

> - apiVersion: monitoring.coreos.com/v1
      jsonPointers:
      - /spec
      - /status
      kind: PrometheusRule
      name: prometheus-longhorn-rules 

under following section

>  diff:
      comparePatches:

Still not sure how to identify path for a particular resource like how to identify spec and status are pointers for prometheus-rule? 

Thanks a lot once again for providing very useful hint.

**Comment by w13915984028** [comment]
@prashantgnet  That looks good. 

Regarding your further quetions, I try to answer it:

```
:~ # kubectl get managedchart -nfleet-local harvester -oyaml
apiVersion: management.cattle.io/v3
kind: ManagedChart

...
spec:
  chart: harvester
  defaultNamespace: harvester-system
  diff:
    comparePatches:
    - apiVersion: storage.k8s.io/v1
      kind: StorageClass
      name: harvester-longhorn
      jsonPointers:
      - /metadata/annotations

...
  resourceKey:
  - apiVersion: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: backingimagedatasources.longhorn.io    
...
```

(1) All sub-resources of a managedchart are listed in `managedchart.spec.resoruceKey` field, with `apiVersion, kind, name`, they can be added to `spec.diff.comparePatches`

(2) For the diff, the `spec` and `status` are the root path of any sub-resources monitored by `managedchart`, you can use `spec.a.b.c....` to locate to your modified fields instead of a high level match from root, set it's vaue in `jsonPointers`.

**Comment by prashantgnet** [comment]
Hello @w13915984028 

Thanks a lot for very detailed information, this is really helpful.

Closing this ticket.
