### ISSUE TITLE
[BUG] upgrade hung on apply-manifests

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4846]
**Describe the bug**

When upgrading from v1.1.2 -> v1.1.3-rc1 -> v1.2.1 the upgrade hangs on `hvst-upgrade-qn7lt-apply-manifests` forever and it doesn't time out. This was on the second part of the upgrade, v1.1.3-rc1 -> v1.2.1. 
**To Reproduce**
1. Deploy 2 node v1.1.2 cluster
2. Do pre-upgrade tasks
3. upgrade to v1.1.3-rc1
4. Add new node to cluster
5. Upgrade to v1.2.1

**Expected behavior**

The upgrade should complete
**Support bundle**

[support_bundle_apply_manfiests.zip](https://github.com/harvester/harvester/files/13620255/support_bundle_apply_manfiests.zip)

**Environment**
 - Harvester ISO version: v1.1.2 -> v1.1.3-rc1 -> v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node DL160 bare metal

**Additional context**
Longhorn volumes all look good.

On further inspection it looks like it thinks it's hung on deleting the cattle-monitoring-system logs.
`[hvst-upgrade-qn7lt-apply-manifests-jl2sv] there are still 9 pods in cattle-monitoring-system to be deleted`
However we deleted all of those logs in Rancher and it still was hung although the number of pods changed in the logs so it does look like it updated. Also the cordoned node is still labeled as schedulable. It looks like the apply-manifests job is hung.
 You'll see two in the list, but the other one is from the previous upgrade.
[hvst-upgrade-qn7lt-upgradelog-archive-2023-12-08T19-15-47Z.zip](https://github.com/harvester/harvester/files/13620152/hvst-upgrade-qn7lt-upgradelog-archive-2023-12-08T19-15-47Z.zip)

![Greenshot 2023-12-08 11 22 04](https://github.com/harvester/harvester/assets/83787952/42475807-556a-4dcb-b8ab-64f21f667639)

![Greenshot 2023-12-08 11 15 26](https://github.com/harvester/harvester/assets/83787952/280b9778-25d0-4cdc-b9f5-1432ac10e55b)
![Greenshot 2023-12-08 11 07 20](https://github.com/harvester/harvester/assets/83787952/04447421-f17f-450f-9b26-5f1b8942e86b)
![Greenshot 2023-12-08 10 40 30](https://github.com/harvester/harvester/assets/83787952/95d1d1ed-e49e-412a-9609-3341550f72eb)

![Greenshot 2023-12-08 10 16 14](https://github.com/harvester/harvester/assets/83787952/c73d380f-f890-41df-b00a-6aa78e84f7bb)
```
kubectl get jobs -n harvester-system -l harvesterhci.io/upgradeComponent=manifest
NAME                                 COMPLETIONS   DURATION   AGE
hvst-upgrade-ndd42-apply-manifests   1/1           7m58s      44h
hvst-upgrade-qn7lt-apply-manifests   0/1           18h        18h
```

**Comment by bk201** [comment]
@w13915984028 Can you take a look, seems related: https://docs.harvesterhci.io/v1.2/upgrade/v1-1-2-to-v1-2-0#6-an-upgrade-is-stuck-in-the-upgrading-system-service-state

**Comment by w13915984028** [comment]
Sometimes, forcely deleting the POD may still not fix this issue, instead, we need to remove their parent objects:

>POD  <- StatefulSet/Deployment/Daemonset <- Customized Prometheus/Alertmanager
<- ... finally ManagedChart

unfortunately, ManagedChart is removed but the final PODs are left, and those in-between object may also exist, if they are, deleting the POD has no effect, as they will be re-deployed.
```
root resources in cattle-monitoring-system

Customized CRD: Prometheus  object: rancher-monitoring-prometheus
   sub-object: statefulset.apps/prometheus-rancher-monitoring-prometheus

Customized  CRD: Alertmanager object:  rancher-monitoring-alertmanager 
  Sub-object:  statefulset.apps/alertmanager-rancher-monitoring-alertmanager

Deployment:
rancher-monitoring-grafana
rancher-monitoring-kube-state-metrics
rancher-monitoring-operator
rancher-monitoring-prometheus-adapter

Daemonset:
rancher-monitoring-prometheus-node-exporter


use below commands to delete them:

kubectl delete prometheus rancher-monitoring-prometheus -n cattle-monitoring-system
kubectl delete alertmanager rancher-monitoring-alertmanager -n cattle-monitoring-system

kubectl delete deployment rancher-monitoring-grafana -n cattle-monitoring-system
kubectl delete deployment rancher-monitoring-kube-state-metrics -n cattle-monitoring-system
kubectl delete deployment rancher-monitoring-operator -n cattle-monitoring-system
kubectl delete deployment rancher-monitoring-prometheus-adapter -n cattle-monitoring-system

kubectl delete daemonset rancher-monitoring-prometheus-node-exporter -n cattle-monitoring-system
```

The workaroud in the document will also be updated.

**Comment by w13915984028** [comment]
@noahgildersleeve Would you mind close this ticket? The document was updated.

**Comment by noahgildersleeve** [comment]
Closing as fixed since there was the [doc](https://github.com/harvester/docs/pull/495) update.
