### ISSUE TITLE
[BUG] The installer and dashboard are always displayed on tty1

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#485]
**Describe the bug**

The harvester-installer and the Dashboard after installation are always tied to tty1.
This prevents users from seeing the installer or the dashboard on headless servers or cloud instances that only come with a serial console.

**To Reproduce**
1. Use a headless server or cloud platform like Equinix Metal. I also tested with KVM and use `virsh console` to test.
2. Boot the ISO or kernel image and the installer is always on VGA output.
3. Finish the installation and the Dashboard is always on the VGA output.

**Expected behavior**
User should be able to use the installer and dashboard on serial console.

**Log**

**Environment:**
 - Harvester ISO version: 0.1.0
 - Installation Mode: ISO/app-mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
   - KVM VMs
   - Equinix Metal

**Additional context**

- The termbox uses tty1 if `TTY` is not defined:
https://github.com/rancher/harvester-installer/blob/4921224894d53abf46320839bb919814d6bbcb82/vendor/github.com/nsf/termbox-go/api.go#L30-L33

- The dashboard is on tty1
https://github.com/rancher/harvester-installer/blob/4921224894d53abf46320839bb919814d6bbcb82/k3os/overlay/libexec/k3os/boot#L26

**Comment by bk201** [comment]
By testing [current master code](https://github.com/rancher/harvester-installer/tree/0c48dec613364caadb78a246bc2a58eb8ae110be) on Equinix Metal, we found the installer is not displayed on ttyS1.

The repo contain sample iPXE scripts for the test: https://github.com/bk201/hvst-ipxe/tree/51d4ded66ec34e89c9c31959f9f5ee2feded4032/equinix

After Equinix boot up a node, we can see kernel messages are printed out to the SOS console (ttyS1), but eventually the harvester installer is not displayed.

stracing the harvester process:

```
kf-01 [~]# strace -p 3723
strace: Process 3723 attached
openat(AT_FDCWD, "/dev/ttyS1", O_WRONLY|O_CLOEXEC
```

**Comment by kingsd041** [comment]
Validated on master-388aa82c-head

Steps:
1. Create a VM in ESXI and add a serial port
2. Start Harvester via ISO
3. Change grub to `linux (loop0)/vmlinuz printk.devkmsg=on k3os.mode=install console=tty1 console=ttyS0,115200`
4. View the serial port output

Result:
The harvester installation options can be viewed through the serial port：
![image](https://user-images.githubusercontent.com/19684717/112956392-00770a00-9173-11eb-9963-41658bebb2e8.png)
