### ISSUE TITLE
[BUG] v1.1.3-rc1 ISO Install Fails Legacy BIOS/UEFI multi/single NICs

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4851]
**Describe the bug**
USB Installation hangs at same point as:
https://github.com/harvester/harvester/issues/4510

**To Reproduce**
1. Using something like [Popsicle](https://github.com/pop-os/popsicle) or Balena Etcher, flash v1.1.3-rc1 -> usually these are not present on `dd` or Rufus USB Flashing Tool
2. Hangs after Phillip Lougher, /dev/mapper/live-rw - timeout

Perhaps can be reproduced with:
- https://github.com/bk201/misc/blob/main/harvester/issue-4510/Vagrantfile

**Expected behavior**
Even with a system with low resources to at least make it to the screen of installer

**Environment**
 - Harvester ISO version: v1.1.3-rc1 
 - Underlying Infrastructure: baremetal lenovo-thinkcenter m93

**Additional context**
[dmesg-log.log](https://github.com/harvester/harvester/files/13631257/dmesg-log.log)
[etc-initrd-release.txt](https://github.com/harvester/harvester/files/13631259/etc-initrd-release.txt)
[etc-os-release.txt](https://github.com/harvester/harvester/files/13631260/etc-os-release.txt)
[journalctl-log.log](https://github.com/harvester/harvester/files/13631261/journalctl-log.log)
[rdsosreport.txt](https://github.com/harvester/harvester/files/13631262/rdsosreport.txt)

**Comment by Vicente-Cheng** [comment]
From the [rdsosreport.txt](https://github.com/harvester/harvester/files/13631262/rdsosreport.txt)

There is a weird point we met before.

we can see the blkid result:
```
/dev/sdb2: SEC_TYPE="msdos" UUID="CA0A-0DC2" BLOCK_SIZE="512" TYPE="vfat"
/dev/sdb1: BLOCK_SIZE="2048" UUID="2023-11-22-14-15-38-00" LABEL="COS_LIVE" TYPE="iso9660"
```

`/dev/sdb1` is the root we need to boot with installation

Then we can see the `/dev/disk/by-label` as below:
/dev/disk/by-label:
```
total 0
lrwxrwxrwx 1 root root 10 Aug 16 12:00 COS_LIVE -> ../../sdb2
...
```

The system thought the /dev/sdb2 was the root. That's why it hung.
That is a very similar case with https://github.com/harvester/harvester/issues/4510.
But the real root cause could be related to the udev rules.

**Comment by irishgordo** [comment]
@Vicente-Cheng 
Here are the new logs from the balena-etcher provisioning allong with udevadm info results :smile: 

[label-results-udevadm-dev-sdb2.log](https://github.com/harvester/harvester/files/13642434/label-results-udevadm-dev-sdb2.log)
[label-results-udevadm-dev-sdb1.log](https://github.com/harvester/harvester/files/13642435/label-results-udevadm-dev-sdb1.log)
[dev-sdb2-udevadm-result.log](https://github.com/harvester/harvester/files/13642436/dev-sdb2-udevadm-result.log)
[dev-sdb1-udevadm-result.log](https://github.com/harvester/harvester/files/13642437/dev-sdb1-udevadm-result.log)
[new-journalctl.log](https://github.com/harvester/harvester/files/13642438/new-journalctl.log)
[new-systemctl-status.log](https://github.com/harvester/harvester/files/13642439/new-systemctl-status.log)
[new-rdosreport.log](https://github.com/harvester/harvester/files/13642440/new-rdosreport.log)

**Comment by Vicente-Cheng** [comment]
This issue is due to the new udev changes from https://github.com/systemd/systemd/pull/28481

Now, the link priority will decrease if type `iso-9660`.

That will cause the root partition to have lower priority, so the `by-path/COS_LIVE` will be occupied by EFI boot partition.

**Comment by irishgordo** [comment]
@Vicente-Cheng I've tested this leveraging the `harvester-installer` checking that out at v1.1 and then running `make` yielding:

```go
No existed harvester source. Pulling...
Cloning into '../harvester'...
remote: Enumerating objects: 11738, done.
remote: Counting objects: 100% (11738/11738), done.
remote: Compressing objects: 100% (8231/8231), done.
remote: Total 11738 (delta 3371), reused 7992 (delta 2696), pack-reused 0
Receiving objects: 100% (11738/11738), 18.59 MiB | 19.13 MiB/s, done.
Resolving deltas: 100% (3371/3371), done.
Installer version: master
Harvester version: 70d4eb54
Harvester chart version: 0.0.0-v1-1-70d4eb54
Rancher version: v2.6.13
Rancher monitoring version: 100.1.0+up19.0.3
Rancher logging version: 100.1.3+up3.17.7
Running tests
ok  	github.com/harvester/harvester-installer/pkg/config	0.006s	coverage: 56.7% of statements
?   	github.com/harvester/harvester-installer/pkg/version	[no test files]
?   	github.com/harvester/harvester-installer/pkg/widgets	[no test files]
ok  	github.com/harvester/harvester-installer/pkg/console	0.011s	coverage: 7.5% of statements
ok  	github.com/harvester/harvester-installer/pkg/util	0.011s	coverage: 56.0% of statements
ARCH: amd64
VERSION: 70d4eb54
CHART_VERSION: 0.0.0-v1-1-70d4eb54
APP_VERSION: v1.1-70d4eb54
SUFFIX: -amd64
REPO: rancher
TAG: 70d4eb54-amd64
IMAGE_PUSH_TAG: v1.1-head
MIN_UPGRADABLE_VERSION: 
Replace the Harvester chart version to 0.0.0-v1-1-70d4eb54
Replace the Harvester appVersion to v1.1-70d4eb54
Replace the Harvester image tag to v1.1-head
Replace the Harvester image repo to rancher
Successfully packaged chart and saved it to: /go/src/github.com/harvester/harvester-installer/package/harvester-repo/charts/harvester-0.0.0-v1-1-70d4eb54.tgz
Successfully packaged chart and saved it to: /go/src/github.com/harvester/harvester-installer/package/harvester-repo/charts/harvester-crd-0.0.0-v1-1-70d4eb54.tgz
patch rancher logging rke2 configmap.yaml, daemonset.yaml
# harvester-patch to configmap fluent-bit.conf
            - mountPath: "/var/log/audit/audit.log" # harvester-patch
        - name: rke2-audit  # harvester-patch
Successfully packaged chart and saved it to: /go/src/github.com/harvester/harvester-installer/package/harvester-repo/charts/rancher-logging-100.1.3+up3.17.7.tgz
finish patch ranch-logging chart
tar: rancher-logging/Chart.yaml: time stamp 2023-12-13 22:17:33 is 0.019861482 s in the future
tar: rancher-logging/values.yaml: time stamp 2023-12-13 22:17:33 is 0.019788165 s in the future
```
Then taking a USB flashing with Balena Etcher and testing on:
- UEFI (virtualized & bare-metal)
- Legacy BIOS (bare-metal)
- Intel & AMD
- Single & Multi-NICs

And it seems to look good.
Harvester Interactive ISO Installation is able to load and make it to the first pane of installer without issue, not hanging on dev-mapper rw / seeing timeout :smile: :+1: 

![Screenshot from 2023-12-13 15-37-21](https://github.com/harvester/harvester/assets/5370752/cd5c8a32-1ce6-4371-8dd6-5eaf7b975ca2)
![Screenshot from 2023-12-13 15-36-24](https://github.com/harvester/harvester/assets/5370752/6872794e-5da2-4cbc-91ff-8dbe96a985b0)
![Screenshot from 2023-12-13 15-35-15](https://github.com/harvester/harvester/assets/5370752/9c9ecd7c-e437-40a4-b2eb-20aef64a3af2)
![Screenshot from 2023-12-13 15-34-52](https://github.com/harvester/harvester/assets/5370752/aac22b6e-a68d-4d79-8086-86440ee9051e)
![Screenshot from 2023-12-13 14-16-02](https://github.com/harvester/harvester/assets/5370752/e417bcd5-f541-4a8f-85a7-89d9ced7f9a3)
![PXL_20231213_234120866](https://github.com/harvester/harvester/assets/5370752/833b1235-a247-4acb-b167-468f6792410c)
![PXL_20231213_234141443](https://github.com/harvester/harvester/assets/5370752/9883fb88-bbe4-4273-a4e0-0abbad848358)
![PXL_20231213_234217357](https://github.com/harvester/harvester/assets/5370752/eb16c20a-d192-45d1-b48c-601d49b5fa7f)
![PXL_20231213_234310762](https://github.com/harvester/harvester/assets/5370752/9822f99f-f18f-475e-93c0-8bea6b7ea7c2)
![PXL_20231213_225751858](https://github.com/harvester/harvester/assets/5370752/e2e3bdce-3241-4f89-809c-ebdcfa67f445)
![PXL_20231213_225926909](https://github.com/harvester/harvester/assets/5370752/203cf7d1-5fd5-46a0-872a-1c2726dcf960)
![PXL_20231213_225952847](https://github.com/harvester/harvester/assets/5370752/c8bb92cb-047d-4318-b266-97fcc8ad24a2)


I'll go ahead and close this out - thanks for the fix :+1: :smile: !
