### ISSUE TITLE
[BUG] Faild to integrate Harvester and Rancher

### ISSUE THREAD

**Issue by zeinali0** [harvester/harvester#4855]
**Describe the bug**
Getting `Certificate chain is not complete` when trying to integrate harvester and rancher

**To Reproduce**
1. I ran an on-premise rancher with helm chart and cert-manager on and rke2 cluster
2. I installed harvester on a bear-metal server and create a new Harvester Cluster
3. export rancher certificate from it's url (https:/192.168.10.119:30444) using openssl and  add it in Harvester -> Settings -> additional-ca
4. I tried to Integrate Harvester with my Rancher but I'm getting cert error in cattle-cluster-agent on Harvester

**Environment**
 - Harvester ISO version: 1.2.1
 - Rancher: 2.7.9

**cattle-cluster-agent logs**
```
~> kubectl logs pod/cattle-cluster-agent-5f58f4d47d-fhbnx -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.52.0.67 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.53.235.105:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.53.235.105:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.53.235.105 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.53.235.105:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.53.235.105 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.53.235.105 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=34409118-c866-4a82-a867-901c55ec8449 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-5f58f4d47d-fhbnx CATTLE_RANCHER_WEBHOOK_MIN_VERSION= CATTLE_RANCHER_WEBHOOK_VERSION=2.0.6+up0.3.6 CATTLE_SERVER=https://192.168.10.119:30444 CATTLE_SERVER_VERSION=v2.7.9
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.53.0.10 options ndots:5
INFO: https://192.168.10.119:30444/ping is accessible
time="2023-12-11T15:24:13Z" level=info msg="Listening on /tmp/log.sock"
time="2023-12-11T15:24:13Z" level=info msg="Rancher agent version v2.7.9 is starting"
time="2023-12-11T15:24:13Z" level=info msg="Certificate details from https://192.168.10.119:30444"
time="2023-12-11T15:24:13Z" level=info msg="Certificate #0 (https://192.168.10.119:30444)"
time="2023-12-11T15:24:13Z" level=info msg="Subject: CN=dynamic,O=dynamic"
time="2023-12-11T15:24:13Z" level=info msg="Issuer: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T15:24:13Z" level=info msg="IsCA: false"
time="2023-12-11T15:24:13Z" level=info msg="DNS Names: [localhost]"
time="2023-12-11T15:24:13Z" level=info msg="IPAddresses: [10.42.2.2 10.42.2.3 10.42.2.5 10.42.2.8 10.43.247.0 127.0.0.1 192.168.10.119]"
time="2023-12-11T15:24:13Z" level=info msg="NotBefore: 2023-12-04 14:05:32 +0000 UTC"
time="2023-12-11T15:24:13Z" level=info msg="NotAfter: 2024-12-05 20:53:38 +0000 UTC"
time="2023-12-11T15:24:13Z" level=info msg="SignatureAlgorithm: ECDSA-SHA256"
time="2023-12-11T15:24:13Z" level=info msg="PublicKeyAlgorithm: ECDSA"
time="2023-12-11T15:24:13Z" level=info msg="Certificate #1 (https://192.168.10.119:30444)"
time="2023-12-11T15:24:13Z" level=info msg="Subject: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T15:24:13Z" level=info msg="Issuer: CN=dynamiclistener-ca@1701698732,O=dynamiclistener-org"
time="2023-12-11T15:24:13Z" level=info msg="IsCA: true"
time="2023-12-11T15:24:13Z" level=info msg="DNS Names: <none>"
time="2023-12-11T15:24:13Z" level=info msg="IPAddresses: <none>"
time="2023-12-11T15:24:13Z" level=info msg="NotBefore: 2023-12-04 14:05:32 +0000 UTC"
time="2023-12-11T15:24:13Z" level=info msg="NotAfter: 2033-12-01 14:05:32 +0000 UTC"
time="2023-12-11T15:24:13Z" level=info msg="SignatureAlgorithm: ECDSA-SHA256"
time="2023-12-11T15:24:13Z" level=info msg="PublicKeyAlgorithm: ECDSA"
time="2023-12-11T15:24:13Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://192.168.10.119:30444\": x509: certificate signed by unknown authority"
```

**Comment by WebberHuang1118** [comment]
It seems the certificate on Rancher is incomplete, maybe it's self-signed or empty.  For your reference: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/add-tls-secrets, https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate.

From my experience, If the rke2 cluster is [deployed with rancher and cert-manager](https://ranchermanager.docs.rancher.com/getting-started/quick-start-guides/deploy-rancher-manager/helm-cli), it's not needed to configure additional ca for [importing Harvester](https://docs.harvesterhci.io/v1.3/rancher/virtualization-management#importing-harvester-cluster).

**Comment by zeinali0** [comment]
Here are created tls secrets for rancher:

![image](https://github.com/harvester/harvester/assets/28354390/cc5d391c-2cf0-487d-ab6c-cac936df8b5a)

I guess the problem is `tls-rancher` and `tls-rancher-ingress` are different and as I'm using a fake domain for rancher i can't use it in harvester node so i had to expose rancher via a node port service so it using `tls-rancher` Cert while `CATTLE-CHECKSUM` we are passing to harvester node throw `https://192.168.10.119:30444/v3/import/{****}.yaml` is for `tls-rancher-ingress`

Is there any way to add domain to ip map in harvester? 
I tried editing `/etc/hosts` (while it's readonly) but it seems it's not working and it can't resolve my fake domain name.

**Comment by zeinali0** [comment]
> I guess the problem is tls-rancher and tls-rancher-ingress are different and as I'm using a fake domain for rancher i can't use it in harvester node so i had to expose rancher via a node port service so it using tls-rancher Cert while CATTLE-CHECKSUM we are passing to harvester node throw https://192.168.10.119:30444/v3/import/{****}.yaml is for tls-rancher-ingress
> 
> Is there any way to add domain to ip map in harvester?
> I tried editing /etc/hosts (while it's readonly) but it seems it's not working and it can't resolve my fake domain name.

I confirm this was the case. Using url (`https://rancher.mydomain.dmv/v3/import/{****}.yaml`) and ingress service instead of node-port fixed the problem
