### ISSUE TITLE
[ENHANCEMENT] BaseOS related update

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#4857]
**Is your enhancement related to a problem? Please describe.**
This issue is used to track BaseOS (OS image, Elemental) related PRs for v1.2.2

**Describe the solution you'd like**
task list:
- [x] https://github.com/harvester/harvester/pull/4822
- [x] https://github.com/harvester/harvester-installer/pull/609
- [x] https://github.com/harvester/os2/pull/85
- [x] https://github.com/harvester/harvester/issues/4856

**Describe alternatives you've considered**
None

**Additional context**
TBD

**Comment by Vicente-Cheng** [comment]
After I bump the new baseos, I will move this to ready for testing again.

**Comment by khushboo-rancher** [comment]
@lanfon72 Do you think our e2e should be enough to test it?

**Comment by lanfon72** [comment]
We would still need to manually check versions, but no new automation test required.

**Comment by lanfon72** [comment]
Verified this change has been applied.

- Basic operations tested by daily e2e and it works.
- Basic Rancher integration tested by daily e2e and it works.
- Packages and release version hit the required in https://github.com/harvester/harvester/issues/4857#issuecomment-1920917361
![image](https://github.com/harvester/harvester/assets/5169694/84e67062-2033-48b5-8f81-9e2ceb4ff0c5)
