### ISSUE TITLE
[BUG] can't run terraform init after using harvester terraformer to import resources

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#4859]
**Describe the bug**

Currently, when I use harvester/terraformer to import resources, I couldn't run `terraform init` smoothly.

**To Reproduce**

1. Download v1.1.1 harvester/terraformer (https://github.com/harvester/terraformer/releases/tag/v1.1.1-harvester)
2. Use commands to import resource, such as `import harvester -r image,virtualmachine`
3. `cd generated/harvester/image`
4. `terraform init`
5. It shows this error message
```
Initializing the backend...
╷
│ Error: Invalid legacy provider address
│
│ This configuration or its associated state refers to the unqualified provider "harvester".
│
│ You must complete the Terraform 0.13 upgrade process before upgrading to later versions.
```

**Expected behavior**

It should be successful when I run `terraform init`

**Workaround**

1. Run `terraform state replace-provider -auto-approve "registry.terraform.io/-/harvester" "harvester/harvester"`
2. Add `source = "harvester/harvester"` in `generated/harvester/image/provider.tf` like below.
```diff
terraform {
	required_providers {
		harvester = {
+			source = "harvester/harvester"
			version = "~> 0.6.3"
		}
	}
}
```
3. Run `terraform init`

**Environment**
 - Harvester ISO version: 1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM 

**Additional context**

When you run `cat generated/harvester/image/terraform.tfstate`, the terraform version is `0.12.31`.

There is a difference in provider.tf between current terraformer and harvester terraformer.

- harvester terraformer (there is no source key in older terraformer version)
https://github.com/harvester/terraformer/blob/master/terraformutils/terraformoutput/hcl.go#L34-L40
- current terraformer https://github.com/GoogleCloudPlatform/terraformer/blob/master/terraformutils/terraformoutput/hcl.go#L36-L38

**Comment by lanfon72** [comment]
closed as this is known behavior was mentioned in https://github.com/harvester/harvester/issues/943#issuecomment-886431707
