### ISSUE TITLE
[ENHANCEMENT] Use general image for promote job

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4865]
**Is your enhancement related to a problem? Please describe.**
Currently, there're two image values in [promote_controller.go](https://github.com/FrankYang0529/harvester/blob/197012aa566c55469472e4c8970d7f6a0912bfb2/pkg/controller/master/node/promote_controller.go#L48) and [helm chart](https://github.com/FrankYang0529/harvester/blob/197012aa566c55469472e4c8970d7f6a0912bfb2/deploy/charts/harvester/values.yaml#L491-L492). We can use Rancher Apps to get the value from helm chart, so we don't need to maintain the same value in two places.

**Additional context**
https://github.com/harvester/harvester/pull/4852#pullrequestreview-1777529928

**Comment by albinsun** [comment]
Doea this ticket relates/same to #4839 ?

**Comment by Yu-Jack** [comment]
Yes, it's almost same. But, original PR https://github.com/harvester/harvester/pull/4852 doesn't fetch value from rancher app, so we open another enhancement issue (this one 4865) to track this. It's about implementation.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-dev-20240105`, close as fixed.


## Environment
* Harvester
 * Version: `v1.3.0-dev-20240105`
 * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
 * ui-source: `Auto`


## Steps 
1. <details open>
     <summary> Check helm chart value: <code>registry.suse.com/bci/bci-base:15.5</code>
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/585597c5-19b0-486d-acd1-b0f6a9435671)
   </details>
   
1. Check promote jobs uses image same as helm chart value
   * <details open>
       <summary> harvester-promote-harvester-node-1 :ballot_box_with_check: 
       </summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/8ed8e383-7b5f-4437-b075-9c05c3c6165f)
     </details>

   * <details open>
       <summary> harvester-promote-harvester-node-2 :ballot_box_with_check: 
       </summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/e0c818d0-5bf8-4426-896c-15f0b1963cc5)
     </details>
     
   * <details open>
       <summary> Jobs are completed :ballot_box_with_check: 
       </summary>
       
       ![image](https://github.com/harvester/harvester/assets/2773781/b52e2e36-4041-4613-88c7-3b88a5f085b4)
     </details>
