### ISSUE TITLE
[BUG] Upgrade hangs/fails for v1.1.3-rc1 to v1.2.1 with rebuilding Longhorn volume

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#4873]
**Describe the bug**

When upgrading from v1.1.3-rc1 to v1.2.1 the upgrade won't complete. It 
**To Reproduce**
1. Create a three node cluster in Harvester on v1.1.3-rc1
2. Start an upgrade via the upgrade responder

**Expected behavior**

Upgrade should complete
**Support bundle**

**For the support bundles change the `_2` one from `_2.zip to .z01`. It's split but Github won't allow split zips, and they have to be the same name to easily unzip.**
[split_upgrade_v113-rc1-to-v1.2.1_support_bundle.zip](https://github.com/harvester/harvester/files/13676057/split_upgrade_v113-rc1-to-v1.2.1_support_bundle.zip)
[split_upgrade_v113-rc1-to-v1.2.1_support_bundle_2.zip](https://github.com/harvester/harvester/files/13676065/split_upgrade_v113-rc1-to-v1.2.1_support_bundle_2.zip)

**Environment**
 - Harvester ISO version: v1.1.3-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node bare metal DL160
[split_upgrade_v113-rc1-to-v1.2.1_support_bundle.zip](https://github.com/harvester/harvester/files/13676057/split_upgrade_v113-rc1-to-v1.2.1_support_bundle.zip)
[split_upgrade_v113-rc1-to-v1.2.1_support_bundle_2.zip](https://github.com/harvester/harvester/files/13676065/split_upgrade_v113-rc1-to-v1.2.1_support_bundle_2.zip)

**Additional context**
This was originally tested on a 3 node bare metal setup with a lot of pre-setup, but it was reproduced on a simple upgrade setup by Kiefer. Initially there was a hangup on the monitoring pods, but after forcing those to delete and then proceed with the upgrade it started to loop on rebuilding a longhorn volume.
![Greenshot 2023-12-11 16 05 05](https://github.com/harvester/harvester/assets/83787952/938109f6-7594-4534-a9bd-37d15ce4819d)
![Greenshot 2023-12-11 16 00 12](https://github.com/harvester/harvester/assets/83787952/f083c20e-a880-40d8-9a96-706208db3f24)

**Comment by bk201** [comment]
During the upgrade, Canal CNI was downgraded from v3.26.1 to v3.25.0. Version v3.25.0's userspace tool is not compatible with the kernel in Harvester v1.1.3-rc* (newer than v1.2.1!), thus we see rke2-canal pods keep crashing with the following errors:

```
2023-12-12 15:29:11.839 [ERROR][29638] felix/ipsets.go 569: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.36: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6\nKernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n"
2023-12-12 15:29:12.097 [ERROR][29638] felix/ipsets.go 569: Bad return code from 'ipset list'. error=exit status 1 family="inet" stderr="ipset v6.36: Kernel support protocol versions 6-7 while userspace supports protocol versions 6-6\nKernel and userspace incompatible: settype hash:net with revision 7 not supported by userspace.\n
This leads to replica rebuild failure because the pods' network doesn't work. (edited) 
```

We decided to revert the RKE2 bump and make sure users can upgrade to v1.2.* version first.

**Comment by innobead** [comment]
@bk201 why bumping RKE2, but the Canal CNI was downgraded?

**Comment by bk201** [comment]
> @bk201 why bumping RKE2, but the Canal CNI was downgraded?

No it's not downgrade in the 1.1.2 -> 1.1.3 path.
But it will be downgraded if we bump RKE2 in 1.1.3, and then a user upgrades from 1.1.3 to 1.21.

**Comment by TachunLin** [comment]
We have the 3 nodes upgrade test from `v1.1.3-rc3` to `v1.2.1` on the baremetal machines also using the upgrade-responder. 

We can successfully upgrade to v1.2.1 without hanging on the Pre-draining of the last node.  
And during the process, we did not encounter the rebuilding Longhorn volume issue.
![image](https://github.com/harvester/harvester/assets/29251855/f72bdc46-334c-4e1c-b54a-a73560a17ede)


Since the symptoms and verification steps are the same with #4830 
We can refer to the test result in https://github.com/harvester/harvester/issues/4830#issuecomment-1862001027 and close out this issue accordingly.  

Please feel free to reopen if encounter this issue again. Thanks.

**Comment by irishgordo** [comment]
As it's been covered in 4830 I'll go ahead and close this out - thanks again @TachunLin :smile: :+1:
