### ISSUE TITLE
[Doc] ReleaseNote / Document for Multiple nodes pre-drains in an upgrade

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#4877]
**Is your doc request related to a problem? Please describe or add related issue ID.**
[[BUG] Multiple nodes pre-drains in an upgrade #3216](https://github.com/harvester/harvester/issues/3216#top)

**Describe the solution you'd like**
This known issue has workaround that one can manually uncordon the accidentally-cordoned node to continue the upgrade.
However this issue may hit over 1 times during upgrade (depends on cluster size)
We should note it in release note or document for releases supports upgrade from `v1.1.1`.

**Comment by bk201** [comment]
Doc PR: https://github.com/harvester/docs/pull/492
Doc published: https://docs.harvesterhci.io/v1.1/upgrade/v1-1-1-to-v1-1-3
