### ISSUE TITLE
[ENHANCEMENT] upgrade: adapt Longhorn im-e/im-r pod unification

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4879]
**Is your enhancement related to a problem? Please describe.**

In Longhorn 1.5.x, im-r and im-e pods are consolidated into one pod. We should adapt the change and fix the waiting logic here: https://github.com/harvester/harvester/blob/a46456a7cf1f4bafcc22a7b6960d9b7bb6732122/package/upgrade/upgrade_manifests.sh#L161

**Describe the solution you'd like**

Fix the wait logic.

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
Move back to implement. for upgrade from LH v1.5 -> v1.6, there will be 2 aio instance-manager pods if a node has any attached volumes.

**Comment by lanfon72** [comment]
Verified the enhancement has been applied.

Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.2-d542563e-head** -> **v1.3.0-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create VMs with additional volumes
4. perform upgrade
5. Harvester should upgraded successfully
6. VM should keep running and operation normally
