### ISSUE TITLE
[BUG] 1.1.1 - 1.1.2 upgrade (before 1.2.x upgrade)

### ISSUE THREAD

**Issue by Sepiidae** [harvester/harvester#4884]
**Describe the bug**

We just closed out our Fall semester and went to upgrade to 1.2.x. To do so we need to upgrade 

1.1.1 to 1.1.2
1.1.2 to 1.2.x

Unfortunately upon initating the upgrade get an error in the logs stating that elemental isn't availble in registry.opensuse.org

Dec 18 13:35:05 10.116.8.87 2023-11-04T02: 38:55+00:00#011rke2#011{"level":"E","thread_id":"2581","filename":"pod_workers.go","linenumber":"965","message":"\"Error syncing pod, skipping\" err=\"failed to \\\"StartContainer\\\" for \\\"runner\\\" with ImagePullBackOff: \\\"Back-off pulling image \\\\\\\"registry.opensuse.org/isv/rancher/elemental/stable/teal53/15.4/rancher/elemental-teal-channel/5.3:latest\\\\\\\"\\\"\" pod=\"fleet-default/elemental-teal-channel\" podUID=bb7fe3c1-1e25-43ef-9248-3744af7c55c4"}

Any recommendations or alternative registries we should use?

**To Reproduce**
1. Start 1.1.1 -> 1.1.2 upgrade via the gui

**Expected behavior**

A successful upgrade to 1.1.2

**Support bundle**

This is on the way

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
15 Baremetal Dell R6000 AMD nodes

**Additional context**

**Comment by bk201** [comment]
@Sepiidae Can you share which file contains the log? The image is not used by Harvester.

**Comment by Sepiidae** [comment]
> @Sepiidae Can you share which file contains the log? The image is not used by Harvester.

The log line is received via log shipping to our syslog server. I am not sure which file on the harvester servers contains this line. I am going to run a grep to search.

**Comment by Sepiidae** [comment]
Ok, we went down the wrong rabbit hole. This error message was not related to the upgrade. It appears we are stuck with prometheus being stuck during its upgrade. I am following a few other threads which walk through the fix. If we get stuck I'll post another issue. 

As aways thank you for this community.
