### ISSUE TITLE
[BUG] Harvester Prevents From Configuring Storage Network Even There in no Running VM and Online Volumes

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#4886]
**Describe the bug**
Harvester prevents from configuring Storage Network even if there is no running VM and online volumes.

**To Reproduce**
1. Create a VM and shutdown it inside the VM
2. Configure the Storage Network
3. Configure failed with message `Please stop all VMs before configuring the storage-network`![storage_network_webhook](https://github.com/harvester/harvester/assets/19387129/8f1f28f5-b817-427c-b4ee-b339cd679045)
4. However, there is no running VM if checked from GUI![no_vm](https://github.com/harvester/harvester/assets/19387129/4d7460d6-eaa3-4451-8fc4-74e0c26213bd)
5. There is no online volume, either if check from LH GUI![no_online_volume](https://github.com/harvester/harvester/assets/19387129/ab92ea98-17b1-4be3-b1c5-49aebffebe4f)

**Expected behavior**
The Storage Network could be configured successfully if there is no running VM and online volume.

**Environment**
 - Harvester ISO version: master-head

**Comment by starbops** [comment]
connect with #4363

**Comment by Yu-Jack** [comment]
connect with https://github.com/harvester/harvester/issues/4778, it's a similar bug related to stopping vm and vmi behavior between inside vm and outside vm.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
To be noticed that this bug been fixed on `master-head` but not `v1.3` branch yet.

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **master-0432ad56-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/4886#issue-2047825326
3. Storage Network should able to be created
