### ISSUE TITLE
[BUG] Harvester Mounting Partitions Of Old Harvester

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#4887]
**Describe the bug**
Given a single node cluster Harvester instance with two drives of the same size (either logical RAID drives or pass-through hba).
If Harvester has at one point been installed (same version) on both drives it gets confused and seems to automount some partitions from some of each drive.

**To Reproduce**
Pre-reqs:
- Single node Harvester cluster, 2 drives of same size ex 350G 

Scenario 1:
1. install Harvester to `/dev/vda` - allow installer to finish
1. node reboots, power off node before Harvester becomes ready
1. install Harvester to `/dev/vdb` - allow installer to finish
1. node reboots, keep boot order as:
  a. `/dev/vda`
  b. `/dev/vdb`
1. you'll notice that some partitions of `/dev/vdb` & `/dev/vda` are automatically mounted 

Scenario 2:
1. power down Harvester node
1. reverse the boot order:
  a. `/dev/vdb`
  b. `/dev/vda`
1. power up the node, you'll notice that some partitions of `/dev/vda` & `/dev/vdb` are automatically mounted 

**Expected behavior**
Perhaps not auto mounting partitions from another drive, unless they're like an "extra-disk" partition? 

**Environment**
 - Harvester ISO version: v1.1.3-rc3
 - Underlying Infrastructure: qemu-kvm & bare-metal hp dl160

**Additional context**
![Screenshot from 2023-12-18 19-40-25](https://github.com/harvester/harvester/assets/5370752/4f60ebc5-1940-4c4e-8453-4b7d677c3424)
![Screenshot from 2023-12-18 19-38-41](https://github.com/harvester/harvester/assets/5370752/dce1d70b-4f4e-4914-a97b-28aa60ff1dff)
![Screenshot from 2023-12-18 19-23-00](https://github.com/harvester/harvester/assets/5370752/e7b87ff2-d72b-4889-a71d-98b05005562d)
![Screenshot from 2023-12-18 19-11-18](https://github.com/harvester/harvester/assets/5370752/81e9f25f-94d4-4827-80c2-f767f2edc5d7)

**Comment by bk201** [comment]
@irishgordo This is expected because elemental mount partition by labels. One way to deal with this is to pop up a warning if the installer detects an existing installation.

**Comment by irishgordo** [comment]
@bk201 that pop up warning sounds like a great idea :smile:  - maybe additionally it could funnel a user into the ability to format the drive(s) that it detected had an existing installation

**Comment by bk201** [comment]
supposed to be fixed with wipefs configuration.
