### ISSUE TITLE
[ENHANCEMENT] Improve the UX of non-migratable VMs in node maintenance mode

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4888]
**Is your enhancement related to a problem? Please describe.**

When a node is put into maintenance, Harvester will start to live-migrate VMs on it. In some cases, VMs can't migrate to other node:
- VMs have PCI passthrough devices.
- VMs have NodeSelector or zone constraints, but can't find another node to schedule.

And these VMs will stay migrating until timeout happens.

**Describe the solution you'd like**

Improving the UX. Some ideas:

- Display a non-migratable VM list and suggest those VMs will be shut down.
- Once the user confirms, we shut down the VMs and perform maintenance.

**Describe alternatives you've considered**

**Additional context**

**Comment by megabreit** [comment]
Is this just an UI issue? Currently only 2 life migration are done in parallel. And if 2 migrations are in progress (and never finish), the rest of the VMs, even if they can be migrated, will not be moved to other hypervisor nodes.

**Comment by bk201** [comment]
> Is this just an UI issue? Currently only 2 life migration are done in parallel. And if 2 migrations are in progress (and never finish), the rest of the VMs, even if they can be migrated, will not be moved to other hypervisor nodes.

No. the `require-ui` label is just for indicating there is UI work involved. So one proposal in the issue is to warn the user a VM can't live-migrate if the user tries to migrate it or put a node into maintenance.

**Comment by torchiaf** [comment]
@bk201 @ibrokethecloud is there a chance that `force` option will shoutdown all non-migratable VMs ?
- If so, we could add a tooltip to the force checkbox or a message, to inform the users that they can use force checkbox to shutdown the VMs If first try fails.
- else we need a new checkbox, visible on errors, to shutdown the VMs.

What do you think ?

cc @a110605

**Comment by a110605** [comment]
> @bk201 @ibrokethecloud is there a chance that `force` option will shoutdown all non-migratable VMs ?
> 
> * If so, we could add a tooltip to the force checkbox or a message, to inform the users that they can use force checkbox to shutdown the VMs If first try fails.
> * else we need a new checkbox, visible on errors, to shutdown the VMs.
> 
> What do you think ?
> 
> cc @a110605

I think we can always display force shutdown banner message in the modal rather than show it after getting the unhealtyVMs list.
It provides clear inform to users.

<img width="552" alt="Screenshot 2024-08-07 at 1 56 02 PM" src="https://github.com/user-attachments/assets/b900b41e-8a76-49c6-b5cf-b2241b3a62ec">

**Comment by ibrokethecloud** [comment]
the UI looks good to me. The force option will shutdown all VM's which are not migratable irrespective of the reason for their non-migaration.

**Comment by lanfon72** [comment]
Move back to review as https://github.com/harvester/harvester/pull/6397 not merged yet.
(tested on `v1.4-1305f11-head`)

**Comment by bk201** [comment]
@lanfon72 According to @ibrokethecloud, #6397 is a further improvement and it can be tracked in https://github.com/harvester/harvester/issues/6509

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/user-attachments/assets/16270f8d-0f91-4db5-b9b5-94f33745a6ec)
![image](https://github.com/user-attachments/assets/c0ed4377-8f18-4be6-94f3-5558cc64a0fb)


Test Information
----
* Environment: **bare metal DL360G9 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 2 nodes having PCI devices
2. Create an image for VM creation
3. Enable Addon `pci-devices-controller`
4. Create VM and start it
    - `vm1` with PCI device attached
    - `vm2` with Node Scheduling rules (match only one specific node, using `spec.spec.affinity.nodeAffinity`)
    - `vm3` with **container** volume
    - `vm4` with **CD-ROM** volume
5. Enable maintenance mode without **force** on the node hosting VMs
6. Error message displayed and VMs should NOT be shut down automatically
7. The node should NOT enter maintenance mode
8. Enable maintenance mode with **force** on the node hosting VMs
9. VMs should be shut down automatically
10. The node should enter maintenance mode
