### ISSUE TITLE
[ENHANCEMENT] Update node-manager Helm packaging to include harvester-node-manager-webhook

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#4892]
**Is your enhancement related to a problem? Please describe.**

https://github.com/harvester/harvester/issues/4710

**Describe the solution you'd like**

Charts repository needs to be updated to deploy the webhook once it has been merged into the node-manager repo and images have been pushed to the container registry

https://github.com/harvester/charts

Pre-requisites

- [x] Create Docker Hub repo: rancher/harvester-node-manager-webhook -- EIO ticket pending
- [x] Update node-manager Drone CI to build and push webhook images

**Describe alternatives you've considered**

**Additional context**

**Comment by connorkuehl** [comment]
Need published images first: https://github.com/harvester/node-manager/pull/28

**Comment by irishgordo** [comment]
I'm going to go ahead and close this out :smile: :+1: as things look good.
Additionally, the coverage of cases pending:
https://github.com/harvester/tests/pull/1100/files
