### ISSUE TITLE
[Question] Volume Actual Size is not equal with the host actual size, How to trim the block

### ISSUE THREAD

**Issue by Captured77** [harvester/harvester#4908]
I use harvester v1.1.0. I found  when I remove a big file from the vm. The volume's actual size on the longhorn is bigger than the vm's actual size. How can I trim this volume? I scanned  longhorn's web and found how to trim the volume with filesystem mode. it's not about trim volume with block mode.
longhorn-ui:
![image](https://github.com/harvester/harvester/assets/37179253/fae1b9cf-923f-4f07-b783-c4741196577b)

host path /var/lib/longhorn:
![image](https://github.com/harvester/harvester/assets/37179253/038e6625-a2c3-402b-90c5-bc2f340550b7)

vm:
![image](https://github.com/harvester/harvester/assets/37179253/0fd3f171-0fff-4b1a-ab68-15619e6c84e9)

**Comment by WebberHuang1118** [comment]
@Captured77 
Harvester v1.1.0 utilizes LH v1.3.2, however, LH supports trim since LH v1.4.0 https://longhorn.io/docs/1.5.3/volumes-and-nodes/trim-filesystem/.

IIRC, LH doesn't support automatic trimming for block mode volume. Did you try to issue discard in the VM?

**Comment by Captured77** [comment]
> @WebberHuang1118  Harvester v1.1.0 utilizes LH v1.3.2, however, LH supports trim since LH v1.4.0 https://longhorn.io/docs/1.5.3/volumes-and-nodes/trim-filesystem/.
> 
> IIRC, LH doesn't support automatic trimming for block mode volume. Did you try to issue discard in the VM?

Thank you for your reply! You are right. LH surpport trim from LH 1.4.0. But It can trim the volme with the mode of filesystem! I try to mount this volume to the host. Sadlly.  It failed.

**Comment by WebberHuang1118** [comment]
How about issuing the discard in VM?
