### ISSUE TITLE
new green theme

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#493]

**Comment by TangStone** [comment]
@WuJun2016  Switch to Dark mode, should it be blue or green
![image](https://user-images.githubusercontent.com/15829074/110439593-9ed2fb00-80f2-11eb-97bd-c4297fc1422b.png)

**Comment by WuJun2016** [comment]
@TangStone  I think it should be green

**Comment by TangStone** [comment]
@DaiYuzeng Please change the color to green

**Comment by DaiYuzeng** [comment]
use green as primary color on dark mode

**Comment by TangStone** [comment]
Versions : master-dba9243a-head
Switch to Dark mode
![image](https://user-images.githubusercontent.com/15829074/110769783-89e19d80-8293-11eb-9596-95c6536a716b.png)
Validated
