### ISSUE TITLE
[TASK] Streamline add-on updates

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4937]
**Is your enhancement related to a problem? Please describe.**

If an add-on needs an update, we'll need to
- If the add-on's chart changes
    - Bump chart in harvester/charts (master and release branch)
    - Bump chart version in the upgrade path ([example](https://github.com/harvester/harvester/blob/d3dc81cae1045ab175a6510f52fa290c7e56263e/package/upgrade/addons/vm-import-controller.yaml#L8)).
    - Bump chart version in the installer manifest ([example](https://github.com/harvester/harvester-installer/blob/6fe07342f44224747370fa0c0664fecc53295939/pkg/config/templates/rancherd-22-addons.yaml#L9)).
    - Bump chart version in the installer build-bundle script ([example](https://github.com/harvester/harvester-installer/blob/6fe07342f44224747370fa0c0664fecc53295939/scripts/build-bundle#L28C4-L28C4))
- If the add-on image tag changes
    - Bump image tag in the upgrade path ([example](https://github.com/harvester/harvester/blob/d3dc81cae1045ab175a6510f52fa290c7e56263e/package/upgrade/addons/vm-import-controller.yaml#L13)).
    - Bump image tag in the installer manifest ([example](https://github.com/harvester/harvester-installer/blob/6fe07342f44224747370fa0c0664fecc53295939/pkg/config/templates/rancherd-22-addons.yaml#L18)).
    - Bump image tag in the build-bundle script ([example](https://github.com/harvester/harvester-installer/blob/6fe07342f44224747370fa0c0664fecc53295939/scripts/build-bundle#L29)).

**Describe the solution you'd like**

This requires multiple PRs to bump an add-on. We need to figure out how to streamline the process or reduce the places needing updates.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
After PR 750, we will look for a solution to check if all default image tags are packed into ISO.

Tags may be defined from top to down: 
```
Addon & ManagedChart; 
values.yaml of each chart; 
values.yaml of sub-chart; 
templates/other files in chart/sub-chart.
```
