### ISSUE TITLE
[ENHANCEMENT] Bump golangci-lint to a version after v1.51.0

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#4938]
**Is your enhancement related to a problem? Please describe.**

We bump golang to v1.20 in most of repositories. However, we didn't bump golangci-lint. The first release for golangci-lint to support golang v1.20 is v1.51.0. If we don't bump it, we may get OOM when we run `golangci-lint run`.

**Additional context**
https://github.com/golangci/golangci-lint/blob/master/CHANGELOG.md#v1510

**Comment by Vicente-Cheng** [comment]
Although the `node-manager` uses the `golangci-lint` v1.52.0, I still bump to the same version on this issue.
To make whole components with the same `golangci-lint` version. (NDM also does the same thing on the reviewing PR)

**Comment by FrankYang0529** [comment]
All PRs are merged. Close the issue.
