### ISSUE TITLE
[ENHANCEMENT] Bump rancher-logging chart version in Harvester v1.3.0

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4940]
**Is your enhancement related to a problem? Please describe.**

Bump the proper version of rancher-logging in Harvester v1.3.0

https://github.com/rancher/charts/tree/b4221314e3eb0fbf777a5b0ea74df3fcda80ed46/charts/rancher-logging/102.0.1%2Bup3.17.10

**Describe the solution you'd like**

Depends on the Rancher version used in Harvester v1.3.0, the rancher-logging and rancher-logging-crd need to be bumped to related new version.

We also need a new release of event-router after PR https://github.com/harvester/eventrouter/pull/5  and use the new image  in `rancher-logging`.

Tasks:

- [x] Bump harvester-eventrouter to v0.1.2 (https://github.com/harvester/harvester-installer/pull/628)
- [x] Bump rancher-logging-crd and rancher-logging chart version (https://github.com/harvester/harvester-installer/pull/629)

**Describe alternatives you've considered**

**Additional context**

https://github.com/harvester/harvester/issues/4782
Rancher: v2.7.9
RKE2: v1.26.x

**Comment by albinsun** [comment]
Tested together with #4941, close as fixed.
