### ISSUE TITLE
[ENHANCEMENT] Bump rancher-monitoring chart version in Harvester v1.3.0

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4941]
**Is your enhancement related to a problem? Please describe.**

Bump the proper version of rancher-monitoring in Harvester v1.3.0

**Describe the solution you'd like**

Depends on the Rancher version used in Harvester v1.3.0, the rancher-monitoring and rancher-monitoring-crd need to be bumped to related new version.

**Describe alternatives you've considered**

**Additional context**

https://github.com/harvester/harvester/issues/4782
Rancher: v2.7.9
RKE2: v1.26.x

**Comment by albinsun** [comment]
Provide test result on `master-6ca6acfd-head`, close as fixed.


## Environment
* Harvester
  * Version: `master-6ca6acfd-head`
  * Profile: QEMU/KVM, 2 nodes (8C/20G/500G)
  * ui-source: `Auto`


## Steps 
1. Enable `rancher-monitoring` and `rancher-logging` addons
   ![image](https://github.com/harvester/harvester/assets/2773781/14bcc1b7-ed93-4cae-92f3-d28a50ab377b)

1. Check charts are properly deployed/running
   * `rancher-monitoring` w/ `102.0.2+up40.1.2` :ballot_box_with_check: 
     Chart
     ![image](https://github.com/harvester/harvester/assets/2773781/4336e383-e2a6-465c-b85c-4161258800ea)
     Pod
     ![image](https://github.com/harvester/harvester/assets/2773781/b1a49a77-008b-40c5-bd5b-5c6e3515be71)


   * `rancher-logging` w/ `102.0.1+up3.17.10` :ballot_box_with_check: 
      Chart
      ![image](https://github.com/harvester/harvester/assets/2773781/d97ec60c-9c9d-4e16-873b-7d30d51c960a)
      Pod
      ![image](https://github.com/harvester/harvester/assets/2773781/9f442b48-9c49-44e6-8b0d-73dc03827a32)


   * `harvester-eventrouter` w/ `v0.1.2` :ballot_box_with_check: 
     ![image](https://github.com/harvester/harvester/assets/2773781/e86ee4ff-3487-489a-8023-331460040707)
