### ISSUE TITLE
[v1.2.2] [ENHANCEMENT] Grafana configmap upgrade in potential Harvester v1.2.2 version

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4942]
**Is your enhancement related to a problem? Please describe.**

For v1.2.1 ->  v1.2.2, we will bump a newer version of rancher-monitoring chart, check the configmap is upgraded, and grafana works as expected.
https://github.com/harvester/harvester-installer/pull/623#issuecomment-1875348543

**Describe the solution you'd like**

Enhance upgrade script to deal with this case.

**Describe alternatives you've considered**

**Additional context**

https://github.com/harvester/harvester/issues/4756

**Comment by w13915984028** [comment]
This issue may be validated with https://github.com/harvester/harvester/issues/5412 together, the `rancher-monitoring` addon and `grafana` link should work well in both new installation and upgrade path.

**Comment by albinsun** [comment]
Provide test results for new installation (`v1.2.2-dev-20240329`) and upgrade (`v1.2.1` -> `v1.2-f414942f-head`) case, both are `103.0.3+up45.31.1` as expectation, close as done.


## Environment
* Harvester
  * Profile: QEMU/KVM, 8C/16G/500G per node
  * ui-source: `Auto`


## Test Cases
### New Installation (3 nodes, `v1.2.2-dev-20240329`)
1. Setup harvester `v1.2.2-dev-20240329`
   * <details>
     <summary> Enable <b>rancher-monitoring</b> and <b>rancher-logging</b> addons
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/b5429de6-9789-4376-95b2-336d07e0ccbe)
     </details>

1. Check charts are properly deployed/running
   * <details>
     <summary> :green_circle: <b>rancher-monitoring</b> should be <code>103.0.3+up45.31.1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a8399b19-5d24-4f33-aae1-3e3e28a7a88b)
     Chart
     ![image](https://github.com/harvester/harvester/assets/2773781/8478f6aa-fe72-4fe4-9d08-635c05316437)
     Pod
     ![image](https://github.com/harvester/harvester/assets/2773781/cbea1a77-8060-4ae8-9947-2a751c982b7d)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle: via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/7072c6e0-532b-4f09-9239-6b940e0bca19)
     ![image](https://github.com/harvester/harvester/assets/2773781/85796102-a802-4ab9-abb1-79cf84859d0a)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/707ddc15-e5ce-4641-b465-666e5811bdf2)
     ![image](https://github.com/harvester/harvester/assets/2773781/6d44e865-b152-4c5a-8178-be767b7ab8df)
     </details>


### Upgrade from `v1.2.1` to `v1.2-f414942f-head` (Single node)
1. Setup harvester `v1.2.1`
   * <details>
     <summary> Enable <b>rancher-monitoring</b> and <b>rancher-logging</b> addons
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/5bb288d6-8330-4d87-a54a-642e2ab8b529)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle: via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/a5bde71f-d035-4c8f-bc4f-d2c3c5669f1a)
     
     Login
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/02c5763d-f631-414f-8ef2-f0a01943f763)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b3b1194d-53aa-44e2-9479-14d4bd15d5a6)

     Login
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/ee9679c1-1487-4591-9783-8d4c74eb0dfe)
     </details>


1. <details>
   <summary> Upgrade to <code>v1.2-f414942f-head</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/6a912cd0-d850-41d2-aff2-533654bbe204)
   </details>

1. Check charts version and status
   * <details>
     <summary> :green_circle: <b>rancher-monitoring</b> is <code>103.0.3+up45.31.1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b4fb9a7c-3ab3-45fb-9678-1adb14ff1f2e)
     ![image](https://github.com/harvester/harvester/assets/2773781/f17ef6f9-6a05-44da-a9c8-63ce8637d177)
     </details>


1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle:  via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/78230f78-126f-4ee6-8c1d-b1919ccfe3e9)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7013591a-069e-4e77-873f-3dee90413781)
     </details>


## Reference
1. PR: harvester/harvester-installer/pull/681
