### ISSUE TITLE
[ENHANCEMENT] rancher-agent image is not packed into Harvester ISO

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4944]
**Is your enhancement related to a problem? Please describe.**

When setting [cluster-registration-url](https://docs.harvesterhci.io/v1.3/advanced/index#cluster-registration-url), a new POD from image `rancher/rancher-agent` is created to fulfill the related task. From the observation when debugging https://github.com/harvester/harvester/issues/4756, the `rancher/rancher-agent` image is not packed into Harvester ISO.

For air-gapped environment, or slow internet environment, the setting may pend for a long time or fail.

**Describe the solution you'd like**

Pack the related `rancher/rancher-agent` image into Harvester ISO.

**Describe alternatives you've considered**

Update the document [cluster-registration-url](https://docs.harvesterhci.io/v1.3/advanced/index#cluster-registration-url), give user a clear note that, the Cluster should have a way to get the `rancher/rancher-agent` image from docker image hub or private image registry.

**Additional context**

Bump rancher image version in Harvester
https://github.com/harvester/harvester/issues/4782

**Comment by ibrokethecloud** [comment]
Users should set a system registry in rancher settings: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/authentication-permissions-and-global-configuration/global-default-private-registry

<img width="1467" alt="image" src="https://github.com/harvester/harvester/assets/19664014/0b1d8870-2896-40db-af4c-9e93451f778e">

Once this is done, the registration url is generated with image referencing the private registry

<img width="639" alt="image" src="https://github.com/harvester/harvester/assets/19664014/040c0368-12df-447d-83c3-9dc4c0f641e5">

**Comment by w13915984028** [comment]
@ibrokethecloud That's great. I will update the Harvester document to note this.

**Comment by w13915984028** [comment]
Harvester Document has been updated.
