### ISSUE TITLE
How to fix the system crash caused by configuring https-proxy without configuring no-proxy

### ISSUE THREAD

**Issue by yangzhenwnt** [harvester/harvester#4946]
Harvester version 1.2.1

Physical machine network segment 172.19.14.0/24

VIP: 172.19.14.252

Phenomenon:

In the Harvard dashboard settings -->HTTP proxy settings https://xxx.xx.com But the no proxy option was not set, causing the entire Harvester dashboard to crash.

Currently, the host is using kubectl to get node and view relevant information. The connection to the server 127.0.0.1:6443 was reused - did you specify the right host or port?

May I ask how to restore the Harvester dashboard

**Comment by w13915984028** [comment]
Try `kubectl get settings.harvesterhci.io -A`, find the related one, then `kubectl edit ...` to change it.

**Comment by yangzhenwnt** [comment]
api-server keeps restarting and cannot perform kubectl related operations.
![image](https://github.com/harvester/harvester/assets/62133366/96d9c374-fb99-4cda-9e6e-890752931d35)
