### ISSUE TITLE
[FEATURE] Show host role promote status on UI

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#495]
**Is your feature request related to a problem? Please describe.**

Show host role promote status on UI

related issue: #259

**Describe the solution you'd like**

*** Label  Role ***
`control-plane` means label `node-role.kubernetes.io/master="true"` is exist or label `node-role.kubernetes.io/control-plane="true"` is exist.

*** Promote Status *** 
The value of annotation `harvester.cattle.io/promote-status`, 
`none` means this annotation is not exist

*** Show Promote Status *** 
Show on UI

![image](https://user-images.githubusercontent.com/15064560/109465550-53da3780-7aa3-11eb-8590-4833ccf1a449.png)

Label  Role | Promote Status | Show Promote Status |  Show Promote Status(ZH)
-- | -- | -- | --
none | none | none | none
none | running | promoting | 角色升级中
none | failed | promote failed | 角色升级失败
none | unknown | promote halted | 角色升级中断
none | complete | restarting | 角色升级重启中
control-plane | none | none | none
control-plane | running | promoting | 角色升级中
control-plane | failed | promote failed | 角色升级失败
control-plane | unknown | promote halted | 角色升级中断
control-plane | complete | promote ~~complete~~ completed | 角色升级完成

**Describe alternatives you've considered**

**Additional context**

**Comment by futuretea** [comment]
So sorry, may be `promote complete` should be `promote completed` @WuJun2016

**Comment by WuJun2016** [comment]
promote complete => promote completed    (done)

**Comment by TangStone** [comment]
**Validation Scenarios**
1. From 2 nodes, expand to 3 nodes and observe the state change of the compute node
2. Remove one of the control-planes from 4 nodes and observe the state of the compute node

**The results are in accordance with the following table**

Label  Role | Promote Status | Show Promote Status |  Show Promote Status(ZH) | Validation
-- | -- | -- | -- | --
none | none | none | none | passed
none | running | promoting | 角色升级中 | passed
none | complete | restarting | 角色升级重启中 | passed
control-plane | none | none | none | passed
control-plane | running | promoting | 角色升级中 | passed
control-plane | complete | promote ~~complete~~ completed | 角色升级完成 | passed

**Exception Scenario Verification**
- Use the command `kubectl edit node harvester`,Modify `harvester.cattle.io/promote-status`

Label  Role | Promote Status | Show Promote Status |  Show Promote Status(ZH)  | Validation
-- | -- | -- | -- | --
none | failed | promote failed | 角色升级失败 | passed
none | unknown | promote halted | 角色升级中断 | passed
control-plane | failed | promote failed | 角色升级失败 | passed
control-plane | unknown | promote halted | 角色升级中断 | passed
