### ISSUE TITLE
[BUG] The prometheus pvc fails in v1.3.0 default 250 G disk installation 

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#4962]
**Describe the bug**

In Harvester v1.3.0, when install the cluster with default 250 G disk, the prometheus pvc fails

**To Reproduce**

1. Install v1.3.0 master-head cluster

2. Enable `rancher-monitoring` addon, will observe:

a. The POD `prometheus-rancher-monitoring-prometheus-0` fails to start due to PVC attached failed,

b. Try to attache the volume from LH UI, it reports:

>cannot attach volume pvc-69f37c10-4b79-4946-b6ed-66e8a9999588 because the engine image longhornio/longhorn-engine:v1.5.3 is not deployed on at least one of the the replicas' nodes or the node that the volume is going to attach to

c. From LH pod `longhorn-manager-qw2pv` log, it has:

> time="2024-01-09T10:10:48Z" level=error msg="There's no available disk for replica pvc-69f37c10-4b79-4946-b6ed-66e8a9999588-r-1a519857, size 53687091200" func="scheduler.(*ReplicaScheduler).ScheduleReplica" file="replica_scheduler.go:95"

```
harv41:/home/rancher # df -H
Filesystem                                              Size  Used Avail Use% Mounted on

/dev/sda4                                                16G  4.6G   11G  31% /run/initramfs/cos-state
/dev/sda2                                                44M  287k   40M   1% /oem
/dev/sda5                                               158G   33G  117G  22% /usr/local
tmpfs                                                    11G     0   11G   0% /tmp
/dev/sda6                                                81G  269M   77G   1% /var/lib/harvester/defaultdisk
```

After disable the `rancher-monitoring` addon, edit the config to set `30G` pvc size, the `prometheus` starts up.

**Expected behavior**

The default setting should works as usual. Increase the minimal disk size if required.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM as Harvester Node.

**Additional context**
Observed in test PR https://github.com/harvester/harvester-installer/pull/629

**Comment by bk201** [comment]
250G is not recommended for production use, I guess we can add a document to decrease the Prometheus PVC size or allow more overprovision in Longhorn for testing purposes.

**Comment by bk201** [comment]
Doc is published: https://docs.harvesterhci.io/v1.3/troubleshooting/monitoring#fail-to-enable-rancher-monitoring-addon
