### ISSUE TITLE
[Question] How can I monitor hard raid status?

### ISSUE THREAD

**Issue by dawid10353** [harvester/harvester#4968]
Hello,

How can I monitor hard raid status in harvester?
I connect harvester cluster (by official helm zabbix repo) to zabbix but "smart template" (https://www.zabbix.com/integrations/smart) show me:
"Failed to execute smartctl: Command execution failed: exit status 1."

How can I monitor hard raid status without install smartctl?
What is the official way?

Thanks for help

**Comment by Vicente-Cheng** [comment]
Hi @dawid10353 

IIRC, we have installed the `smartctl`. I thought you would like to use the wrapped `smartctl` of zabbix, right?

If yes, did Zabbix provide the container image so that you can run this image on the harvester cluster?

**Comment by dawid10353** [comment]
You are right. I don't know why zabbix doesn't see smartctl.
I installed zabbix agents on harvester cluster by helm (https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/browse?at=refs%2Fheads%2Frelease%2F6.0).

Still, how can I monitor hardware RAID status in Harvester?
Is there any "official" way?

**Comment by Vicente-Cheng** [comment]
> You are right. I don't know why zabbix doesn't see smartctl. I installed zabbix agents on harvester cluster by helm (https://git.zabbix.com/projects/ZT/repos/kubernetes-helm/browse?at=refs%2Fheads%2Frelease%2F6.0).
> 
> Still, how can I monitor hardware RAID status in Harvester? Is there any "official" way?

Hi @dawid10353, 
Sorry for the late reply.

IIUC, most hardware raid vendors provide the official tools for monitoring.
So, you need to install the official tools on Harvester or running on the toolbox container.
You can refer to the following:
- install extra package on Harvester https://docs.harvesterhci.io/v1.3/troubleshooting/os#how-can-i-install-packages-why-are-some-paths-read-only
- use toolbox image https://harvesterhci.io/kb/package_your_own_toolbox_image
