### ISSUE TITLE
[Question] how to "migrate" a VM from an image to a standalone VM?

### ISSUE THREAD

**Issue by ne0YT** [harvester/harvester#4969]
I imported some VMs manually (by using images), and now would like to have them as an auotonomous VMs.
also I would like ot import some VMs more directly by using the uploaded .qco2 instead of going the route of using an image.

**Comment by WebberHuang1118** [comment]
Do you mean using a custom image to start a VM? Rather than build an environment from scratch?

**Comment by ne0YT** [comment]
> Do you mean using a custom image to start a VM? Rather than build an environment from scratch?

no. to "unlink" an image from a VM.
so I could restore it on another harvester host from a Backup or to be able to delete the image I used to create the VM

**Comment by jrlittlefoot64** [comment]
I think you can clone it, then you can move the cloned image where you want

**Comment by WebberHuang1118** [comment]
We will provide [a backup including image](https://github.com/harvester/harvester/issues/2237) on Harvester v1.4.0. 
For Harvester v1.3.0 and before, you may export the image-backed volume as a new image, download it, and use the synthetic image in another cluster.
