### ISSUE TITLE
[TASK] Bump Longhorn to v1.6.0 in v1.3.0

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#4970]
**Is your enhancement related to a problem? Please describe.**

To provide better support, we need to ship Longhorn v1.6.x with Harvester v1.3.0.
Currently, Harvester v1.2.x has Longhorn v1.4.x, which will violate Longhorn's one-minor-version upgrade policy if we bump Longhorn. Longhorn team is working on the upgrade path validation and will support it: https://github.com/longhorn/longhorn/issues/7539

**Describe the solution you'd like**

Bump Longhorn to v1.6.x.

**Describe alternatives you've considered**

**Additional context**

**Comment by innobead** [comment]
ref: https://github.com/longhorn/longhorn/issues/7539

Let's start the integration after RC2 is out.

**Comment by lanfon72** [comment]
Verified Longhorn `v1.6.0` applied to Harvester  `v1.3.0-rc2`
Longhorn related (volumes, images, backups) automation tests all _**PASS**_ excepts known issues.

Waiting the case 2 described in https://github.com/harvester/harvester/pull/5087#issue-2113924381 that `v1.2.1` still using Longhorn `v1.4.3`, same as the latest _v1.2-head_: `v1.2-c5270e4d-head`, and the upgrade is blocked.

**Comment by lanfon72** [comment]
Verified Harvester `v1.2-head` upgraded to `v1.3.0-rc2` successfully, and Longhorn related automation tests all _PASS_ excepts known issues.
