### ISSUE TITLE
Import Harvester 1.2.1 in Rancher 2.8 both single node problem

### ISSUE THREAD

**Issue by gcecchi** [harvester/harvester#4971]
Hello,
just wanted to experiment with Harvester and Rancher integration.
I have installed Harvester 1.2.1 on single node (virtual machine) through PXE.
Dashboard accessible on mgmt ip after setting up the new password and all seems ok.
In console I see "Ready" for both Harvester Cluster and Node.
BTW: in Dashboard --> settings the cluster-registration-url is empty
Do I have to put here anything?
I have installed Rancher 2.8 on single node (virtual machine), installing Ubuntu 22.04 through PXE, then installing docker (version 24.0.7 community edition), then running the docker install command as describe here:
https://ranchermanager.docs.rancher.com/v2.8/pages-for-subheaders/rancher-on-a-single-node-with-docker
docker run -d --restart=unless-stopped \
  -p 80:80 -p 443:443 \
  --privileged \
  rancher/rancher:latest
Dashboard accessible after setting up the new password and all seems ok.
Now I would like to import the Harvester cluster and experiment the integration part. But I don't find correspondence between doc pages and other links and what I see. 
BTW: when imported through rancher will I be able to run also containers in my harvester cluster creating them from within rancher, or the harvester cluster will be confined to run only VM workloads?
If I select "Virtualization Management" in GLOBAL APPS section I'm proposed to "Import Existing". If I click the button I get a page where I only have to input a "cluster name"
See screenshot here:
https://drive.google.com/file/d/1v1a6qJtai9sUXUerzvKKxEUvIKQJZTsT/view?usp=sharing
but any name I put there I get a "Network Error" message:
https://drive.google.com/file/d/1MYLb95eD8qSqGjeIZtIW5yUgDMNG2BtF/view?usp=sharing

Does it depend on rancher being inside docker? Any further setting to do?
It seems that:
. from inside the rancher docker container I'm able to reach port 6443 of the Harvester mgmt ip.
. from inside the harvester server I'm able to reach port 443 of rancher ip
Thanks for any suggestion or link with documentation.
Gianluca

**Comment by khushboo-rancher** [comment]
@gcecchi I would suggest if you're experimenting with Harvester with Rancher, use Rancher v2.7 as per the [support matrix](https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-x/).
> BTW: in Dashboard --> settings the cluster-registration-url is empty

Initially, the url is empty because it is not registered with Rancher yet, you'll need to edit it and save the url provided by Rancher. Steps are [here](https://docs.harvesterhci.io/v1.2/rancher/virtualization-management#importing-harvester-cluster)

**Comment by gcecchi** [comment]
Thanks for the reply.
You are right, my fault. With 2.7.9 all went fine in importing harvester 1.2.1.
Rethinking about my steps, I did go through the support matrix. But then when searching the requirements to install rancher as single node I didn't put enough attention to the "latest" wording and so Rancher 2.8 was pulled/installed.
I have to say  that also the version specific link:
https://ranchermanager.docs.rancher.com/v2.7/pages-for-subheaders/rancher-on-a-single-node-with-docker
contains "latest" in the docker run command, while probably it should contain "v2.7.9", to avoid confusion.
After using "latest" I didn't consider that 2.8 was pulled in and forgot the support matrix, my bad.
Questions: from command line I can create pods/deployments in Harvester. Can i manage them from within Rancher GUI after importing it? i don't see how. Or harvester k8s can only managed by GUI for kubevirt VM workloads?
Also, can I use the Rancher local k8s env to manage containers workloads from gui? Or is it only intended to be used for its mgmt capabilities and I have to import another k8s cluster to manage deployments and pods?
Thanks,
Gianluca

**Comment by khushboo-rancher** [comment]
@gcecchi We would like to know your use case in details to understand what's your requirement exactly. I have put some doc reference to answer your questions, hope that helps.

If you are using Rancher to manage k8s cluster running on VMs in Harvester, [docs](https://docs.harvesterhci.io/v1.2/rancher/index) explains the steps, the page also contains the details for [Baremetal container workload support](https://docs.harvesterhci.io/v1.2/rancher/index#harvester-baremetal-container-workload-support-experimental).
If you are looking for Rancher Manager as a workload on the underlying Harvester cluster, the details are [here](https://docs.harvesterhci.io/v1.2/advanced/addons/rancher-vcluster)

Note: Baremetal container workload support and Rancher manager on underlying Harvester cluster are experimental features at this moment.

**Comment by gcecchi** [comment]
Thanks for your reply and the doc references. My use case at the moment is basically to familiarize with the features of Rancher and Harvester and have an idea of the possible implementation scenarios based on different needs.
Based on the docs it seems to me that:
. when you import Harvester in Rancher, you can manage by default only its kubevirt based VMs, through:
Hamburger  --> Virtualization Management. It works for me
. when enabling experimental features you mentioned above, from within Rancher you can also manage the containers' workloads inside the Harvester cluster, through:
Hamburger --> harvester-assigned-name that appears now in the "EXPLORE CLUSTER" section. It works for me
. when you import a generic k8s cluster (in my test case a K3S installed on a separate SLES 15 VM with  K3s_VERSION="v1.26.12+k3s1"), from within Rancher you can manage it in the "EXPLORE CLUSTER" section, where its name appears after a successful import phase. It works for me 
Let me know if I understood correctly, please.

The only doubt remained is about the Rancher "local" k8s cluster itself that I see in "EXPLORE CLUSTER" section: is it meant to be used as a regular normal k8s cluster with its workloads without particular limitations, or should I leave it dedicated to internal Rancher logics?

Thanks again,
Gianluca

**Comment by khushboo-rancher** [comment]
The local cluster is the Kubernetes cluster that is running the Rancher server workloads, it is not recommended to use it for general purposes but you can if needed.

**Comment by khushboo-rancher** [comment]
Closing this now. @gcecchi feel free to reopen if you have further doubts.
