### ISSUE TITLE
[BUG] VM state "Stopping" is ambiguous when starting VM which has affinity rule that can't be fulfilled

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#4982]
**Describe the bug**

When creating a vm which has affinity rule that can't be fulfilled, the state shows `Stopping`. It would be better to be other state because this vm is scheduling actually instead of `Stopping`

**To Reproduce**

1. Create a vm which has affinity rule that can't be fulfilled. For example, adding random nodeSelector which doesn't exist.
2. At this moment, it show `Starting`.
3. Stop it and start it again.
4. It shows `Stopping`

**Expected behavior**

The `Stopping` doesn't match the VM real state, it should be other state, such as scheduling or something which matches the VM real state.

**Support bundle**
None

**Environment**
 - Harvester ISO version: 1.2.1

**Additional context**

After I tested it, this [condition](https://github.com/harvester/dashboard/blob/ca9a835bb18ca07d74ae74e8f32642fbe133f4a9/pkg/harvester/models/kubevirt.io.virtualmachine.js#L600-L606) returns the `Stopping` with following variables.
- .spec.runStrategy: `"RerunOnFailure"`
- .vmi.status.phase: `"Scheduling"`
- .status.created: `true`
- .status.printableStatus: `"ErrorUnschedulable"`
- .status.conditions[0]
    - .message: `"Guest VM is not reported as running"` 
    - .reason: `"GuestNotRunning"` 
    - .type: `"Ready"`
- .status.conditions[1]
    - .message: `"0/1 nodes are available: 1 node(s) didn't match Pod's node affinity/selector. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling."` 
    - .reason: `"Unschedulable"` 
    - .type: `"PodScheduled"`

![image](https://github.com/harvester/harvester/assets/6960289/47df1934-53b2-4213-9711-13a219c160f8)

p.s. test2 isn't stopped yet after creating it in this screenshot.

**Comment by torchiaf** [comment]
Given that we have all required info to decode the unschedulable conditions, it should be relatively simple to change the `status` label on the UI.

**Comment by torchiaf** [comment]
Reopen for QA tests

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/harvester/harvester/assets/5169694/82b3d775-0be4-498b-b42c-a734089dd143)


Test Information
----
* Environment: **baremetal DL360G9 5 nodes**
* Harvester Version: **v1.3.0-rc1**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create a image for VM creation
3. Create a VM  with matching scheduling rule, Required key-value is not exist
4. VM should display `Unschedulable` state with error message.
