### ISSUE TITLE
[BUG] Cannot use 1.1T Data disk during install 

### ISSUE THREAD

**Issue by Gumbees** [harvester/harvester#4983]
**Describe the bug**

When trying to install Harverster 1.2.1 it states the data disk I want to use, 1.1T, is too small and 180 GB is required.

**To Reproduce**
1. Boot ISO
2. Select "Join an existing Harvester cluster"
3. Select Data disk "sdb 1.1T"
4. Get an error message that says "Disk size is too small. Minimum 180Gi is required".

**Expected behavior**

I should be able to use 1.1T disk as a data disk.

**Support bundle**

**Environment**
 - Harvester ISO version: 1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal Dell R420

**Additional context**

**Comment by bk201** [comment]
Sounds like https://github.com/harvester/harvester/issues/4734 to me, The message is not clear, it means the installation disk. What's the installation disk size? 250Gi is needed.

**Comment by Gumbees** [comment]
> Sounds like #4734 to me, The message is not clear, it means the installation disk. What's the installation disk size? 250Gi is needed.

That clears it up then. Installation disk size is 111.3G. I'll RAID 0 my OS disks to test this out. This is only a witness host in a home lab.

**Comment by Gumbees** [comment]
> > Sounds like #4734 to me, The message is not clear, it means the installation disk. What's the installation disk size? 250Gi is needed.
> 
> That clears it up then. Installation disk size is 111.3G. I'll RAID 0 my OS disks to test this out. This is only a witness host in a home lab.

This did solve my problem. Closing. Thanks again @bk201
