### ISSUE TITLE
[FEATURE] Adjust columns width

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#4989]
**Is your feature request related to a problem? Please describe.**

We need to revisit and fix columns width and layout.
Related issue: https://github.com/rancher/dashboard/issues/9821.

TBD, we may want to implement a mechanism to manually adjust the column widths and save them into user profiles.

**Comment by albinsun** [comment]
Hi @torchiaf ,
Please help to comment DoD/criteria of this enhancement.

**Comment by lanfon72** [comment]
Verified this feature has been applied.

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. In _Dashboard_, column width of **Reason** in _Events_ should be update to `130`
3. In _Hosts_, column width of **Name** should be update to `130`
4. In _Volumes_, column **Snapshot Counts** should be update to align `center`
5. In _Virtual Machines_, column width of **Name** should be update to `350`
6. In _Advanced/Storage Classes_, column **Number Of Replicas** should be update to align `center`
7. In _Networks/Cluster Networks/Configs_, header should not overlap
![image](https://github.com/harvester/harvester/assets/5169694/2d3af63c-af4d-40e6-afa8-b668395dfdb3)
