### ISSUE TITLE
Use the LabelValue component to refactor detail pages 

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#499]
We intend to use the `LabelValue` to instead of `LabeledInput` on detail pages.

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/110306937-5a375900-8039-11eb-817e-467ecb310586.png)
![image](https://user-images.githubusercontent.com/57614736/110307008-69b6a200-8039-11eb-80e8-d5a4c7283b2f.png)
