### ISSUE TITLE
Unable to ssh to harvester host.

### ISSUE THREAD

**Issue by MAH8U8** [harvester/harvester#4991]
I'm very new to #Harvester HCI. Just deployed a 2 node cluster and can log in through GUI, but cannot ssh. 

login as: admin
Keyboard-interactive authentication prompts from server:
| Password:
End of keyboard-interactive prompts from server
Access denied

**Comment by Vicente-Cheng** [comment]
Hi @MAH8U8, how did you create your cluster?
IIRC, the default login account was `rancher` instead `admin`

**Comment by MAH8U8** [comment]
Hi @Vicente-Cheng, 
Yes, the account is rancher and working now, thanks a lot!!

**Comment by Vicente-Cheng** [comment]
@MAH8U8, 
No problem! I will close this issue. Feel free to reopen it or create a new one if you encounter it again.

**Comment by MAH8U8** [comment]
Sure

Thanks
-Mahbub

> Sent from my cellphone, please excuse brevity and typos.
