### ISSUE TITLE
[ENHANCEMENT] Monitoring, Logging upgrade in v1.3.0

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5003]
**Is your enhancement related to a problem? Please describe.**

After https://github.com/harvester/harvester/issues/4940 and https://github.com/harvester/harvester/issues/4941, the related upgrade path should also be rechecked.

**Describe the solution you'd like**

Add related processing of addon upgrade.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
To QA:
In PR https://github.com/harvester/harvester-installer/pull/657 and https://github.com/harvester/harvester-installer/pull/658, the monitoring and logging versions are further bumped in Harvester v1.3.0.

Please validate the latest version, thanks.

**Comment by albinsun** [comment]
Provide test result on `v1.3-7cb8315c-head`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3-7cb8315c-head`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps
1. Setup a 3 node cluster and perform same version upgrade
   * <details>
     <summary> Upgrade success :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a5918fe7-0e1c-4249-aa36-22b097cf9268)
     </details>
   
1. Enable **rancher-monitoring** addon
   * <details>
     <summary>  Deploy Successful :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/502e53c7-1e20-4539-9d1c-91bf7c008136)
     </details>

   * <details>
     <summary> Version is <code>103.0.3+up45.31.1</code>  :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/c59d3b05-7292-46d4-859b-7d2545bc9366)
     </details>
    
   * <details>
     <summary> Grafana dashboard works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5cebbb27-f96d-477f-ba0b-09c9dc64615f)
     </details>

1. Enable **rancher-logging** addon
   * <details>
     <summary>  Deploy Successful :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/502e53c7-1e20-4539-9d1c-91bf7c008136)
     </details>

   * <details>
     <summary> Version is <code>103.0.0+up3.17.10</code>  :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6a80217d-7544-4745-ab05-c4d0c40c6d98)
     </details>

## Note
1. **rancher-monitoring**: [Fix CVE and bump monitoring to 103.0.3+up45.31.1](https://github.com/harvester/harvester-installer/pull/657#top)
2. **rancher-logging**: [Fix CVE and bump logging to 103.0.0+up3.17.10](https://github.com/harvester/harvester-installer/pull/658#top)
