### ISSUE TITLE
[ENHANCEMENT] Bump Rancher version in Rancher Manager (vCluster) add-on

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5016]
**Is your enhancement related to a problem? Please describe.**

Bump Rancher version to v2.7.9/10 or v2.8.1 in the add-on.
- Newer Rancher.
- To support newer RKE2 versions in the guest cluster.

**Describe the solution you'd like**

Bump Rancher version to v2.7.9/10 or v2.8.1 in the add-on.

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
addressed by: https://github.com/harvester/experimental-addons/pull/10

**Comment by bk201** [comment]
We eventually move to v2.8.2 since it's released.

**Comment by albinsun** [comment]
Provide test result on `v1.3.0-rc3`, close as fixed.

## Environment
* Harvester
  * Version: `v1.3.0-rc3`
  * Profile: QEMU/KVM, single node (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.8.2`
  * Profile: `rancher-vcluster`

## Steps 
1. Enable `rancher-vcluster` following https://docs.harvesterhci.io/v1.3/advanced/addons/rancher-vcluster
   * <details>
     <summary> Rancher version should be <code>v2.8.2</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6cda77f6-abe0-4de2-bb75-d11220b32990)
     </details>
   * <details>
     <summary> Rancher and spin up successfully and version is <code>v2.8.2</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/b432ea93-897e-4203-bfa9-9b99d7494385)
     </details>
   
1. Join Harvester to Rancher following https://docs.harvesterhci.io/v1.3/rancher/virtualization-management#importing-harvester-cluster
   * <details>
     <summary> Harvester is <code>Active</code> :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/b917dae9-fd2c-49f9-8863-6cb55ad1b212)
     </details>

1. Setup RKE2 cluster
   * <details>
     <summary> RKE2 cluster is <code>Active</code> :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/56c08798-79fa-40a6-a68d-0c05d36a2278)
     </details>

   * <details>
     <summary> harvester apps are <code>Active</code> :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/80b4914a-830f-40f5-9761-c6942f936779)
     </details>

   * <details>
     <summary> Deploy nginx with PVC :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/c946ebe2-e641-4ce3-b9e9-e5d7a7f810af)
     ![image](https://github.com/harvester/harvester/assets/2773781/c69cf230-2b91-4e03-9da7-a0fee5ade0cd)
     </details>

   * <details>
     <summary> Loadbalancer works :heavy_check_mark: 
     </summary>
 
     ![image](https://github.com/harvester/harvester/assets/2773781/788aad35-f1c6-4545-9105-915d7e878948)
     </details>
