### ISSUE TITLE
[FEATURE] Add Fleet support with Harvester

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#5018]
**Is your feature request related to a problem? Please describe.**
User should be able deploy and manage object like images, network etc using Fleet in a Harvester cluster.

Fleet examples - https://github.com/ibrokethecloud/harvester-fleet-demo

Test plan - https://harvester.github.io/tests/manual/advanced/fleet-support-with-harvester/

**Comment by irishgordo** [comment]
This looks good with:
- Harvester v1.3.0-rc1
- Rancher v2.7.9 (via V-Cluster)
- Rancher Dashboard Version: commit c3ae9bc14ad1a306025c0882eefde7baef3d046d ( containing: commit 65366810efe83db05512194589771b8c3a0a0914 

The GitOps is great :smile: 
Forked and did some mods / changes throughout to:
https://github.com/irishgordo/harvester-fleet-demo

![Screenshot from 2024-01-31 23-22-01](https://github.com/harvester/harvester/assets/5370752/97fd18f9-1a52-46c3-bb50-741b1346144d)
![Screenshot from 2024-01-31 23-20-22](https://github.com/harvester/harvester/assets/5370752/3da31f35-f4b3-43eb-8d33-0a3616042e95)
![Screenshot from 2024-01-31 23-16-49](https://github.com/harvester/harvester/assets/5370752/e1dc53f9-b814-4176-9a73-2cbe724ee288)
![Screenshot from 2024-01-31 23-12-23](https://github.com/harvester/harvester/assets/5370752/02eb2c99-180f-438f-9d45-28f59dec532c)
![Screenshot from 2024-01-31 23-09-52](https://github.com/harvester/harvester/assets/5370752/ff2f9960-60bc-41a3-86ab-fcfb7439a171)
![Screenshot from 2024-01-31 23-07-47](https://github.com/harvester/harvester/assets/5370752/9fa6e7fa-c047-4a71-8c4e-06d356953c53)
![Screenshot from 2024-01-31 23-06-20](https://github.com/harvester/harvester/assets/5370752/730ff5e0-d2c0-4d6f-a80d-d51185085464)
![Screenshot from 2024-01-31 23-04-23](https://github.com/harvester/harvester/assets/5370752/c576d543-1b24-473f-816f-fffecfb75a7f)

**Comment by irishgordo** [comment]
Encountering issue w/ creating `CloudInit` Resource, opened: https://github.com/harvester/harvester/issues/5110

**Comment by irishgordo** [comment]
Opening:
- https://github.com/harvester/harvester/issues/5132
- https://github.com/harvester/harvester/issues/5133

**Comment by irishgordo** [comment]
Moving back to 'Implement' as this will need Docs before it is closed out

cc: @jillian-maroket

**Comment by markhillgit** [comment]
moving to 1.4.0 to make sure there is adequate time to document

**Comment by jillian-maroket** [comment]
The doc has been updated.

PR: [590](https://github.com/harvester/docs/pull/590)
Doc: [Fleet Support (Experimental)](https://docs.harvesterhci.io/v1.3/rancher/rancher-integration#fleet-support-experimental)
