### ISSUE TITLE
Single Nic Deployment

### ISSUE THREAD

**Issue by kevinevans1** [harvester/harvester#5030]
Hello

I'm looking for guidance on howe to configure my Harvester instance to use a single NIC. I have successfully have the MGT network up and running. But I'm unable to ping or ssh to freshly created virtual machines.

Can you advise if it is possible to do this configuration ?

Thanks

**Comment by w13915984028** [comment]
When you are using single nic, you need to ssh into your host node first then ssh/ping your VM's IP.

As in this mode, the VM is using private IP address. It can ping internet, but not vice versa.

**Comment by kevinevans1** [comment]
I was trying to get direct access to my VM's as my main dev tools are on my local machine. Would the recommendation to have two nics for direct access ?

Thanks

Kevin

**Comment by w13915984028** [comment]
For direct access, the general solution is to add a second nic and put it in an indepedent VLAN, then the VM get IP from this VLAN, with it, the IP is directly reachable.

**Comment by kevinevans1** [comment]
Hey 

The dual nics work , but do not present the private up address in the portal.

Please close question.
