### ISSUE TITLE
[BUG] harvester-installer CI failed (docker save: Error response from daemon: read )

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#504]
**Describe the bug**

**To Reproduce**
Run harvester-installer ci

**Log**

**Additional context**
```bash
$ docker save quay.io/kubevirt/virt-launcher:v0.38.1 -o image.out
Error response from daemon: read /var/lib/docker/overlay2/14142766c26e92075713e727c84efc6431f4dbb7fbf72f3fcf5c7ff3c109ef77/diff/lib64: is a directory
```

**Comment by futuretea** [comment]
Use ctr to workaroundrancher/harvester-installer#49.  Need more investigate.

**Comment by gitlawr** [comment]
https://github.com/moby/moby/issues/42114

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-installer/pull/49 with changes from docker to ctr.

**Comment by futuretea** [comment]
https://github.com/kubevirt/kubevirt/issues/5571#issuecomment-832904637
