### ISSUE TITLE
[ENHANCEMENT] Make "LiveMigrateIfPossible" the default EvictionStrategy instead of "LiveMigrate"

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5049]
**Is your enhancement related to a problem? Please describe.**

KubeVirt fires an event with a severity of Warning when a VMI exists with an EvictionStrategy of LiveMigrate and it cannot be live migrated (i.e. the VMI is configured with a HostDevice.) This Warning event can trigger alerting in monitoring stacks.

When a Harvester user configures a VM with PCI Passthrough, it is understood that the VM cannot be live migrated. 

**Describe the solution you'd like**

KubeVirt recently merged a new EvictionStrategy, LiveMigrateIfPossible, which does not emit spurious warnings when a VMI is configured with a HostDevice.

Harvester 1.3.0-rc1 ships with a version of KubeVirt that includes this new EvictionStrategy.

**Describe alternatives you've considered**

**Additional context**

**Comment by torchiaf** [comment]
@connorkuehl Do we need a v1.2 backport for this? Isn't KubeVirt shipped with Harvester v1.3 ?

**Comment by connorkuehl** [comment]
Yes, 1.2, 1.3, and master all have a new-enough version of KubeVirt to where it needs to be backported through to 1.2

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4.0-dev-20240830**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create VM `vm1`
4. edit VM yaml of `vm1`
5. the value of `spec.evictionStrategy` should be `LiveMigrateIfPossible`
