### ISSUE TITLE
[BUG] helm install failed

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#505]
**Describe the bug**

**To Reproduce**
1. Provision a k8s cluster(v1.19.8)
2. Follow the instructions in https://github.com/rancher/harvester/blob/master/docs/app-mode-installation.md#option-1-install-with-helm

**Expected behavior**
Installation succeeded.

**Log**
```
$ helm install harvester harvester \
  --namespace harvester-system \
  --set longhorn.enabled=true,minio.persistence.storageClass=longhorn
W0304 15:14:06.265969   57420 warnings.go:70] apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(CDI.spec.infra): unknown field "workload" in io.kubevirt.cdi.v1beta1.CDI.spec.infra
```

**Environment:**
 - Harvester ISO version: chart on master branch
 - Installation Mode: app-mode

**Additional context**

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/115847048-1e274e80-a455-11eb-8308-67a7dc54839a.png)
