### ISSUE TITLE
[ENHANCEMENT] Bump Longhorn to v1.5.4 in v1.2 branch

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5056]
**Describe the solution you'd like**
Bump Longhorn to v1.5.4 in v1.2 branch.

**Comment by innobead** [comment]
1.5.4 is going to be released, so we need to rebase it later.

**Comment by bk201** [comment]
@FrankYang0529 Can you help bump v1.5.4, it's released.

**Comment by khushboo-rancher** [comment]
@noahgildersleeve Run/check all the e2e involving backup/restore and any manual test cases you think should be needed.

**Comment by FrankYang0529** [comment]
Close the issue since we have a new one v1.5.5.

https://github.com/harvester/harvester/issues/5553
