### ISSUE TITLE
[backport v1.2] [BUG] Device List, make input rows reactive

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5061]
**Describe the bug**

Original Issue: https://github.com/harvester/harvester/issues/4796
Commit to backport: https://github.com/harvester/dashboard/commit/bfede793e99d13d61d89254112bc1eb4d132502c

**Comment by irishgordo** [comment]
Thanks for the backport @torchiaf  - this looks good on:
- v2.8.2 Rancher via Rancher VCluster
- v1.2.2-rc1 Harvester

I'll go ahead and close this out
![Screenshot from 2024-04-26 16-39-06](https://github.com/harvester/harvester/assets/5370752/eab53e81-429c-4754-a290-c778655577e5)
