### ISSUE TITLE
[FEATURE] Improving Harvester Maintenance Mode

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5069]
**Is your enhancement related to a problem? Please describe.**
When setting a Harvester host into maintenance mode it will (try to) migrate all virtual machines on that node to other nodes in the cluster.
I want to have the possibility to not migrate all virtual machines on that node to other nodes in the cluster.

**Describe the solution you'd like**
For instance, a radio button where you can prevent the migration of virtual machines in the "Enable Maintenance Mode" pop-up.
Having the option to trigger (via an annotation or webhook) the execution of a script/command inside the VM that then could i.e. remove/disable the application.

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by votdev** [comment]
# Proposal
- The VMs that do not have to be migrated to other nodes when a node is set into maintenance mode must be labeled with `harvesterhci.io/maintain-force-shutdown`.
- When the maintenance mode is activated for a node, these labeled VMs are shut down to free their resources.
- The VMs are not started automatically if the maintenance mode is disabled for the node. At this point the VMs that have been shut down previously can not be identified because the reference to the owner node has been removed.
- Special actions that have to be done by the VM before shutting down can be implemented via systemd unit files in the VM itself or via the `PrePost` [container lifecycle hook](https://kubernetes.io/docs/concepts/containers/container-lifecycle-hooks/).
- If maintenance mode is forced via UI (by setting the checkbox in the dialog), this will override the custom settings per VM.

See https://github.com/harvester/harvester/pull/5984 for a up-to-date proposal.

**Comment by w13915984028** [comment]
This will be a good enhancement.

When user plan to put a node to `Maintenance Mode`, if UI opens a new page with more details, it will be better:

Support is sunch a new page, it lists all VMs on this Node per their migration ability:
 - ready to migrate, 
 - cannot migrate e.g. with vGPU or pci-paththrough, with dedicated scheduling policy/label, or VM has only the last active replica
 
 User can click the specific vm to open vm page, and do related actions like stop or migration to a desired node.

And when user clicks the `Maintenance Mode` button, display the migration status and progress of each vm on this page.

**Comment by votdev** [comment]
> This will be a good enhancement.
> 
> When user plan to put a node to `Maintenance Mode`, if UI opens a new page with more details, it will be better:
> 
> Support is sunch a new page, it lists all VMs on this Node per their migration ability:
> 
>     * ready to migrate,
> 
>     * cannot migrate e.g. with vGPU or pci-paththrough, with dedicated scheduling policy/label, or VM has only the last active replica
> 
> 
> User can click the specific vm to open vm page, and do related actions like stop or migration to a desired node.
> 
> And when user clicks the `Maintenance Mode` button, display the migration status and progress of each vm on this page.

These are very good additional suggestions for improvement, but they do not match the customer's current requirements that PR is trying to implement.

I would therefore suggest opening another issue to implement these suggestions for improvement separately and independently of the customer's requirements.

**Comment by innobead** [comment]
@votdev please add an HEP for this as well, as this is a new feature, even though you already have the implementation PR.

**Comment by albinsun** [comment]
Test **FAIL**, return to _Implement_.

`node-1` stuck on `Cordoned` 
* 2 VMs (_default_ and _migrate_) successfully migrate as expect
* 3 VMs (_shutdown_, _shutdown-and-restart-after-enable_ and _shutdown-and-restart-after-disable_) still `Running` on _node-1_

### Environment
* `harvester-v1.4.0-dev-20240918`
  * Profile: 3 nodes witness QEMU/KVM
  * ui-source: `Auto`

### Prerequisite
1. &NewLine;
   <details>
   <summary> Setup a 3 nodes witness cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/f99dd936-8360-4d77-afd8-35148b926134)
   </details>

   * _node-0_: default (12C/20G/500G)
   * _node-1_: default (12C/20G/500G)
   * _node-2_: witness (4C/4G)

2. &NewLine;
   <details>
   <summary> Create 5 VMs with different <code>harvesterhci.io/maintain-mode-strategy</code> label values
   </summary>

   * _default_: Does NOT specify, should behave like `Migrate`
     ![image](https://github.com/user-attachments/assets/78746907-326b-4e4a-95c9-86048f0765ea)
   * _migrate_: `Migrate`
     ![image](https://github.com/user-attachments/assets/dae2bdac-ecdc-4808-aa70-8d2693217801)
   * _shutdown_: `Shutdown`
     ![image](https://github.com/user-attachments/assets/648e7ea8-c709-467d-ac6b-c2fac20c676a)
   * _shutdown-and-restart-after-enable_: `ShutdownAndRestartAfterEnable`
     ![image](https://github.com/user-attachments/assets/0b0caab9-61af-44d5-bedf-8657bb1a475d)
   * _shutdown-and-restart-after-disable_: `ShutdownAndRestartAfterDisable`
     ![image](https://github.com/user-attachments/assets/a5844b13-8ce1-4f9c-9e43-2282610c28c9)
   </details>

   * _default_: Does NOT specify, should behave like `Migrate`
   * _migrate_: `Migrate`
   * _shutdown_: `Shutdown`
   * _shutdown-and-restart-after-enable_: `ShutdownAndRestartAfterEnable`
   * _shutdown-and-restart-after-disable_: `ShutdownAndRestartAfterDisable`


### Scenario
1. Enable Maintenance Mode
   * &NewLine;
     <details>
     <summary> <i>Given</i> 5 VMs with different <code>harvesterhci.io/maintain-mode-strategy</code> <code>Running</code> on <i>node-1</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/207134c2-7120-4e78-8eea-73febffadd8a)
     </details>

     * network: _mgmt-vlan1_

   * &NewLine;
     <details open>
     <summary> :x: <i>When</i> <i>node-1</i> Enables Maintenance Mode
     </summary>

     > _node-1_ stuck in `Cordoned`
     > ![image](https://github.com/user-attachments/assets/7a56e4e7-b1d2-4743-bb55-0fdbbc57b324)
     > ![image](https://github.com/user-attachments/assets/6ef110a6-d5f9-4172-bf5b-cfb67f9dcc61)
     </details>

   * &NewLine;
     <details open>
     <summary> :x: <i>Then</i> 5 VMs should be migrated or <code>Off</code>
     </summary>
     
     > Only 2 VMs _default_ and _migrate_ migrated to _node-0_ 
     ![image](https://github.com/user-attachments/assets/cfcc4227-67c8-423f-a918-1b982cc1fa78)
     </details>

     * :heavy_check_mark: _default_: Migrate to _node-0_ and no `maintain-mode-strategy-node-name`
     * :heavy_check_mark: _migrate_: Migrated to _node-0_ and no `maintain-mode-strategy-node-name`
     * :x: _shutdown_: `Off`
     * :x: _shutdown-and-restart-after-enable_: Restarted on _node-0_ and no `maintain-mode-strategy-node-name`
     * :x: _shutdown-and-restart-after-disable_: `Off` and `maintain-mode-strategy-node-name` is _node-1_


2. Disable Maintenance Mode
   
   > Not test yet


### Supportbundle
[supportbundle_CanNotEnterMaintenanceMode.zip](https://github.com/user-attachments/files/17092301/supportbundle_CanNotEnterMaintenanceMode.zip)

### Reference
1. HEP: https://github.com/harvester/harvester/blob/master/enhancements/20240605-enhanced-maintenance-mode.md

**Comment by votdev** [comment]
@albinsun You need to add the label `harvesterhci.io/maintain-mode-strategy` to `metadata.labels` and not to `spec.template.metadata.labels`. You need to add them AFTER the VM has been created, because the UI only supports to add `Instance Labels`. 

Because of that reason i've opened the PR https://github.com/harvester/dashboard/pull/1045 which will allow users to add `Labels`as well beside `Instance Labels`.

**Comment by votdev** [comment]
@albinsun BTW, you can also use the UI to set the `Maintenance Mode Strategy`.

[Bildschirmaufzeichnung vom 2024-10-08 14-44-08.webm](https://github.com/user-attachments/assets/5c70c82d-55c5-4325-b73b-6c187ca11aac)

**Comment by albinsun** [comment]
Hi @votdev

Retest by UI field `Maintenance Mode Strategy`.
`Shutdown` and `ShutdownAndRestartAfterDisable` has `Running` state instead of expected `Off`.
Please help to check, thank you.

> [!NOTE]
> Migration strategy set along with VM creation
> ![image](https://github.com/user-attachments/assets/bf1c4da8-b84e-4d7d-a08b-d7990093819a)


### Environment
* `harvester-v1.4.0-rc1`
  * Profile: 3 nodes witness QEMU/KVM
  * ui-source: `Auto`

### Test Step
1. <details>
   <summary> :green_circle: Setup a 3 nodes witness cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/4a03bea9-189b-48ff-aa4c-3ec6e7934efc)
   </details>

1. :green_circle: Create 4 VMs with different <code>harvesterhci.io/maintain-mode-strategy</code> on <b>node-1</b>
   ![image](https://github.com/user-attachments/assets/d19a894e-2d2f-4617-9280-746f2c60c329)
   * <details>
     <summary> migrate
     </summary>
     
     ![image](https://github.com/user-attachments/assets/6e73738d-f7b5-4b9c-a6df-72a073e7993a)
     </details>

   * <details>
     <summary> shutdown
     </summary>
  
     ![image](https://github.com/user-attachments/assets/abaf8723-8dc3-4a60-8d7b-c254b77518c2)
     </details>

   * <details>
     <summary> shutdown-and-restart-after-enable
     </summary>
  
     ![image](https://github.com/user-attachments/assets/e9927dbb-d808-4d62-9cdf-c82a690c296a)
     </details>

   * <details>
     <summary> shutdown-and-restart-after-disable
     </summary>
  
     ![image](https://github.com/user-attachments/assets/ab63c80c-f7c3-4343-abe3-7f02f104da4c)
     </details>
     
1. <details>
   <summary> :green_circle: <b>node-1</b> Enable Maintenance Mode
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3da79d53-b1d7-4fcb-a0ab-4f87dc995088)
   </details>

1. Check 4 VMs migration status
   * <details>
     <summary> migrate: Migrated to <b>node-0</b> and no <code>maintain-mode-strategy-node-name</code>
     </summary>

     * Basic Tab
       ![image](https://github.com/user-attachments/assets/20a0368f-0e23-4f31-89e5-21e71efe0b90)
     * No <code>maintain-mode-strategy-node-name</code>
       ![image](https://github.com/user-attachments/assets/71dd69bf-6260-443b-a58e-4fe1702fe0b6)
     * Migration Tab
       ![image](https://github.com/user-attachments/assets/839d416a-7cdf-456d-a2b9-e012c016cbfd)
     </details>

   * <details open>
     <summary> :red_circle: shutdown: <code>Off</code>
     </summary>
  
     * :x: Expect `Off` but `Running` (on <b>node-0</b>)
       ![image](https://github.com/user-attachments/assets/0e15c36e-81f3-45fb-9096-cbdf0232c5f0)
     * :heavy_check_mark: No <code>maintain-mode-strategy-node-name</code>
       ![image](https://github.com/user-attachments/assets/c8e2ae0a-dda2-4922-8def-7a382664cb9e)
     * :heavy_check_mark: Migration Tab
       ![image](https://github.com/user-attachments/assets/2a94c3bd-b00a-4e7a-968f-7a69e17ad408)
     </details>

   * <details>
     <summary> :green_circle: shutdown-and-restart-after-enable: Restarted on <b>node-0</b> and no <code>maintain-mode-strategy-node-name</code>
     </summary>
  
     * :heavy_check_mark: Running on <b>node-0</b>
       ![image](https://github.com/user-attachments/assets/4b3b6729-06ab-40c3-acd3-a3254a9416db)
     * :heavy_check_mark: No <code>maintain-mode-strategy-node-name</code>
       ![image](https://github.com/user-attachments/assets/92ec4a8e-adf7-427b-90ca-49ba16acd9cf)
     * heavy_check_mark: Migration Tab
       ![image](https://github.com/user-attachments/assets/88f0caa2-41ad-4a30-af81-f182137086b6)
     </details>

   * <details open>
     <summary> :red_circle: shutdown-and-restart-after-disable: <code>Off</code> and <code>maintain-mode-strategy-node-name</code> is <b>node-1</b>
     </summary>
  
     * :x: Expect `Off` but `Running` (on <b>node-0</b>)
       ![image](https://github.com/user-attachments/assets/c2298248-f52f-430b-93b4-4d614a300da7)
     * :heavy_check_mark: Has <code>maintain-mode-strategy-node-name</code>
       ![image](https://github.com/user-attachments/assets/bede3877-8817-4130-b377-5ccdb84d4fd9)
     * :heavy_check_mark: Migration Tab
       ![image](https://github.com/user-attachments/assets/9019e990-a746-41bb-bb3c-86d3c74ad2ac)
     </details>


## Supportbundle
[supportbundle_MigrationTag_2024-10-08T17-10-09Z.zip](https://github.com/user-attachments/files/17296922/supportbundle_MigrationTag_2024-10-08T17-10-09Z.zip)

**Comment by votdev** [comment]
@albinsun We have to wait until https://github.com/harvester/harvester/issues/6727 is backported to v1.4. After that you can do the testing again with v1.4.0-rc3.

**Comment by votdev** [comment]
[Bugfix](https://github.com/harvester/harvester/pull/6741) has been merged and should be available with next 1.4.0-rc3.

**Comment by albinsun** [comment]
Test basically looks fine.

However we found a negtive case error and record in #6835 about unexpected input value via **Edit as YAML**.
As test cases using valid values works fine, I am going to close this as done first and tracking further by new issues.

## Environment
* `harvester-v1.4.0-rc3`
  * Profile: Single node AMD64 QEMU/KVM//Bare-metal
  * ui-source: `Auto`


## Prerequisite
1. Create image _ubuntu-22.04-server-cloudimg-amd64.img_
1. Create VM network _mgmt-vlan1_
1. <details>
   <summary> Setup 3 nodes Harvester includes a witness node.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b283bd79-ed58-461b-a3d0-8f5b5799ca34)
   </details>


## Test Scenarios
### Configuration
1. :heavy_check_mark: Migrate
   * <details>
     <summary> Create by UI</summary>
     
     ![image](https://github.com/user-attachments/assets/dd582efb-1d45-476d-b467-2c1c8110d890)
     </details>
   * <details>
     <summary> Create by YAML takes the same effect as UI </summary>
     
     * VM created by YAML
       ![image](https://github.com/user-attachments/assets/1d25a3df-4db1-4b63-a2c1-4655c7f190a4)
     * Comparism
       ![image](https://github.com/user-attachments/assets/219793ce-c231-43e4-8f25-448f1acb6ef9)
     </details>

1. :heavy_check_mark: Shutdown
   * <details>
     <summary> Create by UI</summary>
     
     ![image](https://github.com/user-attachments/assets/fdcac165-9042-469f-bb95-c7f848c590e9)
     </details>
   * <details>
     <summary> Create by YAML takes the same effect as UI </summary>
     
     * VM created by YAML
       ![image](https://github.com/user-attachments/assets/9ebc0b0a-eab9-41b7-92d6-7322c49ba451)
     * Comparism
       ![image](https://github.com/user-attachments/assets/53cd8a70-c42f-46e6-adb2-a197d8aed8fe)
     </details>

1. :heavy_check_mark: Shutdown and Restart After Enable
   * <details>
     <summary> Create by UI</summary>
     
     ![image](https://github.com/user-attachments/assets/d0895dd1-ab3d-4bbc-a088-e396fb89bc86)
     </details>
   * <details>
     <summary> Create by YAML takes the same effect as UI </summary>
     
     * VM created by YAML
       ![image](https://github.com/user-attachments/assets/e3ff4da0-bfca-4a81-90fe-bb00ceac031b)
     * Comparism
       ![image](https://github.com/user-attachments/assets/90bc4e85-6c7b-48ca-a488-265893ab9a0e)
     </details>

1. :heavy_check_mark: Shutdown and Restart After Disable
   * <details>
     <summary> Create by UI</summary>
     
     ![image](https://github.com/user-attachments/assets/62279b94-44d0-4d6b-9f2c-c80d601d1fe1)
     </details>
   * <details>
     <summary> Create by YAML takes the same effect as UI </summary>
     
     * VM created by YAML
       ![image](https://github.com/user-attachments/assets/28a1c615-91d3-44bb-8afa-b5bf67fec800)
     * Comparism
       ![image](https://github.com/user-attachments/assets/d246aeb6-9c84-4aed-beb4-cee0d40e9e93)
     </details>


### Enable Maintenance Behavior
1. <details>
   <summary> :heavy_check_mark: Make sure all VMs on <i>node-1</i> and <b>Enable Maintenance Mode</b> on it
   </summary>
   
   * All VMs on _node-1_
     ![image](https://github.com/user-attachments/assets/ec5f48e1-9574-47bf-b7f7-64747a77158f)
   * **Enable Maintenance Mode** 
     ![image](https://github.com/user-attachments/assets/62a77d50-7473-44a4-a759-8b61ee709154)
   </details>

1. <details>
   <summary> :heavy_check_mark: <i>migrate</i>: Migrated to <i>node-0</i> and NO <code>maintain-mode-strategy-node-name</code>
   </summary>
   
   * Migrated to <i>node-0</i>
     ![image](https://github.com/user-attachments/assets/c52fdec6-1ef6-46ae-8e92-2f4247ed4a65)
   * NO <code>maintain-mode-strategy-node-name</code> annotation
     ![image](https://github.com/user-attachments/assets/e9b5d4ca-774e-4a0c-a7da-b10ecd8fb0b9)
   </details>

1. <details>
   <summary> :heavy_check_mark: <i>shutdown</i>: <code>Off</code> and NO <code>maintain-mode-strategy-node-name</code>
   </summary>
   
   * <code>Off</code>
     ![image](https://github.com/user-attachments/assets/0f758617-23d6-444c-b870-a1364c2e8bab)
   * NO <code>maintain-mode-strategy-node-name</code>
     ![image](https://github.com/user-attachments/assets/fb4129e1-353c-41aa-9bfd-665a01dba793)
   </details>

1. <details>
   <summary> :heavy_check_mark: <i>after-enable</i>: Restarted on <i>node-0</i> and NO <code>maintain-mode-strategy-node-name</code>
   </summary>
   
   * Before
     ![image](https://github.com/user-attachments/assets/0b02a86f-ac2a-4afa-bb31-3cf6ff07539d)
   * Running on <i>node-0</i>
     ![image](https://github.com/user-attachments/assets/6eff3694-8012-4f6e-b235-d63d77f2838c)
   * NO <code>maintain-mode-strategy-node-name</code>
     ![image](https://github.com/user-attachments/assets/5cb8b283-363d-4f22-9924-fd69869fbf8c)
   </details>

1. <details>
   <summary> :heavy_check_mark: <i>after-disable</i>: <code>Off</code> and <code>maintain-mode-strategy-node-name</code> is <i>node-1</i>
   </summary>

   * <code>Off</code>
     ![image](https://github.com/user-attachments/assets/3b46c0da-c55b-4e4b-98da-dffd53fa5cc1)
   * <code>maintain-mode-strategy-node-name</code> is <i>node-1</i>
     ![image](https://github.com/user-attachments/assets/bcdf5135-fb97-4db3-8001-84c29ac2d94b)
   </details>


### Disable Maintenance Behavior
1. <details>
   <summary> :heavy_check_mark: <i>node-1</i> in maintenance mode, VMs are migrated of stopped.
   </summary>
   
   * Host
     ![image](https://github.com/user-attachments/assets/55ff63c9-5c1b-4eff-8f79-78a60a52ff97)
   * VMs
     ![image](https://github.com/user-attachments/assets/05145898-17a3-4178-b2f4-d47023e6e947)
   </details>
  
1. <details>
   <summary> :heavy_check_mark: <b>Disable Maintenance Mode</b> on <i>node-1</i>
   </summary>
   
   * Disable Maintenance Mode
     ![image](https://github.com/user-attachments/assets/a84217f4-629a-477e-9a59-1f6d09495cb2)
   * VMs
     ![image](https://github.com/user-attachments/assets/e49929f6-cffc-429e-a51e-1ed2aeaf2464)
   </details>

   > * <i>migrate</i>: Not affected cuz already migrated in previous phase, still <code>Running</code> on <i>node-0</i>
   > * <i>shutdown</i>: Not affected, still <code>Off</code>
   > * <i>after-enable</i>: Not affected cuz already migrated in previous phase, still <code>Running</code> on <i>node-0</i>
   > * <i>after-disable</i>: Start on the disable-mainenance node.
