### ISSUE TITLE
[BUG] Second witness node's role is Management but NOT behave like management node

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5070]
According to https://github.com/harvester/harvester/issues/4840#issuecomment-1883190132
> Even if we try to set up 2 witness nodes, we still have one witness node.

Suppose the 2nd witness node should become and behave like managemant node.
Please help to check it's expected or not.

## Environment
* Harvester
  * Version: `v1.3.0-rc1`
  * Profile: QEMU/KVM, 2 -> 3 nodes
    * Default (D) node: 8C/16G/500G
    * Witness (W) node: 4C/8G/500G
  * ui-source: `Auto`
  * Longhorn: `v1.6.0-rc2`

## Steps 
1. Setup 2 nodes cluster (Default + Witness)
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/45ccb0a3-cc07-47b0-ae29-cdfe93b06116)
     </details>

   * <details>
     <summary> <b>node-0</b> is Management and <b>node-1</b> is Witness :heavy_check_mark: 
     </summary>
     
     node-0
     ![image](https://github.com/harvester/harvester/assets/2773781/327fe6f6-5683-4002-aeca-64cc76c0cbcd)
     node-1
     ![image](https://github.com/harvester/harvester/assets/2773781/2c8f5600-2f19-4fbe-b87a-27ef5dce242d)
     </details>

   * <details>
     <summary> Longhorn should has only 1 node :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/44d840f9-a2a7-4156-a175-0fb99f1b0592)
     </details>

2. Create a VM with some data
   * <details>
     <summary> VM is Running :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/f1b09099-d1a7-4c39-bdea-c5ca95b7a20c)
     </details>

   * <details>
     <summary> Volume is Ready, replica should be 1 (LH has 1 node) :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/8875d4b7-0406-4345-8746-08ac74a5985a)
     </details>

   
3. Adding Witness node-2
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/868b5fd2-6e60-4500-8ab5-63513e69a971)
     </details>

   * <details open>
     <summary> <b>node-2</b> should be and behave as Management node :x: 
     </summary>

     Role is `Management` but shows `Hardware-based virtualization is disabled or not supported. Hardware-based virtualization must be enabled before creating any Virtual Machines.`
     ![image](https://github.com/harvester/harvester/assets/2773781/c497e52e-0881-4e99-b444-8634b0b6ed64)
     </details>

   * <details open>
     <summary> LH should have 2 nodes :x: 
     </summary>
   
     LH still has 1 node only
     ![image](https://github.com/harvester/harvester/assets/2773781/5cadc862-159d-4119-ad5b-412ccc6961e5)
     Volume is Ready, but still one replica since only has 1 node
     ![image](https://github.com/harvester/harvester/assets/2773781/2b2ecd73-d5a0-4475-940e-2656e7ab689c)
     </details>

## Supportbundle
[supportbundle_dww_2024-01-31T10-11-10Z.zip](https://github.com/harvester/harvester/files/14110263/supportbundle_dww_2024-01-31T10-11-10Z.zip)

**Comment by Vicente-Cheng** [comment]
Hi @albinsun, 
I created a PR and updated the test plan for this issue.

**Comment by Vicente-Cheng** [comment]
Hi @albinsun, I thought you could test this issue by master-head.

**Comment by albinsun** [comment]
Provide test result on `master-c5ebd89b-head` for scenario 3 (DWW) [^2], close as fixed.


## Environment
* Harvester
  * Version: `master-c5ebd89b-head`
  * Profile: QEMU/KVM, 2 -> 3 nodes
    * Default (D) node: 8C/16G/500G
    * Witness (W) node: 4C/8G/500G
  * ui-source: `Auto`
  * Longhorn: `v1.6.0-rc3`


## Steps 
1. Setup 2 nodes cluster (Default + Witness)
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/406a257b-334c-4228-9ad4-5f0585236910)
     </details>

   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/440e8637-f9f7-4d8c-8cc7-2922e3d10501)
     </details>


   * <details>
     <summary> <b>node-1</b> is <code>Witness</code>/<code>worker</code>. :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/69eb4882-5e42-4f31-a882-d394156c288e)
     </details>

   * <details>
     <summary> Longhorn should has only 1 node :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/ae71cca0-6c64-44ff-ab18-b1e1023c6c91)
     </details>


2. Create a VM with extra volume and some data
   * <details>
     <summary> VM is Running :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/80ce9b37-45bb-430b-aef3-8e23dadf1a00)
     </details>

   * <details>
     <summary> Volume is Ready, replica should be 1 (LH has 1 node) :heavy_check_mark: 
     </summary>
   
     rootdisk
     ![image](https://github.com/harvester/harvester/assets/2773781/5d9d0636-0dcf-4f39-b218-087f34ed4875)
     disk-1     
     ![image](https://github.com/harvester/harvester/assets/2773781/916b3345-bcbe-4d2b-ba55-2b99c3537b8a)
     </details>

   * <details>
     <summary> Data check :heavy_check_mark:  
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/0b5a5b4e-3131-467a-9ace-b60b5ec3ec2a)
     </details>

   
3. Adding Witness **node-2**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/4ed7798e-798b-4164-931d-0f20b0af85d3)
     </details>

   * <details>
     <summary> <b>node-2</b> should be <code>Witness</code>/<code>worker</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/5e3df5d5-e220-4899-b92a-689b76680a67)
     </details>

   * <details>
     <summary> LH should still have 1 node :heavy_check_mark: 
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/64dda5c9-67c7-4dc4-9758-ff9aa07f8cd6)
     </details>


1. Checks
   * <details>
     <summary> Can NOT migrate VM to witness node :heavy_check_mark: 
     </summary>
     
     **node-1**
     ![image](https://github.com/harvester/harvester/assets/2773781/4ad020fd-c260-4089-81ca-6e6870853001)
     ![image](https://github.com/harvester/harvester/assets/2773781/81f9d576-0f51-43c0-beb3-b941259db877)

     **node-2**
     ![image](https://github.com/harvester/harvester/assets/2773781/bba71f0e-605f-49d3-aea2-5c636cd2b114)
     </details>
     
   * <details>
     <summary> Data check -> Reboot -> data check :heavy_check_mark:  
     </summary>
     
     Data check
     ![image](https://github.com/harvester/harvester/assets/2773781/b6178d34-ff52-450b-bdff-98314ff9f2c7)

     Reboot
     ![image](https://github.com/harvester/harvester/assets/2773781/799a8fb0-fd4a-43b9-b0fa-676897b7cb68)
     
     Not migrate to witness node
     ![image](https://github.com/harvester/harvester/assets/2773781/d29bba49-ab78-4f96-b5c2-7c97be9b09fe)

     Data check
     ![image](https://github.com/harvester/harvester/assets/2773781/09e1ef45-7095-45b6-9fe0-54c1a8db7671)
     </details>

   * <details>
     <summary> Stop -> Snapshot -> Restore Existing -> Data check  :heavy_check_mark: 
     </summary>
     
     Stop
     ![image](https://github.com/harvester/harvester/assets/2773781/55b48072-73f7-4c1f-832e-83785e21df15)

     Snapshot
     ![image](https://github.com/harvester/harvester/assets/2773781/9db57bac-6ec2-4fb3-8488-a5d4e482cbfd)

     Restore Replace Existing
     ![image](https://github.com/harvester/harvester/assets/2773781/61831168-dec1-47dd-9a71-9fea9e935005)

     Data Check
     ![image](https://github.com/harvester/harvester/assets/2773781/987ecc03-3e35-48f0-8d60-eee0769cb412)
     </details>



1. Adding **node-3** (4th) Default node
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c801ae10-4260-457d-bd61-84a90413fcdf)
     </details>
     
   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/03346a98-c23e-402c-9e30-5f71d459a724)
     </details>
 
   * <details>
     <summary> <b>node-1</b> is <code>Witness</code>/<code>etcd</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/3302043f-f1c5-4438-9c72-afa2b52f6f8f)
     </details>

   * <details>
     <summary> <b>node-2</b> is <code>Witness</code>/<code>worker</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a408a101-259c-4126-9664-75c9313f751e)
     </details>

   * <details>
     <summary> <b>node-3</b> is <code>Management</code> (promoted) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5ff1f89e-52cb-4fd2-bd9c-4c21a3e48202)
     </details>

   * <details>
     <summary> Longhorn should have 2 nodes (<b>node-0</b> and <b>node-3</b>) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/bb1a4ffe-74d9-4324-bbf8-6f938900cf52)
     </details>

1. Check
   * <details>
     <summary> Volume should be Ready but Degraded due to 2 replicas 
     </summary>
     
     rootdisk
     ![image](https://github.com/harvester/harvester/assets/2773781/37a36777-f102-450a-a4f4-f0cd4d0a20bf)
     disk-1
     ![image](https://github.com/harvester/harvester/assets/2773781/dcdd521f-e6cd-4ec8-9108-f15345e8dbc5)
     </details>

   * <details>
     <summary> Data check -> Restart -> data check :heavy_check_mark:  
     </summary>
     
     Check
     ![image](https://github.com/harvester/harvester/assets/2773781/2830a3f4-f427-4dc7-bce8-690c10ed351d)
     Restart
     ![image](https://github.com/harvester/harvester/assets/2773781/5b7edaef-58d3-4d3f-9fdd-00130c579961)
     Check
     ![image](https://github.com/harvester/harvester/assets/2773781/99e01b5f-8783-41b5-bb74-441b6871ff77)
     </details>

   * <details>
     <summary> Stop -> Restore Existing -> Data check :heavy_check_mark: 
     </summary>
     
     Stop
     ![image](https://github.com/harvester/harvester/assets/2773781/3223b2eb-b6ec-48ce-a78b-b4421d3b757b)
     
     Restore
     ![image](https://github.com/harvester/harvester/assets/2773781/92f3210f-0456-4ab5-b5f0-de37497b6fe2)
     </details>


1. Rancher by `rancher-vcluster` [^1]
   * <details>
     <summary> Enable <b>rancher-vcluster</b> and can access Rancher :heavy_check_mark:
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7c7661a0-23d9-4b67-a59d-f638f9bdab56)
     </details>
     
   * <details>
     <summary> Import Harvester to Rancher :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ee8701b1-e652-4e43-be2e-8de15ad11e50)
     </details>

   * <details>
     <summary> Create RKE2 cluster :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cf054138-0e67-4782-bf65-4b5617d1af5d)
     ![image](https://github.com/harvester/harvester/assets/2773781/5a8e9127-be73-4ee1-b676-570198dfa3d7)
     </details>

   * <details>
     <summary> Deploy Nginx w/ pvc and LB :heavy_check_mark: 
     </summary>
     
     PVC is mount
     ![image](https://github.com/harvester/harvester/assets/2773781/eacfac3b-aabb-4099-b355-26ecf92ab476)
     
     LB works
     ![image](https://github.com/harvester/harvester/assets/2773781/5e1e2649-761d-4b8b-b897-75d4ca25d3de)
     </details>


1. Maintenance and Drop etcd **node-1**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>
          
     ![image](https://github.com/harvester/harvester/assets/2773781/a38b8632-2a4e-4629-a660-ca73e1c20423)
     </details>
     
   * <details>
     <summary> <b>node-0</b> is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/807f01e6-bf04-4c43-9b50-53af8f312a02)
     </details>

   * <details>
     <summary> <b>node-2</b> is <code>Witness</code>/<code>etcd</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9f30054d-dbf2-4528-b608-00db7e310f79)
     </details>

   * <details>
     <summary> <b>node-3</b> is <code>Management</code> (promoted) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5d644384-64bb-44b9-bbc3-909e5604dcc5)
     </details>

1. Check
   * <details>
     <summary> VM Data check -> Restart -> data check :heavy_check_mark:  
     </summary>
     
     Check
     ![image](https://github.com/harvester/harvester/assets/2773781/e11a2c3d-c784-453d-80d7-08d420a29376)

     Restart
     ![image](https://github.com/harvester/harvester/assets/2773781/cb7c95eb-d38a-4ce8-9b2f-54de55981105)

     Check
     ![image](https://github.com/harvester/harvester/assets/2773781/ae78842b-9e64-4e72-8d17-f385c3d0a0b6)
     </details>

   * <details>
     <summary> VM Stop -> Restore Existing -> Data check :heavy_check_mark: 
     </summary>
     
     Stop
     ![image](https://github.com/harvester/harvester/assets/2773781/100297c8-5fe7-4346-ab71-619e134f9d98)
     
     Restore
     ![image](https://github.com/harvester/harvester/assets/2773781/cdfa2e54-dc52-4ca7-afa1-ec55adcee57e)
     ![image](https://github.com/harvester/harvester/assets/2773781/00139805-4297-4582-b02b-9192b9207b10)
     </details>

   * <details>
     <summary> <code>rancher-vcluster</code> still works :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/90981e00-bd7a-4cb8-b54c-08b4445c3a44)
     ![image](https://github.com/harvester/harvester/assets/2773781/b04e8b99-8299-4252-8f84-5092f67b3755)
     </details>

1. Now we enter the **DWD** scenario.


[^1]: https://docs.harvesterhci.io/v1.3/advanced/addons/rancher-vcluster
[^2]: https://github.com/harvester/harvester/issues/3266
