### ISSUE TITLE
Transition from VMware to Harvester

### ISSUE THREAD

**Issue by IT-Gandalph** [harvester/harvester#5073]
Hello,

  we are a medium manufacturing company and we are currently using ISCSI for all things storage to on-prem Netapps and HP 3PAR is there a way to easily integrate these NAS via ISCSI to Harvester either way of Longhorn or direct?

**Comment by ibrokethecloud** [comment]
we recently introduced support for 3rd party csi in harvester: https://docs.harvesterhci.io/v1.2/advanced/csidriver, not sure if this meets you requirements.

we would like to understand more about your environment, and if a GH issue is not the right place then please feel free to reach out to us on rancher-users slack.

**Comment by ibrokethecloud** [comment]
a more detailed example: https://harvesterhci.io/kb/install_netapp_trident_csi

**Comment by asettle** [comment]
Hi @IT-Gandalph, how is this progressing? Can we help further?

**Comment by markhillgit** [comment]
A new article is here about how to use iscsi directly https://harvesterhci.io/kb/install_iscsi_firmware_install_boot
