### ISSUE TITLE
[BUG] ISO size is bigger than 2GB (release file max size)

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#508]
**Describe the bug**

currently, iso size grows to 2.1G

**To Reproduce**
1. run harvester-installer ci
2. check iso size

**Expected behavior**

iso size is smaller than 2G

**Log**

https://github.com/futuretea/harvester-autobuild/runs/2030680047?check_suite_focus=true
```bash
(node:5374) UnhandledPromiseRejectionWarning: RangeError [ERR_FS_FILE_TOO_LARGE]: File size (2181070848) is greater than possible Buffer: 2147483647 bytes
```

```bash
$ ll dist/artifacts
-rw-r--r-- 1 root root 2.1G  3月  4 21:17 harvester-amd64.iso
-rw-r--r-- 1 root root  87M  3月  4 21:17 harvester-initrd-amd64
-rw------- 1 root root  12M  3月  4 21:17 harvester-vmlinuz-amd64
```

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
let's move the full iso image to the GCP first before we can get full IT support of this from SUSE, additionally let's add another ISO image without offline-images to the GH release. cc @gitlawr

**Comment by DoNotSayYes** [comment]
Validated on this site
https://drone-pr.rancher.io/rancher/harvester-installer/166/1/2
