### ISSUE TITLE
[BUG] Need adjust harvester chart version in harvester-installer before release

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#509]
**Describe the bug**

After installer by iso, the job of harvester installation always `Error`

**To Reproduce**
1. Install harvester by iso

**Expected behavior**

The job of harvester installation will complete

**Log**

```bash
Error: failed to download "https://10.43.0.1:443/static/charts/harvester-0.1.0.tgz" (hint: running `helm repo update` may help)
```

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
**Validation Version**
- master-3d9efd26-head

**Steps**
1. Install harvester by iso
2. View helm-install-harvester pod and  harvester pod logs
- `kubectl logs -f helm-install-harvester-pmj2r -n kube-system`
- `kubectl logs -f harvester-9cffd97b8-hq8ts -n harvester-system`

**Results**
1. Successful deployment
2. No error reported in the logs
