### ISSUE TITLE
[BUG] The apply-manifests job in a previous upgrade updates the `SystemServicesUpgraded` condition of the current upgrade

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5090]
**Describe the bug**

The `apply-manifests` job in a previous upgrade updates the `SystemServicesUpgraded` condition of the current upgrade.

**To Reproduce**
1. Upgrade from v1.2.1 to v1.2-head.
2. Upgrade v1.2-head to v1.3-head immediately (< 7 days).
3. The "upgrade system service" part is complete even though the `apply_manifest` job is still running. And harvester starts cordoning the first node to upgrade the node. The pre-drain job can't start because apply_manifest job still running.
4. If the apply_manifest is complete, the pre-drain job should start and the upgrade continues.

**Expected behavior**

The second upgrade's "upgrade system service" progress should not complete if apply_manifest job still running.

**Additional context**

Note this issue is found while testing upgrade two minor versions in a short time, for most use cases the user can't see it because two upgrades are not to be performed so close.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.3-4372cbc4-head` (24/03/01). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ When the second upgrade apply manifest job is running, the "Upgrade System Service" progress is running. They both complete at the same time. $~~$</summary>

  1. When the apply manifest job complete, the "Upgrade System Service" progress bar also complete

  https://github.com/harvester/harvester/assets/29251855/5dfa2fb5-bd4b-40f2-8b14-7deb54baf965
  
  ![image](https://github.com/harvester/harvester/assets/29251855/3f58e0a4-393d-4bd1-be94-6546acf8a725)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Can successfully upgrade to v1.3-head  $~~$</summary>

  ![image](https://github.com/harvester/harvester/assets/29251855/13a90803-26be-419e-9501-c654776b22f6)


 </details>

### Test Information
* Test Environment: Three nodes harvester on bare metal machines
* Harvester version: `v1.3-4372cbc4-head` (24/03/01)

### Verify Steps
<details><summary> Check the second upgrade process </summary>

  1. Create the v1.2.1 Harvester cluster
  2. Upgrade to v1.2-head
  3. After upgrade complete, prepare another upgrade to v1.3-head
  4. Wait until the upgrade progress proceed to `Upgrading System Service` stage
  5. Open K9s and check the apply manifest job logs
  6. After the apply manifest complete, refresh the Harvester to check the upgrade progress 
  7. Ensure when the apply manifest job is running, the upgrade is also running on the stage of `Upgrading System Service`

</details>
