### ISSUE TITLE
[Doc] Add retain of supportbundle file and manual download into troubleshooting

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5094]
**Is your doc request related to a problem? Please describe or add related issue ID.**

**Describe the solution you'd like**

Regarding @Martin-Weiss 's question in #3383 , we can use following workaroud at the moment.

1. Click `Generate supportbundle` from Harvester WebUI
2. When the progress is about 20%, close the WebUI page
3. Check support-bundle status from kubectl
```
# kubectl get supportbundle -A -oyaml
apiVersion: v1
items:
- apiVersion: harvesterhci.io/v1beta1
  kind: SupportBundle
  metadata:
    creationTimestamp: "2024-02-02T11:18:09Z"
    generation: 5
    name: bundle-htl5f
    namespace: harvester-system
    resourceVersion: "1218311"
    uid: a3776373-05fe-4584-8a9a-baac3fa91bbf
  spec:
    description: sp1
    issueURL: ""
  status:
    conditions:
    - lastUpdateTime: "2024-02-02T11:18:38Z"
      status: "True"
      type: Initialized
    filename: supportbundle_db25ccb6-b52a-4f9d-97dd-db2df2b004d4_2024-02-02T11-18-10Z.zip
    filesize: 8868712
    progress: 100
    state: ready
kind: List
metadata:
  resourceVersion: ""
```
4. curl/wget the SB file via
```
curl -k https://192.168.122.199/v1/harvester/supportbundles/bundle-htl5f/download?retain=true -o sb2.zip
```
5. check the SB, it's still there
```
 # kubectl get supportbundle -A
NAMESPACE          NAME           ISSUE_URL   DESCRIPTION   AGE
harvester-system   bundle-htl5f               sp1           114s
```
6. Those 2 setting will help clean the resources.
https://docs.harvesterhci.io/v1.3/advanced/index#support-bundle-timeout
https://docs.harvesterhci.io/v1.3/advanced/index#support-bundle-expiration

Refer https://github.com/harvester/harvester/issues/3383#issuecomment-1923616964

**Comment by w13915984028** [comment]
After https://github.com/harvester/harvester/issues/5093 is done, we need to further update the document.

**Comment by Yu-Jack** [comment]
Just provide another idea, we could give the command about how to construct the URL like below and add some explanation.

```sh
IP=$(kubectl get ingress rancher-expose -n cattle-system -o=jsonpath='{.status.loadBalancer.ingress[0].ip}')
SUPPORT_BUNDLE_NAME=$(kubectl get supportbundle -A -o=jsonpath='{.items[0].metadata.name}')
curl https://$IP/v1/harvester/supportbundles/$SUPPORT_BUNDLE_NAME/download?retain=true -o sb.zip
```

p.s If you have multiple support bundles here, you could execute `kubectl get supportbundle -A` to pick one you want to replace `$SUPPORT_BUNDLE_NAME`.

**Comment by w13915984028** [comment]
The workaround was added to document, close issue.
