### ISSUE TITLE
[BUG] Error message is not hidden + validation is not triggered immediately

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5096]
![Peek 2024-02-02 12-56](https://github.com/harvester/harvester/assets/1897962/61824c4c-e71c-4e89-98db-ebc6c060ca00)

**Describe the bug**
When installing Harvester via ISO, on the disk setup page an error message is not hidden in some situations. Additionally the validation of the `Persistent size` field should be triggered immediately when the field is left. Right now the validation is only done before switching to the next page (e.g. when accepting the MBR settings with enter or key-down).

**To Reproduce**
See above

**Expected behavior**
- The error message should be hidden when the entered value is valid.
- The `Persistent size` value should be validated immediately when the input field loses focus.

**Support bundle**

n/a

**Environment**
 - Harvester ISO version: v1.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VM test environment

**Additional context**
n/a

**Comment by irishgordo** [comment]
@votdev -thanks for this fix :smile: :+1: 
This looks great in v1.4.0-rc4, closing this out.
![Screenshot from 2024-10-24 11-08-02](https://github.com/user-attachments/assets/aa6a9170-53ab-4c7a-88ad-37bfc98fcee2)
![Screenshot from 2024-10-24 11-07-39](https://github.com/user-attachments/assets/7f3197c7-8f62-405d-95e0-ea8fe52bc94b)

https://github.com/user-attachments/assets/7b90da48-c13d-4ea9-ba47-2e094ddf879e
