### ISSUE TITLE
[BUG] Disk page in Installer requires pressing Enter two times before switching to next page

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5097]
**Describe the bug**
After the user entered all information in the disk page it is still necessary to press `Enter` or `Key-Down` twice at the `Use MBR partitioning scheme` form control before switching to the next (Hostname) page. This is confusing for the user because there is no reason to do so.

The main problem is this [line of code](https://github.com/harvester/harvester-installer/blob/b402b17c9a0d44f6c220c21e8b3ff700752ab0f9/pkg/console/install_panels.go#L474).

With https://github.com/harvester/harvester-installer/pull/649 and setting `diskConfirmed = true` some [lines above](https://github.com/harvester/harvester-installer/blob/b402b17c9a0d44f6c220c21e8b3ff700752ab0f9/pkg/console/install_panels.go#L471) should fix that behaviour.

**To Reproduce**
1. Go to disk page
2. File all data
3. After going to the `Use MBR partitioning scheme` field it is necessary to press `Enter` or `Key-Down` twice to switch to the `Hostname` page.

**Expected behavior**
When the page is valid the switch to the next page should be done immediately. This means it is only necessary to confirm the selected `Use MBR partitioning scheme` value once.

**Support bundle**

n/a

**Environment**
 - Harvester ISO version: v1.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VM test environment

**Additional context**
n/a

**Comment by irishgordo** [comment]
@votdev  - thanks so much for the fix :smile: :+1:  - this looks good on master-head, bare-metal


https://github.com/harvester/harvester/assets/5370752/0d3db2e1-fa8a-42f0-931b-7a12b9f2fc0a


https://github.com/harvester/harvester/assets/5370752/90204894-6ee8-4fdd-802a-f7700abed181



I'll go ahead and close this out :+1: :smile:
