### ISSUE TITLE
[FEATURE] Configure loop protection for harvester-br0

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#510]
**Is your feature request related to a problem? Please describe.**

If over one NIC in the same network attach with harvester-br0, it cause a L2 loop. 

**Describe the solution you'd like**

Set STP on. By the way, I have not found a ready-made library written with go to configure STP.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by guangbochen** [comment]
we only need to verify whether enable the STP configuration on the switch will address the above case, for the current stage code change is not required.

**Comment by yasker** [comment]
Close as stale. Feel free to reopen if needed.
