### ISSUE TITLE
[BUG] Can't Enable SR-IOV GPU in UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5112]
**Describe the bug**

You can't enable SR-IOV GPU in the UI

**To Reproduce**
1. Enable both `pcidevices-controller` and `nvidia-driver-toolkit` addon on a system with a GPU installed
2. Navigate to SR-IOV GPU Devices in the left sidebar
3. Enable one of the GPUS by clicking the three dots on the right and selecting enable
**Expected behavior**

The GPU should enable and be available as an option in vGPU devices

**Support bundle**

[supportbundle_b580a14b-9c0c-465c-ad49-dcdde8cfbb84_2024-02-06T01-37-41Z.zip](https://github.com/harvester/harvester/files/14173803/supportbundle_b580a14b-9c0c-465c-ad49-dcdde8cfbb84_2024-02-06T01-37-41Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node DL360 bare metal

**Additional context**

Found while testing #2764 . 
![Greenshot 2024-02-05 17 59 31](https://github.com/harvester/harvester/assets/83787952/8ee6e42d-088c-4a38-a460-5a8c6ce38496)

It's worth noting that on this cluster there are 2 nodes. Both have GPUs, but one them shouldn't support this feature. The issue might be related to the feature check on the chipset.

**Comment by khushboo-rancher** [comment]
cc @ibrokethecloud

**Comment by ibrokethecloud** [comment]
There are 2 issues:

1. nvidia driver toolkit addon needs a UI enhancement to allow users to specify an override image and location for GPU driver. Currently enabling the addon without editing the yaml results in an invalid endpoint definition as a result of which the driver is never installed. @torchiaf need your assistance on this.
2. the 2nd node in the cluster has a NVIDIA GPU which only supports MIG mode vGPU. These GPU's should be ignored by the pcidevices controller and the PR: https://github.com/harvester/pcidevices/pull/65 addresses the same.

**Comment by noahgildersleeve** [comment]
Validated in master-a2c98e96-head (build right after v1.3.0-rc4). Closing as fixed.
