### ISSUE TITLE
[FEATURE] Add Harvester node driver

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#512]
**Is your feature request related to a problem? Please describe.**
Add Harvester node driver of Rancher to enable stage a k8s cluster directly with the RKE.

**Describe the solution you'd like**
- build a Harvester node driver using the docker-machine mechanism
- support metadata/userdata injection, test the target OS to be compatible with the requirements of RKE
- default to support `Ubuntu/openSUSE` 

**Additional context **
- [optional] considering to support `VM clone` mode, depends on https://github.com/longhorn/longhorn/issues/1815

**Comment by futuretea** [comment]
related issues: #590

**Comment by futuretea** [comment]
If we want to support opensuse/sles：
- [ ] need rancher/install-docker support opensuse/sles (https://github.com/rancher/rancher/issues/31817)
- [x] need rancher/machine support opensuse/sles （v0.15.0-rancher53 at least to support opensuse）
- [ ] need rancher bump rancher/install-docker and rancher/machine

**Comment by guangbochen** [comment]
link to repo https://github.com/harvester/docker-machine-driver-harvester

**Comment by TangStone** [comment]
Validate version in v0.2.0-rc5
1. Add harvester Node Template  ,the configuration is as follows
![image](https://user-images.githubusercontent.com/15829074/116662180-05281b80-a9c8-11eb-9676-38eaccd77768.png)
2. Adding a harvester cluster, the configuration is as follows, cluster options default
![image](https://user-images.githubusercontent.com/15829074/116662802-d2caee00-a9c8-11eb-9482-68af492c5d04.png)
3. View cluster creation success
![image](https://user-images.githubusercontent.com/15829074/116664780-80d79780-a9cb-11eb-8502-d66352d8f67e.png)
![image](https://user-images.githubusercontent.com/15829074/116665806-c8aaee80-a9cc-11eb-874c-adbc92147945.png)
4. Verify that the cluster was created successfully
![image](https://user-images.githubusercontent.com/15829074/116665623-94373280-a9cc-11eb-9d78-948bcc0ba437.png)
5. Delete cluster successfully
