### ISSUE TITLE
[BUG] Downloading ISO fails if it is hosted on CDN

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5126]
[video.webm](https://github.com/harvester/harvester/assets/1897962/9246e3da-1da7-4432-bcf8-5caed2b3cced)

**Describe the bug**
It seems Harvester is not able to download ISO images from a CDN.

**To Reproduce**
1. In Harvester dashboard, go to `Images` and press `Create`
2. Use the URL `https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso`. You can get the URL [here](https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/).
3. Press `Create`
4. The UI display `Downloading` and after a while a size of 101 bytes instead of ~500 MiB.

When downloading the ISO via `wget`, the ISO is finally resolved and downloaded from `https://deac-ams.dl.sourceforge.net/project/clonezilla/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso`. When using that URL in the UI, then Harvester is capable of downloading the ISO.

**Expected behavior**
The ISO should be download, even if the entered URL redirects to somewhere else within the CDN of the provider that is hosting the ISO image.

**Support bundle**

**Environment**
 - Harvester ISO version: `master-10c281c4-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): `ipxe-examples/vagrant-pxe-harvester`

**Additional context**
n/a

**Comment by innobead** [comment]
@votdev take this as an exercise to figure out the cause or even fix it.

**Comment by votdev** [comment]
Downloading the content of the image (inspected via API browser `https://<IPADDR>/v1/harvester/harvesterhci.io.virtualmachineimages/default/image-<XXX>/download`) displays a `failed with unexpected http Status code 500` in the browser. The content should be the HTML code of the Sourceforge download page.

**Comment by votdev** [comment]
The current research shows the following.

The observed issue refers to a specific behavior of the SourceForge service. If the above specified URL for downloading the ISO file is used, it will be redirected to the page `https://xxx/download`. Now the special behavior of Sourceforge comes into play. The download only works if the `Referer`-header is removed for each redirect.

This can be achieved by using the following changes for this [code](https://github.com/longhorn/backing-image-manager/blob/b3275a8e7c12f66d6450c4430b854916623046f9/pkg/sync/handler.go#L75):

```
  client := http.Client{
    CheckRedirect: func(req *http.Request, via []*http.Request) error {
      for k, _ := range req.Header {
        delete(req.Header, k)
      }
      return nil
    },
  }
```

With this code, the download is done after 3 redirects. Without this modification, the first redirect is done and then the HTML code of `https://xxx/download` is downloaded instead of the ISO image.

The cookie handling of the `DownloadFromURL` function needs to be inspected as well.

**Comment by votdev** [comment]
To understand why `curl` is able to download the ISO image, here is a condensed output of the download:
```
> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*

< HTTP/2 301 
< location: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/
< set-cookie: VISITOR=e7cd4d94-a480-4cf6-90c2-4c97923c5b28; Max-Age=315360000; Path=/; expires=Thu, 09-Feb-2034 09:03:47 GMT; secure; HttpOnly

> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/ HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*

< HTTP/2 301 
< location: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/download
< set-cookie: VISITOR=f5da466d-de96-40fe-8a86-7b4376b54de1; Max-Age=315360000; Path=/; expires=Thu, 09-Feb-2034 09:03:48 GMT; secure; HttpOnly

> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/download HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*

< HTTP/2 302 
< location: https://downloads.sourceforge.net/project/clonezilla/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso?ts=gAAAAABlyd700SFHA3vzPtby73BPQXfgWQotboIYp2t7gctCQl46xTTTWdx0oQ-CzPw9cZb4VWIunUAm5ghF0VvWK-X5mbL_Cw%3D%3D&use_mirror=altushost-swe&r=
< set-cookie: VISITOR=e90e54f1-81d0-45b7-9282-c17406d3bc8c; Max-Age=315360000; Path=/; expires=Thu, 09-Feb-2034 09:03:48 GMT; secure; HttpOnly

> GET /project/clonezilla/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso?ts=gAAAAABlyd700SFHA3vzPtby73BPQXfgWQotboIYp2t7gctCQl46xTTTWdx0oQ-CzPw9cZb4VWIunUAm5ghF0VvWK-X5mbL_Cw%3D%3D&use_mirror=altushost-swe&r= HTTP/2
> Host: downloads.sourceforge.net
> user-agent: curl/7.81.0
> accept: */*

< HTTP/2 302 
< location: https://altushost-swe.dl.sourceforge.net/project/clonezilla/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso
< set-cookie: sf_mirror_attempt=clonezilla:altushost-swe:clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso; Max-Age=120; Path=/; expires=Mon, 12-Feb-2024 09:05:49 GMT

> GET /project/clonezilla/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso HTTP/1.1
> Host: altushost-swe.dl.sourceforge.net
> User-Agent: curl/7.81.0
> Accept: */*
```
As indicated in my previous comment, `curl` does not seem to send a `Referer` header either.

Cross-check... make curl automatically set the previous URL when it follows a `Location` header.
```
$ curl --referer ";auto" -L -v -s -o /dev/null -D - https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso

> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*

< HTTP/2 301 
< location: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/

> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/ HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*
> referer: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso

< HTTP/2 301 
< location: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/download

> GET /projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/download HTTP/2
> Host: sourceforge.net
> user-agent: curl/7.81.0
> accept: */*
> referer: https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso/

< HTTP/2 200 
```
This will download the HTML download page only, not the ISO file.

**Comment by votdev** [comment]
The bugfix will be available as soon as Longhorn is upgraded to version >= [1.6.1](https://github.com/longhorn/longhorn/issues/7987).

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an Image via URL which hosted CDN
    - eg: `https://sourceforge.net/projects/clonezilla/files/clonezilla_live_alternative/20240116-mantic/clonezilla-live-20240116-mantic-amd64.iso`
3. Image should created successfully
