### ISSUE TITLE
[FEATURE] Add Rancher to the Harvester on HCI mode

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#513]
**Is your feature request related to a problem? Please describe.**
Add Rancher to the Harvester by default on the HCI mode, allow the Harvester `admin/user` to manage and create k8s cluster directly using the harvester node driver.

**Describe the solution you'd like**
- install and configure the Rancher by default using Harvester ISO mode installation
- allow the Harvester `admin/user` to manage and create k8s cluster directly on the Rancher UI using the Harvester node driver
- configure centralized RBAC and authorization between the Rancher and Harvester

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by liorkesos** [comment]
+1

**Comment by kingsd041** [comment]
Validated on v0.2.0-rc1

Following test cases are verified:
1. Launch the harvester via iso (single node and multiple nodes), and the harvester will install Rancher Server by default.
2. You need to set a password to log in to the harvester for the first time. This user and password can also log in to Rancher Server
3. Create a user in Rancher Server, and this user can log in to the harvester UI
4. After the harvester becomes `Ready`, first log in to the Rancher Server to set a password, and then use the username/password to successfully log in to the harvester.
