### ISSUE TITLE
[Question] - Support for Rancher 2.7.10-11 in Harvester 1.2.1?

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#5135]
Rancher fixed some pretty high CVE (https://github.com/rancher/rancher/releases/tag/v2.7.10) in rancher 2.7.10.  The Suse support matrix states that Harvester supports only 2.7.6 and 2.7.9.  Is 2.7.10 supported with harvester 1.2.1?  I don't think it's reasonable to wait for months for the upgrade 1.3 to fix these vulnerabilities...  Rancher in Harvester itself is also vulnerable to 2 of those vulnerabilities...  And I don't think it's super safe to upgrade rancher without harvester, but at the same time, waiting months to fix those kind of vulnerabilities is far from ideal...

Kind Regards

**Comment by bk201** [comment]
@khushboo-rancher Does QA have a plan to test v2.7.10 + 1.2.1?

**Comment by khushboo-rancher** [comment]
Typically, we test both the stable and latest versions of Rancher active branches when releasing Harvester. We also regularly update the supported Rancher versions with Harvester releases, prioritizing based on testing needs or customer usage patterns. Our goal is to automate this process, enabling more frequent updates to Rancher supported versions, ideally within 1-2 weeks of Rancher releases.

Regarding Rancher 2.7.10 with Harvester 1.2.1, we intend to conduct testing after the release of Harvester 1.3.0, which is scheduled for the next couple of weeks or so as all QAs are busy in efforts and automation tasks related to the 1.3.0 release.

**Comment by RegisWeduLabs** [comment]
Hi there, now that 1.3.0 is released, and that there is warning in the release note ```If you are using Rancher v2.7.11 with Harvester, AVOID upgrading to Rancher v2.8.2. A known issue https://github.com/harvester/harvester/issues/5347 results in all downstream cluster nodes being replaced by Rancher (one at a time).```, is it safe to assume that 1.2.1 is compatible with Rancher 2.7.10/11 even tough the support matrix stops at 2.7.9?

**Comment by khushboo-rancher** [comment]
We can say Harvester 1.2.1 works with Rancher 2.7.10 and 2.7.11 in general as we did some testing around it during Harvester 1.3.0 release. However, Harvester 1.2.1 compatibility testing still is in progress and we would be able to update the support matrix for Harvester 1.2.1 soon.

Testing details of Harvester 1.2.1 with Rancher 2.7.10 & 2.7.11
1. Node driver compatibility - Passed
2. rke2/rke1 guest cluster provisioning (creation/modification/deletion) - Passed
3. Cloud provider and CSI Driver compatibility - Passed
4. Upgrade path - In progress

@RegisHubelia Could you please provide further information about your setup or environment to help us gain a better understanding of your use case? Like how many guest clusters, rke1 or rke2 etc..

**Comment by albinsun** [comment]
Having some basic tests based on `harvester-v1.2.1` + `rancher-v2.7.9` with upgrade path -> `v2.7.10` -> `v2.7.11` -> `v2.8.3-rc5`.
Hit an known issue #5247 (minor cuz have [workaround](https://github.com/harvester/harvester/issues/5247#issuecomment-1970596335)), in general LGTM.

cc. @khushboo-rancher

**Comment by khushboo-rancher** [comment]
Harvester officially supports Rancher 2.7.10, 2.7.11 and 2.8.2 now. Support matrix - https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-x/

**Comment by RegisWeduLabs** [comment]
Thanks!

**Comment by RegisHubelia** [comment]
One thing tough...  With the warning on your 1.3.0 release page https://github.com/harvester/harvester/releases/tag/v1.3.0 : 

![screenshot_2024-03-22-105519](https://github.com/harvester/harvester/assets/25985730/d1904dfa-af74-4322-a14d-b6700b4f89d2)

Wouldn't be better to stop the support matrix to 2.7.11 and wait for the release of 2.8.3  so users don't try to upgrade to 2.8.2 from 2.7.11?  I am unsure if the issue applies to Harvester 1.2.1, but I assume it does..?
