### ISSUE TITLE
[BUG] Automatic VM volume type (cd-rom/disk) based on image type only works for first disk

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#5142]
**Describe the bug**
When creating a new VM, on the Volumes tab, if you select an ISO Image, the image Type is automatically set to cd-rom, and the Bus to SATA:

![image](https://github.com/harvester/harvester/assets/754700/68f88684-e4e9-42d1-a7bc-a31cd4aeda9e)

If I change the image to something else (not an ISO), the Type changes to disk and the Bus to VirtIO. This automatic update only applies to the first disk. If I add a second disk and select an ISO image, the type remains disk and the bus VirtIO:

![image](https://github.com/harvester/harvester/assets/754700/907a10f0-4080-49dc-a510-3183fb18d5e1)

I'm at a loss as to understand why we'd only want this automatic disk type and bus setting to happen for the first disk. It should apply for any disk.

(Apologies for missing highlighting the bus on the screenshots)

**To Reproduce**
1. Go to Virtual Machines and click Create.
2. Go to the Volumes tab and add two VM images.
3. Observe that if you select an ISO or non-ISO image for the first disk, the type and bus update as expected.
4. Observe that this type and bus update does not happen for the second disk.

**Expected behavior**
The type should change to cd-rom and the bus to SATA for any disk with an ISO image (not just the first disk)

**Additional context**
This should fix it:

```diff
--- a/pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
+++ b/pkg/harvester/edit/kubevirt.io.virtualmachine/VirtualMachineVolume/type/vmImage.vue
@@ -141,14 +141,12 @@ export default {
     onImageChange() {
       const imageResource = this.$store.getters['harvester/all'](HCI.IMAGE)?.find( I => this.value.image === I.id);
 
-      if (this.idx === 0) {
-        if (/iso$/i.test(imageResource?.imageSuffix)) {
-          this.$set(this.value, 'type', 'cd-rom');
-          this.$set(this.value, 'bus', 'sata');
-        } else {
-          this.$set(this.value, 'type', 'disk');
-          this.$set(this.value, 'bus', 'virtio');
-        }
+      if (/iso$/i.test(imageResource?.imageSuffix)) {
+        this.$set(this.value, 'type', 'cd-rom');
+        this.$set(this.value, 'bus', 'sata');
+      } else {
+        this.$set(this.value, 'type', 'disk');
+        this.$set(this.value, 'bus', 'virtio');
       }
 
       this.update();
```

**Comment by irishgordo** [comment]
Thanks for this fix @tserong :smile: :+1: 
This looks great in ` Version: v1.4.0-dev-20240830 `
![Screenshot from 2024-09-10 14-38-52](https://github.com/user-attachments/assets/10606391-4d98-41a5-b81a-422811626124)

Opened up [6540](https://github.com/harvester/harvester/issues/6540) to track an un-expected behavior I saw w/ VM creation default disk-sizes.

So I'll go ahead and close this out :+1: :smile:
