### ISSUE TITLE
[BUG] node-manager-webhook has 3 replicas of POD in single-node cluster

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5149]
**Describe the bug**

node-manager-webhook has 3 replicas of POD in single-node cluster.

It seems such annotation is not in the replicaset definition:
```
management.cattle.io/scale-available: "3"
```

**To Reproduce**
1. Install a single-node v1.3.0 master-head cluster
2. Check pods and replicaset

```
NAMESPACE                         NAME                                                     READY   STATUS      RESTARTS      AGE

harvester-system                  harvester-node-manager-snqtr                             1/1     Running     0             25m
harvester-system                  harvester-node-manager-webhook-585c84c966-42h9s          1/1     Running     0             25m
harvester-system                  harvester-node-manager-webhook-585c84c966-9nds2          1/1     Running     0             25m
harvester-system                  harvester-node-manager-webhook-585c84c966-q7q5v          1/1     Running     0             25m

# kk get ReplicaSet -n harvester-system harvester-node-manager-webhook-585c84c966
NAME                                        DESIRED   CURRENT   READY   AGE
harvester-node-manager-webhook-585c84c966   3         3         3       28m
```

**Expected behavior**

1. Like `Harvester`, extend the replica when nodes are increasing.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM VM based

**Additional context**
Observed when validating https://github.com/harvester/harvester-installer/pull/658

---

- [x] https://github.com/harvester/charts/pull/221
- [x] Backport to release branch https://github.com/harvester/charts/pull/222
- [x] Vendor to harvester/harvester

**Comment by Vicente-Cheng** [comment]
Thanks @w13915984028 for finding that.

I thought @connorkuehl should be more familiar with node-manager-webhook, so I changed the owner to him.

Hi @connorkuehl,
Please help to confirm that. Maybe we need the following annotation as @w13915984028 mentioned
```
management.cattle.io/scale-available
```

**Comment by connorkuehl** [comment]
Fix should be available in 1.3.0-rc3, moving to Ready for Testing.

**Comment by albinsun** [comment]
Hi @connorkuehl,

We found that **node-manager-webhook** will not deploy on witness node.
Please help to check the toleration.

cc @Vicente-Cheng 

## Environment
* Harvester
  * Version: `v1.3.0-rc3`
  * Profile: QEMU/KVM, 1 and 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. Setup a single node harvester
   * <details>
     <summary> <code>node-manager-webhook</code> replica should be 1 :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/b37e63d3-7af9-4d63-9e30-9e8985c47855)
     </details>
   
1. Join one default node-1
   * <details>
     <summary> <code>node-manager-webhook</code> replica should become 2 :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/0a81f8e8-545d-452c-9d01-f21e5dec3701)
     </details>

1. Join one witness node-2
   * <details>
     <summary> Cluster is Active and node-2 is etcd :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a0935d43-a242-4d86-afc4-d3d105736bd8)
     </details>

   * <details>
     <summary> <code>node-manager-webhook</code> replica should become 3 :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/f84eb465-fd96-4967-a879-143de1ae214f)
     </details>

   * <details open>
     <summary> Each node should have 1 <code>node-manager-webhook</code> :x: ${\color{red} \text{no replica on node-2 (witness)}}$
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/5cc8ddcf-41e1-44bd-9c63-6ccc820cc39f)
     </details>


## Supportbundle
[supportbundle_64e3c3fe-26c5-4eee-9abb-ce5214e4bba6_2024-02-23T04-14-00Z.zip](https://github.com/harvester/harvester/files/14381669/supportbundle_64e3c3fe-26c5-4eee-9abb-ce5214e4bba6_2024-02-23T04-14-00Z.zip)

**Comment by starbops** [comment]
I also found that it's impossible to upgrade a single-node cluster from `master-head`. The request get rejected by the webhook because the `mcc-harvester` bundle is not in a good state, though `harvester-node-manager-webhook`'s replicas is set to 1.

![image](https://github.com/harvester/harvester/assets/1827717/9a770645-d73e-4aac-9560-efbd44bba85b)

```
$ kubectl -n harvester-system get deployments harvester-node-manager-webhook
NAME                             READY   UP-TO-DATE   AVAILABLE   AGE
harvester-node-manager-webhook   1/1     1            1           11m

$ kubectl -n fleet-local get bundles mcc-harvester
NAME            BUNDLEDEPLOYMENTS-READY   STATUS
mcc-harvester   0/1                       Modified(1) [Cluster fleet-local/local]; deployment.apps harvester-system/harvester-node-manager-webhook modified {"spec":{"replicas":3}}
```

I have to patch the `harvester` ManageChart to set `.spec.values.harvester-node-manager.webhook.replicas` to 1 to work around the issue.

[support-bundle.zip](https://github.com/harvester/harvester/files/14382811/support-bundle.zip)

**Comment by connorkuehl** [comment]
Fixes for the above two issues should be available as of 1.3 commit d60468f14c49cd5c45c9adfa3081a112c0a4af51.

Moving back to Ready for Testing.

**Comment by albinsun** [comment]
Provide test result on `v1.3-d60468f1-head`, we found that after fresh setup, node may still has more than 1 **node-manager-webhook**. Please help to check, thanks.


## Environment
* Harvester
  * Version: `v1.3-d60468f1-head`
  * Profile: QEMU/KVM, 1->2->3 nodes w/ winess (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. Setup default node-0
   * Each node should have 1 **node-manager-webhook** :heavy_check_mark:  
   * **mcc-harvester** bundle should be `Ready` :heavy_check_mark: 
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/ec5c17d6-2a6b-4625-b75e-550e52a86bd5)
   </details>

   
1. Join default node-1
   * Each node should have 1 **node-manager-webhook** & **node-manager** :x:  ${\color{red} \text{node-0 has 2 webhook}}$
   * **mcc-harvester** bundle should be `Ready` :heavy_check_mark:
   <details open>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/b054fdd9-6aab-4fc9-bd56-3a75ff666e4b)
   </details>

   

1. Join witness node-2
   * Each node should have 1 **node-manager-webhook** & **node-manager** :x: 
   * **mcc-harvester** bundle should be `Ready` :heavy_check_mark:   
   <details open>
   
   cluster
   ![image](https://github.com/harvester/harvester/assets/2773781/002087b6-b048-49bb-80c2-34a01ebd071e)
   node-manager
   ![image](https://github.com/harvester/harvester/assets/2773781/55e914db-f19f-4f5c-a24f-a7fb83fadb2b)
   </details>


## Supportbundle
[supportbundle_2e6f1f52-e3b1-4ae0-bbdf-7b65ea73c0c3_2024-03-01T04-11-59Z.zip](https://github.com/harvester/harvester/files/14456402/supportbundle_2e6f1f52-e3b1-4ae0-bbdf-7b65ea73c0c3_2024-03-01T04-11-59Z.zip)



## Note
1. Version
   * harvester-node-manager-0.2.3
   * harvester-node-manager-webhook:v0.2.1
    ```
    harvester-node-0:~ # kubectl describe deployment -n harvester-system | grep node-manager
    Name:                   harvester-node-manager-webhook
    Labels:                 app.kubernetes.io/component=node-manager
                            helm.sh/chart=harvester-node-manager-0.2.3
    Selector:               app.kubernetes.io/name=harvester-node-manager-webhook
      Labels:           app.kubernetes.io/name=harvester-node-manager-webhook
      Service Account:  harvester-node-manager-webhook
       harvester-node-manager-webhook:
        Image:      rancher/harvester-node-manager-webhook:v0.2.1
    NewReplicaSet:   harvester-node-manager-webhook-9cfccc84c (2/2 replicas created)
      Normal  ScalingReplicaSet  58m   deployment-controller  Scaled up replica set harvester-node-manager-webhook-9cfccc84c to 1
      Normal  ScalingReplicaSet  19m   deployment-controller  Scaled up replica set harvester-node-manager-webhook-9cfccc84c to 2 from 1
    ```

**Comment by connorkuehl** [comment]
@albinsun the harvester-node-manager-webhook is not a daemonset, so each node in the cluster will not necessarily have it deployed. The only issue is that the number of harvester-node-webhook pods should be scaled dynamically up to the specified default of 3 while adding nodes.

Furthermore, how long are you waiting after joining the node for the deployment to be rescheduled? I've found while testing locally it takes about 30-60s for the kube scheduler to realize that it can redistribute the pods unless I manually do `kubectl rollout restart deployment harvester-node-manager-webhook -n harvester-system`

@bk201 @Vicente-Cheng should the harvester-node-manager-webhook have a requirement for antiaffinity rules to avoid being colocated on a node?

**Comment by albinsun** [comment]
> @albinsun the harvester-node-manager-webhook is not a daemonset, so each node in the cluster will not necessarily have it deployed. The only issue is that the number of harvester-node-webhook pods should be scaled dynamically up to the specified default of 3 while adding nodes.
> 
> Furthermore, how long are you waiting after joining the node for the deployment to be rescheduled? I've found while testing locally it takes about 30-60s for the kube scheduler to realize that it can redistribute the pods unless I manually do `kubectl rollout restart deployment harvester-node-manager-webhook -n harvester-system`
> 
> @bk201 @Vicente-Cheng should the harvester-node-manager-webhook have a requirement for antiaffinity rules to avoid being colocated on a node?

@connorkuehl, test again on `v1.3-4372cbc4-head` with waiting

1. Create **node-0**, wait 300s and check pods
   ![image](https://github.com/harvester/harvester/assets/2773781/aaa361dd-179e-4d0b-a058-8365abf4ebd1)

2. Join **node-1**, wait 300s and check pods (No change)
   ![image](https://github.com/harvester/harvester/assets/2773781/38f9f5b6-401a-472c-8e17-e57bce25e6ed)

3. Manually restart (Redistributed)
   ![image](https://github.com/harvester/harvester/assets/2773781/8af6f194-d5dc-4508-a8de-4eb92eb15a05)

**Comment by bk201** [comment]
@albinsun @connorkuehl I think we can live with colocated pods.

**Comment by albinsun** [comment]
Provide test result on `v1.3-4372cbc4-head`, close as fixed.
Criteria
1. Each node should have 1 **node-manager**
2. Total **node-manager-webhook** equals cluster size (maximum 3)


## Environment
* Harvester
  * Version: `v1.3-4372cbc4-head`
  * Profile: QEMU/KVM, 3 nodes cluster w/ witness
  * ui-source: `Auto`


## Steps 
1. Setup default node-0 (Current cluster: D)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/0d2dc85a-ccd1-48b4-a105-8f74e6a945b9)
   </details>

   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should be 1 :heavy_check_mark: 

   
1. Join witness node-2 (Current cluster: DW)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/2fc1f83b-6119-4764-b598-abe61ef1a366)
   </details>

   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should be 2 :heavy_check_mark: 


1. Join default node-1 (Current cluster: DWD)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/86f14991-f4cb-4860-8a9c-378d57e9aba0)
   </details>

   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should be 3 :heavy_check_mark: 
   
    
1. Drop witness node-2 (Current cluster: DD)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/05ac5354-7664-4711-a0c5-c01b8c1afbfd)
   </details>
   
   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should be 2    :heavy_check_mark: 
   

1. Join worker node-3 (Current cluster: DDC)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/083efe01-a27c-40d8-aada-7d18d6a70ac1)
   </details>
   
   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should be 3 :heavy_check_mark: 
   
   
1. Join default node-4 (Current cluster: DDCD)
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/9be236eb-6fae-423a-83f5-041213be7141)
   </details>

   * Each node should have 1 **node-manager** :heavy_check_mark: 
   * Total **node-manager-webhook** should still 3 :heavy_check_mark:
