### ISSUE TITLE
[BUG] Harvester theme color incorrect

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#515]
**Describe the bug**
Harvester theme color incorrect

**To Reproduce**
1. The local machine is in dark theme
2. Log in harvester

**Result**
The harvester dark theme is in blue color

**Expected**
The blue color in the dark theme is not expected.
![image](https://user-images.githubusercontent.com/57614736/110428844-f1a5b600-80e4-11eb-99d3-3afc1ef06a97.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO/app-mode

**Comment by TangStone** [comment]
### validate on master-67244e23-head
1. Set Theme to Dark
![image](https://user-images.githubusercontent.com/15829074/112927856-3e126d80-9148-11eb-90de-77dd19644376.png)
2. Switch to other pages to check the theme

**Verification passed**
