### ISSUE TITLE
[FEATURE] Support for iscsi boot disks

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#5150]
**Is your feature request related to a problem? Please describe.**

Large customers running diskless systems may wish to use something like an iscsi disk as the boot device.

Most modern hardware allows definition of an iscsi target as a boot device. 

As we have tested internally when booting of an iscsi disk additional kernel arguments `rd.iscsi.firmware rd.iscsi.ibft` are needed to ensure that the OS can boot successfully.

**Describe the solution you'd like**

We should have an additional check in the installer / upgrade path to detect if the install disk is an iscsi disk, and accordingly append these additional kernel arguments in the default entry.

These arguments will need to be retained post upgrade as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by abonillabeeche** [comment]
We may need to include the support to use the OS and DATA mpio disks rather than the individual disk. This means the initramfs would need mpio support. See [here](https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-multipath.html#sec-multipath-planning)

Otherwise, we'd need to disable mpio for the [root/OS](https://documentation.suse.com/sles/15-SP5/html/SLES-all/cha-multipath.html#pr-multipath-disable-root) disk.

**Comment by innobead** [comment]
Let's add HEP for this, even though we have a KB for reference. 

cc @bk201

**Comment by ibrokethecloud** [comment]
For testing the changes:

The multipath support can be validated in a kvm setup as follows:

* Create a raw disk image of atleast 250GB
![image](https://github.com/user-attachments/assets/b60936cd-8c7f-421a-8fb7-a3a56c73777c)

* Add the same disk twice to an VM. Please ensure the following
   - The disk is marked sharable
   - A serial is provided, say disk1. The serial info needs to be same on both scsi disk additions
 
![image](https://github.com/user-attachments/assets/7008208c-7926-4b72-b8ea-d5780a219e02)
![image](https://github.com/user-attachments/assets/aaaf7767-776c-49bb-aee3-99a010a1a087)

* Boot from the iso.  Despite two paths being added to the same underlying disk, the harvester installer only shows the 1 installable disk. The serial info is important here as it is used to dedup disks with same serial info and/or wwn number
*  Proceed with installation as normal, and specify the following harvester config via a config url to enable multipathd and configure multipath.conf. The `additionalKernelArguments` are not needed for this example to work, but have been added to help validate the arguments being passed to kernel via grub post install
```
os:
  externalStorageConfig:
    enabled: true
    multiPathConfig:
    - vendor: "QEMU"
      product: "QEMU HARDDISK"
  additionalKernelArguments: "multipath=on"
```

* Post install of harvester, create a VM
* Shell into node and verify multipath is only showing pathing for the install disks, and longhorn disks are ignored
```
multipath:~ # multipath -ll
0QEMU_QEMU_HARDDISK_disk1 dm-0 QEMU,QEMU HARDDISK
size=250G features='0' hwhandler='0' wp=rw
|-+- policy='service-time 0' prio=1 status=active
| `- 0:0:0:1 sda 8:0  active ready running
`-+- policy='service-time 0' prio=1 status=enabled
  `- 0:0:0:2 sdb 8:16 active ready running
```

**Comment by noahgildersleeve** [comment]
Validated multpath with Harvester `v1.4.0-rc3`.Verified that multpath was running properly after install and boot and ran the `p0` `volumes` and `images` test cases from automation. I don't think the one failed automated test is relevant.

![Screenshot_20241022_123502](https://github.com/user-attachments/assets/17012741-d963-40b7-95ef-82b78ea46d87)
![Screenshot_20241022_140403](https://github.com/user-attachments/assets/f4154527-ba8e-49bc-b8c5-e80206b5d4f2)


I'm checking if this covers the iscsi test case as well.

I ran the test according to the quoted steps.

> For testing the changes:
> 
> The multipath support can be validated in a kvm setup as follows:
> 
> * Create a raw disk image of atleast 250GB
>   ![image](https://private-user-images.githubusercontent.com/19664014/361331008-b60936cd-8c7f-421a-8fb7-a3a56c73777c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjI5MTEsIm5iZiI6MTcyOTYyMjYxMSwicGF0aCI6Ii8xOTY2NDAxNC8zNjEzMzEwMDgtYjYwOTM2Y2QtOGM3Zi00MjFhLThmYjctYTNhNTZjNzM3NzdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE4NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3NDcxNjYwNDBjODU5OGVmODlhMTZmOTc3YjljYmIxNDJmZWI5MWI2OTBiMWQ4NjljNGJmMTY4YTIxODIxZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Wuug2AbEpDL9PKTLUkKDdIncXn4QEfux08n-B3V_o_4)
> * Add the same disk twice to an VM. Please ensure the following
>   
>   * The disk is marked sharable
>   * A serial is provided, say disk1. The serial info needs to be same on both scsi disk additions
> 
> ![image](https://private-user-images.githubusercontent.com/19664014/361331436-7008208c-7926-4b72-b8ea-d5780a219e02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjI5MTEsIm5iZiI6MTcyOTYyMjYxMSwicGF0aCI6Ii8xOTY2NDAxNC8zNjEzMzE0MzYtNzAwODIwOGMtNzkyNi00YjcyLWI4ZWEtZDU3ODBhMjE5ZTAyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE4NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2MDdiNDNkNzgzY2ZmMjZlMGUyMzc2NDVjNGRkMzM5MzFjNmEyNWM0NmRiYWYxY2Q1ZmQyNTY4MDRiY2QzNWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D9EGw916tHF8m_5dOFD81sjEJjTfNLC6dsiim-EtlL8) ![image](https://private-user-images.githubusercontent.com/19664014/361331501-aaaf7767-776c-49bb-aee3-99a010a1a087.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk2MjI5MTEsIm5iZiI6MTcyOTYyMjYxMSwicGF0aCI6Ii8xOTY2NDAxNC8zNjEzMzE1MDEtYWFhZjc3NjctNzc2Yy00OWJiLWFlZTMtOTlhMDEwYTFhMDg3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDIyVDE4NDMzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZTNkMGZhOTU4ZWRlNjk1N2RhYzQ4N2NlOTMyMzk4NjVjZDIyNmVhZjBiNTU1ZDRjMDJmOGU5NDUyODA3NWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JCdjBBb5tLxGcCahnKZY0-XFoNdgPiwqqxjyw2RJyEo)
> 
> * Boot from the iso.  Despite two paths being added to the same underlying disk, the harvester installer only shows the 1 installable disk. The serial info is important here as it is used to dedup disks with same serial info and/or wwn number
> * Proceed with installation as normal, and specify the following harvester config via a config url to enable multipathd and configure multipath.conf. The `additionalKernelArguments` are not needed for this example to work, but have been added to help validate the arguments being passed to kernel via grub post install
> 
> ```
> os:
>   externalStorageConfig:
>     enabled: true
>     multiPathConfig:
>     - vendor: "QEMU"
>       product: "QEMU HARDDISK"
>   additionalKernelArguments: "multipath=on"
> ```
> 
> * Post install of harvester, create a VM
> * Shell into node and verify multipath is only showing pathing for the install disks, and longhorn disks are ignored
> 
> ```
> multipath:~ # multipath -ll
> 0QEMU_QEMU_HARDDISK_disk1 dm-0 QEMU,QEMU HARDDISK
> size=250G features='0' hwhandler='0' wp=rw
> |-+- policy='service-time 0' prio=1 status=active
> | `- 0:0:0:1 sda 8:0  active ready running
> `-+- policy='service-time 0' prio=1 status=enabled
>   `- 0:0:0:2 sdb 8:16 active ready running
> ```

**Comment by noahgildersleeve** [comment]
I talked with @ibrokethecloud about this and the implementation of the multpath should cover the test case. It's checking for duped serial numbers and deduping them. This should affect anything that's being passed over to the host OS from the BIOS/UEFI. This includes duped serials from RAID controllers, iSCSI, and others.

 I'm going to double check this on physical hardware then close it if it works as expected.

**Comment by noahgildersleeve** [comment]
I'm closing this as fixed and will re-open it if there are any issues on bare metal.

**Comment by innobead** [comment]
Do we have a doc for this feature?

**Comment by bk201** [comment]
@ibrokethecloud we should have a doc PR before closing the issue.

**Comment by ibrokethecloud** [comment]
i will submit a docs PR with the additional config needed to leverage this

**Comment by khushboo-rancher** [comment]
Moving this to implement as this is waiting for doc PR.

**Comment by bk201** [comment]
Doc published https://docs.harvesterhci.io/v1.4/install/external-disk-support

**Comment by DrackThor** [comment]
Sorry to bother this issue, although it is already closed. There are two things that I'm still missing for this particular use-case:

- where can I find the docs for the new(?) config parameters `externalStorageConfig` and `additionalKernelArguments`? I can't find them in the 1.4 harvester configuration docs -> https://docs.harvesterhci.io/v1.4/install/harvester-configuration/
- In my usecase, I don't necessarily want to install harvester on an iSCSI disk, but later on I want to be able to use iSCSI disks for harvester VMs. I use NetApp trident (CSI) on harvester, which works fine, up until the point where I want to connect to the iSCSI target and mount the volume to the VM (pod). Since by default `multipath=off`, multipathd won't start and I'm getting this error in the harvester logs (VM pod that want's to use an iSCSI PV): 

```
 Events:
  Type     Reason                  Age                  From                     Message
  ----     ------                  ----                 ----                     -------
  Warning  FailedScheduling        3m25s                default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
  Warning  FailedScheduling        3m23s                default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
  Normal   Scheduled               3m21s                default-scheduler        Successfully assigned default/virt-launcher-test-gkj9z to harvester-2
  Normal   SuccessfulAttachVolume  3m22s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-0b6f8b0c-93d4-40df-9b0d-18206ab87938"
  Normal   SuccessfulAttachVolume  3m12s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d"
  Normal   SuccessfulMountVolume   3m11s                kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d/dev"
  Normal   SuccessfulMountVolume   3m11s                kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d" volumeMapPath "/var/lib/kubelet/pods/71d1ecd1-e432-415d-a085-4adf2a542816/volumeDevices/kubernetes.io~csi"
  Warning  FailedMapVolume         64s (x9 over 3m12s)  kubelet                  MapVolume.SetUpDevice failed for volume "pvc-0b6f8b0c-93d4-40df-9b0d-18206ab87938" : rpc error: code = Internal desc = rpc error: code = Internal desc = failed to stage volume: multipathd is not running
```

This problem contradicts with these docs/guides (an I get them), since they require multipath:
- https://docs.harvesterhci.io/v1.4/advanced/csidriver/
- https://harvesterhci.io/kb/install_netapp_trident_csi/

I did the same thing on 1.3.1 which worked fine. For config, I used something like this:
- https://github.com/dell/iac-storage-automation/blob/harvester/kubernetes/harvester/multipathd-harvester.yaml

**Comment by solox2** [comment]
> Sorry to bother this issue, although it is already closed. There are two things that I'm still missing for this particular use-case:
> 
> * where can I find the docs for the new(?) config parameters `externalStorageConfig` and `additionalKernelArguments`? I can't find them in the 1.4 harvester configuration docs -> https://docs.harvesterhci.io/v1.4/install/harvester-configuration/
> * In my usecase, I don't necessarily want to install harvester on an iSCSI disk, but later on I want to be able to use iSCSI disks for harvester VMs. I use NetApp trident (CSI) on harvester, which works fine, up until the point where I want to connect to the iSCSI target and mount the volume to the VM (pod). Since by default `multipath=off`, multipathd won't start and I'm getting this error in the harvester logs (VM pod that want's to use an iSCSI PV):
> 
> ```
>  Events:
>   Type     Reason                  Age                  From                     Message
>   ----     ------                  ----                 ----                     -------
>   Warning  FailedScheduling        3m25s                default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
>   Warning  FailedScheduling        3m23s                default-scheduler        0/3 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/3 nodes are available: 3 Preemption is not helpful for scheduling.
>   Normal   Scheduled               3m21s                default-scheduler        Successfully assigned default/virt-launcher-test-gkj9z to harvester-2
>   Normal   SuccessfulAttachVolume  3m22s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-0b6f8b0c-93d4-40df-9b0d-18206ab87938"
>   Normal   SuccessfulAttachVolume  3m12s                attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d"
>   Normal   SuccessfulMountVolume   3m11s                kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d" globalMapPath "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d/dev"
>   Normal   SuccessfulMountVolume   3m11s                kubelet                  MapVolume.MapPodDevice succeeded for volume "pvc-9bf53b8b-2e7a-4f38-ae4c-de018668937d" volumeMapPath "/var/lib/kubelet/pods/71d1ecd1-e432-415d-a085-4adf2a542816/volumeDevices/kubernetes.io~csi"
>   Warning  FailedMapVolume         64s (x9 over 3m12s)  kubelet                  MapVolume.SetUpDevice failed for volume "pvc-0b6f8b0c-93d4-40df-9b0d-18206ab87938" : rpc error: code = Internal desc = rpc error: code = Internal desc = failed to stage volume: multipathd is not running
> ```
> 
> This problem contradicts with these docs/guides (an I get them), since they require multipath:
> 
> * https://docs.harvesterhci.io/v1.4/advanced/csidriver/
> * https://harvesterhci.io/kb/install_netapp_trident_csi/
> 
> I did the same thing on 1.3.1 which worked fine. For config, I used something like this:
> 
> * https://github.com/dell/iac-storage-automation/blob/harvester/kubernetes/harvester/multipathd-harvester.yaml

I second this problem. We are using HPE CSI driver that uses iSCSI connections and the Multipath is not coming up  per the new changes related to this.  Is there any way to disable this new functionality through /oem custom files etc.  @ibrokethecloud

**Comment by ibrokethecloud** [comment]
@DrackThor the documentation is here: https://docs.harvesterhci.io/v1.4/install/external-disk-support

if i understand correctly you just want to enabled `multipathd`?

**Comment by DrackThor** [comment]
@ibrokethecloud I'm familiar with these docs, but I'm still not sure where to find the reference for the storage related options `externalStorageConfig.multiPathConfig`. Like which values I can put there, what this does in detail,..

Exactly - I want/need multipathd to use iSCSI volumes, provisioned by a CSI driver running on Harvester.. providing additional disk volumes for VMs.

**Comment by ibrokethecloud** [comment]
Is it possible to please provide the logs from the `hpe-csi-node` pod which is likely failing.

**Comment by ibrokethecloud** [comment]
the 1.4.0 build during new install or as part of the upgrade will set `mutlitpath=off` via the kernel arguments. This will stop `multipathd` service from starting up correctly.

These arguments are passed via a variable named `third_party_kernel_args` in `/oem/grubenv` file

To work around this on each node of your cluster please run the following steps.

* find current value of `third_party_kernel_args` by running as `root`
```
node2:~ # grub2-editenv /oem/grubenv list
third_party_kernel_args=multipath=off
```
* remove `multipath=off`. Please tweak this command accordingly, leaving any other `third_party_kernel_args` you need to leave the original list
```
grub2-editenv /oem/grubenv set third_party_kernel_args=""
```

reboot machine and multipathd should start successfully.

**Comment by innobead** [comment]
@ibrokethecloud should we allow users to decide enabling/disabling multipath during install/upgrade instead of disabling it by default?

**Comment by ibrokethecloud** [comment]
@innobead the better fix is to just let dracut multipath during boot when not needed. I am planning to make this the new default.

Turns out when `multipath=off` is removed from kernel arguments, in setups where host is booting of nvme disks, dracut fails to mount partitions because multipath tries to setup multipathing for nvme boot disks.

The fix is to change `third_party_kernel_args` as follows

```
grub2-editenv /oem/grubenv set "third_party_kernel_args=rd.multipath=0"
```

This will allow multipath to still be enabled by user later on while not being used during the boot phase.
