### ISSUE TITLE
[BUG] vm-dhcp-agent failed to communicate with kube-apiserver

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5153]
**Describe the bug**

This is the issue I discovered while testing the vm-dhcp-controller's limits. When creating an IPPool with a subnet contains the internal Kubernetes pod/service network (`10.5[23].0.0/16`), the agent will fail to communicate with `kube-apiserver` because the network is shadowed. For example, the following IPPool has CIDR `10.0.0.0/8`

```
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: super-net
spec:
  ipv4Config:
    serverIP: 10.0.0.1
    cidr: 10.0.0.0/8
    pool:
      start: 10.0.0.2
      end: 10.255.255.254
    leaseTime: 300
  networkName: default/super-net
```

After creating the IPPool object, check the agent's log:

```
$ kubectl -n harvester-system logs default-super-net-agent                                                               
Defaulted container "agent" out of: agent, ip-setter (init)
time="2024-02-16T11:30:56Z" level=info msg="Starting VM DHCP Agent: default-super-net-agent"
time="2024-02-16T11:30:56Z" level=info msg="monitor ippool default/super-net"
time="2024-02-16T11:30:56Z" level=info msg="(ippool.EventListener) starting IPPool event listener"
time="2024-02-16T11:30:56Z" level=info msg="(ippool.Run) starting IPPool controller"
time="2024-02-16T11:30:56Z" level=info msg="Starting HTTP server"
time="2024-02-16T11:30:56Z" level=info msg="Listening on port: 8080"
time="2024-02-16T11:30:56Z" level=info msg="(dhcp.Run) starting DHCP service on nic eth1"
W0216 11:30:59.535227       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:30:59.535326       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
W0216 11:31:03.439592       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:31:03.439703       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
W0216 11:31:09.519542       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:31:09.519759       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
W0216 11:31:17.263172       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:31:17.263236       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
W0216 11:31:27.471175       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:31:27.471234       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
W0216 11:31:53.071193       1 reflector.go:533] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
E0216 11:31:53.071221       1 reflector.go:148] pkg/mod/k8s.io/client-go@v0.27.9/tools/cache/reflector.go:231: Failed to watch *v1alpha1.IPPool: failed to list *v1alpha1.IPPool: Get "https://10.53.0.1:443/apis/network.harvesterhci.io/v1alpha1/namespaces/default/ippools?limit=500&resourceVersion=0": dial tcp 10.53.0.1:443: connect: no route to host
time="2024-02-16T11:31:59Z" level=warning msg="(dhcp.dhcpHandler) NO LEASE FOUND: hwaddr=64:4b:f0:37:d8:c3"
time="2024-02-16T11:32:00Z" level=warning msg="(dhcp.dhcpHandler) NO LEASE FOUND: hwaddr=64:4b:f0:37:d8:c3"
time="2024-02-16T11:32:03Z" level=warning msg="(dhcp.dhcpHandler) NO LEASE FOUND: hwaddr=64:4b:f0:37:d8:c3"
```

Losing the ability to connect to `kube-apiserver` means the agent will be unable to serve DHCP clients because it cannot sync with the IPPool object.

**To Reproduce**

For a more specific case, just create an `ippools.network` object like the following:

```
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  namespace: default
  name: overlap-net
spec:
  ipv4Config:
    serverIP: 10.53.0.1
    cidr: 10.53.0.0/16
    pool:
      start: 10.53.0.2
      end: 10.53.255.254
    leaseTime: 300
  networkName: default/overlap-net

```

**Expected behavior**

The agent should be able to communicate with `kube-apiserver` without problems.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1 (with vm-dhcp-controller v0.1.0)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**

There are two remedies that I can think of:

- Denied such IPPool objects (CIDR contains the pod/service network) from creating
- Add a static and strict routing rule `10.53.0.1/32` by the init container

**Comment by starbops** [comment]
Suppose an extreme scenario...

The user creates an IPPool object with CIDR `10.53.0.0/16`, precisely the same as the Kubernetes service network subnet. The vm-dhcp-webhook and controller must ensure the following:

1. Knowing what the subnet is used for the service network. For example, a Kubernetes cluster installed using `kubeadm` will have `10.96.0.0/12` as its default service network subnet; in Harvester's context, it is `--service-cluster-ip-range=10.53.0.0/16`.
2. The embedded DHCP server's IP address must not be the same as the one of the `default/kubernetes` Service, e.g., `10.53.0.1`
3. A strict static route, `10.53.0.1/32`, must be configured in the agent Pod for traffic to and from the Kubernetes API server
4. Finally, the IP address `10.53.0.1` must not be allocated to any DHCP clients (marked as reserved)

It could be done. Theoretically, the Kubernetes cluster network would not be compromised in such cases since their underlying networks are different, albeit they have the same L3 subnet info configured.

Any insight into this?
cc @w13915984028 @mingshuoqiu 
Thank you.

**Comment by w13915984028** [comment]
The first step will be exclude those subnets in both webhook and document.

To battle with k8s internal subnet will only get endless issues and troubleshootings.

**Comment by starbops** [comment]
There seems to be no good way to grab such information (service CIDR) using native Kubernetes API calls. ~I'm considering making it a configuration via a chart value, e.g. `.webhook.serviceCIDR`, but not detecting it in runtime.~

We could determine what service CIDR is by querying for the Node objects. An annotation called `rke2.io/node-args` contains the `--service-cidr` flag and its value. Kudos to @Vicente-Cheng!

**Comment by starbops** [comment]
For Harvester worker nodes, no `--service-cidr` flag is set in the nodes' `rke2.io/node-args` annotation. If the user enables the harvester-vm-dhcp-controller add-on on a 2-node cluster (or clusters of more than three nodes), the webhook fails to validate the request during IPPool object creation.

**Comment by starbops** [comment]
For vm-dhcp-controller to be vendor-agnostic, it's better to have a general solution. Its usage would be limited depending on one annotation that only applies to a specific Kubernetes distribution. Since there's still no good way to retrieve such information via native Kubernetes API, I suggest we expose a new command line option for users to configure the cluster-wide service CIDR for the webhook to consume.

**Comment by starbops** [comment]
## Test Plan

1. Install and enable the `harvester-vm-dhcp-controller` add-on
   ```yaml
   apiVersion: harvesterhci.io/v1beta1
   kind: Addon
   metadata:
     name: harvester-vm-dhcp-controller
     namespace: harvester-system
     labels:
       addon.harvesterhci.io/experimental: "true"
   spec:
     enabled: true
     repo: https://charts.harvesterhci.io
     version: 0.3.1
     chart: harvester-vm-dhcp-controller
     valuesContent: ""
   ```
2. Create a VM Network (NAD) called `test-net`
3. Create the following IPPool object with `kubectl`
   ```yaml
   apiVersion: network.harvesterhci.io/v1alpha1
   kind: IPPool
   metadata:
     namespace: default
     name: test-net
   spec:
     ipv4Config:
       cidr: 10.53.0.0/24
     networkName: default/test-net
   ```
4. The above `kubectl` create request should be rejected by the webhook.

**Comment by irishgordo** [comment]
This looks great on ` Version: v1.3-f8469881-head` w/ v0.3.1 chart version for the addon :smile: :+1: - thanks for this fix @starbops  - I'll go ahead and close this out :smile:
