### ISSUE TITLE
[BUG] - Prometheus: 100% of the rancher/rancher targets in cattle-system namespace are down - v1.2.1

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#5157]
**Describe the bug**
Since I upgraded to v1.2.1, even if rancher is working fine, and when I curl/wget /metrics directly from the cattle-system namespace pods I get a Found, when I do it from a pod outside of cattle-system, I get a Not Found - even tough other paths seems to work fine.

**To Reproduce**
1. harvester 1.2.1
2. Monitoring enabled

**Expected behavior**
/metrics should not return a not found error.

**Environment**
 - Harvester ISO version: 1.2.1

**Comment by RegisWeduLabs** [comment]
Anyone have this issue after the upgrade?

**Comment by RegisWeduLabs** [comment]
bump...  Just to be clear, the error comes from rancher monitoring.

**Comment by RegisWeduLabs** [comment]
bump

**Comment by w13915984028** [comment]
@RegisHubelia

Could you add more detailed steps about the CLI commands or UI operations, we can follow them to reproduce and check. thanks.

**Comment by RegisWeduLabs** [comment]
I'll be sending the support bundle soon, but I do this from the prometheus pod:

/prometheus $ wget http://rancher.cattle-system.svc.cluster.local/metrics --no-check-certificate
Connecting to rancher.cattle-system.svc.cluster.local (x.x.x.x:80)
Connecting to rancher.cattle-system.svc.cluster.local (x.x.x.x.:443)
wget: server returned error: HTTP/1.1 404 Not Found


If I do the same from a rancher pod or pods within harvester-system or cattle-system ns:

curl http://rancher.cattle-system.svc.cluster.local/metrics
`<a href="https://rancher.cattle-system.svc.cluster.local/metrics">Found</a>.`

Thanks

**Comment by RegisWeduLabs** [comment]
Bump

**Comment by w13915984028** [comment]
We had an analysis on https://github.com/harvester/harvester/issues/4958#issuecomment-2020169189

The `ServiceMonitor` object `rancher` is accidently added from v1.2.1 comparing to v1.2.0 and before.

Need to further check a best solution: remove this SeriviceMonitor object; or check how to export the `.../metrics` path.

```
$kubectl get servicemonitor -A
NAMESPACE                  NAME                                          AGE
..
cattle-system              rancher                                       3h
```

**Comment by w13915984028** [comment]
The workaround for Harvester v1.2.1 and later version:

https://github.com/harvester/harvester/issues/4958#issuecomment-2147691350

**Comment by w13915984028** [comment]
Duplicated with https://github.com/harvester/harvester/issues/4958, and the workaround is updated. Close issue.
