### ISSUE TITLE
[BUG] node-3 can NOT be promoted and stuck in Cordoned when shutdown and delete node-0

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5158]
## Description
In a fresh installed 4 nodes cluster, when shutdown and delete node-0 (1st node), node-3 can NOT be promoted and stuck in Cordoned.

> [!NOTE]
> Test can pass if the target node is node-1.

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 4 nodes (8C/10G/500G)

## Steps 
1. Setup 4 nodes Harvester cluster
   * All using default role (Do not specify role in yaml)
   * <details>
     <summary> Cluster is Active and with 3 management and 1 compute node. :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/14fc55fa-f1b1-4103-a648-1780021993d2)
     </details>

   * <details>
     <summary> Longhorn show 4 Scheduable nodes too :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/390c38ff-e9a0-411d-bae5-905ce9718730)
     </details>
   
1. Shutdown node-0 via shell CMD `shutdown -h now`
   * <details>
     <summary> node-0 becomes <code>Unavailable</code>, cluster still works (still 2 managements there)
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/86cf99de-4e1b-4d0e-8a39-d05862830727)
     </details>

   * <details>
     <summary> Longhorn show 4: 3 <code>Schedulable</code> and 1 <code>Down</code>
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/69073012-0005-4805-9dfd-8e83b8007411)
     </details>

1. Delete node-0 from UI
   * <details>
     <summary> node-0 gone, cluster still works (still 2 managements there)
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/17efa386-f86d-4325-8741-499487fa4be1)
     </details>

   * <details>
     <summary> node-3 should be promote to management :x: ${\color{red} \text{Stuck in Cordoned}}$
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/2657036f-3368-4b39-92ab-6b521b45917c)
     </details>

   * <details>
     <summary> Longhorn has 3 nodes: 2 <code>Schedulable</code> and 1 <code>Down</code>
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/8784b06a-9260-46f1-b895-0d3b063b4033)
     </details>

## Supportbundle
[supportbundle_drop-node0-trial3_2024-02-17T05-34-55Z.zip](https://github.com/harvester/harvester/files/14318040/supportbundle_drop-node0-trial3_2024-02-17T05-34-55Z.zip)

**Comment by Vicente-Cheng** [comment]
So far, I found the promoted pending nodes with the follow error logs on the `rancher-system-agent`
```
Feb 19 03:11:18 harvester-node-3 rancher-system-agent[7205]: time="2024-02-19T03:11:18Z" level=error msg="error loading x509 client cert/key for probe kube-apiserver (/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt//var/lib/rancher/rke2/server/tls/client-kube-apiserver.key): open /var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt: no such file or directory"
Feb 19 03:11:18 harvester-node-3 rancher-system-agent[7205]: time="2024-02-19T03:11:18Z" level=error msg="error loading CA cert for probe (kube-apiserver) /var/lib/rancher/rke2/server/tls/server-ca.crt: open /var/lib/rancher/rke2/server/tls/server-ca.crt: no such file or directory"
```
The `/var/lib/rancher/rke2/server/tls/` is empty.

I also tried to delete the `node-1` instead `node-0` then it worked.
Seems the tls could be updated successfully with the following logs
```
2024-02-20T13:54:48.233936375Z stdout F 2024/02/20 13:54:48 [INFO] Updating TLS secret for cattle-system/serving-cert
2024-02-20T13:54:48.246269045Z stdout F 2024/02/20 13:54:48 [INFO] Active TLS secret cattle-system/serving-cert
``` 

Not sure about are there some limitations of init node (means node-0) deleting?

**Comment by FrankYang0529** [comment]
Currently, the workround is deleting harvester-node-0 machine. We can check the resource name with following command:

```sh
kubectl get machine -n fleet-local | grep harvester-node-0 | awk '{ print $1 }'
```

**Comment by FrankYang0529** [comment]
The proper way to remove node is to remove machine. The CAPI controller will automatically drain the node and remove the node.

https://github.com/kubernetes-sigs/cluster-api/blob/00dbf7b9f6322d7ebd06ae2efa703b23354dd37d/internal/controllers/machine/machine_controller.go#L306-L453

However, rancher-provisioning-capi hardcodes the replica as `1`. If the CAPI pod is on the removing node, the pod may not be rescheduled and the process may fail.

https://github.com/rancher/charts/blob/754b283f0e5ac07071d1ca9be83adaecd3577ffa/charts/rancher-provisioning-capi/100.0.0%2Bup0.0.1/templates/deployment-capi-controller-manager.yaml#L10

I think a workable way is to add a node controller in harvester. If users removes a node, we remove the related machine.

cc @bk201 @ibrokethecloud @Vicente-Cheng WDYT? Thank you.

**Comment by FrankYang0529** [comment]
> I think a workable way is to add a node controller in harvester. If users removes a node, we remove the related machine.

We have another reason to add the controller. I try to remove the second node. After the final node is promoted to control-plan, the second machine is still in the cluster.

```
> kubectl get node
NAME               STATUS   ROLES                       AGE   VERSION
harvester-node-0   Ready    control-plane,etcd,master   63m   v1.27.10+rke2r1
harvester-node-2   Ready    control-plane,etcd,master   44m   v1.27.10+rke2r1
harvester-node-3   Ready    control-plane,etcd,master   33m   v1.27.10+rke2r1

>  kubectl get machine -n fleet-local
NAME                  CLUSTER   NODENAME           PROVIDERID                PHASE     AGE   VERSION
custom-2857f482960b   local     harvester-node-0   rke2://harvester-node-0   Running   58m
custom-32016a74afcd   local     harvester-node-2   rke2://harvester-node-2   Running   44m
custom-7d4e61d9bb67   local     harvester-node-1   rke2://harvester-node-1   Running   53m
custom-e4f31cf9f98d   local     harvester-node-3   rke2://harvester-node-3   Running   33m
```

**Comment by bk201** [comment]
It's also recommended by the Rancher team that deleting a node's CAPI machine is much more reliable than deleting the node resource. e.g.,

Say we want to delete `node1`, and we can find node1's machine on it's annotation:
```
apiVersion: v1
kind: Node
metadata:
  annotations:
      cluster.x-k8s.io/machine: custom-ff9b2dc968c8
```

And then delete the machine
```
kubectl delete -n fleet-local machines.cluster.x-k8s.io custom-ff9b2dc968c8
```

@torchiaf We need the behavior in the GUI (Hosts -> select a host -> Delete) to change to this behavior.

**Comment by torchiaf** [comment]
@bk201 I'm opening a new UI issue for this, thanks. https://github.com/harvester/harvester/issues/5258

**Comment by torchiaf** [comment]
Does it requires backports ? @bk201 I'm not sure if the bug happens in versions < v.1.3.

**Comment by bk201** [comment]
@torchiaf Let's the change in v1.3.0 for now, and can consider backporting to the v1.2 branch later.

**Comment by FrankYang0529** [comment]
After https://github.com/harvester/harvester/pull/5267 and https://github.com/harvester/dashboard/pull/962 are merged, we can move to ready for testing.

**Comment by bk201** [comment]
@albinsun Please be sure to follow the updated doc: https://github.com/harvester/docs/pull/507/files

Preview: https://65e54875d5105e17a75d9f1e--harvester-preview.netlify.app/v1.3/host/#deleting-a-node

**Comment by albinsun** [comment]
Provide test result using `v1.3-f6dab5e8-head` on both default cluster and cluster with witness, close as fixed.

![image](https://github.com/harvester/harvester/assets/2773781/b4d3b557-bf10-4b79-ad49-237ceab1a056)

Node deleting steps refer to https://github.com/harvester/docs/blob/96e7d4d739620f62560b632deee0cb81ddeff54c/docs/host/host.md#deleting-a-node
(https://65e54875d5105e17a75d9f1e--harvester-preview.netlify.app/v1.3/host/#deleting-a-node)




## Environment
* Harvester
  * Version: `v1.3-f6dab5e8-head`
  * Profile: QEMU/KVM, 4 nodes (8C/12G/500G)


## Steps 
1. Prerequisites
   * <details>
     <summary> Setup 4 nodes (DDWD) Harvester cluster :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/b55a4293-2d93-4c34-8da4-d9314a095e13)
     </details>

   * <details>
     <summary> Longhorn show 3 Scheduable nodes (node-0,1,3) :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/71857233-0c68-4e14-8138-595941639154)
     </details>

   * <details>
     <summary> Create VM with test data :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/71110a0e-f7dd-40f0-8741-4853c137ba08)
     </details>
   
1. Delete node-0 
   * <details>
     <summary> Check volumes are healthy :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7ac79bbf-2374-4ed7-b338-e992f632ef27)
     </details>
     
   * <details>
     <summary> Set <b>node-0</b> Scheduling to <code>Disable</code> and Evict Requested to <code>True</code> :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/bde6cafe-4230-4d8c-a3ed-62731f8f9e72)
     ![image](https://github.com/harvester/harvester/assets/2773781/519730b8-edc2-4d0b-bb7d-0708328bdf3d)
     </details>


   * <details>
     <summary> Set <b>node-0</b> <code>Maintenance</code> (Evict workloads out of the deleting node) :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/55fd2ebe-e507-4857-9e57-967d5955b08b)
     </details>

   * <details>
     <summary> Delete the node from UI and RKE2 services on the node :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/24667a8d-99a5-47d6-ad42-e7480289c04e)
     ![image](https://github.com/harvester/harvester/assets/2773781/d0d74708-2256-4555-b4d9-b3b6d50d798e)
     </details>


1. Checks
   * <details open>
     <summary> Cluster is active and <b>node-3</b> should be promoted :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/521f9d13-cba4-4edf-a91c-fb69abe60e8a)
     </details>

   * <details>
     <summary> Longhorn show 2 Scheduable nodes (node-1 and 3) :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/0be93d8e-6652-4bf4-a7ba-422b1408cbda)
     </details>

   * <details>
     <summary> VM is running and data check ok :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5c7c7933-ed3b-4ef2-97b8-206bd399dad8)
     </details>
