### ISSUE TITLE
[BUG] Configuring the network connection will cause the installation to exit if the nic state is down

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#516]
**Describe the bug**
Configuring the network connection will cause the installation to exit if the nic state is down

**To Reproduce**
1. Install harvester in installation mode
2. Assuming the host has only one nic and its state is down
3. Configure the network connection

**Result**
Configuring the network connection will cause the installation to exit if the nic state is down
![image](https://user-images.githubusercontent.com/57614736/110449396-2160b800-80fd-11eb-9ceb-f5b097c1357f.png)
![image](https://user-images.githubusercontent.com/57614736/110449762-7e5c6e00-80fd-11eb-9c64-a5bb585cba37.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO/app-mode

**Comment by TangStone** [comment]
Validated on master-3d4a5990-head
![image](https://user-images.githubusercontent.com/15829074/112250711-d74b0b00-8c94-11eb-8219-854e53150a3a.png)
@futuretea  There is an error in the prompt

**Comment by futuretea** [comment]
@TangStone Fixed

**Comment by TangStone** [comment]
Validated on master-c5a265d5-head
![image](https://user-images.githubusercontent.com/15829074/112443617-22921600-8d88-11eb-89b5-98e559fcab45.png)
