### ISSUE TITLE
[BUG] Older witness node sometimes does not has higher priority to promote

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5161]
By design, older node should has higher priority to promote.
But in this DCWW setup, we found the second Witness was promoted when joining one more Management node. 

> [!NOTE]
> * default (D)
> * management (M)
> * worker (C)
> * witness (W)

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 5 nodes (8C/10G/500G)

## Steps 
1. Setup D node-0 and C node-1
2. Join W node-2 
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/83abd860-31bb-4183-afc8-edfa0b389b78)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9660b65d-a231-418e-9b69-44290560ec23)
     </details>

   * <details>
     <summary> node-2 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/f1d35c90-0cff-415d-9e98-daecdb4240e1)
     </details>

   * <details>
     <summary> Longhorn nodes is 2 (DC) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9ee81631-d6a0-4514-9fbc-42e780e40363)
     </details>

3. Join W node-3
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/1475998c-f0e5-4c67-bd88-a4347c78c2fb)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/c8b848ce-47b0-407c-9955-c0f584b2cebf)
     </details>

   * <details>
     <summary> node-2 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/cc586bbf-e4b1-471b-a97c-5342de733acc)
     </details>

   * <details>
     <summary> node-3 (W) is <code>Witness</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5d290362-7e65-412b-a81b-5edbbe40ba9e)
     </details>

   * <details>
     <summary> Longhorn nodes is still 2 (DC) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/fcbdacae-8bb5-4526-a4ea-325884f27553)
     </details>

4. Join M node-4
   * <details>
     <summary> node-0 (D) is <code>Management</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/6b1a61f1-0c9e-46e0-8a8f-375748557da2)
     </details>

   * <details>
     <summary> node-1 (C) is <code>Compute</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/1c54fbb2-b635-458c-81da-03bbdcd665ef)
     </details>

   * <details open>
     <summary> node-2 (W) is <code>Witness (etcd)</code> :x: ${\color{red} \text{Still Witness (none), node-2 should have higher promotion priority than node-3 since join early. }}$
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0651a547-04e3-4b1b-815c-67b673fb29b9)
     </details>

   * <details open>
     <summary> node-3 (W) is <code>Witness (none)</code>  :x: ${\color{red} \text{Promote to etcd, but node-2 should have higher promotion priority than node-3. }}$ 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/ab61e3b5-b17e-4ad3-b041-6bf6f58cfb45)
     </details>

   * <details>
     <summary> node-4 (M) is <code>Management (Promoted)</code> :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/309ea3ff-35db-44da-95f4-715245208397)
     </details>

   * <details>
     <summary> Longhorn nodes is 3 (DCM) :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7ece1c2a-815f-457e-b8aa-cd68a9067f8b)
     </details>

## Reproducibility: 1/2
* Failed case
  * Cluster: DCWWM
  * [supportbundle_early_witness_not_promote_2024-02-19T03-12-13Z.zip](https://github.com/harvester/harvester/files/14325968/supportbundle_early_witness_not_promote_2024-02-19T03-12-13Z.zip)
* Successful case
  * Cluster: MCWWD
  * [supportbundle_older_witness_is_picked_2024-02-19T04-57-53Z.zip](https://github.com/harvester/harvester/files/14326583/supportbundle_older_witness_is_picked_2024-02-19T04-57-53Z.zip)
  * Snapshot
    ![image](https://github.com/harvester/harvester/assets/2773781/e52a2b6f-a122-4875-a863-bf14d842d2ee)

**Comment by Vicente-Cheng** [comment]
Hi @albinsun, 
I checked again the promote controller.
We do not guarantee the promotion order, but mostly, the older node will be promoted first.

I think that could be an enhancement instead of a bug. Thanks!
cc @bk201

**Comment by bk201** [comment]
yeah I think it's inherited from legacy code: the default node to be promoted is random.

**Comment by albinsun** [comment]
Hi @Vicente-Cheng and @bk201,

Thanks for the comment.
Close as by design first, can reopen/refer later if we need it as enhancement.
