### ISSUE TITLE
[FEATURE] support create VM template use existing VM

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#517]
**Is your feature request related to a problem? Please describe.**
allow the user to create a VM template using the existing VM

**Describe the solution you'd like**
- configurations like basic configuration, volumes, networks, and advanced options should be saved
- Do NOT save interface macAddress since it is unique of each VM pod

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by guangbochen** [comment]
@DaiYuzeng I think we should implement this via backend with a new `createTemplate` action instead do it via front-end.

**Comment by rmweir** [comment]
Cannot assign myself but going to give this issue a try.

**Comment by DoNotSayYes** [comment]
No action can be found on the front end. @DaiYuzeng Could you help confirm that anything should be done on the front end?
![image](https://user-images.githubusercontent.com/57614736/114367753-5ace8c80-9baf-11eb-9203-7c47f482e36c.png)
![image](https://user-images.githubusercontent.com/57614736/114368040-9d906480-9baf-11eb-882b-c387062b813f.png)

**Comment by DaiYuzeng** [comment]
we need to add an item of action-menu would be called `Create Template`

**Comment by DoNotSayYes** [comment]
It returns no content when generating a VM template.
![image](https://user-images.githubusercontent.com/57614736/115194335-e9975800-a11f-11eb-867e-be9d744492fa.png)

**Comment by guangbochen** [comment]
should be tracked on https://github.com/rancher/harvester/issues/702 as an enhancement.

> It returns no content when generating a VM template.
> ![image](https://user-images.githubusercontent.com/57614736/115194335-e9975800-a11f-11eb-867e-be9d744492fa.png)

**Comment by DoNotSayYes** [comment]
Validated on master-head
