### ISSUE TITLE
[BUG] Scale down 3 node with-etcd cluster to 1 causes cluster out of service

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5175]
We try to simulate an edge case that 2 nodes broken in a 3 nodes cluster via **Delete Node**
System looks fine when remaining 2 nodes but out of service when only 1 node left.

## Environment
* Harvester
  * Version: `v1.3.0-rc2`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)

## Steps 
1. Create MWM cluster
   * <details> 
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/ec67a63c-7e23-46de-8eb2-e80da45ee1be)
   </details>

   * node-0 is management :heavy_check_mark: 
   * node-1 is Witness (etcd) :heavy_check_mark: 
   * node-2 is management :heavy_check_mark: 
   
   
1. Delete node-2
   * <details> 
     <summary> Cluster is Active :heavy_check_mark: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/3737e59e-d6d1-4843-be32-79aa2e9038ae)
     </details>
   * node-0 is management :heavy_check_mark: 
   * node-1 is Witness (etcd) :heavy_check_mark: 

1. Delete node-1
   * <details open> 
       <summary> Cluster is Active :x: ${\color{red} \text{Error from server: etcdserver: request timed out}}$
       </summary>

       Delete
       ![image](https://github.com/harvester/harvester/assets/2773781/a03b7719-9a8f-409e-bb2c-93edd58ad1c9)
       Cluster our of service
       ![image](https://github.com/harvester/harvester/assets/2773781/0bcdce7e-9c69-4455-9d58-638e996387a6)
       ```
       harvester-node-0:~ # kubectl get nodes
       Error from server: etcdserver: request timed out
       ```
     </details>

## Supportbundle
1. Can not get support bundle from UI.
2. Provide /var/log tgz: [log.zip](https://github.com/harvester/harvester/files/14334386/log.zip)
1. `# tail -f /var/log/console.log`
   ```
   harvester-node-0:/var/log  
   time="2024-02-19T15:39:14Z" level=error msg="exit status 1Error from server: etcdserver: request timed out\n"
   time="2024-02-19T15:39:44Z" level=error msg="exit status 1Error from server: etcdserver: request timed out\n"
   time="2024-02-19T15:39:44Z" level=error msg="exit status 1Error from server: etcdserver: request timed out\n"
   time="2024-02-19T15:39:44Z" level=error msg="exit status 1%!(EXTRA string=)"
   ```
2. `# journalctl -u rancher-system-agent.service`
   ```
   Feb 19 15:46:49 harvester-node-0 systemd[1]: rancher-system-agent.service: Scheduled restart job, restart counter is at 175.
    Feb 19 15:46:49 harvester-node-0 systemd[1]: Stopped Rancher System Agent.
    Feb 19 15:46:49 harvester-node-0 systemd[1]: Started Rancher System Agent.
    Feb 19 15:46:49 harvester-node-0 rancher-system-agent[6975]: time="2024-02-19T15:46:49Z" level=info msg="Rancher System Agent version v0.3.4 (63eb11a) i>
    Feb 19 15:46:49 harvester-node-0 rancher-system-agent[6975]: time="2024-02-19T15:46:49Z" level=info msg="Using directory /var/lib/rancher/agent/work for>
    Feb 19 15:46:49 harvester-node-0 rancher-system-agent[6975]: time="2024-02-19T15:46:49Z" level=info msg="Starting remote watch of plans"
    Feb 19 15:46:49 harvester-node-0 rancher-system-agent[6975]: time="2024-02-19T15:46:49Z" level=fatal msg="error while connecting to Kubernetes cluster: >
    Feb 19 15:46:49 harvester-node-0 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=1/FAILURE
    Feb 19 15:46:49 harvester-node-0 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
    ```

## Note
1. Reproducibility: 3/3
1. Same test on MMM cluster can pass.
   * [supportbundle_MMM_can_scale_down_2024-02-19T16-40-14Z.zip](https://github.com/harvester/harvester/files/14334953/supportbundle_MMM_can_scale_down_2024-02-19T16-40-14Z.zip)
   * Screenshot
     ![image](https://github.com/harvester/harvester/assets/2773781/4e8365e6-942d-4cc5-8327-3b5bf9d17330)

**Comment by bk201** [comment]
~~@albinsun this is by design. A witness node is just to make the node count 3.
The maximum tolerable down node is still one.~~

Please ignore my comment, its deleting behavior not a server down. So there might be ectd member removal involved.

**Comment by bk201** [comment]
I can reproduce this. It looks when there are two node left, deleting one node immediately brings down the etcd quorum. There is no chance to remove the deleting node from the etcd member list.

**Comment by albinsun** [comment]
Provide test result on `v1.3-f6dab5e8-head`, close as fixed.


## Environment
* Harvester
  * Version: `v1.3-f6dab5e8-head`
  * Profile: QEMU/KVM, 3 nodes with witness node (8C/16G/500G)


## Steps 
1. <details> 
     <summary> Create 3 nodes cluster with witness node
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a37d8c1d-3902-49d3-9ada-5b35bf5be9ed)
   </details>

   * node-0: Management 
   * node-1: Management
   * node-2: Witness (etcd)

1. <details>
   <summary> Create VM with test data
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/225898a2-96bd-4f88-8b1a-4792c1706d4b)
   </details>
   
1. <details>
   <summary> Delete <b>node-1</b> :heavy_check_mark: 
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/45fc036d-570f-47d4-bd04-198f00edd92b)
   ![image](https://github.com/harvester/harvester/assets/2773781/266ac18c-e05b-4059-b9b7-6a0e0e4c9c9e)
   ![image](https://github.com/harvester/harvester/assets/2773781/0b32adc0-5281-481a-9c0f-8f3679e9910e)
   </details>


1. <details>
   <summary> Delete <b>node-2</b> :heavy_check_mark: 
   </summary>

   `kubectl drain harvester-node-2  --force --ignore-daemonsets --delete-local-data --pod-selector='app!=csi-attacher,app!=csi-provisioner'`
   ![image](https://github.com/harvester/harvester/assets/2773781/190c5b1d-b5cf-43f3-8c98-cbc093e56466)

   </details>

   > :warning: Not recommended/support case, only for ensuring cluster stability


1. <details>
   <summary> Cluster becomes single node and still <code>Active</code> and VM still live :heavy_check_mark: 
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/1c0f1853-25a9-47dd-89be-868e7367698b)
   ![image](https://github.com/harvester/harvester/assets/2773781/213bfb8b-2015-4773-a1cf-731ce69825b2)
   </details>

## Note
1. Node deleting steps refer to https://github.com/harvester/docs/blob/96e7d4d739620f62560b632deee0cb81ddeff54c/docs/host/host.md#deleting-a-node
(https://65e54875d5105e17a75d9f1e--harvester-preview.netlify.app/v1.3/host/#deleting-a-node)
