### ISSUE TITLE
[ENHANCEMENT] Add UI for `auto-rotate-rke2-certs` setting

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5176]
**Is your enhancement related to a problem? Please describe.**
In https://github.com/harvester/harvester/issues/3863, we add a new setting `auto-rotate-rke2-certs`. We would like to let user change the value via UI.

**Describe the solution you'd like**
Add a new setting `auto-rotate-rke2-certs` on UI. It's a JSON string with two fields `enable` and `expiringInHours`.

The `enable` is a boolean field.
The `expiringInHours` is an integer between `1` and `8759`.

**Comment by torchiaf** [comment]
@FrankYang0529 What could be the description for this setting ?

**Comment by FrankYang0529** [comment]
I think we can write:

The certificate rotation mechanism relies on Rancher. Harvester will automatically update certificates generation to trigger rotation. Please check https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/manage-clusters/rotate-certificates.

**Comment by w13915984028** [comment]
UI and backend seem to have different default value:

```
const (
	defaultReconcilAutoRotateRKE2CertsSettingDuration = time.Hour * 24 // 1 day
)
```,

UI, description: `240 H`

**Comment by bk201** [comment]
Add release-note label, a suggestion from @w13915984028 
> As the *.crt will due in 1 year, and if it also affects the normal running e.g. a node rebooting (not confirmed yet) besides the upgrading, then we need to recommend users to configure auto-rotate-rke2-certs anyway on their clusters.

**Comment by torchiaf** [comment]
> UI and backend seem to have different default value:
> 
> ```
> const (
> 	defaultReconcilAutoRotateRKE2CertsSettingDuration = time.Hour * 24 // 1 day
> )
> ```,
> 
> UI, description: `240 H`
> ```

I'll take a look, in theory the UI receives the default settings from the backend.

**Comment by FrankYang0529** [comment]
> UI and backend seem to have different default value:
> 
> ```
> const (
> 	defaultReconcilAutoRotateRKE2CertsSettingDuration = time.Hour * 24 // 1 day
> )
> ```,
> 
> UI, description: `240 H`
> ```

This is just default duration for k8s event, so we will check it every min(1 day, expire time - now).

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-1305f11-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Follow test steps in https://github.com/harvester/harvester/issues/5176#issuecomment-2102292578
