### ISSUE TITLE
[BUG] Can't RollingUpdate harevster deployment if node numbers <3

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#518]
**Describe the bug**

Can't RollingUpdate harevster deployment

**To Reproduce**
1. kubectl -n harvester-system set image deployment/harvester apiserver=newimagename
2. kubectl -n harvester-system get po

result: new replicaset keep pending

**Expected behavior**

if `app.kubernetes.io/version` is differenet
1. new replicaset ready
2. old replicaset deleted

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
Validation Version 
- master-dba9243a-head

Validation Scenarios
- 1 node and 2 nodes need to be verified separately
- 1 node needs to change the value of the tag app.kubernetes.io/version
- Use the command `kubectl -n harvester-system set image deployment/harvester apiserver=newimagename`
- View the images version in Running's pod `kubectl -n harvester-system get pod harvester-65957bc4dc-mblmt -o yaml`
- Compare the viewed image with the set image

Results
- Can RollingUpdate harevster deployment if node numbers <3
