### ISSUE TITLE
[BUG] Problem importing VMware VMs with EFI boot option.

### ISSUE THREAD

**Issue by tremilla** [harvester/harvester#5184]
When importing a VMware VM which boots with EFI, the VM in harvester does not start with EFI enabled.  It has to be enabled after the import manually from the VM's Advanced Options.   Can the EFI option be added to the vmware import yaml file?

**Comment by ibrokethecloud** [comment]
@bk201 we should may be add this to list of improvements for vm-import-controller for v1.4.0

**Comment by innobead** [comment]
Duplicated, https://github.com/harvester/harvester/issues/5758
