### ISSUE TITLE
[BUG] containerd-registry setting is no longer backwards compatible since 1.3.0-rc2

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5190]
**Describe the bug**

Harvester's github.com/rancher/wharfie dependency was recently upgraded and it turns out that module introduced a [breaking change for the wharfie.Registry struct](https://github.com/harvester/harvester/commit/6687a6be3#diff-c9ae2ac8ca36c77313e61fb5a1bffcc789d55ef58fbb52bac2220aff81f8a3bc), which is what the Harvester settings controller uses to unmarshal the JSON payload from the Harvester dashboard where the containerd-registry settings are entered into.

As a result, now a containerd-registry setting from a version of Harvester prior to 1.3.0-rc2 is not forwards-compatible.

**To Reproduce**

1. Add a non-default containerd-registry setting value

```console
harv1:~ # kubectl get setting server-version
NAME             VALUE
server-version   v1.2.1
harv1:~ # cat /etc/rancher/rke2/registries.yaml 
{"configs":{},"mirrors":{"cr.example.com":{"endpoint":["https://cr.example.com:5000"]}}}
```

2. Upgrade to Harvester >= 1.3.0-rc2.

3. Touch the containerd-registry setting (either delete the hash annotation or just add a space somewhere in the containerd-registry value string (but leave it as syntactically correct JSON)

```console
harv1:~ # cat /etc/rancher/rke2/registries.yaml 
{"configs":{},"mirrors":{"cr.example.com":{}}}
```

As you can see, using the containerd-registry value carried forward from a release of Harvester < 1.3.0-rc2 resulted in losing part of the setting.

**Expected behavior**

/etc/rancher/rke2/registries.yaml contains semantically the same information as it did prior to upgrading Harvester >= 1.3.0-rc2.

**Support bundle**

**Environment**
 - Harvester ISO version: 1.2.1 upgrade to 1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): QEMU/KVM

**Additional context**

Related issue: https://github.com/harvester/harvester/issues/5187

**Comment by connorkuehl** [comment]
Just waiting on the 1.2 backport to merge before moving to Ready for Testing.

**Comment by albinsun** [comment]
Provide test result on `v1.2-a822a3a4-head` -> `v1.3-4372cbc4-head`, close as fixed.


## Environment
* Harvester
  * Version: `v1.2-a822a3a4-head` -> `v1.3-4372cbc4-head`
  * Profile: QEMU/KVM, 2 nodes (8C/20G/500G)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> Config <code>containerd-registry</code> as ticket :heavy_check_mark: 
   </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/7ae9d6de-4da1-4102-b71c-7ed8e0c121b1)
   </details>
   
   
1. Upgrade to <code>v1.3-head</code>
   * <details>
     <summary> Upgrade successfully :heavy_check_mark: 
     </summary>
  
     ![image](https://github.com/harvester/harvester/assets/2773781/370a562d-f1ca-4a0b-b7b4-30f0a88ed4df)
     ![image](https://github.com/harvester/harvester/assets/2773781/2d64b6af-5106-47aa-b8c5-257b202474f3)
     </details>
   * <details>
     <summary> <code>containerd-registry</code> still ok :heavy_check_mark: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/5618f3cf-f992-4f3a-a682-944455fb8554)
     </details>

1. <details open>
   <summary> Touch <code>containerd-registry</code>, should ok without info loss.
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/a914ab6d-9492-4b1d-b654-cedfd5600ef7)
   </details>
