### ISSUE TITLE
[FEATURE] show action error message

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#520]
**Is your feature request related to a problem? Please describe.**
An error occurred in the action operation and no error message was displayed

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by TangStone** [comment]
### Validated on master-c5a265d5-head
**500 scenario validated**
![image](https://user-images.githubusercontent.com/15829074/112452528-ab617f80-8d91-11eb-8c3c-3f5b1aced868.png)
![image](https://user-images.githubusercontent.com/15829074/112453495-b963d000-8d92-11eb-9cc6-2126faa165a8.png)
**4xx scenario validated**
![image](https://user-images.githubusercontent.com/15829074/112453074-435f6900-8d92-11eb-8966-81a4e363fb87.png)
