### ISSUE TITLE
[ENHANCEMENT] add a field `keep mac address` to vmrestore page

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5205]
**Is your enhancement related to a problem? Please describe.**

In https://github.com/harvester/harvester/issues/3541, we add a new field `KeepMacAddress` to VMRestore field. We need a new boolean field on UI to set the value.

**Comment by lanfon72** [comment]
reopen for QA verification.

**Comment by lanfon72** [comment]
Verified the enhancement not applied yet, move back to implement.

![image](https://github.com/harvester/harvester/assets/5169694/4bf8c890-d1cb-4151-b6d2-4955f6442d0e)

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create a VM `vm1`
4. Setup **backup-target**
5. Backup `vm1` into `vm1b`
6. Restore `vm1b` via **Restore New**, there should have a checkbox `Keep Mac Address`

**Comment by albinsun** [comment]
Verified on `v1.3-4372cbc4-head`, close as fixed

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create a VM `vm1`
4. Setup **backup-target**
5. Backup `vm1` into `vm1.bak`
6. Restore `vm1.bak` via **Restore New**, there should have a checkbox `Keep Mac Address`
![image](https://github.com/harvester/harvester/assets/2773781/71e84f91-ba9b-46b5-9b28-5b4420984762)
![image](https://github.com/harvester/harvester/assets/2773781/d2c53712-a8d5-47d6-934b-4d6a60c3f53a)
