### ISSUE TITLE
[BUG] Check object tolerations for different node roles

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5207]
In `v1.3.0`, a feature is to explicitly config node role as `management`, `witness` or `worker`, which introduce complexity on object spec. especially `tolerations` which may cause potential issues.
Please help to survey they are properly set for different role.

Thank you.

Includes:
* Pod
* Job
* Plan
* ...

## Related Issues
1. #5192 
2. #5149

**Comment by Vicente-Cheng** [comment]
We introduce the various roles (management, witness, worker) in v1.3.0.

The witness role is the only one we will taint.

For the most part, we were already done when we implemented this feature.
So, this issue will focus on the witness role in the integration scenario. We will record something we are missing with the environment containing the witness node.

**Comment by Vicente-Cheng** [comment]
Add @connorkuehl because he is working on the node-manager-webhook part.

**Comment by albinsun** [comment]
As we have had a general survey on related object tolerations, just close this ticket and trace each respectively.
