### ISSUE TITLE
[BUG] harvester-node-manager-webhook does not get scheduled on witness nodes

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5210]
**Describe the bug**

The harvester-node-manager-webhook pods are not scheduled on etcd nodes, so for example if you have a control plane node and witness node, the replicaset is scaled to 2 but both webhook pods are on the same node:

```console
harv1:~ # kubectl get nodes
NAME    STATUS   ROLES                       AGE   VERSION
etcd1   Ready    <none>                      47m   v1.27.10+rke2r1
harv1   Ready    control-plane,etcd,master   18h   v1.27.10+rke2r1

harv1:~ # kubectl get pods -n harvester-system -o=custom-columns='NAME:.metadata.name,NODE:spec.nodeName' | grep node-manager-webhook
harvester-node-manager-webhook-6b8cfcbc7b-lnhhc         harv1
harvester-node-manager-webhook-6b8cfcbc7b-pk5wl         harv1
```

The harvester-node-manager daemonset will be scheduled on etcd/witness nodes, and since the webhook is required for its operation, the harvester-node-manager-webhook needs to be eligible for scheduling there as well.

**To Reproduce**
1. Leave harvester-node-manager-webhook replicas set to the default value of 3
2. Your Harvester cluster has 2 nodes, one is a regular control plane node and one is a witness/etcd node

```console
harv1:~ # kubectl get nodes
NAME    STATUS   ROLES                       AGE   VERSION
etcd1   Ready    <none>                      47m   v1.27.10+rke2r1
harv1   Ready    control-plane,etcd,master   18h   v1.27.10+rke2r1

harv1:~ # kubectl get pods -n harvester-system -o=custom-columns='NAME:.metadata.name,NODE:spec.nodeName' | grep node-manager-webhook
harvester-node-manager-webhook-6b8cfcbc7b-lnhhc         harv1
harvester-node-manager-webhook-6b8cfcbc7b-pk5wl         harv1
```

**Expected behavior**

harvester-node-manager-webhook should be scheduled on the witness node if the number of nodes in the cluster is <= the desired amount of harvester-node-manager-webhook replicas.

```console
harv1:~ # kubectl get pods -n harvester-system -o=custom-columns='NAME:.metadata.name,NODE:spec.nodeName' | grep node-manager-webhook
harvester-node-manager-webhook-6cdd49c4bd-7wtt6         harv1
harvester-node-manager-webhook-6cdd49c4bd-8fncw         etcd1
```

**Additional context**

Originally reported here: https://github.com/harvester/harvester/issues/5149#issuecomment-1960716173

---

- [x] Backport fix to release/ branch
- [x] Update vendored node-manager chart in harvester/harvester

**Comment by bk201** [comment]
@connorkuehl Just want to mention the example in the description looks like a worker node to me. If a cluster has only two nodes, the witness role node is not promoted to the witness role. But I remember even though we don't promote it yet, there are some tainits on it. cc @Vicente-Cheng

**Comment by Vicente-Cheng** [comment]
yes, the witness role will contain the `node-role.kubernetes.io/etcd=true:NoExecute` taint when installation. You can check this commit https://github.com/harvester/harvester-installer/commit/416d30bb0d815ae1af6a833ff36f925f72bffbcc

**Comment by connorkuehl** [comment]
Fix should be available as of 1.3 commit d60468f14c49cd5c45c9adfa3081a112c0a4af51.

Moving to Ready for Testing.

**Comment by albinsun** [comment]
Provide test result on `v1.3-d60468f1-head`, please help to check, thanks.
Ref. https://github.com/harvester/harvester/issues/5149#issuecomment-1972483165

**Comment by albinsun** [comment]
Provide test result on `v1.3-4372cbc4-head`, close as fixed along with https://github.com/harvester/harvester/issues/5149#issuecomment-1976436503
