### ISSUE TITLE
[BUG] Grafana link returns 404

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5217]
**Describe the bug**

In `rancher-monitoring` add-on page , the link to Grafana dashboard is wrong and reports 404.

**To Reproduce**
1. Go to Advanced -> Addons
2. Click on `rancher-monitoring` addon
3. Go to Grafana tab
4. Click of Grafana link

**Expected behavior**

The uses should be redirected to Grafana Dashboard.

**Environment**
 - Harvester UI `v1.2.1`

**Comment by lanfon72** [comment]
Verified this bug not been fixed yet, move back to implement.

For **Path 1**, changes in [the PR] is not applied.
For **Path 2**, issue #5221 reproduced.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.8.1**

### Verify Steps
**Path 1**
1. Install Harvester with any nodes
2. Navigate to `Advanced/Addons`, enable `rancher-monitoring`
3. After **Deploy Successful**, click `rancher-monitoring` to access Grafana

**Path 2**
1. Import Harvester into Rancher
2. Access Harvester dashboard via Rancher
3. Navigate to `Advanced/Addons` then click `rancher-montoring` to access Grafana

**Comment by w13915984028** [comment]
A formal validation of this issue, needs two parts of fix:

UI PR: https://github.com/harvester/dashboard/pull/958, issue: #5217
Backend PR https://github.com/harvester/harvester-installer/pull/665, issue: https://github.com/harvester/harvester/issues/5221

To now, both of them should be in v1.3.0 released daily build ISO, but not is RC3 ISO.

**Comment by lanfon72** [comment]
Verified this bug partially fixed.

https://github.com/harvester/harvester/assets/5169694/57d35720-a2e4-477e-b5e9-a2e4c81d5893


Test Information
----
* Environment: **qemu/KVM 2 node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.8.1**

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/5217#issuecomment-1975249213

**Comment by lanfon72** [comment]
@torchiaf It looks adding `/?orgId=1` ([the change](https://github.com/harvester/dashboard/pull/958/files)) might not necessary? I tested all paths are good excepts `Advanced/Addons -> rancher-monitoring -> Grafana`, and if I remove `/?orgId=1` temporarily from DOM, this path will display correctly as the same path from Rancher.

I think the bug in backend has been fixed as all paths reported in #5221 are good as I tested, but I'm not sure whether remove the added `/?orgId=1` will affect other URL visiting from Rancher, WDYT?

**Comment by w13915984028** [comment]
The `grafana`, has differences in Harvester v1.2.1 and v1.3.0. Hence the backend has 2 separate PRs for v122 and v130.

The UI code, for v121 & v122, the param `/?orgId=1` is required.  But for v130, it may not be required, I will also double check.

**Comment by torchiaf** [comment]
@lanfon72 @w13915984028 I removed the `orgId=1`: https://github.com/harvester/dashboard/pull/971 .
The [backport](https://github.com/harvester/harvester/issues/5218) is still valid since the param is required in previous Harvester versions < 1.3.0.

**Comment by irishgordo** [comment]
@torchiaf @w13915984028 @lanfon72 
Following Verify Steps:

> Verify Steps

>Path 1

    Install Harvester with any nodes
    Navigate to Advanced/Addons, enable rancher-monitoring
    After Deploy Successful, click rancher-monitoring to access Grafana

>Path 2

    Import Harvester into Rancher
    Access Harvester dashboard via Rancher
    Navigate to Advanced/Addons then click rancher-montoring to access Grafana


Path 1: PASSES

Path 2: FAILS

Testing loadout:
- Docker v2.8.1 Rancher
- Bare-Metal HP DL160  Version: v1.3-7cb8315c-head 

Moving back to implement.


https://github.com/harvester/harvester/assets/5370752/c0cbdf6b-a661-4fb6-bf3b-0a3f8898843b

**Comment by lanfon72** [comment]
I had different result of this.

https://github.com/harvester/harvester/assets/5169694/e388f8e5-51f1-45ca-bd54-8bd30399cd25


I think the root cause is, the `v1.3-7cb8315c-head` is an old ISO
![image](https://github.com/harvester/harvester/assets/5169694/89bbd62d-7424-4935-9b76-4ab974c8a47c)

The backend PR was merged in March, so we would need to use ISO newer than that.

**Comment by irishgordo** [comment]
Testing again with:
```
 Version: v1.3-2c8332b7-head 
```
And the loadout the second case now passes :smile: :+1: 
I'll go ahead and close this out:

https://github.com/harvester/harvester/assets/5370752/bab8e59e-8abd-4384-93bf-a1092f0b5291
