### ISSUE TITLE
Accessing Grafana page of the Harvester cluster via Rancher's Virtualization Management through Manage and Explore gives "Page not found 404 Error"

### ISSUE THREAD

**Issue by stalin4suse** [harvester/harvester#5221]
**Describe the bug**

Unable to access Grafana, enabled on Harvester (from Addons) via the `Manage` option available from Ranchers `Virtualization Management` page. 

![image](https://github.com/harvester/harvester/assets/92844430/374b7c79-88bd-4837-8afa-fff2205d9d6f)

**To Reproduce**
1. Import Harvester cluster to Rancher. 
2. Enable `rancher-monitoring` from `Advanced` --> `Addons`

![image](https://github.com/harvester/harvester/assets/92844430/a0467a7b-f71e-4582-9a66-20168e21f557)

3. From Rancher UI, click on the `hamburger menu` on the left top corner --> `Virtualization Management` --> click on `Manage` button of the cluster --> click on `Explore` button --> scroll to the bottom of the page until you see `Cluster Metrics` tab and you would be able to see `404 Error` page.

![image](https://github.com/harvester/harvester/assets/92844430/377b6be0-12d8-4bcd-ad27-5322fe67e2c4)
  
4. Click on `Grafana` link to view the metrics and you would get the same `404 Error` in the Grafana tab.

![image](https://github.com/harvester/harvester/assets/92844430/17fc48bf-7b0b-4470-beb2-e935105907ff) 

5. From the Grafana browser tab click on `home dashboard` url that you see on the broken page towards the right side of the graph which is broken.

![image](https://github.com/harvester/harvester/assets/92844430/037ad903-17a7-4df3-a64e-4b2aed27e3ed)

6. This will take you to the Grafanas dashboard where you can `Sign In`.

![image](https://github.com/harvester/harvester/assets/92844430/68905292-0b73-44f3-bae5-8dd62777329b)

7.) Clicking on `Sign In` would give you the following error message:
```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "services \"rancher-monitoring-grafana\" not found",
  "reason": "NotFound",
  "details": {
    "name": "rancher-monitoring-grafana",
    "kind": "services"
  },
  "code": 404
}
```

**Expected behavior**
After applying the workaround from the following [PR](https://github.com/harvester/harvester/issues/4756#issuecomment-1874242139), we should be able to access Grafana UI without any issues from within Rancher via the `Virtualization Management` --> `Manage` option. 

**Support bundle**
Harvester bundle generated and uploaded. 
[supportbundle_dbbe495e-27f6-4eb1-83c0-c56fa8b5a239_2024-02-26T16-29-27Z.zip](https://github.com/harvester/harvester/files/14407514/supportbundle_dbbe495e-27f6-4eb1-83c0-c56fa8b5a239_2024-02-26T16-29-27Z.zip)

**Environment**
 - Harvester ISO version: 1.2.1
 - Rancher 2.7.9
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Equinix

**Additional context**
None

**Comment by w13915984028** [comment]
UI related issue: https://github.com/harvester/harvester/issues/5217

**Comment by w13915984028** [comment]
FYI: the workaround link:
https://github.com/harvester/harvester/issues/4756#issuecomment-1874242139

**Comment by w13915984028** [comment]
A formal validation of this issue, needs two parts of fix:

UI PR: https://github.com/harvester/dashboard/pull/958, issue: https://github.com/harvester/harvester/issues/5217
Backend PR https://github.com/harvester/harvester-installer/pull/665, issue: https://github.com/harvester/harvester/issues/5221

To now, both of them should be in v1.3.0 released daily build ISO, but not in RC3 ISO.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.
![image](https://github.com/harvester/harvester/assets/5169694/2d060e50-a140-4696-9a07-3da42bdf4484)
![image](https://github.com/harvester/harvester/assets/5169694/c5525fc8-e07f-4a7f-89c5-3d87c9ab745a)


Test Information
----
* Environment: **qemu/KVM 2 node**
* Harvester Version: **v1.3-4372cbc4-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.8.1**

### Verify Steps
- Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/5221#issue-2154626077
