### ISSUE TITLE
[BUG] Cannot download upgrade logs due to the previous-version harvester-upgrade image missing

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5230]
**Describe the bug**

We introduced the image pruning feature for Harvester upgrades in #4995. However, in air-gapped environments, users are unable to download the upgrade logs from the dashboard after the upgrade ends successfully because the packager Pod is using the old `harvester-upgrade` container image, which no longer exists on the system.

![image](https://github.com/harvester/harvester/assets/1827717/b3508130-3f65-4247-9da7-576129c51236)

**To Reproduce**

1. Prepare a Harvester cluster with v1.2.1
2. Upgrade to v1.3.0-rc3
3. After the upgrade ends, try to download upgrade logs from the Harvester dashboard
4. The packaging Job fails to complete, and you won't get the tarball

**Expected behavior**

Upgrade logs can be downloaded successfully even after the upgrade ends.

**Support bundle**

N/A

**Environment**
 - Harvester ISO version: v1.2.1 to v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Retagging the `harvester-upgrade` image should did the trick (as a workaround).

**Comment by TachunLin** [comment]
Verifying on `master-b227ca1d-head`  (24/03/04). Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Can download upgrade logs after upgrade from `v1.2.1` to `master-head` $~~$</summary>



https://github.com/harvester/harvester/assets/29251855/ffae9876-0d6c-4b57-8de6-42511e957a08


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Can download upgrade logs after upgrade from `v1.2.1` to `v1.2-head` $~~$</summary>

https://github.com/harvester/harvester/assets/29251855/c8d8cf08-a4aa-4fb2-a144-d6f513dfb8b3



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Can download upgrade logs after upgrade from `v1.2-head` to `master-head` $~~$</summary>


https://github.com/harvester/harvester/assets/29251855/9879d236-129b-4ee8-adb3-4a27b46c4dee


https://github.com/harvester/harvester/assets/29251855/ffae9876-0d6c-4b57-8de6-42511e957a08


 </details>

### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: `master-b227ca1d-head`  (24/03/04)

### Verify Steps
<details><summary>Steps</summary>

  1. Upgrade from v1.2.1 to master-head
  2. After upgrade complete, click the Download log on dashboard
  3. Check can download the upgrade log files
  4. Upgrade from v1.2.1 to v1.2-head
  5. After upgrade complete, click the Download log on dashboard
  6. Check can download the upgrade log files
  7. Upgrade from v1.2-head to master-head
  8. After upgrade complete, click the Download log on dashboard
  9. Check can download the upgrade log files

</details>
