### ISSUE TITLE
[DOC] Document UI workflow for creating, updating, deleting CloudInit resources

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5240]
- [ ] Depends on https://github.com/harvester/harvester/issues/4711
- [ ] Depends on https://github.com/harvester/harvester/issues/4708

---

Harvester 1.3.0 will release with the backend code for managing elemental cloud-init documents via CloudInit Kubernetes objects.

**Describe the solution you'd like**

This ticket is to expand on the docs that describe kubectl-centric workflows for CloudInit resources in the Harvester documentation with their UI-based analogues.

**Comment by ibrokethecloud** [comment]
link to documentation: https://docs.harvesterhci.io/v1.3/advanced/cloudinitcrd
