### ISSUE TITLE
[BUG] Can't put a control node into maintenance if there is a witness node

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5248]
**Describe the bug**

Can't put a control node into maintenance if the witness node is presented.

**To Reproduce**
1. Create a 3-node cluster, one should be a witness node.
2. Put any non-witness node into maintenance mode and see this from the GUI:
![截圖 2024-02-29 上午9 26 08](https://github.com/harvester/harvester/assets/1691518/a8d07194-790d-4d9d-8f28-7375cdde4596)

**Expected behavior**

The node should be able to enter maintenance mode since there is one control node and witness node alive.
We need to find tune the selector here: https://github.com/harvester/harvester/blob/cd75150dbe642d12e1612509520cf1deb98241ec/pkg/util/drainhelper/helper.go#L84

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by albinsun** [comment]
# Test Plan
## Environment
* Harvester
  * Version: `v1.3-head`
  * Profile: QEMU/KVM, 3 nodes with witness
    * Default: 8C/16G/500G
    * Witness: 4C/8G/500G

## Test Suites
### Prerequisites
1. <details>
   <summary> Create a VM
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/289cf4b2-05cc-4492-a52e-6a081ddfe536)
   </details>

1. Create 3 node (MMW) cluster with witness node
   * <details> 
     <summary> Cluster is Active :question: 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/63d288b2-2090-4895-b720-49acd2bd322a)
     </details>

   * <details>
     <summary> Create a VM (node-1) :question: 
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a257493e-8d8e-472a-b9bd-4efffa62f366)
     </details>

   
1. Ensable maintenance on node-1
   * <details> 
     <summary> Cluster is Active :question: 
     </summary>

     </details>

   * <details> 
     <summary> node-0 and node-2 should NOT be able to maintenance :question: 
     </summary>

     </details>

   * <details> 
     <summary> Disable maintenance on node-1 :question: 
     </summary>

     </details>


1. Ensable maintenance on node-2
   * <details> 
     <summary> Cluster is Active :question: 
     </summary>

     </details>

   * <details> 
     <summary>  node-0 and node-1 should NOT be able to maintenance :question: 
     </summary>

     </details>

   * <details> 
     <summary> Disable maintenance on node-3 :question: 
     </summary>

     </details>


1. Ensable maintenance on node-0
   * <details> 
     <summary> Cluster is Active :question: 
     </summary>

     </details>

   * <details> 
     <summary>  node-1 and node-2 should NOT be able to maintenance :question: 
     </summary>

     </details>

   * <details> 
     <summary> Disable maintenance on node-0 :question: 
     </summary>

     </details>

**Comment by albinsun** [comment]
Provide test result on `v1.3-f6dab5e8-head`, close as fixed.

## Environment
* Harvester
  * Version: `v1.3-f6dab5e8-head`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)


## Steps 
1. <details> 
     <summary> Create 3 nodes cluster with witness node
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a37d8c1d-3902-49d3-9ada-5b35bf5be9ed)
   </details>

   * node-0: Management 
   * node-1: Management
   * node-2: Witness (etcd)
   
   
1. Maintenenace **node-1**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/5f0beed6-c3e2-4bb4-8230-45d97687edf9)
     </details>

   * <details>
     <summary> Should NOT be able to maintenance other nodes :heavy_check_mark: 
     </summary> 

     node-0
     ![image](https://github.com/harvester/harvester/assets/2773781/07a3016d-d018-462f-9e60-dd4b1d27c786)
     node-2
     ![image](https://github.com/harvester/harvester/assets/2773781/c206b0a4-5408-47dd-a94b-58dea75b7d6e)
     </details>

1. Disable maintenenace **node-1**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/c490d189-3b7c-4a38-82a3-ebbab46cda79)
     </details>


1. Maintenenace **node-2**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/81d7afc6-ddd4-498a-9214-008cdaa573b9)
     </details>

   * <details>
     <summary> Should NOT be able to maintenance other nodes :heavy_check_mark: 
     </summary> 

     node-0
     ![image](https://github.com/harvester/harvester/assets/2773781/66f430e9-a4f0-4e4d-936b-8155d22cac91)
     node-1     
     ![image](https://github.com/harvester/harvester/assets/2773781/535acf94-0d56-42c3-96b2-bc0eb4278a86)
     </details>

1. Disable maintenenace **node-2**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/edf7c25e-9427-45f3-8ae8-d349793833fd)
     </details>


1. Maintenenace **node-0**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/f77c7263-f186-4ff0-8e72-2615ac51b15f)
     </details>

   * <details>
     <summary> Should NOT be able to maintenance other nodes :heavy_check_mark: 
     </summary> 

     node-1
     ![image](https://github.com/harvester/harvester/assets/2773781/cfdd60e5-c950-4e1e-b82e-a887d5e7d2e4)
     node-2
     ![image](https://github.com/harvester/harvester/assets/2773781/9dc9b8d6-7d7d-4fd3-8b45-46846a4ce96d)
     </details>

1. Disable maintenenace **node-0**
   * <details>
     <summary> Cluster is Active :heavy_check_mark: 
     </summary> 

     ![image](https://github.com/harvester/harvester/assets/2773781/adefc1b4-9901-4f03-b884-91bbcf56734e)
     </details>
