### ISSUE TITLE
[BUG] node-n can NOT be promoted and stuck in Cordoned when shutdown and delete node-0

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5258]
**Describe the bug**

When deleting a node using the UI, it should only delete the node's machine objects.

**Additional context**

Related issue: https://github.com/harvester/harvester/issues/5158

**Comment by bk201** [comment]
@torchiaf Please **only** delete the machine objects. Rancher will eventually delete the Node object.

**Comment by albinsun** [comment]
Provide test result using `v1.3-f6dab5e8-head` on both default cluster and cluster with witness, close as fixed along with https://github.com/harvester/harvester/issues/5158#issuecomment-1978491795
