### ISSUE TITLE
[Question] Windows Defender alert on harvester-v1.2.0-patch1-amd64.iso

### ISSUE THREAD

**Issue by heckelmann** [harvester/harvester#5260]
Hi,

I've downloaded https://releases.rancher.com/harvester/v1.2.0/harvester-v1.2.0-patch1-amd64.iso from https://docs.harvesterhci.io/v1.2/install/usb-install and Windows Defender is telling me it contains `Trojan:Linux/Zapchast!MTB`

```
containerfile: C:\Users\XXXXXX\Downloads\harvester-v1.2.0-patch1-amd64.iso
file: C:\Users\XXXXXXX\Downloads\harvester-v1.2.0-patch1-amd64.iso->bundle\harvester\images\rancher-images-v2.7.5.tar.zst->(ZStandard)->e664345d1500be905a2d0fae028b7ebf0af2414c89a28392237aa3abf60de6ff/layer.tar->bin/[
```

Sorry, but the system message cuts off aber `/bin`

I scanned the file using Virustotal with no issue (https://www.virustotal.com/gui/url/b12146b77ab054d92c9c2c84fa41c96b101b383e1e1179af356e46d07f4314ec?nocache=1)

**Comment by tserong** [comment]
I'm running a scan to see if I can reproduce. Will report back when it finishes.

**Comment by tserong** [comment]
I've reproduced Windows Defender's alleged detection of `Trojan:Linux/Zapchast!MTB` in that ISO on Windows 10. The file it's picking up is in `rancher-images-v2.7.5.tar.zst`, and according to the manifest it's in one of the layers of `rancher/mirrored-prometheus-alertmanager:v0.24.0`:

```
   {
      "Config" : "e556bd45e16c2d65837d3af76a12b7aa100743ec9242861322af2f978839072c.json",
      "Layers" : [
         "e664345d1500be905a2d0fae028b7ebf0af2414c89a28392237aa3abf60de6ff/layer.tar",
         "67ea2840324e72f3a58693704bce3c6f35edfc5f736dfac7de69afa27ee3ee18/layer.tar",
         "0254a96b83a3babd678aa49178be494d29191cc18a2a4ed5816baf412a902556/layer.tar",
         "04759ff67d9283d7293dbe38c0beec4f9aa7b5c88ac0c5a508b669d8cea84de3/layer.tar",
         "0c43c0f3bb6cec81fecf729595e68275c5340ea5e29e41238e67d3adf7640af2/layer.tar",
         "c82de166d1ccc3ccf5fb7067f7c46323ca0def14e521b6d1d290fa5459e03932/layer.tar"
      ],
      "RepoTags" : [
         "rancher/mirrored-prometheus-alertmanager:v0.24.0"
      ]
   },
```

To try to figure out which file in that layer was triggering the detection, I extracted that layer, recompressed it as a zip file, and ran the scan on that. It flagged every single file under `/bin` in that image, i.e. `/bin/[`, ..., `/bin/acpid`, ..., all the way through to `/bin/zcip`. And that explains what _looks_ like a truncated error in the initial report. I'll split it up a bit to make it clearer:

```
file:
  C:\Users\XXXXXXX\Downloads\harvester-v1.2.0-patch1-amd64.iso->
    bundle\harvester\images\rancher-images-v2.7.5.tar.zst->
      (ZStandard)->
        e664345d1500be905a2d0fae028b7ebf0af2414c89a28392237aa3abf60de6ff/layer.tar->
          bin/[
```

i.e. that's complaining about the file `bin/[` inside `layer.tar`, inside `rancher-images-v2.7.5.tar.zst` inside the ISO itself.

Bearing in mind that with a busybox-based image, everything under `/bin` is the same file, Windows Defender is spitting on this version of busybox.

Just in case there was something wrong with `rancher/mirrored-prometheus-alertmanager:v0.24.0`, I pulled `prom/alertmanager:v0.24.0` and scanned that too. Sure enough, everything under `/bin` tripped the `Trojan:Linux/Zapchast!MTB` detection.

So I grabbed one of those binaries and gave it to virustotal.com. Bearing in mind the comments at https://www.virustotal.com/gui/file/dcd9a5af1c6297ed1a66c851efa305000335d8ade068ba515125a6612f1d5300/community, it is my considered opinion that this is a false positive, i.e. our ISO contains a container image which contains busybox, and busybox is also used in some malware/trojans. This does not mean that busybox in our container in our ISO is malware, or a trojan.

**Comment by tserong** [comment]
Also, my apologies, I meant to add: thank you for the report @heckelmann! Much appreciated.

**Comment by tserong** [comment]
Addendum: Windows Defender will also flag this with the v1.2.1 ISO, as it's got the same embedded images as v1.2.0-patch1. Looks like v1.3.0 won't hit it because alertmanager is slightly newer, with a slightly newer version of busybox.

**Comment by tserong** [comment]
SUSE has just published https://www.suse.com/support/kb/doc/?id=000021432 which confirms that this is a false positive.
