### ISSUE TITLE
[BUG] Click View Logs option on virtual machine dashboard can't display any log entry 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5266]
**Describe the bug**

On Harvester virtual machine dashboard page, select any virtual machine and click the `View Logs` 
The log panel can't display any log content, 

![image](https://github.com/harvester/harvester/assets/29251855/3de6e67b-9cf4-4f61-aae7-d2b5858ebcb2)
 

https://github.com/harvester/harvester/assets/29251855/6d83c920-b9c0-4e11-9d84-e0ea9ea9edb5

In comparison, check from backend and Rancher explorer page we can view vm log display well.
![image](https://github.com/harvester/harvester/assets/29251855/fb5b1c84-02cd-4952-8daf-bb2e7861cfad)

**To Reproduce**
1. Open Harvester virtual machine page 
2. Create some virtual machines
3. Check all vm in running state 
4. Click the `View Logs` in the side option menu
5. Check the log panel content of vm
6. In comparison, open the explorer page https://<vip>/dashboard/c/local/explorer/pod
7. Check the log pane content virt-manager-<vm-name>

**Expected behavior**

Should display all log entries after click the `View Logs` on any vm on the Harvester virtual machine page 

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes remote kvm machine

**Comment by bk201** [comment]
@brandboat if I press the "Download" button and see the traffic, I can get this error:

```
"a container name must be specified for pod virt-launcher-ubuntu-0-v82bc, choose one of: [compute guest-console-log]"
```

With the new version of kubevirt, there are two containers in a pod, maybe we need to specify one.

**Comment by brandboat** [comment]
> @brandboat if I press the "Download" button and see the traffic, I can get this error:
> "a container name must be specified for pod virt-launcher-ubuntu-0-v82bc, choose one of: [compute guest-console-log]"
> With the new version of kubevirt, there are two containers in a pod, maybe we need to specify one.

Thanks for your comment, @bk201 ! Comfired this was fixed in harvester/dashboard#963,

[Screencast from 2024-03-04 11-11-29.webm](https://github.com/harvester/harvester/assets/4344302/e17af555-2786-4292-866e-655e0ee12281)

**Comment by TachunLin** [comment]
Verified **fixed** on `master-30b40b90-head` (24/03/05).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Click view logs can correctly display vm logs $~~$</summary>


![image](https://github.com/harvester/harvester/assets/29251855/cdbd78ae-6b0e-42fb-9959-15a82200e1df)


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ All view logs functions works as expected $~~$</summary>


  - $\color{green}{\textsf{PASS}}$ Download Logs $~~$
  
  - $\color{green}{\textsf{PASS}}$ Clear Logs $~~$
  
  - $\color{green}{\textsf{PASS}}$ Follow Logs $~~$
  
  - $\color{green}{\textsf{PASS}}$ Use previous container $~~$
  
  - $\color{green}{\textsf{PASS}}$ Filter logs $~~$
  
  - $\color{green}{\textsf{PASS}}$ Wrap Lines $~~$
  
  - $\color{green}{\textsf{PASS}}$ Show Timestamps $~~$


 </details>

### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: `master-30b40b90-head` (24/03/05).

### Verify Steps
<details><summary> Steps </summary>

  1. Open Harvester virtual machine page
  2. Create some virtual machines
  3. Check all vm in running state
  4. Click the View Logs in the side option menu
  5. Check the log panel content of vm
  6. Test all View Logs functions

</details>

**Comment by TachunLin** [comment]
This issue also exists while testing on `v1.2-1a44ad32-head` (24/04/11). 
Thus reopen this ticket to track the behavior.

  ![image](https://github.com/harvester/harvester/assets/29251855/3247e7da-f300-40eb-80e7-749a6db65e4d)


https://github.com/harvester/harvester/assets/29251855/3527cf42-c724-4cd1-a85b-9544b874bd55


Perhaps we also need to backport the changes to v1.2 release.

**Comment by bk201** [comment]
Use the backport issue https://github.com/harvester/harvester/issues/5597 to track, thank you David.
