### ISSUE TITLE
[ENHANCEMENT] Upgrade `cluster.x-k8s.io/v1alpha4` to `cluster.x-k8s.io/v1beta1`

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5268]
**Is your enhancement related to a problem? Please describe.**
The `cluster.x-k8s.io/v1alpha4` will be removed after v1.6. Currently, we use CAPI v1.4.4. We only have 1 minor version to upgrade it.

ref: https://cluster-api.sigs.k8s.io/#-breaking-changes-

**Describe the solution you'd like**

Upgrade `cluster.x-k8s.io/v1alpha4` to `cluster.x-k8s.io/v1beta1`.

https://github.com/harvester/harvester/blob/c14caf46c92f464cfa556dee08a80175f054b274/pkg/codegen/main.go#L26

https://github.com/harvester/harvester/blob/c14caf46c92f464cfa556dee08a80175f054b274/pkg/codegen/main.go#L191-L205

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4.0-dev-20240830**
* **ui-source** Option: **Auto**

### Verify Steps
1. Same as https://github.com/harvester/harvester/pull/5377#issue-2191084890
