### ISSUE TITLE
[BUG] If no CRD, the environment should not crash

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#527]
**Describe the bug**
Request a non-existent CRD object, the whole page will crash， 
（For example, the user's UI is the latest version, but the back end is not upgraded）

**Expected behavior**
I hope the UI will not crash
![image](https://user-images.githubusercontent.com/4569037/110909455-100ceb00-834b-11eb-8c5b-404e0f0cb1db.png)

**Comment by guangbochen** [comment]
need to verify if the UI's subscribed CRDs does not exist, the user is still able to view other pages successfully, e.g
1. delete one of the CRD via `$kubectl delete crd virtualmachinebackups.harvesterhci.io` and go to the backup page, it should print the proper error message on this page.
2. go to the other page like the VM page, the user should be able to view or create a new VM without further error.

**Comment by kingsd041** [comment]
Not fixed in master-0008ce84-head version

1. kubectl delete crd keypairs.harvesterhci.io
2. Refresh the Harvester UI

![image](https://user-images.githubusercontent.com/19684717/115517162-6d387c80-a2b9-11eb-820f-c4c9d7d158f9.png)

**Comment by kingsd041** [comment]
Validate version master-64e4d950-head

After using `kubectl delete crd keypairs.harvesterhci.io`to remove CRD, i can continue to access the harvester UI
