### ISSUE TITLE
[backport v1.2] Sending ctrl-alt-delete does not have any reaction on a windows VM

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5285]
backport the issue https://github.com/harvester/harvester/issues/4535

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.2-1aa85320-head` (24/04/18). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Click ctrl+alt+delete key combination works on windows login page $~~$</summary>

* Click the ctrl+alt+delete key combination on the windows server 2022 login page works as expected



https://github.com/harvester/harvester/assets/29251855/16411e00-b0df-42fd-a37c-f74db6192f90



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Click ctrl+alt+delete key combination works inside windows  $~~$</summary>

* Click the ctrl+alt+delete key combination after login to windows server 2022 desktop works as expected


https://github.com/harvester/harvester/assets/29251855/23e696ba-edcd-443b-b3c7-9934ee0323a3


 </details>

### Test Information
* Test Environment: Single nodes harvester on local kvm machine
* Harvester version: `v1.2-1aa85320-head` (24/04/18)
* Windows ISO: windows_server_2022_en-us

### Verify Steps
<details><summary> On Windows server 2022 </summary>

  1. Create windows server 2022 iso image
  2. Create a VM, add the second `SATA` disk
  3. Install windows server 2002 with desktop 
  4. After installation complete
  5. Open the web console 
  5. In the windows login page, click the Shortcut Keys
  6. Click Ctrl , Alt, Del in sequence
  7. After login to desktop
  8.   Click Ctrl , Alt, Del in sequence again

</details>
