### ISSUE TITLE
[BUG] If you add two vGPUs the VM won't boot

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5289]
**Describe the bug**

When you add two vGPUs to a VM it won't boot

**To Reproduce**
1. Enable two vGPUs on existing VM
2. Save and restart VM or start
3. Wait for VM to start

**Expected behavior**

It should either boot or if we only support one vGPU it should 
**Support bundle**

[supportbundle_bf973e5e-935b-45fd-b911-432fb8a2a038_2024-03-05T01-35-13Z.zip](https://github.com/harvester/harvester/files/14489249/supportbundle_bf973e5e-935b-45fd-b911-432fb8a2a038_2024-03-05T01-35-13Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 nodes DL360 servers bare metal. A102

**Additional context**
Found while testing #2764 
The issue looks like it might be related to this error that I'm seeing in events. I also included a screenshot
`Server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=20, Message='unsupported configuration: Only one vgpu device can have 'ramfb' enabled')"`

![Greenshot 2024-03-04 17 44 17](https://github.com/harvester/harvester/assets/83787952/a191ce3d-ea4f-4549-98ec-5399f15704bc)
![Greenshot 2024-03-04 17 31 19](https://github.com/harvester/harvester/assets/83787952/e82bb2cf-1dee-4f63-86df-d8c59344d08b)

**Comment by ibrokethecloud** [comment]
I can confirm that a VM with multiple vGPU's can boot once the following `virtualGPUOptions` are applied to device

```
virtualGPUOptions:
  display:
     ramFB:
       enabled: false 
```

However for this to work, the vGPU profile should support multiple vGPU allocation. Based on documentation https://docs.nvidia.com/grid/16.0/grid-vgpu-release-notes-generic-linux-kvm/index.html, our GPU's only support multiple vGPU allocation if the Q-series vGPU's are used:

![image](https://github.com/harvester/harvester/assets/19664014/7e414b8d-e524-46f5-aed8-614652946e5c)


I was able to create a VM with 2 A2-4Q vgpu profiles

![image](https://github.com/harvester/harvester/assets/19664014/1e7a2151-816b-49fe-8465-d78b39a3f671)

And attach them to a VM with the additional `virtualGPUOptions` on one of the vGPU:

![image](https://github.com/harvester/harvester/assets/19664014/b1ee7676-cc64-4c5a-b6ea-9ce856a566bd)


Post this change VM is able to boot successfully and devices are visible to guest

![image](https://github.com/harvester/harvester/assets/19664014/2cfe7f96-e6f1-49f6-abb2-14e160f776f7)

**Comment by noahgildersleeve** [comment]
I validated the workaround with version `master-a2c98e96-head`.

**Comment by bk201** [comment]
The doc PR cover this: https://github.com/harvester/docs/pull/526

**Comment by bk201** [comment]
Doc published: https://docs.harvesterhci.io/v1.3/advanced/vgpusupport#attaching-multiple-vgpus
