### ISSUE TITLE
Is it possible to create custom rancher RBAC roles for Harvester operations?

### ISSUE THREAD

**Issue by jcambronero** [harvester/harvester#5290]
For example, if we want to create a role that prevents users from taking snapshots or creating images. 
Is this possible?

Thanks.

**Comment by bk201** [comment]
@jcambronero Are you using purely Harvester or importing Harvester to Rancher?

**Comment by jcambronero** [comment]
@bk201 I'm importing Harvester to Rancher.

**Comment by ibrokethecloud** [comment]
yes you could create custom roles in rancher, and assign these roles to the downstream harvester cluster if needed at project scope or cluster scope.
