### ISSUE TITLE
[BUG] You can disable vGPUs when they are in use

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5293]
**Describe the bug**

You can disable vGPUs that are assigned to existing VMs. You can even remove them so that running VMs stop working 
**To Reproduce**
1. Enable vGPU profile for card
2. Add vGPU to VM
3. Verify that vGPU is working
4. disable vGPU profile
5. 
**Expected behavior**

You should get an error while trying to disable a vGPU profile that is in use.
**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node DL360 bare metal servers

**Additional context**
Found while testing #2764 
I found this while testing with 4 of the same vGPU profile and adding three of them to VMs then removing three of them. It seemed like this probably sent it into a weird fail state and I started getting 500 errors on disabling vGPUs and I couldn't assign the one that still existed.
![Greenshot 2024-03-04 18 32 00](https://github.com/harvester/harvester/assets/83787952/8ab8d7f8-bd8d-400d-91a6-81c9700b6d9b)
![Greenshot 2024-03-04 18 18 34](https://github.com/harvester/harvester/assets/83787952/61bdcc46-0650-459d-97e8-86c4ed6fec77)
![Greenshot 2024-03-04 18 11 19](https://github.com/harvester/harvester/assets/83787952/4b603a88-7dcf-4441-8f71-21ccfe3185ef)

**Comment by ibrokethecloud** [comment]
I suspect this is a UI bug:

The UI shows the device has been disabled while the pcidevices webhook has clearly rejected the request.

Refreshing the page, shows the vGPU device is still enabled. This is likely what is causing the weird state experienced where user is trying to enable an already enabled device.

```harvester-pcidevices-controller-jzk8t agent time="2024-03-05T05:11:22Z" level=debug msg="Request (user: user-tv78p, devices.harvesterhci.io/v1beta1, Kind=VGPUDevice, namespace: , name: harvester-kgd9c-000008004, operation: UPDATE) operation is rejected: device harvester-kgd9c-000008004 is in use with VM opensuse in namespace default"
harvester-pcidevices-controller-jzk8t agent time="2024-03-05T05:11:23Z" level=debug msg="admit result: UPDATE devices.harvesterhci.io/v1beta1, Kind=VGPUDevice harvester-kgd9c-000008004 user=user-tv78p allowed=false err=<nil>"
```

**Comment by ibrokethecloud** [comment]
@torchiaf any chance you could please take a look at this?

**Comment by torchiaf** [comment]
@ibrokethecloud I'm working on it.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.4.0-rc2`. Verified as fixed. 

## Test Steps

1. Create a new downstream RKE2 cluster with vGPUs
2. Wait for them to provision
3. Try to disable vGPUs in Harvester UI
![Greenshot 2024-10-10 14 57 01](https://github.com/user-attachments/assets/05c382a4-9c81-4dff-8297-85030d6e0831)
