### ISSUE TITLE
[ENHANCEMENT] Adding `dig` to Harvester

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5305]
**Is your enhancement related to a problem? Please describe.**
It's very difficult to troubleshoot nameserver issues when `dig` isn't present.
Dig is a great too for dns lookups / troubleshooting dns problems.
It's author I believe is still the "Internet Systems Consortium".
https://www.isc.org/tags/dig/
https://www.isc.org/download/

**Describe the solution you'd like**
To be able to run `dig` from any Harvester node in the cluster.
```
dig +short @Name-Server-IPV4-We-Are-Troubleshooting blahblah.name.localdomain
```

**Describe alternatives you've considered**
We can't easily side load this in.

**Additional context**
This would just be such a joy to have, as it's substantially difficult right now in Harvester to troubleshoot DNS problems...like near impossible it feels at times.  This would be substantially helpful to validate air-gapped nameservers w/ hosts we're trying to access.

**Comment by irishgordo** [comment]
Additionally, the extra packages that come bundled with bind-utils would be excellent.

https://software.opensuse.org/package/bind-utils

**Comment by tserong** [comment]
This should do it, applied to https://build.opensuse.org/package/show/isv:Rancher:Harvester:OS:Dev/baseos (and v1.3, and v1.2, ...)

```diff
--- Dockerfile  (revision 15)
+++ Dockerfile  (working copy)
@@ -40,7 +40,8 @@
     sensors \
     yq \
     nvme-cli \
-    kubevirt-virtctl
+    kubevirt-virtctl \
+    bind-utils
     
 # Only install in x86_64 builds
 #!ArchExclusiveLine: x86_64
```

**Comment by tserong** [comment]
I've applied the above change to baseos (and baseos-headers) in:

- https://build.opensuse.org/project/show/isv:Rancher:Harvester:OS:Dev
- https://build.opensuse.org/project/show/isv:Rancher:Harvester:OS:v1.3
- https://build.opensuse.org/project/show/isv:Rancher:Harvester:OS:v1.2

AIUI this should be picked up automatically for builds of the harvester master branch, which uses rancher/harvester-os:sle-micro-head.

For the v1.3 and v1.2 series, we'll need to tag new releases of harvester/os2 to pick up the above changes, and then open PRs against harvester-installer to bump to the new release.

**Comment by tserong** [comment]
v1.2 PR: https://github.com/harvester/harvester-installer/pull/728
v1.3 PR: https://github.com/harvester/harvester-installer/pull/731

**Comment by irishgordo** [comment]
@tserong thanks for this addition :smile: :+1: 
This looks great in Harvester Version: v1.4.0-dev-20240705 

I'll go ahead and close this out:
```
testnode8:/home/rancher # rpm -qa bind-utils
warning: Found NDB Packages.db database while attempting bdb backend: using ndb backend.
bind-utils-9.16.48-150500.8.16.1.x86_64
testnode8:/home/rancher # dig version

; <<>> DiG 9.16.48 <<>> version
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NXDOMAIN, id: 63488
;; flags: qr rd ra ad; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;version.			IN	A

;; AUTHORITY SECTION:
.			86400	IN	SOA	a.root-servers.net. nstld.verisign-grs.com. 2024070803 1800 900 604800 86400

;; Query time: 24 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: Tue Jul 09 03:34:47 UTC 2024
;; MSG SIZE  rcvd: 111

testnode8:/home/rancher # cat /etc/os-release 
NAME="SLE Micro"
VERSION="5.5"
VERSION_ID="5.5"
PRETTY_NAME="Harvester v1.4.0-dev-20240705"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.5"
IMAGE_REPO="registry.suse.com/suse/sle-micro/base-5.5"
IMAGE_TAG="2.0.4-5.8.34"
IMAGE="registry.suse.com/suse/sle-micro/base-5.5:2.0.4-5.8.34"
TIMESTAMP=20240703104612
GRUB_ENTRY_NAME="SLE Micro"
VARIANT="Harvester"
VARIANT_ID="Harvester-v1.4-20240705"
GRUB_ENTRY_NAME="Harvester v1.4.0-dev-20240705"

```
