### ISSUE TITLE
[BUG] replicas of running VMs aren't moved from evicted extra disk

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5307]
**Describe the bug**

When VMs are running with replicas, the replicas should be moved from evicted extra disk. 

But, currently it shows `failed to update device mount 50451df09c455d707e5b7685a9895afa: failed to execute: nsenter [--mount=/host/proc/3430/ns/mnt --net=/host/proc/3430/ns/net umount /var/lib/harvester/extra-disks/50451df09c455d707e5b7685a9895afa], output , stderr umount: /var/lib/harvester/extra-disks/50451df09c455d707e5b7685a9895afa: target is busy. : exit status 32`

**To Reproduce**
1. Create extra disk.
2. Attach extra disk to node-0 on the node page of harvester dashboard.
3. Create a lot of volumes until new volume is scheduled on the extra disk. Then delete other volumes which are on the root disk.
    ![image](https://github.com/harvester/harvester/assets/6960289/adfe5812-bcf1-4c28-b44c-094741f7eb2b)
4. Create one VM to node-0, and attach previous volume to this VM.
5. Wait for VM become `running`.
6. Remove this extra disk from node-0 on the node page of harvester dashboard.
7. Update will be successful, but it will show error message when you reload the page. And this extra disk is not removed.

![image](https://github.com/harvester/harvester/assets/6960289/a2eb74fc-4b04-4a0f-bf69-96c42e6bd6d9)

**Expected behavior**

This extra disk should be removed from node-0, and the replicas should be moved to root disk.

**Support bundle**
[supportbundle_1012541a-a5cb-420c-a9f4-49bc87c725cb_2024-03-07T02-57-36Z.zip](https://github.com/harvester/harvester/files/14518140/supportbundle_1012541a-a5cb-420c-a9f4-49bc87c725cb_2024-03-07T02-57-36Z.zip)

**Environment**
 - Harvester ISO version: 1.3.0-rc4 with 3 node cluster
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM

**Additional context**
None

**Comment by bk201** [comment]
Related: https://github.com/harvester/harvester/issues/3344
It's recommended to evict a disk before removing it.

**Comment by Vicente-Cheng** [comment]
Add some context here as to why the unmount failed.

Assume the related folder is /var/lib/harvester/extra-disks/d4ad0f88af675aff222c23463b5a20b7
We found the process which uses it
```
harvester-node-2:~ # lsof +D /var/lib/harvester/extra-disks/d4ad0f88af675aff222c23463b5a20b7 -P
COMMAND   PID USER   FD   TYPE DEVICE   SIZE/OFF   NODE NAME
longhorn 9576 root   11u   REG    8,0       4096 393220 /var/lib/harvester/extra-disks/d4ad0f88af675aff222c23463b5a20b7/replicas/pvc-b20cf239-1ce2-440e-96f4-20c9c80e4446-aef96919/revision.counter
longhorn 9576 root   12u   REG    8,0 5368709120 393221 /var/lib/harvester/extra-disks/d4ad0f88af675aff222c23463b5a20b7/replicas/pvc-b20cf239-1ce2-440e-96f4-20c9c80e4446-aef96919/volume-head-000.img
longhorn 9586 root  cwd    DIR    8,0       4096 393218 /var/lib/harvester/extra-disks/d4ad0f88af675aff222c23463b5a20b7/replicas/pvc-b20cf239-1ce2-440e-96f4-20c9c80e4446-aef96919
```

Then check the process 9576
```
 9576  9586 10632 10620 ?           -1 Sl       0   0:01          |   \_ /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.6.0/longhorn --volume-name pvc-b20cf239-1ce2-440e-96f4-20c9c80e4446 sync-agent --listen 0.0.0.0:10013 --replica 0.0.0.0:10011 --listen-port-range 10014-10020 --replica-instance-name pvc-b20cf239-1ce2-440e-96f4-20c9c80e4446-r-a0851d18
```

So that is why the unmount failed.

Back to the related issue @bk201 mentioned, we should improve our current document.
Doc link here: https://docs.harvesterhci.io/v1.3/host/#remove-disks

**Comment by Yu-Jack** [comment]
Revise original test case description https://github.com/harvester/tests/pull/1149

**Comment by Yu-Jack** [comment]
close this one because it's not an issue, just need to add more detail in test case.
