### ISSUE TITLE
[ENHANCEMENT] disable disk on the Harvester UI

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5309]
**Is your enhancement related to a problem? Please describe.**
Add disable operation for the disk management.
That would be helpful to ensure the replica is not scheduled to this disk.

**Describe the solution you'd like**
Add the scheduled flag to blockdevice CRD; then the controller will do the related things.

**Describe alternatives you've considered**
None

**Additional context**
We can only do this operation on the Longhorn UI currently.

**Comment by a110605** [comment]
Per discuss with @Vicente-Cheng , no backend change needed for this ticket. 
UI PR and backport PRs to v1.4 and v1.3 are all merged.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.4.0-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/5836#issuecomment-2345159953
