### ISSUE TITLE
[ENHANCEMENT] Bump go to v1.21

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5310]
**Is your enhancement related to a problem? Please describe.**
Go v1.20 is EOL on 06 Feb 2024.

Ref: https://endoflife.date/go

**Describe the solution you'd like**
We should update all repositories to v1.21.

**Comment by votdev** [comment]
The project that are involved are:

- https://github.com/harvester/harvester/
- https://github.com/harvester/harvester-installer/
- https://github.com/harvester/node-manager/
- https://github.com/harvester/network-controller-harvester/
- https://github.com/harvester/cloud-provider-harvester/
- https://github.com/harvester/node-disk-manager/
- https://github.com/harvester/vm-import-controller/
- https://github.com/harvester/pcidevices/
- https://github.com/harvester/load-balancer-harvester/
- https://github.com/harvester/terraform-provider-harvester/
- https://github.com/harvester/terraformer/
- https://github.com/harvester/go-common/
- https://github.com/harvester/eventrouter/
- https://github.com/harvester/docker-machine-driver-harvester/
- https://github.com/harvester/harvester-csi-driver/

**Comment by votdev** [comment]
Close as all sub-projects have been merged.
