### ISSUE TITLE
[BUG] The image list packing part of the build script should be architecture-aware

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#5313]
**Describe the bug**

We will soon publish ARM64 artifacts for the v1.3.0 release. The build pipeline includes an image list packing stage, which packs the image lists for the current and previous versions ([ref](https://github.com/harvester/harvester-installer/blob/4adc9fea30a6e6f612b3e75fdd8f6eb37cb50c3d/scripts/package-harvester-os#L46)). It isn't arch-aware yet, so the results (the packed image lists) will be the same for both AMD64 and ARM64 built artifacts.

The packed image lists inside the built ISO will be referenced in the final stage of Harvester upgrades to purge unneeded container images. If the image lists contain wrong image names, the container images cannot be removed.

In addition, future releases will publish the image lists with `ARCH` as the name suffix. We need to adapt this to prevent build failure.

**To Reproduce**

1. Build the v1.3.0-rc4 ISO image
2. Examine the built image, check the packed image list

**Expected behavior**

Fetch the correct image list according to the target architecture and pack them into the ISO image.

**Support bundle**

N/A

**Environment**
 - Harvester ISO version: v1.3.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): not relevant

**Additional context**

N/A

**Comment by lanfon72** [comment]
milestone/release required.

**Comment by brandboat** [comment]
thanks @lanfon72 , milestone added,  this one should be included in v1.4.0 and backport to v1.3 (it was merged, and I thought is in v1.3.1 release... https://github.com/harvester/harvester-installer/pull/691)

**Comment by albinsun** [comment]
Test PASS, both AMD64 and ARM64 arch has _image_list_all.txt_ for `v1.3.0`, `v1.3.1` and `v1.3.2`, close as fixed.

## Environment
* Harvester Image
  * harvester-v1.4.0-rc2-**amd64**.iso
  * harvester-v1.4.0-rc2-**arm64**.iso

## Test Steps
1. <details open>
   <summary> Mount Harvester AMD64 and ARM64 ISOs
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a9151ce2-9d94-4478-81be-f1796f4949a6)
   </details>

1. <details open>
   <summary> Check AMD64 v1.3.0, v1.3.1 and v1.3.2 <i>image_list_all.txt</i> exists
   </summary>
   
   ![image](https://github.com/user-attachments/assets/fa52c284-e16c-4338-a656-c67e1dea6311)
   </details>

1. <details open>
   <summary> Check ARM v1.3.0, v1.3.1 and v1.3.2 <i>image_list_all.txt</i> exists
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b6463076-4b41-4723-8fce-3bd35edebe7e)
   </details>



[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
