### ISSUE TITLE
[BUG] Harvester LB is not correctly syncing with VMI

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5316]
**Describe the bug**

**To Reproduce**
1. create vm vm1, start vm
1. Create ippoo and lb lb1, lb1 select vm1, wait all ok
1. Stop vm1
![image](https://github.com/harvester/harvester/assets/31133476/26efc0c4-a2f5-4306-b9d0-174d1f11f859)
1. The lb1 is still active
![image](https://github.com/harvester/harvester/assets/31133476/c0beac15-538a-4eb2-83a7-dab9ef6eebbb)
1. The lb1 has the backend server address, but vm1 is indeed gone.
```
$kubectl get lb lb1 -oyaml
apiVersion: loadbalancer.harvesterhci.io/v1beta1
kind: LoadBalancer
metadata:
  annotations:
    loadbalancer.harvesterhci.io/namespace: default
    loadbalancer.harvesterhci.io/network: ""
    loadbalancer.harvesterhci.io/project: c-m-f4kgwhds/p-fsmsq
  creationTimestamp: "2024-03-07T12:54:47Z"
  finalizers:
  - wrangler.cattle.io/harvester-lb-controller
  generation: 4
  name: lb1
  namespace: default
  resourceVersion: "1305316"
  uid: 8e739158-56c5-4ca4-b0d9-994ed8033a0c
spec:
  backendServerSelector:
    harvesterhci.io/vmName:
    - vm1
  healthCheck: {}
  ipPool: pool1
  ipam: pool
  listeners:
  - backendPort: 80
    name: listener1
    port: 8088
    protocol: TCP
  workloadType: vm
status:
  address: 192.168.122.230
  allocatedAddress:
    gateway: 192.168.122.1
    ip: 192.168.122.230
    ipPool: pool1
    mask: 255.255.255.0
  backendServers:
  - 10.52.0.200
  conditions:
  - lastUpdateTime: "2024-03-07T12:54:48Z"
    status: "True"
    type: Ready
```

**Expected behavior**

vm status is correctly synced to lb.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.2.1; harvester-load-balancer:v0.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Observed when debugging: #5033 

Note: 
Harvester v1.2.1 and v1.3.0, with different kubevirt version, the error messages are diffrent. note: #5137

**Comment by w13915984028** [comment]
After open debug, we get:
> time="2024-03-07T13:21:22Z" level=error msg="error syncing 'default/lb1': handler harvester-lb-controller: update lb default/lb1 status failed, error: admission webhook \"validator.harvester-system.harvester-load-balancer-webhook\" denied the request: Internal error occurred: update loadbalancer default/lb1 failed: no virtual machine instance matched, requeuing"

**Comment by w13915984028** [comment]
With current enhancement,

the LB can be a place-holder, if no backend servers are detected, it will move to "Not Ready" status.

![image](https://github.com/harvester/harvester/assets/31133476/8b10884a-9cc5-4b2f-b543-c70792f8672b)

**Comment by w13915984028** [comment]
Test plan (Harvester ISO should be built after 2024.08.30):

Create one LB which has a selector, but the target VM is never created, or VM is ever there but stopped/removed, the LB can detect those correctly:

When IP pool has no free IPs/DHCP fail to allocate IP for this LB, LB is `Not Ready`
When no backend server, LB is `Not Ready`
When all backend servers are down, LB is `Not Ready`
When none of the backed servers is health checked as active, LB is `Not Ready`

When an active backend server is up, LB changes to `Ready`.

Refer: https://github.com/harvester/load-balancer-harvester/pull/31#issue-2387926834

**Comment by rrajendran17** [comment]
Verified on v1.4-00cd4ee-head and works as expected

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHIzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ac65daa4226524853fbed4df1e99aae87022f65f/5316image1.png" alt="5316image1.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHYzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a69ed64e042995448b57b6df0131efdc401d73cc/5316image2.png" alt="5316image2.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHozQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b218538fbaf69ed80b9cdc8dba52c8b068688217/5316image3.png" alt="5316image3.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDMzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3ca526ff105f2cb6e80ae16105cfd72beec69999/5316image4.png" alt="5316image4.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDczQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--1767a7f236b2fc437e8a89c90eb0322c57be7d6f/5316image5.png" alt="5316image5.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeC8zQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f679dcbfbf06d76faf5ec0236124117eadfd3275/5316image6.png" alt="5316image6.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUQzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0864025bee884de51b0a57ac86538d367d65954b/5316image7.png" alt="5316image7.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUwzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--12a26f02d8f4b5207eec982027bd185d6628da29/5316image8.png" alt="5316image8.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVAzQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8ecc55ab7a7ec1dbd075d3e4de9f521c1e2c273/5316image9.png" alt="5316image9.png" />
