### ISSUE TITLE
[Question] Verify if any workload in Havester that runs as non-root id (different than 0) and has root group id (0)

### ISSUE THREAD

**Issue by PhanLe1010** [harvester/harvester#5318]
Longhorn is planing to change the default group ID of Longhorn device from group id 0 to group id 6 to solve this problem:
* Problem https://github.com/longhorn/longhorn/issues/8088
* Analysis https://github.com/longhorn/longhorn/issues/8088#issuecomment-1982300242

We create this ticket so that the Harvester team can investigate to see any workload in Havester that runs as non-root id (different than 0) and has root group id (0)? if any workload has that config, it will not be able to read Longhorn block device anymore

**Comment by PhanLe1010** [comment]
Thanks @Vicente-Cheng for the help

**Comment by Vicente-Cheng** [comment]
I found that the `virt-launcher` will change the uid/gid to 107(qemu) with its volumes.
So, it seems it works fine and is not affected by the original issue.

Here are my verification steps.
1. build/replace the longhorn-engine of this enhancement https://github.com/longhorn/go-iscsi-helper/pull/79
2. create a VM, hotplug volume from the new engine. Make sure the gid is `6` on the engine side
```
instance-manager-eb472b0a27f589dc2424c5296ae92067:/ # ls -al /dev/longhorn/
total 0
drwxr-xr-x  2 root root   120 Mar 11 14:43 .
drwxr-xr-x 19 root root  4380 Mar 11 14:43 ..
brw-rw----  1 root    6 8, 16 Mar 11 10:54 pvc-862795d0-4190-453a-9ce4-9607614df7eb
```

On the `virt-launcher` pod, the volume uid/gid is changed to 107:107, as shown below.
```
qemu@vm001:/> ls /dev/disk-0 -al
brw-rw---- 1 qemu qemu 8, 16 Mar 11 15:05 /dev/disk-0
```

3. Make sure the VM operation works well. (Migration, IO, restart, snapshot, clone, restore)

I thought we could keep this open until the next release w/ this enhancement.
Once we find other issues, we can update here. Thanks!

**Comment by vasiliy-ul** [comment]
@Vicente-Cheng, @PhanLe1010, I accidentally found this github issue. If non-root access to block devices still brings you troubles, there is a CRI option `device_ownership_from_security_context` [0] which acts similarly to what `fsGroup` does to files and dirs. It is also recommended for CDI [1]. Just FYI.

[0] https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/
[1] https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md

**Comment by Vicente-Cheng** [comment]
I thought we were OK with closing it?

Harvester v1.4 works fine with the changes @PhanLe1010 mentioned.
I will close it tomorrow. If you have any concerns, feel free to update here.
Thanks!

cc @vasiliy-ul, @bk201

**Comment by Vicente-Cheng** [comment]
Close as we did not hit any issue
