### ISSUE TITLE
[ENHANCEMENT] Reduce support bundle generation time

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5323]
**Is your enhancement related to a problem? Please describe.**

Starting from v1.2.1, [we run `supportconfig` on each node to collect system information](https://github.com/rancher/support-bundle-kit/pull/76). However, the script takes several minutes to finish due to unnecessary enabled features and the lack of network capacity in the agent pods. 

If the collecting time exceeds the timeout value (10 minutes), the user can't get any support bundle at all.

**Describe the solution you'd like**

Change `supportconfig` to collect only needed features.

**Regarding lack of network capacity in the agent pod**

While a bundle is generating, you can observe these log in the agent pod:
```
setting the network namespace "cni-9e0f8c93-42d0-9f4c-ff85-fc8b16fbba25" failed: Operation not permitted
setting the network namespace "cni-3f483e1e-6b43-b6f6-d9f5-6c3fedc86915" failed: Operation not permitted
setting the network namespace "cni-3f483e1e-6b43-b6f6-d9f5-6c3fedc86915" failed: Operation not permitted
setting the network namespace "cni-3f483e1e-6b43-b6f6-d9f5-6c3fedc86915" failed: Operation not permitted
setting the network namespace "cni-3f483e1e-6b43-b6f6-d9f5-6c3fedc86915" failed: Operation not permitted
setting the network namespace "cni-3f483e1e-6b43-b6f6-d9f5-6c3fedc86915" failed: Operation not permitted
```

In the agent pod, the command is run for each ns and it might take a while depending on the environment:
```
root     18571  0.0  0.0  10668  2452 ?        S    08:34   0:00 /bin/ping -n -c1 -W1 ip netns exec cni-276b5cb9-1ec8-7ddd-b952-8dd8a747d21d
```

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.3-f8469881-head` (24/03/12). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Single node: reduce **41%** generate support bundle time ( 218s -> 130s ) $~~$</summary>

1. v1.3-head: Generate support bundle takes **130** seconds
 - With one vm, one image and enable all Addons

https://github.com/harvester/harvester/assets/29251855/af34323d-28c6-4ee2-9a31-d3d1ef205b02

2. v1.2.1: Generate support bundle takes: **218** seconds
 - With one vm, one image and enable all Addons

https://github.com/harvester/harvester/assets/29251855/c32bc4c5-6624-4f17-bd2e-192a68fdbbf7


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Single node: the nodes/<node_name>/logs/scc_supportconfig_harvester_xxx.txz file exists $~~$</summary>

1. The `nodes/<node_name>/logs/scc_supportconfig_harvester_xxx.txz` file exists
![image](https://github.com/harvester/harvester/assets/29251855/9c14c854-c0c1-422b-9abc-b2b64ee79bf6)

</details>

<details><summary>$\color{green}{\textsf{PASS}}$ Three nodes: reduce **38%** generate support bundle time ( 270s -> 165s ) $~~$</summary>

1. v1.3-head: Generate support bundle takes: **165** seconds
 - With one vm, one image and enable all Addons


https://github.com/harvester/harvester/assets/29251855/bee235e6-0808-420a-8c4c-e81f720ef331



2. v1.2.1: Generate support bundle takes 270 seconds
- With one vm, one image and enable all Addons


https://github.com/harvester/harvester/assets/29251855/fbf3fb49-b050-4066-a70e-587cc52f6b28


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Three nodes: the nodes/<node_name>/logs/scc_supportconfig_harvester_xxx.txz file exists on each node $~~$</summary>

3. On each node: The `nodes/<node_name>/logs/scc_supportconfig_harvester_xxx.txz` file exists

 -  node1
![image](https://github.com/harvester/harvester/assets/29251855/2b1bdc79-3c2d-46ff-a4cb-ad65c606a9f2)

-  node2
![image](https://github.com/harvester/harvester/assets/29251855/8bf8cdf3-ffd8-4301-8208-4f0661f9819b)

- node3
![image](https://github.com/harvester/harvester/assets/29251855/4c16ae15-62df-408b-aab6-72d5a3696b97)

</details>


<details><summary>$\color{green}{\textsf{PASS}}$ Three nodes: all txt files exists and can open correctly $~~$</summary>

- node1- node1
![image](https://github.com/harvester/harvester/assets/29251855/a9e0b730-ebf9-47d5-bb84-655d3e2260d7)

```
scc_supportconfig_node2/basic-environment.txt
scc_supportconfig_node2/basic-health-check.txt
scc_supportconfig_node2/boot.txt
scc_supportconfig_node2/etc.txt
scc_supportconfig_node2/fs-diskio.txt
scc_supportconfig_node2/fs-iscsi.txt
scc_supportconfig_node2/fs-smartmon.txt
scc_supportconfig_node2/hardware.txt
scc_supportconfig_node2/memory.txt
scc_supportconfig_node2/messages.txt
scc_supportconfig_node2/messages_localwarn.txt
scc_supportconfig_node2/modules.txt
scc_supportconfig_node2/pam.txt
scc_supportconfig_node2/plugin-harvester_plugin_console.txt
scc_supportconfig_node2/plugin-harvester_plugin_rke2.txt
scc_supportconfig_node2/rpm.txt
scc_supportconfig_node2/summary.xml
scc_supportconfig_node2/supportconfig.txt
scc_supportconfig_node2/systemd.txt
scc_supportconfig_node2/y2log.txt
```

- node2

![image](https://github.com/harvester/harvester/assets/29251855/b3d1e9a9-416d-4819-90dd-5f1c12dbac0a)


- node3

![image](https://github.com/harvester/harvester/assets/29251855/f4512737-01dd-4a79-a81f-453161419ee1)




</details>


### Test Information
* Test Environment: Single node on local kvm and three nodes baremetal machines
* Harvester version: `v1.3-f8469881-head` (24/03/12)

### Verify Steps
<details><summary> Test steps </summary>

  1. Prepare a single and three nodes Harvester v1.3-head cluster
  2. Enable all addons
  3. Create one virtual machine
  4. Generate the support bundle
  5. Record the total time in seconds
  6. Confirm can save the support bundle
  7. Extract the support bundle zip file
  8. Extract every txz file in the `nodes/<node-name>/logs with command
  ```
  $ tar Jxvf scc_supportconfig_node3.txz
  ```
  9. Ensure all the files exists under the txz archive file
  10. Check can open every txt files in the extracted folder

</details>
