### ISSUE TITLE
[BUG] UI error message when adding label on witness node

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5326]
## Environment
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: QEMU/KVM, 2 nodes with witness(8C/16G/500G)
  * ui-source: `Auto`

## Steps
1. Setup a harvester cluster with witness node

1. Hosts -> WITNESS_NODE -> Edit Config -> Labels
   ![image](https://github.com/harvester/harvester/assets/2773781/66fd173a-d585-4a74-8350-cf99c0db1ae2)

**Comment by bk201** [comment]
@Vicente-Cheng Can you help check if this is a backend issue? Thanks.

**Comment by Vicente-Cheng** [comment]
I do some tests on my side.

1. On the UI side
It looks like the first label has been added, and some requests report error 409.

**UPDATE** I can add labels successfully in very few times. (maybe 1/10)

2. On the CLI side
I can use the kubectl command to add labels without error.

**Comment by torchiaf** [comment]
@a110605 did you reproduce this issue in your local env. ?

**Comment by a110605** [comment]
yeah, can reproduce on witness node. Although error message report `Cannot read properties of undefined (reading 'save')`, but the label is successfully added even I changed to other browser.

The PUT `https://192.168.0.131/v1/harvester/nodes/harvester-node-1` also got response 200 with label I added.


![456](https://github.com/harvester/harvester/assets/5744158/561e273f-6649-4e62-8919-7df2ff3deef4)

**Comment by a110605** [comment]
The code goes to [await this.applyHooks(AFTER_SAVE_HOOKS);](https://github.com/harvester/dashboard/blob/b2e94bbf6d1325b627a9ebba195f78f2bb772691/shell/mixins/create-edit-view/impl.js#L155) and have a above undefined exception.
![Screenshot_20240619_231834](https://github.com/harvester/harvester/assets/5744158/f5656035-5e37-4b90-94d8-54ca80ae3f2f)

**Comment by a110605** [comment]
[this.longhornNode](https://github.com/harvester/dashboard/blob/b2e94bbf6d1325b627a9ebba195f78f2bb772691/pkg/harvester/edit/harvesterhci.io.host/index.vue#L489) is undefined. Something wrong in [longhornNode()](https://github.com/harvester/dashboard/blob/b2e94bbf6d1325b627a9ebba195f78f2bb772691/pkg/harvester/edit/harvesterhci.io.host/index.vue#L213-L217)

![find](https://github.com/harvester/harvester/assets/5744158/0aceeb47-50b6-4a20-9665-bea616c07e73)



[longhornNodes](https://github.com/harvester/dashboard/blob/b2e94bbf6d1325b627a9ebba195f78f2bb772691/pkg/harvester/edit/harvesterhci.io.host/index.vue#L215) should get "longhorn-system/harvester-node-1" not "longhorn-system/harvester-node-0" 

![Screenshot_20240619_233706](https://github.com/harvester/harvester/assets/5744158/2a6e6ce0-9bea-4238-8b73-6d0623207e58)


cc @torchiaf , @Vicente-Cheng

**Comment by Vicente-Cheng** [comment]
Hi @a110605, sorry for the late reply

I thought that because the witness node did not have the CRD `nodes.longhorn.io`.
Could we skip updating this resource when the node is a witness node?

**Comment by bk201** [comment]
set p2 because the CLI way still works.

**Comment by albinsun** [comment]
Test OK on `v1.4.0-dev-20240719`, close as fixed.


## Environment
* harvester-`v1.4.0-dev-20240719`
  * Profile: 2 & 3 nodes QEMU/KVM (8C/16G/500G)
  * ui-source: `Auto`


## Steps
1. <details>
   <summary> Setup a 2 nodes harvester cluster with witness node
   </summary>

   ![image](https://github.com/user-attachments/assets/d7ac5183-534c-4f80-96e2-a64601625a2a)

   ![image](https://github.com/user-attachments/assets/15a32673-8b34-4481-a808-71768a357221)
   </details>

1. <details>
   <summary> <b>Hosts</b> -> WITNESS_NODE -> <b>Edit Config</b> -> <b>Labels</b>
   </summary>

   ![image](https://github.com/user-attachments/assets/c1e7fbf9-ce1b-493c-949c-ebe7d6d98b4e)
   </details>

1. <details>
   <summary> Update label
   </summary>

   ![image](https://github.com/user-attachments/assets/e7c8c965-7c20-4b00-9dd6-b5bc579e64cf)
   </details> 

1. <details>
   <summary> Delete label
   </summary>

   ![image](https://github.com/user-attachments/assets/767eb78f-6be6-4ae4-806c-cda5c64d68c0)
   </details> 

1. <details>
   <summary> Join 3rd node (node-2), labels still there.
   </summary>

   ![image](https://github.com/user-attachments/assets/4437318d-e69c-4287-8309-c1cd2091fb8f)

   ![image](https://github.com/user-attachments/assets/230fd894-4e5c-4c17-b009-5e94584a6b9d)
   </details>

1. <details>
   <summary> Add a new label
   </summary>

   ![image](https://github.com/user-attachments/assets/c1ae1d3e-620e-4c6d-bcc0-6b4270bf9925)
   </details> 

1. <details>
   <summary> Update label
   </summary>

   ![image](https://github.com/user-attachments/assets/dd799876-8ba7-41bf-9b70-b9d70dca2062)
   </details> 

1. <details>
   <summary> Delete label
   </summary>

   ![image](https://github.com/user-attachments/assets/16ade869-c104-4385-8357-03a552e2bd1c)
   </details>  

1. <details>
   <summary> Label operation on non-witness nodes works
   </summary>
   
   ![image](https://github.com/user-attachments/assets/56523a0c-c46a-418f-b3a1-bd5ef1d5e6f0)
   </details>
