### ISSUE TITLE
[ENHANCEMENT] Move CI builds to Github Action

### ISSUE THREAD

**Issue by innobead** [harvester/harvester#5327]
**Is your enhancement related to a problem? Please describe.**

Currently, we are using Drone as our CI backend, but it lacks active maintenance for a while, despite its independence from source code version control management platforms. 

Since we heavily rely on GitHub for code maintenance, development cycle, and artifact delivery, leveraging GitHub Actions would be a compelling choice.  GitHub Actions is becoming a CI workflow-compatible interface to be supported in other solutions like Gitea and has the potential to expand to other platforms in the future.

@Yu-Jack has a guide on https://github.com/harvester/harvester/wiki/Moving-Drone-CI-to-Github-Action

| Done | Repository | Owner |
| --- | --- | --- |
| 🟢 | https://github.com/harvester/bot |  @Yu-Jack   |
| 🔵 | https://github.com/harvester/charts | - |
| 🟢| https://github.com/harvester/cloud-provider-harvester | @w13915984028  |
| 🟢 | https://github.com/harvester/dashboard | @torchiaf  |
| 🔵 | https://github.com/harvester/docker-machine-driver-harvester | - |
| 🟢  | https://github.com/harvester/docs | @jillian-maroket |
| 🟢 | https://github.com/harvester/eventrouter | @w13915984028 |
| 🔵 | https://github.com/harvester/experimental-addons | - |
| 🔵 | https://github.com/harvester/go-common | - |
| 🟢 | https://github.com/harvester/harvester | @FrankYang0529 |
| 🟢 | https://github.com/harvester/harvester-csi-driver | @Vicente-Cheng |
| 🟢 | https://github.com/harvester/harvester-installer | @tserong |
| 🔵 | https://github.com/harvester/harvesterhci.io | - |
| 🟢 | https://github.com/harvester/load-balancer-harvester | @starbops |
| 🟢 | https://github.com/harvester/network-controller-harvester | @mingshuoqiu |
| 🟢 | https://github.com/harvester/node-disk-manager | @Vicente-Cheng |
| 🟢 | https://github.com/harvester/node-manager | @brandboat  |
| 🟢 | https://github.com/harvester/os2 | @Vicente-Cheng |
|🟢 | https://github.com/harvester/pcidevices | @ibrokethecloud |
|🟢 | https://github.com/harvester/seeder | @ibrokethecloud |
|🟢 | https://github.com/rancher/rancherd | @FrankYang0529 |
| 🟢 | https://github.com/rancher/support-bundle-kit | @Yu-Jack  |
| 🟢 | https://github.com/harvester/vm-dhcp-controller | @starbops |
| 🟢 | https://github.com/harvester/vm-import-controller | @ibrokethecloud  |
| 🟢 | https://github.com/harvester/terraform-provider-harvester | @FrankYang0529 |
| 🟢 | https://github.com/rancher/local-path-provisioner | @derekbit |

> By @Yu-Jack, I used simple icons to represent the current state, feel free to use it.
> 
> 🟢 means all done, including removing drone CI.
> 🔵 no need
> 🟠 means action is ready, and wait for secret migration.

**Comment by innobead** [comment]
cc @rebeccazzzz

**Comment by bk201** [comment]
@innobead I think we need to wait until self hosted runner from the EIO team is ready right?

**Update** I have received guidance.

**Comment by Yu-Jack** [comment]
Leave some information here.

We don't need to use following setting to run dapper, we could run `make ci` directly. If needs, check this example  https://github.com/rancher/support-bundle-kit/blob/master/.github/workflows/template-build.yml.

```yaml
container:
      image: rancher/dapper:v0.5.8
```

**Comment by Yu-Jack** [comment]
I wrote a quick guideline to move Drone CI to Github Action, free feel to leave any comments to revise this wiki, thanks.

https://github.com/harvester/harvester/wiki/Moving-Drone-CI-to-Github-Action

**Comment by innobead** [comment]
@brandboat Please help with this item. 
> | | https://github.com/harvester/node-manager | @brandboat  |

**Comment by bk201** [comment]
All repos migrate to GHA. Thanks all!
