### ISSUE TITLE
[BUG] Scaling worker pool incorrectly scales control plane instead

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#5330]
**Describe the bug**

During rancher integration test, there is a weird behavior when creating two pools one for controlplane + etcd, another one is for worker, and pressing the scale + / - bottom in worker pool, it scale up / down control plane pool instead. 
**While this only happened when using Terraform, use GUI to create cluster won't happen.**

scale up

[Screencast from 2024-03-11 12-14-05.webm](https://github.com/harvester/harvester/assets/4344302/4617ab19-583c-4a19-8c0d-90f0e76dfed2)

scale down

[Screencast from 2024-03-11 12-37-00.webm](https://github.com/harvester/harvester/assets/4344302/1b7d43c5-8de0-42a3-b9bd-d1777846feee)

**To Reproduce**
1. setup harvester with 3 nodes
2. setup rancher
    -  `docker run --privileged -d --name=rancher --restart=unless-stopped -p 8080:80 -p 6443:443 rancher/rancher:v2.7.10`
3. import harvester to rancher
4. Use terraform to create rancher cluster
    - Download terraform settings 
[guest-cluster-in-harvester-example-rancher-integration-test-1.3.0-rc-4.zip](https://github.com/harvester/harvester/files/14553534/guest-cluster-in-harvester-example-rancher-integration-test-1.3.0-rc-4.zip) ([github link](https://github.com/brandboat/guest-cluster-in-harvester-example/tree/rancher-integration-test-1.3.0-rc-4))
    - unzip the zipfile
    - run `terraform init`
    - create image and vm network in harvester
    - Then edit config terraform.tfvars, cloud-init-template and modules/guest_cluster_harvester_cloud_provider/kvm.config (the kubeconfig file)
    - run `terraform apply -target=module.guest_cluster_harvester_cloud_provider`
5. After cluster is created, go to rancher cluster page and click scale up button in worker pool (which role is worker)

**Expected behavior**

Click worker pool scale up / down button should only scale up/down nodes in worker pool

**Support bundle**

[supportbundle_7dd5d53a-dd6d-4732-9a1b-531cd1869689_2024-03-11T04-26-06Z.zip](https://github.com/harvester/harvester/files/14553510/supportbundle_7dd5d53a-dd6d-4732-9a1b-531cd1869689_2024-03-11T04-26-06Z.zip)

**Environment**
- Harvester ISO version: 1.3.0-rc4 with 3 node cluster (8cpu, 16GB ram, 250GB disk)
- Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): KVM
- rancher: 2.7.10

**Additional context**
N/A

**Comment by FrankYang0529** [comment]
This may be a UI bug. I can see UI send a request to decrease control-plane pool even if I check button on worker pool.

1. ✅ Click plus on control-plan pool. The quantity on control-plan pool is increased to 2.

![Screenshot 2024-03-11 at 4 06 29 PM](https://github.com/harvester/harvester/assets/4927361/7fbd0a89-006d-476a-b2d0-d56e0f7d7f95)

2. ❌ Click minus on worker pool. The quantity on worker pool is not decreased, but control-plan pool is decreased to 1.

![Screenshot 2024-03-11 at 4 07 11 PM](https://github.com/harvester/harvester/assets/4927361/442f232e-d3b9-42c1-b5c5-53db3c89fa5a)

**Comment by bk201** [comment]
@torchiaf Can you help with this issue, note it seems to only be reproduced when a cluster is deployed with terraform provider.

**Comment by FrankYang0529** [comment]
I found the root cause: we should use different `rancher2_machine_config_v2` for different machine pools. In the example, we use same `harvesterkvm` config for both pools. In my last comment, we can see two pools have same `machineConfigRef`, so UI can't choose a correct pool to increase or decrease quantity.

https://github.com/brandboat/guest-cluster-in-harvester-example/blob/7389abd723a1e53c4f6b0d353e7318c8ed75023f/modules/guest_cluster_harvester_cloud_provider/main.tf#L50-L53

**Comment by bk201** [comment]
@brandboat Can you help modify the terraform files and re-verify again? Thank you!

**Comment by torchiaf** [comment]
Likely, the first `machinePoll` is always selected here:

https://github.com/rancher/dashboard/blob/01eeb0548fe3b9326961ad58a7dc43cd266e6e0c/shell/models/cluster.x-k8s.io.machinedeployment.js#L105

and then scaled up/down:

https://github.com/rancher/dashboard/blob/01eeb0548fe3b9326961ad58a7dc43cd266e6e0c/shell/models/cluster.x-k8s.io.machinedeployment.js#L116

**Comment by brandboat** [comment]
> @brandboat Can you help modify the terraform files and re-verify again? Thank you!

Yeah, like @FrankYang0529 mentioned in https://github.com/harvester/harvester/issues/5330#issuecomment-1988323218, this issue was caused by incorrect machine_config setting, we can't use the same machine_config in different pools. After correcting that, scale +/- works fine. 

Thanks for your time, @FrankYang0529 and @torchiaf . Huge thanks !

[Screencast from 2024-03-12 14-25-15.webm](https://github.com/harvester/harvester/assets/4344302/3c515e49-423a-4aff-aca2-1b3d10b2afaf)

[Screencast from 2024-03-12 14-33-49.webm](https://github.com/harvester/harvester/assets/4344302/a271d7c5-f507-47ab-a4ff-22648914ae02)
