### ISSUE TITLE
[BUG] Rancher fail to deploy harvester-cloud-provider pod on Import Existing RKE2 VM  

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5332]
**Describe the bug**
Fail to install **harvester-cloud-provider** app in the **Import Existing** RKE2 VM case 

```
# /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml logs -f -n kube-system harvester-cloud-provider-77d47fb757-pt7q2
I0311 04:45:35.401474       1 serving.go:348] Generated self-signed cert in-memory
failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
Error: failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
Usage:
  cloud-controller-manager [flags]
...
```

**To Reproduce**
1. Create rke2 Harvester node driver cluster (Import)
   * <details>
     <summary> :green_circle: 
     Create VM with cloud-provider & csi-driver cloud-config
     </summary>
   
     cloud-provider[^4] & csi-driver[^5] cloud-config
     ![image](https://github.com/harvester/tests/assets/2773781/8a0e9910-ac92-49c7-9c29-56e467d1c3df)
     VM status
     ![image](https://github.com/harvester/tests/assets/2773781/ad5ed40b-3593-49be-804f-733daf3def79)
     </details>

   * <details>
     <summary> :green_circle: 
     Setting up a RKE2 VM and import to Rancher 
     </summary>
   
     Install RKE2 service on VM [^1]
     ![image](https://github.com/harvester/tests/assets/2773781/ec16f68b-fbb4-4b53-96ed-d37682ceca16)
     </details>
     
   * <details>
     <summary> :green_circle: 
     Set <code>cattle-cluster-agent</code> to <code>preferredDuringSchedulingIgnoredDuringExecution</code> and import to Rancher 
     </summary>
   
     Ref. https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/about-rancher-agents
     Import RKE2 VM to Rancher [^2][^3]
     ![image](https://github.com/harvester/tests/assets/2773781/3075cb4b-6907-4663-8c70-1f9a3506551a)
     </details>

   * <details open>
     <summary> :red_circle: 
     Install harvester-cloud-provider
     </summary>
     
     ${\color{red} \text{App OK but deployment stucks in Updating due to pod Crashloopbackoff}}$
     ![image](https://github.com/harvester/tests/assets/2773781/8300bb09-4b4f-49bd-942e-73b7e2f404e8)
     ![image](https://github.com/harvester/tests/assets/2773781/13096783-31d5-4745-b18d-99508582d6fb)
     </details>

   * <details>
     <summary> :green_circle: 
     Install harvester-csi-driver
     </summary>
     
     ![image](https://github.com/harvester/tests/assets/2773781/5d1d6ab4-48bf-46d3-b3b0-2aef4a798ed9)
     </details>

**Expected behavior**
harvester-cloud-provider should be deploy successfully

**Support bundle**
* [supportbundle_2499ea15-c8d9-4800-86f8-a61c8e8b42cc_2024-03-11T04-46-38Z.zip](https://github.com/harvester/harvester/files/14553640/supportbundle_2499ea15-c8d9-4800-86f8-a61c8e8b42cc_2024-03-11T04-46-38Z.zip)
* harvester-cloud-provider pod log
  ```
  # /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml get pod -n kube-system harvester-cloud-provider-77d47fb757-pt7q2
  NAME                                        READY   STATUS             RESTARTS        AGE
  harvester-cloud-provider-77d47fb757-pt7q2   0/1     CrashLoopBackOff   9 (4m39s ago)   25m

  # /var/lib/rancher/rke2/bin/kubectl --kubeconfig /etc/rancher/rke2/rke2.yaml logs -f -n kube-system harvester-cloud-provider-77d47fb757-pt7q2
  I0311 04:45:35.401474       1 serving.go:348] Generated self-signed cert in-memory
  failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
  Error: failed to create listener: failed to listen on 0.0.0.0:10258: listen tcp 0.0.0.0:10258: bind: address already in use
  Usage:
    cloud-controller-manager [flags]
  
  ...
  ```

* rke2-server.service 
  ```
  root@myrke2-import-m1:~# journalctl -u rke2-server.service --follow
  -- Logs begin at Mon 2024-03-11 04:11:28 UTC. --
  Mar 11 04:15:31 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:31Z" level=info msg="Updating TLS secret for kube-system/rke2-serving (count: 12): map[listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.0.54:192.168.0.54 listener.cattle.io/cn-__1-f16284:::1 listener.cattle.io/cn-another-kubernetes-domain.com:another-kubernetes-domain.com listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc:kubernetes.default.svc listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-my-kubernetes-domain.com:my-kubernetes-domain.com listener.cattle.io/cn-myrke2-import-m1:myrke2-import-m1 listener.cattle.io/fingerprint:SHA1=7728443E22C685501FBC237D5EE0FBD936AE76BF]"
  Mar 11 04:15:33 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:33Z" level=info msg="Running kube-proxy --cluster-cidr=10.42.0.0/16 --conntrack-max-per-core=0 --conntrack-tcp-timeout-close-wait=0s --conntrack-tcp-timeout-established=0s --healthz-bind-address=127.0.0.1 --hostname-override=myrke2-import-m1 --kubeconfig=/var/lib/rancher/rke2/agent/kubeproxy.kubeconfig --proxy-mode=iptables"
  Mar 11 04:15:34 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:34Z" level=error msg="error syncing 'kube-system/rke2-metrics-server': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-metrics-server\" not found, requeuing"
  Mar 11 04:15:34 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:34Z" level=error msg="error syncing 'kube-system/rke2-snapshot-controller-crd': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-snapshot-controller-crd\" not found, requeuing"
  Mar 11 04:15:35 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:35Z" level=error msg="error syncing 'kube-system/rke2-snapshot-controller': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-snapshot-controller\" not found, requeuing"
  Mar 11 04:15:35 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:35Z" level=error msg="error syncing 'kube-system/rke2-snapshot-validation-webhook': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-snapshot-validation-webhook\" not found, requeuing"
  Mar 11 04:15:42 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:15:42Z" level=info msg="Adding node myrke2-import-m1-43e9f5e1 etcd status condition"
  Mar 11 04:16:40 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:16:40Z" level=info msg="Tunnel authorizer set Kubelet Port 10250"
  Mar 11 04:20:29 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:20:29Z" level=info msg="Updating TLS secret for kube-system/rke2-serving (count: 13): map[field.cattle.io/projectId:c-m-4h9lrx4b:p-r8scv listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.0.54:192.168.0.54 listener.cattle.io/cn-__1-f16284:::1 listener.cattle.io/cn-another-kubernetes-domain.com:another-kubernetes-domain.com listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc:kubernetes.default.svc listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-my-kubernetes-domain.com:my-kubernetes-domain.com listener.cattle.io/cn-myrke2-import-m1:myrke2-import-m1 listener.cattle.io/fingerprint:SHA1=7728443E22C685501FBC237D5EE0FBD936AE76BF]"
  Mar 11 04:20:29 myrke2-import-m1 rke2[2430]: time="2024-03-11T04:20:29Z" level=info msg="Active TLS secret kube-system/rke2-serving (ver=2665) (count 13): map[field.cattle.io/projectId:c-m-4h9lrx4b:p-r8scv listener.cattle.io/cn-10.43.0.1:10.43.0.1 listener.cattle.io/cn-127.0.0.1:127.0.0.1 listener.cattle.io/cn-192.168.0.54:192.168.0.54 listener.cattle.io/cn-__1-f16284:::1 listener.cattle.io/cn-another-kubernetes-domain.com:another-kubernetes-domain.com listener.cattle.io/cn-kubernetes:kubernetes listener.cattle.io/cn-kubernetes.default:kubernetes.default listener.cattle.io/cn-kubernetes.default.svc:kubernetes.default.svc listener.cattle.io/cn-kubernetes.default.svc.cluster.local:kubernetes.default.svc.cluster.local listener.cattle.io/cn-localhost:localhost listener.cattle.io/cn-my-kubernetes-domain.com:my-kubernetes-domain.com listener.cattle.io/cn-myrke2-import-m1:myrke2-import-m1 listener.cattle.io/fingerprint:SHA1=7728443E22C685501FBC237D5EE0FBD936AE76BF]"
  ```

**Environment**
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.8.1`
  * Profile: Docker (1C/4G)

**Additional context**
1. RKE2 cluster directly create from Rancher works.
   see harvester/tests#1150

[^1]: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher
[^2]: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-clusters-in-rancher-setup/register-existing-clusters
[^3]: https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/launch-kubernetes-with-rancher/about-rancher-agents
[^4]: https://docs.harvesterhci.io/v1.3/rancher/cloud-provider#deploying-to-the-rke2-custom-cluster-experimental
[^5]: https://docs.harvesterhci.io/v1.3/rancher/csi-driver/#deploy-harvester-csi-driver

**Comment by w13915984028** [comment]
@albinsun  There has already been a CCM pod deployed before this VM is imported to REK2

![image](https://github.com/harvester/harvester/assets/31133476/f020972b-c52d-453a-90c8-a6b6f62eb35d)

When `harvester-cloud-provider` is to be deployed, the original ccm should be disabled/removed to avoid port duplication (10258 and/or others).

You may double check the directly deployed rke2 cluster with harvester cloud provider, there should no `ccm` related pods.

About 10258 port, refer: https://github.com/k3s-io/k3s/issues/6554 or others.

**Comment by irishgordo** [comment]
@albinsun  where you able to implement a workaround?
Is it just deleting the old pod?
I'm running into this on v1.3.0-rc4 airgap
![Screenshot from 2024-03-11 22-40-37](https://github.com/harvester/harvester/assets/5370752/50f168d8-912a-4991-9bd3-037b0d74d075)

I'm not able to "update" the cloud provider it seems

**Comment by albinsun** [comment]
> @albinsun where you able to implement a workaround? Is it just deleting the old pod? I'm running into this on v1.3.0-rc4 airgap ![Screenshot from 2024-03-11 22-40-37](https://private-user-images.githubusercontent.com/5370752/311954800-50f168d8-912a-4991-9bd3-037b0d74d075.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAyMjI0MDMsIm5iZiI6MTcxMDIyMjEwMywicGF0aCI6Ii81MzcwNzUyLzMxMTk1NDgwMC01MGYxNjhkOC05MTJhLTQ5OTEtOWJkMy0wMzdiMGQ3NGQwNzUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMTJUMDU0MTQzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MjhlZTQ3OGY1NzczMTBiZmI1MWE3OGM0ZTNlN2ZiNzAyNmNjNDM5NzU0Y2JkZDFlZmI5NWU2YjEwZDg3M2YyNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.D2h_htPegkRWnlKR3NfxSLSxFo7TnjsimktVeS93-jg)
> 
> I'm not able to "update" the cloud provider it seems

@irishgordo , I haven't try upgrade yet since it just not fully deployed when install.

**Comment by starbops** [comment]
By default, installing the RKE2 (according to https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher#1-install-kubernetes-and-set-up-the-rke2-server) will also bring up the `cloud-controller-manager` as a static pod. To be able to **import** VMs with RKE2 running to a Rancher Manager and enable the Harvester cloud provider, users need to disable the cloud-controller-manager via `/etc/rancher/rke2/config.yaml`:

```yaml
token: my-shared-secret
tls-san:
  - my-kubernetes-domain.com
  - another-kubernetes-domain.com
disable-cloud-controller: true  # <-- disable cloud-controller-manager so it will not conflict with harvester-cloud-provider
```

This could be done from the beginning or after the RKE2 is fully installed and running (will need to restart RKE2 after apply the config shown above.)

**Comment by albinsun** [comment]
Thank you @starbops and @w13915984028,

harvester-cloud-provieer can successfully deploy after adding `disable-cloud-controller: true` in `/etc/rancher/rke2/config.yaml`. Close it.
![image](https://github.com/harvester/harvester/assets/2773781/64b9e4a9-e4bb-4659-bef6-d0220814f577)


But we found that deployment with pvc will hit `0/1 nodes are available: pod has unbound immediate PersistentVolumeClaims. preemption: 0/1 nodes are available: 1 Preemption is not helpful for scheduling..`
However, it's not the scope of this ticket, let's trace in another one.
![image](https://github.com/harvester/harvester/assets/2773781/7c7459ba-9038-4c5a-bb44-cea11b284b79)

**Comment by khushboo-rancher** [comment]
@starbops @w13915984028 Should we mention this in our documentation somewhere. I don't see `importing rke2 cluster in Harvester` section in our doc, do you think we can add that?

**Comment by w13915984028** [comment]
@khushboo-rancher Documents should be updated.

I guess your new issue https://github.com/harvester/harvester/issues/6147 is for it. thanks.
