### ISSUE TITLE
[BUG] The witness node should not be selected as a migration target 

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5338]
**Describe the bug**
The witness node should not be selected as a migration target.

The cluster would be like:
```
NAME               STATUS   ROLES                       AGE     VERSION
harvester-node-0   Ready    control-plane,etcd,master   4d13h   v1.27.10+rke2r1
harvester-node-1   Ready    etcd                        4d13h   v1.27.10+rke2r1
harvester-node-2   Ready    control-plane,etcd,master   4d13h   v1.27.10+rke2r1
```

The `harvester-node-1` can still be selected as a migration target.
<img width="1238" alt="截圖 2024-03-11 下午4 23 40" src="https://github.com/harvester/harvester/assets/1615081/a2270370-e42a-42b7-bcb5-21aa9f6e7488">

**To Reproduce**
1. Create a cluster with a witness node.
2. Create a VM
3. Try to migrate the above VM.
4. Check the witness node, which will be the migration list.

**Expected behavior**
The witness node should not be selected as a migration target.

**Support bundle**
None.

**Environment**
 - Harvester ISO version: v1.3.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): kvm

**Additional context**

**Comment by markhillgit** [comment]
should release note this in 1.3.0, the fix may need to be in an upcoming release

**Comment by bk201** [comment]
@Vicente-Cheng please help add this to known issue on https://github.com/harvester/docs/pull/522

**Comment by Vicente-Cheng** [comment]
Updated to the above document PR

**Comment by a110605** [comment]
@Vicente-Cheng , @bk201 , is it okay to add `backport-needed/v1.3.3` label for this issue ?

**Comment by Vicente-Cheng** [comment]
It should be. Added.

**Comment by rrajendran17** [comment]
verified on v1.4-rc2 and it works as expected.

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK1kvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--83a8bcd93a8be38226dd0e64f018885aefa0b331/5338img1.png" alt="5338img1.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2cvQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cd88c9bdb52fe18b3bff468d2d469517aac7e78/5338img2.png" alt="5338img2.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK2svQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ba71640586cc72d25a966b8933bd97470f5dc5c1/5338img3.png" alt="5338img3.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBK28vQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b3bb949b3b66ec74da9f43b679d5fa583009766e/5338img4.png" alt="5338img4.png" />
