### ISSUE TITLE
[BUG] You can't deploy PCI devices if you deploy nvidia toolkit vgpu addon first

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5340]
**Describe the bug**

When you deploy the nvidia toolkit 
**To Reproduce**
1. Deploy a single node with v1.3.0-rc4
2. Enable the nvidia toolkit in the addons section
3. Wait for it to deploy
4. Enable PCI devices

**Expected behavior**

You should be able to enable both addons in that order, or you shouldn't be able to and get an error

**Support bundle**

[supportbundle_d7c7beea-fdc1-4607-900f-0b7ee8d4958e_2024-03-12T00-17-23Z.zip](https://github.com/harvester/harvester/files/14565688/supportbundle_d7c7beea-fdc1-4607-900f-0b7ee8d4958e_2024-03-12T00-17-23Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL360 and A102 tesla Nvidia gpu

**Additional context**
This was working before, but I think I did it in another order while testing #2764  
1. Enable PCI devices controller
2. Wait for it to deploy
3. Enable nvidia toolkit
4. wait for nvidia toolkit to deploy
5. configure nvidia toolkit

I want to double check that is still working, but I'm leaving up the environment for debugging for now.

![Greenshot 2024-03-11 17 14 50](https://github.com/harvester/harvester/assets/83787952/c8d235f9-5252-4bb1-a9c6-95024084cbc4)
![Greenshot 2024-03-11 17 08 33](https://github.com/harvester/harvester/assets/83787952/de891aa4-dc9b-4c39-9e2d-df765d8f7e46)
![Greenshot 2024-03-11 17 08 26](https://github.com/harvester/harvester/assets/83787952/e5eb44d6-fe3c-46af-88b4-29f99ca3d688)
![Greenshot 2024-03-11 17 08 11](https://github.com/harvester/harvester/assets/83787952/3761c02c-e9e8-4302-a030-2c6b0f3e73a2)
![Greenshot 2024-03-11 17 08 06](https://github.com/harvester/harvester/assets/83787952/784990c4-c2cd-4de6-875d-1568436632ca)

**Comment by ibrokethecloud** [comment]
this has been fixed: https://github.com/harvester/harvester-installer/pull/676

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/5337
