### ISSUE TITLE
[ENHANCEMENT] Automatically parse name of SSH key 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5342]
**Is your enhancement related to a problem? Please describe.**
When creating SSH key, it will be conveient if **Name** can be automatically parsed from key content just like the behavior in image creating.
> [!NOTE]
> It will work only when the name contains "@" , e.g. john.doe@mail.com

**Describe the solution you'd like**
![image](https://github.com/harvester/harvester/assets/2773781/3452937f-aed0-4c1f-94ec-fe4a7a2afe61)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by albinsun** [comment]
Hi @Yu-Jack ,
Can we test this on non `v1.4.0` branch or w/ specific **ui-source**?

**Comment by Yu-Jack** [comment]
@albinsun yes, it's nothing related to backend, it's just frontend.

**Comment by albinsun** [comment]
Provide test result on `v1.2-f414942f-head`, close as fixed.

## Environment
* Harvester
  * Version: `v1.2-f414942f-head`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`

## Test Steps
1. Go to **Settings** -> **ntp-servers**
   ![image](https://github.com/harvester/harvester/assets/2773781/e49316ae-665e-4e1c-b4d0-8ed05037aded)
   ![image](https://github.com/harvester/harvester/assets/2773781/ebf63021-5171-4327-8878-4fbeb609b399)

**Comment by albinsun** [comment]
Provide test result on `master-ba586eaf-head`, suffix w/o `@` still not parse.

Should I use other **ui-index** sourse?
Please help to check, thanks.


## Environment
* Harvester
  * Version: `master-ba586eaf-head`
  * Profile: QEMU/KVM, single nodes (8C/16G/500G)
  * ui-source: `Auto`
    ![image](https://github.com/harvester/harvester/assets/2773781/89dad4e1-fb2a-432c-a192-67b583e73505)



## Test Cases
### Read from File
1. <details>
   <summary> :green_circle:  Mail suffix
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/1a559485-0fee-49b2-a63f-4bacf725c2d4)
   </details>

1. <details open>
   <summary> :red_circle: Name suffix
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/bbdc3967-6dd3-4b97-8698-55218eebc138)
   </details>

1. :white_circle: Empty suffix

### Paste
1. :white_circle: Mail suffix

1. :white_circle: Name suffix

1. :white_circle: Empty suffix

**Comment by albinsun** [comment]
Provide test result on `master-41b6fd1e-head`, both name and mail suffix can be parsed, close as fixed.
![image](https://github.com/harvester/harvester/assets/2773781/897e8d5a-a758-4886-b1c2-49edb490cda5)


## Environment
* Harvester
  * Version: `master-41b6fd1e-head`
  * Profile: QEMU/KVM, single nodes (16C/32G/500G)
  * ui-source: `Auto`


## Test Cases
### Read from File
1. <details>
   <summary> :green_circle:  Mail suffix
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/6dbc1c6f-889e-418f-af80-77bfec9066be)
   </details>

1. <details>
   <summary> :green_circle: Name suffix
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/c78367b1-ecc8-4b03-8339-b0df711519a6)
   </details>

1. <details>
   <summary> :green_circle: Empty suffix
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/bd7571bb-6620-428e-83fd-b945efec614b)
   </details>

### Paste
1. <details>
   <summary> :green_circle: Mail suffix
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/9e2736c0-d378-4561-8f7b-bf87714e0e73)
   </details>

1. <details>
   <summary> :green_circle: Name suffix
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/897e8d5a-a758-4886-b1c2-49edb490cda5)
   </details>

1. <details>
   <summary> :green_circle: Empty (w/ space) suffix
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/85c1c3c0-4a59-4c73-95a5-598dfdcd449c)
   </details>
