### ISSUE TITLE
[BUG] LoadBalancer stuck Pending in the Import Existing RKE2 case

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5345]
**Describe the bug**
In the Import Existing RKE2 case,we encounter LB can not deploy due to `Error syncing load balancer: failed to ensure load balancer: wait ip timeout`
![image](https://github.com/harvester/harvester/assets/2773781/62be4d60-1b43-4115-b8f1-4c06acfdf8a3)

**To Reproduce**
1. Create VM on Harvester with pre-gen cloud-provider & csi-driver cloud-config
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/2b034245-5b0e-49b1-9371-3031dfc5630b)
   </details>

   * cloud-provider
     ```
     curl -sfL https://raw.githubusercontent.com/harvester/cloud-provider-harvester/master/deploy/generate_addon.sh | bash -s RKE2_CLUSTER_NAME default
     ```
   * csi-driver
     ```
     curl -sfL https://raw.githubusercontent.com/harvester/harvester-csi-driver/master/deploy/generate_addon_csi.sh | bash -s RKE2_CLUSTER_NAME default RKE2
     ```

2. SSH to VM and setup RKE2 manually
   * Ref. https://ranchermanager.docs.rancher.com/how-to-guides/new-user-guides/kubernetes-cluster-setup/rke2-for-rancher#1-install-kubernetes-and-set-up-the-rke2-server
   * _/etc/rancher/rke2/config.yaml_ should be
     ```
     token: my-shared-secret
     tls-san:
       - my-kubernetes-domain.com
       - another-kubernetes-domain.com
     disable-cloud-controller: true
     ```

3. Rancher -> Cluster Management -> Import Existing -> Generic
   * In **Agent Environment Vars**, add `cattle-cluster-agent `: `preferredDuringSchedulingIgnoredDuringExecution`
   * Following command to let join VM.

4. Install harvester-cloud-provider from store
   ![image](https://github.com/harvester/harvester/assets/2773781/5f772f19-a578-42f5-8a1d-d80ac2d2f6e1)

5. Create nginx deployment and LB direct to it.
   ${\color{red} \text{Status should stuck at Pending.}}$
   ![image](https://github.com/harvester/harvester/assets/2773781/c1675869-ee38-4faf-8407-2bb435e18aef)
   ![image](https://github.com/harvester/harvester/assets/2773781/e71f8b6c-87f3-44a1-b150-99ca16010e96)

**Expected behavior**
Load balancer should be successfully deploy and forward to nginx deployment.

**Support bundle**
[supportbundle_lb_2024-03-12T10-42-20Z.zip](https://github.com/harvester/harvester/files/14571086/supportbundle_lb_2024-03-12T10-42-20Z.zip)

**Environment**
* Harvester
  * Version: `v1.3.0-rc4`
  * Profile: baremetal, 1 nodes (48C/128G/2T)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.8.2`
  * Profile: rancher-vcluster (1C/4G)
  * harvester-cloud-provider: `103.0.0+up0.1.14`

**Comment by starbops** [comment]
harvester-cloud-provider `103.0.1+up0.2.3` is in rancher/charts `dev-v2.8` branch but not in `release-v2.8` branch yet.

- `dev-v2.8`: https://github.com/rancher/charts/tree/dev-v2.8/assets/harvester-cloud-provider
- `release-v2.8`: https://github.com/rancher/charts/tree/release-v2.8/assets/harvester-cloud-provider

I think that's why we only have `103.0.0+up0.1.14` to choose from on the marketplace. cc @w13915984028

**Comment by starbops** [comment]
Since harvester-cloud-provider `103.0.1+up0.2.3` and `103.0.2+up0.2.4` were already there, we can verify again to see if the issue persists. Thanks. cc @albinsun

**Comment by w13915984028** [comment]
Now the latest `103.0.2+up0.2.4` is also available on `release-v2.8`.

https://github.com/rancher/charts/blob/release-v2.8/assets/harvester-cloud-provider/harvester-cloud-provider-103.0.2%2Bup0.2.4.tgz

**Comment by albinsun** [comment]
Having a quick test using `harvester-v1.3.1-rc2` + `rancher-2.8.4` + `harvester-cloud-provider-v0.2.4`.

* LB works
  ![image](https://github.com/harvester/tests/assets/2773781/22d39b80-0af2-4f1f-b5ff-d0e30755d26e)

But we observe following uncommon behavior:
1. When adding LB, no configurable IPAM field (DHCP or Pool)
   ![image](https://github.com/harvester/tests/assets/2773781/b41ffab7-1240-4c67-9db1-5bc5b7b54bd3) 
LB works
2. Implicitly use IPAM Pool by default
   ![image](https://github.com/harvester/tests/assets/2773781/b3c23108-7597-4634-88f4-d46a3addcde0)

Is this expected?

**Comment by khushboo-rancher** [comment]
@albinsun Is it about `Add-on` tab is missing and you can't set IPAM field? By default IPAM is set to pool?

**Comment by albinsun** [comment]
> @albinsun Is it about `Add-on` tab is missing and you can't set IPAM field? By default IPAM is set to pool?

Yes that's what I mean.
1. Can create LB and working but IPAM is not configurable
2. From the assigned IP it's from Pool

**Comment by starbops** [comment]
For imported existing guest clusters, the dashboard does not show the IPAM tab. We need insights from frontend developers to know what the missing bits are to show such a tab. cc @a110605 @torchiaf

With that said, I feel that this is not related to the original issue. As long as you can get a VIP from either the pool or DHCP server, the LB CR will not be stuck in the pending state. #6122 describes the tab-missing issue more accurately.

**Comment by khushboo-rancher** [comment]
Agree with @starbops, we can use another ticket to track the UI issue and close this one.

**Comment by albinsun** [comment]
Close as the original issue is resolved and will track the IPAM missing issue in harvester/harvester/issues/6122.
