### ISSUE TITLE
[BUG] `csi-snapshotter` at incorrect tag version in v1.3.0-rc4

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5346]
**Describe the bug**
In v1.3.0-rc4 Harvester:

```
kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}' | grep -ie "snapshot"
```

Yields:

```
harvester-snapshot-validation-webhook registry.k8s.io/sig-storage/snapshot-validation-webhook:v6.3.3
snapshot-controller registry.k8s.io/sig-storage/snapshot-controller:v6.3.3
csi-snapshotter longhornio/csi-snapshotter:v6.3.2
```

Where according to:
https://github.com/harvester/harvester/blob/632ec8d8981186e55f0146c547f21a5161d97a81/deploy/charts/harvester/values.yaml#L379-L385

Should be: v6.3.3

**Comment by bk201** [comment]
@irishgordo The image tag `registry.k8s.io/sig-storage/snapshot-controller:v6.3.3` in Harvester's [values.yaml file](https://github.com/harvester/harvester/blob/632ec8d8981186e55f0146c547f21a5161d97a81/deploy/charts/harvester/values.yaml#L379-L385) is for the deployment `kube-system/snapshot-controller`.



Image `longhornio/csi-snapshotter:v6.3.2` is for `csi-snapshotter` in Longhorn v1.6.0 (It's harvester's dependency chart):  https://github.com/longhorn/charts/blob/18b534061109f24b11285d2c7c276aafa7b8c4ed/charts/longhorn/values.yaml#L94

**Comment by irishgordo** [comment]
@bk201 - Oh! 
Apologies, I just noticed that :sweat_smile: 
I'll go ahead and close this out :smile:
