### ISSUE TITLE
[BUG] After upgrade Rancher v2.7.11 to 2.8.2, RKE2 cluster shows a redundant node and stuck at deleteing.

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5347]
**Describe the bug**
* Before (`v2.7.11`)
  With a Nginx deployment and LoadBalancer
![image](https://github.com/harvester/tests/assets/2773781/8fafa151-8f2e-455c-9083-9d75b03023af)

* After Upgrade to `2.8.2`
  Deployment and LB still works, but a redundant machine shows up and stuck at `Deleting`
  ![image](https://github.com/harvester/tests/assets/2773781/4a33b75b-7aef-494c-b60b-c93234789fcf)
  ![image](https://github.com/harvester/tests/assets/2773781/56c32657-d3c1-4fc5-ba09-ad318c29ead2)

**To Reproduce**
Reproduce (2/3)
1. Setup Harvester `v1.3.0-rc4`
2. Setup Rancher `v2.7.11`
3. Create RKE2 Harvester node driver cluster, say **myrke2**
4. Entering **myrke2**, create a nginx deployment and a LB for it, check both works.
5. Upgrade to `v2.8.2`
   * Follow https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/other-installation-methods/rancher-on-a-single-node-with-docker/upgrade-docker-installed-rancher
   * docker rancher log
     ```
     ...
      2024/03/12 18:32:34 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd
      2024/03/12 18:32:35 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd
      2024/03/12 18:32:35 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd
      2024/03/12 18:33:00 [ERROR] error syncing 'fleet-default/myrke22-bootstrap-template-th8n6': handler rke-bootstrap-cluster-name: an error on the server ("error trying to reach service: dial tcp 10.43.0.1:443: connect: connection refused") has prevented the request from succeeding (get nodes myrke22-pool1-86f0fbf5-nqfwj), requeuing
     ...
     ```
  

**Expected behavior**
There should only one machine in cluster, and both deployment and LB works.

**Support bundle**
[supportbundle_r2711-r282_2024-03-12T18-47-55Z.zip](https://github.com/harvester/harvester/files/14577303/supportbundle_r2711-r282_2024-03-12T18-47-55Z.zip)

[docker_rancher.log](https://github.com/harvester/harvester/files/14577304/docker_rancher.log)

**Environment**
* Harvester `v1.3.0-rc4`
  * Profile: QEMU/KVM, 3 nodes  (8C/16G/500G)
  * ui-source: `Auto`
* Rancher `v2.7.11` -> `2.8.2`
  * Profile: Docker (1C/4G)
* RKE2 `v1.27.11+rke2r1`

**Comment by albinsun** [comment]
Reproduce (1/2) in single node cluster.

**Environment**
* Harvester `v1.3.0-rc4`
  * Profile: QEMU/KVM, Single node  (16C/32G/500G)
  * ui-source: `Auto`
* Rancher `v2.7.11` -> `2.8.2`
  * Profile: Docker (1C/4G)
* RKE2 `v1.27.11+rke2r1`


### Before
myrke2-pool1-5b64888cd7xhlhj8-bbh5w / myrke2-pool1-2e0e7a4f-8knwj
![image](https://github.com/harvester/harvester/assets/2773781/8cbcffa5-c024-4ea8-b9bd-79fb2152df7d)

myrke2-pool1-7c766797ddx655hs-wwlw9 / n/a

### After
![image](https://github.com/harvester/harvester/assets/2773781/359142e0-6feb-4f76-9fd6-64ca97729049)

**Comment by albinsun** [comment]
## Reproduce based on helm installation.
### Setup v2.7.11
Single node RKE2 cluster
![image](https://github.com/harvester/harvester/assets/2773781/e120642e-7eb2-4ad6-b445-7d849980adcb)

### Trigger Upgrade to v2.8.2
![image](https://github.com/harvester/harvester/assets/2773781/722c963d-1133-417a-a79f-dac6e5d88614)
![image](https://github.com/harvester/harvester/assets/2773781/9ddec9db-d3fd-40f3-ace6-3a141aecb576)

### After Upgrade, cluster do not in-service 
![image](https://github.com/harvester/harvester/assets/2773781/3094cc9a-e735-4964-bc99-635a1e182d12)

#### Rancher logs-collector
[rancher-2024-03-14_00_16_58.tar.gz](https://github.com/harvester/harvester/files/14595051/rancher-2024-03-14_00_16_58.tar.gz)

#### rancher pod log
[rancher_pod.log](https://github.com/harvester/harvester/files/14586454/rancher_pod.log)
```
2024/03/13 10:46:34 [ERROR] error syncing 'c-m-4t6t4h5l': handler cluster-deploy: etcdserver: request timed out, requeuing
2024/03/13 10:46:34 [INFO] [planner] rkecluster fleet-default/myrke2: configuring bootstrap node(s) myrke2-pool1-6d5fc8f9d9xdc4cb-2fp7q: waiting for probes: etcd, kube-apiserver, kube-controller-manager
2024/03/13 10:46:36 [ERROR] Error during subscribe websocket: close sent
2024/03/13 10:46:41 [ERROR] error syncing 'c-m-4t6t4h5l': handler cluster-deploy: Get "https://10.43.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": dial tcp 10.43.0.1:443: connect: no route to host, requeuing
2024/03/13 10:46:41 [INFO] [planner] rkecluster fleet-default/myrke2: configuring bootstrap node(s) myrke2-pool1-6d5fc8f9d9xdc4cb-2fp7q: waiting for probes: etcd, kube-apiserver, kube-controller-manager
2024/03/13 10:46:47 [ERROR] error syncing 'c-m-4t6t4h5l': handler cluster-deploy: Get "https://10.43.0.1:443/apis/apps/v1/namespaces/cattle-system/daemonsets/cattle-node-agent": dial tcp 10.43.0.1:443: connect: no route to host, requeuing
2024/03/13 10:46:47 [INFO] [planner] rkecluster fleet-default/myrke2: configuring bootstrap node(s) myrke2-pool1-6d5fc8f9d9xdc4cb-2fp7q: waiting for probes: etcd, kube-apiserver, kube-controller-manager
W0313 10:46:54.781134      32 warnings.go:80] cluster.x-k8s.io/v1alpha3 MachineDeployment is deprecated; use cluster.x-k8s.io/v1beta1 MachineDeployment
2024/03/13 10:47:49 [ERROR] error syncing 'c-m-4t6t4h5l': handler cluster-deploy: etcdserver: request timed out, requeuing
2024/03/13 10:47:49 [INFO] [planner] rkecluster fleet-default/myrke2: configuring bootstrap node(s) myrke2-pool1-6d5fc8f9d9xdc4cb-2fp7q: waiting for probes: etcd, kube-apiserver, kube-controller-manager

```
#### Harvester (New machine is created)
[supportbundle_prime2711to282_2024-03-13T10-49-34Z.zip](https://github.com/harvester/harvester/files/14586503/supportbundle_prime2711to282_2024-03-13T10-49-34Z.zip)

![image](https://github.com/harvester/harvester/assets/2773781/50ed0c1b-c5f4-47a7-a71a-651b04024e4f)

**Comment by w13915984028** [comment]
A quick look of the first support-bundle:

**Seems something wrong at Rancher side, to be further confirmed.**


In the first support-bundle, there is such log

>2024/03/12 18:33:00 [ERROR] error syncing 'fleet-default/myrke22-bootstrap-template-th8n6': handler rke-bootstrap-cluster-name: an error on the server ("error trying to reach service: dial tcp 10.43.0.1:443: connect: connection refused") has prevented the request from succeeding (get nodes myrke22-pool1-86f0fbf5-nqfwj), requeuing
2024/03/12 18:33:00 [ERROR] error syncing 'fleet-default/myrke22-bootstrap-template-th8n6': handler rke-bootstrap-cluster-name: an error on the server ("error trying to reach service: dial tcp 10.43.0.1:443: connect: connection refused") has prevented the request from succeeding (get nodes myrke22-pool1-86f0fbf5-nqfwj), requeuing

Below log with a few repeats

>2024/03/12 18:26:04 [INFO] [planner] rkecluster fleet-default/myrke22: configuring bootstrap node(s) myrke22-pool1-68fd5df64dx9lg6q-rfhvd: waiting for plan to be applied



Final logs related to node: `...68fd5df64dx9lg6q...`, this **ERROR** looks to be critical

>2024/03/12 18:32:34 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd
2024/03/12 18:32:35 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd
2024/03/12 18:32:35 [ERROR] [rkebootstrap] fleet-default/myrke22-bootstrap-template-th8n6: cluster fleet-default/myrke22 machine fleet-default/myrke22-pool1-74d58b5579x9dkb8-f5g7p was still joined to deleting etcd machine fleet-default/myrke22-pool1-68fd5df64dx9lg6q-rfhvd


From the Harvester side, all vm, vmi, pod instaces of those 2 nodes looks to be running, no delete timestamp on vmi instance. The old VMI was not triggered to delete.

```
- apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  metadata:
    annotations:
      harvesterhci.io/sshNames: '[]'
      harvesterhci.io/waitForLeaseInterfaceNames: '[]'
      kubernetes.io/hostname: harvester-node-2
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      kubevirt.io/vm-generation: "3"
    creationTimestamp: "2024-03-12T17:41:40Z"  /////////// old node
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    - foregroundDeleteVirtualMachine
    - wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs
    generation: 27
    labels:
      harvesterhci.io/creator: docker-machine-driver-harvester
      harvesterhci.io/vmName: myrke22-pool1-86f0fbf5-nqfwj
      kubevirt.io/nodeName: harvester-node-2
      ...
- apiVersion: kubevirt.io/v1
  kind: VirtualMachineInstance
  metadata:
    annotations:
      harvesterhci.io/sshNames: '[]'
      harvesterhci.io/waitForLeaseInterfaceNames: '[]'
      kubernetes.io/hostname: harvester-node-1
      kubevirt.io/latest-observed-api-version: v1
      kubevirt.io/storage-observed-api-version: v1
      kubevirt.io/vm-generation: "2"
    creationTimestamp: "2024-03-12T18:27:07Z"  /////////// new node
    finalizers:
    - kubevirt.io/virtualMachineControllerFinalize
    - foregroundDeleteVirtualMachine
    - wrangler.cattle.io/VMIController.UnsetOwnerOfPVCs
    generation: 14
    labels:
      harvesterhci.io/creator: docker-machine-driver-harvester
      harvesterhci.io/vmName: myrke22-pool1-d4b9077a-snz8l
      kubevirt.io/nodeName: harvester-node-1
```

**Comment by ibrokethecloud** [comment]
Based on some analysis, the issue could be due to the lower version of harvester machine driver in v2.8.2.

In v2.7.11 we introduced harvester machine driver v0.6.7, which added additional fields for secureBoot, enableEFI, vgpuInfo and vmAntiAffinity. 

In v2.8.2, the harvester machine driver is still v0.6.5.

It looks like the drop in version causes updates to the HarvesterConfig, which results in dropping of two fields.  In one install we observed the following messages post upgrade

```
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103853      33 warnings.go:80] unknown field "spec.enableEfi"
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103872      33 warnings.go:80] unknown field "spec.enableSecureBoot"
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103878      33 warnings.go:80] unknown field "spec.vgpuInfo"
```

It seems like this update causes a reconcilliation of the cluster, and all nodes to be replaced.

To verify this theory, we have built a custom rancher image based off 2.8.2, which has the update machine driver image.

```
FROM registry.rancher.com/rancher/rancher:v2.8.2


ENV DOCKER_MACHINE_HARVESTER_VERSION v0.6.7


RUN curl --insecure -LO [https://releases.rancher.com/harvester-node-driver/${DOCKER_MACHINE_HARVESTER_VERSION}/docker-machine-driver-harvester-amd64.tar.gz](https://releases.rancher.com/harvester-node-driver/$%7BDOCKER_MACHINE_HARVESTER_VERSION%7D/docker-machine-driver-harvester-amd64.tar.gz) && \
    tar -xf docker-machine-driver-harvester-amd64.tar.gz -C /opt/drivers/management-state/bin && \
    cp /opt/drivers/management-state/bin/docker-machine-driver-harvester /usr/share/rancher/ui/assets/ && \
    rm docker-machine-driver-harvester-amd64.tar.gz
```

Updating to rancher chart v2.8.2 with this custom image does not cause issues during upgrade and no nodes are replaced.

**Comment by ibrokethecloud** [comment]
Based on some analysis, the issue could be due to the lower version of harvester machine driver in v2.8.2.

In v2.7.11 we introduced harvester machine driver v0.6.7, which added additional fields for secureBoot, enableEFI, vgpuInfo and vmAntiAffinity. 

In v2.8.2, the harvester machine driver is still v0.6.5.

It looks like the drop in version causes updates to the HarvesterConfig, which results in dropping of two fields.  In one install we observed the following messages post upgrade

```
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103853      33 warnings.go:80] unknown field "spec.enableEfi"
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103872      33 warnings.go:80] unknown field "spec.enableSecureBoot"
rancher-68d9db65b6-k79kl rancher W0313 23:35:14.103878      33 warnings.go:80] unknown field "spec.vgpuInfo"
```

It seems like this update causes a reconcilliation of the cluster, and all nodes to be replaced.

To verify this theory, we have built a custom rancher image based off 2.8.2, which has the update machine driver image.

```
FROM registry/rancher/rancher:v2.8.2


ENV DOCKER_MACHINE_HARVESTER_VERSION v0.6.7


RUN curl --insecure -LO [https://releases.rancher.com/harvester-node-driver/${DOCKER_MACHINE_HARVESTER_VERSION}/docker-machine-driver-harvester-amd64.tar.gz](https://releases.rancher.com/harvester-node-driver/$%7BDOCKER_MACHINE_HARVESTER_VERSION%7D/docker-machine-driver-harvester-amd64.tar.gz) && \
    tar -xf docker-machine-driver-harvester-amd64.tar.gz -C /opt/drivers/management-state/bin && \
    cp /opt/drivers/management-state/bin/docker-machine-driver-harvester /usr/share/rancher/ui/assets/ && \
    rm docker-machine-driver-harvester-amd64.tar.gz
```

Updating to rancher chart v2.8.2 with this custom image does not cause issues during upgrade and no nodes are replaced.

In addition, we have run the same test against harvester v1.2.1 and v1.2.0, where we provisioned a downstream cluster with rancher 2.7.11 and subsequently upgraded rancher to v2.8.2. The same behaviour, where nodes are replaced in the downstream cluster is observed in these setups as well.

**Comment by jakefhyde** [comment]
@ibrokethecloud Your analysis is correct, the upgrade to `v2.8.2` is essentially a downgrade of harvester. Looking at the diff https://github.com/harvester/docker-machine-driver-harvester/compare/v0.6.5...v0.6.7 I can see three new fields added. Because of the way CAPI (and by extension, Rancher) works, the infrastructure machine template is updated in place, which causes all machine deployments to do a rollout. This is because Rancher generates it's CRDs using a dynamic schema CR, which is unversioned and modified in place when the related docker machine drivers are changed. Although the spec of the dynamicSchema is populated to the machine pool on the provisioning cluster, that only catches the upgrade case. In the case of a downgrade, existing fields (even if they were at their zero values) are removed from the machine template since the dynamic schema regenerates the CRD, and thus all related CRs for the driver and modified. This causes those "unknown field" errors you are seeing. This causes the `machine-template-hash` annotation to change when computing the desired machineset, and the CAPI machine deployment controller begins by creating a new machine set and scaling it up, while scaling down the old one.

**Comment by bk201** [comment]
Thank you, @jakefhyde.

Node driver change PR https://github.com/rancher/rancher/pull/43595 is merged and supposed we should have this in Rancher 2.8.3

**Comment by FrankYang0529** [comment]
I just test upgrade from `v2.7.11` to `v2.8.3-rc4` and there is no machine replacement.

**Comment by albinsun** [comment]
Having a test on single node `harvester-v1.3.0-rc4`+`rancher-v2.7.11` upgrade to `rancher-v2.8.3-rc4`.
The RKE2 cluster looks good and no new machine was generated. :+1: 

Note that we observing a Peding deletion harvester-cloud-provider pod, but seems not affect operations.
Will test again later once `harvester-v1.3.0` release.

Thank you.

1. From `v2.7.11`
   <details>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/5ed50b1f-3cef-43f6-ba8e-dea3e5c70649)
   </details
   
2. Upgrade to `v2.8.3-rc4`
   * <details>
     <summary> :green_circle: 
       No new machine bean created
     </summary>
     ![image](https://github.com/harvester/harvester/assets/2773781/d3d33846-b5f9-4e7a-bbee-dccb6b34a672)
     </details>

   * <details>
     <summary> :green_circle: 
     Deployment and LB still works 
     </summary>
     ![image](https://github.com/harvester/harvester/assets/2773781/e0cee565-087b-4656-a525-9c665bac6b58)
     </details>
   
   * :yellow_circle: cloud-provider works, but has a `Pending` deleting pod
      `[Unschedulable] 0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..`
     ![image](https://github.com/harvester/harvester/assets/2773781/58664374-fca0-489c-88b9-3826f5952672)
     ![image](https://github.com/harvester/harvester/assets/2773781/7f91c95c-9d2e-4eb0-aca9-bbf79553a928)

**Comment by albinsun** [comment]
Provide test result on `v1.3.0`.
No more new generated nodes, thx. :+1: 
But we observe that a pending deleting harvester cloud provider pod is there, and 2 pod comes from different image source:
* `rancher/harvester-cloud-provider:v0.2.0` -> `Pending Deleteing`
* `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.0` -> `Running`


## Environment
* Harvester
  * Version: `v1.3.0`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.11` -> `v2.8.3-rc4`
  * Profile: Helm (1C/4G)


## Steps
1. Setup env. (v2.7.11)
   * <details>
     <summary> :green_circle: 
     Rancher
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a6f0d767-c42f-4e19-af74-466d86bc2106)
     </details>
     


   * <details>
     <summary> :green_circle: 
     deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6dfbfd32-13e0-418a-bb87-98df9ac13484)
     </details>
     
   * <details>
     <summary> :green_circle: 
     LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/51a6c841-af92-46e6-aa5c-c60074ffe6d1)
     </details>
     

1. Upgrade env. (v2.8.3-rc4)
   * :yellow_circle: Rancher 
     ![image](https://github.com/harvester/harvester/assets/2773781/59ee4261-9510-47cc-84b0-be7d0238dea1)
     ${\color{red} \text{0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..}}$
     ![image](https://github.com/harvester/harvester/assets/2773781/d2486c64-1738-4e15-9042-93fb2ac65728)


   * <details>
     <summary> :green_circle: 
     deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/18317f50-4b3c-463c-a3c1-2847d14f3912)
     </details>
     

     
   * <details>
     <summary> :green_circle: 
     LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/dadee14d-f807-454b-aa38-a12e990eb759)
     </details>

**Comment by albinsun** [comment]
Provide test result on Harvester `v1.3.0` with Rancher `2.8.3-rc4`. No more new generated nodes, close ticket.

But we observe that a pending deleting harvester cloud provider pod is there, and 2 pod comes from different image source:
* `rancher/harvester-cloud-provider:v0.2.0` -> `Pending Deleteing`
* `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.0` -> `Running`

Let's trace in #5382 


## Environment
* Harvester
  * Version: `v1.3.0`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.11` -> `v2.8.3-rc4`
  * Profile: Helm (1C/4G)


## Steps
1. Setup env. (v2.7.11)
   * <details>
     <summary> :green_circle: 
     Rancher
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a6f0d767-c42f-4e19-af74-466d86bc2106)
     </details>
     


   * <details>
     <summary> :green_circle: 
     deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6dfbfd32-13e0-418a-bb87-98df9ac13484)
     </details>
     
   * <details>
     <summary> :green_circle: 
     LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/51a6c841-af92-46e6-aa5c-c60074ffe6d1)
     </details>
     

1. Upgrade env. (v2.8.3-rc4)
   * :yellow_circle: Rancher 
     ![image](https://github.com/harvester/harvester/assets/2773781/59ee4261-9510-47cc-84b0-be7d0238dea1)
     ${\color{red} \text{0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..}}$
     ![image](https://github.com/harvester/harvester/assets/2773781/d2486c64-1738-4e15-9042-93fb2ac65728)


   * <details>
     <summary> :green_circle: 
     deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/18317f50-4b3c-463c-a3c1-2847d14f3912)
     </details>
     

     
   * <details>
     <summary> :green_circle: 
     LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/dadee14d-f807-454b-aa38-a12e990eb759)
     </details>
