### ISSUE TITLE
[BUG] Settings link in the Advanced/Networks menu does not work

### ISSUE THREAD

**Issue by belgaied2** [harvester/harvester#535]
**Describe the bug**
I want to define a Host Network, I click on the menu Advanced/Networks, I see `You must configure a network in Settings before creating a new network. ` which is expected, but clicking on `Settings` in the message gives a blank screen.

**To Reproduce**
1. Login to Harvester,
2. Go to menu `Advanced`, then `Networks`
3. Click on `Settings`
4. See the blank screen

**Expected behavior**
Should show the network settings.

**Log**
Javascript console shows:
```
TypeError: Cannot read property 'id' of null
    at Object.<anonymous> (type-map.js:378)
    at f.parent (Masthead.vue:166)
    at _n.get (vue.runtime.esm.js:4479)
    at _n.evaluate (vue.runtime.esm.js:4584)
    at f.parent (vue.runtime.esm.js:4836)
    at f.r (Masthead.vue?a680:1)
    at f.t._render (vue.runtime.esm.js:3548)
    at f.r (vue.runtime.esm.js:4066)
    at _n.get (vue.runtime.esm.js:4479)
    at new _n (vue.runtime.esm.js:4468)
```

**Environment:**
 - Harvester ISO version: master-85a12ff7-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Equinix

**Additional context**
This occured after installing Harvester on Equinix using a modified configuration of the iPXE setup from [this repo](https://github.com/bk201/hvst-ipxe/tree/main/equinix).

The `Settings` link that does not work shows the following link: https://<harvester-link>/#/c/local/virtual/network.harvester.cattle.io.clusternetwork/harvester-system/vlan?mode=edit.

And indeed, it looks like Harvester's API does not have a `ClusterNetwork` object but a `GlobalNetwork` object. Maybe a recent change? If yes, the UI needs to be updated.

**Comment by WuJun2016** [comment]
@belgaied2 
 The latest version has changed, please use the latest version, thank you.

**Comment by kingsd041** [comment]
Validated on v0.2.0-rc1

Steps:
1. Login to Harvester,
2. Go to menu `Advanced`, then `Networks`
3. Click on `Settings`

Result:
Will jump to the config `ClusterNetwork: vlan` page
