### ISSUE TITLE
Harvester project lacks a security policy

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#5353]
Our README.md explains how to contact us via Slack, the forum, and how to file issues on github, but it does not provide any guidance on how to file potential security issues. We should probably create an organization-wide security policy, similar to the Rancher org's https://github.com/rancher/.github/blob/main/SECURITY.md. By doing this at the org level, github will automatically add links to the security policy in all repos withing the org.

**Comment by tserong** [comment]
I've added an org-wide security policy at https://github.com/harvester/.github/blob/main/SECURITY.md, based on the Rancher org's policy.

Some notes:

- I've linked to the Rancher policy for GPG key info - this means the information isn't duplicated here, and only needs to be updated in one place if the key ever changes.
- I haven't put a link to Security Advisories, being uncertain whether I should link to https://github.com/harvester/harvester/security/advisories or https://github.com/rancher/rancher/security/advisories or both
- I left out the types of issues to report or not report, in case that wants to be different to the Rancher guidelines.

Can you please review @bk201 @markhillgit @macedogm ?

**Comment by macedogm** [comment]
@tserong thanks for working on this. Some small comments:

- In the policy - https://github.com/harvester/.github/blob/main/SECURITY.md:
  - `s/ackknowledge/acknowledge/`
  - In `This is to protect the Rancher ecosystem users and enable us to follow through our coordinated disclosure process.`, should it also mention Harvester or do we believe that with "Rancher ecosystem" it encompass everything?

About:

> I haven't put a link to Security Advisories, being uncertain whether I should link to https://github.com/harvester/harvester/security/advisories or https://github.com/rancher/rancher/security/advisories or both

You can link to both, but IMO it should be important to clarify that Harvester's CVEs are/will be released in https://github.com/harvester/harvester/security/advisories and that for CVEs in Rancher users should go to https://github.com/rancher/rancher/security/advisories.
