### ISSUE TITLE
[Doc] Disable Request Buffering for Image Upload from Multi-Cluster Management with Nginx Ingress

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#5355]
**Describe the solution you'd like**

While uploading a large image from multi-cluster management, if the cluster hosting Rancher uses nginx ingress, the `proxy_request_buffering` should be disabled, otherwise, LH backing image will encounter the [upload POST timeout](https://github.com/longhorn/backing-image-manager/blob/e07c2782a60c889bb435cc472353ee700c9b3b67/pkg/datasource/service.go#L163-L173).

Although this is specific to the cluster running Rancher, we could have a document update about how to workaround this.

**Comment by innobead** [comment]
> While uploading a large image from multi-cluster management, if

Does this mean uploading images through Rancher UI proxy?

**Comment by WebberHuang1118** [comment]
> > While uploading a large image from multi-cluster management, if
> 
> Does this mean uploading images through Rancher UI proxy?

Yes, through the ingress on the cluster that is hosting Rancher.

**Comment by WebberHuang1118** [comment]
Close as https://github.com/harvester/docs/pull/550 is merged, thanks.
