### ISSUE TITLE
Volume marked as " Not Ready " 

### ISSUE THREAD

**Issue by AminGR** [harvester/harvester#5362]
I have a data disk about 2,5T which was attached to a vm as volume.
Two days ago I detached it to move it to another vm and since then its marked as 
![image](https://github.com/harvester/harvester/assets/33826995/72a1b11d-0d10-4743-a0cc-0ee19b400fea)
" Not Ready ".
Does anyone have had such an experience? or any rough estimation about how long does it take ?

Thanks for your replies in advance.

**Comment by Vicente-Cheng** [comment]
Hi @AminGR, sorry for the late update.

Is this case still there?
If yes, could you try to check the status on the Longhorn page?
(how to go to longhorn page -> https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#access-embedded-rancher-and-longhorn-dashboards)

Thanks!
