### ISSUE TITLE
[BUG] unable to enter maintenance mode on last node of 2 nodes cluster

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#5365]
### Describe the bug
The node would be cordoned but not updated to maintenance and no further message displayed.

### To Reproduce
1. Install Harvester with 2 nodes
2. Enable maintenance mode on the last node

### Expected behavior
The node should entered maintenance mode.

## Environment:
 - Harvester ISO version: **v1.3-2c8332b7-head** (after `v1.3.0-rc4`)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **MegaRAC SP-X 2 nodes** (arm-based)
 - **ui-source** Option: **Auto**

### Additional context
link to #371

**Comment by ibrokethecloud** [comment]
unable to currently reproduce the error on 1.3.0

**Comment by ibrokethecloud** [comment]
during my testing, this error cannot be reproduced on arm nodes.

based on my chat with @lanfon72 there seems to be a small discrepancy in how the test is run.

the UI makes a set of api calls:
* `endpoint/harvester/nodes/${node}?action=maintenancePossible`, which checks if maintenance is currently possible on the node
* `endpoint/harvester/nodes/${node}?action=listUnhealthyVM`, which checks if there are any VMs running in the cluster which may have their last healthy replica on node being targeted for maintenance
* `endpoint/harvester/nodes/${node}?action=enableMaintenanceMode`, places the node in maintenance when first two calls are successful.

It seems the testing is skipping the first two calls and only running `action=enableMaintenanceMode`, which seems to attempt and place the single controlplane node into maintenance mode which is not possible in a 2 node cluster. The controller subsequently skips the controlplane node but it floods the logs with messages while retrying to reconcile the node.

We should either change the set of api calls during the tests or update the api calls to move `isMaintenancePossible` and `listUnhealthyVM` in the `enableMaintenanceMode` action.

**Comment by lanfon72** [comment]
We can add those 2 API calls in our tests, but as those API endpoint are new added in `v1.2.0`[^1], I thought we should still consider that check `maintenancePossible` while user calling `enableMaintenanceMode` directly.  (to prevent some users using automation to control nodes and didn't aware the change.)


This bug would only happened on 2 nodes environment, so severity could be more lower. (as we don't suggest users to use Harvester with only 2 nodes)

cc @bk201 

[^1]: https://github.com/harvester/harvester/issues/2723

**Comment by albinsun** [comment]
FYI, looks fine in `harvester-v1.3.1-rc2`

## Environment
* **harvester-`v1.3.1-rc2`**
  * Profile: 2 nodes, aarch64, 32C/64G/1T per node
  * ui-source: `Auto`

## Step
1. Enter maintenance mode
   ![image](https://github.com/harvester/harvester/assets/2773781/f46ea385-694f-4be2-b2c2-64db773ebef4)

1. Disable maintenance mode
   ![image](https://github.com/harvester/harvester/assets/2773781/02c74be7-d876-413f-bc3f-9fa5ee426cb3)

**Comment by lanfon72** [comment]
> FYI, looks fine in `harvester-v1.3.1-rc2`


To reproduce this bug, you need to enable maintenance mode on first node (via API calls), then the node will have the annotation `harvesterhci.io/drain-requested: "true"` to block 2nd node.

**Comment by ibrokethecloud** [comment]
@mergifyio backport v1.3

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/65322dbb-ddfb-49ad-92bc-22eb26f263bf)


Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.4-63a0567-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with 2 nodes
2. Enable maintenance mode on the first node
3. First node should not have annotation `harvesterhci.io/drain-requested: "true"`[^1]

[^1]: https://github.com/harvester/harvester/issues/5365#issuecomment-2163456172
