### ISSUE TITLE
[Question]Virtual machine IO failure causing inability to connect

### ISSUE THREAD

**Issue by wangch1030** [harvester/harvester#5376]
Dear Harvester developers.
During use, we encountered some issues.our environment is Harvester 1.2.1.
Deploy the master and Harbor of k8s on two virtual machines within Harvester 1.2.1, while running some test applications on the master node. After running for a period of time, the virtual machine fails to connect.
By logging into the Harvester backend to view the virtual machine status, the INFO prompt is _task docked: XXX blocked for more than 120 seconds._
![image](https://github.com/harvester/harvester/assets/144816721/0e6b8c0e-ab90-4c32-ac8d-dc33c7b49cf5)
1. We suspect that it is related to high IO and create a testing environment for it. We attempted to replicate the phenomenon through a single node, but it was not successful. We inferred that the IO pressure was insufficient, and plan to add two k8s nodes because synchronization between ETCD will generate IO, as well as push/pull operations on the Harbor.
2. We suspect that it is related to the guest agent calling guest free. In the message log of the virtual machine, we found that the last log that the virtual machine tampered with was Qemu ga [1138]: info: guest free called.
In the virtual machine, the qemu-guest agent called guest-fsfreeze to freeze the file system. In some backups, the guest agent does not follow the freezing order.
![image](https://github.com/harvester/harvester/assets/144816721/15fc889c-47d3-4bf5-b898-c9579a08a6e6)
We found a post about guest free causing system lag: _https://gitlab.com/qemu-project/qemu/-/issues/520_, but there is no answer as to why Harvester 1.2.1 calls guest free.
The above is our speculation, and we look forward to your help to clarify it.

**Comment by Yu-Jack** [comment]
Hi @wangch1030, could you provide the support bundle file by following this tutor https://docs.harvesterhci.io/v1.2/troubleshooting/harvester#generate-a-support-bundle? And are there same virtual machine acted like this issue?
