### ISSUE TITLE
[BUG] Need to strip whitespace from image URLs before download

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#5378]
**Describe the bug**
When creating an image from a URL, if the URL contains leading or trailing whitespace, the image will fail to download due to either URL parsing errors or 404 errors:

![image](https://github.com/harvester/harvester/assets/754700/1a32979f-eeb5-4fd4-9b40-45d8ffdf98a7)

This could be avoided by trimming leading and trailing whitespace from the URL field.

**To Reproduce**
1. Go to Images and click Create
2. Enter a URL with either leading or trailing whitespace (e.g. " http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img" or "http://download.cirros-cloud.net/0.6.2/cirros-0.6.2-x86_64-disk.img ", but without the quotes)
3. Click Create
4. Back on the Images screen, observe that the image fails to download with one of the above errors.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized

**Additional context**
Originally reported at https://rancher-users.slack.com/archives/C01GKHKAG0K/p1710636810766079

**Comment by irishgordo** [comment]
@torchiaf  thanks for this fix :+1: :smile:  - this looks great on Harvester Version: v1.4.0-dev-20240705 

I'll go ahead and close this out :smile: 

![Screenshot from 2024-07-08 20-37-48](https://github.com/harvester/harvester/assets/5370752/ebeb61ae-42c0-48f3-aab9-0728aa7e3373)
![Screenshot from 2024-07-08 20-37-17](https://github.com/harvester/harvester/assets/5370752/3ed9e9a5-8ec0-442e-8c76-329c5ada7423)
