### ISSUE TITLE
[Question]Unable to modify installation media during installation process

### ISSUE THREAD

**Issue by charnet1019** [harvester/harvester#5379]
I can not modify installation media during install process。Pressing the left and right keys has no response.

ENV: 
Dell R740 Intel(R) Xeon(R) Silver 4114 CPU
BIOS Version: 2.12.2
Lifecycle Controller Fireware: 3.21.21.21
Harvester Version: 1.3.0

![image](https://github.com/harvester/harvester/assets/18616254/9897245b-7bec-44cb-96f0-5b0f0fc97432)

**Comment by Yu-Jack** [comment]
@charnet1019 could you try tab key? It should work.

**Comment by charnet1019** [comment]
Yes, time is worked. Thanks发自我的手机-------- 原始邮件 --------发件人： Jack Yu ***@***.***>日期： 2024年3月18日周一 14:42收件人： harvester/harvester ***@***.***>抄送： charnet1019 ***@***.***>, Mention ***@***.***>主    题： Re: [harvester/harvester] [Question]Unable to modify installation media during installation process (Issue #5379)
@charnet1019 could you try tab key? It should work.

**Comment by Yu-Jack** [comment]
I close this issue since it works, feel free to reopen it or file a new issue if you have question.
