### ISSUE TITLE
[BUG] Users are allowed to create networks when an invalid physical NIC has been configured.

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#538]
**Describe the bug**
Users are allowed to create networks when an invalid physical NIC has been configured.

**To Reproduce**
1. Go to the VLAN edit page
2. Enable the default physical nic and set it to 1, then save

**Result**
Even though an invalid physical nic is configured, users are still allowed to create networks. By the way, the error message seems a little not friendly.
![image](https://user-images.githubusercontent.com/57614736/111757035-d9e4e380-88d5-11eb-92eb-dd7a25648b55.png)

**Expected**
If the physical nic is invalid, users should not be able to create networks

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by yaocw2020** [comment]
![image](https://user-images.githubusercontent.com/7421463/115986967-87d66280-a5e5-11eb-8675-046593efa921.png)

validated on master-head
