### ISSUE TITLE
[BUG] A pending fail pod from different hub is generated after upgrade rancher

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5382]
**Describe the bug**
Based on harvester `v1.3.0`, by performing a Rancher upgrade form  v2.7.11 to v2.8.3-rc4, we found that a new generated pod is stuck in pending fail. 

Note that new one comes from a different image `rancher/harvester-cloud-provider:v0.2.0` compare to the running one `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.0`
![image](https://github.com/harvester/harvester/assets/2773781/62e6a94d-37eb-41a8-916c-a1947e8d568a)

**To Reproduce**
1. Setup RKE2 cluster based on Harvester `v1.3.0` + Rancher `v2.7.11`
   * <details>
     <summary> :green_circle: 
     Create RKE2 cluster 
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/a6f0d767-c42f-4e19-af74-466d86bc2106)
     </details>
     
   * <details>
     <summary> :green_circle: 
     Check deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/6dfbfd32-13e0-418a-bb87-98df9ac13484)
     </details>
     
   * <details>
     <summary> :green_circle: 
     Check LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/51a6c841-af92-46e6-aa5c-c60074ffe6d1)
     </details>
     

1. Upgrade Rancher to `v2.8.3-rc4`
   * <details>
     <summary> :green_circle: 
       Cluster is Active
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/59ee4261-9510-47cc-84b0-be7d0238dea1)
     </details>
 
   * <details open>
     <summary> :red_circle: 
     Apps are in health 
     </summary>
     
     ${\color{red} \text{0/1 nodes are available: 1 node(s) didn't match pod anti-affinity rules. preemption: 0/1 nodes are available: 1 No preemption victims found for incoming pod..}}$
     ![image](https://github.com/harvester/harvester/assets/2773781/d2486c64-1738-4e15-9042-93fb2ac65728)
     </details>

   * <details>
     <summary> :green_circle: 
     Check deployment with pvc
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/18317f50-4b3c-463c-a3c1-2847d14f3912)
     </details>
     
   * <details>
     <summary> :green_circle: 
     Check LB
     </summary>

     ![image](https://github.com/harvester/harvester/assets/2773781/dadee14d-f807-454b-aa38-a12e990eb759)
     </details>

**Expected behavior**
**harvester-cloud-provider** should be in health after upgrade

**Support bundle**
1. Harvester: [supportbundle_cloudproviderhub_2024-03-18T06-38-10Z.zip](https://github.com/harvester/harvester/files/14631994/supportbundle_cloudproviderhub_2024-03-18T06-38-10Z.zip)
2. Rancher: [rancher-2024-03-18_06_41_29.tar.gz](https://github.com/harvester/harvester/files/14632037/rancher-2024-03-18_06_41_29.tar.gz)

**Environment**
* Harvester
  * Version: `v1.3.0`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.11` -> `v2.8.3-rc4`
  * Profile: Helm (1C/4G)

**Comment by albinsun** [comment]
FYI, hit similiar issue during `v1.2.1` but with opposite image source
* Old pod (`Running`): `rancher/harvester-cloud-provider:v0.2.0`
* New pod (`Pending`): `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.0`

Context (Rancher Community -> Prime)
1. `harvester-v1.2.1` + `rancher-v2.7.10`
2. Upgrade Rancher to `v2.7.11` (Prime)

![image](https://github.com/harvester/harvester/assets/2773781/57574063-f1b7-4f50-82e8-8b9bcf290f14)

![image](https://github.com/harvester/harvester/assets/2773781/d9569e32-4c56-4072-a0ba-5777a5fa5387)

**Comment by albinsun** [comment]
### Workaround
> [!NOTE]
> Delete the old pod and let the rolling update continue.

![image](https://github.com/harvester/harvester/assets/2773781/ff94e92e-4d9b-4322-90e3-02f5377f7c5b)

**Comment by bk201** [comment]
cc @starbops, we need to backport https://github.com/harvester/charts/pull/239 to the release branch to fix this problem.

**Comment by albinsun** [comment]
Test basically fine using Rancher marketplace to update **harvester-cloud-provider**.

Per discussed with @starbops, there are mainly 2 paths for **harvester-cloud-provider** chart
1. Rancher Marketplace
2. RKE2 self-contained

This ticket fix 1) but user may still hit via 2), no sure if we can inform RKE2 to use latest **harvester-cloud-provider** when they release or some other cross-team integrations?

cc. @bk201 and @FrankYang0529 


## Environment
* _harvester-v1.4.0-rc2_
  * Profile: Single node QEMU/KVM (amd64)
  * ui-source: `Auto`
* `rancher-v2.8.8` => `rancher-v2.9.3-alpha6`
  * Profile: Helm (_v1.30.5+k3s1_) on QEMU/KVM (amd64)
  * _cert-manager-v1.5.1_ 
* Guest Cluster
  * Profile: Single node _v1.27.16+rke2r2_
  * Image: _ubuntu-22.04-server-cloudimg-amd64.img_


## Test Case
### :green_circle: Upgrade harvester-cloud-provider via Marketplace
1. <details>
   <summary> Import Harvester to <i>rancher-v2.8.8</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/37828990-7501-4920-bce7-48eae85884d2)
   </details>

1. <details>
   <summary> Create <i>v1.28.13+rke2r1</i> cluster
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4a57e9eb-fd87-420e-a32d-6ab12eb5c4f1)
   </details>

1. <details>
   <summary> Check <b>harvester-cloud-provider</b> app version less than <i>v0.2.5</i>
   </summary>
   
   * `harvester-cloud-provider-v0.2.4`
     ![image](https://github.com/user-attachments/assets/a0a45e5f-9706-43d2-a8ba-0e6ecf55c644)
   </details>


1. <details>
   <summary> Upgrade <b>harvester-cloud-provider</b> to <i>v0.2.5+</i>
   </summary>
   
   * Upgrade to `103.0.3-up0.2.6`
     ![image](https://github.com/user-attachments/assets/9d9e89ec-621b-4db6-8835-ecd120251559)
     ![image](https://github.com/user-attachments/assets/9cac5698-b75d-4165-9596-9b9902863e7d)
   </details>

1. <details>
   <summary> Should NOT have pending fail <b>harvester-cloud-provider</b> pod
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5676b505-e10d-4d25-87ae-a3787c21a775)
   </details>


### :yellow_circle: harvester-cloud-provider may rollout when upgrade Rancher
1. <details>
   <summary> Import Harvester to <i>rancher-v2.8.8</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7f408a94-9010-43aa-a3b0-e0a8625f02a2)
   </details>

1. <details>
   <summary> Create <i>v1.27.16 +rke2r2</i> cluster
   </summary>
   
   ![image](https://github.com/user-attachments/assets/514de86f-dc05-4d31-a510-80486357bc14)
   </details>

1. <details>
   <summary> Check <b>harvester-cloud-provider</b> version less than <i>v0.2.5</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f7e58ff2-f9f7-472c-8bd5-3c833bab357c)
   </details>

1. <details>
   <summary> Deploy Nginx w/ PVC
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e66e61bd-63a7-406d-9d32-6597bdd26b28)
   </details>

1. <details>
   <summary> Upgrade Rancher to <i>v2.9.3-alpha5</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/39dfcbbc-d0d0-49b9-ab62-e0d29bcccbf7)
   </details>

1. <details open>
   <summary> Check <b>harvester-cloud-provider</b> is <i>v0.2.5+</i>
   </summary>
   
   * :warning: `rancher-v2.9.3-alpha5` still use 0.2.4 by default.
     ![image](https://github.com/user-attachments/assets/03a02b3a-ea0d-4a15-8d87-db928e66b5bf)
   * Manually upgrade to v0.2.6
     ![image](https://github.com/user-attachments/assets/5409b14e-1da6-43a5-a507-b7ecbaf9d9e1)
     ![image](https://github.com/user-attachments/assets/2ef2d99a-56ca-4632-8940-f0c930a7ec7e)
   </details>

**Comment by starbops** [comment]
I noticed that the harvester-cloud-provider's image changed from `registry.rancher.com/rancher/harvester-cloud-provider:v0.2.1` to `rancher/harvester-cloud-provider:v0.2.1`. That's the reason why the deployment was rolled out during the Rancher upgrade, but I'm unsure what caused the difference.
