### ISSUE TITLE
[Question] Is it garbled code?

### ISSUE THREAD

**Issue by charnet1019** [harvester/harvester#5384]
Is it garbled code?

Harvester Version: 1.3.0

![image](https://github.com/harvester/harvester/assets/18616254/ea98d692-5844-4dbe-940c-ee8449b6f82a)

**Comment by Yu-Jack** [comment]
It seems GUI bug. It's normal when you change EN to CN, but it doesn't show proper words when you refresh page in CN mode.

#### Normal 

https://github.com/harvester/harvester/assets/6960289/d1e779de-6cd4-4d20-ac9a-bfabccfbbd6c

#### Bug

https://github.com/harvester/harvester/assets/6960289/c886512c-638d-414e-a3c9-b28950ec47d8

**Comment by bk201** [comment]
@charnet1019 Thanks for the feedback, simplified Chinese is not maintained anymore. Please switch to English for now.
