### ISSUE TITLE
[BUG] The error message should be dismissed if the physical NIC has been corrected from an invalid one

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#539]
**Describe the bug**

**To Reproduce**
1. Go to the VLAN edit page
2. Enable the default physical nic and set it to 1, then save
3. Edit the default physical nic, and set it to eth0, which is fetched from one of the cluster hosts.

**Result**
Even though the physical nic has been corrected, the error message displays on the networks page all the time
![image](https://user-images.githubusercontent.com/57614736/111761132-83c66f00-88da-11eb-818f-f755e4506165.png)
![image](https://user-images.githubusercontent.com/57614736/111761187-93de4e80-88da-11eb-9c36-5f1174123225.png)

**Expected**
The error message should be dismissed after the physical nic has been corrected.

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by WuJun2016** [comment]
@DoNotSayYes   The modification of the defailtPhysicalNIC attribute will not affect the existing nodeNetwork crd object, so it is correct that the error message did not disappear

**Comment by gitlawr** [comment]
~~We shouldn't show errors if the configurations are correct. It needs to be fixed in the backend in this case~~
Nevermind, I get what @WuJun2016 means. I think current info telling the default applies to new nodes make sense
