### ISSUE TITLE
[Doc] New param skipchecks is not fully documented

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5392]
**Is your doc request related to a problem? Please describe or add related issue ID.**

New configuration param `skipchecks` is mentioned in https://docs.harvesterhci.io/v1.3/install/pxe-boot-install via https://github.com/harvester/docs/pull/501, but not in https://docs.harvesterhci.io/v1.3/install/harvester-configuration.

```
	Automatic           bool    `json:"automatic,omitempty"`
	SkipChecks          bool    `json:"skipchecks,omitempty"`
```

https://docs.harvesterhci.io/v1.3/install/pxe-boot-install#harvesterinstallskipcheckstrue

The `harvester.install.skipchecks` is described as a kernel param; meanwhile, configure it in `harvester-configuration` file (config-create.yaml below) seems to have the same effect.

>kernel harvester-<version>-vmlinuz initrd=harvester-<version>-initrd ip=dhcp net.ifnames=1 rd.cos.disable rd.noverifyssl console=tty1 root=live:http://10.100.0.10/harvester/rootfs.squashfs harvester.install.automatic=true harvester.install.config_url=http://10.100.0.10/harvester/config-create.yaml

Such snapshot was taken, it means the configuration file was fetched at first, then the preflight messages were shown. The configuration file will have chance to rule.
![image](https://github.com/harvester/harvester/assets/31133476/8efa2638-a54e-4741-9dfe-7552e8b52132)

**Describe the solution you'd like**

Update document.
(1) The https://docs.harvesterhci.io/v1.3/install/harvester-configuration should include all supported configuration params.
(2) Configure the `skipchecks` in the configuration file is also an option. (To be double confirmed by @tserong )

**Comment by tserong** [comment]
Updated docs are now published.
