### ISSUE TITLE
Issues Freeing Up Disk Space on Harvester Nodes Using harv-purge-images.sh

### ISSUE THREAD

**Issue by BringerOD** [harvester/harvester#5394]
Hello,

I'm currently managing a Harvester HCI environment and have encountered issues with disk space across my 4 Harvester nodes. In an effort to free up disk space, I attempted to use the `harv-purge-images.sh` script to purge old images from the nodes.

### Steps Taken
I followed the steps below to run the image purge script:

```bash
ssh rancher@<ip>
sudo -i

# Download the harv-purge-images.sh script
curl -sLf https://github.com/harvester/upgrade-helpers/blob/d490e51c76b107c8d5df2df71d0e9b7000b392d6/bin/harv-purge-images.sh -o harv-purge-images.sh
chmod +x harv-purge-images.sh

# Attempt to run the script
./harv-purge-images.sh v1.1.2 v1.2.1
```

### Encountered Error
However, I encountered the following error messages:

```
cat: '""/image_list_diff.txt': No such file or directory
./harv-purge-images.sh: line 1: payload:allShortcutsEnabled:false: command not found
```

### Additional Context
- **Harvester Version**: I recently upgraded to Harvester v1.2.1, but I'm uncertain of the previous version from which I upgraded.
- **Disk Space Usage**:
  - The partition `/dev/nvme0n1p5` is currently at `76%` usage (71G used out of 98G).
  - The majority of the space is consumed by directories within `/usr/local/.state`, especially related to `rke2` and containerd data (snapshots and blobs).

![image](https://github.com/harvester/harvester/assets/7971305/64249d61-7d47-42c9-9a49-6f5463bf30ad)

[Support Bundle](https://www.dropbox.com/scl/fi/75s0kaj7blhkbbcetwcwq/supportbundle_11d5cdae-5a2a-4436-b159-0af35d0605e5_2024-03-18T22-48-31Z.zip?rlkey=ra3yc6x4zct8tkj933bfpn13b&dl=0)

### Request for Guidance
I'm looking for advice on how to successfully free up space using the script or any other recommended methods. Specifically, I'm not sure how to address the script errors or alternative approaches to manage disk space effectively.

Any assistance or guidance on this matter would be greatly appreciated. Thank you in advance for your help!

**Comment by starbops** [comment]
Hi @BringerOD! Could you try this URL instead: `https://raw.githubusercontent.com/harvester/upgrade-helpers/main/bin/harv-purge-images.sh`

Thank you.

**Comment by BringerOD** [comment]
That worked.  Thanks!

**Comment by BringerOD** [comment]
That worked!  Thanks
