### ISSUE TITLE
[Question]  uploading images to harvester

### ISSUE THREAD

**Issue by AlexNicot** [harvester/harvester#5395]
when I upload an image via terraform and the name is too long (once the namespace has been added to it). harvester renames the image so it complies with the name scheme, however  I have noticed that the storageclass that goes with the image does not reference this new image name and so when I go to provision a vm the pvc will complain that the storageclass does not have the backing image.

what am I doing wrong I cant belive this is a bug as someone else would of surely encountered it ? 

I am running harvester 1.2.1

as an example:

I upload an image with the name ubuntu-24-04-20240312-abcd to the production-k8s namespace

production-k8s-ubuntu-24-04-20240312-abcd is too long so it gets renamed to say production-k8s-ubuntu-24-04008

 if I spin up a vm in tf and supply production-k8s-ubuntu-24-04008 i get image does not exist, if I do ubuntu-24-04-20240312-abcd the vm will get stuck with the pvc saying the storageclass for the image has no backing image called ubuntu-24-04-20240312-abcd I look at the storageclass and it has a backing image called production-k8s-ubuntu-24-04008.
 
 apologies if its confusing but the summery is that there seems to be some kind of disconnect with the name changes or I am supplying the wrong information ?
 
 
 also I am right in thinking you have to have the image uploaded to the same namespace you want to provision a vm in ?

**Comment by Yu-Jack** [comment]
Hi @AlexNicot , could you provide the terraform code and which terraform-provider-harvester version you use? thanks!

**Comment by WebberHuang1118** [comment]
Hi @AlexNicot,

I think you encountered a known issue https://github.com/harvester/harvester/issues/4520, 
which has already been addressed on Harvester v1.3.0 and will be included for Harvester v1.2.2, too.

**Comment by Yu-Jack** [comment]
I tested it on v1.3.0, it works well.

**Comment by tl-alex-nicot** [comment]
@WebberHuang1118 thats exactly it thanks for sharing it
