### ISSUE TITLE
[Question] harvester v1.3.0-arm64 got stuck on the ARM Kunpeng server

### ISSUE THREAD

**Issue by feng-prince** [harvester/harvester#5405]
I installed Harvester v1.3.0-arm64.iso on the ARM Kunpeng server and kept getting stuck on this interface. Does anyone know how to solve this problem?
![28542ec1c80985e298044edc42cbc84](https://github.com/harvester/harvester/assets/164117011/9dfa151b-a8ae-4f10-b3a5-a655fbb1d794)
![Uploading 微信图片_20240320101511.png…]()

**Comment by bk201** [comment]
Hi, can you post the output of:

```
cat /sys/class/tty/console/active
```

Thanks.

**Comment by ibrokethecloud** [comment]
is this serial console? or tty1?

**Comment by NonoMoh** [comment]
![SPCR](https://github.com/harvester/harvester/assets/52237475/3846fe39-6498-4d2f-a941-db62b7e3eaaa)
close BIOS SPCR
