### ISSUE TITLE
[ENHANCEMENT] Prohibit users from resizing volume when vm is stopping.

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5407]
**Is your enhancement related to a problem? Please describe.**

Currently, this PR https://github.com/harvester/harvester/pull/4794 solution doesn't fix the problem which users could resize the volume when vm is stopping.

When we stop vm from kubevirt, its `RunStrategy` and `PrintableStatus` will be like this:

- RunStrategy: RerunOnFailure, , PrintableStatus: Running
- RunStrategy: Halted, , PrintableStatus: Running
- RunStrategy: Halted, PrintableStatus: Stopping
- VMI still exists
- **At this moment, it takes some time to stop vm, so users could edit vm config to resize volume.**
- RunStrategy: Halted, PrintableStatus: Stopped
- VMI is gone

**Describe the solution you'd like**

We should change condition order, move `PrintableStatus != Stopped` to first one.

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Test PASS on `harvester-v1.4.0-dev-20240830`.


### Environment
* `harvester-v1.4.0-dev-20240830`
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: `Auto`


### Prerequisite
1. <details>
   <summary> Fresh install harvester with any nodes
   </summary>
  
   ![image](https://github.com/user-attachments/assets/520d6ede-c6d8-4c81-a924-b8f0696c192b)
   </details>

1. <details>
   <summary> Create a VM, check <code>Running</code>.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c1bfc167-8605-4bff-9fe4-18c258fc2a9e)
   </details>


### Steps 
1. <details>
   <summary> VM => ⋮ => Edit Config, should NOT be able to resize. :heavy_check_mark: 
   </summary>

   ![image](https://github.com/user-attachments/assets/6651b67e-bead-4a37-845a-e17b7e666fbb)
   </details>

1. <details>
   <summary> Stop VM => ⋮ => Edit Config when <code>Stopping</code>, should NOT be able to resize. :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/998394dd-4fbd-472f-9fab-44b4349e32be)
   </details>

1. <details>
   <summary> Check VM <code>Stopped</code> => ⋮ => Edit Config, should be able to resize. :heavy_check_mark: 
   </summary>
  
   * Resizing
     ![image](https://github.com/user-attachments/assets/10858975-022e-4322-b802-654acb77203b)
   * Ready
     ![image](https://github.com/user-attachments/assets/e75f2e78-53e5-4f44-8514-626c85b25b26)
   </details>

1. <details>
   <summary> Start VM, check <code>Running</code> and disk do resized. :heavy_check_mark: 
   </summary>
  
   * VM `Running`
     ![image](https://github.com/user-attachments/assets/60b63d47-e531-4396-b35f-2f5b310fa8a2)
   * Volume do resized
     ![image](https://github.com/user-attachments/assets/b1e43fb7-9139-4049-bf66-7393e168db90)
   </details>


### Note
1. harvester/harvester/pull/5409


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
