### ISSUE TITLE
[ENHANCEMENT][v1.2.2] Bump rancher-monitoring and rancher-logging version

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#5412]
**Is your enhancement related to a problem? Please describe.**

To solve https://github.com/harvester/security/issues/46

The `rancher-monitoring` and `rancher-logging` version should also be bumped as what have already been done in v1.3.0:

#4940 
#4941

https://github.com/harvester/harvester-installer/pull/658
https://github.com/harvester/harvester-installer/pull/657

In Harvester v1.2.2, the related upstream versions are:

```
RKE2_VERSION="v1.26.13+rke2r1"
RANCHER_VERSION="v2.8.2"
```

**Describe the solution you'd like**

Bump rancher-monitoring and rancher-logging version

**Describe alternatives you've considered**

**Additional context**

This is a manual backport of https://github.com/harvester/harvester-installer/pull/657, https://github.com/harvester/harvester-installer/pull/658 to solve https://github.com/harvester/security/issues/46

**Comment by w13915984028** [comment]
Note another issue:
https://github.com/harvester/harvester/issues/5442
https://github.com/harvester/harvester/issues/5499
And related PR:
https://github.com/harvester/harvester-installer/pull/693

**Comment by albinsun** [comment]
Provide test results for new installation (`v1.2.2-dev-20240329`) and upgrade (`v1.2.1` -> `v1.2-f414942f-head`) case.

Tests looks fine in new installation but we found **eventrouter** is `v0.1.1` instead of expected `v0.1.2` in the upgrade case.
Please help to check.


## Environment
* Harvester
  * Profile: QEMU/KVM, 8C/16G/500G per node
  * ui-source: `Auto`


## Test Cases
### New Installation (3 nodes, `v1.2.2-dev-20240329`)
1. Setup harvester `v1.2.2-dev-20240329`
   * <details>
     <summary> Enable <b>rancher-monitoring</b> and <b>rancher-logging</b> addons
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/b5429de6-9789-4376-95b2-336d07e0ccbe)
     </details>

1. Check charts are properly deployed/running
   * <details>
     <summary> :green_circle: <b>rancher-monitoring</b> should be <code>103.0.3+up45.31.1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a8399b19-5d24-4f33-aae1-3e3e28a7a88b)
     Chart
     ![image](https://github.com/harvester/harvester/assets/2773781/8478f6aa-fe72-4fe4-9d08-635c05316437)
     Pod
     ![image](https://github.com/harvester/harvester/assets/2773781/cbea1a77-8060-4ae8-9947-2a751c982b7d)
     </details>

   * <details> 
     <summary> :green_circle: <b>rancher-logging</b> should be <code>103.0.0+up3.17.10</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/18eaf6b6-e948-418d-8051-26fb62f7af77)
     Chart
     ![image](https://github.com/harvester/harvester/assets/2773781/fbaf2530-17a2-4819-a2a1-99eb9a4fc695)
     Pod
     ![image](https://github.com/harvester/harvester/assets/2773781/1699134e-c99e-4a83-a523-e62adfe4576e)
     </details>

   * <details>
     <summary> :green_circle: <b>harvester-eventrouter</b> should be <code>v0.1.2</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/942bf837-d7ec-42ea-a93d-bb6e2cbc4eaa)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle: via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/7072c6e0-532b-4f09-9239-6b940e0bca19)
     ![image](https://github.com/harvester/harvester/assets/2773781/85796102-a802-4ab9-abb1-79cf84859d0a)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/707ddc15-e5ce-4641-b465-666e5811bdf2)
     ![image](https://github.com/harvester/harvester/assets/2773781/6d44e865-b152-4c5a-8178-be767b7ab8df)
     </details>


### Upgrade from `v1.2.1` to `v1.2-f414942f-head` (Single node)
1. Setup harvester `v1.2.1`
   * <details>
     <summary> Enable <b>rancher-monitoring</b> and <b>rancher-logging</b> addons
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/5bb288d6-8330-4d87-a54a-642e2ab8b529)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle: via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/a5bde71f-d035-4c8f-bc4f-d2c3c5669f1a)
     
     Login
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/02c5763d-f631-414f-8ef2-f0a01943f763)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b3b1194d-53aa-44e2-9479-14d4bd15d5a6)

     Login
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/ee9679c1-1487-4591-9783-8d4c74eb0dfe)
     </details>


1. <details>
   <summary> Upgrade to <code>v1.2-f414942f-head</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/6a912cd0-d850-41d2-aff2-533654bbe204)
   </details>

1. Check charts version and status
   * <details>
     <summary> :green_circle: <b>rancher-monitoring</b> is <code>103.0.3+up45.31.1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b4fb9a7c-3ab3-45fb-9678-1adb14ff1f2e)
     ![image](https://github.com/harvester/harvester/assets/2773781/f17ef6f9-6a05-44da-a9c8-63ce8637d177)
     </details>

   * <details> 
     <summary> :green_circle: <b>rancher-logging</b> should be <code>103.0.0+up3.17.10</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/b9b6ff98-6b31-4ac8-829d-640c027d6fb6)
     ![image](https://github.com/harvester/harvester/assets/2773781/cc71fb08-a4fe-47c7-b51b-0b6408270408)
     </details>

   * <details open>
     <summary> :red_circle: <b>harvester-eventrouter</b> should be <code>v0.1.2</code> ${\color{red} \text{Got v0.1.1}}$
     </summary>
     
     Ref.
       1. https://github.com/harvester/harvester-installer/blob/v1.2/pkg/config/templates/rancherd-22-addons.yaml#L94
       2. https://github.com/harvester/harvester-installer/blob/v1.2/scripts/images/harvester-additional-images.txt#L2

     ![image](https://github.com/harvester/harvester/assets/2773781/d7d7aa84-aba4-4a89-9723-35c0cd8131bb)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle:  via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/78230f78-126f-4ee6-8c1d-b1919ccfe3e9)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/7013591a-069e-4e77-873f-3dee90413781)
     </details>


## Reference
1. PR: https://github.com/harvester/harvester-installer/pull/681

**Comment by w13915984028** [comment]
@albinsun Thanks for the detailed verification. I will add another [PR](https://github.com/harvester/harvester/pull/5591) to fix the `harvester-eventrouter` version upgrading.

**Comment by w13915984028** [comment]
@albinsun The PR https://github.com/harvester/harvester/pull/5591 was merged today. You may re-validate with a new daily-built ISO from 2024.04.18 which includes the fix, thanks.

**Comment by albinsun** [comment]
Retest the upgrade (`v1.2.1` -> `v1.2-60f5c8a9-head`) case, all 3 images uses expected version, close as fixed.
Thank you.

## Environment
* Harvester
  * Version: `v1.2.1` -> `v1.2-60f5c8a9-head`
  * Profile: QEMU/KVM, single node (16C/32G/500G)
  * ui-source: `Auto`


## Test Cases
1. Setup harvester `v1.2.1`
   * <details>
     <summary> Enable <b>rancher-monitoring</b> and <b>rancher-logging</b> addons
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/46f63666-ea64-4543-8028-b6a8dc8d8dea)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle: via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/e8d8a6e5-dfb1-4ced-9dea-953ee23f5c34)
     
     Sign-in
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/0d6784c6-04e3-4137-ac72-0a8688261dde)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/91395f7f-75fb-44d3-aae4-b3bcd56b52ee)
     ![image](https://github.com/harvester/harvester/assets/2773781/885a68e0-8e36-4b3b-911a-f1329903636a)

     Login
     harvester#4756
     ![image](https://github.com/harvester/harvester/assets/2773781/0fac3cd3-f9ce-4910-85ec-c30dc1ebcede)
     </details>


1. <details>
   <summary> Upgrade to <code>v1.2-60f5c8a9-head</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f67fbbb2-0e0d-4dd4-b835-c426d8d7ba8b)
   </details>

1. Check charts version and status
   * <details>
     <summary> :green_circle: <b>rancher-monitoring</b> is <code>103.0.3+up45.31.1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/33c72ac9-e435-479d-9e8d-df1e7cdaa250)
     ![image](https://github.com/harvester/harvester/assets/2773781/925a21f5-4bd7-41a6-b957-a3d97636ccd0)
     </details>

   * <details> 
     <summary> :green_circle: <b>rancher-logging</b> should be <code>103.0.0+up3.17.10</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9516d3a8-413e-43bc-8923-a15886a9a8d4)
     ![image](https://github.com/harvester/harvester/assets/2773781/511bd8d2-882c-4e29-8107-cc9d4394276c)
     </details>

   * <details>
     <summary> :green_circle: <b>harvester-eventrouter</b> should be <code>v0.1.2</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a141cd54-002e-447f-8ced-f1025392c68e)
     </details>

1. Check Grafana Dashboard and Login
   * <details>
     <summary> :green_circle:  via Harvester
     </summary>
   
     ![image](https://github.com/harvester/harvester/assets/2773781/a55bf36b-87ff-4088-acf1-f5791f09dfd9)
     </details>

   * <details>
     <summary> :green_circle: via Rancher
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/9e1d0b88-e171-43f8-9574-462727153ec9)
     </details>
