### ISSUE TITLE
[Doc] Document management VIP requirements

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5417]
**Is your doc request related to a problem? Please describe or add related issue ID.**

Harvester may be deployed into some environments where routing to the Harvester hosts management interfaces is managed via software-defined networking. For example, a bare metal provider might provide their customer with an IP address that can be reassigned to a different host in real time.

In a scenario such as this, kube-vip's gratuitous ARP failovers will be ineffective, as the bare metal provider will still direct traffic to whatever IP address the "floating"/"reserved" IP is set to in their systems.

This can have adverse effects on a cluster. For example, if the bare metal customer purchases another server to join to the cluster, the new node will not be able to join, since it will send packets destined to the VIP, the bare metal provider will route to the OLD host that the VIP was on, and the OLD host will look at the IP address on the packets and say "that's not me" -- and it isn't, because kube-vip removed the IP address from the OLD host's interface, and it is now on a new host. 

The customer must manually update the "Reserved IP" through their hosting provider in order to restore functionality when kube-vip fails over.

**Describe the solution you'd like**

Document these caveats when using a bare metal hosting provider so that Harvester operators are not taken by surprise. Also document how to identify which node the VIP failed over to so that they know what value to plug into their hosting provider's Reserved IP settings.

---

Note, there is a pre-existing Harvester issue RE: one such provider: https://github.com/harvester/harvester/issues/1181

And it's possible that if Harvester grew support for parameterizing the kube-vip configuration to use BGP that may also resolve the issue for some hosting providers: https://kube-vip.io/docs/modes/bgp/ -- but that is separate from this documentation issue.

**Comment by bk201** [comment]
cc @starbops too
