### ISSUE TITLE
[Question] The current version v1.2.1 is less than the minimum upgradable version v1.2.2.

### ISSUE THREAD

**Issue by DovydasNavickas** [harvester/harvester#5418]
I spent some time figuring this one out, so I'll leave it here as a closed question.

I have Harvester 1.2.1 cluster and wanted to upgrade it to Harvester 1.3.0, thus I created the version from a command line by applying `version.yaml` that is found in [1.3.0 release assets](https://github.com/harvester/harvester/releases/tag/v1.3.0).

What I read, but did not register was the note bellow in the release notes:

>Note
>
>Harvester will eventually support upgrading from v1.2.2 to v1.3.0. Once that version is released, you must first upgrade a Harvester cluster to v1.2.2 before upgrading to v1.3.0.

This says that 1.2.2 version will be released later on, so right now upgrade is simply not supported 🥲

But hey, you can do what I will: reinstall Harvester right now from scratch.

Hope this helps someone like me 😄

**Comment by dimepues** [comment]
@DovydasNavickas - that addresses my confusion as well.
