### ISSUE TITLE
[BUG] Namespace "X" not found when creating public SSH key in a new namespace

### ISSUE THREAD

**Issue by DovydasNavickas** [harvester/harvester#5419]
**Describe the bug**

Creating a VM and a namespace doesn't allow adding new public SSH keys.

**To Reproduce**
When creating VM in a, I can create a new namespace:
![image](https://github.com/harvester/harvester/assets/7989797/9d05c356-aee0-4363-8dfc-b59a1ff4b2ac)

Then, I can add a new public SSH key:

<img width="1223" alt="image" src="https://github.com/harvester/harvester/assets/7989797/c4e32226-0417-44a1-a44f-05556c0a44f3">

And when trying to create the public SSH key, I get an error about the namespace:
![image](https://github.com/harvester/harvester/assets/7989797/414a1402-08f8-4441-9b60-558d3509c3a3)

**Expected behavior**

Both namespace and public SSH keys would be created.

**Support bundle**

**Environment**
Irrelevant.

**Comment by Yu-Jack** [comment]
@DovydasNavickas thank for raising this, it's a bug indeed.

Currently, we create namespace after clicking `Create` button on vm page. It checks if this namespace exists or not. If not, it creates it first, like these requests order on the network tab. 

![image](https://github.com/harvester/harvester/assets/6960289/c46208a6-be30-4aae-a6bf-1a486ec0a9a0)
![image](https://github.com/harvester/harvester/assets/6960289/23933b55-aaec-4ec8-8b14-b8a9f10139dd)
![image](https://github.com/harvester/harvester/assets/6960289/0ff0fe65-2e76-4c23-8b94-57588f4ab051)

But, it didn't have this flow when creating ssh key on vm page. Current workaround is to create ssh first on "SSH Keys" page or create namespace first before doing this.

**Comment by torchiaf** [comment]
The SSHKey modal is used only in VM create page.
I think we could just edit the new SSH key and save it after clicking Create button, so that the namespace is created first, then the SSH key and then the VM.

**Comment by torchiaf** [comment]
@bk201 It's possible to create a VM in namespace `x`,  assigning SSH Keys from namespace `y` . Does it make sense ?

**Comment by DovydasNavickas** [comment]
@torchiaf, that is true, assigning SSH keys from other namespaces is fine.

But creating them into selected namespace still makes sense and if the namespace doesn't exist yet, creating it for the SSH keys being created also makes sense, no matter whether the VM creation will be canceled or approved.

**Comment by irishgordo** [comment]
@torchiaf thanks for this fix :smile: :+1:  - this looks good on v1.4.0-dev-20240705 I'll go ahead and close this out 
![Screenshot from 2024-07-09 15-50-17](https://github.com/harvester/harvester/assets/5370752/6ec0a8a2-4752-4ab1-9086-89889611e034)
