### ISSUE TITLE
[BUG] Unable to enable NVIDIA A30 SR-IOV GPU Devices in Harvester

### ISSUE THREAD

**Issue by avramadam** [harvester/harvester#5438]
**Describe the bug**
Unable to enable NVIDIA A30 SR-IOV GPU Devices in Harvester

**To Reproduce**
1. enable nvidia driver toolkit
2. enable GPU in SR-IOV GPU Devices
3. device will not enable

**Expected behavior**

1. GPU devices should enable and be viewable in GPU devices and vGPU's should be assignable to VM's

**Support bundle**
[
[supportbundle_504f86b3-e0c2-4621-947e-bbfdf3e22e8c_2024-03-19T17-17-15Z.zip](https://github.com/harvester/harvester/files/14705231/supportbundle_504f86b3-e0c2-4621-947e-bbfdf3e22e8c_2024-03-19T17-17-15Z.zip)
](url)

**Environment**
 - Harvester ISO version: 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Gigabyte G492-HA0

**Comment by Yu-Jack** [comment]
Hi @ibrokethecloud, could you help me take a look at this one if you're available?

I found some error messages in support bundle file, do you have any ideas about this one?

1. In harvester-system/nvidia-driver-runtime pod
    `Installing nvidia driver from HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run`, and this is env setting for this pod. Is it normal to use `HTTPENDPOINT` string here?
    ```yaml
    env:
    - name: DRIVER_LOCATION
      value: HTTPENDPOINT/NVIDIA-Linux-x86_64-vgpu-kvm.run
    ```
2. In harvester-system/harvester-pcidevices-controller
    - `error syncing 'harvester0-00001c000': handler on-gpu-change: error during readiness check: error during command execution: unable to upgrade connection: container not found (\"nvidia-driver-ctr\"), requeuing`
    - `pcideviceclaim harvester0-00001c000 is already in use with vm windows11 in namespace saravm`, but I couldn't find any pcidevicecalim in SBK.
    - `nvidia.com/GA100GL_A30_PCIE device plugin failed to deregister: rpc error: code = Unavailable desc = transport is closing","pos":"device_manager.go:250","reason":"rpc error: code = Unavailable desc = transport is closing`

**Comment by avramadam** [comment]
Needed to follow instructions in https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit/
