### ISSUE TITLE
[BUG] Grafana dasboard doesn't show the correct vm metrics

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5442]
**Describe the bug**
It's a bug from https://github.com/harvester/harvester/issues/5439, the metrics name aren't setup well in Grafana dashboard.

**To Reproduce**
1. Install rancher-monitor addon
2. Create a new VM
3. Open `Harvester VM Dashboard` and `Harvester VM Info Detail` two dashboards
4. `CPU Usage` and `IO Time` are empty

**Expected behavior**
The dashboard should show `CPU Usage` and `IO Time` correctly. We should modify [config here](https://github.com/harvester/harvester-installer/blob/ff64a85e38168afe5c1b982948b5f159a59ca8d1/pkg/config/templates/rancherd-12-monitoring-dashboard.yaml).

The problems is that there is a breaking change on kubevirt between v1.0.0 and v1.1.0. We should check all metrics make sure we don't miss one of them.
- KubeVirt v1.0.0 - https://github.com/kubevirt/kubevirt/blob/v1.0.0/docs/metrics.md#kubevirt_vmi_vcpu_seconds
- KubeVirt v1.1.0 - https://github.com/kubevirt/kubevirt/blob/v1.1.0/docs/metrics.md#kubevirt_vmi_vcpu_seconds_total

We only need backport to v1.3 unless we will upgrade KubeVirt of Harvester v1.2.
- Harvester v1.2 use KubeVirt v1.0.0 https://github.com/harvester/harvester/blob/918dd4f3064136b8ea87ec0b63af8381f2f6f9fb/go.mod#L46-L47
- Harvester v1.3 use Kubevirt v1.1.0  https://github.com/harvester/harvester/blob/93c13ccca7aa8a4557b8a46047ffe07ed92ede3d/go.mod#L47-L48

**Workaround**
[Current workaround way](https://github.com/harvester/harvester/issues/5439#issuecomment-2014355790). 

**Environment**
 - Harvester ISO version: v1.3.0

**Additional context**
None

**Comment by brandboat** [comment]
kubevirt also rename these two metrics `kubevirt_vmi_storage_read_times_ms_total`  `kubevirt_vmi_storage_write_times_ms_total` which are used in `rancherd-12-monitoring-dashboard.yaml`.

`kubevirt_vmi_storage_read_times_ms_total` → `kubevirt_vmi_storage_read_times_seconds_total`
`kubevirt_vmi_storage_write_times_ms_total`  → `kubevirt_vmi_storage_write_times_seconds_total`

**Comment by w13915984028** [comment]
Test on latest Harvester v1.2.2, it has similar issue, the kubevirt related image version is v1.1.0.

![image](https://github.com/harvester/harvester/assets/31133476/96fd6ff4-3b76-42ae-99c7-1e8e66667a6f)

**Comment by w13915984028** [comment]
An upgrade processing will be added to Harvester v1.2.2 to fix the configmap on upgrade path, as those 2 configmaps are not in some charts.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-8b80f82-head` (24/07/17). Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ On single node: can display vm dashboard and vm metrics details with correct value and chart  $~~$</summary>

  1. Can display the Harvester vm dashboard chart and value well
   ![image](https://github.com/user-attachments/assets/2ede6177-9ed5-4b63-8b3c-b1a320b21d30)

  2. Can display the Harvester vm metrics details chart and value well
  ![image](https://github.com/user-attachments/assets/4e9ae900-4675-4b8e-af2a-7cdc033dc134)



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ On multiple nodes: can display vm dashboard and vm metrics details with correct value and chart  $~~$</summary>

  1. Can display the Harvester vm dashboard chart and value well
  ![image](https://github.com/user-attachments/assets/4a4226e8-d1ff-40d1-a352-3e44076fde7f)


  2. Can display the Harvester vm metrics details chart and value well
  ![image](https://github.com/user-attachments/assets/cd6d118e-3f9a-4616-ab25-24d882024bf0)



 </details>

### Test Information
* Test Environment: Single nodes harvester on equinix bare machines
* Harvester version: `v1.1-340486a3-head` (23/11/20)

### Verify Steps
<details><summary>Check VM dashboard and VM metrics charts</summary>

  1. Enable rancher monitoring addons
  2. Create some vms
  4. Check the Harvester VM metrics dashboard on the `Dashboard` page
  5. Access any of the vm
  6. Check the `VM Metrics` page content

</details>
