### ISSUE TITLE
[BUG] Websocket keeps reconnecting on the host detail page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#546]
**Describe the bug**
Websocket keeps reconnecting on the host detail page

**To Reproduce**
1. Go to the settings page and enable VLAN
2. Go to the host detail page
3. Check on the console in Chrome

**Result**
Websocket keeps reconnecting on the host detail page
![image](https://user-images.githubusercontent.com/57614736/111962894-dc417a80-8b2d-11eb-9545-a917c053b8c2.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by WuJun2016** [comment]
@guangbochen     When I subscribe to resources based on id, the situation of always disconnecting and reconnecting will recur. Please help to determine if I can subscribe to resources based on ID

**Comment by gitlawr** [comment]
It seems that watching nodemetrics.metrics.k8s.io is not supported
```
$ kubectl get nodemetrics.metrics.k8s.io  nn1 -w
NAME   AGE
nn1    0s
Error from server (MethodNotAllowed): the server does not allow this method on the requested resource (get nodes.metrics.k8s.io)
```
Can we change to watch the collection if that works in this case?

**Comment by DoNotSayYes** [comment]
Validated on master-head
