### ISSUE TITLE
[BUG] Load balancer using IPAM Pool stuck Pending

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5475]
**Describe the bug**
Load balancer using IPAM Pool stuck Pending with message `Error syncing load balancer`.

**Environment**
* Harvester
  * Version: `v1.3.0`
  * Profile: QEMU/KVM, single nodes (16C/32G/500G)
  * ui-source: `Auto`
* Rancher
  * Version: `v2.7.10`
  * Profile: Helm w/ K3s (1C/4G)
  * Guest Cluster: `v1.26.14+rke2r1`

**To Reproduce**
1. Setup `harvester-v1.3.0`
2. Prerequisites
   * <details>
     <summary> Image <b>ubuntu-22.04-server-cloudimg-amd64.img</b>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a3911863-a249-4b97-bcea-168938692ca6)
     </details>

   * <details>
     <summary> VM Network <b>mgmt-vlan1</b>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/3d92503b-7991-488c-ae84-2aff922b3fb0)
     </details>
     
   * <details>
     <summary> IP Pool 192.68.0.0/24 with <b>mgmt-vlan1</b> and <b>default</b> namespace
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/a2b5de3c-bce6-432d-baae-a161877311d3)
     ![image](https://github.com/harvester/harvester/assets/2773781/4480e4d8-6f2f-4717-a36a-2fb2c164df24)
     </details>

4. Import  to `rancher-v2.7.10`
   <details>

   ![image](https://github.com/harvester/harvester/assets/2773781/4877b45d-5adb-49d1-8789-1096d91363ac)
   </details>

5. Create RKE2 cluster
   * <details>
     <summary> <code>v1.26.14+rke2r1</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/0bebf6b1-eeb8-47fb-93f7-101a65df982c)
     </details>

   * <details>
     <summary> Upgrade <b>harvester-cloud-provider</b> to <code>102.0.2+up0.2.3</code>
     </summary>
     
     ![image](https://github.com/harvester/harvester/assets/2773781/264b50f9-44fb-42b7-a291-2981290e9e02)
     </details>

6. Deploy mynginx with image `nginx:latest`
   <details>

   ![image](https://github.com/harvester/harvester/assets/2773781/865d8e1f-9470-4a4f-94d3-8dcfb5b21997)
   </details>

7. Create load balancer **lb-pool** with IPAM `Pool` :red_circle: 
   * <details open>
     <summary> Stuck <code>Pending</code>
     </summary>
     
     `Error syncing load balancer: failed to ensure load balancer: update load balancer IP of service default/lb-nginx-pool failed, error: timeout waiting for IP address`
     ![image](https://github.com/harvester/harvester/assets/2773781/e9518523-3586-4d37-8ae1-ed589f7748f0)
     </details>
   
   * <details>
     <summary> Config YAML
     </summary>
   
     ```
      apiVersion: v1
      kind: Service
      metadata:
        annotations:
          cloudprovider.harvesterhci.io/ipam: pool
        creationTimestamp: '2024-03-27T16:21:10Z'
        finalizers:
          - service.kubernetes.io/load-balancer-cleanup
        managedFields:
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:annotations:
                  .: {}
                  f:cloudprovider.harvesterhci.io/ipam: {}
              f:spec:
                f:allocateLoadBalancerNodePorts: {}
                f:externalTrafficPolicy: {}
                f:internalTrafficPolicy: {}
                f:ports:
                  .: {}
                  k:{"port":8080,"protocol":"TCP"}:
                    .: {}
                    f:name: {}
                    f:port: {}
                    f:protocol: {}
                    f:targetPort: {}
                f:selector: {}
                f:sessionAffinity: {}
                f:type: {}
            manager: agent
            operation: Update
            time: '2024-03-27T16:21:10Z'
          - apiVersion: v1
            fieldsType: FieldsV1
            fieldsV1:
              f:metadata:
                f:finalizers:
                  .: {}
                  v:"service.kubernetes.io/load-balancer-cleanup": {}
            manager: harvester-cloud-provider
            operation: Update
            subresource: status
            time: '2024-03-27T16:21:10Z'
        name: lb-nginx-pool
        namespace: default
        resourceVersion: '7754'
        uid: c357f9d8-49e1-46c1-a3ba-49cf6e112f3c
      spec:
        allocateLoadBalancerNodePorts: true
        clusterIP: 10.43.6.193
        clusterIPs:
          - 10.43.6.193
        externalTrafficPolicy: Cluster
        internalTrafficPolicy: Cluster
        ipFamilies:
          - IPv4
        ipFamilyPolicy: SingleStack
        ports:
          - name: myport
            nodePort: 31083
            port: 8080
            protocol: TCP
            targetPort: 80
        selector:
          name: mynginx
        sessionAffinity: None
        type: LoadBalancer
      status:
        loadBalancer: {}
     ```
     </details>
   

**Expected behavior**
Load Balancer successfully deploied and start forwarding.

**Support bundle**
* Harvester:
[supportbundle_ippools.zip](https://github.com/harvester/harvester/files/14776371/supportbundle_ippools.zip)

* Rancher:
[rancher-2024-03-27_16_28_37.tar.gz](https://github.com/harvester/harvester/files/14776374/rancher-2024-03-27_16_28_37.tar.gz)

**Additional context**
1. It is the first created LB on this cluster, no previous deleted ones.

**Comment by albinsun** [comment]
Hi @starbops ,
I know there are ongoing enhancement/fixs about DHCP, so not sure this is expected or not.  
Please help to check.

Thanks

c.c @TachunLin

**Comment by albinsun** [comment]
FYI, test can pass if we config IPPool via Rancher RBAC.
Note that the selector UI field is different with RBAC.

![image](https://github.com/harvester/harvester/assets/2773781/6da4cac6-2b44-4dbe-9409-a002d0748815)
![image](https://github.com/harvester/harvester/assets/2773781/cd1237b0-829c-43cc-8431-8c78da455d5d)

**Comment by albinsun** [comment]
Per discussion, this is the expected behavior.
To summarize:
* IPPool for guest cluster LB need to be config via Rancher RBAC.
* IPPool for harvester own LB can config directly.

**Comment by w13915984028** [comment]
Connect with https://github.com/harvester/harvester/issues/5483, will check if we need to add some notes on Harvester document.
