### ISSUE TITLE
[BUG] VM IP address displays incorrect

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#548]
**Describe the bug**
VM IP address displays incorrect

**To Reproduce**
1. Create a VM
2. Go to the VM detail page
3. Check IP Address

**Result**
VM IP address displays incorrect
![image](https://user-images.githubusercontent.com/57614736/111968393-0dbd4480-8b34-11eb-84cc-8098e06c0dbf.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by kingsd041** [comment]
Validated on v0.2.0-rc2

This issue has been fixed in v0.2.0-rc1, and the VM IP can be displayed correctly
![image](https://user-images.githubusercontent.com/19684717/113124382-0db1f880-9248-11eb-9168-502ec514e24b.png)
