### ISSUE TITLE
[Question] Deploying VMs through kubernetes operations (infrastructure as code)

### ISSUE THREAD

**Issue by mjj29** [harvester/harvester#5484]
Hi there, I see that Harvester manages everything through kubernetes objects. That suggests that I could use gitops to deploy VMs by creating k8s objects in git and then applying them directly to the cluster, rather than through the UI. However, I don't obviously see that in the documentation that it's supported. Is that something you explicitly support? Presumably I'd need to do something to create/copy the disks as well as the VM object itself?

Thanks,
Matt

**Comment by starbops** [comment]
Hi @mjj29, it looks like #5018 is what you need, is that correct?

**Comment by mjj29** [comment]
Yes, that looks OK, thanks
