### ISSUE TITLE
[BUG]  v1.3.0 ：The node is locked and cannot be restored

### ISSUE THREAD

**Issue by seajelly** [harvester/harvester#5490]
**Describe the bug**

When I added the node03 node to the cluster and wanted to set up a 3-node cluster, I found that the status of node03 was always Cordoned, and there was no uncordon option in the more operations.

**To Reproduce**
1.  View host status
![image](https://github.com/harvester/harvester/assets/42405205/84a5304d-9d16-4902-a58e-5223c3cd0898)

2. 
There is no uncordon option
![image](https://github.com/harvester/harvester/assets/42405205/d0fcf40f-8f63-4e9c-8c99-c4d641c8b974)

3.  dashboard  event
![image](https://github.com/harvester/harvester/assets/42405205/b749eb01-ae09-4bd4-9d9d-e5260a4e3432)

**Expected behavior**

That the worker node would be able to recover
**Support bundle**

[supportbundle_28abdbb1-ae21-4d67-b8ad-9ab1b55ea369_2024-03-29T07-28-05Z.zip](https://github.com/harvester/harvester/files/14800969/supportbundle_28abdbb1-ae21-4d67-b8ad-9ab1b55ea369_2024-03-29T07-28-05Z.zip)

**Environment**
 - Harvester ISO version: 
   v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
  huawei 2288hv5

**Additional context**

**Comment by bk201** [comment]
Label `kubevirt.io/schedulable` is `false` on node `har-node03`. And virt-handler complains it can't register kvm.

kubelet on `harv-node03` keep posting:
```
E0329 07:29:28.613082   33500 server.go:309] "Unable to authenticate the request due to an error" err="[invalid bearer token, service account token is not valid yet]"
E0329 07:29:45.920131   33500 server.go:309] "Unable to authenticate the request due to an error" err="[invalid bearer token, service account token is not valid yet]"
E0329 07:30:10.493452   33500 server.go:309] "Unable to authenticate the request due to an error" err="[invalid bearer token, service account token is not valid yet]"
E0329 07:30:28.696648   33500 server.go:309] "Unable to authenticate the request due to an error" err="[invalid bearer token, service account token is not valid yet]"
```

Can you try if running `systemctl restart rke2-server` on `harv-node03` to restart kubelet helps?

**Comment by bk201** [comment]
And does the time sync between 3 nodes? Thanks.

**Comment by seajelly** [comment]
> And does the time sync between 3 nodes? Thanks.时间在 3 个节点之间同步吗？谢谢。

sorry ，The three nodes are out of sync. They are directly different by a few minutes. Now I will modify the ntp service.

**Comment by seajelly** [comment]
> And does the time sync between 3 nodes? Thanks.

thank you， bro 。After time synchronization, the problem is solved.  god bless you
