### ISSUE TITLE
[ENHANCEMENT] Make "LiveMigrateIfPossible" the default EvictionStrategy instead of "LiveMigrate"

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5495]
**Is your enhancement related to a problem? Please describe.**

KubeVirt fires an event with a severity of Warning when a VMI exists with an EvictionStrategy of LiveMigrate and it cannot be live migrated (i.e. the VMI is configured with a HostDevice.) This Warning event can trigger alerting in monitoring stacks.

Currently, the dashboard hardcodes LiveMigrate as the eviction strategy.

**Describe the solution you'd like**

Harvester 1.2-head, 1.3-head, and master all have a new enough version of KubeVirt that supports LiveMigrateIfNecessary to avoid firing off spurious warnings.

**Describe alternatives you've considered**

**Additional context**

**Comment by connorkuehl** [comment]
The checklist seems to suggest UI and backend issues can just exist as one issue, so I will close this one in favor of 

https://github.com/harvester/harvester/issues/5049

**Comment by bk201** [comment]
> The checklist seems to suggest UI and backend issues can just exist as one issue, so I will close this one in favor of
> 
> #5049

Close, let's use only #5049 to track.
