### ISSUE TITLE
[Doc] Remove useless "namespace" parameters which some APIs don't need that.

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5497]
**Is your doc request related to a problem? Please describe or add related issue ID.**

The "clusternetwork" API does not have a "namespace" parameter, but it is mentioned in our documentation (https://docs.harvesterhci.io/v1.3/api/list-namespaced-cluster-network). 

![image](https://github.com/harvester/harvester/assets/6960289/799b307d-6224-4874-a1b6-82b9b17141de)

**Describe the solution you'd like**

We only check if this api has namespace or not in path, but not other fields. So, we need to add it back. 

For example:

https://github.com/harvester/harvester/blob/e44afeb0c7ad61a265be9d6888ba125e78002750/pkg/genswagger/rest/webservices.go#L201-L203

Should become following

```go
func addGetNamespacedListParams(builder *restful.RouteBuilder, ws *restful.WebService, namespaced bool) *restful.RouteBuilder {
	addCollectionParams(builder, ws)

	if namespaced {
		builder.Param(NamespaceParam(ws))
	}

	return builder
}
```

**TODO**

- [x] Fix harvester/harvester
- [x] Fix harvester/docs

**Comment by drewmullen** [comment]
- [I see that](https://github.com/harvester/harvester/blob/master/api/openapi-spec/swagger.json#L7931-L7939) `namespace` is listed as a required post parameter in the OAS doc.
- I also see it as [required](https://github.com/drewmullen/harvester-go-sdk/blob/main/api_networks.go#L29) when calling LIST ClusterNetworks in the Go sdk

Question: Should it even be considered an optional parameter? based on your description I think not even an optional param but just want to be clear. 

Are there any LIST APIs that should `namespace` as a param? If yes, what is the difference between passing the namespace in path vs as a param? FWIW,  every LIST API specifies `namespace` as required ATM.

**Comment by Yu-Jack** [comment]
IIRC, clusternetworks doesn't have namespace here cause its scope is cluster. That's why I think need to remove it in documentation.

**Comment by drewmullen** [comment]
I was curious so I tested your proposed solution out this morning and it works.  I'm happy to add it onto #5512 if you'd like!

**Comment by Yu-Jack** [comment]
Because it's not only LIST API, it might include others, need to walk through to check that. So, I prefer not to add it into #5521 PR, thanks!

**Comment by Yu-Jack** [comment]
## Environment

- https://docs.harvesterhci.io/v1.3/api/list-cluster-network
- https://docs.harvesterhci.io/v1.4/api/list-cluster-network

## Test Cases

It works well, so I would close it.

![image](https://github.com/harvester/harvester/assets/6960289/a99b39da-75f9-4458-9d04-995ad5607b32)

![image](https://github.com/harvester/harvester/assets/6960289/129bcd40-621b-44b1-887c-5422156354d8)
