### ISSUE TITLE
[BUG] Cannot access to Harvester dashboard

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5506]
This issue is intended to track the bug for QA.
Rancher original issue: https://github.com/rancher/dashboard/issues/10647

**Describe the bug**

The UI throws an error when navigating to Harvester dashboard from Rancher Virtualization tab

**To Reproduce**

- Setup a Harvester cluster on Rancher
- Go to explorer -> Virtualization tab
- Click on Harvester cluster' name in the clusters table.

**Result**

The fail-whale page shows the error:
```
Cannot read properties of undefined (reading 'currentProduct')
```

**Support bundle**

**Environment**
 - Rancher UI: v2.9-head
 - Harvester UI: all supported versions

**Additional context**

**Comment by irishgordo** [comment]
@torchiaf should this be checked with [Rancher v2.9.0-rc1](https://github.com/rancher/rancher/releases/tag/v2.9.0-rc1) or is v2.8.2 Rancher fine?

**Comment by torchiaf** [comment]
@irishgordo [Rancher v2.9.0-rc1](https://github.com/rancher/rancher/releases/tag/v2.9.0-rc1)

**Comment by irishgordo** [comment]
@torchiaf - this looks great on v2.9.0-rc1 Rancher via Rancher vCluster Addon with Harvester v1.3-head, I'll go ahead and close this out :smile: :+1: 
![Screenshot from 2024-05-17 12-30-51](https://github.com/harvester/harvester/assets/5370752/4a9725a3-1990-40d4-8023-3647ce0ba67e)

**Comment by irishgordo** [comment]
Re-Opening, need to revalidate due to:
https://github.com/harvester/harvester-installer/pull/737

**Comment by irishgordo** [comment]
Currently Blocked by:
https://github.com/harvester/harvester/issues/5852

**Comment by irishgordo** [comment]
Not blocked, testing on Docker w/ Rancher v2.9.0-rc1 this looks good with v1.3-head
![Screenshot from 2024-05-22 16-09-55](https://github.com/harvester/harvester/assets/5370752/58aee143-f35d-4684-aab8-661909d9ed4b)
![Screenshot from 2024-05-22 16-11-09](https://github.com/harvester/harvester/assets/5370752/3e978a5c-dfee-4c92-a562-91785609f061)

Thanks again for the fix @torchiaf
