### ISSUE TITLE
[BUG] Unable to select NIC to create network config

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#5509]
**Describe the bug**
There is no any NIC to select in the "Network Config: Create" page.
![image](https://github.com/harvester/harvester/assets/6293679/163fa781-5ed4-4604-ab68-7a6f47d3dd01)

**To Reproduce**
1. NETWORKS -> CLUSTER NETWORKS -> Create Cluster Network
2. for the cluster network in Step1 do CREATE NETWORK CONFIG
3. type the name
4. select nodes (I tried "all nodes", "specific node")
5. UPLINK -> NICS

ERROR: Sorry, no matching options

**Expected behavior**
I expect, that I can select existing NIC

**Environment**
 - Harvester ISO version: 1.3.0
 - one node: Dell Precision T7820, NVMe disc, 1 built-in NIC
 - here is my install config:
![image](https://github.com/harvester/harvester/assets/6293679/22cb6439-62ff-4d15-9952-03fbd996f4b9)

**Comment by SlavikCA** [comment]
[supportbundle_604401bf-d900-4d10-8f06-6c18a799c392_2024-04-04T04-00-30Z.zip](https://github.com/harvester/harvester/files/14861184/supportbundle_604401bf-d900-4d10-8f06-6c18a799c392_2024-04-04T04-00-30Z.zip)

**Comment by SlavikCA** [comment]
When I read https://github.com/harvester/harvester/issues/5030, I see @w13915984028 said 
> For direct access, the general solution is to add a second nic and put it in an indepedent VLAN

But when I read here https://docs.harvesterhci.io/v1.3/install/requirements/ - nothing says that I need more than 1 NIC.

Also here https://docs.harvesterhci.io/v1.3/advanced/singlenodeclusters/ I don't see anything about single node cluster having any limitation related to the network.

So, is it a bug? Or is it documentation need to be updated to inform, that Harvester doesn't support non-management cluster network without 2nd NIC?

**Comment by w13915984028** [comment]
@SlavikCA

When you are playing Harvester clusters with single-nic node, you can create VLAN network, which is carried by the built-in management network, follow https://docs.harvesterhci.io/v1.2/networking/harvester-network#vlan-network.

The general practice in production is to separate management network and VM workload network, in such cases, >= 2 nics in each node is needed. The newly created cluster-network will have dedicated uplink.

We will update the document to mention such requirements in https://docs.harvesterhci.io/v1.2/install/requirements#hardware-requirements. Thanks.

**Comment by w13915984028** [comment]
@SlavikCA Please also take a look the document PR https://github.com/harvester/docs/pull/543, thanks.

**Comment by SlavikCA** [comment]
> @SlavikCA Please also take a look the document PR [harvester/docs#543](https://github.com/harvester/docs/pull/543), thanks.

That helps! Thank you.

**Comment by SlavikCA** [comment]
Little bit off-topic, but since we're looking at the documentation now, let me ask:

What's the recommended network configuration if I have 1Gbps NIC and 10Gbps NIC?
Should I use 1Gbps for `management cluster network` and 10Gbps for `VM workload network`? Or vice versa?
Will Longhorn use `management cluster network` by default? 

The reason I ask about this specific setup is because often servers comes with 1Gbps NIC already on motherboard. So, as a user I'll add NIC to PCIe slot and it'll be 10Gbps.

If Longhorn uses `management cluster network`, I think I should dedicate 10Gbps to it and 1Gbps to VM workload network. Is it reasonable?

**Comment by starbops** [comment]
Hi @SlavikCA By default, yes, LH uses the `management cluster network`. You can configure a storage network with dedicated NICs on the nodes for LH pods to separate the replication traffic. For more details please refer to https://docs.harvesterhci.io/v1.3/advanced/storagenetwork

Thank you.
