### ISSUE TITLE
[FEATURE] End to end (e2e) test framework

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#551]
We need to create an end-to-end test framework for Harvester.

All the major features of Harvester need to be tested, including starting/stopping VM and VLAN, etc.

**Comment by guangbochen** [comment]
- [Harvester iPXE Boot Using Vagrant Libvirt](https://github.com/harvester/ipxe-examples/tree/main/vagrant-pxe-harvester)
- Harvester e2e testing cases - [harvester/tests](https://github.com/harvester/tests)

**Comment by guangbochen** [comment]
I think it should be fine for us to close this issue and open the sub-item tasks to track those missing e2e tests if needed, thanks.

**Comment by yasker** [comment]
The basic framework is done at https://github.com/harvester/tests. Close this issue and track sub items accordingly.
