### ISSUE TITLE
Cannot start VMs, I've had a long journey to get to where I am.

### ISSUE THREAD

**Issue by prhiam** [harvester/harvester#5513]
I've had a tough time getting a Harvester node up, and I know that I've got only two nodes in the cluster, but I don't have a third to add at this time. Right now, I cannot start harvester VMs, the volumes always says degraded and replica scheduling failed. I really want to use and learn Harvester and Rancher, but this is starting to get frustrating after over 2 weeks just to stand the machines up. Can anyone give me an idea as to why it would be generating this error even though there is plenty of disk space for what I'm trying to do? I have 600 free on the machine and I'm asking for a disk size of 40.
<img width="2306" alt="Screenshot 2024-04-05 at 8 43 31 AM" src="https://github.com/harvester/harvester/assets/39346758/cfa9aea9-5454-4f0b-a836-99a3a7b5a4c4">

**Comment by RegisWeduLabs** [comment]
Hi there, Can you go directly in the k8s cluster - in longhorn, and see what is going on there?  Once logged in, you need to modify the url to get access to the actual underlying k8s cluster.  As an example: https://x.x.x.x/dashboard/harvester/c/local/kubevirt.io.virtualmachine - remove the harvester and the kubevirt.io.... - so the url looks like https://x.x.x.x/dashboard/c/local/ - you should then see a longhorn tab in the left menu - it will give you a better idea of what is going on.  If you can, provide screenshots of the volumes - and also, please provide a screenshot of one of the node "storage" section (in harvester - hosts - click the host, you will have a "storage" section.

**Comment by prhiam** [comment]
I guess I’m not sure how to troubleshoot properly, which is my fault. All I see is the disks there, then degraded. I tried attaching two volumes to a node and it says there are no scheduled replicas. I haven’t edited anything from my install, I’m not sure how to get scheduled replicas? Attached are all the screenshots. Thank you for showing me how to get into Longhorn though, I never knew how to get into the k8s cluster dashboard before, it’s very beneficial.

Any information you can give me would be great.






Thank you,
Paul Hiam

**Comment by RegisWeduLabs** [comment]
Hey - I don't see your screenshots...

**Comment by prhiam** [comment]
Now?

**Comment by RegisWeduLabs** [comment]
Nop - ideally, go on github and add the screenshots there - as I can see that you replied via email.

**Comment by prhiam** [comment]
Sorry about that, here they are.
<img width="2070" alt="Screenshot 2024-04-05 at 9 17 26 AM" src="https://github.com/harvester/harvester/assets/39346758/35d3ef68-6938-467b-b893-57c6d5c56f84">
<img width="2506" alt="Screenshot 2024-04-05 at 9 56 56 AM" src="https://github.com/harvester/harvester/assets/39346758/53c79a38-ca15-4783-940c-cba6acdd250e">
<img width="2096" alt="Screenshot 2024-04-05 at 9 18 57 AM" src="https://github.com/harvester/harvester/assets/39346758/4d97db19-c256-4f63-b6ea-9f9630524691">
<img width="2493" alt="Screenshot 2024-04-05 at 9 18 44 AM" src="https://github.com/harvester/harvester/assets/39346758/8ec6cb58-61e8-4be2-adf6-f427159b886c">
<img width="2073" alt="Screenshot 2024-04-05 at 9 17 15 AM" src="https://github.com/harvester/harvester/assets/39346758/7216e84e-ee9b-4b45-8f9b-9a835e6e4218">
<img width="2506" alt="Screenshot 2024-04-05 at 9 16 47 AM" src="https://github.com/harvester/harvester/assets/39346758/63f89eeb-0002-4794-a61d-5eb03549ef37">
<img width="2272" alt="Screenshot 2024-04-05 at 9 14 11 AM" src="https://github.com/harvester/harvester/assets/39346758/a4b688bd-6336-48b3-b2b3-334288f2e8c6">

**Comment by RegisWeduLabs** [comment]
Can you please click on one of the volume in longhorn?  It will show the nodes and replicas:
![image](https://github.com/harvester/harvester/assets/25985730/fa1f8f01-f2a4-420b-8fb5-23c2e76befbb)

And send a screenshot?  Also, on your volumes, in longhorn, change the replicas count from 3 to 2 as you have only 2 nodes.  If you are going to use only 2 nodes, create a new storage class and set the replica count to 2 - then use this storage class for your new vms - but for now setting the replica count to 2 should be fine for the existing ones.

**Comment by prhiam** [comment]
I've changed the replicas to 2 in the settings, that hasn't affected the main Storage Classes already created during install. Should I re-create the VM and see if it goes through with the new settings? Also, I had already used a new Storage Class and that one fails as well.

<img width="2518" alt="Screenshot 2024-04-05 at 10 58 18 AM" src="https://github.com/harvester/harvester/assets/39346758/42cb7a34-02b8-45a9-be5c-a48439dc891c">

**Comment by RegisWeduLabs** [comment]
From your screen shot - it seems the replicas are still 3 - did you changed the setting to 2 for this volume?

**Comment by prhiam** [comment]
I changed it in Longhorn settings, not sure how to set it for the Storage Class on the harvester cluster VIP.

**Comment by RegisWeduLabs** [comment]
Basically, in the longhorn dashboard - volumes tab - there is an hamburger menu on the right of each volume.  Click on it - "Update Replicas Count" - change it to 2 - do that for all your current volumes.  You can also do it in bulk by selecting all volumes - then click the hamburger menu on the top left of the screen next to Detatch - create backup - and you have the Update Replicas Count there so you can do them all in 1 go.

**Comment by prhiam** [comment]
Ok so done. But I still can't create VMs... In Longhorn one is still detached and can't be attached to a node without the error no replicas available. The other went in by default to 3 replicas again, I had to manually change it to get it to work. Should I reboot the nodes for the default replica counts to go to 2?

<img width="2500" alt="Screenshot 2024-04-05 at 11 31 12 AM" src="https://github.com/harvester/harvester/assets/39346758/bf33f0e9-4553-4d27-b5eb-77906eb82e74">

**Comment by prhiam** [comment]
Storage Classes still reading 3.
<img width="2299" alt="Screenshot 2024-04-05 at 11 34 10 AM" src="https://github.com/harvester/harvester/assets/39346758/74357f20-fc69-4794-8cc6-c230b3133af8">

**Comment by RegisWeduLabs** [comment]
No - just clone the harvester-longhorn storage class to something like harvester-2-replicas or whatever, set the replicas count to 2 - when you create a VM, make sure you select that new storage class you just created - and do so for all other vms going forward.  Just for the sake of simplicity - if your vms don't contain anything important, just delete them and recreate them using the new storage class you created.  Let me know if all works after this.  If not, please include new screenshots of the current state - including volume details (clicking on the volume in LH UI) - and the events on the dashboard of the K8S cluster interface.

**Comment by prhiam** [comment]
Both volumes failed, both volumes go into harvester detached. This is the frustration I've lived in for 2 weeks. I've also tried many of this before (from the storage class in Harvester UI). I've rebuilt the Cluster Nodes 3 times as well.

<img width="2526" alt="Screenshot 2024-04-05 at 12 09 47 PM" src="https://github.com/harvester/harvester/assets/39346758/486dfb8e-0ada-41bf-a1e8-b1f40982fa3d">
<img width="2532" alt="Screenshot 2024-04-05 at 12 09 36 PM" src="https://github.com/harvester/harvester/assets/39346758/6d52a72e-d77e-4b2a-89e9-42e11cd6342c">
<img width="2274" alt="Screenshot 2024-04-05 at 12 09 28 PM" src="https://github.com/harvester/harvester/assets/39346758/ab3b09bc-fcf0-47fe-be1d-b2064d2d48e7">
<img width="2513" alt="Screenshot 2024-04-05 at 12 08 26 PM" src="https://github.com/harvester/harvester/assets/39346758/4c3c428b-73bf-4651-818e-a1254bcb17b8">
<img width="2310" alt="Screenshot 2024-04-05 at 12 08 15 PM" src="https://github.com/harvester/harvester/assets/39346758/b3f345e3-7cd3-4c2d-bc47-0d7968d946e1">

**Comment by RegisWeduLabs** [comment]
At this point - maybe it's better if someone from harvester hop in - and probably provide a support bundle for them to analyse...  One thing you could try is to delete the instance managers pods and the scheduler pods in the longhorn-system namespace - see if that helps.  If not - then at this point a support bundle would contain information needed to troubleshoot.

**Comment by Vicente-Cheng** [comment]
Hi @prhiam, sorry for the late reply.

Did the situation still happen?
If yes, could you generate the support bundle (REF: https://docs.harvesterhci.io/v1.3/troubleshooting/harvester/#generate-a-support-bundle) for investigation?

Thanks!

**Comment by prhiam** [comment]
As much as I wanted to use harvester for my hypervisor I finally just gave up on it. There were too many issues I kept running in to, from this issue which I resolved through a new install. To provisioning new hosts with cloud init images. It was non-stop issues after issue. Took way too much of my time building, so I just installed proxmox and haven’t looked back.

Thank you
