### ISSUE TITLE
[BUG] Various error messages in the console, using Harvester - embedded mode

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5526]
**Describe the bug**

Some console errors are visible when running Harvester in Rancher UI, in local environments.

**To Reproduce**
1. Run a Rancher UI instance locally
2. Go to Virtualization Manager -> click on a Harvester cluster
3. Go to Virtual Machines tab
4. Check the Browser's console

**Result**

`State` field and others in `HarvesterMigrationState` component are generating Vue errors

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
Thanks for the fix @torchiaf :smile: :+1:  - this looks good on v1.2.2-rc1, not noticing any of the error messages in the console similar to:
https://github.com/harvester/dashboard/pull/978#issue-2206432293
W/ Rancher v2.8.2 & Harvester v1.2.2-rc1 w/ Rancher installed via rancher-vcluster
![Screenshot from 2024-04-30 17-42-52](https://github.com/harvester/harvester/assets/5370752/cec3e1e2-3197-455a-84a8-5527eaf79ae7)
I'll go ahead and close this out

**Comment by irishgordo** [comment]
re-opening as to wait to close this out based on v1.3 testing

**Comment by irishgordo** [comment]
@torchiaf this looks great on Harvester  Version: v1.4.0-dev-20240705  - with Docker Rancher v2.8.5 running :+1: :smile: 

I'll go ahead and close this out :smile: 

![Screenshot from 2024-07-08 20-58-55](https://github.com/harvester/harvester/assets/5370752/eae0f1a1-97e1-4026-b0d5-98e6b1a3dac3)
