### ISSUE TITLE
[BUG] Using vmimage.status.storageClassName to fill volumeClaimTemplates

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5551]
**Describe the bug**
When changing storage class name format (https://github.com/harvester/harvester/pull/5459), I cannot create a VM with new format. It looks like dashboard uses `longhorn-<vmimage-name>` as storage class name. It's better to get storage class name from `vmimage.status.storageClassName`.

**To Reproduce**
1. Install a new harvester cluster with https://github.com/harvester/harvester/pull/5459.
2. Create a VMImage and VM.
3. VM PVC can't be provisioned cause of storage class not found.

**Expected behavior**
VM can run.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 2 nodes + 1 witness**
* Harvester Version: **v1.4.0-dev-20240918**
* **ui-source** Option: **Auto**

### Verify Steps
1. same as https://github.com/harvester/harvester/issues/5584#issuecomment-2092604751
