### ISSUE TITLE
[ENHANCEMENT] Bump LH to v1.5.5 in Harvester v1.2

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5553]

**Comment by albinsun** [comment]
Verified done on `v1.2-6d0fc357-head`, close ticket.


## Environment
* Harvester
  * Version: `v1.2-6d0fc357-head`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> Go to "Preferences" -> Check "Enable Extension developer features" 
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f1ea92f9-1382-4ec1-b40a-50847485496e)
   </details>

2. <details>
   <summary> Go to "Support" -> "Access Embedded Longhorn UI"
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/406a718b-95ca-47c2-b3f1-4ec5b9008bd7)

   ![image](https://github.com/harvester/harvester/assets/2773781/302ef0ae-222a-4f5c-aadf-1192702f2ca1)
   </details>

2. <details open>
   <summary> Go to "Setting" -> "General", check <b>Current Longhorn Version</b> is <code>v1.5.5</code>
   </summary>
 
   ![image](https://github.com/harvester/harvester/assets/2773781/f5e89452-3763-4879-9abd-2b8d02f3c41c)
   </details>

**Comment by khushboo-rancher** [comment]
@albinsun No unexpected failures on e2e CI, right?
