### ISSUE TITLE
[Doc] Update the harvester wiki "Development Best Practices" to include structured logging conventions

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5564]
**Is your doc request related to a problem? Please describe or add related issue ID.**

Consistency in field keys and structure increases the utility of structured logging.

**Describe the solution you'd like**

Let's make the "Development Best Practices" page the single source of truth for which structured logging packages Harvester projects prefer, as well as any logging keys that are applicable across code bases (such as the ones proposed in the HEP as well as any others that end up surfacing during implementation/refactoring).

Related HEP: https://github.com/harvester/harvester/pull/5474

**Comment by m-ildefons** [comment]
Done:
https://github.com/harvester/harvester/wiki/Development-Best-Practices#structured-logging
