### ISSUE TITLE
[Question] Troubleshoot NIC connection speed between nodes

### ISSUE THREAD

**Issue by ctft1** [harvester/harvester#5565]
Hi,

I'm pretty new to Harvester, currently only trying to have a quick setup to evaluate it with a 3 nodes cluster. Each node has a 2x100 Gb network card (Intel E810), but when trying to setup a 2 VM on 2 different nodes, I can only get 10-11 Gb connection speed between (with VirtIO adapters)

What is the correct way to troubleshoot NICs on Harvester ? Is there a way to test physical link speed at the node level ? I usually use iperf (multithreaded) but here Harvester seems to have a very different way to handle the physical NICs (which is pretty logical as there are some features added on top of them)

Thank you!

**Comment by ctft1** [comment]
Some complementary information : my idea would be to conduct some tests for the real base link speed (as with iperf for example), but from the node themself and not the VM (to avoid any other issue). 

For what I've read Intel E810 cards can sometimes be slow with the kernel default driver (which can be upgraded with the Intel ICE version), but here we are 10x less. Also sometimes there can be hardware issues,  especially at this 100Gb/s speed (switch, bad DAC cable or adapter, ...)

Right now I checked with Ethtool, and my cards are UP and negociated a 100000Mb speed (which is fine). 
So now my idea would be to further test with a node to node connection test

**Comment by bk201** [comment]
cc @mingshuoqiu 
@ctft1 I'd Are you running VMs with the default management network (that is, no VLAN involved)? If yes, I'd try iperf to test the pod network https://www.suse.com/support/kb/doc/?id=000020954. The pod network is an overlay network build with flannel (VxLan), there is some overhead due to encapsulation. But I don't feel the performance should degrade so much.

**Comment by ctft1** [comment]
The management network was orignilly setup with a dedicated RJ45 (1Gb) NIC, so no.

The VMs are connected through an UntaggedNetwork configured as a Cluster Network only with 2 NICs (1 NIC for each node) at the moment. But as I know there may be some specific issues with this additional config, that's why I would prefer to ensure the network can reach it's full speed at the node level first.

Right now I removed some other Network Cluster config (to get back the 100Gb NIC as "master" (not SLAVE) on the node, then added an IP address on those NICs on those 2 nodes. I can ping, but it seems iperf was removed from the default tools (and I cannot install it as the OS is mounted as read-only if I'm right)

Maybe iperf was replaced with another tool ? Or maybe there are some diag tools for this on Harvester ? (I'm running v1.3.0)

**Comment by mingshuoqiu** [comment]
iperf3 is good enough.

Since there will be a software bridge for each Cluster Network, I'll suggest to test the end-to-end traffic between the Node first to verify the network speed of the physical layer.
If the throughput looks good, then we can verify the speed between nodes to see if there's any overhead introduced.
Please share your network topology between nodes with us, we'll try to find out the bottleneck.

**Comment by bk201** [comment]
@ctft1 iperf is not shipped with the OS, and it's not easy to install it because it's an immutable system. You can try use a toolbox container: https://harvesterhci.io/kb/package_your_own_toolbox_image/

**Comment by ctft1** [comment]
Thank you both. I totally agree that I should first check at the lowest lovel (node)

What I also did is bypassing the PCIE NIC cards to the VMs. That's not perfect as I guess there is still some overhead / different interrupts management / ... but it gave me an idea that something may be wrong with the NIC config or even hardware setup as I cannot go over 35 Gbit/s with 1500 MTU , and ~45 Gbit/s with 9000... This also allowed me to test with the Intel ICE driver (not the kernel one) but this is almost the same bandwidth

That's great for the toolbox container, I will try this solution ASAP, as it would be the correct way to process directly from the node.

**Comment by ctft1** [comment]
I have a newbie question: I created my Toolbox Dockerfile as described here https://harvesterhci.io/kb/package_your_own_toolbox_image/

When in the Dockerfile directory and trying to run `docker build -t harvester/toolbox:dev .`

I'm getting either, as non-root user:

```
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
WARN[0000] environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
FATA[0000] rootless containerd not running? (hint: use `containerd-rootless-setuptool.sh install` to start rootless containerd): environment variable XDG_RUNTIME_DIR is not set, see https://rootlesscontaine.rs/getting-started/common/login/
```


Or as root user (sudo -i):

```
ERRO[0000] `buildctl` needs to be installed and `buildkitd` needs to be running, see https://github.com/moby/buildkit  error="3 errors occurred:\n\t* failed to ping to host unix:///run/buildkit-k8s.io/buildkitd.sock: exec: \"buildctl\": executable file not found in $PATH\n\t* failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exec: \"buildctl\": executable file not found in $PATH\n\t* failed to ping to host unix:///run/buildkit/buildkitd.sock: exec: \"buildctl\": executable file not found in $PATH\n\n"
FATA[0000] no buildkit host is available, tried 3 candidates: 3 errors occurred:
        * failed to ping to host unix:///run/buildkit-k8s.io/buildkitd.sock: exec: "buildctl": executable file not found in $PATH
        * failed to ping to host unix:///run/buildkit-default/buildkitd.sock: exec: "buildctl": executable file not found in $PATH
        * failed to ping to host unix:///run/buildkit/buildkitd.sock: exec: "buildctl": executable file not found in $PATH
```

Is there a first step to complete before running this Docker command?
Or maybe a specific folder location for the Dockerfile?

**Comment by starbops** [comment]
@ctft1 If you have another machine that runs Docker, you might want to build the toolbox image there instead of directly on the Harvester node. After the container image is constructed and pushed, run the container (the `docker run` command) on the Harvester node to start the diagnosis.

**Comment by ctft1** [comment]
Thank you! I could create my container and run it from the node. I just have a question about the network. I've seen I can use "--network host" or "--net=host" params when running the container to make the container use the host connection.

Does anyone know if there is some overhead for that, or is it a kind of direct pass-through? (it's important to understand this point as I plan to run network bandwidth tests)

**Comment by mingshuoqiu** [comment]
It's a direct pass-through and I think the overhead should be minor.

**Comment by ctft1** [comment]
Ok perfect, thank you, that was helpful to be able to perform iperf tests. I finally found the speed issue was related to a modified BIOS parameter ("memory interleave" had been disabled)

**Comment by bk201** [comment]
> Ok perfect, thank you, that was helpful to be able to perform iperf tests. I finally found the speed issue was related to a modified BIOS parameter ("memory interleave" had been disabled)

@ctft1 Thanks for sharing the cause! @mingshuoqiu we can collect tips like this to KB articles.
