### ISSUE TITLE
Harvester 1.3.0 install stuck on setting up node.  Why "Network unreachable" for Rancher System Agent?

### ISSUE THREAD

**Issue by dg1sbg** [harvester/harvester#5575]
PROBLEM:

Harvester 1.3.0 installaction is stuck bringing up the node with a Network Unreachable error when starting Rancher System Agent.

LOG EXCERPT:

Apr 12 18:15:23 goedes01 systemd[1]: Started Rancher System Agent.
Apr 12 18:15:23 goedes01 rancher-system-agent[42796]: time="2024-04-12T18:15:23Z" level=info msg="Rancher System Agent version v0.3.4 (63eb11a) is starting"
Apr 12 18:15:23 goedes01 rancher-system-agent[42796]: time="2024-04-12T18:15:23Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Apr 12 18:15:23 goedes01 rancher-system-agent[42796]: time="2024-04-12T18:15:23Z" level=info msg="Starting remote watch of plans"
_________________ ERROR MSG BELOW _________________
Apr 12 18:15:23 goedes01 rancher-system-agent[42796]: time="2024-04-12T18:15:23Z" level=fatal msg="error while connecting to Kubernetes cluster: Get \"https://10.53.151.2/version\": dial tcp 10.53.151.2:443: connect: network is unreachable"
_____________________________________________________

Apr 12 18:15:23 goedes01 systemd[1]: ^[[0;1;39m^[[0;1;31m^[[0;1;39mrancher-system-agent.service: Main process exited, code=exited, status=1/FAILURE
Apr 12 18:15:23 goedes01 systemd[1]: ^[[0;1;38;5;185m^[[0;1;39m^[[0;1;38;5;185mrancher-system-agent.service: Failed with result 'exit-code'.

Please see attached exptended log file with sytem information.

QUESTION:

I am unaware of any command setting up a 10.53.0.0/16 network udring installation. I do see anaother network, 10.52.0.0/24 being active and seemingly doing ok.

Did I miss any network setup during instrallation? I used just standard selections and all static IP addresses for VIP and node.

Thanks for any hints and advice.

Regards
   Frank

[install.log.gz](https://github.com/harvester/harvester/files/14962494/install.log.gz)

**Comment by dg1sbg** [comment]
ADDITIONAL INFO:

When looking for services that use an 10.53.0.0/16 IP address I found that several services use `--service-cluster-ip-range=10.53.0.0/16` as a parameter:

rancher@goedes01:~> ps aux | grep "10.53"

root      3370  4.7  0.0 842428 125248 ?       Sl   08:02  11:43 kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins --file-check-frequency=5s --sync-frequency=30s --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.53.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock --eviction-hard=imagefs.available<5%,nodefs.available<5% --eviction-minimum-reclaim=imagefs.available=10%,nodefs.available=10% --fail-swap-on=false --feature-gates=CloudDualStackNodeIPs=true --healthz-bind-address=127.0.0.1 --hostname-override=goedes01 --kubeconfig=/var/lib/rancher/rke2/agent/kubelet.kubeconfig --max-pods=200 --node-ip=192.168.2.21 --node-labels=rke.cattle.io/machine=e1984bf4-9774-4535-9473-23407fe2eb6d --pod-infra-container-image=index.docker.io/rancher/mirrored-pause:3.6 --pod-manifest-path=/var/lib/rancher/rke2/agent/pod-manifests --read-only-port=0 --resolv-conf=/etc/resolv.conf --serialize-image-pulls=false --tls-cert-file=/var/lib/rancher/rke2/agent/serving-kubelet.crt --tls-private-key-file=/var/lib/rancher/rke2/agent/serving-kubelet.key

root      3626  4.6  0.3 1259780 460332 ?      Ssl  08:02  11:30 kube-apiserver --admission-control-config-file=/etc/rancher/rke2/rke2-pss.yaml --audit-policy-file=/etc/rancher/rke2/config.yaml.d/92-harvester-kube-audit-policy.yaml --audit-log-maxage=30 --audit-log-maxbackup=10 --audit-log-maxsize=100 --audit-log-path=/var/lib/rancher/rke2/server/logs/audit.log --allow-privileged=true --anonymous-auth=false --api-audiences=https://kubernetes.default.svc.cluster.local,rke2 --authorization-mode=Node,RBAC --bind-address=0.0.0.0 --cert-dir=/var/lib/rancher/rke2/server/tls/temporary-certs --client-ca-file=/var/lib/rancher/rke2/server/tls/client-ca.crt --egress-selector-config-file=/var/lib/rancher/rke2/server/etc/egress-selector-config.yaml --enable-admission-plugins=NodeRestriction --enable-aggregator-routing=true --enable-bootstrap-token-auth=true --encryption-provider-config=/var/lib/rancher/rke2/server/cred/encryption-config.json --etcd-cafile=/var/lib/rancher/rke2/server/tls/etcd/server-ca.crt --etcd-certfile=/var/lib/rancher/rke2/server/tls/etcd/client.crt --etcd-keyfile=/var/lib/rancher/rke2/server/tls/etcd/client.key --etcd-servers=https://127.0.0.1:2379 --kubelet-certificate-authority=/var/lib/rancher/rke2/server/tls/server-ca.crt --kubelet-client-certificate=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.crt --kubelet-client-key=/var/lib/rancher/rke2/server/tls/client-kube-apiserver.key --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname --profiling=false --proxy-client-cert-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.crt --proxy-client-key-file=/var/lib/rancher/rke2/server/tls/client-auth-proxy.key --requestheader-allowed-names=system:auth-proxy --requestheader-client-ca-file=/var/lib/rancher/rke2/server/tls/request-header-ca.crt --requestheader-extra-headers-prefix=X-Remote-Extra- --requestheader-group-headers=X-Remote-Group --requestheader-username-headers=X-Remote-User --secure-port=6443 --service-account-issuer=https://kubernetes.default.svc.cluster.local --service-account-key-file=/var/lib/rancher/rke2/server/tls/service.key --service-account-signing-key-file=/var/lib/rancher/rke2/server/tls/service.current.key --service-cluster-ip-range=10.53.0.0/16 --service-node-port-range=30000-32767 --storage-backend=etcd3 --tls-cert-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.crt --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --tls-private-key-file=/var/lib/rancher/rke2/server/tls/serving-kube-apiserver.key

root      3848  1.4  0.0 839356 131228 ?       Ssl  08:02   3:27 kube-controller-manager --flex-volume-plugin-dir=/var/lib/kubelet/volumeplugins --terminated-pod-gc-threshold=1000 --permit-port-sharing=true --allocate-node-cidrs=true --authentication-kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --authorization-kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --bind-address=127.0.0.1 --cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager --cluster-cidr=10.52.0.0/16 --cluster-signing-kube-apiserver-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.nochain.crt --cluster-signing-kube-apiserver-client-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --cluster-signing-kubelet-client-cert-file=/var/lib/rancher/rke2/server/tls/client-ca.nochain.crt --cluster-signing-kubelet-client-key-file=/var/lib/rancher/rke2/server/tls/client-ca.key --cluster-signing-kubelet-serving-cert-file=/var/lib/rancher/rke2/server/tls/server-ca.nochain.crt --cluster-signing-kubelet-serving-key-file=/var/lib/rancher/rke2/server/tls/server-ca.key --cluster-signing-legacy-unknown-cert-file=/var/lib/rancher/rke2/server/tls/server-ca.nochain.crt --cluster-signing-legacy-unknown-key-file=/var/lib/rancher/rke2/server/tls/server-ca.key --configure-cloud-routes=false --controllers=*,tokencleaner,-service,-route,-cloud-node-lifecycle --kubeconfig=/var/lib/rancher/rke2/server/cred/controller.kubeconfig --profiling=false --root-ca-file=/var/lib/rancher/rke2/server/tls/server-ca.crt --secure-port=10257 --service-account-private-key-file=/var/lib/rancher/rke2/server/tls/service.current.key --service-cluster-ip-range=10.53.0.0/16 --use-service-account-credentials=true

**Comment by w13915984028** [comment]
The `10.53.151.2` is a cluster internal service IP, it is not configured by user manually but automatically.

We need more information to check, thanks.
* Is this the first node of your cluster, and it failed to setup after the installation ?
* How is it installed, by ISO or PXE?
* Node IP, static or DHCP ? if DHCP, is it binded to MAC in DHCP-server side?
* VIP/Management IP, static or DHCP?
* Is http_proxy configured? (step 12 on https://docs.harvesterhci.io/v1.3/install/index)
* try to execute `sudo -i kubectl get pods -A` on your node
* `cat /oem/*harvester*.cfg`

**Comment by dg1sbg** [comment]
Hi @w13915984028 -

Thanks for taking the time to look into this. My issue/ question is related to [issue 5579](https://github.com/harvester/harvester/issues/5579).  After fixing this issue the problem with the 10.53.0.0/16 net went away and the cluster now runs as expected.

I think we should close this issue.

Thanks again!

Best,
    Frank
