### ISSUE TITLE
[BUG] Failing to install master chart

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#558]
**To Reproduce**
1. Deploy Harvester in app mode, use the chart in the master branch

**Expected behavior**
Deployment succeeds

**Result**
Failed to install app harvester-system. Error: failed post-install: unable to build kubernetes object for post-install hook harvester/templates/longhorn-storageclass-override.yaml: error validating "": error validating data: apiVersion not set
![image](https://user-images.githubusercontent.com/5697937/112255429-2006c200-8c9d-11eb-820f-9906756ab00c.png)

**Comment by kingsd041** [comment]
Validation Version：
master-67244e23-head

Use the default config to launch the harvester through the app mode, and the harvester successfully launches
