### ISSUE TITLE
ARM64 Support - does this incude raspberry pi ?

### ISSUE THREAD

**Issue by mkocaks** [harvester/harvester#5590]
I understand with release 1.3.0 there is support for arm64, is this supported on raspberry pi's ?

**Comment by mkocaks** [comment]
Hi, I would love to start using harvester and stop using proxmox or esxi however you can run these on raspberry pi's which I have amples of and is enough fo rmy lab work.
However I am confused about the recent feature support for arm64 - if this can work on raspberrypi's can anyone provide a guide on how to perform the install to the pi as the usb bootable fails to boot for the arm64 iso image on a pi...
There are ways to hack around it which I have not tried so thought incase I am missing something obvious would post here before I probably end up bricking one of my pi's :-D
https://www.eisfunke.com/posts/2023/uefi-boot-on-raspberry-pi-3.html#:~:text=Download%20the%20latest%20release%20of,interface%20of%20the%20UEFI%20firmware.

**Comment by ibrokethecloud** [comment]
we have not tried to install harvester on arm, and that was not the original use case either. with arm builds we were targeting more powerful arm hardware like ampere altra based machines.

**Comment by mkocaks** [comment]
Ah! I misunderstood so no plans for raspberry pi images then ? Would be pretty cool if you could

**Comment by mkocaks** [comment]
I am more than happy to help test etc...

**Comment by mkocaks** [comment]
So these images are only for specific arm hardware ?
https://releases.rancher.com/harvester/v1.3.0/harvester-v1.3.0-arm64.iso

**Comment by mkocaks** [comment]
![image](https://github.com/harvester/harvester/assets/87523722/5c567a71-354e-4945-9c7a-b24da11db7a6)

**Comment by mkocaks** [comment]
@ibrokethecloud Sorry buddy do you haev any feedback on the above - in theroy with the uefi hack on the pi I think it shoudl work but maybe I still dont get what these images are for ?

**Comment by connorkuehl** [comment]
> @ibrokethecloud Sorry buddy do you haev any feedback on the above - in theroy with the uefi hack on the pi I think it shoudl work but maybe I still dont get what these images are for ?

They're intended for ARM-based machines that meet the Harvester minimum requirements: https://docs.harvesterhci.io/v1.3/install/requirements#hardware-requirements

**Comment by mkocaks** [comment]
@connorkuehl  Thank you, I ended up installing harvester on a single 8GB Pi using this https://github.com/pftf/RPi4
But your right...after too much time to get drivers and other dependencies (or attempted at least) to support things like pwm fan control for the poe hat (the Pi heated to such a degree I had to cool it constantly using an external fan :-D) - in the end the Pi is too low powered to run anything like this at some reasonable and acceptable levels.
Will dig out my old hpz620 that has 24 cores and 96GB of RAM from the garage :-D

**Comment by mkocaks** [comment]
Will check back from time to time just in case you guys release a "Harvester Pi Lite" version (Joke) :-D

**Comment by innobead** [comment]
Closing as this is not the priority or plan for now. Would like to see more feedback in the future.
