### ISSUE TITLE
[ENHANCEMENT] [v1.2] Bump RKE2 to v1.26.15+rke2r1

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5596]
**Is your enhancement related to a problem? Please describe.**

We should catch up the latest RKE2 release.

**Describe the solution you'd like**

Bump RKE2 to v1.26.15+rke2r1

**Describe alternatives you've considered**

**Additional context**

**Comment by albinsun** [comment]
Verified done on `v1.2-6d0fc357-head`, close ticket.


## Environment
* Harvester
  * Version: `v1.2-6d0fc357-head`
  * Profile: QEMU/KVM, 2 nodes (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> Go to "Preferences" -> Check "Enable Extension developer features" 
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/f1ea92f9-1382-4ec1-b40a-50847485496e)
   </details>

2. <details>
   <summary> Go to "Support" -> "Access Embedded Rancher UI"
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/406a718b-95ca-47c2-b3f1-4ec5b9008bd7)

   ![image](https://github.com/harvester/harvester/assets/2773781/521dd78b-bbd1-43bf-b08b-7c91b36a32fd)
   </details>

2. <details open>
   <summary> Go to "Nodes", check nodes' RKE2 version is <code>v1.26.15+rke2r1</code>
   </summary>
 
   ![image](https://github.com/harvester/harvester/assets/2773781/f2ec7c7f-d60d-46cc-9712-e90f4aa3fbf5)
   </details>
