### ISSUE TITLE
[BUG] Harvester cluster stuck in all nodes maintenance mode

### ISSUE THREAD

**Issue by codot-fr** [harvester/harvester#5598]
**Describe the bug**
Due to a power maintenance I had to shutdown the harvester cluster. Doing so I put all four nodes in maintenance mode.
Now that the nodes have rebooted, I can't get them out of maintenance mode.

NAME          STATUS                     ROLES                       AGE    VERSION
harvester01   Ready,SchedulingDisabled   control-plane,etcd,master   417d   v1.25.9+rke2r1
harvester02   Ready,SchedulingDisabled   <none>                      417d   v1.25.9+rke2r1
harvester03   Ready,SchedulingDisabled   control-plane,etcd,master   417d   v1.25.9+rke2r1
harvester04   Ready,SchedulingDisabled   control-plane,etcd,master   417d   v1.25.9+rke2r1

Trying to uncordon won't work:

harvester01:~ # kubectl uncordon harvester01
error: unable to uncordon node "harvester01": Internal error occurred: failed calling webhook "validator.harvesterhci.io": failed to call webhook: Post "https://harvester-webhook.harvester-system.svc:443/v1/webhook/validation?timeout=10s": no endpoints available for service "harvester-webhook"

**Environment**
 - Harvester ISO version:  1.2.1

**Comment by codot-fr** [comment]
harvester01:~ # kubectl describe service harvester-webhook -n harvester-system
Name:              harvester-webhook
Namespace:         harvester-system
Labels:            app.kubernetes.io/managed-by=Helm
                   objectset.rio.cattle.io/hash=e852fa897f5eae59a44b4bfe186aad80b10b94b3
Annotations:       meta.helm.sh/release-name: harvester
                   meta.helm.sh/release-namespace: harvester-system
                   objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
Selector:          app.kubernetes.io/component=webhook-server,app.kubernetes.io/name=harvester
Type:              ClusterIP
IP Family Policy:  SingleStack
IP Families:       IPv4
IP:                10.53.233.43
IPs:               10.53.233.43
Port:              https  443/TCP
TargetPort:        9443/TCP
Endpoints:         <none>
Session Affinity:  None
Events:            <none>

**Comment by codot-fr** [comment]
```
harvester01:~ # kubectl get pod -n harvester-system --selector=app.kubernetes.io/name=harvester
NAME                                 READY   STATUS    RESTARTS   AGE
harvester-6cd46946d6-tjktv           0/1     Pending   0          3d18h
harvester-6cd46946d6-tvdb2           0/1     Pending   0          3d18h
harvester-6cd46946d6-wvplf           0/1     Pending   0          3d18h
harvester-webhook-666ff99847-d59n7   0/1     Pending   0          3d18h
harvester-webhook-666ff99847-gchqd   0/1     Pending   0          3d18h
harvester-webhook-666ff99847-x6sbg   0/1     Pending   0          3d18h


harvester01:~ # kubectl describe pod harvester-webhook-666ff99847-d59n7 -n harvester-system
Name:             harvester-webhook-666ff99847-d59n7
Namespace:        harvester-system
Priority:         0
Service Account:  harvester
Node:             <none>
Labels:           app.kubernetes.io/component=webhook-server
                  app.kubernetes.io/managed-by=Helm
                  app.kubernetes.io/name=harvester
                  app.kubernetes.io/part-of=harvester
                  app.kubernetes.io/version=v1.2.1
                  helm.sh/chart=harvester-1.2.1
                  helm.sh/release=harvester
                  pod-template-hash=666ff99847
Annotations:      container.apparmor.security.beta.kubernetes.io/harvester-webhook: unconfined
Status:           Pending
IP:
IPs:              <none>
Controlled By:    ReplicaSet/harvester-webhook-666ff99847
Containers:
  harvester-webhook:
    Image:      rancher/harvester-webhook:v1.2.1
    Port:       9443/TCP
    Host Port:  0/TCP
    Environment:
      HARVESTER_WEBHOOK_SERVER_HTTPS_PORT:  9443
      NAMESPACE:                            harvester-system (v1:metadata.namespace)
      HARVESTER_DEBUG:                      false
      HARVESTER_CONTROLLER_USER_NAME:       system:serviceaccount:harvester-system:harvester
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-x2kj9 (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  kube-api-access-x2kj9:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  59m (x248 over 21h)  default-scheduler  0/4 nodes are available: 4 node(s) were unschedulable. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
  Warning  FailedScheduling  2s (x11 over 51m)    default-scheduler  0/4 nodes are available: 4 node(s) were unschedulable. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```


I can't uncordon because harvester-webhook is down but harvester-webhook is down because all the nodes are cordonned...

**Comment by w13915984028** [comment]
Try to delete `ValidatingWebhookConfiguration` `harvester-validator`, then uncordon.

```
$ kubectl get ValidatingWebhookConfiguration -A
NAME                                    WEBHOOKS   AGE
..
harvester-validator                     1          21d
..

$ kubectl get MutatingWebhookConfiguration
NAME                              WEBHOOKS   AGE
..
harvester-mutator                 1          21d

```

**Comment by codot-fr** [comment]
Done, but it keeps reverting back to cordoned after a while. harvester-validator respawn and put them back in maintenance I guess. What should I do with harvester-mutator?

**Comment by codot-fr** [comment]
As per https://github.com/harvester/harvester/issues/4834, I removed the harvesterhci.io/drain-requested: true annotation from the nodes. I'm rebooting all the nodes to see if it fixes the issue.

**Comment by codot-fr** [comment]
It did fix the issue, everything restarted properly. Thanks for the help.

**Comment by w13915984028** [comment]
@codot-fr We close the issue, feel free to reopen. Thanks.
