### ISSUE TITLE
[BUG] Available memory reported in preflight checks is lower than physical system RAM

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#5599]
**Describe the bug**
The preflight memory check uses `MemTotal` from `/proc/meminfo` to try to figure out how much RAM there is. This figure will always be a bit less than the actual amount of memory installed in the system. This results in a couple of kinks:

1. The amount of memory shown in the warning can be surprising (e.g. "Only 7GiB RAM detected" on a system you know has 8GiB installed).
2. We have to allow some wiggle room when checking to ensure there's enough memory for production use. The current implementation allows 5%, which means if `MemTotal` is at least `63753420 kB` (i.e. 64 * 1024 * 1024 * 0.95 == 60.8GiB), we assume the system has 64GiB RAM. But, I've had one report of someone with _just_ under that amount, i.e. 60GiB and the check failing.

**To Reproduce**
Run the installer with < 64GiB RAM. Observe that the warning messages show a GiB or two less than the physical system memory.

**Expected behavior**
The detected memory is actually exactly the same as the physical memory in the system.

**Environment**
 - Harvester ISO version: 1.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

A possible fix may be to use `dmidecode` instead of `/proc/meminfo`, e.g. on my 64GiB desktop system running `dmidecode -t 19` gives:

```
# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0034, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x00FFFFFFFFF
	Range Size: 64 GB
	Physical Array Handle: 0x002F
	Partition Width: 8
```

Note that this will still require some messing around, because you don't always get one convenient chunk of output. Here's a couple of other examples:

1. A VM with 8GiB RAM:

```
# dmidecode 3.4
Getting SMBIOS data from sysfs.
SMBIOS 3.0.0 present.

Handle 0x1300, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00000000000
	Ending Address: 0x0007FFFFFFF
	Range Size: 2 GB
	Physical Array Handle: 0x1000
	Partition Width: 1

Handle 0x1301, DMI type 19, 31 bytes
Memory Array Mapped Address
	Starting Address: 0x00100000000
	Ending Address: 0x0027FFFFFFF
	Range Size: 6 GB
	Physical Array Handle: 0x1000
	Partition Width: 1
```

2. A system with 512GiB RAM:

```
# dmidecode 3.5
Getting SMBIOS data from sysfs.
SMBIOS 2.8 present.

Handle 0x0024, DMI type 19, 31 bytes
Memory Array Mapped Address
        Starting Address: 0x00000000000
        Ending Address: 0x0007FFFFFFF
        Range Size: 2 GB
        Physical Array Handle: 0x000A
        Partition Width: 1

Handle 0x0025, DMI type 19, 31 bytes
Memory Array Mapped Address
        Starting Address: 0x0000000100000000k
        Ending Address: 0x000000807FFFFFFFk
        Range Size: 510 GB
        Physical Array Handle: 0x000B
        Partition Width: 1
```

**Comment by irishgordo** [comment]
@tserong thanks for this fix :smile: :+1:  - this all looks good - I'll go ahead and close this out :smile: 

### Environment
* Harvester
  * Version: Harvester-v1.4-20240923 /  Version: v1.4-97e60e1-head 
  * Profile: QEMU/KVM
  * ui-source: Auto


### Verification
### 1 Node Cluster
1. :green_circle: All RAM Values Reflect Accurately
   
   <details>
   <summary> <i>Given</i> Certain RAM Values Exist
   </summary>
         <ul>
          <li>our installer preflight checks should reflect those values</li>
          </ul>
   
      ![Screenshot from 2024-09-30 11-05-52](https://github.com/user-attachments/assets/b0111ca6-fd8f-4c1e-9714-5d56d49ffc72)
      ![Screenshot from 2024-09-30 11-04-26](https://github.com/user-attachments/assets/21108ecc-aa2e-4b59-b1e3-35a9ad926e44)
      ![Screenshot from 2024-09-30 10-40-54](https://github.com/user-attachments/assets/8d016b14-c93f-4983-bff7-da349bf791a7)
      ![Screenshot from 2024-09-30 10-37-58](https://github.com/user-attachments/assets/07ac79e4-a22d-4c5f-82ec-6081933a9f1d)
      ![Screenshot from 2024-09-30 10-37-17](https://github.com/user-attachments/assets/48ff192f-f959-4148-85e3-7c2a5e643024)
      ![Screenshot from 2024-09-30 10-36-27](https://github.com/user-attachments/assets/d94aa1df-ae2b-4325-a854-2c80ebe43bb9)
