### ISSUE TITLE
[Doc] Document when Live Migration might fail because of CPU model/features and suggest way to work it around.

### ISSUE THREAD

**Issue by belgaied2** [harvester/harvester#5603]
**Is your doc request related to a problem? Please describe or add related issue ID.**
Live Migration fails if target machine is not compatible with CPU model/features. For instance, if a VM is first scheduled on a node using `Icelake` Xeon CPU, it cannot be live migrated to a node using a `Cascadelake` Xeon CPU even if the VM does not make use of the `Icelake` features.
Issues:
- #3015 
- #3762 

**Describe the solution you'd like**
The problem appears very often if nodes with different generations of CPUs are present. But it is documented nowhere. It should explicitely appear in the Live Migration page, mentioning:
- Why it is happening (Kubevirt automatically uses `host-model` by default for each new VM after it being scheduled)
- Why CPU model is important for Live Migration (for successful migrations if the initial VM uses specific CPU features) and why the operator should understand what he is doing.
- How to override CPU Model: at the VMI level, and [at the cluster level](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#enabling-default-cluster-cpu-model) 
- How to override CPU feature: [only possible at the VMI level right now](https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#features). It should also be mentioned that Kubevirt works on [future support of cluster-wide cpu feature configuration](https://github.com/kubevirt/kubevirt/pull/11407).

**Comment by armagankaratosun** [comment]
Hello @belgaied2 

Since I opened one of the two issues pointing to this problem, would you like me to help with the documentation? maybe under a subchapter called "Known issues" here https://github.com/harvester/docs/blob/main/versioned_docs/version-v1.3/vm/live-migration.md? 

Feel free to assign me to this issue if you think this is a good idea. Cheers!

**Comment by bk201** [comment]
@armagankaratosun I guess we missed this comment. Are you still able to help contribute to the document?

**Comment by armagankaratosun** [comment]
Hello @bk201 , sorry for the late response.  Sure, I would be glad to help!

**Comment by Yu-Jack** [comment]
Document is updated and published, please check following sections.

- [v1.4] Hardware Requirements: [CPU Specifications](https://docs.harvesterhci.io/v1.4/install/requirements/#cpu-specifications) | Live Migration: [How Migration Works](https://docs.harvesterhci.io/v1.4/vm/live-migration/#how-migration-works) + [Limitation](https://docs.harvesterhci.io/v1.4/vm/live-migration/#limitation)
- [v1.3] Hardware Requirements: [CPU Specifications](https://docs.harvesterhci.io/v1.3/install/requirements/#cpu-specifications) | Live Migration: [How Migration Works](https://docs.harvesterhci.io/v1.3/vm/live-migration/#how-migration-works) + [Limitation](https://docs.harvesterhci.io/v1.3/vm/live-migration#limitation)
- [v1.2] Hardware Requirements: [CPU Specifications](https://docs.harvesterhci.io/v1.2/install/requirements#cpu-specifications) | Live Migration: [How Migration Works](https://docs.harvesterhci.io/v1.2/vm/live-migration#how-migration-works) + [Limitation](https://docs.harvesterhci.io/v1.2/vm/live-migration#limitation)
