### ISSUE TITLE
[BUG] vGPU page doesn't show a title on install

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5604]
**Describe the bug**

When you navigate to the vGPU page in the advanced settings it doesn't have a title, just a question mark

**To Reproduce**
1. Deploy a new Harvester Cluster
2. Sign in
3. Navigate to the vGPU page in advanced settings

**Expected behavior**

There should be a title on the page
There should be a title

**Support bundle**

[supportbundle_7e6677cc-a04f-452b-8ffe-0239ef4904f2_2024-04-16T16-30-48Z.zip](https://github.com/harvester/harvester/files/14999875/supportbundle_7e6677cc-a04f-452b-8ffe-0239ef4904f2_2024-04-16T16-30-48Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node ipxe-examples libvirt deploy

**Additional context**
If you enable the PCI devices addon it then has the title on the page. It seems like maybe some of the UI assets aren't there. We should either have the title show up on install or hide the vGPU page the way that we hide the SR-IOV GPU page until you enable the addons.

![Screenshot_20240416_092811](https://github.com/harvester/harvester/assets/83787952/e11bb6d5-17ac-4ecb-b0d2-deadc2aa7a2e)

**Comment by khushboo-rancher** [comment]
Verified on 1.4.0-rc2

Validation - Passed

The title is present as shown in the screenshot.
<img width="1184" alt="Screenshot 2024-10-15 at 3 28 48 PM" src="https://github.com/user-attachments/assets/17efc5f4-703a-4ef9-91e7-239d8a9253e2">
