### ISSUE TITLE
[BUG] Can't add node to the cluster network because NIC name doesn't match

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#5605]
1st node
=====
Installed Harvester 1.3.0 on first node (baremetal DELL T7820), which has NIC with 4 ports (I'm using only 2):
```
2: enp147s0f0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP mode DEFAULT group default qlen 1000
    link/ether 34:80:0d:c3:55:64 brd ff:ff:ff:ff:ff:ff
3: enp147s0f1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 34:80:0d:c3:55:65 brd ff:ff:ff:ff:ff:ff
4: enp147s0f2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether 34:80:0d:c3:55:66 brd ff:ff:ff:ff:ff:ff
5: enp147s0f3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master cn2-bo state UP mode DEFAULT group default qlen 1000
    link/ether 34:80:0d:c3:55:67 brd ff:ff:ff:ff:ff:ff
```
I have cluster management network on `enp147s0f0`:
```
    managementinterface:
        interfaces:
            - name: enp147s0f0
              hwaddr: 34:80:0d:c3:55:64
```
Created cluster network `cn2` on `enp147s0f3`
Created network config `nc2`

Everything works, no issues

2nd node
======
Installed Harvester 1.3.0 on second node (VM) - `ds1621`, which has 2 NICs
```
2: ens3: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast master mgmt-bo state UP mode DEFAULT group default qlen 1000
    link/ether 02:11:32:2a:16:9a brd ff:ff:ff:ff:ff:ff
    altname enp0s3
3: ens4: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether 02:11:32:25:84:e0 brd ff:ff:ff:ff:ff:ff
    altname enp0s4
```
The node joined the cluster.
`ens3` used for cluster management network:
```
    managementinterface:
        interfaces:
            - name: ens3
              hwaddr: 02:11:32:2a:16:9a
```
However, when I'm looking at the network config `nc2` in UI, I see this message:
> NIC "enp147s0f3" is not available on the selected nodes

Apparently that's because my 2nd node has `ens4`, not `enp147s0f3`

BUG? 
====
Does that mean, that to install Harvester cluster I need somehow to ensure, that NIC names match between nodes?

Is it possible to rename NIC?

Or is it possible to have networks config, which can have different names on different nodes?

WORKAROUND?
==========
I tried to rename NIC, according to suggestion in this [message](https://github.com/harvester/harvester/issues/4591#issuecomment-1752759181)

vi /etc/udev/rules.d/70-persistent-ipoib.rules

ACTION=="add", SUBSYSTEM=="net", ATTR{address}=="02:11:32:25:84:e0", NAME="enp147s0f3"

But when I reboot, the file is overwritten and my changes are gone.

I tried to use different name - /etc/udev/rules.d/99-custom-net-names.rules
Same thing - it get's deleted.

Any other workaround?

**Comment by connorkuehl** [comment]
> Does that mean, that to install Harvester cluster I need somehow to ensure, that NIC names match between nodes?

Not necessarily. 
 
> Or is it possible to have networks config, which can have different names on different nodes?

Yeah, this. You can create 1 cluster network, and then for that cluster network you can create as many network configurations as needed to include all of the nodes with their specified uplinks, since they may differ (as they do in your case)

**Comment by SlavikCA** [comment]
I forgot to mention, that I also had VM network `net2` - UntaggedNetwork

@connorkuehl :
> You can create 1 cluster network, and then for that cluster network you can create as many network configurations as needed to include all of the nodes with their specified uplinks

I just tried to add one more network config for the `cn2`:
- name: `nc3`
- node selector set to `ds1621`
- NIC: ens4
- mode: active-backup (default)

and getting error:

> admission webhook "validator.harvester-system.harvester-network-webhook" denied the request: Internal error occurred: could not create vlanConfig nc3 because it overlaps with other vlanconfigs matching node(s) [ds1621]

Am I doing something wrong?

**Comment by SlavikCA** [comment]
ok, figured it out.

The issue was that my original `nc2` was configured for `Select all nodes`. I changed it to `Select specific node` and then successfully created new network config.
