### ISSUE TITLE
[BUG] State is missing for newly created VMs

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#561]
**Describe the bug**

**To Reproduce**
1. create a cirros image
2. create a VM from the image with 1C1G

**Environment:**
 - Harvester ISO version: master 
 - Installation Mode: ISO

**Result**
![image](https://user-images.githubusercontent.com/5697937/112263945-09fffe00-8cab-11eb-92e0-7dfc9ce8aba6.png)

It shows running after a period of time
![image](https://user-images.githubusercontent.com/5697937/112264011-2ef47100-8cab-11eb-9f7a-701815b60b17.png)

**Comment by TangStone** [comment]
Validation passes in **master-67244e23-head** version
