### ISSUE TITLE
[BUG] Snapshot restore seems broken

### ISSUE THREAD

**Issue by codot-fr** [harvester/harvester#5617]
**Describe the bug**
I took snapshots of virtual machines and then restored.

First, the virtual machine a stun in a "restoring" status indefinitly. I monitored the operations on longhorn and once it was stabilised I used the "start" action.

![image](https://github.com/harvester/harvester/assets/39614999/a7ae3a19-176f-47f4-9ecf-752279cd4a8a)

However, the operating system won't boot. 

First boot usualy works but I have this error message at startup:
![image](https://github.com/harvester/harvester/assets/39614999/1564b210-9477-4bb7-abe0-38781662ad91)

![image](https://github.com/harvester/harvester/assets/39614999/f98f6779-cb98-4cbc-a633-4337b54b983f)

If I restart, it hangs at the boot stage after "btrfs loaded" (it's an ubuntu 22.04 OS). So it seems the data is somehow corrupted.

![image](https://github.com/harvester/harvester/assets/39614999/b1b9d9a5-8def-4825-beb5-0176561d1a10)

Any idea how to troubleshoot both issues (the "restoring" status and the filesystem corruption one?

**Environment**
 - Harvester ISO version: 1.2.1

**Comment by codot-fr** [comment]
First part seems related to https://github.com/harvester/harvester/issues/4915.

**Comment by Vicente-Cheng** [comment]
Hi @codot-fr, 

Could you elaborate on more details?
Like:
What is your VM root partition format?
Before restoring, did you gracefully shutdown the VM?
Did the original VM could boot normally?

Thanks!

**Comment by codot-fr** [comment]
Hello Vicente.

I'll try to rescue boot the VM to give you more information.

I think my mistake was to make a "hot" snapshot (while the VM was running). 

I did shutdown the VM before restoring.

The original VM could boot normally.

From what I saw, restoring the snapshot is equivalent to cloning the snapshot to a new disk and attaching this new disks to the existing virtual machine. Is there a way to reattach the original disk to the virtual machine?

**Comment by WebberHuang1118** [comment]
@codot-fr 
Since you can manually restart the VM (although the data seems corrupt), the restoring pending is likely the issue you mentioned https://github.com/harvester/harvester/issues/4307.

You may rescue the VM by following https://harvesterhci.io/kb/scan-and-repair-vm-root-filesystem .

**Comment by codot-fr** [comment]
Thanks a lot for the rescue procedure, I worked just fine.

There's still something wrong obviously because rke2-server won't start now. Something about nm-cloud-setup.service being absent (`Failed to get unit file state for nm-cloud-setup.service: No such file or directory`), which it is. I never had the issue before, I'll dig into it.

**Comment by codot-fr** [comment]
No sorry, I was focusing on the wrong thing. Seems the etcd database is the issue:
```
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: rke2-server.service: Failed with result 'exit-code'.
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:75 +0x18a
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:76 +0x78
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:55 +0x399
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0xc0005ab230, 0x27}, {0x0, 0x0}, {0x0, 0x0}, {0xc00058c750,
 0x1, 0x1}, {0xc00058c630, ...}, ...}, ...)
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:163
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:189 +0x429
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc00058f080, 0x37}, 0x5f5e100, 0x2710, {0x366ac3f, 0x7},
 0x280000000, 0xc00085e770, 0x0, 0x0, ...})
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap.(*Logger).Panic(0xc00058f080?, {0x369c63f?, 0x453dd2?}, {0xc00089ea00, 0x2, 0x2})
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001fa750, {0xc00089ea00, 0x2, 0x2})
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0xc0002d9818?, {0x0?, 0x0?, 0xc000824580?})
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: goroutine 207 [running]:
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: panic: failed to open database
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"panic","ts":"2024-04-18T14:04:53.34906Z","caller":"backend/backend.go:189","msg":"failed to open da
tabase","path":"/var/lib/rancher/rke2/server/db/etcd-tmp/member/snap/db","error":"invalid database","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\t/go
/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\t/go/pkg/mod/github.com/k3s-io/etcd/server
/v3@v3.5.9-k3s1/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backen
d.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:76"}
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.333049Z","caller":"embed/etcd.go:309","msg":"starting an etcd serve
r","etcd-version":"3.5.9","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.20.11 X:boringcrypto","go-os":"linux","go-arch":"amd64","max-cpu-se
t":2,"max-cpu-available":2,"member-initialized":true,"name":"k8s-orange-ctrl-f197b549-mnmqk-22de9013","data-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp","wal-dir":"","
wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initia
l-election-tick-advance":true,"snapshot-count":10000,"max-wals":0,"max-snapshots":0,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"
],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"
cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572
864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-
time-interval":"1m0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-
interval":"5s"}
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.332902Z","caller":"embed/etcd.go:135","msg":"configuring client lis
teners","listen-client-urls":["http://127.0.0.1:2399"]}
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.332567Z","caller":"embed/etcd.go:127","msg":"configuring peer liste
ners","listen-peer-urls":["http://127.0.0.1:2400"]}
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sudo[2681]: pam_unix(sudo:session): session opened for user root(uid=0) by ubuntu(uid=1000)
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sudo[2681]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/bin/journalctl -r
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Starting temporary etcd to reconcile with datastore"
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Starting rke2 v1.26.11+rke2r1 (7ee1cfc93db32d05f3270711b24c429515
019e8a)"
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Applying Pod Security Admission Configuration"
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=warning msg="not running in CIS mode"
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sh[2669]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sh[2668]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
```

**Comment by Vicente-Cheng** [comment]
> No sorry, I was focusing on the wrong thing. Seems the etcd database is the issue:
> 
> ```
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: Failed to start Rancher Kubernetes Engine v2 (server).
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: rke2-server.service: Failed with result 'exit-code'.
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: rke2-server.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:75 +0x18a
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: created by go.etcd.io/etcd/server/v3/etcdserver.openBackend
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:76 +0x78
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/etcdserver.openBackend.func1()
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:55 +0x399
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/etcdserver.newBackend({{0xc0005ab230, 0x27}, {0x0, 0x0}, {0x0, 0x0}, {0xc00058c750,
>  0x1, 0x1}, {0xc00058c630, ...}, ...}, ...)
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:163
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/mvcc/backend.New(...)
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:189 +0x429
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.etcd.io/etcd/server/v3/mvcc/backend.newBackend({{0xc00058f080, 0x37}, 0x5f5e100, 0x2710, {0x366ac3f, 0x7},
>  0x280000000, 0xc00085e770, 0x0, 0x0, ...})
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/logger.go:258 +0x59
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap.(*Logger).Panic(0xc00058f080?, {0x369c63f?, 0x453dd2?}, {0xc00089ea00, 0x2, 0x2})
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:264 +0x3ec
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap/zapcore.(*CheckedEntry).Write(0xc0001fa750, {0xc00089ea00, 0x2, 0x2})
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]:         /go/pkg/mod/go.uber.org/zap@v1.24.0/zapcore/entry.go:198 +0x65
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: go.uber.org/zap/zapcore.CheckWriteAction.OnWrite(0x2?, 0xc0002d9818?, {0x0?, 0x0?, 0xc000824580?})
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: goroutine 207 [running]:
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: panic: failed to open database
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"panic","ts":"2024-04-18T14:04:53.34906Z","caller":"backend/backend.go:189","msg":"failed to open da
> tabase","path":"/var/lib/rancher/rke2/server/db/etcd-tmp/member/snap/db","error":"invalid database","stacktrace":"go.etcd.io/etcd/server/v3/mvcc/backend.newBackend\n\t/go
> /pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/mvcc/backend/backend.go:189\ngo.etcd.io/etcd/server/v3/mvcc/backend.New\n\t/go/pkg/mod/github.com/k3s-io/etcd/server
> /v3@v3.5.9-k3s1/mvcc/backend/backend.go:163\ngo.etcd.io/etcd/server/v3/etcdserver.newBackend\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backen
> d.go:55\ngo.etcd.io/etcd/server/v3/etcdserver.openBackend.func1\n\t/go/pkg/mod/github.com/k3s-io/etcd/server/v3@v3.5.9-k3s1/etcdserver/backend.go:76"}
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.333049Z","caller":"embed/etcd.go:309","msg":"starting an etcd serve
> r","etcd-version":"3.5.9","git-sha":"Not provided (use ./build instead of go build)","go-version":"go1.20.11 X:boringcrypto","go-os":"linux","go-arch":"amd64","max-cpu-se
> t":2,"max-cpu-available":2,"member-initialized":true,"name":"k8s-orange-ctrl-f197b549-mnmqk-22de9013","data-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp","wal-dir":"","
> wal-dir-dedicated":"","member-dir":"/var/lib/rancher/rke2/server/db/etcd-tmp/member","force-new-cluster":true,"heartbeat-interval":"500ms","election-timeout":"5s","initia
> l-election-tick-advance":true,"snapshot-count":10000,"max-wals":0,"max-snapshots":0,"snapshot-catchup-entries":5000,"initial-advertise-peer-urls":["http://127.0.0.1:2400"
> ],"listen-peer-urls":["http://127.0.0.1:2400"],"advertise-client-urls":["http://127.0.0.1:2399"],"listen-client-urls":["http://127.0.0.1:2399"],"listen-metrics-urls":[],"
> cors":["*"],"host-whitelist":["*"],"initial-cluster":"","initial-cluster-state":"new","initial-cluster-token":"","quota-backend-bytes":2147483648,"max-request-bytes":1572
> 864,"max-concurrent-streams":4294967295,"pre-vote":true,"initial-corrupt-check":true,"corrupt-check-time-interval":"0s","compact-check-time-enabled":false,"compact-check-
> time-interval":"1m0s","auto-compaction-mode":"","auto-compaction-retention":"0s","auto-compaction-interval":"0s","discovery-url":"","discovery-proxy":"","downgrade-check-
> interval":"5s"}
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.332902Z","caller":"embed/etcd.go:135","msg":"configuring client lis
> teners","listen-client-urls":["http://127.0.0.1:2399"]}
> avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: {"level":"info","ts":"2024-04-18T14:04:53.332567Z","caller":"embed/etcd.go:127","msg":"configuring peer liste
> ners","listen-peer-urls":["http://127.0.0.1:2400"]}
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sudo[2681]: pam_unix(sudo:session): session opened for user root(uid=0) by ubuntu(uid=1000)
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sudo[2681]:   ubuntu : TTY=pts/0 ; PWD=/home/ubuntu ; USER=root ; COMMAND=/usr/bin/journalctl -r
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Starting temporary etcd to reconcile with datastore"
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Managed etcd cluster bootstrap already complete and initialized"
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Starting rke2 v1.26.11+rke2r1 (7ee1cfc93db32d05f3270711b24c429515
> 019e8a)"
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=info msg="Applying Pod Security Admission Configuration"
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: time="2024-04-18T14:04:52Z" level=warning msg="not running in CIS mode"
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sh[2669]: Failed to get unit file state for nm-cloud-setup.service: No such file or directory
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk sh[2668]: + /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service
> avril 18 14:04:52 k8s-orange-ctrl-f197b549-mnmqk systemd[1]: Starting Rancher Kubernetes Engine v2 (server)...
> ```

Hi @codot-fr, does this issue happen on the restore VM or the original one?
Seems the etcd db is missing or corrupted
```
avril 18 14:04:53 k8s-orange-ctrl-f197b549-mnmqk rke2[2672]: panic: failed to open database
```

**Comment by codot-fr** [comment]
Hello Vicente,

On the restored VM. To be more precise, on the VM onto which I restored the snapshot and that I had to repair using the restore procedure in the KB.

**Comment by Vicente-Cheng** [comment]
Hi @codot-fr, 
Could you help to verify the following things? (If your original VM is still here)
1. Shutdown the original VM.
2. take snapshot
3. restore from the above snapshot

To see the VM status (bootup, etcd status)

BTW, could I know the original VM configuration?
like how many CPU/Memory, what is disks configuration ... etc?
Thanks!
