### ISSUE TITLE
[BUG] Migration fails if USB tablet is enabled

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#562]
**To Reproduce**
1. Create a cirros VM with 1C1G. Confirm that USB tablet is enabled in VM advanced options
2. Click migrate action of the VM.

**Expected behavior**
Migration succeeds

**Result**
The VM hangs in running/migrating state.

**Log**
From the target launcher pod:
```
{"component":"virt-launcher","level":"error","msg":"XML error: non unique alias detected: ua-","pos":"virDomainDeviceDefValidateAliasesIterator:6842","subcomponent":"libvirt","thread":"33","timestamp":"2021-03-24T07:52:59.324000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"a","namespace":"default","pos":"libvirt_helper.go:102","reason":"virError(Code=27, Domain=20, Message='XML error: non unique alias detected: ua-')","timestamp":"2021-03-24T07:52:59.325118Z","uid":"404d71c6-d4a6-4a23-b2f1-be13157b574f"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to migrate vmi","name":"a","namespace":"default","pos":"server.go:105","reason":"virError(Code=27, Domain=20, Message='XML error: non unique alias detected: ua-')","timestamp":"2021-03-24T07:52:59.325209Z","uid":"404d71c6-d4a6-4a23-b2f1-be13157b574f"}
```

**Environment:**
 - Harvester ISO version: master
 - Installation Mode: ISO

**Additional context**

This is fixed upstream, so hopefully fixed after updating kubevirt to v0.39.0+

Related issue: https://bugzilla.redhat.com/show_bug.cgi?id=1930339
Related PR: https://github.com/kubevirt/kubevirt/pull/5067

**Comment by gitlawr** [comment]
v0.39.0 is broken due to https://github.com/kubevirt/kubevirt/issues/5220, we need to wait for a newer kubevirt release.

**Comment by gitlawr** [comment]
We disabled USB tablet by default to workaround this issue. 
Now we can enable the USB tablet by default. @WuJun2016

**Comment by TangStone** [comment]
**Validation in version master-0008ce84-head**
- [x] 1. Create vm to enable USB tablet by default

- [x] 2. VM with USB tablet migrated successfully
