### ISSUE TITLE
[Question] Virtual machines go into a pause/running loop during .iso install

### ISSUE THREAD

**Issue by Eric-Domeier** [harvester/harvester#5620]
Hello,

I installed **Harvester 1.3.0** the other day on my homelab server (Single-node) and am running into issues when trying to install a new VM through an ISO file, where it starts to run and then when the OS starts to write to disk I get stuck in an paused/running loop and it freezes. I imagine it may be the old hardware.. but just in case asking.

##Hardware

Dell PowerEdge  R530
2x Intel(R) Xeon(R) CPU E5-2660 v3
PERC H730P mini Storage controller
8x Seagate ST33000650SS
 RAID-1 (Harvester) & RAID-6 (VM/Data) Configuration

##Steps taken

- Configured a new storage class and set replication to 1 for a single node and set to default
- Upload .iso image (Tried RHEL8, Ubuntu 22.04.4, Kali latest)
- Create new VM
- -Select the image for first volume
- -Select another disk with ~100GB using VirtIO, SCSI or SATA
- Go through install menu, it works temporarily usually until the installer tries to write to disk before it freezes.

An interesting error shown right before it starts the loop:

`parsing time "(process:29)" as "2006-01-02 15:04:05.999-0700": cannot parse "(process:29)" as "2006"`

Additional logs attached, any help appreciated.

[virt-launcher-ubuntuiso-swpgq_compute.log](https://github.com/harvester/harvester/files/15018891/virt-launcher-ubuntuiso-swpgq_compute.log)

**Comment by connorkuehl** [comment]
Would you be willing to provide a support bundle? https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle

I see in the log you attached where the I/O error occurred, but there will be more information from the Longhorn layer in the support bundle.

If your VM is in a custom namespace, you may have to add it to the `support-bundle-namespaces` setting.

Harvester Dashboard > Advanced > Settings > support-bundle-namespaces

**Comment by Eric-Domeier** [comment]
@connorkuehl I seem to be having issues with getting stuck at generating the support bundle at 40%.... it timed out the first time so I found that you can set it to infinite... I will let it run overnight and see what happens.

**Comment by Eric-Domeier** [comment]
Came back to the following error

{"errors":["fail to get support bundle resource: supportbundles.harvesterhci.io \"bundle-g92fv\" not found"]}

**Comment by Eric-Domeier** [comment]
I managed to find some additional errors from Longhorn, I noticed that the share-manager seems to go into a terminating/restart state and some of the logs I was able to capture are as follows

```
`harvester-node-1:~ # kubectl logs share-manager-pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 -n longhorn-system
time="2024-04-20T04:18:05Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-04-20T04:18:05Z" level=info msg="Ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
time="2024-04-20T04:18:05Z" level=info msg="Listening on share manager gRPC server :9600" func=cmd.start.func2 file="server.go:134"
time="2024-04-20T04:18:05Z" level=info msg="Volume pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 device /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 contains filesystem of format unknown data, probably partitions" encrypted=false volume=pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9
W0420 04:18:05.993884       1 mount_linux.go:531] Configured to mount disk /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 as unknown data, probably partitions but current format is ext4, things might break
I0420 04:18:05.999415       1 mount_linux.go:452] `fsck` error fsck from util-linux 2.37.4
fsck.ext2: Bad magic number in super-block while trying to open /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9
/dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9:
The superblock could not be read or does not describe a valid ext2/ext3/ext4
filesystem.  If the device is valid and it really contains an ext2/ext3/ext4
filesystem (and not swap or ufs or something else), then the superblock
is corrupt, and you might try running e2fsck with an alternate superblock:
    e2fsck -b 8193 <device>
 or
    e2fsck -b 32768 <device>

Found a gpt partition table in /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9
E0420 04:18:06.062115       1 mount_linux.go:230] Mount failed: exit status 32
Mounting command: mount
time="2024-04-20T04:18:06Z" level=warning msg="Failed to mount volume" encrypted=false error="mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9\nOutput: mount: /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9, missing codepage or helper program, or other error.\n" volume=pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9
Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9
Output: mount: /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9, missing codepage or helper program, or other error.

time="2024-04-20T04:18:06Z" level=debug msg="Device /dev/mapper/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 is not an active LUKS device" func=crypto.DeviceEncryptionStatus file="crypto.go:89" error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/24140/ns/mnt --ipc=/host/proc/24140/ns/ipc cryptsetup status pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9], output , stderr nsenter: failed to execute cryptsetup: No such file or directory\n: exit status 127"
time="2024-04-20T04:18:06Z" level=fatal msg="Error running start command: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9 /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9\nOutput: mount: /export/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9: wrong fs type, bad option, bad superblock on /dev/longhorn/pvc-992dd415-44a2-42a2-8fa4-121a99ac2bd9, missing codepage or helper program, or other error.\n." func=cmd.ServerCmd.func1 file="server.go:100"`
```

it seems it may not like the filesystem?

**Comment by Eric-Domeier** [comment]
Okay, Well i got it working, I missed the option when making a new storage class for bind mount options

![image](https://github.com/harvester/harvester/assets/35058053/241a73fb-8d6e-45aa-a437-7adc6ffc229a)

Selecting "Bind and provision a persistent volume once a VM using the PersistentVolumeCLaim is created" allowed me to go through the entire install process and create a VM.

I'm not sure if this was documented somewhere and i missed it, common knowledge or a bug
