### ISSUE TITLE
[BUG]  proxy mode can't remove vm

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#563]
**Describe the bug**
Cannot delete vm in proxy mode

**To Reproduce**
1. Deploy the harvester app in the rancher store
2. Open harvester ui via app
3. create a vm
4. delete vm

**Expected behavior**
vm should be deleted

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
**Validation Version**
- master-67244e23-head

**Validation Scenarios**
1. Deploy the harvester app in the rancher store
2. Open harvester ui via app
3. create a vm
4. delete vm

** Results**
Delete vm successfully
