### ISSUE TITLE
[ENHANCEMENT] vGPU allocation during downstream cluster provisioning

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#5651]
**Is your enhancement related to a problem? Please describe.**

With Harvester v1.3.0 we now support vGPU device passthrough.

We need to allow user to specify vGPU device requirement during downstream cluster provisioning. This is already supported in the machine driver: https://github.com/harvester/docker-machine-driver-harvester/pull/50

The machine driver changes are included in rancher v2.7.9+ and v2.8.3+

A UI change is now needed in Rancher to allow passing vGPU requirements during downstream cluster provisioning.

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
related dashboard issue: https://github.com/rancher/dashboard/issues/10588

**Comment by bk201** [comment]
Rancher issues:
- v2.9: https://github.com/rancher/dashboard/issues/10588
- v2.8: https://github.com/rancher/dashboard/issues/10593

**Comment by albinsun** [comment]
Test PASS, close as done.

### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: Single node QEMU/KVM (48C/128G/1.6T)
  * ui-source: Auto
* Rancher
  * Version: v2.9.1
  * Profile: harvester-vcluster (v1.29.9+k3s1)

### Prerequisite
1. &NewLine;
   <details>
   <summary> Create VM network <i>mgmt-vlan1</i>
   </summary>
  
   ![image](https://github.com/user-attachments/assets/1479cbd7-4eba-4c08-9dd9-877b8a3e48c4)
   </details>

1. &NewLine;
   <details>
   <summary> Create VM image <i>jammy-server-cloudimg-amd64.img</i>
   </summary>
  
   ![image](https://github.com/user-attachments/assets/4621bd90-c302-4d29-9487-3cb8ecd46ae5)
   </details>

1. &NewLine;
   <details>
   <summary> Enable required addons
   </summary>
 
   ![image](https://github.com/user-attachments/assets/4b86881f-04f3-47b9-a9d2-ce4613ac001f)
   </details>

   * **rancher-vcluster**: rancher-v2.9.1
   * **pcidevices-controller**
   * **nvidia-driver-toolkit**: Driver _NVIDIA-Linux-x86_64-550.90.05-vgpu-kvm.run_

1. 
   &NewLine;
   <details>
   <summary> Enable <b>SR-IOV GPU Device</b> and one <b>vGPU Device</b>
   </summary> 
  
   * SR-IOV GPU Device
     ![image](https://github.com/user-attachments/assets/a571b568-841f-4748-bf63-b35f3ca99be5)
   * vGPU
     ![image](https://github.com/user-attachments/assets/2d285132-1d5d-48e1-ac9a-7c81ef6e8f26)
   </details>

   > Ref. https://docs.harvesterhci.io/v1.3/advanced/vgpusupport/

### Steps
1. &NewLine;
   <details>
   <summary> <i>Given</i> import Harvester to Rancher
   </summary>
  
   ![image](https://github.com/user-attachments/assets/5f5f493e-d2e4-4405-86e7-0511f510e895)
   </details>

  
1. &NewLine;
   <details>
   <summary> <i>When</i> provisioning a new RKE2 guest cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/f7969d0d-fe09-4c83-b08f-e08aaf567899)
   </details>

1. &NewLine;
   <details>
   <summary> <i>Then</i> can select the enabled vGPU in the <b>vGPUs</b> field in <b>Advanced</b> section
   </summary>
  
   ![image](https://github.com/user-attachments/assets/3e43498e-abd2-487e-809c-084604b38673)
   </details>
   
   > Ref. HEP: https://github.com/harvester/harvester/pull/5752

1. &NewLine;
   <details open>
   <summary> <i>And</i> guest cluster with attached vGPU can successfully provisioned
   </summary>
   
   * RKE2 cluster
     ![image](https://github.com/user-attachments/assets/3ae5cfb4-01dd-47f7-beae-7cc1e0eac31b)
   * vGPU do attached on VM
     ![image](https://github.com/user-attachments/assets/35f62d54-a541-47b4-9718-e4d8156be271)
     ![image](https://github.com/user-attachments/assets/5e867b61-794a-49df-9ee4-3b1c7dc8fdf0)
   </details>


### Supportbundle
n/a

### QA Check List
1. Update labels
   - [x] This ticket: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
   - [x] tests ticket: harvester/tests/issues/1240
