### ISSUE TITLE
Using dated version of govmomi library

### ISSUE THREAD

**Issue by rajesh1084** [harvester/harvester#5653]
As per `[go.mod](https://github.com/harvester/vm-import-controller/blob/main/go.mod#L16)`, Harvester is using dated version of the govmomi library. The latest version as of today is v0.37.1 (https://github.com/vmware/govmomi/tags).

Will it be possible to update to the latest and make it available in the next build/release?

**Comment by ibrokethecloud** [comment]
fixed in: https://github.com/harvester/vm-import-controller/pull/31

**Comment by brandboat** [comment]
Test OK on harvester-v1.4.0-rc3

## Test steps
- Addon enable successfully
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/6be95c66-efaa-420b-aa45-0c15c4e17b7f">

- Make sure govmomi library use the appropriate version.
<img width="1673" alt="image" src="https://github.com/user-attachments/assets/fb94394c-5af1-462d-9cf6-fc4a123f5ab4">

1.4.0-rc3 use v0.4.1 vm-import-controller, and it use `github.com/vmware/govmomi v0.37.2`

https://github.com/harvester/vm-import-controller/blob/v0.4.1/go.mod#L16
