### ISSUE TITLE
[BUG] SR-IOV filter button overlaps the filter list in vGPU devices page

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5663]
**Version**
v1.3.0

**Describe the bug**

The Parent SR-IOV filter button overlaps the filter list in vGpu devices page; we should investigate the issue is specific or it affects other buttons in the UI.

**To Reproduce**
1. Go to Advanced -> vGPU devices tab
2. Click on 'Filter By Parent SR-IOV' filter on top -right side of the page.

**Expected behavior**

The filter's list should be displayed correctly

**Additional context**

![image](https://github.com/harvester/harvester/assets/26394656/95773b16-3219-4d35-9e81-445ed5f9d626)

**Comment by rrajendran17** [comment]
@torchiaf I checked this on v1.4.0-rc2 and still see an overlap.
Am I checking this correctly  ?

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNTFtQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--72134a54c0688db8c050e090e4ba1161ed61d3cf/vGPU.png" alt="vGPU.png" />

**Comment by rrajendran17** [comment]
@a110605  can you please check my above comment ?

**Comment by rrajendran17** [comment]
checked this in v1.4.0-rc4 and still see the overlap. @a110605  @torchiaf  can you please check this ?

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEZ4Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e65b55daef25c7d41e435c487f0fa6189dedcf1a/5663-new1.png" alt="5663-new1.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOE54Qnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--bc5d9810a03a06c11593b186e1d71f38ad9731f5/5663-new2.png" alt="5663-new2.png" />

**Comment by torchiaf** [comment]
@rrajendran17 I'm testing the 1.4 version. Updates ASAP.

**Comment by rrajendran17** [comment]
Thanks @torchiaf.you can use 172.19.97.190 if you want.It has v1.4.0-rc4 installed.

**Comment by rrajendran17** [comment]
@torchiaf  @a110605 I am moving it to "Implement" for now.Please feel free to move it back to "Ready to Testing" if you feel its fixed already.

**Comment by a110605** [comment]
Hi @rrajendran17, the filter option position in your screenshot is correct.

You can carefully compare the screenshot in this issue description. 

The filter options should OVERLAY on the `Filter by parent SR-IOV GPU` box.

You can refer in fixed PR: https://github.com/harvester/dashboard/pull/1033


cc @torchiaf

**Comment by rrajendran17** [comment]
@a110605 Thanks for the clarification,as it works as expected closing this.
