### ISSUE TITLE
[Question] requesting a default manifest

### ISSUE THREAD

**Issue by claywd** [harvester/harvester#5667]
I deleted the rancher-monitoring namespace.

Then the addon disappeared from the ui... which makes sense now (but was kind of unexpected) since harvester is built on k8s and when I delete the ns the addon resource for rancher-monitoring was also deleted.

tl;dr
Can someone please drop here the default manifest for the rancher-monitoring addon so I can recreate.

**Comment by Yu-Jack** [comment]
It should be this one https://github.com/harvester/harvester/blob/master/package/upgrade/addons/monitoring_addon.yaml. There are default Addon manifests in that directory as well.
