### ISSUE TITLE
[FEATURE] add default rancher server-url on harvester first login

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#567]
**Is your feature request related to a problem? Please describe.**
add default rancher server-url on harvester first login

**validation steps**
1. visit rancher and check it server-url is same as harvester URL but with port 30444

**Comment by TangStone** [comment]
1. rancher-enabled defaults to Disable 
![image](https://user-images.githubusercontent.com/15829074/113082056-5e0b6500-920c-11eb-92de-bdea6f22729b.png)
2. rancher-enabled is set to Enable, Rancher button appears in the upper right corner of the UI, click the button, access successfully, the URL is the same but port 30444
![image](https://user-images.githubusercontent.com/15829074/113082173-8c894000-920c-11eb-96db-1f1f5a1f17ca.png)
![image](https://user-images.githubusercontent.com/15829074/113082202-9c088900-920c-11eb-8c02-61357f799a45.png)
3. rancher-enabled is set to Disable, the rancher button entry in the upper right corner of the harvester disappears
