### ISSUE TITLE
[Enhancement] Add a hint and document for the Console button

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5679]
**Is your doc request related to a problem? Please describe or add related issue ID.**
The console button on the "hosts" page is gray by default and confusing.
<img width="1674" alt="console" src="https://github.com/harvester/harvester/assets/1691518/5642e175-a251-4c97-a6d3-092d11e6b12d">

**Describe the solution you'd like**

Add a document for it and provide a tooltip hint while hovering the button.

**Comment by a110605** [comment]
Hi @WebberHuang1118 , UI PR is merged now.
We can update the doc link in dashboard once have new document block.

**Comment by a110605** [comment]
> Hi @WebberHuang1118 , UI PR is merged now. We can update the doc link in dashboard once have new document block.

After synced with @WebberHuang1118 , the doc update will be added in https://docs.harvesterhci.io/v1.4/host/. So move this ticket to `READY FOR TESTING`

**Comment by lanfon72** [comment]
The link of tool-tip added, but no document available, **move back to implement**. (as there have label `require/doc`)
And I would suggest that add anchor for the relevant document section, for example: `/v1.4/host/#Console_URL`.

The feature was introduced in #752 and enhanced in #2806, but we still not add any documentation for it.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-95024f7c-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Navigate to Host pages
3. There should have a link for console button
4. The link should describe how the console button work

**Comment by bk201** [comment]
cc @WebberHuang1118 please double check the doc

**Comment by WebberHuang1118** [comment]
Since the document has not been updated yet, after a discussion with @a110605, the GUI will link the URL to the host page first. Then the GUI fix could be decoupled with the document update. I will have the document update ASAP.

**Comment by WebberHuang1118** [comment]
Thanks @a110605 
Document PR https://github.com/harvester/docs/pull/652 and GUI PR https://github.com/harvester/dashboard/pull/1205 are under reviewing

**Comment by a110605** [comment]
Doc and UI PRs are merged. 
https://docs.harvesterhci.io/v1.4/host/#remote-console is updated. Move back to `Ready For Testing`

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.


Test Information
----
* Environment: **bare metal DL360G9 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **External**

### Verify Steps
- Same as https://github.com/harvester/harvester/issues/5679#issuecomment-2420188377
