### ISSUE TITLE
[FEATURE] Create image from volume

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#568]
It's common for the user to modify the existing VM content, then want to use the updated volume content as an image for the new VM.

We need to support create an image from a volume, for both root image and non-root image.

Depends on: https://github.com/longhorn/longhorn/issues/2403

**Comment by futuretea** [comment]
If this is implemented, then a packer provider can also be implemented to automate the entire process of creating images.

**Comment by WuJun2016** [comment]
Done

**Comment by gitlawr** [comment]
Some UI issues to be fixed:
1. When the volume export is in progress, the image status shows `Uploading`.
2. Edit an image created from a volume, it shows `Upload Files`
![image](https://user-images.githubusercontent.com/5697937/134793965-64d3f211-a69d-4a89-a6eb-da8019a01287.png)

**Comment by guangbochen** [comment]
Few Typo and enhancement:
- Export Image => Export to Image
- system namespaces are not filtered and should use the user's current selected default namespace
- swap the order of the namespace first and name, also why the margin is quite big and the height is quite different between those two fields?
![image](https://user-images.githubusercontent.com/4569037/134799547-36d74f31-d8ed-40c1-963d-f856ea6e395d.png)

**Comment by gitlawr** [comment]
![image](https://user-images.githubusercontent.com/5697937/134801500-9f173338-0eb6-44a0-bd0b-6e45fd510873.png)
The error happens when exporting an image in a different namespace. @shangma

**Comment by shangma** [comment]
### To Test:

1. Download the latest harvester [ISO](https://releases.rancher.com/harvester/master/harvester-amd64.iso) and boot a virtual machine from it
2. Log into Harvester
3. Go to "Images" section and create an original os image from an url, say [this one](https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-disk1.img)
4. Create a virtual machine from the image above with proper config. A good example can be found [here](https://docs.harvesterhci.io/v0.2/vm/create-vm/#cloud-config-examples).
5. Once the vm is created, log into it and make some changes. The default username for the image above is "ubuntu" and the password can be configure from step 3
6. Go to "Volumes" section and select the volume for the virtual machine above. And then click on the three dots on the far right and choose "Export Image"
![image](https://user-images.githubusercontent.com/2396545/134824988-35ba8f37-5ae2-4dc8-93c7-95e0c51ae93f.png)

7. Choose a namespace and give a proper name and then click "create" (verify using another namespace owned by the user should also works)
![image](https://user-images.githubusercontent.com/2396545/134824713-29a36050-5dc8-4f9c-9b74-4acd5fb20d5c.png)

8. A new image should appear in the Images section
![image](https://user-images.githubusercontent.com/2396545/134824734-c7e93372-d80c-42f7-8562-487c2e842f79.png)

8. Once the image export is finished, create another virtual machine from this newly created image like step 3, log into it and make sure the changes we made in step 4 is there.

**Comment by lanfon72** [comment]
verified the behavior followed the [steps](https://github.com/harvester/harvester/issues/568#issuecomment-927375947).

Test Information
----
* Environment:  **Bare metal DL360** single node
* Harvester Version: **v0.3.0-rc1**
### Verify Steps:
  1. create image of [k3os](https://github.com/rancher/k3os/releases/download/v0.20.4-k3s1r0/k3os-amd64.iso) in `Images`
  2. create vm1 based on k3os' image in `VIrtual Machines` ( disk1 as iso, disk2 as hdd)
     - Install k3os on disk2
     - eject k3os iso and reboot
     - login and do `echo "hello world" > show`
     - shutdown vm1
  3. Export **vm1**'s disk2 as _vm1-shadow_ in `Volumes`
  4. create vm2 based on **vm1-shadow_ in `Virtual Machines`
     - **disk size** most **greater** than origin one(eg. vm1's size is 20G, vm1-shadow's size should be greater than 20G), otherwise boot fail raised.
     - **disk type** should be `disk` rather than `cd-rom`
     - start vm2 and login w/ vm1's username/password
     - do `cat show`, it will display `hello world`

### Additional Verify:
  - modification on vm1, will not affect to vm2
  - modiication on vm2 will not affect to vm3 which using the same Image to create. (different volume)
