### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by jtamas96** [harvester/harvester#5684]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
@jtamas96 Do you mind completing the issue title and description? Thanks!

**Comment by rebeccazzzz** [comment]
Closing this issue in favor of https://github.com/harvester/harvester/issues/5685. Feel free to open additional feature requests and issues anytime.
