### ISSUE TITLE
[BUG] overcommit-config defaults are not applied

### ISSUE THREAD

**Issue by connorkuehl** [harvester/harvester#5695]
**To be honest, I am not 100% sure that this is a bug. I can see why it would be useful to err on the side of not overcommitting anything out of the box. Perhaps this is more of a UI/UX/docs issue regarding the behavior of this setting.**

---

**Describe the bug**

The overcommit-config setting's default settings that are shown on the dashboard are not automatically applied, as we can see here the Longhorn overcommit percentage is not the default 200:

![before](https://github.com/harvester/harvester/assets/5227338/b53ed6b7-fc31-4af9-9a60-85944d2c9bdd)

Unless you click "save", in which case, they are:

![after](https://github.com/harvester/harvester/assets/5227338/59006ea3-52e8-4523-bcd0-502102dd36f0)

The fact that these values are prepopulated makes it seem as though they should be applied out of the box.

**To Reproduce**
1. Install Harvester 1.3.0
2. Check the overcommit-config
3. Look at Longhorn dashboard, compare Longhorn's overprovisioning percentage to the overcommit-config storage value

**Expected behavior**

In this case, the default storage value for overcommit-config is 200, so I would expect Longhorn's overprovisioning percentage to be 200.

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

In the case of the Longhorn storage overcommit value not being propagated, that is because Harvester only pays attention to the setting.Value, and doesn't override it with the setting.Default if setting.Value is not set.

https://github.com/harvester/harvester/blob/8958ebee30387c8591eeb17ddf60e178517e9de3/pkg/controller/master/setting/overcommit_config.go#L15-36

**Comment by janeczku** [comment]
It appears that Harvester 1.3.0 has storage over-commit disabled by default (since the Longhorn `StorageOverProvisioningPercentage` setting defaults to 100%).

This contradicts the documentation, which [clearly states](https://docs.harvesterhci.io/v1.3/vm/resource-overcommit) that Harvester uses a storage over commit ration of 200% by default.

This issue should be clearly marked in the documentation and/or release notes. @innobead

**Comment by tserong** [comment]
Longhorn previously defaulted over commit to 200%, but this was changed to 100% in Longhorn version 1.5.0 (see https://github.com/longhorn/longhorn/issues/2694 and https://github.com/longhorn/longhorn-manager/pull/1896), so this affects Harvester v1.2.2 (which has LH v1.5.4 vs. Harvester 1.2.1 which had LH v1.4.3), and the Harvester 1.3 and newer series (LH v1.6+)

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard and *Enable Extension developer features* in preferences
3. Access embedded longhorn dashboard via support page
4. Check the setting `Storage Over Provisioning Percentage` should be the same as Harvester setting `overcommit-config`
    - The default value should be the same as `200`
    - Update the `storage` value in Harvester dashboard, longhorn's *Storage Over Provisioning Percentage* should be updated automatically.
