### ISSUE TITLE
[ENHANCEMENT] In Harvester Installer `pkg/console/install_panels.go` show DNS Servers User Input within `func addConfirmInstall Panel`

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5696]
**Is your enhancement related to a problem? Please describe.**
A user, can't, at the final stage see DNS Servers that they input

**Describe the solution you'd like**
`func addConfirmInstallPanel` could possibly just show that information

**Describe alternatives you've considered**
A user, just "has to remember" what they input for that field... 

**Additional context**
A user is being asked for DNS servers, or default is used, if the user inputs DNS servers, showing the user the DNS servers they input on the final panel could be beneficial for a multitude of reasons.

**Comment by bk201** [comment]
@irishgordo I added a test plan and moved the issue to ready for testing. Thanks.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.2.2-rc2`. Validated as fixed. 

![Screenshot_20240507_122318](https://github.com/harvester/harvester/assets/83787952/106e3e58-ee75-4604-9dd3-0b8286e5b937)
![Screenshot_20240507_120321](https://github.com/harvester/harvester/assets/83787952/663bb7cd-a4e8-43d3-9e0d-13545bfaa62f)

**Comment by noahgildersleeve** [comment]
I accidentally closed this when I was testing the backport issue with #5703 . So I'm marking it as ready for testing again.

**Comment by albinsun** [comment]
Test **PASS**, close as done.


### Environment
* `harvester-v1.4.0-dev-20240918`
  * Profile: Single node QEMU/KVM (8C/16G/500G)
  * ui-source: `Auto`


### Prerequisite
1. Manual ISO installation with DNS `1.1.1.1,8.8.8.8,9.9.9.9`
   ![image](https://github.com/user-attachments/assets/93ecaf6e-f1ca-42b7-a22b-0d7eddbafb3e)


### Steps 
1. <details>
   <summary> DNS shows in the installation summary :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/356ac8d0-9712-47c8-8bcd-cd14ca4ba78d)
   </details>

1. <details>
   <summary> DNS do configured in system :heavy_check_mark: 
   </summary>
  
   ![image](https://github.com/user-attachments/assets/57562b57-cac9-4c8f-9ba3-f92fa0095c56)
   </details>


### QA Check List
- [x] Labels: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
- [x] Update corresponding tests ticket lables
