### ISSUE TITLE
[BUG] support-bundle-image's default value becomes empty in multi-nodes cluster

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5699]
**Describe the bug**
Once config **Setting:support-bundle-image**, will fail to reset to default value.

**To Reproduce**
1. Go to 'Settings' -> support-bundle-image -> Edit Setting -> Save
   ![image](https://github.com/harvester/harvester/assets/2773781/9f235d9e-5e2c-492f-ae29-73d0cb2976f1)
1. Go to 'Settings' -> support-bundle-image -> Edit Setting -> Use the default value -> Save 
   ${\color{red} \text{Fail, shows "Repository"/"Tag" is required.}}$
   ![image](https://github.com/harvester/harvester/assets/2773781/a2fe7f6b-920a-478a-801f-d9cd5a1ca125)
   

**Expected behavior**
Should be able to save after click "Use the default value"

**Support bundle**
[supportbundle_setting-support-bundle-image_2024-04-29T04-32-31Z.zip](https://github.com/harvester/harvester/files/15145149/supportbundle_setting-support-bundle-image_2024-04-29T04-32-31Z.zip)

**Environment**
* Harvester
  * Version: `v1.2.2-rc1`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`

**Additional context**
n/a

**Comment by torchiaf** [comment]
@albinsun could you check if you are receiving the `default` value in `harvesterhci.io.settings` -> `support-bundle-image` payload ?

![image](https://github.com/harvester/harvester/assets/26394656/4dadae1d-0d97-444b-a226-a55ed9e433f1)

**Comment by albinsun** [comment]
> @albinsun could you check if you are receiving the `default` value in `harvesterhci.io.settings` -> `support-bundle-image` payload ?
> 
> ![image](https://private-user-images.githubusercontent.com/26394656/326405107-4dadae1d-0d97-444b-a226-a55ed9e433f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0NDEzNTcsIm5iZiI6MTcxNDQ0MTA1NywicGF0aCI6Ii8yNjM5NDY1Ni8zMjY0MDUxMDctNGRhZGFlMWQtMGQ5Ny00NDRiLWEyMjYtYTU1ZWQ5ZTQzM2YxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDAxMzczN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlhZjVmZWVmZmM2Mjg2NzE2MTU0N2MzMzZhMzU3NzA3ZjczYjM5NDg1MjQ3ZjFjYTJmMDliOGMzZjY0YTkzMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DHcLRW7PJdMaak_GoWfkCz_ifjNX1qwP0XQCqRFjC-A)

nope, key `default` has empty value.
![image](https://github.com/harvester/harvester/assets/2773781/1c780eb9-8b94-4739-931e-e6390a9ea166)
Following is my UI source (I haven't change it, should be default value)
![image](https://github.com/harvester/harvester/assets/2773781/833f9ddb-2fe0-4231-9354-90f6c6db1be7)

**Comment by a110605** [comment]
I tested with v1.4.0-rc3 and can't reproduce this issue. The `use default value` work as expected and can successfully save.

<img width="1495" alt="image" src="https://github.com/user-attachments/assets/9fdd992f-9b1d-41d8-93e1-f9f871998266">

**Comment by bk201** [comment]
@albinsun is this still a valid issue?

**Comment by albinsun** [comment]
@a110605 and @bk201 ,

Had more tries and note that this issue exists in `v1.3.2` too but not `v1.4.0`.
I will change title to "support-bundle-image's default value becomes empty in multi-nodes cluster"
Please refer following recording.

## v1.3.2
1. :green_circle: Setup 1st node, check **Setting: support-bundle-image**.

   https://github.com/user-attachments/assets/dea0f678-17a4-416b-8469-770ca983f271

1. :red_circle: Join 2nd node, check **Setting: support-bundle-image**.
   > Default value becomes empty

   https://github.com/user-attachments/assets/cc5ad2c8-57c2-485f-9d08-ca483688366c

## v1.4.0-rc5
1. :green_circle: Setup 1st node, check **Setting: support-bundle-image**.

   https://github.com/user-attachments/assets/22981057-80fa-44a2-9500-90271f63b75c

1. :green_circle: Join 2nd node, check **Setting: support-bundle-image**.

   https://github.com/user-attachments/assets/7b52d264-4e43-409b-b665-cf8ced187e62

**Comment by bk201** [comment]
Thank you @albinsun, add the issue to the milestone 1.3.3

**Comment by a110605** [comment]
hi @bk201 , @albinsun  the `support-bundle-image` default setting is an empty object from API `v1/harvester/harvesterhci.io.settings` after adding second node. (If only one node is good)

Could you help check with backend why it's empty object ?

<img width="1496" alt="Screenshot 2024-11-25 at 4 13 34 PM" src="https://github.com/user-attachments/assets/7fc4499c-7373-4a76-830f-78cd73cd7f2f">

**Comment by w13915984028** [comment]
FYI:

In Harvester v1.4.0 there was a PR https://github.com/harvester/harvester/pull/6358; and on v1.3.3 there is a pending PR https://github.com/harvester/harvester/pull/6481, after the PR https://github.com/harvester/harvester/pull/6481, v1.3.3 should behaviour same as v1.4.0

**Comment by a110605** [comment]
> #6481

As v1.3.3 backport PR https://github.com/harvester/harvester/pull/6481 is merged. I will move this ticket to READY FOR TESTING.

**Comment by albinsun** [comment]
Test PASS, close as fixed.


## Environment
* `harvester-v1.3-93523eab-head`
  * Profile: 4 nodes witness AMD64 QEMU/KVM
  * ui-source: `Auto`


## Test Steps
1. <details>
   <summary> :green_circle: Setup a 4 nodes witness cluster
   </summary>

   ![Image](https://github.com/user-attachments/assets/32e0b3fa-6330-49fb-b936-988d4c4b1101)
   </details>

1. <details open>
   <summary> :green_circle: Go to <b>Settings</b> -> <b>support-bundle-image</b> -> <b>Edit Setting</b> -> <b>Save</b>
   </summary>

   ![Image](https://github.com/user-attachments/assets/987a7426-2d96-4074-b83a-e28c66f8c4a9)
   </details>

1. <details open>
   <summary> :green_circle: Go to Go to <b>Settings</b> -> <b>support-bundle-image</b> -> <b>Edit Setting</b> -> <b>Use the default value</b> -> Save
   </summary>

   ![Image](https://github.com/user-attachments/assets/1e6ae783-2fc8-4295-a3ee-40eb070ebd6f)
   </details>
