### ISSUE TITLE
[BUG] Bare Metal ISO install stalls with workqueue locks

### ISSUE THREAD

**Issue by gregorymcphee** [harvester/harvester#5707]
**Describe the bug**
<Harvester 1.3.0 ISO will not install>

**To Reproduce**
Boot from 1.3.0 USB ISO on Dell R720XD 

**Expected behavior**
<Harvester Boot Menu should appear>

**Support bundle**
<Unable to generate support bundle given where in the process the error is occuring.  Said another way, the error is during SUSE linux load, pre-kernel load.  No access to TTY or journalctl>

Posted this issue on slack: Harvester

**Environment**
 - Harvester ISO version: 1.3.0 
 - Baremetal with Dell PowerEdge R730XD
 - 64g RAM, PERC730 with 2 RAID VD (1 BOOT - SSD, 2 DATA - HD), NIC 4 port (2 ports SFP+ GBIC, 2 RJ45 Ethernet)
 - RJ45 Ethernets connected to Nexus 3k. 2 SFP+ ports not connected
 - E5-2680 14c x 2 @ 2.4
<img width="1115" alt="Screenshot 2024-04-29 at 9 25 23 AM" src="https://github.com/harvester/harvester/assets/109609497/29e19cfd-f31d-4ecd-8128-5eb9b293ad0e">

**Comment by bk201** [comment]
@gregorymcphee Does this only happen to this machine?

**Comment by gregorymcphee** [comment]
I have no other hardware to test on.  So yes. I have successful loaded Windows 11 and ESXi 7.0.3.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ibrokethecloud** [comment]
does the machine refuse to boot with other versions of harvester as well? say v1.2.1?

**Comment by gregorymcphee** [comment]
Things I've tried... 
Upgraded bios to latest version (was 1 version old).
Upgraded Lifecycle manager (was 1 version old).
Disconnected all ssd's and hard drives.
Connected all 4 ethernet ports to a live switch.
Tried booting with 1.21 and 1.22+rc1.
Compared the BIOS settings between existing ESXi hosts (Dell R720) and this machine (R730xd).
Let the system boot run for 12 hours.
All end with the same errors.

**Comment by ibrokethecloud** [comment]
are you able to try booting the machine using opensuse 15.4 iso?

**Comment by gregorymcphee** [comment]
I was able to boot/install on a Dell R630 using very similar hardware. Only glaring difffernece is R630 has PERC 730 and Dell R730 has PERC 730 Mini.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ibrokethecloud** [comment]
are you able to disable the raid controller and boot? it may mean nothing since you may not be able eventually install harvester since there may be no disks visible, but it will help isolate the issue.

**Comment by t-v** [comment]
I have the same issue. 

![image](https://github.com/harvester/harvester/assets/6328839/7aefc480-3209-477c-93b5-3e5600b13b51)
![image](https://github.com/harvester/harvester/assets/6328839/f8632746-fed9-4696-bd37-a03cef537e8a)

I have tried previous versions and they all give the same issue.

**Comment by gregorymcphee** [comment]
I’ve seen some blogs mentioning this issue is the storage controller. Not sure the error message supports that, but error messages don’t always point to the source issue.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
