### ISSUE TITLE
[BUG] 3 nodes upgrade from v1.2.1 to v1.2.2-rc1 with Rancher integrated stuck in Upgrading System Service

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5712]
**Describe the bug**

While Harvester v1.2.1 integrated with Rancher v2.8.2 and have other vm created.
We shutdown the vm from operating system (not from dashboard UI)

When upgrade to v1.2.2-rc1, the upgrade process stuck in `Upgrading System Service`
![image](https://github.com/harvester/harvester/assets/29251855/c6d917ea-0482-480b-bd8b-a712d52c64b3)

Check the upgrade apply manifest pod log, it get error and prompt message
`Error from server (NotFound): deployments.apps "fleet-agent" not found` 

```
│ Wait for Rancher dependencies helm releases...                                                                                                             │
│ Wait for Rancher dependencies rollout...                                                                                                                   │
│ deployment "fleet-agent" successfully rolled out                                                                                                           │
│ deployment "fleet-controller" successfully rolled out                                                                                                      │
│ deployment "rancher-webhook" successfully rolled out                                                                                                       │
│ Wait for cluster settling down...                                                                                                                          │
│ Waiting for CAPI cluster fleet-local/local to be provisioned (current phase: Provisioned, current generation: 472)...                                      │
│ Waiting for CAPI cluster fleet-local/local to be provisioned (current phase: Provisioned, current generation: 472)...                                      │
│ Waiting for CAPI cluster fleet-local/local to be provisioned (current phase: Provisioned, current generation: 472)...                                      │
│ CAPI cluster fleet-local/local is provisioned (current generation: 476).                                                                                   │
│ cluster.fleet.cattle.io/local patched                                                                                                                      │
│ Error from server (NotFound): deployments.apps "fleet-agent" not found                                                                                     │
│ Stream closed EOF for harvester-system/hvst-upgrade-j4qxs-apply-manifests-7rgtw (apply)
```

**To Reproduce**
1. Prepare the 3 nodes Harvester
2. Integrate with Rancher v2.8.2
3. Provision the RKE2 v1.27.12 guest cluster 
4. Create a windows server 2019 vm
5. Create a opensuse leap 15.4 no cloud vm 
6. Open web console to access then shutdown windows and opensuse vm 
7. Upgrade Harvester to v1.2.2-rc1

**Expected behavior**

Can upgrade Harvester from v1.2.1 to v1.2.2-rc1 with Rancher v2.8.2 integrated

**Support bundle**
[supportbundle_60c51d7a-78b5-4182-8a75-bfca43a14c5d_2024-04-29T17-38-44Z.zip](https://github.com/harvester/harvester/files/15156740/supportbundle_60c51d7a-78b5-4182-8a75-bfca43a14c5d_2024-04-29T17-38-44Z.zip)

**Upgrade log**

[hvst-upgrade-j4qxs-upgradelog-archive-2024-04-29T17-37-38Z.zip](https://github.com/harvester/harvester/files/15156753/hvst-upgrade-j4qxs-upgradelog-archive-2024-04-29T17-37-38Z.zip)

**Environment**
 - Harvester ISO version: v1.2.2-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes on remote kvm machines

**Comment by bk201** [comment]
should be duplicated with https://github.com/harvester/harvester/issues/5690

**Comment by TachunLin** [comment]
Close this issue since duplicated with #5690

**Comment by TachunLin** [comment]
During testing upgrade from v1.2.1 to v1.2.2-rc2 on 3 nodes Harvester on kvm machines.
 
I also encounter the issue again to stuck in the upgrading system service
![image](https://github.com/harvester/harvester/assets/29251855/2a0fe8b6-ea10-43f8-92c0-8734d21f38c4)

With the failure `deployments.apps "fleet-agent" not found`
![image](https://github.com/harvester/harvester/assets/29251855/a9fbd413-bf9f-4bc1-b16c-a04202ab3b75)

**Comment by w13915984028** [comment]
@ibrokethecloud Seems the last PR hit another bug, the `wait_for_fleet_agent` may fetch deploy failed as the previous deploy was deleted and the new one is not created yet

https://github.com/harvester/harvester/blob/95bb0270d4b121e8b4cbaf013b92be731be3c24b/package/upgrade/upgrade_manifests.sh#L1373

```
  patch_fleet_cluster
  wait_for_fleet_agent $pre_patch_timestamp
```

**Comment by bk201** [comment]
~~Duplicated with https://github.com/harvester/harvester/issues/5690~~  ignore this. A new issue is found

**Comment by TachunLin** [comment]
Verifying on `v1.2-9b75c2bf-head` (24/05/07).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade from v1.2.1 to v1.2-head did not stuck in <strong>"upgrading system service"</strong> $~~$</summary>

  1. The upgrade can proceed to "Upgrading Node"
  
  ![image](https://github.com/harvester/harvester/assets/29251855/117d384a-40ac-40ff-adfa-e0da16d3e613)

  2. Did not encounter the "fleet-agent" not found" error in the apply manifest log

 </details>

<details><summary>$\color{red}{\textsf{FAILED}}$ Can completely upgrade to v1.2-head  $~~$</summary>

 1. The upgrade stuck in "Pre-draining" the node-1 
 
  ![image](https://github.com/harvester/harvester/assets/29251855/a10e8582-0b22-4539-9f29-fc891c12c368)

  2. Check the pre-drain log, it looping in message 
  
  ```
  Waiting for VM live-migration or shutdown...(count: 1)
  ```
  ![image](https://github.com/harvester/harvester/assets/29251855/c1e3286e-bac0-48df-8e60-a5f3f647e744)
 
  3. This may probably related to issue #5008

 </details>

### Test Information
* Test Environment: Three nodes on remote kvm machines
* Harvester version: `v1.2-9b75c2bf-head` (24/05/07)

### Verify Steps
<details><summary> Upgrade process </summary>

  1. Prepare the 3 nodes v1.2.1 Harvester
  2. Integrate with Rancher v2.8.2
  3. Provision the RKE2 v1.27.12 guest cluster
  4. Create a windows server 2019 vm
  5. Create a opensuse leap 15.4 no cloud vm
  6. Open web console to access then shutdown windows and opensuse vm
  7. Upgrade Harvester to v1.2-head


</details>

**Comment by w13915984028** [comment]
@TachunLin From your post, there seems to be one `migrating VM`

did you observe something?

![image](https://github.com/harvester/harvester/assets/31133476/2635e7b0-fe6f-4c83-8f90-fac2505a07f4)

**Comment by TachunLin** [comment]
From the RKE2 guest cluster vm events. it kept in "migrating" 
![image](https://github.com/harvester/harvester/assets/29251855/6cd5953d-f022-4ca5-95d8-8edbdca4ee64)

From the `hvst-upgrade-l25l8-pre-drain-harvester-node-1` pod log keep looping 
`echo 'Waiting for VM live-migration or shutdown...(count: 1)'` 

https://github.com/harvester/harvester/assets/29251855/b0636c53-b704-42da-86d0-a911c3604bf7

Checking the vmi log of the guest cluster rke2-v12712-pool1-efda1178-fw2k, it stuck in Migrating
![image](https://github.com/harvester/harvester/assets/29251855/e05f8e78-9410-44c1-bc0c-43688486a9d6)

Just create #5756 to track this issue.

**Comment by TachunLin** [comment]
As per discussed, since under the same environment the upgrade did not stuck in `Upgrading System Service` with apply mainifest log error `deployments.apps "fleet-agent" not found`  

We can assume the original issue stated in this ticket have been fixed. 

Thus we can close this issue and track the RKE2 guest cluster vm migrating failure in #5756
