### ISSUE TITLE
[ENHANCEMENT] refine the node-disk-manager for more flexible to storage backend

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5713]
**Is your enhancement related to a problem? Please describe.**
NDM (node-disk-manager) now only worked with Longhorn v1.
We need to refine the backend behavior to fit like longhorn v2 engine, LVM. 

**Describe the solution you'd like**
refine the backend storage provisioned.
At least support: Longhorn v1, Longhorn v2, LVM

**Describe alternatives you've considered**

**Additional context**
TBH

**Comment by bk201** [comment]
Tracked with 
- https://github.com/harvester/harvester/issues/5274
- https://github.com/harvester/harvester/issues/5724
