### ISSUE TITLE
[backport v1.2] [ENHANCEMENT] Make "LiveMigrateIfPossible" the default EvictionStrategy instead of "LiveMigrate"

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5715]
This is a backport of https://github.com/harvester/harvester/issues/5495

Original body:

**Is your enhancement related to a problem? Please describe.**

KubeVirt fires an event with a severity of Warning when a VMI exists with an EvictionStrategy of LiveMigrate and it cannot be live migrated (i.e. the VMI is configured with a HostDevice.) This Warning event can trigger alerting in monitoring stacks.

Currently, the dashboard hardcodes LiveMigrate as the eviction strategy.

**Describe the solution you'd like**

Harvester 1.2-head, 1.3-head, and master all have a new enough version of KubeVirt that supports LiveMigrateIfNecessary to avoid firing off spurious warnings.

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
tracked in https://github.com/harvester/harvester/issues/5560
