### ISSUE TITLE
vm-import-controller - Long hostname support: metadata.labels: invalid value - must be no more than 63 characters

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#5717]
Large hostnames like `sl-micro-vmx-pool1-e209b506-w28c9` may break the upgrade due to the amount of characters in the metadata label.

`time="2024-05-01T05:16:03Z" level=error msg="error syncing 'default/sl-micro-vmx-pool1-e209b506-w28c9': handler virtualmachine-import-job-change: error creating vmi: VirtualMachineImage.harvesterhci.io \"image-qzdlm\" is invalid: metadata.labels: Invalid value: \"vm-import-sl-micro-vmx-pool1-e209b506-w28c9-sl-micro-vmx-pool1-e209b506-w28c9-default-disk-0.img\": must be no more than 63 characters, requeuing"`

**Comment by ibrokethecloud** [comment]
that looks like a k8s workload, may be better option is to just recreate it?
