### ISSUE TITLE
[BUG] Can't delete Storage disk

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#5726]
**Describe the bug**
Deleting a Storage device from the UI doesn't work. I had to go into Longhorn and delete the disk after eviction/scheduling is disabled

**To Reproduce**
Hosts -> Edit Config -> Storage -> X on the Disk to remove -> Save
Hosts -> Edit Config -> Storage - Disk is still there.

Refer to https://suse.slack.com/archives/C02CN3TT61M/p1714679403477409

**Expected behavior**
Disk should be removed. Instead one has to go into Longhorn and remove the disk.

**Environment**
 - Harvester ISO version: 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): R620

**Comment by irishgordo** [comment]
@Vicente-Cheng  -thanks for this :smile: :+1:  - this looks good on Harvester Version: master-9c0a3a1-head 

On a bare-metal HP DL160, 3 Node Cluster, the disk can be removed physically from the node and then cleaned up appropriately on Harvester & Longhorn UI

![PXL_20240703_233032549](https://github.com/harvester/harvester/assets/5370752/f4114d39-05bc-402d-ae04-d5e0a1eb1258)
![PXL_20240703_233043764](https://github.com/harvester/harvester/assets/5370752/9d50b140-f19b-4eaa-9abb-a984df9e4fac)
![Screenshot from 2024-07-03 16-33-32](https://github.com/harvester/harvester/assets/5370752/4f2b6bb8-408e-401e-a844-f65d40a262a3)
![Screenshot from 2024-07-03 16-32-48](https://github.com/harvester/harvester/assets/5370752/442d4a7c-5d3e-4824-8e16-f5d1333e7205)
![Screenshot from 2024-07-03 16-32-14](https://github.com/harvester/harvester/assets/5370752/0b6ebb8c-10a6-4b53-a54d-d22cb33191b8)
![Screenshot from 2024-07-03 16-31-34](https://github.com/harvester/harvester/assets/5370752/9a1f2a01-6882-4a30-8aef-97e0e4b08b0e)

Disk was provisioned and schedulable, prior - via extra storage class etc.
