### ISSUE TITLE
[BUG] Payload Too Large when uploading images through Rancher

### ISSUE THREAD

**Issue by krumware** [harvester/harvester#5728]
**Describe the bug**

When adding an image via the web UI, when the UI is accessed via a Rancher UI and the Virtualization Management page, the image upload fails with 413 Payload Too Large. Additionally, the upload fails immediately, but the upload status and progress bar persist and do not reflect an errored state.

When uploading the same image via the Harvester UI directly, the image upload succeeds.

**To Reproduce**
1. Access Harvester through a connected Rancher Management Server UI
2. Create an Image
3. Select Upload
4. Select File
5. Click Create

**Expected behavior**

An image should begin uploading

**Support bundle**
(this may not need a support bundle)

**Environment**
 - Harvester ISO version: 1.3.0
 - Rancher UI Version: 2.8.3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare metal mini PCs, 32gb, 16cpu

**Additional context**

I recognize this may moreso be a Rancher UI issue, but wanted to first share this in context of Harvester.

**Comment by ibrokethecloud** [comment]
Hi @krumware are you able to please try this? 

https://docs.harvesterhci.io/v1.3/upload-image/#http-413-error-in-rancher-multi-cluster-management

**Comment by krumware** [comment]
Ah, thank you for the pointer! I was searching via the "Payload Too Large" instead and didn't find results.
I'll give that a try shortly and report back.

**Comment by krumware** [comment]
I confirmed that the above suggestion did resolve the issue, and was very simple. Thank you!

Steps to resolve: Update the nginx ingress manually, test resolution. Apply the configuration change to the helm deployment values of the Rancher management server, and perform an upgrade. Check for persistence of the configuration. Re-tested and confirmed.

**Comment by krumware** [comment]
complete
