### ISSUE TITLE
[BUG] Console button overlap

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5730]
**Describe the bug**

The console button in the VM details page overlaps other elements in the right column.

**To Reproduce**
1. Create a VM and assign a name with more than 20 characters to it.
2. Go to VM details page

**Expected behavior**

The console button shouldn't overlap other page's content.

We should fix the layout by avoiding the columns overlap or move the console button in another section.
**Environment**
 - Harvester UI version: v1.3.0

**Additional context**

![image](https://github.com/harvester/harvester/assets/26394656/afb94fe7-0a9e-4238-b1be-e6d25e8a9a0b)

**Comment by irishgordo** [comment]
Thanks for the fix @a110605 this looks good on Harvester Version: master-9c0a3a1-head 

I'll go ahead and close this out :+1: :smile: 
![Screenshot from 2024-07-03 17-24-12](https://github.com/harvester/harvester/assets/5370752/7a57ef46-bef9-42e9-ab27-3ff5ebbe91c4)
