### ISSUE TITLE
[BUG] Volume - create page, validation errors inconsistency

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5733]
**Describe the bug**

The validation errors in the Volume creation page should be revisited

**To Reproduce**
1. Go to Volume -> Create
2. Assign the volume name and leave the Size field empty.
3. Click on Create button

**Expected behavior**

- A validation error is displayed - `"spec.resources.requests.storage" is required`
  - It shouldn't be displayed since the Storage Class field is filled with the default value - (harvester-longhorn)
- A validation error is displayed - `Exceed maximum size 999999999 GiB!`
  - It should indicates empty Size field, instead of  max size.

**Environment**
 - Harvester UI: v1.3.0

**Additional context**

![image](https://github.com/harvester/harvester/assets/26394656/6e75e388-8cf4-41b9-9372-b1e7b63a3ded)

**Comment by a110605** [comment]
Hi @torchiaf , Storage Class field is put in `spec.storageClassName` not `spec.resources.requests.storage`.

`spec.resources.requests.storage` is the size of image and default value is null.

<img width="1265" alt="Screenshot 2024-05-12 at 9 35 36 PM" src="https://github.com/harvester/harvester/assets/5744158/7cd7aa3f-e910-48ed-9db0-88a3124efa4a">

**Comment by irishgordo** [comment]
This looks good on Harvester Version: master-9c0a3a1-head  - thanks for the fix @a110605 :smile: :+1: 
![Screenshot from 2024-07-03 17-18-58](https://github.com/harvester/harvester/assets/5370752/f56c74b8-7ec3-46ec-9f53-5d77b5f8a327)
