### ISSUE TITLE
Can harvester use the /etc/hosts file to resolve URL's when no DNS available or DNS does not have the specified record 

### ISSUE THREAD

**Issue by smalls922** [harvester/harvester#5738]
**Describe the bug**
Harvester is looking at the nameservers to resolve a URL. When trying to add Harvester as node to rancher, the cattle server URL is not able to be resolved.  I want harvester to look local to the /etc/hosts files before going to DNS

**Comment by ibrokethecloud** [comment]
k8s by default will not use the /etc/hosts file for resolution. The resolution comes from dns service running in the cluster, which delegates to the underlying dns service listed from /etc/resolv.conf

As a temporary work around you could add a host entry in coredns via coredns config map in `kube-system` namespace: https://coredns.io/plugins/hosts/
