### ISSUE TITLE
[ENHANCEMENT] Bump harvester/pcidevices KubeVirt to v1.1.1

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5746]
**Is your enhancement related to a problem? Please describe.**

KubeVirt v1.1.1 provides the node USB passthrough feature, and we're going to implement USB passthrough in harvester/pcidevices. So, we need to bump that.

**Describe the solution you'd like**

Bump the KubeVirt to v1.1.1.

**Describe alternatives you've considered**

**Additional context**

**Related Issue**
https://github.com/harvester/harvester/issues/1710

**Comment by albinsun** [comment]
Test OK on `harvester-v1.4.0-dev-20240830`, the current KubeVirt is `1.2.2-150500.8.21.1` which greater or equal to `1.1.1`.

## Environment
* `harvester-v1.4.0-dev-20240830`
  * Profile: Single nodes QEMU/KVM (48C/128G/2T)
  * ui-source: `Auto`


## Steps 
1. Fresh install <code>harvester-v1.4.0-dev-20240830</code>
   
1. <details open>
   <summary> :green_circle: Check <b>virt-operator</b> deployment greater or equal to <code>v1.1.1</code> 
   </summary>
   
   `registry.suse.com/suse/sles/15.5/virt-operator:1.2.2-150500.8.21.1`
   ![image](https://github.com/user-attachments/assets/7d36eb60-61f2-4912-ab70-8a26bb64661d)
   </details>

1. <details open>
   <summary> :green_circle: Check <b>virt-controller</b> deployment greater or equal to <code>v1.1.1</code>
   </summary>
   
   `registry.suse.com/suse/sles/15.5/virt-controller:1.2.2-150500.8.21.1`
   ![image](https://github.com/user-attachments/assets/98156f19-ab21-4322-99f8-f71d0f2f5544)
   </details>

1. <details open>
   <summary> Check <b>virt-api</b> deployment greater or equal to <code>v1.1.1</code>
   </summary>
   
   `registry.suse.com/suse/sles/15.5/virt-api:1.2.2-150500.8.21.1`
   ![image](https://github.com/user-attachments/assets/6b19bea7-0555-41b2-b292-5f9ab3627de1)
   </details>


## Reference
1. harvester/harvester/issues/6189
