### ISSUE TITLE
[HEP] vGPU Support, Rancher UI integration

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#5747]
**Is your enhancement related to a problem? Please describe.**

This is for external Rancher integration.
We want to add the possibility to Rancher customers to allocate vGPU resources for Harvester clusters.

**Describe the solution you'd like**

Adding a new 'VGPus' dropdown element to select and assign vGPUs when creating Harvester provisioned clusters.

**Additional context**

Harvester vGPU feature: https://github.com/harvester/harvester/issues/2764
Rancher UI feature: https://github.com/rancher/dashboard/issues/10588

**Comment by innobead** [comment]
@torchiaf is this for external Rancher integration? nothing we will introduce to the embedded UI in Harvester, correct?

**Comment by torchiaf** [comment]
> @torchiaf is this for external Rancher integration? nothing we will introduce to the embedded UI in Harvester, correct?

Correct, I updated the description.

**Comment by torchiaf** [comment]
Closing as not required. We linked the HEP PR to the original feature request.
