### ISSUE TITLE
[Enhancement] add publish image to the gcs on the Drone CI

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#575]
**Is your feature request related to a problem? Please describe.**
The harvester ISO image has exceeded the maximum file size limitation on the GH release which is 2G, change to use GCS to host ISO images.

**Describe the solution you'd like**
Update Drone CI to publish ISO images to the GCS.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TangStone** [comment]
validated
