### ISSUE TITLE
[BUG] "migration.sh: grep: /oem/99_custom.yaml: No such file or directory" error in journal on boot

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#5751]
**Describe the bug**

A migration script was introduced for the upgrade from harvester 1.0 to 1.1 in https://github.com/harvester/harvester/issues/2761 and https://github.com/harvester/harvester-installer/pull/334 (it changed the network configuration from using an interface named harvester-mgmt, to mgmt-br and mgmt-bo). This migration script operates on the file `/oem/99_custom.yaml`, but that was renamed to `/oem/90_custom.yaml` in v1.1.2 (see https://github.com/harvester/harvester/issues/4775). However, the migration script still refers to the old file, so on boot we see the following in the journal:

```
May 07 10:38:07 localhost migration.sh[1167]: grep: /oem/99_custom.yaml: No such file or directory
May 07 10:38:07 localhost migration.sh[1166]: harvester-mgmt not found. Skipping.
```

Needless to say the migration script won't actually have any effect under the circumstances.

**To Reproduce**

1. Boot (I assume) any version of harvester >= v1.1.2
2. Run `journalctl` and check for the "grep: /oem/99_custom.yaml: No such file or directory" error.

**Expected behavior**

No error message.

**Additional context**

We could update the migration script to refer to `/oem/90_custom.yaml`, but under the circumstances we should probably actually just delete the migration script entirely.

Note that while investigating this, I discovered harvester-installer still has another reference to `/oem/99_custom`:

https://github.com/harvester/harvester-installer/blob/c8ffa53786a64c2dce24d5c26bfa8c71c140c392/pkg/console/dashboard_panels.go#L37

This is used here:

https://github.com/harvester/harvester-installer/blob/c8ffa53786a64c2dce24d5c26bfa8c71c140c392/pkg/console/util.go#L899

...which in turn is ultimately called from here:

https://github.com/harvester/harvester-installer/blob/c8ffa53786a64c2dce24d5c26bfa8c71c140c392/pkg/console/install_panels.go#L2128

...which will only happen if `alreadyInstalled == true`, but I'm pretty sure that will only ever be set if the `harvester.install.mode=install` kernel command line option is passed. Who would do that, and why? How often is this code path exercised?

Anyway, the point is, that other reference to `/oem/99_custom.yaml` presumably also wants changing to `/oem/90_custom.yaml`.

**Comment by bk201** [comment]
@tserong I guess we can simply remove the script. The upgrade path from v1.0 to v1.1 assure the interface is already migrated.

**Comment by bk201** [comment]
@tserong Regarding the `99_custom.yml` file that you mentioned in the description. I'm not entirely sure if that's intentional.  (@ibrokethecloud to confirm)
Here is what's presented in the directory after a user runs an "install binaries only" installation , reboot, and configures a node:
```
harvester-4rltv:~ # ls /oem/9* -alh
-rw-rw-rw- 1 root root 1.1K Sep 12 09:35 /oem/90_custom.yaml
-rw------- 1 root root 184K Sep 12 09:41 /oem/99_custom.yaml
```
- When we choose "install binaries only" in the installation stage. The `90_custom.yaml` is generated for some pre-configuration in the next boot.
-  After the reboot and the user configures the node, the `99_custom.yaml` is created according to the user's inputs.

[90_custom.yaml.txt](https://github.com/user-attachments/files/16977284/90_custom.yaml.txt)
[99_custom.yaml.txt](https://github.com/user-attachments/files/16977285/99_custom.yaml.txt)

**Comment by tserong** [comment]
Interesting. My _guess_ is that we should have updated `99_custom.yaml` in the installer to `90_custom.yaml` in that case (back when this was changed in elemental in v1.1.2), but that this was just somehow missed.

**Comment by w13915984028** [comment]
Test report: the issue is resolved as expected, thanks.

In v1.4.0 newly installed cluster, no such errors.

```
harv41:/home/rancher # journalctl | grep migration -i
```
