### ISSUE TITLE
[BUG] Live migration fail when upgrade v1.2.1 to v1.2.2-rc2 due to virError

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#5755]
**Describe the bug**
During `v1.2.1` to `v1.2.2-rc2` upgrade, hit live migration fail in the pre-drain phase due to continue looping following
```
VirtualMachineInstance migration uid 46c9f7af-1f77-4f94-bf78-e8320c9a9b24 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=9, Domain=31, Message='operation failed: guest CPU doesn't match specification: missing features: waitpkg')
```

**To Reproduce**
1. :green_circle: Create 3 node `v1.2.1` cluster 
2. :green_circle: Create a VM (here located on node-2)
3. :red_circle: Upgrade to `v1.2.2-rc2`
   * node-0 and node-1 are `Succeeded`
   * node-2 stuck in `Pre-draining` due to live migration fail
     ![image](https://github.com/harvester/harvester/assets/2773781/10abedf8-ff20-441c-ae5b-d5bece01a5e1)
     ![image](https://github.com/harvester/tests/assets/2773781/be99f8a5-5ef9-40f3-8dc8-7c5db5cdb25e)
     ![image](https://github.com/harvester/tests/assets/2773781/23843a05-c9c4-4547-ad6e-6c97a9b7f11c)
   

**Expected behavior**
Upgrade successfully

**Support bundle**
[supportbundle_stuck_predraining.zip](https://github.com/harvester/harvester/files/15237710/supportbundle_stuck_predraining.zip)

**Upgrade log**
[hvst-upgrade-gvmcm-upgradelog-archive-stuck_predraining.zip](https://github.com/harvester/harvester/files/15237672/hvst-upgrade-gvmcm-upgradelog-archive-stuck_predraining.zip)

**Environment**
* Harvester
  * Version: `v1.2.1` -> `v1.2.2-rc2`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/500G)
  * ui-source: `Auto`

**Comment by albinsun** [comment]
FYI
Can also reproduce in 2 nodes cluster.
Note that there is no migration in single node and we hit VM forcely shutdown instead.

## Two nodes (8C/20G per node)
1. <details>
   <summary> :green_circle: Setup 2 nodes <code>harvester-v1.2.1</code>
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/ba4393f6-2124-4356-945d-fda5d9d1239f)
   </details>

2. <details>
   <summary> :green_circle: Create a VM (VM locates on node-1)
   </summary>
   
   ![image](https://github.com/harvester/harvester/assets/2773781/1ea86bd2-9e45-4e78-b373-e4ba2e7b2bcc)
   </details>
   
3. <details open>
   <summary> :red_circle: Upgrade to <code>v1.2.2-rc2</code>
   </summary>
   
   **node-1** is `Cordoned` and stuck in `Pre-draining`
   ![image](https://github.com/harvester/harvester/assets/2773781/a74c727b-1baa-4caf-8ddf-800d607b9143)
   VM live migration fail
   ![image](https://github.com/harvester/harvester/assets/2773781/9de37b20-a677-4e38-b8c7-bef33f24ec1c)
   ![image](https://github.com/harvester/harvester/assets/2773781/352e117f-eeb0-4d06-a13d-746d1e127f39)
   ```
   VirtualMachineInstance migration uid 5de2134c-25e2-404e-88b2-9307f54866c8 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=9, Domain=31, Message='operation failed: guest CPU doesn't match specification: missing features: waitpkg')
   ```
   </details>

* Upgrade log: [hvst-upgrade-4v6ct-upgradelog-archive-2nodes.zip](https://github.com/harvester/harvester/files/15239176/hvst-upgrade-4v6ct-upgradelog-archive-2nodes.zip)
* Support bundle: [supportbundle_2nodes.zip](https://github.com/harvester/harvester/files/15239190/supportbundle_2nodes.zip)


## Single node (16C/32G)
> [!NOTE]
> No migration since only one node.

Upgrade successfully but **VM was forced off**.
![image](https://github.com/harvester/harvester/assets/2773781/99c08997-0cde-4ed7-9337-998ef8a24fe3)

* Upgrade log: [hvst-upgrade-2xn2c-upgradelog-archive-single.zip](https://github.com/harvester/harvester/files/15238490/hvst-upgrade-2xn2c-upgradelog-archive-single.zip)
* Support bundle: [supportbundle_single.zip](https://github.com/harvester/harvester/files/15238476/supportbundle_single.zip)

**Comment by w13915984028** [comment]
could this be same root cause ase https://github.com/harvester/harvester/issues/5756, both have (rke2) VM stucking on migrating and further blocks upgrading.

**Comment by bk201** [comment]
The cause is some QEMU change between SLES SP4 and SP5. The issue happens when harvester nodes are in VMs and guests are in nested VMs. Here is the words from virtualization team:

> but the bug is rather that you see the waitpkg flag in SP4, more than the fact that you don't see it in SP5

> yes, SP5's QEMU behavior is correct, i.e., on your particular hardware, it's ok to not advertise that flag in a nested VM. It's actually SP4's QEMU that is at fault, i.e., it shouldn't advertise it in the first place, while instead it did. As I said, I can backport the fix to SP's QEMU, but this won't probably help you for that particular VM (or it would break it in even worse way, when/if the updated QEMU would reach SP4's KubeVirt)

Moving the harvester VM cpumode from host-passthrough to host-mode workaround the issue.

**Comment by albinsun** [comment]
Test can pass after let QEMU using default cpu_mode `host-model`.
Ref. https://github.com/harvester/ipxe-examples/pull/82

In short,
* `host-passthrough` will copy all feature from host cpu even libvirt does not understand.
* `host-model` will choose from supportted list which closest to host CPU.

So
For Performance:  `host-passthrough`  > `host-model`
For Reliability: `host-model` > `host-passthrough`

Ref. https://libvirt.org/formatdomain.html#cpu-model-and-topology


![image](https://github.com/harvester/harvester/assets/2773781/d87ceb84-21a7-4e10-b142-a7fe8a3a6e1d)

**Comment by albinsun** [comment]
Do not observe live migration fail after taking the workaround mentioned in https://github.com/harvester/ipxe-examples/pull/82.
Let's close this issue first and discuss whether to commit the workaround.
