### ISSUE TITLE
[BUG] Upgrade to v1.2-head stuck in pre-draining stage due to RKE2 guest cluster vm kept in Migrating state 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5756]
**Describe the bug**

While upgrade from 3 nodes v1.2.1 with rke2 guest cluster to `v1.2-9b75c2bf-head`. 

* The upgrade stuck in `Pre-draining` of the second node
* The RKE2 vm kept in `Migrating` state
  ![image](https://github.com/harvester/harvester/assets/29251855/23f6a4cb-6051-4d16-9298-349df0e62d5b)

* harvester-node-1 in `Cordoned` state
  ![image](https://github.com/harvester/harvester/assets/29251855/7ddcd838-2abd-4e30-9479-acb41b5544ad)

* Check the `hvst-upgrade-l25l8-pre-drain-harvester-node-1-mkz9k` pod log, it keeps looping in
  ```
  'Waiting for VM live-migration or shutdown...(count: 1)'
  ``` 
  ![image](https://github.com/harvester/harvester/assets/29251855/39ce6da1-70e4-494b-9138-ed3435969b0a)

* Found the `virt-launcher-rke2-v12712-pool1-efda1178-fw2kq-987n2` pod display error
  ![image](https://github.com/harvester/harvester/assets/29251855/7cfbf384-b9fd-43d9-91a3-295defbd2163)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/2a12c726-59c3-4a1f-9dff-eeeb7c61acae)

* Check the vmi log of the guest cluster `rke2-v12712-pool1-efda1178-fw2k`, it stuck in Migrating
![image](https://github.com/harvester/harvester/assets/29251855/415357d1-5f30-414d-b4b4-c1526602e775)

**To Reproduce**

1. Steps to reproduce the behavior:
2. Prepare the 3 nodes v1.2.1 Harvester 
3. Integrate with Rancher v2.8.2
4. Provision the RKE2 v1.27.12 guest cluster
5. Create a windows server 2019 vm
6. Create a opensuse leap 15.4 no cloud vm
7. Open web console to access then shutdown windows and opensuse vm
8. Upgrade Harvester to v1.2-head

**Expected behavior**

The RKE2 guest cluster should not be stuck in migrating while upgrading Harvester.
Can completely upgrade from v1.2.1 to v1.2-head or v1.2.2-rc

**Support bundle**

[supportbundle_6b4b27c2-f07c-484f-986e-868b5b501748_2024-05-07T16-02-42Z.zip](https://github.com/harvester/harvester/files/15238168/supportbundle_6b4b27c2-f07c-484f-986e-868b5b501748_2024-05-07T16-02-42Z.zip)

**Upgrade log**
[hvst-upgrade-l25l8-upgradelog-archive-2024-05-07T16-00-16Z.zip](https://github.com/harvester/harvester/files/15238165/hvst-upgrade-l25l8-upgradelog-archive-2024-05-07T16-00-16Z.zip)

**Environment**
 - Harvester ISO version:  v1.2.1 to `v1.2-9b75c2bf-head` (24/05/08)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 nodes remote kvm  machines

**Comment by w13915984028** [comment]
be same root cause with #5755 ?

**Comment by bk201** [comment]
@TachunLin it's due the the migration timeout:

```
2024-05-07T13:52:33.222175472Z {"component":"virt-launcher","kind":"","level":"error","msg":"Live migration abort detected with reason: Live migration is not completed after 4000 seconds and has been aborted","name":"rke2-v12712-pool1-efda1178-fw2kq","namespace":"default","pos":"live-migration-source.go:836","timestamp":"2024-05-07T13:52:33.221428Z","uid":"288919f0-b443-41e8-91d1-8386981d489f"}
2024-05-07T15:00:13.658733159Z {"component":"virt-launcher","kind":"","level":"error","msg":"Live migration abort detected with reason: Live migration is not completed after 4000 seconds and has been aborted","name":"rke2-v12712-pool1-efda1178-fw2kq","namespace":"default","pos":"live-migration-source.go:836","timestamp":"2024-05-07T15:00:13.658445Z","uid":"288919f0-b443-41e8-91d1-8386981d489f"}
```

Probably a performance issue. Consider changing migration policy to Auto-converge might improve: https://harvesterhci.io/kb/vm_live_migration_policy_and_configuration/#understanding-different-vm-live-migration-strategies

**Comment by TachunLin** [comment]
By adding the `Auto-converge` migration setting in the `kubevirt` CRD as sated in the KB 
https://harvesterhci.io/kb/vm_live_migration_policy_and_configuration/#changing-cluster-wide-migration-limits

Retest the 3 nodes upgrade on the similar environment with RKE2 guest cluster.
We can correctly upgrade from v1.2.1 to `v1.2.2-rc3` without stuck in RKE2 guest vm migrating.  
![image](https://github.com/harvester/harvester/assets/29251855/89b84a94-261a-4a0d-80c0-8ce97ac0e645)

To configure the setting, we can follow the steps:
1. Prepare a 3 nodes Harvester and import to Rancher 
2. Access the Harvester management node and change to root
3. Execute the command `kubectl edit kubevirt -n harvester-system`
4. Add the following configuration and save the edit
  ```
        configuration:
          migrations:
            allowAutoConverge: true
  ```
5. Trigger the upgrade to v1.2.2-rc3

Thus close this issue as found the root cause and verified with the workaround.
