### ISSUE TITLE
[ENHANCEMENT] vm-import-controller enhancements

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#5758]
**Is your enhancement related to a problem? Please describe.**

EPIC to track various vm-import-controller enhancements requested by the community. 

Some vmare specific ones are as follows:
* support for efi mode for migrated VM's
* support for different storage classes for migrated VM's
* change reconcile behaviour to not retry migrations due to failure as this may cause unnecessary export tasks on source cluster
* support for different bus types on migrated VM's to avoid having to install virtio drivers on source VM

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ibrokethecloud** [comment]
related issues: 
https://github.com/harvester/harvester/issues/5717
https://github.com/harvester/harvester/issues/5184

**Comment by ibrokethecloud** [comment]
To test the changes:

The following tests are applicable for both Openstack and Vmware source environments

BIOS based VM Migration:
* Create a VM with BIOS mode
* Based on source disk bus specified the following will be observed for vmware sources
    * scsi source buses will be mapped to scsi bus in harvester
    * non scsi source buses will be mapped to sata bus in harvester
    * Openstack only supports virtio bus, so no change will be observed
* Create VirtualMachineImport and VM should migrate and boot correctly

EFI Based VM Migration:
* Create a VM with EFI mode
* Based on source disk bus specified the following will be observed for vmware sources
    * scsi source buses will be mapped to scsi bus in harvester
    * non scsi source buses will be mapped to sata bus in harvester
    * Openstack only supports virtio bus, so no change will be observed
* Create VirtualMachineImport and VM should migrate and boot correctly
* New imported VM will have EFI mode set

EFI Based VM with secure boot migration:
* Create a VM with EFI mode + secure boot
* Based on source disk bus specified the following will be observed for vmware sources
    * scsi source buses will be mapped to scsi bus in harvester
    * non scsi source buses will be mapped to sata bus in harvester
    * Openstack only supports virtio bus, so no change will be observed
* Create VirtualMachineImport and VM should migrate and boot correctly
* New imported VM will have EFI mode + secure boot set

EFI Based VM with secure boot migration:
* Create a VM with EFI mode + secure boot
* Based on source disk bus specified the following will be observed for vmware sources
    * scsi source buses will be mapped to scsi bus in harvester
    * non scsi source buses will be mapped to sata bus in harvester
    * Openstack only supports virtio bus, so no change will be observed
* Create VirtualMachineImport and VM should migrate and boot correctly
* New imported VM will have EFI mode + secure boot set

Using a custom storage class:
* Use a VM from any of the above scenarios
* During creation of VirtualMachineImport, specify the field `storageClass`

```
apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: opensuse-import
  namespace: default
spec:
  virtualMachineName: "gm-opensuse-base"
  storageClass: single-replica
```
* Post migration the PVC and virtual machine image should be using the specified non-default storage class

**Comment by irishgordo** [comment]
@ibrokethecloud out of curiousity is:
 ```
 EFI Based VM with secure boot migration:

    Create a VM with EFI mode + secure boot
    Based on source disk bus specified the following will be observed for vmware sources
        scsi source buses will be mapped to scsi bus in harvester
        non scsi source buses will be mapped to sata bus in harvester
        Openstack only supports virtio bus, so no change will be observed
    Create VirtualMachineImport and VM should migrate and boot correctly
    New imported VM will have EFI mode + secure boot set

 ```
 Mentioned twice? - is it intended to be "BIOS w/ secure boot?"

**Comment by irishgordo** [comment]
@TachunLin  ^ for a small mention, it is duplicated, the plan should just be:


BIOS based VM Migration:

    Create a VM with BIOS mode
    Based on source disk bus specified the following will be observed for vmware sources
        scsi source buses will be mapped to scsi bus in harvester
        non scsi source buses will be mapped to sata bus in harvester
        Openstack only supports virtio bus, so no change will be observed
    Create VirtualMachineImport and VM should migrate and boot correctly

EFI Based VM Migration:

    Create a VM with EFI mode
    Based on source disk bus specified the following will be observed for vmware sources
        scsi source buses will be mapped to scsi bus in harvester
        non scsi source buses will be mapped to sata bus in harvester
        Openstack only supports virtio bus, so no change will be observed
    Create VirtualMachineImport and VM should migrate and boot correctly
    New imported VM will have EFI mode set

EFI Based VM with secure boot migration:

    Create a VM with EFI mode + secure boot
    Based on source disk bus specified the following will be observed for vmware sources
        scsi source buses will be mapped to scsi bus in harvester
        non scsi source buses will be mapped to sata bus in harvester
        Openstack only supports virtio bus, so no change will be observed
    Create VirtualMachineImport and VM should migrate and boot correctly
    New imported VM will have EFI mode + secure boot set

Using a custom storage class:

    Use a VM from any of the above scenarios
    During creation of VirtualMachineImport, specify the field storageClass

apiVersion: migration.harvesterhci.io/v1beta1
kind: VirtualMachineImport
metadata:
  name: opensuse-import
  namespace: default
spec:
  virtualMachineName: "gm-opensuse-base"
  storageClass: single-replica

    Post migration the PVC and virtual machine image should be using the specified non-default storage class

**Comment by albinsun** [comment]
Test PASS in general, close as done.
Note that we found that BIOS based VMs has no IP address, track by #6644 .
![image](https://github.com/user-attachments/assets/d69c13af-5fa3-4372-a83b-8f9d63f6f0cc)

### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: Single node QEMU/KVM (48C/128G/1.6T)
  * ui-source: Auto


### Prerequisite
1. Having VMWare endpoint
2. Having OpenStack endpoint
3. <details>
   <summary> Create VM network <i>mgmt-vlan1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/fbe8707c-9772-4cff-9455-9a375dae7732)
   </details>
1. <details>
   <summary> Create Storage Class <i>mysc</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/aba2bdf1-aaf8-4b20-88f0-1b4e99be2bee)
   </details>
4. <details>
   <summary> Enable <b>vm-import-controller</b> addon 
   </summary>
   
   * Deploy Successful
     ![image](https://github.com/user-attachments/assets/11e9708a-7d50-4612-819b-7258ab05b193)
   * Config
     ![image](https://github.com/user-attachments/assets/5317714b-9d79-4de3-a653-cf07841411bf)
   </details>
   
   > Ref. https://docs.harvesterhci.io/v1.3/advanced/addons/vmimport

### Scenario
1. Setup Source Hypervisor [^1]
   * :green_circle: VMWare 
     <details>
     <summary> <i>Given</i> create <i>Secret</i> for VMWare endpoint 
     </summary>
     
     ```
      # cat secret-vmware.yaml 
      apiVersion: v1
      kind: Secret
      metadata: 
        name: vsphere-credentials
        namespace: default
      stringData:
        "username": "USERNAME"
        "password": "PASSWORD"

      # kubectl apply -f secret-vmware.yaml 
      secret/vsphere-credentials created

      # kubectl get Secret vsphere-credentials
      NAME                  TYPE     DATA   AGE
      vsphere-credentials   Opaque   2      40s
     ```
     </details>
  
     <details>
     <summary> <i>When</i> create a <i>VmwareSource</i> for VMWare endpoint
     </summary>

      ```
      # cat vmwaresource.yaml
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: VmwareSource
      metadata:
        name: vcsim
        namespace: default
      spec:
        endpoint: "https://ENDPOINT/sdk"
        dc: "DATACENTER"
        credentials:
          name: vsphere-credentials
          namespace: default

      # kubectl apply -f vmwaresource.yaml 
      vmwaresource.migration.harvesterhci.io/vcsim created
      ```
     </details>
  
     <details>
     <summary> <i>Then</i> created <i>VmwareSource</i>'s STATUS should be <i>clusterReady</i>
     </summary>

      ```
      # kubectl get VmwareSource
      NAME    STATUS
      vcsim   clusterReady
      ```
     </details>

   * :green_circle: OpenStack
     <details>
     <summary> <i>Given</i> create <i>Secret</i> for OpenStack endpoint 
     </summary>

      ```
      # cat secret-openstack.yaml 
      apiVersion: v1
      kind: Secret
      metadata: 
        name: microstack-credentials
        namespace: default
      stringData:
        "username": "USERNAME"
        "password": "PASSWORD"
        "project_name": "demo"
        "domain_name": "default"
        "ca_cert": "pem-encoded-ca-cert"
      
      # kubectl apply -f secret-openstack.yaml 
      secret/microstack-credentials created

      # kubectl get Secret microstack-credentials
      NAME                     TYPE     DATA   AGE
      microstack-credentials   Opaque   5      11s
     ```
     </details>
  
     <details>
     <summary> <i>When</i> create a <i>OpenstackSource</i> for OpenStack endpoint
     </summary>

      ```
      # cat openstacksource.yaml 
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: OpenstackSource
      metadata:
        name: microstack
        namespace: default
      spec:
        endpoint: "ENDPOINT"
        region: "REGION"
        credentials:
          name: microstack-credentials
          namespace: default
      # 
      # kubectl apply -f openstacksource.yaml 
      openstacksource.migration.harvesterhci.io/microstack created
      ```
     </details>
  
     <details>
     <summary> <i>Then</i> created <i>OpenstackSource</i> STATUS should be <i>clusterReady</i>
     </summary>

      ```
      # kubectl get OpenstackSource
      NAME         STATUS
      microstack   clusterReady
      ```
     </details>


1. Import EFI Based VM [^2][^3]
   * :green_circle: VMWare
     <details>
     <summary> <i>Given</i> a running EFI based VM <i>dl-opensue-uefi</i>
     </summary>
     
     * EFI
       ![image](https://github.com/user-attachments/assets/a7977e72-4b7b-4a10-bb52-e301107bd007)
     * Running
       ![image](https://github.com/user-attachments/assets/fdc937fc-fb01-4c00-8e14-1341c8030d94)
     </details>
    
     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
     </summary>

      ```
      # cat vmware-VirtualMachineImport.yaml 
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: VirtualMachineImport
      metadata:
        name: vmware-efi
        namespace: default
      spec: 
        virtualMachineName: "dl-opensue-uefi"
        networkMapping:
        - sourceNetwork: "VM Network"
          destinationNetwork: "default/mgmt-vlan1"
        sourceCluster: 
          name: vcsim
          namespace: default
          kind: VmwareSource
          apiVersion: migration.harvesterhci.io/v1beta1
      # 
      # kubectl apply -f vmware-VirtualMachineImport.yaml 
      virtualmachineimport.migration.harvesterhci.io/vmware-efi created
      ```
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>

     ![image](https://github.com/user-attachments/assets/9b5f9a34-6b05-47d0-b80b-3e3d48b052de)
     </details>
     
     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is checked but not <b>Secure Boot</b>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/1672741f-d470-49f2-a922-b5e05d413652)
     </details>

   * :green_circle: OpenStack
     <details>
     <summary> <i>Given</i> a running EFI based VM <i>uefi-only-no-secure-boot</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/dbdd5214-cd55-4e4f-889f-10fdf59cf392)
     </details>
    
     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
     </summary>

      ```
      # cat openstack-VirtualMachineImport.yaml 
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: VirtualMachineImport
      metadata:
        name: openstack-efi
        namespace: default
      spec: 
        virtualMachineName: "uefi-only-no-secure-boot"
        networkMapping:
        - sourceNetwork: "shared"
          destinationNetwork: "default/mgmt-vlan1"
        sourceCluster: 
          name: microstack
          namespace: default
          kind: OpenstackSource
          apiVersion: migration.harvesterhci.io/v1beta1
      # 
      # kubectl apply -f openstack-VirtualMachineImport.yaml 
      virtualmachineimport.migration.harvesterhci.io/openstack-efi created
      ```
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>
     
     ![image](https://github.com/user-attachments/assets/56ab65c5-445d-429e-92ac-495f1de33233)
     </details>
    
     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is checked but not <b>Secure Boot</b>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/9d24ee2b-34de-431b-ac30-92d44504503d)
     </details>


1. Import EFI + Secure Boot Based VM [^2][^3]
   * :green_circle: VMWare
      <details>
      <summary> <i>Given</i> a running EFI + Secure Boot based VM <i>dl-opensuse-uefi-secure</i>
      </summary>
      
      * Running
        ![image](https://github.com/user-attachments/assets/7e3a11b3-d3b6-43bb-9726-de99df8689a8)
      * EFI + Secure Boot
        ![image](https://github.com/user-attachments/assets/bfd75d9b-865b-451d-9443-3c24c03ca07f)
      </details>
      
      <details>
      <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
      </summary>
      
      ![image](https://github.com/user-attachments/assets/c2a80eaa-6175-4276-8ab3-24038359a649)
      </details>
      
      <details>
      <summary> <i>Then</i> VM should be import and boot correctly
      </summary>
      
      ![image](https://github.com/user-attachments/assets/bb82c592-e4c2-41c2-ad3f-ee085633fd24)
      </details>
      
      <details>
      <summary> <i>And</i> in <b>Advanced Options</b> page, both <b>Booting in EFI mode</b> and <b>Secure Boot</b> are checked
      </summary>
      
      ![image](https://github.com/user-attachments/assets/42d60a92-8a1a-406b-a3c6-44311b75fc6c)
      </details>

   * :green_circle: OpenStack
      <details>
      <summary> <i>Given</i> a running EFI + Secure Boot based VM <i>opensuse-uefi-secure</i>
      </summary>
      
      ![image](https://github.com/user-attachments/assets/5e3b52df-b4dd-4883-8da4-8bee410bcf4b)
      </details>
      
      <details>
      <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
      </summary>
      
      ![image](https://github.com/user-attachments/assets/b246216f-4c46-4028-badb-f7263ef53b47)
      </details>
      
      <details>
      <summary> <i>Then</i> VM should be import and boot correctly
      </summary>
      
      ![image](https://github.com/user-attachments/assets/ab99ab9d-a02d-4a50-9888-2f8781c235e9)
      </details>
      
      <details>
      <summary> <i>And</i> in <b>Advanced Options</b> page, both <b>Booting in EFI mode</b> and <b>Secure Boot</b> are checked
      </summary>
      
      ![image](https://github.com/user-attachments/assets/6e07048e-e2f7-4bcd-b63a-557680cc7559)
      </details>

1. Import using Custom Storage Class
   * :yellow_circle: VMWare
     <details>
     <summary> <i>Given</i> a running BIOS based VM <i>dl-ubuntu-bios</i>
     </summary>
     
     * BIOS based
       ![image](https://github.com/user-attachments/assets/ad239002-2eb5-4d1d-910c-405092fcc46a)
     * Running
       ![image](https://github.com/user-attachments/assets/e69fa935-b9d3-4fcd-99b5-abf391d7ec51)
     </details>
    
     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i> with customized storage class <i>mysc</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/f02891b5-0618-44e1-ab15-d0cf7adbb4e4)
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>
     
     * Running
       ![image](https://github.com/user-attachments/assets/5b7bec9b-6fe9-4db6-826f-ea28157d7985)
     * Shows IP
       ![image](https://github.com/user-attachments/assets/5a05beb9-e226-4dad-8b3a-3a638d11a0a8)
       ![image](https://github.com/user-attachments/assets/d69c13af-5fa3-4372-a83b-8f9d63f6f0cc)
     </details>

     > :warning: IP does NOT shown

     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is not checked
     </summary>
     
     ![image](https://github.com/user-attachments/assets/3266877b-0769-4767-9419-c81898801d12)
     </details>

     <details>
     <summary> <i>And</i> storage class should be <i>mysc</i>
     </summary>
     
     * Volume
       ![image](https://github.com/user-attachments/assets/ea9328ba-d5b1-42c2-a4e4-18aa32425d47)
     * Image
       ![image](https://github.com/user-attachments/assets/6399479a-dd22-406a-a1a6-d4ee96ccfa50)
     </details>


   * :yellow_circle: OpenStack
     <details>
     <summary> <i>Given</i> a running BIOS based VM <i>ubuntu-bios</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/1b6eac9a-86f7-4901-af81-32b6c8b15dd3)
     </details>

     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i> with customized storage class <i>mysc</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/fdb2f0de-8f59-4a6e-a7d4-ae41ecf9dc27)
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>
     
     * Running
       ![image](https://github.com/user-attachments/assets/5b7bec9b-6fe9-4db6-826f-ea28157d7985)
     * Shows IP
       ![image](https://github.com/user-attachments/assets/5a05beb9-e226-4dad-8b3a-3a638d11a0a8)
       ![image](https://github.com/user-attachments/assets/d69c13af-5fa3-4372-a83b-8f9d63f6f0cc)
     </details>

     > :warning: IP does NOT shown

     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is not checked
     </summary>
     
     ![image](https://github.com/user-attachments/assets/695035ef-cd7c-4a03-8457-0a2907ec3ff8)
     </details>

     <details>
     <summary> <i>And</i> storage class should be <i>mysc</i>
     </summary>
     
     * Volume
       ![image](https://github.com/user-attachments/assets/e234ea10-d914-45aa-8eea-7edd2853c337)
     * Image
       ![image](https://github.com/user-attachments/assets/88bc2344-20b0-405c-8a02-55aca48c2114)
     </details>

1. Import BIOS based VM [^2][^3]
   * :yellow_circle: VMWare
     <details>
     <summary> <i>Given</i> a running BIOS based VM <i>dl-ubuntu-bios</i>
     </summary>
     
     * BIOS based
       ![image](https://github.com/user-attachments/assets/ad239002-2eb5-4d1d-910c-405092fcc46a)
     * Running
       ![image](https://github.com/user-attachments/assets/e69fa935-b9d3-4fcd-99b5-abf391d7ec51)
     </details>
    
     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
     </summary>

      ```
      # cat vmware-VirtualMachineImport.yaml 
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: VirtualMachineImport
      metadata:
        name: vmware-bios
        namespace: default
      spec: 
        virtualMachineName: "dl-ubuntu-bios"
        networkMapping:
        - sourceNetwork: "VM Network"
          destinationNetwork: "default/mgmt-vlan1"
        sourceCluster: 
          name: vcsim
          namespace: default
          kind: VmwareSource
          apiVersion: migration.harvesterhci.io/v1beta1
      
      # kubectl apply -f vmware-VirtualMachineImport.yaml 
      virtualmachineimport.migration.harvesterhci.io/vmware-bios created
      # 
      ```
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>
     
     ![image](https://github.com/user-attachments/assets/c0b790f9-ddc4-4bf9-a768-432cfac65a66)
     </details>
     
     > :warning: IP does NOT shown

     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is not checked
     </summary>
     
     ![image](https://github.com/user-attachments/assets/cac48aa0-a8f8-4c74-beb2-7f28baaae95c)
     </details>


   * :yellow_circle: OpenStack
     <details>
     <summary> <i>Given</i> a running BIOS based VM <i>ubuntu-bios</i>
     </summary>
     
     ![image](https://github.com/user-attachments/assets/6c69b6fb-5070-4734-a150-e95b39884427)
     </details>

     <details>
     <summary> <i>When</i> import VM by creating <i>VirtualMachineImport</i>
     </summary>

      ```
      # cat openstack-VirtualMachineImport.yaml 
      apiVersion: migration.harvesterhci.io/v1beta1
      kind: VirtualMachineImport
      metadata:
        name: openstack-bios
        namespace: default
      spec: 
        virtualMachineName: "ubuntu-bios"
        networkMapping:
        - sourceNetwork: "shared"
          destinationNetwork: "default/mgmt-vlan1"
        sourceCluster: 
          name: microstack
          namespace: default
          kind: OpenstackSource
          apiVersion: migration.harvesterhci.io/v1beta1
      # 
      # kubectl apply -f openstack-VirtualMachineImport.yaml 
      virtualmachineimport.migration.harvesterhci.io/openstack-bios created
      # 
      ```
     </details>
    
     <details>
     <summary> <i>Then</i> VM should be import and boot correctly
     </summary>
     
     ![image](https://github.com/user-attachments/assets/2b5e10ee-88e0-4be6-9382-dc06cf1a1954)
     </details>
     
     > :warning: IP does NOT shown

     <details>
     <summary> <i>And</i> in <b>Advanced Options</b> page, <b>Booting in EFI mode</b> is not checked
     </summary>
     
     ![image](https://github.com/user-attachments/assets/687a5631-470c-4428-b39b-5556c9761b16)
     </details>

### Supportbundle


### QA Check List
1. Update labels
   - [ ] This ticket: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
   - [ ] tests ticket: harvester/tests/issues/1291


[^1]: https://docs.harvesterhci.io/v1.3/advanced/addons/vmimport#sources
[^2]: https://docs.harvesterhci.io/v1.3/advanced/addons/vmimport#virtualmachineimport
[^3]: https://harvester.github.io/tests/manual/advanced/addons/5846-vm-import-enhancement/
