### ISSUE TITLE
[FEATURE] Enhanced Monitoring

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#576]
1. We need to expose Prometheus endpoints.
2. We need the ability to monitor VM/storage/network better in the UI.

Updated:
We also want to have the ability to collect hardware information, especially hardware failures, from the node. So the user can know and prepare for the hardware failure.
The common tool used for that will be ipmitool, smartctl etc.
Some existing exporters for Prometheus: https://github.com/soundcloud/ipmi_exporter

**Comment by guangbochen** [comment]
An known issue: https://github.com/harvester/harvester/issues/1289

**Testing Plan:**
1. harvester monitoring should be enabled by default when installed from the ISO
2. check if the monitoring pod are up and running
```
$kubectl get pod -n cattle-monitoring-system
NAME                                                     READY   STATUS    RESTARTS   AGE
prometheus-rancher-monitoring-prometheus-0               3/3     Running   1          3m47s
rancher-monitoring-grafana-7f54b7d8bc-8pj4c              3/3     Running   0          106s
rancher-monitoring-kube-state-metrics-744b9448f4-2tgwj   1/1     Running   0          4m4s
rancher-monitoring-operator-754bcd8cb4-w85jz             1/1     Running   0          4m4s
rancher-monitoring-prometheus-adapter-77568b975-k49n5    1/1     Running   0          4m4s
rancher-monitoring-prometheus-node-exporter-nsmzt        1/1     Running   0          4m4s
```
3. check if two built-in harvester monitoring dashboards are loaded via:
```
$kubectl get configmap -n cattle-dashboards | grep har
harvester-vm-dashboard                                 1      9m14s
harvester-vm-detail-dashboard                          1      9m14s
```
4. check prometheusrules and servicemonitors are exist
```
$ kubectl get servicemonitor -n cattle-monitoring-system
cattle-monitoring-system   prometheus-kubevirt-rules               28m
cattle-monitoring-system   rancher-monitoring-grafana              27m
cattle-monitoring-system   rancher-monitoring-kube-state-metrics   27m
cattle-monitoring-system   rancher-monitoring-node-exporter        27m
cattle-monitoring-system   rancher-monitoring-operator             27m
cattle-monitoring-system   rancher-monitoring-prometheus           27m

$kubectl get prometheusrules -n harvester-system
NAME                        AGE
prometheus-kubevirt-rules   29m
```
5. check graphs from the dashboard page and VM details page are showing correctly.
![image](https://user-images.githubusercontent.com/4569037/134799398-b678e000-034c-4f23-9a03-2a8b5b4d2bcd.png)
![image](https://user-images.githubusercontent.com/4569037/134799408-e5545ad1-edce-440f-af29-d2610d1b6ca0.png)

**Comment by guangbochen** [comment]
close as verified in the Harvester v0.3.0-rc1.
