### ISSUE TITLE
[FEATURE] GUI support USB Passthrough

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5763]
**Is your feature request related to a problem? Please describe.**

Regarding #1710, we need to implement USB Passthrough on the node. This ticket is for frontend.

**Describe the solution you'd like**

According to HEP https://github.com/harvester/harvester/issues/5430 to implement solution.

**TODO**

- [x] Need GUI documentation to guide this feature https://github.com/harvester/docs/pull/638

**Comment by irishgordo** [comment]
Thanks for all the work with this @torchiaf , in general this looks great :smile: :+1:  

I'll go ahead and close this out :smile: :+1: 


1. :green_circle: USB device can be attached and used by VM a variety (webcam, usb network adapters, usb storage, etc.)
2. :green_circle: Multiple USB devices can be attached and used by VM
3. :green_circle: Can not migrate VM to another node when using USB devices
4. :green_circle: USB devices can be removed from a VM and used on another VM
5. :green_circle: USB devices get cleaned up when not present on physical nodes
6. :green_circle: Can restore a VM with USB devices (snapshot & backup)
7. :green_circle: Can clone a powered off VM with USB devices
8. :green_circle: Can have multiple of same USB products used in VM (same vendor/product-model)
9. :green_circle: USB device enabling works with both: integrated-usb-controller-hub and PCIe/PCI USB Controller Card(s) on node -> all USB devices are shown available from all available sources 
10. :green_circle: USB devices can move locations on Node(s) and still be accessible 
11. :green_circle: If USB Devices being used by VM from USB PCI Controller, the PCI USB Controller can not be enabled, from PCI Devices

Harvester v1.4.0-rc2
2 Node Cluster (1 Dell PowerEdge R720, 1 HP DL 160 Gen9)

USB Integrated & PCI Controller:
```bash
rancher@test-r720-v140rc2:~> sudo lspci | grep -ie "USB"
00:1a.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #2 (rev 05)
00:1d.0 USB controller: Intel Corporation C600/X79 series chipset USB2 Enhanced Host Controller #1 (rev 05)
06:00.0 USB controller: ASMedia Technology Inc. ASM2142/ASM3142 USB 3.1 Host Controller
0b:00.0 USB controller: ASMedia Technology Inc. ASM2142/ASM3142 USB 3.1 Host Controller
```

Supporting Screengrabs:

![Screenshot from 2024-10-16 10-58-06](https://github.com/user-attachments/assets/fda3d868-3514-4281-8c9f-d20a71e443bb)

![Screenshot from 2024-10-16 10-55-43](https://github.com/user-attachments/assets/c3a66789-f014-4558-b2ed-47ab277532dc)

![Screenshot from 2024-10-16 10-04-22](https://github.com/user-attachments/assets/ee311f32-7f1a-4626-a960-5bd7c647faf7)

![Screenshot from 2024-10-15 13-59-14](https://github.com/user-attachments/assets/4b4441a0-aa22-4f9f-b963-48866eee982a)

![Screenshot from 2024-10-15 13-58-42](https://github.com/user-attachments/assets/e56bb0d0-545a-41e7-85cf-c83463bf9920)

![Screenshot from 2024-10-15 13-57-57](https://github.com/user-attachments/assets/c3171390-2ae6-4332-a2de-109650367fb0)

![Screenshot from 2024-10-15 13-57-11](https://github.com/user-attachments/assets/17f53302-8d70-4b58-929d-8da9d5a92a85)



I'll go ahead and close this out :smile: :+1: 


I'll leave open the additional issues found w/ USB testing to track:
- #6790 
- #6805 
- #6806 
- #6809 
- #6779
