### ISSUE TITLE
[ENHANCEMENT] A better reserved memory value for VMs

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5768]
**Is your enhancement related to a problem? Please describe.**

We reserve 100MB of memory since https://github.com/harvester/harvester/pull/1543, but we still see some VMs OOM. 

**Describe the solution you'd like**

- We can do some benchmarks and fine-tune a good default value.
- We should have a document or KB on adjusting the values based on VM workload.

**Describe alternatives you've considered**

**Additional context**

A customer is hitting the issue with the default value.
- It's a 64GB VM.
- The VM is running RKE2 guest cluster.
- The VM has many hot-plugging volumes. This should be taken into consideration, more volumes might increase memory usage.

**Comment by bk201** [comment]
@w13915984028 Please help check this issue. cc @innobead

**Comment by w13915984028** [comment]
From the investigation till now, there are still some doubts to be digged.

The main question is:
The Cgroup memory limit for a VM is set to: [(1) guest OS usable memory][(2)all kinds of reservation]

When OOM happens, it's the (1) + (2)  > limit, and normally, (1) >>>>> (2), it will mean (1) will use a big amount of memory to trigger the OOM.

**Comment by tserong** [comment]
In case it helps with the investigation, someone on the Rancher Users slack ran into the OOM issue back in March when doing heavy IO on a database in a VM, and provided a support bundle there. The discussion is at https://rancher-users.slack.com/archives/C01GKHKAG0K/p1710208792865519 but note that we're probably getting pretty close to the 90 day message limit on Slack in that conversation.

**Comment by bk201** [comment]
@w13915984028 Do you have any update on this issue?

**Comment by w13915984028** [comment]
The current summary is on https://github.com/w13915984028/harvester-develop-summary/blob/main/oom-related-issue-investigation.md, we will optimize the VM to have options for user:

(1) Set a higher reserved memroy by default, update documents about why to do so and how

(2) Remove the memory limit of a VM, keep the wanted memroy of guest VM. e.g. A VM can have upto 16GB memory, but the cgroup of this VM's backing POD, has no memory uplimit. This is useful for mission-critical VM which should never be OOM killed.

User will decide to use which kind of otpion for each VM.

**Comment by w13915984028** [comment]
@torchiaf Please also help remove the `Show More` from UI to expose the `Reserved Memory` option directly, it is very important to adjust this value accordingly. thanks.

![image](https://github.com/user-attachments/assets/7f23220e-bfdf-490a-a015-115b4e23991d)

**Comment by a110605** [comment]
> [WIP]Set higher default reserved memory for VM #6177

How about simply move reserved memory input box out of `Read More` block ? 
User can easily see the reserved memory number. See PR https://github.com/harvester/dashboard/pull/1117

**Comment by w13915984028** [comment]
@a110605 Moving `Reserved Memory` out of the `Read More` is also OK.

**Comment by w13915984028** [comment]
@a110605 @torchiaf

To solve this issue, PR https://github.com/harvester/harvester/pull/6438 is added, which defines a new setting:

`additional-guest-memory-overhead-ratio`

This setting itself is a string, can be empty or a valid float64 value string like "0.0" or "1.5" or "3.9", range:[0, 1..10]; all the checks are done at backend validator, it will deny the input like "-5", "not a number", "100". 

This new setting also needs the help from UI to expose it on Harvester setting. Do you want a new issue for UI or stick to this issue? thanks.

**Comment by albinsun** [comment]
Setting **additional-guest-memory-overhead-ratio** seems not included in `v1.4.0-dev-20240918`.
Perhaps due to [UI PR](https://github.com/harvester/dashboard/pull/1155) just merged last week.
Will test in _v1.4.0-rc1_.
![image](https://github.com/user-attachments/assets/47218c6c-d059-4b25-a19a-a33f5c33b46b)

Reference
* Reserved Memory: https://66d61b2b7a08694d93628b0f--harvester-preview.netlify.app/v1.4/vm/index/#reserved-memory
* additional-guest-memory-overhead-ratio: https://66d61b2b7a08694d93628b0f--harvester-preview.netlify.app/v1.4/advanced/index/#additional-guest-memory-overhead-ratio

**Comment by albinsun** [comment]
Hi @w13915984028,
My current understanding is:
* **Reserved Memory**: Per VM configuration.
* _additional-guest-memory-overhead-ratio_: Global configuration, affects all VMs.

If so, when user update `additional-guest-memory-overhead-ratio`, how/when existing VMs' affected? Do we need to explicitly restart or something?

cc. @torchiaf and @bk201

**Comment by w13915984028** [comment]
@albinsun

1. Edit VM spec from GUI (e.g. a new memory size), VM is  rebooted by GUI
![image](https://github.com/user-attachments/assets/59ed44d7-6f7b-424d-ad8a-ccc3c0fc3c1c)

2. Edit vm spec from kubectl, VM is not rebooted automatically, but there is a hint about generation
![image](https://github.com/user-attachments/assets/222af2cb-5196-4a27-955c-beaa04294a76)

3. Edit the settings `additional-guest-memory-overhead-ratio` from GUI or kubectl;  all running VMs are not affected, unless the VMs are rebooted. The resource limitation is computed and set on the namesapce & pod objects, they are the running instances of VM, for existing objects, they are not affected.  As this is a global setting, avoid rebooting all VMs directly are also  safe. (I updated the document PR to emphasis this point https://github.com/harvester/docs/pull/615/commits/451054363d670c720c96a4152e90f4af3ae46146)

default ratio 1.5:   vm 1 cpu 2 Gi, and the related pod resources limits
```
      resources:
        limits:
          cpu: "1"
          devices.kubevirt.io/kvm: "1"
          devices.kubevirt.io/tun: "1"
          devices.kubevirt.io/vhost-net: "1"
          memory: "2404034561"  // computed from default ratio 1.5
```

change ratio to 2, re-start the vm, and the related pod resources limits
```
      resources:
        limits:
          cpu: "1"
          devices.kubevirt.io/kvm: "1"
          devices.kubevirt.io/tun: "1"
          devices.kubevirt.io/vhost-net: "1"
          memory: "2660585561"  // computed from new ratio 2.0
```

**Comment by torchiaf** [comment]
@albinsun @w13915984028  I'd like to add a message when editing the `additional-guest-memory-overhead-ratio` saying that VMs need to be restarted for the new settings to take effect.
WDYT ?

**Comment by w13915984028** [comment]
@torchiaf Good idea, thanks.

**Comment by albinsun** [comment]
Configuration test PASS.


## Environment
* Harvester
  * Version: v1.4.0-rc1
  * Profile: 3 nodes QEMU/KVM (include a witness node)
  * ui-source: Auto


## Prerequisite
1. Create image <i>ubuntu-22.04-jammy-server-cloudimg-amd64.img</i>
1. Create VM network <i>mgmt-vlan1</i>


## Scenario
### Configuration value
#### :green_circle: Positive
1. <details>
   <summary> Default value is <code>1.5</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/7107f42a-735d-469f-8824-33523affd28f)
   </details>

1. <details>
   <summary> Set to <code>2</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/26621300-8be2-48fd-8367-0906f1ff0a83)
   </details>

1. <details>
   <summary> Set to <code>1.0</code>
   </summary>

   ![image](https://github.com/user-attachments/assets/f83aa88d-2871-4f20-96c9-90d5f45e1d87)
   </details>

1. <details>
   <summary> Set by <b>Use the default value</b>
   </summary>

   ![image](https://github.com/user-attachments/assets/1723b61f-7826-4dc7-9ebd-2641982b536c)
   </details>

1. <details>
   <summary> Set to <code>0</code>, value is <code>0</code> (disabled)
   </summary>

   ![image](https://github.com/user-attachments/assets/5c77e518-6b43-4028-be68-9cd32981da12)
   </details>

1. <details>
   <summary> Set to <code>empty</code>, value is <code>1.5</code> (default value)
   </summary>

   ![image](https://github.com/user-attachments/assets/2e8a3a0f-bca0-4172-bfe2-c893482f4f2b)
   </details>

#### :green_circle: Negtive
1. <details>
   <summary> Set to <code>100</code>, should fail.
   </summary>

   ![image](https://github.com/user-attachments/assets/7ac6810b-cb82-45be-b070-1e439ab4c785)
   </details>

1. <details>
   <summary> Set to <code>0.1</code>, should fail.
   </summary>

   ![image](https://github.com/user-attachments/assets/980bd238-2535-446b-8a75-5640bd2d423e)
   </details>

1. <details>
   <summary> Set to <code>-1</code>, should fail.
   </summary>

   ![image](https://github.com/user-attachments/assets/23d59408-aecb-4edb-aa7e-0f82be1f746e)
   </details>

1. <details>
   <summary> Set to string, should fail.
   </summary>

   ![image](https://github.com/user-attachments/assets/022e9935-55ad-4c17-8208-ba1d7d308afd)
   </details>

**Comment by albinsun** [comment]
Hi @w13915984028 ,

The linear relation of new overhead ratio setting looks fine.
But we have a failure case just after fresh installation, the value shows `1.5` but the actual value act on VM pod is `1.0`, you can refer detail in the following scenario **Default Value (Just After Fresh Installation)**.

Please help to check, thanks.


> [!NOTE] 
> In this test, expected VM memory $m_{guest}$ and pod memory $m_{pod}$ are calculated from the relation
> 
> * $m_{guest} = m_{req} - m_{res}$
> * $m_{pod} = m_{req} + r_{overhead} \times m_{sys}$
> 
> Ref. https://66d61b2b7a08694d93628b0f--harvester-preview.netlify.app/v1.4/advanced/index/#additional-guest-memory-overhead-ratio

## Environment
* Harvester
  * Version: v1.4.0-rc1
  * Profile: 3 nodes QEMU/KVM (include a witness node)
  * ui-source: Auto


## Prerequisite
1. Create image <i>ubuntu-22.04-jammy-server-cloudimg-amd64.img</i>
1. Create VM network <i>mgmt-vlan1</i>
3. <details>
   <summary> Create a basic VM and check $m_{sys}$ (<code>~245 M</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/77c7d927-440f-4e0f-9629-75d32581deee)
   </details>

## Scenario
### Config Explicitly
### $r_{overhead} = 1$
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2293 M</code> (<code>2048+245x1</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4bc0bdda-821f-4090-bb3c-d6493074384f)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2293 M</code> (<code>2048+245x1</code>) and $m_{guest}$ should be <code>1792 M</code> when $m_{res}$ is <code>256 M</code> (<code>2048-256</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a79b6923-f1f7-4218-ba95-f146082cfb60)
   </details>


### $r_{overhead} = 1.50$
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/9002b9ba-fa1c-4dac-a5e9-a867402f99eb)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/ae8c1119-28cd-4fa3-bcc3-f1e5485a539b)
   </details>


### $r_{overhead} = 3$
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2783 M</code> (<code>2048+245x3</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/1a208503-6d2a-4694-a2e0-7f07a8fe4277)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2783 M</code> (<code>2048+245x3</code>) and $m_{guest}$ should be <code>2038 M</code> when $m_{res}$ is <code>10 M</code> (<code>2048-10</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/18d58270-5239-4726-8556-6c906cf8c7fa)
   </details>


### $r_{overhead} = 0$
> Basically same as $r_{o} = 1$ except when $m_{res}$ is 0 a default 100M memory overhead will be assign.

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2293 M</code> (<code>2048+245x1</code>) and $m_{guest}$ should be <code>1948 M</code> (<code>2048-100</code>) when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7f60df4e-dd03-419e-8935-edaa7e41bce4)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2293 M</code> (<code>2048+245x1</code>) and $m_{guest}$ should be <code>1792 M</code> when $m_{res}$ is <code>256 M</code> (<code>2048-256</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4aecbf1d-fbd3-4075-905d-6a2f5e6554d8)
   </details>


### Restart VM to Fetch Latest Value 
1. <details>
   <summary> :green_circle: Reboot all VMs and every pods should have $m_{pod}$ with <code>~2783 M</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/18d58270-5239-4726-8556-6c906cf8c7fa)

   * vm-1-0
     ![image](https://github.com/user-attachments/assets/a1a7dae6-6f1a-47e7-98cb-3fcaf242409f)
   * vm-1-256
     ![image](https://github.com/user-attachments/assets/9067752b-bd85-4d67-9650-af811067382d)
   * vm-1p5-0
     ![image](https://github.com/user-attachments/assets/143d7139-da18-4c66-b864-dd4b18e0e19a)
   * vm-1p5-128
     ![image](https://github.com/user-attachments/assets/b5d26c75-e57e-48e4-9b49-fe56e689ee97)
   * vm-3-0
     ![image](https://github.com/user-attachments/assets/e491fa32-b3cd-48db-b7fb-60e71518c928)
   * vm-3-10
     ![image](https://github.com/user-attachments/assets/da6b85dc-412e-4f3a-bb0b-eef68fa2b520)
   </details>


### Default Value (should identical with `1.5`)
#### By **Use the default value**
1. <details>
   <summary> :green_circle: Configure by <b>Use the default value</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/79958491-b9ad-46b2-9139-1d7ba361b504)
   </details>
   
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/464ef9c2-7094-4b4a-b0c5-e7ec1cf545c3)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/0a9c1a0f-e522-45b4-b149-acc56dca6814)
   </details>

#### By config as `""`
1. <details open>
   <summary> :yellow_circle: Configure by <b>Use the default value</b>
   </summary>
   
   * Configure with empty value
     ![image](https://github.com/user-attachments/assets/2e37ca97-c037-4d13-a303-0e117143c247)
   * Setting Status `False`
     ![image](https://github.com/user-attachments/assets/b9a6ae8c-d3ce-4117-9173-550ac49f82a3)
   </details>


1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f5c77c10-10fa-4dca-8b73-88559c7470ec)
   </details>


### Default Value (Just After Fresh Installation)
2. <details open>
   <summary> :yellow_circle: Initial value (just after fresh installation)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/6e56b34d-2afa-467e-a284-7909c819dcb5)
   </details>

1. <details open>
   <summary> :red_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   > :x: Got $m_{pod}$ `~2293 M` ($r_o = 1$) instead of `~2416 M` ($r_o = 1.5$) 
   ![image](https://github.com/user-attachments/assets/ee51e818-7413-4b6d-a75c-9c4cec068b91)
   </details>



## Supportbundle
1. [supportbundle_5768-running_2024-10-08T15-09-52Z.zip](https://github.com/user-attachments/files/17295396/supportbundle_5768-running_2024-10-08T15-09-52Z.zip)
2. Fresh install cluster
   [supportbundle_5768-fresh_2024-10-08T15-46-38Z.zip](https://github.com/user-attachments/files/17295870/supportbundle_5768-fresh_2024-10-08T15-46-38Z.zip)

**Comment by w13915984028** [comment]
@albinsun Thanks for your detailed test.

The default value processing seems to have a bug, I will fix it on another PR.

**Comment by w13915984028** [comment]
Update:

The configuration `additional-guest-memory-overhead-ratio` is not  processed by the setting controller on a freshly installed cluster by default as it is not in the `bootstrap` filter list.

The open points listed on https://github.com/harvester/harvester/issues/5768#issuecomment-2400233915 will be verified after PR #6745 is merged.

**Comment by w13915984028** [comment]
Remaining points can be futher verified on v140-rc3 version, thanks.

The PR #6758 is on https://github.com/harvester/harvester/releases/tag/v1.4.0-rc3 release lists.

**Comment by albinsun** [comment]
Test PASS, close as done.


## Environment
* `harvester-v1.4.0-rc3`
  * Profile: 3 nodes QEMU/KVM (include a witness node)
  * ui-source: Auto


## Prerequisite
1. Create image _ubuntu-22.04-jammy-server-cloudimg-amd64.img_
1. Create VM network _mgmt-vlan1_


## Scenario
### Default Value (Just After Fresh Installation)
1. <details>
   <summary> :green_circle: Initial value (just after fresh installation)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/53529989-6341-467c-81c7-6fa159c365ad)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/9b6e9322-56ef-4144-a0b2-ad6d87f61cd0)
   </details>

### Configure $r_{overhead} = 2$
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2538 M</code> (<code>2048+245x2</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/55b3b4d1-a12c-42d5-b916-661e1cf0b00d)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2538 M</code> (<code>2048+245x2</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5be1e05c-4fe7-421a-8127-2d47d4c5bfd0)
   </details>



### Use the default value (should identical with `1.5`)
1. <details>
   <summary> :green_circle: Configure by <b>Use the default value</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c8633094-6264-41f1-a1f0-8d4a27f00c42)
   </details>
   
1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>2048 M</code> when $m_{res}$ is <code>0 M</code> (<code>2048-0</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7da4b50e-7709-49fa-a133-ff30d482e17d)
   </details>

1. <details>
   <summary> :green_circle: $m_{pod}$ should be <code>~2416 M</code> (<code>2048+245x1.5</code>) and $m_{guest}$ should be <code>1920 M</code> when $m_{res}$ is <code>128 M</code> (<code>2048-128</code>)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/6fc9542b-c228-4925-a78d-c9541661c215)
   </details>
