### ISSUE TITLE
[FEATURE] Logging

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#577]
1. We need to provide a way for users to view the system-related logs.
2. We need the ability to export the system-related logs to outside the cluster in case the user wants to collect and analyse it later.

To elaborate:
1. We need to export Harvester logs to a central location. We should support what Rancher logging can support, including Elasticsearch and Splunk. https://rancher.com/docs/rancher/v2.6/en/logging/
2. The log we need to collect are:
    1. Log in the OS. E.g. major system logs under /var/log/
    2. RKE2/Kubernetes related logs
    3. Logs for Harvester components running as pod inside the Kubernetes cluster.
    4. Logs for other workloads/VMs.

**Comment by ibrokethecloud** [comment]
Possible solution:

**Base Components:**
* Deploy ManagedChart for rancher logging
* Deploy a default `ClusterFlow` to aggregate/filter logs from the cluster.
* Allow a `ClusterOutput` to be configured via Settings to control the details of the log aggregation endpoint. 

**Additional Features:**
* Deploy a managed chart for Loki.
* Configure additional datasources in Prometheus to point to Loki.
* Configure a default ClusterOutput to stream logs to Loki.
* UI changes to allow access to Grafana to query logs via Loki.

**Comment by doug62** [comment]
Heck - I can't even find the logs in var/log - Having several issues but can't see logs, or install utilities like tcpdump.

**Comment by oivindoh** [comment]
I think splitting this into two different scopes would indeed be helpful, where the most critical scope for most is likely the ability to simply collect and forward system logs elsewhere, and the other is actual local insight through loki and grafana for people who'd like to keep this within the harvester system.

**Comment by guangbochen** [comment]
Close this epic issue as all sub-items are all verified and closed.
