### ISSUE TITLE
[BUG] The vGPU allocatable count for a node isn't updated after cluster creation

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5774]
**Describe the bug**

When you create a RKE2 cluster from an upstream Rancher cluster it doesn't update the vGPU allocatable list `node.status.allocatable` after the cluster creation
**To Reproduce**
1. Create 4 vGPU profiles on a node
2. deploy a 3 node RKE2 cluster with that vGPU profile
3. Try to deploy out another 3 node RKE2 cluster and check allocatable 

**Expected behavior**

The allocatable vGPU count should update 
**Support bundle**

[supportbundle_314d015f-bac6-449f-a676-14fd3732e576_2024-05-08T22-16-49Z.zip](https://github.com/harvester/harvester/files/15255792/supportbundle_314d015f-bac6-449f-a676-14fd3732e576_2024-05-08T22-16-49Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0
 - Rancher version: v2.8-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node DL360

**Additional context**
This is the Harvester side bug for [10948](https://github.com/rancher/dashboard/issues/10948)

![Greenshot 2024-05-03 17 55 22](https://github.com/harvester/harvester/assets/83787952/7954c237-6a9c-4057-b41e-c448f7a345e1)

**Comment by ibrokethecloud** [comment]
we should improve the device plugin pcidevices controller to monitor resource usage: https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#monitoring-device-plugin-resources

additional changes may be needed in the harvester api to federate plugin info from all nodes for rancher to leverage

**Comment by bk201** [comment]
require-doc
- doc: update vGPU doc and mention the feature is available after Rancher version xxx
- release note: mention the feature is available after Rancher version xxx

**Comment by noahgildersleeve** [comment]
Tested with Harvester v1.4.0-rc2 with Rancher versions

- v2.8-68e5d43e449fcd3ef73baf1caee98da6f0104eed-head
![Greenshot 2024-10-09 17 47 34](https://github.com/user-attachments/assets/e60d594d-0f23-4b0d-bde6-8caec0d0cff6)
![Greenshot 2024-10-09 17 46 08](https://github.com/user-attachments/assets/62da3e9b-f926-41fd-bbc9-69e034501f8c)
![Greenshot 2024-10-09 17 45 47](https://github.com/user-attachments/assets/52e52c73-3bec-43e1-bdb6-a4306258e621)
![Greenshot 2024-10-09 17 45 39](https://github.com/user-attachments/assets/e2bb36e4-0e67-4bb5-9656-18b039114f0b)

- v2.9-af2463ff43418024ff86cfd9304836b7074a924a-head
![Greenshot 2024-10-09 18 04 22](https://github.com/user-attachments/assets/2327197a-d63f-456f-8cdd-dd7e7007daae)
![Greenshot 2024-10-09 18 04 18](https://github.com/user-attachments/assets/9eba035b-54a9-4669-9a15-089fc3c5e101)
![Greenshot 2024-10-09 18 03 48](https://github.com/user-attachments/assets/cf3b5ec5-c2c0-4182-b7fd-328f42498495)

- v2.10-fe30db77dab22d42b769c9d88d9410a8044c4066-head
![Greenshot 2024-10-09 20 21 08](https://github.com/user-attachments/assets/3f8d5a0a-80e1-49e8-a4f3-8857bfd3098c)
![Greenshot 2024-10-09 20 20 29](https://github.com/user-attachments/assets/d37edea5-7434-4466-82d9-1bd1c0a8dce7)
![Greenshot 2024-10-09 20 20 12](https://github.com/user-attachments/assets/7e586bdf-c2be-4448-8df1-298ba3f2ec42)
![Greenshot 2024-10-09 19 49 03](https://github.com/user-attachments/assets/a03648e5-bc13-40ef-834d-1bfa8f1256b8)
![Greenshot 2024-10-09 19 48 38](https://github.com/user-attachments/assets/7f834849-68a5-47e5-ab01-f16e88d1797f)
![Greenshot 2024-10-09 19 48 32](https://github.com/user-attachments/assets/3006a98a-ea51-4db2-b8f7-c97e4bd3fc7c)
