### ISSUE TITLE
[BUG] You can enable a vGPU address without a profile

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5775]
**Describe the bug**

You can hit save in adding a vGPU profile without a profile selected
**To Reproduce**
1. Navigate to vGPU Devices
2. Click enable
3. Hit save without selecting a profile

**Expected behavior**

Save should be grayed out or you should get an error
**Support bundle**

[supportbundle_314d015f-bac6-449f-a676-14fd3732e576_2024-05-08T23-05-09Z.zip](https://github.com/harvester/harvester/files/15255824/supportbundle_314d015f-bac6-449f-a676-14fd3732e576_2024-05-08T23-05-09Z.zip)

**Environment**
 - Harvester ISO version: v1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL360

**Additional context**
![Greenshot 2024-05-08 16 04 15](https://github.com/harvester/harvester/assets/83787952/3d134675-1124-4d41-8b74-54e2924deb1a)
![Greenshot 2024-05-08 16 04 11](https://github.com/harvester/harvester/assets/83787952/a3c35b46-8873-4123-9988-5a2499e9f77d)

**Comment by ibrokethecloud** [comment]
we need to improve the validation logic in pcidevices and UI to prevent vgpu device to be enabled with an empty vGPU profile

vgpu definition from the support bundle
```
apiVersion: devices.harvesterhci.io/v1beta1
kind: VGPUDevice
metadata:
  annotations:
    sim.harvesterhci.io/creationTimestamp: "2024-05-08T17:26:59Z"
  creationTimestamp: "2024-05-08T17:26:59Z"
  generation: 1
  labels:
    harvesterhci.io/parentSRIOVGPUDevice: vgpu-2-000008000
    nodename: vgpu-2
  name: vgpu-2-000008006
  resourceVersion: "1427"
  uid: b1879c29-85a9-45c4-a50f-3f0125a1c7eb
spec:
  address: "0000:08:00.6"
  enabled: true
  nodeName: vgpu-2
  parentGPUDeviceAddress: "0000:08:00.0"
status: {}
```

**Comment by torchiaf** [comment]
I pushed a PR to disable the Save button in the UI. I think there should be a validation step for the webhook as well.

**Comment by noahgildersleeve** [comment]
Tested in Harvester `v1.4.0-rc2`. Validated as fixed. The modal doesn't have save enabled if you don't have a profile selected.

![Greenshot 2024-10-10 15 00 11](https://github.com/user-attachments/assets/6acc75d6-8267-4e27-ad8a-a7272d669a59)
