### ISSUE TITLE
[FEATURE] Event and audit log

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#578]
We need to provide a way for the user, especially the admin user to know what's happened in the system. E.g. who created which VM etc.

As a part of this feature, we should implement an audit log mechanism as well.

**Comment by FrankYang0529** [comment]
Probably, we can leverage Kubernetes Auditing feature to make this.

https://kubernetes.io/docs/tasks/debug/debug-cluster/audit/

**Comment by weihanglo** [comment]
Some thoughts from my personal note:

---

### Questions to ask when implementing auditing

- Who performed an activity
- What activity was performed
- How the system responded.

### Topics to discuss

- Policy: 
    - What should be audited.
    - How much do we audit.
- Log backend/Log routing: 
    - To Where events should be written
    - External storage, e.g. AWS Nightwatch, Google cloud logging. 
    - A webhook backend.
- Batching: Reduce I/O
- Security
- Syslog protocol (related to  #577) 

### RKE2

Generally, Kuberenetes may audit the activities generated

- by users, 
- by applications that use the Kubernetes API, 
- and by the control plane itself.

Each request on each stage generates a log (event)

- RequestReceived
- ResponseStarted
- ResponseComplete
- Panic

Ref: 

- https://rancher.com/docs/rke/latest/en/config-options/audit-log/
- https://kubernetes.io/docs/tasks/debug-application-cluster/audit/

### What else to collect

Project [A](https://cloud.google.com/logging/docs/audit) collects:

- Admin Activity audit logs: modify configs or metadata
- Data Access audit logs: modify resources (public resources don't generate logs)
- System Event audit logs: controlled by its own managed service
- ⚠️ Policy Denied audit logs: when service is denied, generate a log

[Project](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-F35D7005-58EB-48AC-99D5-B9942EB2A8EF.html) [B](https://docs.vmware.com/en/VMware-vSphere/7.0/com.vmware.vsphere.security.doc/GUID-9BBC8AA0-4533-4943-AEF5-6A8BC64D7A5D.html) collects:

- Authentication events
- Host agent event about configuring VMs and hosts
- Shell logs
- VM events, including power events, system failure, time sync, virtual hardware changes, migrations, clones…

**Comment by w13915984028** [comment]
connect with #577

**Comment by w13915984028** [comment]
All sub-stories are done, close EPIC.
