### ISSUE TITLE
[BUG] Delete PVC should return PVC not status

### ISSUE THREAD

**Issue by drewmullen** [harvester/harvester#5781]
**Describe the bug**

Deleting a `persistentvolumeclaim` should return the pvc object, not `Status`: 

https://github.com/harvester/harvester/blob/bf5847ad1bac8d63be93355559b85af4f86d1901/api/openapi-spec/swagger.json#L410-L425

This API comes from the k8s API which documents the appropriate return type: https://raw.githubusercontent.com/kubernetes/kubernetes/master/api/openapi-spec/swagger.json

<img width="692" alt="image" src="https://github.com/harvester/harvester/assets/3812162/955cc8c3-770c-48af-b863-d825e0422c6c">

**Comment by drewmullen** [comment]
highly suspect:

https://github.com/harvester/harvester/blob/5ab43f02144fb8c193005905945d60cc65a73133/pkg/genswagger/rest/webservices.go#L162-L175

**Comment by Vicente-Cheng** [comment]
Hi @drewmullen
Thanks for raising this!

We would check your PR with both issues https://github.com/harvester/harvester/issues/5781, https://github.com/harvester/harvester/issues/5528

Hi @Yu-Jack, @m-ildefons, could you help to check the PR https://github.com/harvester/harvester/pull/5782?
Thanks!

**Comment by drewmullen** [comment]
Thanks for accepting! Can you please confirm, I think the “reopen” was on accident? @bk201
