### ISSUE TITLE
[FEATURE] Support bundle

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#579]
We need to provide a mechanism for the user to easily collect system-related log in Harvester, to help with troubleshooting and support.

**Comment by yasker** [comment]
Move to v0.2.0 milestone.

We're going to announce v0.2.0 as the first beta release. Need to have a way to help users troubleshooting issues.

**Comment by guangbochen** [comment]
we should support to tail the following component logs as for a minimum requirement, 
1. all pod logs in the `harvester-system` namespace
3. pod logs in the `longhorn-system` if its pod status is an error
4. pod logs in the `default` user namespace if its pod status is an error
5. pod logs in the `kube-system` namespace if its pod status is an error
6. pod logs in the `cattle-system` namespace if its pod status is an error

The user should be able to submit the debug bundled directly on the harvester UI(if the UI is not reachable, allow users to deploy the log container YAML file with the `kubectl` command):

**Comment by yasker** [comment]
We also need logs from dmesg, k3s log, and kubelet on all the nodes (I think kubelet log is included in k3s log?).

And all the related YAML for CR objects we're using in Harvester.

For Longhorn, you can directly get a support bundle and embedded it in Harvester support bundle.

Only the error pod's log is normally not enough.

Rancher also have a way to collect support bundle, it's better if we can integrate that as well. A simple doc is available at https://support.rancher.com/hc/en-us/articles/360039113911-The-Rancher-v2-x-Linux-log-collector-script

It's better if the user can download the support bundle directly from UI. But it's better to have an alternative using kubectl or curl in case the server is down.

**Comment by bk201** [comment]
I'm implementing the approach that Longhorn currently uses to provide a support bundle:
- Logs
  - [x] All pods in `harvester-system` namespace.
  - [x] All pods in the default namespace.
  - [x] All pods in the `kube-system` namespace.
  - [x] All pods in the `cattle-system` namespace.
- YAML files
  - [x] Kubernetes workload resources, like pods, configmaps, etc. Longhorn support bundle provides the same thing.
  - [x] Harvester CRs
  - [x] KubeVirt CRs
  - [x] CDI CRs
- A `external` folder contains 3rd party support-bundles. 
  - [x] longhorn support bundle.

[WIP branch](https://github.com/bk201/harvester/commits/support-bundle)

Sample bundle:
[Harvester-support-bundle_1c5e4cf4-2792-4ea2-88fb-be9a1b062189_2021-04-09T06-52-09Z.zip](https://github.com/rancher/harvester/files/6283731/Harvester-support-bundle_1c5e4cf4-2792-4ea2-88fb-be9a1b062189_2021-04-09T06-52-09Z.zip)

**Comment by guangbochen** [comment]
verified using the harvester-v0.2.0-rc5, generating support bundle works, and the zip file contains all the logs and YAML files as needed.
![image](https://user-images.githubusercontent.com/4569037/116655046-f38d4680-a9bc-11eb-9ebb-f84495a4161c.png)
![image](https://user-images.githubusercontent.com/4569037/116655180-38b17880-a9bd-11eb-9c53-8de8cf7a4e51.png)
