### ISSUE TITLE
[ENHANCEMENT] Bump RKE2 to v1.27.13+rke2r1 and Rancher to v2.8.3

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5792]
**Is your enhancement related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Verified in Harvester `v1.3-95b4f9dc-head` on vagrant-pxe-harvester deploy with 2 nodes in libvirt. 

## Verification Steps
- Run `kubectl get nodes`
- Run `kubectl get settings.management.cattle.io server-version`

### Expected Results
-  Kubernetes version is v1.27.13+rke2r1
- Embedded Rancher is v2.8.3

![Screenshot_20240522_103345](https://github.com/harvester/harvester/assets/83787952/27388e1b-eb1b-47e6-ad2c-726cc065cf8d)
![Screenshot_20240522_103341](https://github.com/harvester/harvester/assets/83787952/bff88f8f-5715-44c1-9f9f-15d4e3fdc13b)
