### ISSUE TITLE
[BUG] Unable to enable the GPU's via the GUI

### ISSUE THREAD

**Issue by IASN-CCC** [harvester/harvester#5793]
**Describe the bug**
Unable to enable the GPU's that are installed in the server from the UI

Two GPUs are listed (2xNVIDIA L40) however selecting one and selecting enable nothing happens

**To Reproduce**
Goto SR-IOV GPU Devices, Select a listed GPU and click the 3 dots to enable
![image](https://github.com/harvester/harvester/assets/111335687/91dc0b39-0924-4633-84f7-54cd0a9a0a60)

**Expected behavior**
GPU should enable

**Support bundle**
Please reach out to request one securely

**Environment**
 - Harvester ISO version:  1.3.0
 - Underlying Infrastructure: DELL R760XA Baremetal with Dual NVIDIA L40 GPUs

**Additional context**

**Comment by ibrokethecloud** [comment]
are you please able to confirm that the nvidia driver addon is enabled?

**Comment by IASN-CCC** [comment]
> are you please able to confirm that the nvidia driver addon is enabled?

Hi, Yes ive enabled the driver addon and its showing as working
<img width="800" alt="image" src="https://github.com/harvester/harvester/assets/111335687/21779cf7-1aaa-48b8-80b8-42166ab1a42e">

If i look in the PCI device list i can also see the two GPUs and i have not enabled them for pass through

**Comment by bathomas** [comment]
Are the `pcidevices-controllers` crashing? I had to increase the limits on them and was able to enable.

**Comment by IASN-CCC** [comment]
> Are the `pcidevices-controllers` crashing? I had to increase the limits on them and was able to enable.

Hi, Not sure how i can check this?
How did you increase the limits?

**Comment by ibrokethecloud** [comment]
the `nvidia-driver-toolkit` needs the driver location, which is http endpoint where the nvidia kvm driver is located. 

From that screenshot it looks like this has not been edited so no real driver has been installed on the underlying hosts.

**Comment by IASN-CCC** [comment]
> the `nvidia-driver-toolkit` needs the driver location, which is http endpoint where the nvidia kvm driver is located.
> 
> From that screenshot it looks like this has not been edited so no real driver has been installed on the underlying hosts.

Oh ok, that makes sense then.

The host is not currently internet connected (sits behind a proxy and i am trying to locate all the URLs to white list in our proxy)

Will internet access resolve this or do i still need to find a location

**Comment by ibrokethecloud** [comment]
the http endpoint is supposed to be an internal http server where you can host the drivers. You will need access to the nvidia portal to download the nvidia kvm drivers. These are different from the opensource drivers. 

Please refer to the docs: https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit

**Comment by IASN-CCC** [comment]
> https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit

OK, downloaded the latest KVM drivers and put them on an internal web server, updated it but still no luck
![image](https://github.com/harvester/harvester/assets/111335687/63bc2b89-c906-4d41-9550-a186cbeae1ff)

Tested that i can hit the URL from my PC and the file starts downloading, i also can ping the host from the harvester host.

**Comment by ibrokethecloud** [comment]
any chance i may have a support bundle to figure out what is going on? There would be messages in the nvidia driver toolkit container / pcidevices which would provide insights on what is going on.

**Comment by IASN-CCC** [comment]
> any chance i may have a support bundle to figure out what is going on? There would be messages in the nvidia driver toolkit container / pcidevices which would provide insights on what is going on.

Sure, What is the best way to provide them to you securely?

**Comment by ibrokethecloud** [comment]
please email the bundle to harvester-support-bundle@suse.com

**Comment by IASN-CCC** [comment]
> please email the bundle to [harvester-support-bundle@suse.com](mailto:harvester-support-bundle@suse.com)

Sent. Thank you

**Comment by ibrokethecloud** [comment]
The nvidia-driver-runtime image cannot be pulled by your nodes

```
nvidia-driver-runtime-5vvwn                             0/1     ImagePullBackOff   0              21h
```

This image is not shipped in the iso and needs to be pulled to your private registry in case your nodes do not have access to the docker hub.

Once the image is available please update the image details in the addon to point to your private registry.

This is mentioned in the docs: https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit

**Comment by IASN-CCC** [comment]
> The nvidia-driver-runtime image cannot be pulled by your nodes
> 
> ```
> nvidia-driver-runtime-5vvwn                             0/1     ImagePullBackOff   0              21h
> ```
> 
> This image is not shipped in the iso and needs to be pulled to your private registry in case your nodes do not have access to the docker hub.
> 
> Once the image is available please update the image details in the addon to point to your private registry.
> 
> This is mentioned in the docs: https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit

Oh ok, I didnt realise that, I thought i just had to download the driver and host it on a web server which i done

Do i need to setup this private registry also? Do i just deploy a SUSE microOS and setup as a private registry?

Thanks

**Comment by ibrokethecloud** [comment]
The private registry is a container registry. I do not think microOS contains a registry of its own. You could use something like [goharbor](https://goharbor.io/) to get started with a private registry

**Comment by IASN-CCC** [comment]
> The private registry is a container registry. I do not think microOS contains a registry of its own. You could use something like [goharbor](https://goharbor.io/) to get started with a private registry

Thanks for that, we will look into that.

Interestingly, i white listed all the domains the system was trying to get out to in our proxy and then configured the proxy in the harvester UI, but still no luck, it should be able to get out now

**Comment by ibrokethecloud** [comment]
are you able to ssh to all your nodes and just run `docker pull rancher/harvester-nvidia-driver-toolkit:v1.3-20240307`

if the nodes can pull this image then the addon should work

**Comment by IASN-CCC** [comment]
> docker pull rancher/harvester-nvidia-driver-toolkit:v1.3-20240307

No such luck
![image](https://github.com/harvester/harvester/assets/111335687/8aae1cb8-9cd8-4c3d-9e75-dc4814593c25)

**Comment by IASN-CCC** [comment]
Hi @ibrokethecloud - Just wondering if you had a chance to review the above?

Thanks

**Comment by ibrokethecloud** [comment]
this is likely because environment variables are not set. best bet would be to `sudo su -` and then run the `docker pull`

**Comment by IASN-CCC** [comment]
@ibrokethecloud 

Ok, done that - looks positive?
![image](https://github.com/harvester/harvester/assets/111335687/07152c57-4256-4bf8-a3a3-ae92173438e0)

**Comment by IASN-CCC** [comment]
@ibrokethecloud 

Ive emailed over an updated support bundle

I did a host reboot after the above, but still no luck, right clicking and enabling these two GPUs does nothing
![image](https://github.com/harvester/harvester/assets/111335687/f6a12995-3314-4e9e-a0bb-d7187d42a5e7)

![image](https://github.com/harvester/harvester/assets/111335687/ed17675e-59e0-4417-8780-78a68143498f)

**Comment by ibrokethecloud** [comment]
are you able to please edit the daemonset `kubectl edit ds nvidia-driver-runtime -n harvester-system` and change the `imagePullPolicy` to `IfNotPresent`? 

The current policy in the manifest is `Always` which means kubelet is trying to pull it even when the image is still present and likely failing

**Comment by IASN-CCC** [comment]
> are you able to please edit the daemonset `kubectl edit ds nvidia-driver-runtime -n harvester-system` and change the `imagePullPolicy` to `IfNotPresent`?
> 
> The current policy in the manifest is `Always` which means kubelet is trying to pull it even when the image is still present and likely failing

Do i SSH to the host and run 
$ kubectl edit ds nvidia-driver-runtime -n harvester-system

Happy to do a screenshare if that helps?

**Comment by IASN-CCC** [comment]
I edited the file and amended the image pull policy (imagePullPolicy) replacing  "always" with the value you gave me, but this did not solve the issue

![image](https://github.com/harvester/harvester/assets/111335687/7c098845-4934-4f79-9086-c65163bc855e)

When i go to "SR-IOV GPU Devices" i still cannot enable them

**Comment by psarinana-fsb** [comment]
Did you ever receive a resolution for this issue?  I am experiencing very similar behavior and would like to see if there is a solution before I open a new case
