### ISSUE TITLE
[BUG] When upgrading 1 node Harvester with PCI passthrough the VM won't come up and kube-vip crashes

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5796]
**Describe the bug**

When you upgrade a single node Harvester cluster from v1.2.1 -> v1.2.2-rc3
**To Reproduce**
1. Create a Harvester cluster
2. Add PCI passthrough
3. Create a VM 
4. Turn on the VM
5. Add the PCI device to the VM and reboot
6. Validate that the device was added
7. Turn off VM
8. Upgrade to v1.2.2-rc3
9. Wait for upgrade to finish
10. Turn VM back on

**Expected behavior**

VM should turn on successfully.

**Support bundle**

[supportbundle_09ea7a32-1b8f-4996-80fa-845eb2a84415_2024-05-13T20-29-36Z.zip](https://github.com/harvester/harvester/files/15299972/supportbundle_09ea7a32-1b8f-4996-80fa-845eb2a84415_2024-05-13T20-29-36Z.zip)

**Environment**
 - Harvester ISO version: v1.2.1 -> v1.2.2-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL360

**Additional context**
Possibly related to #5373 and #5374 .

It's worth noting I can still admin the cluster from the node IP and from the upstream Rancher cluster where it is imported. Just the VIP seems to be down.

The kubevip worked immediately after the upgrade, and stopped working after a while. `kube-vip` is getting this error then it's looping on the waiting error.
```
time="2024-05-13T20:27:11Z" level=info msg="Using existing macvlan interface for DHCP [vip-e8d7c773]"
time="2024-05-13T20:27:21Z" level=error msg="timeout to request the IP from DHCP server for service kube-system/ingress-expose"
time="2024-05-13T20:27:46Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 10s)"
time="2024-05-13T20:28:28Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 1m0s)"
```

The PCI passthrough VM is getting a memory setting error. I recall a similar issue in the past where when you edited a VM and added PCI passthrough it would not work because we were overcommiting memory by default and it seemed like kubevirt didn't like that with VMs that had PCI devices.

![Greenshot 2024-05-13 13 35 50](https://github.com/harvester/harvester/assets/83787952/cb04a442-94d5-443a-b1f0-5ef20836a515)

**Comment by w13915984028** [comment]
@noahgildersleeve 
kube-vip failed to get dhcp response, is your dhcp server still alive?  you may tcpdump on your server side then kill kube-vip pod to re-trigger the dhcp process; and aslo tcpdump harvester mgmt-bo to check if dhcp frames are sending and receiving.

```
time="2024-05-13T20:27:11Z" level=info msg="Using existing macvlan interface for DHCP [vip-e8d7c773]"
time="2024-05-13T20:27:21Z" level=error msg="timeout to request the IP from DHCP server for service kube-system/ingress-expose"
time="2024-05-13T20:27:46Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 10s)"
time="2024-05-13T20:28:28Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 1m0s)"
```

**Comment by noahgildersleeve** [comment]
We tried to clear out the tube-vip and it's having the same issue. It might be environmental. I'm going to test it again without DHCP on the VIP in a different more simple environment.

**Comment by noahgildersleeve** [comment]
## Validation steps
1. Create a v1.2.1 cluster
2. enable pci passthrough
3. Enable PCI passthrough device
4. Create VMs and assign PCI device
5. Upgrade to v1.2-head
6. unassign pci device
7. Create new VM and assign PCI device
8. Turn on new VM
9. Check for warning on Harvester cluster with `kubectl get events | grep Warn`

**Comment by noahgildersleeve** [comment]
Also I validated that the issue with the kubevip was that it lost the DHCP lease. When I ran the upgrade with a static IP for the VIP it worked fine.

**Comment by noahgildersleeve** [comment]
Closing as completed.
