### ISSUE TITLE
[FEATURE] Guest cluster CSI driver

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#580]
We need to provide the guest cluster inside the Harvester cluster with the native storage performance.

The basic idea is to use a Harvester CSI driver inside the guest cluster to connect to the Harvester host cluster, ask the host cluster to hotplug a disk into that node.

Depends on #283 

Ref: #633

**Comment by guangbochen** [comment]
Currently, we should be able to verify this feature by importing the Harvester v0.3.0-rc1 release to the upstream Rancher v2.6.1-rc5.

**To Test:**
- create a guest k8s cluster with RKE2 v1.21.5+ provider and make sure the cloud provider is set to `Harvester`
- once the guest k8s cluster is up and running, go to the Rancher cluster management page
- create a workload and add a PVC to it via the `Storage` tab, select the built-in `harvester` storage-class
![image](https://user-images.githubusercontent.com/4569037/135387386-ed53e121-6882-4ce2-8547-2ab618ee61e8.png)
- the user should be able to create/resize and delete the PVC using pf built-in `harvester` guest CSI driver
   - on the Harvester bare-metal cluster, the associated volumes should either create or removed upon the guest k8s deployment status.
   - user can only resize the PVC when the volume is detached(deployment scaled to 0) https://longhorn.io/docs/1.2.0/volumes-and-nodes/expansion/
 - verify the guest CSI storage performance is as efficient as how it runs on the bare-metal cluster

**Comment by shangma** [comment]
### Test Info

- Verified version:
  - Rancher: v2.6.1-rc10
  - Harvester: v0.3.0-rc1

- Environment: rancher and harvester are running in its own vm respectively

### Test Case
1. Start rancher using docker in a vm and start harvester in another
2. Import harvester into rancher from "Virtualization Management" page
3. On rancher, enable harvester node driver at "Cluster Management" -> "Drivers" -> "Node Driver"
4. Go back to "Cluster Management" and create a rke2 cluster using Harvester
5. Once the created cluster is active on the "Cluster Management" page, click on the "Explore"
6. Go to "Workload" -> "Deployment" and "Create" a new deployment, during which in the page of "Storage", click on "Add Volume" and select "Create Persistent Volume Claim" and select "Harvester" in the "Storage Class"
7. Click "Create" to create the deployment
8. Verify that on the Harvester side, a new volume is created.
9. Delete the created deployment and then delete the created pvc. Verify on the harvester side that the newly created volume is also deleted.
10. create another deployment, say nginx:latest with 8GB storage created as step 6.
11. "Execute shell" into the deployment above and use "dd" command to test the read & write speed in the directory where the pvc is mounted:
![image](https://user-images.githubusercontent.com/2396545/136323545-699b24dd-39b0-4222-a888-8213b8462651.png)

12. SSH into a vm created on the bare metal and run the same dd command:
![image](https://user-images.githubusercontent.com/2396545/136323396-7ab2532d-7eff-4e6e-a622-8845eed4857c.png)

13. Scale down the above deployment to 0 replica and resize the pvc to 15GB on the harvester side:
![image](https://user-images.githubusercontent.com/2396545/136323146-94e3507e-7346-459f-b867-c39bf69de9d3.png)

14. Double check the pvc is resized on the longhorn side.
![image](https://user-images.githubusercontent.com/2396545/136323179-71793c2f-4cd7-4734-95e2-59de3b38c32f.png)

**Comment by brotherdust** [comment]
I realize this issue has been closed for some time, but I've been running into an issue where I'm trying to deploy my own k8s guest cluster on top of Harvester and there doesn't seem to be a straightforward way to integrate with Longhorn. I've tried looking around the RKE2 integration and copying the manifests and created support bundles, etc; but no bueno. Is there a guide on how to use the CSI driver for k8s guest cluster that Rancher hasn't deployed?

**Comment by Martin-Weiss** [comment]
> I realize this issue has been closed for some time, but I've been running into an issue where I'm trying to deploy my own k8s guest cluster on top of Harvester and there doesn't seem to be a straightforward way to integrate with Longhorn. I've tried looking around the RKE2 integration and copying the manifests and created support bundles, etc; but no bueno. Is there a guide on how to use the CSI driver for k8s guest cluster that Rancher hasn't deployed?

Did not try this but this should work the same way as deploying any other custom CPI/CSI driver for RKE2.. (create kubeconfig with proper rights, copy that to all nodes and do a helm install of the chart)

What problem did you face? Logs in the CSI driver?

**Comment by brotherdust** [comment]
@Martin-Weiss , which chart are you referring to?

**Comment by Martin-Weiss** [comment]
> @Martin-Weiss , which chart are you referring to?

https://github.com/harvester/harvester-csi-driver
https://github.com/harvester/cloud-provider-harvester

Helm Charts are at
rke2-charts           	https://rke2-charts.rancher.io 
rancher-v2.6-charts     	https://raw.githubusercontent.com/rancher/charts/release-v2.6
rancher-v2.7-charts   	https://raw.githubusercontent.com/rancher/charts/release-v2.7

But AFAIK the charts are also part of rke2 directly..

**Comment by brotherdust** [comment]
Thank you! I'll give these a go. I'm using Kubespray because, at least to me, easier to automate setup and teardown.
Appreciate your time!

**Comment by IQNeoXen** [comment]
I made this work using connors tutorial in #4446 : https://github.com/harvester/harvester/issues/4446#issuecomment-1693607991
