### ISSUE TITLE
[EPIC] improve the stability of Harvester CSI Driver 

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5801]
**Is your enhancement related to a problem? Please describe.**
After some discussion with @WebberHuang1118, we thought Harvester CSI driver had various straightforward mechanisms
We should make it more stable and robust.

**Describe the solution you'd like**
Check the Harvester CSI Driver detail and refine it.

**Describe alternatives you've considered**

**Additional context**
TBD

**Comment by bk201** [comment]
Need concrete action items

**Comment by Vicente-Cheng** [comment]
> Need concrete action items

Update some items, we are investigating more.

**Comment by innobead** [comment]
Add investigation label first, as we need more context for this issue.

**Comment by Vicente-Cheng** [comment]
It is mainly related to the following issues:
https://github.com/harvester/harvester/issues/5949
https://github.com/harvester/harvester/issues/5951

I thought we could close this because the above two issues were resolved.
WDYT? @bk201, @innobead

**Comment by bk201** [comment]
Close because related work are done.
