### ISSUE TITLE
Help with our Harvester setup

### ISSUE THREAD

**Issue by IASN-CCC** [harvester/harvester#5804]
Hi,

We are setting up a 1 node cluster running harvester as bare metal, then rancher as a management VM to handle a kubernetes cluster (which will be VMs on said host)

Our setup will be
- Single server with Harvester installed on Bare Metal
- Dual 25Gbe Network linked in an LACP bond (as configured on harvester installation)
- 10TB of NVMe storage on a hardware raid 5, Volume is visible in the node view.

We plan to run Rancher on a Suse MicroOS virtual machine (hosted on the above harvester node) then configure rancher to point back to the harvester node via integration and have it deploy a kubernetes cluster for us (6x etcd, 6 worker).

Questions i have are
1) Does our above setup look OK (we understand a single node is not ideal, but this is research only and a rather high end node with plenty of inbuilt resiliency)

2) When we create a VM network, It only allows us to attach it to the "mgmt" network - is that normal practice?
![image](https://github.com/harvester/harvester/assets/111335687/32c38e8e-3939-48e5-a80f-095008101dbb)
![image](https://github.com/harvester/harvester/assets/111335687/5fef1815-fa77-4b28-aa87-a405922319cb)

3) The inbuilt storage is seen (this is not where harvester is installed tho, harvester is on another dual ssd, raid 1 vol)
![image](https://github.com/harvester/harvester/assets/111335687/530c0fe0-c828-4b7e-b3e2-8892c1072ebc)

Is this where VMs will naturally sit?

4) Can we connect our DELL Powerstore SAN to this host (we have it wired via fibre channel)

5) Is there a list of website URLs that Rancher and Harvester ideally need access to in order to do updates, pull drives etc? I need to white list in our proxy

6) We are trying to connect the BMC out of band but get the following (we tested the IP and credentials work, the server supports redfish)
![image](https://github.com/harvester/harvester/assets/111335687/1e5e18d6-fa9a-4816-b71e-71a379cbb4a2)

Sorry for all the questions, come from a strong vmware / windows background so this is a steep learning curve for me

Thank you

**Comment by bk201** [comment]
Hi, just some thoughts on some questions.
- 6x etcd, this doesn't sound right. I'd suggest using an odd number like 3.
- mgmt network is handy if you want to create VLAN networks on the same NICs belonged to the management network.
- >Is this where VMs will naturally sit?

    Yes. You can log in to the physical node and check what block device is mounted under /var/lib/harvester/defaultdisk.
