### ISSUE TITLE
[BUG] PCIE devices with the same "Vendor ID" and "Device ID" are randomly passed through to a VM, no matter which one is choosen

### ISSUE THREAD

**Issue by Rabie-Zamane** [harvester/harvester#5823]
**Describe the bug**
PCIE devices with the same "Vendor ID" and "Device ID" are randomly passed through to a VM, no matter which one is selected in the VM passthrough configuration.

We have 3 Server with 3 identical pcie-nvme each.
When we add one of the nvme-pci-devices to a VM. The device is randomly selected and  passedthrough to the VM.

In this example:
- Selected device for passthrough: campus-hci-srv1-0000c1000 (/dev/nvme2n1p1: LABEL="c1-nvme2")
- VM Name: test2-nvme-pt
- VM runs on Node: campus-hci-srv1

Before using passthrough we labeled all the nvme devices.

```
/dev/nvme0n1p1: LABEL="41-nvme0"
/dev/nvme1n1p1: LABEL="81-nvme1"
/dev/nvme2n1p1: LABEL="c1-nvme2"
```
Although the VM settings remain the same, one of the 3 NVMEs is randomly passed through every time the VM is restarted.
(campus-hci-srv1-0000c1000, campus-hci-srv1-000041000, campus-hci-srv1-000081000)

```
campus-hci-srv1:~ # kubectl get pcidevices| grep -E "NAME|Samsung"
NAME                        ADDRESS        VENDOR ID   DEVICE ID   NODE NAME         DESCRIPTION                                                                                                                         KERNEL DRIVER IN USE
campus-hci-srv1-000041000   0000:41:00.0   144d        a824        campus-hci-srv1   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv1-000081000   0000:81:00.0   144d        a824        campus-hci-srv1   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv1-0000c1000   0000:c1:00.0   144d        a824        campus-hci-srv1   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv2-000041000   0000:41:00.0   144d        a824        campus-hci-srv2   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv2-000081000   0000:81:00.0   144d        a824        campus-hci-srv2   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv2-0000c1000   0000:c1:00.0   144d        a824        campus-hci-srv2   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv3-000041000   0000:41:00.0   144d        a824        campus-hci-srv3   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv3-000081000   0000:81:00.0   144d        a824        campus-hci-srv3   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X                                               vfio-pci
campus-hci-srv3-0000c1000   0000:c1:00.0   144d        a824        campus-hci-srv3   Non-Volatile memory controller: Samsung Electronics Co Ltd NVMe SSD Controller PM173X
```

VM Passthrough config
![image](https://github.com/harvester/harvester/assets/6882050/872fd268-a32e-41b9-a3a0-f77d3eb85a34)

After each reboot a random nvme is passed through

![image](https://github.com/harvester/harvester/assets/6882050/878e066b-47d2-4f1f-889e-1d7a80934412)
reboot...
![hv02](https://github.com/harvester/harvester/assets/6882050/7aec4f9a-a8b7-4273-8b33-e0bfbad488c8)
reboot...
![hv03](https://github.com/harvester/harvester/assets/6882050/61a9c67a-fecf-4b21-9a6e-a91c8a3c9422)

**To Reproduce**
1. Use harvester 1.3.0 or 1.2.2-rc3
2. Install multiple pcie-nvme that has the same Vendor and Device ID
3. Label all NVMEs so you can distinguish them later
5. passthrough one of the pcie-nvme to a VM
6. start the VM and check witch nvme-device ist passed through.
7. restart the VM and check witch nvme-device ist passed through.

**Expected behavior**
- Selected device for passthrough (over the UI): campus-hci-srv1-0000c1000 (/dev/nvme2n1p1: LABEL="c1-nvme2")
- after restart the device passed through to the VM must be campus-hci-srv1-0000c1000 (/dev/nvme2n1p1: LABEL="c1-nvme2")

**Support bundle**

[supportbundle_1aac5dd2-744d-4f77-bd44-14bc598c877d_2024-05-16T13-05-32Z.zip](https://github.com/harvester/harvester/files/15335562/supportbundle_1aac5dd2-744d-4f77-bd44-14bc598c877d_2024-05-16T13-05-32Z.zip)

**Environment**
 - Harvester ISO version: 1.2.2-rc3 and 1.3.0
 - Underlying Infrastructure: 3x Dell PowerEdge R930. Baremetal.

**Comment by Vicente-Cheng** [comment]
Hi @ibrokethecloud, could you help to check this?

**Comment by Rabie-Zamane** [comment]
Hi,
The issue/bug also exists in Harvester version 1.3.2.
I labeled the nvmes as follow: 

![grafik](https://github.com/user-attachments/assets/88b94465-60cf-4e49-9ef5-2d3481978edc) 

then I passed through the first one to the the vm

![grafik](https://github.com/user-attachments/assets/d6626db4-21d0-47dd-b225-94350edc4344)

first boot:

![grafik](https://github.com/user-attachments/assets/7ac0d821-1fcb-4aa8-9c6a-d6a4461fbf70)

Second boot:

![grafik](https://github.com/user-attachments/assets/2d328e8a-a3b5-44e6-9505-8006b340ff6f)
