### ISSUE TITLE
[Question] Are Load Balancer IPs Available Externally?

### ISSUE THREAD

**Issue by Daemonslayer2048** [harvester/harvester#5832]
## Summary
I feel like I have a bug but I am not sure at the moment. To explain: I am currently testing a single node Harvester machine with two NICs. One NIC is the management interface, the second NIC is my production/development NIC. NIC two has two VLANs attached (5 and 7). When I deploy a cluster to VLAN 7 all nodes are able to get an IP on VLAN 7 (10.0.7.0/26), then I can deploy a workload to the child cluster and get a loadblanced service with Traefik. I successfully obtain an IP from the IP pool, however I can never get the service to be accessible from out side the layer2 domain. Is this intended?

## Steps to reproduce    
- Deploy single node Harvester cluster  (I am on v1.3.0)
  - Node must have 1 mgmt interface, and 1 workload interface  
  - Workload interface should have a VLAN attached   
- From Rancher  
  - Create a project named "Production" in the harvester cluster
  - Create a namespace in the "Production" project named "production"  
  - Create a Cluster Network (I Named mine "cluster-net")
  - Add a Network Config to "cluster-net"  
    - Select all nodes   
    - Select the second NIC with VLAN
    - Mode: active-backup
    - Miimon: -1
    - MTU: 1500 
  - Add a VM Network
    -  Add to "production" namespace
    - Name: production
    - Type: L2VlanNetwork
    - VlanID: Whatever your vlan is (Mine is 7)
    - Cluster Network: cluster-net
    - Route: Your CIDR and Gateway (Mine is 10.0.7.1/26 and 10.0.7.1)
  - Add an IP Pool
    - Name: production
    - Range:  
      - Subnet: 10.0.7.1/26
      - Gateway: 10.0.7.1
      - Start IP: 10.0.7.20
      - End IP: 10.0.7.30  
    - Selector:
      - VM Network: production/vm
      - Scope: 
        - Production All All   
- Deploy child cluster via Rancher into Harvester node/cluster using VLAN interface
  - Use a loadbalancer service to consume an IP 
  - When you have consumed an IP confirm it can be curl'd.   
 
In my case it can not be curl'd directly as I am deploying Traefik so I set an entry in the VMs `etc/hosts` file corresponding to the VIP and hostname. This succeeds. Now curl the VIP from another network and it will fail. I can confirm there should be no firewall rules preventing this as I am ssh'ing into the VMs for the initial testing. From my firewall I can see my desktop is being allowed in to the production vlan.

## Notes
I did do a packet capture from the firewall interface and did find something of note:  
![image](https://github.com/harvester/harvester/assets/43078293/8a516a69-951e-42f0-852c-310648ebf357)  
In the snippet above from the packet capture my desktop (10.0.2.2) when reaching out to the loadbalanced IP (10.0.7.31) an ICMP response follows it with a "Destination unreachable". This is odd as I can SSH into those VMs (which are in that 10.0.7.0 network) and ping my desktop. So again no firewall funny business. 

Any guidance would be much appreciated.

**Comment by Daemonslayer2048** [comment]
I also believe I may be using VMs with too high of an MTU, much like the MTU issue described in the docs I thought I would go through all the VMs and set their MTU values to 1400 just in case.

No change

**Comment by Daemonslayer2048** [comment]
I will close this issue. I redeployed my harvester node and all appears to work fine.
One thing to note in the future: using `externalTrafficPolicy: Local` on a service appears to break the load balancer. I can't verify if this was the cause of the issue originally but using this setting does prevent access into the cluster.

**Comment by starbops** [comment]
Hi @Daemonslayer2048 For `externalTrafficPolicy: Local` to work, you'll need to enable leader election per service for kube-vip. Please refer to the [document](https://kube-vip.io/docs/usage/kubernetes-services/#external-traffic-policy-kube-vip-v050) for more details. kube-vip, which runs in the guest cluster, is responsible for the nitty-gritty. I tried enabling the `svc_leaderelection` option, but there seems to be a problem updating the lock/lease for services, so I wouldn't recommend it.

For your original issue, the setup looks fine and should work. If you happen to run into the problem again, please let us know. Thank you.
