### ISSUE TITLE
[Question] - Rancher 2.8.4

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#5834]
From the release note of rancher 2.8.4, I haven't seen potential breaking changes for Harvester.  Is it safe to upgrade Rancher to 2.8.4 if managing an Harvester cluster from Rancher and if so, is it possible to update the compatibility matrix on https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-x

Thanks

**Comment by bk201** [comment]
Hi @RegisHubelia, We'll update the support matrix once verification is done by QA.
cc @khushboo-rancher

**Comment by RegisWeduLabs** [comment]
Thank you!

**Comment by bk201** [comment]
Rancher 2.8.4 is added: https://www.suse.com/suse-harvester/support-matrix/all-supported-versions/harvester-v1-2-x/
