### ISSUE TITLE
[BUG] Remove Edit Config/YAML from the menu bar due to VLANs are not allowed to edit

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#584]
**Describe the bug**
Remove Edit Config/YAML from the menu bar due to VLANs are not allowed to edit

**To Reproduce**
1. Add VLANs
2. Edit them

**Expected behavior**
Remove Edit Config/YAML from the menu bar due to VLANs are not allowed to edit
![image](https://user-images.githubusercontent.com/57614736/112437997-8dd8e980-8d82-11eb-9af2-b2f28c4fab00.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by kingsd041** [comment]
Validated on master-c5a265d5-head

**Steps:**
1. Add VLANs
2. Edit them

**Result:**
The `edit` button has been removed from the menu, currently only `delete`

![image](https://user-images.githubusercontent.com/19684717/112572058-54f15100-8e24-11eb-903e-d8ee1369bf49.png)
