### ISSUE TITLE
[BUG] The support bundle did not contain the `yaml` directory

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5847]
**Describe the bug**
The support bundle did not contain the `yaml` directory after we generated it.

**To Reproduce**
We did not have the way to reproduce everytime.
But we still saw some support bundle from users did not contain the `yaml` directory.

For example, we found the following SB did not contain the `yaml` directory
https://github.com/harvester/harvester/issues/5828#issuecomment-2118612999
You can use cat to combine two files to unzip (e.g. cat a.zip b.zip > c.zip && unzip c.zip)

**Expected behavior**
The `yaml` directory should exist

**Support bundle**

Check the reproduce section

**Environment**
 - Harvester ISO version: 1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
Just to confirm that also encountered such.
