### ISSUE TITLE
[Question] What source code version of KubeVirt did Harvester 1.2.1 use to build for tag 0.54.0-150400.3.19.1?

### ISSUE THREAD

**Issue by went2** [harvester/harvester#5849]
**Describe the question**

Hi, I am replacing the installed KubeVirt components images tagged `0.54.0-150400.3.19.1` with the images built directly from KubeVirt source code. 

However, I cannot find the same tag `0.54.0-150400.3.19.1` in the KubeVirt source code repository; it only has the tag v0.54.0 (without -150400.3.19.1).

I tried using the images built from the `v0.54.0` source code (eg. my-resigtry/library/sles/15.4/virt-handler:0.54.0) to replace installed images(eg. `registry.suse.com/suse/sles/15.4/virt-handler:0.54.0-150400.3.19.1`), but they did not work correctly, causing pod scheduling errors and other issues.

Are there any clues on how can I build the same images from the KubeVirt source code as Harvester 1.2.1 used with tag `0.54.0-150400.3.19.1`.

The KubeVirt components I want to replace are listed below:

- registry.suse.com/suse/sles/15.4/libguestfs-tools:0.54.0-150400.3.19.1
- registry.suse.com/suse/sles/15.4/virt-api:0.54.0-150400.3.19.1
- registry.suse.com/suse/sles/15.4/virt-controller:0.54.0-150400.3.19.1
- registry.suse.com/suse/sles/15.4/virt-handler:0.54.0-150400.3.19.1
- registry.suse.com/suse/sles/15.4/virt-launcher:0.54.0-150400.3.19.1
- registry.suse.com/suse/sles/15.4/virt-operator:0.54.0-150400.3.19.1

Harvester version: 1.2.1 

Thanks for any help!

**Comment by bk201** [comment]
@Vicente-Cheng, can you help share the OBS repo.

**Comment by vasiliy-ul** [comment]
The source code for that specific KubeVirt build can be found at https://sources.suse.com/SUSE:Maintenance:29906/kubevirt.SUSE_SLE-15-SP4_Update/161c986f4b6065817b116c612420fc45/.

The tarball `kubevirt-0.54.0.tar.gz` contains the source code from the corresponding upstream revision (`v0.54.0`). Additionally, there are several patches fixing bugs and discovered CVEs. Those have been backported to this version and are applied during the build.

**Comment by bk201** [comment]
Thanks @vasiliy-ul , also add how to extract the URL by inspecting the image:
```
docker inspect registry.suse.com/suse/sles/15.4/virt-handler:0.54.0-150400.3.19.1 | grep kubevirt.disturl
                "com.suse.kubevirt.disturl": "obs://build.suse.de/SUSE:Maintenance:29906/containerfile/321fafd0bc6d9ac4f8f1f1d2caba6f76-virt-handler-container.SUSE_SLE-15-SP4_Update",
                "com.suse.kubevirt.disturl": "obs://build.suse.de/SUSE:Maintenance:29906/containerfile/321fafd0bc6d9ac4f8f1f1d2caba6f76-virt-handler-container.SUSE_SLE-15-SP4_Update",
```

Here we can get the request ID `SUSE:Maintenance:29906` and source will be under https://sources.suse.com/SUSE:Maintenance:29906/

**Comment by went2** [comment]
Thanks @vasiliy-ul , @bk201 for providing the detailed information and the link to the source code. This's exactly what I needed. Will use the source code from the link to try again. Thanks for your support!

**Comment by went2** [comment]
Thanks @vasiliy-ul , @bk201 for providing the detailed information and the link to the source code. This's exactly what I needed. Will use the source code from the link to try again. Thanks for your support!

**Comment by hchyue** [comment]
I also need to build the specific KubeVirt. I didn't find the way to build the kubevirt container images. how to build the container images with the source code https://sources.suse.com/SUSE:Maintenance:29906/kubevirt.SUSE_SLE-15-SP4_Update/161c986f4b6065817b116c612420fc45/.
thanks for help. @bk201 @vasiliy-ul 

> The source code for that specific KubeVirt build can be found at https://sources.suse.com/SUSE:Maintenance:29906/kubevirt.SUSE_SLE-15-SP4_Update/161c986f4b6065817b116c612420fc45/.
> 
> The tarball `kubevirt-0.54.0.tar.gz` contains the source code from the corresponding upstream revision (`v0.54.0`). Additionally, there are several patches fixing bugs and discovered CVEs. Those have been backported to this version and are applied during the build.
