### ISSUE TITLE
[Question]静态ip下，错误设置了network-setting，导致8443端口无法访问UI，UI已经崩溃了，请问怎么恢复这个设置为空？

### ISSUE THREAD

**Issue by kongzi68** [harvester/harvester#586]
现状：使用connmanctl配置的静态IP，在web管理界面设置了network-setting的值为{"NIC":"eth0","ConfiguredNIC":"eth0"}，导致web管理界面崩溃无法访问。

问题：
       1、请问在harvester master主机上，命令行模式，需要怎么操作【或者是修改什么配置文件】，才能把这个network-setting的值恢复成其默认值{"NIC":"","ConfiguredNIC":""}呢？
       2、把network-setting恢复成默认值后，harvester master 的web管理界面会自动恢复吗？

**Comment by yaocw2020** [comment]
Try `kubectl edit setting network-setting` to edit network-setting

**Comment by kongzi68** [comment]
![微信图片_20210326225709](https://user-images.githubusercontent.com/24288333/112652663-99163d00-8e88-11eb-99fb-20ad14bc7eb0.png)
谢谢，问题已经解决。
