### ISSUE TITLE
[ENHANCEMENT] bump cloud provider on rke2

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5866]
**Is your enhancement related to a problem? Please describe.**
We would like to use the latest cloud provider (v0.2.4) on rke2.

**Describe the solution you'd like**
Bump cloud provider v0.2.4 on rke2 master, v1.29, v1.28 and v1.27

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by Vicente-Cheng** [comment]
Related PRs:
https://github.com/rancher/rke2/pull/5980
https://github.com/rancher/rke2/pull/5981
https://github.com/rancher/rke2/pull/5982
https://github.com/rancher/rke2/pull/5983

**Comment by Vicente-Cheng** [comment]
PRs are merged
Corresponding issues here:
rke2-v1.30: https://github.com/rancher/rke2/issues/6008
rke2-v1.29: https://github.com/rancher/rke2/issues/5990
rke2-v1.28: https://github.com/rancher/rke2/issues/5991
rke2-v1.27: https://github.com/rancher/rke2/issues/5992

**Comment by w13915984028** [comment]
I added a PR https://github.com/harvester/charts/pull/243 to consolidate the steps to release a chart and bump it to upstreams.

**Comment by Vicente-Cheng** [comment]
close it because it's already done
