### ISSUE TITLE
[BUG] storage uses longhorn even when provisioned with a different storageclass

### ISSUE THREAD

**Issue by mjschmidt** [harvester/harvester#587]
**Describe the bug**

Harvester needs a way for the user to declare the storage class that they want to use because when you are not using longhorn-system storage the provisioner creates pvcs that can never be provisioned.

**To Reproduce**
1. deploy harvestor without the longhorn system (say rook-ceph) and set the helm chart default storage class to rook-ceph-block
2. deploy harvestor helm chart
3. through the gui create a vm that requires a pvc
4. grab the yaml from the gui, then delete the vm as it will not provision 
5. deploy the yaml directly, after changing the sotrageclass as so the pvc can be fulfilled 

**Expected behavior**

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by mjschmidt** [comment]
I am not sure where or why harvester is setting a storage class for the virtual machine volumes. Where is that code?

**Comment by guangbochen** [comment]
it is hardcoded in the UI to use `longhorn` as the default storage class. adding an option to set storage class name is considerable but it will not be covered in our support matrix and testing scope when using other CSI drivers, especially in regards to some advanced features like VM backup & live migration, it requires the CSI driver to support RWM and volumesnapshot features etc.

**Comment by mjschmidt** [comment]
How about supporting a upload yaml feature in the UI? I was able to download the yaml, make changes to it an then push it back. In the meantime I'd be happy to update the documentation and specify the work around? To hard code harvester for longhorn doesn't make a lot of sense to me especially when you can change in the helm yaml to specify to use another storageclass and not install longhorn.

**Comment by mjschmidt** [comment]
Or a disable button that dehardcodes and ignores the storage class and have a little warning that says if you disable some features may not work?

**Comment by mjschmidt** [comment]
@guangbochen if you could point me to which file is doing that hard coding I can fork and maintain my own copy, build my own container etc. Its not a big deal.

**Comment by guangbochen** [comment]
u can folk the https://github.com/rancher/harvester-ui and just replace the `ui-index` setting with your custom build.

**Comment by mjschmidt** [comment]
@guangbochen thanks I was able to work around by getting the yaml, deleting the vm and then editing the vm yaml template to use my own stoargeclass.

**Comment by futuretea** [comment]
@mjschmidt Hi, we have introduced [storageclass](https://docs.harvesterhci.io/v1.1/advanced/storageclass) in v1.1
You can specify storageclass when creating vms/volumes/images now.

**Comment by bk201** [comment]
@mjschmidt As @futuretea said, we support storage class in v1.1. Please see if the feature helps. Thanks.
