### ISSUE TITLE
[BUG] Harvester Kubeconfig Expires After 30 Days (No External Rancher Integration)

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5874]
**Describe the bug**
The Harvester Kubeconfig expires after 30 days.
When you download the Harvester Kubeconfig from the "support" portion of Harvester.

**To Reproduce**
1. Clone this repo: https://github.com/irishgordo/fake-ntp-thingy
1. Run `docker compose up` (or `-d` for detatched)
1. Check that it gives you back a date of 35 days prior from today, from your host machine to the container `ntpdate -q 192.168.9.163`, replace `192.168.9.163` with your host machine's ipv4 -> You can of course modify this date by setting in the Dockerfile `ENV FAKETIME="-Nd"` where "N" would represent the # of days we want to shift the date back, as we fake a date on the container running the ntp server `chrony` and cut `chrony` off from the outside world so it has no upstream ntp-servers
1. Install a Single-Node Harvester at v1.3-head (either ipxe-examples or iso) just be sure to set the NTP server to be your host machine
1. Once Harvester is installed check that it's using the NTP server via: `systemctl status systemd-timesyncd.service` - you should see it is pointing to the IPV4 address of your host machine
1. Goto Harvester Dashboard -> Support -> Download KubeConfig
1. Ensure the Kubeconfig works, eg `kubectl get nodes` when using the Kubeconfig
1. Then in Harvester, modify the setting of the ntp-server -> change it to `time1.google.com` or another NTP server of your desire
1. Ensure that when you look at on the single-node Harvester cluster's `cat /etc/systemd/timesync.conf` you should see that it has added the new "time server" to the file and would read something like `NTP = 192.168.9.163 time1.google.com` - you may need to query it a few times before the new time-server shows up 
1. Because it seems, that the NTP setting in Harvester is only additive, we need to modify the `/etc/systemd/timesync.conf`, we will modify it to remove the IPv4 address of your host machine so that it only reads `NTP = time1.google.com` 
1. Once modified we need to restart the systemd process, `systemctl restart systemd-timesyncd.service`
1. You should then see that it will resync, noting `systemctl status systemd-timesyncd.service`
1. Then refresh the GUI Harvester Dashboard, you'll see that it requires you to log in again
1. Then attempt, to use the Kubeconfig you downloaded, you will note, that it is broken when you try to do a `kubectl` operation:
```
kubectl get nodes
E0524 11:54:16.909964 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
E0524 11:54:16.910865 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
E0524 11:54:16.913613 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
E0524 11:54:16.914344 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
E0524 11:54:16.916780 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
E0524 11:54:16.917458 1540383 memcache.go:265] couldn't get current server API group list: the server has asked for the client to provide credentials
error: You must be logged in to the server (Unauthorized)
```

**Workaround**
The user must re-download the Kubeconfig.
Ex: Harvester Dashboard -> Support -> Download Kubeconfig

**Expected behavior**
The Kubeconfig for Harvester to not expire

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: v1.3-head 
 - Underlying Infrastructure: qemu/kvm or bare-metal, doesn't matter

**Additional context**
Relates to:
- https://github.com/harvester/harvester/issues/5669
- https://github.com/rancher/rancher/issues/44912
- https://github.com/harvester/harvester/issues/5827

This would impact a user's ability to use:
- kubectl
- terraform
- additional integrations, potentially

If the user was leveraging their Kubeconfig from Harvester's Support -> Download Kubeconfig in pipelines or the like, it will be entirely broken and force the user to implement the work-around

Thanks to @m-ildefons for pointing out "this" potential issue from 5669.

**Comment by irishgordo** [comment]
Opening:
https://github.com/harvester/harvester/issues/5876

To track the strange ntp-server /etc/systemd/timesyncd.conf behavior

**Comment by ibrokethecloud** [comment]
the kubeconfig expiry is being caused by the new kubconfig ttl-expiry setting introduced in rancher 2.8.x

https://ranchermanager.docs.rancher.com/api/api-tokens#kubeconfig-default-token-ttl-minutes

Users should be able to download the kubeconfig again from the UI.

**Comment by irishgordo** [comment]
> the kubeconfig expiry is being caused by the new kubconfig ttl-expiry setting introduced in rancher 2.8.x
> 
> https://ranchermanager.docs.rancher.com/api/api-tokens#kubeconfig-default-token-ttl-minutes
> 
> Users should be able to download the kubeconfig again from the UI.

I agree :smile: :+1:  - the workaround listed, is easy to implement in the interim.

**Comment by ibrokethecloud** [comment]
To test download a kubeconfig before and after this change:

1. Identify the `token` from the kubeconfig as follows
```
token=$(more $KUBECONFIG | yq '.users[0].user.token' | awk -F ":" '{print $1}')
```
2. Check ttl on token as follows
```
kubectl get token $token -o yaml | yq .ttl
```

Before the change when using harvester 1.2.2 or 1.3.0, the default ttl should be `2592000000`

After the change the default ttl should be `0`

Any changes to harvester setting `kubeconfig-default-token-ttl-minutes` will reflect in subsequent kubeconfig downloads.

**Comment by irishgordo** [comment]
@ibrokethecloud 

This is great :smile: and will definitely be useful :+1: 

I did want to mention a small validation issue that I'm noticing, though.

### Validation Issue
Either when setting the value on the UI, using @votdev 's un-merged feature-branch `API=IPv4 yarn dev` and navigating to localhost:8005 etc.
But also noticing / seeing this error just setting it to be, adding the `value: ""` field to it w/ kubectl edit on the setting itself.

That when it takes the shape of:
```
Name:         kubeconfig-default-token-ttl-minutes
Namespace:    
Labels:       <none>
Annotations:  harvesterhci.io/hash: 0e867c00b4100cac8fcc3c7570b3c659ff62d870b9acd6aedcf93fd3
API Version:  harvesterhci.io/v1beta1
Default:      0
Kind:         Setting
Metadata:
  Creation Timestamp:  2024-06-10T19:10:08Z
  Generation:          14
  Managed Fields:
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:default:
    Manager:      kubectl-edit
    Operation:    Update
    Time:         2024-06-10T20:04:32Z
    API Version:  harvesterhci.io/v1beta1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:harvesterhci.io/hash:
      f:status:
        .:
        f:conditions:
      f:value:
    Manager:         harvester
    Operation:       Update
    Time:            2024-06-10T22:01:23Z
  Resource Version:  144633
  UID:               02c71e23-6a14-426f-86c6-b62e5c2591d2
Status:
  Conditions:
    Last Update Time:  2024-06-10T20:04:32Z
    Status:            True
    Type:              configured
Value:                 99999999999999
Events:                <none>
```

We're hitting an upper bound limitation I believe of that TTL.
As it throws an error when trying to download the Kubeconfig either from:
- v1.3.1-rc2 's Dashboard
- votdev feature branch

```
failed to get default token TTL: failed to parse setting 'kubeconfig-default-token-ttl-minutes': error parsing token ttl: time: invalid duration "99999999999999m" 
```

![Screenshot from 2024-06-10 14-58-32](https://github.com/harvester/harvester/assets/5370752/c6d05b06-0a9e-471e-8036-62d5342db98e)

Not sure if we want to open this up as a separate issue or not - as I think the work-around would just be to not set the TTL to be a number that large.
As it is a pretty absurd number :laughing: - and highly un-likely anyone would set a value that high, when they could just set `0`.
But did want to mention this upper-bound limit on the validation and collect thoughts. :smile:

**Comment by irishgordo** [comment]
I've opened:
https://github.com/harvester/harvester/issues/6011
To track the small issue with the upper-bounds of the value :smile:

**Comment by irishgordo** [comment]
@ibrokethecloud  -Since 6011 is open, after the UI PR get's merged in - I can re-validate and then I believe we could close this out :smile: :+1:  - I validated the `kubectl` based edits w/ it respecting the timeout & I validated the UI  but only off of the fork & running `yarn dev` vs. having it all bundled into an artifact.

**Comment by irishgordo** [comment]
@ibrokethecloud thanks for this fix :smile: :+1: 
This looks good in v1.4.0-rc3.
I'll go ahead and close this out :smile: 

Can validate that:
- :green_circle:  GUI time input on ttl expiration is respected, when changed / altered
- :green_circle: default time on ttl is `0`
- :green_circle: updating ntp to date in future, still valid kubeconfig
- :green_circle: validation in data-type / allowed positive integers

I did open up [6837](https://github.com/harvester/harvester/issues/6837) to track another issue found

![Screenshot from 2024-10-21 13-23-29](https://github.com/user-attachments/assets/c2cdfafb-c179-4231-a166-ba29f039070e)
![Screenshot from 2024-10-21 13-09-10](https://github.com/user-attachments/assets/9d0ac917-c495-426d-a17e-c65b4926003e)
