### ISSUE TITLE
GUI access error "404 Not Found"

### ISSUE THREAD

**Issue by kingnarmer** [harvester/harvester#5875]
**Describe the bug**
I am getting error on gui access "404 Not Found"

![image](https://github.com/harvester/harvester/assets/48229843/ae1875d7-0404-4608-a60a-2fa02affc8c0)

**To Reproduce**
1. Go to 'https://IP-of-harvester-cluster'

**Expected behavior**
Get prompted for user/pass to access gui

**Support bundle**
Will send support bundle by email. 

**Environment**
 - Harvester ISO version:  1.3.0
 - Underlying Infrastructure : Dell PowerEdge R730
 -  Rancher 2.8.4

**Comment by kingnarmer** [comment]
support bundle create and sent.

**Comment by bk201** [comment]
@kingnarmer I didn't see the SB in the support bundle mailing box, can you help check again if it's sent to the correct address? Thanks.

**Comment by bk201** [comment]
The issue was resolved offline with Slack, feel free to reopen it if needed.
