### ISSUE TITLE
[BUG]Login page keeps requesting authentication api on proxy mode

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#588]
**Describe the bug**

Login page on proxy mode will keep requesting `/v1-public/authModes`

**Reason**

The page will redirect to Login Page when `/v1-public/authModes` throwing 401 error.
But `/v1-public/authModes` will also be requested on Login Page.
So the bug will occurs, keeps redirecting, keeps requesting.

**Environment:**
 - Installation Mode: `Rancher Catalog Apps`

**Comment by kingsd041** [comment]
**Validation Version**

master-67244e23-head

When accessing the login page in proxy mode, there is no repeated request of `/v1-public/authModes`
