### ISSUE TITLE
[BUG] iPXE Install Param `harvester.install.wipe_disks=true` may not be wiping fully at re-install

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5886]
**Describe the bug**
Installing v1.3-head.
Then installing v1.3-rc1, with `harvester.install.wipe_disks=true` on kernel/install-param.
Seems to cause hang at boot of:
```
booting from disk
```
On the node, where the node ends up in boot-loop.
Where the node does not use the RAID Controller, is purely setup with HBA Passthrough, no logical drives.

**Workaround**
- boot grml-full, `sgdisk -z /dev/sda` or whatever the disk is, prior to v1.3-rc1 install

**To Reproduce**
Pre-Reqs:
- no raid controller logical drives, only hba passthrough
- two drives something like "dev/sda" & "dev/sdb"
- both drives wiped with something like `sgdisk -z /dev/sda && sgdisk -z /dev/sdb`

1. Install v1.3-head, don't specify the parameter
1. Install v1.3-rc1, specify the parameter
1. Install will complete
1. Node is in bootloop

**Expected behavior**
Node to not be caught in boot-loop

**Environment**
 - Harvester ISO version: v1.3-head & v1.3-rc1
 - Underlying Infrastructure: baremetal

**Additional Context**
Sample pxe script at:
https://github.com/irishgordo/netboot.xyz-custom/blob/master/standardharvester.ipxe

**Comment by ibrokethecloud** [comment]
@irishgordo wast this an ipxe install or an iso based install?

**Comment by irishgordo** [comment]
Let me try to reproduce this :smile: :+1:

**Comment by irishgordo** [comment]
Going to close this out after 6+ times to try to reproduce, I can not reproduce this.
