### ISSUE TITLE
[BUG] v1.3.1-rc1 / v1.3-head doesn't show VirtualMachineImage Error in UI

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#5887]
**Describe the bug**
VirtualMachineImage Error is silent in the UI but noticeable on the console network tab.
```
'VirtualMachineImage.harvesterhci.io "image-hv6zw" is invalid: spec.sourceType: Unsupported value: "non-enum-testing-type": supported values: "download", "upload", "export-from-volume"'
```
Doesn't bubble up to anywhere that a user could see outside of the console -> Network Tab.

**To Reproduce**
1. Upload or Download a VirtualMachineImage
1. Once finished, click "Edit as YAML" -> change the YAML's spec.sourceType to be something that isn't: [ "download", "upload", "export-from-volume"']
1. You'll notice there is an "Error" in the call-to-action / SAVE button... but there is No Error presented to the end user in the UI of "what happened"

**Workaround**
- The user would need to manually audit the network tab, see the API request failed with a 422 response code back, then they would need to manually observe the "response" -> in that response they would be able to see the error

**Expected behavior**
The user to not have to look at the console -> network tab and the error to bubble up in the UI instead of a silent error that fails in the background

**Environment**
 - Harvester ISO version: v1.3.1-rc1 & v1.3-head 
 - Underlying Infrastructure: bare-metal / qemu-kvm

**Comment by bk201** [comment]
@torchiaf it seems like a UI issue to me, please help check it.

**Comment by torchiaf** [comment]
The errors should be displayed on top of the YAML editor view. I'll take a look.

**Comment by irishgordo** [comment]
@torchiaf thanks for this fix :+1: :smile:  - this looks good on Harvester Version: v1.4.0-dev-20240705 

I'll go ahead and close this out

![Screenshot from 2024-07-08 20-41-37](https://github.com/harvester/harvester/assets/5370752/a34c4a8b-36d8-446a-83b6-ae8bb2368344)
