### ISSUE TITLE
[ENHANCEMENT] Remove namespace annotation resource quota check

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5895]
**Is your enhancement related to a problem? Please describe.**
In current design, we validate resource quota from namespace annotation and corev1 ResourceQuota CR. We can just use corev1 ResourceQuota CR, because Rancher will help to sync value between two place.

Harvester: https://github.com/harvester/harvester/blob/5ee0329f1a6acef48e52758d3caf1d19e3bac1aa/pkg/util/resourcequota/calculator.go#L85-L104
Rancher: https://github.com/rancher/rancher/blob/a1c690ac47aa06d2206d71e2338f812a9d3b4267/pkg/controllers/managementuser/resourcequota/resource_quota_sync.go#L114-L195

**Comment by innobead** [comment]
@FrankYang0529 since you are working on this, assign it to the upcoming milestone directly next time.

**Comment by FrankYang0529** [comment]
I misunderstood the original design https://github.com/harvester/harvester/pull/3829. It uses both resource quota CR and resource quota on namespace annotation, because resource quota CR will change during VM migration. Resource quota on namespace annotation is more like single source of truth, so we need it.

Close the issue because we can't just use resource quota CR.
