### ISSUE TITLE
[ENHANCEMENT] Support Longhorn backing image HA

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5897]
**Is your enhancement related to a problem? Please describe.**

Longhorn will add the HA for backing images in 1.7.0, we need to leverage this enhancement. See the [LEP].(https://github.com/longhorn/longhorn/blob/master/enhancements/20240426-backing-image-enhancement.md)

**Describe the solution you'd like**

- Support the [`numOfCopies` field](https://github.com/longhorn/longhorn/blob/master/enhancements/20240426-backing-image-enhancement.md#crd) in VirtualMachineImage.
- Consider the node/disk eviction.
- (Optionally) Support [`diskSelector` and `nodeSelector`](https://github.com/longhorn/longhorn/blob/master/enhancements/20240426-backing-image-enhancement.md#crd-1).

**Describe alternatives you've considered**

**Additional context**

**Comment by WebberHuang1118** [comment]
Refer to LEP https://github.com/longhorn/longhorn/pull/8452

**Comment by WebberHuang1118** [comment]
If Images are created on the previous version, they will not have image HA. We will need a document update for this information.

**Comment by albinsun** [comment]
Test PASS, close as done.


### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: QEMU/KVM
  * ui-source: Auto


### Verification
### 2 nodes cluster
1. Prerequisite
   <details>
   <summary> Setup a 2 nodes cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/9da8e35c-e38a-4719-8256-57509e8578e2)
   </details>

   <details>
   <summary> On Harvester, create storage class <i>sc1</i> with <code>numberOfReplicas</code> 1
   </summary>
   
   ![image](https://github.com/user-attachments/assets/da01c771-821f-4182-8dd3-472e781c748c)
   </details>

   <details>
   <summary> On Longhorn, set Backing Image Cleanup Wait Interval to 1 min
   </summary>

   ![image](https://github.com/user-attachments/assets/d6c60d35-6536-4e31-b654-dcfb2200fe7f)
   </details>

1. :green_circle: Longhorn BI's `minNumberOfCopies` copies from Harvester SC's `numberOfReplicas`
   <details>
   <summary> <i>Given</i> set <i>sc1</i> as default storage class
   </summary>
   
   ![image](https://github.com/user-attachments/assets/da01c771-821f-4182-8dd3-472e781c748c)
   </details>

   <details>
   <summary> <i>When</i> create image on Harvester 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/6d3d28b9-2e8e-4b27-9e45-6a0bff59fdde)
   </details>

   <details>
   <summary> <i>Then</i> Longhorn BI's <code>minNumberOfCopies</code> copies from Harvester VMI's <code>numberOfReplicas</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/253fb6a2-723d-44d7-8d66-826ca8a351bb)
   </details>

   <details>
   <summary> <i>And</i> Longhorn BI do has <code>minNumberOfCopies</code> replica(s)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/81d22655-0481-4042-882e-b85eca34a62d)
   </details>


1. :green_circle: When node eviction, BI will migrate to satisfy `minNumberOfCopies`
   <details>
   <summary> <i>Given</i> <i>sc1</i> BI locates on <i>node-0</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f5e6456c-5495-4bf4-901e-322aef6e2731)
   </details>

   <details>
   <summary> <i>When</i> evict <i>node-0</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8b840600-0af1-4aee-8a06-87225dee8774)
   </details>

   <details>
   <summary> <i>Then</i> the replica will migrate to <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/76eba7f4-89e4-4e5b-9a4b-67c81c53b9b0)
   </details>


1. :green_circle: Increasing `minNumberOfCopies`, replicas also increases
   <details>
   <summary> <i>Given</i> a <i>sc1</i> BI locates on <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/76eba7f4-89e4-4e5b-9a4b-67c81c53b9b0)
   </details>

   <details>
   <summary> <i>And</i> Both nodes are <b>Schedulable</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/c7b0869d-61d3-40b8-870b-38f3cb7eef8a)
   </details>

   <details>
   <summary> <i>When</i> increase <code>minNumberOfCopies</code> to 2
   </summary>
   
   ![image](https://github.com/user-attachments/assets/ca818a58-9eca-4b35-a7c1-d78bac1098c5)
   </details>

   <details>
   <summary> <i>And</i> BI's replicas should expand to 2
   </summary>
   
   ![image](https://github.com/user-attachments/assets/ef31cb95-2bbf-4d5a-94fb-eef44a3d74b0)
   </details>

   <details>
   <summary> <i>And</i> BI's replicas will stay on 2 even increase <code>minNumberOfCopies</code> to 3 (over cluster size 2)
   </summary>
   
   * minNumberOfCopies 3 (over cluster size 2)
     ![image](https://github.com/user-attachments/assets/4af488ae-d375-4bf3-a00a-c3562a0c4db6)
   * Replica still 2
     ![image](https://github.com/user-attachments/assets/56cab707-69ec-4a99-993a-c458de529663)
   </details>


1. :green_circle: Decreasing `minNumberOfCopies`, replicas also decreases
   <details>
   <summary> <i>Given</i> BI's <code>minNumberOfCopies</code> and replicas are both 2
   </summary>
   
   * `minNumberOfCopies` 2
     ![image](https://github.com/user-attachments/assets/ef31cb95-2bbf-4d5a-94fb-eef44a3d74b0)
   * Replicas 2
     ![image](https://github.com/user-attachments/assets/ef31cb95-2bbf-4d5a-94fb-eef44a3d74b0)
   </details>

   <details>
   <summary> <i>When</i> decrease <code>minNumberOfCopies</code> to 1
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b6b60578-80a6-41a5-aba4-c5f20ab51e74)
   </details>

   <details>
   <summary> <i>And</i> BI' replicas should shrink to 1
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8d18ddab-6cc6-433e-b9a3-be57d8200c36)
   </details>



### 4 nodes cluster (2 defaults + 1 witness + 1 worker)
1. Prerequisite
   <details>
   <summary> Setup a 4 nodes cluster (2 defaults + 1 witness + 1 worker)
   </summary>

   * Harvester
     ![image](https://github.com/user-attachments/assets/aa38a3b8-311e-4945-a7a0-716d669144ae)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/8c279ad6-09c6-41d6-944e-f7c7e4c53f1a)
   </details>

   <details>
   <summary> On Harvester, create storage class <i>sc2</i> with <code>numberOfReplicas</code> 2
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b22131c4-abb6-4999-86cf-cce62feb94a0)
   </details>

   <details>
   <summary> On Longhorn, set Backing Image Cleanup Wait Interval to 1 min
   </summary>

   ![image](https://github.com/user-attachments/assets/d6c60d35-6536-4e31-b654-dcfb2200fe7f)
   </details>

1. :green_circle: Longhorn BI's `minNumberOfCopies` copies from Harvester SC's `numberOfReplicas`
   <details>
   <summary> <i>Given</i> set <i>sc2</i> as default storage class
   </summary>

   ![image](https://github.com/user-attachments/assets/b22131c4-abb6-4999-86cf-cce62feb94a0)
   </details>

   <details>
   <summary> <i>When</i> create image on Harvester 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b0bd8059-ccf2-4590-8f7b-2e5df6a7b87a)
   </details>

   <details>
   <summary> <i>Then</i> Longhorn BI's <code>minNumberOfCopies</code> copies from Harvester VMI's <code>numberOfReplicas</code> 2
   </summary>
   
   ![image](https://github.com/user-attachments/assets/6c6aa245-d7c2-4529-96dd-b7e32fe1d91b)
   </details>

   <details>
   <summary> <i>And</i> Longhorn BI do has 2 replica(s) on <i>node-0</i> and <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d9c44248-6f20-4728-a6ef-6d3f01f232ed)
   </details>


1. :green_circle: When node eviction, BI will migrate to satisfy `minNumberOfCopies`
   <details>
   <summary> <i>Given</i> <i>sc2</i> BI locates on <i>node-0</i> and <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d9c44248-6f20-4728-a6ef-6d3f01f232ed)
   </details>

   <details>
   <summary> <i>When</i> evict <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/15d87313-ef48-4906-af76-29dff4990f54)
   </details>

   <details>
   <summary> <i>Then</i> the replicas will locates on <i>node-0</i> and <i>node-3</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/589cf3a5-63e5-474d-b8c7-41bc17e4065b)
   </details>


1. :green_circle: Increasing `minNumberOfCopies`, replicas also increases
   <details>
   <summary> <i>Given</i> a <i>sc2</i> BI locates on <i>node-0</i> and <i>node-3</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/589cf3a5-63e5-474d-b8c7-41bc17e4065b)
   </details>

   <details>
   <summary> <i>And</i> All nodes are <b>Schedulable</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8e592cd5-3298-4a21-b4a4-64c51549fc9a)
   </details>

   <details>
   <summary> <i>When</i> increase <code>minNumberOfCopies</code> to 3
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b7364536-42fc-4548-aa9d-4f191c876ea4)
   </details>

   <details>
   <summary> <i>And</i> BI's replicas should expand to 3
   </summary>
   
   ![image](https://github.com/user-attachments/assets/9cae0dd6-b0c6-4373-83b9-34ec1eb330af)
   </details>

   <details>
   <summary> <i>And</i> BI's replicas will stay on 3 even increase <code>minNumberOfCopies</code> to 4 (over cluster size 3)
   </summary>
   
   * minNumberOfCopies
     ![image](https://github.com/user-attachments/assets/9ed572e7-b32d-4388-bfae-022606263331)
   * Replica
     ![image](https://github.com/user-attachments/assets/403ac153-7b2a-4fd5-9427-7cda760b1add)
   </details>


1. :green_circle: Decreasing `minNumberOfCopies`, replicas also decreases
   <details>
   <summary> <i>Given</i> BI's <code>minNumberOfCopies</code> and replicas are both 3
   </summary>
   
   * minNumberOfCopies
     ![image](https://github.com/user-attachments/assets/9ed572e7-b32d-4388-bfae-022606263331)
   * Replica
     ![image](https://github.com/user-attachments/assets/403ac153-7b2a-4fd5-9427-7cda760b1add)
   </details>

   <details>
   <summary> <i>When</i> decrease <code>minNumberOfCopies</code> to 1
   </summary>
   
   ![image](https://github.com/user-attachments/assets/10af7bc7-61d5-4257-acb8-b0540848a539)
   </details>

   <details>
   <summary> <i>And</i> BI' replicas should shrink to 1
   </summary>
   
   ![image](https://github.com/user-attachments/assets/1d4d5a71-bb03-4c09-88d9-60a28809d27b)
   </details>

1. :green_circle: When node eviction, the BI will migrate to satisfy `minNumberOfCopies`
   <details>
   <summary> <i>Given</i> BI has only 1 replica locates on <i>node-3</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/acec0cc8-fdf0-427a-8f4d-088f5855f360)
   </details>

   <details>
   <summary> <i>When</i> evict <i>node-3</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/bb1ff3e9-653d-4c1e-b548-6da825db0283)
   </details>

   <details>
   <summary> <i>Then</i> the replicas will locates on <i>node-0</i> or <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/2738437b-49e2-4fa8-9268-bca572f5ed29)
   </details>

1. :green_circle: When node eviction and no available nodes, will see error
   <details>
   <summary> <i>Given</i> BI has only 1 replica locates on <i>node-1</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/dd188478-28a4-41b7-b990-9847ce80899f)
   </details>

   <details>
   <summary> <i>When</i> evict <i>node-1</i> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7544cf42-f655-44b8-865f-1043a0db584f)
   </details>

   <details>
   <summary> <i>Then</i> will get error <code>Failed to evict backing image</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4f882852-482b-4085-97f3-bffa713458ba)
   </details>
