### ISSUE TITLE
[BUG] In first request, go-harvester login will return io.EOF because of cert change, need retry

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#590]
**Describe the bug**

**To Reproduce**
1.  harvester fresh setup
2.  use harvester node-driver to create a cluster

**Expected behavior**

**Log**

```bash
Error with pre-create check: "Get \"https://harvester.harvester-system:8443/v1-public/auth-modes\": EOF"; Timeout waiting for ssh key
```

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
link to #512

**Comment by DoNotSayYes** [comment]
Validated on master-head
![image](https://user-images.githubusercontent.com/57614736/115512586-b934f280-a2b4-11eb-992a-c581be481792.png)
