### ISSUE TITLE
[ENHANCEMENT] [UI] Refactor Attached VM information

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#5905]
**Is your enhancement related to a problem? Please describe.**
When we implemented https://github.com/harvester/harvester/pull/5406, we found that `Attached VM` information is empty. It looks like UI use `harvesterhci.io/owned-by` annotation to get the result.

**Describe the solution you'd like**
Refactor UI to build a PVC to VM map from VM. 

Option 1: for loop each PVC in VM.spec.template.spec.volumes to build the map.
Option 2: use LH information to get workload name.

1. PVC.spec.volumeName -> LH Volume.
2. Volume.status.kubernetesStatus.workloadsStatus.workloadName -> VM. The `workloadsStatus` is a list, so we have to filter `podStatus: Running` in it.

**Additional context**
https://github.com/harvester/harvester/issues/5383

**Comment by albinsun** [comment]
Test PASS, close as done.


### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G per node)
  * ui-source: Auto


### Prerequisite
1. <details>
   <summary> Create VM image <i>ubuntu-22.04-jammy-server-cloudimg-amd64.img</i>
   </summary>

   ![image](https://github.com/user-attachments/assets/d43978c4-f46b-4b74-9f64-26f80cf00c8c)
   </details>


### Test Case
1. :green_circle: New empty volume
   <details>
   <summary> <i>When</i> creating a volume <i>volume-new</i> with source <b>New</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/df442995-3fd2-4588-adf4-1f4b51fdbee8)
   </details>

   <details>
   <summary> <i>Then</i> <i>volume-new</i> has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e2e58377-38ad-4c57-84a4-30a179f8f5fd)
   </details>

   <details>
   <summary> <i>And</i> <i>volume-new</i> has empty <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/57cfe167-6701-47f6-b4b9-2d24e92abce3)
   </details>


1. :green_circle: Resizing volume
   <details>
   <summary> <i>When</i> resizing volume <i>volume-new</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/a556936d-8964-4cde-925c-f0b6195ede62)
   </details>

   <details>
   <summary> <i>Then</i> <i>volume-new</i> has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f41b2ab1-0d41-4013-b144-a5535ea49bad)
   </details>

   <details>
   <summary> <i>And</i> <i>volume-new</i> has empty <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/2b3008ef-d973-4541-a9a4-c14fba29e724)
   </details>


1. :green_circle: Volume from VMI
   <details>
   <summary> <i>When</i> creating a volume <i>volume-vmi</i> from VMI
   </summary>
   
   ![image](https://github.com/user-attachments/assets/06e8b714-f878-42c5-958f-13f2770bb26e)
   </details>

   <details>
   <summary> <i>Then</i> <i>volume-vmi</i> has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7a54be26-f389-41a0-b80b-0a9b8ffd65e9)
   </details>

   <details>
   <summary> <i>And</i> <i>volume-vmi</i> has empty <b>Attached VM</b> 
   </summary>

   ![image](https://github.com/user-attachments/assets/06e8b714-f878-42c5-958f-13f2770bb26e)
   </details>


1. :green_circle: Create VM
   <details>
   <summary> <i>When</i> creating a VM using <i>volume-vmi</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d9396809-2555-485b-9fae-31bf0635962d)
   </details>

   <details>
   <summary> <i>Then</i> <i>volume-vmi</i> has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8c99a95b-7df4-4684-8769-b27f28689611)
   </details>

   <details>
   <summary> <i>And</i> <i>volume-vmi</i> has <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e27cc3d1-c363-449b-a3ae-a6af9dd96d6a)
   </details>


1. :green_circle: Resizing attached volume
   <details>
   <summary> <i>Given</i> attached volume <i>volume-vmi</i> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e27cc3d1-c363-449b-a3ae-a6af9dd96d6a)
   </details>

   <details>
   <summary> <i>When</i> stop VM and resizing volume <i>volume-vmi</i>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/6ee78dae-1f80-4bb8-b4e7-84efad7e6f63)
   </details>

   <details>
   <summary> <i>Then</i> <i>volume-vmi</i> has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/fed6404e-7be9-43ef-843c-2df2df9c35b1)
   </details>

   <details>
   <summary> <i>And</i> <i>volume-vmi</i> has <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8c195390-9f39-4e06-b903-2b769fb780d9)
   </details>


1. :green_circle: Attaching volume
   <details>
   <summary> <i>Given</i> a VM from last case
   </summary>
   
   ![image](https://github.com/user-attachments/assets/47b0a22b-8e48-4024-9b81-f53b22361f45)
   </details>

   <details>
   <summary> <i>When</i> attaching <i>volume-new</i> to VM
   </summary>
   
   ![image](https://github.com/user-attachments/assets/fef9bb79-0a59-434a-9827-ff2a227b93c1)
   </details>

   <details>
   <summary> <i>Then</i> both volumes have NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   * volume-vmi
     ![image](https://github.com/user-attachments/assets/bd6ea860-3550-477d-b368-98e6fd52e182)
   * volume-new
     ![image](https://github.com/user-attachments/assets/0e7f3db1-071c-4b24-be5e-e2aa63597b3f)
   </details>

   <details>
   <summary> <i>And</i> both volumes have <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/bec33ca6-8b63-4a5c-8d4e-1e3282daf172)
   </details>

   <details>
   <summary> <i>And</i> start VM do not change previous assertion
   </summary>
   
   * Start
     ![image](https://github.com/user-attachments/assets/9bc9523b-fd0a-4989-987b-b51696f6a6d6)
   * Attached VM
     ![image](https://github.com/user-attachments/assets/c1d32237-2890-44c0-82f5-71651d633d3a)
   * NO **harvesterhci.io/owned-by** annotation
     ![image](https://github.com/user-attachments/assets/c29afb0a-925d-4cd0-9dca-ea81197b7aed)
     ![image](https://github.com/user-attachments/assets/e801f0ce-0273-4abb-8b3d-ebcce95a1dbd)
   </details>


1. :green_circle: Backup and restore New
   <details>
   <summary> <i>Given</i> backup a running VM
   </summary>
   
   ![image](https://github.com/user-attachments/assets/65bb58df-16d7-4467-b17a-84dfa174c405)
   </details>

   <details>
   <summary> <i>When</i> restore New the backup 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/02f4d603-797d-4d4d-a921-0d54cc0febc3)
   </details>

   <details>
   <summary> <i>Then</i> all volumes has NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>

   * _vm_
     ![image](https://github.com/user-attachments/assets/2c3f0c7a-f3a3-44a9-8574-75cc9ead8910)
     ![image](https://github.com/user-attachments/assets/d13dc455-dda2-4fe4-8bf9-1b8fddd519f1)
   * _vm.restore_
     ![image](https://github.com/user-attachments/assets/8c77061b-b1d6-4227-b4b2-f62ea8ada73a)
     ![image](https://github.com/user-attachments/assets/89c1153f-11ec-4687-b3f8-c92fd46df1dc)
   </details>

   <details>
   <summary> <i>And</i> all volumes has <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4f63e774-2de5-4991-8ca3-35f814d47a87)
   </details>


1. :green_circle: Backup and restore replace
   <details>
   <summary> <i>Given</i> backup a running VM
   </summary>

   ![image](https://github.com/user-attachments/assets/65bb58df-16d7-4467-b17a-84dfa174c405)
   </details>

   <details>
   <summary> <i>When</i> stop vm and restore <b>Replace existing</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3edede32-5105-4651-af90-dee24abefe76)
   ![image](https://github.com/user-attachments/assets/a39499d1-d44b-4884-9d8d-7a04171510c9)
   </details>

   <details>
   <summary> <i>Then</i> both volumes have NO <b>harvesterhci.io/owned-by</b> annotation 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/2f9030ba-0681-4426-aea7-e2681ed85e01)
   ![image](https://github.com/user-attachments/assets/daa032fb-88a5-48ef-a133-e58a073463b0)
   </details>

   <details>
   <summary> <i>And</i> both volumes have <b>Attached VM</b> 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/593e8845-206a-4548-8dd1-7c12c762a82e)
   </details>


### Supportbundle


### QA Check List
1. Update labels
   - [x] This ticket: `not-require/test-plan`, `not-require/release-note`, `require-ui`, `regression`...
   - [x] tests ticket: harvester/tests/issues/1369
