### ISSUE TITLE
[BUG] Node recovery installation fails at Configure Network - ifreload fails

### ISSUE THREAD

**Issue by krumware** [harvester/harvester#5907]
**Describe the bug**

During the recovery process prompted by the `Harvester v1.3.0 recovery` boot option, the process fails at the Configure Network step.
After configuring the network, an error is received: `device-not-running\n: failed to run wicket ifreload all: exit status 2`
It is then not possible to advance the recovery past this point.
The same behavior occurred on agent nodes as well as the original creation node.

**To Reproduce**

1. Attempt to Restore a node.
2. Select `Create new cluster`
3. Follow steps until the Configure Network screen.
4. Configure the network, then observe the failure.

**Expected behavior**

Normal function.

**Support bundle**

Unable to retrieve support bundle. Kubectl and UI both not working, and instructions are unclear outside of those methods.

**Environment**

 - Harvester ISO version: 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare metal with mini PCs

**Additional context**

I am attempting to reinstall or restore harvester after the host network IP range changed. The VIP was not successfully restored following changes in the host network.

**Comment by WebberHuang1118** [comment]
IIUC, Harvester doesn't officially support change VIP https://github.com/harvester/harvester/issues/4584.

However, @starbops provided some preliminary experiments on it https://github.com/harvester/harvester/issues/4584#issuecomment-2046463200

@starbops @w13915984028  @mingshuoqiu any feedback on this? Thanks

**Comment by krumware** [comment]
This wasn't done in an attempt to change VIP, the recovery was an attempt to fix the primary node after it failed to restore the VIP. (That was for extra context anyways). I don't know if the recovery would have fixed the VIP issue, but the failure to successfully go through recovery did seem worthy of reporting. 

I believe the VIP issue may also be reportable but I intended that for a separate issue, as the nodes failed to reestablish the VIP despite being configured as static, and maybe that's also related to the ifreload issue behind the scenes.

**Comment by Vicente-Cheng** [comment]
Hi @krumware,

Thanks for raising this issue.
I am curious about the first two steps.
```
1. Attempt to Restore a node.
2. Select Create new cluster
```

If you would like to create a new cluster, why do you try to restore a node?
Do you want to keep some configuration? Is that the reason?

Thanks!

**Comment by krumware** [comment]
Frankly, I was uncertain what option to choose there. When I entered recovery mode and saw that it was essentially the installer, I assumed I needed to select Create new cluster since it was the node that previously had the Create in the harvester.config. Primarily I needed a node which would recreate the VIP. I was hopeful the previous configuration would be maintained to some degree and this would perform a repair or at least create a new cluster using the previous config values.

**Comment by Vicente-Cheng** [comment]
Hi @krumware, sorry for the late reply.

I tried to conclude your situation as below: (If something I understand wrong, please correct me)
 
You lost the VIP after some errant behavior (move to another DHCP server), and the VIP could not get back after you moved back (Back to the previous DHCP server). Also, the kubectl can not be used anymore.

I am afraid something is changed or broken when you move to another DHCP server. The kubectl cannot perform might be related to the `kube-apiserver`. 

Could you show the error message of kubectl command failed?

cc @FrankYang0529, @starbops, @ibrokethecloud, and @bk201 to see if we ever encounter this situation.

**Comment by krumware** [comment]
Unfortunately, I don't have the exact kubectl error, but it was essentially the failure to connect to 127.0.0.1 error. Typical if RKE2 is not running correctly.

Fortunately, the situation is easy to replicate (doing now for testing). I have 3 nodes connected to a router. That router provides an IP range `192.168.1.` 10-254. The router and is configured for DHCP, and was connected to a different network , which caused the router to update its IP range to a different subnet `10.175.1.`
All nodes simultaneously transition into NotReady almost immediately, and Management URL on all nodes is Unavailable. They all do show the correct IP for their own node details.
You'll see that the reservations do remain:
![image](https://github.com/harvester/harvester/assets/17303782/21d45216-d72a-4d0a-8b2c-d52044bee365)

Once I reconnect the router to the appropriate network and update the IP range, the cluster never recovers.
`ip addr show mgmt-br` only shows the node IP only, on all nodes.
`kubectl` commands result in `couldn't get current server API group list: Get "https://127.0.0.1/api?timeout=32s": dial TCP 127.0.0.1:6443: connect: connection refused`

**Comment by krumware** [comment]
Just confirming, I was able to replicate on command. Am available for calls if needed to demonstrate

**Comment by Vicente-Cheng** [comment]
Hi @krumware, 
Nice to hear this information.
~Could you provide the steps to reproduce it?~
Are the reproduction steps from the above:
1. create 3 nodes harvester cluster
2. move to another DHCP server (with different network scope)
3. move back to the original DHCP server

Is that correct?

Then, we could investigate and check if it is a bug or something that is a limitation.

BTW, could you please change the title?
I thought your case was not related to the node recovery, right?

UPDATE:
If you still have the env with that issue, could you also help to get the `rke2-server` logs here?

Thanks!

**Comment by krumware** [comment]
Hi Vincent,

Correct, those are the steps. Unfortunately I don't have the rke2-server logs handy but I can't grab that here at susecon, or shortly after.

Thanks!
Colin

**Comment by krumware** [comment]
For the title change, it may be more appropriate to move the comments to a new issue. I believe the original issue is still relevant (though was discovered through attempts at resolution of the one in conversation)

**Comment by Vicente-Cheng** [comment]
Hi @krumware 

>Correct, those are the steps. Unfortunately I don't have the rke2-server logs handy but I can't grab that here at susecon, or shortly after.

No worries. After the steps are confirmed, we could reproduce them in our own environment to investigate.
You can also help to update the logs once you are back from the susecon.

> For the title change, it may be more appropriate to move the comments to a new issue. I believe the original issue is still relevant (though was discovered through attempts at resolution of the one in conversation)

Sure, could you help to create a new issue to track this?

Thanks!

**Comment by krumware** [comment]
Yes sir, I'll knock that out this week during the susecon shenanigans. Thanks!

**Comment by ER-EPR** [comment]
I can confirm this bug in 1.2.1, 1.2.0, and 1.1.x images. 
![image](https://github.com/user-attachments/assets/56c0d771-5290-4942-bc0c-2c0738dd00fa)
Choose recovery in the boot menu, either create or join, in the network config stage, the interface display name is not correct, and it can not acquire a IP address.
