### ISSUE TITLE
[BUG] VM network is unreachable in VLAN

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#591]
**Describe the bug**
VM network is unreachable in VLAN

**To Reproduce**
1. Set a default NIC
2. Create an available VLAN network
3. Create VMs using that VLAN

**Expected behavior**
VM network is reachable

**Result**
Now the network between VMs is unreachable

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO

**Comment by yaocw2020** [comment]
We have to set the switch port as trunk mode.

**Comment by kongzi68** [comment]
> We have to set the switch port as trunk mode.

我目前有3台物理主机搭建了harvester集群，请问是接三台主机的交换机端口都需要设置为`trunk mode`吗？还是只需要设置控制节点所在的那台物理服务器的交换机端口为`trunk mode`呢？
![微信图片_20210330095345](https://user-images.githubusercontent.com/24288333/112921773-f1c23000-913d-11eb-95d3-4ee101ea8817.png)
也就是说，我三台harvester物理服务器的ip地址段为`192.168.16.100~254`之间，通过DHCP获取。我想harvester里面创建的虚拟机可以获取到`192.168.16.100~254`之间的IP，也就是真实IP，并且与外部能通信。
目前，我通过cloud init给虚拟机设置了IP：192.168.16.100，但是无法ping通外部网络。

**Comment by yaocw2020** [comment]
All of the switch ports have to set as trunk mode.

**Comment by yaocw2020** [comment]
> > We have to set the switch port as trunk mode.
> 
> 我目前有3台物理主机搭建了harvester集群，请问是接三台主机的交换机端口都需要设置为`trunk mode`吗？还是只需要设置控制节点所在的那台物理服务器的交换机端口为`trunk mode`呢？
> ![微信图片_20210330095345](https://user-images.githubusercontent.com/24288333/112921773-f1c23000-913d-11eb-95d3-4ee101ea8817.png)
> 也就是说，我三台harvester物理服务器的ip地址段为`192.168.16.100~254`之间，通过DHCP获取。我想harvester里面创建的虚拟机可以获取到`192.168.16.100~254`之间的IP，也就是真实IP，并且与外部能通信。
> 目前，我通过cloud init给虚拟机设置了IP：192.168.16.100，但是无法ping通外部网络。

All of the switch ports have to set as trunk mode.

**Comment by kongzi68** [comment]
使用的版本为：Rancher Harvester v0.1.0 initial release
目前，我三台物理服务器组建了harvester集群。1管理节点，2node节点。在交换机中，接3台服务器的端口都设置了dhcp 、trunck，以及配置了vlanID分别为16、17。我在harvesterUI界面创建了两个vlan，分别为：vlan16，id为16；vlan17，id为17。已经调通，创建的虚拟机可以DHCP获取到真实IP了。谢谢。

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/591#issuecomment-819284527
