### ISSUE TITLE
[BUG] Upgrade to 1.3.1RC - managed chart harvester is not ready

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#5917]
**Describe the bug**
I have 3 nodes cluster v1.3.0: 
- 2 management-workers node
- 1 witness

I applied https://releases.rancher.com/harvester/v1.3.1-rc1/version.yaml

Then I pressed UPGRADE -> UPGRADE in the web UI

Got the error message:

> admission webhook "validator.harvesterhci.io" denied the request: managed chart harvester is not ready, please wait for it to be ready

Looking into details I see this message:
>  ErrApplied(1) [Cluster fleet-local/local: release: not found]; deployment.apps harvester-system/harvester [progressing] Available: 2/3; deployment.apps harvester-system/harvester-webhook [progressing] Deployment does not have minimum availability., Available: 2/3

```
# kubectl get bundles.fleet.cattle.io -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1
fleet-local   local-managed-system-agent                    1/1
fleet-local   mcc-harvester                                 0/1                       ErrApplied(1) [Cluster fleet-local/local: release: not found]; deployment.apps harvester-system/harvester [progressing] Available: 2/3; deployment.apps harvester-system/harvester-webhook [progressing] Deployment does not have minimum availability., Available: 2/3
fleet-local   mcc-harvester-crd                             1/1
fleet-local   mcc-local-managed-system-upgrade-controller   1/1
fleet-local   mcc-rancher-logging-crd                       1/1
fleet-local   mcc-rancher-monitoring-crd                    1/1
```

Looking at UI, I see all 3 nodes are in the healthy state:
![Screenshot 2024-05-30 at 11 41 27](https://github.com/harvester/harvester/assets/6293679/e62c6725-fc99-4314-8408-9178ba881690)

can the issue be because I only 2 management/workers nodes and 3rd is witness?

I know that upgrade 1.3.0 -> 1.3.1RC1 is not officially supported, but is it possible? is there any way to do that?

**Support bundle**
https://s3.fursov.family/shares/supportbundle_06b15f17-7231-42ca-9fbe-58f9e910f3b6_2024-05-30T18-47-23Z.zip

**Comment by bk201** [comment]
This could be due to the witness node.

>I know that upgrade 1.3.0 -> 1.3.1RC1 is not officially supported, but is it possible? is there any way to do that?

It's not recommended because we won't verify the path `1.3.1-rc1` to `1.3.1`.

**Comment by SlavikCA** [comment]
Tested with 1.3.1.
Same error.

Can not upgrade from 2 node + witness 1.3.0 to 1.3.1 because of `Deployment does not have minimum availability`.

Is there any workaround?

**Comment by w13915984028** [comment]
@SlavikCA You may try to edit the `kubectl edit deployment harvester -n harvester-system`, and set the following annotation to 2 instead of 3,  then wait a while to check if the managedchart chages to ready.

```
management.cattle.io/scale-available:
```

**Comment by zerofai** [comment]
> @SlavikCA You may try to edit the `kubectl edit deployment harvester -n harvester-system`, and set the following annotation to 2 instead of 3, then wait a while to check if the managedchart chages to ready.
> 
> ```
> management.cattle.io/scale-available:
> ```

Checked on my 2 node + witness system,  management.cattle.io/scale-available:  is 2, but still not allow me to upgrade.

**Comment by Vicente-Cheng** [comment]
Hi @SlavikCA, sorry for the late reply

I checked the support bundle, looks we have the redundant machine.
That's why the managed chart will show not ready.

Do you still encounter this situation?

**Comment by SlavikCA** [comment]
Yes, issue still exists

**Comment by Vicente-Cheng** [comment]
> Yes, issue still exists

Hi @SlavikCA, 
Could you generate an SB again?

I would like to recheck it and give some instructions for your situation.
Thanks!

**Comment by SlavikCA** [comment]
@Vicente-Cheng 
I manually re-installed Harvester 1.3.1, so currently my system is not in the UPGRADE state.

I think whenever version 1.3.2 will be ready, I'll have same problem. So, I'll generate SB then.

**Comment by Vicente-Cheng** [comment]
Thanks @SlavikCA,

Feel free to give feedback and ping me.
I will take a look at your issue.

**Comment by bk201** [comment]
Please re-open if seeing the issue again, thanks!
