### ISSUE TITLE
[BUG] Managed charts have inconsistent generations after upgrading from v1.3.0 to v1.3.1-rc1

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5923]
**Describe the bug**

After upgrading from v1.3.0 to v1.3.1-rc1, some managed charts' generation and observedGeneration mismatch and are marked as "In Progress" in the Rancher GUI.

![Screenshot from 2024-05-30 17-02-09](https://github.com/harvester/harvester/assets/1691518/959a1d60-f0a9-4135-b9c2-7bf3f9b6bba1)

**To Reproduce**
1. Create a v1.3.0 cluster.
2. Upgrade to v1.3.1-rc1.
3. Check the ManagedCharts:
```
$ kubectl get managedcharts -n fleet-local -o yaml | yq '.items[] | .metadata.name + ", " + .metadata.generation + ", " + .status.observedGeneration'
harvester, 4, 5
harvester-crd, 4, 5
local-managed-system-upgrade-controller, 2, 2
rancher-logging-crd, 3, 4
rancher-monitoring-crd, 3, 4
```

Note: The charts are deployed and the upgrade is fine.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by FrankYang0529** [comment]
I can reproduce the issue, but the behavior is weird. In general, server updates `generation` first and controller updates `observedGeneration` after finishes the job, so `observedGeneration` can't be greater than `generation`.

From Rancher source code, it updates managed chart status from bundle. If we update bundle directly, this case may happen. However, I can't find any source code update bundle directly in Harvester.

https://github.com/rancher/rancher/blob/29572e61e1bc6c92621df9951da900aaa981f512/pkg/controllers/provisioningv2/managedchart/managedchart.go#L166-L176

**Comment by FrankYang0529** [comment]
The reproduce steps can be simplified as followings:

1. Deploy Harvester v1.3.0.
2. Bump Rancher.
```
helm repo add rancher-stable https://releases.rancher.com/server-charts/stable
helm get values rancher -n cattle-system -o yaml > values.yaml
yq -e e '.rancherImageTag = "v2.8.3"' values.yaml -i
helm upgrade rancher rancher-stable/rancher --namespace cattle-system -f values.yaml --wait
```
3. After Rancher is rollout and wait for few seconds. Check managed charts `generation` and `observedGeneration`.
```
$ kubectl get managedcharts -n fleet-local -o yaml | yq '.items[] | .metadata.name + ", " + .metadata.generation + ", " + .status.observedGeneration'

harvester, 1, 2
harvester-crd, 1, 2
local-managed-system-upgrade-controller, 2, 3
rancher-logging-crd, 1, 2
rancher-monitoring-crd, 1, 2
```

**Comment by FrankYang0529** [comment]
The main problem is that `correctDrift` is not a nullable field in fleet v0.9.0, but it is in v0.9.2. After we upgrade to fleet v0.9.2, the empty `correctDrift: {}` is removed and it triggers bundle generation update.

* v0.9.0: https://github.com/rancher/fleet/blob/93432f288e79f436e2f5cfe940e3274994d00b29/charts/fleet-crd/templates/crds.yaml#L50-L52
* v0.9.2: https://github.com/rancher/fleet/blob/e75c1fb498e3137ba39c2bdc4d59c9122f5ef9c6/charts/fleet-crd/templates/crds.yaml#L50C17-L53

Since managed chart doesn't provide fields to control `correctDrift` in fleet, we can't set some default values before upgrading to avoid removing the field.

A workaround is to stop fleet-controller and rancher to make managed chart generation keep up with bundle and then start controllers again. For example:

```
kubectl scale deploy fleet-controller -n cattle-fleet-system --replicas=0
kubectl scale deploy rancher -n cattle-system --replicas=0
kubectl patch managedcharts.management.cattle.io harvester-crd -n fleet-local --type='json' -p='[{"op": "replace", "path": "/spec/paused", "value":true}]'
kubectl patch managedcharts.management.cattle.io harvester-crd -n fleet-local --type='json' -p='[{"op": "replace", "path": "/spec/paused", "value":false}]'

kubectl scale deploy fleet-controller -n cattle-fleet-system --replicas=1
kubectl scale deploy rancher -n cattle-system --replicas=1
kubectl patch bundles.fleet.cattle.io mcc-harvester-crd -n fleet-local --type='json' -p='[{"op": "add", "path": "/spec/correctDrift", "value":{}}]'
```

**Comment by FrankYang0529** [comment]
Following upgrade path can pass without error. Although there is inconsistent generation finally, it doesn't block upgrade. I think we can close the issue. Thanks.

v1.3.0 -> v1.3.1-rc1 -> master

**Comment by bk201** [comment]
Thanks @FrankYang0529 and @ibrokethecloud, we'll close this for now it doesn't impact any feature

**Comment by ER-EPR** [comment]
> A workaround is to stop fleet-controller and rancher to make managed chart generation keep up with bundle and then start controllers again. For example:
> 
> ```
> kubectl scale deploy fleet-controller -n cattle-fleet-system --replicas=0
> kubectl scale deploy rancher -n cattle-system --replicas=0
> kubectl patch managedcharts.management.cattle.io harvester-crd -n fleet-local --type='json' -p='[{"op": "replace", "path": "/spec/paused", "value":true}]'
> kubectl patch managedcharts.management.cattle.io harvester-crd -n fleet-local --type='json' -p='[{"op": "replace", "path": "/spec/paused", "value":false}]'
> 
> kubectl scale deploy fleet-controller -n cattle-fleet-system --replicas=1
> kubectl scale deploy rancher -n cattle-system --replicas=1
> kubectl patch bundles.fleet.cattle.io mcc-harvester-crd -n fleet-local --type='json' -p='[{"op": "add", "path": "/spec/correctDrift", "value":{}}]'
> ```

Hi, @FrankYang0529  ! I follow your instruction but the mismatch doesn't go away, but gets weirder.
I noticed the rancher deployment replica. As soon as I set it to 0, it will come back as 3.
What should I do now if I still want to sync those charts? BTW, I upgraded from 1.2.2 to 1.3.1. And enabled rancher-vcluster addon. Will that be a problem?
Follow up: I also tried disable the vcluster or upgrade the rancher inside to 2.8.3, still not working.
Thanks very much!
![image](https://github.com/user-attachments/assets/fe7086f7-68e3-4717-9125-247f7504aa7b)

**Comment by ER-EPR** [comment]
I find out `kubectl scale deploy rancher -n cattle-system --replicas=0` needs to be executed twice to fully shut down rancher deployment. After that, those commands should do the trick. But be careful not to execute the patch multiple times as I did. In that way your will need to execute equal times of patch/add to the bundle and the managed charts, to get their generation to be equal.
