### ISSUE TITLE
[TASK] Bump Harvester component minor versions

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#5947]
**Context**

A harvester component in the previous minor release might be newer than the version in the current release.
For example, we have the image `rancher/harvester-network-controller:v0.3.7`  in Harvester v1.2.2, but `rancher/harvester-network-controller:v0.3.6` in Harvester v1.3-head.

If a user upgrade from Harvester v1.2.2 to v1.3.1, the component's semantic version will be downgraded.

**Task**
- Bump Harvester components' minor version x.y.z to x.y+1.z in v1.3.

Images tags:
|Done|   | v1.2.2  | v1.3-head  | Suggested new version | Owner |
|---|---|---|---|---|---|
| 🟢 | harvester-network-controller  |  v0.3.7 | v0.3.6  |  v0.4.0 | @mingshuoqiu  |
| 🟢 |  harvester-node-disk-manager | v0.5.5  | v0.6.3  |  | |
| 🟢 |  harvester-load-balancer |  v0.2.6 | v0.2.5  | v0.3.0 | @Yu-Jack   |
| 🟢 |  harvester-node-manager |  v0.1.10 | v0.2.1 |  | | 
| 🟢 |  (add-on) vm-import-controller | v0.1.8 | v0.1.8 | v0.3.0 | @ibrokethecloud |
| 🟢 | (add-on) pcidevices-controller | v0.2.7 | v0.3.2 | | |
| 🟢 | (add-on) rancher/harvester-eventrouter | v0.1.2 | v0.1.2 |v0.2.0 |  @w13915984028 |
| 🟢 | (add-on) seeder | 0.1.2 | 0.1.2 | 0.3.0 | @ibrokethecloud  |

Charts:
| Done |  | v1.2.2  | v1.3-head  | Suggested new version | Owner |
|---|---|---|---|---|---|
| 🟢 | harvester-network-controller  |  v0.3.3 | v0.3.3  |  v0.4.0 | @mingshuoqiu  |
| 🟢 | harvester-node-disk-manager | v0.5.0  | v0.6.0  |  | |
| 🟢 | harvester-load-balancer |  v0.2.0 | v0.2.0  | v0.3.0 |  @Yu-Jack |
|🟢 | harvester-node-manager |  v0.1.5 | v0.2.3 |  | | 
|  🟢| (add-on) vm-import-controller | v0.1.8 | v0.1.8 | v0.3.0 | @ibrokethecloud  |
| 🟢| (add-on) pcidevices-controller | v0.2.7 | v0.3.2 | | |
| 🟢| (add-on) rancher-logging | 103.0.0+up3.17.10 | 103.0.0+up3.17.10 | chart version unchanged, but eventrouter image tag is bumped to v0.2.0 | @w13915984028  |
|🟢 | (add-on) rancher-monitoring | 103.0.3+up45.31.1 | 103.0.3+up45.31.1 | | - |
| 🟢| (add-on) seeder | 0.1.1 | 0.1.1 | v0.3.0 | @ibrokethecloud  |

**Comment by Yu-Jack** [comment]
@bk201 I don't see there is v0.3.0 in https://github.com/harvester/load-balancer-harvester/releases, there is only v0.2.6.

**Comment by bk201** [comment]
@Yu-Jack yes, so we need to create a new version and a branch for 0.2.x

**Comment by w13915984028** [comment]
The image `rancher/harvester-eventrouter` will have a `v0.1.3` version after the GHA EIO ticket is done.

**Comment by bk201** [comment]
> The image `rancher/harvester-eventrouter` will have a `v0.1.3` version after the GHA EIO ticket is done.

@w13915984028 Please jump to v0.2.x. we want to have a different minor version between v1.2 and v1.3. And it works with the current drone flow, no need to wait for GHA ready.

**Comment by bk201** [comment]
Confirmed updates in v1.3 ISO

Images:
```
$ kubectl get pods --all-namespaces -o jsonpath="{.items[*].spec.containers[*].image}" |tr -s '[[:space:]]' '\n' |sort |uniq | grep -E "seeder|vm-import|load-balancer|harvester-network"
rancher/harvester-load-balancer:v0.3.0
rancher/harvester-load-balancer-webhook:v0.3.0
rancher/harvester-network-controller:v0.4.0
rancher/harvester-network-webhook:v0.4.0
rancher/harvester-seeder:v0.3.0
rancher/harvester-vm-import-controller:v0.3.0
```

Charts:
```
$ helm list -A  | grep -E 'seeder|vm-import'
harvester-seeder                           	harvester-system               	1       	2024-06-05 08:48:37.326344333 +0000 UTC	deployed	harvester-seeder-0.3.0                                                                           	v0.3.0
vm-import-controller                       	harvester-system               	1       	2024-06-05 08:48:29.36765968 +0000 UTC 	deployed	harvester-vm-import-controller-0.3.0                                                             	v0.3.0
```

**Comment by w13915984028** [comment]
Update of eventrouter:
(1) new container image:
https://github.com/harvester/eventrouter/releases/tag/v0.2.0

**master-head:**

(2) bump image to addon 
https://github.com/harvester/addons/pull/1

(3) build image list
https://github.com/harvester/harvester-installer/pull/752

(4) upgrade path
https://github.com/harvester/harvester/pull/5976

**v1.3**
(2) bump image to addon and image list
https://github.com/harvester/harvester-installer/pull/753

(3) upgrade path
https://github.com/harvester/harvester/pull/5976 -> wait mergify auto backport

All PRs are merged.

**Comment by albinsun** [comment]
Test OK on `v1.3.1-rc2` for following 3 cases
1. Fresh install
2. Upgrade from `1.2.2` -> enable addons
3. Enable addons -> Upgrade from `1.3.0`

Close as done.

## Environment
* **harvester-`v1.3.1-rc2`**
  * Profile: 2 nodes QEMU/KVM (8C/16G/500G)
  * ui-source: `Auto`


## Test Suite
### Fresh Install
1. Check images tags

|Done|   | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-network-controller  |  v0.3.7 | v0.3.6  |  v0.4.0 | :heavy_check_mark: `rancher/harvester-network-controller:v0.4.0` ![image](https://github.com/harvester/harvester/assets/2773781/7e54eaec-8f50-418a-9a80-669a91cc3a5f)|
| 🟢 |  harvester-node-disk-manager | v0.5.5  | v0.6.3  |  | :heavy_check_mark: `rancher/harvester-node-disk-manager:v0.6.3` ![image](https://github.com/harvester/harvester/assets/2773781/698d3467-72cb-4cc6-a9c3-9473a2f16db2)|
| 🟢 |  harvester-load-balancer |  v0.2.6 | v0.2.5  | v0.3.0 | :heavy_check_mark: `rancher/harvester-load-balancer:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/3dd058db-0f03-43c8-a38c-1841e3b28338)|
| 🟢 |  harvester-node-manager |  v0.1.10 | v0.2.1 |  | :heavy_check_mark: `rancher/harvester-node-manager:v0.2.1` ![image](https://github.com/harvester/harvester/assets/2773781/41f8292b-7789-47fa-9c73-4d2b244fbeb3)| 
| 🟢 |  (add-on) vm-import-controller | v0.1.8 | v0.1.8 | v0.3.0 | :heavy_check_mark: `rancher/harvester-vm-import-controller:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/fda403dd-8e13-4058-82ba-80b2c863a60a)|
| 🟢 | (add-on) pcidevices-controller | v0.2.7 | v0.3.2 | | :heavy_check_mark: `rancher/harvester-pcidevices:v0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/aab41632-0129-4e26-9b26-6f3288c28bd6)|
| 🟢 | (add-on) rancher/harvester-eventrouter | v0.1.2 | v0.1.2 |v0.2.0 | :heavy_check_mark: `rancher/harvester-eventrouter:v0.2.0` ![image](https://github.com/harvester/harvester/assets/2773781/2ae9fcb6-1c9f-4639-bf99-b8f2e4471357)|
| 🟢 | (add-on) seeder | 0.1.2 | 0.1.2 | 0.3.0 | :heavy_check_mark: `rancher/harvester-seeder:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/9a650961-6301-4a5d-ae24-d68b8d967f73)|


4. Check charts

| Done |  | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-node-disk-manager | v0.5.0  | v0.6.0  |  | :heavy_check_mark: `harvester-node-disk-manager-0.6.0` ![image](https://github.com/harvester/harvester/assets/2773781/fe2dae3d-bc01-4894-aa9b-1421c96d521a)|
|🟢 | harvester-node-manager |  v0.1.5 | v0.2.3 |  | :heavy_check_mark: `harvester-node-manager-0.2.3` ![image](https://github.com/harvester/harvester/assets/2773781/795a8ea7-9ca1-4e2a-8b23-c135b22a49a3)| 
|  🟢| (add-on) vm-import-controller | v0.1.8 | v0.1.8 | v0.3.0 | :heavy_check_mark: `rancher/harvester-vm-import-controller:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/925ccacd-227f-4a19-8e56-cab47797a55c) |
| 🟢| (add-on) pcidevices-controller | v0.2.7 | v0.3.2 | | :heavy_check_mark: `harvester-pcidevices-controller-0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/211feec2-da98-474d-a448-d44b6a081ee5)|
| 🟢| (add-on) rancher-logging | 103.0.0+up3.17.10 | 103.0.0+up3.17.10 |  | :heavy_check_mark: `rancher-logging-103.0.0+up3.17.10` ![image](https://github.com/harvester/harvester/assets/2773781/a158d23b-5d8b-46b9-913d-eff6aa99839d)|
|🟢 | (add-on) rancher-monitoring | 103.0.3+up45.31.1 | 103.0.3+up45.31.1 | | :heavy_check_mark: `rancher-monitoring-103.0.3+up45.31.1` ![image](https://github.com/harvester/harvester/assets/2773781/6bc6eacf-9bbc-42c3-965b-0f9b8c0fd84f)|
| 🟢| (add-on) seeder | 0.1.1 | 0.1.1 | v0.3.0 | :heavy_check_mark: `harvester-seeder-0.3.0`![image](https://github.com/harvester/harvester/assets/2773781/48338355-c9f1-44f3-b368-62b171eec0e7) |
 

### Upgrade `v1.2.2` -> `v1.3.1-rc2` (Enable addon after upgrade)
1. <details>
   <summary> Upgrade <code>v1.2.2</code> -> <code>v1.3.1-rc2</code>
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/dd4119fb-ca70-4ff9-b82d-53d164836871)   
   </details>


5. Check images tags

|Done|   | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-network-controller           | v0.3.7  | v0.3.6 | v0.4.0 | :heavy_check_mark:  `rancher/harvester-network-controller:v0.4.0` ![image](https://github.com/harvester/harvester/assets/2773781/bdcf2e2a-d634-4116-bee2-2ce3e72fc636) |
| 🟢 |  harvester-node-disk-manager           | v0.5.5  | v0.6.3 |        | :heavy_check_mark: `rancher/harvester-node-disk-manager:v0.6.3` ![image](https://github.com/harvester/harvester/assets/2773781/90304a49-7f4e-44ce-a7da-a7a5c2d97f75)|
| 🟢 |  harvester-load-balancer               | v0.2.6  | v0.2.5 | v0.3.0 | :heavy_check_mark: `rancher/harvester-load-balancer:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/3d829be6-24ef-416d-bf93-18a704a0cf66)|
| 🟢 |  harvester-node-manager                | v0.1.10 | v0.2.1 |        | :heavy_check_mark: `rancher/harvester-node-manager:v0.2.1` ![image](https://github.com/harvester/harvester/assets/2773781/8768be52-cb7e-4c6b-8faa-bb0fa97821d4)| 
| 🟢 |  (add-on) vm-import-controller         | v0.1.8  | v0.1.8 | v0.3.0 | :heavy_check_mark: `rancher/harvester-vm-import-controller:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/8bd9107a-d8a9-4c54-8f01-8f03f66a171f)|
| 🟢 | (add-on) pcidevices-controller         | v0.2.7  | v0.3.2 |        | :heavy_check_mark: `rancher/harvester-pcidevices:v0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/0497c4a4-56c3-4ac8-871e-ddb1ce0a0078)|
| 🟢 | (add-on) rancher/harvester-eventrouter | v0.1.2  | v0.1.2 | v0.2.0 | :heavy_check_mark: `rancher/harvester-eventrouter:v0.2.0` ![image](https://github.com/harvester/harvester/assets/2773781/6ae7c177-cd68-4275-9cc0-9da5bf92a5c8)|
| 🟢 | (add-on) seeder                        | 0.1.2   | 0.1.2  | 0.3.0  | :heavy_check_mark: `rancher/harvester-seeder:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/a1be3ba4-23fc-4a33-b036-c0a6ded2fafe)|


6. Check charts

| Done |  | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-node-disk-manager   | v0.5.0            | v0.6.0 |          | :heavy_check_mark: `harvester-node-disk-manager-0.6.0` ![image](https://github.com/harvester/harvester/assets/2773781/0966b4c6-c71a-4b4f-a2a2-e1095420f88d)|
|🟢 | harvester-node-manager         |  v0.1.5           | v0.2.3 |          | :heavy_check_mark: `harvester-node-manager-0.2.3` ![image](https://github.com/harvester/harvester/assets/2773781/e15734ff-2bc1-4c1e-951e-0b9aac2718b5)| 
|  🟢| (add-on) vm-import-controller | v0.1.8            | v0.1.8 | v0.3.0   | :heavy_check_mark: `harvester-vm-import-controller-0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/b01e82ee-983d-40cc-b5bf-275b5d09722d)|
| 🟢| (add-on) pcidevices-controller | v0.2.7            | v0.3.2 |          | :heavy_check_mark: `harvester-pcidevices-controller-0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/8286d718-a9f7-4316-abf2-a4bbda836639)|
| 🟢| (add-on) rancher-logging       | 103.0.0+up3.17.10 | 103.0.0+up3.17.10 |  | :heavy_check_mark: `rancher-logging-103.0.0+up3.17.10` ![image](https://github.com/harvester/harvester/assets/2773781/50aada80-1a1e-49c7-9d94-72f22df3e940)|
|🟢 | (add-on) rancher-monitoring    | 103.0.3+up45.31.1 | 103.0.3+up45.31.1 | | :heavy_check_mark: `rancher-monitoring-103.0.3+up45.31.1` ![image](https://github.com/harvester/harvester/assets/2773781/bcbdc522-21f8-44b1-8872-03a99a1a1580)|
| 🟢| (add-on) seeder                | 0.1.1             | 0.1.1             | v0.3.0 | :heavy_check_mark: `harvester-seeder-0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/58127bc3-ae61-4621-84d8-1490abeb4a0a)|


### Upgrade `v1.3.0` -> `v1.3.1-rc2` (Enable addon before upgrade)
1. <details>
   <summary> Enable Addons
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/7022832f-4bb4-463f-8a9e-13f3c20d5fa4)
   </details>

1. <details>
   <summary> Upgrade <code>v1.3.0</code> -> <code>v1.3.1-rc2</code>
   </summary>

   ![image](https://github.com/harvester/harvester/assets/2773781/e5fe6fd1-03af-42f8-a7cc-81e30cdc860f)
   </details>


1. Check images tags

|Done|   | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-network-controller           | v0.3.7  | v0.3.6 | v0.4.0 | :heavy_check_mark: `rancher/harvester-network-controller:v0.4.0` ![image](https://github.com/harvester/harvester/assets/2773781/ca9bc753-1634-4e7e-aa5b-bd7d7bc8cdd5)|
| 🟢 |  harvester-node-disk-manager           | v0.5.5  | v0.6.3 |        | :heavy_check_mark: `rancher/harvester-node-disk-manager:v0.6.3` ![image](https://github.com/harvester/harvester/assets/2773781/cb5896b1-81fd-497b-ad12-b4249092875d)|
| 🟢 |  harvester-load-balancer               | v0.2.6  | v0.2.5 | v0.3.0 | :heavy_check_mark: `rancher/harvester-load-balancer:v0.3.0`![image](https://github.com/harvester/harvester/assets/2773781/cbf147bc-659a-42e2-8e29-a4d071073146)|
| 🟢 |  harvester-node-manager                | v0.1.10 | v0.2.1 |        | :heavy_check_mark: `rancher/harvester-node-manager:v0.2.1` ![image](https://github.com/harvester/harvester/assets/2773781/505f8c21-7250-4306-9d04-fedb682b0499)| 
| 🟢 |  (add-on) vm-import-controller         | v0.1.8  | v0.1.8 | v0.3.0 | :heavy_check_mark: `rancher/harvester-vm-import-controller:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/3dda18ab-f8f8-4d1c-a190-3fc3b247385d)|
| 🟢 | (add-on) pcidevices-controller         | v0.2.7  | v0.3.2 |        | :heavy_check_mark: `rancher/harvester-pcidevices:v0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/010718f5-740f-4b3a-85e2-eea74a58648c)|
| 🟢 | (add-on) rancher/harvester-eventrouter | v0.1.2  | v0.1.2 | v0.2.0 | :heavy_check_mark: `rancher/harvester-eventrouter:v0.2.0` ![image](https://github.com/harvester/harvester/assets/2773781/a000e1e7-5413-4b03-af8d-f909f8320803)|
| 🟢 | (add-on) seeder                        | 0.1.2   | 0.1.2  | 0.3.0  | :heavy_check_mark: `rancher/harvester-seeder:v0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/778ffb9d-a775-4425-aed3-4d32a2c2d6a3) |


2. Check charts

| Done |  | v1.2.2  | v1.3-head  | Suggested new version | Check |
|---|---|---|---|---|---|
| 🟢 | harvester-node-disk-manager   | v0.5.0            | v0.6.0 |          | :heavy_check_mark: `harvester-node-disk-manager-0.6.0` ![image](https://github.com/harvester/harvester/assets/2773781/1135e6eb-34e5-47b7-99b2-c2050c1fe315)|
|🟢 | harvester-node-manager         |  v0.1.5           | v0.2.3 |          | :heavy_check_mark: `harvester-node-manager-0.2.3` ![image](https://github.com/harvester/harvester/assets/2773781/17eebd56-31da-4561-bea5-178ef9a3a6a4)| 
|  🟢| (add-on) vm-import-controller | v0.1.8            | v0.1.8 | v0.3.0   | :heavy_check_mark: `harvester-vm-import-controller-0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/7d3356a0-c11a-43cb-bc3d-6d7ff238dd24)|
| 🟢| (add-on) pcidevices-controller | v0.2.7            | v0.3.2 |          | :heavy_check_mark: `harvester-pcidevices-controller-0.3.2` ![image](https://github.com/harvester/harvester/assets/2773781/0144930a-b14a-4a8b-b2d6-786c1f559b30)|
| 🟢| (add-on) rancher-logging       | 103.0.0+up3.17.10 | 103.0.0+up3.17.10 |  | :heavy_check_mark: `rancher-logging-103.0.0+up3.17.10` ![image](https://github.com/harvester/harvester/assets/2773781/1d9051cc-1ea2-4670-bda4-9e1182a3c1e7)|
|🟢 | (add-on) rancher-monitoring    | 103.0.3+up45.31.1 | 103.0.3+up45.31.1 | | :heavy_check_mark: `rancher-monitoring-103.0.3+up45.31.1` ![image](https://github.com/harvester/harvester/assets/2773781/dd6cb5a1-a841-441c-abb5-f7ffc61d0f85)|
| 🟢| (add-on) seeder                | 0.1.1             | 0.1.1             | v0.3.0 | :heavy_check_mark: `harvester-seeder-0.3.0` ![image](https://github.com/harvester/harvester/assets/2773781/2c09abd2-717a-4ec7-b0c8-622f7bdef1b2)|
