### ISSUE TITLE
[DOC] Missing old version APIs documentation

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#5948]
**Is your doc request related to a problem? Please describe or add related issue ID.**

Although we have multiple harvester version options in documentation, but we only have v1.3 and dev APIs documentation. When we click v1.1 harvester documentation, then click API, it'll be redirected  v1.3 APIs documentation. In other words, I can't see v1.1 APIs documentation.

**Describe the solution you'd like**

Do we need to add it back?

The other thing is that our openapi generator follows our harvester/harvester repo. If we fix some errors of openapi generator in new release version, we can't apply it on our old release version unless we backport. But, it seems weird that only backport those fixes for fixing openapi generator. Maybe we could have another repo only for openapi generator?

It's a open question here, welcome any ideas.

**Comment by jillian-maroket** [comment]
@innobead I am not familiar with how exactly the API documentation is generated. What I know is from [this PR](https://github.com/harvester/docs/pull/545), which @m-ildefons created.

**Comment by m-ildefons** [comment]
I'll check this one out. I'm sure it's a fairly small error in the docusaurus config somewhere.

**Comment by m-ildefons** [comment]
The API docs for the old versions is _there_ (e.g. https://docs.harvesterhci.io/v1.2/api/create-namespaced-virtual-machine-backup/) but what's missing is a link or a menu that leads to it. Somehow the version-change menu doesn't work for the API docs of older versions, but it does work for v1.4/dev and v1.3. There also doesn't seem to be a landing page/category index for those versions.
