### ISSUE TITLE
[ENHANCEMENT] improve the migration stability of downstream cluster

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#5949]
**Is your enhancement related to a problem? Please describe.**
Sometimes, we will see some weird situations like multiple `volume attachment`, `longhorn-engine`, or volume migration hang.
Seems it is related to the downstream cluster workload (volume) migration.

This issue will improve the stability of downstream cluster workload (volume) migration.

**Describe the solution you'd like**
Make sure how the Longhorn expects the volume status, and we should improve it with the Harvester CSI driver

**Describe alternatives you've considered**

**Additional context**

**Comment by WebberHuang1118** [comment]
I found a set of steps to make the guest cluster workload (volume) have live migration on the LH side:
- Create a two-node Harvester cluster
- Create a two-node guest cluster (make sure the two node VMs are on different Harvester nodes)
  - First VM with the label `choose:vm0`
  - Second VM with the label `choose:vm1`
- Apply a PVC on the guest cluster
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: my-pvc
  spec:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi
  ```
- Apply deployment on the guest cluster
  ```
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-deployment
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: myapp
    template:
      metadata:
        labels:
          app: myapp
      spec:
        nodeSelector:
          choose: vm0
        containers:
        - name: myapp
          image: nginx:latest
          ports:
          - containerPort: 80
          volumeMounts:
          - mountPath: "/usr/share/nginx/html"
            name: my-storage
        volumes:
        - name: my-storage
          persistentVolumeClaim:
            claimName: my-pvc
  ```
- After the deployment is created successfully, change its node selector to another node
  - This is going to trigger workload migration 

PVC `my-pvc` is bounded to PV `pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb` on the guest cluster, and PVC `pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb` is bounded to PV `pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e` on the Harvester

From the Harvester-CSI log in the guest cluster, we could find the volume `pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb` had `ControllerUnpublishVolume()` first, and went through `ControllerPublishVolume()` and `NodePublishVolume()` 
```
harvester-csi-driver-lmwhq:harvester-csi-driver time="2024-06-14T08:24:56Z" level=info msg="ControllerServer ControllerUnpublishVolume req: volume_id:\"pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb\" node_id:\"rke2-local-pool1-2e35e72c-6h6fn\" "

harvester-csi-driver-lmwhq:harvester-csi-driver time="2024-06-14T08:24:57Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb\" node_id:\"rke2-local-pool1-2e35e72c-4rjqf\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1718333177365-8081-driver.harvesterhci.io\" > "

harvester-csi-driver-lmwhq:harvester-csi-driver time="2024-06-14T08:24:59Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb\" target_path:\"/var/lib/kubelet/pods/4d53f294-eddf-4bb6-8ae2-adb72ad137c2/volumes/kubernetes.io~csi/pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"csi.storage.k8s.io/ephemeral\" value:\"false\" > volume_context:<key:\"csi.storage.k8s.io/pod.name\" value:\"my-deployment-68ffb5fb77-rr6k2\" > volume_context:<key:\"csi.storage.k8s.io/pod.namespace\" value:\"default\" > volume_context:<key:\"csi.storage.k8s.io/pod.uid\" value:\"4d53f294-eddf-4bb6-8ae2-adb72ad137c2\" > volume_context:<key:\"csi.storage.k8s.io/serviceAccount.name\" value:\"default\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1718333177365-8081-driver.harvesterhci.io\" > "

harvester-csi-driver-lmwhq:harvester-csi-driver time="2024-06-14T08:24:59Z" level=error msg="GRPC error: rpc error: code = Aborted desc = The hot-plug volume pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb is not ready"

.....

harvester-csi-driver-lmwhq:harvester-csi-driver time="2024-06-14T08:25:15Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb\" target_path:\"/var/lib/kubelet/pods/4d53f294-eddf-4bb6-8ae2-adb72ad137c2/volumes/kubernetes.io~csi/pvc-0020bd67-e8e0-4f6b-9488-ff48cef5dceb/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"csi.storage.k8s.io/ephemeral\" value:\"false\" > volume_context:<key:\"csi.storage.k8s.io/pod.name\" value:\"my-deployment-68ffb5fb77-rr6k2\" > volume_context:<key:\"csi.storage.k8s.io/pod.namespace\" value:\"default\" > volume_context:<key:\"csi.storage.k8s.io/pod.uid\" value:\"4d53f294-eddf-4bb6-8ae2-adb72ad137c2\" > volume_context:<key:\"csi.storage.k8s.io/serviceAccount.name\" value:\"default\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1718333177365-8081-driver.harvesterhci.io\" > "
```

From the Longhorn CSI log, we could find the volume `pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e` received `ControllerPublishVolume()` for a new attachment and `NodeUnpublishVolume()` for detaching an old attachment at the same time, then it brought the live migration for the hotplug volume, which should not happen in Harvester-CSI design (hotplug volume in the guest cluster in RWO)
```
longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:24:57Z" level=info msg="ControllerPublishVolume: req: {\"node_id\":\"harvester-node-1\",\"volume_capability\":{\"AccessType\":{\"Block\":{}},\"access_mode\":{\"mode\":5}},\"volume_context\":{\"migratable\":\"true\",\"numberOfReplicas\":\"2\",\"share\":\"true\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1718333702909-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\"}"

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:24:57Z" level=info msg="NodeUnpublishVolume: req: {\"target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e/cf33c1a4-17b1-4d3f-a449-bec8422c8a5b\",\"volume_id\":\"pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\"}"

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:24:58Z" level=info msg="NodeUnstageVolume: volume pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e unmounted from node path /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e"

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:25:01Z" level=error msg="ControllerUnpublishVolume: err: rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to detach volume pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e: migration is not ready yet, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e?action=detach]"
longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:25:01Z" level=debug msg="Polling volume pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e state for volume published at 2024-06-14 08:25:01.558242963 +0000 UTC m=+69562.579481013"

............................

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:25:09Z" level=info msg="ControllerPublishVolume: volume pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e with accessMode rwx published to harvester-node-1"

longhorn-csi-plugin-6bdbl:longhorn-csi-plugin time="2024-06-14T08:25:10Z" level=info msg="NodeStageVolume: req: {\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\",\"volume_capability\":{\"AccessType\":{\"Block\":{}},\"access_mode\":{\"mode\":5}},\"volume_context\":{\"migratable\":\"true\",\"numberOfReplicas\":\"2\",\"share\":\"true\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1718333702909-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\"}"

longhorn-csi-plugin-6bdbl:longhorn-csi-plugin time="2024-06-14T08:25:10Z" level=info msg="NodePublishVolume: req: {\"staging_target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/staging/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\",\"target_path\":\"/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e/7f3dcf3b-01a7-42c4-8e69-c6c82644f1db\",\"volume_capability\":{\"AccessType\":{\"Block\":{}},\"access_mode\":{\"mode\":5}},\"volume_context\":{\"csi.storage.k8s.io/ephemeral\":\"false\",\"csi.storage.k8s.io/pod.name\":\"hp-volume-kzd44\",\"csi.storage.k8s.io/pod.namespace\":\"default\",\"csi.storage.k8s.io/pod.uid\":\"7f3dcf3b-01a7-42c4-8e69-c6c82644f1db\",\"csi.storage.k8s.io/serviceAccount.name\":\"default\",\"migratable\":\"true\",\"numberOfReplicas\":\"2\",\"share\":\"true\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1718333702909-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\"}"

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:25:11Z" level=info msg="ControllerUnpublishVolume: req: {\"node_id\":\"harvester-node-0\",\"volume_id\":\"pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e\"}"

longhorn-csi-plugin-k96xg:longhorn-csi-plugin time="2024-06-14T08:25:13Z" level=debug msg="Volume pvc-b28e7e3f-b866-43f2-b321-ab97fcd8377e unpublished from harvester-node-0"
```

IMHO, this is caused by the [Harvester CSI driver not checking the VM and LH volume status in ControlUnPublishVolume](https://github.com/harvester/harvester-csi-driver/blob/84e7a15b8d2c41cb4c2d06600ab2768b46f4bc8c/pkg/csi/controller_server.go#L309-L317), and the issue a new attachment even there is ongoing volume detachment on Longhorn side. WDYT? @Vicente-Cheng 

Thanks

**Comment by Vicente-Cheng** [comment]
Hi @WebberHuang1118,
Yeah, I addressed this issue and opened a PR for the enhancement.
https://github.com/harvester/harvester-csi-driver/pull/39/commits/4f9fda21679b159c34d1d8ba4caddc9e92420dc8

I am going back to this issue to give the whole flow so we can get more perspective from the Longhorn side.

**Comment by w13915984028** [comment]
Is JIRA ticket 8570 also caused by this?

**Comment by Vicente-Cheng** [comment]
I am still investigating but looks related to https://github.com/harvester/harvester/issues/5951.

**Comment by Vicente-Cheng** [comment]
There is the current flow when volume migration on the guest cluster.
![harvester-csi-driver](https://github.com/harvester/harvester/assets/1615081/588e4640-da57-4897-8907-014ef02d2e1d)


The main issue happened in steps 2 to 4.
Currently, the source Harvester CSI driver needs to check the controllerUnpublish result.
Then, the target Harvester CSI driver will try to do the controller publish.

The above behavior would trigger the host volume to migrate to another host. (Means the Longhorn volume migration involved here)

This is not the VM migration, just the volume migration from one VM to another VM. We could not rely on the libvirt/qemu mechanism to ensure the IO would be redirected to the new VM.
This means we will see the shot time period for which two VMs are attached to the same volume.
That would cause some data consistency issues.

So we at least need to ensure the volume is detached from the source VM, then the controllerUnpublish can return a successful response.

WDYT for that?  cc @WebberHuang1118, @ejweber, @bk201

**Comment by WebberHuang1118** [comment]
I agree, and I'm checking PR https://github.com/harvester/harvester-csi-driver/pull/39 which seems to address this issue. 

I will check it also, thanks.

**Comment by albinsun** [comment]
Test FAIL, the 1st round migration looks fine but hit error `Multi-Attach error for volume` when we tried to add more volumes in the 2nd round.
From `htop`, the node is not over-loading, not like a performance issue.

Please help to check, thank you.


## Environment
* `harvester-v1.4.0-rc2`
  * Profile: 2 nodes AMD64 Bare-metal
  * ui-source: `Auto`
* `rancher-v2.8.5`
  * Profile: Docker on single node AMD64 Bare-metal
* Guest Cluster
  * Profile: 2 nodes v1.28.13+rke2r1 (4C/8G)
  * Image: _jammy-server-cloudimg-amd64.img_

## Prerequisite
1. <details>
   <summary> Import Harvester to Rancher
   </summary>

   ![image](https://github.com/user-attachments/assets/93697e9c-7d18-477b-aa50-926e89442dd3)
   </details>

1. <details>
   <summary> Create a 2 nodes RKE2 cluster (Each one locates on different node)
   </summary>

   ![image](https://github.com/user-attachments/assets/1cd690bd-248b-4e5a-b169-a3e0b0e206da)
   </details>

1. <details>
   <summary> Upgrade <i>harvester-csi-driver</i> to <code>dev-v2.8</code>
   </summary>

   * Add `dev-v2.8` chart repo
     ![image](https://github.com/user-attachments/assets/6d491ba4-3192-4723-8222-adc8979a445f)
   * Upgrade _harvester-csi-driver_ to `103.0.3+up0.1.20`
     ![image](https://github.com/user-attachments/assets/b8899059-1ad9-4c6c-8941-699587c6d2a4)
   </details>




## Test Case
### Phase 1
1. <details>
   <summary> :green_circle: Deploy a Nginx with 20 PVCs
   </summary>

   * Deployment
     ![image](https://github.com/user-attachments/assets/40e62516-07b3-4fc5-a834-c6226a183269)
   * PVCs
     ![image](https://github.com/user-attachments/assets/cb5d2c69-095d-43b2-9ceb-c9055e55b0bc)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/24f0dd9f-545c-491a-b9b8-972a4f104326)
   </details>

1. <details>
   <summary> :green_circle: Cordon node which Nginx is running on and delete Nginx pod 
   </summary>

   * Cordon
     ![image](https://github.com/user-attachments/assets/be548b60-4769-4fc6-80b2-d04231b95bec)
   * Delete Nginx pod
     ![image](https://github.com/user-attachments/assets/f22e70cc-75e5-41b6-bf11-ba475551a40f)
   </details>

1. <details>
   <summary> :green_circle: Nginx pod should be launch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/98df9ce4-856d-4c1f-8196-54766c561e28)
   </details>


### Phase 2
1. <details>
   <summary> :green_circle: Check 2 RKE2 nodes are <code>Active</code> (Uncordon node if need)
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3c1ea401-b312-4992-968a-bd2dd265680c)
   </details>

1. <details open>
   <summary> :red_circle: Attach 10 more new PVCs to Nginx pod
   </summary>

   :warning: `Multi-Attach error for volume "pvc-f6446b4e-a025-44a3-835f-412e91347aef" Volume is already used by pod(s) mynginx-949fdb86-5xs9x`
   * Deployment
     ![image](https://github.com/user-attachments/assets/a2d22d4f-53a0-4fc8-8ef8-65cb231390a5)
   * Pod
     ![image](https://github.com/user-attachments/assets/85aac1ff-2624-4a7f-a213-ee5cceccdf1f)
   </details>


1. <details>
   <summary> :white_circle: Cordon node  and delete Nginx pod 
   </summary>
   </details>

1. <details>
   <summary> :white_circle: Nginx pod should be launch on the other node with all PVC migrated
   </summary>
   </details>


## Logs
* Support bundle: [supportbundle_BatchAttachPVCs_2024-10-17T14-22-48Z.zip](https://github.com/user-attachments/files/17414009/supportbundle_BatchAttachPVCs_2024-10-17T14-22-48Z.zip)
* RKE rancher2_logs: 
  * Running pod: [rke2-ravens-pool1-f1acb2cd-59jct-2024-10-17_14_26_55.tar.gz](https://github.com/user-attachments/files/17414041/rke2-ravens-pool1-f1acb2cd-59jct-2024-10-17_14_26_55.tar.gz)
  * Launching pod: [rke2-ravens-pool1-f1acb2cd-qnjbt-2024-10-17_14_24_20.tar.gz](https://github.com/user-attachments/files/17414010/rke2-ravens-pool1-f1acb2cd-qnjbt-2024-10-17_14_24_20.tar.gz)

**Comment by albinsun** [comment]
Test PASS with all 5 rounds up to 50 PVCs, works well and stable. Close as done.

## Environment
* `harvester-v1.4.0-rc2`
  * Profile: 2 nodes AMD64 Bare-metal
  * ui-source: `Auto`
* `rancher-v2.8.5`
  * Profile: Docker on single node AMD64 Bare-metal
* Guest Cluster
  * Profile: 2 nodes v1.28.13+rke2r1 (4C/16G)
  * Image: _jammy-server-cloudimg-amd64.img_

## Prerequisite
1. <details>
   <summary> Import Harvester to Rancher
   </summary>

   ![image](https://github.com/user-attachments/assets/93697e9c-7d18-477b-aa50-926e89442dd3)
   </details>

1. <details>
   <summary> Create a 2 nodes RKE2 cluster (Each one locates on different node)
   </summary>

   * Rancher
     ![image](https://github.com/user-attachments/assets/63666c04-13c5-4e3d-8590-a6e218e3fa8f)
   * Harvester
     ![image](https://github.com/user-attachments/assets/b4e8ae7e-0e8e-43be-af92-9557fbc1b54a)
   </details>

1. <details>
   <summary> Upgrade <i>harvester-csi-driver</i> to <code>dev-v2.8</code>
   </summary>

   * Add `dev-v2.8` chart repo
     ![image](https://github.com/user-attachments/assets/1d4725e4-f9da-4d5d-92d6-025180b2fd69)
   * Upgrade _harvester-csi-driver_ to `103.0.3+up0.1.20`
     ![image](https://github.com/user-attachments/assets/9820461c-f33d-4918-ac51-1dd8386bd701)
   </details>


## Test Case
### :green_circle: Phase 1 (10 PVCs)
1. <details>
   <summary> Deploy a Nginx with 10 PVCs
   </summary>

   ![image](https://github.com/user-attachments/assets/29b681ef-eaf8-4fb2-823e-5bf837eb994c)
   </details>

1. <details>
   <summary> Cordon the node which Nginx is running on 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/1ff79abe-1c5d-4b90-9609-d42316a1a3d8)
   </details>

1. <details>
   <summary> Delete Nginx pod and it should be relaunch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/cb2cd3cd-3c6f-4f8e-8246-7284ed7a328e)
   </details>


### :green_circle: Phase 2 (20 PVCs)
1. <details>
   <summary> Uncordon, check both nodes are <code>Active</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8ee1fd6d-47a3-46e8-bb39-b944efb42bcd)
   </details>

1. <details>
   <summary> Attach 10 new PVCs to Nginx pod
   </summary>
   
   1. Set `replicas=0`
      ![image](https://github.com/user-attachments/assets/fbdcf4ef-449c-44df-ab3b-f2dcdfcd0256)
   2. Add new PVCs and set `replicas=1`
      ![image](https://github.com/user-attachments/assets/69f193e1-6fc3-487f-90c0-86592efd7e87)
   </details>

1. <details>
   <summary> Cordon the node which Nginx is running on
   </summary>
   
   ![image](https://github.com/user-attachments/assets/7b55ef2d-e295-46b1-b2f0-e7feba49bd39)
   </details>

1. <details>
   <summary> Delete Nginx pod and it should be relaunch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/37f93572-4605-428d-bf99-1d52123e94b7)
   * Longhorn
     ![image](https://github.com/user-attachments/assets/8ed1e6af-480a-4c82-8eb3-72202c0c1acd)
   </details>


### :green_circle: Phase 3 (30 PVCs)
1. <details>
   <summary> Uncordon, check both nodes are <code>Active</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/0c6ab8d3-1bec-48bb-a026-f1c38a1d6c68)
   </details>

1. <details>
   <summary> Attach 10 new PVCs to Nginx pod
   </summary>

   1. Set `replicas=0`
      ![image](https://github.com/user-attachments/assets/0af1fe4a-3897-422c-b32d-0d92b08444c0)
   2. Add new PVCs and set `replicas=1`
      ![image](https://github.com/user-attachments/assets/53100d2a-a03d-4684-a5bb-852a8f5559c2)
      ![image](https://github.com/user-attachments/assets/9879f97e-e829-4f58-bdf6-c30c28aba995)
   </details>

1. <details>
   <summary> Cordon the node which Nginx is running on 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/df8286a7-c52c-44ba-8ea8-e1e2e0e7b436)
   </details>

1. <details>
   <summary> Delete Nginx pod and it should be relaunch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/87847b0c-a1a7-4e7e-985e-2738af60871e)
   
   ![image](https://github.com/user-attachments/assets/a6398b1e-8a49-4470-befc-d83a557e59e4)
   </details>


### :green_circle: Phase 4 (40 PVCs)
1. <details>
   <summary> Uncordon, check both nodes are <code>Active</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/0cc24e1e-22d9-46a3-8e45-17e6fcc9ec89)
   </details>

1. <details>
   <summary> Attach 10 new PVCs to Nginx pod
   </summary>

   1. Set `replicas=0`
      ![image](https://github.com/user-attachments/assets/17cbb8ca-538d-46dd-b09e-f52a1c97de97)
   2. Add new PVCs and set `replicas=1`
      ![image](https://github.com/user-attachments/assets/86516ca1-fedc-4976-9041-9fdf966349f4)
      ![image](https://github.com/user-attachments/assets/b57646ef-0e3c-4e03-8074-86cb718f036c)
      ![image](https://github.com/user-attachments/assets/b0054b66-450a-44e4-b5a1-11094371dd30)

   </details>

1. <details>
   <summary> Cordon the node which Nginx is running on
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4ea19987-e44f-458d-a14a-ecfcdaebcdcd)
   </details>

1. <details>
   <summary> Delete Nginx pod and it should be relaunch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/14d083c7-f147-4464-b271-5e917f7bc667)
   ![image](https://github.com/user-attachments/assets/98dccd7a-54e9-40fd-b7df-a58e770abd8e)
   ![image](https://github.com/user-attachments/assets/f259682d-2dca-4a1a-9a4b-6b4bf0c90f53)
   </details>


### :green_circle: Phase 5 (50 PVCs)
1. <details>
   <summary> Uncordon, check both nodes are <code>Active</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/e7f6206e-2266-482f-8a33-70adf516fc56)
   </details>

1. <details>
   <summary> Attach 10 new PVCs to Nginx pod
   </summary>

   1. Set `replicas=0`
      ![image](https://github.com/user-attachments/assets/e5fb1a15-90b0-4216-ada5-1d54d08d4ec5)
   2. Add new PVCs and set `replicas=1`
      ![image](https://github.com/user-attachments/assets/58c82676-750d-4e4e-b367-e07acb0f71cc)
      ![image](https://github.com/user-attachments/assets/b81366b3-5091-45e9-86c7-9fbcc30c972b)
      ![image](https://github.com/user-attachments/assets/e001b95d-f068-4c94-8909-b3295b0766c3)
   </details>


1. <details>
   <summary> Cordon the node which Nginx is running on 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/989c2a04-de7b-4308-96c0-e12ca8c7821b)
   </details>

1. <details>
   <summary> Delete Nginx pod and it should be relaunch on the other node with all PVC migrated
   </summary>
   
   ![image](https://github.com/user-attachments/assets/9b82ec28-cd30-4ad2-91ec-d02831754cee)
   ![image](https://github.com/user-attachments/assets/b59a15b5-56dd-401c-becd-0c432eec0f6d)
   ![image](https://github.com/user-attachments/assets/c2a2b8cb-a961-49b0-a972-10746ee4d03a)
   </details>
