### ISSUE TITLE
[BUG] Routing issues on server with 2 network interfaces and only one in actual use

### ISSUE THREAD

**Issue by pgonin** [harvester/harvester#595]
**Describe the bug**
I am deploying Harvester on bare metal servers that have multiple interfaces but only one is actually cabled.
Deployment of node with installer (remote access over serial console/lan) is successful.
I choose the active interface during the setup (eth0 in most cases)
When the server installation is finished and after the reboot I can only access it with the console.

Default route is set to eth1, which is useless
```
# route
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
default         *               0.0.0.0         U     0      0        0 eth1
10.--.--.21      10.--.--.254    255.255.255.255 UGH   0      0        0 eth0
[...]
127.0.0.0       *               255.0.0.0       U     0      0        0 lo
169.254.0.0     *               255.255.0.0     U     0      0        0 eth1
```

**Environment:**
 - Harvester ISO version: master-c5a265d5-head
 - Installation Mode: ISO
 - Underlying Infrastructure (Baremetal with HP DL360 G9):

**Workaround:**
I manage to manually fix it with the following steps:

edit /etc/connman/main.conf
blacklist eth1
```
[General]
NetworkInterfaceBlacklist=veth,eth1
...
```
```
rc-service connman restart
connmanctl services
*AO Wired                ethernet_xxx_cable

connmanctl config ethernet_xxx_cable --ipv4 dhcp
```

**Comment by yaocw2020** [comment]
Does it work after you block eth1?

**Comment by guangbochen** [comment]
as per above suggestion, @pgonin plese let us know if it is ok to close this issue, thanks

**Comment by pgonin** [comment]
Yes, once eth1 is in the NetworkInterfaceBlacklist the problems are gone. But that's a tedious manual work to perform over serial console after installation is finished

**Comment by pgonin** [comment]
Apparently if I pick the actual system name (as it is in dhcp), the issue appears less often (but that's not an observation over many installation attempts, it might just be luck)

**Comment by yaocw2020** [comment]
@pgonin Connman will choose one physical NIC as the default route interface. If the NIC is invalid, it's better to block it.

**Comment by pgonin** [comment]
I get that. And I do have a workaround. 
Maybe It needs to be changed to a Feature Request to have the ability to configure NetworkInterfaceBlacklist during installation somehow

**Comment by yaocw2020** [comment]
> I get that. And I do have a workaround.
> Maybe It needs to be changed to a Feature Request to have the ability to configure NetworkInterfaceBlacklist during installation somehow

We are considering to replace K3OS. May connman will replaced at the same time. We will take this scenario into consideration and you will be informed if it solved.

**Comment by yaocw2020** [comment]
https://github.com/rancher/harvester/issues/581

**Comment by pgonin** [comment]
Fair enough. Thanks

**Comment by yaocw2020** [comment]
@pgonin I am glad to inform you that we have changed the OS for the Harvester and use wicked to manage the network. The default route is set on the `harvester-mgmt`, a bond device created during the installation.
```
# ip r
default via 172.16.0.1 dev harvester-mgmt proto dhcp
```

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head.

- Tested with 2 NICs ON VM with KVM/libvirt
- One NIC active
- One NIC inactive
- Was able to access Harvester and ping an internet address from node
