### ISSUE TITLE
[BUG] No configuration option in the sidebar for logging

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5959]
**Describe the bug**

There is not an option for configuration in the sidebar for logging.
**To Reproduce**
1. Install a new cluster
2. Enable the logging addon
3. Wait for it to deploy
4. Navigate to the logging section of the sidebar

**Expected behavior**

There should be a configuration option at the top of the sidebar

**Support bundle**

[supportbundle_3dd936ab-eb61-446e-bc9c-cd996a10b0a3_2024-06-04T22-44-14Z.zip](https://github.com/user-attachments/files/15571190/supportbundle_3dd936ab-eb61-446e-bc9c-cd996a10b0a3_2024-06-04T22-44-14Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 3 node libvirt ipxe-examples virtualized environment

**Additional context**

It's worth noting that you can still edit the config in the addons section by clicking the triple dot and selecting edit config.

![Screenshot_20240604_154735](https://github.com/harvester/harvester/assets/83787952/a465da09-9508-4035-ba0d-6b9378c5d511)
![Screenshot_20240604_154318](https://github.com/harvester/harvester/assets/83787952/cb3f76d8-19ca-472c-b883-2e4e4165bc71)
![Screenshot_20240604_154248](https://github.com/harvester/harvester/assets/83787952/63bed3b7-41f1-4fc1-82c6-3965641970ea)
![Screenshot_20240604_153829](https://github.com/harvester/harvester/assets/83787952/02b3f88d-c52f-4615-a4f9-9456fd445143)

When this test was originally wrote it was working

![191697822-6bc0d7b8-2c56-42e0-805a-408c1ef19845](https://github.com/harvester/harvester/assets/83787952/4270bd30-daff-4a6e-af09-28eba46dd912)

**Comment by a110605** [comment]
The monitoring & Logging -> Logging -> Configuration navgation item (`LOGGING_CONFIGURATION`) was added in this [commit](https://github.com/a110605/harvester-dashboard/commit/6edcaaa943effbe4c78c72c0c5dabd0e51c0b19d) , but later remove from this [commit](https://github.com/harvester/dashboard/commit/eff21bc020e4a5f1e242111f9a6726d854b42a99).  

At that time, the logging configure page was still there. ([QA verification result](https://github.com/harvester/harvester/issues/2646#issuecomment-1254700612))
But later removed from this PR https://github.com/harvester/dashboard/pull/654

cc @torchiaf @bk201

**Comment by torchiaf** [comment]
Should we re-introduce the Configuration tab @bk201 ?

**Comment by noahgildersleeve** [comment]
We can also update the test, if this is the desired functionality.

**Comment by noahgildersleeve** [comment]
Based on input from @bk201 this is working as expected. I'm going to update the tests in a PR and close this as `working as intended`.
