### ISSUE TITLE
[BUG] 1.2.1 to 1.2.2 failed because node did not reboot

### ISSUE THREAD

**Issue by Felrenzler** [harvester/harvester#5962]
During an upgrade one node failed to reboot in a 4 node cluster.  Eventually at some point the upgrade vm quit working and status on the upgrade still shows for server3 "Waiting on reboot".

On rebooting the server I noticed that the hard drives were re-ordered, but the /dev/disk/by-label seems adapted to it being sdb vs it's original sda, but it pauses 5 minues and drops to maintenance prompt.  Going to the failback propmpt on grub everything boots fine, it just gets stuck on a start job that's essentially angry at the drives being reordered.  On failback that boot disk is SDA.

Stuck on "A start job is running for /dev/disk/by-label" dies at 5 minute mark.

Unsure how to proceed at this point.  I have 2 nodes sucessfully upgraded, and the 3rd stuck, 4th waiting with images preloaded.

**Comment by Felrenzler** [comment]
![srv03 hang](https://github.com/harvester/harvester/assets/1921014/4cc6c8cf-d74c-481f-918f-002b8eccb3e5)

**Comment by Felrenzler** [comment]
![srv03 hang rdsosoutput](https://github.com/harvester/harvester/assets/1921014/6eb1800c-aaf8-4010-9b7d-5489fb59ba13)

Relevant error in the rdsosoutput.

**Comment by bk201** [comment]
Disk reorder is fine because the OS mount partitions by labels, any chance the disk is offline? If the boot eventually drops to an emergent shell, can you provide the output of `lsblk`?

**Comment by Felrenzler** [comment]
I will later today, but no those disks can be manually mounted just fine when in the emergency shell.

**Comment by Felrenzler** [comment]
Does anyone know what that first start job is trying to do?

**Comment by Felrenzler** [comment]
![srv03 blkid](https://github.com/harvester/harvester/assets/1921014/8b3685bc-6f39-4c90-acc4-5f919d6506d7)


lsblk/blkid attached.

**Comment by bk201** [comment]
@Vicente-Cheng @tserong any idea about this? the labels look good

**Comment by Felrenzler** [comment]
I can manually mount those disks, and iDrac shows them as being fine so that's what's really odd about this.  One other odd thing is it's showing an avocent KVM being attached that's not attached anymore.  Are those 64M images hard locked to the HW state?

**Comment by tserong** [comment]
Can you please provide a copy of `/etc/fstab` from the broken environment?

The reason I'm asking is that the system unit name is weird. Note how it says `A start job is running for /dev/disk/by-label (3min 38s / 5min)` then later `dev-disk-by\x2dlabel.device: Job dev-disk-by\x2dlabel.device/start timed out.` AFAIK that's not a valid unit name. It shouldn't be just `/dev/disk/by-label`, it should be `/dev/disk/by-label/SOME_ACTUAL_DEVICE` and `dev-disk-by\x2dlabel-SOME_ACTUAL_DEVICE.device` (where SOME_ACTUAL_DEVICE is of course replaced by an actual valid label). So I'm wondering if `/etc/fstab` is somehow messed up, or missing labels, which in turn may result in that bogus unit trying to start.

**Comment by Felrenzler** [comment]
Oh it's empty as the devils soul.

**Comment by tserong** [comment]
> Oh it's empty as the devils soul.

Interesting. AIUI `/etc/fstab` should itself be automatically generated very early by elemental. Is is possible for you to paste or upload a complete copy of `/run/initramfs/rdsosreport.txt`?
