### ISSUE TITLE
[BUG] Failed to provision RKE2 guest cluster in Rancher with OpenSUSE image

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#5965]
**Describe the bug**

When we tried to provision the v1.27 (28) RKE2 guest cluster in Rancher v2.8.2 to Harvester `v1.3.1-rc1` with **opensuse-leap-15.4.x86_64-nocloud.qcow2** image.

The RKE2 provisioning process would stuck with `error applying plan` failure message

  ![image](https://github.com/harvester/harvester/assets/29251855/32fe723f-7f5b-4b47-a093-53d8befb9e10)
  ![image](https://github.com/harvester/harvester/assets/29251855/3b258878-1043-434a-a014-75acb5775840)

  ```
  Configuring bootstrap node(s) rke2-v12713-pool1-7d58dbd5c9xbfzd6-8wx4k: error applying plan -- check rancher-system-agent.service logs on node for more information, waiting for agent to check in and apply initial plan
  ```

* Check the `rancher-system-agent.service` logs can found the following error message 
  ```
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=error msg="error loading CA cert for probe (kube-scheduler) /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt: open /var/lib/rancher/rke2/server/tls/kube-scheduler/kube-scheduler.crt: no such file or directory"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=error msg="error while appending ca cert to pool for probe kube-scheduler"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=info msg="[K8s] updated plan secret fleet-default/rke2-v12713-bootstrap-template-rlqt4-machine-plan with feedback"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=info msg="[Applyinator] Applying one-time instructions for plan with checksum cbd762d1747205b461f6c3a2e40877a0a669c72acb8839c7702256e954e696ed"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=info msg="[Applyinator] Extracting image rancher/system-agent-installer-rke2:v1.27.13-rke2r1 to directory /var/lib/rancher/agent/work/20240605-045458/cbd762d1747205b461f6c3a2e40877a0a669c72acb8839c7702256e954e696ed_0"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=info msg="Using private registry config file at /etc/rancher/agent/registries.yaml"
  Jun 05 04:54:58 rke2-v12713-pool1-996bce2c-5nds2 rancher-system-agent[2797]: time="2024-06-05T04:54:58Z" level=info msg="Pulling image index.docker.io/rancher/system-agent-installer-rke2:v1.27.13-rke2r1"
  
  ```

**To Reproduce**
1. Use [ipxe-example](https://github.com/harvester/ipxe-examples) to provision the `v1.3.1-rc1` Harvester and `v2.8.2` Rancher
2. Create an Opensuse Leap 15.4 nocloud image from url: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.4/images/openSUSE-Leap-15.4.x86_64-NoCloud.qcow2
3. Create vlan 1 network on Harvester
4. Import Harvester to Rancher and create credential 
5. Provision a `v1.27.13` RKE2 cluster on Rancher

**Expected behavior**

Can use Opensuse Leap nocloud image to provision downstream RKE2 cluster in Rancher correctly
 

**Support bundle**

[supportbundle_feee5d2a-bb82-4be1-a07e-732667e98f73_2024-06-05T05-05-01Z.zip](https://github.com/user-attachments/files/15573470/supportbundle_feee5d2a-bb82-4be1-a07e-732667e98f73_2024-06-05T05-05-01Z.zip)

**rancher-system-agent.service logs**
[rancher-system-agent.log](https://github.com/user-attachments/files/15573478/rancher-system-agent.log)

**Environment**
 - Harvester ISO version: v1.3.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single and four nodes on kvm machines
 - Rancher version: v2.8.2 
 - RKE2 k8s version: v1.27.13

**Additional context**

* Use ubuntu focal and jammy image **can provision** RKE2 guest cluster 
* This issue also exists on Harvester v1.3.0 
* Tested also exists on v1.26, v1.27 and v1.28 guest cluster version.

**Comment by tserong** [comment]
Out of curiosity, does the openSUSE Leap 15.4 Minimal VM OpensStack Cloud image work?

https://download.opensuse.org/distribution/leap/15.4/appliances/openSUSE-Leap-15.4-Minimal-VM.x86_64-OpenStack-Cloud.qcow2

**Comment by TachunLin** [comment]
Thanks for the suggestion, let me try the  Minimal VM OpensStack Cloud image on the existing environment.

**Comment by TachunLin** [comment]
Use openSUSE Leap 15.4 Minimal VM OpensStack Cloud image to provision the RKE2 guest cluster. 

It will also encounter the same issue to stuck in `Error applying plan` 
  ![image](https://github.com/harvester/harvester/assets/29251855/5c713670-9c5f-4beb-81d7-b64d870ae79d)

  ![image](https://github.com/harvester/harvester/assets/29251855/45ad3c67-84a3-4e79-b72f-9e1a05467ec0)

**Comment by tserong** [comment]
Thanks for the confirmation!

**Comment by TachunLin** [comment]
Thanks @tserong, according to your investigation and suggestion. 
I modify the `vagrant-pxe-harvester/settings.yml` to replace the dns_server to `1.1.1.1`

```
harvester_network_config:
  # Run as an airgapped environment that only has internet connectivity through an HTTP proxy.
  # The HTTP proxy runs on DHCP server using port 3128
  offline: false

  dhcp_server:
    ip: 192.168.0.254
    subnet: 192.168.0.0
    netmask: 255.255.255.0
    range: 192.168.0.50 192.168.0.130
    https: false
    #  Change this to a custom DNS server if you need one for your DHCP scope
    ## Replace original 4.4.2.2
    dns_server: 1.1.1.1 

```
After rebuilding the environment with ipxe-example and restart the RKE2 downstream cluster provisioning. 

This time we can successfully provision the RKE2 cluster using the OpenSUSE Leap 15.4 nocloud image. 
![image](https://github.com/harvester/harvester/assets/29251855/d4f722c5-e89e-4e6f-90fa-e2a308cccdb4)

Since it's related to the dns problem, we can close this issue as can be solved by environment configuration.
