### ISSUE TITLE
[BUG] Once the console reports running, but the UI not ready yet. 

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#597]
**Describe the bug**

**To Reproduce**
1. install harvester by ISO
2. once the console reports running, try to login

**Expected behavior**

console can prompt for the correct time to log in

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Validated on master-388aa82c-head

Steps:
1. install harvester with ISO
2. When the harvester console displays `NotReady` and `Ready` status, try to log in to the harvester UI

Result:
After the status changes from `NotReady` to `Ready`, you can log in to the harvester UI immediately
