### ISSUE TITLE
[DOC] Add Add-On How-To tutorials 

### ISSUE THREAD

**Issue by innobead** [harvester/harvester#5970]
**Is your doc request related to a problem? Please describe or add related issue ID.**

- Create Add-on tutorial
I would like to have Kasten contribute a K10 add-on in 1.4.0. They can take the first example for future partner cooperation. If anything Partner can install at runtime, we can ask them to integrate us via Add-on. So, we need a doc for it. (It's better to have it in the Harvester doc site if possible or at least WIKI. I would like to have it transparent and public)

- Create an Add-on for the host driver tutorial (like what we have done for the NVIDIA driver)
We need to have a recommended way for partners, especially they need to deploy proprietary drivers on hosts. Although users can do anything through Elemental stages, that is not what we recommend as we don't know how the system will be impacted. It's better to come out with a container solution to deploy user drivers at runtime. The entry point for users is still Add-on.

- Add-on upgrade flow
Do we have any upgrade mechanism for add-ons? If the partner relies on an add-on mechanism, we need to have a way for that day 1 and 2, as they need to manage their integration.

cc @bk201

**Comment by ibrokethecloud** [comment]
link to documentation: https://docs.harvesterhci.io/v1.4/developer/Add-on-development-guide
