### ISSUE TITLE
[BUG] The `Labels` title is displayed twice in the `Host` labels page

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#5973]
**Describe the bug**
The title `Labels` is displayed twice in the `Host` page.

![labels_before](https://github.com/harvester/harvester/assets/1897962/c6979663-a601-4991-91db-d43f5273898e)

**To Reproduce**
1. Go to `Hosts`, select one and choose the `Edit Config` action menu.
2. Select the `Labels` tab.

**Expected behavior**
The title should be displayed only once, as it is done in the `Images` page for example.

![Bildschirmfoto vom 2024-06-05 13-50-23](https://github.com/harvester/harvester/assets/1897962/e608a180-0252-4dca-84bb-9e62b2b282d6)

**Environment**
 - Harvester ISO version: 1.4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ipxe-examples/vagrant-pxe-harvester

**Test Plan**
1. Go to `Hosts`, select one and choose the `Edit Config` action menu.
2. Select the `Labels` tab.
3. There should be only one `Labels` title.

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.3-8c17f4c-head`. Closet this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ The Label title only display once in the Host labels page $~~$</summary>

![image](https://github.com/harvester/harvester/assets/29251855/0f2cf8b9-2350-4aa2-abd1-d5a3f656c560)


 </details>

### Test Information
* Test Environment: Three nodes on remote kvm machines
* Harvester version: `v1.3-8c17f4c-head`

### Verify Steps
<details><summary>Check the Host labels page</summary>

1. Edit Harvester node
2. Open the `Labels` page
3. Check the title

</details>

**Comment by TachunLin** [comment]
Verified **fixed** on `master-8b80f82-head` (24/07/17). Close this issue

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ On singe node: only display one <strong>Labels</strong> in the Host labels page  $~~$</summary>

  ![image](https://github.com/user-attachments/assets/ef06c0a8-ba84-4477-81c5-5b734acc0ffc)



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ On multiple nodes: only display one <strong>Labels</strong> in the Host labels page  $~~$</summary>

  ![image](https://github.com/user-attachments/assets/a2b6c699-ce2a-4f7d-abb2-5b8f148f07d3)


 </details>

### Test Information
* Test Environment: Single node and four nodes on baremetal machines
* Harvester version: `v1.1-340486a3-head` (23/11/20)

### Verify Steps
<details><summary>Check the Host labels page </summary>

  1. Edit config of any node in the Host page
  2. Open the Labels page
  3. Check the UI content

</details>
