### ISSUE TITLE
[BUG] ISO fails to download on v1.2.2 to v1.3.1-rc1 upgrade

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#5989]
**Describe the bug**

You get an `VMImage has reached the specified retry limit` error when trying to do an airgap style upgrade from v1.2.2 -> v1.3.1-rc1.

**To Reproduce**
1. Create a new 1 node v1.2.2 cluster
2. Enable PCI devices addon
3. Create some VMs
4. Run the upgrade by creating a version via `kubectl create -f http://<ipAddress>/version.yaml`
5. Run the upgrade

**Expected behavior**

**Support bundle**

[supportbundle_e9fd7460-a135-4629-a126-8c62f3340c85_2024-06-06T18-15-40Z.zip](https://github.com/user-attachments/files/15680830/supportbundle_e9fd7460-a135-4629-a126-8c62f3340c85_2024-06-06T18-15-40Z.zip)

**Environment**
 - Harvester ISO version: v1.2.2 -> v1.3.1-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): single node dl160

**Additional context**
This was done on a 1 node cluster with PCI devices addon enabled and a PCI device assigned. All the VMs were turned off. This was done on an upgrade test with a log of upgrade pre-reqs. I'm attaching the upgrade log from before I tried to fix it.
![Greenshot 2024-06-06 10 43 12](https://github.com/harvester/harvester/assets/83787952/9c28e136-cdf1-4b3d-a057-6748ba8d04dd)
![Greenshot 2024-06-06 10 59 05](https://github.com/harvester/harvester/assets/83787952/0bf6ff72-0178-4798-8b60-9d70540939eb)
![Greenshot 2024-06-06 10 59 02](https://github.com/harvester/harvester/assets/83787952/9df76d01-282f-4425-a5df-656c1fe9eaed)

[hvst-upgrade-zgzbq-upgradelog-archive-2024-06-06T17-21-42Z.zip](https://github.com/user-attachments/files/15681180/hvst-upgrade-zgzbq-upgradelog-archive-2024-06-06T17-21-42Z.zip)

**Comment by brandboat** [comment]
The ISO URL is wrong, in harvester log, it complains
```text
2024-06-06T17:47:03.994566138Z time="2024-06-06T17:47:03Z" level=error msg="failed to check vmimage" error="Head \"http:/172.19.96.23/iso/v1.3.1-rc1/harvester-v1.3.1-rc1-amd64.iso\": http: no Host in request URL" name=hvst-upgrade-r52kh namespace=harvester-system
```
`http:/172.19.96.23/iso/v1.3.1-rc1/harvester-v1.3.1-rc1-amd64.iso` should be
`http://172.19.96.23/iso/v1.3.1-rc1/harvester-v1.3.1-rc1-amd64.iso`

gentle ping @noahgildersleeve , could you try again with the correct ISO url ? Thanks !

**Comment by bk201** [comment]
@noahgildersleeve Please re-open if it's not a mal-formatted URL.

**Comment by noahgildersleeve** [comment]
I didn't update this, but I was able to download this with the updated URL in the version.yaml and it worked fine. Thanks for the help.
