### ISSUE TITLE
[BUG] After logging out Harvester app, the rancher user is logged out

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#599]
**To Reproduce**
1. Install harvester to a rancher cluster in app mode.
2. Log in to harvester, then do log out in harvester UI.

**Result**
The Rancher user is also logged out.

**Expected behavior**
Logging out Harvester in app mode does not affect the rancher session.

**Environment:**
 - Harvester ISO version: master
 - Installation Mode: app-mode

**Comment by kingsd041** [comment]
master-31c55a75-head
Validated on master-31c55a75-head

Steps:
1. Install harvester to a rancher cluster in app mode.
2. Log in to harvester, then do log out in harvester UI.

Result:
Log out the harvester does not affect the rancher session
