### ISSUE TITLE
[Question] when i create ubuntu vm ，“not a bootable disk”

### ISSUE THREAD

**Issue by yaphetsQ** [harvester/harvester#600]
when  i  create  ubuntu vm ，“not  a  bootable disk” ,  Is it related to hard disk format？

**Comment by guangbochen** [comment]
what type of image are you using? if it is an `ISO` image please reference the ISO template that has been provided by the Harvester, as u will need a bootable driver and a root disk for it.

**Comment by mjschmidt** [comment]
Not all the Ubuntu discs work @yaphetsQ. This image worked for me:
https://cloud-images.ubuntu.com/minimal/releases/focal/release-20200423/ubuntu-20.04-minimal-cloudimg-amd64.img

**Comment by yaphetsQ** [comment]
@guangbochen @mjschmidt  iso or img  type，same  error!
![image](https://user-images.githubusercontent.com/32384347/112929464-0ce76c80-914b-11eb-9a4b-fb9676cc06fe.png)

**Comment by guangbochen** [comment]
can u please provide a reproducible step here? and maybe should try to connect using serial console instead of VNC as not all cloud images will support the VNC console.

**Comment by yaphetsQ** [comment]
@guangbochen   All the settings are done according to the document.

1、
![image](https://user-images.githubusercontent.com/32384347/113085831-26ec8200-9213-11eb-8f90-c825aba08e05.png)

2、
![image](https://user-images.githubusercontent.com/32384347/113085877-37046180-9213-11eb-9aad-7f538d87fc2b.png)

3、
![image](https://user-images.githubusercontent.com/32384347/113086449-34eed280-9214-11eb-87b8-8f015c6b46cd.png)

4、
![image](https://user-images.githubusercontent.com/32384347/113086463-3cae7700-9214-11eb-8ccd-77207890c743.png)

**Comment by guangbochen** [comment]
the image is empty, u will need to select one, the template does not contain any OS images
