### ISSUE TITLE
[BUG] After update TLS certificate in Rancher, Harvester Cluster is unavailable in Rancher 

### ISSUE THREAD

**Issue by dawid10353** [harvester/harvester#6001]
**Describe the bug**
After update TLS certificate in Rancher, Harvester cluster in "Rancher" -> "Virtualization Management" stuck in "Unavailable Cluster agent is not connected" state. 

**To Reproduce**
Change TLS certificate in Rancher (https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate)

**Expected behavior**
Rancher can connect to Harvester cluster.

**Environment**
 - Harvester ISO version: v1.2.2
-  Rancher: v2.8.3

**Comment by ibrokethecloud** [comment]
Hi @dawid10353 are you able to please confirm if you perform the steps listed under section: https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/update-rancher-certificate#4-reconfigure-rancher-agents-to-trust-the-private-ca
