### ISSUE TITLE
[BUG] Migrating VM Hung For 10 Min + During Upgrade Pre-Drain on Node

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6002]
**Describe the bug**
**_Seems very difficult to reproduce._**
RKE2 VM hung at 10min+ on migrating during upgrade.

**Workaround, fairly simple**
1. Stopping the VM
1. Removing the virt-launcher pod from the node it was migrating from.
1. Then draining will be successful on node and node can continue upgrade.

**To Reproduce**
1. Seems very difficult to reproduce

**Expected behavior**
RKE2 VM not to be hung at migrating.

**Environment**
 - Harvester ISO version: v1.3.0->v1.3.1-rc2
 - Underlying Infrastructure: bare-metal, HP DL160

**Additional Context**
- Encountered:
"Corresponding Condition of pod readiness gate kubevirt / unpaused does not exist"

![Screenshot from 2024-06-08 19-13-17](https://github.com/harvester/harvester/assets/5370752/c2ff4e22-e412-461b-9a5a-094012ad5c81)

Marking as reproduce/rare

**Comment by w13915984028** [comment]
One of the know limitation of migration is that when the memory dirty speed on source VM is faster than the copy speed to dest, the VM may show as hung.

@irishgordo Were there some busy applications on those 2 VMs when pre-drain?

**Comment by irishgordo** [comment]
So the VM that was hung was an RKE2 v1.27 VM, the only thing running on that RKE2 VM was a few PVCs attached to an NGINX deployment w/ a load-balancer.  But other than that the cluster wasn't too busy...it had a few extra test vms & an RKE1 VM

**Comment by bpedersen2** [comment]
I did observe a similar behavior on upgrade (1.2.2-> 1.3.1). The problematic pod were in my case ( rancher-provisoned  rke2 clusters)  the etcd pods that got stuck and produced massive memory load. Manually deleting the stuck ones in the downstream clusters allowed the upgrade to progress. 

You could observe the memory migration problem easily in the vm logs in harverster:  the memory remaining to migrate did first decrease, but then jumped backed to a much higher value again...
