### ISSUE TITLE
[Question] Supported upgrade path from 1.1.3?

### ISSUE THREAD

**Issue by simonflood** [harvester/harvester#6010]
With Harvester 1.1 now EOL, currently there doesn't appear to be an officially supported upgrade path from Harvester 1.1.3 - the docs have 1.1.1/1.1.2 to 1.1.3 but nothing from 1.1.3.

Based on #4873 and #4830 I suspect the supported target is 1.2.1. If so the upgrade index page for 1.2 and 1.3 (and onwards) needs updating to reflect this.

**Comment by bk201** [comment]
@simonflood the supported upgrade path will be v1.1.3 -> v1.2.1, we'll update the doc.

**Comment by bk201** [comment]
Doc is published: https://docs.harvesterhci.io/v1.3/upgrade/v1-2-0-to-v1-2-1
