### ISSUE TITLE
[Doc] Add info about software required by the NVIDIA Driver Toolkit addon

### ISSUE THREAD

**Issue by jillian-maroket** [harvester/harvester#6013]
**Is your doc request related to a problem? Please describe or add related issue ID.**

This is from `harvester/docs`. Issue creation for that repo will be disabled soon.

Per Alejandro, the download link in the screenshot is from the NVIDIA Enterprise Downloads.

<img width="1130" alt="Screenshot 2024-06-12 at 11 47 54 AM" src="https://github.com/harvester/harvester/assets/67180770/bf4e4012-f93e-4363-863a-9305f8fe19bd">

**Describe the solution you'd like**

Tell users where they can find the required modules and guest drivers.

**Comment by jillian-maroket** [comment]
@bk201 Who can help provide the requested information?

**Comment by bk201** [comment]
@jillian-maroket I've checked with @ibrokethecloud. We can't recommend a driver, the user will need to have a license access nvidia's doc, and locate the driver by according to the models.  So the paragraph in https://docs.harvesterhci.io/v1.3/advanced/addons/nvidiadrivertoolkit does the trick:
> note
The toolkit only includes the correct Harvester OS image, build utilities, and kernel headers that allow NVIDIA drivers to be compiled and loaded from the container. You must download the NVIDIA KVM drivers using a valid NVIDIA subscription. For guidance on identifying the correct driver for your NVIDIA GPU, see the [NVIDIA documentation](https://www.nvidia.com/en-au/drivers/vgpu-software-driver/).

**Comment by jillian-maroket** [comment]
@bk201 @ibrokethecloud Thank you for checking the request. I agree that providing specific package names is tricky because these can change any time.

**Comment by bk201** [comment]
Close due to it's not recommend to have a package name, please se https://github.com/harvester/harvester/issues/6013#issuecomment-2283059263
