### ISSUE TITLE
[ENHANCEMENT] Change the location of supportconfig file of support bundle

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6016]
**Is your enhancement related to a problem? Please describe.**
The `supportconfig` will help to provide various system info, and it would help us to dig more with the system side.
But it is located on the `nodes/<node name>/logs`, It's not easy to find. We should change it to a clearer directory.

**Describe the solution you'd like**
Move supportconfig generated file to `/nodes/<node name>/scc`

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by TachunLin** [comment]
Verified **fixed** on master-d58e8b1-head (24/09/11).

### Single node result
<details><summary>$\color{green}{\textsf{PASS}}$ The scc tarball file is on the top layer of nodes/<node name> $~~$</summary>

![image](https://github.com/user-attachments/assets/7a53b808-c805-463c-b6c5-ef799a59804d)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ The scc tarball file can be extracted and all the files can be opened with available content $~~$</summary>

  ![image](https://github.com/user-attachments/assets/370d0cc3-7e70-4bfa-b04d-56ebcc399fe5)
  ![image](https://github.com/user-attachments/assets/f5705f0c-40c1-40bd-be8c-aeafb7be7df1)

 </details>

### Multiple nodes result
<details><summary>$\color{green}{\textsf{PASS}}$ The scc tarball file is on the top layer of each nodes/<node name> $~~$</summary>
  



  ![image](https://github.com/user-attachments/assets/a891a98a-2a4f-44b2-9c48-c8be1624498a)
  
  ![image](https://github.com/user-attachments/assets/d14cf763-cd78-4c6a-a550-2d857a232635)
  
  ![image](https://github.com/user-attachments/assets/2ec316d0-18ec-4cbd-b9f8-1eac9722bd60)



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ The scc tarball file can be extracted and all the files can be opened with available content $~~$</summary>

  ![image](https://github.com/user-attachments/assets/1b68db39-a19d-40a9-a843-f64efc0e568c)
  
  ![image](https://github.com/user-attachments/assets/8b9046ce-2f52-4b2e-a81f-5ea0a8e2b6c1)
  
  
  ![image](https://github.com/user-attachments/assets/9989e60a-95c6-4be0-949d-2a7fb0d50035)


 </details>

### Test Information
* Test Environment: Single and three nodes harvester on kvm and bare metal machines
* Harvester version: master-d58e8b1-head (24/09/11)

### Verify Steps
<details><summary> Check the supportconfig file location </summary>

1. Provision Harvester cluster ready
2. Download the support bundle 
3. Extract the support bundle
4. Check the scc tarball file is under the nodes/<node name> path
5. Unzip the scc_supportconfig_<node-name>.txz
  ```
  tar Jxvf <file name>.txz
  ```
6. Check can extract the tarball file and all content exists

</details>
