### ISSUE TITLE
[BUG] storage classes showing the wrong name on volumes page

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6019]
**Describe the bug**

The storage classes show the wrong name on the volumes page.
**To Reproduce**
1. Create a new storage class
2. Create a new VM with the storage class
3. Navigate to the Volumes page after creating the VM
**Expected behavior**

It should show the name of the storage class label that you created, or not show it at all.
**Support bundle**

[supportbundle_f42350f8-c19b-427c-9d50-a87916b89ed3_2024-06-13T17-46-59Z.zip](https://github.com/user-attachments/files/15828590/supportbundle_f42350f8-c19b-427c-9d50-a87916b89ed3_2024-06-13T17-46-59Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1-rc2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 node bare metal DL160

**Additional context**

It looks like it's using the name that longhorn is creating on the backend.

![Greenshot 2024-06-13 10 46 14](https://github.com/harvester/harvester/assets/83787952/4da9236d-2f85-4780-b219-fa04e6df6a86)

**Comment by WebberHuang1118** [comment]
Hi @noahgildersleeve ,

I think this is expected, the image-backed volume uses a different SC (compared to the origin one) to connect the volume with the LH backing image, and the name of the SC is automatically decided by the Harvester controller.

From SB, I found most of the pvc are image-backed so their SC related to a backing image, for exampe pvc `rke2-test-rke2-test-8f80e2bc-ln9g4-disk-0-gc4bm` (with SC `longhorn-image-s8r7p`) is created with VM image `image-s8r7p` (display-name `focal-server-cloudimg-amd64-disk-kvm.img`)

Only one pvc `hvst-upgrade-4h6lp-upgradelog-log-archive` is not image-backed, so it's with SC `ssd`, this is not generated by the Harvester controller, thanks.
