### ISSUE TITLE
[Question] what is the migrate function of Cluster Networks/Configs 

### ISSUE THREAD

**Issue by hchyue** [harvester/harvester#6021]
![image](https://github.com/harvester/harvester/assets/69490488/119ca9fc-ce3b-4b36-bb95-52c230615289)
is there any documents for this ?

**Comment by w13915984028** [comment]
Seems the source code can help :), FYI:

https://github.com/harvester/dashboard/blob/11ce37d397fe89df6a62ff81794ade3f5e6591ed/pkg/harvester/models/network.harvesterhci.io.vlanconfig.js#L70

https://github.com/harvester/dashboard/blob/master/pkg/harvester/dialog/HarvesterVlanConfigMigrateDialog.vue#L68

**Comment by starbops** [comment]
Some background of the VlanConfig migration enhancement: #3372 

Perhaps we need documentation to explain why this feature exists and why we need this additional dedicated operation, even though solely the "Edit Config" action seems to be able to accomplish this task (which is not).

**Comment by hchyue** [comment]
> Some background of the VlanConfig migration enhancement: #3372
> 
> Perhaps we need documentation to explain why this feature exists and why we need this additional dedicated operation, even though solely the "Edit Config" action seems to be able to accomplish this task (which is not).

yes，the background explained the migrate function of Cluster Networks/Configs is：migrate vlanconfigs into a new cluster network

thank you!
