### ISSUE TITLE
[ENHANCEMENT] Bump Harvester OS to SLE-Micro 5.5

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6027]
**Is your enhancement related to a problem? Please describe.**
We should use the newer OS for v1.4.0

**Describe the solution you'd like**
Bump OS with SLE-Micro 5.5

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by innobead** [comment]
Have we considered bumping to SLE-Micro 5.6?

**Comment by Vicente-Cheng** [comment]
> Have we considered bumping to SLE-Micro 5.6?

The next release of SLE-Micro 5.5 is SLE-Micro 6.0
(Ref: https://www.suse.com/lifecycle/#suse-linux-enterprise-micro)

IIUC, there are some major changes (like moving to btrfs instead image-based immutable OS) on SLE-Micro 6.0.
So, I thought we should use SLE-Micro 5.5 instead SLE-MIcro 6.0. (6.0 will bring too many potential risks)
Also, the EoL of SLE-Micro 5.5 is' 31 Oct 2027`. It's long enough for us to move on to the next.

**Comment by irishgordo** [comment]
Thanks for this @Vicente-Cheng  - this looks good on Harvester Version: master-9c0a3a1-head
With:
```
(rancher@192.168.104.163) Password: 
Last login: Wed Jul  3 19:35:38 2024 from 192.168.9.163
rancher@test-node-8:~> sudo cat /etc/os-release 
NAME="SLE Micro"
VERSION="5.5"
VERSION_ID="5.5"
PRETTY_NAME="Harvester master"
ID="sle-micro-rancher"
ID_LIKE="suse"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sle-micro-rancher:5.5"
IMAGE_REPO="registry.suse.com/suse/sle-micro/base-5.5"
IMAGE_TAG="2.0.4-5.8.31"
IMAGE="registry.suse.com/suse/sle-micro/base-5.5:2.0.4-5.8.31"
TIMESTAMP=20240626110458
GRUB_ENTRY_NAME="SLE Micro"
VARIANT="Harvester"
VARIANT_ID="Harvester-20240703-785f4dd"
GRUB_ENTRY_NAME="Harvester master"
rancher@test-node-8:~> 
``` 
I'll go ahead and close this out :+1: :smile:
