### ISSUE TITLE
[ENHANCEMENT] Skip the image preloading phase of Harvester upgrade

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#6028]
**Is your enhancement related to a problem? Please describe.**

We've had all the required images published on the Internet, so presumably, all the needed images could be downloaded if the Harvester cluster has Internet connectivity, i.e., non-air-gapped clusters. This gives us the green light to skip the image-preloading phase of the Harvester upgrade to speed up the currently time-consuming node-by-node process.

**Describe the solution you'd like**

Respect a newly introduced annotation for the Upgrade CR: `harvesterhci.io/skip-image-preload`. If such an annotation is set to true, the upgrade controller will skip creating the image-preloading Plan CR and mark all the nodes as `Image Preloaded`.

**Describe alternatives you've considered**

Enabling image preloading parallelism is another way to speed up the Harvester upgrade, especially for the image preloading phase.

**Additional context**

**Comment by w13915984028** [comment]
Validation: **PASS**

(1) Install a cluster from v140-20240918 ISO.
```
$kubectl get settings.harvesterhci.io upgrade-config
NAME             VALUE
upgrade-config   {"imagePreloadOption":{"strategy":{"type":"skip"}}, "restoreVM": true}
```
(2) Upgrade to a local built v140-branch master-head ISO at 20241001:

Upgrade stucks `ImagePullBackOff` as there seems no such image in the remote.

![image](https://github.com/user-attachments/assets/54fb36cd-8f98-4d9b-842a-45e1e2d9b1e9)

```
$kubectl get pods -A | grep upgrade
cattle-system                     system-upgrade-controller-6f86d6d4df-mg8p4               1/1     Running            2 (22m ago)    6d1h
harvester-system                  hvst-upgrade-tvs2p-apply-manifests-897cb                 0/1     ImagePullBackOff   0              5m19s
harvester-system                  virt-launcher-upgrade-repo-hvst-upgrade-tvs2p-hlc6b      2/2     Running            0              7m36s

$kubectl get pods -n harvester-system hvst-upgrade-tvs2p-apply-manifests-897cb -oyaml | grep image
    image: rancher/harvester-upgrade:aa4976fe
    imagePullPolicy: IfNotPresent
  - image: rancher/harvester-upgrade:aa4976fe
    imageID: ""
        message: Back-off pulling image "rancher/harvester-upgrade:aa4976fe"
```

(3) Upgrade to a v140-rc1 ISO

Upgrade is successful
![image](https://github.com/user-attachments/assets/f4ef16c3-1e51-4a9f-b7a7-2ac1d83fe8f0)

There is no prepare on node process
```
$kubectl get pods -A | grep upgrade
cattle-system                     apply-system-agent-upgrader-on-harv2-with-4c66be614b821bd-zt8wb   0/1     Completed   0               4m43s
cattle-system                     system-upgrade-controller-795b6fdf6-xv4ng                         1/1     Running     0               4m52s
harvester-system                  hvst-upgrade-hbds9-apply-manifests-65vnv                          0/1     Completed   0               7m27s
harvester-system                  hvst-upgrade-hbds9-single-node-upgrade-harv2-2rxtr                1/1     Running     0               113s
```

After upgrade, there is no `docker.io/rancher/harvester-eventrouter` v0.3.2 container image, as we did not enable rancher-logging addon
```
...
docker.io/rancher/harvester-cluster-repo                                    v1.4.0-dev-20240918                         b380103d6ef07       190MB
docker.io/rancher/harvester-cluster-repo                                    v1.4.0-rc1                                  c8db45f85b8e1       65.8MB
docker.io/rancher/harvester-eventrouter                                     v0.3.1                                      cd6357a872149       91.8MB
docker.io/rancher/harvester-load-balancer-webhook                           v0.4.1                                      fc1a13a58a021       106MB
docker.io/rancher/harvester-load-balancer-webhook                           v0.4.2                                      7a580e34c2c86       34.3MB
...
```

After enabling `rancher-logging` addon, it is successful, the new image is dynamically loaded
![image](https://github.com/user-attachments/assets/9cdf13e9-f875-4823-8712-04b005575ba7)


```
docker.io/rancher/harvester-cluster-repo                                    v1.4.0-rc1                                  c8db45f85b8e1       65.8MB
docker.io/rancher/harvester-eventrouter                                     v0.3.1                                      cd6357a872149       91.8MB
docker.io/rancher/harvester-eventrouter                                     v0.3.2                                      4682a8df751f1       29.7MB
docker.io/rancher/harvester-load-balancer-webhook                           v0.4.1                                      fc1a13a58a021       106MB
```

All works.

**Comment by w13915984028** [comment]
This enhancement works well, thanks @starbops .
