### ISSUE TITLE
[BUG] Updating specific Harvester settings like containerd-registry during upgrade will break the upgrade

### ISSUE THREAD

**Issue by starbops** [harvester/harvester#6035]
**Describe the bug**

Updating Harvester settings like `containerd-registry`, `auto-rotate-rke2-certs`, and `http-proxy` during Harvester upgrade will also update the `local` Cluster object. Things will go wrong if such actions happen when the cluster is under upgrading.

To be more precise, when the upgrade process enters the "node upgrade" phase, the `.spec.rkeConfig` is filled with some upgrade-specific data (e.g., pre/post-drain options). Once the Cluster object is updated, say, with some custom registry, the internal Rancher Manager will reconcile the object and start draining the first node. Even if the first node is fully upgraded, the internal Rancher Manager will drain it again. Things will worsen because Harvester leverages the pre/post-drain hook mechanism provided by Rancher, but Harvester is clever enough not to pre/post-drain the node again. As a result, the first node will be stuck in the draining state indefinitely.

**To Reproduce**

1. Prepare a v1.2.2 multi-node Harvester cluster
2. Upgrade to v1.3.1
3. When the first node start to pre-drain, update the `containerd-registry` setting
4. The entire upgrade process will be stuck at the first node draining

**Expected behavior**

Upgrade should end successfully.

**Support bundle**

Please refer to #6022 for support bundles.

**Environment**
 - Harvester ISO version: v1.2.2 upgrade to v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

This is the root cause of #6022. But since that ticket involved other problems, we created a new one (this) to focus on the update-setting-during-upgrade issue.

**Comment by w13915984028** [comment]
It looks the general rule is to disable the editing of settings during upgrade, unless some are specially annotated.
