### ISSUE TITLE
[BUG] Upgrade v1.2.2->v1.3.1 stuck at Waiting for kubelet to update, even the node has been updated

### ISSUE THREAD

**Issue by W0n9** [harvester/harvester#6041]
**Describe the bug**

This is my another cluster, similar to https://github.com/harvester/harvester/issues/6022, but did NOT change the settings during upgrading process.

![image](https://github.com/harvester/harvester/assets/38560218/ce3a8918-b4b6-4f04-b9b6-5ea80756ef8d)
![image](https://github.com/harvester/harvester/assets/38560218/227ad375-28e3-470d-8eda-d1848baabafa)
![image](https://github.com/harvester/harvester/assets/38560218/9b6efa93-56a1-4b20-8657-2730b4acdcdb)
![image](https://github.com/harvester/harvester/assets/38560218/04286e64-10c6-4c7a-9a85-58582ac2642c)

**To Reproduce**
1. Upgrade harvester from v1.2.2 to v1.3.1

**Expected behavior**

Cluster should be upgraded successfully

**Support bundle**

[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-19T14-53-14Z.001.zip](https://github.com/user-attachments/files/15902959/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-19T14-53-14Z.001.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-19T14-53-14Z.002.zip](https://github.com/user-attachments/files/15902961/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-19T14-53-14Z.002.zip)
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-19T14-58-37Z.001.zip](https://github.com/user-attachments/files/15902962/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-19T14-58-37Z.001.zip)
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-19T14-58-37Z.002.zip](https://github.com/user-attachments/files/15902963/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-19T14-58-37Z.002.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure: Baremetal with Dell PowerEdge R740

**Additional context**

**Comment by bk201** [comment]
@W0n9 can you help get the log of `capi-controller-manager-xxx` pod in the `cattle-provisioning-capi-system` namespace? Thanks. cc @FrankYang0529

**Comment by W0n9** [comment]
Hi @bk201 
Here is the logs
[capi-controller-manager-6685d6b766-jv87k_manager.log](https://github.com/user-attachments/files/15907357/capi-controller-manager-6685d6b766-jv87k_manager.log)

**Comment by bk201** [comment]
@W0n9 Please kill the `capi-controller-manager-xxx` pod and let it restart, the upgrade should go on.

**Comment by W0n9** [comment]
Hi @bk201 
I tried to kill the capi-controller-manager, which made one of my node upgrade succeed.
But the last node stuck at Pre-draining again.
I followed [this](https://github.com/harvester/harvester/issues/4698#issuecomment-1818363857), it seems to draining node now.

**Comment by W0n9** [comment]
Hi @bk201 
I have followed https://github.com/harvester/harvester/issues/4698#issuecomment-1818363857, and executed `./post-drain.sh harvester1`.
It stuck at `pre-drained` state now and I followed [this](https://docs.harvesterhci.io/v1.3/upgrade/v1-1-2-to-v1-2-0#5-an-upgrade-is-stuck-in-the-pre-drained-state) to check, but they don't work.
![image](https://github.com/harvester/harvester/assets/38560218/a84493ae-c7aa-47fa-aa1c-7983fd3e18ee)

Here is my latest support bundle files:
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-20T09-43-29Z.001.zip](https://github.com/user-attachments/files/15912137/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-20T09-43-29Z.001.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-20T09-43-29Z.002.zip](https://github.com/user-attachments/files/15912139/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-06-20T09-43-29Z.002.zip)

Upgrade logs:
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.001.zip](https://github.com/user-attachments/files/15912174/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.001.zip)
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.002.zip](https://github.com/user-attachments/files/15912176/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.002.zip)
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.003.zip](https://github.com/user-attachments/files/15912178/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.003.zip)
[hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.004.zip](https://github.com/user-attachments/files/15912183/hvst-upgrade-vpf4q-upgradelog-archive-2024-06-20T10-03-50Z.004.zip)

**Comment by W0n9** [comment]
Inspired by https://github.com/harvester/harvester/issues/6094#issuecomment-2198017986, I have made `harvester1` into Maintenance Mode, then reboot and exit Maintenance Mode. I found the VM can be scheduled to `harvester1` now.
From the Embedded Rancher UI, I found the pod image on `harvester1` has been updated to `rancher/harvester:v1.3.1`, but OS image still at Harvester v1.2.2.
Moreover, I found a pod `snapshot-controller-56f675cb4d-gq6dx` with `Imagepullbackoff`, it maybe related to something wrong with `image preload`?
![image](https://github.com/harvester/harvester/assets/38560218/bf8c2b23-219a-4049-9c2e-1a9c7a973d58)

**Comment by johnwc** [comment]
> Inspired by [#6094 (comment)](https://github.com/harvester/harvester/issues/6094#issuecomment-2198017986), I have made `harvester1` into Maintenance Mode, then reboot and exit Maintenance Mode. I found the VM can be scheduled to `harvester1` now. From the Embedded Rancher UI, I found the pod image on `harvester1` has been updated to `rancher/harvester:v1.3.1`, but OS image still at Harvester v1.2.2. Moreover, I found a pod `snapshot-controller-56f675cb4d-gq6dx` with `Imagepullbackoff`, it maybe related to something wrong with `image preload`? ![image](https://private-user-images.githubusercontent.com/38560218/344862404-bf8c2b23-219a-4049-9c2e-1a9c7a973d58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5Mzg0NDksIm5iZiI6MTcxOTkzODE0OSwicGF0aCI6Ii8zODU2MDIxOC8zNDQ4NjI0MDQtYmY4YzJiMjMtMjE5YS00MDQ5LTljMmUtMWE5YzdhOTczZDU4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDE2MzU0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE1MzEzYTMwZjRhOTc3OTdmYTNiYTIyOGIyZjNjY2UwYTk2NWM5Mjc5MjZhNTllM2RkNDg2NjFlNTkzMWQ1YzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LU8_RlyewHZs5Aro5SzPI6sCzttuns0KosjKl6sgEp0)

@W0n9  The errors in the screenshot are telling you that your servers are unable to reach the web server on the internet that is hosting the files it is trying to download. Is there a firewall blocking it?

**Comment by W0n9** [comment]
Hi @johnwc 
Exactly I am in a "Air Gapped Environment".
But in my opinion, refer to https://github.com/harvester/harvester/releases/download/v1.3.1/harvester-images-list-amd64.txt, the image `registry.k8s.io/sig-storage/snapshot-controller:v6.3.3` have been packed in the Harvester ISO, it should run without Internet connection.

**Comment by bk201** [comment]
@W0n9 Did your cluster hit an image garbage collection due to space usage?

**Comment by W0n9** [comment]
Hi @bk201 
I think it didn't hit, because `/usr/local` has 34GB available.
![image](https://github.com/harvester/harvester/assets/38560218/16934732-2dba-4f4b-b230-54a8bf618c35)
How can I check wheather my cluster ever hit an image gc?
And can I reload the image into the node?

**Comment by W0n9** [comment]
Inspired by https://github.com/harvester/harvester/issues/6022#issuecomment-2217150057, I reran the upgrade.
And it upgraded successfully. It maybe a workaround for this problem.
![image](https://github.com/harvester/harvester/assets/38560218/f001f835-19f7-43e6-a1c7-660339dac050)

**Comment by albinsun** [comment]
Hi @W0n9 ,
I'm trying reproduce this issue and want to confirm:
1. Your operations on Harvester (e.g. create VM and trigger upgrade...) are via an external `rancher-v2.8.5`, is that correct? 
   ![image](https://github.com/harvester/harvester/assets/2773781/6da0d495-c034-4092-964c-eaaa39dfe9f2)
2. If so, did you upgrade rancher before upgrading harvester?

**Comment by W0n9** [comment]
Hi @albinsun ,
1. Exactly, my operations are via an external rancher 2.8.5.
2. I upgraded rancher before upgrading harvester. Result is from followed picture, my timezone is UTC+8
![image](https://github.com/harvester/harvester/assets/38560218/aa0014d1-c906-4a40-8fe9-8130f1a0b258)

**Comment by bk201** [comment]
To check if users hit this while upgrading 1.3.1 to 1.3.2

**Comment by bk201** [comment]
Please reopen if seeing this again.

**Comment by W0n9** [comment]
Hi @bk201 
I faced the problem which is stuck at pre-drained after stuck at pre-draining again during upgrade from v1.3.2 to v1.4.0.
Stuck at pre-draining issue: https://github.com/harvester/harvester/issues/7067
![微信截图_20241129155956](https://github.com/user-attachments/assets/a98b9fa0-2714-4a0c-931c-ae49ffbec62d)
Here are the logs and supportbundle
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.5.zip](https://github.com/user-attachments/files/17956357/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.5.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.4.zip](https://github.com/user-attachments/files/17956359/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.4.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.3.zip](https://github.com/user-attachments/files/17956362/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.3.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.2.zip](https://github.com/user-attachments/files/17956364/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.2.zip)
[supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.1.zip](https://github.com/user-attachments/files/17956365/supportbundle_6200f644-e4a1-40c1-bf7c-070ccbcb556d_2024-11-29T08-16-06Z.1.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.6.zip](https://github.com/user-attachments/files/17956367/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.6.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.5.zip](https://github.com/user-attachments/files/17956368/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.5.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.4.zip](https://github.com/user-attachments/files/17956369/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.4.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.3.zip](https://github.com/user-attachments/files/17956371/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.3.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.2.zip](https://github.com/user-attachments/files/17956372/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.2.zip)
[hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.1.zip](https://github.com/user-attachments/files/17956375/hvst-upgrade-sc8tg-upgradelog-archive-2024-11-29T08-10-35Z.1.zip)
