### ISSUE TITLE
[BUG] Custom console url stripping characters

### ISSUE THREAD

**Issue by johnwc** [harvester/harvester#6042]
**Describe the bug**
We use Royal TS to manage and connect to remote devices/services. The app [supports uri handler](https://docs.royalapps.com/r2021/royalts/advanced/uri.html) for `rtsx://` When we add the uri of `rtsx://vnc%3a%2f%2fUser@server-x.domain.local?property_Port=1234&property_Description=Server%20X` as a console URL for a host, the colon in the uri gets stripped out when clicking on the console button from the UI. The browser opens a new tab trying to connect to `rtsx//vnc%3a%2f%2fUser@server-x.domain.local?property_Port=1234&property_Description=Server%20X`

**To Reproduce**
1. Edit a host
2. Add URI as described above as `Console URL` and save.
3. Click on `Console` button for same host.

**Expected behavior**
Browser opens unmodified url.

**Environment**
 - Harvester ISO version: v1.2.2
 - Underlying Infrastructure: Dell PowerEdge R640

**Comment by m-ildefons** [comment]
Confirmed, this reproduces on v1.3.1(-rc1) as well.

This commit introduced code that enforces that console URLs must always start with `http://` or `https://` or else `http://` will be prepended to the console URL:
https://github.com/rancher/dashboard/pull/6806/commits/bc5523bed18a7b11668d4082069b1aca3e2d8a34

```
    if (!url.startsWith('http://') && !url.startsWith('https://')) {
      return `http://${ url }`;
    }
```

I'm not sure why this check was introduced. I suppose support for custom protocol schemas isn't well established between different browsers and versions?
There is an [RFC](https://www.rfc-editor.org/rfc/rfc7869.html) describing a possible `vnc://` URL schema as well, so to me it makes little sense to limit the URL schemas to `http://` and `https://` only. While the `vnc://` URL schema is [recognized by IANA](https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml), the `rtsx://` schema is not. Nevertheless, limiting the possible URLs to those with `http://` or `https://` schemas is overly restrictive IMO.

**Comment by johnwc** [comment]
If they really wanted to verify it was a URL with a schema, so to avoid doing something like `/some/path/in/harvester`; it could just verify that `^[a-z]+:\/\/` matches the url string.
