### ISSUE TITLE
[ENHANCEMENT] Improve the log time format from `journalctl`

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6043]
**Is your enhancement related to a problem? Please describe.**
We do not have any specific time format, so it's not very accurate on logs.
We can not ensure the event order with the various logs.

**Describe the solution you'd like**
We could use `-o short-precise` to improve that.
w/o this
```
Jun 19 10:33:53 harvester-node-1 kernel: loop2: detected capacity change from 0 to 2097152
Jun 19 10:33:53 harvester-node-1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

w/ this
```
Jun 19 10:33:53.477371 harvester-node-1 kernel: loop2: detected capacity change from 0 to 2097152
Jun 19 10:33:53.653363 harvester-node-1 kernel: IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

**Describe alternatives you've considered**
None

**Additional context**
Make sure the format of the log timestamp is like the above.

**Comment by TachunLin** [comment]
Verified **fixed** on `master-d58e8b1-head` (24/09/11). Close this issue.

### Singe node test result
<details><summary>$\color{green}{\textsf{PASS}}$ The time format in the kernel.log of support bundle contain more precise information $~~$</summary>

  ![image](https://github.com/user-attachments/assets/1776ecad-e500-4209-90b7-db5a0b015810)
  
  ![image](https://github.com/user-attachments/assets/a277920c-82f3-4349-8be3-91156d35478d)


 </details>

### Three nodes test result
<details><summary>$\color{green}{\textsf{PASS}}$ On each node, the time format in the kernel.log of support bundle contain more precise information $~~$</summary>

  
  ![image](https://github.com/user-attachments/assets/19b72de8-0edb-4b46-947d-4614528edd19)
  
  ![image](https://github.com/user-attachments/assets/67e36a78-8e75-4d95-8f62-d8a02e8723c7)
  
  ![image](https://github.com/user-attachments/assets/6a488cb4-d6ab-475a-96d7-1907fad5551b)


 </details>

### Test Information
* Test Environment: Single and three nodes harvester on local and baremetal machines.
* Harvester version: `master-d58e8b1-head` (24/09/11)

### Verify Steps
<details><summary> Time format of the kernel.log in support bundle </summary>

  1. Prepare single or three nodes Harvester cluster 
  2. Download the support bundle file 
  3. Extract the support bundle to local drive
  4. Open the `nodes/<node name>/logs/kernel.log or kernel1.log

</details>
