### ISSUE TITLE
[question]cluster-registration-url  question

### ISSUE THREAD

**Issue by sonic2825** [harvester/harvester#6049]
Title: Certificate Verification Error with Rancher v2.8.3 and Harvester v1.3.1

Environment:

Rancher Version: v2.8.3
Harvester Version: v1.3.1
Description:
I'm encountering a certificate verification error when trying to use Rancher with Harvester. The error suggests that the certificate chain is not complete.

hvsi1061:~ # kubectl  logs -f cattle-cluster-agent-74bc874f8d-zlm5k -n cattle-system
INFO: Environment: CATTLE_ADDRESS=10.52.3.38 CATTLE_CA_CHECKSUM= CATTLE_CLUSTER=true CATTLE_CLUSTER_AGENT_PORT=tcp://10.53.161.151:80 CATTLE_CLUSTER_AGENT_PORT_443_TCP=tcp://10.53.161.151:443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_ADDR=10.53.161.151 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PORT=443 CATTLE_CLUSTER_AGENT_PORT_443_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_PORT_80_TCP=tcp://10.53.161.151:80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_ADDR=10.53.161.151 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PORT=80 CATTLE_CLUSTER_AGENT_PORT_80_TCP_PROTO=tcp CATTLE_CLUSTER_AGENT_SERVICE_HOST=10.53.161.151 CATTLE_CLUSTER_AGENT_SERVICE_PORT=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTP=80 CATTLE_CLUSTER_AGENT_SERVICE_PORT_HTTPS_INTERNAL=443 CATTLE_CLUSTER_REGISTRY= CATTLE_INGRESS_IP_DOMAIN=sslip.io CATTLE_INSTALL_UUID=bfa29b1e-7b2a-42ad-b750-d3603e554a23 CATTLE_INTERNAL_ADDRESS= CATTLE_IS_RKE=false CATTLE_K8S_MANAGED=true CATTLE_NODE_NAME=cattle-cluster-agent-74bc874f8d-zlm5k CATTLE_RANCHER_WEBHOOK_VERSION= CATTLE_SERVER=https://inf-k8s.sha-dc01.metax-tech.com CATTLE_SERVER_VERSION=v2.8.3
INFO: Using resolv.conf: search cattle-system.svc.cluster.local svc.cluster.local cluster.local nameserver 10.53.0.10 options ndots:5
INFO: https://inf-k8s.sha-dc01.metax-tech.com/ping is accessible
INFO: inf-k8s.sha-dc01.metax-tech.com resolves to 10.2.151.5
time="2024-06-21T02:57:10Z" level=info msg="Listening on /tmp/log.sock"
time="2024-06-21T02:57:10Z" level=info msg="Rancher agent version v2.8.3 is starting"
time="2024-06-21T02:57:10Z" level=info msg="Certificate details from https://inf-k8s.sha-dc01.metax-tech.com"
time="2024-06-21T02:57:10Z" level=info msg="Certificate #0 (https://inf-k8s.sha-dc01.metax-tech.com)"
time="2024-06-21T02:57:10Z" level=info msg="Subject: CN=*.metax-tech.com,OU=IT,O=MetaX,L=Shanghai,ST=SHA,C=CN"
time="2024-06-21T02:57:10Z" level=info msg="Issuer: CN=METAX-WPKI,0.9.2342.19200300.100.1.25=#130a6d657461782d74656368,0.9.2342.19200300.100.1.25=#1303636f6d"
time="2024-06-21T02:57:10Z" level=info msg="IsCA: false"
time="2024-06-21T02:57:10Z" level=info msg="DNS Names: [*.sha-dc01.metax-tech.com *.sha-dc02.metax-tech.com *.dvp.metax-tech.com *.dmz.metax-tech.com *.dtz.metax-tech.com *.gscs.metax-tech.com *.mde.metax-tech.com *.mse.metax-tech.com *.ywgl.metax-tech.com *.metax-tech.com]"
time="2024-06-21T02:57:10Z" level=info msg="IPAddresses: <none>"
time="2024-06-21T02:57:10Z" level=info msg="NotBefore: 2023-04-16 03:28:05 +0000 UTC"
time="2024-06-21T02:57:10Z" level=info msg="NotAfter: 2025-04-16 03:38:05 +0000 UTC"
time="2024-06-21T02:57:10Z" level=info msg="SignatureAlgorithm: SHA256-RSA"
time="2024-06-21T02:57:10Z" level=info msg="PublicKeyAlgorithm: RSA"
time="2024-06-21T02:57:10Z" level=fatal msg="Certificate chain is not complete, please check if all needed intermediate certificates are included in the server certificate (in the correct order) and if the cacerts setting in Rancher either contains the correct CA certificate (in the case of using self signed certificates) or is empty (in the case of using a certificate signed by a recognized CA). Certificate information is displayed above. error: Get \"https://inf-k8s.sha-dc01.metax-tech.com\": tls: failed to verify certificate: x509: certificate signed by unknown authority"

Additional Questions:

Is there a way to bypass the certificate verification for development purposes? I understand this is not recommended for production environments, but it would be helpful to proceed with my current development setup.

Any assistance with resolving this issue would be greatly appreciated. Thank you in advance for your help.

**Comment by starbops** [comment]
Hi @sonic2825 

Is the certificate signed by a private/custom CA?

**Comment by sonic2825** [comment]
My certificate is a private certificate issued by the AD (Active Directory) CA.

**Comment by starbops** [comment]
Did you install Rancher by following [these instructions (the "Certificates from Files" tab)](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster#5-install-rancher-with-helm-and-your-chosen-certificate-option)? You'll have to provide your certificates to Rancher manually (please refer to the [doc](https://ranchermanager.docs.rancher.com/getting-started/installation-and-upgrade/resources/add-tls-secrets) for details). The log indicated a problem with the incompleteness of the server certificate chain.
