### ISSUE TITLE
[BUG] vm's image show "-" which created by use node-driver

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#605]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/112817676-4a011f80-90b5-11eb-8b1c-7d2a956063ed.png)

**To Reproduce**
create a vm by docker-machine-driver-harvester

**Expected behavior**

show image correctly
**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
link to #512

**Comment by TangStone** [comment]
### Validation passed in version v0.2.0-rc3
**Steps**
1. Create Node template
![image](https://user-images.githubusercontent.com/15829074/115358487-4d895180-a1f0-11eb-8b47-bb219fd7afdc.png)
2. Create cluster
![image](https://user-images.githubusercontent.com/15829074/115358563-609c2180-a1f0-11eb-9e45-7ab5802e381e.png)
### vm's image is displayed correctly
![image](https://user-images.githubusercontent.com/15829074/115358237-0733f280-a1f0-11eb-8c71-2f6ad3e4286e.png)
