### ISSUE TITLE
[BUG] Failed to load cluster and vm metrics monitoring graph when provisioned RKE2 cluster from Rancher

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#6059]
**Describe the bug**

When Harvester v1.3.1 integrated with Rancher 2.8.2 and have a v1.27.14 RKE2 downstream cluster provisioned.
After we enable the `rancher-monitoring` and `rancher-logging` addons.

* We found failed to load the Prometheus monitoring diagram for cluster and vm metrics
* Indicate the `Failed to load graph`
    ![image](https://github.com/harvester/harvester/assets/29251855/16c9dc56-8a74-4f8e-808f-2765c53a4f1d)
    
    
    ![image](https://github.com/harvester/harvester/assets/29251855/79bcce29-6905-4b8c-87c2-87f287183725)

* The `prometheus-rancher-monitoring-prometheus-0` pod keeps in `Init` state
    ![image](https://github.com/harvester/harvester/assets/29251855/1f565d6f-e0f4-42e1-8e7e-8a74ed69b707)

* Check the related containers
    ![image](https://github.com/harvester/harvester/assets/29251855/0e8908fb-729a-4f29-9920-91381b0acde4)

* All prompt with the following logs `is waiting to start: PodInitializing for cattle-monitor`
  ```
   stream logs failed container "config-reloader" in pod "prometheus-rancher-monitoring-prometheus-0" is waiting to start: PodInitializing for cattle-monitor │
  │ ing-system/prometheus-rancher-monitoring-prometheus-0 (config-reloader) 
  ```
  ![image](https://github.com/harvester/harvester/assets/29251855/b5d35b5e-9a06-4c73-9500-c881fb033f46)

* Detailed full video recording process

https://github.com/harvester/harvester/assets/29251855/d00d87f3-5cfd-4ba3-aeeb-174a560bd848

**To Reproduce**
1. Import Harvester v1.3.1 to Rancher v2.8.2
2. Provision a v1.27.14 RKE2 guest cluster
3. Go to Harvester Addons settings
4. Enable the `rancher-monitoring` and `rancher-logging` addons.
5. Go to Host page
6. Check the cluster and vm metrics graph 

**Expected behavior**

Can load load cluster and vm metrics monitoring graph when provisioned RKE2 cluster from Rancher

**Support bundle**

[supportbundle_1de2c4e1-125f-41d7-a1b3-6ec5ab3c72d6_2024-06-24T08-04-50Z.zip](https://github.com/user-attachments/files/15953913/supportbundle_1de2c4e1-125f-41d7-a1b3-6ec5ab3c72d6_2024-06-24T08-04-50Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine

**Additional context**
In a clean install Harvester without Rancher integrated.
Tested can load the cluster and vm metrics well.

**Comment by w13915984028** [comment]
@TachunLin You may encounter this https://docs.harvesterhci.io/v1.3/troubleshooting/monitoring#fail-to-enable-rancher-monitoring-addon, if you set only ~250 G disk for the KVM VM which is used as the Harvester node. The workaroud can solve it. thanks.

**Comment by TachunLin** [comment]
Thanks @w13915984028 for sharing the workaround. 

In this case, I set the Harvester node disk to `300Gi` and have a `40Gi` RKE2 guest cluster vm created on it. 
While in the clean install without vm created, there I can enable the monitoring addons and load the cluster/vm metrics 

If that means the RKE2 guest cluster occupy to much spaces which makes the `prometheus-rancher-monitoring-prometheus-0` failed to start?

**Comment by TachunLin** [comment]
I just prepared the same environment on Harvester v1.3.1 with a RKE2 guest cluster vm provisioned on it. (40Gi) 

After applying the workaround in https://docs.harvesterhci.io/v1.3/troubleshooting/monitoring/#workaround

* By changing the monitoring addons yaml content, set the `retentionSize` to `10GiB` and storage to `10Gi`
  ```
          retentionSize: 10GiB
          storageSpec:
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 10Gi
  ```


  ![image](https://github.com/harvester/harvester/assets/29251855/80c435c9-6e0e-4949-95bf-c55e2a6a8f47)

* All the monitoring pods are running well 
  ![image](https://github.com/harvester/harvester/assets/29251855/5e767e38-31b6-4abc-90e7-862478d64527)

* The cluster and vm metrics graph can load correctly
  ![image](https://github.com/harvester/harvester/assets/29251855/cb350f22-1601-43e7-8dab-7a7e55f33bef)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/647a13eb-4851-4383-b2b5-9505405d2bc3)

Thanks @w13915984028 for checking and share the workaround.

**Comment by TachunLin** [comment]
Close this issue as we found the workaround to solve the failed to load graph.

It would be nice and suggested we can have a warning message for user to check at least have `50Gi` free space on the embedded longhorn partition prior to enable the `rancher-monitoring` addons
