### ISSUE TITLE
[FEATURE] [GUI] Optimize upgrade image preloading

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#6060]
**Is your feature request related to a problem? Please describe.**

Original Request https://github.com/harvester/harvester/issues/3059

Currently, the `image preloading` will happen in `NODEs` one by one, for massive-node cluster, it takes long time.

**Describe the solution you'd like**

Preload image to nodes in parallel.
Or allow user to set up an image registry outside of cluster, images will be fetched on demand.
Also consider to allow user to select  `one-by-one`, `multi-in-parallel`, `fetch-on-demand-from-registry` mode.

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
@torchiaf we have the automatically created issue https://github.com/harvester/harvester/issues/6045
I copy the description to that one and closed this one.
