### ISSUE TITLE
[BUG] Minor issue on time synchronization messge

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6067]
**Describe the bug**

If a node can't sync with a NTP server, a message displays but there is a checkbox after the message.
It would also be nice to change the text to "The time is not synchronized with the NTP server."
<img width="483" alt="截圖 2024-06-25 下午5 03 00" src="https://github.com/harvester/harvester/assets/1691518/73d4c3ec-94a4-42dc-9633-3d04724c69c8">

**To Reproduce**
1. Install Harvester.
2. Enter a failing NTP server or put nodes in an air-gapped environment.

**Expected behavior**

No check box at the end.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by irishgordo** [comment]
This looks good on  Harvester v1.4.0-dev-20240719 - thanks for the fix @torchiaf :smile: :+1: 
I'll go ahead and close this out
![Screenshot from 2024-07-29 16-08-54](https://github.com/user-attachments/assets/e4d8f135-f6f8-442a-8673-6b7c5c9906be)
