### ISSUE TITLE
[BUG]x86 and arm harvester 1.3.0 can't delete node on the web interface

### ISSUE THREAD

**Issue by NonoMoh** [harvester/harvester#6069]
x86 and arm harvester 1.3.0 can't delete node on the web interface
too much recursion error  
![1719371538362](https://github.com/harvester/harvester/assets/52237475/b78e1fb0-8c40-4ff0-b7ba-d19e84f17766)

![1719371561519](https://github.com/harvester/harvester/assets/52237475/112cd9ea-c2e4-4137-9d97-f480d7ca44d0)

**Comment by Yu-Jack** [comment]
I think this is related to https://github.com/harvester/harvester/issues/5883

**Comment by Yu-Jack** [comment]
@NonoMoh Could you please provide more details steps how to reproduce? Thank you.
