### ISSUE TITLE
[BUG] Minor issues in the VM backup modal

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#607]
**Describe the bug**

**To Reproduce**
1. Go to Harvester GUI -> Virtual Machines
2. Select a virtual machine and perform "Take Backup" action.
3. The backup modal is displayed:
The modal title is not correct, this is supposed to make a backup, not restore.
![Screen Shot 2021-03-29 at 5 45 02 PM](https://user-images.githubusercontent.com/1691518/112819098-cd6f4080-90b6-11eb-872d-a5ce945c0b5d.png)
The `Name` field should be `required` and perform validation before clicking `Create`.
Otherwise, a request is sent to backend with this error:
![Screen Shot 2021-03-29 at 5 45 10 PM](https://user-images.githubusercontent.com/1691518/112819355-17f0bd00-90b7-11eb-8171-160dcde5ed2c.png)

**Expected behavior**

A error hint should be displayed if `Name` field is empty.

**Log**

**Environment:**
 - Harvester GUI version: https://github.com/rancher/harvester-ui/commit/8d59e3b7436875d86a51ca77bec640dad7a8dd87
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
I can confirm this is already fixed.

**Comment by TangStone** [comment]
### Validation in v0.2.0-rc1
![image](https://user-images.githubusercontent.com/15829074/113370810-68a63580-9397-11eb-906e-48f1823ae629.png)
**Validated**
