### ISSUE TITLE
[BUG] harvester `make ci` failed when verify vm api in local

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#6070]
**Describe the bug**
execute `make ci` in local laptop under harvester master branch, got error as follows.
The verify vm api always failed, and in the kind I found both harvester deployment and harvester node manager not running.
![image](https://github.com/harvester/harvester/assets/4344302/8831d386-43ab-4c7c-a1e1-8e54ede7842b)
![image](https://github.com/harvester/harvester/assets/4344302/1902b7a2-c7b9-4af6-b1d6-463a51d1abcc)
![image](https://github.com/harvester/harvester/assets/4344302/859e01ee-5475-45cd-9cdc-abc828b04aa5)
![image](https://github.com/harvester/harvester/assets/4344302/dbf6fb19-21ea-4e0a-a5d0-89cd0c1d5060)

**To Reproduce**
1. check out harvester master branch
2. execute `make ci`

**Expected behavior**
no error

**Support bundle**
N/A

**Environment**
- harvester master branch
- local laptop

**Additional context**
`make ci` passed in github actions.

**Comment by bk201** [comment]
The error is virt-launcher pod fails with:
```
compute {"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"test-grsvz","namespace":"default","pos":"server.go:202","reason":"virError(Code=1, Domain=1
0, Message='internal error: Failed to start QEMU binary /usr/bin/qemu-system-x86_64 for probing: libvirt:  error : cannot execute binary /usr/bin/qemu-system-x86_64: Operation not permitted
\n')","timestamp":"2024-06-26T07:46:15.346012Z","uid":"e4ec1043-d9ce-4246-b672-f554e9a00169"}
```

Per @Vicente-Cheng's investigation, adding `Root` feature to kubevirt object is a workaround. We don't know why the CI pass in GHA runners yet.

**Comment by Vicente-Cheng** [comment]
For now, we can disable the following apparmor for the local tests.

```
// on host side
# aa-disable /etc/apparmor.d/usr.sbin.libvirtd
# aa-disable /etc/apparmor.d/usr.sbin.virtqemud
```

But I am not sure if there is another way to give the correct permission, or if we need to disable that.

**Comment by Vicente-Cheng** [comment]
I added the test to check our GHA configuration for AppArmor and looks like the AppArmor is disabled on that.
PR (only for checking): https://github.com/harvester/harvester/pull/6075 
Action: https://github.com/harvester/harvester/actions/runs/9678919059/job/26703719522
So, that's why the GHA can run `make ci` successfully.

I will comment on our script to provide tips we need to disable the `virtqemud`
Then we can close this one. WDYT?

cc @brandboat, @bk201

**Comment by brandboat** [comment]
> I added the test to check our GHA configuration for AppArmor and looks like the AppArmor is disabled on that.
PR (only for checking): https://github.com/harvester/harvester/pull/6075
Action: https://github.com/harvester/harvester/actions/runs/9678919059/job/26703719522
So, that's why the GHA can run make ci successfully.

Interesting, thanks for confirming !

> I will comment on our script to provide tips we need to disable the virtqemud
Then we can close this one. WDYT?

I'm fine with this one, perhaps we could also add some description to https://github.com/harvester/harvester/blob/master/tests/README.md.
