### ISSUE TITLE
[BUG] Changing the image does not take effect. (nodeDriver)

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#609]
**Describe the bug**

Changing the image of an existing template does not take effect

**To Reproduce**

1. Switch to rancher ui
2.  Add a harvester node driver
3. Click global 
4. Click Add Cluster, Choose harvester
5. add template => save
6. Delete all images in the harvester ui
7. Add an image
7. Modify the template just created in rancher ui，  => Select image
8. Check the template api, check whether the image value has changed

**Expected behavior**
Hope this image value changes

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DoNotSayYes** [comment]
Validated on master-head
