### ISSUE TITLE
[BUG] Images ignores dataLocality of storageClass

### ISSUE THREAD

**Issue by SnelsSM** [harvester/harvester#6091]
Hi!
When I create a new image and select a StorageClass, the new StorageClass for that image ignores the longhorn parameters.

**Steps to reproduce the behavior:**
1. Create a new StorageClass
2. Add parameter dataLocality: best-effort, strict-local etc...
3. Create a new image and select the newly created StorageClass
4. The Longhorn parameters for the image have been lost
5. New virtual machines created using this image have also lost parameters...

**Expected behavior**
The Longhorn parameters defined in the StorageClass must be reused when creating the image.
The same parameters must be reused when creating a VM from this image.

**Environment**
 - Harvester ISO version: 1.2.1

**Additional context**
If attach an extra volume to VM using the StorageClass with defined longhorn parameters, everything will work fine.
But not everyone needs extra volumes.

**Comment by SnelsSM** [comment]
By the way, more... If the problem with using strict-local is only in migrating virtual machines when updating Harvester, then maybe just stop such virtual machines instead of migrating?

**Comment by WebberHuang1118** [comment]
Hi @SnelsSM 
Harvester supports data locality for images since v1.3.0 https://docs.harvesterhci.io/v1.3/advanced/storageclass#data-locality-settings.

And Harvester doesn't support strict-local because it can affect certain operations such as [VM Live Migration](https://docs.harvesterhci.io/v1.3/vm/live-migration)

**Comment by SnelsSM** [comment]
@WebberHuang1118 

> And Harvester doesn't support strict-local because it can affect certain operations such as VM Live Migration

But  live migration is not always necessary. Why not just turn off such virtual machines if live migration is not required?

**Comment by WebberHuang1118** [comment]
@SnelsSM 

Strict local makes LH volume have one local replica only, however, live migration is required for the Harvester upgrade.
And one replica also reduces the data availability.

**Comment by SnelsSM** [comment]
> Strict local makes LH volume have one local replica only, however, live migration is required for the Harvester upgrade.
> And one replica also reduces the data availability.

A single replica without defined dataLocality also disrupts the operation of some virtual machines when upgrading Harvester, and live migration in this case is pointless.
It might be better to be able to customize the upgrade strategy for Harvester: force live migrate, live migrate if possible, shutdown VMs, etc...
Too many cases when VMs exists just for temporary workload. There is no point migrating virtual machines on upgrade when stopping these virtual machines is acceptable.

As a bonus, it will be possible to use strict-local painlessly, load the network less and have better volume performance. Profit.

**Comment by WebberHuang1118** [comment]
> It might be better to be able to customize the upgrade strategy for Harvester: force live migrate, live migrate if possible, shutdown VMs, etc...

@SnelsSM Thanks for your suggestion, we will discuss on it.

Just have some clarification:

> A single replica without defined dataLocality also disrupts the operation of some virtual machines when upgrading Harvester, and live migration in this case is pointless.

> As a bonus, it will be possible to use strict-local painlessly, load the network less and have better volume performance. Profit.

The single replica doesn't disrupt live migration, and if you want to avoid network overhead, considering make use of data locality with `best-effort`. As a result, LH will always try to build a local replica.
