### ISSUE TITLE
[BUG] Can`t upgrade cluster from v1.2.1 to v1.2.2  

### ISSUE THREAD

**Issue by DrKivz** [harvester/harvester#6095]
**Describe the bug**
Can`t upgrade Cluster 
admission webhook "validator.harvesterhci.io" denied the request: machine fleet-local/custom-fb95dfe58f89 is not running

**To Reproduce**
1. Go to Dashboard->Upgrade->Select v1.2.2->Click upgrade

**Expected behavior**
Starting upgrade.

**Support bundle**
[supportbundle_2a61ebea-0c94-42f2-b8fa-038613794980_2024-06-29T13-57-59Z.zip](https://drive.google.com/file/d/1RZFDwUkpoGDrya5Im1OLtzIcUDik9Xg1/view?usp=sharing)

**Environment**
 - Harvester ISO version:  v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
None

**Comment by Yu-Jack** [comment]
@DrKivz 

Your `machine.cluster.x-k8s.io/v1beta1` and `node` resources are mismatched, you could try to delete those machines which are in `Provisioning` phase to recover state.  

I also found there is a message `waiting for probes: calico, kubelet` in `machine.cluster.x-k8s.io/v1beta1`, seem like there is a rke2 installation failed here. Do you have any failed jobs?

**Comment by DrKivz** [comment]
![image](https://github.com/harvester/harvester/assets/50614467/4cba3c2d-fa02-4dd6-b0c6-aefb4cea09c8)
no failed jobs
