### ISSUE TITLE
[BUG] Unable to install cloud-provider in fully running with csi-driver on the imported cluster in Rancher v2.9.0-alpha5 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#6099]
**Describe the bug**

Given we already have a imported `v1.29.5` RKE2 cluster from Harvester in Rancher 
After we manually install the latest csi-driver `0.1.7` and cloud provider `0.2.4` from the chart market  

* Then try to install the dhcp type load balancer service, it would stuck in `Pending` state
  ![image](https://github.com/harvester/harvester/assets/29251855/6a1c8198-15fa-4572-9cab-e8cd3af2dc5a)

* Check the harvester-cloud-provider application, it was not fully deployed and running
  ![image](https://github.com/harvester/harvester/assets/29251855/72520acb-a2ef-4cf8-80b7-9db6303dc017)

* The harvester-cloud-provider deployment failed with `Crashloopbackoff` failure
  ![image](https://github.com/harvester/harvester/assets/29251855/253d7a4d-1050-44c6-900d-f9fb4707ef7f)
  
  ![image](https://github.com/harvester/harvester/assets/29251855/2481c0bd-3553-4a3a-9c53-f110f220de44)

**To Reproduce**
#### Pre-requisite 
1. Use helm to provision the Rancher `v2.9.0-alpha5` 
   - Repo url: https://releases.rancher.com/server-charts/alpha
2.  Create a v1.3.1 Harvester cluster 
3.  Import Harvester to Rancher 

#### steps to import RKE2 cluster in Rancher
* Refer to https://github.com/harvester/tests/issues/1312#issuecomment-2159649815 

  <details><summary>Detailed steps</summary>
  1. On Harvester, prepare KUBECONFIG with harvester VIP as server
  
    ```
       rancher@harvester-node-0:~> cp /etc/rancher/rke2/rke2.yaml ~/.kube/config/rke2.yaml ^C
       rancher@harvester-node-0:~> vim ~/.kube/config/rke2.yaml ^C
       rancher@harvester-node-0:~> head ~/.kube/config/rke2.yaml 
       apiVersion: v1
       clusters:
       - cluster:
           ...
           server: https://192.168.0.131:6443       <-- Modify to Harvester VIP
         name: default
       contexts:
       - context:
           cluster: default
           user: default
      ...
    ```
  
  
  2. On Harvester with KUBECONFIG, create VM with pre-gen cloud-provider & csi-driver cloud-config
     Pre-gen cloud-provider cloud-config
      ```
       rancher@harvester-node-0:~> echo $KUBECONFIG 
       /home/rancher/.kube/config/rke2.yaml
       rancher@harvester-node-0:~> curl -sfL https://raw.githubusercontent.com/harvester/cloud-provider-harvester/master/deploy/generate_addon.sh | bash -s myrke2-import-test3 default
       ...
       Creating a clusterrolebinding myrke2-import
       ...
       
       ########## cloud-init user data ############
       write_files:
         - encoding: b64
           content: 
       owner: root:root
       path: /etc/kubernetes/cloud-config
       permissions: '0644'
      ```
      Pre-gen csi-driver cloud-config
    
        ```
         rancher@harvester-node-0:~> echo $KUBECONFIG 
         /home/rancher/.kube/config/rke2.yaml
         rancher@harvester-node-0:~> curl -sfL https://raw.githubusercontent.com/harvester/harvester-csi-driver/master/deploy/generate_addon_csi.sh | bash -s myrke2-import-test3 default RKE2
         ...
         Creating a service account in default namespace: myrke2-import
         ...
         
         ########## cloud-init user data ############
         write_files:
           - encoding: b64
             content: 
             owner: root:root
             path: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
             permissions: '0644'
        ```

  3. Create VM with pre-gened cloud-config
  
  4. SSH to VM and setup RKE2 manually
      - Setup and enable RKE2 service
        ![image](https://github.com/harvester/harvester/assets/29251855/3a89d1f4-006e-4352-9dc4-925788bae958)
      - Check RKE2 is Running
        ![image](https://github.com/harvester/harvester/assets/29251855/c8f29b39-e37e-4c9b-a2ba-d4da6df66c81)

  
  5. On Rancher, Go to Cluster Management -> Import Existing -> Generic
      - In Agent Environment Vars, add cattle-cluster-agent as `preferredDuringSchedulingIgnoredDuringExecution`
      - Follows commands in previous step to join VM.
    
        ![image](https://github.com/harvester/harvester/assets/29251855/8bdf2259-d3d8-444f-badc-47bf6749a77c)

  6. Install the latest Harvester csi-driver from chart
  
    ![image](https://github.com/harvester/harvester/assets/29251855/0312a98c-2dc6-483f-8c8e-5fcf0f6e1aba)

  7. Install the latest Harvester cloud-provider from chart 
  
    ![image](https://github.com/harvester/harvester/assets/29251855/d7ce7e33-1f06-4f73-8b0d-d96cf72a61ee)

  8. Create a dhcp load balancer service and check the state
  9. Back to application, check the harvester-cloud-provider deployment state

  </details>

**Expected behavior**

Can install both the csi-drirver and cloud-provider on the imported RKE2 cluster and create load balancer service routing well. 

**Support bundle**

[supportbundle_a94a8926-f7b3-4f92-937f-4cbcb56bc9a1_2024-07-01T11-54-02Z.zip](https://github.com/user-attachments/files/16052845/supportbundle_a94a8926-f7b3-4f92-937f-4cbcb56bc9a1_2024-07-01T11-54-02Z.zip)

**Latest Support bundle (24/07/04)**
[supportbundle_a94a8926-f7b3-4f92-937f-4cbcb56bc9a1_2024-07-04T07-57-08Z.zip](https://github.com/user-attachments/files/16095320/supportbundle_a94a8926-f7b3-4f92-937f-4cbcb56bc9a1_2024-07-04T07-57-08Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Rancher version: v2.9.0-alpha5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single nodes on baremetal machine
 - RKE2 version: v1.29.5+rke2r1

**Comment by starbops** [comment]
Looks like the same as #5332

Please disable the default CCM that the guest RKE2 brings up. After that, the harvester-cloud-provider pods should be able to run without issue (because they compete for the same port).

**Comment by TachunLin** [comment]
Thanks @starbops for sharing the workaround in https://github.com/harvester/harvester/issues/5332#issuecomment-1990877923

I review the entire import RKE2 cluster process and rebuild it again
This time remember to add the `disable-cloud-controller: true` in `/etc/rancher/rke2/config.yaml`

  ```
  root@rke2-import-test:~# cat /etc/rancher/rke2/config.yaml
  token: my-shared-secret
  tls-san:
    - my-kubernetes-domain.com
    - another-kubernetes-domain.com
  disable-cloud-controller: true
  ``` 

This time the cloud provider and csi-driver application are installed and all running well 
  ![image](https://github.com/harvester/harvester/assets/29251855/dc895753-3d34-486f-bc00-895db734c7a3)
  ![image](https://github.com/harvester/harvester/assets/29251855/7306a92d-3bc6-44ec-9023-ae31eed260b5)

But after create the dhcp type load balancer, it still stuck in `Pending` with message
![image](https://github.com/harvester/harvester/assets/29251855/585b1dab-9a81-4979-943f-c2b113d26fcf)

The event indicate message `update load balancer IP of service default/lb-dhcp failed, error: timeout waiting for IP address` 
![image](https://github.com/harvester/harvester/assets/29251855/559bbd06-e953-4861-a185-2d3c0a77239f)

**Comment by starbops** [comment]
Hi @TachunLin 

These two LB-type service objects are not created in the `DHCP` IPAM mode. I cannot find any annotations from the service objects indicating they are.

```sh
> kubectl get services lb-dhcp -o yaml
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2024-07-03T06:14:16Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: lb-dhcp
  namespace: default
  resourceVersion: "37312"
  uid: bb72408d-7906-4faf-baf9-443e629247d5
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.101.230
  clusterIPs:
  - 10.43.101.230
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: myport
    nodePort: 31257
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    test: test
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

Normally, it should look like the following:

```sh
> kubectl get services lb-dhcp -o yaml
apiVersion: v1
kind: Service
metadata:
  annotations:
    cloudprovider.harvesterhci.io/ipam: dhcp
    kube-vip.io/loadbalancerIPs: 0.0.0.0
  creationTimestamp: "2024-07-04T03:01:49Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  name: lb-dhcp
  namespace: default
  resourceVersion: "9592"
  uid: 1da24638-876b-42ca-9ebc-70d4fd342615
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.43.222.167
  clusterIPs:
  - 10.43.222.167
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: myport
    nodePort: 31167
    port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: blog
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
```

From the service creation page of the Rancher dashboard, the "Add-on Config" tab is missing:

![image](https://github.com/harvester/harvester/assets/1827717/b7ddf2d7-7b62-4faf-ad77-0e5e67b6ddaa)

This is from the guest cluster of my machines:

![image](https://github.com/harvester/harvester/assets/1827717/48674087-4a1d-4af7-9839-6eca6898301f)

After manually adding those missing annotations to the `lb-dhcp` service object, the Harvester load balancer and kube-vip can successfully get the DHCP IP address. So, the backend is still working fine; we just need to find out why the tab is missing on the UI.

**Comment by w13915984028** [comment]
@TachunLin Do you have the new support-bundle file from Harvester cluster of the latest try? There may have some useful information.

**Comment by w13915984028** [comment]
The new support-bundle gives further proof:

The LB on Harvester side assumes this is to allocate IP from a pool, however the pool name is not set and no default pool is matched, it failed.

But the initial target is to get IP from DHCP, in the guest cluster directlys, and just as @starbops said, the related DHCP mode information was not added to service object.

> 2024-07-04T02:14:22.122973939Z time="2024-07-04T02:14:22Z" level=error msg="error syncing 'default/rke2-import-test-default-lb-dhcp-9818d82f': handler harvester-lb-controller: allocate ip for lb default/rke2-import-test-default-lb-dhcp-9818d82f failed, error: fail to select the pool for lb default/rke2-import-test-default-lb-dhcp-9818d82f, error: no matching IP pool with requirement &{Network: Project:c-m-99p68n4t/p-z4gnl Namespace:default Cluster:rke2-import-test}, requeuing"

> 2024-07-04T07:53:18.797640278Z time="2024-07-04T07:53:18Z" level=error msg="error syncing 'default/rke2-import-test-default-lb-dhcp2-f715dc92': handler harvester-lb-controller: allocate ip for lb default/rke2-import-test-default-lb-dhcp2-f715dc92 failed, error: fail to select the pool for lb default/rke2-import-test-default-lb-dhcp2-f715dc92, error: no matching IP pool with requirement &{Network: Project:c-m-99p68n4t/p-z4gnl Namespace:default Cluster:rke2-import-test}, requeuing"

fetch ipam from service object, if no, default to `pool`
https://github.com/harvester/cloud-provider-harvester/blob/5e276ec8e6da55cd0bf3620a832c02d2f9b468c9/pkg/cloud-controller-manager/loadbalancer.go#L244

ip allocation
https://github.com/harvester/load-balancer-harvester/blob/0025da293f105cc500a27795249e4f952d80adcd/pkg/controller/loadbalancer/controller.go#L187

from pool
https://github.com/harvester/load-balancer-harvester/blob/0025da293f105cc500a27795249e4f952d80adcd/pkg/controller/loadbalancer/controller.go#L219

**Comment by starbops** [comment]
The same issue happened in previous versions and was raised by @albinsun 
https://github.com/harvester/harvester/issues/5345#issuecomment-2158472395

**Comment by TachunLin** [comment]
I think we can close this issue since we can correctly install cloud-provider and csi-driver on the imported RKE2 cluster.
And track the missing Add-on config page behavior on the new issue #6122
