### ISSUE TITLE
[BUG] Restore from the VM Menu (after power off) shows snapshot options but it may be created for Backups.

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#6109]
**Describe the bug**
After a VM is powered Off, I can try and restore but the Menu shows as if it's for "Backups" but the snapshots are also listed.

**To Reproduce**
1. Take a snapshot of the VM
2. Power Off the VM
3. On the VM Menu, select Restore, the Menu shows "backups" and selecting a snapshot will fail to restore.

**Expected behavior**
Restoring snapshots should work, and the list should clarify it is for both Snapshots and Backups.

**Environment**
 - Harvester ISO version: 1.3.0

**Comment by Yu-Jack** [comment]
I'd like to check some details.

1. Did you have any error message when selecting a snapshot?
2. Did you restore after vm is fully stopped or is stopping?

Thank you.
