### ISSUE TITLE
[BUG] empty error message on VLAN network init setup

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#611]
**Describe the bug**

**To Reproduce**
1. Go to the network setting and enable the default NIC to eth0
2. go to the networks page
3. empty error message appears

**Expected behavior**
handle the message correctly

**Log**

![image](https://user-images.githubusercontent.com/4569037/112931202-3fdf2f80-914e-11eb-86e1-5a4b119b3397.png)

**Environment:**
 - Harvester ISO version:  master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
### Verification passed in master-a720ef1b-head
![image](https://user-images.githubusercontent.com/15829074/113826619-f6798a80-97b4-11eb-9af4-20cbdfeb621d.png)
