### ISSUE TITLE
[BUG] Click Save button will not redirect to Hosts page

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#6116]
### Describe the bug
Click `Save` button will not redirect to hosts page (But the change has been applied)
![image](https://github.com/harvester/harvester/assets/5169694/565ebf56-357f-4db8-8a4d-1b6a5cb49fe0)

### To Reproduce
1. Install Harvester with any nodes
2. Navigate to Hosts page
3. edit one of hosts
4. Click Save button

### Expected behavior
UI should redirect to hosts page

## Environment:
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 2 nodes (1 witness)**
 - Harvester ISO version: **master-25937fe-head**
 - **ui-source** Option: **Auto**

### Additional context
ref to https://github.com/harvester/harvester/issues/5325#issuecomment-2205097163

### Support bundle
N/A

**Comment by a110605** [comment]
I think this issue is duplicated to https://github.com/harvester/harvester/issues/5326.
I will verify once my fixed PR merged :  https://github.com/harvester/harvester/issues/6116

**Comment by lanfon72** [comment]
Let's track this on #5326
