### ISSUE TITLE
[BUG]Node name can not be updated after migration

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#612]
**Describe the bug**

**To Reproduce**

1. migrate a vm
2. the node name on vm list can not be updated after migration.

**Expected behavior**

1. the node name can be updated

**Comment by DaiYuzeng** [comment]
#384

**Comment by kingsd041** [comment]
Validated on v0.2.0-rc1

Steps:
1. Create VM
2. Migrate VM
3. Wait for the migration to succeed, go to the VM Basics page, and check Node

Result:
`Node` updated to the correct node
