### ISSUE TITLE
[ENHANCEMENT] Bump Kubevirt to 1.1.1-150500.8.18.1

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6131]
**Is your enhancement related to a problem? Please describe.**

Bump Kubevirt to 1.1.1-150500.8.18.1

**Describe the solution you'd like**

Bump Kubevirt to 1.1.1-150500.8.18.1

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
Validated in master-09f3ca1-head. Version was rolled for virt-api, virt-controller, and virt-handler.
