### ISSUE TITLE
[BUG] Managed DHCP VMs do not show IP address in UI or CLI

### ISSUE THREAD

**Issue by wichitalineman** [harvester/harvester#6146]
**Describe the bug**
We have enabled the experimental Manged DHCP add-on in Harvester and configured it with internal subnets following the instructions here: https://docs.harvesterhci.io/v1.3/advanced/addons/managed-dhcp/

VMs spin up and are assigned appropriate IPs in the subnet, and are properly routed through our network. The issue is that the assigned IP address for the VM is not shown in the UI, it is blank, and from kubectl we see and ip address from the management network. Users have to open WebVNC, log into the instance, and pull the IP address manually.

**To Reproduce**
1. Enabled Experimental Managed DHCP
2. Create VM network:

apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    network.harvesterhci.io/route: >-
      {"mode":"manual","cidr":"10.91.231.0/24","gateway":"10.91.231.254","connectivity":"true"}
  finalizers:
    - wrangler.cattle.io/harvester-network-nad-controller
    - wrangler.cattle.io/harvester-network-manager-nad-controller
  generation: 1
  labels:
    network.harvesterhci.io/clusternetwork: vm-network
    network.harvesterhci.io/ready: 'true'
    network.harvesterhci.io/type: L2VlanNetwork
    network.harvesterhci.io/vlan-id: '2074'
  name: vlan-2074
  namespace: default
spec:
  config: >-
    {"cniVersion":"0.3.1","name":"vlan-2074","type":"bridge","bridge":"vm-network-br","promiscMode":true,"vlan":2074,"ipam":{},"mtu":9000}

3. Add network-pool from kubectl

apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  name: vlan-2074
  namespace: default
spec:
  ipv4Config:
    serverIP: 10.91.231.1
    cidr: 10.91.231.0/24
    pool:
      start: 10.91.231.5
      end: 10.91.231.49
    router: 10.91.231.254
    dns:
    - 10.0.0.1
    leaseTime: 300
  networkName: default/vlan-2074

4. Create VM on the vlan-2074 network 

5. After VM comes up UI shows a blank IP address:

<img width="1557" alt="Screenshot 2024-07-09 at 9 48 34 AM" src="https://github.com/harvester/harvester/assets/19436761/cdda523a-5a61-4f3d-9d58-ba565e84a4e4">

<img width="1304" alt="Screenshot 2024-07-09 at 9 48 26 AM" src="https://github.com/harvester/harvester/assets/19436761/695cf71f-bb8c-4850-976a-e556030498e5">

6. Kubectl provide this address, which is not accessible to anything inside or outside Harvester:

default                           virt-launcher-restore-from-snap-2hc9q                             2/2     Running     0               22m     **10.52.0.132**     test-harvester-master-01   <none>           1/1

7. Opening the WebVNC console to the VM and running `ip a` provide the correct IP address:

[root@localhost ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 9000 qdisc fq_codel state UP group default qlen 1000
    link/ether 9e:0e:98:97:3c:2e brd ff:ff:ff:ff:ff:ff
    inet **10.91.231.29/24** brd 10.91.231.255 scope global dynamic noprefixroute enp1s0
       valid_lft 182sec preferred_lft 182sec
    inet6 fe80::9c0e:98ff:fe97:3c2e/64 scope link noprefixroute
       valid_lft forever preferred_lft forever

8. User can then SSH into VM with the correct address as expected.

Note: As an Admin I can view the pool information and the virtual network information, but not something that users will be able to do:

kka get ippools.network
NAME        NETWORK             AVAILABLE   USED   REGISTERED   CACHEREADY   AGENTREADY   AGE
vlan-2074   default/vlan-2074   40                  5          True                True         True         21h

kka get virtualmachinenetworkconfigs.network restore-from-snap -o yaml
....
status:
  conditions:
  - lastUpdateTime: "2024-07-09T13:30:27Z"
    status: "True"
    type: Allocated
  - lastUpdateTime: "2024-07-09T13:29:50Z"
    status: "False"
    type: Disabled
  networkConfigs:
  - allocatedIPAddress: 10.91.231.29
    macAddress: 9e:0e:98:97:3c:2e
    networkName: default/vlan-2074
    state: Allocated

**Expected behavior**
After VM is created the IP address provided from the Managed DHCP will show in the UI and kubectl to avoid the exit steps to get the address.

**Environment**
 - Harvester ISO version: 1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal SM

**Comment by bk201** [comment]
@wichitalineman Thanks for the report. Can you help provide:
- The image to provision the volume. (If it's a public cloud image). Or tell us the image type.
- It seems the VM gets the IP correctly, can the VM access the Internet?
- Output of VM's VMI. `kubectl get vmi -A` to get all VMIs, and you can dump the the corresponding VM's VMI with `kubectl get vmi -n <ns> <vm_vmi> -o yaml`.

**Comment by starbops** [comment]
Hi @wichitalineman, Do you have qemu-guest-agent running on the VM? The agent must be running for the underlying Harvester to know its IP address.

**Comment by Yu-Jack** [comment]
~~Provide some information. One of reasons might be related the UI? Current [code base](https://github.com/harvester/dashboard/blob/a0ef90a5a050190e7a9355df4a67a1cdd194120e/pkg/harvester/formatters/HarvesterIpAddress.vue#L71-L88) only fetches the `interface.ipAddress`. This is difference between them in vmi CR.~~ 

After install qemu-guest-agent, it shows IP.

**Comment by bk201** [comment]
Please check if the above comments help, and reopen if needed.
