### ISSUE TITLE
[Doc] Improve the Rancher integration doc

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#6147]
Currently, Rancher integration document mention most of the informations needed for a user to get started with but lacks few things as below
1. Guest cluster can be created in few ways as below
    a. Node driver (mentioned)
    b. Custom cluster (mentioned in cloud provider page only)
    c. Using Rancher terraform (not mentioned)
    d. Import existing cluster (Not mentioned)
2. Disabling & Enabling(By default) cloud provider & csi driver chart deployment in Rke2 cluster.
3. Upgrading charts in guest cluster

**Comment by krumware** [comment]
I'd also like to suggest that node image preparation is currently skipped over, and isn't very clear. (setup requirements for a VM image to be ready to be used with node pools / cluster creation)

**Comment by w13915984028** [comment]
@khushboo-rancher @krumware thanks for your kind reminder, we will update those parts in v1.4.0.

FYI @Vicente-Cheng @FrankYang0529 @starbops @jillian-maroket

**Comment by FrankYang0529** [comment]
Thanks for the issue. I will handle this.

**Comment by khushboo-rancher** [comment]
Details are updated in the rancher section - https://docs.harvesterhci.io/v1.4/rancher/rancher-integration
