### ISSUE TITLE
[BUG] Error ui jump on vm events page

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#615]
**Describe the bug**

**To Reproduce**
1. on vm events page
2. click next page button, then navigate to the vm detail page again, not navigate  to the next page
![image](https://user-images.githubusercontent.com/15064560/112973879-5e601d80-9184-11eb-94c4-4b09f1b3e7c7.png)
![image](https://user-images.githubusercontent.com/15064560/112974129-b008a800-9184-11eb-8f3d-d2ac6972c8cd.png)

**Expected behavior**

navigate to next events page

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Fix in the master-a720ef1b-head version, click the next page button, it will jump to the next page correctly
