### ISSUE TITLE
[ENHANCEMENT] Enhance wording on the error message when insufficient kubelet image garbage collection when triggering upgrade

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6155]
We should
1. Enhance error message to let user know it's a estimated value thus avoid confusion.
2. Provide document or hint about how to fix (eg. purge unused images)

Note that we hit 2 cases:
1. `higher than kubelet image garbage collection threshold`
   ![image](https://github.com/harvester/harvester/assets/2773781/52c1c59c-8bb0-496d-a5a3-ec1488b8b331)
1. `df -h /usr/local`
   ![image](https://github.com/harvester/harvester/assets/2773781/3544a06a-69f9-410a-bbd5-cd1b90edb593)

# DEPRECATED, PLEASE IGNORE FOLLOWING
**Describe the bug**
During reproduce harvesterharvester/issues/6041 and trigger `v1.2.2` -> `v1.3.1` upgrade but it 's denied by
```
admission webhook "validator.harvesterhci.io" denied the request: Node "harvester-4qqjh" uses 88.336050% storage space. It's higher than kubelet image garbage collection threshold 85.000000%.
```
![image](https://github.com/harvester/harvester/assets/2773781/edafcc15-4951-4db1-a95d-92383cb8a3b5)

But the node's partitions (also `/var/lib/kubelet` mounted as `/usr/local`) looks ok and does not over `85%` threshhold.
![image](https://github.com/harvester/harvester/assets/2773781/655ae136-243b-4690-ad90-2786d2f2a49b)

CC @TachunLin 

**To Reproduce**
1. Setup `v1.1.3` 4 nodes cluster
4. Join Harvester to Rancher `v2.8.5` (But not create any guest cluster)
5. Create 2 VMs, both with 2 volumes (1 default and 1 customized)
6. Upgrade to `v1.2.1`
7. Create a 3 nodes RKE2 guest cluster
8. Upgrade to `v1.2.2`
9. Upgrade to `v1.3.1` :x: 
   ![image](https://github.com/harvester/harvester/assets/2773781/edafcc15-4951-4db1-a95d-92383cb8a3b5)

**Expected behavior**
1. Can trigger upgrade cuz from user aspect the problem node has no partition over `85%` usage.
2. If the space calculation way is not simply checking `/usr/local` and perhaps we sould document or hint somewhere.

**Support bundle**
[supportbundle_denyUpgradeBySpace_2024-07-11T01-28-53Z.zip](https://github.com/user-attachments/files/16170397/supportbundle_denyUpgradeBySpace_2024-07-11T01-28-53Z.zip)

**Environment**
* _harvester-`v1.2.2`_ -> _harvester-`v1.3.1`_
  * Profile: 4 nodes QEMU/KVM (24C/128G/2T)
  * ui-source: `Auto`
* _rancher-`v2.8.5`_
  * Profile: Docker on QEMU/KVM (8C/32G)
  * Guest Cluster: 3 nodes `v1.27.14+rke2r1`

**Additional context**
n/a

**Comment by TachunLin** [comment]
Verified **fixed** on `master-0e15f01-head` (24/09/18). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade when one of the node have insufficient space on the /usr/local  $~~$</summary>

  1. When one of the node have use more than 85% space on the /usr/local
  ```
  harvester-node-0:/usr/local # df -h /usr/local
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/vda5       147G  121G   20G  87% /usr/local
  ```
  2. Trigger upgrade will be blocked with the enhanced message 

  ![image](https://github.com/user-attachments/assets/09f1f8b4-df19-4709-86d7-886effdfb55f)


  https://github.com/user-attachments/assets/3a4808d9-d2dc-409e-9370-4f3e9b38dcfa


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade when multiple nodes have insufficient space on the /usr/local   $~~$</summary>

  1. When two of the node have use more than 85% space on the /usr/local

    ```
    harvester-node-0:/usr/local # df -h /usr/local
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda5       147G  121G   20G  87% /usr/local
    
    harvester-node-2:~ # df -h /usr/local
    Filesystem      Size  Used Avail Use% Mounted on
    /dev/vda5       147G  122G   18G  88% /usr/local
    ```


  2. Trigger upgrade will be blocked with the enhanced message, indicate the last node have used more than 85% of the space

  ![image](https://github.com/user-attachments/assets/2fd8a148-7e3b-4c09-a754-cded9fa5d293)
  
  
  https://github.com/user-attachments/assets/084109fe-70df-458c-8c8b-e3134c8e4056


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Upgrade when all nodes have enough space on the /usr/local    $~~$</summary>

  1. When all of the node have used less than 85% space on the /usr/local

  ```
  harvester-node-0:/usr/local # df -h /usr/local
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/vda5       147G   22G  118G  16% /usr/local
  
  harvester-node-1:~ # df -h /usr/local
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/vda5       147G   25G  115G  18% /usr/local
  
  harvester-node-2:/usr/local # df -h /usr/local
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/vda5       147G   18G  122G  13% /usr/local
  
  
  harvester-node-3:~ # df -h /usr/local
  Filesystem      Size  Used Avail Use% Mounted on
  /dev/vda5       147G   21G  119G  15% /usr/local
  ```

  2. We can trigger the upgrade correctly  

  https://github.com/user-attachments/assets/05b56330-4ccc-4539-8d5a-6d7468593fc0



 </details>

### Test Information
* Test Environment: Three nodes harvester on kvm machines
* Harvester version:  `master-0e15f01-head` (24/09/18)

### Verify Steps
<details><summary> Check disk space usage before upgrade </summary>

  1. Prepare three nodes Harvester v1.4.0-head cluster, each have 250Gi disk
  2. Access node 1 machine of the Harvester cluster
  3. Run the dd command to occupy space on /usr/local 
  ```
  dd if=/dev/zero of=/usr/local/test.img bs=1G count=93
  ```
  4. Ensure the space usage of /usr/local have exceed 85% 
  ```
  df -h /usr/local
  ```
  5. Prepare the offline upgrade yaml to v1.4.0-head 
  6. Trigger the upgrade
  7. Check the blocked message content 
  8. Repeat the steps to use more than 85% of the /usr/local space on other nodes 
  9. Trigger the upgrade again 
  10. Check the blocked message content
  11. Delete all the created image file from dd command on each nodes
  12. Ensure all nodes have less than 85% usage on the /usr/local folder 
  13. Trigger the upgrade again 
  14. Check can trigger the upgrade correctly

</details>
