### ISSUE TITLE
[TASK] Bump Harvester component minor versions for v1.4

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6158]
Bump Harvester components' minor version x.y.z to x.y+1.z in v1.4.

cc @tserong 

### Charts

| Done |  | v1.3-head  | v1.4-head | Owner |
|---|---|---|---|---|
| 🟢 | harvester-network-controller  |  0.4.0 |  0.5.1 | @mingshuoqiu  |
| 🟢 | harvester-node-disk-manager | 0.6.0  | 0.7.2  | @Vicente-Cheng |
| 🟢 | harvester-load-balancer |  0.3.0 | 0.4.0 |  @w13915984028 |
| 🟢 | harvester-node-manager |  0.2.3 | 0.3.1 | @brandboat  | 
| 🟢 | (add-on) pcidevices-controller | 0.3.2 | 0.4.1 | @Yu-Jack   |
| 🟢 | (add-on) seeder | 0.3.0 | 0.4.0 | @starbops   |
| 🟢  | (add-on) vm-import-controller | v0.3.0 | 0.4.0 | @ibrokethecloud  |
|  | (add-on) nvidia-driver-runtime | v0.1.1 | 0.2.0 | @ibrokethecloud  |
|  | (add-on) vcluster | | | Experimental add-on |
|  | (add-on) harvester-vm-dhcp-controller | | | Skip, Experimental add-on |

> **How to bump a chart**
> - Fork and clone https://github.com/harvester/charts.
> - Check out a local branch from the `release` branch.
> - Modify a chart's version in the `Chart.yaml` file.
> - Create a PR to merge the change to the `release` branch.
> - A new chart version will be published once the PR is merged.
> - Sample PR: https://github.com/harvester/charts/pull/242

### Images

|Done|   | v1.3-head | v1.4-head  | Owner |
|---|---|---|---|---|
| 🟢 | harvester-network-controller  |  0.4.0 |  0.5.1 | @mingshuoqiu  |
| 🟢 | harvester-node-disk-manager | 0.6.0  | 0.7.1  | @Vicente-Cheng |
| 🟢 | harvester-load-balancer |  0.3.0 | 0.4.1 |  @w13915984028 |
| 🟢 | harvester-node-manager |  0.2.1 | 0.3.0 | @brandboat  | 
| 🟢 | (add-on) pcidevices-controller | 0.3.2 | 0.4.0 | @Yu-Jack   |
| 🟢 | (add-on) seeder | 0.3.0 | 0.4.0 | @starbops   |
| 🟢  | (add-on) vm-import-controller | v0.3.0 | 0.4.0 | @ibrokethecloud  |
|  | (add-on) nvidia-driver-runtime | | | Updated by os2 change  |
|  | (add-on) vcluster | | | Experimental add-on |
|  | (add-on) harvester-vm-dhcp-controller | | | Skip, Experimental add-on |
| 🟢 | harvester-eventrouter |  0.2.0 | 0.3.1 |  @w13915984028 |

> **How to create a new version of images**
> - Create a new tag in a repository.
> - (Optional) Branch management. For each component, you should create a new branch for the previous minor version to backport future changes back to that branch.

**Comment by khushboo-rancher** [comment]
@rrajendran17 Could you please help check all the versions are bumped in 1.4.0-rc2?

**Comment by Yu-Jack** [comment]
The `pcidevices-controller` is `v0.4.1`. cc @bk201 

PRs:
- https://github.com/harvester/addons/pull/25
- https://github.com/harvester/charts/pull/296

**Comment by bk201** [comment]
In general, the component needs to have the same minor version, but it's OK to have a newer patch number because we are moving forward.

> The `pcidevices-controller` is `v0.4.1`. cc @bk201
> 
> PRs:
> 
> * [addon updates for v1.4.0-rc2 addons#25](https://github.com/harvester/addons/pull/25)
> * [Pcidevices 0.4.1 charts#296](https://github.com/harvester/charts/pull/296)

**Comment by rrajendran17** [comment]
@w13915984028 can you please let me know what "harvester-eventrouter" is ?
what is the Kind and namespace it is present ?

**Comment by bk201** [comment]
@rrajendran17 You can enable the logging add-on and a pod called `harvester-default-event-tailer-0` will use this image.

**Comment by rrajendran17** [comment]
verified that all above mentioned components are bumped in 1.4-rc2.closing this as completed.
