### ISSUE TITLE
[ENHANCEMENT] Bump go to v1.22

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6160]
**Is your enhancement related to a problem? Please describe.**

Go v1.21 is going to be EOL soon in August 2024.

Ref: https://endoflife.date/go, https://tip.golang.org/doc/go1.23

**Describe the solution you'd like**

Update repositories to GO 1.22 in `go.mod` and `Dockerfile`. If a repository builds many images, please remember to update each `Dockerfile`.

| Done | Repository | Owner |
| --- | --- | --- |
| v | https://github.com/harvester/cloud-provider-harvester | @w13915984028  |
| v | https://github.com/harvester/docker-machine-driver-harvester | @FrankYang0529  |
| v | https://github.com/harvester/eventrouter | @w13915984028 |
| v | https://github.com/harvester/go-common | - |
| v  | https://github.com/harvester/harvester | @FrankYang0529 |
| v  | https://github.com/harvester/harvester-csi-driver | @Vicente-Cheng |
| v | https://github.com/harvester/harvester-installer | @tserong |
| v | https://github.com/harvester/load-balancer-harvester | @starbops |
| v | https://github.com/harvester/network-controller-harvester | @mingshuoqiu |
| v | https://github.com/harvester/node-disk-manager | @Vicente-Cheng |
| v | https://github.com/harvester/node-manager | @brandboat  |
| v | https://github.com/harvester/pcidevices | @ibrokethecloud |
| v | https://github.com/harvester/seeder | @ibrokethecloud |
| v | https://github.com/rancher/rancherd | @FrankYang0529 |
| v | https://github.com/rancher/support-bundle-kit | @Yu-Jack  |
| v | https://github.com/harvester/vm-dhcp-controller | @starbops |
| v | https://github.com/harvester/vm-import-controller | @ibrokethecloud  |
| v | https://github.com/harvester/terraform-provider-harvester | @FrankYang0529 |

**Comment by Vicente-Cheng** [comment]
If you encounter the following issue when running validation after bumping to go 1.22.
```
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x9ef28f]
```

Please update the `sigs.k8s.io/controller-tools/cmd/controller-gen` from `v0.6.2` to `v0.15.0`
(e.g. https://github.com/harvester/node-disk-manager/blob/master/Dockerfile.dapper#L18)

**Comment by FrankYang0529** [comment]
If golangci-lint version is too low, you may get error like:

```
Running: golangci-lint
./validate: line 18: 21563 Killed                  golangci-lint run
```

This can be fixed by updating `golangci-lint` to newer version like `v1.58.2`.

**Comment by FrankYang0529** [comment]
All PRs are merged. Close the issue.
