### ISSUE TITLE
[BUG] [GUI] Image creation progress is not up-to-date

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6164]
**Describe the bug**
The image creation progress is not up-to-date in frontend

**To Reproduce**
1. Creating an image with upload via URL or via Local file
2. The creation progress bar may not be updated
3. Checking the backend CR `VirtualMachineImage`'s `.status.progress`, it's kept updating

**Expected behavior**
The frontend's information should remain consistent with the backend

**Environment**
 - Harvester ISO version: master-head (`09f3ca172fc1dc1ce7cc4af840d32888f3365a79`)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
It's a rare case, not always reproducible

**Comment by FrankYang0529** [comment]
@a110605 @torchiaf, could you take a look for this? Thank you.

**Comment by torchiaf** [comment]
@WebberHuang1118 I can't reproduce the bug.
Could you provide more details? How much workload is in your environment ? Do you have any websocket errors in the web browser console?

**Comment by WebberHuang1118** [comment]
@torchiaf 
There is no specific workload and websocket errors, and as I mentioned this is not always reproducible. However, it happens occasionally.
