### ISSUE TITLE
[ENHANCEMENT v1.4.0] Bump rancher-monitoring version to 103.1.1+up45.31.1, rancher-logging to 103.1.0+up4.4.0

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6166]
**Is your enhancement related to a problem? Please describe.**

Bump rancher-monitoring to `103.0.4+up45.31.1` (for Rancher v2.8)

Bump rancher-logging to 103.1.0+up4.4.0

https://github.com/rancher/charts/blob/release-v2.8/charts/rancher-monitoring/103.1.1%2Bup45.31.1/values.yaml

https://github.com/rancher/charts/blob/release-v2.8/charts/rancher-logging/103.1.1%2Bup4.4.0/values.yaml

Bump shell image to 0.1.26, reduce CVE
https://github.com/rancherlabs/image-scanning/issues?q=is%3Aissue+is%3Aopen+shell

Bump eventrouter image to [v0.3.1](https://github.com/harvester/eventrouter/releases/tag/v0.3.1) after bump  go v122
https://github.com/harvester/eventrouter/pull/11

Bump chart version on https://github.com/harvester/addons/pull/5

Other possible updates

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

Also related to https://github.com/harvester/harvester/issues/6158

**Comment by brandboat** [comment]
gentle ping @w13915984028, do we have test plan for this ?

**Comment by albinsun** [comment]
> gentle ping @w13915984028, do we have test plan for this ?

@brandboat, can refer to https://github.com/harvester/harvester/issues/5003#issuecomment-1965899160.

**Comment by brandboat** [comment]
> @brandboat, can refer to https://github.com/harvester/harvester/issues/5003#issuecomment-1965899160.

Huge thanks !!! I'll go ahead and test this.

**Comment by w13915984028** [comment]
Thanks @albinsun @brandboat :

The general test plans are:
(1) On v140 version, like https://github.com/harvester/harvester/issues/5003#issuecomment-1965899160, the `rancher-monitoring` and `rancher-logging` addons can be sucessfully enabled and the related versions are as expected.  If your cluster is using 250Gi disk, it may hit https://docs.harvesterhci.io/v1.4/troubleshooting/monitoring#fail-to-enable-rancher-monitoring-addon and use the related workaround.

(2) On the upgrade path v1.3.2 -> v1.4.0:
(2.1) Enable them on v1.3.2, after upgrading, they are still enabled and the versions are upgraded to target.
(2.2) Disable them on v1.3.2, after upgrading, they are still disabled and the versions are upgraded (view from yaml of the addon), and can be enabled successfully.

**Comment by brandboat** [comment]
gentle ping @w13915984028, I saw an issue in rancher-logging, could you please take a look ? And do you know how to verify rancher-logging is working ? 

## Environment
* Harvester
  * Version: `v1.4.0-rc3`
  * Profile: QEMU/KVM, 1 node (16C/32G/500G)
  * ui-source: `Auto`

## Steps
- Upgrade from v1.3.2 to v1.4.0-rc3
- Enable monitoring and logging addons, also check rancher-monitoring version is `103.1.1+up45.31.1` and rancher-logging version is`103.1.0+up4.4.0`.
![image](https://github.com/user-attachments/assets/0f5e791f-b63e-4d56-8560-0162b8080fda)
- Grafana works well
![截圖 2024-10-18 上午11 56 50](https://github.com/user-attachments/assets/eeab3468-1166-4412-bba1-e72ca263a206)
- But when I try to create Output in rancher-logging 
![image](https://github.com/user-attachments/assets/d4cd903a-2cc3-4a4d-9caa-a2e3b50fc79b)
- in output buffer tab, I saw error
![image](https://github.com/user-attachments/assets/14de4c2c-6403-4ae6-aaac-732a7a0143a3)
- And in v1.3.2, this should be something like
![image](https://github.com/user-attachments/assets/0c47149a-9ad7-492e-afc2-cbe4e50bb184)
- And I proceeded to click create, an error pop out
![image](https://github.com/user-attachments/assets/e107a1de-01eb-48e5-aa2b-a62347543a9d)

**Comment by brandboat** [comment]
Test OK on v1.4.0-rc3, will close the issue

## Environment
* Harvester
  * Version: `v1.4.0-rc3`
  * Profile: QEMU/KVM, 1 node (16C/32G/500G)
  * ui-source: `Auto`

## Steps
### Upgrade from v1.3.2 to v1.4.0-rc3
- ✅  Enable monitoring and logging addons, also check rancher-monitoring version is `103.1.1+up45.31.1` and rancher-logging version is`103.1.0+up4.4.0`.
![image](https://github.com/user-attachments/assets/0f5e791f-b63e-4d56-8560-0162b8080fda)
- ✅  Grafana works well
![截圖 2024-10-18 上午11 56 50](https://github.com/user-attachments/assets/eeab3468-1166-4412-bba1-e72ca263a206)
- ✅  Follow rancher-logging test steps in https://github.com/w13915984028/harvester-develop-summary/blob/main/test-log-event-audit-with-webhook-server.md, all good.
  - logging
  <img width="1668" alt="image" src="https://github.com/user-attachments/assets/f374b6cf-f419-4ab8-bef2-b1d588cc3b32">
  - event
  <img width="1666" alt="image" src="https://github.com/user-attachments/assets/3ca66635-a84a-4e04-8f27-1c11a7c5bf1d">
  - audit
  <img width="1672" alt="image" src="https://github.com/user-attachments/assets/e942aaf2-d4e2-403d-8530-dcce883e8295">

### Fresh installation v1.4.0-rc3
- ✅  Enable monitoring and logging addons, also check rancher-monitoring version is `103.1.1+up45.31.1` and rancher-logging version is`103.1.0+up4.4.0`.
![image](https://github.com/user-attachments/assets/a525cf22-62e4-4df1-b301-12c17ef227eb)

- ✅  Grafana works well
![image](https://github.com/user-attachments/assets/1bbf9827-6a0e-4829-93b2-5ab25707274d)

- ✅ Follow rancher-logging test steps in https://github.com/w13915984028/harvester-develop-summary/blob/main/test-log-event-audit-with-webhook-server.md, all good.
  - logging
  <img width="1667" alt="image" src="https://github.com/user-attachments/assets/dff980f5-db67-4541-bee1-0165783d0675">
  - event
  <img width="1672" alt="image" src="https://github.com/user-attachments/assets/47933a69-b3f6-404e-9864-1c3bfe8d694a">
  - audit 
  <img width="1667" alt="image" src="https://github.com/user-attachments/assets/ad05d6df-08cc-4b8f-861a-23a5a2b0c764">
