### ISSUE TITLE
[Question] StorageClass DiskSelector/Host Storage Disk Tag

### ISSUE THREAD

**Issue by boverhof** [harvester/harvester#6168]
I created a `StorageClass` with `number-replicas:1` and `data-locality:best-effort`.  I added a "Disk Tag" in the Host Storage UI and saved it.  However, the `StorageClass` Disk Selector displays no options.

I'm not sure if I'm misunderstanding how to do this or if this is a bug or unsupported edge case, or maybe I just need to edit the YAML..  Any pointers appreciated.

thanks
version v1.3.0

![Screenshot 2024-07-12 at 10 08 32 AM](https://github.com/user-attachments/assets/6da1ad2c-faf7-415f-be74-2c78d68df99f)

**Comment by Vicente-Cheng** [comment]
Hi @boverhof, could you generate the support bundle for this issue?
(REF: https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle)

I cannot reproduce in my local environment.
Thanks!

**Comment by FrankYang0529** [comment]
I tried the operation in Harvester v1.3.0, but can't reproduce this. May you provide support-bundle? Thanks.

<img width="865" alt="Screenshot 2024-07-17 at 12 13 09 PM" src="https://github.com/user-attachments/assets/c690bf4c-efd1-44af-846a-8c08d6bff0d7">
<img width="869" alt="Screenshot 2024-07-17 at 12 13 39 PM" src="https://github.com/user-attachments/assets/3d44803d-9fee-4429-9146-3f0ee1f9f2b8">
