### ISSUE TITLE
[BUG] Harvester v1.3.0 virtual machine suddenly crashed

### ISSUE THREAD

**Issue by seajelly** [harvester/harvester#6170]
**Describe the bug**

My business staff gave me feedback that our virtual machine with nacos installed cannot be accessed. I opened the vnc console and found the prompt below the virtual machine.
![a69231a993fcff7c7f6b4e9603d215d](https://github.com/user-attachments/assets/f276a08a-c7ad-4816-81d6-0d55e3e6ccb7)

**To Reproduce**

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  v 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):  huawei RH2288V5PRO

**Additional context**

**Comment by Vicente-Cheng** [comment]
Hi @seajelly,

It seems the VM root is broken.

Could you generate the Support bundle for it?
(REF: https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle)
Also, do you remember what operation you have done before this?

**Comment by seajelly** [comment]
Thanks for the reply, I confirmed The crashed VM is only manageable by me and only runs the naocos registry. At a later stage I removed this crashed VM I'm not sure if you can still see the logs you are looking for。This runaway VM is running on har-node02。The log I downloaded was 37MB in size, and github limits uploading files to 25Mb.

**Comment by seajelly** [comment]
@Vicente-Cheng   hi ，I put the logs in a git project url: https://gitee.com/zerof_fei/logs/raw/master/supportbundle_28abdbb1-ae21-4d67-b8ad-9ab1b55ea369_2024-07-15T02- 53-53Z.zip
