### ISSUE TITLE
[ENHANCEMENT] Bump LH to v1.7.1

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#6172]
Since harvester needs some features of LH v1.7, so bump it. Include:
- https://github.com/harvester/harvester/issues/3129

**Comment by Yu-Jack** [comment]
Bumping Logs:

1. Bump LH to `v1.7.0-rc1` , `go mod tidy and go mod vendor` are okay. Start to run build and go mod tidy/vendor after each changes.

   1. LH needs `VolumeResourceRequirements` when building binary

   2. Bump `k8s.io/api` to `v0.29.6` which contains `VolumeResourceRequirements`

   3. `kubevirt.io/client-go/kubecli` needs `k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1`, but `k8s.io/api@v0.29.6` already removed `v1alpha1`

   4. Bump `kubevirt.io/api` to `v1.3.0-rc2` because `kubevirt.io/api@v1.2.2` still uses `v1alpha`, but `v1.3.0-rc2` uses `v1beta1`

   5. `kubevirt.io/client-go/kubecli` needs `k8s.io/client-go/kubernetes/typed/storagemigration/v1alpha1`, but `k8s.io/api@v0.29.6` doesn’t have `storagemigration/v1alpha1` yet.

   6. Bump `k8s.io/api` to `v0.30.3`, which contains `storagemigration/v1alpha1`

   7. `rancher/wrangler/pkg/controller-gen/args` needs `k8s.io/code-generator/cmd/client-gen/path` , which is removed from `k8s.io/api@v0.30.x `

   8. Bump `rancher/wrangler` to `v2.1.4`. In this step, need to replace all `github.com/rancher/wrangler` with `github.com/rancher/wrangler/v2` in import list. But, `rancher/wrangler@v2.1.4` still needs `k8s.io/code-generator/cmd/client-gen/path`

   9. Bump `rancher/wrangler` to `v3.0.0`. In this step, still need to replace `wrangler/v2` with `wrangler/v3` in all import list.

   10. `github.com/harvester/harvester/pkg/codegen` needs \
      ⇒`github.com/rancher/rancher/pkg/apis/management.cattle.io/v3`\
      ⇒`github.com/rancher/rke/types`\
      ⇒`k8s.io/apiserver/pkg/apis/config/v1`, which is removed from `k8s.io/apiserver@0.30.x`

   11. Bump `rancher/rancher/pkg/apis & rancher/rancher/pkg/client & rancher/rancher` to `release/v2.9@93e3321` , which is not stable and released yet.

2. `go mod tidy and go mod vendor` are okay. Start building.

   1. Replace `ResourceRequirements` to `VolumeResourceRequirements` in `Volume.Spec`

   2. Type problem in `pkg/config/context.go:347:66: cannot use opts (variable of type *"github.com/rancher/wrangler/v3/pkg/generic".FactoryOptions) as *"github.com/rancher/wrangler/pkg/generic".FactoryOptions value in argument to helmv1.NewFactoryFromConfigWithOptions`

   3. `k3s-io/helm-controller` still uses `wrangler@v0`, should have `"github.com/rancher/wrangler/v3/pkg/generic".Handler`

   4. Bump `k3s-io/helm-controller` from `v0.11.7` to `v0.16.1`. BTW, it starts to use `wrangler@v3` from `v0.16.1`, `v0.16.0` uses `wrangler@v2`

   5. Fix `rancher/steve` `proxy.NewProxyStore` usage issue from three parameters to four parameters

3. Building is successful. Re-run `go generate`

   1. `rancher/wrangler@v3` removed the `InformersPackage` `ClientSetPackage` `ListersPackage`, so we need to remove those fields in our generator.

4. Generating is successful. Run Golint and testing.

   1. Lot of missing methods and variables, see [fixing commit](https://github.com/harvester/harvester/pull/6173/commits/de6ac2695ad74d464041418715c55b75340fb1e1) for more details. Overall modifying is `fakeclients` due to `rancher/wrangler` bumping.

   2. `rancher/fleet/pkg/apis/fleet.cattle.io/v1alpha1` remove some constant variables like `BundleResourceName`

   3. Usage from `validationutil.IsValidIP(addonContent.Hostname)` to `validationutil.IsValidIP(field.NewPath(""), addonContent.Hostname)`

   4. ~~`pkg/generated/clientset/versioned/typed/cluster.x-k8s.io/v1beta1/fake/fake_cluster.go` uses `SchemeGroupVersion` from  `sigs.k8s.io/cluster-api/api/v1beta1`, but `SchemeGroupVersion` doesn’t exist. The correct name is `GroupVersion`. But, this is generated by `rancher/wrangler`. So, we need to fix it manually for temporary. 🔴 RED FLAG, would be dangerous.~~ There is already a workaround in codegen/main.go.

5. Successfully run `./scripts/build` and `./scripts/test` in my laptop. Try to create PR for CI.

   1. `vendor/modernc.org/sqlite/bind_blob_musl.go:12:2: found import comments "modernc.org/libc" (aliases.go) and "modernc.org/libc/v2" (atomic.go) in /go/src/github.com/harvester/harvester/vendor/modernc.org/libc` , which is used by `rancher/lasso`. 

   2. `cannot find package in any of goroot gopath when doing golint`, add `ENV GO111MODULE on` in Dockerfile.dapper. This also fixed previous issue.

   3. `../../../vendor/helm.sh/helm/v3/pkg/kube/client.go:92:12: cannot use cmdutil.NewFactory(getter) (value of type "k8s.io/kubectl/pkg/cmd/util".Factory) as Factory value in struct literal: "k8s.io/kubectl/pkg/cmd/util".Factory does not implement Factory (missing method OpenAPIGetter)` , need to bump `github.com/rancher/helm/v3` to `v3.13.3-rancher1`
   
   4.  `oras.land/oras-go/pkg/auth/docker ../../../vendor/oras.land/oras-go/pkg/auth/docker/login.go:86:39: cannot use remote (variable of type *"github.com/docker/docker/registry".DefaultService) as *"github.com/docker/docker/registry".Service value in argument to c.loginWithTLS: *"github.com/docker/docker/registry".DefaultService does not implement *"github.com/docker/docker/registry".Service (type *"github.com/docker/docker/registry".Service is pointer to interface, not interface)`, bump `github.com/docker/docker` to `v24.0.6+incompatible`

5. Now, it can run integration tests.

**Comment by FrankYang0529** [comment]
It looks like Harvester only imports `github.com/longhorn/longhorn-manager` to use constant values and CRD. If we don't use new fields in CRD or new constant values, we probably can just bump chart, so we don't need to include lot of changes.

**Comment by Yu-Jack** [comment]
It seems we have two options for this case:

- Bump go modules, including LH chart -> One PR
- Bump LH chart first, then bump go modules -> Two PRs

**Comment by bk201** [comment]
@Yu-Jack Please help bump to 1.7.0-rc4 to verify https://github.com/longhorn/longhorn-manager/pull/3064

Test plan:

in longhorn-csi-plugin pods, curl http://longhorn-backend:9500/v1 repeatedly should work well.

**Comment by FrankYang0529** [comment]
Hi @Yu-Jack, could you bump LH to v1.7.1-rc1? There is a critical issue in v1.7.0, so we may need to skip it. Thank you.

v1.7.0: https://github.com/longhorn/longhorn/releases/tag/v1.7.0
v1.7.1-rc1: https://github.com/longhorn/longhorn/releases/tag/untagged-c474743c5f9dc38df0fc

**Comment by TachunLin** [comment]
Verifying on `v1.4-cd10d18-head` (24/09/18).

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Check already bump Longhorn to v1.7.1 $~~$</summary>

  1. On Longhorn dashboard, the current Longhorn version is `v1.7.1`
  ![image](https://github.com/user-attachments/assets/64df6e30-c3eb-4d67-9a58-5e7d6f8f04fd)

  2. Check the Harvester deployment and node setting already bump to `v1.7.1`


  ```
  harvester-node-0:~ # kubectl get nodes -o json | grep longhorn
                      "csi.volume.kubernetes.io/nodeid": "{\"driver.longhorn.io\":\"harvester-node-0\"}",
                              "docker.io/longhornio/longhorn-instance-manager:v1.7.1"
                              "docker.io/longhornio/backing-image-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-engine:v1.7.1"
                              "docker.io/longhornio/longhorn-manager:v1.7.1"
                              "docker.io/longhornio/support-bundle-kit:v0.0.42"
                              "docker.io/longhornio/longhorn-cli:v1.7.1"
                              "docker.io/longhornio/longhorn-share-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-ui:v1.7.1"
                      "csi.volume.kubernetes.io/nodeid": "{\"driver.longhorn.io\":\"harvester-node-1\"}",
                              "docker.io/longhornio/longhorn-instance-manager:v1.7.1"
                              "docker.io/longhornio/backing-image-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-engine:v1.7.1"
                              "docker.io/longhornio/longhorn-manager:v1.7.1"
                              "docker.io/longhornio/support-bundle-kit:v0.0.42"
                              "docker.io/longhornio/longhorn-cli:v1.7.1"
                              "docker.io/longhornio/longhorn-share-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-ui:v1.7.1"
                      "csi.volume.kubernetes.io/nodeid": "{\"driver.longhorn.io\":\"harvester-node-2\"}",
                              "docker.io/longhornio/longhorn-instance-manager:v1.7.1"
                              "docker.io/longhornio/backing-image-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-engine:v1.7.1"
                              "docker.io/longhornio/longhorn-manager:v1.7.1"
                              "docker.io/longhornio/support-bundle-kit:v0.0.42"
                              "docker.io/longhornio/longhorn-cli:v1.7.1"
                              "docker.io/longhornio/longhorn-share-manager:v1.7.1"
                              "docker.io/longhornio/longhorn-ui:v1.7.1"
  ```   
                      
  ```
  harvester-node-0:~ # kubectl get deployments -A -o jsonpath='{range .items[*]}{@.metadata.name}{" "}{@.spec.template.spec.containers[*].image}{"\n"}{end}'|column -t | grep longhorn
  csi-attacher                           longhornio/csi-attacher:v4.6.1
  csi-provisioner                        longhornio/csi-provisioner:v4.0.1
  csi-resizer                            longhornio/csi-resizer:v1.11.1
  csi-snapshotter                        longhornio/csi-snapshotter:v7.0.2
  longhorn-driver-deployer               longhornio/longhorn-manager:v1.7.1
  longhorn-ui                            longhornio/longhorn-ui:v1.7.1
  
  ```





 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Verify all the pods in the longhorn-system are healthy $~~$</summary>

  ```
  harvester-node-0:~ # kubectl get pods -n longhorn-system
  NAME                                                READY   STATUS    RESTARTS        AGE
  csi-attacher-749459cf65-jkcgh                       1/1     Running   0               3h49m
  csi-attacher-749459cf65-qkkdz                       1/1     Running   0               3h49m
  csi-attacher-749459cf65-snqb7                       1/1     Running   0               3h49m
  csi-provisioner-775b4f76f4-7hs4j                    1/1     Running   0               3h49m
  csi-provisioner-775b4f76f4-95x9x                    1/1     Running   0               3h49m
  csi-provisioner-775b4f76f4-k9qxc                    1/1     Running   0               3h49m
  csi-resizer-68867d54f5-4z8g4                        1/1     Running   0               3h49m
  csi-resizer-68867d54f5-72qd9                        1/1     Running   0               3h49m
  csi-resizer-68867d54f5-j4sqx                        1/1     Running   0               3h49m
  csi-snapshotter-8469656cc7-fd87f                    1/1     Running   0               3h49m
  csi-snapshotter-8469656cc7-k6ls8                    1/1     Running   0               3h49m
  csi-snapshotter-8469656cc7-vqchf                    1/1     Running   0               3h49m
  engine-image-ei-f4f7aa25-l4mlb                      1/1     Running   0               3h39m
  engine-image-ei-f4f7aa25-twtwh                      1/1     Running   0               3h24m
  engine-image-ei-f4f7aa25-z4tvz                      1/1     Running   0               3h50m
  instance-manager-72d4e3a97e5a50abeaa2ba4e95c6cf41   1/1     Running   0               3h39m
  instance-manager-909ab1b4cee25ce65cdbc6454cc73a4f   1/1     Running   0               3h23m
  instance-manager-c10fc2f09885c699d762acbc8cbe8620   1/1     Running   0               3h50m
  longhorn-csi-plugin-22btk                           3/3     Running   0               3h49m
  longhorn-csi-plugin-kf98t                           3/3     Running   1 (3h23m ago)   3h39m
  longhorn-csi-plugin-t7d7q                           3/3     Running   1 (3h22m ago)   3h24m
  longhorn-driver-deployer-7964bdf7df-ss4p7           1/1     Running   0               3h51m
  longhorn-loop-device-cleaner-k9ddt                  1/1     Running   0               3h39m
  longhorn-loop-device-cleaner-ml6ll                  1/1     Running   0               3h24m
  longhorn-loop-device-cleaner-zbtbs                  1/1     Running   0               3h51m
  longhorn-manager-gztfk                              2/2     Running   0               3h51m
  longhorn-manager-hdpnl                              2/2     Running   0               3h39m
  longhorn-manager-zr7qr                              2/2     Running   0               3h24m
  longhorn-ui-68bb9478bb-p9hsh                        1/1     Running   0               3h51m
  longhorn-ui-68bb9478bb-w2z8f                        1/1     Running   0               3h51m
  ```

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Verify using curl http://longhorn-backend:9500/v1 repeatedly should work well $~~$</summary>

```
longhorn-csi-plugin-22btk:/tmp # sh test.sh
Success: Reached http://longhorn-backend:9500/v1 on attempt 1
Success: Reached http://longhorn-backend:9500/v1 on attempt 2
Success: Reached http://longhorn-backend:9500/v1 on attempt 3
Success: Reached http://longhorn-backend:9500/v1 on attempt 4
Success: Reached http://longhorn-backend:9500/v1 on attempt 5
Success: Reached http://longhorn-backend:9500/v1 on attempt 6
Success: Reached http://longhorn-backend:9500/v1 on attempt 7
Success: Reached http://longhorn-backend:9500/v1 on attempt 8
Success: Reached http://longhorn-backend:9500/v1 on attempt 9
Success: Reached http://longhorn-backend:9500/v1 on attempt 10

```


 </details>


<details><summary>$\color{green}{\textsf{PASS}}$ Execute volume e2e automation test $~~$</summary>

According to the [harvester_run_test/106/TestReport](http://172.19.99.74/job/harvester-runtests/106/TestReport/)

1. PASS most of the volume e2e test 
![image](https://github.com/user-attachments/assets/1ddf7f9f-44bb-4f73-b47a-6e8e788f1b25)

2. Except the following failed test cases
    - test_1_volumes.py::test_volume_export
    - test_1_volumes.py::TestVolumeWithVM::test_delete_volume_on_deleted_vm::teardown

3. Manually double check the volume export can works as expected, the e2e test failure would related to test script clean up action and the timing synchronization.

 </details>

<details><summary>$\color{red}{\textsf{Failed}}$ Execute vm_function e2e automation test $~~$</summary>


According to the [harvester_run_test/107/TestReport](http://172.19.99.74/job/harvester-runtests/107/TestReport/)

1. We failed the following vm function e2e test 

![image](https://github.com/user-attachments/assets/13458ded-9e6a-4900-bab6-42cdd859ff5e)
![image](https://github.com/user-attachments/assets/c1fe0510-199f-4d88-9bab-3baa534c62bd)

  - TestVMOperations::test_stop
  - TestVMOperations::test_restart
  - TestVMOperations::test_restart
  - TestVMOperations::test_softreboot
  - TestVMOperations::test_migrate
  - TestVMOperations::test_abort_migrate
  - TestVMResource::test_create_schedule_on_maximum[cpu]
  - TestVMResource::test_create_schedule_on_maximum[memory]
  - TestVMResource::test_update_schedule_on_maximum[cpu]
  - test_update_schedule_on_maximum[memory]
  - TestVMResource::test_update_enable_usb
  - TestVMResource::test_update_enable_user_data
  - TestVMClone::test_clone_stopped_vm
  - TestVMWithVolumes::test_create_with_two_volumes
  - test_vm_with_bogus_vlan

 </details>

### Test Information
* Test Environment: Three nodes harvester on kvm machines
* Harvester version: `v1.4-cd10d18-head` (24/09/18)

### Verify Steps
<details><summary>Steps </summary>


</details>

**Comment by Yu-Jack** [comment]
@TachunLin I notice that `TestVMOperations::test_stop` failed. According to https://github.com/harvester/harvester/issues/6312#issuecomment-2288004787, the `spec.RunStratedy` isn't changed after Kubevirt v1.2.2. Our `virt-operator` image is `registry.suse.com/suse/sles/15.5/virt-api:1.2.2-150500.8.21.1` in v1.4. So, I think the assertion of this test case might be modified. 

cc @WebberHuang1118 If I misunderstand this, please let me know, thanks!

**Comment by TachunLin** [comment]
@Yu-Jack, 
Thank you for checking the failed vm function e2e test and indicate the possible root cause.  
As per discussed with QA member, we already confirmed Longhorn already bump to `v1.7.1` well. 

We can close this issue since the major requirement already accomplished. 
And we can track the failed test cases in https://github.com/harvester/tests/issues/1544
