### ISSUE TITLE
[BUG] Embedded Rancher UI Cannot Add Reveicer in AlertmanagerConfig

### ISSUE THREAD

**Issue by braveantony** [harvester/harvester#6174]
**Describe the bug**

The UI throws an error when navigating to Add Reveicers from AlertmanagerConfig tab

**To Reproduce**

1. on the `Support` page，Click `Access Embedded Rancher UI`
2. Create an AlertmanagerConfigs in `cattle-monitoring-system` namespace
3. Click the `Alertmanager Configs` just created to continue the configuration
4. Click `Add Receiver`

**Result**

The fail-whale page shows the error:

```
Cannot read properties of undefined (reading 'map')
```

**Expected behavior**

Can set the Name for the receiver and can select the receiver type.

**Environment**
 - Harvester ISO version: harvester-v1.3.1-amd64.iso

**Additional context**

![image](https://github.com/user-attachments/assets/0bad2b35-d0d1-4870-858f-4bde9b6fe80b)

**Comment by FrankYang0529** [comment]
Hi @braveantony, embedded Rancher is used for building Harvester cluster and managing Harvester dependency charts. We don't encourage users to use it directly. If you want to deploy a Rancher in Harvester, we suggest to use rancher-vcluster.

https://docs.harvesterhci.io/v1.3/advanced/addons/rancher-vcluster/#installing-rancher-vcluster

**Comment by braveantony** [comment]
Hi @FrankYang0529, I understand, thank you very much for your reply, but rancher-vcluster is still an experimental feature in Harvester v1.3, it's hard to implement in Airgap environment, will it become non-experimental in later versions?

**Comment by FrankYang0529** [comment]
Hi @braveantony, according to the [roadmap](https://github.com/harvester/harvester/wiki/Roadmap), rancher-vcluster will be GA in Harvester v1.5.0.
