### ISSUE TITLE
[Question] Applying an incorrect rke.cattle.io/init-node-machine-id in Harvester has caused the cluster to fail to start. How can I recover it?

### ISSUE THREAD

**Issue by silentdark** [harvester/harvester#6178]
Hello everyone,

Here’s the situation: 

I have a 3-node cluster, and one of the nodes was damaged in an accident. 

When I tried to add a new node, the promote failed. 

So, I followed the method described in this GitHub issue #2187 and prepared to apply the rke.cattle.io/init-node-machine-id of the second node, but I copied the wrong number. 

Now, the cluster cannot start, and the rancher-system-agent reports the following error:

`Jul 16 13:47:17 harvester0 systemd[1]: Started Rancher System Agent.
Jul 16 13:47:17 harvester0 rancher-system-agent[86739]: time="2024-07-16T13:47:17Z" level=info msg="Rancher System Agent version v0.3.4 (63eb11a) is starting"
Jul 16 13:47:17 harvester0 rancher-system-agent[86739]: time="2024-07-16T13:47:17Z" level=info msg="Using directory /var/lib/rancher/agent/work for work"
Jul 16 13:47:17 harvester0 rancher-system-agent[86739]: time="2024-07-16T13:47:17Z" level=info msg="Starting remote watch of plans"
Jul 16 13:49:27 harvester0 rancher-system-agent[86739]: time="2024-07-16T13:49:27Z" level=fatal msg="error while connecting to Kubernetes cluster: Get \"https://10.53.117.85/version\": dial tcp 10.53.117.85:443: connect: connection timed out"
Jul 16 13:49:27 harvester0 systemd[1]: rancher-system-agent.service: Main process exited, code=exited, status=1/FAILURE
Jul 16 13:49:27 harvester0 systemd[1]: rancher-system-agent.service: Failed with result 'exit-code'.
Jul 16 13:49:32 harvester0 systemd[1]: rancher-system-agent.service: Scheduled restart job, restart counter is at 9.
Jul 16 13:49:32 harvester0 systemd[1]: Stopped Rancher System Agent.`

How can I recover the cluster?

**Comment by ibrokethecloud** [comment]
some more info would help.

Is the error on the new node you added?

What is the state of the other 2 nodes left from the original cluster are they running?

I assume `https://10.53.117.85/` is the VIP for your cluster?

**Comment by silentdark** [comment]
Thank you very much.

After hard work, I finally got the cluster back.

First, I restored the harvester cluster using snapshot, fixed the init-node-machine-id.

Cleaned up the remaining machine.cluster.x-k8s.io resources.

Then added back 3 nodes one by one.

And finally the whole cluster was working!
