### ISSUE TITLE
[Question] v1.3.0 Replace storage disk

### ISSUE THREAD

**Issue by seajelly** [harvester/harvester#6184]
background:
      1. I am currently running a harvester (v1.3.0) cluster consisting of three node components. The node02 node is equipped with the following system disk: raid5 (1TSSD*3), storage disk: raid5 (Seagate 6THDD*4).
       2. I have migrated all the virtual machines on node02 to node01 and node03.
       3. The number of volume copies for all virtual machines is 2
expect:
        I want to replace all the storage disks on the node02 node, and replace 4 Seagate HDDs with 4 Western Digital HDDs.
Puzzled:
      1. After the node02 machine is in the latest maintenance status, can I directly replace the storage disk after shutting down? Will it affect my running virtual machine?
      2. Can node 02 still start normally after converting the storage disk?

**Comment by seajelly** [comment]
I have completed the disk replacement, but my node02 is stuck at the system initialization interface. ,Do you have any good ideas, bro?
![0a454c971702f8a67774268847108e8](https://github.com/user-attachments/assets/0579fd13-d102-4434-a77b-ca0c46602dc7)
![581608934cb407065e2501235d29a6e](https://github.com/user-attachments/assets/7186f153-28bf-4792-a304-aa49d250fed3)
@FrankYang0529

**Comment by Vicente-Cheng** [comment]
Hi @seajelly, could you describe your steps for the whole operation?

>1. After the node02 machine is in the latest maintenance status, can I directly replace the storage disk after shutting down? Will it affect my running virtual machine?

If no replica/VM is on node02, directly replacing the external disk should be fine. You can remove the disk on the storage page (REF: https://docs.harvesterhci.io/v1.3/host/#remove-disks) before you replace it.

2. Can node 02 still start normally after converting the storage disk?
It should be fine. Have you already restarted node02 and seen this error?

**Comment by seajelly** [comment]
@Vicente-Cheng thank you for your reply.
Implementation process:
1. I first set node02 as non-schedulable and enabled maintenance mode.
2. I directly shut down the physical machine of node02. I did not uninstall the original data disk on node02.
3. After shutting down, I replaced all 4 data disks on the node02 machine, installed 4 new Western Digital 4T gold disks, and configured raid5.
4. When I turned it on again, my node02 node seemed to be stuck in the initialization stage. (As in the picture I sent above, I can't see the error on the monitor)

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng thank you for your reply. Implementation process:
> 
> 1. I first set node02 as non-schedulable and enabled maintenance mode.
> 2. I directly shut down the physical machine of node02. I did not uninstall the original data disk on node02.
> 3. After shutting down, I replaced all 4 data disks on the node02 machine, installed 4 new Western Digital 4T gold disks, and configured raid5.
> 4. When I turned it on again, my node02 node seemed to be stuck in the initialization stage. (As in the picture I sent above, I can't see the error on the monitor)

Could you add the boot parameters `rd.shell` and `rd.debug` to kernel cmd by editing the grub option and trying to boot again?

**Comment by seajelly** [comment]
> > @Vicente-Cheng thank you for your reply. Implementation process: 感谢你的回复。实施过程：
> > 
> > 1. I first set node02 as non-schedulable and enabled maintenance mode.我首先将node02设置为不可调度并启用维护模式。
> > 2. I directly shut down the physical machine of node02. I did not uninstall the original data disk on node02.我直接关闭了node02的物理机。我没有卸载node02上原来的数据盘。
> > 3. After shutting down, I replaced all 4 data disks on the node02 machine, installed 4 new Western Digital 4T gold disks, and configured raid5.关机后，我将node02机器上的4块数据盘全部更换，安装了4块新的西数4T金盘，配置了raid5。
> > 4. When I turned it on again, my node02 node seemed to be stuck in the initialization stage. (As in the picture I sent above, I can't see the error on the monitor)当我再次打开它时，我的node02节点似乎卡在初始化阶段。 （如我上面发送的图片，我在显示器上看不到错误）
> 
> Could you add the boot parameters `rd.shell` and `rd.debug` to kernel cmd by editing the grub option and trying to boot again?您能否通过编辑 grub 选项将启动参数 `rd.shell` 和 `rd.debug` 添加到内核 cmd 并尝试再次启动？

Sorry, I may not be able to do this as we need to restore the cluster as soon as possible, so this node has already been reset. But we encountered a new problem with node X, which has been in a not ready state since resetting. When I SSH to this node, I found that it doesn't have rke2

**Comment by seajelly** [comment]
@Vicente-Cheng ![image](https://github.com/user-attachments/assets/6150dc08-4958-4a75-8923-fe7d903abda0)

**Comment by Vicente-Cheng** [comment]
> @Vicente-Cheng ![image](https://private-user-images.githubusercontent.com/42405205/350212669-6150dc08-4958-4a75-8923-fe7d903abda0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE1Mzg2ODQsIm5iZiI6MTcyMTUzODM4NCwicGF0aCI6Ii80MjQwNTIwNS8zNTAyMTI2NjktNjE1MGRjMDgtNDk1OC00YTc1LTg5MjMtZmU3ZDkwM2FiZGEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIxVDA1MDYyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYyMjFiMDY4NDZjYWEyY2FjOWUzOGVlZmIxOTM0MTU2ODgzYzNkNjBhYTI2ZTY3ZmU0ZDVlMTY2MmE5ZjIxMGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Kf2OWkoUFNxa4sjpguYmTo3mVdyJRLYk6E1oxEmU9uQ)

Hi @seajelly 
How did you restore the node02?

Did you mean the remove/re-join?
Could you elaborate more or generate a support bundle for this situation?

**Comment by seajelly** [comment]
@Vicente-Cheng I've figured out where the problem is, thank you for your attention.
