### ISSUE TITLE
[ENHANCEMENT] Bump KubeVirt to v1.2

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#6189]
**Describe the solution you'd like**
Bump KubeVirt to v1.2 for some new features like cpu/memory hotplug.

**Additional context**
https://github.com/harvester/harvester/issues/5835

**Comment by Yu-Jack** [comment]
During [bumping LH to v1.7](https://github.com/harvester/harvester/issues/6172), I also bumped the KubeVirt to v1.3.0-rc.2 due to restriction. However, I think we could firstly bump KubeVirt, which I think it's more easier than bumping LH. Anyway, just add relation between these two issues.

**Comment by Vicente-Cheng** [comment]
We also need Kubevirt v1.2 to enhance the hotplug volume behavior.
Reference Kubevirt PR: https://github.com/kubevirt/kubevirt/pull/10567
Harvester issue: https://github.com/harvester/harvester/issues/5951

**Comment by FrankYang0529** [comment]
> We also need Kubevirt v1.2 to enhance the hotplug volume behavior.

Hi @Vicente-Cheng, thanks for the reference. Let's wait for new release in `registry.suse.com/suse/sles/15.6/virt-operator`. Currently, the latest version is v1.1.1.

```
> reg tags -d registry.suse.com/suse/sles/15.6/virt-operator
DEBU[0000] Using registry "registry.suse.com" with no authentication
INFO[0000] domain: registry.suse.com
INFO[0000] server address: registry.suse.com
2024/07/25 22:22:18 registry.ping url=https://registry.suse.com/v2/
2024/07/25 22:22:21 registry.tags url=https://registry.suse.com/v2/suse/sles/15.6/virt-operator/tags/list repository=suse/sles/15.6/virt-operator
2024/07/25 22:22:22 registry.registry resp.Status=200 OK
1.1.1
1.1.1-150600.3.6
1.1.1-150600.5.3.2
1.1.1.22.386
1.1.1.24.3.3
sha256-b29f8c9e530a6301138b09f490b1d5844df7cf0f9d3fd3777e1c4f6c1c8345ff.att
sha256-b29f8c9e530a6301138b09f490b1d5844df7cf0f9d3fd3777e1c4f6c1c8345ff.sig
sha256-e1082fbe7f1ba9ec915e237467bdf689fdd63f393fd06e6e7b19330b270b1194.att
sha256-e1082fbe7f1ba9ec915e237467bdf689fdd63f393fd06e6e7b19330b270b1194.sig
```

**Comment by bk201** [comment]
Close. we already bump kubevirt to v1.2 in v1.4 branch.
