### ISSUE TITLE
[Question] ArgoCD to deploy vms 

### ISSUE THREAD

**Issue by emctl** [harvester/harvester#619]
Is there any vision of including a gitops operator (fleet/argocd/flux) as part of the harvester iso offering where a user could point to a repo to deploy the needed vms as part as the iso install?

I look at this from the self hosted homelab side where users can spin up multiple vm/clusters inside vms completely from code from a simple iso install.

**Comment by olljanat** [comment]
Afaiu Fleet have been included to Harvester codebase.

**Comment by haiwu** [comment]
When could ArgoCD be supported by Harvester?

**Comment by w13915984028** [comment]
Harvester is more than a k8s cluster, it also takes control of the underlay OS.

There is no plan to support ArgoCD or fleet directly at the moment.
