### ISSUE TITLE
[Question] Guest has not initialized the display when launch win10 with RTX A5000 vGPU

### ISSUE THREAD

**Issue by charnet1019** [harvester/harvester#6192]
When the NVIDIA Dirver toolkit is enabled, vGPU devices can be seen, but when vGPU is bound to a Windows host, it prompts "has not initialized the display"

![QQ_1721293256555](https://github.com/user-attachments/assets/be93d23a-1fe0-4329-a91a-aecb5169ed1b)
![image](https://github.com/user-attachments/assets/6acf3cce-c5f4-44ac-997d-b89726dfdcbd)

![image](https://github.com/user-attachments/assets/37281a1a-0eb7-4dfd-a6ea-fe059e1bd9bf)
![image](https://github.com/user-attachments/assets/c40c8b77-6a91-468f-9269-416d48180cc4)

[supportbundle_7ad0f472-368c-4aa8-af82-085be2d5bd3a_2024-07-18T09-03-34Z.zip](https://github.com/user-attachments/files/16280788/supportbundle_7ad0f472-368c-4aa8-af82-085be2d5bd3a_2024-07-18T09-03-34Z.zip)

**Comment by innobead** [comment]
@ibrokethecloud have we verified this before for Win VMs?

cc @harvester/qa

**Comment by charnet1019** [comment]
Can anyone help me take a look?
Thanks.

**Comment by ibrokethecloud** [comment]
are you able to add the following to vGPU section and try again? 
```
 virtualGPUOptions: 
          display:
            enabled: false
```

**Comment by noahgildersleeve** [comment]
I'm going to take a look and see if I can get it to repro and if there's a simple workaround.

**Comment by charnet1019** [comment]
> are you able to add the following to vGPU section and try again?
> 
> ```
>  virtualGPUOptions: 
>           display:
>             enabled: false
> ```


Thank you, resolved.

```yaml
gpus:
- deviceName: nvidia.com/NVIDIA_RTXA5000-2Q
   name: virtsmart-000017011
   virtualGPUOptions:
     display:
        enabled: false
```

**Comment by charnet1019** [comment]
But there is another issue, accessing the web console at this time will result in a black screen.

![image](https://github.com/user-attachments/assets/7a451905-d57a-4b43-8aad-80b8d0b3faa1)
