### ISSUE TITLE
[BUG] UI stucks on `Abort Migration` after clicking it

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6193]
**Describe the bug**

[BUG] UI stucks at `AbortMigration` after clicking it

**To Reproduce**
1. Start a VM migration
2. Abort the migration just after the migration starts
3. The VM menu is not refreshed automatically, the `Abort Migration` is still there
![image](https://github.com/user-attachments/assets/fa04b097-d19f-45e0-ad82-d32678f17675)

4. Forcely refresh the Web page, the `Migrate` menu is back
![image](https://github.com/user-attachments/assets/7e4ea2e9-e27b-4cd2-829a-ba8aca4c52d0)

code snippt
```
ui: pkg/harvester/models/kubevirt.io.virtualmachine.js

      {
        action:  'abortMigrationVM',
        enabled: !!this.actions?.abortMigration,
        icon:    'icon icon-close',
        label:   this.t('harvester.action.abortMigration')
      },


  abortMigrationVM() {
    this.doActionGrowl('abortMigration', {});
  }


     shell/plugins/dashboard-store/resource-class.js

  async doActionGrowl(actionName, body, opt = {}) {
    try {
      return await this.$dispatch('resourceAction', {
        resource: this,
        actionName,
        body,
        opt,
      });
    } catch (err) {
      this.$dispatch('growl/fromError', {
        title: this.$rootGetters['i18n/t']('generic.notification.title.error'),
        err:   err.data || err,
      }, { root: true });
    }
  }

```

**Expected behavior**

Update menu automatically.

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
Jira ticket https://jira.suse.com/browse/SURE-8731

**Comment by a110605** [comment]
The VM actions list is not updated after click Abort Migration (call POST /v1/harvester/kubevirt.io.virtualmachines/harvester-public/ubuntu2204?action=abortMigration).

The `abortMigration` should be `migrate` in action list after stop migration, that migrate button can show in operation menu.

![Screenshot_20240721_132900](https://github.com/user-attachments/assets/f5b16ff9-55d3-4f3b-8b6e-7cd4dd69dab4)

cc @torchiaf , @w13915984028

**Comment by w13915984028** [comment]
@a110605 @torchiaf

Not sure you are metioning this is a UI bug or backend bug.

When did UI re-fetch the actions from vm/vmi after clicking `Abort Migration`? A force refresh of the UI page can get things back.

**Comment by torchiaf** [comment]
> When did UI re-fetch the actions from vm/vmi after clicking `Abort Migration`? A force refresh of the UI page can get things back.

@w13915984028 The backend should send an update via websocket, once the migration is aborted, adding again the `migrate` action in the VM's actions list and removing the `abortMigration` action.
As you can see from Andy's screenshot, the action's list wasn't updated after the migration abort, this means the UI is not receiving the new actions list from the server.

In general, the UI can also hide/show an action based on other parameters, like resource's `status`/`labels`/`annotations`, but it would be better to receive the action's list from the server for consistency.

**Comment by w13915984028** [comment]
We had a pair troubleshooting on this, it worthy to write things down to know what happened:

The Websocket

(1) When open the Harvester webpage, UI creates 2 websockets to watch the backend resources. This is a general framework, it watchs certain CRD objects on the apiserver DB, as long as the `resourceVersion` field of object is updated, the websocket will notice this and notify the frontend components.

note: backend modules are in passive mode, they have no idea of those websockets. websocket is more like a polling robert on apiserver DB.

(2) The `actions` are dynamic fields added to CRD objects when they are feched from UI, thus UI adds different menus for objects

(1) (2) works well for most single-source objects.

Backto this issue:
(1) When click `migration`, the vm object is updated with a new `resourceVersion`, and websocket detects this, the `abortMigration` menu is correctly deduced.

(2) When click `abortMigration` quickly after above step, the vm object is also updated with a new `resourceVersion`; but the `virtualmachineinstancemigrations.kubevirt.io` object is not gone yet, the backend assumes the `abortMigration`. When the `virtualmachineinstancemigrations.kubevirt.io` object is gone, the vm object is NOT updated with a new `resourceVersion`. frontend has no chance to be notified again.

Apparently, when an action is related to >=2 crd objects, there will be sequence issues, more over, the slow deleting of k8s objects.

I will also check the backend code, how to handle this action correctly.

a. `migration` and then `abortmigration` quickly
b. after `abortmigration` then `migrate` quickly

When a `virtualmachineinstancemigrations.kubevirt.io` is there but with `deletionTimestamp`.

**Comment by w13915984028** [comment]
With move investigation and test, the bug is better to be fixed from backend.

Refer https://github.com/harvester/harvester/pull/6225

**Comment by rrajendran17** [comment]
verified on v1.4-00cd4ee-head and works as expected

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLzcvQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--8deab105c118fd4d101ca34e0093e6d0663de77e/6193image1.png" alt="6193image1.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBLy8vQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--62c432018f10c3fda2a3c2e0e20854ba2bdf0b7d/6193image2.png" alt="6193image2.png" />
