### ISSUE TITLE
[Question] How can I clear "Completed" status after VM restore?

### ISSUE THREAD

**Issue by dawid10353** [harvester/harvester#6194]
Hello,

how can I clear "Completed" status after VM restore?
Harvester v1.3.1

Screenshot:
![image](https://github.com/user-attachments/assets/aac0a5c0-f167-444e-b6fa-cd62bd86565b)

**Comment by devenkulkarni** [comment]
You may need to delete the completed restore from the harvester k8s cluster. We have identified it as a bug and as a workaround for now, you can delete the completed restore.

```
kubectl get virtualmachinerestores.harvesterhci -A
NAMESPACE   NAME                               TARGET_KIND      TARGET_NAME   COMPLETE   AGE     ERROR
default     restore-devendra-s3-backup-z5h5j   VirtualMachine   restored-vm   true       5m26s  
```

```
kubectl delete virtualmachinerestores.harvesterhci restore-devendra-s3-backup-z5h5 -n default
```

Note: You would need to change the name of restore as per your cluster and it shall help remove the `Restore` column from the UI.

**Comment by dawid10353** [comment]
> virtualmachinerestores.harvesterhci

But.. When I deleted "completed restore" using that commad:
![image](https://github.com/user-attachments/assets/09cb540a-9636-4b35-bc5e-3a5a2d1909f4)
The PVC for VM is deleted too...
![image](https://github.com/user-attachments/assets/33a89d81-b37f-4816-b985-07bc908cdc79)

**Comment by dawid10353** [comment]
It forces me to restore from backup again... And again I have "Completed" status.

**Comment by WebberHuang1118** [comment]
Hi @dawid10353 

The restoring VM's pvc has `ownerReferences` points to the matched CR `virtualmahcinerestore`, for example:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  ....
  name: restore-vm-b1-434fd2c1-fd7a-4c0f-bda7-9ac31becef13-disk-0
  namespace: default
  ownerReferences:
  - apiVersion: harvesterhci.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineRestore
    name: restore-vm-b1-5xcnx
    uid: 434fd2c1-fd7a-4c0f-bda7-9ac31becef13
  resourceVersion: "100298"
  uid: c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
spec:
  accessModes:
  - ReadWriteMany
  ....
  storageClassName: longhorn-image-l8mlc
  volumeMode: Block
  volumeName: pvc-c7db72ed-d9c9-4fee-a424-14a3cefbb0bb
```

so once the `virtualmachinerestore` CR is deleted, the PVC will turn into `Terminating` status. If the restoring VM is stopped, the PVC will be completely deleted.

Since it seems to be a cosmetics issue so far, I suggest not removing the `virtualmachinerestore` resource.
