### ISSUE TITLE
[BUG] number of replicas in the StorageClass ignored when downloading images

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#6197]
**Describe the bug**
- download new image. Use StorageClass, which has more than 1 replicas

**Expected behavior**
- expected, that downloaded image will have few replicas, as defined in the StorageClass

**Actual behavior**
- only one replica created for downloaded image
- that can be observed by looking at used storage in Longhorn UI

**Environment**
 - Harvester ISO version: 1.3.1
 - 2 nodes on bare metal DELL workstations + 1 witness on VM

**Additional context**
- when I create VM with the downloaded image (150GB) - at that moment I see that additional replicas are created. I can see that by looking at the Longhorn UI: the volume is in "Attaching" state and free space is decreasing for about 20 mins. That results in very slow VM starts: it stays in "Starting" state for 20+ mins, during which replicas created.

**Comment by FrankYang0529** [comment]
Hi @SlavikCA, do you have [support-bundle](https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle) for this? If yes, could you upload it? Thank you.

**Comment by SlavikCA** [comment]
Support bundle:
https://s3.fursov.family/shares/supportbundle_9ae6faf0-dfdf-48ab-ad8f-8a3686a01fac_2024-07-19T20-17-51Z.zip
