### ISSUE TITLE
[TASK] harvester-installer / baseos: update `yip`

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6199]
Running `go mod tidy` in harvester-installer now errors out:

```
go: downloading github.com/tredoe/osutil v1.3.6
go: github.com/mudler/yip@v0.0.0-20211129144714-088f39125cf7 requires
	github.com/mudler/entities@v0.0.0-20211108084227-d1414478861b requires
	github.com/tredoe/osutil/v2@v2.0.0-rc.16: reading github.com/tredoe/osutil/go.mod at revision v2.0.0-rc.16: unknown revision v2.0.0-rc.16
```

I don't know what happened to github.com/tredoe/osutil, but it doesn't look like they've got any sort of v2.0.0 release anymore. Meanwhile, github.com/mudler/yip has been superseded by github.com/rancher/yip.

To further confuse matters, out baseos uses github.com/Vicente-Cheng/yip which was previously forked off github.com/mudler/yip (see https://build.opensuse.org/projects/isv:Rancher:Harvester:ExtraPackages:Dev/packages/yip/files/_service?expand=1).

We should probably either:

1. Update go.mod in harvester-installer to point to github.com/Vicente-Cheng/yip, or,
2. Update go.mod in harvester-installer to point to github.com/rancher/yip, and also update the yip package in baseos to match.

Not super high priority (everything is working, right?) but we'll need to look at this before the next time someone wants to run `go mod tidy` in harvester-installer ;-)

cc @Vicente-Cheng

**Comment by Vicente-Cheng** [comment]
https://github.com/harvester/yip created.
Will link the OBS source to the above.

**Comment by Vicente-Cheng** [comment]
OBS updated (https://build.opensuse.org/package/show/isv:Rancher:Harvester:ExtraPackages:v1.4/yip)

The next sprint release will involve the new `yip` package.

**Comment by bk201** [comment]
Dep are updated and CI runs well.
