### ISSUE TITLE
set default template version when a new template is created

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#62]
**Description:**
set default template version when a new template is created

**Comment by guangbochen** [comment]
```E0820 05:11:37.247975       6 reflector.go:178] github.com/rancher/lasso/pkg/cache/cache.go:112: Failed to list *v1alpha1.VirtualMachineTemplateVersion: v1alpha1.VirtualMachineTemplateVersionList.Items: []v1alpha1.VirtualMachineTemplateVersion: v1alpha1.VirtualMachineTemplateVersion.Spec: v1alpha1.VirtualMachineTemplateVersionSpec.VM: v1alpha3.VirtualMachineSpec.Template: v1alpha3.VirtualMachineInstanceTemplateSpec.Spec: v1alpha3.VirtualMachineInstanceSpec.Domain: v1alpha3.DomainSpec.CPU: v1alpha3.CPU.Cores: readUint32: unexpected character: �, error found in #10 byte of ...|{"cores":"","sockets|..., bigger context ...|rue,"template":{"spec":{"domain":{"cpu":{"cores":"","sockets":1,"threads":1},"devices":{"disks":[{"d|...```

**Comment by aiwantaozi** [comment]
this is caused by the invalid type `Cores` should be int, but got `""`, then the cache was broken, now our crd missed the validation part, we could create another issue for the crd should include validation part

**Comment by guangbochen** [comment]
sure, before the CRD validation is added can we sync with UI to ensure the default value is set correctly with its required data type to avoid those errors, thanks.

**Comment by guangbochen** [comment]
link to PR https://github.com/rancher/harvester/pull/65

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/pull/65
