### ISSUE TITLE
[BUG] all of the nodes goes to the same node

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#620]
**Describe the bug**
All of the nodes I created using node driver in Rancher have landed on the same physical node. We need at least a soft-anti-affinity rule here

**To Reproduce**
1. create k8s cluster using harvester node driver in the Rancher
2. check VM on the Harvester page

**Expected behavior**
We need at least a soft-anti-affinity rule here

**Log**
N/A

**Environment:**
 - Harvester ISO version: v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Validated on master-621eedd7-head

Steps:

1. create k8s cluster using harvester node driver in the Rancher
2. check VM on the Harvester page

Result:
3 VMs are created on 3 harvester nodes respectively
