### ISSUE TITLE
[BUG] Upgrade from 1.2.2 to 1.3.1 stuck

### ISSUE THREAD

**Issue by johnwc** [harvester/harvester#6203]
**Describe the bug**
We attempted to upgrade to v1.3.1, the first node upgraded but the rest did not. Following one of your other issues, we attempted to restart the upgrade following the directions to delete the existing upgrade and start it again. Only after we did this, did we notice the known issue about this very specific thing where the fix is to restart a capi pod. So, we are stuck now with only one node upgraded, harvester UI displaying v1.3.1, longhorn UI displaying v1.6.2, one node on v1.27.13+rke2r1 and the rest on v1.26.15+rke2r1, and one node keeps getting set as cordoned like it is trying to continue the upgrade. I did see that the node that is being cordoned is waiting for a machine plan to be applied if that helps any. I will be creating a support bundle after this issue creation and emailing it to [harvester-support-bundle@suse.com](mailto:harvester-support-bundle@suse.com)

**Comment by bk201** [comment]
@FrankYang0529 Please help check, a quick scan of SB the cluster is wating:
```
    - lastTransitionTime: "2024-07-20T19:22:07Z"
      message: configuring etcd node(s) custom-29716d46e185,custom-5a9f02b8304b,custom-c3b245516405
      reason: Waiting
      status: Unknown
      type: ControlPlaneReady
```

There are 9 nodes but 11 CAPI machines in the cluster.

**Comment by johnwc** [comment]
> @FrankYang0529 Please help check, a quick scan of SB the cluster is wating:
> 
> ```
>     - lastTransitionTime: "2024-07-20T19:22:07Z"
>       message: configuring etcd node(s) custom-29716d46e185,custom-5a9f02b8304b,custom-c3b245516405
>       reason: Waiting
>       status: Unknown
>       type: ControlPlaneReady
> ```
> 
> There are 9 nodes but 11 CAPI machines in the cluster.

@bk201  Sorry, I don't know what SB stands for. Do you need me to run a command and share back with you? What do I need to do?

**Comment by DovydasNavickas** [comment]
SB is support bundle 😄

**Comment by johnwc** [comment]
@FrankYang0529 Do you need me to run a command and share back with you? What do I need to do?

**Comment by johnwc** [comment]
@FrankYang0529 I found the 2 orphaned machine configs, removed them and restarted the upgrade manually. It is now stuck at Upgrading System Service 50%. I sent the logs to the same email address.

![image](https://github.com/user-attachments/assets/68b61e4f-ae27-4ca0-988f-abd67a5c9bbb)

**Comment by johnwc** [comment]
@FrankYang0529 any suggestions or help?

**Comment by johnwc** [comment]
@bk201 @w13915984028 Can we get any help with this. Our harvester has been stuck half installed for over a week now.

**Comment by FrankYang0529** [comment]
Hi @johnwc, I was out last few days. I will take a look today.

**Comment by FrankYang0529** [comment]
Hi @johnwc, in the last upgrade log, I can find harvester pod repeats log like `node hyper04 is in upgrade pre-draining state, try to detach unused volumes`. Could you check whether there is VM workload on `hyper04`? If yes, you can try to manually migrate it to other host.

BTW, in the last attachment, it looks like there is only upgrade log. Could you send an email with both support-bundle and upgrade log? In upgrade log, we can only see pod log (including terminated pods). In support-bundle, we can see YAML and running pod log. Thank you for your patience.

**Comment by johnwc** [comment]
> Hi @johnwc, in the last upgrade log, I can find harvester pod repeats log like `node hyper04 is in upgrade pre-draining state, try to detach unused volumes`. Could you check whether there is VM workload on `hyper04`? If yes, you can try to manually migrate it to other host.

None of the servers are in that state, they all still say `Images preloaded`

> BTW, in the last attachment, it looks like there is only upgrade log. Could you send an email with both support-bundle and upgrade log? In upgrade log, we can only see pod log (including terminated pods). In support-bundle, we can see YAML and running pod log. Thank you for your patience.

@FrankYang0529 I just emailed both.

**Comment by johnwc** [comment]
@FrankYang0529 had a chance to look at the logs?

**Comment by FrankYang0529** [comment]
From support bundle, the cluster is like:

1. The `fleet-local/local` cluster waits for etcd nodes on custom-5a9f02b8304b (hyper02) and custom-c3b245516405 (hyper05).
2. From `rancher-system-agent.log` on both nodes, there is no obvious error log, so I think the error is not about running plan on both nodes.
3. From etcd logs on both nodes, there is no obvious error log either. The etcd version is `v3.5.9-k3s1-build20230802` on hyper02 and hyper05, but `v3.5.9-k3s1-build20240418` on hyper06. 
4. From `rke2-server.log` on both nodes, there is lot of proxy error like:
```
Proxy error: write failed: write tcp 127.0.0.1:9345->127.0.0.1:56994: write: connection reset by peer
```
5. From job list, we can see some system helm charts are not running. May you check why these jobs fail? There is no related pod log in the support bundle.
```
kube-system                  helm-install-rke2-canal                          0/1            12d         12d
kube-system                  helm-install-rke2-coredns                        0/1            12d         12d
kube-system                  helm-install-rke2-multus                         0/1            12d         12d
```

**Comment by johnwc** [comment]
@FrankYang0529 If these are supposed to be pods, I do not see any pods with these names under kube-system.

```
kube-system                  helm-install-rke2-canal                          0/1            12d         12d
kube-system                  helm-install-rke2-coredns                        0/1            12d         12d
kube-system                  helm-install-rke2-multus                         0/1            12d         12d
```

**Comment by johnwc** [comment]
@FrankYang0529 I do see three jobs with those names that are failed state.

![image](https://github.com/user-attachments/assets/6591ac1f-7f9b-4f87-bb11-7838887e62a9)

**Comment by FrankYang0529** [comment]
Yes, they're jobs. Can you find related pod logs? Thanks.

**Comment by johnwc** [comment]
@FrankYang0529 There is no pods for them. How do we get it to recreate the pods?

**Comment by FrankYang0529** [comment]
From helm-controller source code, we can remove failed job first and then remove `status` field in related `HelmChart` CR. This way can work on my cluster, but I'm not sure whether there is side effect.

https://github.com/k3s-io/helm-controller/blob/9c37be215ba63bf695ee396e02c014db14e202fb/pkg/controllers/chart/chart.go#L200-L222

**Comment by johnwc** [comment]
@FrankYang0529 so first delete the job, then edit the `kube-system/rke2-???` chart yaml to delete the entire status hierarchy?

Do I do each in any specific order?

**Comment by FrankYang0529** [comment]
> @FrankYang0529 so first delete the job, then edit the `kube-system/rke2-???` chart yaml to delete the entire status hierarchy?

Yes, but I observe that helm-controller doesn't add `status.jobName` automatically after creating a new job, so we may need to manually update `status.jobName` again after job is finished.

> Do I do each in any specific order?

No, I think there is no specific order.

**Comment by johnwc** [comment]
@FrankYang0529 Seeing these errors in pods now

```
2024-08-02T04:41:25.366783099Z Upgrading rke2-canal
2024-08-02T04:41:25.366867299Z + helm_v3 upgrade --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 rke2-canal /tmp/rke2-canal.tgz
2024-08-02T04:41:25.686614196Z Error: UPGRADE FAILED: chart requires kubeVersion: >= v1.27.13 which is incompatible with Kubernetes v1.26.15+rke2r1
2024-08-02T04:41:25.689842956Z + exit
```

```
2024-08-02T04:41:23.257851555Z Upgrading rke2-coredns
+ helm_v3 upgrade --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 rke2-coredns /tmp/rke2-coredns.tgz
Error: UPGRADE FAILED: chart requires kubeVersion: >= v1.27.13 which is incompatible with Kubernetes v1.26.15+rke2r1
+ exit
```

```
Upgrading rke2-multus
+ shift 1
+ helm_v3 upgrade --set-string global.clusterCIDR=10.52.0.0/16 --set-string global.clusterCIDRv4=10.52.0.0/16 --set-string global.clusterDNS=10.53.0.10 --set-string global.clusterDomain=cluster.local --set-string global.rke2DataDir=/var/lib/rancher/rke2 --set-string global.serviceCIDR=10.53.0.0/16 rke2-multus /tmp/rke2-multus.tgz
2024-08-02T04:43:13.446910985Z Error: UPGRADE FAILED: chart requires kubeVersion: >= v1.27.13 which is incompatible with Kubernetes v1.26.15+rke2r1
+ exit
```

**Comment by FrankYang0529** [comment]
It looks like the root cause is RKE2 update. Nodes hyper02 and hyper05 is still in `v1.26.15+rke2r1`. Only hyper06 is upgraded to `v1.27.13+rke2r1`. @bk201, we may need Rancher team to take a look as well. I'm not sure how to trigger RKE2 update on a node.

**Comment by FrankYang0529** [comment]
I can find another error is in `rke2-coredns-xxx` pods. Not sure whether there is network issue in the cluster.

```
[ERROR] plugin/errors: 2 grafana.com. A: read udp 10.52.8.72:39095->10.100.1.5:53: i/o timeout
[ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.52.8.72:41725->10.100.1.7:53: i/o timeout
[ERROR] plugin/errors: 2 grafana.com. AAAA: read udp 10.52.8.72:35587->10.100.1.5:53: i/o timeout
[ERROR] plugin/errors: 2 raw.githubusercontent.com. A: read udp 10.52.8.72:44832->10.100.1.7:53: i/o timeout
[ERROR] plugin/errors: 2 raw.githubusercontent.com. AAAA: read udp 10.52.8.72:48330->10.100.1.7:53: i/o timeout
```

**Comment by johnwc** [comment]
As far as I can tell, there is no network issue going on. Could it be canal maybe? @bk201 any thoughts on triggering RKE2 update?

**Comment by bk201** [comment]
> Following one of your other issues, we attempted to restart the upgrade following the directions to delete the existing upgrade and start it again. 

@johnwc I think Rancher is still upgrading the node, it's the remaining state from the previous deleted upgrade. It's not recommended to start over an upgrade in this status, but our webhook check didn't implement well. I'll suggest let's delete the on-going upgrade first and make the cluster stable first. Can you first try
- Delete the ongoing upgrade `hvst-upgrade-gnvpj`.
- Go to node `hyper02`. You should see the directory exist: `/run/systemd/system/rancher-system-agent.service.d` and two files exist in the directory: `10-harvester-upgrade.env  override.conf`, please delete the directory and run `systemctl daemon-reload`
- Go to node `hyper02` and run the command:
    ```
    /opt/rke2/bin/rke2 --version
    ```
- If the version is `v1.27.13+rke2r1`, restart the rke2 `systemctl restart --no-block rke2-server`
- Check if the node in `kubectl get nodes` becomes the version `v1.27.13+rke2r1`.
- If everything looks good, capture a support bundle and send it to us.

**Comment by johnwc** [comment]
@bk201 everything executed as you expected, just sent bundle.

**Comment by bk201** [comment]
@johnwc Thanks. The cluster moves on and I believe it's currently hit the known issue, please follow the check and workaround in the [doc](https://docs.harvesterhci.io/v1.3/upgrade/v1-2-2-to-v1-3-1#1-cluster-upgrade-stuck-after-the-first-node-is-upgraded). 

And then repeat the procedure in https://github.com/harvester/harvester/issues/6203#issuecomment-2268096464 for node `hyper05`. If you can join [Slack we can also help you there.](https://slack.rancher.io/)

**Comment by johnwc** [comment]
@bk201 It has something similar for the cluster status, but not of bootstrap but etcd. And the capi logs do not show those errors. With this knowledge, what should I do, continue with hyper05?

```yaml
  - lastUpdateTime: "2024-08-05T04:05:38Z"
    message: 'configuring etcd node(s) custom-c3b245516405: waiting for kubelet to
      update'
    reason: Waiting
    status: Unknown
    type: Provisioned
  - lastUpdateTime: "2024-08-05T04:05:38Z"
    message: 'configuring etcd node(s) custom-c3b245516405: waiting for kubelet to
      update'
    reason: Waiting
    status: Unknown
    type: Updated
```

capi log
```
I0723 16:49:53.199489       1 controller.go:228] "Starting workers" controller="machinedeployment" controllerGroup="cluster.x-k8s.io" controllerKind="MachineDeployment" worker count=10
I0723 16:49:53.199568       1 controller.go:228] "Starting workers" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" worker count=10
I0723 16:49:53.308989       1 tracker.go:57] "Adding watcher on external object" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="fleet-local/custom-d376c8cf3f50" namespace="fleet-l
ocal" name="custom-d376c8cf3f50" reconcileID=3bf09aeb-41eb-4518-b249-a0925f25784c Cluster="fleet-local/local" Cluster="fleet-local/local" groupVersionKind="rke.cattle.io/v1, Kind=RKEBootstrap"
I0723 16:49:53.309019       1 controller.go:151] "Starting EventSource" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" source="kind source: *unstructured.Unstructured"
I0723 16:49:53.310100       1 tracker.go:57] "Adding watcher on external object" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="fleet-local/local" namespace="fleet-local" name="lo
cal" reconcileID=f7e3a218-6c39-4850-bd09-662f3b6d05a9 groupVersionKind="rke.cattle.io/v1, Kind=RKECluster"
I0723 16:49:53.310135       1 controller.go:151] "Starting EventSource" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" source="kind source: *unstructured.Unstructured"
I0723 16:49:53.313098       1 tracker.go:57] "Adding watcher on external object" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="fleet-local/custom-d376c8cf3f50" namespace="fleet-l
ocal" name="custom-d376c8cf3f50" reconcileID=3bf09aeb-41eb-4518-b249-a0925f25784c Cluster="fleet-local/local" Cluster="fleet-local/local" groupVersionKind="rke.cattle.io/v1, Kind=CustomMachine"
I0723 16:49:53.313128       1 controller.go:151] "Starting EventSource" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" source="kind source: *unstructured.Unstructured"
I0723 16:49:53.317048       1 tracker.go:57] "Adding watcher on external object" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" Cluster="fleet-local/local" namespace="fleet-local" name="lo
cal" reconcileID=f7e3a218-6c39-4850-bd09-662f3b6d05a9 groupVersionKind="rke.cattle.io/v1, Kind=RKEControlPlane"
I0723 16:49:53.317086       1 controller.go:151] "Starting EventSource" controller="cluster" controllerGroup="cluster.x-k8s.io" controllerKind="Cluster" source="kind source: *unstructured.Unstructured"
I0723 16:49:53.399468       1 cluster_cache_tracker.go:298] "Creating cluster accessor for cluster \"fleet-local/local\" with the regular apiserver endpoint \"https://10.53.145.107/k8s/clusters/local\"" controller="machine
" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" Machine="fleet-local/custom-d376c8cf3f50" namespace="fleet-local" name="custom-d376c8cf3f50" reconcileID=3bf09aeb-41eb-4518-b249-a0925f25784c Cluster="fleet-loc
al/local" Cluster="fleet-local/local"
I0723 16:49:53.743748       1 controller.go:151] "Starting EventSource" controller="machine" controllerGroup="cluster.x-k8s.io" controllerKind="Machine" source="kind source: *v1.Node"
2024/07/23 17:18:23 http: TLS handshake error from 10.52.8.0:46406: EOF
2024/07/23 17:18:23 http: TLS handshake error from 10.52.8.0:46416: EOF
2024/07/23 17:18:23 http: TLS handshake error from 10.52.8.0:46422: EOF
2024/07/23 17:18:23 http: TLS handshake error from 10.52.8.0:46432: EOF
2024/07/23 17:18:25 http: TLS handshake error from 10.52.8.0:59874: EOF
2024/07/23 17:18:25 http: TLS handshake error from 10.52.8.0:59878: EOF
... nothing more but a ton of the same error
```

**Comment by johnwc** [comment]
@bk201 I joined the link for slack, but it was for Rancher and not Harvester

**Comment by FrankYang0529** [comment]
Some summary from last support bundle `supportbundle_735ed0c8-c74c-4a78-af06-03d5b9be91da_2024-08-07T07-16-46Z`.

After manually restart each node's RKE2 process, all nodes are upgraded to `v1.27.13+rke2r1`. The `RKEControlPlane` and CAPI cluster is ready. However, the provisioning cluster's Ready condition is unknown:

```yaml
  conditions:
  - lastUpdateTime: "2023-11-07T06:59:19Z"
    message: custom-49bfa698d325,custom-5a9f02b8304b,custom-93a5dd7408bf
    reason: Waiting
    status: Unknown
    type: Ready
```

We can't find related machine CR in the cluster and `machine-plan` secrets, so I think we may need a way to trigger reconciliation in the Rancher to correct the condition.

For rancher pod log, I can't find obvious error.

**Comment by FrankYang0529** [comment]
The upgrade is finished in user's cluster. The issues we encountered include:

* Orphan machines.
* Remove ongoing upgrade makes next upgrade is stuck in unready provisioning cluster.
* Certificate expire: https://github.com/harvester/harvester/issues/3863#issuecomment-1539681311
