### ISSUE TITLE
[BUG] Login page has 401 errors

### ISSUE THREAD

**Issue by Clashsoft** [harvester/harvester#6206]
**Describe the bug**
I cannot login because the login page has 401 unauthorized errors.

**To Reproduce**
1. Go to the Harvester URL.
2. See screenshot.

**Expected behavior**
Login form is shown.

**Support bundle**

N/A (cannot login)

**Environment**
 - Harvester ISO version: 1.3.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal, 3 nodes freshly installed.

**Additional context**
<img width="1919" alt="Screenshot 2024-07-22 at 11 06 58" src="https://github.com/user-attachments/assets/d7166812-f86e-4b18-948f-97c35c614aa9">

It used to work with 2 nodes. As soon as the third node joined, this problem appeared.
Any pointers to log files etc would be greatly appreciated.

**Comment by albinsun** [comment]
May try to generate SB manually
https://github.com/rancher/support-bundle-kit/blob/master/docs/standalone.md

**Comment by Clashsoft** [comment]
I think we fixed this. It seemed to be an issue with general network connectivity, e.g. the time server being unreachable, probably leading to failing https requests due to differing client/server times.

**Comment by ibrokethecloud** [comment]
Closing this issue. Please feel free to re-open or create a new one if you run into issues.
