### ISSUE TITLE
[BUG] regullar disconnected from UI due to SSL cert

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#621]
**Describe the bug**
I have been temporarily disconnected from UI twice. The first time it’s when I was configuring the backup and it seems node promotion is also happening, the second time is when I was adding a new image. The new image gets stuck in that case, and one of the harvester pods seems restarted (need to re-confirm the SSL certificate later). I’ve checked the Harvester server log but cannot see anything there.

**To Reproduce**
1. when the pod is restart

**Expected behavior**
1. make an enhancement of the SSL cert change
2. print logs on the harvester if has any

**Log**
N/A

**Environment:**
 - Harvester ISO version: v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
Depend on https://github.com/rancher/harvester/issues/632

**Comment by guangbochen** [comment]
Did not encounter this error after using the VIP entry point with `0.3-master-48c97ea7-head`, feel free to reopen it if needed.
