### ISSUE TITLE
[BUG] Upgrade from 1.3.0 to 1.3.1 had problems

### ISSUE THREAD

**Issue by DovydasNavickas** [harvester/harvester#6212]
**Describe the bug**

*As the upgrade succeeded for me in the end with quite a bit of intervention, I leave this as a probable troubleshooting for others.*

I ran the upgrade for 1.3.0 cluster to 1.3.1 and it got stuck on `Pre-draining`:
![image](https://github.com/user-attachments/assets/c8537286-890e-4703-bebd-811ea355e2e1)

I found this pod:
```sh
harvester-system/hvst-upgrade-qwsfm-pre-drain-compute-02-bgq89
```

And its logs said this on the loop:
```logs
Waiting for VM live-migration or shutdown...(count: 1)
+ '[' true ']'
++ get_running_vm_count
++ local vmioutput=/tmp/vmioutput.yaml
++ rm -f /tmp/vmioutput.yaml
++ local EXIT_CODE=0
++ kubectl get vmi -A -l kubevirt.io/nodeName=compute-02 -o yaml
++ [[ 0 -eq 0 ]]
+++ yq e '.items |  map(select(.status.phase!="Succeeded")) | length' /tmp/vmioutput.yaml
++ local count=1
++ echo 1
++ rm -f /tmp/vmioutput.yaml
+ vm_count=1
Waiting for VM live-migration or shutdown...(count: 1)
+ '[' 1 = 0 ']'
+ echo 'Waiting for VM live-migration or shutdown...(count: 1)'
+ sleep 5 
```

There were no user VMs running, so I checked:
```sh
kubectl get vmi -A
```

And got:
```logs
NAMESPACE          NAME                              AGE    PHASE     IP           NODENAME     READY
harvester-system   upgrade-repo-hvst-upgrade-qwsfm   147m   Running   10.52.1.94   compute-02   True
```

This VMI has been spun up by the upgrade itself and is not visible in the web UI.

When I deleted the VMI object and force deleted the pod as it was stuck for quite some time with errors about sending some event, it went to `Pre-drained` status:
![image](https://github.com/user-attachments/assets/6c86f7c8-7bfd-4ef3-81b5-c73183deea9e)

This spun the upgrade repo pod again, but nothing happened for a long time again. Thus, I rebooted the compute-02 node and it then successfully finished the upgrade.

![image](https://github.com/user-attachments/assets/9b1a0ac7-c127-4b81-a5e2-a50f6e0c4322)

Not sure where the problem was, but `pre-drain` that said there's a VM that upgrade itself spun up seems like a bug to me.

The last node waited for Longhorn volumes to be healthy and some of them had failed replicas on compute-02, which I restarted, so I deleted them, they were rebuilt and when all volumes were healthy, node was upgraded successfully without further intervention.

**To Reproduce**
Upgrade cluster from 1.3.0 to 1.3.1.

**Expected behavior**

Upgrade succeeds without user intervention. Especially when I stopped all of the VMs to make sure there were no Live migrations that could go wrong.

**Support bundle**

**Environment**
 - Harvester ISO version: 1.3.0 pre-upgrade, 1.3.1 post-upgrade
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 SuperMicro servers with Intel and AMD CPUs (I know that is not ideal and doesn't let Live Migrations. That is why I shutdown all of the VMs before the upgrade)

**Additional context**
I also hit this error at the start of the upgrade:
https://github.com/cloudnativelabs/kube-router/issues/383

I am not sure whether it was connected to the upgrade hurdles though.

**Comment by bk201** [comment]
@DovydasNavickas Thanks for sharing. When Harvester upgrades node `compute-02`, it will try to live-migrate the upgrade-repo VM (`upgrade-repo-hvst-upgrade-qwsfm`) out of the node to continue. There might be a reason that the VM is pending there, but it's hard to tell without an SB at that moment. Killing the VM makes it respawn on another node an the upgrade continues.

**Comment by DovydasNavickas** [comment]
Well, this makes sense and I know exactly why it failed to live-migrate.

My nodes have different CPUs, one is Intel and another one is AMD, so the live-migration doesn't work, unfortunately. This is fine for my case as I am hosting Kubernetes clusters and I don't need live-migration at all, killing the nodes is fine for me, but if the upgrade expects that live-migration will work, it won't in my case and it just gets stuck.

Is this is a supported case and is a valid bug or is not a supported case and should be closed as "won't fix"?

**Comment by bk201** [comment]
Unfortunately for the current design, the upgrade-repo VM is still needed and live-migrated (but killing it is a workaround in your case). As an enhancement, the [epic](https://github.com/harvester/harvester/issues/4926) has an item to eliminate the upgrade-repo VM, but it won't be implemented sooner.

We are also working on a document to explain the limitation of live migration between nodes with different CPUs.
- issue: https://github.com/harvester/harvester/issues/5603
- PR: https://github.com/harvester/docs/pull/614

**Comment by votdev** [comment]
Closing, see [previous comment](https://github.com/harvester/harvester/issues/6212#issuecomment-2244767275).
