### ISSUE TITLE
[BUG] harvester-installer: errors in validateConfig, PrepareWebooks and doInstall appear in console, but aren't logged

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6214]
**Describe the bug**
The last chunk of code in the install panel's `PreShow()` function calls `validateConfig()`, ` PrepareWebhooks()` and one of `configureInstalledNode()` or `doInstall()`. All these functions return an error value in `err`, but if `err` is set, all we do is call `printToPanel()` - we never actually log the error:

https://github.com/harvester/harvester-installer/blob/36ea2bf0c7f4e420b5ca4f1d1a75312240d1f9bc/pkg/console/install_panels.go#L2168-L2184

This means if you're using the installer interactively and one of these things fails, you can see what went wrong on the console display. But, if you're doing a PXE install and any of these things fail, and for some reason you _can't_ see the console and can only access the log in `/var/log/console.log` you will have no idea what went wrong.

**To Reproduce**
1. Set up a PXE install (e.g. vagrant-pxe-harvester from https://github.com/harvester/ipxe-examples), but mess up the config somehow, for example:
   ```
   install:
     mode: This ain't right
   ```
2. Boot a node, and confirm that the installation fails by checking the console:
   ![image](https://github.com/user-attachments/assets/aba039ea-2f50-4eca-b5af-62142c910e3e)
3. Check `/var/log/console.log` and note that there's no indication of the actual problem - in this example all we see is some preflight check failures which is quite misleading:
   ![image](https://github.com/user-attachments/assets/4672b2c6-0472-4fcf-921a-e40135efba55)

**Expected behavior**
Whatever failed is actually logged.

**Support bundle**
N/A

**Environment**
 - Harvester ISO version: v1.3.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized

**Additional context**
N/A

**Comment by irishgordo** [comment]
@tserong thanks for this enhancment :smile: :+1:  - this all looks good - I'll go ahead and close this out :smile: 

### Environment
* Harvester
  * Version: Harvester-v1.4-head
  * Profile: QEMU/KVM
  * ui-source: Auto


### Verification
### 1 Node Cluster
1. :green_circle: Logs are more useful given strange parameters in Harvester configuration at Install time w/ Harvester Installer 
   
   <details>
   <summary> <i>Given</i> a strange harvester install mode is specified 
   </summary>
         <ul>
          <li>our installer should be logging out the content of what has happened giving us more depth in the console about the yaml configuration it was provided</li>
          </ul>
   
    ![Screenshot from 2024-10-01 13-49-12](https://github.com/user-attachments/assets/c4c8aa48-49ab-4af4-b775-4701769a53ee)
    ![Screenshot from 2024-10-01 13-45-48](https://github.com/user-attachments/assets/85d5d201-c8ec-4e43-a665-fe966566727e)
