### ISSUE TITLE
[BUG] migration can not be canceled or selecting a target node

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#622]
**Describe the bug**
1. migrate doesn’t require destination node name? it should as It’s not node eviction.
2. The first time migration worked but later ones get stuck. It seems migration cannot be canceled. And there is no update in the Migration tab  even for the VM in the process of migration

**To Reproduce**
1. Go to the VM page and create new VM
2. doing a migrate of the VM
3. Can't select the target node

**Expected behavior**
1. User should be able to select the target node of the VM migration
2. Allow user to cancel the migration
3. Add more details to the migration tab of events or messages

**Log**
N/A

**Environment:**
 - Harvester ISO version:  v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by bk201** [comment]
> User should be able to select the target node of the VM migration

Looks lie It's a limitation of KubeVirt, [the spec only accepts the source VMI name](https://kubevirt.io/api-reference/v0.38.1/definitions.html#_v1_virtualmachineinstancemigrationspec).
It creates a target pod on nodes other than the node that the source VM is being migrated from. ([ref](https://github.com/kubevirt/kubevirt/blob/4987c1102c6d607dc80c2d07fae509ef83d56fb5/pkg/virt-controller/watch/migration.go#L381-L426))

**Comment by gitlawr** [comment]
We can implement it on our side before it is available in kubevirt API

**Comment by TangStone** [comment]
### Validate the version in master-95a5828a-head
**The nodes of harvester are as follows**
![image](https://user-images.githubusercontent.com/15829074/114635771-071b8a80-9cf8-11eb-8b05-aadd22a4fec0.png)
1. Verify the VM from the current node to the specified node
Target node list is correct
![image](https://user-images.githubusercontent.com/15829074/114635909-66799a80-9cf8-11eb-906a-d227875d9096.png)
In VM detail page, a Migration tab showing migration status，
![image](https://user-images.githubusercontent.com/15829074/114636024-a771af00-9cf8-11eb-95b6-b3f359ee268d.png)
Add more details to the migration tab of events or messages
![image](https://user-images.githubusercontent.com/15829074/114636269-2a930500-9cf9-11eb-9904-4500bfac199a.png)
Complete the migration to the specified target node
![image](https://user-images.githubusercontent.com/15829074/114636134-ddaf2e80-9cf8-11eb-9e0c-f412cce82831.png)
2. Allow user to cancel the migration
Migrate VMs to harvster nodes and cancel migration before completion
![image](https://user-images.githubusercontent.com/15829074/114636577-ed7b4280-9cf9-11eb-8e04-dcb213681ee9.png)
Cancel migration successfully
![image](https://user-images.githubusercontent.com/15829074/114636716-477c0800-9cfa-11eb-9ee2-4f588a916c8e.png)
