### ISSUE TITLE
[BUG] allow opt-in (instead of opt-out) to 'Collecting Longhorn Usage Metrics'

### ISSUE THREAD

**Issue by snuggles4553** [harvester/harvester#6221]
**Describe the bug**
By default, Longhorn usage metrics are turned on. A few problems with this: it's not obvious that this is happening, and the setting is hidden in the Longhorn web UI (which one might not even know exists, and one has to look for it on purpose).

**To Reproduce**
1. Installer Harvester.
2. Go to the Longhorn web UI.
3. Go to settings.
4. Observe that Collecting Longhorn Usage Metrics is enabled by default, and you weren't informed about this in any obvious way.

**Expected behavior**
I guess it would be best if:
Either Harvester should ask about this, and make it an "opt-in" choice (checkbox off by default).
Alternatively, Harvester could make it so this feature is off and don't ask about it.
The first option seems the most sensible.
Maybe the Harvester web UI could ask about this?
Or the Harvester installer?

**Environment**
 - Harvester ISO version: 1.3.1

**Comment by votdev** [comment]
I also suggest to rename it from `Usage Metrics` -> `Telemetry Data`. I think that's common wording these days.
