### ISSUE TITLE
[BUG] the built-in VM template does not work on the v0.2.0-rc1

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#623]
**Describe the bug**
the built-in VM template does not work on the v0.2.0-rc1

**To Reproduce**
1. go the VM page and create a VM using ISO template
2. The iso-image-base-template seems to not create the cd-rom volume,  only the root disk. 

**Expected behavior**
the built-in template should work with backing image changes.
**Log**

![image](https://user-images.githubusercontent.com/4569037/113081566-7cbd2c00-920b-11eb-90b1-5330b5e1164b.png)

**Environment:**
 - Harvester ISO version: v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
### Validate version master-621eedd7-head
Need image pop-up list? @futuretea 
![image](https://user-images.githubusercontent.com/15829074/114114464-79b0f280-9913-11eb-8485-caec0d672b92.png)
The v0.1.0 version of iso-image-base-template does not have this
![image](https://user-images.githubusercontent.com/15829074/114114913-694d4780-9914-11eb-984e-ce23c1c86e71.png)

**Comment by futuretea** [comment]
> ### Validate version master-621eedd7-head
> Need image pop-up list? @futuretea
> ![image](https://user-images.githubusercontent.com/15829074/114114464-79b0f280-9913-11eb-8485-caec0d672b92.png)
> The v0.1.0 version of iso-image-base-template does not have this
> ![image](https://user-images.githubusercontent.com/15829074/114114913-694d4780-9914-11eb-984e-ce23c1c86e71.png)

CC @WuJun2016

**Comment by WuJun2016** [comment]
@TangStone  @futuretea   is a bug, the image list should not be displayed

**Comment by TangStone** [comment]
### Validate version master-95a5828a-head
UI issues have been verified and modified
![image](https://user-images.githubusercontent.com/15829074/115029136-41537a80-9ef8-11eb-9e73-3e90e1c6b3c6.png)
Use the above template to create a VM
![image](https://user-images.githubusercontent.com/15829074/115029887-07cf3f00-9ef9-11eb-83d0-b97072fe4c20.png)
