### ISSUE TITLE
[BUG] Upgrade can be deleted in the "Upgrade Node" phase

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6258]
**Describe the bug**

Some users delete an upgrade when the upgrade enters the "Upgrade node" phase.
This makes debugging extremely hard if the user starts over another upgrade, we should prohibit the behavior.

**To Reproduce**
1. Upgrade a cluster
2. After "Upgrading system services" phase complete, delete the upgrade.
3. The upgrade is deleted.

**Expected behavior**

The upgrade should not be deleted.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

The webhook implemented in https://github.com/harvester/harvester/blob/e269dfe35b0cb822e2c2801c435fed4d9a3d2523/pkg/webhook/resources/upgrade/validator.go#L387-L405 is not enough to prevent the delete, we need more checks. And add an annotation to bypass the check.

**Comment by khushboo-rancher** [comment]
@noahgildersleeve Can we test this when we will do the upgrade testing during release testing.

**Comment by noahgildersleeve** [comment]
Validated with 2 node libvirt cluster upgrading from v1.3.2 -> v1.4-c6facee4-head. I waited for first node to upgrade then tried to delete upgrade. Verified as fixed.

![Screenshot_20241030_162147](https://github.com/user-attachments/assets/799171cb-9eb0-44e7-9083-9f234d8d98d0)
