### ISSUE TITLE
[BUG] The default setting shows an empty backup target

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#626]
**Describe the bug**
The default setting shows an empty backup target.

**To Reproduce**
1. Go to the settings page 
2. the backup target contains an error message `Empty backup target` on the default.

**Expected behavior**
1. [x] No error message should be displayed by default.
1. [x] Only need to display the endpoint of the backup target on the settings page.
2. [x] set default type to s3 when the backup target is empty.

**Log**

![image](https://user-images.githubusercontent.com/4569037/113112524-d76e7c00-923b-11eb-99d7-acda1544876c.png)

**Environment:**
 - Harvester ISO version: v0.2.0-rc1
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
### Validation in master-621eedd7-head
1. [x] No error message should be displayed by default.
![image](https://user-images.githubusercontent.com/15829074/113816560-96301c00-97a7-11eb-988d-cfb5f14b5aa0.png)
2. [x] Only need to display the endpoint of the backup target on the settings page.
![image](https://user-images.githubusercontent.com/15829074/113817680-49e5db80-97a9-11eb-9c5a-c605f107d58e.png)
![image](https://user-images.githubusercontent.com/15829074/114038815-c6191580-98b4-11eb-83f3-9ae438359755.png)

3. [x] set default type to s3 when the backup target is empty.
![image](https://user-images.githubusercontent.com/15829074/113816669-b5c74480-97a7-11eb-9a1a-6666bb47ac86.png)
4. VM backup created and restored successfully
![image](https://user-images.githubusercontent.com/15829074/114038307-560a8f80-98b4-11eb-8296-30ac2b1f2b23.png)
