### ISSUE TITLE
[ENHANCEMENT] Bump Rancher to 2.8.5 and RKE2 to 1.28.12

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6262]
**Is your enhancement related to a problem? Please describe.**

We should bump Rancher to v2.8.5 and RKE2 to v1.28.x (so we can upgrade to v1.29 in Harvester v1.4.0)

**Describe the solution you'd like**

Bump Rancher to v2.8.5 and RKE2 to v1.28.12 (so we can upgrade to v1.29 in Harvester v1.4.0)

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
a PR to bump Rancher to 2.8.5: https://github.com/harvester/harvester-installer/pull/765

**Comment by albinsun** [comment]
Test OK on `v1.3-81d64ff-head`, have Rancher <code>v2.8.5</code> and RKE2 <code>v1.28.12+rke2r1</code>.
Close as done.


## Environment
* harvester-`v1.3-81d64ff-head`
  * Profile: 1 and 2 nodes QEMU/KVM (8C/16G/500G)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> Setup a single node cluster
   </summary>

   ![image](https://github.com/user-attachments/assets/2437cf9a-607e-4861-b658-1808e84769d6)
   </details>

1. <details>
   <summary> Check version is Rancher <code>v2.8.5</code> and RKE2 <code>v1.28.12</code>
   </summary>

   * CLI
     ![image](https://github.com/user-attachments/assets/67757c59-048f-4c60-b783-acbe50e2f273)
   * UI
     ![image](https://github.com/user-attachments/assets/784083b5-4561-41fe-8031-f848b1de93e6)
     ![image](https://github.com/user-attachments/assets/3985de88-a1de-4ec1-827f-262589562968)
   </details>

1. <details>
   <summary> Join 2nd node
   </summary>
   
   ![image](https://github.com/user-attachments/assets/ed3daca1-134e-4827-84f2-c95eef17eebb)
   </details>

1. <details open>
   <summary> Check version is Rancher <code>v2.8.5</code> and RKE2 <code>v1.28.12</code>
   </summary>
   
   * CLI
     ![image](https://github.com/user-attachments/assets/dd48ad32-08b7-455d-999c-6d656fcb7cc7)
   * UI
     ![image](https://github.com/user-attachments/assets/a005df31-b1bc-4197-9247-eefff96f3284)
     ![image](https://github.com/user-attachments/assets/f515c781-28e6-47a0-9555-9e0701042266)
   </details>
