### ISSUE TITLE
[BUG] Single-replica volume may break Harvester maintenance mode

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6266]
**Describe the bug**

Single-replica volume may break Harvester maintenance mode

**To Reproduce**
1. Create a single-replica storageclass
2. Create a VM which uses this single-replica storageclass to create volume
3. After VM is running, observe the scheduled node (the single-replica volume is scheduled to this node), stop the VM
4. Put the observed node into `maintenance mode`
5. There are continuously reported such error on Harvester pod, it fails to evict LH pod

>time="2024-08-05T09:51:06Z" level=info msg="evicting pod longhorn-system/instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7"
time="2024-08-05T09:51:06Z" level=info msg="error when evicting pods/\"instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7\" -n \"longhorn-system\" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget."

6. The node will not enter `maintenance mode` as expected.

The root cause is that the LH will check there is at least one another PDB alive before allowing killing the pdb for the drained node, but for single-replica volume, it makes no sense. The global setting also does not solve all situations.

new debug log
>time="2024-08-05T15:07:41Z" level=info msg="Node instance-manager-68cd2514dd3f6d59b95cbd865d5b08f7 is marked unschedulable but removing harv2 PDB is blocked: no pdb on another node, wait " func="controller.(*InstanceManagerController).syncInstanceManagerPDB" file="instance_manager_controller.go:730" controller=longhorn-instance-manager node=harv2

The global setting can't solve all scenarios.

```
longhorn-system   node-drain-policy                                                 block-if-contains-last-replica                47d
```

**Expected behavior**

Enter maintenance node as expected.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Observed on PR https://github.com/longhorn/longhorn-manager/pull/3045

related issues:
https://github.com/longhorn/longhorn/issues/9183
https://github.com/longhorn/longhorn/issues/5910#issuecomment-2269316423
https://github.com/harvester/harvester/issues/6264

**Comment by w13915984028** [comment]
For Harvester, seems we need to set https://longhorn.io/docs/1.6.0/references/settings/#node-drain-policy to `allow-if-replica-is-stopped` instead of the default option `block-if-contains-last-replica`.

**Comment by w13915984028** [comment]
About test plan:

1. For new installation, per https://github.com/harvester/harvester-installer/pull/788#issue-2450000964

2. For upgrade: per https://github.com/harvester/harvester/pull/6276#issue-2451185837

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
- Follow step to reproduce in https://github.com/harvester/harvester/issues/6266#issue-2448952654
