### ISSUE TITLE
[ENHANCEMENT] Allow update the default value of Harvester settings from Chart

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6277]
**Is your enhancement related to a problem? Please describe.**

Observed this weird value from a SB:

```
- apiVersion: harvesterhci.io/v1beta1
  default: '{}'
  kind: Setting
  metadata:
    creationTimestamp: "2024-05-28T18:04:11Z"
    generation: 40
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:default: {}
        f:status: {}
      manager: harvester
      operation: Update
      time: "2024-07-26T14:21:10Z"
    name: support-bundle-image
    resourceVersion: "86812263"
    uid: 2662b6a9-17b0-4227-88e6-df8568c37e76
  status: {}
```

A good value looks:
```
settings.harvesterhci.io support-bundle-image -oyaml
apiVersion: harvesterhci.io/v1beta1
default: '{"repository":"rancher/support-bundle-kit","tag":"master-head","imagePullPolicy":"IfNotPresent"}'
kind: Setting
metadata:
  creationTimestamp: "2024-08-15T19:48:37Z"
  generation: 1
  name: support-bundle-image
  resourceVersion: "6646"
  uid: 01952165-f164-4edd-bc62-e5afa52fcfd8
status: {}
```

With the PR https://github.com/harvester/harvester/pull/1771, below log is also observed on Harvester cluster bootstrap stage, as the `App` object is earlier that `Settings.harvesterhci.io` object. But it does no harm as it will sccess finally.

```
time="2024-08-15T19:48:36Z" level=info msg="Starting monitoring.coreos.com/v1, Kind=Alertmanager controller"
time="2024-08-15T19:48:36Z" level=error msg="error syncing 'harvester-system/harvester': handler harvester-setting-controller: settings.harvesterhci.io \"support-bundle-image\" not found, requeuing"
time="2024-08-15T19:48:36Z" level=error msg="error syncing 'harvester-system/harvester': handler harvester-setting-controller: settings.harvesterhci.io \"support-bundle-image\" not found, requeuing"
time="2024-08-15T19:48:36Z" level=error msg="error syncing 'harvester-system/harvester': handler harvester-setting-controller: settings.harvesterhci.io \"support-bundle-image\" not found, requeuing"
```

**Describe the solution you'd like**

tasks
- [ ] https://github.com/harvester/harvester/pull/6358
- [ ] https://github.com/harvester/docs/pull/624
- [ ] TBD: remove the `onApp` controller to avoid depends on Rancher App CRD

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
One cluster was upgraded to v1.3.1 from v1.2.2, and the SB image default value was set to nil.

```
- apiVersion: harvesterhci.io/v1beta1
  kind: Upgrade
  metadata:
    annotations:
      harvesterhci.io/image-cleanup-plan-completed: "true"
    creationTimestamp: "2024-06-28T15:14:26Z"

    - lastUpdateTime: "2024-06-28T15:32:15Z"
      status: "True"
      type: SystemServicesUpgraded
      
    previousVersion: v1.2.2
    repoInfo: |
      release:
          harvester: v1.3.1
          harvesterChart: 1.3.1
          os: Harvester v1.3.1
          kubernetes: v1.27.13+rke2r1
          rancher: v2.8.3
          monitoringChart: 103.0.3+up45.31.1
          minUpgradableVersion: v1.2.2
    upgradeLog: hvst-upgrade-jsgz2-upgradelog
```

And the setting is:
```
- apiVersion: harvesterhci.io/v1beta1
  default: '{}'
  kind: Setting
  metadata:
    creationTimestamp: "2024-05-28T18:04:11Z"
    generation: 40
    managedFields:
    - apiVersion: harvesterhci.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        f:default: {}
        f:status: {}
      manager: harvester
      operation: Update
      time: "2024-07-26T14:21:10Z"
    name: support-bundle-image
    resourceVersion: "86812263"
    uid: 2662b6a9-17b0-4227-88e6-df8568c37e76
  status: {}
  

upgrade crd object:


  spec:
    image: "null"
    logEnabled: true
    version: v1.3.1
  status:
    conditions:
    - lastUpdateTime: "2024-06-28T16:20:29Z"
      status: "True"
      type: Completed
    - lastUpdateTime: "2024-06-28T15:15:11Z"
      status: "True"
      type: LogReady
    - lastUpdateTime: "2024-06-28T15:16:16Z"
      status: "True"
      type: ImageReady
    - lastUpdateTime: "2024-06-28T15:19:51Z"
      status: "True"
      type: RepoReady
    - lastUpdateTime: "2024-06-28T15:27:24Z"
      status: "True"
      type: NodesPrepared
    - lastUpdateTime: "2024-06-28T15:32:15Z"
      status: "True"
      type: SystemServicesUpgraded
    - lastUpdateTime: "2024-06-28T16:20:29Z"
      status: "True"
      type: NodesUpgraded
    imageID: harvester-system/hvst-upgrade-jsgz2
    nodeStatuses:
      s37570031:
        state: Succeeded
      s37570032:
        state: Succeeded
      s37570033:
        state: Succeeded
    previousVersion: v1.2.2
    repoInfo: |
      release:
          harvester: v1.3.1
          harvesterChart: 1.3.1
          os: Harvester v1.3.1
          kubernetes: v1.27.13+rke2r1
          rancher: v2.8.3
          monitoringChart: 103.0.3+up45.31.1
          minUpgradableVersion: v1.2.2
    upgradeLog: hvst-upgrade-jsgz2-upgradelog  


the controller depends on below object to update the setting:

- apiVersion: catalog.cattle.io/v1
  kind: App
  metadata:
    annotations
    
        support-bundle-kit:
          image:
            imagePullPolicy: IfNotPresent
            repository: rancher/support-bundle-kit
            tag: v0.0.38
``` 

code path: 

https://github.com/harvester/harvester/blob/0fa939f85ea57148160b9bd5fa48125906e97c5e/pkg/controller/master/setting/support_bundle_image.go#L21

**Comment by w13915984028** [comment]
Refer https://github.com/harvester/harvester-installer/pull/813#issuecomment-2290923491

Need to check if below issues are valid.

==
Both Rancher and Harvester, has the setting which was initialized from Source code, instead of chart element like configmap. And this setting has a default value.

https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/pkg/settings/settings.go#L47

Rancher shell-image
```
harv31:/home/rancher # kubectl get settings.management.cattle.io shell-image -oyaml
apiVersion: management.cattle.io/v3
customized: false
default: rancher/shell:v0.1.23
kind: Setting
metadata:
  creationTimestamp: "2024-08-06T13:05:10Z"
  generation: 1
  name: shell-image
  resourceVersion: "1358"
  uid: 4752640a-6b51-46ac-a6e7-24568a9af084
source: ""
value: ""
```
That will bring potential issues like:

When such a setting was created on say Harvester v1.3.1 with default value A; after upgraded to v1.4.0, the default value A may not be updated to the new default value B on Harvester v1.4.0. (need to confirm). User may click `reset default value` on Harvester UI.

When user set a value on v1.3.1, but after upgrade to v1.4.0, the default value is newer than the user set value, should we revert the user set value automatically?  e.g., the continuously upgraded `support-bundle-kit` image.

LH has a configmap to init the settings from chart; and the controller checks the configmap to decide which value should be adopt, looks to be a bit better.

**Comment by w13915984028** [comment]
With some investigation and test:
(1) If the `default value` field of a setting is defined in the code,

https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/pkg/settings/settings.go#L47

(2) Then it will be updated to the CRD object `settings.harvesterhci.io` when Harvester POD starts to run
https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/pkg/controller/global/settings/register.go#L116

(3) For those settings which does not set a default value in the code, the story will vary:

A. support-bundle-image:

https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/pkg/controller/global/settings/register.go#L50

https://github.com/harvester/harvester/blob/78193016883c6738a12125dd4c5349d18709bd86/pkg/controller/master/supportbundle/controller.go#L53

it also watchs  `app` crd object and then update the `default` value of setting, always update the default value per harvester chart.
https://github.com/harvester/harvester/blob/4e94f46e2f40fcf1cd6efd4530e63870b6945a5f/pkg/controller/master/setting/handler.go#L196

need to check why old valus was still there:
https://github.com/harvester/harvester/issues/6277#issuecomment-2271932861

**Comment by w13915984028** [comment]
PR for v1.4 has been merged, move forward.

https://github.com/harvester/harvester/pull/6480

**Comment by w13915984028** [comment]
Test plan: 

For the newly installed or upgraded cluster, in the harvester settings `support-bundle-image`, the `default` field should always point to the `rancher/support-bundle-kit` image tag which was packed into the `new/upgrade-target` ISO.

```
settings.harvesterhci.io support-bundle-image -oyaml
apiVersion: harvesterhci.io/v1beta1
default: '{"repository":"rancher/support-bundle-kit","tag":"master-head","imagePullPolicy":"IfNotPresent"}'
kind: Setting
metadata:
..
  name: support-bundle-image
..
```

**Comment by brandboat** [comment]
Test OK on [v1.4.0-rc1](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc1), close as fixed.

## Environment
* [v1.4.0-rc1](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc1)
  * Profile: 1 node QEMU/KVM (8C/16G/250G)
  * ui-source: `Auto`

## Test Steps
- In v1.4.0-rc1, check the setting `support-bundle-image` default value in tag is [`v0.0.44`](https://github.com/harvester/harvester/blob/79af4198fbd8b9745933cfa7907ba39ac88897db/deploy/charts/harvester/values.yaml#L507)
- Upgrade to master from v1.4.0-rc1, check the setting `support-bundle-image` default value in tag is [`master-head`](https://github.com/harvester/harvester/blob/89628d3927553a0a858d11e6071c3274c15e601e/deploy/charts/harvester/values.yaml#L507)
- Also check in both v1.4.0-rc1 and master versions, we can download support-bundle successfully.

**Comment by brandboat** [comment]
BTW, I noticed that a backport PR for v1.3 has been opened, but there’s no corresponding GitHub issue to track this for v1.3.
@w13915984028 , do we need to open another issue ?

**Comment by w13915984028** [comment]
@brandboat Thanks, v1.3 issue #6725 is added.
