### ISSUE TITLE
[ENHANCEMENT] [v1.3.2] minor updates

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6283]
**Is your enhancement related to a problem? Please describe.**

minor updates for v1.3.2 release, including:

- [x] https://github.com/harvester/harvester-installer/pull/790
- [x] https://github.com/harvester/harvester-installer/pull/813
- [x] https://github.com/harvester/harvester/pull/6347

**Describe the solution you'd like**

The whole Harvester cluster will does not depends on shell v0.0.24 relase; the image is not packed into Harvester ISO; only v0.0.26.

The air-gapped installed should success; the normall installation should have no v0.0.24 image accidently pulled from docker hub to local.

The upgrade path to v1.3.2 should also not depend on shell v0.024.

**Describe alternatives you've considered**

**Additional context**

manual cherry pick of
issue: https://github.com/harvester/harvester/issues/6166
pr: https://github.com/harvester/harvester-installer/pull/766

**Comment by w13915984028** [comment]
From @mallardduck
https://github.com/harvester/harvester-installer/pull/766#issuecomment-2261336583

> From my understanding Harvester considers the last 2 minors as the maintained versions; so currently 1.3 and 1.2 - but when 1.4.0 releases it will be 1.3 and 1.4. If this is correct I am wondering if we can backport (at least just the shell changes) to Harvester 1.3 as well for security benefits?
> 
> This same version of Shell can be used in both Rancher 2.7 and 2.8 versions, so if the Harvester 1.3 branch uses similar k8s/rancher versions, then this can be safe there too.
> 
> Additionally, if the version of shell that Harvester embedded Rancher uses could be updated too that would be good. Not sure if there's a mechanism on the installer to do that, but changing the shell version that rancher uses can be done via:
> 
> `kubectl patch settings.management.cattle.io shell-image --type merge -p '{"value":"rancher/shell:v0.1.26"}'`

**Comment by bk201** [comment]
@w13915984028 is the issue ready for testing?

**Comment by w13915984028** [comment]
@bk201 
Harvester installer shell image is bumped, merged and can be tested now;

Patch Rancher is not started yet.

**Comment by w13915984028** [comment]
Latest update: refer: https://github.com/harvester/harvester-installer/pull/813

<del>
Test on `patch rancher setting`:

(1) Drop the `docker.io/rancher/shell:v0.1.24` image and don't pack it into Harvester ISO

https://github.com/harvester/harvester-installer/blob/9c01e92131192b58b299b04b357a1feb68bac59d/scripts/images/rancher-images.txt#L21

The test result is: the Harvester cluster can't finish the bootstrap. `rke2-server.service` can't be ready. The `bootstrap` itself failed.

Harvester even has no chance to patch the shell-image setting yet.

rancherd:

```
...
Aug 14 11:53:02 harv21 rancherd[2071]: time="2024-08-14T11:53:02Z" level=info msg="No image provided, creating empty working directory /var/lib/rancher/rancherd/plan/work/20240814-114835-applied.pla>
Aug 14 11:53:02 harv21 rancherd[2071]: time="2024-08-14T11:53:02Z" level=info msg="Running command: /usr/bin/rancherd [retry /var/lib/rancher/rke2/bin/kubectl -n fleet-local wait --for=condition=Pro>
Aug 14 11:53:32 harv21 rancherd[2071]: time="2024-08-14T11:53:32Z" level=info msg="[stderr]: error: timed out waiting for the condition on clusters/local"
Aug 14 11:53:32 harv21 rancherd[2071]: time="2024-08-14T11:53:32Z" level=info msg="[stderr]: time=\"2024-08-14T11:53:32Z\" level=error msg=\"will retry failed command [/var/lib/rancher/rke2/bin/kube>
Aug 14 11:54:17 harv21 rancherd[2071]: time="2024-08-14T11:54:17Z" level=info msg="[stderr]: error: timed out waiting for the condition on clusters/local"
Aug 14 11:54:17 harv21 rancherd[2071]: time="2024-08-14T11:54:17Z" level=info msg="[stderr]: time=\"2024-08-14T11:54:17Z\" level=error msg=\"will retry failed command [/var/lib/rancher/rke2/bin/kube>
Aug 14 11:55:04 harv21 rancherd[2071]: time="2024-08-14T11:55:04Z" level=info msg="[stderr]: E0814 11:55:04.562331   28980 memcache.go:265] couldn't get current server API group list: Get \"https://>
Aug 14 11:55:36 harv21 rancherd[2071]: time="2024-08-14T11:55:36Z" level=info msg="[stderr]: E0814 11:55:36.565020   28980 memcache.go:265] couldn't get current server API group list: Get \"https://>
Aug 14 11:56:08 harv21 rancherd[2071]: time="2024-08-14T11:56:08Z" level=info msg="[stderr]: E0814 11:56:08.571216   28980 memcache.go:265] couldn't get current server API group list: Get \"https://>
Aug 14 11:56:40 harv21 rancherd[2071]: time="2024-08-14T11:56:40Z" level=info msg="[stderr]: E0814 11:56:40.575436   28980 memcache.go:265] couldn't get current server API group list: the server was>

```

rke2-server:
```
...
ug 14 11:49:08 harv21 rke2[2214]: time="2024-08-14T11:49:08Z" level=info msg="Starting batch/v1, Kind=Job controller"
Aug 14 11:49:08 harv21 rke2[2214]: time="2024-08-14T11:49:08Z" level=error msg="error syncing 'kube-system/rke2-coredns': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2>
Aug 14 11:49:08 harv21 rke2[2214]: time="2024-08-14T11:49:08Z" level=error msg="error syncing 'kube-system/rke2-canal': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2-c>
Aug 14 11:49:08 harv21 rke2[2214]: time="2024-08-14T11:49:08Z" level=info msg="Reconciling snapshot ConfigMap data"
Aug 14 11:49:09 harv21 rke2[2214]: time="2024-08-14T11:49:09Z" level=error msg="error syncing 'kube-system/rke2-ingress-nginx': handler helm-controller-chart-registration: helmcharts.helm.cattle.io >
Aug 14 11:49:10 harv21 rke2[2214]: time="2024-08-14T11:49:10Z" level=info msg="Updating TLS secret for kube-system/rke2-serving (count: 11): map[listener.cattle.io/cn-10.53.0.1:10.53.0.1 listener.ca>
Aug 14 11:49:10 harv21 rke2[2214]: time="2024-08-14T11:49:10Z" level=info msg="Updating TLS secret for kube-system/rke2-serving (count: 11): map[listener.cattle.io/cn-10.53.0.1:10.53.0.1 listener.ca>
Aug 14 11:49:10 harv21 rke2[2214]: time="2024-08-14T11:49:10Z" level=info msg="Labels and annotations have been set successfully on node: harv21"
Aug 14 11:49:11 harv21 rke2[2214]: time="2024-08-14T11:49:11Z" level=info msg="Active TLS secret kube-system/rke2-serving (ver=390) (count 11): map[listener.cattle.io/cn-10.53.0.1:10.53.0.1 listener>
Aug 14 11:49:11 harv21 rke2[2214]: time="2024-08-14T11:49:11Z" level=error msg="error syncing 'kube-system/rke2-metrics-server': handler helm-controller-chart-registration: helmcharts.helm.cattle.io>
Aug 14 11:49:12 harv21 rke2[2214]: time="2024-08-14T11:49:12Z" level=error msg="error syncing 'kube-system/rke2-multus': handler helm-controller-chart-registration: helmcharts.helm.cattle.io \"rke2->
Aug 14 11:49:19 harv21 rke2[2214]: time="2024-08-14T11:49:19Z" level=info msg="Adding node harv21-b9496a00 etcd status condition"
Aug 14 11:49:22 harv21 rke2[2214]: time="2024-08-14T11:49:22Z" level=info msg="Tunnel authorizer set Kubelet Port 0.0.0.0:10250"
Aug 14 11:51:15 harv21 rke2[2214]: time="2024-08-14T11:51:15Z" level=error msg="error syncing 'kube-system/rke2-ingress-nginx': handler helm-controller-chart-registration: DesiredSet - Replace Wait >
Aug 14 11:53:03 harv21 systemd[1]: Stopping Rancher Kubernetes Engine v2 (server)...
Aug 14 11:53:03 harv21 rke2[2214]: time="2024-08-14T11:53:03Z" level=info msg="Shutting down /v1, Kind=ServiceAccount workers"
Aug 14 11:53:03 harv21 rke2[2214]: time="2024-08-14T11:53:03Z" level=info msg="Shutting down k3s.cattle.io/v1, Kind=ETCDSnapshotFile workers"
Aug 14 11:53:03 harv21 rke2[2214]: time="2024-08-14T11:53:03Z" level=fatal msg="context canceled"
Aug 14 11:53:03 harv21 systemd[1]: rke2-server.service: Main process exited, code=exited, status=1/FAILURE
Aug 14 11:53:03 harv21 systemd[1]: rke2-server.service: Failed with result 'exit-code'.
Aug 14 11:53:03 harv21 systemd[1]: rke2-server.service: Unit process 2524 (containerd-shim) remains running after unit stopped.
Aug 14 11:53:03 harv21 systemd[1]: rke2-server.service: Unit process 2525 (containerd-shim) remains running after unit stopped.
Aug 14 11:53:03 harv21 systemd[1]: rke2-server.service: Unit process 2693 (containerd-shim) remains running after unit stopped.

```


With some initial investigation, the default image `v0.1.24` was used in early stages before we can path the rancher-setting.
```
pkg/settings/setting.go:	ShellImage                          = NewSetting("shell-image", "rancher/shell:v0.1.24")

pkg/catalogv2/helmop/operation.go:			GenerateName: "helm-operation-",
pkg/catalogv2/helmop/operation.go:			GenerateName: "helm-operation-",
pkg/catalogv2/helmop/operation.go:							SecretName: "helm-operation-",
pkg/controllers/dashboard/helm/operations.go:	relatedresource.Watch(ctx, "helm-operation", o.findOperationsFromPod, operations, pods)
pkg/controllers/dashboard/helm/operations.go:	catalogcontrollers.RegisterOperationStatusHandler(ctx, operations, "", "helm-operation", o.onOperationChange)
```

also note https://github.com/rancher/rancher/issues/42396

(2) Restore the `docker.io/rancher/shell:v0.1.24` image, the newly installed cluster run smoothly.


**Summary:**
1. The shellimage is hard-coded on Rancher code like beow, and there seems no easy solution to change it in the very beginning. 
```
pkg/settings/setting.go
ShellImage                          = NewSetting("shell-image", "rancher/shell:v0.1.24")
```

2. A formal solution will be like below, set a param and pass to Rancher

https://github.com/harvester/harvester-installer/blob/9c01e92131192b58b299b04b357a1feb68bac59d/pkg/config/templates/rancherd-config.yaml#L13

3.Given the fact that the default shell image can't be patched from the beginning, it is also not suggested to patch it on the Harvester upgrade path, to avoid importing new issues.

We keep this as a known CVE issue on v1.3.2.

</del>

cc @bk201 @@mallardduck

**Comment by mallardduck** [comment]
> Given the fact that the default shell image can't be patched from the beginning,   

I believe this is incorrect.

`NewSetting` is a helper to generate a setting CRD which can be overridden via ENV vars.
It should be configurable by setting `CATTLE_SHELL_IMAGE` on the EVN of the Rancher pod/deployment.

Adding:

```
extraEnv:
  - name: CATTLE_SHELL_IMAGE
    value: "rancher/shell:v0.1.24"
```

To, I believe, this file: https://github.com/harvester/harvester-installer/blob/master/package/harvester-os/files/usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml Would be how we can inform rancher to use a different version of shell from the first time the pod comes online.

**Comment by w13915984028** [comment]
@mallardduck I did not find this param before, let me check and test if it can work, thanks.

**Comment by w13915984028** [comment]
@mallardduck Could you share Rancher code path where this ENV is defined and used? I can't search `CATTLE_SHELL_IMAGE` from Rancher code, thanks.

**Comment by mallardduck** [comment]
Here: https://github.com/rancher/rancher/blob/60847a88d8660e4b397bcf54119d3fd31703537f/pkg/settings/setting.go#L128

Any `NewSetting` can be converted to an ENV variable to set them. And the actual retrieval of the ENV value is encapsulated here:

https://github.com/rancher/rancher/blob/60847a88d8660e4b397bcf54119d3fd31703537f/pkg/controllers/dashboardapi/settings/settings.go#L35

You will find that:

- If the setting exists as en equivalent ENV, it will return/use that value,
- Otherwise it checks setting cache and will then:
- return the default if no value set, or will return the value.

**Comment by w13915984028** [comment]
how is this `CATTLE_SHELL_IMAGE` converted to 
```
ShellImage                          = NewSetting("shell-image", "rancher/shell:v0.1.24")
```
?

**Comment by mallardduck** [comment]
At value lookup/fetch time per: https://github.com/rancher/rancher/blob/60847a88d8660e4b397bcf54119d3fd31703537f/pkg/controllers/dashboardapi/settings/settings.go#L35

The name is composed to the ENV var here: https://github.com/rancher/rancher/blob/main/pkg/settings/setting.go#L480

**Comment by w13915984028** [comment]
@mallardduck It works as expected, thanks.

https://github.com/harvester/harvester-installer/pull/813#issue-2466341844

**Comment by irishgordo** [comment]
@w13915984028 do we have a test plan for this?

**Comment by w13915984028** [comment]
cc @irishgordo  Test Plan:

In a newly installed cluster
(1) Enable rancher-monitoring addon, it should sucess, and the container images on any cluster node should have only `docker.io/rancher/shell:v0.1.26`
```
$ crictl image ls | grep shell
docker.io/rancher/shell                                                     v0.1.26                                     33dc949c57f81       304MB
```


(2) Below expected values are correct
```
$ cat /usr/share/rancher/rancherd/config.yaml.d/50-defaults.yaml
..
  extraEnv:
    - name: CATTLE_SHELL_IMAGE
      value: "rancher/shell:v0.1.26"

$ kubectl get settings.management.cattle.io shell-image -oyaml
apiVersion: management.cattle.io/v3
customized: false
default: rancher/shell:v0.1.24
kind: Setting
metadata:
..
  name: shell-image
..
source: env
value: rancher/shell:v0.1.26  /// patched value
```

On upgrade path, after upgrade
(1) The cluster should also have:
```
$ kubectl get settings.management.cattle.io shell-image -oyaml
...
value: rancher/shell:v0.1.26 // patched value
```

(2) The `rancher-monitoring` addon can be enabled successfully.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.


Test Information
----
* Environment: **qemu/KVM 2 nodes** and **baremetal DL360G9 4 nodes**
* Harvester Version: **v1.3.2-rc1** and **v1.3.1** -> **v1.3.2-rc2**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with at least 2 nodes
2. Follow test plan in https://github.com/harvester/harvester/issues/6283#issuecomment-2296105664
