### ISSUE TITLE
[DOC] Base OS version info does NOT update since v1.2

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6288]
**Is your doc request related to a problem? Please describe or add the related issue ID.**
The base OS info in the harvester document https://docs.harvesterhci.io should be incorrect since `v1.2`
![image](https://github.com/user-attachments/assets/68d0b7bb-c51f-47a2-952e-95449fac0a41)

**Describe the solution you'd like**
Correct mapping should be
* _harvester-v1.2_ : `5.4` ([Ref.](https://build.opensuse.org/projects/isv:Rancher:Harvester:OS:v1.2/packages/baseos/files/Dockerfile))
* _harvester-v1.3_ : `5.4` ([Ref.](https://build.opensuse.org/projects/isv:Rancher:Harvester:OS:v1.3/packages/baseos/files/Dockerfile))
* _harvester-v1.4_: `5.5` (TBD, [Ref.](https://build.opensuse.org/projects/isv:Rancher:Harvester:OS:v1.4/packages/baseos/files/Dockerfile))

## Additional context
n/a

**Comment by bk201** [comment]
Should be fixed in https://github.com/harvester/docs/pull/621
