### ISSUE TITLE
[BUG] [UI] Create VM Network VLAN ID input validation buggy

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester#6290]
**Describe the bug**
When creating a new VM Network, the UI does not allow entering some values for the VLAN ID, even though they should be valid.

**To Reproduce**:
Create new VM Network via UI and try to set the VLAN ID to 4048.

**Expected behavior**:
Any valid VLAN ID can be entered (1-4094)

**Environment**:
 - Harvester ISO version: v1.3.1, v1.2.2

**Additional context**:
https://jira.suse.com/browse/SURE-8851

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Create cluster network
3. Create VM network, the field of `VLAN ID` should able to input number 1 to 4094.
