### ISSUE TITLE
[BUG] Installation stops with "No default route found." with installation method "Install Harvester binaries only"

### ISSUE THREAD

**Issue by ma44in** [harvester/harvester#6306]
**Describe the bug**
If i try to to install harvester in "Binaries only" mode, the installation stops with "No default route found. Please check the router setting on the DHCP server". I assumed that no network was required for "binaries only". 

**To Reproduce**

1. Boot from ISO
2. Select "Install Harvester binaries only"
3. Make disk settings and set password
4. Confirm installation options

**Expected behavior**
Binaries should be installed regardless of whether a default route exists or not, because network will be setup afterwards.

**Environment**
 - Harvester ISO version: 1.3.1-amd64 and v1.4.0-dev-20240802-amd64 
 - Underlying Infrastructure: QEMU/KVM Environment 

 
**Additional context**
I am trying to build an image which I want to stream directly to the hard disk of a bare-metal server, as described in https://docs.harvesterhci.io/v1.3/install/install-binaries-mode and "Streaming disk mode". Due to the fact that there is no current RAW image in version 1.3.1, I am trying to create one myself. Alternatively, it would of course be great if there were a RAW image (similar to harvester-v1.2.0-amd64.raw) for the current version of Harvester.

**Comment by bk201** [comment]
Thanks for reporting. @mingshuoqiu Please help see if we can remove the route check in binary mode. I'll check the image publishing issue.

**Comment by ibrokethecloud** [comment]
are you able to please switch console when this happens and provide us the output of /var/log/console.log

**Comment by ibrokethecloud** [comment]
i can confirm that we can reproduce the issue

**Comment by ibrokethecloud** [comment]
the issue is caused by this check: [addInstallPanel](https://github.com/harvester/harvester-installer/blob/master/pkg/console/install_panels.go#L2155)

It should be 
```
if !installModeOnly && !isDefaultRouteExist {
```

**Comment by lanfon72** [comment]
> i can confirm that we can reproduce the issue

Hi @ibrokethecloud, could you provide the steps to reproduce this on qemu environment? thanks.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM single node**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with `Install Binary Only`
2. Harvester should able to be installed successfully
