### ISSUE TITLE
[BUG] Restore from backup to replace existing vm would stuck in `Restoring` with `WaitingForVolumeBinding` 

### ISSUE THREAD

**Issue by TachunLin** [harvester/harvester#6312]
**Describe the bug**

When restore a vm backup to replace the existing vm (retain volume), the restore kept in `Restoring` and won't complete.

* Restore from clean backup to replace existing vm 
  ![image](https://github.com/user-attachments/assets/8c2ac109-49e7-4739-8772-db846708106e)
  
  
  https://github.com/user-attachments/assets/d71b0e18-f76b-4fec-82fc-7196f4209f77

* Restore from backup already restore to new before to replace existing vm 

  https://github.com/user-attachments/assets/367b5227-2c44-44c7-ad7e-8218735e56ee

* The vm display status `WaitingForVolumeBinding`
  ![image](https://github.com/user-attachments/assets/6d10192c-188d-46af-a4d1-4280ba2a10be)

**To Reproduce**

1. Create a vm names opensuse
2. Setup nfs backup target
3. Create a backup named opensuse-backup
4. Shutdown the vm
5. Select restore to existing vm
6. Select to retain (or delete) volume
7. Check the restore process complete
8. Check the restore column will disappear after restore process finish

**Expected behavior**

Can restore vm to replace existing vm correctly,the vm should be started in running state

**Support bundle**

* Restore to replace existing which already restore to new one before
[supportbundle_3c2a0704-abe7-41eb-894b-041b497c5bfc_2024-08-12T09-56-19Z.zip](https://github.com/user-attachments/files/16580321/supportbundle_3c2a0704-abe7-41eb-894b-041b497c5bfc_2024-08-12T09-56-19Z.zip)

* Restore to replace existing vm 
[supportbundle_3c2a0704-abe7-41eb-894b-041b497c5bfc_2024-08-12T11-20-43Z.zip](https://github.com/user-attachments/files/16580868/supportbundle_3c2a0704-abe7-41eb-894b-041b497c5bfc_2024-08-12T11-20-43Z.zip)

**Environment**
 - Harvester ISO version: `v1.4-4fe69de-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node on local kvm machine

**Comment by TachunLin** [comment]
This issue also exists on the latest master `master-97b50dc-head` 

https://github.com/user-attachments/assets/f3ecec66-f289-4eed-a7b3-db716c6ae6c7

**Comment by WebberHuang1118** [comment]
I can reproduce it on my env, and workaround it by setting VM CR's `.spec.runStrategy` = `Halted`

**Comment by TachunLin** [comment]
Also confirmed this issue **did not happen** on the v1.3-head (v1.3.2 `v1.3-5445e91-head`) 

* Can restore backup to replace existing vm (with retain volume) 

  https://github.com/user-attachments/assets/4dbce5d2-098c-466b-81af-db6dc3254311

* Can restore backup to replace existing vm (with delete volume)

  https://github.com/user-attachments/assets/4afac350-e733-4352-bde2-a644617fed20

**Comment by FrankYang0529** [comment]
Another workaround is sending a start request to VM.

**Comment by FrankYang0529** [comment]
The issue is similar to https://github.com/kubevirt/kubevirt/issues/12544.

**Comment by FrankYang0529** [comment]
Hi @WebberHuang1118, for hot fix, I think we can send a start request if `runStrategy` is `RerunOnFailure` and VMI is not existent.

https://github.com/harvester/harvester/blob/250496b171249565fb9501a1e8b9d03b0fdf4e95/pkg/controller/master/backup/restore.go#L921-L923

**Comment by WebberHuang1118** [comment]
Hi @FrankYang0529 
for the replacing existing case, I'm considering making the VM from RunStrategy as Halted, and Harvester controller will try to start afterwards, WDYT?

**Comment by FrankYang0529** [comment]
Do you mean no matter original which `runStrategy` was, we always replace it with `Halted`? If yes, I can't find any side effect currently. We can give it a try.

**Comment by WebberHuang1118** [comment]
> Hi @WebberHuang1118, for hot fix, I think we can send a start request if `runStrategy` is `RerunOnFailure` and VMI is not existent.

yes, IIUC, we don't have to do `send a start request if runStrategy is RerunOnFailure and VMI is not existent` for the creating new one case. And for replacing existing case, since the source VM is stopped, so the restored VM starts from halted should make sense?

**Comment by FrankYang0529** [comment]
Yes, sounds good to me. Thanks.

**Comment by WebberHuang1118** [comment]
For Kubevirt v1.1.1, as the source VM is stopped, its `RunStratedy` will change to `Halted`
- https://github.com/kubevirt/kubevirt/blob/689c0e66cc6893f311dd648ff32e247203b6c96a/pkg/virt-api/rest/subresource.go#L694-L698
- https://github.com/kubevirt/kubevirt/blob/689c0e66cc6893f311dd648ff32e247203b6c96a/pkg/virt-api/rest/subresource.go#L275-L285

and the restored VM will be kicked off by the Harvester controller
- https://github.com/harvester/harvester/blob/0fa939f85ea57148160b9bd5fa48125906e97c5e/pkg/controller/master/backup/restore.go#L941-L942

For Kubevirt v1.2.2, as the source VM is stopped, its `RunStratedy` keeps as `RerunOnFailure`
- https://github.com/kubevirt/kubevirt/blob/1466b658f78b9b8bb9517ffb6dafd4b777f33fe6/pkg/virt-api/rest/subresource.go#L575-L589

so the restored VM will not start automatically

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.4-4c27327-head` (24/09/06). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$  Can well restore to existing vm with retain volume  $~~$</summary>

  1. Successfully restore vm to existing vm without stuck 

https://github.com/user-attachments/assets/37fa501c-40b3-4573-938a-82fbc78fe2c1


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$  Can well restore to existing vm with delete volume  $~~$</summary>

  1. Successfully restore vm to existing vm without stuck 

https://github.com/user-attachments/assets/30e77da1-0bb1-4f09-b422-00ae5ab5148b


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$  Can well restore to the new vm $~~$</summary>

  1. Successfully restore vm to new vm without stuck 

https://github.com/user-attachments/assets/80ac95b1-6205-4b7e-b4e6-82721daf4c62


 </details>

### Test Information
* Test Environment: Single nodes harvester on kvm machine
* Harvester version: `v1.4-4c27327-head` (24/09/06)

### Verify Steps
<details><summary> Restore backup to existing vm with retain volume </summary>

1. Create a vm names opensuse
2. Setup nfs backup target
3. Create a backup named opensuse-backup
4. Shutdown the vm
5. Select restore to existing vm
6. Select to retain (or delete) volume
7. Check the restore process complete
8. Check the restore column will disappear after restore process finish


</details>
