### ISSUE TITLE
[FEATURE] Built-in HA load balancer

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#632]
We want to have a built-in HA load balancer shipped with the solution, so we can provide VIP(virtual IP address) feature of the Harvester cluster.

Additionally, it can act as a cloud provider in Kubernetes with https://github.com/harvester/harvester/issues/633 enhancement.

We can use kube-vip(https://kube-vip.io/) potentially.

**Comment by larssb** [comment]
Allow me to comment on this one. I would like you to consider https://purelb.gitlab.io/docs/ ... especially as it has support for the `OSPF` routing protocol. `BGP` is, I think, outdated and well known to be insecure. PureLB evolved from, started as far as I know, as a fork of MetalLB. And it's implementation is quite nice. It uses the Bird Router for routing so a nice separation of concerns was done in regards to what PureLB do and do not do.

Please give it a look. Thank you.

**Comment by yaocw2020** [comment]
https://purelb.gitlab.io/docs/how_it_works/bundledbird/

**Comment by olljanat** [comment]
Afaiu this was implemented by #1155 but not closed automatically because description misses magic Word "Closes"

**Comment by yasker** [comment]
@olljanat Thanks for the reminder. Before we can close an issue, our QA will need to validate the issue has been indeed fixed. So that's why we don't use `close` keyword in the PRs.

**Comment by lanfon72** [comment]
Verified the feature implemented on *v0.3.0-rc1* and newer.

[bare metal v0.3.0-rc1]
![image](https://user-images.githubusercontent.com/5169694/135636816-73418b42-f52c-4786-9245-247f69003a47.png)
[qemu/KVM master-82506f55-head]
![image](https://user-images.githubusercontent.com/5169694/135637398-d3f7fda3-75e1-46f1-b06a-7d8d0321ce45.png)

Test Information
----
* Environment: **Bare mental DL360** 3 nodes, **qemu/KVM** 5 nodes
* Harvester Version: **v0.3.0-rc1**, **master-82506f55-head**
### Verify Steps:
  1. install harvester with 2 secondary nodes
  2. open dashboard with VIP
  3. shutdown or reboot any node
  4. check the dashboard still working and the node shouldn't be marked as `active`
