### ISSUE TITLE
[BUG] Add-ons can't be enabled

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6327]
**Describe the bug**

When enabling an addon, its corresponding `helm-install` pod keep respawning to do the helm chart installatation.

**To Reproduce**
1. Install a cluster with master or v1.3-head ISO (container RKE2 v1.28.12).
2. Enable an addon, like seeder.
3. Observe the `helm-install-harvester-seeder-xxx` pod, it will keep respawning.
4. The addon's chart keeps being upgraded:
```
╰─$ helm history -n harvester-system harvester-seeder
REVISION	UPDATED                 	STATUS    	CHART                 	APP VERSION	DESCRIPTION
350     	Tue Aug 13 09:04:29 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
351     	Tue Aug 13 09:04:34 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
352     	Tue Aug 13 09:04:39 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
353     	Tue Aug 13 09:04:44 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
354     	Tue Aug 13 09:04:49 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
355     	Tue Aug 13 09:04:54 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
356     	Tue Aug 13 09:04:59 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
357     	Tue Aug 13 09:05:35 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
358     	Tue Aug 13 09:05:48 2024	superseded	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
359     	Tue Aug 13 09:05:52 2024	deployed  	harvester-seeder-0.3.2	v0.3.2     	Upgrade complete
```
5. If luck the progress will stop at some place.

**Expected behavior**

The chart installation should be just run once.

**Support bundle**

**Environment**
 - Harvester ISO version: master, v1.3-head. (need to container RKE2 1.28.12)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

- @ibrokethecloud  revert RKE2 back to v1.28.10 and can't reproduce this.

**Comment by w13915984028** [comment]
Test report: issue is solved in harvester v1.4.0.

Eanabling addon works as expected.
![image](https://github.com/user-attachments/assets/250d164f-c4a6-4535-85b0-5b6f8daa29b9)

Disabling addon works as expected.
![image](https://github.com/user-attachments/assets/ee916129-6d72-45b8-8c5c-3cf93ffad046)

Re-enable:
![image](https://github.com/user-attachments/assets/bd1ef97d-c865-4427-b6dd-b3975e5a2a9e)

jobs:
```
kubectl get jobs -n harvester-system
NAME                            COMPLETIONS   DURATION   AGE
helm-install-harvester-seeder   1/1           4s         17s
```
