### ISSUE TITLE
[FEATURE] Make Harvester a cloud provider for Kubernetes

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#633]
Depends on https://github.com/rancher/harvester/issues/632

- Develop a helm chart for Kube-vip, only support ARP mode and get IP from DHCP. (2 days)
     - [x] Develop Kube-vip helm chart
     - [x] Support VLAN and kube-vip to use the same network interface.
     - [x] Keep the IP got from the DHCP server same after restarting. 
          - https://github.com/kube-vip/kube-vip/issues/220
     - [x] Support DHCP and pool ipam.
- Define a new CRD and implement the corresponding controller. ( 1 week)
     - [x] Define the new CRD `LoadBalancer`.
     - [x] Implement a controller which uses the Kubernetes service as the load balancer.
     - [x] Support TCP health checker.
 - Develop the Harvester CCM. (1 week)
     - [x] Call API of CRD VirtualMachineInstance to implement the Instance interface.
     - [x] Call API of CRD LoadBalancer to implement the loadbalancer interface.
     - [x] Use `kubeconfig` file as the cloud-config.
     - [x] #1019
 - Support VIP https://github.com/harvester/harvester/issues/632
     - [x] Add VIP when installing the Harvester.
     - [x] https://github.com/kube-vip/kube-vip/issues/243 TBD

**Comment by futuretea** [comment]
Can we implement a [cluster-autoscaler](https://github.com/kubernetes/autoscaler/tree/master/cluster-autoscaler) for Harvester?

**Comment by yaocw2020** [comment]
Reference about [how to develop a cloud provider](https://kubernetes.io/docs/tasks/administer-cluster/developing-cloud-controller-manager/)

**Comment by yaocw2020** [comment]
[Guidelines](https://kubernetes-csi.github.io/docs/developing.html) to develop a CSI driver.

**Comment by yasker** [comment]
@yaocw2020 Don't worry about CSI part for now. It's tracked separately at #580

**Comment by yaocw2020** [comment]
TODO: 
- Support VLAN and kube-vip to use the same network interface.
- Keep the IP got from the DHCP server same after restarting. (block)
    - https://github.com/kube-vip/kube-vip/issues/220
- Use kubeconfig file as the cloud-config. (block)
- Automatical installation in REK2. (block)
    - https://github.com/rancher/rke2/issues/568
- UI integration: Enable the Harvester Load Balancer.

**Comment by yaocw2020** [comment]
To test:
- Install harvester load balancer in the Harvester first. Refer to the [README](https://github.com/harvester/load-balancer-harvester/blob/main/README.md) of the Harvester Load Balancer repo.
- Set up an RKE cluster(guest cluster) with the Harvester node driver and add the addon configuration generated by a script in the RKE YAML. Refer to the [README](https://github.com/harvester/cloud-provider-harvester/blob/master/README.md) of the Harvester Cloud Provider repo.
- Deploy an Nginx deployment and the related service of the type load balancer.
- Check the external IP of the service and access the Nginx website.
- Add annotations in the service to enable the health check. Access the Nginx to confirm the health check take into effect. Refer to the document [Load Balancer Request Parameters](https://github.com/harvester/load-balancer-harvester/blob/main/README.md).
    - Add a wrong port and users can not access the Nginx.

**Comment by davidspek** [comment]
@yaocw2020 Should the kube-vip.interface be the same interface used for the management network? I have a few hosts where the VLAN and management NICs are the same, and installation of the load balancer seems to have brought down the Harvester cluster completely.

**Comment by yaocw2020** [comment]
> @yaocw2020 Should the kube-vip.interface be the same interface used for the management network? I have a few hosts where the VLAN and management NICs are the same, and installation of the load balancer seems to have brought down the Harvester cluster completely.

I have submitted the pr to solve this problem. https://github.com/harvester/network-controller-harvester/pull/37
You can set the kube-vip.interface as `harvester-br0`. We also plan to set `harvester-br0` as the default interface for kube-ip in the Harvester.

**Comment by davidspek** [comment]
Thank you for the quick response and fix. I'll setup a fresh cluster and test with the harvester bridge interface. This is an awesome project by the way, amazing work!

**Comment by yasker** [comment]
The feature is done. It will be covered in the regression test cases.

Feel free to file new issues against the feature.
