### ISSUE TITLE
[BUG] The `branding` system setting is not handled correct or the documentation is incorrect

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#6331]
**Describe the bug**
The `branding` system setting is documented [here](https://docs.harvesterhci.io/v1.4/advanced/index#branding).

Now there are several possibilities of what is wrong or right; accordingly, the errors are then to be sought in the appropriate places.

# Code
This setting is not configured in the code, see [1](https://github.com/harvester/harvester/blob/0fa939f85ea57148160b9bd5fa48125906e97c5e/pkg/settings/settings.go#L22) and [2](https://github.com/harvester/harvester-installer/blob/e80ee9a7ae07292f03acb86edffcff9f4337c430/pkg/config/config.go#L41). In this case, however, adding `branding` would only open up the possibility of setting the `Private Label`. The fields `Logo`, `Favicon`, `Primary Color` and `Link Color` are still not available because `branding` is only an alias for `ui-pl`.

To support all UI settings, the following settings need to be added:
```
ui-pl
ui-logo-light
ui-logo-dark
ui-favicon
ui-primary-color
ui-link-color
branding // alias for ui-pl
```

# Documentation
The documentation of [branding](https://docs.harvesterhci.io/v1.4/advanced/index#branding) is incorrect.
1. It should be mentioned that this setting can not be injected via [Harvester Configuration](https://docs.harvesterhci.io/v1.4/install/harvester-configuration#system_settings) during installation if we do not add them to the code (see above).
2. It should be mentioned that this setting is only available in a Single-Node installation or when a new cluster is set up ([1](https://github.com/harvester/dashboard/blob/79bd33276fad0ce22268bd3888a0c33853076765/pkg/harvester/config/settings.js#L93), [2](https://github.com/harvester/dashboard/blob/79bd33276fad0ce22268bd3888a0c33853076765/pkg/harvester/list/harvesterhci.io.setting.vue#L64)).
3. The origin system setting names need to be mentioned in the [documentation](https://docs.harvesterhci.io/v1.2/advanced/index#ui-settings). These are:
```
ui-pl
ui-logo-light
ui-logo-dark
ui-favicon
ui-primary-color
ui-link-color
branding // alias for ui-pl
```

**Comment by votdev** [comment]
The mentioned settings `ui-pl, ui-logo-light, ui-logo-dark, ui-favicon, ui-primary-color, ui-link-color and branding` are handled by the `management.cattle.io/v3` API group and not `harvesterhci.io/v1beta1`. Because of that it is not possible to support them via [Harvester configuration system_settings](https://docs.harvesterhci.io/v1.4/install/harvester-configuration/#system_settings).

This should be mentioned in the documentation.

**Comment by w13915984028** [comment]
Testing report:

The document PR https://github.com/harvester/docs/pull/623 looks missing a `)` in the `(for example`, I added a PR https://github.com/harvester/docs/pull/642 to fix it, after the PR is merged, I will close this issue.

![image](https://github.com/user-attachments/assets/4b4a4b73-c57f-47c6-80d3-81ac668733df)

**Comment by w13915984028** [comment]
Document is updated.

![image](https://github.com/user-attachments/assets/e39ed29c-d70d-40a5-8698-42e97b88999c)
