### ISSUE TITLE
[FEATURE] Terraform provider

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#634]
**Description:**
- Need a terraform provider for users to provision VMs from the command line.
- Support defining harvester infrastructure based on Terraform files
- Support terraform v1.0.0

**Supported Resources:**
- [x] ssh-key
- [x] image
- [x] network
- [x] volume
- [x] virtualmachine
- [x] clusternetwork

**Stages:**
- [x] add basic implemetation
- [x] add tests
- [ ] publich to the TF registry

**Comment by futuretea** [comment]
# To tests:
1. download and install terraform https://www.terraform.io/downloads.html
2. download and install terraform-provider-harvester  https://github.com/harvester/terraform-provider-harvester#readme
3. test `plan`, `apply`, `destory`, `import` commands for each supported resource
   * https://github.com/harvester/terraform-provider-harvester/tree/master/docs
   * https://github.com/harvester/terraform-provider-harvester/tree/master/examples

## Take the following steps to test provider:
1. write a provider.tf
```hcl
terraform {
  required_providers {
    harvester = {
      source  = "registry.terraform.io/harvester/harvester"
      version = "~> 0.1.0"
    }
  }
}

provider "harvester" {
}
```
0.1.0 is the version of terraform-provider-harvester
2. run `terraform init` , no error, prompting `Terraform has been successfully initialized!`

## Take the following steps to test each resource:
1. If a resource already exists, run the `terraform  import` command to import it 
2. If the configuration is inconsistent with the actual resource status, run the `terraform  plan` command to display the difference between the actual status and the configured status
3. Run `terraform  apply`, no error, The actual status is consistent with the configuration
4. Run `terraform  plan` again, no error, prompting `No changes`
5. Run `terraform  apply` again, no error, prompting `No changes`
6. Run `terraform  destroy`, no error and the resource is deleted

**Comment by juadk** [comment]
I'm looking at the provider example here: https://github.com/harvester/terraform-provider-harvester/blob/master/examples/provider/provider.tf
I think a kubeconfig file is needed if you don't have one in your home dir.
What's the parameter to specify it in the provider configuration?
Anyway, I tried with the harvester kubeconfig file in my .kube/config and it works.

**Comment by futuretea** [comment]
> What's the parameter to specify it in the provider configuration?

kubeconfig, https://github.com/harvester/terraform-provider-harvester/blob/master/docs/index.md

**Comment by juadk** [comment]
Tested with: Harvester **master-2f810069-head** + **terraform-provider-harvester v.0.1.0** + **Terraform v1.0.3**

I tested both authentications with the default kubeconfig file and with the kubeconfig variable pointing to the a specified kubeconfig.

1. Installation of the provider :heavy_check_mark: 
2. `harvester_ssh_key`: All steps ok :heavy_check_mark: 
3. `harvester_clusternetwork`: :heavy_check_mark:
4. `harvester_image`: :heavy_check_mark: 
5. `harvester_network`: :heavy_check_mark: 
6. `harvester_volume`: :heavy_check_mark: , found this [bug](https://github.com/harvester/harvester/issues/1041)
7. `harvester_virtualmachine`: :heavy_check_mark: 
8. Test cases added on Confluence

**Comment by juadk** [comment]
If I understand correctly, we need to document this new provider directly on https://registry.terraform.io/providers/ instead of the harvester documentation.

**Comment by futuretea** [comment]
> If I understand correctly, we need to document this new provider directly on https://registry.terraform.io/providers/ instead of the harvester documentation.

After push provider to terraform registry, the documents in `./docs` will also show in the registry.
Example: https://registry.terraform.io/providers/aztfmod/azurecaf/latest/docs/resources/azurecaf_name

**Comment by juadk** [comment]
> After push provider to terraform registry, the documents in `./docs` will also show in the registry.
> Example: https://registry.terraform.io/providers/aztfmod/azurecaf/latest/docs/resources/azurecaf_name

Ok, great! Thx for the info.
That being done, do you think we need to mention the terraform provider on the doc website (https://docs.harvesterhci.io/) for v0.3 version? Seems like a good thing to me.

**Comment by guangbochen** [comment]
yes, need to add both the harvester and terraform provider doc, and they can be linked to each other and no duplicate content is required.

**Comment by juadk** [comment]
Documentation added by this PR https://github.com/harvester/docs/pull/16

**Comment by guangbochen** [comment]
Will track the publish to TF registry and doc on the https://github.com/harvester/harvester/issues/1151 issue.
@juadk please help to close this issue if all the functionality-related tests are passed, thanks.

**Comment by guangbochen** [comment]
close as this has already been verified as described above by @juadk
