### ISSUE TITLE
[ENHANCEMENT] Drop tho potential manual patch of Rancher shell image v0.1.26 on Harvester v1.3.2

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6352]
**Is your enhancement related to a problem? Please describe.**

Harvester v1.4.0 will use Rancher v2.9 version, and the later uses a new shell image `defaultShellVersion: rancher/shell:v0.2.1`

https://github.com/rancher/rancher/blob/3f7c25803c00e5311d89d1144b3c6684b288ed51/pkg/settings/setting.go#L128C78-L128C97
https://github.com/rancher/rancher/blob/a9946d267616beb1be27c3142a4ebaf6186ba3e7/build.yaml#L4

From issue https://github.com/harvester/harvester/issues/6352, the `shell-image` was patched to `v0.1.26` on Harvester v1.3.2 upgrade path, that may affect the further upgrade to v1.4.0.

**Describe the solution you'd like**

Drop to manual patch on v1.4.0 upgrade path

**Describe alternatives you've considered**

**Additional context**

Previous upgrade PR: https://github.com/harvester/harvester/pull/6347

**Comment by w13915984028** [comment]
Test plan:
(1) Upgrade to v1.3.2, check below CRD object, notice the VALUE column has value like `v0.1.26`
(2) Further upgrade to v1.4.0, the VALUE column is empty

```
v132->v140 upgrade, Rancher should upgrade smoothly, and the value of below CRD object should be empty after upgrade

setting.management.cattle.io/shell-image
NAME          VALUE
shell-image   
```

**Comment by brandboat** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM 1 node**
* ui-source Option: **Auto**

### Test Plan
basically follow the test plan in https://github.com/harvester/harvester/issues/6352#issuecomment-2326958381
- Harvester Version: **v1.4.0-rc2** , `shell-image` is empty
  ```txt
  harvester-node-0:~ # kubectl get settings.management.cattle.io shell-image
  NAME          VALUE
  shell-image
  ```
- Harvester Version: **v1.3.2**, `shell-image` is v0.1.26
  ```txt
  harvester-node-0:~ # kubectl get settings.management.cattle.io shell-image
  NAME          VALUE
  shell-image   rancher/shell:v0.1.26
  ```
- Harvester Version: upgrade from **v1.3.2** to **v1.4.0-rc2**, `shell-image` is empty
  ```txt
  harvester-node-0:~ # kubectl get settings.management.cattle.io shell-image
  NAME          VALUE
  shell-image
  ```
