### ISSUE TITLE
[BUG] Reserved storage size in the dashboard isn't useful

### ISSUE THREAD

**Issue by ejweber** [harvester/harvester#6362]
**Describe the bug**

The "reserved" storage on the Harvester dashboard comes from the `spec.disks[].storageReserved` field in the nodes.longhorn.io CR.

- https://github.com/harvester/dashboard/blob/b97bf0600b4da2bb0d11fd70d7c0af0cf01789cb/pkg/harvester/list/harvesterhci.io.dashboard.vue#L376-L390
- https://github.com/longhorn/longhorn-manager/blob/470213508633a57934d0b6fa8fb75b16ca91b088/k8s/pkg/apis/longhorn/v1beta2/node.go#L94-L95

That field does NOT indicate anything about the resources Longhorn volumes are consuming. Instead, it is determined by the user at disk creation (or by the system with the storage-reserved-percentage-for-default-disk for the default disk). It is a parameter passed TO Longhorn to influence scheduling decisions.

The Longhorn UI calculates the "Allocated" space using the `spec.disks[].storageScheduled` field instead. I think this is the information Harvester intends to show.

https://github.com/longhorn/longhorn-ui/blob/ed85b7b76923258ca3f6f95514d9aa18007a5eeb/src/routes/host/HostList.js#L203-L205

Notice in the Harvester view that each node supposedly has `81 GiB` of reserved storage.

![image](https://github.com/user-attachments/assets/85382bf0-53ac-4e5c-96b3-f973b65b3da3)

In the Longhorn UI, we can see that `81 GiB` (`80.6 GiB`) represented as "Reserved", but the information that is actually of interest is the `180 GiB` of allocated space. The Longhorn UI shows that these nodes are out of space, but the Harvester UI doesn't reflect it.

![image](https://github.com/user-attachments/assets/34bcc3e5-d55a-4148-823e-57eddb22e8e0)

**Expected behavior**

The "reserved" storage for a node should probably be related to the amount of storage Longhorn has already scheduled/allocated and NOT be the "reserved" space that Longhorn is not allowed to use.

**Environment**

It looks like Harvester has done the calculation this way for many years.

**Comment by innobead** [comment]
cc @Vicente-Cheng to drive the change in 1.5 including backend. @votdev can help with the implementation.

cc @bk201

**Comment by a110605** [comment]
Harvester dashboard already have `status.diskStatus[].storageScheduled` from LH CR. 
We can just change **Reserved** to **Allocated** for host storage column.

<img width="1130" alt="Screenshot 2024-08-19 at 10 05 58 AM" src="https://github.com/user-attachments/assets/5e67b61d-6f87-41c0-b40b-73e3f9b300bb">

**Comment by Vicente-Cheng** [comment]
> cc @Vicente-Cheng to drive the change in 1.5 including backend. @votdev can help with the implementation.
> 
> cc @bk201

I would like to create another issue for later enhancements.
For this issue, we could focus on the UI enhancement for v1.4.0

**Comment by Vicente-Cheng** [comment]
New issue: https://github.com/harvester/harvester/issues/6366 for later enhancement on v1.5.0

**Comment by votdev** [comment]
> That field does NOT indicate anything about the resources Longhorn volumes are consuming. Instead, it is determined by the user at disk creation (or by the system with the storage-reserved-percentage-for-default-disk for the default disk). It is a parameter passed TO Longhorn to influence scheduling decisions.

This is a good example of how a documentation of the parameters and their purpose might have helped to clear up this misunderstanding in the implementation of the UI.

**Comment by votdev** [comment]
How should we name the progress bars in the dashboard?

![grafik](https://github.com/user-attachments/assets/f044b02c-4141-486c-ab6f-21b0bde5a6bf)

Should we name it `Allocated` like we did in the LH UI? Or maybe `Scheduled`?

Same for the `Storage Size` column in the `Hosts` page?

![Bildschirmfoto vom 2024-08-19 17-25-37](https://github.com/user-attachments/assets/8b7bc3e3-51e0-43af-9c3a-758fe0043de0)

**Comment by a110605** [comment]
> Should we name it `Allocated` like we did in the LH UI? Or maybe `Scheduled`?

Both are fine to me. Do you have any preferenece for the naming ? @Vicente-Cheng , @bk201 

> Same for the `Storage Size` column in the `Hosts` page?

Yes, the host and dashboard pages should change to the same naming.

**Comment by Vicente-Cheng** [comment]
> Should we name it `Allocated` like we did in the LH UI? Or maybe `Scheduled`?

I thought the `Allocated` makes more sense to me.

**Comment by votdev** [comment]
While working on the issue i realized that the calculation of the `total` value is incorrect. In Harvester the values of `storageMaximum` are simply [summarized](https://github.com/harvester/dashboard/blob/b97bf0600b4da2bb0d11fd70d7c0af0cf01789cb/pkg/harvester/list/harvesterhci.io.dashboard.vue#L400), in LH instead the formula is `total = /(sum_storageMaximum - sum_storageReserved) * storageOverProvisioningPercentage) / 100` where `storage-over-provisioning-percentage` is `200` in the settings. Check out the calculation [here](https://github.com/longhorn/longhorn-ui/blob/ed85b7b76923258ca3f6f95514d9aa18007a5eeb/src/routes/host/HostList.js#L198). I think we need to adapt that in Harvester as well to display the same values in both apps.

# LH
![grafik](https://github.com/user-attachments/assets/c405fdbd-dc6b-4be7-8091-63405b30f694)
allocated = 40GiB
total = 448GiB

# Harvester
![grafik](https://github.com/user-attachments/assets/f32b8e9e-da50-4782-b89b-2f64ce06ad07)
allocated = 40GiB
total = 321GiB

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/6f7faa75-772b-4284-b2ef-daaebdbd3853)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-97e60e1-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install harvester with any nodes
2. Login to Harvester dashboard and navigate to Hosts page
3. Field of *Storage Size* should be named to `Allocated` and `Used`
4. Access Embedded Longhorn UI and navigate to Node page
5. Field value of `Allocated` and `Used` should be the same value (might be round up) of Harvester dashboard displayed
