### ISSUE TITLE
[Question] Failed to install Harvester on physical server

### ISSUE THREAD

**Issue by 1114774464** [harvester/harvester#637]
HP DL380G server install Harvester, error as follows
![微信图片_20210401195158](https://user-images.githubusercontent.com/24802027/113290143-cc8f1680-9323-11eb-986e-fbb41dffaf4a.jpg)
Server CPU:Intel xeon CPU E5-2600 V2@2.20GHz
How to solve this problem？

**Comment by 1114774464** [comment]
Harvester ISO is v0.1.0

**Comment by futuretea** [comment]
@1114774464 What tool was used to create the usb? 
https://github.com/rancher/harvester/issues/404#issuecomment-799997996

**Comment by emctl** [comment]
@1114774464 - I got this when I flashed the ISO with Rufus however It worked with [etcher](https://www.balena.io/etcher/)

**Comment by 1114774464** [comment]
> @1114774464 What tool was used to create the usb?
> [#404 (comment)](https://github.com/rancher/harvester/issues/404#issuecomment-799997996)
CD-ROM

**Comment by 1114774464** [comment]
> @1114774464 - I got this when I flashed the ISO with Rufus however It worked with [etcher](https://www.balena.io/etcher/)

I flash the ISO with etcher,no errors,but stop as follows
![usb](https://user-images.githubusercontent.com/24802027/113370595-d9991d80-9396-11eb-8c25-bcf444547ef4.jpg)

**Comment by 1114774464** [comment]
When the ISO writte with the UltraISOPortable to a usb drive,the following exception occurs
![u](https://user-images.githubusercontent.com/24802027/113372040-4eba2200-939a-11eb-8ff3-9b4b01b7dc30.jpg)

**Comment by emctl** [comment]
> > @1114774464 - I got this when I flashed the ISO with Rufus however It worked with [etcher](https://www.balena.io/etcher/)
> 
> I flash the ISO with etcher,no errors,but stop as follows
> ![usb](https://user-images.githubusercontent.com/24802027/113370595-d9991d80-9396-11eb-8c25-bcf444547ef4.jpg)

Isn't that the screen you want to proceed with the install?
