### ISSUE TITLE
[BUG] Harvester setting `log-level` has no effect after pod is restarted

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6378]
**Describe the bug**

**To Reproduce**
1. Set to `debug`
2. Restart the Harvester pod
3. The log-level reverts to `info`

**Expected behavior**

Persistant and/or update the document.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.0 master-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by w13915984028** [comment]
Test plan:
(1) From Harvester UI, set `log-level` to `debug`;
(2) Check Harvester POD log, should see many debug level logs and info/warning/error level logs;
(3) Kill the leader Harvester POD, the new leader/the replaced POD should still print debug logs;
(4) Reboot the cluster, after that the Harvester POD still print `debug` log
(5) Repeat (1)..(4), set `log-level` to `Info`, should only and always observe `Info` (and above like warning/error) level log.

**Comment by w13915984028** [comment]
FYI: When testing with v1.4/master, the ISO needs to be after 2024.08.30, it will include the PR https://github.com/harvester/harvester/pull/6460 / https://github.com/harvester/harvester/pull/6396, thanks.

**Comment by m-ildefons** [comment]
Failed to verify with `v1.4.0-dev-20240830`. Was this not included in that release?

**Comment by w13915984028** [comment]
Need to wait a bit:

The `v1.4.0-dev-20240830` did not include the related PR.

https://github.com/harvester/harvester/commits/v1.4.0-dev-20240830/
https://github.com/harvester/harvester/commits/v1.4/

**Comment by m-ildefons** [comment]
Testenvironment:
Harvester v1.4.0-rc4 on baremetal (falcons)

Test 1: Default Setting
:green_circle: Logs contain only `info` level or above messages

Test 2: Change Log-Level Setting to `debug`
:green_circle: Logs now also contain `debug` level messages

Test 3: Restart Harvester Pod
:green_circle: The new Harvester pod also writes `debug` level messages to its log

Test 4: Reboot Harvester Node
:green_circle: Logs still contain `debug` level messages

![Screenshot at 2024-10-25 11-04-24](https://github.com/user-attachments/assets/f567fb0d-e021-4174-a4f2-e48d3e5188ff)

Test 5: Change Log-Level Setting back to `info`
:green_circle: `debug` level log messages stop appearing in the log

Test 6: Restart Harvester Pod
:green_circle: Logs contain only `info` level or above messages

![Screenshot at 2024-10-25 11-11-16](https://github.com/user-attachments/assets/b8e5ae4d-19e1-4067-abbc-dafe71e4fc28)

Test 7: Reboot Harvester Node
:green_circle: Logs don't contain `debug` level messages - only `info` level or above.

![Screenshot at 2024-10-25 11-21-07](https://github.com/user-attachments/assets/c951782e-504c-4801-b211-7f6703e61c50)
