### ISSUE TITLE
[FEATURE] Add websocket disconnection prompt

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#638]
**Is your feature request related to a problem? Please describe.**

When the websocket is disconnected, the disconnect message needs to be displayed

**Comment by TangStone** [comment]
Validate version master-621eedd7-head
Shut down the harvester host or disconnect the client from the network
![image](https://user-images.githubusercontent.com/15829074/114133857-4aad7780-9939-11eb-9979-86837f39eb4d.png)
