### ISSUE TITLE
Move out minIO component

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#639]
Motivations:
1. There's no guarantee for upgrading distributed minIO with zero downtime.
2. It's additional overhead when we have backing image support in longhorn.
3. Reduce support efforts.

**Comment by gitlawr** [comment]
UI: Adapt to the API, remove the imported status and progress for images. Remove the tips for image storage health check.

QA: Confirm the minIO component is gone. confirm that image & VM operations work as before.

**Comment by TangStone** [comment]
### Confirm the minIO component is gone
View the minIO component in the v0.2.0-rc1 version
![image](https://user-images.githubusercontent.com/15829074/114493357-024dcc80-9c4d-11eb-80e3-4ea2e06b7cb0.png)
View minIO component in master-95a5828a-head version
![image](https://user-images.githubusercontent.com/15829074/114493526-4b9e1c00-9c4d-11eb-8ef2-2060143b006e.png)

**Comment by TangStone** [comment]
### confirm that image & VM operations work as before.
Validation in master-95a5828a-head version

- [x] 1. add image to harvester
![image](https://user-images.githubusercontent.com/15829074/114512465-b8c0aa00-9c6b-11eb-9186-59b4bc85190e.png)
- [x] 2. Create a VM with the added image, View basic VM information and operate the VM
![image](https://user-images.githubusercontent.com/15829074/114514405-d55de180-9c6d-11eb-8011-5a1876488384.png)
- [x] 3. View Backing image
![image](https://user-images.githubusercontent.com/15829074/114515170-a7c56800-9c6e-11eb-8a11-8fafd2dc03cf.png)
- [x] 4. delete image successfully
- [x] 5. delete VM successfully
