### ISSUE TITLE
[BUG] The Harvester setting kubeconfig-default-token-ttl-minutes is only applied to Rancher once

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6395]
**Describe the bug**

The Harvester setting `kubeconfig-default-token-ttl-minutes` is only applied to Rancher once

**To Reproduce**
1. Set Harvester settings `kubeconfig-default-token-ttl-minutes` to value X, the Rancher setting `kubeconfig-default-token-ttl-minutes` is also updated to X
2. Manually change Rancher `kubeconfig-default-token-ttl-minutes` to Y; (This simulates the possible scenario where setting of Rancher was changed)
3. Restart Harvester POD, the Rancher `kubeconfig-default-token-ttl-minutes` is still X;

**Expected behavior**

If the backend setting `kubeconfig-default-token-ttl-minutes` was changed in various possibilities, Harvester should re-apply the setting to the backend at least when Harvester POD restarts.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

https://github.com/harvester/harvester/issues/6378

In general, for any Harvester settings, if it is forwarded to other components, there are 3 options:
(1) Set once
(2) Add a controller to watch and sync all the time
(3) When POD starts, check and sync

Most of the settings are using (1), but (2)/(3) will be better. This PR https://github.com/harvester/harvester/pull/6396 adopts (3).

**Comment by w13915984028** [comment]
Test plan:

(1) From harvester UI, set `kubeconfig-default-token-ttl-minutes` setting to 36000

Check the Rancher settings from kubectl
```
$kubectl get settings.management.cattle.io | grep 36000
auth-token-max-ttl-minutes                36000
kubeconfig-default-token-ttl-minutes      36000
```

(2) Manual re-set Rancher setting to another value
```
$kubectl get settings.management.cattle.io kubeconfig-default-token-ttl-minutes
NAME                                   VALUE
kubeconfig-default-token-ttl-minutes   2600
```

(3) Kill the Harvester leader POD
```
$kubectl delete  pods -n harvester-system harvester-c8d679898-pzzkn
pod "harvester-c8d679898-pzzkn" deleted
```

Check the log of new Harvester leader POD, get such :
```
time="2024-08-21T14:35:06Z" level=info msg="Rancher setting kubeconfig-default-token-ttl-minutes and auth-token-max-ttl-minutes will be set to 36000"
```

Check Rancher setting:
```
$kubectl get settings.management.cattle.io | grep 36000
auth-token-max-ttl-minutes                36000
kubeconfig-default-token-ttl-minutes      36000
```

(4) Set Harvester `kubeconfig-default-token-ttl-minutes` setting to `Use the default value`.

Check Rancher setting, they should also be `0`

````
harv21:/home/rancher # kk get settings.management.cattle.io | grep ttl -i
auth-token-max-ttl-minutes                0    
kubeconfig-default-token-ttl-minutes      0

```

**Comment by w13915984028** [comment]
FYI: When testing with v1.4/master, the ISO needs to be after 2024.08.30, it will include the PR https://github.com/harvester/harvester/pull/6460 / https://github.com/harvester/harvester/pull/6396, thanks.

**Comment by brandboat** [comment]
Test OK on [v1.4.0-dev-20240918](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918), close as fixed.

## Environment
* [`v1.4.0-dev-20240918`](https://github.com/harvester/harvester/releases/tag/v1.4.0-dev-20240918)
  * Profile: 2 nodes QEMU/KVM (8C/16G/250G per node)
  * ui-source: `Auto`

## Test Steps
follow test steps in https://github.com/harvester/harvester/issues/6395#issuecomment-2302338402 and all good.
