### ISSUE TITLE
[Enhancement] Extract doc links mapping into a file

### ISSUE THREAD

**Issue by a110605** [harvester/harvester#6403]
**Is your enhancement related to a problem? Please describe.**

In harvester/dashboard code base, we have 4 links in en-us.yaml pointing to the harvester doc link.

As we will have more releases in the future, it would be easier for developer or technique writer to modify if we put them in a central file. (e.g config/doc-link.js)

<img width="1141" alt="Screenshot 2024-08-22 at 3 55 05 PM" src="https://github.com/user-attachments/assets/ca1d31c3-b023-4be5-a071-5495f114113b">

We can honor the package.json version to auto determine the harvester doc version.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-dev-20240918**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Login to dashboard and navigate to _Hosts_ page, the link aside **Console** button should open the relevant document of the cluster version. (for example, when the cluster is `v1.3.2-rc2`, it should link to `https://docs.harvesterhci.io/v1.3/host/`)
3. Edit one of the host and update Ksmtuned's _Run Strategy_ to **Run**, the link aside `Mode` should open the relevant document of the cluster version.
