### ISSUE TITLE
[BUG] 1.3.1 Disiappearing IP addresses in UI / kubectl

### ISSUE THREAD

**Issue by web-engineer** [harvester/harvester#6406]
**Describe the bug**

IP addresses can take a while to populate, can be empty for a host sometimes - but eventually shows an IP most of the time... [From discussion in slack](https://rancher-users.slack.com/archives/C01GKHKAG0K/p1724331866250879?thread_ts=1724240434.324089&cid=C01GKHKAG0K).

Is there anything we can do to get this to update more reliably, often I see IP's then after a while they disappear from the list then reappear later - VM's are running rocky-linux 9, this is with a new 1.3.1 harvester cluster - 2 workers, 1 witness node.

Network is getting IP addresses from our routers DHCP and those IP's are set as static mappings for the Macs as we find what they are, new VM's can take a little while to appear.

If I login to our router I can see the machines in the DHCP table - so its easy to work out, just frustrating that the UI doesn't seem to show them all the time - they are fine 95% if the time but there is often 1 or 2 missing, is this a symptom of a greater problem - or just the way it is?

Just to add - there is a DNS pod in this list, its not used yet - there is a dedicated DNSmasq machine outside of the cluster serving the network and a backup VM inside an old cluster - and the router reports both IP's for DNS resolution

![Screenshot 2024-08-21 at 12 40 07](https://github.com/user-attachments/assets/f6e7e9cb-7330-4d7b-95f3-9654907a777e)

**To Reproduce**

Simply goto the virtual hosts page or run and watch the output of 

`kubectl get VirtualMachineInstance -A --watch`

Example outputs -

```
NAMESPACE             NAME                AGE     PHASE     IP                NODENAME   READY
harvester-public      web1-clone          6d      Running   192.168.100.206   n4         True
web-engine-services   dns                 3h26m   Running                     n5         True
web-engine-services   gitlab              28h     Running   192.168.100.53    n4         True
web-engine-services   nfs                 77m     Running                     n5         True
web-engine-services   runner-01           4h48m   Running   192.168.100.137   n5         True
... truncated ...
web-engine-services   nfs                 15m     Running                        n5         True
web-engine-services   nfs                 16m     Running      192.168.100.122   n5         True
web-engine-services   minio               47h     Running      192.168.100.200   n5         True
web-engine-services   zabbix              46h     Running                        n4         True
web-engine-services   zabbix              46h     Running      192.168.100.131   n4         True
```

**Expected behavior**

IP Addresses should be stable

**Support bundle**

[supportbundle_4d170f3b-38c0-41ba-b05c-dfef3d4a621a_2024-08-22T14-36-57Z.zip](https://github.com/user-attachments/files/16712780/supportbundle_4d170f3b-38c0-41ba-b05c-dfef3d4a621a_2024-08-22T14-36-57Z.zip)

**Environment**
 - Harvester ISO version: 1.3.1
 - Underlying Infrastructure: Bare metal, custom build x86 processors, 6 nodes, 1 witness, 2 CP managed via separate rancher cluster of 5 low power nodes.

**Additional context**

Fairly fresh setup - our router has several DHCP servers running - with statically assigned IP's for any nodes/vm's within the cloud (2 separate subnets). We've got router -> 24 port 1GB layer 2 switch (with all tennant networks connected and the mini rancher cluster) -> 24 port spf+ 10GB Layer 3 switch to which the harvester nodes are directly connected with dedicated 10GBSPF for management and one for storage, with a VLAN configured in this switch for the storage network.

**Comment by votdev** [comment]
There is another issue where the IP address disappears: https://github.com/harvester/harvester/issues/3990

**Comment by web-engineer** [comment]
And similar - #5251

**Comment by votdev** [comment]
Sounds like this in [kubevirt](https://github.com/kubevirt/kubevirt/issues/7508).

**Comment by ibrokethecloud** [comment]
are you able to please confirm the guest OS and qemu guest agent version in VM?

**Comment by bk201** [comment]
cc @starbops @mingshuoqiu @rrajendran17

**Comment by web-engineer** [comment]
> are you able to please confirm the guest OS and qemu guest agent version in VM?

Guest OS's both Debian and EL9 - specifically -

Debian-12-generic-amd64-20240717-1811
```
debian@admin2:~$ sudo cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
debian@admin2:~$ apt list qemu-guest-agent
Listing... Done
qemu-guest-agent/stable,now 1:7.2+dfsg-7+deb12u6 amd64 [installed]
```


Rocky-9-GenericCloud-LVM-9.4-20240609
```
[rocky@nfs ~]$ sudo cat /etc/os-release
NAME="Rocky Linux"
VERSION="9.4 (Blue Onyx)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="9.4"
PLATFORM_ID="platform:el9"
PRETTY_NAME="Rocky Linux 9.4 (Blue Onyx)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:9::baseos"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2032-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-9"
ROCKY_SUPPORT_PRODUCT_VERSION="9.4"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="9.4"
[rocky@nfs ~]$ yum list qemu-guest-agent
Rocky Linux 9 - BaseOS                                                 6.0 MB/s | 2.3 MB     00:00
Rocky Linux 9 - AppStream                                               18 MB/s | 8.0 MB     00:00
Rocky Linux 9 - Extras                                                  48 kB/s |  15 kB     00:00
Installed Packages
qemu-guest-agent.x86_64                         17:8.2.0-11.el9_4.4                          @appstream
```

Certainly affecting the Rocky 9 instances - I didn't stop to check if the debian instances are affected too - keeping an eye out presently as that might obviously help shed some light.

**Comment by web-engineer** [comment]
I'll leave a trace running for the day on `kubectl get VirtualMachineInstance -A --watch` to see if the debian guests are affected - this morning just one of the rocky vm's were showing blank. This is one of those things that seems to come and go - it does seem rare to get a full list of IP's and usually there is one blank.

**Comment by web-engineer** [comment]
I'll keep this trace going - so far today the only guest vm's that have triggered this appear to be the RHEL9 based VM's (Rocky 9.4) -

```
NAMESPACE             NAME                                 AGE    PHASE     IP                NODENAME   READY
harvester-public      web1-clone                           131m   Running   192.168.100.206   n4         True
web-engine-services   backup                               131m   Running                     n4         True
web-engine-services   dns                                  131m   Running   192.168.122.124   n4         True
web-engine-services   gitlab                               131m   Running   192.168.100.53    n5         True
web-engine-services   minio                                131m   Running   192.168.100.200   n5         True
web-engine-services   nfs                                  131m   Running   192.168.100.122   n5         True
web-engine-services   runner-01                            131m   Running   192.168.100.137   n4         True
web-engine-services   runner-02                            131m   Running   192.168.100.248   n5         True
web-engine-services   runner-03                            131m   Running   192.168.100.194   n4         True
web-engine-services   web-engine-c1-pool1-eea087ef-bs6wm   129m   Running   192.168.122.186   n4         True
web-engine-services   web-engine-c1-pool1-eea087ef-jbf55   129m   Running   192.168.122.151   n5         True
web-engine-services   web-engine-c1-pool1-eea087ef-qfv4k   129m   Running   192.168.122.19    n4         True
web-engine-services   web-engine-c1-pool2-c06dc04b-lds9s   129m   Running   192.168.122.202   n5         True
web-engine-services   web-engine-c1-pool2-c06dc04b-mtllr   129m   Running   192.168.122.57    n5         True
web-engine-services   web-engine-c1-pool2-c06dc04b-pt7w7   129m   Running   192.168.122.83    n5         True
web-engine-services   web-engine-c1-pool2-c06dc04b-skl76   129m   Running   192.168.122.158   n4         True
web-engine-services   web-server-debian                    131m   Running   192.168.100.147   n5         True
web-engine-services   zabbix                               131m   Running   192.168.100.131   n4         True
web-engine-services   nfs                                  134m   Running                     n5         True
web-engine-services   nfs                                  135m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  140m   Running                     n5         True
web-engine-services   nfs                                  140m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  145m   Running                     n5         True
web-engine-services   nfs                                  145m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  150m   Running                     n5         True
web-engine-services   nfs                                  150m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  155m   Running                     n5         True
web-engine-services   nfs                                  155m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  160m   Running                     n5         True
web-engine-services   nfs                                  160m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  165m   Running                     n5         True
web-engine-services   nfs                                  165m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  170m   Running                     n5         True
web-engine-services   nfs                                  170m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  175m   Running                     n5         True
web-engine-services   nfs                                  175m   Running   192.168.100.122   n5         True
web-engine-services   nfs                                  3h     Running                     n5         True
web-engine-services   nfs                                  3h     Running   192.168.100.122   n5         True
web-engine-services   nfs                                  3h5m   Running                     n5         True
web-engine-services   nfs                                  3h5m   Running   192.168.100.122   n5         True 
```

This NFS server seems to be particularly "chatty" though the only one in the UI thats blank is "backup" which which had failed to boot and was stuck at grub - so that maybe a different issue I guess!

```
web-engine-services   backup                               0s      Scheduling                                False
web-engine-services   backup                               0s      Scheduling                                False
web-engine-services   backup                               2s      Scheduled                      n4         False
web-engine-services   backup                               2s      Scheduled                      n4         False
web-engine-services   backup                               3s      Running                        n4         False
web-engine-services   backup                               3s      Running                        n4         True
web-engine-services   backup                               3s      Running                        n4         True
web-engine-services   backup                               102s    Running                        n4         True
web-engine-services   backup                               102s    Running                        n4         True
web-engine-services   backup                               112s    Running      192.168.100.15    n4         True
web-engine-services   nfs                                  3h20m   Running                        n5         True
web-engine-services   nfs                                  3h20m   Running      192.168.100.122   n5         True
```

Force stop and start of "backup" and we can see its IP assigned above - nfs still doing polling.

So this morning the UI is reporting all IP's that were active -  `kubectl get VirtualMachineInstance -A --watch` showing above, if this is normal or not I've no idea, UI presently looks stable - will keep an eye out to see if it starts happening again.

Only difference today is that we deployed a k8s into this harvester cluster so we have another 7 VM's running using a different DHCP network range (122.X) web-engine-c1-poolX-YYYY above - so maybe when there are more VM's this is happier... if I spot anything more significant I'll update again.

**Comment by votdev** [comment]
I can see that issue as well on my [ixpe](https://github.com/harvester/ipxe-examples) cluster. 

I had some network problems on my host system while the problem occurred. This was manifested by my Rancher node not starting. Error message from both `cattle-cluster-agent-xxx` pods was: `Can not reach rancher.192.168.0.141.sslip.io`.
After I rebooted my host system and restarted the ipxe cluster, the problem with the disappearing IP addresses no longer occurred.
I have no idea how this is connected, but maybe it will help to narrow down the problem somehow.

![Bildschirmfoto vom 2024-08-26 10-18-05](https://github.com/user-attachments/assets/8d7f0b11-4438-46e4-ab44-6726f625b5f0)

![Bildschirmfoto vom 2024-08-26 10-18-35](https://github.com/user-attachments/assets/aeb52a4a-ef65-41b6-b0f2-a82ad69f2f83)

**Comment by bk201** [comment]
@rrajendran17 can you see if this a duplication?

**Comment by rrajendran17** [comment]
@bk201 yes this issue is same as 
https://github.com/harvester/harvester/issues/5251
https://github.com/harvester/harvester/issues/3990

And we specifically see on alma-linux and rocky-linux 9 versions.

Kubevirt issue tracking: https://github.com/kubevirt/kubevirt/issues/12698

**Comment by bk201** [comment]
Thanks for the report, the issue is duplicated with https://github.com/harvester/harvester/issues/3990 and we can track in that issue.
