### ISSUE TITLE
[BUG] UI Improvements: Language and consistency

### ISSUE THREAD

**Issue by asettle** [harvester/harvester#6407]
**Describe the bug**
The Harvester UI has inconsistent uses of language and some instances could require further clarification.

**Environment**
 - Harvester ISO version: 1.3.1

**Additional context**

1. The following image shows "Monitoring Addon". Add-on is a hyphenated word and should not be capitalised: <img width="883" alt="Screenshot 2024-08-23 at 15 28 59" src="https://github.com/user-attachments/assets/e1d99f0c-b57e-4d27-b7f0-6ea3b2ffc6df">
2. This also follows on to this image. "Addon: rancher-monitoring". Add-on should be hyphenated as above. <img width="883" alt="Screenshot 2024-08-23 at 15 29 29" src="https://github.com/user-attachments/assets/1137a51d-15ad-42d0-b260-a917559cc080">
3. In this table "Memory" is unnecessarily fully capitalised. This should be standard case. <img width="883" alt="Screenshot 2024-08-23 at 15 29 47" src="https://github.com/user-attachments/assets/29ce72d3-03cc-4d65-a06f-b9ccb0e0f40e">
4. We should be spelling "VM" out to be "Virtual machine" as it is used inconsistently across the UI <img width="883" alt="Screenshot 2024-08-23 at 15 31 02" src="https://github.com/user-attachments/assets/43460e9e-8466-4e55-b447-77ad2280d4b1">
5. "Miimon" is an acceptable term, but it's not intuitive. I suggest adding a roll-over with a suggestion with an explanation of what a miimon is. <img width="883" alt="Screenshot 2024-08-23 at 15 32 03" src="https://github.com/user-attachments/assets/75aa1379-18d8-48aa-879f-2ac14f1e7c9b">
6. The following image shows an inconsistent naming convention in the navigation panel. Please spell out "Virtual machine" in the instance of "Virtual machine networks" and avoid the use of the slash between "Cluster Network/Configs" - I'd recommend using "Cluster Network Configuration". It should also be "Backup and Snapshots" and "Monitoring and Logging". Reduce the use of the casual ampersand (&) as we want user-friendly and readable content. <img width="368" alt="Screenshot 2024-08-23 at 15 32 33" src="https://github.com/user-attachments/assets/34bea295-e0c4-44ae-8a2c-af92ecff01f8">
7. The proper use of "vlan" is VLAN - please correct <img width="1231" alt="Screenshot 2024-08-23 at 15 32 57" src="https://github.com/user-attachments/assets/bd52d442-32f1-41c2-9d73-5d544a5edb42">
8. This sentence is difficult to read. I would suggest the following rewrite: "You must configure the backup target before creating a new backup. The instructions are [here](https://172.19.108.2/dashboard/harvester/c/local/harvesterhci.io.setting/backup-target?mode=edit)." <img width="745" alt="Screenshot 2024-08-23 at 15 34 02" src="https://github.com/user-attachments/assets/032ee7e4-5275-427a-b15b-1dba5f40bbe4">
9. The use of "VM Backup" and "VM Snapshots" should be expanded to have "Virtual Machine Backups" and "Virtual Machine Snapshots" 
10. This should read "Alertmanager Configuration". Add-on also needs to be hyphenated. And "Monitoring" does not need to be capitalised. The sentence _"Routes and receivers for project alerting and cluster alerting are configured within AlertmanagerConfig resources."_ needs to have a link to the resources. Also I recommend changing it to _"Routes and receivers for project and cluster alerting are configured within AlertmanagerConfig resources."_ <img width="745" alt="Screenshot 2024-08-23 at 15 48 14" src="https://github.com/user-attachments/assets/ea10bfc8-e51d-408f-adbb-de41495d3280">
11. The sentence needs to be edited to say "You must enable [logging ](https://172.19.108.2/dashboard/harvester/c/local/harvesterhci.io.addon/cattle-logging-system/rancher-logging?mode=edit#basic)for any configuration to take effect." <img width="745" alt="Screenshot 2024-08-23 at 15 50 48" src="https://github.com/user-attachments/assets/6f47064c-d71e-4e39-a669-908ba45473ce">
12. The "templateVersion option" needs to use the actual name rather than the technical name. Ie, needs to say "Add template version"  <img width="1251" alt="Screenshot 2024-08-23 at 15 52 25" src="https://github.com/user-attachments/assets/df29777e-3da9-4fac-ad75-eb812455612b">
13. This should say "Cloud Configuration Templates" <img width="844" alt="Screenshot 2024-08-23 at 15 53 14" src="https://github.com/user-attachments/assets/d3271e2b-f3d5-434f-8013-3f1677cf05d2">
14. In this example, the UI should read _"The pcidevices-controller add-on is not enabled, click [here ](https://172.19.108.2/dashboard/harvester/c/local/harvesterhci.io.addon/harvester-system/pcidevices-controller?mode=edit)to enable the add-on to successfully manage your PCI devices."_  <img width="752" alt="Screenshot 2024-08-23 at 15 53 59" src="https://github.com/user-attachments/assets/0a6b7704-5800-4488-8f16-fdfce4f0b4c5">
15. Changed "addon" to "add-on" <img width="752" alt="Screenshot 2024-08-23 at 15 54 54" src="https://github.com/user-attachments/assets/a0231b03-3ff5-4f76-9169-0a4ded145754">
16. All options within this need to be changed to "add-on"<img width="752" alt="Screenshot 2024-08-23 at 15 55 28" src="https://github.com/user-attachments/assets/c20aec34-4bd2-48dc-9a39-55b135f2acd9">
17. The sentence _"Typical users will not need to change these. Proceed with caution, incorrect values can break your Explorer installation. Settings which have been customized from default settings are tagged 'Modified'."_  needs to be edited. What is a "typical" user? What is a "Explorer installation"? It also should read, "Settings _that_ have been customized from default settings are tagged with 'Modified'."
<img width="1314" alt="Screenshot 2024-08-23 at 15 56 13" src="https://github.com/user-attachments/assets/f8732b12-6425-4810-8769-efc416c52206">

**Comment by asettle** [comment]
When creating a VM, the words "VirtualMachine" should be separated and not conjoined 
<img width="1314" alt="Screenshot 2024-08-23 at 16 22 03" src="https://github.com/user-attachments/assets/5515d19a-c062-42f3-b952-8144048629f8">

**Comment by innobead** [comment]
cc @a110605 @torchiaf

**Comment by asettle** [comment]
I can likely pick this up and do it myself @innobead - I'll do it today :)

**Comment by bk201** [comment]
@TachunLin There are some term changes in the GUI, please also check if Cypress needs some change.

**Comment by TachunLin** [comment]
According to the latest cypress [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240917-145232-4d4d22b/index.html) on Jenkins jobs [#110](http://172.19.99.74/job/harvester-cypress-test/110/) on Harvester v1.4-head (`master`).

* We found `46` failed cypress test cases 
  ![image](https://github.com/user-attachments/assets/62a9dda3-efc3-4581-b915-2106b52777b8)
  
  ![image](https://github.com/user-attachments/assets/2bd56a46-db36-430c-9986-5604d02851a8)


* Compared with the cypress test job [#105](http://172.19.99.74/job/harvester-cypress-test/105/), In [test result](https://minio.provo.rancherlabs.com:31524/cypress-test-report/cypress/results/20240913-034545-4d4d22b/index.html) on Harvester `v1.3.2`. 

* There have `4` failed cypress tests.
  ![image](https://github.com/user-attachments/assets/58a7addd-a31e-4656-acc7-4ae74917efd5)

There probably some changes introduced to affect the existing cypress test result. 

I have created the test issue https://github.com/harvester/tests/issues/1535 to investigate and track them on `v1.4.0-head` release.

**Comment by khushboo-rancher** [comment]
@TachunLin The failures might be related to the string changes. We'll need to modify the strings we are using for comparison.

**Comment by TachunLin** [comment]
During fixing the cypress test on the latest v1.4-head Harvester. 
I found an inconsistency title of `Virtual Machines Networks` against `Virtual Machine Networks` under Networks page. 

![image](https://github.com/user-attachments/assets/4d712fbb-6740-42c1-8077-913b11a3a1c9)

Nos sure whether we should also align the title to `Virtual Machines Networks`.

**Comment by bk201** [comment]
@asettle Can you check David's [comment](https://github.com/harvester/harvester/issues/6407#issuecomment-2364205576)? It looks like "Virtual Machine Networks" is more correct.

This also happens to 
- Virtual Machine**s** Backups: https://github.com/harvester/dashboard/pull/1110/files#diff-c7b517e8422253bdca93e9c0d49cbecd98c42d0ef796342c9319078eaebfb1b7R1425-R1426
- Virtual Machine**s** Snapshots: https://github.com/harvester/dashboard/pull/1110/files#diff-c7b517e8422253bdca93e9c0d49cbecd98c42d0ef796342c9319078eaebfb1b7R1440-R1441

**Comment by rrajendran17** [comment]
Tested on v1.4-00cd4ee-head and found the following discrepancies.

1.rancher monitoring (Addon: rancher-monitoring) is this Addon should be hyphenated ?
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeDMyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3bb3829073ff240daf361318972d4b0626dcd944/image2.png" alt="image2.png" />

2.miimon under cluster network config does not explain what it means.
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUQyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d78797bd8c47deb62475c332e8d9b20b4da0bde0/image6.png" alt="image6.png" />

3.Alert manager configs contradicts with Alert Manager configurations

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeUgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e7ab4ebd07539428a66046cd2d829e19d8f84726/image11.png" alt="image11.png" />

4.Logging (cluster Flow,cluster output,flow,output) contradicts with (cluster Flows.cluster Outputs,Flows,outputs)
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeVgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2fd249f53dc22790be2eae9a9eb84241c87ae7a9/image12.png" alt="image12.png" />

5.PCI Devices description not changed as described in the bug

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeWIyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e0a33ac2dc8fe16a51b9e1d7a4cb8818c9de0712/image14.png" alt="image14.png" />

6.Settings description (Typical users...) not changed as expected in the bug 
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeW4yQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6cf4b3b13f962b1b35a1237a44f1abc5cbdea04a/image16.png" alt="image16.png" />

7.During creation of the vm, the message (VirtualMachine generation is 2...) is still VirtualMachine and not separated as "Virtual Machine"
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeXYyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d285766d7bfeddba881e7340d31781a06f143c85/image17.png" alt="image17.png" />

8.Discrepancy between Virtual Machine Networks and Virtual Machines Networks
                                       Virtual Machine Backups and Virtual Machines Backups
                                       Virtual Machine Snapshots and Virtual Machines Snapshots

@asettle Please let me know if you will open a separate PR to take care of above missed ones ?

**Comment by asettle** [comment]
> @asettle Please let me know if you will open a separate PR to take care of above missed ones ?
Will do - thank you!

**Comment by asettle** [comment]
Here we go: https://github.com/harvester/dashboard/pull/1176 two things are missing atm

**Comment by TachunLin** [comment]
During fixing the cypress test on `v1.4.0-rc1`.  

I found there seems a string inconsistency on the `Take Virtual Machine snapshot` 

* The vm menu option display with `Take Virtual Machine snapshot`
  ![image](https://github.com/user-attachments/assets/4adb8bc8-6c15-4677-8136-9945c3f790da)

* While the dialog title have `Take VM Snapshot` 
  ![image](https://github.com/user-attachments/assets/82fb39e6-c310-43f5-8050-55ff0831120f)

* Related cypress take virtual machine snapshot case
  ![image](https://github.com/user-attachments/assets/788a7f09-7d3b-4f63-94b1-603749bfa5fa)


Do we still have the chance to also check and update them. Many thanks.

**Comment by rrajendran17** [comment]
verified on v1.4-aa4976-head and discrepencies mentioned during testing v1.4-00cd4ee-head are fixed and works as expected
<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM2tsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--84b543381429205bff9270a42e591111d5357122/6407f1.png" alt="6407f1.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM29sQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--ca9a16e830f1ff3c73efd26c380f2f332d20337b/6407f2.png" alt="6407f2.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3NsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--761b5476fc7f6abe94f53876e8247845154b7c03/6407f3.png" alt="6407f3.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBM3dsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a9fb842ad229671fb4642da8f9603f26cf3f6931/6407f4.png" alt="6407f4.png" />

<img width="1344" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMzBsQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--16f8fd03e1256abb1e8f541f312c0c3c90ced213/6407f5.png" alt="6407f5.png" />

**Comment by TachunLin** [comment]
@asettle, 
May I know if we still have chance to check and update the dialog title inconsistency for the `Take VM snapshot` as explained in [comment](https://github.com/harvester/harvester/issues/6407#issuecomment-2390455220). Many thanks.

![image](https://github.com/user-attachments/assets/4264d247-a46f-454e-bef1-02ea16528af0)

**Comment by rrajendran17** [comment]
The inconsistency of "Take Virtual Machine Snapshot" and "Take VM Snapshot" is fixed.Verified in v1.4.0-rc4. Hence closing this.

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNmgxQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--21a8b16d04b89bb788208c1d741cf3a6cc06d502/vmsnap.png" alt="vmsnap.png" />
