### ISSUE TITLE
[BUG] After edit vm description, vm will be restarted

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#641]
**Describe the bug**

**To Reproduce**
1. click `Edit Config`
2. add vm description

**Expected behavior**

don‘t restart vm, if just edit vm description

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Validated on master-621eedd7-head

Steps:
1. click Edit Config
2. add vm description

Result:
Saved successfully, and the vm did not restart
