### ISSUE TITLE
[BUG] managed dhcp works sporadicaly

### ISSUE THREAD

**Issue by SnakebiteEF2000** [harvester/harvester#6419]
**Describe the bug**
5 node clusters, 4 physical machines, and one witness node running in VMware
managed DHCP add-on installed and configured for a VLAN network
The VLAN is set up as allowed and tagged for the mgmt interfaces of harvester on the switch. The witness node does not have a tagged VLAN on its mgmt interface

The DHCP always hands out an IP address when checked with the given command in the documentation, the VM network configuration gets created correctly, but the VM does not receive or use the IP. This happens in about 80% of cases, and sometimes it works flawlessly

**To Reproduce**
Set up a cluster with a witness node
connect to Rancher
Create an Ubuntu cloud image minimal Nobel 2024 image
Create a namespace and a VLAN vm network tag 2024
Create clusters using Rancher.

**Expected behavior**
VMs get IPs
**Support bundle**
This is a company cluster, so I am not sure if I am allowed to add it here. I will add it later, when I checked.

**Environment**
 - Harvester ISO version:  1.3.1
 - Underlying Infrastructure (e.g. Bare-metal with Dell PowerEdge R630):
 - 4x PowerEdge R630 16-core, 96-GB ram split into two Datacenters
 - witness node 8 cores 32gb ram running in VMware
 - 1 master and 1 worker in each datacenter

**Additional context**
I have installed the DHCP add-on manually using Helm because the cluster is behind a DPI firewall

IPpool setup for the vlan net
```yml
apiVersion: network.harvesterhci.io/v1alpha1
kind: IPPool
metadata:
  name: t3-dynamic-services-2024
  namespace: testnetz-testing
spec:
  ipv4Config:
    serverIP: 10.13.9.29
    cidr: 10.13.9.0/24
    pool:
      start: 10.13.9.30
      end: 10.13.9.50
    router: 10.13.9.1
    dns:
    - 10.2.0.101
    - 10.2.0.102
    - 10.2.0.103
    domainName: t3.example.lan
    domainSearch:
    - t3.example.lan
    ntp:
    - ntp01.example.lan
    - ntp02.example.lan
    leaseTime: 300
  networkName: testnetz-testing/t3-dynamic-services-2024
```

Network config of a VM with this issue. A finalizer seems to persist and hinder the completion of the setup
```bash
k get virtualmachinenetworkconfigs.network ds-testcase-sup-testing-worker-c7f60d65-72sjr -n testnetz-testing -o yaml

apiVersion: network.harvesterhci.io/v1alpha1
kind: VirtualMachineNetworkConfig
metadata:
  creationTimestamp: "2024-08-26T05:39:19Z"
  finalizers:
  - wrangler.cattle.io/vm-dhcp-vmnetcfg-controller
  generation: 2
  labels:
    harvesterhci.io/vmName: ds-testcase-sup-testing-worker-c7f60d65-72sjr
  name: ds-testcase-sup-testing-worker-c7f60d65-72sjr
  namespace: testnetz-testing
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    kind: VirtualMachine
    name: ds-testcase-sup-testing-worker-c7f60d65-72sjr
    uid: 92add140-faec-4998-9ed3-ba8ad5218cd9
  resourceVersion: "8537025"
  uid: abfa0f29-d7fc-4c69-aa31-2f10c35d4913
spec:
  networkConfigs:
  - macAddress: 2e:f4:b2:d9:af:2e
    networkName: testnetz-testing/t3-dynamic-services-2024
  vmName: ds-testcase-sup-testing-worker-c7f60d65-72sjr
status:
  conditions:
  - lastUpdateTime: "2024-08-26T05:39:37Z"
    status: "True"
    type: Allocated
  - lastUpdateTime: "2024-08-26T05:39:19Z"
    status: "False"
    type: Disabled
  networkConfigs:
  - allocatedIPAddress: 10.13.9.40
    macAddress: 2e:f4:b2:d9:af:2e
    networkName: testnetz-testing/t3-dynamic-services-2024
    state: Allocated
```

**Comment by starbops** [comment]
Hi @SnakebiteEF2000, thank you for reporting to us. Please attach the support bundle file so we can have more information to work on. If that's inconvenient, posting the log for the `harvester-vm-dhcp-controller` would be much appreciated.

It looks fine from the IPPool and VirtualMachineNetworkConfig objects you posted. Does the DHCP IP address always allocated to your VirtualMachineNetworkConfig object, even when the actual virtual machine did not receive the IP address?

Besides, I'm also curious about what the chart you used to install vm-dhcp-controller? Is it the one from the harvester/vm-dhcp-controller project, or the other under the harvester/charts?

**Comment by SnakebiteEF2000** [comment]
Hello @starbops Thanks so much for your answer. I will close this issue now as this problem is solved. The network team at our Datacenter replaced the spine and leaf switches of the rack one of the harvester servers was in. Somehow there was a misconfiguration of the native vlan which caused this issue. 


As for the install. I just cloned the repo and installed it as local chart.
