### ISSUE TITLE
[BUG] The filter box of the vm list is not filtered correctly

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#642]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/113384794-648b0f80-93b9-11eb-87ac-0d1805494c54.png)

**To Reproduce**
1. Go to `Virtual Machines`
2. Enter a character in the filter box and vm will be displayed even if no virtual machine has this character in its name

**Expected behavior**

vm list will be filtered correctly

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DaiYuzeng** [comment]
@WuJun2016 

all of columns is searchable by default, if we don't add the `search: false` for columns.

do we need to set columns to be unsearchable by default?

**Comment by guangbochen** [comment]
duplicate of https://github.com/rancher/harvester/issues/661

**Comment by n313893254** [comment]
`state` is `running` with `i`.  The search result is expected.
