### ISSUE TITLE
Harvester 1.3.2 to deploy with longhorn 1.6.3?

### ISSUE THREAD

**Issue by jrlittlefoot64** [harvester/harvester#6421]
I read in lonhorn issue [#9132](https://github.com/longhorn/longhorn/issues/9132) about the security issues, is it not better to wait till longorn 1.6.3 is ready?

**Comment by votdev** [comment]
> I read in lonhorn issue [#9132](https://github.com/longhorn/longhorn/issues/9132) about the security issues, is it not better to wait till longorn 1.6.3 is ready?

In which direction is your question aimed? Waiting with the Harvester 1.3.2 release or with your local installation?

**Comment by bk201** [comment]
Hi, Longhorn 1.6.3 date is not firm yet. We'll include v1.6.3 in Harvester 1.3.3.

**Comment by jrlittlefoot64** [comment]
I think waiting with the harvester release 1.3.2. In a lab installation is okay to not wait, but in an production environment I will get problems with our security department and i think i am not alone. It's only for discuss here.

**Comment by jrlittlefoot64** [comment]
1.3.2 is out, I closed this issue
