### ISSUE TITLE
[BUG] After change UI to Chinese, Migration tab still display English

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#643]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/113385185-2fcb8800-93ba-11eb-8e83-f05a015c4a94.png)

**To Reproduce**
1. change UI to Chinese
2. check migration tab display

**Expected behavior**

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
Fields on migration tab are still display English. @DaiYuzeng 
 ![image](https://user-images.githubusercontent.com/15064560/114667118-aa3cc600-9d31-11eb-89fc-d3c7c1eb3ddb.png)

**Comment by TangStone** [comment]
Validation passed in version master-95a5828a-head
![image](https://user-images.githubusercontent.com/15829074/115181444-8d760900-a10a-11eb-947a-b61d9f60924b.png)
