### ISSUE TITLE
[BUG] Strange UI Error around "backup-target" setting if "http-proxy" is set / unset

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6441]
**Describe the bug**
Based on:
https://github.com/harvester/harvester/issues/6440
^ Following those repro steps.
Seeing a strange UI Error around "backup-target" that is claiming "backup-target" already exists... but it doesn't... it was never set or modified.

**To Reproduce**
1. Follow steps in 6440
1. Notice too, it has another un-intended side-effect of causing Settings -> Backup-Target to have an erronous error on the Front-End / Dashboard / Web-UI

**Expected behavior**
backup-target to not spit back an error in the settings ui

**Environment**
 - Harvester ISO version: v1.3.2-rc2
 - Underlying Infrastructure: bare-metal

**Additional context**
![Screenshot from 2024-08-28 11-50-47](https://github.com/user-attachments/assets/c39a9355-6d33-40ed-8cc8-b191319e8cfc)

**Comment by votdev** [comment]
@irishgordo Can you please update the steps to reproduce the error. The description gives no indication of when the error occurs. Do I have to press `Cancel` after getting the admission webhook error in `http-proxy` to see the `backup-target` error? Or do i have to do something else?

**Comment by irishgordo** [comment]
I can not reproduce this consistently.
But I can reproduce #6440 consistently :smile: 
So I'll go ahead and close this out @votdev 
I'll re-open if I see it again, but out of 5 tries, I was not able to see it again.
