### ISSUE TITLE
[BUG] copy button in Harvester UI doesn't work in upstream Rancher cluster

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6448]
**Describe the bug**

When you click the copy button next to an IP on the VM list it doesn't copy the text. This happens in virtualization management when you 
**To Reproduce**
1. Import Rancher into upstream Rancher
2. Navigate to Harvester UI through virtualization management
3. Go to the virtual machine list
4. Click the copy button next to an IP

**Expected behavior**

The text should be copied to the clipboard
**Support bundle**

[supportbundle_63da7e36-1372-48e0-bd03-d449fd141c63_2024-08-29T19-41-17Z.zip](https://github.com/user-attachments/files/16805176/supportbundle_63da7e36-1372-48e0-bd03-d449fd141c63_2024-08-29T19-41-17Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Rancher version: Helm install of v2.9.0 on RKE2 on v1.30 k8s
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node DL160

**Additional context**

This does not happen in the Harvester UI when logged in directly
![Greenshot 2024-08-29 12 37 56](https://github.com/user-attachments/assets/d0bf24f2-3ef9-46f4-849f-9bca06e2a7f3)

```
TypeError: this.$copyText is not a function
    at a.clicked (CopyToClipboardText.vue:23:1)
    at _n (vue.min.js:11:22257)
    at HTMLAnchorElement.r (vue.min.js:11:10679)
    at o._wrapper (vue.min.js:11:59895)
En @ vue.min.js:11
wn @ vue.min.js:11
yn @ vue.min.js:11
_n @ vue.min.js:11
r @ vue.min.js:11
o._wrapper @ vue.min.js:11
Show 6 more frames
Show less
```

**Comment by innobead** [comment]
@a110605 is this also related to https://extensions.rancher.io/extensions/rancher-2.9-support#breaking-changes-in-290?

**Comment by a110605** [comment]
> @a110605 is this also related to https://extensions.rancher.io/extensions/rancher-2.9-support#breaking-changes-in-290?

The rancher/dashboard v2.9.0 have drastically change. But harvester shell still stay in a legacy version v2.7...

The [CopyToClipboardText.vue](https://github.com/rancher/dashboard/blob/master/shell/components/CopyToClipboardText.vue) is modified in rancher/dashboard. (v.s harvester [CopyToClipboardText.vue](https://github.com/harvester/dashboard/blob/master/shell/components/CopyToClipboardText.vue))


I think we just need to port the change back to harvester shell that can make it work in rancher embedded mode. 
I will try it.

**Comment by rrajendran17** [comment]
verified in v1.4.0-rc2, rancher version v2.9.2 and it works as expected.
