### ISSUE TITLE
[BUG] image error of the VM template

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#645]
**Describe the bug**
1. when creating a new VM template version the image is always required.
2. when creating a new VM template version the previous configured image is not copied.

**Expected behavior**
1. the image should not be required.
2. when creating a new VM template version, if the previous version contains an image it should also be carried over to the new one. 

**Log**
N/A

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
Create a virtual machine template without image, created successfully and can be used normally
![image](https://user-images.githubusercontent.com/15829074/115345602-9e457e00-a1e1-11eb-82d4-d03099f015a1.png)

**Comment by TangStone** [comment]
Create a vm template, add the new version, the previous image configuration is not copied @DaiYuzeng

**Comment by TangStone** [comment]
Validation in version master-0008ce84-head
1. Create a vm template without image and use that template to create the vm
2. Create a vm template, add the new version, the previous image configuration is copied
