### ISSUE TITLE
[BUG] Rancher doesn't use dark mode in popup modals when in Harvester UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6450]
**Describe the bug**

When you get a popup in Harvester UI while using upstream Rancher virtualization management it doesn't use dark mode if it's set
**To Reproduce**
1. Set default preference to dark mode
2. Import Harvester into Rancher
3. Go into Harvester UI through virtualization management in Rancher
4. Edit one of the VMs and make a change, such as changing the network
5. Click Save

**Expected behavior**

The popup should be in dark mode
**Support bundle**

[supportbundle_63da7e36-1372-48e0-bd03-d449fd141c63_2024-08-29T20-34-23Z.zip](https://github.com/user-attachments/files/16805796/supportbundle_63da7e36-1372-48e0-bd03-d449fd141c63_2024-08-29T20-34-23Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Rancher version: Rancher v2.9.0 deployed via helm on single node RKE2 k8s v1.30
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160

**Additional context**

![Greenshot 2024-08-29 13 32 32](https://github.com/user-attachments/assets/0b03ab55-61e4-4a4e-90b3-b5b190f55dff)
![Greenshot 2024-08-29 13 31 44](https://github.com/user-attachments/assets/4c753aaf-ea18-463d-9317-882b5c6f3178)

**Comment by a110605** [comment]
Hi QA, 
The fixed PR replaces all modals using the latest version. 
We have tested most of them, but could you kindly help check ALL the pop-up modals and ensure everything work as expected. 

See : https://github.com/harvester/dashboard/pull/1163

**Comment by lanfon72** [comment]
milestone/release required.

**Comment by w13915984028** [comment]
Test: **PASS**

(1) Install Rancher v2.9.2, set dark mode
(2) Import Harvester v1.4.1-rc4
(3) Edit a VM:

![image](https://github.com/user-attachments/assets/5b7f6683-cdf3-4408-8275-178ed222df87)

delete the vm:
![image](https://github.com/user-attachments/assets/079ecbc5-2eaa-431b-ab2b-103527236439)


(4) Change a LB to trigger admission webhook:
![image](https://github.com/user-attachments/assets/f3b52c0f-320c-40e1-980c-8c0ef2cec6f1)


(5) Add disk on Host page:
![image](https://github.com/user-attachments/assets/f7954a81-7616-4396-b2e3-972e5c3fb92c)

(6) Resume a stopped schedulevmbackup
![image](https://github.com/user-attachments/assets/17632b6d-4d66-4d19-a4ba-4671fb8243e6)

(7) Networking, looks good

![image](https://github.com/user-attachments/assets/e574d7ab-6128-4b46-a03f-849064114c5f)

**Comment by w13915984028** [comment]
@a110605 @torchiaf 

BTW, from my personal view of point,  following info looks not so `noticeable` sometimes. But I won't mark them as bugs.


`Settings that have been customized from default settings are tagged with 'Modified'.`

![image](https://github.com/user-attachments/assets/6dd958c6-7a4e-417c-9653-e06e990e7b95)

![image](https://github.com/user-attachments/assets/204d72cd-0dd5-427a-9001-90a634289657)

`Modified`, `Experimental`,

![image](https://github.com/user-attachments/assets/83350806-1d7e-4838-b278-d06204ff9680)

![image](https://github.com/user-attachments/assets/2cda7bfa-123a-49ed-aab7-539d3d46450b)

`upgrade-checker-enabled` hard to be noticed on `light`/`auto` mode.

![image](https://github.com/user-attachments/assets/b112cbd6-2451-4b00-8e35-72bce6eb87f6)

![image](https://github.com/user-attachments/assets/2c7a2a1b-68a3-40a5-90aa-12632c8ef46e)

**Comment by w13915984028** [comment]
The original bug is fixed.

With a general test/UI navigation via Rancher v2.9.2 & Harvester v1.4.0-rc4, the UI `dark mode` looks good. Thanks @noahgildersleeve @a110605 @torchiaf.
