### ISSUE TITLE
[BUG] Harvester importing of OpenStack VMs that have minimal resources enter SeaBIOS BootLoop

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6452]
### Describe the bug
Importing of OpenStack (Devstack, 2023.1/stable) VMs like `cirros` that have a minimal amount of resources on OpenStack

Example:
- 1GB Root Disk
- 128 MB RAM
- 1 vCPU

Simply do not run on Harvester

### Workaround
1. The user will need to manually increase the resources to the VMs that were imported from OpenStack that may have "run fine" in OpenStack but Harvester needs more resources for the VM to be up and running successfully.
2. Once the user bumps the resources up: MEM, Disk (mainly) -> The VM can run successfully.

### To Reproduce:
1. have some m1.nano & m1.micro vms running in OpenStack
2. import them via VM Import Controller 
3. the vms won't start, SeaBIOS Boot Loop

### Expected Behavior
VMs not to be stuck in boot loop

### Environment
 - Harvester ISO version: v1.3.2-rc2 
 - Underlying Infrastructure: bare-metal

#### Example not running, stuck in bootloop

https://github.com/user-attachments/assets/388b9e61-b08f-467d-937e-ea8d50f103ff

#### Example running, once finally we increase the resources because OpenStack flavors don't work with parity with Harvester

https://github.com/user-attachments/assets/5e05d3bd-85da-49f0-a863-933ce9332e07

*screengrab*
![Screenshot from 2024-08-29 17-57-37](https://github.com/user-attachments/assets/c9a3596a-a52d-49b3-b99b-657f1ab9d325)

**Comment by ibrokethecloud** [comment]
technically this is not a bug since kubevirt will have its own minimal vm sizing requirements

we can extend the CRD to allow user to override imported VM's cpu/memory sizing to allow vm-import-controller to resize incoming vm.

**Comment by bk201** [comment]
@irishgordo I added an enhancement https://github.com/harvester/harvester/issues/6456 to track. Nano size VMs are not common in production, do you think we can close this one?

**Comment by irishgordo** [comment]
@ibrokethecloud  yeah I think extending the CRD to allow users to override their possible small vms in OpenStack would be beneficial :smile: :+1: 

@bk201  -I'll go ahead and close this out since you've opened that up

Thanks to you both :smile: :+1:
