### ISSUE TITLE
[DOC] Update for Storage Network IP Usage

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6457]
**Describe the solution you'd like**
LH consolidates `im-e` and `im-r` pods to [single `im` pod](https://github.com/longhorn/longhorn/issues/5208),so the #IPs required for Storage Network changed. 

Harvester should have a [document](https://docs.harvesterhci.io/v1.3/advanced/storagenetwork#configuration-example) update accordingly.

**Comment by bk201** [comment]
Doc is published: https://docs.harvesterhci.io/v1.3/advanced/storagenetwork/#configuration-example
