### ISSUE TITLE
[BUG] UI Reports total available on root file systems, not total Longhorn storage

### ISSUE THREAD

**Issue by gregoryg** [harvester/harvester#647]
**Describe the bug**
UI Dashboard -> Storage size reports total disk size on the root file systems in the Harvester cluster, not the total storage available to Longhorn

**Expected behavior**
The total Longhorn storage is what's relevant to Harvester, not the local root partition storage size.  Expected behavior would be to report the same number shown in the Longhorn UI (either "Storage Schedulable" or "Total")

**Environment:**
 - Harvester ISO version: 0.2.0-rci
 - Installation Mode: ISO and App modes
 - Underlying Infrastructure: Baremetal or virtualized

**Comment by yasker** [comment]
We will address it in https://github.com/harvester/harvester/issues/747 .
