### ISSUE TITLE
[ENHANCEMENT] Hardening `syncHTTPProxy` function

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#6473]
**Is your enhancement related to a problem? Please describe.**
The [syncHTTPProxy](https://github.com/harvester/harvester/blob/3123cb9b11f7185e9218e954212bcb2ae2d945f7/pkg/controller/master/setting/http_proxy.go#L18) function is decoding the setting string into JSON. The setting type is `string` and the `Value` property might be an empty string (which is no valid JSON). This circumstance might cause a decoding error.

**Describe the solution you'd like**
Handle empty strings as `{}`.

**Describe alternatives you've considered**
n/a

**Additional context**
See https://github.com/harvester/harvester/pull/6447#discussion_r1740554200

**Comment by innobead** [comment]
@votdev don't forget to set the milestone. For every item we are working on, need the milestone set. Otherwise, this will be never covered in a release and verified by QA.

cc @bk201 @harvester/qa

**Comment by albinsun** [comment]
Test PASS, try config settings which accept empty value and does not show error, close as done.


## Environment
* `harvester-v1.4.0-rc2`
  * Profile: 2 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`


## Test Case
1. <details>
   <summary> :green_circle: <b>additional-ca</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/a27a0317-221c-4e15-8e6f-85ea1186e9f3)
   2. **Use the default value**
      ![image](https://github.com/user-attachments/assets/833a84dd-8d6b-4594-8365-1fbc42231fa9)
   </details>

1. <details>
   <summary> :green_circle: <b>additional-guest-memory-overhead-ratio</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/0404b59b-20ef-41fd-b10e-40c4303c9e96)
   2. Empty
      ![image](https://github.com/user-attachments/assets/b5ae014b-6958-417d-9484-d12ce16af430)
      adopt default value `1.5`
      ![image](https://github.com/user-attachments/assets/11ed2ee0-bd06-438d-bc77-450c2efa8e5f)

   </details>

1. <details>
   <summary> :green_circle: <b>auto-disk-provision-paths</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/383c9533-229d-4844-a835-2f68c5a7521e)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/d47d435b-7dae-450e-b3a5-769a4ea2cf3b)
   </details>

1. <details>
   <summary> :green_circle: <b>auto-rotate-rke2-certs</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/c9148b76-e5e2-4e95-8395-83f98253f981)
   2. **Use the default value** -> Disable
      ![image](https://github.com/user-attachments/assets/936e8d44-507e-4a7a-8e6d-361e6e71da89)
   </details>

1. <details>
   <summary> :green_circle: <b>backup-target</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/726aab19-ebc6-40f3-8b39-894da20768b9)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/eae7139c-e03a-4338-8f19-17d899c14ae4)
   </details>

1. <details>
   <summary> :green_circle: <b>cluster-registration-url</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/cb7e6366-9424-4240-8c0a-3d16674bb159)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/4d1cf816-26f2-4458-9def-784747bbffc6)
   </details>

1. <details>
   <summary> :green_circle: <b>containerd-registry</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/f72bb5cf-c432-4e6f-9e1c-077f358483be)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/9273d049-f8dd-4016-902f-1ea98ab5b9e7)

1. <details>
   <summary> :white_circle: <b>csi-driver-config</b>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/598d71a0-b628-46a4-a9ad-81abcb91e1db)
   </details>

   > Does not allow configure

1. <details>
   <summary> :green_circle: <b>default-vm-termination-grace-period-seconds</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/912c13e2-9f5b-4fc5-a80d-2b7224a5500b)
   2. Empty value will be block
      ![image](https://github.com/user-attachments/assets/2e62e53e-b17f-41c1-8315-cc906ef5833e)
   </details>

1. <details>
   <summary> :green_circle: <b>http-proxy</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/b985c642-795b-40d9-afb9-916c545c12e1)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/8a649b62-095d-4a8d-84b5-81d3ba0b0c69)
   </details>

1. <details>
   <summary> :green_circle: <b>kubeconfig-default-token-ttl-minutes</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/6d55e49a-f8d5-48e6-bd4b-9d22a44d18b0)
   2. Empty value
      ![image](https://github.com/user-attachments/assets/41f55f5b-570f-4fdb-9dd6-55590084fcd0)
   </details>

1. <details>
   <summary> :green_circle: <b>ntp-servers </b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/db8c6ba7-6662-487e-9a1a-f7f36eb9f6fe)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/9ad321d2-52b8-4bc7-abc8-1edae9070b36)
   </details>

1. <details>
   <summary> :green_circle: <b>release-download-url</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/669a014f-0ffc-4450-b9b0-548748bb0b83)
   2. Empty string converts to default URL
      ![image](https://github.com/user-attachments/assets/2c3c5141-751d-45f6-b5d0-09d30455d8a9)
   </details>

1. <details>
   <summary> :green_circle: <b>support-bundle-expiration</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/4520675f-416d-4f90-9786-0239ef5287ac)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/7da60720-4c84-4287-84f1-b738538566f2)
   </details>

1. <details>
   <summary> :green_circle: <b>support-bundle-namespaces</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/421cac62-22b6-46af-a22d-859f61371096)
   2. Empty by **Use the default value**
      ![image](https://github.com/user-attachments/assets/2b559c8d-9659-4fe9-9fe6-433c09b18ce8)
   </details>

1. <details>
   <summary> :green_circle: <b>support-bundle-node-collection-timeout</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/8d92af11-0f89-4dc2-85e1-fa19f637cd04)
   2. Empty value
      ![image](https://github.com/user-attachments/assets/d6146084-008e-4974-9f47-a7056dd2a4cf)
   </details>

1. <details>
   <summary> :green_circle: <b>support-bundle-timeout</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/82f7a296-e0ff-4679-b9fc-cb2c190035cf)
   2. Empty value
      ![image](https://github.com/user-attachments/assets/41663395-a530-4770-9876-62d96bb64a35)
   </details>

1. <details>
   <summary> :green_circle: <b>upgrade-checker-url</b>
   </summary>
   
   1. Configured
      ![image](https://github.com/user-attachments/assets/bbc4fd06-f967-4801-90ae-ff86a774ddfd)
   2. Empty value
      ![image](https://github.com/user-attachments/assets/8d7855ad-913c-42bc-8d93-ececd75d7a75)
   </details>

1. <details>
   <summary> :green_circle: <b>vm-force-reset-policy</b>
   </summary>
   
   Empty value will be block
   ![image](https://github.com/user-attachments/assets/3abec550-16a3-43e7-8540-5515a965865a)
   </details>
