### ISSUE TITLE
[GUI] [ENHANCEMENT] When creating a VM from the Images List, canceling may return to the Image List page instead of the VM List page

### ISSUE THREAD

**Issue by went2** [harvester/harvester#6485]
**Is your enhancement related to a problem? Please describe.**
When initiating a creation of a virtual machine from the Image list page and then click "Cancel" on the creation page, it navigates to the VM list page instead of Images list.

![image1 creating a virtaul machine from an image](https://github.com/user-attachments/assets/412fb9ef-a97d-4f85-b8da-6f174977e90e)
image1: create a virtaul machine from an image

![image2: cancel the creation](https://github.com/user-attachments/assets/306d4e5c-9f4c-4b94-b451-368c9874b1b3)
image2: cancel the creation

![image3: router navigates to the VM list](https://github.com/user-attachments/assets/431282da-d659-40ae-a3a7-93e6a28dd2ca)
mage3: router navigates to the VM list

**Describe the solution you'd like**
It would provide more consistent user experience to navigate back to the Images list on canceling an VM creation which is initiated from the Images List page.

**Additional context**
Harvester Dashboard version: v1.3.0

**Comment by Faker523** [comment]
my env has the same problem

**Comment by rrajendran17** [comment]
Tested on v1.4-00cd4ee-head and works as expected.<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVAyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d8e6c2d80346f5b1a3fd405c633629043d33a8b3/6485image1.png" alt="6485image1.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVQyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--b9eaf1cdeba642ff586885a9911d64b9789ed13b/6485image2.png" alt="6485image2.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMVgyQmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--a71c26dfd525a356020d23354a76d97772208996/6485image3.png" alt="6485image3.png" />
