### ISSUE TITLE
[ENHANCEMENT] Detect Red Hat linux OS Type like Ubuntu and OpenSUSE

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6503]
**Is your enhancement related to a problem? Please describe.**
1. Create VM -> **Volumes** -> Choose `rhel-9.4-x86_64-kvm.qcow2`
   ![image](https://github.com/user-attachments/assets/738c678f-7739-43d9-b5e5-a0134d004585)
1. -> **Advanced Options**, OS Type is not detected.
   ![image](https://github.com/user-attachments/assets/4474cf72-29a2-446c-b989-8c05fd338550)

**Describe the solution you'd like**
Redhat linux should also be detect like Ubuntu and OpenSUSE.
For example,
![image](https://github.com/user-attachments/assets/2104b9b2-0a63-40a4-b5a1-c190ea98f1b8)
![image](https://github.com/user-attachments/assets/9c844c6b-2823-4be6-a6bf-e1c5207dbd4e)

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rrajendran17** [comment]
Verified on v1.4-00cd4ee-head and works as expected
<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNy84Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--699fb62245b7f1e87ccf85f0ad83d6de2971c567/rhelimage1.png" alt="rhelimage1.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEQ4Qmc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2bddce6ebe299a2af2ed83c5258cce35a2812e84/rhelimage2.png" alt="rhelimage2.png" />
