### ISSUE TITLE
[FEATURE] update both API version and API group before the v0.2.0 release

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#651]
**Is your feature request related to a problem? Please describe.**
update both API version and API group before the v0.2.0 release

**Describe the solution you'd like**
bump the API version to `v1beta1` and API group to the `harvesterhci.io`
- [x] update the API version and API group of the Harvester.
- [x] update the API group and API version of the network-controller chart.
- [x] update the API version, label, and annotations of the Harvester UI.
- [x] bump the Harvester API version in the Harvester node driver
- [x] update API group of the managed host annotation (harvester-installer)

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by guangbochen** [comment]
should be validated using the `harvester-master.iso` created after 21/04.
1. run `$kubectl get crds | grep harvester.cattle.io` should not exist
2. the harvesterhci.io CRD's version should be v1beta1
3. both UI and the Harvester node-driver should be working as expected and no error message is expected
4. network controller pods should be running and its API group and API version should be is `network.harvesterhci.io` and `v1beta1` respectively.
5. node promotion should be working as expected

**Comment by kingsd041** [comment]
validated on v0.2.0-rc4

1. `$kubectl get crds | grep harvester.cattle.i` returns empty
```
h1 [~]# kubectl get crds | grep harvester.cattle.io
h1 [~]#
```

2. All Harvesterhci.io CRD versions are v1beta1
```
h1 [~]# crd_name=`kubectl get crd | grep harvesterhci.io | awk '{print $1}'`

h1 [~]# for crd in $crd_name; do version=`kubectl get crd $i -o jsonpath='{.spec.versions[0].name}'`; echo "$crd version: $version" ;done
clusternetworks.network.harvesterhci.io version: v1beta1
keypairs.harvesterhci.io version: v1beta1
nodenetworks.network.harvesterhci.io version: v1beta1
preferences.harvesterhci.io version: v1beta1
settings.harvesterhci.io version: v1beta1
upgrades.harvesterhci.io version: v1beta1
users.harvesterhci.io version: v1beta1
virtualmachinebackupcontents.harvesterhci.io version: v1beta1
virtualmachinebackups.harvesterhci.io version: v1beta1
virtualmachineimages.harvesterhci.io version: v1beta1
virtualmachinerestores.harvesterhci.io version: v1beta1
virtualmachinetemplates.harvesterhci.io version: v1beta1
virtualmachinetemplateversions.harvesterhci.io version: v1beta1
```

3. The Harvester node driver does not work as expected due to https://github.com/harvester/harvester/issues/775
4. The network controller Pod is operating normally, and its API group and API version are network.harvesterhci.io and v1beta1 respectively.
```
h1 [~]# kubectl get pods -A | grep network
harvester-system          harvester-network-controller-67d9k                      1/1     Running     1          3h36m
harvester-system          harvester-network-controller-d2s7n                      1/1     Running     0          3h46m
harvester-system          harvester-network-controller-manager-749bff44cf-9925p   1/1     Running     0          3h46m
harvester-system          harvester-network-controller-manager-749bff44cf-vgz2v   1/1     Running     1          3h46m
harvester-system          harvester-network-controller-ql8tr                      1/1     Running     0          3h32m

h1 [~]# crd_name="clusternetworks.network.harvesterhci.io nodenetworks.network.harvesterhci.io"
h1 [~]# for crd in $crd_name; do version=`kubectl get crd $i -o jsonpath='{.spec.versions[0].name}'`; echo "$crd version: $version" ;done
clusternetworks.network.harvesterhci.io version: v1beta1
nodenetworks.network.harvesterhci.io version: v1beta1
```

5. About the harvester upgrade -- https://github.com/harvester/harvester/issues/383
