### ISSUE TITLE
[BUG] rke2-nginx-ingress-controller workload stuck with InProgress (Containers with unready status) on SLES SP5/6 based RKE2 clsuter 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6515]
**Describe the bug**
We found that on a SLES SP5/6 based RKE2 cluster, rke2-nginx-ingress-controller workload can not successfully `Active` and stuck `InProgress`

![image](https://github.com/user-attachments/assets/6e6c9c67-eb45-4902-81c8-f17de8b5aca7)

![image](https://github.com/user-attachments/assets/086affa8-1481-4300-9217-1163defbe5b6)

**To Reproduce**
1. Join `harvester-v1.3.2-rc2` to `rancher-v2.8.5`
1. Create a RKE2 cluster (`rke2-1.28`) based on SLES SP5/6
   * `SLES15-SP5-Minimal-VM.x86_64-Cloud-GM.qcow2`
   * `SLES15-SP6-Minimal-VM.x86_64-Cloud-GM.qcow2`
1. RKE2 cluster is `Active`
1. Check workloads and Apps :x:
   > rke2-nginx-ingress-controller stuck with `InProgress`
   > ![image](https://github.com/user-attachments/assets/6e6c9c67-eb45-4902-81c8-f17de8b5aca7)

**Expected behavior**
All workloads and apps should be bring up.

**Support bundle**
n/a

**Environment**
* `harvester-v1.3.2-rc2`
  * Profile: Single node baremetal (48C/128G/2T)
  * ui-source: `Auto`
* `rancher-v2.8.5`
  * Profile: rancher-vcluster (`v1.28.13+k3s1`)
  * Guest Cluster
    * Image: SLES SP5/6
    * Profile: Single node `v1.28.13+rke2r1`

**Additional context**
1. Same test work fine on SL-Micro 6, RHEL 9 and Ubuntu 22 based RKE2 cluster.

**Comment by irishgordo** [comment]
@albinsun - this looks to be similar symptoms of:

https://github.com/harvester/harvester/issues/6418#issuecomment-2309775157

Could you check?

As I believe `kernel-default` package must be installed when you "first" build your RKE2 cluster in order to have RKE2 DHCP LoadBalancers work with SLES SP5/SP6 work out of the box.

**Comment by starbops** [comment]
The ingress-nginx-controller pod remains in the `ContainerCreating` state with the following reason:

```
$ kubectl -n kube-system describe pods rke2-ingress-nginx-controller-wqmnq 
Name:             rke2-ingress-nginx-controller-wqmnq
Namespace:        kube-system
...
Events:
  Type    Reason          Age                   From                      Message
  ----    ------          ----                  ----                      -------
  Normal  SandboxChanged  33m (x555 over 153m)  kubelet                   Pod sandbox changed, it will be killed and re-created.
```

By checking the kubelet's log in the guest cluster VM, we found that it's complaining it cannot find the iptables binary:

```
# In /var/lib/rancher/rke2/agent/logs/kubelet.log
E0905 07:20:29.412791    2253 remote_runtime.go:222] "StopPodSandbox from runtime service failed" err="rpc error: code = Unknown desc = failed to destroy network for sandbox \"dc807d9f1b6c972b30bfd2e3c4bcb71de8260737f5ddb5fc4f33c705718b017b\": plugin type=\"portmap\" failed (delete): neither iptables nor ip6tables usable" podSandboxID="dc807d9f1b6c972b30bfd2e3c4bcb71de8260737f5ddb5fc4f33c705718b017b"
E0905 07:20:29.412838    2253 kuberuntime_manager.go:1390] "Failed to stop sandbox" podSandboxID={"Type":"containerd","ID":"dc807d9f1b6c972b30bfd2e3c4bcb71de8260737f5ddb5fc4f33c705718b017b"}
E0905 07:20:29.412875    2253 kuberuntime_manager.go:1090] "killPodWithSyncResult failed" err="failed to \"KillPodSandbox\" for \"af090669-322f-43ff-9b11-445f2e3b139a\" with KillPodSandboxError: \"rpc error: code = Unknown desc = failed to destroy network for sandbox \\\"dc807d9f1b6c972b30bfd2e3c4bcb71de8260737f5ddb5fc4f33c705718b017b\\\": plugin type=\\\"portmap\\\" failed (delete): neither iptables nor ip6tables usable\""
E0905 07:20:29.412908    2253 pod_workers.go:1300] "Error syncing pod, skipping" err="failed to \"KillPodSandbox\" for \"af090669-322f-43ff-9b11-445f2e3b139a\" with KillPodSandboxError: \"rpc error: code = Unknown desc = failed to destroy network for sandbox \\\"dc807d9f1b6c972b30bfd2e3c4bcb71de8260737f5ddb5fc4f33c705718b017b\\\": plugin type=\\\"portmap\\\" failed (delete): neither iptables nor ip6tables usable\"" pod="kube-system/rke2-ingress-nginx-controller-wqmnq" podUID="af090669-322f-43ff-9b11-445f2e3b139a"
```

After installing the iptables package, the ingress-nginx-controller pod transitioned to the Running state.

```
sudo zypper in -t package iptables
```

---

This one is a bit like #6418 but doesn't require a reboot. So, perhaps it could be done via cloud-init.

**Comment by w13915984028** [comment]
The document mentioned the requirement of `iptables or xtables-nft`. Someone from Slack also encountered similar issue.

https://docs.harvesterhci.io/v1.3/rancher/node/rke2-cluster#create-rke2-kubernetes-cluster

![image](https://github.com/user-attachments/assets/2f3f4fce-a971-49e4-beac-64592249b991)

**Comment by starbops** [comment]
Great! Then, we have that somewhat covered in the documentation. But that's for the node driver, which says iptables is required by Calico and Canal. In Albin's environment, all the Calico pods are running fine.

@w13915984028 do you have any insight into the difference?

**Comment by w13915984028** [comment]
@starbops 
maybe on new RKE2 calic/canal does not rely on `iptables` and the document is not updated :), we need to check more and update the document.

**Comment by albinsun** [comment]
Thank you @irishgordo, @starbops and @w13915984028.
Per discussed, have more testing and note current result:

In short, we have 2 independent problems:
1. Workload `nginx-ingress-controller` stuck `InProgress` (This ticket)
   * Steps to resolve
     1. Add `iptables` in cloud-config's packages section
3. Load balancer stuck Pending ([#6418](https://github.com/harvester/harvester/issues/6418))
   * Steps to resolve
     1. Add `kernel-default` in cloud-config's packages section
        Ref. https://docs.harvesterhci.io/v1.4/rancher/cloud-provider/#prerequisites
     2. **Reboot** VM

### Steps to Resolve
To cover both issues, one need to
1. Include `kernel-default` and `iptables` in cloud-config packages, e.g.:
    ```
    #cloud-config
    package_update: true
    packages:
      - qemu-guest-agent
      - kernel-default
      - iptables
    ...
    ```
2. **Reboot** VM to let `macvlan` kernel module take effect. 

### Screenshot
1. nginx-ingress
   ![image](https://github.com/user-attachments/assets/844ffa67-8296-4eb4-8609-1aabedee6d02)
2. load balancer
   ![image](https://github.com/user-attachments/assets/b17ea114-3e87-4c3a-944c-fdc8e1c54ae3)
