### ISSUE TITLE
[BUG] A volume with an identical name in another namespace is also considered attached in GUI

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6528]
**Describe the bug**

A volume with an identical name in another namespace is also considered attached in GUI.

**To Reproduce**
1. Create a volume `default/abc`.
2. Create a volume `ci/abc`.
3. Create a VM `ci/test`.
4. Attach the volume `ci/abc` to the VM.
5. Visit the **Volumes** page, the volume in the `default/abc` is also attached to the VM `ci/test`.

<img width="956" alt="截圖 2024-09-09 下午2 44 41" src="https://github.com/user-attachments/assets/6a82d897-6ac1-475b-bccb-ca73dec6a793">

<img width="955" alt="截圖 2024-09-09 下午2 44 50" src="https://github.com/user-attachments/assets/7ee86cd5-b26c-4c6d-b6b3-b9ca52f9c1dc">

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version: `master-3bba1d6-head`(3bba1d6dcc17589fe9607aff38bea7614065b8be)
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

The consequence is the volume in another namespace can't be attached to VM from GUI. I looks like a frontend issue, the backend doesn't show the volume is attached.

**Comment by albinsun** [comment]
Test OK on `harvester-v1.3.2`.

## Environment
* `harvester-v1.3.2`
  * Profile: Single node QEMU/KVM (8C/16G/500G per node)
  * ui-source: `Auto`


## Steps 
1. <details>
   <summary> :green_circle: Create namespace <code>myns</code>.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5a16e30c-6208-4648-8892-5a2686e2bcd1)
   </details>

1. <details>
   <summary> :green_circle: Create volume <code>default/myvol</code> and <code>myns/myvol</code>.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3fe88926-ab41-4608-aa4b-cd357ccd0500)
   </details>

1. <details>
   <summary> :green_circle: Create a VM <code>myns/test</code> and attach <code>myns/myvol</code>.
   </summary>
   
   * VM
     ![image](https://github.com/user-attachments/assets/4c26e0f9-a651-4b44-bf99-c9636163ef7e)
   </details>

1. <details open>
   <summary> :green_circle: <code>default/myvol</code> should NOT attach to the VM <code>myns/test</code>.
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b62a585a-11bd-4c7c-903e-22137b6ed575)
   </details>

**Comment by bk201** [comment]
@torchiaf @a110605 Please help check, it might be related to how we get the relationship between VM in volumes in master/v1.4.

**Comment by a110605** [comment]
> @torchiaf @a110605 Please help check, it might be related to how we get the relationship between VM in volumes in master/v1.4.

This issue was caused by PR https://github.com/harvester/dashboard/pull/1065 which is not backport to v1.3.

Since VM can only attach to the same namespace volume (correct me if it's wrong), we can add namespace check when finding attachVM.

cc @torchiaf

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-f5fc452-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Follow step to reproduce in https://github.com/harvester/harvester/issues/6528#issue-2513059440
