### ISSUE TITLE
[QUESTION] - Upgrade from 1.2.2

### ISSUE THREAD

**Issue by RegisWeduLabs** [harvester/harvester#6529]
Hi,

I wanted to take a chance, and even tough in the upgrade guides, it only lists upgrading from 1.3.1 -> 1.3.2, I wanted to know if it was possible to upgrade from 1.2.2 to 1.3.2...

I was waiting for 1.3.2 before doing my upgrades (1.2.1 currently).  I didn't want to have 3 upgrades in a row (1.2.1->1.2.2->1.3.1->1.3.2) and instead upgrade 1.2.1->1.2.2->1.3.2.  Is this possible or we have to upgrade to 1.3.1 before being able to go 1.3.2?

Thanks!

**Comment by bk201** [comment]
The upgrade path 1.2.2 -> 1.3.1 -> 1.3.2 is tested by our QA. The upgrade path is mandatory because Kubernetes's minor versions are bumped in these versions.

**Comment by RegisWeduLabs** [comment]
Okay Thank you!
