### ISSUE TITLE
[BUG] In the network configuration page, when moving up, the input is not saved

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#654]
**Describe the bug**

**To Reproduce**
1. install harvester by ISO
2. choose static ip mode
3. input dnsservers
4. move up
5. move down（then dnsservers change to empty）

**Expected behavior**

the input will be saved

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc3

steps:
1. install harvester by ISO
2. choose static ip mode
3. input dnsservers
4. move up
5. move down

Result：
the input will be saved
