### ISSUE TITLE
[BUG] VM Creation Default Disk Size Changes

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6540]
**Describe the bug**
In ` v1.4.0-dev-20240830 ` - noticing that when creating a VM like in the video below, the VM Disk size for SL Micro 6 QCOW GM -> ends up being 32GB ...instead of what is the default 10.

V1.4-dev example video:

https://github.com/user-attachments/assets/19e25645-3c2c-4d1a-a1e8-027bd110094b

In contrast, here's the video with v1.3.1:

https://github.com/user-attachments/assets/5e791398-4ccf-453c-94a0-e3ab7486ad21

**To Reproduce**
1. Upload SLE Micro QCOW GM Image
1. Begin to create a VM, select that image as the first disk, disk is now 32GB whereas with v1.3.1, disk stays at 10G

**Expected behavior**
Disk size to be staying default 10GB, just based on historic frequency of VM Creation.

**Environment**
 - Harvester ISO version: v1.4.0-dev-20240830 
 - Underlying Infrastructure: qemu/kvm

**Workaround**
- just modify disk size manually

**Comment by tserong** [comment]
This is an enhancement - see https://github.com/harvester/harvester/issues/4905 for details. TL;DR: if we default to 10GB but the underlying image virtual size is actually bigger, the VM ends up with a corrupt disk. I got some information about this into the docs the other week (https://github.com/harvester/docs/pull/631)

**Comment by irishgordo** [comment]
@tserong - thanks for that mention :smile: :+1:  - I'll go ahead and close this out then :smile:
