### ISSUE TITLE
[BUG] GUI for VM "disk image" fields shows "backing image" name

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#6557]
**To Reproduce**
- create VM, using cloud image. I used Ubuntu 22 and vm name "ub3090"
- in Harvester GUI, go to VIRTUAL MACHINES -> click on VM -> Volumes

**Expected behavior**
I expect to see volume name

**Actual behavior**
I see cloud image name:

**Environment**
 - Harvester ISO version: 1.3.2
![Screenshot 2024-09-12 at 20 20 51](https://github.com/user-attachments/assets/381e8d63-9cac-426d-aadf-250bfdcfda04)

**Note*
I can see correct volume name in the VOLUMES section of GUI:
![Screenshot 2024-09-12 at 20 18 14](https://github.com/user-attachments/assets/becfcc22-4bad-4725-9c2f-bd9c928d20ce)

**Comment by brandboat** [comment]
Hi, @SlavikCA , this is not a bug, the `image` in Volumes page indicate to the name of VM image, not volume name.
