### ISSUE TITLE
[ENHANCEMENT] Show QCOW virtual size in the UI 

### ISSUE THREAD

**Issue by dfaltum** [harvester/harvester#6560]
**Is your enhancement related to a problem? Please describe.**
When creating a VM from a QCOW file, you can choose the root file system's size. If you choose less than the virtual size of the QCOW image you will be stuck in an initramfs rescue shell like this:

![image](https://github.com/user-attachments/assets/a1b7c5ca-e316-4aae-9a2d-1d7ddb1d22ec)

**Describe the solution you'd like**
It would be nice if the UI could show the virtual size of the QCOW image.

**Additional context**
There is a note in the [documentation](https://docs.harvesterhci.io/v1.3/vm/index#volumes) which is great, but it would be nice if the UI could warn about this kind of situation.

**Comment by brandboat** [comment]
Thank you for reporting this issue, @dfaltum. It appears to be a duplicate of https://github.com/harvester/harvester/issues/4905, which has already been resolved in the v1.4 branch.

**Comment by dfaltum** [comment]
Hi @brandboat,
Oh that's cool, thank you for the information!
