### ISSUE TITLE
Cannot Upgrade Harvester Cluster From 1.3.1 -> 1.3.2

### ISSUE THREAD

**Issue by jmcglock** [harvester/harvester#6561]
When attempting to upgrade my Harvester cluster from 1.3.1 to 1.3.2 I get the following error:
`admission webhook "validator.harvesterhci.io" denied the request: managed chart harvester is not ready, please wait for it to be ready`

My cluster has 1 witness node and 2 other nodes.

I did some digging and realized this might be helpful at pointing to the issue:

```
harvester-elliot:~ # kubectl get nodes
NAME                  STATUS   ROLES                       AGE   VERSION
harvester-darlene     Ready    control-plane,etcd,master   83d   v1.27.13+rke2r1
harvester-elliot      Ready    etcd                        83d   v1.27.13+rke2r1
harvester-whiterose   Ready    control-plane,etcd,master   83d   v1.27.13+rke2r1
harvester-elliot:~ # kubectl get bundles.fleet.cattle.io -A
NAMESPACE     NAME                                          BUNDLEDEPLOYMENTS-READY   STATUS
fleet-local   fleet-agent-local                             1/1                       
fleet-local   local-managed-system-agent                    1/1                       
fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; configmap.v1 longhorn-system/longhorn-default-setting modified {"data":{"default-setting.yaml":"default-data-path: /var/lib/harvester/defaultdisk\ntaint-toleration: kubevirt.io/drain:NoSchedule\npriority-class: system-cluster-critical\nconcurrent-automatic-engine-upgrade-per-node-limit: 3"}}
fleet-local   mcc-harvester-crd                             1/1                       
fleet-local   mcc-local-managed-system-upgrade-controller   1/1                       
fleet-local   mcc-rancher-logging-crd                       1/1                       
fleet-local   mcc-rancher-monitoring-crd                    1/1
```

**Environment**
CPUs:

- Intel(R) Xeon(R) CPU E5-2680 v2 @ 2.80GHz
- Intel(R) Xeon(R) CPU E5-2650 v2 @ 2.60GHz
- Intel(R) Core(TM) i5-9500T CPU @ 2.20GHz (witness node)

**Comment by adonskoy** [comment]
Faced a similar problem when upgrading to 1.3.2. The problem is in the hvst-upgrade job, which tries to check the status of longhorn instance-manager on the witness-node, on which there is no longhorn. 

After deleting witness-node, the upgrade started. But I have 4 nodes + witness node, in your case after deleting witness node you may encounter another problem described [here](https://docs.harvesterhci.io/v1.3/upgrade/v1-3-1-to-v1-3-2#1-two-node-cluster-upgrade-stuck-after-the-first-node-is-pre-drained)

Logs of upgrade job:
```
Waiting for longhorn-manager to be upgraded...
Checking instance-manager (aio) pod on node harvester1...
Checking instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) on node harvester1 OK.
Checking instance-manager (aio) pod on node harvester2...
Checking instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) on node harvester2 OK.
Checking instance-manager (aio) pod on node harvester3...
Checking instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) on node harvester3 OK.
Checking instance-manager (aio) pod on node witness-node...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...
instance-manager (aio) (image=longhornio/longhorn-instance-manager:v1.6.2) count is not 1 on node witness-node, will retry...

```

**Comment by arminzaugg** [comment]
I have a somewhat similar problem. I am running a one node cluster. For performance reasons I created a new default storageclass and tuned down longhorn resources. I guess I deleted the original default storage class. Now I dont know how to recover from this.

`Modified(1) [Cluster fleet-local/local]; deployment.apps longhorn-system/longhorn-ui modified {"spec":{"replicas":2}}; storageclass.storage.k8s.io harvester-longhorn missing`

**Comment by ibrokethecloud** [comment]
@jmcglock did you happy to change any longhorn settings manually?

**Comment by ibrokethecloud** [comment]
@arminzaugg you can reapply the storage class again https://github.com/harvester/harvester/blob/master/deploy/charts/harvester/templates/harvester-storageclass.yaml

or even via Harvester UI: https://docs.harvesterhci.io/v1.3/advanced/storageclass

**Comment by Yu-Jack** [comment]
Regarding `Modified(1) [Cluster fleet-local/local]; deployment.apps longhorn-system/longhorn-ui modified {"spec":{"replicas":2}}; storageclass.storage.k8s.io harvester-longhorn missing`, please follow below steps to fix that:

1. Run `helm get manifest harvester -n harvester-system | grep "name: harvester-longhorn" -A 10 -B 10`. You'll get the default harvester-longhorn storage class like this (**Please do not apply this yaml directly, it's just an example.**):
  ```yaml
  allowVolumeExpansion: true
  apiVersion: storage.k8s.io/v1
  kind: StorageClass
  metadata:
    annotations:
      objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system # important annotation for fleet
      storageclass.kubernetes.io/is-default-class: "true"
    labels:
      objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3 # important label for fleet
    name: harvester-longhorn
  parameters:
    baseImage: ""
    fromBackup: ""
    migratable: "true"
    numberOfReplicas: "3"
    staleReplicaTimeout: "30"
  provisioner: driver.longhorn.io
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  ```
2. Apply the result from step 1.

The reason is that fleet would check id in annotations and hash in labels. Please see https://github.com/rancher/fleet/issues/910#issuecomment-1215042215 for more details.

**Comment by arminzaugg** [comment]
@ibrokethecloud 
Yes, I changed them a tried out different things. Afterall I ended up creating a new default class and removed the original default. I knew how to create new storages classes from UI but this did not solved my issue.

@Yu-Jack 
Thank you I was able to recreated a harvester-longhorn storage class using the output my cluster specific manifest.

Unfortunately I still cannot upgrade. I still get 
```fleet-local   mcc-harvester                                 0/1                       Modified(1) [Cluster fleet-local/local]; deployment.apps longhorn-system/longhorn-ui modified {"spec":{"replicas":2}}```

And update UI says
```admission webhook "validator.harvesterhci.io" denied the request: managed chart harvester is not ready, please wait for it to be ready```

Apparently the managedchart harvester seems to be missing on my system. I have no idea why.
```
kubectl get managedchart harvester -n cattle-system

Alias tip: k get managedchart harvester -n cattle-system
Error from server (NotFound): managedcharts.management.cattle.io "harvester" not found
```

My Storage Class should be ok now
```
❯ k get storageclasses.storage.k8s.io harvester-longhorn -o yaml
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"objectset.rio.cattle.io/id":"default-mcc-harvester-cattle-fleet-local-system","storageclass.kubernetes.io/is-default-class":"false"},"labels":{"objectset.rio.cattle.io/hash":"e852fa897f5eae59a44b4bfe186aad80b10b94b3"},"name":"harvester-longhorn"},"parameters":{"baseImage":"","fromBackup":"","migratable":"true","numberOfReplicas":"3","staleReplicaTimeout":"30"},"provisioner":"driver.longhorn.io","reclaimPolicy":"Delete","volumeBindingMode":"Immediate"}
    objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubernetes.io/is-default-class: "true"
  creationTimestamp: "2024-09-16T10:56:16Z"
  labels:
    objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3
  name: harvester-longhorn
  resourceVersion: "82627985"
  uid: 92da25ba-6b04-4be6-89a7-3673917baf20
parameters:
  baseImage: ""
  fromBackup: ""
  migratable: "true"
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate
```

**Comment by arminzaugg** [comment]
I was able to resolve the issue by reverting my change to the replica count of the blocking ressource.
Running ```k -n fleet-local describe managedcharts.management.cattle.io harvester```, will tell you if something is not as expected.

With that I was able to complete the update.

**Comment by jmcglock** [comment]
```
>>> Check all bundles ready...
All Helm bundles are ready.
>>> Check the Harvester bundle is ready...
2,12c2
< modified: 1
< nonReadyResources:
<   - bundleState: Modified
<     modifiedStatus:
<       - apiVersion: v1
<         kind: ConfigMap
<         name: longhorn-default-setting
<         namespace: longhorn-system
<         patch: '{"data":{"default-setting.yaml":"default-data-path: /var/lib/harvester/defaultdisk\ntaint-toleration: kubevirt.io/drain:NoSchedule\npriority-class: system-cluster-critical\nconcurrent-automatic-engine-upgrade-per-node-limit: 3"}}'
<     name: fleet-local/local
< ready: 0
```

**Comment by ibrokethecloud** [comment]
did you happen to change any longhorn settings?

**Comment by jmcglock** [comment]
Hey @ibrokethecloud 
Yes. I changed some settings. I am trying to revert them to the original to see if that works.

**Comment by web-engineer** [comment]
> Regarding `Modified(1) [Cluster fleet-local/local]; deployment.apps longhorn-system/longhorn-ui modified {"spec":{"replicas":2}}; storageclass.storage.k8s.io harvester-longhorn missing`, please follow below steps to fix that:
> 
> 1. Run `helm get manifest harvester -n harvester-system | grep "name: harvester-longhorn" -A 10 -B 10`. You'll get the default harvester-longhorn storage class like this (**Please do not apply this yaml directly, it's just an example.**):
> 
> ```yaml
> allowVolumeExpansion: true
> apiVersion: storage.k8s.io/v1
> kind: StorageClass
> metadata:
>   annotations:
>     objectset.rio.cattle.io/id: default-mcc-harvester-cattle-fleet-local-system # important annotation for fleet
>     storageclass.kubernetes.io/is-default-class: "true"
>   labels:
>     objectset.rio.cattle.io/hash: e852fa897f5eae59a44b4bfe186aad80b10b94b3 # important label for fleet
>   name: harvester-longhorn
> parameters:
>   baseImage: ""
>   fromBackup: ""
>   migratable: "true"
>   numberOfReplicas: "3"
>   staleReplicaTimeout: "30"
> provisioner: driver.longhorn.io
> reclaimPolicy: Delete
> volumeBindingMode: Immediate
> ```
> 
> 2. Apply the result from step 1.
> 
> The reason is that fleet would check id in annotations and hash in labels. Please see [rancher/fleet#910 (comment)](https://github.com/rancher/fleet/issues/910#issuecomment-1215042215) for more details.

This worked for me - I had manually re-created the storage class and that didn't work - removing my created class and un-checking the default then applying the default template fixed it for me too.

**Comment by jmcglock** [comment]
I was able to revert the Longhorn settings that I had changed.
