### ISSUE TITLE
[ENHANCEMENT] Bump base image to BCI 15.6

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6568]
**Is your enhancement related to a problem? Please describe.**
We should bump the base image to 15.6 for each component because of the EoL date.
IIUC, the 15.5 EoL might be the end of 2024. cc @bk201 

**Describe the solution you'd like**
Update `registry.suse.com/bci/bci-base:15.5` to `registry.suse.com/bci/bci-base:15.6`

Please help bump the base images of these images for v1.4.0 (You can check the previous bump at https://github.com/harvester/harvester/issues/4757)

**Here is the general flow**:
- Bump the base image in the project's docker file.
- Backport the change to a stable branch if needed.
- For Harvester dependencies:
   - Do a tag to release a new image.
   - Add a note we should update the [values file](https://github.com/harvester/harvester/blob/v1.4/deploy/charts/harvester/values.yaml) in the [comment](https://github.com/harvester/harvester/issues/6568#issuecomment-2358040237). @brandboat will create a PR to include all new image tags.
- For Harvester Add-ons:
   - Build-in addons
       - Update image tags https://github.com/harvester/addons/blob/main/version_info and backport to v1.4 branch.
   - Experimental add-ons: Update image tag in charts or https://github.com/harvester/experimental-addons

|   | Image                                             | Owner | Comment |
|---|---------------------------------------------------|-------|---------|
|   | docker.io/rancher/harvester-eventrouter           |  @w13915984028       | tag: v0.3.2  PRs: installer https://github.com/harvester/harvester-installer/pull/839, addons https://github.com/harvester/addons/pull/21       |
|   | docker.io/rancher/harvester-load-balancer-webhook |  @starbops      | tag: [v0.4.2](https://github.com/harvester/load-balancer-harvester/releases/tag/v0.4.2) PR: https://github.com/harvester/load-balancer-harvester/pull/34 |
|   | docker.io/rancher/harvester-load-balancer         |  @starbops      | tag: [v0.4.2](https://github.com/harvester/load-balancer-harvester/releases/tag/v0.4.2) PR: https://github.com/harvester/load-balancer-harvester/pull/34 |
|   | docker.io/rancher/harvester-network-controller    |   @mingshuoqiu     | tag: v0.5.2 PR: https://github.com/harvester/network-controller-harvester/pull/118        |
|   | docker.io/rancher/harvester-network-helper        |     @mingshuoqiu   | tag: v0.5.2 PR: https://github.com/harvester/network-controller-harvester/pull/118        |
|   | docker.io/rancher/harvester-network-webhook       |    @mingshuoqiu    | tag: v0.5.2 PR: https://github.com/harvester/network-controller-harvester/pull/118        |
|   | docker.io/rancher/harvester-node-disk-manager     |     @Vicente-Cheng   |  tag: [v0.7.4](https://github.com/harvester/node-disk-manager/releases/tag/v0.7.3) PR: https://github.com/harvester/node-disk-manager/pull/135       |
|   | docker.io/rancher/harvester-node-manager          |  @brandboat      | tag:[v0.3.3](https://github.com/harvester/node-manager/releases/tag/v0.3.3) PR: https://github.com/harvester/node-manager/pull/61        |
|   | docker.io/rancher/harvester-pcidevices            |   @ibrokethecloud     |    PR: https://github.com/harvester/pcidevices/pull/92     |
|   | docker.io/rancher/harvester-seeder                |    @starbops    | tag: [v0.4.1](https://github.com/harvester/seeder/releases/tag/v0.4.1) PR: https://github.com/harvester/seeder/pull/40 |
|   | docker.io/rancher/harvester-upgrade               |   @FrankYang0529     | https://github.com/harvester/harvester/pull/6585 |
|   | docker.io/rancher/harvester-webhook               |   @FrankYang0529     | https://github.com/harvester/harvester/pull/6585 |
|   | docker.io/rancher/harvester                       | @FrankYang0529       | https://github.com/harvester/harvester/pull/6585 |
|   | docker.io/rancher/harvester-vm-import-controller  |  @starbops     | tag: [v0.4.1](https://github.com/harvester/vm-import-controller/releases/tag/v0.4.1) PR: https://github.com/harvester/vm-import-controller/pull/44 |
|     | docker.io/rancher/support-bundle-kit              |   @Yu-Jack     |  Tag [`v0.0.44`](https://github.com/rancher/support-bundle-kit/releases/tag/v0.0.44) PR https://github.com/rancher/support-bundle-kit/pull/120  |
|   | docker.io/rancher/harvester-cluster-repo          |   @tserong     | PR https://github.com/harvester/harvester-installer/pull/841        |
|   | registry.suse.com/bci/bci-base:15.4               |   @FrankYang0529     |     generalJob image, https://github.com/harvester/harvester/pull/6585    |
|   | docker.io/rancher/harvester-networkfs-manager     |     @Vicente-Cheng   |  tag: [v0.1.1](https://github.com/harvester/networkfs-manager/releases/tag/v0.1.1) PR: https://github.com/harvester/networkfs-manager/pull/5      |
|   | docker.io/rancher/harvester-lvm-csi-plugin     |     @Vicente-Cheng   |  tag: [v0.1.2](https://github.com/harvester/csi-driver-lvm/releases/tag/v0.1.1) PR: https://github.com/harvester/csi-driver-lvm/pull/5       |
|   | docker.io/rancher/harvester-lvm-provisioner     |     @Vicente-Cheng   |  tag:[v0.1.2](https://github.com/harvester/csi-driver-lvm/releases/tag/v0.1.1) PR: https://github.com/harvester/csi-driver-lvm/pull/5          |
|   | docker.io/rancher/harvester-csi-driver     |     @Vicente-Cheng   | tag: [v0.2.0](https://github.com/harvester/harvester-csi-driver/releases/tag/v0.2.0) PR: https://github.com/harvester/harvester-csi-driver/pull/44        |
|   | docker.io/rancher/cloud-provider-harvester   |     @starbops   | tag: [v0.2.3](https://github.com/harvester/cloud-provider-harvester/releases/tag/v0.2.3) PR: https://github.com/harvester/cloud-provider-harvester/pull/48 |

**Describe alternatives you've considered**
None

**Additional context**
None

**Comment by bk201** [comment]
@brandboat will help submit a single PR to update all image tags in the [values file](https://github.com/harvester/harvester/blob/v1.4/deploy/charts/harvester/values.yaml), please edit this comment to include the image tag.
- rancher/support-bundle-kit:v0.0.44
- rancher/harvester-node-manager:v0.3.3

**Comment by bk201** [comment]
Considering 1.5.5 is EOL in the end of the year, we should also backport the change back to the v1.3 branch. Sorry for the additional effort.

**Comment by bk201** [comment]
gentle ping to everyone, please update your image and tag in the [comment](https://github.com/harvester/harvester/issues/6568#issuecomment-2358040237) if a new image is published and the tag needs to bump in the values.yaml file. Then we can bump all the images with a PR. Thanks.

**Comment by bk201** [comment]
Base images are bumped in the code level.
