### ISSUE TITLE
[BUG] RBAC cluster owner can't set project membership

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6575]
**Describe the bug**

When logged into Rancher as a Harvester cluster owner you can't set the project membership on a project in a downstream Harvester cluster

**To Reproduce**
1. Import Harvester into Rancher
2. Create a user and set it as a cluster owner in Harvester via RBAC
3. Log into Rancher as the cluster owner
4. Edit the config on one of the projects
5. Check for the members tab on the sidebar

**Expected behavior**

You should be able to set project membership while logged in as a cluster owner

**Support bundle**

[supportbundle_95151210-c1e6-4774-803e-2663034237e4_2024-09-17T17-54-53Z.zip](https://github.com/user-attachments/files/17033004/supportbundle_95151210-c1e6-4774-803e-2663034237e4_2024-09-17T17-54-53Z.zip)

**Environment**
 - Harvester ISO version: v1.3.1
 - Rancher version: v2.9.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Harvester: 3 node vagrant-libvirt, Rancher: 1 node docker instance

**Additional context**

This might be a UI bug that the section doesn't show up. You can't really tell from the page. There were some warnings about routing though in the UI. It does show up if you are logged in as the admin though.

![Screenshot_20240917_105054](https://github.com/user-attachments/assets/d82915c1-9294-4e8c-8285-332ad164b2d8)
![Screenshot_20240917_105050](https://github.com/user-attachments/assets/013c1ec5-1305-4631-a7c8-5c9aa409ec5b)
![Screenshot_20240917_105043](https://github.com/user-attachments/assets/91edb68b-7dc8-4cb8-82bb-210f6857f912)
![Screenshot_20240917_103946](https://github.com/user-attachments/assets/f47a9e5b-4661-445c-8b9e-09d50b49e876)
![Screenshot_20240917_103907](https://github.com/user-attachments/assets/6dcb4038-b2d0-4de1-90bf-2627d7e51fe9)

![Screenshot_20240917_105543](https://github.com/user-attachments/assets/59505969-a27d-42eb-b1d0-4fcb25fa87d8)
![Screenshot_20240917_105536](https://github.com/user-attachments/assets/dd5dcc8a-df70-486b-90f1-2b31c31fd2c1)

**Comment by a110605** [comment]
@noahgildersleeve , is this issue only happen on Rancher 2.9 ? Is it okay on Rancher 2.8?

**Comment by noahgildersleeve** [comment]
I'm not sure @a110605 . I'll check.

**Comment by noahgildersleeve** [comment]
I took a look and it is happening in v2.8.5 as well. I think it might be related to the fact that Harvester doesn't have a concept of projects, just namespaces. So if a user is set as a cluster owner they would have access to all of the Harvester cluster resources, but a project doesn't seem to be a part of that.

An admin is a cluster owner, but it's also an admin on Rancher and has access to all of the Rancher resources as well. The owner accounts I was creating were login only accounts from a Rancher permissions perspective. If you go into namespaces in Harvester you don't see them at all. 

![Screenshot_20240917_175307](https://github.com/user-attachments/assets/cefa3207-4f47-4799-87b6-5b9cff050079)
