### ISSUE TITLE
[BUG] Long time to for instances to be removed after deleting VMs; can't create new instance with same name

### ISSUE THREAD

**Issue by philipwilk** [harvester/harvester#658]
**Describe the bug**
If I delete a VM from the harvester UI it disappears from the list of VMs but the pods still exists. This makes sense if it's shutting down before deleting itself, but it means that if I try to create another VM with the same name, I get an error that an instance with this name already exists under its events, and it gets the state **VM error** under harvester, even though the old vm isn't visible in harvester. 
This wouldn't be much of a problem if it meant the VM you deployed was shortly in VM error state, but it's currently impossible for the end user to know how long it may take for the old instance to be removed, as it may be moments, or still in progress over an hour later when you try to deploy again.
![image](https://user-images.githubusercontent.com/50517631/113933074-0eb8cc00-97ec-11eb-9b39-51bda7cca443.png)
![image](https://user-images.githubusercontent.com/50517631/113933221-34de6c00-97ec-11eb-8d61-4e5dff3e0c51.png)

**To Reproduce**
1. Delete an instance. This issue is much more profound if you try to deploy multiple instances. 
2. Shortly after, create another instance with the same name.
3. Get VM error from harvester ui, while rancher ui shows the instance is being removed.

**Expected behavior**
Once I've deleted the old instances, I should either see that they're being removed and be unable to create another instance because of this, or be able to create the instance as the previous one should be gone.

**Environment:**
 - Harvester ISO version: Build from source on 06/04/2021
 - Installation Mode: ISO
 - Underlying Infrastructure: Baremetal HP DL380P G8 16c/32t/48GB

**Additional context**
Probably related bug; the instances are removing forever, but are also being created simultaneously.
![image](https://user-images.githubusercontent.com/50517631/113934370-93f0b080-97ed-11eb-99e9-e7c0db468b0d.png)

**Comment by guangbochen** [comment]
when the VM is removed its backend is still waiting for the VM pod to be deleted, therefore we should add the VM sub-resources status check in the UI to avoid ambiguity.

**Comment by gitlawr** [comment]
We need to use [forground cascading deletion policy](https://kubernetes.io/docs/concepts/workloads/controllers/garbage-collection/#foreground-cascading-deletion) to delete VM objects.

**Comment by gitlawr** [comment]
@WuJun2016 Set the propagationPolicy param when calling the vm deletion API.
e.g.:
```
https://IP:30443/v1/kubevirt.io.virtualmachines/default/aa?propagationPolicy=Foreground
```

**Comment by kingsd041** [comment]
Validate version master-0008ce84-head

Steps:
1. Delete vm
2. When the vm disappears from the UI, immediately create a vm with the same name

Results：
The vm with the same name can be successfully created
