### ISSUE TITLE
[TASK] Bump RKE2 to v1.29.8+rke2r1 and Rancher to v2.9.2

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6584]
**Is your enhancement related to a problem? Please describe.**

Bump RKE2 to v1.29.8+rke2r1 and Rancher to v2.9.2.

**Describe the solution you'd like**

Bump RKE2 to v1.29.8+rke2r1 and Rancher to v2.9.2

**Describe alternatives you've considered**

**Additional context**

**Comment by bk201** [comment]
Update to v1.29.9+rke2r1 because it's released.

**Comment by khushboo-rancher** [comment]
Validated with 1.4.0-rc1, 1 node setup 

Validation - Pass

The RKE2 Version is updated to `v1.29.9+rke2r1`. Not sure how to validate the Rancher version as the Rancher version appears as `unknown (Harvester-v1.4.0-rc1)`

<img width="833" alt="Screenshot 2024-10-03 at 2 57 58 PM" src="https://github.com/user-attachments/assets/8963ee4d-8957-4998-a415-caa613cebe6d">
<img width="980" alt="Screenshot 2024-10-03 at 2 59 12 PM" src="https://github.com/user-attachments/assets/2e93cb22-6db2-4c01-aa32-f1abef004b09">
