### ISSUE TITLE
[FEATURE] vmi needs to be displayed in the vm list

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#659]
**Is your feature request related to a problem? Please describe.**
If vm is deleted, but vmi still exists, then vmi needs to be displayed in the vm list

1.  vm and vmi exist at the same time, showing vm
2.  vm does not exist, vmi exists, display vmi

**Comment by TangStone** [comment]
### Validate version master-95a5828a-head

1. Create a vm, check the status of vm and vmi at this time
![image](https://user-images.githubusercontent.com/15829074/115180163-88638a80-a107-11eb-9384-0aa081a250b6.png)
**vm and vmi exist at the same time, showing vm**
![image](https://user-images.githubusercontent.com/15829074/115180151-81d51300-a107-11eb-9281-c24faed6bf17.png)
2. First "kubectl edit vmi vm2, add a "test" to the finalizers field, then "kubectl delete vm vm2"
![image](https://user-images.githubusercontent.com/15829074/115180544-64547900-a108-11eb-9729-03cab94f01c2.png)
**vm does not exist, vmi exists, display vmi**
![image](https://user-images.githubusercontent.com/15829074/115180556-6cacb400-a108-11eb-97e1-6bd5f1ba3a9f.png)
