### ISSUE TITLE
[BUG] There is no target nodes for VM migration

### ISSUE THREAD

**Issue by lanfon72** [harvester/harvester#6591]
### Describe the bug
Simple VM created but migrate target options is empty.

https://github.com/user-attachments/assets/856f3f1a-a467-4f2f-a230-b3c1ee3a573b

### To Reproduce
1. Install Harvester with any nodes
2. Create an image for VM creation
3. Create an VM `vm1` with all default value
4. Migrate `vm1` to other nodes in UI

### Expected behavior
There should have options to let VM migrate to other nodes

## Environment:
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): **qemu/KVM 2 nodes + 1 witness** and **Baremetal DL360G9 4 nodes**
 - Harvester ISO version: **v1.4.0-dev-20240918** and **v1.4-00cd4ee-head**
 - **ui-source** Option: **Auto**

### Additional context
It's UI issue, API still work as expected.

**Comment by albinsun** [comment]
Hit on 2 nodes cluster too (2 default, no witness).

**Comment by bk201** [comment]
@torchiaf @a110605 Please help check this one, the issue blocks multiple ready-for-testing issues.

**Comment by w13915984028** [comment]
From my local test, UI seems to filter the returned nodes from backend.
```
POST
:path:
/v1/harvester/kubevirt.io.virtualmachines/default/vm2?action=findMigratableNodes
```
returns:
```
{"nodes":["harv2"]}
```

but UI shows none. I will also take a quick look.

**Comment by w13915984028** [comment]
This line from latest PR

https://github.com/harvester/dashboard/blob/ff89417b5b5821d32f1f865af96a508f67d72782/pkg/harvester/dialog/HarvesterMigrationDialog.vue#L79

```
      return nodes.filter((n) => {
        const isNotSelfNode = !!this.availableNodes.includes(n.id);
        const isNotWitnessNode = n.isEtcd !== 'true'; // do not allow to migrate to self node and witness node
        const matchingCpuManagerConfig = n.isCPUManagerEnabled; // If cpu-pinning is enabled, filter-out non-enabled CPU manager nodes.

        return isNotSelfNode && isNotWitnessNode && matchingCpuManagerConfig; /// last condition matchingCpuManagerConfig, should be !matchingCpuManagerConfig ?
      })
```

looks suspectable.

@a110605 @torchiaf

**Comment by a110605** [comment]
hi @lanfon72 , we have fixed this issue and add an enhancement  in migration dialog to let user know CPU pinning VM can only migrate to node which enable CPU manager.
 See in https://github.com/harvester/dashboard/pull/1168#issuecomment-2372828507

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

Test Information
----
* Environment: **qemu/KVM 2 nodes**
* Harvester Version: **v1.4-97e60e1-head**
* **ui-source** Option: **Auto**

### Verify Steps
1. Follow **Steps to reproduce** in https://github.com/harvester/harvester/issues/6591#issue-2537130971
