### ISSUE TITLE
[QUESTION] Label harvesterhci.io/maintain-mode-strategy can only check via "YAML" but not "Config"

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6603]
We observe this during testing harvester#5888, is it a expected behavior?
(Although [HEP](https://github.com/harvester/harvester/blob/master/enhancements/20240605-enhanced-maintenance-mode.md) only mentions "Edit YAML")

If it's not expected, we should convert this ticket to BUG.

* Edit YAML
  ![image](https://github.com/user-attachments/assets/e0e1d562-c013-4faf-abee-16100356185e)
* Edit Config (Only `vmName`)
  ![image](https://github.com/user-attachments/assets/c330661a-0347-49cc-a598-dc0a4928d765)
* Config (Only `vmName`)
  ![image](https://github.com/user-attachments/assets/dd7f5f7b-25e6-4280-973a-9cd976d32d19)

**Comment by bk201** [comment]
@torchiaf can you check this one and see if we can fix it in 1.4.0? Thanks.

**Comment by torchiaf** [comment]
@albinsun the label `harvesterhci.io/maintain-mode-strategy` is handled in a dedicated field:

![image](https://github.com/user-attachments/assets/4894559e-956b-4498-90ba-1380bb2416d9)

that's why we removed it from 'Instance Labels' tab.

**Comment by albinsun** [comment]
Close as by design.
