### ISSUE TITLE
[BUG] Hint is Missing for Oversized Volume Creation Error

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6607]
**Describe the bug**
The hint for an oversized volume creation error is missing, the hint is from PV annotation `longhorn.io/volume-scheduling-error`

**To Reproduce**
1. Creating an oversize volume
2. On the GUI, there is no obvious hint about oversized volume scheduling error

**Expected behavior**
The GUI will display an `Insufficient storage` hint on the volume page

**Environment**
 - Harvester ISO version: master-head (5ad9d940ea98c1b4c67c1f2d9a0212aa2876a663)
 - LH version: v1.7.1

**Additional context**
- This doesn't happen on Harvester v1.3.0 (LH v1.6.0)
- This depends on the LH issue https://github.com/longhorn/longhorn/issues/9514
- This also impacts the issue #1931, which was fixed before

**Comment by WebberHuang1118** [comment]
Based on LH issue https://github.com/longhorn/longhorn/issues/9514, this ticket will be fixed in LH v1.7.2

**Comment by innobead** [comment]
Let's make sure the correct labels are added.

**Comment by brandboat** [comment]
Test OK, will close the issue.

# Environment
- single node (16C/32G/500GB)
- 1.4.0-rc3

# Test Plan
- Create a volume size > node disk size, we can see `Insufficient storage` error message.
<img width="1677" alt="image" src="https://github.com/user-attachments/assets/5171a4d8-6ee2-47c0-b53f-7202131ec039">

![image](https://github.com/user-attachments/assets/6a1a4994-b1f5-4baa-b050-2555928bde7b)
