### ISSUE TITLE
[BUG] Search result does not match the criterion on the VM page

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#661]
**Describe the bug**
Search result does not match the criterion on the VM page

**To Reproduce**
1. Go to the VM page
2. Search a
3. Then search ar

**Result**
Search a and search ar came out different results
![image](https://user-images.githubusercontent.com/57614736/114002351-5d6b7200-988f-11eb-8090-a61b2f9e79e2.png)
![image](https://user-images.githubusercontent.com/57614736/114002830-cfdc5200-988f-11eb-8716-575dec6fa85b.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by n313893254** [comment]
`a` is search by id, which prefix is a namespace. I guess is 'default'. 

After fixed, It only searches by name, state, CPU, and memory.

**Comment by ldevulder** [comment]
Tested on version `master-902bee60-head`. I was able to filler by VM name, CPU, RAM and state. I was not able to reproduce the previous behavior, namespace is not part of the filtering anymore.

Issue closed.
