### ISSUE TITLE
[QUESTION] Request for AMD GPU Support and Future Plans

### ISSUE THREAD

**Issue by Rj455555** [harvester/harvester#6614]
### Questions: 
1.  Is there any current or planned support for AMD GPUs in Harvester?   
2.  If not yet supported, are there any specific blockers or technical challenges preventing AMD GPU integration?  
3.  Is there a roadmap or timeline for adding AMD GPU support in future releases? 

It would be great to have AMD GPU support for various use cases, including virtual machine GPU passthrough and other GPU-accelerated workloads.   

Looking forward to your response and any guidance you can provide! 

thanks!

**Comment by SlavikCA** [comment]
I'm not from Harvester team,
But as far as I can see - you can do passthrough for any PCI card: AMD or nVidia now. I'm doing it for few nVidia cards.

The only issue I had is I have to manually unbind the card:
https://github.com/harvester/harvester/issues/6228

**Comment by Rj455555** [comment]
Thank you very much for your answer!

When I add AMD PCIE device to my virtual machine, the whole cluster crashes. 

So I thought it was a lack of support for AMD devices?
