### ISSUE TITLE
Pod error will appear when creating vm, which should not appear under normal circumstances

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#662]
**Is your feature request related to a problem? Please describe.**
The vm status may change to pod err, and it will be normal after a while

**expect**
There is no need to display this pod err, unless it is really wrong

**Comment by gitlawr** [comment]
![image](https://user-images.githubusercontent.com/5697937/114013670-5e55d100-989a-11eb-89f9-94d8650e08cf.png)

**Comment by WuJun2016** [comment]
![image](https://user-images.githubusercontent.com/24985926/114138257-f5289900-993f-11eb-9d7f-b01eb593a4d5.png)

**Comment by guangbochen** [comment]
duplicate of https://github.com/rancher/harvester/issues/662
