### ISSUE TITLE
[ENHANCEMENT] Schedule VM Backup Misc Update

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6621]
**Is your enhancement related to a problem? Please describe.**
- Improve webhook message for multiple svmbackup creation for the same vm
- Suspend schedule and delete the LH backup if the volumesnapshot is in an error state but LH backup keeps reconciling

**Comment by w13915984028** [comment]
Test report: **PASS**

(1) Create 2 similar backup for same VM:

got error:
> admission webhook "validator.harvesterhci.io" denied the request: same granularity as schedule svmbackup-vm1-running and offset less than 10m0s

![image](https://github.com/user-attachments/assets/9ea8f8f2-7175-4b3e-9ac2-9d34764bb75b)

(2) Suspend a schedule and create a new one
got error:
> admission webhook "validator.harvesterhci.io" denied the request: VM default/vm1-running already has backup schedule

![image](https://github.com/user-attachments/assets/d8c32cde-799c-42b9-9c5a-069556e19fcc)

![image](https://github.com/user-attachments/assets/6a5da9f1-f20e-42a4-a1c4-48cdc51a3b55)

(3) Create schedule type `snapshot` after an existing schedule type `backup`
got error:
>admission webhook "validator.harvesterhci.io" denied the request: VM default/vm1-running already has backup schedule

![image](https://github.com/user-attachments/assets/6f02f29a-d719-4014-bc4d-eabb71560433)

(4) Change the backup source vm via `Edit Yaml` (not allowed from UI config directly)
got error:
>admission webhook "validator.harvesterhci.io" denied the request: source vm can't be changed

![image](https://github.com/user-attachments/assets/dc430790-63c2-48a3-b6a6-d0d00bf8bfbe)

(5) Disable the backup target to test the status of schedule
(5.1) Create a NFS type schedulebackup
(5.2) Stop the NFS server
(5.3) Wait until the schedule is triggered, then observe:

![image](https://github.com/user-attachments/assets/875b54a0-b26c-4914-889c-f4890d502ad8)

![image](https://github.com/user-attachments/assets/23a776e9-160e-489d-b301-90b6503225df)

the above meets the expectation

(5.4) Start the NFS server
(5.5) Manually delete the error backup
![image](https://github.com/user-attachments/assets/cf6fa09b-2095-40bd-9662-02f1f65f1376)

(5.6) But the schedulebackup still shows below message
![image](https://github.com/user-attachments/assets/704c1505-0856-41b7-805d-a706c574aba0)

5.6 could be handled via https://github.com/harvester/harvester/issues/6876

**Comment by w13915984028** [comment]
The enhancement is done, thanks @WebberHuang1118 .

A minor fix https://github.com/harvester/harvester/issues/6876 could be addressed in next release.
