### ISSUE TITLE
[GUI] [FEATURE] Add provisioned vGpus in VM's devices list

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#6638]
**Is your feature request related to a problem? Please describe.**

We want to improve the vGpu allocation when provisioning Harvester clusters in Rancher. https://github.com/harvester/harvester/issues/5774

With the new mechanism, the vGpu IDs are selected by the backend once a vGpu device is assigned to a provisioned cluster in Rancher, and saved in `harvesterhci.io/deviceAllocationDetails` VM's annotation in Harvester.

cc @ibrokethecloud @bk201 

**Describe the solution you'd like**

The UI should build the vGpu list from both source fields:

- `domain.devices.gpus`
- `harvesterhci.io/deviceAllocationDetails` label

**Describe alternatives you've considered**

**Additional context**

**Comment by noahgildersleeve** [comment]
@torchiaf Could you please update the reproduction steps so that I can be sure I test every scenario before closing this? You mentioned that you changed the way the count in the node driver was determined but I wanted to be sure to update it in every case and make sure the count was correct.

**Comment by bk201** [comment]
cc @torchiaf Please add a test plan.

**Comment by noahgildersleeve** [comment]
Tested with Harvester `v1.4-ce5e24e3-head` with Rancher `v2.9.4` and Rancher `v2.10.0`
. Validated as working. 

# Validation Steps

1. Create at least 4 vGPU devices on Harvester
2. Import Harvester into Rancher
3. Create a 3 node RKE2 cluster with assigned vGPUs
4. Wait for cluster to provision
5. Click edit on each individual VM in Harvester
6. Check vGPU tab and validate that each VM has a different vGPU ID

### Screenshots

#### v2.9.4
![Greenshot 2024-11-25 15 25 44](https://github.com/user-attachments/assets/4ca27580-257e-40ac-a5a2-19fa85a7c245)
![Greenshot 2024-11-25 15 23 12](https://github.com/user-attachments/assets/c1a0d409-5a51-4483-ae30-98ce81b9f8a5)
![Greenshot 2024-11-25 15 23 01](https://github.com/user-attachments/assets/c8e1a67d-6d46-484d-8eef-f80e76a303cf)
![Greenshot 2024-11-25 15 22 48](https://github.com/user-attachments/assets/e1ca9891-d06c-41ac-b9d3-524547017f7b)
![Greenshot 2024-11-25 15 22 40](https://github.com/user-attachments/assets/0e25b1ac-2265-4613-8e01-2b22a1906180)
![Greenshot 2024-11-25 15 22 29](https://github.com/user-attachments/assets/5fec6ed8-2f05-41df-81d9-52f91cbb709b)
![Greenshot 2024-11-25 15 22 20](https://github.com/user-attachments/assets/441d1055-a060-48e6-afaa-5da05c148702)
![Greenshot 2024-11-25 15 22 13](https://github.com/user-attachments/assets/cd87dc26-5f60-44d7-8ea3-02da65a27288)
![Greenshot 2024-11-25 15 22 09](https://github.com/user-attachments/assets/e1fffb68-6067-43b0-a45b-af2ccd86318a)
![Greenshot 2024-11-25 14 23 23](https://github.com/user-attachments/assets/2e560f0f-6aa4-4bb6-b38f-4acc5d153290)

#### v2.10.0
![Greenshot 2024-11-25 14 22 47](https://github.com/user-attachments/assets/62b95b0d-bbc5-4b62-b636-004f2af1dd0b)
![Greenshot 2024-11-25 14 17 12](https://github.com/user-attachments/assets/3e15873b-3321-4878-8ef4-630b48c01a20)
![Greenshot 2024-11-25 14 15 33](https://github.com/user-attachments/assets/634904d2-977d-42ee-865f-d0f4982643b0)
![Greenshot 2024-11-25 14 15 13](https://github.com/user-attachments/assets/5c940d99-f771-4afc-bcb4-d5bcb36014e4)
![Greenshot 2024-11-25 14 14 49](https://github.com/user-attachments/assets/805b1b76-1412-4a8e-aad4-fa47c4e9a26a)
![Greenshot 2024-11-25 14 14 39](https://github.com/user-attachments/assets/b3cd130f-67da-4867-aba6-557780a3089e)
![Greenshot 2024-11-25 14 14 26](https://github.com/user-attachments/assets/ebeaf64a-648b-4f16-878c-ea672ae1b678)
![Greenshot 2024-11-25 14 14 12](https://github.com/user-attachments/assets/cbdb9a8b-f06a-453e-893d-99330e2ca7df)
![Greenshot 2024-11-25 14 14 05](https://github.com/user-attachments/assets/879fe9a9-a9fc-467f-99b1-a71242909f48)
![Greenshot 2024-11-25 13 46 43](https://github.com/user-attachments/assets/95367b9e-5bbf-4fca-917f-be785508c505)
![Greenshot 2024-11-25 13 43 52](https://github.com/user-attachments/assets/59fbeb3b-0b67-4ef1-9714-18c6abb83593)
![Greenshot 2024-11-25 13 42 28](https://github.com/user-attachments/assets/4b9da3e9-7bcd-42fc-a8d9-d7ef1455d8d6)
