### ISSUE TITLE
[BUG] Empty template name in template version view page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#664]
**To Reproduce**
1. Click View Config
![image](https://user-images.githubusercontent.com/5697937/114014731-82fe7880-989b-11eb-84db-6ae3dfb1473b.png)

**Result**
![image](https://user-images.githubusercontent.com/5697937/114014789-94478500-989b-11eb-9bf9-e5f85659e011.png)

**Comment by DoNotSayYes** [comment]
Still can be encountered.
![image](https://user-images.githubusercontent.com/57614736/115210193-f1abc380-a130-11eb-807b-98e928fc295c.png)
![image](https://user-images.githubusercontent.com/57614736/115210279-05572a00-a131-11eb-841f-ca80bda18a48.png)

**Comment by WuJun2016** [comment]
The template version created by vm is missing the version number

**Comment by guangbochen** [comment]
when click the VM template actions it has no response 
![image](https://user-images.githubusercontent.com/4569037/115244879-f2efe700-a156-11eb-927c-50f6eabbcc17.png)

**Comment by kingsd041** [comment]
Fix in `master-0008ce84-head` version

![image](https://user-images.githubusercontent.com/19684717/115509777-6efe4200-a2b1-11eb-965a-646617ab345f.png)
