### ISSUE TITLE
[BUG] kubelet failed to start after enabling cpu manager

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#6641]
**Describe the bug**
After upgrade from `v1.3.2` to harvester `v1.4.0-dev-20240918` then enabling CPUManager on the node, the node remains in `cordoned` state. From UI is complains that Kubelet stopped posting node status. 
![image](https://github.com/user-attachments/assets/e4890782-a51d-4d54-9c75-539efa61d43e)

The root cause is upgrade_node.sh#set_reserved_resource use incorrect variable name, this lead both `systemReservedCPU` and `kubeReservedCPU` to zero thus make static cpu manager policy not work and make kubelet failed to start.

From the log `/var/lib/rancher/rke2/agent/logs/kubelet.log` we can see error as belows.
```
E0925 09:22:52.429151   16618 container_manager_linux.go:329] "Failed to initialize cpu manager" err="[cpumanager] unable to determine reserved CPU resources for static policy"
```

**To Reproduce**
1. Prepare v1.3.2 single node cluster (easy to test)
2. Upgrade to harvester dev release `v1.4.0-dev-20240918`
3. Enable CPU Manager through UI Hosts Page

**Expected behavior**
The node should remains in `Active` state after enableCPUManager finished.

**Support bundle**
N/A

**Environment**
N/A

**Additional context**
N/A

**Comment by khushboo-rancher** [comment]
@albinsun Let's test this when testing the upgrade test during the release testing of 1.4.0.

**Comment by albinsun** [comment]
Test PASS using single node `v1.3.2` => `v1.4.0-rc4`, close as fixed.


## Environment
* `harvester-v1.3.2` => `harvester-v1.4.0-rc4`
  * Profile: Single node AMD64 Bare-metal HPE ProLiant DL360 
  * ui-source: `Auto`


## Test Case
### CASE
1. Setup single node Harvester `v1.3.2`
2. Perform some VM operation and Rancher integration
3. Upgrade to Harvester `v1.4.0-rc4`
4. Should **Enable CPU Manager** successfully and node is `Active`
   ![image](https://github.com/user-attachments/assets/33371643-6b87-4d4a-b1b1-5f89c7586334)
   ![image](https://github.com/user-attachments/assets/7c19b452-3285-46c0-8236-f9ff818134fb)
