### ISSUE TITLE
[ENHANCEMENT] Release Harvester Node Driver v0.7.0

### ISSUE THREAD

**Issue by m-ildefons** [harvester/harvester#6645]
**Is your enhancement related to a problem? Please describe.**
Due to changes in the node driver API of Rancher, a hook has to be implemented in each node driver. The PR to do this for the Harvester Node Driver is:
https://github.com/harvester/docker-machine-driver-harvester/pull/61
This hook implements necessary functionality to be able to rotate the kubeconfig that the node driver uses. Therefore this hook is also needed to be able to rotate cloud credentials for existing guest clusters.
To make use of this hook, a new release of the Harvester Node Driver is needed, so it can be included in the next Rancher release.

**Describe the solution you'd like**

A new release of the Harvester Node Driver, which can be included in the next Rancher release.

**Describe alternatives you've considered**

Not releasing a new version of Harvester Node Driver and accepting that https://github.com/rancher/rancher/issues/44912 will not be fully fixed by the respected changes in Rancher (https://github.com/rancher/dashboard/issues/11270)

**Comment by innobead** [comment]
cc @bk201 @FrankYang0529

**Comment by innobead** [comment]
@rebeccazzzz @bk201 For any issues that require fixing in Rancher, let's make sure to have a corresponding Rancher issue and track the versions where they might be fixed; otherwise, they could be overlooked.

As far as I know, Rancher 2.9.3 is in code freeze now, but https://github.com/rancher/rancher/pull/47463 and https://github.com/rancher/rancher/pull/47485 were just created and, of course, haven't been merged yet.

**Comment by bk201** [comment]
Issues are created: 
- https://github.com/rancher/rancher/issues/47507
- https://github.com/rancher/rancher/issues/47508

For the v2.9 issue, I use v2.9.4 as the milestone.
@m-ildefons Can you help link the two PRs to these issues? 
- https://github.com/rancher/rancher/pull/47463
- https://github.com/rancher/rancher/pull/47485

**Comment by khushboo-rancher** [comment]
https://github.com/rancher/rancher/issues/47508 was included in Rancher 2.9.3. I verified the node driver, it is working as expected.
~~I'll validate with Rancher 2.10, will update here.~~
Validated on 2.10, node driver in updated to v0.7.0

Note: Details of testing is in the Rancher ticket

**Comment by FrankYang0529** [comment]
There is a dependency issue, so we need a new version to include it.

https://github.com/harvester/docker-machine-driver-harvester/pull/62

**Comment by m-ildefons** [comment]
Too late. v0.7.0 is already released. Maybe create a new release v0.7.1?

**Comment by FrankYang0529** [comment]
Yes, I see. I will create a new release for it.

**Comment by khushboo-rancher** [comment]
Closing this in favor of updating node driver to v0.7.0. @FrankYang0529 We can track the release v0.7.1 with a new ticket. Thanks

**Comment by innobead** [comment]
> Closing this in favor of updating node driver to v0.7.0. @FrankYang0529 We can track the release v0.7.1 with a new ticket. Thanks

Remember to have a ticket at the Rancher side as well. cc @rebeccazzzz @bk201

**Comment by FrankYang0529** [comment]
> > Closing this in favor of updating node driver to v0.7.0. @FrankYang0529 We can track the release v0.7.1 with a new ticket. Thanks
> 
> Remember to have a ticket at the Rancher side as well. cc @rebeccazzzz @bk201

Yes, created it. Thanks.

https://github.com/harvester/harvester/issues/6829
https://github.com/rancher/rancher/issues/47631
