### ISSUE TITLE
[BUG] VMs started on wrong hosts when PCI Passtrough devices are mapped

### ISSUE THREAD

**Issue by samueldewever** [harvester/harvester#6648]
**Describe the bug**
We create a new VM and map a PCI device trough it on a host. 
On the node scheduling we say it may start on any available host
When we start the VM, it might boot it on another node than the node of the PCI devices (the compatible node)
Because of this, PCI passthrough fails or even worse, point to the wrong /dev/vfio folder as a simular folder may exist on the other node as well. 

I would expect that the node can only be scheduled on a compatible node, so the node of the PCI device. 

**To Reproduce**

**Expected behavior**
I would expect that the node can only be scheduled on a compatible node, so the node of the PCI device. If not possible, it should not be able to select the option to run it on any available node when a PCI device is passtrought. 

**Support bundle**

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): dell poweredge R660

**Additional context**

**Comment by samueldewever** [comment]
Might be related by the fact that we have simular network cards in different nodes (simular model & brand) and that the same address is found accross multiple nodes:
![image](https://github.com/user-attachments/assets/65b39abf-56b1-4e6d-b8fb-7ce38123bf90)

**Comment by samueldewever** [comment]
> Might be related by the fact that we have simular network cards in different nodes (simular model & brand) and that the same address is found accross multiple nodes: ![image](https://private-user-images.githubusercontent.com/180277902/370876700-65b39abf-56b1-4e6d-b8fb-7ce38123bf90.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjcyOTQ3OTIsIm5iZiI6MTcyNzI5NDQ5MiwicGF0aCI6Ii8xODAyNzc5MDIvMzcwODc2NzAwLTY1YjM5YWJmLTU2YjEtNGU2ZC1iOGZiLTdjZTM4MTIzYmY5MC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyNVQyMDAxMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hMDBiMWJiMTUyODk1YTAxYzFiMDlmYzcwYTlhNzczMDIzOWZiZTZkZDU2ZDIwMWE2Mjg3NmZjZjRkMWUyZWRmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.T3abniEDARq8d5IGpuZEOmaL58j-R77fap5V-E7hrag)

Pretty sure its related. I disabled the VF on all hosts except one so we don't have this duplicates and than the VM is always placed at the right host. If I try to force it to another, it nicely put it in unscheduble.

So the problem happens when you have multiple hosts with SR-IOV enabled which have the same brand & type of network card. Because of that the address on the hosts get generated the same which fuckes up the whole PCI passtrough.

**Comment by irishgordo** [comment]
I was seeing a similar behavior with SR-IOV VFs when you're adding or removing a PCI card from the phsyical node, in my case a single 2U Dell PowerEdge R720 (that powered a Single Node Harvester Cluster at v1.3.1):
- https://github.com/harvester/harvester/issues/6518

I noticed that the workaround I outlined in 6518 "seemed" to mostly fix the situation when I did end up powering down that node and added another PCI device.... not sure if it's related or not :thinking:

**Comment by samueldewever** [comment]
> I was seeing a similar behavior with SR-IOV VFs when you're adding or removing a PCI card from the phsyical node, in my case a single 2U Dell PowerEdge R720 (that powered a Single Node Harvester Cluster at v1.3.1):
> 
> * [[BUG] Harvester cluster nodes aren't resilent when new PCI devices get added and VMs are using some "pre-existing" PCI Devices #6518](https://github.com/harvester/harvester/issues/6518)
> 
> I noticed that the workaround I outlined in 6518 "seemed" to mostly fix the situation when I did end up powering down that node and added another PCI device.... not sure if it's related or not 🤔

I indeed saw your bug report as Well. I tried the workaround before but in my case that Doesnt work. 

If you added a simular second identicsl Card in the server, i assume it might be related. Can you check if you see duplicate vf addedes in your case on the same node ?

**Comment by bk201** [comment]
cc @WebberHuang1118 @Yu-Jack

**Comment by WebberHuang1118** [comment]
@samueldewever 
Do you enable SR-IOV network function? or Just use the PCI passthrough?

**Comment by samueldewever** [comment]
> @samueldewever Do you enable SR-IOV network function? or Just use the PCI passthrough?

SR IOV network functions.

**Comment by samueldewever** [comment]
> @samueldewever Do you enable SR-IOV network function? or Just use the PCI passthrough?

In the meantime there is also a official suse support case 01555257 for this.

Apperently scheduling is done by using the devicename , which is always the same name for Intel virtual functions resulting in this behaviour. 

This is something which should be changed. Scheduling should happen bases on something more unique like name

**Comment by samueldewever** [comment]
@ibrokethecloud  refering to https://github.com/harvester/harvester/issues/6724 which was opened after our support case. 
I still believe this is not an enhancement, but the current behaviour is a bug as its not working by design by the 'wrong' implementation. 

I will add some nodes on 6724 in case you are planning this as an enhacement for 1.5

**Comment by w13915984028** [comment]
@samueldewever 

Did you try to label different nodes manually, e.g. for those with compatible hardwares with a label, and when creating VM, add this labels as the selector for scheduling https://docs.harvesterhci.io/v1.3/vm/index#vm-scheduling. You guide the system to work, instead letting it work automatically and may be out of expectation in some cases.

Meanwhile, there is no SB file attached https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle. When possible, could you post the VM/VMI's yaml output  & the NODEs' yaml output, we can check from the scheduler's point of view, which group of nodes will be the target of this VM. thanks.

**Comment by samueldewever** [comment]
> @samueldewever
> 
> Did you try to label different nodes manually, e.g. for those with compatible hardwares with a label, and when creating VM, add this labels as the selector for scheduling https://docs.harvesterhci.io/v1.3/vm/index#vm-scheduling. You guide the system to work, instead letting it work automatically and may be out of expectation in some cases.
> 
> Meanwhile, there is no SB file attached https://docs.harvesterhci.io/v1.3/troubleshooting/harvester#generate-a-support-bundle. When possible, could you post the VM/VMI's yaml output & the NODEs' yaml output, we can check from the scheduler's point of view, which group of nodes will be the target of this VM. thanks.

@w13915984028 
I assume that with labelling, it will work, but its ofcourse a workaround. 

In the meantime https://github.com/harvester/harvester/issues/6724 is opened to address this issue. Its a comfirmed thing, now marked as improvement, however for me its still is a bug ;-) 

Anyway, the workaround is too manually schedule it to the right host.

**Comment by w13915984028** [comment]
@samueldewever From your description https://github.com/harvester/harvester/issues/6648#issuecomment-2375145565, I wonder https://github.com/harvester/harvester/issues/6724#issue-2572080903 can work as a general solution for your case: similar devices on different nodes; but #6724 aims for multi-similar devices on same node.



If each device on each host is marked separately, then the VM will be tied to one/a couple of nodes.

**Comment by w13915984028** [comment]
@ibrokethecloud @WebberHuang1118 Would you mind to add this as a known limitation & with related workaroud to document? thanks.

**Comment by samueldewever** [comment]
> oved this from **New** to **Resolved/Scheduled** i

I do believe that indeed would work. If we would combine the labeling in nodes with the current way of handling the scheduling based on resourcename, it would 

> @ibrokethecloud @WebberHuang1118 Would you mind to add this as a known limitation & with related workaroud to document? thanks.

Once scheduling can be done based on hostDevice instead of resourcename, the VM will be scheduled on the host of the select PCIDevice. This is in theory what you would expect , as you really specify in the UI as well a specific PCI hostdevice including the host on which it should run

The other option would be to do it based on the current resourceName and use labels as an additional way for scheduling. The advantage is that it could give some 'failover redunandancy' for VMs with VF, however it would still feel a bit bizar. When you make the VM you would select a VF with a name from a specific host, however you known that your VM might end up at another host.

I believe that in 99% of the use cases, once you give PCI Devices access or VF you want to link that VM to that specific host as well, so the enhancement of looking to hostDevice is in my opinion the by-default standard to be used.

**Comment by samueldewever** [comment]
> @samueldewever From your description [#6648 (comment)](https://github.com/harvester/harvester/issues/6648#issuecomment-2375145565), I wonder [#6724 (comment)](https://github.com/harvester/harvester/issues/6724#issue-2572080903) can work as a general solution for your case: similar devices on different nodes; but #6724 aims for multi-similar devices on same node.
> 
> If each device on each host is marked separately, then the VM will be tied to one/a couple of nodes.


@w13915984028 
Once scheduling can be done based on hostDevice instead of resourcename, the VM will be scheduled on the host of the select PCIDevice. This is in theory what you would expect , as you really specify in the UI as well a specific PCI hostdevice including the host on which it should run

The other option would be to do it based on the current resourceName and use labels as an additional way for scheduling. The advantage is that it could give some 'failover redunandancy' for VMs with VF, however it would still feel a bit bizar. When you make the VM you would select a VF with a name from a specific host, however you known that your VM might end up at another host.

I believe that in 99% of the use cases, once you give PCI Devices access or VF you want to link that VM to that specific host as well, so the enhancement of looking to hostDevice is in my opinion the by-default standard to be used.

**Comment by w13915984028** [comment]
@samueldewever Well, from your description, it looks we can convert the `nodeName: harvester-f7gmj` of selected pci-devices to vm selector directly from UI code. It sures that the VM is scheduled to the target node.  given your statement `the VM will be scheduled on the host of the select PCIDevice`. Before #6724 , we can quickly fix this bug.


```
  name: harvester-f7gmj-000008002
  ownerReferences:
  - apiVersion: devices.harvesterhci.io/v1beta1
    kind: PCIDevice
    name: harvester-f7gmj-000008002
spec:
  address: "0000:08:00.2"
  nodeName: harvester-f7gmj
```

**Comment by w13915984028** [comment]
Hi @torchiaf @a110605:

Just like schedule the VM to a given node, when a VM cliams a PCI device from UI, UI has all information of this PCI device including which node it belongs to. 

UI may add the PCI device's node name to VM's scheduler/selector, thus the node information is not lost and not causing this issue: when several nodes have same PCI-devices, the VM is scheduled to a random node. thanks.

**Comment by w13915984028** [comment]
I did following test, the `nodeSelector` `kubernetes.io/hostname` is added when setting VM to run on a node.

Selecting the `pci-device` means the VM should add the above selector automatically & implicitly (by UI), to record the host which provisions the selected device.

One corner case is a bit complex: if user sets a target node & adds a `pci-device` (on same node); and then removes the `pci-deivce`, should the `node` be removed to kept. Document it should be fine.


![image](https://github.com/user-attachments/assets/de62b37e-5c6d-491f-a0b5-9b99bd26c547)

```
VM object:

spec:
..
      labels:
        harvesterhci.io/vmName: vm4
    spec:
      affinity: {}
..
...
      nodeSelector:
        kubernetes.io/hostname: harv41  // `pci-device` operation may fill this as well.
```

**Comment by w13915984028** [comment]
Currently, Harvester adds the `migrate` action to a VM with a simple condition check:

https://github.com/harvester/harvester/blob/d0d234b5d8f434301111acef85370cc41972e202/pkg/api/vm/formatter.go#L246
```
	// The VM is set to run on a specific node
	if vmi.Spec.NodeSelector != nil && vmi.Spec.NodeSelector[corev1.LabelHostname] != "" {
		return false
	}
```

This issue, in turn, also causes the VM showing `migrate` button on then UI.

The `canMigrate` will be refactored via issue #6843.

**Comment by w13915984028** [comment]
cc @bk201   Added the `v1.4.0` for now, to track the issue.

Per discussion with @torchiaf, this issue is existing on v1.3.0 as well.

**Comment by bk201** [comment]
will be addressed in https://github.com/harvester/harvester/issues/6724

**Comment by w13915984028** [comment]
This issue, and https://github.com/harvester/harvester/issues/6843,  looks to be a general topic for UI as well. cc @torchiaf @a110605 @Yu-Jack 

When a device (vGPU, PCI, USB ...) is binded to a VM, if the device has host info, then UI needs to copy the host info to VM node selector, at least, it meets user's expectation.

**Comment by w13915984028** [comment]
@bk201 As this issue is moved to v1.5.0, we need to update v1.4.0 document to list it as a know issue: when user adds PCI devices to a VM and there are more nodes having the same type of PCI devices, the VM may be scheduled to any of them. The workaroud is to edit VM yaml and add the target node to `nodeSelector`.

**Comment by bk201** [comment]
@ibrokethecloud please help create a doc and I can close this one (keep https://github.com/harvester/harvester/issues/6724)
