### ISSUE TITLE
[BUG] Harvester setting upgrade-config is not avialable on UI

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6659]
**Describe the bug**

Setting `upgrade-config` and and related options introduced via PR: https://github.com/harvester/harvester/pull/6181,  https://github.com/harvester/harvester/pull/6426

```
upgrade-config                                {"imagePreloadOption":{"strategy":{"type":"sequential"}}, "restoreVM": true}
```

are not available on Harvester-UI.

![image](https://github.com/user-attachments/assets/a4efd14d-d0e0-4039-9f2a-89f606ff0c67)

**To Reproduce**

User needs to be able to configure them on UI.

**Expected behavior**

**Support bundle**

**Environment**
 - Harvester ISO version:  v1.4.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

https://github.com/harvester/harvester/issues/4005

https://github.com/harvester/harvester/issues/3059
https://github.com/harvester/harvester/issues/6028

**Comment by w13915984028** [comment]
cc @starbops @tserong @torchiaf @a110605

**Comment by w13915984028** [comment]
@bk201 This is observed in the upgrade related issues validation, lable them on the `v1.4.0` release from initial.

**Comment by bk201** [comment]
Thanks for reporting. The [GUI issue](https://github.com/harvester/harvester/issues/6045) was moved to 1.5.0 intentionally to let the GUI team focus on high-priority features. I'll close this one.
