### ISSUE TITLE
[ENHANCEMENT] Avoid loop dependence between harvester and harvester-network-controller

### ISSUE THREAD

**Issue by FrankYang0529** [harvester/harvester#6667]
**Is your enhancement related to a problem? Please describe.**
harvester-network-controller import harvester: https://github.com/harvester/network-controller-harvester/blob/f81a6225dc7fc135b0ca1e28f1da109b8e4b66b6/pkg/utils/vmi.go#L8

harvester import harvester-network-controller: https://github.com/harvester/harvester/blob/606f485579d087def560e2a8a255a2b0f4bad019/pkg/webhook/resources/setting/validator.go#L39-L40

**Describe the solution you'd like**
Define a clear dependence path to avoid loop dependence between harvester and harvester related repositories.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
I am also working on a similar issue https://github.com/harvester/harvester/issues/6570, decouple the cross dependency is essential.

**Comment by FrankYang0529** [comment]
Thank you. I didn't find it. I'll close this one. 👍
