### ISSUE TITLE
[BUG] Volume lose Degraded status after Stop then Start 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6669]
**Describe the bug**
Volume lose its Degraded status after Stop then Start 

**To Reproduce**
1. Create 3 VMs _vm-restart_, _vm-softreboot_ and _vm-stopstart_ with same spec
   ![image](https://github.com/user-attachments/assets/be775fb8-d771-4458-bf14-826d822efa16)

2. All volumes should be `Degraded`
   * Harvester :heavy_check_mark: 
     ![image](https://github.com/user-attachments/assets/d379b015-f899-4abd-832a-ddf5c3bca1ec)
   * Longhorn :heavy_check_mark: 
     ![image](https://github.com/user-attachments/assets/9ce2b09c-a189-44b4-8618-2bee4074d46d)

3. Power actions
   * _vm-restart_: Restart 
   * _vm-softreboot_: Soft Reboot 
   * _vm-stopstart_: Stop => Start
   ![image](https://github.com/user-attachments/assets/0e23f767-424a-4da1-9d95-5b7ae46ab8ed)
   ![image](https://github.com/user-attachments/assets/327c618f-4755-4ee2-bd9a-681ef3d6c60e)

2. All volumes should be **Degraded** too
   * Harvester :x: 
     > Stop => Start VM is `In-use` 
     > ![image](https://github.com/user-attachments/assets/0e6cb422-77d0-4def-baca-5889f4436678)
    
   * Longhorn :heavy_check_mark: 
     ![image](https://github.com/user-attachments/assets/386a7c79-7c37-42d6-a3eb-22d4123d8c24)

**Expected behavior**
Volume status should be independent, not relates to VM power history.

**Support bundle**
[supportbundle_LoseDegradedAfterStopStart_2024-09-27T11-27-55Z.zip](https://github.com/user-attachments/files/17163452/supportbundle_LoseDegradedAfterStopStart_2024-09-27T11-27-55Z.zip)

**Environment**
 - Harvester ISO version: v1.4.0-dev-20240918
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node QEMU/KVM (8C/16G/500G)

**Additional context**
1. Reboot does not help return to the correct status.

**Comment by Yu-Jack** [comment]
After investigation, it seems that Longhorn might have an issue.

To reproduce it:
1. Create a Longhorn RWX or RWO volume (backing image is okay as well) with replica count 3. Be sure this replica number should be greater than our nodes.
2. Attach volume to node.
3. Detach volume.
4. Attach volume again.

Reproduce recoding
https://github.com/user-attachments/assets/1a813f9c-ee9e-4e81-8ed3-065eb0dee32b

In 2. step, please check annotation `longhorn.io/volume-scheduling-error` in `persistentvolume`, it's a `replica scheduling failed`. The condition in `longhorn.io/v1beta2/volume`, it's:

```
- lastProbeTime: ""
    lastTransitionTime: "2024-09-30T04:38:09Z"
    message: replica scheduling failed
    reason: ReplicaSchedulingFailure
    status: "False"
    type: Scheduled
```

In 4. step, the annotation `longhorn.io/volume-scheduling-error` in `persistentvolume` becomes `""`. The condition in `longhorn.io/v1beta2/volume`, it becomes:
```
  - lastProbeTime: ""
    lastTransitionTime: "2024-09-30T04:33:48Z"
    message: precheck new replica failed
    reason: ReplicaSchedulingFailure
    status: "False"
    type: Scheduled
```

[In Harvester](https://github.com/harvester/dashboard/blob/a537c1ae38eb7030542ac371f24ae3336cd9d422/pkg/harvester/models/harvester/persistentvolumeclaim.js#L101-L117), we used that annotation in `persistentvolume` to present `Degraded` status. [In Longhorn](https://github.com/longhorn/longhorn-ui/blob/b982e534a1d39b222d03687704c690118ac7b60c/src/routes/volume/VolumeList.js#L185), they used `status.robustness` in `longhorn.io/v1beta2/volume` to present `Degraded` status. It's from different places. There are [two pieces of codes](https://github.com/search?q=repo%3Alonghorn%2Flonghorn-manager%20PVAnnotationLonghornVolumeSchedulingError&type=code) where Longhorn updates this annotation in v1.7.1. Therefore, I think it's likely an issue with Longhorn.

**Comment by WebberHuang1118** [comment]
This is similar to https://github.com/longhorn/longhorn/issues/9514. The pv annotation `longhorn.io/volume-scheduling-error` is set to empty under different situation.

**Comment by WebberHuang1118** [comment]
Hi @Yu-Jack,
I just checked with the Harvester which bumps LH to v1.7.2-rc1 https://github.com/harvester/harvester/pull/6753.

According to the reproduce steps https://github.com/harvester/harvester/issues/6669#issuecomment-2382443653, after the LH fix is merged https://github.com/longhorn/longhorn-manager/pull/3194, the PV annotation will change from `replica scheduling failed` to `precheck new replica failed`, and the GUI changed from `degarded` to `NotReady`, it seems the GUI depends on certain message string. cc @bk201

**Comment by Yu-Jack** [comment]
HI @WebberHuang1118 It's still rc1 now, rc2 is not released yet.

**Comment by Yu-Jack** [comment]
This issue requires two features
- Bump LH to v1.7.2-rc1 at least: 
   master: https://github.com/harvester/harvester/pull/6753
   v1.4: https://github.com/harvester/harvester/pull/6795
- Extend degraded error list in GUI: 
   master: https://github.com/harvester/dashboard/pull/1194
   v1.4: https://github.com/harvester/dashboard/pull/1196

**Comment by Yu-Jack** [comment]
This is a master-demo (7382733a).

https://github.com/user-attachments/assets/6e888c54-9c1e-4183-bfab-b2a541ae06b6

**Comment by Yu-Jack** [comment]
v1.4-9b9498f-head

https://github.com/user-attachments/assets/6316783b-6cfa-4762-beed-d49388901d97

**Comment by Yu-Jack** [comment]
Just tested in RC3.

![image](https://github.com/user-attachments/assets/f5b6abb6-8b80-4784-8f30-15b6fba9f060)

![image](https://github.com/user-attachments/assets/87f2148a-918f-4c80-b980-627c8c2d3649)

**Comment by albinsun** [comment]
Test PASS, close as fixed.


## Environment
* `harvester-v1.4.0-rc3`
  * Profile: Single node AMD64 QEMU/KVM
  * ui-source: `Auto`


## Prerequisite
1. Create image _ubuntu-22.04-jammy-server-cloudimg-amd64.img_
1. Create VM network _mgmt-vlan1_


## Steps
1. <details>
   <summary> :heavy_check_mark: Create 3 VMs <i>vm-restart</i>, <i>vm-softreboot</i> and <i>vm-stopstart</i> with same spec
   </summary>
   
   ![image](https://github.com/user-attachments/assets/3161fdd3-6fab-4d03-8ba1-5d490440ca0b)
   </details>

1. <details>
   <summary> :heavy_check_mark: All volumes should be `Degraded`
   </summary>
   
   * Harvester Volumes
     ![image](https://github.com/user-attachments/assets/02bcaab7-d22b-4c60-b5e2-cb93211b8bfa)
   * _persistentvolumes_
     ![image](https://github.com/user-attachments/assets/66d89b16-c1b3-4a62-8a01-3117d5d1b24c)
   </details>

1. <details>
   <summary> :heavy_check_mark: Power actions on each VMs respectively
   </summary>
   
   ![image](https://github.com/user-attachments/assets/52b847d7-f9fe-4fa0-9b3f-5747716e24e6)
   </details>

   * _vm-restart_: Restart 
   * _vm-softreboot_: Soft Reboot 
   * _vm-stopstart_: Stop => Start

1. <details>
   <summary> :heavy_check_mark: All volumes should be **Degraded** too
   </summary>
   
   * Dashboard
     ![image](https://github.com/user-attachments/assets/a1ce6602-5660-440b-b731-385204ff6bd5)
   * _persistentvolumes_
     ![image](https://github.com/user-attachments/assets/3a30e382-84fb-4286-95ff-e6cb7b9867b2)
   </details>


[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade
