### ISSUE TITLE
[ENHANCEMENT] Do not allow to delete harvester-longhorn storageclass

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6678]
**Is your enhancement related to a problem? Please describe.**

User may delete harvester-longhorn SC, which is monitoring by managedchart, and also used by rancher-monitoring stack by default.

**Describe the solution you'd like**

Deny to delete it.

**Describe alternatives you've considered**

**Additional context**

**Comment by w13915984028** [comment]
Test plan:

(1) Install a v1.4.0 new cluster.
(2) Delete the `harvester-longhorn` storage-class, it will be denied.
(3) Upgrade a v1.3.* cluster to v1.4.0, repeat (2).

(4) On the newly installed v1.4.0 or upgrade to v1.4.0 cluster, create a new storage-class, add `harvesterhci.io/is-reserved-storageclass: "true"` to it's annotations manually, then delete this SC, it will be denied;  remove this annotation/set the value to "false", the SC can be deleted.

**Comment by brandboat** [comment]
Test OK on [v1.4.0-rc2](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc2), close as fixed.

## Environment
* [v1.4.0-rc2](https://github.com/harvester/harvester/releases/tag/v1.4.0-rc2)
  * Profile: 1 node QEMU/KVM (8C/16G/250G)
  * ui-source: `Auto`

## Test Steps
✅  Delete the harvester-longhorn storage-class, got error `The request is invalid: : storage class harvester-longhorn is reserved by Harvester and can't be deleted`
✅  Create storage-class `test` and add annotation `harvesterhci.io/is-reserved-storageclass: "true"` manually, then delete the SC, got the same error message as above.
✅  Create storage-class `test`, then I can delete the SC successfully.

These 3 checks all passed under 
- newly installed v1.4.0-rc2 harvester 
- cluster upgrade from v1.3.2 to v1.4.0-rc2
