### ISSUE TITLE
[BUG] LB IP does not release when IPAM change

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6684]
Pool LB IP does not release when change IPAM to DHCP, and vice versa.

* IPAM Pool -> DHCP
  ![image](https://github.com/user-attachments/assets/96e873e0-ef9e-4fd6-8ac1-4b25b535a5c8)
* IPAM DHCP -> Pool
  ![image](https://github.com/user-attachments/assets/82ad9e72-0be4-4621-a5bf-42b961deb2d6)

### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: Single node QEMU/KVM
  * ui-source: Auto

### Prerequisite
1. <details>
   <summary> STEP
   </summary>
   </details>

### Steps
1. <details>
   <summary> Create an IPPool w/ 3 IPs
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4915fc47-9453-4c87-8f4e-b6051d667934)
   </details>

1. <details>
   <summary> Create 3 LBs (IPAM Pool), 3 LBs gets IP
   </summary>
   
   ![image](https://github.com/user-attachments/assets/8d6be99a-80c9-4efe-9cfa-67758d5d62e3)
   </details>

1. <details open>
   <summary> :x: Change <i>lb1</i>'s <b>IPAM</b> from <code>Pool</code> to <code>DHCP</code>, address should be release and reallocated.
   </summary>
   
   * Change IPAM to DHCP
     ![image](https://github.com/user-attachments/assets/b3899db5-14d4-40f1-b512-d7f67daa975f)
   * IP not release
     ![image](https://github.com/user-attachments/assets/96e873e0-ef9e-4fd6-8ac1-4b25b535a5c8)
   </details>

1. <details open>
   <summary> :x: Delete <i>lb1</i> and <i>lb4</i> should get IP
   </summary>
   
   ![image](https://github.com/user-attachments/assets/0c4a8778-02ba-4b78-b7e4-461ab43206e8)
   </details>

### Supportbundle
[supportbundle_IpNotReleaseWhenChangeIPAM_2024-10-01T08-23-23Z.zip](https://github.com/user-attachments/files/17201880/supportbundle_IpNotReleaseWhenChangeIPAM_2024-10-01T08-23-23Z.zip)

**Comment by w13915984028** [comment]
As LB can be created as a placeholder and easily re-created.

We will add a webhook check to deny the change of IPAM from IPPool to DHCP and vice versa, to avoid possible address leaking. User may delete and create a new LB to get the purpose.

**Comment by starbops** [comment]
Please note that #1834 is not fully implemented yet.

**Comment by w13915984028** [comment]
@starbops Please check comment https://github.com/harvester/harvester/issues/1834#issuecomment-2397111183, I did not find a better solution to release the IP by kube-vip from DHCP server when changing the IPAM from DHCP to Pool. Deny the change and explain the details in the document is the current proposal, thanks.

**Comment by w13915984028** [comment]
This issue can be validated with the coming harvester-v1.4.0-rc4 release, which has the new LB image tag bumped via PR https://github.com/harvester/harvester/pull/6833.

**Comment by Yu-Jack** [comment]
## Validation Description

Follow original post to reproduce. It blocks requests from DHCP to Pool or from Pool to DHCP.

<details>
<summary> 🟢 From Pool to DHCP</summary>

GUI
![image](https://github.com/user-attachments/assets/31869d19-666b-4923-9c4c-d621ab3036bd)

YAML of GUI
![image](https://github.com/user-attachments/assets/e2817715-0102-4656-a169-39b2a25646e4)

`kubectl`
![image](https://github.com/user-attachments/assets/40d974fa-7a7e-4c75-9d18-fc29cde716d9)


</details>

<details>
<summary> 🟢 From DHCP to Pool</summary>

GUI
![image](https://github.com/user-attachments/assets/d773a000-87d1-4ada-b52e-6bffe49834c4)

YAML of GUI
![image](https://github.com/user-attachments/assets/0b37eef3-b226-4d36-bee7-290fa6d67651)

`kubectl`
![image](https://github.com/user-attachments/assets/dbc2d802-6164-47ab-a270-bfbe33c8d2c6)


</details>

## Environment

- Single Node harvester-v1.4.0-rc4
