### ISSUE TITLE
[GUI] [ENHANCEMENT] Host local storage support

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#6685]
**Is your enhancement related to a problem? Please describe.**

Related PR https://github.com/harvester/dashboard/pull/1076

We added LVM and Longhorn V2 storage support in Harvester v1.4.
We want to add some restrictions to Volumes, Snapshots and Images functionalities when handling these types of storage and improve error handling.

**Describe the solution you'd like**

- Remove 'Export to Image' action for Longhorn V2 volumes.
- Remove 'Take a snapshot' action for Longhorn V2 volumes.
- Disable 'Size' inputBox for Longhorn V2 volumes in edit mode and add a warning banner - both Volumes and Virtual Machines page.
- Disable volume encryption block if choosen `Longhorn v2` Provisioner in storage class create page.
- Delete unsaved disk in host edit page should clean related data, add new disk back should have empty fields. (see [comment](https://github.com/harvester/dashboard/pull/1076#issuecomment-2373280046)) 

**Describe alternatives you've considered**

**Additional context**

**Comment by torchiaf** [comment]
@a110605 I think keeping the removed disks is something we want by design, there is a dedicate logic to do that:

https://github.com/harvester/dashboard/blob/ed19b0de38713d7f8e363de0cc14006f7c4c218d/edit/host/index.vue#L214-L219

```
addDisk(id) {
  const removedDisk = findBy(this.removedDisks, 'blockDevice.id', id);

  if (removedDisk) {
    return this.newDisks.push(removedDisk);
  }
```

I'm not sure if we want to remove this behavior. @bk201 what do you think ?

**Comment by a110605** [comment]
> harvester/dashboard#1076

That [behavior](https://github.com/harvester/dashboard/pull/1076#issuecomment-2373280046) is strange from my perspective. Is there any harm to clean up the previous remove disk ? cc @bk201 

@Vicente-Cheng said [backend have no limitation](https://github.com/harvester/dashboard/pull/1076#issuecomment-2384688377) to update disk CR.

**Comment by tserong** [comment]
I think we need to disable encryption for LHv2 volumes as well (this is on the LH roadmap for v1.8 -- https://github.com/longhorn/longhorn/wiki/Roadmap#longhorn-v18-january-2025)

**Comment by tserong** [comment]
...and just to confirm, LHv2 _does_ support snapshots. I can successfully snapshot and restore volumes using the LH GUI, so the backend functionality works fine. It's behaving weirdly on the Harvester side - I can create snapshots, but when restoring, the new volumes get stuck somehow, but that means we have a separate issue to fix; I don't think that means we should disable snapshots for V2 volumes.

I'll open a separate issue for the snapshot restore weirdness once I've got some more details...

**Comment by a110605** [comment]
> ...and just to confirm, LHv2 _does_ support snapshots. I can successfully snapshot and restore volumes using the LH GUI, so the backend functionality works fine. It's behaving weirdly on the Harvester side - I can create snapshots, but when restoring, the new volumes get stuck somehow, but that means we have a separate issue to fix; I don't think that means we should disable snapshots for V2 volumes.
> 
> I'll open a separate issue for the snapshot restore weirdness once I've got some more details...

Thanks @tserong , I updated this ticket discription to keep the `take snapshot` action for LHv2 volume and add another one to disable encryption/decryption for LHv2 volume.

**Comment by torchiaf** [comment]
@a110605 I've re-enabled the snapshots action and disable volume envryption for V2 classes + code refactoring, pleate take a look.
`Delete unsaved disk in host edit page should clean related data` point is still open, so I'd keep it as is for the moment.

**Comment by brandboat** [comment]
Will test this after v1.4.0-rc5 comes out as we need the fix PR https://github.com/harvester/node-disk-manager/pull/161.
to verify GUI enhancement
> Delete unsaved disk in host edit page should clean related data, add new disk back should have empty fields. (see https://github.com/harvester/dashboard/pull/1076#issuecomment-2373280046)

**Comment by brandboat** [comment]
test ok in v1.4.0-rc5, will close the issue.

# Environment
- 3 nodes (8C/16GB/250GB)
- v1.4.0-rc5

# Prerequisistes
- Run [`attach-disk.sh`](https://github.com/harvester/vagrant-rancherd/blob/main/scripts/attach-disk.sh) to attach disk to harvester-node-0
- Create `lhv2-sc` longhorn v2 (CSI) storage class
<img width="1660" alt="image" src="https://github.com/user-attachments/assets/299c1c8b-fe44-4f86-ab28-f875d00d3ab3">


# Test plan
## ✅  Delete unsaved disk in host edit page should clean related data, add new disk back should have empty fields
go to hosts page, edit storage config in harvester-node-0

https://github.com/user-attachments/assets/2849dbd8-1a01-45bf-b4d9-6596e65f0c62

## ✅  Remove 'Export to Image' action for Longhorn V2 volumes.
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/4384a1a5-efed-4199-9e2a-e981b1e16bfb">

## ✅  Remove 'Take a snapshot' action for Longhorn V2 volumes.
screenshort provided in `Remove 'Export to Image' action for Longhorn V2 volumes.`

## ✅  Disable 'Size' inputBox for Longhorn V2 volumes in edit mode and add a warning banner - both Volumes and Virtual Machines page.
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/c9f4601b-eb2d-4875-9f5c-4cda5ab769e5">

## ✅ Disable volume encryption block if choosen Longhorn v2 Provisioner in storage class create page.
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/8f556772-43b1-4d03-9b4e-250f5387af1f">
