### ISSUE TITLE
[BUG] IPPool range overlapped when Scope configured

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6687]
New IPPool validated as overlapped when **Scope** is configured.
But cab be created with empty **Scope**.

### Environment
* Harvester
  * Version: v1.4.0-dev-20240918
  * Profile: single node QEMU/KVM
  * ui-source: Auto

### Test Case
1. <details>
   <summary> Create an ranged IPPool <code>192.168.0.0/28 and 192.168.0.11 ~ 192.168.0.13</code> with <b>Scope</b> configured 
   </summary>
   
   ![image](https://github.com/user-attachments/assets/f21a13a3-4f89-4f35-b62d-36c1de930c58)
   </details>

1. <details open>
   <summary> :x: Create another ranged IPPool <code>192.168.0.0/28 and 192.168.0.7 ~ 192.168.0.9</code> with <b>Scope</b> configured 
   </summary>
   
   * Scope `All`
     ![image](https://github.com/user-attachments/assets/c608f985-6435-444d-87ef-a2dd7aa195ff)
   * Scope `default`
     ![image](https://github.com/user-attachments/assets/6597967d-d6a6-44ee-8921-ab4004976cfc)
   </details>

### Supportbundle
[supportbundle_IPPoolRangeOverlappedWhenScopeConfigured_2024-10-01T09-38-41Z.zip](https://github.com/user-attachments/files/17202903/supportbundle_IPPoolRangeOverlappedWhenScopeConfigured_2024-10-01T09-38-41Z.zip)

[^1]: https://docs.harvesterhci.io/v1.1/upgrade/automatic#prepare-an-air-gapped-upgrade

**Comment by w13915984028** [comment]
This issue was not labeled with milestone and release; but it is belonging to v1.4.0 and has been fixed via PR https://github.com/harvester/tests/issues/1562.

Test Plan:

1. Same as issue description, the error information has clear description https://github.com/harvester/load-balancer-harvester/pull/37#issue-2559867642

**Comment by rrajendran17** [comment]
@w13915984028  If I understand correctly, The issue mentioned in the bug is expected,not an issue, and I believe the issue is fixed by rephrasing the webhook error in more meaningful way.For example
" can't update IP pool pool4 because scope selector is same as the pool pool3 with priority 0 Project Namespace default GuestCluster , set a different priority or scope"

as the scopes must be unique for each IP pool.

**Comment by w13915984028** [comment]
@rrajendran17 Yes, your description is correct. thanks.

**Comment by rrajendran17** [comment]
Thanks @w13915984028

**Comment by rrajendran17** [comment]
Verified this on v1.4-eaf3009a-head and works as expected.
Steps of verification:
1.create pool1 and pool2 without scope - success
2.create pool3 with scope All - success
3.create pool4 with scope default - webhook error (scopes must be unique)
4.create pool4 with scope All - webhook error (scopes must be unique)
5.create pool4 with scope harvester-public - webhook error (scopes must be unique)
6.Edit pool3 with scope default - success
7.Create pool4 with scope harvester-public - success (as scopes are unique now)
8.Edit pool4 with scope default - webhook error

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN21rQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--3e7ea1de17279b22bd5cd1c6803815713c9f8387/6687-img3.png" alt="6687-img3.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3FrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--4f8879bda535971c8ad6215d09d9c5bab789971e/6687-img4.png" alt="6687-img4.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3lrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--6ff6081065a924d0d25253edc00c4cf267e591d5/6687-img5.png" alt="6687-img5.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzJrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f95f51d468cd485d4cc1686410097b758749ce15/6687-img6.png" alt="6687-img6.png" />


<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNzZrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0cf6da54c37a19ad39d7d106c7a57206e25fefa5/6687-img7.png" alt="6687-img7.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBNytrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--cb9f4c3c8ca08ec5f68bd1ee2f0527e717337e28/6687-img7.png" alt="6687-img7.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOENrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--906aaf44e77fa37c2e1fc62d91b0b12a8b396c25/6687-img8.png" alt="6687-img8.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOEdrQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--995e2e88f33be923697ffbe443c622ce6f1e026d/6687-img9.png" alt="6687-img9.png" />

<img width="1324" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOG1rQnc9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--e037daf53f69cfc78d5fde75a74cb432b8873fe7/6687-img11.png" alt="6687-img11.png" />
