### ISSUE TITLE
[FEATURE] Add more debug/performance tools to Harvester ISO

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#669]
![image](https://user-images.githubusercontent.com/15064560/114121153-6d7f6200-9920-11eb-987f-42a76a8c7448.png)

**Comment by guangbochen** [comment]
@futuretea can u please help to clarify what tool has been added and what are verification steps required from the QA side, thanks.

**Comment by futuretea** [comment]
verification steps:
1. check if the corresponding command exists.


package | command
-- | --
sysstat | pidstat,iostat,sar
smartmontools | smartctl
hwinfo | hwinfo
gotop | gotop
bcc-tools | /usr/share/bcc/tools/*
iperf | iperf
iftop | iftop
iotop | iotop
fio | fio
scapy | scapy
tcpdump | tcpdump
tshark | tshark
ethtool | ethtool
socat | socat
httpie | http
tcptraceroute | tcptraceroute
mtr | mtr
bind-tools | dig
tmux | tmux
fd | fd
the_silver_searcher | ag

**Comment by TangStone** [comment]
### Validation in version master-0008ce84-head

package | command | Results
-- | -- | --
sysstat | pidstat,iostat,sar |  Validated
smartmontools | smartctl | Validated
hwinfo | hwinfo | Validated
gotop | gotop | Validated
bcc-tools | /usr/share/bcc/tools/* | Validated
iperf | iperf | Validated
iftop | iftop | Validated
iotop | iotop | Validated
fio | fio | Validated
scapy | scapy | Validated
tcpdump | tcpdump | Validated
tshark | tshark | Validated
ethtool | ethtool | Validated
socat | socat | Validated
httpie | http | Validated
tcptraceroute | tcptraceroute | Validated
mtr | mtr | Validated
bind-tools | dig  | Validated
tmux | tmux | Validated
fd | fd | Validated
the_silver_searcher | ag | Validated
