### ISSUE TITLE
[BUG] Can't upgrade from master/stable branch 

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6699]
**Describe the bug**

If you deploy a master or v1.4-head ISO and try to upgrade to another version, the preload job will fail because it can't find the harvester-upgrade image. For example:

![image](https://github.com/user-attachments/assets/76bbfb5f-3357-41e8-8fcf-6bdbcaa97978)

**To Reproduce**
1. Download master or v1.4 ISO.
2. Upgrade to the same version.

**Expected behavior**

The upgrade should continue.

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

The cause is the mismatch between the `server-version` and the image tag. For example: in a crime scene we found the server version is `v1.4-cd10d18-head`, but the image preloaded on the node has the tag `v1.4-cd10d18d-head` (hash length different).

**Comment by Yu-Jack** [comment]
We should pay attention to other places where we use this command if we have.

https://stackoverflow.com/questions/44286795/why-does-git-rev-parse-short-use-a-non-default-length
https://stackoverflow.com/questions/63224118/git-rev-parse-short-head

**Comment by khushboo-rancher** [comment]
@lanfon72 Is it possible to use upgrade CI by setting the right parameters to test this? e.g. upgrade from 1.4-head/1.4-rc2 to master?

**Comment by lanfon72** [comment]
yes we can use Jenkins to do the test.

**Comment by lanfon72** [comment]
Verified this bug has been fixed.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4-95024f7c-head** (same version upgrade)
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes
2. Perform upgrade
3. Upgrade should complete successfully
