### ISSUE TITLE
[BUG] Longhorn V2 disks are added successfully, but show webhook errors in the UI, and in BD status conditions

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6709]
**Describe the bug**
When adding an additional disk to a node with provisioner set to Longhorn V2, the disk is added successfully, but later shows admission webhook errors, for example:

![image](https://github.com/user-attachments/assets/a3d8794e-960b-475a-b574-61e25a907d8e)

After rebooting the host, we see a different error:

![image](https://github.com/user-attachments/assets/ce78055f-4261-41f6-9671-c615817c641e)

...and the corresponding block device status shows the `AddedToNode` condition is `false`, even though the disk _is_ provisioned successfully:

```
# kubectl get bds -n longhorn-system -o yaml
[...]
  spec:
    [...]
    provision: true
    provisioner:
      longhorn:
        engineVersion: LonghornV2
  status:
    conditions:
    - lastUpdateTime: "2024-10-04T07:36:57Z"
      message: 'Internal error occurred: failed calling webhook "mutator.longhorn.io":
        failed to call webhook: Post "https://longhorn-admission-webhook.longhorn-system.svc:9502/v1/webhook/mutation?timeout=10s":
        proxy error from 127.0.0.1:9345 while dialing 10.52.0.174:9502, code 502:
        502 Bad Gateway'
      reason: Error
      status: "False"
      type: AddedToNode
    [...]
    provisionPhase: Provisioned
    state: Active
```

**To Reproduce**
1. Add a new disk to a host using the Longhorn V2 provisioner.
2. Wait and observe the errors described above.

**Expected behavior**
The disk is added successfully and we don't see any errors.

**Environment**
 - Harvester ISO version: master as at 2024-10-02
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized

**Additional context**
I thought I'd fixed this with https://github.com/harvester/node-disk-manager/pull/142, but apparently I didn't :-/

**Comment by khushboo-rancher** [comment]
This can be tested together with https://github.com/harvester/harvester/issues/5274

**Comment by albinsun** [comment]
Test PASS on `v1.4.0-rc3`, does not observe webhook error.

## Environment
* `harvester-v1.4.0-rc3`
  * Profile: 3 nodes witness AMD64 QEMU/KVM
  * ui-source: `Auto`

## Verification
1. <details open>
   <summary> :green_circle: <i>node-1</i> (LHv2 engine enabled) can attach disk using Longhorn V2 (CSI) Provisioner.
   </summary>
   
   * Provision extra disk as LHv2
     ![image](https://github.com/user-attachments/assets/4969d7af-c878-48cc-bc0d-31c2a20b7ebb)
   * Use the Longhorn GUI to verify that the disk is successfully added to the node
   * **Longhorn** => **Node**, the LHv2 disks should show as "block" as opposed to "filesystem" (the latter is for V1).
     ![image](https://github.com/user-attachments/assets/cf257711-3205-4d65-ad33-b075fd6e466c)
   </details>
