### ISSUE TITLE
[FEATURE] Add warning on the installer when a NIC can't get IP from its DHCP server

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#671]
**Is your feature request related to a problem? Please describe.**
When a physical NIC is failed to request an IP from its DHCP server during the Harvester installation, the commnatcl in k3os will allocate a fallback IP with 169.250.x.x, however, this is not obvious to the common users and they may continue to process the Harvester installation with this bad IP address, as a result, the k3s cluster will not work as expected.

**Describe the solution you'd like**
Would be better to add a warning on the installer when a NIC can't get IP from its DHCP server.

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc3

![image](https://user-images.githubusercontent.com/19684717/115483296-14e68800-a283-11eb-88bf-d0e630adc927.png)

![image](https://user-images.githubusercontent.com/19684717/115483302-16b04b80-a283-11eb-9417-74dd8e25e9bd.png)
