### ISSUE TITLE
[BUG] All Backups are lost in the Backup Target if the NFS Service Disconnects and Reconnects again

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6716]
**Describe the bug**
All backups are removed in the Backup Target if the NFS Service disconnects and reconnects again

Please refer to LH issue [#9530](https://github.com/longhorn/longhorn/issues/9530) for more details

**Additional context**
- This will be fixed by LH issue [#9530](https://github.com/longhorn/longhorn/issues/9530)
- LEP reference https://github.com/longhorn/longhorn/pull/9570

**Comment by WebberHuang1118** [comment]
I checked this is fixed by LH issue https://github.com/longhorn/longhorn/issues/9530 with LH v1.7.2-rc1 https://github.com/harvester/harvester/pull/6753

**Comment by brandboat** [comment]
Test OK, will close the issue.

# Environment
- ipxe 3 nodes (8c/16G/250GB)
- v1.4.0-rc4
- NFS (cmd as below)
  ```sh
  docker run -d \
    --name nfs-server \
    --privileged \
    --network host \
    -v /tmp/nfs:/nfsshare \
    -e SHARED_DIRECTORY=/nfsshare \
    itsthenetwork/nfs-server-alpine:latest
  ```

# Test Plan
follow test steps in https://github.com/longhorn/longhorn/issues/9530#issue-2549850846
- Setting [Backupstore Poll Interval](https://longhorn.io/docs/1.7.1/references/settings/#backupstore-poll-interval) as 30 seconds
- Create VM `test2`
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/2a51447e-909b-406e-b7ab-daf8686210ea">

- Taking the first VM (volume) backup, and waiting until it completes
- Taking the second VM (volume) backup, and waiting until it completes
- Stopping the NFS Service
- Taking the third VM (volume) backup, and waiting until it fails
- Taking the fourth VM (volume) backup, and waiting util it fails
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/8420139b-e279-4c91-8069-019349d556d6">

- Starting the NFS Service
- Checking if all LH backups are still exists (both in the backup target and the LH backup CR)
- And after waiting a few minutes, all backups are in completed status (include backup 3 & 4)
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/09bb3f07-df15-460f-b782-aecec811066c">

  vmbackups
  ```
  harvester-node-0:~ # kubectl get vmbackups -A
  NAMESPACE   NAME   SOURCE_KIND      SOURCE_NAME   TYPE     READY_TO_USE   AGE     ERROR
  default     1      VirtualMachine   vm2           backup   true           41m
  default     2      VirtualMachine   vm2           backup   true           41m
  default     3      VirtualMachine   vm2           backup   true           9m24s
  default     4      VirtualMachine   vm2           backup   true           9m19s
  ```
  
  LH backups
  ```
  harvester-node-0:~ # kubectl get backups -A
  NAMESPACE         NAME                      SNAPSHOTNAME                                    SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE       LASTSYNCEDAT
  longhorn-system   backup-0ddb64b5f31d4308   snapshot-39979d4f-8911-4d56-b8c5-0055833187f4   994050048      2024-10-29T08:13:54Z   Completed   2024-10-29T08:17:50Z
  longhorn-system   backup-31d20887c40b4899   snapshot-42170f2e-2c68-4357-92c1-44cc20a35747   2097152        2024-10-29T07:41:15Z   Completed   2024-10-29T08:17:24Z
  longhorn-system   backup-58ab8219005d4ced   snapshot-1097006c-e9f1-4b35-921f-c41918f27952   994050048      2024-10-29T08:18:36Z   Completed   2024-10-29T08:18:40Z
  longhorn-system   backup-98eb576ab5f64423   snapshot-6f45b195-252a-45d1-99de-c5a9ab731ac7   12582912       2024-10-29T07:41:29Z   Completed   2024-10-29T08:17:24Z
  ```
  
  NFS
  ```
  ➜ brandboat@suse  ~  sudo ls -la /tmp/nfs/harvester/vmbackups/default
  [sudo] password for root:
  total 16
  drwx------ 2 root root  120 Oct 29 16:22 .
  drwx------ 3 root root   60 Oct 29 15:34 ..
  -rw-r--r-- 1 root root 2980 Oct 29 15:41 1.cfg
  -rw-r--r-- 1 root root 2980 Oct 29 15:41 2.cfg
  -rw-r--r-- 1 root root 2980 Oct 29 16:22 3.cfg
  -rw-r--r-- 1 root root 2980 Oct 29 16:18 4.cfg
  ```
