### ISSUE TITLE
[BUG] Cannot Clean Up Orphaned USB Devices, Re-Use Of USB Device Fails Entirely, and VM eventually left barren no USB device fufilling it's purpose

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6720]
### Describe the bug
A user can not clean up orphaned USB devices.
A user can not sufficently change the location of the USB device on the integrated USB controller(s) without having substaintial consequences, eventually the USB device will no longer be able to be attached to the VM.

### To Reproduce
Steps to reproduce the behavior.
Pre-Reqs: Testing was done with a "non-mass-storage" USB Device, IE: Webcam or some other possible variant 

**_Stage 1:_**
1. Have a USB device plugged into a node
1. Use that device for a VM
1. Power up that VM with that device, validate it works
1. Power down the VM
1. Power down the Node that has the USB device
1. Remove the USB device from the Node
1. Power back up the Node
1. Wait till node connects back to cluster, re-attach the USB device to another location on the Node
1. Edit the configuration of the VM, to remove the USB device, save the configuration
1. Enable pass-through to the new USB device from USB Devices
1. Attempt to disable passthrough of the Old USB Device
1. It will fail
1. Boot the VM with the new USB device, see if that succeeds

_**Stage 2:**_
1. Power off Any VM that is using the USB device 
1. Remove the USB Device from the VM
1. Place the USB Device somewhere else, IE: another USB port || OR || Alternatively, remove the device from the same port, wait ~15 sec, plug the device back in ...new device should be within index page of USB Devices referencing the same device
1. Note in USB Devices, a new possible USB Device address is detected
1. Enable Pass through on that USB device
1. Once you have roughly 3 USB Devices that all have the same name, IE: referencing all the same Device, make sure they are all "enabled"
1. Then try to attach and run the VM with each one of the 3 devices
1. The VM will not start, the VM will not be able to schedule the KubeVirt Pod

**_Stage 3:_**
- just observer enabling passthrough on a USB device, removing that USB device from the Node, that Enabling passthrough of the new USB device that is displayed when re-attaching the same USB device back to the node
- Note that you can't delete / remove any of the USB devices (that have the same name) ...as you'll be met with:
```bash

Error disabling passthrough on node6-test-046d-085c-004003

You cannot disable passthrough on a device claimed by another user. 
```

### Expected Behavior
- Better handling of orphaned USB Passthrough Devices that were enabled
- Better handling of removing & re-attaching of the same USB device accross mulitple or the-single port

### Support Bundle
[supportbundle_b5f37a65-549a-4700-9544-fe0863fec276_2024-10-07T18-57-17Z.zip](https://github.com/user-attachments/files/17283359/supportbundle_b5f37a65-549a-4700-9544-fe0863fec276_2024-10-07T18-57-17Z.zip)

### Environment
 - Harvester ISO version: v1.4.0-rc1
 - Underlying Infrastructure: bare-metal, hp dl160 gen 9

### Additional Context

For reference, here are some of the DMESG logs from the node directly:
```bash
[  117.755120] sd 9:0:0:1: Power-on or device reset occurred
[  117.755235] sd 9:0:0:1: [sde] 104857600 512-byte logical blocks: (53.7 GB/50.0 GiB)
[  117.755283] sd 9:0:0:1: [sde] Write Protect is off
[  117.755286] sd 9:0:0:1: [sde] Mode Sense: 69 00 10 08
[  117.755375] sd 9:0:0:1: [sde] Write cache: disabled, read cache: enabled, supports DPO and FUA
[  117.771759] sd 9:0:0:1: [sde] Attached SCSI disk
[  118.437920] r8169 0000:08:00.0 enp8s0: Link is Up - 1Gbps/Full - flow control off
[  118.679218] r8169 0000:09:00.0 enp9s0: Link is Up - 1Gbps/Full - flow control off
[  125.726777] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  146.889809] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  149.403336] usb 3-9: new high-speed USB device number 3 using xhci_hcd
[  151.789183] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[  151.789192] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[  151.789194] usb 3-9: Product: C922 Pro Stream Webcam
[  151.789196] usb 3-9: SerialNumber: FFDEAE4F
[  151.918266] mc: Linux media interface: v0.10
[  152.041252] videodev: Linux video capture interface: v2.00
[  152.209935] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[  152.211089] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input8
[  152.211180] usbcore: registered new interface driver uvcvideo
[  152.572966] usbcore: registered new interface driver snd-usb-audio
[  153.944345] EXT4-fs (sdd): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[  154.087543] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  155.226075] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  155.630514] EXT4-fs (sdc): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[  155.663092] VFIO - User Level meta-driver version: 0.3
[  155.925708] EXT4-fs (sde): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[  166.091112] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  168.473333] Initializing XFRM netlink socket
[  170.411962] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  175.389698] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  198.958030] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  286.954424] scsi host10: iSCSI Initiator over TCP/IP
[  286.962039] scsi 10:0:0:0: RAID              IET      Controller       0001 PQ: 0 ANSI: 5
[  286.962977] scsi 10:0:0:0: Attached scsi generic sg10 type 12
[  286.963202] scsi 10:0:0:1: Direct-Access     IET      VIRTUAL-DISK     0001 PQ: 0 ANSI: 5
[  286.964193] sd 10:0:0:1: Attached scsi generic sg11 type 0
[  286.964307] sd 10:0:0:1: Power-on or device reset occurred
[  286.964432] sd 10:0:0:1: [sdf] 146800640 512-byte logical blocks: (75.2 GB/70.0 GiB)
[  286.964509] sd 10:0:0:1: [sdf] Write Protect is off
[  286.964513] sd 10:0:0:1: [sdf] Mode Sense: 69 00 10 08
[  286.964695] sd 10:0:0:1: [sdf] Write cache: disabled, read cache: enabled, supports DPO and FUA
[  286.990645]  sdf: sdf1 sdf2
[  286.990912] sd 10:0:0:1: [sdf] Attached SCSI disk
[  294.869027] loop1: detected capacity change from 0 to 146800640
[  295.146266] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  295.221055] extra-br: port 2(vetha4560941) entered blocking state
[  295.221061] extra-br: port 2(vetha4560941) entered disabled state
[  295.221147] device vetha4560941 entered promiscuous mode
[  295.221251] extra-br: port 2(vetha4560941) entered blocking state
[  295.221260] extra-br: port 2(vetha4560941) entered forwarding state
[  297.313914] extra-br: port 2(vetha4560941) entered disabled state
[  297.314025] 37a8eec1ce1-nic: renamed from pod37a8eec1ce1
[  297.349198] k6t-37a8eec1ce1: port 1(37a8eec1ce1-nic) entered blocking state
[  297.349210] k6t-37a8eec1ce1: port 1(37a8eec1ce1-nic) entered disabled state
[  297.349310] device 37a8eec1ce1-nic entered promiscuous mode
[  297.350678] IPv6: ADDRCONF(NETDEV_CHANGE): 37a8eec1ce1-nic: link becomes ready
[  297.350711] k6t-37a8eec1ce1: port 1(37a8eec1ce1-nic) entered blocking state
[  297.350714] k6t-37a8eec1ce1: port 1(37a8eec1ce1-nic) entered forwarding state
[  297.350730] extra-br: port 2(vetha4560941) entered blocking state
[  297.350732] extra-br: port 2(vetha4560941) entered forwarding state
[  297.490485] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered blocking state
[  297.490492] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered disabled state
[  297.490556] device tap37a8eec1ce1 entered promiscuous mode
[  297.490737] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered blocking state
[  297.490740] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered forwarding state
[  298.328382] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered disabled state
[  300.386338] IPv6: ADDRCONF(NETDEV_CHANGE): tap37a8eec1ce1: link becomes ready
[  300.386383] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered blocking state
[  300.386386] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered forwarding state
[  300.844283] usb 3-9: reset high-speed USB device number 3 using xhci_hcd
[  306.328088] usb 3-9: reset high-speed USB device number 3 using xhci_hcd
[  318.995763] usb 3-9: reset high-speed USB device number 3 using xhci_hcd
[  326.531592] usb 3-9: reset high-speed USB device number 3 using xhci_hcd
[  338.554940] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  497.572999] usb 3-9: reset high-speed USB device number 3 using xhci_hcd
[  497.727104] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[  497.728264] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input9
[  497.748943] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered disabled state
[  507.380785] device tap37a8eec1ce1 left promiscuous mode
[  507.380831] k6t-37a8eec1ce1: port 2(tap37a8eec1ce1) entered disabled state
[  507.400890] device 37a8eec1ce1-nic left promiscuous mode
[  507.400941] k6t-37a8eec1ce1: port 1(37a8eec1ce1-nic) entered disabled state
[  507.421364] extra-br: port 2(vetha4560941) entered disabled state
[  507.537218] device vetha4560941 left promiscuous mode
[  507.537245] extra-br: port 2(vetha4560941) entered disabled state
[  524.887716] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
[  531.740293] usb 3-9: USB disconnect, device number 3
[  786.233113] usb 3-9: new high-speed USB device number 4 using xhci_hcd
[  788.611131] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[  788.611144] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[  788.611148] usb 3-9: Product: C922 Pro Stream Webcam
[  788.611152] usb 3-9: SerialNumber: FFDEAE4F
[  788.611751] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[  788.612937] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input10
[ 1747.706329] usb 3-9: USB disconnect, device number 4
[ 1751.630224] usb 3-9: new high-speed USB device number 5 using xhci_hcd
[ 1754.024184] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1754.024211] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1754.024215] usb 3-9: Product: C922 Pro Stream Webcam
[ 1754.024218] usb 3-9: SerialNumber: FFDEAE4F
[ 1754.024841] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1754.026156] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input11
[ 1779.929712] usb 3-9: USB disconnect, device number 5
[ 1784.537588] usb 3-9: new high-speed USB device number 6 using xhci_hcd
[ 1786.919527] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1786.919537] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1786.919539] usb 3-9: Product: C922 Pro Stream Webcam
[ 1786.919542] usb 3-9: SerialNumber: FFDEAE4F
[ 1786.920122] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1786.921317] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input12
[ 1790.437504] usb 3-9: USB disconnect, device number 6
[ 1794.597406] usb 3-9: new high-speed USB device number 7 using xhci_hcd
[ 1796.967324] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1796.967337] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1796.967342] usb 3-9: Product: C922 Pro Stream Webcam
[ 1796.967346] usb 3-9: SerialNumber: FFDEAE4F
[ 1796.967925] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1796.969134] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input13
[ 1797.833408] usb 2-1: USB disconnect, device number 2
[ 1799.677335] usb 3-9: USB disconnect, device number 7
[ 1803.621208] usb 3-9: new high-speed USB device number 8 using xhci_hcd
[ 1805.991206] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1805.991220] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1805.991225] usb 3-9: Product: C922 Pro Stream Webcam
[ 1805.991228] usb 3-9: SerialNumber: FFDEAE4F
[ 1805.991860] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1805.993322] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input14
[ 1807.182074] usb 3-9: USB disconnect, device number 8
[ 1810.885104] usb 3-9: new high-speed USB device number 9 using xhci_hcd
[ 1813.255009] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1813.255023] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1813.255028] usb 3-9: Product: C922 Pro Stream Webcam
[ 1813.255031] usb 3-9: SerialNumber: FFDEAE4F
[ 1813.255615] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1813.256804] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input15
[ 1937.474743] usb 3-9: USB disconnect, device number 9
[ 1941.410629] usb 3-9: new high-speed USB device number 10 using xhci_hcd
[ 1943.780618] usb 3-9: New USB device found, idVendor=046d, idProduct=085c, bcdDevice= 0.16
[ 1943.780632] usb 3-9: New USB device strings: Mfr=0, Product=2, SerialNumber=1
[ 1943.780636] usb 3-9: Product: C922 Pro Stream Webcam
[ 1943.780640] usb 3-9: SerialNumber: FFDEAE4F
[ 1943.781281] usb 3-9: Found UVC 1.00 device C922 Pro Stream Webcam (046d:085c)
[ 1943.782470] input: C922 Pro Stream Webcam as /devices/pci0000:00/0000:00:14.0/usb3/3-9/3-9:1.0/input/input16
[ 2161.699613] IPv6: ADDRCONF(NETDEV_CHANGE): eth0: link becomes ready
```

![Screenshot from 2024-10-07 11-57-00](https://github.com/user-attachments/assets/2b927c27-95db-4a25-b29c-645aaceb06a4)
![Screenshot from 2024-10-07 11-56-37](https://github.com/user-attachments/assets/f281f048-be36-44be-8490-294edfbed74f)
![Screenshot from 2024-10-07 11-46-29](https://github.com/user-attachments/assets/bda61168-a3da-4b04-9154-7eb580081916)
![Screenshot from 2024-10-07 11-45-55](https://github.com/user-attachments/assets/ce483042-0a37-41e8-b446-729197b65fdf)

**Comment by Yu-Jack** [comment]
Hi @irishgordo. Because @ibrokethecloud and I re-tagged the harvester/pcidevices last week and we tagged a new v0.4.1 yesterday, so the updated codes would not be v1.4.0-rc1. I really apologize for this. However, you can do following changes to get new codes.

1. Change image of daemonset/harvester-pcidevices-controller to `rancher/harvester-pcidevices:v0.4.1`
2. Find clusterrole/harvester-pcidevices-controller, add following permissions.
```diff
resources:
 - virtualmachines
+- virtualmachineinstances
verbs:
 - get
 - list
 - watch
+- update
```

**To Stage1**

You should be able to disable the old USB devices after bumping. However, after disabling the old USB devices, those old USB devices still exist. But, they shouldn't exist actually. I'll improve this flow, deleting them after disabling them if they don't exist.

For other stages, I'll update later.

**Comment by Yu-Jack** [comment]
**To Stage3**

After bumping to v0.4.1, you're able to delete them. The reason you can't delete is that we check `userName` if it matches the `usbdeviceclaim` owner or not. But, in your environment, `userName` is in `status.userName`, which is not correct. It should be `spec.userName`. So, it should be addressed after bumping.

**Comment by Yu-Jack** [comment]
**To Stage2**

I think it's an expected behavior. In general flow, we expect users do:

1. Plugin USB device
2. Enable USB device
3. Attach USB device to VM spec
4. Detach USB device from VM spec
5. Disable USB device
6. Unplug USB device

But, we can't force users to follow above steps, so they might just remove USB device without disabling or detaching . I think it's weird that we help users to remove old enabled USB devices after they re-plugin. In other words, if this USB device is enabled and attached to a VM, we can't directly remove the USB device from `spec` or USB device list after they re-plugin the USB device.

I think we should add more warning and tutor on https://docs.harvesterhci.io/v1.4/advanced/addons/pcidevices#limitations. After all, we don't support re-plugin without creating a new `usbdeviceclaim` (because its `devicePath` is changed).

**Comment by Yu-Jack** [comment]
After https://github.com/harvester/pcidevices/pull/94 is merged, there is still a case we should pay attention to.

Steps:

1. Plugin USB device.
2. Enable it and attach it to a VM.
3. Unplug it directly without disabling and detaching.
4. Plugin it back.

It shows two USB devices on the list even I only have one USB device. This happens because the webhook validator blocks the deletion request in step 3, as the USB device is still present in the VM's spec. Users should disable device before unplug it. I'll add a warning message on the documentation.

**Comment by Yu-Jack** [comment]
Hi @irishgordo , the new change is already on the v1.4.0-rc2.

First demo is that system helps to remove unattached and enabled USB device when that USB device is removed without disabling.

https://github.com/user-attachments/assets/8dd0bbbb-1161-459d-9678-4d370dc538bf

Second demo is that system marks old attached and enabled USB device as orphaned when re-plugin the USB device back. Then, we remove it from the VM and disable it.

https://github.com/user-attachments/assets/022f7453-e81a-4fc4-848c-e70370f7caee

**Comment by irishgordo** [comment]
Thanks for the fix @Yu-Jack :smile: :+1: 
This all looks good with v1.4.0-rc2 :smile: :+1: 
I'll go ahead and close this out
![Screenshot from 2024-10-14 20-06-27](https://github.com/user-attachments/assets/1cc1fb07-be23-4e11-967d-5f159bee7408)

**Comment by Yu-Jack** [comment]
> Thanks for the fix @Vicente-Cheng 😄 👍 This all looks good with v1.4.0-rc2 😄 👍 I'll go ahead and close this out !

@irishgordo I'm guessing you're talking about me 🤣

**Comment by irishgordo** [comment]
> > Thanks for the fix @Vicente-Cheng 😄 👍 This all looks good with v1.4.0-rc2 😄 👍 I'll go ahead and close this out !
> 
> @irishgordo I'm guessing you're talking about me 🤣

:sweat_smile: :laughing:  - yes :smile:  - my eyes played tricks on me as I had 4045 open in another window :sweat_smile:
