### ISSUE TITLE
[BUG] Restore backup to new cluster doesn't work for backups created with v1.3.2 and restored to v1.4.0

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6721]
**Describe the bug**

You can't restore backups from a v1.3.2 cluster to a new v1.4.0-rc1 cluster
**To Reproduce**
1. Create a VM with 3 chained backups on a v1.3.2 cluster with a backup target of either NFS or S3
2. Create a new cluster with v1.4.0-rc1
**Expected behavior**

You should be able to restore to the new cluster
**Support bundle**

[s3-backup-v132-to-v140-rc1-supportbundle_0ee0c1a3-c1c6-4f70-9267-e1e6b211b1f7_2024-10-07T22-38-03Z.zip](https://github.com/user-attachments/files/17285264/s3-backup-v132-to-v140-rc1-supportbundle_0ee0c1a3-c1c6-4f70-9267-e1e6b211b1f7_2024-10-07T22-38-03Z.zip)
[nfs-backup-v132-to-v140-rc1-supportbundle_3518d480-aff7-4e8d-8fc9-c80bd93b3831_2024-10-07T19-17-20Z.zip](https://github.com/user-attachments/files/17285265/nfs-backup-v132-to-v140-rc1-supportbundle_3518d480-aff7-4e8d-8fc9-c80bd93b3831_2024-10-07T19-17-20Z.zip)

**Environment**
 - Harvester ISO version: v1.3.2 -> v1.4.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): three node libvirt clusters

**Additional context**

This works when restoring from v1.4.0-rc1 to new v1.4.0-rc1 clusters.

On clusters that where the backups were created on v1.3.2 and restored to v1.4.0-rc1 I was unable to restore on either NFS or S3 backup targets, but the behavior was different.
- On NFS backups I wasn't able to see the backups in the backup target after adding the NFS backup target to the new cluster. I was able to see the backup targets on v1.3.2 when the backups were created with v1.4.0
- On S3 backups I was able to see the backups, but they failed to restore with a error `Storageclass.storage.k8s.io "longhorn-image-lmpt8" not found`

![Screenshot_20241007_154213](https://github.com/user-attachments/assets/0282c853-8ae1-485d-b0da-e380ff4d1f9c)
![Screenshot_20241007_154207](https://github.com/user-attachments/assets/bbca4825-6b7d-4a71-9675-a66e1e4a459a)

**Comment by FrankYang0529** [comment]
Hi @noahgildersleeve, I think this is expected behavior, because this feature is in v1.4.0. The v1.3.2 doesn't upload related data to backup target, so v1.4.0 can't get required data. I can add this requirement to the document, so users don't misunderstand it. Thanks.

**Comment by bk201** [comment]
@noahgildersleeve can you help check PoAn's [comment](https://github.com/harvester/harvester/issues/6721#issuecomment-2398505724) and see if it makes sense? Thank you!

**Comment by noahgildersleeve** [comment]
I'm closing this as working as designed. It looks like restoring to a new cluster on clusters are v1.3.2 (old cluster) -> v1.4.0 (new cluster). We might consider adding a note that if a customer is thinking of doing this to be sure to create a new backup after the upgrade to v1.4.0.

**Comment by bk201** [comment]
We should add a release note to mention the behavior. @FrankYang0529 Is there a doc I can link to that describes this?

**Comment by FrankYang0529** [comment]
Yes, this doc PR https://github.com/harvester/docs/pull/647. The document link needs to wait for PR merged.
