### ISSUE TITLE
[BUG] Improved Harvester Maintenance Mode broken

### ISSUE THREAD

**Issue by votdev** [harvester/harvester#6727]
**Describe the bug**
The [Improving Harvester Maintenance Mode](https://github.com/harvester/harvester/pull/5328) feature has been broken by another [PR](https://github.com/harvester/harvester/pull/5991) [by changing the logic](https://github.com/harvester/harvester/pull/5991/files#diff-668050f872b498d877736c7b008f2bdf89bbd48800f9ef83d2d3da8e57a1d872L147) which is responsible for shutting down VMs.

The for loop which iterates over the VMs to be shut down was probably mistakenly pulled in an if condition, which is unfortunately wrong and makes the previous logic inoperable.

**To Reproduce**
Replay the [test cases](https://github.com/harvester/harvester/issues/5069#issuecomment-2367154971).

**Expected behavior**
The Improving Harvester Maintenance Mode [should work as expected](https://github.com/harvester/harvester/pull/5328#issue-2176203298).

**Environment**
 - Harvester ISO version: v1.4.0-rc1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ixpe 3 node cluster

**Comment by tserong** [comment]
(apologies, that close shouldn't have happened - my bad)

**Comment by w13915984028** [comment]
Test report: **PASS**

test steps: refer: https://github.com/harvester/harvester/pull/5328#issue-2176203298

---
:green_circle: **Case 1: Label `harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterDisable`**

 Add label to VM and start VM
```
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterDisable
    harvesterhci.io/os: linux
```
![image](https://github.com/user-attachments/assets/c5bf976e-f551-4b5f-96b5-807640913172)

put node to `maintenance mode`:
![image](https://github.com/user-attachments/assets/db660227-f386-4afd-bb58-69a1cd85d843)

![image](https://github.com/user-attachments/assets/fe081af6-c3e9-4311-9e60-188bb454fe77)

vm becomes off:
![image](https://github.com/user-attachments/assets/2f327844-1f96-469f-bc9d-b65b307473af)

Disable `maintenance mode`
![image](https://github.com/user-attachments/assets/967ac925-6d29-481a-a486-e47640d7059f)

VM starts
![image](https://github.com/user-attachments/assets/408baa00-8ada-4e20-96ec-1cdb27aa79d4)

and be Running, still on the original node
![image](https://github.com/user-attachments/assets/a6126430-41fb-4cb5-9e00-89cb13c95bfe)

---

:green_circle:**Case 2: Label `harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterEnable`**

put node to `maintenance mode`:
![image](https://github.com/user-attachments/assets/91972609-1b36-47f2-95e9-b934ed9db7c8)

vm stopped and starts:
![image](https://github.com/user-attachments/assets/36b9a804-18c5-4fbc-bd9f-9ed8a8bfb025)

VM runs on some other node
![image](https://github.com/user-attachments/assets/fbd304cf-b346-455a-bc1b-64e08b1a9f43)

---

:green_circle: **Case 3: Label `harvesterhci.io/maintain-mode-strategy: Shutdown`**

put node to `maintenance mode`, VM is shutdown and becomes `Off`
![image](https://github.com/user-attachments/assets/fd622b74-cfe8-4ee5-90ff-d133995804cb)

disable `maintenance mode`, VM is still `Off`
![image](https://github.com/user-attachments/assets/7752a788-079d-4b10-9584-f6547bfbfff1)

---

:green_circle: **Case 4: Label `harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterDisable`**
After the VM is Shutdown when put node to `maintenance mode`, the vmi has annotation `harvesterhci.io/maintain-mode-strategy-node-name`

```
  annotations:
    harvesterhci.io/maintain-mode-strategy-node-name: harv2
...
  labels:
    harvesterhci.io/creator: harvester
    harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterDisable
    harvesterhci.io/os: linux
```

Manually delete the `harvesterhci.io/maintain-mode-strategy-node-name: harv2` annotation, then disable `maintenance mode`, VM is still `Off`

![image](https://github.com/user-attachments/assets/5c1a80a0-0946-4edb-b57d-990f093b97ac)

no similar log `restarting the VM that was` is foundd on Harvester pod.

---

:green_circle: **Case 5: Label `harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterDisable`**
After the VM is Shutdown when put node to `maintenance mode`, the vmi has annotation `harvesterhci.io/maintain-mode-strategy-node-name`
![image](https://github.com/user-attachments/assets/840e3899-4222-467f-bd9e-6ea9e59f24bf)

After delete the node:
The VM is scheduled to another node and runs, no `harvesterhci.io/maintain-mode-strategy-node-name` annotation.
![image](https://github.com/user-attachments/assets/3261396d-5252-4d98-93f8-10cbe50bea6e)

```
    annotations:
      harvesterhci.io/timestamp: "2024-10-25T14:20:01Z"
      harvesterhci.io/vmRunStrategy: RerunOnFailure
..
    creationTimestamp: "2024-10-24T12:41:04Z"
...
    labels:
      harvesterhci.io/creator: harvester
      harvesterhci.io/maintain-mode-strategy: ShutdownAndRestartAfterEnable
      harvesterhci.io/os: linux
    name: vm1-running

**Comment by w13915984028** [comment]
This feature functions well, thanks @votdev .
