### ISSUE TITLE
[BUG] installer console exits on network configuration page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#673]
**Version**
master 0409

**To Reproduce**
1. Boot from ISO image
2. Select Join a cluster.
3. Select the device target
4. Do not input anything in the hostname field and click arrow-down key.

**Result**
console exit and the shell shows up.
Logs:
![image](https://user-images.githubusercontent.com/5697937/114135308-aaa51d80-993b-11eb-8704-09b4fde8fa30.png)

**Comment by futuretea** [comment]
Caused by a small screen resolution

**Comment by weihanglo** [comment]
Cannot reproduce this bug on master branch ISO downloaded at 2021-06-15T17:50:23Z. I can't skip step 4 without any input on hostname field. Is the issue still relevant?

**Comment by gitlawr** [comment]
I'm not able to reproduce now
