### ISSUE TITLE
[BUG] ssh key from template does not display in VM creation page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#674]
**To Reproduce**
1. Create an ssh key
2. Create a VM template with the ssh key
3. Create a VM, use the template.

**Expected behavior**
Display the ssh key from template in VM creation page.

**Result**
The ssh key option is empty after the template is used.
The ssh key is included in the VM spec after creation, and it shows up when you edit the config of the VM.

**Comment by TangStone** [comment]
### Validation passed in version v0.2.0-rc2
**Steps**

1. create an ssh key
![image](https://user-images.githubusercontent.com/15829074/115192163-03836b80-a11d-11eb-84b1-266d6d7331dc.png)
2. Create a VM template with the ssh key
![image](https://user-images.githubusercontent.com/15829074/115192242-21e96700-a11d-11eb-8cf7-d0ced122cc81.png)
3. Create a VM, use the template,vm created successfully
![image](https://user-images.githubusercontent.com/15829074/115192286-32014680-a11d-11eb-9612-24a4d6330d7a.png)
![image](https://user-images.githubusercontent.com/15829074/115219155-ced1dd00-a139-11eb-9559-684fa34f6e2f.png)
4. Create vm directly from template, vm created successfully
![image](https://user-images.githubusercontent.com/15829074/115219596-43a51700-a13a-11eb-859d-6b222e333863.png)
![image](https://user-images.githubusercontent.com/15829074/115219835-77803c80-a13a-11eb-8cb4-c57003fd8ef1.png)
![image](https://user-images.githubusercontent.com/15829074/115219863-7fd87780-a13a-11eb-96e2-1cdd0cde1dd7.png)
