### ISSUE TITLE
[BUG] Harvester after upgrade to v1.4.0-rc2 fails to bring back mcc-harvester bundle, harvester-network-controller-manager pods stuck in error and crashloop backoff

### ISSUE THREAD

**Issue by irishgordo** [harvester/harvester#6747]
**Describe the bug**
This likely will be encountered from v1.3.2 -> v1.4.0-rc2.
But has been only currently experienced from:
- v1.4.0-rc1 -> v1.4.0-rc1
- v1.4.0-rc2 -> v1.4.0-rc2

Something expereience with in #3059 -> @starbops [also experienced](https://github.com/harvester/harvester/issues/3059#issuecomment-2401779176).

**To Reproduce**
Steps to reproduce the behavior (pxe or baremetal):
1. have a 2 node or greater cluster at v1.4.0-rc2
1. upgrade to v1.4.0-rc2 (same version upgrade)
1. allow upgrade to complete
1. check bundles -> mcc-harvester isn't happy because harvester-network-controller-manager pods are stuck in error and backoff state

**Expected behavior**
Upgrade to not break:
- mcc-harvester bundle
- replicaset harvester-network-controller-manager-uuid
- deployment harvester-network-controller-manager
Not see errors in pods of replicaset for deployment harvester-network-controller-manager :
```
harvester-network-controller-manager-67dc895674-jpr7w F1009 23:24:47.313805       1 vlan.go:148] disable net.bridge.bridge-nf-call-iptables failed, error: open /proc/sys/net/bridge/bridge-n
f-call-iptables: read-only file system                                                                                                                                                       
harvester-network-controller-manager-67dc895674-pbnqj F1009 23:23:29.728257       1 vlan.go:148] disable net.bridge.bridge-nf-call-iptables failed, error: open /proc/sys/net/bridge/bridge-n
f-call-iptables: read-only file system        
```

**Support bundle**
[supportbundle_4e913967-2061-4e17-8f4c-a8a1c7ca7ae7_2024-10-09T23-22-41Z.zip](https://github.com/user-attachments/files/17319857/supportbundle_4e913967-2061-4e17-8f4c-a8a1c7ca7ae7_2024-10-09T23-22-41Z.zip)

**Environment**
 - Harvester ISO version: v1.4.0-rc2
 - Underlying Infrastructure: qemu\kvm or baremetal -> both replicatable 

**Additional context**
![Screenshot from 2024-10-09 16-21-22](https://github.com/user-attachments/assets/72818e27-d0b9-4411-b002-2d65abfb77f5)
![Screenshot from 2024-10-09 16-19-47](https://github.com/user-attachments/assets/b862b578-a765-47a8-85de-38f068d21492)
![Screenshot from 2024-10-09 16-19-10](https://github.com/user-attachments/assets/3e77d62b-3871-4f83-909e-42ecb04b85ff)
![Screenshot from 2024-10-09 16-18-48](https://github.com/user-attachments/assets/a8857c4b-de2a-41de-a325-f93d9375fb29)
![Screenshot from 2024-10-09 16-18-32](https://github.com/user-attachments/assets/92cdb7c5-2505-451c-bf5e-dac6a369fc34)

**Comment by starbops** [comment]
This might relate to the change introduced in harvester/network-controller-harvester#83.

**Comment by mingshuoqiu** [comment]
What's the output of `sysctl net.bridge.bridge-nf-call-iptables`?
How many times does the `disable net.bridge.bridge-nf-call-iptables failed, error: open /proc/sys/net/bridge/bridge-n
f-call-iptables: read-only file system` show?

**Comment by irishgordo** [comment]
@mingshuoqiu - I unfortunately needed to use the hardware that the cluster was running.
But the:
```
disable net.bridge.bridge-nf-call-iptables failed, error: open /proc/sys/net/bridge/bridge-n f-call-iptables: read-only file system
```
I believe showed once before the pod crashed and restarted?  I can't recall exactly.
But the deployment's replica set kept trying to start the pods, so the pods would continously try to come up, each time met with that error.

**Comment by starbops** [comment]
Normally, host-specific operations should be done by the agent pod, not the manager pod. So the error message appeared in the manager pods is just not right.

**Comment by starbops** [comment]
Note: Even in a newly provisioned v1.4.0-rc2 cluster, restarting the `harvester-network-controller-manager` deployment or simply killing off the pod causes the newly spawned pods to run into the CrashLoopBackOff state with the exact same error message.

**Comment by starbops** [comment]
Workaround: run `sudo sysctl -w net.bridge.bridge-nf-call-iptables=0` on each node. The manager pods will be back in a short time.

---

You won't hit this issue for clusters upgrading from v1.3.2 and having at least one new cluster network created before the upgrade.

**Comment by irishgordo** [comment]
@mingshuoqiu thank you for the fix :smile: :+1: 
Validated on  Version: v1.4-1856e9dc-head  w/ 2 nodes -> also upgrade to  Version: v1.4-1856e9dc-head  that there were no issues.  Restarting the network controller manager deployment also doesn't show any issues in the logs.  The bundles all look great after upgrade too :smile: .
This looks good :+1: 
I'll go ahead and close this out :+1: 
![Screenshot from 2024-10-21 17-56-28](https://github.com/user-attachments/assets/06d8ddb0-4d75-4d7d-8ae7-780fcd33b4ab)
![Screenshot from 2024-10-21 17-54-34](https://github.com/user-attachments/assets/765ea50f-603f-419d-8285-2b88e05ec08f)
