### ISSUE TITLE
[BUG] Cannot use VM image if the URL is duplicate with another VM image.

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#676]
**Describe the bug**

**To Reproduce**
1. Create a VM image ubuntu1.
2. Provision a VM using ubuntu1 image.
3. Create another VM image ubuntu2 with the same URL as ubuntu1.
4. Provision a VM using ubuntu2 image.

**Expected behavior**
VM provisioning succeeds.

**Result**
The VM pod and relevant pvc stuck in pending status.

**Log**
```
$ kubectl describe pvc xxx
Events:
  Type     Reason                Age                   From                                                                                     Message
  ----     ------                ----                  ----                                                                                     -------
  Warning  ProvisioningFailed    9m26s (x2 over 13m)   driver.longhorn.io_csi-provisioner-fdd754d5d-2h5p5_d802f3f5-fcd6-42a7-b0e1-9222937da288  
failed to provision volume with StorageClass "longhorn-image-gjtk9": 
rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. 
Body: [message=unable to create backing image image-gjtk9 for URL http://172.16.4.20/os-images/ubuntu-18.04-server-cloudimg-amd64.img: 
backing image image-5rw9z is already created based on URL http://172.16.4.20/os-images/ubuntu-18.04-server-cloudimg-amd64.img,
code=Server Error, detail=] from [http://longhorn-backend:9500/v1/backingimages]
```

**Environment:**
 - Harvester ISO version: master-621eedd7-head(0409)
 - Installation Mode: ISO

**Comment by gitlawr** [comment]
cc @shuo-wu seems like a limitation to use the same URL in different backing images

**Comment by shuo-wu** [comment]
Longhorn won't create a new backing image if the URL is already used by an existing backing image. 

If this check is unnecessary, I can remove it.

**Comment by guangbochen** [comment]
Yes please remove this logic since we won't block a user from creating a new image from the same URL since different users might upload the same file @shuo-wu .

**Comment by shuo-wu** [comment]
The fix is the commit `Allow creating multiple backing images with the same URL` in this PR:
https://github.com/longhorn/longhorn-manager/pull/869

**Comment by guangbochen** [comment]
we should be able to verify this after bump the longhorn to https://github.com/longhorn/longhorn/releases/tag/v1.1.1-rc2.

**Comment by TangStone** [comment]
Validation passes in version master-64e4d950-head
1. Create a VM image ubuntu1.
![image](https://user-images.githubusercontent.com/15829074/115981816-3e781a00-a5c9-11eb-8227-17f2f574b910.png)
2. Provision a VM using ubuntu1 image.
![image](https://user-images.githubusercontent.com/15829074/115981840-68c9d780-a5c9-11eb-8edb-5bd1849134bb.png)
3. Create another VM image ubuntu2 with the same URL as ubuntu1.
![image](https://user-images.githubusercontent.com/15829074/115981818-459f2800-a5c9-11eb-9e7e-5a29a64820c9.png)
4. Provision a VM using ubuntu2 image.
![image](https://user-images.githubusercontent.com/15829074/115981865-86973c80-a5c9-11eb-8ec8-39800440a4ba.png)
