### ISSUE TITLE
[BUG] Fail to import harvester-v1.4.0-rc2 to rancher-v2.9.3-alpha4

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6760]
**Describe the bug**
Fail to import harvester-v1.4.0-rc2 to rancher-v2.9.3-alpha4
Hit on both AMD64 and ARM64 env. but with different symptoms.

**To Reproduce**
1. Setup single node harvester-v1.4.0-rc2 
2. Setup rancher-v2.9.3-alpha4
3. Rancher => Virtualization Management => Import Existing => ... => Create
4. Follows instructions to import Harvester
   ![image](https://github.com/user-attachments/assets/748ce56c-0d4e-4760-9053-a9ab27f6fdc7)
5. Imported Harvester should be `Active` and can retrieve K8s version
   > :x: cluster stuck `Waiting` (`Waiting for API to be available`)
   ![image](https://github.com/user-attachments/assets/d4596797-8e4e-489f-961f-c15920dec62e)

**Expected behavior**
Imported Harvester should be `Active` and can retrieve K8s version

**Support bundle**
* support-bundle: [supportbundle_rancher293alpha4_2024-10-11T14-51-21Z.zip](https://github.com/user-attachments/files/17344215/supportbundle_rancher293alpha4_2024-10-11T14-51-21Z.zip)
* rancher2_logs: [rancher-2024-10-11_14_59_41.tar.gz](https://github.com/user-attachments/files/17344290/rancher-2024-10-11_14_59_41.tar.gz)

**Environment**
* Harvester
  * Version: v1.4.0-rc2
  * Profile: single node QEMU/KVM
  * ui-source: Auto
* _rancher-v2.9.3-alpha4_ [^1]
  * Profile: aarch64, Helm w/ _v1.29.9+k3s1_
  * cert-manager-v1.12.13 [^2]

**ARM64 Reproduce (with different symptoms)**
* cluster becomes `Unavailable` instead of `Waiting` on AMD64 env.
  * status
   ![image](https://github.com/user-attachments/assets/98d5f0d0-5e07-4515-b101-ca12619e5edf)
  * Debug Console
   ![image](https://github.com/user-attachments/assets/75488739-3358-492d-861a-51653ef85d80)
* support-bundle: [supportbundle_rancher293alpha4arm_2024-10-11T14-55-20Z.zip](https://github.com/user-attachments/files/17344263/supportbundle_rancher293alpha4arm_2024-10-11T14-55-20Z.zip)
* rancher2_logs: [arm-133-2024-10-11_15_07_01.tar.gz](https://github.com/user-attachments/files/17344354/arm-133-2024-10-11_15_07_01.tar.gz)

[^1]: https://ranchermanager.docs.rancher.com/v2.9/getting-started/installation-and-upgrade/install-upgrade-on-a-kubernetes-cluster
[^2]: https://cert-manager.io/docs/installation/kubectl/#1-install-from-the-cert-manager-release-manifest

**Comment by albinsun** [comment]
Retest works fine, decrease the severity and observe for few more runs.

**Comment by Yu-Jack** [comment]
I ran into similar issue, but I used rancher:v2.8.0 to import harvester-v1.4.0-rc2.

![image](https://github.com/user-attachments/assets/c2fcd2e6-c5ce-4f0e-92d6-4408ff23d7b6)

![image](https://github.com/user-attachments/assets/149b2931-c80b-43a4-ab8f-480bde8f3f11)

**Comment by bk201** [comment]
@a110605 Can you take a look at the issue description? Somehow it's loading a v1.0.3 assets.

**Comment by Yu-Jack** [comment]
FYI, the loading path is from this request (pic1).

![image](https://github.com/user-attachments/assets/770291b6-1418-48fd-aa38-546f80c706b2)

![image](https://github.com/user-attachments/assets/6fbe734c-8384-40aa-9764-236f2413f078)

**Comment by bk201** [comment]
I'm lowering the priority since most people can't reproduce it.

**Comment by albinsun** [comment]
Close as env. issue.
