### ISSUE TITLE
[ENHANCEMENT] Remove "Clone" action for Longhorn V2 Storage Classes

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6762]
**Is your enhancement related to a problem? Please describe.**
The Longhorn v2 data engine doesn't yet support volume clone, so we need to hide the Clone operations in the Harvester UI for LHv2 volumes.

**Describe the solution you'd like**
Much the same as https://github.com/harvester/dashboard/pull/1189 for snapshots, it would be ideal if we could:
- Remove the Clone action for LHv2 Volumes
- Remove the Clone action for VMs that have LHv2 Volumes attached.

**Describe alternatives you've considered**
Document the limitation

**Additional context**
Related issue: https://github.com/harvester/harvester/issues/5274

**Comment by Vicente-Cheng** [comment]
~Hi @tserong, @a110605  
LVM also needs to remove the Clone action in v1.4.0.
Could we use the same issue to track?~

**Comment by tserong** [comment]
> Could we use the same issue to track?

Fine by me :-)

**Comment by Vicente-Cheng** [comment]
> > Could we use the same issue to track?
> 
> Fine by me :-)

Thanks! Updated the title and content.

**Comment by Vicente-Cheng** [comment]
After today's discussion/test with @a110605 

The LVM CSI driver had the capability to perform clone operations, so I opened the dashboard PR (https://github.com/harvester/dashboard/pull/1202) to add it back.

**Comment by lanfon72** [comment]
Verified this enhancement has been applied.

![image](https://github.com/user-attachments/assets/9adb0039-b9e9-4a27-bb87-f1afe3b1c0f8)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes having additional disks
2. Enable Longhorn engine V2[^1]
3. Create longhorn engine V2 storage class `lhv2`
4. Create volume `v1` with storage class `lhv2`
5. Clone function should not work on volume `v1`


[^1]: https://github.com/harvester/harvester/pull/6167/files#diff-ef12ba08019b0eaeee53c465b01de7055067e0aa68fb17df266067468471c6f5
