### ISSUE TITLE
[QUESTION] i want to create airgrapped update on 1.3.0 to 1.3.1 

### ISSUE THREAD

**Issue by AhBun9** [harvester/harvester#6763]
Hello, when running kubectl create -f i receive the following error saying 

**Ouput**

kubectl create -f http://172.16.102.6/v1.3.1/version.yaml
Error from server (AlreadyExists): error when creating "http://172.16.102.6/v1.3.1/version.yaml": versions.harvesterhci.io "v1.3.1" already exists

is possible to remove current file and add airgrapped update?

**Comment by bk201** [comment]
@AhBun9 You can get the current versions with:
```
kubectl get versions -n harvester-system
```

and delete one version or edit it with `kubectl delete/kubectl edit`.
