### ISSUE TITLE
[BUG]should not display the state of VM when the VM is migrating/aborting

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#677]
**Describe the bug**

**To Reproduce**
1. Go to VM list page
2. Migrate a VM
3. The field of state would display two badges, one is VM state, the other one is migration state

**Expected behavior**

1. should not display the state of VM when the VM is migrating/aborting

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
Validation passed in version v0.2.0-rc2
1. vm Migration
![image](https://user-images.githubusercontent.com/15829074/115197764-f158fb80-a123-11eb-96d0-2b65bde51972.png)
2. vm Aborting migration
![image](https://user-images.githubusercontent.com/15829074/115197927-19485f00-a124-11eb-85bd-cc9a8f6ea572.png)
