### ISSUE TITLE
[BUG] All VMBackup couldn't be recovered if Remote Backup has any VMImage with the same DisplayName

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6772]
**Describe the bug**
All VMBackup couldn't be recovered if Remote Backup has any VMImage with the same DisplayName

**To Reproduce**
1. Setting a remote backup target
2. Uploading an VMImage from the local file
3. Creating VM `vm1`, and having a related VMBackup `vm1-b`
4. Deleting VM `vm1`, VMBackup `vm1-b` and the VMImage
5. Uploading another VMImage from the same local file
6. Creating VM `vm2`, and having a related VMBackup `vm2-b`
7. Setting the remote backup target to default
8. Deleting VMBackup `vm2-b`
9. Setting the remote backup target back
10. Can't discover VMBackup `vm2-b`
      - Harvester controller with error message `can't sync vm image metadata" error="admission webhook \"validator.harvesterhci.io  \" denied the request: A resource with the same name exists" target.endpoint="http://192.188.0.54:9000" target.type=s3` 
      - This is brought by the legacy VMImage metadata. The legacy VMImage has the same displayName as an existing VMImage, although it has already been deleted. However, its metadata is still left on the backup target.
      - The above situation caused the conflict in `syncVMImage()` https://github.com/harvester/harvester/blob/b3aee86ae14eeca73aed9647de244410f5f144f0/pkg/controller/master/backup/backup_metadata.go#L124-L128, and make function `syncVMBackup()` be skipped

**Expected behavior**
VMBackup `vm2-b` could be recovered after setting back the remote backup target

**Environment**
 - Harvester ISO version: master-head branch (`b3aee86ae14eeca73aed9647de244410f5f144f0`)

**Additional context**
- This is introduced by https://github.com/harvester/harvester/pull/4614 cc @FrankYang0529
- The Harvester controller uploads VMImage metadata as LH creates backupbackingimage CR https://github.com/harvester/harvester/blob/b3aee86ae14eeca73aed9647de244410f5f144f0/pkg/controller/master/backup/backup_backing_image.go#L131-L146. However, when VMImage is deleted, the VMImage metadata is never touched on the backup target. This brings an inconsistency between the cluster and remote backup target, maybe we should consider the design for the backup image. WDYT? @FrankYang0529 
- Sync VMBackup to another cluster can have a similar situation

**Comment by brandboat** [comment]
Test OK on v1.4.0-rc3, will close the issue

## Environment
* Harvester
  * Version: `v1.4.0-rc3`
  * Profile: QEMU/KVM, 3 nodes (8C/16G/250G)
  * ui-source: `Auto`
## Test Plan
follow test plan in https://github.com/harvester/harvester/pull/6780#issue-2587553329
### Case 1: Removing VM image can cleanup VM image metadata in backup target
1. Create a new cluster
2. Setup backup target.
3. Create a VM image and VM.
4. Take a backup for the VM.
  <img width="1678" alt="image" src="https://github.com/user-attachments/assets/c020db2a-cfe9-4607-9076-fd111d7c7f47">
5. Check there is VM image metadata in the backup target.
  <img width="1661" alt="image" src="https://github.com/user-attachments/assets/c662512a-e7cb-4a9f-ab62-03aa3b51481d">

6. Remove the backup, VM, and VM image.
<img width="1679" alt="image" src="https://github.com/user-attachments/assets/44793be9-f075-42b7-9cf3-26e41f5f5591">
<img width="1670" alt="image" src="https://github.com/user-attachments/assets/fb0bb912-d2f5-4b29-9bd2-e7aba5c81ca9">
<img width="1678" alt="image" src="https://github.com/user-attachments/assets/f31537d2-f951-4647-9a4e-0d2487e9377c">
7. Check the VM image metadata is removed in the backup target.
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/bc527ed4-1452-483d-8686-f82b7059b5b8">

### Case 2: Skip restoring VM image with same display name
1. Create a new cluster
2. Setup backup target.
3. Create a VM image and VM.
4. Take a backup for the VM.
<img width="1672" alt="image" src="https://github.com/user-attachments/assets/076e1c6a-81e0-4e4f-8c8c-7651d11e58a1">
5. Set backup target to default value.
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/02a33600-db8f-41da-9dd3-9941ab7fdb4d">
6. Remove the backup, VM, and VM image.
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/ef80ef6e-8476-460b-a514-87dad233a3af">
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/d25210c7-3820-4912-a8ca-d09e98eaa9c4">
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/61db4f0b-2d1a-4468-b9fd-1cad2cb8ac72">
7. Create a new VM image with same display name and different CR name.
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/cc7d4d22-b574-4c07-9343-f51451e703b0">
8. Set backup target back.

![image](https://github.com/user-attachments/assets/40c6ee40-2ed8-4d0d-8804-9f6509ac4a85)

9. Check harvester pod has following log.
<img width="1675" alt="截圖 2024-10-21 下午4 54 28" src="https://github.com/user-attachments/assets/52123bc3-19f9-4146-9c76-b7ea6ccd9c20">
