### ISSUE TITLE
[BUG] Load Balancer shows Pending and does not created on Harvester side

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6774]
**Describe the bug**
From Rancher RKE2/RKE1 cluster, fail to create LB due to
```
Error syncing load balancer: failed to ensure load balancer: create or update lb default/xxx failed, error: admission webhook "validator.harvester-system.harvester-load-balancer-webhook" denied the request: Internal error occurred: create loadbalancer default/xxx failed: the loadbalancer needs to have at least one listener
```

**To Reproduce**
1. <details>
   <summary> Import Harvester to Rancher
   </summary>
   
   ![image](https://github.com/user-attachments/assets/2d037658-d1fa-41a4-903e-1f43ce3c9133)
   </details>

1. <details>
   <summary> Create RKE2 cluster
   </summary>
   
   ![image](https://github.com/user-attachments/assets/4735d843-fd7b-4d59-b75f-dd32533de8f6)
   </details>

1. <details>
   <summary> Check Installed Apps
   </summary>
   
   ![image](https://github.com/user-attachments/assets/d4c3546e-9906-4398-bd25-8ccbef2be6c3)
   </details>

1. <details>
   <summary> Deploy Nginx workload
   </summary>
   
   ![image](https://github.com/user-attachments/assets/b41432e5-4bd4-404a-bf9b-b693662e8917)
   </details>

1. <details open>
   <summary> Create LB (DHCP) for Nginx workload
   </summary>
   
   > :x: `Error syncing load balancer: failed to ensure load balancer... the loadbalancer needs to have at least one listener`
   * Rancher
     ![image](https://github.com/user-attachments/assets/504782bf-c5a9-45ef-8935-e8f8710d104e)
   * Harvester
     ![image](https://github.com/user-attachments/assets/d6b863f0-afde-440d-a8fc-13bd68f8bf45)
   </details>

**Expected behavior**
LB should be successfully created

**Support Log**
* support_bundle: [supportbundle_LoadBalancerNotCreated_2024-10-14T11-44-43Z.zip](https://github.com/user-attachments/files/17363509/supportbundle_LoadBalancerNotCreated_2024-10-14T11-44-43Z.zip)
* rancher2_logs: [myrke2-pool1-ft4cd-pnh7t-2024-10-14_12_04_20.tar.gz](https://github.com/user-attachments/files/17363631/myrke2-pool1-ft4cd-pnh7t-2024-10-14_12_04_20.tar.gz)

**Environment**
* _harvester-v1.4.0-rc2_
  * Profile: AMD64, single node, 10C/20G/500G
  * ui-source: `Auto`
* _rancher-v2.9.2_
  * Profile: AMD64, Helm w/ K3s _v1.28.14+k3s1_
  * _cert-manager-v1.5.1_
  * RKE2 Guest Cluster
    * _v1.28.13+rke2r1_
    * _harvester-cloud-provider:0.2.400_
    * _harvester-csi-driver:0.1.1800_

**Additional context**
1. Both RKE2 and RKE1 cluster hit this issue.
2. rancher-v2.8.5 also hits

**Comment by starbops** [comment]
It looks like we accidentally added a minimum listener check (must be > 0) to the load balancer webhook in a recent refactor. This check is unsuitable for cluster-type load balancer use cases and should only apply to VM-type load balancers.

Harvester cloud provider creates LBs in the underlying Harvester cluster without any listeners defined:

https://github.com/harvester/cloud-provider-harvester/blob/86465fdee5dacef170752ad18e2169f448b027e5/pkg/cloud-controller-manager/loadbalancer.go#L210-L255

**Comment by w13915984028** [comment]
This issue can be validated with the coming harvester-v1.4.0-rc4 release, which has the new LB image tag bumped via PR https://github.com/harvester/harvester/pull/6833.

**Comment by Yu-Jack** [comment]
## Validation Description

Follow OP to create load balancer with data below.

Nginx image is `nginx:latest`. Service Listening Port is `8080` and target port is `80`. Remember to fill out Selectors with correct label name in nginx POD. Others are default.

<details>
<summary> 🟢  Service was successfully created and connectd.</summary>

![image](https://github.com/user-attachments/assets/6c852e72-84f2-4b87-8586-0068945d33e7)

![image](https://github.com/user-attachments/assets/b9329665-00ad-4260-8adc-6b71f1e56c97)


</details>

<details>
<summary> 🟢 WorkloadType shouldn't be changed from vm to cluster with kubectl or GUI in Harvester</summary>

![image](https://github.com/user-attachments/assets/5a09b99d-186a-433f-a89e-b6491b471afa)

![image](https://github.com/user-attachments/assets/78dbf5e6-71d3-433b-b010-028a9eca1d89)

</details>

---

❓  However, there are some warnings about resource version. It's still the same with multiple trials.

<details>
<summary>Try-1</summary>

![image](https://github.com/user-attachments/assets/ed40d357-a3bb-4407-867c-6f50384da4af)

</details>

<details>
<summary>Try-2</summary>

![image](https://github.com/user-attachments/assets/4ee2363d-9758-481d-aff6-a4f816ab5ff7)

</details>

cc @starbops @w13915984028 , if you're okay with this, I could close this one and open a new issue for v1.5.0. What do you think?

## Environment

- harvester-v1.4.0-rc4
- rancher-v2.8.5

Other configs are default.

**Comment by w13915984028** [comment]
@Yu-Jack Those kind of error messages are normal. When the LB can turn `Active`, its fine. thanks.
