### ISSUE TITLE
[BUG] Delete vmi and vm error at the same time

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#678]
**Describe the bug**
When there is a vmi that has not been deleted, an error will be reported if you choose to delete the vm at the same time
![image](https://user-images.githubusercontent.com/24985926/114363784-5607d980-9bab-11eb-9e12-a5eb49e5ed84.png)

![image](https://user-images.githubusercontent.com/24985926/114364245-c9115000-9bab-11eb-8447-826a8d8464ad.png)

**To Reproduce**
1. creata  vm
2. delete vm （When it appears that vmi has not been deleted）
3. create another vm
4. delete all vm

**Expected behavior**
Hope that no error is reported, vm can be deleted, but vmi may not be deleted

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by DoNotSayYes** [comment]
Validated on master-head
