### ISSUE TITLE
[BUG] With V2 data engine enabled, all volumes created when creating VMs have access mode set to RWO

### ISSUE THREAD

**Issue by tserong** [harvester/harvester#6793]
**Describe the bug**
When creating new volumes as part of VM creation, with the Longhorn V2 data engine enabled, all the new volumes have their access mode set to RWO, but it should only be the LHv2 volumes that use RWO. LHv1 volumes should still be set to RWX.

This issue prevents live migration of VMs whose volumes were created during VM creation.

**To Reproduce**
1. Enable the V2 data engine
2. Create a VM
3. Run `kubectl get vmi $VM_NAME -o yaml` and note that the `persistentVolumeClaimInfo` for each volume includes `accessMode: ReadWriteOnce`

**Expected behavior**
Only volumes created with a longhorn v2 storage class should be given `accessMode: ReadWriteOnce`. Volumes created with a longhorn v1 storage class should be `accessMode: ReadWriteMany`.

**Environment**
 - Harvester ISO version: 650dff19
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): virtualized

**Additional context**
This was introduced as part of https://github.com/harvester/dashboard/pull/1076, I suspect due to https://github.com/harvester/dashboard/blob/f7703120ea14a1e251c3f1f394379bb2997bab2b/pkg/harvester/mixins/harvester-vm/index.js#L458

The behaviour is correct when creating volumes on the Volumes screen (i.e. v1 volumes are set to ReadWriteMany and v2 volumes are set to ReadWriteOnce). The problem only occurs when new volumes are created as part of VM creation, so a workaround is to create all volumes first on the Volumes screen, then create a VM using those volumes.

**Comment by a110605** [comment]
Test under creating a VM plus a extra disk using longhorn storage class.

The extra disk (disk-1) accessModes is `ReadWriteMany`.

<img width="1489" alt="Screenshot 2024-10-16 at 3 01 55 PM" src="https://github.com/user-attachments/assets/d687be0a-e8ca-4e66-9734-b129e7fe4caa">

<img width="1197" alt="Screenshot 2024-10-16 at 3 01 31 PM" src="https://github.com/user-attachments/assets/0cae88e2-a5d5-43cb-9a05-1b2d78317d44">

**Comment by lanfon72** [comment]
Verified this bug has been fixed.

![image](https://github.com/user-attachments/assets/f7065a07-27b5-48e0-83b0-9979fab4a3ca)


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **v1.4.0-rc3**
* **ui-source** Option: **Auto**

### Verify Steps
1. Install Harvester with any nodes having additional disks
2. Enable Longhorn engine V2[^1]
3. Create longhorn engine V2 storage class `lhv2`
4. Create an image for VM creation
5. Create VM `vm1` with new volumes (`lhv2` and default)
6. VM should started successfully
7. Edit yaml on `vm1`, check annotation of `harvesterhci.io/volumeClaimTemplates`
    - **accessModes: ReadWriteOnce** should be with the **storageClassName: lhv2**
    - **accessModes: ReadWriteOnce** should NOT be with the **storageClassName: lhv2**
    - **accessModes: ReadWriteMany** should NOT be with the **storageClassName: lhv2**

[^1]: https://github.com/harvester/harvester/pull/6167/files#diff-ef12ba08019b0eaeee53c465b01de7055067e0aa68fb17df266067468471c6f5
