### ISSUE TITLE
[BUG] VMs get stuck in paused/unpause loop while Longhorn replicas are being recreated

### ISSUE THREAD

**Issue by sarahhenkens** [harvester/harvester#6804]
**Describe the bug**

VMs are stuck in a pause/unpause loop during Longhorn volume repair when one of harvester nodes had a temporary network disruption.

VMs that are running on the harvester node that was not disconnected are also doing the pause/unpause loop. They become stable once longhorn finished recreating the replica volume on the node that was disconnected.
<img width="1992" alt="harvester-dashboard" src="https://github.com/user-attachments/assets/7906a031-3768-4676-8c3c-a133daf4da73">

In the events I see the following reason:

```
VirtualMachineInstance home-cluster-worker-7d7dacea-pchf9
VM Paused due to IO error at the volume: disk-0
```

### Longhorn recreating the replicas
 
<img width="2230" alt="longhorn-dashboard" src="https://github.com/user-attachments/assets/be2b44d0-bc86-4cb2-9989-0623a9e0d943">

**To Reproduce**

1. Create 2 harvester nodes
2. Deploy VMs on both of them
3. Temporary disconnect network on harvester node 2

**Expected behavior**

VMs to keep running on harvester node 1

**Support bundle**

**Environment**
 - Harvester ISO version: v1.2.1
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): node 1 running on Dell R730, node 2 running on a repurposed intel i9 desktop computer

**Additional context**

**Comment by RegisWeduLabs** [comment]
Hey there.  Please see issue https://github.com/harvester/harvester/issues/4739

Basically, disable fstrim in the vms.

Regards.

**Comment by sarahhenkens** [comment]
Oh interesting! Thanks for referencing the existing issue! 

Looks like this was also fixed upstream in Longhorn 🤔 https://github.com/longhorn/longhorn/issues/7103

**Comment by RegisWeduLabs** [comment]
Yes - but Harvester 1.2.1 has longhorn 1.4.3 - it is fixed in later versions of harvester (therefore later longhorn versions)
