### ISSUE TITLE
[BUG] network interface gets renamed during reboots

### ISSUE THREAD

**Issue by ibrokethecloud** [harvester/harvester#6808]
**Describe the bug**

On nodes using mellanox nics, users have reported an issue where the nic renaming fails during reboot of the nodes.

This is caused due to predictable renaming of nics to be broken due to a race condition with udev discovering and attempting to rename the devices and a secondary script in initramfs stage in installer attempting to bring up the nics. When the script executes before udev has managed to complete device renaming the predictable interface naming is broken.

**To Reproduce**
1. Install harvester 1.3.2 on a node with mellanox nics as management interface
2. Complete harvester installation
3. Reboot the node a few times to run into nic renaming issue

**Expected behavior**

predictable interface naming should persist across reboots

**Support bundle**

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by ibrokethecloud** [comment]
Test instructions

**Needs a machine with mellanox nics to easy replication of errors**

Using version 1.3.2
* install harvester on a node
* reboot node a few times to see an issue where network does not come online as the nic has been renamed from say enP0.. to eth0
* harvester startup fails

Using version 1.4.0-rc3
* install harvester on node
* reboot node a few times and nic should not get renamed
* harvester starts up successfully

**Comment by khushboo-rancher** [comment]
Waiting for ARM machines to be available in the lab as this is reproducible only on ARM machine.

**Comment by samueldewever** [comment]
@ibrokethecloud @albinsun : just FYI, its not only happening with Mellanox cards. We have the same issue on our Intel network NICS which got renamed after reload from time to time.

**Comment by ibrokethecloud** [comment]
@samueldewever if you have a spare machine where this error can be generated would you be willing to help test out 1.4.0-rc5?

**Comment by samueldewever** [comment]
> @samueldewever if you have a spare machine where this error can be generated would you be willing to help test out 1.4.0-rc5?

@ibrokethecloud 
I could probably free a server to do the testing, my only problem is that the engineer to assign on this is on holiday untill the 18th. 
In case you didn't had a opportunity to test it yourself before, I will ask him to test it with the rc5 after the 18th!

**Comment by TachunLin** [comment]
Verifying on `v1.4-ce5e24e3-head` (24/11/15).

### Result
<details><summary>$\color{red}{\textsf{Failed}}$ Restart Harvester v1.4-head node <strong>20 times</strong> on node with mellanox nics device $~~$</summary>

1. The <strong>1th to 15th</strong> trials of machine boot all works well, can startup Harvester and nic name did not renamed 
2. While on the <strong>16th</strong> trial of machine reboot
3. Harvester failed to startup  
  ![image](https://github.com/user-attachments/assets/6a2a2884-def7-4ae5-8250-3d93d1604d9d)

4. Check the console, but all nic name did not renamed  
  ![image](https://github.com/user-attachments/assets/969f1009-4a87-4274-8dd4-1e7b177142cb)


 </details>

<details><summary>$\color{orange}{\textsf{Comparison}}$ Restart Harvester v1.3.2 node <strong>10 times</strong> on node with mellanox nics device $~~$</summary>


1. While on the <strong>4th</strong> trial of machine reboot
2. Harvester failed to startup  
  ![image](https://github.com/user-attachments/assets/6a2a2884-def7-4ae5-8250-3d93d1604d9d)

3. Check the console, but all nic name did not renamed  
  ![image](https://github.com/user-attachments/assets/969f1009-4a87-4274-8dd4-1e7b177142cb)

 </details>

### Test Information
* Test Environment: Single node ARM bare-metal machine with mellanox nics
* Harvester version: `v1.4-ce5e24e3-head` (24/11/15)

### Verify Steps
<details><summary>Restart Harvester node several times on node with mellanox nics device  </summary>

1. Prepare two bare-metal machine installed with mellanox network interface card 
  ```
  arm-14-head:~ # lspci | grep -i mellanox
  0001:01:00.0 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
  0001:01:00.1 Ethernet controller: Mellanox Technologies MT27800 Family [ConnectX-5]
  ```
2. Provision the Harvester cluster 
3. Confirm the network interface naming status before rebooting `arm-14-head`

  ```
  arm-14-head:~ # ip link show
  1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
      link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
  2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
      link/ether d8:5e:d3:e6:90:76 brd ff:ff:ff:ff:ff:ff
      altname enP3p2s0f0
  3: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
      link/ether d8:5e:d3:e6:90:77 brd ff:ff:ff:ff:ff:ff
      altname enP3p2s0f1
  4: enP1p1s0f0np0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP mode DEFAULT group default qlen 1000
      link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
  5: enP1p1s0f1np1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
      link/ether b8:3f:d2:b0:b4:59 brd ff:ff:ff:ff:ff:ff
  6: enP4p3s0u4u3c2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
      link/ether 76:5f:78:2b:05:27 brd ff:ff:ff:ff:ff:ff
  7: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
      link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
  8: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP mode DEFAULT group default qlen 1000
      link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
  9: mgmt-br.2011@mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
      link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
  ```
4. Reboot the machine 
5. Check can start up Harvester correctly
  ![image](https://github.com/user-attachments/assets/0ea92b28-674e-4348-aa7c-04186a363bcd)

6. Network connection exists, can access Harvester dashboard 

  ![image](https://github.com/user-attachments/assets/e417525a-8562-4dc9-9ddf-3c623b93a834)


7. Can ssh to node, check NIC name should not be renamed

```
arm-14-head:~ # ip link show
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eno1: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether d8:5e:d3:e6:90:76 brd ff:ff:ff:ff:ff:ff
    altname enP3p2s0f0
3: eno2: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc mq state DOWN mode DEFAULT group default qlen 1000
    link/ether d8:5e:d3:e6:90:77 brd ff:ff:ff:ff:ff:ff
    altname enP3p2s0f1
4: enP1p1s0f0np0: <BROADCAST,MULTICAST,SLAVE,UP,LOWER_UP> mtu 1500 qdisc mq master mgmt-bo state UP mode DEFAULT group default qlen 1000
    link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
5: enP1p1s0f1np1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether b8:3f:d2:b0:b4:59 brd ff:ff:ff:ff:ff:ff
6: enP4p3s0u4u3c2: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1000
    link/ether 76:5f:78:2b:05:27 brd ff:ff:ff:ff:ff:ff
7: mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
8: mgmt-bo: <BROADCAST,MULTICAST,MASTER,UP,LOWER_UP> mtu 1500 qdisc noqueue master mgmt-br state UP mode DEFAULT group default qlen 1000
    link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
9: mgmt-br.2011@mgmt-br: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether b8:3f:d2:b0:b4:58 brd ff:ff:ff:ff:ff:ff
```

</details>

**Comment by khushboo-rancher** [comment]
@ibrokethecloud Could you please help check the above [comment](https://github.com/harvester/harvester/issues/6808#issuecomment-2478595456) ?

**Comment by samueldewever** [comment]
@ibrokethecloud I don't think the issue which TanchunLin described in his tests is not related to this issue. 

Do you want us to still test RC5? If yes I will assign it to an engineer internally.

**Comment by ibrokethecloud** [comment]
hi @samueldewever that is unrelated issue and was more related due to dhcp in our environment. any feedback would be appreciated.

**Comment by samueldewever** [comment]
@ibrokethecloud : My collegue Kresimir is currently installing RC5 on a spare labo machine and will do the testings tomorrow and report results afterwards

**Comment by dstny-ksimac** [comment]
@ibrokethecloud , @samueldewever,

After setting up the test system and going through 26 reboot cycles, so far, I can confirm that the name of the adapter doesn't change.

Name stays the same on CLI as well as the web UI.

If there are any other suggestions, I'd be happy to try them out if possible

**Comment by ibrokethecloud** [comment]
thank you @dstny-ksimac for helping us validate this as well.

**Comment by bk201** [comment]
@TachunLin Are we good to close this one, the nic is not renamed in your testing.

**Comment by TachunLin** [comment]
@bk201,
I think we are good to close this issue since during the entire test process we did not encounter any mellanox nic name renamed situation. 
The previous hit startup failure was related to dhcp failed to get an address which would more related to the environment issue.
