### ISSUE TITLE
[BUG] ResourceCancelModal style is missing 

### ISSUE THREAD

**Issue by a110605** [harvester/harvester#6814]
**Describe the bug**
The pop up modal style is missing when clicking "Back to Form".

**To Reproduce**
1. Go to Create VM page
2. Click "Edit As Yaml" button
3. Click "Back to Form" button
4. ResourceCancelModal style is missing 

**Expected behavior**
Should looks like
<img width="1490" alt="Screenshot 2024-10-17 at 10 58 38 AM" src="https://github.com/user-attachments/assets/a0c4f663-cf9b-4d16-a3c0-d481a766f88a">

But now looks like
<img width="1486" alt="Screenshot 2024-10-17 at 11 04 52 AM" src="https://github.com/user-attachments/assets/897db0fd-2443-4195-9449-ed4c01ae0ac3">

**Environment**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Due to missing port `harvester-dashboard/shell/components/ResourceCancelModal.vue` change rancher/dashboard.

**Comment by brandboat** [comment]
This one seems not included in v1.4.0-rc3 yet, move it back to ready for testing

**Comment by noahgildersleeve** [comment]
Validated as fixed in `v1.4-1856e9dc-head` on 3 node libvirt cluster

![Screenshot_20241021_144022](https://github.com/user-attachments/assets/19f8a50e-c15f-4a58-97ad-902e6c18cc63)
