### ISSUE TITLE
[ENHANCEMENT] Improve load-balancer-harvester IPPool error message

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6819]
**Is your enhancement related to a problem? Please describe.**

![image](https://github.com/user-attachments/assets/500ce558-5412-45f4-ab2b-ac1c88256a36)

The above error is due to: the input `192.168.15.0` is not a valid CIDR like `192.168.15.0/24`, but the error message `invalid range...` is not helpful.

**Describe the solution you'd like**

Return a helpful error message.

**Describe alternatives you've considered**

**Additional context**

Observed when testing PR: https://github.com/harvester/load-balancer-harvester/pull/39

**Comment by w13915984028** [comment]
Test Plan:

Per PR https://github.com/harvester/load-balancer-harvester/pull/40 description, when an invalid subnet CIDR `a.b.c.d/xy` is input, it is denied and error message exactly says the CIDR is wrong.

**Comment by w13915984028** [comment]
This issue can be validated with the coming harvester-v1.4.0-rc4 release, which has the new LB image tag bumped via PR https://github.com/harvester/harvester/pull/6833.

**Comment by Yu-Jack** [comment]
SIngle Node Harvester v1.4.0-rc4.

<details>
<summary> 🟢 Case 1: 192.168.1.0</summary>

![image](https://github.com/user-attachments/assets/bd0fb806-62b0-4bbd-89ea-8017b04a582c)

</details>

<details>
<summary> 🟢 Case 2: 192.168.1.0/-1, 192.168.1.0/33, 192.168.1.0/a, 192.168.1.0/</summary>

![image](https://github.com/user-attachments/assets/4bc48879-e864-4e34-ad3e-469809a9182d)

![image](https://github.com/user-attachments/assets/dde0fab9-6df8-4a94-a873-54dfb899401e)

![image](https://github.com/user-attachments/assets/92609dc6-20f1-46a9-83ae-faaca478b049)

![image](https://github.com/user-attachments/assets/879c451d-7524-4d04-a2fd-11d5d8999e46)

</details>

<details>
<summary> 🟢 Case 3: 192.168.1.999/24, 192.168.1.999/16</summary>

![image](https://github.com/user-attachments/assets/a3ec9b7a-becb-42ff-adce-02f00829fd2c)

![image](https://github.com/user-attachments/assets/451c5f82-7492-41c7-8116-cec7cabd995a)

</details>


<details>
<summary> 🟢 Case 4: 192.168.1.0//24, 192.168.1.0^/24, 192.168.1.0"/24, 192.168.1.0$/24</summary>

![image](https://github.com/user-attachments/assets/6ebfe52b-1f44-467f-a8b2-22d636545047)

![image](https://github.com/user-attachments/assets/1f17bb25-cb53-4619-bd67-2f89c21d626b)

![image](https://github.com/user-attachments/assets/a3e0c108-d71d-4491-881c-8d3d2bc3774e)

![image](https://github.com/user-attachments/assets/ff2e3a90-37b2-45c1-ae06-5c42fcccc8c7)

</details>

<details>
<summary> 🟢 Case 5: 10.8.0.0/99</summary>

![image](https://github.com/user-attachments/assets/e9c766c1-ed68-4715-b003-52fe4a09f986)

</details>
