### ISSUE TITLE
Update image format hint for gz and xz fomat 

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#682]
Compressed image format is not supported in current implementation. The support for it is tracked in https://github.com/rancher/harvester/issues/681

We need to update the hint on image creation page:
![image](https://user-images.githubusercontent.com/5697937/114505612-3b913700-9c63-11eb-8347-246b381af905.png)

**Comment by TangStone** [comment]
### Validation passed in version v0.2.0-rc2
![image](https://user-images.githubusercontent.com/15829074/115343856-152d4780-a1df-11eb-8b6e-7a5532f54a46.png)
![image](https://user-images.githubusercontent.com/15829074/115344006-47d74000-a1df-11eb-8058-e81292571238.png)

**Comment by futuretea** [comment]
On latest master-head 
1. Create a image with unsupported extension, the error message still say supoort compressed image.
![image](https://user-images.githubusercontent.com/15064560/115516643-ec798080-a2b8-11eb-8031-efc37573c685.png)

2. currently we don't support compressed image in backend, but still can create a image by a url with comperessed file extension 
![image](https://user-images.githubusercontent.com/15064560/115516692-f7ccac00-a2b8-11eb-9ff6-4dc17851c1d1.png)

**Comment by DaiYuzeng** [comment]
compressed image is not supported on the editing image page, and remove the tips about compressed image

**Comment by futuretea** [comment]
validated on master-0423.iso
![image](https://user-images.githubusercontent.com/15064560/115951260-5c367800-a512-11eb-94d1-274f6bb9bd6b.png)
![image](https://user-images.githubusercontent.com/15064560/115951267-66587680-a512-11eb-9771-8b182f5cf07e.png)
