### ISSUE TITLE
[ENHANCEMENT] Improve the selector processing on loadbalancer harvester

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6820]
**Is your enhancement related to a problem? Please describe.**

When a LB does not set selector (it is allowed for place-holder), it may select the running VMs implicitly and becomes ready.

And the information is mis-matching.

UI shows no VM is matched.
![image](https://github.com/user-attachments/assets/3ead465b-dafe-4f37-9b9c-b63d2999e22b)

But the LB shows `ready` and VM IP on `backendServers`
![image](https://github.com/user-attachments/assets/b81e8957-675d-44e9-ad96-26e04f6df68f)

![image](https://github.com/user-attachments/assets/01443327-d665-4f8b-9112-efaa7fee247d)

**Describe the solution you'd like**

When a LB does not set selector, let it become `not ready`, to avoid affecting other LB accidentally.

**Describe alternatives you've considered**

**Additional context**

**Local Test**

After the fix:

![image](https://github.com/user-attachments/assets/efee3216-df3a-4673-9d41-846fbacd9200)

![image](https://github.com/user-attachments/assets/48c3526c-b568-4ffb-82dd-6bff2514b0db)

And after setting a valid selector:
![image](https://github.com/user-attachments/assets/5e320f4d-34b2-4ee9-aaa6-7be70edce1fe)

**Comment by w13915984028** [comment]
Test plan:

(1) Create a few VMs
(2) Create a IPPool
(3) Create a few LBs via allocating IPs from the above Pool, but does not set `node selector`, LB shows `Not Ready`  with message `No running backend servers`

(before this issue is fixed, you may observe the mis-matching information https://github.com/harvester/harvester/issues/6820#issue-2595524880)

(4) Set the selector of one LB to select one/a few VMs, it then shows `Ready`, the VMs' IP are show on LB's `backendServers`
(5) Remove the selector, it becomes 'Not Ready` again

**Comment by w13915984028** [comment]
This issue can be validated with the coming harvester-v1.4.0-rc4 release, which has the new LB image tag bumped via PR https://github.com/harvester/harvester/pull/6833.

**Comment by brandboat** [comment]
Test ok, will close the issue.

# Environment
- 3 nodes (8c/16G/250GB)
- v1.4.0-rc4


# Test Plan
Prerequisites:
- Create 2 VMs
<img width="1675" alt="image" src="https://github.com/user-attachments/assets/1ab4dead-88e8-4d51-b6d0-49c40c001db0">

- Create IP Pool
<img width="1676" alt="image" src="https://github.com/user-attachments/assets/88b817ea-01b2-4b53-94a5-0edceb31b5af">

## Verify load balancer not ready when selector is empty
<img width="1671" alt="image" src="https://github.com/user-attachments/assets/3fb4868d-8d6f-42e2-8df5-a9498ae080af">

<img width="1677" alt="image" src="https://github.com/user-attachments/assets/b274f8a5-65bd-4aac-82ae-b7312d7be0bf">

## Verify load balancer is ready when selector matches VM
<img width="1665" alt="image" src="https://github.com/user-attachments/assets/1806f789-f27a-4486-b6d3-69396ef18d04">
