### ISSUE TITLE
[BUG] RKE2 cluster won't become active when provisioned from Rancher v2.10-head  downstream on Harvester v1.4.0-rc2

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#6821]
**Describe the bug**

When provisioning downstream RKE2 clusters they don't come up after provisioning. The VMs seem to be created successfully.

**To Reproduce**
1. Import Harvester into Rancher
2. Create cloud credentials
3. Provision a 3 node RKE2 cluster
**Result**
They stay in the status of `Configuring bootstrap node(s) v210-a-v210-a-npmnb-rg27l: waiting for cluster agent to connect`

**Expected behavior**

The clusters should go active
**Support bundle**

[supportbundle_05592c18-a8ad-4f0f-9f08-6de16ff75576_2024-10-10T19-14-01Z.zip](https://github.com/user-attachments/files/17333157/supportbundle_05592c18-a8ad-4f0f-9f08-6de16ff75576_2024-10-10T19-14-01Z.zip)

**Environment**
 - Harvester ISO version: v1.4.0-rc2
 - Rancher version: v2.10-e4572f8147ba107fae3eea8e3bf73c9306c272b0-head on single node Docker instance
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node ProLiant DL360 Gen9

**Additional context**

This is the Harvester ticket for this [original bug](https://github.com/rancher/rancher/issues/47501)

This works if you select the default RKE2 embedded cloud provider. After working with @jakefhyde on the issue he found the `harvester-cloud-provider` is stuck in `ContainerCreating`
```
kubectl --kubeconfig ./kube.config.2 get pods -A
NAMESPACE         NAME                                                        READY   STATUS              RESTARTS   AGE
calico-system     calico-kube-controllers-657847c99f-sn9z4                    0/1     Pending             0          25h
calico-system     calico-node-slhtk                                           0/1     Running             0          25h
calico-system     calico-typha-c6bd85c4b-jrvh8                                0/1     Pending             0          25h
cattle-system     cattle-cluster-agent-58b9f86797-65qq8                       0/1     Pending             0          25h
kube-system       etcd-first-test-first-test-62gvj-v6zq4                      1/1     Running             0          25h
kube-system       harvester-cloud-provider-76dfdc87f7-m6k85                   0/1     ContainerCreating   0          25h
kube-system       harvester-csi-driver-controllers-694f475d94-82nts           0/3     Pending             0          25h
kube-system       harvester-csi-driver-controllers-694f475d94-rxhpb           0/3     Pending             0          25h
kube-system       harvester-csi-driver-controllers-694f475d94-tnxbx           0/3     Pending             0          25h
kube-system       helm-install-harvester-cloud-provider-jk9xd                 0/1     Completed           0          25h
kube-system       helm-install-harvester-csi-driver-rhkmj                     0/1     Completed           0          25h
kube-system       helm-install-rke2-calico-9g7tz                              0/1     Completed           2          25h
kube-system       helm-install-rke2-calico-crd-6csjx                          0/1     Completed           0          25h
kube-system       helm-install-rke2-coredns-r6rkm                             0/1     Completed           0          25h
kube-system       helm-install-rke2-ingress-nginx-7bj2n                       0/1     Pending             0          25h
kube-system       helm-install-rke2-metrics-server-8z24m                      0/1     Pending             0          25h
kube-system       helm-install-rke2-snapshot-controller-crd-jsmp6             0/1     Pending             0          25h
kube-system       helm-install-rke2-snapshot-controller-fzfz9                 0/1     Pending             0          25h
kube-system       helm-install-rke2-snapshot-validation-webhook-v9l8r         0/1     Pending             0          25h
kube-system       kube-apiserver-first-test-first-test-62gvj-v6zq4            1/1     Running             0          25h
kube-system       kube-controller-manager-first-test-first-test-62gvj-v6zq4   1/1     Running             0          25h
kube-system       kube-proxy-first-test-first-test-62gvj-v6zq4                1/1     Running             0          25h
kube-system       kube-scheduler-first-test-first-test-62gvj-v6zq4            1/1     Running             0          25h
kube-system       rke2-coredns-rke2-coredns-79f8cbfcf7-vfcqt                  0/1     Pending             0          25h
kube-system       rke2-coredns-rke2-coredns-autoscaler-7cf7db4bdc-w4h8n       0/1     Pending             0          25h
tigera-operator   tigera-operator-7cf54cf557-wtht6                            1/1     Running             0          25h
```
He said that we can see why if we describe it:

```
❯ kubectl --kubeconfig ./kube.config.2 describe pods -n kube-system harvester-cloud-provider-76dfdc87f7-m6k85
Name:         harvester-cloud-provider-76dfdc87f7-m6k85
Namespace:    kube-system
Priority:     0
Node:         first-test-first-test-62gvj-v6zq4/
Start Time:   Thu, 10 Oct 2024 16:16:17 -0400
Labels:       app.kubernetes.io/instance=harvester-cloud-provider
              app.kubernetes.io/name=harvester-cloud-provider
              pod-template-hash=76dfdc87f7
Annotations:  <none>
Status:       Pending
Controlled By:  ReplicaSet/harvester-cloud-provider-76dfdc87f7
Containers:
  harvester-cloud-provider:
    Container ID:  
    Image:         rancher/harvester-cloud-provider:v0.2.2
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Command:
      harvester-cloud-provider
    Args:
      --cloud-config=/etc/kubernetes/cloud-config
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /etc/kubernetes/cloud-config from cloud-config (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-cz4sw (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  cloud-config:
    Type:          HostPath (bare host directory volume)
    Path:          /etc/kubernetes/cloud-config
    HostPathType:  File
  kube-api-access-cz4sw:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 cattle.io/os=linux:NoSchedule
                             node-role.kubernetes.io/control-plane:NoSchedule
                             node-role.kubernetes.io/etcd:NoExecute
                             node.cloudprovider.kubernetes.io/uninitialized=true:NoSchedule
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason       Age                    From     Message
  ----     ------       ----                   ----     -------
  Warning  FailedMount  3m26s (x746 over 25h)  kubelet  MountVolume.SetUp failed for volume "cloud-config" : hostPath type check failed: /etc/kubernetes/cloud-config is not a file
```

It seems that it's related to the cloud provider and the volume either not mounting or not downloading

**Comment by ibrokethecloud** [comment]
I suspect the issue is how the rkeConfig is being setup in the cluster.yaml

```
  rkeConfig:
    chartValues:
      harvester-cloud-provider: {}
      harvester-cloud-provider.cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
      harvester-cloud-provider.global.cattle.clusterName: v210-test
```

It should have been

```
  rkeConfig:
    chartValues:
      harvester-cloud-provider:
        cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
        global:
          cattle:
            clusterName: v210-test
```

Manually editing and correcting the yaml triggers correct deployment of cloud provider and subsequent provisioning of cluster

**Comment by bk201** [comment]
@a110605 @torchiaf please take a look. The field is not expanded to a map.

**Comment by innobead** [comment]
If this is a UI issue, we need to review why having this regression and how to prevent this.

**Comment by irishgordo** [comment]
fwiw, on Harvester v1.3.2 & Rancher v2.10.0-alpha3 I'm noticing w/ `journalctl -u rke2-server.service --follow` on the node itself:
```
helm.cattle.io \"harvester-cloud-provider.cloudConfigPath\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.cloudConfigPath\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create kube-system/harvester-cloud-provider.global.cattle.clusterName helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.global.cattle.clusterName\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.global.cattle.clusterName\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
Oct 18 23:07:03 newsample-pool1-nvq5f-fldfj rke2[2165]: time="2024-10-18T23:07:03Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml: failed to create kube-system/harvester-cloud-provider.cloudConfigPath helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.cloudConfigPath\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.cloudConfigPath\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create kube-system/harvester-cloud-provider.global.cattle.clusterName helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.global.cattle.clusterName\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.global.cattle.clusterName\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
Oct 18 23:07:18 newsample-pool1-nvq5f-fldfj rke2[2165]: time="2024-10-18T23:07:18Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml: failed to create kube-system/harvester-cloud-provider.cloudConfigPath helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.cloudConfigPath\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.cloudConfigPath\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create kube-system/harvester-cloud-provider.global.cattle.clusterName helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.global.cattle.clusterName\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.global.cattle.clusterName\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
Oct 18 23:07:34 newsample-pool1-nvq5f-fldfj rke2[2165]: time="2024-10-18T23:07:34Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml: failed to create kube-system/harvester-cloud-provider.cloudConfigPath helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.cloudConfigPath\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.cloudConfigPath\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create kube-system/harvester-cloud-provider.global.cattle.clusterName helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.global.cattle.clusterName\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.global.cattle.clusterName\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
Oct 18 23:07:50 newsample-pool1-nvq5f-fldfj rke2[2165]: time="2024-10-18T23:07:50Z" level=error msg="Failed to process config: failed to process /var/lib/rancher/rke2/server/manifests/rancher/managed-chart-config.yaml: failed to create kube-system/harvester-cloud-provider.cloudConfigPath helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.cloudConfigPath\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.cloudConfigPath\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'), failed to create kube-system/harvester-cloud-provider.global.cattle.clusterName helm.cattle.io/v1, Kind=HelmChartConfig for  kube-system/managed-chart-config: HelmChartConfig.helm.cattle.io \"harvester-cloud-provider.global.cattle.clusterName\" is invalid: metadata.name: Invalid value: \"harvester-cloud-provider.global.cattle.clusterName\": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"
```

So I also had to implement the workaround on an RKE2 cluster:
- https://github.com/harvester/harvester/issues/6821#issuecomment-2420731729

**Comment by a110605** [comment]
> I suspect the issue is how the rkeConfig is being setup in the cluster.yaml
> 
> ```
>   rkeConfig:
>     chartValues:
>       harvester-cloud-provider: {}
>       harvester-cloud-provider.cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
>       harvester-cloud-provider.global.cattle.clusterName: v210-test
> ```
> 
> It should have been
> 
> ```
>   rkeConfig:
>     chartValues:
>       harvester-cloud-provider:
>         cloudConfigPath: /var/lib/rancher/rke2/etc/config-files/cloud-provider-config
>         global:
>           cattle:
>             clusterName: v210-test
> ```
> 
> Manually editing and correcting the yaml triggers correct deployment of cloud provider and subsequent provisioning of cluster

Compare to rancher/dashboard v2.9 and v2.10, the `harvester-cloud-provider` in `spec.rkeConfig.chartValues` payload does not expanded in  `POST /v1/provisioning.cattle.io.clusters` API.

Looks like something wrong in https://github.com/rancher/dashboard/blob/master/shell/edit/provisioning.cattle.io.cluster/rke2.vue needs to be fixed. cc @torchiaf 

<img width="1462" alt="Screenshot 2024-10-21 at 12 30 39 PM" src="https://github.com/user-attachments/assets/d493a52d-d5bc-4f9b-93c4-d7ddd8932e2c">

**Comment by torchiaf** [comment]
Thanks @ibrokethecloud  @a110605 for identifying the problem.
@noahgildersleeve I fixed the request payload but I'm not sure this is the only problem that we have in RKE2 cluster's provisioning.
I just created a new cluster with the new version and still waiting for it to become active. Update ASAP.

**Comment by bk201** [comment]
Reopen, the issue was closed by PR merged.

**Comment by noahgildersleeve** [comment]
I validated  this with
- Harvester `v1.4-63ccec9f-head` on a 3 node libvirt cluster
- Rancher `v2.10-8decbf6fd040b5b2168430f1e72ccc484d59b6e0-head` running on a single node Docker instance
- Dashboard pulling from remote on latest `master 4e82a4d`
- RKE2 running v1.30.5+rke2r1 on a single node with openSUSE Leap 15.6 as the host

It seems to be working now. I'm not going to close this yet since v2.10 hasn't been released and doesn't have an RC yet. We can close this once we have a v2.10 release, or when we go through testing it in Harvester v1.5.0.

 ![Screenshot_20241022_111423](https://github.com/user-attachments/assets/655ce0d3-af55-4d99-8642-24b823097384)
![Screenshot_20241022_111013](https://github.com/user-attachments/assets/8a305f91-35a2-4862-9755-331ddea3b4ac)
![Screenshot_20241022_111000](https://github.com/user-attachments/assets/eab1ca5c-2e24-4be3-b241-cf975b5f6a19)

**Comment by noahgildersleeve** [comment]
Closing as completed per earlier test since it's in v1.4.0 now.

> I validated this with
> 
> * Harvester `v1.4-63ccec9f-head` on a 3 node libvirt cluster
> * Rancher `v2.10-8decbf6fd040b5b2168430f1e72ccc484d59b6e0-head` running on a single node Docker instance
> * Dashboard pulling from remote on latest `master 4e82a4d`
> * RKE2 running v1.30.5+rke2r1 on a single node with openSUSE Leap 15.6 as the host
> 
> It seems to be working now. I'm not going to close this yet since v2.10 hasn't been released and doesn't have an RC yet. We can close this once we have a v2.10 release, or when we go through testing it in Harvester v1.5.0.
> 
> ![Screenshot_20241022_111423](https://private-user-images.githubusercontent.com/83787952/378969123-655ce0d3-af55-4d99-8642-24b823097384.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTI4NzIsIm5iZiI6MTczMDM5MjU3MiwicGF0aCI6Ii84Mzc4Nzk1Mi8zNzg5NjkxMjMtNjU1Y2UwZDMtYWY1NS00ZDk5LTg2NDItMjRiODIzMDk3Mzg0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFhMGZhM2EyYjIwYmUwN2ZmN2U3ZGNlOWVkOWRmNWRkNzgwOTI4YjE1YzczOTRkODlmOWNjNzNiYzI2YTRiNmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.A1NoFiYdCOnbgY4tqfT8gFmZKefRWN8E2X867tSNeRQ) ![Screenshot_20241022_111013](https://private-user-images.githubusercontent.com/83787952/378968954-8a305f91-35a2-4862-9755-331ddea3b4ac.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTI4NzIsIm5iZiI6MTczMDM5MjU3MiwicGF0aCI6Ii84Mzc4Nzk1Mi8zNzg5Njg5NTQtOGEzMDVmOTEtMzVhMi00ODYyLTk3NTUtMzMxZGRlYTNiNGFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiMDhkOTllYmNjZDUwNDQ2MDcxMDI3ZjgzYTZhZGIyOTczNDMwYmRiY2ZhMjFkZjM4Mzg1NTUwNmQwNTgyNWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.RYFQBfwyfhZO7sXvlYqochpYr1TMYVb_zytFfgucBHk) ![Screenshot_20241022_111000](https://private-user-images.githubusercontent.com/83787952/378968958-eab1ca5c-2e24-4be3-b241-cf975b5f6a19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAzOTI4NzIsIm5iZiI6MTczMDM5MjU3MiwicGF0aCI6Ii84Mzc4Nzk1Mi8zNzg5Njg5NTgtZWFiMWNhNWMtMmUyNC00YmUzLWIyNDEtY2Y5NzViNWY2YTE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDMxVDE2MzYxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTg5NmVhYjNlY2E4NDU5ZmQ0NTE0NjcxOTNmYzJhZjgzYmM5NTY1MzQ5NGYxZmViMjQxOTEwNjYxZjZkMGZkMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.md9Gw8OjNGlLRejYgUhXiZbMj9OHbOX1J0J6r5VwB7w)
