### ISSUE TITLE
[DOC] All link direct to banzaicloud.com doc are broken

### ISSUE THREAD

**Issue by brandboat** [harvester/harvester#6824]
**Is your doc request related to a problem? Please describe or add the related issue ID.**

In https://docs.harvesterhci.io/v1.4/logging/harvester-logging/#configuring-log-destinations, there are many links in there are broken.

**Describe the solution you'd like**
Fix all links, or find a way to remove them.

## Additional context
Perhaps those broken link could be replace with docs under  https://kube-logging.dev/,  like ranch-logging mentioned in https://ranchermanager.docs.rancher.com/integrations-in-rancher/logging/custom-resource-configuration/outputs-and-clusteroutputs

**Comment by w13915984028** [comment]
Harvester document v1.3, v1.4 has been updated via PR https://github.com/harvester/docs/pull/654.
