### ISSUE TITLE
[BUG] ndm doesn't clear/wipe the disk when adding storage to Harvester

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#6828]
**Describe the bug**
On 1.4-RC3, the v2 disk won't be provisioned if there is a partition/previous data in it. We should wipefs the disk.

**To Reproduce**
1. Go to Host
2. Edit
3. Storage
4. Add a disk as v2 

**Expected behavior**
NDM should wipe the disk

**Support bundle**
```Type     Reason       Age   From                      Message
  ----     ------       ----  ----                      -------
  Warning  Ready        5m9s  longhorn-node-controller  Disk c1fd02d173a3f4b9176705e9b2e37d39(0003:03:00.0) on node altra is not ready: failed to generate disk config: error: rpc error: code = Internal desc = rpc error: code = Internal desc = failed to add disk block device: failed to create disk bdev: failed to attach NVMe disk 0003:03:00.0: error sending message, id 3126, method bdev_nvme_attach_controller, params {c1fd02d173a3f4b9176705e9b2e37d39 {PCIe  0003:03:00.0  }   30 2 15 disable}: {"code": -19,"message": "No such device"}
  Warning  Schedulable  5m9s  longhorn-node-controller  Disk c1fd02d173a3f4b9176705e9b2e37d39 (0003:03:00.0) on the node altra is not ready```

**Comment by TachunLin** [comment]
Verified **fixed** on v1.4.0-rc4. Close this issue. 

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ NVME disk with partition can be added as Longhorn V2 disk to Host  $~~$</summary>

  1. After enabled LHv2 config 
    ![image](https://github.com/user-attachments/assets/ced4a195-144b-4ede-b9bd-3660a9143f66)

  2. And run `mkfs.ext4 /dev/nvme1n1` to make a file system.

  ```
  v1:~ # mkfs.ext4 /dev/nvme1n1
  mke2fs 1.46.4 (18-Aug-2021)
  Discarding device blocks: done                            
  Creating filesystem with 58607766 4k blocks and 14655488 inodes
  Filesystem UUID: 6ef7d9f7-d126-4226-ac74-70cb092b2739
  Superblock backups stored on blocks: 
	  32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	  4096000, 7962624, 11239424, 20480000, 23887872
  
  Allocating group tables: done                            
  Writing inode tables: done                            
  Creating journal (262144 blocks): done
  Writing superblocks and filesystem accounting information: done
  ```
  
  ```
  v1:~ # lsblk
  NAME    MAJ:MIN RM   SIZE RO TYPE MOUNTPOINTS
  ---
  ...
  nvme0n1 259:0    0 223.6G  0 disk /var/lib/harvester/defaultdisk
  nvme1n1 259:1    0 223.6G  0 disk 
  
  ```

  3. Can correctly add a Longhorn V2 provisioner disk to the host 

  https://github.com/user-attachments/assets/6957513f-527a-4336-91e3-f982077c85f3
    
    
    
  ![image](https://github.com/user-attachments/assets/987aec3e-cc9f-4695-a3c6-4b798ed235bf)


4. Create a volume with the Longhorn V2 storage class, the volume can be created in the correct version 

  ![image](https://github.com/user-attachments/assets/4183d851-32e9-4f90-8260-257297b1ebee)


 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ SATA disk with partition can be added as Longhorn V2 disk to Host $~~$</summary>


  1. And run `mkfs.ext4 /dev/sdb` to make a file system.

```
v1:~ # lsblk -o NAME,TYPE,TRAN
NAME    TYPE TRAN
loop0   loop 
sda     disk sata
├─sda1  part 
├─sda2  part 
├─sda3  part 
├─sda4  part 
└─sda5  part 
sdb     disk sata
sdc     disk sas
sdd     disk sas
```

  ```
  v1:~ # mkfs.ext4 /dev/sdb
  mke2fs 1.46.4 (18-Aug-2021)
  Discarding device blocks: done                            
  Creating filesystem with 234423126 4k blocks and 58613760 inodes
  Filesystem UUID: d0afacf0-e72e-4dc1-9e9c-79c6c323ccff
  Superblock backups stored on blocks: 
	  32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	  4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
	  102400000, 214990848
  
  Allocating group tables: done                            
  Writing inode tables: done                            
  Creating journal (262144 blocks): done
  Writing superblocks and filesystem accounting information: done
  ```

  2. Can correctly add a Longhorn V2 provisioner disk to the host 

  ![image](https://github.com/user-attachments/assets/35f403a2-5b47-4fdd-a5fc-8748abc997e4)
  
  
  https://github.com/user-attachments/assets/7a8ddfab-5562-405f-bb63-417b22b8a179
  
  https://github.com/user-attachments/assets/7406fe62-1544-47a1-a4b9-0ac2478c0e27





3. Create a volume with the Longhorn V2 storage class, the volume can be created in the correct version 
  
  ![image](https://github.com/user-attachments/assets/b4af8a0c-953f-498a-a8c0-176e5c04e145)
  
  ![image](https://github.com/user-attachments/assets/225512fa-1a6d-47f4-b7d3-ada3c567dcfd)

 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Large SCSI disk with partition can be added as Longhorn V2 disk to Host $~~$</summary>


  1. And run `mkfs.ext4 /dev/sdc` to make a file system.

  ```
  v1:~ # lsblk -o NAME,TYPE,TRAN
  NAME    TYPE TRAN
  loop0   loop 
  sda     disk sata
  ├─sda1  part 
  ├─sda2  part 
  ├─sda3  part 
  ├─sda4  part 
  └─sda5  part 
  sdb     disk sata
  sdc     disk sas
  sdd     disk sas
  ```

  ```
  v1:~ # mkfs.ext4 /dev/sdc
  mke2fs 1.46.4 (18-Aug-2021)
  Creating filesystem with 1953506646 4k blocks and 244191232 inodes
  Filesystem UUID: 40467eaa-11ac-4b40-bb37-5d8f95336a62
  Superblock backups stored on blocks: 
	  32768, 98304, 163840, 229376, 294912, 819200, 884736, 1605632, 2654208, 
	  4096000, 7962624, 11239424, 20480000, 23887872, 71663616, 78675968, 
	  102400000, 214990848, 512000000, 550731776, 644972544, 1934917632
  
  Allocating group tables: done                            
  Writing inode tables: done                            
  Creating journal (262144 blocks): done
  Writing superblocks and filesystem accounting information: done
  ```

  2. Can correctly add a Longhorn V2 provisioner disk to the host 


![image](https://github.com/user-attachments/assets/27e8a5a4-a087-4cab-bf91-0be4b3e2bcdd)


  3. Create a volume with the Longhorn V2 storage class, the volume can be created in the correct version

  ![image](https://github.com/user-attachments/assets/a6fff790-53b9-46cd-ab38-ad42f3c2a21e)
  
  ![image](https://github.com/user-attachments/assets/f7104371-1a4c-46bd-8f4c-416433a59c06)


 </details>

### Test Information
* Test Environment: Single node harvester on Equinix bare-metal machine (`s3.xlarge.x86`)
* Harvester version: v1.4.0-rc4

### Verify Steps
<details><summary> Add Longhorn v2 disk with partition to host </summary>

  1. Enable the Longhorn V2 engine in settings
  2. Access the Harvester node
  3. Run `mkfs.ext4 /dev/nvme1n1` to make a file system.  
  ```
  v1:~ # mkfs.ext4 /dev/nvme1n1
  ```
  4. Add a disk in host 
  5. Select the nvme disk with partition
  6. Select Longhorn V2  
  7. Check can add the disk to host 
  8. Add node and disk tag to the host
  9. Create a storage class name `lhv2-sc` with Longhorn V2 provisioner 
  10. Select the correct node and disk tag
  11. Create a volume using the `lhv2-sc` storage class 
  12. Check the volume can be created
  13. Check in Lonhhorn dashboard to ensure the volume is in Longhorn V2 engine.

</details>

**Comment by innobead** [comment]
> PASS
>  Large SCSI disk with partition failed to be added as Longhorn V2 disk to Host 

@TachunLin for this case, it failed to add the disk for v2?

**Comment by TachunLin** [comment]
@innobead 
Sorry for the typo. It should pass to add the Large SCSI disk for Longhorn v2.  
Let me update the title.
