### ISSUE TITLE
[BUG] Websocket prompt enhancement

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#683]
**Describe the bug**

To improve user experience, websocket disconnection does not need to prompt immediately. Because it may be disconnected, the connection will be successful immediately.

Solution: Prompt after 30 seconds after disconnection (if the connection is not successful yet)

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc3

1. Disconnect from the network
2. Check the console error message
3. It will take about 1 minute before the WebSocket cannot be connected prompt appears
4. Restore the network and reconnect the WebSocket

![image](https://user-images.githubusercontent.com/19684717/115362588-45cbac00-a1f4-11eb-9345-092b6be79f83.png)
