### ISSUE TITLE
[BUG]the action is unavailable on host page

### ISSUE THREAD

**Issue by DaiYuzeng** [harvester/harvester#684]
**Describe the bug**

**To Reproduce**
1. Go to Host detail page, switch to instance tab
2. the migrate action and the backup action are both unavailable

**Expected behavior**
1. the migrate action and the backup action should be available

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc3

steps：
1. Go to Host detail page, switch to instance tab
2. Both migration and backup operations are available
