### ISSUE TITLE
[BUG] Upgrade webhook returned error message is not shown with red colour

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6847]
**Describe the bug**

**In general, the webhook returned error is shown with red colour,**

![image](https://github.com/user-attachments/assets/ba6b04f4-1197-470e-ad83-9da87b4617d9)

**But the upgrade is showing the returned error with same font as the `Warning`.**

![image](https://github.com/user-attachments/assets/93555bf4-a2dc-4607-93cf-10418290ebf7)

It is better to unify the font.

**To Reproduce**

**Expected behavior**

The returned error should be easy to be noticed.

**Support bundle**

**Environment**
 - Harvester ISO version:  Harvester v1.4.0-rc3
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Observed when validate #6754 , refer: https://github.com/harvester/harvester/issues/6754#issuecomment-2429459530

**Comment by w13915984028** [comment]
cc @torchiaf @a110605 Please check if this is an easy fix, I am ok to put this in later release. thanks.

**Comment by Yu-Jack** [comment]
This one is still not included in v1.4.0-rc4 yet, so I'll use v1.4-head to test it.

**Comment by Yu-Jack** [comment]
Test Verified on Harvester Version [v1.4-fca54eb](https://github.com/harvester/harvester/commit/fca54eb1f5ef76d0513052fbdeb24c9298384ec3)

![image](https://github.com/user-attachments/assets/3a9b3b10-5115-4706-8468-071391a30aaf)

This is a webhook error on creating VM page.

![image](https://github.com/user-attachments/assets/559dee3f-fb5a-49e5-9693-ff40fca51b96)

This is a webhook error on upgrading page.

![image](https://github.com/user-attachments/assets/f4b88649-6ba2-4a9f-a5e2-24b1906ab25c)
