### ISSUE TITLE
[BUG] Any active schedulevmbackup will block the upgrade.

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6848]
**Describe the bug**

Any active schedulevmbackup (but the timer is not reached and no backup is running) will block the upgrade.

When user creates many schedulers for many VMs, the upgrade requires the users to stop all schedulers manually before upgrade. This is not user-friendly .

https://github.com/harvester/harvester/issues/6754
https://github.com/harvester/harvester/pull/6755
Test step 8 https://github.com/harvester/harvester/issues/6754#issuecomment-2429459530

**To Reproduce**
1. Create any VM backup schedule
![image](https://github.com/user-attachments/assets/e620dfd4-c57d-441a-8101-8c31cd9a761f)

2. Click upgrade, it will block and the only solution is to suspend the schedule manually.
![image](https://github.com/user-attachments/assets/c74b4a50-3b65-407a-a91f-cec1d277d6e8)

> admission webhook "validator.harvesterhci.io" denied the request: please suspend all backup/snapshot schedule, for example default/svmbackup-vm1-ubuntu is running

**Expected behavior**

Simplify the user operation:

(1) Add a setting like `suspend-schedule` automatically when an upgrade is clicked and restore them after upgrade.

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.4.0-rc3 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

When testing https://github.com/harvester/harvester/issues/6754

**Comment by w13915984028** [comment]
@khushboo-rancher @bk201 @WebberHuang1118 @FrankYang0529 

This issue is more related to user experience. I am open to put this in next release. For v1.4.0, we need to add this limitation to the document if not updated yet. thanks.

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/6759, please see https://github.com/harvester/harvester/issues/6754#issuecomment-2430599418

@WebberHuang1118 Please see if there are any information in this issue can be added to #6759, thanks.
