### ISSUE TITLE
[DOC] VM Schedule Backup/Snapshot Feature

### ISSUE THREAD

**Issue by WebberHuang1118** [harvester/harvester#6850]
**Describe the solution you'd like**
Describing the working principle and parameters for VM Schedule Backup/Snapshot Feature

**Comment by w13915984028** [comment]
For v1.4.0, please also mention that all schedulebackup need to be suspended before an upgrade & resume after upgrade manually. thanks.

**Comment by innobead** [comment]
This issue was not added to the right milestone, even though it was finished already. 

cc @bk201 @WebberHuang1118
