### ISSUE TITLE
[BUG] GUI is broken when creating RKE1 guest cluster

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#6856]
**Describe the bug**

**To Reproduce**
1. Install Harvester (v1.4.0-rc3).
2. Install Rancher (v2.8.5, v2.9.2 or v2.9.3-alpha4).
3. Import Harvester to Rancher.
4. Create a guest cluster with RKE1 GUI.

This is RKE2.
![image](https://github.com/user-attachments/assets/3c897a9f-5afd-423d-865c-24bd0fba34d1)

This is RKE1.
![image](https://github.com/user-attachments/assets/7f868451-9d7d-4f9c-a14a-c44b4702c159)

Console Logs:
`harvester:1 Refused to apply style from 'https://192.168.1.122/assets/A.css?2.9-dev' because its MIME type ('text/plain') is not a supported stylesheet MIME type, and strict MIME checking is enabled.`

If you use 2.8.5 Rancher, it shows this url `'https://192.168.1.122/assets/A.css?2.8-dev'` instead.

Network Tabs:
![image](https://github.com/user-attachments/assets/eeba9692-31ba-47b6-b0cf-135de4598623)

**Expected behavior**
The GUI style should be normal.

**Environment**
 - Harvester ISO version: 1.4.0-rc3
 - Rancher version: v2.8.5, v2.9.2 or v2.9.3-alpha4

**Additional context**

**Comment by bk201** [comment]
cc @a110605 @torchiaf

**Comment by a110605** [comment]
I can't reproduce this issue using Rancher v2.9.2 + Harvester ipxe master-head deployment. 

https://github.com/user-attachments/assets/70631f83-3eaf-4846-bc25-d1899c9e465e


I will deploy harvester v1.4.0-rc3 and try reproduce it again.

**Comment by a110605** [comment]
Test again with Rancher 2.8.5 + Harvester v1.4.0-rc3 with chrome / edge / firefox in dark and light mode, still can't reproduce it. 

https://github.com/user-attachments/assets/5295c3b4-ac65-4daf-ba14-e9f0b6c4c41c

**Comment by bk201** [comment]
I can't reproduce with v2.9.3-alpha3, GUI looks good.

**Comment by Yu-Jack** [comment]
It's really strange. I used fresh and newly created v2.8.5 rancher alone, but the result is still the same ... Here is my command to install Rancher: `docker run -d --restart=unless-stopped -p 80:80 -p 443:443 --privileged rancher/rancher:v2.8.5`

![image](https://github.com/user-attachments/assets/b6c34877-a197-409c-934d-59c5b2e1b602)

**Comment by Yu-Jack** [comment]
umm ... after trying with `docker run -d --restart=unless-stopped -p 804:80 -p 4443:443 --privileged rancher/rancher:v2.8.5`, it works. I have no ideas why it works when changing host port. I think we could close this issue due to personal environment issue.

**Comment by bk201** [comment]
double check by @albinsun and @FrankYang0529, can't reproduce the issue.
