### ISSUE TITLE
[ENHANCEMENT] Support Force Formatted when Add disk using LHv2 Provisioner

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6859]
**Is your enhancement related to a problem? Please describe.**
* LHv1 has **Force Formatted**
  ![image](https://github.com/user-attachments/assets/2276d1f6-3ae7-47de-bd62-6fcc6976aeca)
* LHv2 has no **Force Formatted**
  ![image](https://github.com/user-attachments/assets/bb5a4ddf-5120-41e2-bbf5-97d2d8286e84)

**Describe the solution you'd like**
Provide same options as LHv1

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by Vicente-Cheng** [comment]
The disk for Longhorn V2 engine is raw type. @tserong  already has the PR (https://github.com/harvester/node-disk-manager/pull/157) do the wipefs before provision.

So, I thought we did not need this option when the disk is provisioned for v2 engine.
