### ISSUE TITLE
[BUG] The vm migration button in the VM Instacne list is not responding

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#686]
**Describe the bug**

The vm migration button in the VM Instacne list is not responding
**To Reproduce**
1. As shown below, click the `Migrate` button, no response
![image](https://user-images.githubusercontent.com/15829074/114641095-0852b480-9d04-11eb-870d-b1b3dec8ee10.png)

**Expected behavior**

**Log**

**Environment:**
 - Harvester ISO version: master-95a5828a-head
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
@TangStone 
Repeat, close this issue, and track another one  https://github.com/rancher/harvester/issues/684
