### ISSUE TITLE
[BUG] Can not Take Snapshot on LHv2 volume and VM with LHv2 volume 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6864]
**Describe the bug**
longhorn-v1.7.2 supports snapshot, see [[FEATURE] v2 data engine volume snapshot and revert](https://github.com/longhorn/longhorn/issues/6137#top).
But there seems no corresponding options on Harvester.

If this is expected then perhaps we should convert this to Enhancement.

**To Reproduce**
1. <details>
   <summary> Setup NFS backup-target
   </summary>
   
   ![image](https://github.com/user-attachments/assets/55995dbb-df6f-4b66-bc05-e9f0a92e80d6)
   </details>
   
2. <details>
   <summary> Enable LHv2 data engine and add disk and storage class
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5fda0be7-4aa6-4f19-9c1d-0d0e6a1620f4)
   </details>
   
3. <details>
   <summary> Create a VM with rootdisk using LHv1 and extra disk using LHv2
   </summary> 
   
   ![image](https://github.com/user-attachments/assets/67c2f72d-7e5b-45af-be0b-b5882acb1581)
   </details>
  
4. In **Volumes**, check actions on 2 volumes to **Take Snapshot**
   * LHv1
     ![image](https://github.com/user-attachments/assets/0419c827-fda6-4987-9add-782f9481fe2e)
   * LHv2
     ![image](https://github.com/user-attachments/assets/e7d12caf-8288-4643-80a3-88c8c3fc4746)

**Expected behavior**
LHv2 volume should support snapshot like LHv1 ones

**Support bundle**
n/a

**Environment**
* `harvester-v1.4.0-rc4`
  * Profile: 3 nodes AMD64 QEMU/KVM
  * ui-source: `Auto`

**Additional context**
1. Also not on VM with LHv2 volume
   * VM with LHv1 volume only
     ![image](https://github.com/user-attachments/assets/2e8d3d42-dc63-4039-bb86-d434551a99e8)
   * VM with LHv2 volume
     :x: No **Take Virtual Machine Snapshot**
     ![image](https://github.com/user-attachments/assets/be83c3d7-cc19-4aba-940a-9d1792cabb24)

**Comment by a110605** [comment]
The `Take snapshot` action for LHv2 volume was hidden in https://github.com/harvester/harvester/issues/6685 as dicussed with @tserong , @Vicente-Cheng, @bk201 .

There is [something wrong](https://github.com/harvester/harvester/issues/6710#issuecomment-2395999507) when restoring LHv2 snapshot.  That's why we hides the `take snapshot` action.

A bug ticket is opened : https://github.com/harvester/harvester/issues/6710

**Comment by innobead** [comment]
Let's track on #6710 instead.
