### ISSUE TITLE
[BUG] Pod prometheus-rancher-monitoring can not be started after v1.3.2 => v1.4.0-rc4 upgrade 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6891]
**Describe the bug**
![image](https://github.com/user-attachments/assets/cd1d5474-df88-431e-a692-d3163410e8d5)

```
...
prometheus ts=2024-10-27T07:18:07.980Z caller=query_logger.go:91 level=error component=activeQueryTracker msg="Error opening query log file" file=/pr │
│ ometheus/queries.active err="open /prometheus/queries.active: read-only file system" 
...
```

> [!NOTE]
> Note that this is similiar to harvester/harvester/issues/2150 but not on the prometheus pod status. Pod is `Running` in #2150 but fail to bring up in this ticket.

> [!WARNING]
> Disable and Enable rancher-monitoring does not help
> ![image](https://github.com/user-attachments/assets/43df1b45-ea6b-4942-a638-3e607d25a343)

**To Reproduce**
1. Setup single node `harvester-v1.3.2`
3. Create some VMs using different NIC
6. Enable <i>rancher-monitoring</i> addon and check metrics
8. Upgrade Harvester to `v1.4.0-rc4`
9. :x: Check metrics
   ![image](https://github.com/user-attachments/assets/683c615f-9aac-4202-87f6-491999d3a33d)

**Expected behavior**
rancher-monitoring Metrics should still work after upgrade

**Support bundle**
* upgrade log: [hvst-upgrade-cck7x-upgradelog-archive-2024-10-27T06-41-17Z.zip](https://github.com/user-attachments/files/17533104/hvst-upgrade-cck7x-upgradelog-archive-2024-10-27T06-41-17Z.zip)
* support bundle: [supportbundle_ceda6574-348e-41c1-89dc-a4a3cd1ddc1c_2024-10-27T07-34-13Z.zip](https://github.com/user-attachments/files/17533103/supportbundle_ceda6574-348e-41c1-89dc-a4a3cd1ddc1c_2024-10-27T07-34-13Z.zip)
  * Need to disable _rancher-monitoring_ first or will fail to gen SB
    ![image](https://github.com/user-attachments/assets/eaa869b6-5b4f-4def-a6f8-cb6a76c4fbb8)

**Environment**
 - Harvester ISO version: `v1.3.2` => `v1.4.0-rc4`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal HPE ProLiant DL360

**Additional context**
* Pod _prometheus-rancher-monitoring-prometheus-0_
![image](https://github.com/user-attachments/assets/72bba0ea-35dc-404f-8672-bc5f49163b34)
![image](https://github.com/user-attachments/assets/b2f3dc4d-50ae-454c-a08d-9c4e968581d1)

**Comment by w13915984028** [comment]
A quick update:

This issue is due to prometheus can't recover the previous (before upgrade) data file. A last step is to delete those file manually. Similar issue was ever reported before.

---

Why `disable/enable rancher-monitoring addon` does not recover?

The addon configuration and PV (used by prometheus) are kept after disabling and reused for enabling.

If data in PV was corrupted, the solution is to delete related files, or all files, that means prometheus can be recovered but losing some/all of the history metrics on the cluster.

---

Some references:

https://github.com/prometheus/prometheus/issues/4603
https://github.com/prometheus/prometheus/issues/6898

https://help.sap.com/docs/SAP_DATA_INTELLIGENCE_ON-PREMISE/b13b5722c8ff4bf9bb097251310031d0/8c69c688050845f9a0f15066ceb6170d.html
(Handle Corrupt Prometheus Write-Ahead Log (WAL))

**Comment by w13915984028** [comment]
Regarding the SB can't be collected when `rancher-monitoring` is enabled, we need a fix per https://github.com/harvester/harvester/issues/6898 cc @Yu-Jack

**Comment by w13915984028** [comment]
I will add a document PR to describe the workaround about how to recover from such occasional case.

**Comment by innobead** [comment]
It seems like a day 1 issue for all addons.

It's good to have a workaround doc. However, suggest creating another issue for the long-term resolution.

**Comment by Yu-Jack** [comment]
If possible, I think I could fix this in v1.4.0. Not having a support bundle is painful. cc @bk201

**Comment by Yu-Jack** [comment]
It's a quick fix https://github.com/rancher/support-bundle-kit/pull/126 for this one.

**Comment by w13915984028** [comment]
Hi @Yu-Jack , please move forward issue https://github.com/harvester/harvester/issues/6898 with your new fix, but keep this issue for prometheus WAL file broken related, thanks.

**Comment by Yu-Jack** [comment]
@w13915984028 Okay, let me move this back, thanks!

**Comment by bk201** [comment]
@w13915984028 Is the issue caused by disk failure in #6893?

**Comment by w13915984028** [comment]
@bk201 @albinsun 

It looks this issue was found on the same cluster with https://github.com/harvester/harvester/issues/6893#issuecomment-2441497440

The attached SB file also has many below error logs, the disks on the node seems broken.

```
Oct 27 06:13:37.944022 qa-191 kernel: sd 0:1:0:0: [sda] tag#425 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=2s
Oct 27 06:13:37.944460 qa-191 kernel: sd 0:1:0:0: [sda] tag#425 Sense Key : Medium Error [current] 
Oct 27 06:13:37.944700 qa-191 kernel: sd 0:1:0:0: [sda] tag#425 Add. Sense: Unrecovered read error
Oct 27 06:13:37.944918 qa-191 kernel: sd 0:1:0:0: [sda] tag#425 CDB: Read(10) 28 00 59 71 c0 00 00 04 00 00
Oct 27 06:13:37.945127 qa-191 kernel: critical medium error, dev sda, sector 1500626944 op 0x0:(READ) flags 0x4200 phys_seg 8 prio class 0
Oct 27 06:13:37.945181 qa-191 kernel: critical medium error, dev dm-0, sector 1500626944 op 0x0:(READ) flags 0x0 phys_seg 8 prio class 0
Oct 27 06:13:37.945222 qa-191 kernel: sd 5:0:0:1: [sdf] tag#112 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=2s
```

What do you think for next step? thanks.

**Comment by albinsun** [comment]
Let me retest this again with release testing, will update then.

**Comment by albinsun** [comment]
Retest PASS, close as env. issue.
Refer detail to https://github.com/harvester/tests/issues/1617#issuecomment-2458907552.

Thank you all for investiation.
