### ISSUE TITLE
[BUG] RKE2 guest cluster restart repeatedly due to low level I/Oerror after manual start following a v1.3.2 -> v1.4.0-rc4 upgrade 

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6893]
**Describe the bug**
VM shows `IOerror`
![image](https://github.com/user-attachments/assets/1849de68-bbee-4c40-83e3-86fdd4380a7f)

**To Reproduce**
1. Setup single node Harvester `v1.3.2` and import to Rancher `v2.8.8`
2. Provision a RKE2 <code>v1.27</code> cluster using <code>SLES-15.6</code>
3. Deploy Nginx and LoadBalancer
4. <details>
   <summary> Upgrade Rancher to <code>v2.8.9</code>, check RKE2 cluster still work
   </summary>
   
   * Cluster
     ![image](https://github.com/user-attachments/assets/3e8feee1-70b3-4f65-b4c6-9fe92bbba49d)
   * App
     ![image](https://github.com/user-attachments/assets/6032b48c-e92d-4a90-9323-6997756a5ba8)
   * Deployment
     ![image](https://github.com/user-attachments/assets/b649283c-930f-4c29-8550-6cd053d65bf9)
   * LoadBalancer
     ![image](https://github.com/user-attachments/assets/7d7aa711-35f4-4ba4-861a-b35abea5b482)
   </details>
 
5. <details>
   <summary> Upgrade Harvester to <code>v1.4.0-rc4</code>
   </summary>

   * Prepare air-gapped upgrade
     Ref. https://docs.harvesterhci.io/v1.4/upgrade/index#prepare-an-air-gapped-upgrade
     ![image](https://github.com/user-attachments/assets/77d95c23-7e81-4ce3-a847-0504d18fc148)
   * Before
     ![image](https://github.com/user-attachments/assets/b863c204-7e32-4485-a8f2-8fbc8744a521)
     ![image](https://github.com/user-attachments/assets/d87fd4b6-5428-4729-816f-da824e352468)
   * After
     ![image](https://github.com/user-attachments/assets/5d902053-e23e-40a0-8c8a-6646231dc492)
   </details>

6. :x: Manually start VM and wait RKE2 cluster <code>Active</code>
   * Harvester
     > VM was stopped due to single node cluster upgrade 
     ![image](https://github.com/user-attachments/assets/d163ac5d-012d-42b3-9c07-dc141ce296e7)
   * Rancher
     ![image](https://github.com/user-attachments/assets/85757d07-f428-4c4e-a6ca-fd38e4e8c61f)
   
   

**Expected behavior**
Restart VM should not have IOerror

**Support bundle**
* upgrade log: [hvst-upgrade-cck7x-upgradelog-archive-2024-10-27T06-41-17Z.zip](https://github.com/user-attachments/files/17533226/hvst-upgrade-cck7x-upgradelog-archive-2024-10-27T06-41-17Z.zip)

* Cluster rke2-sles
  * rancher2_logs: [rke2-sles-pool1-155e3ec0-n5458-2024-10-27_17_57_56.tar.gz](https://github.com/user-attachments/files/17534929/rke2-sles-pool1-155e3ec0-n5458-2024-10-27_17_57_56.tar.gz)

  * support bundle
    * [supportbundle_AfterUpgrade1_2024-10-27T07-34-13Z.zip](https://github.com/user-attachments/files/17533225/supportbundle_AfterUpgrade1_2024-10-27T07-34-13Z.zip)
    * [supportbundle_AfterUpgrade2_2024-10-27T08-08-38Z.zip](https://github.com/user-attachments/files/17533227/supportbundle_AfterUpgrade2_2024-10-27T08-08-38Z.zip)

* Cluster rke2-ubuntu
  * rancher2_logs: [rke2-ubuntu-pool1-d209b3ca-6lxf5-2024-10-27_18_14_38.tar.gz](https://github.com/user-attachments/files/17535022/rke2-ubuntu-pool1-d209b3ca-6lxf5-2024-10-27_18_14_38.tar.gz)
  * support bundle: [supportbundle_ceda6574-348e-41c1-89dc-a4a3cd1ddc1c_2024-10-27T18-18-11Z.zip](https://github.com/user-attachments/files/17535032/supportbundle_ceda6574-348e-41c1-89dc-a4a3cd1ddc1c_2024-10-27T18-18-11Z.zip)

**Environment**
 - Harvester ISO version: `v1.3.2` => `v1.4.0-rc4`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Single node Bare-metal HPE ProLiant DL360

**Additional context**
For comparism, another same Ubuntu Jammy based RKE2 cluster doest NOT hit this problem 
* Rancher
  ![image](https://github.com/user-attachments/assets/afa4b6c5-77ba-47c9-8f96-b4cb696a3af5)
* Harvester
  ![image](https://github.com/user-attachments/assets/e4e08c91-b23a-4aab-ba02-6adbc6f123eb)

**Comment by Vicente-Cheng** [comment]
The investigation:

VM: `rke2-sles-pool1-155e3ec0-n5458`
PVC: `rke2-sles-pool1-155e3ec0-n5458-disk-0-59ds8`, volume: `pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c`

We found this volume repeated re-login as below:
```
Oct 27 07:42:30.880667 qa-191 iscsid[21842]: iscsid: Connection162:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 07:46:23.221186 qa-191 iscsid[21842]: iscsid: Connection162:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 07:46:25.945519 qa-191 iscsid[21842]: iscsid: Connection170:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 07:50:28.125252 qa-191 iscsid[21842]: iscsid: Connection170:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 07:50:30.755354 qa-191 iscsid[21842]: iscsid: Connection172:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 07:54:28.129436 qa-191 iscsid[21842]: iscsid: Connection172:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 07:54:30.761804 qa-191 iscsid[21842]: iscsid: Connection174:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 07:55:05.712314 qa-191 iscsid[21842]: iscsid: Connection174:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 07:55:11.788509 qa-191 iscsid[21842]: iscsid: Connection175:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 07:58:34.109230 qa-191 iscsid[21842]: iscsid: Connection175:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 07:58:36.767787 qa-191 iscsid[21842]: iscsid: Connection177:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 08:02:54.105484 qa-191 iscsid[21842]: iscsid: Connection177:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 08:02:56.716517 qa-191 iscsid[21842]: iscsid: Connection179:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 08:03:35.896338 qa-191 iscsid[21842]: iscsid: Connection179:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 08:03:39.747591 qa-191 iscsid[21842]: iscsid: Connection180:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
Oct 27 08:06:47.125339 qa-191 iscsid[21842]: iscsid: Connection180:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is shutdown.
Oct 27 08:06:49.769960 qa-191 iscsid[21842]: iscsid: Connection182:0 to [target: iqn.2019-10.io.longhorn:pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c, portal: 10.52.0.197,3260] through [iface: default] is operational now
```

Also, we found the replica marked failed, that the reason the volume would be logout
```
2024-10-27T07:46:22.475682182Z time="2024-10-27T07:46:22Z" level=warning msg="Replica pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-r-a635133d is marked as failed, current state running, mode ERR, engine name pvc-1eec6411-15f7-41d2-9d2
c-6437c11a3c8c-e-0, active true" func="controller.(*VolumeController).ReconcileEngineReplicaState" file="volume_controller.go:731" accessMode=rwx controller=longhorn-volume currentEngine=pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-e-0 frontend=blockdev migratable=true node=qa-191 owner=qa-191 shareEndpoint= shareState= state=attached volume=pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c
2024-10-27T07:46:22.475806975Z time="2024-10-27T07:46:22Z" level=info msg="All replicas are failed, set engine salvageRequested to true" func="controller.(*VolumeController).ReconcileVolumeState" file="volume_controller.go:1339" a
ccessMode=rwx controller=longhorn-volume frontend=blockdev migratable=true node=qa-191 owner=qa-191 shareEndpoint= shareState= state=attached volume=pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c
```

So, check why replica marked error, we found that.
```
2024-10-27T07:46:19.544753162Z [pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-e-0] time="2024-10-27T07:46:19Z" level=error msg="Failed to read: index 0, off 28267073536, len 16384" func="controller.(*replicator).ReadAt" file="replicator.go:114" error="read /host/var/lib/harvester/defaultdisk/replicas/pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-0e12a90c/volume-head-000.img: no data available"
2024-10-27T07:46:19.552303466Z response_process: Receive error for response 3 of seq 43851
2024-10-27T07:46:19.556708026Z tgtd: bs_longhorn_request(111) fail to read at 28267073536 for 16384
2024-10-27T07:46:19.556717723Z tgtd: bs_longhorn_request(210) io error 0x1176dc0 28 -14 16384 28267073536, Success
2024-10-27T07:46:19.556741387Z response_process: Receive error for response 3 of seq 43853
2024-10-27T07:46:19.556768371Z response_process: Receive error for response 3 of seq 43854
2024-10-27T07:46:19.556786215Z tgtd: bs_longhorn_request(111) fail to read at 18967986176 for 524288
2024-10-27T07:46:19.556790938Z tgtd: bs_longhorn_request(210) io error 0x11ab730 28 -14 524288 18967986176, Success
2024-10-27T07:46:19.556794550Z tgtd: bs_longhorn_request(111) fail to read at 18968510464 for 524288
2024-10-27T07:46:19.556797979Z tgtd: bs_longhorn_request(210) io error 0x119b5a0 28 -14 524288 18968510464, Success
2024-10-27T07:46:19.556801343Z response_process: Receive error for response 3 of seq 43855
2024-10-27T07:46:19.556804984Z tgtd: bs_longhorn_request(97) fail to write at 18524151808 for 4096
2024-10-27T07:46:19.556808480Z tgtd: bs_longhorn_request(210) io error 0x1176840 2a -14 4096 18524151808, Success
2024-10-27T07:46:19.556952305Z [pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-e-0] time="2024-10-27T07:46:19Z" level=error msg="Setting replica tcp://10.52.0.197:11798 to ERR" func="controller.(*Controller).handleErrorNoLock" file="control.go:1177" error="tcp://10.52.0.197:11798: read /host/var/lib/harvester/defaultdisk/replicas/pvc-1eec6411-15f7-41d2-9d2c-6437c11a3c8c-0e12a90c/volume-head-000.img: no data available"
```

The replica encounters many times read errors.
Then, we check the replica and its backend disk.

We found there are some errors happening on the backend disk, as shown below
```
Oct 27 07:43:13 qa-191 kernel: sd 0:1:0:0: [sda] tag#71 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=2s
Oct 27 07:43:13 qa-191 kernel: sd 0:1:0:0: [sda] tag#71 Sense Key : Medium Error [current]
Oct 27 07:43:13 qa-191 kernel: sd 0:1:0:0: [sda] tag#71 Add. Sense: Unrecovered read error
Oct 27 07:43:13 qa-191 kernel: sd 0:1:0:0: [sda] tag#71 CDB: Read(10) 28 00 45 f9 f0 d0 00 08 00 00
Oct 27 07:43:13 qa-191 kernel: critical medium error, dev sda, sector 1174008016 op 0x0:(READ) flags 0x4200 phys_seg 17 prio class 0
...
Oct 27 07:46:19 qa-191 kernel: sd 0:1:0:0: [sda] tag#438 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=1s
Oct 27 07:46:19 qa-191 kernel: sd 0:1:0:0: [sda] tag#438 Sense Key : Medium Error [current]
Oct 27 07:46:19 qa-191 kernel: sd 0:1:0:0: [sda] tag#438 Add. Sense: Unrecovered read error
Oct 27 07:46:19 qa-191 kernel: sd 0:1:0:0: [sda] tag#438 CDB: Read(10) 28 00 57 86 8c a8 00 00 20 00
Oct 27 07:46:19 qa-191 kernel: critical medium error, dev sda, sector 1468435624 op 0x0:(READ) flags 0x4200 phys_seg 1 prio class 0
...
```
The sda6 is associated with the Longhorn default disk.
So, I thought the replica read error might related to the default disk error.

Could we test again on another environment?

**Comment by albinsun** [comment]
Try 2 more run on another machine but can not reproduce, more likely hardware issue on previous server.
Decrease the reproducibility and close.

1. Setup single node Harvester `v1.3.2` and import to Rancher `v2.8.8`
2. <details>
   <summary> Provision 2 RKE2 <code>v1.27</code> clusters
   </summary>
   
   ![image](https://github.com/user-attachments/assets/5e1eb9e6-c307-422c-8b3d-67b68d915a3c)
   </details>


4. <details>
   <summary> Deploy Nginx and LoadBalancer
   </summary>
   
   * rke2-sles
     ![image](https://github.com/user-attachments/assets/8f90a85b-d895-4c18-a3d3-b17fb2ece30f)

   * rke2-ubuntu
     ![image](https://github.com/user-attachments/assets/b68312f0-106f-4f31-be33-d1aa605b219e)
   </details>


5. <details>
   <summary> Upgrade Rancher to <code>v2.8.9</code>, check RKE2 cluster still work
   </summary>
   
   * Cluster
     ![image](https://github.com/user-attachments/assets/e6fe5691-9fbe-4b49-bed4-86f2588058cd)
   * rke2-sles
     ![image](https://github.com/user-attachments/assets/fef31e50-27bf-4c3e-a3db-845b3831d093)
     ![image](https://github.com/user-attachments/assets/7fdd6546-1ff8-4fef-bf92-8ab8ce636c2a)
   * rke2-ubuntu
     ![image](https://github.com/user-attachments/assets/eddea37e-a247-4aaf-beef-b5398ad1499c)
     ![image](https://github.com/user-attachments/assets/2c295b07-68d5-45b6-aa70-75d2b5da16e5)
   </details>
 
6. <details>
   <summary> Upgrade Harvester to <code>v1.4.0-head</code>
   </summary>

   * Prepare air-gapped upgrade
     Ref. https://docs.harvesterhci.io/v1.4/upgrade/index#prepare-an-air-gapped-upgrade
     
   * Before
     ![image](https://github.com/user-attachments/assets/d70a86e9-cfaf-465d-8f46-4ac33468de42)

   * After
     ![image](https://github.com/user-attachments/assets/005e5b45-ea32-461b-9aac-934523a9208e)
     ![image](https://github.com/user-attachments/assets/709e5b1e-ac28-49e5-9e4d-a16aca7b0ca9)
     ![image](https://github.com/user-attachments/assets/77a719f5-27c9-4211-96a7-ec6a7168eb9c)
   </details>

7. Manually start all VMs and wait RKE2 cluster <code>Active</code>
   * Harvester
     ![image](https://github.com/user-attachments/assets/5cb27375-b2a3-4c72-8fa3-f77997dac816)

   * Rancher
     ![image](https://github.com/user-attachments/assets/cc445eda-eff9-4aed-9af3-4df29939f41e)
     ![image](https://github.com/user-attachments/assets/5bd7d912-a339-4d23-a7d4-79eb0a31f202)
