### ISSUE TITLE
[BUG] Support-bundle should not set error on optional phase

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#6898]
**Describe the bug**

Support-bundle can't work unless disable `rancher-monitoring` addon

https://github.com/harvester/harvester/issues/6891#issue-2616380981

![image](https://github.com/user-attachments/assets/7adba12e-41d7-4860-90ac-8efd508454b4)

It caused the `rancher-monitoring` related POD logs can't be collected.

**To Reproduce**
1. It happend per issue #6891 when prometheus can't work properly

**Expected behavior**

SB should work as reliable as possible

https://github.com/rancher/support-bundle-kit/blob/6bd0407236d20de97b38c84a31944fe2d36d9949/pkg/manager/manager.go#L285

Prometheus is broken, above code will return error

https://github.com/harvester/harvester/blob/19bc22db86ec0c9d796ec1d9116c3ddce908082a/pkg/controller/master/supportbundle/controller.go#L152

```
...
	if managerStatus.Error {
		return h.setError(sb, managerStatus.ErrorMessage) // will cause SB to be aborted
	}
```

https://github.com/rancher/support-bundle-kit/blob/6bd0407236d20de97b38c84a31944fe2d36d9949/pkg/manager/manager.go#L189

```
func (m *SupportBundleManager) runPhase(phase RunPhase, progressCount *int, maxProgressCount int) error {
	logrus.Infof("Running phase %s", phase.Name)
	m.status.SetPhase(phase.Name)
	if err := phase.Run(); err != nil {
		m.status.SetError(err.Error())
		logrus.Errorf("Failed to run phase %s: %s", phase.Name, err.Error())
		return err
	}
...

func (m *SupportBundleManager) runAllPhases(requiredPhases []RunPhase, optionalPhases []RunPhase, postPhases []RunPhase) {

...

	for _, phase := range optionalPhases {
		if err := m.runPhase(phase, &progressCount, maxProgressCount); err != nil {
			logrus.Errorf("Failed to run optionalPhases %s: %s", phase.Name, err.Error())
			// Since it's optional, don't return error.
			continue
		}
	}

```

**Support bundle**

**Environment**
 - Harvester ISO version: Harvester v1.4.0-rc4
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by Yu-Jack** [comment]
I also notice that there is a bug for `progressCount`. If the optional phase gets error, the `progressCount` doesn't increase. But, it should increase since it's optional. I'll fix this as well.

**Comment by brandboat** [comment]
Test OK on v1.4-head, will close the issue

# Environment
- single node (12C/16G/500GB)
- v1.4-head (https://github.com/harvester/harvester/commit/c6facee407d4ea4d018ec5fa2a21de8973b2a8d5)

# Test Plan
- Follow https://github.com/harvester/harvester/pull/6905, and I can generate support bundle by either enable/disable rancher-monitoring, and when using fake prometheus, I can see logs as follows (support bundle still successfully created)

<img width="1631" alt="image" src="https://github.com/user-attachments/assets/69f80434-0a48-4e92-9dd6-8333ef57ad1e">
