### ISSUE TITLE
allow persist data volume when delete the VM

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#69]
**Description:**
allow the user to persist data volumes while deleting the VM so it can be reused later.

**Comment by guangbochen** [comment]
will add an action handler of the VM that the user can select which DV needs to be removed. cc @aiwantaozi

**Comment by gitlawr** [comment]
UI is not ready, moving this out

**Comment by guangbochen** [comment]
1. when deleting the VM, the root-disk should be selected by default 
1. need to fix the modal UI button
1. when deleting a list of VMs, change the `Select All` to `Delete All` and default to select.

cc @WuJun2016 

![image](https://user-images.githubusercontent.com/4569037/99239847-9c445100-2836-11eb-8da4-733b0f8c3deb.png)
![image](https://user-images.githubusercontent.com/4569037/99240012-d877b180-2836-11eb-9dd3-95e48fe4ae29.png)

**Comment by DoNotSayYes** [comment]
Validated
![image](https://user-images.githubusercontent.com/57614736/99938717-60b00680-2da3-11eb-92c0-656763ef4e82.png)
![image](https://user-images.githubusercontent.com/57614736/99938681-4ece6380-2da3-11eb-88f4-4708fbe0b720.png)
