### ISSUE TITLE
[DOC] Create RKE2 cluster doc user data

### ISSUE THREAD

**Issue by drewmullen** [harvester/harvester#6908]
[This page](https://docs.harvesterhci.io/v1.3/rancher/node/rke2-cluster) states how to add user data to the rancher cluster deployment when using the harvester node driver. These options dont exist on newer versions. This document should probably be re-vetted and updated accordingly:

Docs today:
<img width="719" alt="image" src="https://github.com/user-attachments/assets/6d3fd575-29b9-4cbc-b2b4-2da7cced44c4">

Harvester today:
<img width="674" alt="image" src="https://github.com/user-attachments/assets/ce88ce60-bb54-4cd8-ba54-53a7444bc8d9">

**Comment by bk201** [comment]
@drewmullen may I ask the Rancher version you use? I used Rancher 2.8.2 and the user data is hidden in the "Show Advanced" text, not the "Advanced" tab in the cluster configuration.


https://github.com/user-attachments/assets/849835cb-8231-4c5b-96ed-c7559480d9bd

**Comment by drewmullen** [comment]
@bk201 Thank you for pointing that out. yes its there for me on 2.8.2 - "advanced" vs "show advanced"... may be a way to clarify in the docs but my mistake!
