### ISSUE TITLE
[BUG] Sometimes Harvester could be unreachable

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#692]
**Describe the bug**
Sometimes Harvester could be unreachable.

**To Reproduce**
1. On the harvester VM page or any
2. Refresh the page

**Result**
Sometimes Harvester could be unreachable, clearing cookies and refreshing the page would not help. However, at the same time, it could work in another browser.
![image](https://user-images.githubusercontent.com/57614736/114686931-d104f780-9d45-11eb-9fd9-e43a3e7e554f.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by guangbochen** [comment]
close due to old version and inactivity, please open a new issue if something similar appears, thanks.
