### ISSUE TITLE
[BUG] Add a CD-ROM automatically when creating a VM using an ISO image

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#694]
**Describe the bug**
Add a CD-ROM automatically when creating a VM using an ISO image

**To Reproduce**
1. Go to the VM page
2. Create a harvester VM using the harvester ISO image,  but not adding a CR-ROM

**Result**
The harvester ISO image is not bootable due to lacking a CD-ROM
![image](https://user-images.githubusercontent.com/57614736/114692198-fe07d900-9d4a-11eb-996a-c5f5b57738f9.png)

**Suggestion**
It's better to add a CD-ROM automatically when creating a VM using an ISO image

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by guangbochen** [comment]
there are few spaces for the UX improvement that we could make upon the ISO image type:
- [x] auto change the disk type to `CD-ROM` when a `.iso` image is selected.
- [x] add a notification on the first VM image tab when the VM only contains a `CD-ROM` disk.

**Comment by DoNotSayYes** [comment]
Validated on master-head
