### ISSUE TITLE
[BUG] Management interface with a VLAN ID fails to do DHCP configuration in the interactive installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#6959]
**Describe the bug**

Management interface with a VLAN ID fails to configure in the interactive installation.
<img width="790" alt="截圖 2024-11-06 下午6 06 27" src="https://github.com/user-attachments/assets/735004f6-e490-48ba-bb05-80df05fc7b22">

**To Reproduce**
1. Boot an ISO in a network environment that only supports tagged VLAN. No DHCPD in vlan1 or non-vlan network.
2. Create a management network with a VLAN ID, and set the method to DHCP.
3. The installation can't continue.

**Expected behavior**

The installation should continue.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.4.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

- The [function](https://github.com/harvester/harvester-installer/blob/b85cf7c1a2e96037abaf908a995936ff132a1734/pkg/console/install_panels.go#L1402) always sends testing DHCP packets without a VLAN ID, even the user configure a VLAN to the management network.
- Supposed to be the cause of https://github.com/harvester/harvester/issues/3428, I'll leave https://github.com/harvester/harvester/issues/3428 open because Windows DHCPd is involved.

**Comment by w13915984028** [comment]
Test plan:

1. As per issue description, install harvester via ISO, and set a proper VLAN ID for the management network and use DHCP to get IP, the installer should get an IP successfully and continue the following steps.

When TCPDUMP is used to detect the network traffic, it will show that the DHCP related frames are encapsulated with the VLAN ID.

2. When VLAN ID is not input, the installation should also be successful.

**Comment by TachunLin** [comment]
Verified **fixed** on v1.4-head (24/11/11). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Use ISO install with <strong>proper VLAN ID</strong> for the management network to get DHCP IP   $~~$</summary>

1. ISO install and set VLAN ID on the Management NIC, it can use DHCP to get VIP IP Address correctly

  https://github.com/user-attachments/assets/6b9b4d7d-b72e-4f7a-a889-0ea3ded5bf38

2. And finish all the configuration setting, it can trigger the installation well 

  https://github.com/user-attachments/assets/4bd7db89-5d76-441b-a385-43994c292ea8



 </details>

<details><summary>$\color{green}{\textsf{PASS}}$ Use ISO install with <strong>no VLAN ID</strong> for the management network to get DHCP IP   $~~$</summary>

1. ISO install and do not set VLAN ID on the Management NIC, it can use DHCP to get VIP IP Address correctly

https://github.com/user-attachments/assets/f889335d-de61-472f-86c2-3b0a87f7a8ca


2. And finish all the configuration setting, it can trigger the installation well



 </details>

### Test Information
* Test Environment: Single node harvester on bare-metal machine and local kvm 
* Harvester version: v1.4-head (24/11/11)

### Verify Steps
<details><summary> ISO install <strong>with</strong> VLAN ID on management NIC </summary>

  1. Under the environment where the network switch can provide valid VLAN ID
  2. Use ISO install Harvester
  3. On the Configure Network page
  4. Provide the valid VLAN ID 
  5. Use the default bond mode active-backup
  6. Use DHCP as the IPv4 method
  7. Check can get VIP IP address through VLAN ID 
  8. Continue with the configuration
  9. Check can complete all the configuration to trigger Harvester installation process 

</details>

<details><summary> ISO install <strong>without</strong> VLAN ID on management NIC </summary>

  1. Under the environment where the network switch can provide valid VLAN ID
  2. Use ISO install Harvester
  3. On the Configure Network page
  4. Do not provide VLAN ID, leave it emtpy
  5. Use the default bond mode active-backup
  6. Use DHCP as the IPv4 method
  7. Check can get VIP IP address correctly 
  8. Continue with the configuration
  9. Check can complete all the configuration to trigger Harvester installation process 

</details>
