### ISSUE TITLE
Disable image URL editing

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#696]
Editing the image URL may cause confusion. For example, two VMs may use the same image but the volume data is different if they are from different image URLs. To avoid this, disable updating the image URL.

**Comment by futuretea** [comment]
![image](https://user-images.githubusercontent.com/15064560/115219266-edd06f00-a139-11eb-9365-a132b424e9d1.png)

Can't edit all image field. @WuJun2016

**Comment by kingsd041** [comment]
![image](https://user-images.githubusercontent.com/19684717/115350542-cf28b180-a1e7-11eb-95c2-43e895b58372.png)


Can't the labels and description of the image be edited? @WuJun2016

**Comment by WuJun2016** [comment]
@kingsd041  If label and describe can be edited better, we can track enhancement https://github.com/rancher/harvester/issues/719

**Comment by kingsd041** [comment]
Validate version v0.2.0-rc2

This version no longer allows modifying the image URL

**Comment by gitlawr** [comment]
I would expect users to be able to edit the description and labels.
Let me know if there are other concerns that I'm not aware of

**Comment by WuJun2016** [comment]
Fixed

**Comment by kingsd041** [comment]
Validate master-0008ce84-head

Verify the following case:
1. The image URL is not allowed to be edited
2. Image label allows editing
3. image description allows editing
