### ISSUE TITLE
[BUG] [UI] v1.4.0-rc4 storage class page shows error

### ISSUE THREAD

**Issue by a110605** [harvester/harvester#6970]
**Describe the bug**
From https://github.com/harvester/harvester/issues/6927#issuecomment-2461381294, follow the steps can reproduce this error

Run this (ignore the fact that we're not setting proper values, we don't intend to actually use freenas here, we just want to break the Harvester GUI):
```
> helm repo add democratic-csi https://democratic-csi.github.io/charts/
> helm repo update
> helm search repo democratic-csi
> wget https://raw.githubusercontent.com/democratic-csi/charts/refs/heads/master/stable/democratic-csi/examples/freenas-iscsi.yaml
> helm install --values freenas-iscsi.yaml freenas-iscsi democratic-csi/democratic-csi
```

Go to the Advanced: Storage Classes screen and you'll get the error "TypeError: this.$el.querySelector is not a function". Must be something about the "freenas-iscsi-csi" Storage Class created when installing democratic-csi that Harvester doesn't like for some reason.

<img width="1493" alt="Screenshot 2024-11-08 at 11 19 34 AM" src="https://github.com/user-attachments/assets/988373c6-db63-4cac-9cc4-589dd1c55acb">

**Expected behavior**
Storage class page should display correctly

**Comment by TachunLin** [comment]
Verified **fixed** on `v1.4-ce5e24e3-head` (24/11/11). Close this issue.

### Result
<details><summary>$\color{green}{\textsf{PASS}}$ Can display storage class page content well after install the freenas csi storage class $~~$</summary>

  1. After helm install `freenas-iscsi-csi` storage class 

  ```
  harv14-241111:~ # vim freenas-iscsi.yaml
  harv14-241111:~ # helm install --values freenas-iscsi.yaml freenas-iscsi democratic-csi/democratic-csi
  NAME: freenas-iscsi
  LAST DEPLOYED: Tue Nov 12 13:02:26 2024
  NAMESPACE: default
  STATUS: deployed
  REVISION: 1
  TEST SUITE: None
  ```

2. Access the Storage class page, can well display all content including the `freenas-iscsi-csi`
  ![image](https://github.com/user-attachments/assets/0db93ebd-308c-4e1f-bcd8-d47c5a391f18)



 </details>



### Test Information
* Test Environment: Single node local kvm machine
* Harvester version: `v1.4-ce5e24e3-head` (24/11/11)

### Verify Steps
<details><summary> Check storage class page content after install the freenas csi storage class </summary>

  1. Use helm command to install the  `freenas-iscsi-csi` storage class
  
  ```
  harv14-241111:~ # curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
  harv14-241111:~ # chmod 700 get_helm.sh
  harv14-241111:~ # mkdir /usr/local/bin
  harv14-241111:~ # ./get_helm.sh
  [WARNING] Could not find git. It is required for plugin installation.
  Downloading https://get.helm.sh/helm-v3.16.2-linux-amd64.tar.gz
  Verifying checksum... Done.
  Preparing to install helm into /usr/local/bin
  helm installed into /usr/local/bin/helm
  harv14-241111:~ # helm history harvester -n harvester-system 
  REVISION	UPDATED                 	STATUS  	CHART                        	APP VERSION  	DESCRIPTION     
  1       	Tue Nov 12 04:11:26 2024	deployed	harvester-0.0.0-v1.4-ce5e24e3	v1.4-ce5e24e3	Install complete
  harv14-241111:~ # helm repo add democratic-csi https://democratic-csi.github.io/charts/
  "democratic-csi" has been added to your repositories
  harv14-241111:~ # helm repo update
  Hang tight while we grab the latest from your chart repositories...
  ...Successfully got an update from the "democratic-csi" chart repository
  Update Complete. ⎈Happy Helming!⎈
  harv14-241111:~ # helm search repo democratic-csi
  NAME                              	CHART VERSION	APP VERSION	DESCRIPTION                                    
  democratic-csi/democratic-csi     	0.14.6       	1.0        	csi storage for container orchestration systems
  democratic-csi/snapshot-controller	0.2.4        	6.2.2      	csi snapshot-controller                        
  
  harv14-241111:~ # vim freenas-iscsi.yaml
  harv14-241111:~ # helm install --values freenas-iscsi.yaml freenas-iscsi democratic-csi/democratic-csi
  NAME: freenas-iscsi
  LAST DEPLOYED: Tue Nov 12 13:02:26 2024
  NAMESPACE: default
  STATUS: deployed
  REVISION: 1
  TEST SUITE: None
  
  ```
  
   
  2. Open Advanced -> Storage Class and check the content

</details>
