### ISSUE TITLE
[BUG]SR-IOV vGPU devices not showing up after enabling nvidia-driver-toolkit

### ISSUE THREAD

**Issue by PhlegmingChee** [harvester/harvester#6973]
**Describe the bug**
After enabling the addons for the nvidia-driver-toolkit and pcidevices-controller, no vGPU devices are enumerated in the Harvester UI

**To Reproduce**
1. Go to Addons, enable both pcidevices-controller and nvidia-driver-toolkit
2. Go to PCI Devices and search for NVIDIA devices and enable all of them

**Expected behavior**
I expected to see the NVIDIA GPUs listed under SR-IOV GPU Devices and / or vGPU Devices. Both tabs are empty

**Support bundle**
Support bundle attached to this report

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure: Baremetal with three Dell PowerEdge 740 nodes, with three NVIDIA Tesla T4 GPUs installed

**Additional context**
I have also attempted to do this on Harvester 1.4.0.rc5 and reproduced the same issue.
[supportbundle_a8bd0764-a68e-4876-a0bc-f543ef68ac39_2024-11-09T00-09-05Z.zip](https://github.com/user-attachments/files/17685302/supportbundle_a8bd0764-a68e-4876-a0bc-f543ef68ac39_2024-11-09T00-09-05Z.zip)

**Comment by PhlegmingChee** [comment]
I forgot to note that no pods are created:
<img width="1113" alt="image" src="https://github.com/user-attachments/assets/89924724-730b-4ca7-9fdd-e8255b08703f">

**Comment by ibrokethecloud** [comment]
NVIDIA T4 does not support sriov based vGPU devices. There is a check in the controller code which labels the nodes when a supported GPU is found and that triggers deployment of the driver.

**Comment by PhlegmingChee** [comment]
Really? Interesting because it claims it's SR-IOV capable:
<img width="1006" alt="image" src="https://github.com/user-attachments/assets/1f95dffe-d60e-4841-b1b5-c53367880cd5">

**Comment by PhlegmingChee** [comment]
This document also confirms SR-IOV support: [https://www.nvidia.com/content/dam/en-zz/Solutions/Data-Center/tesla-t4/t4-tensor-core-product-brief.pdf](url) on page 8

**Comment by PhlegmingChee** [comment]
After some back-and-forth with Nvidia support to clarify the Tesla T4's non-support of SR-IOV, I'm wondering if I should make a feature request to add support for legacy vGPUs in Harvester. The T4 is enabled as a pcidevice for passthrough, so is there any solution to attach it to a VM that way?
<img width="1773" alt="image" src="https://github.com/user-attachments/assets/f9b31517-728a-4025-bdd1-b98a6d2ed98d">

**Comment by ibrokethecloud** [comment]
the T4 can be fully passed through to the VM like any other pcidevice

**Comment by PhlegmingChee** [comment]
Just wondering if I'm doing this correctly because my VM doesn't add the GPU using passthrough. This is some output on the bare-metal host to confirm it sees the GPUs

<img width="1119" alt="image" src="https://github.com/user-attachments/assets/01c161c3-2748-4cb4-acc3-2691ddce9c83">

I'm adding the PCI device this way:
<img width="1776" alt="image" src="https://github.com/user-attachments/assets/48bf3783-f73d-43db-9e0f-dbafb0789fe2">
I've added the VM's yaml file for you as I can't see the PCI device or a claim for a vfio-pci device: 
[vgpu-jammy.yaml.zip](https://github.com/user-attachments/files/17734250/vgpu-jammy.yaml.zip)

Finally, this output from the VM shows no passthrough of the GPU
<img width="1250" alt="image" src="https://github.com/user-attachments/assets/2f9fa90a-e0db-4336-8c2a-1721236d3912">

**Comment by PhlegmingChee** [comment]
RTFM applies here. Just realized where I messed up:
<img width="1787" alt="image" src="https://github.com/user-attachments/assets/7c65f8b3-7d4c-4a30-b527-a108d600ae1d">

**Comment by PhlegmingChee** [comment]
Just to confirm, the PCI Device passthrough of the Tesla T4 works:
<img width="914" alt="image" src="https://github.com/user-attachments/assets/450a4984-b0c1-4a61-9bda-2a4799bed56a">
