### ISSUE TITLE
[BUG] netmask config on static up fails

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#698]
**Describe the bug**

when configuring a static ip and pressing down to move to netmask, the installer drops into a shell

**To Reproduce**
1. Load the installer
2. Specify a hostname and Ethernet interface
3. Tab to change dhcp to static 
4. Input the IP and press down to go to netmask

**Expected behavior**

the prompt should move to netmask and allow to input the address

**Log**

**Environment:**
 - Harvester ISO version: 2 rc2
 - Installation Mode: ISO
 - Underlying Infrastructure  Baremetal with Dell PowerEdge R620

**Additional context**

**Comment by futuretea** [comment]
![image](https://user-images.githubusercontent.com/15064560/114954481-44655100-9e8d-11eb-85a5-797af402d708.png)
@abonillabeeche  I think you mean the `Gateway` input box.
The value of `IPv4 Address` must be a CIDR address
The reason for the abnormal exit is most likely that the screen is too small to display the error message bar.
Can you help to check logs on `/var/log/console.log`? Thanks

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/673
