### ISSUE TITLE
[BUG] Can not select upgrade version from Rancher UI

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#6982]
**Describe the bug**
From Rancher, **AVAILABLE COMPATIBLE VERSION** dropdown list is empty
![image](https://github.com/user-attachments/assets/6e02cc27-fa29-4a8e-81e1-b1ceaaa2bf2d)

**To Reproduce**
1. Import Harvester `v1.3.2` to Rancher `v2.9.3`
2. Prepare airgapped upgrade to `v1.4.0-rc5`
   > Ref. https://docs.harvesterhci.io/v1.4/upgrade/index#prepare-an-air-gapped-upgrade
3. On Harvester -> Click **Upgrade** -> Click **AVAILABLE COMPATIBLE VERSION**, can select `v1.4.0-rc5`
   ![image](https://github.com/user-attachments/assets/09e92456-5574-4c5b-ad47-3a1a8de26cd8)
4. :warning: On Rancher -> Virtualization Management -> Harvester -> Click **Upgrade** -> Click **AVAILABLE COMPATIBLE VERSION**, no content in dropdown list.
   ![image](https://github.com/user-attachments/assets/6e02cc27-fa29-4a8e-81e1-b1ceaaa2bf2d)

**Expected behavior**
Should be able to trigger upgrade from Rancher side.

**Support bundle**
[supportbundle_296ee449-9a35-4cc2-9cac-9b18a97fbb1a_2024-11-12T04-46-25Z.zip](https://github.com/user-attachments/files/17711274/supportbundle_296ee449-9a35-4cc2-9cac-9b18a97fbb1a_2024-11-12T04-46-25Z.zip)

**Environment**
 - Harvester version: `v1.3.2`
 - Rancher version: `v2.9.3` 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Additional context**
* Firefox gives the same result
  ![image](https://github.com/user-attachments/assets/93625e8a-065a-43b9-8341-24aaa4b2095c)

**Comment by albinsun** [comment]
Similar to https://github.com/harvester/harvester/issues/6522

**Comment by bk201** [comment]
@torchiaf can you help investigate the issue?

**Comment by lanfon72** [comment]
Is it same as #6522 ?

**Comment by a110605** [comment]
The related [fixed PR](https://github.com/harvester/dashboard/pull/1163) is already merged in master and v1.4 release branch. For v1.3, we hasn't merge fixed PR yet.
https://github.com/harvester/dashboard/pull/1197

**Comment by bk201** [comment]
Duplicated with https://github.com/harvester/harvester/issues/6559, Thanks @a110605 and @lanfon72 .
