### ISSUE TITLE
[ENHANCEMENT] [GUI] Show warning message for Longhorn V2 unsupported actions

### ISSUE THREAD

**Issue by torchiaf** [harvester/harvester#6989]
**Is your enhancement related to a problem? Please describe.**

Some table actions in Volumes and Virtual Machine tables are not supported when using Longhorn V2

**Describe the solution you'd like**

We want to show a warning message to inform the users why they are disabled and add a link to Harvester -> Longhorn v2 docs.

![image (4)](https://github.com/user-attachments/assets/8a633598-716c-45b3-84ba-8677a74c9ef6)

**Describe alternatives you've considered**

**Additional context**

**Comment by irishgordo** [comment]
Thanks for this enhancement @torchiaf  :smile: :+1: 

This looks good on  Version: v1.4-bede7c36-head 

I'll go ahead and close this out :smile: 

![Screenshot from 2024-11-15 15-12-09](https://github.com/user-attachments/assets/31c3f14d-920d-4935-a469-1f410f5d3e7e)
![Screenshot from 2024-11-15 15-11-24](https://github.com/user-attachments/assets/328adcd2-c6b6-480a-aabd-e41e1eb09598)
![Screenshot from 2024-11-15 15-10-53](https://github.com/user-attachments/assets/f3d98f88-098f-439c-9984-831a4f0222a3)
