### ISSUE TITLE
[ENHANCEMENT] Bump Harvester CSI Driver 0.1.21 to Rancher/RKE2

### ISSUE THREAD

**Issue by Vicente-Cheng** [harvester/harvester#6991]
**Is your enhancement related to a problem? Please describe.**
Bump Harvester CSI driver for issues like below:
- https://github.com/harvester/harvester/issues/6981
- https://github.com/harvester/harvester/issues/6849

**Describe the solution you'd like**
Bump Harvester CSI Driver

**Describe alternatives you've considered**
None

**Additional context**
None

**TODO**
- [x] new release - [v0.2.2](https://github.com/harvester/harvester-csi-driver/releases/tag/v0.2.2)
- [x] new chart - [harvester-csi-driver-v0.1.21](https://github.com/harvester/charts/releases/tag/harvester-csi-driver-0.1.21)
- [x] Rancher side
  - v2.8: https://github.com/rancher/charts/pull/4749
  - v2.9: https://github.com/rancher/charts/pull/4750
  - v2.10: https://github.com/rancher/charts/pull/4761
- [x] RKE2 side
  - chart: https://github.com/rancher/rke2-charts/pull/564
  - https://github.com/rancher/rke2/pull/7282
  - https://github.com/rancher/rke2/pull/7283
  - https://github.com/rancher/rke2/pull/7284
  - https://github.com/rancher/rke2/pull/7285
  - https://github.com/rancher/rke2/pull/7286 (v1.28 will not have any new release, closed)

**Comment by khushboo-rancher** [comment]
cc: @rebeccazzzz for helping with creating issues for rke2 and tagging them for rke2 next release.

**Comment by khushboo-rancher** [comment]
### Validation Summary: Rancher Charts and RKE2  

#### Validation Steps:  

1. **Deploy CSI Latest Version and Verify Functionality**  
    - Deploy a PVC with Harvester storage class.  
    - Attach to a workload; verify the volume attachment in Longhorn.  
    - Scale down the workload to 0; verify the volume detachment in Longhorn.  

2. **Uninstall the Chart**  
   - Verify the uninstallation process.  

3. **Upgrade Scenario Validation**  
     - Deploy CSI version **v0.1.18**.  
     - Deploy a PVC with Harvester storage class.  
     - Attach to a workload; verify the volume attachment in Longhorn.  
     - Scale down the workload to 0; confirm volume fails to reattach.  
     - Upgrade CSI version to **v0.1.21**.  
     - Verify that attachment works post-upgrade.  

---

#### **Rancher Chart Update**  
- CSI version **0.1.21** has been bumped in the following branches:  
  - `2.10`, `2.9`, `2.8`.  
- Users running Rancher versions from these branches can access the updated CSI chart in the **Apps** section.  

Details - https://github.com/harvester/tests/issues/1686

---

#### **RKE2 Validation**  

1. **Rancher v2.10.1-alpha1**  
   - RKE2 Versions:  
     - `v1.31.4-rc1+rke2r1`  
     - `v1.30.8-rc1+rke2r1`  
     - `v1.29.12-rc1+rke2r1`  
   - Tested with **Harvester v1.4.0**.  
   - Details: [[Issue Comment Link](https://github.com/harvester/tests/issues/1729#issuecomment-2549439027)](https://github.com/harvester/tests/issues/1729#issuecomment-2549439027).  

2. **Rancher v2.9.3**  
   - RKE2 Versions:  
     - `v1.30.8-rc1+rke2r1`  
     - `v1.29.12-rc1+rke2r1`  
   - Tested with **Harvester v1.4.0**.  
   - Details: [[Issue Comment Link](https://github.com/harvester/tests/issues/1729#issuecomment-2552028425)](https://github.com/harvester/tests/issues/1729#issuecomment-2552028425).
