### ISSUE TITLE
[BUG] Harvester 1.3.2 Volume Attachment Issues

### ISSUE THREAD

**Issue by xelab04** [harvester/harvester#7001]
**Describe the bug**
When I create a VM, it creates the associated volume. However, the VM is stuck in `A start job is running for /dev/disk/by-uuid ` with the uuid of the disk in question. The same happens if I create a volume directly - using the same iso image.

I accessed the Longhorn UI and saw that 0b were used out of the allocated space - which makes sense as the volume couldn't even get mounted for the OS to be installed onto it.

**To Reproduce**
1. Install Harvester v1.3.2.
2. Create a VM, and attempt to install onto the volume. I used openSUSE-Leap-15.6-Minimal.

**Expected behavior**
The volume should be properly mounted to the VM, and the OS iso image should be able to be "applied" to an independent volume.

**Environment**
 - Harvester v1.3.2
 - Baremetal servers
 - Longhorn with iscsid.service enabled (is not enabled by default)

**Additional context**
I did not have this problem on v1.3.1 though someone else had setup the cluster before me so I do not know if there is additional config I may have missed.

Installation used mostly defaults.
```
> kubectl get nodes
NAME           STATUS   ROLES                       AGE   VERSION
harvester-01   Ready    control-plane,etcd,master   28h   v1.28.12+rke2r1
harvester-2    Ready    <none>                      27h   v1.28.12+rke2r1
```

**Comment by Vicente-Cheng** [comment]
Hi @xelab04, 
Could you generate a support bundle?
That would help us to investigate your question.

Thanks!

**Comment by xelab04** [comment]
@Vicente-Cheng 
![image](https://github.com/user-attachments/assets/5716832b-bb6c-45c6-b0a3-83eeb023be87)
[supportbundle_alex_storage_attachmentissue.zip](https://github.com/user-attachments/files/17794707/supportbundle_alex_storage_attachmentissue.zip)

**Comment by xelab04** [comment]
Something additional I thought of. This instance of Harvester was installed through the iso file, replacing a previous installation. The installer said it was going to reformat the drive, but I believe it reformated only the OS drive, and not the second storage device where I pointed Longhorn to.
It may be possible that some configuration files were left over on this second partition, causing Longhorn to misbehave with the new Harvester installation.

**Comment by xelab04** [comment]
I decided to `rm -rf *` on the storage device, and restart longhorn. Though now this causes an issue where the volume won't be created. State is stuck in "attaching".
![image](https://github.com/user-attachments/assets/7d948390-1f2e-4a73-977a-45a3a288f1e3)

**Comment by xelab04** [comment]
I have deleted my previous comments.
I rm -rf'd sdb, and reinstalled Harvester, to override sda.
This is a completely fresh Harvester installation and the issue is still present.

I strongly doubt that this has anything to do with me reinstalling Harvester, and replacing a previous installation. Here's the cleanest support bundle possible - nothing else except a VM and a volume.
[supportbundle_alex_stillstorage.zip](https://github.com/user-attachments/files/17814509/supportbundle_alex_stillstorage.zip)

**Comment by xelab04** [comment]
On the fresh install, iscsid.service is disabled and is not running on boot. I assume the following may be related?
`> kubectl describe pod virt-launcher-test-xxxxx`
```
Warning  FailedMapVolume   58s (x25 over 61s)  kubelet            MapVolume.SetUpDevice failed for volume "pvc-346e61f4-9ea8-444a-aecc-bab9ce366a10" : kubernetes.io/csi: blockMapper.SetUpDevice failed to get CSI client: driver name driver.longhorn.io not found in the list of registered CSI drivers
```

**Comment by bpedersen2** [comment]
Can it be the iscsi option?  Did you try without it?

**Comment by xelab04** [comment]
@bpedersen2 hello, thank you. What do you mean by iscsi option? Where would I go to turn it on/off?
I should also add that the default behaviour on a fresh install is that iscsid.service is disabled and not running.

Both iscsid on or off have the same issue - though I'm unaware if there's some config I need to change inside harvester for that

**Comment by xelab04** [comment]
When enabled, iscsid seems to work properly.
`systemctl status iscsid`
`Nov 20 06:59:24 harvester-1 iscsid[9317]: iscsid: Connection3:0 to [target: iqn.2019-10.io.longhorn:pvc-c4ed30e7-6ef7-48e8-8e9d-d9461ed6b4b8, portal: 10.52.0.171,3260] through [iface: default] is operational now`

With iscsid.socket on, and iscsid.service off, the volume does attach, though the same as above happens, as the socket turns the service back on, it seems.

Disabling iscsid.service and iscsid.socket cause the volume to never attach to the VM, and the VM doesn't even enter the running state. 

I went to check permissions for the replica file, though it's fairly unlikely to be the cause as Harvester would usually take care of this well on install.
```
harvester-1:/home/rancher # ls -l /var/lib/harvester/defaultdisk/
total 32
drw-r--r-- 3 root root  4096 Nov 19 11:25 backing-images
-rw-r--r-- 1 root root    51 Nov 19 11:12 longhorn-disk.cfg
drwx------ 2 root root 16384 Nov 19 10:57 lost+found
drwxr-xr-x 3 root root  4096 Nov 20 06:59 replicas
drw-r--r-- 2 root root  4096 Nov 19 11:25 tmp

harvester-1:/home/rancher # ls -l /var/lib/harvester/defaultdisk/replicas/
total 4
drwx------ 2 root root 4096 Nov 20 06:59 pvc-c4ed30e7-6ef7-48e8-8e9d-d9461ed6b4b8-e81e5bc0
harvester-1:/home/rancher # 
```

**Comment by bk201** [comment]
@xelab04 this should be image issue, can you try this image instead: https://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.6/images/openSUSE-Leap-15.6.x86_64-NoCloud.qcow2

**Comment by xelab04** [comment]
@bk201 you absolute legend. I spent 2 weeks on this without so much as considering the image was bad. Thank you infinitely. Thank you to everyone else who helped as well.
