### ISSUE TITLE
[BUG] Upgrade from v1.3.2 with PCI passthrough and vGPUs has issues running VMs after upgrade

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#7002]
**Describe the bug**

After upgrade of 2 node cluster with PCI passthrough and vGPUs enabled on VMs the PCI passthrough VM wouldn't start and the vGPU isn't working on the VM that had one assigned. It also added an extra vGPU

**To Reproduce**
1. Create a 2 node cluster running v1.3.2
2. Set up one node with PCI passthrough device (I used a GPU)
3. Set up the other node with vGPU enabled
4. Create a VM with the PCI passthrough device
5. Create a VM with vGPU enabled on it
6. Validate both PCI GPU and vGPU work on the VMs
7. Turn off the VMs
8. Upgrade to v1.4-head
9. Start the VMs
10. Try to validate that both VMs are working

**Expected behavior**

The VMs should turn on and the GPU/vGPU should work as they did before the upgrade
**Support bundle**

The support bundle is too large to upload. Please reach out if you need it

**Environment**
 - Harvester ISO version: `v1.3.2` -> `v1.4-ce5e24e3-head`
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): 2 bare metal DL360s

**Additional context**

![Greenshot 2024-11-13 15 21 20](https://github.com/user-attachments/assets/2229c6d9-e104-4592-bfab-24896d959f9a)
![Greenshot 2024-11-13 15 20 42](https://github.com/user-attachments/assets/286ca6c7-abe9-471b-8e90-26ff71f6bb68)
![Greenshot 2024-11-13 15 20 32](https://github.com/user-attachments/assets/55154edc-7174-4825-bf63-371ae15a88a3)

[hvst-upgrade-tkj4z-upgradelog-archive-2024-11-13T23-21-33Z.zip](https://github.com/user-attachments/files/17740578/hvst-upgrade-tkj4z-upgradelog-archive-2024-11-13T23-21-33Z.zip)

**Comment by noahgildersleeve** [comment]
This seems to be related to #6892

**Comment by noahgildersleeve** [comment]
After debugging the PCI passthrough device issue with @ibrokethecloud this seems to be the workaround

1. Turn off the VM
2. Remove the PCI device from the VM
3. Disable passthrough on the device
4. Enable passthrough on the device
5. Add the device to the VM
6. Turn the VM back on

This seems to have resolved that issue, and I was able to validate the GPU was working when the VM came back on.

**Comment by bk201** [comment]
should be fix with https://github.com/harvester/harvester/issues/7003

**Comment by noahgildersleeve** [comment]
The PCI device issue is a dupe of #6892. I'm closing this issue due to it being addressed by #7003 and #6892.
