### ISSUE TITLE
[BUG] During vm migration, vm status show Running on vm detail page

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#701]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/114960749-4386ec00-9e9a-11eb-8097-9e7d96c18b07.png)

**To Reproduce**
1. go to vm detail page
2. migrate a vm

**Expected behavior**

vm status show Migrating

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
@futuretea  @guangbochen  vm status and migration status are separate, I think it’s better not to change .

**Comment by guangbochen** [comment]
I think they should be consistent, even though we know the VM is running as it is live migration, but the `migrating` status should be prioritized.

**Comment by TangStone** [comment]
### Validation in version master-0008ce84-head
migrate a vm,  vm status show Migrating on vm detail page
![image](https://user-images.githubusercontent.com/15829074/115508313-bf74a000-a2af-11eb-9191-6a9be8f4ff1d.png)
