### ISSUE TITLE
[BUG] Can't generate vm template if vm is stopped

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#702]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/114962149-ca3cc880-9e9c-11eb-9c6a-f18efc20331c.png)
![image](https://user-images.githubusercontent.com/15064560/114962351-1ab42600-9e9d-11eb-9965-27f0f5d1956f.png)

**To Reproduce**
1. stop a vm
2. check if vm can generate template

**Expected behavior**

also can generate vm template when vm is stopped

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
@WuJun2016 should allow users to specify the template name and description when creating a VM template from the existing VM.

**Comment by futuretea** [comment]
validated on master-0008ce84-head

![image](https://user-images.githubusercontent.com/15064560/115501466-d6ae9000-a2a5-11eb-9415-74fc60303121.png)
![image](https://user-images.githubusercontent.com/15064560/115501629-23926680-a2a6-11eb-9f4c-1a55d1f88722.png)
