### ISSUE TITLE
[QUESTION] After a 3-node cluster is powered off and restarted, one node cannot start.

### ISSUE THREAD

**Issue by seajelly** [harvester/harvester#7028]
The rke2-server of the node02 node cannot be started and the following prompt appears.
version: v1.3.0

systemcl status rke2-server
lines 1-32/32 (END)...skipping...
● rke2-server.service - Rancher Kubernetes Engine v2 (server)
     Loaded: loaded (/etc/systemd/system/rke2-server.service; enabled; vendor preset: disabled)
    Drop-In: /etc/systemd/system/rke2-server.service.d
             └─override.conf
     Active: activating (start) since Wed 2024-11-20 06:48:15 UTC; 1min 44s ago
       Docs: https://github.com/rancher/rke2#readme
    Process: 43608 ExecStartPre=/bin/sh -xc ! /usr/bin/systemctl is-enabled --quiet nm-cloud-setup.service (code=exited, status=0/SUCCESS)
    Process: 43610 ExecStartPre=/sbin/modprobe br_netfilter (code=exited, status=0/SUCCESS)
    Process: 43611 ExecStartPre=/sbin/modprobe overlay (code=exited, status=0/SUCCESS)
    Process: 43612 ExecStartPre=/usr/sbin/harv-update-rke2-server-url server (code=exited, status=0/SUCCESS)
   Main PID: 43614 (rke2)
      Tasks: 265
     CGroup: /system.slice/rke2-server.service
             ├─  5462 /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2 -namespace k8s.io -id 50f68a233e8a8ffe729162fd4f02aed50ee78bf0af99f22ed7f1bc79579aa3dd -address /run/k3s/containerd/containerd.sock
             ├─  5463 /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2 -namespace k8s.io -id 0d9697adffd36d8c19cd8a0f47ea3f86f505b47c5d915e0ebfd6a06a4fb0af8a -address /run/k3s/containerd/containerd.sock
             ├─  5469 /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2 -namespace k8s.io -id a955eca31e7f39866fef802935abf1b399bf59b1605c91598e4a4082027d3f67 -address /run/k3s/containerd/containerd.sock
             ├─  5507 /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2 -namespace k8s.io -id d69af40c8e5b82c1e3615dcb64129eaaf80e6add056e7c5f70f093c6425f04c2 -address /run/k3s/containerd/containerd.sock
             ├─  5508 /var/lib/rancher/rke2/data/v1.27.10-rke2r1-31de34f39de5/bin/containerd-shim-runc-v2 -namespace k8s.io -id c617823f79288762a7c2aacf11a66c51162120873f4988627879aff0f0cb0e9b -address /run/k3s/containerd/containerd.sock
             ├─ 43614 "/opt/rke2/bin/rke2 server"
             ├─ 43679 containerd -c /var/lib/rancher/rke2/agent/etc/containerd/config.toml -a /run/k3s/containerd/containerd.sock --state /run/k3s/containerd --root /var/lib/rancher/rke2/agent/containerd
             └─ 43796 kubelet --volume-plugin-dir=/var/lib/kubelet/volumeplugins --file-check-frequency=5s --sync-frequency=30s --address=0.0.0.0 --anonymous-auth=false --authentication-token-webhook=true --authorization-mode=Webhook --cgroup-driver=systemd --client-ca-file=/var/lib/rancher/rke2/agent/client-ca.crt --cloud-provider=external --cluster-dns=10.53.0.10 --cluster-domain=cluster.local --container-runtime-endpoint=unix:///run/k3s/containerd/containerd.sock --containerd=/run/k3s/containerd/containerd.sock "--eviction-har>

Nov 20 06:49:45 har-node02 rke2[43614]: {"level":"info","ts":"2024-11-20T06:49:45.56028Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/client.go:210","msg":"Auto sync endpoints failed.","error":"context deadline exceeded"}
Nov 20 06:49:45 har-node02 rke2[43614]: time="2024-11-20T06:49:45Z" level=info msg="Waiting for etcd server to become available"
Nov 20 06:49:45 har-node02 rke2[43614]: time="2024-11-20T06:49:45Z" level=info msg="Waiting for API server to become available"
Nov 20 06:49:48 har-node02 rke2[43614]: {"level":"warn","ts":"2024-11-20T06:49:48.322313Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc001170380/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
Nov 20 06:49:48 har-node02 rke2[43614]: time="2024-11-20T06:49:48Z" level=error msg="Failed to check local etcd status for learner management: context deadline exceeded"
Nov 20 06:49:48 har-node02 rke2[43614]: time="2024-11-20T06:49:48Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Nov 20 06:49:53 har-node02 rke2[43614]: time="2024-11-20T06:49:53Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
Nov 20 06:49:55 har-node02 rke2[43614]: {"level":"warn","ts":"2024-11-20T06:49:55.562438Z","logger":"etcd-client","caller":"v3@v3.5.9-k3s1/retry_interceptor.go:62","msg":"retrying of unary invoker failed","target":"etcd-endpoints://0xc001170380/127.0.0.1:2379","attempt":0,"error":"rpc error: code = DeadlineExceeded desc = latest balancer error: last connection error: connection error: desc = \"transport: Error while dialing: dial tcp 127.0.0.1:2379: connect: connection refused\""}
Nov 20 06:49:55 har-node02 rke2[43614]: time="2024-11-20T06:49:55Z" level=info msg="Failed to test data store connection: context deadline exceeded"
Nov 20 06:49:58 har-node02 rke2[43614]: time="2024-11-20T06:49:58Z" level=info msg="Waiting to retrieve kube-proxy configuration; server is not ready: https://127.0.0.1:9345/v1-rke2/readyz: 500 Internal Server Error"
~
~
~

Viewed etcd logs
 
Log prompt cannot restore from snapshot
![image](https://github.com/user-attachments/assets/2335e438-04b3-4935-bd5b-9176038a26fc)
I found that the snapshot still exists
![image](https://github.com/user-attachments/assets/76755b64-7eb8-4066-8cc0-f05840771d1b)

How will I restore this node, hope you guys can give suggestions

**Comment by revgit12** [comment]
@seajelly 
What is the resolution for it. I think I am facing same issue
