### ISSUE TITLE
[BUG] Can't backup vm if vm is stopped

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#703]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/114962149-ca3cc880-9e9c-11eb-9c6a-f18efc20331c.png)
![image](https://user-images.githubusercontent.com/15064560/114962351-1ab42600-9e9d-11eb-9965-27f0f5d1956f.png)

**To Reproduce**
1. stop a vm
2. check if vm can backup

**Expected behavior**

also can backup vm when vm is stopped

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
### Validation in version master-0008ce84-head
**Step**
1. Create a vm successfully and write some data to the vm
![image](https://user-images.githubusercontent.com/15829074/115502305-4b35fe80-a2a7-11eb-8b5b-837491c41ca7.png)
2. stop  vm
![image](https://user-images.githubusercontent.com/15829074/115502777-03fc3d80-a2a8-11eb-8e46-009c39528286.png)
3. check if vm can backup
![image](https://user-images.githubusercontent.com/15829074/115502811-15454a00-a2a8-11eb-9b2a-80bdcc23eb05.png)
![image](https://user-images.githubusercontent.com/15829074/115502884-34dc7280-a2a8-11eb-94cf-aa1ed624aba3.png)
![image](https://user-images.githubusercontent.com/15829074/115503124-8258df80-a2a8-11eb-87c5-cd5822ad0de0.png)
4. Restore vm using a backup of stop vm
![image](https://user-images.githubusercontent.com/15829074/115503469-090dbc80-a2a9-11eb-8a45-d36f9d3a7668.png)
