### ISSUE TITLE
[FEATURE] Add VLAN 1 by default

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#704]
**Is your feature request related to a problem? Please describe.**

Users often don't know how to configure a public IP address to the VMs.

**Describe the solution you'd like**

We can add a network of VLAN 1 by default when creating a VM if VLAN is open. 

**Describe alternatives you've considered**

None

**Additional context**

None

**Comment by guangbochen** [comment]
added on the doc https://github.com/rancher/harvester/pull/589
