### ISSUE TITLE
[FEATURE] Show detailed information about vm status

### ISSUE THREAD

**Issue by WuJun2016** [harvester/harvester#705]
**Is your feature request related to a problem? Please describe.**
When the vm status is not running, display the detailed information of the associated crd, such as the error message of pod or vmi

**Comment by WuJun2016** [comment]
![image](https://user-images.githubusercontent.com/24985926/115192111-f1a1c880-a11c-11eb-9d75-dec608762d2f.png)

**Comment by kingsd041** [comment]
When the vm is in the failed migration state, no error message can be seen on the vm state, and it cannot be migrated again.

The migration failure can be reproduced by the following operations:
1. Migrate vm from host A to host B
2. Shutdown host B
3. Restart the vm

**Comment by gitlawr** [comment]
For failed migrations(https://github.com/harvester/harvester/issues/693#issuecomment-824591476), in some cases reason for the failure is not available.
If the `VMI.status.migrationState` is correctly set, we should be able to get the event message for the details(REASON==Migrated)
```
LAST SEEN   TYPE      REASON                       OBJECT                                                 MESSAGE
23m         Warning   Migrated                     virtualmachineinstance/lawr                            VirtualMachineInstance migration uid c01c564e-f93e-4a06-856d-3af245d00ca8 failed. reason:Live migration failed virError(Code=9, Domain=31, Message='operation failed: guest CPU doesn't match specification: missing features: ss,fma,movbe,f16c,rdrand,fsgsbase,bmi1,avx2,smep,bmi2,erms,invpcid,abm')
34m         Normal    Migrated                     virtualmachineinstance/test                            The VirtualMachineInstance migrated to node node1.
32m         Normal    Migrated                     virtualmachineinstance/test                            The VirtualMachineInstance migrated to node node1.
28m         Warning   Migrated                     virtualmachineinstance/test                            VirtualMachineInstance migration uid e024cf21-2a4f-4036-9299-8bf5e55f9b2f failed. reason:Live migration failed virError(Code=1, Domain=7, Message='internal error: client socket is closed')
```

**Comment by kingsd041** [comment]
validated on v0.2.0-rc4
![image](https://user-images.githubusercontent.com/19684717/116188735-7f536880-a75a-11eb-8e6d-0cb13db07a54.png)
![image](https://user-images.githubusercontent.com/19684717/116190655-9cd60180-a75d-11eb-8a87-3d85254c210d.png)
