### ISSUE TITLE
Log rotation for k3s logs

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#706]
The `/var/log/k3s-service.log` can be large in size as time goes.

Related: https://github.com/rancher/k3os/issues/433

**Comment by guangbochen** [comment]
@bk201 can u PTAL if the rke2 has a similar issue or do they support log compression?

**Comment by bk201** [comment]
Service logs are record in journald in RancherOSv2. Currently, we are using the default settings:
- All systemd unit's logs are consolidated together.
- They are compressed by default.
- The maximum journal size is 10% of the filesystem capacity (which is the size of cOS persistent partition). But the value is capped to 4GB.
- The journal is rotated when it reach 1/8 of maximum journal size. The whole journal file is rotated, not individual service logs.

We can tune the settings if necessary.

**Comment by bk201** [comment]
In the new OS, we collect logs of each boot and limit the size to 10MB.
https://github.com/rancher/support-bundle-kit/pull/17/files#diff-0cddcf1d434947801c187310d89bbf0779d515df7332c932b669c6c30cb0c879R27

**Comment by guangbochen** [comment]
close in favor of the newOS and support-bundle-kit update, please feel free to reopen it if u encounter a large size rke2 logs.
