### ISSUE TITLE
[BUG] Two machine instances are existing upon one node and cause the node stuck on cordon state

### ISSUE THREAD

**Issue by w13915984028** [harvester/harvester#7065]
**Describe the bug**

User reported:
>Some Harvester hosts were temporarily removed from Harvester (following the steps in the documentation) and then re-added. Since they were re-added, they persistently remain in cordoned state, despite being manually uncordoned.

A node  shows:
```
...
    name: hpci01
    resourceVersion: "114922467"
    uid: 14fb39ff-1507-4030-9a8c-fe96defcfa0b
  spec:
    podCIDR: 10.52.29.0/24
    podCIDRs:
    - 10.52.29.0/24
    providerID: rke2://hpci01
    taints:
    - effect: NoSchedule
      key: node.kubernetes.io/unschedulable
      timeAdded: "2024-11-28T06:13:39Z"
    unschedulable: true
...
```

And the manual `uncordon` operation does not work.

After investigation, we found:

The `hpci01` has 2 machines, one related to already-deleted node, and one related to new node. Apparently, the old machine object was not deleted, and it is just battling with new machine and causing the issue.

```
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:

    creationTimestamp: "2024-09-12T07:28:53Z"
    deletionGracePeriodSeconds: 0
    deletionTimestamp: "2024-11-21T05:33:24Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generation: 4
    labels:
      cluster.x-k8s.io/cluster-name: local
      cluster.x-k8s.io/control-plane: "true"
      objectset.rio.cattle.io/hash: 66b74d053c11b4117fb09e769b0dee4455188f9b
      rke.cattle.io/cluster-name: local
      rke.cattle.io/control-plane-role: "true"
      rke.cattle.io/etcd-role: "true"
      rke.cattle.io/machine-id: dd9eaec0385559615d3030627ef55a32a1d5e93d535766ff47d1e0b4eecd5e4
      rke.cattle.io/worker-role: "true"

    name: custom-9038fa228c32
    namespace: fleet-local
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: local
      uid: 1be88e70-671b-49a5-abd6-667736174e97
    resourceVersion: "101630198"
    uid: 21953903-0efb-4f93-8efd-d219ce06ceee
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-9038fa228c32
        namespace: fleet-local
      dataSecretName: custom-9038fa228c32-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-9038fa228c32
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://hpci01
  status:
    addresses:
    - address: 10.218.0.1
      type: InternalIP
    - address: hpci01
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2024-09-12T07:28:53Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2024-09-12T07:28:53Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2024-11-21T05:33:33Z"
      status: "True"
      type: DrainingSucceeded
    - lastTransitionTime: "2024-09-12T07:28:53Z"
      status: "True"
      type: InfrastructureReady
    - lastTransitionTime: "2024-11-20T13:16:24Z"
      status: "True"
      type: NodeHealthy
    - lastTransitionTime: "2024-09-12T07:28:53Z"
      status: "True"
      type: PlanApplied
    - lastTransitionTime: "2024-11-21T05:33:24Z"
      status: "True"
      type: PreDrainDeleteHookSucceeded
    - lastTransitionTime: "2024-11-21T05:33:33Z"
      reason: WaitingExternalHook
      severity: Info
      status: "False"
      type: PreTerminateDeleteHookSucceeded
    - lastTransitionTime: "2024-11-12T03:38:29Z"
      status: "True"
      type: Reconciled
    - lastTransitionTime: "2024-11-21T05:33:33Z"
      status: "True"
      type: VolumeDetachSucceeded
    infrastructureReady: true
    lastUpdated: "2024-11-21T05:33:33Z"
    nodeInfo:
      architecture: amd64
      bootID: 788b7635-5759-4b66-b23c-01732041f76b
      containerRuntimeVersion: containerd://1.7.17-k3s1
      kernelVersion: 5.14.21-150400.24.128-default
      kubeProxyVersion: v1.28.12+rke2r1
      kubeletVersion: v1.28.12+rke2r1
      machineID: f93c751c5aa9e98da8a607da66d82d3c
      operatingSystem: linux
      osImage: Harvester v1.3.2
      systemUUID: 4c4c4544-0057-3510-8047-b6c04f423034
    nodeRef:
      apiVersion: v1
      kind: Node
      name: hpci01
      uid: ce697494-0005-4877-ae41-908aa61f891e
    observedGeneration: 4
    phase: Deleting    
```

```
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:
    annotations:
      objectset.rio.cattle.io/id: unmanaged-machine
      objectset.rio.cattle.io/owner-gvk: /v1, Kind=Secret
      objectset.rio.cattle.io/owner-name: custom-00c3c56937c3
      objectset.rio.cattle.io/owner-namespace: local
    creationTimestamp: "2024-11-27T08:21:39Z"
    finalizers:
    - machine.cluster.x-k8s.io
    generation: 3
    labels:
      cluster.x-k8s.io/cluster-name: local
      harvesterhci.io/managed: "true"
      objectset.rio.cattle.io/hash: fa90fc89d51da6eb9da95d7a4549f0a3b7eb9a80
      rke.cattle.io/cluster-name: local
      rke.cattle.io/machine-id: 03c05f8a7a9ea50729a5a93204ab7fe870591e8bf454475e6a4a8af46d6f53d
      rke.cattle.io/worker-role: "true"

    name: custom-00c3c56937c3
    namespace: fleet-local
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: local
      uid: 1be88e70-671b-49a5-abd6-667736174e97
    resourceVersion: "113117949"
    uid: 23c1c998-7314-4ba6-89ad-b7bf75d4c5a4
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-00c3c56937c3
        namespace: fleet-local
      dataSecretName: custom-00c3c56937c3-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-00c3c56937c3
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://hpci01
  status:
    addresses:
    - address: 10.218.0.1
      type: InternalIP
    - address: hpci01
      type: Hostname
    bootstrapReady: true
    conditions:
    - lastTransitionTime: "2024-11-27T08:21:40Z"
      status: "True"
      type: Ready
    - lastTransitionTime: "2024-11-27T08:21:40Z"
      status: "True"
      type: BootstrapReady
    - lastTransitionTime: "2024-11-27T08:21:40Z"
      status: "True"
      type: InfrastructureReady
    - lastTransitionTime: "2024-11-27T08:21:59Z"
      status: "True"
      type: NodeHealthy
    - lastTransitionTime: "2024-11-27T08:21:39Z"
      status: "True"
      type: PlanApplied
    - lastTransitionTime: "2024-11-27T08:21:59Z"
      status: "True"
      type: Reconciled
    infrastructureReady: true
    lastUpdated: "2024-11-27T08:21:59Z"
    nodeInfo:
      architecture: amd64
      bootID: 3305477b-9ae0-4203-aa4f-b4f01220444a
      containerRuntimeVersion: containerd://1.7.17-k3s1
      kernelVersion: 5.14.21-150400.24.128-default
      kubeProxyVersion: v1.28.12+rke2r1
      kubeletVersion: v1.28.12+rke2r1
      machineID: f93c751c5aa9e98da8a607da66d82d3c
      operatingSystem: linux
      osImage: Harvester v1.3.2
      systemUUID: 4c4c4544-0057-3510-8047-b6c04f423034
    nodeRef:
      apiVersion: v1
      kind: Node
      name: hpci01
      uid: 14fb39ff-1507-4030-9a8c-fe96defcfa0b
    observedGeneration: 3
    phase: Running  
```

**To Reproduce**
1. Delete the node `hpci01` 
2. Adde it back
3. Later this new node stucks on cordon state.

**Expected behavior**

Remove & add node should work smoothly.

The old `machine` object should be removed or refuse to create the new `machine` object.

**Support bundle**

**Environment**
 - Harvester ISO version: v1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

#7066

**Comment by FrankYang0529** [comment]
Hi @w13915984028, I tried the steps multiple time today, but still can't reproduce the issue. Can you reproduce this in your cluster? Thanks.

**Comment by w13915984028** [comment]
@FrankYang0529 I did not reproduce yet and guess it is not easy to reproduce, instead, the yamls/logs had following clues:

```
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:
..
    deletionTimestamp: "2024-11-21T05:33:24Z"
    finalizers:
    - machine.cluster.x-k8s.io
..

    name: custom-9038fa228c32
    namespace: fleet-local

    - lastTransitionTime: "2024-11-21T05:33:24Z"
      status: "True"
      type: PreDrainDeleteHookSucceeded

    - lastTransitionTime: "2024-11-21T05:33:33Z"
      reason: WaitingExternalHook
      severity: Info
      status: "False"  // -------------------------------> need to check source code, if this condition will block it
      type: PreTerminateDeleteHookSucceeded
```

Rancher pod:  `2024-11-21T07:43:39` starts to log 
```
2024-11-21T07:43:39.255264884Z 2024/11/21 07:43:39 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-2733b5337201 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32
...

2024-11-28T08:08:07.241745560Z 2024/11/28 08:08:07 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-9b6c463e8c03 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32
...
```

https://github.com/rancher/cluster-api/blob/bc756c4e7ed08313413c1300859bd4dceeccb25a/controllers/machine_controller.go#L352

https://github.com/rancher/cluster-api-provider-rke2/blob/fced99c83c95bf93aa88a6af3c628afb33d9a2bc/controlplane/internal/controllers/rke2controlplane_controller.go#L1007

bootstrap error message:

https://github.com/rancher/rancher/blob/1fc33272102599d7e6410f145a7bc190a0f2d292/pkg/controllers/capr/bootstrap/controller.go#L517

**Comment by w13915984028** [comment]
@FrankYang0529 From the bootstrap code, it looks the being-deleted machine is a node for a couple of other machines to join, it can't be removed simply.

```
	// If the RKEControlPlane is not deleting, then make sure this node is not being used as an init node.
	if cp.DeletionTimestamp.IsZero() {
		planSecret, err := h.secretCache.Get(bootstrap.Namespace, capr.PlanSecretFromBootstrapName(bootstrap.Name))
		if err != nil && !apierrors.IsNotFound(err) {
			return bootstrap, fmt.Errorf("error retrieving plan secret to validate it was not an init node: %v", err)
		}

		if planSecret != nil {
			// validate that no other nodes are joined to this node, otherwise removing it will cause a bunch of nodes to start crashing.
			joinURL := planSecret.Annotations[capr.JoinURLAnnotation]
			planSecrets, err := h.secretCache.List(bootstrap.Namespace, labels.SelectorFromSet(map[string]string{
				capi.ClusterNameLabel: bootstrap.Spec.ClusterName,
			}))
			if err != nil {
				return bootstrap, fmt.Errorf("error encountered list plansecrets to ensure node was not joined: %v", err)
			}
			for _, ps := range planSecrets {
				if ps.GetAnnotations()[capr.JoinedToAnnotation] == joinURL {
					logrus.Errorf("[rkebootstrap] %s/%s: cluster %s/%s machine %s/%s was still joined to deleting etcd machine %s/%s", bootstrap.Namespace, bootstrap.Name, capiCluster.Namespace, capiCluster.Name, bootstrap.Namespace, ps.GetLabels()[capr.MachineNameLabel], machine.Namespace, machine.Name)
					h.rkeBootstrap.EnqueueAfter(bootstrap.Namespace, bootstrap.Name, 5*time.Second)
					return bootstrap, generic.ErrSkip
				}
			}
		}
	}
```

**Comment by w13915984028** [comment]
A couple of machines joned to `fleet-local/custom-9038fa228c32`

```
2024-11-28T08:03:17.203960038Z 2024/11/28 08:03:17 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-9a91bb10338c was still joined to deleting etcd machine fleet-local/custom-9038fa228c32

2024-11-28T08:03:22.204744916Z 2024/11/28 08:03:22 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-2ba1e7b328e0 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32

2024-11-28T08:03:27.205355341Z 2024/11/28 08:03:27 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-2733b5337201 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32
2
2024-11-28T08:03:32.206357256Z 2024/11/28 08:03:32 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-b22d8f5a2797 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32

2024-11-28T08:03:37.207122706Z 2024/11/28 08:03:37 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-dcafab1e9bd2 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32

2024-11-28T08:03:42.207405199Z 2024/11/28 08:03:42 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-1c6896337eb7 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32

2024-11-28T08:03:47.207546790Z 2024/11/28 08:03:47 [ERROR] [rkebootstrap] fleet-local/custom-9038fa228c32: cluster fleet-local/local machine fleet-local/custom-2ba1e7b328e0 was still joined to deleting etcd machine fleet-local/custom-9038fa228c32
```

**Comment by w13915984028** [comment]
Short summary:

The machine object `custom-9038fa228c32` has annotation `pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: rke-bootstrap-controller`, and which trggers capi to mark the condition `PreTerminateDeleteHookSucceeded` as `False`, and waiting for `rke-bootstrap-controller` to remove this annotation.

But unluckily, the `rke-bootstrap-controller` complians that the machine `custom-9038fa228c32` has a couple of other nodes joining to it, and blocks it.

Thus the old machine `custom-9038fa228c32` stucks on `phase: Deleting`.

capi machine-controller:
https://github.com/rancher/cluster-api/blob/bc756c4e7ed08313413c1300859bd4dceeccb25a/controllers/machine_controller.go#L352

bootstrap-controller:
https://github.com/rancher/rancher/blob/1fc33272102599d7e6410f145a7bc190a0f2d292/pkg/controllers/capr/bootstrap/controller.go#L516


```
- apiVersion: cluster.x-k8s.io/v1beta1
  kind: Machine
  metadata:
    annotations:
      pre-terminate.delete.hook.machine.cluster.x-k8s.io/rke-bootstrap-cleanup: rke-bootstrap-controller
...
    name: custom-9038fa228c32
    namespace: fleet-local
    ownerReferences:
    - apiVersion: cluster.x-k8s.io/v1beta1
      kind: Cluster
      name: local
      uid: 1be88e70-671b-49a5-abd6-667736174e97
    resourceVersion: "101630198"
    uid: 21953903-0efb-4f93-8efd-d219ce06ceee
  spec:
    bootstrap:
      configRef:
        apiVersion: rke.cattle.io/v1
        kind: RKEBootstrap
        name: custom-9038fa228c32
        namespace: fleet-local
      dataSecretName: custom-9038fa228c32-machine-bootstrap
    clusterName: local
    infrastructureRef:
      apiVersion: rke.cattle.io/v1
      kind: CustomMachine
      name: custom-9038fa228c32
      namespace: fleet-local
    nodeDeletionTimeout: 10s
    providerID: rke2://hpci01
...

**Comment by FrankYang0529** [comment]
Hi @w13915984028, I think `rke.cattle.io/joined-to` is not the root cause. Within a 4-node cluster, each node has `rke.cattle.io/joined-to` annotation like following:

* harvester-node-0: ""
* harvester-node-1: "harvester-node-0"
* harvester-node-2: "harvester-node-0"
* harvester-node-3: "harvester-node-1"

In this case, I remove harvester-node-1. The `rke.cattle.io/joined-to` in harvester-node-3 will change to another node, so I think it will not be stuck in log like https://github.com/harvester/harvester/issues/7065#issuecomment-2507396032.

**Comment by FrankYang0529** [comment]
The only case that the cluster may be stuck in removing node is that removing harvester-node-0. I think the reason is that it has `rke.cattle.io/init-node: "true"`. A workable way to remove this node is:

* Turn on maintenance mode for the node.
* Shutdown the node.
* Removing the node.

I think we can add one more step `Shutdown the node` to the document, so we can safely remove a node with `rke.cattle.io/init-node: "true"`.

**Comment by albinsun** [comment]
Test PASS, delete and recreate node succeeds following documentation fix https://docs.harvesterhci.io/v1.3/host/#deleting-a-node.



## Environment
* `harvester-v1.3.2`
  * Profile: AMD64 QEMU/KVM
  * ui-source: `Auto`


## Test Cases

> Delettion steps follows https://docs.harvesterhci.io/v1.3/host/#deleting-a-node.

### 🟢 3 Nodes Cluster
1. <details>
   <summary> Create a 3 nodes cluster
   </summary>
   
   ![Image](https://github.com/user-attachments/assets/04f4323c-e9f8-4c61-8f29-c59af5432381)
   </details>

1. <details>
   <summary> Create and let each nodes has 1 VM
   </summary>

   ![Image](https://github.com/user-attachments/assets/547f2875-2113-483c-ae19-7c6bb5b4bd66)
   </details>

1. <details>
   <summary> All volumes are Healthy
   </summary>

   ![Image](https://github.com/user-attachments/assets/ce688c68-a58d-4c70-aad9-14b14328256d)
   </details>

1. Delete and recreate node-1
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     ![Image](https://github.com/user-attachments/assets/35fda7fd-ca8f-4c91-807e-3ef52a1483a9)
     </details>

   * <details>
     <summary> Evict workloads by Maintenance Mode
     </summary>

     * Noes
       ![Image](https://github.com/user-attachments/assets/0bff3b08-323e-4459-bc51-cb02e5d8c201)
     * VMs
       ![Image](https://github.com/user-attachments/assets/6cc22acb-14d9-4b62-8143-04df0ebfb9c8)
     </details>

   * <details>
     <summary> Delete RKE2 services and shut down the node.
     </summary>

     ![Image](https://github.com/user-attachments/assets/d808d27e-8731-4f03-9ee9-4bb1bac64974)
     </details>

   * <details>
     <summary> Remove <b>node-1</b>
     </summary>

     Trigger Delete
     ![Image](https://github.com/user-attachments/assets/31a9f32b-7471-4e56-831b-43c5e827f0fc)
     Deleted (takes ~5 mins)
     ![Image](https://github.com/user-attachments/assets/dc207d16-8c37-4bae-acca-0adddecacf31)
     </details>

   * <details>
     <summary> Newly setup <b>node-1</b> and join, check <code>Active</code> over 10 mins.
     </summary>

     * Hosts
       ![Image](https://github.com/user-attachments/assets/89ebe826-b01d-4a03-88b4-45fd7741aae3)
     * VMs
       ![Image](https://github.com/user-attachments/assets/901c0c43-eb7d-4574-939f-4721907d5ccf)
     </details>

   * <details>
     <summary> Longhorn volume are <code>Healthy</code>
     </summary>

     * Nodes
       ![Image](https://github.com/user-attachments/assets/35642dd8-37b1-47de-bf59-fa7e30ca8e0b)
     * Volumes
       ![Image](https://github.com/user-attachments/assets/f538a313-f13d-4ade-95e2-6be34e440758)
     </details>


1. Delete and recreate node-2
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     * Nodes
       ![Image](https://github.com/user-attachments/assets/aa38c59a-0774-43b9-b8fe-0e65b2ccab68)
     * Volumes
       ![Image](https://github.com/user-attachments/assets/2c41bced-57fe-4eb2-b4e7-285a84d80be6)
     </details>

   * <details>
     <summary> Evict workloads by Maintenance Mode
     </summary>

     * Noes
       ![Image](https://github.com/user-attachments/assets/dfb30144-fe0f-40f3-9229-9cf1f50bc6b3)
     * VMs
       ![Image](https://github.com/user-attachments/assets/774a6bba-0293-441f-b968-dd87053a2d3d)
     </details>

   * <details>
     <summary> Delete RKE2 services and shut down the node.
     </summary>

     ![Image](https://github.com/user-attachments/assets/7fca0c68-08e3-49e5-a157-4f7020626e4a)
     </details>

   * <details>
     <summary> Remove <b>node-2</b>
     </summary>

     Trigger Delete
     ![Image](https://github.com/user-attachments/assets/df47eb48-3d62-45d7-a903-b194a29f3f95)
     Deleted (takes ~5 mins)
     ![Image](https://github.com/user-attachments/assets/8ea11ea9-3adb-4422-ba49-d504d0798f4e)
     </details>

   * <details>
     <summary> Newly setup <b>node-2</b> and join, check <code>Active</code> over 10 mins.
     </summary>

     * Hosts
       ![Image](https://github.com/user-attachments/assets/627432ef-a4ec-4aef-b74a-1f279e4d62bc)
     * VMs
       ![Image](https://github.com/user-attachments/assets/74d047df-7ed0-4a52-a9b5-5f728d4fd379)
     </details>

   * <details>
     <summary> Longhorn volume are <code>Healthy</code>
     </summary>

     * Nodes
       ![Image](https://github.com/user-attachments/assets/5885bb20-2f99-40f2-adb0-0ffc7c2c6240)
     * Volumes
       ![Image](https://github.com/user-attachments/assets/b28d5fca-edde-4c97-963f-09d9709dc7d4)
     </details>





### 🟢 2 Nodes Cluster

> [!WARNING]
> Edge case, not recommended cuz only 2 control planes.
> See https://docs.harvesterhci.io/v1.3/host/#1-check-if-the-node-can-be-removed-from-the-cluster

1. <details>
   <summary> Create a 2 nodes cluster
   </summary>

   ![Image](https://github.com/user-attachments/assets/51d6d655-76d2-42a8-9381-475930c736e8)
   </details>

1. <details>
   <summary> Create and let each nodes has 1 VM
   </summary>

   ![Image](https://github.com/user-attachments/assets/3bef2300-3c70-4bfc-8538-43c727e9da86)
   </details>

1. <details>
   <summary> All volumes are Healthy
   </summary>

   ![Image](https://github.com/user-attachments/assets/92be09cb-0e66-42ed-a153-2107fcb8ce3b)
   </details>

   > Degraded, expected as 2 nodes edge case. 

1. Delete and recreate node-1
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     ![Image](https://github.com/user-attachments/assets/4c72fec6-24ef-4fae-baee-840146ea00b0)
     </details>

   * <details>
     <summary> Evict workloads by Maintenance Mode
     </summary>

     * Noes
       ![Image](https://github.com/user-attachments/assets/913a847d-e2af-42ac-8ac2-4d32c3bbbb4e)
     * VMs
       ![Image](https://github.com/user-attachments/assets/84db2e03-b2d5-4653-86b3-d0712f0b43bb)
     </details>

   * <details>
     <summary> Delete RKE2 services and shut down the node.
     </summary>

     ![Image](https://github.com/user-attachments/assets/17275b43-22f9-4014-b496-ed09d91c6fc9)
     </details>

   * <details>
     <summary> Remove <b>node-1</b>
     </summary>

     Deleted (takes ~5 mins)
     ![Image](https://github.com/user-attachments/assets/ebe1e730-974e-4483-8ab3-4f9ce59ccc6d)
     </details>

   * <details>
     <summary> Newly setup <b>node-1</b> and join, check <code>Active</code> over 10 mins.
     </summary>

     * Hosts
       ![Image](https://github.com/user-attachments/assets/a54bdc4f-15ab-4ada-ae06-ca9aaba10f8e)
     * VMs
       ![Image](https://github.com/user-attachments/assets/51a6422b-cc03-4690-99e0-c6a704f4f214)
     </details>


1. Delete and recreate node-0
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     ![Image](https://github.com/user-attachments/assets/3eae4849-bba2-4445-9745-237f9ecc991b)
     </details>

   * <details>
     <summary> Should NOT be able to evict workloads by Maintenance Mode
     </summary>

     ![Image](https://github.com/user-attachments/assets/32c68433-8baa-4d8e-adcb-e83aadedeb90)
     </details>

     > Single controlplane cluster, cannot place controlplane in maintenance mode


### 🟢 3 Nodes Witness Cluster
1. Based on previous 2 nodes cluser env.
2. <details>
   <summary> Join node-2 witness node
   </summary>

   ![Image](https://github.com/user-attachments/assets/f63a1769-e7f0-44be-905c-d60e5d2461c6)
   </details>

1. Delete and recreate node-2 (witness)
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     ![Image](https://github.com/user-attachments/assets/8071e071-4ab3-4fe2-9451-8994cb77c7dd)
     </details>
   
     > Witness node does not store data

   * <details>
     <summary> Evict workloads by Maintenance Mode
     </summary>

     * Noes
      ![Image](https://github.com/user-attachments/assets/e4f07ac9-6a80-448f-ba75-aa15f33160ca)
     * VMs
       ![Image](https://github.com/user-attachments/assets/5dbbb0fc-6b33-45a6-a126-978b86ece49f)      
     </details>

   * <details>
     <summary> Delete RKE2 services and shut down the node.
     </summary>

     ![Image](https://github.com/user-attachments/assets/67bd7e03-491c-4fab-b5a2-67d622f5021c)
     </details>

   * <details>
     <summary> Remove <b>node-2</b>
     </summary>

     Deleted
     ![Image](https://github.com/user-attachments/assets/514cc573-488b-434c-b6f2-e5bd18141983)
     </details>

   * <details>
     <summary> Newly setup <b>node-2</b> and join, check <code>Active</code> over 10 mins.
     </summary>

     * Hosts
       ![Image](https://github.com/user-attachments/assets/e054b235-686c-477d-888b-236023b4ce34)
     * VMs
       ![Image](https://github.com/user-attachments/assets/e0f8ff3e-3a6f-48ae-9822-1e9a314ac6df)
     </details>

1. Delete and recreate node-0
   * <details>
     <summary> Evict replicas via Longhorn
     </summary>

     ![Image](https://github.com/user-attachments/assets/6aee8d7a-78c9-4e68-abbb-9e9e062372a9)    
     </details>

   * <details>
     <summary> Evict workloads by Maintenance Mode
     </summary>

     * Noes
       ![Image](https://github.com/user-attachments/assets/eddaef83-9b69-403f-9eab-bb82b07a363a)
     * VMs
       ![Image](https://github.com/user-attachments/assets/ea91bd7d-0b78-481c-8479-3e7906400f4f)
     </details>

   * <details>
     <summary> Delete RKE2 services and shut down the node.
     </summary>

     ![Image](https://github.com/user-attachments/assets/f212e976-9772-495b-b51c-6794e3a94de2) 
     </details>

   * <details>
     <summary> Remove <b>node-0</b>
     </summary>

     Deleted (takes ~5 mins)
     ![Image](https://github.com/user-attachments/assets/9b8ba266-4a8b-4993-8ad6-e6f4f704965a)
     * VMs
       ![Image](https://github.com/user-attachments/assets/13cdab0a-3dec-42d5-9e2e-b861d6d979b2)

     </details>

   * <details>
     <summary> Newly setup <b>node-0</b> and join, check <code>Active</code> over 10 mins.
     </summary>

     * Hosts
       ![Image](https://github.com/user-attachments/assets/3fc92fe6-8e05-4d81-85a5-d7cceb0c97e1)
     * VMs
       ![Image](https://github.com/user-attachments/assets/c209a8c2-c363-42df-9bb1-b68b6730c128)
     * Try Migrate
       ![Image](https://github.com/user-attachments/assets/794bae74-a76a-4d7c-ba00-ea160ac6c7c7)
     </details>
