### ISSUE TITLE
[BUG] Search doesn't work in DOCS, if version set to 1.4

### ISSUE THREAD

**Issue by SlavikCA** [harvester/harvester#7071]
**To Reproduce**
1. https://docs.harvesterhci.io/search?q=boot
2. Select version `v1.4`

**Actual behavior**
> No results were found

All other versions are working without issue.

**Comment by albinsun** [comment]
Can be reproduce
* `v1.5 (dev)`
  ![image](https://github.com/user-attachments/assets/6d7cc1fa-16ad-4644-94c3-84318160b3e0)
* `v1.4 (latest)`
  ![image](https://github.com/user-attachments/assets/9d71a52f-2466-4a28-b6ef-ef78ad7ca18c)
* `v1.3`
  ![image](https://github.com/user-attachments/assets/26a4e5a2-64d3-4241-bdbf-dd9c9dbc3f97)

**Comment by bk201** [comment]
Fixed with https://github.com/harvester/harvester/issues/6623
