### ISSUE TITLE
[BUG] Image state is failed when initially created

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#708]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5697937/114996849-d5f6b200-9ed1-11eb-9d01-887463b28815.png)

**To Reproduce**
1. Create a VM image using `http://cloud-images-archive.ubuntu.com/releases/bionic/release-20201117/ubuntu-18.04-server-cloudimg-amd64.img`
2. Check the image state

**Expected behavior**
No Failed state unless there's anything wrong.

**Result**
The image is in failed at the beginning then turns to be active after a short period.

**Environment:**
 - Harvester ISO version: v0.2.0-rc2
 - Installation Mode: ISO

**Comment by TangStone** [comment]
Validation passes in version master-0008ce84-head
