### ISSUE TITLE
[BUG] The default route disappeared

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#709]
**Describe the bug**

After the IPv4 address of slave NIC changed, the default route whose interface is harvester-br0 disappeared.

**To Reproduce**
Change the IPv4 address of the slave NIC via DHCP.
- Bind a difference IP in DHCP static table.
- Execute `udhcpc -i <slave NIC>` to change IP

**Expected behavior**

The IPv4 address of harvester-br0 keeps the same as the slave NIC and the Harvester network-controller only adjusts the routes with the old src address.

**Log**

```
bm-small [~]$ ip r
10.52.0.0/24 via 10.52.0.0 dev flannel.1 onlink
10.52.1.0/24 via 10.52.1.0 dev flannel.1 onlink
10.52.2.0/24 dev cni0 proto kernel scope link src 10.52.2.1
127.0.0.0/8 dev lo scope host
172.16.0.0/16 dev harvester-br0 proto kernel scope link src 172.16.0.231
bm-small [~]$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1): 56 data bytes
ping: sendto: Network unreachable
```

**Environment:**
 - Harvester ISO version:  0.2-rc2
 - Installation Mode: ISO
 - Underlying Infrastructure: Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by TangStone** [comment]
### Validation in version master-64e4d950-head
1. Install harvester
2. harvester Network Information
![image](https://user-images.githubusercontent.com/15829074/115989809-bdce1380-a5f2-11eb-985f-5d6dbfc07edb.png)
```
default via 172.16.0.1 dev harvester-br0 
10.52.0.0/24 dev cni0 proto kernel scope link src 10.52.0.1 
114.114.114.114 via 172.16.0.1 dev harvester-br0 
127.0.0.0/8 dev lo scope host 
172.16.0.0/16 dev harvester-br0 proto kernel scope link src 172.16.0.204 
172.16.0.1 dev harvester-br0 scope link
```
3. Bind a difference IP in DHCP static table
![image](https://user-images.githubusercontent.com/15829074/115989886-2ae1a900-a5f3-11eb-87e8-224333312b9a.png)
4. Execute` udhcpc -i eth0 ` change IP
![image](https://user-images.githubusercontent.com/15829074/115990172-73e62d00-a5f4-11eb-887e-eac7b2bf131d.png)
```
default via 172.16.0.1 dev harvester-br0 
default via 172.16.0.1 dev harvester-br0 metric 202 
10.52.0.0/24 dev cni0 proto kernel scope link src 10.52.0.1 
127.0.0.0/8 dev lo scope host 
172.16.0.0/16 dev harvester-br0 proto kernel scope link src 172.16.4.124
```
5. Comparison of ip route table before and after executing command `udhcpc -i eth0`
![image](https://user-images.githubusercontent.com/15829074/115993309-cd565800-a604-11eb-8312-7f1f63932e9b.png)

**Comment by yaocw2020** [comment]
@TangStone We find a special scenario. If the DHCP client renews and fetches the same IP address, the default route also disappears. The solution is to ignore the case with the same IP address and not trigger the address synchronization.

**Comment by guangbochen** [comment]
Verified on v0.2.0-rc5, renew the IP via DHCP will persist the default route as desired.
```
bm-harv3 [~]$ udhcpc -i eth0
udhcpc: socket(AF_INET,3,255): Operation not permitted
bm-harv3 [~]$ sudo su
bm-harv3 [/home/rancher]$ udhcpc -i eth0
udhcpc: started, v1.31.1
udhcpc: sending discover
udhcpc: sending select for 172.16.4.3
udhcpc: lease of 172.16.4.3 obtained, lease time 86400
RTNETLINK answers: Network unreachable
bm-harv3 [/home/rancher]$ ip r
default via 172.16.0.1 dev harvester-br0
10.52.0.0/24 dev cni0 proto kernel scope link src 10.52.0.1
10.52.1.0/24 via 10.52.1.0 dev flannel.1 onlink
10.52.2.0/24 via 10.52.2.0 dev flannel.1 onlink
114.114.114.114 via 172.16.0.1 dev harvester-br0
127.0.0.0/8 dev lo scope host
172.16.0.0/16 dev harvester-br0 proto kernel scope link src 172.16.4.3
172.16.0.1 dev harvester-br0 scope link
```
