### ISSUE TITLE
[QUESTION] How to install Harvester without VIP?

### ISSUE THREAD

**Issue by thomas-ej-worm** [harvester/harvester#7093]
Hello,

I want to install a Harvester cluster on servers in a data center that does not offer VIPs and also not offer floating IPs. I have only static IPs for the nodes and additional static IPs for the nodes.  The IPs are from different subnets. I can setup a server that can loadbalance an IP to different nodes, but this is not a VIP/Floating IP.

The installer requires to give a VIP. How can I disable VIP usage?

**Comment by bpedersen2** [comment]
You need to use oneof your 'extra' static ips. If that does not work, then your server subscription is not suitable for a harvester installation.

**Comment by thomas-ej-worm** [comment]
Thanks. When I use an extra static IP it is only valid for one node. Can I tell harvester that the VIP should be sticky on a node? And how do I bypass the same subnet check? The extra static IP is not the same subnet as the management address.

**Comment by starbops** [comment]
Hi @thomas-ej-worm, thanks for trying out Harvester. But I'm afraid that this is infeasible in our current implementation. Harvester relies on kube-vip to maintain the VIP address, and it works in the ARP mode: https://kube-vip.io/docs/modes/arp/. It will literally bind the VIP address to the `mgmt-br` interface on one of the cluster nodes. Even if you bypass the same-subnet-check in the installer, I doubt it will work if the VIP address is not in the same subnet as the node IP addresses.
