### ISSUE TITLE
[QUESTION] Can Harvester VM host DNS server for the cluster

### ISSUE THREAD

**Issue by aburhinox** [harvester/harvester#7097]
I'm slowing converting my infrastructure over from ovirt to harvester because this looks like an awesome project.  I have one harvester node up and running and I was just moving my infrastructure VMs (freeipa that hosts ldap and dns for my lab) over, then I pointed harvester at the new DNS servers and things stopped working.  

What I noticed is that from my actual harvester node, I can query the new DNS servers fine, but within the kubernetes cluster cant see them.  That means it cant see the latest update to pull from (I'm still using v1.3.2) and it cant deploy the rancher vcluster addon since it's pulling down a helm chart from the internet and cant resolve DNS.

I tried following along with the kubernets troubleshooting DNS guide (https://kubernetes.io/docs/tasks/administer-cluster/dns-debugging-resolution/), I started running dig commands directly at specific DNS servers bypassing coredns.  I found when I run queries to the harvester hosted DNS, I get timeouts, but to other DNS servers its fine.  I did a packet capture on the harvester host and I see the DNS request and response go out across the mgmt-br interface (still just testing with everything running over the mgmt-br), but it never gets back into the cluster.  This is my first time with kubernetes and I dont know where to look after that in the network stack to see what's going on.

I'm wondering if there is something preventing me from using a DNS server hosted within the cluster.  I can use DNS servers on the same subnet and I see a response on the harvester host, so it's not an issue with the external network config or DNS server.  Any thoughts on where next to look or what else would help me to troubleshoot?

Thanks!

**Comment by starbops** [comment]
Hey @aburhinox, thanks for the feedback! It would be nice if you could attach a support bundle for us to troubleshoot. Here's how to generate one (please ensure to add the namespaces that you want us to inspect before generating the SB): https://docs.harvesterhci.io/v1.4/troubleshooting/harvester#generate-a-support-bundle

While lacking a support bundle, I wonder if your environment involves VLANs. You mentioned three key facts that ring the bell:

1. Getting timeouts making requests
2. There involves communications between the Harvester itself (especially the Harvester's internal services, i.e., system pods) and the virtual machines through the VM Network
3. You're using v1.3.2 and are not using any ClusterNetwork except the default one, `mgmt`.

If all your network setup is correct, you might be hitting #3960. However, I cannot be 100% sure until I get further information from you.

**Comment by aburhinox** [comment]
Thanks @starbops.  I've attached my support bundle and added my custom namespace, bastet11.  

Yes, my environment involves two VLANs.  I have one setup for hardware devices and one for virtual devices, so my DNS server is on the virtual VLAN while the harvester node is on the physical VLAN.  

Looking at #3960, I tried the `sysctl -w net.bridge.bridge-nf-call-iptables=0` command it I was able to run a manual ping that didnt work before.  That seems to have done the trick, temporarily.  I'll have to figure out how to make that more permanent since the fix looks to be tagged in future releases.

[supportbundle_a41b8745-7e6d-408f-ae7a-dae415122bac_2024-12-06T02-21-55Z.zip](https://github.com/user-attachments/files/18031960/supportbundle_a41b8745-7e6d-408f-ae7a-dae415122bac_2024-12-06T02-21-55Z.zip)

**Comment by starbops** [comment]
A formal way to do this is to add a rke2-{server,agent} drop-in file. For instance, put the following in the `/etc/systemd/system/rke2-{server,agent}.service.d/bridge.conf` file:

```
[Service]
ExecStartPost=/sbin/sysctl -w net.bridge.bridge-nf-call-iptables=0
```

It helps you persist the config after service restart, but still, it won't survive after reboots because Harvester is built upon an immutable OS. To overcome this, you can insert the following snippet into `/oem/90_custom.yaml`:

```
    - path: /etc/systemd/system/rke2-server.service.d/bridge.conf
      permissions: 448
      owner: 0 
      group: 0
      content: |
        [Service]
        ExecStartPost=/sbin/sysctl -w net.bridge.bridge-nf-call-iptables=0
      encoding: ""
      ownerstring: ""
```

Please refer to the [doc](https://docs.harvesterhci.io/v1.4/install/update-harvester-configuration) for more examples. Thank you.

**Comment by aburhinox** [comment]
That did the trick to persist the changes.  thanks again for the assist, looking forward to getting this resolved in the next release!
