### ISSUE TITLE
Provide image format info

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#71]
Be able to show the format when a VM image is imported.
The incentive is to handle root volume differently for iso image.

**Comment by guangbochen** [comment]
<del>we need to support differing the image by its file extension and OS using a specified label, i.e:
<del>1. Windows vs Linux
<del>2. `.iso` image vs non-ISO image

**Comment by guangbochen** [comment]
<del>adding default label when uploading the image
![image](https://user-images.githubusercontent.com/4569037/90866680-d4b6c900-e3c6-11ea-9d81-a2780222bc0c.png)


<del>supported labels:
```
harvester.cattle.io/format:   iso/raw/qcow2
harvester.cattle.io/os: linux/windows
```

**Comment by guangbochen** [comment]
as discussed offline, using labels to manage the disk logic from UI does not make sense instead we will add [default template](https://github.com/rancher/harvester/issues/72) to facilitate root volume configuration of different OS and iso images.

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester/issues/72
