### ISSUE TITLE
[BUG] After vm restore, sshkey name become Unknown

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#710]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/115174094-2f8df500-a0fb-11eb-9faa-a51faafe7f54.png)
![image](https://user-images.githubusercontent.com/15064560/115173974-f0f83a80-a0fa-11eb-81a8-063f341a1e33.png)

**To Reproduce**
1.  restore a backup
2. check the restored vm's sshkey

**Expected behavior**

the restored vm's sshkey show correct name

**Log**

**Environment:**
 - Harvester ISO version:  0.2.0-rc3
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
@futuretea   When the added SSH is deleted in the SSH list page, the front-end will display Unknow if the corresponding relationship cannot be found

**Comment by futuretea** [comment]
validated on master-0423.iso
![image](https://user-images.githubusercontent.com/15064560/115951962-272c2480-a516-11eb-9e1a-1f9459ccbd72.png)
