### ISSUE TITLE
[BUG]  Create a PVC without name

### ISSUE THREAD

**Issue by Yu-Jack** [harvester/harvester#7100]
**Describe the bug**

In Harvester dashboard, we can create a PVC without a name. Although it still generates the resource, but it seems weird that we put the `Required` in that field. It also happens on API. Our validator doesn't block this request. I'm not sure the name is required or not. 

On the other hand, our harvester/tests [expects it should return error](https://github.com/harvester/tests/blob/0edf8437294ef28f44c9ba83becf03dd93631bc2/harvester_e2e_tests/apis/test_volumes.py#L64-L73) instead of successful code.

https://github.com/user-attachments/assets/01da4342-b22d-4704-bf9a-4ad656f6a441

**To Reproduce**
1. Install Harvester.
2. Create a PVC on GUI page.

**Expected behavior**
It should prevent users from creating a PVC without name.

**Environment**
 - Harvester ISO version: v1.4.0

**Additional context**

**Comment by lanfon72** [comment]
Duplicate #7030
