### ISSUE TITLE
[BUG] After vm restore, display text "Operation complete" on backup detail page

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#711]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/115175039-e474e180-a0fc-11eb-851c-effd5b55b8ee.png)

**To Reproduce**
1. restore vm from a backup
2. go to backup detail page

**Expected behavior**

don't  show the "Operation complete" text

**Log**

**Environment:**
 - Harvester ISO version: 0.2.0-rc3
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
Will need to change the `Progressing` condition type to `InProgress` to avoid incorrect error state, this is a framework condition https://github.com/rancher/wrangler/blob/master/pkg/summary/summary.go#L121  @WuJun2016

**Comment by futuretea** [comment]
validated on master-0423.iso
![image](https://user-images.githubusercontent.com/15064560/115952021-72463780-a516-11eb-8004-3faa1238fb4b.png)
![image](https://user-images.githubusercontent.com/15064560/115951997-53e03c00-a516-11eb-80bf-93fb55ee4c46.png)
