### ISSUE TITLE
[CI] Enable UI testing for Harvester UI extension

### ISSUE THREAD

**Issue by innobead** [harvester/harvester#7122]
BTW, there is another topic directly related to this, we need UI testing during a PR created/updated, a tag/release made, or ad-hoc triggering. QA can help with setting up the infra and we need a corresponding GitHub action for this. 

@a110605 @torchiaf please make this a priority and work with @bk201. Thanks. cc @albinsun @TachunLin

**Comment by bk201** [comment]
It's tracked in https://github.com/harvester/tests/issues/1697, Albin and David will work on this.
