### ISSUE TITLE
[FEATURE] Add nodenetwork yaml in the HOST edit page

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#717]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Add nodenetwork yaml in the HOST edit page

**Describe alternatives you've considered**

No

**Additional context**

No

**Comment by WuJun2016** [comment]
Is this a needed feature ?   We can close if we don't need it.    cc @guangbochen   @yaocw2020

**Comment by yaocw2020** [comment]
I think we can close it.
