### ISSUE TITLE
[FEATURE] UI design enhancement

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#719]
- [ ] 1. On the VM create page, the prompt looks like an option and selectable in the dropdown, it may make users get confused
![image](https://user-images.githubusercontent.com/57614736/115216523-2884d800-a137-11eb-937c-b4105e807876.png)

- [x] 2. 
![image](https://user-images.githubusercontent.com/24985926/115535724-9d891680-a2cb-11eb-838b-a5393424dd62.png)

- [ ] 3.  Message type:
  * Message notification
  * Error Prompt
![image](https://user-images.githubusercontent.com/24985926/116360153-3373f280-a832-11eb-938a-d7794f52d45d.png)

- [x] 4. settings options to add description information
![image](https://user-images.githubusercontent.com/24985926/116505331-2c5dea80-a8ed-11eb-8438-3b3c9e8e1eff.png)

- [ ] 5.  Add promotion information after the bundle file has been successfully downloaded

- [ ] 6. It's required to do full matching filtering for the cloud-init ssh configuration obtained from the template when the ssh key is selected repeatedly.
![image](https://user-images.githubusercontent.com/7421463/124104602-055e9900-da95-11eb-9f1a-f1c086608231.png)
![image](https://user-images.githubusercontent.com/7421463/124104684-19a29600-da95-11eb-8ae1-0dc9adaaabb5.png)

**Comment by kingsd041** [comment]
It is recommended to support the modification of the labels and description of the images

**Comment by guangbochen** [comment]
close in favor of the 0.3 new UI changes, feel free to open new UI issues in regards to the new UX, thanks.
