### ISSUE TITLE
[QUESTION]why kernel parameters bridge-nf-call-iptables not set 0 by default

### ISSUE THREAD

**Issue by fangfenghuang** [harvester/harvester#7192]
I've encountered a problem that the vm can't send transfer oversized packets(icmp/udp packet greater than 1500 bytes) when only the default mgmt cluster network is available.

But when I added a new cluster network, I found that vm can transfer oversized packets suddenly, because the kernel parameter 'bridge nf call iptables' was set from 1 to 0 after adding new cluster network. 

My question is, why not set bridge-nf-call-iptables to 0 by default?

**Comment by WebberHuang1118** [comment]
Hi @fangfenghuang 

Harvester will persist `bridge-nf-call-iptables = 0` with [this PR](https://github.com/harvester/harvester-installer/pull/884)
cc @mingshuoqiu @starbops

**Comment by fangfenghuang** [comment]
> Hi @fangfenghuang
> 
> Harvester will persist `bridge-nf-call-iptables = 0` with [this PR](https://github.com/harvester/harvester-installer/pull/884) cc @mingshuoqiu @starbops

Got it, Thank you for your answer!
