### ISSUE TITLE
[FEATURE] Documenting that the network stack must be ready when attempting an automatic installation

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#720]
**Is your feature request related to a problem? Please describe.**
The [automated installation](https://github.com/rancher/harvester/blob/master/docs/automatic-installation.md) starts without the network stack fully ready and this ended with a `network unreachable` message in the console.log.
That means the harvester-console can't download the config-create.yaml hosted on my web server and the installation just fails.

![image](https://user-images.githubusercontent.com/6025636/115225250-28bcad80-a10e-11eb-8f9a-94cb4ef0dda3.png)

The webserver is working perfectly because I was able to download the kernel and initrd from there.

**Workaround**
I was able to get over this by adding `boot_cmd="echo include_ping_test=yes >> /etc/conf.d/net-online"` on the kernel cmdline.

**Describe the solution you'd like**
I can see two solutions here:
1) Document that the workaround just above could be used on the automated installation process.
2) By default, the setting `include_ping_test=yes` is disabled on k3os, maybe it can be activated when the scenario is a harvester automatic deployment.

**Comment by guangbochen** [comment]
documented in https://github.com/harvester/harvester/pull/780
