### ISSUE TITLE
[BUG] use user generated namespace of the ssh-key and templates

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#724]
**Describe the bug**
currently, the user-generated ssh-keys and template are using the `harvester-system` namespace which can't be accessed by the non-admin users when the RBAC is introduced.

**To Reproduce**
1. Go to the ssh key page 
2. create a new user ssh key
3. click view config to check its assigned namespace, it will display as `harvester-system`

**Expected behavior**
1. use user namespace for both user-generate ssh-keys and templates.

**Log**
```
piVersion: harvesterhci.io/v1beta1
kind: KeyPair
metadata:
  creationTimestamp: "2021-04-20T09:28:05Z"
  generation: 2
  name: aa
  namespace: harvester-system
  resourceVersion: "46855"
  uid: 5cf7e288-0066-4632-9127-17085c500159
spec:
  publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCmAZFWNfXPfzV2o203bW1107LpQeynoQ4JhByXRDM3rd1gHW60Xdcbpr7Yi9JHiqSR7YIW+mMpmjacr9bwQ1EjkfsozxHrx69IFfvYRpasBaXdBdHD/Ye3DZ28rQvEEZbyWsa9bIWcWb/m/PPmb2I4p2gX7dGxFxR/DCwUyNk95pra+w5z2H7IyXMHwTI+60dV+GguHaWfCwA/LUnDsq253hJsmAvn4Sr3G2hXqO0x+bD7hWwJHYHi6z1ZU62W3ex7w6D/0+YNh1AhTCkBI9gSKOqnWbkAekbvItSKVVqN9IfkXvvZBsgKPKjledhAHnAvXjt/+Pfkq3RhSEZp7+iL guangbochen@guangbos-MacBook-Pro.local
status:
  conditions:
  - lastUpdateTime: "2021-04-20T09:28:05Z"
    status: "True"
    type: validated
  fingerPrint: 5f:cb:b4:e1:ed:99:4c:cc:9e:4a:e1:f8:1f:5b:7e:f3

```

**Environment:**
 - Harvester ISO version: v0.2.0-rc3
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
validated on master-head
