### ISSUE TITLE
[BUG] Upgrade from 1.3.2 to 1.4 hanging on single-node cluster

### ISSUE THREAD

**Issue by Techwizz-somboo** [harvester/harvester#7246]
**Describe the bug**
My 1-node Harvester cluster has been stuck upgrading for about 36 hours now. It's stuck on Upgrading System Service, which is at 50% according to the web ui.

**To Reproduce**

Attempt to upgrade from 1.3.2 to 1.4, potentially only on a 1-node cluster?

**Expected behavior**

A successful upgrade from Harvester 1.3.2 to 1.4.

**Support bundle**
[supportbundle_25f40afb-1aad-4b1f-ac6b-8f40182d969f_2024-12-24T07-02-25Z.zip](https://github.com/user-attachments/files/18236940/supportbundle_25f40afb-1aad-4b1f-ac6b-8f40182d969f_2024-12-24T07-02-25Z.zip)

**Environment**
 - Harvester ISO version: 1.3.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal on a 1-node cluster (CPU: AMD Ryzen 5 7640U, 192 GB DDR5 RAM, 4 TB NVME single-drive).

**Additional context**

Log from the updater:

[hvst-upgrade-c4bz6-upgradelog-archive-2024-12-23T03-54-27Z.zip](https://github.com/user-attachments/files/18236941/hvst-upgrade-c4bz6-upgradelog-archive-2024-12-23T03-54-27Z.zip)

Thanks for taking a look, much appreciated!

**Comment by bk201** [comment]
The jobs is waiting for fleet:
```
2024-12-22T18:08:27.963234523Z Happy Containering!
2024-12-22T18:08:28.155758418Z Wait for Rancher to be upgraded to v2.9.2...
2024-12-22T18:08:33.313904250Z Wait for Rancher to be upgraded to v2.9.2...
2024-12-22T18:08:38.499261475Z Wait for Rancher to be upgraded to v2.9.2...
2024-12-22T18:08:43.678100373Z Wait for Rancher dependencies helm releases...
2024-12-22T18:08:43.678122645Z wait helm release cattle-fleet-system fleet fleet-104.0.2+up0.10.2 0.10.2 deployed
```

**Comment by FrankYang0529** [comment]
Hi @Techwizz-somboo, may you run this command to get helm history? Thanks.

```
helm history -n cattle-fleet-system fleet
```

**Comment by FrankYang0529** [comment]
BTW, the namespace `fleet-default` cannot be found in the system. May you manually create it? Thanks.

```
kubectl create ns fleet-default
```

**Comment by Techwizz-somboo** [comment]
Hi, thanks for taking the time to respond. It seems helm isn't installed on my node or just isn't in the path? Is that only for manual deployments of Harvester on a RKE2 cluster? I installed Harvester using an ISO release of 1.3.2.

I created the fleet-default namespace. 

```
harvester:~ # kubectl create ns fleet-default
namespace/fleet-default created
```

Thank you.

**Comment by FrankYang0529** [comment]
May you use another computer to run helm command which can link to the harvester cluster? I found that helm command is included in v1.4.0, but not in v1.3.2.

**Comment by Techwizz-somboo** [comment]
> May you use another computer to run helm command which can link to the harvester cluster? I found that helm command is included in v1.4.0, but not in v1.3.2.

Hello! Sure, I can give that a try soon. It's alright to add a 1.4.0 node into a cluster running on 1.3.2? Is there not a better way to debug this? Also with it being in an updating status, will it give me problems adding another node? Thank you.

**Comment by FrankYang0529** [comment]
> It's alright to add a 1.4.0 node into a cluster running on 1.3.2?

No, we don't support a cluster with different versions.

> with it being in an updating status, will it give me problems adding another node?

No, you can't add node during upgrade.

Could you get the helm result and generate a new support bundle and upgrade log? Thanks.

**Comment by Techwizz-somboo** [comment]
> > It's alright to add a 1.4.0 node into a cluster running on 1.3.2?
> 
> No, we don't support a cluster with different versions.
> 
> > with it being in an updating status, will it give me problems adding another node?
> 
> No, you can't add node during upgrade.
> 
> Could you get the helm result and generate a new support bundle and upgrade log? Thanks.

~~Hi, sorry how can I get the helm result? I appreciate your help!~~ 

Edit: I figured it out. Just download kubectl + helm along with the Harvester KubeConfig.

**Comment by Techwizz-somboo** [comment]
Got it, thank you again @FrankYang0529!

```
$ helm history -n cattle-fleet-system fleet
REVISION	UPDATED                 	STATUS         	CHART                	APP VERSION	DESCRIPTION      
26      	Tue Dec 10 03:09:13 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
27      	Sun Dec 15 09:26:54 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
28      	Sun Dec 15 09:27:03 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
29      	Mon Dec 16 05:57:03 2024	deployed       	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
30      	Mon Dec 16 05:57:13 2024	pending-upgrade	fleet-103.1.5+up0.9.5	0.9.5      	Preparing upgrade
```

**Comment by Techwizz-somboo** [comment]
Updated support bundle: https://github.com/Techwizz-somboo/harvester-support-bundles/raw/refs/heads/master/supportbundle_25f40afb-1aad-4b1f-ac6b-8f40182d969f_2024-12-28T02-19-20Z.zip

Updated update log: https://github.com/Techwizz-somboo/harvester-support-bundles/raw/refs/heads/master/hvst-upgrade-c4bz6-upgradelog-archive-2024-12-28T02-19-02Z.zip

Thank you.

**Comment by FrankYang0529** [comment]
Thanks for the result. Could you try to rollback to revision 29 and get the helm history result again?

```
helm rollback fleet -n cattle-fleet-system 29
```

**Comment by Techwizz-somboo** [comment]
It says the rollback was a success.

```
$ helm rollback fleet -n cattle-fleet-system 29
Rollback was a success! Happy Helming!
$ helm history -n cattle-fleet-system fleet
REVISION	UPDATED                 	STATUS         	CHART                	APP VERSION	DESCRIPTION      
26      	Tue Dec 10 03:09:13 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
27      	Sun Dec 15 09:26:54 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
28      	Sun Dec 15 09:27:03 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
29      	Mon Dec 16 05:57:03 2024	superseded     	fleet-103.1.5+up0.9.5	0.9.5      	Upgrade complete 
30      	Mon Dec 16 05:57:13 2024	pending-upgrade	fleet-103.1.5+up0.9.5	0.9.5      	Preparing upgrade
31      	Sat Dec 28 16:45:19 2024	deployed       	fleet-103.1.5+up0.9.5	0.9.5      	Rollback to 29
```

**Comment by Techwizz-somboo** [comment]
Okay, I think that did it. The web UI now shows 1.4.0, but it's working on upgrading nodes now. It shows 0% as of right now, but it probably is working. I'll give it a few hours and let you know if it succeeds! Thanks for your help!

Edit: This is the current output of the helm commanad:

```
$ helm history -n cattle-fleet-system fleet
REVISION	UPDATED                 	STATUS         	CHART                 	APP VERSION	DESCRIPTION      
28      	Sun Dec 15 09:27:03 2024	superseded     	fleet-103.1.5+up0.9.5 	0.9.5      	Upgrade complete 
29      	Mon Dec 16 05:57:03 2024	superseded     	fleet-103.1.5+up0.9.5 	0.9.5      	Upgrade complete 
30      	Mon Dec 16 05:57:13 2024	pending-upgrade	fleet-103.1.5+up0.9.5 	0.9.5      	Preparing upgrade
31      	Sat Dec 28 16:45:19 2024	superseded     	fleet-103.1.5+up0.9.5 	0.9.5      	Rollback to 29   
32      	Sat Dec 28 17:09:16 2024	deployed       	fleet-104.0.2+up0.10.2	0.10.2     	Upgrade complete
```

**Comment by Techwizz-somboo** [comment]
It just rebooted my node, the upgrade status now shows success! I believe that is it, thanks so much @FrankYang0529!!

Would you like me to leave this issue open?

**Comment by FrankYang0529** [comment]
Hi @Techwizz-somboo, good to know your cluster is upgraded successfully. Yes, please leave this issue open. I think we need to add it as a known issue to document. We will close it after updating document. Thanks.

**Comment by FrankYang0529** [comment]
Close since document PR is merged.

https://github.com/harvester/docs/pull/697

**Comment by innobead** [comment]
`require/doc` was missed.
