### ISSUE TITLE
[BUG] Upgrade stucking after Download Upgrade Image due to "no route to host"

### ISSUE THREAD

**Issue by albinsun** [harvester/harvester#7256]
**Describe the bug**
`v1.4.1-dev-20241222` same version upgrade stucking after **Download Upgrade Image** due to `dial tcp 10.52.0.89:80: connect: no route to host`

**To Reproduce**
1. <details>
   <summary> Fresh install <code>v1.4.1-dev-20241222</code>
   </summary>
   
   ![image](https://github.com/user-attachments/assets/71daac5d-da45-4e4a-84c9-e332da5d34b2)
   </details>

2. <details>
   <summary> Perform same version upgrade
   </summary>
   
   ![image](https://github.com/user-attachments/assets/94775b1b-3046-428f-8090-12436a9ffb0b)
   </details>

   > Ref. https://docs.harvesterhci.io/v1.4/upgrade/index#prepare-an-air-gapped-upgrade

3. :x: Should upgrade successfully
   * Pod _virt-launcher-upgrade-repo-hvst-upgrade-vm5d6-6jn6_
     `Readiness probe failed: Get "http://10.52.0.89:80/harvester-iso/harvester-release.yaml": dial tcp 10.52.0.89:80: connect: no route to host`
   * Screenshot
     ![image](https://github.com/user-attachments/assets/396fd7f7-42ab-4934-9212-e727a9aae715)

  

**Expected behavior**
Should upgrade successfully

**Support bundle**
* Upgrade log: [hvst-upgrade-vm5d6-upgradelog-archive-2024-12-25T14-25-31Z.zip](https://github.com/user-attachments/files/18246300/hvst-upgrade-vm5d6-upgradelog-archive-2024-12-25T14-25-31Z.zip)
* Supportbundle:  
[supportbundle_UpgradeStuckNoRouteToHost_2024-12-25T14-26-43Z.zip](https://github.com/user-attachments/files/18246324/supportbundle_UpgradeStuckNoRouteToHost_2024-12-25T14-26-43Z.zip)

**Environment**
 - Harvester ISO version: <code>v1.4.1-dev-20241222</code>
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare-metal HPE ProLiant DL360

**Additional context**
1. Can be reproduce on both baremetal and QEMU/KVM.

**Comment by bk201** [comment]
The two PRs are not included, I'm fixing this.
- https://github.com/harvester/os2/pull/142
- https://github.com/harvester/os2/pull/141

**Comment by bk201** [comment]
cc @albinsun Please test with the v1.4 ISO.

**Comment by albinsun** [comment]
Test PASS, close along with #7012, thank you.
