### ISSUE TITLE
[BUG] Need fix repo reference because repo `rancher/harvester`  has been moved to `harvester/harvester`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#727]
**Describe the bug**

- [x] harvester https://github.com/harvester/harvester/pull/728
- [x] harvester-ui https://github.com/harvester/harvester-ui/pull/437
- [x] harvester-installer https://github.com/harvester/harvester-installer/pull/79
- [x] harvester-network-controller (depend on harvester) https://github.com/harvester/harvester-network-controller/pull/29
- [x] go-harvester (depend on harvester) https://github.com/harvester/go-harvester/pull/11
- [x] docker-machine-driver-harvester  (depend on go-harvester) https://github.com/harvester/docker-machine-driver-harvester/pull/14

**Comment by guangbochen** [comment]
close as all repo reference has been changed to use the `harvester/harvester`
