### ISSUE TITLE
[Question] How to update the image of deployment/harvester 

### ISSUE THREAD

**Issue by AmazingPangWei** [harvester/harvester#733]
I'm intersted in harvester, so I add some logs in it. Then I execute "make" to build a harvester image, and it's fine. Next, I edit the deployment/harvester, replace image with above one. But after that, it shows like this:

![image](https://user-images.githubusercontent.com/32997185/115515333-9a842b00-a2b7-11eb-9f70-29f9e522aa9b.png)

And it's logs like this:
``` log
time="2021-04-21T07:38:53Z" level=error msg="Error during subscribe websocket: close sent"
time="2021-04-21T07:38:53Z" level=error msg="Error during subscribe websocket: close sent"
```

So, did I do something wrong?

**Comment by futuretea** [comment]
can u try to rebase your custom code on the latest harvester/harvester:master

**Comment by AmazingPangWei** [comment]
My custom code is based on the v0.1 branch. Is that OK?

**Comment by guangbochen** [comment]
since the dev version will use the `latest` UI which is not compatible with the v0.1 branch, therefore u will need to change the default `UIIndex` to `https://releases.rancher.com/harvester-ui/v0.1.4/index.html` instead.

**Comment by AmazingPangWei** [comment]
Thanks a lot! I modified the UIIndex in **scripts/build** and **pkg/settings/settings.go**, and that worked for me. 

But if I develop based on the v0.2 branch, must I change it again?
