### ISSUE TITLE
[BUG] VM is not bootable if not filling the boot order in volumes

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#734]
**Describe the bug**
VM is not bootable if not filling the boot order in volumes

**To Reproduce**
1. Go to the VM page
2. Create a VM, adding a CD_ROM and a disk
3. Not filling the boot order in the volumes

**Result**
VM is not bootable if not filling the boot order in volumes
![image](https://user-images.githubusercontent.com/57614736/115527392-9827ce00-a2c3-11eb-8e2a-4b65bc8fcd48.png)
BTW, why users are not allowed to edit the boot order in volumes?
![image](https://user-images.githubusercontent.com/57614736/115527518-b392d900-a2c3-11eb-9f8f-6da231e933bd.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Fixed.
