### ISSUE TITLE
[BUG] Ejecting the CD-ROM will abort the system boot and cause the VM to be not bootable

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#735]
**Describe the bug**
Ejecting the CD-ROM will abort the system boot and cause the VM to be not bootable

**To Reproduce**
1. Go to the VM page
2. Create a VM, add a CD-ROM and a disk, then save.
3. Once the VM status turns to `Running`, eject the CD-ROM

**Result**
Ejecting the CD-ROM will abort the system boot and cause the VM to be not bootable
![image](https://user-images.githubusercontent.com/57614736/115534766-b1804880-a2ca-11eb-8c27-c2f104c184b7.png)

**Environment:**
 - Harvester ISO version: master-head
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by yasker** [comment]
I don't believe this is a bug since the system is booting from the CDROM.
