### ISSUE TITLE
[BUG]The prompt text of mutiple instance's name prefix  is incorrect

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#736]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/115535690-93ffae80-a2cb-11eb-8b6d-44393c0cf375.png)
**To Reproduce**
1. Go to vm page
2. Click `Create`
3. switch to `Multiple instance`

**Expected behavior**

1. `Prefix Name` should be `Name Prefix`
2. Show `Name prefix for each instance` or something else

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
![image](https://user-images.githubusercontent.com/15064560/115535965-d628f000-a2cb-11eb-983e-f125a6797ac2.png)

**Comment by gitlawr** [comment]
![image](https://user-images.githubusercontent.com/5697937/115651461-cbb73680-a35d-11eb-93c5-134725dbda83.png)
And capitalize the `count` @WuJun2016

**Comment by futuretea** [comment]
need capitalize the `count`
![image](https://user-images.githubusercontent.com/15064560/115951091-6f951380-a511-11eb-9c6c-d1febe8515e8.png)

**Comment by futuretea** [comment]
validated on master-head
