### ISSUE TITLE
[BUG] The size of the images detail page is displayed ‘-’

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#739]
**Describe the bug**

The size of the images detail page is displayed ‘-’
**To Reproduce**
1. add an image to harvester
2. Go to the details page of image
![image](https://user-images.githubusercontent.com/15829074/115653246-69f8cb80-a361-11eb-8b2f-cfa7f2bd4050.png)

**Expected behavior**

Display the size of the image
**Log**

**Environment:**
 - Harvester ISO version: master-0008ce84-head
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
valiadted on master-0423.iso
![image](https://user-images.githubusercontent.com/15064560/115950782-dc0f1300-a50f-11eb-82e3-12281438a849.png)
