### ISSUE TITLE
[BUG] Inconsistent display for Download YAML and Delete buttons

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#742]
**Describe the bug**
![image](https://user-images.githubusercontent.com/5697937/115675370-1bf3c000-a381-11eb-9470-19aef68a20bf.png)
![image](https://user-images.githubusercontent.com/5697937/115675411-231ace00-a381-11eb-951d-85299d421423.png)

![image](https://user-images.githubusercontent.com/5697937/115675443-2ada7280-a381-11eb-9288-50917b999d1a.png)

In Hosts/Volumes/Images/SSH keys pages, the `Download YAML` and `Delete` buttons are shown by default.

In VMs/Templates/Users pages, they are displayed when an item is selected.

In Backups/Networks page, the `Download YAML` button is not available

**To Reproduce**
Check the UI

**Comment by futuretea** [comment]
In Backups page, the Download YAML button is not available
![image](https://user-images.githubusercontent.com/15064560/115982567-d3c9dd00-a5ce-11eb-94db-f9689bfe382c.png)

**Comment by WuJun2016** [comment]
@futuretea   The user does not need to download the backup yaml file, because the relevant content is stored in the backupcontent, so the download button is disabled in this place

**Comment by futuretea** [comment]
validated on master-head
