### ISSUE TITLE
[BUG]Missing spaces for input labels

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#743]
**To Reproduce**
1. Edit backup-target setting
![image](https://user-images.githubusercontent.com/5697937/115681479-25802680-a387-11eb-9d60-522964f97da6.png)

2. Edit vlan setting
![image](https://user-images.githubusercontent.com/5697937/115681560-3b8de700-a387-11eb-9974-1a37501e9be6.png)

**Expected behavior**

BucketName => Bucket Name
BucketRegion => Bucket Region
AccessKeyId => Access Key ID
SecretAccessKey => Secret Access Key
VirtualHostedStyle => Virtual Hosted-Style
DefaultPhysicalNIC => Default Physical NIC

**Environment:**
 - Harvester ISO version: master-c8e3e5b1-head(0422)

**Comment by futuretea** [comment]
validated on master-0423.iso
![image](https://user-images.githubusercontent.com/15064560/115951205-fe099500-a511-11eb-902d-0f63eccc8f24.png)
![image](https://user-images.githubusercontent.com/15064560/115951187-e9c59800-a511-11eb-951f-201565ac7560.png)
