### ISSUE TITLE
[BUG] Download yaml action fails when multiple items are selected

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#744]
**To Reproduce**
1. Select two VMs
2. Click the Download Yaml action

**Result**
Nothing happens in the UI.
Error logs in the browser console:
![image](https://user-images.githubusercontent.com/5697937/115692377-81e84380-a391-11eb-8c9e-7be12c08f0f3.png)

**Environment:**
 - Harvester ISO version: master-c8e3e5b1-head(0422)

**Comment by futuretea** [comment]
validated on master-0423.iso
