### ISSUE TITLE
[BUG] Wrong information in volume view page

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#746]
**To Reproduce**
1. Create a VM image
2. Create a Volume from the VM image.
3. View the Volume, check the detail
![image](https://user-images.githubusercontent.com/5697937/115694970-f3c18c80-a393-11eb-9d25-f70534c6a2f0.png)
`Select an Image` does not make sense, probably change to `Image Name`.
4. Click `Config` tab
![image](https://user-images.githubusercontent.com/5697937/115695180-210e3a80-a394-11eb-80d0-643dcbd08157.png)

The Source is `VM Image` on creation, but it shows New now.

**Environment:**
 - Harvester ISO version: master-c8e3e5b1-head(0422)

**Comment by futuretea** [comment]
In Config tab `Select an image` should be `Image`
![image](https://user-images.githubusercontent.com/15064560/115951416-35c50c80-a513-11eb-8a18-5b91847c9666.png)

**Comment by futuretea** [comment]
After click `Edit Config` `Select an image` should be `Image`
![image](https://user-images.githubusercontent.com/15064560/115982437-987ade80-a5cd-11eb-8eb8-7eb863003e08.png)

**Comment by futuretea** [comment]
validated on master-head
