### ISSUE TITLE
[FEATURE] Multi-disks management

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#747]
It's common for a bare-metal node to have multiple disks.

Currently, Harvester is only able to utilize the root disk for storage, even though Longhorn supports multiple disks.

There are a few things we need to do:
1. Separate the root disk from the data partition, even for the first disk, to ensure node pressure won't happen due to storage.
2. For other disks, provide an option (either in installer or UI) to format pre-exists raw block device, and add them automatically in Longhorn.
    * Be careful not to count Longhorn-provided block devices, since it's likely we need to support it in the UI with additional disks as well.
3. Provide disk management function in Harvester UI.

**Comment by guangbochen** [comment]
For existing Harvester users if u want to add multi-disks u can do it via longhorn's UI, run 
```
kubectl patch svc longhorn-frontend -p '{"spec": {"ports": [{"port":80, "targetPort":"http", "name":"http", "nodePort":30445}],"type": "NodePort"}}' -n longhorn-system
``` 
in your harvester node and visiting the Longhorn's UI via `http://node_ip:30445` and follow the doc instruction on https://longhorn.io/docs/1.1.1/volumes-and-nodes/multidisk/

**Comment by lanfon72** [comment]
> It's common for a bare-metal node to have multiple disks.
> 
> Currently, Harvester is only able to utilize the root disk for storage, even though Longhorn supports multiple disks.
> 
> There are a few things we need to do:
> 
> 1. Separate the root disk from the data partition, even for the first disk, to ensure node pressure won't happen due to storage.
> 2. For other disks, provide an option (either in installer or UI) to format pre-exists raw block device, and add them automatically in Longhorn.
>    
>    * Be careful not to count Longhorn-provided block devices, since it's likely we need to support it in the UI with additional disks as well.
> 3. Provide disk management function in Harvester UI.

@yasker please help to check and close this issue after the the result as the expected.

```
1. Verified the root disk has been separated into to data partition and other partitions.
    (As the pic [1] & [2] shown, root disk be separated into data partition (38G) and others)
2. Verified add new pre-exists raw block device is usable and successful.
    (As the pic [1] & [2] shown, pre-exists raw block device could be added from UI)
3. Verified the disk management function is work normally.
    (As the pic [3] shown, the function work normally.)
```
snapshots
----
[1] 
![image](https://user-images.githubusercontent.com/5169694/134532138-7f72c96d-f05f-4d7e-8e44-8bb15a49b72b.png)

[2]
![image](https://user-images.githubusercontent.com/5169694/134532812-199a02bf-d6b9-43f7-a408-a842bf699330.png)

[3]
![747-3](https://user-images.githubusercontent.com/5169694/134534062-effbf450-5d92-47ed-af23-b8fcb33347c7.png)

Test Information
----
* Environment: Laptop, QEMU/KVM, manual install
* Harvester Version: [master-1a041d23-head](https://github.com/harvester/harvester/commit/1a041d2371c5e70419bbe2a6997e8756054ab58c)
Verify Steps:
  - add multiple SATA Devices (60G/20G/20G) before boot
  - boot and install harvester manually
  - login to console, use `fdisk` to format secondary disks
  - verify dashboard implementation and disk's modification

**Comment by yasker** [comment]
The basically functionality looks good.

Let's track the issues later separately.

Ref:
https://github.com/harvester/harvester/issues/1240
https://github.com/harvester/harvester/issues/1237

@lanfon72 feel free to close the issue. QA is normally the one who close the issue.

**Comment by lanfon72** [comment]
close this issue as enhancement has been separated into other issues.
