### ISSUE TITLE
[BUG] Authentication failed on the first login

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#749]
**Describe the bug**

**To Reproduce**
1. Install harvester by ISO
2. Access the UI
3. set the password for the default admin, click continue

**Expected behavior**
Password is set and log in successfully.

**Result**
![image](https://user-images.githubusercontent.com/5697937/115856326-ea512680-a45e-11eb-968f-b729a76754cd.png)

**Environment:**
 - Harvester ISO version: master 0423
 - Installation Mode: ISO

**Comment by gitlawr** [comment]
CRDs(v1) created by Harvester are not compatible with CRDs(v1beta1) used in rancher v2.5.7

**Comment by futuretea** [comment]
validated on master-head
