### ISSUE TITLE
add usb-tablet enhancement to the QEMU

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#75]
add USB-tablet enhancement to the QEMU config that allowing the mouse to report its position without having to grab the mouse.
https://www.qemu.org/docs/master/system/usb.html

**Comment by thxCode** [comment]
@guangbochen Have we tried the input devices configuration before? 

According to https://kubevirt.io/user-guide/#/creation/devices?id=tablet and https://libvirt.org/formatdomain.html#input-devices, we can use `spec.template.spec.domain.devices.inputs` to indicate to emulate the tablet device as below:

```diff
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ...
spec:
  template:
    spec:
      domain:
        devices:
+         inputs:
+         - bus: usb
+           name: tablet
+           type: tablet

```

cc @gitlawr

**Comment by guangbochen** [comment]
maybe we should add this as an advanced configuration in the VM page and allow the user to disable if it is not required(this will default to true)?

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/pull/167
