### ISSUE TITLE
[FEATURE] Additional Authentication Providers.

### ISSUE THREAD

**Issue by michaelpearce-gain** [harvester/harvester#750]
**Is your feature request related to a problem? Please describe.**
Currently it seems only local user auth and k8s auth is supported. In an enterprise its typical to need to manage users, credentials and roles in a central authentication system. E.g. LDAP, Azure AD, Okta, Redhat SSO etc.

**Describe the solution you'd like**
Ability to connect authentication to LDAP, Azure AD, Okta etc.

**Describe alternatives you've considered**
There isn't one.

**Additional context**
Rancher support the above external auths, i guess the expectation would be for harvester to have similar level of auth integration support.

**Comment by michaelpearce-gain** [comment]
Along with this it would be important to be able to auto map roles to internal role authorisations that provide access/restrictions to functions areas/logical spaces, whilst i assume this would be a given, i think it just important to be explicit just to avoid any assumption.

**Comment by yasker** [comment]
@michaelpearce-gain This will be covered by #552 and #582 in v0.3.0 release.

I will close this issue as a duplicate for now. Feel free to reopen it or follow up in the above issues if there are more questions.
