### ISSUE TITLE
[FEATURE] add console feature to Hosts

### ISSUE THREAD

**Issue by rrrai** [harvester/harvester#752]
**Is your feature request related to a problem? Please describe.**
Currently to access consoles for the host for bare metal servers/machines

**Describe the solution you'd like**
It will be helpful to have console capability to hosts machine similar to remote login VM's for host nodes

**Describe alternatives you've considered**
Using hardware KVM or connecting physical screen/keyboard

**Additional context**
Baremetal 
v0.2.0-rc1

**Comment by futuretea** [comment]
@rrrai  what do you think about this solution?
Add a `console url` option to the configuration of each host in harvester, if the user configures this url, then UI will display a `console` button, and when the user clicks this console button, a new tab will be opened with the configured console url.
The value of the console url is fully customizable by the user：
1. IPMI address
2. KVM over IP address
3. webtty/gotty address
4. vnc address

**Comment by rrrai** [comment]
Hi Yuhang
This sounds like a great solution. This will cover all possible scenarios... from high end servers to shoe string budget bare-metal servers.

**Comment by noahgildersleeve** [comment]
Not currently in master-3edc82a7-head. Will check after next ISO build.

**Comment by noahgildersleeve** [comment]
Console button is available if you input console URL. Tested in master-3edc82a7-head

**Comment by abonillabeeche** [comment]
Is this really implemented? I don't see it - and it's not documented under
https://docs.harvesterhci.io/v0.3/host/host/
please let me know so I can reopen or open a bug for the docs. Thanks

**Comment by noahgildersleeve** [comment]
@abonillabeeche It's in the config for the host. You can edit it via the UI. 
![image](https://user-images.githubusercontent.com/83787952/138312320-c61ab1c6-5470-4368-a381-a634219968c3.png)
It mostly just allows you to input the

1. IPMI address
2. KVM over IP address
3. webtty/gotty address
4. vnc address

or anything similar. If it's not in the docs definitely open a bug for creating the docs for it. Thanks for pointing it out.
