### ISSUE TITLE
[BUG] Inconsistent display for `Host` and `Node`

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#769]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/116064963-17991100-a6b9-11eb-97c9-f84283b80396.png)
**To Reproduce**
1. Go to Harvester Dashboard

**Expected behavior**

Show `Hosts`

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by WuJun2016** [comment]
Hosts or Host is determined based on the number

**Comment by futuretea** [comment]
validated on master-head
![image](https://user-images.githubusercontent.com/15064560/116181052-83788980-a74c-11eb-95dc-6a7519346755.png)
