### ISSUE TITLE
[BUG] Unable to access to the Harvester dashboard (v0.2.0-rc4)

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#772]
**Describe the bug**
I tried to deploy the v0.2.0-rc4 version and I got HTTP error 404 when I try to connect to the dashboard: `404 page not found`
It happened both on bare-metal system and virtual machine.

**To Reproduce**
1. Install the last harvester ISO v0.2.0-rc4 and try to access the dashboard.

**Expected behavior**
We should see the harvester web login page.

**Log**
I don't know which log can be useful for you but you can tell me what you need, my cluster is still up.
All the pods look fine.

**Environment:**
 - Harvester ISO version: v0.2.0-rc4
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with ProLiant DL360 Gen9 and VM on my laptop

**Additional context**
N/A

**Comment by juadk** [comment]
Fixed by https://github.com/harvester/harvester/pull/773
I can access the dashboard with the last ISO, thx.

**Comment by futuretea** [comment]
@juadk Sorry, we have fixed this issue in :
* the new `harvester-amd64.iso` (sha256:7ed3a8ad68c21fff37c8c9cd8d0028562c50ce1e79cdb8832f6e63fa4f1cf2e9) 
* the new image  `rancher/harvester:v0.2.0-rc4` (sha256:84454494c7f093cb4ec0cec6154ec04c12998db711b822077ca77989de9e5b48)

Thank you very much!

**Comment by juadk** [comment]
No worries, we opened the same issue at the same time eh eh.
