### ISSUE TITLE
[BUG] Unable to login (Invalid CSRF Token)

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#774]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/116108539-9193bf00-a6e6-11eb-9ae5-3ecc7adf1085.png)

**To Reproduce**
There is currently no stable steps to reproduce

**Expected behavior**

login success

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
close due to inactivity and does not occur in the master-head version anymore.
