### ISSUE TITLE
[FEATURE] Simplify the operation of view all virtual machines on the specified host

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#782]
**Is your feature request related to a problem? Please describe.**

Current:
1. Click `Hosts`
2. Click one host
3. Click `VM Instance`
![image](https://user-images.githubusercontent.com/15064560/116338442-542a5100-a80e-11eb-9b08-69a538cda15a.png)

**Describe the solution you'd like**

Expect:
1.  Click Hosts
2.  Click one host (default to open vm instance page)

**Describe alternatives you've considered**

**Additional context**

**Comment by ldevulder** [comment]
Tested on version `master-902bee60-head`. On `Host` page when I click on a host I now directly have the `Virtual Machines` page with the list of active VMs on the node.

Issue closed.
