### ISSUE TITLE
[BUG] ui console error

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#784]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/116349676-1be13d80-a823-11eb-9722-466b2b5b883d.png)
**To Reproduce**
1. click any tab menu
2. click `Harvester` logo

**Expected behavior**

no any error

**Log**

**Environment:**
 - Harvester ISO version: 
 - Installation Mode: ISO/app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested in master-f38adc70-head. Verified as fixed. No console error
![image](https://user-images.githubusercontent.com/83787952/135156873-bc5436ef-3f1b-4dd0-8443-dcb8e9951d2d.png)
