### ISSUE TITLE
[FEATURE] Ability to share vm template

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#785]
**Is your feature request related to a problem? Please describe.**

currently, we can only download tempate's yaml

**Describe the solution you'd like**

- [ ] export template 
- [ ] import template

**Describe alternatives you've considered**

**Additional context**

**Comment by guangbochen** [comment]
- import or edit as YAML will be supported via https://github.com/harvester/harvester/issues/1304
- export template is already supported via 0.3.0 with download the YAML
