### ISSUE TITLE
[BUG] can not create vm instance

### ISSUE THREAD

**Issue by iswbm** [harvester/harvester#787]
**Describe the bug**

When I'm creating a virtual machine, the following error is reported: AttachVolume.Attach failed for volume "pvc-65422e18-ff21-4643-ac98-32ef08df05cf" : rpc error: code = Aborted desc = The volume pvc-65422e18-ff21-4643-ac98-32ef08df05cf in state detached is not ready for workloads

**To Reproduce**
1. Create a virtual machine on harvester web

**Expected behavior**

**Log**

![image](https://user-images.githubusercontent.com/22311419/116357216-d460ae80-a82e-11eb-88d1-ab559578c523.png)

**Environment:**
 - Harvester ISO version: No ISO
 - Installation Mode: app-mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**
 
a pod named backing-image-manager always on Terminating status

![image](https://user-images.githubusercontent.com/22311419/116357875-9912af80-a82f-11eb-8012-dbc57ea3cbc2.png)

**Comment by rrajendran17** [comment]
@iswbm can you get the output of kubectl describe pod backing-image-manager-17ed-066e -n longhorn-system ?
This is could hint us some reason for the backing image pod in terminating status.
Can you also check if the mgmt ip of that pod is reachable from harvester node ?

**Comment by w13915984028** [comment]
The issue was reported on an old Harvester version, we believe it had been solved in later versions, please try those new releases, thanks.
