### ISSUE TITLE
[Question] Is there a way to specify static IP range when creating multiple VM instance

### ISSUE THREAD

**Issue by rrrai** [harvester/harvester#792]
I am trying to create multiple VM instances with two network cards using cloud config below. For example I want to create 5 vm's will xx ranging from 31-35. The two choices I have are, to create 5 separate instance manually with desired static IP or creating one and then cloning it with different IP's. Is there a better way to specify the IP's range such that Harvester creates multiple instances automatically. 
Is this something that will be addressed by a future capability?

network:
  version: 1
  config:
  - type: physical
    name: enp1s0
    subnets:
      - type: dhcp
  - type: physical
    name: enp2s0
    subnets:
      - type: static
        address: 192.168.0.XX/23
        gateway: 192.168.1.1
        dns_nameservers:
          - 192.168.1.1
          - 8.8.8.8
      - type: route
        destination: 192.168.0.0/23
        gateway: 192.168.1.1
        metric: 1

**Comment by futuretea** [comment]
Personally, I would like to have programmability like vagrantfile
```Vagrantfile
Vagrant.configure("2") do |config|
 (11..11).each do |i|
    config.vm.define "harv#{i}" do |node|
      node.ssh.username = 'rancher'
      node.ssh.password = 'vagrant'
      node.ssh.insert_key = false
      node.vm.box = "harvester-dev"
      node.vm.guest = 'linux'
      node.vm.hostname = "harv#{i}"
      node.vm.synced_folder '.', '/vagrant', disabled: true
      node.vm.provider :libvirt do |domain|
        domain.driver = 'kvm'
        domain.memory = 16384
        domain.cpus = 8
        domain.nested = true
        domain.management_network_name = "harv"
        domain.management_network_address = "10.5.6.0/24"
        domain.management_network_mac = ip2mac("50:50","10.5.6.#{i}")
        domain.storage :file, :size => '2048G', :bus => 'virtio'
        domain.storage :file, :size => '1024G', :bus => 'virtio'
      end
      node.vm.provision :shell, :path => 'scripts/config-first-server.sh',
        :upload_path => '/home/rancher/vagrant-shell'
    end
  end
end
```

**Comment by futuretea** [comment]
Or possibly support template rendering
![image](https://user-images.githubusercontent.com/15064560/116507111-3681e800-a8f1-11eb-94ab-fc8feb288b2e.png)

**Comment by rrrai** [comment]
@futuretea 
Both of them will be a great addition. 
Should this become a feature request?

**Comment by futuretea** [comment]
@rrrai we are adding a [terraform-provider-harvester](https://github.com/harvester/terraform-provider-harvester), with the ablility of terraform, user can provision multi-instance with different configuration.

The user experience looks something like this https://github.com/futuretea/terraform-provider-harvester/blob/init/examples/k3os-cluster/k3os.tf
