### ISSUE TITLE
Cannot migrate VMs when the cluster consists of 2 nodes

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#798]
**To Reproduce**
1. Install Harvester with two nodes.
2. Create a VM
3. Migrate the VM to another node.

**Result**
The VM stucks in migrating state.

**Expected behavior**
Migration succeeds. Or tell the user this operation is not permitted

**Log**
The target pod is in ContainerCreating status.
```
NAME                                     READY   STATUS              RESTARTS   AGE
virt-launcher-lawr-1-j75dc               1/1     Running             0          116m
virt-launcher-lawr-1-tcxvq               0/1     ContainerCreating   0          8m47s


Warning  FailedAttachVolume  3s (x3 over 9s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-83b575fa-4229-46be-a6a0-186561a903cc" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-83b575fa-4229-46be-a6a0-186561a903cc to bm-harv2: volume must be healthy to start migration, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-83b575fa-4229-46be-a6a0-186561a903cc?action=attach]
```

And all volumes are degraded, given that the Longhorn replica is equal to 3.

**Environment:**
 - Harvester ISO version: v0.2.0-rc5

**Comment by guangbochen** [comment]
depends on https://github.com/longhorn/longhorn/issues/2805

**Comment by 2stacks** [comment]
@gitlawr can you work around this by changing the replica count in Longhorn to the number of hosts in your cluster?

`https://<mgmt_ip>/k8s/clusters/local/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:80/proxy/#/dashboard`

![longhorn3](https://user-images.githubusercontent.com/15258140/134012765-8bf49732-696d-491e-9bb1-b7f3bf021f18.png)

**Comment by guangbochen** [comment]
Volume degradation is supported via https://github.com/longhorn/longhorn/issues/2805, should be ready for testing.

**Comment by yasker** [comment]
@johnliu55tw Please file a separate UI issue regarding the new finding. Thanks.

**Comment by FrankYang0529** [comment]
## Test Info

* Verified version: v0.3.0-rc1
* Environment: 2 nodes in KVM

## Test cases

* Run a VM, create a file on VM, and migrate to another node.
  * [x] VM can be migrated.
  * [x] File is still existent.
* Followed above test case. Enable Maintenance Mode.
  * [x] VM can be migrated to another node.
  * [x] File is still existent.

**Comment by gsuess** [comment]
Now that this is closed and marked as complete, should the documentation here be updated accordingly? https://docs.harvesterhci.io/v1.1/vm/live-migration
