### ISSUE TITLE
[BUG] Unable to obtain complete installation information during ipxe deployment of harvester

### ISSUE THREAD

**Issue by kingsd041** [harvester/harvester#800]
Unable to obtain complete installation information during ipxe deployment of harvester

![image](https://user-images.githubusercontent.com/19684717/116534139-c08f7800-a914-11eb-9748-0f8d155ae98b.png)

**Environment:**
 - Harvester ISO version:  v0.2.0-rc5
 - Installation Mode: equinix ipxe
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Comment by juadk** [comment]
Tested successfully in build `master-abc91f03-head` ​with ISO mode and a 5 nodes cluster.
I changed my PXE configuration to cause an error (wrong link for the ISO) and I was able to see all the console output:
![Screenshot from 2021-06-21 15-19-02](https://user-images.githubusercontent.com/6025636/122769721-1a714600-d2a5-11eb-8e87-a06486ecbbdf.png)
