### ISSUE TITLE
[BUG] adjust the event tab columns in the VM detail page

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#801]
**Describe the bug**
adjust the event tab columns in the VM detail page

**Additional context**
![image](https://user-images.githubusercontent.com/4569037/116535469-58419600-a916-11eb-94c5-1540a8e46a0e.png)

**Comment by noahgildersleeve** [comment]
Tested in master-c13c2a35-head. Fixed.
![image](https://user-images.githubusercontent.com/83787952/119405427-177b3980-bc96-11eb-9f83-ef74f676b026.png)

**Comment by noahgildersleeve** [comment]
Closing
