### ISSUE TITLE
[BUG] UI - vlan config shouldn't be changed without using the edit config or edit YAML button

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#802]
**Describe the bug**
I'm not sure this a bug but it looks unclear to me.
Settings can be changed without using the `Edit Config / Edit YAML` buttons.
![image](https://user-images.githubusercontent.com/6025636/116534630-13e8d280-a8e3-11eb-9325-8f3586e23a53.png)

**To Reproduce**
1. Go to `Advanced / Settings`
2. Click on `vlan` at the bottom
3. Click on the `Config` tab
![image](https://user-images.githubusercontent.com/6025636/116534949-75a93c80-a8e3-11eb-9fba-85ffbcb6c634.png)
4. You can enable vlan and define a `Default Physical NIC` without using the `Edit config` button
5. After writing the settings, no `Save` button appears.
6. If you go back to the `Settings` summarize, you can see your fresh config:
![image](https://user-images.githubusercontent.com/6025636/116535306-e94b4980-a8e3-11eb-90ce-fb161a7fcfda.png)
7. But I can see the new interface in the network host configuration
![image](https://user-images.githubusercontent.com/6025636/116535480-113aad00-a8e4-11eb-8251-c8bdc030aa1d.png)
And then it is complicated to going back to a stable situation
8. However, all is working fine if I'm doing the same using the `Edit Config` button
![image](https://user-images.githubusercontent.com/6025636/116535684-4fd06780-a8e4-11eb-8f61-0c11853b2efc.png)
and I can see the network refresh:
![image](https://user-images.githubusercontent.com/6025636/116536253-f9aff400-a8e4-11eb-93a1-cf87e04b0a06.png)
and then, I can choose the interface I want:
![image](https://user-images.githubusercontent.com/6025636/116536307-0c2a2d80-a8e5-11eb-9331-fce1a4b13dbb.png)

**Expected behavior**

From my point of view, it shouldn't be able to change the settings without using both `Edit` buttons, otherwise, the `Save` button should appear to be sure the settings will be applied.

**Environment:**
 - Harvester ISO version: 0.2.0-rc5
 - Installation Mode: ISO
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal

**Comment by noahgildersleeve** [comment]
You can't edit this at all now. There is no edit config or edit YAML button. Is that by design?

**Comment by guangbochen** [comment]
The `Config` tab would allow the user to either view what are the configurable parameters or having a preview of the UI changes with the configured parameters, however, this will not be saved to the backend unless the user clicks edit to and save it manually.

This is the same design that we have inherited from the rancher dashboard, will just make it consistent for now.

**Comment by noahgildersleeve** [comment]
You can't edit this at all now. This might be related to something else. I'm looking into it.
![image](https://user-images.githubusercontent.com/83787952/119404168-4abcc900-bc94-11eb-97aa-1d0219d8e4df.png)

**Comment by noahgildersleeve** [comment]
Blocked by https://github.com/harvester/harvester/issues/901

**Comment by noahgildersleeve** [comment]
tested in build `master-199b3b79-head`. The config tab in VLANs has been removed, and the new UI doesn't include it. You can't currently edit the VLAN without selecting edit config. Closing
