### ISSUE TITLE
[Doc] Document required explaining how user can set up proxy URL for Harvester UI to access UI from outside the world.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#804]
Document required explaining how user can set up proxy URL for Harvester UI to access UI from outside the world.

**Comment by yasker** [comment]
@khushboo-rancher Is this still valid?

**Comment by khushboo-rancher** [comment]
Not valid, we have https://docs.harvesterhci.io/v1.0/settings/settings/#http-proxy in place already.
