### ISSUE TITLE
[FEATURE] display the sate of physical NICs

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#807]
**Is your feature request related to a problem? Please describe.**

The physical NICs which is not up are invalid for the VLAN network. Thus, it's better to not display them.

``` shell
bm-harv3 [/home/rancher]$ ip a show dev eth0
2: eth0: <BROADCAST,MULTICAST,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc mq master harvester-br0 state UP group default qlen 1000
    link/ether b8:ca:3a:f9:9b:5c brd ff:ff:ff:ff:ff:ff
    inet 172.16.4.3/16 brd 172.16.255.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fd31:f874:bf29::e39/64 scope global
       valid_lft forever preferred_lft forever
    inet6 fe80::baca:3aff:fef9:9b5c/64 scope link
       valid_lft forever preferred_lft forever
bm-harv3 [/home/rancher]$ ip a show dev eth1
3: eth1: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether b8:ca:3a:f9:9b:5d brd ff:ff:ff:ff:ff:ff
bm-harv3 [/home/rancher]$ ip a show dev eth2
4: eth2: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether b8:ca:3a:f9:9b:5e brd ff:ff:ff:ff:ff:ff
bm-harv3 [/home/rancher]$ ip a show dev eth3
5: eth3: <NO-CARRIER,BROADCAST,MULTICAST,DYNAMIC,UP> mtu 1500 qdisc mq state DOWN group default qlen 1000
    link/ether b8:ca:3a:f9:9b:5f brd ff:ff:ff:ff:ff:ff
```

![image](https://user-images.githubusercontent.com/7421463/116643836-7c4bb880-a9a4-11eb-91c0-0ceb3ee6b90f.png)

**Describe the solution you'd like**

The node network CRs will not save the physical NICs which are not in an up state.

**Describe alternatives you've considered**

**Additional context**

**Comment by Remigius2011** [comment]
Actually, it might be better just to mark them as currently down - it might be that there's just a temporary reason why they are down and one might still want to select them (or keep them selected)

**Comment by yaocw2020** [comment]
@WuJun2016 Please help to display the state of NICs in the UI.

**Comment by WuJun2016** [comment]
To test:
1.  Make sure you are using the latest iso version on and after Aug 19
2. click advanced, enter setting page
3. edit Vlan (enabled vlan, fill in the correct NIC)
4. go to node page and edit node config
5. choose Network tab,  （You can see the state in the NIC drop-down box）
![image](https://user-images.githubusercontent.com/24985926/129855562-fdb3ffac-c76e-4904-bbcd-24df9884ff9b.png)

**Comment by ldevulder** [comment]
I tried with latest `master-head` build but I was not able to select a NIC as well as see the NIC state, here waht I have on the screen:
![harvester-nic-selection](https://user-images.githubusercontent.com/25102165/129906693-84f9152a-3433-46bd-ac44-2f0563b153f7.png)

I tried on a baremetal 5 nodes cluster with 2 NICs on each nodes as well as on a VM with 4 virtual NICs attached: same issue.

Did I do something wrong during my test? I follow @WuJun2016 's procedure.

**Comment by WuJun2016** [comment]
@ldevulder   Is your vlan enabled ?  
1. go to setting page, 
2.  edit vlan， enable vlan， and fill in the correct NIC

like this: 
![image](https://user-images.githubusercontent.com/24985926/129998167-8284333a-22af-48a4-bf57-a540e1dfcdd7.png)

**Comment by ldevulder** [comment]
@WuJun2016 Yes vlan is enabled. I checked again and cleaned my web cache this time and all is fine now... Maybe related to the WebUI changes? And this is why a clean cache fixed the issue? Or could be a chair/keyboard interface problem :D But as I tested this on 2 different clusters I'm more for the cache issue.

Anyway it works now, the issue could be closed.
