### ISSUE TITLE
[BUG] ISO install accepts multiple words for 'cluster token' value resulting in failure to join cluster

### ISSUE THREAD

**Issue by dev-dull** [harvester/harvester#812]
**Describe the bug**
When installing from ISO, the user is prompted for a cluster token. I had set `satellite of love` for my main server (gypsy; physical server) and two nodes (tom-servo; physical server, crow; virtual machine). The server/controller boots and is accessible as expected, but the nodes never successfully join.

**To Reproduce**
1. Boot main server/controller from ISO and select the option to create a new cluster
2. At the 'Cluster token' prompt, enter, `satellite of love`
3. proceed to complete the installation
4. Boot a secondary host from the installation ISO and select the option to join an existing cluster
5. At the 'Cluster token' prompt, enter, `satellite of love`
6. proceed to complete the installation

**Expected behavior**
The new hosts should join the existing cluster, OR, the installer should not permit the user to continue with installation until an appropriate 'cluster token' is used.

**Log**
On the host attempting to join the existing cluster, the tail of `/var/log/k3s-service.log` will show a message stating that `--token` is required.

**Environment:**
 - Harvester ISO version: 0.2.0
 - Installation Mode: ISO
 - Underlying Infrastructure:
   - Bare metal; Intel(R) Xeon(R) CPU E5-2609 0 @ 2.40GHz, 8GB
   - Bare metal; Intel(R) Xeon(R) CPU E5-2609 0 @ 2.40GHz, 4GB
   - XCP-ng VM, 4 CPUs @ 2.1Ghz CPU, 16GB

**Comment by yasker** [comment]
Thanks for the report @dev-dull . It's probably the space in `satellite of love`. 

1. We should prevent users from typing or input invalid token values.
2. If we failed to join due to a token issue, or any related issue, there should be an easy way for the user to figure out what's wrong. We should either show it in the console, or document an easy troubleshooting process.

**Comment by rrrai** [comment]
I ran into a similar issue but with a token that had letters, numbers and special characters !<@( . Had to reinstall Harvester
Ability to extract and modify token once set will be really helpful

**Comment by bk201** [comment]
The [generated k3s env file ](https://github.com/k3s-io/k3s/blob/245efe0d665838dfc228e3442efd11bcd3b39ec8/install.sh#L705-L713)doesn't quote the variable and the [variable sourcing](https://github.com/k3s-io/k3s/blob/7a10a9971f224b2335302acb2ab8b25baf142c3f/install.sh#L779-L784) is failing:

```
# cat /etc/rancher/k3s/k3s-service.env
K3S_CLUSTER_SECRET=there is a space
K3S_URL=https://10.33.33.11:6443

# /etc/init.d/k3s-service start
/lib/rc/sh/openrc-run.sh: /etc/rancher/k3s/k3s-service.env: line 1: is: not found
 * Starting k3s-service ...

```

**Comment by yasker** [comment]
We also need to exclude any invalid characters we cannot accept. Better make a whitelist instead of a blacklist.

**Comment by yasker** [comment]
In fact, since we're changing to the new OS, we need wait for the OS switching before fixing this.

**Comment by bk201** [comment]
I didn't see this issue in the new OS.
The token is escaped well in RKE2 config.
```
# cat /etc/rancher/rke2/config.yaml.d/50-rancher.yaml
{
  "node-label": [
    "harvesterhci.io/managed=true",
    "rke.cattle.io/machine=c8c51b07-7984-4187-8c4e-edfa6b69f5e6"
  ],
  "server": "https://10.10.0.15:9345",
  "token": "a b c"
}
```

**Comment by johnliu55tw** [comment]
Test cases:
- `satellite of love`: Passed
- `= = :) ;P /???\`: Passed
- `"token"`: Passed
- `'token'`: **Failed**

If the string contains single quotes, the system stuck at the state where Harvester management URL shows "Unavailable" and Current status is "NotReady" after installation.
![image](https://user-images.githubusercontent.com/5047724/135555227-b050d9d1-cb02-4b8b-85dc-f07086143f62.png)

Switch to Shell and found the file `/etc/rancher/rke2/config.yaml.d/50-rancher.yaml` does not exist.

Also, `journalctl` show message like this:
```
Oct 01 02:40:41 asdf rancherd[1884]: time="2021-10-01T02:40:41Z" level=info msg="failed to bootstrap system, will retry: loading config from /etc/rancher/rancherd/config.yaml: error converting YAML to JSON: yaml: line 1: did not find expected key"
```
Content of file `/etc/rancher/rancherd/config.yaml`:
```
role: cluster-init
token: ''token''
kubernetesVersion: v1.21.4-rc1+rke2r4
labels:
 - harvesterhci.io/managed=true
```

Looks like the single quotes got escaped incorrectly. I checked the installer generated config YAML during the installation and noticed that it should be escaped like this in YAML:
```
serverurl: ""
token: '''token'''
os: ...
```

**Comment by yasker** [comment]
Move back to New Issues and punt to v1.0.0 to solve the single quote issue.

**Comment by guangbochen** [comment]
I think instead of supporting all characters, it is better for us to add validation and return errors if the token does not meet the requirements. e.g using  https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-subdomain-names validation

**Comment by johnliu55tw** [comment]
Please see https://github.com/harvester/harvester-installer/pull/174 for detail of the fix.

**Comment by noahgildersleeve** [comment]
Tested with master-655c251a-head on vagrant ipxe install by changing token to `satellite of love`. Install of 3 node cluster completed successfully.
