### ISSUE TITLE
Change boot order of disks in VM

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#813]
**Is your feature request related to a problem? Please describe.**
I've built a VM using the 'iso' template. After the VM has completed installing the OS (Ubuntu 20.04) it ends with the virtual disk at "Boot order: 1" and the CD-ROM as "Boot order: 2".
I want to boot from the CD-ROM again.
The UI does not allow me to change the "Boot order".

**Describe the solution you'd like**
The UI should allow altering the boot order, in the same way that the you can change the boot order when creating a VM.

**Describe alternatives you've considered**
Editing the YAML works, but is not a good UX.

**Additional context**
When talking about the issue on Slack, https://rancher-users.slack.com/archives/C01GKHKAG0K/p1619866196244100 , Sheng Yang said:
> Probably an oversight. We should allow order change at least when the VM is down.

**Comment by noahgildersleeve** [comment]
Currently testing this is blocked by https://github.com/harvester/harvester/issues/892 .

**Comment by noahgildersleeve** [comment]
Moving back to implement due to blocking dependent issue.

**Comment by noahgildersleeve** [comment]
Moving back to analysis/design due to needed UI elements for testing.

**Comment by WuJun2016** [comment]
test step:
1. Drag and drop to change boot order
2. Use the up and down arrow buttons to change the boot order

![image](https://user-images.githubusercontent.com/24985926/131676291-90f2f9b0-6902-40a0-8ae7-82763ff0567f.png)

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Fixed.
