### ISSUE TITLE
Change boot order of disks when creating a VM

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#814]
**Is your feature request related to a problem? Please describe.**
When manipulating the "Boot order" of volumes while creating a new machine, you cannot just swap the "Boot order" two volumes (make the volume that was boot order 2 be boot order 1, and visa-versa).
This does not work:
1 -> 2 (implies 2 -> 1)
You have to do:
2 -> 3
1 -> 2
3 -> 1
This is understandable, but not intuitive.

**Describe the solution you'd like**
The UI should be more clever when changing the boot order. 

**Describe alternatives you've considered**
As said above, you have to move one drive into an unused position, then move it back.

**Additional context**
When talking about the issue on Slack, https://rancher-users.slack.com/archives/C01GKHKAG0K/p1619868428249700, Sheng Yang said:
> We can improve that using some UI tricks.

**Comment by WuJun2016** [comment]
See the UX & test step:  https://github.com/harvester/harvester/issues/813

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Fixed.
