### ISSUE TITLE
Validate the name in the UI when creating a template

### ISSUE THREAD

**Issue by himslm01** [harvester/harvester#815]
**Is your feature request related to a problem? Please describe.**
Creating Templates from a configured VM is awesome.
It would be better if the name validation happened while typing, not after you've clicked "create" and the dialogue has closed.

**Describe the solution you'd like**
All 'name' fields should have validation code in the UI. 

**Describe alternatives you've considered**
Can't think of any alternatives.

**Additional context**
When talking about the issue on Slack, https://rancher-users.slack.com/archives/C01GKHKAG0K/p1619867218245700, Sheng Yang said:
> Yeah

**Comment by noahgildersleeve** [comment]
Tested in `master-c13c2a35-head`. Verified as fixed. The name field now has name validation.
