### ISSUE TITLE
[FEATURE] VM host selection

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#817]
**Is your feature request related to a problem? Please describe.**
Allow the ability to choose the initial host to deploy the VM

**Describe the solution you'd like**
Virtual Machines -> Create VM -> Host: drop down to choose one of all available hosts

**Describe alternatives you've considered**
Afinity or Anti-Afinity to other labels or virtual machines

**Additional context**
The goal is to be able to deploy a VM on a specific host or to avoid a host in which certain other VMs are already running.

**Comment by DaiYuzeng** [comment]
We are going to replace the Input Component with Select Component for the node selector enhancement.

**Comment by FrankYang0529** [comment]
## Test info

* Verified version: v0.3.0-rc1
* Environment: 2 nodes on KVM

## Test cases

* Choose a specific node to deploy a VM.
  * [x] Dashboard can list available nodes.
![Screenshot from 2021-10-04 13-17-13](https://user-images.githubusercontent.com/4927361/135798107-47acda47-4f14-4ad1-b606-005bf14eb79d.png)
  * [x] VM can be deployed to a specific node.
![Screenshot from 2021-10-04 13-17-45](https://user-images.githubusercontent.com/4927361/135798192-a3f226f1-4278-44fb-8ade-199a12da8438.png)

## Comments

If a node is maintenance mode, it still can be listed in the selection. Not sure whether we should hide nodes with maintenance mode in the selection. cc @yasker

**Comment by yasker** [comment]
@FrankYang0529 You're right, the nodes in the maintenance modes shouldn't be listed. Please file a separate issue regarding the node in the maintenance mode. We will track it for v1.0.0 release.

**Comment by FrankYang0529** [comment]
File a new issue https://github.com/harvester/harvester/issues/1350 and close this one.
