### ISSUE TITLE
[Question] Naming `rancher-harvester` vs `harvester` and Readme.md.in

### ISSUE THREAD

**Issue by jubalh** [harvester/harvester#821]
I intended to create a PR that changes https://github.com/harvester/harvester/blob/master/main.go#L35 from `rancher-harvester` to `harvester`.

Reasons:
* Commit 476ee31f14b859dacdfa73fe40e8ddcdcee5c268 did rename `Rancher Harvester` to `Harvester` in several documentation locations.
* Since our repository is called `harvester` a regular `go build` will also name the binary `harvester`.
* In `README.md.in` the binary is mentioned as `./bin/harvester`.

Speaking of `README.md.in`, is this file actually used or a leftover?

Let me know what you think :) Maybe I'm missing something, or some tool expects this name?

**Comment by guangbochen** [comment]
yep, both the app name and `README.md.in` file are leftover and either need to be changed or removed, please feel free to submit a PR for it, thanks.
