### ISSUE TITLE
[Question] Can't install guest agent for a running VM

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#837]
**Describe the bug**

We cannot install a guest agent for a running VM. 

**To Reproduce**
1. Select a running VM without a guest agent and edit the VM config.
2. Go to the `Advanced Options` tab, check the box `install guest agent` and then click the save button.
3. After restarting, we still can't see the IP address of the VM.

**Expected behavior**

Install guest agent successfully and we can see the IP address of the VM.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Dell PowerEdge R630

**Additional context**

**Comment by futuretea** [comment]
cloud-init will only be executed once
try `cloud-init clean --logs --reboot`


https://cloudinit.readthedocs.io/en/latest/topics/cli.html#clean

**Comment by guangbochen** [comment]
move those kinds of questions to the Harvester FAQ docs.

**Comment by guangbochen** [comment]
close in favor of https://docs.harvesterhci.io/v0.3/faq/
