### ISSUE TITLE
[FEATURE] allow default storage class configuration

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#842]
**Is your feature request related to a problem? Please describe.**
For development purposes, when running a Harvester-in-Harvester, the disk performance of the longhorn in the nested environment will be less efficient, therefore we should allow the user to config an alternative storage class like [local-path-provisioner](https://github.com/rancher/local-path-provisioner) for better performance tunning.

**Describe the solution you'd like**
Add a setting to allow the user to configure an alternative storage class, however, this will only be compatible with VM using ISO installation in the current stage, and this is because the Harvester image feature requirements of https://github.com/harvester/harvester/issues/368.

**Describe alternatives you've considered**
N/A

**Additional Context**
User will need to deploy the custom storage class manually to the Harvester cluster, e.g using the local path provisioner https://github.com/rancher/local-path-provisioner

Also, this is for development purposes only, since many features including live migration, backing image support, backup/restore won't be supported.

**Comment by Jellyfrog** [comment]
I think local path provider should be included,
Since longhorn adds quite a performance hit it would be nice with a fast storage alternative for databases etc. Even with its limits

**Comment by guangbochen** [comment]
close as this is resolved by the https://github.com/harvester/harvester/issues/2147
