### ISSUE TITLE
[BUG] One node of a three-node cluster lost IP after a couple of days

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#845]
**Describe the bug**
One node of a three-node cluster lost IP after a couple of days

**To Reproduce**
Only happened in one environment. No active action was taken except for creating a few VMs on top of the cluster.

**Expected behavior**
IP won't be lost

**Support bundle**
n/a

**Environment:**
 - Harvester ISO version: v0.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DELL PowerEdge R630

**Additional context**
The following steps have been performed on the node:
1. `udhcpc harvester-br0` doesn't work. Failed to acquire DHCP lease.
2. `udhcpc eth4` doesn't work. Failed to acquire DHCP lease.
3. `brctl delif harvester-br0 eth4` then `udhcpc eht4` get the DHCP lease correctly after.

**Comment by yasker** [comment]
It happened again...

**Comment by guangbochen** [comment]
close due to inactivity and does not occur in the 0.3-master-head version.
