### ISSUE TITLE
[BUG] 'Labels' appears twice on the create image page.

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#847]
**To Reproduce**
1. Go to 'Create image' page.
2. Go to 'Labels' tab

<img width="1522" alt="Screen Shot 2021-05-10 at 6 24 05 PM" src="https://user-images.githubusercontent.com/60111667/117744398-74b6bb80-b1bd-11eb-8926-1640a2903617.png">

**Expected behavior**
Labels title should appear only once.

**Environment:**
 - Harvester ISO version: v0.2.0-rc5

**Comment by juadk** [comment]
Tested successfully in build `master-6d5c7df2-head` ​with ISO mode and 5 nodes cluster.

![image](https://user-images.githubusercontent.com/6025636/122223352-5f673800-ceb3-11eb-8b10-c73acfb9af3b.png)

I added a label and checked the YAML file, all good.
![image](https://user-images.githubusercontent.com/6025636/122223499-80c82400-ceb3-11eb-975b-d1c5e072c611.png)
![image](https://user-images.githubusercontent.com/6025636/122223707-b79e3a00-ceb3-11eb-892b-72569925b448.png)
Issue can be closed.
