### ISSUE TITLE
In the process of creating harvester cluster, rancher restart causes cluster creation failure

### ISSUE THREAD

**Issue by TangStone** [harvester/harvester#848]
**Describe the bug**

node template
![image](https://user-images.githubusercontent.com/15829074/117752553-91003a00-b249-11eb-8c9c-440c868dd2b7.png)
harvester cluster configuration, other options default
![image](https://user-images.githubusercontent.com/15829074/117752673-c9a01380-b249-11eb-846a-ae3d27864170.png)
Current status of the cluster
![image](https://user-images.githubusercontent.com/15829074/117752745-e89ea580-b249-11eb-9112-f9e00af1f19c.png)
![image](https://user-images.githubusercontent.com/15829074/117752813-066c0a80-b24a-11eb-9f34-277d6b40a8bd.png)
![image](https://user-images.githubusercontent.com/15829074/117752845-12f06300-b24a-11eb-9bcf-d7f7aad4323e.png)

**To Reproduce**
1. Install harvester v0.2.0-rc4 successfully
- The node information is as follows

| Name | CPU | Memory 
| --- | --- | --- 
| harvester | 8c | 8G 
| harvester2 | 8c | 8G 
| harvester3 | 8c | 7G 

2. Add image(ubuntu-18.04-server-cloudimg-amd64.img) 
3. Enable rancher-enabled
4. execute command ` kubectl patch setting upgradable-versions --type=merge -p 'value: v0.2.0' `on harvester node
"
5. UI operation to upgrade the cluster to v0.2.0
6. Create a harvester cluster

**Expected behavior**

Upgrade to v0.2.0, able to create harvester cluster successfully
**Support bundle**

[harvester-supportbundle_dc7679e8-ece5-4e4e-853a-fa7f9e068e4f_2021-05-11T03-17-27Z.zip](https://github.com/harvester/harvester/files/6456308/harvester-supportbundle_dc7679e8-ece5-4e4e-853a-fa7f9e068e4f_2021-05-11T03-17-27Z.zip)

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by guangbochen** [comment]
@futuretea is this still an issue of the node driver?

**Comment by guangbochen** [comment]
close of v0.3.0
