### ISSUE TITLE
A virtual machine cannot be created by using the generated hostname with uppercase

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#85]
**Steps to replicate:**
1. Select one of the images, in this case, select `CentOS-7-x86_64-GenericCloud.qcow2.xz`
2. Fill up other information and save it

**Result:**
The virtual machine cannot be created because of the invalid hostname
![image](https://user-images.githubusercontent.com/57614736/91433682-3d55e800-e896-11ea-964e-432b62e9f417.png)

**Suggestion:**
It makes no sense that a user cannot create a virtual machine by using a generated name by default even though a hostname is not allowed to have any upper case. 

If there is no way to have this kind of name to be saved, it's better to let the frontend convert the uppercase to lowercase before sending it to the backend.

**Comment by guangbochen** [comment]
fixed in the latest harvester with default to lowercase name.
