### ISSUE TITLE
[BUG] clicking enter in SSH key name entry closes modal

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#854]
**Describe the bug**
When you click enter while in the SSH key name entry field it closes the modal, but only seems to hide it. The data is still there if you re-enter it

**To Reproduce**
1. Create a new VM
2. Select a template to create it
3. Click add SSH Key
4. Enter in your key
5. Enter in a name
6. Click enter while in the name field
7. Click add SSH key again

**Expected behavior**
It should either create the SSH key and give an error if there is anything wrong, or it shouldn't do anything

**Support bundle**
[harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-11T20-32-28Z.zip](https://github.com/harvester/harvester/files/6461865/harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-11T20-32-28Z.zip)

**Environment:**
 - Harvester ISO version: 0.2.0-rc5 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL360G9 cluster with 2 nodes

**Additional context**
![ssh-key-enter](https://user-images.githubusercontent.com/83787952/117880583-20fbaf00-b25d-11eb-9c38-73b078a7b380.gif)

**Comment by noahgildersleeve** [comment]
Tested in master-c13c2a35-head. It clears the fields now when you click enter. @yasker . Is that the desired behavior, or do we want to disable the enter key closing that modal?

**Comment by yasker** [comment]
I don't think it makes sense to clear the field when enter. @WuJun2016 can you explain the desired behavior?

**Comment by WuJun2016** [comment]
@yasker  @noahgildersleeve  This is not the behavior I want, it's a bug I didn't notice,

**Comment by noahgildersleeve** [comment]
Tested in master-199b3b79-head with external UI (new UI). Validated as fixed. Still having issue with bundled UI.
