### ISSUE TITLE
[BUG] Chart-wrong ConfigMap for longhorn StorageClass after upgrading

### ISSUE THREAD

**Issue by joy717** [harvester/harvester#857]
**Describe the bug**
The longhorn-storageclass-override.yaml will be overridden by charts/longhorn after upgrading.

**To Reproduce**
1. install via helm chart.  
`kubectl get cm -n longhorn-system longhorn-storageclass -o yaml`. 
 will find "migratable" property.
2. upgrade via helm. 
3. `kubectl get cm -n longhorn-system longhorn-storageclass -o yaml`.  
now  "migratable" property is missing.

**Expected behavior**
longhorn-storageclass-override.yaml should work correctly after upgrading.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by gitlawr** [comment]
The storageclass-override stuff is kind of a workaround due to the release time frame. It would be more straightforward if we can make the parameter configurable in the Longhorn chart. I've opened a Longhorn issue for the request: https://github.com/longhorn/longhorn/issues/2594

**Comment by innobead** [comment]
> The storageclass-override stuff is kind of a workaround due to the release time frame. It would be more straightforward if we can make the parameter configurable in the Longhorn chart. I've opened a Longhorn issue for the request: [longhorn/longhorn#2594](https://github.com/longhorn/longhorn/issues/2594)

Please check https://github.com/longhorn/longhorn/issues/2594#issuecomment-841667027. I would suggest just using an individual storage class to avoid this kind of coupling/dependency.

cc @joshimoo

**Comment by gitlawr** [comment]
To test:
Dev mode
1. Install Harvester by [helm chart](https://docs.harvesterhci.io/v0.2/dev/dev-mode/#option-1-install-using-helm)
2. Check the params in the longhorn storageclass: `kubectl get sc longhorn -o yaml`
3. Upgrade using helm: 
```
helm upgrade harvester harvester \
--namespace harvester-system \
--set longhorn.enabled=true \
--set a=b
```
4. Check the params in the longhorn storageclass: `kubectl get sc longhorn -o yaml`

HCI mode
1. Install harvester by ISO image
2. Check the params in the longhorn storageclass: `kubectl get sc longhorn -o yaml`
3. Upgrade helm release by `kubectl -n kube-system edit helmchart harvester`, then add `a: b` to `spec.set`
4. Wait and check the storageclass params

**Comment by juadk** [comment]
**Test with dev mode ok:**
The parameter `migratable` is still there after the upgrade.

1. Install Harvester by helm chart
`helm install harvester harvester --namespace harvester-system --set service.harvester.type=NodePort --set longhorn.enabled=true`
2. Check the params in the longhorn storageclass:
```
kubectl get sc longhorn -o yaml|grep migratable
        migratable: "true"
  migratable: "true"
```
3. Upgrade
helm upgrade harvester harvester --namespace harvester-system --set longhorn.enabled=true --set a=b

4. Check the params in the longhorn storageclass:
```
kubectl get sc longhorn -o yaml|grep migratable
        migratable: "true"
  migratable: "true"
```
**Test with HCI mode: master-abc91f03-head**
1. Check the params:
```
kubectl get sc longhorn -o yaml|grep migratable
        migratable: "true"
        f:migratable: {}
  migratable: "true"
```
2. Upgrade helm release and add `a: b` to spec.set
```
kubectl -n kube-system edit helmchart harvester
helmchart.helm.cattle.io/harvester edited
```
3. Check the storageclass params:
```
kubectl get sc longhorn -o yaml|grep migratable
        migratable: "true"
        f:migratable: {}
  migratable: "true"
```
