### ISSUE TITLE
[FEATURE] allow specifying a harvester template vs rancher template for node driver

### ISSUE THREAD

**Issue by abonillabeeche** [harvester/harvester#858]
**Is your feature request related to a problem? Please describe.**
I inject DNS, users and certain specific values via Cloud Config Templates - which are available within Harvester but not within the Harvester node driver Template

**Describe the solution you'd like**
Would like to specify a Harvester template instead of having to re-create a template - not only besides of re-creation but because Harvester has Cloud Config Templates.

**Describe alternatives you've considered**
1. Enable Cloud Config Templates to the Rancher Node driver for Harvester; or
2. Allow us to specify a Harvester template within the Node Template creation in Rancher.

**Comment by yasker** [comment]
I think making a Harvester template selectable when creating clusters in Rancher should be better.

**Comment by futuretea** [comment]
implements:
https://github.com/rancher/ui/pull/4705
https://github.com/rancher/dashboard/pull/3348

**Comment by guangbochen** [comment]
For the current design, the user is able to select the existing cloud-config template and customize it if needed.

**Comment by ldevulder** [comment]
I used Rancher version `master-0a0d07a` and Harvester version `master-bc40fc79-head`, I created a Cloud Config template on my Harvester cluster and I tested:
- with RKE1, I was able to select the template in Rancher dashboard
- with RKE2, I was able to select the template in Rancher dashboard
- with RKE2/k3s, I was able to select the template in Rancher dashboard

So changes are validated, the issue can be closed.
