### ISSUE TITLE
[BUG] Serial console doesn't work on safari for ubuntu image

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#859]
**Describe the bug**
The serial console hangs and doesn't allow to access the serial console on safari browser.

**To Reproduce**
1. Deploy harvester on three nodes.
2. Open the Harvester UI on safari browser 14.0.3
3. Create a vm with cloud image - `http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img`.
4. Open the serial console, it hangs with blank terminal.

**Expected behavior**
The serial console should allow user to access the vm.

**Environment:**
 - Harvester ISO version:  0.2.0-rc5

**Comment by noahgildersleeve** [comment]
Tested in master-199b3b79-head on external UI (new UI). Validated as working.
