### ISSUE TITLE
VM create page issues

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#86]
- [x] 1. Create a VM with no image selected, the create button turns to created - `Validated`
![image](https://user-images.githubusercontent.com/57614736/91435576-1a790300-e899-11ea-8ec1-caf09967528a.png)

- [x] 2. Create a VM with the only image selected, the page title disappears - `Validated`
![image](https://user-images.githubusercontent.com/57614736/91435816-852a3e80-e899-11ea-9b68-ba2638a72cc9.png)

- [x] 3. An image just can be searched by using the accurate criteria, e.g., if a user searches the image by using the keyword `cent `, it will just filter out all the items contains `cent` accurately. (Case sensitive) - `Validated`

- [x] 4. Choose a Size, CPU and Memory textboxes are allowed to fill in non-numeric values if a user is using a Chinese input method - `Validated`

- [x] 5. Choose a Size, CPU and Memory textboxes are allowed to fill in a super large number, and they finally turn into infinity - `Validated` 
![image](https://user-images.githubusercontent.com/57614736/91436583-f9191680-e89a-11ea-989f-4e1ab15e19ac.png)

- [x] 6. Add a disk, there is no limit length on the Name, users can name it with a very very long string. Size has no limit as well, after clicking the `show advanced`, there is `show advanced` still displaying. Edit a disk, it still pops up a 'Add a disk' prompt - `Validated` 
![image](https://user-images.githubusercontent.com/57614736/91436773-5ad98080-e89b-11ea-8a39-21e592318bc0.png)

- [x] 7. Add a networking interface, there is no limit length on the Name and Networking Name, users can name it with a very very long string, size has no limit as well. Edit a networking interface, it still pops up a 'Add a networking interface' prompt. An invalid Mac Address still can be saved - - `Validated` 
![image](https://user-images.githubusercontent.com/57614736/91437501-945ebb80-e89c-11ea-94a6-13971b3b21dc.png)

- [ ] 8. Add an SSH key, the length limit for the Name is better to be set in the front end. the SSH-Key label overlaps the content in the textbox. - `Will keep tracking it`
![image](https://user-images.githubusercontent.com/57614736/91437529-9c1e6000-e89c-11ea-87aa-320b5e35ac89.png)

**Comment by WuJun2016** [comment]
case 8, (the SSH-Key label overlaps the content in the textbox waiting for refactoring to repair)

**Comment by DoNotSayYes** [comment]
Validated except case 8
