### ISSUE TITLE
[BUG] When the cluster consists of 2 nodes, the virtual machine of the slave node does not work properly.

### ISSUE THREAD

**Issue by devadapter** [harvester/harvester#867]
**Describe the bug**

**To Reproduce**
1. Install Harvester with two nodes.
2. Create multiple virtual machines
3. Observe the running state of the slave node virtual machine

**Result**
The virtual machine stops in the startup state and cannot be restarted or stopped. 
Restart the slave node server, the VMs on the node1 server will be migrated to the master node, and the VMs will work normally at this time.

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):
 - Both master and slave nodes are 24-core 64g RAM 1T hard drive servers

**Additional context**
![harvester](https://user-images.githubusercontent.com/23102962/118251216-db97e580-b4d9-11eb-9556-3809d018344a.gif)

**Comment by gitlawr** [comment]
Can you provide a support bundle? You can generate it at the UI bottom.

**Comment by devadapter** [comment]
**Support bundle**
[harvester-supportbundle_e353bddd-443a-44ed-86f8-ecdc990f1f2a_2021-05-17T01-14-30Z.zip](https://github.com/harvester/harvester/files/6490451/harvester-supportbundle_e353bddd-443a-44ed-86f8-ecdc990f1f2a_2021-05-17T01-14-30Z.zip)

**Comment by gitlawr** [comment]
The disk could be faulty based on the events and dmesg logs:
```
# event from VirtualMachineInstance nfs-server
Reason: IOerror,  message: VM Paused due to IO error at the volume: rootdisk
```
```
# dmesg.log
[  803.333334] sd 10:0:0:1: [sde] tag#52 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE
[  803.333342] sd 10:0:0:1: [sde] tag#52 Sense Key : Medium Error [current] 
[  803.333344] sd 10:0:0:1: [sde] tag#52 Add. Sense: Unrecovered read error
[  803.333348] sd 10:0:0:1: [sde] tag#52 CDB: Read(10) 28 00 1a df e8 fd 00 0a 00 00
[  803.333351] blk_update_request: critical medium error, dev sde, sector 450881789 op 0x0:(READ) flags 0x4000 phys_seg 320 prio class 0
```

Can you run the following command to check and fix it if that's the case?
```
sudo badblocks -sv -o badsectors.txt <path-to-the-device>
```

**Comment by devadapter** [comment]
I tried to run the command you said, but the result seems fine. How should I fix it.

![image](https://user-images.githubusercontent.com/23102962/118448659-dc708780-b724-11eb-9da1-33127a58cd94.png)

**Comment by gitlawr** [comment]
If you check the `dmesg` logs, the errors are from other devices including `sdd/sde/sdg...`. Can you check those?

**Comment by devadapter** [comment]
I tried to change the Harvester cluster from one master and two slaves to three independent Harvester. now the Harvester is running VMs perfectly without problems.

**Comment by guangbochen** [comment]
close in favor of https://github.com/harvester/harvester/issues/867#issuecomment-844623536
