### ISSUE TITLE
[BUG] longhorn storage replica

### ISSUE THREAD

**Issue by chifu1234** [harvester/harvester#868]
Currently Harvester sets hardcoded to 3 the amount of replicas. It should use the default setting from longhorn.

**Comment by larssb** [comment]
@chifu1234 where's is this hardcoded?

**Comment by guangbochen** [comment]
the default value is 3 and it has not been hard-coded on the Harvester side, so u should be able to change it accordingly from the Longhorn UI or using `kubectl`.

**Comment by larssb** [comment]
Great stuff then I guess we can close this - right @chifu1234
