### ISSUE TITLE
mount: /run/k3os/iso: wrong fs type, bad option, bad superblock on .... missing codepage .... 

### ISSUE THREAD

**Issue by larssb** [harvester/harvester#869]
**Describe the bug**
When executing an ISO install of Harvester v0.2.0 on a HP ProLiant G9 server over iLO, I get the error seen on the below screenshot and in the title of this issue.

<img width="1440" alt="Screenshot 2021-05-07 at 12 32 09" src="https://user-images.githubusercontent.com/5261530/118270605-93b89480-b4c0-11eb-91d7-a6d45206e21c.png">

**To Reproduce**
1. Login to the iLO webinterface of the HP server
2. Attach the ISO, a locally downloaded ISO, to the server
3. When the server is booting up select to boot from the virtual cd-rom
4. go through the install ....

then already when Harvester is preparing the installation wizard steps, right before the initial install wizard page - where one states the server-name and so forth, errors referring to `bad superblock or fs type` can be seen.

Then if one continue, the error is seen again and blocks the installation from continuing after the entire installation wizard has been run through. And `===Installing Harvester====` is running. 

**Expected behavior**
It can be fixed/worked around by entering the grub menu by hitting `e` and then adding `rescue` to the menu. When arriving at the rescue shell one can delete any potential partitions already present on the disk restart the installation and it works.

**Environment:**
 - Harvester ISO version: The official v0.2.0 release
 - Barae-metal installation
 - HP ProLiant G9 server

**Additional context**
It's my impression that this could be caused by Harvester not being able to successfully wiping any previous partitions on the disk one wants to install Harvester on.

**Comment by gitlawr** [comment]
The error message looks similar to https://github.com/rancher/k3os/issues/488 which happens to be a K3OS issue from you. Are they possibly related?

Inferring from the code, this is probably in https://github.com/harvester/harvester-installer/blob/deb8bd1eec15dfcd22163e59063b5d33b33d8ec9/k3os/install.sh#L254-L264 where it failed to get the ISO_DEVICE then failed the follow-up mounts.

**Comment by lin1005q** [comment]
Is there any progress?

**Comment by gitlawr** [comment]
@lin1005q Did you hit the same issue? Can you describe your setup/steps?

**Comment by lin1005q** [comment]
1. download iso (https://releases.rancher.com/harvester/v0.2.0/harvester-amd64.iso)
2. Copy the file to the USB flash drive.
3. The USB has installed [ventoy](https://github.com/ventoy)
4. Turn on the computer
5. same error

**Comment by gitlawr** [comment]
@lin1005q 
The way of burning the USB stick matters. Users had reported that some of the ways like the `etcher` tool not working.

Does it work if you prepare the USB drive with
- `dd` if you use Linux/macOS
- `rufus` in DD mode if you use Windows

For more background infos: https://github.com/pbatard/rufus/wiki/FAQ#why-doesnt-rufus-recommend-dd-mode-over-iso-mode-for-isohybrid-images-surely-dd-is-better

(We probably need to add the information to the FAQ docs and investigate how we can improve the compatibility in further releases if that's the case.)

**Comment by guangbochen** [comment]
close due to inactivity, also we have replaced the k3os with the newOS in our installer, please verify it using https://releases.rancher.com/harvester/master/harvester-amd64.iso and feel free to open a new issue if any similar issue was encountered.
