### ISSUE TITLE
VM list page issues

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#87]
- [x] 1. Choose one of the active VM -> Edit as form, values missing on the edit page, e.g., there is no source image selected when editing a VM - `SSH keys are still not selected, I'd like to track it in a separate issue`
![image](https://user-images.githubusercontent.com/57614736/91534445-21a91b00-e944-11ea-8c6d-407d6b08b315.png)

- [x] 2. The status in the list is inconsistent with the status on the detail page - `Status has been removed from the detail page`
![image](https://user-images.githubusercontent.com/57614736/91537222-8a929200-e948-11ea-9815-4f5a24c640d6.png)
![image](https://user-images.githubusercontent.com/57614736/91537190-7e0e3980-e948-11ea-81ef-6ef1d505543c.png)

- [x] 3. Cannot sort by clicking State, after clicking State, users are no longer able to manipulate the list - `Validated`
![image](https://user-images.githubusercontent.com/57614736/91537917-9d599680-e949-11ea-9dc3-2631485f282b.png)

- [x] 4. When stopping or restarting a VM, Node and Address info do not refresh instantly, e.g, stop a VM, its Node and Address are still presenting - `Validated`
![image](https://user-images.githubusercontent.com/57614736/91539997-c596c480-e94c-11ea-91a4-8e21b53d159d.png)

- [ ] 5. The open console does not work - Validated

- [x] 6. Backward or forward the page, the menu bar will not close if it has been open - Validated
![image](https://user-images.githubusercontent.com/57614736/91554840-765b8e80-e962-11ea-8142-f245ed90988d.png)

- [x] 7. The error state overlaps the VM name on the list - Validated
![image](https://user-images.githubusercontent.com/57614736/91810010-b1f6a100-ec5f-11ea-993a-c9ed819b1470.png)

**Comment by WuJun2016** [comment]
case 5, delete open conosle action

**Comment by DoNotSayYes** [comment]
Validated
