### ISSUE TITLE
[BUG] unable open pxe installation docs from README 

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#870]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/118427374-9ce37480-b6ff-11eb-9a94-d85b6d90d1d6.png)
![image](https://user-images.githubusercontent.com/15064560/118427507-f0ee5900-b6ff-11eb-8d46-459e7b1396be.png)

**To Reproduce**
1. README
2. click `Overview` -> `PXE/iPXE boot support`

**Expected behavior**

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by noahgildersleeve** [comment]
Tested on github page in Chrome on MacOS. Link correctly redirected to https://docs.harvesterhci.io/v0.2/install/pxe-boot-install/
