### ISSUE TITLE
[BUG] ejected CD-rom can't not be delete from the volumes page

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#871]
**Describe the bug**
![image](https://user-images.githubusercontent.com/4569037/118460372-370ee100-b72f-11eb-89fd-db8ce5b6e329.png)

**To Reproduce**
1. create a VM using an ISO image
2. after the installation is complete, select to eject the cd-rom disk
3. the disk is ejected and the VM is rebooted
4. go to the volumes page, select to delete the cd-rom disk
5. it shows unable to delete because of owner reference

**Expected behavior**
1. should allow the user to delete those ejected cd-roms
2. allow the user to delete those cd-rom disks directly from the ejection

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal

**Comment by noahgildersleeve** [comment]
Tested in build `master-3b6b8a6d-head`.

1. Created new VM from ISO template with ISO https://releases.ubuntu.com/20.04.2/ubuntu-20.04.2-live-server-amd64.iso
2. Installed Ubuntu server
3. Ejected CDROM after install
4. Waited for machine to reboot and log in
5. Checked health of VM
6. Deleted volume for CDROM (virtio-container-disk)
7. Waited for machine to reboot
8. Logged into VM
9. Verified that login worked
10. Verified that volume was removed in config on harvester
