### ISSUE TITLE
[BUG] Unable to login if no Rancher installed

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#873]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/118603553-a1368d00-b7e6-11eb-85a1-115314874673.png)

**To Reproduce**
1. install harvester by charts
2. try to login

**Expected behavior**

show login page

**Support bundle**

**Environment:**
 - Harvester ISO version:  on ISO, dev mode
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
Before the UI is fixed, we can manually change the settings `ui-Index` 's value to `https://releases.rancher.com/harvester-ui/v0.2.1/index.html` by kubectl

**Comment by juadk** [comment]
Tested successfully in build `master-8cfc827f-head` ​with dev-mod.
I can log in without Rancher installed.
![image](https://user-images.githubusercontent.com/6025636/120979054-78663f80-c775-11eb-9055-dd8692c1114f.png)
