### ISSUE TITLE
notready

### ISSUE THREAD

**Issue by mygitdds** [harvester/harvester#875]
Restart after installing havester prompt notready
The web page can be accessed normally, but when the image is added, the image will not be downloaded

**Comment by larssb** [comment]
Use the Harvester channel on the RancherLabs Slack community for this type of questions. It's way faster.

Also you created two issues that are basically the same.

**Comment by guangbochen** [comment]
can u please share the error message of the image that was not able to be downloaded.
Also would be nice if u can specify your setup environment and sharing a supported bundle file that can be generated through the UI, thanks.

**Comment by guangbochen** [comment]
close due to inactivity, also feel free to reopen it if u encounter a similar issue in the https://github.com/harvester/harvester/releases/tag/v0.3.0 release, thanks.
