### ISSUE TITLE
 [Question] startharvester

### ISSUE THREAD

**Issue by mygitdds** [harvester/harvester#876]
This is the reason why notready? Is displayed in harvester?

**Comment by larssb** [comment]
I would certainly go to the Harvester channel on the RancherLabs Slack community for this type of question.

**Comment by guangbochen** [comment]
close due to inactivity, also feel free to reopen it if u encounter a similar issue in the https://github.com/harvester/harvester/releases/tag/v0.3.0 release, thanks.
