### ISSUE TITLE
[BUG] No Create VM using YAML Button in Harvester UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#878]
**Describe the bug**

The Create vm using Yaml file button is not available on the Harvester GUI.
**To Reproduce**
1. Navigate to Virtual Machine list
2. Look for Create 

**Expected behavior**

There should be an option for creating a VM from YAML, this was confirmed by @guangbochen . 

**Support bundle**

**Environment:**
 - Harvester ISO version: version: 0.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL360G9 cluster with 3 nodes

**Additional context**
I'm not sure where the UI is supposed to have that option.
![118692113-96680200-b7be-11eb-8873-03c7b02c8305](https://user-images.githubusercontent.com/83787952/120042479-021c4d00-bfbf-11eb-8295-619ae532b9e8.jpg)

**Comment by guangbochen** [comment]
For the 0.3+ version, there is no `Create from YAML` button for all pages, so let's just align the UX.

**Comment by yasker** [comment]
Close as won't fix.
