### ISSUE TITLE
[Enhancement] Support volume expansion

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#879]
**Describe the bug**

Can't edit volume size
**To Reproduce**
1. Open detached volume via volume list in harvester
2. Edit volume
3. Try to change size
4. Try to change size via YAML and save
**Expected behavior**

You should be able to edit size on a detached volume since that is a supported action in Longhorn
**Support bundle**

[harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-18T18-24-41Z.zip](https://github.com/harvester/harvester/files/6503480/harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-18T18-24-41Z.zip)

**Environment:**
 - Harvester ISO version: v0.2.0-rc5
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL360G9 cluster with 3 nodes

**Additional context**
You get an error when trying to edit an attached volume, but on an unattached volume it silently fails and the button says error, but without outputting any error text
![edit-volume](https://user-images.githubusercontent.com/83787952/118704318-d681b180-b7cb-11eb-8c2a-96788a681ee0.gif)

**Comment by WuJun2016** [comment]
@ngildersleeveSUSE   Volume size editing is not supported after volume is created

**Comment by guangbochen** [comment]
Longhorn can support volume resize but only when the volume is detached, therefore we should allow the user to do a volume expansion when the VM is off.

Additionally will need to address the validation issue from the kubevirt CDI:
```
error: datavolumes.cdi.kubevirt.io "ub1-disk-0-zypoe" could not be patched: admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Cannot update DataVolume Spec
```

**Comment by weihanglo** [comment]
Unfortunately, [`datavolume.spec` is frozen after creation][1] (except multistage import). 
[The documentations of DataVolume][2] also points out this property:

> Once the process is completed, the DV will be in a **consistent state** that allow consumers to make certain assumptions about the DV in order to progress their own orchestration.

Although we can modify the underlying size of PersistentVolumeClaim to trigger an expansion, the DataVolume owning the PVC  won't reflect the change, so it is not a good way when dealing with this feature.

There are one solution I can think of now: Create a new data volume and sourcing from the original PVC, then change volumes in VirtualMachine correspondingly. 

IIRC this solution includes the process of [volume smart-cloning], which under the hood create CSI snapshot. This may be a problem since Harvester uses Longhorn to help CSI-snapsshot, and we will need longhorn/longhorn#2534 to implement. Also mind that for this solution, `vm.spec.dataVolumeTemplates.spec.source` might be inconsistent if the original datavolume was sourced from a `blank` image, but we try to use a new datavolume sourced from a PVC. This may not be a real problem, just note it here as reference.

[volume smart-cloning]: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/smart-clone.md
[1]: https://git.io/JcHtL
[2]: https://git.io/Jc9jU

**Comment by gitlawr** [comment]
What if we don't use datavolume and use PVC directly?

**Comment by weihanglo** [comment]
What do you mean by "use PVC directly"? Creating a vm without DV or editing PVC's size directly? For the former, it needs to change a certain amount of code, including Web UI. For the latter it will cause size inconsistency between DataVolume and PVC,  namely the difference between `dv.spec.pvc.resource.requests.storage` and `pvc.spec.resource.requests.storage`.

**Comment by guangbochen** [comment]
> What if we don't use datavolume and use PVC directly?

It will definitely work, but meanwhile, we are losing the capability of some nice features from CDI like [importing VMWare image to the Harvester](https://github.com/kubevirt/containerized-data-importer/blob/c963ebb276024c4e5041a194c126b3589d43f4fb/doc/datavolumes.md#vddk-data-volume), let's discuss this on the next syn-up and the other solution is to fix it on the upstream CDI to support volume expansion when the VM is stopped, as the volume resize is also supported of the AWS ec2 instance.

**Comment by weihanglo** [comment]
Probably related: https://github.com/kubevirt/containerized-data-importer/issues/1689.

There is also an online resizing PR against KubeVirt. Not directly related but we can keep an eye on it. https://github.com/kubevirt/kubevirt/pull/5981

**Comment by weihanglo** [comment]
Related: https://github.com/kubevirt/containerized-data-importer/issues/1858

**Comment by guangbochen** [comment]
Since we have replaced [DV with PVC](https://github.com/harvester/harvester/pull/1066), now the volume expansion will be supported automatically. 
Additionally, the `in-use` PVC's VM must be off if the user wants to resize those VM volumes.

**Comment by johnliu55tw** [comment]
## Test info
- Verified Harvester version: v0.3.0-rc1

## Test cases and results
- Change volume size using Config
  - Expand volume when VM is Off should succeed - PASS
  - Expand volume which has been expanded before when VM is Off should succeed - PASS
  - Expand volume when VM is On should not be allowed - PASS
  - Shrink volume when VM is Off should not be allowed - PASS
  - Shrink volume when VM is On should not be allowed - PASS
- Change volume size using YAML
  - Expand volume when VM is Off should succeed - PASS
  - Expand volume when VM is On should not be allowed - PASS
  - Expand volume which has been expanded before when VM is Off should succeed - PASS
  - Shrink volume when VM is Off should not be allowed - PASS
  - Shrink volume when VM is On should not be allowed - PASS

- Expand volume size to which exceed the system limit - **FAIL**

## Comments
### Expand volume size to which exceed the system limit failed silently
When I was trying to expand the volume size from 10G to 30G, Harvester didn't show any error message. After I log into the VM and check the size of the disk, I noticed that the size of the disk is not expanded. Create a bug to track this issue: https://github.com/harvester/harvester/issues/1346.

### Volume status shows "In-use" even when the VM is off
After stopping the VM, go to "Volumes" page and its volume still shows "In-use". Not sure whether this is by-design @yasker
![image](https://user-images.githubusercontent.com/5047724/135849001-b412f33e-3902-4a0b-8239-e7ab3ebf4731.png)
![image](https://user-images.githubusercontent.com/5047724/135849025-ab1c8ecb-db39-481e-a59b-dc4f659b5847.png)

**Comment by yasker** [comment]
@johnliu55tw `in use` means the volume is still associated with a VM, so it's expected.

Regarding expansion beyond supported, there is a Longhorn issue that was recently fixed. https://github.com/longhorn/longhorn/issues/2962 . We should carry the error information to the Harvester UI as well in the next release.

**Comment by johnliu55tw** [comment]
Close this ticket because it's work as expected and corner case is tracked by a bug.
