### ISSUE TITLE
[FEATURE] Ability to use extenal Rancher to provide /v3 API

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#883]
**Is your feature request related to a problem? Please describe.**

Rancher integrates multiple authentication methods and RBAC.
Harvester deployed through Chart should also be able to reuse this part of the capability by connecting to an external Rancher.

**Describe the solution you'd like**

Access Rancher by configuring KUBECONFIG for the external Rancher `local` cluster

**Describe alternatives you've considered**

**Additional context**

**Comment by futuretea** [comment]
test plan:
1. Prepare a k8s cluster and a external Rancher server
2. Import this k8s cluster to Rancher server
3. Save `extranal Rancher's kubeconfig` to a local file ( filename must be kubernetes.kubeconfig)
4. Create secret in the k8s cluster:
  ```bash
  kubectl create ns harvester-system
  kubectl -n harvester-system create secret generic rancher-kubeconfig --from-file=kubernetes.kubeconfig
  ```
5. Use `--set containers.apiserver.authMode="rancher" ` and  `--set rancherURL="rancher server URL"`  during helm install
eg:
  ```bash
  helm install harvester deploy/charts/harvester -n harvester-system \
      --set multus.enabled="true" \
      --set multus.hostPath.cniConfDir=/etc/cni/net.d \
          --set multus.hostPath.cniBinDir=/opt/cni/bin \
          --set multus.args={"--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"} \
      --set longhorn.defaultSettings.taintToleration="kubevirt.io/drain:NoSchedule" \
      --set service.harvester.type="NodePort" \
      --set service.harvester.httpsNodePort="30443" \
      --set containers.apiserver.authMode="rancher" \
      --set rancherURL="https://192.168.0.81:30443"
  ```
6. Try to log in harvester

**Comment by noahgildersleeve** [comment]
IsDoest this only require testing internal rancher authentication, or any of the new auth types going into `v0.3.0`?

**Comment by noahgildersleeve** [comment]
I tried to get this running, but the harvester nodes keep crash looping. I'm getting this error in the logs on the pod. 
```
time="2021-06-09T21:49:51Z" level=info msg="Starting controller"
time="2021-06-09T21:49:51Z" level=fatal msg="failed to create harvester server: invalid configuration: no configuration has been provided, try setting KUBERNETES_MASTER environment variable"
```

**Comment by noahgildersleeve** [comment]
I tried this with a multi-node RKE cluster before, but to simplify it I went with was the setup.

- 1 RKE Node (Etcd, worker, and controlplane) (16gb RAM, 6cpu)
- Rancher HA setup with 3 nodes

**Comment by guangbochen** [comment]
that could be the `configmap` that u have created via `kubectl -n harvester-system create secret generic rancher-kubeconfig --from-file=kubernetes.kubeconfig` either not contains the correct path or the file is invalid. Will ask the dev to verify this issue, thanks.

**Comment by TangStone** [comment]
> test plan:
> 
> 1. Prepare a k8s cluster and a external Rancher server
> 2. Import this k8s cluster to Rancher server
> 3. Save `extranal Rancher's kubeconfig` to a local file ( filename must be kubernetes.kubeconfig)
> 4. Create secret in the k8s cluster:
> 
> ```shell
> kubectl create ns harvester-system
> kubectl -n harvester-system create secret generic rancher-kubeconfig --from-file=kubernetes.kubeconfig
> ```
> 
> 1. Use `--set containers.apiserver.authMode="rancher" ` and  `--set rancherURL="rancher server URL"`  during helm install
>    eg:
> 
> ```shell
> helm install harvester deploy/charts/harvester -n harvester-system \
>     --set multus.enabled="true" \
>     --set multus.hostPath.cniConfDir=/etc/cni/net.d \
>         --set multus.hostPath.cniBinDir=/opt/cni/bin \
>         --set multus.args={"--multus-kubeconfig-file-host=/etc/cni/net.d/multus.d/multus.kubeconfig"} \
>     --set longhorn.defaultSettings.taintToleration="kubevirt.io/drain:NoSchedule" \
>     --set service.harvester.type="NodePort" \
>     --set service.harvester.httpsNodePort="30443" \
>     --set containers.apiserver.authMode="rancher" \
>     --set rancherURL="https://192.168.0.81:30443"
> ```
> 
> 1. Try to log in harvester

1. Before logging into harvester, you need to import the harvester cluster to rancher
2. Verify harvester version **master-158a35d3-head**，rancher:2.4.8 and rancher:2.4.7
3. The following figure shows the harvester and rancher local deployment based on rke k8s distribution and hardware configuration
![image](https://user-images.githubusercontent.com/15829074/122961066-a030e680-d3b6-11eb-8894-ec677d8c8f30.png)
4. Create users user1 and user2 in the rancher and give them the roles of cluster owner and project owner respectively under the harvester cluster
5. In the login page of harvester ui, use admin, user1, user2 to login respectively
- Login successfully
- Create vm successfully respectively
- Function module verification after login

Features/Users | admin | user1 | user2 
---|--- |--- |---
Dashboard | yes | yes | x
Host | yes | yes | x
Projects/Namespaces | yes | yes | x
Virtual Machines | yes | yes | yes
Volumes | yes | yes | yes
Images | yes | yes | yes
Users&Authentication | yes | yes | x
Advanced | yes | yes | yes
Templates | yes | yes | yes
Backups | yes | yes | yes
Networks | yes | yes | yes
SSH Keys | yes | yes | yes
Cloud Config Templates | yes | yes | yes
Settings | yes | yes | x
