### ISSUE TITLE
[BUG] Can not select empty Boot order

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#884]
**Describe the bug**

Boot order can not be a string.

![image](https://user-images.githubusercontent.com/7421463/118913059-57bb7e80-b95b-11eb-9ad0-3fbedaf8cc9c.png)

**To Reproduce**
1. Go to Virtual Machines and create a new VM
2. Go to Volumes, select "-" on the BootOrder box

**Expected behavior**

Support to select empty boot order

**Support bundle**

None

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by WuJun2016** [comment]
close:  Now we change the bootorder by dragging and dropping

https://github.com/harvester/dashboard/pull/67
