### ISSUE TITLE
[FEATURE] ceph support

### ISSUE THREAD

**Issue by showsmall** [harvester/harvester#888]
Very much looking forward to supporting ceph.

**Comment by wjimenez5271** [comment]
@showsmall Could you elaborate on your interest in CEPH support? Are there specific features you need that aren't in the existing storage layer of Harvester?

**Comment by showsmall** [comment]
I hope to support distributed storage, so that the virtual machine is safe and reliable, and in this way can support online migration.

**Comment by davidspek** [comment]
Ceph would enable native object storage support, something which Longhorn can’t provide.

**Comment by showsmall** [comment]
I file di dischi di macchine virtuali possono essere memorizzati in CEPH?

**Comment by yasker** [comment]
Hi, we don't have a plan to support Ceph in Harvester. It doesn't fit in the stack SUSE/Rancher can provide.

On the other hand, features like S3 support are coming to Longhorn. See https://github.com/longhorn/longhorn/wiki/Roadmap#longhorn-v14 for details.

**Comment by voarsh2** [comment]
> Hi, we don't have a plan to support Ceph in Harvester. It doesn't fit in the stack SUSE/Rancher can provide.
> 
> On the other hand, features like S3 support are coming to Longhorn. See https://github.com/longhorn/longhorn/wiki/Roadmap#longhorn-v14 for details.

Well, that's a shame. Longhorn is not fit for purpose, after trialling for over 6 months....... SUSE needs to realise that Longhorn isn't good enough. Talk about VENDOR lock-in. I don't want anything to do with Longhorn.

**Comment by Martin-Weiss** [comment]
@voarsh2  - could you share details on what exactly you are missing in Longhorn that you must have? What is "not good enough"? Thanks!!

**Comment by freezxp** [comment]
> @voarsh2 - could you share details on what exactly you are missing in Longhorn that you must have? What is "not good enough"? Thanks!!

I believe its the performance, just tested the Harvester, the iops is really slow, about 20-30% of the native disk IOPS.

**Comment by poelzi** [comment]
I really like the harvest concept, but the fixation on longhorn is u bummer. ceph-rook has so much more to provide, like cephfs

**Comment by Martin-Weiss** [comment]
Did not try - but I believe you should be able to deploy rook-ceph on top of Harvester 1.2.0 and use that storage classes for everything that is not the OS image..
