### ISSUE TITLE
VM detail page issues

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#89]
### Virtual Machine Detail
- [x] 1. There is no label to remove, the remove button is not necessary, the close and the save button are in Chinese, click the save button, the popup does not close
![image](https://user-images.githubusercontent.com/57614736/91556841-fafbdc00-e965-11ea-8269-dcddbefa0b25.png)

- [x] 2. Add a label and then remove it, but the removed label will be recovered when clicking the save button, which means it has not been deleted

- [x] 3. Unable to add more than one label, add a new one and it will be erased automatically

- [x] 4. The IP Address copy tooltip's background is transparent that makes the texts overlap 
![image](https://user-images.githubusercontent.com/57614736/91674804-bb531100-eb6c-11ea-84a6-435dd58645ed.png)
![image](https://user-images.githubusercontent.com/57614736/91675142-dd00c800-eb6d-11ea-9926-ebb583bd933a.png)

**Comment by DaiYuzeng** [comment]
- [x]  1. There is no label to remove, the remove button is not necessary, the close and the save button are in Chinese, click the save button, the popup does not close
- [x]  2. Add a label and then remove it, but the removed label will be recovered when clicking the save button, which means it has not been deleted
- [x]  3. Unable to add more than one label, add a new one and it will be erased automatically
- [x]  4. The IP Address copy tooltip's background is transparent that makes the texts overlap

**Comment by guangbochen** [comment]
@DaiYuzeng for the second issue, the user is still not able to remove the last label or annotation since u didn't send an empty array of string to the API.

**Comment by DaiYuzeng** [comment]
> @DaiYuzeng for the second issue, the user is still not able to remove the last label or annotation since u didn't send an empty array of string to the API.

Oh! Maybe i forgot to reset the bound object value,  I will fix it tomorrow! Thanks for your advice!

**Comment by DoNotSayYes** [comment]
Validated
