### ISSUE TITLE
[FEATURE] Complete documentation for the REST APIs.

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#890]
**Is your feature request related to a problem? Please describe.**
We are developing end-to-end (functional) test suites for Harvester, using public REST APIs. Currently the APIs are sparingly documented here https://github.com/harvester/harvester/wiki/Harvester-API-Test. While that's a good start, but we would like it to be more detail and complete.

**Describe the solution you'd like**
Complete REST API documentation in Swagger or Sphinx style format.

**Describe alternatives you've considered**
We are trying to read the client code (https://github.com/harvester/go-harvester/tree/main/pkg) to figure out the APIs. But that's a rather slow and painful process as we are not proficient in GO.

**Additional context**

**Comment by yasker** [comment]
Ideally, we can publish the API reference as a website. In the future, we can see if we're able to get it automatically built and updated.

**Comment by gitlawr** [comment]
Available at https://docs.harvesterhci.io/v0.2/reference/api/

**Comment by juadk** [comment]
The API is well described at https://docs.harvesterhci.io/v0.2/reference/api/
I haven't had a chance to use it yet. @guangyee is it ok for you?

**Comment by guangyee** [comment]
It's a good start. Though I only used a few APIs so far. There are two areas I think we can do better.

1. distinguish the `required` versus `optional` attributes in the request body. There are some optional attributes that are not needed in the request. For example, to create an image (`/apis/harvesterhci.io/v1beta1/namespaces/{namespace:[a-z0-9][a-z0-9\-]*}/virtualmachineimages`),  all I need is something like this in the request. `{'apiVersion': harvester_api_version,
                  'kind': 'VirtualMachineImage',
                  'metadata': {'name': 'my_image'},
                  'spec': {'displayName': 'My Image',
                           'url': image_url}}
`, the rest seem optional. And for the optional attributes, what are their default values.
2. provide cURL style examples if possible

**Comment by gitlawr** [comment]
1. With the follow-up PR, you should be able to check required fields in the model
![image](https://user-images.githubusercontent.com/5697937/121329359-b9ae4900-c947-11eb-8d27-e781c2b29364.png)

2. If you click `Try it out` then `execute`, the swagger ui will provide the curl style example for the request. If that's convenient, I think we can keep the `Try it out` stuff for now.

**Comment by guangbochen** [comment]
Updated by https://github.com/harvester/harvester/pull/941

**Comment by juadk** [comment]
We can see which fields are required:

![image](https://user-images.githubusercontent.com/6025636/122233290-39926100-cebc-11eb-84fa-9f1547c40990.png)

The curl example is also there but I think we can open another issue because the flashy green color is not very readable:
![image](https://user-images.githubusercontent.com/6025636/122233596-7bbba280-cebc-11eb-918e-d80d8d2e99d4.png)

@guangyee WDYT?

**Comment by guangyee** [comment]
Looks good! The "required" indicator is super helpful. That should help API users reduce large amount of clutter/boilerplate stuff in the API requests. Thanks!
