### ISSUE TITLE
[BUG] Creating a VM from ISO fails

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#892]
**Describe the bug**

1. When you try to create a VM from ISO with the ISO template it fails
**To Reproduce**
1. Create a new VM
2. Select ISO template
3. Select an ISO from the dropdown
4. Click Create

**Expected behavior**

It should create and start properly
**Support bundle**

[harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-20T22-40-24Z.zip](https://github.com/harvester/harvester/files/6519094/harvester-supportbundle_046bfe97-0e0e-45e2-b9e2-6ed767e0aa1d_2021-05-20T22-40-24Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal DL360G9

**Additional context**
![Greenshot 2021-05-20 15 39 17](https://user-images.githubusercontent.com/83787952/119058692-b399fd80-b983-11eb-9b36-43cb4dc72b0d.png)
![Greenshot 2021-05-20 15 39 30](https://user-images.githubusercontent.com/83787952/119058697-b4329400-b983-11eb-9277-5b5ea0c7e584.png)
![Greenshot 2021-05-20 15 39 53](https://user-images.githubusercontent.com/83787952/119058700-b4cb2a80-b983-11eb-96dc-f51b3436c4de.png)
![Greenshot 2021-05-20 15 40 03](https://user-images.githubusercontent.com/83787952/119058701-b563c100-b983-11eb-8b82-6cf03af4f656.png)

**Comment by gitlawr** [comment]
The migratable param is missing in the longhorn storage class. Possibly related to https://github.com/harvester/harvester/issues/857

This can be fixed by running the following and add `migratable: "true"` to the params.
```
kubectl edit cm -n longhorn-system longhorn-storageclass
```

**Comment by noahgildersleeve** [comment]
This might have been resolved with the fixes from https://github.com/harvester/harvester/issues/857 .

**Comment by noahgildersleeve** [comment]
Tested in version `master-3b6b8a6d-head`

1. Created VM with ISO template 2 vCPU and 4GB of RAM
2. Set image as  https://download.fedoraproject.org/pub/fedora/linux/releases/34/Server/x86_64/iso/Fedora-Server-netinst-x86_64-34-1.2.iso . It installed and passed VM health checks.
3. Installed with defaults
4. Rebooted
5. Ran ping test to google and verified read/write operations. All health checks passed.
