### ISSUE TITLE
[FEATURE] better way to handle admin password on the first login

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#893]
**Is your feature request related to a problem? Please describe.**
Accessing the UI for the first time, right after PXE booting up the ISO, I was prompted to set the `admin` user password. I presume this is the local admin user? Is there a way to avoid setting the admin password manually via the UI? We are trying to automate Harvester end-to-end testing and there should not be any manual steps in between. Furthermore, allowing anyone with the UI URL to set the admin password on first login could be a security concern.

**Describe the solution you'd like**
Ideally, we should be allowed to seed the `admin` user password in PXE `config-create.yaml` (https://github.com/harvester/ipxe-examples/blob/main/general/config-create.yaml) and have a policy in place to force password change upon first successful login, all done via REST API.

Otherwise, we could consider allowing a one-time randomly generated API/registration token to be configured in PXE `config-create.yaml` and use that via REST API to reset the admin password. As this is a one time token, it will be invalidate as soon as the admin password is created.

**Describe alternatives you've considered**
We could parse HTML and do form post? But since this is public REST API, HTTP form post is unreliable. Therefore, from automation point-of-view, there isn't a viable alternative right now.

**Additional context**
![harvester_first_login](https://user-images.githubusercontent.com/1808417/119058554-75044300-b983-11eb-8901-9f333e273c32.png)

**Comment by noahgildersleeve** [comment]
Currently the call seems to be https://ipaddress:30443/v3/users?action=changepassword
The payload is `{"currentPassword":"admin","newPassword":"yourNewPassword"}`

**Comment by guangyee** [comment]
> Currently the call seems to be https://ipaddress:30443/v3/users?action=changepassword
> The payload is `{"currentPassword":"admin","newPassword":"yourNewPassword"}`

Where's the "currentPassword" coming from for PXE boot installation?

**Comment by noahgildersleeve** [comment]
It seems that `currentPassword` is just being set to `admin` as a default value on install. I got this by capturing the REST call from dev tools. I think you should be able to just use it for setting the password after the PXE install.

**Comment by guangyee** [comment]
Doesn't seem to work.
`curl -d "{\"currentPassword\": \"admin\", \"newPassword\": \"password\"}" -k https://192.168.121.31:30443/v3/users?action=changepassword
{"type":"error","status":"401","message":"Unauthorized 401: must authenticate"}`

**Comment by futuretea** [comment]
1. after both harvester and rancher are ready
2. login by admin/admin
3. change password

**Comment by guangbochen** [comment]
close as we will just use the default password for now, feel free to reopen it if needed, thanks.
