### ISSUE TITLE
add vm lifecycle action handler

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#9]
**Description:**

Add action handlers to the kubevirt virtual machine object.

- [x] start VM action handler
- [x] stop VM action handler
- [x] restart VM action handler
- [x] pause VM action handler
- [x] unpause VM action handler
~~- [ ] terminate the VM action handler(e.g permanent delete the VM after 2 minutes?) [TBD]~~

**Comment by guangbochen** [comment]
currently, the restart action API is succeeded but not reflecting on the UI as `restarting` status, we should make an enhancement on this.

**Comment by WuJun2016** [comment]
We can't distinguish restart States,  which are similar to creating a new VM  @guangbochen

**Comment by gitlawr** [comment]
I'm moving out the terminate action from the scope. It can be done by deleting the VM.
Verified that I can start/stop/restart/pause/unpause a VM in the UI.
