### ISSUE TITLE
[BUG] Can't edit settings through UI

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#901]
**Describe the bug**

There is no option to edit settings and clicking on the fields doesn't work.
**To Reproduce**
1. Navigate to settings page
2. Try to change rancher enabled from `false` to `true`
**Expected behavior**

You should be able to edit the settings
**Support bundle**

[harvester-supportbundle_e7e376da-3ef6-4216-b9ca-cc85c312de13_2021-05-24T20-31-30Z.zip](https://github.com/harvester/harvester/files/6534840/harvester-supportbundle_e7e376da-3ef6-4216-b9ca-cc85c312de13_2021-05-24T20-31-30Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160G9 

**Additional context**
![cant edit settings](https://user-images.githubusercontent.com/83787952/119404727-0c73d980-bc95-11eb-98f0-16c1ab775803.gif)

**Comment by WuJun2016** [comment]
@guangbochen  @ngildersleeveSUSE  
We have restricted the edit setting function
1. Click on the avatar in the upper right corner to go to Preferences
2. Enable Developer Tool & Features

**Comment by guangbochen** [comment]
Yep, but I think it doesn't make sense to enable the editing of settings through the `developer tool & features` option, can we just enable it by default, thanks.

**Comment by noahgildersleeve** [comment]
Tested in `master-199b3b79-head`. Edit config shows up in settings now without `developer tool & features` being selected in preferences.
