### ISSUE TITLE
[BUG] You can delete raw image that is in use by VM

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#902]
**Describe the bug**

You can delete a raw image that is in use
**To Reproduce**
1. Add a raw image
2. Create a VM using that image
3. Delete that image
**Expected behavior**

You shouldn't be able to delete a raw image that is in use. 
**Support bundle**

[harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-25T21-50-57Z.zip](https://github.com/harvester/harvester/files/6542566/harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-25T21-50-57Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): DL160G9

**Additional context**
When you remove this the dropdown in the config goes to blank. It still seems to work though. It also reboots fine. I"m not sure about desired functionality.
![Greenshot 2021-05-25 14 55 12](https://user-images.githubusercontent.com/83787952/119573665-7067d200-bd69-11eb-9b99-307eda087f0d.png)

**Comment by guangbochen** [comment]
do u mean if the image is currently in use by a VM, the user should not be allowed to delete this image?

**Comment by noahgildersleeve** [comment]
That was my understanding, but I wasn't sure about the desired functionality/how that was being implemented on the backend.

**Comment by gitlawr** [comment]
If the deletion does not affect existing VMs I think it's not necessary to prevent the operation

**Comment by juadk** [comment]
I'm running the tests filled in the images section with the last master branch.
From my point of view, I agree that we can delete an image used by an active VM, it makes sense to me. So, is this issue can be closed though?

**Comment by guangbochen** [comment]
close for now as this is expected behavior.
