### ISSUE TITLE
[BUG] Can't boot from volume created from raw image

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#903]
**Describe the bug**

If you create a volume from a raw image, then create a VM with that volume, it won't boot
**To Reproduce**
1. Create a volume from a raw image
2. Create a VM
3. Add the existing volume to the VM
4. Make the base disk a CDROM
**Expected behavior**

It should boot
**Support bundle**

[harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-25T22-17-20Z.zip](https://github.com/harvester/harvester/files/6542677/harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-25T22-17-20Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL160G9

**Additional context**
![Greenshot 2021-05-25 16 01 29](https://user-images.githubusercontent.com/83787952/119579062-83cb6b00-bd72-11eb-941a-ea43ab94426c.png)
![Greenshot 2021-05-25 15 35 45](https://user-images.githubusercontent.com/83787952/119578996-626a7f00-bd72-11eb-83eb-22ff0738ee72.png)
![Greenshot 2021-05-25 15 35 52](https://user-images.githubusercontent.com/83787952/119579002-64344280-bd72-11eb-806c-cb636f0e4590.png)

**Comment by futuretea** [comment]
Can you provide more details about `Create a volume from a raw image`?
My current steps are:
1. create a vm use raw template 
2. wait this vm Running 
3. delete this vm, but  keep rootdisk volume 

So I've got  a volume from a raw image.

**Comment by guangbochen** [comment]
if is the raw image the disk type should be `disk` instead of `CD-ROM`, CD-ROM is just for ISO images.

**Comment by noahgildersleeve** [comment]
The steps were

1. Create a separate disk volume from the raw image
2. Create a VM
3. Because you can't specify existing volume for the root volume I set the main volume as a CDROM with no ISO
4. I attached the existing volume
5. I marked it as boot order one
6. Created the VM

**Comment by guangbochen** [comment]
the process looks good to me, but which raw image are u using for testing, cloud images do not have VNC console support, so u might need to check the serial console.

**Comment by noahgildersleeve** [comment]
I created it with this image http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img . The serial connection was completely empty. It looked like it failed to boot. The output of the VNC connection was that there was no bootable device.

**Comment by noahgildersleeve** [comment]
Exact steps for reproduction on build `master-3b6b8a6d-head`

1. Add http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img to images
2. Create a volume from the volume page
2. Select from VM image
3. Select image
4. Select 10GB as size
5. Create VM
6. Don't use template
7. Select 1 CPU, 2GB RAM
8. Go to volumes
9. Change rootdisk to cdrom and boot order to 2
10. Add existing volume
11. Select volume created before
12. Set boot order to 1
13. Create VM
14. Wait for VM to go to running
15. Open web VNC
It says the hard drive isn't a bootable drive.

**Comment by futuretea** [comment]
![image](https://user-images.githubusercontent.com/15064560/120569369-5b193480-c448-11eb-890c-a582fefdbac6.png)
![image](https://user-images.githubusercontent.com/15064560/120569122-d7f7de80-c447-11eb-8412-8e78c6bf41c0.png)
check  the volume created from vm image, the storageClassName is missing. 
cc @WuJun2016

**Comment by noahgildersleeve** [comment]
If you try to do this you can't create the VM because you are required to put in an image when creating a VM
![image](https://user-images.githubusercontent.com/83787952/130160574-ebcb3808-6e3d-4263-8753-3eace1eb6a8f.png)
@guangbochen said that there might be an existing UI issue about this, but I wasn't able to find it. I'm not sure what the desired functionality would be. We could change the image requirement in the UI, but I imagine that was specifically added.

**Comment by noahgildersleeve** [comment]
tested in `master-c4584348-head`. Verified as fixed.
