### ISSUE TITLE
Port configuration of the VM management network is confusing

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#909]
We can set ports of the management network in the UI.
![image](https://user-images.githubusercontent.com/5697937/119954641-c76fe000-bfd1-11eb-8cb4-1abcaae216a3.png)

1. The usage is not clarified in the documentation and is not clear from the UI.
2. It applies to the management network but not the VLAN networks.

**Describe the solution you'd like**
Revisit to see if we should remove it.

**Additional context**
It works as the following:
By default, all ports of the management network are accessible. 
If users configure a set of ports, only those ports are accessible.

**Comment by noahgildersleeve** [comment]
Tested in master-8afedf0a-head. Port input was removed when adding networks. Closing as fixed.
