### ISSUE TITLE
[BUG] Migration fails when migrating to a host without a longhorn replica set

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#910]
**Describe the bug**

When you migrate a VM to a host that doesn't have a copy of the volume it fails
**To Reproduce**
1. Create a new VM on a 4 node cluster
2. Check which nodes have copies of the replica set
3. Migrate the VM to the host that does not have the volume

**Expected behavior**

You should either be able to migrate the VM, or it shouldn't be an option for migration
**Support bundle**

[harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-28T20-00-02Z.zip](https://github.com/harvester/harvester/files/6563093/harvester-supportbundle_6ed888bc-24da-430c-b562-c44ba23d5b21_2021-05-28T20-00-02Z.zip)

**Environment:**
 - Harvester ISO version: master-c13c2a35-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL160G9

**Additional context**
![Greenshot 2021-05-28 13 01 18](https://user-images.githubusercontent.com/83787952/120036483-0e031180-bfb5-11eb-8bfb-19615ada8a2a.png)
![Greenshot 2021-05-28 13 01 30](https://user-images.githubusercontent.com/83787952/120036485-0e9ba800-bfb5-11eb-9721-7f34b7b4a7a8.png)
![Greenshot_2021-05-28_13_42_02](https://user-images.githubusercontent.com/83787952/120042352-c41f2900-bfbe-11eb-97c0-2207d9116d8b.jpg)

**Comment by gitlawr** [comment]
In my testing the migration to a node with no replica works, so the cause of the failure might be irrelevant to the longhorn replicas.
Can you reproduce and provide the logs from both the source and target launcher pod? Not sure why there's only logs from one test-migrate-5 pod in the support bundle.

**Comment by noahgildersleeve** [comment]
I tested this with build `master-0c3b2844-head` and the migration worked for me too. It must have gotten resolved at some point. I wonder if it was related to the [storage class Longhorn bug](https://github.com/harvester/harvester/issues/857). It seems to be resolved now.

**Comment by guangbochen** [comment]
close in favor of the https://github.com/harvester/harvester/pull/860

> I tested this with build `master-0c3b2844-head` and the migration worked for me too. It must have gotten resolved at some point. I wonder if it was related to the [storage class Longhorn bug](https://github.com/harvester/harvester/issues/857). It seems to be resolved now.
