### ISSUE TITLE
[Question] Is there a node label or taint to so harvester ignores

### ISSUE THREAD

**Issue by brunnels** [harvester/harvester#914]
I don't want harvester doing anything with my master nodes.  Is there a label or taint I can add to them so they won't show up in the harvester UI?

**Comment by guangbochen** [comment]
currently not supported, can u explain a little bit why this feature needs?

**Comment by brunnels** [comment]
I'm running a mixed bare metal cluster.  Masters are all arm with very little storage.  Worker nodes are all amd64.  Many things don't even have arm containers so best to have master/NoSchedule taint.

**Comment by guangbochen** [comment]
is this installed using the helm chart? u can try to run `kubectl taint nodes node1 key=value:NoSchedule` for those master nodes to repel a set of VMs.

**Comment by brunnels** [comment]
Harvester is installed with helm and all nodes are k3os.  All master nodes have taint `node-role.kubernetes.io/master:NoSchedule`.  I needed to remove the tolerations in the harvester helm values for multus and harvester-network-controller.  
```
multus:
  enabled: true
  tolerations: []
harvester-network-controller:
  tolerations: []
```

The node taint doesn't prevent the master nodes from showing in the harvester hosts list and doesn't prevent harvester trying to config the network on the tainted nodes.  There are always a `k3s-master1 Installing network configuration` warnings on the network page.
