### ISSUE TITLE
[FEATURE] Remove Harvester users

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#921]
**Is your feature request related to a problem? Please describe.**
Remove the Harvester user system since we will merge it to use the Rancher users instead.

**Describe the solution you'd like**
Remove the user implementation on the Harvester side, if the Rancher is not set then the Harvester will disable the authentication by default.

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by noahgildersleeve** [comment]
verified as removed in build `master-c4584348-head`.
