### ISSUE TITLE
[FEATURE] Harvester UI refactoring to merge with Rancher dashboard

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#923]
**Is your feature request related to a problem? Please describe.**
Harvester UI refactoring to merge with Rancher dashboard

**Describe the solution you'd like**
Harvester UI refactoring to merge with Rancher dashboard

**Comment by guangbochen** [comment]
Since the [API aggregation](https://github.com/harvester/harvester/issues/922) feature is merged, we should be able to continue the UI integration work using the [master-head](https://releases.rancher.com/harvester/master/harvester-amd64.iso) ISO image. @WuJun2016

**Comment by WuJun2016** [comment]
Merge into dashboard https://github.com/rancher/dashboard/pull/3726.

Close!
