### ISSUE TITLE
[BUG] Harvester should have the individual Storage class with the required parameters rather than depending on the Longhorn SC

### ISSUE THREAD

**Issue by khushboo-rancher** [harvester/harvester#925]
**Describe the bug**
Instead of having ConfigMap for longhorn StorageClass, it's better to have own storage class with `provisioner: driver.longhorn.io` and other required parameters.

**Environment:**
 - Harvester ISO version: v0.2.0

**Additional context**
https://github.com/harvester/harvester/issues/857

**Comment by guangbochen** [comment]
close as this has been addressed via https://github.com/harvester/harvester/issues/857
