### ISSUE TITLE
[BUG] old version of tidwall/gjson has known CVEs that can cause denial of service errors

### ISSUE THREAD

**Issue by vielmetti** [harvester/harvester#926]
**Describe the bug**

Harvester's "go.mod" brings in a version of `github.com/tidwall/gjson` (@v1.6.3) which has several known CVEs that can cause denial of service conditions.

https://github.com/harvester/harvester/blob/5ea5fc3111d1da1d1cef9dd6eb2c5a6c978fc2d5/go.mod#L84

**To Reproduce**
1. Go to https://deps.dev/go/github.com%2Fharvester%2Fharvester/v0.2.0/dependencies?q=gjson
2. Review https://deps.dev/go/github.com%2Ftidwall%2Fgjson/v1.6.3

**Expected behavior**

Harvester should use a version of its dependency that does not have any known issues.

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

Found with https://deps.dev a new tool from Google for auditing open source.

**Comment by ldevulder** [comment]
`go.mod` has been updated, and latest `master` version is installing well from ISO image and in dev-mode.
