### ISSUE TITLE
vm template UI bugs

### ISSUE THREAD

**Issue by aiwantaozi** [harvester/harvester#93]
1. launch vm need to add source when user select image
![image](https://user-images.githubusercontent.com/5936271/91695919-6f6e8f00-eba1-11ea-9cb6-fba2c332a4bf.png)

2. update the text to ```Create template```
![image](https://user-images.githubusercontent.com/5936271/91695980-8319f580-eba1-11ea-9f95-27bb8628ce03.png)

3. support select version when launch from template
![image](https://user-images.githubusercontent.com/5936271/91695298-7fd23a00-eba0-11ea-85fe-301f3298e427.png)

4. no need comment
![image](https://user-images.githubusercontent.com/5936271/91695589-fcfdaf00-eba0-11ea-94ba-092e5bc795dd.png)

**Comment by DoNotSayYes** [comment]
Validated
