### ISSUE TITLE
[BUG] Unable to deploy when non-install disk contains data

### ISSUE THREAD

**Issue by alexdepalex** [harvester/harvester#930]
**Describe the bug**
When deploying Harvester on a node that has a disk next to the installation disk which already contains data, the installation process fails.

**To Reproduce**
Make sure the non-install disk contains a file system. Try to deploy on the install disk.

**Expected behavior**
It shouldn't happen.

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure: PowerEdge R940. Install disk on BOSS adapter. NVMe on PCI bus.

**Additional context:**
The nodes were previously installed with Harvester. The NVMe (/dev/nvme0n1) was formatted with ext4 and used for Longhorn storage.

![rpviewer (33)](https://user-images.githubusercontent.com/713019/120999290-3fd06100-c789-11eb-95de-ae275184df58.png)

**Comment by yasker** [comment]
@alexdepalex This issue seems pretty old and with k3os. Does this still happen with v0.3.0-rc1?

**Comment by yasker** [comment]
Likely a non-issue now. Move to v1.0.0.

**Comment by guangbochen** [comment]
close in favor of v0.3.0 release, feel free to re-open it if needed, thanks.
