### ISSUE TITLE
[FEATURE] Progress indicator for backups

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#933]
**Is your feature request related to a problem? Please describe.**

Currently the backups only show a status indicator, but no progress indicator. For multi-hour backups this can be problematic.
**Describe the solution you'd like**

A progress indicator like we have in Longhorn
**Describe alternatives you've considered**

**Additional context**

Currently this information is available in Longhorn, but not harvester. It makes it hard to tell if a backup is having issues.

**Comment by guangbochen** [comment]
duplicate of https://github.com/harvester/harvester/issues/526
