### ISSUE TITLE
[FEATURE] Support configuring NTP servers during the installation

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#935]
**Is your feature request related to a problem? Please describe.**
We use `ntp.ubuntu.com` as the connman's fallback NTP server, we should allow users to configure it during the installation. Hard-coding a public NTP server might be considered [abuse](https://en.wikipedia.org/wiki/NTP_server_misuse_and_abuse).

**Describe the solution you'd like**

Maybe we can add a panel to configure NTP servers in the installer.

**Describe alternatives you've considered**

Harvester nodes as fallback NTP server.

**Additional context**
- The NTP server is hard-coded at
https://github.com/harvester/harvester-installer/blob/deb8bd1eec15dfcd22163e59063b5d33b33d8ec9/pkg/console/install_panels.go#L52

- For PXE installation, the [user-provided NTP list](https://docs.harvesterhci.io/v0.2/install/harvester-configuration/#osntp_servers) is merged with the hard-coding one.

**Comment by alexdepalex** [comment]
I guess that for air-gapped environments the user provided list should be replacing the default list instead of merged. Furthermore, with the preview build, it doesn't seem like NTP is actually enabled after deployment.
```
n-2:/etc/systemd # timedatectl
               Local time: Mon 2021-09-20 12:31:01 UTC
           Universal time: Mon 2021-09-20 12:31:01 UTC
                 RTC time: Mon 2021-09-20 12:30:54
                Time zone: Etc/UTC (UTC, +0000)
System clock synchronized: no
              NTP service: inactive
          RTC in local TZ: no
```

**Comment by FrankYang0529** [comment]
Hi @alexdepalex, I think we can replace default NTP server by deleting it in input field. Also, we enable `systemd-timesyncd` after reboot.

ref: https://github.com/harvester/harvester-installer/pull/125/files

**Comment by johnliu55tw** [comment]
## To verify NTP sync status
- To verify whether NTP sync is enabled and running: `$ timedatectl`: `System clock synchornized` should be `yes` and `NTP service` should be `active`
- To verify NTP servers: `$ timedatectl show-timesync --all`
- To see time synchronization log: `# journalctl -b -u systemd-timesyncd`
## Test info
- Verified version: v0.3.0-rc1

## Test cases
- Use default NTP server `0.suse.pool.ntp.org`
    - [x] Verify NTP sync service is enabled with default NTP server
- Change NTP server to something else: `time.cloudflare.com`
    - [x] Verify NTP sync service is enabled with specified NTP server
- Add multiple NTP servers: `time.cloudflare.com,time.stdtime.gov.tw`
    - [x] [Installer] Enter NTP servers separated by space? -> Not able to connect
    - [x] Verify NTP sync service is enabled with multiple NTP server
- Add multiple NTP servers, the first does not work: `1.2.3.4,0.suse.pool.ntp.org`
    - [x] [Installer] Warn user the first one is unreachable
    - [x] Verify NTP sync service is enabled with multiple NTP server
    - [x] Time should still be synchronized
- Enter incorrect NTP `1.2.3.4`
    - [x] [Installer] Warning message should be shown to users
    - [x] [Installer] Users could proceed with the installation if they wish to
    - [x] System clock is **not** synchronized
    - [x] NTP server is `1.2.3.4`
- Do not provide any NTP server
    - [x] Delete the NTP server `0.suse.pool.ntp.org` entirely -> NTP service (`systemd-timesyncd`) will not be enabled.
