### ISSUE TITLE
[FEATURE] Multicluster Harvester management

### ISSUE THREAD

**Issue by yasker** [harvester/harvester#938]
When the user has more than one Harvester cluster across different geolocations, it's important to provide a way for the user to manage all those clusters in a central place.

We're working with the Rancher team to use Rancher to manage multiple Harvester clusters from a central Rancher. Also, by utilizing Fleet we can achieve mass deployment and management.

On the Rancher side, it will be mostly UI change instead of backend change.

**Comment by guangbochen** [comment]
please help to verify using the latest rancher v2.6.0 release and the new harvester-installer, u will need to replace the Rancher UI with the customized harvester release: https://releases.rancher.com/harvester-ui/dashboard/latest/index.html.

Verification scope:
- Either install Rancher 2.6.0 via the [docker run](https://rancher.com/docs/rancher/v2.6/en/quick-start-guide/deployment/quickstart-manual-setup/#2-install-rancher) or using your existing Rancher server
- Once the Rancher is ready go to the `global settings` and replace the `ui-dashboard-index` with the above-customized Harvester UI release(Harvester MCM UI is targeting to get merged in Rancher 2.6.1)
- Click the `Virtualization Management` tab and select importing the downstream harvester cluster to the upstream Rancher
- the cluster should be imported and check basic VM related functionalities are working
- delete the imported Harvester cluster and it should be gone from the UI
- re-importing the deleted Harvester cluster and things should just work like before.

Related verification Issues:
https://github.com/harvester/harvester/issues/582 https://github.com/harvester/harvester/issues/552

**Comment by yasker** [comment]
Multi-cluster management feature works with Rancher 2.6.1-rc5 and Harvester v0.3.0-rc1.
