### ISSUE TITLE
[BUG] Harvester v0.2.0 dashboard layout broken on Safari 14.1.1

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#939]
**Describe the bug**
Layout broken on macOS Safari 14.1.1

**To Reproduce**
1. Open harvester dashboard in Safari 14.1.1

**Expected behavior**
 Layout the dashboard correctly

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure: VirtualBox 6.1 on macOS 11.4

**Additional context**

<img width="1518" alt="image" src="https://user-images.githubusercontent.com/14314532/121279048-77b0e300-c906-11eb-9240-bf5645e89ff9.png">

**Comment by weihanglo** [comment]
Haven't check against master branch. Feel free to close if it is already fixed.

**Comment by noahgildersleeve** [comment]
Tested in safari on mac os Version 14.1.1 (16611.2.7.1.4) and harvester version master-07efe71c-head. Verified as fixed.
![image](https://user-images.githubusercontent.com/83787952/125535910-038c067a-4cbe-4a40-9013-6d4267065ed5.png)
