### ISSUE TITLE
[FEATURE] Support generating Terraform files  based on existing harvester infrastructure

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#943]
The current implementation of Terraform import can only import resources into the state. It does not generate configuration
Because of this, prior to running terraform import it is necessary to write manually a resource configuration block for the resource, to which the imported object will be mapped.

So  we need a tool to generates tf/json and tfstate files based on existing infrastructure (reverse Terraform).

**Reference projects**
https://github.com/GoogleCloudPlatform/terraformer

**Comment by futuretea** [comment]
## To Test:
1. Downlaod terraformerfrom releases https://github.com/harvester/terraformer/releases and add it to PATH
```bash
wget https://github.com/harvester/terraformer/releases/download/v0.1.0-harvester/terraformer-harvester-linux-amd64
chmod +x terraformer-harvester-linux-amd64
sudo mv terraformer-harvester-linux-amd64 /usr/local/bin/terraformer
```
2. Use terraformer to generate tf files and tfstates file from existing resources (example: only import image default/image-6skr8 and harvester-public/image-9lspw)
```bash
terraformer import harvester -r image -f image=default/image-6skr8:harvester-public/image-9lspw
```

3. replace provider to registry.terraform.io/harvester/harvester
```bash
cd generated/harvester/image
vim provider.tf (add source  = "registry.terraform.io/harvester/harvester" to terraform.required_providers.harvester)
terraform state replace-provider "registry.terraform.io/-/harvester" "registry.terraform.io/harvester/harvester"

```

4. Use the tf files  and tfstate files to manage the existing resources.
```bash
terraform init
terraform plan ...
terrform apply ...
```

## Supported Resources:
1. clusternetwork
1. network
1. ssh_key
1. image
1. virtualmachine
1. volume

**Comment by guangbochen** [comment]
@futuretea can u please help to update the README with adding the Harvester as a sub-item of `Infrastructure Software` at the [ToC](https://github.com/harvester/terraformer#table-of-contents), thanks

**Comment by futuretea** [comment]
TODO：

- [ ] update README
- [ ] release

**Comment by juadk** [comment]
@futuretea I've started to test it, first I didn't know Terrafomer before today and it looks to be a fantastic tool!
I was able to import my images and I can change the settings for them but I can't delete an image. I removed the image resource from the image.tf but it gave me an error when I tried to plan/apply. Maybe I misunderstand something with the tool.
```
terraform plan

│ Error: Reference to undeclared resource
│ 
│   on outputs.tf line 6, in output "harvester_image_tumbleweed_id":
│    6:   value = "${harvester_image.tumbleweed.id}"
│ 
│ A managed resource "harvester_image" "tumbleweed" has not been declared in the root module.
```
PS:
Forget it, if I understand correctly, the only one way to delete a specific resource is to use something like:
`terraform destroy -target harvester_image.ubuntu-focal`

**Comment by juadk** [comment]
Tested with:
* harvester `master-ada6b573-head`
* terraformer `v0.1.0-harvester`
* terraform-provider-harvester `v.0.1.0`
* terraform `v1.0.3`

Install Terraformer: :heavy_check_mark: 
Export KUBECONFIG env variable with the kubeconfig file path: :heavy_check_mark: 

1. Images test :heavy_check_mark: 
` terraformer import harvester -r image`
```
cd generated/harvester/image
vim provider.tf (add source  = "registry.terraform.io/harvester/harvester" to terraform.required_providers.harvester)
terraform state replace-provider "registry.terraform.io/-/harvester" "registry.terraform.io/harvester/harvester"
```
I successfully altered the following fields: description, display name, name, namespace and url

2. Clusternetwork test :heavy_check_mark: 
`terraformer import harvester -r clusternetwork`
Replace the provider.
I successfully altered the following fields: default_physical_nic, enable

3. Ssh-key test :heavy_check_mark: 
`terraformer import harvester -r ssh_key`
Replace the provider.
I successfully altered the following fields: name, namespace, public_key

4. Network test :heavy_check_mark: 
`terraformer import harvester -r network`
Replace the provider.
I successfully altered the following fields: name, namespace, vlan_id

5. Volume test :heavy_check_mark: 
`terraformer import harvester -r volume`
Replace the provider.
I successfully altered the following fields: name, namespace

6. Virtualmachine test: :heavy_check_mark: 
`terraformer import harvester -r volume`
Replace the provider.
I successfully altered the following fields: cpu, memory
If I change either VM name or namespace, the VM is destroyed and started back but that's well noticied by the terraform output: `Plan: 1 to add, 0 to change, 1 to destroy`
