### ISSUE TITLE
[BUG] restoring from a chained backup with the middle deleted fails

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#945]
**Describe the bug**

When you do a chained backup, delete the middle one and restore to the first it fails.
**To Reproduce**

1. Create a new VM
2. Create a file named 1 and add some data using command dd if=/dev/urandom of=file1.txt count=100 bs=1M
3. Compute md5sum : md5sum-1
4. Create a backup1
5. Overwrite file 1 
6. Create file 2
7. Compute md5sum for file 1 and file 2 : md5sum-2, md5sum-3
8. Create Backup2
9. Overwrite the file 2
10. Create file 3 and compute md5sum for file 2 and file 3 : md5sum-4, md5sum-5
11. Create backup3
12. Delete backup 2
13. Validate file 2 and 3 are the same as they were
14. Restore to backup 1
15. Validate that
      1. file 1 is in original format - md5sum-1
      1. file 2 doesn't exist
      1. file 3 doesn't exist
19. Validate data by restoring other backups also.

**Expected behavior**

Restore should complete successfully.
**Support bundle**

[harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-10T23-15-34Z.zip](https://github.com/harvester/harvester/files/6634903/harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-10T23-15-34Z.zip)

**Environment:**
 - Harvester ISO version: master-3b6b8a6d-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL360G9

**Additional context**
It looks like the volume faulted in longhorn.
![Greenshot 2021-06-10 16 14 49](https://user-images.githubusercontent.com/83787952/121610144-33a70680-ca0a-11eb-8e54-96e40780deba.png)
![Greenshot 2021-06-10 16 15 16](https://user-images.githubusercontent.com/83787952/121610148-34d83380-ca0a-11eb-9926-4ed6df7c4b47.png)

**Comment by guangbochen** [comment]
I was able to restore both the backup1 and backup3(the backup 2 was deleted) by replacing the existing VM operation.

1. restore to backup1
```shell
ubuntu@vm1:~$ ls -la
total 10272
drwxr-xr-x 4 ubuntu ubuntu     4096 Jun 21 08:27 .
drwxr-xr-x 3 root   root       4096 Jun 21 08:23 ..
-rw------- 1 ubuntu ubuntu        0 Jun 21 08:27 .bash_history
-rw-r--r-- 1 ubuntu ubuntu      220 Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu     3771 Feb 25  2020 .bashrc
drwx------ 2 ubuntu ubuntu     4096 Jun 21 08:27 .cache
-rw-r--r-- 1 ubuntu ubuntu      807 Feb 25  2020 .profile
drwx------ 2 ubuntu ubuntu     4096 Jun 21 08:23 .ssh
-rw-rw-r-- 1 ubuntu ubuntu       44 Jun 21 08:27 file1.md5
-rw-rw-r-- 1 ubuntu ubuntu 10485760 Jun 21 08:27 file1.txt
ubuntu@vm1:~$ md5sum -c file1.md5
file1.txt: OK
```
2. restore to backup3
```shell
ubuntu@vm1:~$ ls -la --block-size=M
total 31M
drwxr-xr-x 4 ubuntu ubuntu  1M Jun 21 09:00 .
drwxr-xr-x 3 root   root    1M Jun 21 08:23 ..
-rw------- 1 ubuntu ubuntu  1M Jun 21 08:27 .bash_history
-rw-r--r-- 1 ubuntu ubuntu  1M Feb 25  2020 .bash_logout
-rw-r--r-- 1 ubuntu ubuntu  1M Feb 25  2020 .bashrc
drwx------ 2 ubuntu ubuntu  1M Jun 21 08:27 .cache
-rw-r--r-- 1 ubuntu ubuntu  1M Feb 25  2020 .profile
drwx------ 2 ubuntu ubuntu  1M Jun 21 08:23 .ssh
-rw-rw-r-- 1 ubuntu ubuntu  1M Jun 21 08:56 file1-2.md5
-rw-rw-r-- 1 ubuntu ubuntu  1M Jun 21 08:27 file1.md5
-rw-rw-r-- 1 ubuntu ubuntu 10M Jun 21 08:56 file1.txt
-rw-rw-r-- 1 ubuntu ubuntu  1M Jun 21 09:00 file2-2.md5
-rw-rw-r-- 1 ubuntu ubuntu  1M Jun 21 08:57 file2.md5
-rw-rw-r-- 1 ubuntu ubuntu 10M Jun 21 09:00 file2.txt
-rw-rw-r-- 1 ubuntu ubuntu  1M Jun 21 09:00 file3.md5
-rw-rw-r-- 1 ubuntu ubuntu 10M Jun 21 09:00 file3.txt
ubuntu@vm1:~$ md5sum -c file2.md5 file1-2.md5 file2-2.md5 file3.md5
file2.txt: FAILED
md5sum: WARNING: 1 computed checksum did NOT match
file1.txt: OK
file2.txt: OK
file3.txt: OK
```

And according to the volume log that u have posted, the restore is failed because of `All replica restore failed and the volume became Faulted`, this may cause by a bad network connection between your cluster and the s3 storage server(I'm using Minio for testing).

**Comment by noahgildersleeve** [comment]
I retested this on S3 and these were the failures.
- Delete last backup in chained backup	
- Restore last backup in chained backup	
  - It's showing the files from backup 2 not backup 3
- Restore middle backup in chained backup
  - Showing the files from backup 1 not backup 2
- Restore First backup in chained backup	
  - file1.md5 was empty

**Comment by FrankYang0529** [comment]
I can reproduce this issue with s3 backup.
![Screenshot from 2021-10-04 16-10-37](https://user-images.githubusercontent.com/4927361/135816239-86b4f84e-887f-4942-9142-9b5d8af08b2a.png)

**Comment by FrankYang0529** [comment]
I found that even if we delete backup-2 and backup-3, VM still can't be restored by backup-1 at first time. I tried to stop VM, restored it again, and VM can be started successfully at second time. However, the data in the VM is latest, not backup-1. I will check whether Harvester delete correct longhorn backup

**Comment by lanfon72** [comment]
Reproduced on **master-82506f55-head**.
Can't test on NFS as there have a NFS related issue #1351

** Related test cases(15, 16, 17, 18, 19, 20, negative 10) of Backup and Restore.

**Comment by FrankYang0529** [comment]
After testing again on the latest build (master-a452886-head), VM can be started successfully without volume restoration failed. However, the data in VM is latest (backup3), not oldest (backup1). I think issues now are:
* Harvester can't choose a correct backup to restore VM.
* Harvester can't delete backups in longhorn correctly.

![Screenshot from 2021-10-06 23-34-02](https://user-images.githubusercontent.com/4927361/136238255-a87e0402-c7c0-4a5e-a082-c73b914f5c4a.png)

**Comment by yasker** [comment]
~~It seems there are some serious disconnections from the Harvester backup to Longhorn backup.~~

Longhorn backup is broken for v1.2.0 and v1.2.1.

**Comment by joshimoo** [comment]
We analysed the issue and identified it as a longhorn issue we are working on a fix as part of https://github.com/longhorn/longhorn/issues/3111

cc @innobead

**Comment by yasker** [comment]
Good job on finding this issue @FrankYang0529 ! We will fix it on the Longhorn side.

**Comment by guangbochen** [comment]
@FrankYang0529 can u please help to re-validate it again with the master-head build since we have bumped the LH to v1.2.2, thanks

**Comment by FrankYang0529** [comment]
## Test info

* Verified Harvester version: master-d96b7f6b-head

## Test cases

* Follow reproduce steps to restore backup1.
  * [x] file1.txt is existent.
  * [x] file2.txt and file3.txt don't exist.
  * [x] `md5sum -c md5sum1-1` Pass.
* Follow reproduce steps to restore backup3.
  * [x] file1.txt, file2.txt and fil3.txt are existent.
  * [x] `md5sum -c md5sum3-1 md5sum2-2 md5sum 1-2` Pass
