### ISSUE TITLE
[Question] Instructions to build a custom image?

### ISSUE THREAD

**Issue by withinboredom** [harvester/harvester#948]
I've tried to build a custom ISO (to embed k3os config/firmware) due to there being 0 bytes free in the image -- otherwise, I'd just edit the image. However, I cannot figure out how to do this on OSX and the docs don't give many details.

**Comment by guangbochen** [comment]
u may check the https://github.com/harvester/harvester-installer and run `make` to build your custom ISO, however, because we are using the containerd which is currently not supported in the macOS so u may need to make the create via a VM like Ubuntu to run the build with tools like Virtualbox.

**Comment by withinboredom** [comment]
Ah, I saw the HFS partition and assumed a mac was needed. Worked like a charm on a Linux machine!
