### ISSUE TITLE
[BUG] When deleting last backup in a chain some files aren't there after restore

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#949]
**Describe the bug**

When restoring after deleting the last backup in a chain some files are empty
**To Reproduce**

1. Create a new VM
2. Create a file named 1 and add some data using command dd if=/dev/urandom of=file1.txt count=100 bs=1M
3. Compute md5sum : md5sum-1
4. Create a backup
5. Overwrite file 1 
6. Create file 2
7. Compute md5sum for file 1 and file 2 : md5sum-2, md5sum-3
8. Create Backup
9. Overwrite the file 2
10. Create file 3 and compute md5sum for file 2 and file 3 : md5sum-4, md5sum-5
11. Create backup
12. delete backup 3
13. Validate that files didn't change
14. Restore to backup 2
15. Validate that
  - md5sum -c file1-2.md5 file2.md5 file3.md5 
  - file 1 is in second format
  - file 2 is in original format
  - file 3 doesn't exist

**Expected behavior**

The files should match, and file3 shouldn't exist.
**Support bundle**

[harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-14T19-34-31Z.zip](https://github.com/harvester/harvester/files/6650788/harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-14T19-34-31Z.zip)

**Environment:**
 - Harvester ISO version: master-3b6b8a6d-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL360G9

**Additional context**
This was on a VM created from http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img and with SSH config in the cloudconfig section.
```
#cloud-config
password: password
chpasswd: {expire: False}
sshpwauth: Tru
```

This might be related to [this bug](https://github.com/harvester/harvester/issues/945) since it's also an issue with chained backup.

`file2.md5` and `file1-2.md5` exist but are empty. Those files were created during between the 1st and second backup. The files from the first backup seem fine. The shell script I was using to generate and validate the files at every backup step is as follows:
```
#!/bin/bash
# first file
if [ $1 = 1 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    md5sum file1.txt > file1.md5
    md5sum -c file1.md5
fi
## overwrite file1 and create file2
if [ $1 = 2 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    md5sum file1.txt > file1-2.md5
    md5sum file2.txt > file2.md5
    md5sum -c file1.md5 file1-2.md5 file2.md5
fi
## overwrite file2 and create file3
if [ $1 = 3 ]
then
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    dd if=/dev/urandom of=file3.txt count=100 bs=1M
    md5sum file2.txt > file2-2.md5
    md5sum file3.txt > file3.md5
    md5sum -c file2.md5 file1-2.md5 file2-2.md5 file3.md5
fi
```

**Comment by noahgildersleeve** [comment]
I looked into this some more and it doesn't seem to be related to the delete. This happens even when just restoring to the middle of the chain without deleting one of the backups.

**Comment by noahgildersleeve** [comment]
So after some further investigation in a chained backup restore to backup1 is fine, but restore to backup2 and backup3 fail due to the files being empty.

**Comment by yasker** [comment]
Not sure if this still exists. Need to recheck.

**Comment by yasker** [comment]
This is blocked by https://github.com/harvester/harvester/issues/945

**Comment by guangbochen** [comment]
@lanfon72 can u please help to re-validate this one using the master-head ISO since the LH is bumped to v1.2.2.

**Comment by FrankYang0529** [comment]
## Test info

* Verified Harvester version: master-d96b7f6b-head

## Test cases

* Follow reproduce steps to delete backup3.
  * [x] files don't change.
* Follow reproduce steps to restore backup2.
  * [x] file1.txt and file2.txt are existent.
  * [x] file3.txt, file2-2.md5 and file3-1.md5 don't exist.
  * [x] `md5sum -c file1-2.md5 file2-1.md5` Pass
