### ISSUE TITLE
[BUG] If use an external Rancher, project owner user get  /v1/userpreferences return 404

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#951]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/122029130-35ecd480-cdff-11eb-80f4-80a23c292525.png)

**To Reproduce**
1. Use an external Rancher
2. Create a project owner user
3. Use the user to log in
4. After log in, check api  /v1/userpreferences

**Expected behavior**

/v1/userpreferences return 200

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by TangStone** [comment]
Validated in version master-158a35d3-head
![image](https://user-images.githubusercontent.com/15829074/122954967-7aa1de00-d3b2-11eb-93db-ba10c6b2b0db.png)
