### ISSUE TITLE
[BUG] Unable to install if a wifi card is present

### ISSUE THREAD

**Issue by withinboredom** [harvester/harvester#953]
**Describe the bug**

If there's a wifi card present, `harvester-configure-network` will choke if a nearby wifi network contains spaces.

**To Reproduce**
1. Burn iso and boot on a machine with a wifi card
2. Ensure a local access point is broadcasting an SSID with spaces in it
3. Try to configure networking, cannot continue past the network configuration screen.

Due to being unable to continue past this point, it's probably safe to try on your personal laptops :)

**Expected behavior**

Able to configure networking.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.2.0
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Bare Metal MBP 13,2 (needs separate patches currently in-progress)

**Additional context**

**Comment by yaocw2020** [comment]
We change the os for the Harvester and use wicked which should support wifi cards to manage the network. I can not find a machine with a wifi card, @withinboredom  could you kindly help verify this issue?
https://releases.rancher.com/harvester/master/harvester-amd64.iso

**Comment by guangbochen** [comment]
close in favor of the v0.3.0 release, please feel free to re-open it if u encounter a `wifi card` issue, thanks.
