### ISSUE TITLE
[BUG] Second network doesn't show up in VM

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#954]
**Describe the bug**

If you add a second network to a VM then it won't add the network interface
**To Reproduce**
1. Start to Create a new VM
2. Create it with the VM image template and http://cloud-images.ubuntu.com/releases/focal/release/ubuntu-20.04-server-cloudimg-amd64-disk-kvm.img
2. that is a VLAN network that is configured correctly and has external network connectivity
3. Create the VM
4. Verify that the network works
5. Edit the VM via config
6. Add a second network that is the management network with masquerade as the type
7. Save
8. Wait for VM to reboot
9. Check network connectivity

**Expected behavior**

VM should have access to the second network
**Support bundle**

[harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-15T22-38-39Z.zip](https://github.com/harvester/harvester/files/6659155/harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-15T22-38-39Z.zip)

**Environment:**
 - Harvester ISO version: master-3b6b8a6d-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL360G9
**Additional context**
I also tried this with the original network being the management network and then adding the VLAN network, and also with adding both on creation. It only seems to ever support the first network. I checked in `ifconfig` and I only see `enp1s0` and no other network interface besides the loopback interface. I don't see two network interfaces in the guest OS. I checked the YAML and it didn't seem any different from VMs that had working management networks.
![Greenshot 2021-06-15 15 43 33](https://user-images.githubusercontent.com/83787952/122133380-70e80b80-cdf1-11eb-818c-00672b52a883.png)
![Greenshot 2021-06-15 15 43 42](https://user-images.githubusercontent.com/83787952/122133385-72193880-cdf1-11eb-923d-c664e7a84874.png)

**Comment by guangbochen** [comment]
can we please check if this is still an issue of the master-head version, thanks?

**Comment by yasker** [comment]
Works for me in master. Close as fixed.
