### ISSUE TITLE
[BUG] Cannot see the harvester hosts with the default selected view "Only User Namespaces"

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#956]
**Describe the bug**
After a fresh install of a five nodes cluster, I can't see the 5 harvesters nodes in the host section with the default filter "Only User Namespaces".

**To Reproduce**
1. Install the last master ISO and make sure you have the default namespace view:  "Only User Namespaces".

![Screenshot from 2021-06-16 11-47-49](https://user-images.githubusercontent.com/6025636/122217113-625f2a00-cead-11eb-8b4c-2257f0eff981.png)

2. Click on the host section, no host appears.
![Screenshot from 2021-06-16 14-13-53](https://user-images.githubusercontent.com/6025636/122217556-ce419280-cead-11eb-9dfe-cf4ee1fa5019.png)

You can see them if you delete the filter "Only User Namespaces" or select "All namespaces"

**Expected behavior**
The hosts should show up.

**Support bundle**
[harvester-supportbundle_3c8e9a06-40f7-457a-bdae-60c33a02f65a_2021-06-16T12-22-10Z.zip](https://github.com/harvester/harvester/files/6662952/harvester-supportbundle_3c8e9a06-40f7-457a-bdae-60c33a02f65a_2021-06-16T12-22-10Z.zip)

**Environment:**
 - Harvester ISO version: master-6d5c7df2-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with DL360-G9

**Additional context**
N/A

**Comment by noahgildersleeve** [comment]
The link in the sidebar is going to /host, but the link on the dashboard is going to /node. It seems that /node is where the hosts are being displayed.
![Greenshot_2021-06-23_13_50_12](https://user-images.githubusercontent.com/83787952/123170854-df4f4e00-d42f-11eb-8f02-23352e1238ed.jpg)
![Greenshot_2021-06-23_13_50_23](https://user-images.githubusercontent.com/83787952/123170861-e0807b00-d42f-11eb-9d7d-55f831dd07f6.jpg)

**Comment by juadk** [comment]
Tested successfully with `master-46ee2188-head` on a 5 nodes cluster.

I can see the hosts with the default namespace view: "Only User Namespaces".
![Screenshot from 2021-06-30 13-59-35](https://user-images.githubusercontent.com/6025636/123956937-85a8cf80-d9ab-11eb-85d0-31bb170b1fe5.png)
Both sidebar and dashboard host links are pointing to the same URL now: `/dashboard/c/local/virtual/host
`
