### ISSUE TITLE
[BUG]The required fields in API doc still not quite correct

### ISSUE THREAD

**Issue by guangyee** [harvester/harvester#957]
**Describe the bug**
This is a followup to https://github.com/harvester/harvester/issues/890. The newly generated API doc here https://docs.harvesterhci.io/v0.3-dev/reference/api/ still not quite correct. For example, when creating SSH key pairs, `apiVersion`, `kind`, and either `metadata/name` or `metadata/gererateName` are required. But none of them have a red asterisk (*) symbol next to them.

**To Reproduce**
See the newly generated doc here https://docs.harvesterhci.io/v0.3-dev/reference/api/

**Expected behavior**
All the required field should have the red asterisk (*) symbol next to them

**Support bundle**
N/A

**Environment:**
Harvester version: 0.3-dev

**Additional context**

**Comment by gitlawr** [comment]
If users can use either name or generateName I think we cannot add the red asterisk to any of them. The `kind` and `apiVersion` (and the names) are from kubernetes core API and they are not required in the schema. We might need to find a hacky way to improve. For example in kubevirt docs: https://kubevirt.io/api-reference/master/definitions.html#_v1_kubevirt

**Comment by guangyee** [comment]
Problem is if they are absent Harvester will return HTTP 422. So from end user's perspective, they are required.

**Comment by guangyee** [comment]
Looks like the `network` APIs are missing as well.

**Comment by juadk** [comment]
The network API doc is now available here https://docs.harvesterhci.io/v0.3-dev/reference/api/
Regarding `apiVersion`, `kind`, `metadata/name` and `metadata/gererateName` as required fields. it looks good to me if I'm checking the POST command to create a KeyPair object: 
![Screenshot from 2021-06-30 16-44-08](https://user-images.githubusercontent.com/6025636/123981254-7bde9680-d9c2-11eb-8ef1-bcaf3905edcf.png)
![Screenshot from 2021-06-30 16-44-21](https://user-images.githubusercontent.com/6025636/123981289-826d0e00-d9c2-11eb-9281-9affc5e053d4.png)
@guangyee is ok for you? Maybe I can try to create/change network settings through the API?

**Comment by guangyee** [comment]
The networking API are there. The name field still not consistent for some resources. For example, for virtualmachinetemplates, the name or generateName still required but it was marked as required.

**Comment by juadk** [comment]
@gitlawr Could you take a look at this please?

**Comment by gitlawr** [comment]
@guangyee I can see that the name of virtualmachinetemplates is marked as required, is there anything I am missing?
![image](https://user-images.githubusercontent.com/5697937/124083110-12bd5880-da80-11eb-9e4e-6257dedce736.png)

**Comment by guangyee** [comment]
Would be awesome if we can document the metrics APIs as well. Basically API that UI uses we should have them documented in Swagger.

**Comment by guangbochen** [comment]
close in favor of the existing API doc, please file a separate issue if a more detailed doc is needed.
