### ISSUE TITLE
websocket is broken in some cases

### ISSUE THREAD

**Issue by gitlawr** [harvester/harvester#96]
Steps to reproduce:
1. Go to the image list page. do a refresh
2. Create an image

Result:
The import progress of the image is not updated.

It works following these steps:
1. Go to the VM list page. do a refresh
2. Click image in the navigation and go to the image list page.
3. Create an image.

**Comment by gitlawr** [comment]
In the working case, the UI sends the following message about which resource type and revision to watch
![image](https://user-images.githubusercontent.com/5697937/91789716-ca57c300-ec41-11ea-876c-6e05cc959bac.png)

In the broken case, the message is not sent
![image](https://user-images.githubusercontent.com/5697937/91789905-2e7a8700-ec42-11ea-82d8-27d60ec0d937.png)

**Comment by guangbochen** [comment]
close in favor of https://github.com/rancher/harvester-ui/commit/67da3aa926645772c2b353515442d1c7c1a55c4f
