### ISSUE TITLE
[BUG] All restores fail on backups with NFS backup target

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#960]
**Describe the bug**

All backups are missing file contents on restores from NFS backups
**To Reproduce**

1. Create a new VM
2. Create a file named 1 and add some data using command dd if=/dev/urandom of=file1.txt count=100 bs=1M
3. Compute md5sum : md5sum-1
4. Create a backup
5. Overwrite file 1 
6. Create file 2
7. Compute md5sum for file 1 and file 2 : md5sum-2, md5sum-3
8. Create Backup
9. Overwrite the file 2
10. Create file 3 and compute md5sum for file 2 and file 3 : md5sum-4, md5sum-5
11. Create backup
12. Validate that files didn't change
13. Restore to backup 1
14. Validate that
  - 15. md5sum -c file1.md5 file2.md5 file3.md5 
  - 16. file 1 is in original format - md5sum-1
  - 17. file 2 doesn't exist
  - 18. file 3 doesn't exist
**Expected behavior**

Backup should restore and file should match checksum
**Support bundle**

[harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-17T16-44-55Z.zip](https://github.com/harvester/harvester/files/6672093/harvester-supportbundle_50043b09-3cc7-4421-8769-294c983cfbbc_2021-06-17T16-44-55Z.zip)

**Environment:**
 - Harvester ISO version: master-3b6b8a6d-head
Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal DL360G9

**Additional context**
I tested this against every P1 test case for NFS and they all failed. This is probably related to [this bug](https://github.com/harvester/harvester/issues/949), but for S3 stores this specific scenario did work. I was testing this on a local NFS store setup on Longhorn on the local rancher cluster, but I did also verify that it was broken on a remote NFS store.

The files seem to be getting created. I was able to verify on the remote NFS and the local NFS.
Here is the shell script I used for creating the files and getting the md5 checksums
```
#!/bin/bash
# first file
if [ $1 = 1 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    md5sum file1.txt > file1.md5
    md5sum -c file1.md5
fi
## overwrite file1 and create file2
if [ $1 = 2 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    md5sum file1.txt > file1-2.md5
    md5sum file2.txt > file2.md5
    md5sum -c file1.md5 file1-2.md5 file2.md5
fi
## overwrite file2 and create file3
if [ $1 = 3 ]
then
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    dd if=/dev/urandom of=file3.txt count=100 bs=1M
    md5sum file2.txt > file2-2.md5
    md5sum file3.txt > file3.md5
    md5sum -c file2.md5 file1-2.md5 file2-2.md5 file3.md5
fi
```

**Comment by noahgildersleeve** [comment]
Possibly related to https://github.com/harvester/harvester/issues/949

**Comment by noahgildersleeve** [comment]
I tested NFS again and these were the failures.
- Delete first backup in chained backup
- Delete last backup in chained backup	
- Restore last backup in chained backup	
- Restore middle backup in chained backup

**Comment by yasker** [comment]
Move to v1.0.0 due to NFS backupstore is not P1 use case for v0.3.0.

**Comment by FrankYang0529** [comment]
I can't reproduce this in master-d05acc-head.

## Test Environment

* Verified version: master-d05acc-head (1 node on KVM).
* Use local NFS from Longhorn example (https://github.com/longhorn/longhorn/blob/v1.2.2/deploy/backupstores/nfs-backupstore.yaml).

## Test cases

Follow test steps 1 to 12.

### Case 1 - Restore backup 1

* Verified only file1.txt and md5sum1-1 existent.✔️
* Verified `md5sum -c md5sum1-1` pass.✔️

### Case 2 - Restore backup 2

* Verified only file1.txt, file2.txt, md5sum1-1, md5sum1-2 and md5sum2-1 existent.✔️
* Verified `md5sum -c md5sum1-2 md5sum2-1` pass.✔️
* Verified `md5sum -c md5sum1-1` fail.✔️

### Case 3 - Restore backup 3

* Verified file1.txt, file2.txt, file3.txt md5sum1-1, md5sum1-2, md5sum2-1, md5sum2-2 and md5sum3-1 existent.✔️
* Verified `md5sum -c md5sum1-2 md5sum2-2 md5sum3-1` pass.✔️
* Verified `md5sum -c md5sum1-1 md5sum2-1` fail.✔️

**Comment by noahgildersleeve** [comment]
Currently blocked by https://github.com/harvester/harvester/issues/1536

**Comment by noahgildersleeve** [comment]
Tested in master-655c251a-head. On restore from backup files were missing contents. I tested this on opensuse 15.3 and Ubuntu focal. This was on chained backups, but I also tested by 
1. Run all 3 steps in attached script
```
#!/bin/bash
# first file
if [ $1 = 1 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    md5sum file1.txt > file1.md5
    md5sum -c file1.md5
fi
## overwrite file1 and create file2
if [ $1 = 2 ]
then
    dd if=/dev/urandom of=file1.txt count=100 bs=1M
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    md5sum file1.txt > file1-2.md5
    md5sum file2.txt > file2.md5
    md5sum -c file1.md5 file1-2.md5 file2.md5
fi
## overwrite file2 and create file3
if [ $1 = 3 ]
then
    dd if=/dev/urandom of=file2.txt count=100 bs=1M
    dd if=/dev/urandom of=file3.txt count=100 bs=1M
    md5sum file2.txt > file2-2.md5
    md5sum file3.txt > file3.md5
    md5sum -c file2.md5 file1-2.md5 file2-2.md5 file3.md5
fi
```
2. Create backup
3. Restore from backup run final `md5sum -c file2.md5 file1-2.md5 file2-2.md5 file3.md5`
the files containing the checksums were empty.

**Comment by FrankYang0529** [comment]
It looks like there is some delay for data from the cache to disk. I try to run a command `sync` before making the backup. I can get nonempty checksums.

@guangbochen, do you think it's a case? Thank you.

**Comment by guangbochen** [comment]
@noahgildersleeve can u please help to double check if using the `sync` command before taking the backup works for u, the `sync` command forces an immediate transfer of the data in memory to disk.

**Comment by noahgildersleeve** [comment]
Tested in master-3d096946-head. Validated that all three chained backups worked
## Test Steps

1. ran `backup.sh 1`
2. run `sync`
3. take backup
4. ran `backup.sh 2`
5. run `sync`
6. take backup
7. ran `backup.sh 3`
8. run `sync`
9. take backup
10. ran `backup.sh 4`
11. restore to backup 3
12. verify files
13. restore to backup 2
14. verify files
15. restore to backup 1
16. verify files
