### ISSUE TITLE
[BUG] Webhook service is not available in air-gapped enviornment

### ISSUE THREAD

**Issue by bk201** [harvester/harvester#962]
**Describe the bug**

**To Reproduce**
1. Install Harvester from the master ISO.
2. If there is no Internet connectivity, the harvester-webhook pods stay in `ImagePullBackOff` state.
    e.g. 
    ```
    harvester-system   harvester-webhook-596c748d74-g7hnv                      0/1     ImagePullBackOff    0          17m
    ```

**Expected behavior**
The harvester-webhook pods should be running.

**Support bundle**

**Environment:**
 - Harvester ISO version: 03ecd279b0a8e3334fa485ab72bed2630c3b91d2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): VM testing.

**Additional context**
Need to patch imagePullPolicy in https://github.com/harvester/harvester-installer/blob/master/manifests/harvester.yaml

**Comment by ldevulder** [comment]
I've installed the latest master version (`master-158a35d`) and tested:
- installation with an internet connection that I've removed after: pod `harvester-webhook` was still in `Running` state
- installation without an internet connection: pod `harvester-webhook` was in `Running` state and Harvester status was `Ready`

So I was not able to reproduce the issue with the fix in PR#89, issue closed.
