### ISSUE TITLE
[BUG] disk name is increase even if not used

### ISSUE THREAD

**Issue by ldevulder** [harvester/harvester#965]
**Describe the bug**
If I want to add a volume in a VM (a new one or an existing one) when I clickj on `Add <whatever_you_want>` the disk name is automatically increased by default, so name is set to `disk-1` by default. But if I finally don't add the disk and if I click again on `Add ...` the disk name is incremented to `disk-2` instead of `disk-1`.

It's not something critical of course, as I can still manually change the disk name and it works as a workaround. But it's a little bit weird.

**To Reproduce**
1. Go to `Virtual Machines`
2. Then `Create`
3. Then `Volumes` and `Add Volume`, disk name is set by default to `disk-1`
4. Click on the cross to not add the volume
5. Re-click on `Add Volume`, disk name is now set by default to `disk-2` instead of `disk-1`

**Expected behavior**
The name of the disk should be incremented according to the latest used disk.

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: master-abc91f03-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): baremetal on DL160 Gen9

**Additional context**
N/A

**Comment by guangbochen** [comment]
close in favor of v0.3.0, now it support drag and drop and move up or down.
