### ISSUE TITLE
image list and detail page issue

### ISSUE THREAD

**Issue by DoNotSayYes** [harvester/harvester#97]
- [x] 1. The state of the image on the list page, but unknown on the detail page
![image](https://user-images.githubusercontent.com/57614736/91790860-4fdc7280-ec44-11ea-845a-5bbef3e4a35b.png)
![image](https://user-images.githubusercontent.com/57614736/91790950-7ef2e400-ec44-11ea-9749-e5cf5b4ef570.png)

- [x] 2. Sort by the state on the list page could make the page work inappropriately, something like the menubar does not pop up by clicking the ellipsis
![image](https://user-images.githubusercontent.com/57614736/91791291-57e8e200-ec45-11ea-99eb-4fb767c3ffe8.png)

- [x] 3. Select one of the items, proceed clone as form, users are not able to add more than one label or annotation
![image](https://user-images.githubusercontent.com/57614736/91791483-d80f4780-ec45-11ea-93fc-23fa5d88ec9c.png)

- [ ] 4. Is it necessary to suppress the `create a virtual machine ` on the menu bar if the image state is not healthy?
![image](https://user-images.githubusercontent.com/57614736/91792896-38ec4f00-ec49-11ea-8f30-9fa46079e6c2.png)

- [x] 5. This functionality does work
![image](https://user-images.githubusercontent.com/57614736/91801882-21b75c80-ec5d-11ea-9fae-9920dbea7aae.png)

**Comment by guangbochen** [comment]
remove the protips hint from the dialog.

**Comment by DoNotSayYes** [comment]
Validated all except the 4th item
