### ISSUE TITLE
[BUG] Can't set S3 Backup Target

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#971]
**Describe the bug**

You get an error while trying to create S3 backup target
**To Reproduce**
1. Add S3 backup target in settings

**Expected behavior**

It should save target successfully.

**Support bundle**

[harvester-supportbundle_ede8b267-584d-4bbb-931a-71cf30b5e83d_2021-06-23T17-59-32Z.zip](https://github.com/harvester/harvester/files/6703995/harvester-supportbundle_ede8b267-584d-4bbb-931a-71cf30b5e83d_2021-06-23T17-59-32Z.zip)

**Environment:**
 - Harvester ISO version: master-158a35d3-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL160G9

**Additional context**
This was working before with this same S3 bucket. I wonder if this might be a result of the introduction of the web hooks. 
![Greenshot_2021-06-23_10_42_57](https://user-images.githubusercontent.com/83787952/123146363-a0f76600-d412-11eb-8423-8679cbc7c344.jpg)

**Comment by guangbochen** [comment]
do we specify the region?

**Comment by noahgildersleeve** [comment]
Yes, but this one has been cleared for security reasons.
![Greenshot 2021-06-23 17 18 47](https://user-images.githubusercontent.com/83787952/123183763-17ae5680-d447-11eb-8bc7-035cf031b553.png)

**Comment by weihanglo** [comment]
IIRC bucket name and bucket region won't be clear. Maybe fail to save the config?

**Comment by weihanglo** [comment]
I can reproduce the issue by specifying "endpoint" for backup target. If endpoint is not provided and other fields are valid, this should just work.

```
// excertp from provided suport bundle settings.yaml

metadata: {
  name: "backup-target"
},
value: {
  "type": "s3",
  "endpoint": "https://s3.xxxxx.amazonaws.com/",
  "accessKeyId": "",
  "secretAccessKey": "",
  "bucketName": "xxxxx",
  "bucketRegion": "xxxx-region",
  "cert": "",
  "virtualHostedStyle": false
}
```

> Version:  master-158a35d3-head

**Comment by guangbochen** [comment]
**Testing plan:**
- config the s3 backup target with the specified region and endpoint e.g, ap-northeast-1 and https://s3.ap-northeast-1.amazonaws.com respectively.
- config the s3 backup target without specifying the endpoint but the region only.

**Comment by juadk** [comment]
Tested successfully with `master-07efe71c-head`.
* Configuration with the endpoint
![with_endpoint](https://user-images.githubusercontent.com/6025636/125475037-e5af9041-7383-4457-8e8f-183f8cfc0e96.png)
Test to backup a VM with the endpoint defined: :heavy_check_mark: 

* Configuration without the endpoint
![without_endpoints](https://user-images.githubusercontent.com/6025636/125477752-fd232963-10a3-4986-9539-e09807640bf9.png)
Test to backup a VM without the endpoint defined: :heavy_check_mark: 

Expected message about the remove of the endpoint:
![Screenshot from 2021-07-13 17-15-13](https://user-images.githubusercontent.com/6025636/125477957-67b4f33e-7bf3-401b-b62d-3d33dc9b9568.png)
