### ISSUE TITLE
[BUG]Error while updating a VM using kubevirt api 

### ISSUE THREAD

**Issue by chajain** [harvester/harvester#972]
**Describe the bug**
While trying to update a VM's cores and memory using the API, it fails with error -
E       AssertionError: Failed to update vm: b'{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \\"62a6b86fbc35454796a6dc6d808fb4b5\\": the object has been modified; please apply your changes to the latest version and try again","reason":"Conflict","details":{"name":"62a6b86fbc35454796a6dc6d808fb4b5","group":"kubevirt.io","kind":"virtualmachines"},"code":409}\n'

**To Reproduce**
Use a script to update a created VM using the update API 

**Expected behavior**
After a successful update, the api should return status code 200 and update the VM with updated cores and memory

**Support bundle**

**Environment:**
 - Harvester ISO version: master
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Harvester iPXE Boot Using Vagrant Libvirt

**Additional context**

**Comment by maxiloEmmmm** [comment]
@chajain u can update after vm state become running, the resource will be updated multiple times before then, so updates that are too fast after the script is created will cause conflicts

**Comment by maxiloEmmmm** [comment]
@chajain u can use script to watch vm state, if become running, do update

**Comment by guangbochen** [comment]
Kubernetes objects have a resource version that is unique for each update. If an update comes in that has an out-of-date resource version, it is rejected to prevent racing updates from clobbering each other. it is an implementation detail.
