### ISSUE TITLE
[BUG] Sidebar link to hosts isn't showing hosts

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#974]
**Describe the bug**

When you go to the hosts page in the side navigation you can't see any hosts, but you can if you click hosts from dashboard
**To Reproduce**
1. Click hosts from sidebar navigation
**Expected behavior**

You should see the hosts in the list
**Support bundle**

[harvester-supportbundle_ede8b267-584d-4bbb-931a-71cf30b5e83d_2021-06-23T20-53-05Z.zip](https://github.com/harvester/harvester/files/6704838/harvester-supportbundle_ede8b267-584d-4bbb-931a-71cf30b5e83d_2021-06-23T20-53-05Z.zip)

**Environment:**
 - Harvester ISO version: master-158a35d3-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal bare metal DL160G9

**Additional context**
The link in the sidebar is going to `/host`, but the link on the dashboard is going to `/node`. It seems that `/node` is where the hosts are being 
![Greenshot_2021-06-23_13_50_12](https://user-images.githubusercontent.com/83787952/123166519-597cd400-d42a-11eb-9e12-5d50c388bf30.jpg)
![Greenshot_2021-06-23_13_50_23](https://user-images.githubusercontent.com/83787952/123166523-5aae0100-d42a-11eb-9d84-8667815f81bf.jpg)

**Comment by juadk** [comment]
Looks similar to this [bug](https://github.com/harvester/harvester/issues/956), WDYT?

**Comment by noahgildersleeve** [comment]
I agree. I think that it's the same issue. I still think it has something to do with the difference in the URL. I'll close this bug and update the other one since it was first.

**Comment by noahgildersleeve** [comment]
Closing bug as dupe of https://github.com/harvester/harvester/issues/956
