### ISSUE TITLE
[BUG] Wrong login page tab name

### ISSUE THREAD

**Issue by juadk** [harvester/harvester#975]
**Describe the bug**
The login page tab name is **Rancher** instead of **Harvester** with the Harvester logo, I don't think that's expected.

![Screenshot from 2021-06-24 08-29-22](https://user-images.githubusercontent.com/6025636/123213447-4ddeeb00-d4c6-11eb-9008-86aaaeadee76.png)

**To Reproduce**
1. Go to the login page and check the tab name.

**Expected behavior**
Tab should be named **Harvester**

**Support bundle**
N/A

**Environment:**
 - Harvester ISO version: master-158a35d3-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): ISO and dev mode

**Additional context**
N/A

**Comment by WuJun2016** [comment]
@DaiYuzeng   Solve problems in customer projects, 

@guangbochen   harvester will not have this problem after merge to dashboard

**Comment by noahgildersleeve** [comment]
tested with master from 8-18, but build number is showing v2.6.0-rc3 due to existing bug. Closing
