### ISSUE TITLE
[FEATURE] VLAN network enhancement: distinguish one and multiple NICs cases

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#980]
**Is your feature request related to a problem? Please describe.**

If the machine has only one physical NIC, the VLAN network and management network will use the same NIC, it has to inherit the IP address and routing rules of the NIC. However, if there are multiple physical NICs and the VLAN network use the NIC different from the management network, it is unnecessary to inherit the IP address and routing rules. 

The Harvester network controller does not distinguish between these two cases. It inherits the IP address and routing rules of the NIC used by the VLAN network, whether is used by the management network or not. This method increases the complexity to handle the routing rules. The routing rules of the NIC used by the management network are fixed and easy to inherit. 

**Describe the solution you'd like**

To distinguish one and multiple NICs cases.

![image](https://user-images.githubusercontent.com/7421463/123505224-73b7eb80-d690-11eb-85e2-13d4d26c56f4.png)

In case 1, the management network and VLAN network use the same physical NIC. Harvester-br0 will inherit the IP address and routing rules of eth0. The IP address of eth0 can not be changed. 
In case 2, the management network and VLAN network use different physical NICs. The harvester-br0 will not inherit the IP address and routing rules of eth1 which will be ignored or cleared.

**Describe alternatives you've considered**

In both cases, we will bind kube-vip with harvester-br0 where kube-vip configures the VIP address and the IP address of loadBalancer services.

> Hint: We can use [ghw](https://github.com/jaypipes/ghw) to distinguish the type of NICs.

**Additional context**

**Comment by yaocw2020** [comment]
@DaiYuzeng `v1/network.harvesterhci.io.nodenetworks` API changed.

**Comment by yaocw2020** [comment]
To test:
- Select the NIC used by the management network as the NIC for the VLAN network. The `harvester-br0` will inherit the IP address and routes. The VLAN network should work.
- Change the NIC for the VLAN network with another one not used by the management network. The `harvester-br0` won't inherit the IP and routes. And the routes of the NIC will be cleared. The VLAN network should work.

The shell commands help to check the IP and routes.
``` shell 
ip a show dev <interface>
ip r show dev <interface>
```

**Comment by yaocw2020** [comment]
``` yaml
apiVersion: network.harvesterhci.io/v1beta1
kind: NodeNetwork
metadata:
  creationTimestamp: "2021-08-03T07:10:23Z"
  finalizers:
  - wrangler.cattle.io/harvester-nodenetwork-controller
  generation: 3
  labels:
    network.harvesterhci.io/nodename: wj
  managedFields:
  - apiVersion: network.harvesterhci.io/v1beta1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"wrangler.cattle.io/harvester-nodenetwork-controller": {}
        f:labels:
          .: {}
          f:network.harvesterhci.io/nodename: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"38123f6b-3ba0-4604-ae1d-780f05247828"}:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:uid: {}
      f:spec:
        .: {}
        f:nic: {}
        f:nodeName: {}
        f:type: {}
      f:status:
        .: {}
        f:conditions: {}
        f:networkLinkStatus:
          .: {}
          f:eth0:
            .: {}
            f:index: {}
            f:ipv4Address: {}
            f:mac: {}
            f:masterIndex: {}
            f:state: {}
            f:type: {}
          f:harvester-br0:
            .: {}
            f:index: {}
            f:ipv4Address: {}
            f:mac: {}
            f:promiscuous: {}
            f:routes: {}
            f:state: {}
            f:type: {}
        f:nics: {}
    manager: harvester-network-controller
    operation: Update
    time: "2021-08-03T07:10:23Z"
  name: wj-vlan
  ownerReferences:
  - apiVersion: core
    kind: Node
    name: wj
    uid: 38123f6b-3ba0-4604-ae1d-780f05247828
  resourceVersion: "66358277"
  uid: 75237794-dd2c-4e7c-876a-a95fcdd34b61
spec:
  nic: eth0
  nodeName: wj
  type: vlan
status:
  conditions:
  - lastUpdateTime: "2021-08-03T07:10:23Z"
    status: "True"
    type: Ready
  networkLinkStatus:
    eth0:
      index: 2
      ipv4Address:
      - 172.16.0.203/16 eth0
      mac: ee:7c:6f:f7:47:86
      masterIndex: 48
      state: up
      type: device
    harvester-br0:
      index: 48
      ipv4Address:
      - 172.16.0.203/16 harvester-br0
      mac: ee:7c:6f:f7:47:86
      promiscuous: true
      routes:
      - '{"LinkIndex":48,"ILinkIndex":0,"Scope":0,"Dst":null,"Src":"","Gw":"172.16.0.1","MultiPath":null,"Protocol":3,"Priority":0,"Table":254,"Type":1,"Tos":0,"Flags":0,"MPLSDst":null,"NewDst":null,"Encap":null,"Via":null,"MTU":0,"Window":0,"Rtt":0,"RttVar":0,"Ssthresh":0,"Cwnd":0,"AdvMSS":0,"Reordering":0,"Hoplimit":0,"InitCwnd":0,"Features":0,"RtoMin":0,"InitRwnd":0,"QuickACK":0,"Congctl":"","FastOpenNoCookie":0}'
      - '{"LinkIndex":48,"ILinkIndex":0,"Scope":0,"Dst":{"IP":"144.144.144.144","Mask":"/////w=="},"Src":"","Gw":"172.16.0.1","MultiPath":null,"Protocol":3,"Priority":0,"Table":254,"Type":1,"Tos":0,"Flags":0,"MPLSDst":null,"NewDst":null,"Encap":null,"Via":null,"MTU":0,"Window":0,"Rtt":0,"RttVar":0,"Ssthresh":0,"Cwnd":0,"AdvMSS":0,"Reordering":0,"Hoplimit":0,"InitCwnd":0,"Features":0,"RtoMin":0,"InitRwnd":0,"QuickACK":0,"Congctl":"","FastOpenNoCookie":0}'
      - '{"LinkIndex":48,"ILinkIndex":0,"Scope":253,"Dst":{"IP":"172.16.0.0","Mask":"//8AAA=="},"Src":"172.16.0.203","Gw":"","MultiPath":null,"Protocol":2,"Priority":0,"Table":254,"Type":1,"Tos":0,"Flags":0,"MPLSDst":null,"NewDst":null,"Encap":null,"Via":null,"MTU":0,"Window":0,"Rtt":0,"RttVar":0,"Ssthresh":0,"Cwnd":0,"AdvMSS":0,"Reordering":0,"Hoplimit":0,"InitCwnd":0,"Features":0,"RtoMin":0,"InitRwnd":0,"QuickACK":0,"Congctl":"","FastOpenNoCookie":0}'
      - '{"LinkIndex":48,"ILinkIndex":0,"Scope":253,"Dst":{"IP":"172.16.0.1","Mask":"/////w=="},"Src":"","Gw":"","MultiPath":null,"Protocol":3,"Priority":0,"Table":254,"Type":1,"Tos":0,"Flags":0,"MPLSDst":null,"NewDst":null,"Encap":null,"Via":null,"MTU":0,"Window":0,"Rtt":0,"RttVar":0,"Ssthresh":0,"Cwnd":0,"AdvMSS":0,"Reordering":0,"Hoplimit":0,"InitCwnd":0,"Features":0,"RtoMin":0,"InitRwnd":0,"QuickACK":0,"Congctl":"","FastOpenNoCookie":0}'
      state: up
      type: bridge
  nics:
  - index: 2
    masterIndex: 48
    name: eth0
    state: up
    type: device
    usedByManagementNetwork: true

```

**Comment by yaocw2020** [comment]
```
  nics:
  - index: 2
    masterIndex: 48
    name: eth0
    state: up
    type: device
    usedByManagementNetwork: true
```
The item changed.
Please help to display the state in the UI.
![image](https://user-images.githubusercontent.com/7421463/127993009-c8984fe5-97c6-4d2c-8917-4f0ef21a7cae.png)

**Comment by DaiYuzeng** [comment]
Click [here](https://github.com/harvester/harvester/issues/807#issuecomment-900873123) to see how to test this issue.

#807

**Comment by gitlawr** [comment]
In a multi-NIC case:
NIC1: 10.10.1.0/24(vlan200)
NIC2: 10.10.2.0/24(vlan300)

1. Setup Harvester cluster using NIC1 as the management NIC, VIP is fetched from DHCP in 10.10.1.0/24 CIDR, say, 10.10.1.10
2. Enable vlan network and use the NIC2 for vlan network.

As a result, the VIP is not accessible.

The kube-vip daemonset uses harvester-br0 as the vip_interface.
harvester-br0 is the master of NIC2, using a different CIDR from the VIP 10.10.1.10

Logs from the leader kube-vip pod:
```
time="2021-10-10T02:46:01Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 10s)"
time="2021-10-10T02:46:46Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 12.926157818s)"
time="2021-10-10T02:47:34Z" level=error msg="request failed, error: got an error while processing the request: no matching response packet received (waiting 24.264065943s)"
```

**Comment by gitlawr** [comment]
Edit: it happened when I configure the default NIC to harvester-mgmt then change the vlan NIC to NIC2 for each node. If I configure NIC2 as the cluster default or disable then reconfigure vlan network it works as expect

**Comment by gitlawr** [comment]
Closing as both single-NIC and multiple-NIC cases work for me
