### ISSUE TITLE
[BUG] VM status doesn't update when host goes down

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#982]
**Describe the bug**

VM status doesn't update when you take a host offline
**To Reproduce**
1. Create a VM on a host
2. Turn off the host
3. Wait for host to become unavailable
4. Check status of VM
**Expected behavior**

VM should either show that it's unavailable or migrate to a new host
**Support bundle**

[harvester-supportbundle_c77a57eb-bc3d-4ed3-9037-6f9da0c0e2f6_2021-06-28T23-07-22Z.zip](https://github.com/harvester/harvester/files/6729674/harvester-supportbundle_c77a57eb-bc3d-4ed3-9037-6f9da0c0e2f6_2021-06-28T23-07-22Z.zip)

**Environment:**
 - Harvester ISO version: master-158a35d3-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal on DL160

**Additional context**
![Greenshot 2021-06-28 16 06 27](https://user-images.githubusercontent.com/83787952/123715701-b3680a00-d82d-11eb-88b9-f3af3250b092.png)
![Greenshot 2021-06-28 16 06 35](https://user-images.githubusercontent.com/83787952/123715703-b4993700-d82d-11eb-98f8-e6ce2587686e.png)
![Greenshot 2021-06-28 16 06 41](https://user-images.githubusercontent.com/83787952/123715705-b531cd80-d82d-11eb-8fb2-a527340980db.png)

**Comment by weihanglo** [comment]
<strike>Duplicate? https://github.com/harvester/harvester/issues/913</strike>

**Comment by yasker** [comment]
Not sure if there is anything we can do for this release. Need to investigate first.

**Comment by FrankYang0529** [comment]
For this issue and https://github.com/harvester/harvester/issues/983, Pods are stuck in the `Terminating` state when we turn off a node. This is also including Longhorn Pods. We can't gracefully remove Pods. Even if we set `--grace-period=0`, Pods still can't be removed. Also, there is no finalizer for VM Pods, so deleting finalizers doesn't work. We can only delete Pods by adding `--force`.

For a workable way, I think we should also check the `Ready` status in `VirtualMachineInstance`. If the `Ready` status is `False`, we show the `NotReady` state for the VM and hide the migration button. We can give a hint for users if they want to reschedule VMs, we can force delete Pods.

ref: https://containersolutions.github.io/runbooks/posts/kubernetes/pod-stuck-in-terminating-state/

cc @weihanglo @guangbochen

**Comment by guangbochen** [comment]
I think the expected behaviors would be:
- VMs should report unhealthy status
- VMs can recover on the other nodes(automatically after a period of time, or can be done manually by users).

Can we also check if adding the following configs to the apiserver would mitigate the issue, thanks?
https://github.com/kubernetes/kubernetes/issues/55713#issuecomment-922168158

**Comment by FrankYang0529** [comment]
> I think the expected behaviors would be:
> 
> * VMs should report unhealthy status
> * VMs can recover on the other nodes(automatically after a period of time, or can be done manually by users).
> 
> Can we also check if adding the following configs to the apiserver would mitigate the issue, thanks? [kubernetes/kubernetes#55713 (comment)](https://github.com/kubernetes/kubernetes/issues/55713#issuecomment-922168158)

After reading the https://github.com/kubernetes/kubernetes/issues/55713#issuecomment-922168158 and trying the config. I think their issue is Pods stay in `Running` status when a node is down. In our case, we can see Pods turn to `Terminating` status without the config, but they can't be really terminated.

I think the root cause is that the `VirtualMachineInstance` controller creates the new Pod only if the prior one has been removed. I tried to deploy the following Deployment on a 2-node environment and turn off 1 node. We can see that the `Deployment` controller creates a new Pod even if the prior one is stuck in `Terminating` status. 

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
```

```
> kubectl get pods -w
NAME                               READY   STATUS    RESTARTS   AGE     IP           NODE               NOMINATED NODE   READINESS GATES
nginx-deployment-9d84cfbd9-b9vmk   1/1     Running   0          60s     10.52.1.35   harvester-node-1   <none>           <none>
nginx-deployment-9d84cfbd9-n48hq   1/1     Running   0          35s     10.52.0.84   harvester-node-0   <none>           <none>
virt-launcher-vm-d99pr             1/1     Running   0          7m16s   10.52.1.34   harvester-node-1   <none>           <none>

virt-launcher-vm-d99pr             1/1     Terminating   0          8m6s    10.52.1.34   harvester-node-1   <none>           <none>
nginx-deployment-9d84cfbd9-b9vmk   1/1     Terminating   0          110s    10.52.1.35   harvester-node-1   <none>           <none>

nginx-deployment-9d84cfbd9-jkzr2   0/1     Pending       0          0s      <none>       harvester-node-0   <none>           <none>
nginx-deployment-9d84cfbd9-jkzr2   0/1     ContainerCreating   0          0s      <none>       harvester-node-0   <none>           <none>
nginx-deployment-9d84cfbd9-jkzr2   1/1     Running             0          1s      10.52.0.85   harvester-node-0   <none>           <none
```

If we want to solve the issue from the backend, we may need some enhancement from upstream. For example, the `VirtualMachineInstance` controller creates a new Pod when the old one is in `Terminating` status instead of waiting until Pod is really terminated. I will file an issue in KubeVirt for this.

For "VMs should report unhealthy status", we may need to track the `Ready` field in the frontend, because there is no `Unhealthy` in the `Phase` field [(ref)](https://github.com/kubevirt/kubevirt/blob/fcb238bd6b221f6e70ddd9ea7a2905d218020c32/staging/src/kubevirt.io/client-go/apis/core/v1/types.go#L633-L659). `VirtualMachineInstance` controller tracks whether VM can work by the `Ready` field.

```
> kubectl get vmi
NAME   AGE   PHASE     IP           NODENAME           READY
vm     45m   Running   10.52.1.48   harvester-node-1   False
```

**Comment by FrankYang0529** [comment]
https://github.com/kubevirt/kubevirt/issues/6682

**Comment by gitlawr** [comment]
Are the terminating pods waiting for volume detachment?
There is a related Longhorn setting: https://longhorn.io/docs/1.2.2/high-availability/node-failure/#longhorn-pod-deletion-policy-when-node-is-down
However, Longhorn only deals with statefulset/deployment pods.
If it's the same cause, we may request support for "all" policy or implement in similar way on Harvester side.

**Comment by FrankYang0529** [comment]
> Are the terminating pods waiting for volume detachment? There is a related Longhorn setting: https://longhorn.io/docs/1.2.2/high-availability/node-failure/#longhorn-pod-deletion-policy-when-node-is-down However, Longhorn only deals with statefulset/deployment pods. If it's the same cause, we may request support for "all" policy or implement in similar way on Harvester side.

No, I don't see detachment failed events and log in controller-manager.

```
> kubectl get events -w
# ...
0s          Normal    NodeNotReady                   node/harvester-node-1                                  Node harvester-node-1 status is now: NodeNotReady
1s          Warning   NodeNotReady                   pod/virt-launcher-vm-h7cj9                             Node is not ready
0s          Normal    TaintManagerEviction           pod/virt-launcher-vm-h7cj9                             Marking for deletion Pod default/virt-launcher-vm-h7cj9
0s          Normal    NodeUnresponsive               node/harvester-node-1                                  virt-handler is not responsive, marking node as unresponsive
```

```
> kubectl logs -n kube-system kube-controller-manager-harvester-node-0
I1027 09:11:42.763243       1 reconciler.go:219] attacherDetacher.DetachVolume started for volume "pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374") on node "harvester-node-0"
I1027 09:11:42.766160       1 operation_generator.go:1483] Verified volume is safe to detach for volume "pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374") on node "harvester-node-0"
I1027 09:12:21.736164       1 event.go:291] "Event occurred" object="harvester-node-1" kind="Node" apiVersion="v1" type="Normal" reason="NodeNotReady" message="Node harvester-node-1 status is now: NodeNotReady"
I1027 09:12:21.745522       1 event.go:291] "Event occurred" object="cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-0" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.752877       1 event.go:291] "Event occurred" object="harvester-system/harvester-webhook-5955cd87bb-jrf6g" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.778726       1 event.go:291] "Event occurred" object="kube-system/rke2-canal-pbg7z" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.797224       1 event.go:291] "Event occurred" object="longhorn-system/longhorn-csi-plugin-64f94" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.809822       1 event.go:291] "Event occurred" object="harvester-system/harvester-node-disk-manager-99sqk" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.828870       1 event.go:291] "Event occurred" object="longhorn-system/instance-manager-r-b8a9387e" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.840772       1 event.go:291] "Event occurred" object="longhorn-system/backing-image-manager-c00e-8699" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.849240       1 event.go:291] "Event occurred" object="harvester-system/virt-handler-vx7jv" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.863217       1 event.go:291] "Event occurred" object="harvester-system/harvester-d544ddb6f-fkk4p" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.877776       1 event.go:291] "Event occurred" object="longhorn-system/instance-manager-e-08fd6612" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.888400       1 event.go:291] "Event occurred" object="default/virt-launcher-vm-h7cj9" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.900758       1 event.go:291] "Event occurred" object="harvester-system/harvester-network-controller-w9hcm" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.915034       1 event.go:291] "Event occurred" object="longhorn-system/longhorn-manager-vfv2x" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.922903       1 event.go:291] "Event occurred" object="longhorn-system/engine-image-ei-d4c780c6-bwj2t" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.935791       1 event.go:291] "Event occurred" object="kube-system/kube-multus-ds-tfxk9" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.940323       1 event.go:291] "Event occurred" object="cattle-monitoring-system/rancher-monitoring-prometheus-node-exporter-jhtnk" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:21.978320       1 event.go:291] "Event occurred" object="kube-system/kube-proxy-harvester-node-1" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:22.078719       1 event.go:291] "Event occurred" object="cattle-system/rancher-7fc9c56c78-dlfps" kind="Pod" apiVersion="v1" type="Warning" reason="NodeNotReady" message="Node is not ready"
I1027 09:12:26.952973       1 operation_generator.go:483] DetachVolume.Detach succeeded for volume "pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-23c4d6f1-a6d1-4612-b4fc-cc410a350374") on node "harvester-node-0"
```

**Comment by FrankYang0529** [comment]
From https://github.com/kubevirt/kubevirt/issues/6682#issuecomment-952988715, we can not resolve this issue from upstream.

If we still want to reschedule Pods on an unhealthy node to other nodes, we may have a setting like Longhorn `Pod deletion policy when a node is down` to trigger force deletion. We can have options like `None` and `VirtualMachineInstance` for the current situation. WDYT? Thank you. @gitlawr @guangbochen @weihanglo

**Comment by guangbochen** [comment]
IMO, I would recommend adding the following changes:
1. [UI] check if the VMI `Ready` status is true or not, if not set the VM status to `NotReady` @WuJun2016 
2. Add `VM Deletion Policy when the Node is Down` on the Harvester side and prefer to add deletion time period with option from 0 to 5 minutes.

**Comment by lanfon72** [comment]
Verified VM's state will be changed to `Not Ready` when host goes down.

[states of Hosts]
![image](https://user-images.githubusercontent.com/5169694/141085982-8355e906-89a2-44e2-94ea-445c67ceae29.png)

[states of VMs]
![image](https://user-images.githubusercontent.com/5169694/141086052-8ad91638-b321-4439-90e7-385af7ee9856.png)


Test Information
----
* Environment: **qemu/KVM** 2 nodes
* Harvester Version: **master-119c2c48-head**
* **ui-source** Option: **External**

### Verify Steps:
1. Install Harvester with 2+ nodes
2. Create an Image for VM creation
3. Create a VM and wait until state becomes **Running**
4. Reboot the node which hosting the VM
5. Node's _State_ should be `In Progress` in _**Hosts**_ page
6. VM's _State_ should be `Not Ready` in _**Virtual Machines**_ page

**Comment by lanfon72** [comment]
VM can't bring back after host is back, it would be tracking in #1360

**Comment by Erick-shi** [comment]
> [lanfon72](/lanfon72)

hi, what's the dashboard you use? It's cool.
