### ISSUE TITLE
[BUG] Can not disable VLAN network if the slave of harvester-br0 is a bond interface

### ISSUE THREAD

**Issue by yaocw2020** [harvester/harvester#984]
**Describe the bug**

Can not disable VLAN network if the slave of harvester-br0 is not physical NIC, such as NIC of bond type.
```
I0629 03:54:04.367154       1 controller.go:105] node network configuration 10.130.186.14-vlan has been deleted
I0629 03:54:04.368422       1 controller.go:205] ignore link not found error, details: slave of harvester-br0 not found
```

**To Reproduce**
1. Enable VLAN network with a NIC of type bond.
2. Disable VLAN network.

**Expected behavior**

Disable VLAN network successfully.

**Support bundle**

**Environment:**
 - Harvester ISO version: v0.2
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): Baremetal with Dell PowerEdge R630

**Additional context**

**Comment by yaocw2020** [comment]
To test:
- Repalce the image tag of the Harvester Network Controller daemonset as the `master-head`.
- Login host to create a bond interface `bond0` with the following shell command.
  ```
  ip link add bond0 type bond mode 802.3ad
  ip link set <NIC-1> down
  ip link set <NIC-2> down
  ip link set <NIC-1> master bond0
  ip link set <NIC-2> master bond0
  ip link set bond0 up
  ```
- Enable VLAN with default NIC `bond0`. Check the master of bond0 with the following shell command. It should be `harvester-br0`.
   ```
   ip a show dev bond0
   ```
- Disable VLAN. Check the master of bond0 with the following shell command. It should have no master.
   ```
   ip a show dev bond0
   ```

**Comment by ldevulder** [comment]
I tested with version `master-902bee60-head`.
After VLAN activation I have this state for `bond0`:
```
# ip a show dev bond0
54: bond0: <BROADCAST,MULTICAST,MASTER,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc noqueue master harvester-br0 state UP group default qlen 1000
    link/ether 52:54:00:50:d2:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.144/24 brd 192.168.122.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe50:d21b/64 scope link 
       valid_lft forever preferred_lft forever
```
So the master of `bond0` is `harvester-br0`.

After disabling VLAN I have this state:
```
# ip a show dev bond0
54: bond0: <BROADCAST,MULTICAST,MASTER,DYNAMIC,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 52:54:00:50:d2:1b brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.144/24 brd 192.168.122.255 scope global bond0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe50:d21b/64 scope link 
       valid_lft forever preferred_lft forever
```
And there is no master on `bond0`, as expected. I also don't have any error messages in `/var/log/message`.

Issue closed.
