### ISSUE TITLE
[BUG] Manually attached volumes don't show up in Volume page after restore

### ISSUE THREAD

**Issue by weihanglo** [harvester/harvester#987]
### Describe the bug

After a successful backup, when we try to restore a VM attached with manually attached volumes (a.k.a volume added via "Add Existing Volume" button), the volumes won't show up in  Volume page nor VM's volume section.

It may due to these lines, which creating PersistentVolumeClaims instead of DataVolumes if the volume in backup content cannot match any in DataVolumeTemplate. 

https://github.com/harvester/harvester/blob/46ee2188688b6910cee7e01b66e5935f7220ec6c/pkg/controller/master/backup/restore.go#L546-L557

After skimming the logic, existing volumes are always restored as PVCs since all manually attached volume won't appear in `vm.spec.DataVolumeTemplates`. This bug (or feature?) also affects hotplug volumes feature #283 

### To Reproduce

1. Manually create a volume from the Web UI "Volume" page
2. Create a VM with a root disk and add the volume created in previous step as second disk
3. Take a backup on the VM (both S3 and NSF are ok as long as they succeed)
4. Restore a new VM from the backup
5. 💥 Navigate to the VM page > Volume section. Only the root disk shows up there.
6. 💥 Navigate to "Volume" page. Only volume associated with the root disk shows up there.

### Expected behavior

After a restore, manually attached volumes show up in Volume page as well as VM's volume section.

### Environment

- Harvester ISO version: 46ee218 from harvester master

**Comment by guangbochen** [comment]
since we are directly replacing the CDI data volumes with PVC, let's review this after PR  https://github.com/harvester/harvester/pull/1066 is merged.

**Comment by weihanglo** [comment]
Confirmed that thisl issue has been resolved on the ISO from 82506f5. Closed.

<details>

<summary>Click to see screenshots</summary>

### List of volumes after restore

![image](https://user-images.githubusercontent.com/14314532/135787036-7e2c698e-4cc2-4cea-bfff-4962118a64b5.png)


### Volumes of original VM 


![image](https://user-images.githubusercontent.com/14314532/135787102-1ce64df0-523e-4b04-8431-6756608127a4.png)

### Volumes on restored VM

![image](https://user-images.githubusercontent.com/14314532/135787110-b195d31d-990d-483e-8e74-4fe679e5ed7f.png)

</details>
