### ISSUE TITLE
[FEATURE] backup VM required metadata to the external storage server

### ISSUE THREAD

**Issue by guangbochen** [harvester/harvester#988]
**Is your feature request related to a problem? Please describe.**
Currently, only the VM volumes will be backup to the external storage server, we should also save the VM YAML to the external storage server so that it can be redeployed to the other cluster.

**Describe the solution you'd like**
- [x] store the VM metadata to the external storage server

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by yasker** [comment]
Those can be set using the label in the Backup.

**Comment by FrankYang0529** [comment]
## Test plan

### Case 1 - Sync VMBackup Metadata back.

* Setup an NFS/S3 backup target.
* Create a VM `vm`.
* Modify a file like `tmp.txt` and input `123` in it.
* Create a VM Backup `backup1`.
* Modify a file like `tmp.txt` and change content to `456`.
* Create a VM Backup `backup2`.
  * Check associated VolumeSnapshot / VolumeSnapshotContent/ LH Backup exist.
  * Check `default-backup1.cfg` and `default-backup2.cfg` are in the backup target.
  * Check `LonghornBackupName` exists in VM Backup `backup1` and `backup2`.
  * Check `LonghornBackupName` in CR `backup1` and `backup2` is same as `default-backup1.cfg` and `default-backup2.cfg` in backup target.
* Change backup target to another NFS/S3 backup target.
* Delete the VM Backup `backup1` and `backup2` and VM `vm`.
  * Check associated VolumeSnapshot / VolumeSnapshotContent / LH Backup are deleted.
  * Check `default-backup1.cfg` and `default-backup2.cfg` are still in the original backup target.
* Change backup target back.
  * Check VMBackup `backup1` and `backup2` and associated VolumeSnapshot / VolumeSnapshotContent / LH Backup are created again.
* Restore `backup1` to `vm1`
  * Check whether the file has `123` in it.
* Restore `backup2` to `vm2`
  * Check whether the file has `456` in it.

### Case 2 - Delete VM Backup should delete the remote file.

* Setup an NFS/S3 backup target.
* Create a VM and create a VM Backup `backup1`.
  * Check whether `default-backup1.cfg` is in the backup target.
* Delete the VM Backup.
  * Check whether `default-backup1.cfg` is deleted in the backup target.

### Case 3 - Sync VM Backup to a fresh cluster
* Create a cluster 1 and follow Case 1 to create VM Backup `backup1` and `backup2`.
* Create a cluster 2 and create VirtualMachineImage with the same name as cluster 1. (BackingImage and StorageClass must also be the same name as cluster 1)
* Set the same backup target to cluster 2 as in cluster 1.
  * Check VM Backup `backup1` and `backup2` can be synced back.
  * Check associated LH Backup / VolumeSnapshot / VolumeSnapshotContent are created.
* Restore VM Backup `backup1` and `backup2` to new VMs.
  * Check VMs can be started.
  * Check data in VMs is the same as VM Backup.

**Comment by lanfon72** [comment]
@FrankYang0529 verified not work as expected.
Failed in case 1, switch back to original backup-target with those errors:
- Backups reload failed, there should have 2 backups 
![image](https://user-images.githubusercontent.com/5169694/144395668-0419174a-c80b-4728-bba9-fa84dbc96084.png)
![image](https://user-images.githubusercontent.com/5169694/144396725-1e548439-8fd3-453f-9595-56aae45152e7.png)

- Generate support bundle stuck
![image](https://user-images.githubusercontent.com/5169694/144396983-ba1fef95-68f7-427a-ae2d-dfaef97e7310.png)

In short, after change the backup-target back, whole dashboard become unstable and crash frequently.
![image](https://user-images.githubusercontent.com/5169694/144397841-ec831051-32a4-4c03-ba60-6ae8f257ac00.png)


Test Information
----
* Environment: **qemu/KVM** 3 nodes
* Harvester Version: **v1.0.0-rc1**
* **ui-source** Option: **Auto**
* Backup-target A: 192.170.0.254 (pxe-server on kvm)
* Backup-target B: 10.84.44.120 (pxe-server on Provo, bare metal)

### Verify Steps:
Follow the instruction of Case 1 in https://github.com/harvester/harvester/issues/988#issuecomment-978898179

**Comment by lanfon72** [comment]
I tested on **master-1e042e04-head** (the last version before rc1) after verify #1086 yesterday, same behavior as errors above.
Backup-target works correctly, but the metadata probably had something missed.

**Comment by FrankYang0529** [comment]
@lanfon72 do you keep the environment? If yes, may you help me get the following content?  Thank you.

* Content in backup files `<namespace>-<name>.cfg`
* VolumeSnapshot resources: `kubectl get volumesnapshot -A`
* VolumeSnapshotContent resources: `kubectl get volumesnapshotcontent -A`
* LH Backup resources: `kubectl get backup -A`

**Comment by lanfon72** [comment]
[cfgs.zip](https://github.com/harvester/harvester/files/7641310/cfgs.zip)
![image](https://user-images.githubusercontent.com/5169694/144409222-fda672f2-0993-42f5-b482-feaa3abcf476.png)

**Comment by FrankYang0529** [comment]
@guangbochen I would like to do some enhancements to prevent remote data is deleted unexpectedly.

1. Although we have `blockOwnerDeletion` in VolumeSnapshot, it is not effective if we don't specify `--cascade=foreground` when we delete VMBackup. I have tried to stop harvester-controller and deleted the finalizer in VMBackup. If we run `kubectl delete vmbackup <vm-backup-name> --cascade=foreground`, VMBackup will not be deleted if VolumeSnapshot and VolumeSnapshotContent are still existent.
Ref: https://github.com/kubernetes/kubernetes/issues/86509#issuecomment-749176440
2. With the improvement above, we can detect whether there is VMBackup in progress or deleting in Backup Target validation. If yes, we stop users to change Backup Target.

WDYT? Thank you.

**Comment by guangbochen** [comment]
sure, this is LGTM and will need to coordinate with the UI team to add the `--casade=foreground` option while deleting the VMBackup, cc @WuJun2016

**Comment by n313893254** [comment]
Hi, @FrankYang0529, Do you know how to add `--casade=foreground` from the API side.  Is the URL looks like `/v1/harvester/harvesterhci.io.virtualmachinebackups/default/test?propagationPolicy=Foreground`?

**Comment by FrankYang0529** [comment]
> Hi, @FrankYang0529, Do you know how to add `--casade=foreground` from the API side. Is the URL looks like `/v1/harvester/harvesterhci.io.virtualmachinebackups/default/test?propagationPolicy=Foreground`?

From [Kubernetes article](https://kubernetes.io/docs/tasks/administer-cluster/use-cascading-deletion/#use-foreground-cascading-deletion), I think `propagationPolicy=Foreground` is correct.

**Comment by lanfon72** [comment]
Verified following test cases:
- [x] Sync VMBackup metadata back (swithing between NFS and S3)
- [x] Delete VM Backup will delete those files storing in remote target
- [ ] Sync VM backup to a fresh cluster

For unchecked test cases, please check details in Additional Content.

Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-3d096946-head**
* **ui-source** Option: **Auto**

### Verify Steps:
- follow the Test Plan https://github.com/harvester/harvester/issues/988#issuecomment-978898179
- VM image: http://download.opensuse.org/repositories/Cloud:/Images:/Leap_15.3/images/openSUSE-Leap-15.3.x86_64-NoCloud.qcow2
- Using Minio as the compatible alternative for S3 backup

### Additional Content
- For 2nd backup, data will lost unless power off the VM. (it not affect this feature)
- For reload backup data in another cluster, tested in the same version **3d096946** and newer version (**3d096946** then **5e8d9764**) with same error.
  1. first time setup _backup-target_, **Backups** loads and able to **Restore-New**, but the new VM stuck on _Creating_, Volume stuck on _Pending_ state.
  2. switch to empty S3 or another NFS backup-target, the whole system broken. (as video records)

https://user-images.githubusercontent.com/5169694/146398335-54d02bf3-2269-4c94-a02d-390e9bfe977d.mp4

https://user-images.githubusercontent.com/5169694/146398382-025c3f36-9147-4a41-b17a-5b3a4f65fd2a.mp4

**Comment by FrankYang0529** [comment]
Hi @lanfon72, may I know how do you create the image in the new cluster? We need to have the same BackingImage and StorageClass name as the old cluster, so I create an image by applying the following YAML. After the image download finish, I change backup target and restore VM. I can get expected data in VM.

```
apiVersion: harvesterhci.io/v1beta1
kind: VirtualMachineImage
metadata:
  name: image-rxbsq
  namespace: default
spec:
  displayName: focal-server-cloudimg-amd64.img
  pvcName: ""
  pvcNamespace: ""
  sourceType: download
  url: https://cloud-images.ubuntu.com/focal/20211216/focal-server-cloudimg-amd64.img
status:
  storageClassName: longhorn-image-rxbsq
```

**Comment by lanfon72** [comment]
@FrankYang0529, I guess it is the root cause that I didn't upload image with the name which VM was using.
(as the test case not require that, so I didn't test that scenario)

Let me test it based on the scenario, will we add some caveats for the requirement?

**Comment by FrankYang0529** [comment]
> 

Yes, we will add it to the document. Thank you.

**Comment by lanfon72** [comment]
Verified the case 3 is work correctly with some caveats, updated in _**verify steps**_.
@FrankYang0529 please update document based on the _**verify steps**_, thanks


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-3d096946-head**
* **ui-source** Option: **Auto**

### Verify Steps:
1. setup **backup-target** in cluster B
2. **Backup Targets** in _Backups_ should show `Ready` state for all backups.  (this will take few mins depends on network connection)
3. Create image for backup
    1. The image **MUST** use the same `storageClassName` name as the backup.
    2. `storageClassName` can be found in backup's `volumeBackups` in the YAML definition.
    3. `storageClassName` can be assigned by `metadata.name` when creating image via YAML.
       for example, when you assign `metadata.name` as `image-dgf27`, the `storageClassName` will be named as `longhorn-image-dgf27`
4. Restore backup to new VM
5. VM should started successfully
6. VM should contain those data that it was taken backup


### Additional Content
- Check `storageClassName` in backup's YAML
![image](https://user-images.githubusercontent.com/5169694/146515296-355432a7-2167-4d5f-9d60-0f490406e5f3.png)
- Create Image with assign `metadata.name`
![image](https://user-images.githubusercontent.com/5169694/146515663-a35335d0-8873-4b41-92cd-6e7b9cb1f4bb.png)
![image](https://user-images.githubusercontent.com/5169694/146515739-4160453a-4afe-474e-8f5b-5453ae8c61b6.png)

- Image Created with the specific `storageClassName`
![image](https://user-images.githubusercontent.com/5169694/146515515-dc84eb5f-384d-408e-a7b4-6a51aa31eaa9.png)
