### ISSUE TITLE
[Bug] Stop action can be click when the VM is "off" state

### ISSUE THREAD

**Issue by n313893254** [harvester/harvester#989]
**Describe the bug**
The Stop action menu is clickable when the VM is "off" state, and after clicking it, the console is throwing a network error.

![image.png](https://images.zenhubusercontent.com/59db4297b0222d5de47ad632/837bd592-bdce-4275-af44-eac75a1bb975)

**To Reproduce**
1. Create a standard VM.
2. Try to stop the VM. wait for it to the off state.
3. You can see the stop action is clickable.

**Expected behavior**
"stop" action should not show in the action menu when the VM is "off" state.

**Environment:**
 - Harvester version: `v0.2.0-rc5`

**Comment by juadk** [comment]
Also reproducible with the last master branch version: `master-46ee2188-head`

**Comment by noahgildersleeve** [comment]
Tested in harvester master-07efe71c-head. Still have option to stop off VM.
![Greenshot_2021-07-13_16_03_52](https://user-images.githubusercontent.com/83787952/125536197-9abad8e9-e15e-4641-8870-2f58ebfbedad.jpg)

**Comment by weihanglo** [comment]
@noahgildersleeve 
master-07efe71c-head does not include commit 6ae8d8e, which is exactly that fix.

**Comment by noahgildersleeve** [comment]
Ah, then @weihanglo. That was merged into master correct? I just did a deploy off of master about an hour or so ago.

**Comment by noahgildersleeve** [comment]
I see. The build I did a deploy off of was from yesterday, but before you merged it into master. I'll check it after it goes through.

**Comment by noahgildersleeve** [comment]
Tested in master-6ae8d8ee-head. Verified as fixed.
