### ISSUE TITLE
[BUG] Host goes unavailable when deleted

### ISSUE THREAD

**Issue by noahgildersleeve** [harvester/harvester#991]
**Describe the bug**

When you delete a host from the UI it doesn't get removed and goes into unavailable status
**To Reproduce**
1. Create a 4 node cluster
2. Create some VMs on one of the nodes
3. Delete a node that doesn't have any VMs on it

**Expected behavior**

The host should delete
**Support bundle**

[harvester-supportbundle_bf0fe65b-3289-4a27-b0bd-6593c876c7c3_2021-07-01T16-13-41Z.zip](https://github.com/harvester/harvester/files/6749661/harvester-supportbundle_bf0fe65b-3289-4a27-b0bd-6593c876c7c3_2021-07-01T16-13-41Z.zip)

**Environment:**
 - Harvester ISO version: master-46ee2188-head
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630): bare metal DL160

**Additional context**
![Greenshot 2021-07-01 09 10 26](https://user-images.githubusercontent.com/83787952/124203422-8ae04a00-da91-11eb-8cdd-bcbfed3b59cb.png)

**Comment by gitlawr** [comment]
The deletion is blocked by the finalizer
```
metadata:
  deletionTimestamp: "2021-07-01T16:09:37Z"
  finalizers:
  - wrangler.cattle.io/node
```

The workaround is removing the finalizers field of the node resource.

K3S issue: https://github.com/k3s-io/k3s/issues/2669

We can wait for the upstream fix.

**Comment by gitlawr** [comment]
Fixed in the upstream

**Comment by FrankYang0529** [comment]
## Test info

* Verified version: v0.3.0-rc1

## Test cases

* Delete a node which doesn't have VMs on it, but there are VMs on other nodes.
  * [x] Verify the node can be deleted on dashboard
  * [x] Use `kubectl get nodes`. The node is not in the list.
