### ISSUE TITLE
[BUG] VM keep starting if enable namespace ResourceQuota

### ISSUE THREAD

**Issue by futuretea** [harvester/harvester#999]
**Describe the bug**

![image](https://user-images.githubusercontent.com/15064560/124441955-d6a33400-ddae-11eb-8f7e-18fea3fe5089.png)

**To Reproduce**
1. create a  namespace test 
2. configure namespace test's ResourceQuota on Rancher
3. create vm on namespace test

**Expected behavior**

vm running

**Support bundle**

**Environment:**
 - Harvester ISO version: 
 - Underlying Infrastructure (e.g. Baremetal with Dell PowerEdge R630):

**Additional context**

**Comment by futuretea** [comment]
We also need to update default vm templates

**Comment by FrankYang0529** [comment]
I think after PR https://github.com/harvester/harvester/pull/1543, we don't have this issue. We specify `resources.requests` and `resources.limits` for CPU and memory. I can't reproduce this issue in Harvester `master-1be9cb5e-head`.

**Comment by lanfon72** [comment]
Can not reproduce this bug.
The VM can be created which exceed resource quota and start successfully.


Test Information
----
* Environment: **qemu/KVM 3 nodes**
* Harvester Version: **master-a67f96d0-head**
* **ui-source** Option: **Auto**
* Rancher Version: **v2.6.3**

### Verify Steps:
1. Install Harvester with any nodes
2. Install Rancher and import Harvester in **Virtualization Management**
3. Navigate to **Projects/Namespaces** page (from Virtualization Management)
4. Create Project then Create resource limited namespace `test`
5. Create Image for VM creation
6. Create VM based on `test` namespace and exceed the resource limitation
7. VM should not keep starting
